### ISSUE TITLE
Issue with "HTMLElement.focus()": focusin/focusout not listed in related events section

### ISSUE THREAD

**Issue by stacker60** [mdn/content#10008]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus

#### What information was incorrect, unhelpful, or incomplete?
The Related Events section doesn't list focusin or focusout events which are very much related. 

#### Specific section or headline?
Related Events

#### What did you expect to see?
Focusin and focusout

#### Did you test this? If so, how?
Yes, I read the section.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlelement/focus`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/focus/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by abdelrazek-alaa** [comment]
well, I just put this issue on my to-do list for tomorrow's contributions.
but I have a question.
Related Events seems to be in the left sidebar.
and the left sidebar itself isn't included in the page index.md
How do I get to the left sidebar to fix this? 
thanks :slightly_smiling_face:

**Comment by SphinxKnight** [comment]
Since the sidebar is the same for all the HTML DOM pages, I think it would be better to add a "See also" section at the end of the page to link to those pages ([`focusout`](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event), [`focusin`](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusin_event)).  As per `blur()`, it already is in the sidebar under *Methods*.

**Comment by abdelrazek-alaa** [comment]
> Since the sidebar is the same for all the HTML DOM pages, I think it would be better to add a "See also" section at the end of the page to link to those pages ([`focusout`](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event), [`focusin`](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusin_event)). As per `blur()`, it already is in the sidebar under _Methods_.

that sounds like a great idea 👍️ , thank you very much 🙂
since I just made my today's contribution. I will work on that tomorrow :slightly_smiling_face: 
I'm grateful to you, thanks :slightly_smiling_face:
