### ISSUE TITLE
Issue with "Using the WebAssembly JavaScript API": 404 link

### ISSUE THREAD

**Issue by Lemmih** [mdn/content#10007]
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API

#### What information was incorrect, unhelpful, or incomplete?

The link to `dynamic linking` (https://webassembly.org/docs/dynamic-linking) is 404.

#### Specific section or headline?

In the `Multiplicity` section.

#### What did you expect to see?

I expected a link to a non-404 page.

#### Did you test this? If so, how?

I clicked on the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/using_the_javascript_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/using_the_javascript_api/index.md
* Last commit: https://github.com/mdn/content/commit/bbe7383371e67c90d2eb72f3899115ba4b5d4548
* Document last modified: 2021-10-11T10:56:41.000Z

</details>

**Comment by abdelrazek-alaa** [comment]
@Rumyra
I've [reached out](https://github.com/WebAssembly/website/issues/253) to the WebAssembly team today.
and the problem has been solved :slightly_smiling_face: 
> Thanks for the report. Fixed / added a redirect to the proposal document.

**Comment by Lemmih** [comment]
👍
