### ISSUE TITLE
Issue with "Command line crash course": (short summary here please)

### ISSUE THREAD

**Issue by Eamonn-O-Flaherty** [mdn/content#10005]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line

#### What information was incorrect, unhelpful, or incomplete?
An example URL appeared to be incorrect

#### Specific section or headline?
"A slightly more complex example" headline

#### What did you expect to see?
This section refers to one URL being out of date and the next one being correct, but they are both the same URL... I think?

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/command_line`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. I suspect our flaw checker fixed up the old redirect text so it no longer redirects. I've had to modify this a bit so that does not happen again.
