### ISSUE TITLE
Issue with "performance.measure()": return type is from the "draft" spec

### ISSUE THREAD

**Issue by stewx** [mdn/content#10009]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure

#### What information was incorrect, unhelpful, or incomplete?
The information here is based on a draft version of the W3C spec and there is a discrepancy between the return values.

Official: https://www.w3.org/TR/user-timing/#measure-method
Draft: https://w3c.github.io/user-timing/#dom-performance-measure

#### Specific section or headline?
Return value. It says "entry" but it should be "undefined".

#### What did you expect to see?
undefined

#### Did you test this? If so, how?
It crashed our app in production because we were expecting it to return the "entry" in Firefox, like the MDN page says, and it doesn't.

Firefox returns undefined (which is in the W3C spec) which surprised me because the MDN page says it returns the measurement entry.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/performance/measure`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/performance/measure/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by wbamberg** [comment]
Closing per https://github.com/mdn/content/pull/10235#issuecomment-964726350 - this should be handled as a browser compat issue IMO.
