### ISSUE TITLE
Issue with "Test your skills: Strings": (short summary here please)

### ISSUE THREAD

**Issue by mdnIsCool** [mdn/content#10036]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Strings

#### What information was incorrect, unhelpful, or incomplete?

In the strings1 live code, in the quoteStart string there is no escape sequence for the apostrophe in the word don't so the live example only returns SyntaxError: Unexpected identifier.

#### Specific section or headline?

Strings 1

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/test_your_skills_colon__strings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Strings
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/test_your_skills_colon__strings/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by Rumyra** [comment]
Thanks @singla-shivam :) Yes the above is correct @mdnIsCool I hope the explanation helps 👍
