### ISSUE TITLE
Issue with CSS ":playing" doc: Specifications and Browser Compatibility sections are missing

### ISSUE THREAD

**Issue by RolandHeinze** [mdn/content#10035]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:playing

#### What information was incorrect, unhelpful, or incomplete?
The "Syntax" is displayed to be `:checked` but it should be `:playing`. The "Specifications" are missing but there exist specification data at [Selectors Level 4 Specification](https://www.w3.org/TR/selectors-4/#video-state).

#### Specific section or headline?
Headlines "Syntax" and "Specification".

#### What did you expect to see?
"Syntax":  `:playing`
"Specification": [Selectors Level 4 Specification](https://www.w3.org/TR/selectors-4/#video-state)

#### Did you test this? If so, how?
I looked it up. No tested were needed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_playing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:playing
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_playing/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by sideshowbarker** [comment]
The `:checked` problem in the Syntax section has been fixed, I think.

But the article still lacks content in the Specifications and Browser Compatibility sections — and that’s because there is not yet any data in BCD for the `:playing` selector.

**Comment by teoli2003** [comment]
Is there any web browser implementing this, or is this an example of a feature documented too early?

**Comment by NiedziolkaMichal** [comment]
@teoli2003 Safari does. I am not sure since which version though, as I couldn't find it in [release notes](https://developer.apple.com/documentation/safari-release-notes).

**Comment by NiedziolkaMichal** [comment]
[:paused](https://developer.mozilla.org/en-US/docs/Web/CSS/:paused) is implemented on Safari too

**Comment by teoli2003** [comment]
So the solution here is to add both entries to mdn/browser-compatibility-data, and this issue will (about one week after the PR will be merged)

**Comment by sideshowbarker** [comment]
@RolandHeinze Thanks for raising this. I’ve opened https://github.com/mdn/browser-compat-data/pull/17136 with a fix that adds the necessary data to BCD.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

@NiedziolkaMichal

> Safari does. I am not sure since which version though, as I couldn't find it in [release notes](https://developer.apple.com/documentation/safari-release-notes).

Thanks for confirming that. Per https://github.com/WebKit/WebKit/commit/b64b4d1 it seems this shipped in Safari 15.4.

I tested with the test case at https://github.com/WebKit/WebKit/blob/main/LayoutTests/media/media-css-playing-paused.html to confirm.
