### ISSUE TITLE
chrome_settings_overrides improvements

### ISSUE THREAD

**Issue by rebloor** [mdn/content#10055]
## What page(s) did you find the problem on?

[chrome_settings_overrides](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_settings_overrides)

## What is the problem?

Page is not well align with other key pages? That is:

-    add an example row into the table (suggest using the homepage example)
-    move the 2 examples to an "Examples" section placed before the "Browser compatibility" section
-    replace the introductory description and 2 bullets with something similar to "Use the chrome_settings_overrides key to override the browser's home page and add a new search engine."

**Comment by Biki-das** [comment]
Would like to work on this

**Comment by hamishwillee** [comment]
Thanks @Biki-das - I've assigned to you!

**Comment by Biki-das** [comment]
@rebloor  which home page example are you talking about?

**Comment by rebloor** [comment]
@Biki-das I was referring to:
```
"chrome_settings_overrides" : {
  "homepage": "https://developer.mozilla.org/"
}
```

**Comment by Biki-das** [comment]
@rebloor and how do i use it further

**Comment by rebloor** [comment]
@Biki-das If you scan a few of the other manifest key pages you will see that the table providing basic information about the key includes Type, Mandatory, and Example sections. To align the content of this page's tabla with the others, add an Example section to the table using the homepage code.
