### ISSUE TITLE
Issue with "Introducing asynchronous JavaScript": (text says the why we can't use an object that is returned async directly in main thread is maybe it is not completely done)

### ISSUE THREAD

**Issue by usfstdd** [mdn/content#10051]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing

#### What information was incorrect, unhelpful, or incomplete?
in the example that suggest access to image.src and see how asyc operations work. the text says the reason why we get this error (TypeError: image is undefined; can't access its "src" property) is "You just can't guarantee that the async function will return before the browser has processed the sync block."
but the thing that i learn according other mdn documents is all async callbacks will added to event queue and will execute after pop off of last stack that is related to main thread.the good example of that is calling setTimeout with zero delay. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/introducing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/introducing/index.md
* Last commit: https://github.com/mdn/content/commit/d3294c26781ae6d0a7be8baabf060244215c7cc5
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by Josh-Cena** [comment]
This has been fixed via #12930
