### ISSUE TITLE
Issue with "Element.replaceChildren()": (Code example doesn't do anything)

### ISSUE THREAD

**Issue by Quo210** [mdn/content#10067]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren

#### What information was incorrect, unhelpful, or incomplete?
The example about transferring nodes, the buttons don't work.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren#transferring_nodes_between_elements

#### What did you expect to see?
Upon clicking the button the list should have moved to the other side.

#### Did you test this? If so, how?
I didn't rewrite the code, was simply browsing while studying and after I clicked the button nothing happened.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/replacechildren`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/replacechildren/index.md
* Last commit: https://github.com/mdn/content/commit/92942b07754b549f595c32e72440a0f0973893a9
* Document last modified: 2021-09-15T12:39:31.000Z

</details>

**Comment by wbamberg** [comment]
@AnilSeervi is right, I think, this example is working as intended.
