### ISSUE TITLE
Issue with "HTMLFormElement: submit event": Bubbles description is confusing

### ISSUE THREAD

**Issue by andrewnicols** [mdn/content#10069]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event

#### What information was incorrect, unhelpful, or incomplete?
> Bubbles: Yes (although specified as a simple event that doesn't bubble)

#### Specific section or headline?
Bubbles

#### What did you expect to see?
Information on what is meant here. It bubbles, but it doesn't? What is a Simple event and why doens't it bubble? How does it bubble yet not bubble?

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlformelement/submit_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlformelement/submit_event/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by ddbeck** [comment]
@Elchi3 Something perhaps of interest for your work on events.

**Comment by Josh-Cena** [comment]
This sentence no longer exists, so there should be no confusion now.
