### ISSUE TITLE
Issue with "<style>: The Style Information element": Confusing description for 'type' attribute

### ISSUE THREAD

**Issue by nikunj-glorywebs** [mdn/content#10106]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style

#### What information was incorrect, unhelpful, or incomplete?
In the **Attributes** section, in the description of the `type` attribute, there is a note saying "There is very little reason to include this attribute in modern web documents." , while in the **Browser compatibility** table, there is `title` attribute given on **thumb down icon** beside the `type` attribute with text "Deprecated. Not for use in new websites.". These are confusing. Are "modern web documents" and "new websites" same? (I think they are same.) Should one specify the `type` attribute or not?

#### Specific section or headline?
**Attributes** section and **Browser compatibility** table.

#### What did you expect to see?
First, internally, it needs to be cleared whether "modern web documents" and "new websites" are same or not. If they are different then details about how these are different should be described somewhere in the documentation, and reference should be provided in the `style` tag/element's page. If they are same then single identifying group of words needed to be used (either "modern web documents" or "new websites" or something else).

Documentation needs to clearly mention whether `type` attribute should be specified in the `style` tag or not (, and in "modern web documents" or "new websites" or old sites or anything else possible specifically).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/style/index.md
* Last commit: https://github.com/mdn/content/commit/775662998e66813a612e3ff27e02f2ada867bc17
* Document last modified: 2021-10-03T00:01:51.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing this issue: I created https://github.com/mdn/content/pull/10611 with a fix.
