### ISSUE TITLE
Issue with "tabs.getCurrent()": (it doesn't return undefined when called from a background script)

### ISSUE THREAD

**Issue by bingqiao** [mdn/content#10113]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/getCurrent

#### What information was incorrect, unhelpful, or incomplete?
`If you call it from a background script or a popup, it will return undefined.`

#### Specific section or headline?
In "Note"

#### What did you expect to see?
getCurrent works fine in background script. So I suspect this was meant to say:
`If you call it from a content script or a popup, it will return undefined.`

#### Did you test this? If so, how?
Tested in a Safari Web Extension

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/tabs/getcurrent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/getCurrent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/tabs/getcurrent/index.md
* Last commit: https://github.com/mdn/content/commit/629960fa07e15f2354d75daf14f149d4942539ec
* Document last modified: 2021-10-26T21:28:18.000Z

</details>

**Comment by rebloor** [comment]
I've tested this by modifying the background script in the tabs-tabs-tabs example and confirmed that it is undefined in that situation.
![image](https://github.com/mdn/content/assets/7352080/15620d4b-f7f2-410c-9286-98d926c1ff50)
The documentation is also consistent with the [Chrome documentation](https://developer.chrome.com/docs/extensions/reference/tabs/#method-getCurrent) and the fact that a background script isn't associated with a tab.
