### ISSUE TITLE
`MouseEvent.offset{X,Y}`: not actually experimental

### ISSUE THREAD

**Issue by nfreeze** [mdn/content#10120]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX

#### What information was incorrect, unhelpful, or incomplete?
I believe listing offsetX and offsetY as experimental is inaccurate considering that they have been supported in every major browser for several years. 

#### Specific section or headline?
Experimental: This is an experimental technology

#### What did you expect to see?
No warning about it being experimental

#### Did you test this? If so, how?
Yes. I referenced MDN's definition which deems a feature no longer experimental if it is supported in two or more major browsers.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mouseevent/offsetx`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mouseevent/offsetx/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Timmmm** [comment]
I found this weird too so I've made a PR to fix it. They're definitely not experimental.

**Comment by hamishwillee** [comment]
Done in #10220. This a slightly bigger change, and I'll have to go do a little more BCD work too.
