### ISSUE TITLE
[WebAPI] WebGL KHR_parallel_shader_compile not supported

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#10147]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Seems Firefox doesn't support this WebGL extension. I've already commented on the bug to check at which version support will happen. BCD is currently stating FF80 - so that will need to change

## Related Gecko bugs

[WebGL extension KHR_parallel_shader_compile doesn't appear to be supported](https://bugzilla.mozilla.org/show_bug.cgi?id=1736076)

**Comment by hamishwillee** [comment]
@Rumyra I'm on top of my issues now, so going to start work on this. Let me know if you need me to take any of the others - otherwise I will assume not.
