### ISSUE TITLE
[CSS] Support CSS cursor property on Android

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#10145]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

I wonder if this even made it into bcd to begin with, but without looking this should just be a bcd update

## Related Gecko bugs

[Support CSS cursor property on Android](https://bugzilla.mozilla.org/show_bug.cgi?id=1672609)

**Comment by hamishwillee** [comment]
For this specific feature you're right that it is just a BCD. But this is an opportunity to clean up some of the crap in https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Basic_User_Interface/Using_URL_values_for_the_cursor_property and also perhaps expand on what x and y values are in the API reference.

Status:
- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/13353
- [ ] Release note
- [ ] Docs - tidy [CSS `cursor`](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)
- [ ] Docs - Maybe delete [Using URL values for the cursor property](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Basic_User_Interface/Using_URL_values_for_the_cursor_property) - discussing in BCD query.
