### ISSUE TITLE
Issue with "Using the Notifications API": Requesting and setting the permission

### ISSUE THREAD

**Issue by KevinBurton** [mdn/content#10148]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

#### What information was incorrect, unhelpful, or incomplete?

The source code sets the permission only on condition of !('permission' in Notification). The online article doesn't mention setting the permission on the global object.

#### Specific section or headline?

Example request permission in https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

#### What did you expect to see?

I expected to see documentation on how to set the permission

#### Did you test this? If so, how?

Downloaded the todo app and ran it in Chrome.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/notifications_api/using_the_notifications_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/notifications_api/using_the_notifications_api/index.md
* Last commit: https://github.com/mdn/content/commit/8bc9a25846c2ecfe4e2c2c2a363fd2208f3a69ae
* Document last modified: 2021-10-13T06:21:42.000Z

</details>

**Comment by Jenna59** [comment]
@Rumyra I'm interested in this issue. Feel free to assign it to me.

**Comment by Josh-Cena** [comment]
This part is simply to support legacy browsers that do not have the `permission` property (namely, Chrome 20–31); such checks are common and there are other instances on this page. We don't feel like it's necessary to explain in content.
