### ISSUE TITLE
[Not Released] [Web API] Custom elements updates

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#10142]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

There are three bugs all pertaining to the same interface: `ElementInternals`, so I'm just creating one bug for all of them as I believe it'd be better to tackle them all at once. Might be a chunky bit of work, but will be easier on rel notes & bcd 👍 

## Related Gecko bugs

[Custom elements: implement form attribute of ElementInternals](https://bugzilla.mozilla.org/show_bug.cgi?id=1556362)
[Custom elements: implement labels for ElementInternals](https://bugzilla.mozilla.org/show_bug.cgi?id=1556373)
[Custom elements: implement setFormValue() for ElementInternals](https://bugzilla.mozilla.org/show_bug.cgi?id=1556449)

**Comment by hamishwillee** [comment]
Status - Still working this out

[Custom elements: implement form attribute of ElementInternals](https://bugzilla.mozilla.org/show_bug.cgi?id=1556362)
- [ ] Docs: 
   - [ ] [ElementInternals.form](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/form) already written -  review and update as needed (probably just fix to syntax box)
- [ ] BCD - TBD - but looks like just FF95 for custom elements
- [ ] dev-docs-complete
- [ ] Release note: ?

[Custom elements: implement labels for ElementInternals](https://bugzilla.mozilla.org/show_bug.cgi?id=1556373)
- [ ] Docs: [ElementInternals.labels](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/labels)
- [ ] BCD: TBD - but looks like just FF95 for custom elements
- [ ] dev-docs-complete:
- [ ] Release note: ?

[Custom elements: implement setFormValue() for ElementInternals](https://bugzilla.mozilla.org/show_bug.cgi?id=1556449)
- [ ] Docs: [ElementInternals.setFormValue()](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/setFormValue) - already documented. Maybe look at whether the example needs details. 
- [ ] BCD: - Just set values appropriately
- [ ] dev-docs-complete:
- [ ] Release note: ?

Need to look at these individually, and possibly enhance examples.

**Comment by hamishwillee** [comment]
@Rumyra This is actually not released but is behind a preference that is only set true by default on nightly. I have reverted the release note update, added experimental features update, and fixed up BCD. I have decided not to add any more docs while this is behind the pref. On release we might update the docs on using custom elements to at least mention these.
