### ISSUE TITLE
[Web API] Implement crypto.randomUUID()

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#10143]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

`cryto.randomUUID()` method needs docs

## Related Gecko bugs

[Implement crypto.randomUUID()](https://bugzilla.mozilla.org/show_bug.cgi?id=1723674)

**Comment by hamishwillee** [comment]
Status
- [ ] Docs: 
   -  [ ] Update [Crypto.randomUUID()](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) as needed - - #10198
- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/13220 (also ended up doing https://github.com/mdn/browser-compat-data/pull/13221 which I ran into while reviewing).
- [ ] Release note - #10198
- [ ] Dev-docs-completed
