### ISSUE TITLE
[HTML] Ship inputmode attribute

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#10144]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

`inputmode` already has a doc https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode so that's good. Probably just updates to bcd & rel needed

## Related Gecko bugs

[Ship inputmode attribute](https://bugzilla.mozilla.org/show_bug.cgi?id=1205133)

**Comment by hamishwillee** [comment]
Status
- [ ]  BCD: https://github.com/mdn/browser-compat-data/pull/13355
- [ ] Release notes
- [ ] Remove from Experimental features
- [ ] Docs updates - TBD
- [ ] dev-doc complete
