### ISSUE TITLE
Issue with "Number.prototype.toFixed()": 20.45.toFixed(1) return 20.4?

### ISSUE THREAD

**Issue by benhuangatcihi** [mdn/content#10171]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed

Recently my application had problem for rounding up number, i traced down the code and found it was using the toFixed() function. It behave inconsistent.

Most of the time it will return expected value, but there are certain case that would fail it.

e.g. 20.45.toFixed(1) returns 20.4 // expect 20.5
       234.45.toFixed(1) returns 234.4 // expect 234.5
       2234.45.toFixed(1) returns 2234.4 // expect 2234.5

However 2.45.toFixed(1) returns 2.5

Is this a bug?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/number/tofixed`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/number/tofixed/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by Florian-Schoenherr** [comment]
![image](https://user-images.githubusercontent.com/65456722/139525921-287ddea7-16e4-4398-93b2-3f5721d4bcc2.png)
![image](https://user-images.githubusercontent.com/65456722/139525927-3b6a7ffd-a8ec-4f43-93d2-9b260f20ba4a.png)

I think it's the same problem.

**Comment by Josh-Cena** [comment]
I think this is already addressed by the warning and numerous examples—can't see how it can be further clarified.
