### ISSUE TITLE
Issue with "Date.UTC()": Use full year

### ISSUE THREAD

**Issue by deep42Thought** [mdn/content#10176]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC

#### What information was incorrect, unhelpful, or incomplete?

examples in Date.UTC for YEAR show two digit year and illustrate Date.UTC(0,0,,) responding with 1899 - which is a two digit interpretation of year.  However the spec for year says it is to be a full year, which would require Date.UTC(1900,0,

if the two digit interpretation is used how then do you enter dates as the first ever Easter?

#### Specific section or headline?

example and property spec

#### What did you expect to see?

one of the two areas changed to be compatible with the other

#### Did you test this? If so, how?

testing is not required - this is a documentary fault

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/utc`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/utc/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

>  However the spec for year says it is to be a full year, which would require Date.UTC(1900,0,

When you say "spec" are you referring to this bit of the page:

<img width="911" alt="Screen Shot 2022-01-15 at 11 02 14 AM" src="https://user-images.githubusercontent.com/432915/149634584-e2c10dff-1216-4b1e-81bb-9b73f03ad70a.png">

**Comment by sideshowbarker** [comment]
Closing for lack of response.

**Comment by teoli2003** [comment]
Reopening per #10176, the Original Poster would like to continue the discussion (so the lack of response reason goes away).

**Comment by deep42Thought** [comment]
Yes the reference was to the part of the spec indicated.
I would like to enter the year that Jesus was put on a cross.  IE 0 AD.  The reference in the response to the year 1900 is not relevant to the issue.

**Comment by teoli2003** [comment]
I conducted some tests. What is written under `Date.UTC` and circled in red by @wbamberg on the image above is wrong.

It behaves like the `Date()` constructor (I've tested it) and the documentation there is clear about the behaviour. We should use it here, too:

> * `year`
>  Integer value representing the year.
>
>   Values from 0 to 99 map to the years 1900 to 1999. All other values are the actual year. 

PR incoming.

**Comment by deep42Thought** [comment]
Jean-Yves

Thanks but this does not work.  This is because a single integer given yo
Date is also defined elsewhere to be a dateserial

So

Test performed on nodejs version v16.13.1

new Date(50)
1970-01-01T00:00:00.050Z

Just tried on Chrome

new Date(50).toISOString()
'1970-01-01T00:00:00.050Z'

These do not match the option to quote a single year - the single year
version should simply be removed from the spec.  You have to provide a
month.  But even then this still does not answer my question - how do I
enter the real full year 50 as in 50AD

Martin

Martin


Dr. Martin W Baker
York Development and Research Limited

07986 297498
martinwbaker ***@***.******@***.***

**Comment by wbamberg** [comment]
> Thanks but this does not work.  This is because a single integer given yo
Date is also defined elsewhere to be a dateserial
>
> Test performed on nodejs version v16.13.1
>
> new Date(50)
> 1970-01-01T00:00:00.050Z
>
> Just tried on Chrome
>
> new Date(50).toISOString()
> '1970-01-01T00:00:00.050Z'
>
> These do not match the option to quote a single year - the single year
version should simply be removed from the spec.  You have to provide a
month.

Are you talking about the `Date` constructor or `Date.UTC()` now? This issue is about `Date.UTC()` but your examples here are for the `Date` constructor.

You don't have to provide a month to `Date.UTC()`:

```js
new Date(Date.UTC(50))
// Date Sat Dec 31 1949 16:00:00 GMT-0800 (Pacific Standard Time)

new Date(Date.UTC(2010))
// Date Thu Dec 31 2009 16:00:00 GMT-0800 (Pacific Standard Time)
```

> But even then this still does not answer my question - how do I
enter the real full year 50 as in 50AD

You have to set the year after constructing the date:

```js
const d = new Date()
// Date Thu Feb 03 2022 10:43:25 GMT-0800 (Pacific Standard Time)

d.setFullYear(50)
// Date Thu Feb 03 0050 10:43:25 GMT-0812 (Pacific Standard Time)
```

This is documented in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#interpretation_of_two-digit_years, which the fix Jean-Yves made links to.
