### ISSUE TITLE
Issue with "MIME types (IANA media types)": Missing Image Types

### ISSUE THREAD

**Issue by eriaxy** [mdn/content#10181]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

Image MIME types are missing, while "{{page("en-US/docs/Web/Media/Formats/Image_types", "table-of-image-file-types")}}" is shown.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/basics_of_http/mime_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/mime_types/index.md
* Last commit: https://github.com/mdn/content/commit/d9a333d16fa31a598e23d71e66da77714eaf1ebc
* Document last modified: 2021-10-28T07:36:04.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. Fixed by #10193
