### ISSUE TITLE
Issue with "Cache Storage": (short summary here please) I don't know how to do what you want me to do ; I only want to add Lucida 

### ISSUE THREAD

**Issue by LordMacLeod** [mdn/content#10180]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector/Cache_Storage

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/storage_inspector/cache_storage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector/Cache_Storage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/storage_inspector/cache_storage/index.html
* Last commit: https://github.com/mdn/content/commit/0ea5ea66ca3ff5f0c02583c1f3606b3b7d4aee40
* Document last modified: 2021-02-02T16:28:31.000Z

</details>

**Comment by hamishwillee** [comment]
Closing. Insufficient information provided to act on this.

If you disagree, please raise the issue again, filling in the templated information requested.
