### ISSUE TITLE
Throwing an error Issue with "static": (short summary here please)

### ISSUE THREAD

**Issue by Ronincod3** [mdn/content#10189]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static

#### What information was incorrect, unhelpful, or incomplete?
JavaScript Demo: Classes Static - on the first example it is throwing an error when running the example: "Error: Unexpected token '{'"

#### Specific section or headline?
JavaScript Demo: Classes Static - in the example to run

#### What did you expect to see?
the result of the static method

#### Did you test this? If so, how?
I have run it on my own IDE, and it works fine, but the example on the MDN site is not working.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/classes/static`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/classes/static/index.md
* Last commit: https://github.com/mdn/content/commit/2354c90ba2395175413198f9262cde1de536af88
* Document last modified: 2021-09-28T10:29:09.000Z

</details>

**Comment by Ronincod3** [comment]
![image](https://user-images.githubusercontent.com/91428461/139594652-75ab69bf-b53f-4694-b5ff-099a565498ca.png)

**Comment by hamishwillee** [comment]
Hi @Ronincod3 
Thanks for reporting. I'm going to close because this works on current versions of Firefox, Opera, Edge that I have tested. If I had to guess you're using a very old browers like IE that does not support the keyword.
![image](https://user-images.githubusercontent.com/5368500/139602905-765b0a82-ebef-4b6d-b84c-43a1f9fe95ca.png)
