### ISSUE TITLE
Issue with "XSLT Basic Example": (short summary here please)

### ISSUE THREAD

**Issue by diomedea** [mdn/content#10182]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XSLTProcessor/Basic_Example

#### What information was incorrect, unhelpful, or incomplete?
XSLT with exactly the example files as published is expected to work. It doesn't at least with Firefox 93.0 (64bit)

#### What did you expect to see?
As for the example in the web page:
Article - My Article
Authors:
- Mr. Foo
- Mr. Bar

#### Did you test this? If so, how?
Copied both xml and xsl example files on a local directory. Took care that file names matched (so, the href within xml was same as the xsl filename). Did not change anything in content from both example files.
Then opened the xml in Firefox. Expectation is to see the XSLT work resulting in the output as shown in the webpage. Effective result is just the list of textual info collected from all xml nodes.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/xsltprocessor/basic_example`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XSLTProcessor/Basic_Example
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/xsltprocessor/basic_example/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much - fixed by #10195.

The short answer is that you need to run the example using a local server or you'll get a CORS error. See https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server#running_a_simple_local_http_server for instructions on how to set up a server - I use the Python one most commonly.
