### ISSUE TITLE
Content suggestion: performance glossary term: largest contentful paint/First Input Delay

### ISSUE THREAD

**Issue by estelle** [mdn/content#10196]
## What is the new suggestion?
Glossary terms: 
 - LCP -> largest contentful paint.
 - FID -> First Input Delay

## Why is it important or useful?
TTFB and FCP are defined. LCP and FID are needed

How many pages are likely to be needed?
2
How much time do you think this work should take? 5 hours

Will the work enable learners or professionals to achieve their goals better? yes
Does it address critical needs in the web industry? yes
Is the work an operational necessity, i.e. is not having it a security risk? no
Does the content help make the web more ethical? yes

MDN URL: https://developer.mozilla.org/en-US/docs/Glossary
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Performance

**Comment by wbamberg** [comment]
These are both documented:
https://developer.mozilla.org/en-US/docs/Glossary/Largest_contentful_paint
https://developer.mozilla.org/en-US/docs/Glossary/First_input_delay
