### ISSUE TITLE
Content suggestion: device-posture CSS media query

### ISSUE THREAD

**Issue by estelle** [mdn/content#10197]
## What is the new suggestion?
@media (device-posture: folded)

## Why is it important or useful?
Some devices fold. The spec has not been addressed since I think it may be samsung only, but other devices will fold. 

How many pages are likely to be needed? 1
How much time do you think this work should take? one day
Will the work enable learners or professionals to achieve their goals better? yes
Does it address critical needs in the web industry? yes
Is the work an operational necessity, i.e. is not having it a security risk? Kind of
Does the content help make the web more ethical? sorta

https://w3c.github.io/device-posture/

**Comment by Josh-Cena** [comment]
This is perhaps too early for documentation, as two years have passed and I don't think there's an implementation—not much progress on the spec, either. If it lands, we would document the API as a whole (which also includes `navigator.devicePosture`).
