### ISSUE TITLE
"Content Security Policy (CSP)": Wording / Grammar issue

### ISSUE THREAD

**Issue by EliteSpud** [mdn/content#10230]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

#### What information was incorrect, unhelpful, or incomplete?

Content Security Policy (CSP) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross-Site Scripting (XSS) and data injection attacks. These attacks are used for everything from data theft to site defacement to distribute malware. 

Should read "to distributing malware" at the end?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/csp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/csp/index.md
* Last commit: https://github.com/mdn/content/commit/68f3e396186dee446d507ad972f455690145e0bf
* Document last modified: 2021-08-30T05:13:09.000Z

</details>

**Comment by abdelrazek-alaa** [comment]
@EliteSpud @ddbeck
Hello everybody :slightly_smiling_face: 
>These attacks are used for everything from data theft to site defacement to distribute malware

so, the suggested edit for this line is just:
```diff
- distribute malware.
+ distributing malware.
```

**Comment by hamishwillee** [comment]
Thanks all - fixed by  #10298

Note, for simply grammar and typo fixes like this, it is best to just make the change that you think necessary as a PR.

**Comment by EliteSpud** [comment]
Ah, thank you. I wasn't sure of the usual procedure for stuff like this :)

**Comment by hamishwillee** [comment]
@EliteSpud There is no problem with creating an issue either:-). It's just that if you're sure of a fix it is probably just as easy for you to show what needs fixing as explain it.
