### ISSUE TITLE
Content bug: Element.classList.add does not accept empty string

### ISSUE THREAD

**Issue by masell** [mdn/content#10238]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/add

## What is the problem?

It should be mentioned in the docs that the class (which is almost always a variable), can not be empty string.

## What did you expect to see?

Add a "Warning" saying that browser will throw a exception if the string is empty.

## Did you test this? If so, how?
```javascript
const cls = '';
document.body.classList.add(cls);
```
In google chrome:
> Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.

In firefox:
> SyntaxError: An invalid or illegal string was specified

**Comment by Biki-das** [comment]
@teoli2003 need a little help here, like how should i introduce the warning should it be in another heading

**Comment by wbamberg** [comment]
This was fixed in https://github.com/mdn/content/pull/11504.
