### ISSUE TITLE
Set Custom Validity Work

### ISSUE THREAD

**Issue by alpesh230** [mdn/content#10255]
In Firefox Browser we use set Custom message on input field using setCustomValidity('invalid input') its work perfectly first time. after second click its not working properly please check below link 
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#constraint_combining_several_fields_postal_code_validation
In this section one form which is input field please check. also this work older version perfectly after update browser its behavior change...

**Comment by sideshowbarker** [comment]
This doesn’t seem to be proposing any specific change to MDN content
