### ISSUE TITLE
Math.floor function is not working properly for specific number

### ISSUE THREAD

**Issue by Singh123Pankaj** [mdn/content#1025]
### ISSUE IN MATH.FLOOR()
example: let val=(Math.floor(-130.866*1000))/1000;
 **Expected Value**: -130.866
**Actual value **: -130.867
we can also see issue with the number-
 -130.865,-130.867 then -130.965.....-130.967

I am unable to find the reason, Please help !!!!!!!!

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/howto/report_a_problem`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Report_a_problem
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/contribute/howto/report_a_problem/index.html
* Report started: 2021-01-07T04:33:05.999Z

</details>

**Comment by rockerer** [comment]
Hi,
the expression `-130.688*1000` is evaluated to -`130866.00000000001`. Thats why `Math.floor(-130.866*1000) = -130867` and thus `(Math.floor(-130.866*1000))/1000 = -130.867`. 

Some literature about this: https://modernweb.com/what-every-javascript-developer-should-know-about-floating-points/

**Comment by chrisdavidmills** [comment]
Thanks for the explanation here @rockerer. Floating points are interesting ;-)

I don't think there is anything to change here, so I'm closing this, but feel free to chime in if you have any more questions @Singh123Pankaj .
