### ISSUE TITLE
Browser Compatibility on Web API Animation iOS needs to be updated

### ISSUE THREAD

**Issue by aquaductape** [mdn/content#1026]
In Web API Animation, the [Browser Compatibility iOS section](https://developer.mozilla.org/en-US/docs/Web/API/Animation#browser_compatibility) shows no support on the methods: `play`, `pause`, and `reverse`. I tested on iOS 14.3 and all three do work. [Codepen Demo](https://codepen.io/Kahlub/pen/NWRzaRB).

I have only tested those three methods.

According to this [Webkit blog](https://webkit.org/blog/10266/web-animations-in-safari-13-1/), in iOS 13.4, iPadOS 13.4, and Safari 13.1, they do support some playBack Control, which includes `pausing`. But I don't have those devices, so I can't verify.

**Comment by chrisdavidmills** [comment]
Thanks for reporting @aquaductape ! Looks like we need someone to investigate these thoroughly, do some testing, and then update the values in the `Animation` compat data — https://github.com/mdn/browser-compat-data/blob/master/api/Animation.json

I wonder if @graouts could provide some help in unearthing WebKit/iOS support versions for these features?

**Comment by graouts** [comment]
Hi, and sorry for taking this long to reply, had not been looking at my GitHub notification emails in a while.

Web Animations indeed shipped with iOS 13.4 and iPadOS 13.4, at the same time as Safari 13.1 shipped for macOS. The entire `Animation` interface is implemented since those releases.
