### ISSUE TITLE
"CSP: script-src" multiple source interactions unspecified (unsafe-inline)

### ISSUE THREAD

**Issue by kmacdough** [mdn/content#10260]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

#### What information was incorrect, unhelpful, or incomplete?
The documentation suggests `script-src` is additive (i.e. if a script matches ANY `script-src` sources in a policy, it is allowed by that policy). It also specifies that `'unsafe-inline'` allows all forms of inline scripts. Putting these two together, this implies that any policy containing `'unsafe-inline'` should, regardless of other sources, allow:
`<script src="https://www.example.com/some.js"></script>`

This does not match the behavior of modern Chrome, Firefox or Opera where the policy
`Content-Security-Policy: script-src 'self' 'unsafe-inline' https://not-example.com`
blocks
`<script src="https://www.example.com/some.js"></script>`

#### What did you expect to see?

I would expect to see some explanation of how multiple sources within a directive affect each other. It appears that certain conditions disable an `'unsafe-inline'` source, but I see no clear indication of when this does or does not happen. That or the meaning of `'unsafe-inline'` has changed from the documented behavior.

But the behavior appears consistent across modern browsers, so I believe it should be documented.

#### Did you test this? If so, how?

I am not a web developer and have not yet invested the time to put together enough of a server to test this. However, this thread shows a fix for a CSP blocking issue demonstrating 

I did manually perform before/after checks on all 3 browsers and confirmed the change resolved the issue. The change simply added URLs to a `script-src 'self' 'unsafe-eval' 'unsafe-inline'` 

https://forum.flightgear.org/viewtopic.php?f=8&t=39900&p=394287

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/script-src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/script-src/index.md
* Last commit: https://github.com/mdn/content/commit/2e2631aa9d11718154ca50c2c3cc82074ab34ccd
* Document last modified: 2021-08-31T15:21:54.000Z

</details>

**Comment by Josh-Cena** [comment]
`"unsafe-inline"` blocks _inline scripts_, i.e. script source contained directly in the `<script>` tag. Your `<script src="https://www.example.com/some.js"></script>` is an external script that's matched by neither `"unsafe-inline"` nor `https://not-example.com` and hence blocked.
