### ISSUE TITLE
Issue with "Element.scrollTo()": behavior no longer accepts the value 'instant'

### ISSUE THREAD

**Issue by patik** [mdn/content#10265]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo

#### What information was incorrect, unhelpful, or incomplete?

The value `'instant'` is no longer supported for `behavior`

#### Specific section or headline?

Each mention of `behavior`

#### What did you expect to see?

Only the values `'auto'` and `'smooth'`

#### Did you test this? If so, how?

TypeScript pointed out the error to me. See [this CSSWG issue](https://github.com/w3c/csswg-drafts/issues/2146) for more, and another reference [here](https://github.com/microsoft/TypeScript-DOM-lib-generator/commit/fe01c9a6d6afde86bd15f2588dc9360416a2beb4).

Note that the same issue existed with the page on `scrollIntoView`, but that page has already been updated so `'instant'` is no longer mentioned.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/scrollto`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/scrollto/index.md
* Last commit: https://github.com/mdn/content/commit/db6e4a8e749fe4f8c06373a9d5c1af3715e2e213
* Document last modified: 2021-09-20T21:44:14.000Z

</details>

**Comment by abdelrazek-alaa** [comment]
Ok, I'll work on that :slightly_smiling_face:
