### ISSUE TITLE
Duplicate heading on manifest version format page

### ISSUE THREAD

**Issue by rebloor** [mdn/content#10274]
## What page(s) did you find the problem on?

Manifest [Version Format](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version/format)

## Specific page section or heading?

Version Format/Manifest Version Format

## What is the problem?

The page title is duplicated.

## What did you expect to see?

Just the Version Format title.

**Comment by abdelrazek-alaa** [comment]
I'll work on this issue :slightly_smiling_face:
