### ISSUE TITLE
Content bug: Typo in URL slug for guide on Unicode bidirectional text algorithm

### ISSUE THREAD

**Issue by adityasharad** [mdn/content#10280]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/Guide/Unicode_Bidrectional_Text_Algorithm

## Specific page section or heading?

URL slug

## What is the problem?

Typo in the URL slug: `Bidrectional -> Bidirectional`

## What did you expect to see?

The URL should ideally be `https://developer.mozilla.org/en-US/docs/Web/Guide/Unicode_Bidirectional_Text_Algorithm`.

## Did you test this? If so, how?

At time of writing, https://developer.mozilla.org/en-US/docs/Web/Guide/Unicode_Bidirectional_Text_Algorithm (corrected spelling) does not exist.

Happy to make this change myself, but I'm not sure how redirects are handled in this content. Is it better to rename the directory and fix the slug within the Markdown front matter, or to keep both the old and new directories around to handle traffic that goes to the old URL?

**Comment by hamishwillee** [comment]
Thanks @adityasharad 

The thing to do is use follow these commands: https://github.com/mdn/content#moving-one-or-more-documents

You may need to edit the page a bit after moving (I can't remember)

Even though the redirect will work, I also generally fix up those links I can in the source manually.

**Comment by wbamberg** [comment]
This page has since been deleted as it didn't contain any useful content.
