### ISSUE TITLE
Issue with "Gzip compression": example link leads to marketing site

### ISSUE THREAD

**Issue by dsmith-digitalmint** [mdn/content#10283]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/GZip_compression

#### What information was incorrect, unhelpful, or incomplete?

The link titled `How to enable compression and gzip for page speed` does not lead to any further tutorials instead it links to an "SEO consultant" I won't be posting the link so they do not get more clout.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/gzip_compression`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/GZip_compression
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/gzip_compression/index.md
* Last commit: https://github.com/mdn/content/commit/4a9f9d2e9c1811ce3519a7061e906db9200a5e97
* Document last modified: 2021-10-08T00:24:32.000Z

</details>

**Comment by wbamberg** [comment]
Ugh, thank you for filing! I've submitted https://github.com/mdn/content/pull/10292 as a fix.
