### ISSUE TITLE
“Paint Timing API” overview document needs to be written

### ISSUE THREAD

**Issue by punkah** [mdn/content#10287]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming

#### What information was incorrect, unhelpful, or incomplete?
Broken link

#### Specific section or headline?
Reference to  Paint Timing API 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/performancepainttiming`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/performancepainttiming/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment]
There are lots of broken links in the docs. 

It is worth creating issues if there is good content on MDN and the page just doesn't link to it. 

However usually this just indicates content that is yet to be written. In my opinion there isn't much point creating issues for these - we can generate lists of broken links dynamically. Not sure if that is general consensus.

**Comment by aegatlin** [comment]
Is there actually a spec for a Paint Timing API? It seems that `PerformancePaintTiming` is an interface on the `PerformanceEntry` interface according to the [linked w3c spec from the same page](https://w3c.github.io/paint-timing/#sec-PerformancePaintTiming). Could this perhaps be a typo, and the link and name-of-link should point to [MDN docs on Performance Entry](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEntry) instead? If not, where can the spec for the api be found?
