### ISSUE TITLE
Issue with "IDBDatabase.createObjectStore()": (short summary here please)

### ISSUE THREAD

**Issue by HelmZalee** [mdn/content#10293]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/createObjectStore

#### What information was incorrect, unhelpful, or incomplete?
The first line of text says "The createObjectStore() method of the IDBDatabase interface creates and returns a new object store _or index_.  Further along under **Returns** is "A new IDBObjectStore."

Probably I'm missing something, but this seems inconsistent.  It may be that I don't correctly grasp what "...or _index_" refers to,  

The page https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/createIndex says "The createIndex() method...creates and returns a new _IDBIndex_ object..."  So it appears an "index" is an IDBIndex, and "object store" isan IDBObjectStore, and createObjectStore does not return both.  (The following sentence, about "creating a new field..."  seems problematic, but this is already too convoluted.)

The next paragraph says "Bear in mind that IndexedDB _indexes_ can contain any JavaScript data type; IndexedDB uses the structured clone algorithm to serialize stored objects, which allows for storage of simple and complex objects."  Certainly this is true of an IDBObjectStore.  Is it also somehow true of an _IDBIndex_?  Is this trying to say something about the possible structure of a _key_ in the IDBIndex?

#### Specific section or headline?
First sentence of first section of the createObjectStore page.

#### What did you expect to see?
A statement similar to the first line of the createIndex page, e.g., "The createObjectStore() method of the IDBDatabase interface creates and returns a new _IDBObjectStore_."

Replacing _a new object store or index_ with _IDBObjectStore_ seems to remove any ambiguity about exactly what is returned.

#### Did you test this? If so, how?
Reading, re-reading, switching back and forth between the two pages...

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/idbdatabase/createobjectstore`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/createObjectStore
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/idbdatabase/createobjectstore/index.md
* Last commit: https://github.com/mdn/content/commit/223f4e52e66e1e20e84a2c57ee799141e92e2700
* Document last modified: 2021-10-23T02:55:34.000Z

</details>

**Comment by wbamberg** [comment]
Yes, I think you are right and have filed https://github.com/mdn/content/pull/10306 accordingly. Thanks for the report!
