### ISSUE TITLE
Issue with "204 No Content": …

### ISSUE THREAD

**Issue by sylvaingirardbe** [mdn/content#1030]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204

#### What information was incorrect, unhelpful, or incomplete?
The information is subject to misinterpretation. Our UI updates resources using PUT and receives a 204 when successful. In most cases it will do a GET of the aggregate root to get the new version. This information seems to suggest that we would need to return a 200 in this case.
The information found here is less open for interpretation:
- https://httpstatuses.com/204
-  https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status/204`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/status/204/index.html
* Report started: 2021-01-07T12:19:05.460Z

</details>

**Comment by hamishwillee** [comment]
@sylvaingirardbe I think I agree.  The bit at the end (shown below) implies that you *have to* return 201 on creation or 200 if you require an update. In fact this is a choice; you can return 204 in the first request and then do a second request to update the UI if you so wish. Further if you want to do a save and edit when first creating a page you can return a 204 in this case.

>If the resource is created, 201 Created is returned instead. If the page should be changed to the newly updated page, the 200 should be used instead.

All that is implied by this code is that the client should not update the content as a result of this particular request. 

I have tried to fix this in #1483
