### ISSUE TITLE
Codepen HTML example doesn't render

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#10300]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions#using_transitions_when_highlighting_menus
click 'live demo' link https://codepen.io/anon/pen/WOEpva
observe the page/HTML is not rendered
If you modify the HTML code, then the page will render to see the example

**Comment by wbamberg** [comment]
That's weird, I wonder why. We should convert this into a live sample in the page.
