### ISSUE TITLE
Issue with "CanvasRenderingContext2D.putImageData()": Syntax Error in Example

### ISSUE THREAD

**Issue by gabekole** [mdn/content#10302]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData

#### What information was incorrect, unhelpful, or incomplete?
I believe there is a syntax error in one of the examples

#### Specific section or headline?
Understanding putImageData

#### What did you expect to see?
"putImageData(ctx, imagedata, 150, 0, 50, 50, 25, 25);"
I expected
"ctx.putImageData(imagedata, 150, 0, 50, 50, 25, 25);"

#### Did you test this? If so, how?
I tested it in a repl.it and the documentation for the method does not state this a valid usage of it

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/putimagedata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/putimagedata/index.md
* Last commit: https://github.com/mdn/content/commit/d3c38334923570ada25766f77212b2e808fdebc5
* Document last modified: 2021-10-15T17:04:17.000Z

</details>

**Comment by sideshowbarker** [comment]
It’s not a syntax error. That example intentionally doesn’t intend to show the `CanvasRenderingContext2D: putImageData()` standard method. Instead, the point of that example appears to be to illustrate “an implementation on top of `CanvasRenderingContext2D.fillRect()`. ” It first defines a `function putImageData()` function, and then calls it.

I’m not sure it’s a great idea for the article to have such an example — but at least it’s not an outright error.
