### ISSUE TITLE
JavaScript objects not well documented and require alignment

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#10301]
There are two issues:
* JS docs need to be updated to document JS objects properly and consistently, and cover classes
* We have a number of JS guides that need to be aligned:
  1. the JS Learn docs: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects
  2. this page, a re-introduction to JS: https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript
  3. The JS guide: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Details_of_the_Object_Model

From @wbamberg 

> At this point I wonder if anything would be lost if we retired "a re-introduction to JS" and just redirected it to the JS guide. I think it served a purpose at a particular time in the history of JS, but that time has moved on, and in many other ways this page looks dated.
>
> That leaves us with 2 sets of JS guides, Learn and the JS guide, which I think makes sense - Learn is organized as pathway for beginners, omitting lots of gory details, and the Guide goes deep and is organized by subject.
>
> For the first issue, the Learn area and the JS guide **also** don't do a good job of explaining modern JS objects. I'm working on https://github.com/mdn/content/blob/main/rfcs/modernize-learn-js.md in this quarter, and as part of that will need to update the way Learn talks about objects. But we would need a new vehicle for updating the JS guide.

This originates from https://github.com/mdn/content/pull/10190#issuecomment-958091432

**Comment by Josh-Cena** [comment]
I plan to re-write the "Details of the object model" and make it _solely_ based on classes. This way, we have two pages dealing with prototypes: "Details of the object model" deals with the nicely abstracted class paradigm and compares it to Java / other OOP stuff without going into the language details, while "Inheritance and the prototype chain" dives into the underlying mechanism. How does that sound?
