### ISSUE TITLE
Issue with "Document.hasFocus()": `setInterval(checkPageFocus, 300)` is not a very efficient method.

### ISSUE THREAD

**Issue by jespertheend** [mdn/content#10312]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus

#### What information was incorrect, unhelpful, or incomplete?
I came to the page to figure out if there was a relation between `document.hasFocus()` and the `focus` and `blur` events.
To my surprise I saw the example containing `setInterval(checkPageFocus, 300);` which seems like an inefficient way to do it.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus#javascript

#### What did you expect to see?
Something more along the lines of
```js
window.addEventListener("blur", checkPageFocus);
window.addEventListener("focus", checkPageFocus);
```

#### Did you test this? If so, how?
I have implemented in this way in my own application. However, I'm not sure if a guarantee is being made regarding the spec that this behaviour is expected. I.e. I'm not sure if `document.hasFocus()` is guaranteed to be `true` right after a `focus` event and `false` right after a `blur` event. [This page](https://developers.google.com/web/updates/2018/07/page-lifecycle-api#state-passive) seems to suggest so but I couldn't find anything in the spec.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/hasfocus`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/hasfocus/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by bsmth** [comment]
Hi @jespertheend we've closed the issue as resolved but we have kept polling as the way to demonstrate this functionality. You can see the rationale in the linked pull request thread. If you can think of a better solution, you're very welcome to open a pull request that improves the example.

Thank you :)

**Comment by jespertheend** [comment]
Ah that makes sense yeah, I hadn't thought of that. The way I'm using `hasFocus()` in my application is that I have a single function that updates state based on a bunch of parameters, then that function is called from both the `"blur"` and `"focus"` events, as well as some other places where state is changed. But I don't think this use case can be incorporated into a simple example to be honest.

**Comment by wbamberg** [comment]
I guess we could add a comment that this is just a demo example, and we don't recommend polling as a real-world strategy?

**Comment by jespertheend** [comment]
Now that I think about it, using the focus and blur events would work in the current example as well.

The point of using a single `checkDocumentFocus()` function is that you don't know if the document is focused when the page loaded. So you still need an if statement to check which text to show once the page loads. After that, you might as well reuse the function in the `"focus"` and `"blur"` events, otherwise you will have to type the text twice.
