### ISSUE TITLE
Issue with "Taking still photos with WebRTC": (example does not use WebRTC)

### ISSUE THREAD

**Issue by KVAnton-WEB** [mdn/content#10327]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos

#### What information was incorrect, unhelpful, or incomplete?

WebRTC in this example only in the title.
An example has nothing to do with the WebRTC.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #17645 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
