### ISSUE TITLE
Issue with "Your first extension": YouTube videos unavailable and extension not working

### ISSUE THREAD

**Issue by XsongyangX** [mdn/content#10320]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

#### What information was incorrect, unhelpful, or incomplete?
The YouTube videos are unavailable. The extension tutorial does not work.

#### What did you expect to see?
YouTube videos and the change brought by the tutorial extension.

#### Did you test this? If so, how?
As followed in the tutorial.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/your_first_webextension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/your_first_webextension/index.md
* Last commit: https://github.com/mdn/content/commit/629960fa07e15f2354d75daf14f149d4942539ec
* Document last modified: 2021-10-26T21:28:18.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. Closing because this is a duplicate/known issue - see https://github.com/mdn/content/issues/7457

This particular example also has the issue that it requires private browsing. There is a hint on that here: https://github.com/mdn/content/issues/9861#issuecomment-949457848
