### ISSUE TITLE
Issue with "Use a source map": (short summary here please)

### ISSUE THREAD

**Issue by almonalisa** [mdn/content#10321]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/debugger/how_to/use_a_source_map`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/debugger/how_to/use_a_source_map/index.html
* Last commit: https://github.com/mdn/content/commit/4388bb9bbdfe74a2271e8d4df6a33e3b76737473
* Document last modified: 2021-04-29T03:28:00.000Z

</details>

**Comment by Rumyra** [comment]
Hi @almonalisa thanks for submitting the issue - can you explain what the problem is with this page - thank you!
