### ISSUE TITLE
Issue with "Drawing graphics": (change starting color)

### ISSUE THREAD

**Issue by VladimirFokow** [mdn/content#10338]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics#a_simple_drawing_application

#### What information was incorrect, unhelpful, or incomplete?
The "simple drawing application" example is not working. All I can see is a black canvas, and I can't draw anything.

#### Specific section or headline?
A simple drawing application

#### What did you expect to see?
Line being drawn under cursor while the left mouse button is pressed.

#### Did you test this? If so, how?
Tried drawing in Safari and Chrome.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/drawing_graphics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by abdelrazek-alaa** [comment]
I think you have to change the color to be able to draw :slightly_smiling_face: 
![mdn](https://user-images.githubusercontent.com/28750621/140642178-a6fdf82c-6487-4990-b179-f40163355094.png)

**Comment by VladimirFokow** [comment]
Oh! Got it, thanks😁
Maybe it would be less confusing for others in the future if the starting color is something other than black )

**Comment by hamishwillee** [comment]
@VladimirFokow I could not agree more. Thanks for reporting. Fixed by https://github.com/mdn/learning-area/pull/417
