### ISSUE TITLE
Issue with "Your first extension": Videos are unavailable

### ISSUE THREAD

**Issue by jsuvanto** [mdn/content#10348]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

#### What information was incorrect, unhelpful, or incomplete?
The embedded YouTube videos are unavailable.

#### Specific section or headline?
"Trying it out", subsections "Installing" and "Testing".

#### What did you expect to see?
I expected to see the videos.

#### Did you test this? If so, how?
I looked at the source of the document. I looked for a video id and checked it in YouTube. The video turned out to be set to "private".

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/your_first_webextension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/your_first_webextension/index.md
* Last commit: https://github.com/mdn/content/commit/629960fa07e15f2354d75daf14f149d4942539ec
* Document last modified: 2021-10-26T21:28:18.000Z

</details>

**Comment by hamishwillee** [comment]
@jsuvanto Thanks. Closing because this is a duplicate/known issue - see https://github.com/mdn/content/issues/7457

This particular example also has the issue that it requires private browsing. There is a hint on that here: https://github.com/mdn/content/issues/9861#issuecomment-949457848
