### ISSUE TITLE
Issue with "FontFace.load": Not allowed to load local resource

### ISSUE THREAD

**Issue by rafailyk** [mdn/content#10353]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FontFace/load

#### What information was incorrect, unhelpful, or incomplete?
_load()_ feature do not actually work on Safari, Chrome, Firefox (local folder, localhost, server).
I use the following code:
```
let font_file = new FontFace('FontFamily Style', 'url(fontfamily-style.woff2)');
font_file.load().then(function(font_loaded) {
	// do something
}
```

**Safari** and **Chrome** (local, localhost): "Not allowed to load local resource" + "Unhandled Promise Rejection: NetworkError:  A network error occurred."
**Firefox** (local, localhost): "downloadable font: download failed ..." + "Uncaught (in promise) DOMException: A network error occurred."
**Safari** (Apache server): "Unhandled Promise Rejection: NetworkError:  A network error occurred."
**Chrome** (Apache server): "Failed to decode downloaded font ..." + "Uncaught (in promise) DOMException: A network error occurred."
**Firefox** (Apache server): "downloadable font: rejected by sanitizer ..." + "Uncaught (in promise) DOMException: A network error occurred."

When I use this font file with CSS @font-face, everything works fine.

#### What did you expect to see?
Font file should be loaded. Ok, if not on localhost, then on Apache server.
I want to see the moment when new features become really useful on reality.

#### Did you test this? If so, how?
Safari macOS, Chrome macOS, Firefox macOS.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/fontface/load`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FontFace/load
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fontface/load/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for reporting.  It is far more likely that either your code or your font file are incorrect - certainly your code above is wrong since it has a syntax error - which I assume is just a typo here. You might get that error, for example, if you specify the wrong location for the file. 

I verified locally and remotely using very similar test code and a google font called bitter.woff2 and it works fine on current browsers.
```
const log = document.getElementById("log");

log.textContent+="running\n";
//self.reportError();

//let font_file = new FontFace('FontFamily Style', 'url(bitter.woff2)');
let font_file = new FontFace('FontFamily Style', 'url(https://fonts.gstatic.com/s/bitter/v7/HEpP8tJXlWaYHimsnXgfCOvvDin1pK8aKteLpeZ5c0A.woff2)');

font_file.load().then(function(font_loaded) {
	// do something
   }
);
```
This works with the same file both locally and hosted.

But even if this was a problem with browser implementations, it would not be an MDN bug. YOu would need to post the issue against the specific browser.

**Comment by rafailyk** [comment]
Hi, Hamish.
Thanks, now I see – that's really just a syntax error (missing closing parenthesis). Shame for me :/
