### ISSUE TITLE
Issue with "<image>: The Image element": Page reports the spec as lost, but I found it!

### ISSUE THREAD

**Issue by binyamin** [mdn/content#10350]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/image

#### What information was incorrect, unhelpful, or incomplete?
The document says that the specification for the `<image>` element has been lost over time.

#### Specific section or headline?
> This might have once been part of a specification, but nobody seems to remember. It certainly isn't anymore. Just avoid it like the plague.
[§specifications](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/image#specifications)

#### What did you expect to see?
Well, I found this element in an HTML+ specification[^htmlplus] (link: [§ 5.9 - Images](https://www.w3.org/MarkUp/HTMLPlus/htmlplus_21.html)). In fact, [there's a footnote](https://www.w3.org/MarkUp/HTMLPlus/htmlplus_FootNote_108.html) which _recommends it_ over `<img>`.

#### Did you test this? If so, how?
Not applicable

[^htmlplus]: Dave Raggett, "HTML+ Discussion Document", November 8, 1993.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/image`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/image
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/image/index.md
* Last commit: https://github.com/mdn/content/commit/775662998e66813a612e3ff27e02f2ada867bc17
* Document last modified: 2021-10-03T00:01:51.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. Technically a discussion document is not an HTML specification, but I'll grant it's fun. I've added into the doc, so hopefully people don't see finding this as a challenge :-)
