### ISSUE TITLE
Issue with "DOMMatrixReadOnly()": Incorrectly labeled non-standard; missing link from Interface to constructor

### ISSUE THREAD

**Issue by danburzo** [mdn/content#10352]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMMatrixReadOnly/DOMMatrixReadOnly

#### What information was incorrect, unhelpful, or incomplete?

The `DOMMatrixReadOnly()` constructor is labeled as non-standard. In addition, the page on `DOMMatrixReadOnly()` is missing a link to its constructor. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/dommatrixreadonly/dommatrixreadonly`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMMatrixReadOnly/DOMMatrixReadOnly
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/dommatrixreadonly/dommatrixreadonly/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by teoli2003** [comment]
Thanks for the report. I fixed the existing pages. At some point in the future, we will need to write the missing pages.

**Comment by danburzo** [comment]
Cool, thanks @teoli2003!
