### ISSUE TITLE
Issue with "Test your skills: Images and Form elements": (live editor seems not to work)

### ISSUE THREAD

**Issue by Den0702** [mdn/content#10355]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_tasks

#### What information was incorrect, unhelpful, or incomplete?
It is like this live frame is broken and not working? 

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_tasks#task_one

#### What did you expect to see?
![ice_screenshot_20211107-201216](https://user-images.githubusercontent.com/30319035/140658590-097c472b-d750-4930-a0c4-0efdafcbad12.png)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/images_tasks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_tasks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/images_tasks/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by Rumyra** [comment]
Hi @Den0702 - thanks for opening this issue.

The interactive editor is indeed working - try setting the image width to 50% and it will update. If you need any help with finding solutions to the tasks try asking in our learning forum https://discourse.mozilla.org/c/mdn/learn/250/l/latest 👍
