### ISSUE TITLE
Issue with "Creating hyperlinks": (title is missing)

### ISSUE THREAD

**Issue by stamgolesh** [mdn/content#10357]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks

#### What information was incorrect, unhelpful, or incomplete?
title is missing

#### Specific section or headline?
Adding supporting information with the title attribute

#### What did you expect to see?
This gives us the following result **and hovering over the link displays the title as a tooltip**.
I'm creating a link to the Mozilla homepage.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/creating_hyperlinks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/creating_hyperlinks/index.md
* Last commit: https://github.com/mdn/content/commit/8bc9a25846c2ecfe4e2c2c2a363fd2208f3a69ae
* Document last modified: 2021-10-13T06:21:42.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. Fixed by https://github.com/mdn/content/pull/10358
