### ISSUE TITLE
Where to discuss Firefox's parsing of CSS selectors?

### ISSUE THREAD

**Issue by ianthedev** [mdn/content#10367]
Years ago, MDN [published an article on how to write efficient CSS selectors](https://web.archive.org/web/20120505043119/https://developer.mozilla.org/en/Writing_Efficient_CSS). I have some questions regarding the teaching of the article and would appreciate if the Firefox development team could answer them. Where do I start such a discussion?

**Comment by schalkneethling** [comment]
@Rumyra ^^

**Comment by estelle** [comment]
Browsers are optimized to parse CSS. The reason there aren't many if any articles on optimizing selectors for performance is it's **not** a low hanging fruit. Likely, optimizing a single image will bring more performance benefits than optimizing all of your CSS selectors. :first-child is faster than :last-child, but we're talking nano-seconds.

**Comment by ianthedev** [comment]
@estelle Thanks. I'll check webperformance.slack.com

> My assumption is putting the pseudoclass last is possibly faster

Since browsers parse each line of selector from right to left, wouldn't it be more logical to assume putting _non-pseudoclass_ last is possibly faster? I mean, when it comes to _key selector_ (the last part of a line of selector), wouldn't `:last-child.foo-item` supposed to be faster than `.foo-item:last-child`?
