### ISSUE TITLE
Issue with "Clipboard.read()": Wrong return value listed

### ISSUE THREAD

**Issue by fpapado** [mdn/content#1036]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read

#### What information was incorrect, unhelpful, or incomplete?

On MDN, the "Return value" section for the Clipboard.read() method of the Clipboard interface indicates

> A Promise that resolves with a DataTransfer object containing the clipboard's contents. The promise is rejected if permission to access the clipboard is not granted.

However, this is incorrect. According to both [the linked specification](https://w3c.github.io/clipboard-apis/#dom-clipboard-read) and demos of the API ([Clipboard.read demo on web.dev](https://web.dev/async-clipboard/#read()), [own experiment with Clipboard.read on CodePen](https://codepen.io/fpapado/pen/mdrKGXV?editors=0010)).

The method returns an array of [ClipboardItem](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem)

> Let data be a copy of the system clipboard data represented as a sequence of ClipboardItems.
   Resolve p with data.

(from [the linked specification](https://w3c.github.io/clipboard-apis/#dom-clipboard-read))

The two different Clipboard APIs (ClipboardEvent and Clipboard) can be confusing to make sense of (especially as browser support for the latter grows). The distinction between what .read returns (Array<ClipboardItem>) and what the 'paste' event returns (DataTransfer object) has tripped me up!.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read#return_value

Also at https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#methods -> 'read()'

#### What did you expect to see?

I think a small tweak to change the return type would be enough as a first step. The rejection reasons are the same:

> A Promise that resolves with an array of [ClipboardItem](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem) objects, representing the clipboard's contents. The promise is rejected if permission to access the clipboard is not granted.

**I would be happy to make a PR for this :)**

#### Did you test this? If so, how?

I checked with the spec, the web.dev demo, and my own experiment with what each of these APIs returns. I have linked them in the previous paragraphs.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/clipboard/read`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/clipboard/read/index.html
* Report started: 2021-01-07T15:33:52.230Z

</details>

**Comment by sideshowbarker** [comment]
> **I would be happy to make a PR for this :)**

That would be great; for guidance, see https://github.com/mdn/content/blob/main/README.md#more-substantial-changes

**Comment by sideshowbarker** [comment]
Fixed by #6230.
