### ISSUE TITLE
Content bug: Missing redirect for some DOM events

### ISSUE THREAD

**Issue by danburzo** [mdn/content#10376]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/Events/dataavailable
https://developer.mozilla.org/en-US/docs/Web/Events/formdata
https://developer.mozilla.org/en-US/docs/Web/Events/touchstart

## What is the problem?

The DOM event pages linked above don't have a redirect and result in 404. Noticed by chance while using this page: https://danburzo.ro/reference/dom-events/

(The list may not be exhaustive.)

## What did you expect to see?

The event pages should redirect to their canonical URL under the associated DOM interface.

**Comment by hamishwillee** [comment]
@danburzo Would you like to create a PR to fix? The redirects are created using yari by following the instructions here: https://github.com/mdn/content#redirecting-a-document. For the last case, for example, you'd do:
```
yarn content add-redirect /en-US/docs/Web/Events/touchstart /en-US/docs/Web/API/Element/touchstart_event
```
