### ISSUE TITLE
Issue with "JSON viewer": YouTube video is set to private

### ISSUE THREAD

**Issue by QazCetelic** [mdn/content#10374]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer

#### What information was incorrect, unhelpful, or incomplete?
YouTube video is unavailable

#### What did you expect to see?
That the YouTube video was watchable

#### Did you test this? If so, how?
Yes, the video is set to private

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/json_viewer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/json_viewer/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — we have https://github.com/mdn/content/issues/7457 open already for tracking the issue, so I’m going ahead and closing this.
