### ISSUE TITLE
Issue with "Response.statusText": (short summary here please)

### ISSUE THREAD

**Issue by devuxer** [mdn/content#10384]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText

#### What information was incorrect, unhelpful, or incomplete?

Doesn't say what the possible values are or even whether they are upper case, title case, etc. I don't think it's necessary to put every possible value, but listing the most common examples (e.g., "OK", "Bad Request", "Unauthorized", "Forbidden", "Not Found", "Request Timeout", "Conflict", and "Internal Server Error") and providing a link to a page describing all the standard status codes would be very helpful.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText#value

#### What did you expect to see?

List of possible values or several examples

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/response/statustext`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/response/statustext/index.md
* Last commit: https://github.com/mdn/content/commit/66d13347b8cf840d1be7a64417920a5a4802b939
* Document last modified: 2021-10-16T17:32:30.000Z

</details>

**Comment by hamishwillee** [comment]
Fixed by https://github.com/mdn/content/pull/10387. I added a few examples and link to more.

**Comment by devuxer** [comment]
@hamishwillee , Nice! Thanks for the quick response!
