### ISSUE TITLE
Issue with "Web technology for developers": …

### ISSUE THREAD

**Issue by BlandJE** [mdn/content#1038]
MDN URL: https://developer.mozilla.org/en-US/docs/Web

#### What information was incorrect, unhelpful, or incomplete?
Dead link under "Code Snippets"

#### Specific section or headline?
Code Snippets

#### What did you expect to see?
A link that lead to an article

#### Did you test this? If so, how?
Yes, Clicked to open in a new tab. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/index.html
* Report started: 2021-01-07T16:04:10.950Z

</details>

**Comment by chrisdavidmills** [comment]
This one got fixed yesterday; see https://github.com/mdn/content/commit/dea99f433199473342fa8994c8843b88efac2560
