### ISSUE TITLE
Add an example showing ths is() does not match pseudo-elements

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#10382]
See https://github.com/mdn/content/pull/10240 and in particular https://github.com/mdn/content/pull/10240#issuecomment-961240824.

**Comment by chris-kruining** [comment]
as mentioned in https://github.com/mdn/content/pull/10240#issuecomment-963463477 I'll give this a shot

**Comment by chris-kruining** [comment]
this can be closed right?

**Comment by wbamberg** [comment]
Yes! Thanks for the fix @chris-kruining !
