### ISSUE TITLE
Issue with "CanvasRenderingContext2D.getImageData()": (The number of opaque black pixels should be 2,500 other than 5,000)

### ISSUE THREAD

**Issue by hustnzj** [mdn/content#10390]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData

#### What information was incorrect, unhelpful, or incomplete?
> The object retrieved by getImageData() has a width of 200 and a height of 100, for a total of 20,000 pixels. Of those pixels, most are either transparent or taken from off the canvas; only 5,000 of them are opaque black (the color of the drawn rectangle).

The number of `opaque black` pixels should be 2,500 other than 5,000

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData#example

#### What did you expect to see?
The number of `opaque black` pixels should be 2,500 other than 5,000

#### Did you test this? If so, how?
Yes.

Just add a `for` loop below the `let imageData = ctx.getImageData(60, 60, 200, 100);` statement as below:
```js
    let count = 0;
    for (let p = 0; p < imageData.data.length; p += 4) {
      if (imageData.data[p + 0] === 0
        && imageData.data[p + 1] === 0
        && imageData.data[p + 2] === 0
        && imageData.data[p + 3] === 255
      ) {
        count++
      }
    }
    console.log(count)
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/getimagedata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/getimagedata/index.md
* Last commit: https://github.com/mdn/content/commit/e26459f9ff49767d68f656795d0dfe1735ebfc20
* Document last modified: 2021-09-18T06:14:07.000Z

</details>

**Comment by abdelrazek-alaa** [comment]
Ok, I'll work on that :slightly_smiling_face:
