### ISSUE TITLE
Issue with "Sending forms through JavaScript": (short summary here please)

### ISSUE THREAD

**Issue by asaf959** [mdn/content#10392]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_forms_through_JavaScript

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/sending_forms_through_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_forms_through_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/sending_forms_through_javascript/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by Anurella** [comment]
Please can you be specific with the issue experienced.

**Comment by hamishwillee** [comment]
Closing, Not enough information to do anything with this.
