### ISSUE TITLE
Issue with "HTMLElement.innerText": (short summary here please)

### ISSUE THREAD

**Issue by serdar87** [mdn/content#10393]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText

#### What information was incorrect, unhelpful, or incomplete?
The result of textContent and result of innerText are similiar. 

#### What did you expect to see?
Result of textContent:

  #source { color: red;  } #text { text-transform: uppercase; }
Take a look athow this textis interpreted
       below.
  HIDDEN TEXT

Result of innerText:
TAKE A LOOK AT
HOW THIS TEXT
IS INTERPRETED BELOW.

#### Did you test this? If so, how?
Yes I have tested it. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlelement/innertext`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/innertext/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Anurella** [comment]
@serdar87 The result is correct, why it appears slightly different from the console is because of the width of the textarea containing the value. If you adjust the size of the textarea, you would get what you want.

**Comment by serdar87** [comment]
The problem happens at Google Chrome not Mozilla Firefox.

**Comment by hamishwillee** [comment]
An easier way to reproduce - open [this `HTML.innerText` link][(https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText#result)) _in a new tab_.

In Chrome this shows the textContent in both boxes. However if you open this in the same tab, or in any way you like in Firefox or Edge the innerText shown in the example is correct.

I think this is some kind of browser issue, but I guess it could be something to do with yari. @sideshowbarker any ideas on next steps for this?

**Comment by sideshowbarker** [comment]
> I think this is some kind of browser issue, but I guess it could be something to do with yari. @sideshowbarker any ideas on next steps for this?

I don’t have any insight to offer on it. I really haven’t been able to make time to look at it in detail
