### ISSUE TITLE
[Prettier] Add an initial Prettier config to the repo

### ISSUE THREAD

**Issue by ddbeck** [mdn/content#10405]
This is part of #10402.

We should check in a basic Prettier configuration to the repository. As a start, we could stipulate that new documents follow Prettier style by creating a `.prettierrc` file and a `.prettierignore` file which contains all the existing Markdown files.

See also:

- [Prettier: Configuration File](https://prettier.io/docs/en/configuration.html)
- [Prettier: Ignoring Code](https://prettier.io/docs/en/ignore.html)

**Comment by nschonni** [comment]
The initial config and ignore has landed now

**Comment by Josh-Cena** [comment]
Yep, I think this is good.
