### ISSUE TITLE
Issue with "Function expression": (short summary here please)

### ISSUE THREAD

**Issue by Pranav108** [mdn/content#10410]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function

#### What information was incorrect, unhelpful, or incomplete?
Expecting the sentence to be more clear , though able to understand it later . But still suggestion for improvement in 1st line of second paragraph under the heading mentioned below.

#### Specific section or headline?
In the second paragraph of headline "Named function expression".

#### What did you expect to see?
Need grammatical improvement

#### Did you test this? If so, how?
Asked to one of my friend ,initially he was also confused but later on understood.
![functionMDN](https://user-images.githubusercontent.com/56934594/140938236-940a787c-4cf7-4a2b-83f3-cb9a00502525.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/function/index.md
* Last commit: https://github.com/mdn/content/commit/7ad5af1a66f88e5ea9f3834c76cd77be76ee03c3
* Document last modified: 2021-09-22T01:11:56.000Z

</details>

**Comment by wbamberg** [comment]
Ha, yes, I saw that bug and it's true, it's an ugly sentence. Do you like:

> The variable to which the function expression is assigned will have a name property.

?
