### ISSUE TITLE
Examples in tables not rendering correctly

### ISSUE THREAD

**Issue by rebloor** [mdn/content#10413]
## What page(s) did you find the problem on?

Any Manifest keys page where code examples are included in a table, for example, [browser_action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action)

## What is the problem?

Curly braces on rendering in the code examples:

<img width="963" alt="image" src="https://user-images.githubusercontent.com/7352080/140956323-b1fbd821-7deb-478f-9b53-60187db8b20e.png">

is generated from

<img width="448" alt="image" src="https://user-images.githubusercontent.com/7352080/140956607-ded1a8fd-e2a2-4acb-a8ec-a9dcf4c9aa10.png">

## What did you expect to see?

Curly braces rendered.

**Comment by wbamberg** [comment]
They are rendered, they are just invisible 😭.

@schalkneethling , this looks like https://github.com/mdn/yari/issues/4254, which is closed. Do you know if it's the same issue again?

**Comment by schalkneethling** [comment]
![Screenshot showing the table rendering issue being resolved.](https://user-images.githubusercontent.com/10350960/141073400-558690fe-b35b-43a4-bf5f-01312e750857.png)

The new version of minimalist was released yesterday. The above is how it looks now in production so, I reckon we are good to go now.

**Comment by rebloor** [comment]
Looks good, thanks @schalkneethling
