### ISSUE TITLE
Issue with "Document.currentScript": …

### ISSUE THREAD

**Issue by plfstr** [mdn/content#1042]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript

#### What information was incorrect, unhelpful, or incomplete?
> (For modules use import.meta instead.) 

‘import.meta’ includes a non-clickable link. 
A hover tooltip suggest this content hasn't been written. 
However, there is a page for this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta

#### Specific section or headline?
Opening paragraph + ‘See also’ section at the bottom of the page

#### What did you expect to see?
A link to the import.meta page

#### Did you test this? If so, how?
I clicked with increasing confusion. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/currentscript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/document/currentscript/index.html
* Report started: 2021-01-07T17:26:12.882Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/1107 with a fix.

Incidentally, the https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript example linked to in this article doesn’t actually work as intended — but I couldn’t actually find if/where the source for it is stored; so I raised https://github.com/mdn/yari/issues/2414 for that.
