### ISSUE TITLE
Issue with "Beginner's guide to media queries": (Broken text formatting)

### ISSUE THREAD

**Issue by Den0702** [mdn/content#10426]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Media_queries

#### What information was incorrect, unhelpful, or incomplete?
A problem with formatting on this page have appeared. As it turned out, that's not the only page. This [HTML Structure](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure) page has the same problem. That's why I think there are must be more pages, where text formatting have been broken.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/css_layout/media_queries`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Media_queries
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/media_queries/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing. Can you be specific about what's broken here?

**Comment by hamishwillee** [comment]
I can't see anything broken. @Den0702 can you please show a screenshot of the part of the formatting you think is wrong, and let us know what browser you are using?

**Comment by wbamberg** [comment]
Closed as unresponsive.
