### ISSUE TITLE
Issue with "DOMTokenList.replace()": incomplete examples section

### ISSUE THREAD

**Issue by AtomEistee** [mdn/content#10429]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/replace

#### What information was incorrect, unhelpful, or incomplete?
Examples section have "The output looks like this:" but there is no output.

#### Specific section or headline?
Examples.

#### What did you expect to see?
The output from js and html.

#### Did you test this? If so, how?
No i didnt.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/domtokenlist/replace`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/replace
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/domtokenlist/replace/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by teoli2003** [comment]
I see this:
<img width="286" alt="Screenshot 2021-11-10 at 16 30 34" src="https://user-images.githubusercontent.com/1466293/141142488-d44b7eca-8738-44d9-a63e-6ba35588a1ec.png">

Sounds good to me.

**Comment by AtomEistee** [comment]
but i see this:
![image](https://user-images.githubusercontent.com/36533957/141167649-f705b0f9-abc6-40d5-a188-4d7c1376cdf0.png)

**Comment by teoli2003** [comment]
Do you have something blocking iframes?

**Comment by AtomEistee** [comment]
Im not sure, adblock?

**Comment by AtomEistee** [comment]
oh yes you right, it was adblock fault, sorry
