### ISSUE TITLE
Clarify behavior of webRequest.filterResponseData()

### ISSUE THREAD

**Issue by rebloor** [mdn/content#10432]
## What page(s) did you find the problem on?

[webRequest.filterResponseData()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData) and [webRequest.StreamFilter](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/StreamFilter)

## What did you expect to see?

Information explaining that once the `filterResponseData` has been created, that the extension is given full control over response, and that it should have an `ondata` listener to process the stream (even if it's just `filter.write(event.data)`) and the extension should be calling `close()` or `disconnect()`.

See  [Bug 1738877](https://bugzilla.mozilla.org/show_bug.cgi?id=1738877) Warn on badly used browser.webRequest.filterResponseData

**Comment by Rob--W** [comment]
Fixed by https://github.com/mdn/content/pull/12349
