### ISSUE TITLE
Content update: -webkit-text-security is now input-security

### ISSUE THREAD

**Issue by jensimmons** [mdn/content#10438]
## What page(s) did you find the problem on?
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-security

## What is the problem?
In 2018, the CSSWG resolved to standardize `-webkit-text-security` as a new CSS property, `input-security`. 
- Resolution: https://github.com/w3c/csswg-drafts/issues/2495
- Web standard: https://drafts.csswg.org/css-ui-4/#input-security

## What did you expect to see?
The MDN page should be updated to reflect the new property, with a BDC chart of support data.

**Comment by Elchi3** [comment]
Is `input-security` a replacement of  `-webkit-text-security`? 

Asking because we need to decide if we should have two separate features/pages or if we should have one page (with a note that there has been a non-standard  `-webkit-text-security` before). Context: https://github.com/mdn/browser-compat-data/pull/12822

**Comment by lukewarlow** [comment]
Also relevant https://github.com/mdn/data/pull/512

**Comment by Elchi3** [comment]
@jensimmons (or @rachelandrew maybe?) is `input-security` a replacement of `-webkit-text-security`? 
That is, should we document `input-security` **instead** of `-webkit-text-security`? Or are both too different and we would rather have two features and two MDN pages?

**Comment by Elchi3** [comment]
No response here unfortunately.

Meanwhile Webkit removed input-security again, see https://bugs.webkit.org/show_bug.cgi?id=235557:
"The input-security property is planned to be removed from CSS UI 4. See https://github.com/w3c/csswg-drafts/issues/6788."

Closing.
