### ISSUE TITLE
Issue with "SyntaxError: function statement requires a name": (short summary here please)

### ISSUE THREAD

**Issue by jaradc** [mdn/content#10436]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unnamed_function_statement

#### What information was incorrect, unhelpful, or incomplete?
Grammar

#### Specific section or headline?
Examples

#### What did you expect to see?
Or, **you** function is maybe intended to be an

should be

Or, **your** function is maybe intended to be an

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/unnamed_function_statement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unnamed_function_statement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/unnamed_function_statement/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. Fixed by #10466

FYI, if you're fairly sure that there is an error you can propose a fix yourself. At the bottom of every page there is an "Edit on Github" link that will take you to the page for editing.
