### ISSUE TITLE
Issue with "Hypertext": …

### ISSUE THREAD

**Issue by emilyTK** [mdn/content#1044]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Hypertext

#### What information was incorrect, unhelpful, or incomplete?
link: Hypertext Information Base

#### Specific section or headline?
Technical Reference

#### What did you expect to see?
A working link

#### Did you test this? If so, how?
I clicked the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/hypertext`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Hypertext
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/glossary/hypertext/index.html
* Report started: 2021-01-07T17:53:18.073Z

</details>

**Comment by chrisdavidmills** [comment]
Thansk for reporting, @emilyTK !

I don't have an equivalent link, so I've just deleted it for now; see https://github.com/mdn/content/commit/b48f29a0626a58d26ae051d47dfd2f9655563c32
