### ISSUE TITLE
Issue with "<area>: The Image Map Area element": "default" is given as a possible value for the "coords" attribute

### ISSUE THREAD

**Issue by angleKH** [mdn/content#10447]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area

#### What information was incorrect, unhelpful, or incomplete?
The page says that the `coords` attribute can be provided a value of `default`, while the [HTML standard](https://html.spec.whatwg.org/multipage/image-maps.html#attr-area-shape-default) says:
> In the default state state, area elements must not have a coords attribute.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/area`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/area/index.md
* Last commit: https://github.com/mdn/content/commit/da7f599549a6a36371b9bd9848fa0e3d51379196
* Document last modified: 2021-10-25T20:11:36.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. Fixed by #10468
