### ISSUE TITLE
Issue with "Forwarded": Multiple values example is misleading

### ISSUE THREAD

**Issue by jido** [mdn/content#10456]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded

#### What information was incorrect, unhelpful, or incomplete?

This example:

```
# multiple values can be appended using a comma
Forwarded: for=192.0.2.43, for=198.51.100.17
```

It suggests that a single proxy can specify multiple values for one parameter (in this example "for"), which is not the intention and could lead to incorrect implementations.

#### Specific section or headline?

Examples

#### What did you expect to see?

The comma-separated list is intended to allow successive proxies to add their contribution to the header according to the RFC.
https://datatracker.ietf.org/doc/html/rfc7239#section-4

The example could be improved by showing more than one parameter being repeated:

```
# successive proxies can append values in a comma-separated list
Forwarded: by=192.0.4.51;for=192.0.2.43, by=198.51.4.4;for=198.51.100.17
```

#### Did you test this? If so, how?

No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/forwarded`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/forwarded/index.md
* Last commit: https://github.com/mdn/content/commit/966363413c429c7020f20f6ebe7f0a8b679812a9
* Document last modified: 2021-10-03T11:06:03.000Z

</details>

**Comment by hamishwillee** [comment]
@jido Thanks very much. That example is actually from the spec. That makes sense in the spec because it clearly identifies that this header can be added/modified by a chain of proxies.

To me the problem here is that the MDN doc does not draw that distinction - it infers the there can only be one proxy so yes, you might well assume that one proxy added all the headers.

I will attempt a fix :-)

**Comment by hamishwillee** [comment]
Done. There is quite a bit of change but the most important bit in the example is to change the text to say "Values from multiple proxy servers can be appended using a comma"
