### ISSUE TITLE
Issue with "<a>: The Anchor element": There is no treatment of empty anchor tag

### ISSUE THREAD

**Issue by boom100100** [mdn/content#10459]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

#### What information was incorrect, unhelpful, or incomplete?

Incorrect: the documentation shows a glyph associated with empty anchor tags if you edit the very first example to remove the anchor tag's text. This is true for when the anchor tag is nested in the list item, and when the anchor tag has been moved to outside of the unordered list.

```
<a href="https://example.com"></a>


<ul>
  <li><a href="https://example.com"></a></li>
</ul>
```

<img width="876" alt="Screen Shot 2021-11-11 at 4 26 40 PM" src="https://user-images.githubusercontent.com/18746369/141371971-31565f14-6791-49f8-84ec-1cc63b4daf77.png">

Incomplete: the documentation doesn't specify the behavior that should happen or any ways to work around it that would allow for a seemingly empty value for anchor tag text.

#### Specific section or headline?
<a>: The Anchor element

#### What did you expect to see?
I expected the example I provided not to show anything in that anchor tag's soace, as this seems to be the default behavior for anchor tags. My main reason for looking for this specific information is that I wanted to know what would be a good default value for if no text should appear that would still allow the link to render, like maybe a &nbsp; *edit non breaking space, but I understand that may be too implementation-specific.

#### Did you test this? If so, how?
Yes. See code and image above.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/a`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/a/index.md
* Last commit: https://github.com/mdn/content/commit/8fb27535e5b0ab8f16798c00e74531792c34a4b9
* Document last modified: 2021-11-04T08:43:49.000Z

</details>

**Comment by wbamberg** [comment]
In that example the "🔗" etc characters appear because the CSS sets them using [`::before`](https://developer.mozilla.org/en-US/docs/Web/CSS/::before). You can see this by switching to the "CSS" tab in the demo:

<img width="324" alt="Screen Shot 2021-11-12 at 8 49 43 AM" src="https://user-images.githubusercontent.com/432915/141503973-e01f9bd3-0487-4aaf-8456-95a9c93437c8.png">

Without that the example would indeed show nothing if you remove the text, and you can confirm that by editing the CSS.

But now you mention this I can see how this is confusing and I'd support removing that CSS from the example, so we just show the basic default behavior. What do you think?

**Comment by boom100100** [comment]
That change sounds reasonable. Perhaps adding these icons via a class and showing with and without the class would be more illustrative.

Should the other points in this issue (guidance on dealing with an anchor tag with no text child) be separated out into a new issue?

**Comment by wbamberg** [comment]
> That change sounds reasonable. Perhaps adding these icons via a class and showing with and without the class would be more illustrative.

These demos at the tops of pages are really supposed to be short and simple illustrations of the basic usage of a feature, so I don't think we need to go into that level of detail here.

> Should the other points in this issue (guidance on dealing with an anchor tag with no text child) be separated out into a new issue?

Probably. I wasn't sure what the other points in the issue were really. If you don't have any content in the anchor, then you won't see anything. I'm not sure why you would want to do that.

**Comment by boom100100** [comment]
I see, your suggestion sounds like the best way to go, then. I'll make a new issue for the other points.

**Comment by wbamberg** [comment]
Thanks! I filed https://github.com/mdn/interactive-examples/pull/1946 to remove the styling from the example.

**Comment by teoli2003** [comment]
We will need to wait for a deployment to see it live in production, but this is fixed.
