### ISSUE TITLE
Issue with "Graceful asynchronous programming with Promises": A lot of it was broken English, which complicates the learning process

### ISSUE THREAD

**Issue by JosephCWatkins** [mdn/content#10464]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises

#### What information was incorrect, unhelpful, or incomplete?
A lot of it was broken English, which complicates the learning process. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/promises/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! If you can, it would really help to be as specific as possible in describing the problems you found. This will help us to fix them.

**Comment by wbamberg** [comment]
@JosephCWatkins , we recently rewrote this bit of the Learning Area: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous. I hope it is more comprehensible now and we'll be able to close this issue.

If it isn't, please give specific examples of what the problems are - just saying "A lot of it was broken English" isn't really specific enough for us to fix. Thanks!

**Comment by wbamberg** [comment]
Closing as there's been no response.
