### ISSUE TITLE
Issue with "globalThis": ("the global across environments" content is outdated))

### ISSUE THREAD

**Issue by Southhill** [mdn/content#10470]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

#### What information was incorrect, unhelpful, or incomplete?
> Prior to globalThis, the only reliable cross-platform way to get the global object for an environment was Function('return this')(). However, this causes CSP violations in some settings, so es6-shim uses a check like this, for example:

[the global across environments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#search_for_the_global_across_environments) content is outdated.

[es6-shim](https://github.com/paulmillr/es6-shim) source code is changed, for example:

```javascript
var getGlobal = new Function('return this;');
```
link: https://github.com/paulmillr/es6-shim/blob/master/es6-sham.js#L31

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/globalthis`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/globalthis/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by Josh-Cena** [comment]
This is because `es6-shim` and `es6-sham` are two things. You can find `es6-shim`'s related source here: https://github.com/paulmillr/es6-shim/blob/c3eb45b440092c53597e092cee47cedb578f4c24/es6-shim.js#L176-L187

The idea of a sham is that—IIUC—it just provides the existence of an API, but does not provide any behaviors, so the implementation appears to be quite cracky.
