### ISSUE TITLE
Issue with "Date.prototype.toLocaleDateString()": Expected outputs not matching in Playground

### ISSUE THREAD

**Issue by mmartinsky** [mdn/content#10483]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

#### What information was incorrect, unhelpful, or incomplete?
The expected outputs in the topmost sandbox do not match the results clicking Run. I am in EST, GMT-5, on MacOS Catalina / Chrome 95.0.4638.69

![image](https://user-images.githubusercontent.com/9168958/141516936-ace6efd6-e51c-44e8-b0ed-7d81fc45045a.png)

#### Specific section or headline?
JavaScript Demo: Date.toLocaleDateString()

#### What did you expect to see?
Donnerstag, 20. Dezember 2012
الخميس، ٢٠ ديسمبر، ٢٠١٢
Thursday, December 20, 2012

#### Did you test this? If so, how?
Click Run on the first sandbox

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/tolocaledatestring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks! You're a day early in your timezone (i.e. 3 am take away 5 hours UTC puts us on 19th).. That wasn't obvious in the page, so I have fixed this in the text of the page in #10525
