### ISSUE TITLE
Issue with "Basic concepts of flexbox": typo in total container size

### ISSUE THREAD

**Issue by Elbasel** [mdn/content#10486]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox

#### What information was incorrect, unhelpful, or incomplete?
In the below paragraph:

The flex-grow property can be used to distribute space in proportion. If we give our first item a flex-grow value of 2, and the other items a value of 1 each, 2 parts will be given to the first item (100px out of 200px in the case of the example above), 1 part each the other two (50px each out of the 200px total).

The total size of the container in the example is 500px not 200px which can be confusing for new learners.

#### Specific section or headline?
The flex-grow property

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_flexible_box_layout/basic_concepts_of_flexbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
* Last commit: https://github.com/mdn/content/commit/195882ad9880c3fbd8c0b01a9350f32013ade250
* Document last modified: 2021-09-24T19:04:40.000Z

</details>

**Comment by smalllong** [comment]
Hey, I believe this issue and the related MR is a mistake. In the article the space which can be distributed by flex-grow is the available space which is 200px rather than the whole 500px. Maybe we can make it not confusing by adding 'available' before 'space' in the paragraph @Elbasel @anushkachauhxn @teoli2003

**Comment by wbamberg** [comment]
> Hey, I believe this issue and the related MR is a mistake. In the article the space which can be distributed by flex-grow is the available space which is 200px rather than the whole 500px. Maybe we can make it not confusing by adding 'available' before 'space' in the paragraph @Elbasel @anushkachauhxn @teoli2003

Yes, I think you are right. See also https://github.com/mdn/content/pull/11735.
