### ISSUE TITLE
Issue with "Using the alert role": …

### ISSUE THREAD

**Issue by harlanlewis** [mdn/content#1048]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role

#### What information was incorrect, unhelpful, or incomplete?
404 errors on links to working examples:
- http://www.oaa-accessibility.org/example/1/
- http://www.oaa-accessibility.org/examplep/alertdialog1/

#### Specific section or headline?
Example 4 > Working Examples > links

#### What did you expect to see?
The links to resolve on working examples.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/aria_techniques/using_the_alert_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/accessibility/aria/aria_techniques/using_the_alert_role/index.html
* Report started: 2021-01-07T20:27:50.174Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve raised #1076 with a fix
