### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by sergeii-55** [mdn/content#1049]
Spanish version of:
https://developer.mozilla.org/es/docs/Web/JavaScript/Una_re-introducci%C3%B3n_a_JavaScript

got a  typo error naming the length attribute

![JSss](https://user-images.githubusercontent.com/25111770/103948591-3ddd7580-50f7-11eb-832d-c52fbd169d64.png)

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
