### ISSUE TITLE
Issue with "DOMTokenList": (spelling issue 'DOMTokkenList')

### ISSUE THREAD

**Issue by ScottHuston** [mdn/content#10495]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList

#### What information was incorrect, unhelpful, or incomplete?

Misspelled as DOMTokkenList

<pre>
A DOMTokkenList is indexed beginning with 0 as with JavaScript Array objects. DOMTokenList is always case-sensitive.
</pre>

#### Specific section or headline?

Initial section

#### What did you expect to see?

DOMTokenList vs DOMTokkenList

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/domtokenlist`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/domtokenlist/index.md
* Last commit: https://github.com/mdn/content/commit/d9dbab6fdafbce717073cbad9fbb6e2cdfcf9bd5
* Document last modified: 2021-11-11T17:53:47.000Z

</details>

**Comment by teoli2003** [comment]
Thanks, I fixed the typo in the PR. Sorry, my keyboard is duplicating some letters and I missed this one. The new computer arrives next week with a working keyboard :-)
