### ISSUE TITLE
Issue with "OfflineAudioContext.oncomplete": missing parameter documentation

### ISSUE THREAD

**Issue by MRossignol** [mdn/content#10491]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/oncomplete

#### What information was incorrect, unhelpful, or incomplete?

The documentation doesn't mention (either in the text or in the example) the OfflineAudioCompletionEvent parameter that's passed to the function when it gets called. You can only discover it in the documentation of OfflineAudioContext.startRendering .

#### What did you expect to see?

Some information on how to access the rendered audio once it's ready.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/offlineaudiocontext/oncomplete`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/oncomplete
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/offlineaudiocontext/oncomplete/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment]
While that is technically true probably not such a big deal considering:
1. **All** onXxxx message handlers take an event of the type specified as the parameter.
2. The example here doesn't do anything with the event, because there is nothing to do with it. Well technically you could use `OfflineAudioCompletionEvent.renderedBuffer` - need to check if this is actually deprecated or not according to the spec.

**Comment by hamishwillee** [comment]
@Elchi3 I don't want to do anything with this while you're [evolving the event structure](https://github.com/mdn/content/discussions/10544). I've assigned to you, but feel free to dump back on me once we have an executable plan.

**Comment by Elchi3** [comment]
The event is now documented as https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/complete_event and I believe the problem no longer exist on this new page.
