### ISSUE TITLE
Issue with "with": Additional example

### ISSUE THREAD

**Issue by manngo** [mdn/content#10502]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with

#### What information was incorrect, unhelpful, or incomplete?

Not a problem, but the note indicates that `with` is discourage, and suggests assigning a temporary variable. Perhaps destructuring the object could also be an alternative. In particular, the example using the `Math` object won’t benefit from assigning a temporary variable, but will from destructuring:

```js
let a, x, y;
const r = 10;

var {PI, sin, cos} = Math;	//	or let or const

a = PI * r * r;
x = r * cos(PI);
y = r * sin(PI / 2);
```

Something like this could be given as an additional example, given that destructuring is only supported on current versions.

I can do this myself but I would like an opinion on this first.

#### Specific section or headline?

na

#### What did you expect to see?

na

#### Did you test this? If so, how?

na

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/with`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/with/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks @manngo for reporting this issue. I like your idea of suggesting alternatives besides just prohibiting. May I suggest creating a PR to draw more attention to this issue (and the proposed fix). Thanks

**Comment by wbamberg** [comment]
Sorry to be slow replying. I agree with @himanshugarg , this sound like a good idea and I think it would be great to see a PR for it!
