### ISSUE TITLE
Issue with "Marking up a letter": Unclear Project Brief description

### ISSUE THREAD

**Issue by AstronautAnonymous** [mdn/content#1050]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter

#### What information was incorrect, unhelpful, or incomplete?
The direction to "Mark up the five acronyms/abbreviations in the main text of the letter to provide expansions of each acronym/abbreviation" is unclear.

- As can be inferred from the dotted underlines in the image of the letter, the five abbreviations are supposed to be, in order, "PhD," "HTML," "CSS," "BC," and "Esq." However, this ignores that "C" (Centigrade) and "F" (Fahrenheit) are both in the main text of the letter, and no guidance is provided why they are not meant to be marked up.
- As well, "Esq." also likely falls outside the "main text" of the letter because it is after the signature and therefore in an area that semantically should likely be marked as the footer; if we include "Esq." as part of the "main text," then that implies that the "Dr." in the signature should also be considered part of the "main text."

If we include "C," "F," and "Dr.," then we have eight total abbreviations. (As well, there is a further "Dr." in the address at the top, though that is more obviously not semantically part of the main text of the letter.)

#### Specific section or headline?

The unclear instruction is listed in the "Inline semantics" subsection of the "Project Brief."

#### What did you expect to see?

I think the clearest instruction would list which abbreviations should be expanded. I'm not sure there is any benefit in expecting the learner to guess what counts as an abbreviation.

However, if you believe there _is_ an advantage to not explicitly identifying the abbreviations, then I think it should either say something like "Mark up the **eight** acronyms/abbreviations in the main text of the letter (including the signature)..." or it should say something like "Mark up the **six** acronyms/abbreviations in the main text of the letter (not including the address or signature)..." [the latter would include "C" and "F," but not include "Dr." or "Esq."].

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/marking_up_a_letter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/html/introduction_to_html/marking_up_a_letter/index.html
* Report started: 2021-01-07T20:53:09.315Z

</details>

**Comment by chrisdavidmills** [comment]
I think you've got a fair point here; thanks for reporting it.

I've fixed this via https://github.com/mdn/content/commit/77f8b68d0e3de5f7630bbda36c51199c4a3f9914
