### ISSUE TITLE
Issue with "SyntaxError: invalid regular expression flag "x"": (short summary here please)

### ISSUE THREAD

**Issue by jespertheend** [mdn/content#10521]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_regexp_flag

#### Specific section or headline?
"are not one of g, i, m, s, u, or y."
"but there are only six of them in ECMAScript"
and the table

#### What did you expect to see?
Mentioning of the `d` flag

#### Did you test this? If so, how?
I am actively using the `d` flag right now.

The `d` flag is quite new. So maybe it should't be added quite yet. Or perhaps with a disclaimer.
Here's a [compat table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/hasIndices#browser_compatibility) for the `hasIndices` property.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/bad_regexp_flag`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_regexp_flag
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/bad_regexp_flag/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, fixed by #10523. The flag is documented in other places. I've tidied this up a bit.
