### ISSUE TITLE
Issue with "Array.prototype.reduce()": (short summary here please)

### ISSUE THREAD

**Issue by Paynethegenius** [mdn/content#10524]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

#### What information was incorrect, unhelpful, or incomplete?
the section that demonstrates how the reduce function works starts out at index 1 not zero. based on previous explanations, that doesn't seem  right.

#### Specific section or headline?
How reduce() works

#### What did you expect to see?

at first call the table should read  previous value = 0, current value = 0, current index = 0, array [0,1,2,3,4]  return value 0
then the next should iterate appropriately

#### Did you test this? If so, how?
by walking through

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/reduce`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/reduce/index.md
* Last commit: https://github.com/mdn/content/commit/5e1522e6fd662d5e46c941824798bfffa04e5de3
* Document last modified: 2021-10-22T17:38:41.000Z

</details>

**Comment by hamishwillee** [comment]
Yes, but it is right. 

I presume you are talking about this section: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#how_reduce_works

Here we have the method. Just run it and you can see that the index does start at 1:
```js
[0, 1, 2, 3, 4].reduce(function(previousValue, currentValue, currentIndex, array) {
  console.log("currIndx: " + currentIndex);
  return previousValue + currentValue
})
```

@wbamberg We don't actually say how the `currentIndex` is iterated (i.e. 1 rather than 0 based. OK to you if I add that here:

![image](https://user-images.githubusercontent.com/5368500/141728734-884424df-b6b8-4b4b-8487-2a5d6a0cc9be.png)

**Comment by anushkacreates** [comment]
Hey,

If you run this code:

```
[0, 1, 2, 3, 4].reduce(function(previousValue, currentValue, currentIndex, array) {
  console.log(previousValue, currentValue, currentIndex, previousValue + currentValue)
  return previousValue + currentValue
})
```

The output is:

![image](https://user-images.githubusercontent.com/59930625/141828733-ba721c6d-4bce-4d3f-8a6f-990d28631a9d.png)

**Comment by wbamberg** [comment]
`currentIndex` is the index of the `currentValue` argument in the array.

If you don't pass an `initialValue` to `reduce()` then the first time `callbackFn` is called:
* `previousValue` is the first element in the array
* `currentValue` is the **second** element
* `currentIndex` is therefore 1

If you do pass an `initialValue` to `reduce()` then the first time `callbackFn` is called:
* `previousValue` is `initialValue`
* `currentValue` is the **first** element
* `currentIndex` is therefore 0

I think this is explained reasonably well in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#how_reduce_works and I don't see any errors there. It might be worth updating the bit you quoted to add something like:

> * previousValue (the value resulting from the previous call to callbackfn)
> * currentValue (the value of the current element)
> * currentIndex Optional **(the index position of currentValue in the array)**
> * array (the array to traverse) Optional

We could perhaps improve https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#how_reduce_works a bit by:

* choosing values for the array that aren't the same as the indices
* just making them all use arrow functions skipping that distracting bit about "you can use arrow functions")
* having H4 headings like "Without an initialValue argument" and "With an initialValue argument" to emphasise the difference between the two cases shown.

I'm also not wild about the huge blockquote from the spec in this page. If we can't explain this better than the spec does we're not adding any value. (though this isn't helped by our rather confusing blockquote style)

**Comment by wbamberg** [comment]
Also I'm not sure what "Optional" is doing in:

> previousValue (the value resulting from the previous call to callbackfn)
> currentValue (the value of the current element)
> currentIndex Optional
> array (the array to traverse) Optional

I mean they're optional in that the callback function had no obligation to make use of them, but that's true of any function parameter:

```js
const array1 = [1, 2, 3, 4];
const reducer = () => console.log("hey!");
```

**Comment by hamishwillee** [comment]
@wbamberg Thanks very much for that feedback. Taken on board and results in update in #10555. That includes the separate headings for examples and different numbers for the example.

You may not recall that the spec-in-text was a relatively recent addition because the previous attempt to do this in text confused people. I completely agreed that this could be done without the big quote, but it would take care, and more time than I feel like investing on this right now.

**Comment by wbamberg** [comment]
I didn't recall that, no! Although I do remember tangling with this page recently. I might have a go at doing that once we have merged your PR.
