### ISSUE TITLE
Content suggestion: Window Controls Overlay for PWAs

### ISSUE THREAD

**Issue by captainbrosset** [mdn/content#10539]
## What is the new suggestion?
I'm proposing to add some documentation content for the Window Controls Overlay feature of PWAs.

This feature is implemented in Chromium, and while it's been on origin trial up until now, is going to be globally available in Chrome and Edge soon.

It allows PWAs on desktop to make use of the top window area normally reserved for the title bar.
The feature is documented in these places right now:

* https://web.dev/window-controls-overlay/
* https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/window-controls-overlay

And is spec'd as a WICG explainer: https://github.com/WICG/window-controls-overlay/blob/main/explainer.md and wicg spec draft: https://wicg.github.io/window-controls-overlay/

## Why is it important or useful?

The feature is implemented, and changes how PWAs look on desktop quite a lot. It gives web authors opportunities to really make their apps "native"-looking. It's important to document the various APIs that it depends on.

The main changes that would be needed are:

- [x] Adding the `display_overrides` member to https://developer.mozilla.org/en-US/docs/Web/Manifest
- [x] Documenting the `window-controls-overlay` value on the `display_overrides` page
- [x] Adding the `titlebar-area-*` environment variables to https://developer.mozilla.org/en-US/docs/Web/CSS/env()
- [x] Documenting the `navigator.windowControlsOverlay` API

**Comment by captainbrosset** [comment]
If there's no objections about adding this content to MDN/BCD, I will start working on this soon.

**Comment by sideshowbarker** [comment]
@captainbrosset Seeing no objections to this, it seems like you can go ahead with it

**Comment by captainbrosset** [comment]
All of the PRs have now been merged. So I'll close this issue.
The only outstanding task is to update MDN's dependency to BCD so that the right compat-data/specs information shows up.
