### ISSUE TITLE
Issue with "Window.scrollTo()": there is no 'instant' option in scrollTo()

### ISSUE THREAD

**Issue by DevelopSoo** [mdn/content#10538]
I used scrollTo and put options like below.
ex) 
`window.scrollTo({top:` 100, left: 0, behavior: instant})`

![스크린샷 2021-11-15 오후 6 29 59](https://user-images.githubusercontent.com/69490984/141756936-8c37a620-8131-4917-a48f-22bffb7e3075.png)

But I found there is no 'instant' in scrollTo method options
<img width="438" alt="스크린샷 2021-11-15 오후 6 33 24" src="https://user-images.githubusercontent.com/69490984/141757462-8a5a7a40-5ba8-4efc-a7e0-18972f07f361.png">

I'd like page to move some place instantly. But in Chrome, it moves smoothly.
But in Safari, it moves instantly

Could you tell me why this happens, if you don't mind?

For your information, my node version is 10.16.3
and I'm using typescript and target of compilerOptions is "es5"

if you need any more information, please tell me

**Comment by wbamberg** [comment]
This looks like another place MDN needs to be updated to reflect https://github.com/w3c/csswg-drafts/issues/2146 , like https://github.com/mdn/content/issues/10265. As far as I see from that (and https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior), `auto` ought to mean "instant".
