### ISSUE TITLE
Issue with "font-variation-settings": Wrong Specification (both text and link)

### ISSUE THREAD

**Issue by BartolomeSintes** [mdn/content#10535]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variation-settings

#### What information was incorrect, unhelpful, or incomplete?
I would say that there are two errors in the Specifications section:
1. font-variation-settings is defined in CSS Fonts 4, not CSS Fonts 5.
2. the link links to the wrong id (#font-rend-desc instead of #font-variation-settings-de

#### Specific section or headline?
Specifications
[CSS Fonts Module Level 5 (CSS Fonts 5)](https://drafts.csswg.org/css-fonts/#font-rend-desc)

#### What did you expect to see?
[CSS Fonts Module Level 4 (CSS Fonts 4)](https://drafts.csswg.org/css-fonts/#font-variation-settings-def)

#### Did you test this? If so, how?
Yes. Clicking the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/font-variation-settings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variation-settings
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-variation-settings/index.md
* Last commit: https://github.com/mdn/content/commit/707a37cd04dcc1f555e9adbaba4b236cd8b9d27c
* Document last modified: 2021-09-18T04:33:12.000Z

</details>

**Comment by Rumyra** [comment]
The data for the spec urls is held in https://github.com/mdn/browser-compat-data - I've updated it there - see mentioned pr above 👍
