### ISSUE TITLE
Issue with "Stacking context example 2": (short summary here please)

### ISSUE THREAD

**Issue by monika-petkova** [mdn/content#10543]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_context_example_2

#### What information was incorrect, unhelpful, or incomplete?
- root stacking context
  - DIV 2 (z-index 2)
  - DIV 3 (z-index 1)
    - DIV 4 (z-index 10)

#### Specific section or headline?
Stacking context example 2

#### What did you expect to see?
- root stacking context
  - DIV 3 (z-index 1)
    - DIV 4 (z-index 10)
  - DIV 2 (z-index 2)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_2`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_context_example_2
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_2/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by wbamberg** [comment]
Closing per https://github.com/mdn/content/pull/10549#issuecomment-1010234780.
