### ISSUE TITLE
Content bug: Function indexOF

### ISSUE THREAD

**Issue by sruiNascimento** [mdn/content#10563]
The function indexOf has a problem.
for example:
const name = "Rui";
console.log(name.indexOf("R"));
the result is index = 0
However if i to try
console.log(name.indexOf(""))
the result is index=0 too.

Bug??
![bugIndexOF](https://user-images.githubusercontent.com/57668890/141983664-9331f930-ba15-47e4-985a-8d9c1b55c370.PNG)
?

**Comment by sruiNascimento** [comment]
I'm learning JS, but the result is ambiguous

**Comment by AnilSeervi** [comment]
You are searching for empty strings within a String which is basically present everywhere within a String. That is why you can split a String into Array at every element using `String.split("")`

So `.indexOf("", fromIndex)` will return the `fromIndex`(if passed) or 0 if `fromIndex` isn't passed.

**Comment by wbamberg** [comment]
That's the [specced behavior](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-stringindexof), and is documented in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf#return_value .
