### ISSUE TITLE
Issue with "Express Tutorial Part 3: Using a Database (with Mo…": Missing the require of Luxon's package DateTime function

### ISSUE THREAD

**Issue by santimirandarp** [mdn/content#10566]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

#### What information was incorrect, unhelpful, or incomplete?
Missing the require of Luxon's package DateTime function. 

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#author_model

#### What did you expect to see?
`const {DateTime}  = require('luxon');

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by hamishwillee** [comment]
Nowhere in this page do we refer to luxon or need to do any formatting of the times. That comes later on in the tutorial: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Date_formatting_using_moment

I'm therefore closing this as invalid.

**Comment by hamishwillee** [comment]
It's part of the JavaScript language AFAIK so it doesn't need to be specifically imported.

**Comment by hamishwillee** [comment]
I'll have a look at this on Friday.

**Comment by sideshowbarker** [comment]
ping @hamishwillee

**Comment by hamishwillee** [comment]
Thanks very much. This was fixed in https://github.com/mdn/content/pull/10992
