### ISSUE TITLE
Issue with "Client.postMessage()": Page does not give a full code example, or enough context to create one

### ISSUE THREAD

**Issue by ChristopherWirtOfficial** [mdn/content#10573]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Client/postMessage

#### What information was incorrect, unhelpful, or incomplete?
When providing an example of how to get a client from an eventId, there is not enough context to know where the `clients` variable comes from, and it takes another scroll through the docs or another google search to be able to paint the whole picture.

#### Specific section or headline?
Examples

#### What did you expect to see?
I would have expected an example that shows the user one or more of the following:
a) How to match all clients, or a specific client (not necessarily explaining the code, but to give a full example)
b) The main article about getting a client or a list of clients from a servicer worker.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/client/postmessage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Client/postMessage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/client/postmessage/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Josh-Cena** [comment]
@ChristopherWirtOfficial It's quite an old issue, but: This is a complete example, because `clients` is a global in the worker scope. What do you think is missing?

**Comment by ChristopherWirtOfficial** [comment]
It's a set of implied semantics that doesn't offer someone a complete cold picture of the fact that you (and now I) _know_ that clients is in the global scope.

Without knowing for sure what and why clients is present, it seems like pseudo code.

**Comment by Josh-Cena** [comment]
We don't need to explain all the globals that are present; otherwise the explanation becomes bloated. You probably know that `console` and `navigator` are globals; with the same logic it wouldn't be unreasonable to assume that `clients` is also a global, and verification that it is is trivial.

Unless the code specifically doesn't work on its own, I don't think there is a bug with the content.

**Comment by ChristopherWirtOfficial** [comment]
This is a particularly opaque document about a subject not highly understood.

 The general familiarity with a global only present in a scope that someone is clearly actively researching, and is not in the typical toolset of the rest of the massive ecosystem, is not "bloat".

Literally I personally didn't understand the `clients` global as even being a global. As someone that already understands the semantics, consider the perspective of someone not knowing to even look for semantics to figure out. 

Again, it's opaque.

**Comment by Josh-Cena** [comment]
Okay, I think it's fine to add one sentence pointing out that `clients` is a global and link to its page.

**Comment by skyclouds2001** [comment]
I think rather by adding addtional information about, it is better to using property `self` as a prefix

like change

```js
const client = await clients.get(event.clientId);
```

to

```js
const client = await self.clients.get(event.clientId);
```

so if users see the example, they can clearly recoginize that `clients` is a property on `ServiceWorkerGlobalScope`
