### ISSUE TITLE
Issue with "SVG element reference":  <unknown> element

### ISSUE THREAD

**Issue by fabricereix** [mdn/content#10584]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element

#### What information was incorrect, unhelpful, or incomplete?

There is the `unknown` element in https://developer.mozilla.org/en-US/docs/Web/SVG/Element#u which does not seem valid.
The link is also broken.
It should be probably deleted.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/index.md
* Last commit: https://github.com/mdn/content/commit/bd3f490ef78b600a1435dfe3611a27f3f2fbf4ef
* Document last modified: 2021-09-23T21:22:12.000Z

</details>

**Comment by anushkacreates** [comment]
Hey,
I think the `unknown` element is valid as it has been mentioned [here](https://www.w3.org/TR/SVG2/eltindex.html). The link is broken though.

**Comment by fabricereix** [comment]
Ok I now understand that this is coming from the original specs. 

But "unknown" should not to be taken literally. It could have be named "undefined", "other", "any", ...
That's why I don't think it should be part of the elements starting with 'u'.

Rather than being an element, it is more a set of elements (all the elements not defined in the SVG spec).
This could be explained as an additional note to the existing list. 
"Have unknown elements treated as ‘g’ for the purpose of rendering." (https://www.w3.org/TR/SVG2/struct.html#UnknownElement)
