### ISSUE TITLE
Content suggestion: Glossary Terms: Accessible Name & Description

### ISSUE THREAD

**Issue by estelle** [mdn/content#10598]
## What is the new suggestion?
Glossary Terms: 
* Accessible Name
* Accessible description

## Why is it important or useful?
Many pages reference it, including SVG title and all of the a11y section

How many pages are likely to be needed? 2
How much time do you think this work should take? A few hours
Will the work enable learners or professionals to achieve their goals better? yes
Does it address critical needs in the web industry? yes
Is the work an operational necessity, i.e. is not having it a security risk? No
Does the content help make the web more ethical? Yes

## Other supporting information
https://www.w3.org/WAI/standards-guidelines/act/rules/image-button-accessible-name-59796f/#accessible-name

https://developer.mozilla.org/en-US/docs/Glossary

**Comment by Malvoz** [comment]
Related doc: https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names

**Comment by Josh-Cena** [comment]
https://github.com/mdn/content/pull/27336 added "accessible name". @estelle do you plan to add "accessible description" soon?

**Comment by estelle** [comment]
> #27336 added "accessible name". @estelle do you plan to add "accessible description" soon?

Totally forgot that i had filed this issue almost two years ago. It's not on my TODO list if anyone wants to grab it.
