### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by anushkachauhxn** [mdn/content#10591]
### What page(s) did you find the problem on?
MDN URLs: 
- https://developer.mozilla.org/en-US/docs/Web/SVG/Element
- https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute
- https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model

### What is the problem?
A lot of links are broken in these pages.

**Comment by hamishwillee** [comment]
Yes, there are heaps of broken links in the documentation. Generally they should be considered documents that we'd like someone to write - hints. In particular this is true for API reference docs.

Generally unless they are links that are broken - i.e. pointing to nothing when a good target exists, or a topic that would not be useful to create there isn't much point created bugs for them. I'm therefore going to close this issue.

Thanks for posting!
