### ISSUE TITLE
Documentation for Web Share Target API does not exist

### ISSUE THREAD

**Issue by gue-ni** [mdn/content#10600]
The documentation page [1] for the Web Share Target API returns Page not found.

[1] https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_Target_API

It is also knowhere to be found among the other Web APIs:
https://developer.mozilla.org/en-US/docs/Web/API

**Comment by wbamberg** [comment]
Duplicate of https://github.com/mdn/content/issues/10601 .
