### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by DevRadhy** [mdn/content#1060]
on `mdn/structures/macro/index.html` there is a broken link: `<a href="/en-US/docs/templates">complete list of all macros</a>` that link should take you to a page that shows all the macros, but that link does not exist.

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it.

https://web.archive.org/web/20190116224225/https://developer.mozilla.org/en-US/docs/templates and https://web.archive.org/web/20190116224226/https://developer.mozilla.org/en-US/dashboards/macros seem to indicate that page just redirected to https://developer.mozilla.org/en-US/dashboards/macros.

But https://developer.mozilla.org/en-US/dashboards/macros no longer exists either. As far as I can see, it was generated by the legacy Kuma backend — along with other such generated resources under that https://developer.mozilla.org/en-US/dashboards path.

Anyway, that https://developer.mozilla.org/en-US/dashboards page was mostly just a generated index with links to the macro sources. So in https://github.com/mdn/content/pull/1072 I’ve just replaced it with a direct link to https://github.com/mdn/yari/tree/master/kumascript/macros.

cc @mdn/core-yari-dev is case they might have any other guidance/feedback on this

**Comment by chrisdavidmills** [comment]
I've already removed this link in a PR that I'm currently working on (see https://github.com/mdn/content/pull/1007), therefore I'm closing this one.
