### ISSUE TITLE
Minor issue with wording in "<input type="range">" article

### ISSUE THREAD

**Issue by amjoshuamichael** [mdn/content#10609]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

#### What information was incorrect, unhelpful, or incomplete?

This is the page that many people see for the first time when researching the input range element in html. In fact, it's the first google result for "input range". So, when it opens with "_Because this kind of widget is imprecise, it shouldn't typically be used unless the control's exact value isn't important,_" that's an issue. Skimming over this article, one jumps to the phrase "_it shouldn't typically be used,_" because, frankly, web development is full of things that "shouldn't typically be used". However, what I think the author meant to say is that the widget, while useful, should only be used if the control's exact value isn't important. The use of the words "shouldn't" and "unless" in conjunction here constitute a confusing double negative that clouds the meaning of the statement, making the reader believe at a glance that the input:range widget is useless or unusable. In fact, this widget is quite important, and is used not only on the web but in other programs and physical interfaces to create a visual indication of a changing parameter with a minimum and maximum. The introduction paragraph for this article, which for all intents and purposes is the main description for this html element online, fails to reflect this.

In summary, I believe the phrase "Because this kind of widget is imprecise, it shouldn't typically be used unless the control's exact value isn't important," should be replaced with "Because this kind of widget is imprecise, it should only be used if the control's exact value isn't important," in order to accurately reflect the usefulness of a range slider in html.

#### Specific section or headline?

The final sentence in the introduction paragraph of the input:range article.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/range`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/range/index.md
* Last commit: https://github.com/mdn/content/commit/775662998e66813a612e3ff27e02f2ada867bc17
* Document last modified: 2021-10-03T00:01:51.000Z

</details>

**Comment by wbamberg** [comment]
> In summary, I believe the phrase "Because this kind of widget is imprecise, it shouldn't typically be used unless the control's exact value isn't important," should be replaced with "Because this kind of widget is imprecise, it should only be used if the control's exact value isn't important," in order to accurately reflect the usefulness of a range slider in html.

Good suggestion! I agree that this would be better.
