### ISSUE TITLE
Issue with "Dynamic programming language": (short summary here please)

### ISSUE THREAD

**Issue by Pranav108** [mdn/content#10616]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Dynamic_programming_language

#### What information was incorrect, unhelpful, or incomplete?
First sentence doesn't totally make sense. Get confused near "operations otherwise".

#### Specific section or headline?
In first section, first line of  'Dynamic programming language'.

#### What did you expect to see?
First sentence to be more clear.

#### Did you test this? If so, how?
One of my friend also said this sentence to be ugly.

![image](https://user-images.githubusercontent.com/56934594/142382048-48ae6727-d5e4-462b-b1fb-09bb6bb8f055.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/dynamic_programming_language`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Dynamic_programming_language
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/dynamic_programming_language/index.md
* Last commit: https://github.com/mdn/content/commit/4a9f9d2e9c1811ce3519a7061e906db9200a5e97
* Document last modified: 2021-10-08T00:24:32.000Z

</details>

**Comment by sideshowbarker** [comment]
#10630 deleted the entire glossary entry
