### ISSUE TITLE
Issue with "inset-block": documentation is for inset-inline

### ISSUE THREAD

**Issue by inopinatus** [mdn/content#1061]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/inset-block

#### What information was incorrect, unhelpful, or incomplete?

Page actually contains the content for `inset-inline`.

#### What did you expect to see?

The content for `inset-block`, which appears to have been overwritten in https://github.com/mdn/content/commit/6ec6bf2b95fb1d10631d99d16e71d40cd0e33020

#### Did you test this? If so, how?

Visit the page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/inset-block`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/inset-block
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/inset-block/index.html
* Report started: 2021-01-08T00:13:22.094Z

</details>

**Comment by sideshowbarker** [comment]
> The content for `inset-block`, which appears to have been overwritten in [6ec6bf2](https://github.com/mdn/content/commit/6ec6bf2b95fb1d10631d99d16e71d40cd0e33020)

Yes, seems so — thanks very much for investigating to identify that change as what broke it, and thanks for catching this and reporting it. I’ve opened https://github.com/mdn/content/pull/1066 with a fix.
