### ISSUE TITLE
Issue with "Using HTTP cookies": (short summary here please)

### ISSUE THREAD

**Issue by asoom804** [mdn/content#10653]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cookies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cookies/index.md
* Last commit: https://github.com/mdn/content/commit/844164a143ee33b6c141545de22f0458ba906ebf
* Document last modified: 2021-10-03T11:46:42.000Z

</details>

**Comment by hamishwillee** [comment]
Closing. No information provided about problem.
