### ISSUE TITLE
Issue with "Push API": invalid url serviceworke.rs

### ISSUE THREAD

**Issue by h1z1** [mdn/content#10666]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Push_API

#### What information was incorrect, unhelpful, or incomplete?

Reference is to "Serviceworker cookbook", not sure what it's supposed to link to but was added with https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630

no combination of servicewok.rs appears to resolve in DNS.

#### Specific section or headline?

Examples

#### What did you expect to see?

Correct URL.

#### Did you test this? If so, how?

Magic of leftclicking on link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/push_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Push_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/push_api/index.md
* Last commit: https://github.com/mdn/content/commit/75406fcc62b0baba2fac2cf2e1071b6ede787eef
* Document last modified: 2021-10-18T15:44:34.000Z

</details>

**Comment by h1z1** [comment]
Related-  maybe the domain expired?

```
Registration date: 16.11.2015 19:06:36
Modification date: 21.11.2020 12:07:36
Expiration date: 16.11.2021 19:06:36
Confirmed: 16.11.2015 19:06:36
Registrar: NINET Company d.o.o.


Registrant: Individual

Administrative contact: Individual

Technical contact: NINET Company d.o.o.
Address: Bul. Nemanjica 25, TC Zona 3 lok. K6, Nis, Serbia
Postal Code: 
ID Number: 17499114
Tax ID: 


DNS: marek.ns.cloudflare.com - 
DNS: kia.ns.cloudflare.com - 


DNSSEC signed: no

Whois Timestamp: 21.11.2021 02:07:51
```

**Comment by wbamberg** [comment]
Fixed in https://github.com/mdn/content/pull/11032
