### ISSUE TITLE
Issue with "RegExp.prototype.test()": (short summary here please)

### ISSUE THREAD

**Issue by BretmG** [mdn/content#10678]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

#### What information was incorrect, unhelpful, or incomplete?
In the demo section there are two examples for: console.log(**globalRegex.lastIndex**);

console.log(globalRegex.lastIndex);
// expected output: 0
. . .
console.log(globalRegex.lastIndex);
// expected output: 9

#### Specific section or headline?
JavaScript Demo: RegExp.prototype.test

#### What did you expect to see?
I believe the _first_ example should be: console.log(**regex**.lastIndex);

#### Did you test this? If so, how?
The [ Run ] button shows the output for: console.log(**regex**.lastIndex); 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/regexp/test`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/regexp/test/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by AnilSeervi** [comment]
> The [ Run ] button shows the output for: console.log(regex.lastIndex);

The first `console.log(globalRegex.lastIndex);` is working as expected.
Before a match is found the lastIndex will be at 0.
After a match is found using `.test()` the lastIndex is 9.
You can read more about it at - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex

But personally I do think that `console.log(regex.lastIndex);` makes more sense there.

**Comment by wbamberg** [comment]
Thanks for filing, but as commented in https://github.com/mdn/interactive-examples/pull/1954#issuecomment-975987760, I think this is intentional and working as expected.
