### ISSUE TITLE
Issue with "Origin": (short summary here please)

### ISSUE THREAD

**Issue by timbl** [mdn/content#10679]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

#### What information was incorrect, unhelpful, or incomplete?

Incomplete:  Maybe explain that the "Origin of the request" means: 
the domain name of the web page if and only if the user is running a web app, and is otherwise "null" .
(It is not the domain name of the computer the user is running, for example!).
Chrome gives "null" when user is running a HTML/JS app in "file:" scheme space.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/origin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/origin/index.md
* Last commit: https://github.com/mdn/content/commit/1d273c5a91191d5dd22b70e15d7e5731a8aa125f
* Document last modified: 2021-11-02T15:09:07.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for posting this @timbl 

I agree that origin of the request is not well explained - in particular that it is the origin of the page that caused the request, not the computer IP address.

The topic is actually very complicated, with answers spread across a whole bunch of specs. There is a pretty good overview of the `null` case here: https://stackoverflow.com/questions/42239643/when-do-browsers-send-the-origin-header-when-do-browsers-set-the-origin-to-null/42242802#42242802
That is linked from the page at the bottom. What I have done is embedded that in the description. 

PR here: #10709
