### ISSUE TITLE
Issue with "resize event": the logged height does not change when changing the height of the browser window

### ISSUE THREAD

**Issue by bb-harlan** [mdn/content#10683]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event

#### What information was incorrect, unhelpful, or incomplete?

In the example below the logged height does not change when changing the height of the browser window. (The width logger works.)

#### Specific section or headline?

Examples
Window size logger

#### What did you expect to see?

I expected to see the logged height change in response to changing the browser's window height.

#### Did you test this? If so, how?

I resized the bowser window to see the example work and observed that the height part of the example does not work.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/globaleventhandlers/onresize`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onresize
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/globaleventhandlers/onresize/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by wbamberg** [comment]
I guess this is because the example is in an iframe and the iframe height isn't changing. Since the example would work almost as well without logging height, maybe we should just remove that and only log width?

**Comment by bb-harlan** [comment]
I think if you changed the example to log only the width, you would need to explain why no height example (the iframe thing).  

How about including the height with one of the following?

- Provide something in the example's UI to change the iframe height ,(would still need mention of the iframe thing), or  
- provide a link or a "Try it" button  that opens the example in a new browser tab such that the example is NOT in an iframe?

**Comment by AnilSeervi** [comment]
> - provide a link or a "Try it" button that opens the example in a new browser tab such that the example is NOT in an iframe?

providing a link to the scr of iframe will work - https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/GlobalEventHandlers/onresize/_sample_.Window_size_logger.html

**Comment by bb-harlan** [comment]
AnilSeervi,

Thanks for creating a page to demonstrate it to the MDN people. 

That "Try it" technique is employed a lot on the W3 Schools site, but I haven't seen it on the MDN site. I wonder whether MDN  would be willing to go against the precedent of not using it. This is a case for which I think breaking the precedent would be worthwhile, but I will accept whatever the MDN people decide. It's a small thing, but it was annoying to spend time on trying to understand what the problem was and then reporting it here. I wouldn't wish that on anybody else who stumbles across this problem.

I will be interested in seeing what MDN decides.

**Comment by AnilSeervi** [comment]
> Thanks for creating a page to demonstrate it to the MDN people. 

To clarify it, I didn't create the page myself. It's source is actually from MDN. I have shared the iframe's `src` so that it can be viewed standalone, which in-turn is a good case to implement the 'Try it' link.

Yet I'm uncertain of the changes that can occur to the `src` link.

**Comment by wbamberg** [comment]
Although it's a clever idea to link to the generated page I'm concerned that this is exposing the implementation machinery of the live sample system.

Perhaps the best option would be to convert this example to a GitHub-hosted page, by adding it to the https://github.com/mdn/dom-examples/ repo, then we could link to it there.

**Comment by AnilSeervi** [comment]
Can it be linked to a JSFiddle ?

**Comment by bb-harlan** [comment]
**Re:** Perhaps the best option would be to convert this example to a GitHub-hosted page, by adding it to the https://github.com/mdn/dom-examples/ repo, then we could link to it there.

...sounds good to me.

**Comment by AnilSeervi** [comment]
@wbamberg Can you guide me as to where to put the files in the repo?

**Comment by wbamberg** [comment]
@AnilSeervi , sure! You should probably create a directory under https://github.com/mdn/dom-examples/, called "resize-event" or something like that, and create it as a standalone page in there. You could use one of the existing pages for guidance, such as https://github.com/mdn/dom-examples/blob/master/htmldialogelement-basic/index.html.

You should also update the README (https://github.com/mdn/dom-examples) with a quick description of this example.

One thing that's lacking with these GitHub hosted pages compared with live samples, is that you don't automatically see the code. So maybe you could copy the code into the MDN page and link to the GitHub page as well.

**Comment by AnilSeervi** [comment]
> One thing that's lacking with these GitHub hosted pages compared with live samples, is that you don't automatically see the code. So maybe you could copy the code into the MDN page and link to the GitHub page as well.

Thanks @wbamberg , are you suggesting that we remove the live sample from the MDN page and put the GitHub hosted page code there?

whereas I thought of keeping the live sample and adding a description below it something like 'Try it "here" to see both values change as you resize the window.

Your thoughts?

**Comment by wbamberg** [comment]
I think if we add the GH example we should remove the live sample, and show the code from the GH example in the page just as a static code block. I think it would be pretty confusing to have two examples that are substantially the same but behave differently.

**Comment by AnilSeervi** [comment]
Okay 👍 @wbamberg 

You can assign me to it. I'll make the changes and PR at both repos within a day :)

**Comment by wbamberg** [comment]
Awesome, thank you @AnilSeervi !

**Comment by AnilSeervi** [comment]
Live samples are very good at demonstrating the example then and there.
Can't we change the live sample itself to access the `parent`(window) object in the  iframe to showcase `onresize`. This way we don't have to do GH page example.

what do you think? @wbamberg

**Comment by bb-harlan** [comment]
@AnilSeervi,,

I realize you weren't asking me, but...

**Re:** Can't we change the live sample itself to access the parent(window) object in the iframe to showcase onresize. This way we don't have to do GH page example.

changing the resize function to something like
```
function resize() {
  heightOutput.textContent = parent.window.innerHeight;
  widthOutput.textContent = parent.window.innerWidth;
}

parent.window.onresize = resize;
```

I agree that would be better if it works. I tried implementing it using the inspector's editing capabilities, but I couldn't get it to work. I also tried to  simply change the ` iframe ` to a ` div ` ...couldn't get that to work either. Maybe you can give it a ry.

**Comment by wbamberg** [comment]
Thanks for the suggestion @AnilSeervi . But I don't think we ought to do this, because it's introducing weirdness into the user-facing example code because of the implementation of our live sample system.

Someone looking at examples on this page wants to see code that shows the normal usage of the API, not a usage that's specifically tailored to our live sample system. Readers of our pages don't know or care that live samples live in an iframe, or that this `window.parent` is only needed because of that (and they don't want us to tell them about that, when they just want to know how to use the `resize` event). They'll just take that `window.parent` code and use it in their pages.

So unless live samples can work with normal usage of the API, we should do something different - either a GH page or even a static code block.

**Comment by AnilSeervi** [comment]
@wbamberg can you look at the mdn/dom-examples#86 PR and approve it so that I can make further changes to the MDN page.

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/22295
