### ISSUE TITLE
Issue with "Web Crypto API": (discouraging warning)

### ISSUE THREAD

**Issue by gabesullice** [mdn/content#10681]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API

#### What information was incorrect, unhelpful, or incomplete?
I believe the warning is unhelpful and counterproductive because it discourages readers by setting an expectation that they probably aren't capable of understanding the material. I also believe it could be more brief.

#### Specific section or headline?
![Screenshot_20211121-082120](https://user-images.githubusercontent.com/4500265/142768052-f83e2b89-5721-40b0-b016-939e196aa77c.png)

#### What did you expect to see?
A warning which serves the purpose of protecting users' privacy without discouraging learners.

Suggested replacement:

> Warning: Cryptography is a subject which requires know-how and experience to deploy securely. Please learn and experiment, but don't guarantee or imply the security of your work before an individual knowledgeable in this subject matter thoroughly reviews it.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/web_crypto_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_crypto_api/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks @gabesullice for suggesting a replacement. See also a related issue https://github.com/mdn/content/issues/9794 . Are you aware of any authoritative resources that get into the details of what might go wrong?

**Comment by gabesullice** [comment]
No problem! Thanks for linking to the related issue. I'm not aware of any, unfortunately.

**Comment by greggles** [comment]
I'm not really sure what you'd do with the crypto apis, but 2 general sources of info on doing cryptography securely:

* The PCI DSS standard has sections on key management, rotation etc that opened my eyes on the subject.
* I have not read it, but [the joy of cryptography](https://joyofcryptography.com/) is [now online and creative commons licensed](https://twitter.com/benadida/status/1462567278290083846). Seems like it could be helpful in this situation.

**Comment by wbamberg** [comment]
As the person who wrote this warning, I will say it was written in collaboration with the Mozilla security team, and was absolutely intended to discourage people from using this API unless they had a solid understanding of the issues involved. 

> setting an expectation that they probably aren't capable of understanding the material.

I'm not sure I agree with that . It is intended to an expectation that they should understand the underlying principles of designing secure systems before using these APIs to try to build secure systems. Not that they are not capable of understanding anything.

The Web Crypto API is pretty controversial in the crypto community, as is partly summarised here: https://github.com/mdn/sprints/issues/672. We did want to have a document on guidance to using the APIs properly, but that really needs a lot of collaboration with specialist experts, and we weren't able to get those resources.

>  Are you aware of any authoritative resources that get into the details of what might go wrong?

I'm told that a good place to start is https://www.crypto101.io/.

All that said, if people want to change the warning, sure. Noone reads warnings anyway :).

**Comment by wbamberg** [comment]
On https://github.com/mdn/content/issues/9794:

> developers ... would want to know more of the Web Crypto API and would want to know how to properly use it

...again, linking in the warning to https://www.crypto101.io/ is probably not a bad idea.

**Comment by wbamberg** [comment]
Maybe we can close this, thanks to @himanshugarg 's https://github.com/mdn/content/pull/10830, which made the warning a bit less hostile?

**Comment by gabesullice** [comment]
Sweet! Yeah, I think we can close it. :fist_right: :boom: :fist_left:
