### ISSUE TITLE
Issue with "JavaScript modules": caniuse reports Safari 15 supports modules in workers

### ISSUE THREAD

**Issue by FrankReh** [mdn/content#10680]
Maybe this page hasn't been updated since safari 15 came out, or maybe caniuse is wrong. If caniuse is correct, Firefox is the lone holdout of the major players and an unfortunate missing piece for the independent web.

**Comment by hamishwillee** [comment]
Thanks. I've updated the browser compatibility information to indicate Safari 15 supports import in workers: https://github.com/mdn/browser-compat-data/pull/13670

Firefox still does not. This will be closed when https://github.com/mdn/browser-compat-data/pull/13670 is merged.

**Comment by ddbeck** [comment]
https://github.com/mdn/browser-compat-data/pull/13670 is resolved. Closing this. Thank you!
