### ISSUE TITLE
Issue with "An overview of HTTP": (short summary here please)

### ISSUE THREAD

**Issue by sadyng** [mdn/content#10691]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview

#### What information was incorrect, unhelpful, or incomplete?
lack some doc after http flow(step 4 and rest are not show on mdn),i found this lackness because i open a chinese translated page too

#### Specific section or headline?
the elment id is #http_flow, it should has step 4 and rest ,but it end with step 3

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/overview`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/overview/index.md
* Last commit: https://github.com/mdn/content/commit/863c4704c3879b3417c9b277dceddfe27e888695
* Document last modified: 2021-10-03T10:32:45.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much - fixed by #10711 (the step was there, but removed by incorrect layout of the preceding code block.
