### ISSUE TITLE
Issue with "Your first extension": (short summary here please)

### ISSUE THREAD

**Issue by Snowworm3000** [mdn/content#10699]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

#### What information was incorrect, unhelpful, or incomplete?
Incomplete: All example videos are unavailable.

#### Specific section or headline?
Every section containing an embedded YouTube video player.

#### What did you expect to see?
An available video to watch demonstrating the instructions.

#### Did you test this? If so, how?
Using Firefox 94.0.1 (64 bit) in mac OS Monterey

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/your_first_webextension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/your_first_webextension/index.md
* Last commit: https://github.com/mdn/content/commit/629960fa07e15f2354d75daf14f149d4942539ec
* Document last modified: 2021-10-26T21:28:18.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. This was fixed in https://github.com/mdn/content/pull/10567 (yesterday). It should appear in the live version in a few days.
