### ISSUE TITLE
Issue with "Client-Server Overview": GET request example wrong

### ISSUE THREAD

**Issue by notroid5** [mdn/content#10693]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Client-Server_overview

#### What information was incorrect, unhelpful, or incomplete?
"Accept-Language" in the text is not text same as in the actual request above.

Request:
Accept-Language: en-US,en;q=0.8,es;q=0.6

Text below:
Accept-Language: de,en;q=0.7,en-us;q=0.3

#### Specific section or headline?
GET request/response example

#### What did you expect to see?
The two lines should be the same.

#### Did you test this? If so, how?
Nothing to test.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/first_steps/client-server_overview`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Client-Server_overview
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/first_steps/client-server_overview/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, will be fixed by #10710

FYI, for little fixes like this, feel free to fix it yourself. There is an edit link at the bottom of the page that will take you to the right page for editing:
![image](https://user-images.githubusercontent.com/5368500/142964838-214603ee-c5af-443e-8037-951aee5b631e.png)
