### ISSUE TITLE
Issue with "The Unicode Bidirectional Text Algorithm": typo LRI vs RLI

### ISSUE THREAD

**Issue by mandolaerik** [mdn/content#10695]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Unicode_Bidrectional_Text_Algorithm

#### What information was incorrect, unhelpful, or incomplete?

The second table row, leftmost cell, says `Right-to-Left Isolate (LRI)`. Should be `(RLI)`.

#### Specific section or headline?

Overriding BiDi using Unicode control characters

#### What did you expect to see?

`Right-to-Left Isolate (RLI)`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/guide/unicode_bidrectional_text_algorithm`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Unicode_Bidrectional_Text_Algorithm
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/unicode_bidrectional_text_algorithm/index.md
* Last commit: https://github.com/mdn/content/commit/d2871ae4b914b7a76bb5a8c5e560399e4e2c8353
* Document last modified: 2021-10-21T15:03:24.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! We decided too delete the page: https://github.com/mdn/content/pull/10702.
