### ISSUE TITLE
Issue with "HTMLSelectElement.selectedOptions": broken link

### ISSUE THREAD

**Issue by nickolay** [mdn/content#1070]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedOptions#see_also

#### What information was incorrect, unhelpful, or incomplete?

"[Drop-down content](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/The_native_form_widgets#Drop-down_content) in Basic native form controls" link is broken; should probably point to https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls#drop-down_controls

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlselectelement/selectedoptions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedOptions
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/htmlselectelement/selectedoptions/index.html
* Report started: 2021-01-08T04:16:27.066Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this and reporting it.

> should probably point to [developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls#drop-down_controls](https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls#drop-down_controls)

Yup — in https://github.com/mdn/content/pull/1073 I’ve made it so
