### ISSUE TITLE
Dark mode feature

### ISSUE THREAD

**Issue by diamant3** [mdn/content#10714]
I request this feature to helps learners/developers reading or studying at night or in dark environments.

Benefits:

* enhances visual ergonomics by reducing eye strain.
* increase the battery life on your device.

[Source](https://www.healthline.com/health/is-dark-mode-better-for-your-eyes#benefits-of-dark-mode)

**Comment by wbamberg** [comment]
Duplicate of https://github.com/mdn/yari/discussions/2539 (along with many others).
