### ISSUE TITLE
Issue with "NSS Tools": replacement of old netscape links

### ISSUE THREAD

**Issue by PSJoshi** [mdn/content#1071]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/tools

Object Signing and Form signing links at the bottom of the page are still pointing to old Netscape portal:
http://developer.netscape.com/docs/manuals/security.html#OBJ
http://developer.netscape.com/docs/manuals/security.html#FORM
As a result, 404 is returned.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/projects/nss/tools`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/tools
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/projects/nss/tools/index.html
* Report started: 2021-01-08T04:46:39.682Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting. I've just removed these notes, as there is no reference to them in the table, and I can't find equivalent resources to the broken links anywhere. See https://github.com/mdn/content/commit/1d13a37a56072e65ace7ba1e66c50d0c2fa76a7c for a fix.
