### ISSUE TITLE
Issue with "Document.getElementById()": (short summary here please)

### ISSUE THREAD

**Issue by Adam-Books** [mdn/content#10722]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById

#### What information was incorrect, unhelpful, or incomplete?
var element = document.getElementById(id);

#### Specific section or headline?
Syntax

#### What did you expect to see?
var element = document.getElementById('id');

#### Did you test this? If so, how?
The id must be inside quote marks.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/getelementbyid`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/getelementbyid/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by AnilSeervi** [comment]
Within the [**Parameters**](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById#parameters) it is described that `id` is case-sensitive string value.
Other pages also use the same syntax, if you've noticed.
> The ID is case-sensitive string which is unique within the document

**Comment by Adam-Books** [comment]
No... I don't mean the case-sensitive... I'm talking about the quote marks... It should be: 
- document.getElementById('id')
- document.querySelector('selectors')
- parentNode.querySelectorAll('selectors')

**Comment by wbamberg** [comment]
Thanks for filing! But we don't do this for syntax sections.

> The id must be inside quote marks.

Only if it is a string literal, which would usually not be the case.
