### ISSUE TITLE
Issue with "Clipboard.writeText()": doesn't work in HTTP protocol

### ISSUE THREAD

**Issue by fikryrmdhna** [mdn/content#10741]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText

I created a copy to clipboard with the Clipboard API, I created it with the code as I made below. When on localhost it worked fine. But when it's on the server there is an error like this

![image](https://user-images.githubusercontent.com/58467587/143193153-7cac9d31-852c-41f7-83ad-ba7379b39d63.png)

I've read because for this it works both on HTTPS and localhost. What I want to ask is how does this work in HTTP?

```
async function copyToClipboard(str, notification) {
	try {
		var copyText = str;

		/* Select the text field */
		copyText.select();

		/* Copy the text inside the text field */
		await navigator.clipboard.writeText(copyText.value);
		showGlobalNotification(notification);
	  	console.log('Page URL copied to clipboard');
	} catch (err) {
	  	console.error('Failed to copy: ', err);
	}
  }
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/clipboard/writetext`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/clipboard/writetext/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

Are you asking, "how can I use `clipboard.writeText` on HTTP? I think the answer is "you can't" because it's one of the APIs that is only available to pages served over HTTPS. You can see that because in the spec: https://w3c.github.io/clipboard-apis/#clipboard-interface it's marked as `SecureContext`.

But we should document this on MDN, and we don't.

**Comment by hamishwillee** [comment]
Thanks @wbamberg 

I added the secure context header to  `Clipboard` in #10776, as that is the standard way we document the fact you can't use something in HTTPs. Note that you wouldn't find this header in `Clipboard.writeText()` - you would be expected to check the parent page to find this restriction.
