### ISSUE TITLE
Wrong sounds of Russian letter "О"

### ISSUE THREAD

**Issue by vostok1982** [mdn/content#10742]
Hello, dear colleague!

Our educational site for children wikids.ru is using the api https://mdn.github.io/web-speech-api/speak-easy-synthesis/ for voice acting of our text. I have noticed that in Yandex browser you can choose only 1 Russian voice - Irina. This voice incorrectly sound Russian letter О  when it stands alone - I mean when text is "О" and nothing more. The letter O sounds like А [а] not like [о].

**Comment by wbamberg** [comment]
I believe the voices available and the particular sounds they produce are determined by the browser. As you can see, the code for the speech synthesis example is really simple: https://github.com/mdn/web-speech-api/blob/master/speak-easy-synthesis/script.js - most of the clever stuff is done by the browser or even the underlying OS, behind the [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API).

So if there is a problem with the sounds produced this is not an issue with the demo, but with the browser/OS.

**Comment by wbamberg** [comment]
Closed per https://github.com/mdn/content/issues/10742#issuecomment-978840973
