### ISSUE TITLE
Issue with "label": (short summary here please)

### ISSUE THREAD

**Issue by dakgk** [mdn/content#10743]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/label`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/label/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by wbamberg** [comment]
Closing this as it is an empty issue.

**Comment by dakgk** [comment]
#10743
