### ISSUE TITLE
Issue with "Browser Console": no more "Web Developer" submenu

### ISSUE THREAD

**Issue by skierpage** [mdn/content#10754]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Browser_Console

#### What information was incorrect, unhelpful, or incomplete?
The MDN  page says
> select "Browser Console" from the Web Developer submenu in the Firefox Menu

but there's no such submenu in Firefox Nightly 96.0a1 (2021-11-24) on Linux. Instead my Firefox menu has a "More tools" submenu. Similarly, the MDN goes on to say
> or Tools menu if you display the menu bar

but again there is no Web Developer submenu of Tools in the conventional menu bar. Instead the conventional menu bar has Tools > Browser Tools

#### Specific section or headline?
Opening the Browser Console

#### What did you expect to see?
Instructions should match the actual Firefox "hamburger" menu.

#### Did you test this? If so, how?
Yes, I followed the instructions.

### Other Notes
This is with Nightly but the menus seem the same in regular Firefox 94.

If the "Web Developer" menu is truly gone, then changes are needed across the entire Firefox codebase. searchfox.org finds dozens of mentions of the Web Developer menu/sub-menu, Tools > Web Developer > ... , etc. in code comments and some .md files.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/browser_console`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Browser_Console
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/browser_console/index.html
* Last commit: https://github.com/mdn/content/commit/cb257575007c0d4273a9c55b984387f27a1e9a41
* Document last modified: 2021-07-15T13:27:06.000Z

</details>

**Comment by AnilSeervi** [comment]
I agree. Devtools content by whole is pretty old and needs to be updated.

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!

**Comment by skierpage** [comment]
Thanks. Yes Firefox DevTools User Docs pages including [the home page](https://firefox-source-docs.mozilla.org/devtools-user/) and [Web Console](https://firefox-source-docs.mozilla.org/devtools-user/web_console/index.html) still mention a "Web Developer" menu, so I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1761367
