### ISSUE TITLE
Array.prototype.copyWithin()

### ISSUE THREAD

**Issue by solutayo** [mdn/content#10765]
MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin

**One of the examples displayed incorrect result.**

`const array1 = ['a', 'b', 'c', 'd', 'e'];`

_`// copy to index 1 all elements from index 3 to the end`_
**`console.log(array1.copyWithin(1, 3));`**

**The result was given as:** 

` Array ["d", "d", "e", "d", "e"]`

**Instead of:** 

`Array [ 'a', 'd', 'e', 'd', 'e' ]`

**Comment by wbamberg** [comment]
I don't think so. `copyWithin` changes the array, so after line 4 it is `["d", "b", "c", "d", "e"]`, then line 8 modifies the second and third elements. If you comment out line 4 you get the result you were expecting, but as it is this example is working as expected.
