### ISSUE TITLE
Issue with "Introduction to events": persistent text in bubbling and capturing example

### ISSUE THREAD

**Issue by johnrjervis** [mdn/content#10773]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events

#### What information was incorrect, unhelpful, or incomplete?
The example for bubbling and capturing has a small flaw: some text remains in the log section after the "clear output" button is clicked. Adding "evt.stopPropagation()" to the "clearOutput()" function should fix this (it would also be necessary to update the clearOutput() function definition to "function clearOutput(evt)").

#### Specific section or headline?
"Bubbling and capturing explained"

#### What did you expect to see?
All text in the log section of the example should disappear once the "clear output" button is clicked.

#### Did you test this? If so, how?
I created a local copy of the code and edited it: see a live example at https://johnrjervis.github.io/bubbling-and-capture/ -  the second iframe containing the updated code works as I would expect. (The updated JS file for this can be found at https://github.com/johnrjervis/bubbling-and-capture/blob/main/bubbling-and-capturing-updated.js.)

In my version of the JS, I have also added some string formatting to strip the square brackets and the word "object" from the output of the gphase() function.

I tried to create a pull request, but could not work out where the source code for the example is stored - it is referenced in "index.md" as {{ EmbedLiveSample('Using_event_targets', '100%', 430, "", "") }}, and I could not work out how to access this code.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/events/index.md
* Last commit: https://github.com/mdn/content/commit/a23d783f2bbcc02474a68c6cd766c34d4059f632
* Document last modified: 2021-11-22T18:29:17.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing and digging into it, @johnrjervis !

In case you did want to file a PR: if I understand you correctly, the code that needs updating is at https://github.com/mdn/content/blob/f74ed294ed20d4323ef2b0f363c182132d452be9/files/en-us/learn/javascript/building_blocks/events/index.md?plain=1#L603-L674 .

The `{{ EmbedLiveSample }}` macro is given the ID of a section of the document where it can find the code blocks it can use to build the example. In this case it is (if I understand you right) the call at https://github.com/mdn/content/blob/f74ed294ed20d4323ef2b0f363c182132d452be9/files/en-us/learn/javascript/building_blocks/events/index.md?plain=1#L601, which referring to the section "Example_code_event_phases".

**Comment by johnrjervis** [comment]
Hi @wbamberg - thanks for the reply!

That's quite clever how the code examples are built from the index document itself! I'll see if I can work out how to do a PR for this.
