### ISSUE TITLE
Issue with "Push API": Examples 'ServiceWorker Cookbook' hyperlink not loading

### ISSUE THREAD

**Issue by SoSDylan** [mdn/content#10779]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Push_API

#### What information was incorrect, unhelpful, or incomplete?
The link 'ServiceWorker Cookbook' to https://serviceworke.rs/ does not lead to a working site.

#### Specific section or headline?
Examples

#### What did you expect to see?
I expected the https://serviceworke.rs/ site to load but it did not.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/push_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Push_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/push_api/index.md
* Last commit: https://github.com/mdn/content/commit/75406fcc62b0baba2fac2cf2e1071b6ede787eef
* Document last modified: 2021-10-18T15:44:34.000Z

</details>

**Comment by AnilSeervi** [comment]
The site seems to be down.
I guess it has something to do with the build fail.

suggestion: maybe the link can be changed to lead to https://github.com/mozilla/serviceworker-cookbook

**Comment by wbamberg** [comment]
Fixed in https://github.com/mdn/content/pull/11032.
