### ISSUE TITLE
Issue with "@media": Need more clarity re Level 4 v Level 3, browser compat, and broken links

### ISSUE THREAD

**Issue by JakeQZ** [mdn/content#10774]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media

#### What information was incorrect, unhelpful, or incomplete?

The link to the W3C CSS Level 3 spec is broken.

The link to your own CSS Level 3 archive (https://developer.mozilla.org/en-US/docs/Archive/CSS3) is also broken.

I think there needs to be more clarity on the page on the differences between Level 3 and Level 4, particularly regarding the `not` and `or` operators, and more particularly because AFAIK Firefox is the only browser that supports Level 4 here.

I think there should be more examples using the `not` and `or` operators for both Level 3 and Level 4.  I have not come across the `or` operator before (in Level 3 one would use the comma operator).

The browser compatibility table should include whether Level 4 is supported for `@media` rules.

The browser compatibility table should include which media features are supported (not all support all).  Some browsers will discard entire `@media` rules if they include an unsupported media feature.

#### Specific section or headline?

Various sections.

#### What did you expect to see?

Clearer guidance for developers.

#### Did you test this? If so, how?

Yes, multifariously.  And from experience.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/@media`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@media/index.md
* Last commit: https://github.com/mdn/content/commit/a5154c6965a0416e13c893414b9e2493ef1ba4aa
* Document last modified: 2021-10-22T03:29:59.000Z

</details>

**Comment by estelle** [comment]
The content has been updated over the past year. Resolved. Closing.
