### ISSUE TITLE
Issue with "transform": Need to clarify transform-function application in reverse order

### ISSUE THREAD

**Issue by JakeQZ** [mdn/content#10781]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform

#### What information was incorrect, unhelpful, or incomplete?

It's not obvious or clear that the transform functions are effectively applied in reverse order, and that each represents a transform matrix applied to the initial vector of each of the four corners of the target.

In vector/matrix maths we write V(result) = M(1) M(2) V(initial).  The assumed operator is 'matrix multiplication'.  Thus we see that M(2) is applied first.  A link to something explaining this would be useful.

> If perspective() is one of multiple function values, it must be listed first.

Really?  Surely it's just another matrix.

#### Specific section or headline?

n/a

#### What did you expect to see?

Some explanation of the maths, at least indicating that the transforms are applied in reverse order.

#### Did you test this? If so, how?

I studied mathematics at university.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/transform`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/transform/index.md
* Last commit: https://github.com/mdn/content/commit/b90911dc2846c8feefc042ee9b52910834295ce3
* Document last modified: 2021-10-25T07:54:55.000Z

</details>

**Comment by JakeQZ** [comment]
> > If perspective() is one of multiple function values, it must be listed first.
> 
> Really? Surely it's just another matrix.

After a few moments thought, I realize this is flatting the co-ordinate space from 3D to 2D.  But does that really mean further transforms can't be applied?  It needs explaining.

This is quite an involved topic and I would suggest some links to wikipedia articles (there are some that may benefit readers) rather than rewriting the wheel.

**Comment by estelle** [comment]
I added an example to indicate how function order matters. Does this address your concern?  

I don't think a math explanation is needed as it may be more confusing than helpful.
