### ISSUE TITLE
Issue with "Use the Inspector API": Dead link and wrongly categorized(?)

### ISSUE THREAD

**Issue by Thiibo** [mdn/content#10802]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Use_the_Inspector_API

#### What information was incorrect, unhelpful, or incomplete?
The link to a file called "inspector-panel.js" is dead.
Furthermore, I also feel like the article seems to be wrongly categorized. I could be misinterpreting what the API is supposed to do, but from what I can see, it is supposed to be used with addons/extensions. If so, it feels strange that it is not bundled with the other extension documentation at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions. Instead, it is placed together with guides on how to (manually) work with the inspector as a developer (under https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to).

#### Specific section or headline?
window.inspector (for broken link)

#### What did you expect to see?
Not too sure. Again, I'm not really certain about what the API is exactly supposed to do. Maybe the link should show a function definition in a JavaScript file?

#### Did you test this? If so, how?
Clicking the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/use_the_inspector_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Use_the_Inspector_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/use_the_inspector_api/index.html
* Last commit: https://github.com/mdn/content/commit/6b813901a413f1ea27bc0c982e041f7c60c2604e
* Document last modified: 2021-04-05T17:56:05.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

Yes, this is an API supported in the old add-ons system, which Firefox hasn't supported for years. This page should just be deleted. There is a supported devtools extension interface (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools) but it's completely different.

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
