### ISSUE TITLE
Content suggestion: Create a standalone page with just a standalone version of the JavaScript editor used for interactive examples

### ISSUE THREAD

**Issue by kvetoslavnovak** [mdn/content#10800]
## What is the new suggestion?
It would be great to have your JavaScript editor as a separate webpage. 

## Why is it important or useful?
Even though there are many other sites with special JavaScript editor I often find myself to use your MDN JavaScript editor mostly. Because your editor is very easy to use, with the run and reset button, not bloated. So it may be very nice to have it not only as a part of your tutorials but to have a special dedicated webpage with just a plain JavaScript editor. 

Thank you very much.

**Comment by Josh-Cena** [comment]
We discussed this a bit and the sentiment I got is that "this is useful for some but not necessary". I agree with this—a stand-alone editor page is probably not going to be any more discoverable than a random JS reference page, which is likely going to have an interactive example anyway. Plus, you get much more features using the browser's console.
