### ISSUE TITLE
Issue with "HTMLImageElement.srcset": Live example is missing the load handler

### ISSUE THREAD

**Issue by jonex2** [mdn/content#10811]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset

#### What information was incorrect, unhelpful, or incomplete?
The text says that "The following code is run within a handler for the window's load event. " but the code of the the live example (s. clock example) on https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/HTMLImageElement/srcset/_sample_.Example.html ist missing this handler.
Because of this the example doesn't work correctly with Chrome-browser. You don't see the srcset information below the image. 
 
As soon as you execute the code in the handler like this, it works:
```
window.addEventListener("load", () => {
  let box = document.querySelector(".box");
  let image = box.querySelector("img");

  let newElem = document.createElement("p");
  newElem.innerHTML = `Image: <code>${image.currentSrc}</code>`;
  box.appendChild(newElem);
});
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlimageelement/srcset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlimageelement/srcset/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by jonex2** [comment]
Would be nice to say "Thank you" for reporting the problem.

**Comment by hamishwillee** [comment]
@jonex2 Thank you for reporting the problem! It is appreciated.
