### ISSUE TITLE
Issue with "HTMLImageElement.srcset": Live example has wrong image

### ISSUE THREAD

**Issue by jonex2** [mdn/content#10812]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset

#### What information was incorrect, unhelpful, or incomplete?
In the live example with the clock the two images of the srcset attribute have the same pixel dimensions (width 400px). But the image with filename "clock-demo-200px.png" should have a width of 200px.

live example:
https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/HTMLImageElement/srcset/_sample_.Example.html
Image 1:  
https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/web/html/element/img/clock-demo-200px.png
Image 2:  
https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/web/html/element/img/clock-demo-400px.png. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlimageelement/srcset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlimageelement/srcset/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by jonex2** [comment]
Would be nice to say "Thank you" for reporting the problem.

**Comment by hamishwillee** [comment]
Thank you!
