### ISSUE TITLE
Content bug: Serve better images for HiDPi devices

### ISSUE THREAD

**Issue by WebReflection** [mdn/content#10824]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

## Specific page section or heading?

Every section with an image

## What is the problem?

Every image is blurry on HiDPi screens, because no picture or srcset is used.

<img src="https://user-images.githubusercontent.com/85749/143687974-3b150804-59f9-4dce-a593-8ee566ac574a.png" width="414">

On top of that, most images have no accessible content, so that:

  * people with sight problems cannot know what's the image about
  * people without sight problems but a good HiDPi screen, cannot 100% benefit from images on the page, as the text is **really** hard to read

Nobody wins, and bad practices around content are shown instead.

## What did you expect to see?

From the No.1 resource on the internet to learn about the Web, I expect its content to be up to the latest best practices.

I have found instead a page that looks from the 90's where HiDPi screens did not exist.

## Did you test this? If so, how?

I have surfed the Web and landed in that page which is otherwise full of interesting content.

**Comment by wbamberg** [comment]
Yeah, I agree that this is pretty bad. I wonder really why lots of these things are images at all rather than just text, and a lot of the text is honestly not that great either.

So I think though that fixing it properly would really mean rewriting much of this page.

**Comment by wbamberg** [comment]
A little while ago @SphinxKnight rewrote this page and replace the diagrams with SVGs. @WebReflection , please let us know if this issue can be closed now.

**Comment by WebReflection** [comment]
@wbamberg I can confirm it looks good now, the only blurry image is the Star Wars (caption) after but that's not super relevant for the page so feel free to close this.
