### ISSUE TITLE
Very anxious! The navigator. MediaDevices. GetUserMedia part in huawei mobile phone models open camera shows Could not start video source error

### ISSUE THREAD

**Issue by 243739177** [mdn/content#10820]
Should the project requirements, using the navigator. MediaDevices. GetUserMedia in WeChat browser open camera tips Could not start video source, but only in part of mobile phone models, the problems in huawei For example, huawei P40 and Huawei MATe30 Pro, how can I solve this problem? Ask for help! Very anxious!

**Comment by hamishwillee** [comment]
Closing. This sounds like you are having some sort of problem with your phone. This area is for reporting issues with the documentation.
