### ISSUE TITLE
Demo not working properly

### ISSUE THREAD

**Issue by limnestor** [mdn/content#10821]
![buy1](https://user-images.githubusercontent.com/1665280/143684107-1fa94d63-10e4-467f-9c72-c3657960be1e.jpg)

Click on cooperatively scheduled background task link on Result.

Result demo not working properly at https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API

**Comment by wbamberg** [comment]
Fix here is to remove that link from the example source: https://github.com/mdn/content/blob/0caadad1efcaca87c7b9f142419230e68e752950/files/en-us/web/api/background_tasks_api/index.md?plain=1#L93-L94

It's useless anyway since it just links to the embedding page.
