### ISSUE TITLE
Issue with "TypeScript support in Svelte": Change npm run validate to npm run check

### ISSUE THREAD

**Issue by SavaAdi** [mdn/content#10823]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_TypeScript

#### What information was incorrect, unhelpful, or incomplete?

**The application template has a validate script configured that runs svelte-check against your code.
You can also run the validate script in watch mode with npm run validate -- --watch. In this case,**
+other sections "npm run validate" command is mentioned 

#### Specific section or headline?
More than one, for example:
**Porting our to-do list app to TypeScript**

#### What did you expect to see?
Checking my **package.json** file I see that the script is now called _"check"_ instead of _"validate_".
 ```
...
 "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "sirv public",
    "check": "svelte-check --tsconfig ./tsconfig.json"
  },
...
```

#### Did you test this? If so, how?
Running `npm run validate -- --watch` does not work since there is no script with that name in package.json.
Running `npm run check -- --watch` works.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_typescript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_TypeScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_typescript/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks @SavaAdi for reporting. This has been fixed in https://github.com/mdn/content/pull/11550

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/10823#issuecomment-1030734127
