### ISSUE TITLE
Issue with "content_security_policy": examples contradict a statement (see below)

### ISSUE THREAD

**Issue by opto** [mdn/content#10836]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy

#### What information was incorrect, unhelpful, or incomplete?

'The policy must include at least the script-src and the object-src directives,'

#### Specific section or headline?

In this paragraph:
'There are restrictions on the policy you can specify here:'

#### What did you expect to see?

if there is an AND, I would not expect examples only having script-src. The statement tells script-src and object-src are required. If not, please clarify the statement. Thanks.

#### Did you test this? If so, how?

In TB, a script-source "self" throws an error on addon install

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
* Last commit: https://github.com/mdn/content/commit/629960fa07e15f2354d75daf14f149d4942539ec
* Document last modified: 2021-10-26T21:28:18.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. Fixed in https://github.com/mdn/content/pull/10843

This is the only case I found. I am fairly sure the text is correct and the example incorrect - but the reviewer will confirm.

![image](https://user-images.githubusercontent.com/5368500/143790623-58eebbf2-da5f-475c-b656-d5f777a3bc02.png)

**Comment by hamishwillee** [comment]
FYI the reviewer tells me I was wrong. You are allowed to have a CSP of just default-src. I have made the change to the text that said you must have the object-src etc.
