### ISSUE TITLE
Issue with "BrowserSetting.get()": unclear whether "controlled_by_other_extensions" means one cannot control the setting itself

### ISSUE THREAD

**Issue by rugk** [mdn/content#10838]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/types/BrowserSetting/get

#### What information was incorrect, unhelpful, or incomplete?

You write the `levelOfControl` can be used "to check whether you can modify the  setting", however, it is not clear whether `"controlled_by_other_extensions"` means
You write as a description "Another extension that was installed after this one has modified this setting.". Well okay, fair enough, but does that mean I can take control back with my extension or is it "locked" and only the latest extension that was installed can control this setting?

The other values are pretty clear.

#### Specific section or headline?
`levelOfControl`

#### What did you expect to see?
An explanation of whether I can take back control. Maybe even just a simple extra column with ticks named "Can be controlled", which thus shows which of these values allow the extension to take back control.

**Edit:** Ah, as I guess everything related to that [is explained here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/types/BrowserSetting/set), maybe you can also – or even better additionally – link to the `set` doc?

#### Did you test this? If so, how?
no(?)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/types/browsersetting/get`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/types/BrowserSetting/get
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/types/browsersetting/get/index.md
* Last commit: https://github.com/mdn/content/commit/629960fa07e15f2354d75daf14f149d4942539ec
* Document last modified: 2021-10-26T21:28:18.000Z

</details>

**Comment by rebloor** [comment]
> Ah, as I guess everything related to that [is explained here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/types/BrowserSetting/set), maybe you can also – or even better additionally – link to the set doc?

There is a clear link to the `set` documentation

>[levelOfControl](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/types/BrowserSetting/get#levelofcontrol)
>    string. This represents the way the setting is currently controlled. You can use it to check whether you can modify the setting. See [BrowserSetting.set()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/types/BrowserSetting/set) for details. Its value may be any of the following:
