### ISSUE TITLE
Issue with "<dialog>: The Dialog element": Cancel button wouldn't work if there is required input element

### ISSUE THREAD

**Issue by datvm** [mdn/content#10848]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

#### What information was incorrect, unhelpful, or incomplete?

When adding an `input` with `required` attribute, user cannot click Cancel to dismiss the dialog since the form cannot be submitted due to validation. It would be helpful to add a way to make a Cancel button.

#### Specific section or headline?

Advanced example

#### What did you expect to see?

A demo with a Cancel button that can work 

#### Did you test this? If so, how?

Relevant [StackOverflow question with code](https://stackoverflow.com/questions/70153242/is-it-possible-to-make-a-close-dismiss-button-for-html-native-dialog-no-plugi)

```html
<dialog id="diag">
  <form method="dialog">
    <input id="txt-name" required />
    
    <button value="submit">Submit</button>
    <button value="">Cancel</button>
  </form>
</dialog>

<button id="btn-show">Show Dialog</button>

<p>Result: <span class="result"></span></p>
```

```js
const diag = document.querySelector("#diag")

diag.addEventListener("close", () => {
  if (!diag.returnValue) { return; }
  
  document.querySelector(".result").textContent = document.querySelector("#txt-name").value;
});

document.querySelector("#btn-show").addEventListener("click", () => {
  diag.showModal();
});
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/dialog/index.md
* Last commit: https://github.com/mdn/content/commit/775662998e66813a612e3ff27e02f2ada867bc17
* Document last modified: 2021-10-03T00:01:51.000Z

</details>

**Comment by estelle** [comment]
This is covered:

> [<form>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form) elements can close a <dialog> if they have the attribute method="dialog" or if the button used to submit the form has formmethod="dialog" set. In this case, the state of the form controls are saved, not submitted, the <dialog> closes, and the [returnValue](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/returnValue) property gets set to the value of the button that was used to save the form's state.

**Comment by datvm** [comment]
@estelle Hi, even with both `method="dialog"` on the `form` and `formmethod="dialog"` on the cancel button, the form is still not submitted or dialog closed because the required field are not filled in.

See: https://codepen.io/datvm/pen/RwYERbB, click the "Show Dialog" button and then don't fill in anything, and click Cancel.

**Comment by florianmarkusse** [comment]
Is anyone working on this? Running into this issue as well.

**Comment by LokeshC2** [comment]
The correct way to implement a close button would be to use formnovalidate attribute on the button. You only need formmethod=dialog if he form itself does not specify method=dialog. It is not needed twice.

**Comment by datvm** [comment]
Can confirm @LokeshC2 's solution works.

**Comment by LokeshC2** [comment]
@estelle can this be closed now?

**Comment by Josh-Cena** [comment]
The `formnovalidate` trick should perhaps be mentioned in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#usage_notes
