### ISSUE TITLE
[WebAPI] Web Locks API under pref dom.weblocks.enabled

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#10859]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Looks like the Web Locks API is documented - so a check through that against spec is needed: https://wicg.github.io/web-locks/
Experimental feature `dom.weblocks.enabled` for BCD & rel notes

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1739233
https://bugzilla.mozilla.org/show_bug.cgi?id=1740044
https://bugzilla.mozilla.org/show_bug.cgi?id=1666833

**Comment by hamishwillee** [comment]
OK, so in FF96 it first got enabled in Nightly [bug1739233](https://bugzilla.mozilla.org/show_bug.cgi?id=1739233) and then release [bug 1740044](https://bugzilla.mozilla.org/show_bug.cgi?id=1740044). Seems to have been first implemented in FF93 behind pref ([bug 1725734](https://bugzilla.mozilla.org/show_bug.cgi?id=1725734)).

- [ ] Experimental feature - not required as will go live in FF96
- [ ] Release note
- [ ] BCD - pref in FF93
- [ ] Docs - TBD
- [ ] dev-doc-complete across the relevant bugs:
    - [ ] [bug1739233](https://bugzilla.mozilla.org/show_bug.cgi?id=1739233) 
    - [ ] [bug 1740044](https://bugzilla.mozilla.org/show_bug.cgi?id=1740044)

**Comment by hamishwillee** [comment]
This should be pretty much done. Just waiting on release notes and bcd to merge.
