### ISSUE TITLE
[WebAPI] Implement WebP image encoder

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#10853]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

I'm not entirely sure what is required here, but at a first pass adding WebP as a supported image type in `HTMLCanvasElement.toDataURL` is at least one place

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1511670

**Comment by hamishwillee** [comment]
The work for

**Comment by Rumyra** [comment]
That's sounds pretty much in line with what I was thinking when I looked at the bug @hamishwillee - at the end of the day it's just an added format to convert to, so I doubt there's much to do docs wise.

> My guess is that you could use this to create a drawing app and download the result in webp.

Yeh it's just 'saving' out what's on a canvas 👍

**Comment by hamishwillee** [comment]
@Rumyra Pretty much done. Just waiting on BCD to clear - that already went one round with Daniel and I am not expecting major surprises.

**Comment by Rumyra** [comment]
Brill - thank you @hamishwillee

**Comment by Janghou** [comment]
A quality/compression setting seems to be missing.

AFAICS, it's compression level is now something like 93%.

https://bugzilla.mozilla.org/show_bug.cgi?id=1511670

**Comment by hamishwillee** [comment]
Thanks @Janghou ,
I don't see that as something we would record here - at this point a user would probably only care that the file can save to the format, not on its specific compression.
