### ISSUE TITLE
[HTTP] Enable sameSite=lax by default

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#10857]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Enable sameSite=lax by default - related docs in bugzilla thread

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1617609

**Comment by hamishwillee** [comment]
I did most of the work to reflect this some months ago when it was added behind preference `network.cookie.sameSite.laxByDefault` - e.g. updates to https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#samesite_cookies and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

This issue enables this preference by default. So this requires BCD and release note update. Possibly also minor update to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

- [ ] BCD
- [ ] Release note
- [ ] Dev-doc complete
- [ ] Remove from experimental features (if needed)

**Comment by Rumyra** [comment]
In light BCD will be merged, am closing and will check back later

**Comment by hamishwillee** [comment]
Thanks. It will indeed.
