### ISSUE TITLE
[Not released] [WebAPI] Custom elements: implement willValidate for ElementInternals

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#10851]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Custom elements: implement willValidate for ElementInternals

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1556365

**Comment by hamishwillee** [comment]
Docs look pretty good already so mostly BCD (simple) and release note. I need to check what this concept really means though :-)

- [ ] Docs: [ElementInternals.willValidate](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/willValidate)
- [ ] BCD - add support from FF96
- [ ] Release note
- [ ] dev-doc-complete

**Comment by hamishwillee** [comment]
@Rumyra This is pretty much done once the other bits merge. Had to fix it up today because discovered that the feature is behind a preference. Point for you being that it is not in the release.

**Comment by Rumyra** [comment]
Thanks @hamishwillee 👍
