### ISSUE TITLE
[WebAPI] Intersection observer FF no longer throws exception for rootMargin

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#10854]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

(intersection-observer) Chrome allows an empty string for rootMargin, Firefox throws an exception, breaking some shopping sites. Probably just a note in BCD & checking docs

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1738791

**Comment by hamishwillee** [comment]
- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/13902
- [ ] Release note
- [ ] Docs - seem OK.
