### ISSUE TITLE
Issue with "Window: popstate event": (Missing user interaction required to fire event)

### ISSUE THREAD

**Issue by fpenovi** [mdn/content#10870]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event

#### What information was incorrect, unhelpful, or incomplete?
Documentation fails to mention the policy adopted by browsers ([like Chrome](https://groups.google.com/a/chromium.org/g/blink-dev/c/OCS7g72HtyI)) to **avoid back button abuse** which prevents `popstate` from being fired when no user interaction happened on the page (i.e: scroll, click, etc).

#### Specific section or headline?
It should probably be added into [When `popstate` is sent](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event#when_popstate_is_sent) section.

#### What did you expect to see?
Some paragraph like this one extracted from [Window: beforeunload event](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event):
>_To combat unwanted pop-ups, browsers may not display prompts created in beforeunload event handlers unless the page has been interacted with, or may even not display them at all._ 

#### Did you test this? If so, how?
Yes, I tested it on my own and here is a [JSFiddle](https://jsfiddle.net/0xwvLndu/) with a reproducible scenario extracted from [this StackOverflow discussion](https://stackoverflow.com/questions/57339098/chrome-popstate-not-firing-on-back-button-if-no-user-interaction).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/popstate_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/popstate_event/index.md
* Last commit: https://github.com/mdn/content/commit/6129d32ddb31d6c85e682e912782d2b826e1305f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #17640 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
