### ISSUE TITLE
Issue with "Intersection Observer API": non-zero intersection rectangle

### ISSUE THREAD

**Issue by joekingTheThird3** [mdn/content#10878]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

#### Specific section or headline?
This section needs clarification. Is this indeed correct?
'Note that it's possible to have a non-zero intersection rectangle, which can happen if the intersection is exactly along the boundary between the two or the area of boundingClientRect is zero. This state of the target and root sharing a boundary line is not considered enough to be considered transitioning into an intersecting state.'

#### What did you expect to see?
Not sure.
Can you have a zero (area/width) intersection rectangle?
 What does 'sharing a boundary line' mean? Does that mean overlap? Is the x/y coord of the root and x/y coord of the target the same coord?

Should the first line I quoted actually read:
''Note that it's possible to have a zero area intersection rectangle...' ?
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/intersection_observer_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/intersection_observer_api/index.md
* Last commit: https://github.com/mdn/content/commit/ab7b28b6fa5e278f5efb6fd4f51db8e82c5ec3cd
* Document last modified: 2021-09-30T08:57:06.000Z

</details>

**Comment by vlwkaos** [comment]
@joekingTheThird3 

Did a bit of testing, and yes I agree that the paragraph should read ''Note that it's possible to have a zero area intersection rectangle...' 

I think this sentence can be better by clarifying what is meant by 'the two'

> which can happen if the intersection is exactly along the boundary between the two...

- It is possible to have a zero area intersection rectangle when the boundary of a target is exactly along the root. When this happens the state of intersection is `false`.
- It is possible to have a zero area intersection rectangle when the area of a target is zero. In this case it seems like the position of the target matters when deciding what state the intersection is in.

Do above information clarifies the section you mentioned? If it is, I can make a change to the content.
