### ISSUE TITLE
Issue with "Componentizing our React app": (map don't found)

### ISSUE THREAD

**Issue by CuminoCarlo** [mdn/content#10871]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components

#### What information was incorrect, unhelpful, or incomplete?
The information about the function  Array.prototype.map(). It doesn't work with me. The browser give me this error: ×
TypeError: Cannot read properties of undefined (reading 'map')

#### Specific section or headline?
Rendering with iteration

#### What did you expect to see?
I aspect to see a paragraph dedicated to this problem

#### Did you test this? If so, how?
I follow tour instruction and put the string const taskList = props.tasks.map(task => task.name); above the return statement in App()

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by IestynGage** [comment]
Hey @CuminoCarlo I've had a look at [React_components#rendering_with_iteration](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components#rendering_with_iteration) and saw that the suggested line is: 
```javascript
const taskList = props.tasks?.map(task => task.name);
```
however you wrote:
```javascript
const taskList = props.tasks.map(task => task.name);
```
It seems that you've missed a `?` ([optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)). Whilst it's only a single charater, it's probably whats causing the error . In summary what this operator does it is that it checks `props.tasks` exists, if not then it returns `undeifined`, thus skipping `map(task => task.name)`. (If `props.tasks` does exists then it computes `map(task => task.name);`)

I hope this helps 😄

**Comment by Josh-Cena** [comment]
Closing per https://github.com/mdn/content/issues/10871#issuecomment-989213609
