### ISSUE TITLE
Issue with "-webkit-tap-highlight-color": Documented as inherited but not specified/implemented as inherited

### ISSUE THREAD

**Issue by eps1lon** [mdn/content#10886]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color

#### What information was incorrect, unhelpful, or incomplete?

Inherited

#### Specific section or headline?

Formal syntax

#### What did you expect to see?

Inherited | yes

#### Did you test this? If so, how?

1. Open https://codesandbox.io/s/webkittaphighlightcolor-inherited-2cbh5

If `-webkit-tap-highlight-color` would not be inherited then `.App  button` and `button` should have the same `-webkit-tap-highlight-color`. However `.App button` has the same `-webkit-tap-highlight-color` as `.App`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/-webkit-tap-highlight-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/-webkit-tap-highlight-color/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by wbamberg** [comment]
Yes, it also says in the ["spec"](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/AdjustingtheTextSize/AdjustingtheTextSize.html#//apple_ref/doc/uid/TP40006510-SW5):

> This is an inherited property
