### ISSUE TITLE
Issue with "Express Tutorial Part 3: Using a Database (with Mo…": (short summary here please)

### ISSUE THREAD

**Issue by nitramrelpmur** [mdn/content#10885]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

#### What information was incorrect, unhelpful, or incomplete?
In the Author model the required package "luxon" is missing. The code uses the DateTime type from this package.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#author_model

#### What did you expect to see?
The following line is missing:
const { DateTime } = require("luxon");  //for date handling

#### Did you test this? If so, how?
There is an error: DateTime is undefined.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for posting. This may well be correct - I need to do a little more investigation. Probably not until next week.

**Comment by hamishwillee** [comment]
Thanks very much. The fix is here: https://github.com/mdn/content/pull/10992

The solution is actually to revert to using `Date`. The flow here is that at this point you don't need to know about Luxon - so we just use the generic features.
