### ISSUE TITLE
Broken links on german <datalist> docs

### ISSUE THREAD

**Issue by ynn1k** [mdn/content#1089]
link of "globalen Attribute" under "Attribute" ends on a 404.
&
"HTML5
Die Definition von '`<datalist>`' in dieser Spezifikation." under "Spezifikationen" too.

https://developer.mozilla.org/de/docs/Web/HTML/Element/datalist

**Comment by Ryuno-Ki** [comment]
Hey @ynn1k,
thanks for reporting. Right now, translated content won't be touched.
See https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.

@peterbe Does that effect localised URLs like https://developer.mozilla.org/de/docs/HTML/Global_attributes in this case, too?
I _think_ you had something cooking along harmonising those URLs.

https://www.w3.org/TR/html52/the-datalist-element.html#the-datalist-element is also a dead end, but that is outside of MDN web docs

**Comment by chrisdavidmills** [comment]
> Hey @ynn1k,
> thanks for reporting. Right now, translated content won't be touched.
> See https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.

That's correct, thanks for reporting this @Ryuno-Ki 

> @peterbe Does that effect localised URLs like https://developer.mozilla.org/de/docs/HTML/Global_attributes in this case, too?
> I _think_ you had something cooking along harmonising those URLs.

We are soon enforcing a "en-US slugs only" policy to give tier 1 locales the same structure as the en-US content. But this doesn't include de, as it isn't a tier 1 locale (it has no active maintenance community). We'll be annouceing this in a blog post later today.
 
> https://www.w3.org/TR/html52/the-datalist-element.html#the-datalist-element is also a dead end, but that is outside of MDN web docs

**Comment by Ryuno-Ki** [comment]
For the Record: Closed, because German locale is frozen and there is a link to the English pendant.
