### ISSUE TITLE
Issue with "Audio()": browser compatibility table does not show ≤ symbol for WebView Android

### ISSUE THREAD

**Issue by MikeDimmickMnetics** [mdn/content#10899]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio

#### What information was incorrect, unhelpful, or incomplete?

The Browser Compatibility table shows '37' in the WebView Android cell. However, the underlying compatibility data (https://github.com/mdn/browser-compat-data/blob/53fe3ff177ec0b9cbe5cecbd8c7705d884865eb0/api/HTMLAudioElement.json#L41) has:

```json
"webview_android": {
    "version_added": "≤37"
}
```

A change was made to change every `webview_android` with `version_added` of `"1"` to `"≤37"`, as it had previously been assumed that anything in Chrome 1.0 was in WebView Android 1.0, but this was not felt to be a safe assumption (https://github.com/mdn/browser-compat-data/pull/10589)

#### Specific section or headline?

Browser compatibility table.

#### What did you expect to see?

The WebView Android cell should show '≤37' to indicate the uncertainty. In general, where the compatibility data has a ≤ symbol, this should be displayed in the resulting page.

#### Did you test this? If so, how?

This is an issue of compatibility data not being displayed correctly, rather than errors in the description of the API.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlaudioelement/audio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlaudioelement/audio/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by AnilSeervi** [comment]
BCD ranges are treated as exact versions to avoid confusion for the reader
See https://github.com/mdn/yari/issues/3238

Here's the code that removes `≤` from the versions - https://github.com/mdn/yari/blob/main/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx#L111-L113

**Comment by hamishwillee** [comment]
Closing, as on that basis this is intentional behaviour. Note that it will become less of a concern - most of the web platform now states actual values for starting versions, and this continues to improve.
