### ISSUE TITLE
Issue with "OLD SSL Reference": dead links to MDC guides and ref

### ISSUE THREAD

**Issue by CapitainFlam** [mdn/content#10903]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/SSL_functions/OLD_SSL_Reference

#### What information was incorrect, unhelpful, or incomplete?
the first note of the page : 
```
<div class="note">
  <ul>
    <li>We are migrating this SSL Reference into the format described in the <a
        href="/en-US/docs/Project:MDC_style_guide">MDN Style Guide</a>. If you are inclined to help with this migration,
      your help would be very much appreciated.</li>
  </ul>
  <ul>
    <li>Upgraded documentation may be found in the <a href="/NSS_reference">Current NSS Reference</a>
    </li>
  </ul>
```
contains deadlink to `<a
        href="/en-US/docs/Project:MDC_style_guide">MDN Style Guide</a>` 
or `<a href="/NSS_reference">Current NSS Reference</a>` 
It's bad :,-( 

Furthermore, other pages as 
[SSL error page : https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/SSL_functions/sslerr](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/SSL_functions/sslerr)
has the same issue. 

#### Specific section or headline?
line 8 to 17 of the [GitHug page of OLD_SSL_Reference](https://github.com/mdn/content/blob/main/files/en-us/mozilla/projects/nss/ssl_functions/old_ssl_reference/index.html)
line 7 to 16 of the [sslerr GitHub page](https://github.com/mdn/content/blob/main/files/en-us/mozilla/projects/nss/ssl_functions/sslerr/index.html)

#### What did you expect to see?
not a dead link :)

#### Did you test this? If so, how?
=> link `<a
        href="/en-US/docs/Project:MDC_style_guide">MDN Style Guide</a>` go to : 
[https://developer.mozilla.org/en-US/docs/Project:MDC_style_guide](https://developer.mozilla.org/en-US/docs/Project:MDC_style_guide)
and says :
```
Page not found

Sorry, the page /en-US/docs/Project:MDC_style_guide could not be found.
```
 
link `<a href="/NSS_reference">Current NSS Reference</a>`  goes to : 
[https://developer.mozilla.org/NSS_reference](https://developer.mozilla.org/NSS_reference)
and says : 
```
Page not found

Sorry, the page /NSS_reference could not be found.
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/projects/nss/ssl_functions/old_ssl_reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/SSL_functions/OLD_SSL_Reference
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/projects/nss/ssl_functions/old_ssl_reference/index.html
* Last commit: https://github.com/mdn/content/commit/7ce080a8d79c3ba23048cb7e28655818d6e49efb
* Document last modified: 2021-08-23T21:16:18.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @CapitainFlam 
This is a known issue. The content is being moved off MDN - I even tried the deletion previously in https://github.com/mdn/content/pull/8215

I'm going to close this

@escattone Can we delete the tree yet. I'm concerned this is open ended. Perhaps just dump it into the archive repo and let them take it when they want?
