### ISSUE TITLE
Issue with "Navigator.share()": (short summary here please)

### ISSUE THREAD

**Issue by tehniat** [mdn/content#10919]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

#### What information was incorrect, unhelpful, or incomplete?
contents did not have the information how to handle the following error
This site can’t provide a secure connection localhost sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

#### Specific section or headline?

  navigator.share(shareData.title,shareData.text,shareData.url,[file] )
#### What did you expect to see?
Please includes detail of ERR_SSL_PROTOCOL_ERROR # Did you test this? If so, how?
yes i have implemented the given code in react 

import { IconButton, TextField } from '@material-ui/core'
import { Share } from '@material-ui/icons'
import React from 'react'
import { useState ,useEffect} from 'react';

export default function MyShare2() {
   const [text1, setText] = useState('hi');
   const myImage='my image url'
   const shareData = {
        title: 'MDN',
        text: 'Learn web development on MDN!',
        url: 'https://developer.mozilla.org'
              
        
      }
      
      useEffect(() => {
        if (navigator.share === undefined) {
           if (window.location.protocol === 'http:') {
              window.location.replace(window.location.href.replace(/^http:/, 'https:'));
           }
        }
     }, []);
      const myHandleClick =async()=>{
                const response=await fetch(myImage)
                const blob= await response.blob()
                const file=new File([blob], 'share.jpg',{type:blob.type});
                
                try {
                   navigator.share(shareData.title,shareData.text,shareData.url,[file] )
                   setText('MDN shared Shared sucessfully')  
                } catch (error) {
                   setText(error)
                   
                }
       };
      
    return (
        
        <div>
          <IconButton>
              <Share onClick={myHandleClick}></Share>
                            
              </IconButton>
              <TextField value={text1}></TextField>   
        </div>
    )
}

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/navigator/share`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/share/index.md
* Last commit: https://github.com/mdn/content/commit/a72657860fa14af36721d69011ef27d930a766bf
* Document last modified: 2021-11-25T03:48:02.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for reporting, but I am closing this as invalid.

The error is unrelated to use of this API and is therefore not in the spec (or appropriate here). You are getting it for some other reason. I did a brief Internet search and it appears to be something Chrome can sometimes report.

**Comment by tehniat** [comment]
Ok thanks for your reply. I am using Axios Api instead of webshare and its working fine.
