### ISSUE TITLE
Command line crash course:  where is the real doc?

### ISSUE THREAD

**Issue by joefiesta** [mdn/content#10928]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line

#### What information was incorrect, unhelpful, or incomplete?

I searched for "command line" and only got one relevant hit on github.   this entry.   but, it is just a tutorial and documents only a couple command line parameters.    Where are ALL the command line parameters actualliy documented?   Seems the one bookmark I had is now not valid.  It is: https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options#-no-remote

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/command_line`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
* Last commit: https://github.com/mdn/content/commit/d05bc9c5acbbd1a7ce03d03dfb333753619797b5
* Document last modified: 2021-11-18T10:30:13.000Z

</details>

**Comment by hamishwillee** [comment]
Firefox docs were moved off MDN and are now maintained by the Firefox team. I am not sure where this particular document is, but you could ask on https://support.mozilla.org/en-US/products/firefox/get-started

The old MDN version is archived: https://github.com/mdn/archived-content/blob/main/files/en-us/mozilla/command_line_options/index.html
