### ISSUE TITLE
Issue with "place-content": need info about safe/unsafe

### ISSUE THREAD

**Issue by mfluehr** [mdn/content#10924]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/place-content

This page lacks information about the `safe` and `unsafe` keywords.

Compare with https://developer.mozilla.org/en-US/docs/Web/CSS/align-content and https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/place-content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/place-content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/place-content/index.md
* Last commit: https://github.com/mdn/content/commit/9b6feffb4828a7e318cd4a22041d887f430bedf5
* Document last modified: 2021-10-29T00:37:17.000Z

</details>

**Comment by sideshowbarker** [comment]
Fixed by #11183
