### ISSUE TITLE
Content bug: invalid syntax in "syntax" sections

### ISSUE THREAD

**Issue by jugglinmike** [mdn/content#10937]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/FinalizationRegistry

## Specific page section or heading?

Syntax

## What is the problem?

[MDN's guidance on writing "Syntax" sections](https://developer.mozilla.org/en-US/docs/MDN/Structures/Syntax_sections) includes two patterns which are invalid syntax:

> ### Callback syntax blocks
>
> [...]
>
> ```js
> filter((currentValue) => { ... } )
> ```
>
> [...]
>
> ### Syntax for arbitrary number of parameters
>
> [...]
>
> ```js
> unshift(element0, element1, ... , elementN)
> ```

Those well-versed in JavaScript likely recognize that a shorthand is in use. In my experience teaching first-time programmers, though, many folks initially assume they are looking at some language feature that they have not yet discovered.

## What did you expect to see?

By extending its recommended patterns with multi-line comments, MDN can avoid suggesting that some functions support distinct invocation grammar. More concretely:

```diff
-filter((currentValue) => { ... } )
+filter((currentValue) => { /* ... */ } )
```

```diff
-unshift(element0, element1, ... , elementN)
+unshift(element0, element1, /* ... , */ elementN)
```

The extra characters might be taken as noise by those who are familiar with the language, but I think the overhead is negigible compared to the clarity it affords newcomers.

If this suggestion is accepted, I'd be glad to update the relevant documentation, templates, and content.

Thanks for maintaining such an invaluable resource!

**Comment by AnilSeervi** [comment]
> many folks initially assume they are looking at some language feature that they have not yet discovered

It sure does look like `spread` or `rest` operator. which is an actual syntax in JavaScript.

`Rest` - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters
`Spread` - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by hamishwillee** [comment]
@Elchi3 Thoughts? 

Using the commented syntax is certainly "no worse"

**Comment by Elchi3** [comment]
I think this is a good idea.
