### ISSUE TITLE
Issue with "Using IndexedDB": broken live demo link

### ISSUE THREAD

**Issue by justinjc** [mdn/content#10941]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB

#### What information was incorrect, unhelpful, or incomplete?
The link "Test the online live demo" close to the end of the page is broken (https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB/_sample_.Full_IndexedDB_example.html).

#### Specific section or headline?
At the end of "Full IndexedDB example"

#### What did you expect to see?
Expected a working link to a working live demo.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/indexeddb_api/using_indexeddb`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/indexeddb_api/using_indexeddb/index.md
* Last commit: https://github.com/mdn/content/commit/5f82874a394e6f53fbd9fbebe42e235e8b5095db
* Document last modified: 2021-11-02T19:34:20.000Z

</details>

**Comment by wbamberg** [comment]
The example is merged into dom-examples (thanks Florian) so we just have to update the MDN page to point to it.
