### ISSUE TITLE
Issue with "Element: dblclick event": (short summary here please)

### ISSUE THREAD

**Issue by AnatuGreen** [mdn/content#10944]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event

#### What information was incorrect, unhelpful, or incomplete?
Not working on Opera browser latest version as at 03-Dec-2021.
Version: 82.0.4227.23

Works on Chrome, Edge, Mozilla browsers but the button is not working when tested on Opera 

#### What did you expect to see?
I added and event listener (dblclick) to a button and added the function to console log out a string for test. It did not log out on Opera but did on other browsers.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/dblclick_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/dblclick_event/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>
I added and event listener (dblclick) to a button and added the function to console log out a string for test. It did not log out on Opera but did on other browsers.

**Comment by hamishwillee** [comment]
So the in-page test of this event works fine on Opera - i.e. double click the box and note that it doubles in size.
![image](https://user-images.githubusercontent.com/5368500/144767525-797158c2-fa80-493b-a5b7-296152aafb5d.png)

I'm closing as "not a defect in this page" since it clearly does work.
