### ISSUE TITLE
Web extensions privacy API not showing compatibility data

### ISSUE THREAD

**Issue by rebloor** [mdn/content#10969]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy#browser_compatibility

## Specific page section or heading?

Browser compatibility

## What is the problem?

No compatibility data is showing.

<img width="1538" alt="image" src="https://user-images.githubusercontent.com/7352080/144652224-603a9220-873e-447c-85e8-4dae842065d1.png">

However, compatibility data for the APIs properties is displayed:

<img width="1538" alt="image" src="https://user-images.githubusercontent.com/7352080/144714272-308a46fa-72f5-4c4a-a30d-676075ea3705.png">

## What did you expect to see?

The compatibility data from https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/privacy.json

**Comment by ShadowWalker918** [comment]
I just wanted to see what would happen if you overlapped all sources. I am bored and new to this field.

**Comment by rebloor** [comment]
@ShadowWalker918 Please clarify your comment

**Comment by ShadowWalker918** [comment]
If I do that the ppl will steal my idea. The actual error that I created hasn't even been mentioned.

**Comment by hamishwillee** [comment]
@rebloor The problem is with the browser compat data - the top level https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/privacy.json#L5 does not have a `__compat` section. 

Either it's a fix to the data or a fix to yari to allow rendering of sub features if there is no compat data in the parent. I suspect the former.

PS I deleted the spam comments chain here.

**Comment by rebloor** [comment]
@hamishwillee Neither does https://github.com/mdn/browser-compat-data/blob/5a1494b6100bee72631b3d605ac4b47ef872a88c/webextensions/api/permissions.json#L5  and that displays compatibility data on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions. And, that doesn't appear to be the only example.
Seems to suggest this is more of a yari issue.

**Comment by hamishwillee** [comment]
It might well be. Do you have the rights to push it across to yari for discussion?

**Comment by rebloor** [comment]
@hamishwillee Not aware of having any "rights to push" I was simply going to create a new issue and close this one

**Comment by hamishwillee** [comment]
Sure, that works too. 

FYI someone else posted a BCD issue on the "missing" compat data here: https://github.com/mdn/browser-compat-data/issues/13895 . While that might not be the cause of this problem it might possibly fix the problem.

**Comment by ShadowWalker918** [comment]
...
