### ISSUE TITLE
discrepancy in article "Introducing asynchronous JavaScript"

### ISSUE THREAD

**Issue by yhas14** [mdn/content#10967]
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing

For reasons illustrated earlier (e.g. related to blocking), many Web API features now use asynchronous code to run, especially those that access or fetch some kind of resource from an external device, such as fetching a file from the network, accessing a database and returning data from it, accessing a video stream from a web cam, or broadcasting the display to a VR headset.

**Why is this difficult to get to work using asynchronous code?**

I think this meant to say, ' Why is this difficult to get to work using synchronous code?'

**Comment by hamishwillee** [comment]
Thanks but this is correct. It is explaining why asynchronous code is hard to get to to work.
