### ISSUE TITLE
Content update: SVG `tabindex` accessibility consideration

### ISSUE THREAD

**Issue by Malvoz** [mdn/content#10965]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/tabindex

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/tabindex#example

## What is the problem?

The `tabindex` example uses values greater than 0, which is best avoided unless an informed decision is made: https://dequeuniversity.com/rules/axe/4.1/tabindex.

## What did you expect to see?

I'd suggest the SVG tabindex example only uses `tabindex="0"`.

Related: https://developer.mozilla.org/en-US/docs/Web/Accessibility

**Comment by vlwkaos** [comment]
Does this SVG attribute have different specification from global DOM attribute [tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)?

This page simply wants to demonstrate tabindex with SVG, so I think one way to inform people about:

> The tabindex example uses values greater than 0, which is best avoided unless an informed decision is made:

is to simple link to `tabindex` global attribute page.
