### ISSUE TITLE
Issue with "Destructuring assignment": Note code tag overflowing

### ISSUE THREAD

**Issue by plfstr** [mdn/content#10971]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

#### What information was incorrect, unhelpful, or incomplete?
A note has a lengthy code tag which overflows the container causing horizontal page scrolling at narrow screen widths.

#### Specific section or headline?
Note after section: [Setting a function parameter's default value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#setting_a_function_parameters_default_value)

> Note: In the function signature for drawChart above, the destructured left-hand side is assigned to an empty object literal on the right-hand side: `{size = 'big', coords = {x: 0, y: 0}, radius = 25} = {}`

#### What did you expect to see?
The code example to line-wrap to remain inside the container OR the notes container overflow handled via scrolling.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/destructuring_assignment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/destructuring_assignment/index.md
* Last commit: https://github.com/mdn/content/commit/0f1f6f74804725f379465c09f698b88611292c90
* Document last modified: 2021-12-01T06:01:14.000Z

</details>

**Comment by AnilSeervi** [comment]
`<code>` blocks have CSS rule [`white-space: nowrap;`](https://github.com/mdn/mdn-minimalist/blob/main/sass/atoms/_code.scss#L9), which is causing the issue.

**Comment by hamishwillee** [comment]
I've done the easy fix - change to a code block - in #10989.
