### ISSUE TITLE
Content bug: <arguments.length>

### ISSUE THREAD

**Issue by lingyuncelia** [mdn/content#10973]
function xxx(a,b,c) {
    console.log(arguments.length)    
}
xxx(1,2)
console.log('arg:',arguments.length) 

The fifth line of code reports an error at the console：
Uncaught ReferenceError: arguments is not defined
About this, I can understand.
But in vscode,the fifth line of code reports:
arg: 5
Why does it work？
What does 5 mean？

**Comment by hamishwillee** [comment]
@lingyuncelia This area is for posting bugs against MDN content. As you have not filled in the template questions we don't know how to help you. Closing as  invalid.
