### ISSUE TITLE
Issue with "handler.apply()": target argument description

### ISSUE THREAD

**Issue by mikeandtherest** [mdn/content#10980]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/apply

#### What information was incorrect, unhelpful, or incomplete?

Incomplete/vague argument description.

#### Specific section or headline?

"Parameters" section -> `target` argument

#### What did you expect to see?

The current description of the `target` argument looks like this:

```
The target object.
```

In my opinion, since `target` must be a callable, I think it would be better to change the description to this:

```
The target function object.
```

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/proxy/proxy/apply`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/apply
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/proxy/proxy/apply/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by chandantiwari1** [comment]
How can I make it correct.

**Comment by evilpie** [comment]
The target could be a non-function callable, i.e another Proxy, so this would incorrect. Seems like there is a preexisting inaccuracy as well with:

>  The target must be a callable itself. That is, it must be a function object.

**Comment by mikeandtherest** [comment]
> The target could be a non-function callable, i.e another Proxy

Even if it's another Proxy, it needs to be a callable one. That is a function proxy. I don't think it's meant to work with regular objects.

That being said, maybe it's better to have it like this:

```
The target callable object.
```

**Comment by sideshowbarker** [comment]
> That being said, maybe it's better to have it like this:
> 
> ```
> The target callable object.
> ```

Thanks — I’ve opened #11066 with a fix that makes that change.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
