### ISSUE TITLE
Issue with "Setting up a Django development environment": All links to docs.djangoproject.com refer to v3.1 -- can these be easily updated to v3.2 (and (best-of-worlds) auto-update to current release)?

### ISSUE THREAD

**Issue by git-mar29** [mdn/content#10987]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/development_environment

#### Specific section or headline?
First example, on the above-referenced page:

=  =  =  =  =  
**What version of Python should be used?**

You can use any Python version supported by your target Django release. For Django 3.1.2 the allowed versions are Python 3.6 to 3.8 (see [FAQ:Installation](https://docs.djangoproject.com/en/3.1/faq/install/#what-python-version-can-i-use-with-django)).
=  =  =  =  =  

The link "FAQ:Installation" links to the url:  
    [https:// docs.djangoproject.com/en/ **3.1** /faq/install/#what-python-version-can-i-use-with-django](https://docs.djangoproject.com/en/3.1/faq/install/#what-python-version-can-i-use-with-django)

#### What did you expect to see?
The link url should refer to the doc page for Django version 3.2:  
    [https:// docs.djangoproject.com/en/ **3.2** /faq/install/#what-python-version-can-i-use-with-django](https://docs.djangoproject.com/en/3.2/faq/install/#what-python-version-can-i-use-with-django)

#### Did you test this? If so, how?
I copied the link address on the MDN page, and pasted it into a new browser window: it was the "v3.1" page.
I clicked on the link itself, and found it went to Django v3.1.

I manually replaced "3.1" with "3.2" in my browser, and -- for this specific URL, actually got **different content** about Python and Django versions. I put the 3.1 page and 3.2 page on adjacent tabs, and switched back and forth to confirm.

...This isn't a total emergency or anything, but:
* (I personally have found that) the MDN's  Django introduction is **far** better-written than the Introduction docs on the Django website itself -- so it's in everyone's interest that the links on these pages refer to the correct pages on the Django website for the detailed reference material.

Thanks, & best regards,  
git-mar29

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/development_environment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/development_environment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/development_environment/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by hamishwillee** [comment]
Hi @git-mar29 

The short answer is "not yet".  Periodically I run through this whole tutorial and test against the latest possible version of Django - at that point I update the links to match along with updating any new methods etc where things have been improved. If I update to 3.2 now without doing a full check it is possible there will be some mis-alignment in what the tutorial says you should do and Django say. 

Thanks very much for your post though. This will certainly happen at some point.

**Comment by hamishwillee** [comment]
PS Pleased you like the tutorial.

**Comment by git-mar29** [comment]
Wow, thanks for the quick reply! Once I figured out the "link thing", I just changed them as needed.

The **big** thing, though, is the whatever-it-is in the (your?) technical writing that makes the MDN Django intro a joy (as these things go) to read and work through on my own machine.

Best regards, again!
