### ISSUE TITLE
Content bug: Left shift Description not correct

### ISSUE THREAD

**Issue by HerrCai0907** [mdn/content#10999]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Left_shift

## What is the problem?

>The left shift operator (<<) shifts the first operand the specified number of bits to the left. Excess bits shifted off to the left are discarded. Zero bits are shifted in from the right.

This is not correct. In chromium and nodejs-12, when I try to run 100 << 32, I get result 100 instead of 0. 
So the `Excess bits shifted off to the left are discarded` should be changed to `Excess bits shifted off to the left are used in the right` or other similar.

**Comment by AnilSeervi** [comment]
JavaScript stores numbers as 64 bits floating point numbers, but all bitwise operations are performed on 32 bits binary numbers.
Before a bitwise operation is performed, JavaScript converts numbers to 32 bits signed integers.
After the bitwise operation is performed, the result is converted back to 64 bits JavaScript numbers.

so as you exceed 31, the RHS `shift_value` is basically reminder from 32(`shift_value%32`)

you can check the values in binary from the following expr:
```js
(100<<32).toString(2)    // 1100100
(100<<0).toString(2)     // 1100100
```

**Comment by HerrCai0907** [comment]
understand, thanks! 100<<32 = 100 is because 100 << 32 = 100<<(32 % 32) = 100 << 0 = 100, instead of cycle shift.

**Comment by AnilSeervi** [comment]
> understand, thanks! 100<<32 = 100 is because 100 << 32 = 100<<(32 % 32) = 100 << 0 = 100, instead of cycle shift.

Yep :)

**Comment by hamishwillee** [comment]
Cool. Would one of you like to add a comment about this in the doc - i.e. the description is not incorrect, but nor is it complete.

**Comment by generalmimon** [comment]
https://github.com/mdn/content/issues/10999#issuecomment-986872124:

> Before a bitwise operation is performed, JavaScript converts numbers to 32 bits signed integers.

@AnilSeervi Well, yes, but this fact does not actually explain this behavior - if you convert the number `32` or `33` from the double-precision float to the signed 32-bit integer, you are still getting integers `32` and `33`. The range of signed 32-bit integers is from **−2<sup>31</sup>** (`-0x8000_0000` in JS) to **2<sup>31</sup> − 1** inclusive  (`0x7fff_ffff` in JS), so as long as you use integers in this range, you won't lose any precision.

One cannot _expect_ from the above that the right operand of bit shift operators is somehow special and hence is not only converted to the 32-bit integer, but even taken just as modulo 32 - that is a totally different thing.

> so as you exceed 31, the RHS `shift_value` is basically reminder from 32(`shift_value%32`)

It behaves as _proper_ modulo 32 (associated with floored division: `a mod d = a - Math.floor(a / d) * d`), **not** the [remainder (`%`)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder) as you suggest, which is associated with truncated division in JS (`a % d = a - d * Math.trunc(a / d)`). This makes a difference for negative dividends: with modulo, you always get a non-negative number for any dividend `a` (`0 <= a mod d < d`), but with remainder, you get non-positive numbers for negative dividends (`a < 0`: `-d < a % d <= 0`).

`x mod 32` can be simulated as `x & 31`, see https://graphics.stanford.edu/~seander/bithacks.html#ModulusDivisionEasy. So any bit shift `a >>> b` is always equivalent to `a >>> (b & 31)` (or `a >>> (b & 0b0001_1111)`) - the same applies to other bit shifts (`<<` and `>>`) too.

```js
function dumpInt32(x) {
    console.log('0b' + (x >>> 0).toString(2).padStart(32, '0').match(/.{1,8}/g).join('_'));
}

dumpInt32(0xb200_0000);
// 0b10110010_00000000_00000000_00000000
dumpInt32(0xb200_0000 >>> -4);
// 0b00000000_00000000_00000000_00001011
// -4 mod 32 = -4 & 31 = 28
dumpInt32(0xb200_0000 >>> 28);
// 0b00000000_00000000_00000000_00001011

dumpInt32(0x0000_004d);
// 0b00000000_00000000_00000000_01001101
dumpInt32(0x0000_004d << -4);
// 0b11010000_00000000_00000000_00000000
// -4 mod 32 = -4 & 31 = 28
dumpInt32(0x0000_004d << 28);
// 0b11010000_00000000_00000000_00000000
```

**Comment by generalmimon** [comment]
JavaScript apparently behaves the same as Java (https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.19):

> If the promoted type of the left-hand operand is int, only the five lowest-order bits of the right-hand operand are used as the shift distance. It is as if the right-hand operand were subjected to a bitwise logical AND operator & ([§15.22.1](https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.22.1)) with the mask value 0x1f (0b11111). The shift distance actually used is therefore always in the range `0` to `31`, inclusive.

IMHO something like this should be written in the MDN docs as well - currently it does not mention this case at all, AFAIK.
