### ISSUE TITLE
Issue with "overflow": (short summary here please)

### ISSUE THREAD

**Issue by TbirdDuncan** [mdn/content#11034]
No scrollbar is present in the example provided

**Comment by AnilSeervi** [comment]
I guess that is what the `overflow` property does.

Only the property values `auto` and `scroll` give the _box_ a scrollbar(if the content seems to overflow)

**Comment by sideshowbarker** [comment]
@TbirdDuncan What articles should be updated to resolve this issue?

**Comment by sideshowbarker** [comment]
Closing for lack of response.
