### ISSUE TITLE
Content bug: "See also" section for Element.innerHTML inaccurately describes XMLSerializer

### ISSUE THREAD

**Issue by othermaciej** [mdn/content#11036]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML

## Specific page section or heading?

"See also"

## What is the problem?

The section includes the bullet: "Serializing XML or HTML into a DOM tree: XMLSerializer". This is inaccurate. XMLSerializer doesn't serialize anything into a DOM tree, it serializes a DOM tree into an XML string.

## What did you expect to see?

Something like: "Serializing a DOM tree into an XML string: XMLSerializer"

## Did you test this? If so, how?

n/a

**Comment by othermaciej** [comment]
Other related pages have similar errors:

https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML
XMLSerializer: Construct a DOM representation of XML text

That's not accurate, XMLSerializer does the opposite. It constructs XML text from a DOM.

https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML
Serializing DOM trees into XML or HTML: XMLSerializer

Nope, it only serializes into XML; can't do HTML.

**Comment by othermaciej** [comment]
There's also a slight accuracy error with the DOMParser description on the original page:

"Parsing HTML into a DOM tree: DOMParser"

DOMParser can parse either HTLM or XML into a DOM tree.

**Comment by sideshowbarker** [comment]
Thanks for catching those problems — I’ve opened https://github.com/mdn/content/pull/11048 with fixes.
