### ISSUE TITLE
Issue with "Window: deviceorientation event": orientation-devtool link is broken 

### ISSUE THREAD

**Issue by wgwz** [mdn/content#11041]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientation_event

#### What information was incorrect, unhelpful, or incomplete?

There is a link called orientation-devtool that is broken.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/deviceorientation_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientation_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/deviceorientation_event/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/11047 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
