### ISSUE TITLE
“Contributing to MDN” link in README seems to be broken

### ISSUE THREAD

**Issue by simevidas** [mdn/content#11042]
Steps to reproduce:

1. Go to https://github.com/mdn/content/blob/main/README.md
2. Click the “Contributing to MDN” link in the first note at the top

That link’s URL is https://developer.mozilla.org/en-US/docs/MDN/Contribute

I’ve tried in multiple browsers. The page does not load correctly. For example, I’m getting “page isn’t redirecting properly” in Firefox.

**Comment by sideshowbarker** [comment]
Thanks yeah, please see https://github.com/mdn/content/issues/11046#issuecomment-988572574. Something’s borked but we need @mdn/core-yari-dev help to troubleshoot it. So, will close this as being tracked in #11046
