### ISSUE TITLE
Issue with "Page Visibility API": how to remove from W3C spec?

### ISSUE THREAD

**Issue by JakeQZ** [mdn/content#11045]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

#### What information was incorrect, unhelpful, or incomplete?

How does one get this API removed from the W3C spec on grounds of privacy?

Can we re-allow other potential XSS vectors that had more useful benefits?

Or is the W3C just cow-towing to Google, YouTube, and other providers with video ads who want to make sure the ads are seen?

The forced showing of ads was not what the internet was designed for and the loopholes that allow this should be closed, instead of the opposite which is allowing Google etc. to dictate the API.

Adding more APIs to track users and control content-delivery is unacceptable.  Tim Berners-Lee would certainly not approve.

How does one go about getting APIs such as this removed?

#### What did you expect to see?

Nothing except resistance to this snooping API 

#### Did you test this? If so, how?

I used the internet and found it to be nothing but a sea of adverts, or content specifically written to game search engines in order to drive advertising revenue.

Sites with audio/video content atop playing as soon as you try to do something else 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/page_visibility_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/page_visibility_api/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
The scope of this repo is content within MDN itself, not the content of W3C specifications.

**Comment by JakeQZ** [comment]
Thank you for your dismissive response,

Are you aware of other projects that may cover some or any of the issues I referred to in the OP?  If so, would you be able to point me in the right direction?

In terms of W3C etc, might I suggest that the documentation pages carry relevant and up-to-date links?

If W3C keep changing the URL of the relevant 'thing' - this is the case in a lot of cases - might I suggest you keep nobbling them for some kind of, um, IDK, permanant link - it might be called a permalink.
