### ISSUE TITLE
Issue with "Setting up a Node development environment": (short summary here please)

### ISSUE THREAD

**Issue by AndrewSRea** [mdn/content#11059]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment

#### What information was incorrect, unhelpful, or incomplete?

Why is port 8000 used in the example in the section listed below but port 3000 is used in the other examples in other sections? This caused an error -- "cannot GET /catalog/" -- to appear in my browser when I tried to open the app using "http://127.0.0.1:8000", and I wasted time searching all over the Internet for an answer. Thankfully I found that using port 3000 is better than using port 8000.
I think the instructions in the example in the section listed below should be changed.

#### What did you expect to see?

See above.

#### Did you test this? If so, how?

See above.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/development_environment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/development_environment/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @AndrewSRea .
There is no reason for them to be different or the same. It's not a bug but happy to update so that people don't waste time on something that isn't part of the "learning focus" - #11097
