### ISSUE TITLE
Issue with "Test your skills: Math": the tests make critically flawed assumptions in their requests

### ISSUE THREAD

**Issue by ghost** [mdn/content#11058]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Math

#### What information was incorrect, unhelpful, or incomplete?

The tests, while highly useful in reinforcing the material being taught, make critically flawed assumptions in their requests.

Their requests presuppose that the information conveyed up until that point, and any subsequent nuances, have been understood, and retained by the learner. This notion might not be explicitly espoused within the text itself; however, it can be inferred by the lack of reference to the information needed to complete the task being asked of the learner.

For example, in the section titled ["Test your skills: Math - Math 3" ](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Math#math_3)the learner is given the following instruction;

_In the final task for this article, we want you to write some tests. You've got three groups, each consisting of a statement and two variables. For each one, write a test that proves or disproves the statement made. Store the results of those tests in variables called `weightComparison`, `heightComparison`, and `pwdMatch`, respectively._

For someone who is versed in JavaScript, this is probably an exceedingly trivial task to perform; perhaps even if they have somewhat limited previous exposure to the language, or knowledge of other programming languages.

However, if the learner is completely new to the field, with little to no exposure - barring what they have managed to glean from their progress in the course thus far - this sort of request, while challenging, can also serve as a bit of a discouragement in regards to the learning process.

Perhaps is would better serve the learner if references were given to pin-point where in the course the information was previously conveyed; meaning, providing a hint that they have indeed been introduced to these concepts, and a link to those concepts to serve as a refresher?

Looking at the information, there are no contextual clues that would provide a nudge in the direction the learner needs to go to review previous information to complete the task successfully, as the instructions do not correlate to the section titles. Consider the following instruction;

 _"For each one, write a test that proves or disproves the statement made."_

None of the chapter titles provide any indication that this information was expounded upon previously. A more effective rendering of the text would look like this;

__In the final task for this article, we want you to write some tests using the information previously taught in the following sections;_

_[A link to the section where the information needed to complete the challenge was taught](#)_

_You've got three groups, each consisting of a statement and two variables. For each one, write a test that proves or disproves the statement made. Store the results of those tests in variables called `weightComparison`, `heightComparison`, and `pwdMatch`, respectively.__

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/test_your_skills_colon__math`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Math
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/test_your_skills_colon__math/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by bsmth** [comment]
It appears the changes requested have been added:

>The aim of this skill test is to assess whether you've understood our [Basic math in JavaScript — numbers and operators](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math) article.

It's clear from the introduction that the reader should be applying what they've learned from these resources. I've made a pass over this page anyway to make some minor simplifications.
