### ISSUE TITLE
Unclear usage of "a group of siblings" in :nth-child() and :nth-of-type() descriptions.

### ISSUE THREAD

**Issue by berkleebytez** [mdn/content#11055]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child

#### What information was incorrect, unhelpful, or incomplete?
In both the nth-of-type and nth-child docs, it is unclear from the description which elements make up 'a group of siblings'. Are the siblings element-agnostic? Or does the element type matter? Not only would answering these questions clarify each document, it would also help to clarify the difference between the two selectors. 

#### Specific section or headline?
Very first sentence.

#### What did you expect to see?

suggested :nth-of-type description:
The :nth-of-type() CSS pseudo-class matches an element of a given type (tag name) if its position among similarly-typed siblings matches the given pattern.

suggested :nth-child description:
The :nth-of-type() CSS pseudo-class matches an element of a given type (tag name) if its position among siblings matches the given pattern.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_nth-of-type`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_nth-of-type/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by dev-nicolaos** [comment]
I can work on this

**Comment by dev-nicolaos** [comment]
Put up a PR to address the central problem stated in this issue:

> it is unclear from the description which elements make up 'a group of siblings'.

I opted not to use the OP's suggested descriptions as...
1) the selector's can select multiple elements not just one
2) the `nth-child` selector does not take element type into account

...but hopefully the clarifications are helpful.
