### ISSUE TITLE
Issue with ":scope": Examples don't work

### ISSUE THREAD

**Issue by estelle** [mdn/content#11069]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:scope

#### What information was incorrect, unhelpful, or incomplete?
This needs to be looked at. The example doesn't work.

#### What did you expect to see?
The paragraph, I assume, should have been lime. It wasn't

#### Did you test this? If so, how?
FF & Chrome, both support it according to BCD

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_scope`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:scope
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_scope/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
The [examples](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope#examples) look good to me.

The introduction presents a CSS declaration block that sets the background color of the root `html` element to lime, but the following paragraph explains this well enough.

> Currently, when used in a stylesheet, :scope is the same as :root, since there is not at this time a way to explicitly establish a scoped element.

Perhaps the introduction should be clearer that `:scope` is, at this time, only useful when used in a selector passed to one of the mentioned DOM APIs. To avoid confusion, maybe the introduction's stylesheet demonstration should be removed (until such time it would be useful).

**Comment by estelle** [comment]
@scope is now supported in Canary: https://codepen.io/miriamsuzanne/pen/wvyBNXP?editors=1100 - view in canary only

**Comment by Josh-Cena** [comment]
@estelle, is this issue still relevant? `@scope` and `:scope` are probably not the same thing. Maybe we just need to add a note as mentioned in https://github.com/mdn/content/issues/11069#issuecomment-991882097?

**Comment by OnkarRuikar** [comment]
: confused : In examples section no color has been set on paragraphs. The introductory section code also works: https://jsfiddle.net/h5a864L2/

> https://github.com/scope is now supported in Canary: [codepen.io/miriamsuzanne/pen/wvyBNXP?editors=1100](https://codepen.io/miriamsuzanne/pen/wvyBNXP?editors=1100) - view in canary only

We do not have a page for `@scope` (https://drafts.csswg.org/css-cascade-6/#scoped-styles). Also there is no entry for it in BCD repo https://github.com/mdn/browser-compat-data/tree/main/css/at-rules

**Comment by Josh-Cena** [comment]
I don't think there's any bug with `:scope`, per se, so I'm closing this. `@scope` doesn't look like available in any stable browser yet, and that will be a separate topic to document anyway.
