### ISSUE TITLE
mdn webpage goes blank and throws some errors

### ISSUE THREAD

**Issue by lucianocavallo** [mdn/content#11071]
Hello, I've experienced this problem in some pages of mdn like "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND", that throw some errors on the console and the page goes blank.
I'm new to the frontend developer world and wasn't able to figure out what was the problem, so I send you a screenshot of the console's errors, so you can be aware of.
Thank you very much by the dedication shown in your web, it really helps a lot for a student of JS like me.
![mdn_error_screenshot](https://user-images.githubusercontent.com/91575506/145352615-92b68c23-b0af-4812-9bda-0dbdff8b8d4b.png)

**Comment by chrwahl** [comment]
I have en same experience. When focusing on the search input element the page loads https://developer.mozilla.org/static/js/22.2c17438b.chunk.js but fails (404). This creates an error in the following script and all the content on the page is removed.

**Comment by sideshowbarker** [comment]
I can’t reproduce this, but maybe someone from @mdn/core-yari-dev might have some insight

**Comment by fiji-flo** [comment]
Could I couldn't reproduce it either. Could you specify browser, version, OS. And maybe try in a different browser / without extensions?

**Comment by chrwahl** [comment]
> Could I couldn't reproduce it either. Could you specify browser, version, OS. And maybe try in a different browser / without extensions?

Yes, I have tested in Ubuntu; Google Chrome 96 and Firefox 94. I request https://developer.mozilla.org/static/js/22.2c17438b.chunk.js in both. Chrome returns a JavaScript file (so, the page works) and Firefox returns 404 page.

I have tried to remove headers in Firefox, disable cache and open in private window -- same result.

**Comment by fiji-flo** [comment]
Could you test
```
curl -I https://developer.mozilla.org/static/js/22.2c17438b.chunk.js
```
vs
```
curl https://developer.mozilla.org/static/js/22.2c17438b.chunk.js -H 'Accept-Encoding: gzip, deflate, br'
```

I'll dig and look what's causing this.

**Comment by chrwahl** [comment]
> Could you test `curl`

Yes, `curl https://developer.mozilla.org/static/js/22.2c17438b.chunk.js -H 'Accept-Encoding: gzip, deflate, br' -I` (I added `-I` for printing headers) response is fine.

But if I look in Firefox I can also find `Accept-Encoding: gzip, deflate, br`, so what is the difference?

**Comment by fiji-flo** [comment]
So I looks like this was an old cached file. Could you verify that (after potentially doing a hard refresh) the original MDN page now works?
I invalidated the files in our CDN.

https://developer.mozilla.org/static/js/22.2c17438b.chunk.js

should in fact not exist.

**Comment by chrwahl** [comment]
> So I looks like this was an old cached file. Could you verify that (after potentially doing a hard refresh) the original MDN page now works?

Yes, it works now. After refreshing the request changed to a new URL.

**Comment by schalkneethling** [comment]
@fiji-flo Works for me, thanks!

**Comment by lucianocavallo** [comment]
It works now! Thanks!
PD: sorry I've found the messages just today 'cause had some problems with my email.
