### ISSUE TITLE
Issue with "Express Tutorial Part 3: Using a Database (with Mo…": (short summary here please)

### ISSUE THREAD

**Issue by Borovnica1** [mdn/content#11078]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

#### What information was incorrect, unhelpful, or incomplete?

In Author Model code section there is one parentheses more than it should!

.......

// Virtual for author's lifespan
AuthorSchema.virtual('lifespan').get(function() {
  var lifetime_string = '';
  if (this.date_of_birth) {

====================================

    lifetime_string = this.date_of_birth.getYear()).toString();

=====================

Should be:
    lifetime_string = this.date_of_birth.getYear().toString();

=========================

  }
  lifetime_string += ' - ';
  if (this.date_of_death) {
    lifetime_string += this.date_of_death.getYear()
  }
  return lifetime_string;
});

.....

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/a33dfeacb70b75ba2508736d61eced530c325343
* Document last modified: 2021-12-06T03:55:23.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this — I’ve opened #11084 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
