### ISSUE TITLE
Issue with "HTMLCanvasElement.toBlob()": callback argument can be `null`

### ISSUE THREAD

**Issue by thw0rted** [mdn/content#11086]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

#### What information was incorrect, unhelpful, or incomplete?

The signature of the callback method is never explicitly described, and all examples on the page use the callback argument without checking whether it's `null`.  For example, passing `null` to `URL.createObjectURL` is illegal.

#### Specific section or headline?

"Parameters" section, and Examples

#### What did you expect to see?

Per [the relevant standard](https://html.spec.whatwg.org/multipage/canvas.html#dom-canvas-toblob-dev), `result` can be `null` if serialization of the canvas bitmap fails.  This should be made explicit in the documentation.

#### Did you test this? If so, how?

No, I don't know how to reproduce an encoder error and force a `null` return, it's just *possible* per the spec.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlcanvaselement/toblob`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlcanvaselement/toblob/index.md
* Last commit: https://github.com/mdn/content/commit/a484593c022279d74a8434379d791f461f13ad9d
* Document last modified: 2021-12-08T02:53:13.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for reporting. I will deal with this as I need to update the document anyway. Note I expect to simply update the callback to indicate that null may be reported; I don't plan to update the examples.

**Comment by hamishwillee** [comment]
This was fixed in #11105

The specific fix to this bit was a note in the callback parameter
![image](https://user-images.githubusercontent.com/5368500/146485341-1f144c28-f2de-414f-bcbb-03a331ccf7e4.png)
