### ISSUE TITLE
Issue with ":invalid": Include fieldset

### ISSUE THREAD

**Issue by manngo** [mdn/content#11096]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid

#### What information was incorrect, unhelpful, or incomplete?

As far as I am aware, the `:invalid` pseudoclass is also applicable to `fieldset`s. This makes it possible to manipulate sections of the form without bothering with individual form elements.

I have tested this in all the current browsers.

I would be happy to add this myself. I want to check first whether this is suitable.

#### Did you test this? If so, how?

I have a sample page at https://experiments.internotes.net/staged-form.html . If `fieldset:invalid` is valid, the form should incrementally expand.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_invalid`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_invalid/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by sideshowbarker** [comment]
> I would be happy to add this myself. I want to check first whether this is suitable.

Please go ahead and open a PR for it

**Comment by manngo** [comment]
> > I would be happy to add this myself. I want to check first whether this is suitable.
> 
> Please go ahead and open a PR for it

Thanks for the feedback. I’m still new to doing this, so please let me know what to do next.

I have made some changes, but there are a few gaps as per my comments:

> I don’t know how to include the sample result, nor how to update the compatibility table. According to https://html.spec.whatwg.org/multipage/semantics-other.html#selector-invalid the `fieldset:invalid` is part of the spec. https://caniuse.com/?search=%3Ainvalid doesn’t mention `fieldset` specifically, but does include `form:invalid`; IE is, of course, out, while curent Edge is in (older Edge was out).

As such, I haven’t created the pull request yet. Should I do that now?

The changes are at: https://github.com/mdn/content/compare/main...manngo:patch-1

**Comment by estelle** [comment]
Not sure when fieldset was added, but https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid now shows that it applies. closing as resolved.
