### ISSUE TITLE
Issue with "screenshots": missing "label" member

### ISSUE THREAD

**Issue by nstringham** [mdn/content#11100]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots

#### What information was incorrect, unhelpful, or incomplete?

This page should include information about the `label` member.

https://w3c.github.io/manifest-app-info/#label-member

#### Specific section or headline?

Examples

#### What did you expect to see?

an example with the `label` member specified

#### Did you test this? If so, how?

No?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/manifest/screenshots`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/manifest/screenshots/index.md
* Last commit: https://github.com/mdn/content/commit/4c03c6709411f09bd0350b1f5d4bdcbf0525ef3d
* Document last modified: 2021-10-11T10:39:03.000Z

</details>

**Comment by raouldevil** [comment]
I would like to make a first contribution to the content repo, may I take on this issue?

**Comment by AnilSeervi** [comment]
There's also the `platform` member - https://w3c.github.io/manifest-app-info/#platform-member
