### ISSUE TITLE
Issue with "HTMLTableSectionElement": deleteRow() and insertRow() are not inherited

### ISSUE THREAD

**Issue by asukakenji** [mdn/content#11113]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableSectionElement

#### What information was incorrect, unhelpful, or incomplete?

The methods `deleteRow` and `insertRow` are not inherited from `HTMLElement`. In fact, they are not inherited from anywhere.

#### Specific section or headline?

[Methods](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableSectionElement#methods)

#### What did you expect to see?

The sentence "Inherits methods from its parent, HTMLElement." is removed and the links point to the actual documentation rather than disabled.

#### Did you test this? If so, how?

Open Firefox JavaScript Console:

```js
HTMLTableElement.prototype.insertRow         // function insertRow()
HTMLTableSectionElement.prototype.insertRow  // function insertRow()
HTMLElement.prototype.insertRow              // undefined
HTMLTableElement.prototype.insertRow === HTMLTableSectionElement.prototype.insertRow  // false
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmltablesectionelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableSectionElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmltablesectionelement/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
That *"Inherits methods from its parent, [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement)"* sentence is not stating that `deleteRow()` and `insertRow()` are inherited from `HTMLElement` — instead that sentence is saying, “There are other methods this interface inherits from [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) — and you can follow that link if you want to see those — but the methods listed below are not inherited.

All of the MDN articles for HTML elements use that same language and pattern/structure.
