### ISSUE TITLE
Issue with "TextMetrics": (short summary here please)

### ISSUE THREAD

**Issue by susbox** [mdn/content#11116]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics

#### What information was incorrect, unhelpful, or incomplete?
Actually this paragraph does not make sense to me. To get the width of the bounding box, the left value should be subtracted from the right one. Calculating a sum does not give anything valuable. 
Even then, if we fix this to the proposed method of width calculation, the width of the actualBoundingBox is wider than the width of the inline box, which contradicts the statement below: _the width of the inline box is wider that the width of actualBoundingBox_

```
When measuring the x-direction of a piece of text, **the sum** of actualBoundingBoxLeft and actualBoundingBoxRight can be wider than the width of the inline box (width), due to slanted/italic fonts where characters overhang their advance width.

It can therefore be useful to use the **sum** of actualBoundingBoxLeft and actualBoundingBoxRight as a more accurate way to get the absolute text width:

const canvas = document.getElementById('canvas');
const ctx = canvas.getContext('2d');
const text = 'Abcdefghijklmnop';
ctx.font = 'italic 50px serif';
const textMetrics = ctx.measureText(text);

**console.log(textMetrics.width);
// 459.8833312988281

console.log(Math.abs(textMetrics.actualBoundingBoxLeft) +
            Math.abs(textMetrics.actualBoundingBoxRight));
// 462.8833333333333**
```

#### What did you expect to see?
When measuring the x-direction of a piece of text, the **difference** between actualBoundingBoxRight and actualBoundingBoxLeft can be wider than the width of the inline box (width), due to slanted/italic fonts where characters overhang their advance width.

It can therefore be useful to use the difference between actualBoundingBoxRight and actualBoundingBoxLeft as a more accurate way to get the absolute text width:

const canvas = document.getElementById('canvas');
const ctx = canvas.getContext('2d');
const text = 'Abcdefghijklmnop';
ctx.font = 'italic 50px serif';
const textMetrics = ctx.measureText(text);

**console.log(textMetrics.width);
**// 363.7939453125**

console.log(**Math.abs(textMetrics.actualBoundingBoxRight) -
            Math.abs(textMetrics.actualBoundingBoxLeft**));
**// 359.7939453125****

#### Did you test this? If so, how?
I wrote the proposed code above and found that for this example the width of the inline box is wider than the width of actualBoundingBox. Either this particular example is wrong, or the statement is false.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/textmetrics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/textmetrics/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by vlwkaos** [comment]
Few things to clarify here,

The paragraph says:

> the sum of actualBoundingBoxLeft and actualBoundingBoxRight **can be wider than the width of the inline box** (width), due to slanted/italic fonts where characters overhang their advance width.

Not the other way around as you say.

So, what the sample code demonstrates actually agrees with the statement.

It also agrees with what you mentioned:

> Even then, if we fix this to the proposed method of width calculation, the width of the actualBoundingBox is wider than the width of the inline box, ...

And no where does the paragraph says

> the width of the inline box is wider that the width of actualBoundingBox

---

Now, to actually confirm the if the paragraph is correct or not:

https://codesandbox.io/s/html5-canvas-forked-ym0tk?file=/src/index.js

I found that this is the case: ActualBoundingBox is **not always wider** than the width of the inline box. But it **can be wider**.

and I assume that this result confused you.

However, after testing further, **the sum of actualBoundingBoxLeft and actualBoundingBoxRight** is valuable, since it is more accurate representation of the actual text width.


If the wordings of the below sentence from the section confuses people, it can be changed.

>  the sum of actualBoundingBoxLeft and actualBoundingBoxRight **can be wider than the width of the inline box** (width), due to slanted/italic fonts where characters overhang their advance width.

**Comment by susbox** [comment]
![image](https://user-images.githubusercontent.com/49647676/145994964-057c99ef-38fb-4b67-b845-40a504b09a41.png)

Above is a demonstration of how the bounding box is classically understood.

To get a width of such a box, the left X coordinate should be distracted from the right one, i.e.: **actualBoundingBoxRight - actualBoundingBoxLeft**

Either the idea of the **actualBoundingBox** is different, or summing the X coordinates (**actualBoundingBoxLeft + actualBoundingBoxRight**) to get a width of the box doesn't make sense.

**Comment by vlwkaos** [comment]
@susbox Can I havs a source or a reference to teach myself for "Above is a demonstration of how the bounding box is classically understood" since I am not an expert in this area?

**Comment by vlwkaos** [comment]
@susbox 

This is part of the code where it measures the width:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/44766242/146470779-71b5ac50-2108-4630-91e5-129d76960911.png">

The comment says: 

> // Note that actualBoundingBoxLeft measures the distance in the leftward
    // direction, so its sign is reversed from our usual physical coordinates.

Which I think correctly demonstrates the image you showed me. So it has to be the sum in this case. (which is a difference due to reversed sign of actualBoundingBoxLeft)

Correct me if I am wrong.

**Comment by susbox** [comment]
Thank you for the code. With it I can confirm that the this has to be sum.

I think the name for the group of these variables (aka actualBoundingBox) is confusing, because of the leftward direction for one specific variable within it (actualBoundingBoxLeft). It's worth mentioning about this specific in the description, which does not reflect that at the moment:

![image](https://user-images.githubusercontent.com/49647676/146538476-deff52be-6ead-4b70-b42c-2101f6f2776c.png)

**Comment by vlwkaos** [comment]
@susbox 

Yes, I agree with you. I'll try and come up with a change.

**Comment by susbox** [comment]
Thank you. Appreciate your assistance.
