### ISSUE TITLE
Issue with "HTMLElement: input event": InputEvent is actually not always used

### ISSUE THREAD

**Issue by saschanaz** [mdn/content#11120]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

#### What information was incorrect, unhelpful, or incomplete?

"Interface: InputEvent" part

#### Specific section or headline?

... in the event info table.

#### What did you expect to see?

It's more like "Event" _OR_ "InputEvent".

#### Did you test this? If so, how?

`data:text/html,<input type=range oninput="console.log(event.constructor.name)"><input type=text oninput="console.log(event.constructor.name)">`

On `input[type=range]` the event uses `Event` and on `input[type=text]` it uses `InputEvent`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlelement/input_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/input_event/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by rohitb4** [comment]
@sideshowbarker can I work on this issue?

**Comment by sideshowbarker** [comment]
@rohitb4 Yep — now assigned to you
