### ISSUE TITLE
Content suggestion: HTML inert attribute

### ISSUE THREAD

**Issue by estelle** [mdn/content#11128]
## What is the new suggestion?
add a page for the inert attribute in the HTML section (currently only in the API Element section)

## Why is it important or useful?
[https://css-tricks.com/focus-management-and-inert/#enter-inert]

How many pages are likely to be needed?
1
How much time do you think this work should take:
a few hours

## Other supporting information
[https://whatpr.org/html/4288/interaction.html#the-inert-attribute]
[https://caniuse.com/mdn-api_htmlelement_inert]
[https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert]
[https://developer.mozilla.org/en-US/docs/Web/HTML]

**Comment by Malvoz** [comment]
Fixed in https://github.com/mdn/content/pull/19090.
