### ISSUE TITLE
Issue with "URL": Missing details on handling Matrix URIs

### ISSUE THREAD

**Issue by SetTrend** [mdn/content#11124]
The [Angular](https://angular.io/guide/router-tutorial-toh#heroes-list-optionally-selecting-a-hero) JavaScript framework is heavily using [Matrix URIs](https://www.w3.org/DesignIssues/MatrixURIs.html).

I'm missing information in the below mentioned MDN page on how the Matrix part of URIs is handled. Is it just part of the [`pathname`](https://developer.mozilla.org/en-US/docs/Web/API/URL/pathname) property, without any distinction?

I guess it is. Yet, just for clarification, I would suggest to have a note in the below mentioned MDN documentation page, explicitly mentioning that fact.

MDN URL: [`https://developer.mozilla.org/en-US/docs/Web/API/URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL)

### What information was incorrect, unhelpful, or incomplete?

Information on handling Matrix URIs is missing.

### What did you expect to see?

I would expect to see a note on how Matrix URIs are handled, just for clarification.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/url`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/url/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z
</details>

**Comment by Andrew-Cottrell** [comment]
Use of semi-colon for this purpose appears to be non-standard, or at least is not mentioned in the [URL Standard](https://url.spec.whatwg.org/) or in RFC.


```javascript
var normal = new URL("localhost:4200/heroes?id=15&foo=foo");
console.log(normal.pathname); // "4200/heroes"
console.log(normal.search); // "?id=15&foo=foo"

var matrix = new URL("localhost:4200/heroes;id=15;foo=foo");
console.log(matrix.pathname); // "4200/heroes;id=15;foo=foo"
console.log(matrix.search); // ""
```

However, a script or server can choose to interpret a URL component anyway it chooses.

**Comment by SetTrend** [comment]
Great enhancement suggestion. Loving it!
