### ISSUE TITLE
Issue with "Fundamental text and font styling": (short summary here please)

### ISSUE THREAD

**Issue by tolgatorun** [mdn/content#11126]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals

#### Specific section or headline?
Active learning part is broken 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/styling_text/fundamentals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/styling_text/fundamentals/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by cw118** [comment]
Hello, could you please specify which part of this page is broken? I was not able to reproduce any errors on my end.

**Comment by tolgatorun** [comment]
When i saw javascript code i thought it is broken and show javascript code instead of interactive part but thats not the thing.
