### ISSUE TITLE
Issue with "justify-items": states 'right' behaves the same as 'start' this should read 'end'

### ISSUE THREAD

**Issue by essexgit** [mdn/content#11138]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-items

#### Specific section or headline?
left
The items are packed flush to each other toward the left edge of the alignment container. If the property's axis is not parallel with the inline axis, this value behaves like start.

right
The items are packed flush to each other toward the right edge of the alignment container in the appropriate axis. If the property's axis is not parallel with the inline axis, this value behaves like **_start_**.

#### What did you expect to see?
left
The items are packed flush to each other toward the left edge of the alignment container. If the property's axis is not parallel with the inline axis, this value behaves like start.

right
The items are packed flush to each other toward the right edge of the alignment container in the appropriate axis. If the property's axis is not parallel with the inline axis, this value behaves like **_end_**.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/justify-items`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-items
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/justify-items/index.md
* Last commit: https://github.com/mdn/content/commit/9b6feffb4828a7e318cd4a22041d887f430bedf5
* Document last modified: 2021-10-29T00:37:17.000Z

</details>

**Comment by vlwkaos** [comment]
@essexgit 

below is copied over from #11205 

---

Is this actually a typo? Did you test the case as per w3c css box alignment level3 document?

    Currently, the only case where the property’s axis is not parallel with either left↔right axis is in a column flexbox.

That means the typo is also in the draft.

**Comment by vlwkaos** [comment]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/44766242/157005479-f92604fb-f94a-456e-b71f-7dcc7c04c2da.png">

As I mentioned in #11205 the [w3c CSS level3](https://www.w3.org/TR/css-align-3/#positional-values) states the information as-is. 
Was the change a necessary one? @LuisCadillo @wbamberg 

Is it a typo in a working draft?

**Comment by essexgit** [comment]
I've just looked at MDN at "behaves as **start**" on 'right' has been changed to "behaves as **end**" [https://developer.mozilla.org/en-US/docs/Web/CSS/justify-items](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-items)

**Comment by wbamberg** [comment]
Yes, thank you @vlwkaos , it looks like you (and the spec) are right. I filed https://github.com/mdn/content/pull/13622 to undo the change.
