### ISSUE TITLE
Issue with "Window.print()": script keeps running after this line

### ISSUE THREAD

**Issue by beyzad-asa** [mdn/content#11133]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/print

#### What information was incorrect, unhelpful, or incomplete?

> In most browsers, this method will block while the print dialog is open. However in more recent versions of Safari, it may return immediately.

#### Specific section or headline?

> In most browsers, this method will block while the print dialog is open. However in more recent versions of Safari, it may return immediately.

#### What did you expect to see?
Well as mentioned, i expect the browser waits till the dialog is open. But it will now and immedialty runs next script line (window.location in my case)

#### Did you test this? If so, how?
Yes. wrote a 4 line javascript file.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/print`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/print
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/print/index.md
* Last commit: https://github.com/mdn/content/commit/a2a45a0aec877e97ec64d9ddcd5ea9c95daef0d3
* Document last modified: 2021-11-19T00:06:12.000Z

</details>

**Comment by wbamberg** [comment]
What browser are you running? On Firefox, Safari, and Chrome, if I paste this into the console:

```js
window.print();
console.log('hi');
```

...then I don't see the console statement appearing until the print dialog has been dismissed.

**Comment by beyzad-asa** [comment]
> What browser are you running? On Firefox, Safari, and Chrome, if I paste this into the console:
> 
> ```js
> window.print();
> console.log('hi');
> ```
> 
> ...then I don't see the console statement appearing until the print dialog has been dismissed.

Weired....
Looks like running script in console itself is fine. but if you run script using files, its not ok.

Proof:
https://pasteboard.co/kXV6mDZarlIE.png

file content:
`test
<script>
	window.print();
	console.log('hi');
</script>`

**Comment by wbamberg** [comment]
I think what happens here is that if the document is still loading when `print()` is called, then the browser queues a task to open the print dialog until it has finished loading. Once the print dialog has opened, the page is blocked.

This is from the [spec](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-print):

> 4. If document is ready for post-load tasks, then run the printing steps for document.
>
> 5. Otherwise, set document's print when loaded flag.

Thanks @Elchi3  for pointing this out to me.

**Comment by beyzad-asa** [comment]
> If you think you found an issue with Firefox 95 specifically, you can try to file a bug here: https://bugzilla.mozilla.org/home

Well, as it happens in latest chrome version too, i really have no idea what it related to.
May be i am wrong and my script is not standard. dont know.

Can you guys please do me a favor and suggest a code to achive my scenario please?

**Comment by Elchi3** [comment]
I'm sorry, I guess it could be many things. More recent browsers are also including more security-related restrictions, like sandboxing, CSP, tracking protection, HTTPS only, and many more. Maybe that's interfering here, maybe not. 
This issue is about MDN documentation and I believe we clarified the docs to better describe the behavior of window.print. I would advise you to try asking about your specific scenario in forums like stackoverflow.

**Comment by beyzad-asa** [comment]
Its ok. thanks for your help.
I will update this thread with future info for others who reached here by searching.

Many thanks to you, sideshowbarker and wbamberg
Regards.
