### ISSUE TITLE
Issue with "Inheritance and the prototype chain": …

### ISSUE THREAD

**Issue by wlnirvana** [mdn/content#1114]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain

#### What information was incorrect, unhelpful, or incomplete?

```
var d = Object.create(null);
// d ---> null
```

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain#with_object.create

#### What did you expect to see?

It's worth mentioning that in some browser implementations, one cannot get d's prototype null by `d.__proto__`, but has to use the ECMAScript 2015 syntax `Object.getPrototypeOf(d)`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/inheritance_and_the_prototype_chain`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/inheritance_and_the_prototype_chain/index.html
* Report started: 2021-01-09T02:34:38.703Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I’ve raised https://github.com/mdn/content/pull/1145 with some changes.

Note that the article already says this:

> Since ECMAScript 2015, the <code>[[Prototype]]</code> is accessed using the accessors <a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf"><code>Object.getPrototypeOf()</code></a> and <a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf"><code>Object.setPrototypeOf()</code></a>. This is equivalent to the JavaScript property <code>\_\_proto\_\_</code> which is non-standard but de-facto implemented by many browsers.

However, there were a couple examples in the code which used `foo.__proto___` — so I replaced those.
