### ISSUE TITLE
Issue with ":autofill": colors with transparency do not work

### ISSUE THREAD

**Issue by rowild** [mdn/content#11148]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill

#### What information was incorrect, unhelpful, or incomplete?
It seems that the color values used MUST NOT include transparency. A color value like "rgb(200,250,100)" works fine, while a color value "rgba(200,250,100,0.5)" does NOT work and falls back to the browser's default.  

#### Did you test this? If so, how?
I tested this locally. I wanted to prepare a codepen / codesandbox, but it seems that tose platforms do not support "input field memory" - meaning I do not get any values that I entered earlier, which make it impossible to text "autofill".

However, here is a sandbox, if you want to quickly copy and paste something to your local environment:
https://codesandbox.io/s/brave-minsky-o1h57?file=/index.html

And here is a github repo:
https://github.com/rowild/autofill-with-transparency-example/blob/main/README.md

I also opened a discussion on the Chromium forums:
https://groups.google.com/a/chromium.org/g/chromium-discuss/search?q=-webkit-autofill
But at the point of writing this issue, the discussion was not yet published.

If this is something that can be verified by more developers, I would consider this "important information" and therefore ask to implement it in the docus. (I, of course, would be happy to provide a PR, but I would kindly ask some of you, who read this, to test and verify/falsify. Thank you!)

UPDATE:

I must clarify my issue by adding that I am actually referring to the `background-color` attribute. As it seems it cannot be changed at all, which is, why in the given examples there `box-shadow` classes (to fake background color). However, for whatever idiotic reason I did not include `background-color` attributes - sorry for being so unclear and thanks to @wbamberg for bringing that to my attention!

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_autofill`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_autofill/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by wbamberg** [comment]
I might be misunderstanding this, but it seems to work for me. https://codepen.io/willbamberg/pen/jOGeGLE is a CodePen based on the one at https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/. 

In Chrome I have added an autofill address in "Autofill"/"Addresses and more". When I load that CodePen page and click in the "Email address" box, I see an autofill suggestion, and when I hover over it I get the autofilled values with the expected style, including transparency.

**Comment by wbamberg** [comment]
Like this:

![autofill](https://user-images.githubusercontent.com/432915/148883776-0f99adf9-5c4b-4c08-b41d-aad47f620bbd.gif)

**Comment by rowild** [comment]
@wbamberg Thank you very much for your feedback and your examples! Great to see that auto-fill can be done, and I wonder, why I didn't get it to work!

However, I indeed was very unclear in my formulation, because the problem I intended to address does not concern the text color, but the background color. I do not mention that with any word - how stupid of me!

I took the liberty of copying our CodePen and added background color definitions:
https://codepen.io/rowild/pen/MWEPGmL

And I will now update my issue to make it more clear.

Maybe you have a moment and could leave a comment with your observations? Maybe fix my error? :-)

**Comment by wbamberg** [comment]
> the problem I intended to address does not concern the text color, but the background color

Is this covered by the the note at the top of the [`:autofill`](https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill) page?

> The user agent style sheets of many browsers use !important in their :-webkit-autofill style declarations, making them non-overrideable by webpages without resorting to JavaScript hacks. For example Chrome has the following in its internal stylesheet:
>
> background-color: rgb(232, 240, 254) !important;
> background-image: none !important;
> color: -internal-light-dark(black, white) !important;
>
> This means that you cannot set the background-color, background-image, or color in your own rules.

**Comment by rowild** [comment]
Oh God - send brain, eye-sight and the ability to understand what I read!

Unbelievable! How could I not have seen that? I swear I've read the page more than once!
Thank you very much, @wbamberg , for educating me!

Ashamed I will close this issue and further on see all input fields' backgrounds as red as I am now!

**Comment by wbamberg** [comment]
No worries @rowild ! I had to educate myself about this feature as well :).
