### ISSUE TITLE
Content bug: Result incorrect in the example for microtask

### ISSUE THREAD

**Issue by SidneyTTW** [mdn/content#11173]
## What page(s) did you find the problem on?
https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide

## Specific page section or heading?
https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide#microtask_from_a_function

## What is the problem?
The example in this section is supposed to log `Regular timeout callback has run` only once, but in the `Result` section, it occurs twice.
![image](https://user-images.githubusercontent.com/906877/145757838-7826cb24-49f9-4be0-b8e7-e6116d9f98bd.png)

## What did you expect to see?
The `Regular timeout callback has run` should be logged only once, after the `*** Oh noes! An urgent callback has run!`

## Did you test this? If so, how?
Yes, I tried the console in Chrome with the sample code (the `undefined` in the screenshot is find, it's just the result of the adhoc statement):
![image](https://user-images.githubusercontent.com/906877/145758068-61ca2704-9b28-4ce3-99d8-4249a9c95c3f.png)

**Comment by AnilSeervi** [comment]
it's logging twice due to the last log statement, which strangely isn't visible on you Screenshot of the example.

Even the source-code has that line in its example:
https://github.com/mdn/content/blob/3b6ca8e44e5f874d169bfbc1e0afda1a92c5e9ca/files/en-us/web/api/html_dom_api/microtask_guide/index.md?plain=1#L288

![image](https://user-images.githubusercontent.com/61609033/145921472-54cf26cd-6541-4a92-8261-e0ab749e6fe3.png)

**Comment by sideshowbarker** [comment]
@AnilSeervi Are you saying that this is resolved?

**Comment by SidneyTTW** [comment]
@AnilSeervi , I think the last log statement has just been added yesterday: https://github.com/mdn/content/pull/11149
It seems a little bit weird to update the script to have some duplicated log, instead of updating the result part.
Anyway, at least the result matches the script.

Thanks for replying. And thanks @joneslloyd for the PR

**Comment by sideshowbarker** [comment]
OK, closing this per https://github.com/mdn/content/issues/11173#issuecomment-993201256
