### ISSUE TITLE
Issue with "Number.prototype.toLocaleString()": needs description of all the options

### ISSUE THREAD

**Issue by MarioDings** [mdn/content#11174]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

#### What information was incorrect, unhelpful, or **incomplete**?
Options: 

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#using_options

#### What did you expect to see?
There's no description of all the options. I found a list in German language, but I don't know if that's the correct list.

#### Did you test this? If so, how?
no.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/number/tolocalestring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/number/tolocalestring/index.md
* Last commit: https://github.com/mdn/content/commit/0347d27d3ba30907174acfd3a49976a7ac19ca2b
* Document last modified: 2021-09-17T15:25:55.000Z

</details>

**Comment by hamishwillee** [comment]
The page says under [pararameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#parameters), where the options would normally be documented, that they are documented in the constructor.
![image](https://user-images.githubusercontent.com/5368500/145906751-63a1566c-6652-47c1-b500-348ec21870b2.png)

@wbamberg Do you think it is worth duplicating the content (not the effort to copy, but the potential ongoing maintenance). This kind of "see here" string is definitely not as good as including the content, and  to a user they appear to be different APIs.

**Comment by MarioDings** [comment]
Thank you for your reply

 I didn't see that. Maybe a second reference/hyperlink to the parameters
options. I didn know there were so many.


Op di 14 dec. 2021 00:47 schreef Hamish Willee ***@***.***>:

**Comment by wbamberg** [comment]
> @wbamberg Do you think it is worth duplicating the content (not the effort to copy, but the potential ongoing maintenance). This kind of "see here" string is definitely not as good as including the content, and to a user they appear to be different APIs.

Yeah, maybe in this case it is. At least we'd only be duplicating it once!

**Comment by SaurabhCha** [comment]
Hi, Can I work on this issue! Thanks

**Comment by sideshowbarker** [comment]
> Hi, Can I work on this issue! Thanks

@SaurabhCha Yup — assigned to you now

**Comment by SaurabhCha** [comment]
Hi, Thank you for assigning this to me. I checked for options and found similar options for NumberFormat(). 
Please have a look: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat
I can check for all options and prepare the same for toLocaleString()
Please confirm this.

**Comment by SaurabhCha** [comment]
Hi @sideshowbarker , Can you please review the above comment and let me know if I am taking the right approach. Thanks

**Comment by sideshowbarker** [comment]
> Hi @sideshowbarker , Can you please review the above comment and let me know if I am taking the right approach. Thanks

Please go ahead and create a PR

**Comment by SaurabhCha** [comment]
@sideshowbarker I have created a PR.
PR: https://github.com/mdn/content/pull/16295
Please let me know if anything else is required.
