### ISSUE TITLE
Issue with "Element.insertAdjacentText()": (confusing description of the text nature)

### ISSUE THREAD

**Issue by jackdeguest** [mdn/content#11188]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentText

#### What information was incorrect, unhelpful, or incomplete?
In the short introduction, it is written that this "inserts a given text node", suggesting this is already a node object. However, a bit later on the same page, it is written to describe the text as being a "DOMString representing the text to be inserted into the tree".

So it this a node object, or a text string? Which is it?

#### What did you expect to see?
Consistency in the words chosen to describe the arguments passed.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/insertadjacenttext`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentText
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/insertadjacenttext/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve opened #11192 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
