### ISSUE TITLE
Issue with "Element.insertAdjacentHTML()": (missing some information about exceptions and return value)

### ISSUE THREAD

**Issue by jackdeguest** [mdn/content#11187]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML

#### What information was incorrect, unhelpful, or incomplete?
Contrary to [insertAdjacentElement](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentElement), you do not make any mention about the types of exception thrown, i.e. `SyntaxError` or `TypeError`

Also, you do not mention the value returned. Does it return a list of nodes thus parsed and inserted or merely a boolean value?

#### What did you expect to see?
I expected to see a slightly more complete information.

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/insertadjacenthtml`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/insertadjacenthtml/index.md
* Last commit: https://github.com/mdn/content/commit/c3ca3cce60e089115b7223c5400c847e7502c529
* Document last modified: 2021-12-08T14:32:25.000Z

</details>

**Comment by tratul** [comment]
Hello I can update the answer would you assign me the task.
