### ISSUE TITLE
Issue with "Document and website structure": …

### ISSUE THREAD

**Issue by Ouss84** [mdn/content#1120]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure

#### What information was incorrect, unhelpful, or incomplete?
Typo error:
1 in every 12 men

#### Specific section or headline?
located in the first Note:1st note

#### What did you expect to see?
1 in every 120 men

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/document_and_website_structure`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/html/introduction_to_html/document_and_website_structure/index.html
* Report started: 2021-01-09T11:11:08.234Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. So the https://www.color-blindness.com/2006/04/28/colorblind-population/ article that’s cited says:

> Roughly 8% of men and 0.5% of women are affected

8% ≅ 1/12 — not 1/120 — so it seems like the *1 in every 12 men* statement is accurate, right?

I’ve anyway opened https://github.com/mdn/content/pull/1122 with a change which copies that *Roughly 8% of men and 0.5% of women* language into the MDN article — to make it more explicit where the data for that *“approximately 1 in every 12 men and 1 in every 200 women”* statement came from.

**Comment by Ouss84** [comment]
Thank you for your precise information, I am sorry if I got the misunderstanding!
