### ISSUE TITLE
Issue with "Django Tutorial Part 9: Working with forms": Multiple sets of misplaced asterisks

### ISSUE THREAD

**Issue by PythonCoderAS** [mdn/content#11203]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms

#### What information was incorrect, unhelpful, or incomplete?

Multiple blocks of text such as `*model_name***_form.html**` exist scattered across the page

#### Specific section or headline?

N/A

#### What did you expect to see?

Blocks of text such as `model_name_form.html`

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/forms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/forms/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by sideshowbarker** [comment]
@cw118 Can you please post a comment here to confirm you’ll be working on this?

**Comment by cw118** [comment]
Hello, I'm working on this issue.

**Comment by hamishwillee** [comment]
Just FYI, these are supposed to render like _model_name_**\_form.html** - unfortunate conversion.

**Comment by cw118** [comment]
> Just FYI, these are supposed to render like _model_name_**_form.html** - unfortunate conversion.

Thank you for letting me know! I'll keep that in mind
