### ISSUE TITLE
Issue with "Process for running short surveys": (short summary here please)

### ISSUE THREAD

**Issue by nosyajmagS020796** [mdn/content#11217]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Processes/Short_surveys

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/processes/short_surveys`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Processes/Short_surveys
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/processes/short_surveys/index.md
* Last commit: https://github.com/mdn/content/commit/32f6335487194aa8c3a9fb5c90eeba5e95be6224
* Document last modified: 2021-10-15T15:32:38.000Z

</details>

**Comment by hamishwillee** [comment]
Closing, as template information not provided. Feel free to create a new issue and provide specific information about your problem.
