### ISSUE TITLE
Content bug: /docs/Mozilla/Add-ons/Themes 404's

### ISSUE THREAD

**Issue by amychurchwell** [mdn/content#11214]
## What page(s) did you find the problem on?
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons

## Specific page section or heading?

Sidebar section underneath "Related Topics"

## What is the problem?

The link [Themes](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Themes) 404's

## What did you expect to see?

Documentation about theme development.

**Comment by PythonCoderAS** [comment]
This link works for me.

**Comment by himanshugarg** [comment]
The link redirects now even though the link itself is awaiting an update via https://github.com/mdn/yari/pull/5089. Perhaps we can close this issue?

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/11214#issuecomment-1030735972

**Comment by rebloor** [comment]
@sideshowbarker @himanshugarg as they doesn't seem to be an obvious explanation as to why this is now working, I've reopened pending merging of the menu update.

**Comment by rebloor** [comment]
Themes menu item link to extension workshop [#5089](https://github.com/mdn/yari/pull/5089) has been merged so all changes are complete.
