### ISSUE TITLE
Issue with "What’s in the head? Metadata in HTML": (icon URIs 404)

### ISSUE THREAD

**Issue by alanthssss** [mdn/content#11228]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML

#### What information was incorrect, unhelpful, or incomplete?
There are no img resources as the content says, as well as the icon imgs are 404 now.

#### Specific section or headline?
[Adding custom icons to your site](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#adding_custom_icons_to_your_site)

#### What did you expect to see?
Relocate the right URIs of the img resources.

#### Did you test this? If so, how?

Sure, the URIs are 404

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/the_head_metadata_in_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/the_head_metadata_in_html/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for reporting - but I am going to close because there are no missing images displaying in this section and when I reload the page I can see that all resources it links are returning HTTP 200 code. 

Possibly there was a temporary problem.

**Comment by alanthssss** [comment]
@hamishwillee 
Thanks for your reply.
Maybe my description is not clear enough.
There are no images 404 on this page, while the icon images are 404 in the `custom icos` section: 
```
<!-- third-generation iPad with high-resolution Retina display: -->
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="https://developer.mozilla.org/static/img/favicon144.png">
<!-- iPhone with high-resolution Retina display: -->
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="https://developer.mozilla.org/static/img/favicon114.png">
<!-- first- and second-generation iPad: -->
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="https://developer.mozilla.org/static/img/favicon72.png">
<!-- non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<link rel="apple-touch-icon-precomposed" href="https://developer.mozilla.org/static/img/favicon57.png">
<!-- basic favicon -->
<link rel="icon" href="https://developer.mozilla.org/static/img/favicon32.png">

```

**Comment by hamishwillee** [comment]
Thanks for the clarification. 
So for whoever takes this, in https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#adding_custom_icons_to_your_site there is a section that talks about various favicons on MDN, using pre-github wiki information. The section needs to be updated to point to some "real" favicons.

**Comment by alanthssss** [comment]
> Thanks for the clarification. So for whoever takes this, in https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#adding_custom_icons_to_your_site there is a section that talks about various favicons on MDN, using pre-github wiki information. The section needs to be updated to point to some "real" favicons.


@hamishwillee 
Cool! That's it. 
BTW, this section tell the content well even if here are no "real" favicons.
That will be better with "real" favicons.

Where would the new images with the multiple sizes be put in?
If it is a open source action, I'd like to reshape new images and put it in the right dir/URI.
I am familiar with PhotoShop as well.

**Comment by alanthssss** [comment]
> > Thanks for the clarification. So for whoever takes this, in https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#adding_custom_icons_to_your_site there is a section that talks about various favicons on MDN, using pre-github wiki information. The section needs to be updated to point to some "real" favicons.
> 
> @hamishwillee Cool! That's it. BTW, this section tells the content well even if here are no "real" favicons, as well as it's not very important to have "real" favicons here. But it would be better with "real" favicons, so that newbees for web development would need no more explainations here.
> 
> Where would the new images with the multiple sizes be put in? If it is an open source action, I'd like to resize new favicons and put them in the right dir/URIs. I am familiar with PhotoShop as well.

I would resize some new favicons as require and put them in the [current dir](https://github.com/alanthssss/content/tree/main/files/en-us/learn/html/introduction_to_html/the_head_metadata_in_html),
then replace the new URIs to the content, and there would be  a  PR for it.

**Comment by hamishwillee** [comment]
It would be better to use a real site as an example, if possible. We could for example use the current images on the site:
```
<link rel="icon" href="/favicon-48x48.97046865.png">
<link rel="apple-touch-icon" href="/apple-touch-icon.0ea0fa02.png">
```

Now this is not as complete as the old set, but we can perhaps make minor changes to the docs so that the old set are displayed as a more thorough example of what you might do in theory for retina screens etc. I.e. the point is to show a real case and an ideal case. Hope that makes sense.
