### ISSUE TITLE
Issue with "Element.toggleAttribute()": (confusing definition of 'force' parameter)

### ISSUE THREAD

**Issue by jackdeguest** [mdn/content#11224]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute

#### What information was incorrect, unhelpful, or incomplete?
In the description of the optional 'force' parameter, the documentation states that 'force' is a "boolean value to determine whether the attribute should be added or removed, no matter whether the attribute is present or not at the moment."

Maybe it is just me, but I think this is confusing and at the very least does not help explain what goes on.

#### What did you expect to see?
I would rather recommend something along the line of:
"A boolean value to determine whether the return boolean value should be forced to be true when the attribute already exists and should normally be toggled off, or should be forced to be false when the attribute does not yet exist and should normally be toggled on"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/toggleattribute`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/toggleattribute/index.md
* Last commit: https://github.com/mdn/content/commit/2537c8c37d938ea0e01cd0cf7e74ba63688d9781
* Document last modified: 2021-09-23T14:01:52.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve opened #11231 with a fix
