### ISSUE TITLE
Issue with "Web APIs": Subpage Transferable is a 404

### ISSUE THREAD

**Issue by PythonCoderAS** [mdn/content#11223]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API

#### What information was incorrect, unhelpful, or incomplete?

Link https://developer.mozilla.org/en-US/docs/Web/API/Transferable is on the left sidebar and an HTTP 404.

#### Specific section or headline?

N/A

#### What did you expect to see?

Either the webpage exists or it isn't included in the sidebar

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
> Link [developer.mozilla.org/en-US/docs/Web/API/Transferable](https://developer.mozilla.org/en-US/docs/Web/API/Transferable) is on the left sidebar and an HTTP 404.

For some reason, I don’t see a sidebar on that page… But regardless, I’ve opened #11232 with a fix that will cause to be dropped from anywhere it might appear.
