### ISSUE TITLE
Issue with "@layer": (example does not follow explanation. Text should be purple)

### ISSUE THREAD

**Issue by onnodejong** [mdn/content#11238]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@layer

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/@layer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@layer/index.md
* Last commit: https://github.com/mdn/content/commit/72a0f52e9fe3adc9246c1a040675a20385909f11
* Document last modified: 2021-11-15T22:04:26.000Z

</details>

**Comment by spartanatreyu** [comment]
I think the main issue here is that the result is rendered in-browser, despite browsers not supporting the feature yet.

The example here should probably be split into an image example result and a live-in-browser example result.

**Comment by onnodejong** [comment]
Time will fix it.

**Comment by Rumyra** [comment]
Assign myself - I'l address this in https://github.com/mdn/content/issues/9369

**Comment by Rumyra** [comment]
Thanks for the issue @onnodejong - this has been address in #12185 - along with upcoming additions to the Browser Compatibility section
