### ISSUE TITLE
Issue with "Reason: CORS request not HTTP": (short summary here please)

### ISSUE THREAD

**Issue by kapuza** [mdn/content#11235]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

#### What information was incorrect, unhelpful, or incomplete?
In firefox 95.0 **privacy.file_unique_origin** not working for *file://*
Not workind [MDWiki](http://www.mdwiki.info/) for local files

#### What did you expect to see?
I am update my firefox from 94.0 to 95.0 and have a trouble for my docs

#### Did you test this? If so, how?
Yes
Test now in my computer

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cors/errors/corsrequestnothttp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/errors/corsrequestnothttp/index.md
* Last commit: https://github.com/mdn/content/commit/46234997b6257b619423a11ce31154afa336143f
* Document last modified: 2021-08-13T16:17:49.000Z

</details>

**Comment by sideshowbarker** [comment]
This seems like something that should be reported at https://bugzilla.mozilla.org/

**Comment by Zeratul2k** [comment]
Can confirm on Firefox 97. Similar error on Chrome 98, where the error reads: "Access to XMLHttpRequest at 'file:///C:/<DATA EXPUNGED>/index.md' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https."

**Comment by hamishwillee** [comment]
@Zeratul2k Thanks, but please don't necrobump issues. This is closed - if you look at the page referenced it no longer talks about `privacy.file_unique_origin` (which was removed) and suggests that you need to use a local server.
