### ISSUE TITLE
Issue with "devtools": broken links in sidebar

### ISSUE THREAD

**Issue by jakseb** [mdn/content#1126]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools

#### What information was incorrect, unhelpful, or incomplete?

Links to `devtools.inspectedWindow`, `devtools.network` and `devtools.panels` point to 404 pages.

#### Specific section or headline?

In section [Interfaces](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools#interfaces).

#### What did you expect to see?

Clicking the link labelled `devtools.inspectedWindow` should result in navigating to the documentation of that API, which is located at <https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.inspectedWindow>. The link instead points to <https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/inspectedWindow> (a slash replaces the last dot).

#### Did you test this? If so, how?

By clicking the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/devtools`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/add-ons/webextensions/api/devtools/index.html
* Report started: 2021-01-09T14:13:14.421Z

</details>

**Comment by nschonni** [comment]
I think #598 should fix these

**Comment by jakseb** [comment]
The links I complained about now work. However, the sidebar has stopped displaying links to `devtools.panels` and the other two namespaces and their members.

If I could suggest something, it seems that the sidebar issue would not have been introduced if one had not moved the files and had only added appropriate redirects (from 'all-slash' URLs to ones with a dot).

**Comment by himanshugarg** [comment]
Would the fix here be to show (possibly nested) the members not just for devtools but also for other interfaces on the sidebar such as - alarms, bookmarks, browserAction, and so on?

**Comment by rebloor** [comment]
This issue relate to the way in which the menu side bar is generated by the macros in Yari. As such, it's not something that can be addressed by changes in the content. Created  [Add devtools interfaces to web extension side bar #5158 ](https://github.com/mdn/yari/issues/5158)
