### ISSUE TITLE
Issue with "Learn web development": ambiguous grammar

### ISSUE THREAD

**Issue by vhliyr** [mdn/content#11276]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn

#### What information was incorrect, unhelpful, or incomplete?

CSS is the language that we can use to style and **layout** our web content,

#### What did you expect to see?

CSS is the language that we can use to style and **lay out** our web content,

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
`layout` is the usual term, but it can be jarring when used as a verb. How about switching from verbs to nouns?
> CSS is the language that we can use to control our web content's style and layout, as well as adding behavior like animation.

**Comment by hamishwillee** [comment]
Thanks. The term layout is well understood and used through both MDN and the specifications. I appreciate that sometimes it can be jarring and there are definitely places where using "lay out" would be better. However it is not incorrect, confusing or ambiguous. 

Given that I'm going to close this as "not worth focusing effort on compared to technical content tasks"

@rumya tagging you in case you feel strongly that our time would be well spent on this.

**Comment by Josh-Cena** [comment]
Accepting a PR to change it to a noun.

> CSS is the language that we can use to control our web content's style and layout, as well as adding behavior like animation.

This conforms to the MS style guide, which says do not use nouns as verbs.
