### ISSUE TITLE
Issue with "appearance (-moz-appearance, -webkit-appearance)": (demo doesn't work)

### ISSUE THREAD

**Issue by tdiprima** [mdn/content#11278]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/appearance

#### What information was incorrect, unhelpful, or incomplete?
No matter which code you click on, the example-element div to the right of the code, does not change its appearance.
Particularly: `-webkit-appearance: menulist-button` and `-webkit-appearance: button;` should have some effect, but nothing happens.

#### Specific section or headline?
CSS Demo: appearance

#### What did you expect to see?
Depending on which code you click on, the example-element div to the right of the code, should change its appearance.

#### Did you test this? If so, how?
Using **Firefox version 95.0.1 (64-bit)** on MacBook Pro version 12.0.1 Monterey.
I also tested with **Chrome** v96.0.4664.110.

I clicked each div to the left containing code, and observed: no changes to the div on the right of it.
A warning in the console says: Content Security Policy: Couldn’t process unknown directive ‘script-src-elem’.
In browser settings, security, I have "standard" security.
I have NO browser extensions.

The browser it actually works on is: **Safari v15.1**
`-webkit-appearance: button;` works.
But `-webkit-appearance: menulist-button;` looks weird (see pic below):

<img width="88" alt="Screen Shot 2021-12-17 at 10 06 57 AM" src="https://user-images.githubusercontent.com/4490270/146565266-fb44b948-acd2-4777-97a5-80ba753058ae.png">

Thanks.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/appearance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/appearance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/appearance/index.md
* Last commit: https://github.com/mdn/content/commit/e0463adc4d3e45549265603cacd951db609fbc5e
* Document last modified: 2021-11-03T04:58:23.000Z

</details>

**Comment by AnilSeervi** [comment]
`appearance` has different implementations in different browsers: 

MDN
>Note: If you wish to use this property on websites, you should test it very carefully. Although it is supported in most modern browsers, its implementation varies. In older browsers, even the keyword none does not have the same effect on all form elements across different browsers, and some do not support it at all. The differences are smaller in the newest browsers.

---

After the introduction of **HTML5**, the `appearance` property seems to have lost support.

More about it here: 
https://wiki.csswg.org/spec/css4-ui#dropped-css3-features

**Comment by hamishwillee** [comment]
@rachelandrew Howdy, should this be marked as deprecated? I just tried this on chrome (where it is said to be supported) for a bunch of the UI items and and nothing is rendering specially on chrome or Firefox. I did this using my own small example to avoid the oddity in the CSP loading on firefox.

**Comment by sideshowbarker** [comment]
I think this was fixed by https://github.com/mdn/interactive-examples/pull/2066
