### ISSUE TITLE
Issue with "Date.prototype.setDate()": comment in examples section wrong.

### ISSUE THREAD

**Issue by KeaUehara** [mdn/content#11270]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setDate

#### What information was incorrect, unhelpful, or incomplete?
Date.setDate example comment is incorrect.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setDate#using_setdate
Examples
Using setDate()
Last example setting date to -50.
Comment is: // 1962-08-11 (11th of August 1962)

#### What did you expect to see?
Comment should be: // 1962-05-11 (11th of May 1962)

#### Did you test this? If so, how?
Ran code in Chrome dev tools Version 96.0.4664.110 (Official Build) (x86_64)
const theBigDay = new Date(1962, 6, 7, 12);
theBigDay.setDate(-50);
console.log(theBigDay);

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/setdate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setDate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/setdate/index.md
* Last commit: https://github.com/mdn/content/commit/a1e76705eadb18b3659a7b031a703054cfd0ff60
* Document last modified: 2021-07-23T13:14:13.000Z

</details>

**Comment by vlwkaos** [comment]
@KeaUehara 

The example sets date to 98 `theBigDay.setDate(98)` prior to setting date to 50. The code sample is correct.

**Comment by KeaUehara** [comment]
Ahh, you're supposed to run all of them at the same time. I see. Thanks!
