### ISSUE TITLE
Issue with "Making decisions in your code — conditionals": …

### ISSUE THREAD

**Issue by deekox** [mdn/content#1127]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals

#### What information was incorrect, unhelpful, or incomplete?
The example introduces some concerns.

#### Specific section or headline?
"A note on comparison operators"
example:

`let shoppingDone = false;`

`if (shoppingDone) { // don't need to explicitly specify '=== true'`
`    let childsAllowance = 10;`
`} else {`
`    let childsAllowance = 5;`
`}`

#### What did you expect to see?
`childsAllowance` has no use outside of blocks where it is defined (`var` instead of `let` would do the trick but I think this is still a bad style).

#### Did you test this? If so, how?
Yes. I added following line:

`console.log(childsAllowance);`

this causes an exception: "Uncaught ReferenceError: val is not defined"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/conditionals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/javascript/building_blocks/conditionals/index.html
* Report started: 2021-01-09T14:42:15.560Z

</details>

**Comment by chrisdavidmills** [comment]
Yup, I see your point here @deekox . These code examples were never really meant to be run, but regardless, people will try them, and then possibly get confused about why `childsAllowance` returns `undefined`.

I've made a fix in https://github.com/mdn/content/commit/6f35e2ed9f00cf4f1cbdd03fefe1a2467284913e.

I'll close this now, but feel free to chime in if you have any more comments.
