### ISSUE TITLE
Issue with "Node.nodeName": JS example making assignment to constant

### ISSUE THREAD

**Issue by FongWan** [mdn/content#11288]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeName

#### What information was incorrect, unhelpful, or incomplete?

In the example, the first line of the script is something like this:

~~~javascript
const node = document.getElementsByTagName("body")[0].firstChild;
~~~

But it shouldn't be `const`, it should be `var` since later there is an assignment inside the while loop.

#### Specific section or headline?

Example.

#### What did you expect to see?

~~~javascript
var node = document.getElementsByTagName("body")[0].firstChild;
~~~

#### Did you test this? If so, how?

The Firefox console showed `Uncaught TypeError: invalid assignment to const 'node'` when visiting the page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/node/nodename`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeName
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/node/nodename/index.md
* Last commit: https://github.com/mdn/content/commit/422c1e46f09bb860015396fbecb6ef4c27cb8004
* Document last modified: 2021-11-08T14:59:08.000Z

</details>

**Comment by jackdeguest** [comment]
Also, please correct the HTML, especially the `svg` tag which is not closed properly.

**Comment by AnilSeervi** [comment]
> Also, please correct the HTML, especially the `svg` tag which is not closed properly.

Corrected in https://github.com/mdn/content/pull/11291/commits/6fa2011dbab3f7559fe65d95fbaa79a0406e53e0

**Comment by hamishwillee** [comment]
Thanks @FongWan for posting, and others for your fixes!
