### ISSUE TITLE
Issue with "Django Tutorial Part 2: Creating a skeleton websit…": (short summary here please)

### ISSUE THREAD

**Issue by damohzak** [mdn/content#11292]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website

#### What information was incorrect, unhelpful, or incomplete?
Hooking up the URL mapper to catalog 'urls.py' file.
Following the instructions, it looks like the code snippet is calling a 'catalog.urls' file of some sort which does not exist in the catalog directory.

After adding the code to the urls.py file in the LocalLibray project folder, The server then says 
ModuleNotFoundError: No module named 'catalog.urls'

#### Specific section or headline?
Hooking up the URL mapper

#### What did you expect to see?
I expected it to work, and the catalog page (http://127.0.0.1:8000/catalog/) to load, but it does not

#### Did you test this? If so, how?
unsure how to fix, im learning how to use this, but the tutorial seems incomplete.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/skeleton_website`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/skeleton_website/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by hamishwillee** [comment]
I've run through this catalog from scratch a bunch of times, and I assure you that it is not incomplete :-). 

Most likely you missed the final step where you create the file:
![image](https://user-images.githubusercontent.com/5368500/146712413-0114d86d-7ce8-4851-9371-0bb057e3d50e.png)

**Comment by damohzak** [comment]
Hey,

Thanks for the promot reply,
Makes sense, I'll re read and try again.
Cheers

Kind regards,

Damian
________________________________
