### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [mdn/content#113]
Hello, I understand that it is in Beta format, but I trust the project and I think it would be good to do the translations into Spanish.

I wish I could take the task of creating the "es" folder and converting all the content from English to Spanish.

Could do it?

**Comment by chrisdavidmills** [comment]
Hi there @FranciscoImanolSuarez !

I love your enthusiasm for helping out on the project. However, I'd like to say a couple of things to set some clear expectations:

1. We are currently working on a new process for localization on MDN. The previous way that localization was done on MDN was too difficult to maintain, and not very effective — people could translate anything, in a huge variety of languages, and we ended up with too many out of date translations and junk pages (e.g. someone starts a translation, translates one paragraph of an article, and then gets too busy to finish it). We also don't have the resources to effectively manage large scale translation efforts like this. What we need is a smaller scope, more controlled way of handling translations, which replies on management by the community, and I'm hoping to be able to share some more plans on this soon.

2. There is far too much content on MDN for you to convert all the content from English to Spanish. You'd need a team to work with.

3. There is already a load of Spanish articles on the existing MDN Wiki platform. Some of them might be good enough quality to reuse, but we just don't know. This would require some investigation.

I'd therefore like to ask you to not do anything yet, except to maybe consider the above points. Once we have considered our plans carefully, we'll be able to communicate more, hopefully soon.

Thanks for getting in touch with us.
