### ISSUE TITLE
Issue with "Namespaces in IMSC": (short summary here please)

### ISSUE THREAD

**Issue by musty99** [mdn/content#11303]
MDN URL: https://developer.mozilla.org/en-US/docs/Related/IMSC/Namespaces

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/related/imsc/namespaces`
* MDN URL: https://developer.mozilla.org/en-US/docs/Related/IMSC/Namespaces
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/related/imsc/namespaces/index.md
* Last commit: https://github.com/mdn/content/commit/96be35b407af85246d140511d392e5b6e7379914
* Document last modified: 2021-12-17T15:48:52.000Z

</details>

**Comment by hamishwillee** [comment]
Closing. Not enough information provided in template to understand problem
