### ISSUE TITLE
Issue with "Window: load event": (short summary here please)

### ISSUE THREAD

**Issue by pinter-gabor-at** [mdn/content#11309]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event

#### What information was incorrect, unhelpful, or incomplete?
The page says
`window.addEventListener('load', ...`
and
`window.onload= ...`
are interchangable.

It is not true.
window.onload **replaces** all previously defined event listeners with the current one.
window.addEventListener( **adds a new** listener to the existing ones.

#### Specific section or headline?
Window load event, Examples

#### What did you expect to see?
These two are interchangeble only if there is only one eventlistener.

#### Did you test this? If so, how?
Test 1:

```
window.onload= function() {
  console.log('page is fully loaded 1');
};
window.onload= function() {
  console.log('page is fully loaded 2');
};
```

Result:
Only the second function gets executed.

Test 2:

```
window.addEventListener('load', (event) => {
  console.log('page is fully loaded 1');
});
window.addEventListener('load', (event) => {
  console.log('page is fully loaded 2');
});

```

Result:
Both functions get executed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/load_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/load_event/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by AnilSeervi** [comment]
The problem you've encountered is described here - https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_handler_properties

They are interchangeable in regard to adding a event listener, but `addEventListener` has its own benefits.

**Comment by hamishwillee** [comment]
I'm going to close this because we are currently modifying the way we document events - this will no longer be valid in the updated version.

@Elchi3 For the new-style event docs, it might be worth adding a See also link to https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_handler_properties for all of our event docs.
