### ISSUE TITLE
Issue with "@media": `speech` media type is deprecated

### ISSUE THREAD

**Issue by JakeQZ** [mdn/content#11317]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media

#### What information was incorrect, unhelpful, or incomplete?

`speech` media type appears in main list.  The note below lists the deprecated media types, does not include `speech` in that list, and just implies it was a replacement for `aural`.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/CSS/@media#media_types

#### What did you expect to see?

The main list should only have `all`, `print` and `screen`.  `speech` should be in the deprecated list.

#### Did you test this? If so, how?

Looked at https://drafts.csswg.org/mediaqueries/#media-types

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/@media`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@media/index.md
* Last commit: https://github.com/mdn/content/commit/a5154c6965a0416e13c893414b9e2493ef1ba4aa
* Document last modified: 2021-10-22T03:29:59.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, I think you're right.

What I've done is raised https://github.com/mdn/browser-compat-data/pull/14077 to verify this with the browser compatibility team (just because this is an "editors draft" and not a "final spec"). Once that goes in we can make the corresponding changes in MDN docs.
