### ISSUE TITLE
Sentence structure on German <abbr> page

### ISSUE THREAD

**Issue by evolkmann** [mdn/content#1131]
Page: https://developer.mozilla.org/de/docs/Web/HTML/Element/abbr

In the first paragraph, instead of
> Wenn vorhanden, `title` diese vollständige Beschreibung und nichts anderes enthalten.

it should be

> Wenn vorhanden, sollte `title` diese vollständige Beschreibung und nichts anderes enthalten.

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.

**Comment by evolkmann** [comment]
Thanks for the information, I was not aware of the freeze.
