### ISSUE TITLE
Issue with "SubtleCrypto.digest()": Article doesn't reflect specs and is not really complete

### ISSUE THREAD

**Issue by danieltroger** [mdn/content#11328]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest

#### What information was incorrect, unhelpful, or incomplete?

In the MDN article it says that

> algorithm is a **DOMString** defining the hash function to use. Supported values are: 

#### Specific section or headline?

In the specs: https://www.w3.org/TR/WebCryptoAPI/#dfn-AlgorithmIdentifier it says

```
typedef (object or DOMString) AlgorithmIdentifier;

typedef AlgorithmIdentifier HashAlgorithmIdentifier;

dictionary Algorithm {
  required DOMString name;
};
```

So basically:
> The WebCrypto API says the argument can be either a DOMString or an object { name: DOMString }

Quoted from here: https://github.com/ampproject/amphtml/issues/4354

#### What did you expect to see?

The problem is that the MDN article is incorrect. It says that you can only specify a string, but in the compat data it says "chrome 37", but precisely what the MDN article describes throws in chrome 37-40.

So I expect:
1) The argument being described as in the specification
2) The compat table list which browsers support what option

#### Did you test this? If so, how?

My clients did.

I have this error:
```
TypeError: Failed to execute 'digest' on 'SubtleCrypto': parameter 1 ('algorithm') is not an object.
```

from
1. `Mozilla/5.0 (Linux; Android 7.0; VIE-L09 Build/HUAWEIVIE-L09) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/38.0.0.0 Mobile Safari/537.36`
2. `Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-J320FN Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.5 Chrome/38.0.2125.102 Mobile Safari/537.36`
3. `Mozilla/5.0 (Linux; Android 4.4.4; SM-T561 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.109 Safari/537.36`
4. `Mozilla/5.0 (Linux; Android 5.0.2; SAMSUNG SM-T805 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.0 Chrome/38.0.2125.102 Safari/537.36`
5. `Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-J500FN Build/LMY48B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.3 Chrome/38.0.2125.102 Mobile Safari/537.36`
6. `Mozilla/5.0 (Linux; Android 5.0.2; SAMSUNG SM-T535 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.2 Chrome/38.0.2125.102 Safari/537.36`
7. `Mozilla/5.0 (Linux; Android 5.1; MD501 Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36`
8. `Mozilla/5.0 (Linux; Android 4.4.2; Lenovo A7600-F Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.109 Safari/537.36`
9. `Mozilla/5.0 (Linux; Android 5.0.2; P01Y Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Safari/537.36`

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/subtlecrypto/digest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/subtlecrypto/digest/index.md
* Last commit: https://github.com/mdn/content/commit/09dafad33d830a475d16760fd1b10b3f8459fb58
* Document last modified: 2021-12-15T12:03:48.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! I have filed https://github.com/mdn/browser-compat-data/issues/14804 for the compat data part of this, and https://github.com/mdn/content/pull/12659 for the MDN part.
