### ISSUE TITLE
Issue with "<fePointLight>": (English grammar error)

### ISSUE THREAD

**Issue by jackdeguest** [mdn/content#11321]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fePointLight

#### What information was incorrect, unhelpful, or incomplete?
"It that can be used within a lighting filter primitive" should probably be replaced by "It then can be used within a lighting filter primitive"

#### What did you expect to see?
"It then can be used within a lighting filter primitive"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/element/fepointlight`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fePointLight
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/fepointlight/index.md
* Last commit: https://github.com/mdn/content/commit/bd3f490ef78b600a1435dfe3611a27f3f2fbf4ef
* Document last modified: 2021-09-23T21:22:12.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. Fixed by #11323
