### ISSUE TITLE
Issue with "<feSpotLight>": (Another English grammar error)

### ISSUE THREAD

**Issue by jackdeguest** [mdn/content#11322]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpotLight

#### What information was incorrect, unhelpful, or incomplete?
"It that can be used within a lighting filter primitive" should likely be replaced with "It then can be used within a lighting filter primitive"

#### What did you expect to see?
"It then can be used within a lighting filter primitive"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/element/fespotlight`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpotLight
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/fespotlight/index.md
* Last commit: https://github.com/mdn/content/commit/bd3f490ef78b600a1435dfe3611a27f3f2fbf4ef
* Document last modified: 2021-09-23T21:22:12.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @jackdeguest 

FYI generally it easier for us to review a pull request (PR) which you can create by clicking edit on the bottom of any page of the docs as shown. 

![image](https://user-images.githubusercontent.com/5368500/146695836-4b8fa8df-fcc0-45ab-b660-21deaf61223c.png)

**Comment by jackdeguest** [comment]
Got it. I will try to do that for next time.
