### ISSUE TITLE
Content suggestion: <WORDY>

### ISSUE THREAD

**Issue by bobychaudhary** [mdn/content#11332]
The phrase "at that point in time" may be wordy in README.md. Consider changing the wording.
You can use then or now.

**Comment by hamishwillee** [comment]
Hi @bobychaudhary 

Thanks for your suggestion. As a rule we try avoid pure grammar improvements in MDN - it's not that we wouldn't like things to be better but that there are only so many reviewers and authors, and our time is generally better spent making sure the technical content is correct.

Upshot, unless the text is actually incorrect or ambiguous it may not be the best use of time. Normally we recommend doing this sort of change as part of larger chunks of work.

**Comment by hamishwillee** [comment]
I'm closing as "no one is going to take this on", but we might consider a PR. Thanks again.
