### ISSUE TITLE
Issue with "Examine and edit the box model": Two example videos are private

### ISSUE THREAD

**Issue by goozak** [mdn/content#11351]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model

#### What information was incorrect, unhelpful, or incomplete?
The last two videos on the page (YouTube IDs `H3ZxRbbyfwI` & `gHjDjM8GJ9I`) are marked as "private" according to YouTube.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/examine_and_edit_the_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/examine_and_edit_the_box_model/index.html
* Last commit: https://github.com/mdn/content/commit/05b71a290b2ab444b23e0f35f619d93203c7e2d8
* Document last modified: 2021-02-02T16:31:29.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you. This is a common problem right now. If it can be done effectively, the easiest way to fix this is to replace the youtube videos with a screenshot.

**Comment by sideshowbarker** [comment]
We have https://github.com/mdn/content/issues/7457 open for tracking the underlying problem
