### ISSUE TITLE
Issue with "IDBIndex.getAllKeys()": getAllKeys returns an Array.

### ISSUE THREAD

**Issue by HelmZalee** [mdn/content#11354]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex/getAllKeys

#### What information was incorrect, unhelpful, or incomplete?
"The getAllKeys() method of the IDBIndex interface instantly retrieves the primary keys of all objects inside the index, setting them as the result of the request object."

First, the article does not specify the form of the information returned in the result property of the request object.  (It is an Array.)  

Second, it does not seem to be the case that getAllKeys "instantly retrieves the primary keys..." _in all circumstances_.  See "did you test this".
#### Specific section or headline?
The topmost headline: IDBIndex.getAllKeys().

#### What did you expect to see?
Different phrasing, perhaps "[the method] returns an IDBRequest object on which success and error handlers may be set.  The _result_ property of the success handler _event_ argument will be an Array containing the keys."

#### Did you test this? If so, how?
Wrote HTML and js to define a simple idb, create a couple of stores, one with an index, and perform operations on that db.  Then I stepped through the code in both FF and Chrome.

After some hours with the Chrome & FF debuggers, I realized stepping through with the FF debugger produces different results than letting the code run to completion.  (In Chrome, the result is the same whether stepping through code, or running w/o breakpoints.)

The test code looks like this:
```
       req = oStore.getAllKeys();
       if (req.result && Array.isArray(res.result)) {
       if (req.readyState !== "pending") {---; return;}
       req.onsuccess = onSuccess;
       ---
       function onSuccess(event) {
          callback(event.result);
          return;
       }
```
With breakpoints disabled, req.readyState === "pending" in both FF and Chrome, and in both the onSuccess handler is assigned and fires.

With a breakpoint at the 'if' statement, using the debugger to inspect req, FF reports req.readyState is 'done' and req.result is an Array of key values.  Upon continuing, the "if" block is executed.  onSuccess is neither assigned nor executed.

Breaking at the same point in Chrome, req.readyState === "pending".  Upon continuing, the "if" block is skipped, onSuccess is assigned, and onSuccess fires, exactly as without any break.

Given this, it is somewhat difficult to describe what getAllKeys does.  It seems to be browser dependent.  Or at least, debugger dependent.  And...if there is a problem, it is with the debugger.  But I don't know enough about this stuff to say it is a problem, rather than something about the debugger I don't get.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/idbindex/getallkeys`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex/getAllKeys
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/idbindex/getallkeys/index.md
* Last commit: https://github.com/mdn/content/commit/b0b00060b28f06c75c2174cddd42581a9d438df0
* Document last modified: 2021-10-22T15:52:01.000Z

</details>

**Comment by sideshowbarker** [comment]
@inexorabletash may be able to give us some guidance here

**Comment by wbamberg** [comment]
I'm closing this. https://github.com/mdn/content/pull/23421 adds the fact that the result is an array. As for the question with the debugger, it's not obvious to me that this is something we should document here, rather than raise an issue against the Firefox developer tools (assuming there is an issue there.
