### ISSUE TITLE
Content suggestion: Convert drag and drop event examples to live examples

### ISSUE THREAD

**Issue by AnilSeervi** [mdn/content#11364]
## What is the new suggestion?

To convert the **static code examples** on the following pages to a **live example**:

 - [x] https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragend

- [x] https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragleave

- [x] https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragover

- [x] https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragstart

- [ ] https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondrop

## Why is it important or useful?

Having live examples will make the concept be understood well for the readers, like I converted for `ondragenter` in PR #8667
## Other supporting information
I'd like to follow upon https://github.com/mdn/content/pull/8667#issuecomment-913198125 and replace static code in the above pages with working live samples.

**Comment by AnilSeervi** [comment]
similar issue #8669
Sorry for creating another issue regarding the conversion @wbamberg

I'd like to track the progress by completing the conversion of examples one after another.

**Comment by wbamberg** [comment]
No worries @AnilSeervi ! I'll close https://github.com/mdn/content/issues/8669 .

**Comment by wbamberg** [comment]
Nice work @AnilSeervi !
