### ISSUE TITLE
Issue with "Element": …

### ISSUE THREAD

**Issue by blmatthews** [mdn/content#1136]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element

#### What information was incorrect, unhelpful, or incomplete?

It uses Slotable instead of Slottable. In fact, it looks like 5 pages do (if I search for Slotable.)

#### Specific section or headline?

Properties included from Slotable

#### What did you expect to see?

Slottable

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/element/index.html
* Report started: 2021-01-09T22:01:14.346Z

</details>

**Comment by chrisdavidmills** [comment]
Ah, yes, thanks for reporting @blmatthews !

So it looks like the spelling of slottable has bene mostly fixed on the `Slottable` class pages, but there are incorrect instances that need fixing on these pages:

* https://developer.mozilla.org/en-US/docs/Web/Web_Components
* https://developer.mozilla.org/en-US/docs/Web/API/Text
* https://developer.mozilla.org/en-US/docs/Web/API/Element/slot
* https://developer.mozilla.org/en-US/docs/Web/API/Element

Please let me know if you find any more!

Whoever does this would also need to update our GroupData to correct this too: https://github.com/mdn/yari/blob/master/kumascript/macros/GroupData.json#L1660

NB: The spec originally used "slotable"; see https://github.com/whatwg/dom/issues/844

**Comment by NegiAkash890** [comment]
HI @chrisdavidmills ,  I can help fixing this issue  : ) . 
Thanks

**Comment by NegiAkash890** [comment]
HI @sideshowbarker , I fixed have the  typos in the page and the remaining are those which are  links like `{{domxref("Slotable")}}`.
I just want to ask before I proceed , that after fixing typos in these links too as I need to do is edit the `mdn/yari` json file and all the side bars like this
![Screenshot from 2021-03-03 16-51-21](https://user-images.githubusercontent.com/55234838/109799083-92a5f400-7c41-11eb-9c66-5e9797c4ffc2.png)
will get fixed too . If I am missing something please correct me .
Thank You

**Comment by sideshowbarker** [comment]
> after fixing typos in these links too all I need to do is edit the `mdn/yari` json file and all the side bars as shown in the image below , will get fixed too

That sounds right

**Comment by sideshowbarker** [comment]
This seems to have been resolved.
