### ISSUE TITLE
Issue with "Cache-Control": Possible grammar incorrectness

### ISSUE THREAD

**Issue by wenfangdu** [mdn/content#11379]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

#### What information was incorrect, unhelpful, or incomplete?

> So if the other cache(s) on the path the response takes store it for 100 seconds (indicated using the `Age` response header field), the browser cache would deduct 100 seconds from its freshness lifetime.

The above sentence feels grammatically incorrect, could anyone change it so that it's easier for non-native English speakers to understand?

<details>
<summary>MDN Content page report details</summary>

- Folder: `en-us/web/http/headers/cache-control`
- MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
- GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/cache-control/index.md
- Last commit: https://github.com/mdn/content/commit/0f1f6f74804725f379465c09f698b88611292c90
- Document last modified: 2021-12-01T06:01:14.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
How about?
> So if the other cache(s) on the network path, taken by the response, store it for 100 seconds (indicated using the Age response header field), the browser cache would deduct 100 seconds from its freshness lifetime.

**Comment by wenfangdu** [comment]
@Andrew-Cottrell Thanks for the effort, it's much clearer now.

**Comment by sideshowbarker** [comment]
Thanks @wenfangdu and thanks @Andrew-Cottrell — I’ve opened #11545 with the suggested wording change.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
