### ISSUE TITLE
Issue with "var()": (scope od custom properties when multiple css files are used on a page)

### ISSUE THREAD

**Issue by sloanthrasher** [mdn/content#11382]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/var

#### What information was incorrect, unhelpful, or incomplete?
Does setting a custom property in one css file allow it's use in other cases files on the same page, and if so, should the custom properties be defined in the first css file loaded?
It would be helpful if this was covered in the document. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/var()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/var()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/var()/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by tlylt** [comment]
Hi @sloanthrasher, answering your questions directly:
- Does setting a custom property in one css file allow it's use in other cases files on the same page?
  - Answer: Yes
- should the custom properties be defined in the first css file loaded?
  - Answer: Not necessarily, it also works if it is defined in the second CSS file

I have raised a PR to put up some examples to illustrate the above, which hopefully helps with making the idea clearer.

Cheers!
