### ISSUE TITLE
Issue with "Introduction": Text references missing images.

### ISSUE THREAD

**Issue by nbanion-gh** [mdn/content#11389]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Introduction

#### What information was incorrect, unhelpful, or incomplete?

The first sentence references "... [svg graphics] shown to the right." These graphics do not appear to exist anymore. To fix, consider removing the reference from the text, adding graphics, or referencing an existing svg like the site logo.

#### Specific section or headline?

Under the h1 "Introduction."

#### What did you expect to see?

Sample images to the right of the text.

#### Did you test this? If so, how?

Viewed the page in Firefox.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/tutorial/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/tutorial/introduction/index.md
* Last commit: https://github.com/mdn/content/commit/bd3f490ef78b600a1435dfe3611a27f3f2fbf4ef
* Document last modified: 2021-09-23T21:22:12.000Z

</details>

**Comment by AnilSeervi** [comment]
Previously there was a **png** image and it seems to have lost during conversion to markdown.
#8652 was raised stating that problem and is still open.


I suggest adding the firefox dino svg as the demo that's available at - https://interactive-examples.mdn.mozilla.net/media/dino.svg

<img src="https://interactive-examples.mdn.mozilla.net/media/dino.svg" width="100" style="background: #fff;" />

**Comment by wbamberg** [comment]
Yeah, this was removed because in Markdown we can't float images, so "to the right" wouldn't work, and as you say, it wasn't even SVG! But we missed the bit of text. Honestly I think it would be fine just to remove the text, but I'd be happy to use the dino head as well. But if we do, we should include it in the source rather than link to https://interactive-examples.mdn.mozilla.net/media/dino.svg .
