### ISSUE TITLE
Split that title

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#1139]
Hello there 👋,

In that document
https://developer.mozilla.org/en-US/docs/Web/API/PaintWorklet/Paint%E2%80%8BWorklet%E2%80%8B.device%E2%80%8BPixel%E2%80%8BRatio

Should not be the title 
## devicePixelRatio
and not
## Paint​Worklet​.device​Pixel​Ratio

See how it looks the URL, some words are repeated.

Note
In this repository there is not discussions so i opened an issue.

### GitHub URL
If You want to get the GitHub's URL visit the document and scroll to _Found a problem with this page?_ section.

https://developer.mozilla.org/en-US/docs/Web/API/PaintWorklet/devicePixelRatio

**Comment by nschonni** [comment]
The one with the bad spaces was deleted awhile ago and the others were also removed in https://github.com/mdn/content/pull/975

**Comment by mattiapontonio** [comment]
I don't know if worked...
Try to start from search
https://developer.mozilla.org/en-US/search?q=Paint%E2%80%8BWorklet%E2%80%8B.device%E2%80%8BPixel%E2%80%8BRatio

**Comment by mattiapontonio** [comment]
https://www.github.com/mdn/content/tree/master/files%2Fen-us%2Fweb%2Fapi%2Fpaintworklet%2Fpaint%E2%80%8Bworklet%E2%80%8B.device%E2%80%8Bpixel%E2%80%8Bratio%2Findex.html

**Comment by mattiapontonio** [comment]
![Screenshot_20210110-022829](https://user-images.githubusercontent.com/44380480/104112159-95443700-52eb-11eb-9b94-cf92ab0f5ae3.png)

Maybe Is even related to the fact that sometimes the source on GitHub doesn't load in my GitHub app

**Comment by mattiapontonio** [comment]
Sorry if this issue Is gone out of repository but Is a issue.

**Comment by chrisdavidmills** [comment]
If you look at the source code for the page: https://github.com/mdn/content/blob/main/files/en-us/web/api/paintworklet/devicepixelratio/index.html#L3

You'll see that the slug is now fixed. We are just waiting for this fix to propagate up to the production site. So this can be closed.
