### ISSUE TITLE
Issue with "Clear-Site-Data": Cache can no longer be cleared since ff 94

### ISSUE THREAD

**Issue by joernheissler** [mdn/content#11395]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data

#### What information was incorrect, unhelpful, or incomplete?

Page is missing the fact that cache can no longer be cleared.
See:
* https://www.mozilla.org/en-US/firefox/94.0/releasenotes/
* https://bugzilla.mozilla.org/show_bug.cgi?id=1671182

#### Specific section or headline?

Directives / cache

#### What did you expect to see?

"no longer works in ff >= 94" or similar.

#### Did you test this? If so, how?

Feature still works with older version but not in current.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/clear-site-data`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/clear-site-data/index.md
* Last commit: https://github.com/mdn/content/commit/abf2061ec81ba17f987ecea93747085bde382654
* Document last modified: 2021-10-27T03:40:13.000Z

</details>

**Comment by hamishwillee** [comment]
@joernheissler Thanks very much. I'll tidy this up. FYI, the best way to get docs support is to add the keyword `dev-doc-needed` to the bugzilla bug. Then we usually pick up a docs action is needed - I've added that now. 

Thanks!
