### ISSUE TITLE
Issue with "Content  categories": text contradicts itself

### ISSUE THREAD

**Issue by davidglavas** [mdn/content#11393]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories

#### What information was incorrect, unhelpful, or incomplete?
The first sentence says "Every HTML element is a member of one or more content categories..."

The last sentence of the same paragraph says " It's also possible for elements to not be a member of any of these categories."

Whats the point of claiming something in the first sentence which is then refuted in the last sentence?

#### Specific section or headline?
Content categories, first paragraph.

#### What did you expect to see?
The whole paragraph should be rewritten so that it doesnt contradict itself like that. Its misleading because its easy for people to just read the first sentence and then leave the page thinking that the sentence is true, when in reality, just a couple of sentences later it says that its actually not true.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/guide/html/content_categories`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/html/content_categories/index.md
* Last commit: https://github.com/mdn/content/commit/4e3adb1d91e84e12ff939e4bcc6bec49aa214791
* Document last modified: 2021-12-20T04:47:08.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
The [HTML Standard, 3.2.5.2 "Kinds of content"](https://html.spec.whatwg.org/multipage/dom.html#kinds-of-content) states
> Each element in HTML falls into zero or more categories that group elements with similar characteristics together.

So I suggest the first sentence of [the page](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories) be changed to something like
> Most HTML elements are a member of one or more content categories — these categories group elements that share common characteristics.

The last sentence of the same paragraph could be removed.
