### ISSUE TITLE
Issue with "CanvasRenderingContext2D.resetTransform()": (incorrectly marked as experimental)

### ISSUE THREAD

**Issue by torgo** [mdn/content#11401]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/resetTransform

#### What information was incorrect, unhelpful, or incomplete?

The API is marked as experimental even though there are implementations in every shipping browser.

Channeling twitter feedback from @samccone : https://twitter.com/samccone/status/1471580942124806146

#### Specific section or headline?

Warning at the top.

#### What did you expect to see?

No warning.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/resettransform`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/resetTransform
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/resettransform/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing @torgo !

We unfortunately represent "experimental" in 2 places: in the page itself, as an explicit usage of the `{{SeeCompatTable}}` macro, and in the browser compat data, where it shows up as a little beaker icon in the table: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/resetTransform#browser_compatibility.

In this case both are wrong, so we have to update both places (it would be nice to have only BCD representing this, and have Yari apply the banner warning based on BCD, but we are not there yet).

Looking at https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D#browser_compatibility there seem to be a few other items where we should drop "experimental" for BCD, and some of them also reflect that in the page (e.g. https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/filter).

**Comment by wbamberg** [comment]
I filed https://github.com/mdn/content/pull/11410 for the mdn/content side of this.

**Comment by wbamberg** [comment]
I also filed https://github.com/mdn/browser-compat-data/pull/14119 for the BCD side.

**Comment by sideshowbarker** [comment]
Both #11410 and https://github.com/mdn/browser-compat-data/pull/14119 have been merged, so going and and closing this now.
