### ISSUE TITLE
base64 rewrite should be using codePointAt and fromCodePoint instead of charCodeAt and fromCharCode

### ISSUE THREAD

**Issue by sudazzle** [mdn/content#11400]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Base64

#### What information was incorrect, unhelpful, or incomplete?
```
for (var nMapIdx = 0; nMapIdx < nStrLen; nMapIdx++) {
    nChr = sDOMStr.charCodeAt(nMapIdx);
    nArrLen += nChr < 0x80 ? 1 : nChr < 0x800 ? 2 : nChr < 0x10000 ? 3 : nChr < 0x200000 ? 4 : nChr < 0x4000000 ? 5 : 6;
}
```
In the code section above charCodeAt return value between (0 and 65535) as of (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt). Are conditions after nChr < 0x10000 even required?

There are other parts of the implementation that use charCodeAt and fromCharCode.
#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Glossary/Base64#solution_2_%E2%80%93_rewriting_atob_and_btoa_using_typedarrays_and_utf-8

#### What did you expect to see?

c3VkYW1hbvCfmYjtuYjwn5Kv7bKv8J+Wlu22lvCfkYrtsYrwn5mP7bmP8J+Rte2xtfCfpLfttLfi
    gI3imYLvuI/wn6eR7beR4oCN8J+Up+20p/Cflbrttbrim7fwn5q07bq04oCN4pmA77iP8J+Qte2w
    tfCfpq7ttq7wn5Ce7bCe8J+Nk+29k/CfpZfttZfwn4277b278J+Mj+28j+KMmuKavfCfjqftvqfw
    n5al7bal8J+Ug+20g+KcneKBifCfhpfttpfwn4ez7bez8J+Hte23tfCfj7Ttv7TzoIGn7bGn86CB
    ou2xovOggbftsbfzoIGs7bGs86CBs+2xs/Oggb/tsb8=

should decode to 🙈💯🖖👊🙏👵🤷‍♂️🧑‍🔧🕺⛷🚴‍♀️🐵🦮🐞🍓🥗🍻🌏⌚⚽🎧🖥🔃✝⁉🆗🇳🇵🏴󠁧󠁢󠁷󠁬󠁳󠁿 instead it generates "路‍♂️六‍⛷‍♀️瑩綾⌚⚽✝⁉gbwls"

#### Did you test this? If so, how?
I throughly read the implementation and also tested. If you try to decode base64 string generated from other platforms (bash for example) which contains emoji this implementation will fail. I replaced codePointAt and fromCodePoint for charCodeAt and fromCharCode respectively and it works as expected.

Should I do a pull request=

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/base64`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Base64
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/base64/index.md
* Last commit: https://github.com/mdn/content/commit/a7261cd6aebb479bcc359216fe55f9267fa3a865
* Document last modified: 2021-11-16T02:32:25.000Z

</details>

**Comment by AnilSeervi** [comment]
You can use the [MDN dicussions](https://github.com/mdn/content/discussions) for questions, ideas, etc.

**Comment by sudazzle** [comment]
Moved to Discussion https://github.com/mdn/content/discussions/11416

**Comment by sideshowbarker** [comment]
> I throughly read the implementation and also tested. If you try to decode base64 string generated from other platforms (bash for example) which contains emoji this implementation will fail. I replaced codePointAt and fromCodePoint for charCodeAt and fromCharCode respectively and it works as expected.
> 
> Should I do a pull request

Yes, please do
