### ISSUE TITLE
Issue with "Number.NEGATIVE_INFINITY": Describe behaviour of comparisions

### ISSUE THREAD

**Issue by richardl62** [mdn/content#11420]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/NEGATIVE_INFINITY

#### What information was incorrect, unhelpful, or incomplete?

The documentation does not descript how NEGATIVE_INFINITY behaves in comparisons.  

#### Specific section or headline?

Description
#### What did you expect to see?

A statement about how NEGATIVE_INFINITY behaves in comparisons, e.g. that NEGATIVE_INFINITY < x is true for any number x that is not NEGATIVE_INFINITY (assuming this is true).

This is not trivially rule as some other languages have a rule that comparison with infinities are always false.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/number/negative_infinity`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/NEGATIVE_INFINITY
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/number/negative_infinity/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by wannurhadi** [comment]
### 

#1. > [_****_]([url](url))

**Comment by sideshowbarker** [comment]
Thanks — I’ve opened #11556 with an update to make clear that per https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-numeric-types-number-lessThan, `x > Number.NEGATIVE_INFINITY` is true for any number _x_ that isn’t itself `Number.NEGATIVE_INFINITY`.
