### ISSUE TITLE
Issue with "Array": (short summary here please)

### ISSUE THREAD

**Issue by GhbSmwc** [mdn/content#11428]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

#### What information was incorrect, unhelpful, or incomplete?
It didn't mention that if you wanted to copy an array, you have to do this:
```
let original_array = [1, 2, 3]
let new_copy = [...original_array]
```
and not this:
```
let original_array = [1, 2, 3]
let new_copy = original_array
//If you modify, say, sort new_copy (new_copy.sort()), it will also modify original_array.
```
Arrays are actually references to values, not values themselves.
Source: https://www.samanthaming.com/tidbits/35-es6-way-to-clone-an-array/
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/index.md
* Last commit: https://github.com/mdn/content/commit/0f1f6f74804725f379465c09f698b88611292c90
* Document last modified: 2021-12-01T06:01:14.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for pointing this out. I agree and have proposed a fix in #11440.
