### ISSUE TITLE
Issue with "Reason: CORS request not HTTP": (short summary here please)

### ISSUE THREAD

**Issue by gbjbaanb** [mdn/content#11426]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

#### What information was incorrect, unhelpful, or incomplete?

The workaround to use `privacy.file_unique_origin` did not work. Instead I found the way to load a local file:// resource via javascript was to set `security.fileuri.strict_origin_policy` to false.

#### Did you test this? If so, how?

yes. Changing the privacy option made no difference to a page failing to load a local (same directory) json file using XMLHttpRequest.open(). The "CORS not http" error was shown in the debug console even with this setting set to false.

Changing the security option made things work again (without even a restart of FF). The page was run from a local html and js file running from local disk on Windows 10 using Firefox 95.0.2

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cors/errors/corsrequestnothttp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/errors/corsrequestnothttp/index.md
* Last commit: https://github.com/mdn/content/commit/46234997b6257b619423a11ce31154afa336143f
* Document last modified: 2021-08-13T16:17:49.000Z

</details>

**Comment by hamishwillee** [comment]
With what test code ?

**Comment by evilpie** [comment]
`security.fileuri.strict_origin_policy` is also being considered for removal: https://bugzilla.mozilla.org/show_bug.cgi?id=1730535.

**Comment by hamishwillee** [comment]
This issue is fixed by #11352
