### ISSUE TITLE
Content bug: <document.querySelector()>

### ISSUE THREAD

**Issue by Super-Mumoo** [mdn/content#11445]
## What page(s) did you find the problem on?

[Error Page](https://developer.mozilla.org/zh-CN/docs/Web/API/Document/querySelector)

## What is the problem?

The Chinese version of the doc write that the return value type of `document.queryselect()` is `HTMLEment`, but the return value type is actually `Element`. There is no this error in the English doc.

Chinese Doc:
![image](https://user-images.githubusercontent.com/38457677/147321764-e0ca256a-abd8-44c4-a9f8-04824f34b25e.png)
![image](https://user-images.githubusercontent.com/38457677/147321792-6a05674b-5775-4e5c-b044-4fa13a525fac.png)

Engilsh Doc:
![image](https://user-images.githubusercontent.com/38457677/147321831-c5ef0130-33fd-49b7-be45-19a0cfad3ca6.png)
![image](https://user-images.githubusercontent.com/38457677/147321852-d3ab8e1b-754a-4695-b6ba-035857ddf4c9.png)

Actual definition:
![image](https://user-images.githubusercontent.com/38457677/147321914-7d973aed-2778-4f16-b4cc-6ad2bf2d4a32.png)

**Comment by AnilSeervi** [comment]
The place where this change would be done is - https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/document/queryselector/index.html

This issue needs to be transfered to [mdn/translated-content](https://github.com/mdn/translated-content)

**Comment by Super-Mumoo** [comment]
> 

ok，thanks

**Comment by AnilSeervi** [comment]
> > 
> 
> ok，thanks

Its ok. Maintainers can transfer this issue to that repo if you reopen.
