### ISSUE TITLE
Issue with "Typical use cases of Flexbox": Inconsistent statements about the flex property

### ISSUE THREAD

**Issue by sharonytlau** [mdn/content#11458]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox

#### What information was incorrect, unhelpful, or incomplete?

>If I wanted all of my navigation items to have equal width, then I might use `flex: auto`, which is the shorthand for `flex: 1 1 auto` — all items grow and shrink from a flex-basis of auto. This would mean that the longer item would have more space.
In the live example below try changing `flex: auto` to `flex: 1`. This is the shorthand for `flex: 1 1 0` and causes all of the items to become the same width, as they are working from a flex-basis of 0 allowing all of the space to be distributed evenly.

Issue description: These two paragraphs write about distributing available space within items using the flex property, specifically the values `flex: auto` and `flex: 1`. It makes me confused that **the first paragraph** claims that we should `flex: auto` to make "navigation items to have equal width". This contradicts **the second paragraph** (and the fact) that `flex: 1` "causes all of the items to become the same width".

#### Specific section or headline?

[Space distributed within the items](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox#space_distributed_within_the_items)

#### What did you expect to see?

**If I wanted to respect the size property of my navigation items but have the available space shared out equally among them**, then I might use `flex: auto`, which is the shorthand for `flex: 1 1 auto` — all items grow and shrink from a flex-basis of auto. This would mean that the longer item would have more space **because it started from a larger size, even though the same amount of available space is assigned to it as the others**.

In the live example below try changing `flex: auto` to `flex: 1`. This is the shorthand for `flex: 1 1 0` and causes all of the items to become the same width, as they are working from a flex-basis of 0 allowing all of the space to be distributed evenly.

(suggested changes are in bold font)

#### Did you test this? If so, how?

no

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_flexible_box_layout/typical_use_cases_of_flexbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_flexible_box_layout/typical_use_cases_of_flexbox/index.md
* Last commit: https://github.com/mdn/content/commit/4ea7390ec8c402e605eec8b6d94ba383a3cc3d2d
* Document last modified: 2021-11-15T10:11:50.000Z

</details>

**Comment by wbamberg** [comment]
@sharonytlau , I think your suggested change is good. Would you like to open a PR to make the change? If not, no worries, I will do it.

**Comment by sharonytlau** [comment]
@wbamberg Thanks! I will work on that.
