### ISSUE TITLE
Issue with "429 Too Many Requests": No browser info

### ISSUE THREAD

**Issue by SirEpiclyAmazing** [mdn/content#11457]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

#### What information was incorrect, unhelpful, or incomplete?
There is no info about browser support

#### Specific section or headline?
Supported browsers

#### Did you test this? If so, how?
A list of supported browserd and their supported versions

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status/429`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/429/index.md
* Last commit: https://github.com/mdn/content/commit/46234997b6257b619423a11ce31154afa336143f
* Document last modified: 2021-08-13T16:17:49.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
So far as I know, all browsers will display an error message when an unknown 400-499 response status code is received without a response body. For example, Chromium (depending on version) displays something like

> **This page isn't working**
> If the problem continues, contact the site owner.
> `HTTP ERROR 429`

In what way could a browser _not_ support 429?
Is there some specific browser behavior expected, such as there is for 401 and 426?

**Comment by wbamberg** [comment]
Yeah, it looks like BCD is missing compat for lots of HTTP status codes: https://github.com/mdn/browser-compat-data/issues/12015 . I think I'd like to close this issue, as it's being tracked over there.

**Comment by SirEpiclyAmazing** [comment]
ok cool
