### ISSUE TITLE
Issue with "AbortController": (documentation/example does not show expected behaviour)

### ISSUE THREAD

**Issue by Dreamsorcerer** [mdn/content#11466]
#### What information was incorrect, unhelpful, or incomplete?

My interpretation of the documentation is that `controller.abort()` would send a signal to cancel any currently listening requests. However, if I do this:
```
controller.abort()
fetch(..., {signal: controller.signal})
```
Then the fetch request is immediately aborted and no request is ever made. So, it appears that `controller.abort()` actually puts the controller into an "aborted" state and anything that ever listens to it in future will immediately get cancelled.

Even the example uses just one controller, with a fetch request on the download button and an abort on the cancel button. But, that means after clicking the cancel button, the download button is then broken, you will never be able to make a new request.

Presumably, the download button needs to create a new controller before every request.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/abortcontroller`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AbortController
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/abortcontroller/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Dreamsorcerer** [comment]
Suggested change to example:
```
function fetchVideo() {
  ...
  controller = new AbortController();  // Set new controller for this request.
  fetch(url, {signal}).then(function(response) {
    ...
  }).catch(function(e) {
   reports.textContent = 'Download error: ' + e.message;
  })
}
```

**Comment by rohitb4** [comment]
@sideshowbarker can I work on this?

**Comment by sideshowbarker** [comment]
@rohitb4 Thanks — assigned you now
