### ISSUE TITLE
Issue with "HTMLInputElement.webkitdirectory": (short summary here please)

### ISSUE THREAD

**Issue by Malibu948975** [mdn/content#11467]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory

#### What information was incorrect, unhelpful, or incomplete?
the script is not javascript, it's DOM.

#### Specific section or headline?
JavaScript content

#### What did you expect to see?
Script and in code to copy, need to add the balises  <SCRIPT> before document.getElementById("filepicker"....
and  </script>" after }, false);"

I tryed the code with balise "<script javascript.." and it didn't echo the files selected in the form.

#### Did you test this? If so, how?

Good, it's ok.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlinputelement/webkitdirectory`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlinputelement/webkitdirectory/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
The example code works as expected. The code shown is JavaScript code. It’s unclear what’s meant by *balise* here…
