### ISSUE TITLE
Issue with "Standard metadata names": Regarding viewport

### ISSUE THREAD

**Issue by w3bdev1** [mdn/content#11465]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name

#### What information was incorrect, unhelpful, or incomplete?
It says that, CSS Device Adaptation specification defines viewport is "Used by mobile devices only."

#### Specific section or headline?
[Standard metadata names defined in other specifications](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name#standard_metadata_names_defined_in_other_specifications)

#### What did you expect to see?
As of now, it is used by mobile only. But UA vendors can implement it for desktop too.

#### Did you test this? If so, how?
- [CSS Device Adaptation specification](https://drafts.csswg.org/css-device-adapt/#atviewport-rule) says "UA vendors implementing this specification are strongly encouraged to do so both for their mobile and desktop browsers. The @viewport mechanism is designed to be usable and useful on all browsers, not only mobile ones."

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/meta/name`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/meta/name/index.md
* Last commit: https://github.com/mdn/content/commit/775662998e66813a612e3ff27e02f2ada867bc17
* Document last modified: 2021-10-03T00:01:51.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve opened #11544 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
