### ISSUE TITLE
RadioNodeList - Missing an example

### ISSUE THREAD

**Issue by ylerjen** [mdn/content#11476]
#### What information was incorrect, unhelpful, or incomplete?

From the actual [browser-compat-data of the english page](https://developer.mozilla.org/en-US/docs/Web/API/RadioNodeList), it seems RadioNodeList is supported on IE, but after a bug I faced, I've made some tests which demonstrate that it isn't.

#### What did you expect to see?

I expect to see IE not supporting the RadioNodeList api.

#### Did you test this? If so, how?

We faced a bug when checking with `instanceof RadioNodeList` which throw `RadioNodeList is undefined`.

I then tested it by running in IE11's console `typeof RadioNodeList === 'undefined'` which returns `true`.

Is there really a mistake in the doc or did I misunderstand the support table and it's not related to that?

<details>
<summary>MDN page report details</summary>

* Query: `api.RadioNodeList`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RadioNodeList
* Report started: 2021-07-21T11:21:08.558Z

</details>

**Comment by Josh-Cena** [comment]
See https://github.com/mdn/content/pull/33999; only IE doesn't expose this but we don't document IE anyway.
