### ISSUE TITLE
Issue with "HTMLMediaElement.controlsList": (Inaccurate browser support information)

### ISSUE THREAD

**Issue by jackdeguest** [mdn/content#11487]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList

#### What information was incorrect, unhelpful, or incomplete?
That page states that this feature `controlsList` is supported in Chrome v58 or Opera v45. However, I have tested in both Chromium v61 and Opera v82 for Mac and this property is not implemented.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlmediaelement/controlslist`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlmediaelement/controlslist/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment]
Hi @jackdeguest 

Thanks. What test code did you use?
I ran the following test code on Chrome 96 on Windows, and it is at least supported on that version. 

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Test - JavaScript self.reportError()</title>
  </head>

  <body>
  <h1>Test - HTMLMediaElement.controlsList</h1>
  https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList
  <p>... and check out the log</p>
  <textarea id="log" rows="10" cols="150"></textarea>
  <div>
  <video id="mymediaelement" controls="" controlslist="nofullscreen" src="//storage.googleapis.com/media-session/caminandes/short.mp4#t=82"></video>
  <pre>&lt;video controls controlsList="nofullscreen"&gt;</pre>
</div>

<script>
const log = document.getElementById("log");
const mymediaelement = document.getElementById("mymediaelement");
log.textContent=mymediaelement.controlsList
</script>
   </body>
</html>
```
What I see is  `nofullscreen` as shown:

![image](https://user-images.githubusercontent.com/5368500/147422161-641be1e1-ae42-410e-b8aa-7876086d4d2b.png)

Can you confirm you don't see `nofullscreen` if you run this code on those versions of Chrome on Mac? Any chance you can try it a current Chrome on Mac?

If you can verify and we can fine the problem version we can update the compatibility table.

**Comment by hamishwillee** [comment]
@Elchi3 @ddbeck Can you guys move this to BCD for investigation

**Comment by jackdeguest** [comment]
Maybe, it's my mistake, but I simply did:
```
let media = document.createElement('media');
media.controlsList;
```
I ran your test, and it ran fine on Opera and Chromium.
So my bad for thinking `controlsList` would return something with only a simple `media` element.

**Comment by hamishwillee** [comment]
No stupid. Learning experience :-).

**Comment by jackdeguest** [comment]
Yes learning not to report presumed bugs or typos when one is sleep-deprived :)
