### ISSUE TITLE
Issue with "WritableStreamDefaultWriter": (Incorrect/Problematic Example)

### ISSUE THREAD

**Issue by watuwo** [mdn/content#11494]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WritableStreamDefaultWriter

#### What information was incorrect, unhelpful, or incomplete?

Im am referring to this example currently on
https://developer.mozilla.org/en-US/docs/Web/API/WritableStreamDefaultWriter:

```js
const list = document.querySelector('ul');

function sendMessage(message, writableStream) {
	// defaultWriter is of type WritableStreamDefaultWriter
	const defaultWriter = writableStream.getWriter();
	const encoder = new TextEncoder();
	const encoded = encoder.encode(message, { stream: true });
	encoded.forEach((chunk) => {
		defaultWriter.ready
			.then(() => {
				return defaultWriter.write(chunk);
			})
			.then(() => {
				console.log("Chunk written to sink.");
			})
			.catch((err) => {
				console.log("Chunk error:", err);
			});
	});
	// Call ready again to ensure that all chunks are written
	//   before closing the writer.
	defaultWriter.ready
		.then(() => {
			defaultWriter.close();
		})
		.then(() => {
			console.log("All chunks written");
		})
		.catch((err) => {
			console.log("Stream error:", err);
		});
}

const decoder = new TextDecoder("utf-8");
const queuingStrategy = new CountQueuingStrategy({ highWaterMark: 1 });
let result = "";
const writableStream = new WritableStream({
	// Implement the sink
	write(chunk) {
		return new Promise((resolve, reject) => {
			var buffer = new ArrayBuffer(2);
			var view = new Uint16Array(buffer);
			view[0] = chunk;
			var decoded = decoder.decode(view, { stream: true });
			var listItem = document.createElement('li');
			listItem.textContent = "Chunk decoded: " + decoded;
			list.appendChild(listItem);
			result += decoded;
			resolve();
		});
	},
	close() {
		var listItem = document.createElement('li');
		listItem.textContent = "[MESSAGE RECEIVED] " + result;
		list.appendChild(listItem);
	},
	abort(err) {
		console.log("Sink error:", err);
	}
}, queuingStrategy);

sendMessage("Hello, world.", writableStream);

```

Preliminary note: Note that `then` is called multiple
times *on the same* `Promise` (branching, not chaining):
`defaultWriter.ready.then` is called multiple times.

When a write `Promise` rejects, we see the problems with
the code. Assume the first chunk's write promise rejects:

- The error handler printing `"Chunk error:", err` is called
  13 times (not just once for the failing chunk): all
  chunks (their "tasks") are immediately enqueued by
  `defaultWriter.ready` (not in the writer/stream's queue).
- The error handler registered for the closing task
  (printing `"Stream error:", err`) is not called at all.
  The error resulting from calling `defaultWriter.close()`
  is unhandled. Instead of:
  
  ```
  defaultWriter.close();
  ```
  
  it should be
  
  ```
  return defaultWriter.close();
  ```

#### Specific section or headline?

Section "Examples": https://developer.mozilla.org/en-US/docs/Web/API/WritableStreamDefaultWriter#examples

Note that the example might also be here: https://developer.mozilla.org/en-US/docs/Web/API/WritableStreamDefaultWriter/close

#### What did you expect to see?

I would love to see an example that:

- handles errors / `Promise` rejections decently (handling a single error once, no unhandled errors, handling errors from `close`, no writing attempts after error)
- does not use "branching" `then` when "chaining" `then` or `async`/`await` could easily be used (this example shows the confusion that can arise)

#### Did you test this? If so, how?

Yes, I tested this. To reproduce:

- Download the code from "https://mdn.github.io/dom-examples/streams/simple-writer/"
- `reject` some `Promise` (the one already explicitly in the code or add one to `reject`).
- Run the code in a browser already supporting `WritableStream`s.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/writablestreamdefaultwriter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WritableStreamDefaultWriter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/writablestreamdefaultwriter/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by wbamberg** [comment]
@watuwo , it has been a while, but I filed a PR for this today -> https://github.com/mdn/content/pull/25597.
