### ISSUE TITLE
Issue with "Web APIs": (short summary here please)

### ISSUE THREAD

**Issue by arshak-grigoryan** [mdn/content#11498]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API

#### What information was incorrect, unhelpful, or incomplete?

I can't find **The HTML DOM API** in the WEB APsI list.
But I see that, that in this [page](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API)  it is listed under WEB API path
#### What did you expect to see?

The HTML DOM API listed in the WEB APIs list.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks! Fixed in #11501
