### ISSUE TITLE
Issue with "font-display": (short summary here please)

### ISSUE THREAD

**Issue by viprobelk** [mdn/content#11499]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/@font-face/font-display`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@font-face/font-display/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by hamishwillee** [comment]
Closing. No information provided in issue template.
