### ISSUE TITLE
Issue with "MessageEvent()": `type` parameter specified as "XXX"

### ISSUE THREAD

**Issue by ouroborus** [mdn/content#11518]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/MessageEvent

#### What information was incorrect, unhelpful, or incomplete?
`type` parameter described as "This can be one of XXX"

#### Specific section or headline?
Parameters

#### What did you expect to see?
A list describe what the `type` parameter can be.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/messageevent/messageevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/MessageEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/messageevent/messageevent/index.md
* Last commit: https://github.com/mdn/content/commit/e13598c4e35243df24286e4842fafee5ae76217a
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. The spec doesn't state what it is and you can obviously do what you like if you fire this yourself. However most commonly the event types that use MessageEvent are named .... `message`. I've attempted to fix this in #11521
