### ISSUE TITLE
Issue with "i18n": (short summary here please)

### ISSUE THREAD

**Issue by pilsator110** [mdn/content#11513]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/i18n`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/i18n/index.md
* Last commit: https://github.com/mdn/content/commit/0baf49fec367afb6e593067ed872e53e7626c2dd
* Document last modified: 2021-11-29T00:46:14.000Z

</details>

**Comment by hamishwillee** [comment]
Closing. Insufficient information provided in issue template.
