### ISSUE TITLE
Issue with "StorageArea.get()": (empty string behavior inaccurate)

### ISSUE THREAD

**Issue by lapcat** [mdn/content#11515]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get

#### What information was incorrect, unhelpful, or incomplete?
"If you pass an empty string, object or array here, an empty object will be retrieved. If you pass null, or an undefined value, the entire storage contents will be retrieved."

#### Specific section or headline?
Parameters

#### What did you expect to see?
"If you pass an empty object or array here, an empty object will be retrieved. If you pass null, or an undefined value, the entire storage contents will be retrieved."

Compare with [chrome.storage](https://developer.chrome.com/docs/extensions/reference/storage/): "An empty list or object will return an empty result object. Pass in null to get the entire contents of storage."

#### Did you test this? If so, how?
Yes. In Firefox, `browser.storage.local.get("")` returns the value from  `browser.storage.local.set({"":"empty"})` and in Chrome, `chrome.storage.local.get("")` returns the value from `chrome.storage.local.set({"":"empty"})`.

Safari seems to have a bug and returns different values depending on whether the browser or chrome API is used, and not the expected value in either case.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/storage/storagearea/get`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/get/index.md
* Last commit: https://github.com/mdn/content/commit/629960fa07e15f2354d75daf14f149d4942539ec
* Document last modified: 2021-10-26T21:28:18.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #11542 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
