### ISSUE TITLE
Issue with "Django Tutorial Part 4: Django admin site": incorrect defintion of the display_genre method of the BookAdmin class

### ISSUE THREAD

**Issue by mar-vic** [mdn/content#11530]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Admin_site

#### What information was incorrect, unhelpful, or incomplete?

The display_genre method referenced in list_display tuple of the BookAdmin class takes two arguments, not one as specified in the tutorial. Moreover, the genre is not an attribute of 'self' (that is of the BookAdmin object), but of the Book object (i.e., of the second parameter of the display_genre method). 

#### Specific section or headline?

[Configure list views](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Admin_site#configure_list_views)

#### What did you expect to see?

The display_genre function should be defined in the following way:

```python
def display_genre(self, obj): 
    """Create a string for the Genre. This is required to display genre in Admin"""
    return ', '.join(genre.name for genre in obj.genre.all()[:3])
```

#### Did you test this? If so, how?

I did test this by running the code.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/admin_site`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Admin_site
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/admin_site/index.md
* Last commit: https://github.com/mdn/content/commit/0f1f6f74804725f379465c09f698b88611292c90
* Document last modified: 2021-12-01T06:01:14.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, but you are incorrect.

`list_display` takes just one argument - `self`. `BookAdmin` calls it on the specific instance of a book, from which it knows its `self`. There is no need to pass in any other objects.

You can see this using the demo version of this tutorial - which I have tested multiple times and works.
- BookAdmin https://github.com/mdn/django-locallibrary-tutorial/blob/master/catalog/admin.py#L50
- Book Model https://github.com/mdn/django-locallibrary-tutorial/blob/master/catalog/models.py#L49
