### ISSUE TITLE
Issue with "What is JavaScript?": Google experiment link is not correct

### ISSUE THREAD

**Issue by Johanvanhaeren** [mdn/content#11543]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript

#### What information was incorrect, unhelpful, or incomplete?

Google experiment link is not correct, should be: https://experiments.withgoogle.com/collection/chrome

#### What did you expect to see?

https://experiments.withgoogle.com/collection/chrome 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/what_is_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/what_is_javascript/index.md
* Last commit: https://github.com/mdn/content/commit/6e6b0c34cc8809254cc3a00e00eae02c50ecc8a8
* Document last modified: 2021-12-06T22:39:51.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #11551 with the fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
