### ISSUE TITLE
Issue with "Content Security Policy (CSP)" Need coverage of Duck Duck Go

### ISSUE THREAD

**Issue by gregreynoldsjr** [mdn/content#11549]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

#### What information was incorrect, unhelpful, or incomplete?

Duck Duck Go drove the adoption of CSP as a standard. It should be included in the list of supported browsers. 

#### Specific section or headline?

Browser compatibility matrix.

#### What did you expect to see?

Coverage for Duck Duck Go

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/csp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/csp/index.md
* Last commit: https://github.com/mdn/content/commit/0f1f6f74804725f379465c09f698b88611292c90
* Document last modified: 2021-12-01T06:01:14.000Z

</details>

**Comment by sideshowbarker** [comment]
I can’t find any list of supported browsers in the content of the article itself. The Browser Compatibility table isn’t manually maintained; instead each MDN article has Browser Compatibility table that’s generated from data we maintain in the https://github.com/mdn/browser-compat-data repo. And for that we don’t maintain separate lists of browsers depending on feature but instead just the browsers in https://github.com/mdn/browser-compat-data/tree/main/browsers — which doesn’t include the Duck Duck Go browser.
