### ISSUE TITLE
Issue with "Taking still photos with WebRTC": (short summary here please)

### ISSUE THREAD

**Issue by d5269357812** [mdn/content#11562]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos

#### What information was incorrect, unhelpful, or incomplete?
whole page si a shit fucking take me 2 hours and can't run

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webrtc_api/taking_still_photos`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webrtc_api/taking_still_photos/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
There doesn’t seem to be enough information in the issue description for anybody else to be able to help.

Please consider posting another issue with a more-detailed issue description that includes, for example, any error message that the browser is logging in the devtools console.
