### ISSUE TITLE
Issue with "String.prototype.padStart()": List canonical name for space before the unicode endpoint

### ISSUE THREAD

**Issue by PythonCoderAS** [mdn/content#11577]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

#### What information was incorrect, unhelpful, or incomplete?

The `padString` parameter says, 

> The default value is "` `" (`U+0020 'SPACE'`).

I think that it is weird to list the unicode endpoint first, and that the order should be switched around.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart#parameters

#### What did you expect to see?

The order switched around.

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/padstart`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/padstart/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by hamishwillee** [comment]
FWIW This looked fine to me. Certainly switching it around will not be better. I have proposed an alternative in #11580
