### ISSUE TITLE
[NotReleased - behind pref] [WebAPI] Support ScreenOrientation.lock

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#11594]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

https://bugzilla.mozilla.org/show_bug.cgi?id=1697647

**Comment by hamishwillee** [comment]
Status. This is behind a pref, so not a "release". 

- [ ] BCD - need to check the version on which this became disabled so we can update when it became re-enabled. 
- [ ] Docs - [ScreenOrientation.lock()](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock) updates - in progress  https://github.com/mdn/content/pull/11684
- [ ] dev-doc-complete
- [ ] Experimental features addition

**Comment by hamishwillee** [comment]
I think this is done/OK
