### ISSUE TITLE
[WebAPI] Add abort reason to AbortSignal

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#11593]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

https://bugzilla.mozilla.org/show_bug.cgi?id=1737771

**Comment by hamishwillee** [comment]
Status

- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/14418
- [ ] Docs
  - [ ] [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) 
  - [ ] [AbortSignal.abort()](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/abort)
- [ ] Release Note
- [ ] dev-doc-complete
