### ISSUE TITLE
[CSS] Rename/alias color-adjust to print-color-adjust

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#11598]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

https://bugzilla.mozilla.org/show_bug.cgi?id=1747595

**Comment by hamishwillee** [comment]
@Rumyra Not doing any work on this, though possibly might find time Friday. This is what I found out so far.

So this renames [color-adjust](https://developer.mozilla.org/en-US/docs/Web/CSS/color-adjust) to `print-color-adjust`, and makes  `color-adjust` an alias, reflecting a spec change.
The BCD is here: https://github.com/mdn/browser-compat-data/blob/main/css/properties/color-adjust.json

The docs for [color-adjust](https://developer.mozilla.org/en-US/docs/Web/CSS/color-adjust) look OK. Looking at the code here https://hg.mozilla.org/mozilla-central/rev/944668ceb274#l2.50 shows the values. There is one ` "revert-layer",` that is not in the docs - I haven't checked if that is relevant: https://developer.mozilla.org/en-US/docs/Web/CSS/color-adjust#syntax

This is linked in a few places including https://developer.mozilla.org/en-US/docs/Web/HTML/Applying_color but nothing much serious.

There is already a doc for this old alias [-webkit-print-color-adjust](-webkit-print-color-adjust) which is in Chrome - we might want to cross link these while we're here.

I'm not sure how this kind of thing is handled for CSS in BCD and docs. For BCD you could move the doc to the new name and put in `color-adjust` as an alternative name. But then you lose the version in which the spec change happened. I would need to talk to Daniel to work out the right way. That might then inform how the docs change is handled.

**Comment by ddbeck** [comment]
For BCD, the approach is this:

1. Rename the `color-adjust` data to `print-color-adjust`.
2. Fix the existing alternative names to use `prefix` instead.
3. Update the spec URL.
2. For Firefox, use two support statements: one showing support for the new `print-color-adjust` (a plain support statement, from version 97) and one with the alternative name `color-adjust` (from version 48).

The way this is specified makes things somewhat a risk in the future. The spec authors are doing something really odd: making a "shorthand" (of one and only one other property) and making it deprecated. If there was actually a difference in behavior, I'd say we need to separate pages. We might, in the future, should `color-adjust` ever be put to real use. But for now, we can follow the process above.

**Comment by Rumyra** [comment]
> There is one "revert-layer", that is not in the docs 

I've rolled this into the `@layer` work https://github.com/mdn/content/issues/9369 so I can tackle it there 👍

**Comment by hamishwillee** [comment]
Status:
- [ ] BCD: https://github.com/mdn/browser-compat-data/pull/14738
- [ ] Docs 
- [ ] dev-doc-complete
- [ ] Release note
