### ISSUE TITLE
[CSS] Implement scrollbar-gutter css property

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#11595]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed
- [x] mdn/data

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

https://bugzilla.mozilla.org/show_bug.cgi?id=1715112

**Comment by hamishwillee** [comment]
@Rumyra Can't take this but done initial investigations:
- Already documented: [scrollbar-gutter](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter) and supported in chrome
- The docs could be improved with a screenshot showing this reserved gutter space in the various cases - I "think" I know what this means, but I am not sure and a screenshot would help that
- FYI there is a test here: https://w3c-test.org/css/css-overflow/scrollbar-gutter-001.html - in fact a few: https://w3c-test.org/css/css-overflow/
- The [code here](https://hg.mozilla.org/mozilla-central/rev/83044c2e662d#l9.37) has notes like:
  ```
   [overflow scroll, scrollbar-gutter stable both-edges]
  +    expected:
  +      if os == "android": FAIL # Overlay scrollbars do not create scrollbar gutters
  ```
  I am not sure if this reflects that android is always non-compliant with the spec or not. This will of course affect BCD.
- There is no preference I can see - this is released

Upshot, mostly this will be BCD and a release note. If you discover time, additional screenshots showing what the gutter really is would be great.
