### ISSUE TITLE
OpenSearch description format: Mention that support for 'moz:SearchForm' has been dropped in Firefox

### ISSUE THREAD

**Issue by muekoeff** [mdn/content#11607]
## What is the new suggestion?
[OpenSearch description format](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) currently states that `moz:SearchForm` is supported by Firefox. With [Bug 1675996](https://bugzilla.mozilla.org/show_bug.cgi?id=1675996) this feature is yet another useful uniqueness of Firefox that has been stripped from the browser for little to no reason. Therefore `moz:SearchForm` should be marked as deprecated or as no longer supported in the article.

## Why is it important or useful?
The mentioned feature is no longer supported by any of the major browsers and therefore only of interest for readers targeting older versions of Firefox.

**Comment by ntaulbut** [comment]
That merge has confusingly not removed all mention to moz:SearchForm. It is still in the example and in the introduction.
