### ISSUE TITLE
HTMLMediaElement missing resize event page 

### ISSUE THREAD

**Issue by estelle** [mdn/content#11608]
## What is the new suggestion?
Create page to document resize event at [https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/resize_event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/resize_event)

| Event name | Interface | Fired when... | Preconditions
-- | -- | -- | --
resize | Event | One or both of the videoWidth and videoHeight attributes have just been updated. | Media element is a video element; readyState is not HAVE_NOTHING

**Comment by postmeback** [comment]
I can write down the content, but I do not know how to create a new page here. Requesting the maintainers to add the page and link it.

**Comment by estelle** [comment]
To create a page, create a directory named `resize_event` within the `/files/en-us/web/api/htmlmediaelement/` directory.

```
cd files/en-us/web/api/htmlmediaelement/
mkdir resize_event
```

The content is saved within that new directory as `index.md`.

I find saving a version of a similar method or a sibling doc to be the easiest way to create a new page. Here, I would copy either '/files/en-us/web/api/window/resize_event' or the `/files/en-us/web/api/htmlmediaelement/abort_event` page and use one as my template.

There is already a link to the page from `/files/en-us/web/api/HTMLMediaElement` - it is red with a wavy underline. In your local dev environment, that link will turn blue with a straight underline once the page is created and the front matter (the content at the top of the doc that isn't visible to the user) is correct.

```
---
title: "HTMLMediaElement: resize event"
short-title: resize
slug: Web/API/HTMLMediaElement/resize_event
page-type: web-api-event
browser-compat: api.HTMLMediaElement.resize_event
---

{{APIRef}}

The **`resize`** event is fired when...
```

**Comment by Josh-Cena** [comment]
Added in https://github.com/mdn/content/pull/33285

**Comment by estelle** [comment]
Thank you @skyclouds2001, @Josh-Cena, and @sideshowbarker!
