### ISSUE TITLE
Issue with "Client-side storage": (short summary here please)

### ISSUE THREAD

**Issue by horusofoz** [mdn/content#11617]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

#### What information was incorrect, unhelpful, or incomplete?
The link to the ServiceWorkers cookbook links to https://serviceworke.rs/ which is not the expected destination.

#### Specific section or headline?
[A service worker example](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage#a_service_worker_example) > Responding to further requests

#### What did you expect to see?
Expected to link to the Service Worker cookbook - Possibly https://github.com/mozilla/serviceworker-cookbook ?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/client-side_storage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/client-side_web_apis/client-side_storage/index.md
* Last commit: https://github.com/mdn/content/commit/832b5d184a3619e8817805f606937732c50a92c4
* Document last modified: 2021-12-30T18:58:22.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for finding this. I am not sure if just linking to the source on github is sufficient - created https://github.com/mdn/content/pull/11672 to get some opinions.
