### ISSUE TITLE
Deadlink at the Result section of Creating a URL Representing the Content of a Typed Array under Blob of Web APIs

### ISSUE THREAD

**Issue by frankie-frank-frank** [mdn/content#11610]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Blob

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/blob`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Blob
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/blob/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
This is about the **Open the array URL** hyperlink, which causes a CSP violation:

> Content Security Policy: The page’s settings blocked the loading of a resource at `blob:https://yari-demos.prod.mdn.mozit.cloud/55434b57-cc4e-4198-94a6-ed4ddeac9568` (“frame-src”).

**Comment by sideshowbarker** [comment]
Thanks for raising this. I finally got around to writing up and fix, and opened https://github.com/mdn/content/pull/19096.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
