### ISSUE TITLE
Issue with "HTTP conditional requests": Wrong ETag and Last-Modified header in figure httplock1.png

### ISSUE THREAD

**Issue by florianwicher** [mdn/content#11629]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests

#### What information was incorrect, unhelpful, or incomplete?

In this figure
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests/httplock1.png](url)
the headers `Last-Modified` and `ETag` of the first server response depicted should be "date" and "xyz", not "date2" and "xyz2".

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/conditional_requests`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/conditional_requests/index.md
* Last commit: https://github.com/mdn/content/commit/46ea80e2aa45c9a171c8dac4dcba281b2a13e1f0
* Document last modified: 2021-11-04T05:16:23.000Z

</details>

**Comment by hamishwillee** [comment]
Good catch. Thanks very much. Fixed in  #11673
