### ISSUE TITLE
Navigation failed to `Improving scrolling performance with passive listeners`

### ISSUE THREAD

**Issue by donnisnoni** [mdn/content#1163]
The link to permalink https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#improving_scrolling_performance_with_passive_listeners is failed.

The link on the anchor is invalid i think `#improving_scrolling_performance_with________passive_listeners`, it should `#improving_scrolling_performance_with_passive_listeners`.

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @donnisnoni !

I've submitted https://github.com/mdn/content/commit/1cdfa8332670a74cfe46d052fa67d5b86c50e7d2 to fix it, so I think this can be closed now.
