### ISSUE TITLE
Issue with "HTMLLabelElement.control": (label.control and the labelable element)

### ISSUE THREAD

**Issue by jackdeguest** [mdn/content#11633]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/control

#### What information was incorrect, unhelpful, or incomplete?
The documentation explains the control matches the element whose id is provided with the `for` attribute or null otherwise.
However, the specifications differs somewhat. It states that "If the `for` attribute is not specified, but the label element has a labelable element descendant, then the first such descendant in tree order is the label element's labeled control."
A 'labelable element' is a "button, input (if the type attribute is not in the Hidden state) meter, output, progress, select, textarea, form-associated custom elements"
Reference: [https://html.spec.whatwg.org/multipage/forms.html#htmllabelelement](https://html.spec.whatwg.org/multipage/forms.html#htmllabelelement)
Thus if we write:

```
let label = document.createElement('label');
let button = document.createElement('button');
label.appendChild(button);
```

`label.control` should give us the HTMLButtonElement, but now in Firefox v95.0.2 it returns `null`

#### What did you expect to see?
I expected `control` to return the first instance of a child `labelable element` if no `for` attribute is set.

#### Did you test this? If so, how?
```
let label = document.createElement('label');
let button = document.createElement('button');
label.appendChild(button);
label.control instanceof HTMLButtonElement; // label.control returns null
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmllabelelement/control`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/control
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmllabelelement/control/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Josh-Cena** [comment]
I can't reproduce this in FF 90 (released several months before this issue) and latest FF:

<img width="310" alt="image" src="https://user-images.githubusercontent.com/55398995/209402823-93401a43-3dc9-4e76-a5b1-185a3efd17e1.png">

I can only assume there was something wrong with the demo setup, because there's no other way for me to verify.
