### ISSUE TITLE
Issue with "Using XMLHttpRequest": bug in function AJAXSubmit

### ISSUE THREAD

**Issue by jackyhallyday** [mdn/content#11650]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest

#### What information was incorrect, unhelpful, or incomplete?

If the form to send has an input that doesn't have a type attribute, the script stops.
For example: `<input name="company_name">`

#### Specific section or headline?

Section Using FormData objects, function AJAXSubmit of the exemple:

```
sFieldType = oField.nodeName.toUpperCase() === "INPUT" ?
          oField.getAttribute("type").toUpperCase() : "TEXT";
```

#### What did you expect to see?

```
sFieldType = oField.nodeName.toUpperCase() === "INPUT" && oField.hasAttribute("type") ?
          oField.getAttribute("type").toUpperCase() : "TEXT";
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/xmlhttprequest/using_xmlhttprequest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
* Last commit: https://github.com/mdn/content/commit/24ce361ce4e4d0c06cffd0ac8f2022c7b1e96909
* Document last modified: 2021-10-03T12:16:00.000Z

</details>

**Comment by sidverma32** [comment]
@michaelmagyar If this issue is not picked up yet, can take this up?

**Comment by sidverma32** [comment]
I have updated the code. Pls review my changes [#11737](https://github.com/mdn/content/pull/11737) @sideshowbarker @michaelmagyar

**Comment by michaelmagyar** [comment]
Hi @sidverma32. Did you meant to at someone else? I've only once contributed to this repo, and that was to add a missing Markdown backtick to fix documentation formatting.

For what it's worth, the change looks reasonable to me

**Comment by sidverma32** [comment]
ok. Requested to other member from core-team who have access to review and merge this PR.
