### ISSUE TITLE
Issue with "Response": documentation missing XMLHttpRequest mention/cross-link/example. Presumption of only fetch API

### ISSUE THREAD

**Issue by vectorselector** [mdn/content#11667]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response

#### What information was incorrect, unhelpful, or incomplete?
Presumption of ONLY fetch API `response` interface, no mention made of `XMLHttpRequest.response` interface, no cross-reference, no mention at all.

#### Specific section or headline?
Missing `XMLHttpRequest.response` interface reference, when it is still a required API for many developers due to backwards compatibility.

#### What did you expect to see?
Some reference to the (older, yet still most prevalent in terms of browser support)  XMLHttpRequest API.response interface, even if merely as a deprecated API with a cross-link to this page: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response

Ideally lets add an example, as the current URL https://developer.mozilla.org/en-US/docs/Web/API/Response indicates a canonical singular way of doing things while providing only fetch API examples in ES6

 (example: ES5, no transpiling needed.)

```
var xhr = new XMLHttpRequest();
xhr.onreadystatechange =  function(){
  if(this.readystate == 4 && this.status == 200){
     //this block is equivalent to a promise.then block 
      var resp = xhr.response;
  }
}
xhr.open("POST", myUrl, true);
xhr.send(optionalFormData);

```

#### Did you test this? If so, how?
documentation related, not code.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/response`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/response/index.md
* Last commit: https://github.com/mdn/content/commit/4072b1033d73e9d7ee8ff6290f24057fc97e8a58
* Document last modified: 2021-11-09T06:44:18.000Z

</details>

**Comment by sideshowbarker** [comment]
The `xhr.response` property is documented at https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response and is completely unrelated to the `Response` object documented at https://developer.mozilla.org/en-US/docs/Web/API/Response

So it wouldn’t be appropriate to include information about the `xhr.response` property in the https://developer.mozilla.org/en-US/docs/Web/API/Response article.
