### ISSUE TITLE
Issue with "GeolocationPosition.timestamp": timestamp is when acquired, not when object is created

### ISSUE THREAD

**Issue by lborgman** [mdn/content#11669]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPosition/timestamp

#### What information was incorrect, unhelpful, or incomplete?
The value of timestamp should according to W3C be when the geographic position was acquired, not be when the JavaScript position object was created.

#### Specific section or headline?
Initial part, description

#### What did you expect to see?
From the link to W3C: "The timestamp attribute represents the time when the geographic position of the device was acquired."

#### Did you test this? If so, how?
NA

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/geolocationposition/timestamp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPosition/timestamp
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/geolocationposition/timestamp/index.md
* Last commit: https://github.com/mdn/content/commit/a2a45a0aec877e97ec64d9ddcd5ea9c95daef0d3
* Document last modified: 2021-11-19T00:06:12.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. Fix in #11675
