### ISSUE TITLE
Issue with "TypeScript support in Svelte": "npm run validate" doesn’t work

### ISSUE THREAD

**Issue by Equiverse** [mdn/content#11671]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_TypeScript

#### What information was incorrect, unhelpful, or incomplete?
"npm run validate -- --watch"

Does not work

#### Specific section or headline?
Porting our to-do list app to TypeScript

#### What did you expect to see?
After a bit of digging through: 

https://svelte.dev/blog/svelte-and-typescript#Adding_TypeScript_to_an_existing_project

I was expecting to see:

"npx svelte-check --watch"

#### Did you test this? If so, how?

using git bash and vs code terminal

Node seem to have removed your 'validation' module.

A lot of people wont be able to follow along because of this simple mistake.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_typescript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_TypeScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_typescript/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by AnilSeervi** [comment]
- #11550 fixes this issue
