### ISSUE TITLE
Issue with "background-position": 3-value syntax: Two values are keyword values, and the third is the offset for the preceding value:

### ISSUE THREAD

**Issue by Junaid-1993** [mdn/content#11687]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-position

#### What information was incorrect, unhelpful, or incomplete?
The first value is one of the keyword values top, left, bottom, right, or center. If left or right are given here, then this defines X. If top or bottom are given, then this defines Y and the other keyword value defines X.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/CSS/background-position

The 3-value syntax: Two values are keyword values, and the third is the offset for the preceding value:

#### What did you expect to see?
In the 3-value syntax, the first point is very confusing. This point is more relevant for the 2-value syntax, not the 3-value syntax because this point is only defining 2 values, not the 3 values. The same point is defined on the 2-value syntax.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/background-position`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-position
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/background-position/index.md
* Last commit: https://github.com/mdn/content/commit/9ca237eb91173fa84eb24eb5a6336efc14f18f62
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by Anurella** [comment]
The first point is trying to highlight that for 3-value syntax, the first value can be **any** of the keywords but reiterating that `left` or `right` defines X and `top` or `bottom` defines Y.

**Comment by Junaid-1993** [comment]
So this point is only referring to the first value of the 3-value syntax? That it must be Keyword.

**Comment by Anurella** [comment]
> Thank you for the comment: [Anurella]
> 
> So this point is only referring to the first value of the 3-value syntax? That it must be Keyword.

Yes in the context of the 3-value syntax or 4-value syntax, your first value must be a keyword.
