### ISSUE TITLE
Issue with "PannerNode.setOrientation()": What is the suggested replacement?

### ISSUE THREAD

**Issue by erikthysell** [mdn/content#11690]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/setOrientation

#### What information was incorrect, unhelpful, or incomplete?
The page states that the method is deprecated and should not be used.

#### Specific section or headline?
Right below heading

#### What did you expect to see?
A suggestion for work-around/replacement. I.e.:
`It is equivalent to setting orientationX.value, orientationY.value, and orientationZ.value attribute directly, with the x, y and z parameters, respectively.`
(from [this](https://www.w3.org/TR/webaudio/#PannerNode))

#### Did you test this? If so, how?
It currently works in javascript but what about the future?? How am I to handle it then?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/pannernode/setorientation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/setOrientation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/pannernode/setorientation/index.md
* Last commit: https://github.com/mdn/content/commit/aee2b07d51c5f768f0a89b2b506b36d09f8dbdaa
* Document last modified: 2021-11-17T14:48:40.000Z

</details>

**Comment by erikthysell** [comment]
Same goes for [setPosition](https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/setPosition)

and [dopplerFactor](https://developer.mozilla.org/en-US/docs/Web/API/AudioListener/dopplerFactor)

**Comment by sideshowbarker** [comment]
@padenot Is there any suggested replacement for the old `setOrientation()` and `setPosition()` methods of `PannerNode`? Or for the old `dopplerFactor` property of `AudioListener`?

**Comment by teoli2003** [comment]
From the spec:
![Capture d’écran 2022-08-04 à 08 47 58](https://user-images.githubusercontent.com/1466293/182781868-78c055fe-2e3b-414b-bf71-c63f36200235.png)
![Capture d’écran 2022-08-04 à 08 48 07](https://user-images.githubusercontent.com/1466293/182781875-cd182387-1b4b-4be6-aad0-181b98937a16.png)

**Comment by sideshowbarker** [comment]
@erikthysell Thanks for raising this — I’ve opened #19142 with updates to the docs that suggest replacements.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
