### ISSUE TITLE
Issue with "HTML basics": Missing a short explanation about HTML comments

### ISSUE THREAD

**Issue by glmvc** [mdn/content#11692]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics

#### What information was incorrect, unhelpful, or incomplete?

In my opinion, a brief *explanation of HTML comments*, similar to the [CSS basics page](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics#fonts_and_text) & [JavaScript basics page](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics#comments), would be useful for the consistency of the guide.

#### Specific section or headline?

I would suggest *adding a note* like the one on the [CSS basics page](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics#fonts_and_text). There, for the first time in a code example, something was explained with a comment. After that followed the explanation in a note.

But it would also be possible to create a separate short section, as it is the case in the [Introduction to HTML module](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#html_comments) anyway.

#### What did you expect to see?

I was just missing a *short explanation* about HTML comments, because I think it belong to the basics.
Or why are it's explained in CSS basics and Javascript basics, but not in HTML basics?

#### Did you test this? If so, how?
I could have made the edit myself with some more practice and research, but I don't know if the change is justified at all.
I apologize for any inconvenience, as I am still a beginner.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/html_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/html_basics/index.md
* Last commit: https://github.com/mdn/content/commit/e444d247f41c943eff6906704186b0530032fe99
* Document last modified: 2021-12-16T14:38:37.000Z

</details>

**Comment by sideshowbarker** [comment]
> I could have made the edit myself with some more practice and research, but I don't know if the change is justified at all.

It’s justified — so I’d suggest you go ahead and make create a pull request with a change that adds the short explanation described in the issue description here. I think it would be a welcome improvement.

**Comment by glmvc** [comment]
Thanks for the answer, I will do it this way 👍
