### ISSUE TITLE
Issue with "Test Your Skills: Fundamental layout comprehension": (short summary here please)

### ISSUE THREAD

**Issue by web-sudo** [mdn/content#11704]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Fundamental_Layout_Comprehension

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/css_layout/fundamental_layout_comprehension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Fundamental_Layout_Comprehension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/fundamental_layout_comprehension/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by hamishwillee** [comment]
Closing. No information provided that would allow action to be taken.
