### ISSUE TITLE
CSSRule page is missing

### ISSUE THREAD

**Issue by thanhminhmr** [mdn/content#1171]
The [CSSRule](https://developer.mozilla.org/en-US/DOM/cssRule) page is refered to in [CSSRuleList](https://developer.mozilla.org/en-US/docs/Web/API/CSSRuleList) but is currently missing. Is this an out of date link?

https://developer.mozilla.org/en-US/docs/Web/API/CSSRuleList
https://developer.mozilla.org/en-US/DOM/cssRule

**Comment by chrisdavidmills** [comment]
Hi @thanhminhmr , and thanks for reporting this.

You are right that the link was out of date. I've updated it to the correct link, and made a couple more small fixes.

See https://github.com/mdn/content/commit/26f603b7df60f19c5ad0ac1402a5c887488dc66e for the fix.
