### ISSUE TITLE
Issue with "Marking up a letter": This page cites CSS on HTML fundamentals that was not yet aproached

### ISSUE THREAD

**Issue by flaviomorgado** [mdn/content#11728]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter

#### What information was incorrect, unhelpful, or incomplete?
This page cites CSS on HTML fundamentals that was not yet aproached

#### What did you expect to see?
A primer about CSS must be inserted between the lessons to avoid such knowledge gap.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/marking_up_a_letter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/marking_up_a_letter/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks @flaviomorgado for reporting this. The page notes:

| You don't need to know any CSS to do this assignment.  You just need to put the provided CSS inside an HTML element.

So the only pre-requisite around CSS is to include it. Does it deviate from this?

**Comment by flaviomorgado** [comment]
Thanks for your reply.
The HTML course is excellent.
But I suggest again to put some CSS information before use it on the
lessons.,
Anyway, congratulations for the excelente material you disposed.
Best Regards,
Flavio Morgado

Em dom., 9 de jan. de 2022 às 07:38, Himanshu ***@***.***>
escreveu:

**Comment by Josh-Cena** [comment]
Closing per https://github.com/mdn/content/issues/11728#issuecomment-1008272215; we need to introduce CSS to make meaningful HTML, and we definitely need HTML to use CSS. This is a deadlock situation, and asking you to embed an already-prepared stylesheet seems like the minimum that we can require.
