### ISSUE TITLE
Permalink script is overwriting headings which have links

### ISSUE THREAD

**Issue by rachelandrew** [mdn/content#1172]
In investigating #1170 I discovered that the links were correct in the headings, however they were being overwritten by a permalink.

I have fixed the issue for this piece of content in https://github.com/mdn/content/pull/1170 by moving the links, however I imagine it is not the only place to have this pattern in use.

**Comment by sideshowbarker** [comment]
@rachelandrew Do you know if this is still happening? (I think a lot has changed in the relevant Yari handling over the last 5 months)

**Comment by himanshugarg** [comment]
>  they were being overwritten by a permalink.

These pages have links inside of headings. Sorry, the issue is not obvious to me for example in [this page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Working_with_the_Tabs_API). Should these also be converted to definition lists?

```bash
$ grep -rl '<h.*<a' 
files/en-us/tools/performance/scenarios/animating_css_properties/transform-timeline.png
files/en-us/mozilla/add-ons/webextensions/working_with_the_tabs_api/index.html
files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.html
files/en-us/mozilla/projects/nss/ssl_functions/sslintro/index.html
files/en-us/mozilla/projects/nss/ssl_functions/ssltyp/index.html
files/en-us/mozilla/projects/nss/ssl_functions/sslkey/index.html
files/en-us/mozilla/projects/nss/ssl_functions/pkfnc/index.html
files/en-us/mozilla/projects/nss/ssl_functions/old_ssl_reference/index.html
files/en-us/mozilla/projects/nss/ssl_functions/sslerr/index.html
files/en-us/mozilla/projects/nss/ssl_functions/gtstd/index.html
files/en-us/mozilla/projects/nss/ssl_functions/sslfnc/index.html
files/en-us/mozilla/projects/nss/ssl_functions/sslcrt/index.html
files/en-us/mozilla/projects/nss/nss_3.12.6_release_notes/index.html
files/en-us/mozilla/projects/nss/nss_tech_notes/nss_tech_note5/index.html
files/en-us/mozilla/projects/nss/nss_tech_notes/nss_tech_note2/index.html
files/en-us/mozilla/projects/nss/tools/nss_tools_pk12util/index.html
files/en-us/mozilla/projects/nss/tools/nss_tools_modutil/index.html
files/en-us/mozilla/projects/nss/tools/nss_tools_ssltap/index.html
files/en-us/mozilla/projects/nss/tools/nss_tools_cmsutil/index.html
files/en-us/mozilla/projects/nss/tools/nss_tools_crlutil/index.html
files/en-us/mozilla/projects/nss/nss_3.12.9_release_notes/index.html
files/en-us/mozilla/projects/nss/jss/jss_provider_notes/index.html
files/en-us/mozilla/projects/nss/jss/using_jss/index.html
files/en-us/mozilla/projects/nss/nss_3.11.10_release_notes.html/index.html
files/en-us/mozilla/projects/nss/faq/index.html
files/en-us/web/css/_colon_host-context()/index.md
files/en-us/web/css/_colon_host()/index.md
files/en-us/web/css/_colon_host/index.md
files/en-us/web/accessibility/aria/roles/feed_role/index.html
files/en-us/web/accessibility/seizure_disorders/index.html
files/en-us/web/xslt/transforming_xml_with_xslt/index.html
files/en-us/web/xslt/transforming_xml_with_xslt/the_netscape_xslt_xpath_reference/index.html
files/en-us/web/webdriver/capabilities/firefoxoptions/index.html
files/en-us/web/svg/attribute/index.html
```

**Comment by teoli2003** [comment]
> Sorry, the issue is not obvious to me for example in [this page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Working_with_the_Tabs_API). Should these also be converted to definition lists?

In this case, I would move the link from the heading to the same name in the first sentence that follows.

> ```shell
> files/en-us/mozilla/projects/nss/ssl_functions/sslintro/index.html
> …
> ```
Don't bother to fix NSS pages: these files will be deleted soon from MDN. We can live with them not being fixed for some time.

**Comment by teoli2003** [comment]
Interestingly, the flaws dashboard gives a different list (I cut the NSS pages out for readability). Maybe the other are `<h4>`
<img width="963" alt="Screenshot 2021-09-10 at 17 54 16" src="https://user-images.githubusercontent.com/1466293/132882231-10cbad5b-90f8-4236-84e4-48d20ad0bdf0.png">
