### ISSUE TITLE
Issue with "<input type="file">": file size with customary prefixes vs decimal prefixes

### ISSUE THREAD

**Issue by thisjeremiah** [mdn/content#11727]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

#### What information was incorrect, unhelpful, or incomplete?

The file size is formatted using the binary (IEC) interpretation of the `file.size` value, when it should be using the decimal (SI) interpretation? 

#### Specific section or headline?

The `returnFileSize` function and the example do not return the proper file size.

#### What did you expect to see?

I expect to see the `returnFileSize` function use the decimal interpretation of `file.size`.

#### Did you test this? If so, how?

Yes, I can test a file using the example and see a clear mismatch between the displayed value (4.6 MB) and the value shown in my file system (4.8 MB).

![Screen Shot 2022-01-04 at 9 42 51 AM](https://user-images.githubusercontent.com/7308192/148101310-4b8b3144-be5a-44c4-a389-f255d3597541.jpg)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/file`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/file/index.md
* Last commit: https://github.com/mdn/content/commit/c1b43e501c95830a3f27758eec37b5773561db45
* Document last modified: 2021-11-10T01:42:02.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
Unfortunately, a majority of people do not use, understand, or even know about IEC binary prefixes. I think the choice ([customary binary prefixes](https://en.wikipedia.org/wiki/Binary_prefix) vs [decimal prefixes](https://en.wikipedia.org/wiki/Metric_prefix)) depends on the use case and the expected audience. The example code might be used to indicate the cumulative file size when there is a maximum limit per upload, in which case the cumulative file size displayed should use the same prefixes as the indicated maximum. Given that different operating systems display file sizes using different prefixes, websites expecting a majority of users with a particular operating system will probably choose the same prefixes as used by the operating system.

The MDN examples are not a library, so I think the `returnFileSize` function doesn't need to change. But, one option would be to present alternative variants with short comments explaining the difference.

```javascript

/* This variant formats file sizes using customary binary prefixes. */
function returnFileSize(number) {
  if (number < 1024) {
    return number + 'bytes';
  } else if (number >= 1024 && number < 1048576) {
    return (number / 1024).toFixed(1) + 'KB'; // note: upper-case 'K'
  } else if (number >= 1048576 && number < 1073741824) {
    return (number / 1048576).toFixed(1) + 'MB';
  } else {
    return (number / 1073741824).toFixed(1) + 'GB';
  }
}

/* This variant formats file sizes using IEC binary prefixes (like Ubuntu since version 10.10). */
function returnFileSize(number) {
  if (number < 1024) {
    return number + 'bytes';
  } else if (number >= 1024 && number < 1048576) {
    return (number / 1024).toFixed(1) + 'KiB'; // note: upper-case 'K'
  } else if (number >= 1048576 && number < 1073741824) {
    return (number / 1048576).toFixed(1) + 'MiB';
  } else {
    return (number / 1073741824).toFixed(1) + 'GiB';
  }
}

/* This variant formats file sizes using SI decimal prefixes (like macOS since version 10.6). */
function returnFileSize(number) {
  if (number < 1000) {
    return number + 'bytes';
  } else if (number >= 1000 && number < 1000000) {
    return (number / 1000).toFixed(1) + 'kB'; // note: lower-case 'k'
  } else if (number >= 1000000 && number < 1000000000) {
    return (number / 1000000).toFixed(1) + 'MB';
  } else {
    return (number / 1000000000).toFixed(1) + 'GB';
  }
}
```

**Comment by thisjeremiah** [comment]
Thanks for the detailed explanation!

The maximum file size limit issue was actually the problem I was working on. I ended up finding this article and got confused by the default approach mismatching with the macos file system labels.

Based on the fact that there is no consistency across operating systems, it doesn't seem like there is proper fix, but some clarification might help future readers.

Perhaps simply defaulting to IEC (Ki, Mi, Gi, Ti) instead of the legacy (K,M,G,T) would help distinguish them?

**Comment by Andrew-Cottrell** [comment]
A pragmatic fix for the maximum file size use case is the following

```javascript
function returnFileSize(number) {
  var platform = navigator.platform; // deprecated, but Safari & Firefox haven't implemented `userAgentData`
  if (/(mac|iphone|ipod|ipad|pike)/i.test(platform)) {
    return returnFileSizeDecimal(number); // using SI decimal prefixes
  } else {
    return returnFileSizeCustomary(number); // using customary binary prefixes
  }
}
```

If used, this function should be called to format _both_ the maximum file size limit _and_ the cumulative file size.

---
Aside: this issue's title currently has a typo ("EIC" rather than "IEC"). I suggest the title be changed to
> Issue with "\<input type="file"\>": file size with binary prefixes vs decimal prefixes

**Comment by thisjeremiah** [comment]
That seems like a good approach!

Yet another quirk to consider is that Finder on macOS uses **KB** instead of **kB** 🙃

![Screen Shot 2022-01-07 at 9 19 27 AM](https://user-images.githubusercontent.com/7308192/148581771-3465c39b-418d-4089-b41a-647921254619.jpg)


(I'm running macOS Monterey 12.1)

**Comment by Andrew-Cottrell** [comment]
> Yet another quirk to consider is that Finder on macOS uses **KB** instead of **kB** :upside_down_face:

Perhaps we could say macOS is using "_customary decimal prefixes_" rather than "_SI decimal prefixes_" :astonished:
