### ISSUE TITLE
Issue with "Window: beforeunload event": remove obsolete mention about preventDefault

### ISSUE THREAD

**Issue by NagayamaToshiaki** [mdn/content#11736]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

#### What information was incorrect, unhelpful, or incomplete?
According to the page,

> However note that not all browsers support this method (preventDefault), and some instead require the event handler to implement one of two legacy methods:
> 
> - assigning a string to the event's returnValue property
> - returning a string from the event handler.

But now all active browsers including IE supports preventDefault, so this section does not make sense.

#### Specific section or headline?
The fourth paragraph of the first section.

#### What did you expect to see?
Remove the paragraph and the list.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/beforeunload_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/beforeunload_event/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #11768 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
