### ISSUE TITLE
Issue with "HTMLImageElement.sizes": Image doesn't show in example

### ISSUE THREAD

**Issue by iJungleboy** [mdn/content#11744]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes

#### What did you expect to see?

See image - the picture in the demo isn't working:

![image](https://user-images.githubusercontent.com/5321186/148181905-b5ec8cc3-2bd6-4a81-955f-d6fe5a67a9cf.png)

#### Did you test this? If so, how?

Normal browser - latest Chrome

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlimageelement/sizes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlimageelement/sizes/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
https://media.prod.mdn.mozit.cloud/attachments/2019/09/04/16870/fbc7b094f3a874aeff5afdd5916239e5/new-york-skyline-wide.jpg has the image, but in the code there are paths to other missing images.
