### ISSUE TITLE
Issue with "HTMLStyleElement": (false claim about object class returned by sheet property)

### ISSUE THREAD

**Issue by jackdeguest** [mdn/content#11752]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLStyleElement

#### What information was incorrect, unhelpful, or incomplete?
The documentation states wrongly that the `sheet` property returns a `StyleSheet` object. However, given the following html and code, `sheet` would return a `CSSStyleSheet`

```html
<!DOCTYPE html>
<html>
  <head>
    <style href="demo.css"></style>
  </head>
  <body></body>
</html>
```

```js
let sheet = document.getElementsByTagName('style')[0].sheet;
// sheet is a CSSStyleSheet object
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlstyleelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLStyleElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlstyleelement/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by AnilSeervi** [comment]
Thanks @jackdeguest.
Opened #11760 with proper return type for 
```js
document.getElementsByTagName('style')[0].sheet // CSSStyleSheet
```
