### ISSUE TITLE
Issue with "Array.prototype.flatMap()": Note is perhaps misleading

### ISSUE THREAD

**Issue by hildjj** [mdn/content#11763]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

#### What information was incorrect, unhelpful, or incomplete?

> Note, however, that this is inefficient and should be avoided for large arrays: in each iteration, it creates a new temporary array that must be garbage-collected, and it copies elements from the current accumulator array into a new array instead of just adding the new elements to the existing array. 

This text is somewhat misleading, I think.  The version that uses `reduce` directly above does have this problem, but the `flatMap` version does not.  

References:
- [Specification](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-flattenintoarray)
- [SpiderMonkey Source](https://searchfox.org/mozilla-central/source/js/src/builtin/Array.js#1140)

#### Specific section or headline?

Description/Alternative

#### What did you expect to see?

A small modification to the text will make it more clear, and motivate the reason for `flatMap` existing.

> Note, however, that the reduce approach is more inefficient than the flatMap approach and should be avoided for large arrays: in each iteration, it creates a new temporary array that must be garbage-collected, and it copies elements from the current accumulator array into a new array instead of just adding the new elements to the existing array.  The flatMap version only creates a single output array.

#### Did you test this? If so, how?

A benchmark [here](https://jsbench.me/z1ky1v4qh6/1), Firefox 95.0.2, MacOS 12.1 shows:

```js
const arr = Array.from({length: 10000}, (_,i) => i);
arr.flatMap(x => [x, x * 2]); // Case 1
arr.reduce((acc, x) => acc.concat([x, x * 2]), []); // Case 2
```

Case 1: 3336.05 ops/s ± 0.78%
Case 2: 2 ops/s ± 0.98%

With similar results on Chrome and Safari.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/flatmap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/flatmap/index.md
* Last commit: https://github.com/mdn/content/commit/de8ab08ecb27493bbf35e7224cbe5bbbc71a187b
* Document last modified: 2021-12-10T04:34:51.000Z

</details>

**Comment by 99991** [comment]
Both cases are slow, but case 2 is especially bad since it has quadratic complexity.

It would be about twice as fast to not create intermediate arrays at all

```javascript
arr.reduce((acc, x) => { acc.push(x); acc.push(x * 2); return acc; }, [])
```

or over 3 times as fast to fix the size of the resulting array beforehand:

```javascript
var n = arr.length;
var acc = new Array(n * 2);
for (var i = 0; i < n; i++){
	var x = arr[i];
	acc[i * 2] = x;
	acc[i * 2 + 1] = x * 2;
}
```

**Comment by hildjj** [comment]
Agree with @99991 and I've updated the [jsbench](https://jsbench.me/z1ky1v4qh6/1) to have the other approaches.  I'm happy to add some more text to the PR to capture this.

**Comment by sideshowbarker** [comment]
> Agree with @99991 and I've updated the [jsbench](https://jsbench.me/z1ky1v4qh6/1) to have the other approaches. I'm happy to add some more text to the PR to capture this.

That’d be great. But have you raised an actual PR yet? I see that patch at https://github.com/hildjj/content/commit/bd24876e866476e525ab90fd116cbc45e4029139 but I haven’t yet seen a PR.

**Comment by hildjj** [comment]
No, I had not actually sent a PR.  Fixed up the text, and submitted one.
