### ISSUE TITLE
Issue with "position": Move "Types of positioning" explanation to before position values explanation.

### ISSUE THREAD

**Issue by berkleebytez** [mdn/content#11766]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/position

#### What information was incorrect, unhelpful, or incomplete?
The definitions for the position values use the word "positioned" (adjective, not verb) before it is actually defined in the document. Example: 

--------------------------
_absolute_
The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned relative to its closest positioned ancestor
--------------------------

If the reader is going through this document line by line, the word positioned in "its closest positioned ancestor" has not yet been defined. Readers could get confused or come to false conclusions about the meaning of this statement. Also, it is worth noting that the absolute position definition can be scrolled into view without the "Types of positioning" being in view, further facilitating confusion.

#### Specific section or headline?
Position values and "types of positioning"

#### What did you expect to see?
The meaning of the adjective "positioned" ("its closest positioned ancestor") is stated after the position values are explained. Since the "Types of positioning" block is necessary to understand the position values, it should go before the position values are explained. Or, there should be some sort of note before the position values definitions pointing the reader to the definition of "positioned" in the "Types of positioning block".

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/position`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/position
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/position/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by OnkarRuikar** [comment]
I think we simply need to link the "positioned" word to its definitions:
> It is positioned relative to its closest [positioned](https://developer.mozilla.org/en-US/docs/Web/CSS/position#types_of_positioning) ancestor...

***
Adding the definition to [Glossary](https://developer.mozilla.org/en-US/docs/Glossary) and linking that location would be nice.
