### ISSUE TITLE
Duplicate user agents

### ISSUE THREAD

**Issue by hiw-homepage** [mdn/content#11776]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

#### What information was incorrect, unhelpful, or incomplete?
Rendering engine table

#### Specific section or headline?
Rendering engine

#### What did you expect to see?
Both WebKit and Blink apply to Chrome on Linux.

#### Did you test this? If so, how?
I tried it on Chrome OS and Ubuntu.

By Google Translate
Japanese → English

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/browser_detection_using_the_user_agent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/browser_detection_using_the_user_agent/index.md
* Last commit: https://github.com/mdn/content/commit/4458708ee8aa2e7cb1e1db8bf83bce8798578bdf
* Document last modified: 2021-10-20T17:36:16.000Z

</details>

**Comment by sideshowbarker** [comment]
Can you elaborate on what exactly _“Both WebKit and Blink apply to Chrome on Linux”_? What is meant by “apply”?

**Comment by hiw-homepage** [comment]
> Can you elaborate on what exactly _“Both WebKit and Blink apply to Chrome on Linux”_? What is meant by “apply”?

I recognize Chrome as Blink, but WebKit has a notation at the same time. I think this is because it's a fork of WebKit, but if there's a way to distinguish between the two, please list them on the page.

[Actual display](https://drive.google.com/file/d/1KP8og_lHU3Co3eLs25FINe8z452DZX9T/view?usp=sharing)
[MDN table](https://drive.google.com/file/d/11U5qYErJJET4PLekYbCYBw4Iu4Xn2X8U/view?usp=sharing)

By Google Translate
Japanese → English

**Comment by hamishwillee** [comment]
I think you're saying that you can't differentiate the WebKit renderer, because the "AppleWebKit" string is present in Chrome, Opera, Safari etc UA string, as shown here:  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

Is that correct? 

If so, you're right, I don't think you can differentiate webkit from this table. You would have to find some other way - perhaps the OS string:
![image](https://user-images.githubusercontent.com/5368500/148477028-c169e150-a5a3-4b76-969a-bd6d4ee94848.png)

Eventually you'll be able to get more precise information from https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API

**Comment by hiw-homepage** [comment]
> I think you're saying that you can't differentiate the WebKit renderer, because the "AppleWebKit" string is present in Chrome, Opera, Safari etc UA string, as shown here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
> 
> Is that correct?
> 
> If so, you're right, I don't think you can differentiate webkit from this table. You would have to find some other way - perhaps the OS string: ![image](https://user-images.githubusercontent.com/5368500/148477028-c169e150-a5a3-4b76-969a-bd6d4ee94848.png)
> 
> Eventually you'll be able to get more precise information from https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API

thank you. The browser has been correctly determined.

**Comment by hiw-homepage** [comment]
> 

thank you. The browser has been correctly determined.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/11776#issuecomment-1007146905

**Comment by hamishwillee** [comment]
@sideshowbarker Thanks for closing. Before we walk away, do you think it worth a quick update to the https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent to ...

- Just call it "Browser detection" or "Browser/user-agent identification". This is technically "Browser detection using the user agent **string**" but it covers feature detection too. 
- This would be a good place to add a ntoe about https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API - this is much better than using the UA string if it is supported, in particular for chromiums, in which it is supported.

Do you know if the rest of the doc is reasonable? In particular it states pretty clearly that it is good not to customise served pages for the user agent if at all possible - but there wouldn't be UA hints if that was really the case - there are lots of reasons you might want to.

**Comment by sideshowbarker** [comment]
> @sideshowbarker Thanks for closing. Before we walk away, do you think it worth a quick update to the https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent to ...
> 
> - Just call it "Browser detection" or "Browser/user-agent identification". This is technically "Browser detection using the user agent **string**" but it covers feature detection too. 
> - This would be a good place to add a ntoe about https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API - this is much better than using the UA string if it is supported, in particular for chromiums, in which it is supported.

That all sounds fine to me


> Do you know if the rest of the doc is reasonable? In particular it states pretty clearly that it is good not to customise served pages for the user agent if at all possible - but there wouldn't be UA hints if that was really the case - there are lots of reasons you might want to.

I think the doc overall is reasonable
