### ISSUE TITLE
Issue with "Intl.NumberFormat": (problem when having a number larger than 17 digits)

### ISSUE THREAD

**Issue by GanesanDinesh** [mdn/content#11777]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

Hello,

when converting a number input : 1234567891234567891 to INR currency as below example , we can see a discrepancy below occuring for numbers greater than 17 digits.

NOTE:occurs for all currencies

expected :
 
One Crore Thousand Crore twenty-Three Lakh Thousand Crore forty-Five Thousand Thousand Crore Six hundred Seventy-Eight Thousand Crore Ninety-One Hundred Crore twenty-Three Crore forty-Five Lakh Sixty-Seven Thousand Eight hundred Ninety-One Indian Rupeess

actual :

One Crore Thousand Crore twenty-Three Lakh Thousand Crore forty-Five Thousand Thousand Crore Six hundred Seventy-Eight Thousand Crore Ninety-One Hundred Crore twenty-Three Crore forty-Five Lakh Sixty-Eight Thousand Indian Rupeess Zero Paises

Example test as  below:

const number = 1234567891234567891;

console.log(new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(number));
// expected output: "123.456,79 €"

// the Japanese yen doesn't use a minor unit
console.log(new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(number));
// expected output: "￥123,457"

// limit to three significant digits
console.log(new Intl.NumberFormat('en-IN', { maximumSignificantDigits: 3 }).format(number));
// expected output: "1,23,000"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/index.md
* Last commit: https://github.com/mdn/content/commit/84ff708d39cd36b1b07e848dc1ad4260c2ff3c1a
* Document last modified: 2021-08-20T14:59:36.000Z

</details>

**Comment by Josh-Cena** [comment]
This is because `1234567891234567891 > Number.MAX_SAFE_INTEGER`, making it suffer from loss of precision. `1234567891234567891 === 1234567891234568000` is true.

I don't think it's feasible for us to mention loss of precision everywhere, since it's a language limitation, not the API's. The literal doesn't represent what one thinks it does.
