### ISSUE TITLE
Issue with "<input type="checkbox">": inconsistent/problematic syntax

### ISSUE THREAD

**Issue by MalikRumi** [mdn/content#11798]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

#### What information was incorrect, unhelpful, or incomplete?
The sequence / syntax of 'label' and 'input' on this page is the reverse of the sequence on this page:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#examples

#### Specific section or headline?
Demo

#### What did you expect to see?
Consistency

#### Did you test this? If so, how?
I am using PyCharm, and it did not like treating the label and the input as separate tags. Rather, it was only happy when the input was **inside** the label, like this:

`<li><label for="thousand_island_dressing">Thousand Island Dressing"
<input type="checkbox" name="thousand_island_dressing"></label></li>`

I don't know if the fact that I am using a list and your example used a div makes a difference. However, I do know that the Django docs example is different from both yours and PyCharm's:

`<p><label for="id_age">Age?**</label>** <input id="id_age" name="age" type="number" required></p>`

https://docs.djangoproject.com/en/3.2/ref/forms/fields/#label-suffix

Notice that here, 

- they are separate tags, not nested
- the closing label is allowed before input
- PyCharm complained about this, too. 

So, like I said, if sequence didn't matter, I would not have bothered to post this. But apparently it does. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/checkbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/checkbox/index.md
* Last commit: https://github.com/mdn/content/commit/1d1a5b8232bbdb7583b49374f59eb3d15435e3d6
* Document last modified: 2021-11-17T22:22:02.000Z

</details>

**Comment by sideshowbarker** [comment]
What is the exact error/warning message that Pycharm reports?

> So, like I said, if sequence didn't matter, I would not have bothered to post this. But apparently it does.

Can you be more specific about how it matters?

Do you just mean that it matters to Pycharm?

Or do you mean it affects how the label is displayed?

> The sequence / syntax of 'label' and 'input' on this page is the reverse of the sequence on this page:
> [developer.mozilla.org/en-US/docs/Web/HTML/Element/form#examples](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#examples)

Exactly which code examples do you mean?

The examples at the top of that page don’t use the `for` attribute. So in that case, the way to associate the `label` with an `input` is make the `input` element a child of the `label`. Right?

The examples later on in that page use `for` attribute. So in that case, there is no need to make the `input` a child of the `label`; instead the `label` can be anywhere at all in the document.

So that all looks fine.

So is the inconsistency that one page has this:

```html
    <label for="name">Enter your name: </label>
    <input type="text" name="name" id="name" required>
```
…while the other has this?

```html
  <input type="checkbox" id="horns" name="horns">
  <label for="horns">Horns</label>
```

…that is, in one case, the `label` element precedes the `input` element, while in the other case the `label` element follows the `input` element?

**Comment by sideshowbarker** [comment]
> I am using PyCharm, and it did not like treating the label and the input as separate tags. Rather, it was only happy when the input was **inside** the label, like this:

If that’s the case, then that’s a bug in Pycharm.

It’s completely valid for the `input` element to not be inside the `label` element — as long as the `label` element has a `for` attribute.

**Comment by MalikRumi** [comment]
> What is the exact error/warning message that Pycharm reports?

Missing associated label

> > So, like I said, if sequence didn't matter, I would not have bothered to post this. But apparently it does.
> Can you be more specific about how it matters?

Sure. Lots of times, you can put together a string of attributes or method calls and the sequence in which you write them does not matter. A good example would be chaining filters in Django:  

> The order of filter() and select_related() chaining isn’t important, https://docs.djangoproject.com/en/4.0/ref/models/querysets/#select-related

> Do you just mean that it matters to Pycharm?

Yes, clearly that's true. But what I mean is that the sequence of operations matters when the first alters state such that the second either won't work, or won't work as expected because it needed or expected the state which the first one received, i.e., before mutation, or a syntax error.
> Or do you mean it affects how the label is displayed?

No. Not talking about that at all.
> > The sequence / syntax of 'label' and 'input' on this page is the reverse of the sequence on this page:
> > [developer.mozilla.org/en-US/docs/Web/HTML/Element/form#examples](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#examples)
> 
> Exactly which code examples do you mean?

I see that you gave more than one response, and in the second you reference the code I am talking about.

> The examples at the top of that page don’t use the `for` attribute. So in that case, the way to associate the `label` with an `input` is make the `input` element a child of the `label`. Right?

Right.
> The examples later on in that page use `for` attribute. So in that case, there is no need to make the `input` a child of the `label`; instead the `label` can be anywhere at all in the document.

> So that all looks fine.
> 
> So is the inconsistency that one page has this:
> 
> ```
>     <label for="name">Enter your name: </label>
>     <input type="text" name="name" id="name" required>
> ```
> 
> …while the other has this?
> 
> ```
>   <input type="checkbox" id="horns" name="horns">
>   <label for="horns">Horns</label>
> ```
> …that is, in one case, the `label` element precedes the `input` element, while in the other case the `label` element 
> follows the `input` element?

Yes. 

>It’s completely valid for the input element to not be inside the label element — as long as the label element has a for >attribute.

Ok. I did not know it was the for attribute that makes the difference. 
Note that PyCharm still complains even with the _for_ attribute:

```
24        <li><label for="apple pie">apple pie</label>
25        <input type="checkbox" name="apple pie"></li>
26        <li><input type="checkbox" name="applesauce"></li>
27        <label for="applesauce">applesauce</label>
```

Lines:
(24)  No complaint
(25) Missing associated label  ( _even though 24 & 25 are wrapped in the same list tag_)
(26) Missing associated label
(27) Element label is not allowed here

But if I do this:

```
26        <li><input type="checkbox" name="applesauce">
27        <label for="applesauce">applesauce</label></li>
```

Now, with 26 and 27 wrapped in the same list tag, PyCharm's warning about label on 27 disappears, but the 'missing associated label' is there for **every** case where input precedes label _even with the for_. (It is a much longer list than I have posted).
FYI, I decided to look this up at W3: 
https://www.w3.org/WAI/WCAG21/Techniques/html/H44
> Note that the label is positioned after input elements of type="checkbox" and type="radio".

Well, thanks, I guess that clears this up for me. I am grateful for the time, because I am always learning something. I don't consider myself a front end person. I'm not closing this issue in case you wanted to add anything.

**Comment by sideshowbarker** [comment]
> Well, thanks, I guess that clears this up for me. I am grateful for the time, because I am always learning something. I don't consider myself a front end person. I'm not closing this issue in case you wanted to add anything.

Thanks — I’ll go ahead and close this since I can’t see that there’s anything to fix in the article.

But I think you might want to consider filing a bug report against Pycharm about that incorrect “Missing associated label” error and the “Element label is not allowed here” error too. Since there aren’t actually any real problems with using the `label` and `input` elements in the way shown in the examples, those spurious Pycharm errors are causing a lot of users to waste time trying to figure out how to fix markup that’s actually perfectly fine already and doesn’t need fixing.
