### ISSUE TITLE
Issue with "Using the Web Speech API": Recognized short word contains a period

### ISSUE THREAD

**Issue by masaki-itagaki** [mdn/content#11797]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API

#### What information was incorrect, unhelpful, or incomplete?
When a short word (e.g. "hello") is recognized, it is followed by a period (e.g. "Hello."). Until about a week or so ago, there was no period included in reco text. 

Locale: "en-US"
Browser: Chrome (also tested in Edge) on Windows 11

#### Specific section or headline?
N/A

#### What did you expect to see?
No period is included for a short text recognition. Again, this has not been an issue till at least a few weeks ago.  

#### Did you test this? If so, how?
This is a function to call the speech reco. 

function Recognize(locale, callback) {                 
  var recognition = new SpeechRecognition();
  recognition.continuous = false;
  recognition.lang = locale;
  recognition.interimResults = false;
  recognition.maxAlternatives = 1;
  recognition.start();
  recognition.onresult = function(event) {
    var recoText = event.results[0][0].transcript;
    callback(recoText);
  }
}

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/web_speech_api/using_the_web_speech_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_speech_api/using_the_web_speech_api/index.md
* Last commit: https://github.com/mdn/content/commit/8bc9a25846c2ecfe4e2c2c2a363fd2208f3a69ae
* Document last modified: 2021-10-13T06:21:42.000Z

</details>

**Comment by hamishwillee** [comment]
I don't understand the issue you are describing. Are you saying that there is an error in this document? If so, which section has incorrect or missing text? Which example doesn't work? Are you saying that the API is inserting a period when it should or shouldn't?

**Comment by sideshowbarker** [comment]
This seems more like something to report through the Chrome bug tracker at https://bugs.chromium.org/p/chromium/issues/entry

**Comment by masaki-itagaki** [comment]
Hi Hamish, Michael

The issue is simple. When you reco "hello", it used to come up as
just "hello", but now it adds a period like "hello.". Michael, I'm not sure
if this is a but of Chrome since it happens also in Edge. You can simply
test it on your end to see if it adds an extra period. Again, this had not
been the case until at least two weeks ago. My test started failing due to
the extra period.

Please let me know if I can further help you to understand this bug.

Thanks

Masaki

**Comment by sideshowbarker** [comment]
> I'm not sure if this is a but of Chrome since it happens also in Edge.

That would be expected, since both Chrome and Edge use the same engine, Blink.

I think you probably want to go ahead and report this at https://bugs.chromium.org/p/chromium/issues/entry as previously suggested. If the resulting discussion there ends up indicating that there’s some problem in the MDN article that we need o fix, then this MDN issue could be revisited at that time.

In the meantime, I’m going ahead and closing this, since I don’t see any specific problem in the MDN article that needs correcting at this point.
