### ISSUE TITLE
Issue with "<linearGradient>": y2 default value 0% vs 100%

### ISSUE THREAD

**Issue by vmatyi** [mdn/content#11793]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/linearGradient

#### What information was incorrect, unhelpful, or incomplete?
y2 Default value: 0%

#### Specific section or headline?
Attributes

#### What did you expect to see?
100%

#### Did you test this? If so, how?
-

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/element/lineargradient`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/linearGradient
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/lineargradient/index.md
* Last commit: https://github.com/mdn/content/commit/bd3f490ef78b600a1435dfe3611a27f3f2fbf4ef
* Document last modified: 2021-09-23T21:22:12.000Z

</details>

**Comment by sideshowbarker** [comment]
At https://svgwg.org/svg2-draft/pservers.html#LinearGradientElementY2Attribute the spec says the default is 0.

Is that incorrect? If so, this should be fixed in the spec too.

**Comment by sideshowbarker** [comment]
Closing for lack of response.
