### ISSUE TITLE
Issue with "Examine and edit the box model": videos unavailable

### ISSUE THREAD

**Issue by glmvc** [mdn/content#11815]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model

#### What information was incorrect, unhelpful, or incomplete?
Two YouTube videos are not available.

#### Specific section or headline?
- [The Box Model view](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model#the_box_model_view)
- [Editing the box model](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model#editing_the_box_model)

#### What did you expect to see?
The videos

#### Did you test this? If so, how?
Videos are not displayed and according to YouTube, the videos are set to private.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/examine_and_edit_the_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/examine_and_edit_the_box_model/index.html
* Last commit: https://github.com/mdn/content/commit/05b71a290b2ab444b23e0f35f619d93203c7e2d8
* Document last modified: 2021-02-02T16:31:29.000Z

</details>

**Comment by sideshowbarker** [comment]
We have #7457 open already for tracking the underlying problem.
