### ISSUE TITLE
Content bug: Notification.requestPermission is highlighted as supported in webworkers but it is not. 🗜️

### ISSUE THREAD

**Issue by samccone** [mdn/content#11824]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission

## Specific page section or heading?

very top of the page (Note: ....)
![image](https://user-images.githubusercontent.com/883126/148585596-6a096865-dcf8-48da-8b30-3e417ca92cb6.png)

## What is the problem?

`requestPermission` is highlighted as supported in webworkers, where it is not.

https://notifications.spec.whatwg.org/#api

```
[Exposed=Window] static Promise<NotificationPermission> requestPermission(optional NotificationPermissionCallback deprecatedCallback);
```

https://searchfox.org/mozilla-central/source/testing/web-platform/tests/interfaces/notifications.idl#11

## What did you expect to see?

a note saying it is _not_ supported

## Did you test this? If so, how?

https://jsfiddle.net/xwfo6m35/7/ example showing it not working

**Comment by wbamberg** [comment]
Thanks for filing!

Note to anyone who might like to fix this: a fix for this would involve:
* deleting `{{AvailableInWorkers}}` from https://github.com/mdn/content/blob/d8b5aac1382f938674f6b0210bf71eef84553478/files/en-us/web/api/notification/requestpermission/index.md?plain=1#L13
* deleting the note at https://github.com/mdn/content/blob/d8b5aac1382f938674f6b0210bf71eef84553478/files/en-us/web/api/notification/requestpermission/index.md?plain=1#L15

**Comment by samccone** [comment]
PR sent! thanks for the pointer @wbamberg

**Comment by sideshowbarker** [comment]
Closed by https://github.com/mdn/content/pull/11866
