### ISSUE TITLE
Issue with "Navigator.onLine": contains pointer to outdated info

### ISSUE THREAD

**Issue by chhotii-alex** [mdn/content#11821]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine

#### What information was incorrect, unhelpful, or incomplete?

This article contains a recommendation to look at 'HTML5 Rocks article, Working Off the Grid'. However, the "Working of the Grid" article is clearly out of date, because it starts off by recommending that developers take a look at applicationCache. But applicationCache is deprecated. I am looking for updated way to deal with intermittent connectivity, and make the argument to my colleagues that we replace come code that uses applicationCache. This MDN article is not helping in that effort.

#### Specific section or headline?

Third paragraph below the main header "Navigator.onLine"

#### What did you expect to see?

At least omit the sentence "To learn more, see the HTML5 Rocks article, Working Off the Grid." If some of the information in Working off the Grid is still useful/relevant, perhaps someone could author a replacement.

#### Did you test this? If so, how?

I've debugged code that uses window.applicationCache in Google Chrome and it does not work the way it used to when first developed, because the value of window.applicationCache is undefined.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/navigator/online`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/online/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve opened #11823 with a fix.
