### ISSUE TITLE
There is a fairly lengthy file tree that has been moved (I presume), I wish you had put in some 301 and 302 pages

### ISSUE THREAD

**Issue by jeffsilverm** [mdn/content#11849]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide

#### What information was incorrect, unhelpful, or incomplete?
The first hit from duckduckgo when given the search string "mozilla linux preparation" is
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_build/Linux_and_MacOS_build_preparation which could not be found (404).  I originally got to this from the build instructions for bluegriffon, which has broken for some inexplicable reason.  The instructions at https://github.com/therealglazou/bluegriffon#readme point to https://developer.mozilla.org/En/Developer_Guide/Build_Instructions/Linux_Prerequisites

Searching for "linux Mac build preparation" using the search textbox on the page https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_build/Linux_and_MacOS_build_preparation yields nothing useful.

Searching for "install the environment to build mozilla" brings me to  [Building Firefox On Linux](https://firefox-source-docs.mozilla.org/setup/linux_build.html).  It isn't clear that this is what I need but I will start there.

#### What did you expect to see?
I expected to find documentation on how to build Mozilla on Linux and Mac OS X.  Failing that, I would like to a page with a 301 or 302 redirect to where this information is.  Failing that, I'd like to have the search engine find it.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. I can't fix these generally, but I've created redirects for the specific links you identified in https://github.com/mdn/content/pull/11869 and also improved that entry point so it is more obvious what the developer guide contains.

**Comment by jeffsilverm** [comment]
Thank you,

Jeff
