### ISSUE TITLE
Issue with "Window.innerHeight": interactive demo missing

### ISSUE THREAD

**Issue by Toscan0** [mdn/content#11895]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight

> **_NOTE:_**  This a minor bug, more like a remider

#### What information was incorrect, unhelpful, or incomplete?
In the Assuming a frameset there is a "FIXME: link to an interactive demo here"

#### Specific section or headline?
Assuming a frameset
https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight#assuming_a_frameset 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/innerheight`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/innerheight/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by AnilSeervi** [comment]
It can be linked to the example at https://github.com/mdn/dom-examples/pull/86 once it gets approved and merged.
