### ISSUE TITLE
Issue with "Window.isSecureContext": …

### ISSUE THREAD

**Issue by domenic** [mdn/content#1192]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/isSecureContext

#### What information was incorrect, unhelpful, or incomplete?

- This API does not exist only on Window. It's on WorkerGlobalScope as well.

- This API is no longer specified in the Secure Contexts specification. It's specified in https://html.spec.whatwg.org/#dom-issecurecontext

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/issecurecontext`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/isSecureContext
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/window/issecurecontext/index.html
* Report started: 2021-01-11T16:46:56.218Z

</details>

**Comment by sideshowbarker** [comment]
Raised https://github.com/mdn/content/pull/1228

**Comment by Elchi3** [comment]
Yes, I think we can fold this issue into https://github.com/mdn/content/issues/2427.

**Comment by himanshugarg** [comment]
>    This API does not exist only on Window. It's on WorkerGlobalScope as well.

The page has now moved to https://developer.mozilla.org/en-US/docs/Web/API/isSecureContext so this is probably handled.

> This API is no longer specified in the Secure Contexts specification. It's specified in https://html.spec.whatwg.org/#dom-issecurecontext

What is the change, if any, required to deal with this?

**Comment by teoli2003** [comment]
I think this is fixed too. Feel free to reopen if I'm mistaken.
