### ISSUE TITLE
Issue with "Entity header": …

### ISSUE THREAD

**Issue by fromA-Z** [mdn/content#1193]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Entity_header

#### What information was incorrect, unhelpful, or incomplete?
All information seems correct but second `div.notecard.note` is empty 

#### Specific section or headline?
The second `div.notecard.note` is empty 

#### What did you expect to see?
Content in the second `div.notecard.note`

#### Did you test this? If so, how?
I checked the source, nothing to see there

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/entity_header`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Entity_header
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/glossary/entity_header/index.html
* Report started: 2021-01-11T19:24:16.016Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this. Looks like this is an empty notecard that shouldn't be there, so I've just removed it — see https://github.com/mdn/content/commit/c79fda815028e957dc90e939d34ce98cd083c655
