### ISSUE TITLE
Issue with "Navigator.platform": premature recommendation to move to NavigatorUAData.platform

### ISSUE THREAD

**Issue by alexmiddeleer** [mdn/content#11934]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform

#### What information was incorrect, unhelpful, or incomplete?
It's unhelpful to recommend NavigatorUAData.platform when it is not supported by several major browsers yet. At least without a caveat or suggested polyfill.

#### Specific section or headline?
>Note: The recommended alternative to this property is NavigatorUAData.platform, which is returned from Navigator.userAgentData.

#### What did you expect to see?
The following would be better. Best would be some sort of polyfill or other recommendation for adopting this new approach.
>Note: The recommended alternative to this property is NavigatorUAData.platform, which is returned from Navigator.userAgentData. However, this property is not yet supported by some major browsers, and is still in the draft phase.

#### Did you test this? If so, how?
These two pages support my statement that the recommended alternative is still a draft and not yet supported by some major browsers.
I looked at https://wicg.github.io/ua-client-hints/#dom-navigatoruadata-platform and https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/platform

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/navigator/platform`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/platform/index.md
* Last commit: https://github.com/mdn/content/commit/45042595c38501cedb99e17e6b2d98d0451b7338
* Document last modified: 2021-10-21T23:35:07.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve opened #12017 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
