### ISSUE TITLE
Issue with "Array.prototype.sort()": is the compare function a callback function?

### ISSUE THREAD

**Issue by GhbSmwc** [mdn/content#11940]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

#### What information was incorrect, unhelpful, or incomplete?
I was wondering if the compare function using array.sort is a callbackfunction

#### Specific section or headline?
Anywhere it says `compareFn`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/sort`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/sort/index.md
* Last commit: https://github.com/mdn/content/commit/87b0d3e829bc706ddad9cb8b824f0abfc8f60f7e
* Document last modified: 2022-01-04T18:35:05.000Z

</details>

**Comment by AnilSeervi** [comment]
Yes
`compareFn` is a callback function with two `args`
