### ISSUE TITLE
Node database tutorial

### ISSUE THREAD

**Issue by libingqin** [mdn/content#11948]
A small suggestion, part of the node database uses mysql for beginners, mysql is more widely used

MDN URL: https://developer.mozilla.org/en-US/docs/Learn

**Comment by Josh-Cena** [comment]
cc @Rumyra Do you think this should be converted to a discussion? Or should the team consider this at all—I don't think we want to emphasize that much on backend?

**Comment by hamishwillee** [comment]
You select a database based on the requirements of the data to be stored. If you're working with largely unstructured data and speed and ease of use is the most important factor then MongoDB is a much better alternative to MySQL (or [insert name of your favourite relational database here]). 

The specific case [referred to above](https://github.com/mdn/content/issues/11948#issuecomment-960426365) was the express tutorial. For this case I covered that there are alternatives in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#what_databases_can_i_use

I am going to close this issue as it was originally related to the express, for which I don't think this is appropriate. Thank you for posting this @libingqin - I hope my reasoning makes sense.

@Josh-Cena I'll leave it to @Rumyra to decide if we do need a framework-agnostic topic on server-side databases - in which case she can create a separate "clean" issue on the topic outlining the requirement. I think it is relevant, but not any kind of priority.
