### ISSUE TITLE
No está completamente traducido al español

### ISSUE THREAD

**Issue by FerDav** [mdn/content#1196]
Esta web:
https://developer.mozilla.org/es/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content
sólo esta traducida al español hasta **antes del título: Detecting track addition and removal**

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
