### ISSUE TITLE
[Web API] Ship form-associated custom elements FF98

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#11969]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

This follows on from #10142 to release feature

I think that "did everything needed". So this might just remove a preference and update experimental features/release notes.

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1745378

**Comment by hamishwillee** [comment]
Status:

Most of this done in #10142. Now this has shipped all we need to do is update the BCD, release notes, experimental features.

- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/14822
- [ ] Release notes
- [ ] Experimental features
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
🎈
