### ISSUE TITLE
Issue with "TextTrackList": Mention of function that's not actually allowed

### ISSUE THREAD

**Issue by raphaelm** [mdn/content#11974]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList

#### What information was incorrect, unhelpful, or incomplete?

MDN states:

> Retrieve an instance of this object with HTMLMediaElement.textTracks. The individual tracks can be accessed using array syntax or functions such as forEach() for example.

#### What did you expect to see?

> Retrieve an instance of this object with HTMLMediaElement.textTracks. The individual tracks can be accessed using array syntax.

#### Did you test this? If so, how?

We had a production issue with an HLS live stream featuring WebVTT captions. Turns out, ``forEach`` is not actually allowed (tested in Firefox 93.0 and some newer version). I'm unsure whether this is a Firefox bug or a MDN bug, either way, the sentence is currently wrong.

The error message was:

```
Uncaught TypeError: this.$refs.video.textTracks.forEach is not a function
```

The change in our project that fixed the issue was:

https://github.com/venueless/venueless/commit/a6615ebfa1b6b2e4f041b662db09586752c8b080

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve raised #12016 with a fix.
