### ISSUE TITLE
Issue with "Window.open()": Can't make "popup" work

### ISSUE THREAD

**Issue by johaneven** [mdn/content#11988]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/open

#### What information was incorrect, unhelpful, or incomplete?
The popup description is for me a bit unclear. For instance "minimal UI parts"...what does that mean? Does it mean that the address bar is not visible?

#### Specific section or headline?
Popup feature

#### Did you test this? If so, how?

@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<script>
    var windowObjectReference;
    var windowFeatures = "popup=yes";

    function openRequestedPopup() {
      windowObjectReference = window.open("https://edition.cnn.com/asia/live-news/novak-djokovic-australia-visa-01-13-22/index.html", "CNN_WindowName", windowFeatures);
    }
</script>
<div class="text-center">
    <a 
        href="http://www.spreadfirefox.com/"
        target="PromoteFirefoxWindow"
        onclick="openRequestedPopup(); return false;"
        title="test">
    Popup</a>
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

The popup looks exactly the same regardless if I use "popup=yes" or not. I've tried this on Chrome Version 97.0.4692.71 (Official Build) (64-bit) as well as Chrome Version 98.0.4758.54 (Officiell version) beta (64 bitar).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/open`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/open
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/open/index.md
* Last commit: https://github.com/mdn/content/commit/71971ec85b773478db89849364734bda2e70106a
* Document last modified: 2021-11-14T06:14:45.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks for reporting. This is what I see on `Version 97.0.4692.99 (Official Build) (64-bit)`. 

`window.open("https://edition.cnn.com/asia/live-news/novak-djokovic-australia-visa-01-13-22/index.html", "CNN_WindowName");`|`window.open("https://edition.cnn.com/asia/live-news/novak-djokovic-australia-visa-01-13-22/index.html", "CNN_WindowName", "popup");`
--|--
![image](https://user-images.githubusercontent.com/2392803/150662029-7307281e-f1fc-4a82-bbad-1d1a0a85fe52.png)|![image](https://user-images.githubusercontent.com/2392803/150661967-b85f74a0-7dd0-48be-9b34-e7914d7aa011.png)  
Opens link in another tab in same window | Opens link in new window but without the refresh/back/fwd buttons.
