### ISSUE TITLE
Issue with "Package management basics": the npm package 'parcel-bundler' (Parcel v1) is deprecated and no longer maintained

### ISSUE THREAD

**Issue by germanfrelo** [mdn/content#11984]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management

#### What information was incorrect, unhelpful, or incomplete?
Following the article tutorial, we are prompted to install Parcel by running `npm install parcel-bundler`. However, after installing it, the following warning is showed in the terminal (among others):
```
npm WARN deprecated parcel-bundler@1.12.5: Parcel v1 is no longer maintained. Please migrate to v2, which is published under the 'parcel' package. See https://v2.parceljs.org/getting-started/migration for details.
```

The same message is on [the 'parcel-bundler' package page](https://www.npmjs.com/package/parcel-bundler):
> Parcel v1 is no longer maintained. Please migrate to v2, which is published under the 'parcel' package. See https://v2.parceljs.org/getting-started/migration for details.

#### Specific section or headline?
[Installing parcel](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management#installing_parcel)

#### What did you expect to see?
```
npm install parcel
```
instead of
```
npm install parcel-bundler
```

#### Did you test this? If so, how?
I just followed the steps described in the article.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/package_management`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
* Last commit: https://github.com/mdn/content/commit/abc5ffcbcc50f6bad10dd7ad92a90d0e91dfe0f6
* Document last modified: 2021-12-09T22:36:19.000Z

</details>

**Comment by himanshugarg** [comment]
> Parcel has spotted that you need the module, searched for it in the npmjs.com package registry, and installed it locally for us, automatically

Is this something parcel really capable of? I see the following error after updating the `import { formatDistanceToNow } from 'date-fns'` to index.js:

![image](https://user-images.githubusercontent.com/2392803/151689186-94c3314e-c539-43e9-b4c2-4b1d0c24e9a3.png)

**Comment by Techi-Dev** [comment]
To fully debug you can also visit here https://en.parceljs.org/getting_started.html

**Comment by Josh-Cena** [comment]
Closing in favor of https://github.com/mdn/content/issues/17278
