### ISSUE TITLE
Issue with "WAI-ARIA Roles": Do `p` elements have a role?

### ISSUE THREAD

**Issue by marcelltoth** [mdn/content#11980]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles

#### What information was incorrect, unhelpful, or incomplete?

This page states (emphasis mine):
> By default, semantic elements have a role; **`<p>` has the "paragraph" role,** 

The above contradicts with what the [page on `<p>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p) states:
![image](https://user-images.githubusercontent.com/543372/149354948-3fd002e3-666f-4550-9a88-f3df3ada1a33.png)

#### Specific section or headline?

Introduction, 2nd paragraph.

#### What did you expect to see?

As far as I can tell from the WAI-ARIA spec, the `p` page is correct, there is no such standard ARIA role as `paragraph`, and paragraph elements don't have implicit roles.

#### Did you test this? If so, how?

Can't really test it, other than by reading the spec

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/roles`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/roles/index.md
* Last commit: https://github.com/mdn/content/commit/6f410f14b91c3cee5e1a1c7c297c51ede34eb21f
* Document last modified: 2021-12-13T18:20:50.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #12014 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

**Comment by marcelltoth** [comment]
Thank you @sideshowbarker !
