### ISSUE TITLE
Issue with "Proxy Auto-Configuration (PAC) file": …

### ISSUE THREAD

**Issue by devbupkes** [mdn/content#1200]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file

#### What information was incorrect, unhelpful, or incomplete?
Statement: "For a reliable way to use these RegExp syntaxes, just use RegExp instead"

#### Specific section or headline?
shExpMatch()

#### What did you expect to see?
I feel the document would be of better use if an early paragraph addressed what is and is not available for use within the PAC file realm. Way down in "Example 6" provides "Most of the standard JavaScript functionality is available for use...". Since this subject often comes up among non-coding people, it's worth more directly addressing. 
I've been coding PAC scripts for years and even I'm not sure which features can't be used without trial and error testing.

#### Did you test this? If so, how?
n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/proxy_servers_and_tunneling/proxy_auto-configuration_pac_file`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/proxy_servers_and_tunneling/proxy_auto-configuration_pac_file/index.html
* Report started: 2021-01-11T22:03:32.757Z

</details>

**Comment by hamishwillee** [comment]
@devbupkes Firstly, thanks for posting. 

> shExpMatch() ""For a reliable way to use these RegExp syntaxes, just use RegExp instead""

Yes, that's pretty confusing. I've tried to fix this in https://github.com/mdn/content/pull/1484 by explaining the glob syntax without referring to Regexp, then just noting that if RegExp is supported by the client then it can provide a better and more consistent tool for pattern matching. 

> I feel the document would be of better use if an early paragraph addressed what is and is not available for use within the PAC file

Given you have some expertise would it be possible to outline what you think is supported/not supported on some of the different clients. Is it a matter that the entirety of javascript supported by a particular browser is also supported for PAC files?

**Comment by hamishwillee** [comment]
@devbupkes If you can "outline what you think is supported/not supported on some of the different clients. " as in my previous comment please reopen.

Otherwise I think we should leave this closed - it is unlikely someone will have the time to do the needed testing.
