### ISSUE TITLE
Issue with "console.assert()": Chrome's message formatting works now

### ISSUE THREAD

**Issue by NagayamaToshiaki** [mdn/content#12004]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/console/assert

#### What information was incorrect, unhelpful, or incomplete?
As of Chrome 96.0.4664.110, assert message formatting works as intended.
I tried "console.assert(false, 'the word is %s', 'foo');" on the Japanese version of the browser, and the result was "アサーションが失敗しました: the word is foo". So, foo is correctly interpreted as msg's variable.
Is there any browser or environment that treats all assert's params as obj?

#### Specific section or headline?
Examples : the example after "...the use of such a string does not currently work as intended as a parameter for console.assert in all browsers:"

#### What did you expect to see?
Delete mention about Chrome or move it to the e.g. of "correct output in Node.js and some browsers".

#### Did you test this? If so, how?
By using Devtools.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/console/assert`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/console/assert
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/console/assert/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve opened #12012 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
