### ISSUE TITLE
Issue with "Compiling an Existing C Module to WebAssembly": Unhandled Promise Rejection: ReferenceError: Can't find variable: createImageBitmap

### ISSUE THREAD

**Issue by centerqi** [mdn/content#12015]
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/existing_C_to_wasm

#### What information was incorrect, unhelpful, or incomplete?
safari :14.10
Unhandled Promise Rejection: ReferenceError: Can't find variable: createImageBitmap  image.html 93 line
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/existing_c_to_wasm`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/existing_C_to_wasm
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/existing_c_to_wasm/index.md
* Last commit: https://github.com/mdn/content/commit/bbe7383371e67c90d2eb72f3899115ba4b5d4548
* Document last modified: 2021-10-11T10:56:41.000Z

</details>

**Comment by Josh-Cena** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap#browser_compatibility, this is only supported in Safari 15+.
