### ISSUE TITLE
Add position: sticky to thead element of “Browser compatibility for manifest.json” table

### ISSUE THREAD

**Issue by benemohamed** [mdn/content#12035]
## What is the new suggestion?

add position sticky on thead in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_compatibility_for_manifest.json

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.manifest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_compatibility_for_manifest.json
* Report started: 2022-01-15T16:02:58.953Z

</details>

**Comment by rebloor** [comment]
@benemohamed please could you clarify this request. As `position: sticky;` relate to the page presentation rather than its content, this may be something to raise on [mdn/yari](https://github.com/mdn/yari), the engine that renders MDN content.
