### ISSUE TITLE
Issue with "manifest_version": `manifest_version` can be 3

### ISSUE THREAD

**Issue by ylemkimon** [mdn/content#12040]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/manifest_version

#### What information was incorrect, unhelpful, or incomplete?

> Currently, this must always be 2.

MV3 is supported on Chrome.

#### What did you expect to see?

A mention about MV3.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/manifest_version`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/manifest_version
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/manifest.json/manifest_version/index.md
* Last commit: https://github.com/mdn/content/commit/629960fa07e15f2354d75daf14f149d4942539ec
* Document last modified: 2021-10-26T21:28:18.000Z

</details>

**Comment by rebloor** [comment]
They will be information provided about manifest v3 in due course.
