### ISSUE TITLE
Issue with "Node.appendChild()": (misinformation about error raised)

### ISSUE THREAD

**Issue by jackdeguest** [mdn/content#12048]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild

#### What information was incorrect, unhelpful, or incomplete?
The document states about possible error that `If the insertion of aChild would lead to the presence of an Element node before a DocumentType node.`

I am wondering how the appending of a new node could lead to that node being **before** a DocumentType node....

Addendum:
Actually the only case where this could possibly happen is if one were to select the doctype node itself and append it to the document. Assuming an HTML-tag element already exists, that would, in effect, put an element object before the doctype node. If this is the only possibly scenario, maybe the documentation should make it clearer.

And also `Thrown if the parent of aChild is not the current node.`

I do not think the node to be appended needs to be a child of the current node to be appended. It looks like some bad copy/paste from `replaceChild` documentation.

#### What did you expect to see?
I think those 2 particular lines have no point being here, because those error will just never happen.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/node/appendchild`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/node/appendchild/index.md
* Last commit: https://github.com/mdn/content/commit/617ea81e2bf49c36c11f8a1ea52df1aa7dc0e3e3
* Document last modified: 2021-12-05T22:55:39.000Z

</details>

**Comment by sideshowbarker** [comment]
> I think those 2 particular lines have no point being here, because those error will just never happen.

Agreed. If you open a PR which removes those lines, I’d be happy to review and merge it.

**Comment by jackdeguest** [comment]
> > I think those 2 particular lines have no point being here, because those error will just never happen.
> 
> Agreed. If you open a PR which removes those lines, I’d be happy to review and merge it.

Understood. I created a PR to that effect for you to review.

**Comment by teoli2003** [comment]
Hi, @jackdeguest! Thanks for the PR! You said you created a PR but I can't find it. Do you have the # handy? I would like to link it here so that when it lands we can close this.

**Comment by jackdeguest** [comment]
> Hi, @jackdeguest! Thanks for the PR! You said you created a PR but I can't find it. Do you have the # handy? I would like to link it here so that when it lands we can close this.

It is possible that I removed it as it is often suggested once it was approved, and I got confused and removed one that was not finally approved?

**Comment by teoli2003** [comment]
Found it! #12078.

As it has been merged, I think we can close this (feel free to reopen if I'm mistaken)

**Comment by jackdeguest** [comment]
> Found it! #12078.
> 
> As it has been merged, I think we can close this (feel free to reopen if I'm mistaken)

Yes, I checked and it seems the page was already updated.

**Comment by teoli2003** [comment]
(Thanks for fixing this!)
