### ISSUE TITLE
Issue with "Object prototypes": console shows “undefined”

### ISSUE THREAD

**Issue by cjgunzel** [mdn/content#12044]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes

#### What information was incorrect, unhelpful, or incomplete?
Revisiting create()  <-- Section header 

"Earlier on we showed how the Object.create() method can be used to create a new object instance.

    For example, try this in your previous example's JavaScript console:

    let person2 = Object.create(person1);"

This code returns "undefined" on Firefox 96 on Linux.  person1 is not null and shows all the functions and attributes one would expect.

#### What did you expect to see?
What create() actually does is to create a new object from a specified prototype object. Here, person2 is being created using person1 as a prototype object. You can check this by entering the following in the console:

```js
person2.__proto__
```

#### Did you test this? If so, how?
Followed instructions on the page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/objects/object_prototypes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/object_prototypes/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by sideshowbarker** [comment]
What does the console show when you enter `person2.__proto__`?

>> For example, try this in your previous example's JavaScript console:
>> ```js
>> let person2 = Object.create(person1);
>> ```
>
> This code returns "undefined" on Firefox 96 on Linux. person1 is not null and shows all the functions and attributes one would expect.

It seems like what you’re saying is, after you enter `let person2 = Object.create(person1);` in the console, the console displays `undefined`. That’s expected. It doesn’t indicate any problem.

Specifically, it’s not causing `person2` to be set to `undefined`. If you enter `person2` in the console after that statement, what does the console show?

**Comment by cjgunzel** [comment]
I must have forgotten to refresh or something.  It is creating the person2
object now -- didn't do that yesterday so appears to be dumb user issue....

Thanks.  Sorry to have bothered you.

**Comment by sideshowbarker** [comment]
> I must have forgotten to refresh or something. It is creating the person2 object now -- didn't do that yesterday so appears to be dumb user issue.... Thanks. Sorry to have bothered you.

No worries — glad we got it cleared up
