### ISSUE TITLE
touchend: Document why it doesn’t work on Android as expected

### ISSUE THREAD

**Issue by HomyeeKing** [mdn/content#12055]
## What is the new suggestion?

I think it necessary to give some  declaration  about the performance difference on different platform

## Why is it important or useful?

like why it not firing on Android as expect, since I met some problem these days and it turn out to  the touchend invoke problem on Android
but I don't get enough information from the mdn and the answer from the google to this question is not very much and clear

**Comment by Josh-Cena** [comment]
@HomyeeKing It has been a long while, but can you clarify what kind of "doesn't work as expected" behavior are you referring to?

**Comment by HomyeeKing** [comment]
maybe it because of the implementaiton of the webview, I can't remember any details, close for now
