### ISSUE TITLE
Issue with "Clipboard API": read/write permissions are gone/being gone

### ISSUE THREAD

**Issue by saschanaz** [mdn/content#12065]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

#### What information was incorrect, unhelpful, or incomplete?

>Access to the contents of the clipboard is gated behind the Permissions API: The clipboard-write permission is granted automatically to pages when they are in the active tab. The clipboard-read permission must be requested, which you can do by trying to read data from the clipboard.

#### What did you expect to see?

That part should be removed, since Apple and Mozilla have no intent to implement them and thus they are (being) dropped from the specs:

* https://github.com/w3c/permissions/pull/228
* https://github.com/w3c/permissions/pull/246
* https://github.com/w3c/clipboard-apis/pull/132
* https://github.com/w3c/clipboard-apis/pull/164 (in progress)

The compat table should probably also include permission support.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/clipboard_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/clipboard_api/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Opened #12066 for the MDN change

> The compat table should probably also include permission support.

It seems like that should be handled with a BCD PR first
