### ISSUE TITLE
Issue with "Number.NEGATIVE_INFINITY": No description of -ve zero

### ISSUE THREAD

**Issue by richardl62** [mdn/content#12062]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/NEGATIVE_INFINITY

#### What information was incorrect, unhelpful, or incomplete?

The documentation states that division by NEGATIVE_INFINITY results in negative zero or positive zero. But there is no explanation of what negative or positive zero mean, in particular how then differ from 'regular' zero.

There is a similar issue with the documentation on POSITIVE_INFINITY.

#### Specific section or headline?

Description

#### What did you expect to see?

A link to a description of negative and positive zero.

#### Did you test this? If so, how?

-

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/number/negative_infinity`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/NEGATIVE_INFINITY
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/number/negative_infinity/index.md
* Last commit: https://github.com/mdn/content/commit/933cb61a78634a75d6ab284656529440a4e91c68
* Document last modified: 2021-12-29T23:15:19.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks — opened #12068
