### ISSUE TITLE
Issue with "Array.prototype.splice()": Parameters details 

### ISSUE THREAD

**Issue by chithtunnaing23** [mdn/content#12086]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

#### What information was incorrect, unhelpful, or incomplete?
I think splice doesn't work as specified. If it gets 2 parameters it preserves the item at the first parameter index of the array
up to the number of items(second parameter). If zero, empty array is returned.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/splice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/splice/index.md
* Last commit: https://github.com/mdn/content/commit/a9fc7948636b166450cb47ec4be88ad703bbf2a6
* Document last modified: 2021-12-12T22:16:53.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! Please be very specific about which part of the doc is wrong.

>  If it gets 2 parameters it preserves the item at the first parameter index of the array
up to the number of items(second parameter)

I'm not sure what "preserves" means here. `splice()` deletes the number of items given in the second parameter, starting at the index given in the first parameter:

```js
const months = ['Jan', 'Feb', 'March', 'April', 'May', 'June'];

// delete three items, starting at index 2
months.splice(2, 3);

console.log(months);
// "Jan", "Feb", "June"
```

>  If zero, empty array is returned.

I'm not sure what "If zero" means here. If what is zero? If you mean "If the second parameter is zero", then that's correct and that's also what the page says:

> If deleteCount is 0 or negative, no elements are removed.
> ...
> If no elements are removed, an empty array is returned.

**Comment by sideshowbarker** [comment]
Closing for lack of response.
