### ISSUE TITLE
Issue with "async function":  introduce the await promise.catch() syntax

### ISSUE THREAD

**Issue by slk333** [mdn/content#12098]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

#### What information was incorrect, unhelpful, or incomplete?
Rewriting a Promise chain with an async function

#### Specific section or headline?
Rewriting a Promise chain with an async function

#### What did you expect to see?
Mention this alternative to try/catch

```js
async function getProcessedData(url) {

const v = await downloadData(url).catch(e) {
    return await downloadFallbackData(url)
  }
  return processDataInWorker(v)
}
 ```

this is totally correct, shorter and arguably cleaner than the try/catch syntax;

```js
async function getProcessedData(url) {
  let v
  try {
    v = await downloadData(url)
  } catch(e) {
    v = await downloadFallbackData(url)
  }
  return processDataInWorker(v)
}
```

- no need to initialize v
- shorter
- cleaner

#### Did you test this? If so, how?
yes, personally

this is especially useful where you simply throw the error if it goes wrong, a bit like a guard statement
```js
const result = await promise.catch(error=>throw error)
// go ahead with the rest of the function
```
I think this pattern is really useful because the try/catch statement can be very heavy-handed in some situations, and the await / catch syntax handles this gracefully

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/async_function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/async_function/index.md
* Last commit: https://github.com/mdn/content/commit/b69d0dbeab9fc74fbacc818045935abdcfc14d2b
* Document last modified: 2022-01-14T21:38:48.000Z

</details>

**Comment by jamesaucode** [comment]
I made a PR for this. Correct me if Im wrong but I believe your example code snippet can be even more precise like this

```js
async function getProcessedData(url) {
  const v = await downloadData(url).catch(e => {
    return downloadFallbackData(url)
  })
  return processDataInWorker(v)
}
```
