### ISSUE TITLE
Broken link on Element.querySelectorAll() page

### ISSUE THREAD

**Issue by cw118** [mdn/content#12148]
## What page(s) did you find the problem on?

The [`Element.querySelectorAll()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll) has a broken link to code snippets.

In the ["See also" section](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll#see_also), the link for "Code snippets for `querySelector()`", which is `https://developer.mozilla.org/en-US/docs/Code_snippets/QuerySelector`, can't be resolved. 

I tried lots of variations, none of which worked (`en-US/docs/Mozilla/Add-ons/Code_snippets/QuerySelector`, and many more by adding/moving/excluding `Add-ons`, `Code_snippets` and other parts of the URL). I also did a somewhat extensive search for the page and couldn't find anything, so I'm not sure if this link could be replaced by another resource or if it should simply be removed.

**Comment by sideshowbarker** [comment]
> I'm not sure if this link could be replaced by another resource or if it should simply be removed.

It should just be removed. Can you create a PR to remove it?

**Comment by cw118** [comment]
> It should just be removed. Can you create a PR to remove it?

👍 I'll create one now

**Comment by cw118** [comment]
Just a quick question — there's currently a note that links to `/en-US/docs/Web/API/Element/querySelectorAll#escaping_special_characters` which leads nowhere since the anchor/heading doesn't exist. Would [this section on Escape sequences](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#escape_sequences) be a suitable replacement/link? If not, could I just remove the part of the note (_"See **Escaping special characters** for more information."_) that links to the nonexistent heading?
