### ISSUE TITLE
Content bug: JSRef generates preceding content

### ISSUE THREAD

**Issue by That-Guy977** [mdn/content#12156]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/@@iterator
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/anchor
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply

## Specific page section or heading?

N/A problem precedes content

## What is the problem?

JSRef (as it seems to me) generates the property/method list preceding content in some pages

## What did you expect to see?

said list appearing in the side bar, such as in
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/at
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt

## Did you test this? If so, how?

N/A

**Comment by sideshowbarker** [comment]
Alerting @mdn/core-yari-dev

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/anchor is the only page where I can observe the problem described in the issue description.

But when I look at http://localhost:5042/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/anchor (the same page served from my local Yari, that page does not have the problem).

**Comment by schalkneethling** [comment]
> Alerting @mdn/core-yari-dev
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/anchor is the only page where I can observe the problem described in the issue description.
> 
> But when I look at http://localhost:5042/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/anchor (the same page served from my local Yari) that page does not have the problem.

Thanks @sideshowbarker and @That-Guy977. This has been resolved in https://github.com/mdn/yari/pull/5183

**Comment by sideshowbarker** [comment]
Closing as resolved by upstream Yari changes. (So the production pages will be fixed once we get the Yari change propagated.)
