### ISSUE TITLE
Content bug: Docs style was broken when use edge to browser under Mac OS

### ISSUE THREAD

**Issue by finas** [mdn/content#12168]
## What page(s) did you find the problem on?
https://developer.mozilla.org/en-US/docs/Web

## Specific page section or heading?
All docs under https://developer.mozilla.org/en-US/

## What is the problem?
The css file is blocked, and the page is showing without style.  
The error log from web console: `Refused to apply style from 'https://developer.mozilla.org/static/css/main.cd55b6e0.chunk.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

## Did you test this? If so, how?'   
Open the page url.
Brower:Only in edge/edge-beta. Chrome/firefox/safari and edge in-private work great so far.
System:Mac OS.

**Comment by sideshowbarker** [comment]
This should instead be reported as an Edge bug in whatever issue tracker Microsoft uses for Edge.

The MIME type of that file isn’t `text/html`:

```
$ curl -I https://developer.mozilla.org/static/css/main.cd55b6e0.chunk.css
HTTP/2 200
content-type: text/css; charset=utf-8
```
