### ISSUE TITLE
Issue with "RTCPeerConnection.createOffer()": missing params

### ISSUE THREAD

**Issue by pranavAtCamify** [mdn/content#12164]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createOffer

#### What information was incorrect, unhelpful, or incomplete?
Some options were missing

#### Specific section or headline?
Parameters

#### What did you expect to see?
The options 
            offerToReceiveAudio: boolean,
            offerToReceiveVideo: boolean
 that can be passed to the createOffer function

#### Did you test this? If so, how?
Yup. Used it in my application.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/rtcpeerconnection/createoffer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createOffer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/rtcpeerconnection/createoffer/index.md
* Last commit: https://github.com/mdn/content/commit/efd21b7b7368624dcd3492e73f443573832ef04d
* Document last modified: 2021-10-27T06:18:11.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks — I’ve opened #12165 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

**Comment by thegiantbeast** [comment]
@sideshowbarker @wbamberg shouldn't this change also include a note as it was before like:

```
 **Note:** You shouldn't use this legacy property.
    > Instead, use {{domxref("RTCRtpTransceiver")}} to control whether or not to accept
    > incoming audio

 **Note:** You shouldn't use this legacy property.
    > Instead, use {{domxref("RTCRtpTransceiver")}} to control whether or not to accept
    > incoming video.
```
?

Because it clearly states that the props are deprecated but no option is mentioned in the docs. 🤔

**Comment by sideshowbarker** [comment]
> @sideshowbarker @wbamberg shouldn't this change also include a note as it was before like:
> 
>  **Note:** You shouldn't use this legacy property.
>     > Instead, use {{domxref("RTCRtpTransceiver")}} to control whether or not to accept
>     > incoming audio

I don’t know when the source had that Note before, but it wasn’t there when I last edited the source — my 570175c change did not remove it.

**Comment by thegiantbeast** [comment]
The delete of the content happened in this PR https://github.com/mdn/content/pull/9748

**Comment by sideshowbarker** [comment]
> The delete of the content happened in this PR #9748

ping @queengooborg
