### ISSUE TITLE
Issue with "Django Tutorial Part 4: Django admin site": author-detail view contents are wrong

### ISSUE THREAD

**Issue by AnneVerme** [mdn/content#12176]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Admin_site

#### What information was incorrect, unhelpful, or incomplete?
My author detail view contains a `<h2></h2>` tag containing the __str__(self)
defined in models.py
See attachement.

#### Specific section or headline?
Organize detail view layout

#### What did you expect to see?
The author detail view as shown in the image.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/admin_site`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Admin_site
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/admin_site/index.md
* Last commit: https://github.com/mdn/content/commit/a1b01c6558f111f62118e73c60b9e2b95e423a13
* Document last modified: 2022-01-05T16:00:58.000Z

</details
![change_author_detail_view](https://user-images.githubusercontent.com/4706006/150149181-091bdbd1-c603-48e2-ad0e-4701e489baf1.png)
>

**Comment by himanshugarg** [comment]
Thanks for reporting the issue. Did you miss an attachment?

**Comment by hamishwillee** [comment]
I'm closing this, as the additional information (image showing problem) is not provided. Also because I know that most likely you have made a mistake because our worked version of the code does not have this error. YOu can check that out and compare in https://github.com/mdn/django-locallibrary-tutorial
