### ISSUE TITLE
Issue with "Intl.NumberFormat": (missing full table of possible options)

### ISSUE THREAD

**Issue by amfriedman** [mdn/content#12188]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

#### What information was incorrect, unhelpful, or incomplete?
Only a few examples of options. I expected to see a table of all available options.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/index.md
* Last commit: https://github.com/mdn/content/commit/0dbea6dc8f371e2734ca3f0ad1ab311ec79a97ee
* Document last modified: 2022-01-10T19:54:53.000Z

</details>

**Comment by Josh-Cena** [comment]
Isn't the options list here? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

**Comment by sideshowbarker** [comment]
> Isn't the options list here? [developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat)

Maybe all we need here is, everywhere in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat article — and in articles in its subtree — make _options_ a hyperlink to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#options
