### ISSUE TITLE
Issue with "String.prototype.substring()": (nav menu showing up on the wrong place)

### ISSUE THREAD

**Issue by gonza-lito** [mdn/content#12183]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring

#### What information was incorrect, unhelpful, or incomplete?
looks like the nav menu is on the content space
<img width="1960" alt="Screen Shot 2022-01-19 at 13 03 35" src="https://user-images.githubusercontent.com/31010588/150168693-5c1d73d0-bde4-45e9-b07a-84828cd1d698.png">

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/substring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/substring/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by arda2525** [comment]
Needs-triage

**Comment by sideshowbarker** [comment]
Thanks for reporting this — the problem has been fixed on the backend, and the fix will be propagating to the production site soon.
