### ISSUE TITLE
Issue with "Keep-Alive": (the page is loaded without the layout style)

### ISSUE THREAD

**Issue by Wolfergest** [mdn/content#12193]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/keep-alive`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/keep-alive/index.md
* Last commit: https://github.com/mdn/content/commit/9b0740597570c859b81e04e0f73a3d16aac5bbb8
* Document last modified: 2021-10-03T10:58:24.000Z

</details>

**Comment by sideshowbarker** [comment]
Please don’t open multiple issues for the same problem like this — instead, open one issue and add the page URLs.
