### ISSUE TITLE
Issue with "Proxy server": (the page is loaded without the layout style)

### ISSUE THREAD

**Issue by Wolfergest** [mdn/content#12192]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Proxy_server

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/proxy_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Proxy_server
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/proxy_server/index.md
* Last commit: https://github.com/mdn/content/commit/4a9f9d2e9c1811ce3519a7061e906db9200a5e97
* Document last modified: 2021-10-08T00:24:32.000Z

</details>

**Comment by sideshowbarker** [comment]
I don’t see any problems with https://developer.mozilla.org/en-US/docs/Glossary/Proxy_server when I open it in my browser. Can you maybe take a screenshot of what you’re seeing when you open it — and upload that screenshot in a comment here?

**Comment by sideshowbarker** [comment]
Please subscribe to https://github.com/mdn/content/issues/12195 to track the resolution for the underlying problem.
