### ISSUE TITLE
unreadable code in the end of closures page

### ISSUE THREAD

**Issue by MihailVasilev** [mdn/content#1219]
<img width="1256" alt="Screen Shot 2021-01-12 at 6 31 54 PM" src="https://user-images.githubusercontent.com/36164992/104327850-a7e58880-5504-11eb-9a1d-a56a9ce43b34.png">

link => https://developer.mozilla.org/ru/docs/Web/JavaScript/Closures#

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
