### ISSUE TITLE
Issue (question?) with "color()": "name of a color defined by a colorspace"

### ISSUE THREAD

**Issue by coderfin** [mdn/content#12209]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color()

#### What information was incorrect, unhelpful, or incomplete?

The document states that you can pass:
> "a \<string\> giving the name of a color defined by the colorspace."

- I am not able to see any names defined by any color space in the documentation. 
- I also cannot see this syntax in the specification documentation.
  - https://www.w3.org/TR/css-color-4/#color-function
  - https://www.w3.org/TR/css-color-5/#color-function
    - Even in custom colorspaces I don't see syntax for `<string>`

Am I missing something, are there colorspaces that have colors defined as strings similar to how `currentColor` is predefined, or is this page incorrect?

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color()#values

#### What did you expect to see?

It would be nice to have an example `<string>` defined by any colorspace.

#### Did you test this? If so, how?

I tested a few options of what I would expect to possibly work in the latest version of Safari on MacOS.
`background: color(display-p3 1 0.5 0);` - Works
`background: color(srgb orange);` - does not work

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/color_value/color()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/color_value/color()/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by danburzo** [comment]
That part of the `color()` syntax [has been removed](https://github.com/w3c/csswg-drafts/issues/6095).
