### ISSUE TITLE
Issue with "Django Tutorial Part 2: Creating a skeleton websit…": Permanent redirect really is permanent

### ISSUE THREAD

**Issue by axfreeman** [mdn/content#12207]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website

#### What information was incorrect, unhelpful, or incomplete?

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]

#### Specific section or headline?

[Django Tutorial 2 ](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website)

#### What did you expect to see?

I expected that the effects would be limited to this tutorial

#### Did you test this? If so, how?

Having finished the tutorial, I started another project. But the home page (localhost:8000) now redirects to /catalog regardless

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/skeleton_website`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/skeleton_website/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Do you mean that you started another Django project? Did you restart the server?

Have you tried force-reloading? Clearing your browser cache?

**Comment by sideshowbarker** [comment]
Closing for lack of response
