### ISSUE TITLE
Issue with "HTMLElement: transitionend event": Incorrect value syntax in an example

### ISSUE THREAD

**Issue by MaxdAyala** [mdn/content#12214]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/transitionend_event

#### What information was incorrect, unhelpful, or incomplete?

`transition-property: transform background;`

#### Specific section or headline?

Live example

#### What did you expect to see?

`transition-property: transform, background;`

There should be a comma after _transform_.

#### Did you test this? If so, how?

Inspect the source for the example. There is a warning saying that this is an invalid property.

There is a similar error on the transitioncancel page.
[https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/transitioncancel_event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/transitioncancel_event)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlelement/transitionend_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/transitionend_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/transitionend_event/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #12215 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
