### ISSUE TITLE
Issue with "downloads.download()": “browser is not defined”

### ISSUE THREAD

**Issue by joshuamosesb** [mdn/content#12212]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download

#### Specific section or headline?
- Example

#### Did you test this? If so, how?
Tried out the sample code-snippet as below:
```
function onStartedDownload(id) {
  console.log(`Started downloading: ${id}`);
}

function onFailed(error) {
  console.log(`ERROR: Download failed: ${error}`);
}

function download_remote_file(downloadUrl, target_file_name){

       var downloading = browser.downloads.download({
         url : downloadUrl,
         filename : target_file_name,
         conflictAction : 'uniquify'
       });

       downloading.then(onStartedDownload, onFailed);
}
```
- getting an error: `Uncaught ReferenceError: browser is not defined` 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/downloads/download`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/downloads/download/index.md
* Last commit: https://github.com/mdn/content/commit/629960fa07e15f2354d75daf14f149d4942539ec
* Document last modified: 2021-10-26T21:28:18.000Z

</details>

**Comment by rebloor** [comment]
@joshuamosesb can you confirm which version of Firefox you're using and provide a copy of the extension?

**Comment by Alishan-1** [comment]
Tested the code in Chrome browser extension.

In chrome you need to change the keyword ""browser" to "chrome".

`var downloading = browser.downloads.download({`
change the above line to:
`var downloading = chrome.downloads.download({`

You must declare the "downloads" permission in the extension manifest to use this API.

`{
  "name": "My extension",
  ...
  "permissions": [
    "downloads"
  ],
  ...
}`
