### ISSUE TITLE
Issue with "Classes": node support

### ISSUE THREAD

**Issue by bobzhang55** [mdn/content#12226]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

#### What information was incorrect, unhelpful, or incomplete?
Field declarations section is totally invalid.

#### Did you test this? If so, how?
yes. Test with vs code under Node.js

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/classes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/classes/index.md
* Last commit: https://github.com/mdn/content/commit/e752a8fe731fbdb9061e39a6e2b797a7ccb7e2b5
* Document last modified: 2022-01-19T17:57:58.000Z

</details>

**Comment by wbamberg** [comment]
The first example here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#field_declarations

```js
class Rectangle {
  height = 0;
  width;
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
}


const r = new Rectangle(2, 3);
r.width;
// -> 3
```

...works just fine in Chrome 96, Firefox 98, and Node 17.2. Which version of Node are you running? According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields#browser_compatibility Node support public class fields since 12.0.0.

**Comment by bobzhang55** [comment]
10.15.3
Thanks and best regards,

Bob Zhang281-665-3386832-244-3095 

    On Thursday, January 20, 2022, 01:25:24 PM CST, wbamberg ***@***.***> wrote:  
 
 


The first example here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#field_declarations
class Rectangle {
  height = 0;
  width;
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
}


const r = new Rectangle(2, 3);
r.width;
// -> 3
...works just fine in Chrome 96, Firefox 98, and Node 17.2. Which version of Node are you running? According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields#browser_compatibility Node support public class fields since 12.0.0.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wbamberg** [comment]
> 10.15.3

Thanks for the extra detail. As the page says, Node doesn't support this feature until version 12, so the docs are correct here.
