### ISSUE TITLE
Content bug: [Firefox 96 devnotes] Schemeful SameSite got backed out

### ISSUE THREAD

**Issue by myakura** [mdn/content#12224]
## What page(s) did you find the problem on?

* [Firefox 96 for developers](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/96#http)

## Specific page section or heading?

In the [HTTP section](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/96#http).

## What is the problem?

https://github.com/mdn/content/blob/6564731f4289e05f85c7ce42b2d7e2d905152108/files/en-us/mozilla/firefox/releases/96/index.md?plain=1#L36-L39

> - Cookies sent from the same domain but using different schemes (for example http or https) are now considered to be from different sites with respect to the cookie [SameSite](/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) directive.

Schemeful SameSite was backed out due to number of site breakage.

- [1750257 - [Experiment] Staged Rollout: Pref off network.cookie.sameSite.schemeful in Firefox 96 Fx 96.0 to 96.0 Release](https://bugzilla.mozilla.org/show_bug.cgi?id=1750257)
- [1750264 - Disable cookie sameSite schemeful in Firefox 96](https://bugzilla.mozilla.org/show_bug.cgi?id=1750264)

## What did you expect to see?

I don't see the paragraph, or see a note mentioning that Schemeful SameSite had been enabled for a while but got backed out.

**Comment by myakura** [comment]
Looks like SameSite=Lax will be backed out too.
https://bugzilla.mozilla.org/show_bug.cgi?id=1751465

**Comment by hamishwillee** [comment]
Thanks - asking for confirmation in https://bugzilla.mozilla.org/show_bug.cgi?id=1750264#c6

Then the action would be to revert the browser compatibility information, remove the release note, add back experimental features info. Essentially back out the changes from https://github.com/mdn/content/issues/10857#issuecomment-982280050

**Comment by hamishwillee** [comment]
- [ ] Revert BCD changes: https://github.com/mdn/browser-compat-data/pull/14817
- [ ] Remove from release note - 
- [ ] Add to Experimental features -

**Comment by hamishwillee** [comment]
Closing, this is all reverted now.
