### ISSUE TITLE
Issue with "JavaScript object basics": (short summary here please)

### ISSUE THREAD

**Issue by Mouh-Cine-coder** [mdn/content#12220]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics

#### What information was incorrect, unhelpful, or incomplete?

The course was very helpful, but the function u built is deferent from the one u tried to use .
u declare : createPerson
and u used: createNewPerson
#### Specific section or headline?
Introducing constructors

#### What did you expect to see?
i figure it out just from reading  

#### Did you test this? If so, how?
yes, it's just a matter of syntax

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/objects/basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/basics/index.md
* Last commit: https://github.com/mdn/content/commit/318c7ff5cbaaf072ecd4509ebdfcdd30a4bcba9d
* Document last modified: 2022-01-17T18:27:15.000Z

</details>

**Comment by wbamberg** [comment]
Eek! We recently reworked all this content and typos have crept in.

Thanks for reporting this! I opened https://github.com/mdn/content/pull/12222 with a fix.
