### ISSUE TITLE
Issue with "Storing the information you need — Variables": live example not working

### ISSUE THREAD

**Issue by holly-042** [mdn/content#12230]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables

#### What information was incorrect, unhelpful, or incomplete?

the propmt is not popping up to input my name.

#### Specific section or headline?

variable example

#### What did you expect to see?
when I click on the button -- press me, it should open a prompt that askes me my name. then I should see an alert that say "hello ${Name}, nice to see you!" 

then it should print out "Welcome ${name};

#### Did you test this? If so, how?
clicked the button multiple times, Says Welcome null. with no prompt or alert.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/variables`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/variables/index.md
* Last commit: https://github.com/mdn/content/commit/c55519872cc7048e0ad5d55c5d98cfe410a15013
* Document last modified: 2022-01-02T00:07:08.000Z

</details>

**Comment by sideshowbarker** [comment]
What browser and what version of that browser are you using?

What messages is the browser logging to the devtools console?

**Comment by sideshowbarker** [comment]
Closing for lack of response.
