### ISSUE TITLE
Issue with "Array.prototype.forEach()": (Missing id element or example)

### ISSUE THREAD

**Issue by zhang1pr** [mdn/content#12236]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

#### What information was incorrect, unhelpful, or incomplete?
Clicking on link text [**see example below**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#sparsearray) doesn't bring me to any example on the page.
It's missing **id="sparsearray"** element or missing example on the page.

#### Specific section or headline?
**Description** section

#### What did you expect to see?
I expected to see the example.
I assume the [first example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#no_operation_for_uninitialized_values_sparse_arrays) in **Example** section is the one the link is referring to, but it's got a different ID.

#### Did you test this? If so, how?
I'm using Chrome.
I clicked on the link, but I didn't see the example.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/foreach`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/foreach/index.md
* Last commit: https://github.com/mdn/content/commit/de8ab08ecb27493bbf35e7224cbe5bbbc71a187b
* Document last modified: 2021-12-10T04:34:51.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #12237 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
