### ISSUE TITLE
Issue with "HTML attribute: rel": …

### ISSUE THREAD

**Issue by davemoz** [mdn/content#1223]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel

#### What information was incorrect, unhelpful, or incomplete?
Small typo. See below.

#### Specific section or headline?
In the `noreferrer` section.

#### What did you expect to see?
The current paragraph is as follows:

> Relevant to `<form>`, `<a>`, and `<area>`, including this value makes the referrer unknown (no Referer header will be included), and opens the creates a top-level browsing context, as if noopener were also set.

The second half—"...and opens the creates a top-level browsing context..."—looks like a typo. Seems like it should be either "opens a top-level.." or "creates a top-level". Not both.

#### Did you test this? If so, how?
n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/attributes/rel`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/html/attributes/rel/index.html
* Report started: 2021-01-12T15:55:04.594Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @davemoz ! I've fixed this; see https://github.com/mdn/content/commit/6a89a4c22a8d330ad2ba0774cca77ee7578dfa20
