### ISSUE TITLE
Issue with "Classes in JavaScript": code typo

### ISSUE THREAD

**Issue by hatchwald** [mdn/content#12241]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Classes_in_JavaScript

#### What information was incorrect, unhelpful, or incomplete?

```
const walsh = new Professor('Walsh', 'Psychology');
walsh.introduceSelf();  // 'My name is Professor Walsh, and I will be your Psychology professor'
walsh.grade('my paper'); // some random grade
```
for the `walsh.introduceSelf()` should will be `My name is Walsh, and I will be your Psychology professor` right ?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/objects/classes_in_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Classes_in_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/classes_in_javascript/index.md
* Last commit: https://github.com/mdn/content/commit/2bef9a5f18175148702ab2bb3ef5512205eca6da
* Document last modified: 2022-01-19T12:35:54.000Z

</details>

**Comment by sideshowbarker** [comment]
> for the `walsh.introduceSelf()` should will be `My name is Walsh, and I will be your Psychology professor` right ?

Yes. Thanks for catching that — I’ve opened #12245 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/12245
