### ISSUE TITLE
Issue with "Broadcast Channel API": Should mention that messages are passed through structured clone

### ISSUE THREAD

**Issue by justinfagnani** [mdn/content#12310]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API

#### What information was incorrect, unhelpful, or incomplete?

The "Sending a message" section says "Any kind of object can be sent, not just a DOMString.". The message is actually sent through the structured clone algorithm which doesn't support all kinds of objects.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API#sending_a_message

#### What did you expect to see?

Something like in the `postMessage` docs: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#syntax

> Data sent to the channel is serialized using the structured clone algorithm. This means you can send a broad variety of data objects safely without having to serialize them yourself.

#### Did you test this? If so, how?

No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/broadcast_channel_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/broadcast_channel_api/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Howdy Justin — thanks for raising this; I’ve opened #12318 with a fix.
