### ISSUE TITLE
Content suggestion: Add possibility to wrap input[type=checkbox] into label instead of using label[for=id]

### ISSUE THREAD

**Issue by bttger** [mdn/content#12312]
## What is the new suggestion?
The current docs for the input[type=checkbox] only mention the usage of labels with the `for` attribute. I think it should also mention the possibility to wrap the input into the label. 

```html
<!-- current suggestion -->
<div>
  <input type="checkbox" id="horns" name="horns">
  <label for="horns">Horns</label>
</div>

<!-- addition proposal -->
<div>
  <label><input type="checkbox" name="horns">Horns</label>
</div>
```

## Why is it important or useful?
Wrapping the input directly in the label has some advantages (citing [this](https://stackoverflow.com/a/6293626/11858359) stackoverflow answer):
- No need to assign an id to every checkbox (great!).
- No need to use the extra attribute in the `<label>.`
- The input's clickable area is also the label's clickable area, so there aren't two separate places to click that can control the checkbox - only one, no matter how far apart the `<input>` and actual label text are, and no matter what kind of CSS you apply to it.

#### How many pages are likely to be needed? How much time do you think this work should take? 
It would only be an addition to [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox) page - couple of minutes of work. I would create a PR if others agree.

Will the work enable learners or professionals to achieve their goals better? _IMO yes_
Does it address critical needs in the web industry? _No_
Is the work an operational necessity, i.e. is not having it a security risk? _No_
Does the content help make the web more ethical? _No_

MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

**Comment by danieldafoe** [comment]
Perhaps this is obvious, but I think we should ensure that your new suggestion also looks the same way as the original suggestion that uses the `<input>` outside the `<label>`. It would further illustrate that both can accomplish the same thing.

**Comment by teoli2003** [comment]
> I would create a PR if others agree.

I went ahead and assigned this issue to you. (If you don't want anymore, or can't, no worry, just unassign you!)
