### ISSUE TITLE
Issue with "WindowEventHandlers.onbeforeprint": …

### ISSUE THREAD

**Issue by changesbyjames** [mdn/content#1231]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeprint

#### What information was incorrect, unhelpful, or incomplete?
While the compatibility grid is correct, the article itself says that the `window.onbeforeprint` function and `window.addEventListener("beforeprint", () => { ... })` event type aren't supported in safari and suggests a polyfill. This isn't true and is supported, leading to confusion.

#### Specific section or headline?
Polyfill

#### What did you expect to see?
That section not being there or with the caveat that it's not longer needed.

#### Did you test this? If so, how?
I attempted to use the documented syntax in Safari and it worked as expected.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/windoweventhandlers/onbeforeprint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeprint
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/windoweventhandlers/onbeforeprint/index.html
* Report started: 2021-01-12T17:41:11.511Z

</details>

**Comment by chrisdavidmills** [comment]
Hi @changesbyjames !

Thanks for reporting this. I've fixed this by removing the polyfill section; see https://github.com/mdn/content/commit/909ae0493a12f3d91b1442caffd53cceaf15f60c
