### ISSUE TITLE
Issue with "Accessible multimedia": (Undeclare variable)

### ISSUE THREAD

**Issue by horusofoz** [mdn/content#12339]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Multimedia

#### What information was incorrect, unhelpful, or incomplete?
`mediaTime` is given a value without being declared. 

#### Specific section or headline?
Last code block of [Creating custom audio and video controls](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Multimedia#creating_custom_audio_and_video_controls).

#### What did you expect to see?
`mediatime` is declared before it is used,

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/accessibility/multimedia`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Multimedia
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/accessibility/multimedia/index.md
* Last commit: https://github.com/mdn/content/commit/e02edd1a3ba752a88c65e6e8c1ad4049b70adab8
* Document last modified: 2022-01-22T00:04:46.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #12340 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
