### ISSUE TITLE
@font-face/src incorrectly describes the values accepted by the `local()` specifier

### ISSUE THREAD

**Issue by nk9** [mdn/content#12347]
## Specific page section or heading?

[`@font-face/src`, Formal Syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src#formal_syntax)

## What is the problem?

The Formal Syntax claims that the value which should be passed to `local()` is the "family-name". In fact, [the CSS spec](https://www.w3.org/TR/css-fonts-3/#font-face-name-value) makes clear that the value should describe the font face:

>The locally-installed <font-face-name> argument to local() is a format-specific string that uniquely identifies a single font face within a larger family.

>For OpenType and TrueType fonts, this string is used to match only the Postscript name or the full font name in the name table of locally available fonts. Which type of name is used varies by platform and font, so authors should include both of these names to assure proper matching across platforms.

This piece of advice seems super relevant for web developers.

## Did you test this? If so, how?

I discovered this issue while testing with Firefox, Chrome and Safari on macOS 11.6.2. Firefox and Chrome generally require e.g. `local("Helvetica-Oblique")` here to render an italic version of the font, whereas Safari happily accepts `local("Helvetica")` and works out which font face is meant. You can use the following code on different browsers to see the issue:

```
<html>
  <head>
  <style>
    body {
      font-family: "Helvetica";
    }

    @font-face {
      font-family: "Helvetica";
      font-style: italic;
      font-weight: 400;
      font-display: swap;

      /* Font family name will display roman text on most browsers */
      src: local("Helvetica");

      /* Font face PostScript name will display italic text on all browsers */
      /*src: local("Helvetica-Oblique");*/
    }
  </style>
  </head>

  <body>
    <em>This should be italic.</em>
  </body>
</html>
```

**Comment by tlylt** [comment]
Hi @nk9, 

I just checked the section referenced by you and it seems that perhaps the content has already been corrected.
Instead of
> The Formal Syntax claims that the value which should be passed to local() is the "family-name"

It currently states: `local(<font-face-name>)`, which `<font-face-name>` is explained above as:
> Specifies the full name or postscript name of a locally-installed font face using the local() component value, which uniquely identifies a single font face within a larger family. The name can optionally be enclosed in quotes. The font face name [is not case-sensitive](https://w3c.github.io/csswg-drafts/css-fonts-3/#font-family-casing).

Hope that's clear about what arguments are accepted by `local()` and perhaps @sideshowbarker can close this issue?

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/12347#issuecomment-1407901565

**Comment by bsmth** [comment]
Side note that these pages have been refreshed recently in:

- [x] https://github.com/mdn/content/pull/23085
- [x] https://github.com/mdn/content/pull/23375

**Comment by nk9** [comment]
Thanks for this, glad to see the docs have been corrected. However, I notice that the new wording still doesn't include the W3C recommendation about using both names:

> For OpenType and TrueType fonts, this string is used to match only the Postscript name or the full font name in the name table of locally available fonts. Which type of name is used varies by platform and font, so authors should include both of these names to assure proper matching across platforms.

Isn't that useful advice for web developers to have when they're looking up how to use this parameter in MDN?

**Comment by tlylt** [comment]
Thanks @nk9 for following up on this. I have raised a PR to add the recommendation. 

> The first Example block does contain a @font-face using both names of Gill Sans, with comments, but no explanation about why both names should be provided. And the previous example in that block (Futura Medium) doesn't follow the recommended practice of providing both names. Isn't this compatibility advice useful for web developers to have when they're looking up how to use this parameter in MDN?

I do see that examples on the W3C page also omit providing both names at times, I suppose that's fine if some examples are not focused particularly on the `local()` part. Hence, I have not make changes to the examples in MDN.
- https://www.w3.org/TR/css-fonts-3/#font-face-name-value:~:text=src%3A%20local(Gentium)%2C%20%20%20%20/*%20use%20locally%20available%20Gentium%20*/
- https://www.w3.org/TR/css-fonts-3/#font-face-name-value:~:text=src%3A%20local(HiraKakuPro%2DW3)%2C%20local(Meiryo)%2C%20local(IPAPGothic)%3B
