### ISSUE TITLE
Issue with "Concurrency model and the event loop": event loop is not concurrency

### ISSUE THREAD

**Issue by jcubic** [mdn/content#12352]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop

#### What information was incorrect, unhelpful, or incomplete?

Using word concurrency in this article is really misleading. The event loop is not a model of concurrency. The only concurrency that you can have in JavaScript is by using WebWorkers. At least in the browser.

#### Specific section or headline?
The headline and first sentence.

#### What did you expect to see?

Removing word concurrency from this article.

#### Did you test this? If so, how?
Compare Wikipedia articles:
* [Event Loop](https://en.wikipedia.org/wiki/Event_loop)
* [Concurrent computing](https://en.wikipedia.org/wiki/Concurrent_computing)

Quoting Wikipedia (second link):

> A concurrent system is one where a computation can advance without waiting for all other computations to complete.

This eliminates Event Loop because Event Loops is sequential.

If I'm wrong please provide the source of information that can confirm that Event Loop is a concurrency model. Everything in computer science has a name and you can't use it in a different context because it will be really confusing.

If you want proof. Read this article on DEV:

[Concurrency In JavaScript](https://dev.to/kalashin1/concurrency-in-javascript-4oho) and discussion in comments. The article was created by someone that read this on MDN.

**Comment by jcubic** [comment]
I suggest changing the name "concurrency" to "asynchronous".

**Comment by sideshowbarker** [comment]
> Using word concurrency in this article is really misleading. The event loop is not a model of concurrency. The only concurrency that you can have in JavaScript is by using WebWorkers.

Indeed. So, thanks for catching this — I’ve opened #12354 with a fix.

> At least in the browser.

I’m pretty the same holds true for any JavaScript runtime, anywhere — including Node and Deno.

A few years back, Apple’s JavaScript compiler architect wrote up a really interested, detailed outline at https://webkit.org/blog/7846/concurrent-javascript-it-can-work/ of what it would take to bring real concurrency to the entire JavaScript heap. But as far as I know, it’s just remained an thought experiment.

> I suggest changing the name "concurrency" to "asynchronous".

My patch in #12354 just replaces ”concurrency model“ with “runtime model”. But if you feel it’s important to put “asynchronous” in there too, I guess we could work it in. But to me at least it doesn’t seem strictly necessary to mention it at that point in this particular article.

**Comment by jcubic** [comment]
@sideshowbarker runtime is fine, it was just a suggestion, the only one that came into my mind.
