### ISSUE TITLE
Issue with "String.prototype.lastIndexOf()": lastIndexOf returning wrong response

### ISSUE THREAD

**Issue by K-Vishwak** [mdn/content#12351]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/lastIndexOf

#### Did you test this? If so, how?
`const testString = "locate string locate";`
`
testString.lastIndexOf('locate');`
`> 14`
`
testString.lastIndexOf('locate', 14);`

`> 14 - how it is possible?`

![image](https://user-images.githubusercontent.com/18037623/150651229-2a1bc883-be7b-4b5f-ad9d-b81997772ce9.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/lastindexof`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/lastIndexOf
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/lastindexof/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
For which case do you think the return value is wrong?

`testString.lastIndexOf('locate')`? `testString.lastIndexOf('locate', 14)`? Or both?

What do you expect the return value to be, if not `14`? And why?

**Comment by K-Vishwak** [comment]
@sideshowbarker 

in first case it is valid as its lastIndex is 14 in whole string.

Where as in second case, I have provided position as 14 from which to beginning it should ideally look for..

Hence if my position is 14.. String search becomes - 'locate string l' - Hence lastIndexOf('locate', 14) will be 0 only right? how come it is 14.

![image](https://user-images.githubusercontent.com/18037623/150669576-33ed9924-1104-43ee-aca4-6be207f65325.png)

If you see the image above, 'string' is at index 7 in whole string. If I give 6 as position, it thrown -1 whereas if I give 7 showing 7 as still should be -1 because string search for became 'locate s' - there is no string in it hence should be -1.

**Comment by sideshowbarker** [comment]
> Hence if my position is 14.. testString becomes - 'locate string l'

No — it’s zero-indexed, so the position it starts searching at is at `locate string `.

And so at that position — at position 14, where you asked it to start searching — it finds the second substring `locate`, and doesn’t find any other `locate` substring after that.

And so it returns 14 as the position at which is found the last `locate` substring.

> Hence lastIndexOf('locate', 14) will be 0 only right?

No

> how come it is 14.

Because that’s the position in `testString` at which the `lastIndexOf('locate', 14)` call finds the last `locate` substring.

**Comment by sideshowbarker** [comment]
> If you see the image above, 'string' is at index 7 in whole string. If I give 6 as position, it thrown -1

That’s because *fromIndex* is:

> The index of the **last** character in the string to be considered as **the beginning of a match**.

So at position 6 in `testString` there is not the beginning of a match for `string` — there’s no match there, because `string` starts at position 7. But by specifying `6`, you’ve told `lastIndexOf()` to **stop** searching for the beginning of a match at position 6 and **look no further**. So it never moves on to checking the string at position 7.

> whereas if I give 7 as position then it is returned 7 as it still should be -1 because testString became 'locate s' - there is no 'string' in it hence should be -1.

No — it finds **the beginning of a match** of a match for `string` — that is, it finds an `s` — and so then it keeps checking, looking for a `t`, and then an `i`, etc., until it finds a match for the whole substring `string`, successfully.

**Comment by K-Vishwak** [comment]
@sideshowbarker I got the whole info but my question is:

When position is given,

`const testString = 'locate string locate'` - Position - 7 means points to `s` its an index from starting - Correct my understanding if I am wrong.

now,

testString.indexOf('string', 7); returns 7 - valid.  As per DOCs, 7 onwards to end - search will happen.
testString.lastIndexOf('string', 7); returns 7 - seems invalid to me. As per DOCs, 7 onwards to beginning - search will happen. 

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/lastIndexOf

`The lastIndexOf() method returns the index within the calling String object of the last occurrence of the specified value, searching backwards from fromIndex. Returns -1 if the value is not found.`

Do you mean to say in both the cases search will happen towards end from the position?

**Comment by Andrew-Cottrell** [comment]
> The lastIndexOf() method returns the index within the calling String object of the last occurrence of the specified value, `searching backwards from fromIndex`. Returns -1 if the value is not found.

I agree, that is very confusing. The description should avoid implying any particular implementation strategy. Perhaps the introduction could be changed to

> The `lastIndexOf()` method returns the index within the calling [`String`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String) object of the last occurrence of the specified value, searching between `fromIndex` and the end of the calling `String` object. Returns `-1` if the value is not found.

**Comment by K-Vishwak** [comment]
@Andrew-Cottrell  Thank you. Could this be improvement to MDN docs?

Also, could you please answer my last part of above comment?

i.e.;

Should we consider search from position towards beginning or to end? or just in this case it will search to end and in remaining towards beginning?

If that's the case, it's really weird.  

![image](https://user-images.githubusercontent.com/18037623/150686963-7f3c4978-f9d0-43fd-95ad-eaf28a211755.png)

Thank you.

**Comment by Andrew-Cottrell** [comment]
> Should we consider search from position towards beginning or to end? or just in this case it will search to end and in remaining towards beginning?

My advise is to simply understand what the function returns without considering if a specific implementation searches from the beginning, end, or even from the middle outwards in both directions!

In the [ECMAScript specification](https://tc39.es/ecma262/multipage/text-processing.html#sec-string.prototype.lastindexof), the search begins at `fromIndex` and works back towards index `0`. But JavaScript engine implementations can do anything that has the same observable result. At each search index, the implementations will attempt to match the `searchValue` code unit by code unit from the index forwards (past the `fromIndex` as neccessary).

**Comment by Andrew-Cottrell** [comment]
> Could this be improvement to MDN docs?

Yes. Either yourself, or someone else, can [create a pull request](https://developer.mozilla.org/en-US/docs/MDN/Contribute/GitHub_beginners) that changes the introduction of the [`lastIndexOf` page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/lastIndexOf). You could use [my suggestion above](https://github.com/mdn/content/issues/12351#issuecomment-1019505317) or something else. Your pull request would be reviewed and hopefully merged into the main codebase.

**Comment by K-Vishwak** [comment]
> A good way to think about it, is the following algorithm

Hmm. Thinking & understanding won't be a problem. I got the complete concept but this could lead to issues. 

Thank you so much for the explanation @Andrew-Cottrell .

**Comment by K-Vishwak** [comment]
> Yes. Either yourself, or someone else, can [create a pull request](https://developer.mozilla.org/en-US/docs/MDN/Contribute/GitHub_beginners) that changes the introduction of the [`lastIndexOf` page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/lastIndexOf). You could use [my suggestion above](https://github.com/mdn/content/issues/12351#issuecomment-1019505317) or something else. Your pull request would be reviewed and hopefully merged into the main codebase.

Thanks. I will try to do it.

**Comment by K-Vishwak** [comment]
> Thank you so much for the explanation @Andrew-Cottrell .

I am still feeling that we could suggest this improvement to ECMA. Can we do that anywhere?

**Comment by Andrew-Cottrell** [comment]
> I am still feeling that we could suggest this improvement to ECMA. Can we do that anywhere?

Suggestions can be made at https://es.discourse.group/. I'm unclear which improvement might be suggested. Changes that are backwards incompatible are highly unlikely to be accepted.

**Comment by sideshowbarker** [comment]
> > The lastIndexOf() method returns the index within the calling String object of the last occurrence of the specified value, `searching backwards from fromIndex`. Returns -1 if the value is not found.
> 
> I agree, that is very confusing. The [MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/lastIndexOf) should avoid implying any particular implementation strategy. Perhaps the introduction could be changed to something like
> 
> > The `lastIndexOf()` method returns the index within the calling [`String`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String) object of the last occurrence of the specified value that occurs at an index that is less than or equal to `fromIndex`. Returns `-1` if the value is not found.

Thanks much — based on that, I’ve opened #12385 with some rewrites to both the `lastIndexOf()` doc and also (for consistency/parallelism), rewrites to the `indexOf()` doc as well. Review comments over there would be much welcome.
