### ISSUE TITLE
Issue with "<input type="file">": capture on iOS

### ISSUE THREAD

**Issue by kaominghsu** [mdn/content#12379]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

#### What information was incorrect, unhelpful, or incomplete?

capture is not control on IOS,So not Full support on IOS and this not safe.
because not turn off camera on IOS

#### Specific section or headline?
capture 

#### What did you expect to see?
turn off camera

#### Did you test this? If so, how?
Tell IOS how did turn off camera

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/file`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/file/index.md
* Last commit: https://github.com/mdn/content/commit/1314ac4ed0049401ce0c84fbb7103527c37d75fa
* Document last modified: 2022-01-18T02:36:46.000Z

</details>

**Comment by Josh-Cena** [comment]
I'm unsure what this issue is asking about. If it's about exiting the camera view, then you can already tap the "Cancel" button. If it's about removing the "Take photo" option when capture is unspecified, then I believe it's impossible.

I'm going to close given the limited information in this issue but feel free to follow up.

**Comment by kaominghsu** [comment]
hi,Josh

Sorry, I was so busy that I forgot to reply

Let's I have a website or an APP with an embedded web page
When I have not opened the "capture" permission, I can select "capture" in the <input type="file"> on the web page
this is an unreasonable situation

> I'm unsure what this issue is asking about. If it's about exiting the camera view, then you can already tap the "Cancel" button. If it's about removing the "Take photo" option when capture is unspecified, then I believe it's impossible.
> 
> I'm going to close given the limited information in this issue but feel free to follow up.

**Comment by Josh-Cena** [comment]
Thanks, but that would be out of scope for MDN to fix. Could you file an issue for Safari instead?

**Comment by kaominghsu** [comment]
How do I get to the discussion boards in Safari?

> Thanks, but that would be out of scope for MDN to fix. Could you file an issue for Safari instead?

**Comment by Josh-Cena** [comment]
https://bugs.webkit.org/

**Comment by kaominghsu** [comment]
> https://bugs.webkit.org/

thanks your help,
I report this bug.
