### ISSUE TITLE
Issue with "DOM Inspector": …

### ISSUE THREAD

**Issue by mdcclxv** [mdn/content#1238]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Add-ons/DOM_Inspector

The page above is elaborating on a non-existent add-on. It shoud iether be updated with links to the new (maybe renamed) addon or completely removed as it no longer has any use except wasting reader's time.

@Firefox devs: why in the world did you remove the DOM Inspector addon?!?!?!?!?!?!?

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @mdcclxv 

I've deleted all the Firefox DEvTools add-ons stuff, as it is all out of date.

FYI, this is an old add-on that provided a DOM inspector back in the days when we didn't have a decent DOM inspector built in to the browser. We are not getting rid of the built-in DOM inspector.
