### ISSUE TITLE
Videos at your first web extension are private

### ISSUE THREAD

**Issue by Schereo** [mdn/content#12382]
The videos at this url https://developer.mozilla.org/de/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension are private and cannot be watched.

**Comment by sideshowbarker** [comment]
Those videos have already been removed from the `en-US` content. But the `de` content is currently frozen.

https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.

In the meantime,
