### ISSUE TITLE
Issue with "Introduction": Explain why IIFE "massively improves performance"

### ISSUE THREAD

**Issue by ML-Chen** [mdn/content#1239]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Introduction

#### Specific section or headline?
The end of the introduction says:

```
But for now, remember to always include the `(function(){"use strict";` before your code, and add `})();` to the end of your code. You will learn [what these mean](https://developer.mozilla.org/en-US/docs/Glossary/IIFE), but for now they can be thought of as doing the following:

-  Massively improve performance.
-  Prevent semantics in JavaScript that trip up beginners.
-  Prevent code snippets executed in the console from interacting with one-another (e.g., having something created in one console execution being used for a different console execution).
```

#### What information was incorrect, unhelpful, or incomplete?

It says that it massively improves performance, but I don't see anywhere on the IIFE page on MDN or Wikipedia that explains why it does improve performance, compared to code just executed in the top level. Is it `'use strict'` that is supposed to improve performance?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Introduction
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/guide/introduction/index.html
* Report started: 2021-01-13T00:11:36.634Z

</details>

**Comment by sideshowbarker** [comment]
> The end of the introduction says:
> 
>
> > But for now, remember to always include the `(function(){"use strict";` before your code, and add `})();` to the end of your code. You will learn [what these mean](https://developer.mozilla.org/en-US/docs/Glossary/IIFE), but for now they can be thought of as doing the following:
> > 
> > -  Massively improve performance.
> > …

I suggest we just completely drop that *“Massively improve performance”* statement. I at least have no idea why it was ever added there.

> It says that it massively improves performance, but I don't see anywhere on the IIFE page on MDN or Wikipedia that explains why it does improve performance,

I think clearly an IIFE doesn’t improve performance at all, especially not “massively”. 

> Is it `'use strict'` that is supposed to improve performance?

Yeah, I suspect it was added to refer to `use strict`. But even there, it’s not going to improve performance “massively” in the normal case.

So I suggest:

* completely dropping the *“Massively improve performance”* bullet point
* replace the `You will learn [what these mean](https://developer.mozilla.org/en-US/docs/Glossary/IIFE)…` part with something like `The <a href="/en-US/docs/Web/JavaScript/Reference/Strict_mode">strict mode</a> and <a href="/en-US/docs/Glossary/IIFE>IIFE</a> articles explain what those do…`

If you want to write up a patch with those changes, I’d be happy to review it. I guess there’s more that could be done to improve that article, but just those changes would be a good start.

**Comment by Rumyra** [comment]
Re-opening as only the second bullet was changed on the commit I just merged 👍

**Comment by Rumyra** [comment]
Apologies @ML-Chen my oversight. Re-closing and thank you!
