### ISSUE TITLE
Content bug: 'diagnostic is not found' error.

### ISSUE THREAD

**Issue by Alexico1969** [mdn/content#12393]
## What page(s) did you find the problem on?

https://projects.codewizardshq.com/i_h24_capstone_02/index.html

## Specific page section or heading?

??

## What is the problem?

When I try to use the WebSpeech API, all of a sudden I'm getting an 'diagnostic is not defined' error.
This code used to work perfectly well !!

## What did you expect to see?

A working API that recognized the words spoken, then go to other pages on command.

## Did you test this? If so, how?

I've pushed the microphone button. Then spoke the command 'color'.
But I got an error instead of a working app !

**Comment by sideshowbarker** [comment]
This seems like a question more suited to a site such as https://stackoverflow.com/
