### ISSUE TITLE
Issue with "Style Editor": 3rd YouTube video in article is private

### ISSUE THREAD

**Issue by WalkTheMaxPlanck** [mdn/content#12419]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Style_Editor

#### What information was incorrect, unhelpful, or incomplete?

The second youtube video under the "The media sidebar" section, right above the title for the "Creating and importing style sheets" section is no longer functioning, since it has apparently been made private.

#### Specific section or headline?

The media sidebar

#### What did you expect to see?

A functioning youtube video

#### Did you test this? If so, how?

I opened the webpage in both firefox and chrome.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/style_editor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Style_Editor
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/style_editor/index.html
* Last commit: https://github.com/mdn/content/commit/dc9f7fd11b7ddff380d9293fa53bc7a536cbc7f7
* Document last modified: 2022-01-13T06:25:14.000Z

</details>

**Comment by JavascriptLearner815** [comment]
Screenshot: 
![image](https://user-images.githubusercontent.com/59782978/151086484-ab8d015d-f674-4410-8861-987e7fc62301.png)

**Comment by JavascriptLearner815** [comment]
This is a valid issue.

**Comment by sideshowbarker** [comment]
Thanks — this is a known issue that we’re already tracking over at https://github.com/mdn/content/issues/7457
