### ISSUE TITLE
Issue with "var": Link to "delete" operator doesn't work

### ISSUE THREAD

**Issue by ML-Chen** [mdn/content#1241]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var

The link to the "delete" operator, made using {{jsxref("delete")}}, doesn't work. Mousing over it says says, "The documentation about this has not yet been written".

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/var`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/statements/var/index.html
* Report started: 2021-01-13T01:41:49.295Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/1245 with a fix.
