### ISSUE TITLE
Issue with "Extension Storage": (Screen shot and description don't match current version 97)

### ISSUE THREAD

**Issue by jackrg** [mdn/content#12439]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector/Extension_Storage

#### What information was incorrect, unhelpful, or incomplete?
1) Screen shot does not match current look.
2) There is no longer a "Storage" tab"; it is now apparently part of the "Application" tab.
3) There is no "Extension Storage" section in the tree (presumably because you already selected which Extension) before you get to the Storage tree.
3) "Storage Area" column does not exist any more.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/storage_inspector/extension_storage`
* MDN URL: htt
<img width="1086" alt="Screen Shot 2022-01-26 at 4 06 54 PM" src="https://user-images.githubusercontent.com/962177/151267585-43d56319-4c76-4bee-9921-28851894cd77.png">
ps://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector/Extension_Storage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/storage_inspector/extension_storage/index.html
* Last commit: https://github.com/mdn/content/commit/0ea5ea66ca3ff5f0c02583c1f3606b3b7d4aee40
* Document last modified: 2021-02-02T16:28:31.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks for reporting this. Which Firefox version is yours? This is what I see on mine:-

![image](https://user-images.githubusercontent.com/2392803/151683586-dc3f2484-4422-4682-bf98-e5d4482246b1.png)

**Comment by jackrg** [comment]
Thanks for the response. My version is 96.0.2. My question for you: what did you do to put that value there? If you used the interface, that would be cheating. I’m using browser.storage.local.set({key: value}) in the background page, and no value is showing up.

**Comment by himanshugarg** [comment]
Hi, yes that's right. The value comes from the use of [this](https://github.com/mdn/webextensions-examples/tree/master/annotate-page) temporarily loaded Add-on. Didn't modify it using the API.

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
