### ISSUE TITLE
Remove `{{draft}}` macro calls from the Accessibility tree

### ISSUE THREAD

**Issue by ddbeck** [mdn/content#12459]
https://github.com/mdn/content/pull/10504 removed all `{{draft}}` Kumascript macro calls _except_ those in the `/docs/Web/Accessibility` tree. Once the work is completed on ARIA roles, the following tasks need to be completed:

- [ ] Remove the macro calls from all remaining docs
- [ ] Comment on https://github.com/mdn/yari/pull/4943 to proceed with macro removal

**Comment by ddbeck** [comment]
@estelle, I've assigned this issue to you, since you requested that we retain the macros in https://github.com/mdn/content/issues/10504#issuecomment-970624479. I think you're the best person to know when the work is completed, such that the macro can be safely removed.

**Comment by estelle** [comment]
When https://github.com/mdn/content/pull/12650 is merged....

**Comment by teoli2003** [comment]
@estelle I may be mistaken, but it seems to me that there is one left there: https://developer.mozilla.org/en-US/docs/web/accessibility/accessibility_and_spacial_patterns

**Comment by estelle** [comment]
I don't see any {{draft}} occurrences anymore, anywhere, in mdn/content.

**Comment by estelle** [comment]
https://github.com/mdn/content/pull/15874
