### ISSUE TITLE
Issue with "Encoding API": incomplete interface links on sidebar

### ISSUE THREAD

**Issue by hakkikonu** [mdn/content#12464]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Encoding_API

#### What information was incorrect, unhelpful, or incomplete?
`TextDecoderStream` and `TextEncoderStream` don't exist on left sidebar.

#### Specific section or headline?
left sidebar

#### What did you expect to see?
`TextDecoderStream`
`TextEncoderStream` 
links

#### Did you test this? If so, how?
visual

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/encoding_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Encoding_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/encoding_api/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Hakkı, thanks for catching this — I’ve raised #12466 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
