### ISSUE TITLE
Issue with "NSPR functions": broken links to the indiviual functions' documentation pages

### ISSUE THREAD

**Issue by bagder** [mdn/content#12471]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Reference/NSPR_functions

#### What information was incorrect, unhelpful, or incomplete?

The links to all the PR_* functions are "dead". They don't link to correct documentation.

**Comment by sideshowbarker** [comment]
Apparently, the NSS content that contains the NSPR links is itself supposed to have been removed from MDN already. See #10904 and #10903 and #8215. And I think the NSPR stuff it linked to doesn’t yet exist anywhere else that redirects could be set up for — except for the GitHub view of the archive at https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/projects/nspr.

@mdn/yari-content-mdn: I don’t know if somebody from Mozilla has an open action on this, but it seems like this one is likely to keep coming up

**Comment by sylvestre** [comment]
Hello Daniel, 
Nice to "see" you again ;)

We moved most of the Firefox internal doc away from MDN to https://firefox-source-docs.mozilla.org/

NSS & NSPR are a bit special, we kept NSS on MDN https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS
but it seems that it isn't the case for NSPR :/ We should probably have done the same for NSPR.
@ckerschb @beurdouche we should discuss next week about the next step for the NSS/NSPR documentation ;)

Now, about your message https://curl.se/mail/lib-2022-01/0120.html, this documentation situation isn't a sign of lack of interest or maintenance on NSS. The project is alive and maintained.

**Comment by beurdouche** [comment]
At this point I think I am fine killing the old NSS doc entirely. The new doc will be progressively rewritten at firefox-source-docs and having the old one see to confuse people. Let me make that happen.

**Comment by bagder** [comment]
> this documentation situation isn't a sign of lack of interest or maintenance

Prove it. The NSS documentation situation has been miserable forever and it took another deep dive now.

**Comment by ddbeck** [comment]
@sylvestre @beurdouche I'd also like to remove the NSS docs from MDN, since it's not within MDN's current scope. I'd be more than happy to help make that happen on the MDN side of things, but I would like to redirect somewhere useful (even if that's just a page in the Firefox source docs with a brief explanation of why they were removed), since past removals without redirects have provoked a lot of issues. Is there anything else I can do to support this move?

**Comment by sylvestre** [comment]
@ddbeck let's chat about that in the next few weeks ;)

**Comment by sylvestre** [comment]
@bagder the work is available here https://firefox-source-docs.mozilla.org/security/nss/index.html

**Comment by bagder** [comment]
Thanks. Since I was initially curious about `PR_Read()` details I searched for that on this "new" site and found this:

https://firefox-source-docs.mozilla.org/security/nss/legacy/reference/nspr_functions/index.html?highlight=pr_read

I then click the PR_Read link there, which takes me to https://firefox-source-docs.mozilla.org/en-US/PR_Read which has this great content:

~~~
404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: en-US/PR_Read
    RequestId: A2F2QFETTT7366KQ
    HostId: PZKuTenPreyp3chRAVUyL8u9khtYwmz1XL6EIJFLqXMb0adK4EIyDGTYNZpUywQpT/ryx7hEYk0=

**Comment by sylvestre** [comment]
Yeah, NSPR needs love too!

**Comment by sylvestre** [comment]
work started here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1753127
