### ISSUE TITLE
Issue with "image-orientation": cross-origin limitations

### ISSUE THREAD

**Issue by matthewwithanm** [mdn/content#12484]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation

#### What information was incorrect, unhelpful, or incomplete?

As discussed in w3c/csswg-drafts/issues/5165, this behavior is no longer supported for cross-origin images. This severely limits its usefulness and means that the old default behavior (where EXIF data was ignored) can no longer be achieved for cross-origin images.

- [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1655598) (Open)
- [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1110330) (Closed)
- [Webkit bug](https://bugs.webkit.org/show_bug.cgi?id=217294) (Closed)

#### What did you expect to see?

The page should probably have a big callout about this.

#### Did you test this? If so, how?

Yes, I created a page that loads an image with an EXIF rotation and set `image-orientation: none` on it. When using a cross-origin image, the image was flipped according to the EXIF data (in Chrome). When using a same-origin image, the EXIF data was ignored.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/image-orientation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/image-orientation/index.md
* Last commit: https://github.com/mdn/content/commit/0469140da76b9b593251a191c63a2ee92abc1774
* Document last modified: 2021-09-15T02:25:12.000Z

</details>

**Comment by tlylt** [comment]
Hi there,
- [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1655598) is now closed (~3 months ago)
- there's no mention of this change in the [CSS-images-3 draft](https://drafts.csswg.org/css-images-3/#the-image-orientation)

I am not sure if I can find any official reference on this change besides the csswg-drafts issue, @sideshowbarker should we still proceed now with adding a call-out on this or?

**Comment by sideshowbarker** [comment]
> should we still proceed now with adding a call-out on this or?

Yeah — MDN should document what browsers actually do, even in cases where it differs from what the current spec states.
