### ISSUE TITLE
Issue with "EventTarget.addEventListener()": removeEventListener line of text should be removed

### ISSUE THREAD

**Issue by griffintucker** [mdn/content#12500]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

#### What information was incorrect, unhelpful, or incomplete?
the removeEventListener below the introductory  paragraph is confusing and unnecessary and should be removed

#### Specific section or headline?
the line of text "They do not need to be removed manually with removeEventListener()." on it's own line of text

#### What did you expect to see?
removeAddListener description should only be mentioned later on, or otherwise the paragraph that precedes it should include this text as "…for this target, they are not added a second time and they do not need to be removed" to clear up the confusion

#### Did you test this? If so, how?
i'm following the tutorials from a fresh set of eyes, and this line threw me.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/eventtarget/addeventlistener`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/eventtarget/addeventlistener/index.md
* Last commit: https://github.com/mdn/content/commit/2bef9a5f18175148702ab2bb3ef5512205eca6da
* Document last modified: 2022-01-19T12:35:54.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12502 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

**Comment by griffintucker** [comment]
maybe it shouldn't be dropped and should just be moved to the end of the previous paragraph; it may be helpful to link to the `removeEventListener()` doc
