### ISSUE TITLE
Issue with "CSS basics": Probable Copyright Infringement

### ISSUE THREAD

**Issue by barryhunter** [mdn/content#12512]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics

#### What information was incorrect, unhelpful, or incomplete?

This article appears to use a copyrighted image without attribution. 

The image, is available for reuse, but the creative commons licence requires attribution. See th original at
https://www.geograph.org.uk/photo/3418115
Can see the image was htere since 2013, before the MDN article was published. 

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics#css_all_about_boxes

#### What did you expect to see?

Attribution and copyright notice with the image. 

Something like:

- A stack of boxes, Pylafoot - cc-by-sa/2.0 - © Jim Barton - geograph.org.uk/p/3418115

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/css_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/css_basics/index.md
* Last commit: https://github.com/mdn/content/commit/a95f494d9fb76cf99efd92722109056ec8090f15
* Document last modified: 2021-12-16T21:56:04.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12520 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

**Comment by aroramrinaal** [comment]
Hey @sideshowbarker , I am new to Open Source could you please guide me to some **good-first-issues**.
