### ISSUE TITLE
Content suggestion: Improve Table of Contents for WebAssembly documentation

### ISSUE THREAD

**Issue by ghghost** [mdn/content#12513]
The current ToC for the WebAssembly reference doc is only 2 levels deep (to #.# headings). It should be extended to #.#.# sections.

The current ToC makes it very awkward for developers to navigate to specific topics, e.g., Table Instructions.

I don't know from what original format the current spec viewable on the Web is generated, but I'd be surprised if adding another couple of dozen ToC markers would require more than an hour of work.  It should be done by whoever is currently maintaining the document.

MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly

**Comment by Josh-Cena** [comment]
The WASM docs follow the MDN structure norms. The lack of H3 headings in the TOC is a platform issue, which is discussed in https://github.com/orgs/mdn/discussions/162.
