### ISSUE TITLE
Content suggestion: Provide a more useful History section for the WebAssembly specification

### ISSUE THREAD

**Issue by ghghost** [mdn/content#12515]
Replace the current History section of the WebAssembly documentation with one that tracks individually, with dates, every significant change to the specification.

The current History section is next to useless for developers who want to track changes. The "History" changes frequently and unpredictably, in major ways, as does the specification, even though the version number (currently 1.1) is not incremented.

The maintainer of the documentation clearly wants to be conscientious about documenting changes. If it were done according to the usual professional standards, it would be no more work, and would be much more helpful.

MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly

**Comment by wbamberg** [comment]
Thanks for filing!

I don't see a "History" section in https://developer.mozilla.org/en-US/docs/WebAssembly, nor can I find it in the history of this page.

On MDN, although we do occasionally document significant spec changes when a change is likely to confuse people, we don't as a rule document all the significant changes to specifications: we aim to provide up to date documentation for the web as it exists now.
