### ISSUE TITLE
Issue with "Object prototypes": browser console example should remove redundant 'console.log()'

### ISSUE THREAD

**Issue by griffintucker** [mdn/content#12514]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes

#### What information was incorrect, unhelpful, or incomplete?
the first couple of examples say to use the browser console to return and display object properties, but the next one says to use 'console.log' which is inconsistent and redundant

#### Specific section or headline?
console.log(Object.getPrototypeOf(myObject)); // Object {...}

#### What did you expect to see?
Object.getPrototypeOf(myObject);

#### Did you test this? If so, how?
doing the above in the browser console is easier, more efficient, and gets the same information, otherwise the user has to rewrite the complete example in code - it's ok to use console.log() later on in the page for actual code examples

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/objects/object_prototypes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/object_prototypes/index.md
* Last commit: https://github.com/mdn/content/commit/2bef9a5f18175148702ab2bb3ef5512205eca6da
* Document last modified: 2022-01-19T12:35:54.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12521 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
