### ISSUE TITLE
Issue with "Object prototypes": unnecessary blank line in code example

### ISSUE THREAD

**Issue by griffintucker** [mdn/content#12516]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes

#### What information was incorrect, unhelpful, or incomplete?
the blank line in the do/while loop is unnecessary

#### Specific section or headline?
do {  
  object = Object.getPrototypeOf(object);
  console.log(object);

} while (object);

#### What did you expect to see?
do {  
  object = Object.getPrototypeOf(object);
  console.log(object);
} while (object);

#### Did you test this? If so, how?
following the tutorial from a fresh perspective

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/objects/object_prototypes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/object_prototypes/index.md
* Last commit: https://github.com/mdn/content/commit/2bef9a5f18175148702ab2bb3ef5512205eca6da
* Document last modified: 2022-01-19T12:35:54.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12518 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
