### ISSUE TITLE
Content suggestion: css/@font-face/font-feature-settings

### ISSUE THREAD

**Issue by estelle** [mdn/content#12528]
## What is the new suggestion?
css/@font-face/font-feature-settings

## Why is it important or useful?
css/@font-face/font-feature-settings is missing. All other @font-face descriptors are present.

## Other supporting information
https://drafts.csswg.org/css-fonts/#font-rend-desc

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/27513
