### ISSUE TITLE
Code example Reset buttons cut off on narrow screens

### ISSUE THREAD

**Issue by nehalch** [mdn/content#12545]
![Screenshot_20220131-192205_Firefox~2](https://user-images.githubusercontent.com/77306153/151842164-806927b2-aa23-43f1-a1dd-afde3d204b55.png)
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

#### What information was incorrect, unhelpful, or incomplete?
Reset button on Android view.

#### Specific section or headline?
Button.

#### What did you expect to see?
Button.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
* Last commit: https://github.com/mdn/content/commit/5eee57c49a80923d93bca90391537606deeb045b
* Document last modified: 2021-10-25T17:33:52.000Z

</details>

**Comment by estelle** [comment]
If you shrink the window and increase the font size once, this happens on FF on desktop too.

**Comment by wbamberg** [comment]
This is an issue that is (AFAIK) basically impossible to fix in the context of our current example system, in which examples like this are embedded in iframes using a macro.

I'm not sure what to do with it to be honest. We could transfer it to the platform repo in the hope that we might be able to address it as part of a project to implement live/interactive examples differently, but that doesn't really accomplish anything.

**Comment by estelle** [comment]
This appears to have been resolved. Closing.
