### ISSUE TITLE
Issue with "Array.prototype.reduce()": Make variable name in example match documented param name

### ISSUE THREAD

**Issue by klequis** [mdn/content#12549]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

#### What information was incorrect, unhelpful, or incomplete?

Not incorrect. Suggesting a change for clarity.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#function_composition_enabling_piping

#### What did you expect to see?

I was thrown-off for a bit because `input` in this example is called `initialValue` in [Parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#parameters)

I do feel a bit silly by being confused by this but I also think it would help clarity to keep the parameter value the same throughout.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/reduce`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/reduce/index.md
* Last commit: https://github.com/mdn/content/commit/e752a8fe731fbdb9061e39a6e2b797a7ccb7e2b5
* Document last modified: 2022-01-19T17:57:58.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12561 with a fix.
