### ISSUE TITLE
Issue with "Introduction to HTML": Survey callout still relevant?

### ISSUE THREAD

**Issue by glmvc** [mdn/content#12547]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML

#### What information was incorrect, unhelpful, or incomplete?
I noticed the **callout** at the end of this module overview page about taking a survey, and I wonder if that's still relevant at all, because I didn't see it otherwise on the other module overview pages (HTML, CSS and JavaScript Modules).

#### Specific section or headline?
At the end of this page under the assessment.

#### What did you expect to see?
Have not seen or found this on any other page yet.

#### Did you test this? If so, how?
I have looked on the other overview pages.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/index.md
* Last commit: https://github.com/mdn/content/commit/7c66f50d37cff22e46ff91dcf5fa420848c7b2f3
* Document last modified: 2022-01-14T01:16:09.000Z

</details>

**Comment by sideshowbarker** [comment]
cc @mdn/core-yari-content

**Comment by Rumyra** [comment]
Hi @glmvc - thanks for raising this - and yes I think we can remove it 👍
