### ISSUE TITLE
Tables are too wide for mobile screens 

### ISSUE THREAD

**Issue by andneh** [mdn/content#12544]
![Screenshot_20220131-190848_Firefox](https://user-images.githubusercontent.com/77306153/151839961-b9846e11-f187-4ba1-b38d-187810b2e70b.png)
![Screenshot_20220131-190855_Firefox](https://user-images.githubusercontent.com/77306153/151839981-981a02cd-84d9-4745-9d6f-cb9be04959af.png)
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

#### What information was incorrect, unhelpful, or incomplete?
Bad view of table on Android.

#### Specific section or headline?
Table.

#### What did you expect to see?
Responsible view table.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
* Last commit: https://github.com/mdn/content/commit/5eee57c49a80923d93bca90391537606deeb045b
* Document last modified: 2021-10-25T17:33:52.000Z

</details>

**Comment by Josh-Cena** [comment]
After the re-design, the table no longer renders terribly (it is now in its own scrollable container). Tables of this size are fairly common and I don't think we can easily get rid of them. As such I would consider it resolved.
