### ISSUE TITLE
'Issue' with "A first splash into JavaScript": Is this not way too hard as a 'first splash' for total beginner?

### ISSUE THREAD

**Issue by 552020** [mdn/content#1256]
I'm learning JS since a couple of week and I guess if I would have started from the MDN introduction I would have just abandoned it. 

MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/a_first_splash`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/javascript/first_steps/a_first_splash/index.html
* Report started: 2021-01-13T11:46:36.601Z

</details>

**Comment by ML-Chen** [comment]
What parts of the page do you think are too difficult?

**Comment by chrisdavidmills** [comment]
As the writer of these articles, I'd be very interested in some more details here, so please give more feedback.

Taken in isolation, I'd agree that this page would not be a good place to start learning JavaScript, but we need to look at it in context of the rest of the module — the previous article gives you an introduction to what JavaScript is for, and this article is not intended to teach you JavaScript in depth, but to give you a first taste of what it is like to write JavaScript. Subsequent articles then teach all the individual parts in more depth.

**Comment by 552020** [comment]
> What parts of the page do you think are too difficult? Do you have a basic understanding of HTML and CSS?

I completed the HTML course in Codecademy and the most of the CSS: course, so I guess I've a basic understanding of HTML and CSS. I'm doing since a couple of weeks the Codecademy course on JS. The Codecademy course references constantly to the MDN documentation. After completing the module Syntax II on Objects students are asked to read the MDN module  "Introducing JavaScript Objects". I decided to throw a look also to the previous modules starting from the beginning and the first splash was for me a kind of hard splash. I can follow and understand everything and in the Codecademy path  I've built a similar number guesser, but I had the feeling that it was too much information and kind of complex for someone, who had no previous knowledge of JavaScript. The following lessons from "Storing the information you need — Variables" are in my opinion beginner friendly again. 

Just my opinion. It's not really an issue. Therefore the quotation marks in the title of the "Issue".

**Comment by 552020** [comment]
> As the writer of these articles, I'd be very interested in some more details here, so please give more feedback.
> 
> Taken in isolation, I'd agree that this page would not be a good place to start learning JavaScript, but we need to look at it in context of the rest of the module — the previous article gives you an introduction to what JavaScript is for, and this article is not intended to teach you JavaScript in depth, but to give you a first taste of what it is like to write JavaScript. Subsequent articles then teach all the individual parts in more depth.

I wrote an explanation of my feeling answering to ML-Chen: for me it's like too much at once for someone with no previous knowledge of JS. Probably a person willing to learn JS could make it through and every steps are explained but the requested effort is in my opinion to high and it set the expectation for the whole course to very high standard, so people could get scared. 

As I wrote before it's just my opinion as a JS beginner. 

Thanks for having written the course and for the prompt reply!

**Comment by chrisdavidmills** [comment]
Thanks for your thoughts here @552020, it is really useful to consider your point of view here, as often folks who have a lot of experience in a topic are too quick to overlook perceived and actual complexity of a topic, and how that affect's a beginner's ability to engage with a resource.

I'm going to look over the article again and consider whether it needs something added to at least set expectations for the article.

There is no clear action to be taken here, so I'm going to close this, but feel free to add more thoughts here if you wish.

Thanks again.

**Comment by chrisdavidmills** [comment]
As an FYI, I've updated some of the language in the article to try to set clearer expectations: https://github.com/mdn/content/commit/b47f65e0016bdb70db40f77717c1332bad965f6a
