### ISSUE TITLE
[Not Release] [JS] Implement array grouping proposal

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#12579]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

`Array.prototype.groupBy` and `Array.prototype.groupByMap`

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1739648

MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Comment by hamishwillee** [comment]
This is not part of the release as the change is going into nightly only. 
 Status:
 - [ ] BCD - https://github.com/mdn/browser-compat-data/pull/14965
 - [ ] Docs 
    - [ ] `Array.groupBy()`
    - [ ] `Array.groupByToMap()`
    - [ ] [`Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) 
    - [ ] Maybe [Learn web development > JavaScript First Steps > Arrays](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Arrays)
 - [ ] ?Experimental features - not sure about that for JavaScript
 - [ ] dev-docs-complete

**Comment by Josh-Cena** [comment]
@hamishwillee IIUC, this is only waiting for the feature to go stable, right? (Taking much longer than expected)

**Comment by hamishwillee** [comment]
@Josh-Cena Yes. Or to be precise, the documents are done but last time I asked Firefox were testing that the names of the methods were going to be OK. It is a mystery to me how they decide exactly when to ship.

**Comment by hamishwillee** [comment]
Closing this particular issue - the work was done.
