### ISSUE TITLE
Issue with "SVGPoint": Missing deprecation details

### ISSUE THREAD

**Issue by JBoudMS** [mdn/content#12570]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SVGPoint

#### What information was incorrect, unhelpful, or incomplete?
There is no linking or details as to what it has been deprecated in favour of.

#### Specific section or headline?
Deprecated

#### What did you expect to see?
Details about DOMPoint.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/svgpoint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SVGPoint
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/svgpoint/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment]
Yes, that would be nice. FYI often this information gets lost or is hard to find, but sometimes you can find it in the browser compatibility repo - in this case see: https://github.com/mdn/browser-compat-data/pull/10538

**Comment by hamishwillee** [comment]
Should be fixed by #12572
