### ISSUE TITLE
Issue with "Document.onfullscreenchange": (short summary here please)

### ISSUE THREAD

**Issue by r-j-s** [mdn/content#12575]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/onfullscreenchange

#### What information was incorrect, unhelpful, or incomplete?
There is a missing semikolon in the example:

> console.log("FULL SCREEN CHANGE")

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/onfullscreenchange`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/onfullscreenchange
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/onfullscreenchange/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by teoli2003** [comment]
A side-effect of PR #12926 was to fix the problem described here.
