### ISSUE TITLE
[WebAPI] Add support for element.outerText

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#12576]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

`element.outerText`

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1709790

**Comment by hamishwillee** [comment]
element.outerText has now become part of the spec and been added to FF. 

Status:
- [ ] BCD - Add speclinks. Update info about support/standardization
- [ ] Docs
  - [ ] [HTMLElement.outerText](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/outerText) - update doc with live example, and remove info about it being non-standard
  - [ ] [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) - add link to sub topic
  - [ ] Possibly move outerText and friends to `Element`, which is where they are actually defined.
- [ ] Release note - 
- [ ] dev-docs-complete

**Comment by Rumyra** [comment]
🎊
