### ISSUE TITLE
[WebEXT] Support cookieStoreId option in userScripts.register

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#12583]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1738567

**Comment by hamishwillee** [comment]
@Rumyra WebExt stuff just gets assigned to @rebloor right?

**Comment by Rumyra** [comment]
Yes @hamishwillee 👍 I think this month it's mostly APIs and that JS one (which I'm scared to look at tbh 😆)

**Comment by rebloor** [comment]
Addressed in [#13259](https://github.com/mdn/content/pull/13259) & [#15098](https://github.com/mdn/browser-compat-data/pull/15098)

**Comment by Rumyra** [comment]
Thanks @rebloor 👍
