### ISSUE TITLE
[CSS] hyphenate-character now default

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#12580]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Looks like this is not behind a pref for 98 - a good first issue for Dipika

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1751024

**Comment by Rumyra** [comment]
@hamishwillee I realised you did the work on this last release, but it'd be a good first issue for Dipika 🙏

**Comment by hamishwillee** [comment]
@Rumyra Unassigned myself then! 

Dipika welcome! You might find inspiration on the things that need to change in https://github.com/mdn/content/issues/11596. This won't need much if anything for content, but it will need update to BCD, removal from experimental features, and addition of a release note. Happy to help/discuss if you have any questions.

**Comment by Rumyra** [comment]
Me to do data

**Comment by dipikabh** [comment]
Thanks, @hamishwillee! Ruth just demo'ed the whole process to me. I'll get started with this next week and will let you know in case I have questions.

(Adding this comment here will hopefully add me to the list of participants on this issue and allow me to assign the issue to myself)

**Comment by hamishwillee** [comment]
@dipikabh How you going with this? All good?

**Comment by dipikabh** [comment]
Required tasks:

- [ ] Update BCD table to remove preference setting from FF98
- [ ] Update Experimental Features to remove the hyphenate-character table
- [ ] Update Release Notes to add the CSS property
