### ISSUE TITLE
[WebEXT] reduce startup blocking to webRequestBlocking listeners

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#12584]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1749871

**Comment by rebloor** [comment]
Change completed in https://github.com/mdn/content/pull/13192
