### ISSUE TITLE
Issue with "HTTP response status codes": some Http status codes not documented

### ISSUE THREAD

**Issue by ggold7046** [mdn/content#12591]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

#### What information was incorrect, unhelpful, or incomplete?

All below mentioned http status code is missing from the left navigation pane in the references section of HTTP response status codes.

102 Processing (WebDAV), 207 Multi-Status (WebDAV),208 Already Reported (WebDAV),226 IM Used (HTTP Delta encoding),421 Misdirected Request,423 Locked (WebDAV),424 Failed Dependency (WebDAV)

#### Specific section or headline?
references section of HTTP response status codes.

#### What did you expect to see?

All the said response codes to be listed.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/index.md
* Last commit: https://github.com/mdn/content/commit/cdfd4547c1d5ec29d87229ce187a4a401289f335
* Document last modified: 2021-11-18T03:30:28.000Z

</details>

**Comment by ggold7046** [comment]
Hi, I want to contribute to this issue myself. Could anybody guide me how to update this page ? I am a new contributor to MDN.

**Comment by sideshowbarker** [comment]
> All below mentioned http status code is missing from the left navigation pane in the references section of HTTP response status codes.
> 
> 102 Processing (WebDAV), 207 Multi-Status (WebDAV),208 Already Reported (WebDAV),226 IM Used (HTTP Delta encoding),421 Misdirected Request,423 Locked (WebDAV),424 Failed Dependency (WebDAV)

They’re not just missing from the sidebar — instead, there are not yet articles in MDN for those status codes.

> Hi, I want to contribute to this issue myself. Could anybody guide me how to update this page ? I am a new contributor to MDN.

You’d need to write articles for each of those missing status codes. You can use the markdown source for one of the existing status-code articles as a template — for example, https://github.com/mdn/content/blob/main/files/en-us/web/http/status/200/index.md — and see the instructions at https://github.com/mdn/content/blob/main/README.md#more-substantial-changes

**Comment by ggold7046** [comment]
"HTTP response status codes": some Http status codes not documented. 
The rest of the http status codes which were not previously documented;  are documented properly.

**Comment by Josh-Cena** [comment]
This needs to be fixed with #12601, because these codes don't have their pages yet
