### ISSUE TITLE
Issue with "EventTarget.addEventListener()": first time removeEventListener() mentioned needs link to description

### ISSUE THREAD

**Issue by griffintucker** [mdn/content#12617]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

#### What information was incorrect, unhelpful, or incomplete?
the first time removeEventListener() is mentioned descriptively needs a link to it's description

#### Specific section or headline?
[...]Moreover, in the first case, it is not possible to call `removeEventListener()` because no reference to the anonymous function is kept [...]

#### What did you expect to see?
[...]Moreover, in the first case, it is not possible to call <a href="https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener">`removeEventListener()`</a> because no reference to the anonymous function is kept [...]

#### Did you test this? If so, how?
did a search of the page and the first mention of it, aside from the menu on the left, does not link to the removeEventListener description

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/eventtarget/addeventlistener`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/eventtarget/addeventlistener/index.md
* Last commit: https://github.com/mdn/content/commit/f697602c97e36f3a79b0c5035830b78e4b9ea373
* Document last modified: 2022-01-30T09:32:48.000Z

</details>

**Comment by sideshowbarker** [comment]
The first mention seems to be in “Then, we call `removeEventListener()` to clean up after ourselves” in the [Safely detecting option support](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#safely_detecting_option_support) section. Is that the mention you mean should be a hypertext link?

> [...]Moreover, in the first case, it is not possible to call `removeEventListener()` because no reference to the anonymous function is kept [...]

The mention, in the [Memory issues](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#memory_issues) section, is already a hypertext link, right?

**Comment by griffintucker** [comment]
yes, my mistake, you're correct, that's what i meant

**Comment by sideshowbarker** [comment]
> yes, my mistake, you're correct, that's what i meant

👍 Thanks — I’ve opened #12620 with a fix.
