### ISSUE TITLE
Issue with "Layout using named grid lines": (Incomplete word, possible misleading information)

### ISSUE THREAD

**Issue by dmancera7** [mdn/content#12616]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Layout_using_Named_Grid_Lines

#### What information was incorrect, unhelpful, or incomplete?
Found an incomplete word that could mislead information

#### Specific section or headline?
Last paragraph of "Implicit Grid lines from named areas" section

#### What did you expect to see?
'd' letter missing on 'create' from "Given that we have this ability to position create lines from named areas",
should be "Given that we have this ability to position created lines from named areas", or not? Please consider and
correct me if i'm wrong

#### Did you test this? If so, how?
Common sense :) :p
Thats what i found so far, havent read the whole page

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_grid_layout/layout_using_named_grid_lines`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Layout_using_Named_Grid_Lines
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_grid_layout/layout_using_named_grid_lines/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12619 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
