### ISSUE TITLE
Issue with "Localizing MDN": (short summary here please)wont translate to english?

### ISSUE THREAD

**Issue by tucazguy** [mdn/content#12611]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/localize`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/localize/index.md
* Last commit: https://github.com/mdn/content/commit/237099b8121b332aecf8b802f393b3f81e608e7e
* Document last modified: 2022-01-28T03:42:47.000Z

</details>

**Comment by sideshowbarker** [comment]
Can you please re-state what you’re asking for here?

What does “wont translate to english” refer to?

**Comment by sideshowbarker** [comment]
Closing for lack of response
