### ISSUE TITLE
Issue with "white-space": make clear what “white space is collapsed” means

### ISSUE THREAD

**Issue by jenstroeger** [mdn/content#12612]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

#### What information was incorrect, unhelpful, or incomplete?

The page states repeatedly that “Sequences of white space are collapsed.” To what? I suspect “collapsed into a single space”, or might it mean “collapses to an empty string”?

#### Specific section or headline?

Several occurrences across the page.

#### What did you expect to see?

A precise statement.

#### Did you test this? If so, how?

n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/white-space`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/white-space/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12618 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
