### ISSUE TITLE
Content bug: #10176 closed with answers to an irrelevant question

### ISSUE THREAD

**Issue by deep42Thought** [mdn/content#12621]
## What page(s) did you find the problem on?

Re Issue with "Date.UTC()": Use full year #10176

Having waited months for any feedback this issue was then closed before I had a chance to respond.  Three weeks ago I had major surgery to both eyes and for a while had almost no vision.  My vision is still limited and still subject to recovery.

Please reopen the original issue

I said in the original issue "the first ever Easter",  ie the year when Jesus was placed on a cross

The answers all redirect the question as if I had asked for the  year 1900

Hence  the answers and comment are not relevant 

## Specific page section or heading?

Please see #10176

## What is the problem?

you closed an issue with irrelevant answers

## What did you expect to see?

an answer that dealt with the problem I described

## Did you test this? If so, how?

not applicable

**Comment by teoli2003** [comment]
No worry. I'm reopening it.

We are proactive in closing issues, and sometimes too much. In these cases, we can reopen them so that the discussion can continue.

But closing this one 😉
