### ISSUE TITLE
Issue with "EventTarget.addEventListener()": Default values for the "options" are not documented

### ISSUE THREAD

**Issue by FixItDik** [mdn/content#12627]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

#### What information was incorrect, unhelpful, or incomplete?
The "options" parameter consists of 4 potential values that can be set, there is however no mention of what value these take if not passed. Specifically the "passive" option defaults to "true" which is incongruous (as most Boolean options should default to false unless explicitly stated otherwise surely)

#### Specific section or headline?
Parameters >options

#### What did you expect to see?
For each option a sentance at the end of its description stating the default value (as the old "useCapture" parameter below it has "If not specified, useCapture defaults to false."

#### Did you test this? If so, how?
This is a document so testing it is not applicable

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/eventtarget/addeventlistener`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/eventtarget/addeventlistener/index.md
* Last commit: https://github.com/mdn/content/commit/f697602c97e36f3a79b0c5035830b78e4b9ea373
* Document last modified: 2022-01-30T09:32:48.000Z

</details>

**Comment by sideshowbarker** [comment]
> At [dom.spec.whatwg.org/#dictdef-addeventlisteneroptions](https://dom.spec.whatwg.org/#dictdef-addeventlisteneroptions) the spec specifies that it defaults to false.

OK I now see https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#improving_scrolling_performance_with_passive_listeners about `passive` defaulting to true in some cases in some browsers, so I’ll update #12635 to mention that.

**Comment by FixItDik** [comment]
Thanks guys, this change has improved matters however you missed the other time when the passive option defaults to true: the wheel and mousewheel events (it appears to be the same browsers that default it to true for touchstart and touchmove so I suggest the part:

“…defaults to true for the  <https://developer.mozilla.org/en-US/docs/Web/API/Element/touchstart_event> touchstart and  <https://developer.mozilla.org/en-US/docs/Web/API/Element/touchmove_event> touchmove events …”

changes to 

“…defaults to true for the wheel, mousewheel,  <https://developer.mozilla.org/en-US/docs/Web/API/Element/touchstart_event> touchstart and  <https://developer.mozilla.org/en-US/docs/Web/API/Element/touchmove_event> touchmove events …” 

(highlighted text added, links for these events would also need adding)

 

I am a little confused about the statement “…on the document-level nodes  <https://developer.mozilla.org/en-US/docs/Web/API/Window> Window,  <https://developer.mozilla.org/en-US/docs/Web/API/Document> Document, and  <https://developer.mozilla.org/en-US/docs/Web/API/Document/body> Document.body” as I discovered this when trying to zoom an OpenLayers map and saw the whole page scroll as the map also zoomed, setting the “passive:false” option for the OpenLayers object resolved the issue, I did not touch the Window, Document or Body settings.

 

Perhaps I have misunderstood but I believe this last part of the sentence is in fact incorrect and is not just limited to those three nodes.

 

Regards

Dik

**Comment by sideshowbarker** [comment]
@FixItDik Given that you’ve already done a lot of investigation and testing on this, I recommend that you ahead and open a new PR with a patch the reflects the further changes needed to the existing context. Or short of that, open a new issue.
