### ISSUE TITLE
Issue with "Fundamental text and font styling": (short summary here please)

### ISSUE THREAD

**Issue by jowkenji** [mdn/content#12658]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals

#### What information was incorrect, unhelpful, or incomplete?
The "Test Your Skills!" section appears in every section before the end of the module. I struggled to solve the style code denying to cheat looking at the further sections (specifically "Styling links"). When I finished the test, I almost skipped the following sections, then I realized this error. 

#### Specific section or headline?
Learn web development>Learn to style HTML using CSS>Styling text

#### What did you expect to see?
The "Test your skills!" by the end of "Web fonts" only

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/styling_text/fundamentals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/styling_text/fundamentals/index.md
* Last commit: https://github.com/mdn/content/commit/a590d73456035088e5f1cac116974488ebd867ef
* Document last modified: 2022-01-31T14:45:50.000Z

</details>

**Comment by wbamberg** [comment]
Yeah, that does seem unfair! I files https://github.com/mdn/content/pull/12661 for it.
