### ISSUE TITLE
Issue with "grid-template-columns": no definition of <name-repeat>

### ISSUE THREAD

**Issue by Snuff-Daddy** [mdn/content#12656]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns

#### What information was incorrect, unhelpful, or incomplete?
no definition of &lt;name-repeat&gt;

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/grid-template-columns`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/grid-template-columns/index.md
* Last commit: https://github.com/mdn/content/commit/7787d90d6e46167bc6e4c5bdd7fe413faf1d9309
* Document last modified: 2021-09-13T12:03:05.000Z

</details>

**Comment by Snuff-Daddy** [comment]
Why closed with no resolution or explanation?  Problem is legit.

**Comment by wbamberg** [comment]
Oh, sorry! I totally missed the actual report there. We get a lot of empty issues filed, and sometimes I'm a bit quick to close them :).

**Comment by Snuff-Daddy** [comment]
Np.  To clarify, the formal syntax refers to &lt;name-repeat&gt; but that is not defined.  There is no explanation in the description of subgrid.  There are no examples.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/data/pull/551 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

**Comment by Snuff-Daddy** [comment]
Regarding the definition:

<name-repeat> = repeat( [ <integer [1,∞]> ] | auto-fill ], <line-names>+ )

There are two left brackets but three right brackets.

**Comment by sideshowbarker** [comment]
> There are two left brackets but three right brackets.

oops — thanks much for catching that; I’ve opened https://github.com/mdn/data/pull/570 with a fix
