### ISSUE TITLE
Issue with "SyntaxError: Unexpected token": This is different from the actual error message.

### ISSUE THREAD

**Issue by k08045kk** [mdn/content#12665]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_token

#### What information was incorrect, unhelpful, or incomplete?
The execution result of the sample code is different from the actual result.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_token#expression_expected

#### What did you expect to see?
```js
for (let i = 0; i < 5,; ++i) {
  console.log(i);
}
// SyntaxError: expected expression, got ')'
```

I ran the above code. The browser produced the following output.

```
Firefox 96.0.3 / Firefox Nightly 98.0a1
Uncaught SyntaxError: expected expression, got ';'

Chrome 97.0.4692.71
Uncaught SyntaxError: Unexpected token ';'
```

So, I think the following comment is appropriate.

```js
// SyntaxError: expected expression, got ';'
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/unexpected_token`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_token
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/unexpected_token/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #126667 with a fix.
