### ISSUE TITLE
[Angular] Option "--prod" is deprecated

### ISSUE THREAD

**Issue by horusofoz** [mdn/content#12676]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_building

#### What information was incorrect, unhelpful, or incomplete?
Do not need to append the `--prod` to `ng  build` command. Results in output 
`Option "--prod" is deprecated: No need to use this option as this builder defaults to configuration "production".` 

#### Specific section or headline?
NA

#### What did you expect to see?
NA

#### Did you test this? If so, how?
NA

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/angular_building`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_building
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by horusofoz** [comment]
Hi @himanshugarg. It works still just this output was received.

`Option "--prod" is deprecated: No need to use this option as this builder defaults to configuration "production".`

Testing without --prod I didn't get the warning but all executed as expected.

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/19812
