### ISSUE TITLE
Content bug: No note that WEBGL_debug_renderer_info is deprecated on Firefox

### ISSUE THREAD

**Issue by danielhjacobs** [mdn/content#12689]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_debug_renderer_info

## Specific page section or heading?

Immediately below the page header or the browser compatibility table

## What is the problem?

There is no notice that this is deprecated in Firefox, despite the fact when using it in Firefox, you get the message "WEBGL_debug_renderer_info is deprecated in Firefox and will be removed".

## What did you expect to see?

Either a deprecated notecard, or if there is not one because this is only deprecated in Firefox, a note in the browser compatibility section for Firefox explaining that this is deprecated in Firefox.

## Did you test this? If so, how?

Viewing the console of Firefox when using an extension which prints information from WEBGL_debug_renderer_info

**Comment by hamishwillee** [comment]
Thanks for reporting. FYI the deprecation note is here: https://searchfox.org/mozilla-central/source/dom/canvas/WebGLContextExtensions.cpp#207 , introduced in FF92 here: https://bugzilla.mozilla.org/show_bug.cgi?id=1722782.

I'm trying to find out the reason/scope for the change in https://bugzilla.mozilla.org/show_bug.cgi?id=1722782#c9 . Once I know, I'll update the browser compatibility data.

**Comment by danielhjacobs** [comment]
I found 2 prior issues that relate to that last issue:

https://bugzilla.mozilla.org/show_bug.cgi?id=1715690: Original issue related to RENDERER, saying it exposes more info than necessary

https://bugzilla.mozilla.org/show_bug.cgi?id=1722113: Issue that disabled WEBGL_debug_renderer_info in nightly, which caused an issue

https://bugzilla.mozilla.org/show_bug.cgi?id=1722782: Issue that led to the current message, re-enabling WEBGL_debug_renderer_info but describing it as deprecated and stating it will be removed.

**Comment by hamishwillee** [comment]
@danielhjacobs FYI So there [was a response](https://bugzilla.mozilla.org/show_bug.cgi?id=1722782#c10) which indicates that they don't really know if it will be removed "yet". I've added a note to BCD here https://github.com/mdn/browser-compat-data/pull/14964 which should close this.
