### ISSUE TITLE
Issue with "image-orientation": (Sample image does not demonstrate property usage)

### ISSUE THREAD

**Issue by JimBobSquarePants** [mdn/content#12681]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation

#### What information was incorrect, unhelpful, or incomplete?
The image provided in the example does not contain EXIF metadata required to demonstrate the CSS property.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/web/css/image-orientation#examples

#### What did you expect to see?
I expected to see a change in orientation when choosing between `image-orientation: from-image` and `image-orientation: none`

#### Did you test this? If so, how?
I toggled the select and confirmed that the source image is an SVG.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/image-orientation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/image-orientation/index.md
* Last commit: https://github.com/mdn/content/commit/0469140da76b9b593251a191c63a2ee92abc1774
* Document last modified: 2021-09-15T02:25:12.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing this! Should be fixed by https://github.com/mdn/content/pull/12710.
