### ISSUE TITLE
Issue with "max-block-size": examples shows wrong "auto" value but probably "none" intended (max-inline-size has same problem)

### ISSUE THREAD

**Issue by Snuff-Daddy** [mdn/content#12703]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/max-block-size

#### What information was incorrect, unhelpful, or incomplete?
one of the examples shows the "auto" value however this is not a possible value, probably "none" was intended
max-inline-size has the same problem

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/max-block-size`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/max-block-size
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/max-block-size/index.md
* Last commit: https://github.com/mdn/content/commit/2841b917b32e99a7064fb5f7f626bdaed683f971
* Document last modified: 2022-02-02T16:14:54.000Z

</details>

**Comment by Anurella** [comment]
@sideshowbarker I can work on this

**Comment by sideshowbarker** [comment]
> @sideshowbarker I can work on this

👍 Super — assigned to you now
