### ISSUE TITLE
Issue with "Date.prototype.getTime()": the reference to "UNIX epoch" should be "ECMAScript epoch".

### ISSUE THREAD

**Issue by RobG000** [mdn/content#12715]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime

In the statement:

> The getTime() method returns the number of milliseconds* since the Unix Epoch.

the phrase "since the UNIX epoch" infers that ECMAScript time values are dependent on the UNIX epoch, which they aren't. The sentence should read:

> The getTime() method returns the number of milliseconds since the ECMAScript epoch (midnight at the begining of 1 January, 1970 UTC).

The ECMAScript epoch is concurrent with the UNIX epoch, but is not dependent on it (or any other epoch defined for various systems and languages for the same date and time).

The additional sentences:

```
* JavaScript uses milliseconds as the unit of measurement, whereas Unix Time is in seconds.

getTime() always uses UTC for time representation. For example, a client browser in one timezone, getTime() will be the same as a client browser in any other timezone.

```

Are unnecessary and confusing and should be removed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/gettime`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/gettime/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12718 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
