### ISSUE TITLE
Issue with "MediaQueryList.addListener()": …

### ISSUE THREAD

**Issue by chrisaspringer** [mdn/content#1271]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener

#### What information was incorrect, unhelpful, or incomplete?
mediaQueryList.addListener is deprecated.

#### Specific section or headline?
Bottom of Example code block.

#### What did you expect to see?
mediaQueryList.addListener('change', screenTest);

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediaquerylist/addlistener`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/mediaquerylist/addlistener/index.html
* Report started: 2021-01-13T19:18:30.935Z

</details>

**Comment by chrisdavidmills** [comment]
Hi @chrisaspringer !

I've made some small changes to the text to make it clearer that this is deprecated, but I'm not making the suggested code change — `addListener()` only takes a single argument; the `change` event is assumed.
