### ISSUE TITLE
XMLHTTP REQUEST FAILIssue with "Getting started with the Web": (short summary here please)

### ISSUE THREAD

**Issue by 9641048386** [mdn/content#12724]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

Unfortunately, you didn't provide any information about the issue you are reporting. We cannot act on it.

I'm closing it. If you return and provide more information, you are welcome to re-open it (or fill a separate issue).

Thanks a lot for your interest!

**Comment by 9641048386** [comment]
XMLHTTP REQUEST FAIL
