### ISSUE TITLE
Unnecessary RTL-attribute in examples

### ISSUE THREAD

**Issue by Pashted** [mdn/content#1272]
Hi. On this page https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/this#%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B9_%D0%B2%D1%8B%D0%B7%D0%BE%D0%B2 is see unnecessary RTL-attribute for the first block of example code, which unacceptable for Russian and breaks the entire text. This issue does not exist in the English version.

![image](https://user-images.githubusercontent.com/16826622/104506308-443b8800-55f6-11eb-87c7-22564fa6e146.png)

**Comment by chrisdavidmills** [comment]
Generally we're not accepting updates to localised pages at the moment (see https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation)

However this one does look annoying. Any change of fixing this @fiji-flo ?

**Comment by SphinxKnight** [comment]
@Pashted, Russian docs are opened for contributions now. It has been fixed w/. https://github.com/mdn/translated-content/commit/100316f2f54500ba714391b4f6940e96bd246b77#diff-d118fb925eb2262114e557d2c17f85bcca80f668a98f8f832dd13440215fbd5d

If you see anything which needs help on the Russian docs, feel free to file an issue on https://github.com/mdn/translated-content
