### ISSUE TITLE
Issue with "Information contained in a WebIDL file": hyperlinked text points to 404

### ISSUE THREAD

**Issue by yamero1** [mdn/content#12728]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Write_an_API_reference/Information_contained_in_a_WebIDL_file

#### What information was incorrect, unhelpful, or incomplete?
In the section [`Different dialects of WebIDL`](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Write_an_API_reference/Information_contained_in_a_WebIDL_file#different_dialects_of_webidl) there are three bullet points. The first one is:

`For Gecko, MDN has the [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/WebIDL_bindings) of its dialectal WebIDL.
`

The webpage that the word `documentation` has been hyperlinked with doesn't exist.

![image](https://user-images.githubusercontent.com/27294025/152542533-d37fd95b-d14d-44ff-909f-fad93a85383f.png)

#### Specific section or headline?
Different dialects of WebIDL

#### What did you expect to see?
A working link? (idk what to write here)

#### Did you test this? If so, how?
Yes. By visiting the linked page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/howto/write_an_api_reference/information_contained_in_a_webidl_file`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Write_an_API_reference/Information_contained_in_a_WebIDL_file
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
* Last commit: https://github.com/mdn/content/commit/601a273d856ee11aa32dd9ac42d1e84f441c8b58
* Document last modified: 2022-02-03T11:27:16.000Z

</details>

**Comment by teoli2003** [comment]
Thanks! Good catch. I created a PR to the place it moved.
