### ISSUE TITLE
Issue with "SyntaxError": dead link for 'SpiderMonkey'

### ISSUE THREAD

**Issue by scGetStuff** [mdn/content#12743]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError

#### What information was incorrect, unhelpful, or incomplete?
Dead link in several pages in the JavaScript reference part of the site.

#### Specific section or headline?
Instance properties
    SyntaxError.prototype.message

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/syntaxerror`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/syntaxerror/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by teoli2003** [comment]
I clicked the `SyntaxError.prototype.message` link and it lead me to `Error.prototype.message`. It doesn't look like a dead link.

Can you be more explicit? (I must be missing something)

**Comment by sideshowbarker** [comment]
@teoli2003 I see now this about broken links to the now-gone `/en-US/docs/Mozilla/Projects/SpiderMonkey` docs.

Opening a PR with a patch for it now.

**Comment by teoli2003** [comment]
Oh yes, you are right. My bad!

**Comment by sideshowbarker** [comment]
@scGetStuff Thanks for raising this — I’ve opened #12748 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
