### ISSUE TITLE
Issue with "Control flow and error handling": Confusing statement

### ISSUE THREAD

**Issue by techemmy** [mdn/content#12751]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling

#### What information was incorrect, unhelpful, or incomplete?
Under 'Best Practice', a part of the section says this with some code snippets "It's unwise to use simple assignments in a conditional expression, because the assignment can be confused with equality when glancing over the code."
Whereas, assignment is never confused as equality in this case as I've tested it.

#### Specific section or headline?
Conditional Statements

#### What did you expect to see?
I don't know what they are trying to explain there.

#### Did you test this? If so, how?
Yes, I used my browser's Javascript Console. Using a single or double parenthesis still results in an assignment.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/control_flow_and_error_handling`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/control_flow_and_error_handling/index.md
* Last commit: https://github.com/mdn/content/commit/56cef13241e8d9e9ba980840e28202152e099f36
* Document last modified: 2022-02-02T09:01:58.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12774 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
