### ISSUE TITLE
Issue with SVG Tutorial "Getting started": wrong example regarding <object> element

### ISSUE THREAD

**Issue by MrSpiffyClean** [mdn/content#12756]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Getting_Started

#### What information was incorrect, unhelpful, or incomplete?
The example about referencing an SVG file with the <object> element _seems_ wrong, as the closing tag is missing.

#### Specific section or headline?
Basic properties of SVG files

#### What did you expect to see?
`<object data="image.svg" type="image/svg+xml"></object>`

#### Did you test this? If so, how?
I was tinkering with adding SVG images to a page I run. Following the example to the letter breaks the page rendering after the object element. Checking the reference regarding the `<object>` element (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object) shows that both start and end tags are required. Rewriting to include the end tag seems to have fixed the issue.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/tutorial/getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Getting_Started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/tutorial/getting_started/index.md
* Last commit: https://github.com/mdn/content/commit/614cd623fac41cbc68c54ef33b82dd4d5ebb04f7
* Document last modified: 2022-02-04T07:16:02.000Z

</details>

**Comment by sideshowbarker** [comment]
Nice catch — thanks for raising this. I’ve opened #12760 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
