### ISSUE TITLE
Issue with "Element.prepend()": (just a typo)

### ISSUE THREAD

**Issue by Yurghan** [mdn/content#12771]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/prepend

#### What information was incorrect, unhelpful, or incomplete?
The headline: 'Appending an element and text' should be in my understanding - 'Prepending an element and text'

#### Specific section or headline?
<a href="#appending_an_element_and_text" title="Permalink to Appending an element and text">Appending an element and text</a>

#### What did you expect to see?
<a href="#prepending_an_element_and_text" title="Permalink to Prepending an element and text">Prepending an element and text</a>

#### Did you test this? If so, how?
I didn't

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/prepend`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/prepend
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/prepend/index.md
* Last commit: https://github.com/mdn/content/commit/92942b07754b549f595c32e72440a0f0973893a9
* Document last modified: 2021-09-15T12:39:31.000Z

</details>

**Comment by teoli2003** [comment]
Thanks! I've opened a PR; this issue will be closed when it is merged into the tree.
