### ISSUE TITLE
Issue with "WEBGL_color_buffer_float": …

### ISSUE THREAD

**Issue by CVex2150J** [mdn/content#1278]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_color_buffer_float

#### What information was incorrect, unhelpful, or incomplete?
Typo in Exemples. "RBGA32F_EXT" instead of **RGBA32F_EXT**

#### Specific section or headline?
Exemples

#### What did you expect to see?
``gl.renderbufferStorage(gl.RENDERBUFFER, ext.RGBA32F_EXT, 256, 256);``

#### Did you test this? If so, how?
Yes, in Firefox console. The variable RBGA32F_EXT is not defined but RGBA32F_EXT is

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl_color_buffer_float`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_color_buffer_float
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/webgl_color_buffer_float/index.html
* Report started: 2021-01-14T01:15:11.012Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened #1291 with a fix.
