### ISSUE TITLE
Issue with "WebAssembly control flow": Add this reference to main tutorial

### ISSUE THREAD

**Issue by dy** [mdn/content#12804]
That's very valuable piece https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Control_flow
And it's very hard to reach by navigating in https://developer.mozilla.org/en-US/docs/WebAssembly 
I found that accidentally via google. It's worth adding to tutorial as a useful section.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12841 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
