### ISSUE TITLE
Issue with "fx": …

### ISSUE THREAD

**Issue by Mr-LJQ** [mdn/content#1281]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fx

#### What information was incorrect, unhelpful, or incomplete?

Example:line-14
<circle cx="35" cy="35" r="2" fill="white" stroke="white"/>
change:
<circle cx="45" cy="45" r="2" fill="white" stroke="white"/>
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/attribute/fx`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fx
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/svg/attribute/fx/index.html
* Report started: 2021-01-14T01:55:41.572Z

</details>

**Comment by Mr-LJQ** [comment]
<circle cx="35" cy="35" r="2" fill="white" stroke="white"/>
change:
<circle cx="45" cy="45" r="2" fill="white" stroke="white"/>

**Comment by Mr-LJQ** [comment]
The coordinate point of the fourteenth line of Example is wrong, it should be 45, 45 instead of 35, 35

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened #1290 with a fix.
