### ISSUE TITLE
Content bug: wrong function name in explanation - Expressions_and_Operators (Evaluation and nesting)

### ISSUE THREAD

**Issue by ronh991** [mdn/content#12810]
## What page(s) did you find the problem on?
[Evaluation and nesting](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators)

## Specific page section or heading?
Evaluation and nesting in Evaluation example 2

## What is the problem?
Wrong function name reference in explanation. f() should be g()

## What did you expect to see?
The assignment expression y = [ f(), x = g() ] starts to evaluate.
The y on this assignment’s left-hand evaluates into a reference to the variable named y.
The inner array literal [ f(), x = g() ] starts to evaluate.
The function call f() prints "F!" to the console and
then evaluates to the number 2. 2. The assignment expression x = g() starts to evaluate.
The x on this assignment’s left-hand side evaluates into a reference to the variable named x.
The function call g() prints "G!" to the console and then evaluates to the number 3.

That 3 result from g() is assigned to x.  <---- error in this line

The assignment expression x = g() has now finished evaluating;
its result is the new value of x, which is 3. That 3 result becomes the next element in the inner array literal (after the 2 from the f()).

That 3 result from f() is assigned to x.  
should be
That 3 result from g() is assigned to x.

**Comment by hamishwillee** [comment]
Thanks very much @ronh991 - Fixed by @himanshugarg in#12815
