### ISSUE TITLE
Issue with "TypedArray.of()": signed/unsigned int used incorrectly

### ISSUE THREAD

**Issue by brianbienvenu** [mdn/content#1283]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/of

#### What information was incorrect, unhelpful, or incomplete?
The demo example code shown says `let uint16 = new Int16Array;`. This means that the variable should be unsigned ints, but the array is clearly a signed int16.

#### Specific section or headline?
Demo code

#### What did you expect to see?
Signed/unsigned ints used correctly

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/typedarray/of`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/of
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/typedarray/of/index.html
* Report started: 2021-01-14T03:07:33.862Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/interactive-examples/pull/1754 with a fix. Please take a look and comment there if needed.
