### ISSUE TITLE
Issue with "Lexical grammar": …

### ISSUE THREAD

**Issue by zaqvil** [mdn/content#1285]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar

#### What information was incorrect, unhelpful, or incomplete?

{ 1 2 } 3

// is transformed by ASI into

{ 1 2 ;} 3;

It's error.In sourse is
{ 1
2 } 3
to
{ 1
;2 ;} 3;

#### Specific section or headline?
Automatic semicolon insertion first rule

#### What did you expect to see?
http://www.ecma-international.org/ecma-262/6.0/#sec-automatic-semicolon-insertion 11.9.2

#### Did you test this? If so, how?
Yes, { 1 2 } 3 could is error in console

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/lexical_grammar`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/lexical_grammar/index.html
* Report started: 2021-01-14T03:17:34.745Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/1289 with a fix.
