### ISSUE TITLE
Issue with "Intersection Observer API": missing closing parentheses

### ISSUE THREAD

**Issue by gilad905** [mdn/content#12858]
"Clipping and the intersection rectangle", item 3:
> (such as the document contained in an <iframe>,

should be

> (such as the document contained in an <iframe>),

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/intersection_observer_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/intersection_observer_api/index.md
* Last commit: https://github.com/mdn/content/commit/b7aafea1ab7cfee11a7e854a4b5c83a6e6d329d4
* Document last modified: 2022-02-02T09:11:35.000Z

</details>

**Comment by teoli2003** [comment]
Thanks for the report! I've opened a PR to get this fixed.
