### ISSUE TITLE
Issue with "Response.body": body is possibly `null`

### ISSUE THREAD

**Issue by jespertheend** [mdn/content#12862]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/body

#### What information was incorrect, unhelpful, or incomplete?
The page doesn't mention that body might be `null`.

#### Specific section or headline?

Under "[Value](https://developer.mozilla.org/en-US/docs/Web/API/Response/body#value)"

#### What did you expect to see?
"A [`ReadableStream`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) or `null`."

#### Did you test this? If so, how?

I'm not sure under what conditions a `fetch()` results in a `Response` with its body set to `null`, but both [the spec](https://fetch.spec.whatwg.org/#ref-for-dom-body-body) and [`lib.dom.ts`](https://github.com/microsoft/TypeScript/blob/c06849ad16a1ab9bb1e457755f3ef22cf231cac5/lib/lib.dom.d.ts#L2443) mention `body` being possibly null.

The only situation I could find where this is the case is:
```js
const resp = new Response(null);
resp.body; // null
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/response/body`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/body
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/response/body/index.md
* Last commit: https://github.com/mdn/content/commit/4072b1033d73e9d7ee8ff6290f24057fc97e8a58
* Document last modified: 2021-11-09T06:44:18.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #12876 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

> I'm not sure under what conditions a `fetch()` results in a `Response` with its body set to `null`, but both [the spec](https://fetch.spec.whatwg.org/#ref-for-dom-body-body) and [`lib.dom.ts`](https://github.com/microsoft/TypeScript/blob/c06849ad16a1ab9bb1e457755f3ef22cf231cac5/lib/lib.dom.d.ts#L2443) mention `body` being possibly null.

Yeah, for the record here: At https://fetch.spec.whatwg.org/#ref-for-dom-body-body, the WebIDL for `Response`»`body` is this:

```
readonly attribute ReadableStream? body;
```

Per https://webidl.spec.whatwg.org/#idl-nullable-type, the "`?`" annotation there means that the `ReadableStream` type is nullable.

So I’m also no sure under what conditions it might actually end up being `null`, but per-spec at least, it’s allowed to be `null`.

**Comment by sideshowbarker** [comment]
Actually, after think about this, it’s quite common that a `Response`»`body` can be null — for example, in the case of      HTTP 200  “No Content” responses (which, for example, some servers send in response to CORS preflight `OPTIONS` requests).

And the `Response` object isn’t just for code-constructed responses — the responses that the Fetch API exposes are `Response` objects.

**Comment by jespertheend** [comment]
> in the case of HTTP 204

I tried doing a fetch for https://httpstat.us/204 in Firefox and Chrome yesterday and its response body did not end up as null. Neither did a fetch for a local WebSocket endpoint that I had setup.

[The spec](https://fetch.spec.whatwg.org/#statuses) mentions 101, 204, 205, and 304 having a `null body` status. But I’m not sure this actually means the body should be `null`. But perhaps it is, and these browsers are not following the spec here, I’m not sure.

**Comment by sideshowbarker** [comment]
> [The spec](https://fetch.spec.whatwg.org/#statuses) mentions 101, 204, 205, and 304 having a `null body` status. But I’m not sure this actually means the body should be `null`. But perhaps it is, and these browsers are not following the spec here, I’m not sure.

Yeah, per-spec, `response.body` should be null, but it seems to be that browsers (all of them) aren’t following the spec on this (per discussion in https://matrixlogs.bakkot.com/WHATWG/2022-02-10#L0).

So I guess maybe I should do a follow-up PR with some additional language to indicate that browsers don’t actually do what the spec says they should be doing on this.
