### ISSUE TITLE
Issue with "Responsive images": em was given as an example of absolute length unit

### ISSUE THREAD

**Issue by matheus4lves** [mdn/content#12875]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

#### What information was incorrect, unhelpful, or incomplete?
The relative length unit **em**  was given as an example of an absolute length along with the px unit.

#### Specific section or headline?
[Resolution switching: Different sizes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_different_sizes)
The wrong information is in the first note of the section

#### What did you expect to see?
maybe mm, cm or any other absolute length unit

#### Did you test this? If so, how?
No test required. I took a look at Mozilla's own documentation: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#lengths

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.md
* Last commit: https://github.com/mdn/content/commit/7e329de8a1ec173df42c8eab9448f93c3e6c7cfa
* Document last modified: 2022-02-02T01:34:30.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12877 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
