### ISSUE TITLE
tc39.es specification links are 404

### ISSUE THREAD

**Issue by GoldenretriverYT** [mdn/content#12889]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay

#### What information was incorrect, unhelpful, or incomplete?
The specification link on that site is dead.

#### Specific section or headline?
Specifications

#### What did you expect to see?
A link that works.

#### Did you test this? If so, how?
By clicking it

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/getday`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/getday/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by Elchi3** [comment]
Seems like https://tc39.es is down?

https://downforeveryoneorjustme.com/tc39.es?proto=https

**Comment by Elchi3** [comment]
People who are responsible for this host have been notified, so it should be resolved soon.

**Comment by Elchi3** [comment]
It's working again.
