### ISSUE TITLE
Issue with "<foreignObject>": (css property backdrop-filter doesn't support yet)

### ISSUE THREAD

**Issue by simpleneeraj** [mdn/content#12883]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

#### why i need to open an issue 

Hii, my name is neeraj and i am building a tool to create instagram post, so i need i tool or library to convert 
Just like that [domtoimage](https://github.com/tsayen/dom-to-image) 
And also used [html2canvas](https://github.com/niklasvh/html2canvas) 

But i don't get my expected result so i found that,
In `foreign-object` css property `backdrop-filter ` doesn't support.
Can anyone solve this issue with foreignObject......
Help me 

### !important 

If you have another method or library to convert html to image then comment me.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/element/foreignobject`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/foreignobject/index.md
* Last commit: https://github.com/mdn/content/commit/f107840858523dd1a50a07de2b6112928b5c31a2
* Document last modified: 2022-02-06T06:18:20.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing, problems in the MDN documentation.

It looks like you are looking for help with your code. Unfortunately, we don't have enough availability to help you.

May I suggest asking your question on a specialized website, like StackOverflow?

I'm closing this issue. If I've misunderstood you and you were actually reporting a problem in the documentation, feel free to reopen it, while providing more information so we can understand the problem.

Thanks for your interest.
