### ISSUE TITLE
Content suggestion: New HTML feature `blocking=render` on `<script>`,  `<link>`, `<style>`

### ISSUE THREAD

**Issue by zcorpan** [mdn/content#12900]
## What is the new suggestion?

Document the `blocking` attribute on `script`, `link` and `style` HTML elements and examples for how to use it.

## Why is it important or useful?

See the explainer here: https://github.com/whatwg/html/issues/7131

## Other supporting information

https://html.spec.whatwg.org/multipage/semantics.html#attr-link-blocking
https://html.spec.whatwg.org/multipage/semantics.html#attr-style-blocking
https://html.spec.whatwg.org/multipage/scripting.html#attr-script-blocking

This feature was introduced in https://github.com/whatwg/html/pull/7474

cc @xiaochengh @domenic

MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

**Comment by MxYamato** [comment]
This new feature looks great, I sometimes have seen Wikipedia load without the style elements and was thinking about this issue :)
