### ISSUE TITLE
Issue with "Array.prototype.forEach()": Return keyword in forEach behaviour

### ISSUE THREAD

**Issue by joekingTheThird3** [mdn/content#12908]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

#### What information was incorrect, unhelpful, or incomplete?
The behaviour with the return keyword

#### Specific section or headline?
All

#### What did you expect to see?
It is not clear what return in a forEach iteration is supposed to do.

#### Did you test this? If so, how?
[1,2,3,4,5].forEach(n => {
if(n==3) return;
  alert(n)

})
This code gives alert of 1,2,4,5 - it misses 3.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/foreach`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/foreach/index.md
* Last commit: https://github.com/mdn/content/commit/c49942250096b8b0ff03cd12f4f06a0168f3906a
* Document last modified: 2022-02-07T22:25:21.000Z

</details>

**Comment by joekingTheThird3** [comment]
I am looking at the forEach page in this section, it says 'Note: There is no way to stop or break a forEach() loop other than by throwing an exception. If you need such behavior, the forEach() method is the wrong tool. '. If I understand this correctly then the return statement in the callback function in the forEach is actually 'breaking' the current loop.

**Comment by wbamberg** [comment]
I don't think there's an error in the page here, so I'm closing this issue.
