### ISSUE TITLE
Issue with "animation-timeline": Specifications and other data 'Not found'

### ISSUE THREAD

**Issue by 2cb-log** [mdn/content#12903]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline

#### What information was incorrect, unhelpful, or incomplete?

1. "Formal definition" section contains only a 'Value not found in DB!' (in red)
2. "Formal syntax" returns 'No syntax available: No value found in the database.' (in yellow background)
3. "Specifications" includes a 'No specification data found for css.properties.animation-timeline' error along with follow-up corrective action content.
4. "Browser compatibility" includes a 'No comptibility data found for css.properties.animation-timeline' error along with a follow-up action.
5. "Examples" section includes a "Result" window where the #square DIV does not actually rotate

#### Specific section or headline?

As noted in the preceding "incomplete" question, these sections are affected:

1. "Formal definition"
2. "Formal syntax"
3. "Specifications"
4. "Browser compatibility"
5. "Examples"

#### What did you expect to see?

Usual MDN Docs tables containing the relevant properties and values and explanations.  Also, a rotating DIV in the "Results" section.

#### Did you test this? If so, how?

No test, just visual review 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/animation-timeline`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/animation-timeline/index.md
* Last commit: https://github.com/mdn/content/commit/f937963ec983c1f3b89024e92807779139b6a54c
* Document last modified: 2022-02-03T07:56:56.000Z

</details>

**Comment by teoli2003** [comment]
Pinging @rumyra here.

`animation-timeline` is brand new and part of the Scroll Timeline specification.

There are two problems here:
- no entry in mdn/browser-compat-data (this causes _Specifications_  and  _Browser compatibility_ to be in error.
- no entry in mdn/data that causes the others.

I know that both Gecko and Chromium want to implement this and I think it may be the case very soon for Gecko, but Rumyra will now better than me, as well as the status of the PR in the two other repositories.

**Comment by hamishwillee** [comment]
FYI @teoli2003 

For `@scroll-timeline` I think it is just waiting on BCD update to MDN:
- Added to BCD in https://github.com/mdn/browser-compat-data/pull/14662
- MDN data has scroll timeline here: https://github.com/mdn/data/blob/main/css/at-rules.json#L421

For @animation-timeline: 
- https://github.com/mdn/browser-compat-data/pull/14663 - looks like BCD is waiting on @Rumyra to repost.
- Data PR here https://github.com/mdn/data/pull/548 - if there is an issue, pushing back to @Rumyra :-)

**Comment by teoli2003** [comment]
Thanks, @hamish.  mdn/data is published once in a while (usually once a month or once every two months. So this will go away. And `animation-timeline` seems to be on @Rumyra (or @dipikabh ) radar.

I propose to keep this open until mdn/data is published and `animation-timeline` added to bcd. 

@2cb-log Thanks for the report!

**Comment by 2cb-log** [comment]
BTW, congratulations and thanks to the extended team for landing this feature.  Between `timeline` and `@layout` becoming available, it's easy to get excited about CSS all over again 🙂

**Comment by Rumyra** [comment]
Thanks all - I'll get to releasing data over the next week, which should fix that. And yes @teoli2003 I need to redo the bcd pr - I'll update here asap.

**Comment by wbamberg** [comment]
This seems to be all working now. All the data is in the page, and the example works on Firefox if you enable the pref.
