### ISSUE TITLE
Issue with "Privacy, permissions, and information security": allow link to nowhere

### ISSUE THREAD

**Issue by plfstr** [mdn/content#12917]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Privacy

#### What information was incorrect, unhelpful, or incomplete?

The word ‘allow,’ links to the Global Attributes page (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-allow) but ‘allow’ is not defined there.

#### Specific section or headline?
[Privacy and Security Controls table](https://developer.mozilla.org/en-US/docs/Web/Privacy#privacy_and_security_controls), the text: “<iframe>'s allow attribute”

#### What did you expect to see?
A link to the iframe page, allow attribute (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-allow)
OR
A link to the Global Attributes page with ‘allow’ defined there.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/privacy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Privacy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/privacy/index.md
* Last commit: https://github.com/mdn/content/commit/516c74d03bd44861eca7da5a96d287aef846b89d
* Document last modified: 2022-01-27T16:52:19.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #12928 with fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
