### ISSUE TITLE
Issue with "Firefox 97 for developers": Document that "@scroll-timeline" is not enabled by default

### ISSUE THREAD

**Issue by kkolinko** [mdn/content#12942]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/97

#### What information was incorrect, unhelpful, or incomplete?

The [@scroll-timeline](https://developer.mozilla.org/en-US/docs/Web/CSS/@scroll-timeline) at-rule and [animation-timeline](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline) property are now supported.

#### Specific section or headline?

CSS

#### What did you expect to see?

I think that the text should mention that support for "@scroll-timeline" is not enabled by default in Firefox 97.

I followed the links to [@scroll-timeline](https://developer.mozilla.org/en-US/docs/Web/CSS/@scroll-timeline) at-rule and [animation-timeline](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline) MDN pages, and found that the examples on those pages do not work. (Moreover, there is no documentation on those pages in what versions of Firefox this feature is available - see issue #12903).

[Comment 2 in bug 1676782](https://bugzilla.mozilla.org/show_bug.cgi?id=1676782#c2) mentions that configuration property to enable this feature is
`layout.css.scroll-linked-animations.enabled`

#### Did you test this? If so, how?

I am using Firefox 97.0 (Release)

1. On the following pages:
https://developer.mozilla.org/en-US/docs/Web/CSS/@scroll-timeline#simple_example
https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline#simple_example

Scroll down for "Examples / Simple Example" and "Result".
Actual behaviour: I see that a pink square rotates once just after the page has been loaded. It does not rotate when I scroll the scrollbar of its container.
Expected: I expect that the pink square rotates when the scrollbar of its container is being scrolled.

2. If I go to the about:config page and change the `layout.css.scroll-linked-animations.enabled` property to the value of 'true', and reload the page, I see the Expected behaviour.

So this feature is indeed implemented and is behind that configuration property.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/firefox/releases/97`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/97
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/97/index.md
* Last commit: https://github.com/mdn/content/commit/be7254c4ff5bdf543e8dfb1855905c2e3736a22b
* Document last modified: 2022-02-07T19:47:19.000Z

</details>

**Comment by hamishwillee** [comment]
You're quite right @kkolinko . I will add the preference to browser compatibility and remove from the release notes. This will fix both problems.

FYI @Rumyra

**Comment by hamishwillee** [comment]
Closing, as I believe this has now been updated.
