### ISSUE TITLE
Issue with "Firefox 97 for developers": Broken link (@layer)

### ISSUE THREAD

**Issue by kkolinko** [mdn/content#12943]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/97

#### What information was incorrect, unhelpful, or incomplete?

CSS cascade layers are now available by default. The @layer rule ...

#### Specific section or headline?

CSS

#### What did you expect to see?

The link on text "@layer" is broken.

1. Looking at the "@import" link that follows and works, I see that the change that fixes this issue may be

```
- [`@layer`](en-US/docs/Web/CSS/@layer)
+ [`@layer`](/en-US/docs/Web/CSS/@layer)
```
2. but, looking at a "{{cssxref('@scroll-timeline')}}" link in the preceding text (two bullets above this fragment), I think it would be better to redefine both @layer and @import links using the `cssxref()` macro. But I do not know how to test such a change.

#### Did you test this? If so, how?

Clicked on "@layer".
Actual URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/en-US/docs/Web/CSS/@layer
Expected URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@layer

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/firefox/releases/97`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/97
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/97/index.md
* Last commit: https://github.com/mdn/content/commit/be7254c4ff5bdf543e8dfb1855905c2e3736a22b
* Document last modified: 2022-02-07T19:47:19.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. Fixed by #12968. Note that doing an explicit link or using `cssxref()` are both valid and fine in the docs.
