### ISSUE TITLE
Issue with "Request()": How is overiding of headers handled?

### ISSUE THREAD

**Issue by mangelozzi** [mdn/content#12959]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Request/Request

#### What information was incorrect, unhelpful, or incomplete?
If you construct a new request with an existing request, and add an init object and they both specify the same header, which one will "win"?

For Example:
```
    const init = {
        headers: { 'x-foo': 'bar'},
    };
    const newRequest = new Request(oldRequest, init); / / oldRequest contains the header 'x-foo' already
```

#### Specific section or headline?
N/A

#### What did you expect to see?
Some more details about constructing new Requests. 

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/request/request`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Request/Request
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/request/request/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12960 with a fix.

**Comment by mangelozzi** [comment]
Thank for adding that info and clearing it up!! I guess one must learn to read the WHATWG information, it just seems so scary, whereas I have always found the MDN documentation fantastic.

**Comment by sideshowbarker** [comment]
> Thank for adding that info and clearing it up!! I guess one must learn to read the WHATWG information, it just seems so scary, whereas I have always found the MDN documentation fantastic.

Yeah, trying to figure out what some particular behavior is by reading the Fetch spec can be difficult and time-consuming for anybody (including me). But the great thing is that after somebody does it once, and then documents it in MDN, that saves all the rest of us the time and trouble of needing to read the Fetch spec to try to figure it out ourselves 😄
