### ISSUE TITLE
Issue with "Creating and triggering events": …

### ISSUE THREAD

**Issue by massic80** [mdn/content#1297]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

#### What information was incorrect, unhelpful, or incomplete?
In the abstract, the link to the _The_old-fashioned_way_ anchor has uppercase initial.
The actual anchor, _the_old-fashioned_way_ is lowercase.
The link doesn't work

#### Specific section or headline?
Creating custom events

#### What did you expect to see?
I expected [the source](https://github.com/mdn/content/blob/main/files/en-us/web/guide/events/creating_and_triggering_events/index.html) to be the same, but it was uppercase in both places

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/guide/events/creating_and_triggering_events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/guide/events/creating_and_triggering_events/index.html
* Report started: 2021-01-14T10:55:14.766Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this, @massic80 

I've written up an issue of what I think is happening here: https://github.com/mdn/yari/issues/2524

**Comment by massic80** [comment]
Thanks for resolving!
