### ISSUE TITLE
Issue with "<object>: The External Object element": Should "embed a Flash movie" be removed/changed?

### ISSUE THREAD

**Issue by impressivewebs** [mdn/content#12993]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object

#### What information was incorrect, unhelpful, or incomplete?
The page has a small section at the end on how to "embed a Flash movie" with example code referencing including an SWF file.

#### Specific section or headline?
"Examples" section

#### What did you expect to see?
A modern example that doesn't use deprecated or unsupported object embeds.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/object`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/object/index.md
* Last commit: https://github.com/mdn/content/commit/da7f599549a6a36371b9bd9848fa0e3d51379196
* Document last modified: 2021-10-25T20:11:36.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @impressivewebs. Yes, that would be a good idea. Are you willing to  create a PR to fix this?

**Comment by impressivewebs** [comment]
@hamishwillee Sure, I'll use a different example in the code. I think maybe some kind of alternate form of media that's more common would be fine.
