### ISSUE TITLE
Unavailable YouTube embeds (private) - Tools / Page Inspector 

### ISSUE THREAD

**Issue by Productivix** [mdn/content#12994]
MDN URL: https://developer.mozilla.org/fr/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model

#### What information was incorrect, unhelpful, or incomplete?
les last 2 videos are private !!

#### Addendum after transfer
This also applies to https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/tools/page_inspector/how_to/examine_and_edit_the_box_model`
* MDN URL: https://developer.mozilla.org/fr/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/tools/page_inspector/how_to/examine_and_edit_the_box_model/index.html
* Last commit: https://github.com/mdn/translated-content/commit/eb816c469af04c27aa6c230035743b9db0297946
* Document last modified: 2022-02-06T12:46:16.000Z

</details>

**Comment by sideshowbarker** [comment]
See https://github.com/mdn/content/issues/7457

**Comment by hamishwillee** [comment]
https://github.com/mdn/content/issues/12994#issuecomment-1039813368 Which I take to mean "known issue, but you're welcome to copy the pattern in the English version if it has been updated" :-)
