### ISSUE TITLE
Issue with "Element.requestPointerLock()": Document `unadjustedMovement` option

### ISSUE THREAD

**Issue by jespertheend** [mdn/content#13000]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock

#### What information was incorrect, unhelpful, or incomplete?
The requestPointerLock doesn't mention taking an options object.

#### Specific section or headline?
Either "Syntax" or "Browser compatibility"

#### What did you expect to see?
Mentioning of an options object as argument, noting that the availability of the `unadjustedMovement` option.

#### Did you test this? If so, how?
I tried
```js
document.body.addEventListener("mousemove", e => console.log(e.movementX, e.movementY))
document.body.requestPointerLock({unadjustedMovement: true})
```
But did not notice any significant difference on macOS with a trackpad.

####Useful links
[Explainer](https://github.com/slightlyoff/unadjusted_pointer_lock_explainer)
[Blog post](https://web.dev/disable-mouse-acceleration/)
[Spec PR](https://github.com/w3c/pointerlock/pull/49)

How this managed to get into stable Chromium without even the draft spec being merged, I do not know.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/requestpointerlock`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/requestpointerlock/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment]
Correct, because it doesn't according to the specification. The particular PR you point to is not accepted yet.
The proposed change is mentioned in the browser compatibility (or at least the PR is). We'll update the docs when/if the PR goes in.
![image](https://user-images.githubusercontent.com/5368500/153963952-8ca65f6c-f98d-4989-a974-282ea805f98a.png)
