### ISSUE TITLE
Missing HTML global attributes: autofocus and nonce

### ISSUE THREAD

**Issue by foolip** [mdn/content#1300]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes is missing some attributes listed in https://html.spec.whatwg.org/multipage/dom.html#global-attributes

From a manual diffing, `autofocus` and `nonce` are missing on MDN.

cc @sideshowbarker 

Related to https://github.com/mdn/browser-compat-data/pull/7303.

**Comment by Elchi3** [comment]
I've recently documented the `enterkeyhint` global attribute. So, I can take this on.

**Comment by foolip** [comment]
Yay, thanks @Elchi3!

**Comment by sideshowbarker** [comment]
@Elchi3 raised https://github.com/mdn/content/pull/1318 for nonce
