### ISSUE TITLE
Issue with "WebSocket.close()": close status code's default value is ambiguous

### ISSUE THREAD

**Issue by deleteLater** [mdn/content#13010]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close

#### What information was incorrect, unhelpful, or incomplete?
the doc says that the `code` parameter default value is 1005 if not specified, but actually it's 1000 in Chrome Version 98.0.4758.102 (Official Build) (64-bit)
>  If this parameter is not specified, a default value of 1005 is assumed.

#### Specific section or headline?
Syntax > Parameters > code

#### What did you expect to see?
the default value of the `code`  is 1000? Or there is something I missed?

#### Did you test this? If so, how?
```javascript
const ws = new WebSocket(websocketUrl);
ws.onclose = function (event) {
	// the close event's code will be 1000, reason will be string.empty
    console.log(event);
};
ws.close();
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/websocket/close`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/websocket/close/index.md
* Last commit: https://github.com/mdn/content/commit/94485037da46c0e2cc41f13624a6ccc88aa7f0ac
* Document last modified: 2022-01-05T00:52:52.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #13038 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

**Comment by deleteLater** [comment]
Thanks for your great job, very professional 👏
