### ISSUE TITLE
Issue with "File System Access API": Text offers link to "supporting browsers" but section is missing

### ISSUE THREAD

**Issue by aarontgrogg** [mdn/content#13037]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API

#### What information was incorrect, unhelpful, or incomplete?
Opening note:
Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#browser_compatibility).

#### Specific section or headline?
See above.

#### What did you expect to see?
Link usually umps down to compatibility chart.

#### Did you test this? If so, how?
Yes, clicked it.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/file_system_access_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/file_system_access_api/index.md
* Last commit: https://github.com/mdn/content/commit/e752a8fe731fbdb9061e39a6e2b797a7ccb7e2b5
* Document last modified: 2022-01-19T17:57:58.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #13039 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
