### ISSUE TITLE
Issue with "HTTP caching": Wrong Vary header on http_vary.png diagram

### ISSUE THREAD

**Issue by nstdio** [mdn/content#13033]
## What page(s) did you find the problem on?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

## Specific page section or heading?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#varying_responses

## What is the problem?
The [http_vary.png](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching/http_vary.png) diagram suggests that server responded with `Vary: Content-Encoding` header. I believe this is inaccuracy because `Content-Encoding` is a **response** header.

## What did you expect to see?
According to [doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary) it should be `Vary: Accept-Encoding`.

## Did you test this? If so, how?
N/A

**Comment by hamishwillee** [comment]
Thanks. Good catch! Fixed by https://github.com/mdn/content/pull/13083
