### ISSUE TITLE
<nav> usage discrepancy between MDN and W3C HTML living spec

### ISSUE THREAD

**Issue by Zoltanpetrik** [mdn/content#1303]
https://github.com/mdn/content/blob/0d8c3f1ce3e72f620aec1fa2b0c2c2acb7fe9dd7/files/en-us/web/guide/html/using_html_sections_and_outlines/index.html#L127

From the line referenced above I infer than I cannot use `<nav>` in an `<aside>` used as a sidebar to add links to "related articles".

But the example in the spec clearly has an usage like that:

```
 <aside>
  <!-- this aside contains two sections that are tangentially related
  to the page, namely, links to other blogs, and links to blog posts
  from this blog -->
  <nav>
   <h1>My blogroll</h1>
   <ul>
    <li><a href="https://blog.example.com/">Example Blog</a>
   </ul>
  </nav>
  <nav>
   <h1>Archives</h1>
   <ol reversed>
    <li><a href="/last-post">My last post</a>
    <li><a href="/first-post">My first post</a>
   </ol>
  </nav>
 </aside>
```

Source: 3rd exmaple from here: https://html.spec.whatwg.org/#the-aside-element

Is this an issue, or am I misunderstanding something?

**Comment by chrisdavidmills** [comment]
Fixed by https://github.com/mdn/content/pull/1524
