### ISSUE TITLE
Issue with "Express Tutorial Part 3: Using a Database (with Mo…": “FINAL ERR: MongooseError: Operation authors.insertOne() buffering timed out after 10000ms””

### ISSUE THREAD

**Issue by rtobiwan** [mdn/content#13044]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

#### What information was incorrect, unhelpful, or incomplete?
I don't know.

#### Specific section or headline?
populatedb.js

#### What did you expect to see?
I expected my MongoDB Atlas local_library collection to be populated with new documents.

#### Did you test this? If so, how?
Yes. I ran ->  node populatedb 'mongodb+srv://*MYMONGODB:MYPASSWORD*@cluster0.fzgzo.mongodb.net/local_library?retryWrites=true&w=majority' <- on the console and keep getting this error message: FINAL ERR: MongooseError: Operation `authors.insertOne()` buffering timed out after 10000ms

Please help, TY

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/601a273d856ee11aa32dd9ac42d1e84f441c8b58
* Document last modified: 2022-02-03T11:27:16.000Z

</details>

**Comment by rtobiwan** [comment]
**Temporary solve:**

Inside the populatedb.js file, I attached a .then() method after the mongoose.connect method and wrapped all of the rest of the code in the module inside a callback inside of it to make sure it had connected before trying to insert. I don't know if that's the prettiest or the proper practice way to fix the error but it worked. My MongoDB database has now been filled with the library info I needed to proceed with the tutorial. Please advise me of a more proper solution or syntax to the error. I'm sure there must be one. Thank you.

**Comment by hamishwillee** [comment]
The format I used for the url was as shown:
```
mongodb+srv://cooluser:coolpassword@cluster0.a9azn.mongodb.net/local_library?retryWrites=true');
```
The difference appears to be that I didn't wrap it in ' marks, and I didn't use `&w=majority`

**Comment by hamishwillee** [comment]
Does that work for you?

**Comment by sideshowbarker** [comment]
@rtobiwan labeling this with “needs info”, awaiting your response

**Comment by rtobiwan** [comment]
@hamishwillee Thank you Hamish! I'll try it and let you know. :)

**Comment by hamishwillee** [comment]
Great! If we don't hear back in a couple of days I will assume it all just worked :-)

**Comment by rtobiwan** [comment]
I'm afraid I'm still getting the same error. FINAL ERR: MongooseError: Operation authors.insertOne() buffering timed out after 10000ms

**Comment by hamishwillee** [comment]
I will try this myself again on Monday.

**Comment by hamishwillee** [comment]
I think it is the ' chars you have around the url. I tried (exactly) this on Ubuntu and it worked fine.

```
node populatedb mongodb+srv://cooluser:coolpassword@cluster0.a9azn.mongodb.net/local_library?retryWrites=true
```

**Comment by julidagx** [comment]
Changing DNS to 8.8.8.8 worked for me

**Comment by hamishwillee** [comment]
Closing. We can reopen if still a problem.
