### ISSUE TITLE
Issue with "Date.prototype.setDate()": one comment has an incorrect value

### ISSUE THREAD

**Issue by armandoborge** [mdn/content#13047]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setDate

#### What information was incorrect, unhelpful, or incomplete?
The result in the comment for the theBigDay4 values is incorrect

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setDate#examples

#### What did you expect to see?
22nd of July 1962

#### Did you test this? If so, how?
Using the Chrome console

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/setdate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setDate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/setdate/index.md
* Last commit: https://github.com/mdn/content/commit/4d1848584084ee0eaa941e625d30864afa775cff
* Document last modified: 2022-02-11T08:47:56.000Z

</details>

**Comment by teoli2003** [comment]
Yes, you are correct. PR incoming.
![Screenshot 2022-02-16 at 20 10 19](https://user-images.githubusercontent.com/1466293/154338249-81aa29dd-f1e7-48c7-bfea-81043b9cb062.png)
