### ISSUE TITLE
I'm encountering an issue where ` returns undefined and isn't available in the `removeInfo` object either.

### ISSUE THREAD

**Issue by stardud3** [mdn/content#13052]
I'm encountering an issue where `removeInfo.node.title` returns undefined and isn't available in the `removeInfo` object either.

This article specifically shows an example with this in use though: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/onRemoved

May I ask what the issue might be? Is this expected behavior?
not sure what that is tbh^^

_Originally posted by @madebyankur in https://github.com/mdn/content/discussions/12153_

**Comment by Rob--W** [comment]
Thanks for the report. The documentation is correct, but Firefox has a bug. It has been reported before at https://bugzilla.mozilla.org/show_bug.cgi?id=1556427
