### ISSUE TITLE
Issue with "Django Tutorial Part 9: Working with forms": ugettext_lazy is deprecated in django v4

### ISSUE THREAD

**Issue by pfroub** [mdn/content#13070]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms

#### What information was incorrect, unhelpful, or incomplete?
ugettext_lazy is deprecated in django v4

#### Specific section or headline?
forms.py file

#### What did you expect to see?
gettext_lazy

#### Did you test this? If so, how?
runserver crashes

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/forms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/forms/index.md
* Last commit: https://github.com/mdn/content/commit/601a273d856ee11aa32dd9ac42d1e84f441c8b58
* Document last modified: 2022-02-03T11:27:16.000Z

</details>

**Comment by hamishwillee** [comment]
This has not been tested on Django 4. If you follow the instructions you will see that it expects Django 3: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/development_environment#installing_django

I'll see if I can secure some time to go through it again in the coming months. 

Upshot, thanks so much for reporting. I'll leave this open until I can update.
