### ISSUE TITLE
Issue with "Using the Screen Capture API": Does not work on Android

### ISSUE THREAD

**Issue by audas** [mdn/content#13080]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture

#### What information was incorrect, unhelpful, or incomplete?

The example returns an error notice "getDisplayMedia is not a function"

#### Specific section or headline?

Demo example

#### What did you expect to see?

Functioning example of screen capture on Android

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/screen_capture_api/using_screen_capture`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
* Last commit: https://github.com/mdn/content/commit/b7aafea1ab7cfee11a7e854a4b5c83a6e6d329d4
* Document last modified: 2022-02-02T09:11:35.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. You're right - not obvious. Fixed by #13082 which adds a compatibility section.
