### ISSUE TITLE
Replace 0xA0 + smart quotes with normal spaces/quotes

### ISSUE THREAD

**Issue by queengooborg** [mdn/content#13094]
When I've written PRs to modify existing files, my editor of choice has shown me all of these `<0xA0>` characters strewn about all of the files, which I later realized is the character code for a non-breaking space.  I never really understood the reason for using the non-breaking space characters, but in my testing, I've never really found them to have much of an effect on the pages anyways.  I believe that these characters originally came from the old wiki-style system, probably auto-generated by the rich text editor.

I opened #13090 to as a tracking PR for the non-breaking spaces, in which @teoli2003 also mentioned we should replace smart quotes (single and double) with normal quotes.  As such, I have opened this issue to track all of the above.

Current Progress:

- [x] Replace 0xA0 -> normal space
- [ ] Replace smart single quotes
- [ ] Replace smart double quotes

**Comment by teoli2003** [comment]
I think we are done (reopen if not). Do you think you can add an action in the ci to detect the non-breaking spaces and curly ticks? It would be nice not to have them come back (we don't see them in the review tools).
