### ISSUE TITLE
Issue with "Array.prototype.groupBy()": Interactive example seems to be missing

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#13112]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/groupBy

#### What information was incorrect, unhelpful, or incomplete?

The interactive example seems to be missing:

====
404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: pages/js/array-groupby.html
    RequestId: 5DRGEZARZ7FAN4YM
    HostId: G8Km7WGfEFcBmEAWPiyySygyCxaqeHX/x0LO6uoAPP63Wc8FhOZd0M5yLWsm7KFgz0MXUGTJhvw=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: error.html
====

#### Specific section or headline?

Right above the [Syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/groupBy#syntax) section

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/groupby`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/groupBy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/groupby/index.md
* Last commit: https://github.com/mdn/content/commit/6c6c3cdb20d93045316abb4df2b853d184b36738
* Document last modified: 2022-02-17T06:39:29.000Z

</details>

**Comment by sideshowbarker** [comment]
I think this is due to the fact that https://github.com/mdn/interactive-examples/pull/2014 hasn’t been merged and deployed yet.

**Comment by hamishwillee** [comment]
Thanks. This will be fixed by #13162.
FYI @wbamberg Didn't know interactive examples shouldn't exist until broader support. This is nightly only, so makes a lot of sense.
