### ISSUE TITLE
Issue with "Build your own function": (div direct child of html)

### ISSUE THREAD

**Issue by internetword** [mdn/content#13132]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Build_your_own_function

#### What information was incorrect, unhelpful, or incomplete?
`div` element as direct child of `html`element instead of being part of the body.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Build_your_own_function#the_basic_function in step 3.

#### What did you expect to see?
I expect the`div` to be placed as direct child of the `body`.  The html reference section  says the only permitted the only permitted content inside the` <html>` is one `<head>` and one `<body>`. Although, it works fine since it is a learning material, I think it should be as correct as possible. 

I expected to see this: 

```
const body = document.querySelector('body');

const panel = document.createElement('div');
panel.setAttribute('class','msgBox');
body.appendChild(panel);

const msg = document.createElement('p');
msg.textContent = 'This is a message box';
panel.appendChild(msg);

const closeBtn = document.createElement('button');
closeBtn.textContent = 'x';
panel.appendChild(closeBtn);

closeBtn.addEventListener('click', () => panel.parentNode.removeChild(panel));
```

#### Did you test this? If so, how?
I looked in the browser developer console just to be sure it didn't auto-correct.  I'm a beginner so I can't give too much info but I can still spot contradictory info. [html element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/build_your_own_function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Build_your_own_function
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/build_your_own_function/index.md
* Last commit: https://github.com/mdn/content/commit/7e329de8a1ec173df42c8eab9448f93c3e6c7cfa
* Document last modified: 2022-02-02T01:34:30.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #13140 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
