### ISSUE TITLE
Issue with "Array.prototype.groupBy()": (short summary here please)

### ISSUE THREAD

**Issue by enigma1** [mdn/content#13149]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/groupBy

#### What information was incorrect, unhelpful, or incomplete?
First embedded example shows a 404. 

#### Specific section or headline?
Array.prototype.groupBy()

#### What did you expect to see?
An example of the array groupBy method

#### Did you test this? If so, how?
Page access with firefox and by direct access to the iframe
https://interactive-examples.mdn.mozilla.net/pages/js/array-groupby.html

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/groupby`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/groupBy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/groupby/index.md
* Last commit: https://github.com/mdn/content/commit/6c6c3cdb20d93045316abb4df2b853d184b36738
* Document last modified: 2022-02-17T06:39:29.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this. We have https://github.com/mdn/content/issues/13112 open already for tracking the problem — so I’m going ahead and closing this.
