### ISSUE TITLE
Issue with "Bitwise OR (|)": x | 0 does not returns x converted to a 32 bit integer, not x

### ISSUE THREAD

**Issue by MFarmiloe** [mdn/content#13155]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_OR

#### What information was incorrect, unhelpful, or incomplete?
the statement
Bitwise ORing any number x with 0 yields x.
at the end of the Description is incorrect if x is not an integer.

#### Specific section or headline?
Description

#### What did you expect to see?
Bitwise ORing any number x with 0 yields x **converted to a 32-bit integer**.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/bitwise_or`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_OR
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/bitwise_or/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by thedivloop** [comment]
This issue has been corrected, approved and deployed, I guess it can be closed.

**Comment by teoli2003** [comment]
Yes, sorry I forgot to close this!

**Comment by thedivloop** [comment]
Merci!

Divloop
