### ISSUE TITLE
Light / dark color theme per user preference (via `prefers-color-scheme` CSS media query)

### ISSUE THREAD

**Issue by broofa** [mdn/content#13150]
## What is the new suggestion?

Per the title, it would be nice if MDN pages were light/dark styled according to users' system preference.

Websites (and apps) that honor the users current light / dark preference are increasingly common.  Enough so that sites that don't do this (like MDN) are starting to stand out.  (See screen grab below for an example).  As you can see, the difference is pretty jarring.

![CleanShot 2022-02-20 at 05 18 32](https://user-images.githubusercontent.com/164050/154844801-9e3dd5f7-bce3-4db7-bb98-376a482cd489.gif)

## Why is it important or useful?

Prevents users from having ot deal with uncomfortably bright pages when working in dark environs.

## Other supporting information

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by sideshowbarker** [comment]
Thanks for raising this. We have https://github.com/mdn/yari/discussions/2539 open already for tracking discussion about this. See the update at https://github.com/mdn/yari/discussions/2539#discussioncomment-2210250:

> MDN is planning to incorporate a dark theme into their upcoming redesign, so soon there will be no more need for browser extensions and user CSS!
