### ISSUE TITLE
Issue with "IDBTransaction.durability": (short summary here please)

### ISSUE THREAD

**Issue by lll000111** [mdn/content#13159]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction/durability

but also https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction where the third parameter called "options" in the spec for `db.transaction()` should be described.

#### What information was incorrect, unhelpful, or incomplete?

Missing information: How to SET the durability hint.

I only found something following the Chrome issue, leading to their test: https://chromium-review.googlesource.com/c/chromium/src/+/1775557/14/third_party/blink/web_tests/external/wpt/IndexedDB/transaction-relaxed-durability.tentative.any.js#24

Apparently there is a third parameter to `db.transaction()`, which is `{relaxedDurability: boolean}`. HOWEVER, "relaxedDurability" as used in the Chrome test is in conflict with the spec, which says the option is called "durability": https://www.w3.org/TR/IndexedDB/#transaction

![image](https://user-images.githubusercontent.com/25476357/154855550-deab55bb-aa0f-4a94-be29-0dc22b5bc129.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/idbtransaction/durability`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction/durability
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/idbtransaction/durability/index.md
* Last commit: https://github.com/mdn/content/commit/516c74d03bd44861eca7da5a96d287aef846b89d
* Document last modified: 2022-01-27T16:52:19.000Z

</details>

**Comment by teoli2003** [comment]
I've opened a PR with a sentence linking to `IDBDatabase.transaction` that describes the `options` parameter which set it.

**Comment by lll000111** [comment]
@teoli2003 Huh, that was fast. I was stille editing the issue, I changed a few things. Unfortunately there is no "options" 3rd parameter mentioned on https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction

**Comment by teoli2003** [comment]
The parameter is on the constructor method that is on https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/transaction, not on `IDBTransaction`.
