### ISSUE TITLE
Issue with "URL": (short summary here please)

### ISSUE THREAD

**Issue by YOUSU198** [mdn/content#13161]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URL

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/url`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/url/index.md
* Last commit: https://github.com/mdn/content/commit/88508ebe5c73264be2cf03f1a949d8099d68d1ea
* Document last modified: 2022-02-04T02:05:25.000Z

</details>

**Comment by hamishwillee** [comment]
Closing. No problem description.
