### ISSUE TITLE
Issue with "Drawing shapes with canvas": Live examples don't always match screenshots

### ISSUE THREAD

**Issue by merithes** [mdn/content#13173]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes

#### What information was incorrect, unhelpful, or incomplete?

The "Quadratic Bezier curves" example's screenshot looks nothing like the live example (on chrome and FF, Linux and mobile)

#### Specific section or headline?

Quadratic Bezier curves

#### What did you expect to see?

The live example should match the screenshot to a decent extent

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvas_api/tutorial/drawing_shapes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/drawing_shapes/index.md
* Last commit: https://github.com/mdn/content/commit/b7aafea1ab7cfee11a7e854a4b5c83a6e6d329d4
* Document last modified: 2022-02-02T09:11:35.000Z

</details>

**Comment by asususu** [comment]
Is it ok to change the screenshot picture with white background ?
