### ISSUE TITLE
Issue with "i18n": Unable to follow `i18n.js` link to code

### ISSUE THREAD

**Issue by user404d** [mdn/content#13172]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n

#### What information was incorrect, unhelpful, or incomplete?

The `i18n.js` link in the source note in the [Example Extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n#example_extensions) section is broken or requires some type of authentication.

#### What did you expect to see?

The `i18n.js` code and list of supported language tags.

#### Did you test this? If so, how?

Clicked the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/i18n`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/i18n/index.md
* Last commit: https://github.com/mdn/content/commit/0baf49fec367afb6e593067ed872e53e7626c2dd
* Document last modified: 2021-11-29T00:46:14.000Z

</details>

**Comment by rebloor** [comment]
Probably not an issue with the link. Search in Google also pulls up the same link but in the repo the file appears to be missing or is hidden.

**Comment by cw118** [comment]
I believe this was fixed in #16732, the links work now (at least for me).

**Comment by rebloor** [comment]
Confirmed all links working as expected
