### ISSUE TITLE
Issue with "radial-gradient()": missing full function syntax

### ISSUE THREAD

**Issue by d07RiV** [mdn/content#13194]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/radial-gradient()

#### What information was incorrect, unhelpful, or incomplete?

The article lists syntax for `<position>`, `<size>` etc arguments, but never shows the syntax for the full function. It only shows an example (`radial-gradient(circle at center, red 0, blue, green 100%)`), which does not explain how to combine different values together.

Specifically, how do you combine both position and size in the same expression? By trying out all possibilities in a browser it seems that `radial-gradient(<size> <ending-shape> at <position>, ...)` is the correct way.

#### Specific section or headline?

Syntax section

#### What did you expect to see?

Syntax definition for the radial-gradient function

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/gradient/radial-gradient()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/radial-gradient()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/gradient/radial-gradient()/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by NiedziolkaMichal** [comment]
It can be closed.

**Comment by teoli2003** [comment]
Yes. Note that it will take some time to show up in production.
