### ISSUE TITLE
Content suggestion: @font-palette-values and font-palette

### ISSUE THREAD

**Issue by jensimmons** [mdn/content#13215]
The [@font-palette-values](https://drafts.csswg.org/css-fonts-4/#font-palette-values) rule defines a color palette and associates that color palette with a specific font. This allows a web developer to select arbitrary colors to use inside a color font rather than being limited to the preexisting palettes inside font files. 

## Why is it important or useful?
For one, it makes it easy for a website to use one color palette in a color font for light mode, and another for dark mode. 

## How many pages are likely to be needed?
One page, with a browser support table.

## Other supporting information
- https://drafts.csswg.org/css-fonts-4/#font-palette-values
- Support for this feature is in Safari 15.4 beta. https://bugs.webkit.org/show_bug.cgi?id=230337

**Comment by jensimmons** [comment]
The @font-palette-values at-rule shipped in March 2022 in Safari 15.4. It also shipped in April in Chrome 101. 
https://caniuse.com/css-font-palette 

It's something web developers are going to be looking to MDN to help them understand.

**Comment by teoli2003** [comment]
Yes, both would be nice to have. I have no bandwidth to write these two articles right now, but we will happily review any PR. 

Note for the future writer: the at-rule and the property don't need to be added in the same PR, but they can if you want.

**Comment by Josh-Cena** [comment]
Fixed by #22519
