### ISSUE TITLE
What is :// ?

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#1322]
In 
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#deeper_dive

what is `://`?

![Screenshot_20210114-202840.png](https://user-images.githubusercontent.com/44380480/104638942-1cf0c380-56a7-11eb-8814-6f6eacad319b.png)

**Comment by hamishwillee** [comment]
Good point. My understanding is that they are separators marking the end of the scheme (could be wrong). IN any case, possibly the term scheme is more appropriate than _protocol_ here, and by way of example we should use https rather than http.

**Comment by mattiapontonio** [comment]
FTR
https://developer.mozilla.org/en-US/docs/Web/API/URL/protocol

**Comment by tannerdolby** [comment]
To address what @hamishwillee mentioned, With the following URI: `foo://bar.com:8042/some/path?filter=cats#orange`

- The scheme is `foo`
- The authority is `bar.com:8042`
- The path is `/some/path`
- The query is `filter=cats`
- The fragment is `orange`

So I do agree, the `scheme` ends at the start of `://`. 

To explain the semantics of `://`, as described in the [RFC - Section 3](https://tools.ietf.org/html/rfc3986#section-3). If there is a `//` in a URL, it means that what follows is the _authority_. The colon `:` is simply a delimiter.

If a scheme uses an _authority_, it will use the `//` after the `:` colon. If a URI doesn't use or require an authority, it will not use the `//`. 

As a note, the generic URI syntax (referred to as the scheme, authority, path, query, and fragment) looks like this:

```
URI = scheme ":" hier-part [ "?" query ] [ "#" fragment ]
```

**Comment by tannerdolby** [comment]
An example of a URI that doesn't use an authority would be `mailto:foo@gmail.com`. Which wouldn't require `//` since it doesn't use an authority. 

If it did then it would look like `mailto://foo@gmail.com` which doesn't make much sense.

**Comment by Ryuno-Ki** [comment]
I could be wrong, but I think, the `:` belongs to the scheme.
I also vaguely recall, that Sir Tim Berners-Lee mentioned in an interview, that the `//` is the only thing they regret when launching the WWW.
It adds more noise than anything else.

I can imagine, it was used to separate from the root of an UNIX file system (which would be `/`).

**Comment by mattiapontonio** [comment]
> I can imagine, it was used to separate from the root of an UNIX file system (which would be /).

If confirmed that's intresting 👍

**Comment by hamishwillee** [comment]
Hi @tannerdolby I've assigned to you - a PR would be great thanks. We can then discuss the detail based on concrete changes :-)

**Comment by tannerdolby** [comment]
@Ryuno-Ki The `:` doesn't belong to the scheme as described in the [RFC](https://tools.ietf.org/html/rfc3986). It can just be thought of as just a separator or delimiter. To be succinct, it's more of a indicator for the end of the scheme and the start of the hier-part, so it "separates" the scheme and hier-part. 

> I also vaguely recall, that Sir Tim Berners-Lee mentioned in an interview, that the `//` is the only thing they regret when launching the WWW.

You are correct about the above. Sir Tim Berners-Lee did mentioned the `//` is the thing they regretted when launching the WWW. The `//` really doesn't have any use other than for URIs with authority like I mentioned above. "The authority component is preceded by a double slash ("//")".

> I can imagine, it was used to separate from the root of an UNIX file system (which would be /).

I can't say for certain what their thoughts were but yes, the relative part `/` is distinctly different than `//`.

**Comment by tannerdolby** [comment]
Hi @hamishwillee Ok great. I will write up a PR for this and we can then discuss the detail. Thanks :-)
