### ISSUE TITLE
Issue with "lang": Flags used to represent languages in interactive example should be removed

### ISSUE THREAD

**Issue by boydkelly** [mdn/content#13238]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang

#### What information was incorrect, unhelpful, or incomplete?
Flags are used to represent or display languages on this page.

Flags do not represent languages.  They represent countries.  A given language maybe spoken in dozens of countries. A single country may have several national and coequal languages.   The British flag does not represent English for a speaker in Ghana.   A French flag does not represent French for a speaker in Canada.

Just don't do it.

#### Specific section or headline?
html demo

#### What did you expect to see?
No flag

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/global_attributes/lang`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/lang/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by teoli2003** [comment]
Yes, this is an anti-pattern. I opened a PR to fix it. Thanks!
