### ISSUE TITLE
Issue with "Structuring planet data": Little error in the source code of the finished example

### ISSUE THREAD

**Issue by matheus4lves** [mdn/content#13237]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Structuring_planet_data

#### What information was incorrect, unhelpful, or incomplete?

The finished table of the assessment, provided in the [see the example live here](https://mdn.github.io/learning-area/html/tables/assessment-finished/planets-data.html) link has a little mistake. Its source code has the scope of first &lt;th&gt; inside the last &lt;tr&gt; set to _rowgroup_, when it should have been set to _row_.

#### Specific section or headline?

The **Example** heading

#### What did you expect to see?

The scope for the last row should be equals to: scope="row", not scope="rowgroup"

#### Did you test this? If so, how?

No test required.

<details>
<summary>MDN Content page report details</summary>

- Folder: `en-us/learn/html/tables/structuring_planet_data`
- MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Structuring_planet_data
- GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/tables/structuring_planet_data/index.md
- Last commit: https://github.com/mdn/content/commit/1ce6fbd041d6b51d5c0f8b918aa118f5ddc9861c
- Document last modified: 2022-02-03T22:20:49.000Z

</details>

**Comment by AnilSeervi** [comment]
Opened mdn/learning-area#466 as a fix.

**Comment by gargabhishek100** [comment]
is this issue is still open /anyone working on the same?

**Comment by teoli2003** [comment]
Hi! There was an opened PR to fix this. I just reviewed it, then merged it. So this has been closed now.
