### ISSUE TITLE
Issue with "transition-delay": (transition-property values must be separated by commas)

### ISSUE THREAD

**Issue by nadalsol** [mdn/content#13250]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transition-delay

#### What information was incorrect, unhelpful, or incomplete?

```
transition-property: background-color font-size transform color;
```

#### Specific section or headline?

CSS section (code blocks).

#### What did you expect to see?

```
transition-property: background-color, font-size, transform, color;
```

#### Did you test this? If so, how?

With Chrome Dev Tools:
![Screenshot 2022-02-24 at 11 29 42](https://user-images.githubusercontent.com/50826322/155507208-27600f3c-44e0-44b3-8aad-61e61d3f3198.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/transition-delay`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transition-delay
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/transition-delay/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by teoli2003** [comment]
You're right, good catch (our `transition-property` pages is correct). I opened a PR to get this fixed.
