### ISSUE TITLE
missing integrated authentication docs

### ISSUE THREAD

**Issue by mkropf** [mdn/content#13253]
Hi, I'm missing the docs about integrated authentication, the link [https://developer.mozilla.org/en-US/docs/Mozilla/Integrated_authentication](https://developer.mozilla.org/en-US/docs/Mozilla/Integrated_authentication) seems broken.

**Comment by sideshowbarker** [comment]
Hi — https://github.com/mdn/archived-content/blob/main/files/en-us/mozilla/integrated_authentication/index.html has the source of that document.

It was intentionally removed from MDN and archived there.

https://web.archive.org/web/20210608095530/https://developer.mozilla.org/en-US/docs/Mozilla/Integrated_authentication has a rendered version.
