### ISSUE TITLE
Issue with "Select an element": (short summary here please)

### ISSUE THREAD

**Issue by brclouse** [mdn/content#13263]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_an_element

#### What information was incorrect, unhelpful, or incomplete?

Can't watch any of the videos, they are listed as Private

#### Specific section or headline?

Videos

#### What did you expect to see?

Videos

#### Did you test this? If so, how?

Clicked the links, couldn't see videos.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/select_an_element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_an_element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/select_an_element/index.html
* Last commit: https://github.com/mdn/content/commit/526608c380abfb84b3b98b8419206d83e1327f54
* Document last modified: 2022-02-18T09:18:43.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — we have https://github.com/mdn/content/issues/7457 open already for tracking the issue, so I’m going ahead and closing this.
