### ISSUE TITLE
PLEEEEAAAASEEEE make a dark mode button on MDN...You wonderful people keep teaching us about web dev, and yet you don't have a dark mode on the learning pages....

### ISSUE THREAD

**Issue by AronCodes21** [mdn/content#13266]

**Comment by sideshowbarker** [comment]
We have https://github.com/mdn/yari/discussions/2539 open already for tracking discussion about this. See the update at https://github.com/mdn/yari/discussions/2539#discussioncomment-2210250:

> MDN is planning to incorporate a dark theme into their upcoming redesign, so soon there will be no more need for browser extensions and user CSS!

**Comment by AronCodes21** [comment]
Oh my, that's amazing! I can't wait:D
Any idea when that might be?
