### ISSUE TITLE
Issue with "Building a cross-browser extension": Emphasis where Promises cannot be used

### ISSUE THREAD

**Issue by minfrin** [mdn/content#13275]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

#### What information was incorrect, unhelpful, or incomplete?

According to the document, it is recommended that promises be used:

> Firefox also supports callbacks for the APIs that support the chrome.* namespace. However, using promises (and the browser.* namespace) is recommended. Promises have been adopted as part of the proposed standard. It greatly simplifies asynchronous event handling, particularly where you need to chain events together.

Promises cannot cross the content-script / page boundary, and this needs to be emphasised so time isn't wasted trying to use Promises when they are not supported.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension#api_asynchronous_event_handling

#### What did you expect to see?

Clear indication that promises cannot be returned to pages from web extensions, and that promises should be avoided for this purpose.

#### Did you test this? If so, how?

Bug raised here: https://bugzilla.mozilla.org/show_bug.cgi?id=1757066

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.md
* Last commit: https://github.com/mdn/content/commit/0160aac0e623dacdce4019205f32f7b3d3e58019
* Document last modified: 2022-02-18T09:33:58.000Z

</details>

**Comment by guest271314** [comment]
For browser extension the simplest approach I have found to stream from Native Messaging host is to 

1. Include `"web_accessible_resources"` key in the manifest, with `"*.js"`, `"*.html"` set in `"resources"`
2. Append an `<iframe>` to target document
3. Use `onmessage`, `postMessage()` between target document and appended `<iframe>` to stream data from Native Message host to `<iframe>` to and from document

`Promise` is not really needed to achieve the requirement.

**Comment by rebloor** [comment]
This issue has been partially addressed by [#19125 promise cloneinto clarification](https://github.com/mdn/content/pull/19125) and Clarify sharing objects with page scripts impact on build a cross browser extension [#20779](https://github.com/mdn/content/issues/20779) created to add information relating to cross browser extension development.
