### ISSUE TITLE
Issue with "Getting started with the Web": (short summary here please)

### ISSUE THREAD

**Issue by Setr43** [mdn/content#13278]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/index.md
* Last commit: https://github.com/mdn/content/commit/0b270d4f95ba1c4abcc81215df774a9448a78105
* Document last modified: 2022-02-18T09:10:31.000Z

</details>

**Comment by dipikabh** [comment]
Hello @Setr43, welcome to the MDN project! 

In your description comment, it would help if you could explain the issue you spotted on that page. Please also update the title of this issue to reflect the problem you are seeing. Thanks!
