### ISSUE TITLE
Issue with "Set": `keys` does not appear as a method in the left sidebar

### ISSUE THREAD

**Issue by gibson042** [mdn/content#13286]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

#### What information was incorrect, unhelpful, or incomplete?
In the left sidebar, **Methods** includes `Set.prototype.values()` but does not include `Set.prototype.keys()`, presumably because /en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/keys is a redirect to /en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/values and lacks its own content under files/en-us/web/javascript/reference/global_objects/set.

#### Specific section or headline?
See above.

#### What did you expect to see?
I expected to see all methods documented.

#### Did you test this? If so, how?
Yes, and I can get the item to appear by creating files/en-us/web/javascript/reference/global_objects/set/keys/index.md (but this trumps the redirect in every respect, which may not be desirable).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/set/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by wbamberg** [comment]
I saw this bug, and thought, that's tricky. We use the `JSRef` macro to build this sidebar and of course it fetches the subpages of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set get the list of entries: https://github.com/mdn/yari/blob/e2090997003552ecfac6dfd0552722629f237ead/kumascript/macros/JSRef.ejs#L84

Honestly I can't think of a better way than hardcoding it in the macro. This seems like an unusual enough case that it is better to do that than to try some general fix.

**Comment by wbamberg** [comment]
> What is the rationale for not creating a keys() page and complexify a macro?

Fair point. I was just answering "short of creating a Set.prototype.keys() page". But although they have the same behaviour, the content can be different (examples, spec URL, see also links) so perhaps it's better to have 2 pages.

**Comment by sideshowbarker** [comment]
Richard, thanks for raising this — I’ve opened #13326 with a fix.
