### ISSUE TITLE
Issue with "color-gamut": (short summary here please)

### ISSUE THREAD

**Issue by KempWatson** [mdn/content#13287]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut

Are you sure the "p3" is for DCI-P3? this is a terrible choice for web on monitors... maybe you mean Display P3?
Also, the CSS Color Module Level 4 CSS says "display-p3", not "p3", so this seems REALLY inconsistent as Display P3 and DCI-P3 are extremely different things.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/@media/color-gamut`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@media/color-gamut/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by wbamberg** [comment]
Yes, it looks like this ought to be "Display P3" : https://drafts.csswg.org/mediaqueries/#color-gamut
