### ISSUE TITLE
Issue with "image-set()": Alternate image format example isn't showing

### ISSUE THREAD

**Issue by chumbud** [mdn/content#13285]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set()

#### What information was incorrect, unhelpful, or incomplete?
Under "[Using image-set() to provide alternative image formats](https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set()#using_image-set_to_provide_alternative_image_formats)" the example isn't showing up. Looks like the syntax of the property is coming up as invalid.

#### Specific section or headline?
[Using image-set() to provide alternative image formats](https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set()#using_image-set_to_provide_alternative_image_formats)

#### Did you test this? If so, how?
![Screen Shot 2022-02-25 at 1 55 54 PM](https://user-images.githubusercontent.com/3811510/155772014-91ebc5c2-281e-495b-b741-188e14bd68b0.png)
Tested on Mac/Chrome Version 98.0.4758.109

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/image/image-set()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/image/image-set()/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by chumbud** [comment]
Oh, I see types aren't supported on chrome. Is there a fallback that can be used in this situation? If not, this can be closed.

**Comment by wbamberg** [comment]
> Oh, I see types aren't supported on chrome.

It looks that way. Can I ask if you have particular evidence for Chrome not supporting `type()`? Other than the example not working I mean. Like an open bug or something.

Because the page doesn't indicate that (although it should).

**Comment by chumbud** [comment]
Basing it on what I found on caniuse https://caniuse.com/?search=image-set and also this ticket https://chromestatus.com/feature/5432024223449088

**Comment by wbamberg** [comment]
Perfect, thank you! I just went to create an issue in browser-compat-data and found that we already have one: https://github.com/mdn/browser-compat-data/issues/14780.

So I'll just close this one :)

**Comment by chumbud** [comment]
Gotcha, thanks for the help!
