### ISSUE TITLE
Issue with "HTML elements reference": Missing link to `<plaintext>` page

### ISSUE THREAD

**Issue by colejohnson66** [mdn/content#13288]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element

#### What information was incorrect, unhelpful, or incomplete?
Missing link to `<plaintext>`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/plaintext

#### Specific section or headline?
Possibly under "obsolete", but WhatWG's HTML standard [still mandates support for it](https://html.spec.whatwg.org/#plaintext-state), and the compatibility chart for it shows full support.

#### What did you expect to see?
As above.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by colejohnson66** [comment]
Probably worth checking that all elements with pages (see [here](https://github.com/mdn/content/tree/main/files/en-us/web/html/element)) are pointed to also.

**Comment by wbamberg** [comment]
It is listed here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element#obsolete_and_deprecated_elements isn't it?

**Comment by colejohnson66** [comment]
Yes. I could swear it wasn’t there…

**Comment by wbamberg** [comment]
ha, I promise I didn't sneakily add it :)
