### ISSUE TITLE
Issue with ''String.prototype.toString()'': No mention/example of number-to-binary conversion ability 

### ISSUE THREAD

**Issue by MubashirWaheed** [mdn/content#13290]
## What page(s) did you find the problem on?
MDN URL: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toString)
## Specific page section or heading?
In JavaScript demo on the page 
## What is the problem?
MDN docs don't have number to binary conversion example on above linked page 
I was looking to convert numbers into binary and came across the second solution on StackOverflow [https://stackoverflow.com/questions/62933631/how-do-i-randomly-generate-a-binary-number-in-javascript](https://stackoverflow.com/questions/62933631/how-do-i-randomly-generate-a-binary-number-in-javascript) 

## What did you expect to see?
There should be an example showing `toString` can be used to convert string to binary
e.g `(42).toString(2);       // '101010'`

**Comment by NegiAkash890** [comment]
@sideshowbarker can I work on this ?

**Comment by moflaky** [comment]
Hi, not sure if @NegiAkash890 is still working on this, but I would love to give it a try.  I am new to open source and feel I could help with this issue.

**Comment by Rumyra** [comment]
This has been addressed in the above pr 👍
