### ISSUE TITLE
Issue with "counter-reset": What is the difference in behavior between the latest Firefox (82 or later) and the older 81 or earlier or other browsers?

### ISSUE THREAD

**Issue by debiru** [mdn/content#13293]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/counter-reset

Maybe the page to fix is this: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters

#### What information was incorrect, unhelpful, or incomplete?

- (p1) I know that starting with Firefox 82, the behavior of counter-reset has changed from 81 and earlier versions.
    - https://bugzilla.mozilla.org/show_bug.cgi?id=1754521
- (p2) For example, the results of the CSS Demo for counter-reset are different between Firefox (the latest version) and Google Chrome.
    - https://developer.mozilla.org/en-US/docs/Web/CSS/counter-reset
- (p3) The ol and ul elements use CSS counter(list-item) to calculate the numbering in the marker.
    - https://drafts.csswg.org/css-lists/#propdef-list-style-type
- (p4) I'd like to see a clear sample of the difference in behavior between counter-reset and counter-set.
- (p5) In addition, I would like to see a more helpful example of how to use reversed().

It is my hope that the documentation will clearly explain why each browser behaves the way it does.

In particular, I think the following current statement is wrong.

> The value to reset the counter to on each occurrence of the element. Defaults to 0 if not specified. 

The latest version of Firefox doesn't seem to reset to on each occurrence of the element. This may just be because it resets the counter, but creates another instance, which makes it look like the counter is not being reset.

#### Related specs

- https://www.w3.org/TR/css-lists-3/#counter-reset
- https://drafts.csswg.org/css-lists/#counter-reset
- https://github.com/w3c/csswg-drafts/issues/4244
- https://github.com/w3c/csswg-drafts/issues/5477
- https://html.spec.whatwg.org/#lists
- https://drafts.csswg.org/css-lists/#propdef-list-style-type

#### Related links

- https://bugzilla.mozilla.org/show_bug.cgi?id=1548753
- https://github.com/mdn/content/issues/3737
- https://github.com/mdn/content/issues/6360
- https://bugzilla.mozilla.org/show_bug.cgi?id=1754521
- https://bugzilla.mozilla.org/show_bug.cgi?id=1757269

#### What did you expect to see?

I don't know what the specs say about subtle nuances and what is the right way to behave.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/counter-reset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/counter-reset
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/counter-reset/index.md
* Last commit: https://github.com/mdn/content/commit/c2349cdb4688f6e5a8c90ae12addada359dbca4c
* Document last modified: 2022-01-28T02:17:46.000Z

</details>

**Comment by debiru** [comment]
I have rewritten [Using CSS counters](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters). That draft document is https://css-counters.lavoscore.org/.

My rewrite contains the following issues:

- Since I am Japanese and not good at English, there is a possibility that the English sentence is incorrect.
- Last item in browser compatibility "Does not apply implicit ..." is not an implementation item specified in the specification.
    - refs. https://github.com/w3c/csswg-drafts/issues/4244
    - If possible, I would like to show differences in behavior between browsers, rather than implementation status.
- Other documents, such as counter-reset, have not been modified, but we have not decided how to indicate the relevant documents.

To account for these issues, [Using CSS counters](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters) needs to be rewritten and linked from other related documents.

**Comment by sideshowbarker** [comment]
@debiru, If you open a pull request with your changes, that could be reviewed and eventually merged. We don’t otherwise have a process for reviewing changes posted elsewhere.

**Comment by debiru** [comment]
I have not expect you to review drafts written on external sites. It is written only for reference.

As indicated in this topic, the behavior regarding counter-reset has changed after Firefox 82, and users cannot learn more about those behaviors just by reading MDN.

This Issue seeks to remedy that situation. However, I am not able to make a complete pull request including https://github.com/mdn/browser-compat-data/.

I will put it on hold for the time being.

**Comment by OnkarRuikar** [comment]
I've raised [a Chromium bug](https://issues.chromium.org/issues/354025385) because it doesn't respect the inbuilt `list-item` counter.
