### ISSUE TITLE
Issue with "Grammar and types": (the output is undefiend not ReferenceError)

### ISSUE THREAD

**Issue by ahmadalzoubi13579** [mdn/content#13300]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types

#### What information was incorrect, unhelpful, or incomplete?

when executing the following code 
```
console.log(x); // ReferenceError
let x = 3;
```

i am getting `undefiend` not `ReferenceError` as mentioned in the docs.

#### Specific section or headline?

[Variable hoisting](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#variable_hoisting)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/grammar_and_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/grammar_and_types/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by sideshowbarker** [comment]
> i am getting `undefiend` not `ReferenceError` as mentioned in the docs.

In which browser?

And please either copy and paste the exact error message the browser is reporting — or else please post a screenshot.

 Every browser I’ve tried it in gives a `ReferenceError` as expected.

**Comment by teoli2003** [comment]
Here is my test in Firefox:

![Capture d’écran 2022-02-27 à 07 05 52](https://user-images.githubusercontent.com/1466293/155870455-d0cade6d-1b04-412f-b9ee-d9bffa6ec18c.png)

**Comment by ahmadalzoubi13579** [comment]
@sideshowbarker you're right, i was playing with the following [code](https://codesandbox.io/s/great-herschel-dbzwln?file=/src/index.js)
i don't know why the output is not like the docs.

**Comment by Sly-Ozc-34** [comment]
692319

**Comment by sideshowbarker** [comment]
> i was playing with the following [code](https://codesandbox.io/s/great-herschel-dbzwln?file=/src/index.js)
> i don't know why the output is not like the docs

I’m not sure why either — but given there’s not an error in the example in the docs, I’m going ahead and closing this

**Comment by hamishwillee** [comment]
Good call @sideshowbarker . 

@ahmadalzoubi13579 I can explain this. See the code (from doc) here:

```
let x;
console.log('The value of x is ' + x); // The value of x is undefined

console.log('The value of y is ' + y); // Uncaught ReferenceError: y is not defined
let y;
```

So in the first case you declare `x` and it is initialised to `undefined`. So when you log the value it is `undefined`.
In the second case you have not declared `y` when you use it. `y` is hoisted (meaning memory is allocated for it), but it is not initialised to anything, which is why you get a reference error. Had it been a `var` it would have been hosted AND assigned to `undefined`.
