### ISSUE TITLE
Issue with "Using CSS custom properties (variables)": the explanation does not match the code example

### ISSUE THREAD

**Issue by sharonytlau** [mdn/content#13315]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

#### What information was incorrect, unhelpful, or incomplete?

> The paragraph color will not be blue because invalid substitution is replaced by the initial value, not by the fallback. If you had written `color: 16px` without any variable substitutes, then it was a syntax error. The previous declaration will then be used.

#### Specific section or headline?

[What happens with invalid variables?](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#what_happens_with_invalid_variables)

#### What did you expect to see?

The code example or the explanation should be changed.

The code example in question is:

```
:root { --text-color: 16px; }
p { color: blue; }
p { color: var(--text-color); }
```

The current explanation for this example (pasted above)  has implied that `blue` is "the fallback" of the paragraph color. However, in the example, the color `blue` is in the previous declaration as a cascaded value, rather than in the `var()` function as a fallback value.

I think a more precise explanation of why the paragraph color is not blue in this example should be like: 

> The paragraph color will not be blue because invalid substitution is replaced by the initial value, not by the **cascaded value**.

Or, if we want a code example that matches the current explanation, we can change the code example to something like:

```
:root { --text-color: 16px; }
p { color: red; }
p { color: var(--text-color, blue); }
```

Here the second argument `blue` in the `var()` function is by definition a fallback value, which means it will be in effect when the custom property `--text-color` is not defined. Besides, in this suggested new code example, the first declaration uses a different color: `p { color: red; }` instead of `p { color: blue; }`. 

This way, we may improve the explanation by making it clearer which color value will be in effect in different cases:

> The paragraph color will not be blue because invalid substitution is replaced by the initial value, not by the fallback. If you had written `color: 16px` without any variable substitutes, then it was a syntax error. The previous declaration **`color: red`** will then be used.

#### Did you test this? If so, how?

Yes. I've tested which color will be in effect for each case mentioned in the code example explanation. 

Specifically,

- If the custom property is not defined,

```
p { color: red; }
p { color: var(--text-color, blue); }
```

The fallback value `blue` will be in effect.

-  If the custom property is defined but not valid:

```
:root { --text-color: 16px; }
p { color: red; }
p { color: var(--text-color, blue); }
```

The initial value (normally is `black`) will be in effect.

-  If the declaration is written without using a custom property but has a syntax error:

```
p { color: red; }
p { color: 16px; }
```

The cascaded value `red` will be in effect. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/using_css_custom_properties`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/using_css_custom_properties/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by ibrahim-301** [comment]
This was mentioned again in https://github.com/mdn/content/issues/14318 and appears to be handled in https://github.com/mdn/content/pull/15736
