### ISSUE TITLE
Issue with "Intl.Locale.prototype.weekInfo": Incorrect Weekend output for Brunei Darussalam

### ISSUE THREAD

**Issue by MohsenAlyafei** [mdn/content#13311]
The `Intl.Locale.prototype.weekInfo` property gives incorrect weekend information for Brunei Darussalam.

```
console.log(new Intl.Locale("en-BN").weekInfo);  // logs { firstDay: 1, weekend: Array [6, 7], minimalDays: 1 }
```

Meaning that the Weekend in Brunei starts on day 6 (Saturday) and ends on day 7 (Sunday) which is incorrect as Brunei's weekend is on Friday and Sunday.

Brunei like 2 other regions in the world has a non-contiguous working week with **Friday** and **Sunday** being the weekend.

More information here: https://en.wikipedia.org/wiki/Workweek_and_weekend

**Comment by sideshowbarker** [comment]
This sounds like a problem in implementations of `Intl.Locale.prototype.weekInfo`, not a problem in MDN content.

**Comment by MohsenAlyafei** [comment]
The implementation seems incorrect. Rather tan have an array of weekend **start** and weekend **end**, the array should hold the day numbers that are weekend. The weekend days are not always continuous!

In the case of Brunei it should be:   { firstDay: 1, **weekend: Array [5, 7]**, minimalDays: 1 }

In UAE (Sharja) it is 3 days weekend so the array will be: { firstDay: 1, **weekend: Array [5, 6, 7]**, minimalDays: 1 }

**Comment by sideshowbarker** [comment]
So it doesn’t sound like there’s any change we can make to MDN content to fix this. MDN is just documenting the behavior defined in the spec.

It sounds this should instead be reported either in one or more browser-project issue trackers as a browser bug, or else reported in the issue tracker for the spec, as a spec bug.

Do you otherwise have an suggestion for specific changes that should be made to MDN content in regard to this?

**Comment by MohsenAlyafei** [comment]
I agree. We should close this issue. The specification [UTS 35's Week Elements](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Patterns_Week_Elements) need to be addressed.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/13311#issuecomment-1054076740
