### ISSUE TITLE
Content bug: background-clip: text; support on Edge (Chromium) mislabelled

### ISSUE THREAD

**Issue by AtherActive** [mdn/content#13314]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip#browser_compatibility

## What is the problem?

The support section labels Edge as supported for **background-clip: text;** . After multiple hours of testing this does not seem to hold true on Chromium Edge. It instead displays an error in the CSS section of Devtools and does not render the component to which this rule is applied as intended. Using the -webkit prefix does allow it to function fine.

(version:  98.0.1108.56 (Official build) (64-bit) )

## What did you expect to see?

The background should have been clipped to the text. EG: If the background is set to RED, then clipping it and making the regular text color transparent should have made the text red, like it does with the Webkit prefix.

For documentation this means that it should not be labelled as fully supported if it is in fact not supported.

## Did you test this? If so, how?

Testing was conducted on a local webserver:
- Created a CSS file with background-clip on a **h6** element. I also made the text transparent so that the background would render on the area where the text is.
- I then opened the page, and saw that the clip was not applied properly and was displaying the background on the entire box, **Not** only the text like it should. It also shows me a warning that the CSS is invalid.
- I added the -webkit prefix and reloaded the page. This time it did clip correctly and only the text was changed.

## Conclusion

After these tests it seems that it is in fact not fully supported on Edge (chromium).

**Comment by sideshowbarker** [comment]
Thanks for raising this. This issue should actually be in the https://github.com/mdn/browser-compat-data/issues issue tracker — and normally I’d be able to transfer it over there, but for some reason GitHub doesn’t seem to be letting me transfer it…

**Comment by AtherActive** [comment]
> Thanks for raising this. This issue should actually be in the https://github.com/mdn/browser-compat-data/issues issue tracker — and normally I’d be able to transfer it over there, but for some reason GitHub doesn’t seem to be letting me transfer it…

Heya, I can move it there if thats better? If its fine here I'll just leave it but if its better there then Ill move it

**Comment by sideshowbarker** [comment]
> > Thanks for raising this. This issue should actually be in the [https://github.com/mdn/browser-compat-data/issues](https://github.com/mdn/browser-compat-data/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) issue tracker — and normally I’d be able to transfer it over there, but for some reason GitHub doesn’t seem to be letting me transfer it…
> 
> Heya, I can move it there if thats better? If its fine here I'll just leave it but if its better there then Ill move it

Yeah, if you can could open a new issue for it there, that’d be great. (I just tried again moving this one myself, but GitHub’s still not letting me do it…)

**Comment by AtherActive** [comment]
Issue ported over to the correct repo. Can now be found [here](https://github.com/mdn/browser-compat-data/issues/15172#issue-1154244943)
