### ISSUE TITLE
Issue with "Framework main features": (link diagram of a React component's lifecycle not loading)

### ISSUE THREAD

**Issue by hntddt123** [mdn/content#13325]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Main_features

#### What information was incorrect, unhelpful, or incomplete?
https://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/  link not load

#### Specific section or headline?
[Lifecycle](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Main_features#lifecycle)

#### What did you expect to see?
Life cycle of react diagram

#### Did you test this? If so, how?
Link not loading 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/main_features`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Main_features
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by sideshowbarker** [comment]
> [projects.wojtekmaj.pl/react-lifecycle-methods-diagram](https://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/) link not load

It seems to be loading fine for me now. Is it still not loading for you?

**Comment by hntddt123** [comment]
it's loading now Thanks
