### ISSUE TITLE
Issue with "<source>: The Media or Image Source element": Missing information on media attribute when effective

### ISSUE THREAD

**Issue by noahbald** [mdn/content#13323]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source

#### What information was incorrect, unhelpful, or incomplete?
Media queries not supported for video sources in chrome

#### Specific section or headline?
Attributes

#### What did you expect to see?
The `media` attribute has an effect only when the [source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source) element is the direct child of a [picture](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) element.

https://stackoverflow.com/questions/25907930/chrome-not-respecting-video-source-inline-media-queries

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/source`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/source/index.md
* Last commit: https://github.com/mdn/content/commit/56cef13241e8d9e9ba980840e28202152e099f36
* Document last modified: 2022-02-02T09:01:58.000Z

</details>

**Comment by Para505** [comment]
Stephen Balogh

On Feb 27, 2022, at 5:35 PM, Noah Baldwin ***@***.***> wrote:

﻿
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source

What information was incorrect, unhelpful, or incomplete?

Media queries not supported for video sources in chrome

Specific section or headline?

Attributes

What did you expect to see?

The media attribute has an effect only when the source element is the direct child of a picture element.

https://stackoverflow.com/questions/25907930/chrome-not-respecting-video-source-inline-media-queries

Did you test this? If so, how?

MDN Content page report details

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #13327 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
