### ISSUE TITLE
Issue with "Cache": Clarification on all headers or just Set-Cookie headers stripped

### ISSUE THREAD

**Issue by mangelozzi** [mdn/content#13335]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Cache

Firstly thank you for this amazing resource, it is so helpful.

#### What information was incorrect, unhelpful, or incomplete?

> [Storing cookies in Caches](https://developer.mozilla.org/en-US/docs/Web/API/Cache#storing_cookies_in_caches)
The [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) requires [Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) headers to be stripped before returning a [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) object from [fetch()](https://developer.mozilla.org/en-US/docs/Web/API/fetch). So a Response stored in a Cache won't contain headers.> 

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Cache#storing_cookies_in_caches

#### What did you expect to see?
Maybe it is just tme, but I am unsure if the paragraph means all headers are stripped when getting a response from the cache, or just `set-cookie` headers are stripped? Seems quite extreme if it stripped all headers from the response just to fix the case of one header clashing.

#### Did you test this? If so, how?
N/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/cache`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Cache
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/cache/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by sideshowbarker** [comment]
@Jxck, @mnot: The statement _“So a Response stored in a Cache won't contain headers”_ here just seems wrong. And it’s not clear to me why somebody thought this point about Fetch stripping out `Set-Cookie` headers merited a section titled **Storing cookies in Caches**.

This addition to the docs was made back in the wiki days — when all changes went in unreviewed. So I’m not sure what the actual intended point of this section is. While _“The [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) requires [Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) headers to be stripped before returning a [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) object from [fetch()](https://developer.mozilla.org/en-US/docs/Web/API/fetch)”_ is true, it doesn’t necessarily need to be stated in this particular document, which is a conceptual overview of HTTP caching behavior. In that context it seems like a bit of non sequitur.

Maybe we can just delete the entire section?

**Comment by Jxck** [comment]
It seems mentioning https://fetch.spec.whatwg.org/#forbidden-response-header-name.  and other response headers are stored.

So below will works here.
> So a Response stored in a Cache won't contain `set-cookie` headers

But I'm agree @sideshowbarker to delete this section.

**Comment by mnot** [comment]
This is the service worker cache, not the HTTP cache, so I have no idea...

**Comment by sideshowbarker** [comment]
OK, sorry I had neglected to notice that the page this is in is about `Cache` objects, not the HTTP cache.

Anyway, I’ve now opened #13432 with a clarifying fix.
