### ISSUE TITLE
Issue with "Quirks Mode and Standards Mode": (short summary here please)

### ISSUE THREAD

**Issue by RhozaKuja** [mdn/content#13332]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/quirks_mode_and_standards_mode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/quirks_mode_and_standards_mode/index.md
* Last commit: https://github.com/mdn/content/commit/09bc26fb8264fff6396e75b45481187866cb9493
* Document last modified: 2022-01-20T18:54:53.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

Unfortunately, you didn't provide any information about the issue you are reporting. We cannot act on it.

I'm closing it. If you return and provide more information, you are welcome to re-open it (or fill a separate issue).

Thanks a lot for your interest!
