### ISSUE TITLE
Issue with "BiquadFilterNode.frequency": listed as k-rate but spec and top-level page say a-rate

### ISSUE THREAD

**Issue by nuchi** [mdn/content#1333]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/BiquadFilterNode/frequency

#### What information was incorrect, unhelpful, or incomplete?
The first sentence indicates that frequency is a `k-rate` AudioParam. The page for `BiquadFilterNode` indicates that frequency is an `a-rate` AudioParam.

> The frequency property of the BiquadFilterNode interface Is a k-rate AudioParam, a double representing a frequency in the current filtering algorithm measured in hertz (Hz).

#### Specific section or headline?
First sentence.

#### What did you expect to see?
That frequency is an a-rate AudioParam. This agrees with [the spec](https://webaudio.github.io/web-audio-api/#biquadfilternode).

#### Did you test this? If so, how?
I don't know what Firefox's implementation is but I would hope that it agrees with the spec and with the top-level BiquadFilterNode page rather than the BiquadFilterNode.frequency page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/biquadfilternode/frequency`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/BiquadFilterNode/frequency
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/biquadfilternode/frequency/index.html
* Report started: 2021-01-15T00:09:53.293Z

</details>

**Comment by chrisdavidmills** [comment]
@nuchi thank you for reporting this. I've fixed it via https://github.com/mdn/content/commit/c9aa9e18b732f867d306f6d816b3dbe0c1fc625d
