### ISSUE TITLE
Issue with "A simple RTCDataChannel sample": a link is broken

### ISSUE THREAD

**Issue by AhmetHakanKapsiz** [mdn/content#13336]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Simple_RTCDataChannel_sample

#### What information was incorrect, unhelpful, or incomplete?
The Try Out This Example link in Next Steps header is broken

#### Specific section or headline?
the first link in Next Steps

#### What did you expect to see?
I expect the link works

#### Did you test this? If so, how?
Yes, by clicking the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webrtc_api/simple_rtcdatachannel_sample`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Simple_RTCDataChannel_sample
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webrtc_api/simple_rtcdatachannel_sample/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. We’re aware of the general issue, and tracking discussion about it in #5772, so I’m going ahead and closing this.
