### ISSUE TITLE
Issue with "Animation: cancel event": (short summary here please)

### ISSUE THREAD

**Issue by poslfit** [mdn/content#13346]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Animation/cancel_event

#### What information was incorrect, unhelpful, or incomplete?

The word 'finish' here should be changed to 'cancel': 

[Animation](https://developer.mozilla.org/en-US/docs/Web/API/Animation): cancel event
The finish event of the Animation interface is fired when the [Animation.cancel()](https://developer.mozilla.org/en-US/docs/Web/API/Animation/cancel) method is called

#### Specific section or headline?

Animation: cancel event (introductory paragraph)

#### What did you expect to see?

The cancel event of the Animation interface is fired...

#### Did you test this? If so, how?

Yes. I cancelled an animation, with finish and cancel event listeners, in current Google Chrome for MacOS. A cancel event was observed, but no finish.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/animation/cancel_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Animation/cancel_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/animation/cancel_event/index.md
* Last commit: https://github.com/mdn/content/commit/3ad5bb485dd4e15fde32e345f5b7cad9adff6f6b
* Document last modified: 2022-02-16T19:17:45.000Z

</details>

**Comment by hamishwillee** [comment]
Absolutely. Thanks very much. Should be fixed by #13351
