### ISSUE TITLE
Issue with "MIME types (IANA media types)": favouring text/javascript vs application/javascript

### ISSUE THREAD

**Issue by Vaent** [mdn/content#13341]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

#### What information was incorrect, unhelpful, or incomplete?

"Per the HTML specification, JavaScript files should always be served using the MIME type `text/javascript`."

"Note: Even though any given user agent may support any or all of these, you should only use text/javascript. It's the only MIME type guaranteed to work now and into the future."

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript

#### What did you expect to see?

According to https://www.iana.org/assignments/media-types/media-types.xhtml#text (which is linked further up the page) `text/javascript` is "OBSOLETED in favor of application/javascript". `text/ecmascript` is similarly obsoleted. This status is not reflected on the Mozilla page.

See also https://www.rfc-editor.org/rfc/rfc4329.html (chapters 7 & 8).

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/basics_of_http/mime_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/mime_types/index.md
* Last commit: https://github.com/mdn/content/commit/55f17d4608c3bdc3e31d0abfaba6fc61d78a0ff5
* Document last modified: 2022-01-31T23:00:43.000Z

</details>

**Comment by charles-plessy** [comment]
Note that RFC 4329 is about to be obsoleted by a new RFC that restores `text/javascript` as the default.

https://datatracker.ietf.org/doc/draft-ietf-dispatch-javascript-mjs/17/

**Comment by sideshowbarker** [comment]
I’ve opened #18351 with a change that add specification citations to the https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types article to make it crystal clear that `text/javascript` is the correct MIME type.
