### ISSUE TITLE
Issue with "Background Tasks API": minor bug in the example

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13354]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API <br><br>

#### What information was incorrect, unhelpful, or incomplete?
The [example](https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/Background_Tasks_API/_sample_.example.html) has small a bug.  In the output logs it shows `<strong>Running task #1</strong>`. <br><br>

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API#result <br><br>

#### What did you expect to see?
Initial line in logs should display **Running task #1** in bold. 

It shouldn't show the `<strong>` tag.
Either remove the strong tag, don't use  `el.textContent` to set the log text, or use `innerHTML` instead. <br><br>

#### Did you test this? If so, how?
Run the example on Chrome 98 on windows 10. <br><br>

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/background_tasks_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/background_tasks_api/index.md
* Last commit: https://github.com/mdn/content/commit/b7aafea1ab7cfee11a7e854a4b5c83a6e6d329d4
* Document last modified: 2022-02-02T09:11:35.000Z

</details>

**Comment by timeowilliams** [comment]
I'd like to be assigned this issue @sideshowbarker

**Comment by teoli2003** [comment]
Done

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/pull/13392. Thank you @timeowilliams !
