### ISSUE TITLE
Issue with "ElementInternals": syntactically wrong code example

### ISSUE THREAD

**Issue by kantoche** [mdn/content#13356]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals

The code snippet provided in the section [Examples](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals#examples) is syntactically incorrect:

```
class CustomCheckbox extends HTMLElement {

  /* ... */

  window.customElements.define("custom-checkbox", CustomCheckbox);
})();
```
It should be:

```
class CustomCheckbox extends HTMLElement {

  /* ... */

}
window.customElements.define("custom-checkbox", CustomCheckbox);

```
The same example should be fixed in https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/attachInternals.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/elementinternals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/elementinternals/index.md
* Last commit: https://github.com/mdn/content/commit/7aad7d9db1bff042e80985bd7e6bb54d96c8cb93
* Document last modified: 2022-02-27T22:06:00.000Z

</details>

**Comment by ordehi** [comment]
I'd like to take this on, please assign it to me.

**Comment by teoli2003** [comment]
The bug is yours, @ordehi.
