### ISSUE TITLE
[WebEXT] Test for id parameter in history.onTitleChanged event

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#13369]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Add test for id parameter in history.onTitleChanged event

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1756663

**Comment by rebloor** [comment]
The addition of `id` occurred in Firefox 86. The linked bug added a test, to make sure it was present, in 99.

**Comment by Rumyra** [comment]
Great thanks @rebloor - as perviously discussed I'll close this issue, but let me know if you need it open for whatever reason 👍
