### ISSUE TITLE
NOT RELEASE [WebAPI] Enable NavigationPreload on Nightly

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#13367]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Believe this is https://developer.mozilla.org/en-US/docs/Web/API/NavigationPreloadManager - so docs should be mostly complete (worth checking)

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1750515

**Comment by hamishwillee** [comment]
Status

- [ ] BCD - TBD
- [ ] Docs
  - Additional info in https://developers.google.com/web/updates/2017/02/navigation-preload
  - [ ] `NavigationPreloadManager.enable()` - no doc
  - [ ] `NavigationPreloadManager.disable()` - no doc
  - [ ] `NavigationPreloadManager.setHeaderValue()` - no doc
  - [ ] `NavigationPreloadManager.getState()` - no doc
- [ ] Experimental features
- [ ] dev-doc-complete
