### ISSUE TITLE
[WebAPI] Implement RTCPeerConnection.setConfiguration

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#13371]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Implement RTCPeerConnection.setConfiguration

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1253706

**Comment by hamishwillee** [comment]
Looks like this is properly released in v99 (no pref etc). Already documented. So it's mostly BCD, release note, and quick check of existing doc.

Status
- [ ] BCD
- [ ] Docs: [RTCPeerConnection.setConfiguration()](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setConfiguration) - review
- [ ] Release note
- [ ] Dev-doc-complete
