### ISSUE TITLE
Issue with "Examine and edit HTML": broken page-internal links

### ISSUE THREAD

**Issue by dennisgit42** [mdn/content#13397]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_HTML

#### What information was incorrect, unhelpful, or incomplete?
The links under the heading Element Context Popup Menu, starting with Edit As HTML and ending with Copy Link Address, are broken.

#### Specific section or headline?
<h2 id="element_popup_context_menu"><a href="#element_popup_context_menu" title="Permalink to Element popup context menu">Element popup context menu</a></h2>

#### What did you expect to see?
Links should scroll us down to the sections of the document with the same heading, for example, Edit As HTML link should take us to the Edit As HTML tutorial section.

#### Did you test this? If so, how?
By clicking the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/examine_and_edit_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/examine_and_edit_html/index.html
* Last commit: https://github.com/mdn/content/commit/0160aac0e623dacdce4019205f32f7b3d3e58019
* Document last modified: 2022-02-18T09:33:58.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #13399 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
