### ISSUE TITLE
Issue with "Common MIME types": on windows, ZIP files have application/x-zip-compressed for the type

### ISSUE THREAD

**Issue by Jonesie** [mdn/content#13409]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

#### What information was incorrect, unhelpful, or incomplete?
It seems like on windows, ZIP files have application/x-zip-compressed for the type. At least in Edge and Chrome.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/basics_of_http/mime_types/common_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/mime_types/common_types/index.md
* Last commit: https://github.com/mdn/content/commit/9071d9650fae08b4fccae27d8d27bf820ee13a9d
* Document last modified: 2022-01-24T11:34:39.000Z

</details>

**Comment by sideshowbarker** [comment]
> It seems like on windows, ZIP files have application/x-zip-compressed for the type. At least in Edge and Chrome.

Can you explain what leads you to that conclusion? Do you have a demo or test case that can be used to confirm it?

**Comment by sideshowbarker** [comment]
@Jonesie

> It seems like on windows, ZIP files have application/x-zip-compressed for the type. At least in Edge and Chrome.

Can you explain what leads you to that conclusion? Do you have a demo or test case that can be used to confirm it?

**Comment by sideshowbarker** [comment]
Closing for lack of response

**Comment by JonasJonny** [comment]
Still here, when you upload zip file (`req.file`) from Windows to Node application (ExpressJS).
On Mac/Linux `req.file.mimetype === 'application/zip'`. 
Windows file is uploaded as `'application/x-zip-compressed'`.

**Comment by sideshowbarker** [comment]
Without someone providing a reproducible demo case, it seems unlikely that anybody will step in to try to resolve this.

**Comment by JonasJonny** [comment]
@sideshowbarker: I think it's "Windows feature" and "no one" can do anything about it anyway.

**Comment by sideshowbarker** [comment]
> @sideshowbarker: I think it's "Windows feature" and "no one" can do anything about it anyway.

I see. Still, I guess we could add a note to the article about it, as a heads-up at least

**Comment by lianglee** [comment]
Same here it suddenly started showing application/x-zip-compressed

**Comment by JonasJonny** [comment]
> Still here, when you upload zip file (`req.file`) from Windows to Node application (ExpressJS). On Mac/Linux `req.file.mimetype === 'application/zip'`. Windows file is uploaded as `'application/x-zip-compressed'`.

I end up with
```
const mimeTypeMap = {
  'application/zip': true,
  'application/zip-compressed': true,
  'application/x-zip-compressed': true,
  'multipart/x-zip': true,
  //  'application/octet-stream': true, /* It depends on your use case. */
};
```

**Comment by davidjb** [comment]
I can verify that this is still the case, at least on Windows 10 and Server 2022 – the mimetype seen by a browser for a .zip file is `application/zip-compressed`. A quick HTML/JS demo at https://jsfiddle.net/qacgoxrw/ and dragging and dropping a file in Firefox, Edge and Chrome yields:
<img width="369" alt="mimetype result" src="https://github.com/mdn/content/assets/1002811/c6f3d6b1-3c48-4d3a-83a9-b7f0ffd8c117">

Windows is clearly not following the [IANA standard of `application/zip`](https://www.iana.org/assignments/media-types/application/zip).
