### ISSUE TITLE
Content bug: Documentation for document.adoptedStyleSheets needs to be written

### ISSUE THREAD

**Issue by Mossop** [mdn/content#13419]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Document

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/API/Document#browser_compatibility

## What is the problem?

One of the document properties, `adoptedStyleSheets` is linked to the page https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets which does not exist.

## What did you expect to see?

Either the property should be unlinked or the page it links to should exist.

## Did you test this? If so, how?

I clicked the link.

**Comment by Josh-Cena** [comment]
Fixed by #16773
