### ISSUE TITLE
Issue with "ARIA: row role": typo in `aria-expanded` role

### ISSUE THREAD

**Issue by MonstraG** [mdn/content#13412]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/row_role

#### What information was incorrect, unhelpful, or incomplete?
For value "undefined" it is named aria-exp**e**nded instead.

#### Specific section or headline?
States and properties

![image](https://user-images.githubusercontent.com/17963791/156356321-dc8710e8-26a0-4c09-af98-51a1661e8837.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/roles/row_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/row_role
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/roles/row_role/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by teoli2003** [comment]
Thanks! I just opened a PR to get this fixed.
