### ISSUE TITLE
Issue with "Performance API": Broken link

### ISSUE THREAD

**Issue by guiohm** [mdn/content#13428]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Performance_API

#### What information was incorrect, unhelpful, or incomplete?
the [perf-api-support](https://mdn.github.io/web-performance/perf-api-support.html) application link is dead

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Performance_API#implementation_status

#### What did you expect to see?
an existing page

#### Did you test this? If so, how?
clicked on it :)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/performance_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Performance_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/performance_api/index.md
* Last commit: https://github.com/mdn/content/commit/93ae23dec42bba9d71d6f1ed45668d8d26847e9c
* Document last modified: 2022-02-18T09:26:54.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #13431 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
