### ISSUE TITLE
Issue with "Element": setHTML() put in wrong place with no experimental icon

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13441]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element

#### What information was incorrect, unhelpful, or incomplete?
![screenshot](https://i.imgur.com/mGHKYyX.png)

1. The `setHTML()` is a method, but has been placed inside properties section. If you look at the left sidebar it's been placed properly there.
2. There is no experimental icon next to it. Instead the icon has been set on `Element.slot`.
3. `Element.openOrClosedShadowRoot` has not been placed as per sort order inside content.
4. `scrollIntoViewIfNeeded` has not been mentioned in main content.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Element#properties

#### Did you test this? If so, how?
open the page version Last modified: Feb 28, 2022

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/index.md
* Last commit: https://github.com/mdn/content/commit/815e2454db6b3929d0907eb981d4ded70ae38727
* Document last modified: 2022-02-27T22:00:57.000Z

</details>

**Comment by teoli2003** [comment]
Good catch. I created a PR to get this fixed.

**Comment by OnkarRuikar** [comment]
We also need to remove the experimental tag from `Element.slot`.
I think it's been tagged accidentally instead of setHTML, need to check commit history.

**Comment by teoli2003** [comment]
Oh yes. Done! Thanks.
