### ISSUE TITLE
Issue with "storage.managed": Needs additional information about the storage manifest file

### ISSUE THREAD

**Issue by iacobucci** [mdn/content#13459]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed

#### What did you expect to see?
Additional information about the storage manifest file.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/storage/managed`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/storage/managed/index.md
* Last commit: https://github.com/mdn/content/commit/629960fa07e15f2354d75daf14f149d4942539ec
* Document last modified: 2021-10-26T21:28:18.000Z

</details>

**Comment by rebloor** [comment]
Additional information, as noted on the page, is provided on the [Native manifests](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests) page.
