### ISSUE TITLE
Issue with "Using Service Workers": Remove Promises section and rewrite Service Workers Demo

### ISSUE THREAD

**Issue by jonex2** [mdn/content#13452]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

#### What information was incorrect, unhelpful, or incomplete?
The Promises section seems outdated, because it is just mentioned  for a function making a XMLHttpRequest. This is now widely done with fetch API. Because of this also the "Service Worker Demo" should use the fetch API.

#### Specific section or headline?
Promises, Service Workers Demo

#### What did you expect to see?
Remove Promises Section,  Service Workers Demo using fetch

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/service_worker_api/using_service_workers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/service_worker_api/using_service_workers/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by SphinxKnight** [comment]
@wbamberg seems it's done w/ https://github.com/mdn/content/pull/13669 ? (I'll take a closure of this one as a nice answer :) )

**Comment by jonex2** [comment]
thank you!
