### ISSUE TITLE
Issue with "Element.attachShadow()": small bug in the example

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13454]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow

#### What information was incorrect, unhelpful, or incomplete?
In the example, the `countWords(node)` function counts words wrong. For empty string it counts 1 and for string with only new line character it counts two words. 

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow#examples
and also
https://mdn.github.io/web-components-examples/word-count-web-component/

#### What did you expect to see?
1. It needs to return 0 for empty string. We can use `filter` function like this;
```
function countWords(node) {
    var text = node.innerText || node.textContent
    return text.trim().split(/\s+/g).filter(a => a.trim().length > 0).length;
}
```
2. Fix the linked live example: https://github.com/mdn/web-components-examples/tree/master/word-count-web-component
3. Also, the live example code has been [improved](https://github.com/mdn/web-components-examples/commit/690839c536e367312d88f84be129873d2cc53227). So update the code in this post accordingly.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/attachshadow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/attachshadow/index.md
* Last commit: https://github.com/mdn/content/commit/89c8199b06e7fb2b76da4087cb9eedef065b2506
* Document last modified: 2022-02-18T09:24:31.000Z

</details>

**Comment by b0nbon1** [comment]
I'd like to take this on, please assign it to me.

**Comment by sideshowbarker** [comment]
@b0nbon1 Thanks — I’ve gone ahead and set the assignment to you

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/pull/13490  - thank you @b0nbon1 !

We could still modernize the JS in those examples, but that could be a separate PR. The bug reported here is fixed.
