### ISSUE TITLE
Issue with "EventTarget.addEventListener()": example following a statement is doing apposite thing

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13450]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

#### What information was incorrect, unhelpful, or incomplete?
There is a statement 
> You can override this behavior by explicitly setting the value of `passive` to `false`, as shown here: 

This statement introduces following example:
```
/* Feature detection */
let passiveIfSupported = false;

try {
  window.addEventListener("test", null,
    Object.defineProperty(
      {},
      "passive",
      {
        get: function() { passiveIfSupported = { passive: true }; }
      }
    )
  );
} catch(err) {}

window.addEventListener('scroll', function(event) {
  /* do something */
  // can't use event.preventDefault();
}, passiveIfSupported );
```
But the example sets `passive` to `true` using `passiveIfSupported = { passive: true };`. This is exactly opposite and confusing.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#improving_scrolling_performance_with_passive_listeners

#### What did you expect to see?
I think the example is not related to the introductory sentence. The sentence is related to the paragraph above it. But the example is related to the whole improving performance section.
Detach the example from the sentence and introduce the example with new introductory sentence something like:
> To improve the performance, we can safely make event listeners passive, using following code:

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/eventtarget/addeventlistener`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/eventtarget/addeventlistener/index.md
* Last commit: https://github.com/mdn/content/commit/ac8dac6eee533d48402d7246d34882f63b682f22
* Document last modified: 2022-02-14T05:53:38.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14052 with a fix.
