### ISSUE TITLE
Content bug: Docs state that Safari doesn't support Javascript arrow functions.

### ISSUE THREAD

**Issue by somazx** [mdn/content#13468]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/JavaScript

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/JavaScript#using_modern_javascriptapi_features

## What is the problem?

This statement: "Arrow functions are supported across all modern browsers, except for IE and Safari." is not correct. Safari has supported arrow functions since Safari 10 release in 2016.

source https://caniuse.com/arrow-functions

## What did you expect to see?

Maybe, "Arrow functions are supported across all modern browsers."

## Did you test this? If so, how?

I did not test this. =)

**Comment by hamishwillee** [comment]
Thanks @somazx - this is fixed by https://github.com/mdn/content/pull/13470.

Note, you're welcome to fix this kind of thing yourself.
