### ISSUE TITLE
MediaDeviceInfo»toJSON() needs to be documented

### ISSUE THREAD

**Issue by jsmithdev** [mdn/content#13463]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo/toJSON

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo

## What is the problem?

On above MediaDeviceInfo page, I was looking what toJSON() did. I searched and found [toJSON()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo/toJSON) -- it links to page but gives page not found error

## What did you expect to see?

A page saying what toJSON() would do or saying it was deprecated which may be the case.

## Did you test this? If so, how?

Clicking thru above links to this page [toJSON()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo/toJSON)

**Comment by hamishwillee** [comment]
FYI @jsmithdev , the [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo#browser_compatibility) table at the bottom of the page is what tells you that the method is not deprecated, and the versions from which it is supported.

The broken link just tells you that the function hasn't been documented yet - sadly there are many undocumented APIs. When this is done, this page would also have a link to the new method near where the propertys are assigned.

FWIW I looking at the spec https://webidl.spec.whatwg.org/#default-tojson-steps this method does exactly what every other toJSON does - it returns you a JSON object that contains the properties of the associated javascript object.

**Comment by teoli2003** [comment]
Fixed by #25229
