### ISSUE TITLE
Issue with "Element.animate()": example from licensed code hosted at codepen; not clear if it’s used with permission

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13483]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/animate

#### What information was incorrect, unhelpful, or incomplete?
The example section has code from third party site: [Down the Rabbit Hole (with the Web Animation API)](https://codepen.io/rachelnabors/pen/rxpmJL/?editors=0010)
With: Copyright (c) 2022 by Rachel Nabors
And it has a license attached to it.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Element/animate#examples

#### What did you expect to see?
Nothing against the author or codepen.io. Even if it says free, need to check the license, to publish their work on MDN. Also, if the codepen.io goes down the link will brake.
Don't have idea about MDN policies but I think the link should be pointing to an example on mdn.github.io. Either host the example on mdn.github.io or create a completely new example without copying their work.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/animate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/animate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/animate/index.md
* Last commit: https://github.com/mdn/content/commit/89c8199b06e7fb2b76da4087cb9eedef065b2506
* Document last modified: 2022-02-18T09:24:31.000Z

</details>

**Comment by teoli2003** [comment]
Hi! We had a contract with Rachel for this work. It is published on MDN with the regular MDN license. Copying the codepen.io into a more permanent place would be a good idea though, we didn't have interactive examples and a way to host examples back then. There are likely other occurences.

cc/ @ddbeck for his record (as he wasn't here when we contracted Rachel)

**Comment by teoli2003** [comment]
cc/ing @rumyra for her information (the lawyers should have kept a copy of the signed contract, I guess; with the copyright attribution to Mozilla.).

Any objection to close this issue?

**Comment by Rumyra** [comment]
No no objection - I remember Rachel doing the work :) As I mentioned in the above linked issue #16120 we should take some time to consider what we want to replace these larger codepen examples with, before removing them 👍
