### ISSUE TITLE
“Web technology for developers” main landing page lacks links to WebExtension and WebAssembly docs, and maybe more

### ISSUE THREAD

**Issue by xuxinhang** [mdn/content#13482]
## What page(s) did you find the problem on?

[Web technology for developers](https://developer.mozilla.org/en-US/docs/Web/)

## What did you expect to see?

I expect there should be the entry links to [WebExtension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) and [WebAssembly](https://developer.mozilla.org/en-US/docs/WebAssembly) in the content page -  but they seem to have been removed from MDN.  Although I still can access to those pages via searching, I think it's not a good idea for the new-comers.

(I don't know whether there are more entry links removed and maybe further investment is needed.)

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #13491 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
