### ISSUE TITLE
Content suggestion: Don't use `.innerHTML` to insert text in examples.

### ISSUE THREAD

**Issue by TriMoon** [mdn/content#13496]
## What is the new suggestion?
Use proper DOM-API calls to add text to elements eg. instead of `x.innerHTML = y` use:
```javascript
x.appendChild(
	document.createTextNode(y)
);
```

## Why is it important or useful?
This will prevent people from creating code, by example, that could lead to XSS vulnerabilities.
It will also look more professional by doing it the "right-way" in a documentation that many use as reference.

### How many pages are likely to be needed?
Most likely **every example** that makes use of `x.innerHTML = y`

### How much time do you think this work should take? A few hours? A week? A month?
No idea because there are **a lot of examples** that need this change. :smiling_face_with_tear: 

### Will the work enable learners or professionals to achieve their goals better?
Ofcourse because they will :teacher: _learn it the **Proper** way_.
_(:eyes:  **Proper** here does not mean the old way is syntactically wrong.)_

### Does it address critical needs in the web industry?
It will surely help in avoiding common beginner's bugs w.r.t. XSS vulnerabilities. :smile_cat: 

### Is the work an operational necessity, i.e. is not having it a security risk?
That is debatable on a _per-case_ basis.

### Does the content help make the web more ethical?
Nothing can make _non-ethical beings_ become _more ethical_ per definition, so i doubt it.
Though it will help  _ethical beings_ become _more ethical_ by showing how to do _"&copy;The Right Thing&trade;"_ :wink: 

## Other supporting information
See the [Example usage of `DocumentFragment`](https://github.com/mdn/content/blob/main/files/en-us/web/api/documentfragment/index.md#javascript) which is used to teach how to programmatically create content:
- Where they use:
   ```javascript
   var list = document.querySelector('#list')
   var fruits = ['Apple', 'Orange', 'Banana', 'Melon']

   var fragment = new DocumentFragment()

   fruits.forEach(function (fruit) {
     var li = document.createElement('li')
     li.innerHTML = fruit
     fragment.appendChild(li)
   })

   list.appendChild(fragment)
   ```

- Instead of: :angel: 
   ```javascript
   const list = document.querySelector('#list');
   const fruits = ['Apple', 'Orange', 'Banana', 'Melon'];

   const fragment = new DocumentFragment();

   fruits.forEach(fruit => {
   	const li = document.createElement('li');
   	li.appendChild(
   		document.createTextNode(fruit)
   	);
   	fragment.appendChild(li);
   });

   list.appendChild(fragment);
   // It would probably be more appropriate to replace the above line with:
   list.replaceChildren(fragment);
   ```
   <blockquote>Editors notes:<ol>
   <li>Converted to <var>ES6+</var>.</li>
   <li>Indentation changed to <kbd>tab</kbd>.</li>
   <li>Replaced <code>innerHTML = </code> as described in issue.</li>
   <li>Added a comment at end.</li>
   </ol></blockquote>

**Comment by wbamberg** [comment]
We should totally do this. I only count 558 occurrences of `innerHTML`, which is honestly not as many as I was expecting :).

**Comment by sideshowbarker** [comment]
> Use proper DOM-API calls to add text to elements eg. instead of `x.innerHTML = y` use:
> 
> ```js
> x.appendChild(
> 	document.createTextNode(y)
> );
> ```

Is there a reason not to just use `innerText` instead?

**Comment by hamishwillee** [comment]
FMI Assuming it was available more widely, wouldn't [Element.setHTML()](https://developer.mozilla.org/en-US/docs/Web/API/Element/setHTML) be the right thing to recommend?

**Comment by TriMoon** [comment]
> @sideshowbarker : Is there a reason not to just use `innerText` instead?

That is in practice not any different from `innerHTML`, because it will still parse the set value as html... _(At least when i last tried)_

@hamishwillee, thanks for that link :+1: 
It is so new and experimental that i didn't know about it yet.
But as noted on that page it still needs to be turned on, on all desktop browsers, and not supported at all yet on mobiles.
But [it](https://developer.mozilla.org/en-US/docs/Web/API/Element/setHTML) looks like a :+1:nice candidate for future, if the `sanitizer` parameter would become **optional**. :wink:

**Comment by sideshowbarker** [comment]
> > @sideshowbarker : Is there a reason not to just use `innerText` instead?
> 
> That is in practice not any different from `innerHTML`, because it will still parse the set value as html and create a [DocumentFragment](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment)... _(At least when i last tried, or because of other stuff i did wrong back then)_

No, the `innerText` setter does not use the HTML parser — instead any input you give it that looks like HTML will not be parsed but instead be inserted as-is, as text:

```js
document.body.innerText = "<script>alert('foo')</script>";
document.body.childNodes;
// NodeList [ #text ]
document.body.childNodes[0];
// #text "<script>alert('foo')</script>"
```

But anyway, for our existing `innerHTML`-with-text cases, I guess there’s probably no reason to use `innerText` rather than just using `textContent`:

```js
document.body.textContent = "<script>alert('foo')</script>";
document.body.childNodes;
// NodeList [ #text ]
document.body.childNodes[0];
// #text "<script>alert('foo')</script>"
```
My point was just that given a existing case of this in our existing examples:

```js
x.innerHTML = "some text with no HTML markup";
```
…we can just drop-in replace the `innerHTML` with either `innerText` or `textContent`:
```js
x.innerText = "some text with no HTML markup";
x.textContent = "some text with no HTML markup";
```
— that is, without any needing to instead do what’s proposed in the issue description:
```js
x.appendChild(
	document.createTextNode("some text with no HTML markup")
);
```

**Comment by sideshowbarker** [comment]
> FMI Assuming it was available more widely, wouldn't [Element.setHTML()](https://developer.mozilla.org/en-US/docs/Web/API/Element/setHTML) be the right thing to recommend?

From the _”Don't use .innerHTML to insert text in examples”_ issue title, I thought this issue’s scope was limited to cases where `innerHTML` is being used to insert text into an element — not the cases where it’s being used to insert HTML content.

For inserting text rather than HTML, there’d be no reason to use `.setHTML()` rather than `innerText` or `textContent`.

**Comment by TriMoon** [comment]
@wbamberg 
> Sorry, I had misread this issue completely and thought it was about using DOM manipulation methods instead of innerHTML(). 

You were right because i started with <q>Use proper DOM-API calls to add text to elements<q/> which equals the terminology you use...

Anyhow lets push to drop the `.innerHTML` assignments and the like  :rofl:

**Comment by Josh-Cena** [comment]
I've sent 4 PRs to fix all occurrences that I personally think could be fixed. More complex `innerHTML` assignments, especially those that assign with HTML of mostly-known structures, are safe and much less readable when refactored.

**Comment by Josh-Cena** [comment]
Closing this as fixed. Will send follow-ups to fix other repos.
