### ISSUE TITLE
Bug: Output examples obscured by small scrolling region

### ISSUE THREAD

**Issue by superterrific** [mdn/content#13506]
On the `<time>` and `<cite>` pages the output examples cannot be read without scrolling. In both cases the iframe height is set at 60px. 

I did not check every HTML page but looked around enough to note that it seems to be an isolated issue. Several I looked at had no iframe height (`<em>`, `<mark>`, `<s>`, `<span>`) and others had larger fixed height (`<strong>` is set at 80px and was visible without scrolling).

## Where did you spot the bug?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite

### Device
- Desktop

### Browser
- Chrome: (v99.0.4844.51)
- Firefox: (v97.0.1)

### Operating system
- Mac OS: (10.15.7)

## Screenshots
<img width="805" alt="Example showing the result text for the HTML example is cut off and cannot be read" src="https://user-images.githubusercontent.com/34495737/156472093-52592a31-54a1-41a4-a492-0fa6cf943126.png">

**Comment by wbamberg** [comment]
OK, let's fix this in content!
