### ISSUE TITLE
Conflicting descriptions of whether Firefox respects the “autocomplete” attribute, specifically for <input type="checkbox">

### ISSUE THREAD

**Issue by bchandos** [mdn/content#13502]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

#### What information was incorrect, unhelpful, or incomplete?
Documentation states:

>Unlike other browsers, Firefox by default [persists the dynamic checked state](https://stackoverflow.com/questions/5985839/bug-with-firefox-disabled-attribute-of-input-not-resetting-when-refreshing) of an `<input>` across page loads. Use the [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete) attribute to control this feature.

However, the linked page [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete) states the following, which appears to contradict the above text (emphasis mine):

>This attribute has no effect on input types that do not return numeric or text data, **being valid for all input types except checkbox**, radio, file, or any of the button types.

#### Specific section or headline?
"Additional Attributes"

#### What did you expect to see?
Consistent description of whether or not Firefox respects `autocomplete` attribute specifically for `<input type="checkbox">`

#### Did you test this? If so, how?
While I have observed autocomplete behavior of checkboxes in Firefox that seems to confirm the second piece of documentation, the issue is really the apparent contradiction of the two pieces of linked documentation.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/checkbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/checkbox/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by Josh-Cena** [comment]
The https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete page contains this information:

> Note: The autocomplete attribute also controls whether Firefox will — unlike other browsers — [persist the dynamic disabled state and (if applicable) dynamic checkedness](https://stackoverflow.com/questions/5985839/bug-with-firefox-disabled-attribute-of-input-not-resetting-when-refreshing) of an `<input>` element, `<textarea>` element, or entire `<form>` across page loads. The persistence feature is enabled by default. Setting the value of the `autocomplete` attribute to `off` disables this feature. This works even when the `autocomplete` attribute would normally not apply by virtue of its `type`. See [Firefox bug 654072](https://bugzil.la/654072).

I think this is fine considering it's a non-standard browser thing so it doesn't have to be mentioned everywhere.
