### ISSUE TITLE
Content bug: Recommending hypens over underscores in file names

### ISSUE THREAD

**Issue by climbTheStairs** [mdn/content#13519]
## What page(s) did you find the problem on?

[Getting started with the web > Dealing with files](https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/dealing_with_files/index.md)

MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files

## Specific page section or heading?

> ## An aside on casing and spacing
> 
> [...] It's better to separate words with hyphens, rather than underscores: `my-file.html` vs. `my_file.html`.
>
> The short answer is that you should use a hyphen for your file names. The Google search engine treats a hyphen as a word separator but does not regard an underscore that way. For these reasons, it is best to get into the habit of writing your folder and file names lowercase with no spaces and with words separated by hyphens, at least until you know what you're doing. That way you'll bump into fewer problems later down the road.

## What is the problem?  What did you expect to see?

The choice between using hyphens and underscores in file names seems to be a matter of preference, as there are benefits and drawbacks to both: While hyphens are in some cases treated as a word-separator, underscores are easier to read and represent the space character.

I don't think this article should explicitly recommend against using underscores in file names, when many popular websites such as MediaWiki sites (e.g. Wikipedia, Wikia), and especially not when the article itself uses underscores in its own name.

**Comment by hamishwillee** [comment]
I tend to agree. As I understand it google search _does_ care about use of hypens vs underscores **in content** - i.e. a search for `my-file-name.jpg` might find the file, while a search for `my_file_name.jpg` might be looking for "my" and "file" and "name.jpg".

However I don't think any search engine cares about which format you use in your file structure. The only advice there that I know is reasonable is that file names should be lower case, because it is too easy to link to a file using the wrong case and have that fail on a case-sensitive file system. 

The advice about  %20 character is spurious. While that matters in URLs it is something every system understands.

@wbamberg What you think (either way this section needs a bit of improvement)?

**Comment by wbamberg** [comment]
Is one of the things here that this section conflates **URL structure** and **filename structure**, and while there are guidelines for URL structure (https://developers.google.com/search/docs/advanced/guidelines/url-structure), these don't apply for local filenames? If so, is it worth trying to explain this a bit here, as it's definitely not going to be obvious for beginners?

**Comment by hamishwillee** [comment]
Yes it is. But not by me, or at least not today. I'll leave it on my list unless someone else takes it though. Thanks!

**Comment by bshramin** [comment]
Hi, I want to contribute and solve this problem. Should someone assign this issue to me?

**Comment by teoli2003** [comment]
@bshramin The bug is yours.

**Comment by climbTheStairs** [comment]
There's a couple of possible problems still, though I haven't looked into them, & I'm not sure whether they (if they are problems) should be separate bugs:

- The article itself (& presumably all of MDN) still goes against the suggestion of using hyphens over underscores.
- The [link added in the pull request](https://github.com/mdn/content/pull/33953/files#diff-20d148e26f1e2e613d94289821a9d1732623471e231b7ffa0ee2094b576da3fdR29) does not appear in the HTML of the [website](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files#an_aside_on_casing_and_spacing).

**Comment by wbamberg** [comment]
> There's a couple of possible problems still, though I haven't looked into them, & I'm not sure whether they (if they are problems) should be separate bugs:
> 
> * The article itself (& presumably all of MDN) still goes against the suggestion of using hyphens over underscores.
> 

This would be a separate bug, filed against the MDN platform not content (https://github.com/mdn/yari/).

> * The [link added in the pull request](https://github.com/mdn/content/pull/33953/files#diff-20d148e26f1e2e613d94289821a9d1732623471e231b7ffa0ee2094b576da3fdR29) does not appear in the HTML of the [website](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files#an_aside_on_casing_and_spacing).

I'm not sure which link you are talking about. If you mean, the change in this pull request isn't visible in the site yet, that's because the site does not deploy immediately, it takes a day or so for that to happen.

**Comment by climbTheStairs** [comment]
> If you mean, the change in this pull request isn't visible in the site yet, that's because the site does not deploy immediately, it takes a day or so for that to happen.

You're right, apologies, I didn't notice that.

> > The article itself (& presumably all of MDN) still goes against the suggestion of using hyphens over underscores.
>
> This would be a separate bug, filed against the MDN platform not content (https://github.com/mdn/yari/).

I came across [this video](https://youtu.be/AQcSFsQyct8), also from Google, which was very informative: I think it would be good to note that though Google Search prefers hyphens, the difference is still rather small, & that one need not change the established URL structure of an existing site; and to perhaps add this video as an additional resource, as it did clear up quite some confusion for me.
