### ISSUE TITLE
Issue with "Array.prototype.map()": Code in demo overlaps with line numbers

### ISSUE THREAD

**Issue by Sowatee** [mdn/content#13531]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

#### What information was incorrect, unhelpful, or incomplete?

None

#### Specific section or headline?

JavaScript Demo: Array.map()

#### What did you expect to see?

Code not overlapping line number.

#### Did you test this? If so, how?

Tried adding my own code. The numbers sit on top of the syntax.

[screenshot here](https://i.imgur.com/4xVEX0n.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/map`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/map/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by sideshowbarker** [comment]
In which browser and platform are you seeing what’s shown in the https://i.imgur.com/4xVEX0n.png image?

In my macOS environment at least, I can’t reproduce it in Firefox, Chrome, or Safari.

**Comment by Sowatee** [comment]
>n which browser and platform are you seeing

On my chromebook. Using Google Chrome. Oddly enough now it's no longer doing this? I've changed nothing and deleted nothing. Perhaps it was just some random bug idk.
