### ISSUE TITLE
mouseleave is also fired when cursor enters a non-descendant that's visually overlapping

### ISSUE THREAD

**Issue by HelmZalee** [mdn/content#13534]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event

## Specific page section or heading?

Most of it, but particularly in the introduction: "...mouseleave is fired when the pointer has exited the element..."

## What is the problem?
In fact, the mouseleave event fires on an IMG if the pointer enters an AREA defined in a MAP referenced by an IMG - even if that AREA is entirely within the image.  In my mental model, an area is a part of an image; leaving it does not imply I have left the image.  (Though both Chrome and Firefox behave as if it _does_ imply leaving the image.)

## What did you expect to see?
Well, an accurate description :-).  

Perhaps a more thorough definition of "exit".  A MAP seems to present a problem specific to an IMG element.  Neither the map, nor its areas, seems to have a heirarchial relationship to the image, so it's not covered by the discussion of hierarchy.

Perhaps add somewhere "In the case of an image map, the cursor is considered to have left the image when it enters an area, **even if that area is contained entirely within the image**.  Similarly, when the cursor exits an area but remains within the image, a mouseleave event on the area will fire, and a mouseenter event on the image will also fire."

I should probably go to W3 to see if someone addressed the issue...

## Did you test this? If so, how?
Tediously.  

I attached a single mouseenter handler, and a single mouseleave handler, to every IMG and AREA on a page.  They log messages to the console.  I'll guess that anyone reading this will immediately recognize what I have not understood, and the details are not necessary.  I'm omitting them to reduce clutter, but will happily provide code and logs on request :-)

**Comment by wbamberg** [comment]
Sorry to be slow getting to this. Do you have a codepen showing this behavior?

**Comment by Josh-Cena** [comment]
This has nothing to do with imgs or areas. It's about elements that are visually overlapping but not nested in the DOM tree. Here's one simple example (you can run it in codepen or MDN playground etc)

```html
<div id="red"></div>
<div id="blue"></div>
```

```css
#red {
  width: 100px;
  height: 100px;
  position: absolute;
  background-color: red;
}

#blue {
  width: 50px;
  height: 50px;
  position: absolute;
  left: 25px;
  top: 25px;
  background-color: blue;
}
```

```js
red.onmouseleave = () => console.log("left");
```

When your mouse enters the blue box, a `mouseleave` event is fired on `red`.

**Comment by wbamberg** [comment]
And conversely, I suppose, elements that _are_ nested but not visually overlapping will trigger `mouseenter` events in the parent: -> https://codepen.io/willbamberg/pen/bGyKWWz?editors=1111 ?

Perhaps we could add something to the effect that "leaving"/"entering" refers to the element's place in the DOM tree, which is not necessarily the same as its visual position? And maybe even include this as an example?

**Comment by Josh-Cena** [comment]
Sounds good. I'm not extremely confident about what "leaving" means exactly, since theoretically, in my example, when I'm in the blue box, I'm still _in_ the red box, just in a non-visible part of it.

**Comment by wbamberg** [comment]
Well if I understand it, it means something like, entering an element that's not a descendant of this element?

>  I'm still in the red box, just in a non-visible part of it.

You're not "still in the red box" in that (DOM-positional) sense, surely? And it's not exactly visibility that matters either, in that you can give the blue box 0 opacity and you still leave the red box...

**Comment by wbamberg** [comment]
All right I had a go at this, in https://github.com/mdn/content/pull/34395.
