### ISSUE TITLE
Bug: Compatibility table anchor doesn't work

### ISSUE THREAD

**Issue by AaronDewes** [mdn/content#13546]
# Summary

On multiple pages, a link to the compatibility table is included in the docs. When clicking it, it doesn't work.

## Where did you spot the bug?

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write#browser_compatibility

## What is the problem?

The compatibility table link in this box:
![image](https://user-images.githubusercontent.com/67546953/156892191-96f56fae-27e9-4cfa-ba24-57143739a485.png)
should properly link to the compatibility table `#browser_compatibility`, but the link leads to `#browser____compatibility` (4x _)

## What did you expect to happen?

The link to take me to `#browser_compatibility`.
## Steps to reproduce the issue

1. Open https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write in any browser
2. Click on "compatibility table" in the first note.

### Device

- [x] Desktop
- [ ] Mobile: ...
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [x] Chrome: 101 Canary
- [ ] Firefox: (what version?)
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [ ] Windows: (what version?)
- [ ] Mac OS: (what version?)
- [x] Linux: Chrome OS

**Comment by caugner** [comment]
This seems to affect all articles with an [`anch` macro to "Browser compatibility"](https://github.com/mdn/content/search?q=%27anch%28%22Browser+compatibility%27) wrapped as follows ...

```
{{anch("Browser
  compatibility", "browser compatibility")}}
```

... instead of this:

```
{{anch("Browser compatibility", "browser compatibility")}}
```

**Comment by teoli2003** [comment]
We want to remove the `anch` macro. I opened a PR to fix this one; the bug will be closed when it is merged.

If you find other such broken links, feel free to report them (or open a PR). Thanks a lot.
