### ISSUE TITLE
"Feature-Policy": execution-while-not-rendered and execution-while-out-of-viewport documentation needs to be written

### ISSUE THREAD

**Issue by muratariker** [mdn/content#13556]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy

#### What information was incorrect, unhelpful, or incomplete?
[execution-while-not-rendered](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/execution-while-not-rendered) and [execution-while-out-of-viewport](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/execution-while-out-of-viewport) links are broken

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/feature-policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/feature-policy/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/22439
