### ISSUE TITLE
Issue with "Element": deprecated icon 🗑 is misplaced in `show` event's description.

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13552]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element

#### What information was incorrect, unhelpful, or incomplete?
> [show](https://developer.mozilla.org/en-US/docs/Web/API/Element/show_event)
Fired when a [contextmenu](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event) event was fired on/bubbled to an element that has a [contextmenu](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contextmenu) attribute. 🗑 Also available via the [onshow]() property.

1. The icon is put in description, it should be next to the title.
2. `securitypolicyviolation` is not as per the sort order.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Element#events

#### What did you expect to see?
> [show](https://developer.mozilla.org/en-US/docs/Web/API/Element/show_event) 🗑
Fired when a [contextmenu](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event) event was fired on/bubbled to an element that has a [contextmenu](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contextmenu) attribute.  Also available via the [onshow]() property.

Put `securitypolicyviolation` as per sort order.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/index.md
* Last commit: https://github.com/mdn/content/commit/59bd31b29f8785708e4240220620afead865754a
* Document last modified: 2022-03-03T09:24:04.000Z

</details>

**Comment by teoli2003** [comment]
Thanks. I've created a PR to fix this.
