### ISSUE TITLE
Issue with "Element": deprecated badge🗑 is misplaced in `keypress` event's description.

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13562]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element

#### What information was incorrect, unhelpful, or incomplete?
> [keypress](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event)
Fired when a key that produces a character value is pressed down.🗑Also available via the [onkeypress](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onkeypress) property.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Element#keyboard_events

#### What did you expect to see?
The icon should be next to the title.
> [keypress](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event)  🗑
Fired when a key that produces a character value is pressed down. Also available via the [onkeypress](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onkeypress) property.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/index.md
* Last commit: https://github.com/mdn/content/commit/59bd31b29f8785708e4240220620afead865754a
* Document last modified: 2022-03-03T09:24:04.000Z

</details>

**Comment by teoli2003** [comment]
Thanks. PR opened.
