### ISSUE TITLE
Site theme is very ugly, espacially color and font; i prefer the theme before

### ISSUE THREAD

**Issue by Fantilong** [mdn/content#13592]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Feedback

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/feedback`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Feedback
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/feedback/index.md
* Last commit: https://github.com/mdn/content/commit/072ff0c2bdfa29c02861450b6a91ff93f46e2218
* Document last modified: 2022-02-18T09:11:14.000Z

</details>

**Comment by sideshowbarker** [comment]
https://github.com/mdn/MDN-feedback is the repo we’re using now for discussions about the site design/theme
