### ISSUE TITLE
Issue with "Typical use cases of Flexbox": Update live example and explanation to use CSS “gap” rather than “margin”

### ISSUE THREAD

**Issue by AmarAdilovic** [mdn/content#13591]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox

#### What information was incorrect, unhelpful, or incomplete?
The third paragraph in the "Split navigation" outlines the usage of _margin_ to create a gap between items, as the _gap_ property hadn't been implemented in flexbox yet. _gap_ can now be used to achieve the same outcome as the current live example.

#### Specific section or headline?
Split navigation

#### What did you expect to see?
The following CSS has the same result as the CSS in the current Live Example:
```
nav ul {
  display: flex;
  gap: 20px;
}
.push-right {
  margin-left: auto;
}
```
#### Did you test this? If so, how?
Entering the given CSS into the live example will result in no changes to the preview showcasing the live example. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_flexible_box_layout/typical_use_cases_of_flexbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_flexible_box_layout/typical_use_cases_of_flexbox/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by estelle** [comment]
Thanks @OnkarRuikar
