### ISSUE TITLE
"Site" glossary entry says scheme and port are not relevant in determing whether something is same-site

### ISSUE THREAD

**Issue by objectiveryan** [mdn/content#13612]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Site

#### What information was incorrect, unhelpful, or incomplete?
This page says that "scheme and port are not relevant" to sites.

#### Specific section or headline?
In the Examples section.

#### What did you expect to see?
Whether scheme is considered part of the definition of site is inconsistent across different specs. It's unfortunately incorrect to say it's not relevant.

According to the HTML standard, scheme is included: https://html.spec.whatwg.org/multipage/origin.html#sites
It literally says "A site is an opaque origin or a **scheme**-and-host".

This is a problem because the MDN page directly references the Cross-Origin Resource Policy, whose page references the HTML spec.

#### Did you test this? If so, how?

No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/site`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Site
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/site/index.md
* Last commit: https://github.com/mdn/content/commit/4a9f9d2e9c1811ce3519a7061e906db9200a5e97
* Document last modified: 2021-10-08T00:24:32.000Z

</details>

**Comment by Josh-Cena** [comment]
I think https://github.com/mdn/content/pull/14356 fixes it, so closing

**Comment by hamishwillee** [comment]
Yes. This is one of those cases that was originally correct, and then at some point specs started to consider the scheme as well. The fix to the page captures that scheme might be relevent.
