### ISSUE TITLE
Issue with "aria-label": broken glossary link for “accessible name”

### ISSUE THREAD

**Issue by dylakim** [mdn/content#13625]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

#### What information was incorrect, unhelpful, or incomplete?
The "accessible name" link in the first paragraph links to a page not found.

#### Specific section or headline?
First paragraph of the page

#### What did you expect to see?
I expected the link to go to somewhere, not an error page

#### Did you test this? If so, how?
Yes. I clicked the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/attributes/aria-label`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/attributes/aria-label/index.md
* Last commit: https://github.com/mdn/content/commit/a590d73456035088e5f1cac116974488ebd867ef
* Document last modified: 2022-01-31T14:45:50.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #13632 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
