### ISSUE TITLE
Issue with "Select and highlight elements": (short summary here please)

### ISSUE THREAD

**Issue by mattsoza** [mdn/content#13635]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_and_highlight_elements

#### What information was incorrect, unhelpful, or incomplete?
Posted youtube videos are currently private.

#### Specific section or headline?
"With the context menu", "with the HTML pane", "with the node picker", all contain videos that are currently private by Mozilla.

#### What did you expect to see?
Expected videos to be available.

#### Did you test this? If so, how?
Tried to click on youtube link in bottom right of private video panel, it only redirects to youtube.com.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/select_and_highlight_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_and_highlight_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/select_and_highlight_elements/index.html
* Last commit: https://github.com/mdn/content/commit/526608c380abfb84b3b98b8419206d83e1327f54
* Document last modified: 2022-02-18T09:18:43.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks — this is a known issue that we’re already tracking over at https://github.com/mdn/content/issues/7457
