### ISSUE TITLE
Issue with "SubtleCrypto.sign()": browser compatibity not showing

### ISSUE THREAD

**Issue by ABigNwa** [mdn/content#13643]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign

#### What information was incorrect, unhelpful, or incomplete?
Browser compatibity section shows the following message:
> Unfortunately, this table has encountered unhandled error and the content cannot be shown.

#### Specific section or headline?
Browser compatibility:
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign#browser_compatibility

#### What did you expect to see?
The browser compatibility table

#### Did you test this? If so, how?
Nope

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/subtlecrypto/sign`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/subtlecrypto/sign/index.md
* Last commit: https://github.com/mdn/content/commit/08682862836d9ec5dc4e41750279f144106f6fad
* Document last modified: 2022-03-07T11:04:18.000Z

</details>

**Comment by schalkneethling** [comment]
@ABigNwa thank you for reporting. I just had a look and for me the table loads. Can you try reload the page and see if the problem presists?

**Comment by sideshowbarker** [comment]
I can reproduce this — I’m also seeing the _“Unfortunately, this table has encountered unhandled error and the content cannot be shown”_ error message in https://github.com/mdn/content/issues/13644, rather than the expected table.

I’ve run into this same error today with other pages as well — for example, https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign#browser_compatibility.

 I can’t reproduce it locally; it seems to be a problem only with the production site.

**Comment by teoli2003** [comment]
I don't see it. I wonder if there is a problem with the CDN. We got a couple of broken things today, for some but not for all.

**Comment by NiedziolkaMichal** [comment]
For me it's like that everywhere. For example in https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set()
![image](https://user-images.githubusercontent.com/100634371/157238208-09d4f7b4-76ee-4822-a31e-7eff33633a55.png)
![image](https://user-images.githubusercontent.com/100634371/157238309-8151841b-20a0-4f70-8663-bcdf87133752.png)

**Comment by ABigNwa** [comment]
I can now see the table, seems the problem has resolved itself.
Will be closing this now
