### ISSUE TITLE
Content bug: incorrect spec link for aria-description

### ISSUE THREAD

**Issue by fedorareis** [mdn/content#13668]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-description

## Specific page section or heading?

Specifications

## What is the problem?

Links to https://www.w3.org/TR/wai-aria-1.1/#aria-description instead of https://w3c.github.io/aria/#aria-description

## What did you expect to see?

I expected to be directed to the correct spec. I also would have expected something on the page to indicate that it is draft attribute

## Did you test this? If so, how?

I searched the original link for aria-description and didn't find anything. I then checked the 1.2 spec and also didn't find anything. I then stumbled across the draft spec and finally found the spec for the attribute.

**Comment by estelle** [comment]
https://github.com/mdn/content/pull/14722
