### ISSUE TITLE
Issue with "Using HTTP cookies": The term "origin" is misleading in Domain section.

### ISSUE THREAD

**Issue by sbingler** [mdn/content#1367]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

#### What information was incorrect, unhelpful, or incomplete?
"The Domain attribute specifies which hosts are allowed to receive the cookie. If unspecified, it defaults to the same origin that set the cookie".

This is misleading as the value will default to the same host not origin.

#### Specific section or headline?
"Domain"

#### What did you expect to see?
"host"

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cookies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/cookies/index.html
* Report started: 2021-01-15T20:46:45.471Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting @sbingler ; I believe this is the fix you wanted: https://github.com/mdn/content/commit/841360c0677f1df15fcd893eee2f9a0fdfb09a72

I'll close this now, but feel free to comment further if I've misunderstood you.
