### ISSUE TITLE
Issue with "Responsive design": Note that plain HTML also has fundamental responsive qualities

### ISSUE THREAD

**Issue by iDave2** [mdn/content#13673]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design

#### What information was incorrect, unhelpful, or incomplete?

Dear MDN, a quick suggestion before I forget.

This might be a low-priority RFE for your technical writers.

The "Responsive design" page in your CSS tutorial includes interesting history but I felt it lacked the obvious: HTML itself is remarkably responsive. Maybe folks take it for granted today but I remember back in the 80's and 90's -- having spent many hours learning to typeset beautiful Printed pages with Donald Knuth's (complex!) TeX language -- then when I resized the computer window how the HTML all just shuffled itself automatically to fill the space rather nicely. Knuth was worried about automating away typesetting professionals and HTML seemed -- in a sense -- to threaten Knuth's tour de force.

If I throw a big "lorem ipsum" file onto iCloud containing only vanilla HTML -- headers and paragraphs -- it is perfectly readable from the desktop, from the iPhone, from the iPhone tilted into landscape mode -- plain HTML has effectively reformatted that example three times without me lifting a finger and that's pretty neat.

On this view, "liquid" is a good thing and anyone with a 1-inch wide screen needs new hardware, not more CSS.

Or something like that. ;)

2c,
Dave

#### Specific section or headline?

see above

#### What did you expect to see?

see above

#### Did you test this? If so, how?

and thx again for the excellent tutorials!

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/css_layout/responsive_design`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/responsive_design/index.md
* Last commit: https://github.com/mdn/content/commit/7e329de8a1ec173df42c8eab9448f93c3e6c7cfa
* Document last modified: 2022-02-02T01:34:30.000Z

</details>

**Comment by wbamberg** [comment]
I have had a go at addressing this in https://github.com/mdn/content/pull/14944.
