### ISSUE TITLE
Content bug: Section headings do not follow the usual naming scheme

### ISSUE THREAD

**Issue by glmvc** [mdn/content#13671]
## Specific page section or heading?

Like described in the PR #13665 , the section heading naming scheme in the module articles usually follow like this:
1. article / page specific section(s)
2. Interactive Exercises/"Test your skills!" sections (optional)
3. "Summary" section
4. "See also" Section (Optional)
5. "In this module" section

Like in this module page for example: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started

## What is the problem?

But, in the [CSS first steps](https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps) and [CSS building blocks](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks) modules, the naming scheme is different.

Instead of "summary": "What's next", "Wrapping up", "Next steps", "In the next article", "Moving on" or "And finally" is used.

## What did you expect to see?

In the other modules, however, "Summary" is always used in a nicely consistent manner.

My question now is if this is even intentional for these two modules so that it feels "steady" when reading trough this 2 modules (when reading trough I had the feeling that the articles are written somehow continuous)?
Or can I rename the titles of this summary section headings and if content wise it doesn't fit as a summary rewrite it a bit?

## Did you test this? If so, how?

I checked all the other articles in the modules of the HTML and CSS learning guides and they alway used "Summary".

**Comment by wbamberg** [comment]
Sorry to be slow responding to this @glmvc .

I think it would be good for the CSS modules to be consistent, and change them to use "Summary", and tweak the content as needed so it makes sense with that structure.

In fact some of the CSS articles do follow that structure, right? Like https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#summary .
