### ISSUE TITLE
Issue with "Array.prototype.sort()": firstEl and secondEl are inverted

### ISSUE THREAD

**Issue by slk333** [mdn/content#13680]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

#### What information was incorrect, unhelpful, or incomplete?
`sort((firstEl, secondEl) => { /* ... */ } )`
The argument names are conceptually incorrect. They should be inverted or changed (see below)

#### Specific section or headline?
Syntax section

#### What did you expect to see?
I expect the argument names to match the implementation
`sort((secondEl, firstEl) => { /* ... */ } )`
or 
`sort((nextEl, previousEl) => { /* ... */ } )`

#### Did you test this? If so, how?
I log `a` and `b` while sorting. It shows that the first argument of the compare function IS NOT the first element of the array. It is INSTEAD the second one, or more generally the next one.
```js
const array = [1, 2, 3]

function log(a, b) {
  console.log({ a })
  console.log({ b })
  return a - b
}
array.sort(log)
/*
{ a: 2 } // a is NOT the first element!
{ b: 1 }
{ a: 3 }
{ b: 2 }
[ 1, 2, 3 ]
*/
```
Tested on nodeJS and Chrome console.
I noticed that Firefox gives the opposite result

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/sort`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/sort/index.md
* Last commit: https://github.com/mdn/content/commit/da3fa79beeee9d9196160d23f0ce793ec6d2311a
* Document last modified: 2022-03-08T07:08:38.000Z

</details>

**Comment by NiedziolkaMichal** [comment]
Code which you have attached, gives different result than what you have written:
```
{ a: 1 }
{ b: 2 }
{ a: 2 }
{ b: 3 }
```

Try this code, you will see it more clearly:
```
let x = [1,2,3,4,5,6];
x.sort((a, b) => {
    console.log(a, b);
    return a > b
});
```

Parameter names firstEl or secondEl both don't match specification though. Recommended names are a & b. I will make Pull Request about it.

**Comment by slk333** [comment]
> Code which you have attached, gives different result than what you have written:
> 
> ```
> { a: 1 }
> { b: 2 }
> { a: 2 }
> { b: 3 }
> ```
> 
> Try this code, you will see it more clearly:
> 
> ```
> let x = [1,2,3,4,5,6];
> x.sort((a, b) => {
>     console.log(a, b);
>     return a > b
> });
> ```
> 
> Parameter names firstEl or secondEl both don't match specification though. Recommended names are a & b. I will make Pull Request about it.

Please note that I tested my code on NodeJS and Chrome. You probably tested your code with Firefox, which gives the result you produced, that is indeed different from Chrome and Node (V8)

**Comment by slk333** [comment]
I've made a bit of research and I found that the internals of `sort` is [implementation dependant](https://stackoverflow.com/questions/64396555/sorting-compare-in-chrome-vs-firefox) and the implementation from firefox to chrome is indeed different.
So @NiedziolkaMichal si right to replace the argument names with a and b.

We should probably mention that the implementation difference can lead to unexpected result, such as the confusion that arised from this issue

**Comment by NiedziolkaMichal** [comment]
That's interesting. On Safari, IE, Chromium - a is second element, while on firefox a is first.

**Comment by NiedziolkaMichal** [comment]
I will add note about it, thank you

**Comment by slk333** [comment]
fixed by https://github.com/mdn/content/pull/13699
thanks
