### ISSUE TITLE
Issue with "NodeFilter": wrong argument used in the example

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13683]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/NodeFilter
and
https://developer.mozilla.org/en-US/docs/Web/API/NodeFilter/acceptNode
and
https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker/lastChild

#### What information was incorrect, unhelpful, or incomplete?
The method [document.createNodeIterator](https://developer.mozilla.org/en-US/docs/Web/API/Document/createNodeIterator#syntax) has only 3 parameters defined in [the standard](https://dom.spec.whatwg.org/#interface-document). The example passes fourth argument `false` to the method which is not correct.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/NodeFilter#example
and
https://developer.mozilla.org/en-US/docs/Web/API/NodeFilter/acceptNode#example
and
https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker/lastChild#example

#### What did you expect to see?
Remove the last redundant argument `false`. Check all the pages related to the APIs for same issue.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/nodefilter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/NodeFilter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/nodefilter/index.md
* Last commit: https://github.com/mdn/content/commit/93ae23dec42bba9d71d6f1ed45668d8d26847e9c
* Document last modified: 2022-02-18T09:26:54.000Z

</details>

**Comment by danburzo** [comment]
The fourth argument was called [`expandEntityReferences`](https://developer.mozilla.org/en-US/docs/Web/API/NodeIterator/expandEntityReferences) and, as the page suggest, was removed from the standard and phased out by evergreen browsers. Relatedly, TreeWalker should probably get a consistent treatment, as it currently shows the fourth argument as deprecated: https://developer.mozilla.org/en-US/docs/Web/API/Document/createTreeWalker

**Comment by OnkarRuikar** [comment]
@danburzo thanks for the info! 

It was removed in Firefox v21:
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/21#dom
