### ISSUE TITLE
Issue with "FinalizationRegistry.prototype.register()": possible values for `heldValue` aren't mentioned

### ISSUE THREAD

**Issue by danieltroger** [mdn/content#13695]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/register

#### What information was incorrect, unhelpful, or incomplete?

I thought I can only have a string as `heldValue` but apparently it can be any object. I'd appreciate some emphasis on that as `The value` is a bit ambiguous.

#### Specific section or headline?

> heldValue
>  The value to pass to the finalizer for this object. This cannot be the target object.

#### What did you expect to see?

> heldValue
>  The value to pass to the finalizer for this object. This cannot be the target object but any other object (including functions) or primitive value.

#### Did you test this? If so, how?
Using the tests at https://www.javascripture.com/FinalizationRegistry, changing the `42` to `new WeakRef({})` still printed

```
Allocating a lot of objects to try to force garbage collection
cleanup: [object WeakRef]
```
but not sure if it also allows functions, I made that up.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/finalizationregistry/register`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/register
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/finalizationregistry/register/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by timeowilliams** [comment]
Requesting assignment
