### ISSUE TITLE
Issue with "Array.prototype.flatMap()": (short summary here please)

### ISSUE THREAD

**Issue by klequis** [mdn/content#13696]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

#### What information was incorrect, unhelpful, or incomplete?

Not sure if this is incorrect but seems to me it either is, there is something I missed, or an explanation should be added.

In the "Parameters" section, the `array` parameter it says "The array `map` was called upon." Should it say `flatMap` instead of `map`?

The article is about `flatMap`. Although `map` is mentioned there is no indication that `map` is called under the covers or other relation between `flatMap` & `map`.

#### Specific section or headline?

"Parameters" section, the `array` parameter

#### What did you expect to see?

I expected to see the word `flatMap` but instead see `map`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/flatmap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/flatmap/index.md
* Last commit: https://github.com/mdn/content/commit/88508ebe5c73264be2cf03f1a949d8099d68d1ea
* Document last modified: 2022-02-04T02:05:25.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing, @klequis ! You are right, and it's fixed by @NiedziolkaMichal in https://github.com/mdn/content/pull/13700 .
