### ISSUE TITLE
Issue with "Asynchronous JavaScript": (Cooperative asynchronous Java​Script: Timeouts and intervals) section

### ISSUE THREAD

**Issue by alaa-yahia** [mdn/content#13706]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Timeouts_and_intervals

#### What information was incorrect, unhelpful, or incomplete?
I can't go to the section titled `Cooperative asynchronous Java​Script: Timeouts and intervals` in the guide

#### Specific section or headline?
specific section

#### What did you expect to see?
A section titled `Cooperative asynchronous JavaScript: Timeouts and intervals`

#### Did you test this? If so, how?
By going to the specific link [Cooperative asynchronous JavaScript: Timeouts and intervals](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Timeouts_and_intervals) 
It redirect to this [page](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous) 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/index.md
* Last commit: https://github.com/mdn/content/commit/7cf00aff32962e6135132531d699f4d21667f376
* Document last modified: 2022-03-07T18:01:36.000Z

</details>

**Comment by alaa-yahia** [comment]
> May I ask where you found this link? We removed this page as part of a general rewrite of the async module.

I've found the title in the guide
![IMG_20220309_212050](https://user-images.githubusercontent.com/6881345/157516045-51c40cf5-5dd7-4864-951e-dd93ad3cf20e.jpg)

The link I got it from the cache when I searched the title

**Comment by wbamberg** [comment]
Thank you for reporting this! Looks like I forgot to update the sidebar...

**Comment by wbamberg** [comment]
I've filed https://github.com/mdn/yari/pull/5556 to fix this.

**Comment by alaa-yahia** [comment]
Thank you..
I see the change haven't taken effect yet although the branch is merged..is there another step that should take place ?

**Comment by teoli2003** [comment]
The production Web site is usually built once a day; read this [section](https://github.com/mdn/content#when-will-my-change-show-up-on-the-production-mdn-site) for more information.

**Comment by wbamberg** [comment]
I'm now seeing the new sidebar on pages in production 👍 .

**Comment by alaa-yahia** [comment]
Thank you @wbamberg !
I have noticed [Asynchronous JavaScript overview](http://localhost:3000/en-US/docs/Learn/JavaScript/Asynchronous) page became inaccessible from the sidebar so I made this [pull request](https://github.com/mdn/yari/pull/5586) to solve the issue
