### ISSUE TITLE
Issue with "X-Forwarded-For": insufficient mention of risks

### ISSUE THREAD

**Issue by adam-p** [mdn/content#13703]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

#### What information was incorrect, unhelpful, or incomplete?

The description of `X-Forwarded-For` doesn't mention that the any values except those added by your own (reverse) proxies are spoofable and should not be used for anything security-related. While it's true for any header that they can be spoofed, XFF is somewhat special because it can be appended to by a trusted proxy, making it a mix of trusted and untrusted. (It's also, probably, one of the only unverifiable headers that _needs_ to be used for security purposes, since there's often no other way of getting the client IP, for use with rate-limiting, etc.)

Note that everything said here about XFF applies equally to the [`Forwarded`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) header.

See the warnings about XFF in these sources, which are completely absent from the MDN entry:
* https://en.wikipedia.org/wiki/X-Forwarded-For
* https://totaluptime.com/kb/prevent-x-forwarded-for-spoofing-or-manipulation/
* https://docs.fastly.com/signalsciences/faq/real-client-ip-addresses/#x-forwarded-for-header-configuration
* https://datatracker.ietf.org/doc/html/rfc7239#section-8.1

Because MDN is the first source most people go to for information like this, it can -- and probably does -- lead to developers erroneously using the leftmost IP in the XFF list -- MDN says it's the "client" IP, and that's what they want. But the leftmost value is the least trustworthy.

I wrote a blog post (https://adam-p.ca/blog/2022/03/x-forwarded-for/) examining XFF use and abuse and found that it was widely misused, often with significant security implications.

#### What did you expect to see?

More information about how it should and shouldn't be used. Which values are more and less trustable, and why. Warnings, caveats, etc.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/x-forwarded-for`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/x-forwarded-for/index.md
* Last commit: https://github.com/mdn/content/commit/46234997b6257b619423a11ce31154afa336143f
* Document last modified: 2021-08-13T16:17:49.000Z

</details>

**Comment by hamishwillee** [comment]
@adam-p Thanks! Any chance then that you could update the document to fix the flaws?

**Comment by adam-p** [comment]
@hamishwillee See PR #13838.

**Comment by hamishwillee** [comment]
Thanks very much @adam-p - much appreicated. I'm not expert enough to judge the correctness of the material, but mnot is. I've pinged sideshowbarker to find out what is blocking merge.
