### ISSUE TITLE
Issue with "<section>: The Generic Section element": …

### ISSUE THREAD

**Issue by eeriksp** [mdn/content#1370]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

#### What information was incorrect, unhelpful, or incomplete?

The interactive example.

#### Specific section or headline?

The interactive example, which has the title "How to Fish".

#### What did you expect to see?

The given example is good from a technical perspective.
However, its content is causing tension as many people consider killing other living beings, including fish, morally problematic. Regardless of your own stand in this matter, it is hard to deny that many people who use this website have a strong ethical opinion about this and consider it to be promoting violence.

Therefore I suggest to update the content so that it would focus on same ethically positive or neutral theme. For instance "Origins of Coffee" or "Differential equations in a nutshell" or "Best of Monty Python" or "Plato's Allegory of the Cave" or "Species of Bears", the choices are endless.

#### Did you test this? If so, how?

I would be happy to contribute in updating the example, but I was unable to find its location in the repository as it is referenced using `<div>{{EmbedInteractiveExample("pages/tabbed/section.html", "tabbed-standard")}}</div>` and I could not locate the `pages/tabbed/section.html` file.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/section`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/html/element/section/index.html
* Report started: 2021-01-15T21:49:16.264Z

</details>

**Comment by chrisdavidmills** [comment]
@eeriksp I entirely agree with you, thanks for bringing this up. 

I've raised a PR to fix this — https://github.com/mdn/interactive-examples/pull/1755. Let me know what you think.

**Comment by eeriksp** [comment]
@chrisdavidmills Thank you very much! This is really good. :tada:
