### ISSUE TITLE
Issue with "SerialPort.getInfo()": does not return a promise

### ISSUE THREAD

**Issue by Abdull** [mdn/content#13709]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SerialPort/getInfo

#### What information was incorrect, unhelpful, or incomplete?
The documentation currently states "_The [SerialPort](https://developer.mozilla.org/en-US/docs/Web/API/SerialPort).getInfo() method of the SerialPort interface returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that resolves with an object containing properties of the port._"

But actually, [according to specification](https://wicg.github.io/serial/#ref-for-dom-serialport-getinfo-2), `getInfo()` does not return a promise, but directly the [`SerialPortInfo` dictionary](https://wicg.github.io/serial/#dom-serialportinfo).

Tested on `Chrome Version 99.0.4844.51`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/serialport/getinfo`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SerialPort/getInfo
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/serialport/getinfo/index.md
* Last commit: https://github.com/mdn/content/commit/a590d73456035088e5f1cac116974488ebd867ef
* Document last modified: 2022-01-31T14:45:50.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14051 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

**Comment by Abdull** [comment]
Thanks for handling this issue. Taking a look at https://github.com/mdn/content/pull/14051 / https://pr14051.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/SerialPort/getInfo , I notice that the variable name still is `promise`:

```
var promise = SerialPort.getInfo();
```

This is confusing.

**Comment by teoli2003** [comment]
Yes, I've opened a follow-up. We don't put variable names in syntax descriptions anymore. Updating it removes the confusion at the same time.
