### ISSUE TITLE
Jump to section => Table of contents

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#1371]
Let's not worry about making the change. But please feel free to start a discussion about changing the English. I don't think we should just jump into an edit without consent from the content folks. 

_Originally posted by @peterbe in https://github.com/mdn/yari/pull/2471#issuecomment-761230292_

🤜🤛

**Comment by hamishwillee** [comment]
I don't understand **where** this will appear. Is it possible to show the rendered before and after of this proposed change?

**Comment by mattiapontonio** [comment]
Here
![Screenshot_20210118-013814.png](https://user-images.githubusercontent.com/44380480/104860924-dc56ab80-592d-11eb-8aa1-0a2908d3e953.png)

Actually I don't know how to test like modify in inspector since I'm from a smartphone (this Is because my PRs has 99 commits) 🤷🏻‍♂️

**Comment by mattiapontonio** [comment]
You can try to checkout t'ha branch of this PR
https://github.com/mdn/yari/pull/2471

And start the project locally reading the readme.

**Comment by hamishwillee** [comment]
Not need thanks @mattiapontonio - your screenshot makes sense. So the proposed change is the text - ie
![image](https://user-images.githubusercontent.com/5368500/104861058-5dd82900-5982-11eb-8260-b69ee5961772.png)

I have a very _slight_ preference for the current "Jump to section" because the word "section" implies **to me** a jump within the same document.

If this said "table of contents", then perhaps I might consider this a table of site articles.

Others might disagree. @chrisdavidmills

**Comment by hamishwillee** [comment]
PS Sorry I was slow to respond. I personally "like" the term "Table of contents" more - it was hard to find a good way to explain why objectively the current version is probably better.

**Comment by mattiapontonio** [comment]
Ah You want a section and not a dropdown. Make sense.

**Comment by mattiapontonio** [comment]
Lets try...
https://github.com/mdn/content/edit/main/files/en-us/web/javascript/reference/global_objects/proxy/index.html

**Comment by hamishwillee** [comment]
@mattiapontonio Just to be clear, I was only commenting on the text "Jump to section" vs "Table of contents".  Please don't assume I'm commenting on anything else from the screenshot :-)

That said, I do think it is important for the list of page headings (i.e. the page toc) to be readily accessible - in this case a dropdown that is open by default when you load a page. 

This sort of thing is IMO best managed by a product manager - who would define how they want all the page elements to behave.

**Comment by mattiapontonio** [comment]
Yes 👍.
I can't merge.
I'm a _volunteer_.

How do you make the list so vertical without dots?

**Comment by hamishwillee** [comment]
@mattiapontonio I cheated because my image was just to confirm your intent (screenshot of [this page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy) then changed the text, took a second screenshot and combined). 

But if I had to do this properly - something like https://www.w3schools.com/html/tryit.asp?filename=tryhtml_lists_unordered_none

**Comment by mattiapontonio** [comment]
@hamishwillee ok thanks.

**Comment by chrisdavidmills** [comment]
> Others might disagree. @chrisdavidmills

Ah, those classic bikeshed moments ;-) I don't really care that much, as I think any improvement make on this would be prety minor. But here's my 2pence:

1. "Table of contents" feels a bit too generic, like it could be referring to more than just the contents of this article.
2. "Jump to section" is more specific, but it relies on the reader knowing what section means in the context of either an article, or even a sectioning element in the markup (which we don't actually use at this level of granularity). It is not as intuitive.

Which leads me to think is there third option, maybe "Article contents"?

I dunno, doesn't feel great either. As I said, I don't think this is worth spending too much time on.

**Comment by mattiapontonio** [comment]
Should be fun to style a little light border on sections... 🙂 Just to see how it looks.

**Comment by hamishwillee** [comment]
Article contents would work for me too. 
@chrisdavidmills For me it isn't that this kind of thing isn't worth talking about - it's that we have far bigger problems with sidebars on MDN than this.

**Comment by chrisdavidmills** [comment]
> Article contents would work for me too.
> @chrisdavidmills For me it isn't that this kind of thing isn't worth talking about - it's that we have far bigger problems with sidebars on MDN than this.

Yup ;-)

**Comment by mattiapontonio** [comment]
Reopen.
P2.

**Comment by mattiapontonio** [comment]
> Article contents would work for me too. 
> @chrisdavidmills For me it isn't that this kind of thing isn't worth talking about - it's that we have far bigger problems with sidebars on MDN than this.

What issue?

**Comment by peterbe** [comment]
> Which leads me to think is there third option, maybe "Article contents"?

I like this bikeshed better than "Jump to section" (literal but a bit unusual and thus unnecessarily brain-tickling) and "Table of contents" (not something you'd expect to see in a side bar).

Another option would be to pick "On this page"

**Comment by mattiapontonio** [comment]
> expect to see in a side bar
So removing It and leave the sidebar only on the right?

**Comment by mattiapontonio** [comment]
I will close this.
Please reopen in Yari if needed.
