### ISSUE TITLE
Issue with "TreeWalker": Methods section is not being rendered properly

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13717]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker

#### What information was incorrect, unhelpful, or incomplete?
Screenshot:
![screen](https://i.imgur.com/NowiTES.png)

Here ::marker and `:` are visible. List items are not being converted to `<dl>` description list elements.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker#methods

#### What did you expect to see?
There shouldn't be any list decoration.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/treewalker`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/treewalker/index.md
* Last commit: https://github.com/mdn/content/commit/93ae23dec42bba9d71d6f1ed45668d8d26847e9c
* Document last modified: 2022-02-18T09:26:54.000Z

</details>

**Comment by teoli2003** [comment]
I opened #13719 with a fix. There was an indentation problem inside the list that broke the `<dl>` generation from Markdown.

**Comment by teoli2003** [comment]
@OnkarRuikar Thanks a lot for reporting this.
