### ISSUE TITLE
Can web-usb permissions be revoked by javascript code? If so, should be documented

### ISSUE THREAD

**Issue by GODOFZHZ** [mdn/content#13714]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/USBDevice/open

#### What information was incorrect, unhelpful, or incomplete?
![image](https://user-images.githubusercontent.com/28758664/157581809-152f011e-820a-46e1-8788-c90ee88ab1ac.png)

I only know that the authorization can be turned off by clicking this cross, but I want to revoke the authorization using javascript code?

#### Specific section or headline?
Can web-usb permissions be revoked by javascript code? 

#### What did you expect to see?
I want to revoke usb access with javascript code.   
what should I do?  

#### Did you test this? If so, how?
what should I do

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/usbdevice/open`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/USBDevice/open
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/usbdevice/open/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Josh-Cena** [comment]
Very soon after this issue, there came https://developer.mozilla.org/en-US/docs/Web/API/USBDevice/forget. I think that's sufficient to address this issue, since it's already discoverable from the API landing page.
