### ISSUE TITLE
Content bug: Suggested change/example in CSS Grid docs doesn't work

### ISSUE THREAD

**Issue by stevejalim** [mdn/content#13721]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout#use_cases_for_auto-placement

## Specific page section or heading?
**Use cases for auto-placement**

## What is the problem?

In **[Use cases for auto-placement](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout#use_cases_for_auto-placement)** there is a suggestion that the user tries the following in the live editor:

> Try removing the line `grid-auto-flow: dense` to see the content reflow to leave gaps in the layout.

However, removing that line does not make a difference to the layout. Amending other CSS rules for the wrapper does change things, though, so it's not that the update mechanism is broken, it seems that the suggested code removal no longer has the intended effect

## Did you test this? If so, how?

This can easily be replicated on the relevant page, and was tested in FF Developer Edition and Nightly

**Comment by victor0x16** [comment]
Hi @stevejalim, it seems to work as expected. You can see on [#my example on codepen](https://codepen.io/victor0x16/pen/wvPVbGo) or you can add two more Li elements  on the MDN example page to see grid-auto-flow working. 

On MDN, you can see an explaination as well.
[#Filling in the gaps](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout#filling_in_the_gaps)

I was also confused when I was reading it, maybe someone or you can improve it 🚀  !

**Comment by stevejalim** [comment]
Hi @victor0x16 - thanks for your response, but I think it still leaves my content bug report unresolved. When a learner come across the instruction to remove `grid-auto-flow: dense` from the example, they are expecting to see a change n the layout - but they don't. Here's a quick video of what am seeing: https://user-images.githubusercontent.com/101457/157848512-6a92fed5-445a-49e7-9f0e-a474c8b56a51.mov If I knew enough CSS Grid, I'd try to fix it myself, happily 😄

**Comment by Josh-Cena** [comment]
https://github.com/mdn/css-examples/pull/143
