### ISSUE TITLE
Issue with "Window.devicePixelRatio": specifications link broken

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13726]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

#### What information was incorrect, unhelpful, or incomplete?
The link to specifications: https://drafts.csswg.org/cssom-view/#dom-window-devicepixelratio
is broken.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio#specifications

#### What did you expect to see?
Working latest link.
May be this link: https://www.w3.org/TR/cssom-view-1/#dom-window-devicepixelratio

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/devicepixelratio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/devicepixelratio/index.md
* Last commit: https://github.com/mdn/content/commit/93ae23dec42bba9d71d6f1ed45668d8d26847e9c
* Document last modified: 2022-02-18T09:26:54.000Z

</details>

**Comment by AnilSeervi** [comment]
The specs link seems to be working fine for me.
Could you please verify this once again?

**Comment by teoli2003** [comment]
The link is working with me. drafts.csswg.org has intermittent problems that the w3c is aware of. I'm closing this.
