### ISSUE TITLE
Issue with "Window.personalbar": content is no longer correct

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13729]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/personalbar

#### What information was incorrect, unhelpful, or incomplete?
The Example section still has the TODO task pending: 
> FIXME: https://bugzilla.mozilla.org/show_bug.cgi?id=790023

The the object returned by the property is now read only hence the documentation is outdated.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Window/personalbar#example

#### What did you expect to see?
All these window property pages -- locationbar, personalbar,  scrollbars, statusbar, toolbar -- need to be updated like the [menubar](https://developer.mozilla.org/en-US/docs/Web/API/Window/menubar) page.

Also, update the [Window interface](https://developer.mozilla.org/en-US/docs/Web/API/Window). There it says the objects visibility can be toggled. Mention the visibility can be read. Like they've done on [menubar](https://developer.mozilla.org/en-US/docs/Web/API/Window/menubar) page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/personalbar`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/personalbar
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/personalbar/index.md
* Last commit: https://github.com/mdn/content/commit/55f17d4608c3bdc3e31d0abfaba6fc61d78a0ff5
* Document last modified: 2022-01-31T23:00:43.000Z

</details>

**Comment by timeowilliams** [comment]
Requesting assignment

**Comment by sideshowbarker** [comment]
@timeowilliams thanks — it’s all yours

**Comment by Josh-Cena** [comment]
Partially fixed by #15656; still need the `Window` interface page to be updated and preferably an example to be added on the `personalbar` page.
