### ISSUE TITLE
Issue with "DOM Inspector": …

### ISSUE THREAD

**Issue by prohunterdogkeeper** [mdn/content#1373]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Add-ons/DOM_Inspector

#### What information was incorrect, unhelpful, or incomplete?
Entire page is deprecated (and misleading). This page is still top hit when googling for the DOM Inspector, which is a deprecated tool.

#### Specific section or headline?
All of it.

#### What did you expect to see?
Either that it was deleted, or that it informed readers that the tool isn't accessible any longer.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/add-ons/dom_inspector`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Add-ons/DOM_Inspector
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/tools/add-ons/dom_inspector/index.html
* Report started: 2021-01-15T23:11:42.017Z

</details>

**Comment by chrisdavidmills** [comment]
Hi @prohunterdogkeeper !

We had the same thing reported the other day, so I just removed the page (you look at the source link you'll see it 404s — https://github.com/mdn/content/blob/main/files/en-us/tools/add-ons/dom_inspector/index.html)

The change should update in the production site in the next day or so.
