### ISSUE TITLE
Issue with "XPath": Dead tool link to XMLQuire

### ISSUE THREAD

**Issue by N-Onorato** [mdn/content#13737]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/XPath

#### What information was incorrect, unhelpful, or incomplete?
The link to XMLQuire appears to be dead. 

#### Specific section or headline?
Under the 'Tools' headline

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/xpath`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/XPath
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/xpath/index.md
* Last commit: https://github.com/mdn/content/commit/1314ac4ed0049401ce0c84fbb7103527c37d75fa
* Document last modified: 2022-01-18T02:36:46.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. I've fixed it by just removing the link - see #13745
