### ISSUE TITLE
Issue with "Introduction to events" -> "Bubbling and capturing explained": That capture is off by default is not noted.

### ISSUE THREAD

**Issue by OndeVai** [mdn/content#13749]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#bubbling_and_capturing_explained

#### What information was incorrect, unhelpful, or incomplete?
You mention that the browser executes the 3 phases (capture, target and bubble). However, the first phase is optional and off by default. The description does not specify the optionality of capture. 

#### Specific section or headline?
Bubbling and capturing explained

#### What did you expect to see?
Well, I wasn't sure, until I went to some other sources :)

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/events/index.md
* Last commit: https://github.com/mdn/content/commit/0160aac0e623dacdce4019205f32f7b3d3e58019
* Document last modified: 2022-02-18T09:33:58.000Z

</details>

**Comment by timeowilliams** [comment]
Requesting assignment
