### ISSUE TITLE
Django rest framework serializer error ({'required': 'This field is required.', 'null': 'This field may not be null.', 'invalid': 'Invalid data. Expected a dictionary, but got {datatype}.'})

### ISSUE THREAD

**Issue by ShubhaPradhan** [mdn/content#13746]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status/400`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/400/index.md
* Last commit: https://github.com/mdn/content/commit/b738fbd10a45cbc8fbf30772c53be5c8ab4b377d
* Document last modified: 2021-11-25T19:12:02.000Z

</details>

**Comment by hamishwillee** [comment]
Closing, because it is not clear what issue you are reporting. 

The document https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400 is correct.
