### ISSUE TITLE
Issue with "XMLHttpRequest.withCredentials": There is a typo.

### ISSUE THREAD

**Issue by sasky621** [mdn/content#13744]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

#### What information was incorrect, unhelpful, or incomplete?
XMLHttpRequest from a different domain cannot set cookie values for their own domain unless withCredentials is set to true before making the request

#### What did you expect to see?
Just add the word "responses" after the word "XMLHttpRequest", so the previous text would be as following:

XMLHttpRequest responses from a different domain cannot set cookie values for their own domain unless withCredentials is set to true before making the request

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/xmlhttprequest/withcredentials`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/xmlhttprequest/withcredentials/index.md
* Last commit: https://github.com/mdn/content/commit/93ae23dec42bba9d71d6f1ed45668d8d26847e9c
* Document last modified: 2022-02-18T09:26:54.000Z

</details>

**Comment by Explosion-Scratch** [comment]
![image](https://user-images.githubusercontent.com/61319150/157783804-2257604f-3f7a-417b-b480-e630a2b57f39.png)
Looks fine to me!

**Comment by sasky621** [comment]
Yes this is fine, but the typo above that text.
![image](https://user-images.githubusercontent.com/71954861/157785010-c6c1340f-590b-4eee-b2fb-ef6f255ddde7.png)

**Comment by deepug9787** [comment]
Hi, I'd like to work on this issue.

**Comment by teoli2003** [comment]
@deepug9787  The issue is yours.

**Comment by Explosion-Scratch** [comment]
> @deepug9787 The issue is yours.

![image](https://user-images.githubusercontent.com/61319150/157872253-7cabaf4b-8be9-42fe-93cf-375f53f36bed.png)
lol
