### ISSUE TITLE
Django rest framework serailizers errror

### ISSUE THREAD

**Issue by ShubhaPradhan** [mdn/content#13747]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

Here, i have my Assignment Model:
def upload_to(instance, filename):
    return 'assignments/{filename}'.format(filename=filename)

class Assignment(models.Model)--model.py
    # BOTH CHOICES WILL EVENTUALLY COME FROM ADMIN
    # SUBJECTS
    Statistics = 'statistics'
    Numerical_Method = 'numerical method'
    subject_choices = [
        (Statistics,'statistics'),
        (Numerical_Method,'numerical method'), 
    ]
    # ASSIGNMENT TYPE
    Assignment = 'assignment'
    Lab = 'lab'
    assignment_choices = [
        (Assignment,'assignment'),
        (Lab,'lab'), 
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='assignments', blank=True, null=True)
    username = models.CharField(max_length=255, blank=True, null=True)
    title = models.CharField(max_length=20, blank=False, null=False)
    subject = models.CharField(max_length=20, choices=subject_choices, default=Statistics, blank=False)
    assignment_type = models.CharField(max_length=20, choices=assignment_choices, default=Assignment, blank=False)
    assignment_file = models.ImageField(_("Image"),upload_to=upload_to,default="", blank=False)
    description = models.CharField(max_length=50, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    
View.py

class CreateAssignmentView(APIView):
    parser_classes = [MultiPartParser, FormParser]
    serializer_class = AssignmentSerializer
    def post(self, request, format=None):
        assignment = request.data
        print(assignment)
        serializer = self.serializer_class(data = assignment)
        print(serializer)
        print(serializer.error_messages)
        if serializer.is_valid():
            print("valid")
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        
        return Response({'Bad Request': 'Invalid data...'}, status=status.HTTP_400_BAD_REQUEST)

serializers.py:

class AssignmentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Assignment
        fields = ('user', 'username','title', 'subject', 'assignment_type', 'assignment_file', 'description')

ERROR that is being generated:
{'required': 'This field is required.', 'null': 'This field may not be null.', 'invalid': 'Invalid data. Expected a dictionary, but got {datatype}.'}
Bad Request: /api/create-assignments/

React Function for Creating assignments:
  const createAssignment = (e) => {
    e.preventDefault();
    let formData = new FormData();
    console.log()
    const data = {
      user : user.user_id,
      username : user.full_name,
      title : assignmentTitle,
      subject : assignmentSubject,
      assignment_type : assignmentType,
      assignment_file : assignmentFile[0].name + " " + "(" + assignmentFile[0].type + ")",
      description : assignmentdescription,
    }
    formData.append("data", JSON.stringify(data));
    console.log(formData.get("data"));
    const requestOptions = {
      mode: 'no-cors',
      method: "POST",
      body: formData,
    };
    fetch("/api/create-assignments/", requestOptions)
      .then((response) => {
        if (response.ok) {
          return response.json();
        } else {
          setMessage("All fields are required");
          setIsError(true);
        }
      })
      .then((data) => {
        setMessage("Assignment created successfully");
        setIsSuccess(true);
      });
  };

![error](https://user-images.githubusercontent.com/63387565/157789058-39783bd1-8990-4bf8-9597-b3fb93cc2f69.png)

**Comment by hamishwillee** [comment]
Thanks. So you have posted that there is a problem with https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400 and then a whole bunch of text that has nothing to do with that page.

Is the text you have posted something to do with MDN? 

If this is some project of yours that just happens to return HTTP400 then it isn't a problem we can help you with here. This area is for errors in the documentation.
