### ISSUE TITLE
Issue with "Commonly-used macros": …

### ISSUE THREAD

**Issue by jchimene** [mdn/content#1374]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Structures/Macros/Commonly-used_macros

#### What information was incorrect, unhelpful, or incomplete?
At https://developer.mozilla.org/en-US/docs/MDN/Structures/Macros/Commonly-used_macros#linking_to_pages_in_references, the link to domxref() is dead. This may be a known issue.

#### Specific section or headline?
linking_to_pages_in_references

#### What did you expect to see?
More information about the domxref macro

#### Did you test this? If so, how?
Clicked the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/structures/macros/commonly-used_macros`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Structures/Macros/Commonly-used_macros
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/structures/macros/commonly-used_macros/index.html
* Report started: 2021-01-16T00:51:05.161Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @jchimene !

I used a regex to fix all the macro links a little while ago, but the casing is weird on this one, hence the link was not working.

I've fixed it in https://github.com/mdn/content/commit/b944e251145b3b24e2970d757965adca20532a30
