### ISSUE TITLE
Issue with "Date.now()": …

### ISSUE THREAD

**Issue by 4172580636** [mdn/content#1375]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/now`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/date/now/index.html
* Report started: 2021-01-16T01:05:57.037Z

</details>

**Comment by 4172580636** [comment]
The information that states app is Netscape on the information after can I somehow get the shots to show people who are knowledgeable about what it’s possible that could be wrong!?? Is there a way screen shot that is optional on the feedback is not from the web page and web inspector has Java on but I don’t know if google uses it and how can I get it to work with

**Comment by 4172580636** [comment]
Not null

**Comment by chrisdavidmills** [comment]
None of these comments seem to make sense, or have relevance to the page referenced, therefore this sounds like spam to me. Closing.
