### ISSUE TITLE
Issue with "Math.atan2()": Need to wrap in parenthesis 

### ISSUE THREAD

**Issue by zileeva** [mdn/content#13767]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2

#### What information was incorrect, unhelpful, or incomplete?
```
function calcAngleDegrees(x, y) {
  return Math.atan2(y, x) * 180 / Math.PI;
}
```

In this formula `Math.atan2(y, x) * 180` should be wrapped in parenthesis like this:
```
function calcAngleDegrees(x, y) {
  return (Math.atan2(y, x) * 180) / Math.PI;
}
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/math/atan2`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/atan2/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by vlwkaos** [comment]
As you can see from this page [operator precedence](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence), `*` and `/` has the same precedence and therefore follows associativity of 'left-to-right'. So even without the parenthesis, `Math.atan2(y, x) * 180` will be calculated first, then `... / Math.PI` second. You confirm this by running the two functions you mentioned.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/44766242/157893588-6e00f54a-5a5b-497f-a6ba-c742c95888d3.png">

**Comment by teoli2003** [comment]
I confirm: like in regular math, JavaScript calculate these two expressions in the same way. Closing; reopen if I'm mistaken.
