### ISSUE TITLE
Issue with "Error.prototype.lineNumber": renamed to lineno

### ISSUE THREAD

**Issue by clankill3r** [mdn/content#13766]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/lineNumber

Really short: it seamed `lineNumber` is renamed to `lineno`

**Comment by wbamberg** [comment]
Do you have a reference for this? I just tried this in the Firefox devtools:

```js
const e = new Error('Could not parse input');
try {
  throw e;
} catch {
  console.log(`lineno: ${e.lineno}`);
  console.log(`lineNumber: ${e.lineNumber}`);
}
```

...and got:

```
lineno: undefined
lineNumber: 1
```

**Comment by vlwkaos** [comment]
Seems like there is a implementation difference in js engine. 
For example Firefox console has `lineNumber`. (uses spidermonkey engine) 
Typing it in vscode()  autocomplete `lineno`. (electron uses chromium so v8)

**Comment by wbamberg** [comment]
In Chrome and Node I get:

```
lineno: undefined
lineNumber: undefined
```

**Comment by vlwkaos** [comment]
Found out the difference was
1.  error received through `error` event listener -> lineno
2. error caught in try catch syntax -> lineNumber

You can check this with the following code: 

```js
var e = new Error('Could not parse input');
window.addEventListener('error', function(e) {
		console.log('from event listener');
		console.log('lineno',e.lineno); 
		console.log('lineNumber',e.lineNumber); 
	});
  
try {
  throw e;
} catch {
	console.log('error catched')
  console.log(`lineno: ${e.lineno}`);
  console.log(`lineNumber: ${e.lineNumber}`);
  throw e;
}
```

**Comment by wbamberg** [comment]
I think we should close this, as the docs are correct here.
