### ISSUE TITLE
Issue with "Image file type and format guide": JPEG greyscale mode

### ISSUE THREAD

**Issue by MikeRich88** [mdn/content#13784]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types

#### What information was incorrect, unhelpful, or incomplete?
"JPEG has no distinct greyscale mode." is incorrect. It does have a single  component (greyscale) mode. See https://stackoverflow.com/questions/51008883/is-there-a-grayscale-jpg-format

#### Specific section or headline?
[JPEG (Joint Photographic Experts Group image)](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#jpeg_joint_photographic_experts_group_image)

#### What did you expect to see?
That there is a greyscale mode of JPEG

#### Did you test this? If so, how?
n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/media/formats/image_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/media/formats/image_types/index.md
* Last commit: https://github.com/mdn/content/commit/6637b45662089bc1ea48e6a25a8728d2dc9a7fa3
* Document last modified: 2022-03-01T22:12:03.000Z

</details>

**Comment by hamishwillee** [comment]
@sideshowbarker 
FMI only, while I "believe" it is probably supported how do you verify stuff like this? The links are to stackoverflow and Wikipedia - when you get to the actual spec it is hidden behind a login - but in any case isn't clear whether it "applies" or not. For example, the spec on colour space ITU-R BT.601 is "Studio encoding parameters of digital television for standard 4:3 and wide screen 16:9 aspect ratios" and that doesn't sound like JPEG to me :-).

The data/examples aren't conclusive - greyscale can be "emulated" without having a specific mode, and you wouldn't necessarily know by looking at file sizes with a well compressed file.

**Comment by sideshowbarker** [comment]
I think in cases like this, maybe the best means we have for getting confirmation are to ask someone we know with a lot of graphics domain knowledge to look it over. For me, @svgeesus is the first person who comes to mind.

**Comment by hamishwillee** [comment]
Thanks @svgeesus - much appreciated. I have summarized in https://github.com/mdn/content/pull/13992.

If you are able at some point, it would be excellent if you could sanity check the [whole page](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types) as I suspect it might have other errors.

**Comment by svgeesus** [comment]
> Thanks @svgeesus - much appreciated. I have summarized in https://github.com/mdn/content/pull/13992.

Nice.
