### ISSUE TITLE
Issue with "HTML table basics": Missing `caption` element

### ISSUE THREAD

**Issue by norfali** [mdn/content#13782]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Basics

#### What information was incorrect, unhelpful, or incomplete?

I do not see `caption` element mentioned or covered (or in code snippets).

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Basics#active_learning_creating_your_first_table

#### What did you expect to see?

Although the next page, https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced, covers the `caption` element, I wonder if it makes sense that `caption` is required at a _basic_ level, e.g. is `caption` really considered an "advanced" feature?

This might encourage new developers/engineers to start creating a table with caption by default.

#### Did you test this? If so, how?

Not tested.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/tables/basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/tables/basics/index.md
* Last commit: https://github.com/mdn/content/commit/7e329de8a1ec173df42c8eab9448f93c3e6c7cfa
* Document last modified: 2022-02-02T01:34:30.000Z

</details>

**Comment by gullapalli9482** [comment]
As far as I understood, you want the section in the advanced section instead of the beginner section. Am I right?

**Comment by teoli2003** [comment]
I'm going to close this: I think most of the tables on the web don't need a caption element. Choosing to cover it in the advanced section is therefore a legitimate editorial choice.
