### ISSUE TITLE
Issue with "Border-image generator": It says the content is blocked :(

### ISSUE THREAD

**Issue by oona-mlb** [mdn/content#13783]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Border-image_generator

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_backgrounds_and_borders/border-image_generator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Border-image_generator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_backgrounds_and_borders/border-image_generator/index.md
* Last commit: https://github.com/mdn/content/commit/9a9a9f2155e0a09d0fc79861863d24407041dc24
* Document last modified: 2021-08-20T06:28:15.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing. Could you be a bit more specific? What says the content is blocked, and what do you see when you load the page? For me the page works (although the layout is broken, but that's tracked separately here: https://github.com/mdn/yari/issues/5392 .

**Comment by teoli2003** [comment]
Same here, it works for me (except for the layout)

**Comment by AnilSeervi** [comment]
It might be an extension that you might have installed in the browser you are previewing the page.

**Comment by wbamberg** [comment]
No response, closing.
