### ISSUE TITLE
"Strict-Transport-Security": why does the Note still say "The Strict-Transport-Security header is ignored by the browser"? The browser does not ignore the HSTS header. Instead it automatically converts the connection to https - this is according to the Description. So what is the Note trying to say?

### ISSUE THREAD

**Issue by chmgui** [mdn/content#1378]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

#### What information was incorrect, unhelpful, or incomplete?
Do not understand this "Note: The Strict-Transport-Security header is ignored by the browser when your site is accessed using HTTP; this is because an attacker may intercept HTTP connections and inject the header or remove it".

In the Description: "The HTTP Strict Transport Security header informs the browser that it should never load a site using HTTP and should automatically convert all attempts to access the site using HTTP to HTTPS requests instead."

So when user types http or does not type the scheme at all,  the HSTS header in the response will automatically converts his connection to https?   So why does the Note still say "The Strict-Transport-Security header is ignored by the browser"?   The browser does not ignore the HSTS header.  Instead it automatically converts the connection to https - this is according to the Description.   So what is the Note trying to say?   

Thank you very much.

#### Specific section or headline?
Description - Note.

#### What did you expect to see?
N/A

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/strict-transport-security`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/headers/strict-transport-security/index.html
* Report started: 2021-01-16T03:37:08.988Z

</details>

**Comment by Master613** [comment]
@chmgui The note currently says that when you initially access a site over HTTPS with no certificate errors, the browser knows your site is HTTPS capable and will honor the Strict-Transport-Security header. If it has only been accessed by HTTP, the browser **does not** know that your site is HTTPS capable and will **not** honor the header. However, the first part of the note seems redundant, as I don't see a difference whether the site uses the header or not when an attacker is injecting it.

**Comment by heavymachinery** [comment]
👋 Could this be assigned to me please? I'm working on a PR to clarify this note!
