### ISSUE TITLE
Microdata DOM API: Abandoned or Alive and Well?

### ISSUE THREAD

**Issue by HelmZalee** [mdn/content#13791]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Microdata_DOM_API

#### What information was incorrect, unhelpful, or incomplete?
This: **Warning**: Microdata...have been abandoned and removed from all browsers" (Page dated Feb 18 2022)

#### Specific section or headline?
Boxed at top of the article

#### What did you expect to see?
I expected something that would not contradict [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes)  (Page dated Feb 24 2022).  That article itemizes and describes global attributes, including itemid, itemprop, itemref, itemscope, itemtype), prefixing the list with a note and a helpful link: _Note: The item* attributes are part of the [WHATWG HTML **Microdata** [feature ](https://html.spec.whatwg.org/multipage/microdata.html#microdata)

No mention of anything being deprecated, much less abandoned.

In the Compatibility table at the end of the article, all 5 item* are supported by the listed browsers.  They do not seem "abandoned".

#### Did you test this? If so, how?
Tried to make sense of the Micrrodata_DOM_API and failed miserably.  Guessing **Microdata** in its context doesn't mean the same as "**Microdata**" in the Global_attributes article.  

If that's the case, the DOM API article might mention the new use of the old word.  Maybe  Microdata have been replaced by Microdata?  No idea how that works for an "archived" article, which perhaps cannot be modified.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/microdata_dom_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Microdata_DOM_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/microdata_dom_api/index.md
* Last commit: https://github.com/mdn/content/commit/89c8199b06e7fb2b76da4087cb9eedef065b2506
* Document last modified: 2022-02-18T09:24:31.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #13820 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
