### ISSUE TITLE
Issue with "Regular expressions": (consider documenting unicode mode differences)

### ISSUE THREAD

**Issue by kevinushey** [mdn/content#13799]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

#### What information was incorrect, unhelpful, or incomplete?

There are a couple of small differences between unicode and non-unicode regular expressions that could be worth illuminating here. For example:

- Escaping a character which doesn't require escaping is an error; e.g. `/\'/` is okay, but `/\'/u` is not.
- Brackets need to be escaped when not used as quantifiers, e.g. `/{/` is okay, but `/{/u` is not.
- Character classes might have other restrictions, e.g. `/[\w-+]/` is okay, but `/[\w-+]/u` is not.
- And perhaps others I'm not aware of?

The issue with identity escapes has a blurb at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet, but I think it would be worth detailing that in the main guide as well.

Other relevant posts I stumbled upon:

https://stackoverflow.com/a/63007777
https://stackoverflow.com/q/54205197

#### Specific section or headline?

I would propose adding this as a new headline; e.g. "Differences between unicode and non-unicode regular expressions".

#### What did you expect to see?

A small section describing the difference between unicode and non-unicode regular expressions, in terms of what characters are considered "special" or other such rules.

#### Did you test this? If so, how?

N/A, I think?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/index.md
* Last commit: https://github.com/mdn/content/commit/e1df33247c4bc14ef56088b5ca83e4e6fc8488d8
* Document last modified: 2022-02-09T02:25:21.000Z

</details>

**Comment by hamishwillee** [comment]
Sounds very reasonable. Would you like to contribute the section?

**Comment by kevinushey** [comment]
I will give it a shot. Thanks!
