### ISSUE TITLE
Issue with "How do you set up a local testing server?": Client-side JavaScript runs on the browser.

### ISSUE THREAD

**Issue by weeklyd3** [mdn/content#13792]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server

#### What information was incorrect, unhelpful, or incomplete?
Client-side JavaScript runs on the client, assuming it's enabled in the browser. Server-side JavaScript requires special software.

#### Specific section or headline?
Under [`Running server-side languages locally`](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server#running_server-side_languages_locally), the page says:
> it doesn't know how to run code written in languages such as Python, PHP or JavaScript.

#### What did you expect to see?
A correction making the line end with `as Python, PHP or server-side JavaScript` would be nice.

#### Did you test this? If so, how?
1. Create HTML file with client side JavaScript
2. Create JS file with server-side JavaScript
3. Open Python development server
4. We can't see the result of the server-side JavaScript, but the browser executes the client-side JavaScript nicely.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/common_questions/set_up_a_local_testing_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/set_up_a_local_testing_server/index.md
* Last commit: https://github.com/mdn/content/commit/295e508da72ff83272a3b1ffa69a72cfeffcebde
* Document last modified: 2022-02-01T03:06:25.000Z

</details>

**Comment by wbamberg** [comment]
I'm conflicted about this. It is correct:

> Python's http.server (or SimpleHTTPServer for Python 2) module is useful, but it is merely a static file server; it doesn't know how to run code written in languages such as Python, PHP or JavaScript. 

The server doesn't know how to run JavaScript. It's the browser that runs client-side JS. I think saying "server-side JS" here would be strange - by definition it is server-side, if the server is running it.

But perhaps it is confusing, and "server-side" would help?

**Comment by hamishwillee** [comment]
@wbamberg You're quite right. I don't see this as needing to be fixed, but if it did I would change from:

> Python's http.server (or SimpleHTTPServer for Python 2) module is useful, but it is merely a static file server; it doesn't know how to run code written in languages such as Python, PHP or JavaScript. To handle them, you'll need something more — exactly what you'll need depends on the server-side language you are trying to run. Here are a few examples:

to something like

> Python's http.server (or SimpleHTTPServer for Python 2) module is a static file server.
> If your website has dynamic content generated using languages such as Python, PHP or JavaScript you'll need to use a different tool.
> Exactly what you'll need depends on the server-side language you are trying to run. Here are a few examples:


Worth doing?

**Comment by wbamberg** [comment]
Honestly, I like the original better! So I'm closing this (but please reopen if you think there is a better solution).
