### ISSUE TITLE
Issue with "Cache-Control": (The description of two request directives are incorrect)

### ISSUE THREAD

**Issue by jamesxu2018** [mdn/content#13808]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

#### What information was incorrect, unhelpful, or incomplete?
They are max-age, max-stale
MDN said:
The max-age=N request directive indicates that the client allows a stored response that is generated on the origin server within N seconds 
In the case above, if the response with Cache-Control: max-age=604800 was stored in caches 3 hours ago, the cache couldn't reuse that response.
---comment by James: That means there is a local timer tracking the local resident time of the repsonse. but it should be consider the age coming from a proxy cache. 

simliar to max-stale
MDN said:

The max-[stale](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#freshness)=N request directive indicates that the client allows a stored response that is stale within N seconds.

Cache-Control: max-stale=3600
In the case above, if the response with Cache-Control: max-age=604800 was stored on caches 3 hours ago, the cache couldn't reuse that response.
---comment by James: similar to max-age, That means there is a local timer tracking the local resident time of the repsonse. but it should be consider the freshness lifetime  from the origin cache. 

#### Specific section or headline?
Request directive
max-age
max-stale

#### What did you expect to see?
quote from rfc7234: "
The "max-age" request directive indicates that the client is
   unwilling to accept a response whose age is greater than the
   specified number of seconds."

quote from rfc7234:
The "max-stale" request directive indicates that the client is
   willing to accept a response that has exceeded its freshness
   lifetime.  If max-stale is assigned a value, then the client is
   willing to accept a response that has exceeded its freshness lifetime
   by no more than the specified number of seconds.  If no value is
   assigned to max-stale, then the client is willing to accept a stale
   response of any age.

#### Did you test this? If so, how?
No. As the description is not what the willing of rfc7324.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/cache-control`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/cache-control/index.md
* Last commit: https://github.com/mdn/content/commit/5ef0163136a0a6ac356cb93a35b995c521b2bc49
* Document last modified: 2022-02-21T00:44:26.000Z

</details>

**Comment by sideshowbarker** [comment]
@Jxck, would be great if you could take a look at this one

**Comment by Jxck** [comment]
Yes, caches alway respect Age on proxy.
This is simplified example but I'll add mentioning for Age header later.
