### ISSUE TITLE
Issue with "TypedArray.prototype.set()": (bad spec link, ambiguous param name)

### ISSUE THREAD

**Issue by tshinnic** [mdn/content#13815]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set

#### What information was incorrect, unhelpful, or incomplete?

1) The link to the ECMAscript spec is rather to an internal implementation API, not the description of the entire API. The link ought to be to [23.2.3.24 %TypedArray%.prototype.set](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-%typedarray%.prototype.set) 

2) While in the spec's argument description it says "(source, offset)" not much farther on it switches to using "targetOffset", as the offset is *not* into the source buffer/array but an offset into the TypedArray buffer "where values are written."
Since there are two different buffers one is surprised to see only one offset parameter, and concerned as to *which* buffer is being addressed by that offset.
The MDN doc prose does say "offset into the target array at which to begin writing" clearly, but the API having only one offset is still confusing.
&nbsp;
Would it not be better to name the parameter "targetOffset" rather than the ambiguous "offset"? 

#### Specific section or headline?

Heading ["Specifications"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set#specifications)

Heading ["Parameters"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set#parameters)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/typedarray/set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/typedarray/set/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #13818 and https://github.com/mdn/browser-compat-data/pull/15354 with fixes.

After those fixes are merged, this issue will automatically be marked as resolved, and closed.
