### ISSUE TITLE
Issue with "HTML basics": Bad capitalization and unnecessary spaces

### ISSUE THREAD

**Issue by Tyler887** [mdn/content#13826]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics

#### What information was incorrect, unhelpful, or incomplete?
> HTML ( Hyper t ext Markup Language ) is the code that is used to structure a web page and its content. For example, content could be structured within a set of paragraphs, a list of bulleted points, or using images and data tables. As the title suggests, this article will give you a basic understanding of HTML and its functions.

#### Specific section or headline?
Top of page
#### What did you expect to see?
> HTML (Hyper Text Markup Language) is the code that is used to structure a web page and its content. For example, content could be structured within a set of paragraphs, a list of bulleted points, or using images and data tables. As the title suggests, this article will give you a basic understanding of HTML and its functions.

#### Did you test this? If so, how?
Determined by reading the article.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/html_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/html_basics/index.md
* Last commit: https://github.com/mdn/content/commit/0160aac0e623dacdce4019205f32f7b3d3e58019
* Document last modified: 2022-02-18T09:33:58.000Z

</details>

**Comment by vlwkaos** [comment]
Which browser are you using? This is how I see it (firefox)
<img width="757" alt="image" src="https://user-images.githubusercontent.com/44766242/158060077-96639142-3351-456d-807e-df544ff47ca6.png">
