### ISSUE TITLE
SVG "text-anchor": broken "inline-size" link; fix by linking to CSS "inline-size"? or else a new doc page for that SVG attribute

### ISSUE THREAD

**Issue by Penguinlay** [mdn/content#13846]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor

#### What information was incorrect, unhelpful, or incomplete?
Link with text "inline-size" is broken.

#### Specific section or headline?
first text paragraph after long list, near the end of the sentence

#### What did you expect to see?
https://developer.mozilla.org/en-US/docs/Web/CSS/inline-size if it is the same as CSS, else a new doc page as SVG attribute.

#### Did you test this? If so, how?
Click on the link, which will redirected to Page Not Found.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/attribute/text-anchor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/text-anchor/index.md
* Last commit: https://github.com/mdn/content/commit/909c7ece968f1c0b8c9c3f881a7b4d2c5401a00e
* Document last modified: 2022-02-05T07:38:20.000Z

</details>

**Comment by HarshUdai** [comment]
Hello @Penguinlay , i would to like to contribute on this issue.

The below approach i would be using to solve the issue.
The Things which is needed to be changed for the fix:
set the href to : https://developer.mozilla.org/en-US/docs/Web/CSS/inline-size.

Thank you

**Comment by Penguinlay** [comment]
> Hello @Penguinlay , i would to like to contribute on this issue.
> 
> The below approach i would be using to solve the issue. The Things which is needed to be changed for the fix: set the href to : https://developer.mozilla.org/en-US/docs/Web/CSS/inline-size.
> 
> Thank you

Sure, please go ahead.

**Comment by HarshUdai** [comment]
@Penguinlay i have created a PR for this issue #13863. Please check.

**Comment by Penguinlay** [comment]
Possibly resolved by #13863.

**Comment by Penguinlay** [comment]
Closing this since PR is successfully merged at #13863.
