### ISSUE TITLE
Issue with "How to use promises": example code outputs vary across browsers

### ISSUE THREAD

**Issue by sharonytlau** [mdn/content#13842]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises

#### What information was incorrect, unhelpful, or incomplete?

The [`statusText` property](https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText) of `Response` is used in many code examples on this page. However, this property's return value is different across browsers. These code examples will confuse learners if they run the examples in their own browsers.

The following shows screenshots for running one of the code examples on my computer (Windows 10 Home).
 The `statusText` property values (highlighted in yellow) are the same as the output given by the author in  Firefox (98.0), but are empty in Chrome (99.0.4844.51).

``` javascript
const fetchPromise1 = fetch('https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json');
const fetchPromise2 = fetch('https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/not-found');
const fetchPromise3 = fetch('https://mdn.github.io/learning-area/javascript/oojs/json/superheroes.json');

Promise.all([fetchPromise1, fetchPromise2, fetchPromise3])
  .then( responses => {
    for (const response of responses) {
      console.log(`${response.url}: ${response.statusText}`);
    }
  })
  .catch( error => {
    console.error(`Failed to fetch: ${error}`)
  });
```

![firefox-screenshot](https://user-images.githubusercontent.com/62269974/158096137-e79538d7-ebf1-43d1-9c76-e15f0b8c9993.png)

![chrome-screenshot](https://user-images.githubusercontent.com/62269974/158095261-f5de1733-1e6b-4965-96a5-a09c93234ce0.png)

P.S.  I believe this is caused by inconsistency of user agent implementations of the specification. I've found one related issue: https://github.com/whatwg/fetch/issues/599. 

#### Specific section or headline?

One example in the [Using the fetch() API](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises#using_the_fetch_api) section and three examples in the [Combining multiple promises](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises#combining_multiple_promises) section have used `statusText`.

#### What did you expect to see?

I suggest modifying the examples: use `status` rather than `statusText` where appropriate, so that the outputs can be consistent across browsers. 

The following shows screenshots for running the same code example with the suggested modification in my browsers:

``` javascript
const fetchPromise1 = fetch('https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json');
const fetchPromise2 = fetch('https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/not-found');
const fetchPromise3 = fetch('https://mdn.github.io/learning-area/javascript/oojs/json/superheroes.json');

Promise.all([fetchPromise1, fetchPromise2, fetchPromise3])
  .then( responses => {
    for (const response of responses) {
      console.log(`${response.url}: ${response.status}`);
    }
  })
  .catch( error => {
    console.error(`Failed to fetch: ${error}`)
  });
```

![firefox-screenshot-2](https://user-images.githubusercontent.com/62269974/158096962-fa393db1-3623-4f5c-a4c6-5666437fff39.png)

![chrome-screenshot-2](https://user-images.githubusercontent.com/62269974/158096769-4adad1a6-632e-4fda-9737-f6c0cb5b71db.png)

If this suggestion is agreed upon. I can open a PR with changes for all the relevant code examples, outputs, as well as explanations.

#### Did you test this? If so, how?
I've tested in my own environment as illustrated above.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/promises/index.md
* Last commit: https://github.com/mdn/content/commit/bf8f98fd23e853fc46db8e385efe80de062097a4
* Document last modified: 2022-03-08T04:09:51.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing this issue!

> If this suggestion is agreed upon. I can open a PR with changes for all the relevant code examples, outputs, as well as explanations.

I'd be very happy to review a PR like this.
