### ISSUE TITLE
Question on"Array.from()": (Why do I need to use array.from() in the (Array from a Set) section when array.set() already returns an array.)

### ISSUE THREAD

**Issue by Absleepy** [mdn/content#13844]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/from`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/from/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by teoli2003** [comment]
I don't find any `Array/set` method. Where did you find it?

**Comment by casaper** [comment]
@Absleepy I agree with @teoli2003 . There is no method Array.set() as far as I can see.

Could it be that you mixed up [Set.prototype.values()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/values) in the play somehow?

If that ambiguation is the case: 

`Set.prototype.values()` returns an iterator, and not an array. So not the same as `Array.from(set)`

**Comment by Absleepy** [comment]
On MDN there is 
![image](https://user-images.githubusercontent.com/59653077/159148491-ffb185ba-fc7f-4dc9-8a8a-0ee7ec19865b.png)

why don't they write it as   **Array.from(['foo', 'bar', 'baz', 'foo'])**

**Comment by teoli2003** [comment]
Oh yes, thank you. Yes, you can write this, but the goal was to demonstrate that if you have a `Set` you could get an array from it. Here a `Set` is built from a list (with the `foo` item taken only once):
![Capture d’écran 2022-03-20 à 07 08 25](https://user-images.githubusercontent.com/1466293/159150472-75a68ef6-1757-4013-88d9-92f6af7196a4.png)


With your example, you build the `Array` from the list  and have twice the item `foo`:
![Capture d’écran 2022-03-20 à 07 07 05](https://user-images.githubusercontent.com/1466293/159150448-ad7f04f8-9b4b-40a0-86a8-bc6598bd360c.png)

I'm going to close this. Feel free to reopen if I've missed something. Thanks!
