### ISSUE TITLE
Issue with "Client-side storage": tried the example IndexedDB code; delete button doesn’t work

### ISSUE THREAD

**Issue by meredithyan** [mdn/content#13847]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

#### What information was incorrect, unhelpful, or incomplete?
Indexed DB example: the js file is not correct,because when I applied the js file directly and click the delete button, the delete button is not at work

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/client-side_storage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/client-side_web_apis/client-side_storage/index.md
* Last commit: https://github.com/mdn/content/commit/4af7261cd510ace45c0ad563b5e6253f91037ee1
* Document last modified: 2022-03-09T19:33:32.000Z

</details>

**Comment by sideshowbarker** [comment]
I guess this is specifically about https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage#storing_complex_data_%E2%80%94_indexeddb?

> Indexed DB example: the js file is not correct,because when I applied the js file directly and click the delete button, the delete button is not at work

When you open devtools and look at the console, and then try that example code, exactly what messages is the browser logging in the devtools console?

**Comment by meredithyan** [comment]
Hi：
the message on the console  when you first load the page:
Database opened succesfully
Notes all displayed

the message when you try to delete but failed:
![111](https://user-images.githubusercontent.com/33853013/158150900-4a6921e9-2b7f-42fb-b074-f22b3148a420.JPG)
Uncaught DOMException: Data provided to an operation does not meet requirements.
deleteItem file:///C:/Users/Administrator/Desktop/indexed DB/bidui.js:152

**Comment by wbamberg** [comment]
I've worked through the example and it is working correctly in Firefox and Chrome. I also checked the "final" version at https://mdn.github.io/learning-area/javascript/apis/client-side-storage/indexeddb/notes/ (source code at https://github.com/mdn/learning-area/blob/main/javascript/apis/client-side-storage/indexeddb/notes/index.js).

Could you please compare your version of index.js with the version at https://github.com/mdn/learning-area/blob/main/javascript/apis/client-side-storage/indexeddb/notes/index.js ? Could you please share your version of index.js?

**Comment by sideshowbarker** [comment]
@meredithyan This is waiting on your response to https://github.com/mdn/content/issues/13847#issuecomment-1067217567

**Comment by sideshowbarker** [comment]
Closing for lack of response
