### ISSUE TITLE
Feature request in "MDN Web Docs Glossary": 'Literal' is missing. 

### ISSUE THREAD

**Issue by 552020** [mdn/content#1385]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary

#### What information was incorrect, unhelpful, or incomplete?

The concept 'literal' is missing. 

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Glossary

#### What did you expect to see?

A definition of 'literal' like: https://en.wikipedia.org/wiki/Literal_(computer_programming)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/glossary/index.html
* Report started: 2021-01-16T10:06:51.981Z

</details>

**Comment by sideshowbarker** [comment]
Duplicates #1400
