### ISSUE TITLE
Issue with "Window.confirm()": not alternative has been suggested

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#13857]
MDN URLS: 
https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm
and
https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt
and
https://developer.mozilla.org/en-US/docs/Web/API/Window/alert

#### What information was incomplete?
In the Notes section developers have been advised not to use these APIs. 
And no alternative has been suggested.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm#notes

#### What did you expect to see?
The inbuilt HTML `<dialog>` element is a good candidate to take these API's place. 
At the end of the notes one liner about the element and link to it, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog, will be very useful for the readers.

The `<dialog>` element needs to be mentioned on all three confirm(), alert(), and prompt() pages.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/confirm`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/confirm/index.md
* Last commit: https://github.com/mdn/content/commit/e752a8fe731fbdb9061e39a6e2b797a7ccb7e2b5
* Document last modified: 2022-01-19T17:57:58.000Z

</details>

**Comment by teoli2003** [comment]
Yes, the `<dialog>` element took long to be standardized and implemented in an interoperable way, which explains why it is not mentioned.

Do you want to try opening a PR to fix this?

**Comment by OnkarRuikar** [comment]
Sure on it!
