### ISSUE TITLE
Content bug: <Comments of code overlap code>

### ISSUE THREAD

**Issue by DavidMorenoDev** [mdn/content#13866]
## What page(s) did you find the problem on?

 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

## Specific page section or heading?

 First section of examples

## What is the problem?

 Examples comments of code overlap code...it's something weird. I'm in Edge

## What did you expect to see?

 Separete comments and line of codes

**Comment by hamishwillee** [comment]
Thanks @DavidMorenoDev 
Can you please screenshot a problem area, as I'm not seeing this on Edge, Chrome or Firefox.

**Comment by DavidMorenoDev** [comment]
> Thanks @DavidMorenoDev 
> Can you please screenshot a problem area, as I'm not seeing this on Edge, Chrome or Firefox.

Someone solve it without notify here

**Comment by hamishwillee** [comment]
OK I'll mark this as closed then. Thanks.
