### ISSUE TITLE
Issue with "Add to Home screen": SSB on desktop is not being worked on

### ISSUE THREAD

**Issue by oliveconstant** [mdn/content#1386]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen

#### What information was incorrect, unhelpful, or incomplete?

> Firefox [...] is working on desktop support.

I think this is not true any more: https://bugzilla.mozilla.org/show_bug.cgi?id=1682593.

#### Specific section or headline?

Section named "What browsers support A2HS?"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/progressive_web_apps/add_to_home_screen`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/progressive_web_apps/add_to_home_screen/index.html
* Report started: 2021-01-16T14:53:17.487Z

</details>

**Comment by chrisdavidmills** [comment]
@oliveconstant Said to say, you are right; I remember reading this thread too, recently.

I've updated the page accordingly — https://github.com/mdn/content/commit/12da1a0b1beac3e68cd4f60b9510d586bd1ba50b

Thanks for reporting.
