### ISSUE TITLE
Issue with "<a>: The Anchor element": Article implies file:/// scheme is supported

### ISSUE THREAD

**Issue by Dani21** [mdn/content#13867]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

#### What information was incorrect, unhelpful, or incomplete?

"Links are not restricted to HTTP-based URLs — they can use any URL scheme supported by browsers"

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-href

#### What did you expect to see?

"Besides the filesystem scheme `file:///`, links are not restricted to HTTP-based URLs — they can use any URL scheme supported by browsers"

#### Did you test this? If so, how?

Trying to visit any anchor linked to file:///C:/ fails in Firefox, but there's no problem when manually browsing to it: https://jsfiddle.net/ud82scgy/

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/a`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/a/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by danburzo** [comment]
The `file://` scheme _is_ supported in the `href` attributes of `<a>` elements. It's just that, for security reasons, you can't generally open a link pointing to a local file from a `https://` page.

**Comment by Dani21** [comment]
That’s a fair point, but I don’t think MDN says that anywhere. Further, in the Security and Privacy section of the anchor page, it doesn’t mention that. Should it be placed under that heading? I didn’t see anything in the JavaScript pages regarding this either.

**Comment by estelle** [comment]
this has been removed from the doc (I don't know when). Closing.
