### ISSUE TITLE
Issue with "HTTP caching": Varying responses --- the cache key should be url+accept-encoding's value

### ISSUE THREAD

**Issue by jamesxu2018** [mdn/content#13874]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

#### What information was incorrect, unhelpful, or incomplete?
At the section of Varying responses, the words 'Document stored w/ url and Content-Encoding as keys' in the diagram is wrong.
---comment by James: the cache key should be url+vary header's value,here is accept-encoding's value to differentiate varying user requests.

#### Specific section or headline?
Varying responses

#### What did you expect to see?
Document stored w/ url and Accept-Encoding's value as keys. 

#### Did you test this? If so, how?
Not yet.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/caching`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/caching/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by jamesxu2018** [comment]
quoting from rfc7234: '
If a request target is subject to content negotiation, its cache
   entry might consist of multiple stored responses, each differentiated
   by a secondary key for the values of the original request's selecting
   header fields (Section 4.1).'

**Comment by sideshowbarker** [comment]
@Jxck, @mnot can you confirm?

**Comment by Jxck** [comment]
Yes, value of vary is request header, not response header. I'll fix this.

**Comment by Josh-Cena** [comment]
I believe it's fixed now
