### ISSUE TITLE
Issue with "URLSearchParams()": Examples with array wanted

### ISSUE THREAD

**Issue by reisi007** [mdn/content#13938]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams

#### What information was incorrect, unhelpful, or incomplete?

Chrome allowes this: `new URLSearchParams({"test":[1,2]}).toString()` and results in `test=1%2C2` (`test=1,2`). This is not documented

#### Specific section or headline?

Example section & init parameter section

##### init

with an [iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#iterators) that produces a sequence of string pairs 

also numbers seem to be allowed

##### example section

An example similar to the one above to document the single key, multiple value example

#### Did you test this? If so, how?

See above using Chrome 99

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/urlsearchparams/urlsearchparams`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/urlsearchparams/urlsearchparams/index.md
* Last commit: https://github.com/mdn/content/commit/051a58403e033d58aa76fd252a9b648810562bb4
* Document last modified: 2022-02-23T15:06:57.000Z

</details>

**Comment by annevk** [comment]
What you are seeing there is the result of Chrome (also happens in other browsers by the way) stringifying the array as it's required to do per Web IDL. If it truly supported that as multi-value syntax, the end result would be `test=1&test=2`, not `test=1,2`.

Perhaps MDN should do more to educate readers about the effects of Web IDL, but that seems like a more general issue.

**Comment by reisi007** [comment]
Thank you! I will close this issue.

Amazed by the fast feedback
