### ISSUE TITLE
Issue with "Compiling from Rust to WebAssembly": …

### ISSUE THREAD

**Issue by zafergurel** [mdn/content#1394]
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

#### What information was incorrect, unhelpful, or incomplete?
The following code did not work:

<pre>
const js = import("./node_modules/hello-wasm/hello_wasm.js");  
js.then(() => { 
  js.greet("WebAssembly"); 
}); 
</pre>
In the console log, "js.greet is not a function" error is displayed.

#### What did you expect to see?
An alert box saying "Hello, WebAssembly!" .

#### Did you test this? If so, how?
I followed all the steps., built the app and run the webpack dev server to go to localhost:8080.
I solved changing the code as follows:
<pre>
const js = import("./node_modules/hello-wasm/hello_wasm.js"); 
js.then((wasm_mod) => { 
  wasm_mod.greet("WebAssembly"); 
}); 
</pre>

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/rust_to_wasm`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/webassembly/rust_to_wasm/index.html
* Report started: 2021-01-16T16:57:46.261Z

</details>

**Comment by chrisdavidmills** [comment]
This very issue got fixed by a PR the other day: see https://github.com/mdn/content/commit/820f2a3093ec66b0896165315dd182911fa30aa3
