### ISSUE TITLE
I filed an internal feature request with them on your behalf, so no need for you to do anything there :)

### ISSUE THREAD

**Issue by feroenmmek** [mdn/content#13945]
I filed an internal feature request with them on your behalf, so no need for you to do anything there :)

I'll update this issue when we have progress.

_Originally posted by @dasmdasm in https://github.com/google/differential-privacy/issues/90#issuecomment-993016182_

**Comment by feroenmmek** [comment]
> I filed an internal feature request with them on your behalf, so no need for you to do anything there :)
> 
> I'll update this issue when we have progress.
> 
> _Originally posted by @dasmdasm in https://github.com/google/differential-privacy/issues/90#issuecomment-993016182_

**Comment by hamishwillee** [comment]
@teoli2003 Can yo block this spammer?
