### ISSUE TITLE
Issue with "AudioContext.createMediaStreamTrackSource()": Example is not using the method exemplified

### ISSUE THREAD

**Issue by Oortone** [mdn/content#13941]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamTrackSource

`let source = audioCtx.createMediaStreamSource(stream);`

#### Specific section or headline?
The Javascript example.

#### What did you expect to see?
Something using `createMediaStreamTrackSource()`

I also don't understand where the variable/object `audio` in  `audio.srcObject` comes from.

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/audiocontext/createmediastreamtracksource`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamTrackSource
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/audiocontext/createmediastreamtracksource/index.md
* Last commit: https://github.com/mdn/content/commit/516c74d03bd44861eca7da5a96d287aef846b89d
* Document last modified: 2022-01-27T16:52:19.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by #16861
