### ISSUE TITLE
"Throttling" article: How can I open the "network monitor"? Where is there any “throttling” option?

### ISSUE THREAD

**Issue by SomeoneElseOSM** [mdn/content#13956]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Throttling

#### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Throttling

#### Specific section or headline?

n/a, problem applies to the whole page.

#### What did you expect to see?

The page talks about "The network monitor" and goes on to describe "The toolbar is at the top of the main network monitor window".

Unfortunately the page contains no information about how to get to "The network monitor" from within Firefox.  There is no "The network monitor" on any obvious menus and no way to search for it.  I can see many menu entries with similar names, but none exactly the same.

I found the https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Throttling page via a web search.  What I'd expect to see on that page is some way how to access that functionality in the browser itself - what buttons do I need to press in what order?

#### Did you test this? If so, how?

n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/network_monitor/throttling`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Throttling
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/network_monitor/throttling/index.html
* Last commit: https://github.com/mdn/content/commit/0ea5ea66ca3ff5f0c02583c1f3606b3b7d4aee40
* Document last modified: 2021-02-02T16:28:31.000Z

</details>

**Comment by SomeoneElseOSM** [comment]
Hamburger / More Tools / Web Developer Tools
This opens a separate window called "Developer Tools" (it appears to be confused what it is called)
There's a picture of what appears to be a lorry overtaking a van at the top right, just to the left of the "three dots" menu.
Hovering over the overtaking lorry shows some text "Responsive design mode" (there's no help on any of these screens explaining what any of this means)

In there there is a "throttling" option
Is this related?

Unfortunately on that screen is also some device emulation options, and "the actual device that I am actually using" is not one of the available options, making it not very usable.

**Comment by sideshowbarker** [comment]
I think what this article calls “network monitor” is just the **Network** tab/pane in devtools.

And in the Network tab/pane in devtools, there’s a tool bar that has a **Disable Cache** checkbox, and next to that there’s a control that by default is labeled **No Throttling**.  And when you activate that, you get some throttling options.

![image](https://user-images.githubusercontent.com/194984/158726552-f9f6e779-b89b-4e7b-9f40-23671ddd0bfb.png)

So probably what this article needs is a screenshot like the one above, and some further explanation like what I wrote above.

**Comment by SomeoneElseOSM** [comment]
Thanks - one more thing that it'd be good to handle would be the fact that (in English GB at least) the hamburger menu option is "More Tools / Web Developer Tools" but the label on the title bar of the thing that appears is labelled "Developer Tools".

**Comment by sideshowbarker** [comment]
> Thanks - one more thing that it'd be good to handle would be the fact that (in English GB at least) the hamburger menu option is "More Tools / Web Developer Tools" but the label on the title bar of the thing that appears is labelled "Developer Tools".

For that it’s probably be best to raise a new/separate issue

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
