### ISSUE TITLE
Issue with "XMLHttpRequest.timeout": (SSL seems to timeout problem)

### ISSUE THREAD

**Issue by almas** [mdn/content#13968]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout

#### What information was incorrect, unhelpful, or incomplete?
When I send post request via XHR to https (SSL) page then there might some timeout there. About when request get long time then it failed without response etc. But to same site via http URL  then it lasts request got response. Also Chrome works with SSL.

#### Specific section or headline?
Default timeout value is 0 and there is no timeout.

#### What did you expect to see?
But SSL seems got some timeout there.

#### Did you test this? If so, how?
Found when working on web development project.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/xmlhttprequest/timeout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/xmlhttprequest/timeout/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
@almas Can you explain what specific changes do you propose need to be made to the https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout article?

**Comment by almas** [comment]
If there isn't any timeout then it might be a bug. Then I need to bug report to main development repository.
