### ISSUE TITLE
What is an interface?

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#1396]
https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream

> The ReadableStream **[interface]()** of the Streams API represents a readable stream of byte data.

- https://developer.mozilla.org/en-US/search?q=interface
- https://en.m.wikipedia.org/wiki/Interface_(computing)

**Comment by chrisdavidmills** [comment]
An interface is basically how a JavaScript class is represented in WebAPI specs. It is really a spec term, so with hindsight, it'd be better to use "class" rather than "interface", to use language more familiar with "normal" developers.

**Comment by mattiapontonio** [comment]
- Can We add to glossary?
- I know that a `class` can be `extended` or `newed` and an _interface_ can be _implemented_ but basically are groups of members that can be used.

More in general I'm interested in _porting_ the Typescript solutions to JavaScript.

I _don't hate_ the term interface.

**Comment by chrisdavidmills** [comment]
>     * Can We add to glossary?

Feel free to do so ;-)

**Comment by mattiapontonio** [comment]
I'm scared, maybe I open a PR with a blank page.

**Comment by jpmedley** [comment]
Don't be scared. We're the only one's who can really mess things up.

**Comment by Ryuno-Ki** [comment]
> In [programming] languages, a protocol [or interface or trait] is a common means for discrete objects to communicate with each other. These are definitions of methods and values which the objects agree upon, in order to co-operate, as part of an API.
> 
> The protocol/interface is a description of:
> 
> 1. The messages that are understood by the object.
> 1. The arguments that these messages may be supplied with.
> 1. The types of results that these messages return.
> 1. The invariants that are preserved despite modifications to the state of an object.
> 1. The exceptional situations that will be required to be handled by clients to the object.
> 1. (For the communications-style usage only:) The call sequence and decision points of the methods, such as would be represented in UML interaction diagrams: Communication diagram, Sequence diagram, Interaction overview diagram/Activity diagram, Timing diagram.

https://en.wikipedia.org/wiki/Protocol_(object-oriented_programming)

There are other types of interfaces (binary, with hardware etc). Here, we're thinking of Software interface, or API to be more concrete.

In my understanding, it describes a set of functions (including their signature, i.e. arguments and return values) a class needs to implement. That means, the class has this method (with the appropriate access level like public, private etc) and returns the correct format given the correct argument types. It is possible for a class to implement several interfaces.

In practice, I can see this at DOM, where HTML elements implement different interfaces (which can build up on each other, it seems).

**Comment by mattiapontonio** [comment]
Wait wait wait, like a good engeneer i readed the spec.
It says _class_ and then It has a _interface_ definiton...
Who Is wrong?

https://streams.spec.whatwg.org/#rs-class-definition

**Comment by Ryuno-Ki** [comment]
From the code, I'd say, it's an interface (it lacks implementation details).

But that link goes even more confusing (emphasis omitted):

> The ReadableStream class is a concrete instance of the general readable stream concept.

Yes, classes can get instantiated (=> concrete instance), but what is the _concept_ doing here?
Perhaps „class” is spec-term? Not to be confused with OOP-classes?

**Comment by mattiapontonio** [comment]
Great point. Also, is there a non-concrete instance?
