### ISSUE TITLE
Issue with "Introducing workers": (short summary here please)

### ISSUE THREAD

**Issue by StephaneRegnie** [mdn/content#13983]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing_workers

#### What information was incorrect, unhelpful, or incomplete?
JS files in Prime generation with a worker are empty.

#### Specific section or headline?
Prime generation with a worker

#### What did you expect to see?
Code in these files !

#### Did you test this? If so, how?
Yes

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/introducing_workers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing_workers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/introducing_workers/index.md
* Last commit: https://github.com/mdn/content/commit/ea032ab86280848d3842a7e4455b831ea2545603
* Document last modified: 2022-03-15T02:11:20.000Z

</details>

**Comment by wbamberg** [comment]
If you mean https://github.com/mdn/learning-area/tree/main/javascript/asynchronous/workers/start, they are supposed to be empty.

The idea is you start with those empty files and add the code in the tutorial. The finished version is at: https://github.com/mdn/learning-area/tree/main/javascript/asynchronous/workers/finished.

Or is there some other problem here?

**Comment by StephaneRegnie** [comment]
@wbamberg Yes, sure. No, not any other problem, I might have confused with another page of the tutorial. You can close the issue. Thanks

**Comment by wbamberg** [comment]
OK, thanks, and let us now if you do spot anything else (a lot of this content has been reworked lately so it's not at all unlikely for some links to have got messed up).

**Comment by StephaneRegnie** [comment]
👍
