### ISSUE TITLE
"Template literals (Template strings)": article uses the odd term “expression interpolation”

### ISSUE THREAD

**Issue by HelmZalee** [mdn/content#13994]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

#### What information was incorrect, unhelpful, or incomplete?
The section heading (and ID) **Expression Interpolation**

#### Specific section or headline?
**Expression Interpolation**

#### What did you expect to see?
I suspect the author meant **Expression _Interpretation_**.

#### Did you test this? If so, how?
Thought about how I might _interpolate_ an expression....couldn't come up with anything.  I can really only _interpolate_ between two points.  I can, however, _interpret_ an expression.

Within that section, I might have written "Authors can embed executable expressions in a Template Literal.  The syntax to embed an expression _ex_ is ${ex}.  The expression ${ex} is termed a _placeholder_."

In any event, it is difficult to see a justification for Interpolation.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/template_literals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/template_literals/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by hamishwillee** [comment]
No, this text is correct - see https://en.wikipedia.org/wiki/String_interpolation . What it means is to expand out a placeholder to get the final string.

You might argue that this should be more precisely defined though, so I will leave this open.

**Comment by HelmZalee** [comment]
Wow.  I have been using the word for 60+ years, and only ever knew the mathematical usage: “To estimate the value of a function between two tabulated points.” (Wiktionary).  From the same source: in computing, “During the course of processing some data, and in response to a directive in that data, to fetch data from a different source and process it in-line along with the original data.” (L inter, between + polire, to polish.)

 

I stand firmly corrected!  Took awhile.  Thank you!

**Comment by sideshowbarker** [comment]
@HelmZalee Thanks for raising this — I’ve opened #13995 with some refinements to that article.

@hamishwillee 
> No, this text is correct - see [en.wikipedia.org/wiki/String_interpolation](https://en.wikipedia.org/wiki/String_interpolation) . What it means is to expand out a placeholder to get the final string.

Right — I think one thing that’s a cause of confusion in the article is that it has a section titled “Expression interpolation” that should rather be “String interpolation” (for consistency with the term of art that’s used for the everywhere else).

> You might argue that this should be more precisely defined though, so I will leave this open.

In #13995 I’ve tried to make it all more precise

**Comment by sideshowbarker** [comment]
@HelmZalee Thanks for raising this — I’ve opened #13995 with some refinements to that article.

@hamishwillee 
> No, this text is correct - see [en.wikipedia.org/wiki/String_interpolation](https://en.wikipedia.org/wiki/String_interpolation) . What it means is to expand out a placeholder to get the final string.

Right — I think one thing that’s a cause of confusion in the article is that it has a section titled “Expression interpolation” that should rather be “String interpolation” (for consistency with the term of art that’s used for the everywhere else).

> You might argue that this should be more precisely defined though, so I will leave this open.

In #13995 I’ve tried to make it all more precise

**Comment by HelmZalee** [comment]
I think there are a few things that could be done to clarify and simplify.  But I just looked at the link (13995) and understand nothing whatever of the process.  I shall leave it alone 😊.  Probably just as well…

 

I’ll add that the word “interpolation” is frequently used in math in a somewhat different sense.  Well, different until one looks at the etymology.  The word was so very familiar to me I did not feel compelled to look it up.  A lesson.

**Comment by hamishwillee** [comment]
@HelmZalee OK, I've merged @sideshowbarker PR - it addresses your issue and is much better written.

FYI only
1. Thanks for raising this. Anything that can confuse one user is a sign of a potential issue.
2. PR process is that you check that the change raised fixes your concerns. There are two tools for this:
   - The files tab in the PR shows the changes: https://github.com/mdn/content/pull/13995/files
   - The preview urls https://github.com/mdn/content/pull/13995#issuecomment-1071992335 show how the page will look afterwards.
   - From those two you decide if you like the text. You can add comments on the PR if you want. You and the PR author chat and eventually agree you are happy - it gets merged.

Cheers
H
