### ISSUE TITLE
Issue with "Introducing workers": code typo

### ISSUE THREAD

**Issue by Preacher06** [mdn/content#13997]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing_workers

#### What information was incorrect, unhelpful, or incomplete?
In line 7 of main.js of Prime generation with a worker, 
document.querySelector('#generate-primes') needs to be changed  to document.querySelector('#generate') as the id for that particular button in index.html is given as 'generate'.

#### Specific section or headline?
Prime generation with a worker

#### What did you expect to see?
document.querySelector('#generate')

#### Did you test this? If so, how?
The id for that particular button in index.html is given as 'generate', due to this, we are trying to access an event listener on null

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/introducing_workers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing_workers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/introducing_workers/index.md
* Last commit: https://github.com/mdn/content/commit/ea032ab86280848d3842a7e4455b831ea2545603
* Document last modified: 2022-03-15T02:11:20.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #13998 with a fix

After that fix is merged, this issue will automatically be marked as resolved, and closed.
