### ISSUE TITLE
Where to put the ItemComponent selector not clear

### ISSUE THREAD

**Issue by Ritterstahl** [mdn/content#14004]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_item_component

#### What information was incorrect, unhelpful, or incomplete?
"To use the ItemComponent in AppComponent, put the ItemComponent selector in the AppComponent template. "

#### Specific section or headline?
Use the ItemComponent in the AppComponent

#### What did you expect to see?
Specific instruction on where to paste the code in this section

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/angular_item_component`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_item_component
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/angular_item_component/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by Prathapkarumanchi** [comment]
I know you are confused, I will help you.

First of all I hope you are following the tutorial from the start - starting from creating the app.component.ts
[Beginning our Angular todo list app](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_todo_list_beginning)

Next step is to generate the item.component, After generating item component it's time for you to make some change to the app.component like adding, removing and saving functionality to your ToDo App.

[Use the ItemComponent in the AppComponent](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_item_component#use_the_itemcomponent_in_the_appcomponent) <-- what this section tells you is...

```
@Component({
  selector: 'app-item',
  templateUrl: './item.component.html',
  styleUrls: ['./item.component.css']
})

```

This is your child selector **selector: 'app-item',**
_To use the ItemComponent in AppComponent, put the ItemComponent selector in the AppComponent template._ 


The following is your App component template, now you need to add child selector into your app component.
```
<div class="main">
  <h1>My To Do List</h1>
  <h2>What would you like to do today?</h2>

  <ul>
    <li *ngFor="let item of items">{{item.description}}</li>
  </ul>
</div>
```

To Add child selector ie (ItemComponent) into AppComponent, you need to use the selector like this `<app-item></app-item>`

```
<ul>
  <li *ngFor="let item of items">
    <app-item (remove)="remove(item)" [item]="item"></app-item>
  </li>
</ul>
```

I hope this is clear to you, if you need further clarification please comment.

**Comment by Prathapkarumanchi** [comment]
@Ritterstahl FYR - https://stackblitz.com/edit/angular-ivy-ubxhqy

**Comment by Josh-Cena** [comment]
I believe there's no action needed here, because the decorator code is not meant to pasted anywhere—it's showing existing code that should be recognizable by readers who have followed along the tutorial. The next paragraph makes it clear that `app.component.html` needs to be updated.
