### ISSUE TITLE
Small typo in letter case of "General Knowledge" for 'Locale' in Glossary

### ISSUE THREAD

**Issue by tannerdolby** [mdn/content#1401]
While submitting a PR to add a 'Literal' page to the list of items in the Glossary. I noticed that the `index.html` page for `Locale` contained a few small letter case typos (or maybe intended).

```html
<h2 id="Learn_more">Learn more</h2>

<h3 id="General_Knowledge">General Knowledge</h3>
```

The `id` and innerHTML for the `<h3>` tag are both uppercase. Where in the other Glossary pages, the `id`'s are lowercased for the second word like `id="General_knowledge"` and the innerHTML takes the same letter case convention `>General knowledge</h3>`

This might be intended to keep both words uppercased, but in terms of consistency, I wanted to bring it up in case it did need to be fixed. I'm happy to submit a PR and fix it (if needed).

**Comment by hamishwillee** [comment]
Thanks @tannerdolby! The convention is that the heading is sentence capitalised, and the id follows that. So if you could add a PR to change these to `<h3 id="General_knowledge">General knowledge</h3>` that would be correct.

@chrisdavidmills Did I see somewhere that IDs are being globally changed to be all lower-case?

**Comment by tannerdolby** [comment]
Your welcome @hamishwillee! Yeah that's what I originally thought the naming convention was. I will add a PR to fix this for the `Locale` page. I'm not sure if this error occurs anywhere else in Glossary pages, just saw this one while creating a page for `Literal` (which is nearby the Locale page).

**Comment by hamishwillee** [comment]
Thanks @tannerdolby . You can always change heading text, but it might be worth waiting for Chris to respond regarding the anchor.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills Effectively this is the same question as #1356. What is the meaning of [yari 2524](https://github.com/mdn/yari/issues/2524)? It sounds like yari automatically is making all anchors into all lower case - shouldn't we do that in the source too?

Yes, this is correct; it converts them to lower case at runtime, which was breaking a bunch of fragment links, so @peterbe started converting such links to use lower case. I only discovered this the other day. We could do that in the source too, but it sounds like a lot of work for something that the build process just does automatically. Then again it is somewhat confusing.

**Comment by tannerdolby** [comment]
Thanks for the heads up @chrisdavidmills! I remember a little while ago when @peterbe started converting the links or `id`'s to use lower case. I agree, it could be manually updated in the source, but that would be quite a lot of work for something that is being handled by the build process. It is confusing to have differing results from the source and live site, but I don't see it as a "huge" issue.

If you decide that the source needs to be updated, I'm happy to slowly but surely help to get things updated.

**Comment by hamishwillee** [comment]
@tannerdolby So in summary, you can change the heading to sentence capitalisation and the id/anchor to same.

@chrisdavidmills FWIW I think it is confusing. An author shouldn't have to know that yari does something special to get links to work. We would be better making all anchors and links all-lower-case globally.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills FWIW I think it is confusing. An author shouldn't have to know that yari does something special to get links to work. We would be better making all anchors and links all-lower-case globally.

Yeah, I think I agree with this.

**Comment by hamishwillee** [comment]
@chrisdavidmills FYI 
- I've been involved in a parallel discussion with @sideshowbarker on this [here](https://github.com/mdn/content/pull/1356#issuecomment-763166890). 
- Right now his testing shows canonically that Yari generates IDs that exactly match the casing/text of the heading element text content character-for-character (with the spaces replaced by _ underscores).
- I stand by my preference that Yari would lower case anchors :-).

**Comment by chrisdavidmills** [comment]
Do we have a yari issue about this yet? If not, I'd start there.

**Comment by tannerdolby** [comment]
I'm not sure there is a Yari issue about this yet. I know when @peterbe was doing work on creating direct links out of all `<h2>` and `<h3>` tags, I think I remember this being talked about somewhat.

**Comment by tannerdolby** [comment]
With the Glossary,  there a quite a large number of  "General Knowledge" spots in IDs and in `<h3>` tags innerHTML

```git
tannerdolby:content TannerDolby$ git grep -n "General_Knowledge"
files/en-us/glossary/atag/index.html:14:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/caldav/index.html:13:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/cms/index.html:14:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/cookie/index.html:16:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/doctype/index.html:16:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/domain_name/index.html:14:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/ipv4/index.html:17:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/ipv6/index.html:16:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/keyword/index.html:16:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/netscape_navigator/index.html:17:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/node.js/index.html:18:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/object/index.html:14:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/pdf/index.html:14:<h3 id="General_Knowledge">General Knowledge</h3>
:...skipping...
files/en-us/glossary/atag/index.html:14:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/caldav/index.html:13:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/cms/index.html:14:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/cookie/index.html:16:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/doctype/index.html:16:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/domain_name/index.html:14:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/ipv4/index.html:17:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/ipv6/index.html:16:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/keyword/index.html:16:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/netscape_navigator/index.html:17:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/node.js/index.html:18:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/object/index.html:14:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/pdf/index.html:14:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/protocol/index.html:13:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/ril/index.html:17:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/seo/index.html:30:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/syntax_error/index.html:15:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/tag/index.html:14:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/three_js/index.html:15:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/ui/index.html:13:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/webdav/index.html:24:<h3 id="General_Knowledge">General Knowledge</h3>
files/en-us/glossary/whatwg/index.html:18:<h3 id="General_Knowledge">General Knowledge</h3>
```
I'd be happy to slowly start tackling manually fixing these in the source, but let me know your thoughts @chrisdavidmills

**Comment by chrisdavidmills** [comment]
Hrm, this one is kinda still open....I dunno, we might want to consider automating these?

**Comment by peterbe** [comment]
Can someone explain to me what the problem (still) is? 
Case shouldn't matter no more. But we've got some more pages to apply fixes for.

**Comment by tannerdolby** [comment]
@peterbe I think the problem was just that some tags in the source have IDs and innerHTML like `<h3 id="General_Knowledge">General Knowledge</h3>` when the naming convention should be first word upper case and second word lower case. 

Then @chrisdavidmills mentioned that the build process is converting those IDs to lowercase when the direct links are created for each sub heading

```html
<h3 id="general_knowledge"><a href="#general_knowledge" title="Permalink to General knowledge">General knowledge</a></h3>
```

So I guess the "problem" would be that the IDs in the source should match the naming conventions in the live site or at least all follow the same naming convention of `id="General_knowledge"` since they will be converted to lower case at build time anyways. Lastly, the innerHTML for the subheadings should follow the first word upper case second word lowercase since all the other ones do in Glossary.

**Comment by peterbe** [comment]
A ha! Yeah, the case of the `id` no longer matters at all. So what's left, basically, is the English prose/grammer/consistency question on the content itself.

**Comment by tannerdolby** [comment]
Yep! Since the `id` no longer matters, it's just the grammar/consistency question on the content. When I say content, I'm referring to the `innerHTML` of the sub headings like `<h3 ...>General knowledge</h3>`. 

Since there are many of these occurrences throughout `**/glossary/` would you like me to start slowly pruning away the `General Knowledge` inside the `<h3>` tags by changing it to `General knowledge` and go from there? Or would you rather it be automated with some code?

**Comment by peterbe** [comment]
> me to start slowly pruning away the `General Knowledge` inside the `<h3>` tags by changing it to `General knowledge` and go from there? Or would you rather it be automated with some code?

Do a search-and-replace in your IDE for the content. But keep it to one tree (i.e. `files/en-us/glossary/`). Let's not automate this. (not to say we couldn't in some distant future)

**Comment by tannerdolby** [comment]
Got it. I will do a search-and-replace for these occurrences within `files/en-us/glossary/` and create a new branch but reference this issue in the "Fixes X" part. Sounds good!
