### ISSUE TITLE
Issue with "Third-party APIs": (Simple Mapquest API example not working)

### ISSUE THREAD

**Issue by Preacher06** [mdn/content#14024]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs

#### What information was incorrect, unhelpful, or incomplete?
Broken link - Simple Mapquest API example in What are third party APIs

#### Specific section or headline?
What are third party APIs?

#### What did you expect to see?
Simple Mapquest API example link is not working

#### Did you test this? If so, how?
ttps://mdn.github.io/learning-area/javascript/apis/third-party-apis/mapquest/live/index.html - file not found (404)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/third_party_apis`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/client-side_web_apis/third_party_apis/index.md
* Last commit: https://github.com/mdn/content/commit/b9bf1650df6a57e70415fb51d87b559d103fd141
* Document last modified: 2022-03-09T19:26:32.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing, @Preacher06 ! https://github.com/mdn/content/pull/14035 should fix this.
