### ISSUE TITLE
"WorkerGlobalScope.importScripts()": Which MIME types are valid for imported scripts?

### ISSUE THREAD

**Issue by scunliffe** [mdn/content#14020]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts

#### What information was incorrect, unhelpful, or incomplete?
The docs indicate that a network error will occur if an invalid mimetype is specified for the imported scripts. It isn't clear here if "all" JavaScript mimetypes are valid or if *only* the one specified is. e.g. are both "text/javascript" and "application/javascript" valid?

#### Specific section or headline?
Exceptions

#### What did you expect to see?
Clear info on which mimetypes are valid.

#### Did you test this? If so, how?
No, trying to debug and understand if the type I'm supplying is valid (and my errors are elsewhere, or if this is the root cause)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/workerglobalscope/importscripts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/workerglobalscope/importscripts/index.md
* Last commit: https://github.com/mdn/content/commit/93ae23dec42bba9d71d6f1ed45668d8d26847e9c
* Document last modified: 2022-02-18T09:26:54.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14053 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
