### ISSUE TITLE
"SerialPort.setSignals()": the properties of the options are wrong

### ISSUE THREAD

**Issue by RumbleballTheReal** [mdn/content#14027]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SerialPort/setSignals

#### What information was incorrect, unhelpful, or incomplete?
the properties of the options are wrong

#### What did you expect to see?
- dataTerminalReady
  Data Terminal Ready (DTR)
- requestToSend
  Request To Send (RTS)
- break
  Break
see:   https://wicg.github.io/serial/#serialoutputsignals-dictionary

#### Did you test this? If so, how?
By using the serial API

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/serialport/setsignals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SerialPort/setSignals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/serialport/setsignals/index.md
* Last commit: https://github.com/mdn/content/commit/a2a45a0aec877e97ec64d9ddcd5ea9c95daef0d3
* Document last modified: 2021-11-19T00:06:12.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve raised #14050 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
