### ISSUE TITLE
"Images, media, and form elements": discussion of object-fit doesn’t state that when used on images, the image needs to have a width and height set in CSS

### ISSUE THREAD

**Issue by MPiland** [mdn/content#14023]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_media_form_elements

#### What information was incorrect, unhelpful, or incomplete?
When discussing `object-fit`, it wasn't stated that when used on images, the image needs to have a `width` and `height` set in the CSS style sheet.

#### Specific section or headline?
Sizing images

#### What did you expect to see?
When doing the Self Assessment, I wasn't able to get object-fit to work until I Googled why and found an answer on StackOverflow that the img needs to have a width and height set in the CSS sheet.

#### Did you test this? If so, how?
I tested in the live example and my own editor. I first tried to using just a width and just a height with object-fit and the image did not change. It wasn't until I had both did it affect the image.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/images_media_form_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_media_form_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/images_media_form_elements/index.md
* Last commit: https://github.com/mdn/content/commit/295e508da72ff83272a3b1ffa69a72cfeffcebde
* Document last modified: 2022-02-01T03:06:25.000Z

</details>

**Comment by Prathapkarumanchi** [comment]
@MPiland if you scroll down a little in the document you will find an interactive section where it highlights styles.
yes you are right that if you want to control image to fit into the box you may have to use `width` attribute inside an image,

But it would be wise to use *CSS styles* to keep the image size to 100% instead of adding inline.

example: 
```
 img {
  width: 100%;
  height: 100%;
}
```

**Comment by MPiland** [comment]
@Prathapkarumanchi 
The text reads

>You can make other choices about images inside containers. For example, you may want to size an image so it completely covers a box.
>
>The [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) property can help you here. When using `object-fit` the replaced element can be sized to fit a box in a variety of ways.
>
>Below we have used the value `cover`, which sizes the image down, maintaining the aspect ratio so that it neatly fills the box. As the aspect ratio is maintained, some parts of the image will be cropped by the box.

This doesn't mention anywhere that a `height` and `width` attribute are required for the img style in the CSS file is what I'm getting at. So, when doing the test assessment, the person would get stuck on the part about the photo fitting in the box and cropped because the test only says

>In this task, you have an image that is overflowing the box. We want the image to scale down to fit inside the box without any extra white space, but we do not mind if some part of the image is cropped.

Which would a user would assume it can be achieved with only a `width` attribute and (without prior knowledge of both attributes being required) `object-fit: contain` which is not the case. So, putting in the learning about the requirement for both attributes would help clear that up and enhance the learning.
