### ISSUE TITLE
Issue with "The building blocks of responsive design": (short summary here please)

### ISSUE THREAD

**Issue by MPiland** [mdn/content#14043]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Responsive/responsive_design_building_blocks

#### What information was incorrect, unhelpful, or incomplete?
Third paragraph has a link to a discussion about **Responsive design versus adaptive design** but it leads to a page not found [here](https://developer.mozilla.org/en-US/docs/Web/Apps/app_layout/Responsive_design_versus_adaptive_design).

#### What did you expect to see?
A page with a discussion about the topic.

#### Did you test this? If so, how?
Yes, but clicking the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/progressive_web_apps/responsive/responsive_design_building_blocks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Responsive/responsive_design_building_blocks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/responsive/responsive_design_building_blocks/index.md
* Last commit: https://github.com/mdn/content/commit/473efa32fe17feb192ef6ec3a15ca4f767006051
* Document last modified: 2022-01-24T11:26:15.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14044 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
