### ISSUE TITLE
Issue with "yield": Page link `legacy generator function` missing (404)

### ISSUE THREAD

**Issue by mystiquewolf** [mdn/content#14059]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield

#### What information was incorrect, unhelpful, or incomplete?
Page link `legacy generator function` missing right at top of article

#### Specific section or headline?
Right at the top of article

#### What did you expect to see?
The link to work

#### Did you test this? If so, how?
It doesn't work.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/yield`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/yield/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for cathing this — I’ve opened #14067 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
