### ISSUE TITLE
"JavaScript data types and data structures": code in example of using Number.MAX_SAFE_INTEGER doesn’t actually use Number.MAX_SAFE_INTEGER

### ISSUE THREAD

**Issue by yin1999** [mdn/content#14068]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures

#### What information was incorrect, unhelpful, or incomplete?

Description does not match code block.

![image](https://user-images.githubusercontent.com/15844309/159146046-f512b43e-6622-46a2-a1b3-800bfa550994.png)

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#bigint_type

#### What did you expect to see?

the description could match the code block, and compare with `Number Type`

![image](https://user-images.githubusercontent.com/15844309/159146260-4441fad8-7679-48a6-8520-81417275bc7f.png)

#### Did you test this? If so, how?

```js
// BigInt
> const x = BigInt(Number.MAX_SAFE_INTEGER);
9007199254740991n
> x + 1n === x + 2n; // 9007199254740992n === 9007199254740993n
false

// Number
> Number.MAX_SAFE_INTEGER + 1 === Number.MAX_SAFE_INTEGER + 2; // 9007199254740992 === 9007199254740992
true
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/data_structures`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/data_structures/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by yin1999** [comment]
If it looks fine, I'd like to working on it.

**Comment by sideshowbarker** [comment]
> If it looks fine, I'd like to working on it.

It looks fine, so please do go ahead and create a pull request

**Comment by yin1999** [comment]
Done in #14077
