### ISSUE TITLE
Issue with MDN Discourse Forum not loading

### ISSUE THREAD

**Issue by hosungc** [mdn/content#14065]
MDN URL: 
MDN Discourse forum Learning category: https://discourse.mozilla.org/c/mdn/learn/250

Test your skills: Loops:
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Loops

It seems the MDN Discourse forum Learning category will not load. I was on the "Test your skills: Loops" and I tried to follow the link to the forum but the forum would not load.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/test_your_skills_colon__loops`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Loops
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/test_your_skills_colon__loops/index.md
* Last commit: https://github.com/mdn/content/commit/672bace59f60c4931e5cdde8eb32919c924bd191
* Document last modified: 2022-03-14T00:26:56.000Z

</details>

**Comment by sideshowbarker** [comment]
https://discourse.mozilla.org/c/mdn/learn/250 is loading as expected for me in every browser I’ve tried.

Which browsers have you tried? Do you have the same loading problem in every browser?

When you open the browser devtools console, what messages do you see there?

**Comment by hosungc** [comment]
I just tried the link again in Chrome and it is now working for me. I guess the site was just down earlier. Thank you for taking a look!
