### ISSUE TITLE
"RTCRtpSender.replaceTrack()": example uses undeclared variable "PCs"

### ISSUE THREAD

**Issue by Abe2021** [mdn/content#1406]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/replaceTrack

#### What information was incorrect, unhelpful, or incomplete?
I don't think the example code is correct - it introduces "PCs" but what is this?

// example to change video camera, suppose selected value saved into window.selectedCamera...
```

navigator.mediaDevices
  .getUserMedia({
    video: {
      deviceId: {
        exact: window.selectedCamera
      }
    }
  })
  .then(function(stream) {
    let videoTrack = stream.getVideoTracks()[0];
    PCs.forEach(function(pc) {
      var sender = pc.getSenders().find(function(s) {
        return s.track.kind == videoTrack.kind;
      });
      console.log('found sender:', sender);
      sender.replaceTrack(videoTrack);
    });
  })
  .catch(function(err) {
    console.error('Error happens:', err);
  });

```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/rtcrtpsender/replacetrack`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/replaceTrack
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/rtcrtpsender/replacetrack/index.html
* Report started: 2021-01-17T17:33:03.954Z

</details>

**Comment by chrisdavidmills** [comment]
I'm assuming PCs = "Peer Connections" (see https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection), but it isn't good that the variable is being used in the example without any indication of how it is created. This should ideally be added to the snippet.

**Comment by jpmedley** [comment]
For whomever fixes this, while you're there, you might move the explanation out of a comment and into a `<p>`. As is, it scrolls off the screen.
