### ISSUE TITLE
"Create Author form": The text 'First name (Christian) last' is not clear

### ISSUE THREAD

**Issue by RobertHallsey** [mdn/content#14071]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_author_form

#### What information was incorrect, unhelpful, or incomplete?
input#first_name.form-control(type='text' placeholder='First name (Christian) last' name='first_name' required='true' value=(undefined===author ? '' : author.first_name)

#### Specific section or headline?
View https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_author_form#view

#### What did you expect to see?
The text 'First name (Christian) last' is not clear. It's first name, not last. Also, there is no need to mention '(Christian).' Muslims and Buddhists have first names too.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_author_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_author_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_author_form/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by hamishwillee** [comment]
This needed a little more work. Done in https://github.com/mdn/content/pull/14120

Thanks for reporting.
