### ISSUE TITLE
Issue with "Mixin": …

### ISSUE THREAD

**Issue by astef** [mdn/content#1407]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Mixin

#### What information was incorrect, unhelpful, or incomplete?
Broken link:  "[interface](https://developer.mozilla.org/en-US/docs/Glossary/interface)"

#### Specific section or headline?
First section

#### What did you expect to see?
Valid link, or no link.

#### Did you test this? If so, how?
Clicked on it.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/mixin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Mixin
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/glossary/mixin/index.html
* Report started: 2021-01-17T20:55:22.933Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @astef . This was an unwritten glossary page, hence the link not working. For now, I've just fixed it by removing the link: https://github.com/mdn/content/commit/d675b0160b13832bd0e1818b3672e11d34387128

Hopefully we can get someone to write a glossary page for interface in the future.
