### ISSUE TITLE
Content bug: Description of focus events matches current spec but not reality

### ISSUE THREAD

**Issue by danburzo** [mdn/content#14084]
## What page(s) did you find the problem on?

* [focus event](https://developer.mozilla.org/en-US/docs/Web/API/Element/focus_event)
* [blur event](https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event)
* [focusin event](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusin_event)
* [focusout event](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event)

## What is the problem?

The pages match [the text of the current spec](https://www.w3.org/TR/uievents/#events-focus-types), but browsers uniformly implement a different story, and it looks like [the spec is due for an update](https://github.com/w3c/uievents/pull/290) to match the implementations.

## What did you expect to see?

Should we be proactive and update the descriptions to match the soon-to-be-updated spec / current browser implementations?

**Comment by sideshowbarker** [comment]
> Should we be proactive and update the descriptions to match the soon-to-be-updated spec / current browser implementations?

Yes, it seems like we should. Would you be willing to put together a pull request?

I think what the pull request would need to do is to change the text to say _“Here’s what the spec says that browsers must do…”_ (which is what we have in the existing text) *“…but here’s what browsers actually do instead…”*

**Comment by danburzo** [comment]
Yep, definitely. I wonder if we can't just skip the _here's what the spec says_ part if the change in spec to match browser implementation is imminent. (@garykac, could you give us an insight on this?), but I can also just rewrite based on current spec, and update the description once it changes.

**Comment by danburzo** [comment]
See also the issues about adding the focus events to the HTML spec:

- https://github.com/whatwg/html/issues/3514
- https://github.com/whatwg/html/issues/4542

@sideshowbarker given the fact that the specs are still in flux, your call to add the note about _current spec vs. browsers_ sounds like the right way to go.

**Comment by sideshowbarker** [comment]
> Yep, definitely. I wonder if we can't just skip the _here's what the spec says_ part if the change in spec to match browser implementation is imminent

Alternatively, we could wait to merge the PR until after the spec change is made.

But I note that review of the spec PR was requested more than 3 months ago but apparently hasn’t happened yet — so I’m not sure it’d be prudent for us to assume the spec change is imminent. Seems like we should wait to hear from @garykac.

**Comment by sideshowbarker** [comment]
> @sideshowbarker given the fact that the specs are still in flux, your call to add the note about _current spec vs. browsers_ sounds like the right way to go.

OK (though I guess it’s still possible the spec change might get merged before we end up getting our PR merged here)
