### ISSUE TITLE
"Detecting device orientation": in Orientation example, x and y axis are switched

### ISSUE THREAD

**Issue by izderadicka** [mdn/content#14085]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Device_orientation_events/Detecting_device_orientation

#### What information was incorrect, unhelpful, or incomplete?
In Orientation example x and y axis are switched.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/Device_orientation_events/Detecting_device_orientation#orientation_example

#### What did you expect to see?
If you try example ball is not moving according to device rotation  - but in perpendicular direction - e.g I tip device away , but ball goes  left, I tilt left, but ball goes forward.

#### Did you test this? If so, how?
Mobile browser - FF and Chrome

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/events/detecting_device_orientation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Events/Detecting_device_orientation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/events/detecting_device_orientation/index.md
* Last commit: https://github.com/mdn/content/commit/43b1434a8d4feadb6733fd580ae5e382c808d142
* Document last modified: 2022-02-01T03:01:09.000Z

</details>

**Comment by wbamberg** [comment]
I haven't tried the example, but I think you are right.

The diagram in https://developer.mozilla.org/en-US/docs/Web/Events/Orientation_and_motion_data_explained#device_coordinate_frame shows x and y axes as they are understood by device orientation. You could see how:

- "rotating around the y axis" ([`gamma`](https://developer.mozilla.org/en-US/docs/Web/API/DeviceOrientationEvent/gamma)) is tilting left/right, which would mean adjusting `x`, so the ball ought to roll left/right, while
- "rotating around the x axis" ([`beta`](https://developer.mozilla.org/en-US/docs/Web/API/DeviceOrientationEvent/beta)) is tilting up/down, so the ball ought to roll up/down, which would mean adjusting `y`.
