### ISSUE TITLE
Issue with "Date.prototype.toSource()": Missing 'obsolete' icon before toSource() link.

### ISSUE THREAD

**Issue by stenito** [mdn/content#14082]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toSource

#### What information was incorrect, unhelpful, or incomplete?

Method list of the Date object is missing the 'obsolete' icon before the toSource() method link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/tosource`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toSource
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/tosource/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14109 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
