### ISSUE TITLE
Incomplete information for Accept-CH page

### ISSUE THREAD

**Issue by summercms** [mdn/content#1408]
Related to this location: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-CH

This page is missing a huge amount of data, it seems to only cover: 

- DPR
- Viewport Width
- Width

Yet Client Hints cover a lot more, such as:

- Device Memory
- Rtt
- Downlink
- Ect
- Save-Data
etc.

I would like to see the MDN team update the information on the page to add these extra Client Hints and also update the Browser compatibility table.

Thanks.

**Comment by hamishwillee** [comment]
The page doesn't attempt to document everything - it links to the [Client Hints](https://developer.mozilla.org/en-US/docs/Glossary/Client_hints) glossary item where you are supposed to get information about all the headers it might work with.

I think the approach is right, but it should instead link to the list of supported headers at [HTTP/Headers#client_hints](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#client_hints).

The current list of headers on that page is: Accept-CH, Accept-CH-Lifetime ,Early-Data, Device-Memory, Save-Data, Viewport-Width, Width 

So it is missing DPR and Downlink. 

@ayumi-cloud What other ones do you know about?
- I can't see any more in https://tools.ietf.org/html/draft-grigorik-http-client-hints-03
- I can't see any info about RTT

Once we have a list we can update that page, and also look at the BCD for ACCEPT_CH

-

**Comment by ayumi-cloud** [comment]
> What other ones do you know about?

See here: https://wicg.github.io/client-hints-infrastructure/#find-client-hint-value-section

There is also [Lang Client Hint](https://github.com/WICG/lang-client-hint) which has been deprecated, not sure if you want to also mention that in MDN?

> I can't see any info about RTT

Use this info: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/client-hints#rtt

I find that page useful about the blockquotes talking about fingerprinting, in the rtt case:

> Note: The value of RTT is rounded to the nearest 25 milliseconds to prevent fingerprinting.

Is the [Early-Data](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Early-Data) a client hint? I thought it was a separate thing like [103 Early Hints](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103)

Thanks.

**Comment by Ryuno-Ki** [comment]
> There is also [Lang Client Hint](https://github.com/WICG/lang-client-hint) which has been deprecated, not sure if you want to also mention that in MDN?

In my observation, those things tend to be mentioned, but also marked as deprecated.
This way, it will become discoverable but also inform, that it shouldn't be used.

**Comment by hamishwillee** [comment]
Thanks. Hope to start thinking about this on Monday.

**Comment by ayumi-cloud** [comment]
Come across another new client hint being developed by Google called: [Critical-CH](https://tools.ietf.org/html/draft-davidben-http-client-hint-reliability-00#section-3)

**Comment by ayumi-cloud** [comment]
Come across another new client hint being developed by Google called: `Critical-CH`

Links:

https://tools.ietf.org/html/draft-davidben-http-client-hint-reliability-02#section-3
https://github.com/WICG/client-hints-infrastructure/blob/master/reliability.md

**Comment by hamishwillee** [comment]
FYI I am not ignoring this, and happy for someone to take it on. Just "time poor". I will get to it at some point.

**Comment by hamishwillee** [comment]
Reopening. Still got some bits to do: https://github.com/mdn/content/pull/4907#issuecomment-851533679

**Comment by summercms** [comment]
Some more Client Hints that can be added to MDN.

## 1. Client Hint Reliability

https://datatracker.ietf.org/doc/html/draft-davidben-http-client-hint-reliability-03
https://chromestatus.com/feature/5555544540577792

Details | Link
---|---
The Critical-CH Response Header Field | https://datatracker.ietf.org/doc/html/draft-davidben-http-client-hint-reliability-03#section-3
The ACCEPT_CH Frame | https://datatracker.ietf.org/doc/html/draft-davidben-http-client-hint-reliability-03#section-4

## 2. User Preference Media Features Client Hints Headers

https://github.com/tomayac/user-preference-media-features-headers

The list of the client hints is modelled after the [user preference media features](https://drafts.csswg.org/mediaqueries-5/#mf-user-preferences) in [Media Queries Level 5](https://drafts.csswg.org/mediaqueries-5/#descdef-media-prefers-color-scheme).

| Client Hint                           | Allowed Values                                                                                                                                                                                                                                                                        | Corresponding User Preference Media Feature                                                             |
| ------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- |
| `Sec-CH-Prefers-Reduced-Motion`       | [`no-preference`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-prefers-reduced-motion-no-preference), [`reduce`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-prefers-reduced-motion-reduce)                                                                        | [`prefers-reduced-motion`](https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-motion)             |
| `Sec-CH-Prefers-Reduced-Transparency` | [`no-preference`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-prefers-reduced-transparency-no-preference), [`reduce`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-prefers-reduced-transparency-reduce)                                                            | [`prefers-reduced-transparency`](https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-transparency) |
| `Sec-CH-Prefers-Contrast`             | [`no-preference`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-prefers-contrast-no-preference), [`less`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-prefers-contrast-less), [`more`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-prefers-contrast-more),  [`custom`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-prefers-contrast-custom) | [`prefers-contrast`](https://drafts.csswg.org/mediaqueries-5/#prefers-contrast)                         |
| `Sec-CH-Forced-Colors`                | [`active`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-forced-colors-active), [`none`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-forced-colors-none)                                                                                                            | [`forced-colors`](https://drafts.csswg.org/mediaqueries-5/#forced-colors)                               |
| `Sec-CH-Prefers-Color-Scheme`         | [`light`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-prefers-color-scheme-light), [`dark`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-prefers-color-scheme-dark)                                                                                                | [`prefers-color-scheme`](https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme)                 |
| `Sec-CH-Prefers-Reduced-Data`         | [`no-preference`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-prefers-reduced-data-no-preference), [`reduce`](https://drafts.csswg.org/mediaqueries-5/#valdef-media-prefers-reduced-data-reduce)                                                                            | [`prefers-reduced-data`](https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-data)                 |

**Comment by hamishwillee** [comment]
Thanks @summercms . Do the above meet the requirement for documentation here: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Conventions_definitions#when_to_document_new_technologies ?

We also have to consider these cases: https://github.com/mdn/content/pull/4907#issuecomment-851533679

Anyway, if there are new whole "collections" like these then probably wroth having separate issues for each (once verified it is time to document them). The work could be shared better that way.

**Comment by summercms** [comment]
@hamishwillee 

> You should definitely consider documenting a new technology if:

> - It is specified in a specification document published under a reliable standards organization (such as W3C, WHATWG, Khronos, IETF, etc.), which has reached a reasonable level of stability (e.g. a W3C working draft or candidate recommendation, or the spec is looking to be fairly stable judging by the flow of issues filed against it).

Both are under Web Incubator CG (WICG)

> - It is implemented consistently in at least one browser, with other browser developers showing signs of interest (such as an active ticket or "intent to implement" process in effect).

Both are currently being added to Google Chrome.

---

Can open two separate issues for each - **let me know and I can open 2 issues.**

I have seen lately many new client hints being developed on the web, so MDN would probably like to add each one under a separate page to keep the doc's clean and not end up with a huge wall of text in the near future.

**Comment by hamishwillee** [comment]
FYI, slow progress, but I have nearly updated docs/BCD for the original headers in MDN. Some of these are now deprecated and have been replaced by [Responsive Image Client Hints](https://wicg.github.io/responsive-image-client-hints) - but those aren't yet in any browsers.

Next start thinking about these other new ones.

**Comment by hamishwillee** [comment]
@summercms Regarding https://github.com/mdn/content/issues/1408#issuecomment-857224431, My interpretation is that neither of these are ready for documentation. 
The relevant restriction is: **and is implemented somewhere**. Being in development is not good enough. To avoid having lots of churn on docs while a spec is still being "hardened" by real use, we wait until it is in a release build and there is some interest from other browsers. Often appearance in browser compatibility data is another good trigger.

For the same reason I won't be documenting [Responsive Image Client Hints](https://wicg.github.io/responsive-image-client-hints). However I will ask about the [User agent client hints talked about here](https://github.com/mdn/content/pull/4907#issuecomment-851533679), because they went into Chrome 89https://www.chromestatus.com/feature/5995832180473856

**Comment by chris-makaio** [comment]
Sorry for chiming in with a naive question, but why is CH Width marked deprecated? I can‘t find any references saying it is deprecated

**Comment by hamishwillee** [comment]
@chris-makaio If you mean https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Width , it is no longer in any current spec. It has been superseded in another spec, but the replacement has not yet appeared in any browser.

**Comment by himanshugarg** [comment]
Are more fixes expected here? The linked PR is merged.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/1408#issuecomment-1013676984

**Comment by hamishwillee** [comment]
Thanks guys - yes this was done, module minor changes around a Save-Data change that has not yet landed in any browser.
