### ISSUE TITLE
"See also" to "Related"

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#141]
Can _See also_ become 1 word from 2?

###### Examples

- Related ⭐
- Connected
- ...

https://www.google.com/search?q=related+synonym+list

## Example
https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#See_also

**Comment by sideshowbarker** [comment]
I also have a slight preference for *Related* rather than *See also*. I don’t feel strongly about it, but if we were to change it, it seems like now would be the time to do it — rather than later.

**Comment by chrisdavidmills** [comment]
I've not yet seen a strong enough reason to spend the time changing it, but I am happy to consider other arguments.

The best time to change this would be after we've released Yari. At that point, we can easily do a mass replace of all "See also" headings.

**Comment by mattiapontonio** [comment]
Yes, it's probably not a YARI issue but more editorial. Let's say that in my opinion the question is also (as well as cognitive load) the "giving orders or commands" vs "giving information", therefore perhaps also semantics.
