### ISSUE TITLE
Issue with "Shader Editor": (the notecard is out of date)

### ISSUE THREAD

**Issue by yin1999** [mdn/content#14122]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Shader_Editor

##### notecard

The notecard says:

```
Note: This tool has been deprecated and will soon be removed from Firefox
```

But this tool (Shader Editor) has been removed from firefox when [firefox 67 released](https://bugzilla.mozilla.org/show_bug.cgi?id=1342237) (Milestone: Firefox 67). So we should update the notecard.

##### youtube video

And we may also need to deal with the video(`{{EmbedYouTube("YBErisxQkPQ")}}`) in thie document (seems not available):

![image](https://user-images.githubusercontent.com/15844309/159223901-199298a1-be9a-44b7-9a00-fdb332cf7248.png)

Reference: mdn/translated-content#591

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/shader_editor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Shader_Editor
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/shader_editor/index.html
* Last commit: https://github.com/mdn/content/commit/5d8fbcb7e86afaae9504eda006c8ced7396b1d34
* Document last modified: 2021-04-28T23:00:48.000Z

</details>

**Comment by teoli2003** [comment]
@rumyra, @dipikabh Maybe we should delete (or archive) the documentation for this tool?

**Comment by Rumyra** [comment]
Yes agreed @teoli2003 - for this issue, rather than update we can remove the shader tool docs 👍

**Comment by dipikabh** [comment]
https://developer.mozilla.org/en-US/docs/Tools is now redirecting to Firefox documentation. I guess this got fixed after Daniel's [PR](https://github.com/mdn/content/pull/14140)?

**Comment by yin1999** [comment]
Thank you all~
