### ISSUE TITLE
Issue with "@layer": (short summary here please)

### ISSUE THREAD

**Issue by micahgodbolt** [mdn/content#14134]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@layer

#### What information was incorrect, unhelpful, or incomplete?
```css
@import(utilities.css) layer(utilities);
```

#### Specific section or headline?

Under Syntax
https://developer.mozilla.org/en-US/docs/Web/CSS/@layer#syntax

#### What did you expect to see?

```css
@import 'utilities.css' layer(utilities);
```

#### Did you test this? If so, how?

Import rules make it pretty clear https://developer.mozilla.org/en-US/docs/Web/CSS/@import#importing_css_rules

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/@layer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@layer/index.md
* Last commit: https://github.com/mdn/content/commit/3b56659b778cc6de2f3ddab53fbd850516f2a70b
* Document last modified: 2022-01-19T18:12:04.000Z

</details>

**Comment by Jennifer127** [comment]
Sent from my Huawei phone-------- Original message --------From: "Michael[tm] Smith" ***@***.***>Date: Tue, 22 Mar 2022, 3:46 AMTo: mdn/content ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [mdn/content] Issue with ***@***.***": (short summary here please) (Issue #14134)
Closed #14134 via #14143.
