### ISSUE TITLE
"Add to Home screen": with firefox on mobile, not working the popup. is possible only open the three dots menu and select install

### ISSUE THREAD

**Issue by eddymouse** [mdn/content#14133]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen

#### What information was incorrect, unhelpful, or incomplete?
I tested your fox demo page, with firefox on mobile, is not working the popup. is possible only open the three dots menu and select install.

#### What did you expect to see?
Open the popup to install the App

#### Did you test this? If so, how?
I tested it on my Samsung S7 with Firefox last version. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/progressive_web_apps/add_to_home_screen`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/add_to_home_screen/index.md
* Last commit: https://github.com/mdn/content/commit/8f164b688448a602df794f9094e9d4d039887639
* Document last modified: 2021-12-02T19:40:14.000Z

</details>

**Comment by bsmth** [comment]
Hi @eddymouse, thanks a lot for raising this one. It appears this has been fixed in #14419, so I'm going to close this as done. Thank you :)
