### ISSUE TITLE
Issue with "Basic native form controls": Potential typo in checkable items section

### ISSUE THREAD

**Issue by shaunsim15** [mdn/content#14138]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls

#### What information was incorrect, unhelpful, or incomplete?
The sentence currently reads:
The associated <label> is generally placed immediately after the radio button or checkbox...

If I am not mistaken, it should read:
The associated <label> is generally placed immediately **before** the radio button or checkbox...

I'm not sure what standard practice is as I'm new to programming, but in the examples on the same page, the label elements are before the corresponding input elements in the HTML.

#### Specific section or headline?
The section was "**Checkable items: checkboxes and radio buttons**".

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/basic_native_form_controls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/basic_native_form_controls/index.md
* Last commit: https://github.com/mdn/content/commit/84310960fad725ea705b47be08087c90ea075491
* Document last modified: 2022-02-19T06:20:20.000Z

</details>

**Comment by teoli2003** [comment]
Hi! Thanks for your report.

I think the info is correct. For checkboxes and radio buttons, the label is placed after, like here:

[ ] Label
[ ] Label.

**Comment by wbamberg** [comment]
But in the example code in the page, the label is given first:

https://github.com/mdn/content/blob/164f32652af3cf000b8f4932f455d3b6562b3c52/files/en-us/learn/forms/basic_native_form_controls/index.md?plain=1#L129-L147

...so this issue looks legit to me?

Couldn't we just say instead:

>  The associated label is generally placed immediately before or after the radio button or checkbox...

?
