### ISSUE TITLE
“Games” article: image is not readable, doesn’t have horizontal scrolling

### ISSUE THREAD

**Issue by goashir** [mdn/content#14149]
When open MDN, we see dozens of articles about "Responsive,PictureTag, ImageResponsive, figureTag, multiSourceImage, etc" but when it's your turn, you do strange things!
This image is not only readable also does not even have horizontal scrolling:
**https://developer.mozilla.org/en-US/docs/Games**
![Screenshot 2022-03-22 at 01-26-02 Game development MDN(4)](https://user-images.githubusercontent.com/18716709/159363648-2e9791f2-7453-4627-a73d-f0afb5e6d3f5.png)

This is not a subpage that is a small mistake, also its one of main pages

**Comment by wbamberg** [comment]
Thanks for filing! I files https://github.com/mdn/content/pull/15737 to remove this iframe.

> When open MDN, we see dozens of articles about "Responsive,PictureTag, ImageResponsive, figureTag, multiSourceImage, etc" but when it's your turn, you do strange things!

It is possible, and would be appreciated, for you to file issues without the snark. There are people who put a lot of work into this site.
