### ISSUE TITLE
Clarify meaning of "Links..." on new operator page

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mdn/content#1414]
https://github.com/mdn/content/blob/c74acbbd32f731931f94b4010b974c1b1bd2b370/files/en-us/web/javascript/reference/operators/new/index.html#L40-L41

**Comment by chrisdavidmills** [comment]
Page in question: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new
