### ISSUE TITLE
Issue with "Introducing workers": (index.html file with closing link tag)

### ISSUE THREAD

**Issue by galopyz** [mdn/content#14142]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing_workers

#### What information was incorrect, unhelpful, or incomplete?
In the index.html, link tag for stylesheet has a closing tag. This tag does not need a closing tag.

#### Specific section or headline?
<a href='https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing_workers#prime_generation_with_a_worker'>prime_generation_with_a_worker</a>

#### What did you expect to see?
Just a tag link tag itself like this: <link href="style.css"rel="stylesheet">

#### Did you test this? If so, how?
I opened it on my local device.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/introducing_workers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing_workers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/introducing_workers/index.md
* Last commit: https://github.com/mdn/content/commit/63a2e555d718a387d6dcee30cd3a27e593509bae
* Document last modified: 2022-03-18T05:27:57.000Z

</details>

**Comment by teoli2003** [comment]
I've added a parallel PR to fix the mdn/content page itself.

**Comment by galopyz** [comment]
I will just leave it open until your PR gets through and mdn/content shows the correct output.
