### ISSUE TITLE
Issue with "<meter>: The HTML Meter element": (WHATWG does not list the form attribute but MDN Web Docs does)

### ISSUE THREAD

**Issue by misanthrope54** [mdn/content#14146]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter

According to WHATWG html standard the <meter> element does not support the form attribute but it is listed in Web Docs. I'm not sure which is right. I posted this question in the WHATWG chat but I was told to open an issue here.

Attributes section

Not sure

No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/meter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/meter/index.md
* Last commit: https://github.com/mdn/content/commit/09bc26fb8264fff6396e75b45481187866cb9493
* Document last modified: 2022-01-20T18:54:53.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #14158 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
