### ISSUE TITLE
Promote Fetch over XMLHttpRequest and stop using "AJAX"

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#14157]
MDN has lots of docs that mention/promote AJAX and explain how it is implemented using `XMLHttpRequest`. 

Two problems:
1. Fetch should be used instead of `XMLHttpRequest` because it is a lot simpler and results in better code. On quick scan the only downside of Fetch appears to be that it does not support progress notification (I have not checked if this is true or not in current version). There is a great doc here: https://jakearchibald.com/2015/thats-so-fetch/
2. AJAX was an early term for using javascript to fetch new data and dynamically update HTML. That is such an accepted pattern now that the term feels very anachronistic and isn't really even needed.

By grep, "XMLHttpRequest" is about 223 files, while "AJAX" (66 files).
I think this is going to be a bit of a project to resolve. There are some easy wins, but in particular the use of `XMLHttpRequest` is deeply embedded in a lot of docs.

For the Ajax part, would be good to start looking at these entry points:
 - [Glossary: Ajax](https://developer.mozilla.org/en-US/docs/Glossary/AJAX) - could be made stronger statement for Fetch and indicate that is isn't broadly used any more.
- [References > Developer guides > Ajax](https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX)
- [References > Developer guides > Ajax > Getting Started](https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started)
  
https://developer.mozilla.org/en-US/docs/Glossary/AJAX

**Comment by wbamberg** [comment]
> [References > Developer guides > Ajax](https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX)
> [References > Developer guides > Ajax > Getting Started](https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started)

@Josh-Cena consolidated these in https://github.com/mdn/content/pull/27568 🎉 .

So I'm looking at https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX and thinking, this just reads like a "how to use XHR" to me, which we already have in https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Using_XMLHttpRequest.

I guess to me there is a separate meaning of "Ajax" which is not just "how to make HTTP requests from JavaScript" but which is about the whole idea of building a web app around dynamic updates. We cover that in https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data (which has already been properly updated to use Fetch).

So between those two, don't we already have good enough coverage of this topic? Can we just delete https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX and redirect to https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data ?

**Comment by hamishwillee** [comment]
> So between those two, don't we already have good enough coverage of this topic? Can we just delete https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX and redirect to https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data ?

Yes. I was going to say, "but you should update the AJAX glossary" so the term is captured still, but I see you sorted that already.

**Comment by estelle** [comment]
> So between those two, don't we already have good enough coverage of this topic? Can we just delete https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX and redirect to https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data ?

Yes! We talked about this during the #writing-docs meeting earlier today. The consensus:  Remove it! 

It’s an old guide that doesn’t bring much. A comment should be added to the XHR pages indicating "this was called AJAX" with a link to the AJAX glossary page from that text. Also, we need to ensure glossary term "AJAX" no longer links to this page; instead the glossary page (and all other links that pointed to the guide) get updated so they linkback to the relevant Fetch/XHR pages.

**Comment by wbamberg** [comment]
These are the remaining pages that contain "Ajax":

```
games/techniques/2d_collision_detection
glossary/ajax
glossary/http
glossary/javascript
glossary/polyfill
glossary/spa
glossary/xmlhttprequest
learn/javascript/client-side_web_apis/fetching_data
learn/javascript/client-side_web_apis/introduction
learn/server-side/first_steps/client-server_overview
learn/tools_and_testing/cross_browser_testing/javascript
mdn/kitchensink
mozilla/firefox/releases/3/wai_aria_live_regions_api_support
mozilla/firefox/releases/3.5
web/accessibility/aria/aria_screen_reader_implementors_guide
web/api/css_object_model
web/api/document/getelementbyid
web/api/fetch_api/using_fetch
web/api/filereader
web/api/response
web/api/webgl_api/tutorial/adding_2d_content_to_a_webgl_context
web/api/xmlhttprequest_api
web/http/headers/access-control-allow-credentials
web/javascript/reference/statements/switch
```

Of course a lot of these are going to be legit usages.
