### ISSUE TITLE
Add some information about Extranets and Intranets

### ISSUE THREAD

**Issue by ghost** [mdn/content#1416]
At this moment MDN has zero information about those things. I think it's a good idea at least mention them somewhere. For example in a small section on this page https://developer.mozilla.org/en-US/docs/Learn/Common_questions/How_does_the_Internet_work

Or create two glossary pages for them.

**Comment by hamishwillee** [comment]
I quite like the idea of a section in this document; possibly with cross linking to concepts like NAT. @Torhuo want to take a first shot at writing something?

**Comment by Torhuo** [comment]
@hamishwillee Unfortunately my bad knowledge of the English language doesn't allow me write something with good quality.

**Comment by chrisdavidmills** [comment]
To whoever fixes this, a small section needs to be added to the referenced page covering extranets and intranets. Not too much detail, just enough for the reader to undersand what they are.

**Comment by Blakelist7** [comment]
@chrisdavidmills if no one is working of this a newbie like me could give it a shot?

**Comment by Blakelist7** [comment]
@chrisdavidmills please Review my PR

**Comment by Blakelist7** [comment]
Hey, @sideshowbarker I think we can close this issue now.

**Comment by sideshowbarker** [comment]
> Hey, @sideshowbarker I think we can close this issue now.

OK

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/4678
