### ISSUE TITLE
Issue with ":disabled": The result is not being shown.

### ISSUE THREAD

**Issue by developerubaid** [mdn/content#14162]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled

#### What information was incorrect, unhelpful, or incomplete?
The result is not being shown.

#### Specific section or headline?
Result

#### What did you expect to see?
Markup and Styling of Form

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_disabled`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_disabled/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by teoli2003** [comment]
It works fine for me, when I toggle the checkbox the second row of inputs is disabled/enabled as expected.

**Comment by kentinHogbonouto** [comment]
it work properly for me too

**Comment by teoli2003** [comment]
Closing per comments. Feel free to reopen if we are mistaken.
