### ISSUE TITLE
Issue with "Page Visibility API": see also links broken

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#14168]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API#see_also

#### What information was incorrect, unhelpful, or incomplete?
> * Description of the [Page Visibility API](https://blogs.msdn.com/b/ie/archive/2011/07/08/using-pc-hardware-more-efficiently-in-html5-new-web-performance-apis-part-2.aspx) on the IEBlog.
> * Description of the [Page Visibility API](https://code.google.com/chrome/whitepapers/pagevisibility.html) by Google

Both the links now point to something else. Second one points to same w3 speck as the specification section does.

### What did you expect to see?
Remove the links if suitable replacements are not found.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/page_visibility_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/page_visibility_api/index.md
* Last commit: https://github.com/mdn/content/commit/8331519c861d1c990cad798045c3c240de05b810
* Document last modified: 2022-03-07T16:08:41.000Z

</details>

**Comment by teoli2003** [comment]
@jpmedley You had a list of google links to update. By any chance is there a modern google blog post (web.dev ?) about this API?

For the IEBlog, I think we should just remove the link (Edge is based on Chromium nowadays)

**Comment by MrBrain295** [comment]
We could replace the google link with [this](https://www.w3.org/TR/page-visibility/) because that is what it redirects to.

**Comment by jpmedley** [comment]
No. When Chrome 33 shipped, Chrome Developer relations was pretty new and didn't have much of a web presence.

**Comment by teoli2003** [comment]
> We could replace the google link with [this](https://www.w3.org/TR/page-visibility/) because that is what it redirects to.

The spec is linked under
