### ISSUE TITLE
Issue with "Test your skills: Loops": (missing live editor)

### ISSUE THREAD

**Issue by MPiland** [mdn/content#14184]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Loops

#### What information was incorrect, unhelpful, or incomplete?
All of the examples are missing the live editor

#### Did you test this? If so, how?
Tested in both Chrome and Edge

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/test_your_skills_colon__loops`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Loops
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/test_your_skills_colon__loops/index.md
* Last commit: https://github.com/mdn/content/commit/672bace59f60c4931e5cdde8eb32919c924bd191
* Document last modified: 2022-03-14T00:26:56.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! This is intentional, as the page says:

> You can try out solutions for the tasks below by downloading the code, putting it in an online tool such as [CodePen](https://codepen.io/), [jsFiddle](https://jsfiddle.net/), or [Glitch](https://glitch.com/), then working on the tasks. We didn't provide live editable versions of these tasks because of the risk of creating infinite loops and crashing the assessment page!

**Comment by MPiland** [comment]
@wbamberg Is it possible to make that last line stand out from the rest since? The reason is that block is on every page (minus that last line) so if anyone else is like me, we tend to just skip over it since it's the same content. Just an idea.

**Comment by wbamberg** [comment]
Yes, that's a good point.

What if that bit were in a separate note, like:

<img width="1046" alt="Screen Shot 2022-03-22 at 6 28 22 PM" src="https://user-images.githubusercontent.com/432915/159603882-20c9e0bc-d035-4569-836a-08bafcfa3b44.png">

?

**Comment by MPiland** [comment]
I think that would be perfect as it helps separate it from the usual note. Thanks!

**Comment by wbamberg** [comment]
I filed https://github.com/mdn/content/pull/14192 for this. Thanks for pointing it out!
