### ISSUE TITLE
"Using the Payment Request API": demo links broken

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#14197]
MDN URL: https://5546.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Payment_Request_API/Using_the_Payment_Request_API#see_also

#### What information was incorrect?
> [Google PaymentRequest codelab](https://g.co/PaymentRequestCodeLab)

Gives 404.

> Ecommerce website demo and source code [VeggieShop](https://github.com/pjbazin/wpwg-demo)
Web Payment App demo and source code [WhiteCollar](https://github.com/pjbazin/wpwg-demo/tree/master/WhiteCollar)

There is no demo only .net code. `azurewebsites.net` domain is not available anymore so those demosites are gone.

#### What did you expect to see?
No broken links.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/payment_request_api/using_the_payment_request_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API/Using_the_Payment_Request_API
* GitHub URL: https://github.com/mdn/content/blob/5546-readability-accessibility-of-main-content/files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
* Last commit: https://github.com/mdn/content/commit/1783898ec8c5bede2f6745eb7f8d37b445ccc4c4
* Document last modified: 2022-01-06T18:14:53.000Z

</details>

**Comment by sideshowbarker** [comment]
Opened #14249 with a fix.
