### ISSUE TITLE
Issue with "Object-oriented programming": (short summary here please)

### ISSUE THREAD

**Issue by najish** [mdn/content#14199]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_programming

#### What information was incorrect, unhelpful, or incomplete?
There is problem with just return statement in the code at archery method.

#### Specific section or headline?

The return statement of archey method should be like this (return this.year > 1) but there it is (return this.year < 1) which is wrong. Thank you
#### What did you expect to see?

return this.year > 1;

#### Did you test this? If so, how?
Yeah

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/objects/object-oriented_programming`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_programming
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/object-oriented_programming/index.md
* Last commit: https://github.com/mdn/content/commit/200aa6aa564104f8cbe34f92277549d95cdf3a4c
* Document last modified: 2022-02-04T03:48:34.000Z

</details>

**Comment by wbamberg** [comment]
Thanks! -> https://github.com/mdn/content/pull/14200 .
