### ISSUE TITLE
Content bug: Add documentation for priority hints

### ISSUE THREAD

**Issue by pmeenan** [mdn/content#14208]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
https://developer.mozilla.org/en-US/docs/Web/API/Request

## Specific page section or heading?

attributes

## What is the problem?

* The `fetchpriority` attribute is missing from the `<img>`, `<script>`, `<link>` and `<iframe>` elements.
* The `priority` property is missing from the fetch JavaScript API (RequestInit and Request)

## What did you expect to see?

[Priority Hints](https://wicg.github.io/priority-hints/) is [shipping in Chrome 101](https://chromestatus.com/feature/5273474901737472) and the documentation for it is not on MDN yet.

## Did you test this? If so, how?

N/A

**Comment by jpmedley** [comment]
I've already reviewed his PR. Just waiting for his response.

**Comment by pmeenan** [comment]
@jpmedley, sorry, which PR is waiting on something from me?

**Comment by jpmedley** [comment]
I neglected to submit my review comments. Sorry about that.

**Comment by pmeenan** [comment]
Thanks all for the help with the reviews.
