### ISSUE TITLE
"Advance measure" glossary entry: you leave the page with more unknowns than you arrived with

### ISSUE THREAD

**Issue by Eric-Storm** [mdn/content#14201]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/advance_measure

#### What information was incorrect, unhelpful, or incomplete?

This glossary definition contains a net negative information.  By that, I mean that you leave the page with more unknowns than you arrived.

The glossary defines "advance measure" in terms of two other phrases, "advance width" and "advance height".  But the likelihood is, if the user doesn't know what "advance measure" is, they aren't going to know what either of these other two terms mean, either.

Further, neither "advance width" nor "advance height" have glossary definitions, leaving the user no obvious place to turn to figure out what these terms (or the original term) mean.

I have gathered, from some Internet searching, that this term has something to do with the width and height of the zero character in a font... but how the term "advance measure" relates to that is completely unclear.  (In other words, why is it called this?  Knowing why a term got applied is often key to understanding the term itself.)

#### What did you expect to see?
A definition explained in common enough terms that it did not require me to look up yet another term.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/advance_measure`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/advance_measure
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/advance_measure/index.md
* Last commit: https://github.com/mdn/content/commit/e752a8fe731fbdb9061e39a6e2b797a7ccb7e2b5
* Document last modified: 2022-01-19T17:57:58.000Z

</details>

**Comment by NiedziolkaMichal** [comment]
@Eric-Storm Could you check if [my definition](https://github.com/mdn/content/pull/14353) is good enough please?
