### ISSUE TITLE
Issue with "Recording a media element": (short summary here please)

### ISSUE THREAD

**Issue by MnColee** [mdn/content#14203]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Recording_a_media_element

#### What did you expect to see?
I want to see the preview of the camera and it should not recording. Then when I click it that's when it record. I just want the camera be opened. Thanks.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediastream_recording_api/recording_a_media_element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Recording_a_media_element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediastream_recording_api/recording_a_media_element/index.md
* Last commit: https://github.com/mdn/content/commit/e5afb1ea90baa705a8afe50d2739da16bfec1c0b
* Document last modified: 2022-03-15T14:43:47.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14251 with a fix that updates the label of the relevant button to make it more clear that pressing the button will start recording.
