### ISSUE TITLE
Issue with "Logical OR (||)": …

### ISSUE THREAD

**Issue by mushmelty** [mdn/content#1422]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR

#### What information was incorrect, unhelpful, or incomplete?
`true || false && false      // returns true, because && is executed first`

#### Specific section or headline?
**Operator precedence**

#### What did you expect to see?
`true || false && false      // returns true, because || is executed first`

Because of short-circuiting, the portion "false && false" is not evaluated, therefore "&&" is not "executed first", or at all.

#### Did you test this? If so, how?
I tested the statement in the browser console, with function calls after "true ||", which were not executed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/logical_or`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/operators/logical_or/index.html
* Report started: 2021-01-18T08:58:04.771Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @mushmelty ! Do you fancy submitting a PR to fix this? The page source URL is listed under the "MDN Content page report details".

**Comment by tannerdolby** [comment]
@mushmelty Good catch. You are correct. A short-circuit or `||` will stop at the first condition if it's `true` and not evaluate the second condition.

**Comment by mushmelty** [comment]
> Thanks for reporting this @mushmelty ! Do you fancy submitting a PR to fix this? The page source URL is listed under the "MDN Content page report details".

Sure, I'll make the PR.

**Comment by CreaTorAlexander** [comment]
Is this issue free? I can update it

**Comment by tannerdolby** [comment]
@CreaTorAlexander It seems to be fixed already by some other commit/PR.

<img width="894" alt="Screen Shot 2021-02-07 at 2 20 11 PM" src="https://user-images.githubusercontent.com/48612525/107161159-abc3c980-694f-11eb-9342-19d7759abc61.png">

@chrisdavidmills I think this issue can be closed now.

**Comment by mushmelty** [comment]
The correction has been made and incorporated into the documentation.
