### ISSUE TITLE
Issue with "StorageManager.estimate()": usageDetails is not mentioned in standard + not supported by Firefox

### ISSUE THREAD

**Issue by caugner** [mdn/content#14236]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate

#### What information was incorrect, unhelpful, or incomplete?

The [return value section](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate#return_value) mentions property `usageDetails`, but this is neither mentioned in the [Storage Standard](https://storage.spec.whatwg.org/#dictdef-storageestimate) nor returned by Firefox (type `await navigator.storage.estimate()` in the console).

#### Specific section or headline?

[Return value](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate#return_value)

#### What did you expect to see?

The property `usageDetails` should not be listed there.

#### Did you test this? If so, how?

- Ran `await navigator.storage.estimate()` in Firefox.
- Chrome does return the `usageDetails` property though. 🤔 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/storagemanager/estimate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/storagemanager/estimate/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by teoli2003** [comment]
Thanks @caugner!

It looks like it is a non-standard extension by Chrome:
![Capture d’écran 2022-03-24 à 06 39 32](https://user-images.githubusercontent.com/1466293/159849975-a1eb9ede-40e5-4433-81ee-11e5e7176eab.png)

I will open a PR to label it as _Non-standard_ here on _mdn/content_ and another one to add extra entry in the browser compatibility table at mdn/browser-compat-data.

**Comment by caugner** [comment]
Thanks @teoli2003!
