### ISSUE TITLE
"String.prototype.indexOf()": Contradicts itself on what happens when position given is greater than the string length

### ISSUE THREAD

**Issue by sssrgo-dev** [mdn/content#14242]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf

#### What information was incorrect, unhelpful, or incomplete?
You assert, that method doesn't search in certain conditon. In that condition method searches, you write lower in the article..

You write the first: "If position is greater than the length of the calling string, the method doesn't search the calling string at all."
And then you primarily contradict to it: 

"However, with a second argument whose value is greater than or equal to the string's length, the return value is the string's length:

'hello world'.indexOf('', 11) // returns 11
'hello world'.indexOf('', 13) // returns 11
'hello world'.indexOf('', 22) // returns 11
Copy to Clipboard
In the former instance, the method behaves as if it found an empty string just after the position specified in the second argument. In the latter instance, the method behaves as if it found an empty string at the end of the calling string."

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/indexof`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/indexof/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by deepug9787** [comment]
"However, with a second argument whose value is greater than or equal to the string's length, the return value is the string's length"

Do note that this is applicable only when the search term is an empty string. So there is no contradiction here.

From what I understand, the method does not search the calling string if the position argument is greater than the length of the calling string irrespective of whether the search term is an empty string or not. Only the return values will be different.

If the search term isn't an empty string and the position argument is greater than the length of the calling string, the return value will be -1.

If the search term is an empty string and the position argument is greater than the length of the calling string, the return value will be the length of the calling string.

IMO, it would have been less confusing if return value was -1 when the position argument is greater than the calling string length irrespective of whether the search term was empty or not. But it is what it is.

Hope this helps.

**Comment by kentinHogbonouto** [comment]
Hello [sssrgo-dev](https://github.com/sssrgo-dev), there is no contradiction in the explanation, as [deepug9787](https://github.com/deepug9787) said, this one concern only with the empty substring searching, then you can see that when we make the search with a second argument which value is less than the search string the return is equal to the second argument value itself and when the second argument value is greater than or equal to searching string length the return is equal to search string length. Hope that this comment will be helpful

**Comment by wbamberg** [comment]
Thanks for the clarification @deepug9787 ! and @kentinHogbonouto !
