### ISSUE TITLE
Issue with "Feature-Policy": Should be called Permissions Policy

### ISSUE THREAD

**Issue by cynthia** [mdn/content#14257]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy

#### What information was incorrect, unhelpful, or incomplete?

Feature Policy has been renamed to Permissions Policy.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy

#### What did you expect to see?

Permissions Policy. See: https://github.com/w3c/webappsec-permissions-policy

#### Did you test this? If so, how?

I opened the page. It said Feature Policy.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/feature-policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/feature-policy/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by sideshowbarker** [comment]
Howdy Sangwhan, we have https://github.com/mdn/content/issues/1831 which this issue duplicates, so I’m going ahead and closing this
