### ISSUE TITLE
Issue with "Use HTML to solve common problems": Duplicate Article

### ISSUE THREAD

**Issue by GeorgeDaris** [mdn/content#14261]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto

#### What information was incorrect, unhelpful, or incomplete?

Under the "Embedded content" section the article "How to add Flash content within a webpage" links to the previous article, "How to embed a webpage within another webpage"

#### Specific section or headline?

[Embedded content](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto#embedded_content)

#### What did you expect to see?

The article mentioned

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/howto`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/howto/index.md
* Last commit: https://github.com/mdn/content/commit/0b270d4f95ba1c4abcc81215df774a9448a78105
* Document last modified: 2022-02-18T09:10:31.000Z

</details>

**Comment by teoli2003** [comment]
Flash being a thing of the past on the web, the article has been removed long ago. I've removed the link now.

**Comment by GeorgeDaris** [comment]
Makes sense. Good job!
