### ISSUE TITLE
Content bug: Missing semicolon in JavaScript Looping code guide

### ISSUE THREAD

**Issue by ssolunna** [mdn/content#14271]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code

## Specific page section or heading?

[Active learning: Filling in a guest list](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code#active_learning_filling_in_a_guest_list)

## What is the problem?

Missing semicolon in the **Editable code** at:

```refused.textContent = 'Refuse: '```

## What did you expect to see?

A semicolon added at the end of the statement:

```refused.textContent = 'Refuse: ';```

## Did you test this? If so, how?

N/A

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14278 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
