### ISSUE TITLE
Content bug: <Broken url>

### ISSUE THREAD

**Issue by jsmarketingrus** [mdn/content#14276]
## What page(s) did you find the problem on?

https://github.com/mdn/content/blob/main/en-US/docs/Learn/Front-end_web_developer

## Specific page section or heading?

Learn section, index page

## Did you test this? If so, how?

I try to learn your new course for developers, but it was impossible. Call me please when you fix it.

**Comment by hamishwillee** [comment]
Closing. Not an bug report.
