### ISSUE TITLE
Issue with "JavaScript data types and data structures": Number type

### ISSUE THREAD

**Issue by santimirandarp** [mdn/content#14288]
MDN URL to Section [This is the specific headline](
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#number_type)

First of all thanks. I just wonder the wording could be improved here, or I am misunderstanding it.

#### What information was incorrect, unhelpful, or incomplete?

> The Number type is a [double-precision 64-bit binary format IEEE 754 value](https://en.wikipedia.org/wiki/Double_precision_floating-point_format) (numbers between -(2^53 − 1) and 2^53 − 1)

Do you mean integers there? 

The IEEE754 for 64bits numbers assigns  53 bits for the base + 11 for the exponent. So it's a more general, useful built in way to represent rational numbers. 

Not sure what that range is trying to explain. 

-----------

A nice calculation

This is just a random stuff in case you like numbers sorry

IEEE754 is used for both rational numbers and integers. Because 2^10 is approx 10^3, you have about 15 decimals in every number. From Wikipedia it says 15-17 range.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/data_structures`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/data_structures/index.md
* Last commit: https://github.com/mdn/content/commit/181dac2884196d07f0d11f781dd719d23b95a49f
* Document last modified: 2022-03-20T06:13:34.000Z

</details>

**Comment by NiedziolkaMichal** [comment]
This is range of Safe Integers that can be used with IEEE 754. Those values correspond to [MIN_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_SAFE_INTEGER) and [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), though numbers outside of this range can be used. I will make an edit to make it clearer.

**Comment by santimirandarp** [comment]
So for integers is actually uses the bits corresponding to the fractional part and an exponent of 0 ? 

For FP it is clear, you get unsigned 2**11 and that's from -1000 to 1000 approx and in base 10 is -300 to 300, and then the fractional part has about 15-17 decimals.

Maybe I should read the implementation. Thanks for commenting.

**Comment by NiedziolkaMichal** [comment]
IEEE 754 in 64 bits consists of 1 sign bit, 11 exponent bits and 52 significand bits. At value 2^53-1 it exhausts all significand bits, which you can [visualize in here](http://bartaz.github.io/ieee754-visualization/). Unlike data types capable of only holding integers, it's quite hard to understand how floating-points work internally.
