### ISSUE TITLE
Issue with "HTTP caching": (The response max-age directive should be related to Date not time of request)

### ISSUE THREAD

**Issue by jamesxu2018** [mdn/content#14285]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

#### What information was incorrect, unhelpful, or incomplete?
quoting "The most important directive here is max-age=<seconds>, which is the maximum amount of time in which a resource will be considered fresh. This directive is relative to the time of the request, and overrides the Expires header (if set)."
---comment by james: "This directive is relative to the time of the request" is incorrect, this directive is relate to the time of Date, when the message was generated.
#### Specific section or headline?
Expiration

#### What did you expect to see?
This directive is relate to the time of Date, when the message was generated.

#### Did you test this? If so, how?
Not yet. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/caching`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/caching/index.md
* Last commit: https://github.com/mdn/content/commit/e09a44694d5f52b3cd438c018206c7b8a36c1b0f
* Document last modified: 2022-03-18T11:43:49.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. Yes, that's definitely wrong. Fixed in #14383
