### ISSUE TITLE
Issue with "float": Background color of demo clashes with text in dark mode

### ISSUE THREAD

**Issue by mgunyho** [mdn/content#14283]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/float

#### What information was incorrect, unhelpful, or incomplete?
The text in the `float` demo is impossible to read with the dark theme (in my case this was the "OS default"):

![image](https://user-images.githubusercontent.com/20118130/160064405-07751187-cc7d-4650-ad3c-4577a3050257.png)

#### What did you expect to see?
The text should be legible, like in the light theme version:
![image](https://user-images.githubusercontent.com/20118130/160065014-b81ed8ac-f71b-45c5-a3e4-7bea2afd800d.png)

I guess either the background of the box should change with the dark theme, or the text shouldn't.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/float`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/float
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/float/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by NiedziolkaMichal** [comment]
Fix for it is included in PR [#2042](https://github.com/mdn/interactive-examples/pull/2042)
