### ISSUE TITLE
Issue with "-webkit-line-clamp": It didnt work with latest ios version

### ISSUE THREAD

**Issue by KarthikAdyar** [mdn/content#14297]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/-webkit-line-clamp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/-webkit-line-clamp/index.md
* Last commit: https://github.com/mdn/content/commit/08a11a1af633a1e04145494fdb730c460f862f57
* Document last modified: 2022-03-10T18:11:06.000Z

</details>

**Comment by teoli2003** [comment]
It looks like it is working (iOS 15.4):
![WhatsApp Image 2022-03-25 at 3 55 32 PM](https://user-images.githubusercontent.com/1466293/160145431-d6b5988d-b01a-48c3-92f2-9881c0e60f3d.jpeg)

I'm closing this, feel free to reopen if I'm mistaken.

**Comment by KarthikAdyar** [comment]
Try having multiple p tags inside the main div and check.
Works fine with chrome
