### ISSUE TITLE
Issue with "Promise() constructor": try/catch in executor

### ISSUE THREAD

**Issue by bergus** [mdn/content#1429]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise

#### What information was incorrect, unhelpful, or incomplete?

The sentence

> The executor might also include a try{} catch() block that invokes rejectionFunc upon error.

is misleading. A synchronous exception is already handled by the `Promise` constructor itself, one should never need to use `try`/`catch` explicitly. (And in asynchronous callbacks it's a best practice not to do anything that might throw)

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise#parameters

#### What did you expect to see?

[Apparently](https://stackoverflow.com/a/52633469) an earlier version read:

> If an error is thrown in the executor function, the promise is rejected. The return value of the executor is ignored.

Both parts are missing from the current text, but I can't find the revision history any more to check when it changed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise/promise`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/promise/promise/index.html
* Report started: 2021-01-18T12:14:40.088Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for raising this and sorry for the lack of response until now.

I’ve opened https://github.com/mdn/content/pull/5833 with an attempt at fixing the problems cited in the issue description. And along with that, it amounts to being a general reworking of the entire section of the article.
