### ISSUE TITLE
“class” article: Is “You can also define a class using a class expression” correct?

### ISSUE THREAD

**Issue by kimmy253** [mdn/content#14307]
## What page(s) did you find the problem on?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/class

## Specific page section or heading?
Class page right above Syntax.  This paragraph doesn't seem correct. I am new at Javascript so I could be wrong.
"You can also define a class using a [class expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/class). But unlike a **class expression**, a class declaration doesn't allow an existing class to be declared again and will throw a [SyntaxError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError) if attempted.

## What is the problem?

 I think the writer meant "unlike a function expression? IDK.

**Comment by teoli2003** [comment]
I agree with @NiedziolkaMichal. The sentence is correct. Maybe we can improve it to make it simpler to understand. If not, I think we should close this.

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/14369
