### ISSUE TITLE
Issue with "FormData()": type=submit inputs not included

### ISSUE THREAD

**Issue by bluepuma77** [mdn/content#14305]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData

#### What information was incorrect, unhelpful, or incomplete?
The docs do not mention that FormData is ignoring input type=submit elements. 
That is unexpected. A plain HTML submit of a form will include submit inputs.
This feature is useful to implement multiple different submit buttons.

#### Specific section or headline?
Potentially add it to "Note: Only successful form controls are included..."

#### What did you expect to see?
Information about this unexpected behaviour, potentially a "Gotchas" section.

#### Did you test this? If so, how?
```
<!DOCTYPE html>
<html>
  <body>
    <script>
      function handleSubmit(e) {
        e.preventDefault()
        const form = document.getElementById("myForm")
        const data = new FormData(form)
        for (var [key, value] of data.entries()) {
          console.log(key, value)
        }
        return false
      }
    </script>

    <form method="POST" id="myForm" onsubmit="return handleSubmit(event)">
      <input type="text" name="text" value="text" /><br />
      <input type="number" name="number" value="1" /><br />
      <input type="submit" name="submit1" value="Submit1" /><br />
      <input type="submit" name="submit2" value="Submit2" /><br />
    </form>

  </body>
</html>
```

Slightly different Svelte version in [REPL](https://svelte.dev/repl/d4e94c3d49854a739ba3115c2713963c?version=3.46.4
)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/formdata/formdata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/formdata/formdata/index.md
* Last commit: https://github.com/mdn/content/commit/c9a795a59234d6d75b4b1092c7e5fd13a766f1a4
* Document last modified: 2022-01-28T12:28:43.000Z

</details>

**Comment by jenseng** [comment]
This might be covered sufficiently by the [new `submitter` parameter](https://github.com/whatwg/xhr/pull/366) to `FormData` and [this corresponding PR](https://github.com/mdn/content/pull/23950) to document it.

@bluepuma77 would you mind taking a look to see if the new wording and examples are sufficient to resolve this?

**Comment by Josh-Cena** [comment]
Closing assuming it's fixed
