### ISSUE TITLE
Issue with "list-style-image": Can't see the bullet point in dark mode

### ISSUE THREAD

**Issue by Mozzius** [mdn/content#14301]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-image

#### What information was incorrect, unhelpful, or incomplete?

This article explains how to add custom bullet points, and illustrates this with a custom bullet point. Unfortunately, it is invisible on the black background in dark mode, since the custom bullet point is black.

#### Specific section or headline?

Try it

#### What did you expect to see?

The bullet points

#### Did you test this? If so, how?

Turn on dark mode

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/list-style-image`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-image
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/list-style-image/index.md
* Last commit: https://github.com/mdn/content/commit/56da604e4fc9c926015751a990496f0284bf4e41
* Document last modified: 2022-03-18T17:18:24.000Z

</details>

**Comment by NiedziolkaMichal** [comment]
Fix for it is included in PR [#2042](https://github.com/mdn/interactive-examples/pull/2042)
