### ISSUE TITLE
Issue with "<img>: The Image Embed element": Role for empty alt attribute does not align with W3C

### ISSUE THREAD

**Issue by abbott567** [mdn/content#14306]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

#### What information was incorrect, unhelpful, or incomplete?
The implicit role for an img with empty alt attribute is listed as `no corresponding role`.

Example:
- with empty alt attribute: no corresponding role

However, if you click on 'no corresponding role' and go to the [W3C documentation](https://www.w3.org/TR/html-aria/#docconformance), in the table, it outlines the implicit aria role for an img with empty alt attribute as `role="presentation"`.

Example:

| HTML element | Implicit ARIA semantics |
| --------------- | ----------------------- |
| img with alt="" | role=presentation.         |

Not sure which one needs changed, but I feel like these should be aligned?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/img`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/img/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #14316 with a fix.
