### ISSUE TITLE
Issue with "CSP: img-src": …

### ISSUE THREAD

**Issue by bonen02** [mdn/content#1431]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src

#### What information was incorrect, unhelpful, or incomplete?
Broken link to [URL scheme](https://developer.mozilla.org/en-US/docs/URIs_and_URLs), which returns 404

#### Specific section or headline?
Under "`Sources`" -> "`<host-source>`"

#### What did you expect to see?
The linked doc, maybe https://developer.mozilla.org/en-US/docs/Web/HTTP/Resources_and_URIs

#### Did you test this? If so, how?
Click on the link, landed on "Page not found"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/img-src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/headers/content-security-policy/img-src/index.html
* Report started: 2021-01-18T14:09:14.293Z

</details>

**Comment by hamishwillee** [comment]
Fixed by #1432
