### ISSUE TITLE
Issue with "Using CSS custom properties (variables)": (text refers to fallback value while example does not define one)

### ISSUE THREAD

**Issue by DelPoint** [mdn/content#14318]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

#### What information was incorrect, unhelpful, or incomplete?
This sentence refers to a 'fallback' value while the example in the section does not define any fallback for the custom property at all:
"The paragraph color will not be blue because invalid substitution is replaced by the initial value, not by the fallback."

#### Specific section or headline?
[What happens with invalid variables?](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#what_happens_with_invalid_variables)

#### What did you expect to see?
"The paragraph color will not be blue because invalid substitution is replaced by the initial value."

#### Did you test this? If so, how?
Nope.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/using_css_custom_properties`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/using_css_custom_properties/index.md
* Last commit: https://github.com/mdn/content/commit/56da604e4fc9c926015751a990496f0284bf4e41
* Document last modified: 2022-03-18T17:18:24.000Z

</details>

**Comment by deepug9787** [comment]
@DelPoint I think the "fallback" in this case refers to the cascaded value, not the fallback value of the var function.

**Comment by DelPoint** [comment]
@deepug9787 Maybe. But as you've used the term "cascaded value" (which is obviously a 'different' value) in your epxlanation in order to explain/enlighten what happened in the example, they ought to use also this or similar term instead of a misleading one, which is used consistently for a differnt kind of value (read: the var() function's fallback). In other words: mixing/interchanging the terms and hoping someone will 'figure out' it refers actually to another term is not really professional. MDN can do better.

**Comment by wbamberg** [comment]
Yes, it's totally confusing. I just filed https://github.com/mdn/content/pull/15736 for this.
