### ISSUE TITLE
Issue with "Strict mode": …

### ISSUE THREAD

**Issue by KoditkarVedant** [mdn/content#1433]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

#### What information was incorrect, unhelpful, or incomplete?
Under the section `Converting mistakes into errors`, after the `Fourth, strict mode requires that function parameter names be unique` the next point is mentioned as `Sixth, a strict mode in ECMAScript 5 forbids a 0-prefixed octal literal or octal escape sequence.`

#### Specific section or headline?
Converting mistakes into errors

#### What did you expect to see?
Instead of `Sixth`, it should be `Fifth, a strict mode in ECMAScript 5 forbids a 0-prefixed octal literal or octal escape sequence.`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/strict_mode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/strict_mode/index.html
* Report started: 2021-01-18T14:20:39.286Z

</details>

![image](https://user-images.githubusercontent.com/18693839/104928473-b6cab000-59c8-11eb-8ea5-0e73735007e4.png)

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/1434
