### ISSUE TITLE
"Touch events": I am not able to understand the text; need example that is usable, what do you want me to do to use a touchdown event?

### ISSUE THREAD

**Issue by oleviolin** [mdn/content#14332]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events

#### What information was incorrect, unhelpful, or incomplete?
I am not able to understand the text

#### What did you expect to see?
An example that is usable, what do you want me to do to use a touchdown event?

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/touch_events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/touch_events/index.md
* Last commit: https://github.com/mdn/content/commit/7d72325bc7f6b5954209c820aa1770788976eba8
* Document last modified: 2022-03-25T00:46:12.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing, @oleviolin . Could you be more specific? Was there some particular part of the page that didn't make sense? It's hard for us to fix issues that just say "I couldn't understand this page".

**Comment by oleviolin** [comment]
Thank you for fast answer.
I have reread the page, and I think my comments are wrong, since they do not concern the page
My comments are refering to: the Chrome development tool referrer page:
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
The example for a solution here, is a litle mind blowing
Just for adding a simple touchdown event.
The page:
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events
is very clear and structured.
So please cancel my complain.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/14332#issuecomment-1079773217
