### ISSUE TITLE
someone change main page of /docs/Learn content in ID version to other OOT content

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1435]
@shaziawaludin commented on [Mon Jan 11 2021](https://github.com/mdn/sprints/issues/3985)

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
I think someone has changed the content on the main page id/docs/learn section. that should show something that is relevant to web learning, instead be an explanation of the neckline.

url : https://developer.mozilla.org/id/docs/Learn
![image](https://user-images.githubusercontent.com/60837766/104156463-a8eebb00-541b-11eb-864b-af2412fa0956.png)

so different than US version :
![image](https://user-images.githubusercontent.com/60837766/104156486-b99f3100-541b-11eb-804b-f2184b768db3.png)

---

@chrisdavidmills commented on [Mon Jan 11 2021](https://github.com/mdn/sprints/issues/3985#issuecomment-758025795)

Thanks for reporting this issue @shaziawaludin . We currently aren't accepting changes to localized content, but we should be able to get rid of the spam.

Hi @fiji-flo ! Here is one of those instances where we need to get rid of some spam from a localized page. I'm not sure if you're able to extract the last known good version of it from the wiki history dump. If not, we may just have to delete it.

**Comment by Rumyra** [comment]
This content has been retired, so essentially this issue is 'fixed'
