### ISSUE TITLE
"void operator": bad interactive example at beginning of the article; doesn’t produce the expected output

### ISSUE THREAD

**Issue by RobG000** [mdn/content#14361]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void

#### What information was incorrect, unhelpful, or incomplete?

The attempt at using the void operator to cause an error fails. No error is thrown so the expected outcome does not occur. It's not a good example. 

A better example would be:

    let x = void 0;
    console.log(typeof x);  // undefined

#### Specific section or headline?
Try it

#### What did you expect to see?
I expected to see the actual outcome, however the section says that an error should be thrown.

#### Did you test this? If so, how?
Yes, by pressing the "Run" button

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/void`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/void/index.md
* Last commit: https://github.com/mdn/content/commit/4e55ef8d3618f047997d8670fce06b838de6a17b
* Document last modified: 2022-03-25T23:14:02.000Z

</details>

**Comment by RobG000** [comment]
The simplest fix is to change:

    console.log(e);

to:

    console.log(e.message);

However, the *void* operator in the expression does nothing at all since named function expressions don't create variables anyway, e.g. it can be changed to:

    !function test() { ... }()

and the same error is thrown. I.e. it's not the void operator that is the cause of the error, it's using a named function expression and expecting the name to be global. Any operator or punctuator before the *function* keyword that changes the declaration to an expression will have the same effect.

**Comment by NiedziolkaMichal** [comment]
Error is correctly thrown, you can find its message in Dev Tools(F12 on Chrome by default). First paragraph of this page says "The void operator evaluates the given expression and then returns undefined." and that's exactly what example shows. Without operator "void", that function wouldn't become and expression and it would be added to the surrounding scope(though in this particular case, SyntaxError would be thrown, because of braces at the end). It is true that symbols "!", "+", "~" offer similar possibility, by still converting instruction into an expression is cause of the exception.
I will change console.log(e) to console.log(e.message), to make that exception more visible.

**Comment by wbamberg** [comment]
This is a duplicate: https://github.com/mdn/bob/issues/710 . @NiedziolkaMichal 's fix works, which is great, but as noted in that issue:

- it would be even better if the [mock console](https://github.com/mdn/bob/blob/main/editor/js/editor-libs/console-utils.js) in the interactive examples handled error objects
- I think it's virtually certain that this used to work and the mock console regressed at some point. It's a very obvious error (the logged output doesn't match the "expected output" comment) so it almost certainly used to work.

@schalkneethling , do you have any ideas here?

**Comment by sideshowbarker** [comment]
I think part of @RobG000’s point here is that the try…catch to log the exception isn’t at all a good example of `void` specifically. Fixing that suboptimal example doesn’t address the problem that it’s the wrong example to begin with.

As the article itself notes:

> The void operator is often used merely to obtain the `undefined` primitive value, usually using "`void(0)`" (which is equivalent to "`void 0`").

That’s the common case (by far). And the existing example doesn’t at all illustrate that simple common case. Instead it seems to be trying to illustrate something else more complicated. So it’s missing the point — to the degree that it’s just kind of a non sequitur.

So it seems like it’d be better to have a simple example that just illustrates using `void(0)` to intentionally obtain `undefined`.

**Comment by wbamberg** [comment]
Fair enough! I must admit I only read the original issue, not the next comment.

**Comment by sideshowbarker** [comment]
> Fair enough! I must admit I only read the original issue, not the next comment.

Well the point you made in https://github.com/mdn/content/issues/14361#issuecomment-1079982408 still holds: in the browser devtools `console.log(e)` causes the (useful) message *“ReferenceError: Can't find variable: test”* to be logged, but in the mock console, it instead causes a (not useful) literal `Object {  }` to be logged.

So yeah, the mock console is doing something different and less useful here than what actual browser devtools consoles do — and so, getting https://github.com/mdn/bob/issues/710 resolved would be generally useful for more than just this specific case.

**Comment by NiedziolkaMichal** [comment]
@sideshowbarker I have rewritten whole example in PR [#2065](https://github.com/mdn/interactive-examples/pull/2065). It now shows that:
- void always returns undefined
- its expression is normally evaluated
- it's possible to create IIFE with it
- declared function is not placed in surrounding scope
