### ISSUE TITLE
Clarification required concerning Javascript import

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1436]
@gdennie commented on [Sat Jan 02 2021](https://github.com/mdn/sprints/issues/3978)

The distinction between the following two `import` syntax is not sufficiently clear. The notion of `un-exported` is not clarified and presumes the reader knows enough to not require the documentation in the first place. I am still in the midst of research since the article is not clear.

```
import { export1 , export2 } from "module-name";
import { foo , bar } from "module-name/path/to/specific/un-exported/file";
```
Clearly, `module-name`, is not itself a directory such that it should contain the subdirectory `path/to/specific/un-exported` which contains `file.js` that is somehow un-exported.

A question on this issues remains somewhat open on **stackoverflow** [understanding es6 named imports](https://stackoverflow.com/questions/53136869/understanding-es6-named-imports)

**Comment by sideshowbarker** [comment]
The accepted answer at https://stackoverflow.com/questions/53136869/understanding-es6-named-imports/53179501#53179501 would seem to enlightening to anybody who’s interested in working on refining the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import article to make more clear the distinction between the two types of syntax for module-import statements.
