### ISSUE TITLE
Please do a recipe for responsive tables

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1438]
@mattiapontonio commented on [Mon Dec 14 2020](https://github.com/mdn/sprints/issues/3969)

![Screenshot_20201215-001911.png](https://user-images.githubusercontent.com/44380480/102147564-3d8cea00-3e6b-11eb-8a24-2754e6580f7e.png)

    https://developer.mozilla.org/en-US/search?q=responsive+tables

**Comment by mattiapontonio** [comment]
👍
These are the steps:

1. add `overflow-x:auto;` to the `table`;

**Comment by mattiapontonio** [comment]
@chrisdavidmills do You want to test this flow?
How can I just create the page from my smartphone? Do You have a link?

**Comment by mattiapontonio** [comment]
@chrisdavidmills can You add Need help label?
I'm thinking that maybe It should be a section in table Page not a recepy.

**Comment by Ryuno-Ki** [comment]
Added `help wanted` label.

**Comment by shades-7** [comment]
If once can you explain in detail what is needed to be fixed, I would like to take up this issue but?

**Comment by Ryuno-Ki** [comment]
@mattiapontonio Brought this up originally. Do you happen to recall the context, Mattia?

**Comment by chrisdavidmills** [comment]
Mattia unfortunately got blocked from our repos last week.

I think this is referring to creating a decent solution for a responsive table stlying, so that the table works well on wide and narrow screens. I'm not 100% sure where that would be put. In the examples on the `<table>` element page maybe?

**Comment by Ryuno-Ki** [comment]
> Mattia unfortunately got blocked from our repos last week.

Ouch.

> I think this is referring to creating a decent solution for a responsive table stlying, so that the table works well on wide and narrow screens. I'm not 100% sure where that would be put. In the examples on the `<table>` element page maybe?

Okay, that would be https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table ?
Could confuse from the subject on hand.

The only other widespread use of tables I'm aware of are BCD (Browser Compatibility Data) ones.
That is already discussed in https://github.com/mdn/yari/issues/2502 though

**Comment by sideshowbarker** [comment]
From the issue description and comments here, it doesn’t seem clear what the expected resolution for this issue would look like — and the original OP is no longer around to provide clarification. So I’m going ahead and closing this.
