### ISSUE TITLE
Issue with "Date.prototype.getDay()": Sunday is not always day number 0, it depends on current locale

### ISSUE THREAD

**Issue by asn007** [mdn/content#14381]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay

#### What information was incorrect, unhelpful, or incomplete?
`Date.getDay()` does not always return 0 for Sunday, it depends on browser's locale

#### Specific section or headline?
Date.prototype.getDay()

#### What did you expect to see?
The `getDay()` method returns the day of the week for the specified date according to local time, where 0 is the day the week starts on in current locale. For example, for `en_US` it returns 0 for Sunday, but for `ru_RU` it returns 0 for Monday

#### Did you test this? If so, how?
My working PC uses `en_US` locale, but my phone uses `ru_RU`. I've tested this by evaluating `new Date().getDay()` in the browser console of latest Chrome on my working PC and in the browser console of Chrome on my mobile (running latest Chrome on Android 12) using remote debug. On Monday, `new Date().getDay()` returns 1 on the PC, but 0 on the mobile phone

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/getday`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/getday/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by asn007** [comment]
Closing, because of some weird time synchronization issues on my device

**Comment by hamishwillee** [comment]
According to the specification the weekday numbering is not locale dependent. I don't think it would make sense for it to be either:
- [getDay definition is here](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date.prototype.getday)
- That points to [weekday definition](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-week-day)
  > .. is defined as 
  >> WeekDay(t) = [𝔽](https://tc39.es/ecma262/multipage/notational-conventions.html#%F0%9D%94%BD)([ℝ](https://tc39.es/ecma262/multipage/notational-conventions.html#%E2%84%9D)([Day](https://tc39.es/ecma262/multipage/numbers-and-dates.html#eqn-Day)(t) + 4𝔽) [modulo](https://tc39.es/ecma262/multipage/notational-conventions.html#eqn-modulo) 7)
  > A weekday value of **+0𝔽 specifies Sunday**; 1𝔽 specifies Monday; 2𝔽 specifies Tuesday; 3𝔽 specifies Wednesday; 4𝔽 specifies Thursday; 5𝔽 specifies Friday; and 6𝔽 specifies Saturday. Note that WeekDay(+0𝔽) = 4𝔽, corresponding to Thursday, 1 January 1970.
  
So if you are finding this to be true for a particular browser, that will be a browser issue and should be posted as a browser bug.
