### ISSUE TITLE
[WebAssembly] WebAssembly Exception Handling

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#14392]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

WebAssembly now supports exception handling:
- Overview: https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md (a little mismatched to spec for JS API
- https://webassembly.github.io/exception-handling/js-api/#runtime-exceptions - The draft spec
- Proposal: https://github.com/WebAssembly/exception-handling

## Related Gecko bugs

- https://bugzilla.mozilla.org/show_bug.cgi?id=1695715 - Meta bug on feature
- https://bugzilla.mozilla.org/show_bug.cgi?id=1759217 - Shipping bug - FF100

## Other

Was in nightly behind pref `javascript.options.wasm_exceptions`  ([FF98](https://bugzilla.mozilla.org/show_bug.cgi?id=1750040)) and enabled in FF100. So pref needs to be in BCD too. 

Useful references/tools
- MDN docs: https://developer.mozilla.org/en-US/docs/WebAssembly
- Awesome online test tool : https://webassembly.github.io/wabt/demo/wat2wasm/ (part of these tools - https://github.com/webassembly/wabt)
- Unlinked Wasm reference: https://developer.mozilla.org/en-US/docs/WebAssembly/Reference

**Comment by eqrion** [comment]
> 
> Was in nightly behind pref `javascript.options.wasm_function_references` and enabled in FF100. So pref needs to be in BCD too.

Slight correction, not sure if I wrote this wrong somewhere or not. The correct pref is `javascript.options.wasm_exceptions`.

**Comment by hamishwillee** [comment]
Thanks @eqrion - you did nothing wrong - I misread https://phabricator.services.mozilla.com/D141700 (saw the item below the javascript.options.wasm_exceptions). That could have been embarrassing. 
FYI, not sure who is doing this yet. Team is a bit stretched and none of us have specific expertise in web assembly. Probably either me or @Rumyra unless we can find a domain expert.

**Comment by hamishwillee** [comment]
Status:

- [ ] `WebAssembly.Tag` 
  - [ ] Docs
  - [ ] BCD - https://github.com/mdn/browser-compat-data/pull/15668
- [ ] `WebAssebly.Exception`
  - [ ] Docs
  - [ ] BCD - https://github.com/mdn/browser-compat-data/pull/15668 
- [ ] Updates to [concepts](https://developer.mozilla.org/en-US/docs/WebAssembly/Concepts) and other tutorials to cover exception handling:
- [ ] Release notes
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
@hamishwillee I'm enquiring as to the issue on interactive examples in regards to the toolkit... do we want to pull out/separate some of the remaining todos and put them in the backlog?

**Comment by hamishwillee** [comment]
@Rumyra I've created #15836 for the guide which I still hope to create at some point. The interactive example fix needs to be tested, but I don't actually plan on using it "this round".  This can probably be closed, though i have put marking things as dev-doc-complete in the new issue.

**Comment by Rumyra** [comment]
Ok cool 👍 that sounds good to me
