### ISSUE TITLE
Clarify "Permitted parents: any element that accepts metadata content"

### ISSUE THREAD

**Issue by Abdull** [mdn/content#14398]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories

#### What information was incorrect, unhelpful, or incomplete?
_Metadata content elements_ such as
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#technical_summary
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

mention as _permitted parent elements_: "_Any element that accepts [metadata content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#metadata_content)_".

But it is not clear **which** elements accept/allow metadata content.

It would be helpful to provide an additional content category "_metadata content-accepting elements_", list those elements (e.g., [`<head>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head)), and link to it from aforementioned places.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/guide/html/content_categories`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/html/content_categories/index.md
* Last commit: https://github.com/mdn/content/commit/a590d73456035088e5f1cac116974488ebd867ef
* Document last modified: 2022-01-31T14:45:50.000Z

</details>

**Comment by estelle** [comment]
Clarification:

The explanation is circular. [Content_categories](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories) points to meta, and meta points back to content categories, but nowhere in the "loop" are the `<meta>` really defined. The spec does the same loop too, which really isn't helpful and makes this issues difficult to resolve
