### ISSUE TITLE
[WebExtensions] Implement scripting.updateContentScripts()

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#14393]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Docs linked from Gecko bug below: https://developer.chrome.com/docs/extensions/reference/scripting/#method-updateContentScripts

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1736585

**Comment by Rumyra** [comment]
Moving forward we're not creating issues for WebEXT release work (they'll work directly from bugzilla), so I'm closing this 👍
