### ISSUE TITLE
[CSS] Add support for `video-dynamic-range`

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#14405]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Seems `video-dynamic-range` is implemented for `@media` -> https://www.w3.org/TR/mediaqueries-5/#video-dynamic-range
- `dynamic-range` - https://drafts.csswg.org/mediaqueries-5/#dynamic-range

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1751217

WPT tests (FYI only)
- https://wpt.live/css/mediaqueries/dynamic-range.html
- https://wpt.live/css/cssom-view/cssom-view-window-screen-interface.html

(Dipika) UPDATE: Final status of this issue is here: https://github.com/mdn/content/issues/14405#issuecomment-1109656745

**Comment by Rumyra** [comment]
@queengooborg would you be able to update bcd with support for `dynamic-range` & `video-dynamic-range`?

**Comment by dipikabh** [comment]
- [ ] Feature documentation: https://github.com/mdn/content/pull/15375
- [ ] Spec URL and BCD updates: https://github.com/mdn/browser-compat-data/pull/16020
- Interactive example and data repos are updated if appropriate - not applicable
- [ ] Entry in Firefox release notes: https://github.com/mdn/content/pull/15378
- [ ] Bug set to dev-doc-complete
