### ISSUE TITLE
[HTTP] Remove large-allocation header

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#14407]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

FF is removing the large-allocation header https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Large-Allocation

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1598759

**Comment by hamishwillee** [comment]
Status

- [ ] Docs - [`Large-Allocation`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Large-Allocation) add deprecation tag. Also to parent page.
- [ ] BCD is updated
- [ ] dev-doc-complete
- [ ] Release note
