### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1441]
@shivamrathi99 commented on [Wed Dec 09 2020](https://github.com/mdn/sprints/issues/3953)

## URL(s)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

This code: 
The slice() method returns a shallow copy of a portion of an array into a new array object selected from start to end (end not included) where start and end represent the index of items in that array. The original array will not be modified.
```js
const animals = ['ant', 'bison', 'camel', 'duck', 'elephant'];

console.log(animals.slice(2));
// expected output: Array ["camel", "duck", "elephant"]

console.log(animals.slice(2, 4));
// expected output: Array ["camel", "duck"]

console.log(animals.slice(1, 5));
// expected output: Array ["bison", "camel", "duck", "elephant"]
```

can be written as : 
The slice() method returns a shallow copy of a portion of an array into a new array object selected from start to end (end not included) where start and end represent the index of items in that array. The original array will not be modified. **An index of (-1) points to the last element of the array.** 

```js
const animals = ['ant', 'bison', 'camel', 'duck', 'elephant'];
console.log(animals.slice(2));
// expected output: Array ["camel", "duck", "elephant"]
console.log(animals.slice(2, 4));
// expected output: Array ["camel", "duck"]
console.log(animals.slice(1, 5));
// expected output: Array ["bison", "camel", "duck", "elephant"]
**console.log(animals.slice(2, -1));
// expected output: Array ["camel", "duck"]**
```

to improve understanding concepts. 

thanks 

---

@RNabla commented on [Wed Dec 09 2020](https://github.com/mdn/sprints/issues/3953#issuecomment-742070692)

Hi,

Just wanted to point out that you can pass any negative value for 'start' and for 'end'. Explicitly stating **An index of (-1) points to the last element of the array.** seems like some magic case where -1 is bound to the end of array.

Usage of negative arguments it's in fact described in Syntax section. However I agree with that it's good idea to mention that briefly in description (this one on top of the page, not in description section) and add example - it's the first thing that is visible on the page.

I suggest something like:
The slice() method returns a shallow copy of a portion of an array into a new array object selected from start to end (end not included) where start and end represent the index of items in that array. **A negative index can be used, indicating an offset from the end of the sequence.** The original array will not be modified.

**Comment by NegiAkash890** [comment]
Hi @chrisdavidmills , I think it  would be great  to include the negative index case for the slice array method so that one can get a clear understanding of  how it works different when we  pass a positive index or a range as argument to the method . Let me know If I can help here : ) .

**Comment by chrisdavidmills** [comment]
Sure thing @NegiAkash890 , we'd be glad of your help. I've assigned you. Thanks!

**Comment by NegiAkash890** [comment]
Hi @chrisdavidmills , I have added the required examples in the  **mdn /interactive-examples**  : )  .

**Comment by Ryuno-Ki** [comment]
@NegiAkash890 Did you mean to add a reference here?

**Comment by NegiAkash890** [comment]
> @NegiAkash890 Did you mean to add a reference here?

Should I edit the above comment and attach link to the PR in the repo  ( mdn/ interactive examples )?

**Comment by chrisdavidmills** [comment]
> > @NegiAkash890 Did you mean to add a reference here?
> 
> Should I edit the above comment and attach link to the PR in the repo ( mdn/ interactive examples )?

Yes, please do. And in the PR you should include a line "Fixes #1441"

**Comment by NegiAkash890** [comment]
> > > @NegiAkash890 Did you mean to add a reference here?
> > 
> > 
> > Should I edit the above comment and attach link to the PR in the repo ( mdn/ interactive examples )?
> 
> Yes, please do. And in the PR you should include a line "Fixes #1441"

Done !

**Comment by himanshugarg** [comment]
@NegiAkash890 your PR adds useful samples but I couldn't find the text updates suggested above. Is there anything else that is holding this bug open?

**Comment by NegiAkash890** [comment]
Hi @himanshugarg , I have raised a PR addressing this issue in the mdn/interactive-examples#1773 but I think its not currently merged that's why changes are not reflected on the site.Tagging @chrisdavidmills.
