### ISSUE TITLE
Issue with "Add to Home screen": A2HS icon isn't present in latest Firefox on Android

### ISSUE THREAD

**Issue by scottdotjs** [mdn/content#14416]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen

In Firefox 98.3.0 for Android, there's no A2HS icon displayed as described in the section [**How do you use it?**](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen#how_do_you_use_it):

> If you have Firefox for Android available, use it to navigate to our demo at https://mdn.github.io/pwa-examples/a2hs/. You'll see fox pictures, but more important, you'll see a "home" icon with a plus (+) icon inside it — this is the "Add to Home screen" icon displayed for any site that has the necessary features in place.
> 
> ![image](https://user-images.githubusercontent.com/32358661/160495757-aa69e8e9-8f21-422b-8573-a984e38b9886.png)

This is what I see at that URL:

![image](https://user-images.githubusercontent.com/32358661/160496384-5326ae77-849c-48f6-8c1a-70d1a456cc4e.png)

There's an option to "Install" in the app menu but that's it.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/progressive_web_apps/add_to_home_screen`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/add_to_home_screen/index.md
* Last commit: https://github.com/mdn/content/commit/8f164b688448a602df794f9094e9d4d039887639
* Document last modified: 2021-12-02T19:40:14.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks - yes, appears to have changed in recent devices to be an "Install" or "Install app" menu item. Updated in https://github.com/mdn/content/pull/14419

**Comment by scottdotjs** [comment]
Brilliant, thank you @hamishwillee and @wbamberg.
