### ISSUE TITLE
Content bug: Consistency of Style

### ISSUE THREAD

**Issue by erosman** [mdn/content#14438]
## What page(s) did you find the problem on?
[String.prototype.localeCompare()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare)

## What is the problem?
Inconsistent Style

## What did you expect to see?
Consistent Style AFA white space within curly braces

Examples from the page:
```js
console.log(a.localeCompare(b, 'en', { sensitivity: 'base' }));

items.sort( (a, b) => a.localeCompare(b, 'fr', {ignorePunctuation: true}));

console.log('ä'.localeCompare('a', 'de', { sensitivity: 'base' }));

console.log("2".localeCompare("10", undefined, {numeric: true}));
```

### See also:
[JavaScript guidelines: Space after `if`](https://github.com/mdn/content/discussions/9901)

**Comment by teoli2003** [comment]
Thanks! I've opened a PR for this page. If you see other occurrences on other pages, feel free to report them (or to open a PR).
