### ISSUE TITLE
Issue with "cursor": Link to Specifications is not correct

### ISSUE THREAD

**Issue by stacker60** [mdn/content#14440]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

#### What information was incorrect, unhelpful, or incomplete?
Link to Specifications should be https://www.w3.org/TR/css-ui-4/#cursor

#### Specific section or headline?
Specifications 

#### What did you expect to see?
CSS cursor specs.

#### Did you test this? If so, how?
Yes, clicked on "CSS Basic User Interface Module Level 4
# cursor"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/cursor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/cursor/index.md
* Last commit: https://github.com/mdn/content/commit/56da604e4fc9c926015751a990496f0284bf4e41
* Document last modified: 2022-03-18T17:18:24.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this, but that existing spec link is actually correct as-is — we intentionally link to the https://drafts.csswg.org/css-ui/#cursor version rather than the https://www.w3.org/TR/css-ui-4/#cursor version
