### ISSUE TITLE
Confusion Regarding the Support of Editable Content In the Docs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1444]
@zicklag commented on [Tue Dec 08 2020](https://github.com/mdn/sprints/issues/3946)

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hey there, I am encountering a confusing "conflict" in the documentation. In the [Making content editable](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content) page it explains how to enable editable content in your web pages and references [`document.execCommand()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) which has a warning that the feature is obsolete. Both pages have been updated in 2020 so I couldn't determine whether or not the Editable Content page should also be marked as obsolete or whether the `document.execCommand()` API has gotten more standardized across browsers.

It would be great to clear this up. Thanks!

**Comment by sideshowbarker** [comment]
This seems to have been resolved by https://github.com/mdn/content/pull/1793, so I’m going ahead and closing this.
