### ISSUE TITLE
"Array() constructor": "...Note: this implies an array of arrayLength empty slots, not slots with actual undefined values..."

### ISSUE THREAD

**Issue by HelmZalee** [mdn/content#14441]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Array

#### What information was incorrect, unhelpful, or incomplete?
"...Note: this implies an array of arrayLength empty slots, not slots with actual undefined values..." 

#### Specific section or headline?
Parameters / arrayLength

#### What did you expect to see?
Something like "...every element has the value `undefined`...".

For brevity (and to avoid the passive), this might be written:
If a single argument `n` is passed, 0 ≤ n ≤ 2^32-1, the constructor returns an array of length `n` in which every element has the value `undefined`.  If `n` is outside that range, the constructor throws a `RangeError` exception.

#### Did you test this? If so, how?
Interactively set `yada = new Array(5)` followed by `yada[1]=== undefined`, which returned `true`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/array`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Array
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/array/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks @HelmZalee  for reporting. The existing documentation looks more accurate. That `yada[1] === undefined` is `true` could be a side effect of array access rather than the storage. Some evidence:
```
$ node
Welcome to Node.js v16.14.2.
Type ".help" for more information.
> let yada = new Array(5);
undefined
> yada
[ <5 empty items> ]
> yada[2] = undefined
undefined
> yada
[ <2 empty items>, undefined, <2 empty items> ]
> 
```
See also:  [The Array Constructor at 2ality.com](https://2ality.com/2012/12/arrays.html)

**Comment by HelmZalee** [comment]
Very interesting, and thank you @himanshugarg you have taught me something: An Array can be sparse.

I don't want to be argumentative, but I do want to learn, and yet still reply promptly.  So I will read further.  In the meantime, some comments.

- The [article ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) on the Array constructor does not mention sparse arrays.(!)  In fact, it does not contain the word  'sparse'.  That seems like an important omission.
- That an array is sparse is reflected only (as far as I know at the moment) in the way it is iterated.  Other than iterating over an array and counting the elements, I don't immediately see a way to know it is sparse.  You cannot query the non-existent element without getting undefined one way or another, and you won't know why it's undefined:

> sparse = [ , , 'c' ];
> Array(3) [ <2 empty slots>, "c" ]
> 
> sparse[0]===undefined
> true
> sparse[0]\*1
> NaN
> var a; a*1  //a is `undefined`
> NaN          //same result as sparse[0]*1

- I can guess that the implementation maintains, in effect, a 'list of unpopulated elements' so in any iteration, no operation on that element will be performed.  It  is not that they are "empty"; it is they do not _exist_.  If they _did_ exist, the thing wouldn't be sparse!  Gets a little esoteric...

At this point, I'd say (1) the article on the constructor would be more complete were it to mention sparse arrays and 
(2) to say that an element is 'empty' is semantically misleading: it does not _exist_.  

But, it looks like "empty slots" is now built in to the "engine", browser, interpreter, what ever it is, so that entering [,,,] prints the text [<3 empty slots>].  That is, it seems, only because the engine is privy to secrets of implementation we cannot see.  There are no slots.  Or as Gertrude Stein would say, "There's no _there_ there."

I've rambled on too much.  Apologies.  Hope you can set me straight!
