### ISSUE TITLE
Update the async/await docs in the "Learn web development" module

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1445]
@RussianCryptid commented on [Sun Dec 06 2020](https://github.com/mdn/sprints/issues/3945)

# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The issue concerns the following page: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await

In the "The downsides of async/await" section, a `timeTest` code from `fast-async-await.html` is provided as an example where we create and await promises separately and speed up the execution:
![image](https://user-images.githubusercontent.com/35928509/101290488-b361d780-3813-11eb-94be-1c78413acf53.png)

However, the solution used here can lead to unhandled promise rejection errors, as mentioned [in another reference doc about async functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) (see the "Examples" section):

![image](https://user-images.githubusercontent.com/35928509/101290430-549c5e00-3813-11eb-9fc7-94dc0bb2662d.png)
![image](https://user-images.githubusercontent.com/35928509/101290434-5c5c0280-3813-11eb-9688-a2a670dbd76a.png)

Additional, more detailed explanation about the downsides of this approach [can also be found on StackOverflow](https://stackoverflow.com/questions/46889290/waiting-for-more-than-one-concurrent-await-operation/46889489#46889489).

As a fix, a similar note highlighting the issues can be provided on the page, or perhaps the example can be reworked to use `Promise.all`.

**Comment by longm89** [comment]
@chrisdavidmills Hi Chris, could I work on this?

**Comment by chrisdavidmills** [comment]
@longm89 sure, that'd be great! I'll assign you now.

**Comment by longm89** [comment]
@chrisdavidmills Dear Chris, thanks a lot for assigning this issue to me. I fixed the issues pointed out by @RussianCryptid. I modified the example in fast-async-await.html, adding a rejected promise to show that one could get an unhandled promise and fix this problem using Promise.all() as said above.
