### ISSUE TITLE
"CSS Properties Reference":  "border-radius" and its constituent properties are missing

### ISSUE THREAD

**Issue by domleonard** [mdn/content#14458]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Properties_Reference

#### What information was incorrect, unhelpful, or incomplete?

CSS property "border-radius" and its constituent properties are missing from the CSS properties list.

#### Specific section or headline?

The CSS properties table.

#### What did you expect to see?

Entries (table rows) for 
[border-radius](https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius)
[border-top-left-radius](https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-left-radius)
    [border-top-right-radius](https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-right-radius)
    [border-bottom-right-radius](https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-right-radius)
    [border-bottom-left-radius](https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom-left-radius)

#### Did you test this? If so, how?

Searched page for "border-radius" with result "phrase not found".

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_properties_reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Properties_Reference
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_properties_reference/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by teoli2003** [comment]
I think this page is useless. I propose to make it a redirect to https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#index

Pinging @estelle to have a second opinion.

**Comment by estelle** [comment]
Addressed in https://github.com/mdn/content/pull/17746. Closing.

**Comment by estelle** [comment]
Agree. Page is totally useless.

**Comment by domleonard** [comment]
I agree completely:. To be honest I usually consult the  [Reference] page,
and after taking a link from the search box, thought that that was what I
was looking at - albeit a rolled back, edited or otherwise corrupted
version of it.

IMHO
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Properties_Reference
page can be dispensed with (deleted) altogether, and links to it should not
be capable of being displayed in the quick list of search suggestions. If
that is included in what is proposed by making it "redirect to the
Reference" you have my full support.
