### ISSUE TITLE
"max-content": Should specify that max-content represents the intrinsic maximum width or height depending on writing mode

### ISSUE THREAD

**Issue by a89529294** [mdn/content#14454]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/max-content

#### What information was incorrect, unhelpful, or incomplete?
Should specify that max-content represents the intrinsic maximum width or height depending on writing mode

#### Specific section or headline?
Add more explanation in the introduction.

#### What did you expect to see?
In wiriting-mode: horizontal-tb; max-content is the intrinsic max width. It has no effect when used with height like : height:max-content;
In writing-mode:vertical-lr or vertical-rl; max-content is the intrinsic max height. It has no effect when used with width.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/max-content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/max-content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/max-content/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by NsdHSO** [comment]
@ please assigned at me
