### ISSUE TITLE
Issue with "Using the Fetch API": Default request mode is `cors` not `no-cors`

### ISSUE THREAD

**Issue by alex-priiv** [mdn/content#14480]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

#### What information was incorrect, unhelpful, or incomplete?

The default request-mode for fetch is `no-cors`, not `cors`

#### Specific section or headline?

It's in the code block below [this header](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#supplying_request_options)

#### What did you expect to see?

The star indicating the default for `mode` should be on `no-cors`, not `cors`

#### Did you test this? If so, how?

This does not require testing, it is specified in the [whatwg spec](https://fetch.spec.whatwg.org/#concept-request-mode)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/fetch_api/using_fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fetch_api/using_fetch/index.md
* Last commit: https://github.com/mdn/content/commit/c4b6112d856dbb5fa7b929e5034499c605a51e08
* Document last modified: 2022-03-28T14:52:22.000Z

</details>

**Comment by sideshowbarker** [comment]
In fact for using the `fetch()` method the common case, the default request mode is `cors`:

https://fetch.spec.whatwg.org/#ref-for-dom-requestinit-mode
> [mode](https://fetch.spec.whatwg.org/#dom-requestinit-mode)
    A string to indicate whether the request will use CORS, or will be restricted to same-origin URLs. Sets _request_’s [mode](https://fetch.spec.whatwg.org/#dom-request-mode). If _input_ is a string, it defaults to "`cors`".

…where _input_ is the first argument to the `fetch` method — which in the common case is a string representing a URL (but can also instead be a `Request` object).

Given the above, it seems like the comment about the default mode in the example in the existing MDN article is correct per the spec — so I’m going ahead and closing this.
