### ISSUE TITLE
Content bug: <Gecko Guides>

### ISSUE THREAD

**Issue by woulfe68** [mdn/content#14494]
## What page(s) did you find the problem on?
On the Gecko home page, and Gecko getting started page
    - https://wiki.mozilla.org/Gecko:Home_Page
    - https://wiki.mozilla.org/Gecko:Getting_Started

## Specific page section or heading?
For the Gecko home page in the section "Are You In The Right Place?" 

For the gecko getting started page in section "Gecko:Getting Started" in the first sentence The first step is to **download and build Firefox**

## What is the problem?
hyperlink's on the Gecko home page and the Gecko getting started page direct to invalid addresses 

Bellow the page will be indicated by bold text, and the sentence in which the invalid hyperlink will be under, the text in the sentence that is the hyperlinked will be in square brackets, and the hyperlink URL will be bellow the sentence.

**Gecko home page**
Want to hack on Gecko? The [Developer Guide] is probably what you are looking for.
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide

**Gecko getting started page**
The first step is to [download and build Firefox]
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions

## What did you expect to see?

I expected the Gecko home page hyperlink to direct me to a developer guide provided by Mozilla and for the getting started page to direct me to a page that had instructions on downloading and building Firefox provided by Mozilla.

## Did you test this? If so, how?

I followed the hyper link for both of them

**Comment by sideshowbarker** [comment]
I’m going ahead and closing this, because https://wiki.mozilla.org/Gecko:Home_Page and https://wiki.mozilla.org/Gecko:Getting_Started are not part of MDN, so this problem should be reported elsewhere — at https://wiki.mozilla.org/Gecko:Getting_Started I guess

**Comment by woulfe68** [comment]
My bad, entering a bug report there
