### ISSUE TITLE
Where is the page for Function.prototype.prototype?

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1449]
@ugultopu commented on [Tue Dec 01 2020](https://github.com/mdn/sprints/issues/3936)

The `prototype` instance property on a function instance allows that function to be used as a constructor. Although the `prototype` property is mentioned in the [new operator] page as:

> You can add a shared property to a previously defined object type by using the [Function.prototype] property. This defines a property that is shared by all objects created with that function, rather than by just one instance of the object type. The following code adds a color property with value "original color" to all objects of type Car, and then overwrites that value with the string "black" only in the instance object car1. For more information, see [prototype][Function.prototype].

Both links point to the same URL which goes to nowhere. That is, the [Function.prototype] page is not present and it simply redirects to the [Function] page.

This is a big omission if I'm not missing something.

[new operator]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new
[Function.prototype]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/prototype
[Function]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function

**Comment by Ryuno-Ki** [comment]
Perhaps related to https://github.com/mdn/content/pull/1481 (check resolved comments there.)

**Comment by hamishwillee** [comment]
@Rumyra I probably the person best placed to decide if we need a separate `Function.prototype` page.

**Comment by sideshowbarker** [comment]
This might be related to the reorg of the docs that @Elchi3 did some time last year.

**Comment by Elchi3** [comment]
See https://github.com/mdn/sprints/issues/2571 for context. This was done for consistency with the API docs. I think we should close this issue.

**Comment by ayushi2019031** [comment]
I will like to work on this issue.

**Comment by Josh-Cena** [comment]
I'd like to re-open this, because we are clearly lacking a `Function.prototype.prototype` reference page.
