### ISSUE TITLE
feComposite docs/support is a mess

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1450]
@PeterConstable commented on [Tue Dec 01 2020](https://github.com/mdn/sprints/issues/3933)

# Request type

- [x] Correction or update

# Details
This pertains to the SVG feComposite element, as documented in MDN at <https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComposite>.

There is a complex example at the bottom of that page. Supposedly, per [CanIUse](https://caniuse.com/?search=fecomp), this is well supported in Firefox, Chrome and Edge. However, I cannot find a single implementation that reproduces the results shows at the bottom of that MDN page—not even close! Not Firefox; not Chrome; not Edge; not Adobe Illustrator...

So, I can't tell if the MDN documentation is correct, but nothing actually supports this (in spite of CanIUse reports), or if the MDN documentation is wrong.

**Comment by Ryuno-Ki** [comment]
> Supposedly, per [CanIUse](https://caniuse.com/?search=fecomp),

As far as I understand Can I Use, it defers to BCD here:
https://github.com/mdn/browser-compat-data/blob/26dd8f364aafbf822ca5f4bb46bce71c16df0998/svg/elements/feComposite.json

**Comment by Ryuno-Ki** [comment]
For the record: this is how it appears in Firefox:

![feComposite-broken](https://user-images.githubusercontent.com/3097194/105576428-05829c00-5d73-11eb-897d-a788383a242b.png)

You can see, that the red triangles are missing.

**Comment by hamishwillee** [comment]
See https://github.com/mdn/content/issues/1727 - I'm working on the BCD. The example depends on an element that doesn't work on anything except pre-Blink Edge.

**Comment by hamishwillee** [comment]
@Ryuno-Ki You're an SVG expert right? I'm working on (and not too concerned about) the BCD. However I'm not sure sure of a good example for feComposite - can you help?

Specifically I think the concept showing of showing how you might combine each of the types of image is pretty good to show the various types - over, in, automatic etc. However I don't know SVG well enough to create a good example for each.

**Comment by Ryuno-Ki** [comment]
Well, I got invited as SVG expert (but realised, that there is way more to learn!).
Please, do request a review by me.

Thanks for picking it up :heart:
