### ISSUE TITLE
Content bug: Remove references to caching WebAssembly Modules in indexedDB

### ISSUE THREAD

**Issue by evilpie** [mdn/content#14520]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiate

> shared via [postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage) or [cached in IndexedDB](https://developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules).

There are probably more references, probably best to search for indexedDB under WebAssembly/

## What is the problem?

IndexedDB caching was removed from Firefox 4 years ago, I don't think we need to keep the documentation for it. https://bugzilla.mozilla.org/show_bug.cgi?id=1469395

**Comment by wbamberg** [comment]
So this whole page should be removed:

> https://developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules

...is that right?

(as well as some other bits of cleanup)

**Comment by evilpie** [comment]
I think we can just delete whole page. I am not sure who we could ask for details.

**Comment by hamishwillee** [comment]
I'm late to the party, but IMO the page is out of date but the use case is not. It would be better to replace this with a more recent caching mechanism. 

So would suggest finding someone who could help do that. If not, maybe deleting the page and leaving it as a redlink?
