### ISSUE TITLE
Confusing warning about async runtime.onMessage listeners

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1452]
@nickgaya commented on [Sun Nov 29 2020](https://github.com/mdn/sprints/issues/3927)

# Request type

- [ ] New documentation
- [x] Correction or update

# Details

The documentation for [`runtime.onMessage.addListener()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage#addListener_syntax) has a warning box that states:

> **Important:** Do not call `addListener()` using an `async` function. This will cause the listener to consume every message it receives, effectively blocking all other listeners from receiving and processing messages.

I found this confusing.  The underlying issue being described is that an async function always returns a Promise, so passing an async function to `addListener()` only makes sense if you want a single listener to respond to all messages.

I'm not sure how best to improve the wording.  Maybe something like this:

> **Important:** If you call `addListener()` using an `async` function, the listener will return a Promise for every message it receives, preventing other listeners from responding. If you only want the listener to respond to messages of a certain type, you must check the message type synchronously before returning a Promise.

---

@Cimeone commented on [Thu Dec 03 2020](https://github.com/mdn/sprints/issues/3927#issuecomment-737946034)

I'd be happy to address this, could it please be assigned to me.

---

@chrisdavidmills commented on [Thu Dec 03 2020](https://github.com/mdn/sprints/issues/3927#issuecomment-738030385)

@Cimeone assigned, thanks.

**Comment by sideshowbarker** [comment]
I’ve opened https://github.com/mdn/content/pull/3903 with a fix for this.
