### ISSUE TITLE
Issue with "Drag Operations": In sidebar under Related Topics > Events there is a dragexit event, which doesn't exist

### ISSUE THREAD

**Issue by spollard** [mdn/content#14531]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Drag_operations

#### What information was incorrect, unhelpful, or incomplete?
In sidebar under Related Topics > Events there is a dragexit event, which doesn't exist.

#### Specific section or headline?

Sidebar > Related Topics > Events >  Document : dragexit

#### What did you expect to see?
I expected to see only events that exist. :-)

#### Did you test this? If so, how?
I clicked on the 'dragexit' event link and it went to "Page not found".

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/html_drag_and_drop_api/drag_operations`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Drag_operations
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
* Last commit: https://github.com/mdn/content/commit/b7aafea1ab7cfee11a7e854a4b5c83a6e6d329d4
* Document last modified: 2022-02-02T09:11:35.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #14539 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
