### ISSUE TITLE
Sticky flag doesn't entirely mask the global flag

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1454]
@fireattack commented on [Fri Nov 13 2020](https://github.com/mdn/sprints/issues/3887)

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

It says
>A regular expression defined as both sticky and global ignores the global flag.

But this doesn't seem to match my observation.
```js
console.log('##-#'.replace(RegExp('#', 'gy'), 'x'));
console.log('##-#'.replace(RegExp('#', 'y'), 'x'));
console.log('##-#'.replace(RegExp('#', 'g'), 'x'));
```

The above all have different behaviors:

```
xx-#
x#-#
xx-x
```
(And they're as expected.)

---

@fireattack commented on [Fri Nov 13 2020](https://github.com/mdn/sprints/issues/3887#issuecomment-726635491)

Same error can be seen at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/global 

Edit: a very detailed article about difference between `y`, `g`, `yg`: https://2ality.com/2020/01/regexp-lastindex.html

**Comment by Ryuno-Ki** [comment]
@rauschma It would be great, if you could lend us your expertise on this!

**Comment by rauschma** [comment]
`/y` and `/yg` only differ for the following methods:

* `.replace()` replaces once vs. replaces multiple times
* `.replaceAll()` throws if `/g` is missing
* `.match()` works like `.exec()` vs. returns an Array with matches
* `.matchAll()` throws if `/g` is missing

For `.exec()` and `.test()`, there is no difference.

See this table: https://gist.github.com/rauschma/8bd701d07f936c0c335681deaab612b5

**Comment by himanshugarg** [comment]
Thanks @rauschma . @Ryuno-Ki any thoughts on how you'd like this to be handled given that the fix is requested on the pages for the flags but the behavior differs in the context of specific functions?

**Comment by Ryuno-Ki** [comment]
I'm deferring to @yari-content-javascript (= @Rumyra @Elchi3 and @sideshowbarker) for an answer

**Comment by Rumyra** [comment]
Seems to me that @rauschma 's info is worth mentioning on the specific method pages (if not present, I didn't check), as well as a relevant note on the pages for flags.

This can also be added to 'See also' sections https://2ality.com/2020/01/regexp-lastindex.html

**Comment by rauschma** [comment]
Thanks @Rumyra! This is a newer version of this content: https://exploringjs.com/impatient-js/ch_regexps.html#regexp-flags-gy
