### ISSUE TITLE
Iteration protocol doesn't mention the return() method.

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1457]
@theemathas commented on [Mon Nov 09 2020](https://github.com/mdn/sprints/issues/3874)

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

The [iteration protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) page does not mention the [return() method](https://stackoverflow.com/questions/42380087/how-does-break-work-in-for-of-loop-when-stopping-a-generator) that seems to be an optional part of the iterator protocol. Also note that the page for [Generator.prototype.return()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/return) does not mention why this return method exists.

Unfortunately, I am unable to find proper documentation of this anywhere on the internet, possibly because "return" isn't a google-friendly method name.

MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols

**Comment by Ryuno-Ki** [comment]
Table 64 and 67 of the [official spec](https://tc39.es/ecma262/#sec-iterator-interface) could not be used as a starting point?
