### ISSUE TITLE
viewing the black border in dark theme is difficult 

### ISSUE THREAD

**Issue by iamparthvaghela** [mdn/content#14580]
## What is the new suggestion?
can include a light background for viewing the border more effectively

## Why is it important or useful?
Users don't need to change from dark mode to light mode to view the black borders

How many pages are likely to be needed?
How much time do you think this work should take? A few hours? A week? A month?
a few hours maybe 

Will the work enable learners or professionals to achieve their goals better?
Does it address critical needs in the web industry?
Is the work an operational necessity, i.e. is not having it a security risk?
Does the content help make the web more ethical?
 -->

## Other supporting information

https://developer.mozilla.org/en-US/docs/Web/CSS/border-style

![border-style - CSS_ Cascading Style Sheets _ MDN - Google Chrome 02_04_2022 14_18_25](https://user-images.githubusercontent.com/82269041/161375367-783aedbe-7e0d-431d-be84-3b1beb444ea9.png)
![border-style - CSS_ Cascading Style Sheets _ MDN - Google Chrome 02_04_2022 14_18_34](https://user-images.githubusercontent.com/82269041/161375371-be96bf7c-67a7-4624-9d3d-678ad9f0c090.png)

**Comment by AnilSeervi** [comment]
Opened mdn/interactive-examples#2075 as a possible fix by explicitly setting the `.output` bg to `#fff`
