### ISSUE TITLE
Issue with "revert": user-agent stylesheet actually takes precedence over whether the property is inherited or not

### ISSUE THREAD

**Issue by casinero** [mdn/content#14589]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/revert

#### What information was incorrect, unhelpful, or incomplete?

> it resets the property to its inherited value if it inherits from its parent or to the default value established by the user agent's stylesheet

The sentence reads as if only when the property is a non-inherited one the user agent's default will take effect.

However user-agent stylesheet seems to take precedence over whether the property is inherited or not.

By the way, I'm a beginner learner and asked this for clarification on [Mozilla Discourse](https://discourse.mozilla.org/t/does-color-revert-inherit-parent-elements-color-value-or-reset-to-browser-default-for-the-selected-element/95414). Someone there replied suggesting that I should open an issue here.

#### Specific section or headline?
The first paragraph.

#### What did you expect to see?
_it resets the property to the default value established by the user agent's stylesheet, or ..._, not sure.

#### Did you test this? If so, how?
[https://jsfiddle.net/cd1o3j6x/1/](https://jsfiddle.net/cd1o3j6x/1/)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/revert`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/revert
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/revert/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by melink14** [comment]
Just as a passer by who noticed the opposite behavior and [filed an issue](https://github.com/mdn/content/issues/14679) wanted to give my thoughts here:

I think the key point from the spec is that `revert` goes back one level in the cascade spec as it's first priority. So an author style is reverted to a user then user-agent style. "is calculated as if no [author-origin](https://drafts.csswg.org/css-cascade/#cascade-origin-author) rules were specified for this property on this element."

In the case of anchor tags though, the user agent style applies to them directly which means if there is no author style they'll take on the user agent style. (For reference in chrome the user agent style looks like:
```css
a:-webkit-any-link {
    color: -webkit-link;
    cursor: pointer;
    text-decoration: underline;
}
```
)

On the other hand, if you look at a version where you just style li (has no specific user agent override for color) then the inherited green property is preserved: https://jsfiddle.net/cd1o3j6x/1/ (it doesn't revert to the user agent default of black)

Essentially, all inherited values are preserved including those which are set by the user agent. If there is no inherited value then it uses the default established by the user agent.

I think this is confusing enough that having a dedicated section with examples would be useful though.
