### ISSUE TITLE
Issue with "content_security_policy": Extension does not load when 'unsafe-eval' is set

### ISSUE THREAD

**Issue by guest271314** [mdn/content#14592]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy

#### What information was incorrect, unhelpful, or incomplete?

> Allow [eval() and friends](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy#eval%28%29_and_friends):
> 
> "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self';"

#### Did you test this? If so, how?

Yes.

```
{
  "name": "JSDOM in MV3 ServiceWorker",
  "version": "1.0",
  "manifest_version": 3,
  "background": {
    "service_worker": "background.js",
    "type": "module"
  },
  "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self';",
  "action": {},
  "author": "guest271314"
}
```

results in

```
Failed to load extension
File
~/JSDOM
Error
Invalid value for 'content_security_policy'.
Could not load manifest.
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
* Last commit: https://github.com/mdn/content/commit/e752a8fe731fbdb9061e39a6e2b797a7ccb7e2b5
* Document last modified: 2022-01-19T17:57:58.000Z

</details>

**Comment by Rob--W** [comment]
Fixed by #15704.
