### ISSUE TITLE
Fout foit foft

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#146]
https://github.com/mdn/yari/issues/1924

https://css-tricks.com/fout-foit-foft/
I don't find nothing about this from Google.

**Comment by peterbe** [comment]
How we implement web fonts belong to Yari, not the content.

**Comment by mattiapontonio** [comment]
Ok but i think the acronym should be maybe mentioned

**Comment by peterbe** [comment]
On https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content it already explains what it means. 

*"This makes it much more likely that the font will be available for the page render, cutting down on FOUT (flash of unstyled text)."*

**Comment by mattiapontonio** [comment]
_before browsers' main rendering machinery kicks in_

So `preload` solves everyting...
Is not clear of it is _the_ solution.
