### ISSUE TITLE
HTTP > HTTP caching: Revalidate against spec and subedit

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1460]
@hamishwillee commented on [Thu Nov 05 2020](https://github.com/mdn/sprints/issues/3864)

## URL(s)

[Web technology for developers >  HTTP > HTTP caching](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching )

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

- Add docs for `s-max-age` (missing)
- Re-validation whole page against the spec to verify that nothing is missing.
- Subedit for English ("correct" but parts are not particularly readable for non-native speakers)

This follows on from discussion in  https://github.com/mdn/sprints/issues/3257

---

@Jxck commented on [Tue Nov 10 2020](https://github.com/mdn/sprints/issues/3864#issuecomment-724386720)

> Can you please create specific issues for specific problems. This post is for a general revalidation - easy for a specific question hidden in an issue like this to get missed.

Oh, I misunderstood that problem around cache section should gathered in here.
I opened new issue in #3877

---

@hamishwillee commented on [Tue Nov 10 2020](https://github.com/mdn/sprints/issues/3864#issuecomment-724389962)

No worries. I have deleted my response, and will delete this and your comment shortly :-) Thanks very much.

**Comment by sideshowbarker** [comment]
This year the https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching page got some very extensive and careful updates and improvements from a domain expert, so I think we can consider this issue resolved.
