### ISSUE TITLE
Are there really two different ways of handling two-digit years?

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1461]
@nickshanks commented on [Wed Nov 04 2020](https://github.com/mdn/sprints/issues/3860)

## URL(s)
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Compatibility_notes
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Two_digit_years_map_to_1900_–_1999
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setYear#Description

## Request type

- [ ] New documentation
- [X] Correction or update

## Details
The Date class page and the setYear page both say two-digit years are parsed as an offset to the year 1900 (formerly, in the H3: "Two digit years map to 1900 – 1999")  
The Date.parse page says that `Date.parse()` and `new Date()` use values 50-99 to mean 1950-1999 and 0-49 to mean 2000-2049. Thus this apparently differs from how `Date.prototype.setYear()` handles two-digit years.

Are the two implementations of two-digit-year handling actually divergent? If so, why isn't this made explicit in the documentation for both functions? If not, I presume the documentation for setYear(), on both the setYear page and the class page, is incorrect.

**Comment by sideshowbarker** [comment]
I’ve opened #7465 with a fix for this.
