### ISSUE TITLE
Out of date Edge information in Build a cross browser extension

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1462]
@Poopooracoocoo commented on [Thu Oct 29 2020](https://github.com/mdn/sprints/issues/3839)

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Well Edge is now based on Chromium.

It uses the `chrome.` namespace (edit: actually I think they equated the `browser.` namespace with `chrome.` for backwards compatibility). Basically everything related to _developing_ extensions Edge could be deleted as it's now just Chromium. I think the publishing requirements are still there though. I don't think you need additional packaging anymore as Microsoft Edge no longer uses the Microsoft Store. 

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/

---

@chrisdavidmills commented on [Thu Oct 29 2020](https://github.com/mdn/sprints/issues/3839#issuecomment-718556089)

Thanks @Poopooracoocoo . This is something we need to look into.

---

@Cimeone commented on [Thu Dec 03 2020](https://github.com/mdn/sprints/issues/3839#issuecomment-737893957)

I'd be happy to look into this, can this be assigned to me.

---

@chrisdavidmills commented on [Thu Dec 03 2020](https://github.com/mdn/sprints/issues/3839#issuecomment-737896941)

Sure thing @Cimeone, happy to let you have a go.

**Comment by Ryuno-Ki** [comment]
For the record: @Cimeone seem not to be a MDN team member and thus cannot be assigned an issue in GitHub's UI. You'll need some kind of imagination here :-)
