### ISSUE TITLE
Content bug: redirect old files

### ISSUE THREAD

**Issue by estelle** [mdn/content#14628]
## Redirect the following files
* [x] From:  /en-us/docs/web/accessibility/aria/aria_techniques/using_the_link_role to: /en-us/docs/web/accessibility/aria/Roles/link_role
* [x] From:  /en-us/docs/web/accessibility/aria/aria_techniques/using_the_radio_role to: /en-us/docs/web/accessibility/aria/Roles/radio_role
* [x] From:  /en-us/docs/web/accessibility/aria/aria_techniques/using_the_alertdialog_role to: /en-us/docs/web/accessibility/aria/Roles/alertdialog_role
* [x] From:  /en-us/docs/web/accessibility/aria/aria_techniques/using_the_log_role to: /en-us/docs/web/accessibility/aria/Roles/log_role
* [x] From:  /en-us/docs/web/accessibility/aria/aria_techniques/using_the_slider_role to: /en-us/docs/web/accessibility/aria/Roles/slider_role
* [x] From:  /en-us/docs/web/accessibility/aria/aria_techniques/using_the_article_role to: /en-us/docs/web/accessibility/aria/Roles/article_role
* [x] From:  /en-us/docs/web/accessibility/aria/aria_techniques/using_the_presentation_role to: /en-us/docs/web/accessibility/aria/Roles/presentation_role
* [x] From:  /en-us/docs/web/accessibility/aria/aria_techniques/using_the_status_role to: /en-us/docs/web/accessibility/aria/Roles/status_role
* [x] From:  /en-us/docs/web/accessibility/aria/aria_techniques/using_the_group_role to: /en-us/docs/web/accessibility/aria/Roles/group_role
* [x] From:  /en-us/docs/web/accessibility/aria/aria_techniques/using_the_progressbar_role to: /en-us/docs/web/accessibility/aria/Roles/progressbar_role
* [x] From:  /en-us/docs/web/accessibility/aria/aria_techniques/using_the_toolbar_role to: /en-us/docs/web/accessibility/aria/Roles/toolbar_role

**Comment by teoli2003** [comment]
@estelle Do you plan to work yourself on this, or do you want help?

**Comment by estelle** [comment]
@teoli2003 Yes! I forgot about this ticket, but thought I had created the redirects successfully a while ago, but apparently I didn't and the pages are 404'ing.
