### ISSUE TITLE
Issue with "Test your skills: values and units": broken link

### ISSUE THREAD

**Issue by Disney-Banje** [mdn/content#14636]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_tasks

#### What information was incorrect, unhelpful, or incomplete?
The link under Task One for conversion seems to not be working.

#### Specific section or headline?
Under Task One for conversions for the hex color

#### What did you expect to see?
Just wanted to suggest whether it can be updated. Thanks again.

#### Did you test this? If so, how?
I tried to open the link, but it seems not to be working, however, I found another option🙌👍. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/values_tasks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_tasks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/values_tasks/index.md
* Last commit: https://github.com/mdn/content/commit/672bace59f60c4931e5cdde8eb32919c924bd191
* Document last modified: 2022-03-14T00:26:56.000Z

</details>

**Comment by sideshowbarker** [comment]
If you mean the https://convertingcolors.com/hex-color-86DEFA.html link — in the _You can find conversions for the hex color at [this link](https://convertingcolors.com/hex-color-86DEFA.html)_ — then, that link works fine for me. Can you re-try it?

**Comment by Disney-Banje** [comment]
Thanks, it's working 🙏.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
