### ISSUE TITLE
AudioParam - automationRate undocumented

### ISSUE THREAD

**Issue by rowild** [mdn/content#14637]
#### What information was incorrect, unhelpful, or incomplete?

The link to automationRate leads to a 404.

#### What did you expect to see?

A page which documents what `automationRate` is or was good for, whether it is deprecated or not, and "how new/old" it is (introduced 2020-02, e.g.)

#### Did you test this? If so, how?

I found a bit of info here: 
https://developer.mozilla.org/en-US/docs/Web/API/AudioParamDescriptor
But that does not really cover the topic.

<details>
<summary>MDN page report details</summary>

* Query: `api.AudioParam`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioParam
* Report started: 2022-04-03T11:05:12.802Z

</details>

**Comment by hamishwillee** [comment]
Yes some documentation work is needed here. We don't document dictionaries any more but put them where they are used.

FYI only @rowild some information about where it is introduced can be found in the [compatibility table for `AudioParam`](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam#browser_compatibility).

**Comment by Josh-Cena** [comment]
Hi! I'm closing all issues that are in https://openwebdocs.github.io/web-docs-backlog/all/. These features are automatically in our backlog and don't need separate issues to track.
