### ISSUE TITLE
[CSS] Expose HDR video support to content

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#14640]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Draft media query `video-dynamic-range` - in spec here: https://www.w3.org/TR/mediaqueries-5/#descdef-media-video-dynamic-range / https://drafts.csswg.org/mediaqueries-5/#video-dynamic-range
- `dynamic-range` - https://drafts.csswg.org/mediaqueries-5/#dynamic-range

WPT tests (FYI only)
- https://wpt.live/css/mediaqueries/dynamic-range.html
- https://wpt.live/css/cssom-view/cssom-view-window-screen-interface.html

Not in BCD or MDN.

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1751217

**Comment by Rumyra** [comment]
Closing in favour of https://github.com/mdn/content/issues/14405 👍
