### ISSUE TITLE
Triage the webaudio-example repo

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1464]
@Rumyra commented on [Thu Oct 22 2020](https://github.com/mdn/sprints/issues/3821)

webaudio-examples repo has some outstanding issues and PRs which need to looked at

Be good to get around to this sometime so adding it as a low priority issue so it gets on my work list - @Rumyra

**Comment by Rumyra** [comment]
Closing this issue as it's not related to content, but rather the webaudio-examples repo
