### ISSUE TITLE
Issue with "Cross-Origin Resource Sharing (CORS)": missing Range as a safelisted request-header

### ISSUE THREAD

**Issue by dotnetCarpenter** [mdn/content#14654]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

`Range` was added as a safe-listed header as long as the value is in a particular format, which aligns with formats the browser uses when requesting media and resuming downloads.

#### What information was incorrect, unhelpful, or incomplete?

Apart from the headers automatically set by the user agent (for example, [Connection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection), [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent), or [the other headers defined in the Fetch spec as a forbidden header name](https://fetch.spec.whatwg.org/#forbidden-header-name)), the only headers which are allowed to be manually set are [those which the Fetch spec defines as a CORS-safelisted request-header](https://fetch.spec.whatwg.org/#cors-safelisted-request-header), which are:
[Accept](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept)
[Accept-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language)
[Content-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Language)
[Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) (please note the additional requirements below)

#### Specific section or headline?

[Simple requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests)

#### What did you expect to see?

Apart from the headers automatically set by the user agent (for example, [Connection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection), [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent), or [the other headers defined in the Fetch spec as a forbidden header name](https://fetch.spec.whatwg.org/#forbidden-header-name)), the only headers which are allowed to be manually set are [those which the Fetch spec defines as a CORS-safelisted request-header](https://fetch.spec.whatwg.org/#cors-safelisted-request-header), which are:
[Accept](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept)
[Accept-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language)
[Content-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Language)
[Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) (please note the additional requirements below)
**[Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) (only with a [simple range header value](https://fetch.spec.whatwg.org/#simple-range-header-value), e.g. `bytes=0-` or `bytes=127-255`)**

> Note: Firefox has not implemented `Range` as a safelisted request-header yet. See [bug 1733981](https://bugzilla.mozilla.org/show_bug.cgi?id=1733981)

#### Did you test this? If so, how?
WPT tests: 
+ https://wpt.fyi/results/cors/cors-safelisted-request-header.any.html
+ https://github.com/web-platform-tests/wpt/pull/33488 (not merged yet)

My own test: https://dotnetcarpenter.github.io/bug-firefox-fetch-cors/

Shipped in Chromium: https://chromestatus.com/feature/5652396366626816
Patch available for WebKit: https://bugs.webkit.org/show_bug.cgi?id=231174
Not implemented in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1733981

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/index.md
* Last commit: https://github.com/mdn/content/commit/b69b942f36781fd548bbffca077103352333ebda
* Document last modified: 2022-02-21T22:26:49.000Z

</details>

**Comment by dotnetCarpenter** [comment]
@sideshowbarker I can do it! :)

**Comment by sideshowbarker** [comment]
> @sideshowbarker I can do it! :)

Yes please 😄

**Comment by dotnetCarpenter** [comment]
@sideshowbarker done 👍 https://github.com/mdn/content/pull/14657
