### ISSUE TITLE
Issue with "BigInt": docs suggest monkey-patching BigInt.prototype

### ISSUE THREAD

**Issue by crabmusket** [mdn/content#14676]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

#### What information was incorrect, unhelpful, or incomplete?

In the section **Use within JSON**, this is a recommended "solution" to including BigInts in objects serialized to JSON:

```js
BigInt.prototype.toJSON = function() { return this.toString()  }
```

There are two problems:

1. This seems to be against prevailing wisdom in the JS ecosystem: monkey-patching prototypes of builtins has been a historic issue.
2. The solution doesn't show how to _parse_ BigInts _from_ JSON.

A safer solution is to use JSON's "replacer" and "reviver" parameters, as detailed in [this article](https://golb.hplar.ch/2019/01/js-bigint-json.html#client-deserialization). I'd be happy to contribute an example of this to the docs if that's desired.

I can't tell from the [page history](https://github.com/mdn/content/commits/main/files/en-us/web/javascript/reference/global_objects/bigint/index.md) when or why this section was introduced. I considered this may have been discussed before. Searching [issues](https://github.com/mdn/content/issues?q=is%3Aissue+bigint) does not turn up any relevant results AFAICT.

#### Specific section or headline?

**Use within JSON**

#### What did you expect to see?

I did not expect to see monkey-patching a builtin class recommended by official MDN docs.

#### Did you test this? If so, how?

The code works, but is contrary to best practises in the ecosystem.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/bigint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/bigint/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by sideshowbarker** [comment]
> A safer solution is to use JSON's "replacer" and "reviver" parameters, as detailed in [this article](https://golb.hplar.ch/2019/01/js-bigint-json.html#client-deserialization)

100% agreed

> I'd be happy to contribute an example of this to the docs if that's desired.

Yes please

**Comment by sideshowbarker** [comment]
> I can't tell from the [page history](https://github.com/mdn/content/commits/main/files/en-us/web/javascript/reference/global_objects/bigint/index.md) when or why this section was introduced.

It was in the source in the wiki days before the time when we migrated all the content over here to this GitHub. That means it was added at the time when basically anybody could stroll in and make a change directly to the source without it needing to be reviewed or approved by anybody else. So it’s not something we can assume was added by somebody who understood what they were doing, nor reviewed (or even noticed) by anybody else.

I personally kind of liked the anarchy of old wiki system — but one of the consequences/legacies of it is that it’s left us with a significant cases like this one, where somebody make a drive-by change that added something bad/wrong to an article. But I think we’ve got enough eyes and attention on the content now that cases like this one are steadily getting found and fixed.

**Comment by crabmusket** [comment]
Great, I'll work on a minimal example of using a replacer/reviver. I'll take the approach of looking for a specific key in the object to replace/revive, rather than doing any sort of fancy value formatting to automatically recognise bigints.
