### ISSUE TITLE
Issue with "ImageDecoder": some properties missing

### ISSUE THREAD

**Issue by chcunningham** [mdn/content#14670]
@rachelandrew @jpmedley 

MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ImageDecoder

#### What information was incorrect, unhelpful, or incomplete?

* method `isTypeSupported()` is undocumented
* property `type` is undocumented (was unspec'ed, but we've since [added it](https://w3c.github.io/webcodecs/#dom-imagedecoder-type))
* method `decode()` is documented but not linked from the browser compat table
* the browser compat table lists all attributes as experimental, but they are stable (no expected changes)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/imagedecoder`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ImageDecoder
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/imagedecoder/index.md
* Last commit: https://github.com/mdn/content/commit/2cd706358b9366dd00fd2d64eb0a1b776ab221f8
* Document last modified: 2022-03-19T06:47:26.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by #16951
