### ISSUE TITLE
"JavaScript modules": Rename the first use of 'modules' in the file path to 'top-modules' so there is no opportunity for confusion

### ISSUE THREAD

**Issue by eltimbalino** [mdn/content#14677]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

#### What information was incorrect, unhelpful, or incomplete?
So for example:

/js-examples/**modules**/basic-modules/**modules**/square.js

becomes

./modules/square.js

#### What did you expect to see?
So for example:

/js-examples/**top-modules**/basic-modules/**modules**/square.js

becomes

./modules/square.js

#### Did you test this? If so, how?
This is very minor, but it really bothers me when instructional examples use duplicated terms. In this case I would like to see the first use of 'modules' in the file path renamed to 'top-modules' so there is no opportunity for confusion.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/modules`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/modules/index.md
* Last commit: https://github.com/mdn/content/commit/2873c93ec645c6a19cba8f9c3451d15af0ca20f4
* Document last modified: 2022-04-03T17:11:02.000Z

</details>

**Comment by wbamberg** [comment]
Or maybe "module-examples" since that's what they are?

**Comment by eltimbalino** [comment]
> 

@wbamberg Yes, "module-examples" would be good. 
@sideshowbarker Thanks for tidying up my title. I didn't notice it, but will get it right in future.

**Comment by wbamberg** [comment]
I just filed https://github.com/mdn/js-examples/pull/17 for the js-examples part of this. If it gets merged we should update https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules with the right paths.

**Comment by panyachai2018-crypto** [comment]
Ioio
