### ISSUE TITLE
Issue with "ImageDecoder": requesting simple example

### ISSUE THREAD

**Issue by chcunningham** [mdn/content#14671]
@rachelandrew @jpmedley 

MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ImageDecoder

#### What information was incorrect, unhelpful, or incomplete?

The document could be improved by adding a simple example like 
https://github.com/dalecurtis/image-decoder-api/blob/master/explainer.md#example-1-animated-gif-renderer

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/imagedecoder`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ImageDecoder
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/imagedecoder/index.md
* Last commit: https://github.com/mdn/content/commit/2cd706358b9366dd00fd2d64eb0a1b776ab221f8
* Document last modified: 2022-03-19T06:47:26.000Z

</details>

**Comment by bsmth** [comment]
Hi @chcunningham - I think this has been fixed in https://github.com/mdn/content/pull/16951

If it looks better, I would close this issue. Let me know what you think.
Thanks a lot :)

**Comment by wbamberg** [comment]
Let's close this, I agree https://github.com/mdn/content/pull/16951 improves things.
