### ISSUE TITLE
Issue with "Strict mode": Consider renaming function 'strict()' to something else for clarity

### ISSUE THREAD

**Issue by eltimbalino** [mdn/content#14680]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

#### What information was incorrect, unhelpful, or incomplete?
function strict() {
    // because this is a module, I'm strict by default
}
export default strict;

#### What did you expect to see?
function strict_function() {
    // because this is a module, I'm strict by default
}
export default strict_function;
#### Did you test this? If so, how?

I'm not sure if this suggestion is correct or not, because I don't understand what the line:
export default strict;
does. If it is saying "When doing exports, default to make them all strict" then don't put the new function name here.
If it is saying "Export the function named 'strict' ", then please change the name of the function to 'strict_function'.

I have no idea why tutorials don't make functions and variables distinct from the subject they're teaching, but please change this culture. I've seen way too many examples of:
let Button = new button
When it could so easily be:
let my_Button = new button
and avoid all of the confusion.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/strict_mode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/strict_mode/index.md
* Last commit: https://github.com/mdn/content/commit/76a015ffc44bd29c93e725366ad023171e6c7e7d
* Document last modified: 2022-03-27T18:17:05.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/17679

**Comment by teoli2003** [comment]
Closing per comment.
