### ISSUE TITLE
Missing pages for CSSDocumentRule, CSSFontFeatureValuesRule and CSSViewportRule

### ISSUE THREAD

**Issue by iamzapata** [mdn/content#14697]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSSRule

#### What information was incorrect, unhelpful, or incomplete?
The  CSSDocumentRule, CSSFontFeatureValuesRule and CSSViewportRule rules are listed, but not links are attached to them.

#### What did you expect to see?
An icon or a note explaining why there is no content for them.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/cssrule`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSSRule
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/cssrule/index.md
* Last commit: https://github.com/mdn/content/commit/672bace59f60c4931e5cdde8eb32919c924bd191
* Document last modified: 2022-03-14T00:26:56.000Z

</details>

**Comment by maridoroshuk** [comment]
@iamzapata  
Hi! That's why, the articles have not been written yet

![image](https://user-images.githubusercontent.com/59647513/161960158-c4615cdb-1919-4647-8db5-b9a10d0c8d11.png)

**Comment by iamzapata** [comment]
Hi @maridoroshuk I see! 

When I was going over this section I didn't notice the popup, I guess I didn't leave the cursor long enough over them. I'm not a UX expert, but perhaps having an icon (similar to the deprecated icon) next to the content would make it clearer.
