### ISSUE TITLE
Content bug: Printing guide looks very dated

### ISSUE THREAD

**Issue by Elchi3** [mdn/content#14694]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/Guide/Printing

## Specific page section or heading?

Code examples

## What is the problem?

The guide looks quite dated. Not sure if document.write and on- event handlers should be in the code example. Also, _I believe_ (really not an expert here) CSS print style sheets should always be preferred. The `beforeprint` and `afterprint` events should only be considered in edge cases, _I think._

## What did you expect to see?

A modern guide on how to use web platform features (probably mainly CSS) to optimize web sites for printing.

## Did you test this? If so, how?

I did not.

**Comment by Josh-Cena** [comment]
This has been renovated across many PRs and I think it's fine now
