### ISSUE TITLE
`HTML Drag and Drop API` and `Drag Operations` shows 404

### ISSUE THREAD

**Issue by AbihaFatima** [mdn/content#14702]
While going through the docs, I found that [HTML Drag and Drop API](/en-US/docs/Web/API/HTML_Drag_and_Drop_API) and [Drag Operations](/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Drag_operations) directs to GitHub page with error 404.
https://github.com/mdn/content/blob/393e1c92836968cc63e0e0bef86c1d735f125952/files/en-us/web/api/html_drag_and_drop_api/file_drag_and_drop/index.md?plain=1#L95-L96

**Comment by teoli2003** [comment]
Hi! I'm not sure where you found the GitHub links, but on the production site, both links work for me:
[
HTML Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API) and [Drag Operations](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Drag_operations)

**Comment by teoli2003** [comment]
Closing per my [comment](https://github.com/mdn/content/pull/14706#issuecomment-1088687859) in the PR. I think there is a misunderstanding here.
