### ISSUE TITLE
Stepping down from the content team

### ISSUE THREAD

**Issue by ericwbailey** [mdn/content#14708]
I would like to be removed from the content team. 

The scope of concerns of my current role is wide and oftentimes dips into things that are beyond my level of knowledge. I am hoping to still contribute to accessibility concerns on the MDN as an individual contributor, however.

I would also like to voice my concern for offline capability only being available to MDN Plus. A development job is a really effective way to get upwards social mobility, and this is a feature that would be very valuable to people with metered data plans and intermittent connections. I hope Mozilla reconsiders this choice.

In addition, I'd like to say thank you for the support from other maintainers over the past few years. Your time and expertise are valued and appreciated, and the internet is in a better shape because of it.

**Comment by estelle** [comment]
I was looking for a "needs to be undone" label, but there is none.  Thank you for everything you've done for MDN, accessibility, and, really, humanity. I know this isn't "goodbye", just "I won't be around as much". 

Also, I agree that a "reduce bandwidth usage" shouldn't be a paid feature as it is something that only those who can afford bandwidth can get makes no kind of sense.

**Comment by wbamberg** [comment]
Thanks so much, @ericwbailey , for all your work as an mdn/content maintainer. We'll miss you, and I hope we will still see you around MDN in the future.

**Comment by schalkneethling** [comment]
Hey @ericwbailey,

As others have said here, we are all immensely grateful for all of the work you have done on MDN Web Docs. Thanks to people like yourself, we have the best documentation on the internet. As requested, we have removed you from all the relevant teams, so you should no longer be receiving notifications for pull request reviews, etc.

If you do, please do let us know. We look forward to seeing future contributions from you and wish you all of the best.

The MDN Web Docs team ❤️
