### ISSUE TITLE
Issue with "HTML text fundamentals": Missing formatting/emphasis

### ISSUE THREAD

**Issue by SinnahSaint** [mdn/content#14716]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals

#### What information was incorrect, unhelpful, or incomplete?

"For example, the following two sentences have different meanings.

I am glad you weren't late.

I am glad you weren't late.

The first sentence sounds genuinely relieved that the person wasn't late. In contrast, the second one sounds sarcastic or passive-aggressive, expressing annoyance that the person arrived a bit late."

No emphasis on any part of either copy of that sentence.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals#emphasis

#### What did you expect to see?
Expected emphasis on different words to clarify meaning.

#### Did you test this? If so, how?
n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/html_text_fundamentals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/html_text_fundamentals/index.md
* Last commit: https://github.com/mdn/content/commit/76373459da85cd8b1d3feb315c2db2c5d43e09ff
* Document last modified: 2022-03-30T04:13:26.000Z

</details>

**Comment by estelle** [comment]
The new font makes the example difficult to see, so elaborated in the text.
https://github.com/mdn/content/pull/14717
