### ISSUE TITLE
Content bug: Bad link

### ISSUE THREAD

**Issue by patrickfox** [mdn/content#14720]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-sort#see_also

## Specific page section or heading?

"See Also" section towards the bottom

## What is the problem?

aria-pressed link URL is incorrect and leads to a 404 page

## What did you expect to see?

The aria-pressed article at https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-pressed

## Did you test this? If so, how?

In any web browser.

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve raised #14726 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
