### ISSUE TITLE
Issue with "Reflect.set()": Incomplete details on the consequences of the receiver parameter

### ISSUE THREAD

**Issue by acutmore** [mdn/content#14744]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/set

#### What information was incorrect, unhelpful, or incomplete?

> receiver  [optional]
> "The value of this provided for the call to target if a setter is encountered."

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/set#parameters

#### What did you expect to see?

Where a setter is not encountered the `receiver`  argument is still used, it becomes the target for the property update/creation.

#### Did you test this? If so, how?

```js
let a = {};
let b = {};
Reflect.set(a, 'prop', 42, b);
assert(a.prop === undefined);
assert(b.prop === 42);
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/reflect/set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/set
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/reflect/set/index.md
* Last commit: https://github.com/mdn/content/commit/edaa4aff4cf7532efdcba6014b9316aad2a5b6f1
* Document last modified: 2022-03-27T17:30:40.000Z

</details>

**Comment by acutmore** [comment]
For some extra context, this came up here: https://es.discourse.group/t/how-does-super-work-as-an-object/1279/4

**Comment by noinkling** [comment]
Just ran into this discrepancy myself.

**Comment by js-choi** [comment]
For what it’s worth, this issue was raised in response to a [thread on the TC39 Discourse forum](https://es.discourse.group/t/how-does-super-work-as-an-object/1279/4) raised by @fltenwall.
