### ISSUE TITLE
Content suggestion: Add example to Promise.race page

### ISSUE THREAD

**Issue by ruggi99** [mdn/content#14752]
## What is the new suggestion?

Add an example to `Promise.race` page where it is explained how someone could use Promise.race() to see if a Promise has settled or not. I know this is something weird and majority of people says this is not a correct pattern but I think there are some small use-cases where it could be useful.

## Why is it important or useful?

As an example: I have a program that asynchronously does some initial work (it could take about 30 seconds) and it is required to let the program work correctly. Also the program accepts some commands as input (stdin) from the user. It would be great to know if the Promise for the initial work has settled or not. Because it is required to work properly. As all we know there no API to know if a Promise has settled or it is pending (other than attacching a .then and save the result globally).
So my proposal is to add an example inspired to this NPM package: [promise-status-async](https://github.com/kudla/promise-status-async).
With this example at any time and everywhere could know if a Promise has settled or not

## Other supporting information

Don't know if there could be problems with Copyright, Licences, etc.

Thanks in advance

MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race

**Comment by ruggi99** [comment]
Any updates on this?

**Comment by schalkneethling** [comment]
Hey @ruggi99, thank you so much for your proposal here. We have an official process to go through concerning content suggestions. The first step is to file an issue here https://github.com/mdn/mdn/issues/new/choose

We would greatly appreciate it if you could open an issue there. We can then close this one and start discussing a way forward. Thank you for your understanding and for participating in the project.

**Comment by ruggi99** [comment]
Will do.

Didn't see there was an official process to go through

Thanks

**Comment by Josh-Cena** [comment]
Closing in favor of #21636
