### ISSUE TITLE
Issue with "switch": Executed statements are not limited to the ones inside the case clause

### ISSUE THREAD

**Issue by slk333** [mdn/content#14750]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch

#### What information was incorrect, unhelpful, or incomplete?

> the statements **inside the case clause** are executed until either the end of the switch statement or a break

#### Specific section or headline?
Syntax > case valueN

#### What did you expect to see?

> Statements **inside the case clause and inside the next case clauses** are executed until either the end of the switch statement or a break

or
> Statements **both within the current case and within the next ones** are executed until either the end of the switch statement or a break

#### Did you test this? If so, how?
Per the page summary, 

> executes statements associated with that case, as well as statements in cases that follow the matching case.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/switch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/switch/index.md
* Last commit: https://github.com/mdn/content/commit/76a015ffc44bd29c93e725366ad023171e6c7e7d
* Document last modified: 2022-03-27T18:17:05.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14765 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
