### ISSUE TITLE
Issue with "scroll-behavior": Code example is overly complicated, leading to confusion

### ISSUE THREAD

**Issue by benschwarz** [mdn/content#1476]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

#### What information was incorrect, unhelpful, or incomplete?
The code example uses custom elements like `scroll-container` and `scroll-page`, which are not required for the demonstration and make the information less clear. It's unclear that they're not special or magical elements and therefore make the information less-straightforward to take in. 

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior#examples

#### What did you expect to see?
HTML Elements

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/scroll-behavior`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/scroll-behavior/index.html
* Report started: 2021-01-18T23:14:33.631Z

</details>

**Comment by chrisdavidmills** [comment]
Yeah, agreed that this is a little strange. It would be more intuitive to swap these out for `<section>`/`<article>` elements, and then update the CSS to suit. Shouldn't be that difficult a task.

Also whoever fixes this should increase the height argument on the live sample macro call, as the resulting iframe is not tall enough to show the example properly.

**Comment by johnZhang17** [comment]
About this page: in the first [example](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Basic_concepts#basics_of_scroll_snap) I noticed that the scroll-snap works only on Firefox (84.0.2), not on Chrome (87.0.4280.141), Opera (73.0.3856.344) or Edge (87.0.664.75). Does anyone else has the same problem for the mentioned browser versions?

**Comment by captainbrosset** [comment]
I believe the height issue on the sample iframe is the same as #1653. There is a height on the iframe, but `height:auto` is overriding it.

**Comment by Aayushap1** [comment]
Hello @benschwarz @chrisdavidmills 
I fixed this issue PR is  #2077

**Comment by Ryuno-Ki** [comment]
@rachelandrew Since you closed #2077 - is @Aayushap1 meant to submit another PR (with previous testing locally)?
Or is the issue not worth getting fixed? (In this case, shall we close it?)

**Comment by rachelandrew** [comment]
@Ryuno-Ki I closed it because - as explained - it was an incorrect fix and unrelated to the main issue. So no, you should leave this issue as is.

**Comment by Aayushap1** [comment]
Okay,........
And my other PR which I send you that was correct. You found irrelevant
issues in PR. Sorry to say but I can’t change the definition of attribute.I
researched content on 4 sites w3c w3school whatwg and gfg and still you are
saying I just codied everything I sent PR first no reviews by rachel and
then just closed by saying it is copied content and you just reworded the
content Mam I can’t change the meaning of content or definition.

I don’t have a lot and lot of time to just waste it . I want to contribute
to open source as I have enough knowledge to contribute.  But if I don’t
want then how can I ?

**Comment by chrisdavidmills** [comment]
@Aayushap1 Hi there.

I would like to try to address a few things here, to avoid any problems in the future.

For a start, we do really appreciate your attempts to contribute to open source and to MDN, even if they have been mostly unsuccessful so far.

There are a few things to unpick here:

1. The closing of https://github.com/mdn/content/pull/2077 was unfortunate — the problem encountered was part of a bigger issue that needed fixing elsewhere, and your attempt to fix it did not work. It was therefore closed. This was not your fault, but it did need to be closed.

1. I noticed that there were quite a lot of errors in your early work for us — as Rachel pointed out, you need to make sure that you can locally test your work to make sure it all looks OK before submitting it, to avoid reviewer frustration. Did you get this sorted out? Fel free to ask for thelp if you need help.

1. The issue of copying content — I would first like to say that Rachel is only following our policy on copied content, which is available here: https://github.com/mdn/content#can-i-copy-content-from-other-sources-to-put-on-MDN. I wrote it, and am happy to talk about why our policy is written like this.
   
   If you compare https://github.com/mdn/content/pull/2072/files to https://www.w3schools.com/tags/att_form_accept_charset.asp, or https://github.com/mdn/content/pull/2070/files to https://www.w3schools.com/tags/att_script_async.asp, they are not EXACTLY the same, but the entire wording and structure are very similar in places.

    You say that you can't change the meaning of content or definition. But you can change the structure of the text and the way that it is described.

Let's take the async page and look at a couple of examples.

First, the following bit contains one line that is very similar to the opening line on the W3Schools page, and then another line that says a bit more but is somewhat repetitive:

```
<p>The <strong><code>async</code></strong> attribute is a boolean type of attribute.</p>

<p>The <strong><code>async</code></strong> attribute is an allowed attribute for {{htmlelement("script")}}. When used on a <code>&lt;script&gt;</code> element,
the script will be executed automatically without clicking on any button, with loading of page.</p>
```

It is also kind of missing the point — `async` means that the script will be downloaded without blocking page load, and will execute as soon as it is available. See [this section](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript#script_loading_strategies) for more useful details.

You could probably lose the first line and just go with something simple like

```
<p><strong><code>async</code></strong> is a boolean attribute that can be set on the {{htmlelement("script")}} element, only when used to load an external script file. When `async` is used, the script will be downloaded without blocking page load, and will execute as soon as it is available.</p>
```

Second, the bulleted list looks mostly copied from W3Schools, and is largely irrelevant to the `async`. My above paragraph says what needs to be said already. It would be useful for you to say a little bit about the difference between async and defer, maybe something like "If you need to defer your script execution until after the page has fully loaded, use `defer` instead."

So by all means research the feature you are writing about. But make sure you understand it throughly (writing an example is a good way to do this), and define what it does in your own words.

I hope this helps a bit. Happy to discuss this more.

**Comment by rachelandrew** [comment]
@benschwarz thanks for reporting this and sorry you got all the extra discussion in here!

I've just submitted a PR to simplify the example. The height issue on the iframe @chrisdavidmills mentioned is being fixed elsewhere as it is happening to all examples and is a CSS issue, so that should soon resolve.

**Comment by Aayushap1** [comment]
https://github.com/mdn/content/issues/1476#issuecomment-776109342
@chrisdavidmills I was talking about PR #2070
