### ISSUE TITLE
Content bug: "instructions on how to download and build the code for yourself" link in about:license page go to a 404

### ISSUE THREAD

**Issue by jf** [mdn/content#14770]
## What page(s) did you find the problem on?

"about:license" page in Firefox -> [instructions on how to download and build the code for yourself](https://developer.mozilla.org/en/Mozilla_Source_Code_%28Mercurial%29) -> ... -> 404

Please fix this. Firefox is meant to be open source, and it should be easier to get to the source

**Comment by sideshowbarker** [comment]
Please re-raise this at https://bugzilla.mozilla.org/enter_bug.cgi?product=Developer+Infrastructure&component=Firefox+Source+Docs

I suppose the `about:license` page should be updated to point to https://firefox-source-docs.mozilla.org/setup/ now
