### ISSUE TITLE
"<mfenced>": Why is it marked as deprecated?

### ISSUE THREAD

**Issue by johndeighan** [mdn/content#14779]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfenced

#### What information was incorrect, unhelpful, or incomplete?
I'm looking at the MathML spec - both version 3 and version 4, and nowhere is any indication that mfenced is deprecated. The version 4 draft does include this statement: "Examples of features left out of MathML core but part of full MathML are mfenced, menclose, the elementary math elements, and linebreaking.", which does not indicate deprecation. Also, inexplicably, the document then goes on to define the mfenced element and how it works.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/mathml/element/mfenced`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfenced
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/mathml/element/mfenced/index.md
* Last commit: https://github.com/mdn/content/commit/1f771d1177c4cde004354204d557ae66df70c97f
* Document last modified: 2021-10-11T11:37:47.000Z

</details>

**Comment by Elchi3** [comment]
https://github.com/w3c/mathml/issues/2 deprecated it.
Firefox removed it in https://bugzilla.mozilla.org/show_bug.cgi?id=1603773

Apparently the relevant spec for browsers is https://w3c.github.io/mathml-core/ these days.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/14779#issuecomment-1091861763
