### ISSUE TITLE
"GeneratorFunction": example in the Syntax section is wrong

### ISSUE THREAD

**Issue by intervalia** [mdn/content#14781]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction

#### What information was incorrect, unhelpful, or incomplete?
The example in the Syntax section is wrong and shows this:
```
new Function(arg1, functionBody)
new Function(arg1, arg2, functionBody)
new Function(arg1, ... , argN, functionBody)
```

#### Specific section or headline?
Syntax

#### What did you expect to see?
```
new GeneratorFunction(arg1, functionBody)
new GeneratorFunction(arg1, arg2, functionBody)
new GeneratorFunction(arg1, ... , argN, functionBody)
```

#### Did you test this? If so, how?
Yes, I copied the code example from lower on this page in the Examples section:
```
var GeneratorFunction = Object.getPrototypeOf(function*(){}).constructor
var g = new GeneratorFunction('a', 'yield a * 2');
var iterator = g(10);
console.log(iterator.next().value); // 20
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/generatorfunction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/generatorfunction/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14807 with a fix.
