### ISSUE TITLE
Broken URL "Does this belong on MDN?"

### ISSUE THREAD

**Issue by ajax333221** [mdn/content#1478]
In the URL:

https://developer.mozilla.org/en-US/docs/MDN/About

There is a broken link:

https://developer.mozilla.org/en-US/docs/Project:MDN/Contributing/Does_this_belong

Maybe replace with (?):

https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Does_this_belong_on_MDN

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @ajax333221 !

I've updated the link; see https://github.com/mdn/content/commit/e3efe42af85890ead3fbda4a69463e8ad3ceeef1
