### ISSUE TITLE
Issue with "HTTP headers": Broken Link

### ISSUE THREAD

**Issue by c8b** [mdn/content#1480]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

#### What information was incorrect, unhelpful, or incomplete?
Broken link to the  "Client Hints" source from website of the HTTP working group. I received a 404 file not found error when following the link.

#### Specific section or headline?
Client Hints

#### What did you expect to see?
Documentation regarding "Client Hints" from the HTTP working group website.

Navigating to https://httpwg.org/http-extensions/ ,  there are several files related to Client Hints but unsure which one (if any) should be linked.

#### Did you test this? If so, how?
Yes, I clicked on the link and received the 404 file not found error.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/headers/index.html
* Report started: 2021-01-18T23:20:31.075Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting @c8b . I had a look, and couldn't find any good "actual documentation" to link to beyind what we already have (the pages on the HTTP WG site are all pretty dense specs, afaics). So I've replaced the link with a more descriptive sentence about what client hints do instead: https://github.com/mdn/content/commit/e61d2b2b9b1da428f7fa233c6258fd2a51a35b70

**Comment by hamishwillee** [comment]
@chrisdavidmills FYI, I've been discussing alternative link in https://github.com/mdn/content/pull/1485#issuecomment-763161668 :-). My thinking was that text like you put in is great but that we should still keep a link to the spec.

**Comment by Elchi3** [comment]
@chrisdavidmills To avoid conflicts and to participate in discussions like in https://github.com/mdn/content/pull/1485#issuecomment-763161668, would you mind to rather open PRs instead of committing to master directly?

**Comment by chrisdavidmills** [comment]
OK, OK. TBH, I've been doing it to save time, as I am just so swamped right now. But I'll make an effort to stop cutting corners in future.
