### ISSUE TITLE
Web/HTML/Element/input is missing the autocapitalization attribute description

### ISSUE THREAD

**Issue by andrewhodel** [mdn/content#14823]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

### What specific section or headline is this issue about?

input attributes

### What information was incorrect, unhelpful, or incomplete?

The content that is missing is the few hundred letters of text that describe the autocapitalization attribute to an input element.

### What did you expect to see?

the autocapitalization attribute description

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize

On that page it says - The autocapitalize attribute never causes autocapitalization to be enabled for an [<input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) element with a [type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-type) attribute whose value is url, email, or password.

**Comment by thedivloop** [comment]
Knowing that the [input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) page already contains a reference to [global attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) page which in turn references the autocapitalize page, would it be required to add the sentence "The autocapitalize attribute never causes autocapitalization to be enabled for an [<input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) element with a [type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-type) attribute whose value is url, email, or password." ?

If this is confirmed I am happy to add the sentence above.

Thanks!!

**Comment by andrewhodel** [comment]
Why would you have other webkit only attributes on that page?Sent from my Huawei phone-------- Original message --------From: Div Loop ***@***.***>Date: Sun, Apr 10, 2022, 1:03 AMTo: mdn/content ***@***.***>Cc: Andrew Hodel ***@***.***>, Author ***@***.***>Subject: Re: [mdn/content] Web/HTML/Element/input is missing the autocapitalization attribute description (Issue #14823)
Knowing that the input page already contains a reference to global attributes page which in turn references the autocapitalize page, would it be required to add the sentence "The autocapitalize attribute never causes autocapitalization to be enabled for an  element with a type attribute whose value is url, email, or password." ?
If this is confirmed I am happy to add the sentence above.
Thanks!!

**Comment by andrewhodel** [comment]
When you are building with these tools you expect to look up the element and read the list of attributes supported. That is why there is an HTML standard. If Apple wants to add to the standard, then publish once supported or don't for all attributes. Don't purposely ruin the documentation. Sent from my Huawei phone-------- Original message --------From: Hamish Willee ***@***.***>Date: Mon, Apr 11, 2022, 11:33 AMTo: mdn/content ***@***.***>Cc: Andrew Hodel ***@***.***>, Author ***@***.***>Subject: Re: [mdn/content] Web/HTML/Element/input is missing the autocapitalization attribute description (Issue #14823)
The doc already says that the relevant attributes include global attributes, and that those that are of "extra importance" are highlighted. So I guess the question is whether  autocapitalize is (or is not) of extra importance?

**Comment by hamishwillee** [comment]
@andrewhodel MDN does not always/generally include every single attribute on every single page because it would be a maintenance nightmare.

**Comment by andrewhodel** [comment]
That's what happens when the design department isn't drawing only.



Andrew

**Comment by wbamberg** [comment]
> The doc already says that the relevant attributes include global attributes, and that those that are of "extra importance" are highlighted. So I guess the question is whether `autocapitalize` is (or is not) of extra importance?

On that, honestly, it sounds like it is of "extra importance". From the first sentence of [`autocapitalize`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize):

> The autocapitalize [global attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) is an enumerated attribute that controls whether and how text input is automatically capitalized as it is entered/edited by the user.

...makes it sound highly relevant to input.

But I'm not sure it should be a judgement call like this. I think it would be better if this list omitted all global attributes, and made that clear in the description. Then we'd in theory know where we stand, instead of each case being a subjective judgement.

Which, cross-checking https://html.spec.whatwg.org/multipage/dom.html#global-attributes, means we should remove `autofocus` from the table in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attributes.

@hamishwillee , what do you think?

**Comment by andrewhodel** [comment]
I think you are not respecting that javascript can use XHR and documenting
like there is a printing press next door.



Andrew

**Comment by andrewhodel** [comment]
I'm the one who told you about the issue.

You do understand the points I am making.

CSV doesn't have attributes, XML is a nightmare.

JSON and Javascript (with XHR) allow this to be done properly and you
aren't respecting the fact that you can work on a table outside of
harassment.



Andrew

**Comment by andrewhodel** [comment]
My response is not gibberish.

You are working on documentation for the HTML standard.

The HTML standard is close in relation to Javascript and XHR.  The majority
of implementations of the HTML standard also implement Javascript and XHR.

What you are saying is not related to the work being done.



Andrew

**Comment by andrewhodel** [comment]
@wbamberg this issue is not fixed by https://github.com/mdn/content/pull/15218/commits/2c06c394f0785005b2f590cd899ae46f8d0f069b

@hamishwillee 

Are you honestly expecting everyone to never `read` the `element.style.border` key and instead write complex logic to read 10+ other keys for what it describes as a setting?

**Comment by wbamberg** [comment]
@andrewhodel , as discussed in this thread, this page is not intended to list all the global attributes: instead it points to a separate page for them, and lists attributes that are specific to some or all `<input>` elements.

As has already been mentioned in this thread:

> MDN does not always/generally include every single attribute on every single page because it would be a maintenance nightmare.

I appreciate that this might not be the resolution you were hoping for, but MDN is a big site with a small team of maintainers. We really have to think about what we can support with the resources that we have.

**Comment by andrewhodel** [comment]
I don't understand why would think something that doesn't add the autocapitalization attribute description to the URL of discussion would "close" this issue.

Why do you have many other `webkit only` attributes on there but not the autocapitalization attribute?

It's intentional confusion, if you are going to require a link to be clicked to view the attributes then why list any of them before?  You don't list any selectable sort method and there are many.

Why you would try to confuse people?

**It's a major problem, the Autocapitalization functionality needs to be disabled often because the email RFC requires case sensitivity in the local part, but not in the domain.**

You are opening an enormous problem in the future because many email servers are not properly supporting the RFC at the current time and it will get worse.

**Comment by andrewhodel** [comment]
I don't think you are making an informed decision, I think you are trusting a peer that is not following protocol.

**Comment by andrewhodel** [comment]
Perhaps you have made your decision of resolution without the acceptance of professional work and home life co-existing.

It doesn't make sense that you would exclude this from the document, it is a real problem in web development that **email servers are not following the RFC and the reason is this attribute**.

**Comment by andrewhodel** [comment]
Make sense == has reason in this explanation.

Yes, you can do that in English.

**Comment by andrewhodel** [comment]
Why don't you understand that it is not about a global attribute, it is about the importance of a particular attribute and it's omission from the educational content?

You are honestly setting up a problem with the email RFC and you don't understand what you are doing.

It's a critical attribute, it's at the root of the argument between phone numbers and unicode being "already developed".

It's a reality, people remember alphabets.  I cannot believe you are enacting a problem that will be chaotic for so many business owners and email administrators.

Think what they will have to deal with once the protocol is forced on an upgrade and everything is lost because of Apple and Google forcing uppercase "smart keyboard derived" first letters while the protocol is case sensitive there.  There's no reason for you, as an employee of a company that is a third party to this reality and ensures integrity, to not document what's important.

**Comment by sideshowbarker** [comment]
Please note that we have dozens of people watching this repo who may be getting notifications every time you post a comment here.

So please be respectful of other people’s time and attention, and avoid taking actions that might cause excessive notifications for other users here, or in general that disrupt the experience of other users  here.

See [GitHub’s Acceptable Use Policies](https://docs.github.com/en/site-policy/acceptable-use-policies), which along with the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/), govern interactions in the repo. In particular, see https://docs.github.com/en/site-policy/acceptable-use-policies/github-disrupting-the-experience-of-other-users.
