### ISSUE TITLE
Broken link on the Matching web features to browser release version numbers page

### ISSUE THREAD

**Issue by MrBrain295** [mdn/content#14837]
### MDN URL

/en-US/docs/MDN/Contribute/Processes/Matching_features_to_browser_version

### What specific section or headline is this issue about?

FOR WEB API FEATURES

### What information was incorrect, unhelpful, or incomplete?

The link to XPIDL is broken.

### What did you expect to see?

A working link.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/contribute/processes/matching_features_to_browser_version`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Processes/Matching_features_to_browser_version
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/processes/matching_features_to_browser_version/index.md
* Last commit: https://github.com/mdn/content/commit/672bace59f60c4931e5cdde8eb32919c924bd191
* Document last modified: 2022-03-14T00:26:56.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14850 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
