### ISSUE TITLE
Kumascript example uses {{anch}} macro

### ISSUE THREAD

**Issue by MrBrain295** [mdn/content#14864]
### MDN URL

/en-US/docs/MDN/Tools/KumaScript/Troubleshooting

### What specific section or headline is this issue about?

DocumentParsingError

### What information was incorrect, unhelpful, or incomplete?

Kumascript example uses {{anch}} macro.

### What did you expect to see?

A different example.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/tools/kumascript/troubleshooting`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Tools/KumaScript/Troubleshooting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/tools/kumascript/troubleshooting/index.md
* Last commit: https://github.com/mdn/content/commit/a59a9f4f7015a462c16905403cd315475b7da1de
* Document last modified: 2022-04-05T16:10:17.000Z

</details>

**Comment by entity-night** [comment]
hm
