### ISSUE TITLE
All the BCD table links are broken on the HTMLBodyElement page

### ISSUE THREAD

**Issue by MrBrain295** [mdn/content#14865]
### MDN URL

[HTMLBodyElement ](https://developer.mozilla.org/en-US/docs/Web/API/HTMLBodyElement)

### What specific section or headline is this issue about?

The BCD table

### What information was incorrect, unhelpful, or incomplete?

All the BCD table links are broken on the HTMLBodyElement page.

### What did you expect to see?

Working links.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlbodyelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLBodyElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlbodyelement/index.md
* Last commit: https://github.com/mdn/content/commit/67ee2ea91f96a07b9d9b049d9bfd9ce44278a301
* Document last modified: 2022-04-04T14:22:09.000Z

</details>

**Comment by hamishwillee** [comment]
True. 

The compatibility table and docs have lots of "speculative" links. I generally don't consider these bugs since they are more like a request for help.

That said see https://github.com/mdn/content/discussions/14869

**Comment by Josh-Cena** [comment]
Hi! I'm closing this in favor of https://github.com/mdn/mdn/issues/520 so it can be done in a more organized way.
