### ISSUE TITLE
The description of the iframe allow attribute seems wrong?

### ISSUE THREAD

**Issue by greggman** [mdn/content#14882]
### MDN URL

/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy

### What specific section or headline is this issue about?

Enforcing best practices for good user experiences

### What information was incorrect, unhelpful, or incomplete?

> To avoid breaking existing web content, **the default for such policy-controlled features is to allow the functionality to be used by all origins. That is, the default allowlist is '*' for each feature.** Preventing the use of the sub-optimal functionality requires explicitly specifying a policy that disables the features.

### What did you expect to see?

AFAICT this is no longer true. For example gamepads are now opt in not opt out

### Do you have any supporting links, references, or citations?

https://github.com/w3c/gamepad/pull/112

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/feature_policy/using_feature_policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/feature_policy/using_feature_policy/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by Techi-Dev** [comment]
The link is showing broken on my end.

**Comment by Josh-Cena** [comment]
Feature policy is gone, and the new permissions policy page doesn't seem to make this claim, so I'll assume it's fixed.
