### ISSUE TITLE
The colgroup element can be more?

### ISSUE THREAD

**Issue by gMan1990** [mdn/content#149]
https://github.com/mdn/content/blob/eb12fad0ba28d3f40782d4dcf1911412ccf175f8/files/en-us/web/html/element/table/index.html#L35

Show a demo?

**Comment by peterbe** [comment]
What do you mean?

**Comment by gMan1990** [comment]
@peterbe https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table

<div id="table-mdls">Permitted content, In this order:
    <ol>
     <li>an optional <a href="/en-US/docs/Web/HTML/Element/caption" title="The HTML <caption> element specifies the caption (or title) of a table."><code>&lt;caption&gt;</code></a> element,</li>
     <li>zero or more <a href="/en-US/docs/Web/HTML/Element/colgroup" title="The HTML <colgroup> element defines a group of columns within a table."><code>&lt;colgroup&gt;</code></a> elements,</li>
     <li>an optional <a href="/en-US/docs/Web/HTML/Element/thead" title="The HTML <thead> element defines a set of rows defining the head of the columns of the table."><code>&lt;thead&gt;</code></a> element,</li>
     <li>either one of the following:
      <ul>
       <li>zero or more <a href="/en-US/docs/Web/HTML/Element/tbody" title="The HTML Table Body element (<tbody>) encapsulates a set of table rows (<tr> elements), indicating that they comprise the body of the table (<table>)."><code>&lt;tbody&gt;</code></a> elements</li>
       <li>one or more <a href="/en-US/docs/Web/HTML/Element/tr" title="The HTML <tr> element defines a row of cells in a table. The row's cells can then be established using a mix of <td> (data cell) and <th> (header cell) elements."><code>&lt;tr&gt;</code></a> elements</li>
      </ul>
     </li>
     <li>an optional <a href="/en-US/docs/Web/HTML/Element/tfoot" title="The HTML <tfoot> element defines a set of rows summarizing the columns of the table."><code>&lt;tfoot&gt;</code></a> element</li>
    </ol>
    </div>

----
It said `zero or more <colgroup> elements`. Like this:
```html
<table>
    <caption></caption>
    <colgroup><!-- colgroup-1 --></colgroup>
    <colgroup><!-- colgroup-2 --></colgroup>
    <thead></thead>
    <tbody><!-- tbody-1 --></tbody>
    <tbody><!-- tbody-2 --></tbody>
    <tfoot></tfoot>
</table
```
, it that true?

**Comment by peterbe** [comment]
I actually don't know. Go ahead and make a pull request with a proposed changed and someone will be able to help you discuss it there.

**Comment by sideshowbarker** [comment]
> It said `zero or more <colgroup> elements`. Like this:
> …
> , it that true?

Yes, it’s true that the rules in the HTML spec allow a table to have more than one `colgroup`.

* At https://html.spec.whatwg.org/multipage/#table-examples, see the “operating expenses table” example.

* Just after https://html.spec.whatwg.org/multipage/#the-table-element:dom-table-rows-11, see the “Sudoku puzzle” example.

Both of those examples have multiple `colgroup` elements.
