### ISSUE TITLE
Request: Bring back hidefocus attribute

### ISSUE THREAD

**Issue by alanhogan** [mdn/content#14902]
### MDN URL

/en-US/docs/Web/API/HTMLElement

### What specific section or headline is this issue about?

Properties

### What information was incorrect, unhelpful, or incomplete?

There is an Internet Explorer property/attribute, hideFocus, that suppresses focus rings. Other pages on the web link to this MDN page expecting it to document this, but it doesn’t.

I think it would be valuable to bring this back, while of course clearly marking it as deprecated and proprietary.

### What did you expect to see?

Documentation of `hidefocus`

### Do you have any supporting links, references, or citations?

* http://help.dottoro.com/lhgdtcso.php (~links to this MDN page~ _see correction in [comment below](#issuecomment-1104147251)_)
* https://webplatform.github.io/docs/html/attributes/hideFocus/

Those are top web search results for hidefocus.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/index.md
* Last commit: https://github.com/mdn/content/commit/83c3630e9cbc8a64ead8208a4612ed2244761381
* Document last modified: 2022-04-03T06:14:55.000Z

</details>

**Comment by alanhogan** [comment]
Right, I don’t know the history, but I think it *used* to be, and IMHO should be brought back for completeness' sake.

**Comment by wbamberg** [comment]
I don't think we should write docs for features that are IE-only at this point.

**Comment by alanhogan** [comment]
I get it, but on the other hand, there’s still code out there with this attribute. That’s what made me look into it - I saw the attribute and wondered what it did and in which browsers.

**Comment by alanhogan** [comment]
Correction: I said page http://help.dottoro.com/lhgdtcso.php links to MDN regarding `hidefocus`. This isn't quite true. The page actually links to http://msdn.microsoft.com/en-us/library/ms533783(VS.85).aspx, but that MSDN page redirects to MDN's https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement.

Here is [what the MSDN page read as of 2013, per Wayback](https://web.archive.org/web/20130411003542/http://msdn.microsoft.com/en-us/library/ms533783(VS.85).aspx):

<blockquote>
<div class="topic" xmlns="http://www.w3.org/1999/xhtml">
  <h1 class="title">hidefocus attribute | hideFocus property</h1>
  
  <div id="mainSection">
<div class="clsServerSDKContent">

</div>
<p>Sets or gets the value that indicates whether the object visibly shows that it has focus.</p>
<h3>Syntax</h3>

<table>
<tbody><tr><th>HTML</th><td><code>&lt;element <strong>hidefocus</strong>="<em>p</em>" ... &gt;</code></td></tr>
<tr><th>JavaScript</th><td><code><em>p</em> = <em>object.</em><strong>hideFocus</strong></code></td></tr>
</tbody></table>

<h3>Property values</h3>
<p>Type: <strong>Boolean</strong> <strong></strong></p>
<dl class="indent">
<dt><a id=""></a><p><strong>true</strong> (true)</p>
</dt>
<dd>
<p>Focus is not visibly indicated.</p>
</dd>
<dt><a id=""></a><p><strong>false</strong> (false)</p>
</dt>
<dd>
<p>Default. Focus is visibly indicated.</p>
</dd>
</dl>
<h3>Remarks</h3>
<p>The focus of an object is visibly indicated by a focus rectangle—a dotted rectangle within the boundaries of the object.</p>
<p>This property does not control the ability of an object to receive <a href="https://web.archive.org/web/20130411003542/http://msdn.microsoft.com/en-us/library/ms536425(v=vs.85).aspx"><strong xmlns="http://www.w3.org/1999/xhtml">focus</strong></a>; for that, use the <a href="https://web.archive.org/web/20130411003542/http://msdn.microsoft.com/en-us/library/ms534654(v=vs.85).aspx"><strong xmlns="http://www.w3.org/1999/xhtml">tabIndex</strong></a> property.</p>
<h3>Examples</h3>
<p>The following example shows how to use the <strong>hideFocus</strong> attribute to prevent a focus rectangle from appearing on a button.
				</p>
<p><strong>Code example: </strong><a href="https://web.archive.org/web/20130411003542/http://samples.msdn.microsoft.com/workshop/samples/author/dhtml/refs/hidefocus.htm">http://samples.msdn.microsoft.com/workshop/samples/author/dhtml/refs/hidefocus.htm</a></p>

<div id="code-snippet-1" class="codeSnippetContainer" xmlns="">
    <pre>...
&lt;button&gt;
Button With Rectangle&lt;/button&gt;
&lt;button hidefocus="true"&gt;
Button Without Rectangle&lt;/button&gt;
...</pre>
</div>
</div>
</div>
</blockquote>

**Comment by teoli2003** [comment]
Ji!

With IE approaching end-of-line support, we are even discussing removing (little by little) the IE-only features that are left on MDN. (Not in one go, not immediately).

We will not accept IE-only docs: this is not a good use of our time (as writers or as reviewers).

If you want to dig into code of the past, you may find WebPlatform.org  useful: they kept the old IE-only stuff (and as they are not updated anymore, they will continue to do it) In your case, you are looking for: https://webplatform.github.io/docs/html/attributes/hideFocus/

Thanks a lot for your interest.
