### ISSUE TITLE
Contradictory statement

### ISSUE THREAD

**Issue by gdennie** [mdn/content#1491]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes

In the section, **A prototype-based language?**, the inset seems to contradict itself by asserting that there is a distinction between an object's prototype, as revealed by `Object.getPrototypeoOf(obj)`, and the object referred to by its constructor's prototype property. However, it immediately asserts that they always refer to the same object.

Actually, the entire section is a bit tortured. From what I gather elsewhere, constructors are functions that have their own inheritance (prototype) hierarchy (they are also objects). These functions create and decorate objects including assigning them a prototype object which may or may not be their own...perhaps it is themselves they assign to that property of the constructed instance. In any event, Javascript constructors seem to behave more like single method static factory classes complete with their own inheritance hierarchy and a weird invocation method of, `new ClassType()` vs `ClassType.new()`.

I think it could use a rewrite.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/objects/object_prototypes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/javascript/objects/object_prototypes/index.html
* Report started: 2021-01-19T07:25:08.945Z

</details>

**Comment by chrisdavidmills** [comment]
Pretty sure this got fixed in another issue. Feel free to reopen if I'm wrong.
