### ISSUE TITLE
Issue with "Join the MDN Web Docs community": …

### ISSUE THREAD

**Issue by vvsklyar** [mdn/content#1492]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/community`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/community/index.html
* Report started: 2021-01-19T09:34:09.152Z

</details>

**Comment by vvsklyar** [comment]
There are many issues with pages in Russian, which do not exist, for example /ru/docs/MDN/Doc_status/Overview etc.

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
