### ISSUE TITLE
Selectors link broken

### ISSUE THREAD

**Issue by ennioVisco** [mdn/content#14930]
### MDN URL

/en-US/docs/Web/API/Document_object_model/Locating_DOM_elements_using_selectors

### What specific section or headline is this issue about?

**See Also**

### What information was incorrect, unhelpful, or incomplete?

The `Selectors specification` link is broken. 

### What did you expect to see?

The correct link is probably this one: https://www.w3.org/TR/selectors-4/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document_object_model/locating_dom_elements_using_selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/Locating_DOM_elements_using_selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document_object_model/locating_dom_elements_using_selectors/index.md
* Last commit: https://github.com/mdn/content/commit/b5470d4de371c7dd190aabab7b7ea53092c8f253
* Document last modified: 2022-04-11T14:55:51.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

It's working for me now. There is an intermittent issue with the csswg.org links, which they are looking into. So this isn't an MDN issue.
