### ISSUE TITLE
Issue with "Working with the History API"

### ISSUE THREAD

**Issue by x3388638** [mdn/content#1493]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API

#### What information was incorrect, unhelpful, or incomplete?
Source: https://github.com/mdn/content/blob/3c8dd140b3925bf8f7b00d0972f27c5760f5c6a3/files/en-us/web/api/history_api/working_with_the_history_api/index.html#L38
In the first note section of this article, it says `After using history.pushState(), calling history.back() does not raise a popstate event.` which is inconsistent with another note `The popstate event is only triggered by doing a browser action such as a clicking on the back button (or calling history.back() in JavaScript)` in https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent

#### Specific section or headline?
The note section in `Adding and modifying history entries` > `Example of pushState() method`

#### What did you expect to see?
Actually, it will fire popstate event while calling history.back() after history.pushState()

#### Did you test this? If so, how?
**Chrome 87.0.4280.88**
<img width="381" alt="截圖 2021-01-19 18 49 42" src="https://user-images.githubusercontent.com/8147952/105024572-37e87c80-5a87-11eb-854c-f6d009f8a433.png">

**Firefox 84.0.1**
<img width="348" alt="截圖 2021-01-19 18 50 08" src="https://user-images.githubusercontent.com/8147952/105024674-551d4b00-5a87-11eb-949b-f556fe2f5fce.png">

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/history_api/working_with_the_history_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/history_api/working_with_the_history_api/index.html
* Report started: 2021-01-19T10:27:09.927Z

</details>

**Comment by Abhishek01039** [comment]
should we remove while `note` section @chrisdavidmills ?

**Comment by chrisdavidmills** [comment]
It sounds like the first should just be deleted, but someone needs to test it.
