### ISSUE TITLE
Information about how MDN "wiki saves" work looks kuma-y

### ISSUE THREAD

**Issue by Gregoor** [mdn/content#1494]
Hey friends,

just read  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag and it contains a section describing how saving in Kuma MDN works. Don't know if you'd want to switch to a different example or add some info that MDN doesn't work that way anymore.

The section is "Avoiding mid-air collisions" and starts with:

> For example, when editing MDN, the current wiki content is hashed and put into an Etag in the response

🥂 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/etag`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/headers/etag/index.html
* Report started: 2021-01-19T12:33:28.925Z

</details>

**Comment by chrisdavidmills** [comment]
Hey @Gregoor , lovely to hear from you!

You are right that this needs updating. I don't know much about ETags, so I'll put this out to the team. @peterbe @escattone do we still do anything like this on MDN, or do you know of another example to point to?

Alternately, anyone else reading this who fancies fixing this, please feel free to jump in.

**Comment by peterbe** [comment]
> Hey friends,

Man! I miss you! We miss you!

**Comment by peterbe** [comment]
Oh I see. It's actually mentioned in two places. ...that ought to be refreshed. 
<img width="795" alt="Screen Shot 2021-01-20 at 9 59 14 AM" src="https://user-images.githubusercontent.com/26739/105192495-28f4df00-5b06-11eb-974b-0bc17ae95ce1.png">

**Comment by escattone** [comment]
> Hey friends,

Hey buddy! We miss you! Hope all is well!

@chrisdavidmills No, we don't do anything like this any longer on MDN, but I think we can reword that example a bit and continue to use it. I submitted https://github.com/mdn/content/pull/1543 as a suggestion.

**Comment by Gregoor** [comment]
Looks like I was too radical in my unsubscribing and now I don't even get notifications for lovely replies. Miss all of you too!
