### ISSUE TITLE
getAttribute - Special cases, like disabled, multiple etc.

### ISSUE THREAD

**Issue by Skarnivorous** [mdn/content#14946]
### MDN URL

/en-US/docs/Web/API/Element/getAttribute

### What information was incorrect, unhelpful, or incomplete?

The getAttribute behaviour has different browser responses for some special attributes e.g. "disabled", "multiple" even outside of their 'special' context (usually things like input elements)

### What did you expect to see?

Some mention of this inconsistency of the getAttribute response for special cases.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/getattribute`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/getattribute/index.md
* Last commit: https://github.com/mdn/content/commit/b903430b8167127f27d42645c32876c34fcc3e3f
* Document last modified: 2022-04-07T05:24:35.000Z

</details>

**Comment by sideshowbarker** [comment]
@Skarnivorous Thanks for raising this. Do you have a test case or [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates some of the inconsistency of the `getAttribute` response for special cases?

Without that, it doesn’t seem like anybody else would be able to write a description of the inconsistency.

**Comment by Skarnivorous** [comment]
@sideshowbarker I've tried to reproduce what I was experiencing, and now I only find the issue arises when trying to read 'special' attributes (like disabled/multiple) with jQuery - or if the element is created with jQuery parsing it will alter the attribute values in the parsing. I was also testing in IE11 in various compatibility modes. But as I can't reproduce the discrepancies with Firefox/Chrome anymore, I'll close this report.
