### ISSUE TITLE
Superfluous text?

### ISSUE THREAD

**Issue by HelmZalee** [mdn/content#14943]
### MDN URL

/en-US/docs/Web/API/Element/remove

### What specific section or headline is this issue about?

Element.remove()

### What information was incorrect, unhelpful, or incomplete?

The Element.remove() method removes the element **from the tree it belongs to**.

### What did you expect to see?

"...removes the element."  or "...removes the element from the DOM."?

A little hard to see how an element could be removed from "the tree it belongs to" without being also removed from the DOM.  The "non-normative" description in the Standard says simply "Removes _node_".  

As is, the text just seems to raise an unnecessary question.

### Do you have any supporting links, references, or citations?

https://dom.spec.whatwg.org/#ref-for-dom-childnode-remove%E2%91%A0

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/remove`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/remove
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/remove/index.md
* Last commit: https://github.com/mdn/content/commit/1675e464086a13f1d89a140b40c66772e204c695
* Document last modified: 2022-03-23T17:24:31.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14945 with a fix
