### ISSUE TITLE
The r attribute of a svg circle element can be a percentage

### ISSUE THREAD

**Issue by teletep** [mdn/content#14957]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle

### What specific section or headline is this issue about?

Attributes

### What information was incorrect, unhelpful, or incomplete?

The r attribute only specifies the length value type.
It should include the percentage value type.

### What did you expect to see?

for the r attribute: Value type: length|percentage

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/2002/CR-SVG11-20020430/attindex.html

### Do you have anything more you want to share?

The percentage value for the r attribute is the percentage of the average of the width and height of the parent element.
And not a percentage of the diagonal of the parent element!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/element/circle`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/circle/index.md
* Last commit: https://github.com/mdn/content/commit/909c7ece968f1c0b8c9c3f881a7b4d2c5401a00e
* Document last modified: 2022-02-05T07:38:20.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #14986 with a fix.
