### ISSUE TITLE
confusing value type : <length> | <number>

### ISSUE THREAD

**Issue by teletep** [mdn/content#14954]
### MDN URL

/en-US/docs/Web/SVG/Element/line

### What specific section or headline is this issue about?

Attributes

### What information was incorrect, unhelpful, or incomplete?

The x1 x2 y1 y2 attributes specify the value types length|percentage|number.
I think that the number type should not be specified because the length type implicits the number type.

This to be consequent with the attributes of the rect element.
 

### What did you expect to see?

length|percentage in stead of length|percentage|number for the x1 x2 y1 y2 attributes.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect

### Do you have anything more you want to share?

This is not a mistake, but it gives the wrong impression as if there is a difference between the number type and the number type which is handled by the length type.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/element/line`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/line
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/line/index.md
* Last commit: https://github.com/mdn/content/commit/f107840858523dd1a50a07de2b6112928b5c31a2
* Document last modified: 2022-02-06T06:18:20.000Z

</details>

**Comment by sideshowbarker** [comment]
As confusing as it is, it actually matches what the spec says —

https://svgwg.org/svg2-draft/shapes.html#LineElementX1Attribute
> ```
> <length-percentage> | <number>
> ```

So I opened #14985 with a fix that changes the x1, x2, y1, and y2 pages to match the spec.
