### ISSUE TITLE
Broken link in Canvas API

### ISSUE THREAD

**Issue by yin1999** [mdn/content#14961]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/A_basic_ray-caster

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/A_basic_ray-caster#how

### What information was incorrect, unhelpful, or incomplete?

In the following paragraph, the link to document `java raycaster` (<http://www.shinelife.co.uk/java-maze/>) is broken.

```markdown
The code I ended up with is a regurgitated amalgam of the raycaster chapters from an old André LaMothe*Tricks of the Game
Programming Gurus* book (ISBN: 0672305070), and a [java raycaster](http://www.shinelife.co.uk/java-maze/) I found online,
filtered through my compulsion to rename everything so it makes sense to me, and all the tinkering that had to be done to make
things work well.
```

### What did you expect to see?

Fix this link.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvas_api/a_basic_ray-caster`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/A_basic_ray-caster
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/a_basic_ray-caster/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #14983 with a fix.
