### ISSUE TITLE
Form error because req.body is undefined on LocalLibrary Tutorial

### ISSUE THREAD

**Issue by lichaa824** [mdn/content#14973]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form

### What specific section or headline is this issue about?

Controller—post route section

### What information was incorrect, unhelpful, or incomplete?

`
    var genre = new Genre(
      { name: req.body.name }
    );
`

For this part to work you need to add in the app.js `app.use(express.urlencoded())` (Express 4.16+) , in older version you need to install body-parser package.

if you dont do this , req.body return undefined.

### What did you expect to see?

A step that tell the user to add the required line of code in the app.js file. 

### Do you have any supporting links, references, or citations?

> req.body
Contains key-value pairs of data submitted in the request body. By default, it is undefined, and is populated when you use body-parsing middleware such as [express.json()](https://expressjs.com/es/api.html#express.json) or [express.urlencoded()](https://expressjs.com/es/api.html#express.urlencoded).

Source: https://expressjs.com/es/api.html#req.body

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_genre_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_genre_form/index.md
* Last commit: https://github.com/mdn/content/commit/601a273d856ee11aa32dd9ac42d1e84f441c8b58
* Document last modified: 2022-02-03T11:27:16.000Z

</details>

**Comment by hamishwillee** [comment]
That is somewhat covered in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/skeleton_website

More precisely, if you are following this tutorial you will have created the site using the generator which automatically adds the [express.json()](https://expressjs.com/es/api.html#express.json) and [express.urlencoded()](https://expressjs.com/es/api.html#express.urlencoded) middleware.

You can see that the files are mentioned (but not explained other than "they are middleware") in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/skeleton_website#app.js

![image](https://user-images.githubusercontent.com/5368500/163917935-8512903d-da7b-4c8a-8bab-ba5d6b39f793.png)

That is appropriate for the tutorial. Not strictly necessary, but I have added a little explanation of this middleware in https://github.com/mdn/content/pull/15110 .

**Comment by hamishwillee** [comment]
Upshot, I think this can be closed as the instruction exists, it just isn't where you expected it. We don't necessarily break down what you need in the middleware to get each part of the tutorial to work because there is an assumed flow.
