### ISSUE TITLE
If-Range should be Range while If-Unmodified-Since in conjunction with a range

### ISSUE THREAD

**Issue by jamesxu2018** [mdn/content#14975]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Unmodified-Since

### What specific section or headline is this issue about?

If-Unmodified-Since

### What information was incorrect, unhelpful, or incomplete?

In conjunction with a range request using the [If-Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Range) header, this header can be used to ensure that the new fragment requested comes from an unmodified document.

### What did you expect to see?

In conjunction with a range request using the [Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) header, this header can be used to ensure that the new fragment requested comes from an unmodified document.

### Do you have any supporting links, references, or citations?

If-Range is another kind of conditional request header which can work with Range. But, here we are talking about the case of how Range work together with If-Unmodified-Since to archive a specific purpose. So If-Range here, is somewhat confuse the readers. Using Range instead, it's better and meaningful.

### Do you have anything more you want to share?

Below is an example to show how Range work with If-Unmodified-Since to fetch a slice of message or report 412.

[root@test01 conf]# curl test/letter.txt -H 'If-Unmodified-Since: Fri, 03 Sep 2021 02:13:49 GMT' -H 'Range: bytes=0-5' -I
HTTP/1.1 206 Partial Content
Server: nginx/1.20.1
Date: Thu, 14 Apr 2022 02:21:48 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 6
Last-Modified: Fri, 03 Sep 2021 02:13:49 GMT
Connection: keep-alive
ETag: "613184dd-1b"
Content-Range: bytes 0-5/27

[root@test01 conf]# curl test/letter.txt -H 'If-Unmodified-Since: Fri, 03 Sep 2021 02:13:39 GMT' -H 'Range: bytes=0-5' -I
HTTP/1.1 412 Precondition Failed
Server: nginx/1.20.1
Date: Thu, 14 Apr 2022 02:21:55 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 173
Connection: keep-alive

[root@test01 conf]# curl test/letter.txt -H 'If-Unmodified-Since: Fri, 03 Sep 2021 02:13:59 GMT' -H 'Range: bytes=0-5' -I
HTTP/1.1 206 Partial Content
Server: nginx/1.20.1
Date: Thu, 14 Apr 2022 02:22:03 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 6
Last-Modified: Fri, 03 Sep 2021 02:13:49 GMT
Connection: keep-alive
ETag: "613184dd-1b"
Content-Range: bytes 0-5/27

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/if-unmodified-since`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Unmodified-Since
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/if-unmodified-since/index.md
* Last commit: https://github.com/mdn/content/commit/aeed8b8a875a33d9b92b5d9c433000f352155468
* Document last modified: 2021-10-08T11:27:34.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #14984 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
