### ISSUE TITLE
`<bdi>` renders incorrectly.

### ISSUE THREAD

**Issue by jtagcat** [mdn/content#14981]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/38327267/163319191-e7bde585-bd53-4abf-a559-6373ec69c5ab.png)

When text is copied and pasted to URL bar, it shows correctly. Here in GitHub, it shows `تیز سمی: 3rd place`, the same with the  rendered result in the Try it section — it doesn't look right. FF Nightly 101.0a1 (2022-04-11) (64-bit)

### What did you expect to see?

The same as copied content.

### Do you have anything more you want to share?

Might be browser issue instead.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/bdi`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/bdi/index.md
* Last commit: https://github.com/mdn/content/commit/473efa32fe17feb192ef6ec3a15ca4f767006051
* Document last modified: 2022-01-24T11:26:15.000Z

</details>

**Comment by teoli2003** [comment]
The third entry has no `<bdi>`, to demonstrate the need for `<bdi>`. It looks like what is expected.

**Comment by jtagcat** [comment]
It didn't look apparent on first glance. Adding a comment in the codeblock might do?

**Comment by teoli2003** [comment]
Sure! Do you want to give it a try?

**Comment by wbamberg** [comment]
Please don't do this. The general policy with these samples is to show not tell, and not to include comments except for very surprising things (like different behavior across browsers or timezones).

They are demos, not complete documentation. The article explains in lots of detail how `bdi` works and how code like that in the demo should have this effect.

**Comment by teoli2003** [comment]
Closing per comment.
