### ISSUE TITLE
Chrome devtools console allows redeclaring const variables

### ISSUE THREAD

**Issue by pearlrik** [mdn/content#14987]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables

### What specific section or headline is this issue about?

Constants in JavaScript

### What information was incorrect, unhelpful, or incomplete?

In the chapter we have to learn to use the console and use it a lot to test things. So when you said you can't declare a variable twice, I tried it in the console. As you can see in the picture it works. So I was very confused and I'm still not sure why it works. 

What you write is true. It gives an error when I declare the same variable twice with const in visual studio code. 

BUT in the console it seems fine, as you can see in the picture. If the picture does not load, this is the code which does NOT give any errors, even though your page says it should. 

const myName = "john";
const myName = "bob";

No erorr, and the console will give the name bob. 

![image](https://user-images.githubusercontent.com/89338326/163340972-85ca503b-5066-4cfa-a793-863f228581b8.png)

### What did you expect to see?

I expected to see an error, a similar error I do get when I run it from Visual Studio Code. 

Perhaps it's best to explain on the page why running it through console does not give the error expected, and why. (Because we're constantly asked to use console to test things)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/variables`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/variables/index.md
* Last commit: https://github.com/mdn/content/commit/0b270d4f95ba1c4abcc81215df774a9448a78105
* Document last modified: 2022-02-18T09:10:31.000Z

</details>

**Comment by teoli2003** [comment]
It does fail in my console:

![Capture d’écran 2022-04-14 à 10 17 13](https://user-images.githubusercontent.com/1466293/163343750-f9ed438c-8ac2-4736-86f5-fb8aa8e7795b.png)

**Comment by sideshowbarker** [comment]
> It does fail in my console:

…and in mine — as it should in every browser devtools console that’s functioning as expected.

So @pearlrik it’s surprising and interesting that your browser’s devtools console isn’t showing an error. What browser and version and platform are you trying it?

I can’t imagine what might cause this. I don’t think any browser even has particular settings that could be changed that would cause this — but can you think of any devtools settings you may have changed?

**Comment by sideshowbarker** [comment]
Well, actually I just now found https://stackoverflow.com/a/69055218/441757

> Assuming you're using Chrome, this is by design. `const` redeclarations was intentionally implemented in Chrome Devtools 92 as a means to make it easier for developers to test code within the Chrome console:
>
>> The Console now supports redeclaration of const statement, in addition to the existing let and class redeclarations. The inability to redeclare was a common annoyance for web developers who use the Console to experiment with new JavaScript code. https://developer.chrome.com/blog/new-in-devtools-92/#const-redeclaration

I looked in by Chrome Canary 102 and I couldn’t find a setting for it. But maybe there was never any setting for it, but it was changed in Chrome 92 to always be that way — but then subsequently reverted in some later version?

So it would be good to know what Chrome version you’re testing in.

Anyway, I agree this is confusing but I’m not sure whether we should try to document it in MDN.

**Comment by sideshowbarker** [comment]
cc’ing @mathiasbynens for some insight and guidance on this one

**Comment by mathiasbynens** [comment]
> cc’ing @mathiasbynens for some insight and guidance on this one

We only support `let`, `class`, and `const` redeclaration *across multiple, separate REPL inputs*. Within a single input, trying to redeclare a `const` throws, matching the ECMAScript spec. See https://goo.gle/devtools-const-repl for details.
