### ISSUE TITLE
Data Storage API link is broken on the Firefox 49 page

### ISSUE THREAD

**Issue by MrBrain295** [mdn/content#15000]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/49

### What specific section or headline is this issue about?

Interfaces/APIs/DOM

### What information was incorrect, unhelpful, or incomplete?

Data Storage API link is broken on the Firefox 49 page.

### What did you expect to see?

A working link or the link removed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/firefox/releases/49`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/49
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/49/index.md
* Last commit: https://github.com/mdn/content/commit/ddb8a71824e3b62c533f2ef6dfe4022e073d2e9b
* Document last modified: 2022-04-03T23:34:32.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #15014 with a fix.
