### ISSUE TITLE
Geolocation API demo returns incorrect location

### ISSUE THREAD

**Issue by Steve-Z** [mdn/content#15010]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/Using_the_Geolocation_API

### What specific section or headline is this issue about?

Result (#result)

### What information was incorrect, unhelpful, or incomplete?

After clicking "Show My Location" button, incorrect coordinates were returned. Correct state and nearby city but miles away from my location.

### What did you expect to see?

My correct geolocation. My iPhone camera correctly tags my photos' locations (same network).

### Do you have anything more you want to share?

Firefox 99.0 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/geolocation_api/using_the_geolocation_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/Using_the_Geolocation_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/geolocation_api/using_the_geolocation_api/index.md
* Last commit: https://github.com/mdn/content/commit/e9d054bed500fbfb003c8ca31758afe577f43e31
* Document last modified: 2022-01-21T19:13:55.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing, @Steve-Z !

The geolocation API uses whatever is available to the device for finding the location. If it's not accurate for you I don't think this is an error in the demo in this page (the demo returns very accurate coordinates for me).

**Comment by Steve-Z** [comment]
Thanks @wbamberg. I turned on Bluetooth and that fixed my accuracy problem.
