### ISSUE TITLE
Unorganised Content – need some kind of bookmark-like facility which points me exactly where to continue reading from the point I left previously

### ISSUE THREAD

**Issue by khorajia** [mdn/content#15026]
The reader does not have any clue as to what was read and what is left out. The reader gets completely lost in the sea of information because the content is not put in a systematic format. It needs to be in a book format with page numbers. Also there needs to be a bookmark facility for smooth continuation after a break.

**Comment by schalkneethling** [comment]
Hey @khorajia, could you expand on this a little. Are you referring to all the content in general or specific sections? Is this related to the reference pages such as https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array or the learning area https://developer.mozilla.org/es/docs/Learn?

**Comment by khorajia** [comment]
For instance if you are reading this article:
https://developer.mozilla.org/en-US/docs/Learn/Front-end_web_developer
There are many links within a page and it is not possible for anyone to everything at once. Now if I wish to continue reading after few days, I need some kind of bookmark like facility which points me exactly where to continue reading from the point I left previously.

**Comment by schalkneethling** [comment]
Thank you so much for the additional feedback here, @khorajia. I have marked this as something to consider by the team.

**Comment by Josh-Cena** [comment]
This is part of the plus features. https://developer.mozilla.org/en-US/plus/docs/features/collections Nevertheless you can always use your browser's bookmarking capability.
