### ISSUE TITLE
Issue with "GTest": …

### ISSUE THREAD

**Issue by bytesized** [mdn/content#1502]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/GTest

#### What information was incorrect, unhelpful, or incomplete?

All GTest documentation links go to a 404 page because the documentation [was moved](https://github.com/google/googletest/blob/master/googletest/docs/README.md).

#### Specific section or headline?

Many of them. Anything with a link pointing within `https://github.com/google/googletest/blob/master/googletest/docs`

#### What did you expect to see?

I expected the links to work.

#### Did you test this? If so, how?

By clicking on them.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/developer_guide/build_instructions/gtest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/GTest
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/developer_guide/build_instructions/gtest/index.html
* Report started: 2021-01-19T18:09:24.800Z

</details>

**Comment by chrisdavidmills** [comment]
To whoever fixes this — the broken GTest links on the referenced page need fixing.

**Comment by japneetsingh035** [comment]
I think this issue was resolved!

**Comment by sideshowbarker** [comment]
The Mozilla build instructions and Mozilla developer guide have been completely removed from MDN — so this is no longer an issue for MDN.
