### ISSUE TITLE
Issue with "element()": Replace evil button example

### ISSUE THREAD

**Issue by matronator** [mdn/content#1503]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/element()

#### What information was incorrect, unhelpful, or incomplete?

It even states that it doesn't reflect good design practices. Why not then replace it with an example that does show good practices and doesn't put malicious ideas to users heads.

#### Specific section or headline?

[A somewhat more bizarre example](https://developer.mozilla.org/en-US/docs/Web/CSS/element()#a_somewhat_more_bizarre_example)

#### What did you expect to see?

Maybe a form as a background or group of various elements that go together (or don't, but still better than a single button displayed in a fishy way.)

#### Did you test this? If so, how?

Why?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/element()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/element()
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/element()/index.html
* Report started: 2021-01-19T18:29:36.902Z

</details>

**Comment by Ryuno-Ki** [comment]
I think this function crossed my way the other day - but I could only dig up https://iamvdo.me/en/blog/css-element-function during research (which is not what I've seen, but interesting nevertheless)

Perhaps @iamvdo grants MDN the permission to include an example?

**Comment by Ryuno-Ki** [comment]
I just realised, that @LeaVerou had one example for responsive tables using `element()`:
https://lea.verou.me/2018/05/responsive-tables-revisited/

**Comment by iamvdo** [comment]
Hello. Absolutely no problem for using one of my example.
Also, I love the "minimap" use case from https://css-tricks.com/using-the-little-known-css-element-function-to-create-a-minimap-navigator/
