### ISSUE TITLE
Article should show how you can get a list of all the properties for an object

### ISSUE THREAD

**Issue by Fushiguro19** [mdn/content#15046]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes

### What specific section or headline is this issue about?

The prototype chain

### What information was incorrect, unhelpful, or incomplete?

I am unable to get a list of properties using myObject. 
I would like to know how was that list accessed.

### What did you expect to see?

I expected to see how to actually write myObject. in a code snippet because its not working when I'm trying to execute it.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/object_prototypes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/object_prototypes/index.md
* Last commit: https://github.com/mdn/content/commit/10091094be705e7ae699b49f0a0cb1ba97766ab2
* Document last modified: 2022-04-07T02:13:37.000Z

</details>

**Comment by maridoroshuk** [comment]
Hey @Fushiguro19! You

**Comment by maridoroshuk** [comment]
Hey @Fushiguro19! 
You need to execute the code below in the console and after you can type `myObject.` and access all properties.
```
const myObject = {
  city: 'Madrid',
  greet() {
    console.log(`Greetings from ${this.city}`);
  }
}

myObject.greet(); // Greetings from Madrid
```


![image](https://user-images.githubusercontent.com/59647513/163686656-66317b10-9080-4de7-9fa3-da5075a59c3c.png)

**Comment by Fushiguro19** [comment]
Thanks @maridoroshuk !!
