### ISSUE TITLE
Todo-React Tutorial finished github repo does not match tutorial content

### ISSUE THREAD

**Issue by neilgoldman** [mdn/content#15044]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components

### What specific section or headline is this issue about?

Tasks as data, 2nd codeblock

### What information was incorrect, unhelpful, or incomplete?

In the React-Todo tutorial on MDN, the tutorial says to make the render line of the index.js look like this

```ReactDOM.render(<App tasks={DATA} />, document.getElementById("root"));```

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components#tasks_as_data

But the Finished Version repo linked at the beginning of the tutorial uses a multi-line render statement using React.StrictMode tags

```
ReactDOM.render(
  <React.StrictMode>
    <App tasks={DATA} />
  </React.StrictMode>,
  document.getElementById('root')
);
```

https://github.com/mdn/todo-react/blob/master/src/index.js#L13

It is not a huge difference, but I just had to help out a friend who was confused because of this difference, and was solving an unrelated bug thinking it was because of this.

### What did you expect to see?

The code in the repo should match what you get by following the steps in the tutorial. Either the repo or the tutorial steps should be modified.

### Do you have any supporting links, references, or citations?

After the sentence "The final line of src/index.js should read like this:"

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components#tasks_as_data

https://github.com/mdn/todo-react/blob/master/src/index.js#L13

### Do you have anything more you want to share?

Sorry if this sounds nitpicky, but small differences like this can really confuse a beginner who don't understand why the finished code looks different from their code, and they will generally assume they made a mistake following the tutorial rather than the tutorial not matching the repository.

Overall it is a really good tutorial and I appreciate that MDN provides this. Just like I mentioned in an earlier textbox a friend came to me for help after trying for an hour to figure out why her code had a bug and assumed it was related to this.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by neilgoldman** [comment]
Just to add, I can submit a PR with the changes, but don't know if you all would prefer the finished repo be modified, or the tutorial text. If the tutorial text is modified, we should also include a sentence or two explaining what React.StrictMode means.

**Comment by bappyasif** [comment]
fyi, in this 'mdn article' they used 'snippet' there, not full `code`, im sure you know that

**Comment by neilgoldman** [comment]
The beginning of the tutorial says

"Note: If you need to check your code against our version, you can find a finished version of the sample React app code in our [todo-react repository](https://github.com/mdn/todo-react)."

The text above the snippet I linked literally reads "The final line of src/index.js should read like this:" but the final line of todo-react/blob/master/src/index.js does not match this.

I do not know what you mean. My point is that if you follow this tutorial step by step, your finished project will not match the reference finished version.

**Comment by bappyasif** [comment]
output shouldn't be different with `ReactDOM.render(<App tasks={DATA} />, document.getElementById("root"));` either :)

**Comment by neilgoldman** [comment]
I am well of aware of this, but a a newbie to React does not know this. The code you get from following a tutorial should not differ from the reference final version.

A beginner should not have to look up why their code does not match the reference project and then later find out it was a non-functional difference.

They were at [this section](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_interactivity_events_state#adding_a_task) where it says 

" React will give you a warning in your DevTools console — "Warning: Encountered two children with the same key...""

And not getting that error, so they assumed it was related to StrictMode.

**Comment by bappyasif** [comment]
i get it what you mean, but thats part of 'learning', isnt it! having a curious mind :)

**Comment by neilgoldman** [comment]
Following the tutorial is already learning and having a curious mind. The tutorial includes intended bugs and fixing them as part of the tutorial. There should not be hidden differences that teach you to doubt the credibility of a tutorial article.

**Comment by bappyasif** [comment]
sure, mdn deserves to be 'full proof', undoubtedly :)

not that i was undermining your 'effort' here, by any means, hope you know that, thanks....

**Comment by wbamberg** [comment]
@neilgoldman , I agree, they should match. It's always a danger when tutorials and the code are in different places. I had a bit of a look through history to see when/why they diverged, but couldn't find anything.

> Just to add, I can submit a PR with the changes, but don't know if you all would prefer the finished repo be modified, or the tutorial text. If the tutorial text is modified, we should also include a sentence or two explaining what React.StrictMode means.

I'd be very happy to review a PR. Which do you think we should use? I'd pretty ignorant about React.

**Comment by neilgoldman** [comment]
I'd consider myself proficient with React, but nowhere near an expert, so I'll give it some time for anyone else with more knowledge who wants to weigh in.

But I think the tutorial text should be the one that changes. The tutorial begins by using the `create-react-app` tool to create the project boilerplate, which sets up the project with `App` already wrapped in `React.StrictMode` tags.

Though to add another little bit of confusion, it looks like React 18 which released a month ago slightly changed some of the basics for adding your root element to the DOM which makes some other parts of the tutorial out-of-sync.

So maybe a slightly larger PR to update the tutorial content and reference repo to React 18 would be best?


For example, Before React 18
```javascript
import ReactDOM from 'react-dom';
// other imports removed for brevity

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);
```

After React 18
```javascript
import ReactDOM from 'react-dom/client';
// other imports removed for brevity

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```

**Comment by bappyasif** [comment]
my two bits on this would be, if we're going with 'after react 18' approach then it should require update in both 'content and repo' but with 'before react 18 - as it is now in content and repo' we would only have to update 'content and not repo', thanks and happy contributing :)

**Comment by wbamberg** [comment]
@neilgoldman , see also https://github.com/mdn/content/pull/15196 and in particular https://github.com/mdn/content/pull/15196#pullrequestreview-949283728.

I think it would be good for our React docs to be updated to version 18. It looks like the bit you mentioned is covered in that PR:

https://github.com/mdn/content/pull/15196/files#diff-2c14dbd03d07c929cbbdbd1ed7a9b13bfb93c8c1a9c8470ef1e4d8a336f91fa0R315-R316

?

**Comment by neilgoldman** [comment]
Thanks @wbamberg that looks like a good PR. The change I mentioned is actually present in two places in the tutorial article, so I left a comment suggesting a change to the later page where it appears. I think since the tutorial should be updated to match React 18 that means the example repo definitely needs to be updated as well.

We can probably close this issue and move discussion to the PR you linked and maybe create a new issue on the https://github.com/mdn/todo-react repo, or just wait for the update pull request to discuss there.

**Comment by bsmth** [comment]
Hi @neilgoldman I'm going to close this one as it looks like the original issue is fixed by your PR. 

>create a new issue on the https://github.com/mdn/todo-react repo

Feel free to to do this to track follow-up changes as it looks like there is still some outstanding work (upgrading to react 18?).

If you think this is a mistake, feel free to comment here. Thank you :)
