### ISSUE TITLE
Should the software _user_ volume setting really be overridden by the software developer? ... I think not!

### ISSUE THREAD

**Issue by najevi** [mdn/content#15040]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume

### What specific section or headline is this issue about?

Value

### What information was incorrect, unhelpful, or incomplete?

The described (and actual) behavior of this property is contrary to the principle that software user preference take priority over software developer preference.

This principle is why a user prescribed language/locality preference for, say, English(USA) is not arbitrarily (and unilaterally) overriden by the software developer to instead present to the user text in English(UK) or in some other developer-preferred Asian or Arabic language. 

This same principle should be no different for the user prescribed volume setting for any device where the HTMLMediaElement.volume code executes. Illustrating by way of example; if a user has adjusted their device volume to, say, 10% of the loudest possible volume a device is capable of; then that end-user preference should be respected by any HTMLMediaElement served up to that device. A value of (~.volume=1.0), in this example, should correspond to 10% of the loudest possible volume a device is capable of and not 100% of the loudest possible volume a device is capable of.

Does anyone disagree with this principle?

### What did you expect to see?

"A double values must fall between 0 and 1, where 0 is effectively muted and 1 is the current device volume setting prescribed by the user. "

HTMLMediaElement.volume ought to set volume relative to the volume setting currently prescribed/set by the user (i.e. refer to this user setting as "loudest _permitted_ value") rather than the device-capable "loudest _possible_ value". To do otherwise turns the software/user relationship on it's head and has the user working for the software rather than the software working for the user.

So respecting the aforementioned principle, an even less ambiguous description/prescription for this value is:

"A double values must fall between 0 and 1, where 0 is effectively muted and 1 is the loudest permitted value. The current device volume set by the user is always the loudest permitted value."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlmediaelement/volume`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlmediaelement/volume/index.md
* Last commit: https://github.com/mdn/content/commit/83eba422ab9ec896d8d8bc176376936c8745a5b5
* Document last modified: 2022-03-29T04:32:47.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing, @najevi !

I'm not sure where in your issue description there is an incorrect, misleading, or incomplete statement in the MDN docs.

It sounds like you object to the specified behavior of this feature, but that would be an issue for the [specification](https://html.spec.whatwg.org/multipage/), not MDN.

That aside:

> if a user has adjusted their device volume to, say, 10% of the loudest possible volume a device is capable of; then that end-user preference should be respected by any HTMLMediaElement served up to that device. A value of (~.volume=1.0), in this example, should correspond to 10% of the loudest possible volume a device is capable of and not 100% of the loudest possible volume a device is capable of.

I'm not sure I understand this. Is the proposal effectively to assume that the volume the user has chosen at a given time is the maximum volume they will ever want? This doesn't seem like a good assumption.

**Comment by najevi** [comment]
Thank you for referring to the [specification](https://html.spec.whatwg.org/multipage/#toc-semantics). WRT [effective-media-volume](https://html.spec.whatwg.org/multipage/media.html#effective-media-volume) specification; I quote:

> A media element has a playback volume, which is a fraction in the range 0.0 (silent) to 1.0 (loudest). Initially, the volume should be 1.0, but user agents may remember the last set value across sessions, on a per-site basis or otherwise, so the volume may start at other values.
> 
> The volume IDL attribute must return the playback volume of any audio portions of the media element. On setting, if the new value is in the range 0.0 to 1.0 inclusive, the media element's playback volume must be set to the new value. If the new value is outside the range 0.0 to 1.0 inclusive, then, on setting, an "IndexSizeError" DOMException must be thrown instead.
> 
> A media element can also be muted. If anything is muting the element, then it is muted. (For example, when the direction of playback is backwards, the element is muted.)
> 
> The muted IDL attribute must return the value to which it was last set. When a media element is created, if the element has a muted content attribute specified, then the muted IDL attribute should be set to true; otherwise, the user agents may set the value to the user's preferred value (e.g. remembering the last set value across sessions, on a per-site basis or otherwise). While the muted IDL attribute is set to true, the media element must be muted.
> 
> Whenever either of the values that would be returned by the volume and muted IDL attributes change, the user agent must queue a media element task given the media element to fire an event named volumechange at the media element. Then, if the media element is not allowed to play, the user agent must run the internal pause steps for the media element.
> 
> An element's effective media volume is determined as follows:
> 
> 
> 1. If the user has indicated that the user agent is to override the volume of the element, then return the volume desired by the user.
> 2. If the element's audio output is muted, then return zero.
> 3. Let volume be the playback volume of the audio portions of the media element, in range 0.0 (silent) to 1.0 (loudest).
> 4. Return volume, interpreted relative to the range 0.0 to 1.0, with 0.0 being silent, and 1.0 being the loudest setting, values in between increasing in loudness. The range need not be linear. The loudest setting may be lower than the system's loudest possible setting; for example the user could have set a maximum volume.


The specification is quite unambiguous in both the first paragraph and that very last sentence (of 4.); don't you agree? 

i.e. When a user has set a maximum volume of, in the example I offered, 10% then that 10% volume level is the loudest (permitted) setting for the html media element and of course that loudest setting is indeed lower than the system's loudest possible setting .. precisely as the user has prescribed the maximum volume to be.

I don't understand how any other interpretation (than what I have given in this example) could be read into the specification. 
Do you understand this principle of respecting the user prescribed maximum volume setting now?

To answer your specific question (without being baited by your unqualified use of the word **"ever"**) :  
Yes, **until the user adjusts the maximum volume to a new setting** then it _is most appropriate_ to assume that the max volume a user has set _**before** the user causes whichever user agent to call the HTMLMediaElement_ is indeed the max volume that the user would _ever_ want that media element to playback at. If the user _subsequently_ wants to hear a **louder** playback volume then the user may adjust the maximum volume to a new level _before_ causing the user agent to call the same media element again.
In no case should the playback volume of a media element be louder than the the maximum volume preset by the user. I think the specification is very clear on this point.
To assume otherwise is tantamount to presuming that a user's maximum volume setting is to be ignored.



Do you now see how the implementation of HTMLMediaElement.volume is contrary to the specification?

**Comment by teoli2003** [comment]
Just so that you know: we are not able to influence the implementation of a specification. You need to contact browser makers to do this. WebKit, Chromium, and Gecko have public bug trackers. We are merely documenting how the web actually works.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/15040#issuecomment-1100689329 and https://github.com/mdn/content/issues/15040#issuecomment-1100513844
