### ISSUE TITLE
cloneInto example code fails: Error: Encountered unsupported value type writing stack-scoped structured clone

### ISSUE THREAD

**Issue by minfrin** [mdn/content#15059]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts

### What specific section or headline is this issue about?

cloneInto

### What information was incorrect, unhelpful, or incomplete?

The example code has been followed and modified as follows:

```
var promise = new Promise(
      function (resolve, reject) {
          resolve(readerStreamToString(responseStream));
      }
    );

return cloneInto(
  promise,
  window,
  {cloneFunctions: true});
```

The cloneInto cass throws the following exception:

```
Error: Encountered unsupported value type writing stack-scoped structured clone
```

It does not appear that cloneInto works as described, or there are undocumented limitations to cloneInto that need to be highlighted.

At the very least, the docs need to be updated to document what the error above means and how to avoid it.

### What did you expect to see?

Example code leads to a working outcome.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/sharing_objects_with_page_scripts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/sharing_objects_with_page_scripts/index.md
* Last commit: https://github.com/mdn/content/commit/b903430b8167127f27d42645c32876c34fcc3e3f
* Document last modified: 2022-04-07T05:24:35.000Z

</details>

**Comment by Rob--W** [comment]
> It does not appear that cloneInto works as described, or there are undocumented limitations to cloneInto that need to be highlighted.

The limitations are documented: the section mentions that cloneInto "... uses the [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) to clone the object", and that link lists all supported types.

> At the very least, the docs need to be updated to document what the error above means and how to avoid it.

The error "Encountered unsupported value type" is self-explanatory: the type is not supported; a Promise cannot be cloned.

> and how to avoid it.

In the special case of a `Promise`, which I think may be worth documenting, is that the desired result can be achieved by using `window.Promise` instead of `Promise`, and then cloning the resolution value with `cloneInto` if needed:

```js
let promise = new window.Promise(resolve => {
  // if just a primitive, then cloneInto is not needed:
  // resolve("string is a primitive");

  // if not a primitive, such as an object, then the value must be cloned
  let result = { exampleKey: "exampleValue" };
  resolve(cloneInto(result, window));
});
// now promise can be passed to the web page.
```

**Comment by Rob--W** [comment]
For anyone ever stumbling across this in the future: there is a Firefox bug about this issue (i.e. inability to clone a promise) at https://bugzilla.mozilla.org/show_bug.cgi?id=1757066 .
