### ISSUE TITLE
Wrong image is shown

### ISSUE THREAD

**Issue by widheg** [mdn/content#15058]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fr

### What specific section or headline is this issue about?

The second example

### What information was incorrect, unhelpful, or incomplete?

In example 2, the image of example 1 is shown. It does not correspond to the SVG code shown.

### What did you expect to see?

The image corresponding to example 2.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/attribute/fr`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fr
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/fr/index.md
* Last commit: https://github.com/mdn/content/commit/171b2371a2a1e11c80a64f9c27be0e0186234284
* Document last modified: 2022-02-04T07:06:16.000Z

</details>

**Comment by LemonadeCow** [comment]
I can check it out.

**Comment by teoli2003** [comment]
The issue is yours, @LemonadeCow.

**Comment by LemonadeCow** [comment]
Created PR #15073 for this issue
