### ISSUE TITLE
The stacking context is missing the backdrop-filter property

### ISSUE THREAD

**Issue by gxy5202** [mdn/content#15080]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

### What specific section or headline is this issue about?

The stacking context

### What information was incorrect, unhelpful, or incomplete?

In the following description, the [backdrop-filter](https://developer.mozilla.org/zh-CN/docs/Web/CSS/backdrop-filter) property is missing. Although there is a filter property, the backdrop-filter is different from it and cannot directly jump to the link of the backdrop-filter

Element with any of the following properties with value other than none:
[transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform)
[filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)
[perspective](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective)
[clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path)
[mask](https://developer.mozilla.org/en-US/docs/Web/CSS/mask) / [mask-image](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image) / [mask-border](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border)

### What did you expect to see?

Element with any of the following properties with value other than none:
[transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform)
[filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)
[backdrop-filter](https://developer.mozilla.org/zh-CN/docs/Web/CSS/backdrop-filter)
[perspective](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective)
[clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path)
[mask](https://developer.mozilla.org/en-US/docs/Web/CSS/mask) / [mask-image](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image) / [mask-border](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border)

### Do you have any supporting links, references, or citations?

The problem is described in W3C Editor's Draft, Section 2.1 of Filter Effects Module Level 2 [BackdropFilterProperty](https://drafts.fxtf.org/filter-effects-2/#BackdropFilterProperty).

> A computed value of other than none results in the creation of both a [stacking context](https://www.w3.org/TR/CSS21/zindex.html) [[CSS21]](https://drafts.fxtf.org/filter-effects-2/#biblio-css21) and a [Containing Block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block) for absolute and fixed position descendants, unless the element it applies to is a document root element in the current [browsing context](https://html.spec.whatwg.org/multipage/browsers.html#browsing-context).

> Note: This rule works in the same way as for the [filter](https://drafts.fxtf.org/filter-effects-1/#propdef-filter) property.

![image](https://user-images.githubusercontent.com/37973863/163745278-5a684f73-dddf-4bf7-81a4-2b98ff2c30de.png)

### Do you have anything more you want to share?

If we use the latest Microsoft Edge browser, open the 3D view tool, select the z-index tab, and then select "Show only stacking contexts", we can see that the element with the backdrop-filter property  will create a stacking context.

here is my code
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <style>
            .a {
                width: 500px;
                height: 500px;
                background-color: rgba(0, 0, 0);
                backdrop-filter: blur(10px);
            }

            .a .b {
                width: 100px;
                height: 100px;
                background-color: red;
                position: absolute;
                z-index: 1;
            }

            .a .c {
                width: 50px;
                height: 50px;
                position: absolute;
                background-color: blue;
                z-index: 0;
            }
        </style>
    </head>
    <body>
        <div class="a">
            123
            <div class="b">aaa</div>
            <div class="c">bbb</div>
        </div>
    </body>
</html>
```
![image](https://user-images.githubusercontent.com/37973863/163745677-baadaf82-75a6-4c03-b99d-54e21c4a2ed3.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_positioning/understanding_z_index/the_stacking_context`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_positioning/understanding_z_index/the_stacking_context/index.md
* Last commit: https://github.com/mdn/content/commit/533e3a1a457367440cf13514f88e63c393394b2a
* Document last modified: 2022-03-17T00:47:50.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. I see you’ve created a patch for it — could you go ahead and open a pull request with that patch?

**Comment by gxy5202** [comment]
@sideshowbarker thanks, I have submitted the code, please review it
