### ISSUE TITLE
"Barcode Detection API" not marked as experimental on the page

### ISSUE THREAD

**Issue by anuragkalia** [mdn/content#15095]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API#specifications

### What information was incorrect, unhelpful, or incomplete?

"Barcode Detection API" not marked as experimental even though the corresponding standard is a working draft.

https://wicg.github.io/shape-detection-api/#barcode-detection-api

### What did you expect to see?

The experimental symbol in front of the title and the experimental warning on the top of the API page.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #15106 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
