### ISSUE TITLE
Attribute for does not exist

### ISSUE THREAD

**Issue by TheCowMooooo** [mdn/content#1510]
The `for` attribute does not exist for `label` and `output`. Links exist for it, however they just lead to a 404 page.

**Comment by Ryuno-Ki** [comment]
Could you share the page where you found the broken links on?

**Comment by TheCowMooooo** [comment]
[Here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes), it is in the list.

**Comment by Ryuno-Ki** [comment]
Thank you! @rachelandrew Do you want to take it away?

https://github.com/mdn/content/blob/7826d6e8cad907f432a21c1bfd1e803e9dea5e6b/files/en-us/web/html/attributes/index.html#L287

is the matching source code line (the directory seem to lack a couple other attributes)

**Comment by mattiapontonio** [comment]
Why this link is not Red? 🤔
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/for
