### ISSUE TITLE
“Array.prototype.flat()” stack mode does not consider sparse arrays

### ISSUE THREAD

**Issue by breeze55** [mdn/content#15120]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#use_a_stack

### What information was incorrect, unhelpful, or incomplete?

The stack does not consider sparse arrays

`
const arr = [1, 2, ,[3, 4, [5, 6]]];

flatten(arr);

// [1, 2, undefined,3, 4, 5, 6]

`

### What did you expect to see?

`
const arr = [1, 2, ,[3, 4, [5, 6]]];

flatten(arr);

// [1, 2,3, 4, 5, 6]

`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/flat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/flat/index.md
* Last commit: https://github.com/mdn/content/commit/88508ebe5c73264be2cf03f1a949d8099d68d1ea
* Document last modified: 2022-02-04T02:05:25.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#flattening_and_array_holes has the following example:

```js
const arr5 = [1, 2, , 4, 5];
arr5.flat();
// [1, 2, 4, 5]
```

And that example is introduced with the text, _“The flat method removes empty slots in arrays”_

Do you it’s important that the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#use_a_stack example also show an array with an empty slot? If so, can you explain why?

**Comment by sideshowbarker** [comment]
Closing for lack of response
