### ISSUE TITLE
setTimeout does not mention implicit cast

### ISSUE THREAD

**Issue by PythonCoderAS** [mdn/content#15129]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/setTimeout

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

setTimeout will implicitly cast the delay type to a number if the delay is not a number. This can lead to all sorts of silent issues and isn't documented.

### What did you expect to see?

A note saying non-numbers are cast to numbers.

### Do you have any supporting links, references, or citations?

Demo:

```js
setTimeout(() => {
console.log(1);
}, "1000")
```

This code sample will execute a second after running it.

```js
setTimeout(() => {
console.log(1);
}, "string")
```

This code sample will execute instantly.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/settimeout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/setTimeout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/settimeout/index.md
* Last commit: https://github.com/mdn/content/commit/672bace59f60c4931e5cdde8eb32919c924bd191
* Document last modified: 2022-03-14T00:26:56.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #15185 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
