### ISSUE TITLE
Dubious phrase in revved resources section of HTTP caching

### ISSUE THREAD

**Issue by mamdos** [mdn/content#15147]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

### What specific section or headline is this issue about?

revved_resources

### What information was incorrect, unhelpful, or incomplete?

In this document , It' says setting long time expiration cache can be problematic for rarely or infrequently updated resources but it's possible for often or regular updated resources 

I think this is not true since the purpose of using cache is to store rarely modified (updated) resources to reduce server load and improve performance 

Is it a mistake from me or this document really needs to be edited 

### What did you expect to see?

To optimize the use of cached resources, good practices recommend to set expiration times as far in the future as possible. This is possible for resources that are updated rarely or infrequently, but it is problematic for resources that are updated often or regularly.

### Do you have any supporting links, references, or citations?

In this [document of Microsoft](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-6.0) you can see it says : 

> Caching works best with data that changes infrequently and is expensive to generate

**Comment by Josh-Cena** [comment]
Fixed via https://github.com/mdn/content/pull/16009
