### ISSUE TITLE
USDT currency not being validated in intl.NumberFormat

### ISSUE THREAD

**Issue by tommasini** [mdn/content#15153]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/46944231/164226154-5ceb2271-24be-412f-ac7b-f05847e9b790.png)

### What did you expect to see?

![image](https://user-images.githubusercontent.com/46944231/164226213-cd0a6dbb-7d88-4f74-99bc-1e28797a7ce9.png)

But with the USDT currency code instead of XLM

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat/index.md
* Last commit: https://github.com/mdn/content/commit/6f1ecf44bdbbc6a0bf8f8c6be0a6d241dec7b22e
* Document last modified: 2022-04-12T05:38:44.000Z

</details>

**Comment by teoli2003** [comment]
I don't see USDT in ISO 4217. In order to get it in browsers, you need to get ISO 4217 amended. (I think that there is also another standard in the making of crypto-currencies).

cc/ @romulocintra to confirm this.

**Comment by tommasini** [comment]
Thank you so much for the fast answer.
 I was wondering if could be possible here too because XLM is not in the ISO 4217 and the function works.
 I discover here that exist some unofficial codes for cryptos in the ISO 4217 [here](https://en.wikipedia.org/wiki/ISO_4217#Unofficial_codes_for_cryptocurrencies)

**Comment by romulocintra** [comment]
Browsers are doing a fallback implementation, everything you send with 3 chars will be used as your currency. There is an issue on [CLDR to include Cryptocurrencies](https://unicode-org.atlassian.net/browse/CLDR-11499)

**Comment by teoli2003** [comment]
So, if I understand well, there is nothing to update on MDN (until browsers/spec writers deal with more crypto-currencies, like with 4-digit codes).

I'm closing this. Feel free to reopen if you think we should add some information (and I'll happily review a PR then)

Thanks a lot @romulocintra.
