### ISSUE TITLE
SharedArray and Atomics examples don't work!

### ISSUE THREAD

**Issue by kevmoo** [mdn/content#15169]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/and

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

Example fails because `SharedArrayBuffer` is not available

### What did you expect to see?

Demo should work!

### Do you have anything more you want to share?

```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

https://developer.mozilla.org/en-US/docs/Web/API/crossOriginIsolated is `false`

Should either update the hosting story or delete the example 🤷 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/atomics/and`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/and
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/atomics/and/index.md
* Last commit: https://github.com/mdn/content/commit/b8557769aa6c5afb3eb13ffb3e2ae4692b5ef111
* Document last modified: 2021-11-23T19:39:21.000Z

</details>

**Comment by jzombie** [comment]
@kevmoo Which browser and what version are you using?

**Comment by kevmoo** [comment]
I'd suggest looking through all related examples – they are likely all broken.

**Comment by hamishwillee** [comment]
Yes, this requires the server to set:
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```
I have raised https://github.com/mdn/interactive-examples/issues/2105 to see if this can be done by the interactive examples.

In the meantime the [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/SharedArrayBuffer) docs need to be updated to better highlight this issue. Specifically, I THINK we should:
1. Update the BCD with a subfeature for the security requirements to highlight the version. @queengooborg Would it make sense to do this as a subfeature of the constructor?
2. Update the note in constructor header to make it less chrome specific and point to the limitation in the bcd
3. In the top level doc not the restriction in the header.

**Comment by queengooborg** [comment]
If it's consistent across multiple browser engines, or is required by the spec, then yeah, I'd say a BCD subfeature is the way to go!

**Comment by Josh-Cena** [comment]
This seems to be an issue anywhere but in content. Where should we track this? BCD? interactive-examples? Yari?

**Comment by hamishwillee** [comment]
> This seems to be an issue anywhere but in content. 

@Josh-Cena I don't understand what you mean by the above statement

I missed the response from @queengooborg . I believe we need to check the spec and see if this security requirement is defined. If not, work out where it comes from and go from there.

**Comment by Josh-Cena** [comment]
The requirement is defined. It's also present in our content. (See also https://github.com/mdn/content/issues/3489) The only problem here is that our interactive example infra does not serve it with the correct header, which seems more like an infrastructure issue than a content issue. If we want to track the support for COOP and COEP, we can do that in #3489.

**Comment by hamishwillee** [comment]
@Josh-Cena Thanks. 

So yes, this specific bug is an infrastructure issue, which will be fixed (hopefully) by https://github.com/mdn/interactive-examples/issues/2105 

Yes, https://github.com/mdn/content/issues/3489 is a more logical place to track BCD and doc fixes.

**Comment by Josh-Cena** [comment]
OK, let's track it separately in https://github.com/mdn/interactive-examples/issues/2105 and #3489 instead.
