### ISSUE TITLE
Create a 'Using the MediaSession API' tutorial

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1516]
@Rumyra commented on [Thu Oct 15 2020](https://github.com/mdn/sprints/issues/3797)

Due to rel 82 we need a little added extra to MediaSession. Code should be done for release but a nice article to go along side it is always good

**Comment by sideshowbarker** [comment]
Closing this as it seems to have been raised originally as priority for FF 82 release but doesn’t otherwise seem to be a higher priority that other documents not yet written that we’ve not raised specific issues for.
