### ISSUE TITLE
Section "Interpolation" on box-shadow page should be more clear

### ISSUE THREAD

**Issue by myshov** [mdn/content#15168]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow

### What specific section or headline is this issue about?

Interpolation

### What information was incorrect, unhelpful, or incomplete?

The content of Interpolation is not clear. I believe the text in this section describes the behavior during CSS transitions from one box-shadow to another.

### What did you expect to see?

More clear description of Interpolation

### Do you have any supporting links, references, or citations?

There is a question on Stackoverlow and the answer says that Interpolation describes the inner working of the browser that used by only browser developers. I don't think that is true

https://stackoverflow.com/questions/41398269/how-understand-interpolation-about-box-shadow-described-on-mdn

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/box-shadow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/box-shadow/index.md
* Last commit: https://github.com/mdn/content/commit/5ac0339ec2c6b0b0109b51b9f75eb972f54b6a09
* Document last modified: 2022-04-05T11:23:06.000Z

</details>

**Comment by wbamberg** [comment]
Yes, this is probably the most incomprehensible paragraph I've found on MDN.

> The content of Interpolation is not clear. I believe the text in this section describes the behavior during CSS transitions from one box-shadow to another.

I think you are right. The nearest thing to this that I've found in the spec is the [text under _Animation type_](https://drafts.csswg.org/css-backgrounds/#box-shadow), and in our page the [entry for _Animation type_](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow#formal_definition) references the "Interpolation" section as well. So I guess we ought to:

* make it clearer in the "Interpolation" section that we're talking about animation here
* update the content of that section to be closer to the spec (and more understandable)

**Comment by estelle** [comment]
I'll work on this.

**Comment by myshov** [comment]
@estelle JFYI I opened a pull request for adding a new interpolation page https://github.com/mdn/content/pull/15281

**Comment by estelle** [comment]
Thank you @myshov.

https://github.com/mdn/content/pull/16162
