### ISSUE TITLE
Wrong Inheritance for Date

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1517]
@roninbar commented on [Thu Oct 08 2020](https://github.com/mdn/sprints/issues/3764)

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

`Date.prototype` does not inherit from `Function.prototype`. It inherits from `Object.prototype`.
Please fix the Inheritance section of the sidebar.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

---

@sideshowbarker commented on [Sun Oct 11 2020](https://github.com/mdn/sprints/issues/3764#issuecomment-706632149)

There is code in https://github.com/mdn/kumascript/blob/master/macros/JSRef.ejs that seems to be programmatically determining whether to show **Function** or **Object** in the JS sidebar. But I don’t understand how it makes the determination for any cases other than the ones that are hardcoded there.

But maybe somebody else taking a look at that source can figure out what it’s doing (and how to correct it).

---

And speaking of hardcoding, at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object, I notice the sidebar there shows `Object` also inheriting from `Function` — and that’s because the line at https://github.com/mdn/kumascript/blob/master/macros/JSRef.ejs#L46 seems to be hardcoded to set that.

I raised https://github.com/mdn/kumascript/pull/1428 for that

---

@jchimene commented on [Sun Jan 17 2021](https://github.com/mdn/sprints/issues/3764#issuecomment-761857716)

Looking into this.

**Comment by chrisdavidmills** [comment]
@jchimene if you are looking into this, do you want me to assign you to the issue?

**Comment by jchimene** [comment]
No. It looks like @sideshowbarker handled it in https://github.com/mdn/kumascript/pull/1428. I got sidetracked the last few days on the other PRs and didn't get back to this comment to update it after seeing that PR.

**Comment by chrisdavidmills** [comment]
No worries; let's close it.

**Comment by Elchi3** [comment]
This was updated in https://github.com/mdn/yari/pull/2615

Can someone explain to me why `Date` doesn't inherit `Function` and `Object` but just from `Object`?

If I look in the console's autocomplete, I see for built-ins like `Math` its own properties and those from `Object` only. So that's clear to me that it's only inheriting `Object`. 
However, for `Date` it shows own properties and those from `Function` and `Object`. So, why is that? (maybe I'm blanking out on something here, please let me know).

**Comment by Ryuno-Ki** [comment]
I took the chance to take a look into the specification.

Perhaps I'm misreading, but the [properties of the Date constructor]https://262.ecma-international.org/11.0/#sec-properties-of-the-date-constructor) point to the `Function prototype`.

**Comment by jchimene** [comment]
> I took the chance to take a look into the specification.
> 
> Perhaps I'm misreading, but the [properties of the Date constructor](https://262.ecma-international.org/11.0/#sec-properties-of-the-date-constructor) point to the `Function prototype`.

Except that
[sec-properties-of-the-date-prototype-object](https://262.ecma-international.org/11.0/#sec-properties-of-the-date-prototype-object)
states that it's an Object

**Comment by jchimene** [comment]
> I took the chance to take a look into the specification.
> 
> Perhaps I'm misreading, but the [properties of the Date constructor](https://262.ecma-international.org/11.0/#sec-properties-of-the-date-constructor) point to the `Function prototype`.

Ahh, I just realized. Date has an unusual constructor pattern. I'll have to find the reference on SO. I saw found it when researching this PR. It's got something to do with an alternate `new` syntax. It's not possible to discern the inheritance chain for `Date` by looking at the constructor alone.

**Comment by Elchi3** [comment]
Yeah, so that's:

```js
typeof Date.prototype // object
typeof Date // function
```

however, that is nothing special, right?

```js
typeof Array.prototype // object
typeof Array // function
```

**Comment by jchimene** [comment]
When looked at from that perspective, where the return result is `typeof`, yes.

When invoked without the `new` operator:
  * `Date()` is a conversion function returning `toString()` of the current TZ-aware date/time. It does not accept function values.
  *  `Array()` is a conversion function performing `valueOf()` to initialize the array, then returning the array.

```
x = Date()    // "Mon Jan 25 2021 08:14:31 GMT-0700 (Mountain Standard Time)"
y = Array()   // Array []
typeof x      // "string"
typeof y      // "object"
```

**Comment by roninbar** [comment]
@Elchi3 Try typing the following two expressions in the console:
```js
Object.prototype.isPrototypeOf(Date.prototype) // true
Function.prototype.isPrototypeOf(Date.prototype) // false
```

**Comment by sideshowbarker** [comment]
I believe https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date now shows the correct inheritance, so I’m going ahead and closing this as resolved.
