### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1518]
@cor3000 commented on [Thu Oct 08 2020](https://github.com/mdn/sprints/issues/3763)

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

the section on redirect is a bit misleading (at least sounds promising something it actually doesn't provide):

> redirect
> The redirect mode to use: follow (automatically follow redirects), error (abort with an error if a redirect occurs), or manual (**handle redirects manually**). In Chrome the default is follow (before Chrome 47 it defaulted to manual).

comparing it the actual standard (https://fetch.spec.whatwg.org/#requests) making clear it's not actually useful in the way it sounds:

> "manual"
> Retrieves an opaque-redirect filtered response when a request is met with a redirect, to allow a service worker to replay the redirect offline. The **response is otherwise indistinguishable from a network error**, to not violate atomic HTTP redirect handling.

https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch

---

@jchimene commented on [Sat Jan 16 2021](https://github.com/mdn/sprints/issues/3763#issuecomment-761620749)

I'll take a look!

**Comment by chrisdavidmills** [comment]
@jchimene Again, want me to assign you to this?

**Comment by jchimene** [comment]
Sorry, I just reread the docs. Next time I work an issue, I will request an assignment rather than just saying, "Hi!"
It's been merged via https://github.com/mdn/content/pull/1469, so no assignment necessary.

**Comment by chrisdavidmills** [comment]
> Sorry, I just reread the docs. Next time I work an issue, I will request an assignment rather than just saying, "Hi!"
> It's been merged via #1469, so no assignment necessary.

No worries at all, and cool that this has been fixed!
