### ISSUE TITLE
The WebSocket example doesn't work

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1520]
@Lodealodea commented on [Mon Sep 28 2020](https://github.com/mdn/sprints/issues/3739)

The WebSocket Try it Yourself example at https://mdn-samples.mozilla.org/s/websocket-chat/ doesn't work

**Comment by himanshugarg** [comment]
@chrisdavidmills The referenced page seems to have moved as the link - https://mdn-samples.mozilla.org/s/websocket-chat/ - doesn't work

**Comment by chrisdavidmills** [comment]
The sample server is no longer active; a different demo woud need to be created and hosted somewhere.

**Comment by sideshowbarker** [comment]
https://github.com/mdn/content/discussions/5772
