### ISSUE TITLE
Built-in iterables should be more

### ISSUE THREAD

**Issue by codersjj** [mdn/content#15203]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#built-in_iterables

### What specific section or headline is this issue about?

Built-in iterables

### What information was incorrect, unhelpful, or incomplete?

[String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String), [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array), [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray), [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), and [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) are all built-in iterables, because each of their prototype objects implements an @@iterator method.

### What did you expect to see?

[String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String), [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array), [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray), [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), and [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) are all built-in iterables, because each of their prototype objects implements an @@iterator method. **In addition, the [arguments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) object and Some DOM collection types like [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) are also built-in iterables, because each of them implements the @@iterator method.**

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #15312 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
