### ISSUE TITLE
What are all the valid options for Date.prototype.toLocaleDateString()

### ISSUE THREAD

**Issue by s2t2** [mdn/content#15211]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

### What specific section or headline is this issue about?

Options

### What information was incorrect, unhelpful, or incomplete?

The page shows a small number of examples, but not the full list of options.

### What did you expect to see?

A comprehensive list of all the options I could use, and what each does.

### Do you have anything more you want to share?

I am expecting a table like this Python version of the strptime options:
https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/tolocaledatestring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
* Last commit: https://github.com/mdn/content/commit/720c762cf28276587c1bfef67b575f913933a904
* Document last modified: 2022-03-16T11:16:19.000Z

</details>

**Comment by hamishwillee** [comment]
@s2t2 Did you not see the comment in the document?:
![image](https://user-images.githubusercontent.com/5368500/164570384-9450a31b-8018-4ac6-9601-0de01576c1f7.png)
The options are exactly the same. 

MDN is not completely consistent in how we document "duplicates of things". For small lists we will almost always duplicate the list. For very large lists we duplicate the list if there are known subtle differences. If however they items are the same and assumed likely to remain that way we will sometimes instead link as done here. That reduces the maintenance burden.

I have assumed you just did not see the comment. https://github.com/mdn/content/pull/15216 tries to make the cross linking more obvious.

**Comment by teoli2003** [comment]
There is a link to the complete list.

![Capture d’écran 2022-04-22 à 07 30 56](https://user-images.githubusercontent.com/1466293/164609513-6ca46c0a-8a68-42bc-9e59-833ad7fd61ec.png)
