### ISSUE TITLE
Containing block via contain:paint vs other alternatives

### ISSUE THREAD

**Issue by dlaliberte** [mdn/content#15210]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block

### What specific section or headline is this issue about?

Layout and the containing block

### What information was incorrect, unhelpful, or incomplete?

The list [Identifying the containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block) includes this for item iv:
A [contain](https://developer.mozilla.org/en-US/docs/Web/CSS/contain) value of paint (e.g. contain: paint;)

This is misleading since the "value of paint" is overly specific, suggesting the literal value "paint" is used, and the "(e.g. contain: paint;)" is then confusing because it would be redundant.   The reader might be suspicious that there is more to the story, and there is!

### What did you expect to see?

Instead of saying "value of paint", it should refer to "[Paint containment](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Containment#paint_containment)" with the link to information about other ways to specify a paint containment.   The link to [contain](https://developer.mozilla.org/en-US/docs/Web/CSS/contain) is also useful since it is more direct, at least for this way of specifying a paint containment.  On that page, we find 
```
Note: If applied (with value: paint, strict or content), this property creates:

A new [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block) (for the descendants whose [position](https://developer.mozilla.org/en-US/docs/Web/CSS/position) property is absolute or fixed).
```

So, back to the containing block page, why not say "value of 'paint', 'strict', or 'content'", so people don't have to figure out that a value of 'content' (or 'strict'?) implies the equivalent of a value of 'paint'?

### Do you have anything more you want to share?

MDN documentation is a great service, all the more reason to keep it accurate while being very readable. 

I'm not sure about all the other possible ways of affecting the containing block.  This problem came up while trying to figure out why position:fixed was not doing what was expected.   See [Why is my fixed position element not relative to the viewport? - Darren Lester](https://www.darrenlester.com/blog/why-fixed-position-element-not-relative-to-viewport)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/contribute/feedback`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Feedback
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/feedback/index.md
* Last commit: https://github.com/mdn/content/commit/d582bfda3e648eefc2070a742d1b0fe2ea105ca0
* Document last modified: 2022-04-16T05:48:59.000Z

</details>

**Comment by dhurlburtusa** [comment]
`contain: layout` also creates a containing block for fixed position elements. However, it looks like https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block was already updated to include that.

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/26303
