### ISSUE TITLE
RegExp terminology

### ISSUE THREAD

**Issue by pygy** [mdn/content#15227]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges

### What information was incorrect, unhelpful, or incomplete?

RegExp terminology can be confusing, let's not confuse the reader's minds further...

The section title refers to groups and ranges, but goes on to include disjunctions, character classes and back references.

`a|b` is not a group it is a disjunction. `[abc]` is not a range, it is a character class. `\1` and `\k<name>` are neither.

Most of the constructs described in this page are atoms, per the spec, with the exception of `a|b`

The JS API complicates the matter by using `result.groups` to refer to the values of named capturing groups (anonymous capturing groups and non-capturing groups are also groups, but they are excluded from that badly named object).

### What did you expect to see?

Use consistent terminology. Consistent with the spec, and as consistent as possible with itself (`results.group` has sailed, we won't put it back in the box).

I can rewrite some of the page, but I'd like to have the get go before I invest too much time for nothing.

This page could be limited to atoms, and we could create one for sequences (what the spec calls an alternative) and disjunctions, which are not atomic.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions/groups_and_ranges`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/groups_and_ranges/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by sideshowbarker** [comment]
> I can rewrite some of the page, but I'd like to have the get go before I invest too much time for nothing.

The changes you’ve outlined in the issue description sound like welcome improvements — so please do go ahead and create a PR with a rewrite.
