### ISSUE TITLE
Content suggestion: Add content for the Navigation API

### ISSUE THREAD

**Issue by lukewarlow** [mdn/content#15232]
## What is the new suggestion?

The [Navigation API](https://wicg.github.io/navigation-api) (previously known as App History API) is a modern replacement for the History API. Chrome 102 will release support for it so it would be good if it could get added to MDN.

## Why is it important or useful?

 
For developers to be able to start to pick up this better API it needs to be easily discoverable on the single entry point for web documentation. 

Based on the support data I reckon it'd be about 6 pages on the interfaces themselves plus potentially more detailed pages on certain functions, so it would probably be a fair amount of work to do completely. But even just an entry for the Navigation interface with the support data and link to specification would be a useful start.

The browser compat data has been added in this PR:  https://github.com/mdn/browser-compat-data/pull/15951

## Other supporting information

https://wicg.github.io/navigation-api

https://chromestatus.com/feature/6232287446302720 - Chrome status entry

MDN URL: https://developer.mozilla.org/en-US/docs/Web/API

**Comment by Josh-Cena** [comment]
Closed by #21960
