### ISSUE TITLE
pages leading to tutorial are not loading

### ISSUE THREAD

**Issue by themhrao** [mdn/content#15258]
### MDN URL

https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript

### What information was incorrect, unhelpful, or incomplete?

the links leading to tutorial are not loading 

### What did you expect to see?

i want to see tutorial on making a brick breaker game. but its not loading. please help. this is a great learning resource.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/games/tutorials/2d_breakout_game_pure_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/tutorials/2d_breakout_game_pure_javascript/index.md
* Last commit: https://github.com/mdn/content/commit/6fb517d5f9724399d490fb9cda7a03898f40e2fd
* Document last modified: 2022-04-15T05:42:19.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

Please be really specific about which links are not working. All the ones I tried in that page worked for me.

**Comment by themhrao** [comment]
under the lessons OL about game. but never mind now its working
