### ISSUE TITLE
Map.set is missing key types

### ISSUE THREAD

**Issue by jzombie** [mdn/content#15287]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set

### What specific section or headline is this issue about?

Map set function is missing key types in documentation.

### What information was incorrect, unhelpful, or incomplete?

Which variable types can be reliably used with key?

![2022-04-23_11-47](https://user-images.githubusercontent.com/1139657/164933755-b138101e-838f-455f-b8d8-c99c563b538a.png)

### What did you expect to see?

Number, string, symbol, etc...

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/map/set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/map/set/index.md
* Last commit: https://github.com/mdn/content/commit/a5652911e88d08bdb75fde1aa0616a38d84f7084
* Document last modified: 2021-06-22T22:54:14.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #15314 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
