### ISSUE TITLE
Broken Links in Learn -> Forms -> Your First form

### ISSUE THREAD

**Issue by craciunescu** [mdn/content#15280]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Your_first_form

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Forms/Your_first_form#the_form_element

### What information was incorrect, unhelpful, or incomplete?

There are a couple of broken links in the subsection: "The \<form\> element". I have attached a screenshot.

### What did you expect to see?

Either links that work or no links at all

### Do you have anything more you want to share?

![image](https://user-images.githubusercontent.com/25935100/164894397-67e6069e-b921-49c9-9de3-f750fb8d1f05.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/your_first_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Your_first_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/your_first_form/index.md
* Last commit: https://github.com/mdn/content/commit/bf0b84faec66d03c7e8fa9d3f906fe0913ac2105
* Document last modified: 2022-04-12T01:37:16.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve opened #15305 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
