### ISSUE TITLE
Add "Lacuna value" page to the the glossary

### ISSUE THREAD

**Issue by myshov** [mdn/content#15283]
## What is the new suggestion?
There is no page in the glossary explaining what the "lacuna vaule" is

## Why is it important or useful?
The term "lacuna vaule" is used in a [couple](https://developer.mozilla.org/en-US/docs/Web/CSS/filter#interpolation) [places](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/brightness#parameters) on MDN. I think it's a pretty obscure term that has to have a dedicated glossary page.

## Other supporting information
https://berjon.com/xmlbp-no-lacunae-values/

**Comment by teoli2003** [comment]
This sounds like a good idea. I would happily review such a document. @myshov: Do you want to give it a try?

**Comment by myshov** [comment]
@teoli2003 yes. I will take it!

**Comment by myshov** [comment]
@teoli2003 I [found out](https://www.mail-archive.com/public-fx@w3.org/msg00559.html) that "lacuna value" is an old SVGism that is not used anymore. Now [CSS specification](https://www.w3.org/TR/filter-effects-1/#funcdef-filter-grayscale) uses term "initial value" instead of "lacuna value". So we can close this issue and open a new one to replace the "lacuna value" to the "initial value".

**Comment by teoli2003** [comment]
Closing per comment. Thanks for digging this out @myshov.
