### ISSUE TITLE
Issue of Constraint validation API 

### ISSUE THREAD

**Issue by PJ-Luk** [mdn/content#15308]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation

### What specific section or headline is this issue about?

Extensions to other interfaces

### What information was incorrect, unhelpful, or incomplete?

It says that The constraint validation API extends the interfaces for the form-associated elements listed below
[HTMLButtonElement]
[HTMLFieldsetElement]
[HTMLInputElement]
[HTMLObjectElement]
[HTMLOutputElement]
[HTMLSelectElement]
[HTMLTextAreaElement]

But I think [HTMLObjectElement] is not  a form-associated element.
Should [HTMLObjectElement] be excluded from this list?

![Plese see this](https://user-images.githubusercontent.com/97281079/164965981-8b7402da-ccef-4754-b3f6-dfe9976cd80d.png)

### What did you expect to see?

![please see this 2](https://user-images.githubusercontent.com/97281079/164966024-46869b9b-4c5d-4ccb-ad66-2f253279391b.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/constraint_validation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/constraint_validation/index.md
* Last commit: https://github.com/mdn/content/commit/8a491a43bc374d18618918ee3b4ade881479132e
* Document last modified: 2022-01-19T01:58:22.000Z

</details>

**Comment by teoli2003** [comment]
According to the spec, `HTMLObjectElement` does implement the _Constraint validation API_: https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-object-element:dom-cva-willvalidate

What makes you think this is not the case?

**Comment by sideshowbarker** [comment]
> But I think [HTMLObjectElement] is not a form-associated element.
> Should [HTMLObjectElement] be excluded from this list?

https://html.spec.whatwg.org/multipage/forms.html#form-associated-element includes the `object` element among the list of elements normatively (formally) defined as “form-associated elements” — so it’s correct for MDN to include it in the list cited in the question.
