### ISSUE TITLE
CSP article: list all possible directives

### ISSUE THREAD

**Issue by theking2** [mdn/content#15329]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

### What specific section or headline is this issue about?

list all recognized derictives

### What information was incorrect, unhelpful, or incomplete?

There is a lot of examples. But a complete list of all recognized directives is missing

### What did you expect to see?

After some preliminary examples a complete list of all directives recognized

### Do you have any supporting links, references, or citations?

add all directives and all possible values

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/csp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/csp/index.md
* Last commit: https://github.com/mdn/content/commit/0f1f6f74804725f379465c09f698b88611292c90
* Document last modified: 2021-12-01T06:01:14.000Z

</details>

**Comment by hamishwillee** [comment]
FWIW I disagree. The purpose of this page is to introduce the core concepts and context of CSP along with basic how to usage. The place for exhaustive directive listing is, by MDN convention, in the header definition - here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

What might be reasonable is an explicit statement in the introduction that the references is in that doc.
