### ISSUE TITLE
`AbortSignal.throwIfAborted` example seems not correct

### ISSUE THREAD

**Issue by jopemachine** [mdn/content#15348]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/throwIfAborted#implementing_an_abortable_api

### What specific section or headline is this issue about?

Implementing an abortable API

### What information was incorrect, unhelpful, or incomplete?

```js
function myCoolPromiseAPI(..., {signal}) {
  return new Promise((resolve, reject) => {
    //If the signal is already aborted, immediately throw in order to reject the promise.
    signal.throwIfAborted();

    // Perform the main purpose of the API
    // Call resolve(result) when done.

    // Watch for 'abort' signals
    signal.addEventListener('abort', () => {
      // Stop the main operation
      // Reject the promise wth the abort reason.
      reject(signal.reason);
    });
  });
}
```

The document says to call `signal.throwIfAborted` to reject the promise.
But since `throwIfAborted` does not call `reject`, the promise will not be rejected,
This thrown error cannot be caught through `Promise#catch`.

### What did you expect to see?

I think probably the code needs to be changed like below.

```js
function myCoolPromiseAPI(..., {signal}) {
  return new Promise((resolve, reject) => {
	// If the signal is already aborted, immediately throw in order to reject the promise.
    if (signal.aborted) {
		reject(signal.reason);
	}

    // Perform the main purpose of the API
    // Call resolve(result) when done.

    // Watch for 'abort' signals
    signal.addEventListener('abort', () => {
      // Stop the main operation
      // Reject the promise wth the abort reason.
      reject(signal.reason);
    });
  });
}
```

### Do you have any supporting links, references, or citations?

I tried to write short related code in Chrome for testing.

```js
// abort is called before creating promise.
const controller = new AbortController();
controller.abort('some reason');

const promise = new Promise(async (resolve, reject) => {
	// Below thrown error cannot be catched through `Promise#catch` since it does not call reject
	// controller.signal.throwIfAborted();

	if (controller.signal.aborted) {
		reject(controller.signal.reason);
	}

	controller.signal.addEventListener('abort', () => {
		reject(controller.signal.reason);
	});

	setTimeout(() => { resolve('abc') }, 2000);
});

promise.then((res) => {
	console.log('jobs done', res);
}).catch((err) => {
	// Below line not logged when using `throwIfAborted`
	console.log('error catched: ', err);
});

```

**Comment by sideshowbarker** [comment]
@jopemachine This change looks right to me — would you be interested in writing up a PR for it?

**Comment by jopemachine** [comment]
> @jopemachine This change looks right to me — would you be interested in writing up a PR for it?

Sure, I just made a PR.

**Comment by sindresorhus** [comment]
> But since throwIfAborted does not call reject, the promise will not be rejected,
This thrown error cannot be caught through Promise#catch.

@jopemachine This is incorrect. You can throw in a promise constructor as long as it's thrown synchronously.

From the MDN docs:

> If an error is thrown in the executor, the promise is rejected. - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise

Although it's indeed better to use an `if` statement.

**Comment by jopemachine** [comment]
> This is incorrect. You can throw in a promise constructor as long as it's thrown synchronously.

Thanks for correcting it and letting me know.
My understanding was incorrect.

In the synchronous promise constructor, the error should be caught.
The problem of this issue was the constructor's callback is asynchronous.
