### ISSUE TITLE
Content suggestion: document HTTP Refresh header

### ISSUE THREAD

**Issue by ethanaobrien** [mdn/content#15340]
## What is the new suggestion?

To document the refresh header

## Why is it important or useful?

This shouldnt take long to write, it would help web developers learn of a "hidden" header. (I havent been able to find any easy to read documentation for it anywhere)

## Other supporting information

Just about every browser supports it. see [this](https://stackoverflow.com/questions/283752/refresh-http-header), It was created by netscape but never became official.

Header format
```
Refresh: <delay in seconds>;url=<link to redirect to>
```

<br><br>
I would write the docs myself, but Im absolutely terrible with styling (sorry about that)

MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP

**Comment by sideshowbarker** [comment]
Existing documentation on `meta http-equiv=refresh` is at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-http-equiv — and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#examples has an example.

If you believe MDN should have more documentation on it than that, could you be specific about what more?

**Comment by robinmetral** [comment]
FYI, this is part of the HTML spec since 2017 so should absolutely be documented 🙂 happy to help, maybe starting with adding it to the [Headers page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers)

**Comment by hamishwillee** [comment]
Thanks @robinmetral - I see your PR merged. I'll assign to you since I understand from the PR you are working on it.
