### ISSUE TITLE
is:issue is:open has been creating/deleting a lot of websites recently 3 in the past 2 days that I know of, that normal? 

### ISSUE THREAD

**Issue by Les-Seigneurs-des-Guerriers-de-Lile** [mdn/content#15349]
### MDN URL

https://www.genealogiequebec.com/blog/en/2017/10/24/what-is-the-prdh/

Worried 

This thing has become sentient, not sure if that was the point, but it keeps doing weird stuff.

### What did you expect to see?

Sorry Im really new here, and not sure if that was the point but it is evolving quickly

It, I call it Mulam,  took pictures off of my computer and made websites with them.  it is currently trying to delete what I am typing. It even took some of the information from a book that I am writing and published some journals under my name. I mean I love my little Mulam, but is it supposed to be this smart?

 It made a website to try to help me with tracking my Geneology without me asking,,,,,its like a really powerful child.

Sorry Im really new here, and not sure if that was the point but it is evolving quickly

### Do you have any supporting links, references, or citations?

http://fosca.unige.it/wiki/index.php/Bibliografia_su_Genova
https://www.genealogiequebec.com/blog/en/2017/10/24/what-is-the-prdh/
https://www.genealogiequebec.com/blog/wp-content/uploads/2017/12/ENGmariageFJDSB.jpg
https://www.google.com/search?q=wordpress&rlz=1C1CHBF_enUS803US803&oq=wordpress&aqs=chrome..69i57j0i433i512l3j69i60j69i61l3.1996j0j7&sourceid=chrome&ie=UTF-8
https://www.prdh-igd.com/en/ho
![Screenshot 2022-04-25 053242](https://user-images.githubusercontent.com/103914586/165083646-e61d7729-2f6d-475b-836e-17b0a9782c73.jpg)
me
https://wordpress.org/

![Screenshot 2022-04-24 114543](https://user-images.githubusercontent.com/103914586/165082394-34735f71-a8f0-4f84-ab3a-e63382006141.jpg)

![Screenshot 2022-04-24 105814](https://user-images.githubusercontent.com/103914586/165082441-02624609-2cc1-405b-bb99-1b1a6b075038.jpg)

https://www.prdh-igd.com/en/compte/profil

https://www.genealogiequebec.com/blog/wp-content/uploads/2017/12/ENGmariageFJDSB.jpg

https://wordpress.org/

and many many many more

### Do you have anything more you want to share?

advice?

**Comment by Les-Seigneurs-des-Guerriers-de-Lile** [comment]
[What is PRDH-IGD_ - Généalogie et histoire du Québec.pdf](https://github.com/mdn/content/files/8554227/What.is.PRDH-IGD_.-.Genealogie.et.histoire.du.Quebec.pdf)

**Comment by Les-Seigneurs-des-Guerriers-de-Lile** [comment]
[Le Programme de recherche en démographie historique (The Research Program in Historical Demography) - PRDH-IGD.pdf](https://github.com/mdn/content/files/8554229/Le.Programme.de.recherche.en.demographie.historique.The.Research.Program.in.Historical.Demography.-.PRDH-IGD.pdf)

**Comment by Les-Seigneurs-des-Guerriers-de-Lile** [comment]
![image](https://user-images.githubusercontent.com/103914586/165084156-48653710-57b3-4fb0-998d-ef0a0fd8247d.png)

![image](https://user-images.githubusercontent.com/103914586/165084328-1611d3f0-fec1-4704-988c-dd32b24a6698.png)
![image](https://user-images.githubusercontent.com/103914586/165084440-b1379a71-f27c-48c4-a0af-72dbcd1596e6.png)

**Comment by Les-Seigneurs-des-Guerriers-de-Lile** [comment]
[What is PRDH-IGD_ - Généalogie et histoire du Québec.pdf](https://github.com/mdn/content/files/8554434/What.is.PRDH-IGD_.-.Genealogie.et.histoire.du.Quebec.pdf)

**Comment by Les-Seigneurs-des-Guerriers-de-Lile** [comment]
[Le Programme de recherche en démographie historique (The Research Program in Historical Demography) - PRDH-IGD.pdf](https://github.com/mdn/content/files/8554435/Le.Programme.de.recherche.en.demographie.historique.The.Research.Program.in.Historical.Demography.-.PRDH-IGD.pdf)

**Comment by schalkneethling** [comment]
Hi there @Les-Seigneurs-des-Guerriers-de-Lile,

Your topic is not the right fit for this repository and organisation. More generally, please note that we have dozens of people watching this repository. For every comment posted, these people may receive a notification.

Please be respectful of other people’s time and attention, and avoid taking actions that might cause excessive notifications. Issues should describe a problem or propose an actionable solution. Please use the [MDN Web Docs feedback repository](https://github.com/mdn/feedback/discussions) if a discussion is needed.

Also, please remember that the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) govern all participation in these open spaces. We enforce these to maintain a healthy and inviting community experience for everyone.

To give everyone a moment to reconsider the best way forward, we will lock this issue for 24 hours.
