### ISSUE TITLE
Article on MathML <mfrac>: In "Browser Compatibility", "bevelled" is not shown as "deprecated".

### ISSUE THREAD

**Issue by Lucca-mito** [mdn/content#15359]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfrac

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

"bevelled" is not shown as "deprecated", i.e. it does not have a trash can icon

### What did you expect to see?

The trash can (deprecated) icon.

### Do you have any supporting links, references, or citations?

"bevelled" is listed as deprecated earlier in the article.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/mathml/element/mfrac`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfrac
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/mathml/element/mfrac/index.md
* Last commit: https://github.com/mdn/content/commit/1f771d1177c4cde004354204d557ae66df70c97f
* Document last modified: 2021-10-11T11:37:47.000Z

</details>

**Comment by wbamberg** [comment]
Do you have a reference for `bevelled` being deprecated? I can't see one in the spec (https://www.w3.org/TR/MathML3/) but I am not an expert here.

Perhaps the page is wrong and the compat table is correct?

**Comment by sideshowbarker** [comment]
There’s an issue at https://github.com/w3c/mathml/issues/29 but it remains open — so there doesn’t seem to have yet been any decision to formally deprecate it.
