### ISSUE TITLE
Issue with "Reason: CORS header 'Access-Control-Allow-Origin' …": …

### ISSUE THREAD

**Issue by Lucabenj** [mdn/content#1535]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSAllowOriginNotMatchingOrigin

#### What information was incorrect, unhelpful, or incomplete?

"For example, in Apache, add a line such as the following to the server's configuration (within the appropriate <Directory>, <Location>, <Files>, or <VirtualHost> section). The configuration is typically found in a .conf file (httpd.conf and apache.conf are common names for these), or in an .htaccess file."

Header set Access-Control-Allow-Origin **'origin-list'**

#### Specific section or headline?
What went wrong?

#### What did you expect to see?
Enable CORS from multiple domains

If you want to enable CORS for multiple domains (e.g example1.com, example2.com,example3.com), specify them separately one after another:
Header add Access-Control-Allow-Origin "example1.com"
Header add Access-Control-Allow-Origin "example2.com"
Header add Access-Control-Allow-Origin "example3.com"

#### Did you test this? If so, how?
The single list solution does not work. According to the apache manual you have to specify multiple instruction at a time, one for each individual domain.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cors/errors/corsalloworiginnotmatchingorigin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSAllowOriginNotMatchingOrigin
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/cors/errors/corsalloworiginnotmatchingorigin/index.html
* Report started: 2021-01-20T18:56:30.901Z

</details>

**Comment by sideshowbarker** [comment]
> Header add Access-Control-Allow-Origin "example1.com"
> Header add Access-Control-Allow-Origin "example2.com"
> Header add Access-Control-Allow-Origin "example3.com"

That would be wrong. The Access-Control-Allow-Origin value isn’t actually allowed to be a list of origins — the value must instead be either a single origin, or else the `*` wildcard.

Sending multiple Access-Control-Allow-Origin headers just causes browsers to concatenate their values, so the above would have exactly the same effect in browsers as:

    Access-Control-Allow-Origin: example1.com example2.com example3.com

So as an alternative to this PR, I’ve raised https://github.com/mdn/content/pull/1678, which changes the https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSAllowOriginNotMatchingOrigin article to make clear that the value cannot be a list of origins.
