### ISSUE TITLE
Create color-scheme reference page

### ISSUE THREAD

**Issue by lmas** [mdn/content#1536]
Hello, seems we're missing the page for the CSS property [`color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme).

If you go to [this page](https://developer.mozilla.org/en-US/docs/Web/HTML/element/meta/name#standard_metadata_names_defined_in_other_specifications) and look at the paragraph directly above that header, there's a link to the `color-scheme` that complains about it missing.

[Can I Use..](https://caniuse.com/?search=color-scheme) also links directly to the missing `color-scheme` page.

Edit: Huh just found a [w3c draft page](https://drafts.csswg.org/css-color-adjust/#color-scheme-prop) about it, from 16 December 2020 so that explains why it's missing :)

**Comment by chrisdavidmills** [comment]
Thanks for reporting, @lmas !

Looks likw we already have compat data for this — https://github.com/mdn/browser-compat-data/blob/master/css/properties/color-scheme.json — hence caniuse picking it up.

But we do need an actual reference page, which would go at https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme
