### ISSUE TITLE
Automate PR comment that warns that a locale is "frozen"

### ISSUE THREAD

**Issue by peterbe** [mdn/content#15381]
If someone makes a PR on some `ru` or `pl` pages in mdn/translated-content, we should post a PR comment (automatically) that explains that this locale is not actively maintained (i.e. not unfrozen).

**Comment by schalkneethling** [comment]
@Rumyra moved. I reckon this warrants a discussion before turning this issue into something actionable. Should I start one under `Localization` or `Content` on https://github.com/mdn/mdn-community/discussions

**Comment by Rumyra** [comment]
Yes - I'd say localization 👍

**Comment by schalkneethling** [comment]
Closing in favor of the following discussion: https://github.com/mdn/mdn-community/discussions/93
