### ISSUE TITLE
"Next" and "Previous" button is missing from last two chapters of SVG tutorial

### ISSUE THREAD

**Issue by bappyasif** [mdn/content#15384]
"Next" Button is missing in "Tools For SVG" at bottom of this article:
![image](https://user-images.githubusercontent.com/19854521/165308747-e2e32fb5-2d97-4cc1-9794-01858d920d2a.png)

"Previous" button is missing from "SVG and CSS" article at bottom as a part of navigation from articles to articles
![image](https://user-images.githubusercontent.com/19854521/165309397-fcac8f87-97e8-4d2e-aa84-8b5d8333833f.png)

[SVG tutorial](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial) has listed them as a part of it's tutorial but missing "article navigation link - prev/next"
![image](https://user-images.githubusercontent.com/19854521/165310081-52dd655c-ce8d-48b9-a732-e8bbcd104cd2.png)

not sure, if that was intended to be as such or not, just thought of pointing this out, thanks

**Comment by wbamberg** [comment]
Thanks for filing, @bappyasif ! Yes, this is a bug. The macro calls `{{PreviousNext}}` should have another argument pointing to https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_and_CSS, like this:

```
{{ PreviousNext("Web/SVG/Tutorial/SVG_Image_Tag", "Web/SVG/Tutorial/SVG_and_CSS") }}
```

**Comment by wbamberg** [comment]
I would also (but in a separate PR), want to delete all those empty "TBD" sections from https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial, and also the "Introducing SVG from Scratch" heading, so the tutorial links just sit at the top level of that page.

It's been years, and noone has written the other sections of this tutorial.

**Comment by bappyasif** [comment]
@wbamberg  i could make a PR for it with that "macro" in it, if you'd like? thanks :)

**Comment by wbamberg** [comment]
That would be great!

**Comment by bappyasif** [comment]
okay then consider it done, thanks :)
