### ISSUE TITLE
Add information about areas with the same name in grid-template-areas

### ISSUE THREAD

**Issue by myshov** [mdn/content#15392]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas

### What specific section or headline is this issue about?

Values

### What information was incorrect, unhelpful, or incomplete?

This sentence doesn't have information that cell tokens should have the same name to form a single named grid area:
> Multiple named cell tokens within and between rows create a single named grid area that spans the corresponding grid cells.

### What did you expect to see?

We have to add that cell tokens should have the same name to form a single named grid area.

### Do you have any supporting links, references, or citations?

Related to https://github.com/mdn/translated-content/pull/5278

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/grid-template-areas`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/grid-template-areas/index.md
* Last commit: https://github.com/mdn/content/commit/df6360a23ca7c231b4bf1340b028440344bbc159
* Document last modified: 2022-04-25T07:22:46.000Z

</details>

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/pull/15393, I think.
