### ISSUE TITLE
CTZ example is too complicated

### ISSUE THREAD

**Issue by Rudxain** [mdn/content#15396]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/clz32

### What specific section or headline is this issue about?

Description. Specifically ["Count Leading Ones and beyond"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/clz32#count_leading_ones_and_beyond)

### What information was incorrect, unhelpful, or incomplete?

The `ctrz` function

### What did you expect to see?

This:
```js
function ctrz(integer){ // count trailing zeros
    integer >>>= 0 // ensures coercion to Uint32
    if (integer === 0) return 32; // all zeros
    integer &= -integer; // equivalent to `int = int & (~int + 1)`
    return 31 - clz(x);
}
```
I even made a polyfill for `ctz32`:
```js
(function(clz){'use strict';
Math.ctz32 = function(x) {x = +x; return x | 0 ? 31 - clz(x & -x) : 32}
})(Math.clz32)
```

### Do you have any supporting links, references, or citations?

https://en.wikipedia.org/wiki/Find_first_set#CTZ

### Do you have anything more you want to share?

I know the MDN is supposed to be educational, so the complexity of the algorithm can help with learning. But the simple algorithm is good practice. And instead of a replacement, I only ask for both algorithms to be shown

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/math/clz32`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/clz32
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/clz32/index.md
* Last commit: https://github.com/mdn/content/commit/88508ebe5c73264be2cf03f1a949d8099d68d1ea
* Document last modified: 2022-02-04T02:05:25.000Z

</details>

**Comment by sideshowbarker** [comment]
@Rudxain This sounds like a very good improvement — are you interested in creating a PR for it?

**Comment by Rudxain** [comment]
@sideshowbarker Yes, I can start doing it now. But, should both algorithms be shown or only one? I don't know if removing the "old" is a good idea

**Comment by sideshowbarker** [comment]
> @sideshowbarker Yes, I can start doing it now. But, should both algorithms be shown or only one? I don't know if removing the "old" is a good idea

Yeah, let’s keep both. Optionally, the code fencing for the old one and new one can be marked up like this:

````markdown
```js example-bad
/* old algorithm */
```

```js example-good
/* new algorithm */
```
````
…and then in the rendered MDN page, the old one will have a red/bad indicator, and the new one will have a good/green one.

**Comment by Rudxain** [comment]
Ready: https://github.com/mdn/content/pull/15441/commits/8c6ec3587a11d7ef501d1c8780e2d541813b9404
