### ISSUE TITLE
[HTML] Add showPicker() to <input> elements

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#15407]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1745005

## Other

MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD: easy - need to add FF100 (or whatever) and remove experimental.
- [ ] Docs: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/showPicker - I would consider adding a link to the glossary transient activation against the NotAllowed exception. I would also suggest adding examples for other pickers, since it is easy to do, pretty cool, and would not distract from the how to of the existing simple example.
- [ ] Release note
- [ ] dev-docs-complete

**Comment by hamishwillee** [comment]
@Rumyra This is pretty much done bar review. However there is no "ready for review" column [in the project](https://github.com/orgs/mdn/projects/12/views/6). I've just shoved it in the "Done" list - hope that is OK

**Comment by hamishwillee** [comment]
I kind of like the idea of "In Review" because it makes it clear that I'm done with the work and expecting something from you (review, signoff). But if you're happy with this to go into Done and be left open (so that the fact it is open is your trigger for review) then that is fine by me. 

Upshot, you're the one that needs to track the finalisation tasks, so whatever way works best for you is the one we should use.

**Comment by Rumyra** [comment]
I actually just added an 'Archive' column for me to move older FF rel issues into - that means I can keep track of all the work we've done, but keep 'Done' as the current release. Sort of the same but a bit different I guess :)
