### ISSUE TITLE
Some error in `How_browsers_work`

### ISSUE THREAD

**Issue by yin1999** [mdn/content#15413]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Performance/How_browsers_work

### What specific section or headline is this issue about?

- https://developer.mozilla.org/en-US/docs/Web/Performance/How_browsers_work#other_processes
- https://developer.mozilla.org/en-US/docs/Web/Performance/How_browsers_work#tcp_slow_start_14kb_rule

### What information was incorrect, unhelpful, or incomplete?

- The link to `Abstract Syntax Tree` is broken, there is no such a glossary.
- The size of first packet is wrong: (`14Kb` means `14 Kbits` not `14Kbytes`), I think there should be `KB`. Because the [CWND](https://en.wikipedia.org/wiki/TCP_congestion_control#Congestion_window) a small multiple of the [MSS](https://en.wikipedia.org/wiki/Maximum_segment_size). And the [MSS](https://en.wikipedia.org/wiki/Maximum_segment_size) could be about `1412 Kbytes` for Ethernet (<https://blog.apnic.net/2019/07/31/tcp-mss-values-whats-changed/>)

### What did you expect to see?

Fix this link, and correct the `size of first packet` (also with the wrong image below, as `14KB`)

![image](https://user-images.githubusercontent.com/15844309/165418247-9e00584d-ae1d-4e6e-92dc-919ec4cf7c4a.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/performance/how_browsers_work`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Performance/How_browsers_work
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/performance/how_browsers_work/index.md
* Last commit: https://github.com/mdn/content/commit/b903430b8167127f27d42645c32876c34fcc3e3f
* Document last modified: 2022-04-07T05:24:35.000Z

</details>

**Comment by yin1999** [comment]
Hi, I have photoshoped the image as below, and I want to know if it's ok to link the `Abstract Syntax Tree` to [wikipedia](https://en.wikipedia.org/wiki/Abstract_syntax_tree). If it's ok, I'm happe to create a PR to fix this.

![congestioncontrol](https://user-images.githubusercontent.com/15844309/165472042-50916c1e-b365-4d88-b499-6589ceee2122.jpg)

**Comment by sideshowbarker** [comment]
> Hi @sideshowbarker , I have photoshoped the image as below

Beautiful

> and I want to know if it's ok to link the `Abstract Syntax Tree` to [wikipedia](https://en.wikipedia.org/wiki/Abstract_syntax_tree). If it's ok, I'm happe to create a PR to fix this.

Yes, it’s absolutely OK to link to the Wikipedia “Abstract Syntax Tree” article — so yes, please do go ahead with the PR
