### ISSUE TITLE
Content suggestion: Add Iterator Interface Optional Properties

### ISSUE THREAD

**Issue by codersjj** [mdn/content#15434]
## What is the new suggestion?

Add Iterator Interface Optional Properties to [The iterator protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterator_protocol)

## Why is it important or useful?

One page is likely to be needed.
A few hours I think this work should take.

## Other supporting information

https://tc39.es/ecma262/#table-iterator-interface-optional-properties

**Comment by schalkneethling** [comment]
Hey @codersjj! Thank you for opening an issue and sharing your ideas. We recently started the mdn-community repository as a place for the community and staff to share ideas, ask questions, vote on features and more. Would you mind opening this suggestion as a discussion [here](https://github.com/mdn/mdn-community/discussions/categories/content-suggestions)?

Thank you for participating in the MDN Web Docs community.

**Comment by codersjj** [comment]
> Hey @codersjj! Thank you for opening an issue and sharing your ideas. We recently started the mdn-community repository as a place for the community and staff to share ideas, ask questions, vote on features and more. Would you mind opening this suggestion as a discussion [here](https://github.com/mdn/mdn-community/discussions/categories/content-suggestions)?
> 
> If you do open a discussion, please let me know so that I can close the issue. Thank you for participating in the MDN Web Docs community.

Of course not. 😄

**Comment by schalkneethling** [comment]
Thanks so much @codersjj!
