### ISSUE TITLE
[webAPI] AV1 codec strings now supported

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#15463]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

AV1 codec strings passed to MediaCapabilities, HTMLVideoElement.canPlayType and MediaSource.isTypeSupported will now be parsed fully and passed to decoders as av1C data.

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1757861

**Comment by hamishwillee** [comment]
Status: It isn't clear whether this has any real developer facing implication or not -  I am querying in https://bugzilla.mozilla.org/show_bug.cgi?id=1757861

Either way, there is some minor docs improvement work we can do in [`HTMLMediaElement.canPlayType()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType), [`MediaCapabilities.decodingInfo()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaCapabilities/decodingInfo) and [`MediaSource.isTypeSupported()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/isTypeSupported)  to better highlight how codec strings are passed.

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD - in prog: https://github.com/mdn/browser-compat-data/issues/16173
- [ ] Docs
- [ ] Release notes
- [ ] dev-doc-complete

**Comment by hamishwillee** [comment]
@Rumyra All done! Closing :-)
