### ISSUE TITLE
[WebAPI] Prototype Prioritized Task Scheduling API

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#15468]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Prioritized Task Scheduling API

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1734997

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD
- [ ] Docs
- [ ] Experimental features
- [ ] dev-docs-complete

**Comment by hamishwillee** [comment]
All done, bar one minor thingy to merge.

**Comment by Rumyra** [comment]
Nice @hamishwillee

**Comment by hamishwillee** [comment]
Thanks, great to do something with some "meat" to it. But a bit of a challenge at the time.
