### ISSUE TITLE
Extra Space

### ISSUE THREAD

**Issue by PJ-Luk** [mdn/content#15460]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls

### What specific section or headline is this issue about?

Required styles

### What information was incorrect, unhelpful, or incomplete?

I think this should select the element with class #select and #active at the same time instead of the element with class #active that is within a element with class #select
![1](https://user-images.githubusercontent.com/97281079/165703940-4d5a7592-d975-495d-bcac-6f31f59b7891.png)
.

### What did you expect to see?

![2](https://user-images.githubusercontent.com/97281079/165703967-1b4e3a66-de98-485d-a5b4-70ceb2a4e26d.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/how_to_build_custom_form_controls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_build_custom_form_controls/index.md
* Last commit: https://github.com/mdn/content/commit/b06d0695cf809707b421f5202495209928e3519d
* Document last modified: 2022-04-27T05:45:53.000Z

</details>

**Comment by mikoMK** [comment]
Yes, you are right. Thank you!
I also checked the source code of the examples and they correctly use `.select.active`.
Do you like to correct the error yourself?

**Comment by AnilSeervi** [comment]
raised #15472 as the fix
