### ISSUE TITLE
[webAPI] mozPreservePitch is now preservePitch

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#15462]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Looks like bcd update & rel notes

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1652950

**Comment by hamishwillee** [comment]
Status

- [ ] BCD - Already done in https://github.com/mdn/browser-compat-data/pull/15953
- [ ] Docs
- [ ] Release notes
- [ ] dev-doc-complete

**Comment by hamishwillee** [comment]
@Rumyra FYI This is done other than review.

**Comment by Rumyra** [comment]
Awesome - thanks @hamishwillee
