### ISSUE TITLE
Code example for sharing a new candidate does not align with description

### ISSUE THREAD

**Issue by xaviercarmo** [mdn/content#15477]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/icecandidate_event

### What specific section or headline is this issue about?

Sharing a new candidate

### What information was incorrect, unhelpful, or incomplete?

In the code snippet for this section, it uses event.candidate for the first if condition. In the case that event.candidate is an empty string, this will be false, and it will not send the candidate. However in the description below, it emphasises multiple times that we should be sending the empty candidate, and should only refrain from sending the _null_ candidate. Im guessing this should be if (event.candidate !== null) or something?

### What did you expect to see?

I expected to see them sending the empty string candidate.

### Do you have any supporting links, references, or citations?

See the section "indicating the end of a generation of candidates" below:
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/icecandidate_event#indicating_the_end_of_a_generation_of_candidates

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/rtcpeerconnection/icecandidate_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/icecandidate_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/rtcpeerconnection/icecandidate_event/index.md
* Last commit: https://github.com/mdn/content/commit/4b9d61baa046a5aca2cebce3cd6110017e671666
* Document last modified: 2022-03-16T13:04:17.000Z

</details>

**Comment by wbamberg** [comment]
I'm no expert on WebRTC, but as you say the text seems to contradict the example quite clearly.
