### ISSUE TITLE
[WebAPI] Implement RTCRtpEncodingParameters.maxFramerate

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#15470]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Implement `RTCRtpEncodingParameters.maxFramerate`

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1611957

**Comment by hamishwillee** [comment]
Status

- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/16200
   - This is waiting on a w3C spec update https://github.com/w3c/browser-specs/pull/605
   - Further update to merge dictionary might be worth doing. Ignoring for this first-pass.
 - [ ] Docs:
 - [ ] Release notes
 - [ ] dev-doc-complete

**Comment by hamishwillee** [comment]
@Rumyra This one should be pretty much done except for the final reviews.

**Comment by Rumyra** [comment]
Awesome - I realise there's one bcd, but closing with assumption it'll happen 👍
