### ISSUE TITLE
merge is not concluded

### ISSUE THREAD

**Issue by everbrez** [mdn/content#1547]
It seems that merge is not concluded:

https://github.com/mdn/content/blob/caf4851cc148447737667631beb262f5837f1c62/files/en-us/web/html/index.html#L41-L47

and the corresponding page is:
https://developer.mozilla.org/en-US/docs/Web/HTML

**Comment by chrisdavidmills** [comment]
Wow, I can't believe that made its way into the final page!

I've removed it now: https://github.com/mdn/content/commit/b121c1ee503dedfe66c73955794d2631f42a299b

Thanks for reporting.

**Comment by Ryuno-Ki** [comment]
Pinging @peterbe due to https://github.com/mdn/yari/issues/2591 - should be catched now with Yari, I believe.
