### ISSUE TITLE
Issue with "Web audio codec guide": …

### ISSUE THREAD

**Issue by stevens94** [mdn/content#1550]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs

#### What information was incorrect, unhelpful, or incomplete?
Description of G.711 audio codec is totally incorrect.

#### Specific section or headline?
G.711 (Pulse Code Modulation of Voice Frequencies)

#### What did you expect to see?
The G.711 specification, published by the International Telecommunications Union (ITU), was issued in 1972 to define standard audio encoding for telephone applications. It supports voice-grade audio covering frequencies from 300 to 3400 Hz. It is used extensively for telephone traffic and voicemail, and it is the highest quality audio encoding which can be transmitted through the public telephone network.

G.711 is not a high fidelity codec, but rather it is optimized to support a wide range of voice levels (from whisper to shout) while maintaining high intelligibility and low computational complexity. G.711 uses a logarithmic companding algorithm which provides 14 bits of dynamic range in an 8-bit sample. It uses a sampling rate of 8000 samples/sec, corresponding to a bitrate of 64000 bps.

There are two flavors of G.711 which indicate the exact mathematical equation for the algorithm: µ-law (commonly used in North America and Japan) and A-law (common in the rest of the world). There is no substantial quality difference between the two laws, and it is simple to transcode audio from one to the other. Nevertheless, it is important to specify which law is in use in any replay application or file format. A-law audio will replay poorly if mistakenly uncompressed with the µ-law algorithm, and viceversa.

This codec is required to be supported by all WebRTC solutions because it is simple, easy to implement, widely-used, and broadly compatible across all modern computing platforms.

Supported bit rates: 64 kbps
Variable Bit Rate (VBR) support: No
Supported sample formats: encoded audio is 8 bits per sample
Supported sample rates: 8 kHz
Recommended minimum bit rate for stereo sound: 128 kbps
Compression: Logarithmic companding (µ-law or A-law)
Maximum audio channels: 2
Audio frequency bandwidth: 300 Hz – 3400 Hz
Container support: 3GP, WAV

#### Did you test this? If so, how?
I did NOT test, and unsure whether WAV or stereo is actually supported in browsers. But I can assure you that stereo G.711 exists! (typical use is each calling party on one of the channels.)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/media/formats/audio_codecs`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/media/formats/audio_codecs/index.html
* Report started: 2021-01-21T04:02:39.044Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @stevens94 . Do you fancy submitting a pull request on the [page source](https://github.com/mdn/content/blob/main/files/en-us/web/media/formats/audio_codecs/index.html) to fix this?

**Comment by chrisdavidmills** [comment]
To whoever fixes this, the description needs updating as per @stevens94 's text above.

**Comment by teoli2003** [comment]
Thanks a lot for the text, @stevens94 !
