### ISSUE TITLE
URL.port example is misleading

### ISSUE THREAD

**Issue by andersjaensson** [mdn/content#15523]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/URL/port

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The example uses a `https` URL with port `80` like so
```
const url = new URL('https://mydomain.com:80/svn/Repos/');
console.log(url.port); // Logs '80'
```
If the scheme was `http` it would log nothing as `80` is the default port.

### What did you expect to see?

An explanation of why the example uses `https` with port `80`. It is easy to miss the `s`. And maybe a note explaining that the empty string is returned for default ports.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/url/port`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URL/port
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/url/port/index.md
* Last commit: https://github.com/mdn/content/commit/6f4e4cc27b9461828672334aed33a892485cf0a2
* Document last modified: 2022-03-25T05:28:44.000Z

</details>

**Comment by teoli2003** [comment]
Fixed by #15165
