### ISSUE TITLE
getBoundingClientRect: Referenced compabitility problems seem to not be present. Remove warning?

### ISSUE THREAD

**Issue by Jamie5** [mdn/content#15531]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

### What specific section or headline is this issue about?

Notes

### What information was incorrect, unhelpful, or incomplete?

It states "Due to compatibility problems (see below), it is safest to rely on only properties left, top, right, and bottom. "

However, when looking below, I don't see any notes about why to only rely on those four properties.

### What did you expect to see?

Said information that was claimed to be below.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/getboundingclientrect`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/getboundingclientrect/index.md
* Last commit: https://github.com/mdn/content/commit/42a5b601a2eee3842a4bfa20e30138ca3c65e60b
* Document last modified: 2022-04-29T04:45:35.000Z

</details>

**Comment by wbamberg** [comment]
My guess is that it's referring to browser support for `DOMRect.x` and `DOMRect.y`, which is more recent than the others: https://developer.mozilla.org/en-US/docs/Web/API/DOMRect#browser_compatibility. Does that sound likely?

Still though, these properties have been supported for years at this point, so if that is the reason, we should just delete this paragraph.
