### ISSUE TITLE
[page types] Define page types for CSS

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#15540]
Part of https://github.com/mdn/content/issues/15539.

In https://docs.google.com/spreadsheets/d/14RX8EEKPpeYkP2cF5Y_ZKF3JpNJ_24OL7stvZWNJLIY/edit#gid=2083448819, in the "CSS" tab, I've listed every page under https://developer.mozilla.org/en-US/docs/Web/CSS and made an initial determination about the page type.

I've tried to err towards too many page types than too few, since it's easy to amalgamate them but harder to divide them.

I've come up with 16 types:

```
CSS at-rule              16
CSS at-rule descriptor   27
CSS combinator            4
CSS function             74
CSS keyword               8
CSS media feature        39
CSS module               45
CSS property            378
CSS pseudo-class         81
CSS pseudo-element       40
CSS recipe               12
CSS shorthand property   59
CSS type                 37
Guide                   113
Landing page             10
tool                      4
```

...plus two pages that I wasn't able to categorize:
https://developer.mozilla.org/en-US/docs/web/css/color_value/hexadecimal_rgb
https://developer.mozilla.org/en-US/docs/web/css/color_value/system_color_keywords

* I think there's room to argue about whether we could amalgamate some of these. For example, pseudo-elements and pseudo-classes are selectors AFAIK. On the other hand we do currently distinguish them in the sidebar.
* I have split out "CSS recipe" from "Guide" because the recipes have a particular structure. But practically, it's probably not worth differentiating them at this point.
* I have sprinkled a few question marks through, for things I wasn't sure about.

**Comment by wbamberg** [comment]
Thanks Estelle!

This isn't just (or even mostly) for sidebars: it's also, for example, to define the things that different pages must or may contain. So for example, shorthand properties should (probably) have their own type because we want these pages to have a ["Consituent properties" section](https://developer.mozilla.org/en-US/docs/Web/CSS/margin#constituent_properties).

But of course the page types should be able to support the sidebar. At the moment we distinguish selectors, pseudo-classes, and pseudo-elements in the sidebar.

> There are two articles that are fundamental to understanding CSS. Well, maybe more. But specificity and the cascade aren't "guides" like the other guides where you're learning how to use a CSS feature; maybe put those two in "selectors and the cascade" in addition to or instead of guides

I don't think this should be visible as a different page type. A guide page is really just any page that doesn't have any particular structure.

**Comment by teoli2003** [comment]
> https://developer.mozilla.org/en-US/docs/web/css/color_value/hexadecimal_rgb
This can be a CSS function

> https://developer.mozilla.org/en-US/docs/web/css/color_value/system_color_keywords
This is a collection of CSS keywords.

I wonder if we should merge CSS function / CSS keyword and these 2 pages (there is another one I think, I don't have right now) in one single page type.

**Comment by wbamberg** [comment]
> > https://developer.mozilla.org/en-US/docs/web/css/color_value/hexadecimal_rgb

> This can be a CSS function

Could it be a `<hex-color>` type? https://drafts.csswg.org/css-color/#typedef-hex-color

> > https://developer.mozilla.org/en-US/docs/web/css/color_value/system_color_keywords
> 
> This is a collection of CSS keywords.
> 
> I wonder if we should merge CSS function / CSS keyword and these 2 pages (there is another one I think, I don't have right now) in one single page type.

Is there any reason this couldn't be made into a `<system-color>` CSS type page? We don't have one of these (although the spec lists it in the syntax for `<color>`: https://drafts.csswg.org/css-color/#typedef-color.

Similarly I thought we could make https://developer.mozilla.org/en-US/docs/web/css/color_value/color_keywords into a `<named-color>` type.

(In a sense of course many CSS types are "a collection of keywords", like https://developer.mozilla.org/en-US/docs/web/css/blend-mode for instance. It's an enumerated type.)

**Comment by teoli2003** [comment]
I've tried to avoid types that are used only once, but I will try to see how it works in these cases

**Comment by wbamberg** [comment]
Another reason for wanting to do this is: with the new formal syntax macro, we'll get something like this for `<color>` types:

<img width="366" alt="Screen Shot 2022-05-03 at 1 29 15 PM" src="https://user-images.githubusercontent.com/432915/166560656-5ba9aa87-765a-4d1c-8ccd-a0d262e11033.png">

I would like `<hex-color>`, `<named-color>` and `<system-color>` to link to a useful page :). Currently it seems like [we hack this in the macro](https://github.com/mdn/yari/blob/b8b15d5a4b4875d94f94a675df7e34ab6e217d8d/kumascript/macros/CSSSyntax.ejs#L32), but I'd prefer not to do this, as I think it is rather fragile.

**Comment by teoli2003** [comment]
Yes, let's do this.

**Comment by teoli2003** [comment]
I've moved the hexadecimal value page to <hex-color>, let's review it, then I'll do something similar to create <named-color> and <system-color> (we already separate pages for these.

**Comment by wbamberg** [comment]
Having thought about this a bit I think we can go with the set of page types in the original comment: https://github.com/mdn/content/issues/15540#issue-1221660425, with the exception of "CSS recipe" which I think we should treat as a guide for now.

**Comment by wbamberg** [comment]
I think this is done :).
