### ISSUE TITLE
Display <datalist> tag on chromium browsers

### ISSUE THREAD

**Issue by RajuKanaka** [mdn/content#15553]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

### What specific section or headline is this issue about?

All the live examples

### What information was incorrect, unhelpful, or incomplete?

The `<datalist>` tags could have `display: inline-flex` to show the datalist element on the chromium browsers.

### What did you expect to see?

The `labels` to be displayed in the browsers wherever its supported

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/range`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/range/index.md
* Last commit: https://github.com/mdn/content/commit/8dd958883bd69f2fd8105f43d60644dfca572dbc
* Document last modified: 2022-03-25T03:37:54.000Z

</details>

**Comment by estelle** [comment]
datalist is supported everywhere now. Closing.
