### ISSUE TITLE
Outdated guide for setting up MongoDB database

### ISSUE THREAD

**Issue by alabhyajindal** [mdn/content#15556]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

### What specific section or headline is this issue about?

Setting up the MongoDB database

### What information was incorrect, unhelpful, or incomplete?

The user interface of MongoDB has changed. The screenshots and the guide on the page still refer to the old interface which could lead to confusion among learners. 

Correcting this would require modifying the instruction and changing all screenshots under the [Setting up the MongoDB database](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#setting_up_the_mongodb_database) section. Here is a side-by-side comparison of one of the steps, the left image is the one in the guide, right image is how the UI currently looks on MongoDB:

![comparison](https://user-images.githubusercontent.com/52493077/166103759-0865c3b7-ef6c-4d33-bdee-5119ae90350e.jpg)

I would like to work on this and make a PR if that's okay.

### What did you expect to see?

Updated information about how to set up the MongoDB database.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/831aabc34db752bfd7fac701577870d7692b2804
* Document last modified: 2022-04-28T05:11:47.000Z

</details>

**Comment by hamishwillee** [comment]
@alabhyajindal That would be awesome! I have assigned to you.
