### ISSUE TITLE
Object descriptor - configurable

### ISSUE THREAD

**Issue by borishere** [mdn/content#15565]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

### What specific section or headline is this issue about?

Configurable attribute

### What information was incorrect, unhelpful, or incomplete?

As I see, you mean that **value** and **writable** flags could be changed even if **configurable** is set to false.
I tested it in chrome and **writable** can't be changed  - see screenshot.
<img width="514" alt="image" src="https://user-images.githubusercontent.com/4622497/166123406-6c807fa8-d927-43bf-a21f-1ca724c4132f.png">
May be there is some misunderstanding?

### What did you expect to see?

Falsy **configurable**  doesn't allow to change any flag

### Do you have any supporting links, references, or citations?

The configurable attribute controls at the same time whether the property can be deleted from the object and whether its attributes (other than value and writable) can be changed.

### Do you have anything more you want to share?

<img width="785" alt="image" src="https://user-images.githubusercontent.com/4622497/166123137-1c631fd9-0cdf-47e2-b821-b4cf3bb43f05.png">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/defineproperty`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/defineproperty/index.md
* Last commit: https://github.com/mdn/content/commit/edaa4aff4cf7532efdcba6014b9316aad2a5b6f1
* Document last modified: 2022-03-27T17:30:40.000Z

</details>

**Comment by hamishwillee** [comment]
I think you are right - this is a confusing attempt to capture the various caveats covered further down.

![image](https://user-images.githubusercontent.com/5368500/166168925-e6df487c-1b9d-4a02-83d3-ea92d53980b0.png)

How about something like:

> When the `configurable` attribute is set false then properties cannot be deleted and no attributes can be changed. If the `configurable` attribute is set `true` then properties can be deleted from the object and generally attributes, including `writable` can be changed. The exception is the `value` attribute, which requires that both the `configurable` and `writable` attributes are `true`.

**Comment by borishere** [comment]
Yes, that looks more correct.
