### ISSUE TITLE
"A cool-looking box" exercise gives wrong impression about UI design

### ISSUE THREAD

**Issue by mikoMK** [mdn/content#15566]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/A_cool_looking_box

### What specific section or headline is this issue about?

Excercise as a whole

### What information was incorrect, unhelpful, or incomplete?

The exercise is about styling a `<p>`. The end result looks like a button and we even call it a button in the list of subtasks ("A reasonable width/height for a large button"). This gives the wrong impression that it's fine to use a styled `<p>` as a button.

### What did you expect to see?

I see two possibilities to prevent possible misunderstandings:
A) Change the styling of the box so it less looks like a button and change the mention of "button" in the subtasks.
B) Change the exercise to be about "A cool-looking button" and use `<button>` in the starting code.

Personally, I like the gradient, the shadows and the end result. I would tend to version B with no strong opinion either way.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/a_cool_looking_box`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/A_cool_looking_box
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/a_cool_looking_box/index.md
* Last commit: https://github.com/mdn/content/commit/2777cdc8c8b54268a24beeeb7a98520e3331d3be
* Document last modified: 2022-04-26T11:32:33.000Z

</details>

**Comment by schalkneethling** [comment]
I completely agree with you @mikoMK. Also, the end result also has colour contrast problems that needs to be resolved.

**Comment by wbamberg** [comment]
@mikoMK , I agree too. Would you like to file a PR for this?

**Comment by mikoMK** [comment]
Thanks for the feedback @schalkneethling and @wbamberg.
Yes, please. I'll write something up.

**Comment by schalkneethling** [comment]
@mikoMK When updating the article, remember to open a PR against https://github.com/mdn/learning-area/ to edit the code linked to from the assessment. Also, please feel free to ping me for a review. Thanks!

**Comment by mikoMK** [comment]
Congratulations on your first PR here, @vagadeeshwar.
Since I haven't got time to work on this I'm glad you took over. 👍
This is definitively an improvement. 

Two problems I still see:
1. The box still looks like a button. (That was the initial complaint we received on the forum). You could change `height: 55px;` to something like `line-height: 8;` and use `text-align: center;` instead of `padding` for centering.
2. Beside the file @schalkneethling mentioned above there are also the three solution files at https://github.com/mdn/learning-area/tree/main/css/styling-boxes/cool-information-box-finished that need updates. It's important that we keep these files in sync with the assessment and the solution image.

Thank you very much!

**Comment by vagadeeshwar** [comment]
> Congratulations on your first PR here, @vagadeeshwar. Since I haven't got time to work on this I'm glad you took over. 👍 This is definitively an improvement.
> 
> Two problems I still see:
> 
>     1. The box still looks like a button. (That was the initial complaint we received on the forum). You could change `height: 55px;` to something like `line-height: 8;` and use `text-align: center;` instead of `padding` for centering.
> 
>     2. Beside the file @schalkneethling mentioned above there are also the three solution files at https://github.com/mdn/learning-area/tree/main/css/styling-boxes/cool-information-box-finished that need updates. It's important that we keep these files in sync with the assessment and the solution image.
> 
> 
> Thank you very much!

Done!

Also, I don't see any links linking to the starter and solution files from the actual content page. 
Why so?

**Comment by schalkneethling** [comment]
> Also, I don't see any links linking to the starter and solution files from the actual content page.
> Why so?

@wbamberg Any idea?

**Comment by wbamberg** [comment]
For the starter, isn't it this? https://github.com/mdn/content/blob/07025e95df33957519ba4b80f55bb3c7f1ce9b4f/files/en-us/learn/css/building_blocks/a_cool_looking_box/index.md?plain=1#L43 ?

For the solution, it's my understanding that we don't link to a solution from the page. We ask people to ask for an assessment, and the assessor marks it using a marking guide. The marking guide for this assessment is https://github.com/mdn/learning-area/tree/main/css/styling-boxes/cool-information-box-finished.

I would be open to us changing this so people can self-assess, and we link to a solution. I always thought it was a bit odd that we didn't do this.

But again this is a thing we should discuss and apply consistently across the LA, as its own project. And it connects up of course with the discussion at https://github.com/mdn/content/issues/15928.

(I think a systemic problem with the LA is that it wants to have quite an elaborate organization, with modules and articles and "active learning" and assessments and "test your skills" pages, but it's completely reliant on the maintainers to maintain that structure manually, and doesn't give them any help to do so. So over the years, especially as old maintainers leave, it gradually diverges from the original vision until it becomes a but incoherent. It would be great to consider how we might tackle that, by treating LA components as structured pages that must have a particular organization.)

**Comment by vagadeeshwar** [comment]
> For the starter, isn't it this?
> 
> https://github.com/mdn/content/blob/07025e95df33957519ba4b80f55bb3c7f1ce9b4f/files/en-us/learn/css/building_blocks/a_cool_looking_box/index.md?plain=1#L43
> ?
> 
> For the solution, it's my understanding that we don't link to a solution from the page. We ask people to ask for an assessment, and the assessor marks it using a marking guide. The marking guide for this assessment is https://github.com/mdn/learning-area/tree/main/css/styling-boxes/cool-information-box-finished.
> 
> I would be open to us changing this so people can self-assess, and we link to a solution. I always thought it was a bit odd that we didn't do this.
> 
> But again this is a thing we should discuss and apply consistently across the LA, as its own project. And it connects up of course with the discussion at #15928.
> 
> (I think a systemic problem with the LA is that it wants to have quite an elaborate organization, with modules and articles and "active learning" and assessments and "test your skills" pages, but it's completely reliant on the maintainers to maintain that structure manually, and doesn't give them any help to do so. So over the years, especially as old maintainers leave, it gradually diverges from the original vision until it becomes a bit incoherent. It would be great to consider how we might tackle that, by treating LA components as structured pages that must have a particular organization.)

Understood!
Yes, I concur with self-assessment. More like the learners see both the start and finished sample side by side and they can make changes to the starter to make it look like the end.
Cos that's how I learn.

Also,
I don't feel right about using line-height to center the text, can't we just leave the text to start from the top left or something... cos line-height:9 is almost never used that too just to center a text!

Correct me if am wrong, What do you guys think?
