### ISSUE TITLE
Location: live snippet less helpful with HTML/CSS/JS listings included

### ISSUE THREAD

**Issue by bengal75** [mdn/content#15563]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Location

### What specific section or headline is this issue about?

Anatomy Of Location

### What information was incorrect, unhelpful, or incomplete?

The HTML/CSS/JavaScript blocks that have been used to generate the live snippet illustrating the anatomy of the Location object are interesting in their own right, but should not be the focus of this section. IMO it would be more instructive if these could be removed or hidden by default, allowing the focus to be on the snippet itself.

### What did you expect to see?

Having used this page in its previous incarnation, I was expecting to see the interactive "Anatomy of Location" snippet, and was confused until I scrolled down, thinking that the content had been updated as well as the design of the page.

Even if I hadn't been previously familiar with the page contents, from a pedagogical point of view it would make sense to focus on the actual snippet first rather than how it is generated. Unlike some other snippets across MDN, the purpose here is not to allow a developer to recreate the illustrated effect, but instead purely as a teaching aid. The snippet's internal construction (the HTML/CSS/JS behind it) is much less relevant here, and it would be good if the page design could reflect this.

### Do you have anything more you want to share?

The "Result" section here is what I'm looking for when I land on this page. The HTML/CSS/JS is interesting, but very much secondary. As it stands, however, it's presented as the primary focus.

<img width="867" alt="Screenshot 2022-04-30 at 21 31 34" src="https://user-images.githubusercontent.com/5023081/166121678-ac146138-6e3f-40a0-a09d-4b2d011376c5.png">
<img width="867" alt="Screenshot 2022-04-30 at 21 31 59" src="https://user-images.githubusercontent.com/5023081/166121693-41f0978e-83c0-45f6-9505-4e2141d4d748.png">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/location`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Location
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/location/index.md
* Last commit: https://github.com/mdn/content/commit/0850fab8b29cd5ab57b92bb1f77b5bb18adf1ed9
* Document last modified: 2022-01-15T18:36:40.000Z

</details>

**Comment by wbamberg** [comment]
Yes, agreed. I just filed https://github.com/mdn/content/pull/15564 for it. I wonder if it would be better with a line of description before the demo.
