### ISSUE TITLE
Call Stack

### ISSUE THREAD

**Issue by Masterpiece-105** [mdn/content#15560]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Call_stack

### What specific section or headline is this issue about?

Error: Unable to resolve image URL from source (undefined)  This error happened while generating the page. Any console logs will be displayed in the terminal window. Call Stack Object.urlForImage [as default] file:///C:/Users/shubham%20yadav/Desktop/ecommerce/ecommerce1/node_modules/@sanity/image-url/lib/node/urlForImage.js (47:15)

### What information was incorrect, unhelpful, or incomplete?

I dont know

### What did you expect to see?

I want I not show any error 

### Do you have any supporting links, references, or citations?

![Screenshot (747)](https://user-images.githubusercontent.com/86052561/166111654-86a3d134-3b78-4e24-b07d-f255c4ce65b4.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/call_stack`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Call_stack
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/call_stack/index.md
* Last commit: https://github.com/mdn/content/commit/295e508da72ff83272a3b1ffa69a72cfeffcebde
* Document last modified: 2022-02-01T03:06:25.000Z

</details>

**Comment by wbamberg** [comment]
I can't see anything wrong with https://developer.mozilla.org/en-US/docs/Glossary/Call_stack. Can you still reproduce this, @Masterpiece-105 ?

**Comment by sideshowbarker** [comment]
Nothing in the image at https://user-images.githubusercontent.com/86052561/166111654-86a3d134-3b78-4e24-b07d-f255c4ce65b4.png indicates anything related to mdn/content or Yari

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing, problems in the MDN documentation.

It looks like you are looking for help with your code. Unfortunately, we don't have enough availability to help you.

May I suggest asking your question on a specialized website, like StackOverflow?

Thanks for your interest.

**Comment by kalebjorjino** [comment]
const HeroBanner = ( { heroBanner } ) =>{
}
