### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by GutuGaluppo** [mdn/content#1556]
... as mudanças no comportamento dos navegadores não quebrarão o código durante o processo de _padonização_ (**padronização**)

**Comment by chrisdavidmills** [comment]
What page is this typo found on? We can't fix the error with no way of finding it.

**Comment by Ryuno-Ki** [comment]
@chrisdavidmills Should we create a label for this language? (I'd guess it's Portuguese)

**Comment by chrisdavidmills** [comment]
Thing is, we have no intention of unlocking the pt-BR or pt-PT locales yet. To consider that would involve being approached by a team that is willing to take on the responsibiity of maintaining those locales. So I don't want to start maintaining a backlog of issues for those locales either.

If this is about a Portuguese translation, I ought to close it.

**Comment by GutuGaluppo** [comment]
> What page is this typo found on? We can't fix the error with no way of finding it.

Sorry for the late answer guys.
The page is the Vendor Prefix and the language is pt-BR.
