### ISSUE TITLE
Incorrect explanation statement of Javascript scope chain

### ISSUE THREAD

**Issue by thanhit95** [mdn/content#15573]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions#multiply-nested_functions

### What specific section or headline is this issue about?

Scope and the function stack / Multiply-nested functions

### What information was incorrect, unhelpful, or incomplete?

> Because `B`'s closure includes `A`, **`C`'s closure includes `A`**, `C` can access both `B` and `A`'s arguments and variables. In other words, `C` chains the scopes of `B` and `A`, in that order.

### What did you expect to see?

> Because `B`'s closure includes `A`, **`C`'s closure includes `B`**, `C` can access both `B` and `A`'s arguments and variables. In other words, `C` chains the scopes of `B` and `A`, in that order.

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #15696 with a fix.
