### ISSUE TITLE
Issue with "Adding 2D content to a WebGL context": …

### ISSUE THREAD

**Issue by gareththegeek** [mdn/content#1558]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context

#### What information was incorrect, unhelpful, or incomplete?
`mat4` is referenced in the code snippet for drawScene but is not introduced anywhere.
I needed to `yarn add gl-matrix` and `import { mat4 } from 'gl-matrix'` which might trip people up.

#### Specific section or headline?
Rendering the scene

#### What did you expect to see?
Expected explaination of how `mat4` is defined

#### Did you test this? If so, how?
Pasted code snippet into VS Code - have been following along.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl_api/tutorial/adding_2d_content_to_a_webgl_context`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/webgl_api/tutorial/adding_2d_content_to_a_webgl_context/index.html
* Report started: 2021-01-21T10:10:01.537Z

</details>

**Comment by gareththegeek** [comment]
I think this can probably be closed - the document does cover this but I overlooked it - maybe it could be more obvious?

**Comment by Ryuno-Ki** [comment]
Okay, I'm closing. Feel free to reopen if you change your mind.
