### ISSUE TITLE
Pages not found

### ISSUE THREAD

**Issue by dfdaa0** [mdn/content#1559]
In [mozilla's css training (portuguese-brazil)](https://developer.mozilla.org/pt-BR/docs/Web/CSS/Getting_Started) none of the links to the tutorials is functional. 
![Capturarmozilla](https://user-images.githubusercontent.com/62820023/105344579-e1cc2400-5bc1-11eb-9fcf-cce5bffe1e00.PNG)
If i access the tutorials by Google, they are working, but in different URLs. This is the URL that the training guide send you to when you use it - https://developer.mozilla.org/en-US/CSS/Getting_Started/Why_use_CSS
And this is the working URL, that Google shows - https://developer.mozilla.org/pt-BR/docs/Web/CSS/Getting_Started/Porque_usar_CSS

**Comment by chrisdavidmills** [comment]
Hi there @dfdaa0 !

This "Getting started" page is really out of date. The beginner's CSS material now exists on the MDN Learning Area, and on the English version this page now redirects to https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps

There's a pt-BR version of that as well: https://developer.mozilla.org/pt-BR/docs/Learn/CSS/First_steps
