### ISSUE TITLE
Dynamically added textarea fields in FormData are not supported by sending

### ISSUE THREAD

**Issue by dimasikpower** [mdn/content#156]
**Summary**
_What is the problem?_

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Dynamically added textarea fields in FormData are not supported by sending
2. 
3. 

![image](https://user-images.githubusercontent.com/55180531/101317469-a2df4a80-386f-11eb-9be4-c4d783540bb6.png)

**Actual behavior**
_What actually happened?_

**Expected behavior**
_What did you expect to happen?_

**Additional context**
_Is there anything else we should know?_

**Comment by Rumyra** [comment]
Hi @dimasikpower can you provide an MDN page url for this issue - thanks!

**Comment by sideshowbarker** [comment]
Closing for lack of response
