### ISSUE TITLE
"Using Web Workers" link is broken

### ISSUE THREAD

**Issue by jarble** [mdn/content#15622]
### MDN URL

https://developer.mozilla.org/en-US/Using_web_workers

### What specific section or headline is this issue about?

"Using Web Workers"

### What information was incorrect, unhelpful, or incomplete?

This page has a "Page Not Found" error message.

### What did you expect to see?

A link to a page that isn't broken, such as [this one](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API).

**Comment by teoli2003** [comment]
Hi!

Thanks for the report! Where did you find this link?

**Comment by sokarax** [comment]
> Hi!
> 
> 
> 
> Thanks for the report! Where did you find this link?

**Comment by teoli2003** [comment]
So @AnilSeervi found an occurrence and fixed it. So we are closing this. If it wasn't this one, feel free to reopen with the page where you found the link.

Thanks for the report.

**Comment by teoli2003** [comment]
Nothing should link to the url. Where did you find a link to it?

**Comment by jarble** [comment]
@teoli2003 It was an external link (from a forum post). I don't remember exactly where it was posted.
