### ISSUE TITLE
Issue with "CSS Typed Object Model API": Why are some things hidden?

### ISSUE THREAD

**Issue by peterbe** [mdn/content#1563]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS_Typed_OM_API

#### What information was incorrect, unhelpful, or incomplete?

[A portion of the page is wrapped in a `<div class="hidden">`.](https://github.com/mdn/content/blob/97e4d8ce1dc74d402deb43e79f36c76d8cfb2ba6/files/en-us/web/api/css_typed_om_api/index.html#L143-L161)
What is the point of that?

#### Specific section or headline?

You to view source to see it. 

#### What did you expect to see?

It to be removed. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/css_typed_om_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS_Typed_OM_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/css_typed_om_api/index.html
* Report started: 2021-01-21T12:13:34.739Z

</details>

**Comment by schalkneethling** [comment]
You can also see here:
https://github.com/mdn/content/blob/97e4d8ce1dc74d402deb43e79f36c76d8cfb2ba6/files/en-us/glossary/index.html#L42

The subnav is inside a `div` with a class of `hidden`

**Comment by rachelandrew** [comment]
I can have a look, I've seen this before. I think someone who was working on these Houdini specs hid bits they hadn't done yet. I've been doing a bunch of work around these so I'll take a look tomorrow.

**Comment by peterbe** [comment]
> You can also see here:
> 
> https://github.com/mdn/content/blob/97e4d8ce1dc74d402deb43e79f36c76d8cfb2ba6/files/en-us/glossary/index.html#L42
> 
> The subnav is inside a `div` with a class of `hidden`

I think you're talking about a different issue. This particular thing you're bringing up will get automatically solved with https://github.com/mdn/yari/pull/2633

**Comment by rachelandrew** [comment]
Yeah these were essentially to do items, I have come across this kind of thing a few times while working round the Houdini stuff. In the linked PR I've tidied that up.
