### ISSUE TITLE
Ejs Stringfy() looping broken

### ISSUE THREAD

**Issue by Techi-Dev** [mdn/content#15639]
i'm trying to loop on ejs using JSON.stringify()   but i'm receiving  identification errors.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

What do you  expect to see?

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing, problems in the MDN documentation.

It looks like you are looking for help with your code. Unfortunately, we don't have enough availability to help you.

May I suggest asking your question on a specialized website, like StackOverflow?

I'm closing this issue. If I've misunderstood you and you were actually reporting a problem in the documentation, feel free to reopen it, while providing more information so we can understand the problem.

Thanks for your interest.
