### ISSUE TITLE
React App Import Error

### ISSUE THREAD

**Issue by Techi-Dev** [mdn/content#15666]
**Importing Issue**
i'm trying to import react app file to index.js, and the code is right, however it keep throwing an error.

You can share your solution and also explain how you find your solution  useful?
 If you have been encountering the issue , share your code and tell us how to avoid the error for next time as well if possible? 

Is this error due to react update  change made?
i've noticed all of of sudden the app crush when using ReactDOM.render() , is this code not usable anymore?

Attaching the code

<img width="1402" alt="react-bug" src="https://user-images.githubusercontent.com/101612407/166574421-4d02fdb3-80e5-422b-a739-3d733e68794f.png">

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing, problems in the MDN documentation.

It looks like you are looking for help with your code. Unfortunately, we don't have enough availability to help you.

May I suggest asking your question on a specialized website, like StackOverflow?

I'm closing this issue. If I've misunderstood you and you were actually reporting a problem in the documentation, feel free to reopen it, while providing more information so we can understand the problem.

Thanks for your interest.

**Comment by Techi-Dev** [comment]
@teoli2003  I appreciate the suggestion , I agree due to multiple files it is can be confusing.
