### ISSUE TITLE
docs: fix a little format thing

### ISSUE THREAD

**Issue by tjcchen** [mdn/content#1568]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Keyed_collections

#### What information was incorrect, unhelpful, or incomplete?
I am not sure if this is a little format issue( or a typo ) on the content at the bottom of the page. It is about `WeakSets are not enumerable.` line at the bottom of the page.

#### Specific section or headline?
`WeakSets are not enumerable.` content at the bottom of the page  
Should prepend a bullet symbol at the beginning of this line I think, this could be a typo.  
I think this PR could improve our great MDN documents a little. If this is not necessary, please ignore it.

#### What did you expect to see?
- WeakSets are not enumerable.  

a bullet symbol is expected.

#### Did you test this? If so, how?
Yes, by adding this symbol with Markdown on my own computer.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/keyed_collections`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Keyed_collections
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/guide/keyed_collections/index.html
* Report started: 2021-01-18T04:14:32.632Z

</details>

**Comment by tjcchen** [comment]
I think this PR could improve our great MDN documents a little. If this is not necessary, sorry for the bothering, and please ignore it. Thanks in advance!

**Comment by hamishwillee** [comment]
@tjcchen thanks for taking the time to post this - every little bit helps. Fixed in #1602 

Note, you can also fix this kind of thing yourself and create a PR request. That saves us even more time :-)

**Comment by tjcchen** [comment]
Sure, thanks much for your reply and fixing, @hamishwillee. I will submit a PR next time. This is my first time to do a little contribution to our awesome MDN documentation, and I am unfamiliar with the fixing process. 

Your comment did give me a hint on how to fix such issues, appreciate your kind help.

Btw, MDN documentation is really great and helpful in our daily development work. Kudos to your work!
