### ISSUE TITLE
Permissions API 'Browser Compatibility' link in notecard has no address

### ISSUE THREAD

**Issue by coen593** [mdn/content#15690]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API/Using_the_Permissions_API

### What information was incorrect, unhelpful, or incomplete?

The link to 'Browser Compatibility' in the Experimental notecard does not redirect to anywhere (or rather, it redirects to an element that does not exist on the page). It should probably be removed or ideally a browser compatibility table should be shown somewhere in the article.

### What did you expect to see?

I expected the link to redirect me to a browser compatibility table for the Permissions API.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/permissions_api/using_the_permissions_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API/Using_the_Permissions_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/permissions_api/using_the_permissions_api/index.md
* Last commit: https://github.com/mdn/content/commit/add2ddf0803784cb43fbfb81209d68c7123aebb2
* Document last modified: 2022-05-01T05:08:00.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #15697 with a fix
