### ISSUE TITLE
Safari & counter-set

### ISSUE THREAD

**Issue by manngo** [mdn/content#15708]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/counter-set

### What specific section or headline is this issue about?

Compatibility

### What information was incorrect, unhelpful, or incomplete?

Safari supports `counter-reset n` which I think amounts to the same as `counter-set` which it doesn’t support. I think this is worth mentioning.

I’m happy to add this if it seems a good idea.

### What did you expect to see?

See above.

### Do you have any supporting links, references, or citations?

See https://developer.mozilla.org/en-US/docs/Web/CSS/counter-reset

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/counter-set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/counter-set
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/counter-set/index.md
* Last commit: https://github.com/mdn/content/commit/c0611906d2fee37452e9632cef77c28174e32ac9
* Document last modified: 2022-04-22T15:21:26.000Z

</details>

**Comment by hamishwillee** [comment]
@manngo Thank you, but  I don't think so. As I understand it, this is not true: "which I think amounts to the same as counter-set".

It isn't very clear from the current docs, but perhaps a bit more from this PR: https://github.com/mdn/browser-compat-data/pull/15666

In essence counter reset creates a new counter where it is applied while counter-set updates the value of an existing counter. This does much the same thing in some cases - i.e. if the counter being set/reset is an immediate ancestor, but can make quite significant differences for the behaviour when they are applied to peers.

**Comment by manngo** [comment]
One comment from ddbeck in the referenced PR is:

>Excluding Firefox 82 and later, counter-reset and counter-set do the same thing.

I still think it’s worth mentioning.

**Comment by hamishwillee** [comment]
The statement is true because only Firefox follows the spec. Eventually the Chrome implementation will come into line. In the meantime we don't want to be inferring you can safely use something in an off-spec way.
