### ISSUE TITLE
Missing document: !important

### ISSUE THREAD

**Issue by estelle** [mdn/content#15732]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#the_!important_exception

### What specific section or headline is this issue about?

!important exception

### What information was incorrect, unhelpful, or incomplete?

!important is important in CSS. It is relevant to specificity and to the cascade. It is a keyword that can be used in most property values. It is not allowed in animations. The only place it is explained is [/en-US/docs/Web/CSS/Specificity#the_!important_exception](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#the_!important_exception). Does it deserve it's own page? I think so.

### What did you expect to see?

https://developer.mozilla.org/en-US/docs/Web/CSS/important should not 404 ;)

**Comment by Rumyra** [comment]
> https://developer.mozilla.org/en-US/docs/Web/CSS/important should not 404 ;)

Yeh this is a good argument for one @estelle :)

**Comment by estelle** [comment]
Resolved!
