### ISSUE TITLE
`<input>`: most of the basic samples are hidden behind scrollbars

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#15743]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types

### What information was incorrect, unhelpful, or incomplete?

On the page the table shows basic sample of each input type in third column. But most of the sample are being covered by horizontal scrollbars:
![screenshot](https://i.imgur.com/0EfJNxr.png)

Note: no zoom has been applied, notice the address bar.  The resolution on Windows 10 is 1366x768.

### What did you expect to see?

All the basic examples without horizontal scrollbars.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/index.md
* Last commit: https://github.com/mdn/content/commit/1d27eeb2446c33dc402ebd3058b869fd4d1f11b5
* Document last modified: 2022-04-25T05:54:57.000Z

</details>

**Comment by wbamberg** [comment]
I think it would be better to break this table up into separate sections, like:

```
## <input> types

### button

The [button]() type creates a push button ...

[live sample]

### checkbox

The [checkbox]() type creates a check box ...

[live sample]

```

It would give the examples the space they need.

The disadvantage is that it would make this already massive page even longer.

I would also be OK with dropping the live samples and just making this a `<dt>`:

```
- [button]()
  - : A push button with no default behavior displaying the value...
```

I like the idea of these live samples but I think in practice they are not that helpful.

**Comment by maridoroshuk** [comment]
@wbamberg  Hey! Can I work on this?

**Comment by wbamberg** [comment]
Yes, I'd be very happy for you to, but we should get some agreement on we want the fix to look like first.

**Comment by OnkarRuikar** [comment]
We are already using the HTML table there in the markdown. So, why not use actual `<input>` elements instead of livesamples macro. Markdown supports HTML tags. It'll achieve the same thing with less overhead.

For example, for number input we can have following in the markdown. And width can be set such that it'll adjust to the table cell width:
```html
<tr>
      <td>first column</td>
      <td>second column</td>
      <td id="examplenumber">
        <!-- directly use the HTML element and set width to 100%-->
        <input type="number" name="number" style="width:100%;">
        <!-- no need to use this:
         <pre class="brush: html hidden">
               &#x3C;input  type="number" name="number"/></pre>
          {{EmbedLiveSample("examplenumber",200,55,"","", "nobutton")}} -->
      </td>
</tr>
```
![screenshot](https://i.imgur.com/9U4F3Lj.png)
Note, the `password` is still using the livesample. And the number adjusts as per the table cell width.
Also, plus point would be the output will match the dark/light theme. :P
***
Or we can use scalable images instead.

**Comment by wbamberg** [comment]
I think we should maintain a separation between example code and the content of the site, so I don't think we should do this.

**Comment by OnkarRuikar** [comment]
>The disadvantage is that it would make this already massive page even longer.

How about we remove the third examples column, leave the table as it is, and add all in one live sample below it?

**Comment by wbamberg** [comment]
Yes, we could do that. Personally, I think I prefer my second option though. If we have links to the types, then every type's own page has an interactive example at the top, which seems a lot more useful than a context-free live sample (which in many cases just looks like a textbox).

**Comment by maridoroshuk** [comment]
> Yes, we could do that. Personally, I think I prefer my second option though. If we have links to the types, then every type's own page has an interactive example at the top, so it's not hard to see an example, and those examples are a lot more useful than a context-free live sample (which in many cases just looks like a textbox).

I agree thst it's might be better to get rid of the third column based on the fact that every type has own page. 
And yes, replacing html table will look nicer!

**Comment by janbrasna** [comment]
The page works reasonably well on lower resolutions even with three columns and live examples present **_if_** the example iframe content has `overflow:hidden` for its body.

Not sure if that's something universally desirable or viable, just a "drive-by" observation.

**Comment by OnkarRuikar** [comment]
Closing this because the issue has been fixed in yari https://github.com/mdn/yari/pull/6506.
