### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Navigator

### ISSUE THREAD

**Issue by alattalatta** [mdn/content#1576]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
I _think_ these properties should be moved to be under the `NavigatorID`.

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/productSub
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vendor
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vendorSub

On a side note, I found https://github.com/mdn/sprints/issues/1367, but there is `NavigatorID` already so these three would fit better under it.

**Comment by Master613** [comment]
@alattalatta Can you please clarify what you mean by the "NavigatorID". [https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID) redirects to [https://developer.mozilla.org/en-US/docs/Web/API/Navigator](https://developer.mozilla.org/en-US/docs/Web/API/Navigator)
As such, the Navigator.productSub, Navigator.vendor, and Navigator.vendorSub properties **are** under the NavigatorID.

**Comment by teoli2003** [comment]
The mixin NavigatorID (and many other mixins) has been removed after this issue has been opened, making it void.

I'm closing it.
