### ISSUE TITLE
Clarify the part of the “What is JavaScript?” article which discusses the "async" and "defer" attributes

### ISSUE THREAD

**Issue by dcompcoder** [mdn/content#1577]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Under the heading "[async and defer](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript#async_and_defer)", the last sentence of the second paragraph states that 

> It is best to use `async` when the scripts in the page run independently from each other and depend on no other script on the page.

However, Flavio Copes (24 March 2018) wrote that

> [Considering the pros of `defer`, is seems a better choice over `async` in a variety of scenarios.](https://flaviocopes.com/javascript-async-defer)

Obviously, whether it is better to use `async` or `defer` depends on what the script will do and the intention of the author. However, Copes states that when `async` is used

> [The script is fetched asynchronously, and when it’s ready the HTML parsing is paused to execute the script, then it’s resumed.](https://flaviocopes.com/javascript-async-defer)

If Copes' statement is correct, then I think it is important to mention that while a script is being executed, parsing of the HTML is blocked. This is the key reason why Copes thinks that `defer` is better than `async` in terms of the speed of loading a webpage. If Copes is correct, then it is unfortunate that it is not mentioned anywhere in MDN that `async` will block the parsing of HTML during script execution.

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript#async_and_defer

**Comment by chrisdavidmills** [comment]
@Cimeone are you still interesting in doing this one, of shall I unassign you?

**Comment by himanshugarg** [comment]
@Cimeone @chrisdavidmills The section also notes the following :-

> async and defer both instruct the browser to download the script(s) in a separate thread, while the rest of the page (the DOM, etc.) is downloading, so the **page loading is not blocked by the scripts**

which seems to be in conflict with Copes' observation :-

> The script is fetched asynchronously, and when it’s ready **the HTML parsing is paused** to execute the script, then it’s resumed.

Am I missing something?

**Comment by mireille-raad** [comment]
This nice illustration from whatwg.org explains it well.

<img width="941" alt="Screen Shot 2021-06-08 at 3 25 28 PM" src="https://user-images.githubusercontent.com/521705/121387821-fa429e00-c918-11eb-8a43-7af821197b41.png">

Link: [https://html.spec.whatwg.org/multipage/scripting.html#prepare-a-scriptthe  ](https://html.spec.whatwg.org/multipage/scripting.html#prepare-a-scriptthe  )


Should I update the docs and include the image with the original source? I probably should crop the image to remove the module bits because they are not covered in the article and might be confusing.

**Comment by sideshowbarker** [comment]
> Should I update the docs and include the image with the original source?

Yes please — that would be really great

I’ve gone ahead and assigned the issue to you.

Per the HTML spec’s license, we’re free to re-use that image under terms of CC BY 4.0 — which only requires that we include give appropriate credit (_“Image from the [HTML spec](https://html.spec.whatwg.org/images/asyncdefer.svg)”_ or some such), and provide a link to the license (that is, to https://creativecommons.org/licenses/by/4.0/).

> I probably should crop the image to remove the module bits because they are not covered in the article and might be confusing.

Yes, that’d make sense. And so also I think under the _“indicate if changes were made”_ part of the CC BY 4.0 license terms, we’d just need to make sure to mention the image had been cropped — so all together, something like:
> _Image from [the HTML spec](https://html.spec.whatwg.org/images/asyncdefer.svg), copied and cropped to a reduced version, under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) license terms_

**Comment by mireille-raad** [comment]
I submitted a PR: #5872 

side note: I tried to create a png image instead of jpg, but because the image is an SVG file, if I try to edit it with an SVG editor, I get a missing font error and the text becomes squished ... so I used a screenshot instead.

**Comment by sideshowbarker** [comment]
> side note: I tried to create a png image instead of jpg (because that is the format of all the other files, so I figured it might be the standard)...

Yeah, I think for bitmap images in MDN we’re supposed to use png images — but I don’t know whether that’s documented in the style guide or anywhere.

> but because the image is an SVG file, if I try to edit it with an SVG editor, I get a missing font error and the text becomes squished ... so I used a screenshot instead, which means I could not have a transparent background for png.

OK yeah, I think it’s totally fine to have png for this rather than SVG, and I think the lack of a transparent background is fine too
