### ISSUE TITLE
The first parameter is always returned null when i ran the example on Chrome Browser

### ISSUE THREAD

**Issue by awadbensaleh** [mdn/content#15771]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get

### What specific section or headline is this issue about?

Get Method

### What information was incorrect, unhelpful, or incomplete?

https://example.com/?name=Jonathan&age=18

let params = new URLSearchParams(document.location.search);
let name = params.get("name"); // is the string "Jonathan"
let age = parseInt(params.get("age"), 10); // is the number 18

### What did you expect to see?

The content is correct but its working when ran on the chrome browser.

name parameter return null value but when i add "&" infront of name it works. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/urlsearchparams/get`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/urlsearchparams/get/index.md
* Last commit: https://github.com/mdn/content/commit/783f095633e47f57a2c5b744918701225d28fabd
* Document last modified: 2022-04-24T05:48:49.000Z

</details>

**Comment by teoli2003** [comment]
Works for me in both Firefox and Chrome:
- Firefox:
![Firefox](https://user-images.githubusercontent.com/1466293/167242160-824d5a07-0df0-4490-b444-e8ae5c6712e3.png)
- Chrome:
![Chrome](https://user-images.githubusercontent.com/1466293/167242182-1634cb1e-8143-4f93-8b23-f2f452e23fc3.png)

**Comment by teoli2003** [comment]
Do you have a `?` in the string you give to the `URLSearchParams` ctor?

**Comment by awadbensaleh** [comment]
Hi Jean,

I just retried and it gave me the same error see the below screen shots.


Chrome version :
[image: image.png]





https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt


[image: image.png]



thanks & Regards,
Awad.

**Comment by teoli2003** [comment]
(The images have not been transfered)

**Comment by awadbensaleh** [comment]
Chrome version :

![image (1)](https://user-images.githubusercontent.com/31972160/167248350-ee7145da-20cf-42cc-a724-433a6a08027a.png)

[Tried in this editor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt)

[Use the example from the link](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get#browser_compatibility)

![image](https://user-images.githubusercontent.com/31972160/167248352-a1d918ed-c070-4574-9f02-7aa4c39debee.png)

**Comment by teoli2003** [comment]
You are giving the full URL to the `URLSearchParams()`, this is incorrect.

You have to give only the part of the URL _after_ the `?` (a leading `?`) is allowed. See the description and the example at: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams

The example on that page tells you the right way of doing it (using the `search` parameter of an `URL` object):
```
var url = new URL('https://example.com?foo=1&bar=2');
var params = new URLSearchParams(url.search);
```
