### ISSUE TITLE
Example isn't loading

### ISSUE THREAD

**Issue by chriskorosu** [mdn/content#15790]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

Example isn't loading

### What did you expect to see?

A working example based on the HTML/CSS/JS outlined above

### Do you have anything more you want to share?

![image](https://user-images.githubusercontent.com/47898552/167269658-962f9df1-5ff6-476b-b3dd-3c30a431e5f7.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/datatransfer/dropeffect`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/datatransfer/dropeffect/index.md
* Last commit: https://github.com/mdn/content/commit/7f0073df8cd811ebb0f7609385dede3c282a8d97
* Document last modified: 2022-04-30T05:42:32.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #15793 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
