### ISSUE TITLE
Add new properties to themes page

### ISSUE THREAD

**Issue by jscher2000** [mdn/content#15794]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme

### What specific section or headline is this issue about?

Syntax : properties and linked properties details

### What information was incorrect, unhelpful, or incomplete?

Firefox 100 added `color_scheme` and `content_color_scheme` properties to themes in lieu of the previous behavior of auto-assigning a light or dark scheme to add-on themes. These need to be documented.

### What did you expect to see?

Something along the lines of:

Available starting in Firefox 100, the optional `color_scheme` property determines whether a light or dark scheme is used for chrome (such as context menus) and content (such as built-in pages and prefers-color-scheme for web pages). The optional `content_color_scheme` property overrides `color_scheme` for content. Both are strings that can have a value of "auto", "light", "dark", or "system". If you set `color_scheme` and want to let the user control content theming, set `content_color_scheme` to "auto".

### Do you have any supporting links, references, or citations?

* https://bugzilla.mozilla.org/show_bug.cgi?id=1750932
* https://searchfox.org/mozilla-release/source/toolkit/components/extensions/schemas/theme.json#307

### Do you have anything more you want to share?

I apologize for not creating a pull request. This page is too complicated for "my first time."

**Comment by rebloor** [comment]
Completed in [Manifest theme key update #16568](https://github.com/mdn/content/pull/16568)
