### ISSUE TITLE
PowerShell command missing, only has CMD and does not tell you that its CMD only

### ISSUE THREAD

**Issue by myxxmikeyxx** [mdn/content#1580]
While browsing on the [Express Tutorial Part 2 ](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/skeleton_website) I came across the part where we run a command to start the webpage.

![Problem](https://user-images.githubusercontent.com/1766849/105400196-9d0cb100-5bf2-11eb-9b67-ae949bb9a602.PNG)

The code here is correct for CMD but not for PowerShell. it should say 
windows 
     cmd : SET DEBUG=express-locallibrary-tutorial:* & npm start
     ps: $env:DEBUG='express-locallibrary-tutorial:*'; npm start

I have not tired the Linux commands because I am using windows right now.

**Comment by hamishwillee** [comment]
Powershell isn't needed for using express, and the whole tutorial only states how to do things with CMD. 
That said, I think it is worth saying that we only cover CMD.
So in https://github.com/mdn/content/pull/1601 I added the powershell command and a note that we won't describe powershell commands for the rest of the tutorial.

Closing.

Thanks very much!
