### ISSUE TITLE
Issue with "Math.max()": …

### ISSUE THREAD

**Issue by asollberger** [mdn/content#1581]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max

#### What information was incorrect, unhelpful, or incomplete?
It says it returns:
The smallest of the given numbers

#### Specific section or headline?
Return value

#### What did you expect to see?
The largest of the given numbers

#### Did you test this? If so, how?
Math.max obviously should return the largest number.

... this is probably a copy paste error from Math.min

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/math/max`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/math/max/index.html
* Report started: 2021-01-21T20:10:47.412Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @asollberger !

Fixed now; see https://github.com/mdn/content/commit/348feea1ebe19a77866828197b21b9410af9d12d

**Comment by asollberger** [comment]
My pleasure, thanks for correcting it so quickly
