### ISSUE TITLE
“Creating fancy letterheaded paper“ doc: No online source for the images in case there's need for assessment

### ISSUE THREAD

**Issue by why-not-phoenix** [mdn/content#15812]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Creating_fancy_letterheaded_paper

### What specific section or headline is this issue about?

Creating fancy letterheaded paper - Starting Point

### What information was incorrect, unhelpful, or incomplete?

No online source for the images in case there's need for assessment.

### What did you expect to see?

A link to the logo and background images.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/creating_fancy_letterheaded_paper`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Creating_fancy_letterheaded_paper
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/creating_fancy_letterheaded_paper/index.md
* Last commit: https://github.com/mdn/content/commit/2777cdc8c8b54268a24beeeb7a98520e3331d3be
* Document last modified: 2022-04-26T11:32:33.000Z

</details>

**Comment by wbamberg** [comment]
Where it says:

> Save local copies of the [top](https://raw.githubusercontent.com/mdn/learning-area/master/css/styling-boxes/letterheaded-paper-start/top-image.png), [bottom](https://raw.githubusercontent.com/mdn/learning-area/master/css/styling-boxes/letterheaded-paper-start/bottom-image.png) and [logo](https://raw.githubusercontent.com/mdn/learning-area/master/css/styling-boxes/letterheaded-paper-start/logo.png) images in the same directory as your code files.

...aren't these the links?
