### ISSUE TITLE
appendChild chaining warning is confusing

### ISSUE THREAD

**Issue by clshortfuse** [mdn/content#15825]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild

### What information was incorrect, unhelpful, or incomplete?

>Chaining does not work, due to appendChild() returning the child element:
>```js
>let aBlock = document.createElement('block').appendChild( document.createElement('b') );
>```
>Sets aBlock to <b></b> only, meaning you cannot chain further actions on block, like performing several chained appendChild.

### What did you expect to see?

It's confusing that the variable `aBlock` is not the `<block>` element, but instead the `<b>` element. The variable contradicts its type. I think we should have positive examples instead of negative ones. For example, this explains how you can use the return value:

````js
const liElement = ulElement.firstElementChild || ulElement.appendChild(document.createElement('li'));
````

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/node/appendchild`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/node/appendchild/index.md
* Last commit: https://github.com/mdn/content/commit/7a567d4d7458f8ff60483e2098f81eafceab37f5
* Document last modified: 2022-01-18T00:14:33.000Z

</details>

**Comment by wbamberg** [comment]
What do you think about just removing this bit:

> Chaining does not work, due to appendChild() returning the child element:
>
> let aBlock = document.createElement('block').appendChild( document.createElement('b') );
>
> Sets aBlock to <b></b> only, meaning you cannot chain further actions on block, like performing several chained appendChild. 

To be honest it seems a bit random to me.

I'm not sure how much help it is to show someone how to use the return value. It returns what it returns, and we don't know what people might want to do with it.
