### ISSUE TITLE
`FileSystemHandle.requestPermission()` can throw `SecurityError`

### ISSUE THREAD

**Issue by jespertheend** [mdn/content#15831]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle/requestPermission

### What specific section or headline is this issue about?

Exceptions

### What information was incorrect, unhelpful, or incomplete?

Only TypeError is listed, but it's possible for `requestPermission()` to reject with a `SecurityError`

### What did you expect to see?

Mentioning that a `SecurityError` can be thrown and when.

### Do you have any supporting links, references, or citations?

[Here is a demonstration](https://handle-request-permission-security-error.glitch.me/) of a situation where you might get a `SecurityError`. Click 'pick' to select a file or folder on disk, then click 'request write permission' and wait 6 seconds for the `SecurityError` to occur.
Source code for this [is available here](https://glitch.com/edit/#!/handle-request-permission-security-error).

Also, here is `SecurityError` [mentioned in the spec](https://wicg.github.io/file-system-access/#:~:text=a%20SecurityError.-,If%20global%20does%20not%20have%20transient%20activation%2C%20throw%20a%20SecurityError.,-If%20settings%E2%80%99s).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/filesystemhandle/requestpermission`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle/requestPermission
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/filesystemhandle/requestpermission/index.md
* Last commit: https://github.com/mdn/content/commit/71e15c419b606875a6ee77adde4b39de607de5e6
* Document last modified: 2022-04-28T06:41:36.000Z

</details>

**Comment by teoli2003** [comment]
For the person fixing this, there are at least 3 conditions where a `SecurityError` can be raised. Also, this method returns a `Promise` (according to the spec)
