### ISSUE TITLE
Why Microtask keyword is not in Promise Javascript documentation

### ISSUE THREAD

**Issue by krp12345** [mdn/content#1584]
when i call promise object's then method, it will schedule to Microtask queue asynchronously. 
[Promise Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

I was going through it. Why docs did not mention about Microtask queue?

It should be clearly mentioned that then and  catch call adds Microtask to Microtask Queue.

**Comment by jchimene** [comment]
I'd like to propose adding a sentence that contains something like
"**Each of these methods uses the `{{APIRef(Microtask_guide)}}`**" in #instance_method section.

**Comment by Ryuno-Ki** [comment]
@jchimene Take it away!

**Comment by sideshowbarker** [comment]
@krp12345 Please see https://github.com/mdn/content/commit/1712a1f29ae167ddfbf7ffeabc8573c41088566d. If that change resolves this issue to your satisfaction, then please go ahead and close this. Otherwise, if that change doesn’t resolve this issue to your satisfaction, please let us know.

**Comment by krp12345** [comment]
i am closing the issue. thanks a lot. it will help if we mention the link.
