### ISSUE TITLE
Document Array.prototype.findLast and Array.prototype.findLastIndex (ES-stage 3)

### ISSUE THREAD

**Issue by teoli2003** [mdn/content#15851]
See https://www.stefanjudis.com/notes/new-in-javascript-array-findlast-and-array-findlastindex/

The spec proposal: https://github.com/tc39/proposal-array-find-from-last

They have been implemented in Chromium (V8) since v97, they are at stage 3 at EcmaScript.

They are linked (broken for the moment) from the `Array` page which is one of the top-10 on MDN.

@jpmedley Maybe you can help us find somebody to write these two documents?

**Comment by Josh-Cena** [comment]
[`findLast` is now stage-4!](https://github.com/tc39/proposal-array-find-from-last/pull/52)

I thought I was insane some months ago when I found that it already works in Node and Chrome but there's no mention on MDN...

**Comment by hamishwillee** [comment]
FYI, `.findLast()` and `.findLastIndex()` are in BCD - see https://github.com/mdn/browser-compat-data/blob/main/javascript/builtins/Array.json#L642
The firefox bug for this feature is https://bugzilla.mozilla.org/show_bug.cgi?id=1704385

@jpmedley Can we please have an ETA?

**Comment by hamishwillee** [comment]
@jpmedley I am doing this today.

**Comment by hamishwillee** [comment]
Fixed by https://github.com/mdn/content/pull/17977

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/15851#issuecomment-1174681353
