### ISSUE TITLE
Crossorigin parameters don't reflect W3C specifications

### ISSUE THREAD

**Issue by djibe** [mdn/content#15852]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin

### What specific section or headline is this issue about?

First section

### What information was incorrect, unhelpful, or incomplete?

According to MDN, 

Crossorigin attributes are enumerated, and have the following possible values:

anonymous
Request uses CORS headers and credentials flag is set to 'same-origin'.
There is no exchange of user credentials via cookies, client-side SSL certificates or HTTP authentication, unless destination is the same origin.

use-credentials
Request uses CORS headers, credentials flag is set to 'include' and user credentials are always included.

""
Setting the attribute name to an empty value, like crossorigin or crossorigin="", is the same as anonymous.

But reading W3C specs I read this: https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-settings-attributes

    The attribute's invalid value default is the Anonymous state, and its [missing value default](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#missing-value-default) is the No CORS state.

So MDN tells a `crossorigin` equals to anonymous, but W3C specifies it as No CORS state.

For the `crossorigin = ""` both seem to make it equal anonymous.

Am I reading wrong ?

Thank you for your help.

### What did you expect to see?

Setting the attribute name to an empty value (crossorigin=""), is the same as anonymous.

Omitting the attribute like `crossorigin` equals to No CORS state.

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-settings-attributes

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/crossorigin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/crossorigin/index.md
* Last commit: https://github.com/mdn/content/commit/247bca30613eb46efe384c0fb455f7d6b31c0e04
* Document last modified: 2022-05-02T21:33:50.000Z

</details>

**Comment by tlylt** [comment]
(TLDR: missing value != omitted value)

Hi @djibe, 

I re-read the spec you mentioned in [html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-settings-attributes](https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-settings-attributes)
and realized that 
> The attribute's invalid value default is the Anonymous state, and its [missing value default](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#missing-value-default) is the No CORS state.

This is indeed true.

However, "missing value default" [means](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#missing-value-default:~:text=Note%20that%20the%20missing%20value%20default%20applies%20only%20when%20the%20attribute%20is%20missing%2C%20not%20when%20it%20is%20present%20with%20an%20empty%20string%20value.)
> Note that the [missing value default](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#missing-value-default) applies only when the attribute is missing, not when it is present with an empty string value.

So the missing value default should only apply 
> If the attribute is not specified

---

Hence, MDN is correctly stating that:
- not specifying `crossorigin` equals to No CORS
- `crossorigin` equals to `anonymous` (the attribute is not missing)
- `crossorigin=""` equals to `anonymous` (empty string)
- `crossorigin="asdxz" equals to `anonymous` (invalid value)

I also manually tested on latest Chrome:

![image](https://user-images.githubusercontent.com/41845017/210896145-76680618-074b-487e-a6bc-2021db8483f3.png)
![image](https://user-images.githubusercontent.com/41845017/210896204-848288a0-b5cf-457c-802c-90b5dfdd02e4.png)
![image](https://user-images.githubusercontent.com/41845017/210896361-dd219bc4-23cf-4053-ac01-2a4a59143315.png)

Perhaps we can close this issue if the above clarification is clear (and correct :))

(Pinging @sideshowbarker for comment as I do not have the rights 🙏)

**Comment by Josh-Cena** [comment]
Thank you @tlylt! Your research is very convincing and we can close this issue.

**Comment by djibe** [comment]
Lovely answer.
Sorry for my semantic error.
