### ISSUE TITLE
Deprecation box anchor to compatibility table does not work

### ISSUE THREAD

**Issue by todduk** [mdn/content#1585]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setYear
ALSO https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getYear

#### What information was incorrect, unhelpful, or incomplete?
In the deprecation box at the top of the page, the anchor to the compatibility table does not work, it goes to `#Browser_compatibility` but should go to `#browser_compatibility`

#### Specific section or headline?
Deprecation warning

#### What did you expect to see?
Jump to compatibility table

#### Did you test this? If so, how?
Visited two pages with deprecation icon.

EDIT: interestingly the capitalization is correct in the page source but the 'B' is rendered lowercase in Chrome.
https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/setyear/index.html#L70

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/setyear`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setYear
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/date/setyear/index.html
* Report started: 2021-01-21T21:19:25.433Z

</details>

**Comment by chrisdavidmills** [comment]
To the person who fixes this: these boxes are generated by a macro, which call another macro — DeprecatedGeneric for their actual content.

To fix this you need to update the anchor specified in the language strings; see https://github.com/mdn/yari/blob/master/kumascript/macros/DeprecatedGeneric.ejs#L108

And while you are at it, perhaps you could also fix https://github.com/mdn/yari/blob/master/kumascript/macros/SeeCompatTable.ejs#L3

**Comment by chrisdavidmills** [comment]
@todduk do you fancy submitting a PR to the yari repo to fix this?

**Comment by todduk** [comment]
Closed as merged with PR https://github.com/mdn/yari/pull/2667
