### ISSUE TITLE
Please restore NSPR sub-pages that disappeared

### ISSUE THREAD

**Issue by WilsonKathleen** [mdn/content#1586]
I understand that we need to figure out how to move NSS and NSPR content somewhere else this quarter, but it would be very helpful to be able to start with the content that needs to be moved.

In particular, the NSPR sub-pages are no longer available. Would you please restore them?

i.e. All of the links on this page are broken: 
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR#Documentation

**Comment by chrisdavidmills** [comment]
The pages are there, but the links to them are just broken.

So for example https://developer.mozilla.org/en-US/docs/NSPR/About_NSPR now exists at https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR/About_NSPR. The pattern will basically be the same for all of them.

@peterbe does it make sense for me to submit a PR to fix these to the archived content repo, or should we unarchive them first?

**Comment by peterbe** [comment]
> does it make sense for me to submit a PR to fix these to the archived content repo

No, move them over (into `files/en-us/mozilla/projects/nspr/**` etc) first and then, as part of the same unarchive effort, also add the relevant redirects. E.g.
```
/en-US/docs/NSPR [TAB] /en-US/docs/Mozilla/Projects/NSPR
...etc...
```
(remember to use the `yarn tool add-redirect --help` in `yari`)
Once you've done that, all those broken links will be less broken in that they redirect. And if you then want to you can fix all the broken links by apply the fixable flaws. That should take of turning
```diff
-<a href="/en-US/docs/NSPR_build_instructions" title="NSPR_build_instructions">NSPR build instructions</a>
+<a href="/en-US/docs/Mozilla/Projects/NSPR/NSPR_build_instructions" title="NSPR_build_instructions">NSPR build instructions</a>
```

**Comment by himanshugarg** [comment]
Any of the linked pages in the first two comments above don't exist. Is this still an issue? Note this bug needs-triage.

**Comment by hamishwillee** [comment]
All this stuff is supposed to move off MDN, so IMO putting to much effort in is a waste of time.

That said, if someone wanted to put in redirects, they could be created to the archived source: https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/projects/nspr

**Comment by hamishwillee** [comment]
All this stuff is supposed to move off MDN, so IMO putting to much effort in is a waste of time.

That said, if someone wanted to put in redirects, they could be created to the archived source: https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/projects/nspr

**Comment by hamishwillee** [comment]
All this stuff is supposed to move off MDN, so IMO putting to much effort in is a waste of time.

That said, if someone wanted to put in redirects, they could be created to the archived source: https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/projects/nspr

**Comment by WilsonKathleen** [comment]
Fine to close the issue, since we can access the archived pages.
