### ISSUE TITLE
More specific description for positional properties

### ISSUE THREAD

**Issue by vagadeeshwar** [mdn/content#15862]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/bottom https://developer.mozilla.org/en-US/docs/Web/CSS/left https://developer.mozilla.org/en-US/docs/Web/CSS/right

### What specific section or headline is this issue about?

Introduction

### What information was incorrect, unhelpful, or incomplete?

The effect of bottom depends on how the element is positioned (i.e., the value of the [position](https://developer.mozilla.org/en-US/docs/Web/CSS/position) property):

- When position is set to absolute or fixed, the bottom property specifies the distance between the element's _bottom edge_ and the _bottom edge_ of its containing block.

Similarly, for left, right properties

### What did you expect to see?

- When position is set to absolute or fixed, the bottom property specifies the distance between the element's _outer margin of bottom edge_ and the _inner border of the bottom edge_ of its containing block.

### Do you have any supporting links, references, or citations?

It's cleanly mentioned in only the top property.
In bottom/left/right it just mentions as **edge**(padding edge?content edge?...)

https://developer.mozilla.org/en-US/docs/Web/CSS/top

<img width="753" alt="image" src="https://user-images.githubusercontent.com/70265510/167635170-0bed4401-2f30-4948-8626-eb2b53eadd34.png">

### Do you have anything more you want to share?

I have personally checked this with all the position properties and it works as mentioned in top for all.

**Comment by auchynnikau** [comment]
Just created a pull request for it (#21549). Fix is related to left and right properties. As for bottom property it was updated earlier by another contributor without mentioning this issue. So after closing my PR this issue can be resolved :)
