### ISSUE TITLE
Missing Angular To Do App?

### ISSUE THREAD

**Issue by kapunahelewong** [mdn/content#15877]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_getting_started

### What specific section or headline is this issue about?

The Angular Getting Started To Do Sample App

### What information was incorrect, unhelpful, or incomplete?

The sample app that [MDN forked from me](https://github.com/kapunahelewong/angular-to-do-example) in early 2021 (I created the original and wrote the MDN Angular Getting Started when working on the Angular Docs) seems to have been moved, renamed, or deleted. It wouldn't matter to me except that now I have a PR submitted to the original example repo. 

When MDN published the getting started they originally put my personal repo in the tutorial, but I'm a tech writer (not a dev who can keep all the dependencies up-to-date) and I no longer work on the official Angular Documentation. I requested that they take the app and keep it with the other MDN examples, which they did. I am not maintaining the original repo and it's out of date. I'd like to direct the person who as submitted the PR to the appropriate repo. Can you please point me to the right repo so I can direct the PR OP to the right place?

### What did you expect to see?

The Angular Getting Started code.

### Do you have any supporting links, references, or citations?

The [MDN Angular Getting Started](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_getting_started)

[Search for to do repos on gh that doesn't turn up an angular one any more](https://github.com/orgs/mdn/repositories?q=todo&type=all&language=&sort=)

### Do you have anything more you want to share?

Are there still links somewhere to my repo? If so, I'd like to request that they be updated to point elsewhere as I will delete the repo.

**Comment by sideshowbarker** [comment]
Thanks for raising this — there’s link at https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks#angular_tutorials, and that’s the only one. So I’ve opened #15901 to remove that.

> I requested that they take the app and keep it with the other MDN examples, which they did. I am not maintaining the original repo and it's out of date. I'd like to direct the person who as submitted the PR to the appropriate repo. Can you please point me to the right repo so I can direct the PR OP to the right place?

I also haven’t been able to find any existing fork for in the GitHub mdn org — though I see we have https://github.com/mdn/todo-react and https://github.com/mdn/todo-vue.

So as far as I can see, we don’t have any existing repo we could have that PR OP raise their PR against. Which I realize isn’t a super-satisfactory answer, but I don’t have any alternatives to suggest…

**Comment by sideshowbarker** [comment]
> Thanks so much for your quick response, @sideshowbarker. Would someone on your end like to take the original and add it alongside the other todo apps? If you do, I can then link to it from the README.
> 
> [kapunahelewong/angular-to-do-example](https://github.com/kapunahelewong/angular-to-do-example)

I don’t actually have perms to create new repos in the mdn org — so we’d need a decision from @Rumyra or @dipikabh, I think
