### ISSUE TITLE
loops

### ISSUE THREAD

**Issue by trksprkz** [mdn/content#15875]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code

### What specific section or headline is this issue about?

The first loop example doesn't update when you click the button

### What information was incorrect, unhelpful, or incomplete?

This makes it hard for those looking to refresh their knowledge or relearn JS Loops.

### What did you expect to see?

I expected the loop to make circles

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/looping_code`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/looping_code/index.md
* Last commit: https://github.com/mdn/content/commit/260113d65fa8ea917adc07b100ea5cd593aeb3e0
* Document last modified: 2022-03-25T00:46:44.000Z

</details>

**Comment by wbamberg** [comment]
Weird. I can reproduce this sometimes, never locally, and never when the example iframe is in its own tab: https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/_sample_.looping_code_example.html .

There is definitely something wrong here but I don't have an idea what. @caugner , what do you think?

**Comment by wbamberg** [comment]
Would setting the `defer` or `async` attribute on the script in the bit of Yari that builds the live sample page be a more general (and modern) fix for this?
