### ISSUE TITLE
Stop transcluding live sample sources

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#15872]
The `{{EmbedLiveSample}}` macro has a feature in which you can ask to include sources [not from the current page but from a different page](https://github.com/mdn/yari/blob/730d7adf009a62e6789fe8661bf5ad650716f9b1/kumascript/macros/EmbedLiveSample.ejs#L9).

According to @escattone this along with `{{page}}` was one of the things that made KS much more complicated than it needed to be (because it introduced a build dependency between source and target).

Now we are close to 0 occurrences of `{{page}}` in mdn/content (thanks mostly to @hamishwillee ) it would be nice to remove this other source of complexity.

These are all the pages that make use of this feature of `{{EmbedLiveSample}}`:

- [x] https://developer.mozilla.org/en-us/games/techniques/2d_collision_detection
- [x] https://developer.mozilla.org/en-us/games/techniques/3d_on_the_web/glsl_shaders
- [x] https://developer.mozilla.org/en-us/web/api/datatransferitemlist/remove
- [x] https://developer.mozilla.org/en-us/web/api/dommatrixreadonly/flipx
- [x] https://developer.mozilla.org/en-us/web/api/svgrectelement
- [x] https://developer.mozilla.org/en-us/web/api/document/dragenter_event
- [x] https://developer.mozilla.org/en-us/web/api/document/dragleave_event
- [x] https://developer.mozilla.org/en-us/web/api/document/dragstart_event
- [x] https://developer.mozilla.org/en-us/web/api/document/dragover_event
- [x] https://developer.mozilla.org/en-us/web/api/document/drop_event
- [x] https://developer.mozilla.org/en-us/web/api/document/dragend_event
- [x] https://developer.mozilla.org/en-us/web/api/batterymanager/level
- [x] https://developer.mozilla.org/en-us/web/api/svgcircleelement
- [x] https://developer.mozilla.org/en-us/web/html/global_attributes/itemprop
- [x] https://developer.mozilla.org/en-us/web/html/global_attributes/itemid
- [x] https://developer.mozilla.org/en-us/web/html/global_attributes/itemref
- [x] https://developer.mozilla.org/en-us/web/html/global_attributes/itemtype
- [x] https://developer.mozilla.org/en-us/web/html/global_attributes/itemscope
- [x] https://developer.mozilla.org/en-us/web/html/microdata
- [x] https://developer.mozilla.org/en-us/web/html/element/map
- [x] https://developer.mozilla.org/en-us/web/html/element/video
- [x] https://developer.mozilla.org/en-us/web/css/_colon_-moz-list-bullet
- [x] https://developer.mozilla.org/en-us/web/css/@counter-style/pad
- [x] https://developer.mozilla.org/en-us/web/css/@counter-style/negative
- [x] https://developer.mozilla.org/en-us/web/css/font-variant-ligatures
- [x] https://developer.mozilla.org/en-us/web/css/flex-wrap
- [x] https://developer.mozilla.org/en-us/web/css/font-variant
- [x] https://developer.mozilla.org/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_1
- [x] https://developer.mozilla.org/en-us/web/css/font-variant-alternates
- [x] https://developer.mozilla.org/en-us/web/css/box-orient
- [x] https://developer.mozilla.org/en-us/web/css/flex-grow
- [x] https://developer.mozilla.org/en-us/web/css/font-language-override
- [x] https://developer.mozilla.org/en-us/web/svg/tutorial/basic_transformations
- [x] https://developer.mozilla.org/en-us/learn/forms/your_first_form
- [x] https://developer.mozilla.org/en-us/mdn/kitchensink
- [x] https://developer.mozilla.org/en-us/mdn/contribute/howto/create_an_interactive_exercise_to_help_learning_the_web

**Comment by teoli2003** [comment]
Command used to generate that list: `rg "EmbedLiveSample *\(.*,.*,.*, *'.?'.*\)" -l | wc -l`

**Comment by teoli2003** [comment]
I think this is better: `rg "EmbedLiveSample *\([^,]*,[^,]*,[^,]*,[^,]*, *'[^'][^']*'" -i`

**Comment by hamishwillee** [comment]
Excellent idea. Once we're done, I think we should explicitly prohibit this macro importing from other pages.

**Comment by teoli2003** [comment]
So, most of them were fake transclusions :smile:

**Comment by teoli2003** [comment]
> Excellent idea. Once we're done, I think we should explicitly prohibit this macro importing from other pages.

Given that this macro param is (still) used on mdn/translated-content, we can't just remove the mechanism associated with the parameter.

But maybe we can add a non-failing (à la `mdn.deprecated()`) flaw that would warn us if such a thing is used on mdn/content.

**Comment by OnkarRuikar** [comment]
> But maybe we can add a non-failing (à la `mdn.deprecated()`) flaw that would warn us if such a thing is used on `mdn/content`.

I think if we remove the usage from [the documentation](https://developer.mozilla.org/en-US/docs/MDN/Structures/Live_samples#live_sample_macros) then we won't see new cases. 
Also, contributors will prefer to write a new code instead of looking for existing code that achieves intended output. 🤔

**Comment by teoli2003** [comment]
They can forget a parameter and suddenly there is something in the parameter that will break the system. I've seen numerous typos appearing in the flaw dashboard (and mixing the number of empty parameters is easy), despite the review system. I would prefer to have a security net here given I don't see transclusion going away soon in mdn/translated-content.

**Comment by OnkarRuikar** [comment]
Need to update the list in OP. It shows 6 tasks remaining.

**Comment by OnkarRuikar** [comment]
Looks like transclusion hasn't reached the conclusion 🙃:

- [ ] [Learn/Forms/How_to_build_custom_form_controls](https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls)
- [ ] [Web/API/Canvas_API/Tutorial/Compositing](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Compositing)

The regexes didn't use double quotes.

**Comment by teoli2003** [comment]
Let's reopen this.

**Comment by wbamberg** [comment]
GitHub needs a :sob reaction.

**Comment by Josh-Cena** [comment]
For reference, here's a working regex you could use: `EmbedLiveSample *\((?:[^,]*?,){4} *(['"])[^'"]+\1`

**Comment by Josh-Cena** [comment]
https://github.com/mdn/content/pull/28376 and #27813

**Comment by wbamberg** [comment]
🎉 great work @queengooborg and @cw118 !

**Comment by hamishwillee** [comment]
What he said ^^^^ !!!!
