### ISSUE TITLE
Advance measure of ch glyph "0"

### ISSUE THREAD

**Issue by ecodoc** [mdn/content#15886]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/advance_measure

### What specific section or headline is this issue about?

Advance measure

### What information was incorrect, unhelpful, or incomplete?

"The advance measure is the total space the glyph takes ..." How is "space" measured? Is it measured in pixels? What is the space measure of the glyph "0" in an example font?

### What did you expect to see?

I was trying to estimate the size in pixels of a width of 80ch. Or a way of converting from ch to pixels. I realize the advance measure is dependent on the font family so it would be nice to have a few examples of the width of the glyph in pixels  of a couple of common fonts if that is possible. 

### Do you have any supporting links, references, or citations?

After a brief search, I could not find any reference, link or citation that indicated what the size of a glyph  'space' is in any useful unit. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/advance_measure`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/advance_measure
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/advance_measure/index.md
* Last commit: https://github.com/mdn/content/commit/73f237cb0643ee0c4dadee33b53fd5ec307f1502
* Document last modified: 2022-03-28T16:49:15.000Z

</details>

**Comment by wbamberg** [comment]
I'm not sure there's a sensible answer to this, as it's completely dependent on the typeface and font size. I think really the point of using it is that it's not an absolute length like pixels, but it's font-relative.

> I was trying to estimate the size in pixels of a width of 80ch.

The only answer to this is: it depends on the font.
