### ISSUE TITLE
Update MDN font family page with -apple-system

### ISSUE THREAD

**Issue by obtusedev** [mdn/content#15896]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

### What specific section or headline is this issue about?

Values

### What information was incorrect, unhelpful, or incomplete?

I often see

```css
body {
  font-family: -apple-system, BlinkMacSystemFont;
}
```
However I don't see anything on MDN about `-apple-system` and was curious about it. I'm assuming that's a mac only features but can someone add some information about it?

### What did you expect to see?

Entry on `font-family: -apple-system;`.

### Do you have any supporting links, references, or citations?

www.Github.com uses `-apple-system`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-family`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-family/index.md
* Last commit: https://github.com/mdn/content/commit/8cbdabd8c841ff5dbe46c21d55e4d1fd320661a2
* Document last modified: 2022-04-09T04:51:44.000Z

</details>

**Comment by teoli2003** [comment]
Hi, thanks for the issue!

Are these Apple-only values? Is there some document describing them somewhere?
