### ISSUE TITLE
Duplicates in JS API articles

### ISSUE THREAD

**Issue by bershanskiy** [mdn/content#159]
According to MDN style, JS API article slugs should not contain `()` (only article titles do), but there are articles which do not satisfy this rule. Many of these articles are effectively "dead": they are not linked to from anywhere else on MDN and are essentially undiscoverable. Some of these articles are erroneously created duplicate of other articles with proper slugs.

I'll move any salvageable content from these to the correct articles and then just leave links 

- [ ] [files/en-us/mozilla/add-ons/webextensions/api/menus/menus.overridecontext()](https://github.com/mdn/content/tree/main/files/en-us/mozilla/add-ons/webextensions/api/menus/menus.overridecontext())
       Duplicate of [files/en-us/mozilla/add-ons/webextensions/api/menus/overridecontext](https://github.com/mdn/content/tree/main/files/en-us/mozilla/add-ons/webextensions/api/menus/overridecontext)
- [ ] [files/en-us/mozilla/add-ons/webextensions/api/userscripts/registereduserscript/registereduserscript.unregister()](https://github.com/mdn/content/tree/main/files/en-us/mozilla/add-ons/webextensions/api/userscripts/registereduserscript/registereduserscript.unregister())
       Duplicate of [files/en-us/mozilla/add-ons/webextensions/api/userscripts/registereduserscript/unregister](https://github.com/mdn/content/tree/main/files/en-us/mozilla/add-ons/webextensions/api/userscripts/registereduserscript/unregister)
- [ ] [files/en-us/web/api/dompoint/dompoint.frompoint()](https://github.com/mdn/content/tree/main/files/en-us/web/api/dompoint/dompoint.frompoint())
       Should be moved!
- [ ] [files/en-us/web/api/eventtarget/eventtarget.attachevent()](https://github.com/mdn/content/tree/main/files/en-us/web/api/eventtarget/eventtarget.attachevent())
       Created and then deleted by its author.
- [ ] [files/en-us/web/api/offscreencanvas/offscreencanvas.converttoblob()](https://github.com/mdn/content/tree/main/files/en-us/web/api/offscreencanvas/offscreencanvas.converttoblob())
       Duplicate of [files/en-us/web/api/offscreencanvas/converttoblob](https://github.com/mdn/content/tree/main/files/en-us/web/api/offscreencanvas/converttoblob)
- [ ] [files/en-us/web/api/xmlhttprequest/xmlhttprequest.init()](https://github.com/mdn/content/tree/main/files/en-us/web/api/xmlhttprequest/xmlhttprequest.init())
       A non-standard method not exposed to JS at all, which is documented in the wrong place? Probably, should be moved to at least fix links to it.

Edit: clarified scope of the issue.

**Comment by peterbe** [comment]
http://localhost:3000/en-US/docs/Web/CSS/transform-function/rotateY() works fine. But I can easily get behind a rule that disallows brackets in the slug.

**Comment by peterbe** [comment]
There are lots and lots of these:
```
MOZILLA/MDN/content  main ✔
▶ fd '\(\)' | wc -l
      63

```

**Comment by bershanskiy** [comment]
> But I can easily get behind a rule that disallows brackets in the slug.

I'm not suggesting creation of a new rule here, just fixing the 6 files in the list above. Specifically, moving them or turning them in redirects (deleting them).

I meant only the JS API articles, since there is a formal rule against parentheses in their slugs. I can not find documentation for these rules, but I'm sure these rules exist... because someone more experienced than me told me about these rules in a comment on GitHub...

If such rule exists (I'm starting to question my memory now), it probably doesn't apply to CSS articles. On the contrary, there are valid CSS articles describing CSS functions with `()` in them:
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/fit-content()
Which is different from this:
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/fit-content

**Comment by peterbe** [comment]
Ah!! I get it. Sorry, my brain walked down the wrong aisle. 

Terrible that there are dupes and hopefully someday we can have automation that prevents this from happening. But for now, yes, someone needs to `git rm ...` those dupes and add entries to the `_redirects.txt` for the "winner".

**Comment by bershanskiy** [comment]
> someone needs to git rm ... those dupes and add entries to the _redirects.txt for the "winner".

Yeah, I'll prepare such a PR once `mdn/content` becomes authoritative (December 14, right?).

**Comment by peterbe** [comment]
> once `mdn/content` becomes authoritative (December 14, right?).

That's right! 

What matters is when we shut down the Wiki. We're first putting into read-only mode and then switch the DNS a couple of hours later. And all of this is planned for December 14. It's going to be sweet!

**Comment by Rumyra** [comment]
Hi @bershanskiy did these pages get moved/redirected?

**Comment by sideshowbarker** [comment]
Closing this for lack of response.
