### ISSUE TITLE
Imperfect polyfill for Math.trunc: ~~

### ISSUE THREAD

**Issue by Worldwidebrine** [mdn/content#15919]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc

### What information was incorrect, unhelpful, or incomplete?

Additional Information: imperfect polyfill

### What did you expect to see?

`~~n` can be used as `Math.trunc(n)` in some cases
`~~-1.2 // -1`
`~~3.4 // 3`
But
There are also bugged cases. They should also be mentioned.
`~~2147483648 // -2147483648`
`~~-2147483649 // 2147483647`
> Because it's not 'Math.trunc', it's 'ToInt32' conversion.

Originally posted by zloirock

`~~n` is so easy that one who finds it really could decide to use it.
So I think there should be a tip or something.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/math/trunc`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/trunc/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by zloirock** [comment]
`~~2147483648`

**Comment by Worldwidebrine** [comment]
> `~~2147483648`

But I still don't know understand why it shouldn't be mentioned with this bugged case.
I didn't know until you tould me. Isn't it good to let other readers know?

**Comment by zloirock** [comment]
Because it's not 'Math.trunc', it's 'ToInt32' conversion.

**Comment by Worldwidebrine** [comment]
Thank you
