### ISSUE TITLE
Movement_and_motion: an incomplete sentence

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/content#15938]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion

### What specific section or headline is this issue about?

initBuffers()

### What information was incorrect, unhelpful, or incomplete?

In section https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion#everything_else
The paragraph:
>**initBuffers()**
Initializes the buffers that contain data to be passed into WebGL. These buffers include the array of vertex positions, the array of vertex normals, the texture coordinates for each surface of the cube, and the array of vertex indices (specifying which entry in the vertex list represents each corner of the cube). An object containing references to eard

ends abruptly with an unknown word "eard". 

We may find the rest of the sentence/content in the file's history before migration.

### What did you expect to see?

A complete sentence that adds back the missing info.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webxr_device_api/movement_and_motion`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webxr_device_api/movement_and_motion/index.md
* Last commit: https://github.com/mdn/content/commit/add2ddf0803784cb43fbfb81209d68c7123aebb2
* Document last modified: 2022-05-01T05:08:00.000Z

</details>

**Comment by wbamberg** [comment]
eardrums? eardrops? :)

the earliest copy I can find on archive.org (May 2020, so pre-GitHub) has the same error: https://web.archive.org/web/20200510194418/https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion

**Comment by OnkarRuikar** [comment]
> eardrums? eardrops? :)

I scratched my head for a while but couldn't complete the word. I think it's copy paste gone wrong.
@teoli2003, @hamishwillee any ideas?

Google returns only two locations for this text, first the mdn page and the other is https://udn.realityripple.com/docs/Web/API/WebXR_Device_API/Movement_and_motion (why does this mirror site exist?).

**Comment by teoli2003** [comment]
I think this last sentence is bogus because it was an unfortunate cut & paste. I would remove it.
