### ISSUE TITLE
Men Mozilla Firefox files 

### ISSUE THREAD

**Issue by AriesTriputranto9** [mdn/content#15933]
### MDN URL

https://github.com/mdn/content/commits/main/files/en-us/mdn/contribute/getting_started/index.md

### What specific section or headline is this issue about?

Optional 

### What information was incorrect, unhelpful, or incomplete?

Optional 

### What did you expect to see?

Login data platforms 

### Do you have any supporting links, references, or citations?

wikidata -github 

### Do you have anything more you want to share?

Server 404 error 

### MDN metadata

https://github.com/mdn/content/commits/main/files/en-us/mdn/contribute/getting_started/index.md
[WikidataMap user guide_Export DB or Import XML file - Wikibooks, open books for an open world.PDF](https://github.com/mdn/content/files/8673831/WikidataMap.user.guide_Export.DB.or.Import.XML.file.-.Wikibooks.open.books.for.an.open.world.PDF)
[files-20220202124438.pdf](https://github.com/mdn/content/files/8673832/files-20220202124438.pdf)
[Makefile.txt](https://github.com/mdn/content/files/8673833/Makefile.txt)

**Comment by wbamberg** [comment]
Sorry, I don't understand at all what the issue is here.

**Comment by schalkneethling** [comment]
@AriesTriputranto9 please note that we have dozens of people watching this repository. For every comment posted, these people may receive a notification.

Please be respectful of other people’s time and attention, and avoid taking actions that might cause excessive notifications. Issues should describe a problem or propose an actionable solution. Please use the [MDN Web Docs feedback repository](https://github.com/mdn/feedback/discussions) if a discussion is needed.

Also, please remember that the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) govern all participation in these open spaces. We enforce these to maintain a healthy and inviting community experience for everyone.

To give everyone a moment to reconsider the best way forward, we will lock this issue for 24 hours.
