### ISSUE TITLE
Error values not as described and not useful

### ISSUE THREAD

**Issue by alethiophile** [mdn/content#15965]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download

### What specific section or headline is this issue about?

Return value

### What information was incorrect, unhelpful, or incomplete?

The page says:

> If the download started successfully, the promise will be fulfilled with the id of the new [downloads.DownloadItem](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/DownloadItem). Otherwise, the promise will be rejected with an error message taken from [downloads.InterruptReason](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/InterruptReason).

The object passed to the error handler here is not obviously related to anything in InterruptReason, and is not useful. When I cancel a download, I get an Error object with a `message` attribute saying "Download canceled by the user", and no other information. I would expect this to say "USER_CANCELED", as described on the InterruptReason page.

The message I actually get, while suitable for displaying to the user, is not useful for automatically filtering this type of event (since an English string may be localized, change unpredictably between versions, etc). This is really more of a Firefox bug than a docs bug, but if the docs don't match the behavior that's still wrong.

### What did you expect to see?

Documentation that reflected the behavior my Firefox is displaying

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/downloads/download`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/downloads/download/index.md
* Last commit: https://github.com/mdn/content/commit/17f1582dc23b7d4f6ce017b3939b348ddafc81b0
* Document last modified: 2022-05-03T04:49:07.000Z

</details>

**Comment by mixedpuppy** [comment]
This seems like a bug that should be fixed in Firefox rather than changing documentation.

**Comment by rebloor** [comment]
Raised as [Bug 1771062](https://bugzilla.mozilla.org/show_bug.cgi?id=1771062) Downloads not returning error message from downloads.InterruptReason.

**Comment by rebloor** [comment]
The Bugzilla bug has been given a severity and priority and as the documentation is in line with expected functionality and wouldn't need to be changed once the bug is resolved, closing this issue.
