### ISSUE TITLE
Card layout using flex

### ISSUE THREAD

**Issue by deepug9787** [mdn/content#15997]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox

### What specific section or headline is this issue about?

Card layout pushing footer down

### What information was incorrect, unhelpful, or incomplete?

I find there are two issues with this section:

1. We don’t have to add `flex: 1;` to the content div to push the footer to the bottom of the card. I think a better solution would be to add `justify-content: space-between` to the flex container.

2. The text inside one of the card says:

> I've laid the cards out using grid layout, so the cards themselves will stretch to the same height.

This sentence is a bit misleading because it implies that we _have_ to use grid layout in order for the cards to have the same height, when in fact using flexbox is an equally good (if not better) solution to the problem. Flex items by default have an `align-items` value of `stretch `and will take up the entire height of the cross axis.

### What did you expect to see?

1. Remove `flex:1 1 auto;`  from `.card .content`:
```
.card {
    display: flex;
    flex-direction: column;
}

.card .content {
    flex: 1 1 auto;
}
```
And add `justify-content: space-between` to `.card ` instead:

```
.card {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
}
```

2. Replace the text inside the card:

> I've laid the cards out using grid layout, so the cards themselves will stretch to the same height.

with this:

I've laid the cards out using flex layout, so the cards themselves will stretch to the same height.

Also, replace the grid layout applied to `.cards`:
```
.cards {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px,1fr));
    grid-gap: 10px;
}
```
with this:
```
 .cards {
     display: flex;
     flex-wrap: wrap;
     gap: 10px;
}

.card {
    flex: 0 200px;
}
```

**Comment by victoriacheng15** [comment]
Can I work on this? 

You mentioned to replace the `.card` with CSS grid to flexbox. I read the page, and I don't see any CSS grid for the card. Maybe I missed something here?

```css
.cards {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px,1fr));
    grid-gap: 10px;
}
```

**Comment by OnkarRuikar** [comment]
>I think a better solution would be to add `justify-content: space-between` to the flex container.

If you add a header to the card
```html
    <div class="card">
       <header>Card header</header>
        <div class="content">
            <p>This card doesn't have much content.</p>
        </div>
        <footer>Card footer</footer>
    </div>
```
 `justify-content: space-between` pushes content to the center. Which is not the desired look. 

Also, with your solution the card on the left looks like this if we add color to the content:
![space between](https://i.imgur.com/LSHG9V8.png)
Shouldn't the content be taking most of the space in the card? 
With `flex-grow:1` the content gets most of the space it deserves.

***
> I've laid the cards out using flex layout, so the cards themselves will stretch to the same height.

Using `flex: 0 200px` affects the card width. The card width remains fixed to 200px.

**Comment by OnkarRuikar** [comment]
> Maybe I missed something here?

Refer the source code for the interactive example https://github.com/mdn/css-examples/blob/main/flexbox/use-cases/cards.html#L59

**Comment by deepug9787** [comment]
> If you add a header to the card, `justify-content: space-between` pushes content to the center. Which is not the desired look.

If the card has more than two flex items, we could leave the rest of the items alone and use `margin-top: auto;` on the footer.
```
.card {
         display: flex;
         flex-direction: column;
 }
.card footer {
        margin-top: auto;
}
```
This is the approach used in the [specs](https://www.w3.org/TR/css-flexbox-1/#example-c98d7d3f).

But you’re right, adding a background-color to the content won’t work well with this approach either. So, in the end, setting `flex-grow: 1;` on the content might be a better solution.
