### ISSUE TITLE
JS Array_comprehensions & Generator_comprehensions pages linked from bugzilla.mozilla.org are now 404; should be redirected

### ISSUE THREAD

**Issue by dirkf** [mdn/content#15999]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions

### What information was incorrect, unhelpful, or incomplete?

For instance, in [this BZ issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1220564#c0), there are links to then current MDN pages that are necessary to understand the change that the issue is tracking:

>[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions
>[2] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Generator_comprehensions

However these links now give 404, not just a 404 code but an actual custom 404 page.

### What did you expect to see?

What would have been useful, when updating a third-party script whose author for some xxx reason thought it would be a good idea to use a language feature not in an ES specification, would have been the actual page as it was before it was vandalised into a 404. It can still be read here (and no doubt the page on generator comprehensions too)
https://web.archive.org/web/20200603233105/https://developer.mozilla.org/en-US/docs/Archive/Web/JavaScript/Array_comprehensions. Someone actually decided to spend time changing this.

The linked page(s), when resuscitated from archive.org, very clearly identify the material as historical and could not possibly have confused anyone as to the scope of current Firefox JS support or language standardisation. Why remove it in the first place?

If you are going to 404 such a page, why not redirect it to an archived copy instead?

**Comment by Josh-Cena** [comment]
Where do we redirect those to? I'm tempted to say we should document them _somewhere_ on MDN instead of redirecting to web archive. What about a new subsection under https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features?

**Comment by dirkf** [comment]
My suggestion:
1. leave/restore the pages as they were (before 404);
2. obviously don't link them directly from the current https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference;
3. just link the pages to the existing bullet points under `Legacy Generator` in the Deprecated_and_obsolete_features page that currently have tooltips inviting content!
