### ISSUE TITLE
Remove all links to https://www.fxsitecompat.com/ 

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#160]
**Summary**

It looks like the https://_www_fxsitecompat_com/ domain has now been bought up by spammers. It now shows a bunch of spam ads.

Unfortunately MDN features lots of links to this site, as it used to contain a bunch of valuable information.

Can someone do a search and pull up a list of all pages that link to this URL? I'll then go through and rewrite the pages to remove those links.

**Comment by SphinxKnight** [comment]
duped by https://github.com/mdn/content/issues/7124
