### ISSUE TITLE
Rename Web/HTTP/Basics_of_HTTP/Data_URIs to Web/HTTP/Basics_of_HTTP/Data_URLs

### ISSUE THREAD

**Issue by the-wazz** [mdn/content#16012]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

### What specific section or headline is this issue about?

All over.

### What information was incorrect, unhelpful, or incomplete?

Every link I've seen, and the page itself shows blahblah...Data_UR**I**s, but the page title and headings read Data UR**L**s.

### What did you expect to see?

URI.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/basics_of_http/data_uris`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/data_uris/index.md
* Last commit: https://github.com/mdn/content/commit/0ed90ef0783f8c716e76e78b6b4b92000fb494e2
* Document last modified: 2022-04-26T06:21:16.000Z

</details>

**Comment by wbamberg** [comment]
The first paragraph of this page says:

> They were formerly known as "data URIs" until that name was retired by the WHATWG.

...and the specification also uses "URL": https://datatracker.ietf.org/doc/html/rfc2397.

**Comment by the-wazz** [comment]
I actually did miss that, somehow. 

That aside, that leaves the disparity of the URL of the page itself, which has _https:.../Data_URIs_. I guess a change to _https:.../Data_URLs_ will break a lot of links. Redirect? Closing.

**Comment by wbamberg** [comment]
> I actually did miss that, somehow.
> 
> That aside, that leaves the disparity of the URL of the page itself, which has _https:.../Data_URIs_. I guess a change to _https:.../Data_URLs_ will break a lot of links. Redirect?

Oh yes, good point, I hadn't noticed that.

> 
> Edit: Highlighting the change as a note would also be helpful.
