### ISSUE TITLE
Content suggestion: Mention __proto__ in object literal initializers in the "Inheritance and the prototype chain" tutorial

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#16068]
## What is the new suggestion?

This pattern should be mentioned:

```ts
const obj = { __proto__: null, a: 1 };
```

In addition to the `Object.create` method.

## Why is it important or useful?

It's important to note that while `Object.prototype.__proto__` is deprecated and non-standard, the `__proto__` in literal initializers _is_ standard and probably not any less efficient than `Object.create` [citation needed]. It's important for MDN to highlight the difference between the two.

Slightly off-topic: the [`Object.prototype.__proto__`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto#:~:text=The%20__proto__%20property%20can%20also%20be%20used%20in%20an%20object%20literal%20definition%20to%20set%20the%20object%20%5B%5BPrototype%5D%5D%20on%20creation%2C%20as%20an%20alternative%20to%20Object.create().%20See%3A%20object%20initializer%20/%20literal%20syntax.) documentation mentioned that:

> The `__proto__` property can also be used in an object literal definition to set the object `[[Prototype]]` on creation.

Which can be confusing as well, because `__proto__` in object literals is a special construct, not relevant to `Object.prototype.__proto__`.

I'm open to contributing the two fixes myself, mostly just want to see if anyone has sources on whether `__proto__` in initializers are less/more efficient than `Object.create`.

## Other supporting information

- https://github.com/tc39/ecma262/pull/2125
- https://tc39.es/ecma262/#sec-__proto__-property-names-in-object-initializers

**Comment by sideshowbarker** [comment]
> I'm open to contributing the two fixes myself, mostly just want to see if anyone has sources on whether `__proto__` in initializers are less/more efficient than `Object.create`.

Thanks — I’ve assigned this to you, so please do go ahead and open a PR
