### ISSUE TITLE
Need an example site that actually sends 'Accept-Ranges: none' in responses

### ISSUE THREAD

**Issue by ac2epsilon** [mdn/content#16073]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

### What specific section or headline is this issue about?

curl -I https://www.youtube.com/watch?v=EwTZ2xpQwpA

### What information was incorrect, unhelpful, or incomplete?

Look... 1 curled URL directs to a complex Html page, which has corresponding non-media type 2 and as such has no Accept-Ranges: none 3 and surely not in such transcription 4 because youtube uses all-lowercase for headers. Be careful with easy solutions.

### What did you expect to see?

Something which does not cross an idea of the article

### Do you have anything more you want to share?

I love you guys in a different ways

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/range_requests`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/range_requests/index.md
* Last commit: https://github.com/mdn/content/commit/0872b73731bb333479087e069e0ba94009587fb7
* Document last modified: 2022-04-22T06:07:10.000Z

</details>

**Comment by Rodrigoazeved** [comment]
> ### URL MDN
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
> 
> ### De que seção ou título específico trata este problema?
> curl -I https://www.youtube.com/watch?v=EwTZ2xpQwpA
> 
> ### Quais informações estavam incorretas, inúteis ou incompletas?
> Veja... 1 URL enrolado direciona para uma página HTML complexa, que possui o tipo não-mídia correspondente 2 e, como tal, não possui intervalos de aceitação: nenhum 3 e certamente não em tal transcrição 4 porque o youtube usa todas as letras minúsculas para os cabeçalhos. Tenha cuidado com soluções fáceis.
> 
> ### O que você esperava ver?
> Algo que não cruze uma ideia do artigo
> 
> ### Você tem links de apoio, referências ou citações?
> _Sem resposta_
> 
> ### Você tem mais alguma coisa que queira compartilhar?
> Eu amo vocês de maneiras diferentes
> 
> ### Metadados MDN
> Detalhes do relatório de página

**Comment by teoli2003** [comment]
Youtube changed the headers they sent over the years. 

Do you know of another live URL that we could use instead?

**Comment by bsmth** [comment]
Thanks for reporting. The linked PR fixes this. And some more details: some older browsers relied on `Accept-Ranges: none` to disable the 'pause' and 'resume' buttons in the download manager. Nowadays if responses omit the Accept-Ranges header, it indicates the server doesn't support partial requests, so it's going to be harder to find examples that use this.
