### ISSUE TITLE
Incorrect grammar in code comment

### ISSUE THREAD

**Issue by akaustav** [mdn/content#1608]
Comment reads: `// method does not exists ...`
It should probably read: `// method does not exist ...`

https://github.com/mdn/content/blob/c45665984d990171c7a1b269f0074c34ddfb3d02/files/en-us/web/javascript/reference/operators/optional_chaining/index.html#L208

**Comment by mattiapontonio** [comment]
https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/optional_chaining/index.html
