### ISSUE TITLE
More insight on sparse and dense arrays

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#1610]
Reading this
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#trailing_commas_in_literals

I've learned _sparse_ and _dense_ 👌

> If more than one trailing comma is used, an elision (or hole) is produced. An array with holes is called sparse (a dense array has no holes). When iterating arrays for example with Array.prototype.forEach() or Array.prototype.map(), array holes are skipped.

## Question

- What happens to the `length` if in a sparse Array I push a `undefined`?
- Ditto `null`?

## Expectation

More insight on _sparse_ and _dense_.

**Comment by Ryuno-Ki** [comment]
`[undefined].length` yields 1 (same for `Array(1)`).
In short: those Appending `undefined` or `null` will update the `length` property.

**Comment by mattiapontonio** [comment]
```JavaScript
console.assert([].length==0);
console.assert([undefined].length==1);
console.assert([undefined,].length==1);
console.assert([undefined,,].length==1);
console.assert([undefined,,null,,].length==2);
```

**Comment by mattiapontonio** [comment]
Make sense make 2 Pages?
- /sparse
- /dense

**Comment by Ryuno-Ki** [comment]
I guess, you won't have enough content to justify that.
I'd argue to add more sections to the Array literal page if you feel it needs more explanations (I'm too deep into the language already to make a call here).

**Comment by mattiapontonio** [comment]
Yes 2 headings

## Sparse arrays
An array with holes is called sparse
...
## Dense arrays
A dense array has no holes
