### ISSUE TITLE
Need more documentation  on how exactly private variable is implemented internally in prototype chain

### ISSUE THREAD

**Issue by harshakumar347** [mdn/content#16104]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

### What specific section or headline is this issue about?

No convincing 

### What information was incorrect, unhelpful, or incomplete?

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Details_of_the_Object_Model](link1) according to this article . JavaScript class in ECMAScript 2015, are primarily syntactical sugar over JavaScript's existing prototype-based inheritance and it explains nicely how inhertace and static memeber of class is internally implemented in old java script style . But i can't see any explanation on  how private variable which is new feature  introduced recently is implemented, anywhere in MDN docs execpt that there is cocept of closures and we can implement private method and variables using it  [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures]() can we take that that's how # private variable are implemented . If so please mention that in the first metioned article for clarity or Please give some guidence on how its actually implemented 

### What did you expect to see?

please give complete information on how [Private fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#private_fields) are implemented in prototype chain for better clarity 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/classes/private_class_fields`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/classes/private_class_fields/index.md
* Last commit: https://github.com/mdn/content/commit/76a015ffc44bd29c93e725366ad023171e6c7e7d
* Document last modified: 2022-03-27T18:17:05.000Z

</details>

**Comment by Josh-Cena** [comment]
IMO it's better to understand private fields as weakmaps (i.e. associated metadata). They are even polyfilled as such.

**Comment by harshakumar347** [comment]
@Josh-Cena  you mean like this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#emulating_private_members

**Comment by harshakumar347** [comment]
> Yes—although I don't know why it's mentioned in `let` since AFAICT `const` should work as wellsmile And nothing about private members is mentioned on the `WeakMap` page itself, which is even more surprising.

Thank's
