### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by shellbryson** [mdn/content#16116]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

### What information was incorrect, unhelpful, or incomplete?

Incorrect link to https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hexadecimal_rgb part way through content

### What did you expect to see?

A page

### Do you have any supporting links, references, or citations?

Links to: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hexadecimal_rgb

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/color_value`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/color_value/index.md
* Last commit: https://github.com/mdn/content/commit/ad2a3a261ed0e4b9703213af6982167bc4aaa199
* Document last modified: 2022-04-28T02:18:42.000Z

</details>

**Comment by dimitri-bourreau** [comment]
The part that is refered to is:

<img width="655" alt="Capture d’écran 2022-05-17 à 20 09 04" src="https://user-images.githubusercontent.com/32717624/168881048-99dc87e7-d580-4621-885f-1bafe73129f2.png">

Problem is: the same link is in the bottom compatibility table:

<img width="632" alt="Capture d’écran 2022-05-17 à 20 10 43" src="https://user-images.githubusercontent.com/32717624/168881345-fce91045-4076-499a-a60f-bb9c3c08c3bd.png">

I guess we could update the link to: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb.

--- 

As I am new here, I'd like some help on this:

- Does the link I proposed would be OK?
- How do I update a link in the compatibility table?

Thanks!

**Comment by teoli2003** [comment]
The right page is now: https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color
And to update the BCD, you need to update this file: https://github.com/mdn/browser-compat-data/blob/main/css/types/color.json
 
`rgb()` is a function and is a different beast.

**Comment by wbamberg** [comment]
@teoli2003 , @dimitri-bourreau , is this fixed?

**Comment by teoli2003** [comment]
Yes, it is.
