### ISSUE TITLE
[Support / GitHub] Why sometimes contributors share not main branch?

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#1611]
Sometimes i see links that points to weird branches and the edit button does not work.
I've to switch to main and then edit.
I don't know where this branch _starts_.

See screeshot: `c45...`

![Screenshot_20210122-115734.png](https://user-images.githubusercontent.com/44380480/105483109-9e4ce500-5ca9-11eb-87d6-7fc0336494f3.png)

---
https://github.com/mdn/content/issues/1608

**Comment by Ryuno-Ki** [comment]
`c45665984d` refers to the commit SHA.
You can find others in the [history for the optional chaining operator](https://github.com/mdn/content/commits/main/files/en-us/web/javascript/reference/operators/optional_chaining/index.html) (perhaps after [switching to Desktop view](https://support.mozilla.org/en-US/kb/how-do-i-change-desktop-view-firefox-android))

**Comment by mattiapontonio** [comment]
Ok 👍
