### ISSUE TITLE
Ambiguous paragraph in “Introducing the CSS Cascade” doc

### ISSUE THREAD

**Issue by iamzapata** [mdn/content#16129]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade

### What specific section or headline is this issue about?

The note about !important reversing the precedence of cascade layers

### What information was incorrect, unhelpful, or incomplete?

Note: !important reverses the precedence of cascade layers. For this reason, rather than using !important to override external styles, import frameworks, third party styles, widget stylesheets, etc., into layers, demoting their precedence. !important should only be used sparingly, if ever, to guard required styles against later overrides, in the first declared layer.

### What did you expect to see?

>For this reason, rather than using !important to override external styles, import frameworks, third party styles, widget stylesheets, etc., **(missing something here, group, move, transform, place)** into layers, demoting their precedence.

Not really sure what the best word is to make the paragraph obvious. Right now, this paragraph can lead to several interpretations. 

I think the author intended to say that **third parties** should be grouped/organised using layers, because of the mention of "their precedence", referring to third parties. But for this to be true, this note also implies that the author styles are declared outside a layer so they take precedence.

In my head, this is an example of what the author meant: 

```css
@import url(third-party.css) layer(thirdparty);

p {
  color: red;
}
```

but perhaps the ideal example would be (although this requires a bigger change in the note): 

```css

@layer thirdparty, base;

@import url(third-party.css) layer(thirdparty);

@layer base {
  p {
    color: red;
  }
}
```

Another option is to turn this note into a paragraph and provide a full example of how to set up layers to avoid using !important. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/cascade`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/cascade/index.md
* Last commit: https://github.com/mdn/content/commit/f9861ad43f9b33ca9f1b6a4b1d403be5276763db
* Document last modified: 2022-05-16T17:26:04.000Z

</details>

**Comment by iamzapata** [comment]
@sideshowbarker I'm more than happy to help here with a bit of guidance.

**Comment by sideshowbarker** [comment]
> @sideshowbarker I'm more than happy to help here with a bit of guidance. 

If you can go ahead and write up a PR for it, I'll be happy to review it

**Comment by teoli2003** [comment]
@estelle Quick question. I think the cascade docs have been extensively rewritten. Is this issue still open?

**Comment by estelle** [comment]
> @estelle Quick question. I think the cascade docs have been extensively rewritten. Is this issue still open?

This note was in the new (now not so new) documentation.

**Comment by estelle** [comment]
I think the note is clear as is. Would adding "earlier defined" make it clearer for you?

> For this reason, rather than using !important to override external styles, import frameworks, third party styles, widget stylesheets, etc., into **earlier defined** layers, demoting their precedence.
