### ISSUE TITLE
Disable window.sidebar by default

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#16149]
Disable window.sidebar by default - should be check docs, bcd & rel note

## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1768486

**Comment by hamishwillee** [comment]
This puts [`Window.sidebar`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sidebar), an alias of [`Window.external`](https://developer.mozilla.org/en-US/docs/Web/API/Window/external), behind a preference.

Status

- [ ] Docs
- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/16375
- [ ] Release notes
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
Again jumping to assume bcd will go through and closing
