### ISSUE TITLE
[CSS] Implement `update` media query

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#16148]
## Acceptance Criteria

- [X] The listed features are documented sufficiently on MDN
       - [X] `update` [doc page](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/update-frequency) exists
       - [X] `update` mentioned in [Using media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) and [@media](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#media_features) pages
- [X] BCD is updated: https://github.com/mdn/browser-compat-data/pull/16472
- [ ] Interactive example and data repos are updated if appropriate - NA
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [X] Add entry to Firefox release notes if feature is enabled in release: https://github.com/mdn/content/pull/17270
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release - NA

## Features to document

`update` for media query - see https://drafts.csswg.org/mediaqueries-4/#descdef-media-update

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1422312

**Comment by dipikabh** [comment]
Hi @rachelandrew, thanks for the BCD table update for the `update` media query feature! 

I noticed that the [update](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/update-frequency) feature page also is documented.

The page slug is currently https://developer.mozilla.org/en-US/docs/Web/CSS/@media/update-frequency. I wanted to check with you if there was a specific reason to name the slug 'update-frequency'.

Would it be okay if I rename it (move the page) to 'update' to keep it consistent with other page slugs/naming conventions? I checked and didn't see any other directories named 'update'.
