### ISSUE TITLE
[WebAPI] Remove mozGetAsFile

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#16152]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Get rid of HTMLCanvasElement::mozGetAsFile - this was 'removed' (put behind a flag) in 74, it has now been deleted across desktop & mobile. We can delete this page https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/mozGetAsFile and also the reference here https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement#obsolete_methods

FYI I don't think a release note is needed because it's depreciation would have been captured in 74

@queengooborg should this be removed from bcd or wait for the two years?

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1619574

**Comment by queengooborg** [comment]
For the BCD side, I think that if it was put behind a flag back in 74, then that'll qualify for the two year mark, so we can remove the BCD entry as well!

**Comment by dimitri-bourreau** [comment]
Hi!

Sorry I'm new around here, is there anyway I could help you as a newbie here?

Removing what @Rumyra refers to seems easy to me (already done it actually). Is it something you want?

Thanks!

**Comment by hamishwillee** [comment]
Hi @dimitri-bourreau 
Thanks - help is always welcome. If you've done those fixes then can you please create a link back to this issue so that the completion status is easy to track?

**Comment by dimitri-bourreau** [comment]
Done. 😊

**Comment by hamishwillee** [comment]
Status update:

- [ ] Docs
  - [ ] https://github.com/mdn/content/pull/16178
  - [ ] Completeness checks
- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/16372
- [ ] Release notes
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
Thanks @dimitri-bourreau and @hamishwillee :)

I'm going to close this assuming bcd will go through 👍

**Comment by hamishwillee** [comment]
Reopening - too early. If I haven't checkedo every box in the status update post then I probably need to do a final review.

**Comment by hamishwillee** [comment]
Done now (just dev-doc-complete) and a removed a few spurious links to this in https://github.com/mdn/content/pull/16577
