### ISSUE TITLE
Formdata constructor doesn't include form argument

### ISSUE THREAD

**Issue by criesbeck** [mdn/content#16159]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FormData

### What specific section or headline is this issue about?

Constructor

### What information was incorrect, unhelpful, or incomplete?

Only the nulladic FormData constructor is shown. 

### What did you expect to see?

Two contructor options: nulladic and new FormData(formElement)

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects#retrieving_a_formdata_object_from_an_html_form

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/formdata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FormData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/formdata/index.md
* Last commit: https://github.com/mdn/content/commit/1818709a1163361f6fef6c8b1e2cc1eb3a704e4b
* Document last modified: 2022-04-30T03:12:54.000Z

</details>

**Comment by teoli2003** [comment]
@criesbeck : We just merged the missing constructor syntax. Is this what you were expecting or is there more to add?

**Comment by criesbeck** [comment]
Exactly. Thanks so much. That should help others not miss that option as I did when looking for a way to get from form to useful object.
