### ISSUE TITLE
[WebAPI] Implement Import Maps

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#16150]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

This is an experimental feature, but will still need documenting, so best to get ahead.

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1688879

- https://bugzilla.mozilla.org/show_bug.cgi?id=1795647 - shipping in 108!

**Comment by hamishwillee** [comment]
@Rumyra Looking at the recent discussions on this and the code it looks like:
1. Spec https://wicg.github.io/import-maps/ and here https://github.com/WICG/import-maps#readme
1. This is [behind a pref](https://hg.mozilla.org/mozilla-central/rev/0bde7359a1c9#l3.12) `dom.importMaps.enabled` and disabled by default for FF102
1. The spec is not really standardised. According to the thread there is a lot of churn.
1. External import maps not yet supported: https://github.com/WICG/import-maps/issues/235

So this probably isn't something for 102. I'm also not certain I am sufficiently expert. 
Suggest we ask dev team when they think it might be stable enough to document, park this until then, and in the meantime see if we can seek help for documenting. Thoughts?

**Comment by Rumyra** [comment]
Yeh that sounds like a good plan @hamishwillee - I'll come back and revisit this issue when I check the release project next week 👍

**Comment by Rumyra** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1775424 related - still seems early days tho so I'm going to put this in the backlog for now (just as there are lots of issues for 103 which take higher priority)

**Comment by Josh-Cena** [comment]
Question: since this is a web feature instead of a JS feature (the ECMA spec does not specify how module specifiers should be resolved; it's entirely host-specific), should this be triaged as a web API documentation instead?

**Comment by teoli2003** [comment]
Label fixed: https://wicg.github.io/import-maps/ It is indeed not part of the language itself.

**Comment by hamishwillee** [comment]
I'm not entirely sure how to structure this yet. The feature is implemented using an inline script element with `type="importmap"` so it is relatively easy to understand where compatibility information should go.

However there really isn't enough space under the script element under the [`type` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-type) to capture a faction of the nuances/use cases here. I think I'll probably need to have an "HTML script import map page" or "Script importing in HTML" page. That will be useful in any case for linking from docs like JavaScript modules to show the specific differences in browser environments.

Advice welcome.

**Comment by hamishwillee** [comment]
Status:
- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/18214
- [ ] Docs
- [ ] Release note
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
So giving a brief overview - yes I think we should have something of a guide on import maps. The JS module guide does include stuff about `<script>` and as guides simply can not abide by one technology that might be a relevant place (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) 

However this guide is _very_ long 🤔 - I can catch up with you about this when you've also given it some thought @hamishwillee :)

**Comment by hamishwillee** [comment]
All done bar the reviews - we've iterated once so I think fairly close now. I'll move to done but there might be some final tidy up.

**Comment by hamishwillee** [comment]
Phew! All done.

**Comment by Rumyra** [comment]
Phew for you! Thanks @hamishwillee

**Comment by hamishwillee** [comment]
Too right!
