### ISSUE TITLE
[page types] Define page types for JavaScript

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#16156]
Part of https://github.com/mdn/content/issues/15539.

In https://docs.google.com/spreadsheets/d/14RX8EEKPpeYkP2cF5Y_ZKF3JpNJ_24OL7stvZWNJLIY/edit#gid=2083448819, in the "JavaScript" tab, I've listed every page under https://developer.mozilla.org/en-US/docs/Web/JavaScript and made an initial determination about the page type.

I've tried to err towards too many page types than too few, since it's easy to amalgamate them but harder to divide them.

I've come up with 15 types:

```
guide                       50
JS class                    68
JS constructor              61
JS error                    76
JS function                 19
JS global property           3
JS instance method         308
JS instance property        57
JS keyword                   3
JS namespace                 2
JS operator                 70
JS statement                28
JS static method           125
JS static property          49
landing page                 4
```

...plus several pages that I wasn't able to categorize yet:

[javascript/reference/template_literals](https://developer.mozilla.org/en-US/docs/web/javascript/reference/template_literals)
[javascript/reference/classes/private_class_fields](https://developer.mozilla.org/en-US/docs/web/javascript/reference/classes/private_class_fields)
[javascript/reference/classes/public_class_fields](https://developer.mozilla.org/en-US/docs/web/javascript/reference/classes/public_class_fields)
[javascript/reference/classes/class_static_initialization_blocks](https://developer.mozilla.org/en-US/docs/web/javascript/reference/classes/class_static_initialization_blocks)
[javascript/reference/global_objects/generatorfunction](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/generatorfunction)
[javascript/reference/functions/default_parameters](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/default_parameters)
[javascript/reference/functions/rest_parameters](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/rest_parameters)
[javascript/reference/functions/arrow_functions](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/arrow_functions)
[javascript/reference/functions/get](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/get)
[javascript/reference/functions/method_definitions](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/method_definitions)
[javascript/reference/functions](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions)
[javascript/reference/functions/set](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/set)
[javascript/reference/functions/arguments/callee](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/arguments/callee)
[javascript/reference/functions/arguments/length](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/arguments/length)
[javascript/reference/functions/arguments/@@iterator](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/arguments/@@iterator)
[javascript/reference/functions/arguments](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/arguments)
[javascript/reference/trailing_commas](https://developer.mozilla.org/en-US/docs/web/javascript/reference/trailing_commas)

I would love some ideas for what to do about these.

I had a few more questions and things that might be worth discussing.

## JS statements, expressions, operators, keywords

These are a bit murky.

For the most part I just assigned types to parallel the directory structure, so pages under javascript/reference/operators/ got assigned "JS operator" and pages under javascript/reference/statements/ got assigned "JS statement". This doesn't seem quite right though, since "javascript/reference/operators/" includes expressions and operators. Should we distinguish these pages types, although they're not distinguished in the current IA? If not, what should we call the type, "JS operator" is obviously wrong.

We also have a few "JS keyword" types - how really are these distinct from "JS statement"?

## JS methods, functions, namespaces, and classes

I have static and instance methods, which are functions that are attached to classes. That seems reasonable. I also have "JS functions" which I'm mostly using for global functions, like [`decodeuricomponent()`](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/decodeuricomponent). That also sounds kind of plausible.

I also have "JS namespace" as well as "JS class". I'm using this only for `Intl` and `WebAssembly` at the moment. I guess these are defined by:
1. not having a constructor of their own 
2. containing scoped constructors for other objects

On the other hand I have called `Math` a class, even though it doesn't have a constructor. But `Math` doesn't contain any constructors for other objects, it's just a collection of static methods and properties. Should `Math` be a namespace too, so the distinction is just whether they have a constructor?

Relatedly I'm treating functions in namespaces, like say [`WebAssembly.compile()`](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/webassembly/compile) as "JS function" types, rather than static methods.

## JS global property

I have three "JS global property" pages:
- [`nan`](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/nan)
- [`this`](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/globalthis)
- [`Infinity`](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/infinity)

I'm not very happy with these but am not sure what else to do about them.

**Comment by wbamberg** [comment]
I asked @Josh-Cena for opinions about this categorization, and he responded here: https://github.com/mdn/content/pull/17547#issuecomment-1163799532.

> ## JS statements, expressions, operators, keywords
> 
> These are a bit murky.
> 
> For the most part I just assigned types to parallel the directory structure, so pages under javascript/reference/operators/ got assigned "JS operator" and pages under javascript/reference/statements/ got assigned "JS statement". This doesn't seem quite right though, since "javascript/reference/operators/" includes expressions and operators. Should we distinguish these pages types, although they're not distinguished in the current IA? If not, what should we call the type, "JS operator" is obviously wrong.

From his response I'm tempted to resolve this issue by having:

* "JS expressions" (`javascript-expression`) to cover everything under https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators, 
* "JS statements" (`javascript-statement`) to cover everything under https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements

**Comment by Josh-Cena** [comment]
@wbamberg For JS docs, I'd like to distinguish between "instance accessor property" and "instance data property", because they have different data descriptors and accessor properties are more likely to be read-only. WDYT?

**Comment by wbamberg** [comment]
> @wbamberg For JS docs, I'd like to distinguish between "instance accessor property" and "instance data property", because they have different data descriptors and accessor properties are more likely to be read-only. WDYT?

So I don't think I understand this difference well enough to know whether I am in favour, but I can outline what I think should be considerations here.

I think how we split up technology areas into page types is going to be a judgement call and we should make whatever choices serve us best. Considerations include:
- we don't want to have too many page types because it adds complexity. We have ~15 for each of Web/API and CSS, so I would be OK with something like that for JavaScript. I would be happy with fewer :)
- we especially want page types where they capture structural differences between pages. For example, although in many ways we might want to treat "CSS shorthand properties" and "CSS properties" in the same way (in sidebars, for instance, we would probably group them together) we want shorthand properties _always_ to have this "Constituent properties" section, and that makes a separate page type worth having. It means, for instance, that we could imagine a future where we drive linting of pages (or even construction of pages) from a template selected by a page type.
- we probably want page types to distinguish between items that will appear in different bits of a sidebar
- there's a certain "paving cowpaths" thing here. If we routinely talk about pages as documenting "different kinds of thing", and/or want to treat them differently in some way, then there is probably a page type in there trying to get out. One way to think about this project is to formalize and make sharp distinctions which we already make in a relatively informal way. So they're tools we can use to organize the docs, not Platonic truths.

I'm not sure "more likely to be read-only" is on the face of it a good argument. If it was "are always read-only" it might be a different matter.

**Comment by Josh-Cena** [comment]
The way that accessor properties fundamentally differ from data properties is that accessors are defined on the prototype, not on each instance (most data properties are on instances). This means:

1. Page titles (See also #21789). For example, if `length` is an accessor property of `Array`, then we can regretlessly write `Array.prototype.length`; but if it's an own property of each array instance, the only correct way to denote it is `Array: length` or `Array length`.
2. Still page titles. We have some pages (namely, the `@@species` pages) that explicitly include `get` in the page title. IMO, that's a better convention, and is consistent with the spec. I'm not sure I can successfully push it through, given the backlash I've faced in https://github.com/mdn/content/pull/19540, but at least it remains a possibility.
3. Intro paragraph. The intro paragraphs of these properties already make a distinction by saying "the `flags` accessor property..." or "the `length` (data) property..." Having page types, IIUC, helps us consolidate it as a rule and automatically check for consistency in the future.
4. Property descriptor. This one is related to https://github.com/mdn/content/pull/22337. We only have these tables for data properties, because only they have the `writable` attribute. If we want to make use of page types to make sure the tables are consistently present and in the right place, it's better if we can distinguish which pages need them.
5. Accessor properties often have the sentence "the setter of this property is `undefined`; you cannot change this property directly". It's good if we can make that consistent as well. At least we should make sure the description talks about both the getter and the setter.

**Comment by Josh-Cena** [comment]
For the following:

- [javascript/reference/template_literals](https://developer.mozilla.org/en-US/docs/web/javascript/reference/template_literals)
- [javascript/reference/trailing_commas](https://developer.mozilla.org/en-US/docs/web/javascript/reference/trailing_commas)
- [javascript/reference/functions/arrow_functions](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/arrow_functions)
- [javascript/reference/functions/default_parameters](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/default_parameters)
- [javascript/reference/functions/get](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/get)
- [javascript/reference/functions/method_definitions](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/method_definitions)
- [javascript/reference/functions/rest_parameters](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/rest_parameters)
- [javascript/reference/functions/set](https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/set)
- [javascript/reference/classes/private_class_fields](https://developer.mozilla.org/en-US/docs/web/javascript/reference/classes/private_class_fields)
- [javascript/reference/classes/public_class_fields](https://developer.mozilla.org/en-US/docs/web/javascript/reference/classes/public_class_fields)
- [javascript/reference/classes/static_initialization_blocks](https://developer.mozilla.org/en-US/docs/web/javascript/reference/classes/static_initialization_blocks)

I feel like the best categorization is "JS syntax", but that may be too handwavy. No better names to suggest.

**Comment by Josh-Cena** [comment]
I'm not sure what "a static function under a namespace" should be called. In [javascript/reference/global_objects/intl/getcanonicallocales](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/intl/getcanonicallocales), we called it "JS function"; but in [javascript/reference/global_objects/math/abs](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/math/abs), we called it "JS static method". I like "JS function" better, because methods only make sense on classes, but I'm not sure if we want to differentiate between "global function" and "namespaced function".

**Comment by wbamberg** [comment]
In line with your https://github.com/mdn/content/issues/16156#issuecomment-1325967089, I updated the [spreadsheet](https://docs.google.com/spreadsheets/d/14RX8EEKPpeYkP2cF5Y_ZKF3JpNJ_24OL7stvZWNJLIY/edit#gid=1971125626) to add "JS language feature" next to the ones you listed (and replaced "JS keyword" with that too). I agree that "JS language feature" is handwavy but I think it is the best we can do. Note that there are still a few with "?" next to them, are they also "JS language feature"?

I'm happy with your reasoning for distinguishing data properties and accessor properties. Can we call them "JS data instance property" and "JS instance accessor property"? If so please add them to the sheet.

We should consider [the comment about expressions and operators](https://github.com/mdn/content/issues/16156#issuecomment-1165948404) - at the moment I have "JS operator" for everything under https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators but perhaps "JS expression" would be better?

About your comment ["I'm not sure what "a static function under a namespace" should be called"](https://github.com/mdn/content/issues/16156#issuecomment-1325969033) - this is related to my question in the original comment at "JS methods, functions, namespaces, and classes". Currently in the sheet I'm calling functions on namespaces "JS function" rather than "JS method", on the grounds as you say that only classes have methods. But note that we do call them "methods" for example in https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/intl/getcanonicallocales.

But also I am treating `Math` as a class - as our docs currently do, and as we also do for `Atomics` and `JSON`, say. But as I asked, should we call `Math` a namespace? That is, is the rule basically: if it's not instantiable, it's a namespace?

Actually, things like `Math` and `JSON` and `Atomics` fit perfectly well into our current model as "classes with only static methods". The problem is with things like `Intl` that are a namespace for constructors, because we have nowhere to put objects like `Collator` that don't have global constructors.

re: "I'm not sure if we want to differentiate between "global function" and "namespaced function"." I'm tempted to say we should try not differentiating, and see how that goes.

**Comment by Josh-Cena** [comment]
> I'm happy with your reasoning for distinguishing data properties and accessor properties. Can we call them "JS data instance property" and "JS instance accessor property"? If so please add them to the sheet.

Done. I've split both static and instance properties—we have 10 types now, which seems fine.

About namespaces vs. classes. I'm fine with _properties_ of these namespaces being counted as properties/methods, but `Math`, `JSON`, `Atomics`, `Reflect`, and `Intl` should definitely all be called "namespace". The reason is that they are ordinary objects—if it's a class, then `typeof JSON` should return `"function"`. This means we will have "JS namespace", whose subpages are always "JS static data property" or "JS static method", but never "JS function". Does that sound good?

**Comment by Josh-Cena** [comment]
The sheet looks in good shape to me now! I agree with everything under "JS language features"—basically all the special syntaxes (mostly expressions) that do not qualify as "operators". I think this is good to go.

**Comment by wbamberg** [comment]
This gives us the following list of types:

```
JS class
JS constructor
JS error
JS global property
JS instance accessor property
JS instance data property
JS instance method
JS language feature
JS namespace
JS operator
JS statement
JS static accessor property
JS static data property
JS static method
```

**Comment by Josh-Cena** [comment]
LGTM

**Comment by Josh-Cena** [comment]
@wbamberg If we have agreement on this, can we start making changes? Or should we wait for some more time?

**Comment by wbamberg** [comment]
This is done. Thanks @Josh-Cena !
