### ISSUE TITLE
<blink> - Link does not exist

### ISSUE THREAD

**Issue by Wyatt-Stanke** [mdn/content#16164]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blink

### What specific section or headline is this issue about?

See also

### What information was incorrect, unhelpful, or incomplete?

The first link--[this one](https://www.montulli.org/theoriginofthe%3Cblink%3Etag/)--is broken.
I did find an archive link [here](https://web.archive.org/web/20220331020029/http://www.montulli.org/theoriginofthe%3Cblink%3Etag).

### What did you expect to see?

A not broken link.

### Do you have any supporting links, references, or citations?

![image](https://user-images.githubusercontent.com/47758296/168935067-9c14f301-0022-484c-b95c-a788bcff7268.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/blink`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blink
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/blink/index.md
* Last commit: https://github.com/mdn/content/commit/ba8194486e3e267c52e0abd9b9b5c3aa78262f25
* Document last modified: 2022-05-13T05:22:00.000Z

</details>

**Comment by OrToR-KJM** [comment]
🥼

2022년 5월 18일 (수) 09:53, Wyatt Stanke ***@***.***>님이 작성:

**Comment by PrajwalBorkar** [comment]
I can work on this issue. Can u give the updated link?

**Comment by teoli2003** [comment]
Sure: https://web.archive.org/web/20220331020029/http://www.montulli.org/theoriginofthe%3Cblink%3Etag

The issue is yours.
