### ISSUE TITLE
References Web Authentication API Figure 2, step 4 consistency.

### ISSUE THREAD

**Issue by 11301627** [mdn/content#16185]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API

### What specific section or headline is this issue about?

Figure 2, step 4

### What information was incorrect, unhelpful, or incomplete?

In figure 2 at step 4, the figure states that the Authenticator sends "authenticatorData signature". At step 5 the same is send plus clientDataJSON. This is written as "clientDataJSON, authenticatorData, signature". The comma is missing which could suggest "authenticatorData signature" is one thing. 

### What did you expect to see?

In figure 2 at step 4 "authenticatorData, signature"

### Do you have any supporting links, references, or citations?

![mdn_webauthn_authentication_(r1)](https://user-images.githubusercontent.com/31687791/169023114-3aafc6e2-4722-4d73-8132-30fa1679d08f.png)

### Do you have anything more you want to share?

This is a minor issue with consistency in the figure.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_authentication_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_authentication_api/index.md
* Last commit: https://github.com/mdn/content/commit/26dfff8efecc1a4a4cef80c54b2d2f203f0b1695
* Document last modified: 2022-05-11T21:15:28.000Z

</details>

**Comment by OrToR-KJM** [comment]
내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: 11301627 ***@***.***> 날짜: 22/5/18  20:00  (GMT+09:00) 받은 사람: mdn/content ***@***.***> 참조: Subscribed ***@***.***> 제목: [mdn/content] References Web Authentication API Figure 2, step 4 consistency. (Issue #16185) 
MDN URL
https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API
What specific section or headline is this issue about?
Figure 2, step 4
What information was incorrect, unhelpful, or incomplete?
In figure 2 at step 4, the figure states that the Authenticator sends "authenticatorData signature". At step 5 the same is send plus clientDataJSON. This is written as "clientDataJSON, authenticatorData, signature". The comma is missing which could suggest "authenticatorData signature" is one thing.
What did you expect to see?
In figure 2 at step 4 "authenticatorData, signature"
Do you have any supporting links, references, or citations?

Do you have anything more you want to share?
This is a minor issue with consistency in the figure.
MDN metadata


Page report details

Folder: en-us/web/api/web_authentication_api
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API
GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_authentication_api/index.md
Last commit: 26dfff8
Document last modified: 2022-05-11T21:15:28.000Z

**Comment by OrToR-KJM** [comment]
2022년 5월 18일 (수) 20:04, m030142 ***@***.***>님이 작성:
