### ISSUE TITLE
Certificate expired for test262.report domain

### ISSUE THREAD

**Issue by jasonmobley** [mdn/content#1619]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

#### What information was incorrect, unhelpful, or incomplete?
Implementation Progress section is not shown because the SSL certificate is expired as of yesterday.

#### Specific section or headline?
Implementation Progress

#### What did you expect to see?
The table of browser implementation status

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/nullish_coalescing_operator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/operators/nullish_coalescing_operator/index.html
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by jasonmobley** [comment]
<img width="1045" alt="Screen Shot 2021-01-22 at 9 37 57 AM" src="https://user-images.githubusercontent.com/645028/105504480-cfbbb580-5c95-11eb-9859-5e685dea0f48.png">

**Comment by jasonmobley** [comment]
<img width="1002" alt="Screen Shot 2021-01-22 at 9 41 23 AM" src="https://user-images.githubusercontent.com/645028/105504642-009bea80-5c96-11eb-9185-11e72e85c64b.png">

**Comment by Ryuno-Ki** [comment]
@leobalter @rwaldron maintain https://github.com/tc39/test262

**Comment by leobalter** [comment]
Test262.report is a project maintained by Bocoup and I don't have access to its code or maintenance since Jan 2020. 

I recommend you use the project's issue tracker: https://github.com/bocoup/test262-report-issue-tracker

**Comment by rwaldron** [comment]
I don't have access to address this.

**Comment by rwaldron** [comment]
@jugglinmike

**Comment by jugglinmike** [comment]
It looks like an automated system failed on our (Bocoup's) end. I've manually intervened, and with the immediate problem resolved, I'll see to fixing the automation during more normal working hours.

**Comment by Ryuno-Ki** [comment]
It's back online:

![test262](https://user-images.githubusercontent.com/3097194/105626552-ac793d80-5e30-11eb-8550-0ae36d7592e7.png)

Thanks for the fix @leobalter @rwaldron @jugglinmike 

Thanks for the report @jasonmobley
