### ISSUE TITLE
@import url("narrow.css") supports(display: flex) example not working

### ISSUE THREAD

**Issue by SYwaves** [mdn/content#16198]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@import

### What specific section or headline is this issue about?

Importing CSS rules conditionally

### What information was incorrect, unhelpful, or incomplete?

"@import rule will load the narrow.css stylesheet if the user agent supports [display: flex]"

### What did you expect to see?

I can not seem to get the supports() conditional to work in @import. All the other media queries function as normal, but fails to take effect when supports() is added.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@import`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@import
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@import/index.md
* Last commit: https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e
* Document last modified: 2022-05-17T13:23:31.000Z

</details>

**Comment by SYwaves** [comment]
On further inspection, this appears to be unimplemented in any current specifications.

**Comment by Josh-Cena** [comment]
The docs were removed in #23761 and then re-added in #26917. @hamishwillee Do you think we should add experimental badges to the `_supports-condition_` parameter?
