### ISSUE TITLE
CSS positioning should include `transform`

### ISSUE THREAD

**Issue by mholt** [mdn/content#16203]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning

### What information was incorrect, unhelpful, or incomplete?

The list of properties affecting position should include `transform`.

An element that includes `transform` becomes the offset parent to its children.

### What did you expect to see?

A link to `transform` under "CSS Properties"

### Do you have any supporting links, references, or citations?

https://jsfiddle.net/g0ske8rq/

The Firefox inspector will prove that the offset parent is the element with `transform`, not `position`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_positioning`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_positioning/index.md
* Last commit: https://github.com/mdn/content/commit/d7791268eabae921e32eedcbc3a6b6606504a1f0
* Document last modified: 2022-02-22T07:32:00.000Z

</details>

**Comment by OnkarRuikar** [comment]
We need to include `inset-block-start`, `inset-block-end`, `inset-inline-start`, and `inset-inline-end` also.
