### ISSUE TITLE
CSP Style Attribute

### ISSUE THREAD

**Issue by ajay-ally** [mdn/content#16213]
### Discussed in https://github.com/mdn/content/discussions/16175

<div type='discussions-op-text'>

<sup>Originally posted by **ajay-ally** May 18, 2022</sup>
I'm using nonce for styles where style tags are getting blocked but not the style attribute. I'm getting the CSP error in the console for the style attribute but the style is getting applied for the element. Can anyone please help me resolving this issue.

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' localhost:3000 unsafe-hashes 'report-sample' 'nonce-7LV1f57teStNOnc3tYd44w=='". Either the 'unsafe-inline' keyword, a hash ('sha256-8f935d27GvUutRyY9yWScUMiFUk4WTdZURISiYfPOeQ='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.</div>

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing, problems in the MDN documentation.

It looks like you are looking for help with your code. Unfortunately, we don't have enough availability to help you.

May I suggest asking your question on a specialized website, like StackOverflow?

I'm closing this issue. If I've misunderstood you and you were actually reporting a problem in the documentation, feel free to reopen it, while providing more information so we can understand the problem.

Thanks for your interest.
