### ISSUE TITLE
 after the Event.initEvent() abandoned

### ISSUE THREAD

**Issue by leixhao** [mdn/content#16211]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent

### What specific section or headline is this issue about?

Event.initEvent()

### What information was incorrect, unhelpful, or incomplete?

no

### What did you expect to see?

After Event.initEvent() was abandoned, is there any API to replace it
and or
eg

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/event/initevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/event/initevent/index.md
* Last commit: https://github.com/mdn/content/commit/6825e0885de4c1c3877b1ce9b80e1f920215eacf
* Document last modified: 2022-01-18T22:56:08.000Z

</details>

**Comment by teoli2003** [comment]
From this very same page:
![Capture d’écran 2022-05-19 à 06 29 07](https://user-images.githubusercontent.com/1466293/169205200-7159c382-7ac2-401c-bd49-f995f319fc30.png)


More generally, all `initXYZ` have been deprecated 15 years ago and replaced by constructors. Note that for events, you likely don't want to use the `Event` constructor but the one for the actual `Event` interface you want to use (Like `FocusEvent`)

**Comment by leixhao** [comment]
Of course i saw it,but it not what i need.
I want to implement a function that simulates clicking, which must be initialized with ’initevent()‘
But I didn't find a replacement api on that page

**Comment by leixhao** [comment]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/31658015/169218272-b5d0472d-6064-4d04-9e1a-724deacc6ccd.png">

**Comment by teoli2003** [comment]
Click events are of type `MouseEvent` so you create your synthetic click event using `new MouseEvent("click", options)`.

**Comment by teoli2003** [comment]
Note that synthetic UI events are limited for security reasons:
![Capture d’écran 2022-05-19 à 07 42 23](https://user-images.githubusercontent.com/1466293/169218650-1833e96b-dac0-47c3-a586-21e7f73917b5.png)

**Comment by leixhao** [comment]
Sorry. What I want to achieve is a simulated key effect. I use code to realize the key of the keyboard, not clicking. Clicking is just its trigger. I think any other event can be used to trigger this simulated keyboard key event

I can operate the creation and monitoring of keyboard or click events, but what I want to achieve is that the keyboard automatically presses keys, rather than trigger what to do after pressing keys Oh, brother, do you understand what I mean

I need initevent() to initialize the Keydown objectand then automatically dispatch it, but now the init API in all Event,ketboardEvent(), functions is inherited from Event(), and the init in event is about to be discarded

**Comment by teoli2003** [comment]
To create a `keydown` event, you should use the `ev = new KeyboardEvent("keydown", options)` constructor: see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent

Then you dispatch `ev` to the relevant element on the page. (The warning about synthetic events still applies.)
