### ISSUE TITLE
Browsers aren't split between desktop and mobile in support table

### ISSUE THREAD

**Issue by Sora2455** [mdn/content#16212]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

### What specific section or headline is this issue about?

Browser support table

### What information was incorrect, unhelpful, or incomplete?

The header of the support table implies that it is divided into desktop and mobile browsers, when in fact the browsers are displayed in alphabetical order.

![image](https://user-images.githubusercontent.com/8307112/169206762-662ed23a-a4e0-4202-a33d-2cb42457d48d.png)

### What did you expect to see?

The browsers split by desktop and mobile.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/frame-ancestors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/frame-ancestors/index.md
* Last commit: https://github.com/mdn/content/commit/7aeab872cca09c731b81832f1f497437f1d76e4e
* Document last modified: 2022-05-15T18:35:00.000Z

</details>

**Comment by teoli2003** [comment]
cc/ @schalkneethling

**Comment by teoli2003** [comment]
This is a duplicate of mdn/yari#6314. Closing in favour of that issue.
