### ISSUE TITLE
Missing CanvasRenderingContext2D / CanvasState .reset()

### ISSUE THREAD

**Issue by HolgerJeromin** [mdn/content#16227]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D

### What information was incorrect, unhelpful, or incomplete?

I just learned from chrome blog post about this API:

https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-reset

### What did you expect to see?

Some information with proper browser support... (probably needs a change to bcd as well)

### Do you have any supporting links, references, or citations?

ref https://developer.chrome.com/blog/canvas2d/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/index.md
* Last commit: https://github.com/mdn/content/commit/60c663bfc41646473dc4390b34795f3804d883ef
* Document last modified: 2022-04-24T02:34:11.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed via #19859
