### ISSUE TITLE
BeforeUnloadEvent: Custom message was removed from browser support

### ISSUE THREAD

**Issue by milutin** [mdn/content#16226]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/BeforeUnloadEvent

### What information was incorrect, unhelpful, or incomplete?

Customizing message was removed in Chrome 51 and Safari
 https://chromestatus.com/feature/5349061406228480
 

### What did you expect to see?

Information about custom message is not available anymore.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/beforeunloadevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/BeforeUnloadEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/beforeunloadevent/index.md
* Last commit: https://github.com/mdn/content/commit/2ddfb4d94b9168982ff02eb29e615a247fba50cf
* Document last modified: 2022-05-16T17:59:02.000Z

</details>

**Comment by wbamberg** [comment]
@milutin I'm not sure what you are asking for here. As I understand it, some browsers used to allow a `beforeunload` event handler to return a custom string, and in that case the browser would display the custom string when asking the user to confirm that they want to leave the page.

But no modern browsers have supported this for years, and it's not documented on https://developer.mozilla.org/en-US/docs/Web/API/BeforeUnloadEvent, and it's not specced behavior any more.

Are you asking that we should add to https://developer.mozilla.org/en-US/docs/Web/API/BeforeUnloadEvent something like "some browsers used to display the returned string as a custom message, but this is not specced behavior any more and no modern browsers do this any more"?

**Comment by milutin** [comment]
Yes, it would be great to have a warning that it is not supported anymore in modern browsers. Because after reading this article I thought I am doing something wrong when I was testing it on latest chrome. And only after many tries I have googled that it is not supported anymore.
