### ISSUE TITLE
Constraint Exerciser anchor link is broken

### ISSUE THREAD

**Issue by simonvarey** [mdn/content#16235]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API

### What specific section or headline is this issue about?

Guides and tutorials

### What information was incorrect, unhelpful, or incomplete?

The link to the Constraint Exerciser example links to the (non-existent) anchor 'example_constraint_exerciser' on *this* page (Media Streams API), when it should link to that anchor on the Media_Streams_API/Constraints page. The problem is that the 
`{{LandingPageListSubpages}}` macro grabs the first paragraph of the Media_Streams_API/Constraints page, which has the correct anchor link and moves the anchor to this page.

### What did you expect to see?

A link to https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints#example_constraint_exerciser

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/media_streams_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/media_streams_api/index.md
* Last commit: https://github.com/mdn/content/commit/a70fb35668d0eceb785425b748bbef7cb12f22d0
* Document last modified: 2022-05-18T14:48:30.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #16245 with a fix

After that fix is merged, this issue will automatically be marked as resolved, and closed.
