### ISSUE TITLE
Emscripten link on C to Wasm page is broken

### ISSUE THREAD

**Issue by abhimonk** [mdn/content#16238]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm

### What specific section or headline is this issue about?

The first section, "Compiling a New C/C++ Module to WebAssembly"

### What information was incorrect, unhelpful, or incomplete?

The link text in the above page that says "Emscripten" links to this page: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Emscripten

The above is an invalid page and gives a "Page not found" error when clicked.

### What did you expect to see?

I expected to either see the Emscripten text link to an mdn doc about Emscripten or at least the actual Emscripten web site. Alternatively the link could just be removed and the word "Emscripten" could be regular text.

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/16239
