### ISSUE TITLE
File System Access API: spec link seems outdated

### ISSUE THREAD

**Issue by szewai** [mdn/content#16243]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API

### What specific section or headline is this issue about?

Specifications

### What information was incorrect, unhelpful, or incomplete?

It is currently linked to https://wicg.github.io/file-system-access/.  

### What did you expect to see?

The latest link should be https://fs.spec.whatwg.org.

### Do you have any supporting links, references, or citations?

See https://github.com/WICG/file-system-access/issues/370

### Do you have anything more you want to share?

The spec maintainers and implementers are discussing issues around the spec in the whatwg repo; it would be nice if MDN page can point to that link.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/file_system_access_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/file_system_access_api/index.md
* Last commit: https://github.com/mdn/content/commit/f645be61920b67143e010bb6d9b4ffbec28078e0
* Document last modified: 2022-05-15T05:18:07.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #16244 with a fix

After that fix is merged, this issue will automatically be marked as resolved, and closed.
