### ISSUE TITLE
Incomplete example for IdleDeadline

### ISSUE THREAD

**Issue by ashleedawg** [mdn/content#16253]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/IdleDeadline

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

The `Example` section of the page for `IdleDeadline` says:

See our [complete example](https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API#example) in the article [Cooperative Scheduling of Background Tasks API](https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API)

...but the 'complete example" on the [linked page](https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API#example) does not use `IdleDeadline`

### What did you expect to see?

I thought a "complete example" for `IdleDeadline` would use `IdleDeadline`. 

### Do you have any supporting links, references, or citations?

n/a 

### Do you have anything more you want to share?

Great website; I visit several times a day.  Thanks!  :-)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/idledeadline`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IdleDeadline
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/idledeadline/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by OnkarRuikar** [comment]
The example does use the `IdleDeadline` interface:
```js
function runTaskQueue(deadline) {
  while ((deadline.timeRemaining() > 0 || deadline.didTimeout) && taskList.length) {
    let task = taskList.shift();
    currentTaskNumber++;

    task.handler(task.data);
    scheduleStatusRefresh();
  }
```

Here, `deadline` object is of type `IdleDeadline`. It is passed by the browser to the callback method when the browser calls the method.

Also, no constructor has been provided for the interface: https://w3c.github.io/requestidlecallback/#ref-for-dom-idledeadline-1 
Developers are not supposed to create the objects of `IdleDeadline` themselves.

**Comment by teoli2003** [comment]
Closing per comment. Feel free to reopen if we were mistaken.
