### ISSUE TITLE
[page types] Define page types for Web/API

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#16255]
Part of https://github.com/mdn/content/issues/15539.

In https://docs.google.com/spreadsheets/d/14RX8EEKPpeYkP2cF5Y_ZKF3JpNJ_24OL7stvZWNJLIY/edit#gid=2083448819, in the "API" tab, I've listed every page under https://developer.mozilla.org/en-US/docs/Web/API and made an initial determination about the page type.

I've come up with 12 types:

```
Web API overview (API)       119
Web API interface            896
Web API global function       11
Web API global property        6
Web API constructor          230
Web API instance method     1552
Web API instance property   2411
Web API static method         29
Web API static property        6
Web API event                433
Web API guide                202
Web API landing page           2
```

...and have ~100 unclassified.

The unclassified pages seem to fall into three main types: typdefs, WebGL extensions, and IE-only pages

## typedefs

This includes the following:

- [api/arraybufferview](https://developer.mozilla.org/en-US/docs/web/api/arraybufferview)
- [api/buffersource](https://developer.mozilla.org/en-US/docs/web/api/buffersource)
- [api/canvasimagesource](https://developer.mozilla.org/en-US/docs/web/api/canvasimagesource)
- [api/cssomstring](https://developer.mozilla.org/en-US/docs/web/api/cssomstring)
- [api/domhighrestimestamp](https://developer.mozilla.org/en-US/docs/web/api/domhighrestimestamp)
- [api/domstring](https://developer.mozilla.org/en-US/docs/web/api/domstring)
- [api/domtimestamp](https://developer.mozilla.org/en-US/docs/web/api/domtimestamp)
- [api/epochtimestamp](https://developer.mozilla.org/en-US/docs/web/api/epochtimestamp)
- [api/formdataentryvalue](https://developer.mozilla.org/en-US/docs/web/api/formdataentryvalue)
- [api/rtcstatsicecandidatepairstate](https://developer.mozilla.org/en-US/docs/web/api/rtcstatsicecandidatepairstate)
- [api/rtcstatstype](https://developer.mozilla.org/en-US/docs/web/api/rtcstatstype)
- [api/usvstring](https://developer.mozilla.org/en-US/docs/web/api/usvstring)

Maybe we need a "typedef" type? But several of these, like `DOMString` we are trying not to use any more, as they don't seem useful, and perhaps some more, like `RTCStatsIceCandidatePairState`, could be removed.

## WebGL extensions

These don't seem to fit into our Web API taxonomy at all. Maybe we need a WebGL extension type? Seems a shame though as it is rather specialised.

- [api/ext_blend_minmax](https://developer.mozilla.org/en-US/docs/web/api/ext_blend_minmax)
- [api/ext_color_buffer_float](https://developer.mozilla.org/en-US/docs/web/api/ext_color_buffer_float)
- [api/ext_color_buffer_half_float](https://developer.mozilla.org/en-US/docs/web/api/ext_color_buffer_half_float)
- [api/ext_disjoint_timer_query](https://developer.mozilla.org/en-US/docs/web/api/ext_disjoint_timer_query)
- [api/ext_disjoint_timer_query/beginqueryext](https://developer.mozilla.org/en-US/docs/web/api/ext_disjoint_timer_query/beginqueryext)
- [api/ext_disjoint_timer_query/createqueryext](https://developer.mozilla.org/en-US/docs/web/api/ext_disjoint_timer_query/createqueryext)
- [api/ext_disjoint_timer_query/deletequeryext](https://developer.mozilla.org/en-US/docs/web/api/ext_disjoint_timer_query/deletequeryext)
- [api/ext_disjoint_timer_query/endqueryext](https://developer.mozilla.org/en-US/docs/web/api/ext_disjoint_timer_query/endqueryext)
- [api/ext_disjoint_timer_query/getqueryext](https://developer.mozilla.org/en-US/docs/web/api/ext_disjoint_timer_query/getqueryext)
- [api/ext_disjoint_timer_query/getqueryobjectext](https://developer.mozilla.org/en-US/docs/web/api/ext_disjoint_timer_query/getqueryobjectext)
- [api/ext_disjoint_timer_query/isqueryext](https://developer.mozilla.org/en-US/docs/web/api/ext_disjoint_timer_query/isqueryext)
- [api/ext_disjoint_timer_query/querycounterext](https://developer.mozilla.org/en-US/docs/web/api/ext_disjoint_timer_query/querycounterext)
- [api/ext_float_blend](https://developer.mozilla.org/en-US/docs/web/api/ext_float_blend)
- [api/ext_frag_depth](https://developer.mozilla.org/en-US/docs/web/api/ext_frag_depth)
- [api/ext_shader_texture_lod](https://developer.mozilla.org/en-US/docs/web/api/ext_shader_texture_lod)
- [api/ext_srgb](https://developer.mozilla.org/en-US/docs/web/api/ext_srgb)
- [api/ext_texture_compression_bptc](https://developer.mozilla.org/en-US/docs/web/api/ext_texture_compression_bptc)
- [api/ext_texture_compression_rgtc](https://developer.mozilla.org/en-US/docs/web/api/ext_texture_compression_rgtc)
- [api/ext_texture_filter_anisotropic](https://developer.mozilla.org/en-US/docs/web/api/ext_texture_filter_anisotropic)
- [api/ext_texture_norm16](https://developer.mozilla.org/en-US/docs/web/api/ext_texture_norm16)
- [api/khr_parallel_shader_compile](https://developer.mozilla.org/en-US/docs/web/api/khr_parallel_shader_compile)
- [api/oes_element_index_uint](https://developer.mozilla.org/en-US/docs/web/api/oes_element_index_uint)
- [api/oes_fbo_render_mipmap](https://developer.mozilla.org/en-US/docs/web/api/oes_fbo_render_mipmap)
- [api/oes_standard_derivatives](https://developer.mozilla.org/en-US/docs/web/api/oes_standard_derivatives)
- [api/oes_texture_float](https://developer.mozilla.org/en-US/docs/web/api/oes_texture_float)
- [api/oes_texture_float_linear](https://developer.mozilla.org/en-US/docs/web/api/oes_texture_float_linear)
- [api/oes_texture_half_float](https://developer.mozilla.org/en-US/docs/web/api/oes_texture_half_float)
- [api/oes_texture_half_float_linear](https://developer.mozilla.org/en-US/docs/web/api/oes_texture_half_float_linear)
- [api/oes_vertex_array_object](https://developer.mozilla.org/en-US/docs/web/api/oes_vertex_array_object)
- [api/oes_vertex_array_object/bindvertexarrayoes](https://developer.mozilla.org/en-US/docs/web/api/oes_vertex_array_object/bindvertexarrayoes)
- [api/oes_vertex_array_object/createvertexarrayoes](https://developer.mozilla.org/en-US/docs/web/api/oes_vertex_array_object/createvertexarrayoes)
- [api/oes_vertex_array_object/deletevertexarrayoes](https://developer.mozilla.org/en-US/docs/web/api/oes_vertex_array_object/deletevertexarrayoes)
- [api/oes_vertex_array_object/isvertexarrayoes](https://developer.mozilla.org/en-US/docs/web/api/oes_vertex_array_object/isvertexarrayoes)
- [api/ovr_multiview2](https://developer.mozilla.org/en-US/docs/web/api/ovr_multiview2)
- [api/ovr_multiview2/framebuffertexturemultiviewovr](https://developer.mozilla.org/en-US/docs/web/api/ovr_multiview2/framebuffertexturemultiviewovr)
- [api/webgl_color_buffer_float](https://developer.mozilla.org/en-US/docs/web/api/webgl_color_buffer_float)
- [api/webgl_compressed_texture_astc](https://developer.mozilla.org/en-US/docs/web/api/webgl_compressed_texture_astc)
- [api/webgl_compressed_texture_astc/getsupportedprofiles](https://developer.mozilla.org/en-US/docs/web/api/webgl_compressed_texture_astc/getsupportedprofiles)
- [api/webgl_compressed_texture_etc](https://developer.mozilla.org/en-US/docs/web/api/webgl_compressed_texture_etc)
- [api/webgl_compressed_texture_etc1](https://developer.mozilla.org/en-US/docs/web/api/webgl_compressed_texture_etc1)
- [api/webgl_compressed_texture_pvrtc](https://developer.mozilla.org/en-US/docs/web/api/webgl_compressed_texture_pvrtc)
- [api/webgl_compressed_texture_s3tc](https://developer.mozilla.org/en-US/docs/web/api/webgl_compressed_texture_s3tc)
- [api/webgl_compressed_texture_s3tc_srgb](https://developer.mozilla.org/en-US/docs/web/api/webgl_compressed_texture_s3tc_srgb)
- [api/webgl_debug_renderer_info](https://developer.mozilla.org/en-US/docs/web/api/webgl_debug_renderer_info)
- [api/webgl_debug_shaders](https://developer.mozilla.org/en-US/docs/web/api/webgl_debug_shaders)
- [api/webgl_debug_shaders/gettranslatedshadersource](https://developer.mozilla.org/en-US/docs/web/api/webgl_debug_shaders/gettranslatedshadersource)
- [api/webgl_depth_texture](https://developer.mozilla.org/en-US/docs/web/api/webgl_depth_texture)
- [api/webgl_draw_buffers](https://developer.mozilla.org/en-US/docs/web/api/webgl_draw_buffers)
- [api/webgl_draw_buffers/drawbufferswebgl](https://developer.mozilla.org/en-US/docs/web/api/webgl_draw_buffers/drawbufferswebgl)
- [api/webgl_lose_context](https://developer.mozilla.org/en-US/docs/web/api/webgl_lose_context)
- [api/webgl_lose_context/losecontext](https://developer.mozilla.org/en-US/docs/web/api/webgl_lose_context/losecontext)
- [api/webgl_lose_context/restorecontext](https://developer.mozilla.org/en-US/docs/web/api/webgl_lose_context/restorecontext)
- [api/webgl_multi_draw](https://developer.mozilla.org/en-US/docs/web/api/webgl_multi_draw)
- [api/webgl_multi_draw/multidrawarraysinstancedwebgl](https://developer.mozilla.org/en-US/docs/web/api/webgl_multi_draw/multidrawarraysinstancedwebgl)
- [api/webgl_multi_draw/multidrawarrayswebgl](https://developer.mozilla.org/en-US/docs/web/api/webgl_multi_draw/multidrawarrayswebgl)
- [api/webgl_multi_draw/multidrawelementsinstancedwebgl](https://developer.mozilla.org/en-US/docs/web/api/webgl_multi_draw/multidrawelementsinstancedwebgl)
- [api/webgl_multi_draw/multidrawelementswebgl](https://developer.mozilla.org/en-US/docs/web/api/webgl_multi_draw/multidrawelementswebgl)

## IE-only pages

These are all defined at the top level, which seems to be wrong in many cases. But I don't know which interfaces they should be attached to. And it's hard to want to spend much time digging into them.

- [api/mscaching](https://developer.mozilla.org/en-US/docs/web/api/mscaching)
- [api/mscachingenabled](https://developer.mozilla.org/en-US/docs/web/api/mscachingenabled)
- [api/mscandidatewindowhide](https://developer.mozilla.org/en-US/docs/web/api/mscandidatewindowhide)
- [api/mscandidatewindowshow](https://developer.mozilla.org/en-US/docs/web/api/mscandidatewindowshow)
- [api/mscandidatewindowupdate](https://developer.mozilla.org/en-US/docs/web/api/mscandidatewindowupdate)
- [api/mscapslockwarningoff](https://developer.mozilla.org/en-US/docs/web/api/mscapslockwarningoff)
- [api/msfirstpaint](https://developer.mozilla.org/en-US/docs/web/api/msfirstpaint)
- [api/msgestureevent](https://developer.mozilla.org/en-US/docs/web/api/msgestureevent)
- [api/msgetpropertyenabled](https://developer.mozilla.org/en-US/docs/web/api/msgetpropertyenabled)
- [api/msgetregioncontent](https://developer.mozilla.org/en-US/docs/web/api/msgetregioncontent)
- [api/msgraphicstrust](https://developer.mozilla.org/en-US/docs/web/api/msgraphicstrust)
- [api/msgraphicstruststatus](https://developer.mozilla.org/en-US/docs/web/api/msgraphicstruststatus)
- [api/msisboxed](https://developer.mozilla.org/en-US/docs/web/api/msisboxed)
- [api/msmanipulationevent](https://developer.mozilla.org/en-US/docs/web/api/msmanipulationevent)
- [api/msmanipulationevent/initmsmanipulationevent](https://developer.mozilla.org/en-US/docs/web/api/msmanipulationevent/initmsmanipulationevent)
- [api/msplaytodisabled](https://developer.mozilla.org/en-US/docs/web/api/msplaytodisabled)
- [api/msplaytopreferredsourceuri](https://developer.mozilla.org/en-US/docs/web/api/msplaytopreferredsourceuri)
- [api/msplaytoprimary](https://developer.mozilla.org/en-US/docs/web/api/msplaytoprimary)
- [api/msplaytosource](https://developer.mozilla.org/en-US/docs/web/api/msplaytosource)
- [api/msputpropertyenabled](https://developer.mozilla.org/en-US/docs/web/api/msputpropertyenabled)
- [api/msrangecollection](https://developer.mozilla.org/en-US/docs/web/api/msrangecollection)
- [api/msrealtime](https://developer.mozilla.org/en-US/docs/web/api/msrealtime)
- [api/msregionoverflow](https://developer.mozilla.org/en-US/docs/web/api/msregionoverflow)
- [api/mssetmediaprotectionmanager](https://developer.mozilla.org/en-US/docs/web/api/mssetmediaprotectionmanager)
- [api/mssitemodeevent](https://developer.mozilla.org/en-US/docs/web/api/mssitemodeevent)
- [api/mssitemodejumplistitemremoved](https://developer.mozilla.org/en-US/docs/web/api/mssitemodejumplistitemremoved)
- [api/msthumbnailclick](https://developer.mozilla.org/en-US/docs/web/api/msthumbnailclick)
- [api/mswriteprofilermark](https://developer.mozilla.org/en-US/docs/web/api/mswriteprofilermark)

## Misc

There are a few leftovers:

I think perhaps this useless page should be deleted?

- [api/getcandidatewindowclientrect](https://developer.mozilla.org/en-US/docs/web/api/getcandidatewindowclientrect)

...and I think perhaps these were deleted in between me getting the list of pages and doing the analysis:

- [api/mediaconfiguration](https://developer.mozilla.org/en-US/docs/web/api/mediaconfiguration)
- [api/mediadecodingconfiguration](https://developer.mozilla.org/en-US/docs/web/api/mediadecodingconfiguration)
- [api/videoconfiguration](https://developer.mozilla.org/en-US/docs/web/api/videoconfiguration)

**Comment by dontcallmedom** [comment]
re WebGL extensions, from a quick check, they're actually interfaces (but whose interface object is not exposed to JavaScript); so maybe they could folded into interface pages?

what's the difference between an API overview and a landing page?

**Comment by teoli2003** [comment]
For the typedefs:
- [api/cssomstring](https://developer.mozilla.org/en-US/docs/web/api/cssomstring), [api/domstring](https://developer.mozilla.org/en-US/docs/web/api/domstring), [api/usvstring](https://developer.mozilla.org/en-US/docs/web/api/domstring): we are actively removing them:
  - `CSSOMString` – The only links left are in…`DOMString`, `USVString`, and itself. It is almost gone.
  - `USVString` – Without counting  `DOMString`, `USVString`, and itself, there are only 4 pages left linking to it. Consider it gon too
  - `DOMString` – There are still 92 pages with them, but Onkar is actively removing them. If needed, we can accelerate the movement here, but they will be gone this Quarter.
-  [api/domtimestamp](https://developer.mozilla.org/en-US/docs/web/api/domtimestamp), [api/epochtimestamp](https://developer.mozilla.org/en-US/docs/web/api/epochtimestamp), [api/domhighrestimestamp](https://developer.mozilla.org/en-US/docs/web/api/domhighrestimestamp): we want to replace them with _number_, and eventually an explanation (in second, in milisecond, ev. obfuscated). They are the next targets after the strings types.
  - `DOMTimeStamp` – 15 occurrences
  - `EpochTimeStamp` – 1 single occurrence outside `DomTimeStamp`and itself. 
  - `DOMHighResTimeStamp` – 96 occurrences (+ an overview page). This is a bit more work but on our radar.
- [api/rtcstatsicecandidatepairstate](https://developer.mozilla.org/en-US/docs/web/api/rtcstatsicecandidatepairstate),
[api/rtcstatstype](https://developer.mozilla.org/en-US/docs/web/api/rtcstatstype). Like WebRTC dictionaries these are on our radar to be merged in the property and method pages using them.

The only ones to consider are:
- [api/formdataentryvalue](https://developer.mozilla.org/en-US/docs/web/api/formdataentryvalue) (2 occurrences except itself)
- [api/arraybufferview](https://developer.mozilla.org/en-US/docs/web/api/arraybufferview) (34 occurrences)
- [api/buffersource](https://developer.mozilla.org/en-US/docs/web/api/buffersource) (96 occurrences, the only problematic one)
- [api/canvasimagesource](https://developer.mozilla.org/en-US/docs/web/api/canvasimagesource) (10 occurrences)

They act as abbreviations for a list of interfaces. I think we should just rephrase them with that list...

So: I don't think we need the _typedef_ page type, we should just finish the cleaning here.

**Comment by teoli2003** [comment]
For misc:
- Hamish deleted [api/mediaconfiguration](https://developer.mozilla.org/en-US/docs/web/api/mediaconfiguration), [api/mediadecodingconfiguration](https://developer.mozilla.org/en-US/docs/web/api/mediadecodingconfiguration), [api/videoconfiguration](https://developer.mozilla.org/en-US/docs/web/api/videoconfiguration) as part of #15813 (In our movement to delete enums, typedefs and dictionaries, with maybe a few exceptions for the latest ones)
- [api/getcandidatewindowclientrect](https://developer.mozilla.org/en-US/docs/web/api/getcandidatewindowclientrect) delete (I opened the PR: #16259)

**Comment by wbamberg** [comment]
> re WebGL extensions, from a quick check, they're actually interfaces (but whose interface object is not exposed to JavaScript); so maybe they could folded into interface pages?

Thanks, that sounds plausible!

> what's the difference between an API overview and a landing page?

A landing page is a generic page that presents lots of links to other pages, usually at the top of the IA for some content area. So for instance, https://developer.mozilla.org/en-US/docs/Web/CSS/Reference, https://developer.mozilla.org/en-US/docs/Web/API, https://developer.mozilla.org/en-US/docs/Web/HTML/Element are all landing pages. They don't have any defined structure (yet) so in that way are just like guide pages, and for our purposes now can can treat them just like guide pages. Although I think of them more like sidebars really.

An API overview page is specific to Web/API and describes an API, which generally (maybe always?) maps to a specification. It has a [definite structure](https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types#api_landing_page) where we describe the API, list its interfaces and the specifications: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API.

Does that make sense?

**Comment by teoli2003** [comment]
For the IE-specific pages, I would delete them (and redirect to their last GitHub version – I believe a good way to archive content now that we are using git). (And remove internal links leading to them).

That way we don't have to maintain them, but they are still available for IE-fanatics (a.k.a some product managers) victims out there.

**Comment by wbamberg** [comment]
> For the IE-specific pages, I would delete them (and redirect to their last GitHub version – I believe a good way to archive content now that we are using git). (And remove internal links leading to them).

I think the main issue with the IE pages (apart from them being out of date) is that they are in the wrong place. That is, they are really attached to some interface, rather than being global. But it's hard to figure out which interface, given that there's so little information about them. So we could probably solve this, it's just whether it's worth it.

I would be OK to delete them as well. Redirecting to GitHub is a great idea we should totally do, but is not possible in content only as far as I know, so it's a dev dependency.

Also for these difficult cases I would be OK to not assign any page type for now, and that gives us a to-do list of unresolved pages while not blocking any work that depends on having page types.

**Comment by teoli2003** [comment]
>  Redirecting to GitHub is a great idea we should totally do, but is not possible in content only as far as I know, so it's a dev dependency.

There are external redirects in `_redirects.txt`; I don't know if there is an allow-list or not, though. @schalkneethling do you know?
![Capture d’écran 2022-05-20 à 19 21 04](https://user-images.githubusercontent.com/1466293/169580184-b38b3f16-8817-4d26-97e8-7f2550c7e638.png)

**Comment by schalkneethling** [comment]
> > Redirecting to GitHub is a great idea we should totally do, but is not possible in content only as far as I know, so it's a dev dependency.
> 
> There are external redirects in `_redirects.txt`; I don't know if there is an allow-list or not, though. @schalkneethling do you know? ![Capture d’écran 2022-05-20 à 19 21 04](https://user-images.githubusercontent.com/1466293/169580184-b38b3f16-8817-4d26-97e8-7f2550c7e638.png)
> 
> (I'm all for using GitHub as the archive of deleted content. It can even be the default if we don't specify a redirect when using `yarn content delete`.)

Pining the engineering team for input here. /cc @mdn/core-dev

**Comment by caugner** [comment]
> There are external redirects in `_redirects.txt`; I don't know if there is an allow-list or not, though. @schalkneethling do you know?

There is currently no restriction on external redirects.

**Comment by wbamberg** [comment]
@dominiccooney suggested we should have dedicated page types for the WebGL pages, and I think this is best. I think this would give us two new page types:

```
webgl-extension
webgl-extension-method
```

(the second for extensions that add new methods, rather than extending existing methods.) I'm going to file some PRs for this and see how it looks.)

**Comment by wbamberg** [comment]
To help keep track of the MS pages I'm using a spreadsheet: https://docs.google.com/spreadsheets/d/1zN7PjWXDzWMtYNit86e6Fs1zDGZz8lCiXz_RoMFYU2c/edit?usp=sharing.
