### ISSUE TITLE
Uncaught (in promise) DOMException: User cancelled the requestDevice() chooser.

### ISSUE THREAD

**Issue by lwj06** [mdn/content#16261]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/requestDevice

### What specific section or headline is this issue about?

Bluetooth.requestDevice()

### What information was incorrect, unhelpful, or incomplete?

When I call the requestDevice method for the first time, the result is normal, but the second time I get an error：
Uncaught (in promise) DOMException: User cancelled the requestDevice() chooser.

### What did you expect to see?

I want to repeat the search for bluetooth devices on the electron,
requestDevice() Should support multiple searches bluetooth device ?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/bluetooth/requestdevice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/requestDevice
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/bluetooth/requestdevice/index.md
* Last commit: https://github.com/mdn/content/commit/7b51a700e637845d36a059643f8df4e8ca6cc2aa
* Document last modified: 2022-05-16T05:11:01.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing, problems in the MDN documentation.

It looks like you are looking for help with your code. Unfortunately, we don't have enough availability to help you.

May I suggest asking your question on a specialized website, like StackOverflow?

I'm closing this issue. If I've misunderstood you and you were actually reporting a problem in the documentation, feel free to reopen it, while providing more information so we can understand the problem.

Thanks for your interest.
