### ISSUE TITLE
Suggestion: make it possible to use 'name' instead of 'id' for label input

### ISSUE THREAD

**Issue by Scrabble96** [mdn/content#1626]
Background: I am attempting to create an html and CSS-only dropdown dynamically generated menu for a website - i.e. no jQuery, JavaScript, etc. It's a Joomla! 3x website, but the following applies to any website using HTML5 and CSS. 

To avoid the use of buttons - which require the JS 'onClick' function - I have been trying to use the checkbox hack instead. However, as explained on this page [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label](url) if the input is outside the label then the label tag needs to include `for="id-1"` and the input tag needs `id="id-1"`, like this example on the above page with a 'menu' added:

```
<nav>
<label for="cheese">Do you like cheese?</label>
<input type="checkbox" name="cheese" id="cheese">
<ul>
    <li>an item</li>
</ul>
</nav>
```

With this setup it is then possible to display a previously hidden menu `<UL>` like this:
```
#cheese+ul {
    display:none;
  }
#cheese:checked+ul {
    display: block;
  }
```

But, as the same menu could appear twice on the same web page - e.g. at the top and the bottom - using IDs in the code would therefore cause duplicate IDs to appear, which we all know is not valid HTML.

To avoid using the IDs in a label, it is possible to put the input tag inside the label tag and the 'for' and 'id' can be dispensed with, like this:

```
<nav>
<label>Do you like peas?
  <input type="checkbox" name="peas">
</label>
<ul>
    <li>an item</li>
</ul>
</nav>
```

BUT, using this layout without IDs the CSS no longer works on the undisplayed UL as the checked input is no longer its sibling but a 'aunt/uncle', i.e. a sibling of its parent.

My proposal - suggestion - therefore, is to enable the use of the 'name' attribute instead of the 'id', which would solve the problem.

**Comment by Ryuno-Ki** [comment]
In your porposal, how would you target the `<ul>` in CSS?

The relationship of label htmlFor with input ID is required for HTML:
https://www.w3.org/TR/html52/sec-forms.html#the-label-element
https://html.spec.whatwg.org/multipage/forms.html#the-label-element

Unless you nest it.
BUT CSS does not have a parent selector, so it's (to my knowledge) to not target the `<ul>` from `input:checked`.

I imagine that you want to use `input[name="cheese"]:checked + ul` here.
That's totally possible, but does not help when the `<input />` is nested.

**Comment by Scrabble96** [comment]
>
> I imagine that you want to use `input[name="cheese"]:checked + ul` here.
> That's totally possible, but does not help when the `<input />` is nested.

That is exactly the point I was making. My suggestion is that 'name' or some other attribute could be used instead of 'id' when the input is not nested so that the 'for' points to 'a n other-attribute'.

Someone/group makes up the rules. Maybe it's not here, but I'm demonstrating that the rigid rule that requires 'id' means that it's not possible to have a solely HTML & CSS multi-level dropdown menu without using IDs.

**Comment by sideshowbarker** [comment]
I’d suggest re-raising this in the issue tracker for the HTML spec at https://github.com/whatwg/html/issues/
