### ISSUE TITLE
Error in REM example - Default browser in px value used in text not correspinding to the example's output

### ISSUE THREAD

**Issue by vivaelbarto** [mdn/content#16278]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#rems

### What specific section or headline is this issue about?

Rems

### What information was incorrect, unhelpful, or incomplete?

In the example output you are specifying a 10px default browser font-size, see below: 

font-size: 62.5%; /* font-size 1em = **10px on default browser settings** */

While the paragraph below it refers to the browser's default font-size of 16px instead, which is not consistent with the math conveyed:

_**"assuming that the browser's font-size has been left at the default value of 16px"**_

### What did you expect to see?

I think the paragraph should instead state the following: 

_"In this example, the words "outer inner outer" are all displayed at 16px (**assuming that the browser's font-size has been left at the default value of 10px**)."_

If I am understanding correctly, according to the example: 

Default browser font-size: 10px
Span font-size: 1.6rem = 10px * 1.6 = 16px

Since rem units are used, the inner <span> element only inherits the font-size of the root element. Thereby making them all have the same 16px font-size.

I apologize in advance if I'm not understanding the documentation correctly. :)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-size`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-size
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-size/index.md
* Last commit: https://github.com/mdn/content/commit/1090fbd748f0d9595dd3471b6335dae9e20b37c8
* Document last modified: 2022-04-30T05:41:40.000Z

</details>

**Comment by OnkarRuikar** [comment]
The statement is not saying that default font size is 10px.

> font-size: 62.5%; /* font-size 1em = 10px on default browser settings */

The statement means, 16px(default) x 0.625 = 10px. For child elements 1em would be 10px.

I think, as the statement is in `rem` section it should be:

```
  font-size: 62.5%; /* font-size 1rem = 10px on default browser settings */
```

***
We can set the 1rem value in browser(chrome) settings: 
![set font size](https://i.imgur.com/JbhxCOX.png) 
This is what 1rem equals to. The default value is 16px.
The statement "assuming that the browser's font-size has been left at the default value of 16px" is refering to this setting.

**Comment by vivaelbarto** [comment]
Onkar,

Thanks for the clarification.
