### ISSUE TITLE
Error in describing the math related to the EMs compound font size example.

### ISSUE THREAD

**Issue by vivaelbarto** [mdn/content#16272]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#ems

### What specific section or headline is this issue about?

Ems (right after the compound Ems example is presented)

### What information was incorrect, unhelpful, or incomplete?

In the example's CSS output it is stated that the browser's default font-size is 10px, see below:

font-size: 62.5%; /* font-size 1em = **10px on default browser settings** */

But in the paragraph coming later, when the math logic is being further explained, the browser's default font size is mistakenly changed to 16px instead, which could end up misleading the reader. 

This is the line in question: 

"Assuming that the browser's default font-size is 16px"

### What did you expect to see?

I think the correct value should be 10px due to the math:

_"Assuming that the browser's default font-size is 10px, the words "outer" would be rendered at 16px, but the word "inner" would be rendered at 25.6px..."_

This way, the rest of the text would make sense with the expected math result:

Default browser font-size: 10px
Outer Spans: 1.6em = 10px * 1.6 = 16px
Inner Span: 1.6em = 16px * 1.6 = 25.6px 

Sorry if I didn't go straight and edited it myself. I'm just beginning to learn the content so I didn't feel quite confident yet :)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-size`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-size
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-size/index.md
* Last commit: https://github.com/mdn/content/commit/1090fbd748f0d9595dd3471b6335dae9e20b37c8
* Document last modified: 2022-04-30T05:41:40.000Z

</details>

**Comment by deepug9787** [comment]
> font-size: 62.5%; /* font-size 1em = 10px on default browser settings 

What it really means is:

1em = 10px, if the default browser font-size is 16px. (62.5% of 16 = 10)

So the math will be:

Default browser font-size = 16px
html element font-size = 62.5% = 10px (62.5% of 16 = 10)
Outer span font-size = 1.6em = 16px (1.6 x 10)
Inner span font-size = 1.6em x 1.6em = 25.6px (1.6 x 1.6 x10)

I've issued a PR to fix it. 

Hope this helps. Cheers.
