### ISSUE TITLE
WebRTC: Cover how RTP works

### ISSUE THREAD

**Issue by a2sheppy** [mdn/content#1628]
We should cover how RTP works and how you can control or configure it when possible.

## References

*   Specification: https://tools.ietf.org/html/rfc4588 (see especially sections 1 and 3 for information about what it's useful for)

## Topics

*   [ ] How RTP connections are made
*   [ ] How RTP data flows
*   [ ] Probably one or more nice data flow diagrams
*   [ ] RTP transmission (WebRTC RTX)
*   [ ] Enabling RTP (using the `mimeType` on the codec options); see https://w3c.github.io/webrtc-pc/#dom-rtcrtpcapabilities-codecs. In Chrome it's here: http://jsfiddle.net/jib1/n98p63qt/
*   [ ] ... and probably more ...

## Acceptance criteria

*   Content written and reasonably clear
*   Submitted to engineers for review

**Comment by dontcallmedom** [comment]
The issue should be retitled s/WebXR/WebRTC/.

There is an ongoing project to explain the WebRTC stack in general being developed in https://github.com/webrtc-for-the-curious/webrtc-for-the-curious - RTP is covered in the networking piece in https://webrtcforthecurious.com/docs/05-real-time-networking/ (available under CC0)

**Comment by sideshowbarker** [comment]
> The issue should be retitled s/WebXR/WebRTC/.

Retitled
