### ISSUE TITLE
Example code for HTML article element

### ISSUE THREAD

**Issue by krikienoid** [mdn/content#1629]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Both the MDN docs and W3 spec say that:

> Each `<section>` should be identified, typically by including a heading (`<h1>`-`<h6>` element) as a child of the `<section>` element.

However, on the MDN article for the `<article>` element, the example given at the bottom contains `<section>` elements without headings. These `<section>`s should either have headings added or be replaced with `<div>`s.

```
<section class="main_review">
  <p>Dinos were great!</p>
</section>
<section class="user_reviews">
  ...
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve opened https://github.com/mdn/content/pull/1985 with a fix.
