### ISSUE TITLE
/en-US/.../Var_hides_argument article description error

### ISSUE THREAD

**Issue by Yayure** [mdn/content#1630]
## URL(s)
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Var_hides_argument

## Request type

- [ ] New documentation
- [x] Correction or update

## Details
The content described in this article does not occur in strict mode.
```javascript
'use strict';

(function f(arg) { 
  var arg = 'foo';
  console.log(arg);
})('bar')
// foo
// Did't throw an Error in Firefox 77 and Chrome 83.
```

**Comment by himanshugarg** [comment]
What would be the fix here given that the error is not thrown (FF88) even when the function is copied verbatim from the article, instead of converting it to IIFE as is done in the bug report? Is the error ever thrown?

**Comment by hhdihosinzadeh** [comment]
آیا در مورد کارت اعتباری ویزا یا مستر کارت اطلاعی به دست آمده است

**Comment by hhdihosinzadeh** [comment]
اگر به این سرعت منبع باز ساخته شد و بسته شد در مورد پرونده های آینده به همین سرعت باشد ممنون میشم خسته نباشی از همکاری همه اونهای که تلاش کردن تا این درخواست کشش بسته شود

**Comment by hhdihosinzadeh** [comment]
برایم پیامی آمد در 5ساعت پیش به این موضوع که ارز های من آماده شده و در دست نگهداری است موضوع دیگری ضمیمه همین پست  مستر کارت اعتباری بعداً اعلام می‌شود بعد از یک ماه باز مجدداً آماده شده است این را جهت اطلاع رساندم
