### ISSUE TITLE
`null` is not a built-in object

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#16309]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null

### What information was incorrect, unhelpful, or incomplete?

`null` is put under the "Built-in objects" category, which is incorrect, because `null` is a keyword, not a property.

### What did you expect to see?

I expect it to be moved to "Expressions & Operators", where `new.target`, `this`, etc. live.

That would separate this from `undefined`, which is desirable because `undefined` acts more like a "built-in object".

### Do you have any supporting links, references, or citations?

https://tc39.es/ecma262/#prod-ReservedWord

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/null`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/null/index.md
* Last commit: https://github.com/mdn/content/commit/edaa4aff4cf7532efdcba6014b9316aad2a5b6f1
* Document last modified: 2022-03-27T17:30:40.000Z

</details>

**Comment by OnkarRuikar** [comment]
But it is an object:
```js
console.log(typeof null); // returns 'object'
```
I think it belongs in this list: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#value_properties

**Comment by Josh-Cena** [comment]
`typeof import.meta === "object"`, `typeof this === anything`, `typeof new.target === "object"`, but they are all in the "Expressions & statements" section.

`x` being a "global object" means `Object.hasOwn(globalThis, "x")` is true. This holds for `undefined` and `NaN` but not for `null`.
