### ISSUE TITLE
empty reference to compatibility table in Deprecated notice 

### ISSUE THREAD

**Issue by bnjmnrsh** [mdn/content#16300]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

### What specific section or headline is this issue about?

empty reference to compatibility table in Deprecated notice 

### What information was incorrect, unhelpful, or incomplete?

There is a broken link to a compatibility table in the leading deprecation notice. 

### What did you expect to see?

A compatibility table

### Do you have any supporting links, references, or citations?

https://caniuse.com/mdn-svg_elements_a_xlink_href

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/attribute/xlink_colon_href`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/xlink_colon_href/index.md
* Last commit: https://github.com/mdn/content/commit/925f7e1e7d759c74b62d8a52d58e47028b829f4f
* Document last modified: 2022-05-13T21:47:55.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #16313 with a fix for this

After that fix is merged, this issue will automatically be marked as resolved, and closed.
