### ISSUE TITLE
/en-US/.../Non_configurable_array_element there are some errors in this article

### ISSUE THREAD

**Issue by Yayure** [mdn/content#1631]
## URL(s)

https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Non_configurable_array_element

## Request type

- [ ] New documentation
- [x] Correction or update

## Details
The content described in the article will only happen in strict mode.

```javascript
var arr = [];
Object.defineProperty(arr, 0, {value: 0}); 
Object.defineProperty(arr, 1, {value: "1"});

arr.length = 1;
// Nothing happen in Firefox 77 and Chrome 83.
```

```javascript
"use strict";
var arr = [];
Object.defineProperty(arr, 0, {value: 0}); 
Object.defineProperty(arr, 1, {value: "1"});

arr.length = 1;
// Throw an Error in Firefox 77 and Chrome 83.
```

**Comment by CreaTorAlexander** [comment]
I can update it 👍

**Comment by Ryuno-Ki** [comment]
Take it away! (I already noticed the commit).
I assigned you in hope nobody else feel inclined to pick it up then.

**Comment by ayushi2019031** [comment]
I would like to take this issue
