### ISSUE TITLE
Question of validity of statement about `alt`

### ISSUE THREAD

**Issue by estelle** [mdn/content#16312]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt

### What specific section or headline is this issue about?

alt attribute in attribute definitons

### What information was incorrect, unhelpful, or incomplete?

The alt attribute definition reads:

> Omitting alt altogether indicates that the image is a key part of the content and no textual equivalent is available. 

is this true? Are we saying omitting alt is a valid option?

### What did you expect to see?

"although `alt` is not officially required by the specification, omitting the attribute makes the content inaccessible. "

### Do you have any supporting links, references, or citations?

spec leads to https://w3c.github.io/html-aria/#el-img-empty-alt, which basically says use empty quotes, don't omit.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/img`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/img/index.md
* Last commit: https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e
* Document last modified: 2022-05-17T13:23:31.000Z

</details>

**Comment by sideshowbarker** [comment]
@stevefaulkner can speak to this.

As far as what the current wording corresponds to, I guess it comes from https://html.spec.whatwg.org/multipage/images.html#unknown-images and https://html.spec.whatwg.org/multipage/images.html#an-image-in-an-e-mail-or-private-document-intended-for-a-specific-person-who-is-known-to-be-able-to-view-images

But there’s significant disagreement about the guidance in that entire _“Requirements for providing text to act as an alternative for images”_ of the spec — so for MDN purposes, we don’t need to consider that section authoritative at all.

**Comment by OnkarRuikar** [comment]
I think omitting it means it's just an image with no other meaning/role and is part of the data/content. Treat it just like an image and not as image button etc.

With blank it's a part of the presentation(background, decorations etc.) and not to be considered specifically as an image object or any interactable item.

And when provided with value, the img is an image with possible roles as image, button any interactable element. 

Even if developers don't provide specific role/attribute there are implicit roles in second column which are to be inferred by the non visual user agents. So keeping alt blank means it's not an image content it's just part of the presentation(decoration). So I think keeping it blank is worse than omitting it, if the image is a part of your data to be presented and not a decoration.

**Comment by estelle** [comment]
> In such cases, the [alt](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-alt) attribute may be omitted, but one of the following conditions must be met as well:

> The [img](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element) element is in a [figure](https://html.spec.whatwg.org/multipage/grouping-content.html#the-figure-element) element that contains a [figcaption](https://html.spec.whatwg.org/multipage/grouping-content.html#the-figcaption-element) element that contains content other than [inter-element whitespace](https://html.spec.whatwg.org/multipage/dom.html#inter-element-whitespace), and, ignoring the [figcaption](https://html.spec.whatwg.org/multipage/grouping-content.html#the-figcaption-element) element and its descendants, the [figure](https://html.spec.whatwg.org/multipage/grouping-content.html#the-figure-element) element has no [flow content](https://html.spec.whatwg.org/multipage/dom.html#flow-content-2) descendants other than [inter-element whitespace](https://html.spec.whatwg.org/multipage/dom.html#inter-element-whitespace) and the [img](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element) element.

> The [title](https://html.spec.whatwg.org/multipage/dom.html#attr-title) attribute is present and has a non-empty value.

This burden is not included in our description. basically, it is never not ok to not describe an image, though if you're sending yourself an image and you know you can see it, it's "legal" per the second link.
