### ISSUE TITLE
Bad Example for ReadableStream - Doesn't actually work

### ISSUE THREAD

**Issue by jon49** [mdn/content#1632]
The example here https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#Examples is misleading as it doesn't actually work in live code.

See this answer on SO for what actually works (second read stream):

https://stackoverflow.com/a/62459039/632495

I'm not sure how to change the actual docs so just submitting an issue here.

**Comment by Rumyra** [comment]
https://github.com/mdn/content/pull/2398
