### ISSUE TITLE
Issue with "filterRes": …

### ISSUE THREAD

**Issue by seanmorris** [mdn/content#1635]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/filterRes

#### What information was incorrect, unhelpful, or incomplete?

Mentions deprecation but does not specify replacement implementation.

#### Specific section or headline?

"Deprecated" heading

#### What did you expect to see?

The updated alternative that the feature was deprecated in favor of.

#### Did you test this? If so, how?

n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/attribute/filterres`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/filterRes
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/svg/attribute/filterres/index.html
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@seanmorris Thanks for noticing this.

I did some research:
- [The Art Of SVG Filters And Why It Is Awesome](https://www.smashingmagazine.com/2015/05/why-the-svg-filter-is-awesome/) says, it was deprecated in Filter Effects Module Level 1.
- Looking into the [spec](https://www.w3.org/TR/filter-effects/) it says
  > The filterRes attribute was removed from the specification.

  That means, there is no replacement for it.
- Looking at [Large Blurs in SVG Filters not working in Safari](https://stackoverflow.com/a/488976689) from 2018, iOS/Safari might be able to respect it (since they did not remove the code?)
- We still have instances of it on MDN:

```
mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.html
mozilla/add-ons/webextensions/api/webrequest/streamfilter/ondata/index.html
mozilla/add-ons/webextensions/api/webrequest/streamfilter/onstart/index.html
mozilla/add-ons/webextensions/api/webrequest/streamfilter/disconnect/index.html
mozilla/add-ons/webextensions/api/webrequest/streamfilter/error/index.html
mozilla/add-ons/webextensions/api/webrequest/streamfilter/onstop/index.html
mozilla/add-ons/webextensions/api/webrequest/streamfilter/close/index.html
mozilla/add-ons/webextensions/api/webrequest/streamfilter/onerror/index.html
mozilla/add-ons/webextensions/api/webrequest/streamfilter/write/index.html
mozilla/add-ons/webextensions/api/webrequest/streamfilter/suspend/index.html
mozilla/add-ons/webextensions/api/webrequest/streamfilter/status/index.html
mozilla/add-ons/webextensions/api/webrequest/streamfilter/index.html
mozilla/add-ons/webextensions/api/webrequest/streamfilter/resume/index.html
mozilla/add-ons/webextensions/api/webrequest/index.html
mozilla/firefox/releases/57/index.html
_wikihistory.json
_redirects.txt
web/api/svgfilterelement/index.html
web/svg/applying_svg_effects_to_html_content/index.html
web/svg/attribute/filterres/index.html
web/svg/attribute/index.html
web/svg/element/filter/index.html
```

**Comment by Ryuno-Ki** [comment]
@chrisdavidmills What to do with our code examples?
Removing them?

I noticed, that many code snippets moved to „interactive examples” - shall the SVG ones be moved there as well (while at it)?

**Comment by sideshowbarker** [comment]
Closing this since this issue is asking what the recommended replacement is, and per https://github.com/mdn/content/issues/1635#issuecomment-765932628 there is no recommended replacement.
