### ISSUE TITLE
Issue with "Event.preventDefault()": displayWarning() example doesn't work with autofill

### ISSUE THREAD

**Issue by Sudobeast** [mdn/content#1637]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

#### What information was incorrect, unhelpful, or incomplete?
The displayWarning() example didn't work when I selected my capitalized name from my autofill list

#### Specific section or headline?
Stopping keystrokes from reaching an edit field > Result

#### What did you expect to see?
A warning

#### Did you test this? If so, how?
1. Open Microsoft Edge (88.0.705.50)
2. Go to https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault
3. Scroll down to Stopping keystrokes from reaching an edit field > Result
4. Click the box and select an item with a capital letter
5. Observe

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/event/preventdefault`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/event/preventdefault/index.html
* Report started: 2021-01-22T19:11:57.555Z

</details>

**Comment by chrisdavidmills** [comment]
Weird — I tested this in Firefox and Chrome, and it worked fine. I don't have access to Edge, but since v88 is based on Chromium, you'd expect that to work too. Does it give you any error messages in the console?

**Comment by Draguwro** [comment]
@chrisdavidmills No console errors; it's just that I didn't get a warning when I selected my name from autofill:

![](https://i.imgur.com/QqVJEki.gif)

**Comment by chrisdavidmills** [comment]
@Draguwro from the video you have included, it looks like you are including the capital letters in the field via some kind of browser autocomplete mechanism, rather than typing them in. The code is activated via the `keypress` event, so wouldn't be triggered by this.

What happens when you directly type in some non-lower-case letters? Capitals or numbers would do.

**Comment by Ryuno-Ki** [comment]
From a quick research on the web, autofill should trigger a „change” event.
Another option would be the addition of `autocomplete="off"` to disable it completely.
