### ISSUE TITLE
Example is showing a result from bootstrap, not from Django

### ISSUE THREAD

**Issue by SeriousTube** [mdn/content#16409]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views

### What specific section or headline is this issue about?

The bottom of Creating the Detail View template just before What does it look like?

### What information was incorrect, unhelpful, or incomplete?

It says:

The second interesting (and non-obvious) thing in the template is where we set a class (text-success, text-danger, text-warning) to color-code the human readable status text for each book instance ("available", "maintenance", etc.). Astute readers will note that the method BookInstance.get_status_display() that we use to get the status text does not appear elsewhere in the code.

This function is automatically created because BookInstance.status is a [choices field](https://docs.djangoproject.com/en/4.0/ref/models/fields/#choices). Django automatically creates a method get_FOO_display() for every choices field "Foo" in a model, which can be used to get the current value of the field.

### What did you expect to see?

This is confusing two different things. I think it was meant to illustrate the choices option as shown in the [Choices field](https://docs.djangoproject.com/en/4.0/ref/models/fields/#choices) link. However the color coding mentioned is because the example is using the bootstrap framework which isn't mentioned here and has nothing to do with django as seems to be inferred in the example.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/django/generic_views`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/generic_views/index.md
* Last commit: https://github.com/mdn/content/commit/ba0b979c88ca977a35ce40a2329ec941318b860d
* Document last modified: 2022-04-29T06:08:02.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you for taking the time to post. I don't find this confusing, but it certainly isn't necessary. Fixed in https://github.com/mdn/content/pull/16574
