### ISSUE TITLE
Unverified performance claim on Intl use

### ISSUE THREAD

**Issue by davidgilbertson** [mdn/content#1641]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

#### What information was incorrect, unhelpful, or incomplete?
This page contains a note:
> When formatting large numbers of dates, it is better to create an Intl.DateTimeFormat object and use the function provided by its format property.

A few issues with this:
* 'large numbers' is a meaningless combination of words. Does that mean a hundred, a billion?
* Lack of supporting evidence.
* I did a quick test with 10,000 dates and it makes no difference.

#### Specific section or headline?
Performance

#### What did you expect to see?
Truth, evidence, or nothing. I would suggest removing it entirely, unless there is a scenario where it's true (e.g. in Firefox, when parsing more than a million dates), in which case I would suggest mentioning that scenario along with the advice.

That'll save a bunch of happless web developers doing `new Intl.DateTimeFormat` everywhere because "MDN says it's faster".

#### Did you test this? If so, how?
```js
const dates = [...Array(10000)].map(() => new Date());

console.time('Create dates');
const datesStrings = dates.map(date => date.toLocaleString());
console.timeEnd('Create dates');

console.time('Create dates fast?');
const formatter = new Intl.DateTimeFormat();
const datesStrings2 = dates.map(date => formatter.format(date));
console.timeEnd('Create dates fast?');
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/tolocalestring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/date/tolocalestring/index.html
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve opened #1680 with a patch the drops that whole section and sentence.
