### ISSUE TITLE
Issue with "AnalyserNode.minDecibels": min/max dB does not affect getFloatFrequencyData amplitudes

### ISSUE THREAD

**Issue by ssangervasi** [mdn/content#1651]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/minDecibels

#### What information was incorrect, unhelpful, or incomplete?
These passages suggest that float frequency amplitudes are scaled to `[0.0, +1.0]`:

> When getting data from getFloatFrequencyData() or getByteFrequencyData(), any frequencies with an amplitude of minDecibels or lower will be returned as 0.0 or 0, respectively.

>When getting data from getFloatFrequencyData() or getByteFrequencyData(), any frequencies with an amplitude of maxDecibels or higher will be returned as +1.0 or 255, respectively.

In fact, float amplitudes are absolute dB units. Clipping is only applied to bytes. The [specification for bytes](https://webaudio.github.io/web-audio-api/#dom-analysernode-getbytefrequencydata) explains the min/max clipping behavior. The [specification for floats](https://webaudio.github.io/web-audio-api/#dom-analysernode-getfloatfrequencydata) does not.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/minDecibels#value
https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/maxDecibels#value

#### What did you expect to see?
Actual browser behavior matches the specification (containing large negative numbers) and MDN page for [getFloatFrequencyData](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getFloatFrequencyData) correctly notes that a silent value is `-Infinity` dB.

Based on this, I would expect to see an explicit statement that the min/maxDecibles properties have no effect on getFloatFrequencyData.

#### Did you test this? If so, how?
This script on Firefox 78.0.2

```
navigator.mediaDevices.getUserMedia({
    audio: true,
}).then((stream) => {
    const context = new AudioContext()
    const source = context.createMediaStreamTrackSource(
        stream.getAudioTracks()[0],
    )
    const analyser = context.createAnalyser()
    source.connect(analyser)    

    setInterval(() => {
        const dataArray = new Float32Array(analyser.frequencyBinCount)
        analyser.getFloatFrequencyData(dataArray)
    
        console.log('dataArray', dataArray)
        // => Values outside the default [-100, -30] range.
    }, 1000)
})

```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/analysernode/mindecibels`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/minDecibels
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/analysernode/mindecibels/index.html
* Document last modified: 2021-01-11T13:30:57.000Z

</details>

**Comment by Rumyra** [comment]
This all appears to be correct and I'll go ahead and modify the info on min & max decibel pages 👍 thanks @ssangervasi

**Comment by Rumyra** [comment]
https://github.com/mdn/content/pull/2390
&
https://github.com/mdn/content/pull/2391

**Comment by Rumyra** [comment]
Both pages changed - thanks @ssangervasi
