### ISSUE TITLE
Issue with "Box-shadow generator": …

### ISSUE THREAD

**Issue by nchilla** [mdn/content#1653]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator

#### What information was incorrect, unhelpful, or incomplete?
This is not a content issue, but the iframe classed `.sample-code-frame` is quite narrow and is cutting off the generator. I'm seeing this issue in Chrome, Safari, and Firefox on Mac OS Catalina. See screenshot:

<img width="903" alt="Screen Shot 2021-01-22 at 9 40 10 PM" src="https://user-images.githubusercontent.com/55153629/105569871-6d48d080-5cfa-11eb-8096-578e18b1fd33.png">

I was able to manually change the height on this class from auto to a pixel value in order to see the whole generator at once.

#### Specific section or headline?
box-shadow generator

#### What did you expect to see?
The full generator, not cut-off, as it has normally displayed in the past

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_background_and_borders/box-shadow_generator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/css_background_and_borders/box-shadow_generator/index.html
* Document last modified: 2021-01-13T18:01:00.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@nchilla Thanks for catching this!

@rachelandrew The iFrame embedded is https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator/_samples_/box-shadow_generator

It gets included via

https://github.com/mdn/content/blob/976ba14b79a60921c7d4fea54f1511028bd830ba/files/en-us/web/css/css_background_and_borders/box-shadow_generator/index.html#L2858

**Comment by rachelandrew** [comment]
Looks like this is wider issue than just this example https://github.com/mdn/yari/issues/2683

cc: @chrisdavidmills

**Comment by rachelandrew** [comment]
The change has now been made to the CSS so iframes are not tiny any more, therefore closing this.
