### ISSUE TITLE
[Draft/JavaScript] Is ?. a sub doman of . ?

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#1656]
Is `?.` under the doman of `.` ?

**Comment by Ryuno-Ki** [comment]
I'm aware of the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) (`?.`), but what do you mean by `.?`?

**Comment by mattiapontonio** [comment]
I meant 🧂

From
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors

To
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors/Optional_chaining

Or...

- chaining
- chaining/optional

But it's a _draft thinking_

**Comment by Ryuno-Ki** [comment]
I'm sorry, I can't follow.
I got, that it is a draft. But I lost your train of thought.

**Comment by mattiapontonio** [comment]
Because I'm Lost too 🤔

Why 
`obj.func?.(args)`

And not

`obj?.func(args)`

?

Maybe Is ok like It Is.

**Comment by Ryuno-Ki** [comment]
What does this have to do with `.?` (see issue title)?

**Comment by mattiapontonio** [comment]
`?`
make optional
`.`
and
`(`

I don't know... It's a _style issue_

**Comment by mattiapontonio** [comment]
I close this.
Thanks
