### ISSUE TITLE
Issue with "HTMLVideoElement.videoWidth": …

### ISSUE THREAD

**Issue by Sheffler09** [mdn/content#1657]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/videoWidth

#### What information was incorrect, unhelpful, or incomplete?
The anchor for "#about_intrinsic_width_and__height" doesn't lead anywhere and there's a weird piece of content a few paragraphs into the page's content, under the "Value" heading: {{page("/en-US/docs/Web/API/HTMLVideoElement/videoHeight", "About intrinsic width and height", 0, 1)}}

#### Specific section or headline?
Possibly correlated with the weird rendering of {{page("/en-US/docs/Web/API/HTMLVideoElement/videoHeight", "About intrinsic width and height", 0, 1)}} under the "Value" heading, after the 1st paragraph under that heading.

#### What did you expect to see?
A section describing details about video elements' intrinsic width and height.

#### Did you test this? If so, how?
Yes.  I clicked a hyperlink in the first paragraph of page content that was supposed to go to https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/videoWidth#about_intrinsic_width_and__height, but instead returned me to the top of the page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlvideoelement/videowidth`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/videoWidth
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/htmlvideoelement/videowidth/index.html
* Document last modified: 2021-01-11T13:30:57.000Z

</details>

**Comment by Ryuno-Ki** [comment]
See also #1615

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Remove the macro in the first paragraph and replace with a link to the glossary `/en-US/docs/Glossary/Intrinsic_Size`
* Remove in-page macro further down the page `{{page("/en-US/docs/Web/API/HTMLVideoElement/videoHeight", "About intrinsic width and height", 0, 1)}}`

**Comment by amyrlam** [comment]
@Rumyra @Ryuno-Ki 👋 am a new contributor to MDN, I can take this issue!

**Comment by sideshowbarker** [comment]
Hi @amyrlam, thanks much and please do go ahead and write up a PR

**Comment by amyrlam** [comment]
Got delayed. Update: starting it now!

**Comment by amyrlam** [comment]
Have some questions but made https://github.com/mdn/content/pull/4059. Figured would leave it as ready for review (vs a draft) to see if the qs can be answered, lmk if this is the wrong workflow.
