### ISSUE TITLE
JSON.stringify documentation states that the ordering of properties are not guaranteed to be stringified in any particular order

### ISSUE THREAD

**Issue by Ontonator** [mdn/content#16583]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

### What specific section or headline is this issue about?

Issue with plain JSON.stringify for use as JavaScript

### What information was incorrect, unhelpful, or incomplete?

The note between the two code blocks states:
> Note: Properties of non-array objects are not guaranteed to be stringified in any particular order. Do not rely on ordering of properties within the same object within the stringification.

### What did you expect to see?

I believe that the order of properties is now specified (as of ES2015?) here: https://tc39.es/ecma262/#sec-ordinaryownpropertykeys.
Perhaps the note should remain, but with clarification that the order of properties is not guaranteed _in older browsers_.

### Do you have any supporting links, references, or citations?

The chain of references I followed:
- https://tc39.es/ecma262/#sec-json.stringify
- https://tc39.es/ecma262/#sec-serializejsonproperty
- https://tc39.es/ecma262/#sec-serializejsonobject
- https://tc39.es/ecma262/#sec-enumerableownpropertynames (assuming no property list from replacer)
- https://tc39.es/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys
- https://tc39.es/ecma262/#sec-ordinaryownpropertykeys

### Do you have anything more you want to share?

I am not an expert in ES, and it is entirely possible that I'm misinterpreting something.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/json/stringify`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/json/stringify/index.md
* Last commit: https://github.com/mdn/content/commit/edaa4aff4cf7532efdcba6014b9316aad2a5b6f1
* Document last modified: 2022-03-27T17:30:40.000Z

</details>

**Comment by OnkarRuikar** [comment]
In short, number like properties are properly ordered, but string and symbols are put in insertion order.

The argument still holds, as relying on insertion order is not good. Because you can't control how users of your library/API will handle the objects.
```js
let obj = {z:'z', 9:'9', a:'a', '2':2, 1:1};
console.log(JSON.stringify(obj)); // {"1":1,"2":2,"9":"9","z":"z","a":"a"}

delete obj.z;
obj.z = 'zz';

console.log(JSON.stringify(obj)); //{"1":1,"2":2,"9":"9","a":"a","z":"zz"}
```

If we want add a note then I suggest adding it below the section like: "As of ES <version> properties are ordered in following order...".
We still need to check with safari, chrome on iOS iPadOS, IE, and other major browsers.

**Comment by Josh-Cena** [comment]
> but string and symbols are put in insertion order.

TBF, that's still a form of "well-defined" order. It's just not lexicographical.

I do think object key ordering is well-defined now, at least according to the spec (possible that not all implementations have kept up with the spec). It used to be implementation-specific.
