### ISSUE TITLE
CSS values and units: When I resize the browser window's width, the div.box's width doesn't change.

### ISSUE THREAD

**Issue by Den0702** [mdn/content#16594]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#functions

### What information was incorrect, unhelpful, or incomplete?

When I resize the browser window's width (I have opened this frame in new tab), the _div.box's_ width doesn't change.

### What did you expect to see?

 The _div.box's_ width changes when resizing browser window's width

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/values_and_units`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/values_and_units/index.md
* Last commit: https://github.com/mdn/content/commit/4c543c6feaf1a19552a120983ba943debc82858f
* Document last modified: 2022-05-06T22:35:47.000Z

</details>

**Comment by estelle** [comment]
This works as expected (Absolute lengths are not responsive, which is why it doesn't change. 

parent: width: 400px;
child: width: calc(20% + 100px);

20% of 400px is always 80, so the small box will always be 180px wide.

closing.
