### ISSUE TITLE
Picture-in-Picture API documentation should emphasize the enter/exit events

### ISSUE THREAD

**Issue by alanhogan** [mdn/content#16615]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API

### What specific section or headline is this issue about?

Toggling picture-in-picture mode

### What information was incorrect, unhelpful, or incomplete?

The example of toggle code uses the check:`if (document.pictureInPictureElement)`.  However, this property does not indicate that _our_ `<video>` is playing in PIP mode.

Tracking our status using e.g. resolution of `requestPictureInPicture` is not sufficient either, because other videos (on the same page or another page!) can 'take over' the browser's PIP feature, exiting our video's PIP mode for us.

Instead, we should be using the `enterpictureinpicture` and `leavepictureinpicture` events on the `video` element to track whether our video is in PIP mode or not, and then use this check in our toggle code.

This will 'catch' more accurately our PIP status.

### What did you expect to see?

See previous section.

### Do you have any supporting links, references, or citations?

https://developer.chrome.com/blog/watch-video-using-picture-in-picture/#listen-pip-events

### Do you have anything more you want to share?

I think the importance of these enter/exit events should be stressed on related MDN pages as well, including the following:

* http://developer.mozilla.org/en-US/docs/Web/API/Document/pictureInPictureElement (e.g. Note: The presence of this property on the DOM does not necessarily indicate that the video element you care about is being played in PIP mode)
* http://developer.mozilla.org/en-US/docs/Web/API/Document/exitPictureInPicture (e.g.: Calling this method is not the only reason a video may exit PIP; for example, another video from your page or another window may take over the browser's PIP functionality. To track your video's PIP status, listen for the exitpictureinpicture event)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/picture-in-picture_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/picture-in-picture_api/index.md
* Last commit: https://github.com/mdn/content/commit/0fcf43c69308021eff1e232dedb9e7d3b81dc82b
* Document last modified: 2022-05-20T12:13:51.000Z

</details>

**Comment by sideshowbarker** [comment]
Fixed in https://github.com/mdn/content/pull/16616
