### ISSUE TITLE
Prose mentions "inline styles" but markup sample has no inline styles

### ISSUE THREAD

**Issue by slimmy83** [mdn/content#16619]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade

### What specific section or headline is this issue about?

Basic example

### What information was incorrect, unhelpful, or incomplete?

Here we have a user agent style sheet, two author style sheets, a user stylesheet, and _**inline styles**_ within the HTML:

### What did you expect to see?

In the sections below the previous line, I would then expect in the section HTML to show a style attribute. UNLESS it is stating that there is a style attribute present already, but that it has the value "" by default.

HTML:

```
<ul>
<li class="specific">1<sup>st</sup></li>
<li>2<sup>nd</sup></li>
```

### Do you have anything more you want to share?

No, and I could be totally wrong, I just thought I should point this out if it did contain an error so it didn't confuse others.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/cascade`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/cascade/index.md
* Last commit: https://github.com/mdn/content/commit/f9861ad43f9b33ca9f1b6a4b1d403be5276763db
* Document last modified: 2022-05-16T17:26:04.000Z

</details>

**Comment by Anurella** [comment]
@slimmy83 The **inline styles** here is not referring to the style declared in the html like below,
`<li style="color:red:"> helo </li>`
 but the type declared by the user which sometimes is through the developer tool
 
<img width="469" alt="image" src="https://user-images.githubusercontent.com/24455861/170326329-d6ee95be-7a94-4d10-9d39-3867b2a5e900.png">
or some other[setup](https://www.thoughtco.com/user-style-sheet-3469931).
