### ISSUE TITLE
[WebAPI] Remove window.mozPaintCount

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#16625]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Another removal https://bugzilla.mozilla.org/show_bug.cgi?id=1769758

This was disabled in FF a while ago and will be removed in FF102 - so delete page https://developer.mozilla.org/en-US/docs/Web/API/Window/mozPaintCount and update anything linking to it (possibly redirect to window)

**Comment by hamishwillee** [comment]
Status

- [ ] Docs - #16716
- [ ] BCD
- [ ] Release note - not require - FF72 more than sufficient
- [ ] dev-doc-complete
