### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/Events/checking  404

### ISSUE THREAD

**Issue by gaoting** [mdn/content#1662]
https://developer.mozilla.org/en-US/docs/Web/Events/checking
This page 404

**Comment by Ryuno-Ki** [comment]
@gaoting Mind sharing where this page was linked from?
Otherwise, we'll be unable to fix it.
Thanks in advance.

**Comment by hamishwillee** [comment]
Probably it is the one from here: https://developer.mozilla.org/en-US/docs/Web/Events#update_events

There are a bunch of missing pages created using the macro `{{Event("checking")}}`. This is another case where we'd benefit from working highlighting of missing pages.

**Comment by chrisdavidmills** [comment]
FYI, we're not even supposed to be using the Events macro anymore. It creates links that point to the wrong place, and the ones that do work do so because they have redirects in place.

**Comment by hamishwillee** [comment]
@chrisdavidmills 
1. Where should the events go then? I.e. what URL should `checking` be at?
1. FYI only I discovered this documentation page in the archive on /en-US/docs/Web/Events/checking
1. Looking at these it might be that they are related to the Application Cache, now in a "do not use" state - https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

How we deal with this depends on what they are for. Advice welcome.

**Comment by chrisdavidmills** [comment]
So events pages are now hung off the object that they are fired on. So for example see the links under 

* https://developer.mozilla.org/en-US/docs/Web/API/Window#events
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement#events

The checking event was indeed related to AppCache; it is now in our Archive section, see https://developer.mozilla.org/en-US/docs/Archive/Events/checking

We should probably check through that events page, make sure nothing valuable is hidden there, and then just delete it, or write a couple of paragraphs to say that events are now hung off the objects they are fired on.

**Comment by hamishwillee** [comment]
Fixed by #2094
