### ISSUE TITLE
[CSS] Constructible stylesheets enabled

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#16624]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Looks like this is getting enabled on all channels for Firefox 101 - bcd and rel note needed (looks like docs are good)

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1644102

**Comment by hamishwillee** [comment]
Review
- BCD mentions the associated `layout.css.constructable-stylesheets.enabled` pref - it applies to `CSSStyleSheet` constructor, `replace`, `replaceSync` methods.
- The bug fix changes `layout.css.constructable-stylesheets.enabled` to always true. From search fox I can see this is applied to  `CSSStyleSheet` constructor, `replace`, `replaceSync` methods.
- Those methods are documented.
- So yes, minimally we can do a BCD update to mark those message enabled in FF101 and a release note that says they are publically available.

As to the the broad topic of constructible stylesheets, we do not document what that means. The term is used on MDN in [CSSStyleSheet](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet) but not defined.
There is however an excellent doc here:
-  [Constructable Stylesheets](https://web.dev/constructable-stylesheets/) (web.dev) 

I don't fully understand it, but I'd say that "someone" should create a doc for that on MDN - probably as an update to [Using_shadow_DOM]( https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM).
I worry that would be beyond me. Let's discuss next month :-)

Status:
- [ ] BCD
- [ ] Docs
- [ ] Release note
- [ ] dev-doc-complete

**Comment by hamishwillee** [comment]
So all the release work for this done. There is a separate guide that it would be nice to write - see https://github.com/mdn/content/issues/16774 (currently docs link to web.dev resource on why this stuff is relevant).

Would require a good knowledge of shadow DOM. I could gain that, but "not a priority" given time and resource.
