### ISSUE TITLE
Debugging worker threads in devtools information is incorrect

### ISSUE THREAD

**Issue by Eccenux** [mdn/content#16634]
### MDN URL

https://developer.mozilla.org/en-US/docs/web/api/web_workers_api/using_web_workers#debugging_worker_threads

### What specific section or headline is this issue about?

Debugging worker threads

### What information was incorrect, unhelpful, or incomplete?

The whole part about debugging with dev tools is incorrect.

E.g. this:
> The screenshot below shows this on Firefox. The sources list shows worker.js running in a separate worker thread. When selected this file is opened in the [source pane](https://firefox-source-docs.mozilla.org/devtools-user/debugger/ui_tour/index.html#source-pane), just like code running in the main thread.

### What did you expect to see?

I've described how you can actually debug here:
https://stackoverflow.com/questions/19660167/web-worker-debugging-in-firefox/72366362#72366362

There seem to be no other way then using Inspect button via `about:debugging`. Not sure when was this changed, but seems to be the same in FF 100.0 and FF dev 101.0.

### Do you have anything more you want to share?

As a side note this is really bad dev-UX. Would be nice to at least have inspect button in the Application tab of devtools...
https://bugzilla.mozilla.org/show_bug.cgi?id=1695114

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/contribute/feedback`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Feedback
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/feedback/index.md
* Last commit: https://github.com/mdn/content/commit/2777cdc8c8b54268a24beeeb7a98520e3331d3be
* Document last modified: 2022-04-26T11:32:33.000Z

</details>

**Comment by wbamberg** [comment]
Yeah, we shouldn't try to document devtools here, we should link to the devtools docs.

@Eccenux , is the page at https://firefox-source-docs.mozilla.org/devtools-user/application/service_workers/index.html also out of date?

**Comment by wbamberg** [comment]
Yeah, I think this should just link to the devtools docs, and if they are out of date, that's a bug over there :).

**Comment by wbamberg** [comment]
Looking at this again: this page is about web workers, not service workers, but the SO answer seems to be about service workers.

In Firefox (102) I can totally see web workers in the debugger, listed alongside other sources. For example, at https://mdn.github.io/fibonacci-worker/:

<img width="1122" alt="Screen Shot 2022-05-26 at 2 26 17 PM" src="https://user-images.githubusercontent.com/432915/170582908-2e3c9af2-dfd1-4edf-9269-ba0ee1d6bc61.png">

**Comment by Eccenux** [comment]
Oh, that's right. Not sure how I missed that 😅... Thanks.
