### ISSUE TITLE
Issue with the "Getting data into an event listener using the outer scope property" section

### ISSUE THREAD

**Issue by serglider** [mdn/content#1663]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

```
const myButton = document.getElementById('my-button-id');
const someString = 'Data';

myButton.addEventListener('click', function() {
  console.log(someString);  // Expected Value: 'Data'

  someString = 'Data Again';
});

console.log(someString);  // Expected Value: 'Data' (will never output 'Data Again')
```
The above snippet is flawed. There should be:
```
let someString = 'Data';
```
Or it should be mentioned that clicking the button will cause `TypeError: Assignment to constant variable.`

#### Specific section or headline?
Getting data into an event listener using the outer scope property

#### What did you expect to see?
```
const myButton = document.getElementById('my-button-id');
let someString = 'Data';

myButton.addEventListener('click', function() {
  console.log(someString);  // Expected Value: 'Data'

  someString = 'Data Again';
});

console.log(someString);  // Expected Value: 'Data' (will never output 'Data Again')
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/eventtarget/addeventlistener`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/eventtarget/addeventlistener/index.html
* Document last modified: 2021-01-19T19:38:52.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. You're absolutely right. Fixed by https://github.com/mdn/content/pull/1692
