### ISSUE TITLE
ipinfo website link is broken

### ISSUE THREAD

**Issue by Trailingslashes** [mdn/content#16648]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works

### What specific section or headline is this issue about?

DNS request not resolving 

### What information was incorrect, unhelpful, or incomplete?

The link to ipinfo is broken 

### What did you expect to see?

https://ipinfo.info/html/ip_checker.php

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/how_the_web_works`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/how_the_web_works/index.md
* Last commit: https://github.com/mdn/content/commit/15ed3e49a0e5ac3cd6833fc6b0fd0ddbd158718f
* Document last modified: 2022-05-02T14:18:16.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #16649 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
