### ISSUE TITLE
No more vars in Web/API

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#16662]
This is the companion to https://github.com/mdn/content/issues/16614, but for Web/API.

Here's a spreadsheet: https://docs.google.com/spreadsheets/d/1sl6gT8o-7yRPymZprwn6PNBRLQ6KNsKPFILLntsL7gk/edit#gid=0 listing all the pages under Web/API that use `var` .

We should replace usages of `var` with `const` or `let` as appropriate.

If you want to help, please add a comment here *and* request access to the spreadsheet. Once you have access:

- claim some pages by adding your name in the "Fixer" column
- file a PR to fix them. Please add a reference to this issue, but **don't** use "Fixes (this issue)" because that will auto-close this issue when he PR is merged.
- once you have filed a PR, add a link to the PR in the "PR" column
- once the PR is merged, add "Done" in the "Status" column

Note that:

- some of these examples are copied from examples in separate GitHub repositories. In these cases it would be great to update those repos as well, so the examples are the same in both places.
- our policy is to "[use `const` when we can, `let` when we have to](https://github.com/mdn/content/discussions/10389)".
- I'm happy to review other "modern JS" updates, like using `for...of` rather than `for`, and template literals, and arrow functions. But it's not needed at this point.

**Comment by suryanva** [comment]
Would love to help with few links as provided in the google sheet files, would add appropriate variable declaration using ES6.
Thank you.

**Comment by wbamberg** [comment]
Thank you @suryanva ! I added you to the sheet.

**Comment by gullapalli9482** [comment]
I would like to work on this.

**Comment by gullapalli9482** [comment]
Since I've been working on this, I would like to ask for access to the google sheet.
