### ISSUE TITLE
Issue with "Promise.race()": …

### ISSUE THREAD

**Issue by sanoodles** [mdn/content#1667]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race

#### What information was incorrect, unhelpful, or incomplete?

The example does not display the difference with Promise.any()

#### Specific section or headline?

The example

#### What did you expect to see?

The difference with Promise.any()

I suggest to put this example for Promise.race():

`
const promise1 = new Promise((resolve, reject) => {
  setTimeout(resolve, 500, 'one');
});

const promise2 = new Promise((resolve, reject) => {
  setTimeout(reject, 100, 'two');
});

Promise.race([promise1, promise2]).then((value) => {
  console.log('succeeded with value:', value);
}).catch((reason) => {
  console.log('failed with reason:', reason);
  // Only promise1 is fulfilled, but promise2 is faster
});
// expected output: "failed with reason: two"
`

And this example for Promise.any():

`
const promise1 = new Promise((resolve, reject) => {
  setTimeout(resolve, 500, 'one');
});

const promise2 = new Promise((resolve, reject) => {
  setTimeout(reject, 100, 'two');
});

Promise.any([promise1, promise2]).then((value) => {
  console.log('succeeded with value:', value);
  // Only promise1 is fulfilled, even though promise2 settled sooner
}).catch((reason) => {
  console.log('failed with reason:', reason);
});
// expected output: "succeeded with value: one"
`

#### Did you test this? If so, how?

I tested both examples on Firefox devtools' console.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise/race`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/promise/race/index.html
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by keiya01** [comment]
I want to take on this issue.

**Comment by chrisdavidmills** [comment]
@keiya01 assigned! Thank you for your offer of help, and please feel free to ask if you have any questions.

**Comment by wbamberg** [comment]
Fixed: https://github.com/mdn/content/pull/4432
