### ISSUE TITLE
Cannot load image from service worker cache

### ISSUE THREAD

**Issue by adis0308** [mdn/content#16676]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaMetadata/MediaMetadata

### What specific section or headline is this issue about?

Cannot load image from cache

### What information was incorrect, unhelpful, or incomplete?

The image is only displayed the first time the web page is loaded.

### What did you expect to see?

The cache image of the service worker should be displayed.

### Do you have any supporting links, references, or citations?

https://gdplayer.top/embed/06d0b9a2-1831-4fbd-8194-104a82def284

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mediametadata/mediametadata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaMetadata/MediaMetadata
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediametadata/mediametadata/index.md
* Last commit: https://github.com/mdn/content/commit/5dab39f73fb47dddd3ba1ad4259d222eb85864e7
* Document last modified: 2022-05-23T15:59:20.000Z

</details>

**Comment by sideshowbarker** [comment]
The scope of this issue tracker is limited to making changes to the content of MDN articles. Which MDN article would need to be changed in order for this issue to be resolved? Exactly which part of that article would need to be changed?
