### ISSUE TITLE
Complicated 1 sentence paragraph, that should be splitted into at least 3 sentences.

### ISSUE THREAD

**Issue by pmario** [mdn/content#16681]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

### What specific section or headline is this issue about?

[Why Use for...in?](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#why_use_for...in)

### What information was incorrect, unhelpful, or incomplete?

>Given that for...in is built for iterating object properties, not recommended for use with arrays, and options like Array.prototype.forEach() and for...of exist, what might be the use of for...in at all?

IMO this paragraph should contain 3 sentences. 

### What did you expect to see?

>Given that for...in is built for iterating object properties. It is not recommended for use with arrays, and options like Array.prototype.forEach()

The following part of the paragraph doesn't make any sense for me, in the "for...in" context. .. It seems to switch topic to a completely different function of array. ?!?

>and for...of exist, what might be the use of for...in at all?

---------

I have to say, that English isn't my native language. So shorter sentences are much easier to understand.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/for...in`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/for...in/index.md
* Last commit: https://github.com/mdn/content/commit/18c7b9ed2a009efd7974f0af41996b99895382ca
* Document last modified: 2022-04-27T19:48:38.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
How about formatting the clauses within the paragraph as a list; is this much easier to understand?

> Given that 
> - `for...in` is not recommended for use with arrays
> - `for...in` is built for iterating object properties, but other options exist
>     - `Object.keys(obj).forEach( … )`
>     - `for (key of Object.keys(obj)) { … }`
>
> What might be the use of `for...in`?

In my suggestion above, I have also made the indicated options more explicit (using `Object.keys`) to clarify their relevance.

**Comment by pmario** [comment]
I think, there should be a description, what it is used for. ... 

I think, it's OK to mention patterns that should _not_ be used, but they should be mentioned later in the list.

**Comment by Josh-Cena** [comment]
For context, the use of for...in is generally frowned upon today, because it's very likely a mistake where people confuse for...in and for...of. [`eslint-config-airbnb`](https://github.com/airbnb/javascript/blob/cbf9ade10a2f6f06c9da6dbfa25b344bee4bbef6/packages/eslint-config-airbnb-base/rules/style.js#L335-L338), [TS-ESLint](https://typescript-eslint.io/rules/no-for-in-array), and many other toolings ban it in favor of `Object.keys`.

**Comment by Andrew-Cottrell** [comment]
> I think it would be good to write the "new" paragraph here as an example. I can't really write a suggestion, since I already have an "issue" with the existing one.

If you'd like to have a go at writing a rough draft for replacing the [Why Use for...in?](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#why_use_for...in) section, then we could work on it together until it's a polished suggestion.

**Comment by Andrew-Cottrell** [comment]
> For context, the use of for...in is generally frowned upon today, because it's very likely a mistake where people confuse for...in and for...of. [`eslint-config-airbnb`](https://github.com/airbnb/javascript/blob/cbf9ade10a2f6f06c9da6dbfa25b344bee4bbef6/packages/eslint-config-airbnb-base/rules/style.js#L335-L338), [TS-ESLint](https://typescript-eslint.io/rules/no-for-in-array), and many other toolings ban it in favor of `Object.keys`.

Words to that effect should probably be mentioned somewhere on the [for...in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) page, maybe using a **Note** similar to that in the [Array iteration and for...in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#array_iteration_and_for...in) section.

**Comment by Josh-Cena** [comment]
This is _sort of_ already finger-pointed by that particular paragraph...
