### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by oxwilder** [mdn/content#16689]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/calc

### What specific section or headline is this issue about?

Specifications

### What information was incorrect, unhelpful, or incomplete?

Links to https://drafts.csswg.org/css-values/#calc-func (ignores bookmark obviously)

### What did you expect to see?

specifications for the css calc() function

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/calc`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/calc
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/calc/index.md
* Last commit: https://github.com/mdn/content/commit/f01246f406289c4c5222a5f340bcb8668118592a
* Document last modified: 2022-04-06T08:08:41.000Z

</details>

**Comment by sideshowbarker** [comment]
The drafts.csswg.org server gets wedged every few days. But every time, after somebody (re)reports it at https://github.com/w3c/csswg-drafts/issues/6528, the maintainer usually pretty quickly un-wedges it.
