### ISSUE TITLE
Add redirect for AMO Policies page

### ISSUE THREAD

**Issue by ekr** [mdn/content#16703]
### What specific section or headline is this issue about?

The AMO policies page has been moved to Extension Workshop (https://extensionworkshop.com/documentation/publish/add-on-policies/). The original page (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy) is still discoverable with some search engines (e.g. DDG) but giving a 404 error because it has no redirect.  

### What did you expect to see?

The link correctly redirects to Extension Workshop.

### Change required

 Add a redirect as per [these instructions](https://extensionworkshop.com/documentation/publish/add-on-policies/).

**Comment by sideshowbarker** [comment]
alerting @mdn/yari-content-mozilla-add-ons

**Comment by rebloor** [comment]
@ekr could you provide some more information, there isn't a link to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy on https://developer.mozilla.org/en-US/docs/MDN/Contribute/Feedback.

**Comment by ekr** [comment]
I found this by searching on DDG.

**Comment by rebloor** [comment]
The DDG indexing is out of date. That page was moved to https://extensionworkshop.com/documentation/publish/add-on-policies/ at least two years ago. However, there should also be a redirect created for the page but that appears to have been missed. I'm updating the title and description.

**Comment by Grace-00** [comment]
Hi @rebloor , I was working on this by providing the following redirect:
`/en-US/docs/Mozilla/Add-ons/AMO/Policy	https://extensionworkshop.com/documentation/publish/add-on-policies/`

By looking at the other redirects, it looks correct, yet locally, with the following URL `http://localhost:5042/en-US/docs/MDN/Add-ons/AMO/Policy/`, I still see no redirection.

I've checked this path` /en-US/docs/MDN/Add-ons/` and on it I can't seem to find any reference to AMO. 
`/en-US/docs/Mozilla/Add-ons/` seems to contain references to Themes and Extensions but no AMO.

**Comment by Grace-00** [comment]
Hi @rebloor , thanks a lot for your reply! Looking forward to my PR as well :D
This command `yarn content add-redirect /en-US/docs/Mozilla/Add-ons/AMO/policy https://extensionworkshop.com/documentation/publish/add-on-policies/ ` now returns the error:
`From-URL resolves to a file ($ARCHIVED/en-us/mozilla/add-ons/amo/policy/index.html)` . Any idea what this is about? Thanks.

**Comment by rebloor** [comment]
Does the redirect file get updated? The message doesn't look like an error, more a confirmation that there is indeed an archived page that you are creating a redirect for.

**Comment by Grace-00** [comment]
Nope, it doesn’t get updated.

**Comment by Josh-Cena** [comment]
Should have been fixed by #17285
