### ISSUE TITLE
There's practices that are being adviced which are not supported in HTML5

### ISSUE THREAD

**Issue by ARS-coding** [mdn/content#16721]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Test_your_skills:_HTML_accessibility

### What specific section or headline is this issue about?

HTML accessibility 1

### What information was incorrect, unhelpful, or incomplete?

The code that is being shown for the "Need help?" text shouldn't be a font tag since it isn't supported for the HTML5 spesification anymore.

I'm not really informed about the spesificationof HTML and I also didn't know there was a tag named font, so I searched for it and found that it's not supported anymore in HTML5 and wanted to report to you people.
This is the website that says it's nto supported on the HTML5: https://www.w3schools.com/tags/tag_font.asp

### What did you expect to see?

Probably a h2 or h1 would be more appropriate

### Do you have any supporting links, references, or citations?

https://www.w3schools.com/tags/tag_font.asp
https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Test_your_skills:_HTML_accessibility#html_accessibility_1

**Comment by wbamberg** [comment]
Thanks for filing! This is intentional, see the text introducing it:

> In this task we will test your understanding of text semantics, and why they are good for accessibility. The given text is a simple information panel with action buttons, **but the HTML is really bad**.
>
> **We want you to update it use appropriate semantic HTML**. You don't need to worry too much about recreating the exact same look and text sizing, as long as the semantics are good.
