### ISSUE TITLE
“The stacking context” doc: probably missing a link or more information on what is this "previously explained" bit means in that context

### ISSUE THREAD

**Issue by bappyasif** [mdn/content#16723]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

### What specific section or headline is this issue about?

"previously explained" could use some more info to convey a better semantics

### What information was incorrect, unhelpful, or incomplete?

i'm referring to this statement: 
> Within a stacking context, child elements are stacked according to the same rules previously explained

here "previously explained" doesn't really give any comprehensible (to me at least) information about which document or section it's referring to

### What did you expect to see?

it would be nice to see some more context about what it's referring to, as in perhaps: 
* a link to a different document, if applicable
* or a link of a subsection, if from same section

### Do you have any supporting links, references, or citations?

n/a

### Do you have anything more you want to share?

please have a look at my "what do you expect to see" section

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_positioning/understanding_z_index/the_stacking_context`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_positioning/understanding_z_index/the_stacking_context/index.md
* Last commit: https://github.com/mdn/content/commit/8504c291b3e71344e6b1f62db7edb780dde7195d
* Document last modified: 2022-05-18T18:41:26.000Z

</details>

**Comment by promet99** [comment]
I assume the rule is refering to this [Stacking without the z-index property](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_without_z-index) page of MDN docs, which is as following:
```
1. The background and borders of the root element
2. Descendant non-positioned blocks, in order of appearance in the HTML
3. Descendant positioned elements, in order of appearance in the HTML
```

Any other ideas?

**Comment by bappyasif** [comment]
i dont think, it's referring to "stacking context without z-index", rather what is already been "explained" in "bullet points" right above it

what i would say is to, have a better alternative use of words for "previously explained" to something more fitting, my suggestion would be: 
* rules explained just above
* explained in above scenarios

**Comment by promet99** [comment]
> i dont think, it's referring to "stacking context without z-index", rather what is already been "explained" in "bullet points" right above it
> 
> what i would say is to, have a better alternative use of words for "previously explained" to something more fitting, my suggestion would be:
> 
> * rules explained just above
> * explained in above scenarios

Are those bullet points rules? I thought it is a list of kinds of stacking contexts

**Comment by bappyasif** [comment]
> > i dont think, it's referring to "stacking context without z-index", rather what is already been "explained" in "bullet points" right above it
> > what i would say is to, have a better alternative use of words for "previously explained" to something more fitting, my suggestion would be:
> > 
> > * rules explained just above
> > * explained in above scenarios
> 
> Are those bullet points rules? I thought it is a list of kinds of stacking contexts

no, rules are already explained just above that paragraph

bullet points i used to suggest "probable use of words" to avert this issue :)
