### ISSUE TITLE
/en-US prototype inheritance doc contradiction 

### ISSUE THREAD

**Issue by stantoncbradley** [mdn/content#1673]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Conflicting info on prototype inheritance. First the docs say not to assign the `prototype` property directly, then later the example does just that.
url: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain

don't set `.prototype`
![image](https://user-images.githubusercontent.com/5314103/83045182-e2002980-a00a-11ea-9b58-713559eb757c.png)

later example sets `.prototype`
![image](https://user-images.githubusercontent.com/5314103/83045455-34414a80-a00b-11ea-81a0-2ff5e89f1749.png)

**Comment by jchimene** [comment]
I'll pick this up. 
For context, see [this msg on MDN web docs](https://matrix.to/#/!cGYYDEJwjktUBMSTQT:mozilla.org/$nbCDNh0i9llo_6nwuFlT8v_Kj-ADJtQK6PFkttFWY64?via=mozilla.org&via=matrix.org&via=resisty.com)

**Comment by Ryuno-Ki** [comment]
Thank you, @jchimene

**Comment by jchimene** [comment]
> Thank you, @jchimene

onward thru the fog!

**Comment by sideshowbarker** [comment]
> Was looking for an issue to pick up and I think this can be closed by #2747!

Thanks much @amyrlam — will close this out with a link to the associated commit

**Comment by sideshowbarker** [comment]
Fixed by 55715e8
