### ISSUE TITLE
The doc about iframe sandbox does not describe the effect of allow-same-origin on access to cookies

### ISSUE THREAD

**Issue by stof** [mdn/content#1674]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox describes that without `allow-same-origin`, the iframe is considered as being from a special origin failing same-origin policy. But it does not describe the effect of that change.
This sandbox restriction prevents access to storages (I found it for cookies in my case, I haven't checked localstorage and others), even when the iframe was already from a different origin.

It would be great if the doc could be more explicit on the impact.

**Comment by hamishwillee** [comment]
Thanks. I don't entirely agree because you can navigate through the links to get the detail. On the other hand, it doesn't hurt at all to say a few works here what might be affected (ie storage access and some script access). I've proposed a fix in #1696
