### ISSUE TITLE
Item is marked as deprecated with no mention of what should be used instead.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [mdn/content#16744]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-height

### What information was incorrect, unhelpful, or incomplete?

Media query features device-height, device-width and device-aspect-ratio are marked as deprecated, but there is no mention of what should be used in their place.

### What did you expect to see?

The recommended alternative syntax.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@media/device-height`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-height
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@media/device-height/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by wbamberg** [comment]
Do you think some version of the green note at https://drafts.csswg.org/mediaqueries/#mf-deprecated would be sufficient to fix this?

**Comment by Neutrino-Sunset** [comment]
I think that would be perfect.
