### ISSUE TITLE
ARIA FAQ page is outdated. Needs a rewrite

### ISSUE THREAD

**Issue by estelle** [mdn/content#16753]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Web_applications_and_ARIA_FAQ

### What specific section or headline is this issue about?

the entire document

### What information was incorrect, unhelpful, or incomplete?

References JS frameworks like Dojo, YUI.
"IE9 support is much improved."
No mention of Edge

### What did you expect to see?

Up to date content

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/accessibility/aria/web_applications_and_aria_faq`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Web_applications_and_ARIA_FAQ
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/web_applications_and_aria_faq/index.html
* Last commit: https://github.com/mdn/content/commit/0ed90ef0783f8c716e76e78b6b4b92000fb494e2
* Document last modified: 2022-04-26T06:21:16.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed via https://github.com/mdn/content/pull/19052
