### ISSUE TITLE
Missing description of controlsList attribute

### ISSUE THREAD

**Issue by aniWeyn** [mdn/content#16768]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

### What information was incorrect, unhelpful, or incomplete?

This article is missing controlsList="nodownload noplaybackrate"

Tested, it is working (the options are displayed only in Chrome).

### What did you expect to see?

One paragraph about controlList 

### Do you have anything more you want to share?

sorry, I don't have a moment to write the paragraph! 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/audio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/audio/index.md
* Last commit: https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e
* Document last modified: 2022-05-17T13:23:31.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #20423 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
