### ISSUE TITLE
Bad/misleading example in microtask guide

### ISSUE THREAD

**Issue by pelme** [mdn/content#16766]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide

### What specific section or headline is this issue about?

Microtask from a function

### What information was incorrect, unhelpful, or incomplete?

The example is used to show that a microtask is executed before a setTimeout call by scheduling a callback with setTimeout. The last line in the example `log("Regular timeout callback has run");` (after `log("Main program exiting");`) is misleading.

### What did you expect to see?

It would be clearer if the last line of the code was removed to avoid the duplicated log message. The full code would then be:

```js
let callback = () => log("Regular timeout callback has run");

let urgentCallback = () => log("*** Oh noes! An urgent callback has run!");

let doWork = () => {
  let result = 1;

  queueMicrotask(urgentCallback);

  for (let i=2; i<=10; i++) {
    result *= i;
  }
  return result;
};

log("Main program started");
setTimeout(callback, 0);
log(`10! equals ${doWork()}`);
log("Main program exiting");
```

and the result:

```
Main program started
10! equals 3628800
Main program exiting
*** Oh noes! An urgent callback has run!
Regular timeout callback has run
```

### Do you have any supporting links, references, or citations?

This was changed in #11173. The intention of that change was good but I think rather the solution should have been to correct the result section (remove the bad output line).

**Comment by pelme** [comment]
For clarification, this comment: https://github.com/mdn/content/issues/11173#issuecomment-993201256 argues for the same solution I do in this issue 🙂

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/17433
