### ISSUE TITLE
Issue with "WebSocket": …

### ISSUE THREAD

**Issue by aelmosalamy** [mdn/content#1681]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

#### What information was incorrect, unhelpful, or incomplete?
Events navigation link in the left sidebar (under Related topics)

#### Specific section or headline?
Related Topics > Events

#### What did you expect to see?
Expected to see 2 more events "open" and "close", which are mentioned in the page itself but are missing from the sidebar,

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/websocket`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/websocket/index.html
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened #1682 with a fix.

**Comment by aelmosalamy** [comment]
Thanks buddy, it took me some time &mdash; and confidence, to follow my gut over the glorious MDN Web Docs :)
