### ISSUE TITLE
The article for `document.write()` should be more discouraging

### ISSUE THREAD

**Issue by mozfreddyb** [mdn/content#16852]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/write

### What specific section or headline is this issue about?

This is about the top-level warning box.

### What information was incorrect, unhelpful, or incomplete?

The info itself is not technically incorrect.

### What did you expect to see?

 It could need stronger wording that discourages the usage of it. 

### Do you have any supporting links, references, or citations?

See also https://github.com/whatwg/html/issues/7977, which says that it should be discouraged more strongly in the HTML spec

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document/write`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/write
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/write/index.md
* Last commit: https://github.com/mdn/content/commit/37f38ac4b337174d6b7ccf3fc08b1ac66c5a9fcd
* Document last modified: 2022-05-31T04:29:22.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #16854 with a change which adds a prominent warning to the page.
