### ISSUE TITLE
Issue with "USBConfiguration": …

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#1686]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/USBConfiguration

#### What information was incorrect, unhelpful, or incomplete?

In the initial paragraph, the link to WebUSB API is broken (404).

#### Specific section or headline?

> The USBConfiguration interface of the WebUSB API provides information about a particular configuration of a USB device and the interfaces that it supports.

#### What did you expect to see?

Closest I could find is https://developer.mozilla.org/en-US/docs/Web/API/USB (which also links to WebUSB API with the same address)

#### Did you test this? If so, how?

I clicked on https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/usbconfiguration`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/USBConfiguration
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/usbconfiguration/index.html
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by chrisdavidmills** [comment]
Note to whoever fixes this; the https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API API landing page needs to be created, with the same kind of structure as https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API.

**Comment by sideshowbarker** [comment]
The https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API page has since been created, so I’m going ahead and closing this as resolved.
