### ISSUE TITLE
Typo in content: /ru/docs/Web/JavaScript/Reference/Classes

### ISSUE THREAD

**Issue by asssc** [mdn/content#1687]
Page - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Classes

Misspelled sentence: "Как видно из примера, поля могут быть объявлены как **со** начальным значением, так и без него."
Right sentence: "Как видно из примера, поля могут быть объявлены как **с** начальным значением, так и без него."

**Comment by Ryuno-Ki** [comment]
Thank you.
Sadly, translations are currently frozen.
Please check https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for details.
I'm going to close this issue now.
