### ISSUE TITLE
Tip for setting the MONGODB_URI variable

### ISSUE THREAD

**Issue by LizardWizard69** [mdn/content#16886]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment

### What specific section or headline is this issue about?

Setting configuration variables

### What information was incorrect, unhelpful, or incomplete?

When setting the MONGODB_URI variable,  characters like (@, &, ...) inside string variables have to be escaped using the %40, %26 notation (HTML URL Encode). Note that the characters that separate the string must be kept as is. For example, the string 
`>heroku config:set MONGODB_URI=mongodb+srv://cooluser:**coolp@ssword**@cluster0-mbdj7.mongodb.net/local_library?retryWrites=true?w=majority` has to be written as 
`>heroku config:set MONGODB_URI=mongodb+srv://cooluser:**coolp%40ssword**@cluster0-mbdj7.mongodb.net/local_library?retryWrites=true&w=majority`

### What did you expect to see?

Just a note mentionning this issue. I think it is quite common to have special characters, especially in passwords. :) 

### Do you have any supporting links, references, or citations?

At the veeeery end of the page, a small note concerning this issue is mentionned.
https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-atlas-cluster

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/deployment/index.md
* Last commit: https://github.com/mdn/content/commit/84e27d238a5e2228a4ebdd022ccac45c3614b8fc
* Document last modified: 2022-05-11T04:57:38.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @LizardWizard69 - that's a good catch. Fixed in #16920 by extending the note about the fact that on some OS you might need to put quotes around the string.
