### ISSUE TITLE
Hoisting concept for let and const varies across pages

### ISSUE THREAD

**Issue by shaikwasef** [mdn/content#16882]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Hoisting#let_and_const_hoisting

### What specific section or headline is this issue about?

Information is incorrect

### What information was incorrect, unhelpful, or incomplete?

The concept of hoisting is incorrectly discussed across various pages on the mdn docs .

The following article says that let and var are hoisted (which is the case) - Updated in April , 2022
https://developer.mozilla.org/en-US/docs/Glossary/Hoisting#let_and_const_hoisting

But , the other article says that let and var are not hoisted - Updated May , 2022
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_lexical_declaration_before_init

### What did you expect to see?

The correct necessary changes be made .

**Comment by wbamberg** [comment]
Drive-by, but also, the glossary page for Hoisting is much too long. Glossary pages are not guide pages.

**Comment by hamishwillee** [comment]
Fixed error in the error doc #16922 

The glossary being too long is a good point, but it is not this issue. I have raised https://github.com/mdn/content/issues/16923 for  that.
