### ISSUE TITLE
Issue with "TouchList": …

### ISSUE THREAD

**Issue by strarsis** [mdn/content#1689]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TouchList

#### What information was incorrect, unhelpful, or incomplete?
Safari seems to support this feature:
https://developer.apple.com/documentation/webkitjs/touchevent/1632803-targettouches

#### Specific section or headline?
[Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/API/TouchList#browser_compatibility)

#### What did you expect to see?
That Safari supports this feature, too.

#### Did you test this? If so, how?
Deduced this from the documentation by Apple.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/touchlist`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TouchList
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/touchlist/index.html
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@strarsis I'd kindly ask you to fill an issue against mdn/browser-compat-data to update

https://github.com/mdn/browser-compat-data/blob/26dd8f364aafbf822ca5f4bb46bce71c16df0998/api/TouchList.json#L37-L39

with this info. If you cannot do that, someone from the team will pick it up, so no worries :-)

**Comment by strarsis** [comment]
@Ryuno-Ki: PR added: https://github.com/mdn/browser-compat-data/pull/8848
