### ISSUE TITLE
Practice code fails to execute due to Content Security Policy

### ISSUE THREAD

**Issue by CutlerSheridan** [mdn/content#16904]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises

### What specific section or headline is this issue about?

All sections starting with "Using the fetch() API"

### What information was incorrect, unhelpful, or incomplete?

The lesson invites the user to copy and paste the lesson's various example code blocks into the browser's JS console to see the results for yourself, but the URL to the json file/s being fetched in every example are automatically blocked by MDN's Content Security Policy, thus it's impossible to follow along with any of the demonstrations.

<img width="351" alt="Screen Shot 2022-06-02 at 1 14 17 PM" src="https://user-images.githubusercontent.com/43424003/171730061-bc526e8e-a610-451e-9b60-e96d3a8f636f.png">
.

### What did you expect to see?

The expected console output is:

```
Promise { <state>: "pending" }
Started request...
Received response: 200
```

### Do you have any supporting links, references, or citations?

I'm using Chrome on a 2018 Macbook Pro running macOS 11.1

### Do you have anything more you want to share?

To reproduce, simply copy any of the example code into the browser's JS console and press enter.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/promises/index.md
* Last commit: https://github.com/mdn/content/commit/ea032ab86280848d3842a7e4455b831ea2545603
* Document last modified: 2022-03-15T02:11:20.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

Can you confirm that you followed the instructions in the blue note at https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises#using_the_fetch_api, to paste the instructions into the console when you are at https://example.org ?

This works for me (running the same code from developer.mozilla.org doesn't).

**Comment by CutlerSheridan** [comment]
...I'm sorry.  I think of myself as someone who's good at reading instructions.  But no, I was not on https://example.org, I was on developer.mozilla.org.  Works fine now, thank you for pointing that out.

**Comment by wbamberg** [comment]
No worries @CutlerSheridan . It is a bit confusing.
