### ISSUE TITLE
Broken internal link on page "Cross-Origin Resource Sharing (CORS)": …

### ISSUE THREAD

**Issue by akaustav** [mdn/content#1690]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

#### What information was incorrect, unhelpful, or incomplete?
There is a broken inter-page link from an Information/Note block (blue background) above the section titled **Preflighted requests** to **Credentialed requests and wildcards** sub-section under the **Requests with credentials** section.

#### Specific section or headline?
Information/Note (blue background) block above the section titled **Preflighted requests**.

#### What did you expect to see?
To navigate to **Credentialed requests and wildcards** sub-section under the **Requests with credentials** section.

#### Did you test this? If so, how?
Yes. Steps to reproduce:
1. Navigate to the page at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
2. Scroll down to the Information/Note block (with blue background) which starts with:
   > **Note:** When responding to a [credentialed requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#credentialed_requests_and_wildcards) request, the server must specify an origin in the value of the `Access-Control-Allow-Origin` header, instead of specifying the "`*`" wildcard.
3. Click on the [credentialed requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#credentialed_requests_and_wildcards) link in this block.
4. Notice the URL changes to <https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#credentialed_requests_and_wildcards>

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/cors/index.html
* Document last modified: 2021-01-15T13:22:56.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this and reporting it — I’ve opened #1695 with a fix
