### ISSUE TITLE
Warning box not needed for KeyframeEffect.composite

### ISSUE THREAD

**Issue by jensimmons** [mdn/content#16910]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/KeyframeEffect/composite#browser_compatibility

### What specific section or headline is this issue about?

The warning box at the top of the page

### What information was incorrect, unhelpful, or incomplete?

As I pitched in another recent issue, I don't believe the warning boxes labeling certain technology as "too soon to use" are helpful to web developers. This one is out of date. 

> Experimental: This is an [experimental technology](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Conventions_definitions#experimental)
> Check the [Browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/KeyframeEffect/composite#browser_compatibility) carefully before using this in production.

KeyframeEffect.composite works everywhere except IE and Safari 15 and older. It has shipped in Safari Technology Preview. 

### What did you expect to see?

To be able to read the content without being warned against using it.

**Comment by hamishwillee** [comment]
You're absolutely right. MDN should follow the compatibility table here. I'll tidy that.

**Comment by hamishwillee** [comment]
Thanks for reporting. Done in #16921 - also fixed the other parts that were incorrectly tagged.

FYI, feel free to make the changes yourself - pretty much you can match whatever the browser compatibility indicates. BCD should unset the value once it is implemented by more than 2 browser engines.
