### ISSUE TITLE
Wrong name of the month in Date.setMonth() documentation's example.

### ISSUE THREAD

**Issue by jpgmoreira** [mdn/content#16916]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMonth

### What specific section or headline is this issue about?

Last paragraph of description.

### What information was incorrect, unhelpful, or incomplete?

Where it says "if the current value is 31st August 2016", it should probably be "if the current value is 31st January 2016".

### What did you expect to see?

January instead of August.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMonth

### Do you have anything more you want to share?

No

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/setmonth`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMonth
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/setmonth/index.md
* Last commit: https://github.com/mdn/content/commit/c1b22c814668f2b00d189b891b2685d93dce1354
* Document last modified: 2022-05-22T22:35:34.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks! Fixed by #16917
