### ISSUE TITLE
[Web API] Implement Transferrable Streams (Nightly)

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#16930]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

I think this is just 
- experimental features plus 
- check the methods are documented, and list that they are transferrable, and are cross linked from transferrable objects.
- BCD

These are other things to check (which it might affect)
-  [structuredClone()](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) structured clone
- [Window.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)/[Worker.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage)
- [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream)
- [WritableStream](https://developer.mozilla.org/en-US/docs/Web/API/WritableStream)
- [TransformStream](https://developer.mozilla.org/en-US/docs/Web/API/TransformStream)

Might also affect docs:
- [Transferable objects](https://developer.mozilla.org/en-US/docs/Glossary/Transferable_objects)

We'll also need to add this to BCD in same way as for [RTCDataChannel](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel)

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1659025

## Other

Nightly only in FF102 - not a release. Behind pref `dom.streams.transferable.enabled`

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/16525
- [ ] Docs
- [ ] Experimental features
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
Looks good to me - thank you so much @hamishwillee !
