### ISSUE TITLE
Deprecation notice in "WorkerGlobalScope.close()" is misleading.

### ISSUE THREAD

**Issue by Kaiido** [mdn/content#1694]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/close

#### What information was incorrect, unhelpful, or incomplete?
The `close()` method is marked as being deprecated.

#### Specific section or headline?
The deprecation notice.

#### What did you expect to see?
A note explaining that this method has been moved to each specific type of worker global scopes.  
When falling on this page users might think that they can't use this method in a DedicatedWorker (which is the most common Worker type), while, instead of a true deprecation what happened here is that this method has been moved on other interfaces.  
However this change is transparent to users and thus I believe this notice is misleading ([example of someone who got it wrong](https://stackoverflow.com/questions/65875453/how-to-stop-js-web-worker-from-within/65877757)).

At the very least it should say that [Dedicated](https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/close) and [Shared](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorkerGlobalScope/close) workers global scopes still have this method defined.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/workerglobalscope/close`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/close
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/workerglobalscope/close/index.html
* Document last modified: 2021-01-20T20:24:12.000Z

</details>

**Comment by himanshugarg** [comment]
The page now redirects to [DedicatedWorkerGlobalScope.close()](https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/close) so there is none to fix. Anything else remains here?

**Comment by Kaiido** [comment]
Everything looks fine to me, closing this issue and thanks for noticing it's been fixed already.
