### ISSUE TITLE
 Error in parsing value for 'transform'.  Declaration dropped. 2 RE4AwX2:3:25

### ISSUE THREAD

**Issue by Bchris251** [mdn/content#16974]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length

### What specific section or headline is this issue about?

 Error in parsing value for 'transform'.  Declaration dropped. 2 RE4AwX2:3:25

### What information was incorrect, unhelpful, or incomplete?

 Error in parsing value for 'transform'.  Declaration dropped. 2 RE4AwX2:3:25
[NVIDIA System Information 05-29-2022 14-30-36.txt](https://github.com/mdn/content/files/8837937/NVIDIA.System.Information.05-29-2022.14-30-36.txt)

### What did you expect to see?

 Error in parsing value for 'transform'.  Declaration dropped. 2 RE4AwX2:3:25
[NVIDIA System Information 05-30-2022 14-44-49.txt](https://github.com/mdn/content/files/8837939/NVIDIA.System.Information.05-30-2022.14-44-49.txt)
[NVIDIA System Information 05-30-2022 14-44-52.txt](https://github.com/mdn/content/files/8837940/NVIDIA.System.Information.05-30-2022.14-44-52.txt)

### Do you have anything more you want to share?

 Error in parsing value for 'transform'.  Declaration dropped. 2 RE4AwX2:3:25

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-length`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-length/index.md
* Last commit: https://github.com/mdn/content/commit/303a6c3b8ec6658d2956c191c50aee0a0e9e4da5
* Document last modified: 2022-02-18T09:30:25.000Z

</details>

**Comment by teoli2003** [comment]
Closing, spam-like issue.
