### ISSUE TITLE
tag <body> deprecated attributes

### ISSUE THREAD

**Issue by j67Sv89n** [mdn/content#16976]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body

### What specific section or headline is this issue about?

about Trash icon

### What information was incorrect, unhelpful, or incomplete?

Hello,
I'm interested to know,
html <body> tag no longer has attributes?
they are implemented through the CSS now?
Thank you.

### What did you expect to see?

I want an answer to a question, thank you.

### Do you have any supporting links, references, or citations?

[https://i.postimg.cc/7hSYcgw0/body-tag-r.jpg]

**Comment by teoli2003** [comment]
The text right below these attributes clearly indicates that these attributes are deprecated and should be replaced by CSS.

But there are attributes that still exist and are valid for `<body>`, you'll find some of them by clicking the _global attributes_ link.
