### ISSUE TITLE
List of unsupported properties would be great

### ISSUE THREAD

**Issue by inspector71** [mdn/content#16994]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties

### What information was incorrect, unhelpful, or incomplete?

Rather than requiring users to scan through a long list of properties supported by `transition`, then assume the property they might want to animate, such as `position`, if not listed, is not support, could there be a presumably shorter list of **unsupported** properties at the top of the page? 

After all, how often to users come to this page with the question "why is this thing I'm trying to achieve **not** working?" ... as opposed to "oooh, let's learn what IS possible (and someone remember the handful of properties not supported by exclusion of the properties that ARE supported)" ?

### What did you expect to see?

'Both sides of the coin': Support AND unsupported properties.

### Do you have anything more you want to share?

I'd do this myself and submit a pull request but I wouldn't know where to get a formal list of what CSS properties exist, then subtract what is NOT supported from what IS supported. I'm presuming this is not a problem for people more on the inside of the browser / CSS industry. Hopefully it can even be automated?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_animated_properties`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_animated_properties/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by teoli2003** [comment]
To answer the question "Does the property xyz supports animation or not, you should go to the page about xyz and, there, you have the information about animation of xyz (in the summary table)

**Comment by estelle** [comment]
Adding a `>**Note:**` on where to find the data on the individual pages would be helpful, and wouldn't need to be continuously updated. 
the information can be found in each property's #formal_definition section.
though we may need to define discrete, etc.

**Comment by dipikabh** [comment]
The [spec](https://www.w3.org/TR/web-animations/#concept-animatable) says (in a note):

> For example, properties defining animation parameters are [not animatable](https://www.w3.org/TR/web-animations/#not-animatable) since doing so would create complex recursive behavior.

On MDN, the 'Animation type' value for animation properties such as [`animation-direction`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-direction#formal_definition) and [`animation-delay`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-delay#formal_definition) is listed as `discrete`.

However, the spec does say they are `not animatable`: https://drafts.csswg.org/css-animations/#animation-direction and https://drafts.csswg.org/css-animations/#animation-delay. I'll open a separate PR to update their "Formal definition" sections.
