### ISSUE TITLE
Missed braces in Constructor instantiation in Examples

### ISSUE THREAD

**Issue by KoushilM** [mdn/content#17027]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/encodeInto

### What specific section or headline is this issue about?

Encode into a specific position, No Zero-Termination, 

### What information was incorrect, unhelpful, or incomplete?

Missed braces in TextEncoder Constructor instantiation in Examples.

### What did you expect to see?

Currently wrongly specfied:
new TextEncoder

It Should be like:
new TextEncoder()

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/encodeInto#encode_into_a_specific_position

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/textencoder/encodeinto`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/encodeInto
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/textencoder/encodeinto/index.md
* Last commit: https://github.com/mdn/content/commit/c27bad0d78568f4b8b4b15dfb476f86b597717b7
* Document last modified: 2022-06-02T19:19:04.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #17028 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
