### ISSUE TITLE
Typo in “Using channel messaging” doc

### ISSUE THREAD

**Issue by KoushilM** [mdn/content#17024]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API/Using_channel_messaging

### What specific section or headline is this issue about?

Simple examples

### What information was incorrect, unhelpful, or incomplete?

To get your started,

### What did you expect to see?

To get you started,

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/channel_messaging_api/using_channel_messaging`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API/Using_channel_messaging
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/channel_messaging_api/using_channel_messaging/index.md
* Last commit: https://github.com/mdn/content/commit/be4efd7240ce9da3209d9a26a7b023e9b51ed54a
* Document last modified: 2022-06-05T00:37:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #17026 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
