### ISSUE TITLE
Typo in MediaKeyStatusMap

### ISSUE THREAD

**Issue by KoushilM** [mdn/content#17029]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaKeyStatusMap

### What specific section or headline is this issue about?

Properties

### What information was incorrect, unhelpful, or incomplete?

In the description of MediaKeyStatusMap.size.

There is a typo in the below statement. ("Pars" => "Pairs")

Returns the number of key/value pars in the status map.

### What did you expect to see?

Typo Mistake

There is a typo in the below statement. ("Pars" => "Pairs")

Returns the number of key/value pars in the status map.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/MediaKeyStatusMap

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mediakeystatusmap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaKeyStatusMap
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediakeystatusmap/index.md
* Last commit: https://github.com/mdn/content/commit/c1f8207fa145db27da55bf832c85a63aeb7d24b7
* Document last modified: 2022-06-01T05:12:48.000Z

</details>

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:
