### ISSUE TITLE
missing description of sectionRowIndex 

### ISSUE THREAD

**Issue by sergey-titov** [mdn/content#17038]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableRowElement

### What specific section or headline is this issue about?

Properties

### What information was incorrect, unhelpful, or incomplete?

Neither description nor mention of sectionRowIndex property

### What did you expect to see?

Description for sectionRowIndex property

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/2011/WD-html5-author-20110809/the-tr-element.html#dom-tr-sectionrowindex
https://caniuse.com/?search=sectionRowIndex

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmltablerowelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableRowElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmltablerowelement/index.md
* Last commit: https://github.com/mdn/content/commit/4578142fe33d01a3132d77a23fd2a7356fae2995
* Document last modified: 2022-06-01T04:19:41.000Z

</details>

**Comment by sideshowbarker** [comment]
At https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableRowElement#htmltablerowelement.sectionrowindex the article already documents `sectionRowIndex` with this description:

> Returns a `long` value which gives the logical position of the row within the table section it belongs to. If the row is not part of a section, returns `-1`.

So I’m going ahead and closing this issue. But if I’ve misunderstood something, please comment, and this issue could be revisited.
