### ISSUE TITLE
Sentence Correction

### ISSUE THREAD

**Issue by KoushilM** [mdn/content#17031]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper_API

### What specific section or headline is this issue about?

EyeDropper API

### What information was incorrect, unhelpful, or incomplete?

Sentence has a missing word

### What did you expect to see?

In the below sentence we need to add "collect" word

The EyeDropper API provides a mechanism for creating an eyedropper tool. Using this tool, users can sample colors from their screens, including outside of the browser window.

It should be 

The EyeDropper API provides a mechanism for creating an eyedropper tool. Using this tool, users can collect sample colors from their screens, including outside of the browser window.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper_API

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/eyedropper_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/eyedropper_api/index.md
* Last commit: https://github.com/mdn/content/commit/196cc4ff3068a59b962a3fe1cbb960eb72ef542b
* Document last modified: 2022-05-31T04:47:00.000Z

</details>

**Comment by sideshowbarker** [comment]
In the existing sentence, the word _“sample”_ is used as a verb, right? _“users can sample colors from their screens”_. So the existing sentence is not ungrammatical or incorrect in any other way. And changing it to _“users can collect sample colors from their screens”_ doesn’t seem like an improvement. The existing sentence seems better as-is.

**Comment by wbamberg** [comment]
Closing per https://github.com/mdn/content/issues/17031#issuecomment-1148040373.
