### ISSUE TITLE
/en-US/docs/Web/API/HTMLMediaElement/srcObject

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#1704]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The page says this:
Note: As of March 2020, only Safari supports setting objects other than MediaStream.

But, would "Example: Fetch & Play" on https://developers.google.com/web/updates/2017/06/play-request-was-interrupted mean that Chrome supports Blob?

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Investigate whether other browser implementations now support setting objects
* If yes update BCD
* If yes update the information on the page accordingly (probably remove/update note)

**Comment by dontcallmedom** [comment]
I've checked that `srcObject = blob` still fails in both Firefox and Chrome, although it works in Safari and fixed the WPT test that allows to verify it https://github.com/web-platform-tests/wpt/pull/28727

I've filed a pull request to link to the relevant Chromium and Firefox bugs from the BCD data https://github.com/mdn/browser-compat-data/pull/10147

I believe this issue can be fixed as no change is needed in the said MDN page at this time.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/1704#issuecomment-828578541
