### ISSUE TITLE
SVG Tutorial discussed strokes and fills without paint-order

### ISSUE THREAD

**Issue by deanrrio** [mdn/content#17040]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes

### What specific section or headline is this issue about?

Discussing strokes without paint-order

### What information was incorrect, unhelpful, or incomplete?

The article is great, except it lacks details on paint-order.

See the following and very thorough answer on StackOverflow:
https://stackoverflow.com/a/70013225/13468777

And the MDN article:
https://developer.mozilla.org/en-US/docs/Web/CSS/paint-order

### What did you expect to see?

Some coverage of paint-order

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/a/70013225/13468777

https://developer.mozilla.org/en-US/docs/Web/CSS/paint-order

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/tutorial/fills_and_strokes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/tutorial/fills_and_strokes/index.md
* Last commit: https://github.com/mdn/content/commit/614cd623fac41cbc68c54ef33b82dd4d5ebb04f7
* Document last modified: 2022-02-04T07:16:02.000Z

</details>

**Comment by bsmth** [comment]
Hi @deanrrio, thanks for opening this one. I'll take a look at improving this section.
