### ISSUE TITLE
Document form-associated custom elements

### ISSUE THREAD

**Issue by andreubotella** [mdn/content#1705]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [X] New documentation
- [ ] Correction or update

# Details

[Form-associated custom elements](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-face-example) ("FACEs") were merged into the HTML standard on [May 2019](https://github.com/whatwg/html/pull/4383) and implemented in [Chrome 77](https://bugs.chromium.org/p/chromium/issues/detail?id=905922). Despite that, MDN doesn't yet cover the APIs this feature introduces ([`ElementInternals`](https://html.spec.whatwg.org/multipage/custom-elements.html#elementinternals) doesn't have a page, and [`HTMLElement.prototype.attachInternals()`](https://html.spec.whatwg.org/multipage/custom-elements.html#dom-attachinternals) only shows up as an experimental API), let alone include them or their callbacks in the ["Using custom elements"](https://wiki.developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) page.

**Comment by rachelandrew** [comment]
I am currently working on the ElementInternals documentation, and will pick up the other bits as I go.
