### ISSUE TITLE
Misleading Object.constructor definition

### ISSUE THREAD

**Issue by GeorgeBrn** [mdn/content#17061]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor

### What specific section or headline is this issue about?

"The constructor property returns a reference to the Object constructor function that created the instance object."

### What information was incorrect, unhelpful, or incomplete?

If we log a constructor function directly to the console, we get something like this:

{constructor: ƒ}
constructor: ƒ (firstName, birthYear)
[[Prototype]]: Object

In the way the article is written right now, it could imply that this constructor property contains the prototype that was used in creating the instance we are currently viewing. Meaning this constructor property contains the constructor function which is itself??

It should be made more clear that this constructor function property contains the prototype property which will become the prototype of the instances it creates, not itself.

It's made more clear in the next paragraph:

"Any object (with the exception of objects created with Object.create(null)) will have a constructor property on its [[Prototype]]."

So the constructor property is the prototype of the instance we are viewing, only if it's inside in it's [[prototype]], which is correct! But on the first paragraph this condition isn't mentioned at all, and it is all very confusing. 

### What did you expect to see?

I expected to see exactly what the "constructor" property contains and what it is.

I would want to see a full article on every single thing we see on the console when we log an object. Currently there's not a good explanation on what the [[prototype]] is and what this property contains, on what the constructor property is, on the fact that the prototype property is inside the constructor function property

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/constructor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/constructor/index.md
* Last commit: https://github.com/mdn/content/commit/e96daeb62fc8abf41a4dccf0dbca9c21a5a9e571
* Document last modified: 2022-05-27T05:19:46.000Z

</details>

**Comment by Josh-Cena** [comment]
The term "prototype" is pretty ambiguous in JavaScript.

```js
function Person() { this.age = 1; }
const p = new Person;
```

Here we are talking about the `constructor` of the instance `p`, not the `constructor` of `Person`. The opening sentence is saying that `p.constructor === Person`.

I'd be willing to clarify on this page (already did a lot of clarification around prototype chains recently), but I'm not sure exactly what needs to be changed. Could you give a code example, and compare what that sentence makes you think it would print, versus what it actually prints?

**Comment by GeorgeBrn** [comment]
I figured that that article is only about the .constructor method and not
about constructor functions in general ( found here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor).
Sorry for the misunderstanding.

**Comment by Josh-Cena** [comment]
It's about the constructor property—which always happens to be a function/class.

**Comment by sideshowbarker** [comment]
I’m going ahead and closing this per https://github.com/mdn/content/issues/17061#issuecomment-1148775164 — but if there’s still a change here that should be made, we can revisit this.
