### ISSUE TITLE
How to stretch an background image to completely cover the viewport without cropping?

### ISSUE THREAD

**Issue by WDGroll** [mdn/content#1706]
In earlier versions of Firefox it was possible to completely cover the background of the viewport with an image by scaling width and height independently to 100% of the viewports dimensions regardless of the images own propotions.
```
	background-image:url("../img/Bkgnd/Bkgnd.svg");
	background-repeat: no-repeat;
	background-size: 100vw 100vh;

```
This does not work any more, actually the scaling maintains the proportions of the image, leaving uncovered bars either on top and bottom or on the sides of the image, depending on the aspect ratio of the viewport.

So, what is the correct CSS directive to regain the full coverage of the viewport with an image again? Without cropping parts of the image like 'cover' does?

![Bildschirmfoto_2020-04-25_11-47-13](https://user-images.githubusercontent.com/23437854/80276686-96e0b700-86ea-11ea-8d8a-994f5c52afd9.png)
![Bildschirmfoto_2020-04-25_11-46-15](https://user-images.githubusercontent.com/23437854/80276687-97794d80-86ea-11ea-951e-4198c1540403.png)

**Comment by chrisdavidmills** [comment]
I wonder if @rachelandrew has an idea about a solution for this one?

**Comment by Ryuno-Ki** [comment]
>  According to this, 100vw and 100vh should be exactly the size of the viewport.

I was about to suggest just this.

Is this about applying a user stylesheet (which would apply to all webpages) or only for a specific website (htdocs/index.html makes me think of a locally running Apache web server).

**Comment by rachelandrew** [comment]
Seems to work fine with an image, so I'm not sure why not with the SVG.

https://codepen.io/rachelandrew/pen/cb98439b1f485cd33c55a582da973dd4

**Comment by rachelandrew** [comment]
Oh. I just had a thought.

You need `preserveAspectRatio="none" on your SVG.

https://codepen.io/rachelandrew/pen/6be905fc1f68875f5d8ac64c5ce06c0a

@chrisdavidmills @WDGroll

**Comment by chrisdavidmills** [comment]
@rachelandrew nice, thanks Rachel!

**Comment by rachelandrew** [comment]
I was trying to see where this info could be added, and found this: https://developer.mozilla.org/en-US/docs/Web/CSS/Scaling_of_SVG_backgrounds

So maybe I'll add it as a note.
