### ISSUE TITLE
Content suggestion: `complex-selector-list`

### ISSUE THREAD

**Issue by estelle** [mdn/content#17080]
Both `:not()` and `:is()` accept `<complex-selector-list>` as a parameter. but this term isn't defined anywhere on MDN.

https://www.w3.org/TR/selectors-4/#grammar

 ## What is the new suggestion?

**Comment by bsmth** [comment]
It looks like we have something under https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors#structure_of_a_selector

Does that close the issue? Maybe we can link to this definition from the `:not()` and `:is()` pages to fix this.
