### ISSUE TITLE
Issue with "handler.construct()": …

### ISSUE THREAD

**Issue by dipamsen** [mdn/content#1710]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/construct

#### What information was incorrect, unhelpful, or incomplete?
In the Interceptions listed under the Description for the Proxy handler - `construct()` method, it shows that the construct trap can intercept `new Proxy(...args)` Proxy constructor calls, which is incorrect.

#### Specific section or headline?
Description > Interceptions > First Bullet Point

#### What did you expect to see?
In reality, the `construct` method is a trap to the JavaScript `new` operator on the **Proxy object created** (`proxy`), and not the actual JavaScript built in `Proxy`. So it should be
```
## Interceptions
This trap can intercept these operations:

* new proxy(...args)
* Reflect.construct()
```

#### Did you test this? If so, how?
N.A.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/proxy/proxy/construct`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/construct
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/proxy/proxy/construct/index.html
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by Elchi3** [comment]
Thanks for your report! I'm addressing this in https://github.com/mdn/content/pull/1805 to say "myFunction" instead so that it is not confusing this with the built-in `Proxy` for no reason.
