### ISSUE TITLE
fetch could reject when 400 is returned

### ISSUE THREAD

**Issue by jlucartc** [mdn/content#17115]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/fetch

### What specific section or headline is this issue about?

Introduction and "Exceptions". At "Exceptions", the part about TypeError and the table listing all the reasons for it to happen. I didn't find anything that could justify my results in that list.

### What information was incorrect, unhelpful, or incomplete?

> A [fetch()](https://developer.mozilla.org/en-US/docs/Web/API/fetch) promise only rejects when a network error is encountered (which is usually when there's a permissions issue or similar). A [fetch()](https://developer.mozilla.org/en-US/docs/Web/API/fetch) promise does not reject on HTTP errors (404, etc.). Instead, a then() handler must check the [Response.ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) and/or [Response.status](https://developer.mozilla.org/en-US/docs/Web/API/Response/status) properties.

### What did you expect to see?

I was expecting to trigger the execution of my success callback inside `then()` since http errors 4xx and 5xx should not reject the fetch promise. Instead, the error callback was executed.

It seems to me that the information in the fetch() and  Fetch API pages are incorrect or outdated. I've made some tests and found that fetch is indeed rejecting promises when 400 status code is returned. I didn't try other error codes.

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/questions/45899931/typeerror-failed-to-fetch-trying-to-perform-an-post-request-on-api-hosted-on-he/72552340#72552340

https://forum.freecodecamp.org/t/type-error-failed-to-fetch-when-using-fetch-api/456214/5

### Do you have anything more you want to share?

Here is my test:
- Setup a server with some POST methods and respective OPTIONS methods to support preflight requests
- Define some required field in the request body. If the request has the field, make your server return 200. Else, return 400.
- Send a request with and without the field and check which callback is fired inside `then()`.

Request code example:

```javascript
  function test_fetch(){
	  let message = JSON.stringify({
             // 'ids' is the expected field. Change it latter for 'id' or something else to see the error.
             ids: [1] 
	  })
  
	  fetch('http://your.api/get_data',{
		  method: 'post',
                  // Adding Content-Type header to enable preflight. 
                  // It's still not working even with normal(no-preflight) requests.
                  // To test with normal instead of preflight requests,
                  // remove the line below from the fetch options object and
                  // make sure your server can handle text/plain data or else
                  // you may face some error due to wrong parsing of request body.
		  headers: {'Content-Type': 'application/json'},
		  body: message
	  })
	  .then(data => console.log('success'),data => console.log('error'))
  }
```

I've tested in `Chrome, version 102.0.5005.61 (Official Build) (64-bit)` and `Firefox, version 75.0 (64-bit)`. Got the same unexpected behaviour in both.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/fetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fetch/index.md
* Last commit: https://github.com/mdn/content/commit/196cc4ff3068a59b962a3fe1cbb960eb72ef542b
* Document last modified: 2022-05-31T04:47:00.000Z

</details>

**Comment by wbamberg** [comment]
I'm fairly sure that the docs are correct here, or I am misunderstanding your report. Try visiting https://example.org and pasting this into the console:

```js
const fetchPromise = fetch('https://example.org/i-dont-exist');

fetchPromise
  .then( response => {
    console.log(`Received response: ${response.status}`);
  })
  .catch( error => {
    console.error(`Error: ${error}`);
  });
```

When I do this I get:

```
> Received response: 404
```

...i.e. the promise is not rejected.

**Comment by jlucartc** [comment]
> I'm fairly sure that the docs are correct here, or I am misunderstanding your report. Try visiting https://example.org and pasting this into the console:
> 
> ```js
> const fetchPromise = fetch('https://example.org/i-dont-exist');
> 
> fetchPromise
>   .then( response => {
>     console.log(`Received response: ${response.status}`);
>   })
>   .catch( error => {
>     console.error(`Error: ${error}`);
>   });
> ```
> 
> When I do this I get:
> 
> ```
> > Received response: 404
> ```
> 
> ...i.e. the promise is not rejected.

Yes, this behaviour is indeed correct. But still it doesn't work with my test case. I believe that the information present on the fetch() page should be valid regardless of the method used (`GET`,`POST`,etc;), but as I've verified that's not the case, then I decided to open the issue to verify if the info is indeed wrong or if I've made some mistake.

I'm not sure if I'm assuming too much by saying that all methods should work in the same way, but as I've read the fetch() and Fetch API pages, I don't remember reading anything denying that or making exceptions.

Also, I'm not sure if the table in [this](https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions) section should be an exhaustive list of reasons for the promise to be rejected. If that's not, then it would be nice to say it explicitly, so that someone reading may refer to the spec if they stumble in a non-listed case like mine.

I'd like to recommend some API so that you and other could make your tests, but I didn't find any public API accepting POST requests and ready to accept preflight requests. I've tested in my server, so that I could control the response depending on the data sent in body.

**Comment by jlucartc** [comment]
I was having a problem with running my server in daemon but now things worked out. I've created 3 methods in my API so that you can test for yourselves in the same way I did. 

### Preflight tests
`POST` | http://weaver.jlucartc.tech/api/test-preflight : returns 200 if you send the parameter "ids" in body, returns 400 if you don't. OBS: you need to add `Content-Type: application/json` to your headers so that my server cant identify the parameters.

### No-preflight tests
`POST` | http://weaver.jlucartc.tech/api/test-no-preflight-error : always return 400
`POST` | http://weaver.jlucartc.tech/api/test-no-preflight-success : always return 200

### Running tests in browser
#### Preflight request receiving status 200
![mdn1](https://user-images.githubusercontent.com/18648391/173065317-a2957d5f-c78e-4f71-91cb-8531d26f0ba7.png)

#### Preflight request receiving status 400
![mdn2](https://user-images.githubusercontent.com/18648391/173065442-915ef1bc-ac55-4818-beb0-40d28698f912.png)


#### No-preflight request receiving status 200
![mdn3](https://user-images.githubusercontent.com/18648391/173065468-ea8ad937-87d6-4bf6-a03e-2ce415be7cae.png)


#### No-preflight request receiving status 400
![mdn4](https://user-images.githubusercontent.com/18648391/173065491-97841398-f8bd-4658-bf33-447d383e3282.png)

**Comment by wbamberg** [comment]
This is a CORS error, isn't it? If a CORS preflight request doesn't return the expected CORS headers, then a network error is returned to the caller: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests. Because the server is configured to return 400, it's not sending the CORS headers, so the original request rejects.

There are a LOT of cases where fetch will reject with a network error. We should probably do a better job of cataloguing them in https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions though.

**Comment by Josh-Cena** [comment]
Yeah agreed. Looks like it's just about CORS.
