### ISSUE TITLE
chore: update links for web-speech-api repository move

### ISSUE THREAD

**Issue by schalkneethling** [mdn/content#17116]
### MDN URL

 A repository for demos illustrating features of the Web Speech API. See [Web_Speech_API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) for more details.

### What specific section or headline is this issue about?

N/A

### What information was incorrect, unhelpful, or incomplete?

We are moving the web-speech-api repository into [dom-examples](https://github.com/mdn/dom-examples/pull/113). As a result, we need to update all current links in the content to point to the new location.

### What did you expect to see?

All links for web-speech-api repository points to new location of repository contents.

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/17117
