### ISSUE TITLE
[Help Wanted] what does `zoom in` means in the context

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/content#17148]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Viewport_concepts

### What specific section or headline is this issue about?

> Sticky headers or footers, as discussed above, stick to the top and bottom of the layout viewport, and therefore remain in view when we zoom in with the keyboard.

### What information was incorrect, unhelpful, or incomplete?

There is an issue https://github.com/mdn/translated-content/issues/2293 that discuss what is `zoom in` . I want to confirm its meaning to correct the translation.  Bigger or Smaller?

### What did you expect to see?

its actual meaning

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/viewport_concepts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Viewport_concepts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/viewport_concepts/index.md
* Last commit: https://github.com/mdn/content/commit/5c3180fe6dab8c336f19088e202b86474aa9deba
* Document last modified: 2022-04-03T14:19:17.000Z

</details>

**Comment by wbamberg** [comment]
"zoom in" means to make bigger, to increase the zoom level (so for instance, you would see less of the page in the viewport, but the part you did see would be bigger). Does that help?

**Comment by awxiaoxian2020** [comment]
> "zoom in" means to make bigger, to increase the zoom level (so for instance, you would see less of the page in the viewport, but the part you did see would be bigger). Does that help?

LGTM! Thank you!!

**Comment by awxiaoxian2020** [comment]
> Perhaps it's referring to something like https://support.mozilla.org/en-US/kb/font-size-and-zoom-increase-size-of-web-pages , which has keyboard shortcuts?

Oh! thanks very much indeed! @wbamberg 


cc: @yin1999 What else?
