### ISSUE TITLE
Example non-functioning problem report

### ISSUE THREAD

**Issue by Bob-Wright** [mdn/content#17171]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction#creating_an_async_function_from_an_asyncfunction_constructor

### What information was incorrect, unhelpful, or incomplete?

This is an example you present for an async function. It is simply WRONG. I would assume that you would present working examples, not opportunities to debug the writer's presentation. If I copy paste the example into my Nodejs console it presents errors and simply does not work. Hence it is basically USELESS as an example.

This begs the question: is this supposed to be documentation or simply a debug practice workbook? Or perhaps in an insulting vein to the author, do you actually know how it works? By appearances I'd say no you do not. (I realize it is probably a typo in the example code. But that doesn't help me. ☺)

### What did you expect to see?

A snippet of code that actually works as stipulated would be an EXCELLENT solution. lols.

### Do you have any supporting links, references, or citations?

Simply copy and paste the example into your Node console/terminal and run it. Or try to run it. ☺

This is a copy/paste of the example. Test it yourself?

function resolveAfter2Seconds(x) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(x);
    }, 2000);
  });
}

let AsyncFunction = Object.getPrototypeOf(async function(){}).constructor

let a = new AsyncFunction('a',
                          'b',
                          'return await resolveAfter2Seconds(a) + await resolveAfter2Seconds(b);');

a(10, 20).then(v => {
  console.log(v); // prints 30 after 4 seconds
});

This is the result in my console:

ubuntu@syntheticreality:~/portalPGP$ node resolvetest
undefined:3
return await resolveAfter2Seconds(a) + await resolveAfter2Seconds(b);
^

ReferenceError: resolveAfter2Seconds is not defined
    at eval (eval at <anonymous> (/home/ubuntu/portalPGP/resolvetest.js:11:9), <anonymous>:3:1)
    at Object.<anonymous> (/home/ubuntu/portalPGP/resolvetest.js:15:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.3.0

OK, thanks.

### Do you have anything more you want to share?

I am trying to improve my skillset in Nodejs. It seems to be an excellent platform for many use cases and I feel that the notion of event loops and function execution timing add some profound benefits to the Node paradigm. Apparently a lot of folks agree with that assessment.

My learning style is to read, read LOTS of examples and relevant Internet postings, and then to try and realize or write code that reflects what I read. To that end I have to say I have read literally dozens plus of such tutorials about callbacks, promises, and async/await constructs. So if it is of any comfort to you let me note that most of them are similar to this example of yours in that they simply do not work as stated.

I don't expect perfection from most of these references but somehow I had the idea that MDN might provide superior insights, that what was presented might actually work, that somehow MDN might be different, that MDN might be of actual utility in my quest. ☺

My biggest disappointment is frankly way less with MDN and this non-working example than with the fact that I can't yet look at the example and immediately see how to fix it. None of this is as complex as rocket appliances, right? Finally, what I'd call the "meta" of this example, the article itself sans the example, is fairly eloquent. You do a decent job of explaining the overarching philosophy, yet the Devil still remains in the details.

ps. I would really love to contribute towards writing articles or tutorials/documents like this one. Any opportunity in that vein would be of extreme interest. I am 100% physically disabled so any work must be remote, but part of my mind still functions (albeit perhaps marginally...) and I enjoy this kind of effort. Even an entry level position would be worth my consideration. Thanks! itzbobwright@gmail.com

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/asyncfunction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/asyncfunction/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by Josh-Cena** [comment]
I don't think many examples on MDN are written for Node—most are meant to be run in the browser console. So it's an oversight that an example may not work in Node.

For this one specifically, it's because function declarations are attached to the module scope in Node CJS, while implicit eval with function constructors only has access to the global scope. If you change it to:

```js
globalThis.resolveAfter2Seconds = function (x) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(x);
    }, 2000);
  });
}
```

It will work again.

We have a similar issue in https://github.com/mdn/content/issues/3153 where Node has different scoping rules to browser scripts. I don't think it warrants such bitter mockery of the content.

**Comment by Bob-Wright** [comment]
I received an almost immediate reply to this post that explains a lot of my problem with the example. Basically it is a javascript example, not a Node example!
The original sample is designed for use in a browser window, not for use as a nodejs script. This reply comment from MDN clarifies the issue nicely: it doesn't work in nodejs "because function declarations are attached to the module scope in Node CJS, while implicit eval with function constructors only has access to the global scope." The reply goes on to say modify the "resolve after" declaration to include a reference to the global variable so it reads
globalThis.resolveAfter2Seconds = function (x) { and it should work in Node.
The reply from MDN also mentioned this scoping rules issue report: https://github.com/mdn/content/issues/3153
Thanks Joshua Chen!

**Comment by wbamberg** [comment]
@Bob-Wright, this repository is governed by [Mozilla's Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/), which among other things asks participants to be respectful in their interactions with others.

I think your post here is pretty clearly in violation of this guideline, and ask that you amend your behavior in future.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/17171#issuecomment-1152494175
