### ISSUE TITLE
Redundant "Required" in Usage Example

### ISSUE THREAD

**Issue by ryanswarts** [mdn/content#17174]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-required

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

While it's not incorrect, the first code example includes the aria-required attribute on a form field that already has "Required" text on the page as the input's label. This would result in "required" being read aloud twice to screen reader users. This ARIA attribute seems to be intended more for situations such as when an asterisk or some other more visual treatment is used to indicate that a field is required and thus gives users a clear announcement when they may have missed that visual identifier.

### What did you expect to see?

I would like to see this example have the "Required" part of the label removed and replaced with an asterisk. A note could also be added below it that this attribute is unnecessary if the field includes "required" in the label.

### Do you have any supporting links, references, or citations?

[Aria-Required: WCAG Compliance Versus Best Practice](https://www.deque.com/blog/aria-requiredtrue-wcag-2-compliance-practice/)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/accessibility/aria/attributes/aria-required`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-required
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/attributes/aria-required/index.md
* Last commit: https://github.com/mdn/content/commit/6a5709307608e8984b9bf57547c542e54cc1ecf6
* Document last modified: 2022-05-17T13:08:45.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by #17584
