### ISSUE TITLE
:visited description is incorrect in RU translation

### ISSUE THREAD

**Issue by mgrinko** [mdn/content#1717]
https://developer.mozilla.org/ru/docs/Web/CSS/:visited

```вам нужно вставлять правило :visited до правила :link, но после других, определённых LVHA-порядком```
`до` means `before`
`после` means `after`
So the correct order is 

```вам нужно вставлять правило :visited после правила :link, но до других, определённых LVHA-порядком```

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
