### ISSUE TITLE
Firefox 86 release notes (February 23)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1720]
## Acceptance criteria

1. - [x] Firefox 86 release notes are updated with all DDN and DDC bugs.
2. - [x] Experimental Features page is updated.
3. - [x] Hacks blogpost written about Fx 86 new features
4. - [x] Hacks blog post shared with Melissa, Mike Conca, Caitlin Neiman, Asa Dotzler, Jen Boscacci, and Tyler Ahn. 
5. - [x] Links to the Fx hacks blog post is added to the rel notes on MDN.
6. - [x] [A new version of the mdn-data npm package is released](https://github.com/mdn/data/blob/master/docs/publishing.md), if changes were made in the last sprint.
7. - [x] The BCD browser json files mark Firefox 86 as the current release

**Comment by Ryuno-Ki** [comment]
Hey @chrisdavidmills,
I noticed you introduced a new label for it.
I was wondering, whether it couldn't be a milestone in GitHub instead :thinking:

**Comment by chrisdavidmills** [comment]
I just do this because it's easy to search by label. I've never used milestones on GH, to be honest.

**Comment by chrisdavidmills** [comment]
Rel notes updated: https://github.com/mdn/content/pull/2402

**Comment by chrisdavidmills** [comment]
Hacks blog post written (not shared until release).

**Comment by chrisdavidmills** [comment]
2.0.17 of mdn-data published: https://www.npmjs.com/package/mdn-data
