### ISSUE TITLE
Web Sockets Server Example Error

### ISSUE THREAD

**Issue by itranin** [mdn/content#17204]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_server

### What information was incorrect, unhelpful, or incomplete?

msglen = BitConverter.ToUInt64(new byte[] { **data**[9], **data**[8], **data**[7], **data**[6], **data**[5], **data**[4], **data**[3], **data**[2] });

### What did you expect to see?

msglen = BitConverter.ToUInt64(new byte[] { **bytes**[9], **bytes**[8], **bytes**[7], **bytes**[6], **bytes**[5], **bytes**[4], **bytes**[3], **bytes**[2] }**,0**);

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/websockets_api/writing_websocket_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_server
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/websockets_api/writing_websocket_server/index.md
* Last commit: https://github.com/mdn/content/commit/41fe03908c341ab928c4a8d5ee48e03e28e2dd6c
* Document last modified: 2022-06-03T04:21:39.000Z

</details>

**Comment by awxiaoxian2020** [comment]
Is this issue closed by #17845 ?

**Comment by teoli2003** [comment]
Yes, it is. Reopen if I'm mistaken.
