### ISSUE TITLE
[JavaScript] Document Intl.DisplayNames

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1721]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. [`Intl.DisplayNames`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames). This is already documented, so it looks like we just need BCD updating? 

## Related Gecko bugs

1. - [x] [Ship Intl.DisplayNames](https://bugzilla.mozilla.org/show_bug.cgi?id=1654116)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Rumyra** [comment]
BCD PR https://github.com/mdn/browser-compat-data/pull/8935

**Comment by Rumyra** [comment]
Release note: https://github.com/mdn/content/pull/2014

**Comment by Rumyra** [comment]
Believe all prs for this are in and only needs 'dev-doc-complete'

**Comment by chrisdavidmills** [comment]
Changes reviewed, bug set to DDC, all ready to close.

Thanks again @Rumyra !
