### ISSUE TITLE
Error with the sample code

### ISSUE THREAD

**Issue by jiwangyihao** [mdn/content#17232]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply

### What specific section or headline is this issue about?

Examples - Using apply to chain constructors

### What information was incorrect, unhelpful, or incomplete?

![Snipaste_2022-06-13_20-02-54](https://user-images.githubusercontent.com/51940778/173356286-2da1e333-f404-40a4-9cee-2244e3e9a7fb.png)

### What did you expect to see?

Fix problematic sample code.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/function/apply`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/function/apply/index.md
* Last commit: https://github.com/mdn/content/commit/37851e79d7c98d8529c7a2aa622c90bc13eaa2ba
* Document last modified: 2022-05-22T21:28:14.000Z

</details>

**Comment by Josh-Cena** [comment]
Right above this there's another code block with

```js
Function.prototype.construct = function(aArgs) {
  let oNew = Object.create(this.prototype);
  this.apply(oNew, aArgs);
  return oNew;
};
```

You need to run these two snippets in that order.

**Comment by jiwangyihao** [comment]
> 

OK. I see.
