### ISSUE TITLE
scroll-snap-type is not working well with mouse wheel, specially on Safari

### ISSUE THREAD

**Issue by yechukim** [mdn/content#17252]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type

### What information was incorrect, unhelpful, or incomplete?

scroll-snap-type is working well with touchpad or scroll but, when I use this with physical mouse wheel specially on Safari,
it's not smooth at all, it kinda looks buggy

### What did you expect to see?

this css has to be compatible with mouse wheel as well

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/scroll-snap-type`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/scroll-snap-type/index.md
* Last commit: https://github.com/mdn/content/commit/899010f6aff5849b0a08292a3e26a56b4147c54a
* Document last modified: 2022-04-05T21:15:04.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing, problems in the MDN documentation.

It looks like you are looking for help with your code, reporting a problem in a browser, or in the specification. Unfortunately, we don't have enough availability to help you.

For a problem in the code, I suggest asking your question on a specialized website, like StackOverflow.
For a problem in a browser, you should report it to the browser makers.
For a change in the spec, you should report it in their issue tracker.

I'm closing this issue. If I've misunderstood you and you were actually reporting a problem in the documentation, feel free to reopen it, while providing more information so we can understand the problem.

Thanks for your interest.
