### ISSUE TITLE
[CSS] Implement `:-webkit-autofill` in Firefox

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1725]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. [`:-webkit-autofill`](https://developer.mozilla.org/en-US/docs/Web/CSS/:-webkit-autofill). We already have a page about this, but it is pretty thin — could do with compat data, an interactive example, etc.

## Related Gecko bugs

1. - [x] [Consider adding support for -webkit-autofill (and a default stylesheet using it) for interop with Chrome](https://bugzilla.mozilla.org/show_bug.cgi?id=1475316)
2. - [x] [Enable :autofill / :-webkit-autofill support on release channels.](https://bugzilla.mozilla.org/show_bug.cgi?id=1685675)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
@chrisdavidmills there is now an :autofill pseudo added to the HTML 5 spec, and Firefox is implementing that with the webkit prefix as an alias. So I want to move the current page at https://developer.mozilla.org/en-US/docs/Web/CSS/:-webkit-autofill to https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill

I found the redirects file, but adding a redirect from the webkit version to autofill doesn't seem to be working (I get a 404) is there something else to do to move a page?

**Comment by chrisdavidmills** [comment]
@rachelandrew you also need to explicitly move the page to the new location in the repo, and update its title, slug, etc.

This is done via the `yarn content move` command; see https://github.com/mdn/content#moving-one-or-more-documents

**Comment by rachelandrew** [comment]
hmm I'd done that by hand already, it's showing up at the new location just the redirect isn't working.

**Comment by chrisdavidmills** [comment]
Hrm, ok, so that should work then. Can I have a look at your redirect syntax?

**Comment by rachelandrew** [comment]
ah just had a thought, needed to restart the server. Guess it only reads that file on start up?

**Comment by chrisdavidmills** [comment]
Ah yes.

**Comment by rachelandrew** [comment]
I've updated the bugs, added to release notes. BCD is pending merge.

This isn't really a candidate for an Interactive Example.

**Comment by chrisdavidmills** [comment]
This is all looking good; thanks @rachelandrew !
