### ISSUE TITLE
Isn't it misleading to order the shorthand properties starting with bottom?

### ISSUE THREAD

**Issue by TheKleyn** [mdn/content#17269]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/margin

### What specific section or headline is this issue about?

margin, top of article

### What information was incorrect, unhelpful, or incomplete?

I'm not an expert but isn't it misleading to order the shorthand properties starting with margin-bottom?

by where is says:
[Constituent properties](https://developer.mozilla.org/en-US/docs/Web/CSS/margin#constituent_properties)
This property is a shorthand for the following CSS properties:

### What did you expect to see?

correct order of shorthand

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/margin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/margin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/margin/index.md
* Last commit: https://github.com/mdn/content/commit/293c903f50ef81458e5e1df61887abaf8b4d7bb9
* Document last modified: 2022-04-05T16:15:55.000Z

</details>

**Comment by hiteshvijayhv** [comment]
Can I work on this issue?

**Comment by teoli2003** [comment]
They have been listed in alphabetical order, but I agree the _top_-_right_-_bottom_-_left_ would be better in this case.
@hiteshvijayhv: The issue is yours.
