### ISSUE TITLE
background-size article: Try it and Example section code preview is broken in 'Firefox" an "Brave"

### ISSUE THREAD

**Issue by bappyasif** [mdn/content#17272]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

### What specific section or headline is this issue about?

broken preview

### What information was incorrect, unhelpful, or incomplete?

Try it and Example section code preview is broken in "Firefox, and Brave" browser

Firefox view: [Try it](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size#try_it)
![image](https://user-images.githubusercontent.com/19854521/173587412-446d7432-25b8-4ebf-b7f0-20da90530585.png)

Brave view: [Example section](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size#examples)
![image](https://user-images.githubusercontent.com/19854521/173587601-38fd5c11-22d1-48ca-be56-7bdb590d9921.png)

### What did you expect to see?

to see as it is in "chrome" browser

![image](https://user-images.githubusercontent.com/19854521/173587952-e701713f-5025-4e77-a3b3-c11260bba81a.png)

![image](https://user-images.githubusercontent.com/19854521/173587856-a0c0360b-da28-42f3-882f-1f8809cb28cf.png)

### Do you have any supporting links, references, or citations?

Please see above sections

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/background-size`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-size
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/background-size/index.md
* Last commit: https://github.com/mdn/content/commit/ba8194486e3e267c52e0abd9b9b5c3aa78262f25
* Document last modified: 2022-05-13T05:22:00.000Z

</details>

**Comment by teoli2003** [comment]
Works for me in Firefox. Do you have an add-on blocking `<iframes>` like an over-zealous ad-blocker?

**Comment by bappyasif** [comment]
> Works for me in Firefox. Do you have an add-on blocking `<iframes>` like an over-zealous ad-blocker?

thanks, and yeah, apparently 'ultimate blocker' extension was blocking it in 'Firefox' but even though 'adblocker' is turned off, preview is still not showing up in "Bravo"!!
![image](https://user-images.githubusercontent.com/19854521/173617594-a95bf4f8-d325-4bcc-bb55-3f51998e94a7.png)

**Comment by teoli2003** [comment]
Thanks for coming back!
