### ISSUE TITLE
[SVG] Implement <feComposite operator="lighter">

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1727]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. [`<feComposite operator="lighter">`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComposite). So we already have the page, but it seems to suggest that Firefox already supports `operator="lighter"`` on `feComposite`, so some investigating and potential updates needed.

## Related Gecko bugs

1. - [ ] [Implement <feComposite operator="lighter"> (SVG filters)](https://bugzilla.mozilla.org/show_bug.cgi?id=1518099)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Ryuno-Ki** [comment]
Wow, two year old bug finally got fixed :open_mouth: 

The mentioned MDN page for this is https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComposite (see also #1450)

BCD https://github.com/mdn/browser-compat-data/blob/26dd8f364aafbf822ca5f4bb46bce71c16df0998/svg/elements/feComposite.json received no update yet.

The example seem not to be interactive - can the checkbox be ticked?

**Comment by hamishwillee** [comment]
The [svg example file in our doc](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComposite#svg) is copied from the spec. I have modified this to include a test of `lighter` ([svg_example.zip](https://github.com/mdn/content/files/5969521/svg_example.zip)) but as you can see from tests on Firefox, Chrome, Inkscape it doesn't work as expected on any of them.

A [bit of research](https://stackoverflow.com/questions/11839070/fecomposite-code-example-from-official-site-not-working) shows that this is reliant on the filter input `BackgroundImage` which FF (and possibly the others do not support). We very kindly explain that there is a [workaround for BackgroundImage here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/in#workaround_for_backgroundimage) but not why or when you need it :-(. I'll see if I get help from Engineering to improve this. 

![image](https://user-images.githubusercontent.com/5368500/107727021-75ff5600-6d3e-11eb-8b62-583811e39623.png)

**Comment by hamishwillee** [comment]
PS Yes, the SVG story really is a mess/unclear. BCD is a mess. Docs are spread out. I'll start working on the BCD and getting a better example, then think about what else needs to be done for this.

**Comment by hamishwillee** [comment]
Tracking
- [ ] [BCD](https://github.com/mdn/browser-compat-data/pull/9074) - in progress.

**Comment by hamishwillee** [comment]
@chrisdavidmills The release note is done for this, and in theory this might all be that was needed because both the BCD and docs were (incorrectly) stating that this was already supported.

Improved the docs such that now it is a bit more obvious from feComposite docs what the different operations do. That's ready for review. BCD also ready for review.

**Comment by chrisdavidmills** [comment]
@hamishwillee Nice work here Hamish. I've had a good look, and it looks like the BCD just needs to be finalized now.

After that's done, I'll set it to DDC, and we can bump it to done.

**Comment by chrisdavidmills** [comment]
BCD merged; closing.
