### ISSUE TITLE
Should the link of `fetch` of Forbidden header name need change?

### ISSUE THREAD

**Issue by zjffun** [mdn/content#17281]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

### What information was incorrect, unhelpful, or incomplete?

The link of **fetch** in "Names starting with `Sec-` are reserved for creating new headers safe from APIs using **fetch**".

### What did you expect to see?

I think the link of above fetch should not refer to the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), but https://fetch.spec.whatwg.org/#concept-fetch.

### Do you have any supporting links, references, or citations?

https://fetch.spec.whatwg.org/#forbidden-header-name

### Do you have anything more you want to share?

Because of my limited English, I'm not entirely sure my understanding is correct. Thank you

**Comment by zjffun** [comment]
Related https://github.com/mdn/content/pull/17280

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #17530 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
