### ISSUE TITLE
[CSS] Support full <image> syntax in list-style-image

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1728]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. `<image>` syntax in `list-style-image`. We already have pages, but probably need to add examples and updated BCD:

* https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-image (formal syntax/syntax also needs updating?)
* https://developer.mozilla.org/en-US/docs/Web/CSS/image

## Related Gecko bugs

1. - [x] [Support full <image> syntax in list-style-image as per spec.](https://bugzilla.mozilla.org/show_bug.cgi?id=1685078)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
@chrisdavidmills I've tested this in other browsers and it looks like everything else has supported this for a long time IE10/Chrome 26/ Safari 6.2.

Do we want to add a whole line about image support just to flag it is gone into Firefox or add a note saying that prior to 86 `<image>` wasn't supported?

**Comment by chrisdavidmills** [comment]
> Do we want to add a whole line about image support just to flag it is gone into Firefox or add a note saying that prior to 86 `<image>` wasn't supported?

I'm assuming you're talking about adding the note into the `list-style-type` BCD? If so, then yes, I agree. But maybe also added a note into the `<image>` BCD to say that prior to 86, this wasn't supported as a value of `list-stytle-type`? Just in cae, so you get the info whichever page you end up on?

**Comment by rachelandrew** [comment]
I'm not sure this really adds value in the `<image>` type. I don't think someone would be looking at `<image>` if they were trying to use a gradient in an older version of Firefox, they would look at the `list-style-type` page. Do we normally flag this up on type pages if a property changes what it accepts?

**Comment by chrisdavidmills** [comment]
> I'm not sure this really adds value in the `<image>` type. I don't think someone would be looking at `<image>` if they were trying to use a gradient in an older version of Firefox, they would look at the `list-style-type` page. Do we normally flag this up on type pages if a property changes what it accepts?

Sorry, missed this until now. I'm not sure that we have a best practice for this, to be honest. But I think you are right that people are unlikely to look at data type pages and more likely to look at the relevant property page.

**Comment by chrisdavidmills** [comment]
OK, checked this out, and data, BCD, doc, rel note, and bug look perfect. Awesome work @rachelandrew !
