### ISSUE TITLE
[DevTools] Remove the cd command

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1729]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Remove the CD comment from the [web console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console). Most likely to need updating is the [Helpers page](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Helpers). [This comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1607741#c2) is helpful.

## Related Gecko bugs

1. - [x] [Remove the cd command](https://bugzilla.mozilla.org/show_bug.cgi?id=1607741)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
I've kicked off https://github.com/mdn/content/pull/1873 to clean up source prior to this update. 

Deleting this is fairly easy but there are some associated docs improvements that should already have been made/should be made at same time.

Quick review of what needs to happen: 
- - [ ]  BCD is not needed
- - [ ]  Add release note
- - [ ]  Set bugs to dev-doc-complete
- - [ ] Restructure [Working with iframes](https://developer.mozilla.org/en-US/docs/Tools/Working_with_iframes) - which replaced cd. Can be better written.
- - [ ] [Web_Console/Helpers](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Helpers) - just remove the `cd` section
- [Web_Console/The_command_line_interpreter](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter#helper_commands)
  - Has section on helper commands but this is an import - so if we fix helper commands can ignore.
  - - [ ] [working with iframes](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter#working_with_iframes) section refers to `cd` approach and needs to be removed.
- [Web_Console/UI_Tour#toolba](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/UI_Tour#toolbar) - link to the iframes section - this is like top level view on what is possible, so needs to point to the alternative.

**Comment by hamishwillee** [comment]
@chrisdavidmills All the bits of this are now done. When you've reviewed can you please go to the but and update dev-doc-complete?

**Comment by chrisdavidmills** [comment]
Bug set to DDC, and issue ready to close. Nice work @hamishwillee !
