### ISSUE TITLE
Confusing documentation on textarea value attribute

### ISSUE THREAD

**Issue by jbecktruman** [mdn/content#17294]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

### What specific section or headline is this issue about?

Try It

### What information was incorrect, unhelpful, or incomplete?

Default content entered between the opening and closing tags. <textarea> does not support the value attribute.

This is correct, but I find it misleading, because it implies that JavaScript cannot use the .value property of the element.  However, in JS it is essential to use the .value property in certain situations.

### What did you expect to see?

Default content entered between the opening and closing tags. <textarea> does not support the value attribute (however, JavaScript can use the .value _property_ of the element).

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/textarea`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/textarea/index.md
* Last commit: https://github.com/mdn/content/commit/8037fdc19393ba1fc31bff80bc2f02c988462452
* Document last modified: 2022-04-15T22:29:22.000Z

</details>

**Comment by teoli2003** [comment]
You are mixing HTML attributes and API properties. They are completely different things.

Some properties _reflect_ attributes, but that's all.

**Comment by Josh-Cena** [comment]
Closing per https://github.com/mdn/content/issues/17294#issuecomment-1155994786. This sentence is worded in a way that _implies_ that you already know `value` is part of `HTMLTextAreaElement`.
