### ISSUE TITLE
[WebAPI] Ship window.name resetting

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1730]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Ship window.name resetting. Basically a security improvement for [Window.name](https://developer.mozilla.org/en-US/docs/Web/API/Window/name). The [intent to ship](https://groups.google.com/g/mozilla.dev.platform/c/Tu3uXFg5xV0/m/FDNYXZTzBAAJ) is useful for understanding this one. Probably a page update and BCD update, maybe see if there are any privacy pages that need updating too?

## Related Gecko bugs

1. - [ ] [Ship window.name resetting](https://bugzilla.mozilla.org/show_bug.cgi?id=1685089).

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Rumyra** [comment]
OK I've spent a fair bit of time checking any other pages which might need this info, but haven't found any that are really relevant apart from Window.name updates. Wondering if @hamishwillee has any thoughts on this (are there any pages you're more familiar with where this might be worth a mention)?

As far as BCD goes - there is a note referring to this under FF specifying Window.name is set to an empty string on cross browsing... however as this is now the default behaviour should the notes be the opposite and state Window.name persists when it shouldn't (Chrome for example) @chrisdavidmills

**Comment by chrisdavidmills** [comment]
@Rumyra Ah, so you're thinking of including a note that say something like "Previous to version 86, window.name persists when..." kind of thing? Hrm, I'm not sure if there is a standard for this...

**Comment by hamishwillee** [comment]
Hi @Rumyra 

When I did the [edits on windows.name in FF82](https://github.com/mdn/sprints/issues/3731#issuecomment-704017095) the only relevant page I could find was `Windows.name` too. 

I'm confused about what this delivers. My "guess" is that this is exactly the change that was supposed to be released in FF82, but  that [this did not happen](https://bugzilla.mozilla.org/show_bug.cgi?id=444222#c105). So this change turns on that feature all the time using `privacy.window.name.update.enabled`. If that's the case, do we revert history on FF82?

Re BCD, and again if my guess is correct, then the note is wrong. FWIW I'd change the note from:

> From Firefox 82, if a new page from another domain is loaded into a tab, then window.name is set to the empty string (the original string is restored if the tab reverts back to the original page). This change prevents some cross-site attacks. See bug 444222.

TO something like

> From Firefox 86, if a new page from another domain is loaded into a tab, then window.name is set to the empty string (the original string is restored if the tab reverts back to the original page). This change prevents some cross-site attacks. From Firefox 82 to 86 this feature can accessed using the preference `privacy.window.name.update.enabled`. See bugs 1685089 and 444222.

**Comment by Rumyra** [comment]
Thank you so much @hamishwillee 🙏 I noticed the window.name page already had info on this. I wish I had asked earlier 😆 I'll go through the BCD as thinking about it the way it's noted is probably the right way at the moment 👍

**Comment by hamishwillee** [comment]
Glad to finally be able to help :-)

**Comment by Rumyra** [comment]
Release notes: https://github.com/mdn/content/pull/2359

BCD: https://github.com/mdn/browser-compat-data/pull/9129

**Comment by chrisdavidmills** [comment]
@Rumyra I've reviewed your browser compat data, and I'll set the bug to DDC, as I think we are close enough.

Nice work!
