### ISSUE TITLE
maxlength should be replaced with minlength in Client-side validation section 

### ISSUE THREAD

**Issue by pihamchi** [mdn/content#17308]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#client-side_validation

### What specific section or headline is this issue about?

Client-side validation

### What information was incorrect, unhelpful, or incomplete?

![스크린샷 2022-06-15 오후 9 54 52](https://user-images.githubusercontent.com/78897803/173832195-57341032-ddc7-4ea1-a79b-39e6a00205e6.png)

### What did you expect to see?

The attribute associated with validityState.tooShort should be minlength, not maxlength.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/tooShort

### Do you have anything more you want to share?

![스크린샷 2022-06-15 오후 9 57 38](https://user-images.githubusercontent.com/78897803/173832479-0c17c848-7495-4bcc-9ad8-8cb64943fcdd.png)

**Comment by teoli2003** [comment]
This has been fixed in #17315 (2 PRs to fix the same issues a few minutes apart, woah!)

**Comment by pihamchi** [comment]
@teoli2003 It's clear that this is the problem I found. But I think someone else stole what I found. Could you please add me as a co-contributor?
