### ISSUE TITLE
Incorrect code comments on this page

### ISSUE THREAD

**Issue by kaka59** [mdn/content#17304]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Boolean#%E5%AE%9E%E4%BE%8B%E6%96%B9%E6%B3%95

### What specific section or headline is this issue about?

#描述

### What information was incorrect, unhelpful, or incomplete?

var myFalse = new Boolean(false);   // true

### What did you expect to see?

var myFalse = new Boolean(false);   // false

**Comment by AnilSeervi** [comment]
Should be transfered to [mdn/translated-content](https://github.com/mdn/translated-content).

**Comment by kaka59** [comment]
It has been transfer to mdn/translated-content[#6324](https://github.com/mdn/translated-content/issues/6324)
