### ISSUE TITLE
[CSS] Take intrinsic size into account when using aspect-ratio

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1731]
## Acceptance criteria

1. - [ ] The listed features are documented sufficiently on MDN
2. - [ ] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Change in [`aspect-ratio`](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) behavior. I'm not 100% sure of what needs doing here, if anything. Investigation needed.

## Related Gecko bugs

1. - [ ] [Take intrinsic size into account when using aspect-ratio](https://bugzilla.mozilla.org/show_bug.cgi?id=1646100).

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
I think this is the correct bug https://bugzilla.mozilla.org/show_bug.cgi?id=1646100

@chrisdavidmills not convinced there is anything to doc here, the `aspect-ratio` implementation is behind a flag so I think this is just part of the implementation progress, tracking a spec change, as far as I can see. Chrome have just shipped this, so perhaps when Firefox ships I'll add some more examples and so on at that point.

**Comment by chrisdavidmills** [comment]
Ooops, copy/paste error, sorry! I've update it in the description now.

If there is nothing to do here, that's fine; feel free to close this, and remove dev-doc-needed from the bug
