### ISSUE TITLE
Nested negation pseudo-classes e.g. :not(:not(...))

### ISSUE THREAD

**Issue by edbaafi** [mdn/content#17313]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:not

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/:not#description bullet 1

### What information was incorrect, unhelpful, or incomplete?

The page states: 

> The :not pseudo-class may not be nested, which means that :not(:not(...)) is invalid.

But this is no longer the case.  This was from the Selectors Level 3 spec but the current documentation is about the Selectors Level 4 spec (notice the  docs refer to ```:not( <complex-selector-list> )``` not ```:not( <simple-selector> )``` which is the old spec)

### What did you expect to see?

this bullet should be removed as there are no longer any `unusual effects and outcomes` regarding nesting of `:not()` pseudo-classes

### Do you have any supporting links, references, or citations?

The old [Level 3 spec](https://www.w3.org/TR/2018/CR-selectors-3-20180130/#negation) explicitly mentions that `:not()` takes:

>  a [simple selector](https://www.w3.org/TR/2018/CR-selectors-3-20180130/#simple-selectors-dfn) (excluding the negation pseudo-class itself) as an argument. It represents an element that is not represented by its argument.
> 
> Negations may not be nested; :not(:not(...)) is invalid. Note also that since pseudo-elements are not simple selectors, they are not a valid argument to :not().

The current [Level 4 spec](https://drafts.csswg.org/selectors/#negation) removes any mention of this limitation. 

### Do you have anything more you want to share?

This can be tested (and shown to work) in current versions of all major browsers, showing that the browser vendors have interpreted the lack of mention of nested `:not` being invalid as meaning it is allowed:

```
<style>
  :not(:not(.red)){
    color:red;
  }
</style>
<p class="red">red</p>
```

**Comment by edbaafi** [comment]
@estelle @sideshowbarker what do I need to do to get this fixed?  Submit a PR with the bullet point removed?

**Comment by sideshowbarker** [comment]
> @estelle @sideshowbarker what do I need to do to get this fixed? Submit a PR with the bullet point removed?

Yes, please

**Comment by estelle** [comment]
done.

**Comment by sideshowbarker** [comment]
Fixed in https://github.com/mdn/content/pull/18801
