### ISSUE TITLE
Set&Map: What is "insertion order"?

### ISSUE THREAD

**Issue by Worldwidebrine** [mdn/content#17327]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

> You can iterate through the elements of a set in insertion order.

> insertion order

### What did you expect to see?

What's "insertion order"?

What's "insertion" here?

"insertion" is "valid `.add(value)`"?
```js
const set = new Set;
set.add(1);
set.add(2);
set.delete(1);
set.add(3);
for (const value of set) {
  console.log(value);
}
```
output should be 23?

```js
const set = new Set;
set.add(1);
set.add(2);
set.add(1);
for (const value of set) {
  console.log(value);
}
```
12?

```js
const set = new Set;
set.add(1);
set.add(2);
set.delete(1)
set.add(1);
for (const value of set) {
  console.log(value);
}
```
21?

> The `add()` method appends a new element with a specified value to the end of a `Set` object.

> appends

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/set/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by Worldwidebrine** [comment]
Why even is the word "insertion" used here?
Why shouldn't it be "append" or something?

**Comment by Andrew-Cottrell** [comment]
> Why even is the word "insertion" used here?
> Why shouldn't it be "append" or something?

"insertion" is the _de facto_ standard word to use in this context. For example, Wikipedia's [Set (abstract data type)](https://en.wikipedia.org/wiki/Set_(abstract_data_type)) and [Associative array](https://en.wikipedia.org/wiki/Associative_array) pages use "insert" or "insertion" several times, but never use "append".

**Comment by Andrew-Cottrell** [comment]
> But https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/add
> 
> > The `add()` method appends a new element with a specified value to the end of a `Set` object.

I would prefer it to read something like...

> The `add()` method inserts a new element with a specified value in to a `Set` object, unless the value is already represented by an element of the `Set`.

I'm not convinced the concept "end" is especially useful for `Set` objects (although completely understandable), as I tend to think of them as unordered collections that remember the insertion order and have iterators that yield elements in insertion order.

**Comment by sideshowbarker** [comment]
For contributors considering whether to work on this issue: The comments in https://github.com/mdn/content/issues/17327#issuecomment-1165334228 and https://github.com/mdn/content/issues/17327#issuecomment-1165420272 outline a small number of changes that could be made relatively quickly to resolve this issue.

**Comment by rosahbruno** [comment]
@sideshowbarker @Andrew-Cottrell @Worldwidebrine 
I created a pull request to address the issue discussed above, let me know if there are any issues or anything else that may be helpful to add
