### ISSUE TITLE
[WebExt] host permissions or <all_urls> permission behavior

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1732]
## Acceptance criteria

1. - [ ] The listed features are documented sufficiently on MDN
2. - [ ] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Change in host permissions or <all_urls> permission behavior. I'm not 100% sure of what needs doing here. Investigation needed.

## Related Gecko bugs

1. - [ ] [host permissions or <all_urls> permission should grant access to privileged parts of the tabs API](https://bugzilla.mozilla.org/show_bug.cgi?id=1679688).

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by chrisdavidmills** [comment]
Hi @caitmuenster ! Just letting you know about the WebExt work items I found for Fx 86.

**Comment by caitmuenster** [comment]
Tagging @Rob--W for this one. :)

**Comment by Rob--W** [comment]
I decided to not update the BCD because this change affects many APIs. I mentioned the version where the behavior changed in two articles in my PR at #2057.

**Comment by chrisdavidmills** [comment]
Thanks a lot for the documentation, @Rob--W ! As a small FYI, in future, can you also add a rel note to the relevant rel notes for this release (https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/86 in this case)?

You don't need to worry about this one; I'm about to file a PR that fixes up these rel notes.
