### ISSUE TITLE
Editor styled too small to use.

### ISSUE THREAD

**Issue by crimsonkissaki** [mdn/content#1734]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator

#### What information was incorrect, unhelpful, or incomplete?

The CSS styling has forced the generator to have a max height of 176px. The 'height' defined for .sample-code-frame in _examples.css is overriding the iframe's inline "height=1100px" property, rendering the tool unusable.

#### Specific section or headline?
N/A
#### What did you expect to see?

The entire tool, or at least most of it.

#### Did you test this? If so, how?

Chrome DevTools -> Inspect -> select the iframe element and disable "height: auto;" in the .sample-code-frame CSS and the tool expands to proper size.

![box_shadow_tool_173px_default](https://user-images.githubusercontent.com/1197205/105747590-93db5700-5f06-11eb-8984-a9577c831292.png)

![box_shadow_tool_1100px_correct](https://user-images.githubusercontent.com/1197205/105747855-f03e7680-5f06-11eb-9f3a-4bbeac5b84ab.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_background_and_borders/box-shadow_generator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/css_background_and_borders/box-shadow_generator/index.html
* Document last modified: 2021-01-13T18:01:00.000Z

</details>

**Comment by wbamberg** [comment]
@crimsonkissaki , this seems to have got fixed?

**Comment by sideshowbarker** [comment]
Closing as not reproducible per https://github.com/mdn/content/issues/1734#issuecomment-847505540. @crimsonkissaki if you can still reproduce the problem, this issue can be revisited.
