### ISSUE TITLE
Issue with "list-style": Typo in first paragraph.

### ISSUE THREAD

**Issue by leonard-9500** [mdn/content#1736]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style

#### What information was incorrect, unhelpful, or incomplete?
First paragraph "The list-style CSS shorthand property allows **you set** all the list style properties at once"

#### Specific section or headline?
First paragraph

#### What did you expect to see?
"The list-style CSS shorthand property allows you **to** set all the list style properties at once"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/list-style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/list-style/index.html
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by captainbrosset** [comment]
Apologies @leonard-9500 if you intended to create a PR for this. I wanted to see how contributing to MDN content worked and found this simple 2-minutes task quite a good start for me to get a feel for it. Hopefully there are other such issues if you wanted to also work on a PR.
