### ISSUE TITLE
Issue with "Regular expression syntax cheatsheet": …

### ISSUE THREAD

**Issue by ColinEberhardt** [mdn/content#1737]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet

#### What information was incorrect, unhelpful, or incomplete?

The MDN cheat sheet uses the term character set to describe the concept that almost all other regex documentation refers to as characters classes

#### Specific section or headline?

"Character classes" 

#### What did you expect to see?

If you check other sources for regex reference, the regex of the form `[xyz]`, `[a-c]` are termed character classes. See for example:

https://www.regular-expressions.info/refcharclass.html
TC49 tests: https://github.com/tc39/test262/blob/master/test/built-ins/RegExp/regexp-class-chars.js#L9

However, the MDN cheat sheet calls these character sets

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions/cheatsheet`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/guide/regular_expressions/cheatsheet/index.html
* Document last modified: 2021-01-11T10:55:17.000Z

</details>

**Comment by Elchi3** [comment]
Given we call it Character Classes here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes and Character set is easily to be confused with the same term used in encoding (https://developer.mozilla.org/en-us/docs/Glossary/character_set), I'm going to change this.

Thanks for your report!
