### ISSUE TITLE
Issue with "Tutorials": …

### ISSUE THREAD

**Issue by nschonni** [mdn/content#1738]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Tutorials

#### What information was incorrect, unhelpful, or incomplete?

Seems like this should probably get redirected/merged with https://developer.mozilla.org/en-US/docs/Learn

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/tutorials`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Tutorials
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/tutorials/index.html
* Document last modified: 2020-12-28T11:28:23.000Z

</details>

**Comment by Ryuno-Ki** [comment]
It's also interesting to notice, that not all links are internal. I thought, we would mark external links automagically. :thinking: 

Thanks for bringing this up!

**Comment by chrisdavidmills** [comment]
> Seems like this should probably get redirected/merged with https://developer.mozilla.org/en-US/docs/Learn

I initially thought "yes", but then I looked at GA, and this page has quite a lot of traffic. It is untidy to have this, but I am actually tempted to just leave it alone. 

> It's also interesting to notice, that not all links are internal. I thought, we would mark external links automagically. 🤔

We used to, but that styling seems to have disappeared in the platform move.

**Comment by sideshowbarker** [comment]
A while back I looked into this myself and came to the same conclusion at https://github.com/mdn/content/issues/1738#issuecomment-767402105 — that the Tutorials page has value of its own and we shouldn’t redirect it to Learn.

So I’m going ahead and closing this.
