### ISSUE TITLE
Issue with "Web technology reference": …

### ISSUE THREAD

**Issue by nschonni** [mdn/content#1739]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Reference

#### What information was incorrect, unhelpful, or incomplete?

Should probably be redirected/merged with https://developer.mozilla.org/en-US/docs/Web
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Reference
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/reference/index.html
* Document last modified: 2021-01-02T19:24:06.000Z

</details>

**Comment by Ryuno-Ki** [comment]
I have a hard time telling the difference of the links …

**Comment by nschonni** [comment]
Right, should have been the root `docs/Web` for the redirect target

**Comment by chrisdavidmills** [comment]
Sure, please do. I didn't even know that existed.

**Comment by sideshowbarker** [comment]
I opened https://github.com/mdn/content/pull/5793 with a fix for this.
