### ISSUE TITLE
Issue with "Web API reference": …

### ISSUE THREAD

**Issue by nschonni** [mdn/content#1740]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Reference/API

#### What information was incorrect, unhelpful, or incomplete?

Should probably be merged with https://developer.mozilla.org/en-US/docs/Web/API

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/reference/api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Reference/API
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/reference/api/index.html
* Document last modified: 2021-01-02T17:51:39.000Z

</details>

**Comment by chrisdavidmills** [comment]
Yes, definitely.

**Comment by nschonni** [comment]
Should the content be merged or just blindly redirected/deleted?

**Comment by rachelandrew** [comment]
Having made a few index type pages, I think this would be improved if we had the types of Web APIs from https://developer.mozilla.org/en-US/docs/Web/Reference/API with the relevant APIs for each underneath, then the listing of interfaces. I broke up the pseudo-classes page in that way: https://developer.mozilla.org/en-us/docs/Web/CSS/Pseudo-classes

So, essentially merging and restructuring a bit.

Happy to have a go at it, I'd need to know which page we want to keep and which should be redirected.

**Comment by nschonni** [comment]
I think https://developer.mozilla.org/en-US/docs/Web/API is the one to keep. The 2 files under the /Reference/ seem like partial stubs, but the API one seemed like it might have some content that wasn't covered on the existing API index page

**Comment by Rumyra** [comment]
+1 in favour of giving web apis a taxonomy and probably moving the interfaces under the apis themselves. /Web/API is so useful and also can be difficult to navigate. Let me know if you need a hand @rachelandrew

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/5793
