### ISSUE TITLE
Issue with "WebAssembly": …

### ISSUE THREAD

**Issue by nschonni** [mdn/content#1741]
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly

#### What information was incorrect, unhelpful, or incomplete?

Page and sub-pages should probably move under https://developer.mozilla.org/en-US/docs/Web

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/webassembly/index.html
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by chrisdavidmills** [comment]
I'd rather not do this. WebAssembly is really a different beast, and not a web technology as such, in that it is mostly not targetted at web developers.
