### ISSUE TITLE
CSS overflow property is giving results inconsistant with guide

### ISSUE THREAD

**Issue by dylzeee** [mdn/content#17430]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content

### What specific section or headline is this issue about?

Overflowing Content 

### What information was incorrect, unhelpful, or incomplete?

On this page https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content it gives an example for setting the overflow property to 'scroll' and says "Remove some content from the box below. Notice how the scrollbars remain, even if there is no need for scrolling." 

I removed some content but this actually removed the scrollbar (which personally I think is great btw) and contradicts the statement. 

I then did some testing on a local html site and indeed the scrollbar only appears when the text does overflow. I checked the CSS specifications and they still recommend displaying a scrollbar whether content overflows or not, so I'm wondering if this browser specific? I am reading the guide and testing in the latest version of Mozilla Firefox. 

In this same example, it also states below "In the example above, we only need to scroll on the y axis, however we get scrollbars in both axes. To just scroll on the y axis, you could use the [overflow-y](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y) property, setting overflow-y: scroll."

But I also do not see any horizontal scrollbar at all. 

### What did you expect to see?

I expected that to remove some content from the box below and see the scrollbars remain, even though there is no need for scrolling.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/overflowing_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/overflowing_content/index.md
* Last commit: https://github.com/mdn/content/commit/30ff4492fab1aeee1a24e26b89f8135b749c79ba
* Document last modified: 2022-05-11T12:42:29.000Z

</details>

**Comment by Josh-Cena** [comment]
@dylzeee I know it's been a while, but what browser & OS are you using? On mac, this is controlled by a system setting:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/55398995/190304854-37cadcb1-4d60-4378-bb8f-fa02172a91c3.png">

Change it to "always" and you will see the gutter displayed (although not the scrollbar itself, per se)

**Comment by estelle** [comment]
We should likely include a comment that the scrollbar visibility is also controlled by OS settings.
