### ISSUE TITLE
Missing Attribution: Difference between log() and dir()

### ISSUE THREAD

**Issue by LarissaKim** [mdn/content#17444]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/console/log

### What specific section or headline is this issue about?

Difference between log() and dir()

### What information was incorrect, unhelpful, or incomplete?

Excluding the first sentence directly under the header, the information in this section contains content from this [answer on StackOverflow](https://stackoverflow.com/a/19269945).

While it is available for reuse, it is under CC BY-SA 3.0 which requires attribution. There currently doesn't appear to be any attribution to the source for this section :see_no_evil:

### What did you expect to see?

Attribution to the original content. Perhaps: 

> "[What's the difference between console.dir and console.log?](https://stackoverflow.com/questions/11954152/whats-the-difference-between-console-dir-and-console-log)" by [Drew Noakes](https://stackoverflow.com/users/24874/drew-noakes) is licensed under [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)

### Do you have any supporting links, references, or citations?

Source: [https://stackoverflow.com/a/19269945](https://stackoverflow.com/a/19269945)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/console/log`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/console/log
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/console/log/index.md
* Last commit: https://github.com/mdn/content/commit/6c498a447fb5e776a67af7f9801a3aa407fc4d1c
* Document last modified: 2022-05-27T18:36:48.000Z

</details>

**Comment by sideshowbarker** [comment]
I think if we are to keep this section, then minimally the wording should be revised to make it appropriate for the context in which it appears in the article.

For one thing, the answer https://stackoverflow.com/a/19269945 which this content was copied from seems to be specifically about a particular difference in Chrome. But the existing MDN section doesn’t really make that clear.

Changing the section heading to **Difference between log() and dir() in Chrome** would make it more accurate — but then it seems that for MDN we don’t want the section to be specifically about Chrome; instead we want the section to be about the general differences between the two that are common across browsers.

Given all that, and unless somebody steps in with interest in rewriting that section, I think we should for now just remove the entire section.

**Comment by sideshowbarker** [comment]
> Another [answer ](https://stackoverflow.com/a/11954537) in that thread mentions a behaviour difference in Firefox, and yet another [answer ](https://stackoverflow.com/a/63715034) describes the difference as per the [Console Standard](https://console.spec.whatwg.org/), but I agree that it could be reworded to be more generic or removed entirely.

OK, I’ve gone ahead and opened #17570 to remove it

After that fix is merged, this issue will automatically be marked as resolved, and closed.

> It's a valid question to have, but probably difficult to answer because of browser differences.

Agreed
