### ISSUE TITLE
CSP errors and warnings contains lots of 404 links

### ISSUE THREAD

**Issue by SohamMukherjee21** [mdn/content#17459]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors

### What specific section or headline is this issue about?

Page not found

### What information was incorrect, unhelpful, or incomplete?

Browser can't load the page in the link [The page's settings blocked the loading of a resource at %2$S ("%1$S").](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/CSPViolationWithURI)

### What did you expect to see?

Solution page of this generated error

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/csp/errors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/csp/errors/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #19099 with a fix that un-links all the pages that are 404. That’s of course not an ideal fix — but I’m not aware of anyone at this point who plans on actually going in and creating any of those pages. So unless/until somebody does start to work on doing that, there’s no point in having the links.

After #19099 is merged, this issue will automatically be marked as resolved, and closed.
