### ISSUE TITLE
event deprecated but still used in documentation

### ISSUE THREAD

**Issue by Sammeeey** [mdn/content#17454]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/pageY

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/pageY#examples

### What information was incorrect, unhelpful, or incomplete?

The example code described the usage like this:
```js
let pageY = event.pageY;

```

However if I use it like that in VSCode it tells me, that `event` is deprecated.
![event deprecated in VSCode](https://user-images.githubusercontent.com/49591562/174545742-a5b8d3c8-5aa9-4fae-9694-4dcac25319c7.png)

### What did you expect to see?

If `event` is really deprecated, then I would expect a different example (with an approach which is not deprecated) on MDN.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mouseevent/pagey`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/pageY
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mouseevent/pagey/index.md
* Last commit: https://github.com/mdn/content/commit/34824110fdb96935876ef49348813a4405682d5c
* Document last modified: 2022-06-01T05:44:30.000Z

</details>

**Comment by teoli2003** [comment]
It looks like you have not defined `event`. `pageY` is a property and you need to have the instance of `MouseEvent` defined before calling methods on it.

(The example itself is a bit too short, and not self contained, I agree).

**Comment by Sammeeey** [comment]
Thank you for the quick response.
