### ISSUE TITLE
Disable password suggestion on password input field

### ISSUE THREAD

**Issue by Mbengparis** [mdn/content#17466]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

### What information was incorrect, unhelpful, or incomplete?

How can i prevent an input of type password from displaying a suggested password. 

The autocomplete=new-password does not solve the problem as the field still keeps suggesting other saved passwords as dropdown.

### What did you expect to see?

A password field without autocomplete and without auto suggestion on focus.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/security/securing_your_site/turning_off_form_autocompletion`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/security/securing_your_site/turning_off_form_autocompletion/index.md
* Last commit: https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e
* Document last modified: 2022-05-17T13:23:31.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing, problems in the MDN documentation.

It looks like you are looking for help with your code, reporting a problem in a browser, or in the specification. Unfortunately, we don't have enough availability to help you.

For a problem in the code, I suggest asking your question on a specialized website, like StackOverflow.
For a problem in a browser, you should report it to the browser makers.
For a change in the spec, you should report it in their issue tracker.

I'm closing this issue. If I've misunderstood you and you were actually reporting a problem in the documentation, feel free to reopen it, while providing more information so we can understand the problem.

Thanks for your interest.

**Comment by Moe39118** [comment]
how do you used it
