### ISSUE TITLE
[CSS] Implement 'scroll-snap-stop'

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#17469]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Docs are there - needs checking https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-stop (example looks v big)
Probs just release note & bcd

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1312165

**Comment by dipikabh** [comment]
Task list:

Documentation for the property exists as mentioned in the issue description.

- [ ] Update the Examples section on [scroll-snap-stop](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-stop) property page
- [ ] Update BCD
- [ ] Add a release note
- [ ] Update the [scroll-snap-stop](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Basic_concepts#the_scroll-snap-stop_property) section on Basic concepts of CSS Scroll Snap page
