### ISSUE TITLE
Confused term in Border subsection

### ISSUE THREAD

**Issue by thuan-nmt** [mdn/content#17463]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model

### What specific section or headline is this issue about?

Margins, padding, and borders

### What information was incorrect, unhelpful, or incomplete?

In the `Border` subsection, the term `If you are using the standard box model, the size of the border is added to the width and height of the box` make me so confused. Because I don't now what is width and height it mention to. It is t he content width, height (width, height property, as standard box model), or the "real" dimension?

### What did you expect to see?

I think I would write clearly that it is property or something else

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/the_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/the_box_model/index.md
* Last commit: https://github.com/mdn/content/commit/ff7093a803b98de431ec66999c635f8de7c8aecd
* Document last modified: 2022-06-18T17:25:10.000Z

</details>

**Comment by galopyz** [comment]
I can try to clarify here. In standard box model, height and width are the content width and height. On the other hand, alternate box model has height and width as actual box dimensions. 

Therefore, I can modify the sentence to "If you are using the standard box model, the size of the border is added to the width and height of the (content) box" and also the next sentence to "If you are using the alternative box model then the size of the border makes the content box smaller as it takes up some of that available width and height (of actual width and height of the box)". 

Does anybody have any other suggestions or corrections? Thank you.
