### ISSUE TITLE
[JS] Array.findLast & Array.findLastIndex

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#17473]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Array.findLast & Array.findLastIndex

Looks like this will be experimental for 103 but implemented in Chrome & Safari so we should document. https://github.com/mdn/browser-compat-data/blob/main/javascript/builtins/Array.json

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1704385

Shipping bug (no version yet): https://bugzilla.mozilla.org/show_bug.cgi?id=1775026

**Comment by Josh-Cena** [comment]
Related: https://github.com/mdn/content/issues/15851

**Comment by Rumyra** [comment]
Thanks so much @Josh-Cena 👍 that's really helpful

**Comment by Rumyra** [comment]
Shipping bug is here https://bugzilla.mozilla.org/show_bug.cgi?id=1775026 but no release number yet

**Comment by hamishwillee** [comment]
I added a shipping bug. I might take this, since Joe Medley hasn't responded on the other issue. Want to finish streaming docs first.

**Comment by jpmedley** [comment]
Apologies I've been having trouble getting around to it. Ruth told me someone else had inquired about doing these pages, so I thought she had decided to let me off the hook.

**Comment by hamishwillee** [comment]
@jpmedley Appreciate you're busy. I'm happy to do them, I just don't want to duplicate work. So if you don't think you will get to them in the next week or so let me know, otherwise I'll do it myself (and ask for your review if that's OK?)

**Comment by hamishwillee** [comment]
Status update

- [ ]  BCD - https://github.com/mdn/browser-compat-data/pull/16854
- [ ] Docs
- [ ] Experimental features
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
Thanks @hamishwillee! Apologies to both I'm only just getting around to gh notifications this week with our internal work week
