### ISSUE TITLE
[Web API] CacheStorage/Cache should require SecureContext

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#17475]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

CacheStorage/Cache should require SecureContext. This is mentioned in the docs, but Chrome has a bcd note to say when HTTPS was required - maybe we do the same here

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1112134

**Comment by hamishwillee** [comment]
It isn't completely clear what this really delivers and how it relates to that HTTPS thingy. For example, the BCD indicates this was secure context in FF44.
I have asked the question here: https://bugzilla.mozilla.org/show_bug.cgi?id=1112134#c57

There will be some additional changes required:
- [ ] [CacheStorage](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage) - remove experimental markup
- [ ] [caches](https://developer.mozilla.org/en-US/docs/Web/API/caches) global object is not experimental.
- [ ] `caches` should be the thing that is marked as requiring the secure context.

Will know more when the bug assignee gets back to me.

**Comment by hamishwillee** [comment]
Status
- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/16900
- [ ] Docs
- [ ] Release note
- [ ] dev-docs-complete

**Comment by Rumyra** [comment]
Great thanks @hamishwillee
