### ISSUE TITLE
Anchors to link to css values

### ISSUE THREAD

**Issue by jsoref** [mdn/content#1749]
I can link to https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#values
But, I can't link to `break-word` directly.

It'd be nice if each CSS value were an anchor in pages that defined a CSS property.

e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#break-word

**Comment by Ryuno-Ki** [comment]
I'd like to hear @rachelandrew's opinion on this.

Perhaps in conjunction with https://github.com/mdn/content/issues/1707 (which would turn them into separate pages instead of anchors on a page).

**Comment by rachelandrew** [comment]
@Ryuno-Ki these are values and not attributes so this doesn't have anything to do with #1707 

We don't typically make values linkable like that, I would suggest linking to the Values header (https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#values) I wrote quite a lot of CSS material which links to MDN pages and that, with an explanation is generally fine.
