### ISSUE TITLE
Unnecessarily confusing example.

### ISSUE THREAD

**Issue by TravisA9** [mdn/content#17499]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData

### What specific section or headline is this issue about?

Getting image data from a canvas (and Result)

### What information was incorrect, unhelpful, or incomplete?

**Unhelpful**: The specific region selected to copy with getImageData() adds unneeded confusion. 

_**Part**_ of the region of the canvas selected contains white pixels and they are then put into a region with white pixels. This leads to confusing results that may be unexpected by many. The result is, instead of the reader thinking about the topic being covered, they have to do math and visualize why the results might look different than expected. 

In short, it hinders comprehension and distracts from the topic.

### What did you expect to see?

Here's an option: 

> (1) Draw an image to the canvas 
> (2) copy a region from that image with getImageData() and then 
> (3) draw that image-data back to another region of the canvas.

Of course, there are other ways of keeping the example simple. But with an image, the reader would quickly be able to understand what is happening at a glance because they would be able to clearly identify where the portion came from.

### Do you have any supporting links, references, or citations?

Yes, the article itself implies it has an unnecessary layer of complexity:

> `Of those pixels, most are either transparent or taken from off the canvas; only 2,500 of them are opaque black (the color of the drawn rectangle).` 

This clarification would not be necessary if it were simplified.

### Do you have anything more you want to share?

Thank you for considering my recommendation for this, otherwise helpful, example. I hope that this can help to make a great source of information even better.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/getimagedata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/getimagedata/index.md
* Last commit: https://github.com/mdn/content/commit/436f23e605697ee1a9b747ca7579bb6588983db4
* Document last modified: 2022-06-08T03:34:56.000Z

</details>

**Comment by wbamberg** [comment]
Yes, agreed. I have had a go at this in https://github.com/mdn/content/pull/17631, let me know if it works for you!

**Comment by TravisA9** [comment]
Nice, that looks very clear!
