### ISSUE TITLE
Issue with "CSS reference": The link "path()" is incorrect

### ISSUE THREAD

**Issue by restufauzi697** [mdn/content#1751]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

## The link "path()" is incorrect

I tried the `path()` link on the CSS Reference page, but what I got was a **Page not found** page.

After I thought it was impossible for the page to disappear, because I had been there before but not from the CSS Reference page.

I tried changing the link "`https://developer.mozilla.org/en-US/docs/Web/CSS/path`" to "`https://developer.mozilla.org/en-US/docs/Web/CSS/path()`" finally I got access.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/reference/index.html
* Document last modified: 2021-01-15T08:25:52.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@peterbe Is this a content issue or a missing redirect?

**Comment by chrisdavidmills** [comment]
@Ryuno-Ki the "Index" link list is built using the [CSS_Ref](https://github.com/mdn/yari/blob/master/kumascript/macros/CSS_Ref.ejs) macro. We'll have to work out how it works so that we can fix this. I suspect there'll be some other links that have broken too...

**Comment by restufauzi697** [comment]
I've looked at [CSS_Ref.ejs](https://github.com/mdn/yari/blob/master/kumascript/macros/CSS_Ref.ejs). the program is written, the syntax ends in `()`

*from line 141:*
```javascript
        if (syntax.match(/\(\)$/)) {
```

it will be deleted.

*from line 148:*
```javascript
            index[initial].push({
                urlPath: syntax.replace("()", ""),
                label: syntax
            });
```

I have tried checking other links such as
[attr()](https://developer.mozilla.org/en-US/docs/Web/CSS/attr) - `https://developer.mozilla.org/en-US/docs/Web/CSS/attr`,
[blur()](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/blur) - `https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/blur`,
[calc()](https://developer.mozilla.org/en-US/docs/Web/CSS/calc) - `https://developer.mozilla.org/en-US/docs/Web/CSS/calc`.

All links do not end in `()`, but only

[path()](https://developer.mozilla.org/en-US/docs/Web/CSS/path\(\)) - `https://developer.mozilla.org/en-US/docs/Web/CSS/path() `

which ends in `()`.

It looks like the error is from the folder, maybe it hasn't been changed and aligned like the others so it can't be accessed from the link `https://developer.mozilla.org/en-US/docs/Web/CSS/path` and can only be accessed from the link `https://developer.mozilla.org/en-US/docs/Web/CSS/path()`

**Comment by peterbe** [comment]
> @peterbe Is this a content issue or a missing redirect?

It looks like a macro error. It created this:
```html
<a href="/en-US/docs/Web/CSS/path"><code>path()</code></a>
```
when it should have created this:
```html
<a href="/en-US/docs/Web/CSS/path()"><code>path()</code></a>
```

**Comment by peterbe** [comment]
> It looks like the error is from the folder, maybe it hasn't been changed and aligned like the others so it can't be accessed from the link `https://developer.mozilla.org/en-US/docs/Web/CSS/path` and can only be accessed from the link `https://developer.mozilla.org/en-US/docs/Web/CSS/path()`

Yeah, it seems that the bug is that there's a redirect for `/en-US/docs/Web/CSS/calc --> /en-US/docs/Web/CSS/calc()` but no such redirect for `/en-US/docs/Web/CSS/path --> /en-US/docs/Web/CSS/path()`.
