### ISSUE TITLE
Consider avoiding the use of html { font-size: 62.5%; } in examples

### ISSUE THREAD

**Issue by kjellr** [mdn/content#17519]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-size

### What specific section or headline is this issue about?

[Ems](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#ems), [Rems](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#rems)

### What information was incorrect, unhelpful, or incomplete?

Two examples on this page use the outdated practice of using `html { font-size: 62.5%; }` to make `1rem` equal to `10px`. This is generally inadvisable nowadays, since it can easily result in 10px text — generally considered too small to be accessible. Including the example here makes it seem like it's a recommended practice.

### What did you expect to see?

Another example mentioning this method [was removed recently](https://github.com/mdn/content/pull/16322#discussion_r878930069), so I think it makes sense to remove it here for consistency.

**Comment by estelle** [comment]
https://github.com/mdn/content/pull/17520
