### ISSUE TITLE
Should inherited non-standard properties also be marked as non-standard, in their documentation?

### ISSUE THREAD

**Issue by Phosra** [mdn/content#17524]
### MDN URL

For example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError

### What specific section or headline is this issue about?

"Instance Properties"

### What information was incorrect, unhelpful, or incomplete?

The properties/methods for the Error subclass include some which are inherited from the `Error` class itself, some of which are non-standard, and include marking indicating such.

In this particular page, they are not marked as non-standard, so it isn't obvious that they are unless the reader also reviews the documentation on `Error` in order to find this out.

### What did you expect to see?

I would expect, as these properties are marked as non-standard in the page documenting where they come from, that the current page should also be marked with the same `{{non-standard_inline}}` marker to propagate this warning.

**Comment by teoli2003** [comment]
I think they should be marked as such.

**Comment by teoli2003** [comment]
I dream to have this applied automatically, but for the moment, it has to be done manually.

**Comment by Josh-Cena** [comment]
Since this has to be fixed on a case-by-case basis, and the `Error` pages have been fixed, I would consider this resolved for now.
