### ISSUE TITLE
URL Error#toSource directs to Error#toString

### ISSUE THREAD

**Issue by Phosra** [mdn/content#17523]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/toSource

### What specific section or headline is this issue about?

The URL itself

### What information was incorrect, unhelpful, or incomplete?

The method referenced does not exist, it directs to <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/toString>, is this intentional?

### What did you expect to see?

An error ("404") page.

**Comment by Josh-Cena** [comment]
Yes—see https://github.com/mdn/content/pull/15580

**Comment by teoli2003** [comment]
@Phosra Have you found the (redirected) link to `toSource` in MDN? If so we should fix the link. Else, there isn't anything we can do.

**Comment by Josh-Cena** [comment]
There are four mentions:

https://github.com/mdn/content/blob/0dbdb1c819944887d14ada153bf5ee11390a08e3/files/en-us/web/javascript/reference/global_objects/error/tostring/index.md?plain=1#L96

https://github.com/mdn/content/blob/0dbdb1c819944887d14ada153bf5ee11390a08e3/files/en-us/web/javascript/reference/global_objects/webassembly/compileerror/index.md?plain=1#L40

https://github.com/mdn/content/blob/0dbdb1c819944887d14ada153bf5ee11390a08e3/files/en-us/web/javascript/reference/global_objects/webassembly/linkerror/index.md?plain=1#L39

https://github.com/mdn/content/blob/0dbdb1c819944887d14ada153bf5ee11390a08e3/files/en-us/web/javascript/reference/global_objects/webassembly/runtimeerror/index.md?plain=1#L39

**Comment by teoli2003** [comment]
We should fix these. @schalkneethling Who is our WebAssembly expert that can advise us about the `toSource()` in these 4 files?

**Comment by teoli2003** [comment]
Thank you! I'll happily review the removal for the first one. and, then, when #17517 is merged, this issue can be closed.

**Comment by teoli2003** [comment]
Let's keep this open until #17517 gets merged.

**Comment by schalkneethling** [comment]
> We should fix these. @schalkneethling Who is our WebAssembly expert that can advise us about the `toSource()` in these 4 files?

That would be @MendyBerger
