### ISSUE TITLE
A incorrect item in “The statistics type hierarchy”

### ISSUE THREAD

**Issue by hutuworld** [mdn/content#17542]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/RTCStats

### What specific section or headline is this issue about?

The statistics type hierarchy

### What information was incorrect, unhelpful, or incomplete?

The  Object **RTCOutboundRtpStreamStats** under hierarchy of **RTCReceivedRtpStreamStats** should be **RTCRemoteInboundRtpStreamStats**。

wrong content：
RTCReceivedRtpStreamStats
-   RTCInboundRtpStreamStats
-   RTCOutboundRtpStreamStats

### What did you expect to see?

RTCReceivedRtpStreamStats
-   RTCInboundRtpStreamStats
-   RTCRemoteInboundRtpStreamStats

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/webrtc-stats

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/rtcstats`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCStats
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/rtcstats/index.md
* Last commit: https://github.com/mdn/content/commit/d557a2d2720031acc4e5ad9f5bf3e8355188ee42
* Document last modified: 2022-06-20T19:53:56.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #17544 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
