### ISSUE TITLE
hasAttribute introduced in DOM Level 2

### ISSUE THREAD

**Issue by simonvarey** [mdn/content#17580]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course

### What specific section or headline is this issue about?

Scripting in namespaced XML

### What information was incorrect, unhelpful, or incomplete?

Although it does not fit the pattern of method vs namespaced method, the hasAttribute method was only introduced in DOM Level 2, at the same time as the hasAttributeNS method.

### What did you expect to see?

I'm not exactly sure, as hasAttribute doesn't fit the rest of the pattern, but at the least hasAttribute shouldn't link to [DOM Level 1](https://www.w3.org/TR/REC-DOM-Level-1/level-one-core.html), as the method is not defined there.

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-ElHasAttr

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/namespaces_crash_course`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/namespaces_crash_course/index.md
* Last commit: https://github.com/mdn/content/commit/a289cb928d0cd81f6755e33c12e2bc2bd04d32c2
* Document last modified: 2022-02-17T15:36:47.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve raised #17591 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
