### ISSUE TITLE
footer.lang

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#176]
![Screenshot_20201210-001620.png](https://user-images.githubusercontent.com/44380480/101700443-52d5d300-3a7d-11eb-8bd7-8dacaadb152e.png)

https://developer.allizom.org/de/docs/Learn

**Comment by vkWeb** [comment]
@chrisdavidmills This is on purpose I believe...?

**Comment by mattiapontonio** [comment]
I opened it here because from the outside I can't quite understand what comes from content and what comes from Yari, it should be addressed.

**Comment by chrisdavidmills** [comment]
@vkWeb is correct; we are not translating the UI content in Yari, at least not initially.

**Comment by mattiapontonio** [comment]
Ok.
How about set the [lang](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#:~:text=The%20lang%20global%20attribute%20helps,for%20Identifying%20Languages%20(BCP47).) the footer organism?
