### ISSUE TITLE
Poor wording for Error cause, and inaccurate description of location

### ISSUE THREAD

**Issue by ghost** [mdn/content#17610]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

### What specific section or headline is this issue about?

Properties > error.prototype.cause

### What information was incorrect, unhelpful, or incomplete?

> Error cause. If an error is caught and re-thrown, this property should contain the original error. 

This makes me think along the lines of literally
```js
try {
 ...
 try {
  ...
 } catch (exception) {
  // throw it again
  throw exception;
 }
} catch (exception) {
 // it has a .cause now!
 const { cause } = exception;
}
```
which isn't accurate at all.

On another note, it says `Error.prototype.cause`, but this is actually an `OwnProperty`.
See, <https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-installerrorcause>.
I don't think that any articles properly make this distinction, nor that there may be infrastructure or precedent for doing so.

### What did you expect to see?

The cause is supplied by the code that throws the error object, this should be clarified.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/error`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/error/index.md
* Last commit: https://github.com/mdn/content/commit/036687e1d9697abcb4943ed6e0e97619fc3888e7
* Document last modified: 2022-06-23T14:58:53.000Z

</details>

**Comment by Josh-Cena** [comment]
> On another note, it says `Error.prototype.cause`, but this is actually an `OwnProperty`.

See https://github.com/mdn/content/issues/16325. But indeed, this notation makes it impossible to distinguish from, say, `Error.prototype.name`.

**Comment by sideshowbarker** [comment]
For having a broader discussion, https://github.com/mdn/mdn-community/discussions is an option to consider.

As outlined at https://github.com/mdn/mdn-community#discussions:

> If you're ever in doubt about whether to open an issue or a discussion, consider the following guidelines:
> 
> - Issues are for reporting a bug with a clearly defined and actionable outcome.
> - If the issue needs a discussion to agree upon a course of action or define an actionable piece of work, you are in the right place

**Comment by Josh-Cena** [comment]
@Phosra interested in a PR to fix the wording for cause?

**Comment by Josh-Cena** [comment]
Ah, I can take a look as well. No problem
