### ISSUE TITLE
The example of detecting option support in the “addEventListener” article is confusing. Won't passive() always return false?

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#17629]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#safely_detecting_option_support

### What information was incorrect, unhelpful, or incomplete?

The example of detecting option support is confusing.
Won't passive() always return false?

### What did you expect to see?

Different code or more explanation.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/eventtarget/addeventlistener`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/eventtarget/addeventlistener/index.md
* Last commit: https://github.com/mdn/content/commit/196cc4ff3068a59b962a3fe1cbb960eb72ef542b
* Document last modified: 2022-05-31T04:47:00.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

> The example of detecting option support is confusing. Won't passive() always return false?

Yes, it does. As it says, this object is used in the "fake event listener", and is only used to set `passiveSupported` correctly. 

Further on it says: "when you want to create an actual event listener that uses the options in question, you can do something like this..." and the code following that is the real event listener, which uses `passiveSupported` to decide whether to use `passive` or not.

It is a bit tricky, but honestly I think it's reasonably clear and I'm not sure how I would rewrite it to make things clearer.

**Comment by wbamberg** [comment]
I'm closing this, based on https://github.com/mdn/content/issues/17629#issuecomment-1166180510.
