### ISSUE TITLE
malformed text for passive example

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#17628]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#safely_detecting_option_support

### What information was incorrect, unhelpful, or incomplete?

unorganized text, not good format in the last example:
someElement.addEventListener("mouseup", handleMouseUp, passiveSupported
                               ? { passive: true } : false);

### What did you expect to see?

excessive whitespace gone

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/eventtarget/addeventlistener`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/eventtarget/addeventlistener/index.md
* Last commit: https://github.com/mdn/content/commit/196cc4ff3068a59b962a3fe1cbb960eb72ef542b
* Document last modified: 2022-05-31T04:47:00.000Z

</details>

**Comment by JustinWebDev** [comment]
Well, maybe you didn't have a better way in the small width you had to work with.  It just looks odd and made me think it was messed up.  Sorry.  I would delete this issue if I could.

**Comment by wbamberg** [comment]
> Well, maybe you didn't have a better way in the small width you had to work with. It just looks odd and made me think it was messed up. Sorry. I would delete this issue if I could.

FWIW I think you are right and have had a go at improving it in https://github.com/mdn/content/pull/17636.
