### ISSUE TITLE
JavaScript Guidelines don't cover optional bracket usage

### ISSUE THREAD

**Issue by ghost** [mdn/content#17624]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript

### What information was incorrect, unhelpful, or incomplete?

Optional brackets are not covered, e.g.
```js
if(!x)
  console.log("x is false");
```

### What did you expect to see?

A small section giving MDN's preferences regarding formatting and inclusion of brackets where they may be omitted, due to the language syntax.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/guidelines/code_guidelines/javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/code_guidelines/javascript/index.md
* Last commit: https://github.com/mdn/content/commit/32f6335487194aa8c3a9fb5c90eeba5e95be6224
* Document last modified: 2021-10-15T15:32:38.000Z

</details>

**Comment by wbamberg** [comment]
The guidelines defer to the AirBnb guidelines for anything not covered:

> If you want something that goes into more detail, we'd recommend the [AirBnB JavaScript Style Guide](https://github.com/airbnb/javascript), which is generally compatible with our guidelines.

I don't think it is a good use of our time to create and maintain our own style guide. One day we will have Prettier running and this can all go away...
