### ISSUE TITLE
Is the Symbol built-in object a class?

### ISSUE THREAD

**Issue by jjiglesias** [mdn/content#17666]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Symbol

### What specific section or headline is this issue about?

Well-known symbols

### What information was incorrect, unhelpful, or incomplete?

The word "class" at the beggining of the section:  "The Symbol class ..."

### What did you expect to see?

Maybe "The Symbol [global or built-in] object ...".

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/symbol`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Symbol
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/symbol/index.md
* Last commit: https://github.com/mdn/content/commit/4c9f9bb287b37743a0e626fd2b60f54240f4f07e
* Document last modified: 2022-04-26T05:55:54.000Z

</details>

**Comment by wbamberg** [comment]
Closed by https://github.com/mdn/content/pull/17749.
