### ISSUE TITLE
mix-blend-mode examples only use images, there are no text content examples

### ISSUE THREAD

**Issue by SignpostMarv** [mdn/content#17681]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode

### What specific section or headline is this issue about?

examples/try-it

### What information was incorrect, unhelpful, or incomplete?

The mix-blend-mode examples only use images, there are no text content examples.

It is not obvious from the examples that mix-blend-mode can apply to text content.

### What did you expect to see?

Examples of mixed-blend-mode applied to text content

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/mix-blend-mode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/mix-blend-mode/index.md
* Last commit: https://github.com/mdn/content/commit/293c903f50ef81458e5e1df61887abaf8b4d7bb9
* Document last modified: 2022-04-05T16:15:55.000Z

</details>

**Comment by wbamberg** [comment]
I just filed https://github.com/mdn/content/pull/17794 which I hope addresses this.
