### ISSUE TITLE
Update the broken link about `Alternate License Block`

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/content#17696]
It's at
https://github.com/mdn/content/blob/9d464556a9c4c3b67a7904f1d667a6798044996f/files/en-us/mdn/about/index.md?plain=1#L53

**Comment by awxiaoxian2020** [comment]
It's archived in https://github.com/mdn/archived-content/blob/main/files/en-us/archive/meta_docs/examples/alternate_license_block/index.html

**Comment by awxiaoxian2020** [comment]
> It's archived in https://github.com/mdn/archived-content/blob/main/files/en-us/archive/meta_docs/examples/alternate_license_block/index.html

Should we refer to this GitHub link?

**Comment by awxiaoxian2020** [comment]
Any response about this issue? :)

**Comment by teoli2003** [comment]
The quickest way to get this fixed is:
- You make the PR
- I review and merge it 

If I make the PR (that is trivial), we will have to wait for somebody to review it.

**Comment by awxiaoxian2020** [comment]
> The quickest way to get this fixed is:
> 
> * You make the PR
> * I review and merge it
> 
> If I make the PR (that is trivial), we will have to wait for somebody to review it.

I have no idea about it. I can't get your point. just remove it?

**Comment by teoli2003** [comment]
Every pull request has to be reviewed by a maintainer, if I create it, another one will have to review it. If you create the pull request, as you look in a hurry, I can review it and merge it and it will be quicker.

**Comment by awxiaoxian2020** [comment]
> Every pull request has to be reviewed by a maintainer, if I create it, another one will have to review it. If you create the pull request, as you look in a hurry, I can review it and merge it and it will be quicker.

I know about it. What I said is that I don't know how to fix this issue.
