### ISSUE TITLE
Issue with "Making content editable": …

### ISSUE THREAD

**Issue by rhys-childs** [mdn/content#1770]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content

#### What information was incorrect, unhelpful, or incomplete?
The article explains that all browsers mentioned support `document.execCommand`, however [execCommand documentation](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) states that `document.execCommand` has been `Deprecated` and is likely pending removal. It says that people should `Avoid using it, and update existing code if possible`. 

#### Specific section or headline?
Each `document.execCommand` section and example.

#### What did you expect to see?
A supported alternative that can be used to manipulate a contenteditable dom. 

#### Did you test this? If so, how?
yes, it works at the moment. Based on documentation however that will not always be the case and I am trying to replace my outdated code with something that is not deprecated

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/guide/html/editable_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/guide/html/editable_content/index.html
* Document last modified: 2020-11-30T14:41:08.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Perhaps a duplicate of #1444 and/or #629

**Comment by rhys-childs** [comment]
> Perhaps a duplicate of #1444 and/or #629

Thank you @Ryuno-Ki this was a duplicate of #1444.
