### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by MrUpsidown** [mdn/content#17734]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API

### What specific section or headline is this issue about?

Speech synthesis

### What information was incorrect, unhelpful, or incomplete?

The "Live demo URL" (https://mdn.github.io/web-speech-api/speak-easy-synthesis/) points to a 404.

### What did you expect to see?

A live demo.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_speech_api/using_the_web_speech_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_speech_api/using_the_web_speech_api/index.md
* Last commit: https://github.com/mdn/content/commit/287f0d21e05cfe8bb2ce1b49d4ec16e17207aa5b
* Document last modified: 2022-06-20T17:50:03.000Z

</details>

**Comment by cw118** [comment]
Thanks for reporting @MrUpsidown, I opened #17739 which should fix this and another dead link :)
