### ISSUE TITLE
Content suggestion: @scope

### ISSUE THREAD

**Issue by estelle** [mdn/content#17751]
## What is the new suggestion?
Document @scope, which is supported in Chrome 105.

## Why is it important or useful?

It is going to be supported and people are asking for it

How many pages are likely to be needed?

- [x] Create a @scope tutorial (new)
- [x] Update [Introducing the CSS Cascade](https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade) to include @scope
- [x] Updated  [Cascade and inheritance](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance)
- [x] Update [cascade layers](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers) (just remove open and close comment in list)
- [ ] Update Live example to include scope in cascade and specificity tutorials: [CSS Cascade Skills test](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_tasks)
- [x] Update [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) to include @scope
- [x] Update [`:scope`](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope)

## Other supporting information

Test page: https://codepen.io/miriamsuzanne/pen/wvyBNXP works in chrome canary
https://drafts.csswg.org/css-cascade-6/#scoped-styles

**Comment by chrisdavidmills** [comment]
@estelle I'm going to have a go at this one, if that works for you. Looks like this will finally be available in Chrome 118 release.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills
> 
> For reference, you can use this article: https://developer.chrome.com/articles/at-scope/

@ramiy thanks; this is super useful!
