### ISSUE TITLE
Issue with "<img>: The Image Embed element": mention video in <img>

### ISSUE THREAD

**Issue by Artoria2e5** [mdn/content#1777]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

It would be helpful to add a mention of the use of video formats in `<img>` tags, as a replacement of animated image formats. Video codecs are generally much better for doing animation, and using the img tag instead of the video tag tends to hint the browser better wrt preloading and other performance aspects like sleeping.¹

The feature is only supported by Safari 11.1+. The chromium bug (791658) has been marked wontfix. The Mozilla bug is bz895131.

The mention is to be added under the file format section. I don't see a point in adding it to the support table until someone else implements it too.

See also:
* https://css-tricks.com/fallbacks-videos-images/
* https://cloudinary.com/blog/evolution_of_img_gif_without_the_gif

¹ Or we can wait for the image formats to become sort-of video formats, in the sense of adding interframe compression. Chrome decodes AV1 shoehorned into an AVIF container, for example. (I am not quite sure if plain AVIF has interframe compression).

(I am on my phone right now. Expect a PR, maybe.)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/img`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/html/element/img/index.html
* Document last modified: 2020-12-21T22:08:45.000Z

</details>

**Comment by chrisdavidmills** [comment]
Sure thing; adding a note that this is possible is a good idea.

**Comment by Artoria2e5** [comment]
Now I am split between two ways to do this:

1. Change https://github.com/mdn/content/blob/master/files/en-us/web/html/element/img/index.html to add another note below the table. The argument is that mp4 is not really an image format, so the table shouldn't be changed.
2. Change https://github.com/mdn/content/blob/main/files/en-us/web/media/formats/image_types/index.html to add the mention in the table. The argument is that interframe compression is hugely better than what the multi-frame image formats can provide, and should be used when available just because how good it is.

My empty stomach isn't helping me make this decision.

**Comment by hamishwillee** [comment]
If it were me I would add it in `img` (your point 1). The first doc is about what you can use in an img element - so it definitely applies there. 
The second doc is about image formats; while the information would not be inappropriate as a note it isn't as relevant for most readers of the page. 

Something to consider is that while animated gif is terrible compared to video, AVIF is much better - indeed AVIF uses a video codec.

Also FWIW   I quite like the idea of having an insource comment with url links to the mozilla bug and chrome wontfix in your note. That might help someone else get context later.

**Comment by rachelandrew** [comment]
@Artoria2e5 did you intend to get back to this issue and create a PR?
