### ISSUE TITLE
App version in manifest

### ISSUE THREAD

**Issue by pozirk** [mdn/content#17779]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Manifest

### What specific section or headline is this issue about?

"version" key

### What information was incorrect, unhelpful, or incomplete?

_"PWA manifests include its name, **author**, icon(s), **version**, description, and list of all the necessary resources (among other things)."_

After that line there is no mention of how to set an app version in manifest file.
Tried to put "version": "1.2.3" in manifest file - it didn't work.

Same problem with "author" key?

Thank you!

### What did you expect to see?

To set an app version with "version" key.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/manifest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/manifest/index.md
* Last commit: https://github.com/mdn/content/commit/22fef44310d2f3fd7f3cbc6ad3d8d4e17fc38ddd
* Document last modified: 2022-05-20T05:00:51.000Z

</details>

**Comment by Josh-Cena** [comment]
Seems to be fixed by https://github.com/mdn/content/pull/25222
