### ISSUE TITLE
`TypedArray#values()` is a copy of `Array#values()`

### ISSUE THREAD

**Issue by Phosra** [mdn/content#17789]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/values

### What information was incorrect, unhelpful, or incomplete?

The entire page appears to be a copy-and-paste of `Array#values()`.

### What did you expect to see?

A page relevant to `TypedArray#values()`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/typedarray/values`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/values
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
* Last commit: https://github.com/mdn/content/commit/edaa4aff4cf7532efdcba6014b9316aad2a5b6f1
* Document last modified: 2022-03-27T17:30:40.000Z

</details>

**Comment by wbamberg** [comment]
That's pretty weird.

It looks like the original import from the Wiki had the right content: https://github.com/mdn/content/blob/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630/files/en-us/web/javascript/reference/global_objects/typedarray/values/index.html but then the very next catch-up integration broke it https://github.com/mdn/content/pull/110/files#diff-45436b626c5ce68b9a02f7d351d7f60b8cc8c3096ca6b95e9253cbe7aa7baa8f.
