### ISSUE TITLE
TypedArray/fill polyfill is incorrectly described

### ISSUE THREAD

**Issue by Phosra** [mdn/content#17787]
### MDN URL

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/fill
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/some

### What specific section or headline is this issue about?

Polyfill

### What information was incorrect, unhelpful, or incomplete?

Although the `TypedArray` object is not a global, it can still be accessed via JavaScript.

### What did you expect to see?

A more accurate description, and/or a proper implementation that uses `TypedArray` itself.

The polyfill should likely be removed, and referenced via a link instead anyways.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/typedarray/fill`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/fill
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/typedarray/fill/index.md
* Last commit: https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e
* Document last modified: 2022-05-17T13:23:31.000Z

</details>

**Comment by wbamberg** [comment]
I would support deleting these polyfills.

We are already linking to the core-js polyfill in "See also".
