### ISSUE TITLE
CSP: report-to could reference Reporting-Headers in Examples and See Also

### ISSUE THREAD

**Issue by TimJohns** [mdn/content#17784]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to

### What specific section or headline is this issue about?

Examples, See Also

### What information was incorrect, unhelpful, or incomplete?

The Examples illustrate how the CSP headers can use the 'Report-To' header. An additional example could also illustrate how to use the Reporting-Endpoints header field. Similarly, the See Also section could reference the draft (or current) [Reporting API specification](https://w3c.github.io/reporting/), or other Reporting-Endpoints documentation within MDN or elsewhere.  

The validity of curly braces in the JSON content of Report-To are subject to some ambiguity (or at least prolific misunderstanding) by implementors, and also do not enjoy as wide adoption as the legacy inline report-uri. Folks implementing CSP headers in particular may therefore want to consider foregoing the use of Report-To entirely, and instead use a combination of the widely support report-uri inline, and new Reporting-Endpoints. Folks discovering the current article would at least benefit from some awareness of Reporting-Endpoints - even a brief not would be helpful.

Happy to take a crack at the edit myself, if no one picks up this issue. I'm looking for preemptive feedback on whether a broader doc update for the Reporting API is already in the works, and whether there is a 'supported format' or example I can follow, for referencing draft information.

Thanks, as always, and keep up the great work!

### What did you expect to see?

Perhaps a brief reference to the Reporting-Endpoints header

### Do you have any supporting links, references, or citations?

https://w3c.github.io/reporting/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/report-to`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/report-to/index.md
* Last commit: https://github.com/mdn/content/commit/e703747a072adc736f7a1931d2993250f81f70aa
* Document last modified: 2022-01-18T23:06:03.000Z

</details>

**Comment by sideshowbarker** [comment]
> Happy to take a crack at the edit myself

That would be great. I’ve gone ahead and assigned you.

> I'm looking for preemptive feedback on whether a broader doc update for the Reporting API is already in the works

I have seen no indication that such an update is in the works

> whether there is a 'supported format' or example I can follow, for referencing draft information

Can you elaborate on what you mean by that?

**Comment by TimJohns** [comment]
>>whether there is a 'supported format' or example I can follow, for referencing draft information

>Can you elaborate on what you mean by that?

Basically just wondering if there is an existing doc somewhere in [https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/) that I should copy the format from, specifically given that the [W3C reporting API document](https://w3c.github.io/reporting/) still shows "Editor's Draft" at this point. I am wondering if I need to emphasize "draft", although it seems unlikely that either the link to the W3C doc or the specific example I have in mind would change.

**Comment by teoli2003** [comment]
Avoid directly linking to the specs. If you need to add another relevant spec, you can add it in mdn/browser-compat-data. It would be added to the specification table: https://github.com/mdn/browser-compat-data/blob/main/http/headers/content-security-policy.json
