### ISSUE TITLE
Link for PermissionName enum broken in Permissions.query()

### ISSUE THREAD

**Issue by lumisce** [mdn/content#17792]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query

### What specific section or headline is this issue about?

Syntax > Parameters

### What information was incorrect, unhelpful, or incomplete?

The link for PermissionName enum in permissionDescriptor.name is gone.
It seems to be because the spec changed to use DOMString instead.

### What did you expect to see?

Updated description for permissionDescriptor.name

### Do you have any supporting links, references, or citations?

the broken link: https://w3c.github.io/permissions/#enumdef-permissionname
where it seems to be linked before: https://www.w3.org/TR/2022/WD-permissions-20220210/#dom-permissionname
after (see note): https://w3c.github.io/permissions/#query-method

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/permissions/query`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/permissions/query/index.md
* Last commit: https://github.com/mdn/content/commit/e49debb3767603670d43e1aba6819e8df77ed731
* Document last modified: 2022-06-02T04:30:13.000Z

</details>

**Comment by teoli2003** [comment]
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:
