### ISSUE TITLE
The example regular expression for urlMatches is incorrect

### ISSUE THREAD

**Issue by nevetsmik** [mdn/content#17798]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/events/UrlFilter

### What specific section or headline is this issue about?

urlMatches

### What information was incorrect, unhelpful, or incomplete?

The regular expression example is incorrect. The correct regular expression is `^[^:]*:(?:\/\/)?(?:[^/]*\.)?mozilla\.org\/.*$`

### What did you expect to see?

This `^[^:]*:(?:\/\/)?(?:[^/]*\.)?mozilla\.org\/.*$`

instead of this `^[^:]*:(?://)?(?:[^/]*\\.)?mozilla\\.org/.*$`

to match `https://mozilla.org/` and `https://developer.mozilla.org/`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/events/urlfilter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/events/UrlFilter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/events/urlfilter/index.md
* Last commit: https://github.com/mdn/content/commit/41276ffc6899705658b01d81a903f216a3c4f5f0
* Document last modified: 2022-05-04T05:04:14.000Z

</details>

**Comment by Josh-Cena** [comment]
The original code seems correct to me, though. This code is a string literal, not a regexp literal. String literals do not require the forward slashes to be escaped. (i.e. `"/" === "\/"`; `new RegExp("/")` and `new RegExp("\/")` are the same thing.)

**Comment by awxiaoxian2020** [comment]
> The original code seems correct to me, though. This code is a string literal, not a regexp literal. String literals do not require the forward slashes to be escaped. (i.e. `"/" === "\/"`; `new RegExp("/")` and `new RegExp("\/")` would both become `/\//`.)

except this, there is a `\` in `mozilla\\.org/`, there seems not correct

**Comment by Josh-Cena** [comment]
`"\."` is the same as `"."`, i.e., `new RegExp("\.")` is the same as `/./`. You need to "double escape" the backslash so it becomes a single backslash in the regex's source so that it stands for one single escape character. I find the original code fully correct.

**Comment by awxiaoxian2020** [comment]
> `"\."` is the same as `"."`, i.e., `new RegExp("\.")` is the same as `/./`. You need to "double escape" the backslash so it becomes a single backslash in the regex's source so that it stands for one single escape character. I find the original code fully correct.

the first `\` is escaped in `mozilla\\.org/` ?

**Comment by awxiaoxian2020** [comment]
I‘m not sure about this:
![20220701190656](https://user-images.githubusercontent.com/69554233/176883225-c5e2732f-c85e-4617-8692-cae4a11f77d4.png)
@Josh-Cena

**Comment by Josh-Cena** [comment]
This is a tester for regexp literals. Try running `new RegExp("...")` in your browser to see what it's transformed to.

**Comment by awxiaoxian2020** [comment]
> `"\."` is the same as `"."`, i.e., `new RegExp("\.")` is the same as `/./`. You need to "double escape" the backslash so it becomes a single backslash in the regex's source so that it stands for one single escape character. I find the original code fully correct.
The `.org` doesn't need `\` or `/`.

Why not "^[^:]*:(?://)?(?:[^/]*\\.)?mozilla\.org/.*$"

**Comment by Josh-Cena** [comment]
I have limited access to a computer today, but I suggest you try:

```js

console.log(new RegExp("^[^:]*:(?://)?(?:[^/]*\\.)?mozilla\.org/.*$")
  .exec("https://mozillaforg/"))

console.log(new RegExp("^[^:]*:(?://)?(?:[^/]*\\.)?mozilla\\.org/.*$")
  .exec("https://mozillaforg/"))
```

**Comment by awxiaoxian2020** [comment]
> I have limited access to a computer today, but I suggest you try:
> 
> ```js
> console.log(new RegExp("^[^:]*:(?://)?(?:[^/]*\\.)?mozilla\.org/.*$")
>   .exec("https://mozillaforg/"))
> 
> console.log(new RegExp("^[^:]*:(?://)?(?:[^/]*\\.)?mozilla\\.org/.*$")
>   .exec("https://mozillaforg/"))
> ```
> 
> Again... The main issue is that the "RegExp" here is a string literal, not a regex literal. They have different escaping rules.

![issue](https://user-images.githubusercontent.com/69554233/176899105-5dfaa327-f207-46fd-ad7a-2419925fd999.png)

**Comment by awxiaoxian2020** [comment]
> Yes, we can see that the second behavior is the desired one.

OK，I got it. Thank you very much indeed!

**Comment by Josh-Cena** [comment]
We'll close for now—we can reopen if it turns out that the example is proven wrong.
