### ISSUE TITLE
Issue with "Box-shadow generator": embedded iFrame is not tall enough for the content

### ISSUE THREAD

**Issue by arafalov** [mdn/content#1782]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator

#### What information was incorrect, unhelpful, or incomplete?
The embedded example iFrame seems to be not tall enough to fit the content. The explicit height seems to be provided in iFrame definition but - possibly - overriden by the `height: auto;` style that comes from somewhere else.

![iframe-too-short](https://user-images.githubusercontent.com/64153/105938286-4acdf480-6025-11eb-8a1f-acf228f54ac2.png)

#### Specific section or headline?
The generator iFrame

#### What did you expect to see?
A much taller component.

#### Did you test this? If so, how?
When I disabled height:auto in the debug console, it looked much better.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_background_and_borders/box-shadow_generator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/css_background_and_borders/box-shadow_generator/index.html
* Document last modified: 2021-01-13T18:01:00.000Z

</details>

**Comment by arafalov** [comment]
Oops. May be duplicate of #1653 (did not see it in time).

**Comment by chrisdavidmills** [comment]
Yup, it's a dupe; we'll close this one. Thanks @arafalov !
