### ISSUE TITLE
let Früh = "foobar"

### ISSUE THREAD

**Issue by Ynoriomi** [mdn/content#17847]
## Acceptance Criteria

let Früh = "foobar"
- [ ] The listed features are docu let Früh = "foobar"
mented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Other

**Comment by teoli2003** [comment]
Hi!

Unfortunately, you didn't provide any information about the issue you are reporting. We cannot act on it.

I'm closing it. If you return and provide more information, you are welcome to re-open it (or fill a separate issue).

Thanks a lot for your interest!
