### ISSUE TITLE
What's the distinction between Declarations and Statements?

### ISSUE THREAD

**Issue by sssrgo-dev** [mdn/content#17860]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

_Unlike var, let begins Declarations, not Statements. That means you cannot use a lone let declaration as the body of a block (which makes sense, since there's no way to access the variable)._

Here I see that var do not declare anything, everywhere it apears, it's exactly a statement. Even here:

var statementNotDeclarationAlvvays;
statementNotDeclarationAlvvays = 0;
console.log(statementNotDeclarationAlvvays);

And var appears in the "declarations" [here ->](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements)

### What did you expect to see?

I want to get more sense, why is that. My question is, why smthng is either a Declaration, or a Statement.
I only could suggest deal here is in moment of evaluation - at which: that Declaration is something, that is not evaluated during execution, but has already been evaluated at parsing phase, while Statetement evaluated after parsing at running code pase...

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/let`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/let/index.md
* Last commit: https://github.com/mdn/content/commit/dd389d21fdafc24e6683ba3003fab399c122dffd
* Document last modified: 2022-06-29T07:38:44.000Z

</details>

**Comment by Josh-Cena** [comment]
The statement/declaration distinction is a very technical one, and is almost only useful in syntactical production. You can see https://tc39.es/ecma262/#sec-ecmascript-language-statements-and-declarations

In general, a lot of syntactical constructs, like `if`, `while`, etc., only accept _Statement_s as their body. _Declaration_ is not a subset of _Statement_, but it's a member of _StatementListItem_, the latter of which can be part of a _Block_ (i.e. what goes in between the braces).

The more important part of the text here is the example we offer, that you can't use a lone `let` declaration as the body of a control-flow construct.

**Comment by sideshowbarker** [comment]
> We don't have any place where we thoroughly document syntactical productions—maybe we can make a new section under [developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar)?

👍 That would seem good yeah
