### ISSUE TITLE
Incorrect Reference

### ISSUE THREAD

**Issue by fuadinadhif** [mdn/content#17864]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_Colors_and_Luminance

### What specific section or headline is this issue about?

Modeling Light Color and Vision

### What information was incorrect, unhelpful, or incomplete?

> Note: Those familiar with the WCAG 2.x contrast math may notice that the above code uses the threshold value of 0.04045. This is the official IEC standard. The WCAG 2.0 guidelines were drafted citing an obsolete value. In May 2021, this was corrected to 0.04045 in the WCAG 2.1 document. For the record, the WCAG 2.0 value is 0.03928.

The WCAG 2.1 and 2.2 still use 0.03928 as the threshold value. The working draft (WCAG 3.0) neither specifies the relative threshold nor the relative luminance at all.

### What did you expect to see?

According to the published documents, WCAG still use 0.03928 as its threshold while calculating the relative luminance. Reference to the 0.04045 threshold value could only be found on IEC standard.

### Do you have any supporting links, references, or citations?

[WCAG 2.1](https://www.w3.org/TR/2018/REC-WCAG21-20180605/)
[WCAG 2.2](https://www.w3.org/TR/2021/WD-WCAG22-20210521/)
[WCAG 3.0](https://www.w3.org/TR/2021/WD-wcag-3.0-20211207/)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/accessibility/understanding_colors_and_luminance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_Colors_and_Luminance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/understanding_colors_and_luminance/index.md
* Last commit: https://github.com/mdn/content/commit/818ebacdc65e8a53727115cb72d49f9eddedc826
* Document last modified: 2022-06-22T05:18:35.000Z

</details>

**Comment by hiteshvijayhv** [comment]
Can I work on this?

**Comment by AnilSeervi** [comment]
Yes @hiteshvijayhv
You can work on it and PR a fix.

**Comment by sideshowbarker** [comment]
https://github.com/mdn/content/pull/18011 had a fix for this but was closed. Not sure why, but unless @hiteshvijayhv wants to open another PR for this, we still need someone to work on a fix

**Comment by hiteshvijayhv** [comment]
I will reopen PR I accidently deleted the fork so its closed

**Comment by sideshowbarker** [comment]
Hi @hiteshvijayhv 

> I will reopen PR I accidently deleted the fork so its closed

aha — OK, thanks, I’ve gone ahead and re-assigned it to you
