### ISSUE TITLE
'Edit' option, as have been mentioned in article is missing from top of that page

### ISSUE THREAD

**Issue by bappyasif** [mdn/content#17867]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction

### What specific section or headline is this issue about?

[Controlled access to content](https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction#controlled_access_to_content)

### What information was incorrect, unhelpful, or incomplete?

' currently it states in this paragraph, there is a way to edit that page, but it's (edit functionality) not there or not visible

> The site you are on right now controls access to content: articles are visible to everyone, but only users who have logged in can edit them. To try this, click on the **Edit** button at the **_top of this page_** — if you are logged in you will be shown the edit view; if you are not logged in you will be taken to the sign-up page.

### What did you expect to see?

expected to see a "Edit" button of functionality at top of that article or page

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/first_steps/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/first_steps/introduction/index.md
* Last commit: https://github.com/mdn/content/commit/0737c998b877303232cc52442888acb1ab2dde24
* Document last modified: 2022-04-19T05:43:55.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #17882 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
