### ISSUE TITLE
CSS “:focus-visible“ article: “Click me” live sample is broken

### ISSUE THREAD

**Issue by LarsAlaska** [mdn/content#17881]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

### What specific section or headline is this issue about?

'Click me' example is broken half way down page after final focus-visible example

### What information was incorrect, unhelpful, or incomplete?

the example is broken

### What did you expect to see?

a working example

**Comment by awxiaoxian2020** [comment]
I think this issue should be transfered to https://github.com/mdn/css-examples

**Comment by teoli2003** [comment]
No, _live samples_ are stored directly on the page. Only _interactive examples_ (the boxes at the top) are at mdn/css-examples.

**Comment by awxiaoxian2020** [comment]
> No, _live samples_ are stored directly on the page. Only _interactive examples_ (the boxes at the top) are at mdn/css-examples.

My fault. I found it now. Thanks!
