### ISSUE TITLE
Generated webcam video is not playing in Mac's quick time player 

### ISSUE THREAD

**Issue by SagarPrajapati98** [mdn/content#1788]
`function startRecording(stream, lengthInMS) {

var options = {
audioBitsPerSecond: 128000,
videoBitsPerSecond: 2500000,
mimetype: 'video/mp4;codecs=h264'
}
recorder = new MediaRecorder(stream, options);

recorder.ondataavailable = event => data.push(event.data);
recorder.start();
log(recorder.state + " for " + (lengthInMS / 1000) + " seconds...");

let stopped = new Promise((resolve, reject) => {
recorder.onstop = resolve;
recorder.onerror = event => reject(event.name);
});

let recorded = wait(lengthInMS).then(
() => recorder.state == "recording" && recorder.stop()
);

return Promise.all([
stopped,
recorded
])
.then(() => data);
}`

i have used the above code and it's generating video for me and i am able to play video in vlc media plater but when i try to play it with quick time player in mac os it's not playing video and showing file couldn't 

The document “RecordedVideo.mp4” could not be opened. 
The file isn’t compatible with QuickTime Player.

Thank you.

**Comment by Ryuno-Ki** [comment]
Dear @SagarPrajapati98,
could you tell us on which page this code snippet appeared?

**Comment by SagarPrajapati98** [comment]
I have html page and i want record video using MidiaRecorder and save it to azure

**Comment by Ryuno-Ki** [comment]
Thanks for the clarification,
sadly, we don't have the capacity to aid you on resolving your problem.
I'd recommend to open a question on stackoverflow.com and ask for help there.
This might require to provide a minimum working example.
