### ISSUE TITLE
Outdated link to 'is' attribute

### ISSUE THREAD

**Issue by ygoe** [mdn/content#17890]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

### What specific section or headline is this issue about?

High-level view

### What information was incorrect, unhelpful, or incomplete?

> Customized built-in elements inherit from basic HTML elements. To create one of these, you have to specify which element they extend (as implied in the examples above), and they are used by writing out the basic element but specifying the name of the custom element in the [is](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-is) attribute (or property).

The "is" link href seems outdated. Now there is a separate page for the attribute, which can be found on the currently linked page. The current link only goes to the global attributes page at the very top, for the user to find it themselves.

I didn't know how to update this because it's not using links but some other fancy syntax in the article source.

### What did you expect to see?

A direct link to the page for the "is" attribute

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/web_components/using_custom_elements/index.md
* Last commit: https://github.com/mdn/content/commit/30422c6623028eddb267cfb09906ae686718b9d8
* Document last modified: 2022-05-24T05:31:18.000Z

</details>

**Comment by cw118** [comment]
Thanks for reporting @ygoe ! I created a PR that should fix this link (and I also found another similar broken link/macro thanks to this) :)
