### ISSUE TITLE
Given Task 1 Incorrect

### ISSUE THREAD

**Issue by chandrakumarprajapati** [mdn/content#17916]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_tasks

### What specific section or headline is this issue about?

Task 1

### What information was incorrect, unhelpful, or incomplete?

Given task :- In this task, you have an image that is overflowing the box. We want the image to scale down to fit inside the box without any extra white space, but we do not mind if some part of the image is cropped.

My solution :- .box img {
                              object-fit: cover;
                                       }
 Result :- Image did not get fitted into the box size provided by MDN

 Explain :- MDN had given me a task 1 to fit the image in the box provided. The image was overflowing ; I applied helpful CSS to the img selector as provided above to target the image, but my CSS did not get applied to the task. Is there any mistake ; I had made or is there any CSS incorrect property applied please help?

### What did you expect to see?

When I applied  "object-fit" property with value of "cover" to img selector, the image should be fit into the box (border: 5px solid #000; width: 400px; height: 200px;)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/images_tasks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_tasks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/images_tasks/index.md
* Last commit: https://github.com/mdn/content/commit/50bdaf8e0c85f675efbd944c4bc67555843bf545
* Document last modified: 2022-06-07T16:49:18.000Z

</details>

**Comment by cw118** [comment]
Hi @chandrakumarprajapati, I believe this is because the property `object-fit` will only affect an image if you have specified a width and height for that image (note that the width and height don't need to be absolute values like `200px`).

You may also find this [stackoverflow question and its answers](https://stackoverflow.com/questions/34247337/object-fit-not-affecting-images) helpful :)

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/17916#issuecomment-1173107489
