### ISSUE TITLE
Valid link in Markdown but invalid in HTML

### ISSUE THREAD

**Issue by phwt** [mdn/content#17919]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

### What information was incorrect, unhelpful, or incomplete?

The "this list" part of this quote does not direct to "[Information responses](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#information_responses)" as intended.

> **Note:** If you receive a response that is not in [this list](#information-responses), it is a non-standard response, possibly custom to the server's software.

### What did you expect to see?

The `[this list](#information-responses)` is a valid link to `## Information responses` in Markdown but not when rendered as HTML.

This can be tested out by visiting the links below:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#information-responses (does not scroll to the anchor)
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#information_responses (scroll to the correct anchor)

Changing `-` to `_` will make this a valid link in HTML but will break the link in Markdown.

```diff
- [this list](#information-responses)
+ [this list](#information_responses)
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/index.md
* Last commit: https://github.com/mdn/content/commit/73cc9b528b45a869992d268f119853021b33d454
* Document last modified: 2022-05-28T11:16:55.000Z

</details>

**Comment by phwt** [comment]
I wish to fix this myself but I'm not sure what to do because this does break the link in Markdown format. So, I opened an issue instead :)

**Comment by Josh-Cena** [comment]
Yes, please just fix the link. There's nothing as "valid anchor link in Markdown"—Markdown anchor behavior is completely implementation defined. We only care about the generated HTML's semantics.

**Comment by phwt** [comment]
Thanks for the clarification! I've just submitted the PR.
