### ISSUE TITLE
…on testing

### ISSUE THREAD

**Issue by ny-yks** [mdn/content#17943]
…on testing

This is a fully functioning Windows + Linux enterprise lab network virtualized with Vagrant + Ansible.  This network can be used to learn and practice network penetration testing.  I created it specifically as a companion learning tool for my book "The Art of Network Penetration Testing" 

_オリジナルは @R3dy が https://github.com/Hack-with-Github/Awesome-Hacking/pull/124 にポスト_

_オリジナルは @ny-yks が https://github.com/algorand/sandbox/issues/133 にポスト_

**Comment by teoli2003** [comment]
Sandbox, or spam.
