### ISSUE TITLE
No detailed description of what happens when radix isn't provided

### ISSUE THREAD

**Issue by rgeller** [mdn/content#17940]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

At the bottom of the Parameters section, there's a red warning message that says "Warning: The description below explains in more detail what happens when radix is not provided." However, the only mention of this is in reference to octal digits. I think more detailed information would be useful.

### What did you expect to see?

A detailed description of what happens when the radix argument is not provided.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/parseint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/parseint/index.md
* Last commit: https://github.com/mdn/content/commit/8253c65080eca815b1874b77d33e14c72cf37914
* Document last modified: 2022-06-20T13:19:49.000Z

</details>

**Comment by Josh-Cena** [comment]
> A value passed as the radix argument is coerced to a Number (if necessary), then if the value is 0, NaN or Infinity (undefined is coerced to NaN), JavaScript assumes the following:
>
> If the input string begins with "0x" or "0X" (a zero, followed by lowercase or uppercase X), radix is assumed to be 16 and the rest of the string is parsed as a hexadecimal number.
If the input string begins with any other value, the radix is 10 (decimal).
Else if the radix value (coerced if necessary) is not in range [2, 36] (inclusive) parseInt returns NaN.

I think that explains it quite clearly?
