### ISSUE TITLE
/en-US/docs/Web/CSS/@media/forced-colors and approximate implementation in EdgeHTML

### ISSUE THREAD

**Issue by WebMechanic** [mdn/content#1795]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

Add cross reference to the current and applicable _non standard_ implementation of `forced-colors-*` in EdgeHTML (Edge 18-) on MDN; `-ms-high-contrast`  and `-ms-high-contrast-adjust`.

# Details
EdgeHTML implements 
- `-ms-high-contrast` using values `active, black-on-white, white-on-black` (and `none` prior Edge/18) ([MSDoc](https://docs.microsoft.com/en-us/previous-versions/hh771830(v=vs.85))) and
- `-ms-high-contrast-adjust` using values `auto, none` ([MSDoc](https://docs.microsoft.com/en-us/previous-versions/hh771863%28v%3dvs.85%29))

Both are virtually equivalent to what `forced-colors` and `forced-colors-adjust` aim to achieve --once implemented anywhere-- and are also documented on MDN. `-ms-high-contrast` actually links to `forced-colors`, however `-ms-high-contrast-adjust` has no such __Remarks__ section to recommend using `forced-colors-adjust`.
I'd be willing to at least add a similar "Remarks" section to `-ms-high-contrast-adjust` for parity if that's ok.
Also M*S*DN has thorough reference documentatiion of these properties (check "MSDoc" link above) that I'd link to as well.

I don't know the policy on linking from Standards to proprietary extension, especially if said Standard is not implemented in any browser  -- or proably won't be [in the near future](https://caniuse.com/#search=forced-colors).
There are several pages that do so (mostly for `-webkit-`) such as `@media`.

**Comment by rachelandrew** [comment]
I documented `forced-colors-adjust` and mentioned the prefixed property https://developer.mozilla.org/en-US/docs/Web/CSS/forced-color-adjust

Does that solve the issue @WebMechanic ?
