### ISSUE TITLE
/en-US/docs/Web/API/Media_Session_API

### ISSUE THREAD

**Issue by marto55555** [mdn/content#1797]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The examples should be updated to include the recently added actions: `stop` and `seekto`.
Source: [https://github.com/w3c/mediasession/blob/master/explainer.md](https://github.com/w3c/mediasession/blob/master/explainer.md)

**Comment by Rumyra** [comment]
Examples were added with page updates - closing this
