### ISSUE TITLE
/en-US/docs/Web/API/MediaSession/setActionHandler

### ISSUE THREAD

**Issue by marto55555** [mdn/content#1798]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In Syntax > Parameters > type, the docs should include the recently added `MediaSessionAction`s: `stop` and `seekto`.
The examples should be updated as well.
Source: [https://github.com/w3c/mediasession/blob/master/explainer.md](https://github.com/w3c/mediasession/blob/master/explainer.md)

**Comment by Rumyra** [comment]
Same as before - already included
