### ISSUE TITLE
Calculating specificity

### ISSUE THREAD

**Issue by muwecurt** [mdn/content#17987]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

### What specific section or headline is this issue about?

Specificity

### What information was incorrect, unhelpful, or incomplete?

I am still a newbie learning CSS from the MDN website. I am not sure but thought it may have been an oversight from the content creators. 

The table calculating specificity for the selector button:not(#mainBtn, .cta)

### What did you expect to see?

I expected to see a total specificity of 1-1-1

### Do you have any supporting links, references, or citations?

1 element - button
1 class - .cta
1 id - #mainBtn

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
* Last commit: https://github.com/mdn/content/commit/efb58165766cb66558d19c1972664e0673dc8b10
* Document last modified: 2022-07-04T12:43:59.000Z

</details>

**Comment by teoli2003** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity, only the highest parameter of `:not()` counts so 1-1-0 if I count correctly.

**Comment by muwecurt** [comment]
much appreciation teoli2003
