### ISSUE TITLE
Include the `this` object in method syntax

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#17981]
### MDN URL

Taking https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map as example

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

The "syntax" is incomplete: `map((element) => { /* ... */ })` does not highlight the fact that the method needs to have a correct `this` bound.

For example, if you do:

```js
const { map } = [1, 2, 3];
map((e) => console.log(e));
```

It throws: `TypeError: Array.prototype.map called on null or undefined`

### What did you expect to see?

For all methods that require the correct value of `this`, we should treat `this` as part of the parameters (it actually is, in many interpretations of ECMAScript semantics), and include it in both the "Syntax" and "Parameters" section.

For example, here we can write:

```js
array.map((element) => {/* ... */})
```

And then in "Parameters", add:

> - `array`
>    - : An Array, or array-like object. It will be the `this` context of the `map` method.

This is especially important for array and string methods, because they are intentionally designed to be generic, i.e. they don't require `this` to be an array/string exotic object, but can be anything that "behaves" like an array/string.

### Do you have any supporting links, references, or citations?

https://tc39.es/ecma262/#sec-array.prototype.map:

> The `map` function is intentionally generic; it does not require that its `this` value be an Array. Therefore it can be transferred to other kinds of objects for use as a method.

**Comment by teoli2003** [comment]
I would say, just this (without a mention in parameters)

> array.map((element) => {/* ... */})

I think pretty everybody understands that the `this` will be bound to the _array_.

**Comment by teoli2003** [comment]
And this as a "bad-example" (` ```js bad-example ` if I remember correctly) in the _Examples_ section?

> ```
> const { map } = [1, 2, 3];
> map((e) => console.log(e));
> ```
> 
> It throws: `TypeError: Array.prototype.map called on null or undefined`

**Comment by Josh-Cena** [comment]
The more important part is that `Array.prototype.map`, as a function, does not require `this` to be an array.

```js
Array.prototype.map.call({ 0: 1, 1: 2, 2: 3, length: 3 }, (e) => console.log(e));
```

So to some extent, the `array` is part of the parameters, because it is also meaningfully customizable.

**Comment by teoli2003** [comment]
I see: what is the condition on a `this` for `.map()` to work on it?

**Comment by Josh-Cena** [comment]
Many methods in ECMA262 have an editorial note saying it's "intentionally generic". Such methods usually use duck-typing and only require the object to behave to the extent needed by the method. For example, `map` reads the `length` property of `this`, uses `constructor.@@species` to construct the new array, and then index-accesses each number index between 0 and the length, so it only requires those properties to be accessible.

**Comment by teoli2003** [comment]
Thinking aloud.

We could keep the `array` in the syntax box, as this is the most common use case, and add a note below it. Something like:

> *Note:* This method is _intentionally generic_ and also works with objects that are not `Array` objects as long as they have a `length` property, have `constructor.@@species` accessible and allow for accessing using an index each number between 0 and the length.

This would also work for other _intentionally generic_ features. We could link _intentionally generic_ to a new glossary entry about _duck-typing_ with some more generic explanation.

**Comment by Josh-Cena** [comment]
That sounds good as well.

**Comment by hamishwillee** [comment]
Isn't the `this` context provided by `thisArg`?

**Comment by hamishwillee** [comment]
Thanks. I don't understand why the this belonging to the array matters, so I'll exit the discussion.

**Comment by Josh-Cena** [comment]
Yes, that's true. I'll probably start with JS APIs, but it equally applies to web APIs as well.

**Comment by Josh-Cena** [comment]
We can probably ignore that in "Parameters" in this case, but the fact that it throws makes it more essential to be demonstrated in the "Syntax" part.

**Comment by Josh-Cena** [comment]
I've started a discussion at https://github.com/mdn/mdn-community/discussions/148. Until we reach consensus there, we'll keep this closed.

**Comment by teoli2003** [comment]
Thank you!
