### ISSUE TITLE
Issue with ":focus-visible": Incorrect link to specification

### ISSUE THREAD

**Issue by questionmarcus** [mdn/content#1799]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

#### What information was incorrect, unhelpful, or incomplete?

The link to the :focus-visible definition did not direct me to a W3C draft document, but to a directory without any specification files within it.

#### Specific section or headline?

[Specifications section](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#specifications)

#### What did you expect to see?

I would expect to be taken to the correct specification document: https://www.w3.org/TR/2018/WD-selectors-4-20181121/#the-focus-visible-pseudo.

#### Did you test this? If so, how?

I opened the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_focus-visible`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/_colon_focus-visible/index.html
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by rachelandrew** [comment]
@questionmarcus this seems to be an issue with CSS specifications rather than an MDN issue, it's the same for all the spec I tried. I imagine it will be fixed before too long.
