### ISSUE TITLE
Issue with "What is a web server?": …

### ISSUE THREAD

**Issue by IlyaMalanin** [mdn/content#1800]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_web_server

#### What information was incorrect, unhelpful, or incomplete?
When I click on the "Kuma" hyperlink, the "Yari: Men's rendering platform" page opens.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/common_questions/what_is_a_web_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_web_server
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/common_questions/what_is_a_web_server/index.html
* Document last modified: 2021-01-22T12:33:05.000Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @IlyaMalanin . That whole line doesn't really make sense any more now our underlying platform has changed, so I've removed it, and made a few other tweaks. See https://github.com/mdn/content/commit/6cd8fd2ae19f2acaa1f25e538cfc55de5a03dd6f
