### ISSUE TITLE
HTML class names

### ISSUE THREAD

**Issue by cb-acustaf** [mdn/content#18036]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class

### What specific section or headline is this issue about?

The top description

### What information was incorrect, unhelpful, or incomplete?

It is written that class names are case sensitive.
I have found that both Chrome and Safari apply CSS to elements on a web page in a case insenstive manner.
I have not tested with any other browsers.
e.g.
<button class="contextMenu" ...
will get any of the following CSS applied
.ContextMenu {
  ...
}
.CONTEXTMENU {
 ...
}

### What did you expect to see?

Given the observed behavior, I would expect to see the description say that class names are case insensitive.

### Do you have anything more you want to share?

I did follow the link in the article to the HTML documentation.  That documentation does not say much of anything.  Needless to say it is inconclusive how class names should be parsed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/class`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/class/index.md
* Last commit: https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e
* Document last modified: 2022-05-17T13:23:31.000Z

</details>

**Comment by teoli2003** [comment]
I tried with the `Try it` and changed `note` to `Note`, both in Firefox and Chrome.

Clearly, it was case-sensitive. You must have something else interfering.
