### ISSUE TITLE
Requset supprt  or info for W3,CSS

### ISSUE THREAD

**Issue by winniejo** [mdn/content#1803]
I looked up w3.css issues but could not find any. 
my Requset supprt  or info for W3,CSS

Winn

**Comment by chrisdavidmills** [comment]
Hi @winniejo. I don't understand what you are asking here. Issues on this repo should be about reporting problems with the content on https://developer.mozilla.org.

**Comment by winniejo** [comment]
Hay @ chrisdavidmills ,

?W3.CSS" is a CSS framework (strictly html css no JS).
I was wondering if ir is possible to give some pointers for working with "W3.CSS".  
since i can find advice of CSS , Grid, Bootstrap, JS, etc. and all other topics.

Winn

**Comment by chrisdavidmills** [comment]
@winniejo I'm afraid not. We mainly cover the underlying native browser technologies — HTML, CSS, JavaScript, etc. — but we don't have much coverage of frameworks. Generally they just aren't in our remit.

**Comment by winniejo** [comment]
Ok thanks, Iam just asking since there are some Bootstrap topics explained in 
MDN Webdocs and W3.CSS is more like Grid then Boostrap I regain.

Winn
