### ISSUE TITLE
input tel web page has extraneous content

### ISSUE THREAD

**Issue by DG12** [mdn/content#1804]
URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel

Browser / Version: Firefox 84.0
Operating System: Mac OS X 10.16
Tested Another Browser: Yes Chrome and safari

Problem type: Design is broken

several lines similar to
{{page("/en-US/docs/Web/HTML/Element/input/text", "list", 0, 1, 2)}}
{{page("/en-US/docs/Web/HTML/Element/input/text", "placeholder", 0, 1, 2)}}
{{page("/en-US/docs/Web/HTML/Element/input/text", "readonly", 0, 1, 2)}}
{{page("/en-US/docs/Web/HTML/Element/input/text", "size", 0, 1, 2)}}

appear on the page.

I have also checked Safari and firefox.

**Comment by chrisdavidmills** [comment]
Oops, yes, looks like the {{ page }} macro calls aren't being rendered, are are instead being spat out onto the screen. Thanks for reporting this @DG12 

@escattone sorry to bug you, but you worked on something related to this reecently. Any thoughts here?

**Comment by Elchi3** [comment]
See also https://github.com/mdn/content/issues/1819. Something funky is going on with {{ page }}

**Comment by Ryuno-Ki** [comment]
Shoot! @Elchi3 was faster! :-D
Thanks for crosslinking.

**Comment by escattone** [comment]
Thanks everyone. I noticed this yesterday as well, and created #1774 (which was fixed by #1775). However, it can take up to 48 hours for changes to be seen at https://developer.mozilla.org (due to our build schedule and CDN caching) so the changes were finally visible today. This is resolved.

**Comment by DG12** [comment]
Surprised you would close this before it is visible.
