### ISSUE TITLE
Change generator example default end value from 10 to infinity.

### ISSUE THREAD

**Issue by JohnLukeBentley** [mdn/content#18066]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#generator_functions

### What information was incorrect, unhelpful, or incomplete?

The example under "Generator functions" has a signature as follows ...

    function* makeRangeIterator(start = 0, end = 100, step = 1) {

### What did you expect to see?

I suggest we change the default for the end parameter to Infinity, so that we have:

    function* makeRangeIterator(start = 0, end = Infinity, step = 1) {

### Do you have anything more you want to share?

This is in order to make it functionally equivalent to the `makeRangeIterator` found under [Iterators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#iterators). Otherwise the example under "Generator functions" leaves upon the implication that generators can't handle infinity as a default argument (I'm assuming that, indeed, generators and vanilla iterators are both so able).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/iterators_and_generators`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/iterators_and_generators/index.md
* Last commit: https://github.com/mdn/content/commit/c66bfef4fbe37744579bfed6dcecd7c7b73741c2
* Document last modified: 2022-07-05T06:55:27.000Z

</details>

**Comment by Josh-Cena** [comment]
Feel free to send a PR.

**Comment by JohnLukeBentley** [comment]
Thanks. Will do (at some point soon™).
