### ISSUE TITLE
css.properties.font-size - I found a wrong character in the document

### ISSUE THREAD

**Issue by Elliemis** [mdn/content#1806]
#### What information was incorrect, unhelpful, or incomplete?
here is the text of the document

rem
rem 값은 합성 문제를 회피하기 위해 고안되었습니다. rem 값은 부모 엘리먼트가 아니라 최상위 html 엘리먼트에 상대적입니다. 다르게 표현하면, rem 은 부모 크기에 의해 폰크 크기가 정해지지 않도록 하여 합성 문제를 제거합니다.

and here is the wrong character

...크기에 의해 "폰크" 크기가...

#### What did you expect to see?
"폰크" should be changed to "폰트" which means Font

#### Did you test this? If so, how?
I think this problem is simple enough to skip test

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.font-size`
* MDN URL: https://developer.mozilla.org/ko/docs/Web/CSS/font-size
* Report started: 2021-01-27T00:12:48.525Z

</details>

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
