### ISSUE TITLE
Extending documentation of "Interact with the clipboard"

### ISSUE THREAD

**Issue by cyMarvin** [mdn/content#1807]
I think it's worth mentioning that using execCommand() does not work on input fields of type="hidden" with html5 attribute "hidden" or any matching CSS rule using "display: none;".

It's quite common to use "copy to clipboard" buttons for span, div or p tags. Therefore one creates a hidden input field to make use of execCommand('copy') - which then doesn't work.
Maybe this could be mentioned in the documentation with a workaround (like setting the input's position to absolute and moving it out of the viewport).

---

MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@chrisdavidmills You edited the `execCommand()` page recently - is it still something to recommend on the WebExt space?

**Comment by chrisdavidmills** [comment]
@Ryuno-Ki I don't see why not. The main negative point about it is its implementation inconsistency, but if you are only worrying about a single platform...

**Comment by Josh-Cena** [comment]
Fixed by #9344
