### ISSUE TITLE
Wrong Promise.prototype.finally() description

### ISSUE THREAD

**Issue by HelpMe-Pls** [mdn/content#18082]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

There are 2 paragraphs in the [Description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally#description) where I found to be misleading due to the fact that I tried to execute those expressions and the output is not as mentioned:
![image](https://user-images.githubusercontent.com/43715386/177818279-11131020-ce21-4b15-8121-927271be4445.png)
  

### What did you expect to see?

- When I executed `Promise.reject(3).then(() => {}, () => 88)`, it returns a fulfilled promise with the value `88` (**not** "_return a rejected promise with the reason `88`_" as mentioned in the section):
![image](https://user-images.githubusercontent.com/43715386/177819489-2d99a5ef-c530-4b5a-9e51-debded9e58fd.png)

Which matches the [return value of the `Promise.prototype.then()` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#return_value):
![image](https://user-images.githubusercontent.com/43715386/177819765-e6802370-4e34-4e49-ae55-0fd038690cf8.png)

- The `Promise.reject(3).finally(() => throw 99)` actually throws an uncaught exception:
![image](https://user-images.githubusercontent.com/43715386/177820343-495adfa8-d32b-4d28-9132-c4feb6d6c704.png)

Which I believe just a typo. Can be fixed by adding a pair of curly braces: `Promise.reject(3).finally(() => {throw 99});`

- The execution of `Promise.reject(3).finally(() => Promise.reject(99))` actually returns a rejected promise with the reason `99`:
![image](https://user-images.githubusercontent.com/43715386/177821130-b434abca-af5c-4294-9bcf-403b368ad4d3.png)

Which abides by the [return value of the `Promise.prototype.finally()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally#return_value) method:
![image](https://user-images.githubusercontent.com/43715386/177821704-dcedc8fa-cec9-4309-ac88-15734270d1f2.png)

- Assuming the typo from `Promise.reject(3).finally(() => throw 99)` is fixed (because if it were intended to be syntactically wrong, the author should've mentioned that), the phrasing with "either...or" isn't the right choice of words, because they **BOTH** will return a promise that is rejected and has a value of `99`.

### Do you have any supporting links, references, or citations?

Already listed above.

### Do you have anything more you want to share?

I'm still learning Promise and its related topics so I'm unable to formulate a definitive example for that case. I'd like the reviewers to have their insights on this and maybe come up with a better code sample to ease in the reading process.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise/finally`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
* Last commit: https://github.com/mdn/content/commit/4e4ec5dbe15ae4883201057aaab8833dd33b7a05
* Document last modified: 2022-06-30T11:02:34.000Z

</details>

**Comment by hiteshvijayhv** [comment]
Can I work on this?

**Comment by HelpMe-Pls** [comment]
@hiteshvijayhv Yes please :ok_hand:
If you have any practical examples to signify the use cases of this particular event:
![image](https://user-images.githubusercontent.com/43715386/177912324-f04e9955-2361-4913-a614-516dacc2c89f.png)

Then your contribution is definitely most welcomed :sparkles:

**Comment by Josh-Cena** [comment]
Yes, the first one is definitely wrong—the `onRejected` handler returning normally would still cause the promise to fulfill.

**Comment by HelpMe-Pls** [comment]
@Josh-Cena Most definitely.
As a learner, I found those statements very confusing.

**Comment by hiteshvijayhv** [comment]
> @hiteshvijayhv Yes please 👌 If you have any _**practical**_ examples to signify the use cases of this particular event: ![image](https://user-images.githubusercontent.com/43715386/177912324-f04e9955-2361-4913-a614-516dacc2c89f.png)
> 
> Then your contribution is definitely most welcomed ✨

From what I found is that finally() is used to place the code that is executed after the Promise is executed and we want to free up the resources. And this is what that is mentioned there in the docs.

I think this issue is for correcting the doc error instead of addition of more examples.

I will open a new issue regarding the practical implementation of finally()

**Comment by HelpMe-Pls** [comment]
@hiteshvijayhv Sure.
Let's make the document better for the fellow learners.

**Comment by hiteshvijayhv** [comment]
I will make a new PR with all fix sorry for messing up

**Comment by HelpMe-Pls** [comment]
No worries. Keep up the good work 💯

**Comment by hiteshvijayhv** [comment]
> No worries. Keep up the good work 💯

Thanks a lot.
