### ISSUE TITLE
Life360

### ISSUE THREAD

**Issue by tacokitty12** [mdn/content#18129]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Guide/WOFF

### What specific section or headline is this issue about?

Life360

### What information was incorrect, unhelpful, or incomplete?

I can’t open this 

### What did you expect to see?

I don’t know 

### Do you have any supporting links, references, or citations?

<attachment webkitattachmentid="884a9410-7322-4af8-a555-2e8de7d9f789" src="cid:0B0160A4-44BE-4D32-82BD-30A3B53F3749" title="drivingHistoryJSON" type="public.plain-text" subtitle="20 KB" style="font-family: UICTFontTextStyleBody; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: none; -webkit-text-stroke-width: 0px; text-decoration: none;"></attachment>

### Do you have anything more you want to share?

Help

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/guide/woff`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/WOFF
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/woff/index.md
* Last commit: https://github.com/mdn/content/commit/54e3339c1e6036a74d27bcaf927942c4b2315dd7
* Document last modified: 2022-06-21T06:33:12.000Z

</details>

**Comment by hiteshvijayhv** [comment]
I can open the url. Can you explain more?

**Comment by tacokitty12** [comment]
It’s a Life360 log I got from a report of mine
