### ISSUE TITLE
Possible description errors in "How whitespace is handled by HTML, CSS, and in the DOM" article

### ISSUE THREAD

**Issue by ktrNozomi** [mdn/content#18181]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace#how_does_css_process_whitespace

### What information was incorrect, unhelpful, or incomplete?

In the "Explanation" subsection, I notice the description doesn't correspond to the code.

![Snipaste_2022-07-10_20-53-05](https://user-images.githubusercontent.com/86712470/178145811-ccd82faa-09d4-42ad-8555-4bb863fe69c0.png)

### What did you expect to see?

I am not sure if the correct sentence is "And finally, sequences of spaces at the beginning and end of a <del>line</del> <ins>element</ins> are removed, so we finally get this:"

### Do you have any supporting links, references, or citations?

No

### Do you have anything more you want to share?

No

**Comment by hiteshvijayhv** [comment]
I think element is a more appropriate word. Can I make a PR?

**Comment by sideshowbarker** [comment]
> I think element is a more appropriate word. Can I make a PR?

@hiteshvijayhv Please do
