### ISSUE TITLE
Properties of Function vs. Function.prototype

### ISSUE THREAD

**Issue by js-choi** [mdn/content#18188]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

### What specific section or headline is this issue about?

Article title

### What information was incorrect, unhelpful, or incomplete?

The properties of Function instances (`length` and `name`, and I guess the deprecated/nonstandard `arguments`, `caller`, and `displayName`) are named as properties of the Function constructor (e.g., `Function.length`). While it is true that, as a Function itself, the [Function constructor has constant `length` and `name` properties](https://tc39.es/ecma262/#sec-properties-of-the-function-constructor), they are also [present on all Function instances](https://tc39.es/ecma262/#sec-function-instances).

I think it is misleading to title these properties as `Function.length`, etc.—this naming implies that they are present only on the Function constructor rather than Function intsances. It is also inconsistent with how other objects treat their instance properties—e.g., `Array.prototype.length`.

### What did you expect to see?

I expected to see these properties titled `Function.prototype.length`, `Function.prototype.name`, etc. Although `length` and `name` are not strictly speaking inherited from `Function.prototype`, this situation is little different from “exotic” properties on [exotic objects](https://tc39.es/ecma262/#exotic-object), such as [`Array.prototype.length`](https://tc39.es/ecma262/#sec-properties-of-array-instances). It’s less misleading to distinguish them as instance objects using `Function.prototype`.

### Do you have any supporting links, references, or citations?

Links to sections in Ecma262 are given above.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/function/index.md
* Last commit: https://github.com/mdn/content/commit/85e526f765521133b837e2465b02bc05432a0934
* Document last modified: 2022-06-27T06:55:54.000Z

</details>

**Comment by Josh-Cena** [comment]
See https://github.com/mdn/content/issues/16325—Frankly I don't know the final resolution for this and I'm not really satisfied with `Function.prototype.length`.

**Comment by js-choi** [comment]
Thanks; I hadn’t seen #16325, which is about whether the Array-instance `length` property should be titled `Array.prototype.length`. This is an interesting question because, indeed, the Array-instance `length` property does not come from `Array.prototype`. One could argue that this is also misleading. [Ecma262 just calls it a “property of Array instances”](https://tc39.es/ecma262/#sec-properties-of-array-instances), and it [also calls `fn.length` a “property of Function instances”](https://tc39.es/ecma262/#sec-function-instances). So we could argue that `Array.prototype.length` would be best titled with something like “Array instance `length`”. (I would say that it would be much worse to call it `Array.length`; that is definitely wrong.)

It seems that #16325 was resolved in favor of keeping the `Array.prototype.length` title. @hamishwillee says, “In the JavaScript section of MDN using prototype in the title - such as Array.prototype.length is how you indicate that it is an instance variable. If it was Array.length you would know it was a static variable.”

I agree that it may eventually be good to rename `Array.prototype.length` to something like “Array instance `length`”. But that’s another issue. 

In the meantime, it would be most consistent to rename `Function.length` to match `Array.prototype.length`, right? It’s a very parallel situation, and @hamishwillee’s statement probably applies to Function instance properties just as much as it applies to Array instance properties.

**Comment by Josh-Cena** [comment]
Correct—I'm very much in favor of getting rid of `Function.length` (also mentioned in that issue) and replacing it with `Function.prototype.length` seems like the best resolution for the time being.
