### ISSUE TITLE
Negative connotative language regarding asm.js examples

### ISSUE THREAD

**Issue by Phosra** [mdn/content#18192]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/clz32

### What specific section or headline is this issue about?

Description/Examples

### What information was incorrect, unhelpful, or incomplete?

There are a few small comments written in a negative tone on the page in the examples written in asm.js. Some examples are "ASMjs for some reason does not allow ...," and "unfortunately, ASM.JS demands slow crummy objects," while the comments aren't very helpful.

Furthermore, considering that ASM.js is deprecated(?), how about replacing these examples with examples showing realistic usage of what the page is supposed to document: *`Math.clz32`*, because as it stands, it just shows an academic example of counting in the opposite direction.

### What did you expect to see?

Straightforward comments such as "ASMjs prohibits ...," and "ASM.JS demands plain objects," without any negative connotation.

### Do you have any supporting links, references, or citations?

N/A.

### Do you have anything more you want to share?

N/A.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/math/clz32`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/clz32
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/clz32/index.md
* Last commit: https://github.com/mdn/content/commit/f34efd4f1187776662fbefa3fe03fa874a9e8ff1
* Document last modified: 2022-07-03T16:58:44.000Z

</details>

**Comment by hamishwillee** [comment]
Yes! So easy for grumpy authors to inject this kind of thing.

**Comment by Josh-Cena** [comment]
> Make these helper functions into ASM.JS module; then, you have a true performance masterpiece.

That's the one that got me eye-rolling...

**Comment by Josh-Cena** [comment]
> see that a few `Math.*` items have very terse descriptions, without much of an example for application

You are welcome to add an example at any time, if that's what you mean. For certain stuff like `Math.tanh` it's just immediately apparent what it's used for, while for `Math.clz32` it's less apparent especially for those without system language background. Is there any page you have in mind?

**Comment by Josh-Cena** [comment]
Yeah, practical examples would be best. I can't think of actual examples outside of already mathematics/physics intensive areas, though.

**Comment by hamishwillee** [comment]
@Phosra I'm supportive of an fix that improves the docs; but until I see a PR I can't really comment :-).  I have an engineering background so tanh is familiar, but in any case a few words to clarify what people are seeing can do no harm.

I would do the PR that fixes the language, and if you have doubts about the examples, either do as a separate PR or separate commit so that it is easy to revert. Sorry I can't be more canonical.
