### ISSUE TITLE
[Web API] Add structured cloning of error types

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#18208]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1556604

## Other

Clarifying the scope of this in https://bugzilla.mozilla.org/show_bug.cgi?id=1556604#c32

Essentially though I think it is a BCD update for all the error types to indicate support for serializable errors and also addition to the list of structured clone types.
The open question is mostly around what is not serialized and any limitations of this.

**Comment by Josh-Cena** [comment]
Will this edit the `Error` pages? AFAICT we don't document clonability of JS structs elsewhere since `structuredClone` is a web API.

**Comment by hamishwillee** [comment]
@Josh-Cena 

> AFAICT we don't document clonability of JS structs elsewhere since structuredClone is a web API.

I suspect don't document clonability of JS because we've never thought about it. IMO a developer would find this useful to know when looking at the error classes. My intent was to add a note like this one for the errors (from [DOMException](https://developer.mozilla.org/en-US/docs/Web/API/DOMException)):
![image](https://user-images.githubusercontent.com/5368500/178388332-6718a05f-ffc6-4bfd-b118-0388ca7fa46e.png)

If there is a good reason not to update the pages (or you are strongly against this) I don't feel strongly since we'll still have the serializability info in the BCD: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError#browser_compatibility

**Comment by Josh-Cena** [comment]
I'd be happy to document it in JS references—one or two sentences is good enough.

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/17008
- [ ] Docs
- [ ] Release notes
- [ ] dev-docs-complete
