### ISSUE TITLE
Issue with "Django Tutorial Part 4: Django admin site": …

### ISSUE THREAD

**Issue by Anmepod44** [mdn/content#1820]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Admin_site

#### I tried to run the admin site but kept getting  :TypeError at /admin/login/
__init__() missing 1 required positional argument: 'app_module'

 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/admin_site`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Admin_site
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/server-side/django/admin_site/index.html
* Document last modified: 2021-01-11T16:25:05.000Z

</details>

**Comment by hamishwillee** [comment]
@Anmepod44 Glad you like the tutorial.

This really isn't enough for me to debug. 
1. Minimally can you please give me the more full track trace than `init() missing 1 required positional argument: 'app_module'`.
2. Use a file comparison tool to compare your code with the example code in https://github.com/mdn/django-locallibrary-tutorial l
3. If you can't tell anything by comparison can you please upload your code to github and send me the URL so I can inspect.

My guess is that maybe you missed the step in adding the application here: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website#registering_the_catalog_application

**Comment by Anmepod44** [comment]
Thank you very much @hamishwillee  below is the full track trace

Environment:


Request Method: GET
Request URL: http://localhost:8000/admin/login/?next=/admin/

Django Version: 3.1.5
Python Version: 3.8.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'catalog.apps.CatalogConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python38\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Python38\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python38\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python38\lib\site-packages\django\template\base.py", line 168, in render
    with context.bind_template(self):
  File "C:\Python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Python38\lib\site-packages\django\template\context.py", line 244, in bind_template
    updates.update(processor(self.request))

Exception Type: TypeError at /admin/login/
Exception Value: __init__() missing 1 required positional argument: 'app_module'

**Comment by Ryuno-Ki** [comment]
I've took the liberty to add syntax highlighting :)

**Comment by hamishwillee** [comment]
:-). Thanks. I think I need to look at running code. Can you please upload your source to github.

**Comment by Anmepod44** [comment]
Thanks 

Here is a link to my code 
https://github.com/Anmepod44/first-django-site.git

**Comment by hamishwillee** [comment]
Hi @Anmepod44 

What you have shown in https://github.com/Anmepod44/first-django-site.git looks nothing like the final project: https://github.com/mdn/django-locallibrary-tutorial

For a start you don't have a catalog "app" as part of your application as you import here https://github.com/Anmepod44/first-django-site/blob/main/apps.py - which is probably why we see this failure. 

That tells me that you haven't followed the tutorial properly. I recommend you go back to the beginning.
