### ISSUE TITLE
Formatting styles drop down in Writing Guidelines

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#1821]
https://developer.mozilla.org/en-us/docs/MDN/Guidelines/Writing_style_guide#text_formatting_and_styles reads

> Use the **"Formatting Styles"** drop-down list to apply predefined styles to selected content.

Is that a relict of the old WYSIWYG-Editor of the wiki time?
Or does it refer to GitHub's editor?

https://github.com/mdn/content/blob/ec7a60ae626b0253c8eb1570c39251922b13e4d4/files/en-us/mdn/guidelines/writing_style_guide/index.html#L201 is the respective part in the codebase.

**Comment by Elchi3** [comment]
Pretty sure it is a relict from the old WYSIWYG. 
The new Yari Editor doesn't list pre-defined styles. Maybe it should somehow? Maybe as a minimum the Yari Editor could at least point to a link where we list the pre-defined styles because how would anyone know otherwise?

**Comment by Ryuno-Ki** [comment]
I was a bit unsure, whether we might want to point GitHub's editor UI instead (but I haven't got around to edit content myself - since joining, I've got ~1k notifications to catch up with).
