### ISSUE TITLE
Remove notranslate from code samples in Writing Guidelines

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#1822]
https://github.com/mdn/content/blob/ec7a60ae626b0253c8eb1570c39251922b13e4d4/files/en-us/mdn/guidelines/writing_style_guide/index.html

contains several `notranslate` classes in `<pre>` elements, which can be safely removed, because they will get added back on build time using Yari.

**Comment by dk-github-acc** [comment]
Hello sir
As a beginner, I would like to complete this task.

**Comment by Ryuno-Ki** [comment]
Do it!
Looking forward to your first PR :-)

Let us know if you need help with something!

**Comment by dhananjayd1729** [comment]
Hey @Ryuno-Ki , this issue is closed right ? (Though I was able to find out 'notranslate' class in pre.)

**Comment by hamishwillee** [comment]
Yes. There was a global change some weeks ago to remove these (and you can see it is [gone in head revision](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/writing_style_guide/index.html)

@dhananjayd1729 Even so, thanks so much for offering to help. Plenty more things to fix :-)

**Comment by Ryuno-Ki** [comment]
Thanks for closing, @hamishwillee.
Got quite swamped lately over here :-(
