### ISSUE TITLE
Recommendation of macro usage in Writing Guidelines

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#1823]
I'm currently reading some guidelines on MDN authoring.
The following section recommends the usage of macros:

https://github.com/mdn/content/blob/ec7a60ae626b0253c8eb1570c39251922b13e4d4/files/en-us/mdn/guidelines/writing_style_guide/index.html#L247-L261

My understanding was, that we want to get away from these in the long run. Does it make sense to recommend their usage nonetheless?

Production site is https://developer.mozilla.org/en-us/docs/MDN/Guidelines/Writing_style_guide#Styling_mentions_of_HTML_elements

**Comment by hamishwillee** [comment]
I believe the plan is to do a global tool-managed change of the use of these macros. So it does not hurt to have them here for now.
On the other hand  it is good to train people on how we might expect them to do these in future.

So I'd suggest that it certainly would not hurt to update these but perhaps not the highest priority task someone could take on.

**Comment by Rumyra** [comment]
I believe this will be superseeded via the conversion to markdown - so am closing 👍

**Comment by hamishwillee** [comment]
@Rumyra This is not resolved by conversion to markdown, but I am leaving it closed as the docs reflect the status quo - use the macros. I think at some point that will change and then this would have to be revisited.

The TLDR is ...

The conversion to markdown does not remove any macros. There is a general desire to reduce their use but right now they have benefits that bare links do not have. For example, if you use the macro then a link to something works across languages without having to be translated. They are also much simpler to write and easier to read in the source. The only downside I see is that the links to not "work" in markdown.

WillB talks about options for eventually improving this situation, but they don't exist yet. So IMO we just continue to recommend the macros.
