### ISSUE TITLE
Wiki transition is undocumented/no help

### ISSUE THREAD

**Issue by bulk88** [mdn/content#1824]
I last edited MDN summer 2020 thru the old wiki UI. I come back jan 2021, and I notice the MDN site is now a github repo with a static HTML front end, and an obfuscated contribution process. Is it "source available" now or open to contributions?

https://www.google.com/search?q=MDN+wiki all 10 links describe MDN as a wiki. 

https://developer.mozilla.org/en-US/docs/MDN/At_ten/History_of_MDN which is on page 1 of google superficially should say MDN got a forklift upgrade in Dec 2020 but doesnt.

How does someone find out the contributor history of a page prior to Sept 2020/"initial commit" to the github repo?

MDN is essential for tracing the commercial implementation of features, and long running bugs or limited implementations of specs, since W3C/IETF specs are a perpetually moving goal post, and often after no adoption by vendors, specs/drafts are quietly marked terminated. I find blaming/contributor history MDN the fastest way to ensure compatibility to a certain year of browser releases. The new static HTML site, and git repo have no way to trace the provenance of content before Winter 2020.

Is there a single page on MDN that documents the Dec 2020 transition? ```We updated MDN - Learn about our recent changes``` No such help exists.

If MDN is static HTML, why is there a login link?

I find the fact the MDN now has very high barriers to contributing, to be a major detriment to all web devs. The old MDN wiki format was nice, that implementation errata was easily added by random devs over time, vs single devs pouring through grapevine folklore on stackoverflow and upvoting and pinned responses to figure out the usability of various APIs over various eras of browsers for their clients projects.

**Comment by Ryuno-Ki** [comment]
@chrisdavidmills @peterbe Can you help out?

I'm aware of https://github.com/mdn/wiki-revision-history which contains some historic records of the old wiki database.

@bulk88 Have you read https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/ already?

**Comment by peterbe** [comment]
@bulk88 There are pros and cons with both solutions. We just believe that there are more pros than cons for the git approach. Sorry that it was hard to "find your way back on track". Yeah, it's hard to think of every angle that people might have in their relationship with the old platform. 
We believe that the new system is already better and that it has a lot more potential for even further improvement. I really hope you can take a second look and hopefully discover that it's not an "obfuscated contribution process". 

But unless Chris wants to add another, I think @Ryuno-Ki has given the appropriate links, so I'll close it for now.
