### ISSUE TITLE
Replace usage of depricated Object.observe

### ISSUE THREAD

**Issue by Flerox** [mdn/content#1825]
# Replace usage of depricated Object.observe

- [x] Correction or update

# Details
In all examples on the [Intersection Observer API page](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) the depricated Object.observe() is used and should be replaced with an alternative (proxy?).

**Comment by himanshugarg** [comment]
The article reported points to [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/observe) which is not deprecated. Is this still an issue?

**Comment by sideshowbarker** [comment]
> The article reported points to [IntersectionObserver.observe()](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/observe) which is not deprecated.

Thanks much @himanshugarg for clarifying that.

> Is this still an issue?

We’d certainly have an issue if the article did actually use `Object.observe()`. But `IntersectionObserver.p.observe()` is definitely not an issue — it’s been supported across all browsers engines for relatively a long time now, and isn’t in any way deprecated.

So I’m going ahead and closing this.
