### ISSUE TITLE
Several wrong and outdated links on "CSS interface" page

### ISSUE THREAD

**Issue by WebMechanic** [mdn/content#18278]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSS

### What specific section or headline is this issue about?

Specifications + Browser compatibility

#### Specifications
WG Draft Link `https://drafts.csswg.org/cssom/#namespacedef-css`
should go to W3C TR `https://www.w3.org/TR/cssom-1/`

#### Browser compatibility
> This isn't about the compat data, but the links these items point to on MDN!

All links for the individual factory functions result in a 404.

However, there is one [summary page](https://developer.mozilla.org/en-US/docs/Web/API/CSS/factory_functions) as I learned after digging through MDN search results.

#### Specifications
The link should refer to the current W3C TR not the old CSSWG draft.

#### Browser compatibility
Linked factory functions should point to existing page/pages on MDN.
Since there is a [summary page](https://developer.mozilla.org/en-US/docs/Web/API/CSS/factory_functions), they best all link to that.

### Do you have anything more you want to share?

I cloned this repo so I can try to edit a page but in this case both sections use variables (i.e. `{{Specification}}`) with generated data that I don't know how to modify (presumably can't anyway) let alone where they're declared.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/css/index.md
* Last commit: https://github.com/mdn/content/commit/de0dd0427640f74637376429441748f2198c3566
* Document last modified: 2022-07-11T07:05:45.000Z

</details>

**Comment by teoli2003** [comment]
This is the opposite. The TR versions of specs are always outdated. Only the draft versions are used by browsers.

**Comment by WebMechanic** [comment]
I understand, but the given link to _that draft_ is not particulary useful and not what's listed in the WG's index page.
Maybe use https://drafts.csswg.org/cssom-1/ instead? (updated post)

**Comment by WebMechanic** [comment]
Why has this been closed "as completed"?
Neither the link **to the current draft** nor any of the props in the specification table are corrected.
I have provided the URLs.

**Comment by miken32** [comment]
@teoli2003 why was this closed? All the links to CSS draft specs across the entire site are broken. Shouldn't this be fixed? See also:
* https://developer.mozilla.org/en-US/docs/Web/API/AnimationEvent#specifications
* https://developer.mozilla.org/en-US/docs/Web/API/CSS#specifications
* https://developer.mozilla.org/en-US/docs/Web/API/TransitionEvent#specifications

**Comment by teoli2003** [comment]
This is the bug to follow: https://github.com/w3c/csswg-drafts/issues/6528

**Comment by miken32** [comment]
@teoli2003 understood, thanks.
