### ISSUE TITLE
Variable i is not defined in the example map function

### ISSUE THREAD

**Issue by davidk55** [mdn/content#18275]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions

### What specific section or headline is this issue about?

Function expressions

### What information was incorrect, unhelpful, or incomplete?

In the map function the variable `i` is used which is not defined. I think would be helpful to change that so you can just copy the function and test it yourself.

### What did you expect to see?

Maybe something like this:
```js
function map(f, a) {
  const result = [];
  for (let i = 0; i < a.length; i++) {
    result[i] = f(a[i]);
  }
  return result;
}
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/functions/index.md
* Last commit: https://github.com/mdn/content/commit/54ae754f4d18601ee91f741c7b774d2238e2656e
* Document last modified: 2022-07-11T10:50:44.000Z

</details>

**Comment by Josh-Cena** [comment]
Thanks @davidk55 it was a refactor oversight. Your code is correct—do you wish to open a PR?
