### ISSUE TITLE
Fix links to "Violent Theremin" source

### ISSUE THREAD

**Issue by handshek** [mdn/content#18285]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AudioNode#example

### What information was incorrect, unhelpful, or incomplete?

Links to the violent theremin source code don't work anymore.

### What did you expect to see?

Add the appropriate links. Almost every change made in [this commit](https://github.com/mdn/content/pull/17235/commits/eed3df18305459e54fc9e0e870067e30df274baa) needs a fix. 
I believe the correct link is:  https://github.com/mdn/webaudio-examples/tree/master/violent-theremin

### Do you have any supporting links, references, or citations?

https://github.com/mdn/content/pull/17235

**Comment by MrBrain295** [comment]
I will work on this.
