### ISSUE TITLE
MapQuest "finished" example does not seem to work

### ISSUE THREAD

**Issue by 93401** [mdn/content#18322]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs

### What specific section or headline is this issue about?

MapQuest "finished" example does not seem to work

### What information was incorrect, unhelpful, or incomplete?

The map tiles do not load when visiting

(https://mdn.github.io/learning-area/javascript/apis/third-party-apis/mapquest/finished/)

See screenshot.

I tested on Mac Brave, Mac Safari, Mac Firefox and iPad Safari browsers.

### What did you expect to see?

I expected to see MapQuest tiles properly loaded.

### Do you have anything more you want to share?

<img width="614" alt="Screen Shot 2022-07-13 at 8 34 46 AM" src="https://user-images.githubusercontent.com/109233612/178775914-84f35d50-6dc4-4d6e-a6d8-1cc5578b0497.png">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/third_party_apis`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/client-side_web_apis/third_party_apis/index.md
* Last commit: https://github.com/mdn/content/commit/c34c57435f9fc743569a4d661a191660e3dccc78
* Document last modified: 2022-07-03T06:41:31.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this.

The cause is, that https://www.mapquestapi.com/logger/v1/transaction endpoint requires and API key but in our example code at https://github.com/mdn/learning-area/blob/main/javascript/apis/third-party-apis/mapquest/finished/script.js#L1, we’re just doing `L.mapquest.key = 'YOUR-API-KEY-HERE'` — that is, not passing it a real API key.

Given that there’s no way to make it work “live” without a real API key, I’ve opened #18335 with a change that removes the _“also <ins>see it running live here</ins>”_ part.

**Comment by 93401** [comment]
How long does it take for this to be reflected on the live MDN site?

As of 7/14/22 at ~12:50pm PDT, the problem still exists.

The label of the bad hyperlink is "Simple Mapquest API example" .

FYI.

**Comment by teoli2003** [comment]
The production Web site is usually built once a day; read this [section](https://mdn-contributor-docs.mozilla.org/legacy/deployment-timeline/) for more information.

**Comment by sideshowbarker** [comment]
> The label of the bad hyperlink is "Simple Mapquest API example" .

ah, the change I made only removed the the _“also <ins>see it running live here</ins>”_ link further down. We’ll need to open a follow-up PR to un-link the _“Let's look at a <ins>Simple Mapquest API example</ins>”_ link in the intro section.
