### ISSUE TITLE
Table on vertical-align page makes the page scrollable horizontally unnecessarily

### ISSUE THREAD

**Issue by HatimLagzar** [mdn/content#1834]
Hi,

As you can see at the screenshot, the table made the page scrollable horizontally unnecessarily. It looks like a CSS responsive problem.

Using:

- Chrome
- 1080p Screen
- 125% Chrome Page Zoom

![image](https://user-images.githubusercontent.com/29899589/106059211-aca86000-60f2-11eb-8410-65bfdfde8907.png)

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @HatimLagzar . This problem was caused because the embedded live examples are sitting inside iframes, and so not styled by our standard table styling. The example in question had a reasonable responsive style set on it (`table { width: 80% }`), but the iframe was then set to a fixed-width of 1200px ;-|

This could probably do with more work in the future, but for now I've made this better by setting the iframe widths to 100%, so it adjusts to whatver the width of the main body text column is.

see https://github.com/mdn/content/commit/150e6cfab535440d5ca123a66b6e8b91b04d959f for the fix

**Comment by mattiapontonio** [comment]
Still some problems here

![Screenshot_20210128-122149.png](https://user-images.githubusercontent.com/44380480/106131829-748d3580-6163-11eb-8fe5-36f80581138f.png)

- https://github.com/mdn/content/blob/main/files/en-us/web/css/vertical-align/index.html
- https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

**Comment by chrisdavidmills** [comment]
@mattiapontonio the fix hasn't made its way to the production site yet. IT will look better when it does, although it still won't look great on mobile.

**Comment by HatimLagzar** [comment]
> Thanks for reporting this @HatimLagzar . This problem was caused because the embedded live examples are sitting inside iframes, and so not styled by our standard table styling. The example in question had a reasonable responsive style set on it (`table { width: 80% }`), but the iframe was then set to a fixed-width of 1200px ;-|
> 
> This could probably do with more work in the future, but for now I've made this better by setting the iframe widths to 100%, so it adjusts to whatver the width of the main body text column is.
> 
> see [150e6cf](https://github.com/mdn/content/commit/150e6cfab535440d5ca123a66b6e8b91b04d959f) for the fix

I think you adjusted the height not the width of the iframe but, yes the height should be 100% to avoid the vertical scroll bar on the table and the section above the table.

This is a preview of the page with and without the changes you made.

Without Changes:
![image](https://user-images.githubusercontent.com/29899589/106137164-a05fe980-616a-11eb-81d7-409440f8c7e4.png)

With Changes:
![image](https://user-images.githubusercontent.com/29899589/106137428-fb91dc00-616a-11eb-9d31-0b93e94a5251.png)

**Comment by chrisdavidmills** [comment]
@HatimLagzar big oops, and thanks for noticing ;-)

Updated again: https://github.com/mdn/content/commit/1fc347ebeaf4bea3b783943f0dfea51db3b5492c

**Comment by mattiapontonio** [comment]
I would like to say: it probably shouldn't be put in a paragraph; I would like to understand if there are any advantages to using a simple iframe and not the macro or vice versa.
