### ISSUE TITLE
The speechSynthesis example doesn't work in Chrome

### ISSUE THREAD

**Issue by jcubic** [mdn/content#18359]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance

### What specific section or headline is this issue about?

Code snippet

### What information was incorrect, unhelpful, or incomplete?

See those SO questions and solutions:

* [Getting the list of voices in speechSynthesis (Web Speech API)](https://stackoverflow.com/q/21513706/387194)
* [speechSynthesis.getVoices() returns empty array on Windows](https://stackoverflow.com/q/49506716/387194)

There are two solutions to the problem. I see same error on Linux. If MDN is suppose to be complete it should include the information about this.

### What did you expect to see?

One of the solutions from SO should be included on the page. Whichever is the proper solution. Because the snippet doesn't work on Google Chrome (that is the most popular browser).

### Do you have any supporting links, references, or citations?
Here is a working snippet https://codepen.io/jcubic/pen/rNdWjrR?editors=1010

### Do you have anything more you want to share?
I can create a PR with the whole code since I've already added a fix for a syntax error in #18358

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/speechsynthesisutterance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/speechsynthesisutterance/index.md
* Last commit: https://github.com/mdn/content/commit/c55229583a502780b5397a2afb6d8b61dcb1d866
* Document last modified: 2022-07-07T15:35:48.000Z

</details>

**Comment by teoli2003** [comment]
Thanks! Wanna try to make a PR?

**Comment by jcubic** [comment]
Sure, when I started writing this I was not sure what was the right fix. But it seems that the same code is in the example linked on the page.
