### ISSUE TITLE
Problem in running JavaScript in code editor in “Test your skills: HTML5 controls” 

### ISSUE THREAD

**Issue by SeyedAmirHs00** [mdn/content#18350]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Test_your_skills:_HTML5_controls

### What information was incorrect, unhelpful, or incomplete?

In Test 2 I wrote a code that works in my compute very well but in the Test area the output didn't change when I change range input.

```
<form>
  <ul>
    <li>
      <label for="max-invite">Select maximum number of invitations</label>
      <input type="range" id="max-invite" min="1" max="30" value="10" name="max-invite">
      <output for="max-invite" id="invite-output">10</output>
    </li>
    <li>
      <button type="submit">Submit</button>
    </li>
  </ul>
</form>
```
```
<script>
  const outputElem = document.querySelector("#invite-output");
  const maxInviteInput = document.querySelector("#max-invite");

  maxInviteInput.addEventListener("input", () => {
    outputElem.textContent = maxInviteInput.value;
  });
</script>
```

### What did you expect to see?

Please fix this.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/test_your_skills_colon__html5_controls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Test_your_skills:_HTML5_controls
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/test_your_skills_colon__html5_controls/index.md
* Last commit: https://github.com/mdn/content/commit/2777cdc8c8b54268a24beeeb7a98520e3331d3be
* Document last modified: 2022-04-26T11:32:33.000Z

</details>

**Comment by Josh-Cena** [comment]
The problem statement said:

> Give it a class of `invite-output`

Changing `id="invite-outout"` to `class="invite-output"` will fix it.
