### ISSUE TITLE
Intl.NumberFormat formatting same currency in different way

### ISSUE THREAD

**Issue by AlokMishra051298** [mdn/content#18395]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

### What information was incorrect, unhelpful, or incomplete?

It is not about content issue is with format api. I'm not sure where to raise it.

### What did you expect to see?

Currency format should be same for same options config why it differ on text

`$166.0 (for smaller numbers)

166.0 M$ ( if given text is in million)`

### Do you have any supporting links, references, or citations?

![a48b91d3-3909-4924-8900-43170d179e2b](https://user-images.githubusercontent.com/46258899/179241417-3bf620b0-41d1-4e5d-a109-f1dfeb948431.png)

### Do you have anything more you want to share?

I'm not sure where to raise that bug so I raised please raise it to to required place.

**Comment by Josh-Cena** [comment]
In general, you should not care about what the _actual_ formatted text is—only its semantics is guaranteed.

Please give your `locales` and `options`. It's not what I got:

```
> new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", minimumFractionDigits: 2 }).format(11234567)
< '$11.23M'
> new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", minimumFractionDigits: 2 }).format(11)
< '$11.00'
```

**Comment by AlokMishra051298** [comment]
Try for 'es-MX' locale and MXN currency

**Comment by Josh-Cena** [comment]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/55398995/179251709-8521a550-fcb0-4945-b425-1a61621cea68.png">

**Comment by Josh-Cena** [comment]
Ah, I misread `es-MX` as `en-MX`. However, the fact that `es` and `en` format it differently means it's a locale-specific thing. It means in Spanish the unit is canonically put at the end if it has a quantity like `k` or `M`. Unless you have proof otherwise it's not convincing that it's a bug.
