### ISSUE TITLE
Is it possible to know the license of code, after the transition to Yari?

### ISSUE THREAD

**Issue by danny-laa** [mdn/content#184]
According to [MDN](https://developer.mozilla.org/en-US/docs/MDN/About#Copyrights_and_licenses), 

> Code samples added on or after August 20, 2010 are in the public domain (CC0). No licensing notice is necessary, but if you need one, you can use: "Any copyright is dedicated to the Public Domain. http://creativecommons.org/publicdomain/zero/1.0/".
>
> Code samples added to this wiki before August 20, 2010 are available under the MIT license; you should insert the following attribution information into the MIT template: "© <date of last wiki page revision> <name of person who put it in the wiki>".
>
> You can determine which license a code sample is available under by browsing through the article's history. To view the history:
>
> 1. Click the Edit in wiki button in the article header.  This takes you to the same article on the editable, wiki version of MDN Web Docs (but does not actually put the article in edit mode).  
> 2. Click the gear-shaped icon in the header of the wiki article, and choose History in the menu that appears.
> 3. Click View All, and then look for the most recent revision that occurred before August 20, 2010 (if any).
> 4. Click the date stamp of that revision to see the version of the article on that date.

Is it possible to know the license of code, after MDN's transition to Yari?

This repo doesn't seem to contain history older than [15 Sep 2020](https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630)

**Comment by Ryuno-Ki** [comment]
According to README, which points to [LICENSE.md](https://github.com/mdn/content/blob/9ca97d18a387ef8a77e64191dd05e6e621d8ad53/LICENSE.md), it will remain CC0 (code) resp. CC BY-SA 2.5 (prose).

**Comment by danny-laa** [comment]
@Ryuno-Ki According to LICENSE.md, only code added after August 20, 2010 falls under CC0, otherwise it is licensed under MIT License.

https://github.com/mdn/content/blob/9ca97d18a387ef8a77e64191dd05e6e621d8ad53/LICENSE.md#L72-L76

The question is, after the transition to Yari, is there a way to figure out which license applies to a specific code sample, CC0 or MIT?

**Comment by Ryuno-Ki** [comment]
I think, this is related to https://github.com/mdn/yari/issues/706.
@peterbe and @fiji-flo looked how to get `_wikihistory.json` right.

**Comment by danny-laa** [comment]
@Ryuno-Ki Not quite related unless Mozilla is going to import the whole history database to this repo.

Git log won't work if this repo only contains history after 15 Sep 2020.

**Comment by Ryuno-Ki** [comment]
I'm aware, that the created / modified date won't show up in git. They can't. Right now, [MDN is stored in a MySQL database.](https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/) (Ctrl-F „Changes in a nutshell”).

My understanding was, that the meta information is dumped into a JSON file, which then gets evaluated next to git metadata for the display of created / modified date.

**Comment by danny-laa** [comment]
I read [the guide to determine license of a code sample](https://developer.mozilla.org/en-US/docs/MDN/About#Copyrights_and_licenses) one more time and found that I was wrong.

To find out if a code sample was added before August 20, 2010, it would require more than just the metadata, but the whole history of the article (it should be git blame instead of git log if the whole history is imported). For example, an article may be created before August 20, 2010, but some code sample it contains might be added after that date. In that case, those code sample added after the date will be licensed under CC0.

If the whole history won't be imported and the old history won't be accessible by the public after the transition, could Mozilla review and mark license of every code sample for us?

**Comment by dontcallmedom** [comment]
given the lack of clear history tracking before Yari, I think it would probably simpler to assume any code sample pre-Yari is available under MIT license, and only bring the CC0 license for post-Yari submissions.

In practice, availability under MIT license is already very permissive, so doing a lot of uncertain history tracking to "only" get the bonus of CC0 doesn't seem worth the time IMO.

**Comment by maxloh** [comment]
Mozilla can just run an instance of old MDN so users could access history before 15 Sep 2020.

**Comment by maxloh** [comment]
Mozilla can just run an instance of old MDN so users could access history before 15 Sep 2020.

@dontcallmedom it would be a pain in the ass if we were required to include the whole MIT license text in a JavaScript file, just because we copied a few lines of code. The license test may even be longer than the code snippet we copied.

**Comment by danny-laa** [comment]
Mozilla can just run an instance of old MDN so users could access history before 15 Sep 2020.

@dontcallmedom it would be a pain in the ass if we were required to include the whole MIT license text in a JavaScript file, just because we copied a few lines of code. The license test may even be longer than the code snippet we copied.

**Comment by dontcallmedom** [comment]
As far as I understand, the only difference between my suggestion and doing the historical research (or allowing others to do that research) is that the code samples submitted between Aug and December might be upgraded from MIT to CC0. Unless there was a particular streak of code submissions in that period, it still feels unlikely to yield much benefit compared to the required effort.

(wrt copying a few lines of code - IANAL, but code samples just a few lines long are likely not copyrightable in the first place - copyright only applies to original work after all)

**Comment by escattone** [comment]
Sorry for the confusion here. Thank you for bringing this up @danny-laa and to everyone else for their comments/thoughts. It's something that @chrisdavidmills, myself, and others (most likely Mozilla legal) are discussing how to resolve, and we'll report back as soon as we can.

**Comment by danny-laa** [comment]
@escattone Any news?

**Comment by escattone** [comment]
@danny-laa Sorry for the delayed response! Thanks for the reminder. We had started this discssion, but in the rush of everything else going on, never finished it. We'll get it rolling again.

**Comment by danny-laa** [comment]
@escattone Is there any estimated date when will this issue be resolved?
