### ISSUE TITLE
Replace recommendation for VSCode with recommendation for VSCodium in the beginners section 

### ISSUE THREAD

**Issue by wgrlogin** [mdn/content#18421]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Installing_basic_software

### What specific section or headline is this issue about?

Installing a text editor

### What information was incorrect, unhelpful, or incomplete?

"We recommend starting with [**Visual Studio Code]**(https://code.visualstudio.com/), which is a free editor, that offers live previews and code hints."

VSCode is free as in "free beer". But it is not open source, it is proprietary software. There is an open source alternative called "VSCodium", but the link in the line above points to proprietary version of Microsoft.

VSCode or VSCodium do not offer live preview out of the box. You need to install a plugin, which is still under construction.

### What did you expect to see?

It would by nice to see the following instead:
"We recommend starting with [**VS Codium]**(https://vscodium.com/), which is a free and **open source** editor, that offers live previews and code hints."
VSCodium is build entirely on the open source repository "Code - OSS" without any "enrichments".

"VSCodium is identical to VS Code with the single biggest difference that unlike VS Code, VSCodium doesn't track your usage data." (itsfoss)

### Do you have any supporting links, references, or citations?

Downlaod: https://vscodium.com/
See article: https://itsfoss.com/vscodium/
Install on Windows : winget install vscodium

### Do you have anything more you want to share?

For me the way the recommendation is placed looks a little bit like an advertisement for a Microsoft product.
VSCode/VSCodium are very, very good editors. However, there are other editors that could be mentioned. 
Espacially for beginners there is good old "bluefish". Ok, it comes with an old fashioned UX but has everything that beginners need to start with web development. Not as plugins but out of the box.
"kate" or - if you go for unfree software anyway - "sublime-text" are still out there, too. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/installing_basic_software`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Installing_basic_software
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/installing_basic_software/index.md
* Last commit: https://github.com/mdn/content/commit/c3f60e53c878be3cc8d196c31a83928a42449088
* Document last modified: 2022-05-22T21:35:38.000Z

</details>

**Comment by awxiaoxian2020** [comment]
I don't think it's like an ad for Microsoft product. Because it's open source and used by many people. Our Internet is built by everyone and we should respect who contribute for these. 
Sure, we can add other editors. It's a good idea.

**Comment by sideshowbarker** [comment]
I think we should seriously consider deleting the entire “Installing basic software” page.

This issue reminds me of https://github.com/mdn/content/issues/7048, where we have a similar article that will forever require somebody to actively work to try to ensure it stays up to date. But I don’t think the cost of doing that’d be justified by the limited benefits MDN readers would get from somebody doing the work — because the bad combination of characteristics which this article and this one have is:

* the article doesn’t give essential info that’s not already available in other places (unlike, e.g., all our reference content):
* the article requires more maintenance to be kept up to date than other content (e.g., our reference content) 

See my further comments at https://github.com/mdn/content/issues/7048#issuecomment-1178457933.

All that said, if don’t have agreement about deleting the “Installing basic software” page, then perhaps let’s at least consider replacing the current content of the “Installing a text editor” section with text that instead just says something like:

> There is a rich selection of text editors you can use for creating and editing HTML and CSS and JavaScript content. Wikipedia has details about many such editors; so to find an editor that fits your needs, take time to read through some relevant Wikipedia pages — for instance, try starting from the [“Notable examples” section of the Wikipedia “Source-code editor” article](https://en.wikipedia.org/wiki/Source-code_editor#Notable_examples), and following the links there to the pages where you can read all the details about each editor.

**Comment by awxiaoxian2020** [comment]
> I think we should seriously consider deleting the entire “Installing basic software” page.
> 
> This issue reminds me of #7048, where we have a similar article that will forever require somebody to actively work to try to ensure it stays up to date. But I don’t think the cost of doing that’d be justified by the limited benefits MDN readers would get from somebody doing the work — because the bad combination of characteristics which this article and this one have is:
> 
> * the article doesn’t give essential info that’s not already available in other places (unlike, e.g., all our reference content):
> * the article requires more maintenance to be kept up to date than other content (e.g., our reference content)
> 
> See my further comments at [#7048 (comment)](https://github.com/mdn/content/issues/7048#issuecomment-1178457933).
> 
> All that said, if don’t have agreement about deleting the “Installing basic software” page, then perhaps let’s at least consider replacing the current content of the “Installing a text editor” section with text that instead just says something like:
> 
> > There is a rich selection of text editors you can use for creating and editing HTML and CSS and JavaScript content. Wikipedia has details about many such editors; so to find an editor that fits your needs, take time to read through some relevant Wikipedia pages — for instance, try starting from the [“Notable examples” section of the Wikipedia “Source-code editor” article](https://en.wikipedia.org/wiki/Source-code_editor#Notable_examples), and following the links there to the pages where you can read all the details about each editor.

I agree that replacing the section with a brief text instead of a particular editor.
deleting whole the page may be unfriendly for beginners.

**Comment by wgrlogin** [comment]
In my eyes deleting the whole page would be a pitty. 
The WWW is full of pages titled "Web Development for Beginners" and compared to others the MDN page is one of the really, really good ones! 
Don't drop it! That is definitely not what I wanted to achieve.

My only concern was that VSCode is just not open source and the article explicitly states it instead of pointing to the open source VSCodium.

Pointing to the list in Wikipedia is a good idea.

Thank you

**Comment by Josh-Cena** [comment]
For what it's worth, despite being a huge advocate of open-source, I have to say the sentiment that "non-open-source is bad; proprietary is bad; telemetry is bad" is highly subjective. For a beginner tutorial I'll definitely go with recommending VSCode as default—it has richer support and is backed by a strong organization. Sure, VSCodium is almost a clean fork of VSCode, but there's no guarantee it won't go out of sync, or it won't be unable (sorry for the triple negation) to produce the necessary diagnostic data when bugs occur. It's just much easier to say "here's THE most popular text editor on the planet today, here's its docs, try it out".

**Comment by Rumyra** [comment]
This is a page for beginners and pointing them to a popular ide to get them started is within the scope of content. Agree with @Josh-Cena here

> For a beginner tutorial I'll definitely go with recommending VSCode as default—it has richer support and is backed by a strong organization.

As such I'm closing this issue, but thanks for raising it @wgrlogin - further to the other comments this raised I've open a discussion about the 'Getting started with the web' area https://github.com/mdn/mdn-community/discussions/161
