### ISSUE TITLE
Problem with Method definitions

### ISSUE THREAD

**Issue by STHunCoder** [mdn/content#18444]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

### What specific section or headline is this issue about?

Description section

### What information was incorrect, unhelpful, or incomplete?

At the beginning of the Description section, the two codes are the same, the first one is also the shortened one.

### What did you expect to see?

For the first code, I would like to see the unshortened version.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/functions/method_definitions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/functions/method_definitions/index.md
* Last commit: https://github.com/mdn/content/commit/d4b12e290fce9ae43a9ae23b9b9c8a5812b82ebd
* Document last modified: 2022-07-16T06:12:06.000Z

</details>

**Comment by Josh-Cena** [comment]
Haha, good catch, PRs welcome 😄
