### ISSUE TITLE
Inconsistencies with "Test your skills: The Cascade" page.

### ISSUE THREAD

**Issue by SweetBoySavage** [mdn/content#18443]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_tasks

### What specific section or headline is this issue about?

Inconsistencies among the code provided in the interactive editor and the HTML template and the solution on GitHub.

### What information was incorrect, unhelpful, or incomplete?

It seems that the [task](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_tasks#task) on the page has been updated recently, but the _HTML_ template and the solution on _GitHub_ haven’t. The issues:
1. the code in the interactive editor is different from the one provided in the HTML template ([the starting point](https://github.com/mdn/css-examples/blob/main/learn/tasks/cascade/cascade-download.html)), for example, the HTML template doesn't have any cascade layers included, but they are required in order to complete the task. 
2. if we assume that the code in the interactive editor is complete, the second instruction ("...write a declaration in a new rule that will reset the background color to white, without using an actual color value and without touching the lightgreen declaration...") is invalid as it can’t be achieved only using the special values.
3. The [solution](https://github.com/mdn/css-examples/blob/main/learn/tasks/cascade/marking.md) found in the same directory as the HTML template is also invalid since, if we use the rule `#outer #inner a {background-color: initial;}`, the background color is set to transparent instead of white as the initial value of the property “background-color” is “transparent”.

### What did you expect to see?

If it was up to me, I would:
leave the task description as it is;
update the code in the interactive editor like this:
```
      body {
        background-color: #fff;
        font: 1.2em / 1.5 Helvetica Neue, Helvetica, Arial, sans-serif;
        padding: 1em;
        margin: 0;
      }
      #outer div ul .nav a {
        background-color: blue;
        padding: 5px;
        display: inline-block;
        margin-bottom: 10px;
      }
      @layer yellow, purple, green;

      @layer yellow {
        #outer div ul .nav a {
          background-color: yellow;
          padding: 5px;
          display: inline-block;
          margin-bottom: 10px;
        }
      }
      @layer purple {
        div div li a {
          color: rebeccapurple;
        }
      }
      @layer green {
        a {
          color: lightgreen;
        }
      }     
```
update the HTML template like this: 
```
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <title>The Cascade Task</title>

    <style>

      body {
        background-color: #fff;
        font: 1.2em / 1.5 Helvetica Neue, Helvetica, Arial, sans-serif;
        padding: 1em;
        margin: 0;
      }
      #outer div ul .nav a {
        background-color: blue;
        padding: 5px;
        display: inline-block;
        margin-bottom: 10px;
      }
      @layer yellow, purple, green;

      @layer yellow {
        #outer div ul .nav a {
          background-color: yellow;
          padding: 5px;
          display: inline-block;
          margin-bottom: 10px;
        }
      }
      @layer purple {
        div div li a {
          color: rebeccapurple;
        }
      }
      @layer green {
        a {
          color: lightgreen;
        }
      }               
    
      
    </style>
  </head>

  <body>

    <div id="outer" class="container">
      <div id="inner" class="container">
        <ul>
          <li class="nav">
            <a href="#">One</a>
          </li>
          <li class="nav">
            <a href="#">Two</a>
          </li>
        </ul>
      </div>
    </div>

  </body>

</html>
```
and provide the solution like this:
```
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <title>The Cascade Task</title>

    <style>

      body {
        background-color: #fff;
        font: 1.2em / 1.5 Helvetica Neue, Helvetica, Arial, sans-serif;
        padding: 1em;
        margin: 0;
      }
      #outer div ul .nav a {
        background-color: blue;
        padding: 5px;
        display: inline-block;
        margin-bottom: 10px;
      }
     div, div ul, div ul li, #outer #inner ul li a
      {
        background-color: inherit;
      }
      @layer yellow, green, purple;

      @layer yellow {
        #outer div ul .nav a {
          background-color: yellow;
          padding: 5px;
          display: inline-block;
          margin-bottom: 10px;
        }
      }
      @layer purple {
        div div li a {
          color: rebeccapurple;
        }
      }
      @layer green {
        a {
          color: lightgreen;
        }
      }               
    
      
    </style>
  </head>

  <body>

    <div id="outer" class="container">
      <div id="inner" class="container">
        <ul>
          <li class="nav">
            <a href="#">One</a>
          </li>
          <li class="nav">
            <a href="#">Two</a>
          </li>
        </ul>
      </div>
    </div>

  </body>

</html>
```

### Do you have any supporting links, references, or citations?

For more information, please, see the [discussion](https://discourse.mozilla.org/t/assessment-for-cascade-skill-test/99489/11) on this topic and feel free to contact me on the MDN forum or GitHub.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_tasks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_tasks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_tasks/index.md
* Last commit: https://github.com/mdn/content/commit/ace1400b3b5cf252d6afc0caaccf170d0316c15e
* Document last modified: 2022-07-11T21:07:38.000Z

</details>

**Comment by teoli2003** [comment]
cc/ @estelle

**Comment by estelle** [comment]
[PR for examples](https://github.com/mdn/css-examples/pull/78)

**Comment by estelle** [comment]
https://github.com/mdn/content/pull/18564 - this reverts the task instructions and adds a second task. (will be adding the second task in a different PR)
