### ISSUE TITLE
CORS: image for simple request shows an Origin header value lacking a scheme

### ISSUE THREAD

**Issue by jub0bs** [mdn/content#18471]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests

### What information was incorrect, unhelpful, or incomplete?

The [image illustrating an example of a _simple_ request](https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/simple-req.png) shows an `Origin` header whose value lacks a scheme (`Origin: foo.example`):

![simple_req.png](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/simple-req.png)

### What did you expect to see?

To be consistent with the rest of the page (text content as well as images appearing further down), that image should instead show

```http
Origin: https://foo.example
```

### Do you have anything more you want to share?

Omitting the scheme on this image may trip some developers who are not familiar enough with the concept of Web origin and may be tempted to only specify the host and (optionally) the port in the `Access-Control-Allow-Origin` header of their CORS config. See, for instance, https://stackoverflow.com/questions/28839728/must-the-access-control-allow-origin-header-include-scheme

Unfortunately, because I don't know how file `simple-req.png` was produced, I cannot correct it myself.

**Comment by heavymachinery** [comment]
Hi, can this be assigned to me? I've altered the image to include `https` scheme for the `Origin` header and will submit a PR shortly 🙇
