### ISSUE TITLE
[Cauldron](https://cauldron.io/) is an analysis tool to understand a public software and its community. It is possible to make use of cauldron here.

### ISSUE THREAD

**Issue by franckbleyer1** [mdn/content#18481]
[Cauldron](https://cauldron.io/) is an analysis tool to understand a public software and its community. It is possible to make use of cauldron here.

__Originally posted by @OrkoHunter in https://github.com/twitter/metrics/issues/7__

**Comment by Josh-Cena** [comment]
Judging from past behaviors like https://github.com/mdn/content/issues/18460, this is another spam attempt.
