### ISSUE TITLE
Add Web Share API to this list of secure-context-only APIs?

### ISSUE THREAD

**Issue by stuartlangridge** [mdn/content#18512]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts

### What specific section or headline is this issue about?

Current features available only in secure contexts

### What information was incorrect, unhelpful, or incomplete?

I think that the Web Share API is only available on secure contexts too; https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API seems to think so. I'm not sure which versions this happened in, or whether it's the case in all browsers.

### What did you expect to see?

A row in the table for the Web Share API.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/security/secure_contexts/features_restricted_to_secure_contexts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/security/secure_contexts/features_restricted_to_secure_contexts/index.md
* Last commit: https://github.com/mdn/content/commit/1179df92deaff22669b8d6ee320efd51d027f6bd
* Document last modified: 2022-05-17T14:50:44.000Z

</details>

**Comment by hamishwillee** [comment]
Cheers, added in https://github.com/mdn/content/pull/18621

Its a relatively recent API and AFAIK requires secure context in all browsers that support it. If this was "different" across browsers it would go in the browser compatibility information - but because it is the same there is no note there.
