### ISSUE TITLE
information missing

### ISSUE THREAD

**Issue by TheDirigible** [mdn/content#18520]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage

### What information was incorrect, unhelpful, or incomplete?

I was sent here by this runtime message, which is the first I've heard of it:
Returning a Promise is the preferred way to send a reply from an onMessage/onMessageExternal listener, as the sendResponse will be removed from the specs (See https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage)

I go to that page, and there is not one mention of sendResponse being removed or deprecated.

### What did you expect to see?

a mention of sendResponse being removed or deprecated.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/runtime/onmessage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/runtime/onmessage/index.md
* Last commit: https://github.com/mdn/content/commit/78a76c333db7caaf3de64ff2057fea75458438fd
* Document last modified: 2022-06-02T21:12:31.000Z

</details>

**Comment by rebloor** [comment]
@TheDirigible it appears that this message is coming from the polyfill and there is an outstanding ticket https://github.com/mozilla/webextension-polyfill/issues/386 to address this.
