### ISSUE TITLE
How to set private window permission?

### ISSUE THREAD

**Issue by szmarczak** [mdn/content#18525]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings

### What specific section or headline is this issue about?

Note

### What information was incorrect, unhelpful, or incomplete?

> **Note:** The ability to change proxy settings requires private window access because proxy settings affect both private and non-private windows. Therefore, if an extension has not been granted private window permission, calls to `proxy.settings.set()` will throw an exception.

The information is not complete. It's missing how to set the private window permission.

### What did you expect to see?

It should contain information how to set the permission.

Searchfox: https://searchfox.org/mozilla-central/rev/108c7843696fdf951083889d6fb858953139be96/toolkit/components/extensions/parent/ext-proxy.js#217

### Do you have anything more you want to share?

I looked at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions but failed to find "private window".

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/proxy/settings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/proxy/settings/index.md
* Last commit: https://github.com/mdn/content/commit/c87ca062c8d120223f4919b8c45441eec26e9e59
* Document last modified: 2022-07-06T10:18:57.000Z

</details>

**Comment by szmarczak** [comment]
When I set the `incognito` permission it gave this weird warning in the about:debugging page

```
Reading manifest: Warning processing permissions: Error processing permissions.7: Value "incognito" must either: must either [must either [must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], or be one of ["webNavigation"]], be one of ["alarms", "mozillaAddons", "storage", "unlimitedStorage"], be one of ["captivePortal"], be one of ["identity"], be one of ["menus", "contextMenus"], be one of ["normandyAddonStudy"], be one of ["geckoProfiler"], be one of ["urlbar"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["activityLog"], be one of ["networkStatus"], be one of ["telemetry"], or be one of ["theme"]], must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], or be one of ["webNavigation"]], or match the pattern /^experiments(\.\w+)+$/], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]
```

**Comment by szmarczak** [comment]
I just noticed this in `about:addons`

![image](https://user-images.githubusercontent.com/36894700/179844047-13a7dfb4-333c-4f17-afeb-414f588a972e.png)

Having `browser.proxy` affect both contexts extremely degrades DX.

**Comment by rebloor** [comment]
@szmarczak while we do need to clarify the issue you've identified, I wanted to let you know that we have recently added a clarification to the [incognito ](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito)manifest key to explain that permission for an extension to access private windows is under user control.

**Comment by szmarczak** [comment]
Thank you @rebloor, greatly appreciated! ❤️
