### ISSUE TITLE
Outdated web audio example code

### ISSUE THREAD

**Issue by MrBrain295** [mdn/content#18547]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The example code has been updated but this hasn’t.

### What did you expect to see?

Up-to-date code.

### Do you have any supporting links, references, or citations?

https://github.com/mdn/webaudio-examples/tree/master/media-source-buffer

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/audiocontext/createmediaelementsource`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/audiocontext/createmediaelementsource/index.md
* Last commit: https://github.com/mdn/content/commit/c000698d544f932314050edec3f47b8b8dc906bf
* Document last modified: 2022-05-27T16:26:44.000Z

</details>

**Comment by teoli2003** [comment]
Yes, I've updated the webaudio-examples in the directory, I need to update the MDN articles now. That's the next step.

I can use this issue to track the work.

**Comment by Josh-Cena** [comment]
@teoli2003 Any parts left in this issue?

**Comment by teoli2003** [comment]
It is not 100% up-to-date, but I think we can close this for the moment. I would like first to activate ESLint on the examples repositories, and this is not ready to be done (mostly by lack of time). Once done, we will need to synchronize all the examples anyway.
