### ISSUE TITLE
Add example to page for the “tablist” role identical to the example on the page for the “tab” role

### ISSUE THREAD

**Issue by nickshanks** [mdn/content#18555]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tablist_role

### What information was incorrect, unhelpful, or incomplete?

The page does not make it clear if tabpanel elements need to be within the tablist or outside of it (or whether that matters at all).

For example, is either of these invalid?
```
<div role=tablist>
<button role=tab/>
<button role=tab/>
<div role=tabpanel/>
<div role=tabpanel/>
</div>
```

```
<div role=tablist>
<button role=tab/>
<button role=tab/>
</div>
<div role=tabpanel/>
<div role=tabpanel/>
```

### What did you expect to see?

sample code

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/accessibility/aria/roles/tablist_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tablist_role
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/roles/tablist_role/index.md
* Last commit: https://github.com/mdn/content/commit/b98d081f0d5d38667efa163f3660897a5a34747f
* Document last modified: 2022-06-30T01:51:03.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
The following examples place the `<div role="tabpanel">` elements after the `<div role="tablist">` element — as in your second sample — so I assume that is the recommended approach.

- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role#example
- https://w3c.github.io/aria-practices/examples/tabs/tabs-automatic.html#sc1_label
- https://w3c.github.io/aria-practices/examples/tabs/tabs-manual.html#sc1_label

The [example](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tabpanel_role#example) section on the [tabpanel page](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tabpanel_role) refers to the [example](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role#example) on the [tab page](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role), so I suggest an identical **Example** section be added to the [tablist page](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tablist_role).

> ### Example
> See the [tabpanel, tab, and tablist example](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role#example) in the [tab](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role) role definition.

**Comment by dawei-wang** [comment]
I think this issue can be closed as there is a merged PR that implements the changes. Thanks!

**Comment by sideshowbarker** [comment]
Closing per as fixed by https://github.com/mdn/content/pull/19742 per https://github.com/mdn/content/issues/18555#issuecomment-1249965637
