### ISSUE TITLE
`position: fixed` docs do not mention `will-change` also affects the choice of containing block

### ISSUE THREAD

**Issue by bernardobelchior** [mdn/content#18551]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/position

### What specific section or headline is this issue about?

The `position: fixed` part

### What information was incorrect, unhelpful, or incomplete?

The description reads:

> It is positioned relative to the initial [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block) established by the [viewport](https://developer.mozilla.org/en-US/docs/Glossary/Viewport), except when one of its ancestors has a `transform`, `perspective`, or `filter` property set to something other than `none` (see the [CSS Transforms Spec](https://www.w3.org/TR/css-transforms-1/#propdef-transform)), in which case that ancestor behaves as the containing block

However, it seems that `will-change: transform` also causes the `position: fixed` to choose the ancestor, instead of the viewport as the containing block.

### What did you expect to see?

Something along the lines of 

> [...] one of its ancestors has a `transform`, `perspective`, or `filter` property set to something other than `none` (see the [CSS Transforms Spec](https://www.w3.org/TR/css-transforms-1/#propdef-transform)), or `will-change` property set to `transform`, in which case that ancestor behaves as the containing block

### Do you have any supporting links, references, or citations?

I have created a [CodeSandbox example](https://codesandbox.io/s/practical-platform-to4ieo?file=/index.html) where this is visible. 

By commenting/uncommenting line 15 you can see that the `div` with ID `fixed` changes its containing block.

### Do you have anything more you want to share?

This was initially tested on:

Name 	Firefox
Version 	102.0.1
Build ID 	20220705093820

But Google Chrome Version 103.0.5060.114 (Official Build) (arm64) and Safari Version 15.5 (17613.2.7.1.8) have the same behavior. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/position`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/position
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/position/index.md
* Last commit: https://github.com/mdn/content/commit/54ae754f4d18601ee91f741c7b774d2238e2656e
* Document last modified: 2022-07-11T10:50:44.000Z

</details>

**Comment by najmiehsa** [comment]
I take this issue.

**Comment by najmiehsa** [comment]
@bernardobelchior Would you please check the PR to see if everything is done accordingly?
