### ISSUE TITLE
The documentation should link to a doc about the event structure

### ISSUE THREAD

**Issue by v1nce** [mdn/content#18601]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/StreamFilter/ondata

### What information was incorrect, unhelpful, or incomplete?

There's no doc about the event structure except for 'The handler is passed an event object containing a data property'.
Is this the only property ? 

### What did you expect to see?

All docs about event handling webRequest.StreamFilter.onXXX should have a link to the event structure if it matters.
If it only contains a data property, then documentation should emphasize that data is the one and only property

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/webrequest/streamfilter/ondata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/StreamFilter/ondata
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/webrequest/streamfilter/ondata/index.md
* Last commit: https://github.com/mdn/content/commit/fd9019f85fb1696c7d814735cc1cd051c4901585
* Document last modified: 2022-02-11T15:51:39.000Z

</details>

**Comment by Rob--W** [comment]
This is not the one and only property in practice. It is however the one and only supported property that you can rely on.

The object is an [Event](https://developer.mozilla.org/en-US/docs/web/api/event) instance, but e.g. `timestamp` appears to always be zero (0) instead of what one may expect from a true Event instance.
