### ISSUE TITLE
Issue with "ARIA: banner role": …

### ISSUE THREAD

**Issue by fgeierst** [mdn/content#1860]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Banner_role

#### What information was incorrect, unhelpful, or incomplete?

The first code example uses a `<h2>` element for a subtitle, which is considered a bad practice, see: https://www.w3.org/TR/html52/common-idioms-without-dedicated-elements.html#subheadings-subtitles-alternative-titles-and-taglines

```
<div role="banner">
  <img src="companylogo.svg" alt="my company name" />
  <h1>Title</h1>
  <h2>Subtitle</h2>
</div>

```
#### What did you expect to see?

Replace the `<h2>` element with a `<p>` element, same as the other two code examples on the same page.
```
<div role="banner">
  <img src="companylogo.svg" alt="my company name" />
  <h1>Title</h1>
  <p>Subtitle</p>
</div>
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/roles/banner_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Banner_role
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/accessibility/aria/roles/banner_role/index.html
* Last commit: https://github.com/mdn/content/commit/2d777fc9792270755b8b105e381b482a274e2707
* Document last modified: 2020-12-23T14:44:27.000Z

</details>

**Comment by chrisdavidmills** [comment]
I complete agree with this; thanks for reporting, @fgeierst !

I've made the update as suggested. See https://github.com/mdn/content/commit/a609a6060c38dcfcb6d8b3c9270e6364fd2cf213 for the change.
