### ISSUE TITLE
[Tools] using npx does not guarantee correct version or library

### ISSUE THREAD

**Issue by rubiesonthesky** [mdn/content#18616]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain

### What specific section or headline is this issue about?

Running the transformation

### What information was incorrect, unhelpful, or incomplete?

Running parcel with `npx` may be use different version than locally installed depending on the npm version and does user has the package installed globally / locally / not at all. This can lead to incompatible configuration / versions. As the parcel-bundler is already installed locally, it would make more sense to use that version by packege.json scripts, like parcel is instructing https://en.parceljs.org/getting_started.html#adding-parcel-to-your-project 

Here is at least one issue about which version npx is using: https://github.com/npm/cli/issues/2329 

### What did you expect to see?

Instruct user to add dev / build script to run parcel.

**Comment by Josh-Cena** [comment]
The first thing the page asks you to do is

```
npm install --save-dev parcel-bundler
```

And then `npx` is only used to invoke the local script, not to download remote packages on-the-fly.
