### ISSUE TITLE
CSS grid-template-columns documentation's "Formal syntax" section not displaying correctly 

### ISSUE THREAD

**Issue by PDalc** [mdn/content#1862]
The CSS grid-template-columns documentation's "Formal syntax" section not displaying correctly. The problem is on this page: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns 

The "Formal syntax" section is displaying the entire intricate syntax on only 2 lines, but it seems that it should be split over many more lines in order to be legible. The < pre > formatting seems to be combining multiple lines into the same line when rendering this section.

This problem appears on both the latest Chrome browser (on Windows 10) and a recent version of Firefox (also on Windows 10). 

Instead of the entire syntax being combined into two lines, it seems it should probably be displayed more like this:

<pre>
none | &lt;track-list&gt; | &lt;auto-track-list&gt; | subgrid &lt;line-name-list&gt;?

where
&lt;track-list&gt; = [ &lt;line-names&gt;? [ &lt;track-size&gt; | &lt;track-repeat&gt; ] ]+ &lt;line-names&gt;?
&lt;auto-track-list&gt; = [ &lt;line-names&gt;? [ &lt;fixed-size&gt; | &lt;fixed-repeat&gt; ] ]* &lt;line-names&gt;? &lt;auto-repeat&gt; [ &lt;line-names&gt;? [ &lt;fixed-size&gt; | &lt;fixed-repeat&gt; ] ]* &lt;line-names&gt;?
&lt;line-name-list&gt; = [ &lt;line-names&gt; | &lt;name-repeat&gt; ]+

where
&lt;line-names&gt; = '[' &lt;custom-ident&gt;* ']'
&lt;track-size&gt; = &lt;track-breadth&gt; | minmax( &lt;inflexible-breadth&gt; , &lt;track-breadth&gt; ) | fit-content( [ &lt;length&gt; | &lt;percentage&gt; ] )
&lt;track-repeat&gt; = repeat( [ &lt;positive-integer&gt; ] , [ &lt;line-names&gt;? &lt;track-size&gt; ]+ &lt;line-names&gt;? )
&lt;fixed-size&gt; = &lt;fixed-breadth&gt; | minmax( &lt;fixed-breadth&gt; , &lt;track-breadth&gt; ) | minmax( &lt;inflexible-breadth&gt; , &lt;fixed-breadth&gt; )
&lt;fixed-repeat&gt; = repeat( [ &lt;positive-integer&gt; ] , [ &lt;line-names&gt;? &lt;fixed-size&gt; ]+ &lt;line-names&gt;? )
&lt;auto-repeat&gt; = repeat( [ auto-fill | auto-fit ] , [ &lt;line-names&gt;? &lt;fixed-size&gt; ]+ &lt;line-names&gt;? )

where
&lt;track-breadth&gt; = &lt;length-percentage&gt; | &lt;flex&gt; | min-content | max-content | auto
&lt;inflexible-breadth&gt; = &lt;length&gt; | &lt;percentage&gt; | min-content | max-content | auto
&lt;fixed-breadth&gt; = &lt;length-percentage&gt;

where
&lt;length-percentage&gt; = &lt;length&gt; | &lt;percentage&gt;
</pre>

**Comment by rachelandrew** [comment]
This was fixed via a different issue.
