### ISSUE TITLE
incorrect output

### ISSUE THREAD

**Issue by ayyubnurumi** [mdn/content#18632]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Text_formatting

### What specific section or headline is this issue about?

date and time formating

### What information was incorrect, unhelpful, or incomplete?

this is the exemple in date and time formating section

```js
const msPerDay = 24 * 60 * 60 * 1000;

// July 17, 2014 00:00:00 UTC.
const july172014 = new Date(msPerDay * (44 * 365 + 11 + 197));

const options = { year: '2-digit', month: '2-digit', day: '2-digit',
                hour: '2-digit', minute: '2-digit', timeZoneName: 'short' };
const americanDateTime = new Intl.DateTimeFormat('en-US', options).format;

console.log(americanDateTime(july172014)); // 07/16/14, 5:00 PM PDT
```

17 july 2014 should be 07/17/14

### What did you expect to see?

07/17/14, 7:00 AM GMT+7

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/text_formatting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Text_formatting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/text_formatting/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by teoli2003** [comment]
No, that's the date below that is wrong (not the top comment). PR incoming.

**Comment by teoli2003** [comment]
In fact it was correct, for PDT :-D
Anyway, it is clearer with the new comment.
