### ISSUE TITLE
Formal syntax of math-style is missing

### ISSUE THREAD

**Issue by fred-wang** [mdn/content#18641]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/math-style

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/math-style#formal_syntax

### What information was incorrect, unhelpful, or incomplete?

Section only contains `Error: could not find syntax for this item`

### What did you expect to see?

The formal syntax.

### Do you have any supporting links, references, or citations?

https://w3c.github.io/mathml-core/#the-math-style-property

### Do you have anything more you want to share?

The same issue exists for `math-depth`: https://developer.mozilla.org/en-US/docs/Web/CSS/math-depth#formal_syntax
(that one has more data missing, that will be fixed by https://github.com/mdn/browser-compat-data/pull/17071)

Doc: https://w3c.github.io/mathml-core/#the-math-script-level-property

cc @teoli2003 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/math-style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/math-style
* GitHub URL: https://github.com/mdn/content/blob/mstyle-rewrite/files/en-us/web/css/math-style/index.md
* Last commit: https://github.com/mdn/content/commit/null
* Document last modified: 2020-12-12T22:36:34.292Z

</details>

**Comment by teoli2003** [comment]
Since the end of June, we don't use the outdated data we had at mdn/data for the formal syntax, but we extract it now from w3c/webref. It is likely that the MathML Core is missing from the spec read to generate the data. I opened w3c/webref#681 to get this fixed.

**Comment by fred-wang** [comment]
I see that the formal definition is now available for `math-style` (not `math-depth` yet):

https://developer.mozilla.org/en-US/docs/Web/CSS/math-style#formal_definition
https://developer.mozilla.org/en-US/docs/Web/CSS/math-depth#formal_definition

There is another section "formal syntax" which I guess is for the value, but apparently it's not taken even if in webref ( https://github.com/w3c/webref/issues/681#issuecomment-1225917453 )

**Comment by fred-wang** [comment]
`math-style` now has formal definition and syntax, so closing this one. As stated above the issue is still present for `math-depth` and `math-shift`, but hopefully it will be available at the next webref update.

**Comment by fred-wang** [comment]
Remaining work is tracked by https://github.com/mdn/content/issues/18780
