### ISSUE TITLE
Drop wordcount line from SEO guide

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#1864]
I'm quite confident this line is outdated and should be removed:

https://github.com/mdn/content/blob/4b5283173b093d6c44e1617beb8ab4efe81717ac/files/en-us/mdn/contribute/howto/write_for_seo/index.html#L55

Live site:
https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Write_for_SEO#avoid_pages_that_are_too_short

(while at it, the anchors seem not correct also. They should be all lowercase)

**Comment by Ryuno-Ki** [comment]
I'd like to label this as good first issue.

**Comment by chrisdavidmills** [comment]
Labeled ;-)

**Comment by sanket2000sonavane** [comment]
hello sir, I am a beginner. I would like to complete this task.

**Comment by chrisdavidmills** [comment]
@sanket2000sonavane thank you for your interest.

Let me know if you need any help.

**Comment by chrisdavidmills** [comment]
I've checked that page, and it looks like this got fixed, so closing.
