### ISSUE TITLE
Issue with "Separate sites for mobile and desktop": … "Responsive Design" link at the bottom does not link to the correct page.

### ISSUE THREAD

**Issue by jacobtrebil** [mdn/content#1866]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Mobile/Separate_sites

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/guide/mobile/separate_sites`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Mobile/Separate_sites
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/guide/mobile/separate_sites/index.html
* Last commit: https://github.com/mdn/content/commit/452985968235edef6a702b5d5c9c35edab9b6265
* Document last modified: 2021-01-21T16:21:14.000Z

</details>

**Comment by chrisdavidmills** [comment]
This was kinda strange; thanks for reporting it, @jacobtrebil !

We now have a pretty good beginner's guide to responsive design, so I've linked it to that instead. See https://github.com/mdn/content/commit/4ad95e38da46ff56f0dcc42477efa11d253b0569 for the change.
