### ISSUE TITLE
Broken GitHub link for live code editor in Task 2 under "Test your skills: The Cascade - Learn web development | MDN"

### ISSUE THREAD

**Issue by nick-chesterton** [mdn/content#18722]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_tasks

### What specific section or headline is this issue about?

Task 2

### What information was incorrect, unhelpful, or incomplete?

The live code box for Task 2 did not appear, but instead gave a 404 error saying, "404 File Not Found: The site configured at this address does not contain the requested file."

### What did you expect to see?

The editable live code box for Task 2.

### Do you have anything more you want to share?

I do have a screenshot, but had trouble attaching it. I can provide it on request.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_tasks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_tasks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_tasks/index.md
* Last commit: https://github.com/mdn/content/commit/f64936b238949eb7255f00042d54b931c6db8b95
* Document last modified: 2022-07-21T00:16:34.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened #18726 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
