### ISSUE TITLE
False claim: window.pageYOffset === window.scrollY; // always true

### ISSUE THREAD

**Issue by hilbix** [mdn/content#18735]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY

### What specific section or headline is this issue about?

Notes

### What information was incorrect, unhelpful, or incomplete?

The `pageYOffset` property is an alias for the `scrollY` property:

`window.pageYOffset === window.scrollY; // always true`

### What did you expect to see?

If not redefined, the `scrollY` property is an alias for the `pageYOffset` property.  In that case following holds:

window.pageYOffset === window.scrollY; // always true

(I do not know if this makes any sense.  See supporting information.)

### Do you have any supporting links, references, or citations?

I created some content-scripts on Google Chrome (through Extension) which sets the property `window.scrollY`to a negative value (which actually was a bug of my content script, but nevertheless it exposed this problem here).

Afterwards `window.pageYOffset === window.scrollY` was no more true on the content-script,as `window.scrollY` stayed negative, but `window.pageYOffset` continued to work as usual.

Also you state, this property is readonly.  Whatever this means, because I thought that by assigning to `window.scrollY` you can create an effect like with `window.scrollTo()` on Chrome.  (Perhaps I am completely wrong here.)

Read:

**I really have no idea if this is a bug, a feature, some undocumented part of browser extensions, something browser specific, intended or whatever.**

But:

At my side, `window.scrollY` can be set to something negative (which makes no sense at all) and hence the `===` becomes false.

This either is a Browser compatibility issue or some lack of documentation.  In any way, it should be clearly stated.

### Do you have anything more you want to share?

Ubuntu 20.04 LTS
Chrome 102.0.5005.115 (Official Build) (64-bit)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/scrolly`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/scrolly/index.md
* Last commit: https://github.com/mdn/content/commit/cc1f5c3bd1a9976a0668eeee016f6afc144533b0
* Document last modified: 2022-06-03T04:32:25.000Z

</details>

**Comment by emilio** [comment]
They are real aliases, but these properties are `readonly` and `[Replaceable]` (https://webidl.spec.whatwg.org/#Replaceable), which means that you can redefine them by setting the property, which is what you're seeing.

**Comment by Josh-Cena** [comment]
Some observation that may be interesting, if people want to understand how it works:

```js
Object.getOwnPropertyDescriptor(window, "scrollY");
// {enumerable: true, configurable: true, get: ƒ, set: ƒ}
window.scrollY = 1;
Object.getOwnPropertyDescriptor(window, "scrollY");
// {value: 1, writable: true, enumerable: true, configurable: true}
```

**Comment by Josh-Cena** [comment]
We'll also track https://github.com/mdn/content/issues/19933 in this issue, because that one looks quite unactionable given the OP is no longer there. To whoever works on this: please make sure the related pages are all fact-checked.
