### ISSUE TITLE
HTMLFormControlsCollection page has some unclear / incorrect information

### ISSUE THREAD

**Issue by nathnolt** [mdn/content#18733]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormControlsCollection

### What specific section or headline is this issue about?

section 1

### What information was incorrect, unhelpful, or incomplete?

I think it states that the property elements on HTMLFieldSetElement will return HTMLFormControlsCollection but instead it returns HTMLCollection. It's only the HTMLFormElement which will return HTMLFormControlsCollection (at least in the test code I made.)

### What did you expect to see?

I expect to see documentation which states that it only works on the HTMLFormElement -- But then again, maybe it does work in a different setup. at least how it's written now, I believe it can be clearer.

### Do you have any supporting links, references, or citations?

Demo to see the problem https://codepen.io/nathnolt/pen/KKovPRb

### Do you have anything more you want to share?

Demo to see the problem https://codepen.io/nathnolt/pen/KKovPRb

Thanks for reading :)

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. The MDN article is wrong, and what the issue description states is right.

So the page needs to be corrected to state that  the `elements` property of `HTMLFieldSetElement` objects returns an `HTMLCollection` object.

For the record here, this is what the HTML spec has to say:

At https://html.spec.whatwg.org/multipage/form-elements.html#htmlfieldsetelement, the HTML spec says that the `elements` property of `HTMLFieldSetElement` objects returns an `HTMLCollection` object — not an `HTMLFormControlsCollection`.

At https://html.spec.whatwg.org/multipage/forms.html#htmlformelement the HTML spec says that the `elements` property of `HTMLFormElement` objects returnr an `HTMLFormControlsCollection`. And that’s the _only_ case for which the HTML spec says an `HTMLFormControlsCollection` is returned.

**Comment by sideshowbarker** [comment]
Thanks again for catching this and reporting it. I’ve opened #18749 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
