### ISSUE TITLE
Inconsistent file/dir naming

### ISSUE THREAD

**Issue by krzysztof-tokarski** [mdn/content#18739]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes

### What specific section or headline is this issue about?

Create the route-handler callback functions and post that

### What information was incorrect, unhelpful, or incomplete?

The snippets (and further citations) use both kebabcase and camelcase for naming of dirs and files, instead of following one pattern.

### What did you expect to see?

Change everything to kebabcase.

**Comment by hamishwillee** [comment]
Thanks. I'm happy enough that these could be changed to kebab case, but I don't see it as any kind of priority. IF this is done, then the https://github.com/mdn/express-locallibrary-tutorial/ would need to be updated in sync and tested. 

Would you like to do this?
The set of files in the project are:

```
\app.js
\bin
\CODE_OF_CONDUCT.md
\controllers
\filelist.txt
\LICENSE
\models
\public
\README.md
\routes
\views
\bin\www
\controllers\authorController.js
\controllers\bookController.js
\controllers\bookinstanceController.js
\controllers\genreController.js
\models\author.js
\models\book.js
\models\bookinstance.js
\models\genre.js
\public\images
\public\stylesheets
\public\images\Library Website - Mongoose_Express.png
\public\stylesheets\style.css
\routes\catalog.js
\routes\index.js
\routes\users.js
\views\author_delete.pug
\views\author_detail.pug
\views\author_form.pug
\views\author_list.pug
\views\bookinstance_delete.pug
\views\bookinstance_detail.pug
\views\bookinstance_form.pug
\views\bookinstance_list.pug
\views\book_delete.pug
\views\book_detail.pug
\views\book_form.pug
\views\book_list.pug
\views\error.pug
\views\genre_delete.pug
\views\genre_detail.pug
\views\genre_form.pug
\views\genre_list.pug
\views\index.pug
\views\layout.pug
```

**Comment by krzysztof-tokarski** [comment]
Sure, although I will first look over the lesson again and possibly raise
some additional issues to see if we're eye to eye on them, and possibly
make changes in the same pull?

Pon., 25 lip 2022, 02:19 użytkownik Hamish Willee ***@***.***>
napisał:

**Comment by hamishwillee** [comment]
I'm going to close this. The vast number of people will not even notice, and the few that do are unlikely to draw false conclusions that they need to name using this pattern. So the inconsistency is a little annoying, but not worth the time to fix.
