### ISSUE TITLE
Mention inline-size containment

### ISSUE THREAD

**Issue by Seirdy** [mdn/content#18758]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/contain

### What specific section or headline is this issue about?

Values

### What information was incorrect, unhelpful, or incomplete?

The page does not mention the `inline-size` value. 

### What did you expect to see?

I expected to see the `inline-size` value listed as a possible value for the `contain` CSS property.

### Do you have any supporting links, references, or citations?

This is documented in the [CSS Containment Level 3 specification](https://www.w3.org/TR/css-contain-3/#inline-size); it is implemented in WebKit, Firefox, and Chromium.

- [WebKit bug 236354](https://bugs.webkit.org/show_bug.cgi?id=236354)
- [Mozilla bug 1755565](https://bugzilla.mozilla.org/show_bug.cgi?id=1755565)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/contain`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/contain
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/contain/index.md
* Last commit: https://github.com/mdn/content/commit/4e7553185bcaf7f30ec7fec9ae35aa3e8c787bfa
* Document last modified: 2022-07-11T21:06:17.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. I believe https://drafts.csswg.org/css-contain-3/#contain-property is the specific spec section that’s relevant. For the record here, quoting that:

> <h2 class="heading settled" data-level="2" id="contain-property"><span class="secno">2. </span><span class="content"> Strong Containment: the <a class="property css" data-link-type="property" href="https://drafts.csswg.org/css-contain-2/#propdef-contain" id="ref-for-propdef-contain①">contain</a> property</span><a class="self-link" href="https://drafts.csswg.org/css-contain-3/#contain-property"></a></h2>
>    
>    <dl>
>     <dt><dfn class="css" data-dfn-for="contain" data-dfn-type="value" data-export="" id="valdef-contain-inline-size">inline-size<a class="self-link" href="https://drafts.csswg.org/css-contain-3/#valdef-contain-inline-size"></a></dfn> 
>     </dt><dd>
>       This value turns on <a data-link-type="dfn" href="https://drafts.csswg.org/css-contain-3/#inline-size-containment" id="ref-for-inline-size-containment">inline-size containment</a> for the element.
> 			This prevents the <a data-link-type="dfn" href="https://drafts.csswg.org/css-writing-modes-4/#inline-size" id="ref-for-inline-size">inline-size</a> of its <a data-link-type="dfn" href="https://drafts.csswg.org/css-display-3/#principal-box" id="ref-for-principal-box">principal box</a> from directly depending on its contents. 
>    </dd></dl>
> 
> Name: | [contain](https://drafts.csswg.org/css-contain-2/#propdef-contain)
> ------ | --------
> [New values:](https://www.w3.org/TR/css-values/#value-defs) | layout \|\|  style \|\| paint  \|\| [ size \| inline-size ]

**Comment by sideshowbarker** [comment]
Fixing this also needs to include:

* updating the syntax definition in https://github.com/mdn/data/blob/ed1833d1ba4f6bbd037e9a9b5e6017e1177568cf/css/properties.json#L4191-L4192
* updating the in-article syntax block at: https://github.com/mdn/content/blob/40c173c51db62c5ec00ad69c7dca5be965cb8978/files/en-us/web/css/contain/index.md?plain=1#L31-L45
* adding the value and a prose description for it to https://developer.mozilla.org/en-US/docs/Web/CSS/contain#values

Ideally, the examples section at https://developer.mozilla.org/en-US/docs/Web/CSS/contain#examples should also be updated to include an example for `inline-style`.

**Comment by Seirdy** [comment]
Perhaps an update to the BCD would also be necessary.

None of the browsers I tested seem to allow combining `inline-size` with other forms of containment; i.e., `contain: content inline-size` is considered invalid. This doesn't seem clearly documented in the spec, but it should probably be mentioned on MDN if it isn't a bug.

-- 
Seirdy

**Comment by teoli2003** [comment]
cc/ @Rumyra. This looks like it was in Firefox 101 and was missed. Maybe you can help here?

**Comment by Rumyra** [comment]
Thanks @teoli2003 - yes the original bug didn't have `dev-doc-needed` so it was unfortunately missed, I've added it to out release project and we should be able to tackle it 👍

**Comment by Seirdy** [comment]
On Mon, Jul 25, 2022 at 09:06:05AM -0700, Rohan Kumar wrote:
>None of the browsers I tested seem to allow combining `inline-size` with other forms of containment; i.e., `contain: content inline-size` is considered invalid.

Correction: `inline-size` can in fact be combined with other values, but not `content`.

`contain: layout paint inline-size` should be equivalent to strict containment with the exception of the block axis. `contain: content inline-size` is invalid.

-- 
Seirdy (https://seirdy.one)

**Comment by sideshowbarker** [comment]
> Perhaps an update to the BCD would also be necessary.

@hamishwillee landed that in https://github.com/mdn/browser-compat-data/pull/17469

> None of the browsers I tested seem to allow combining `inline-size` with other forms of containment; i.e., `contain: content inline-size` is considered invalid. This doesn't seem clearly documented in the spec, but it should probably be mentioned on MDN if it isn't a bug.

I see there are `contain-inline-*` test results in https://wpt.fyi/results/css/css-contain which show all engines passing most of those tests (though notably, Safari is failing all the https://wpt.fyi/results/css/css-contain/contain-inline-size-replaced.html tests…)

If you were to look at the test sources https://github.com/web-platform-tests/wpt/tree/master/css/css-contain, you might be able to find if there are tests for the _“allow combining `inline-size` with other forms of containment”_ case.

**Comment by bsmth** [comment]
To clarify, the `contain` value can be

 * `[ none || strict || content ]`

__or__

* `[ [ size || inline-size ] || layout || style || paint ]`

I think the confusion here comes from the fact that `content` is a special case because it is shorthand for `contain: layout paint` and `strict` is shorthand for `size layout paint`.

In the wpt repo, [there are tests showing valid combinations](https://wpt.fyi/results/css/css-contain/parsing?label=experimental&label=master&aligned&view=subtest):
- `test_valid_value("contain", "layout inline-size", "inline-size layout");`

According to the spec, `inline-size` can be combined with any of `layout`, `style`, and `paint` and the wpt tests show at least a combination of `layout inline-size` passing.
