### ISSUE TITLE
[Not released] [WebAPI] Support the CSS Font Loading API in workers

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#18769]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Support the CSS Font Loading API in workers
Looks like just a rel note and bcd needed https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1072107

**Comment by hamishwillee** [comment]
> Looks like just a rel note and bcd needed https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API

It's never that easy :-). This is behind a pref, and I'd say those docs are very "thin".

Status:

- [ ] BCD
- [ ] Experimental features
- [ ] Docs
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
> It's never that easy :-)

Sorry @hamishwillee

**Comment by hamishwillee** [comment]
No need to be sorry. I just thought it was funny. This is going to take quite a bit of work based on the quality metric "does Hamish think that the existing docs would enable him to use the API". They do not.
