### ISSUE TITLE
[JS] Ship Array.{findLast,findLastIndex}

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#18774]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Update to rel notes & bcd

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1775026

**Comment by hamishwillee** [comment]
This follows on from #17473, which added the feature behind a flag. Just is just BCD, release note, and remove from experimental features.

- [ ] BCD
- [ ] Docs
- [ ] Release Note
- [ ] Remove experimental features
- [ ] dev-doc-complete
