### ISSUE TITLE
[WebAPI] Add disabled property to SVGStyleElement

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#18775]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Looks like the SVGStyleElement page could do with some updates https://developer.mozilla.org/en-US/docs/Web/API/SVGStyleElement

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1712623

**Comment by hamishwillee** [comment]
Yes, there is quite a lot missing in this area. I'll have a look.

Status:

- [ ] BCD
- [ ] Docs
- [ ] Release notes
- [ ] dev-doc-complete

**Comment by hamishwillee** [comment]
My test code for .disabled (a note) 
[test_svgstyleelement.zip](https://github.com/mdn/content/files/9231434/test_svgstyleelement.zip)

**Comment by Rumyra** [comment]
FWIW SVG docs update is on my content strategy, as I agree the whole area could do with a good update 👍
