### ISSUE TITLE
Issue with "RSS feeds": All links are dead

### ISSUE THREAD

**Issue by SpyroTEQ** [mdn/content#1877]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Tools/Feeds

#### What information was incorrect, unhelpful, or incomplete?
Seems like all RSS feeds are dead (404 page not found)

#### Specific section or headline?
All

#### What did you expect to see?
The RSS feeds (at least for https://developer.mozilla.org/en-US/docs/feeds/rss/all)

#### Did you test this? If so, how?
Just click the links. Seems dead since 13 Dec 2020 (I thought it was connexion issues from my email client, but seems to be MDN changes)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/tools/feeds`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Tools/Feeds
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/tools/feeds/index.html
* Report started: 2021-01-29T08:32:59.193Z

</details>

**Comment by Ryuno-Ki** [comment]
Uh-oh.

Thanks for bringing this to our attention!
@peterbe I assume, the feeds are auto-generated. Would be great if you could take a look into it.

**Comment by chrisdavidmills** [comment]
This is weird. I removed the feeds page a while ago because they no longer work (the source link 404s: https://github.com/mdn/content/blob/main/files/en-us/mdn/tools/feeds/index.html), so I don't know why the page is still showing up on the site.

**Comment by SpyroTEQ** [comment]
oh :c It would be nice to have RSS back working (for me at least ^^), or (if not doable) any other way to know what the changes were "today/this week": I mainly use the RSS feed to do a regular check on the new web APIs/functions or on those I did not know (like, when RSS title was about a doc page for a function/API that I don't know, then I go to read it and get to know this new API though the new MDN doc)

If you have any other way to achieve this goal, I'm listening :)

**Comment by chrisdavidmills** [comment]
I would imagine there'd be a way to achieve this via GitHub history, some kind of dashboard that allows you to query different areas of the content and pull up the changed pages over a set time period. But this wouldn't be a high priority compared to some of the more pressing needs we've got. We'll have to think about the easiest way to achieve this.

**Comment by peterbe** [comment]
@chrisdavidmills We haven't implemented the functionality that deletes (no-longer built stuff) in S3. Thankfully, our XML sitemaps that we submit to Google don't mention this URL. 
I believe @escattone is working on it here: https://github.com/mdn/yari/issues/2224

**Comment by Ryuno-Ki** [comment]
@SpyroTEQ https://github.com/mdn/content/commits/main.atom is the GitHub feed for all changes added to the `main` branch.

See https://www.ronaldsvilcins.com/2020/03/26/rss-feeds-for-your-github-releases-tags-and-activity/ for other feeds.

**Comment by sideshowbarker** [comment]
https://developer.mozilla.org/en-US/docs/MDN/Tools/Feeds is now 404 — with no links on it — which I believe is expected — since per https://github.com/mdn/content/issues/1877#issuecomment-769664433 it as intentionally deleted, and we intentionally have no replacement.

Therefore, I’m going ahead and closing this issue. But if I’m mistaken and there’s some reason we still want to keep this open, somebody please do re-open it.
