### ISSUE TITLE
MediaCapabilitiesInfo is a dictionary in spec + Chrome but interface in Firefox

### ISSUE THREAD

**Issue by foolip** [mdn/content#1878]
https://developer.mozilla.org/en-US/docs/Web/API/MediaCapabilitiesInfo needs to be sorted out because of an unfortunate situation across specs and implementation.

This is a dictionary in spec and Chrome:
https://w3c.github.io/media-capabilities/#media-capabilities-info
https://chromium.googlesource.com/chromium/src/+/6ad4130faeeead16d8bf620c4387283da143ac09/third_party/blink/renderer/modules/media_capabilities/media_capabilities_info.idl

But an interface in Firefox:
https://github.com/mozilla/gecko-dev/blob/7ef5cefd0468b8f509efe38e0212de2398f4c8b3/dom/webidl/MediaCapabilities.webidl#L52

The documentation should probably still describe it as a dictionary, but filing an issue because it's an unusual situation. It shouldn't really matter to web developers, the difference is just that `window.MediaCapabilitiesInfo` exists in Firefox.

**Comment by foolip** [comment]
I've filed a Gecko bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1689560.

**Comment by jpmedley** [comment]
Is the spec up to date? It's not unheard of for implementations get ahead of specs. Eventually one of the implementation will need to change to match the spec. MDN should match the most up-to-date spec.

**Comment by foolip** [comment]
The Gecko developers didn't push back against the spec in https://bugzilla.mozilla.org/show_bug.cgi?id=1689560, so I think MDN should treat this as a dictionary. Which probably means not documenting it as its own thing at all, but rather as part of https://developer.mozilla.org/en-US/docs/Web/API/MediaCapabilities/encodingInfo and https://developer.mozilla.org/en-US/docs/Web/API/MediaCapabilities/decodingInfo.

**Comment by Elchi3** [comment]
https://github.com/mdn/content/pull/9781 removed this dictionary from MDN.
