### ISSUE TITLE
"While it is not always possible to maintain 60fps, it is important to maintain a high and steady frame rate for all animations."

### ISSUE THREAD

**Issue by MarjaE2** [mdn/content#18785]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate

### What specific section or headline is this issue about?

Animation performance and frame rate

### What information was incorrect, unhelpful, or incomplete?

"Users expect all interface interactions to be smooth and all user interfaces to be responsive."

Just because users may *expect* more and more websites to inflict "smooth" animation, motion sickness, migraines, and so on, doesn't mean every user *wants* them to.

"While it is not always possible to maintain 60fps, it is important to maintain a high and steady frame rate for all animations."

### What did you expect to see?

I was trying to see if user css could reduce frame rates on a per-domain basis, so I could read Google Docs without getting migraines.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/performance/animation_performance_and_frame_rate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/performance/animation_performance_and_frame_rate/index.md
* Last commit: https://github.com/mdn/content/commit/c9dc772a9deb0a379518cc6a0aff23182daceeda
* Document last modified: 2022-07-23T04:09:16.000Z

</details>

**Comment by sideshowbarker** [comment]
If you have a specific suggestion for how the current statements could be reworded or supplemented with additional wording, please open a pull request with a patch.

**Comment by Josh-Cena** [comment]
(Also note that FPS is different from animation speed / reduced motion. It's usually dramatic animation combined with low FPS that causes motion sickness. High FPS is AFAICT always desirable.)

**Comment by MarjaE2** [comment]
In my experience, *both* flashing *and* smooth animation make me sick. So no, smoother is not better. I have to disable smooth scrolling, and I still get sick from a lot of sites which inflict smooth zooming, or ease in-out, or their own special smooth scrolling via Javascript, and so on.

In addition, the page has a number of non-scrolling elements protruding into the upper right corner, which are also a migraine trigger.

In Firefox, I can work around "smooth" animations, and around non-scrolling elements, by setting layout.frame_rate 1, i.e. 1 refresh per second.

I would change "Users expect all interface interactions to be smooth and all user interfaces to be responsive. Animation can help make a site feel faster and responsive, but animations can also make a site feel slower and janky if not done correctly. Responsive user interfaces have a frame rate of 60 frames per second (fps). While it is not always possible to maintain 60fps, it is important to maintain a high and steady frame rate for all animations." to

"Users expect all user interfaces to be responsive. Animation can help make a site feel faster and responsive, but animations can also make a site feel slower and janky if not done correctly. Individual users needs may vary. Some users will find flashing helpful. Others will find flashing and/or smooth animation harmful. The prefers-reduced-motion tag may help signal these needs."
