### ISSUE TITLE
Hierarchy of the example is not ordered correctly? or suppose to be not ordered? 

### ISSUE THREAD

**Issue by angelayanpan** [mdn/content#18817]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

### What specific section or headline is this issue about?

The stacking context

### What information was incorrect, unhelpful, or incomplete?

Reading below bullet points:

> The hierarchy of stacking contexts is organized as follows:
> 
> Root
> DIV #1
> DIV #2
> DIV #3
> DIV #4
> DIV #5
> DIV #6

and then reading the later part:

> In our example (sorted according to the final rendering order):
> Root
> DIV #2 - z-index is 2
> DIV #3 - z-index is 4
> DIV #5 - z-index is 1, stacked under an element with a z-index of 4, which results in a rendering order of 4.1
> DIV #6 - z-index is 3, stacked under an element with a z-index of 4, which results in a rendering order of 4.3
> DIV #4 - z-index is 6, stacked under an element with a z-index of 4, which results in a rendering order of 4.6
> DIV #1 - z-index is 5

So if both of these are correct,  then "hierarchy" and the "rendering order" are 2 different concepts? 
I'm able to understand why the "rendering order" are the way they are. 
I'm guessing in the "hierarchy" part, the order is not significant.  but it's not clearly stated. maybe it needs to clearly state (not ordered in any way)? 

### What did you expect to see?

The "hierarchy" of the example is confusing. 

1. if we render them in a flat way, not bullet point, it can convey they are not ordered. 

2. or it needs to specify: "elements of each hierarchy is not ordered"? 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_positioning/understanding_z_index/the_stacking_context`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_positioning/understanding_z_index/the_stacking_context/index.md
* Last commit: https://github.com/mdn/content/commit/8504c291b3e71344e6b1f62db7edb780dde7195d
* Document last modified: 2022-05-18T18:41:26.000Z

</details>

**Comment by najmiehsa** [comment]
I take this issue.

**Comment by angelayanpan** [comment]
thanks!

I was reading the issue again.  just want to point out the main confusion was .... I read the first bullet points, I was like "why is Div3 not ordered in between 1 and 2?" 
I wondered about that for a while.  then I read more further down the page, and then I saw the second list.

**Comment by najmiehsa** [comment]
This is actually a good point because I had forgotten about the difference between hierarchy and rendering order.

**Comment by Josh-Cena** [comment]
Fixed by #18989
