### ISSUE TITLE
iOS older versions not supporting the custom Intl.NumberFormat implementation for global number format

### ISSUE THREAD

**Issue by kalesandhya** [mdn/content#18814]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

### What specific section or headline is this issue about?

Older version of iOS 11.x, 12.x & 13.x not compatible with Intl.numberformat custom implemnetation

### What information was incorrect, unhelpful, or incomplete?

```js
let language = document.querySelector('meta[name="language"]').content;
let country = document.querySelector('meta[name="country"]').content;
let currency = 'USD';
if(country === 'in') currency = 'INR';
let region = language+'-'+(country.toUpperCase());
	return new Intl.NumberFormat(region, { style: 'currency', currency: currency, currencyDisplay: 'narrowSymbol'}).format(amount);
```

This code snippet raising a console error as, _RangeError: currencyDisplay must be either 'Code', 'symbol or name_.
The use case of this implementation is, the website is global & wanted to have global number format for all countries & languages as per page meta.

Is there anything missing in implementation or incorrect as per API design?
Has anyone faced similar issues, please reach out. Any leads would be appreciated here.

### What did you expect to see?

This API should support older iOS versions.
![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/106073715/181023209-334cc31a-c296-4568-9a96-cd8e2d12823b.png)

### Do you have any supporting links, references, or citations?

Following this guideline from this documentation, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat as per browser support section listed on this page, the above implementation should work

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/index.md
* Last commit: https://github.com/mdn/content/commit/e61ec2522d44ccfad5c7d54ad54983e5e14ac84a
* Document last modified: 2022-07-18T06:38:48.000Z

</details>

**Comment by Josh-Cena** [comment]
According to the browser compatibility table, `options.currencyDisplay` is only supported in Safari >14.1 and Safari iOS >14.5.

**Comment by queengooborg** [comment]
> According to the browser compatibility table, `options.currencyDisplay` is only supported in Safari >14.1 and Safari iOS >14.5.

Actually, the option is _fully_ supported since Safari 14.1 -- if you click on the table cell, you can see that the feature was supported since Safari 10, however the `narrowSymbol` value was not supported.  That seems to be what is confirmed here by the issue author based upon the code sample provide, so there isn't any action to take on this issue.

**Comment by Josh-Cena** [comment]
Oooh yeah I see that now :D

**Comment by kalesandhya** [comment]
Thanks for updates on this thread & providing all the details.
Going ahead with the 'symbol' as currencyDisplay option so that is now compatible with older versions of iOS.
