### ISSUE TITLE
Issue with "CSS reference": link from inherits (@property) is dead

### ISSUE THREAD

**Issue by benkasminbullock** [mdn/content#1884]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

#### What information was incorrect, unhelpful, or incomplete?

The link on `inherits (@property)` was a dead link:

https://developer.mozilla.org/en-US/docs/Web/CSS/@property/inherits

#### Specific section or headline?

As above.

#### What did you expect to see?

Information on the CSS property

#### Did you test this? If so, how?

Not in any way other than through the browser.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/reference/index.html
* Last commit: https://github.com/mdn/content/commit/2ef7bb784bf1036ad7886b64e6451a68e573a44b
* Document last modified: 2021-01-15T08:25:52.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@rachelandrew We have https://developer.mozilla.org/en-US/docs/Web/CSS/@property - ( matching https://github.com/mdn/content/blob/main/files/en-us/web/css/%40property/index.html)

but I can't find an explanation of `inherits` there. Is this a missing document?

**Comment by rachelandrew** [comment]
We actually don't have any of the `@property` descriptors documented, I'll do these.
