### ISSUE TITLE
How can I access CSS_Ref?

### ISSUE THREAD

**Issue by benkasminbullock** [mdn/content#1885]
Here it looks like CSS_Ref is made from some kind of templating system:

https://github.com/mdn/content/blob/2ef7bb784bf1036ad7886b64e6451a68e573a44b/files/en-us/web/css/reference/index.html#L60

I cannot see what templating is being used. I searched the repo with "CSS_Ref repo:mdn/content" but it only came back with the above link.

I want to find a downloadable version of the index on the page:

https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#index

This is to use for a CSS checker.

See here:

https://github.com/manwar/Test-CSS/issues/2

Also here:

**Comment by Ryuno-Ki** [comment]
I _think_ it's defined over in the kumascript repo:

https://github.com/mdn/kumascript/blob/a3c7b89ca55a0677ef9da53f60c6d3be86248597/macros/CSSRef.ejs

That's code used for the old wiki edition and will be phased out one bit at a time.

**Comment by chrisdavidmills** [comment]
> I _think_ it's defined over in the kumascript repo:
> 
> https://github.com/mdn/kumascript/blob/a3c7b89ca55a0677ef9da53f60c6d3be86248597/macros/CSSRef.ejs
> 
> That's code used for the old wiki edition and will be phased out one bit at a time.

The up-to-date version of KumaScript is available inside the Yari repo; see https://github.com/mdn/yari/blob/master/kumascript/macros/CSS_Ref.ejs for the updated macro file.

We are still aiming to phase out KS over time, but this is where it now lives.

**Comment by benkasminbullock** [comment]
Thanks for the information. It looks like it will be difficult to use that system for our purposes.
