### ISSUE TITLE
A mistake in the provided example.

### ISSUE THREAD

**Issue by AnsBdran** [mdn/content#18855]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration

### What specific section or headline is this issue about?

while statement, example one

### What information was incorrect, unhelpful, or incomplete?

the changing in the value of "x" as you describe it is false, after the first pass: the value of n is 1, that's true, BUT; if you look at the MDN documentation for the increment(++), you will find that using the increment sign(++) after the operand will increment the value of n, but it will assign the value before incrementing to x, so after the first pass x will be zero, and n will be one, after the second pass x will be 1 and n will be 2, after the third pass x will be 3 and n will be 3.
thanks a lot for your work.

### What did you expect to see?

first pass: x = 0, n = 1;
second pass: x = 1, n = 2;
third pass: x = 3; n = 3;

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Increment

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/loops_and_iteration`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/loops_and_iteration/index.md
* Last commit: https://github.com/mdn/content/commit/31fb5716eac5f3ef6d7aa094c1a1d16a5e7e53bc
* Document last modified: 2022-07-21T08:12:11.000Z

</details>

**Comment by Josh-Cena** [comment]
<img width="198" alt="image" src="https://user-images.githubusercontent.com/55398995/181290312-dc938767-046a-42e2-b546-f35d1039c335.png">

Doing some quick experiment will help.

Postfix increment means the _value_ is returned before it's incremented. It's desugared to:

```js
const increment = (n) => {
  const res = n + 1;
  n = n + 1;
  return res;
}
```

So if `n++;` appears on its own, it has the same effect as `n = n + 1`.

**Comment by AnsBdran** [comment]
![image](https://user-images.githubusercontent.com/83476254/181292142-e0d69390-067b-4ab2-b072-acabb7d50246.png)
you are right, I forget that i edited the syntax of the loop example.
sorry for that.
