### ISSUE TITLE
Background scripts: Snippet requires correction

### ISSUE THREAD

**Issue by erosman** [mdn/content#18936]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts

### What specific section or headline is this issue about?

Filter events

### What information was incorrect, unhelpful, or incomplete?

```js
browser.webNavigation.onCompleted.addListener(function() {
  alert("This is my favorite website!");
}, {url: [{urlMatches : 'https://www.google.com/'}]});
```

Above Code snippet (transferred from [Filter events](https://developer.chrome.com/docs/extensions/mv2/background_pages/#filters)) includes `alert()` which conflicts with [DOM APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts#dom_apis) and can be confusing for the developers:

> Warning: In Firefox, background pages do not support the use of [alert()](https://developer.mozilla.org/en-US/docs/Web/API/Window/alert), [confirm()](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm), or [prompt()](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt).

### What did you expect to see?

Code Snippet that is applicable to Firefox.

**Comment by teoli2003** [comment]
A simple log to the console, like `console.log()` should work.
