### ISSUE TITLE
Page refers to images that aren't visible

### ISSUE THREAD

**Issue by travisricks** [mdn/content#18934]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial

### What specific section or headline is this issue about?

Canvas tutorial - introduction

### What information was incorrect, unhelpful, or incomplete?

> The images on this page show examples of <canvas> implementations which will be created in this tutorial.

### What did you expect to see?

There don't seem to be any images on this page. Should there be a link to another page?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvas_api/tutorial`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/index.md
* Last commit: https://github.com/mdn/content/commit/59afa339ba0c732647864a02e589b50f33adec94
* Document last modified: 2022-06-16T22:42:27.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #18962 with a change that drops the entire sentence.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
