### ISSUE TITLE
correction: `disabled` does not remove DOM nodes from the a11y tree

### ISSUE THREAD

**Issue by ckundo** [mdn/content#18943]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

the article states the `disabled` attribute removes the node from the accessibility tree when it does not. discouraging people to use native attributes with incorrect information damages trust and leads to poor technical choices.

### What did you expect to see?

omit the caveats about `disabled` removing the node from the accessibility tree.

### Do you have any supporting links, references, or citations?

Inspect the accessibility tree in this example, its very clear that the disabled field is still present. https://codepen.io/aardrian/pen/bGvYQYK
<img width="550" alt="Screen Shot 2022-07-29 at 12 39 39 PM" src="https://user-images.githubusercontent.com/108163/181805308-15ccbb5d-5e4f-4659-b152-0afb54226c54.png">

**Comment by scottaohara** [comment]
FYI: i'm in the process of revising this article to help mitigate misunderstandings like these, among other elaborations/revisions to the page.
