### ISSUE TITLE
Missing distinction between a class and a component in Angular

### ISSUE THREAD

**Issue by slim-codes** [mdn/content#18949]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_getting_started

### What specific section or headline is this issue about?

The class under The structure of an Angular application

### What information was incorrect, unhelpful, or incomplete?

I find the **class** subsection under [The structure of an Angular application](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_getting_started#the_structure_of_an_angular_application) to be confusing. The author  has defined what a component and a class is satisfactorily. However, in the description below:
"A typical component is as follows:"
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-item',
    // the following metadata specifies the location of the other parts of the component
  templateUrl: './item.component.html',
  styleUrls: ['./item.component.css']
})

export class ItemComponent {
// your code goes here
}
```
After this code block, the author then proceeds to say "This component is called `ItemComponent`, and its selector is app-item..." If the component's name is `ItemComponent`, does it mean that the class and the component are one and the same?? If they are then this should have been explicitly implied instead of letting the reader ponder and go around the web looking for clarifications. I pose this question because the class name is obviously `ItemComponent` too. This is where my confusion stems from.

### What did you expect to see?

The relationship between a component and a class should have been explicitly stated after _"This component is called ItemComponent"_ statement to avoid confusing the reader.
This is pertinent because it immediately lets the reader know that a component and a class are essentially the same thing.

- Explicitly state that: At the very simplest, a **component** is nothing but a class that encapsulates behavior (what data to load, what data to render, and how to respond to user interactions) and a template (how the data is rendered). Simply put, a **component** is a class augmented by a template, a CSS style and a selector. How is the class augmented? It's augmented by declaring the  `@Component `decorator immediately before the class.

- Hence, the component and the class have the same names because of the definition of a **component** above which says a **component** is a **class**.

### Do you have any supporting links, references, or citations?

[https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_getting_started#the_class](url)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/angular_getting_started/index.md
* Last commit: https://github.com/mdn/content/commit/e9dc850b0141f0e79be8349717a0299824fb8f04
* Document last modified: 2022-07-18T01:55:22.000Z

</details>

**Comment by sideshowbarker** [comment]
Fixed in https://github.com/mdn/content/pull/18992
