### ISSUE TITLE
Empty embedded live samples

### ISSUE THREAD

**Issue by de-oz** [mdn/content#18971]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList

### What information was incorrect, unhelpful, or incomplete?

DOMTokenList API page has empty space under the "The output looks like this:" statement. The same issue is present on many other pages of different methods of this API (some of which are linked below).

### What did you expect to see?

There either should be an attached image that displays the code's output on the page or the statement should be removed. Please, let me know if I can help resolving this issue.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/add
https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/remove
https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle

### Do you have anything more you want to share?

Main DOMTokenList page:
![image](https://user-images.githubusercontent.com/101826623/181939233-f16ea65a-f591-4ecb-bc72-c6eed37831ce.png)

Toggle method page:
![image](https://user-images.githubusercontent.com/101826623/181939760-6d57146c-ad0e-47c3-b704-a918fe2d0e25.png)

**Comment by sideshowbarker** [comment]
> DOMTokenList API page has empty space under the "The output looks like this:" statement. The same issue is present on many other pages of different methods of this API (some of which are linked below).

I can’t reproduce the problem described. Instead, I see output there as expected:

![image](https://user-images.githubusercontent.com/194984/182004246-02534502-c521-48bd-8fb4-c48af3965c00.png)

I tested in Safari, Chrome, and Firefox, and in all of them the output is shown as expected.

Which browsers have you tested in, and is the output missing in all browsers you’ve tried?

When you open browser devtools and look at the console, what error messages do you see there?

> [developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/add](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/add)
> [developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/remove](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/remove)
> [developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle)

I see output as expected in all those pages too.

**Comment by teoli2003** [comment]
This also looks good for me. Maybe you have some extension interfering? These examples are in `<iframe>` elements.

**Comment by de-oz** [comment]
You're right and I'm sorry, indeed it was an extension that caused this problem for me. I should've thought about this.
