### ISSUE TITLE
Confusion about "Test your skills" section

### ISSUE THREAD

**Issue by Overlandcoder** [mdn/content#18972]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling
https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes

The "Test your skills" section for both of these lessons/docs is the exact same. I'm not sure if this is intentional or not.

I don't think the second test for the "Test your skills" section of the "Advanced form styling" lesson/doc was relevant to what was covered/taught. While doing the test, I felt as if I was completely unaware of how to pass that test. And I realized later that it's the "UI pseudo-classes" lesson/doc that has the info required to pass the second test.

### What did you expect to see?

I expected to be able to pass the second test of "Advanced Form Styling", but that lesson/doc doesn't seem to have covered the info required to pass it. Sorry if I'm missing something!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/ui_pseudo-classes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/ui_pseudo-classes/index.md
* Last commit: https://github.com/mdn/content/commit/84e27d238a5e2228a4ebdd022ccac45c3614b8fc
* Document last modified: 2022-05-11T04:57:38.000Z

</details>

**Comment by wbamberg** [comment]
I think this is intentional:

> Bear in mind that some questions in this assessment series assume knowledge of the [next article](https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes) too, so you might want to work through that article first before attempting it.

But I agree that it's not very helpful to give people a test for something we haven't taught yet. We should probably remove that first link.
