### ISSUE TITLE
Same image, different resolution demo page missing other image file sizes

### ISSUE THREAD

**Issue by dodo-the-dev** [mdn/content#18970]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_same_size_different_resolutions

### What information was incorrect, unhelpful, or incomplete?

In the section about resolution switching: same image, different resolutions, the demo page only has one size image in the page, so no matter what size you make the page (physically or using dev tools using the device size option) the picture remains exactly the same. Although the code is calling to different size images, they're not there.

### What did you expect to see?

An image that would grow with the size of the screen. But there's only one image in the source, so it's misleading.

### Do you have any supporting links, references, or citations?

https://mdn.github.io/learning-area/html/multimedia-and-embedding/responsive-images/srcset-resolutions.html

### Do you have anything more you want to share?

none

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.md
* Last commit: https://github.com/mdn/content/commit/d7ae734be1ec44b9f160a54dae9a17abfa01e01e
* Document last modified: 2022-07-10T06:38:27.000Z

</details>

**Comment by najmiehsa** [comment]
I take this issue ^^

**Comment by najmiehsa** [comment]
@dodo-the-dev Have you checked this https://mdn.github.io/learning-area/html/multimedia-and-embedding/responsive-images/responsive.html ? because this image has two different sizes:

` <picture>
          <source media="(max-width: 799px)" srcset="elva-480w-close-portrait.jpg">
          <source media="(min-width: 800px)" srcset="elva-800w.jpg">
          <img src="elva-800w.jpg" alt="Chris standing up holding his daughter Elva">
        </picture>`

 and if you change the browser size you'd see the effect. 

- Is this the exact part you are mentioning in the issue?

**Comment by sideshowbarker** [comment]
@najmiehsa Given the lack of response, are you still planning to proceed with this? If not, we should close it

**Comment by najmiehsa** [comment]
@sideshowbarker Yes, Close it.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/18970#issuecomment-1305633924
