### ISSUE TITLE
Incorrect Hyperlink to a section on a page

### ISSUE THREAD

**Issue by shubham-y** [mdn/content#18986]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#value

### What information was incorrect, unhelpful, or incomplete?

The [hyperlink ](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats#format_of_a_valid_date_string) for `Format of a valid date string` text does not direct it to any section on its [page](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats).

### What did you expect to see?

Expected to see a section named `Format of a valid date string` on [Date and time formats used in HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats) page.

**Comment by WhiteN9** [comment]
Hello, I would like to attempt this one!

**Comment by hamishwillee** [comment]
Sure @WhiteN9 - thanks!

**Comment by WhiteN9** [comment]
I've opened [19033](https://github.com/mdn/content/pull/19003) with a change to the hyperlink. Please take a look and let me know if it is fine. 
Also, if you don't mind, can you guide me a bit on how to run this locally? I tried to follow the readme up to `local preview service is available at http://localhost:5042/` but after I ran `yarn start`, I got `Folder contains whitespace which is not allowed.` when trying to navigate.
