### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by FuNNyGuYz69** [mdn/content#18993]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Other

**Comment by hamishwillee** [comment]
Please don't create sandbox issues on this repository. This wastes time for the review team
