### ISSUE TITLE
Issue with "HTML attribute reference": Link from "async" is dead

### ISSUE THREAD

**Issue by benkasminbullock** [mdn/content#1899]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

#### What information was incorrect, unhelpful, or incomplete?

The link from async was dead

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#attribute_list

#### What did you expect to see?

Information on the async attribute

#### Did you test this? If so, how?

Not other than viewing in the browser.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/html/attributes/index.html
* Last commit: https://github.com/mdn/content/commit/bae04313dc3e19e4a5df529b97d5548c91f39b1f
* Document last modified: 2020-12-30T11:54:07.000Z

</details>

**Comment by benkasminbullock** [comment]
Similar problem with the link on "defer", which takes me here:

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/defer

**Comment by Aayushap1** [comment]
@benkasminbullock , I want to work on this issue please assign it to me

**Comment by Ryuno-Ki** [comment]
@rachelandrew Would you be okay with that, given that you use #1712 to track those missing attributes?

**Comment by benkasminbullock** [comment]
> @benkasminbullock , I want to work on this issue please assign it to me

I don't know how to do that. Since I'm not the repository owner I might not be able to assign people.

**Comment by rachelandrew** [comment]
I would suggest leaving a comment on #1712 then I know not to do that one.

**Comment by Ryuno-Ki** [comment]
@Aayushap1 Take it away!
I'm going to leave a comment in #1712.

**Comment by Aayushap1** [comment]
sir,  please tell me me link which I have to add in "asyn" and "defer".

**Comment by Aayushap1** [comment]
@Ryuno-Ki  I fixed this issue and sent pull request please review and merge .

**Comment by Ryuno-Ki** [comment]
As mentioned in the other ticket, #1943 will be reviewed by Rachel.

**Comment by himanshugarg** [comment]
The links [async](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-async) and [defer](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer) are both alive and well. Is there more to this issue?

**Comment by Ryuno-Ki** [comment]
This got fixed with https://github.com/mdn/content/commit/b85b55d0077333ae05f6e7c2ce1ca09566ddc588 in #3166. Closing.

**Comment by Ryuno-Ki** [comment]
@himanshugarg Thank you for pointing out that we had a dangling issue on this.
