### ISSUE TITLE
Error: array1.findLast is not a function

### ISSUE THREAD

**Issue by ixcw** [mdn/content#19005]
In the JavaScript document, the findLast function of the array, when run the example test, console printed the error message: 
`Error: array1.findLast is not a function`
Please fix this issue.

**Comment by Josh-Cena** [comment]
Please check your browser version. According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLast#browser_compatibility, it's only supported in recent versions of modern browsers.

**Comment by teoli2003** [comment]
![Capture d’écran 2022-08-01 à 07 26 20](https://user-images.githubusercontent.com/1466293/182078074-53dd5bf5-c02f-4273-92a7-6b4ffbc0e711.png)

**Comment by zloirock** [comment]
@teoli2003 
- Node.js: 18.0
- Opera Android: 68
- Samsung Internet: 18.0

**Comment by teoli2003** [comment]
@zloirock Can you open an issue in mdn/browser-compat-data ? Thanks!

**Comment by zloirock** [comment]
@teoli2003 I regularly see the problem with compat data mirroring, so I think that makes no sense to open an issue only about it. I think that it should be fixed fundamentally and you know better than me where it can be fixed.

**Comment by teoli2003** [comment]
cc/ @queengooborg

**Comment by zloirock** [comment]
For example, how it works in `core-js`: it has similar data about used engine versions. On building compact data, it's copied from the base engine if it's not set directly and follows some condition - for example, for Chrome -> NodeJS it's ECMAScript only.

**Comment by ixcw** [comment]
thanks guys, I don't have this issue with chrome browser. it should be a browser compatibility issue, but i do hope you guys can fix it with all the different browser editions, I guess the test code is running on the local browser, is this right?  so i think maybe you guys can build a cloud server to run the code? of course, it's just my little advise, if it costs too much or it's difficult to implement, then just forget about it.

**Comment by hamishwillee** [comment]
@teoli2003 I don't understand the problem.
- The docs are correct. 
- The BCD is correct. It works on the versions that it says it work on. 
- The interactive example does fail on FF, exactly as you would expect based on the BCD.

So this is all the MDN "standard". Yes we could make the interactive example check for support, but that would be pretty messy, and unnecessary IMO.

**Comment by teoli2003** [comment]
Yes, there is no problem with the page. The only potential problem (and I don't know if it is the case) is that it could, eventually, work on Samsung Internet, Node.js, and Opera Android, which is what Denis is saying. (And why I copied Vinyl). The BCD may be incomplete.

But there is no problem with the page itself: it is a new feature, the example will work only on browsers where the feature is implemented.

**Comment by teoli2003** [comment]
> thanks guys, I don't have this issue with chrome browser. it should be a browser compatibility issue, but i do hope you guys can fix it with all the different browser editions, I guess the test code is running on the local browser, is this right? so i think maybe you guys can build a cloud server to run the code? of course, it's just my little advise, if it costs too much or it's difficult to implement, then just forget about it.

We don't plan to build a cloud server to run the code, the goal is for the reader to have an easy way to verify if a feature work on a specific browser.
