### ISSUE TITLE
Issue with "max()": Supported on Opera and Firefox for Android

### ISSUE THREAD

**Issue by joezimdelta** [mdn/content#1901]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/max()

#### What information was incorrect, unhelpful, or incomplete?

The compatibility list says that `max()`, `min()`, and `clamp()` are not supported on Firefox and Opera for Android, but I just tested them and they all worked on both browsers on my Android phone.

#### Specific section or headline?
Compatibility list

#### Did you test this? If so, how?
I opened [this code pen](https://codepen.io/paigen11/pen/ExgGGMW) in both browsers on my phone and fiddled with the numbers inside those functions and saw the boxes resize appropriately.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/max()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/max()
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/max()/index.html
* Last commit: https://github.com/mdn/content/commit/2c1356a45232b3800fd7401acc057b1385935d92
* Document last modified: 2021-01-21T05:04:33.000Z

</details>

**Comment by rachelandrew** [comment]
This has been updated, thanks for the report @joezimdelta !
