### ISSUE TITLE
Issue with "400 Bad Request": (short summary here please)

### ISSUE THREAD

**Issue by wealthyamagre** [mdn/content#1907]
I am priscilla Akpevwe Amagre, i applied for a loan and text message was sent to me via inbox, i was ask to put my BVN, when i put it, it was showing the BVN dose not exist,is about a week now . sir i really need your assistance so if you can resend me the message again so that i can get the loan.Thanks sir. MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status/400`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/status/400/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Seems unrelated to MDN web docs. I'm going ahead and close it as invalid.
