### ISSUE TITLE
Confusing description of Worker message event

### ISSUE THREAD

**Issue by briancodes** [mdn/content#19071]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Worker/message_event

### What specific section or headline is this issue about?

Top level description

### What information was incorrect, unhelpful, or incomplete?

> The message event is fired on a Worker object when the worker's parent receives a message from its worker

### What did you expect to see?

A clearer description of the event

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/worker/message_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Worker/message_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/worker/message_event/index.md
* Last commit: https://github.com/mdn/content/commit/840db6342cecc2bd24cadf780ba7678ddcc25b1f
* Document last modified: 2022-07-23T16:30:18.000Z

</details>

**Comment by Chaitanya7666** [comment]
Hey @sideshowbarker , Could you please tell me that with `help wanted` tag, are you asking the creator of the issue to elaborate more on the issue or does it mean that you are looking for someone to work on the issue? If it means the later, I would like to take it up.

**Comment by Chaitanya7666** [comment]
Hey @sideshowbarker , Could you please tell me that with `help wanted` tag, are you asking the creator of the issue to elaborate more on the issue or does it mean that you are looking for someone to work on the issue? If it means the later, I would like to take it up.

**Comment by briancodes** [comment]
Would it be an idea to have a standardized way of describing events - maybe using the terms like trigger, [dispatch](https://dom.spec.whatwg.org/#dispatching-events) and [listen](https://dom.spec.whatwg.org/#concept-event-listener)

For example with [mouseup](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseup_event) it says the `event is fired at an Element`

> The mouseup event is fired at an Element when a button on a pointing device (such as a mouse or trackpad) is released while the pointer is located inside it

**Comment by sideshowbarker** [comment]
> Could you please tell me that with `help wanted` tag, are you asking the creator of the issue to elaborate more on the issue or does it mean that you are looking for someone to work on the issue?

It means we are looking for someone to work on the issue

**Comment by Chaitanya7666** [comment]
@briancodes, you have linked to [mouseup](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseup_event) & [Worker: message event](https://developer.mozilla.org/en-US/docs/Web/API/Worker/message_event). I see in the _top heading_ of both these events—we have used `fired` to describe the `firing up` of an event.

> The different terms used for very similar concepts can be confusing. For example with [mouseup](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseup_event) it says the event is fired at an Element

Could you please tell me what do you mean by **different terms** as I see that `firing` is the term used—in the top heading of all event docs? 

> Would it be an idea to have a standardized way of describing events - maybe using the terms like trigger, [dispatch](https://dom.spec.whatwg.org/#dispatching-events) and [listen](https://dom.spec.whatwg.org/#concept-event-listener)

Do you mean that we need to change all the occurrences of `fired` to `triggered` and `fires` to `triggers` across all of the `event top heading's`?

**Comment by briancodes** [comment]
@Chaitanya7666 You're right about the `fired` and `firing` terms - they're pretty consistent throughout the site

I guess it was more the _"fired on an object"_ vs _"fired at an element"_, but it's probably fine as is

**Comment by Chaitanya7666** [comment]
> @Chaitanya7666 You're right about the `fired` and `firing` terms - they're pretty consistent throughout the site
> 
> I guess it was more the _"fired on an object"_ vs _"fired at an element"_, but it's probably fine as is

@sideshowbarker Requesting your thoughts on this. Could you please give me any suggestions on how to take this issue further?

**Comment by sideshowbarker** [comment]
> @sideshowbarker Requesting your thoughts on this. Could you please give me any suggestions on how to take this issue further?

I don’t really have any specific thoughts on this, and no particular suggestions to give. Part of the work of resolving an issue — maybe the main work involved — is evaluating the issue on one’s own and making decisions about how to proceed.

**Comment by Chaitanya7666** [comment]
> I guess it was more the "fired on an object" vs "fired at an element", but it's probably fine as is

@briancodes I get what you are saying. Let me read about `Workers` once—to see if it's non-intuitive for people to understand the _difference between the statements that you have mentioned_ before I jump to a conclusion.

**Comment by Chaitanya7666** [comment]
@sideshowbarker, I think that the current description is good and it doesn't look like it needs more improvements and so I think that it can be closed.

**Comment by sideshowbarker** [comment]
> @sideshowbarker, I think that the current description is **good** and I don't see any further improvements that could be done to it and so I think that this issue can be **closed**.

@briancodes What do you think?

**Comment by Josh-Cena** [comment]
Closing because everyone seems to think this is fine as-is.
