### ISSUE TITLE
Issue with "Mobile first": (short summary here please)

### ISSUE THREAD

**Issue by jmejiaxdev** [mdn/content#1908]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Responsive/Mobile_first

#### What information was incorrect, unhelpful, or incomplete?
The URL [Planning your App](https://developer.mozilla.org/en-US/docs/Web/Apps/Planning_your_app) is broken

#### Specific section or headline?
First paragraph

#### What did you expect to see?
Planning your App content

#### Did you test this? If so, how?
On click

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/progressive_web_apps/responsive/mobile_first`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Responsive/Mobile_first
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/progressive_web_apps/responsive/mobile_first/index.html
* Last commit: https://github.com/mdn/content/commit/95f8537ff8f89f6cacfb3ea463725ad28d41c7f8
* Document last modified: 2020-12-29T12:15:43.000Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this, @jmejiaxdev 

The "Planning your app" article is really out of date, so I've removed the link, and rewritten the intro paragraph so that the article stands on its own. See https://github.com/mdn/content/commit/376e53cd094a3a72634f9911ccb562c15fb059ba for the update.
