### ISSUE TITLE
Issue with "version": Broken link

### ISSUE THREAD

**Issue by jamespfluger** [mdn/content#1909]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version

#### What information was incorrect, unhelpful, or incomplete?
The link for "Version format" is broken and leads to a "Page not found error"
![image](https://user-images.githubusercontent.com/16975008/106372560-a3eba000-6325-11eb-97c6-e0aeea0854ba.png)

#### Specific section or headline?
Beneath the first table with the fields "Title/Mandatory/Example" there is a link labeled "Version format"
![image](https://user-images.githubusercontent.com/16975008/106372536-77d01f00-6325-11eb-80a8-ff3d59f11220.png)

#### What did you expect to see?
A page describing the Version format information.

#### Did you test this? If so, how?
Yes, I clicked on the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/version`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/add-ons/webextensions/manifest.json/version/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by jamespfluger** [comment]
I believe the link *should* point to either this URL or another updated one, of which I have not yet found
https://developer.mozilla.org/en-US/docs/Mozilla/Toolkit_version_format

The source of the broken link appears to be in this file at, currently, line 31:
https://github.com/mdn/content/blob/2d423bd1a98b85b8584f08990792ebf39fcea56b/files/en-us/mozilla/add-ons/webextensions/manifest.json/version/index.html#L31

**Comment by Aayushap1** [comment]
i want to work on this issue please assign it to me

**Comment by Ryuno-Ki** [comment]
Could someone from @mdn/yari-content-mozilla-add-ons help out with determining the correct target here first?

**Comment by chrisdavidmills** [comment]
@jamespfluger was correct with his above assertion; the link should point to https://developer.mozilla.org/en-US/docs/Mozilla/Toolkit_version_format.

**Comment by rpl** [comment]
I do also confirm that at the moment we don't have a better page ("better" as in "not archived") to point that link to, and so I think it would be good to update the existing link url to point to https://developer.mozilla.org/en-US/docs/Mozilla/Toolkit_version_format for now.

@jamespfluger Feel free to go ahead and submit the PR to update the url (don't worry if you can, let us know and we will take care of making that change).

**Comment by rpl** [comment]
@caitmuenster I'm thinking that it may be reasonable to also open a separate follow up for this issue, one aiming to create a short WebExtensions mdn doc page to describe the Extension Manifest version format (and maybe in that page link the archived Toolkit version format page, provided mainly for completeness and access to the historical content available in the archived page) or to describe the version format as part of the [manifest.json/version doc page itself](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version), what do you think?

**Comment by caitmuenster** [comment]
@rpl Yes, let's open a new issue for that! Let me dig up the archived page for https://developer.mozilla.org/en-US/docs/Toolkit_version_format and see what we're dealing with.

**Comment by jamespfluger** [comment]
I have a pull request draft (#2065), but if @caitmuenster has a better, long-term fix almost ready for #1959 then that would be a better solution than the draft I have

**Comment by rpl** [comment]
> I have a pull request draft (#2065), but if @caitmuenster has a better, long-term fix almost ready for #1959 then that would be a better solution than the draft I have

I'm fine with both solutions, I'm going to leave to @caitmuenster the final choice.

**Comment by caitmuenster** [comment]
This has been closed in #2268. :)
