### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Lordishh** [mdn/content#1910]
Hi. I have read all about some methods and have come to notice that in the replace method, in the examples part with "global" and "ignore", they use the following syntax:

![asd](https://user-images.githubusercontent.com/70355763/106374567-365e6480-6363-11eb-9dfb-8a480fa158e7.png)

However, this way the flags are not working for me. Quite the opposite if I change "gi" to "ig".

**Comment by Ryuno-Ki** [comment]
Hi @Lordishh,

would you mind to share the page you found the code snippet on?

**Comment by Lordishh** [comment]
This si the page:
https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/String/replace

**Comment by Ryuno-Ki** [comment]
¡Gracias!

Be aware, that non-English pages aren't updated for the time being:
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/

That being said, the English version shows the same code snippet:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#using_global_and_ignore_with_replace

The respective source code can be found here:

https://github.com/mdn/content/blob/d54141e8f5fac3effe8ed12fcde9369617e655ba/files/en-us/web/javascript/reference/global_objects/string/replace/index.html#L202-L216

Would you be willing to check the English code and propose an update as PR?

**Comment by Lordishh** [comment]
I would be delighted, but Github is not used very well

**Comment by Ryuno-Ki** [comment]
Give it a try!

You can either 
1) fork the repo, check out the code locally, make the changes and push it. Then open a PR or
2) do the edits from the GitHub Web UI.

We're here to help if you need assistance :-)

**Comment by Lordishh** [comment]
Okay, I'll try.

**Comment by sideshowbarker** [comment]
Closing, given that #2175 is now closed
