### ISSUE TITLE
Radiogroup role: Incorrect opening tag in the semantic example

### ISSUE THREAD

**Issue by Guignome01** [mdn/content#19118]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/roles/radiogroup_role

### What specific section or headline is this issue about?

Line 15 of the second code block in the semantic example

### What information was incorrect, unhelpful, or incomplete?

The opening tag is an `<li>` HTML element  while the closing tag is `<p>`.

![](https://user-images.githubusercontent.com/35086388/182666943-8b29c314-dadb-458a-9447-eef45ee6fe49.png)

### What did you expect to see?

The HTML element should start with `<p>` to match with the closing tag.

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened #19126 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
