### ISSUE TITLE
Typo Javascript vs JavaScript

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#1912]
On https://developer.mozilla.org/en-us/docs/Web/HTML/Global_attributes/tabindex the explanation for `tabindex="-1"` shows `Javascript` instead of the correct spelling of `JavaScript`.

Thus the following line needs an update:

https://github.com/mdn/content/blob/d54141e8f5fac3effe8ed12fcde9369617e655ba/files/en-us/web/html/global_attributes/tabindex/index.html#L23

**Comment by AnandBIT** [comment]
I would like to work on this issue

**Comment by Ryuno-Ki** [comment]
Sounds great!
I assigned the ticket to you.

Looking forward to a PR :-)

**Comment by AnandBIT** [comment]
Fixed the typo, please check @Ryuno-Ki

**Comment by Ryuno-Ki** [comment]
Thanks!
Since this is a change to the HTML part of MDN web docs, someone from the @yari-content-html will need to review it. (The members are listed in [REVIEWING.md](https://github.com/mdn/content/blob/main/REVIEWING.md#topic-review-owners)

**Comment by rachelandrew** [comment]
Thanks!
