### ISSUE TITLE
Is there an error in  ’... ({ a, b } = { a: 1, b: 2 }) is valid, as is const { a, b } = { a: 1, b: 2 }.‘ ?

### ISSUE THREAD

**Issue by keduhoutian** [mdn/content#19144]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

### What specific section or headline is this issue about?

Binding and assignment => Note

### What information was incorrect, unhelpful, or incomplete?

{ a, b } = { a: 1, b: 2 } is not valid stand-alone syntax, as the {a, b} on the left-hand side is considered a block and not an object literal. However, ({ a, b } = { a: 1, b: 2 }) is valid, **as is const { a, b } = { a: 1, b: 2 }.**
![x](https://user-images.githubusercontent.com/80935875/182808228-dd3c1723-656f-47c8-b8c4-ae73199fc398.jpg)

### What did you expect to see?

**should be 'let'**

I think this 'const { a, b } = { a: 1, b: 2 }' should be a little wrong.
Because the value of variable A or B can be changed.
So the declaration should be **'let'**, not  'const'

for example:
({ a, b } = { a: 1, b: 2 })
a = 10;    // => it can be executed, so should be 'let'.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/destructuring_assignment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/destructuring_assignment/index.md
* Last commit: https://github.com/mdn/content/commit/43ebaea79eba633d9e2bff03b0a05232037704cf
* Document last modified: 2022-07-19T04:32:05.000Z

</details>

**Comment by Josh-Cena** [comment]
We are talking about the _syntax_ here, not what happens afterwards. We are saying that if you want to assign, you have to wrap it in brackets; but if you are declaring fresh variables, there's no need to add the parens, hence `const { a, b } = { a: 1, b : 2 }`. "As is" does not mean "which is the same as"; it means "similarly".
