### ISSUE TITLE
JavaScript design mistakes and weaknesses - Controversial features 

### ISSUE THREAD

**Issue by GHNewbiee** [mdn/content#19147]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript

### What specific section or headline is this issue about?

New section

### What information was incorrect, unhelpful, or incomplete?

Poor design decisions taken in the past have introduced a number of mistakes (logical or not) and weaknesses in the language.

A new section gathering and listing those ones would be pioneer (since I have never seen such a section in the documentation of any project) and help people to consider them in the development of their (similar) projects.

### What did you expect to see?

A new section which will list and explain logically proved mistakes in the design of the language and refer the reason why they cannot get corrected (eg backward compatibility, too late, etc) as well as controversial features with suggestions and comments.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/index.md
* Last commit: https://github.com/mdn/content/commit/e2386ae5b9fba169598aca067d46f30958afc7e0
* Document last modified: 2022-07-06T14:29:00.000Z

</details>

**Comment by hamishwillee** [comment]
Who is the audience? What would they _do_ with the information? 

My instinctive reaction is that this information might be interesting, but it would be of little use. Time could be better spent.

**Comment by Josh-Cena** [comment]
I agree the audience would be really niche and it would basically be one of the "depths of MDN" pages.

**Comment by teoli2003** [comment]
I have a "red alert" alarm blinking here:
- lots of the choices here will be controversial
- only niche people will find this article
- beginners and intermediate people will continue to use the problematic features anyway.

I see risks but no positive outcome for the developers.

I would prefer to have (good) alternative suggested on actual problematic patterns/features documented. Somebody wanted to use them will know they are problematic and will find an alternative. This would have a real positive impact on our readership: they will be warned if they seek information on a specific problematic feature (they likely saw it somewhere and want to know about it).

I would vote to close this issue.

**Comment by Josh-Cena** [comment]
Okay, maintainers seem to have a unanimous stance to close this ^^ 3/3, would close as wontfix. Thanks for your suggestion @GHNewbiee! If you want to summarize some of these, feel free to ask in ES discourse and I'm sure the tc39 delegates would have _strong_ opinions about what are mistakes.

**Comment by GHNewbiee** [comment]
- Maybe the most important thing for MDN folks is to avoid acting as ES/JS religious gate guards.
- Maybe other non-commercial projects adopt the culture of presenting their weaknesses, too.

@Josh-Cena
> How do we assess the "mistakeness" of a feature?

Whatever behaves/implement in an unnatural way, out of common sense, restrict the freedom to be used could be a candidate. Some general examples out of ES implementation:

- Unbound code blocks which are identified by indent/spaces is an "unnatural" way. If you see around you everything has a "hard" bound most of the time for safety or for convenience.
- At school in mathematics you learn that there are functions and in philology there are definitions which clarify the meaning of words. I do not remember definitions exist in mathematics and functions in philology.

> Do we need quotes from Brendan Eich?

We get quotes from all reliable sources.

> Quotes from tc39 delegates?

Ha, ha! The most faithful gate guards. ES "Taliban"! (just a joke!)

> An official deprecation warning in the spec?

@hamishwillee It seems that your background is something between philology and IT. What's your opinion?
> Who is the audience?
+ Anyone who wants to "learn" more about the tool (s)he makes of use or plans to start developing (similar) projects.

> What would they do with the information?
+ They will use to avoid similar mistakes.

> My instinctive reaction is that this information might be interesting, but it would be of little use.
+ This information is not for all who swallow whatever they are given to eat!

> Time could be better spent.
+ Maybe your time.

@teoli2003 It seems that your background is something between philology and IT, too.

@Josh-Cena 
> Okay...

谢谢你的时间。

**Comment by Josh-Cena** [comment]
To be fair, many observable inconsistencies in the language design signal tc39's opinion of "mistakes". For example, `Array.prototype.{find,group,includes}` et al. all visit empty slots in sparse arrays, because they think the ES5 behavior for `{map,forEach,indexOf}` et al. is "wrong". Similarly, new copying methods like `{toReversed,toSorted}` no longer consult `@@species`, because the committee doesn't like `@@species`. I really don't like both of the decisions, but they are there anyway.

**Comment by GHNewbiee** [comment]
@Josh-Cena I hope one day, someone who has the **knowledge** and **time** to start an ES **anti-mandate** documentation project which will include this kind of info **in a good will** and help people/organization who wants to start a new project to consider them. Also, to be a good example to other "great" projects which try to hide the poor choices made in the past.
再一次，谢谢您的时间。
