### ISSUE TITLE
Remove information about the event macro

### ISSUE THREAD

**Issue by MrBrain295** [mdn/content#19157]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Macros/Commonly_used_macros

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Macros/Commonly_used_macros#linking_to_pages_in_references

### What information was incorrect, unhelpful, or incomplete?

The event macro is depreciated.

### What did you expect to see?

No information about the event macro.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/writing_guidelines/page_structures/macros/commonly_used_macros`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Macros/Commonly_used_macros
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/writing_guidelines/page_structures/macros/commonly_used_macros/index.md
* Last commit: https://github.com/mdn/content/commit/1c5c86c721a5935e89065246d49506f1d4cf9567
* Document last modified: 2022-08-03T17:40:02.000Z

</details>

**Comment by Josh-Cena** [comment]
`{{InterWiki}}` needs to be removed as well.

**Comment by MrBrain295** [comment]
@Josh-Cena I would be happy to remove info about the Interwiki macro but I can’t find  any information about it.

**Comment by Josh-Cena** [comment]
Oh, apparently it's already removed in https://github.com/mdn/content/pull/18974. Sorry for the false alarm!
