### ISSUE TITLE
I love the people that work(ed) on the accessibility pages.

### ISSUE THREAD

**Issue by timsartoris** [mdn/content#19167]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility

### What specific section or headline is this issue about?

The Entire <main> content

### What information was incorrect, unhelpful, or incomplete?

Sorry to do this here but I really wanted to just thank the people responsible for providing all the GREAT content about accessibility on the MDN web pages.  I am fascinated by how well-written it is, and all the thorough and helpful examples of code.  Super duper impressive and I can't think you enough.

### What did you expect to see?

Something that wasn't very informative or helpful.

### Do you have anything more you want to share?

I love the people that work(ed) on the accessibility information.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/index.md
* Last commit: https://github.com/mdn/content/commit/1c5c86c721a5935e89065246d49506f1d4cf9567
* Document last modified: 2022-08-03T17:40:02.000Z

</details>

**Comment by teoli2003** [comment]
Thank you! I want to tag a few of these people (and I'm apologizing for the numerous people I forgot): @estelle @scottaohara @mdn/yari-content-accessibility, and many more over the years!

I will mark this issue as closed as it has been acted upon.

**Comment by estelle** [comment]
Thank you! Also want to tag @ericwbailey. He and @scottaohara did a wonderful job editing all the ARIA roles and attributes and have done so much to ensure the accessibility content is accurate.

**Comment by teoli2003** [comment]
_Mea maxima culpa_. I forgot the amazing Eric!
