### ISSUE TITLE
Issue with "<image>": missing crossorigin

### ISSUE THREAD

**Issue by edemaine** [mdn/content#1916]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image

#### What information was incorrect, unhelpful, or incomplete?

SVG 2 added support for the `crossorigin` attribute which isn't mentioned.  See https://svgwg.org/svg2-draft/embedded.html#ImageElementCrossoriginAttribute

#### Specific section or headline?

Specific attributes. Could also mention in SVG 2 Comments column (which already mentions change about width and height).

#### What did you expect to see?

`crossorigin` attribute should be defined/mentioned; SVG `crossorigin` attribute needs a page; probably link to [corresponding HTML `crossorigin` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/element/image`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/svg/element/image/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Thanks for bringing it to our attention.
Since I'm member of the [SVG topic owners](https://github.com/mdn/content/blob/main/REVIEWING.md#topic-review-owners) I'm assigning this to myself.

Will look into it over the course of the following days (booked with another private project for today already).

**Comment by Ryuno-Ki** [comment]
Meh, still haven't found time yet.

**Comment by Ryuno-Ki** [comment]
Finally came around to open https://github.com/mdn/content/pull/2547
