### ISSUE TITLE
Issue with "Date.prototype.toLocaleDateString()": (short summary here please)

### ISSUE THREAD

**Issue by jribbens** [mdn/content#1917]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

#### What information was incorrect, unhelpful, or incomplete?

The sample code `toLocaleDateStringSupportsLocales` does not work as described.

#### Specific section or headline?

Checking for support for locales and options arguments

#### What did you expect to see?

The function name `toLocaleDateStringSupportsLocales` implies that it returns `true` when `toLocaleDateString` supports locales, and `false` if it does not. In fact, it returns the opposite values.

#### Did you test this? If so, how?

By inspecting the code. And also by running the function in the latest Chrome, and node 12, both of which support the locales version of the method but return `false` for this function.

A corrected version of the function would look as follows:

```javascript
function toLocaleDateStringSupportsLocales() {
  try {
    new Date().toLocaleDateString('i');
  } catch (e) {
    return e.name === 'RangeError';
  }
  return false;
}
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/tolocaledatestring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/date/tolocaledatestring/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by sridhar02** [comment]
@chrisdavidmills I would like to work on this issue

**Comment by jribbens** [comment]
It occurred to me to check the page for `toLocaleString` - that page has an almost identical code sample, except it doesn't have the bug. It uses `e instanceof RangeError` rather than `e.name === 'RangeError'`.

The page for `toLocaleTimeString` has a code sample identical to my suggested fix above.

I don't know which is better out of `e.name === 'RangeError'` and `e instanceof RangeError` but I'd suggest that the code on all three pages should be consistent.

**Comment by chrisdavidmills** [comment]
Assigned; thanks for your interest @sridhar02, and let us know if you need any help.

**Comment by mohitdmak** [comment]
can I finish this up @chrisdavidmills

**Comment by chrisdavidmills** [comment]
The PR is assigned to someone else to review, and they will get to it as soon as they can find the time. Thanks for your contribution @mohitdmak .

**Comment by mohitdmak** [comment]
Oh, I am a newcomer actually and didn't know that it is automatically sent for review.
Thanks though.

**Comment by chrisdavidmills** [comment]
No worries at all. Yes, we do have a system to assign reviewers based on what docs area is being changed. If in doubt, check the reviewers list after you have created the PR.

**Comment by mohitdmak** [comment]
Hmm ya I can see that now 👍

**Comment by Ryuno-Ki** [comment]
…aaaand it's in! :confetti_ball: 

Thanks for your help, @mohitdmak!
