### ISSUE TITLE
Intersection Observer v2 delay and trackVisibility properties missing in Browser compatibility and are not described - plus no support in Firefox

### ISSUE THREAD

**Issue by BearCooder** [mdn/content#19201]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

### What specific section or headline is this issue about?

Intersection Observer API

### What information was incorrect, unhelpful, or incomplete?

The information about the two additional properties is missing: `delay` and `trackVisibility`. Looking through the documentation its not mentioned anywhere and not mentioned in the Browser compatibility table. **Chrome** does support it but **Firefox** does not.

_Intersection Observer v2 introduces the concept of tracking the actual "visibility" of a target element as a human being would define it. By setting an option in the [IntersectionObserver constructor](https://developer.mozilla.org/docs/Web/API/IntersectionObserver/IntersectionObserver), intersecting [IntersectionObserverEntry](https://developer.mozilla.org/docs/Web/API/IntersectionObserverEntry) instances will then contain a new boolean field named isVisible. A true value for isVisible is a strong guarantee from the underlying implementation that the target element is completely unoccluded by other content and has no visual effects applied that would alter or distort its display on screen. In contrast, a false value means that the implementation cannot make that guarantee._

_An important detail of the [spec](https://w3c.github.io/IntersectionObserver/v2/#calculate-visibility-algo) is that the implementation is permitted to report false negatives (that is, setting isVisible to false even when the target element is completely visible and unmodified). For performance or other reasons, browsers limit themselves to working with bounding boxes and rectilinear geometry; they don't try to achieve pixel-perfect results for modifications like border-radius._

_That said, false positives are not permitted under any circumstances (that is, setting isVisible to true when the target element is not completely visible and unmodified)._

_The IntersectionObserver constructor now takes two additional configuration properties: `delay` and `trackVisibility`. The `delay` is a number indicating the minimum delay in milliseconds between notifications from the observer for a given target. The `trackVisibility` is a boolean indicating whether the observer will track changes in a target's visibility._

This information is from the following [source](https://web.dev/intersectionobserver-v2/#what's-challenging-with-intersection-observer-v1)

### What did you expect to see?

I expect to see the properties mentioned and explained how they work with an example eventually. Like it always is on MDN. Plus to see it in the Browser compatibility table,

### Do you have any supporting links, references, or citations?

[Delay](https://w3c.github.io/IntersectionObserver/v2/#dom-intersectionobserver-delay)
[TrackVisibility](https://w3c.github.io/IntersectionObserver/v2/#dom-intersectionobserver-trackvisibility)
[isVisible](https://w3c.github.io/IntersectionObserver/v2/#visibility)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/intersection_observer_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/intersection_observer_api/index.md
* Last commit: https://github.com/mdn/content/commit/5bbd76c65594a71609ea28f6d5fe8ef7dd553c61
* Document last modified: 2022-07-23T11:23:29.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! We now have a centralized place to track missing documentation: https://openwebdocs.github.io/web-docs-backlog/all/ since it's currently only supported by Chrome, it's not being priotized. In any case, we are closing all missing documentation issues in favor of this central backlog.
