### ISSUE TITLE
The linked website from https://mozilla.github.io/ shows a 404

### ISSUE THREAD

**Issue by BearCooder** [mdn/content#19202]
### MDN URL

https://mozilla.github.io/webdev

### What information was incorrect, unhelpful, or incomplete?

When I click on Web development it forwards me to a dead page with a 404 error.
From https://mozilla.github.io/ to https://mozilla.github.io/webdev

![grafik](https://user-images.githubusercontent.com/104575503/183159160-5e2df5c1-ee7f-4706-8df6-8b55e7164581.png)

### What did you expect to see?

A working link

**Comment by cw118** [comment]
FWIW it looks like this is an issue for the [`mozilla/webdev` repo](https://github.com/mozilla/webdev) which is archived (thus the GitHub Pages site does not "exist" anymore), and not here (MDN). This was also reported on the [`mozilla.github.io` repo](https://github.com/mozilla/mozilla.github.io) here: https://github.com/mozilla/mozilla.github.io/issues/22

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/19202#issuecomment-1206859295
