### ISSUE TITLE
from_address_bar qualifier is supported on firefox, but that's not indicated in the doc

### ISSUE THREAD

**Issue by sashoism** [mdn/content#19203]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/TransitionQualifier

### What specific section or headline is this issue about?

Transition qualifiers

### What information was incorrect, unhelpful, or incomplete?

the `from_address_bar` qualifier is in fact supported on Firefox 102 or possibly earlier

### What did you expect to see?

The lowest version of Firefox that supports it, at least 102

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/webnavigation/transitionqualifier`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/TransitionQualifier
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/webnavigation/transitionqualifier/index.md
* Last commit: https://github.com/mdn/content/commit/0df41fd3125fba4a65e3900e0a6effb7072144c9
* Document last modified: 2022-06-28T05:17:50.000Z

</details>

**Comment by Isaac108** [comment]
I'll be on it.

**Comment by rebloor** [comment]
Support details updated in https://github.com/mdn/browser-compat-data/pull/17752
