### ISSUE TITLE
Privacy: Page title and location of document misleading. 

### ISSUE THREAD

**Issue by estelle** [mdn/content#19208]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Privacy/Tracking_Protection

### What specific section or headline is this issue about?

Topic is browser specific

### What information was incorrect, unhelpful, or incomplete?

Title and location of document indicate that this page should be about privacy in general, but it is firefox specific. It should be in FF docs, not privacy docs.

### What did you expect to see?

It should be in FF docs, not privacy docs.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/privacy/tracking_protection`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Privacy/Tracking_Protection
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/privacy/tracking_protection/index.md
* Last commit: https://github.com/mdn/content/commit/d4b12e290fce9ae43a9ae23b9b9c8a5812b82ebd
* Document last modified: 2022-07-16T06:12:06.000Z

</details>

**Comment by estelle** [comment]
I did not change the link to the doc on https://developer.mozilla.org/en-US/docs/Web/Privacy#new_privacy_technology should read "Firefox tracking protection" because I think the content and location should be changed, and there should be a doc on tracking protection in general.

**Comment by iSatVeerSingh** [comment]
I am getting this error, please help me.
>yarn run v1.22.19
>$ env-cmd --silent cross-env CONTENT_ROOT=files yari-tool move files/en-us/web/privacy/tracking_protection files/en->us/web/privacy/firefox_tracking_protection

>error: document for files/en-us/web/privacy/tracking_protection does not exist

>error Command failed with exit code 1.
>info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by teoli2003** [comment]
What command do you run?

**Comment by iSatVeerSingh** [comment]
yarn content move files/en-us/web/privacy/tracking_protection files/en-us/web/privacy/firefox_tracking_protection

This command I run

**Comment by teoli2003** [comment]
You need to use the slug (with the right capitalization), something like:

`yarn content move Web/Privacy/Tracking_Protection Web/Privacy/Firefox_tracking_protection`

We use _sentence case_ so the second is the correct capitalization and the first one the current capitalization.

**Comment by iSatVeerSingh** [comment]
It worked. Thank you for guidance
