### ISSUE TITLE
Add "webrtc" CSP directive

### ISSUE THREAD

**Issue by Seirdy** [mdn/content#19218]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

### What specific section or headline is this issue about?

"Other directives"

### What information was incorrect, unhelpful, or incomplete?

The section does not list the new "webrtc" CSP directive.

### What did you expect to see?

Expected to see the "webrtc" directive, which takes a `'block'` or `'allow'` value.

### Do you have any supporting links, references, or citations?

Specification link: https://w3c.github.io/webappsec-csp/#directive-webrtc

### Do you have anything more you want to share?

Since WebRTC doesn't pass through Fetch, the directive is necessary. This might also need an entry on the BCD.

Firefox ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1783489

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/index.md
* Last commit: https://github.com/mdn/content/commit/31fb5716eac5f3ef6d7aa094c1a1d16a5e7e53bc
* Document last modified: 2022-07-21T08:12:11.000Z

</details>

**Comment by teoli2003** [comment]
Is this already implemented in a browser? If not, we should probably wait until one browser ships it (Firefox or another).

**Comment by sideshowbarker** [comment]
> Is this already implemented in a browser? If not, we should probably wait until one browser ships it (Firefox or another).

@jan-ivar, do you know if we have implementations of the `webrtc` CSP directive yet?

**Comment by Seirdy** [comment]
Like the documented `navigate-to`, this isn't yet implemented. Unlike `navigate-to`, this was a highly-demanded feature that closes a major hole in the CSP so there's a good chance that it'll get implemented.

**Comment by benatkin** [comment]
2 years later and it isn't implemented. There was some discussion of what to do about it here: https://github.com/w3c/webappsec-csp/issues/563

**Comment by bsmth** [comment]
Thanks for opening & for linking to the discussion. Shall we close this for now as not planned? We can reopen if there's movement on implementations.

**Comment by hamishwillee** [comment]
@benatkin Call be a cynic, but after two years, there is plenty of evidence it is not a priority for anyone. IMO we should close this until there is an implementation. There is no light to shine until that point, so this is just clutter.

**Comment by benatkin** [comment]
@hamishwillee this isn't just a feature, this is a fix for a security/privacy flaw. That's why it remains in the CSP spec and the Web Platform Tests, and IMHO should remain here.

**Comment by hamishwillee** [comment]
No, it's just another thing that may or may not be implemented some time in future. Clutter.

**Comment by benatkin** [comment]
@hamishwillee well, even if it gets deleted here and it gets deleted from Web Platform Tests, the reality of the situation will remain – it a glaring flaw in the browsers that a page that is as locked down as can be through a Content-Security-Policy can cause a query to be made to a DNS server – one in which a small amount of data could be exfiltrated (maybe more than a small amount if it can make repeated attempts to contact a bunch of ICE servers). It might be clutter from the perspective of this project, but to me it isn't clutter. I appreciate the thoughtful response. I have other ideas for bringing attention to this problem so I guess I don't mind if this issue gets closed.

**Comment by hamishwillee** [comment]
@benatkin Thank you - closing.

FWIW if the existence of this issue was in any way leverage on the implementers to implement the feature I would not be suggesting we close it. The existence in the WPT tests is a much better lever, and they should remain because they reflect the specification (MDN reflects the specification as implemented).
