### ISSUE TITLE
CSS Syntax not shown on Transition-duration t

### ISSUE THREAD

**Issue by 2bad2furious** [mdn/content#19225]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/transition-duration

### What specific section or headline is this issue about?

formal_syntax

### What information was incorrect, unhelpful, or incomplete?

Displays {{csssyntax}} instead of the desired css syntax.

### What did you expect to see?

Formatted formal syntax 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/transition-duration`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transition-duration
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/transition-duration/index.md
* Last commit: https://github.com/mdn/content/commit/899010f6aff5849b0a08292a3e26a56b4147c54a
* Document last modified: 2022-04-05T21:15:04.000Z

</details>

**Comment by wbamberg** [comment]
This looks like another instance of https://github.com/mdn/yari/issues/6779, and should be fixed when we update to the new version of CSSTree.

**Comment by wbamberg** [comment]
Fixed now, thanks for filing!
