### ISSUE TITLE
How can I contribute to translating the document?

### ISSUE THREAD

**Issue by makotoshimazu** [mdn/content#1926]
Hi, 
I've occasionally contributed to translation of the documents, and found that the process to edit the page has been changed under the Open Web Docs project.
I couldn't find the document describing how to contribute to translation (at least in neither of the README.md and https://developer.mozilla.org/). 
Can I ask how to do that, and is it possible to document it on README.md?

Thanks!

**Comment by Ryuno-Ki** [comment]
Hello @makotoshimazu,

thank you for your interest. Sadly, translations are frozen for now. See https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for the background.

I'm going to close this issue for now.

**Comment by makotoshimazu** [comment]
Thanks for the pointer to the article!
Now I understand it's in frozen state for now and the tier-1 locales are going to be unfrozen.
Do you have an idea of when it will be?

**Comment by chrisdavidmills** [comment]
@makotoshimazu We are hoping that it won't be too long; our engineers are working on it now.

**Comment by makotoshimazu** [comment]
Thanks a lot for your quick response. Great to hear that!
