### ISSUE TITLE
Incorrect information on 'DomContentLoaded_event' page

### ISSUE THREAD

**Issue by hochuldev** [mdn/content#19269]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event

### What specific section or headline is this issue about?

The first paragraph of the page.

### What information was incorrect, unhelpful, or incomplete?

The first paragraph of the page states that "The DOMContentLoaded event fires when the initial HTML document has been completely loaded and parsed, without waiting for stylesheets, images, and subframes to finish loading." I belive that this is partially incorrect. I have found out that preloading a large external stylesheet prevents a browser from firing DomContentLoaded event until the stylehsheet is parsed. I have tested this with Chrome browser. I will test this further with Firefox and update the issue.

### What did you expect to see?

 I am not certain if this is the only exception to the statement and thus not sure how to change the statement. However, there seems to be exceptions to the statement, and I belive that the exception as well as any other possibly known exceptions could be included in the document in order to avoid any potential confusion. The statement at least confused me.

### Do you have anything more you want to share?

Steps to reproduce the situation
1. create html file and preload a large external stylesheet. ex)<link rel="preload" href="some_really_long_css" as="style">
2. Link the stylesheet. ex) <link rel="stylesheet" href="some_really_long_css" >
3. Use vscode 'Live Server' extension to open the page
4. Use a developer tool to find out when the DomContentLoaded event fires.

I have attached a screenshot of the event firing 2 seconds after the browser is done with parsing the html. The part ,that is highlighted in yellow line, indicates that the event was fired at 2.06s. The parsing of the html was finished long before the parsing of the external stylesheet began. The screenshot includes some korean words. Sorry for the inconvenience.
![DomContentLoaded](https://user-images.githubusercontent.com/74853891/183335358-eaf62583-67fd-46cc-9232-5a47d202e905.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document/domcontentloaded_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/domcontentloaded_event/index.md
* Last commit: https://github.com/mdn/content/commit/159181b7c2bd49b78972353ba607fefa614eac93
* Document last modified: 2022-08-06T08:37:04.000Z

</details>

**Comment by Josh-Cena** [comment]
This is probably fixed in https://github.com/mdn/content/pull/19924. We will delete the `Window: DOMContentLoaded` page after https://github.com/mdn/content/issues/27197.

@hochuldev If https://github.com/mdn/content/pull/19924 does not answer your question, could you provide the exact steps used to reproduce the issue? FYI here's what I observed:

<img width="1081" alt="image" src="https://github.com/mdn/content/assets/55398995/0daef606-8ca9-4659-9c6b-77d1efe84ae9">

Note that DOMContentLoaded is already fired 200ms after the navigation, far before the stylesheet is even fetched.
