### ISSUE TITLE
Circular / dead link for contributor doc / how to write documentation

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/content#19273]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Issues

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/MDN/Community/Issues#make_progress_not_noise

### What information was incorrect, unhelpful, or incomplete?

Two links are actually empty: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/issues/index.md?plain=1#L63

### What did you expect to see?

Links to the corresponding pages

### Do you have anything more you want to share?

This page contains other "TBD/ToDo"-ish annotations.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community/issues`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community/Issues
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/issues/index.md
* Last commit: https://github.com/mdn/content/commit/52e0541d468a4db057d86b0542b52a34ff1d6aba
* Document last modified: 2022-08-06T02:41:20.000Z

</details>

**Comment by Abhiram-Gullapalli** [comment]
Is the issue resolved because I didn't observe any such behavior as stated, if yes please consider closing this issue to overlapping of work/confusion.

**Comment by SphinxKnight** [comment]
@Abhiram-Gullapalli this is still valid as of `main` now (4f14847593f9de215d3d90bf8e78844e4f2534e0) :
![image](https://user-images.githubusercontent.com/2413436/183580956-33674527-06bb-43a7-b328-d8cc060da7f0.png)

**Comment by Abhiram-Gullapalli** [comment]
Ooh! I'll just fix it right away
