### ISSUE TITLE
Font-stretch examples

### ISSUE THREAD

**Issue by muchafm** [mdn/content#19290]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch

### What specific section or headline is this issue about?

Font-face selection

### What information was incorrect, unhelpful, or incomplete?

The 62.5% font-stretch images example seems incorrect. Maybe we can use live code for this example ? As it was suggested by @estelle in this [pr comment](https://github.com/mdn/content/pull/19205#discussion_r939454942) 

### What did you expect to see?

Maybe live code examples 

### Do you have any supporting links, references, or citations?

[This comment made on a fix pr for the alt descriptions missing](https://github.com/mdn/content/pull/19205#discussion_r939454942)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-stretch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-stretch/index.md
* Last commit: https://github.com/mdn/content/commit/fc64e0c79a705571d7071858f8c3e0e7460e9967
* Document last modified: 2022-05-25T05:57:34.000Z

</details>

**Comment by estelle** [comment]
As all the browsers, with the exception of IE, support this feature, we can ditch the images and just render the example with CSS.
