### ISSUE TITLE
Inaccurate example for implicit type conversion

### ISSUE THREAD

**Issue by francis-ohara** [mdn/content#19293]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Type_Conversion

### What specific section or headline is this issue about?

Type Conversion

### What information was incorrect, unhelpful, or incomplete?

> For example, given the instruction 5+2.0, the floating point 2.0 is implicitly typecast into an integer.

The above example given for implicit type conversion is not accurate. The number 5 and 2.0 are both of type Number in JavaScript. Therefore, there is technically no conversion from one datatype to another datatype since both values are of the same data type. A different example that demonstrates implicit type conversion must therefore be used.

### What did you expect to see?

A more accurate example that demonstrates implicit type conversion must be used instead.

### Do you have any supporting links, references, or citations?

![image](https://user-images.githubusercontent.com/54600205/183485649-3ede44de-3118-4e0f-b2a5-8af0c82afe12.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/type_conversion`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Type_Conversion
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/type_conversion/index.md
* Last commit: https://github.com/mdn/content/commit/0ed71747051ea80a842c7b4dc16765cf97ad2122
* Document last modified: 2022-07-31T05:40:57.000Z

</details>

**Comment by Josh-Cena** [comment]
I think this is talking about C-family languages, not JavaScript. But let's find something more web-relevant.
