### ISSUE TITLE
Different image would improve understanding.

### ISSUE THREAD

**Issue by estelle** [mdn/content#19299]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout

### What specific section or headline is this issue about?

Grid tracks

### What information was incorrect, unhelpful, or incomplete?

1_grid_track.png is supposed to be a hilighted grid track. It doesn't look like anything. A better screen shot would help.

### What did you expect to see?

an image that better explains / displays what a grid track is.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_grid_layout/basic_concepts_of_grid_layout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
* Last commit: https://github.com/mdn/content/commit/b4cb1a7d369ab19319d0e20fc535fd140b9a8694
* Document last modified: 2022-06-18T06:26:01.000Z

</details>

**Comment by Chaitanya7666** [comment]
@estelle What do you think about this [image](https://css-tricks.com/wp-content/uploads/2021/08/terms-grid-track.svg). Isn't it clear?
