### ISSUE TITLE
Please do not use mySearch because is not mine but just the #search or #q

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#193]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

![Screenshot_20201214-213610.png](https://user-images.githubusercontent.com/44380480/102133305-322ec400-3e55-11eb-80bc-90d6b9cd3235.png)

**Comment by vkWeb** [comment]
@mattiapontonio we appreciate your feedback :)

But you see there's nothing wrong in giving them id & label as mySearch. Those are just simple examples. In your production applications you can use whatever suits the most to the purpose. 

So I'm closing this. I hope you understand.

**Comment by mattiapontonio** [comment]
I understand but I have to find a way to explain this because it seems to me a wasted effort. Let's imagine using that code and wanting to paste it into my production, I should change them. If I don't know what name to give sometimes I choose random strings but that kind of name seems to say "hey, I know what it is but I add some of my own" (which I often do too, mind you). 🙂
