### ISSUE TITLE
Suggestion: add issue and pull request template

### ISSUE THREAD

**Issue by ayoubmehd** [mdn/content#1933]
**It will make it easy for new contributors to have a template for pull requests and issues.**
Add issues and pull request template for suggestion bug report and so on...
https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by chrisdavidmills** [comment]
Yes, I totally agree with this. I've added it to our lists of todos for creating an effective content collaboration process.

Thank you @ayoubmehd !

**Comment by chrisdavidmills** [comment]
This got done, so closing!
