### ISSUE TITLE
Ensure no missing `alt` attributes

### ISSUE THREAD

**Issue by estelle** [mdn/content#19334]
### MDN URL

https://developer.mozilla.org/en-us/learn/css/css_layout/flexbox/

### What specific section or headline is this issue about?

All of MDN content

### What information was incorrect, unhelpful, or incomplete?

333 `alt` attributes are missing. 29 have alt attributes that are the image file name. Untold others have unhelpful alt attributes.

### What did you expect to see?

Every image in MDNs content should have a useful alt attribute (other than tutorials explaining bad practices, maybe)>

### Do you have any supporting links, references, or citations?

List  of missing alt attributes: https://docs.google.com/spreadsheets/d/1cDHee6mwDMlY6zANEmg8MjR8tL-wrCS86uawpWZ4XbA/edit#gid=0

### Do you have anything more you want to share?

When writing an alt attribute, think about how you would describe the image to someone who could read the page's content but couldn't load any images. What information does the image convey that is important and relevant to the user?

For example, if there are green boxes with a check mark for good and a red box with an X for bad, the user doesn't need to know the color of the box or the check or X. They do need to know what it is and if it's good or bad.

If there is a screenshot, explain the reason that image was used, not the contents of the screenshot. Don't provide information they don't need or already know. For example, if you're on a page about changing settings on Duck Duck go, if you have a screenshot of duck-duck-go search result, you don't need to explain what the search term is, how many results there are, how long the search took, etc. as that is not the point of the image. Since you're showing how to change settings in duck-duck-go, the alt might be "The settings icon is in the navigation bar below the search field." We didn't include "screenshot" or "duck duck go" as the user doesn't need to know it's a screenshot and already knows it's duck duck go as they are on a page explaining changing duck-duck-go settings.

**Comment by Chaitanya7666** [comment]
Hey @estelle , I just took a look at the spreadsheet. Most of the URL's to the MDN pages seem to be modified. However, I can manage to find them. I would be able to take up this issue and finish it. Could you please assign this to me?

**Comment by estelle** [comment]
> Most of the URL's to the MDN pages seem to be modified. 

Thank you. I fixed all the links. 

>  I would be able to take up this issue and finish it. Could you please assign this to me?

While this issue is a "good first issue", it's a 40+ hour issue so is a good first issue for lots of people. Feel free to claim some sub-ssues by changing the status in the spreadsheet from "not done" to in progress. I don't want to assign it to any individual person because it is a very large task to do them all. 

Thank you for volunteering.

**Comment by Chaitanya7666** [comment]
I have picked up the items from the **glossary** section for now. I will pick up a few more after the PR that I would raise for the current ones gets merged.

**Comment by Abhiram-Gullapalli** [comment]
Can I contribute too 😄

**Comment by Chaitanya7666** [comment]
@Abhiram-Gullapalli , why not? Please change the status of the items that you would like to pick up from the spreadsheet from `Not done` to `In progress` add your name to the `volunteer` column of the corresponding items.

**Comment by Chaitanya7666** [comment]
@estelle [Here is the PR for the items that I have picked](https://github.com/mdn/content/pull/19366)

**Comment by Chaitanya7666** [comment]
#19366

**Comment by Chaitanya7666** [comment]
#19366

**Comment by Chaitanya7666** [comment]
#19404

**Comment by Chaitanya7666** [comment]
#19497

**Comment by Chaitanya7666** [comment]
#19508

**Comment by Lhorla** [comment]
Hi Estelle, here's the [PR](https://github.com/mdn/content/pull/19632) to the items I worked on.

**Comment by estelle** [comment]
> Hi @estelle , here's the [PR](https://github.com/mdn/content/pull/19632) to the items I worked on.

Merged! Thank you.

**Comment by Chaitanya7666** [comment]
@estelle , [Link to PR](https://github.com/mdn/content/pull/19669)

I have made a handful of minor contributions to this issue in recent days but I don't see my name in the [contributors list](https://github.com/mdn/content/graphs/contributors). I couldn't find my name even when I used the filter to view the recent contributors. If you know the reason behind it, could you **please** tell me how to get my name on that list? Am I missing out on something while creating a Pull request? Thank you!

**Comment by Abhiram-Gullapalli** [comment]
One personal suggestion @Chaitanya7666 please contribute to open source projects to make an impact, helping to solve issues but not with any other intention. I hope you understood what I was trying to convey.
No offense intended, just my suggestion.

**Comment by Chaitanya7666** [comment]
> One personal suggestion @Chaitanya7666 please contribute to open source projects to make an impact, helping to solve issues but not with any other intention. I hope you understood what I was trying to convey. No offense intended, just my suggestion.

@Abhiram-Gullapalli ,You are assuming things. I don't understand how you were able to sense my intention behind my comment. I wished to see my name on the contributors list because I have contributed to the project. I don't understand what's wrong with it.

**Comment by Abhiram-Gullapalli** [comment]
Oh ok 😅my bad, keep contributing 🚀🚀

**Comment by Chaitanya7666** [comment]
> Oh ok sweat_smilemy bad, keep contributing rocketrocket

I understand that your intention behind it was to help me. Thank you @Abhiram-Gullapalli

**Comment by estelle** [comment]
We are halfway done!!!! w00t! Thank you for all your help everyone. This is fantastic.

**Comment by winniebosy** [comment]
Hi @estelle, here is the [PR](https://github.com/mdn/content/pull/19765) item I have worked on. Thanks

**Comment by estelle** [comment]
-

**Comment by estelle** [comment]
Closing this issue, and opened https://github.com/mdn/content/issues/20735
