### ISSUE TITLE
Attempting to assign guessField.value to a string throws error.

### ISSUE THREAD

**Issue by davebrogan** [mdn/content#19378]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash

### What specific section or headline is this issue about?

Playing With Browser Objects

### What information was incorrect, unhelpful, or incomplete?

The instruction in Step 4 to change the value of guessField to a string returns an error in the console and does not edit the input field on the page because the input type is set to "number" not "text." A better instruction would be to ask the user to change guessField.value to an int between 1 and 100 to match the input field data type and range that is already established in the sample html.

### What did you expect to see?

The input field data change to 'hello.'

### Do you have any supporting links, references, or citations?

https://www.w3schools.com/html/html_form_input_types.asp

### Do you have anything more you want to share?

![Screenshot 2022-08-10 124847](https://user-images.githubusercontent.com/13038974/183993476-cc8af260-78d7-42e3-bf4d-78930b059c40.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/a_first_splash`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/a_first_splash/index.md
* Last commit: https://github.com/mdn/content/commit/990eef4a94d6207fae003dd711fc3339e0f4f9c9
* Document last modified: 2022-07-11T13:04:03.000Z

</details>

**Comment by wbamberg** [comment]
Yes, agreed with your bug report and the suggested fix:

> A better instruction would be to ask the user to change guessField.value to an int between 1 and 100

e.g.

```js
guessField.value = 2;
```

**Comment by teoli2003** [comment]
Strangely, I see this at the top:

![Capture d’écran 2022-08-17 à 07 38 42](https://user-images.githubusercontent.com/1466293/185042949-eab44025-5de0-4f80-9142-a65f69c66b70.png)

So the `guessField` is an `<input type="text">` and it shouldn't fail. Should we update that line too?
