### ISSUE TITLE
Issue with "HTTP caching": Wrong label on HTTPCachtType.png diagram

### ISSUE THREAD

**Issue by zumoshi** [mdn/content#1937]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

#### What information was incorrect, unhelpful, or incomplete?
The Shared cache section labels the `Caching proxy` as `Browser 1`.

#### Specific section or headline?
Different kinds of caches ([picture](https://media.prod.mdn.mozit.cloud/attachments/2016/08/20/13777/27990fd7280c85641b4de27561f7e653/HTTPCachtType.png))

#### What did you expect to see?
`Shared proxy` or `Shared cache`. Or maybe a more concrete example such as `ISP` or `Company proxy`.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/caching`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/caching/index.html
* Last commit: https://github.com/mdn/content/commit/3c8dd140b3925bf8f7b00d0972f27c5760f5c6a3
* Document last modified: 2021-01-15T13:22:56.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. This will be fixed by #2159
