### ISSUE TITLE
Operator precedence and short circuiting

### ISSUE THREAD

**Issue by MarkFarmiloe** [mdn/content#19387]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND

### What specific section or headline is this issue about?

Operator precedence

### What information was incorrect, unhelpful, or incomplete?

I don't see how the stated order preference can ever be achieved, due to the short-circuiting.
This code:
```
function A() { console.log('called A'); return false; }
function B() { console.log('called B'); return false; }
function C() { console.log('called C'); return true; }

console.log(C() || B() && A());
console.log(A() || B() && C());
console.log(A() || C() && B());
```
gives the output of
```
> "called C"
> true
> "called A"
> "called B"
> false
> "called A"
> "called C"
> "called B"
> false
```
which demonstrates this.
Am I missing something?

### What did you expect to see?

Expected would possibly be
```
> "called B"
> "called C"
> true
> "called B"
> "called A"
> false
> "called C"
> "called B"
> "called A"
> false
```

### Do you have anything more you want to share?

I also believe I've built a perpetual motion machine, so I could be wrong.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/logical_and`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/logical_and/index.md
* Last commit: https://github.com/mdn/content/commit/fead53324d271aa05e93b369966a773bb328c64b
* Document last modified: 2022-08-09T16:39:29.000Z

</details>

**Comment by Josh-Cena** [comment]
"Operator precedence" is a technical term directly derived from the formal syntax. See https://tc39.es/ecma262/#sec-binary-logical-operators:

```
LogicalANDExpression :
    BitwiseORExpression
    LogicalANDExpression && BitwiseORExpression

LogicalORExpression :
    LogicalANDExpression
    LogicalORExpression || LogicalANDExpression
```

This production tells you that the right operand of `||` can be a `&&`, but neither operand of `&&` can be `||`. This means:

```js
true || false && false
```

It will be parsed as `true || (false && false)` and thus evaluate to `true`, instead of `(true || false) && false`, which evaluates to `false`.

Operator precedence does _not_ tell you in which order the _operands_ are evaluated: only the _operator_ order. It's also mentioned on that page:

> It is interesting to note that, the order of evaluation is always left-to-right regardless of associativity and precedence.

**Comment by Josh-Cena** [comment]
Short circuiting would be interesting to explain in tandem with operator precedence. Let's see how to demonstrate it better.

**Comment by MarkFarmiloe** [comment]
Thanks for that explanation.

I was indeed mixing operator precedence in with evaluation order.

That’s probably why my perpetual machine appears to have stopped for no reason.

 

Best regards

Mark

--

Mark Farmiloe

Churchill Computer Solutions Ltd

T: 0121 648 2398

M: 0777 339 1046

**Comment by MarkFarmiloe** [comment]
After a bit more thought, I set up a 'truth table' ish, as follows:
```let txt = '';
const log = (val) => { txt += `${val} `; return val; };

const test = (andFirst, first, second, third) => {
    txt = '';
    let result = eval(`log(first) ${andFirst?'&&':'||'} log(second) ${andFirst?'||':'&&'} log(third)`);
    console.log(`${first} ${andFirst?'&&':'||'} ${second} ${andFirst?'||':'&&'} ${third} => \n\t${txt} = ${result}`);
}

for (const a of [false, true]) {
    for (const b of [0, 1]) {
        for (const c of [null, 2]) {
            for (const d of [undefined, 3]) {
                test(a, b, c, d);
            }
        }
    }
}
```
Not looking for comments on my coding here 😁
which gave the following output:
```0 || null && undefined => 
        0 null  = null
0 || null && 3 => 
        0 null  = null
0 || 2 && undefined => 
        0 2 undefined  = undefined
0 || 2 && 3 => 
        0 2 3  = 3
1 || null && undefined => 
        1  = 1
1 || null && 3 => 
        1  = 1
1 || 2 && undefined => 
        1  = 1
1 || 2 && 3 => 
        1  = 1
0 && null || undefined => 
        0 undefined  = undefined
0 && null || 3 => 
        0 3  = 3
0 && 2 || undefined => 
        0 undefined  = undefined
0 && 2 || 3 => 
        0 3  = 3
1 && null || undefined => 
        1 null undefined  = undefined
1 && null || 3 => 
        1 null 3  = 3
1 && 2 || undefined => 
        1 2  = 2
1 && 2 || 3 => 
        1 2  = 2
```
All made sense to me until the '0 && null && undefined' test!
You said it's always evaluated left-to-right, but these seem to evaluate only the first and third elements !!!
After even more thought, this too makes sense as the second element is irrelevant as it is bracketed with the first.
But I didn't expect the third element to be evaluated and returned. I expected the first element, 0, to be returned due to short-circuiting. THIS is where the precedence comes in.
I don't know whether you could amend the documentation to make this clearer. (good luck if you try)

**Comment by Josh-Cena** [comment]
> Not looking for comments on my coding here 😁

I'd confess I wrote almost the same code last week.

I don't see `0 && null && undefined` in your results list (and its result is `0` which I don't find surprising). Do you mean `0 || null && undefined`?

**Comment by MarkFarmiloe** [comment]
It's the first test beginning with 0 rather than 1. I meant `0 && null || undefined`. 🤦  
And it returns `undefined` which blew my mind until I put the brackets in and properly thought about the short-circuiting, which only happens inside the brackets.
I've also read around on MDN a bit more, especially [Operator Precedence](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence), which explains things a bit more.
I'm writing myself a little document that I can go back to when I get confused (again). 🤣

**Comment by Josh-Cena** [comment]
`0 && null || undefined` returns `undefined`, because `&&` has higher precedence than `||`, so this is `(0 && null) || undefined`—LHS is falsy, so RHS is falsy.

Just don't get short-circuiting and precedence mixed up. Short circuiting is not observable if your operands don't have side-effects—you can always hypothetically substitute all expressions by their eventual values in order to find the final value, just beware that they may not always be actually evaluated.

**Comment by MarkFarmiloe** [comment]
Yes, you're right (of course).
It just took me (quite) some time to work it out.
Thanks for your patience.
I suppose I better sign up to MDN Plus 5 now 😁

**Comment by Josh-Cena** [comment]
Let's still reopen it. There's _something_ we can do to explain here.
