### ISSUE TITLE
Issue with "chrome_settings_overrides": (short summary here please)

### ISSUE THREAD

**Issue by richie3355** [mdn/content#1942]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_settings_overrides

Lets assume you name your search provider as WebSearch1 and then rename as WebSearch2 in the next update of the addon the search provider stops working. Is this an expected behaviour?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_settings_overrides
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by richie3355** [comment]
after debugging the ff code found that in SearchServices.jsm searches for the searcheengine based on the key and any update on engine name does not change the key and only the _name inside values

**Comment by rebloor** [comment]
@richie3355 I have created [Bug 1724468](https://bugzilla.mozilla.org/show_bug.cgi?id=1724468) for this.

**Comment by rebloor** [comment]
@richie3355 What version of Firefox did you find this issue on? I've been advised it was fixed in Firefox 85.

**Comment by rebloor** [comment]
As this was fixed in Firefox 85.
