### ISSUE TITLE
browser object undefined

### ISSUE THREAD

**Issue by sproket** [mdn/content#19424]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/get

### What information was incorrect, unhelpful, or incomplete?

Uncaught ReferenceError: browser is not defined

### What did you expect to see?

The code to work.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/tabs/get`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/get
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/tabs/get/index.md
* Last commit: https://github.com/mdn/content/commit/94d3111ec9d3c77c71486432072eba26e6e221dd
* Document last modified: 2022-05-06T06:20:43.000Z

</details>

**Comment by awxiaoxian2020** [comment]
Could you please tell us where you use it?

**Comment by sproket** [comment]
Sorry you can remove this. I realized that you can only use this with extensions.
