### ISSUE TITLE
Service Workers: Question about handling different paths for different environments

### ISSUE THREAD

**Issue by Bravo555** [mdn/content#19423]
Hello, there!
So I have a question about how to most gracefully handle different paths for different environments.
For example, in this very repository, path to service worker is constant: `/sw-test/sw.js`. On localhost this is no longer the case as the path is now `/sw.js` and further development can't be done until one modifies the scope to match the local environment. On localhost, service worker just don't work. One needs to change the scope and then remember to change it back when pushing, which can be forgotten quite easily.
So, how should I manage the paths for different origins? I used to use the following method for my API to work on localhost (as I host my API on localhost as well during development):
```js
let apiHostname = window.location.hostname.includes('localhost') ? 'http://localhost:8000' : 'https://[productionApiUrl]';
```
Is this good, should be applied to my service worker as well, or are there better methods?

Thanks!

**Comment by Rumyra** [comment]
Hi @Bravo555 the demo this query is about has been moved here: https://bncb2v.csb.app/ and has associated code here https://codesandbox.io/s/bncb2v

Hopefully that will be more helpful 👍
