### ISSUE TITLE
Broken Image Links in SVG pages

### ISSUE THREAD

**Issue by sydneypemberton1986** [mdn/content#19436]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fePointLight

### What specific section or headline is this issue about?

SVG images are broken in several examples throughout SVG section.

### What information was incorrect, unhelpful, or incomplete?

Sample SVG images show a broken image link when trying to link to a file

For example:
```svg
 <image xlink:href="/files/6457/mdn_logo_only_color.png" x="10%" y="10%"
      width="80%" height="80%" style="filter:url(#spotlight);"/>
```

Renders like this 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/46042811/184268598-024023e2-8c1c-4f5e-9dd4-d79534e28d52.png">

### What did you expect to see?

A legible example.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fePointLight and several other pages

### Do you have anything more you want to share?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/element/fepointlight`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fePointLight
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/fepointlight/index.md
* Last commit: https://github.com/mdn/content/commit/f107840858523dd1a50a07de2b6112928b5c31a2
* Document last modified: 2022-02-06T06:18:20.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @sydneypemberton1986 

Yes, this depends on `mdn_logo_only_color.png` which used to be the site logo. I've proposed a fix in #19437 - if it is considered OK I'll fix up the other cases.

**Comment by sydneypemberton1986** [comment]
Amazing turnaround time! Thank you!

**Comment by sydneypemberton1986** [comment]
Actually the PR looks like it will only fix the one page. Look through the other pages as well. 
One other [example](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feTile).

I would be surprised if there weren't more.
