### ISSUE TITLE
[CSS] `prefers-color-scheme` reflects the `color-scheme` on the embedding element

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#19449]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Update [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media query doc to note that:

> `prefers-color-scheme` reflects the `color-scheme` on the embedding element in the embedding document, to the extent acceptable from security standpoint (pending security review).
> This affects SVG and iframes - both same and cross-origin.

This should include an example like the one at the top of https://github.com/w3c/csswg-drafts/issues/7213#issue-1203479280 - 

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1779457 

## Other

What does this all mean?
- https://github.com/w3c/csswg-drafts/issues/7213 - initial CSSWG discussion- description gives example
- https://github.com/w3c/csswg-drafts/issues/7493 - follow up to confirm also applies to cross-origin iframes.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1764354#c20 - discussion with Moz engineer.

IN summary, previously [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) reflected the user choice of light/dark mode based on the device or OS theme setting. It was possible to have a case where the OS and firefox would have a different mode, and you could get `prefers-color-scheme` matching the OS rather than browser - so the incorrect media would be displayed.

The change is that `prefers-color-scheme` in SVG files and iframes will now respect the the [`color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) of the embedder.

## Links / tasks

- [x] mdn/content: https://github.com/mdn/content/pull/20886
- [x] relnote: https://github.com/mdn/content/pull/20888
- [x] BCD: https://github.com/mdn/browser-compat-data/pull/17846

**Comment by hamishwillee** [comment]
@Rumyra @dipikabh This was one of the draft items in the project to investigate. I have done the initial investigation. It doesn't happen until FF105 so parking for now. I can take it, or someone else with more CSS skill at that point.

**Comment by Rumyra** [comment]
Great - thank you so much @hamishwillee !
