### ISSUE TITLE
Error: Unexpected token '{' in Code Example

### ISSUE THREAD

**Issue by alieldeba** [mdn/content#19499]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static#try_it

### What specific section or headline is this issue about?

Try it section

### The code that has the error

``` js
class ClassWithStaticMethod {
  static staticProperty = 'someValue';
  static staticMethod() {
    return 'static method has been called.';
  }
  static {
    console.log('Class static initialization block called');
  }
}

console.log(ClassWithStaticMethod.staticProperty);
// output: "someValue"
console.log(ClassWithStaticMethod.staticMethod());
// output: "static method has been called."

```

### What information was incorrect, unhelpful, or incomplete?

The output was having an Unexpecting Error saying

``` js
Error: Unexpected token '{'
```

### What did you expect to see?

I Expected the output of the code

> Expected output 

``` 
someValue

static method has been called.
```

**Comment by Josh-Cena** [comment]
Please give your browser version. Static blocks are a very new feature.

**Comment by Josh-Cena** [comment]
I will preemtively close this as a question. You can check the compatibility data on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_static_initialization_blocks: I can confirm that it works in Chrome but not in Safari.

**Comment by alieldeba** [comment]
thanks very much the problem was in my chrome version I was testing this on an android 4 version

**Comment by alieldeba** [comment]
The problem is solved!
