### ISSUE TITLE
exslt syntax blocks tagged as "js"

### ISSUE THREAD

**Issue by rubiesonthesky** [mdn/content#19517]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/EXSLT/exsl/object-type

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

Syntax code blocks are tagged as "js". 

Should they be tagged as "plain" or with some other supported language? There are total 13 of pages which are using "js" tag for code blocks.

- [object-type](https://developer.mozilla.org/en-US/docs/Web/EXSLT/exsl/object-type)
- math:highest()
- math:lowest()
- math:max()
- regexp:replace()
- set:difference()
- set:distinct()
- set:has-same-node()
- set:intersection()
- set:trailing()
- str:concat()
- str:split()
- str:tokenize()

### What did you expect to see?

I expected them to be marked as `exsl` or with `plain`.

### Do you have anything more you want to share?

I can send PR for fix if these should be changed and there are info for what they should be instead of "js". Or is the "js" preferred way currently?

**Comment by teoli2003** [comment]
Thank you! Let's use `plain`! I'll happily review a PR.
