### ISSUE TITLE
RegExp - accessors are mis-documented as (own) properties

### ISSUE THREAD

**Issue by Phosra** [mdn/content#19524]
For example, see <https://tc39.es/ecma262/multipage/text-processing.html#sec-get-regexp.prototype.flags>.

MDN documents `RegExp` instance properties, that are actually accessor functions. They also seem to all lack setters, but this is mistakenly documented by calling them "read-only," and giving a property descriptor, which shouldn't exist.

**Comment by Josh-Cena** [comment]
I've just been recently updating regex-related pages. I'll change those as well.
