### ISSUE TITLE
group missing in RegExp. exec return value description

### ISSUE THREAD

**Issue by jho1965us** [mdn/content#19554]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

the table following: "The following table shows the state of result after running this script:"

is missing the "group" entry

### What did you expect to see?

row with property name "group" and explanation  that it is an object with a property for each named group containing  the match value for that group

### Do you have any supporting links, references, or citations?

inspected the return value of: <code>/(?<w>)/.exec(" w ")</code> in Chrome debugger

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/regexp/exec`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/regexp/exec/index.md
* Last commit: https://github.com/mdn/content/commit/2d6d6a1d9f8ba2073c9f8e1bbc6b4e20204fb53c
* Document last modified: 2022-08-07T06:13:17.000Z

</details>

**Comment by Josh-Cena** [comment]
What great timing! This has just been fixed earlier today via https://github.com/mdn/content/pull/19514. You should be able to see the new content within a few hours.
