### ISSUE TITLE
CA Suffixed to French Currency Numberformat in Chrome 

### ISSUE THREAD

**Issue by musalehad** [mdn/content#1956]
Using Intl.Numberformat for french currency causes the number to be suffixed with CA in chrome but not in firefox, safari or IE.
For examples, to format `123.456` i would get `123.456 $ CA` in chrome but `123.456 $` everywhere else.

This issue can be recreated with the below code

```
const number = 123456.789;
const defaultOptions = {
    style: 'currency',
    currency: 'CAD',
    minimumFractionDigits: 0,
  };
console.log(new Intl.NumberFormat('fr-CA', defaultOptions).format(number));
```
Im not sure if this is the right location to post this issue but if possible please provide a workaround for this issue or direct me to where i should post this issue to get a fix/workaround.
Thank you

**Comment by myakura** [comment]
I don't have a workaround for you (sorry), but you might want to file a bug against Chrome from https://crbug.com/new .

**Comment by musalehad** [comment]
No worries. I found one way to fix this for now. 
Using `currencyDisplay: 'narrowSymbol',` in the options removes any country codes.
