### ISSUE TITLE
WebAssembly.Memory#buffer is read-only

### ISSUE THREAD

**Issue by Phosra** [mdn/content#19564]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/buffer

### What information was incorrect, unhelpful, or incomplete?

The item is documented as a property.

### What did you expect to see?

It is a read-only/getter-only accessor.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/webassembly/memory/buffer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/buffer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/webassembly/memory/buffer/index.md
* Last commit: https://github.com/mdn/content/commit/9ce57d5046baf5d25c8eb066e60227f0fbd017cf
* Document last modified: 2022-08-12T14:18:15.000Z

</details>

**Comment by hamishwillee** [comment]
Would it be sufficient to just change the first line to add "read only"?

> The buffer prototype read-only property of the ...

**Comment by Phosra** [comment]
> Would it be sufficient to just change the first line to add "read only"?
> 
> > The buffer prototype read-only property of the ...

I don't know.
I would take precedent from Set#size and TypedArray#length, but this isn't a JavaScript built-in, so looking at Web APIs, I see that items such as Window#innerWidth are documented as read-only, but not an accessor, so... well, I'm of no authority to decide anyways; how about opening a discussion?

**Comment by Phosra** [comment]
I think simply calling it read-only works for now. Any discussion about whether it should say "accessor" can come later.

**Comment by hamishwillee** [comment]
@Phosra That's what I was about to say. Can you make the PRs?

**Comment by Phosra** [comment]
Sure - they're small, I'll find time to make them later.

**Comment by hamishwillee** [comment]
Thanks. Discussion created here: https://github.com/mdn/mdn-community/discussions/195
