### ISSUE TITLE
[CSS] Add :has() to experimental features

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#19572]
## Acceptance Criteria

- [X] The listed features are documented sufficiently on MDN
       The [:has()](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) page exists. The description and examples need to be improved.
       This work will be tracked separately here: https://github.com/mdn/content/issues/19972
- [X] BCD is updated
        https://github.com/mdn/browser-compat-data/pull/17353
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [X] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release - NA
or
- [X] Add entry to Firefox experimental features page if feature is not yet enabled in release
       https://github.com/mdn/content/pull/19970

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1771896

**Comment by hamishwillee** [comment]
@dipikabh This is another PR that was originally a draft. 
- I've added the BCD here: https://github.com/mdn/browser-compat-data/pull/17353
- This will need an experimental features entry - it is behind pref `layout.css.has-selectors.enabled`

In terms of docs the [`:has()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) page exists but IMO needs a bit of work:
- the syntax docs are take a `<forgiving-relative-selector-list>` but that is not defined anywhere in our docs. In summary all the "forgiving" bit means is that any of the comma separated selectors are invalid they just get skipped and the selector works on the valid ones. 
  - This is apparently different to normal list selectors, where if one is wrong the lot get dumped. Not clear if this applies to just when used in a query or in a style sheet.
  - the "relative" bit means that the selectors are relative to the element or whatever that this has() was applied to.
- The WG just added a new rule that `has()` pseudo class can't contain a pseudo class of the current types, but may take future types: https://github.com/w3c/csswg-drafts/issues/7463#issuecomment-1196971909
  - So we may have to list the cases that can't be used.
  - It is not clear whether FF already implements this restriction according to https://bugzilla.mozilla.org/show_bug.cgi?id=418039. I think we need some test code.
- The Description from/including "In earlier revisions of the CSS Selectors Level 4 specification, :has had a limitation that it couldn't be used within stylesheets. ..." should be removed. If it wasn't implemented in any browser it is now irrelevant.
- The examples are too simplistic - they only show one item - NOT a list. We need a list, and we should also show that the case of an invalid selector is dropped. Ideally in a live example.

I assume you want to take this one on, but push it back if you don't :-)

**Comment by dipikabh** [comment]
Thank you so much, @hamishwillee for doing all this digging and drawing out the task list! Appreciate it 🙏 .

I'll definitely like to take a stab at it. I'll possibly ping you if I feel stuck. 🙂

**Comment by dipikabh** [comment]
To reitrate: 
The [:has()](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) page exists. The description and examples need to be improved - this work will be tracked via [Improve the :has() page documentation #19972](https://github.com/mdn/content/issues/19972).

**Comment by adjenks** [comment]
I would rather this feature be half broken than disabled by default. Other major browsers support it. Having it experimental and disabled is basically broken in my opinion. I've wanted to use this feature so many times and I keep checking back to see when it will be enabled by default.
