### ISSUE TITLE
Need content about WebExtensions versions formatting 

### ISSUE THREAD

**Issue by caitmuenster** [mdn/content#1959]
Related to #1909. On https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version, we write, "For the details of the version format, see the [Version format page](https://developer.mozilla.org/en-US/docs/Toolkit_version_format)." `version format page` is a deadlink to https://developer.mozilla.org/en-US/docs/Toolkit_version_format. 

We should either restore the deadlink or include relevant info from the page on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version. 

// cc @rpl

**Comment by caitmuenster** [comment]
Did some digging and it looks like the archived page can be found at https://github.com/mdn/archived-content/blob/main/files/en-us/mozilla/toolkit_version_format/index.html. 

It looks like the relevant part is captured in lines 21 - 77. 

@rpl, if that looks right to you, I can submit a PR to re-add this content.

**Comment by rpl** [comment]
> Did some digging and it looks like the archived page can be found at https://github.com/mdn/archived-content/blob/main/files/en-us/mozilla/toolkit_version_format/index.html.
> 
> It looks like the relevant part is captured in lines 21 - 77.
> 
> @rpl, if that looks right to you, I can submit a PR to re-add this content.

@caitmuenster :+1: yep, that looks right to me
