### ISSUE TITLE
JS “import” doc: getPrimes.js example cannot work as expected.

### ISSUE THREAD

**Issue by malavv** [mdn/content#19601]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

### What specific section or headline is this issue about?

Examples > Standard Import

### What information was incorrect, unhelpful, or incomplete?

The `getPrimes.js` example does not work as expected. 

The person who wrote the code forgot to add the prime to the map before/after adding all the multiple of the prime as non-prime in the map.

### What did you expect to see?

I expected the code in the example to work as the provided output described.

### Do you have any supporting links, references, or citations?

It clearly filter on positive value of the Map, and never sets a positive value, hence it cannot have any result.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/import`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/import/index.md
* Last commit: https://github.com/mdn/content/commit/4f5e0e38cd51ed4d52be2003375b87ceb9874974
* Document last modified: 2022-07-29T02:45:07.000Z

</details>

**Comment by Josh-Cena** [comment]
My bad😅 What I forgot is those map keys that I didn't set aren't there at all. I need to use an array instead (as everyone doing Erathosthenes' sieve does)
