### ISSUE TITLE
Remove use of add/removeListener from MediaQueryList* pages

### ISSUE THREAD

**Issue by teoli2003** [mdn/content#19619]
This is a part of https://github.com/mdn/dom-examples/issues/62.

`MediaQueryList` initially had two special methods, `addListener()` and `removeListener()`. They have been deprecated when `EventTarget` was added to the `MediaQueryList` inheritance chain; now, the standard `addEventListener()` and `removeEventListener()` methods can be used.

I found some occurrences of these in:
- `MediaQueryListEvent.media`
- `MediaQueryListEvent`
- `MediaQueryListEvent.matches`
- `MediaQueryList.matches`

We should update these.

**Comment by iSatVeerSingh** [comment]
I got the issue. I am now working on it.
