### ISSUE TITLE
Auto generated anchor tags in Heading elements pointing to that heading itself except H1 elements (This is on every page) 

### ISSUE THREAD

**Issue by iSatVeerSingh** [mdn/content#19625]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript

### What specific section or headline is this issue about?

Heading elements on every page except H1 element 

### What information was incorrect, unhelpful, or incomplete?

I found that there are auto generated _anchor tags_ in heading elements on every page. These anchor tags points to that heading itself in which it is generated.

The linked page is just one example of it. This issue is on every page.

When I move cursor on to heading, it becomes pointer, which means, this heading element has an anchor tag in it.
When I click on this heading(with auto generated anchor) to points to itself only.
As you can see in below image.
 
![auto-generated-anchor-tags01](https://user-images.githubusercontent.com/85070570/184854162-c06410aa-5f83-4db7-a300-475945ae25e8.png)

When I inspect, it shows that heading element has a nested anchor tag in it.
See below
![auto-generated-anchor-tags0002](https://user-images.githubusercontent.com/85070570/184857034-2668af08-090a-4baa-aecb-c90356c38f95.png)

### What did you expect to see?

There should not be any nested or auto generated anchor tags in heading elements.
If heading has an id attribute then any other element should point to this, not itself.

**This should not be like this :-** 
![problem](https://user-images.githubusercontent.com/85070570/184857972-3b29f651-4b1f-4fe2-9f8b-c214ad0e38db.png)

### This should be like this :- 
![solution](https://user-images.githubusercontent.com/85070570/184858087-9d2293cf-adcf-4840-8a28-58f029e67c47.png)

**Comment by Josh-Cena** [comment]
This is working as intended. Imagine you want to link to the "Solving common JavaScript problems" heading. How do you know what its anchor is without opening dev tools? You click on the heading so that the anchor automatically appears in the URL bar and you can copy.

This is virtually how every documentation site works.
