### ISSUE TITLE
Placeholder WebGL data type information

### ISSUE THREAD

**Issue by ma1ted** [mdn/content#19634]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Data

### What specific section or headline is this issue about?

GLSL data types

### What information was incorrect, unhelpful, or incomplete?

> <<document the basic types, vectors, etc.; see [Data Type (GLSL)](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)) on the Khronos WebGL wiki>>

The information under the *GLSL data types* header is a TODO

### What did you expect to see?

An overview of the GLSL data types, or at least a clean link to the documentation.

### Do you have any supporting links, references, or citations?

[The GLSL data types docs](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL))

### Do you have anything more you want to share?

![image](https://user-images.githubusercontent.com/59726149/184939329-7b02f658-42f5-424e-8f34-dbcea2b0e440.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webgl_api/data`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Data
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/data/index.md
* Last commit: https://github.com/mdn/content/commit/411e3bb536f858a9d58600b4017979c79b2a4408
* Document last modified: 2022-08-15T12:34:54.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing, @ma1ted ! This is fixed by https://github.com/mdn/content/pull/19825.
