### ISSUE TITLE
Iterators explanation issue

### ISSUE THREAD

**Issue by AnandBIT** [mdn/content#19640]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators

### What specific section or headline is this issue about?

Iterables

### What information was incorrect, unhelpful, or incomplete?

**Iterables which can iterate only once (such as Generators) customarily return this from their @@iterator method, whereas iterables which can be iterated many times must return a new iterator on each invocation of @@iterator.**

I'm not able to understand how the above statement holds true as I can iterate a generator function as many times as I want. Can someone please clarify?

### What did you expect to see?

Something better with more examples

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#iterables

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/iterators_and_generators`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/iterators_and_generators/index.md
* Last commit: https://github.com/mdn/content/commit/d6f63f6e41146f459e21046af1c51fadb772de70
* Document last modified: 2022-08-05T15:37:08.000Z

</details>

**Comment by Josh-Cena** [comment]
Every time you call `gen()`, it returns you a new iterator. But every iterator you get from invoking `gen()` can only be iterated once.

**Comment by Josh-Cena** [comment]
I realized we already explained it further up:

> The function can be called as many times as desired, and returns a new Generator each time. Each Generator may only be iterated once.

I don't think we need any amendments here. Closing for now, but feel free to comment below if you feel strongly.

**Comment by AnandBIT** [comment]
> Every time you call `gen()`, it returns you a new iterator. But every iterator you get from invoking `gen()` can only be iterated once. You are mixing up generators with generator functions.

Let's take an example
```js
function* gen() {
	for (var i = 1; i <= 5; i++) {
		yield i;
	}
}
const iterator = gen();
```
In the above example, after getting an `iterator` returned from calling `gen()`, I can iterate the `iterator` 5 times and it can be increased also by replacing the constant `5` with an argument.
I'm not able to understand your statement about the iterator which according to you/mdn docs, can be iterated only once, please clarify

**Comment by Josh-Cena** [comment]
You are misunderstanding what "iterate" means, then. This is "iterating":

```js
for (const i of iterator) console.log(i);
```

After you've iterated it, you can no longer read anything from `iterator` because its `next()` returns `done: true`.

This is also iterating:

```js
iterator.next();
iterator.next();
iterator.next();
iterator.next();
// …
```

"Iterating once" does not mean doing any one particular atomic operation. It just means your action is not recoverable.

**Comment by AnandBIT** [comment]
Got your point, also found a [stackoverflow](https://stackoverflow.com/questions/58573790/generator-iterators-iterable-mdn-documentation) thread related to this.
Thanks for the explanation @Josh-Cena
