### ISSUE TITLE
Clarify intended audience for speeding up [[Prototype]] mutations

### ISSUE THREAD

**Issue by rounakcodes** [mdn/content#19647]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/The_performance_hazards_of_prototype_mutation

### What specific section or headline is this issue about?

Introduction (Second paragraph)

### What information was incorrect, unhelpful, or incomplete?

This article explains why [[Prototype]] mutation is slow in all browsers and describes alternatives that should be used instead.

### What did you expect to see?

This article explains why [[Prototype]] mutation is slow in all browsers and describes the alternatives which should be used by browser developers.

### Do you have any supporting links, references, or citations?

No

### Do you have anything more you want to share?

After reading the concerned statement, I was expecting some content in the article for application developers to speed up the process of [[Prototype]] mutation.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/the_performance_hazards_of_prototype_mutation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/The_performance_hazards_of_prototype_mutation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/the_performance_hazards_of_prototype_mutation/index.md
* Last commit: https://github.com/mdn/content/commit/b40b71d87ab041f2f36a4675bc09af983b22422a
* Document last modified: 2022-08-09T06:29:53.000Z

</details>

**Comment by Josh-Cena** [comment]
You can't _speed up the process of [[Prototype]] mutation_. It's telling you _why_ it's slow, and therefore you should simply never do it because it's impossible to optimize in userland.

**Comment by Phosra** [comment]
Oh, well, [[Prototype]] manipulation might even be *fast*. It's that you de-optimise the code, if using an engine with a JavaScript compiler. So, if you want your code to stay fast, use a JavaScript interpreter.

This is in jest - the suggestion just keeps it slow.

Why do you actually have interest in manipulating the prototype?

**Comment by rounakcodes** [comment]
It seems the title of the thread did not serve its purpose. I am not trying to speed up mutating the [[Prototype]]. When I was reading the document, the statement "This article explains why [[Prototype]] mutation is slow in all browsers and describes alternatives that should be used instead." made me think that there are ways to speed it up in userland. So, I continued reading it. If it was made clearer that it cannot be done in userland and that the article was meant for engine/browser (I don't even know who) developers, I would have skipped reading from that point.

**Comment by Josh-Cena** [comment]
Well—the title says "The performance hazards of [[Prototype]] mutation" so it's just a factual piece of information about "why". I think the "describes alternatives that should be used instead" sentence should be removed if that confuses you.

**Comment by rounakcodes** [comment]
I meant the title: [Clarify intended audience for speeding up [[Prototype]] mutations](https://github.com/mdn/content/issues/19647#top)

**Comment by Josh-Cena** [comment]
Yes. The intended audience is those who would like to know why and how performance for [[Prototype]] mutation is slow, with a reference to how it's implemented under the hood. It's definitely not intended for engine implementers since it's not talking about what they should do; it's not talking about what you should do either—it's simply describing facts.

**Comment by Josh-Cena** [comment]
The more I read it, the more I feel like this page doesn't belong in MDN. It should be a blog post instead, like https://mathiasbynens.be/notes/prototypes

@teoli2003 @Elchi3 @wbamberg thoughts on removing this page and pointing readers to that post instead?

**Comment by Josh-Cena** [comment]
Yes, that's exactly what I'm proposing. Not sure where we should redirect to for the deleted MDN page though, redirecting to the blog post seems cheap.

**Comment by wbamberg** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto is the other place we link to this page, among a ridiculous pile of warnings.

We could just redirect to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf , maybe?
