### ISSUE TITLE
Function#caller is an accessor

### ISSUE THREAD

**Issue by Phosra** [mdn/content#19649]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/caller

### What information was incorrect, unhelpful, or incomplete?

`Function.prototype.caller` is documented as a property.

### What did you expect to see?

`caller` is an get/set accessor.

### Do you have any supporting links, references, or citations?

#19525 Should be applied here.

### Do you have anything more you want to share?

Optionally, nuance may be taken to both pages, to explain when the property is a non-standard own property.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/function/caller`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/caller
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/function/caller/index.md
* Last commit: https://github.com/mdn/content/commit/8a5ab92ceab8fe1b8f44597381cf3fd996e252e9
* Document last modified: 2022-08-06T06:07:15.000Z

</details>

**Comment by Josh-Cena** [comment]
After discussion in https://github.com/mdn/browser-compat-data/issues/17344, I'm not even sure what to do—it's standardized as a getter, but when doing anything meaningful about it without throwing, it's actually a data property. I think the spec isn't really useful here; we can say that "a throwing getter is the only standardized behavior", but in most implementations, if you get actual data from it, then it's a data property.

**Comment by Phosra** [comment]
> After discussion in https://github.com/mdn/browser-compat-data/issues/17344, I'm not even sure what to do—it's standardized as a getter, but when doing anything meaningful about it without throwing, it's actually a data property. I think the spec isn't really useful here; we can say that "a throwing getter is the only standardized behavior", but in most implementations, if you get actual data from it, then it's a data property. This would be useful for people actually using it.

Agreed! This is what I hint to under "Do you have anything more you want to share?"
I believe it would be accurate to bring this up for both relevant pages, and to bring them in sync.
