### ISSUE TITLE
"fr" unit missing

### ISSUE THREAD

**Issue by cilex-ft** [mdn/content#19653]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units

### What specific section or headline is this issue about?

Distance units

### What information was incorrect, unhelpful, or incomplete?

The _**fr**_ unit is not yet listed as a relative length unit. 

### What did you expect to see?

_fr_ shoud be defined as a legitimate unit.

### Do you have any supporting links, references, or citations?

The post about CSS Grid introduced _fr_ as a new unit in August 2021, https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout#the_fr_unit .

EDIT: _**fr**_, not _lr_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_values_and_units`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_values_and_units/index.md
* Last commit: https://github.com/mdn/content/commit/4c4b8b091deccbc18a520b66828b7cef7a9e50ca
* Document last modified: 2022-08-14T00:34:11.000Z

</details>

**Comment by teoli2003** [comment]
It is `fr` not `lr`, but, yes, we may want to consider adding it there.

**Comment by wbamberg** [comment]
It's not a `<length>` unit, it's a value for [`<flex>`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex_value). So we should probably add `<flex>` to the list of dimensions at https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units#dimensions and give it its own subsection, alongside "Distance units" and so on.

**Comment by wbamberg** [comment]
-> https://github.com/mdn/content/pull/19877
