### ISSUE TITLE
Caches.addAll is not origin-relative

### ISSUE THREAD

**Issue by noamr** [mdn/content#19665]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

### What specific section or headline is this issue about?

Install and activate

### What information was incorrect, unhelpful, or incomplete?

It says that URLs passed to Caches.addAll are "origin-relative". This is misleading, they're relative to the document or service worker's base URL.

### What did you expect to see?

Reference to the appropriate base of the relative URL.

### Do you have any supporting links, references, or citations?

From the [service worker spec](https://www.w3.org/TR/service-workers/#dom-cache-addall):

Let r be the associated [request](https://fetch.spec.whatwg.org/#concept-request-request) of the result of invoking the initial value of [Request](https://fetch.spec.whatwg.org/#request) as constructor with request as its argument. If this [throws](https://webidl.spec.whatwg.org/#dfn-throw) an exception, return [a promise rejected with](https://webidl.spec.whatwg.org/#a-promise-rejected-with) that exception.

[Constructor of the Request object](https://fetch.spec.whatwg.org/#dom-request):

Let baseURL be [this](https://webidl.spec.whatwg.org/#this)’s [relevant settings object](https://html.spec.whatwg.org/multipage/webappapis.html#relevant-settings-object)’s [API base URL](https://html.spec.whatwg.org/multipage/webappapis.html#api-base-url).

...

Let parsedURL be the result of [parsing](https://url.spec.whatwg.org/#concept-url-parser) input with baseURL.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/service_worker_api/using_service_workers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/service_worker_api/using_service_workers/index.md
* Last commit: https://github.com/mdn/content/commit/997c48175d0becac5936f3ea3a67749acae74f26
* Document last modified: 2022-07-27T05:54:36.000Z

</details>

**Comment by stuartlangridge** [comment]
While updating this page, it would be useful to also update https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers (which is a very good simple guide to adding a service worker without introducing extra complexity) with a tiny note saying that the URLs added to the cache are relative to the service-worker URL.

**Comment by softorangetech200** [comment]
Where does it show? I'm close to making a PR.

**Comment by noamr** [comment]
> Where does it show? I'm close to making a PR. Searching "origin-relative" in the document reveals no results.

It says:

Inside addResourcesToCache we use the [caches.open()](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/open) method to create a new cache called v1, which will be version 1 of our site resources cache. Then we call a function that calls addAll() on the created cache, which for its parameter takes an array of *origin-relative* URLs to all the resources you want to cache.

**Comment by softorangetech200** [comment]
> > Where does it show? I'm close to making a PR. Searching "origin-relative" in the document reveals no results.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
> 
> It says:
> 
> Inside addResourcesToCache we use the [caches.open()](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/open) method to create a new cache called v1, which will be version 1 of our site resources cache. Then we call a function that calls addAll() on the created cache, which for its parameter takes an array of _origin-relative_ URLs to all the resources you want to cache.
> 
> In the [document in the comment](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers) it doesn't say that but it would be good to add a note, and also in https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll and https://developer.mozilla.org/en-US/docs/Web/API/Cache/add it's not clear what the URLs are relative to.

Creating a PR soon.

**Comment by softorangetech200** [comment]
> > Where does it show? I'm close to making a PR. Searching "origin-relative" in the document reveals no results.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
> 
> It says:
> 
> Inside addResourcesToCache we use the [caches.open()](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/open) method to create a new cache called v1, which will be version 1 of our site resources cache. Then we call a function that calls addAll() on the created cache, which for its parameter takes an array of _origin-relative_ URLs to all the resources you want to cache.
> 
> In the [document in the comment](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers) it doesn't say that but it would be good to add a note, and also in https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll and https://developer.mozilla.org/en-US/docs/Web/API/Cache/add it's not clear what the URLs are relative to.

Hello @noamr! Recently made a new PR. Can you please tell me what to update? That would be nice, since @wbamberg wants me to update the pages that you requested for PRs that fix the issue.

**Comment by noamr** [comment]
> > > Where does it show? I'm close to making a PR. Searching "origin-relative" in the document reveals no results.
> > 
> > 
> > https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
> > It says:
> > Inside addResourcesToCache we use the [caches.open()](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/open) method to create a new cache called v1, which will be version 1 of our site resources cache. Then we call a function that calls addAll() on the created cache, which for its parameter takes an array of _origin-relative_ URLs to all the resources you want to cache.
> > In the [document in the comment](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers) it doesn't say that but it would be good to add a note, and also in https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll and https://developer.mozilla.org/en-US/docs/Web/API/Cache/add it's not clear what the URLs are relative to.
> 
> Hello @noamr! Recently made a new PR. Can you please tell me what to update? That would be nice, since @wbamberg wants me to update the pages that you requested for PRs that fix the issue.

HI
I replied on the PR: https://github.com/mdn/content/pull/19955#issuecomment-1229392375

The way this is spec'ed is that:
- all those cache functions, receive whatever the Request constructor receives
- The Request constructor receives either an existing request, or a URL - which is relative to the document or the worker (nor necessarily a service worker)

mdn should find a nicer way to explain this I guess :)
