### ISSUE TITLE
More objects are claimed to have their shaped modified, than would be expected

### ISSUE THREAD

**Issue by Phosra** [mdn/content#19686]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/The_performance_hazards_of_prototype_mutation

### What specific section or headline is this issue about?

Intelligently Optimizing Inherited Properties

### What information was incorrect, unhelpful, or incomplete?

The example given is reproduced here:
```js
const obj1 = {};
const obj2 = Object.create(obj1);
const obj3 = Object.create(obj2);

// Objects whose shapes would change: obj3, obj2, obj1, Object.prototype
Object.setPrototypeOf(obj3, {});
```
Now, I may be wrong, but as far as I can tell, the shapes of `obj1`, `obj2`, and `Object.prototype` remain the same.

### What did you expect to see?

Any functions called with these three objects should not be de-optimised by a JiT compiler, unless they involve `obj3`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/the_performance_hazards_of_prototype_mutation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/The_performance_hazards_of_prototype_mutation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/the_performance_hazards_of_prototype_mutation/index.md
* Last commit: https://github.com/mdn/content/commit/b40b71d87ab041f2f36a4675bc09af983b22422a
* Document last modified: 2022-08-09T06:29:53.000Z

</details>

**Comment by Josh-Cena** [comment]
I don't know... I raised my eyebrows when reading that sentence as well, but maybe there's something I'm missing, since this section is talking about hidden classes I think.

**Comment by Phosra** [comment]
> I don't know... I raised my eyebrows when reading that sentence as well, but maybe there's something I'm missing, since this section is talking about hidden classes I think.

Indeed, "hidden classes" are what I refer to by "structure," as it's what I believe it means here.
