### ISSUE TITLE
Issue with one of the differences between Object literal notation vs JSON

### ISSUE THREAD

**Issue by nelsonbarrac** [mdn/content#19680]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#object_literal_notation_vs_json

### What information was incorrect, unhelpful, or incomplete?

In the docs it is mentioned : "Objects like [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) will be a string after [JSON.parse()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)"

Although JSON.parse() will fail is you provide a Date object as input, hence I think that JSON.stringify() is the correct method refered.

### What did you expect to see?

Objects like [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) will be a string after [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)

### Do you have any supporting links, references, or citations?

In the documentation of JSON.stringify() there is an example of how a Date object will produce a string as output.
In the other hand JSON.parse() will only receive a string as input.

This is the example mentioned above.

console.log(JSON.stringify(new Date(2006, 0, 2, 15, 4, 5)));
// expected output: ""2006-01-02T15:04:05.000Z""

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/object_initializer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/object_initializer/index.md
* Last commit: https://github.com/mdn/content/commit/85ab598dcece97abba0c654a6f265ca63ebe9b03
* Document last modified: 2022-08-16T06:48:24.000Z

</details>

**Comment by Josh-Cena** [comment]
I don't really know... This sentence looks a bit confusing to me overall. I think this section is comparing a string representing an object versus a string representing JSON, i.e.

```js
const someObjLiteral = "{ a: 1 }";
const someJSON = '{ "a": 1 }';
const data1 = eval(someObjLiteral);
const data2 = JSON.parse(someJSON);
```

I think the intention of this sentence is "JSON can only express plain objects and arrays, but not objects like `Date`".
