### ISSUE TITLE
Wrong link text

### ISSUE THREAD

**Issue by KaleyGoode** [mdn/content#19694]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

### What information was incorrect, unhelpful, or incomplete?

The link text, "Groups and ranges", good to the, "groups and back links", page (no ranges help there)

### What did you expect to see?

"Groups and back links" in the link text and an additional ranges link

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/index.md
* Last commit: https://github.com/mdn/content/commit/4cdc9184d5ad656730afcf3a4dd84c8dd3962a61
* Document last modified: 2022-08-17T19:44:44.000Z

</details>

**Comment by Josh-Cena** [comment]
Thanks for reporting! Do you want to take a shot at this?

**Comment by KaleyGoode** [comment]
I couldn't even write the report without a typo! 😂
