### ISSUE TITLE
[Intent to Document] Background Fetch API and Associated Interfaces

### ISSUE THREAD

**Issue by jpmedley** [mdn/content#197]
**Spec:** https://wicg.github.io/background-fetch/
**Interfaces:**

- [ ] `BackgroundFetchEvent`
- [x] `BackgroundFetchManager`
- [ ] `BackgroundFetchRecord`
- [ ] `BackgroundFetchRegistration`
- [ ] `BackgroundFetchUpdateUIEvent`
- [ ] Four event handlers extending `ServiceWorkerGlobalScope`
- [ ] One event handler extending `ServiceWorkerRegistration`

Spec submitted at: https://github.com/mdn/yari/pull/2636
BCD data for these interfaces is already present

**Comment by himanshugarg** [comment]
Most of the interfaces are now documented. The status of four event handlers is not obvious to me from the relevant page:-
- [x] [BackgroundFetchEvent](https://developer.mozilla.org/en-US/docs/Web/API/BackgroundFetchEvent)
- [x] [BackgroundFetchManager](https://developer.mozilla.org/en-US/docs/Web/API/BackgroundFetchManager)
- [x] [BackgroundFetchRecord](https://developer.mozilla.org/en-US/docs/Web/API/BackgroundFetchRecord)
- [x] [BackgroundFetchRegistration](https://developer.mozilla.org/en-US/docs/Web/API/BackgroundFetchRegistration)
- [x] [BackgroundFetchUpdateUIEvent](https://developer.mozilla.org/en-US/docs/Web/API/BackgroundFetchUpdateUIEvent)
- [ ] Four event handlers extending ServiceWorkerGlobalScope
- [x] [One event handler extending ServiceWorkerRegistration](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration#event_handlers)

**Comment by jpmedley** [comment]
Thank you for the update. If you're not the one who created these, then whoever did has my thanks.

FYI, my boilerplates for events aren't right. I built these before the new idioms were finalized and I'm having trouble getting mode code to generate them.

**Comment by himanshugarg** [comment]
> I'm having trouble getting mode code to generate them

Could it be `onmessageerror` that remains undocumented? 

There are five event handlers [as per the spec](https://w3c.github.io/ServiceWorker/#serviceworkerglobalscope-interface):-

Event Handler | MDN Link 
--- | ---
oninstall |  [Web/API/ServiceWorkerGlobalScope/oninstall](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/oninstall)
onactivate | [Web/API/ServiceWorkerGlobalScope/onactivate](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/onactivate)
onfetch | [Web/API/ServiceWorkerGlobalScope/onfetch](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/onfetch)
onmessage | [Web/API/ServiceWorkerGlobalScope/onmessage](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/onmessage)
onmessageerror | [404](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/onmessageerror)

**Comment by jpmedley** [comment]
>Could it be `onmessageerror` that remains undocumented?

It is.

**Comment by Rumyra** [comment]
I see 4 of the 5 remaining pages above 404'ing - can you confirm @jpmedley ? If so I'll raise new issues for those specific pages left, rather than tracking here 👍

**Comment by jpmedley** [comment]
4 of the 5 is what I see as well. `onmessage` is the only one going to an actual page.

**Comment by teoli2003** [comment]
We don't document _onXYZ_ pages, but _XYZ_event_. All four are documented, but 3 of them have no redirect to the actual passage.

So we can close this, or add the 3 redirects and close this.

**Comment by Rumyra** [comment]
From what I can gather from the history of the ServiceWorkerGlobalScope page `onmessage` was the only one documented and needed a redirect when the new events pages were added, so I think we're ok to close 👍 

(Feel free to disagree and I'll reopen for added redirects)
