### ISSUE TITLE
[HTML] Remove `menuitem` and preferences in Fx 103

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#19707]
https://bugzilla.mozilla.org/show_bug.cgi?id=1372276

- [x] Check docs

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMenuElement
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMenuItemElement

- [x] Update bcd
- [x] Rel note
- [x] update bug keyword

**Comment by teoli2003** [comment]
It is the removal of the _context menu_ feature of <menu> & co. Not the whole feature.

**Comment by bsmth** [comment]
- [ ] MDN/content update: https://github.com/mdn/content/pull/20421
- [ ] BDC: TODO
