### ISSUE TITLE
Example not correct

### ISSUE THREAD

**Issue by stacker60** [mdn/content#19700]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf

### What specific section or headline is this issue about?

position parameter

### What information was incorrect, unhelpful, or incomplete?

The first example given for the position parameter is:

_'hello world hello'.indexOf('o', -5) returns 4 — because it causes the method to behave as if the second argument were 0, and the first occurrence of **`hello`** at a position greater or equal to 0 is at position 4._

The search isn't looking for the word "hello", it's looking for the character "o".

### What did you expect to see?

The example should read:

_'hello world hello'.indexOf('o', -5) returns 4 — because it causes the method to behave as if the second argument were 0, and the first occurrence of **`o`** at a position greater or equal to 0 is at position 4._

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/indexof`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/indexof/index.md
* Last commit: https://github.com/mdn/content/commit/2c2f8caac8cbf8e41019c01be5635e10fe65f2cd
* Document last modified: 2022-08-12T04:52:35.000Z

</details>

**Comment by Josh-Cena** [comment]
Seems like a typo. PR welcome.
