### ISSUE TITLE
Writing forward-compatible websites is outdated

### ISSUE THREAD

**Issue by estelle** [mdn/content#19717]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Guide/Writing_forward-compatible_websites

### What specific section or headline is this issue about?

javascript

### What information was incorrect, unhelpful, or incomplete?

I think we've switched to recommend not using window. and this article recommends using window.
This page needs some modern  love.

### What did you expect to see?

Modern best practices

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/guide/writing_forward-compatible_websites`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Writing_forward-compatible_websites
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/writing_forward-compatible_websites/index.md
* Last commit: https://github.com/mdn/content/commit/0df8a56407d792edf58e9fbcf5afa140a482a04a
* Document last modified: 2022-08-12T19:08:31.000Z

</details>

**Comment by teoli2003** [comment]
> I think we've switched to recommend not using window. and this article recommends using `window`. This page needs some modern love.

It is a bit more complex than this. If you speak about something related to the window, you still prefix it. I would say `window.onload` for example, meaning _code to execute once the window and its content has loaded_ (that is, the UI).

But if you speak about something on the global scope, like `setInterval()`, you don't prefix it or, if you copy and paste the line (for whatever reason), into a worker or a service worker, it won't work anymore (as there is no `window`). By not prefixing it, or prefixing it with `self.` it will work in both places.

**Comment by Josh-Cena** [comment]
The point about "qualify your globals" is still fair. We could recommend `globalThis` if it helps with portability

**Comment by Josh-Cena** [comment]
Page deleted in https://github.com/mdn/content/pull/30622
