### ISSUE TITLE
GET Route is throwing a "not defined" error in view ("ejs") file

### ISSUE THREAD

**Issue by bappyasif** [mdn/content#19737]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form#controller%E2%80%94get_route

### What information was incorrect, unhelpful, or incomplete?

im trying to code this view file in ejs, and up until it was all fine, but here in this "genre_form" view file(ejs) is throwing errors for these two "variables" in "GET" route: 
* genre
* errors

so to mitigate this first variable issue, i had to pass in an extra variable from "GET" route

but for "errors" it still showing error

i will add my tried out code for this in "anything more to share" section

### What did you expect to see?

i expected to see as it is shown in expected output screenshot and not error message in console and browser

### Do you have anything more you want to share?

view file:
https://github.com/bappyasif/Intro-to-node-js/blob/master/external-resources/assignments/mdn-express/local-library-tutorial/views/genre_form.ejs

controller file with tweak for GET route: 
https://github.com/bappyasif/Intro-to-node-js/blob/b8e49afe2515c42a1300df16bcf1fdbc333872b1/external-resources/assignments/mdn-express/local-library-tutorial/controllers/genreController.js#L105

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_genre_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_genre_form/index.md
* Last commit: https://github.com/mdn/content/commit/942fe9841932612a857d787416757b706d0b3d71
* Document last modified: 2022-08-07T17:21:07.000Z

</details>

**Comment by bappyasif** [comment]
fyi: i could make this to behave as "expected output" when i did this in "GET" route: 

```js
let genre_create_get = (req, res, next) => {
    res.render("genre_form", { title: "Create Genre", genre: '', errors: '' });
};
```

now after few more correction and adjustments, its giving me same as "expected" behavior!!

perhaps there could be some sort of mention, that "controller" code needs to be adjusted for "different view" language, unless im wrong, in that case feel free to help me understand this, thanks and much appreciated :)

**Comment by hamishwillee** [comment]
@bappyasif Firstly, I'm sorry I missed this when you posted. I only just saw it now while doing a little cleanup of open issues.

I was not aware that you would need to modify the controller for different rendering engines and find this surprising. 

That said, tutorials follow quite a narrow educational path where you start from nothing and are lead through the most important things you need to know, without attempting to be exhaustive - those things are left for reference and guide material. 
This is a tutorial based around pug. While I could talk about some things you might need to do if using another rendering engine that would require a) a lot more research b) be off topic for the focus of this tutorial. 

Upshot, I don't think I will make this suggested addition.

Thank you for considering other people trying this tutorial and taking the time to make the suggestion.

**Comment by hamishwillee** [comment]
P.S. That said, if someone wanted to write an exhaustive section on using different rendering engines with Express, we might find a place for  it in one of the documents.
