### ISSUE TITLE
Issue with "Express/Node introduction": (short summary here please)

### ISSUE THREAD

**Issue by JeevanSadalge2020** [mdn/content#1976]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction

#### What information was incorrect, unhelpful, or incomplete?
The external link to a site namely "http://hotframeworks.com/" is insecure and not related.

#### Specific section or headline?
HOW POPULAR ARE NODE AND EXPRESS

#### What did you expect to see?
another link or change in content

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/server-side/express_nodejs/introduction/index.html
* Last commit: https://github.com/mdn/content/commit/3f0d70a833121be094f90194c23b3acfb19539fa
* Document last modified: 2021-01-29T00:55:21.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much @JeevanSadalge2020. This link used to be valid but the business that ran it has obviously shut down. I've removed the link in #1984.
