### ISSUE TITLE
Non functioning links in the page

### ISSUE THREAD

**Issue by Abhiram-Gullapalli** [mdn/content#19788]
### MDN URL

https://github.com/mdn/content/blob/main/files/en-us/web/events/event_handlers/index.md

### What specific section or headline is this issue about?

All links are reporting a 404 error

### What information was incorrect, unhelpful, or incomplete?

Links present in the page need to be updated 

### What did you expect to see?

Links navigating to their respective pages

**Comment by teoli2003** [comment]
You have to look at the page on the MDN website. They don't work on GitHub.
