### ISSUE TITLE
Issue with "Date()" docs: Array syntax  of Chromium/Chrome/Edge/Opera...

### ISSUE THREAD

**Issue by lp177** [mdn/content#19798]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
and also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date but it's probably not the good place for this page ?

#### What information was incorrect, unhelpful, or incomplete?

I've see today an unexpected difference between Date constructor of Firefox/Safari vs Chrome/Chromium/Edge/Opera:
`new Date(['2022-08-08','02:00:00'])` on Chrome side work well but return 'invalid date' on Firefox.
Do you think it would be relevant to specify it in this documentation ?
This seems relevant to me to prevent that it will not work on Firefox at less, to discourage its use pending potential support in Firefox.

#### Specific section or headline?

Probably in description of parameters

#### What did you expect to see?

en-US version
Array
You can also use an alternative syntax who is not currently supported on somes majors browsers like Firefox and Safari by provide array of strings with date and time separatly, exemple:
`new Date(['2022-08-08','02:00:00']);`
// Mon Aug 08 2022 02:00:00 GMT...

Fr version
Array
Vous pouvez aussi utiliser cette syntax alternative qui est actuellement non supporté sur plusieurs navigateur majeurs tel que Firefox et Safari en fournissant un tableau de chaîne de caractères contenant séparément une date et une heure, exemple:
`new Date(['2022-08-08','02:00:00']);`
// Mon Aug 08 2022 02:00:00 GMT...

#### Did you test this? If so, how?

Yes in putting the exemple code `new Date(['2022-08-08','02:00:00']);` in script or console of Firefox,Chrome,Chromium,Safari,Edge and Opera browsers

<details>
<summary>Page report details</summary>

* Folder: `fr/web/javascript/reference/global_objects/date/date`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/date/date/index.md
* Last commit: https://github.com/mdn/translated-content/commit/2d2609800f5f7d6175d753edf3ffe4c46ad1815b
* Document last modified: 2022-05-30T11:01:58.000Z

</details>

**Comment by SphinxKnight** [comment]
I'm transfering this issue over mdn/content since the English content is the reference for localized versions.

**Comment by Josh-Cena** [comment]
`new Date()` coerces it's parameter to a primitive if there's only one, and then decides if it's a string (in which case it gets parsed) or not (in which case it gets coerced again to a number and used as a timestamp). `['2022-08-08','02:00:00']` when coerced to a primitive would use `Array.p.toString()`, which joins them by commas, so it becomes `'2022-08-08,02:00:00`. That's not a standard date string so it falls into the "implementation-defined" area.

Usually we don't describe the coercion behavior, since if we tell you it accepts a string, it would be bad for you to pass a non-string anyway, even when it almost always works. Since we get an issue here, I think one sentence is fine.

**Comment by lp177** [comment]
Thank you very much for those explanations @Josh-Cena
Did you think it would be useful to specify somewhere this format managed by many browsers,
in particular for harmonization purposes?

**Comment by Josh-Cena** [comment]
It's not feasible. There's no guarantee for stable behavior and I don't even think it's documented anywhere. It's much much more diverse than you may think.

**Comment by lp177** [comment]
Ok, I'll close this issue then, thanks for your time.
