### ISSUE TITLE
NSS project pages are active and should not be archived

### ISSUE THREAD

**Issue by kjacobs-moz** [mdn/content#198]
During the transition to giithub, [NSS MDN pages](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/) were marked as archived. 

NSS has a release every four weeks, matching the Firefox release cycle. Release notes are at https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_Releases. These pages should not be archived.

**Comment by kjacobs-moz** [comment]
Note that everything under https://developer.mozilla.org/en-US/docs/Mozilla/Projects was archived, so this likely impacts other projects (at least NSPR and Necko).

**Comment by chrisdavidmills** [comment]
We'll uplift the whole archived /en-us/mozilla/projects tree to the content repo, on the understanding that the engineering team will work on moving their content off MDN in Q1 2021

Thanks @peterbe , let me know when you are done with this.

**Comment by peterbe** [comment]
@kjacobs-moz Shall we just un-archive the `mozila/projects/nss` subtree. That includes `nss/releases`.

**Comment by kjacobs-moz** [comment]
That's okay with me. It seems that most of the sub-pages from https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS went missing as well (see: `Overview of NSS`, `NSS FAQ`, etc.) Could you make sure those are restored as well? Thanks!

**Comment by saper** [comment]
Few others are affected, I am pretty sure those are active as well:

Related to NSS work:

* https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR
* https://developer.mozilla.org/en-US/docs/Mozilla/Projects/PSM (sadly just a stub page pointing to ... another Mozilla archive!)
* https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Necko

Others:

* https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey
* https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino

**Comment by WilsonKathleen** [comment]
Thanks for fixing the NSS pages!
