### ISSUE TITLE
The example code has an edge condition where it won't work

### ISSUE THREAD

**Issue by rmwiseman** [mdn/content#19837]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop

### What specific section or headline is this issue about?

Adding messages

### What information was incorrect, unhelpful, or incomplete?

The example code.

### What did you expect to see?

Since the `getSeconds` method of a `Date` object [returns the seconds component of the date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getSeconds), if the example code is run on or after 58th second past the minute (so `seconds` is 58 or 59), the code will never finish because `new Date().getSeconds() - seconds` will always be less than 2 (since `new Date().getSeconds()` will never be more than 58 or 59).

### Do you have any supporting links, references, or citations?

MDN article: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getSeconds

### Do you have anything more you want to share?

Instead of `getSeconds`, `getTime` should be used, and its value should either be divided by 1000 (to give seconds since the UNIX Epoch) or else `>= 2` should become `>= 2000`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/eventloop`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/eventloop/index.md
* Last commit: https://github.com/mdn/content/commit/d6f63f6e41146f459e21046af1c51fadb772de70
* Document last modified: 2022-08-05T15:37:08.000Z

</details>

**Comment by Josh-Cena** [comment]
Feel free to send a PR.
