### ISSUE TITLE
Issue with "String.prototype.replace()": (section link broken)

### ISSUE THREAD

**Issue by nardog** [mdn/content#1983]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

#### What information was incorrect, unhelpful, or incomplete?
The link to the section "Specifying a function as a parameter" does not lead to the section as seemingly intended. The anchor needs to be lowercase.

#### Specific section or headline?
Parameters > function (replacement)

#### What did you expect to see?
Clicking the link will jump to the section "Specifying a string as a parameter".

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/replace`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/string/replace/index.html
* Last commit: https://github.com/mdn/content/commit/934549cd98cbb101f36a09d6833773037221b9ab
* Document last modified: 2021-01-27T15:36:01.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@nardog Thank you for filling.
This was already reported in https://github.com/mdn/content/issues/1854
A fix is in the works at https://github.com/mdn/yari/issues/2763

I'm going to close this as duplicate.
Thanks again.
