### ISSUE TITLE
Autocomplete on login forms: how do browsers designate input fields to be username/password?

### ISSUE THREAD

**Issue by Sebi2020** [mdn/content#19834]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

### What specific section or headline is this issue about?

The autocomplete attribute and login fields

### What information was incorrect, unhelpful, or incomplete?

The page explains that the autocomplete attribute on "login forms" is ignored but does not explain the exact conditions under which a browser designates an input field to be username or password input field. Is it the label, is it the name? How to avoid undefined behaviour?

### What did you expect to see?

Clear conditions under which a field is recognized to be an login input.

### Do you have anything more you want to share?

Consider to disable this. It does not work as expected under all conditions.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/security/securing_your_site/turning_off_form_autocompletion`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/security/securing_your_site/turning_off_form_autocompletion/index.md
* Last commit: https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e
* Document last modified: 2022-05-17T13:23:31.000Z

</details>

**Comment by Josh-Cena** [comment]
This is addressed extensively in https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete already. It just needs a `name` or `id`.
