### ISSUE TITLE
Update background page for MV2-MV3

### ISSUE THREAD

**Issue by erosman** [mdn/content#19846]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background

### What specific section or headline is this issue about?

Entire page

### What information was incorrect, unhelpful, or incomplete?

Currently the page contains data for MV2. This has lead to confusion for some users as per the comment in the following:
`https://stackoverflow.com/questions/73440104/failing-to-export-to-background-js-from-a-common-script-under-firefox-with-mv3`

### What did you expect to see?

- Mark the page for MV2 only with a note mentioning that it will be different in MV3
- Update the page to include MV3 content

### Do you have any supporting links, references, or citations?
- [Migrating to Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/)
- [Migrating from background pages to service workers](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/)

### Do you have anything more you want to share?

Although MV3 `"service_worker": "background.js",` is supported currently by Firefox, `"type": "module"` hasn't been implemented yet. It would be good to mention that when adding MV3 content.

**Comment by mixedpuppy** [comment]
I'm looking at that page, it already includes MV3 information.  It is noted both in the description for persistent as well as the browser compatibility for persistent.  The detail page about background scripts also spells out the differences for persistent and event page backgrounds.

This is also documented in https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/

While you can pref on services worker for mv3, it is not usable at this time, nearly no API hooks have been implemented for services workers.  It is not time yet to suggest that path to developers.

The response on the stackoverflow question is wrong.  MV3 in Firefox supports background scripts as event pages, it is a major feature of MV3 in Firefox.  It does not at this time support service workers or module.

**Comment by erosman** [comment]
Thank you @mixedpuppy for the clarification.
