### ISSUE TITLE
Fix typo in findLastIndex code comment

### ISSUE THREAD

**Issue by Validark** [mdn/content#19840]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLastIndex

### What specific section or headline is this issue about?

#try_it

### What information was incorrect, unhelpful, or incomplete?

// expected output: 3  (of element with value: 30)

### What did you expect to see?

// expected output: 3  (of element with value: 130)

### Do you have anything more you want to share?

I would have submitted a PR myself, but I could not find where the code is actually hosted. Sorry about that.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/findlastindex`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLastIndex
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/findlastindex/index.md
* Last commit: https://github.com/mdn/content/commit/840db6342cecc2bd24cadf780ba7678ddcc25b1f
* Document last modified: 2022-07-23T16:30:18.000Z

</details>

**Comment by Josh-Cena** [comment]
The examples are in a separate repo:

https://github.com/mdn/interactive-examples/blob/ca3a22dd3666e30454197f81eeaa61257a3c1bdb/live-examples/js-examples/array/array-findlastindex.js#L6

If you want to send a PR there, feel free to!
