### ISSUE TITLE
Code unit example wrong

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#19858]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Code_unit

### What information was incorrect, unhelpful, or incomplete?

```js
const myString = 'ñ';
myString.length;
// 2
```

### What did you expect to see?

`'ñ'.length` is actually `1`.

### Do you have any supporting links, references, or citations?

It's obvious from trials. Seems consistent across engines.

The reasoning why it has length 2 (accents are represented separately) makes a lot of sense and I definitely remember some representations doing that. Perhaps that's just not how JavaScript encoding works? This needs some content refactor as well, not just changing the output. There's a fair chance that diacritics don't matter at all; or we need to find another character where it actually matters. Is it a font thing, or a character encoding thing?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/code_unit`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Code_unit
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/code_unit/index.md
* Last commit: https://github.com/mdn/content/commit/5db40c49e356bd7aab34af8ed17e28dd3c05712b
* Document last modified: 2022-01-11T01:44:51.000Z

</details>

**Comment by wbamberg** [comment]
It is I think an encoding thing. You can do this:

```js
const string = '\u006E\u0303'; 
console.log(string); // "ñ"
console.log(string.length); // 2
```

...so you need to construct the string in a particular way. But I'm not sure if there is a less laboured way to do it!

**Comment by Josh-Cena** [comment]
I remember there are two ways to represent accented characters: one as single Unicode, one as pairs of diacritic + base character. I think we need to actually call that out, or use a character that does not have a single designated code point.

**Comment by wbamberg** [comment]
Calling it out is a good idea. There is some stuff on it here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize#description .
