### ISSUE TITLE
Missing a 'multiple' example

### ISSUE THREAD

**Issue by estelle** [mdn/content#19852]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/animation

### What specific section or headline is this issue about?

examples

### What information was incorrect, unhelpful, or incomplete?

would be useful to have an example of using the shorthand for multiple animations declared at once.

### What did you expect to see?

more complex example to show real life usage.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/animation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/animation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/animation/index.md
* Last commit: https://github.com/mdn/content/commit/3cf6e9bc8ca90917d570a732282242cd704b1dce
* Document last modified: 2022-08-19T08:54:56.000Z

</details>

**Comment by estelle** [comment]
Also, the example that is there is a BAD example. You never want to animate box model properties; it's bad for performance. Animating background position would be much better. A second animation could be background color (showing thru the gradient)

**Comment by najmiehsa** [comment]
@estelle hi^^
I want to work on this issue. Do I need to add the examples here https://github.com/mdn/interactive-examples?
I am not sure about the section.
