### ISSUE TITLE
browser object not working

### ISSUE THREAD

**Issue by Me-Debarghya** [mdn/content#19882]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/getAll

### What information was incorrect, unhelpful, or incomplete?

browser object not working

### What did you expect to see?

browser object not working

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/permissions/getall`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/getAll
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/permissions/getall/index.md
* Last commit: https://github.com/mdn/content/commit/1d0e4c0b516be65384388ffd5c6d0f0580635af4
* Document last modified: 2022-04-21T05:20:11.000Z

</details>

**Comment by rebloor** [comment]
@Me-Debarghya it seems that you may be having a technical issue rather than suggesting a documentation update. You should be able to get assistance from the [Add-ons forum](https://discourse.mozilla.org/c/add-ons).
