### ISSUE TITLE
The  <img srcset> source  image only one image from path folder ,why it is include two filename

### ISSUE THREAD

**Issue by LynchMuse** [mdn/content#19907]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

### What specific section or headline is this issue about?

Resolution switching: Different sizes

### What information was incorrect, unhelpful, or incomplete?

<img srcset="elva-fairy-480w.jpg 480w,
             elva-fairy-800w.jpg 800w"
     sizes="(max-width: 600px) 480px,
            800px"
     src="elva-fairy-800w.jpg"
     alt="Elva dressed as a fairy">
I was so confused that there is no image called "Elva-fairy-480.jpg" in path folder after I checked source via chrome inspector. Is that size just rendered by browser or no matter what file name that I give it and just with a width value(480w) will display on page ? 

### What did you expect to see?

I expect to see an image called "elva-fairy-480w.jpg" will in path folder on source tab
<img width="226" alt="Screen Shot 2022-08-24 at 10 19 48 AM" src="https://user-images.githubusercontent.com/46038653/186304150-bec7c86c-1f86-4699-9da0-b5042de1b754.png">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.md
* Last commit: https://github.com/mdn/content/commit/c482f34f48d447bfb9ee76b76013dae3b66f45c7
* Document last modified: 2022-08-20T05:15:25.000Z

</details>

**Comment by wbamberg** [comment]
I think the media condition for your browser is choosing the 800 version, so that's the only one being requested, so that's the one that shows up in the devtools. If you look at the files on disk there is a 480 version: https://github.com/mdn/learning-area/tree/main/html/multimedia-and-embedding/responsive-images , and you can persuade the browser to load that one using the responsive design mode in Firefox.

Isn't that what we would expect to see here?

**Comment by LynchMuse** [comment]
> I think the media condition for your browser is choosing the 800 version, so that's the only one being requested, so that's the one that shows up in the devtools. If you look at the files on disk there is a 480 version: https://github.com/mdn/learning-area/tree/main/html/multimedia-and-embedding/responsive-images , and you can persuade the browser to load that one using the responsive design mode in Firefox (I assume Chrome has something similar but I don't know how to find it).
> 
> Isn't that what we would expect to see here?

Thank you for your answer.But I asked my friend to check the image and he found it in Chrome source panel.anyway I'll ignore that thank you 
![2022-08-25 12 30 43](https://user-images.githubusercontent.com/46038653/186575345-db6cae08-4ce9-4baa-9f4c-36d860c569d4.jpg)

**Comment by wbamberg** [comment]
I think this can be closed, since it's not clear what the content issue is here.
