### ISSUE TITLE
Documentation for CSP: frame-src should mention frame-ancestors and vice versa

### ISSUE THREAD

**Issue by alexandroid** [mdn/content#19938]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src

### What information was incorrect, unhelpful, or incomplete?

No notion how `frame-src` relates to `frame-ancestors` and when one should be used vs the other.

### What did you expect to see?

Both `frame-src` and `frame-ancestors` pages should cross-link to each other and contrast their purpose - what is the difference between the two and when each of them should be used.

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/a/54395977/49678

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/frame-src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/frame-src/index.md
* Last commit: https://github.com/mdn/content/commit/fd4d0f4428adedfe54bd36d78d92d62b39bca5c8
* Document last modified: 2022-07-13T20:41:11.000Z

</details>

**Comment by alexandroid** [comment]
That was fast! Thank you very much!

**Comment by sideshowbarker** [comment]
@alexandroid Thank you for having caught this and taken time to report it
