### ISSUE TITLE
Edits for the window.pageYOffset property and related content

### ISSUE THREAD

**Issue by ghost** [mdn/content#19933]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY

### What information was incorrect, unhelpful, or incomplete?

I need to edit the pages for the 
https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY
https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollx
 and 
https://developer.mozilla.org/en-US/docs/Web/API/Window/pageXOffset
https://developer.mozilla.org/en-US/docs/Web/API/Window/pageYOffset

This is related to https://github.com/mdn/content/pull/19690
 and Issue https://github.com/mdn/content/issues/18735

### What did you expect to see?

Unintentionally I added some parts and it got merged. I need to verify the facts and do some edits for these pages.

**Comment by jpmedley** [comment]
You can just open another PR.

**Comment by najmiehsa** [comment]
Ok, I Open another PR for this issue.

**Comment by Josh-Cena** [comment]
We'll track this in https://github.com/mdn/content/issues/18735
