### ISSUE TITLE
Unreachable `source` tag in example

### ISSUE THREAD

**Issue by benmccann** [mdn/content#19944]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

### What specific section or headline is this issue about?

The srcset attribute

### What information was incorrect, unhelpful, or incomplete?

The example:
```
<picture>
  <source srcset="logo-768.png, logo-768-1.5x.png 1.5x">
  <source srcset="logo-480.png, logo-480-2x.png 2x">
  <img src="logo-320.png" alt="logo">
</picture>
```

It doesn't seem to me like it'd make sense to include both of those `source` tags. How would the browser choose to display `logo-480.png` over `logo-768.png`?

### What did you expect to see?

If there are multiple `source` tags there should be some way to select between them such as a `media` or `type` attribute

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/picture`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/picture/index.md
* Last commit: https://github.com/mdn/content/commit/b0f52c874e2598703c10f8598a83b5f92f23f0ac
* Document last modified: 2022-07-28T02:10:01.000Z

</details>

**Comment by DevRickLin** [comment]
I found [this](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_same_size_different_resolutions). It said the choice between them was implicit (made by the browser). 

> you can allow the browser to choose an appropriate resolution image by using srcset with x-descriptors and without sizes

**Comment by benmccann** [comment]
That example has just a single `srcset` with two images, which is fine. The problem here is that we're specifying two overlapping `srcset`s.

It would be fine if the example just had:
```
  <source srcset="logo-768.png, logo-768-1.5x.png 1.5x">
```
Or just had:
```
  <source srcset="logo-480.png, logo-480-2x.png 2x">
```

But I don't think it makes sense to have both.

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/19966
