### ISSUE TITLE
Ambiguous code example

### ISSUE THREAD

**Issue by c2u5hed** [mdn/content#19963]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Division_assignment

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

The code example in the “Try it” section is ambiguous. In particular, the code uses the division assignment operator as follows: 

```
let a = 3
console.log(a /= 2)
// expected output: 1.5
```

While correct, the `a /= 2` expression in the `console.log()` method is no different from the `a / 2` expression in terms of the result. It does not let the reader understand that the value of `a` also changes when the expression is called. 

### What did you expect to see?

I expected to see a clearer example, say something like this:

```
let a = 6
a /= 2
console.log(a)
// expected result: 3
```

To my mind, this example will surely let the reader understand that the value of `a` is changed when the `a /= 2` expression is called.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/division_assignment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Division_assignment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/division_assignment/index.md
* Last commit: https://github.com/mdn/content/commit/4e55ef8d3618f047997d8670fce06b838de6a17b
* Document last modified: 2022-03-25T23:14:02.000Z

</details>

**Comment by teoli2003** [comment]
I've fixed it. (I made an error, and there is no PR), but this should be fixed in production very soon.

Here is the commit: https://github.com/mdn/interactive-examples/commit/c6b5dc61c6b558c58091b8d974e752e64fc040d2

**Comment by teoli2003** [comment]
Thanks for the report!

**Comment by RUS29TAM** [comment]
Great job Jan. Congratulations.
