### ISSUE TITLE
Separate out upload streams in fetch()

### ISSUE THREAD

**Issue by annevk** [mdn/content#1996]
It's an unsupported feature at the moment, `ReadableStream` will be stringified instead which is rather useless. Hopefully it'll be improved later this year.

**Comment by chrisdavidmills** [comment]
Affected page: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch (possibly others too)

Other info: We should probably update this content to separate out "upload streams" as currently no browser implements that but the documentation somewhat suggests they do (if you pass a ReadableStream object to fetch() today it'll stringify to [Object ReadableStream] or some such)

**Comment by Ryuno-Ki** [comment]
@DannyMoerkerke Would you take a look at it?
I recall your demo at https://github.com/DannyMoerkerke/instant-multi-page-app
I _think_ it utilised ReadableStreams …

**Comment by DannyMoerkerke** [comment]
@Ryuno-Ki yes the demo uses ReadableStream. 
But what is your question?

**Comment by Ryuno-Ki** [comment]
> as currently no browser implements that but the documentation somewhat suggests they do (if you pass a ReadableStream object to fetch() today it'll stringify to [Object ReadableStream]

Can you confirm this? I haven't had a chance to test your code myself, yet.
But I'd doubt it would work if the ReadableStream gets stringified in this way …

**Comment by DannyMoerkerke** [comment]
This is about upload stream whereas I use the `ReadableStream` that is part of the `Response` object, not the `Request` object.

**Comment by Ryuno-Ki** [comment]
Oh, okay.

**Comment by Josh-Cena** [comment]
Should be fixed by #17849 and https://github.com/mdn/browser-compat-data/pull/18155
