### ISSUE TITLE
Issue with "Web Periodic Background Synchronization API":  Typo in example

### ISSUE THREAD

**Issue by AleksanderBodurri** [mdn/content#1998]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Periodic_Background_Synchronization_API

#### What information was incorrect, unhelpful, or incomplete?
The example for the use of this api registers a tag as "fetch-news" and later refers to it as "get-latest-news". I believe these names should be the same. If necessary I can open a PR to fix this.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Web_Periodic_Background_Synchronization_API#requesting_a_periodic_background_sync

https://developer.mozilla.org/en-US/docs/Web/API/Web_Periodic_Background_Synchronization_API#verifying_a_background_periodic_sync_by_tag

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/web_periodic_background_synchronization_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Periodic_Background_Synchronization_API
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/web_periodic_background_synchronization_api/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by chrisdavidmills** [comment]
> If necessary I can open a PR to fix this.

I think you're right, @AleksanderBodurri . Opening a PR would be much appreciated!
