### ISSUE TITLE
Comment on the example for installing express on Heroku: Heroku will phase out free plans for dynos, and shut down free dynos from November 28, 2022

### ISSUE THREAD

**Issue by equeslevi** [mdn/content#19987]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment

### What specific section or headline is this issue about?

Example: Installing LocalLibrary on Heroku

### What information was incorrect, unhelpful, or incomplete?

> Heroku has a [free tier](https://www.heroku.com/pricing) that is really free (albeit with some limitations).

### What did you expect to see?

I stumbled upon this as I was looking for an alternative to Heroku after learning that they will be phasing out the said tier.

### Do you have any supporting links, references, or citations?

As per heroku's [blog](https://blog.heroku.com/next-chapter), they will be phasing out free plans in heroku's dynos. Here is the statement quoted from the Heroku's blog

> Our product, engineering, and security teams are spending an extraordinary amount of effort to manage fraud and abuse of the Heroku free product plans. In order to focus our resources on delivering mission-critical capabilities for customers, we will be phasing out our free plan for Heroku Dynos, free plan for Heroku Postgres, and free plan for Heroku Data for Redis®, as well as deleting inactive accounts.

>Starting October 26, 2022, we will begin deleting inactive accounts and associated storage for accounts that have been inactive for over a year. Starting November 28, 2022, we plan to stop offering free product plans and plan to start shutting down free dynos and data services. We will be sending out a series of email communications to affected users.

>We will continue to provide low-cost solutions for compute and data resources: Heroku Dynos starts at $7/month, Heroku Data for Redis® starts at $15/month, Heroku Postgres starts at $9/month. See [Heroku Pricing Information](https://www.heroku.com/pricing) for current details. These include all the features of the free plans with additional certificate management and the assurance your dynos do not sleep to help ensure your apps are responsive.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/deployment/index.md
* Last commit: https://github.com/mdn/content/commit/51f2cde58fff4a44242577b2540bdfdfc525dda4
* Document last modified: 2022-08-13T04:30:09.000Z

</details>

**Comment by MuratY26** [comment]
Hi, will the exercise be updated with a different PaaS? Since i still have 20 days before free services of Heroku shut down, should i complete the exercise?

**Comment by hamishwillee** [comment]
@MuratY26 Whether or not you complete the exercise is up to you. Personally I would - you have a short window to try out heroku works without paying. Many of the approaches it uses for setup are similar to other services. 

As to the bigger question, the answer is "I am aware of this problem and I am not yet sure how we will solve it".

Essentially "someone" will need to review the available services and see if any have a free tier we can use instead. There are various options with "free credits to start with" but those are a pain because I have already used mine, and so when it comes time to retest/update the instructions it becomes difficult to validate them.

Have you looked at any of the services and do you have an opinion?

**Comment by hamishwillee** [comment]
Note, will probably use https://railway.app/ - MDN core team has been looking at alternatives and this seems to be one of the better options.
