### ISSUE TITLE
Issue with "Introduction to HTML": Escaping HTML tags (lacking information)

### ISSUE THREAD

**Issue by 552020** [mdn/content#2000]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML

#### What information was incorrect, unhelpful, or incomplete?

Being a HTML/CSS/Javascript lerner I was wondering how the topic is presented in MDN. But I couldn't find nothing in the tutorial. I first googled it  ("MDN html tags escape"). The most relevant page that show up is this one.:https://developer.mozilla.org/en-US/docs/Glossary/Entity. Then I looked in the HTML-tutorial. I would  have expected  to find the information between "Getting started with HTML" and "HTML fundamentals". But I couldn't find anything. I don't know I looked hard enough. 

In the snippets of the section Quotation in "Advanced Text-formatting" the escaping-strings are used many times, but not explained (if I didn't oversee the explanation). 

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML

#### What did you expect to see?

An introduction to the escaping strings for the reserved html tags. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/html/introduction_to_html/index.html
* Last commit: https://github.com/mdn/content/commit/775f38d46298d75b700caef7dd8685d12632e827
* Document last modified: 2021-01-22T11:51:09.000Z

</details>

**Comment by chrisdavidmills** [comment]
Hi there @552020 !

When you say "tags", am I right in thinking that you are talking about reserved syntax characters, like `<` being escaped to "&lt;"? In which case, you are talking about entity references, which we cover here: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#entity_references_including_special_characters_in_html

If you are talking about something else, then sorry for the misunderstanding, and let's keep talking ;-)

**Comment by 552020** [comment]
Hello @chrisdavidmills, yes! You're right! I meant what you say. Probably I was misled by the high (but proper) register of the title of the section while looking more for strategies to 'escape' these "entities" while citing html in html. My bad! At the end I found an online HTML _entity_ encoder/decoder. But I also understand that these entities are not 'escaped' the way they are escaped in JS but more 'translated'.

**Comment by chrisdavidmills** [comment]
@552020 I dunno, I still think it is quite similar — in both cases you need to escape certain characters to avoid making the code error. In JS the errors are more explicit, whereas often in HTML you'll get a silent failure but the rendering might not turn out like you expected.

Glad we figured out this one anyway; good luck with your further study!
