### ISSUE TITLE
Issue with "Uint8Array" (and other TypedArray concrete class pages): missing inheritance from %TypedArray%

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#20019]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array

### What information was incorrect, unhelpful, or incomplete?

These pages mention things like `Uint8Array.prototype.copyWithin()`. There's no such thing—only `%TypedArray%.prototype.copyWithin()`. There's no need to repeat these methods on every constructor's page—just include the inheritance from `%TypedArray%` in the left sidebar, like we do for Web API.

### What did you expect to see?

Remove the redundant mentions of typed array methods on every concrete class's page—there's only one such method in JavaScript, not one per typed array class.

### Do you have any supporting links, references, or citations?

<img width="671" alt="image" src="https://user-images.githubusercontent.com/55398995/187012090-586cdc0c-21d7-4b74-b66f-f667014b2adf.png">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/uint8array`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/uint8array/index.md
* Last commit: https://github.com/mdn/content/commit/2d6d6a1d9f8ba2073c9f8e1bbc6b4e20204fb53c
* Document last modified: 2022-08-07T06:13:17.000Z

</details>

**Comment by Josh-Cena** [comment]
I'm pretty sure this has been brought up in the past but I can't find the thread anywhere now. Inheritance information in the JS references is incredibly unuseful—literally everything says "inherits from `Function`", but that's just the constructor, not the actual class.

**Comment by Phosra** [comment]
Appears related to https://github.com/mdn/content/discussions/18002, but you're arguing for the sake of correctness, yes?

**Comment by Josh-Cena** [comment]
Yes, the fact that `Uint8Array.prototype.copyWithin()` is mentioned at all. It should just be shown in the left sidebar as inheritance.

**Comment by Phosra** [comment]
Got it!

Furthermore, note that even the instance properties are accessors, implementated on `%TypeArray%.prototype`, so everything besides the constants and constructors, are inherited.

The constants are each loaded on the individual `<ConcreteTypedArray>.prototype`.
