### ISSUE TITLE
Video player styling basics

### ISSUE THREAD

**Issue by tanishqdaiya** [mdn/content#2002]
There's an Incorrect Code in there. The player doesn't even show up and the JS shows some errors like videoControl is not defined kind of thing.

**Comment by chrisdavidmills** [comment]
@tanishqdaiya what page, or example are you talking about? Can you give me the URL?

Thanks!

**Comment by tanishqdaiya** [comment]
> @tanishqdaiya what page, or example are you talking about? Can you give me the URL?
> 
> Thanks!

https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Video_player_styling_basics

**Comment by tanishqdaiya** [comment]
> @tanishqdaiya what page, or example are you talking about? Can you give me the URL?
> 
> Thanks!

Actually the given code is not working. The live demo and all is ok.

**Comment by chrisdavidmills** [comment]
> > @tanishqdaiya what page, or example are you talking about? Can you give me the URL?
> > Thanks!
> 
> Actually the given code is not working. The live demo and all is ok.

OK, so it sounds like you are saying that the code listing as it appears on the page doesn't work, but the live example does.

Have you got any idea what part of the code is not working? Or to put it another way, what bit of code started to cause problems?

Maybe you could go through your version and compare it to the source of the live version to see if you can see where it differs?

Have you got your version available online  anywhere for us to check it out?

**Comment by Rumyra** [comment]
@tanishqdaiya is this still an issue you are experiencing?

**Comment by tanishqdaiya** [comment]
https://codepen.io/tanishqdaiya/pen/poeQzqx

This is the codepen, blindly pasted... It's not ready for use is what I can see

**Comment by Rumyra** [comment]
Hi @tanishqdaiya it looks like you need to add background images - as per the information on the MDN page:

>For example, the play/pause button has the following background image definitions (the full base64 strings have been omitted for brevity):

On line 52 and 56 of the CSS in your codepen. If the base64 urls were complete, or an image were used, this would fix your issue 👍
