### ISSUE TITLE
Issues with the examples

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#20039]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

### What information was incorrect, unhelpful, or incomplete?

The examples "Try it" and "A simple <iframe>" do not work.
I get a white page

### What did you expect to see?

that the results displayed in the lesson are displayed

### Do you have anything more you want to share?

I use the last version of Firefox

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/iframe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/iframe/index.md
* Last commit: https://github.com/mdn/content/commit/45a09cc1e6a703a1eb5470f182de3f30589731ed
* Document last modified: 2022-03-29T13:36:25.000Z

</details>

**Comment by teoli2003** [comment]
Both work for me… Which browser are you using? Also do you an adblocker or similar that could interfere?

**Comment by DomOBU** [comment]
Thank you for your reply.
The problem was indeed due to an adblocker.

**Comment by Josh-Cena** [comment]
Okay, closing in that case since it's not our content's fault. Adblocks are constant headaches for websites these days—seems like more headache than ads themselves.

**Comment by DomOBU** [comment]
Having been absent I come back to this point with delay.
In the 2 exercises the title is not displayed.

In the lesson "title" it says "The <title> element is always used within a page's <head> block."
In the "iframe" lesson "title" does not appear in the list of attributes.

In the 2 excercises, is using "title" as an attribute of "iframe" an unauthorized extension?
