### ISSUE TITLE
Links to https://drafts.css.org are intermittently broken

### ISSUE THREAD

**Issue by 12Me21** [mdn/content#20043]
Recently i've noticed that links to `https://drafts.csswg.org/<spec>` have been broken for several hours at a time.
(More details at https://github.com/mdn/browser-compat-data/issues/14887 and https://github.com/w3c/csswg-drafts/issues/6528)
Perhaps MDN pages should link to `https://www.w3.org/TR/<spec>/` instead, when possible?

**Comment by teoli2003** [comment]
We never link to TR, they are always outdated. We have to wait for the csswg to solve this problem.
