### ISSUE TITLE
Document Atomics.waitAsync

### ISSUE THREAD

**Issue by foolip** [mdn/content#2005]
`Atomics.waitAsync` was [shipped in Chrome 87](https://groups.google.com/a/chromium.org/g/blink-dev/c/Kprh_FIyj74/m/ZG58hpO1AwAJ). It needs to be [added to BCD](https://github.com/mdn/browser-compat-data/issues/8930) and documented on MDN.

cc @jpmedley 

MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Comment by Elchi3** [comment]
I've sent https://github.com/mdn/content/pull/15433 which may benefit from a reviewer who knows stuff about shared memory.
