### ISSUE TITLE
Iteration on view page seems to be wrong.

### ISSUE THREAD

**Issue by enticingcode** [mdn/content#20067]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_author_form

### What specific section or headline is this issue about?

Create Author Form

### What information was incorrect, unhelpful, or incomplete?

Under the create author form, for error handling I attempted to follow through with the tutorial but was met with a "for in" loop which caused my listed of errors to appear empty. 

` if errors
    ul
      for error in errors
        li!= error.msg`

here when I changed from for in, to a for of loop, I achieved the results I needed in order to display an <li> element displaying the correct `error.msg` functionality. 

### What did you expect to see?

I just want to make sure that I'm not missing something here. Would for in loop work and am I using it incorrectly? I would greatly appreciate your feedback! :) thank you for taking the time to read this.  (Side note: I am using EJS instead of Pug, would that have an effect?)

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_author_form

### Do you have anything more you want to share?

I'd greatly appreciate any feedback to the for in loop method and how it works to display, considering when I console log it, it displays the indices of the array of errors I get in  return, but when using the for of loop i can actually get the object dot notation of error.msg.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_author_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_author_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_author_form/index.md
* Last commit: https://github.com/mdn/content/commit/9e74548012ae11f6eecec4ed65fcf00b8d2f417e
* Document last modified: 2022-08-11T13:27:21.000Z

</details>

**Comment by hamishwillee** [comment]
The tutorial is correct use of pug for iterating the errors - see  https://pugjs.org/language/iteration.html
EJS is not pug so you can't expect it to work the same.

I'm going to close this because it is not a defect. For support you might want to try EJS forums.
