### ISSUE TITLE
`HTMLElement.blur()` needs better example

### ISSUE THREAD

**Issue by kidonng** [mdn/content#20080]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/blur

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The example is unhelpful. The input will lose focus if one clicks the outside, whether there is a `blur()` call or not.

### What did you expect to see?

A better example could be:

```html
<input type="text" id="myText" value="Sample Text">
<br><br>
<button type="button" onclick="focusInput()">Click me to gain focus</button>
```

```js
function focusInput() {
  document.getElementById('myText').focus();
  // The input will lose focus after 3 seconds
  setTimeout(() => {
    document.getElementById('myText').blur();
  }, 3000)
}
```

**Comment by teoli2003** [comment]
Do you want to create a PR so that we can review it?

**Comment by kidonng** [comment]
Sorry if it's something obvious, but I could not find the source of `{{ EmbedLiveSample('Remove_focus_from_a_text_input') }}` (or else I would have already submitted a PR).

**Comment by teoli2003** [comment]
The source is in the page itself, it is the cause above, in the eponymous section.
