### ISSUE TITLE
Case issues with content

### ISSUE THREAD

**Issue by DarthAutocrat** [mdn/content#20085]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation

### What information was incorrect, unhelpful, or incomplete?

Throughout the site, there is an issue with the "case" used for APIs etc.

The example URL provided 
(https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation)
demonstrates the issue several times.

1) The URL "/NetworkInformation" - why does it start with an uppercase?
2) The example properties "NetworkInformation.saveData" - why does it start with an uppercase N?

It's "networkInformation", not "NetworkInformation".

(I know it seems tiny - but for anyone copying/pasting, 
and those citing it without knowing better etc., it's a pain)
it's a pain

### What did you expect to see?

Correct casing for APIs etc.
(no initial uppercase letter as it's camelCase!)

### Do you have anything more you want to share?

Thank you!

**Comment by teoli2003** [comment]
Interfaces start with capital letters. They are not variable names.
