### ISSUE TITLE
Animation.commitStyles() remains unclear, example seems pointless

### ISSUE THREAD

**Issue by ygoe** [mdn/content#20086]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Animation/commitStyles

### What information was incorrect, unhelpful, or incomplete?

The description of this method remains unclear to me. It looks like it should be used to remove a forwards-fill animation when it's done and persist its final style in the element itself. But that's not what I can observe. This method, when called immediately after starting the animation, will persist the initial or current style in the element, not the final state. When deferring that call until after the animation has ended, the final style is persisted. But in any way, the animation still remains active. Something is missing here. Why should I call this method in the way shown in the example? It seems pointless to me.

### What did you expect to see?

I need a reliable way to persist the animation's final style and remove the animation when it's finished and has not been aborted or reversed while playing. Can I use this method or do I need something else?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/animation/commitstyles`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Animation/commitStyles
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/animation/commitstyles/index.md
* Last commit: https://github.com/mdn/content/commit/810d65ba6245b16b46ed352458ed1fee8dec359f
* Document last modified: 2022-07-23T10:49:03.000Z

</details>

**Comment by ygoe** [comment]
Calling that method right at the beginning will set the initial style on the element, but since animations intransparently override styles (you just won't find them in the Inspector's rules list, and even the animations tab won't tell you what the animation is about, only that there is one and how far it has played), that's a useless operation. The whole example on this page has no function.

PS: The animation is also not removed despite explained here: https://developer.mozilla.org/en-US/docs/Web/API/Animation#automatically_removing_filling_animations Something is wrong with the documentation or Firefox' implementation of animations.

I also can't find a way to remove an animation after it has been created. I see that there's a `remove` event on the animation instance, but it doesn't explain how it could be triggered. That page remains a mystery as well. I'd really like to keep using animations but it's not clear how to do that. Plain old CSS transitions were a lot more predictable and after all simpler to use, but not as powerful.

**Comment by ninevra** [comment]
See also https://github.com/w3c/csswg-drafts/issues/5394.

**Comment by hacktivista** [comment]
Apparently the description is wrong when it says "It will cause the end styling state to be written to the element being animated", since it writes the current style of the animation.

In order to write the end state you would need to do something like the following:

```javascript
const anim = document.body.animate(
  { ... },
  { duration: 1000, fill: 'forwards' }
);
await anim.finished;
anim.commitStyles();
```
