### ISSUE TITLE
[Not Release] [CSS] COLRv1 fonts supported

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#20106]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Needs addition to experimental features page.

See Other for further research.

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1740530

## Other

So this allows you to apply colours, gradients etc to a font. 

This is behind `gfx.font_rendering.colr_v1.enabled`. So minimally add to experimental features.

- Useful overviews here: 
  - https://developer.chrome.com/blog/colrv1-fonts/
  - https://css-tricks.com/colrv1-and-css-font-palette-web-typography/
- Spec is here: https://docs.microsoft.com/en-us/typography/opentype/spec/ "OpenType® Specification Version 1.9" 
- Cool easy test for what is supported here: https://pixelambacht.nl/chromacheck/

So this basically is support for using the colr v1 fonts in `@font-face` and `FontFace (i.e. using fonts that have color gradients etc). From the point of our existing docs we don't say very much about the different font tables and types of fonts and I don't think we need to. However we do need to indicate support for these features.

What has to be done is add the supported tables like colrv1 to BCD. Not all of them though, just the ones that can be feature checked in  the  `@font-face` src: descriptor's `tech(...)` syntax that FF is adding in #19833. This makes sense because tech() provides a fallback to a small subset, which are likely therefore to be the ones that have compatibility issues.

I don't think there is any particular need for docs on this though.

**Comment by hamishwillee** [comment]
@Rumyra I've done the basic review and converted to an issue. In summary, this is closely related to #19833. Support for the feature is behind a pref. 

I'll probably take the BCD part of this but let's see how we go next month for the whole thing.

**Comment by Rumyra** [comment]
Yeh 💯 @hamishwillee - with the experimental features such as this I wonder whether the current month task is bcd & experimental features rel note - and we then put the issue back into the backlog (possibly close it temporarily) until it comes back to stable feature

**Comment by hamishwillee** [comment]
> until it comes back to stable feature

Possibly. Depends a bit on `@font-face src: descriptor's tech(...)` feature - if that goes in "not" behind pref we might as well do the lot. Also sometimes it is good to document the stuff already in chrome because then adding the firefox stuff later is easy on shipping. Depends on bandwidth at the time.

Anyway, let's see how it goes :-)

**Comment by hamishwillee** [comment]
Status

- [ ] BCD -
  - [ ] https://github.com/mdn/browser-compat-data/pull/17645 
  - [ ] extend to FontFace?
- [ ] Docs
- [ ] Experimental features
- [ ] Dev-docs complete
