### ISSUE TITLE
Document ::-moz-meter-bar

### ISSUE THREAD

**Issue by chances** [mdn/content#20100]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-meter-bar

### What information was incorrect, unhelpful, or incomplete?

MDN is missing documentation on Firefox's support of `::-moz-meter-bar`.

### What did you expect to see?

MDN is missing documentation on Firefox's support of `::-moz-meter-bar`.

### Do you have any supporting links, references, or citations?

https://css-tricks.com/html5-meter-element

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_doublecolon_-webkit-meter-bar`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-meter-bar
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_-webkit-meter-bar/index.md
* Last commit: https://github.com/mdn/content/commit/9b1f7aa6cb8d0479b4df91a3e2249003a8a863f1
* Document last modified: 2022-08-17T05:30:54.000Z

</details>

**Comment by chances** [comment]
@estelle This issue was in fact not resolved with #20676, especially as [you described that fact](https://github.com/mdn/content/pull/20676#issuecomment-1252913573) in the referenced PR.

**Comment by estelle** [comment]
> @estelle This issue was not resolved with #20676, especially as [you described that fact](https://github.com/mdn/content/pull/20676#issuecomment-1252913573) in the referenced PR.
My mention of this in that PR closed this. Reopening.

**Comment by chances** [comment]
> `::-meter-bar` [is being deprecated](https://github.com/mdn/browser-compat-data/issues/23840) in favour of `:state(meter-bar)`.

That only applies to Chromium browsers. This issue is specifically regarding the equivalent pseudo-class in Firefox.

Does the Firefox team plan to deprecate `::-moz-meter-bar` in favor of `:state(meter-bar)`?
