### ISSUE TITLE
Issue with "AbortController.abort()": Misleading error description caused by abort()

### ISSUE THREAD

**Issue by gorankami** [mdn/content#2010]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort

#### What information was incorrect, unhelpful, or incomplete?

At the bottom of Examples, a note is stated:
"Note: When abort() is called, the fetch() promise rejects with an AbortError."

This was a bit misleading for me because `abort()` throws `DOMException` and the `name` property is indeed `AbortError`, therefore I suggest a clearer description.

#### Specific section or headline?
Bottom of "Examples" Headline.

#### What did you expect to see?

"Note: When abort() is called, the fetch() promise rejects with error of type DOMException, with name AbortError."

#### Did you test this? If so, how?

I have run an example that would look like this:

``` js
...
 
  const controller = new AbortController();
  setTimeout(() => {
    controller.abort();
  }, 1000);

  return fetch(url, {
    signal: controller.signal,
  })
    .catch((error) => {
      if (error instanceof DOMException && error.name === "AbortError"){
        console.log("Aborted with AbortController")
      } else {
        console.log("Other error");
      }
    })
...
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/abortcontroller/abort`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/abortcontroller/abort/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this
