### ISSUE TITLE
Possibly missing information in WebRTC config section about certificates

### ISSUE THREAD

**Issue by martinpetrovaj** [mdn/content#20134]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection

### What specific section or headline is this issue about?

Using certificates

### What information was incorrect, unhelpful, or incomplete?

Section contains visible todo comment "<<<--- add link to information about identity --->>>"

### What did you expect to see?

The comment should either be hidden or said link should be provided

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/rtcpeerconnection/rtcpeerconnection`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/rtcpeerconnection/rtcpeerconnection/index.md
* Last commit: https://github.com/mdn/content/commit/59d036cd686d9715c1cb9f3157a2a8545ea13882
* Document last modified: 2022-06-11T04:12:24.000Z

</details>

**Comment by wbamberg** [comment]
This comment will be deleted in https://github.com/mdn/content/pull/20099/files#diff-41fb44290adb4b22806b7a687eb211d704509f8272b9ce1ebbbc44cab5ac3e90 .

**Comment by Josh-Cena** [comment]
This note has been removed. Since I don't think anyone knows what needs to be added anyway, it may be best to close this.
