### ISSUE TITLE
accessing localStorage raises exception when all cookies disabled

### ISSUE THREAD

**Issue by verhovsky** [mdn/content#20176]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

### What specific section or headline is this issue about?

mention that disabling all cookies causes an exception when accessing localstorage

### What information was incorrect, unhelpful, or incomplete?

When the user has all cookies disabled, trying to access the Window.localStorage will raise this error:

```
Uncaught (in promise) DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
```

I didn't know that accessing localstorage/sessionstorage and not capturing this exception would break my site for privacy-conscious users.

### What did you expect to see?

A note explaining this.

### Do you have any supporting links, references, or citations?

https://blog.tomayac.com/2022/08/30/things-not-available-when-someone-blocks-all-cookies/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/localstorage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/localstorage/index.md
* Last commit: https://github.com/mdn/content/commit/cc1f5c3bd1a9976a0668eeee016f6afc144533b0
* Document last modified: 2022-06-03T04:32:25.000Z

</details>

**Comment by johnmandrus** [comment]
I can work on this one.

**Comment by johnmandrus** [comment]
I can support this one.

**Comment by hamishwillee** [comment]
Thanks @johnmandrus - assigned to you!
