### ISSUE TITLE
time.setMonth(8) isEqual time.setMonth(9) 

### ISSUE THREAD

**Issue by xiaoyongchen** [mdn/content#20170]
today is '2022-08-31';

const time = new Date();
undefined
time.setMonth(8);
1664627025471
time.getMonth();
9
const time1 = new Date();
undefined
time1.setMonth(9);
1667219112264
time1.getMonth();
9

**Comment by xiaoyongchen** [comment]
> Hi! When you use `setMonth(8)`, it actually sets the date to September, because months are 0-indexed. However, September doesn't have 31st, so it wraps to October 1st instead. Then when you call `setMonth(9)`, it stays in October. This is already mentioned in the [description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMonth):
> 
> > The current day of month will have an impact on the behavior of this method. Conceptually it will add the number of days given by the current day of the month to the 1st day of the new month specified as the parameter, to return the new date. For example, if the current value is 31st January 2016, calling setMonth with a value of 1 will return 2nd March 2016. This is because in 2016 February had 29 days.

it's work

  const time = new Date('2022-08');

  time.getMonth(); // 7

  time.setMonth(8); // 1661990400000

  time.getMonth(); // 8

  // or dayjs
  time = new Date(dayjs(startDate).add(1, 'month').valueOf());

**Comment by Josh-Cena** [comment]
`new Date("2022-08")` creates a date of August 1st, so it does not suffer from overflowing and wrapping. You are encouraged to log the string form (`time.toString()`) so that you can actually see the date it corresponds to.

**Comment by xiaoyongchen** [comment]
thanks

> `new Date("2022-08")` creates a date of August 1st, so it does not suffer from overflowing and wrapping. You are encouraged to log the string form (`time.toString()`) so that you can actually see the date it corresponds to. Also, MDN is not a tech support service. Please use other forums for your questions.

thanks
