### ISSUE TITLE
&nbsp; and other entities.

### ISSUE THREAD

**Issue by estelle** [mdn/content#20189]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#entity_references_including_special_characters_in_html

### What specific section or headline is this issue about?

HTML entities

### What information was incorrect, unhelpful, or incomplete?

Maybe i just couldn't find it and it exists somewhere, but I think we need to have a page on HTML entities and escape characters.

We have https://developer.mozilla.org/en-US/docs/Glossary/Entity which covers <, >, &, and ". Two additional named entities are covered in https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#entity_references_including_special_characters_in_html, but I can't find where the non-breaking space, copyright, trademark, and other entities are covered. The main one needing to be covered is `&nbsp;`

### What did you expect to see?

&nbsp; explained somewhere

**Comment by rohini-ranjanR** [comment]
If anyone is not working on this issue can I contribute? I got some documentation from W3C  https://www.w3.org/MarkUp/HTMLPlus/htmlplus_13.html, https://www.w3.org/wiki/Common_HTML_entities_used_for_typography, and https://www.w3.org/MarkUp/Guide/Advanced.html but don't know where should I put the content.

**Comment by estelle** [comment]
> If anyone is not working on this issue can I contribute? I got some documentation from W3C https://www.w3.org/MarkUp/HTMLPlus/htmlplus_13.html, https://www.w3.org/wiki/Common_HTML_entities_used_for_typography, and https://www.w3.org/MarkUp/Guide/Advanced.html but don't know where should I put the content.

No one is working on this. If you would like to take this on, please assign the issue to yourself. (if you can't, let me know, and I'll assign you). Thank you!!!!!

**Comment by rohini-ranjanR** [comment]
Hi @estelle 
I think I can't assign this issue to myself. Can you assign this to me? 
Thank you

**Comment by teoli2003** [comment]
You don't need to ne assigned to an issue to work on it. Jist create a PR and link back to it .
