### ISSUE TITLE
[Intent to Document] Web NFC

### ISSUE THREAD

**Issue by jpmedley** [mdn/content#2019]
This ships in Chrome 89 (in beta at the time of writing). 

https://www.chromestatus.com/features/6261030015467520
https://w3c.github.io/web-nfc/

**Comment by sideshowbarker** [comment]
Since we now have https://developer.mozilla.org/en-US/docs/Web/API/Web_NFC_API as well as reference pages for the interfaces, I’m going ahead and closing this.
