### ISSUE TITLE
WASM “if...else” doc: What happens if the value is not 0 or 1? (incomplete information)

### ISSUE THREAD

**Issue by AntonioNoack** [mdn/content#20193]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Control_flow/if...else

### What specific section or headline is this issue about?

The description

### What information was incorrect, unhelpful, or incomplete?

It is not explained what happens if the value is not 0 or 1.
Often, null checks are practical, and in low level languages like C, it is ok to write `if(ptr) ...`

Is this allowed in WASM, or undefined behavior?

### What did you expect to see?

The answer that it is allowed.
To quote from the specs:
```
If c is non-zero, then Execute the block instruction instr_1
Else Execute the block instruction instr_2
```
Section 4.4.8.5. of https://webassembly.github.io/spec/core/bikeshed/#control-instructions%E2%91%A4

### Do you have any supporting links, references, or citations?

https://webassembly.github.io/spec/core/bikeshed/#control-instructions%E2%91%A4

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/webassembly/reference/control_flow/if...else`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Control_flow/if...else
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/reference/control_flow/if...else/index.md
* Last commit: https://github.com/mdn/content/commit/aab8f6b6783521e17865da924fb9359f1ccd3ae7
* Document last modified: 2022-04-21T02:33:14.000Z

</details>

**Comment by hamishwillee** [comment]
@AntonioNoack Sorry for the very long delay - you were absolutely right. Fixed by #33959
