### ISSUE TITLE
Some issue in text logic

### ISSUE THREAD

**Issue by debChowdhury** [mdn/content#20190]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures

### What information was incorrect, unhelpful, or incomplete?

"However, because blocks don't create scopes for var, the var statements here actually create a global variable. "
This statement in the docs.

### What did you expect to see?

The eg. given above the given statement clearly tells us that there will be an error if we try to get the value of x.
`if (Math.random() > 0.5) {
  var x = 1;
} else {
  var x = 2;
}
console.log(x);
`
Just because in JS unlike Java or C, curly braces do not create scopes. 
But then why it is said again below that 
"However, because blocks don't create scopes for var, the var statements here actually create a global variable. "
If x is a global variable, the there would have been no error in console.log(x).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/closures`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/closures/index.md
* Last commit: https://github.com/mdn/content/commit/1ef12f2e0815d0d285d6027219c987a3e4e228a3
* Document last modified: 2022-08-12T13:49:08.000Z

</details>

**Comment by Josh-Cena** [comment]
The example says it _doesn't_ log an error. This is also what you get.

<img width="210" alt="image" src="https://user-images.githubusercontent.com/55398995/187821246-83e78127-e750-4cbb-a048-4523bfba639e.png">

**Comment by debChowdhury** [comment]
Oh sorry. You are right. Sorry for wasting your time.
