### ISSUE TITLE
Add page summary to frontmatter?

### ISSUE THREAD

**Issue by SachaG** [mdn/content#202]
Looking at pages (such as the one for [fetch](https://github.com/mdn/content/blob/main/files/en-us/web/api/fetch_api/using_fetch/index.html)) I was thinking it could be handy if the page's summary was also added to the frontmatter? 

We use that summary on pages like https://2020.stateofcss.com/en-US/features/shapes-and-graphics/ to show a description for various CSS features and now that there is no more `$json` suffix API anymore it'd be nice to have an easier way to access page metadata such as the summary.

**Comment by peterbe** [comment]
You can get the summary from fetching `.doc.summary` from https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch/index.json
The reason we're not including the summary in the front-matter is complicated and riddled with legacy. Ultimately, we agreed you want to only have to type it once, in an unstructured way, as part of the document. If we could have started from scratch with the content, it might have been a very different story.
