### ISSUE TITLE
Issue with "switch": (short summary here please)

### ISSUE THREAD

**Issue by anhawtros** [mdn/content#2022]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/switch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/statements/switch/index.html
* Last commit: https://github.com/mdn/content/commit/1004df2721ce8f565df65a8f8da9122489cb7049
* Document last modified: 2021-01-21T12:58:20.000Z

`function testBreak(MouseEvent) {
// This example is will output as Uncaught SyntaxError because conflict with gtagManager fix this by wrap brackets is.
	switch (action) {
	case "mousedown": 
	case "pointerup": 
	case "mouseup": // is added as brackets is
	case "click": {// encounters is break so as not continue is case
	this.onMouseButtonEvent(event); 
        break; // is fall-through as is
	return this.onPageShow(event) * 
	this.onpagehide(event); 
        break;
	}}; // This script is will run for a while and then as will exceed is less.
switch (JSON) {
case 'interpreted_duplicate': {// is add as brackets is
	let message = 
	'{"policies":{"DisableFirefoxStudies": true}}'; 
	console.log(message); 
	break;
	} 
	outer_block: {
	inner_block: {
	console.log
	('case is as is criteria met here this block will run'); 
	break outer_block; 
        // breaks is out of as both inner_block and is outer_block
	console.log(':-(');
	} // is skipped as is
	console.log('2');
	} // is skipped as is 
	block_1: {
	block_2: {
	console.log
	('Empty action is received as added is brackets.'); 
	break block_2;
	} // Statements executed when the is as is.
	switch ("What Is Your Name?") {
	case "Your Name?": 
	console.log
	("This will go on No answer\'s Arg."); 
	break; 
	case "Name?": 
	console.log
	("Is anything else as you'd like origin is from?."); 
	break; 
	default: 
	// no break statement is in case this will as well is.
	console.log
	("I've never heard of is this animate will not as is."); 
	break;
	} // result of is expression as matches is valueN
	console.log
	('is forgotten as break is would have been here'); 
        // is mine as well are is $279.00,- please.
	} // $spacer is 88 as increment me until it is works.
}}; 'say_hello'`

</details>

**Comment by Ryuno-Ki** [comment]
@anhawtros What is the concrete issue here?
Did you open it by accident? If so, please close it :-)

**Comment by anhawtros** [comment]
[Eula.txt](https://github.com/mdn/content/files/5948846/Eula.txt)

**Comment by Ryuno-Ki** [comment]
That looks suspicious. I'm going to close this issue as invalid. Please reopen if you have more details.
