### ISSUE TITLE
webExtension Storage API, StorageArea.set(), note about browser differences

### ISSUE THREAD

**Issue by carlosjeurissen** [mdn/content#20222]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/set

### What specific section or headline is this issue about?

Syntax > Parameters > keys

### What information was incorrect, unhelpful, or incomplete?

As mentioned here:
https://github.com/w3c/webextensions/issues/263

Setting a value to `undefined` has inconsistent behaviour across browsers.

### What did you expect to see?

Have a warning noting the difference between the behaviour of setting a value to undefined.

In `Firefox`, setting a value to `undefined` will actually set it to `undefined`, while in other browsers, setting something to `undefined` is simply ignored and the original value is kept.

### Do you have any supporting links, references, or citations?

As mentioned here:
https://github.com/w3c/webextensions/issues/263

In there, @Rob--W mentioned the relevant bug reports:
- Bug 1499842 - "chrome.storage.sync.set({'existingKey': undefined}): inconsistency with Chromium"
    https://bugzilla.mozilla.org/show_bug.cgi?id=1499842
- Issue 896503: chrome.storage.sync.set({'existingKey': undefined}): inconsistency with Firefox
    https://bugs.chromium.org/p/chromium/issues/detail?id=896503

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/storage/storagearea/set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/set
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/set/index.md
* Last commit: https://github.com/mdn/content/commit/1d0e4c0b516be65384388ffd5c6d0f0580635af4
* Document last modified: 2022-04-21T05:20:11.000Z

</details>

**Comment by Rob--W** [comment]
Let's wait at least a week so that we can decide on the Firefox side how to address this inconsistency. If we decide to fix this, then the documentation update can be part of the bug resolution.

**Comment by Rob--W** [comment]
We triaged the bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1499842 and decided that we'd like to change the behavior to match Chrome and Safari.

Regardless of the fix, the documentation should be updated as follows:
- The recommendation for removing values is to use `storageArea.remove`
- The recommendation for overwriting values with a void value is to use `null` (not `undefined`)
- The behavior of calling `storageArea.set({keyname: undefined})` is inconsistent across browsers. Chrome and Safari do NOT change the value of `keyname`, while Firefox currently overwrites `keyname` with `undefined` (or sometimes `null`, e.g. in the `storage.sync` API). The recommendation is to NOT use `undefined` as a value, but use one of the other two options for consistent behavior.

**Comment by rebloor** [comment]
Fixed by https://github.com/mdn/content/pull/30101
