### ISSUE TITLE
Content suggestion: <update Gettiing started with Vue document to vue3 version>

### ISSUE THREAD

**Issue by qppq54s** [mdn/content#20226]
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started

## What is the new suggestion?
**Guides -> Getting started with Vue** still use vue2 but until now vue3 is the official version。
## Why is it important or useful?
· most of docs in this article need to be updated
· this work may take a week
· It allows beginners to use the documentation better, instead of some conflicts

## Other supporting information
· [vue3 document](https://vuejs.org/)
· https://github.com/mdn/content/issues/12475
· https://github.com/mdn/content/issues/16843

**Comment by bsmth** [comment]
The Vue guide was bumped to V3 here -> https://github.com/mdn/content/pull/23482
