### ISSUE TITLE
Issue with "Using the alert role": Example links lead to 404 pages

### ISSUE THREAD

**Issue by morgaan** [mdn/content#2025]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role

#### What information was incorrect, unhelpful, or incomplete?
Working Examples links lead to Page Not Found pages

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role#Working_Examples

#### What did you expect to see?
The working examples to be available resources

#### Did you test this? If so, how?
Yes, clicking the links in Working  Example section opens Page Not Found pages

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/aria_techniques/using_the_alert_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/accessibility/aria/aria_techniques/using_the_alert_role/index.html
* Last commit: https://github.com/mdn/content/commit/9b5cf04786dad342498374e51aacb2ccd1999aac
* Document last modified: 2021-01-25T01:09:48.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@morgaan Thank you for reporting this.

@peterbe I assumed, this would have been caught by https://github.com/mdn/yari/pull/2604 - so perhaps the flaws didn't catch it?

The faulty line is

https://github.com/mdn/content/blob/72a31d9626a392f6a8ac178d93573c76a1a81bbf/files/en-us/web/accessibility/aria/aria_techniques/using_the_alert_role/index.html#L105

(I think, I spotted some more instances).

**Comment by peterbe** [comment]
No, it has nothing to do with flaws. It's the fact that two external links are 404'ing. It's just that the content needs love. ...in the form of some new URLs there or perhaps removal of the links in the first place. 

Checking for broken links is hard.

**Comment by Ryuno-Ki** [comment]
:eyes: 

External links? To me, it looks like pointing to anchors on MDN.

**Comment by morgaan** [comment]
@Ryuno-Ki, @peterbe 
Indeed the issue are these 2 external links:
- [Alert role example using an ARIA alert box](http://www.oaa-accessibility.org/example/1/)
- [Alert example using a modal ARIA dialog box](http://www.oaa-accessibility.org/examplep/alertdialog1/)
They lead to 404s

Thank you for checking this out. Cheers 🌞

**Comment by chrisdavidmills** [comment]
To whoever fixes this issue:

* The two external links detailed above are not working. To fix this bug, either find equivalent examples to link to instead, or remove the links. Another way to fix the bug would be to write new examples and include them on the page, but this is not mandatory.

**Comment by rachelandrew** [comment]
This was fixed in https://github.com/mdn/content/pull/1076

So I think the issue had been reported before. I'll close this as a duplicate.
