### ISSUE TITLE
Vocabulary suggestions for Introduction to the DOM

### ISSUE THREAD

**Issue by matthessbrinks** [mdn/content#20259]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction

### What specific section or headline is this issue about?

Core interfaces in the DOM

### What information was incorrect, unhelpful, or incomplete?

"Many objects **borrow from** several different interfaces."

### What did you expect to see?

I think it is more accurate and helpful to say, "Many objects **implement** several differernt interfaces."

Reasoning: You can't "borrow from" an interface becuase it is not something concrete. You can only implement an interface. This is the essence of polymorphism. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document_object_model/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document_object_model/introduction/index.md
* Last commit: https://github.com/mdn/content/commit/abb45969b32cc406d0381b6e3bc96f603ec606eb
* Document last modified: 2022-08-23T20:20:31.000Z

</details>

**Comment by wbamberg** [comment]
I agree, "implement" is better. Would you like to [make a PR](https://github.com/mdn/content#simple-changes) with this change?

**Comment by bsmth** [comment]
Relates to https://github.com/mdn/content/issues/20260
