### ISSUE TITLE
Subtitle link color issue

### ISSUE THREAD

**Issue by TheCowMooooo** [mdn/content#2026]
[Page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions), Advanced searching with flags.

**Comment by Ryuno-Ki** [comment]
Wow, thanks for catching it!

It looks like this on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Advanced_searching_with_flags

![advanced-search-with-flags](https://user-images.githubusercontent.com/3097194/106726646-ea354d80-660a-11eb-900c-425857d44da9.png)

The markup looks broken, too:

```html
<h3 id="advanced_searching_with_flags_2">
  <a href="#advanced_searching_with_flags_2" title="Permalink to Advanced searching with flags">
    <a name="Advanced_searching_with_flags">
      Advanced searching with flags
    </a>
  </a>
</h3>
```

Source code at

https://github.com/mdn/content/blob/842e4e614cd467cd73c5c1d50164d98a4ff24a4c/files/en-us/web/javascript/guide/regular_expressions/index.html#L281

**Comment by Ryuno-Ki** [comment]
@schalkneethling Could you check, whether it's a design issue (next to a content fix)?
I couldn't tell where the pink comes from.
The black is normal background colour of a h3.

**Comment by schalkneethling** [comment]
> [Page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions), Advanced searching with flags.

What I can see in the HTML here is the following:

```
<h3 id="advanced_searching_with_flags_2"><a href="#advanced_searching_with_flags_2" title="Permalink to Advanced searching with flags"><a name="Advanced_searching_with_flags">Advanced searching with flags</a></a></h3>
```

That is something that needs to be fixed in the content itself.

**Comment by schalkneethling** [comment]
> @schalkneethling Could you check, whether it's a design issue (next to a content fix)?
> I couldn't tell where the pink comes from.
> The black is normal background colour of a h3.

Yup, the markup needs fixing. I did not see the pink color though. Thanks for looking into it @Ryuno-Ki

**Comment by TheCowMooooo** [comment]
I did not see the pink as well, only the blue on black.

**Comment by Ryuno-Ki** [comment]
Okay, perhaps a flaw on my end. I submitted a PR with a fix of the markup.
