### ISSUE TITLE
More vocuabulary suggestions for Introduction to the DOM

### ISSUE THREAD

**Issue by matthessbrinks** [mdn/content#20260]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction

### What specific section or headline is this issue about?

Core interfaces in the DOM

### What information was incorrect, unhelpful, or incomplete?

Regarding this sentence: "The following is a brief list of common APIs in web and XML page scripting using the DOM."

### What did you expect to see?

I think it would be more accurate and helpful to say, "The following is a brief list of commonly used methods within the DOM used for web and XML page scripting."

Reasoning: My understanding is that the term "API" stands for Application Programming Interface and refers to a group of methods used to interact with an application. For example, the MS Word COM API is all of the methods that Word exposes for automation. The Google Maps API is all of the methods that Google exposes for interacting with Maps. The list given is not a list of APIs. It is, rather, a list of methods within the DOM API. I know many young developers who use the term API to refer to a single method or more specifically, a single web method. So maybe the meaning of this word is changing. But I am old and don't agree. :)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document_object_model/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document_object_model/introduction/index.md
* Last commit: https://github.com/mdn/content/commit/abb45969b32cc406d0381b6e3bc96f603ec606eb
* Document last modified: 2022-08-23T20:20:31.000Z

</details>

**Comment by Josh-Cena** [comment]
I don't think it's useful to make that distinction. We often speak about "a wide range of APIs", or "this is a deprecated API". API as of today can be widely understood as a particular method, property, or event. We also say "fetch API" or "worker API", but both meanings are starting to converge, and I don't see a need to change.

**Comment by teoli2003** [comment]
I agree, API today means in the Web, a collection of entry points to interact. Whole interfaces, collection of methods/properties, …

We even hear about the DOM as a shorthand for DOM API (the API to manipulate the DOM).
