### ISSUE TITLE
"::marker" not rendering properly in the example provided

### ISSUE THREAD

**Issue by ksudilla** [mdn/content#20261]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::marker

### What specific section or headline is this issue about?

Try It

### What information was incorrect, unhelpful, or incomplete?

```
li::marker {
    content: '✝ ';
    font-size: 1.2em;
}
```
is not rendering properly; displays as bullet point.

### What did you expect to see?

the ::marker element to render as it would indicate

### Do you have any supporting links, references, or citations?

![ECD5CA96-1902-4B93-B900-B57D3C852470](https://user-images.githubusercontent.com/95648358/188242377-153e1d39-bb3d-4b85-84e4-ea4a5acadf85.jpeg)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_doublecolon_marker`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::marker
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_marker/index.md
* Last commit: https://github.com/mdn/content/commit/5d2e0c070840ecdda07e28b3f86d02f8661d0128
* Document last modified: 2022-07-04T13:57:28.000Z

</details>

**Comment by Josh-Cena** [comment]
Please check [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/::marker#browser_compatibility). If you are using Safari, it only works in technology preview.
