### ISSUE TITLE
Web/API/Permissions/speaker-selection page not written yet

### ISSUE THREAD

**Issue by guest271314** [mdn/content#20296]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API#browser_compatibility

### What information was incorrect, unhelpful, or incomplete?

Link to https://developer.mozilla.org/en-US/docs/Web/API/Permissions/speaker-selection is Page not found.

Firefox does not support `permissions.request()`; thus cannot support `navigator.permissions.request({name: 'speaker-selection'})`.

### What did you expect to see?

A link to documentation about speaker-selection.

### Do you have any supporting links, references, or citations?

 https://github.com/mdn/browser-compat-data/issues/17033

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/permissions_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/permissions_api/index.md
* Last commit: https://github.com/mdn/content/commit/0aeeed7516b4f9955049b85653c451e146b1743d
* Document last modified: 2022-08-20T04:19:37.000Z

</details>

**Comment by Josh-Cena** [comment]
The original broken link is gone, and following other permissions, it is documented under https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/speaker-selection
