### ISSUE TITLE
Edit in your Editor doesn't work on Windows

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#203]
I followed the https://github.com/hamishwillee/content/blob/main/README.md setup instructions, and modified for windows. I.e. set env variable and then restart:
```cmd
setx EDITOR code
```
The command prompt shows this warning when the button is pressed (after a "trying to open" message in the browser):
![image](https://user-images.githubusercontent.com/5368500/102149575-e7e42c00-3ec2-11eb-8e20-95ef71503ef2.png)

I also tried using Notepad++ (ie `setx EDITOR "C:\Program Files\Notepad++\notepad++.exe"`. In this case the page opened in immediately in my default browser.

**Comment by vkWeb** [comment]
@hamishwillee From that error it looks like windows can't reach that location, maybe because windows use `/` as a path separator and on trying to look with `\`. I am not sure just sharing what it feels like.

Btw, I think this issue should belong to the Yari repo.

**Comment by hamishwillee** [comment]
Thanks @vkWeb - moved to https://github.com/mdn/yari/issues/2142
