### ISSUE TITLE
Page for `MouseEvent()` doesn't show how to use it

### ISSUE THREAD

**Issue by NatoBoram** [mdn/content#20329]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent

### What information was incorrect, unhelpful, or incomplete?

This page shows that we can use `new MouseEvent(type, options)` to create a `MouseEvent` but it doesn't show how to use it

### What did you expect to see?

An example that can replace this code:

```typescript
const mouseEvent = document.createEvent("MouseEvent")
mouseEvent.initEvent("mouseover")
element.dispatchEvent(mouseEvent)
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mouseevent/mouseevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mouseevent/mouseevent/index.md
* Last commit: https://github.com/mdn/content/commit/542ec1e002ae3c340f0925adfd1f0d870c14ff32
* Document last modified: 2022-08-09T12:24:48.000Z

</details>

**Comment by Josh-Cena** [comment]
None of the other event constructor pages show an example, so I reckon it's not very useful to have. You can directly do `dispatchEvent(new MouseEvent("mouseover"))`.
