### ISSUE TITLE
HTTP pipeline is not defined in MDN content

### ISSUE THREAD

**Issue by kev1010** [mdn/content#20326]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

### What information was incorrect, unhelpful, or incomplete?

This page uses the term HTTP pipeline which is not specified anywhere in MDN. The term needs to be defined because leaving MDN and searching for a definition returns many different interpretations. 

### What did you expect to see?

The HTTP pipeline word should be rendered as a link to the defintion.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/fetch_api/using_fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fetch_api/using_fetch/index.md
* Last commit: https://github.com/mdn/content/commit/c7aeb96dac3e0ac2864cffe45c02d214ae1a5219
* Document last modified: 2022-08-27T16:31:08.000Z

</details>

**Comment by teoli2003** [comment]
This is not a technical term. HTTP pipelining was a failed attempt at parallelism and is described [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Connection_management_in_HTTP_1.x#http_pipelining).

In this case, we should use the word _protocol_. Do you want to create the PR?
