### ISSUE TITLE
"See the Source Code" Link Gets a Page Not Found Error Message

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#20359]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content

### What specific section or headline is this issue about?

Other <video> features

### What information was incorrect, unhelpful, or incomplete?

Under the heading "Other `<video>` features" for the section right after "preload", the link "see the source code" is getting a page not found for the following link.

https://github.com/mdn/learning-area/blob/gh-pages/html/multimedia-and-embedding/video-and-audio-content/extra-video-features.html)

### What did you expect to see?

I would expect the link to work and go to the proper page.

### Do you have any supporting links, references, or citations?

No

### Do you have anything more you want to share?

No

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/video_and_audio_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/video_and_audio_content/index.md
* Last commit: https://github.com/mdn/content/commit/4b57879ba126b492feae036c321ad7a7ee8c8138
* Document last modified: 2022-08-12T21:03:25.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened #20374 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
