### ISSUE TITLE
The 'hidden' attribute page does not describe the 'until-found' value for this attribute

### ISSUE THREAD

**Issue by helenb** [mdn/content#20382]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

### What information was incorrect, unhelpful, or incomplete?

The browser compatibility section mentions the 'until-found' value for this attribute, but no where else on the page is this described or explained. There is no table of options for the possible values of the 'hidden' attribute.

### What did you expect to see?

A table showing the possible values for the 'hidden' attribute, including the 'until-found' value with a description of what it does.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/hidden`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/hidden/index.md
* Last commit: https://github.com/mdn/content/commit/ae92c3a4a3c76b630bfb8d5d771e8efcc024e353
* Document last modified: 2021-11-19T16:02:29.000Z

</details>

**Comment by helenb** [comment]
Thank you for this @wbamberg!

**Comment by wbamberg** [comment]
You're welcome! Let us know if there's anything else to add here :).
