### ISSUE TITLE
NaN === NaN ? No!

### ISSUE THREAD

**Issue by GarrettS** [mdn/content#20418]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

### What specific section or headline is this issue about?

Wrong example

### What information was incorrect, unhelpful, or incomplete?

> Usually, the global object does not need to be explicitly specified — its properties are automatically accessible as global variables.
> ```js
> console.log(window.NaN === NaN); // true
> ```

No, it isn't

### What did you expect to see?

Something else, such as console.log(window.alert === alert); // true

### Do you have any supporting links, references, or citations?

https://262.ecma-international.org/12.0/#sec-numeric-types-number-equal

### Do you have anything more you want to share?

Somebody was trolling on this example.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/globalthis`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/globalthis/index.md
* Last commit: https://github.com/mdn/content/commit/fa1c80ded72b16a72e6993034620a6ff35d175b5
* Document last modified: 2022-09-05T03:04:56.000Z

</details>

**Comment by Josh-Cena** [comment]
Ha—yes. Feel free to fix it if you wish. Otherwise I will get to it later.

**Comment by shraddhafalane** [comment]
I would like to work on it

**Comment by softorangetech1122** [comment]
@Josh-Cena Wooooooow you trolled us. With no intention😅
![image](https://user-images.githubusercontent.com/111031232/189241754-edd4da2d-4c36-40e9-858d-a56d8401f477.png)

**Comment by Josh-Cena** [comment]
@shraddhafalane Did you get to look at this? I do want to fix this issue ASAP.

**Comment by AnilSeervi** [comment]
created #20557 @Josh-Cena 
you can review it and merge if it resolves this issue.

**Comment by GarrettS** [comment]
> (Also, I wrote that example—with no intention to troll, just forgot about `NaN` being special. And so over-confident I didn't test it.)

Alright. Sorry about accusing you of trolling.

**Comment by GarrettS** [comment]
Reading a few paragraphs down that page, I found more problems with it. 

It might be only an interesting historical factoid that in Internet Explorer, results for window and windowproxy varied; window != self was true.

However, it would be a good idea to caution against "Polyfills", which the article clearly expouses.

> Usually, the global object does not need to be explicitly specified — its properties are automatically accessible as global variables.

That's true when accessing window properties not shadowed by the GlobalScopePolluter (or whatever the hell they call it nowadays) (https://www.mail-archive.com/public-webapps@w3.org/msg13083.html)

> However, one case where one needs to explicitly access the global object is when writing to it, usually for the purpose of [polyfills](https://developer.mozilla.org/en-US/docs/Glossary/Polyfill).

Polyfills are inadvisable. This discussion, on a page about globalThis, serves no purpose. Rather than encouraging such bad coding practices, this distraction should be removed. Better yet, advise against this practice.

Finally, this should be removed or improved.

```
const globalObject =
  check(typeof window === 'object' && window) ||
  check(typeof self === 'object' && self) ||
  check(typeof global === 'object' && global) ||
  // This returns undefined when running in strict mode
  (function () { return this; })() ||
  Function('return this')();
```

Why not just use:
```
const globalObject = (function () { return this; })() ||
  Function('return this')();

window == this is another area that has been historically dodgy in browsers (along with window == document, and others).

**Comment by Josh-Cena** [comment]
> Polyfills are inadvisable

I think @zloirock would have a lot of say on this. You may be confusing "polyfill" with "monkey patching".

Also, the point of `globalThis` is for environments without `window`, for example, Node.

As for your alternative, it won't work if the entire program is in strict mode, and there's strict CSP, which are very likely to happen together.

**Comment by Josh-Cena** [comment]
You can never, ever, get access to the actual global object in browsers—it's always the window proxy. In browsers, `globalThis === window` is always true. In Node, `globalThis === global` is always true. The only point about `globalThis` is to bridge this environment difference.

**Comment by zloirock** [comment]
> Polyfills are inadvisable.

Lol. Who told you such nonsense? For example, polyfills are used on more than 80 of the top 100 websites.

> `const globalObject = (function () { return this; })() || Function('return this')();`

`(function () { return this; })()` will not work in strict mode. `Function('return this')()` will break CSP or other envs with disallowed `eval`.

**Comment by GarrettS** [comment]
"Lol. Who told you such nonsense? " Appeal to incredulity. Your overconfidence is showing.

"polyfills are used on more than 80 of the top 100 websites"

And that makes the approach reliable? That's called "Appeal to popularity", the converse of Appeal to incredulity. 

The problems with polyfills are that they may have divergent behavior than standard and that they lead to false positives with feature tests, as in: `if (typeof document.addEventListener == "function")` My experience in coding led me to realize this (probably while you were still in diapers).

My comments don't have anything to do with the original bug, which has been fixed (thanks), but the page still suffers. This needs a new bug. The level of overconfidence explains the problems on this page.

Get better.

**Comment by zloirock** [comment]
> My experience in coding led me to realize this (probably while you were still in diapers).

Very authoritative opinion and confirmation of the point of view :-D

**Comment by Josh-Cena** [comment]
Polyfills as of 2022 has become an indispensable part of the frontend industry along with transpilers. Without them you won't be able to use any post-ES6 APIs if you have responsible commitments to older browsers. And the fact is, polyfills today don't deviate from the spec—quite on the contrary, they _fix_ bad/buggy engine behaviors.

**Comment by wbamberg** [comment]
Hi

Participation in the mdn/content repo is governed by Mozilla's Community Participation Guidelines (https://www.mozilla.org/en-US/about/governance/policies/participation/), which among other things expects respectful interactions: https://www.mozilla.org/en-US/about/governance/policies/participation/#expected-behavior.

Genuine attempts to improve content and fix problems are greatly appreciated. Respectful behavior to other participants is essential, name-called and abuse are not tolerated. If you are not able to follow these guidelines it's best not to participate in the project.
