### ISSUE TITLE
Culture-centric viewpoint in description of .length

### ISSUE THREAD

**Issue by r12a** [mdn/content#20434]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

This property returns the number of code units in the string. [UTF-16](https://en.wikipedia.org/wiki/UTF-16), the string format used by JavaScript, uses a single 16-bit code unit to represent the most common characters, but needs to use two code units for less commonly-used characters, so it's possible for the value returned by length to not match the actual number of Unicode characters in the string.

### What did you expect to see?

A single utf-16 code unit doesn't cover the 'most common characters' for someone writing, for example, modern-day Fula in the Adlam script, which is encoded beyond the BMP.  The distinction is no longer about common vs less-common characters, but more when the script was encoded. Perhaps just describe it in terms of Unicode's BMP and beyond, or just say that many Unicode characters use a single code unit, but many others use two?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/length`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/length/index.md
* Last commit: https://github.com/mdn/content/commit/8a5ab92ceab8fe1b8f44597381cf3fd996e252e9
* Document last modified: 2022-08-06T06:07:15.000Z

</details>

**Comment by Josh-Cena** [comment]
I think the notion of "common" is unambiguous. "Common" is decided based on the absolute number of occurrences in text exchange, without any context of language or script. Sure, some scripts use mostly non-BMP characters, but those scripts are uncommon in themselves. (This is not a normative statement and makes no value judgement about whether that's good or not).

However I agree this statement is very handwavy and not very helpful for a reference material. We have a better (IMO) description here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_codepoints_and_grapheme_clusters

> This means there are a maximum of 216, or 65536 possible characters representable as single UTF-16 code units. This character set is called the basic multilingual plane (BMP), and includes the most common characters like the Latin, Greek, Cyrillic alphabets, as well as many East Asian characters.

I'm on my way to align all encoding-related string reference pages. I will update this as well to make it appear more technical.
