### ISSUE TITLE
Text Needs Correcting - Number of People is Three Not Two

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#20483]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

### What specific section or headline is this issue about?

Why responsive images?

### What information was incorrect, unhelpful, or incomplete?

In the text below, if you are referring to the banner image, there are three people, not two, in the photo. 

And at this size, it is difficult to see faces of the **two** people within the first content image.

Make the text bold to make it easier to spot.

### What did you expect to see?

I expected to have the text mention the correct number of people.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.md
* Last commit: https://github.com/mdn/content/commit/c482f34f48d447bfb9ee76b76013dae3b66f45c7
* Document last modified: 2022-08-20T05:15:25.000Z

</details>

**Comment by Josh-Cena** [comment]
See https://github.com/mdn/content/pull/20501#issuecomment-1242635416
