### ISSUE TITLE
Link from "align" is dead

### ISSUE THREAD

**Issue by Aayushap1** [mdn/content#2050]

**Comment by Aayushap1** [comment]
I fixed this issue and I will send the PR.

**Comment by chrisdavidmills** [comment]
You don't need separate issues to record the fixing of an issue — this just makes it more confusing. You just comment in the existing issue.

In fact, when you raise a PR and say that it "fixes bug number #whatever" , when that PR is merged, the issue with automatically be closed in a lot of cases, and it will automatically reference the PR that fixed it.
