### ISSUE TITLE
Is the full source code for the “Creating and sequencing audio” demo available?

### ISSUE THREAD

**Issue by transfluxus** [mdn/content#20529]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Advanced_techniques

### What specific section or headline is this issue about?

general

### What information was incorrect, unhelpful, or incomplete?

Is the full source code somewhere available?

the pieces of code put together to deliver the full application.
For example is there no html which contains the  play-button.

Thanks!

### What did you expect to see?

A link to a full html file

### Do you have anything more you want to share?

Great tutorial otherwise

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_audio_api/advanced_techniques`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Advanced_techniques
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_audio_api/advanced_techniques/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. There’s an existing Note in the article, with a link to the source code on GitHub — but I guess it’s kind of easy to overlook. So I’ve opened #20553 with a change that moves the note up to the top of the article.

After that change is merged, this issue will automatically be marked as resolved, and closed.
