### ISSUE TITLE
function playSample accidentally references global variable instead of passed in variable

### ISSUE THREAD

**Issue by whiddershins** [mdn/content#20565]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/cancelScheduledValues

### What specific section or headline is this issue about?

function playSample(audioContext, audioBuffer, time)

### What information was incorrect, unhelpful, or incomplete?

function signature is:
      // Create a buffer, plop in data, connect and play -> modify graph here if required
      function playSample(audioContext, audioBuffer, time) {

on line 377 (first line of the function) 

        const sampleSource = new AudioBufferSourceNode(audioCtx, {

line uses audioCtx (the global context variable) rather than the passed in variable audioContext

### What did you expect to see?

        const sampleSource = new AudioBufferSourceNode(audioContext, {

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/audioparam/cancelscheduledvalues`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/cancelScheduledValues
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/audioparam/cancelscheduledvalues/index.md
* Last commit: https://github.com/mdn/content/commit/bf30e32f3b51f59080f2c76795beadb247a551eb
* Document last modified: 2022-09-09T05:07:36.000Z

</details>

**Comment by teoli2003** [comment]
Hi! Do you feel like creating a PR to fix this?

**Comment by najmiehsa** [comment]
@whiddershins same goes here. Please double-check the reference because it is not correct.
