### ISSUE TITLE
parseInt() is inappropriate in most cases for this example

### ISSUE THREAD

**Issue by whiddershins** [mdn/content#20564]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Advanced_techniques

### What specific section or headline is this issue about?

Several, whenever an eventListener is added

### What information was incorrect, unhelpful, or incomplete?

Using parseInt() for the attackTime and releaseTime clips the control to 0, 1 which isn't expected behavior. 

Using parseInt() on the noiseDuration throws an error when the range slider is adjusted, because it will set the duration to 0.

### What did you expect to see?

Expect the example to use parseFloat(), for example:

            noiseDuration = parseFloat(ev.target.value);

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/audioparam/cancelscheduledvalues`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/cancelScheduledValues
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/audioparam/cancelscheduledvalues/index.md
* Last commit: https://github.com/mdn/content/commit/bf30e32f3b51f59080f2c76795beadb247a551eb
* Document last modified: 2022-09-09T05:07:36.000Z

</details>

**Comment by teoli2003** [comment]
Hi! Do you feel like creating a PR to fix this?

**Comment by najmiehsa** [comment]
@whiddershins would double check the initial reference here? It is not correct and it does not accord with your request.

**Comment by whiddershins** [comment]
Updated
