### ISSUE TITLE
TextEncoderStream & TextDecoderStream

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#20572]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Looks like docs are done, but bcd needs updating 

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1486949

## Other

- Support for [TextDecoderStream](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoderStream)   - [TextEncoderStream](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoderStream)

**Comment by hamishwillee** [comment]
Status

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/17765
- [ ] Docs
- [ ] Release note
- [ ] dev-doc-complete

-

**Comment by Rumyra** [comment]
I'll add it to the 'list' that better examples are probably needed - thanks @hamishwillee
