### ISSUE TITLE
navigator.platform deprecated? What about browsers that don't support navigator.userAgentData?

### ISSUE THREAD

**Issue by oded-af** [mdn/content#20586]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/appVersion

### What specific section or headline is this issue about?

The sections where it says `deprecated` and `See also`

### What information was incorrect, unhelpful, or incomplete?

It is mentioned that navigator.platform is deprecated, it is my understanding that one should use `navigator.userAgentData` instead but what about the (many) browsers that don't support navigator.userAgentData (and client hints in general)? 
This is the missing information I'm referring to. 

### What did you expect to see?

Either an alternative to `navigator.userAgentData.platform` or some information about which browsers would still support `navigator.platform`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/appversion`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/appVersion
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/appversion/index.md
* Last commit: https://github.com/mdn/content/commit/4b4638246aad5d39b9a2e5c572b179b4c39c0a84
* Document last modified: 2022-09-09T05:17:24.000Z

</details>

**Comment by teoli2003** [comment]
The deprecation is in favour of feature detection instead of platform detection:

![Capture d’écran 2022-09-12 à 10 43 25](https://user-images.githubusercontent.com/1466293/189610743-c6ad28eb-09d1-475b-934b-226d79d0bcd4.png)

**Comment by sideshowbarker** [comment]
Closing this per https://github.com/mdn/content/issues/20586#issuecomment-1243409190

(Incidentally, this is one of those cases where instead of the “Deprecated” notice, what we really should have instead is a “Discouraged” notice; see https://github.com/mdn/content/discussions/5549#discussioncomment-814689.)
