### ISSUE TITLE
Issue with "Nullish coalescing operator (??)": Visible template tags

### ISSUE THREAD

**Issue by dannydamianus** [mdn/content#206]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

#### What information was incorrect, unhelpful, or incomplete?
The template tags is shown on the bottom of the page.

![image](https://user-images.githubusercontent.com/2785361/102158725-07785600-3ebd-11eb-9286-0a172e672b44.png)

#### Specific section or headline?
"See also" section

#### What did you expect to see?
The template tags should not be visible

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/nullish_coalescing_operator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/operators/nullish_coalescing_operator/index.html
* Report started: 2020-12-15T01:56:42.398Z

</details>

**Comment by Elchi3** [comment]
Fixed in https://github.com/mdn/content/pull/221
