### ISSUE TITLE
Issue with "Flexbox": (short summary here please)

### ISSUE THREAD

**Issue by pshar7** [mdn/content#2060]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox

#### What information was incorrect, unhelpful, or incomplete?
Spelling ( When elements are laid out as flex items, they are laid out along two axes: )

#### Specific section or headline?
The flex model

#### What did you expect to see?
When elements are laid out as flex items, they are laid out along two axis:

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/css_layout/flexbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/css/css_layout/flexbox/index.html
* Last commit: https://github.com/mdn/content/commit/18c7ef2b2b4824b126508d8c8b788f8245ff4bc3
* Document last modified: 2021-01-08T05:39:20.000Z

</details>

**Comment by rachelandrew** [comment]
Axes is the plural of axis https://www.dictionary.com/browse/axes so I don't think there is something to change here as we are talking about two axes.
