### ISSUE TITLE
Missing CSS functions

### ISSUE THREAD

**Issue by estelle** [mdn/content#20611]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions

### What specific section or headline is this issue about?

I don't know

### What information was incorrect, unhelpful, or incomplete?

@import allows for supports() and layer() bun neither of these are mentioned on this page nor have their own pages. We likely need to:

1. create a supports-query page
2. create a layer-name page
3. add both to the CSS functions page.

### What did you expect to see?

to find both layer() and supports on the function list.
or, on another appropriate page.
this page is for functional notations as part of the value in property/value pairs, so this might not be the right place. But not sure where is.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/CSS/@import

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_functions/index.md
* Last commit: https://github.com/mdn/content/commit/05a61497f79c7bf5ffaf8fe7d94b36d5a0b9626e
* Document last modified: 2022-09-09T05:52:16.000Z

</details>

**Comment by ramiy** [comment]
Not sure if `supports( supports-query )` should be displayed in **[CSS Functions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions)** page. The page talks about functional notation in a context of property values, not in a context of at-rules.

It would be preferred to create a new page for all the at-rules functions. This ways we separate them.

The same way we separate function-like pseudo-classes - `:has()`, `:not()` etc.

**Comment by Josh-Cena** [comment]
Since these are not functions, I would assume this is wontfix
