### ISSUE TITLE
Grouping objects by a property code is not working

### ISSUE THREAD

**Issue by mailmonir** [mdn/content#20631]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

### What specific section or headline is this issue about?

Grouping objects by a property

### What information was incorrect, unhelpful, or incomplete?

I tried this code in editor but it return the following error

Uncaught TypeError: acc[key] is not iterable
    at index.js:11:36
    at Array.reduce (<anonymous>)
    at groupBy (index.js:8:22)
    at index.js:15:23
/favicon.ico:1          Failed to load resource: the server responded with a status of 404 (Not Found)

### What did you expect to see?

I want to see the fully functional code

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/reduce`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/reduce/index.md
* Last commit: https://github.com/mdn/content/commit/395eac3b6c356f7b17ff85af4fb5250d0634e264
* Document last modified: 2022-09-11T17:50:11.000Z

</details>

**Comment by Josh-Cena** [comment]
Ooops, my mistake...
