### ISSUE TITLE
Optional Chaining with Arrays

### ISSUE THREAD

**Issue by aghster** [mdn/content#20635]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

### What specific section or headline is this issue about?

Optional chaining with expressions

### What information was incorrect, unhelpful, or incomplete?

I don't understand the second example of the section, i.e. the example relating to optional chaining with arrays. Why does the given example demonstrate that optional chaining is particularly useful for arrays? Don't ['a', 'b', 'c', 'd']?.[42] and ['a', 'b', 'c', 'd'][42] both return undefined?

### What did you expect to see?

If optional chaining actually is particularly useful for arrays, I would expect an example that demonstrates how optional chaining allows simplifying an expression that otherwise would require much more typing. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/optional_chaining`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/optional_chaining/index.md
* Last commit: https://github.com/mdn/content/commit/968e6f1f3b6f977a09e116a0ac552459b741eac3
* Document last modified: 2022-09-09T05:25:05.000Z

</details>

**Comment by danieltroger** [comment]
@aghster it's useful for this example:

```ts
undefined?.[3]; // -> undefined
undefined[3]; // Uncaught TypeError: Cannot read properties of undefined (reading '3')
```

Where of course `undefined` can be any expression that evaluates to `undefined` or `null`
