### ISSUE TITLE
Page not Found for Code_snippets/QuerySelector

### ISSUE THREAD

**Issue by samihibrahim** [mdn/content#2064]
On this page: https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/Locating_DOM_elements_using_selectors

![original_page](https://user-images.githubusercontent.com/559181/106839393-1cc36280-666c-11eb-9516-5879124fc88f.png)

both links to *Code_snippets/QuerySelector* are broken (404)
![page_not_found](https://user-images.githubusercontent.com/559181/106839402-1f25bc80-666c-11eb-8283-b87c0dc3c6e1.png)

**Comment by Ryuno-Ki** [comment]
@samihibrahim Thanks for filling this issue!

I think, it's best to simply delete the link:

https://github.com/mdn/content/blob/89b781abf1093d108f0fba926286c5b9eac59923/files/en-us/web/api/document_object_model/locating_dom_elements_using_selectors/index.html#L48

Do you want to do it?

**Comment by samihibrahim** [comment]
Sure @Ryuno-Ki, PR (#2304) submitted.

**Comment by Ryuno-Ki** [comment]
Merged.
Thank you and welcome to mdn/content :tada:
