### ISSUE TITLE
Fetch Event client id is null

### ISSUE THREAD

**Issue by transformsen** [mdn/content#20657]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/clientId

### What specific section or headline is this issue about?

Client id is null

### What information was incorrect, unhelpful, or incomplete?

As per specifications and implementation client for non subresource request is null

### What did you expect to see?

Mention it is null for non subresource request

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/fetchevent/clientid`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/clientId
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fetchevent/clientid/index.md
* Last commit: https://github.com/mdn/content/commit/1511e914c6b1ce6f88056bfefd48a6aa585cebce
* Document last modified: 2022-09-09T05:10:34.000Z

</details>

**Comment by tlylt** [comment]
Hi @transformsen,  do you have the links to the specification/implementation that you mentioned?

Sorry if it's a stupid question, but does "non subresource request" here refer to requests from the origin? I can only find references about "subresource" in the context of ["Subresource Integrity"](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity).

**Comment by transformsen** [comment]
Thanks for your reply.. 
Example of non subresource request is from submit. Form submit to new jsp Or servlet page Or any new webpage. 

Form non subresource specification recommend to provide replacesClientid. 
Doc - https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/replacesClientId
Spec - https://w3c.github.io/ServiceWorker/#fetch-event-replacesClientId

But no browser have implemented it. ReplacesClientid would really help for our requirements.

**Comment by Josh-Cena** [comment]
I did not find information in the spec that it can be null. I'm not sure if `clientId` can even be the empty string. The IDL in the spec says:

```webidl
interface FetchEvent : ExtendableEvent {
  constructor(DOMString type, FetchEventInit eventInitDict);
  [SameObject] readonly attribute Request request;
  readonly attribute Promise<any> preloadResponse;
  readonly attribute DOMString clientId;
  readonly attribute DOMString resultingClientId;
  readonly attribute DOMString replacesClientId;
  readonly attribute Promise<undefined> handled;

  undefined respondWith(Promise<Response> r);
};
```

And here are the relevant steps in [initializing the event](https://w3c.github.io/ServiceWorker/#create-fetch-event-and-dispatch-algorithm):

> 9. Initialize e’s [clientId](https://w3c.github.io/ServiceWorker/#dom-fetchevent-clientid) attribute to client’s [id](https://html.spec.whatwg.org/multipage/webappapis.html#concept-environment-id).
> 10. If request is a [non-subresource request](https://fetch.spec.whatwg.org/#non-subresource-request) and request’s [destination](https://fetch.spec.whatwg.org/#concept-request-destination) is not ["report"](https://fetch.spec.whatwg.org/#dom-requestdestination-report), initialize e’s [resultingClientId](https://w3c.github.io/ServiceWorker/#dom-fetchevent-resultingclientid) attribute to reservedClient’s [id](https://html.spec.whatwg.org/multipage/webappapis.html#concept-environment-id), and to the empty string otherwise.
> 11. If request is a [navigation request](https://fetch.spec.whatwg.org/#navigation-request), initialize e’s [replacesClientId](https://w3c.github.io/ServiceWorker/#dom-fetchevent-replacesclientid) attribute to request’s [replaces client id](https://fetch.spec.whatwg.org/#concept-request-replaces-client-id), and to the empty string otherwise.
