### ISSUE TITLE
Issue with "CSS first steps": Outdated link

### ISSUE THREAD

**Issue by navjotjsingh** [mdn/content#2066]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps

#### What information was incorrect, unhelpful, or incomplete?
Intermediate Web Literacy 1: Intro to CSS is no longer available so it makes no sense to link to it anymore.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/first_steps`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/css/first_steps/index.html
* Last commit: https://github.com/mdn/content/commit/98e438b7d2e79c7dc04c72ca7e2f3bf36a84940f
* Document last modified: 2021-01-22T05:20:39.000Z

</details>

**Comment by chrisdavidmills** [comment]
Hi @navjotjsingh !

Yes, I agree with you, completely; thanks for reporting this.

I've removed the obsolete link; see https://github.com/mdn/content/commit/d30011c59287cf40d0a6b72ce534086c9a90f227
