### ISSUE TITLE
Issue with "Time to first byte" Calculation

### ISSUE THREAD

**Issue by nicolasfaurereboot** [mdn/content#2067]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/time_to_first_byte

#### What information was incorrect, unhelpful, or incomplete?

it says Time to First Byte (TTFB) "includes DNS lookup and establishing the connection using a TCP handshake and SSL handshake if the request is made over https." and it defines TTFB as : "TTFB = responseStart - requestStart".

requestStart happens after domainLookupEnd, secureConnectionStart and connectEnd as defined by the  Processing Model of the PerformanceResourceTiming interface (URL: https://www.w3.org/TR/resource-timing-1/#dom-performanceresourcetiming-requeststart ) 

#### What did you expect to see?

"responseStart attribute must return the time immediately after the user agent receives the first byte of the response from the server, or from relevant application caches or from local resources." (URL https://www.w3.org/TR/navigation-timing/#dom-performancetiming-responsestart ).

I would expect to see: "TTFB = responseStart" or "TTFB = responseStart -navigationStart" 

#### Did you test this? If so, how?

How does Google calculate the TTFB in their Chrome Extension "web vitals" ?
getTTFB=responseStart

extract form URL: https://github.com/GoogleChrome/web-vitals/blob/master/src/getTTFB.ts 
export const getTTFB = (onReport: ReportHandler) => {
  const metric = initMetric('TTFB');

  afterLoad(() => {
    try {
      // Use the NavigationTiming L2 entry if available.
      const navigationEntry = performance.getEntriesByType('navigation')[0] ||
          getNavigationEntryFromPerformanceTiming();

      metric.value = metric.delta =
          (navigationEntry as PerformanceNavigationTiming).responseStart;

      metric.entries = [navigationEntry];

      onReport(metric);
    } catch (error) {
      // Do nothing.
    }
  });
};

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/time_to_first_byte`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/time_to_first_byte
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/glossary/time_to_first_byte/index.html
* Last commit: https://github.com/mdn/content/commit/dc2d69ce72ebc6c41ad03720c53ab3c4addc511b
* Document last modified: 2021-01-20T10:16:06.000Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this, @nicolasfaurereboot !

Would you be interested in submitting a PR to the repo to fix this content?

**Comment by nicolasfaurereboot** [comment]
I am very recent github user. I don't know what "submitting a PR to the repo to fix this content" implies and incase how to do it

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills : I am very recent github user. I don't know what "submitting a PR to the repo to fix this content" implies and incase how to do it

OK, no worries. Basically, this content is all stored on a GitHub repo. There is a link at the bottom of every MDN page — "Source on GitHub", which links through to the source code for that page of content. In the case of the page we are discussing, the source is at https://github.com/mdn/content/commit/d30011c59287cf40d0a6b72ce534086c9a90f227

To make changes to that page, you need fork our repo (https://github.com/mdn/content/), create a new branch of your fork to create changes in, make the changes, and then submit a pull request (PR), which means basically you are making a suggestion to us about how some content should be changed. We then review that suggestion, and if it looks good, merge it so that those changes are included in our copy of the repo.

If you don't know what any of that means, then we've got a list of resources here that covers the basics — https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/GitHub. Have a look, and feel free to ask if you've got ay questions. I'm more than happy to help.

Or if you don't feel ready to commit to learning Git/GitHub at this time, that's fine too. You've provided what you think the content update should be, which is already super-helpful.

**Comment by nicolasfaurereboot** [comment]
@chrisdavidmills : thanks for the explanations. As you wrote about fork and I am a French food lover, I have to try this submission.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills : thanks for the explanations. As you wrote about fork and I am a French food lover, I have to try this submission.

Ha — I knew I could appeal to your passions somehow ;-)

Please poing me if you need any help; I'm happy to review your PR too.

**Comment by Aditya-1804078** [comment]
I am a beginner in open source community, can you please assign this issue to me?? Solving this issue would be great start for me.

**Comment by CreaTorAlexander** [comment]
I would like to do it.

> I would expect to see: "TTFB = responseStart" or "TTFB = responseStart -navigationStart"

Which of them is prefered?

**Comment by nicolasfaurereboot** [comment]
> > I would expect to see: "TTFB = responseStart" or "TTFB = responseStart -navigationStart"
> Which of them is prefered?

TTFB = responseStart -navigationStart
- [ ] because navigationStart does not always equal zero

**Comment by CreaTorAlexander** [comment]
Alright, now I just have to find the file where the content is  😆

**Comment by CreaTorAlexander** [comment]
@nicolasfaurereboot is just the equation/formula changing or also the text before?

**Comment by nicolasfaurereboot** [comment]
> @nicolasfaurereboot is just the equation/formula changing or also the text before?

which texte before ?

**Comment by CreaTorAlexander** [comment]
This text 

> Time to First Byte (TTFB) refers to the time between the browser requesting a page and when it receives the first byte of information from the server.  This time includes DNS lookup and establishing the connection using a TCP handshake and SSL handshake if the request is made over https.
> 
> TTFB is the time it takes between the start of the request and the start of the response, in milliseconds:

Also there is a hyperlink for responseStart and requestStart, but I haven't found one for navigationStart https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/navigationStart
<img width="1663" alt="Bildschirmfoto 2021-02-07 um 08 42 08" src="https://user-images.githubusercontent.com/44900696/107140181-aac77380-6920-11eb-97e1-5eaa87a5c036.png">

**Comment by nicolasfaurereboot** [comment]
sorry but I don' understand what you want to edit or do ?
if it's to review the suggestion I made related to the calculation of TTFB, i can't help you, because I am a very recent github user, and don't know how it works yet. But I think I followed all the steps recommended by @chrisdavidmills to submit this suggestion

**Comment by CreaTorAlexander** [comment]
@nicolasfaurereboot The formula which I would like to update here
  https://developer.mozilla.org/en-US/docs/Glossary/time_to_first_byte 

`TTFB = responseStart - requestStart` 
There are hyperlinks on responseStart and requestStart, when you click on one of them then you will redirected to their pages. 

My problem now is when I update the text, to 

`TTFB = responseStart -navigationStart 
`
as you suggested I have no hyperlink for navigationStart at the moment. The question is now shall I update it without a hyperlink.

**Comment by CreaTorAlexander** [comment]
Well I have found it the hyperlink for navigationStart is `/en-US/docs/Web/API/PerformanceTiming/navigationStart`

**Comment by nicolasfaurereboot** [comment]
the hyperlink I referred for the navigationStart's definition is here :
https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming/navigationStart
"navigationStart" is a property from the interface "PerformanceTiming" (URL: https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming) from "Navigation Timing API" (Level 1). 

at the top of all these pages, there is a warning saying these property and timing interface are deprecated (now Navigation Timing API Level 2, so it recommends to use the interface PerformanceNavigationTiming (URL https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming) instead of the interface PerformanceTiming

but on this page (performanceNavigationTiming), :
- there is a warning saying that's experimental
- the specification says the "Navigation Timing Level 2" status is Draft. which is confirmed by w3c (URL: https://w3c.github.io/performance-timeline/#dom-performanceentry-starttime)
- although the Browser compatibility says Chrome 57+, when I try to get the datas with Chrome 88, it doesn't work.

so I think the warning is not appropriated and the browser compatibility is wrong (but I want to do test again before tu suggest an issue). 

for the moment I use the interface PerformanceTiming (Navigation Timing API Level 1) with navigationStart defined here (URL: https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming/navigationStart) and it works well and get the same datas that Chrome Dev Tools / Network & Performance tab

**Comment by Ryuno-Ki** [comment]
You could open

https://github.com/mdn/content/blob/958c4d5be9beeceb04629cb8495a13d0667e120b/files/en-us/glossary/time_to_first_byte/index.html

and pick the pen icon in the upper right corner of the file.
That will switch you to edit mode on GitHub.

From there, make the edits as suggested.

Then, at the bottom, you can write a summary of what changed (helpful to mention `#2067` in it to make it link back to this conversation) and submit it as a new branch.

When navigating back to https://github.com/mdn/content and waiting a short time, there will be a banner above the code asking you, whether you want to submit a PR for that branch into `main`.

**Comment by chrisdavidmills** [comment]
Fixed by https://github.com/mdn/content/pull/2154
