### ISSUE TITLE
Issue with "Array.prototype.at()": "at" fails to work

### ISSUE THREAD

**Issue by JohnyL** [mdn/content#2068]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

#### What information was incorrect, unhelpful, or incomplete?
`Browser compatibility` section says that Google Chrome 89 supports `at`. However, I have tried in 90.0.4400.8 (Official Build) dev (64-bit), and it fails to work. I get the error:
> Uncaught TypeError: arr.at is not a function

#### Specific section or headline?
`Browser compatibility` section

#### Did you test this? If so, how?
JavaScript code:
```
let arr = [1, 2, 3]
let last = arr.at(-1)
console.log(last)
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/at`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/array/at/index.html
* Last commit: https://github.com/mdn/content/commit/2b09e004900775c87f0b01994af9931a2241981c
* Document last modified: 2021-01-25T13:11:56.000Z

</details>

**Comment by chrisdavidmills** [comment]
Hrm, I'm pretty sure this is supported, but only behind a browser preference. The compat data should reflect that, and I believe it was updated recently. The updated data should show on the page very soon.

**Comment by avivmu** [comment]
It's fixed already.
This was fixed `https://github.com/mdn/browser-compat-data/commit/3b5c4d1ebab922bd305c9fdf96a90a56b3f839ad`
Please close the issue
