### ISSUE TITLE
Git client produces error with git precommit hook

### ISSUE THREAD

**Issue by rubiesonthesky** [mdn/content#20727]
I'm reporting this as Github issue because that was wished in Matrix discussion :)

Trying to commit using graphical git client (Fork v2.21, MacOs 12.5.1) produces now errors after husky & precommit hook was added. 

```
env: node: No such file or directory
husky - pre-commit hook exited with code 127 (error)
husky - command not found in PATH=(omited actual line)
```

This does not happen if using git cli. But there were comments that this may be happening also with other non-command line clients / VS code.

**Comment by Josh-Cena** [comment]
Closing because I don't think anyone else has reported it lately, and it's been open for almost 2 years now
