### ISSUE TITLE
Event.returnValue: further deprecation information needed

### ISSUE THREAD

**Issue by i-mw** [mdn/content#20730]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Event/returnValue

### What specific section or headline is this issue about?

Deprecated headline & Compatibility table

### What information was incorrect, unhelpful, or incomplete?

Deprecated headline says that this feature is, obviously, deprecated, despite it being the only working feature across all browsers (preventDefault() doesn't work in Chrome)..
With return 'string' not also working in any browser as I've shown in this [issue](https://github.com/mdn/browser-compat-data/issues/17796)..

More information should be added, as, there's no way to show the unsaved prompt in chrome without this property (returnValue)..

Another problem is that, it's compatibility table isn't consistent with compatibility table in [beforeunload event page](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) 

### What did you expect to see?

More information on the situation, and not just run developers away from it without any working alternative around..
There's no other working solution other than it.. So, that has to be said, if you don't want to remove the Deprecated header.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/event/returnvalue`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Event/returnValue
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/event/returnvalue/index.md
* Last commit: https://github.com/mdn/content/commit/1511e914c6b1ce6f88056bfefd48a6aa585cebce
* Document last modified: 2022-09-09T05:10:34.000Z

</details>

**Comment by Josh-Cena** [comment]
There's more information in https://developer.mozilla.org/en-US/docs/Web/API/BeforeUnloadEvent/returnValue. Since it's (a) supported in Chrome now, (b) never had consistent behavior before Chrome implemented `preventDefault` for `BeforeUnloadEvent` anyway, I don't think we need to do anything special here.
