### ISSUE TITLE
Possible typo in How to write in markdown page about syntax highlighting

### ISSUE THREAD

**Issue by rubiesonthesky** [mdn/content#20733]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN

### What specific section or headline is this issue about?

Example code blocks

### What information was incorrect, unhelpful, or incomplete?

The list says that PowerShell should be marked as `ps` but I think it's incorrect

```
  - `ps` - PowerShell
```

Prism does not list that as alias for PowerShell: https://prismjs.com/#supported-languages

Also it does not seem to be custom alias added here https://github.com/mdn/yari/blob/main/build/syntax-highlight.ts

I'm not sure if this is defined somewhere else and thus listed correctly.

### What did you expect to see?

```
  - `powershell` - PowerShell
```

**Comment by Josh-Cena** [comment]
Correct—using `ps` will show "Unable to find a Prism grammar for 'ps'"
