### ISSUE TITLE
Speech recognition getting 'language not supported' error

### ISSUE THREAD

**Issue by deehuynh** [mdn/content#20749]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API

### What specific section or headline is this issue about?

Speech recognition getting 'language not supported' error

### What information was incorrect, unhelpful, or incomplete?

I was gotten error 'language not supported' on the Edge browser. Is this problem caused by the SpeechRecognition API?

### What did you expect to see?

Information about the 'language not supported' error of the SpeechRecognition API

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_speech_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_speech_api/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #21031 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
