### ISSUE TITLE
HTTP headers landing page makes overly specific references to HTTP/1.1

### ISSUE THREAD

**Issue by LPardue** [mdn/content#20744]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

### What specific section or headline is this issue about?

The intro section

### What information was incorrect, unhelpful, or incomplete?

> HTTP headers let the client and the server pass additional information with an HTTP request or response. An HTTP header consists of its case-insensitive name followed by a colon (:), then by its value. [Whitespace](https://developer.mozilla.org/en-US/docs/Glossary/Whitespace) before the value is ignored.

This is overly specific to how HTTP/1.1 formats fields. 

In RFC 9110 (HTTP semantics), the definition of HTTP fields has been made more general and then specific serialization concerns have been delegated to each HTTP version document (HTTP/1.1 uses one format, HTTP/2 and HTTP/3 use a different one).

### What did you expect to see?

We probably want to introduce headers more generally - before then talking about the specifics of how headers are serialized in each HTTP version. This needs some care to ensure it is logically consistent, and that the references to RFCs are directly related to the subject matter.

### Do you have any supporting links, references, or citations?

https://httpwg.org is the most canonical source

### Do you have anything more you want to share?

Given that this probably needs to incorporate mention of HTTP/2 and HTTP/3, it might make sense to do it as part of that project.

One thing that *will* stick out to developers is that implmentations (browsers, wireshark, curl, servers, etc ) tend to pick a presentation format for HTTP header fields that looks like HTTP/1.1. However, "on the wire" the fields are sent in a potentially different format. By fixing up this page, we'll stumble over that problem and need to take care to present things clearly to the reader.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/index.md
* Last commit: https://github.com/mdn/content/commit/1fb2843562076484f518705129ba9b64cabad30e
* Document last modified: 2022-09-12T20:36:22.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting. There's been no changes that fix this in the meantime, so I think this is still true on the current version.
