### ISSUE TITLE
HTML example with pipes in title

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#20759]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement

### What specific section or headline is this issue about?

HTML

### What information was incorrect, unhelpful, or incomplete?

I noticed that the `<title>` in the HTML code snippet at https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement#basic_example contains `||` around the text.

I can imagine that this is a leftover from Kuma days.

### What did you expect to see?

In case it is not intended, the `<title>` should have no special characters (such as `|`).

### Do you have anything more you want to share?

Changes are needed in

https://github.com/mdn/content/blob/00f17a631ded6421c70089f8564cadff05391bf3/files/en-us/web/api/document/createelement/index.md#html

I haven't checked other HTML pages. Perhaps it can be done in one sweep.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document/createelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/createelement/index.md
* Last commit: https://github.com/mdn/content/commit/77b8cdb3a05999ade4a269d0ef2443618bb7cd66
* Document last modified: 2022-09-13T13:39:19.000Z

</details>

**Comment by wbamberg** [comment]
I could only find that one with:

```
rg ">\\|\\|" ./files
```

...but my rg skills are meager.

**Comment by bsmth** [comment]
Same here (looks like I don't have to escape the pipes etc.):

```bash
grep -r ">||" files
files/en-us/web/css/value_definition_syntax/index.md:      <td><code>||</code></td>
files/en-us/web/api/document/createelement/index.md:    <title>||Working with elements||</title>
files/en-us/web/javascript/guide/expressions_and_operators/index.md:        <a href="/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR">Logical OR </a>(<code>||</code>)
files/en-us/web/javascript/guide/expressions_and_operators/index.md:        values, <code>||</code> returns <code>true</code> if either operand is
```

Looks like the only occurrence; I will open a PR to fix.
