### ISSUE TITLE
Better with let instead of const count = animals.push('cows'); in push() documentation?

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [mdn/content#20758]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push

### What specific section or headline is this issue about?

const count = animals.push('cows');

### What information was incorrect, unhelpful, or incomplete?

Hi! I'm a beginner JavaScript student and was wondering why const count was used for the returned value of the push() method. I was taught that constants are used for values that don't change but in this example it is pretty easy to for example add count = animals.push('chickens'); and get an error (Error: Assignment to constant variable.)

Is this just a standard in the documentation or would it be better to change it to for example
let count = animals.push('cows');  
?

### What did you expect to see?

let count = animals.push('cows');

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/push`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/push/index.md
* Last commit: https://github.com/mdn/content/commit/87a9f73c410c9b9e91300695c8aa4931367243fb
* Document last modified: 2022-09-13T07:01:32.000Z

</details>

**Comment by adFuckYou** [comment]
Happy to provide you with any information that would help,
Or what programs were used and/or why I always end up being the native token, the token adress sometimes and my wallet address😭

**Comment by adFuckYou** [comment]
Sorry  I’m trying to change my name, I made the account after it happened, and my way of getting my stuff back or learning how to code to fuck with them, was and still am furious

**Comment by adFuckYou** [comment]
If anyone can help me locate names then OpenSea will ban them, and we can burn $100k JPEGS haha

**Comment by Josh-Cena** [comment]
@adFuckYou Please stop spamming in unrelated threads.

**Comment by adFuckYou** [comment]
Sorry about that I didn’t know I was spamming 
, this guy just did it for me without asking or telling me

**Comment by adFuckYou** [comment]
I just thought that was really kind and helpful, I didn’t tell him to exclude anything, if one wants to be malicious then go ahead, as long as 1 group of hackers are taken out

**Comment by adFuckYou** [comment]
Apologies again and thank you for opening it up agajn, tired learning how throughout the night, but warning signs kept on telling me that I’m going to screw up and hand it over to them

**Comment by henrikvilhelmberglund** [comment]
Thanks for the explanation!
