### ISSUE TITLE
Clarify sharing objects with page scripts impact on build a cross browser extension

### ISSUE THREAD

**Issue by rebloor** [mdn/content#20779]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

### What information was incorrect, unhelpful, or incomplete?

Firefox supports a mechanism to use `window.promise` to create a Promise accessible to the webpage from  content scrip. This mechanism is explained on the [Sharing objects with page scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts) page but not clarified on [Build_a_cross_browser_extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension).

### What did you expect to see?

Information on [Build_a_cross_browser_extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension) about passing a promise, linking to (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts)

**Comment by Rob--W** [comment]
This can be resolved by adding a section to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension that highlights the differences between content script execution contexts:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#content_script_environment

Although not part of this issue originally, it's also worth removing the "December 2021" banner at the top, and to make the content up-to date:

- [API asynchronous event handling](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension#api_asynchronous_event_handling) section: Chrome's MV3 supports promises.
- A section that mentions the existence of Manifest V2 and Manifest V3. The current content at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/manifest_version is unfortunately very sparse... I think that I may have to bootstrap additional content for that article. For now the bare minimum could be to link to the MV2->MV3 migration guides from Firefox and Chrome: https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/ and https://developer.chrome.com/docs/extensions/migrating/
- Link the background "Browser support" section that was added in https://github.com/mdn/content/pull/30097
