### ISSUE TITLE
Russian translation in guides.

### ISSUE THREAD

**Issue by yaneyard** [mdn/content#2078]
Hello! You have a problem with the Russian guide on your site. When you go to the next part by pressing the "Next" button. For example it redirects to the address "/ru/docs/Learn/HTML/Introduction_to_HTML/Debugging_HTML" instead of "/ru/docs/Learn/HTML/Введение_в_HTML/Структура_документа_и_веб-сайта". Therefore, you have to switch the language again.

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
