### ISSUE TITLE
Issue with "Hoisting": (short summary here please)

### ISSUE THREAD

**Issue by himanshugsn** [mdn/content#2080]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

#### What information was incorrect, unhelpful, or incomplete?
// Example with let:
a = 1; // initialization.
let a; // Throws ReferenceError: Cannot access 'a' before initialization

#### Specific section or headline?
Initializations using let and const are also not hoisted.

#### What did you expect to see?
a = 1; // initialization.
let a; // undefined

#### Did you test this? If so, how?

yes, by using the following code
a  = 1;
let a;
console.log(a);

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/hoisting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/glossary/hoisting/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by avivmu** [comment]
Try to write 
```
a = 1;
let a;
```
together and not line by line. When you write them line by line then you define a property `a` on the global object. See [this SO answer](https://stackoverflow.com/questions/6888570/declaring-variables-without-var-keyword) for more information
Please close this issue

**Comment by Rumyra** [comment]
Closing as the in page code is correct
