### ISSUE TITLE
MDN globalThis tangential

### ISSUE THREAD

**Issue by GarrettS** [mdn/content#20813]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

### What specific section or headline is this issue about?

Polyfills

### What information was incorrect, unhelpful, or incomplete?

The page contains opinionated coding on Polyfills that is not relevant and is a confusing distraction.

The `globalObject` example code supplied by the author doesn't help for the Polyfill example, which again serves no purpose on discussion about the global object. 

### What did you expect to see?

Discussion of globalThis.

**Comment by Josh-Cena** [comment]
Could you elaborate? This page discusses the exact same motivation as in the original proposal: https://github.com/tc39/proposal-global.

**Comment by Josh-Cena** [comment]
I'm going to make a judgment call and close this issue. I (on behalf of the content team) believe the content accurately represents the intended use case of `globalThis`. This page does not describe "global object" as an abstract JS concept, but `globalThis` as a concrete API. Both in terms of the original design motivation and its actual usage in the wild, I'm confident to say that the major use case of `globalThis` remains to be polyfill authors and other scenarios where you wish to write to the global object. More examples are welcome—but this page is fine as-is and does not have anything tangential.

**Comment by GarrettS** [comment]
Even your globalThis polyfill does not make a reliable patch for globalThis.

Please see:
https://github.com/tc39/proposal-global#html-and-the-windowproxy

**Comment by Josh-Cena** [comment]
I'm not sure what you mean. In JavaScript land you can only ever get WindowProxy. You can never ever get the actual window object. Both `globalThis` and the `window` will return the exact same object. Plus in case it wasn't clear, that code (1) illustrates how painful and error-prone polyfills for _other_ APIs are _without_ `globalThis` (2) is a verbatim copy of the actual polyfill for `globalThis` that is used in production by millions of sites and is audited by the spec authors themselves.
