### ISSUE TITLE
TouchEvent.touches: is the array ordered?

### ISSUE THREAD

**Issue by danieltroger** [mdn/content#20811]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/touches

### What information was incorrect, unhelpful, or incomplete?

I want to know if I can assume`TouchEvent.touches[0]` to always be the first finger/thing that touched the surface, `TouchEvent.touches[1]` to be the second thing that touched the surface, etc.

### What did you expect to see?

I know this isn't a QA site and I think I'll just assume it for now since it makes sense that it would be like this. But for a site providing "documentation" I think it would be good to mention in what order the touches are in `TouchEvent.touches` - is it just random? Is it in the order of which touch last changed? Or is it in the order they actually were added? It makes it easier to make safe assumptions to write robust code.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/touchevent/touches`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/touches
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/touchevent/touches/index.md
* Last commit: https://github.com/mdn/content/commit/7455f0c585ea29fa85ea09e11716b70f76241f5b
* Document last modified: 2022-09-11T19:35:30.000Z

</details>

**Comment by Josh-Cena** [comment]
See https://github.com/w3c/touch-events/issues/13 We should recommend people to not rely on any ordering, but only each `Touch`'s ID.

**Comment by advitiya7** [comment]
Hey i want to contribute to this can anyone exactly explain the problem ? Thank you

**Comment by teoli2003** [comment]
You need to add a sentence or two with the recommendation that the order in the list being independant of the actual order the touches happen. To determine the latter, developers should rely on the `Touch` object IDs

**Comment by advitiya7** [comment]
So like i have to add that it can give any random number from the array if i use touchevent.touches and i want a specific sorted order i should use touch id?

**Comment by teoli2003** [comment]
No, it doesn't give you any random number of the array. Merely, the array is not ordered predictably (it depends on the implementation): a developer cannot **assume** a specific order, like the i-th element in the array being the i-th touch that happened). Even if implementations don't randomize this order when creating the array, the developers should assume they could have done it.

**Comment by advitiya7** [comment]
Think i got you so i have to add that devlopers can't just assume and just that the order of touch is not related in any way to the array order?

**Comment by advitiya7** [comment]
I think you explained the whole issue plus the answer to me that has to be added so thank you for that.I am really sorry if i am bothering you with this.

**Comment by teoli2003** [comment]
In your PR description add `Fix #20811`, so it is automatically linked to this issue (a handy GitHub feature 😄 )

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/25822
