### ISSUE TITLE
Issue with "Hoisting": (short summary here please)

### ISSUE THREAD

**Issue by himanshugsn** [mdn/content#2081]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

#### What information was incorrect, unhelpful, or incomplete?
a = 'Cran'; // Initialize a
b = 'berry'; // Initialize b

console.log(a + "" + b); // 'Cranberry'

#### Specific section or headline?
last section

#### What did you expect to see?
a = 'Cran'; // Initialize a
b = 'berry'; // Initialize b

console.log(a + "" + b); //  

#### Did you test this? If so, how?
"ReferenceError: a is not defined
    at <anonymous>:3:3"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/hoisting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/glossary/hoisting/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by himanshugsn** [comment]
Please assign me this issue I will be able to resolve it!

**Comment by avivmu** [comment]
No problem here. Paste this as one block and run it:
`a = 'Cran'; // Initialize a
b = 'berry'; // Initialize b
console.log(a + "" + b); // 'Cranberry'`
It prints `Cranberry` as expected. Please close the issue

**Comment by Ryuno-Ki** [comment]
Confirmed.

```js
// Example 2
// No hoisting, but since initialization also causes declaration (if not already declared), variables are available.

a = 'Cran'; // Initialize a
b = 'berry'; // Initialize b

console.log(a + "" + b); // 'Cranberry'
```
is printing `Cranberry` to me. Closing.
