### ISSUE TITLE
Don't capitalize events

### ISSUE THREAD

**Issue by TheKleyn** [mdn/content#20829]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Events

### What specific section or headline is this issue about?

List of Events

### What information was incorrect, unhelpful, or incomplete?

Shouldn't the Event List table be listed without caps for the entries? As far as I understand they will not work if they are put with a first capital letter, into JS. This may confuse people with less experience. It did for me.

### What did you expect to see?

no caps

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/events/index.md
* Last commit: https://github.com/mdn/content/commit/26de76d3684b4c61684618cecb18e71c8fed93d5
* Document last modified: 2022-09-16T18:48:33.000Z

</details>

**Comment by Josh-Cena** [comment]
@TheKleyn In the "event listing" section, the event names like "languagechange event" accurately reflect their actual casing. Do you have specific examples where the casing is wrong and/or confusing?

**Comment by TheKleyn** [comment]
you're right, sorry
