### ISSUE TITLE
"Black screen" video playing on Slack

### ISSUE THREAD

**Issue by barcadams0** [mdn/content#2082]
Dear Firefox community,
I faced an issue today.  I uploaded a video to a Slack forum thread, it is embededd , I can see the videos' "screen" but  when I press play, i got only a black screen with audio. I've already checked the forums considering this issue, in any case disabling hardware accelaration and disabling extension were advised, I tried this disabling these, but nothing happened.
Of course I have the latest version of Firefox
What can be done, or will it be fixed by an update? 

Thanks in advance,
Yours sincerely,
Ádám
![Unbenannt](https://user-images.githubusercontent.com/71493000/106948553-201e2300-672c-11eb-8ecc-6e184b7a9b19.JPG)

**Comment by chrisdavidmills** [comment]
Hi @barcadams0 !

This repo is for filing issues specifically about the content of https://developer.mozilla.org/en-US/. For general Firefox issues, I'd recommed filing a bug on https://developer.mozilla.org/en-US/, or asking about it in an appropriate Matrix room: https://wiki.mozilla.org/Matrix
