### ISSUE TITLE
supported clone types missing BigInt

### ISSUE THREAD

**Issue by jimmywarting** [mdn/content#20833]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

### What specific section or headline is this issue about?

supported types table

### What information was incorrect, unhelpful, or incomplete?

the table of supported types is missing BigInt types

### What did you expect to see?

support for BigInt

### Do you have any supporting links, references, or citations?

```js
structuredClone(2n) // works fine
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_workers_api/structured_clone_algorithm`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_workers_api/structured_clone_algorithm/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by Josh-Cena** [comment]
The first row of the table says "All primitive types"?
