### ISSUE TITLE
bad link in HTTP logging page

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#2085]
https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging
click the link for "Necko" (https://developer.mozilla.org/en-US/docs/Necko) -> page not found

**Comment by hamishwillee** [comment]
@JustinWebDev We don't fix links in archived pages - that's part of what archived means.

**Comment by JustinWebDev** [comment]
Sorry - that registered with me after I filed the issue.
