### ISSUE TITLE
Reference in browser extension documentation to obsolete "Iconography" page 

### ISSUE THREAD

**Issue by philipmgrant** [mdn/content#20860]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_action

### What specific section or headline is this issue about?

Icons

### What information was incorrect, unhelpful, or incomplete?

There's a link to an Iconography page ([destination](https://design.firefox.com/photon/visuals/iconography.html)) which declares itself to be no longer maintained since the 2021 design refresh release.

### What did you expect to see?

A link to a current and maintained page.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/user_interface/browser_action`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_action
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/user_interface/browser_action/index.md
* Last commit: https://github.com/mdn/content/commit/1ee49b729dc4cd02b862d910f279861f4b30e704
* Document last modified: 2022-09-09T05:03:45.000Z

</details>

**Comment by rebloor** [comment]
Banner on the Photon site states "A new site for the Firefox design system will replace this in the future."
