### ISSUE TITLE
Callback syntax for RTCPeerConnection: setRemoteDescription isn’t listed in the deprecated-JavaScript features index

### ISSUE THREAD

**Issue by Dmole** [mdn/content#2086]
Currently the list
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features
is incomplete, eg it's missing
    https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setRemoteDescription#deprecated_syntax
.
If there were a Standardized Deprecated format like better use of the {{deprecated_inline}}
the Deprecated_and_obsolete_features list could be auto updated, and added to eslint.

**Comment by Dmole** [comment]
Another example;

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

recommends usage of a deprecated API without saying so;

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by Ryuno-Ki** [comment]
Not quite. I asked Chris the same a while ago: https://github.com/mdn/content/issues/1807#issuecomment-768971712

**Comment by hamishwillee** [comment]
@chrisdavidmills I agree with the sentiment here. It is much more scalable and reliable to dynamically generate these kinds of lists from "tagged" content than to try to manually keep them up to date. In this case the "tag" might be use of the `{{deprecated_inline}}` macro.

If you agree we should open a discussion on yari for this.

Note: This is basically the same approach I am proposing we use (eventually) for the events reference, and why I suggested that being able to created lists from tags is a good idea. 


@Dmole In the meantime, would you be able to add the missing features to the list?

**Comment by Ryuno-Ki** [comment]
I've opened https://github.com/mdn/yari/issues/2903 as issue and will fill a discussion (looks like Referencing feature of GitHub does not support this right now).

**Comment by Rumyra** [comment]
Going back to the original issue the depreciated feature is a Web API feature, whereas the Depreciated and obsolete features lists javascript language features.

I'm unaware of any depreciated list for web apis (which honestly I think would be cumbersome).

I'm inclined to close this issue as the depreciated method is listed where it should be and there are other discussions around how such things are handled.

**Comment by jpmedley** [comment]
Since there's a `deprecated` field in the browser compatibility data, a list could easily be generated from that.

**Comment by Dmole** [comment]
@hamishwillee as far as I see there is no official source of deprecated JavaScript usage (as so much is outside the IETF and ECMA).

@Rumyra The point is to make documenting depreciated usage of the Web APIs less cumbersome, to help avoid future security issues etc. Depreciated Web APIs methods are not consistently listed (as shown in the links above).

@jpmedley The reason for this issue is I tried scripting a list of deprecated JavaScript Web API only to find the data (regardless of how scattered it was) was lacking/inconsistent.

**Comment by hamishwillee** [comment]
So @Rumyra is correct in that we would not expect Web API deprecations to be in the Javascript obsolesce list. If the Javascript list is incorrect, which it may be, that would be a different bug.

IMO @jpmedley is correct too. If there is a deprecated tag in the browser compatibility system then that is the right and "standard" place for this information to be recorded. After all, deprecation is on the lifecycle of something being removed, which is the whole point of the BCD.

It _should_ be possible to generate the list of deprecated Web APIs need from the BCD (whether it is useful to do so is a separate question, on which I have no opinion). If you can't, as you indicate, or if there are inconsistencies between what it says on MDN and the BCD then those are content bugs that we should fix. However again, they would be a separate bug to this. 

Does that make sense?

If so, 
- can you create specific bugs for the problem cases you see in Web APIs? For example you posted this one: https://github.com/mdn/content/issues/2086#issuecomment-776954124 ?
- please close this particular issue (or I will next time I come round to it).

**Comment by jpmedley** [comment]
>whether it is useful to do so is a separate question, on which I have no opinion

This would be tremendously useful. As part of trying to fill a backlog of features Chrome contributed to the platform I run a periodic report of what's missing. This would help me keep an accurate [list of what has lower priority or doesn't need to be documented at all](https://github.com/jpmedley/mdn-helper/blob/main/config/default.json#L22).

**Comment by Dmole** [comment]
As per @hamishwillee's comment I have made a [new issue](https://github.com/mdn/content/issues/3851) that is more clear.

**Comment by hamishwillee** [comment]
>> whether it is useful to do so is a separate question, on which I have no opinion

> This would be tremendously useful. As part of trying to fill a backlog of features Chrome contributed to the platform I run a periodic report of what's missing. This would help me keep an accurate list of what has lower priority or doesn't need to be documented at all.

@jpmedley Obviously it is easy to generate a list from BCD "privately" - here's a quick one that I generated using Python: https://gist.github.com/hamishwillee/2c2b26f478a15c7e588289ff3b128283 (this only shows the first level where it encounters a deprecated status - it assumes everything nested below is also deprecated)

Would the "right way" to generate this list be a node script run from yari in CI on a regular basis? If so, then we should request this of the dev team.

What formatting/cross-linking would you find useful on such a page, if any? 

Next step would be to cross reference this with places in the main content that use the `{{deprectated_inline}}` macro and then do a round trip to fix up the bcd right?
