### ISSUE TITLE
Misspelling "th" attribute "colspan" should be "colSpan" and "rowspan" should be "rowSpan"

### ISSUE THREAD

**Issue by JianpingChen** [mdn/content#20862]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th

### What specific section or headline is this issue about?

Attributes

### What information was incorrect, unhelpful, or incomplete?

 "colspan" should be "colSpan" and "rowspan" should be "rowSpan"

### What did you expect to see?

 "colspan" should be "colSpan" and "rowspan" should be "rowSpan"

### Do you have any supporting links, references, or citations?

Tested in Chrome. "colspan" and "rowspan" are undefined. "colSpan" and "rowSpan" has default value of 1.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/th`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/th/index.md
* Last commit: https://github.com/mdn/content/commit/2ae0bf5285e683f92abc0fb51a6523b68cc66702
* Document last modified: 2022-08-28T05:12:31.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! These are HTML element attributes (e.g. `<th rowspan="1" />`), which are case-insensitive and are traditionally lowercase. For its corresponding DOM API, please see [`HTMLTableCellElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement).
