### ISSUE TITLE
instructions in HTTP logging page don't work

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#2087]
https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging#Windows
-> no log file is produced
I had to use the above 12-step instructions to get a log file.

The page says it is not maintained, but Fx devs still point people to it for debugging.

**Comment by hamishwillee** [comment]
@JustinWebDev 
- Who/where is pointing to it for debugging? Essentially I want to talk to them about whether this should be unarchived, and what might no longer be relevant.
- Did you try the command line options: https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging#Start_logging_using_command_line_arguments ?

**Comment by JustinWebDev** [comment]
See Kershaw's comments on bugzilla, https://bugzilla.mozilla.org/show_bug.cgi?id=1686847#c6

Yes, I had to use the CLI.

**Comment by hamishwillee** [comment]
@chrisdavidmills Some advice please. 

The page  https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging  is archived and at least one section doesn't work. BUT, this is being pointed to as a reference in [bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1686847#c6) and in Firefox itself if you go to `about:networking#logging`.

I asked on chat.mozilla.org and it was suggested that maybe the doc be moved to https://firefox-source-docs.mozilla.org/ 

Anyway, this certainly seems useful and should be brought back to life - do you think it should be on MDN or https://firefox-source-docs.mozilla.org/ ? If the former, can you please unarchive it (or explain how I do that) or if the later, tell me who we talk to.?

I can then try to fix it up.

**Comment by chrisdavidmills** [comment]
This sounds like something that should be moved to the firefox source docs. It is already on the list of things to migrate that the Fx engineers are working through. I've ping those involved in that to bring it to their attention.

**Comment by Ryuno-Ki** [comment]
Would it make sense to have a label for Firefox engineers?
This way, they can filter for what's relevant to them.

**Comment by JustinWebDev** [comment]
Just make sure you change the link in Fx about:networking#logging page!  I think this might re-enforce the need to keep the page current.

**Comment by hamishwillee** [comment]
@chrisdavidmills Thanks. Is there an issue we can link for the migration to the firefox source docs? What I'd like to do is file an issue  against firefox to update about:networking#logging when the doc is migrated and ensure that the version in archive ends up being deleted.

That would allow me to close this issue :-)

**Comment by chrisdavidmills** [comment]
> Would it make sense to have a label for Firefox engineers?
> This way, they can filter for what's relevant to them.

No; they're already handling this in a different way

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills Thanks. Is there an issue we can link for the migration to the firefox source docs? What I'd like to do is file an issue against firefox to update about:networking#logging when the doc is migrated and ensure that the version in archive ends up being deleted.
> 
> That would allow me to close this issue :-)

There isn't really an issue to link; there's just a spreadsheet that all the stuff to migrate is recorded on. It is basically implicit that once migrated, we'll redirect to the new location and delete the old page.

**Comment by valenting** [comment]
I have moved the docs to source-docs - https://firefox-source-docs.mozilla.org/networking/http/logging.html
What is the process to set up a redirect / link to the new page?

**Comment by chrisdavidmills** [comment]
@valenting thanks for that!

@peterbe @escattone  is there anything special we have to do to set up a redirect from an old MDN URL to an external one? We can't just do that via the redirects file, right?

**Comment by escattone** [comment]
@chrisdavidmills 
> @peterbe @escattone is there anything special we have to do to set up a redirect from an old MDN URL to an external one? We can't just do that via the redirects file, right?

What we can do in this case is the following:
1. First, submit a PR to remove https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/debugging/http_logging. It doesn't have any translations, so that's all there is.
2. Normally, from the content repo, you could then run:

    ```sh
    yarn
    yarn add-redirect /en-US/docs/Mozilla/Debugging/HTTP_logging https://firefox-source-docs.mozilla.org/networking/http/logging.html
    ```
    but that won't work from the archived-content repo, so I'll do that for now.

Does that make sense? I'll go ahead and do those things, and request you for review.

**Comment by escattone** [comment]
@chrisdavidmills I'm discovering that it's a bit more complicated than I thought when doing this for archived content.

**Comment by escattone** [comment]
@chrisdavidmills FYI. https://github.com/mdn/archived-content/pull/11

**Comment by chrisdavidmills** [comment]
@escattone thanks!

So we remove the archived article, then run a redirect command to add the redirect to _redirects.txt (I didn't realize that you could use that to redirect to exeternal URLs, so that's a nice discovery for me)

And then it looks like you've gone through the archived-content directory and done a find and replace to change the previous URL instances to point to the redirect URL instead...I guess because archived-content doesn't use _redirects.txt?

**Comment by escattone** [comment]
@chrisdavidmills What you described would work for the content repo, but we don't yet have a good story for the archived-content repo, so I had to do everything manually:
- Remove the archived article(s)
- Add the redirect(s) manually to the appropriate `_redirects.txt` file(s) by locale (e.g., https://github.com/mdn/archived-content/blob/main/files/en-us/_redirects.txt)
- Once the archived-content PR is merged, re-generate the `archived.txt` file in the yari repo (https://github.com/mdn/yari/blob/main/content/archived.txt) (we're going to work on improving this step as well as making it easier) 

We need to improve this if we do it more often, but for now, request one of the dev team, and we'll do it for you manually.

**Comment by chrisdavidmills** [comment]
OK, thanks @escattone !

**Comment by himanshugarg** [comment]
The page has now moved . Is there more to this issue?

**Comment by escattone** [comment]
One of the MDN dev team will need to add a redirect for this and other pages that have been moved, but we're really consumed with other tasks at the moment, so that might take a while longer.

**Comment by hamishwillee** [comment]
Hi @escattone,

The discussion is a bit twisted, but it looks like some files in the archive needed to be redirected to https://firefox-source-docs.mozilla.org/networking/http/logging.html and that you fixed this in the archive.

So what remains for MDN dev team? I.e. I can create a redirect if I know the "from" and "to", but it isn't obvious what they are.

**Comment by hamishwillee** [comment]
Well, we're doing nothing then :-(

**Comment by escattone** [comment]
@hamishwillee Sorry for this dragging on, but it seemsquite a bit simpler now that we've dumped the archived content. I've submitted https://github.com/mdn/content/pull/10576 which should resolve this issue.

**Comment by hamishwillee** [comment]
Thanks @escattone ! Awesome to see this gone away at last.
