### ISSUE TITLE
NotRelease: [CSS] contain-intrinsic-size supported

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#20876]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Tracking https://bugzilla.mozilla.org/show_bug.cgi?id=1597529

https://bugzilla.mozilla.org/show_bug.cgi?id=1782529
https://bugzilla.mozilla.org/show_bug.cgi?id=1782540
https://bugzilla.mozilla.org/show_bug.cgi?id=1782589
https://bugzilla.mozilla.org/show_bug.cgi?id=1782673
https://bugzilla.mozilla.org/show_bug.cgi?id=1783296

**Comment by hamishwillee** [comment]
Status/Investigation.

I think this feature is being devleopmed

**Comment by hamishwillee** [comment]
Status:
- BCD - https://github.com/mdn/browser-compat-data/pull/17840
- Docs
- Experimental features
- dev-doc-complete:

**Comment by hamishwillee** [comment]
I think this is all pretty much done except the reviews and sidebar stuff in https://github.com/mdn/data/pull/606

That is supposed to add all the inter-links. However for some reason at least some of this is generating. So waiting on info to explain why.

**Comment by Rumyra** [comment]
This looks closable - thank you @hamishwillee
