### ISSUE TITLE
NotReleased [HTTP] CSP script- and style- 'src-elem' and 'src-attr' directives

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#20878]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

BCD updates + Experimental features

## Related Gecko bugs

- https://bugzilla.mozilla.org/show_bug.cgi?id=1529337 : Implement CSP 'script-src-elem' and 'script-src-attr' directives
- https://bugzilla.mozilla.org/show_bug.cgi?id=1529338 Implement CSP 'style-src-elem' and 'style-src-attr' directives

## Other

Nightly only features. Needs BCD and experimental features only.

```
# The script-src-attr and script-src-elem directive
- name: security.csp.script-src-attr-elem.enabled
  type: bool
  value: @IS_NIGHTLY_BUILD@
  mirror: always

# The style-src-attr and style-src-elem directive
- name: security.csp.style-src-attr-elem.enabled
  type: bool
  value: @IS_NIGHTLY_BUILD@
  mirror: always
```

**Comment by hamishwillee** [comment]
Status

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/17834
- [ ] Docs - Not needed
- [ ] Experimental features
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
Thanks @hamishwillee
