### ISSUE TITLE
Bound functions don't have static class fields

### ISSUE THREAD

**Issue by Worldwidebrine** [mdn/content#20880]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind

### What specific section or headline is this issue about?

Bound functions used as constructors

### What information was incorrect, unhelpful, or incomplete?

Bound functions can be used as constructors.
But can't be used as classes because static properties are ignored.

### What did you expect to see?

Just "static properties of class are ignored"

### Do you have anything more you want to share?

```js
function Classic() {
    console.log("construct")
}
Classic.prototype = { // instance prop
    testInstanceProp: "suc"
};
Object.assign(Classic, { // static prop
    testStaticProp: "suc"
});

class Real {
    constructor() {
        console.log("construct")
    }
    testInstanceProp = "suc";
    static testStaticProp = "suc"
}


console.log(".testStaticProp =", Classic.testStaticProp);
const TestClassic = Classic.bind({});
console.log(".bind({}).testStaticProp =", TestClassic.testStaticProp);

console.log(".testStaticProp =", Real.testStaticProp);
const TestReal = Real.bind({});
console.log(".bind({}).testStaticProp =", TestReal.testStaticProp);
```
> .testStaticProp = suc
> .bind({}).testStaticProp = undefined
> .testStaticProp = suc
> .bind({}).testStaticProp = undefined

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/function/bind`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/function/bind/index.md
* Last commit: https://github.com/mdn/content/commit/d6ce8fcbbc4a71ec9209f379e5ea9774bbf1f5ac
* Document last modified: 2022-09-13T07:06:03.000Z

</details>

**Comment by Josh-Cena** [comment]
Yes, I think that's very important. Thanks for bringing this up!

**Comment by Worldwidebrine** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#bound_functions_used_as_constructors
> The only difference is that it can no longer be used for `extends`.

It also needs to be here, I think.

**Comment by Josh-Cena** [comment]
This part is talking about using it as a constructor. The part about classes is below.

**Comment by Worldwidebrine** [comment]
I know but why talk about constructors and clases separately?

**Comment by Josh-Cena** [comment]
_Constructors_ are functions with `[[Construct]]`—period. The fact that they can have other properties is tangential to them being constructible. The sentence you quoted also starts with:

> Note that you need not do anything special to create a bound function for use with [`new`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new).

Which means we are specifically talking about its behavior with `new`, not about its other usages. In addition static properties have also been mentioned before the example, so IMO there's neither ambiguity nor misinformation.

**Comment by Worldwidebrine** [comment]
Move them together, I mean.
[Transforming methods to utility functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#transforming_methods_to_utility_functions) is between constructors and classes

**Comment by Josh-Cena** [comment]
Ah, I got you. I didn't think too much about this. If you want move the class example up, I can review a PR.

**Comment by Worldwidebrine** [comment]
I'm on mobile. Could you do it?
