### ISSUE TITLE
Issue with "CanvasRenderingContext2D.globalCompositeOperation": Examples box is too small

### ISSUE THREAD

**Issue by RyanTheNerd** [mdn/content#2091]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

#### What information was incorrect, unhelpful, or incomplete?
The height of the box with all the types is very short, it makes it hard to read the examples.

#### Specific section or headline?
Syntax -> Types

#### What did you expect to see?
At least enough height to see one whole example at a time. Or even better yet, show all the examples at the same time instead of having to scroll through them in a very small viewport.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/globalcompositeoperation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/canvasrenderingcontext2d/globalcompositeoperation/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by chrisdavidmills** [comment]
Hrm, this is an interesting one. Changing the `height` of the embedding `<iframe>` no longer seems to increase the display height of the example, and I'm not sure why.

Paging @schalkneethling — has anything changed recently on the front-end that might cause this to break?

**Comment by schalkneethling** [comment]
> Hrm, this is an interesting one. Changing the `height` of the embedding `<iframe>` no longer seems to increase the display height of the example, and I'm not sure why.
> 
> Paging @schalkneethling — has anything changed recently on the front-end that might cause this to break?

Yup, we have an issue about this, soon to be resolved. Thanks for bringing this to my attention @chrisdavidmills

**Comment by chrisdavidmills** [comment]
> > Hrm, this is an interesting one. Changing the `height` of the embedding `<iframe>` no longer seems to increase the display height of the example, and I'm not sure why.
> > Paging @schalkneethling — has anything changed recently on the front-end that might cause this to break?
> 
> Yup, we have an issue about this, soon to be resolved. Thanks for bringing this to my attention @chrisdavidmills

Great stuff, cheers mate.

**Comment by Rumyra** [comment]
This appears to be fixed - if @schalkneethling confirms I'll close the issue 👍

**Comment by schalkneethling** [comment]
> This appears to be fixed - if @schalkneethling confirms I'll close the issue 👍

This looks resolved to me, thanks!
