### ISSUE TITLE
[HTML] Implement width/height attributes on source elements

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#20927]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1694741

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if [Glossary](https://developer.mozilla.org/en-US/docs/Glossary) updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.

**Comment by dletorey** [comment]
I shall be taking this as my **first** issue

**Comment by bsmth** [comment]
@dletorey you can now be assigned to issues thanks to @schalkneethling 🎉

**Comment by dletorey** [comment]
Updated the source page to include example of using width & height attribute - https://github.com/mdn/content/pull/21819
Added height & width to the browser-compat-data https://github.com/mdn/browser-compat-data/pull/18081
