### ISSUE TITLE
Label - a string or a identifier?

### ISSUE THREAD

**Issue by ArchivingToolsForWBM** [mdn/content#20938]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/console/time

### What specific section or headline is this issue about?

time(label)

### What information was incorrect, unhelpful, or incomplete?

The article calls this a label, but does not actually state that it should be a string. The user could interpret that they can just put an identifier on there (a line of text without wrapping it in quotes). During testing it is supposed to be a string wrapped in quotes ``console.time("Example")``, not like this: ``console.time(Example)`` as tested in chrome resulted in an error. Same should apply to https://developer.mozilla.org/en-US/docs/Web/API/console/timeEnd

### What did you expect to see?

It should say something like this:

>The label must be a string.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/console/time`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/console/time
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/console/time/index.md
* Last commit: https://github.com/mdn/content/commit/da88b2f3a23b9d93f083003f13c06f9d96073f6a
* Document last modified: 2022-09-13T05:21:27.000Z

</details>

**Comment by wbamberg** [comment]
It doesn't seem like it has to be a string. All the following work, for example:

```js
console.time(undefined);
console.time({});
console.time([1,2,3]);
```

Passing an undefined variable in there is an error:

```js
console.time(hello);
```

...but it's hard to imagine someone thinking this would be OK. Would it be better to call it a "value"?

**Comment by Josh-Cena** [comment]
According to https://console.spec.whatwg.org/#timing it should be a map with string keys. The argument is simply coerced to a string, so you can do this:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/55398995/194684772-fe548942-c70d-410f-b346-c22fd48e4f7a.png">
