### ISSUE TITLE
"async" page - "execution of all code following this is immediately paused"

### ISSUE THREAD

**Issue by robolmos** [mdn/content#20942]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

### What specific section or headline is this issue about?

Control flow effects of await

### What information was incorrect, unhelpful, or incomplete?

"When an await is encountered in code (either in an async function or in a module), execution of all code following this is immediately paused and pushed into the microtask queue"

It could be clearer that it doesn't mean all code following the await, it means all code after the awaited expression.

Also the "microtask queue" links to the Event Loop page which doesn't mention microtasks. Maybe some other link would be more helpful.

### What did you expect to see?

It could be clearer that it doesn't mean all code following the await, it means all code after the awaited expression.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/await`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/await/index.md
* Last commit: https://github.com/mdn/content/commit/1533276490d15cff6ddcd201fc05562180058a99
* Document last modified: 2022-09-13T07:11:16.000Z

</details>

**Comment by Josh-Cena** [comment]
Could you clarify how they differ? You mean in

```js
await a;
b;
```

The `a` is immediately kicked off, just that `b` is paused?

**Comment by promet99** [comment]
Yes, @Josh-Cena . The code below from the article is a good evidence.

```
async function foo(name) {
  console.log(name, "start");
  await console.log(name, "middle");
  console.log(name, "end");
}

foo("First");
foo("Second");
```
```
// Output
First start
First middle
Second start
Second middle
First end
Second end
```

**Comment by promet99** [comment]
Here is the ECMAScript Spec Doc regarding ```await``` keyword: https://tc39.es/ecma262/#await

It basically means ```await value``` will make ```value``` into promise, the promise is executed, and all codes after ```value``` will be executed once the promise is resolved.

Therefore, below would be an adequate explanation that is both correct and simple:
When an ```await``` is encountered in code (either in an async function or in a module), the awaited expression is executed, and all code that follows is paused and pushed into the microtask queue
