### ISSUE TITLE
Example uses barcode.rawData instead of barcode.rawValue

### ISSUE THREAD

**Issue by cmens** [mdn/content#20953]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/BarcodeDetector/detect

### What specific section or headline is this issue about?

Examples 

### What information was incorrect, unhelpful, or incomplete?

barcodeDetector
  .detect(imageEl)
  .then((barcodes) => {
    barcodes.forEach((barcode) => console.log(barcode.rawData));
  })
  .catch((err) => {
    console.error(err);
  });

### What did you expect to see?

barcodeDetector
  .detect(imageEl)
  .then((barcodes) => {
    barcodes.forEach((barcode) => console.log(barcode.rawValue));
  })
  .catch((err) => {
    console.error(err);
  });

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/barcodedetector/detect`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/BarcodeDetector/detect
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/barcodedetector/detect/index.md
* Last commit: https://github.com/mdn/content/commit/418f9cf461de0c7845665c0c677ad0667740f52a
* Document last modified: 2022-09-15T18:16:38.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #21035 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
