### ISSUE TITLE
XUL Page is 404

### ISSUE THREAD

**Issue by colejohnson66** [mdn/content#20961]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Accessibility/XUL

### What information was incorrect, unhelpful, or incomplete?

The page is missing, but liked to by DuckDuckGo and [Wikipedia](https://en.wikipedia.org/w/index.php?title=XUL)

![Screenshot of a DDG search for "mozilla xul" with the first link being the missing page](https://user-images.githubusercontent.com/11381599/191517568-38e13987-8802-4161-9241-64e7c9f3b247.png)

![Screenshot of the Wikipedia page's infobox](https://user-images.githubusercontent.com/11381599/191517777-e9e76223-06f1-4344-b981-ed796b4b2076.png)

### What did you expect to see?

The page not be a 404.

**Comment by bsmth** [comment]
Hi @colejohnson66 thanks a lot for opening the issue. I took a look through and it looks like all documentation has been deprecated and removed from MDN for XUL. I found a [related issue](https://github.com/mdn/content/issues/12890) on this one and the conclusion from that is there is no appropriate redirect we can add for this.

I'm going to close this issue for now. If you think I'm mistaken, feel free to comment again here. Thank you :)
