### ISSUE TITLE
Misstake in German Version of Destructing Assignment #115

### ISSUE THREAD

**Issue by CreaTorAlexander** [mdn/content#2102]
> Zu beachten ist, dass ein SyntaxError erzeugt wird, wenn auf der linken Seite des Restelements ein trennendes Komma steht:

var [a, ...b,] = [1, 2, 3];
// SyntaxError: rest element may not have a trailing comma

It should be on the right-hand side and not on the left-hand side or in german " [..] auf der rechten Seite"  anstelle "[..]auf der linken Seite"
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Operators/Destrukturierende_Zuweisung

In the english version it is also on the right-hand side.

> Be aware that a SyntaxError will be thrown if a trailing comma is used on the right-hand side of a rest element:

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.

**Comment by CreaTorAlexander** [comment]
Oh sorry than I posted it I thought I forgot to create the issue
