### ISSUE TITLE
Messy text

### ISSUE THREAD

**Issue by falzikla** [mdn/content#21033]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM#using_our_custom_element

### What information was incorrect, unhelpful, or incomplete?

Nothing wrong with that information.

### What did you expect to see?

Tidy text.

### Do you have any supporting links, references, or citations?

No.

### Do you have anything more you want to share?

![gambar](https://user-images.githubusercontent.com/70983461/192088994-b15f07de-44a3-466e-bdb6-79c5c5ec51fe.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/web_components/using_shadow_dom`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/web_components/using_shadow_dom/index.md
* Last commit: https://github.com/mdn/content/commit/df7ea1f5b9ef703b49b1def4e13addf0d6e2a023
* Document last modified: 2022-09-14T12:21:47.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #21034 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
