### ISSUE TITLE
Issue with "URLSearchParams": should mention duplicate parameters and if conversion is lossless

### ISSUE THREAD

**Issue by verhovsky** [mdn/content#2104]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

Questions which I came to the documentation for:

1) How does URLSearchParams handle the same parameter appearing more than once, for example

```js
for (const i of new URLSearchParams("?first=1&second=2&first=3")); { console.log(i) } // ["first", "1"] ["second", "2"] ["first", "3"]
new URLSearchParams("?first=1&second=2&first=3").get('first'); // "1"
```

Edit: nevermind, this second line is documented in `.get()` "Returns the first value", I was unsure about the first because I've seen a [different javascript library](https://www.npmjs.com/package/query-string) return a list as the second item in each entry. I still think it would be good to mention this in the examples too.

2) Does iterating over URLSearchParams preserve the order of the params or is it implemented with an unordered JavaScript dictionary?

it's implemented with a list of lists so order is preserved.

3) Are round trip conversions lossless? How does it differentiate between params with and without an `=`?

No it's not lossless because `?param` and `?param=` both parse as having a value of `""` instead of `null` for the former and `""` for the latter, so they are both converted to `?param=`

```js
for (const i of new URLSearchParams("?first=&second")) { console.log(i) } // ["first", ""] ["second", ""]
String(new URLSearchParams("?first=&second")); // "first=&second="
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/urlsearchparams`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/urlsearchparams/index.html
* Last commit: https://github.com/mdn/content/commit/dad0283e67a05c6e904a7cf30f4529257b28fe98
* Document last modified: 2020-12-21T19:02:54.000Z

</details>

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* An example highlighting `get` returns the first value (poosibly added to the get() method page as well)
* Text explaining order is preserved
* A round trip example
