### ISSUE TITLE
Typo issue - Spanish

### ISSUE THREAD

**Issue by wolobi** [mdn/content#2106]
Hi, 

At this link

https://developer.mozilla.org/es/docs/Web/API/Element/attributes#notes

Have to change:
Enumerando atributos de **elemtentos**
for
Enumerando atributos de **elementos**

Thanks

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
