### ISSUE TITLE
[CSS] Named Scroll Progress Timelines

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#21069]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- FF103 adds scroll-linked animations timelines CSS properties behind pref `layout.css.scroll-linked-animations.enabled`
- Spec link should be this: https://drafts.csswg.org/scroll-animations-1/#scroll-timelines-named
- Only CSS/declarative way supported. From user point of view that is  section 2 "Scroll progress Timelines. 
  - CSS properties: 
    - scroll-timeline-name 
    - scroll-timeline-axis 
    - scroll-timeline (shorthand)
- CSS `scroll()` notation is in another bug, [Bug 1737918](https://bugzilla.mozilla.org/show_bug.cgi?id=1737918).

- API/Interface [ScrollTimeline](https://drafts.csswg.org/scroll-animations-1/#scrolltimeline) are not planned yet. 

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1754897

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if [Glossary](https://developer.mozilla.org/en-US/docs/Glossary) updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.

**Comment by hamishwillee** [comment]
@Rumyra Just running some bug reports and ran into this. Did you already know about it?

**Comment by hamishwillee** [comment]
Status

- [ ] BCD
- [ ] Docs - #21277
- [ ] Experimental features
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
As per any left on scroll timelines is now in https://github.com/mdn/content/issues/15467 I'm closing this bug 👍
