### ISSUE TITLE
[WebAPI] Support the CSS Font Loading API in workers

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#21070]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

The font loading API done in FF104 in #18769 was shipped in https://bugzilla.mozilla.org/show_bug.cgi?id=1779009. Though this is not at all obvious from the name. I noted it looking at the source https://hg.mozilla.org/mozilla-central/rev/ca0fc9488e5d where `layout.css.font-loading-api.workers.enabled` is set true.

Should just be a BCD/release note/experimental features update.

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1779009

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if [Glossary](https://developer.mozilla.org/en-US/docs/Glossary) updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/17889
- [ ] Docs - NA - all done in previous case.
- [ ] Experimental features: Remove: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#css_font_loading_api
- [ ] Release notes - add
- [ ] dev-doc-complete - already done - this "went public" in an unrelated shipping issue.

**Comment by bsmth** [comment]
Hi @hamishwillee it looks like this one is done so I'm going to close it 👍🏻

**Comment by hamishwillee** [comment]
@bsmth Yes. I leave all my release project issues open on completion and move them into the "Done" list. In the past the person doing the release would close them as part of the final release checks. It may be that no one cares, but I'll continue with this until I'm told it isn't useful.

**Comment by bsmth** [comment]
>In the past the person doing the release would close them as part of the final release checks.

Oh I see, thanks for the hint. Carry on! 🙌🏻

**Comment by hamishwillee** [comment]
Well I could be wrong about what is done now - it feels like a long time since I've seen new release getting any fanfare :-).
