### ISSUE TITLE
DOMImplementation.createDocumentType() return type section is inaccurate

### ISSUE THREAD

**Issue by hut8** [mdn/content#21086]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createDocumentType

### What specific section or headline is this issue about?

Return type

### What information was incorrect, unhelpful, or incomplete?

https://dom.spec.whatwg.org/#dom-domimplementation-createdocumenttype specifies that the return type is not undefined.

The MDN page says:

> [Return value](https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createDocumentType#return_value)
> None ([undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined)).

Also, MDN says:

[Examples](https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createDocumentType#examples)

```js
const dt = document.implementation.createDocumentType('svg:svg', '-//W3C//DTD SVG 1.1//EN', 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd');
const d = document.implementation.createDocument('http://www.w3.org/2000/svg', 'svg:svg', dt);
alert(d.doctype.publicId); // -//W3C//DTD SVG 1.1//EN
```

If it returned undefined, `dt` and `d` would not be useful.

### What did you expect to see?

Returns a [DocumentType](https://developer.mozilla.org/en-US/docs/Web/API/DocumentType).

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation

Also, the page with the issue itself says:

> The DOMImplementation.createDocumentType() method returns a [DocumentType](https://developer.mozilla.org/en-US/docs/Web/API/DocumentType)

https://dom.spec.whatwg.org/#dom-domimplementation-createdocumenttype

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/domimplementation/createdocumenttype`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createDocumentType
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/domimplementation/createdocumenttype/index.md
* Last commit: https://github.com/mdn/content/commit/4e233c16c6f0d347972c5c762f5b836318a46124
* Document last modified: 2022-09-13T05:27:14.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened #21101 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
