### ISSUE TITLE
[CSS] Language describing width or height of inline elements

### ISSUE THREAD

**Issue by DevNdamase** [mdn/content#21088]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow

### What specific section or headline is this issue about?

Normal Flow(CSS)

### What information was incorrect, unhelpful, or incomplete?

> You can't set width or height on inline elements — they just sit inside the content of block level elements.

![Screenshot from 2022-09-26 22-00-09](https://user-images.githubusercontent.com/102190131/192369842-322f7f80-5bd4-4b74-92f3-03ef1aa754b8.png)

### What did you expect to see?

You can set width or height on some `inline` elements like an `img` tag but it's display property will still remain `inline`.
If you want to control the display property of an `inline` element, you need to set it to behave like a block level element (e.g., with `display: block;` or `display: inline-block;`, which mixes characteristics from both).

### Do you have anything more you want to share?

> You can't set width or height on inline elements — they just sit inside the content of block level elements.

The above explanation, may be misinterpreted as to mean that you can't resize or modify `inline elements` at all.
These choice of words in the explanation for us  **_non-Engish speakers_**  and  **_beginner  programmers_**  may be confusing.

![Screenshot from 2022-09-26 23-12-21](https://user-images.githubusercontent.com/102190131/192381405-08b786aa-7233-4b6f-9254-f255b36c0dc1.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/css_layout/normal_flow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/normal_flow/index.md
* Last commit: https://github.com/mdn/content/commit/05d8b0eb3591009b6b7fee274bb7ed1bc5638f18
* Document last modified: 2022-09-14T12:03:40.000Z

</details>

**Comment by halcance** [comment]
Hi! The explanation could be changed and I liked your version but I doesn't think it is wrong, yes, you can set width on your code but it will not work so you will lose your time.

If you try to do it in your Firefox this happens:

<img width="299" alt="Captura de tela 2022-10-05 002309" src="https://user-images.githubusercontent.com/17792084/193975312-8012b356-21d5-45ef-8ecc-20af1620ed24.png">

As you said, beginners could misunderstand so we need to review the language structure of the page. If it should be technical or narrative.

**Comment by DevNdamase** [comment]
Yes, a less technical language structure, while still being concise,  could be helpful.
I am a beginner  myself, and I was very confused by the wording.
Thank you for the feedback!

**Comment by halcance** [comment]
It could be done, it depends on the team.

Thanks for your idea!

**Comment by bsmth** [comment]
Hi @DevNdamase, thanks for raising the issue. Would you like to have a go at fixing it? There are some hints for contributing if you want to have a look here: https://github.com/mdn/content/blob/main/CONTRIBUTING.md

**Comment by estelle** [comment]
The screen shot from W3Schools is showing HTML, not CSS. We don't want to confuse the HTML `width` attribute and the CSS `width` property. The `width` attribute can be set on I[MG](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img), [`<canvas>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas), [`<embed>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/embed), [`<iframe>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe), [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), [`<object>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object), [`<video>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video), SVG, all the elements listed on https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width. 

Some of these elements are by default `display: inline`. Others, (`input`) are by UA styled as `inline-block`. 

There are other UA inline-block elements that don't accept HTML width and height attributes but do, by their nature as `inline-block`, get resized with CSS, like  [`<textarea>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea)
