### ISSUE TITLE
Issue with "Object.defineProperty()": Link leads to Page Not Found

### ISSUE THREAD

**Issue by TerryMooreII** [mdn/content#2110]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

#### What information was incorrect, unhelpful, or incomplete?
There is a link to this page that navigates to `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty/Additional_examples` but this results in a Page Not Found

#### Specific section or headline?
This is the text on the page:
If you want to see how to use the Object.defineProperty method with a binary-flags-like syntax, see additional examples.

The text "additional examples" above is a link that results in a 404

#### What did you expect to see?
The page that it was linked to

#### Did you test this? If so, how?
By clicking on the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/defineproperty`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/object/defineproperty/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by avivmu** [comment]
Looks like link was never part of the repository.
I used `git whatchanged | grep -i additional` and it's not listed there
Maybe it was lost in a migration. @chrisdavidmills did you exprience similar issues like this?

**Comment by AnandBIT** [comment]
The text "additional examples" above is a link that results in a 404
Looks like there is not any such text on the webpage https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty
@TerryMooreII could you please provide a screenshot here, with which link you found the issue

**Comment by TerryMooreII** [comment]
It looks like it was removed 9 days ago.  
https://github.com/mdn/content/commit/c34105059b008d9911807e52775cca4772220190#diff-521799e17d123028832347975ea3bd2792338a741bd5b2bed7d3589dd0d43207

**Comment by chrisdavidmills** [comment]
Ah yes, I removed this, so this can be closed.
