### ISSUE TITLE
Link to definitions of "fresh" and "stale" is out of date

### ISSUE THREAD

**Issue by supersime** [mdn/content#21133]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

### What specific section or headline is this issue about?

Vocabulary

### What information was incorrect, unhelpful, or incomplete?

There are a few links in this section that point to the page: <https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#freshness>.

In fact, this same URL is referenced in multiple sections on this page.

However the hash `#freshness` no longer exists on the target page.

I was specifically looking for the definition of "fresh" and "stale" and the target page no longer appears to have it.

### What did you expect to see?

A link that would take me to the definition of "fresh" and "stale".

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/cache-control`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/cache-control/index.md
* Last commit: https://github.com/mdn/content/commit/8e1f45b8c0a3671f6e3de43c0764ad610aa345dd
* Document last modified: 2022-09-14T09:06:12.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened #21148 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
