### ISSUE TITLE
Issue with "WebGL best practices": (short summary here please)

### ISSUE THREAD

**Issue by chylu** [mdn/content#2113]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices

#### What information was incorrect, unhelpful, or incomplete?
This page advises you to call WEBGL_lose_context.loseContext() to free up memory. However, that API is for SIMULATING loss of context. As far as I can tell from hours of research on the internet, there is currently NO way for a JavaScript developer to release a context; additionally, garbage collection for leftover contexts is questionable on every major browser.

#### Specific section or headline?
Delete objects eagerly

#### What did you expect to see?
Information that isn't misleading.

#### Did you test this? If so, how?
No, but among other things it's immediately contradicted by the page on WEBL_lose_context: 
https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_lose_context

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl_api/webgl_best_practices`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/webgl_api/webgl_best_practices/index.html
* Last commit: https://github.com/mdn/content/commit/3c8dd140b3925bf8f7b00d0972f27c5760f5c6a3
* Document last modified: 2021-01-15T13:22:56.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update it. Does it mean to remove the whole part about WEBGL_lose_context.loseContext() to free up memory?

**Comment by chylu** [comment]
I think that would be an acceptable minimal solution.
