### ISSUE TITLE
described behaviour of an unspecified pattern is misleading/incorrect

### ISSUE THREAD

**Issue by blindfish3** [mdn/content#21146]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern

### What specific section or headline is this issue about?

intro section

### What information was incorrect, unhelpful, or incomplete?

> If the specified pattern is not specified or is invalid, no regular expression is applied and this attribute is ignored.

I interpret this to mean that if a pattern attribute is added with an undefined value it will be ignored; but in practice this doesn't appear to be the case.  With the following simple form when I try to submit with *any* content in the field an error is displayed, prompting me to match the requested format (tested in Chrome/Firefox):

```
        <form>
            <input type="text" pattern />
            <button type="submit">submit</button>
        </form>
```

### What did you expect to see?

Some kind of warning that an undefined pattern _will result in validation failure_.

For context I'm using a front-end framework where `pattern` is an input property of a component.  When a pattern isn't specified on the component an empty `pattern` attribute is included in the HTML output; and this causes form validation to fail.

### Do you have any supporting links, references, or citations?

The spec on pattern attribute also appears a little ambiguous on the topic of empty pattern attributes:

https://dev.w3.org/html5/spec-LC/common-input-element-attributes.html#the-pattern-attribute

### Do you have anything more you want to share?

In my case the simplest workaround appears to be to specify a pattern that will match all characters: `pattern=".*"`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/pattern`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/pattern/index.md
* Last commit: https://github.com/mdn/content/commit/bb7e3c7303746408072ddf4cc646e28d7e14214a
* Document last modified: 2022-09-14T06:47:31.000Z

</details>

**Comment by bsmth** [comment]
Thanks @blindfish3 for raising this issue. Would you like to have a go at fixing the section with a pull request? Maybe you could put something under constraint violation?

https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/pattern/index.md?plain=1#L31
