### ISSUE TITLE
[Web API] Missing interfaces in structured clone

### ISSUE THREAD

**Issue by zcorpan** [mdn/content#21178]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

### What specific section or headline is this issue about?

Supported types

### What information was incorrect, unhelpful, or incomplete?

I added a few interfaces in https://github.com/mdn/content/pull/21152 but:

Possibly further interfaces are still missing. Check for [[Serializable] extended attribute](https://html.spec.whatwg.org/multipage/structured-data.html#serializable) in webidl: https://searchfox.org/mozilla-central/search?q=Serializable&path=.webidl&case=true&regexp=false

### What did you expect to see?

All interfaces with `[Serializable]` listed in the table.

**Comment by wbamberg** [comment]
AFAICT webref lists the following Web APIs as serializable:

```
Blob
File
FileList
CryptoKey
FileSystemHandle
FileSystemHandle
FileSystemFileHandle
FileSystemDirectoryHandle
DOMPointReadOnly
DOMPoint
DOMRectReadOnly
DOMRect
DOMQuad
DOMMatrixReadOnly
DOMMatrix
ImageData
ImageBitmap
CropTarget
AudioData
VideoFrame
GPUCompilationMessage
GPUCompilationInfo
DOMException
RTCCertificate
```

**Comment by zloirock** [comment]
@zcorpan interesting moment - by your link, I found that, for example, [`structuredClone` is serializable in FF](https://searchfox.org/mozilla-central/source/dom/webidl/URLSearchParams.webidl#17):

![image](https://user-images.githubusercontent.com/2213682/193361557-459a37e5-e28d-496d-88ae-9e80a7bf95e1.png)

[but it should not be](https://url.spec.whatwg.org/#interface-urlsearchparams):

![image](https://user-images.githubusercontent.com/2213682/193361639-43790060-6589-42f0-a44c-6760966ba7e1.png)

**Comment by zcorpan** [comment]
@zloirock I found this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1636761
