### ISSUE TITLE
img  wrong, didn't show what happend when it is not supported

### ISSUE THREAD

**Issue by Andr-e-acute** [mdn/content#21182]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Controlling_Ratios_of_Flex_Items_Along_the_Main_Ax

### What specific section or headline is this issue about?

Important concepts when working on the main axis 

### What information was incorrect, unhelpful, or incomplete?

the screenshot under the text is not correct and shows the opposite:

"If your browser does not yet support these keywords both paragraphs will be rendered as normal paragraphs in block flow; the below screenshots show the expected rendering."
![image](https://user-images.githubusercontent.com/98744906/193018762-5ad54d56-60e2-43a2-baa8-fa759c931c47.png)

### What did you expect to see?

![image](https://user-images.githubusercontent.com/98744906/193018138-0b4a263a-18ae-4967-a018-a58b6b459a70.png)

**Comment by wbamberg** [comment]
Yes, I think you are right. Also, `max-content` and `min-content` have been supported in all browsers for years, so it would be better to frame this as "if these properties are not set", maybe with a third box in the live example.

**Comment by sidverma32** [comment]
Can i take this and update the image? @wbamberg

**Comment by bsmth** [comment]
Thanks for raising the issue. It looks like this has been fixed in hhttps://github.com/mdn/content/pull/21467 so I'm going to close as done.

Thank you :)
