### ISSUE TITLE
Date parse example uses unsupported format

### ISSUE THREAD

**Issue by greggman** [mdn/content#21188]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

### What specific section or headline is this issue about?

The example

### What information was incorrect, unhelpful, or incomplete?

The 2nd paragraph on the page says

> Only the [ISO 8601 format](https://tc39.es/ecma262/#sec-date-time-string-format) (YYYY-MM-DDTHH:mm:ss.sssZ)

Then immediately below it this example it shown

> ```
> const unixTimeZero = Date.parse('01 Jan 1970 00:00:00 GMT');
> const javaScriptRelease = Date.parse('04 Dec 1995 00:12:00 GMT');
> 
> console.log(unixTimeZero);
> // expected output: 0
> 
> console.log(javaScriptRelease);
> // expected output: 818035920000
> ```
 
According to the paragraph above there's no guarantee this "expected output" will work. It seems mis-leading to show this example. Should the `javaScriptRelease` string be changed to a n ISO 8601 format?

### What did you expect to see?

an example that complies with the spec

### Do you have any supporting links, references, or citations?

The issue is linked in the document itself

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/parse`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/parse/index.md
* Last commit: https://github.com/mdn/content/commit/d6ce8fcbbc4a71ec9209f379e5ea9774bbf1f5ac
* Document last modified: 2022-09-13T07:06:03.000Z

</details>

**Comment by Josh-Cena** [comment]
I think it's fair to expect RFC 2822 date strings to also work, especially when targeting browsers. We just need to make the note less assertive about the risk of non-support.
