### ISSUE TITLE
forEach wording accuracy

### ISSUE THREAD

**Issue by HelmZalee** [mdn/content#21191]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

### What specific section or headline is this issue about?

The first sentence describing forEach is false.

### What information was incorrect, unhelpful, or incomplete?

The description begins with "...executes a provided function once for each array element."  

That is not simply incomplete or lacking detail.  It is false.  

### What did you expect to see?

"...executes a provided function once for each _defined_ array element." might be more accurate.  

### Do you have any supporting links, references, or citations?

From further in the article: "callbackFn is invoked only for array indexes which have assigned values. ".

Consistency in terminology would be helpful as well.  "provided function" might better be "a callback function", as the phrase "callback" is used later.

### Do you have anything more you want to share?

Precision and accuracy are important and difficult.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/foreach`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/foreach/index.md
* Last commit: https://github.com/mdn/content/commit/3a6cbf0bd59de52f671fd7be990a8c5618237bdd
* Document last modified: 2022-09-23T21:10:37.000Z

</details>

**Comment by Josh-Cena** [comment]
Empty slots are not array elements. They are simply "missing". There's nothing wrong here. It's also not the style of MDN to embed critical information within one word choice—if there's some important caveat, we would always add a separate sentence instead of polishing each individual word. Nevertheless, I'm updating these pages anyway, and I'll change the wording in all callback-accepting methods.

**Comment by bsmth** [comment]
Thanks @Josh-Cena for having a look. 

>I'm updating these pages anyway, and I'll change the wording in all callback-accepting methods.

I'll assign this issue to you so we can see at-a-glance that someone is taking care of this if you don't mind
