### ISSUE TITLE
parseInt(): wrong return value stated in prose

### ISSUE THREAD

**Issue by codeus-ex-machina** [mdn/content#21192]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

"If the number is greater than 1e+21 (including) or less than 1e-7 (including), it will return 1. (when using radix 10). "

Incorrect.

e.g.
parseInt(0.0000000004)

Note: The examples are about passing numbers of number type, not strings.

### What did you expect to see?

Will be the first digit of the scientific notation string that the argument is converted to (when argument is of number type.

Or could it be anything else?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/parseint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/parseint/index.md
* Last commit: https://github.com/mdn/content/commit/ce2909126eb09e44c9f48d9f65d072acae827749
* Document last modified: 2022-09-13T07:09:29.000Z

</details>

**Comment by Josh-Cena** [comment]
Yes, the wording here is really confusing, and you are right, it should be the first digit in scientific notation. In fact you should _never_ pass a number to `parseInt` (many people use it for truncation), and this page should be significantly modified.
