### ISSUE TITLE
Align content in CSS grid examples across similar pages

### ISSUE THREAD

**Issue by zhangenming** [mdn/content#21199]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/21235555/193228615-4e98da8d-25d0-484e-a60e-9f0196b0204c.png)
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column
and https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row

The two sides are a lot different
Should be synchronize?thanks..

### What did you expect to see?

roughly the same

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/grid-row`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/grid-row/index.md
* Last commit: https://github.com/mdn/content/commit/44439c7254c9da1797e4438bade0f8e8984cbc35
* Document last modified: 2022-09-27T22:38:41.000Z

</details>

**Comment by zhangenming** [comment]
same as
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns
and
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows

A lot of the content in it is unique but also universal content for them.

**Comment by wbamberg** [comment]
Yes, it looks like the two pages should be aligned with each other. Did you want to have a go at doing this, @zhangenming ?

**Comment by zhangenming** [comment]
Sure. I'll start now...

But should there be a mechanism for automatic alignment such as using procedural generation
There are a lot of pages like this that seem a bit cumbersome to complete manually

**Comment by zhangenming** [comment]
Or at least give a hint, when someone edit this file, hint There's another file there that might need to be modified as well

**Comment by bsmth** [comment]
There's a fix for this at https://github.com/mdn/content/pull/21386
