### ISSUE TITLE
[meta] Disallow merge commits for this repo?

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/content#212]
I merged PRs #205 and #211 from @hamishwillee but now notice that unfortunately the changes were merged to main as “merge commits” rather than through rebasing. In the case of those two PRs, the GiHub UI seemed only provide me with a green *Merge* button, without any option to choose how the merge got made — but probably it was just pilot error on my part, for not being careful about to actually look for the UI control to change it to a rebase/squash.

Anyway, regardless, I recommend that — to prevent this from happening — the repo settings at https://github.com/mdn/content/settings should be changed to uncheck the **Allow merge commits** option, like this:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/194984/102168096-005c4280-3ed3-11eb-9f11-b47354ee7a6a.png">

**Comment by hamishwillee** [comment]
FYI @sideshowbarker the merge method is selected from next to the merge button:
![image](https://user-images.githubusercontent.com/5368500/102169674-ceed7200-3ee6-11eb-88c5-c38502f730f6.png)

Thanks for getting my changes in.

**Comment by sideshowbarker** [comment]
> FYI @sideshowbarker the merge method is selected from next to the merge button:

Thanks yeah but for the case of these two PRs, it didn’t actually seem to show me that control.

Probably it did and just somehow missed seeing it — but what I recall now is just seeing a green button with only the word **Merge** — no **Merge pull request** — and thinking, _Oh there’s no option to select the merge method, so I guess maybe the repo settings already restrict it to just one option_.

But anyway, for other open PRs here that I have perms here to merge, I do in fact see a **Merge pull request** button, with the control to select the type of merge.

**Comment by chrisdavidmills** [comment]
Thanks for bringing this up @sideshowbarker . Probably best for @peterbe or @escattone to make a decision on this.

**Comment by peterbe** [comment]
<img width="550" alt="Screen Shot 2020-12-15 at 10 53 25 AM" src="https://user-images.githubusercontent.com/26739/102238436-c46db100-3ec3-11eb-8983-330105966c52.png">

Now no longer allowed.
