### ISSUE TITLE
Missing word in Audio and Video delivery\Adaptive Streaming

### ISSUE THREAD

**Issue by BrainCrumbz** [mdn/content#21203]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery

### What specific section or headline is this issue about?

Adaptive Streaming

### What information was incorrect, unhelpful, or incomplete?

It says (ellipsis ours)

```
DASH also provides a number of profiles [...] that no preprocessing and splitting up of media files.
--------------------------------------------------^
```

It looks like there' a word missing between `that` and `no`. 

Source file URL:  
https://github.com/mdn/content/blob/c43e8d42c74232755ad6784eaba0b49607ec70be/files/en-us/web/guide/audio_and_video_delivery/index.md

### What did you expect to see?

It might be something like:

```
DASH also provides a number of profiles [...] that *require* no preprocessing and splitting up of media files.
--------------------------------------------------^
```

### Do you have any supporting links, references, or citations?

Link to page section:  
https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery#adaptive_streaming

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened #21234 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
