### ISSUE TITLE
TextEncoder API: It seems to be lacking information

### ISSUE THREAD

**Issue by santimirandarp** [mdn/content#21238]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder

### What specific section or headline is this issue about?

All page

### What information was incorrect, unhelpful, or incomplete?

It is lacking some explanations as well as part of the table for the properties of a TextEncoder. For example, you can use `encoder.decode(data)`. I don't have enough knowledge to do it I think.

### What did you expect to see?

All the methods and properties added and described.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/textencoder`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/textencoder/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by Josh-Cena** [comment]
I don't think `TextEncoder` has a `decode` method.

<img width="196" alt="image" src="https://user-images.githubusercontent.com/55398995/193469856-d6159733-f2e2-4491-8426-45476fca0fef.png">

**Comment by santimirandarp** [comment]
You are correct. I probably typed Decode. Thank you.
