### ISSUE TITLE
"Django introduction" contains link to expired domain

### ISSUE THREAD

**Issue by misha-grigorov** [mdn/content#2124]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Introduction#how_popular_is_django

#### What information was incorrect, unhelpful, or incomplete?
"Django introduction" contains link to expired domain of Hot Frameworks. This might posses some security risks to readers of this course in case someone with malisious intentions obtains this domain.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Introduction#how_popular_is_django

#### What did you expect to see?
Valid link to trusted site.

#### Did you test this? If so, how?
Manually through web-browser.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Introduction
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/server-side/django/introduction/index.html
* Last commit: https://github.com/mdn/content/commit/edbcbfa37c7807eefc5346c734cfc55d3dcc2c8a
* Document last modified: 2021-01-25T07:12:53.000Z

</details>

**Comment by chrisdavidmills** [comment]
Hrm, I thought we'd gotten rid of this already; @hamishwillee, are you happy to remove this line?

**Comment by sanket2000sonavane** [comment]
can I work work on this issue @chrisdavidmills ? can you tell me which link should I add instead of expired domain of Hot Frameworks.

**Comment by hamishwillee** [comment]
I'll fix this (thanks for the offer @sanket2000sonavane but I just fixed one the same in the Express docs).
