### ISSUE TITLE
Content suggestion: enumerated glossary term

### ISSUE THREAD

**Issue by estelle** [mdn/content#21253]
## What is the new suggestion?

define `enumerated`

## Why is it important or useful?

Enumerated is used over 30 times on MDN, but is never defined. The basic definition is "counted" which is not what it means in programming. Also, unlike boolean values where an invalid value is the same as an omitted value, this isn't necessarily the case. This should all be spelled out. Because while `required="required"` is the same as `required`, `contenteditable=contentedible` is not the same as `contenteditable`. There are a few cases where omitted values are different from invalid values.

Then link every first occurrence of enumerated attribute to the enumerated glossary entry.

**Comment by wbamberg** [comment]
I think that in the case you mentioned of [`contenteditable`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable), "enumerated attribute" is a technical term in HTML which should link to a definition within our HTML docs (as in fact it's defined in the spec: https://html.spec.whatwg.org/#keywords-and-enumerated-attributes ), alongside "boolean attribute", which does have a definition although maybe not in the best place: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#boolean_attributes. I don't think linking to a general glossary definition of "enumerated" would be as useful.

We might also want a general glossary definition of "enumerated type" or something, for the other cases. We already have glossary entries for things like ["Variable"](https://developer.mozilla.org/en-US/docs/Glossary/Variable) so it doesn't seem unreasonable.

There might be some other cases where we could just use a more common synonym for "enumerate", like "list".
