### ISSUE TITLE
Issue with "Object.defineProperty()": (broken link to additional examples)

### ISSUE THREAD

**Issue by DI-john** [mdn/content#2127]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

#### What information was incorrect, unhelpful, or incomplete?

At the beginning of the [examples section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#examples) there is a [broken link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty/Additional_examples) to additional examples for  binary-flags-like syntax.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/defineproperty`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/object/defineproperty/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by chrisdavidmills** [comment]
Hrm, this section is definitely no longer on the page. Is there another example on the page that seems to demostrate what is being described, or an external example we could link to instead?

**Comment by DI-john** [comment]
I'm not sure what it's referring to, to be honest, perhaps using some kind of bitmask configuration approach?  If it were up to me, I'd probably just remove that small paragraph, seems out of place, in my opinion.

**Comment by chrisdavidmills** [comment]
Yeah, I think you're right: see https://github.com/mdn/content/commit/c34105059b008d9911807e52775cca4772220190 for the update.

Thanks for reporting this @DI-john
