### ISSUE TITLE
Issue with "Positioning": (live example is not what it claimed to be)

### ISSUE THREAD

**Issue by Arittra** [mdn/content#2128]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning

#### What information was incorrect, unhelpful, or incomplete?
The live example (https://mdn.github.io/learning-area/css/css-layout/positioning/3_absolute-positioning.html) doesn't contain the resize elements it was supposed to have.

#### Specific section or headline?
Absolute positioning.

#### What did you expect to see?
I expected to see the ```<p>``` element with a class of "positioned" to have the properties of ```top: 0; bottom: 0; left: 0; right: 0; margin: 0;``` as it is supposed to have.

#### Did you test this? If so, how?
I tested this using the element inspector.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/css_layout/positioning`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/css/css_layout/positioning/index.html
* Last commit: https://github.com/mdn/content/commit/ae7855b7d2e257273ab276daa9565de2786947b1
* Document last modified: 2021-01-27T07:44:46.000Z

</details>

**Comment by rachelandrew** [comment]
@Arittra I think this is correct, unless I'm looking at the wrong thing. The instructions say to try adding those values, but also to remove them again. They don't say that is what the example demonstrates.

**Comment by rachelandrew** [comment]
Closing as I don't think there is an issue here and original commenter didn't get back - please reopen if you have some other info for me.
