### ISSUE TITLE
Unknown specification for @font-face/src

### ISSUE THREAD

**Issue by jyasskin** [mdn/content#21291]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src

### What specific section or headline is this issue about?

Specifications

### What information was incorrect, unhelpful, or incomplete?

It says 

[Unknown specification
# src-desc](https://w3c.github.io/csswg-drafts/css-fonts/#src-desc)

### What did you expect to see?

Something about it being the CSS Fonts Module Level 4.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@font-face/src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@font-face/src/index.md
* Last commit: https://github.com/mdn/content/commit/d585bcffcda6ed5a1555c65ab62670567925679f
* Document last modified: 2022-09-26T22:45:30.000Z

</details>

**Comment by hamishwillee** [comment]
There are a whole bunch of these - it is an infrastructure thing related to the linked site itself, not a documentation problem. 

@wbamberg Do you know if there a central tracking bug for the spec linking issue?

**Comment by wbamberg** [comment]
Yes, this will we think be fixed by https://github.com/mdn/yari/pull/7262 , but it is waiting for a review.

Fragments are also broken, that one ought to be fixed by https://github.com/w3c/csswg-drafts/pull/7801.

**Comment by hamishwillee** [comment]
Thanks @wbamberg !
