### ISSUE TITLE
Slider controls example could use value instead of textContent

### ISSUE THREAD

**Issue by Endzelisp** [mdn/content#21318]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types

### What specific section or headline is this issue about?

Slider controls

### What information was incorrect, unhelpful, or incomplete?

The guide Forms > HTML5 Input Types, at the section Slider controls, give an example using the HTML tag <output> which is updated via JavaScript using: 

output.textContent = price.value;

At the end of this section exist a note pointing to a CSS-Tricks article where a similar example is given but using .value property instead of .textContent to update the DOM

Here's the link => https://css-tricks.com/the-output-element/

I'm not completely sure if the use of .textContent instead of .value will not create accessibility issues for the user. 

Quote form the output tag MDN reference:

"Many browsers implement this element as an aria-live region. Assistive technology will thereby announce the results of UI interactions posted inside it without requiring that focus is switched away from the controls that produce those results."

### What did you expect to see?

replace  output.textContent = price.value; in the example for output.value = price.value; In the case this replacement is appropiate.

### Do you have any supporting links, references, or citations?

CSS-Tricks article "The Output Element"

https://css-tricks.com/the-output-element/

MDN > References > HTML > Elements > output

Section: Accessibility Concerns

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output#accessibility_concerns

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/html5_input_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/html5_input_types/index.md
* Last commit: https://github.com/mdn/content/commit/f1f3eaf1b5a73e3d92aef40622434b5110418852
* Document last modified: 2022-09-14T13:25:46.000Z

</details>

**Comment by ya-sh-vardh-an** [comment]
Hello, I am new to the MDN. I would like to take this issue.
