### ISSUE TITLE
[input] undefined

### ISSUE THREAD

**Issue by folza1** [mdn/content#21316]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics

### What information was incorrect, unhelpful, or incomplete?

const person = {
  name: ['Bob', 'Smith'],
  age: 32
}
const input = prompt('Get name or age?')
console.log(person[input])

### What did you expect to see?

What I write in the prompt window.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/basics/index.md
* Last commit: https://github.com/mdn/content/commit/904cdf09c7e328b7a15a6a4db6bc6bd31f969cce
* Document last modified: 2022-09-09T05:00:53.000Z

</details>

**Comment by sideshowbarker** [comment]
This question is unclear as currently written.

Can you please elaborate on what the exact problem is? Is there some behavior that you’re expecting to see? If so, exactly what? And is there some actual behavior that’s different from what you expect to see? If so, exactly what?

**Comment by wbamberg** [comment]
If I may, it looks like the reporter is expecting this code to log whatever is entered at the prompt. But the prompt is expecting you to enter either "name" or "age": if you enter anything else you get `undefined` because there aren't any other keys defined for the `person`.

I agree actually that it isn't very clear. Maybe it would help to add some error handling?

```js
const person = {
  name: ['Bob', 'Smith'],
  age: 32
  };

const input = prompt('Get name or age?')

if (person[input] !== undefined) {
  console.log(person[input]);
} else {
  console.log(`Please enter one of the following: ${Object.keys(person).map(k => `"${k}"`).join(", ")}`);
}
```
