### ISSUE TITLE
[web-extension] Incompatible parameter in browser.tab.onUpdated.addListener

### ISSUE THREAD

**Issue by JafarAkhondali** [mdn/content#2131]
In chrome, the [onUpdated](https://developer.chrome.com/docs/extensions/reference/tabs/#event-onUpdated) method only accepts the event function. However Firefox [accepts an optional parameter](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated) called `extraParameters` which can be used for filtering. There is no mention of about this incompatibility in Firefox  documentation with Chrome, thus this should be addressed precisely.  

Also the sort list of `properties` key in `extraParameters` doesn't match with [mentioned](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab) document ( e.g. check `url` key ) .
https://github.com/mdn/content/blob/196093bb4fcf0cba4039dc62652205c11f33cd98/files/en-us/mozilla/add-ons/webextensions/api/tabs/onupdated/index.html#L25

MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab

**Comment by himanshugarg** [comment]
There are two issues reported here:-

> Firefox accepts an optional parameter called extraParameters which can be used for filtering. There is no mention of about this incompatibility in Firefox documentation with Chrome, thus this should be addressed precisely.

There is some mention. **Is that inadequate?**
![image](https://user-images.githubusercontent.com/2392803/145662759-90683d21-7177-4702-95d5-53420ebbc052.png)

>  list of properties key in extraParameters doesn't match with [mentioned](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab) document ( e.g. check url key ) .

While the `url` key appears in both, there are over a dozen other properties now in the [mentioned](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab) document. **How do we figure which of those should appear here?**
