### ISSUE TITLE
Issue with "<input type="checkbox">": (short summary here please)

### ISSUE THREAD

**Issue by danielskg** [mdn/content#2132]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

#### What information was incorrect, unhelpful, or incomplete?
"checked" note: a checkboxes value -> a checkbox's value
"indeterminate": "...meaning that it's state" -> "...meaning that its state"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/checkbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/html/element/input/checkbox/index.html
* Last commit: https://github.com/mdn/content/commit/6ea40ef768005776b5e95c8c29d092133b0af692
* Document last modified: 2020-12-29T13:09:26.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Thanks for flagging it!

The changes would happen in

https://github.com/mdn/content/blob/8cf25f9ab473748bf7d130d14c75b6daa67d6f37/files/en-us/web/html/element/input/checkbox/index.html#L107

and

https://github.com/mdn/content/blob/8cf25f9ab473748bf7d130d14c75b6daa67d6f37/files/en-us/web/html/element/input/checkbox/index.html#L114

You can edit them directly via GitHub's web UI.

**Comment by CreaTorAlexander** [comment]
I can update it.
