### ISSUE TITLE
Broken link - 'DOM XSS injection sinks covered by Trusted Types'

### ISSUE THREAD

**Issue by EricRohlfs** [mdn/content#21337]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for

### What specific section or headline is this issue about?

Broken link

### What information was incorrect, unhelpful, or incomplete?

Expected the link to work, or not to be there.
'DOM XSS injection sinks covered by Trusted Types' near the bottom of the page.

### What did you expect to see?

an article

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/require-trusted-types-for`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/require-trusted-types-for/index.md
* Last commit: https://github.com/mdn/content/commit/36001a269f4d7b2b3ac6de79e942a5f849bb87d8
* Document last modified: 2022-09-09T05:53:39.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing!

It probably wants to be this: https://w3c.github.io/trusted-types/dist/spec/#injection-sinks but we could also remove this link IMO since we link to the spec already at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for#specifications .

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened #21347 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
