### ISSUE TITLE
Confusing example demonstrating control flow in JavaScript guide

### ISSUE THREAD

**Issue by cesarzb** [mdn/content#21339]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling

### What specific section or headline is this issue about?

Try..catch statement section, example code

### What information was incorrect, unhelpful, or incomplete?

mo--; // Adjust month number for array index (1 = Jan, 12 = Dec)

### What did you expect to see?

mo--; // Adjust month number for array index (0 = Jan, 11 = Dec)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/control_flow_and_error_handling`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/control_flow_and_error_handling/index.md
* Last commit: https://github.com/mdn/content/commit/eada29e0774d505becb3a725001d372f0dbdc73d
* Document last modified: 2022-09-13T08:52:08.000Z

</details>

**Comment by bsmth** [comment]
I've closed https://github.com/mdn/content/pull/21344 which was a proposed fix for this issue because the code is working as expected. There is room for the example to be improved, however, as it's currently leading to confusion. I'll leave this issue open to reflect that.
