### ISSUE TITLE
Poor definition for understanding what a property is.

### ISSUE THREAD

**Issue by WilliamEJBaldwin** [mdn/content#21340]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/property/JavaScript

### What specific section or headline is this issue about?

definition

### What information was incorrect, unhelpful, or incomplete?

> A JavaScript property is a characteristic of an object, often describing attributes associated with a data structure.

This tells me that properties are associated with objects. However, the definition of a characteristic is not very exact. From Oxford:

a feature or quality belonging typically to a person, place, or thing and serving to identify it.

A feature? This still doesn't tell me what a property _**IS**_. The definition says that it often (note: not always) describes attributes associated with a data structure. Which data structure? Specifically objects? Since properties are associated with objects? If just objects, why not say so?

All this ambiguity is well and good if it were just general terms that have no meaning, but there are actual code methods like hasOwnProperty() which refers me back to the entry for property. I have to understand hasOwnProperty() so I have to understand property which I can't because the definition given is too vague to make any sense.

### What did you expect to see?

A firm definition of the word property as used in JavaScript so that a beginner can understand the term. Knowing what a property EXACTLY is is important to the knowledge of programmers.

### Do you have any supporting links, references, or citations?

No, just the actual MDN page.

### Do you have anything more you want to share?

I count on MDN as my source for JavaScript knowledge and I think they do a better job than ANY with JavaScript. I value the free resource and it has furthered my learning so much. I wish they did every language. I want to improve the site giving them a new programmer's viewpoint.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/property/javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/property/JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/property/javascript/index.md
* Last commit: https://github.com/mdn/content/commit/ed947b2c608428b62a60f07d09dc543f732dc09b
* Document last modified: 2022-09-21T02:09:26.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
### What information was incorrect, unhelpful, or incomplete?

The stated distinction between _instance properties_ and _static properties_ appears to confuse object properties with [public class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields) (which are implemented using object properties, but are conceptually different).

> There are two kinds of properties:
> - _Instance properties_ hold data that are specific to a given object instance.
> - _Static properties_ hold data that are shared among all object instances.
>
> A property has a name (a [string](https://developer.mozilla.org/en-US/docs/Glossary/String), or [symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)) and a value ([primitive](https://developer.mozilla.org/en-US/docs/Glossary/Primitive), [method](https://developer.mozilla.org/en-US/docs/Glossary/Method), or [object reference](https://developer.mozilla.org/en-US/docs/Glossary/Object_reference)).

### What did you expect to see?

I think it would be more useful for the [Property (JavaScript)](https://developer.mozilla.org/en-US/docs/Glossary/property/JavaScript) article to instead focus on the distinction between data properties and accessor properties.

> There are two kinds of properties:
> - _Data properties_ associate a key (a [string](https://developer.mozilla.org/en-US/docs/Glossary/String), or [symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)) with a value ([primitive](https://developer.mozilla.org/en-US/docs/Glossary/Primitive), [method](https://developer.mozilla.org/en-US/docs/Glossary/Method), or [object reference](https://developer.mozilla.org/en-US/docs/Glossary/Object_reference)).
> - _Accessor property_ associate a key (a [string](https://developer.mozilla.org/en-US/docs/Glossary/String), or [symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)) with a [getter function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) and/or a [setter function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set).
>
> Both static and instance [public class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields) are implemented using properties.

### Do you have any supporting links, references, or citations?
https://262.ecma-international.org/13.0/#sec-object-type

**Comment by Andrew-Cottrell** [comment]
The article might also explain the writable, enumerable, and configurable attributes.

> Each property has three control flags that may limit what can be done with the property:
> - The _writable_ flag controls attempts to change the value of data properties.
> - The _enumerable_ flag controls whether the property will be [enumerated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) by a for-in enumeration.
> - The _configurable_ flag controls attempts to delete the property, change it from a data property to an accessor property or from an accessor property to a data property, to raise the writable flag (set it to `true`), or to change the enumerable or configurable flags.

I expect that my tentative suggestion above can be improved. I could return to it if there is interest in adding such content to the article. Suggestions welcome; e.g. is _control flag_ suitable terminology for MDN?

**Comment by Josh-Cena** [comment]
We already have this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#properties so we just need to link to it. However, it would be useful to differentiate between:

- Properties
- Methods (which are always function properties defined on the prototype)
- Fields (a.k.a. class fields)
- Attributes (configurable, enumerable, writable)

**Comment by WilliamEJBaldwin** [comment]
It seems like properties of objects are really close to but not really the same as a key... or sometimes the same as the object itself... but I can't differentiate it, personally, in my stage of development from the resources I have. If they are the same, why 2 different words? If they aren't, I would appreciate the explanation somewhere on the site. 

Again, thanks to all who make MDN the best source for JS knowledge.

**Comment by Josh-Cena** [comment]
"Properties" are key + value; that's it. You can say "the property's value is `1`" or "the property is keyed by `"foo"`".

**Comment by WilliamEJBaldwin** [comment]
Thanks! How is that different from object? Because that are what objects are, no?

**Comment by Josh-Cena** [comment]
Objects are a _collection_ of key-value pairs, hence a _collection_ of properties. Properties are like elements of the object.

**Comment by WilliamEJBaldwin** [comment]
So, would a single key-value pair be both a property and an object? Again, thanks!

**Comment by Josh-Cena** [comment]
No—just like a single-element set is not the same as the element itself. You can claim $\mathbb{Z}_0 = \{0\}$ but you can't claim $\mathbb{Z}_0 = 0$.

**Comment by Josh-Cena** [comment]
Note that "property" is an abstract term. You can't have "a variable that holds a property" in JavaScript—it's only a concept.

**Comment by WilliamEJBaldwin** [comment]
So, I guess you are saying that their values can be the same (a single key-value pair) but they themselves would not be equal in any programming sense.

Since property is an abstract thing and definitely cannot be assigned to a variable or anything like that, I am struggling to understand parts of hasOwnProperty().

Under hasOwnProperty(), the list the "prop" field as this:

prop
The String name or Symbol of the property to test

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty](url)

If the prop is merely the key and has a name (in the example), what's the difference? They use the key name for what is the prop... so why call it a prop? Or not mention that the prop CAN BE the key? This confuses me a bit seeing as a prop (property) is supposed to be a key: value pair, not just a key.

To me, it should be named hasOwnKey() if that's what they are really just checking, Or do we, just like with objects, use the key to check the values held by the key?

Again, thanks!

**Comment by Josh-Cena** [comment]
`hasOwnKey` definitely makes sense; however, if an object has a _key_, it must also have the _property_, so they are synonymous in this context. `ownKey` is definitely a thing—for example, [`handler.ownKeys`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/ownKeys). Just don't worry about it too much—"property" and "key" are often synonymous (or at least, _isomorphic_), so there's really no point in trying to rigorously differentiating them.
