### ISSUE TITLE
Minor Modification

### ISSUE THREAD

**Issue by harshVar007** [mdn/content#21356]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

### What specific section or headline is this issue about?

Storing complex data — IndexedDB > Database Initial Setup > 2. Next, add the following

### What information was incorrect, unhelpful, or incomplete?

// Open our database; it is created if it doesn't already exist
// (see the upgradeneeded handler below)
const openRequest = window.indexedDB.open('notes_db', 1);

### What did you expect to see?

// Open our database; it is created if it doesn't already exist
// (see the upgradeneeded handler below)
const openRequest = window.indexedDB.open('notes_os', 1);

### Do you have any supporting links, references, or citations?

In later parts you are doing a transaction/opening database  with name of "**notes_os**" not "**notes_db**";

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/client-side_storage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/client-side_web_apis/client-side_storage/index.md
* Last commit: https://github.com/mdn/content/commit/e1f571eced916f60ca387ecb562271f6235beb5c
* Document last modified: 2022-09-19T04:57:04.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing!

"notes_os" is the name of the object store, not the database. So "notes_db" is correct in the `indexedDB.open` call.
