### ISSUE TITLE
Unclear.  Context is not described.

### ISSUE THREAD

**Issue by DerekWSmith** [mdn/content#21383]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

### What specific section or headline is this issue about?

High-level view

### What information was incorrect, unhelpful, or incomplete?

customElements.define("word-count", WordCount, { extends: "p" });

class WordCount extends HTMLParagraphElement {
  constructor() {
    // Always call super first in constructor
    super();

    // Element functionality written in here
  }
}

### What did you expect to see?

Which files these statements are typically written in.
Some explanation as to why they seem to carry the same information:
Are both necessary?
Are they each required, but in a different location?
If one is included/defined in a HTML file, does the other not need to be written in a JS file?
Is one a defintion, the other the instantiation?

Coming to a beginners tutorial, and seeing this kind of ambiguity, raised so many questions - difficult to continue.

### Do you have any supporting links, references, or citations?

I have completed fields marked with an asterisk, and yet cannot press the "submit new issue" button

The title is also required, but not marked with an asterisk

### Do you have anything more you want to share?

I have completed fields marked with an asterisk, and yet cannot press the "submit new issue" button

The title is also required, but not marked with an asterisk

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/web_components/using_custom_elements/index.md
* Last commit: https://github.com/mdn/content/commit/f7a5accb5daac36bf909f45ad79642a454e64646
* Document last modified: 2022-10-01T17:24:44.000Z

</details>

**Comment by bsmth** [comment]
Hi @DerekWSmith thanks a lot for raising the issue. 

There's an example project linked in that page that should answer the questions you have. You can take a look here: https://github.com/mdn/web-components-examples/tree/main/popup-info-box-web-component

Please check through and let me know if you have any other questions.

Thank you! :)

**Comment by bsmth** [comment]
I think my comment above addresses the issue, so I'm going to close this one for now. If you think this is a mistake or it's still unclear, please feel free to comment again. Thanks a lot :)
