### ISSUE TITLE
await return value

### ISSUE THREAD

**Issue by lsc9** [mdn/content#21403]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

### What specific section or headline is this issue about?

Return value

### What information was incorrect, unhelpful, or incomplete?

`The fulfillment value of the promise, or the expression itself's value itself if it's not a Promise.`

### What did you expect to see?

The expression result will be parsed by `Promise.resolve()`. so if this result is a `thenable` object, it will be resolved to a promise.

### Do you have anything more you want to share?
```
const thenable = {
    then: function (resolve) {
        resolve('thenable');
    }
};
async function test() {
    const a = await thenable;
    console.log(a); // 'thenable', instead of `thenable` variables
}
test();
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/await`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/await/index.md
* Last commit: https://github.com/mdn/content/commit/1533276490d15cff6ddcd201fc05562180058a99
* Document last modified: 2022-09-13T07:11:16.000Z

</details>

**Comment by Josh-Cena** [comment]
I forgot to amend the return value section, because it's in fact explained below in the description section:

> The expression is resolved in the same way as [`Promise.resolve()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve), which means [thenable objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables) are supported

Accepting a PR to mention `Promise.resolve()`-like resolution to the return value description, and possibly the description of `expression` itself as well.

**Comment by Josh-Cena** [comment]
Actually I'm going to do it myself, along with https://github.com/mdn/content/issues/20942

**Comment by promet99** [comment]
@Josh-Cena 
Hi, this is my second time contributing to mdn-docs. Do I need a confirmation from maintainers to open a PR?
I was waiting for it before opening a PR for #20942

**Comment by promet99** [comment]
Meh, I guess my explanation is correct. Opened a PR for #20942

**Comment by lsc9** [comment]
In summary, it is
1. Async functions always return a new promise after being called.
2. await expects promise, if not, it will call Promise.resolve() to convert the following value into promise before further processing.
