### ISSUE TITLE
 The page /en-US/docs/Mozilla/Firefox/Multiprocess_Firefox could not be found

### ISSUE THREAD

**Issue by theranjitraut** [mdn/content#21401]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Tutorials

### What specific section or headline is this issue about?

Multiprocess Firefox

### What information was incorrect, unhelpful, or incomplete?

The attached URL is not found.  The page /en-US/docs/Mozilla/Firefox/Multiprocess_Firefox could not be found.

![image](https://user-images.githubusercontent.com/67329253/194732377-9f45ff18-b47e-49bd-983c-0539f7032d7e.png)

### What did you expect to see?

There should be a correct URL instead of the wrong URL.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/Tutorials

### Do you have anything more you want to share?

Go to https://developer.mozilla.org/en-US/docs/Web/Tutorials
In the last sentence of the article, you can find the wrong URL.

![image](https://user-images.githubusercontent.com/67329253/194732451-8c9b4f8b-dd55-430a-a95a-cf9d27eca7cb.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/tutorials`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Tutorials
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/tutorials/index.md
* Last commit: https://github.com/mdn/content/commit/f4f8e2f18ccf19a0bee59e1fe78753e276b98232
* Document last modified: 2022-09-09T07:06:10.000Z

</details>

**Comment by sideshowbarker** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Multiprocess_Firefox is linked to at some external sites such at https://www.ghacks.net/2016/07/22/multi-process-firefox/ and also from the Mozilla wiki https://wiki.mozilla.org/Firefox/multiprocess. So it seems like we should be redirecting https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Multiprocess_Firefox to… somewhere
