### ISSUE TITLE
Issue with "Matrix math for the web": Rotation matrices do not follow the matrix-vector product convention

### ISSUE THREAD

**Issue by riccardoscalco** [mdn/content#2141]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Matrix_math_for_the_web

#### What information was incorrect, unhelpful, or incomplete?

Rotation matrices do not follow the matrix-vector product convention defined section **Multiplying a matrix and a point**.

#### Specific section or headline?

Section "Rotation Matrix". In particular the definition of `rotateAroundXAxis`, `rotateAroundYAxis` and `rotateAroundZAxis`.

#### What did you expect to see?

In section **Multiplying a matrix and a point** the matric-vector product is defined as **vM** (instead of the usual product **Mv**), where **v** is a *row* vector at the left of the matrix. This definition is consistent with the translation matrix defined in the following section, but it is not consistent with the rotation matrices.

With the assumption that positive angles generate a counterclockwise rotation around the axis, which seems in agreement with the image in section **Rotation matrix**, then the correct rotation matrices would be the transpose of the matrices indicated in the text.

#### Did you test this? If so, how?

Please refer to:

* https://en.wikipedia.org/wiki/Translation_(geometry)
* https://en.wikipedia.org/wiki/Rotation_matrix

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl_api/matrix_math_for_the_web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Matrix_math_for_the_web
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/webgl_api/matrix_math_for_the_web/index.html
* Last commit: https://github.com/mdn/content/commit/4fd22eedbc663692eeaf4068f4ff0b016c03a62e
* Document last modified: 2021-01-11T10:55:17.000Z

</details>

**Comment by avivmu** [comment]
Good catch. Wikipedia lists the [basic rotation matrix](https://en.wikipedia.org/wiki/Rotation_matrix#Basic_rotations) and they are in accordance with how the current article is. The problem stems from the fact that the CSS specs define [matrix3d to be specified in **column-major order**](https://drafts.csswg.org/css-transforms-2/#three-d-transform-functions):

> matrix3d() = matrix3d( <number>#{16} )
specifies a 3D transformation as a 4x4 homogeneous matrix of 16 values in column-major order.

**Comment by riccardoscalco** [comment]
Summing up:

In the [jsfiddle](https://jsfiddle.net/tatumcreative/9vr2dorz/) we are passing to **matrix3d** a matrix stored in array `rotateZMatrix` in column-major order 

```
var rotateZMatrix = [cos(a), -sin(a),  ...]
```  

The same matrix stored in a row-major order array would be

```
var rotateZMatrixRmo = [cos(a), sin(a),  ...]
```

The current article specifies matrices in row-major order arrays and defines `rotateZMatrix = [cos(a), -sin(a),  ...]`, in contrast with `rotateZMatrixRmo`, which is the expected definition.

Variable `rotateZMatrix`, in current article, should be equal to `rotateZMatrixRmo` also because `multiplyMatrixAndPoint` defines the vector-matrix product using a row vector on the left, therefore if positive angles generate counterclockwise rotations then `rotateZMatrix = [cos(a), sin(a),  ...]`.

I suggest to add the following changes:
* add a comment in the jsfiddles saying that matrices are stored in coumn-major order, differently from the article.
* in the current PR https://github.com/mdn/content/pull/2142, add a comment in the article saying that matrices are stored in row-major order and the vector-matrix multiplication is defined as **vM**.

@avivmu Please let me know what you think, thanks.

**Comment by avivmu** [comment]
Since the matrices are represented by a one dimensional array, listing the values using `array.join(',')` will output them in row major order:
```
let illustration = [
    'a',  'b',
    'c',  'd'
];
illustration.join(','); // prints a,b,c,d (equivalent to row major order)
```
while when calling [matrix3d](https://drafts.csswg.org/css-transforms-2/#three-d-transform-functions) you should really pass `a,c,b,d` as the input, if you want to use `illustration`.
Why not make the same changes in the fiddles? 
And  update the resulting picture in the article:
![image](https://user-images.githubusercontent.com/19804341/107636708-afb85a00-6c75-11eb-8af7-45a6ef4fd5d6.png)

**Comment by riccardoscalco** [comment]
I agree that we should pass `[a, c, b, d]` to matrix3D in order to pass matrix `illustration`, because matrix3D expect array in column-major order.

I try to explain why I am suggesting to not make the same changes (i.e. the changes introduced in the PR) in the fiddles.

In the current article we define the array `rotateZMatrix = [cos(a), -sin(a), ...]`, that array is in row-major order therefore it describes the matrix
```
  cos(a), -sin(a),    0,    0,
  sin(a),  cos(a),    0,    0,
       0,       0,    1,    0,
       0,       0,    0,    1
``` 

In the jsfiddle we define the array `rotateZMatrix = [cos(a), -sin(a), ...]`, that array is in column-major order therefore it describes the matrix
```
   cos(a), sin(a),    0,    0,
  -sin(a), cos(a),    0,    0,
        0,      0,    1,    0,
        0,      0,    0,    1
``` 

The two matrices are different, so we need to change only one of them. I suggest to change the one in the current article because that change is also in agreement with how the vector-matrix product is defined (**vM**).

For example, say `a = PI/2`, the matrix (after the change) becomes

```
   0,     1,    0,    0,
  -1,     0,    0,    0,
   0,     0,    1,    0,
   0,     0,    0,    1
``` 
Let the row vector `v = [1, 0, 0, 0]`, we have `v' = vM = [0, 1, 0, 0]`, which is a counterclockwise rotation of `v` of `PI/2` radians, consistently with how matrix3D rotate the div in the image.

It may really be something wrong in my reasoning, if you spot the error please let me know, thank you!

**Comment by avivmu** [comment]
> In the current article ... that array is in row-major

> In the jsfiddle ... that array is in column-major order
Both arrays are the same - one dimension - there is no row-major\column-major ordering whatsoever. When we use `rotateZMatrix.join(',')` the output is specified in row-major order - which is incorrect both for the article and for fiddle.

**Comment by riccardoscalco** [comment]
> When we use rotateZMatrix.join(',') the output is specified in row-major order - which is incorrect both for the article and for fiddle.

Are you suggesting to change, in the jsfiddle, both function `matrixArrayToCssMatrix`(so to output in column-major order) and array `rotateZMatrix`?

**Comment by avivmu** [comment]
Since the article snippets are an **exact copy** of fiddle they should be in sync, which means whatever changes happen to one should also be in the other (and vice versa).
Now regarding _what_ should be changed, the specs make it clear what it expects as input to `matrix3d()` and what is the positive rotation direction. I'm okay with your [current PR](https://github.com/riccardoscalco/content/commit/1ecba3bff62ab892a360f9b59a99d488641343b4) changes (which only change the `rotateZMatrix` so that `matrixArrayToCssMatrix()` `array.join(',)` outputs the matrix as col-major-order , just apply those to the fiddle as well. Maybe @gregtatum could add his comments since he wrote those fiddles, or @chrisdavidmills as he's a Member of this repo.

**Comment by gregtatum** [comment]
I feel like some of this representation is somewhat arbitrary, although it's good to be consistent. I haven't reviewed what I did in the article exactly, but I would say make sure the data structure, and rotation direction match the CSS conventions, rather than other conventions. The purpose of the article was to demonstrate matrix math in a web-first context.

**Comment by riccardoscalco** [comment]
> I feel like some of this representation is somewhat arbitrary

The article does not explicitly say if the coordinate system is right or left-handed.  The image in section **Rotation Matrix** shows a counterclockwise rotation, this fact caused me to _assume_ a right-handed system. Therefore my reasoning is under the assumption of a right-handed system. Anyway, this assumption is arbitrary.

The article defines the vector-matrix product as **vM** (function `multiplyMatrixAndPoint`). The `translationMatrix` defined in section **Translation Matrix** is consistent with the product **vM** and it generates the translation of **vM = v + [x,y,z,1]**.

Matrix represented by variable `rotateZMatrix` generates, with product **vM** and positive angles, clockwise rotations of vector **v** in a right-handed system and counterclockwise rotations in a left-handed system. We can verify that by setting **a = pi/2** and **v = [1,0,0]**, then we have **vM = [0,-1,0]**.

_Under the assumption of a right-handed system_, I [proposed](https://github.com/riccardoscalco/content/commit/1ecba3bff62ab892a360f9b59a99d488641343b4) to change variable `rotateZMatrix` in order to represent the transpose of the original matrix. This change leads to a counterclockwise rotation, as showed in the figure.

In the proposed change, I did not take into account any CSS conventions. As far as I understand, CSS transformations [assume](https://drafts.csswg.org/css-transforms-2/#transform-rendering) a left-handed system. If we want to adhere to CSS conventions, then I suggest to leave `rotateZMatrix` as it is and add a sentence that clarify the system handedness.

**Comment by gregtatum** [comment]
> If we want to adhere to CSS conventions, then I suggest to leave rotateZMatrix as it is and add a sentence that clarify the system handedness

Clarifying the system would be great. When I originally wrote this I wasn't thinking about it explicitly, I was only focusing on getting working code. I've found matrix documentation online to be very hand-wavy, and it sounds like you have some expertise here that you can add.

**Comment by riccardoscalco** [comment]
I updated the [PR](https://github.com/mdn/content/pull/2142/files). Let me know if there is something else to add.

**Comment by himanshugarg** [comment]
With the [PR](https://github.com/mdn/content/pull/2142) merged, is there more to be done here?

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/2141#issuecomment-991841894
