### ISSUE TITLE
Broken link on `iframe` page

### ISSUE THREAD

**Issue by sarveshraj** [mdn/content#21424]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attributes

### What information was incorrect, unhelpful, or incomplete?

In the section, see this sentence:

> For more information and examples see: [Using Feature Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy) > [The iframe allow attribute](https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy#the_iframe_allow_attribute).

The link of the text `The iframe allow attribute` (https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy#the_iframe_allow_attribute) does not exist.

### What did you expect to see?

I am not sure what the correct link should be

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/iframe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/iframe/index.md
* Last commit: https://github.com/mdn/content/commit/b56483692fd247dd7c5f11af4233ad40bf19ac31
* Document last modified: 2022-09-14T07:57:28.000Z

</details>

**Comment by sideshowbarker** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy#the_iframe_allow_attribute does seem to exist. 

Can you please try checking again?

**Comment by sarveshraj** [comment]
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy#the_iframe_allow_attribute does seem to exist.
> 
> Can you please try checking again?

Hey @sideshowbarker,
The page does exist but the section identified by `#the_iframe_allow_attribute` does not.

**Comment by sideshowbarker** [comment]
That section does exist, with that same ID —

![image](https://user-images.githubusercontent.com/194984/194797442-cebde8a8-a7f6-403a-b2b2-78d09526869a.png)

**Comment by sarveshraj** [comment]
Weird. You are right. I can see that it does exist. I am unsure why my browser (Chrome) is not scrolling down to the section. 

I will close this issue now as it is no longer about MDN. Apologies for the false alarm and thank you so much for the quick turnaround!
