### ISSUE TITLE
ETag tracking is no longer feasible due to HTTP cache partitioning in browsers

### ISSUE THREAD

**Issue by ziyunfei** [mdn/content#21469]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

### What information was incorrect, unhelpful, or incomplete?

"Etags are therefore similar to fingerprints, and might also be used for tracking purposes by some servers. They might also be set to persist indefinitely by a tracking server."

### What did you expect to see?

ETag-based tracking is dead. this content confuses readers, should be removed.

### Do you have any supporting links, references, or citations?

https://en.wikipedia.org/wiki/HTTP_ETag#Tracking_using_ETags
https://developer.chrome.com/blog/http-cache-partitioning/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/etag`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/etag/index.md
* Last commit: https://github.com/mdn/content/commit/36001a269f4d7b2b3ac6de79e942a5f849bb87d8
* Document last modified: 2022-09-09T05:53:39.000Z

</details>

**Comment by sideshowbarker** [comment]
Can you cite any other sources to support the assertion that “ETag-based tracking is dead”?

https://en.wikipedia.org/wiki/HTTP_ETag#Tracking_using_ETags has nothing to support that assertion, as far as I can see.

https://developer.chrome.com/blog/http-cache-partitioning/ says nothing directly to support that assertion — and it’s not clear to me at least that cache partitioning eliminates the ability to use Etags for tracking. And regardless, that article is about is just about the behavior in Chrome, and says nothing about other browsers.

**Comment by sideshowbarker** [comment]
> [privacytests.org/nightly-private.html](https://privacytests.org/nightly-private.html) see "image cache"

To a normal web developer reading that, it’s not going to be clear what relationship it has to Etag-based tracking.

To be clear, I think making a change for this issue is something we need do — and I think we should more than just remove the text cited in the issue description. We should replace it with something like this:

> In the past it was be possible to use Etags for tracking purposes. However, current browser engines all implement cache partitioning (also known as network partitioning), which prevents Etag-based tracking.

…but the problem is, I can’t find any sources we can point to which clearly state that:

1. Browser engines have all implemented cache partitioning.
2. Cache partitioning prevents Etag-based tracking.

**Comment by sideshowbarker** [comment]
Thanks for raising this. I’ve gone ahead and opened #21502 with a patch that just deletes the outdated statements (as suggested in the issue description). It would be nicer to have something to replace it with — but after looking around, I’ve not been able to find any suitable sources to cite, so without writing something up about it ourselves in MDN, there’s unfortunately doesn’t seem to be anything else we could point to.

**Comment by wbamberg** [comment]
> Thanks for raising this. I’ve gone ahead and opened #21502 with a patch that just deletes the outdated statements (as suggested in the issue description). It would be nicer to have something to replace it with — but after looking around, I’ve not been able to find any suitable sources to cite, so without writing something up about it ourselves in MDN, there’s unfortunately doesn’t seem to be anything else we could point to.

It seems like this might be close: https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning ? But it is very Firefox-specific and would need rework to be made directly relevant.

**Comment by sideshowbarker** [comment]
> It seems like this might be close: [developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning](https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning) ? But it is very Firefox-specific and would need rework to be made directly relevant.

Yeah I think that’s the closest we have to what we’d want. Ideally we’d probably also want to make some additions to the HTTP Caching article that cover specific details about how browsers assign keys for Etags (along with some discussion about cache partitioning).
