### ISSUE TITLE
Issue with "Window.devicePixelRatio": (short summary here please)

### ISSUE THREAD

**Issue by pushkine** [mdn/content#2147]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

Section "Monitoring screen resolution or zoom level changes"

The intent of the snippet is to "check the value of devicePixelRatio any time it changes", however the snippet fails to update whenever the MediaQueryList does not match twice in a row, the example must update the query on every call in order to respect the described intent

```diff
let pixelRatioBox = document.querySelector(".pixel-ratio");
- let mqString = `(resolution: ${window.devicePixelRatio}dppx)`;

const updatePixelRatio = () => {
  let pr = window.devicePixelRatio;
  let prString = (pr * 100).toFixed(0);
  pixelRatioBox.innerText = `${prString}% (${pr.toFixed(2)})`;
+ matchMedia(`(resolution: ${pr}dppx)`).addEventListener("change", updatePixelRatio, { once: true })
}

updatePixelRatio();
- 
- matchMedia(mqString).addListener(updatePixelRatio);
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/devicepixelratio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/window/devicepixelratio/index.html
* Last commit: https://github.com/mdn/content/commit/099cf87a13ed06cd368d3d2a8e9e4a6dfae7295e
* Document last modified: 2021-01-15T10:00:23.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update the snippet 👍

**Comment by Rumyra** [comment]
Hi @CreaTorAlexander how are you getting on with this?

**Comment by CreaTorAlexander** [comment]
I actually thought it were fixed so I didn't work on it. I will update it later on, thank you for the reminder 😄
