### ISSUE TITLE
Missing explanation about IteratorResult

### ISSUE THREAD

**Issue by andreidiaconescu** [mdn/content#21478]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols

### What specific section or headline is this issue about?

The iterator protocol

### What information was incorrect, unhelpful, or incomplete?

the page says 

> "A function that accepts zero or one argument and returns an object conforming to the IteratorResult interface (see below)" 

but it never explains what is an "IteratorResult"

### What did you expect to see?

An explanation about what is an IteratorResult.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/iteration_protocols`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/iteration_protocols/index.md
* Last commit: https://github.com/mdn/content/commit/9b38f886d21c5d0a428f58acb20c4d0fc6c2e098
* Document last modified: 2022-09-12T13:06:56.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, the text below says:

> All iterator protocol methods (`next()`, `return()`, and `throw()`) are expected to return an object implementing the `IteratorResult` interface. It must have the following properties:

That is meant to define `IteratorResult`.
