### ISSUE TITLE
Math.abs() return value section.

### ISSUE THREAD

**Issue by stevendwood** [mdn/content#21526]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/abs

### What specific section or headline is this issue about?

Return Value

### What information was incorrect, unhelpful, or incomplete?

If x is negative (including -0), returns -x. Otherwise, returns x

### What did you expect to see?

Not sure - but Math.abs always returns a positive value so something like that ?

### Do you have any supporting links, references, or citations?

The examples section show as much. e.g. Math.abs(-1) gives 1

### Do you have anything more you want to share?

Nope :)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/math/abs`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/abs
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/abs/index.md
* Last commit: https://github.com/mdn/content/commit/d6ce8fcbbc4a71ec9209f379e5ea9774bbf1f5ac
* Document last modified: 2022-09-13T07:06:03.000Z

</details>

**Comment by stevendwood** [comment]
The statement "If x is negative (including -0), returns -x" is not true unless I am misunderstanding what is supposed to be meant.  The function never returns a negative number so it would not return -x ?

**Comment by Josh-Cena** [comment]
If `x` is negative, `-x` would be positive. -(-1) is 1.

**Comment by stevendwood** [comment]
Ah :)  OK then, agree can be closed, fair comment.
