### ISSUE TITLE
events.Event page has invalid links

### ISSUE THREAD

**Issue by danielbWork** [mdn/content#21523]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/events/Event

### What specific section or headline is this issue about?

Methods

### What information was incorrect, unhelpful, or incomplete?

The link in the page are invalid and lead to non-existent pages

### What did you expect to see?

Either the links working or no links at all

**Comment by bsmth** [comment]
Hi @danielbWork, thanks for raising this one. The links are added as placeholders, so this in intentional. Sorry if this is misleading, but the placeholders are there so that content will be added for the links at some point. 

I'm going to close this one for now. Thank you :)
