### ISSUE TITLE
[SVG] remove SVGSVGElement.useCurrentView

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#21539]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

`SVGSVGElement.useCurrentView` was removed from SVG2. FF107 removes it. (note that `currentView` also out of spec, but not implemented in FF).

Action is to update BCD and add a release note. There is no documentation other than a mention in https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement#instance_properties, which already shows this as deprecated.

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1174097

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if [Glossary](https://developer.mozilla.org/en-US/docs/Glossary) updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/18054
- [ ] Docs - none
- [ ] Release note:
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
Thanks @hamishwillee
