### ISSUE TITLE
Closing slashes not needed in markup

### ISSUE THREAD

**Issue by RobBelics** [mdn/content#21547]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Security/Types_of_attacks

### What specific section or headline is this issue about?

Cross-site request forgery (CSRF)

### What information was incorrect, unhelpful, or incomplete?

The `<img>` and `<input>` HTML tags have a closing slash on them. A closing slash is not called for in any HTML standard. While allowed for backwards compatibility to XHTML used in older sites, the spec states it has no meaning, it does nothing and browsers are instructed to ignore it. 

The closing slashes should be removed.

https://html.spec.whatwg.org/dev/embedded-content.html#the-img-element
https://html.spec.whatwg.org/dev/input.html#the-input-element

### What did you expect to see?

```
<img
  src="https://bank.example.com/withdraw?account=bob&amount=1000000&for=mallory">
```

```
<form action="https://bank.example.com/withdraw" method="POST">
  <input type="hidden" name="account" value="bob">
  <input type="hidden" name="amount" value="1000000">
  <input type="hidden" name="for" value="mallory">
</form>
<script>
  window.addEventListener('DOMContentLoaded', (e) => { document.querySelector('form').submit(); }
</script>
```

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/dev/embedded-content.html#the-img-element
https://html.spec.whatwg.org/dev/input.html#the-input-element

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/security/types_of_attacks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Types_of_attacks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/security/types_of_attacks/index.md
* Last commit: https://github.com/mdn/content/commit/f7a5accb5daac36bf909f45ad79642a454e64646
* Document last modified: 2022-10-01T17:24:44.000Z

</details>

**Comment by schalkneethling** [comment]
Thank you for opening this issue, @RobBelics. We already have a discussion around this topic, so I am going to close this issue as this is more of a discussion topic that an issue we can act on at this time.

https://github.com/orgs/mdn/discussions/242
