### ISSUE TITLE
Correct description about class hoisting

### ISSUE THREAD

**Issue by bsmth** [mdn/content#21546]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

### What specific section or headline is this issue about?

Introductory paragraphs

### What information was incorrect, unhelpful, or incomplete?

Quoting @iamzapata 

> Variable and class declarations are also hoisted, so they too can be referenced before they are declared. Note that doing so can lead to unexpected errors, and is not generally recommended.

This paragraph should be rephrased, or perhaps eliminated. Specifically it contradicts the class hoisting section, where it says that referencing a class before initialisation will result in an error.

### What did you expect to see?

https://github.com/mdn/content/pull/18571

#### Motivation

> Variable and class declarations are also hoisted, so they too can be referenced before they are declared. Note that doing so can lead to unexpected errors, and is not generally recommended.

While "Variable and class declarations are also hoisted" is true, the sentence that follows, "so they too can be referenced before they are declared" is only true for variables, specifically for `var` declarations (differences with `const` and `let` are discussed later in the document), classes on the other hand, will fail to be referenced. 

The following code will give an error:

```javascript
const catClassRef = Cat;

class Cat {}
```

**Error in NodeJS**
[node replit](https://replit.com/@AndresZapata11/Hoisting#index.js)

```bash
ReferenceError: Cannot access 'Cat' before initialization
    at Object.<anonymous> (/home/runner/Hoisting/index.js:1:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

**Error in Chrome**
[codesandbox](https://codesandbox.io/s/class-hoisting-nwuyr9)
[codesandbox live url](https://nwuyr9.csb.app/)

```bash
Uncaught ReferenceError: Cannot access 'Cat' before initialization

### Do you have any supporting links, references, or citations?

discussion in https://github.com/mdn/content/pull/18571

### Do you have anything more you want to share?

_No response_

**Comment by bsmth** [comment]
@iamzapata and @Josh-Cena I've created an issue to track this

**Comment by Josh-Cena** [comment]
Thanks! Cross-linking https://github.com/mdn/content/issues/18901 and https://github.com/mdn/content/issues/16923
