### ISSUE TITLE
Font-variant-alternates page suggests to pirate a copyrighted font

### ISSUE THREAD

**Issue by drott** [mdn/content#21553]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates#examples

### What information was incorrect, unhelpful, or incomplete?

> Note: You need to install the OpenType font Leitura Display Swashes for this example to work. You can find a few free versions for testing purposes, for example from [fontsgeek.com](https://fontsgeek.com/fonts/Leitura-Display-Swashes).

### What did you expect to see?

I suggest to use an open-source font for swashes and stylistic set examples, instead of publishing a suggestion to break licensing agreements.

### Do you have any supporting links, references, or citations?

Leitura is a font that can be licensed from DSType. While the internet may have copies of it, it doesn't mean that there's a testing license granted. https://www.dstype.com/fonts/leitura-display-two/glyphs/swashes/all-glyphs

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-variant-alternates`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-variant-alternates/index.md
* Last commit: https://github.com/mdn/content/commit/fb2af1f15456199685a9f4fbaf8c9d003a2bf91f
* Document last modified: 2022-09-27T02:27:51.000Z

</details>

**Comment by drott** [comment]
For swashes, alternative from the Google Font corpus may be found from this list:

```
Arsenal-BoldItalic.ttf
Arsenal-Bold.ttf
Arsenal-Italic.ttf
Arsenal-Regular.ttf
Bellota-BoldItalic.ttf
Bellota-Bold.ttf
Bellota-Italic.ttf
Bellota-LightItalic.ttf
Bellota-Light.ttf
Bellota-Regular.ttf
BellotaText-BoldItalic.ttf
BellotaText-Bold.ttf
BellotaText-Italic.ttf
BellotaText-LightItalic.ttf
BellotaText-Light.ttf
BellotaText-Regular.ttf
BhuTukaExpandedOne-Regular.ttf
Bilbo-Regular.ttf
BioRhyme-Bold.ttf
BioRhymeExpanded-Bold.ttf
BioRhymeExpanded-ExtraBold.ttf
BioRhymeExpanded-ExtraLight.ttf
BioRhymeExpanded-Light.ttf
BioRhymeExpanded-Regular.ttf
BioRhyme-ExtraBold.ttf
BioRhyme-ExtraLight.ttf
BioRhyme-Light.ttf
BioRhyme-Regular.ttf
BonaNova-Italic.ttf
EBGaramond-Italic[wght].ttf
EBGaramond[wght].ttf
Estonia-Regular.ttf
Gulzar-Regular.ttf
IMFeENit28P.ttf
IMFeFCit28P.ttf
IMFeGPit28P.ttf
IMFELLDoublePica-Italic.ttf
IMFePIit28P.ttf
Itim-Regular.ttf
Lekton-Bold.ttf
Lekton-Regular.ttf
LindenHill-Italic.ttf
MonteCarlo-Regular.ttf
Playball-Regular.ttf
Salsa-Regular.ttf
SansitaSwashed[wght].ttf
Smooch-Regular.ttf
StyleScript-Regular.ttf
WindSong-Medium.ttf
WindSong-Regular.ttf
WorkSans[wght].ttf```

**Comment by robnyman** [comment]
cc @Rumyra @Elchi3 Can you please help here?

**Comment by Elchi3** [comment]
I don't know much about fonts, but I created a PR. Let me know if you have any feedback. https://github.com/mdn/content/pull/21597
