### ISSUE TITLE
Response.json static method is missing

### ISSUE THREAD

**Issue by jespertheend** [mdn/content#21550]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Response

### What specific section or headline is this issue about?

Response.json

### What information was incorrect, unhelpful, or incomplete?

Only the non static `Response.json()` method is mentioned, but not the static one

### What did you expect to see?

A `Response.json()` page explaining what it does. And an extra entry in the compatibility table.
Currently it is only supported in Edge and  Chrome as far as I can tell.

### Do you have any supporting links, references, or citations?

https://fetch.spec.whatwg.org/#ref-for-dom-response-json

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/response`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/response/index.md
* Last commit: https://github.com/mdn/content/commit/06105598d11001e9f12d80ad05087f1df3c0634b
* Document last modified: 2022-10-10T09:00:13.000Z

</details>

**Comment by wbamberg** [comment]
See also https://github.com/openwebdocs/project/issues/104. We're not able to document this yet on MDN :(

**Comment by jespertheend** [comment]
🥲

**Comment by wbamberg** [comment]
I just started https://github.com/mdn/mdn-community/discussions/264.

**Comment by Josh-Cena** [comment]
Fixed by #27154. #22970 will add the last missing parts.
