### ISSUE TITLE
Support Zoom!

### ISSUE THREAD

**Issue by johnaweiss** [mdn/content#21562]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

### What specific section or headline is this issue about?

_"The non-standard zoom [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) property can be used to control the magnification level of an element. [transform: scale()](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale) should be used instead of this property, if possible. However, unlike CSS Transforms, zoom affects the layout size of the element."_

### What information was incorrect, unhelpful, or incomplete?

Firefox should support zoom. I think it’s not appropriate for you to recommend transform:scale – it’s a _different functionality, different behavior_. 

### What did you expect to see?

I expect to see Firefox support a feature that **every other browser supports** -- regardless of standards track. 

### Do you have any supporting links, references, or citations?

https://forum.freecodecamp.org/t/simplest-modern-x-browser-css-to-zoom-with-flow/563166

### Do you have anything more you want to share?

There are no simple workarounds to make transform:scale act like zoom. In 2022, developers shouldn't need workarounds anyway. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/zoom`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/zoom
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/zoom/index.md
* Last commit: https://github.com/mdn/content/commit/413355c790c4102eea5937465ea610938327fe56
* Document last modified: 2022-09-27T03:53:49.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! MDN web docs does not control the development of Firefox in any way, neither are we Firefox-centric. We document the web as it is, including factual statements about implementation status and standardization status. If you want to see a feature in Firefox, please report to them directly at https://bugzilla.mozilla.org/home
