### ISSUE TITLE
QUIC is not experimental

### ISSUE THREAD

**Issue by ekr** [mdn/content#21579]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Evolution_of_HTTP

### What specific section or headline is this issue about?

HTTP/3 - HTTP over QUIC

### What information was incorrect, unhelpful, or incomplete?

The section on QUIC shows an experimental banner, but QUIC/HTTP/3 is now standardized and widely deployed.

CCing @martinthomson

### What did you expect to see?

A description of QUIC.

### Do you have any supporting links, references, or citations?

https://datatracker.ietf.org/doc/rfc9114/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/basics_of_http/evolution_of_http`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Evolution_of_HTTP
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/evolution_of_http/index.md
* Last commit: https://github.com/mdn/content/commit/8e1f45b8c0a3671f6e3de43c0764ad610aa345dd
* Document last modified: 2022-09-14T09:06:12.000Z

</details>

**Comment by sideshowbarker** [comment]
In https://developer.mozilla.org/en-US/docs/Glossary/QUIC also, the mentions of QUIC as being experimental and _“There is limited browser and server support for QUIC today”_, etc., should be removed/rewritten
