### ISSUE TITLE
Incorrect (or at best ambiguous) dsentences

### ISSUE THREAD

**Issue by DovJacobson** [mdn/content#21572]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView

### What specific section or headline is this issue about?

 [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer)

### What information was incorrect, unhelpful, or incomplete?

[DataView.prototype.byteLength](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/byteLength)
The length (in bytes) of this view from the start of its [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer). Fixed at construction time and thus read only.

### What did you expect to see?

[DataView.prototype.byteLength](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/byteLength)
The length (in bytes) of this view. Fixed at construction time and thus read only.

### Do you have any supporting links, references, or citations?

The existing description implies that this value reflects not just its size, but its position in ArrayBuffer. 
This seems far more likely to be a copy-paste error in this documentation than an aberration in the API design.

### Do you have anything more you want to share?

my first comment ever!!
I LOVE MDN!!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/dataview`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/dataview/index.md
* Last commit: https://github.com/mdn/content/commit/968e6f1f3b6f977a09e116a0ac552459b741eac3
* Document last modified: 2022-09-09T05:25:05.000Z

</details>

**Comment by Josh-Cena** [comment]
Looks like a copy&paste error. Want to send a PR?

**Comment by DovJacobson** [comment]
I'm new. Don't know what PR means. If it means Problem Report, I thought I
just sent one.

**Comment by Josh-Cena** [comment]
It means pull request, which is the way you submit work to us to review. You can follow https://github.com/mdn/content/blob/main/CONTRIBUTING.md

**Comment by DovJacobson** [comment]
Thanks Josh -

Made my first correction and PR



*Dov Jacobson*

Managing Director
*Games*That*Work*.com

m:404 610 6750

<http://gamesthatwork.com/>
