### ISSUE TITLE
Link to HTTP/3 browser compatibility table leads to nothing / table is missing

### ISSUE THREAD

**Issue by lbrocke** [mdn/content#21574]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Evolution_of_HTTP#http3_-_http_over_quic

### What specific section or headline is this issue about?

HTTP/3 - HTTP over QUIC

### What information was incorrect, unhelpful, or incomplete?

The `{{SeeCompatTable}}` makro on the _Evolution of HTTP_ page generates a link to a browser compatibility table stating:

> Check the [Browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Evolution_of_HTTP#browser_compatibility) carefully before using this in production.

The link (`<a href="#browser_compatibility">Browser compatibility table</a>`) however leads to nothing, as there is no `browser_compatibility` anchor on the page.

### What did you expect to see?

A HTTP/3 browser compatibility table, probably generated by the `{{Compat}}` makro in a section called _Browser compatibility_.

### Do you have any supporting links, references, or citations?

I used the page [Alt-Svc HTTP header documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc#browser_compatibility) as reference.

It seems like to use the `{{Compat}}` makro, it is necessary to include a `browser-compat: ...` line in the front matter of the page. However, I suspect there is no data on HTTP/3 compatibility yet, as reported in [issue #7034 of the mdn / browser-compat-data repository](https://github.com/mdn/browser-compat-data/issues/7034)?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/basics_of_http/evolution_of_http`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Evolution_of_HTTP
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/evolution_of_http/index.md
* Last commit: https://github.com/mdn/content/commit/8e1f45b8c0a3671f6e3de43c0764ad610aa345dd
* Document last modified: 2022-09-14T09:06:12.000Z

</details>

**Comment by sideshowbarker** [comment]
> I suspect there is no data on HTTP/3 compatibility yet, as reported in [issue #7034 of the mdn / browser-compat-data repository](https://github.com/mdn/browser-compat-data/issues/7034)?

That’s correct. We’d need for the data to be added in the browser-compat-data repo
