### ISSUE TITLE
Border-image generator should allow "auto" as a border-image-width value

### ISSUE THREAD

**Issue by BawdyInkSlinger** [mdn/content#21582]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Border-image_generator

### What specific section or headline is this issue about?

Border-image generator

### What information was incorrect, unhelpful, or incomplete?

 border-image-width does not allow you to enter a value of "auto" but that is a valid value: https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-width

### What did you expect to see?

After I typed "auto" and tabbed away, I expected that value to stay. Instead, it returned to "20"

### Do you have anything more you want to share?

https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-width 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_backgrounds_and_borders/border-image_generator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Border-image_generator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_backgrounds_and_borders/border-image_generator/index.md
* Last commit: https://github.com/mdn/content/commit/71c4bc0b6329ec40ddbefd8d3124547e91cfa612
* Document last modified: 2022-09-28T03:40:57.000Z

</details>

**Comment by Anurella** [comment]
I do not think the value auto should be added as the current input box was not built to accommodate a string, it might also defeat the purpose or intent of why it was created and the way it was set up. @sideshowbarker I would suggest a "**see also**" section that links to the _Constituent_ properties so a user can read more about it and would find out that the "auto" exists

**Comment by BawdyInkSlinger** [comment]
@Anurella 

> it might also defeat the purpose or intent of why it was created and the way it was set up

Maybe this is where I'm confused. What is the purpose/intent of this tool?

**Comment by Anurella** [comment]
@BawdyInkSlinger 

> Maybe this is where I'm confused. What is the purpose/intent of this tool?

By intent drawn from the input element the tool provides, it wants users to explore numeric values against the different properties, maybe that is why there is no room for a string value.
