### ISSUE TITLE
Update webRequest.onAuthRequired extraInfoSpec with Chrome webRequestAuthProvider

### ISSUE THREAD

**Issue by erosman** [mdn/content#21586]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onAuthRequired

### What specific section or headline is this issue about?

extrainfospec + Browser compatibility

### `webRequestAuthProvider`
New `extraInfoSpec` is created by Chrome for MV3 (only) due for
Chrome 108
Stable Release
Tue, Nov 29, 2022

### What did you expect to see?

Update `extrainfospec` + Browser compatibility with the information

### Do you have any supporting links, references, or citations?

https://groups.google.com/a/chromium.org/g/extensions-reviews/c/WEtDeiGxbuM
https://bugs.chromium.org/p/chromium/issues/detail?id=1135492
https://source.chromium.org/chromium/chromium/src/+/main:extensions/browser/api/web_request/web_request_api.cc;l=2857

Commit [ccaeb346...](https://crrev.com/ccaeb346182918e7e97f3dff20b2fab316ec6d2c) initially landed in 108.0.5341.0
https://storage.googleapis.com/chromium-find-releases-static/cca.html#ccaeb346182918e7e97f3dff20b2fab316ec6d2c

**Comment by Rob--W** [comment]
Feature request at Firefox's side: https://bugzilla.mozilla.org/show_bug.cgi?id=1820569
