### ISSUE TITLE
No information on how to select Horizontal and vertical scrollbars

### ISSUE THREAD

**Issue by Pavan-Rajesh** [mdn/content#21581]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

### What information was incorrect, unhelpful, or incomplete?
incomplete about selecting the horizontal and vertical scrollbars

### What did you expect to see?

-webkit-scrollbar:horizontal{
}
and 
-webkit-scrollbar:vertical{
}

this is the content i need in this page

**Comment by Anurella** [comment]
@Pavan-Rajesh The write-up focuses on the different parts of the scroll bar and your request is about the different states of the scroll bar.   @sideshowbarker  can suggest if the states should be a different article or added to the current page. 

If you are interested in learning more about the different states, the "See Also" section has a link [Webkit Blog](https://webkit.org/blog/363/styling-scrollbars/)
