### ISSUE TITLE
Using addition assignment

### ISSUE THREAD

**Issue by IsabelDR** [mdn/content#21594]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Addition_assignment

### What specific section or headline is this issue about?

Using addition assignment

### What information was incorrect, unhelpful, or incomplete?

let baz = true;
// Number + Boolean -> addition
baz += false; // 2

let foo = 'foo';
// String + String -> concatenation
foo += 'bar'; // "foofalsebar"

let bar = 5;
// Number + String -> concatenation
bar += 'foo'; // "7foo"

### What did you expect to see?

let baz = true;
// Number + Boolean -> addition
baz += false; // **1**

let foo = 'foo';
// String + String -> concatenation
foo += 'bar'; // **"foobar"**

let bar = 5;
// Number + String -> concatenation
bar += 'foo'; // **"5foo"**

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/addition_assignment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Addition_assignment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/addition_assignment/index.md
* Last commit: https://github.com/mdn/content/commit/c4abfc721a9848dfa28bb121f75ab14ab9b9f67b
* Document last modified: 2022-09-19T04:44:15.000Z

</details>

**Comment by Josh-Cena** [comment]
Sorry, I don't see how your proposed change is an improvement over the existing content. Specifically, this:

```js
let baz = true;
// Number + Boolean -> addition
baz += false; // 1
```

Is a spurious comment, because it's doing Boolean + Boolean. Everything else seems to be a paraphrase of the existing content. I'm going to close this for now unless more information is provided.

**Comment by IsabelDR** [comment]
Thanks, I didn't look at it that way. I thought both "returns" could me looked at independently.
