### ISSUE TITLE
Inconsistent advice on the meaning of <mark>

### ISSUE THREAD

**Issue by charlesroper** [mdn/content#21595]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark

### What specific section or headline is this issue about?

The intro paragraph and a later note block in usage notes

### What information was incorrect, unhelpful, or incomplete?

The intro paragraph says this:

> The `<mark>` [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents text which is marked or highlighted for reference or notation purposes, due to the marked passage's relevance or importance in the enclosing context.

Whereas later in usage notes in the Note block is says this:

> Note: Don't confuse `<mark>` with the `<strong>` element; `<mark>` is used to denote content which has a degree of _relevance_, while `<strong>` indicates spans of text of _importance_.

According to [the spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-mark-element), the later note block is correct: `<mark>` is not supposed to denote _importance_, only _relevance_. Therefore I suggest the intro paragraph should say "due to the marked passage's relevance in the enclosing context" with reference to importance removed.

### What did you expect to see?

The `<mark>` [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents text which is marked or highlighted for reference or notation purposes, due to the marked passage's relevance in the enclosing context.

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-mark-element

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/mark`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/mark/index.md
* Last commit: https://github.com/mdn/content/commit/b56483692fd247dd7c5f11af4233ad40bf19ac31
* Document last modified: 2022-09-14T07:57:28.000Z

</details>

**Comment by bsmth** [comment]
Hi @charlesroper thanks for raising this one, would you like to open a pull request to make these changes?

**Comment by charlesroper** [comment]
Would be a pleasure. I'll check CONTRIBUTING.md as I've not contributed before. Anything else I need to be aware of or is it all in there?

**Comment by bsmth** [comment]
Sounds good. Everything should be in the contributing.md doc - if not, let us know and we can add it. Thanks! 🙌🏻
