### ISSUE TITLE
incomplete sentence/information

### ISSUE THREAD

**Issue by Azlynne** [mdn/content#21607]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started

### What specific section or headline is this issue about?

Step 1- How to make an HTTP request

### What information was incorrect, unhelpful, or incomplete?

A common pitfall is accessing your site by domain.tld, but attempting to call pages with www.domain.tld. 

### What did you expect to see?

Incomplete sentence - what happens when you access a site by domain.tld?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/guide/ajax/getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/ajax/getting_started/index.md
* Last commit: https://github.com/mdn/content/commit/e14e4830bcd43de164623aaf787fbd695be31d91
* Document last modified: 2022-10-06T14:19:29.000Z

</details>

**Comment by Josh-Cena** [comment]
```
A common pitfall   is    accessing your site by domain.tld,
================ ======  =================================
     SUBJECT     COPULA              ATTRIBUTE
```

This sentence is grammatically well-formed. It's telling you that calling the site by www.domain.ltd is "a common pitfall", because it should be domain.ltd instead.
