### ISSUE TITLE
AudioEncoder example is bogus

### ISSUE THREAD

**Issue by Vanilagy** [mdn/content#21624]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AudioEncoder/configure

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

The example tries to configure an AudioEncoder with

```javascript
let config = {
  codec: "vp8",
  bitrate: 2_000_000, // 2 Mbps
};
```
, which is complete bogus. It looks like somebody took the VideoEncoder example and just replaced Video with Audio.

### What did you expect to see?

I propose something like

```javascript
let config = {
  codec: "opus",
  bitrate: 64_000, // 64 kbps
};
```

### Do you have any supporting links, references, or citations?

Allowed codecs: https://www.w3.org/TR/webcodecs-codec-registry/#audio-codec-registry

### Do you have anything more you want to share?

The documentation and examples on WebCodecs as it stands is still a bit thin. I understand this though, as the API is new and quite experimental, and very niche in usage. I might look into improving parts of it in the future if I feel I'm knowledgeable enough.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/audioencoder/configure`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioEncoder/configure
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/audioencoder/configure/index.md
* Last commit: https://github.com/mdn/content/commit/02e1bfcad5fd0de845fb033d331c3c027afa2d6e
* Document last modified: 2022-09-14T13:55:15.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing, @Vanilagy ! since you've provided a fix here, would you like to open a PR with it?

**Comment by wbamberg** [comment]
Seems to be fixed by https://github.com/mdn/content/pull/22376.
