### ISSUE TITLE
 JXON instead of JSON

### ISSUE THREAD

**Issue by 6akcuk** [mdn/content#21620]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/How_to_create_a_DOM_tree

### What specific section or headline is this issue about?

About "See Also" section

### What information was incorrect, unhelpful, or incomplete?

There is a list of what you can see also and there is a spelling mistake: JXON instead of JSON

### What did you expect to see?

[JSON](https://developer.mozilla.org/en-US/docs/JSON)

### Do you have any supporting links, references, or citations?

[JXON](https://developer.mozilla.org/en-US/docs/JXON)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document_object_model/how_to_create_a_dom_tree`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/How_to_create_a_DOM_tree
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document_object_model/how_to_create_a_dom_tree/index.md
* Last commit: https://github.com/mdn/content/commit/1511e914c6b1ce6f88056bfefd48a6aa585cebce
* Document last modified: 2022-09-09T05:10:34.000Z

</details>

**Comment by Josh-Cena** [comment]
See https://github.com/mdn/content/pull/21585
