### ISSUE TITLE
Ill-defined `options` recommended for custom error types

### ISSUE THREAD

**Issue by AxeOfMen** [mdn/content#21632]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

### What specific section or headline is this issue about?

#differentiate_between_similar_errors

### What information was incorrect, unhelpful, or incomplete?

Information regarding using the cause property in custom errors is provided:

> [Custom error types](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#custom_error_types) can also use the [cause](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#error.prototype.cause) property, provided the subclasses' constructor passes the options parameter when calling super():

An example is given that uses a variable called `options` but it is not defined in the example nor is it explained. What is this `options` you speak of?

### What did you expect to see?

`options` needs to be explained and/or defined. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/error`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/error/index.md
* Last commit: https://github.com/mdn/content/commit/9b38f886d21c5d0a428f58acb20c4d0fc6c2e098
* Document last modified: 2022-09-12T13:06:56.000Z

</details>

**Comment by Josh-Cena** [comment]
It says "the `options` parameter of the constructor", so you should look for it on the constructor page.

**Comment by AxeOfMen** [comment]
The example would be more helpful if 
`/* some arguments */`
was replaced with actual arguments. If the code snippet was an actual working class, clarity would be achieved.

**Comment by Josh-Cena** [comment]
> The example would be more helpful if 
> 
> `/* some arguments */`
> 
> was replaced with actual arguments. If the code snippet was an actual working class, clarity would be achieved.

Indeed, I would work on this. Also, in case you haven't realized, the constructor page is separate from the landing page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error
