### ISSUE TITLE
[MathML] Disable lquote/rquote attributes on the <ms> element

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#21635]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

It looks like @fred-wang has updated bcd (thanks!) - but making sure the docs are in sync and release note has been added

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1793387

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

## Related issues and pull requests

- [x] BCD https://github.com/mdn/browser-compat-data/pull/17969
- [x] Content https://github.com/mdn/content/pull/21248
- [x] Relnote https://github.com/mdn/content/pull/22302

**Comment by fred-wang** [comment]
The doc is at https://developer.mozilla.org/en-US/docs/Web/MathML/Element/ms
"Some browsers may also support the following deprecated attributes and will render the content of the `<ms>` element surrounded by the specified opening and closing quotes:"

**Comment by Rumyra** [comment]
Thanks @fred-wang 👍

**Comment by bsmth** [comment]
I've assigned this one, will take a look at tasks for this shortly 👀

**Comment by bsmth** [comment]
From the [changes to preflist yaml](https://phabricator.services.mozilla.com/rMOZILLACENTRALfba770dda4d9bf6a7f9fc0c35467a9c45801b120):

```yaml
# Whether to disable the lquote/rquote attributes of the <ms> element.
- name: mathml.ms_lquote_rquote_attributes.disabled
  type: bool
  value: true
```

**Comment by bsmth** [comment]
It appears we're all complete with the sub-tasks for this, so I will set the bug to `dev-doc-complete` ✅
