### ISSUE TITLE
Live sample is not themed correctly

### ISSUE THREAD

**Issue by LunarTwilight** [mdn/content#21650]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Location

### What specific section or headline is this issue about?

Location anatomy

### What information was incorrect, unhelpful, or incomplete?

live sample is impossible/hard to read
![image](https://user-images.githubusercontent.com/13520392/196614910-6cea707e-3433-464b-83c7-cbacca76e3d8.png)

### What did you expect to see?

a themed live sample that is easy to read

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/location`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Location
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/location/index.md
* Last commit: https://github.com/mdn/content/commit/bbecba9e7d688493adbdc37fc70e02d87adfe371
* Document last modified: 2022-10-10T08:33:38.000Z

</details>

**Comment by bsmth** [comment]
Thanks @LunarTwilight I can take a look 👀

**Comment by Josh-Cena** [comment]
It's supposed to be hovered over, not read directly. As soon as you start interacting with it it should be apparent.

**Comment by wbamberg** [comment]
Would be nice to get rid of that scrollbar though.

**Comment by Josh-Cena** [comment]
That's true... the black boxes look suspicious. Displaying the text in a subdued gray font and making it black on hover may be better.

**Comment by bsmth** [comment]
Thanks for the hints, I've taken a shot at fixing this in the linked PR.
