### ISSUE TITLE
Addition assignement (+=)

### ISSUE THREAD

**Issue by mikkathecoder** [mdn/content#21663]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Addition_assignment

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Addition_assignment#using_addition_assignment

### What information was incorrect, unhelpful, or incomplete?

let baz = true;

// Boolean + Number -> addition
baz += 1; // 2

// Number + Boolean -> addition
baz += false; // 2

### What did you expect to see?

let baz = true;

// Boolean + Number -> addition
baz += 1; // 2

// Number + Boolean -> addition
baz += false; // 1

### Do you have anything more you want to share?

false = 0
true = 1
if baz = true then baz = 1
baz += true = 1 + 1 = 2

if false = 0
baz += false = 1 + 0 = 1

check console.log(baz) for further confirmation that baz += false = 1

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/addition_assignment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Addition_assignment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/addition_assignment/index.md
* Last commit: https://github.com/mdn/content/commit/c4abfc721a9848dfa28bb121f75ab14ab9b9f67b
* Document last modified: 2022-09-19T04:44:15.000Z

</details>

**Comment by Josh-Cena** [comment]
See https://github.com/mdn/content/issues/21594
