### ISSUE TITLE
Typo mistake

### ISSUE THREAD

**Issue by V-Dat** [mdn/content#21680]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

### What specific section or headline is this issue about?

Example code in section : instanceof vs Array.isArray() 

### What information was incorrect, unhelpful, or incomplete?

const arr = new xArray(1, 2, 3); // [1, 2, 3]

### What did you expect to see?

const arr = new Array(1, 2, 3); // [1, 2, 3]

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/isarray`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/isarray/index.md
* Last commit: https://github.com/mdn/content/commit/2ba81d27e39fc2a03338b84db4945fdd7f0f5ce9
* Document last modified: 2022-09-19T16:34:20.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, did you understand the example? `xArray` is defined as:

```js
const xArray = window.frames[window.frames.length - 1].Array;
```

I.e. a constructor borrowed from another realm. This is showing how this leads to `Array.isArray` and `instanceof` diverging. If you use the same-realm `Array` constructor, they would be the same thing.
