### ISSUE TITLE
Need explanations.

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#21710]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/content

### What information was incorrect, unhelpful, or incomplete?

Hello,

In this page I wanted to run the example “Image combined with text”.
I run it from notepad++ to Edge and Firefox (last versions).

Contrary to what is written in the topic of the example:
“This example inserts an image before the link. If the image is not found, it inserts text instead.”
the image and the text are not always displayed.

With the initial configuration the image is displayed with Edge and not with Firefox.
If I delete / "Mozilla" the image is displayed with Edge and with Firefox.
If I replace .ico with .xxx to perform a test, the text is not displayed either with Edge or with Firefox.

It should be noted that the result of the example displayed in this page does not display the image or the text. Is there a reason?

Sincerely

postscript: it would be good if the links provided in the examples were complete links (https://...) and not partial links (mdn.svg, ../../media/examples/fire.png).

### What did you expect to see?

Depending on the context that the image or text is displayed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/content/index.md
* Last commit: https://github.com/mdn/content/commit/fb2af1f15456199685a9f4fbaf8c9d003a2bf91f
* Document last modified: 2022-09-27T02:27:51.000Z

</details>

**Comment by hamishwillee** [comment]
For any example, or indeed anything you use, you need to check the browser compatibility table: https://developer.mozilla.org/en-US/docs/Web/CSS/content#browser_compatibility

![image](https://user-images.githubusercontent.com/5368500/197423092-97dd7694-996d-49b4-8f8c-ca495edaec6f.png)

In this case you can see that "alternative text after /" is not supported on firefox but it is on Edge. So in this case Edge finds the image and displays it, while Firefox finds the "/" and considers the line invalid - so it renders nothing. 
Bugs to implement this are in https://bugzilla.mozilla.org/show_bug.cgi?id=1281158 and https://bugzilla.mozilla.org/show_bug.cgi?id=1483898

> postscript: it would be good if the links provided in the examples were complete links (https://...) and not partial links (mdn.svg, ../../media/examples/fire.png).

Relative links are perfectly valid, and as relative links they are much easier for translators to ignore when working with content.

**Comment by DomOBU** [comment]
Thank you for your answer.

When I replace .ico with .xxx to perform a test, the text is not displayed either with Edge or with Firefox.
Shouldn't Edge have displayed the text?
