### ISSUE TITLE
Misunderstanding of parameter use - Array.prototype.flat

### ISSUE THREAD

**Issue by saaadel** [mdn/content#2172]
https://github.com/mdn/content/blob/c34105059b008d9911807e52775cca4772220190/files/en-us/web/javascript/reference/global_objects/array/flat/index.html#L22

`var newArray = arr.flat([depth]);`

`[depth]` - in this context it looks like an array element than an optional parameter. Could we replace it for:
`var newArray = arr.flat(depth);`

**Comment by CreaTorAlexander** [comment]
I can update it 👍
