### ISSUE TITLE
sort method has no thisObject param

### ISSUE THREAD

**Issue by yin1999** [mdn/content#21750]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections#array_methods

### What information was incorrect, unhelpful, or incomplete?

the document show that the `sort()` method can take a (optional) second arg:

![image](https://user-images.githubusercontent.com/15844309/197367350-d9139883-7fcd-4e70-9fe4-603c53e385c7.png)

It seems to be wrong (or I haven't understand it?)

I've made a test as below:

```js
function cmp(a, b) {
	console.log(this);
	return a - b;
}

const arr = [1, 2, 3, 4, 5];

const obj = { t: 1 };

arr.sort(cmp, obj); // log `Window`

console.log('================');

arr.sort(cmp); // log `Window`
```

And I've refered the type define in vs code:

![image](https://user-images.githubusercontent.com/15844309/197367406-ba9487e7-2587-4152-bbb9-aebad84ecb2a.png)

I just can't find any `thisObject` there. Is there any thing I've ignored?

### What did you expect to see?

A question

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/indexed_collections`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/indexed_collections/index.md
* Last commit: https://github.com/mdn/content/commit/3a6cbf0bd59de52f671fd7be990a8c5618237bdd
* Document last modified: 2022-09-23T21:10:37.000Z

</details>

**Comment by Josh-Cena** [comment]
You are right—`sort()` is the _only_ method that takes a callback but doesn't accept `thisObject`. Let's change the intro of _iterative methods_ to `map()` instead, because `sort()` isn't an iterative method.

**Comment by Jack-Zhang-1314** [comment]
But chrome platform provides `thisObject`, I  don't know why
![image](https://user-images.githubusercontent.com/82551626/197370364-830b9c22-f273-4fcf-a4df-091fde118a9b.png)

**Comment by Josh-Cena** [comment]
@Jack-Zhang-1314 `forEach` accepts `thisObject`; only `sort()` doesn't, if that's what you mean.

**Comment by Jack-Zhang-1314** [comment]
Sorry, you're right. I got it wrong

**Comment by yin1999** [comment]
> But chrome platform provides `thisObject`, I don't know why ![image](https://user-images.githubusercontent.com/82551626/197370364-830b9c22-f273-4fcf-a4df-091fde118a9b.png)

`thisObject` arg is used to bind with the callback func, but the `this` object in the callback func is **always** `Window` but not `{t: 1}` which is passed as the `thisObject` (if has).

**Comment by Jack-Zhang-1314** [comment]
yeah, Sorry, I used foreach at the time I thought it was the same

**Comment by Jack-Zhang-1314** [comment]
> You are right—`sort()` is the _only_ method that takes a callback but doesn't accept `thisObject`. Let's change the intro of _iterative methods_ to `map()` instead, because `sort()` isn't an iterative method.

Maybe it should be changed to iterative methods. I think this part is important for other available methods.
