### ISSUE TITLE
No mention of comments in reference

### ISSUE THREAD

**Issue by swetepete** [mdn/content#21761]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML

### What specific section or headline is this issue about?

Reference

### What information was incorrect, unhelpful, or incomplete?

Comments of the form `<!---->` are only mentioned in the HTML Basics section, but I believe the reference should be a complete listing of all elements of the language. If you are experienced with programming but new to HTML you might just want to quickly look up a certain syntax. Searching for "comment" in the search bar returns a result on CSS comments but not HTML comments.

### What did you expect to see?

the comment syntax listed in the reference

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/index.md
* Last commit: https://github.com/mdn/content/commit/eada29e0774d505becb3a725001d372f0dbdc73d
* Document last modified: 2022-09-13T08:52:08.000Z

</details>

**Comment by estelle** [comment]
Comments are listed here: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#html_comments

i think this is asking for a new page: similar to https://developer.mozilla.org/en-US/docs/Web/CSS/Comments but at https://developer.mozilla.org/en-US/docs/Web/HTML/Comments

**Comment by teoli2003** [comment]
Also, for whoever will create the page, note that comments are technically not HTML elements.
