### ISSUE TITLE
`hidden` attribute not Boolean anymore

### ISSUE THREAD

**Issue by j9t** [mdn/content#21760]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/hidden

### What information was incorrect, unhelpful, or incomplete?

With the `until-found` value, `hidden` has become [an enumerated attribute, not a Boolean attribute](https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute).

### What did you expect to see?

n/a

### Do you have any supporting links, references, or citations?

[HTML §6.1.](https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/hidden`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/hidden
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/hidden/index.md
* Last commit: https://github.com/mdn/content/commit/a122e87245c624ba56197641b4d7b21b643a6021
* Document last modified: 2022-09-14T06:08:23.000Z

</details>

**Comment by sideshowbarker** [comment]
Hi Jens — thanks for raising this

Along with updating the **Value** section, we should ideally also get a `hidden=until-found` example added

**Comment by sideshowbarker** [comment]
Ah actually I see we have an example of the `hidden=until-found` content attribute already at https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden#using_until-found — so do you think for the `HTMLElement » hidden` page, it may be sufficient to just update the **Value** section, and just add a paragraph pointing to the existing example at https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden#using_until-found?

**Comment by j9t** [comment]
From a scan the “global” page looks good. I don’t think the “Value” section would be all that needs updating on the attribute page; the intro and examples benefit from that, too. But why maintain two pages in the first place?

**Comment by sideshowbarker** [comment]
> why maintain two pages in the first place?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/hidden is for the IDL attribute, and  https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden is for the content (markup) attribute.

MDN always documents the IDL attributes and content attributes separately

**Comment by wbamberg** [comment]
It's a good question though. I mean it makes sense to have separate pages for the IDL properties that reflect attributes, and it makes sense for the IDL property page to describe syntax and have its own example, but for the semantics and use cases, might it not be better for the IDL attribute page just to link to the attribute page?

At the moment the "Description" for the `hidden` attribute page: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden#description is quite extensive, and there doesn't seem any value in duplicating it.
