### ISSUE TITLE
JSFiddle for TabIndex example no longer accurate?

### ISSUE THREAD

**Issue by ForbiddenEra** [mdn/content#21776]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

### What specific section or headline is this issue about?

"Check out this fiddle to understand the scrolling effects of tabindex."

### What information was incorrect, unhelpful, or incomplete?

When viewing the JS fiddle, the first div says: "Child(orange background div)'s content can NOT be accessed by scrolling with Keyboard"

Tabbing into it, the first tab stop highlights the child (orange background div) which shows a focus ring around it. Using the keyboard does indeed scroll the content of the inner/orange background div. [Though, the message says "Child (orange background div)'s content can NOT be accessed by scrolling with the keyboard", though I can scroll the child element fine]

I cannot however focus the outer (white background) div that contains it, or scroll that div with the keyboard, unless I click within that div with my mouse, then I can scroll the outer div, which makes the next tab stop the inner div again, which I can still scroll with the keyboard.

Starting over (keyboard only, ie. disregarding my mouse focus mentioned in the previous paragraph), the next (second) tab stop on the page is the inner div of the second container; this results in the same behavior as the first (outer can't be scrolled unless mouse focused, inner scrolls with keyboard). [I suppose the label here isn't wrong]

Continuing down the page, the third tab stop is the third outer div, which I can scroll with the keyboard. Next stop is the inner div of the same third outer div, which I can also scroll with keyboard. [Again, label not really wrong I guess]

Fourth box (which is the 5th tab stop) selects the outer div, which I can scroll with keyboard, tabbing again doesn't select the inner div, thus I cannot scroll the inner div with keyboard. [Label here says I *can* scroll the child, but I can't]

Fifth box (6th tab stop) selects the fifth boxes outer div, which I can scroll with keyboard. Another tab selects it's child, which I can also scroll with keyboard. [Label here isn't wrong again I guess]

I should also note that the contrast between the fiddle saying "can [not] be accessed *by* scrolling with the keyboard" feels misleading as if focus should be changed by simply scrolling up/down with the keyboard alone, without any tabs; I'm not sure if that would be an accessibility option somewhere but even so, it contrasts with the description linking to the fiddle that says "its child content cannot be scrolled with the arrow keys" which also feels more accurate and clear.

Also, all the labels/descriptions on the page only refer to the inner div content being scrollable, there are situations (at least, now it seems) where the outer div also isn't scrollable and I wonder if it's worth mentioning/exemplifying that as well.

I'm not sure if behavior has changed since the creation of the fiddle or if behavior maybe varies between user agents; my testing on this was all done with Firefox 106.0.1 (64-bit) on Windows 10.

### What did you expect to see?

The labels/descriptions matching the behavior (see above)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/tabindex`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/tabindex/index.md
* Last commit: https://github.com/mdn/content/commit/36001a269f4d7b2b3ac6de79e942a5f849bb87d8
* Document last modified: 2022-09-09T05:53:39.000Z

</details>

**Comment by Josh-Cena** [comment]
The fiddle no longer exists after https://github.com/mdn/content/pull/22882
