### ISSUE TITLE
Variable hoisting not explained properly in JS Guide

### ISSUE THREAD

**Issue by okagon** [mdn/content#21782]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_Types#variable_hoisting

### What specific section or headline is this issue about?

Variable hoisting

### What information was incorrect, unhelpful, or incomplete?

Its not clear weather hoisted variables can be initialized or are just permanently undefined since its says.
"after you use or refer to this variable it still returns undefined"

Also it says " let and const are hoisted but not initialized. Referencing the variable in the block before the variable declaration results in a because the variable is in a "temporal dead zone" from the start of the block until the declaration is processed.
So if its in "temporal dead zone" and totally same as not declared its still Hoisted?
?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_Types#variable_hoisting

### What did you expect to see?

Idk

**Comment by bsmth** [comment]
Hi @okagon, thanks for raising the issue. We have another issue to improve the Glossary for this already: https://github.com/mdn/content/issues/21546

I think the related content you have linked (under JavaScript -> Guide) should also be included with the proposed changes.
