### ISSUE TITLE
await

### ISSUE THREAD

**Issue by Worldwidebrine** [mdn/content#21814]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

> The expression is resolved in the same way as Promise.resolve(), which means thenable objects are supported, and if expression is not a promise, it's implicitly wrapped in a Promise and then resolved.

### What did you expect to see?

How `await` treats a value not thenable is `Promise.resolve(non_thenable_value)` too.

> implicitly wrapped in a Promise and then resolved.

This is exactly what `Promise.resolve()` does.

The behavior is the same.
But the description sounds like non-thenable values are handled differently.

Shouldn't the wrap behavior be described as `await`'s behavior, regardless of thenable?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/await`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/await/index.md
* Last commit: https://github.com/mdn/content/commit/1fdf2cae1c22f4672546b7c7a0ecc2247dc200ed
* Document last modified: 2022-10-11T06:45:07.000Z

</details>

**Comment by Josh-Cena** [comment]
Could you suggest a better wording? Because "The behavior is the same" is exactly what I meant. The sentence should be parsed like this:

> [The expression is resolved in the same way as Promise.resolve(), [which means [thenable objects are supported], and [if expression is not a promise, it's implicitly wrapped in a Promise and then resolved]]].

But maybe it's ambiguous with

> [The expression is resolved in the same way as Promise.resolve(), which means thenable objects are supported], and [if expression is not a promise, it's implicitly wrapped in a Promise and then resolved].

? Only the former interpretation looks natural to me, though.

**Comment by Worldwidebrine** [comment]
English is not my first language. I don't think my suggestion is likely to be considerable.

Even in your first interpretation, doesn't `Promise.resolve()` also wrap thenable that is not Promise?
Both non-promise thenable and non-thenable would be wrapped in a Promise, right?

**Comment by Worldwidebrine** [comment]
I think that `thenable objects are supported` can be removed.
I could be wrong but `thenable objects` are also `expression is not a promise`.

**Comment by Worldwidebrine** [comment]
> The expression is resolved in the same way as Promise.resolve(), which means if expression is a thenable object, it's implicitly wrapped in a Promise and then resolved, and a non-thenable value is wrapped in a Promise resolved with the value.

English is not my first language.

**Comment by Worldwidebrine** [comment]
Here's another one
> The await expression causes async function execution to pause until a promise is settled (that is, fulfilled or rejected), and to resume execution of the async function after fulfillment.

Actually: `await` always pauses.
Even if the value is an resolved/rejected thenable object or even non-thenable, the execution will still pause and a microtask will queue.
```javascript
let test = true;
(async () => {
  while (test) {
    await null;
    console.log("running");
  }
  console.log("end")
})();
(async () => {
  for (let i = 0; i < 10; i++) {
    await null;
  }
  test = false;
})();
```
This behavior is inherited from `then`
```javascript
Promise.resolve().then(() => { console.log("test"); });
console.log("sync");
```

**Comment by Josh-Cena** [comment]
Promises aren't special in any way. The only two cases of resolution are: (a) if it's thenable, then its `then` method is called; (b) if it's not thenable, then it's wrapped in a fulfilling promise and resolved. I'm going to do some minor reword, but this is tricky to get right.

**Comment by Worldwidebrine** [comment]
Promises are special
```js
const p = new Promise(() => {});
console.log(Object.is(Promise.resolve(p), p)); // true
```

**Comment by Josh-Cena** [comment]
For `Promise.resolve`, yes; for `await`, it's barely observable (maybe it is, because there's one less tick for promise unwrapping). In any case I would try to rewrite it

**Comment by Worldwidebrine** [comment]
> In the meantime, the caller of the async function resumes execution.

I don't know how to describe but, if the `await` is not the first executed `await`, `the caller` will be a microtask.
But the microtask is `caller of next()` not `caller of async function`.
`await` finishes the current microtask.
Why wouldn't you mention microtask in promise and async? Isn't Promise based on microtask?

**Comment by Worldwidebrine** [comment]
```js
let i = 0;
queueMicrotask(function test() {
  i++;
  console.log("microtask", i);
  if (i < 6) {
    queueMicrotask(test);
  }
});
(async () => {
  console.log("before await");
  await null;
  console.log("resume 1");
  await null;
  console.log("resume 2");
  for (let i = 3; i < 6; i++) {
    await null;
    console.log("resume", i);
  }
})();
queueMicrotask(() => {
  console.log("queueMicrotask after calling async function");
})
console.log("sync");
```
