### ISSUE TITLE
table with thead but no tbody is valid or invalid?

### ISSUE THREAD

**Issue by BartolomeSintes** [mdn/content#21818]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody

### What specific section or headline is this issue about?

"Tag omission" and "Usage notes"

### What information was incorrect, unhelpful, or incomplete?

According to the W3C validator a table with thead element and no tbody element is valid.
```html
  <table>
    <thead>
      <tr><th>Country</th></tr>
    </thead>
    <tr><td>Spain</td></tr>
    <tr><td>France</td></tr>
  </table>
```
Validator screenshot:
![w3c-validator-bug-2022-10-21](https://user-images.githubusercontent.com/1515413/197281381-759fc486-a0f6-408c-9eab-4f81fb3ade68.png)
But MDN states in this page that:
- Tag omission. The tbody element is not a required child element for a parent table element to graphically render. However, it must be present, if the parent table element has a thead, a tfoot or another tbody element as a child.
- Usage notes.  If the table includes a thead block (to semantically identify header rows), the tbody block must come after it.

I have opened [an issue in the W3C Validator GitHub](https://github.com/validator/validator/issues/1445) asking them if it is a bug of the validator. I have been told that W3C Validator is right and MDN is wrong, so I am opening this issue.
Can you check it?
Thanking you in advance,
Bartolome Sintes

### What did you expect to see?

If the W3C Validator is right and the tbody tag is not needed when there is only one tbody element in a table, I would say that the page has to be corrected accordingly, removing the two sentences I have copied from the MDN page.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/tbody`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/tbody/index.md
* Last commit: https://github.com/mdn/content/commit/a30a908b5a6c05f739e74a8af4505172ce5431c4
* Document last modified: 2022-10-05T06:26:24.000Z

</details>

**Comment by BartolomeSintes** [comment]
This issue has been closed, but I would say that there are editing errors in the html source of the [tbody page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody) that still need to be corrected.
- In the first table of the page the text of the "Tag omission" row is shown before the table, not inside the td, and some tag names are not shown, as you can see in this capture :
![github-mdn-issue-21818-1 ppngmoodle-general-lmsgi](https://user-images.githubusercontent.com/1515413/199103745-9ceb6848-fb56-49d6-8204-2958022776bf.png)

By the way, in the Usage Notes section, the first item states that "If the table includes a thead block (to semantically identify a row of column headers), the tbody block must come after it." A second item regarding tfoot could be added (tfoot must come after the tbody block).

**Comment by wbamberg** [comment]
Ugh, sorry @BartolomeSintes , I should have checked the rendered page more closely. The problem is that this markup is in an HTML table, so Markdown syntax isn't going to work. I'll make a fix now.

**Comment by wbamberg** [comment]
-> https://github.com/mdn/content/pull/21970
