### ISSUE TITLE
Issue with "KeyboardEvent.initKeyboardEvent()": Parameters incorrect

### ISSUE THREAD

**Issue by mykohsu** [mdn/content#2183]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/initKeyboardEvent

#### What information was incorrect, unhelpful, or incomplete?

Parameters for deprecated initKeyboardEvent is incorrect.

This was changed when the method was [removed](https://bugzilla.mozilla.org/show_bug.cgi?id=999645) and then [reintroduced](https://bugzilla.mozilla.org/show_bug.cgi?id=1387828).

#### Specific section or headline?
Parameters

#### What did you expect to see?
Instead of charArg/keyAarg, a single keyArg.
Instead of modifiersListArg, 4 separate parameters for CTRL, ALT, SHIFT, META.
No repeatArg.

See https://www.w3.org/TR/uievents/#idl-interface-KeyboardEvent-initializers

#### Did you test this? If so, how?
Tried in browser, double checked source code.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/keyboardevent/initkeyboardevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/initKeyboardEvent
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/keyboardevent/initkeyboardevent/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Modify the code example to include the correct parameters

**Comment by CreaTorAlexander** [comment]
It should also be written with the new syntax, right?

like
```
kbdEvent.initKeyboardEvent(typeArg)
kbdEvent.initKeyboardEvent(typeArg, optional1)
.....
kbdEvent.initKeyboardEvent(typeArg, optional1, ...., optionalN)
```

**Comment by mykohsu** [comment]
I sent a PR but there are concerns about removing existing parameters that are completely uncompatible.

**Comment by CreaTorAlexander** [comment]
Oh okay, haven't seen it actually.
I thought this issue is about updating the parameters in the example?
