### ISSUE TITLE
Link to site-specific add-on instructions 404

### ISSUE THREAD

**Issue by dochin** [mdn/content#21832]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API

### What specific section or headline is this issue about?

WebMIDI Api

### What information was incorrect, unhelpful, or incomplete?

The link to instructions for setting up a site permission add-on returns 404 on extensionworkshop.com.  The text of the link is “[Instructions on how to set up a site permission add-on can be found here](https://extensionworkshop.com/documentation/publish/site-permission-add-on/).”

### What did you expect to see?

A link to instructions for this step that is required to implement the api

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_midi_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_midi_api/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by MrBrain295** [comment]
I did some looking around and the link is still at the top of Google search results but I can’t find any reference of a new URL anywhere.

**Comment by hamishwillee** [comment]
Link was added in #14432. I've added a request for information at https://bugzilla.mozilla.org/show_bug.cgi?id=836897#c135

**Comment by hamishwillee** [comment]
This is no longer required - see #21951 (Closting this; I will proceed the work there).
