### ISSUE TITLE
Definition/examples of absolute/relative URLs do not match the linked specs

### ISSUE THREAD

**Issue by pine3ree** [mdn/content#21836]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#absolute_urls_vs_relative_urls

### What information was incorrect, unhelpful, or incomplete?

The definition of absolute URL string in the specs: https://url.spec.whatwg.org/#absolute-url-string, only includes full URLs starting with a scheme.

The definition of relative URL string in the specs: https://url.spec.whatwg.org/#relative-url-string includes
  1. scheme-relative-URL or  scheme-relative-special-URL string starting with "//",
  2. path-absolute-URL string starting with "/"
  3. path-relative-scheme-less-URL string

In the [Examples of absolute URLs](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#examples_of_absolute_urls), urls like the ones described in points 1 and 2 above are considered "absolute URLs".

Same here:
https://www.rfc-editor.org/rfc/rfc3986#section-4.3 absolute-URI (even if the definition excludes a fragment)
https://www.rfc-editor.org/rfc/rfc3986#section-4.2 relative-reference

### What did you expect to see?

I expect examples matching the specs

absolute-URL: https://developer.mozilla.org/en-US/docs/Learn
relative-URL:
//developer.mozilla.org/en-US/docs/Learn (network-path reference)

### Do you have any supporting links, references, or citations?

https://url.spec.whatwg.org/#absolute-url-string
https://url.spec.whatwg.org/#relative-url-string
https://www.rfc-editor.org/rfc/rfc3986#section-4.3 (for absolute-URI)
https://www.rfc-editor.org/rfc/rfc3986#section-4.2 (for relative-reference)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/common_questions/what_is_a_url`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/what_is_a_url/index.md
* Last commit: https://github.com/mdn/content/commit/1559cc772669ad51d3fc4ad4d42ff938a6a40172
* Document last modified: 2022-10-09T05:30:32.000Z

</details>

**Comment by kostasx** [comment]
Do you think a restructuring of the examples section that looks like this would work @pine3ree @sideshowbarker? 

https://github.com/kostasx/MDN-content/blob/main/files/en-us/learn/common_questions/web_mechanics/what_is_a_url/index.md#examples-of-absolute-urls

The 2nd and 3rd example have been moved from the Absolute URLs section to the Relative URLs.

**Comment by pine3ree** [comment]
Hello @kostasx ,

I would also add specific terminology (with examples) for relative-references: https://datatracker.ietf.org/doc/html/rfc3986#section-4.2

```
- network-path reference:  "//datatracker.ietf.org/doc/html/rfc3986"
- absolute-path reference: "/doc/html/rfc3986"
- relative-path reference: "doc/html/rfc3986"
```
The confusion arises when, like in the early days of web development, we call (and we used to) `absolute-url` what is really an `absolute-path` relative-reference.

kind regards
