### ISSUE TITLE
Should Efficient animation for web games be kept

### ISSUE THREAD

**Issue by MrBrain295** [mdn/content#21833]
### MDN URL

https://developer.mozilla.org/en-US/docs/Games/Techniques/Efficient_animation_for_web_games

### What specific section or headline is this issue about?

The entire page

### What information was incorrect, unhelpful, or incomplete?

This page is from a blog and was moved to MDN. That begs the question why host this in MDN if it can be found elsewhere.

### What did you expect to see?

A page made on/for MDN.

### Do you have any supporting links, references, or citations?

https://www.chrislord.net/2013/11/29/efficient-animation-for-games-on-the-mobile-web/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/games/techniques/efficient_animation_for_web_games`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Techniques/Efficient_animation_for_web_games
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/techniques/efficient_animation_for_web_games/index.md
* Last commit: https://github.com/mdn/content/commit/ad895c2db45bb24f41b21b0cda2b653613908b37
* Document last modified: 2022-09-11T17:53:56.000Z

</details>

**Comment by wbamberg** [comment]
I've asked around and have found at least one person as well as me who thinks we should remove it, and none who want to keep it. So I think it is worth filing a PR to remove it.

**Comment by MrBrain295** [comment]
I will gladly work on this.
