### ISSUE TITLE
await always causes execution to pause

### ISSUE THREAD

**Issue by Worldwidebrine** [mdn/content#21842]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

> The await expression causes async function execution to pause until a promise is settled (that is, fulfilled or rejected), and to resume execution of the async function after fulfillment.

### What did you expect to see?

Actually `await` always causes the function execution to pause.
Even if the value is a resolved promise or even non-thenable, the execution will still pause and a microtask will queue.
```javascript
let test = true;
(async () => {
  while (test) {
    await null;
    console.log("running");
  }
  console.log("end")
})();
(async () => {
  for (let i = 0; i < 10; i++) {
    await null;
  }
  test = false;
})();
```

### Do you have anything more you want to share?

The behavior is inherited from `then`
```javascript
const resolved = Promise.resolve();
resolved.then(() => {
  console.log("promise has been resolved");
  console.log("before resolved.then()");
  resolved.then(() => {
    console.log("inside resolved.then()");
  });
  console.log("after resolved.then()");
});
```
This behavior should be mentioned in [Promise.prototype.then()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then), I think.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/await`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/await/index.md
* Last commit: https://github.com/mdn/content/commit/1fdf2cae1c22f4672546b7c7a0ecc2247dc200ed
* Document last modified: 2022-10-11T06:45:07.000Z

</details>

**Comment by sideshowbarker** [comment]
Do you have a suggestion for better wording?

**Comment by Worldwidebrine** [comment]
> The `await` expression causes async function execution to pause and to resume in a microtask. If the value of parameter has been settled (that is, fulfilled or rejected), it queues the microtask immediately, otherwise it waits. When resumed, the value of the `await` expression is that of the fulfilled promise.

English is not my first language.
I think my suggestion is not good enough.

**Comment by Worldwidebrine** [comment]
Is "instantly" better?
What is the difference between "immediately" and "instantly"?

**Comment by sideshowbarker** [comment]
> Is "instantly" better?

“immediately” is better, I think

> What is the difference between "immediately" and "instantly"?

In the context of technical specifications, “immediately” is the normal term to use; “instantly” is almost never used.

**Comment by Worldwidebrine** [comment]
The `await null;` code example is a bad practice, but that is the only code I find can reproduce the behavior.

I think that the code should not be mentioned.
But I still think the behavior needs to be mentioned.

Actually, it's bad because the browser finishes all microtasks in one frame.
Is this behavior part of ES standard?

Afaik, in Minecraft's scripting engine, the microtask processing would pause after a microtask is finished if a 6ms timeout is reached, then resume in next frame, which makes `await non_thenable;` useful.
```js
for (let i = 9999999; i > 0; i--) {
  await null;
  // do something
  await null;
  // do something
}
```
In this code, the loop would be executed in multiple frames due to the 6ms timeout, but this behavior is only in Minecraft.

**Comment by Worldwidebrine** [comment]
> In the meantime, the caller of the async function resumes execution.

I don't know how to describe but, if the `await` is not the first executed `await`, `the caller` will be a microtask.
But the microtask is `caller of next()` not `caller of async function`.
