### ISSUE TITLE
Creating explicit grid instead of implicit grid

### ISSUE THREAD

**Issue by pimskie** [mdn/content#21847]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Layout_using_Named_Grid_Lines

### What specific section or headline is this issue about?

Implicit Grid lines from named areas

### What information was incorrect, unhelpful, or incomplete?

The paragraph title: "Implicit Grid lines from named areas"

### What did you expect to see?

"Explicit Grid lines from named areas"

### Do you have any supporting links, references, or citations?

We're creating an explicit grid by defining the `grid-template-areas` and placing everything (`ft`, `hd`, `sd`, `main`) inside the grid. 
There are no elements placed outside the grid.

https://gridbyexample.com/examples/example10/
https://css-tricks.com/difference-explicit-implicit-grids/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_grid_layout/layout_using_named_grid_lines`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Layout_using_Named_Grid_Lines
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_grid_layout/layout_using_named_grid_lines/index.md
* Last commit: https://github.com/mdn/content/commit/71c4bc0b6329ec40ddbefd8d3124547e91cfa612
* Document last modified: 2022-09-28T03:40:57.000Z

</details>

**Comment by estelle** [comment]
See https://github.com/mdn/content/pull/22615#pullrequestreview-1198630556
