### ISSUE TITLE
Information missing for "hidden" <input>s

### ISSUE THREAD

**Issue by rxbracho** [mdn/content#21857]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

### What specific section or headline is this issue about?

Not sure where it would go

### What information was incorrect, unhelpful, or incomplete?

Incomplete, according to the reference page for the `<input>` element.

### What did you expect to see?

When talking about the attributes of `<input>`, in particular `autocomplete`, it includes a link to a different page where we will be told how it behaves differently for `type="hidden"` but there is no specific information in that page.  I am (still) left wondering how does the concept of auto completion meshes with a hidden input element.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/autocomplete`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/autocomplete/index.md
* Last commit: https://github.com/mdn/content/commit/bb7e3c7303746408072ddf4cc646e28d7e14214a
* Document last modified: 2022-09-14T06:47:31.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

I believe this issue is referring to the bit under https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete where it says:

> See [The HTML autocomplete attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) for additional information, including information on password security and how autocomplete is slightly different for hidden than for other input types.

But then https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete doesn't say anything about `type=hidden`.

@rxbracho , is that a correct understanding of this issue? 

I think the bit it wants to say is mentioned in the spec here: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete :

> On an input element whose type attribute is in the Hidden state, the autocomplete attribute wears the autofill anchor mantle. In all other cases, it wears the autofill expectation mantle.

...so I guess the work here is to explain this difference, in the autocomplete page at https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete, in an accessible way.

**Comment by rxbracho** [comment]
You understood the issue precisely, bravo!Thank you for quoting the official spec; you are correct in that it needs an explanation. I didn't understand it.Thanks!Rafael Sent from my Galaxy
-------- Original message --------From: wbamberg ***@***.***> Date: 10/27/22  13:17  (GMT-06:00) To: mdn/content ***@***.***> Cc: Rafael Bracho ***@***.***>, Mention ***@***.***> Subject: Re: [mdn/content] Information missing for "hidden" s (Issue
  #21857) 
Thanks for filing!
I believe this issue is referring to the bit under https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete where it says:

See The HTML autocomplete attribute for additional information, including information on password security and how autocomplete is slightly different for hidden than for other input types.

But then https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete doesn't say anything about type=hidden.
@rxbracho , is that a correct understanding of this issue?
I think the bit it wants to say is mentioned in the spec here: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete :

On an input element whose type attribute is in the Hidden state, the autocomplete attribute wears the autofill anchor mantle. In all other cases, it wears the autofill expectation mantle.

...so I guess the work here is to explain this difference, in the autocomplete page at https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete, in an accessible way.

**Comment by Josh-Cena** [comment]
I believe it's fixed by https://github.com/mdn/content/pull/32789:

> If including the `autocomplete` attribute on hidden input elements (`<input type="hidden">`), its value must be an ordered list of space-separated tokens; the `on` and `off` keywords are not allowed.

(This is what "wears the autofill anchor mantle" means.)

**Comment by rxbracho** [comment]
Thank you for following up.
