### ISSUE TITLE
Issue with "URLSearchParams.get()": should warn that "+" as used in base64 parameters returns " " 

### ISSUE THREAD

**Issue by keithxemi** [mdn/content#2186]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get

#### What information was incorrect, unhelpful, or incomplete?
Common character in URL parameter is changed.

#### Specific section or headline?
Example should include this case or similar https://example.com/?name=Jonathan&bintoa=E+AXQB+A&age=18
let bin = params.get("bintoa"); // is the string "E AXQB A" notice the surprise "+" becomes " " U+0020 
#### What did you expect to see?
warning of surprising result

#### Did you test this? If so, how?
as shown above

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/urlsearchparams/get`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/urlsearchparams/get/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Hm, [both are valid encodings for space but in different contexts](https://stackoverflow.com/a/2678602).

**Comment by keithxemi** [comment]
To follow up, https://developers.google.com/web/updates/2016/01/urlsearchparams has this example parameter q=search+string&version=1&person=Eric clearly showing the + replacement. 

The spec has this comment "This can be especially surprising when using searchParams to operate on a URL’s query." highlighted in a Note https://url.spec.whatwg.org/#dom-urlsearchparams-get 

This MDN page https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#browser_compatibility does include &topic=More+webdev as an example for searchParams.set but does not show the get action and is easily missed.

 Base64 is very commonly used for binary in a URL parameter. The example I proposed does not throw an error as shown here
 btoa(atob("E AXQB A")) // "EAXQBA=="
btoa(atob("E+AXQB+A")) // "E+AXQB+A"
But of course the binary values are very different and might cause an infrequent error that could be difficult to find. The MDN page should be improved by including examples of these cases.

**Comment by Ryuno-Ki** [comment]
@chrisdavidmills Would those examples go into interactive repo or be plain-text in MDN?

**Comment by chrisdavidmills** [comment]
@Ryuno-Ki These would go into the document directly, as static or live examples. We don't currently have the ability to add interactive examples to WebAPI pages.

**Comment by Ryuno-Ki** [comment]
Nice!

@keithxemi Would you be willing to cook some examples and add them to the docs?

https://github.com/mdn/content/blob/89b781abf1093d108f0fba926286c5b9eac59923/files/en-us/web/api/urlsearchparams/get/index.html#L34-L47

**Comment by keithxemi** [comment]
I'll give it a try. Not familiar with the process but I will read up on it.

**Comment by Ryuno-Ki** [comment]
Great!

Let us know if something is unclear or you need help.

**Comment by keithxemi** [comment]
@Ryuno-Ki Did I do this correctly? I see my commit here but no response.

**Comment by CreaTorAlexander** [comment]
Now you have the commit in your forked repository. When you go inside this repo there should be something appear with the text *Compare and pull*. Click on it to create a pull request. Then your commit gets reviewed and probably merged :)

**Comment by CreaTorAlexander** [comment]
@keithxemi it looks like you have only commit your changes to your forked repository.
Now you have to submit a Pull Request. You can do this by going inside your forked repository and there should appear a button with the text *Compare and Pull*. Click on this button to submit you changes.

**Comment by Ryuno-Ki** [comment]
What Alexander says.
The button should show up on https://github.com/mdn/content/compare/main...keithxemi:keithxemi-patch-1
(Right now, I can see a PR against your fork. Instead, make sure to integrate against mdn/content :-) )

**Comment by Rumyra** [comment]
Just a note - PR for this is in https://github.com/mdn/content/pull/2449 but I think the example would be really good on the main URLSearchParams page as well, under the Gotchas heading

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#gotchas

Just holding off merging whilst that query is resolved 👍

**Comment by Rumyra** [comment]
Resolved https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#gotchas
