### ISSUE TITLE
Grouping operator has other uses

### ISSUE THREAD

**Issue by GarrettS** [mdn/content#21862]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Grouping

### What specific section or headline is this issue about?

The Grouping Operator

### What information was incorrect, unhelpful, or incomplete?

"The grouping operator ( ) controls the precedence of evaluation in expressions."

### What did you expect to see?

The Grouping Operator groups primary expressions. 

This can be useful for managing operator precedence, but that's not what it does.

It can also be used to avoid ASI pitfalls and to force tokens' evaluation as PrimaryExpressions.

```
(function a() {
    return 1;
}) () // <-- FE, not FD
```

It can be used to avoid ASI pitfalls:
```
function b() {
    return 
        "LongStringWithManyCharacters"
     + " even more chars";
}

```
— and it can be accidentally interpreted as Arguments when following an Expression, to interpret a CallExpression.

### Do you have any supporting links, references, or citations?

http://jibbering.com/faq/notes/code-guidelines/asi.html

### Do you have anything more you want to share?

It seems like MDN quality has decreased. I'm disappointed. I don't have endless time to volunteer for its betterment, however.

**Comment by Josh-Cena** [comment]
> It seems like MDN quality has decreased. I'm disappointed.

I don't understand where that sentiment comes from, since we've never _removed_ any information. Still, I think the suggestion makes sense.

**Comment by GarrettS** [comment]
Well, parseInt is gone, for example. Ditto for eval, encodeURIComponent, etc.

https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Functions/parseInt

Function `parseInt` changed behavior, too. It originally attempted to parse strings with leading 0's as octal.

**Comment by Josh-Cena** [comment]
What you are looking for are at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent; you may use the search.

We rigorously document implementation reality—we don't control how they should behave. `parseInt` doesn't automatically treat numbers as octal, so we document that it doesn't.
