### ISSUE TITLE
Remove mentions of moz APIs from drag&drop documentation

### ISSUE THREAD

**Issue by evilpie** [mdn/content#21878]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Multiple_items

### What information was incorrect, unhelpful, or incomplete?

At some point all the moz APIs like `mozSetDatAt` were merely Firefox only, but at this point they have been completely removed. (Or rather they are inaccessible to web content)

This also affects https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types.

### What did you expect to see?

It might be best to just remove that page completely.

### Do you have any supporting links, references, or citations?

https://bugzilla.mozilla.org/show_bug.cgi?id=1666287

**Comment by EverLearning2022** [comment]
Hi. I would like to help with this documentation task. I am new to GitHub. Can you confirm that under HTML_Drag_and_Drop_API you want to remove these two doc pages: 

- Multiple_items
- Recommended_drag_types

There are some sections that are more generic so I wasn't sure whether you wanted to keep any of the content.
