### ISSUE TITLE
elegantly  steeling my data !!!!!!

### ISSUE THREAD

**Issue by dmantryingcode** [mdn/content#21887]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onInstalled

### What information was incorrect, unhelpful, or incomplete?

this git repository is cantered to me i have never  worked wit this guys they are connected to me please remove  first i caught there license on my accost now this if tatty do remove them self i will fill a police report  his name shane caraveo please  he is affecting my life  he dosent have talk about my nationality that's racist    dont know his problem  you can contact me (747)273 3367 

### What did you expect to see?

jh7u

### Do you have anything more you want to share?

ouhiuh

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/runtime/oninstalled`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onInstalled
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/runtime/oninstalled/index.md
* Last commit: https://github.com/mdn/content/commit/fae225dc7876dd22800d39dffff0d663ee7808aa
* Document last modified: 2022-09-13T05:04:34.000Z

</details>

**Comment by hamishwillee** [comment]
Please do not spam this repository.
