### ISSUE TITLE
wrong boolean value in doc

### ISSUE THREAD

**Issue by MarcPhilippeJoly** [mdn/content#21880]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check

### What specific section or headline is this issue about?

Exemples

### What information was incorrect, unhelpful, or incomplete?

This method is not supposed to always return true. 
From my tests with Chromium, it returns `false` when `NonExistingFont` doesn't exist.

### What did you expect to see?

If the font given in the font specification does not exist, this function returns `false`:

```
console.log(document.fonts.check("12px NonExistingFont"));
// false
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/fontfaceset/check`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fontfaceset/check/index.md
* Last commit: https://github.com/mdn/content/commit/b9ff6d9960e91ff4ba27d0d675c85063b57a4198
* Document last modified: 2022-10-07T21:16:19.000Z

</details>

**Comment by Josh-Cena** [comment]
Ah, there's already https://github.com/mdn/browser-compat-data/pull/17954. Closing this, then.

**Comment by MarcPhilippeJoly** [comment]
Maybe what is actually needed in the documentation is one single good example of what would be a case where `document.fonts.check` returns `false`. This could definitely help the readers guess what this method actually check for.
