### ISSUE TITLE
@font-face src descriptor: format() not sufficiently defined

### ISSUE THREAD

**Issue by estelle** [mdn/content#21895]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src

### What specific section or headline is this issue about?

format() function

### What information was incorrect, unhelpful, or incomplete?

very little information was provided, not even the potential values included in the spec.

### What did you expect to see?

Everything that is in the spec, explained

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/css-fonts-4/#font-face-src-parsing

There is much more information in the spec that is not on this page:

```
<url> [ format(<font-format>)]? [ tech( <font-tech>#)]? | local(<font-face-name>)
<font-format>= [<string> | collection | embedded-opentype | opentype
 | svg | truetype | woff | woff2 ]
<font-tech>= [<font-feature-tech> | <color-font-tech>
 | variations | palettes | incremental ]
<font-feature-tech>= [feature-opentype | feature-aat | feature-graphite]
<color-font-tech>= [color-COLRv0 | color-COLRv1 | color-SVG | color-sbix | color-CBDT ]
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@font-face/src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@font-face/src/index.md
* Last commit: https://github.com/mdn/content/commit/d7d81910b9dbca47c5ed0efba7f2d70912919ce5
* Document last modified: 2022-10-12T00:40:39.000Z

</details>

**Comment by hamishwillee** [comment]
True. When I looked at `tech()` in August #19833 this was not released in any browser (just behind pref). Normally we'd document anyway, but there was still a lot of discussion around the syntax. That might have settled now. 

This will get documented when Firefox ships with the preference removed unless someone else does it first.

**Comment by estelle** [comment]
Yes, I think it could be safely documented. I found the issue when i was working on another issue, and wanted to document that there is an issue. Would be great to have the actual issue - the format() -  documented / addressed
