### ISSUE TITLE
Issue with "tabs.create()": …

### ISSUE THREAD

**Issue by h-h-h-h** [mdn/content#219]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create

#### What information was incorrect, unhelpful, or incomplete?
The `type` property of the `createProperties` argument isn't documented. I only read of it [here](https://extensionworkshop.com/documentation/develop/onboard-upboard-offboard-users/#onboarding):

```js
        const url = browser.runtime.getURL("views/installed.html");
        await browser.tabs.create({ url });
        // or: await browser.windows.create({ url, type: "popup", height: 600, width: 600, });
```

Same goes for `width` and `height`.

#### Specific section or headline?
"Parameters"

#### What did you expect to see?
Documenation of the properties with possible values like `"popup"`.

#### Did you test this? If so, how?
I tested the commented-out code above in Firefox and it creates a new window without tab bar, address bar etc.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/tabs/create`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/add-ons/webextensions/api/tabs/create/index.html
* Report started: 2020-12-15T07:03:16.600Z

</details>

**Comment by rpl** [comment]
@h-h-h-h `type`, `width` and `height` are not properties supported by browser.tabs.create, those are properties supported only by `browser.window.create` and already documented here:
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create
