### ISSUE TITLE
asmjs.org website

### ISSUE THREAD

**Issue by allan-bonadio** [mdn/content#21905]
### MDN URL

https://developer.mozilla.org/en-US/docs/Games/Tools/asm.js

### What specific section or headline is this issue about?

Not on mozilla.org - on asmjs.org

### What information was incorrect, unhelpful, or incomplete?

Sorry, didn't know where to file this.

The asmjs.org website is still up, pretending like asm.js is still current and encouraging people to do it:
    Status
    This specification is working towards a candidate draft for asm.js version 1. Mozilla's SpiderMonkey JavaScript 
    engine provides an optimizing implementation of this draft.

Then, in the Changelog, the last entry is "18 August 2014".

### What did you expect to see?

Some sort of statement about how asm.js is all deprecated and you should use WebAssembly instead.  Then, some links to WebAssembly specs, either w3c or Mozilla.  Maybe also to emscripten, https://emscripten.org , as that's probably the best way to put WebAssembly to use.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Games/Tools/asm.js
http://asmjs.org

from asmjs.org:
Editors:
David Herman, Mozilla, <dherman@mozilla.com>
Luke Wagner, Mozilla, <luke@mozilla.com>
Alon Zakai, Mozilla, <azakai@mozilla.com>

### Do you have anything more you want to share?

Sorry, didn't know where to file this, but all the editors are from Mozilla.  But the last update was 8 years ago so who knows if they're still at mozilla.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/games/tools/asm.js`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tools/asm.js
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/tools/asm.js/index.md
* Last commit: https://github.com/mdn/content/commit/e4783c03e39807e0060a2f4df3bf3962d25d8388
* Document last modified: 2022-08-26T07:25:46.000Z

</details>

**Comment by sideshowbarker** [comment]
@lukewagner and @kripken may be able to help here

**Comment by lukewagner** [comment]
I think @dherman owns this domain and server and content?  Agreed that a small banner explaining that the site is mostly kept around for historical purposes and linking to WebAssembly would be nice.

**Comment by bsmth** [comment]
I've made a minor update to the deprecation notice on the page in https://github.com/mdn/content/pull/23559

@dherman @lukewagner is there any progress on adding a banner on the [asm.js ](http://asmjs.org/) side?

**Comment by bsmth** [comment]
I'm going to close this one as there's no other action I can take on this repo. It would be nice if changes could be added on asm.js, but this is an external dependency.

__Related PRs:__
- [x] https://github.com/mdn/content/pull/23559
