### ISSUE TITLE
Issue with "Animation performance and frame rate": steps of a canvas animation missing

### ISSUE THREAD

**Issue by anastasiavyalt** [mdn/content#2190]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate

#### What information was incorrect, unhelpful, or incomplete?
In [the rendering waterfall](https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate#the_rendering_waterfall) section after the following sentence:
> When a canvas is animating a drawing, the canvas animation can be described as a waterfall consisting of the following steps: 

There is no image or text specifying the steps.

#### Specific section or headline?
The second paragraph of [the rendering waterfall section](https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate#the_rendering_waterfall) 

#### What did you expect to see?
An image or a list of steps.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/performance/animation_performance_and_frame_rate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/performance/animation_performance_and_frame_rate/index.html
* Last commit: https://github.com/mdn/content/commit/7685c5769199a4528bbff7777581abfa60f58f65
* Document last modified: 2020-12-17T10:02:33.000Z

</details>

**Comment by chrisdavidmills** [comment]
I'm a little confused here. After the sentence you've quoted, I can see the following diagram:

![css-rendering-waterfall](https://user-images.githubusercontent.com/47647/107343835-aa161500-6ab9-11eb-8547-350b6051831a.png)

Do you not see this?

**Comment by anastasiavyalt** [comment]
This diagram is describing the browser's rendering process, I meant the next paragraph which talks about canvas.
![image](https://user-images.githubusercontent.com/31649464/107356866-ef5f3480-6b03-11eb-884a-aeabe4767247.png)

**Comment by chrisdavidmills** [comment]
@anastasiavyalt ah, ok, thanks for the clarification. Yup, that's definitely a missing diagram, and we'll have to find someone to create it.

**Comment by himanshugarg** [comment]
Is "The process a browser uses to paint updated changes to a canvas" described somewhere in mdn docs? So I could use that to draw the missing diagram.

**Comment by bsmth** [comment]
Thanks for reporting this one. The original issue has been fixed in https://github.com/mdn/content/commit/eb0547ef60ad8aeed9be09df3d5fcc0fa77e3bcf so I'm going to close this one for now.

Thank you 🙌🏻
