### ISSUE TITLE
Image link is broken on this page

### ISSUE THREAD

**Issue by Haiz14** [mdn/content#21933]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/A_cool_looking_box

### What specific section or headline is this issue about?

image

### What information was incorrect, unhelpful, or incomplete?

The image link is broken and is showing alt text
```
text
A big red box with rounded corners. White text with drop shadow reads 'this is a cool box'.
```

### What did you expect to see?

The image so that I can compare my result with the expected result.

### Do you have any supporting links, references, or citations?

here's the Screen shot of broken image
____
![Screenshot_2022-10-29-15-22-02-55_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/68465021/198825153-d675d239-8723-4d35-9fa5-40d31fe79dae.jpg)
____

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/a_cool_looking_box`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/A_cool_looking_box
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/a_cool_looking_box/index.md
* Last commit: https://github.com/mdn/content/commit/4f6ba2f5a1615fe155292cac416c7ab6b9d711ec
* Document last modified: 2022-09-11T17:33:19.000Z

</details>

**Comment by Josh-Cena** [comment]
The image works for me:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/55398995/198851336-62b87d62-3813-4cd4-8dc7-23869ee78a85.png">

It's possible that you have a bad internet connection or there was a network glitch. Refreshing should help.
