### ISSUE TITLE
Issue with "SVG as an Image": Hyperlink to HTML5 specification is broken

### ISSUE THREAD

**Issue by tomari** [mdn/content#2194]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image

#### What information was incorrect, unhelpful, or incomplete?

The hyperlink that says `HTML5 - The definition of 'SVG within <img> element' in that specification.` is broken.
The broken link destination is `https://www.w3.org/TR/html52/embedded-content-0.html#the-img-element` .

#### Specific section or headline?

The first external link in the Specifications section is broken.

#### What did you expect to see?

It appears that `https://www.w3.org/TR/html5/embedded-content-0.html#the-img-element` works.

#### Did you test this? If so, how?

I tried following the link using Firefox 86.0b7 (Windows 10, 64-bit) on 9 Feb 2021, 6:26:00 UTC.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/svg_as_an_image`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/svg/svg_as_an_image/index.html
* Last commit: https://github.com/mdn/content/commit/70e23d6fdee9226b63cefe7d20f3842effc4bdfd
* Document last modified: 2020-12-28T11:28:23.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Thanks for catching this!

As soon as I find out how to untangle the macro in

https://github.com/mdn/content/blob/de994daa19735be7153638b2987d54bb9059e7cd/files/en-us/web/svg/svg_as_an_image/index.html#L53

I can fix the link. @peterbe Would that be a change in Yari? Or an opportunity to replace the macro with the generated HTML?

**Comment by chrisdavidmills** [comment]
@Ryuno-Ki This doesn't need a Yari change. The base spec URL is still the same, but the slug has changed since we first wrote this page.

Looking at the HTML 5.2 spec, the `<img>` element definition is now at https://www.w3.org/TR/html52/semantics-embedded-content.html#the-img-element

So the first argument of the `SpecName` macro needs to be changed to `semantics-embedded-content.html#the-img-element`.

**Comment by Ryuno-Ki** [comment]
I opened #2197 with a fix.
