### ISSUE TITLE
Task is to recreate example, but examples are not provided

### ISSUE THREAD

**Issue by 7ivingstone** [mdn/content#21944]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics

### What specific section or headline is this issue about?

(HTML text basics skill test 1)Example results to recreate is not shown

### What information was incorrect, unhelpful, or incomplete?

The task for this particular assessment is to recreate examples, but the examples we are supposed to recreate are not shown.  It may be that I can't see it myself, but it seems to be a problem.

### What did you expect to see?

Expected to see examples to recreate but did not see any. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/test_your_skills_colon__html_text_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/test_your_skills_colon__html_text_basics/index.md
* Last commit: https://github.com/mdn/content/commit/4f6ba2f5a1615fe155292cac416c7ab6b9d711ec
* Document last modified: 2022-09-11T17:33:19.000Z

</details>

**Comment by kylewcode** [comment]
## Issues with providing code examples
Markdown lint does not allow inline html or more than one top-level header. This means that examples cannot be created using markdown or inline HTML. Therefore inserting an iframe would be more appropriate to the best of my knowledge. It appears that the template tag `EmbedGHLiveSample` which is already being used for the code tests, would work well. This requires a commit to another repo at [mdn/learning-area](https://github.com/mdn/learning-area). Once the files are committed, they can then be inserted into this document and resolve the issue.

**Comment by kylewcode** [comment]
@sideshowbarker I'm looking for guidance on next steps. In reference to my previous comment, my assumption is that a separate pull request would need to be made to mdn/learning-area.

**Comment by sideshowbarker** [comment]
> @sideshowbarker I'm looking for guidance on next steps. In reference to my previous comment, my assumption is that a separate pull request would need to be made to mdn/learning-area.

That sounds correct, yes
