### ISSUE TITLE
Issue with "Compiling from Rust to WebAssembly": (short summary here please)

### ISSUE THREAD

**Issue by HectorCastelli** [mdn/content#2195]
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

#### What information was incorrect, unhelpful, or incomplete?
One sentence is meaningless since the code examples do not have an @ sign.

> Note that you need to fill in your own username, after the @, in the dependencies section. 

#### Specific section or headline?

Under the "Using the package on the web" section

#### What did you expect to see?

Either this phrase removed or the code block before it containing an @ sign.

#### Did you test this? If so, how?

No, I have not tried following the tutorial.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/rust_to_wasm`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/webassembly/rust_to_wasm/index.html
* Last commit: https://github.com/mdn/content/commit/820f2a3093ec66b0896165315dd182911fa30aa3
* Document last modified: 2021-01-18T10:03:02.000Z

</details>

**Comment by CreaTorAlexander** [comment]
Maybe it is correlate to the example *Compiling our code to webassembly*

Compiling our code to WebAssembly
To compile our code correctly, we first need to configure it with Cargo.toml. Open this file, and change its contents to look like this:

```
[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/yourgithubusername/hello-wasm"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
```

But then the note should be below this exaple.

**Comment by HectorCastelli** [comment]
@CreaTorAlexander I find that hard to believe.

As far as I understand it, the Cargo dependencies would not have to be named with a username (requiring a @) for the tutorial to work. The NPM dependencies should follow the name of the package from Cargo, so `hello-wasm`, without an @ sign.

I think it makes more sense to remove the sentence after all.

**Comment by CreaTorAlexander** [comment]
@HectorCastelli Okay, I also realized it would not make so much sense. Then the note would be missleading because it says after the @ sign and in the example it would be before the @sign
