### ISSUE TITLE
“Responsive navigation patterns” article needs more examples

### ISSUE THREAD

**Issue by freeduck** [mdn/content#21950]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Responsive/Responsive_navigation_patterns

### What specific section or headline is this issue about?

Pattern 1: Top toggle menu, Pattern 2: Expandable bottom menu and Pattern 3: Left hidden menu

### What information was incorrect, unhelpful, or incomplete?

Incomplete

### What did you expect to see?

Examples of how to implement the different patterns

### Do you have any supporting links, references, or citations?

Something like these:
https://dev.to/ljcdev/hamburger-css-no-js-2dfa
https://codepen.io/erikterwan/pres/EVzeRP

### Do you have anything more you want to share?

Otherwise happy with MDN

Kind regards 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/progressive_web_apps/responsive/responsive_navigation_patterns`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Responsive/Responsive_navigation_patterns
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/responsive/responsive_navigation_patterns/index.md
* Last commit: https://github.com/mdn/content/commit/e14e4830bcd43de164623aaf787fbd695be31d91
* Document last modified: 2022-10-06T14:19:29.000Z

</details>

**Comment by Josh-Cena** [comment]
This doc is removed in https://github.com/mdn/content/pull/27573
