### ISSUE TITLE
Array.fill optional parameters

### ISSUE THREAD

**Issue by AdamXA** [mdn/content#21961]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

`value` parameter is marked as `required` vs `optional`.

### What did you expect to see?

Should this be marked `optional` as it can be called like this:

`[1, 2, 3].fill() // returns [undefined, undefined, undefined]`

e.g. can be useful to omit in the case were you use `.map`:

`new Array(4).fill().map((_, index) => index) // returns [0, 1, 2, 3]`

if this was required, have to pass in something unnecessarily (like I do with TypeScript 😞 ):

`new Array(4).fill(undefined).map((_, index) => index) // returns [0, 1, 2, 3]`

Not sure what cases things are marked as `required` vs `optional` so happy to be wrong about this :smile

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/fill`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/fill/index.md
* Last commit: https://github.com/mdn/content/commit/eff56eb74d327a74032f52418ab15e202f019f9a
* Document last modified: 2022-10-07T21:08:23.000Z

</details>

**Comment by Josh-Cena** [comment]
Please see discussion at https://github.com/orgs/mdn/discussions/201

There aren't many cases where the language literally forbids omission of a parameter. If it conflates omission with `undefined`, MDN tries to indicate optionalness through semantics (i.e. what you likely want). In your case the parameter is definitely required—`fill(undefined)` is significantly more readable than `fill()` ("fill with undefined" versus fill with... what? Empty slots? Literally holes?), so we tell you it's required.
