### ISSUE TITLE
“Uncaught TypeError: props.todos.map is not a function“ when following the “Rendering with iteration” section in “Componentizing our React app”

### ISSUE THREAD

**Issue by digitalrep** [mdn/content#21972]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components#rendering_with_iteration

### What information was incorrect, unhelpful, or incomplete?

I don't know if it's incorrect but when I am following this tutorial, when I get to this bit, I get an error: Uncaught TypeError: props.todos.map is not a function.

### What did you expect to see?

I am trying to finish the tutorial but I can't due to this error. 

### Do you have any supporting links, references, or citations?

No

### Do you have anything more you want to share?

No

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
* Last commit: https://github.com/mdn/content/commit/4b9fefebc6d21e003c8f31b40d98136a7a4b5a95
* Document last modified: 2022-10-01T03:00:18.000Z

</details>

**Comment by Josh-Cena** [comment]
Closing, because we now use `props.todos?.map`. Still, this shouldn't happen after you've added the `todos` prop to the element.
