### ISSUE TITLE
http(s) scheme for WebSocket gives an error anyway

### ISSUE THREAD

**Issue by styhu** [mdn/content#21978]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

at least the WebSocket("https://not-example.com/") example is totally useless as the https scheme will raise an exception in the WebSocket interface, independently from the CSP mechanism, so not-example.com will not even be looked at

### What did you expect to see?

I expected to understand how can I *not* specify the WebSocket protocol for ws://example.com/ in the connect-src and still be able to connect using WebSocket.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket#exceptions

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/connect-src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/connect-src/index.md
* Last commit: https://github.com/mdn/content/commit/8e1f45b8c0a3671f6e3de43c0764ad610aa345dd
* Document last modified: 2022-09-14T09:06:12.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/25220. But see also https://github.com/mdn/content/issues/26731; soon enough, if not now, http will be allowed in WebSocket.
