### ISSUE TITLE
Typo: Description above example in “BackgroundFetchManager»getIds()” doc says mentions “get()” but should be “getIds()”

### ISSUE THREAD

**Issue by neko-kawaii-nyan** [mdn/content#21988]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/BackgroundFetchManager/getIds

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

In description about example code, document says that example code is using `get()`.
However, in the example code, getIds() is used insted of get().  

### What did you expect to see?

# before
use the ServiceWorkerRegistration.backgroundFetch property to access the BackgroundFetchManager object and call its **`get()`** method

# after
use the ServiceWorkerRegistration.backgroundFetch property to access the BackgroundFetchManager object and call its **`getIds()`** method

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened #22122 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
