### ISSUE TITLE
Issue with "Array.prototype.sort()": wrong logic of `compareFunction`

### ISSUE THREAD

**Issue by anantakrroy** [mdn/content#2198]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

#### What information was incorrect, unhelpful, or incomplete?
The logic of working for the `compareFunction` is incorrect

#### Specific section or headline?
The logic is present in the **Description** section.

#### What did you expect to see?
The `compareFunction` works like this:
- If the returned value is < 0 ,  leave a and b unchanged.
- If returned value > 0 , sort a to an index lower than b (i.e. a comes first).

The logic explained is exactly the opposite

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/sort`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/array/sort/index.html
* Last commit: https://github.com/mdn/content/commit/3b26d3bc849cd84ff37ae85b9a8292267726df0b
* Document last modified: 2021-02-08T17:40:47.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update it 👍

**Comment by Ryuno-Ki** [comment]
Take it away, @CreaTorAlexander!

**Comment by mohitdmak** [comment]
#2191

**Comment by CreaTorAlexander** [comment]
@anantakrroy I checked this article at w3schools about the compare function and I would say talking about the explicit elements would be easier to understand.

At the w3schools site sections *The Compare Function* https://www.w3schools.com/js/js_array_sort.asp
> function(a, b){return a - b}
> When the sort() function compares two values, it sends the values to the compare function, and sorts the values according to the returned (negative, zero, positive) value.
> 
> If the result is negative a is sorted before b.
> 
> If the result is positive b is sorted before a.
> 
> If the result is 0 no changes are done with the sort order of the two values.


In the mdn article US/docs/Web/JavaScript/Refereqnce/Global_Objects/Array/sort

> If compareFunction(a, b) returns less than 0, sort a to an index lower than b (i.e. a comes first).
> If compareFunction(a, b) returns 0, leave a and b unchanged with respect to each other, but sorted with respect to all different elements. Note: the ECMAScript standard only started guaranteeing this behavior in 2019, thus, older browsers may not respect this.
> If compareFunction(a, b) returns greater than 0, leave a and b unchanged.
> compareFunction(a, b) must always return the same value when given a specific pair of elements a and b as its two arguments. If inconsistent results are returned, then the sort order is undefined.


Besides that as you said > If compareFunction(a, b) returns greater than 0, leave a and b unchanged.
this is wrong I would not argue like *to an index lower than b (i.e. a comes first).* 
Instead I would write *a* comes before *b*.

**Comment by anantakrroy** [comment]
@CreaTorAlexander Yes, I find this statement more appropriate too
*a comes before b*. In fact, using a [visualizer](http://pythontutor.com/visualize.html#code=let%20list%20%3D%20%5B2,6,13,-10,18,9%5D%3B%0A%0Aconsole.log%28list.sort%28%28a,b%29%20%3D%3E%20a%20-%20b%29%29%3B&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=js&rawInputLstJSON=%5B%5D&textReferences=false) ,  also shows the elements being replaced **in place** . Hence, the language of using *index* is a bit confusing.

**Comment by CreaTorAlexander** [comment]
In my updated version as you can see in the PR above Fixes #2198 #2215

I wrote 
` returns greater than 0, sort b before a`

**Comment by anantakrroy** [comment]
@CreaTorAlexander Yes , I have seen that and it's good to be merged.
