### ISSUE TITLE
Outdated recommendations

### ISSUE THREAD

**Issue by estelle** [mdn/content#21991]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Guide/Mobile/Separate_sites

### What specific section or headline is this issue about?

The entire page

### What information was incorrect, unhelpful, or incomplete?

I don't think separate sites is ever recommended anymore. Should we kill the page?

### What did you expect to see?

updated information (the feature phone section: doesn't anyone target those anymore?)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/guide/mobile/separate_sites`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Mobile/Separate_sites
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/mobile/separate_sites/index.md
* Last commit: https://github.com/mdn/content/commit/f4f8e2f18ccf19a0bee59e1fe78753e276b98232
* Document last modified: 2022-09-09T07:06:10.000Z

</details>

**Comment by teoli2003** [comment]
Yes, we should redirect it to RWD.

**Comment by estelle** [comment]
Thank you!
