### ISSUE TITLE
Issue with "Object prototypes": (short summary here please)

### ISSUE THREAD

**Issue by areberuto** [mdn/content#2200]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes

#### What information was incorrect, unhelpful, or incomplete?

"Note: It's important to understand that there is a distinction between an object's prototype (available via Object.getPrototypeOf(obj), or via the deprecated __proto__ property) and the prototype property on constructor functions.

The former is the property on each instance, and the latter is the property on the constructor. That is, Object.getPrototypeOf(new Foobar()) refers to a different object than Foobar.prototype."

#### Specific section or headline?

"A prototype-based language?"

#### What did you expect to see?

That Object.getPrototypeOf(new Foobar()) is equal to Foobar.prototype.

#### Did you test this? If so, how?

Yes, I tested it with

`Object.getPrototypeOf(new Object()) == Object.prototype // true
`

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/objects/object_prototypes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/javascript/objects/object_prototypes/index.html
* Last commit: https://github.com/mdn/content/commit/09ceed5a32437f2a49745e7da589530bf3720f8f
* Document last modified: 2021-01-29T18:41:36.000Z

</details>

**Comment by Rumyra** [comment]
Agree this isn't worded correctly, however I am trying to decide at the moment a better way to explain it 👍 bear with

**Comment by areberuto** [comment]
Thanks for dealing with it! I'll give it a try, if it sheds some light:

"A constructor's *prototype* property (for example, Foobar.prototype) is the object that will be used as the **[[Prototype]]** (that is, the returned value of calling `Object.getPrototypeOf(new Foobar()` ) for the instances created from said constructor.

We can assert it ourselves:

`
console.log(Foobar.prototype == new Foobar().__proto__); // true
console.log(Foobar.prototype == Object.getPrototypeOf(new Foobar()); // true
`

Take into account that if Foobar.prototype is assigned to a new object, the instances already created will still point to the old one."

In case it helps, I found [this explanation by Javascript Info](https://javascript.info/function-prototype) quite illustrating.

¡Saludos!

**Comment by Rumyra** [comment]
I am yet to read the link :) But yes this is great - thank you - I've been down a little rabbit hole today with this and trying to find a good way to explain it - thank you @areberuto

**Comment by Rumyra** [comment]
New _perfect_ info in this PR https://github.com/mdn/content/pull/2476 ☺️

**Comment by areberuto** [comment]
thank you Rumyra :)

**Comment by Rumyra** [comment]
Thank _you_ @areberuto :D
