### ISSUE TITLE
Missing page and short description for HTMLElement.inputMode

### ISSUE THREAD

**Issue by valioDOTch** [mdn/content#22003]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement

### What specific section or headline is this issue about?

browser_compatibility

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inputMode is linked in the table, but not available as a page; neither is it shortly described on the page itself.

### What did you expect to see?

A description of the property.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/index.md
* Last commit: https://github.com/mdn/content/commit/1732201134d732af9bfd49ee9e10f7e2086cc783
* Document last modified: 2022-10-14T07:09:52.000Z

</details>

**Comment by valioDOTch** [comment]
I stumbled accross this, as I was searching https://caniuse.com/?search=%20inputmode%20
This might be an accidental duplicate of https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

**Comment by wbamberg** [comment]
> I stumbled accross this, as I was searching https://caniuse.com/?search=%20inputmode%20 This might be an accidental duplicate of https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

I think our practice is to document both the HTML attributes and the IDL properties, like `HTMLElement.inputMode`, that reflect them. So I think we should indeed have a page at https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inputMode, but it can be quite short, deferring usage and semantics to the HTML attribute page.

cf
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/hidden
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
