### ISSUE TITLE
Learn: CSS Selectors seems like it should be before Cascade and Inheritance page

### ISSUE THREAD

**Issue by pelnik** [mdn/content#22005]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors

### What specific section or headline is this issue about?

CSS selectors

### What information was incorrect, unhelpful, or incomplete?

Hi,  I'm walking through these extremely helpful introductory pages on HTML and CSS. The CSS selectors page comes pretty late in the tutorials, but the information contained within is fairly essential to better understand previous pages, especially the "Cascade and Inheritance" pages.

### What did you expect to see?

I think it should likely be before the "Cascade and Inheritance" page, or potentially even in the "CSS First Steps" section, as someone who is actually walking through these.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors

### Do you have anything more you want to share?

Thank you for building this!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/index.md
* Last commit: https://github.com/mdn/content/commit/088a645ebde011a5ed01e8c4a20fefca0f322278
* Document last modified: 2022-09-16T20:15:29.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for opening this one. @estelle do you have any thoughts on this?

**Comment by estelle** [comment]
totally agree. Let's fix it!

**Comment by pelnik** [comment]
This is great. Thank you all!
