### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by beingmerry** [mdn/content#22025]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Events

### What specific section or headline is this issue about?

Broken link to mouse gesture events when gesture events exists

### What information was incorrect, unhelpful, or incomplete?

The link found in the table for mouse gesture events for Firefox

https://developer.mozilla.org/en-US/docs/Web/Events/Mouse_gesture_events is broken

### What did you expect to see?

Link to gesture events

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/events/index.md
* Last commit: https://github.com/mdn/content/commit/19dbdc2139ab1c68651da2b9338061d64567665d
* Document last modified: 2022-10-30T06:16:29.000Z

</details>

**Comment by bsmth** [comment]
I took a quick look and it looks like this has been removed in https://github.com/mdn/content/pull/9765

**Comment by wbamberg** [comment]
> I took a quick look and it looks like this has been removed in #9765
> 
> @wbamberg was it intentional to remove this page?

Yes. This page is about Firefox internals, not web platform features. From https://github.com/mdn/content/pull/9765/files#diff-e36fd4b0422f2cd24cc960e187b7968d1a7db603074b6c9c8c71d54a7817f3a0 :

> These gesture events are available to add-ons and other browser chrome code, but are never sent to regular web page content.

(when it says "add-ons" it means old-school XUL add-ons, which haven't been supported for about 5 years, not modern WebExtensions)

So I think the fix here is to remove the link. @beingmerry , were you looking for these pages for a particular reason, or did you just notice the link was broken?
