### ISSUE TITLE
Element.toggleAttribute() example could use other attribute than `readonly` 

### ISSUE THREAD

**Issue by myakura** [mdn/content#2203]
https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute

Currently the example uses the `readonly` attribute on input elements to demonstrate how the method works. 

https://github.com/mdn/content/blob/9917bf17a97973166bb3cb3812a496e4117a778f/files/en-us/web/api/element/toggleattribute/index.html#L47-L65

The demo works, but there's hardly a visible change on the element when the attribute is set (or removed). It might be great to use some other attributes that toggling on/off causes visible change (I'm thinking about `disabled` in particular).

**Comment by Rumyra** [comment]
Thanks @myakura - pull request is in for this change #2206 👍
