### ISSUE TITLE
Example shows non-existent “img.file” attribute

### ISSUE THREAD

**Issue by santimirandarp** [mdn/content#22030]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#example_showing_thumbnails_of_user-selected_images

### What specific section or headline is this issue about?

example_showing_thumbnails_of_user-selected_images

### What information was incorrect, unhelpful, or incomplete?

Uses `img.file` but attribute does not exist

### What did you expect to see?

line should be removed

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/file_api/using_files_from_web_applications`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/file_api/using_files_from_web_applications/index.md
* Last commit: https://github.com/mdn/content/commit/5d88855e1d963ca0b0c3c14aeaa6414f8386c64e
* Document last modified: 2022-10-12T09:03:14.000Z

</details>

**Comment by bsmth** [comment]
Hi @santimirandarp, thanks for raising the issue.

It looks like the `file` attribute is being used [later on in the guide](https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#example_uploading_a_user-selected_file). This is usage of a non-standard attribute to store some data like so:

```js
const img = document.createElement('img');
img.classList.add('obj');
img.aCoolAttribute = 'path/to/file.jpg';
document.head.appendChild(img); 
```

![image](https://user-images.githubusercontent.com/43580235/200052262-38e64262-8116-442a-ab79-aaa34901f515.png)

Maybe usage of data attribute might be better:

https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by santimirandarp** [comment]
I see. Thanks for clarifying, I'd agree using a standard data attribute rather but may not be very important.
