### ISSUE TITLE
Statements about the legality of hotlinking

### ISSUE THREAD

**Issue by jrcain-usgs** [mdn/content#22039]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML

### What specific section or headline is this issue about?

"Warning: Most images are copyrighted." under "How do we put an image on a webpage?"

### What information was incorrect, unhelpful, or incomplete?

A warning box includes the following about hotlinking:

> "...Never point your src attribute at an image hosted on someone else's website that you don't have permission to link to. This is called "hotlinking". Again, stealing someone's bandwidth is illegal..."

The "stealing someone's bandwidth is illegal" assertion surprised me, and I couldn't find a good source to back it up.  Unless a good source is available, I would recommend changing the sentence,
> "Again, stealing someone's bandwidth is illegal."

In the context of hotlinking, I don't think "stealing bandwidth" is likely to be considered illegal, even if it's easy to see that it's unethical.

If someone thinks that "stealing bandwidth" is the illegal part of hotlinking, they might try to host the image themselves, which would change their usage from possible unethical/grey area to actually illegal/copyright violation if the image was copyrighted.

### What did you expect to see?

Some possible alternatives:

> "Hotlinking is likely against the target site's terms of service."

or

> "Hotlinking to copyrighted material could get you in trouble."

I say, "could get you in trouble" because, though copyright violations are illegal, the assertion that hotlinking constitutes such a violation is shaky at best, from what I could find.

### Do you have any supporting links, references, or citations?

This [Law Stack Exchange Answer](https://law.stackexchange.com/questions/27025/when-is-linking-to-copyrighted-material-illegal) seems to indicate that hotlinking is Legal, but unacceptable.

### Do you have anything more you want to share?

I opened an issue instead of making edits myself because I'm not a lawyer or anything - someone else might know more than me here/have a source to back up what is currently on the page.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/images_in_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.md
* Last commit: https://github.com/mdn/content/commit/bb5e443fad3be7d126732a85155d5776ad977cad
* Document last modified: 2022-10-03T03:55:53.000Z

</details>

**Comment by wbamberg** [comment]
Agree that this sounds a bit much

> "Hotlinking to copyrighted material could get you in trouble."

I think the copyright and the hotlinking issue are different though aren't they? Although the current organization of the warning doesn't make that very clear. What about:

> Copyright violations are illegal and unethical.
>
> In addition, never point your src attribute at an image hosted on someone else's website that you don't have permission to link to. This is called "hotlinking". It is at best unethical, since they are paying the bandwidth costs for delivering the image when someone visits _your_ page. It also leaves you with no control over whether the image is removed or replaced with something embarrassing.

?

**Comment by jrcain-usgs** [comment]
That's a good idea, wording/presenting copyright infringement and hotlinking as different issues would cause less confusion.

It almost seems like they each deserve their own warning box?  Then again, the context is talking much more about the src attribute and where the image is hosted.  I almost wonder if talking about copyright doesn't belong here?  I'm not sure.

**Comment by jrcain-usgs** [comment]
Maybe we could start out the warning box with hotlinking, mention that they should host their own images, then say a snippet about copyright/image ownership after that.

Starting at the paragraph above the warning...

> But this is not recommended, as it just makes the browser do more work, looking up the IP address from the DNS server all over again, etc. You should almost always keep the images for your website on the same server as your HTML.
> > Warning: Never point your src attribute at an image hosted on someone else's website without permission. This is called "hotlinking". It is generally considered unethical, since someone else would be paying the bandwidth costs for delivering the image when someone visits your page. It also leaves you with no control over whether the image is removed or replaced with something embarrassing.
> >
> > In general, you should host the images you want to use on your site.  Keep in mind that many images you may find on the web are copyrighted.  Before you host an image, you should make sure that one of these is true:
> > - You own the image.
> > - You have received explicit, written permission from the image owner.
> > - You have ample proof that the image is, in fact, in the public domain.

**Comment by bsmth** [comment]
Thanks all for the good points. @jrcain-usgs would you like to open a pull request to address this issue? We can probably hash out the details at review stage if there are other strong opinions on this.
