### ISSUE TITLE
What is the use of document.fonts.check if it is always going to return true(in safari and firefox...)?

### ISSUE THREAD

**Issue by Vengatesh-Subbaiya** [mdn/content#22044]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check

### What specific section or headline is this issue about?

Browser compatibility for safari and firefox need to corrected as this api always return true....

### What information was incorrect, unhelpful, or incomplete?

Browser compatibility for safari and firefox need to corrected as this api always return true....

### What did you expect to see?

Browser compatibility - should show atleast * for safari and firefox
and show it is always going to return true if the font is not available in system......

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/fontfaceset/check`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fontfaceset/check/index.md
* Last commit: https://github.com/mdn/content/commit/b9ff6d9960e91ff4ba27d0d675c85063b57a4198
* Document last modified: 2022-10-07T21:16:19.000Z

</details>

**Comment by Vengatesh-Subbaiya** [comment]
At least mention browsers has different behaviors.

https://bugzilla.mozilla.org/show_bug.cgi?id=1252821

**Comment by Josh-Cena** [comment]
According to the current [spec draft](https://w3c.github.io/csswg-drafts/css-font-loading/#dom-fontfaceset-check), Firefox and Safari's behavior is compliant. So unless the spec text changes, Chrome needs to be marked with * instead.

**Comment by Josh-Cena** [comment]
This has been addressed in https://github.com/mdn/browser-compat-data/pull/17954 and #24931
