### ISSUE TITLE
contenteditable missing some allowed values description

### ISSUE THREAD

**Issue by dabuside** [mdn/content#22048]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable

### What specific section or headline is this issue about?

main content

### What information was incorrect, unhelpful, or incomplete?

The [above page](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable) says contenteditable has 2 enumerable values `true`, `false`.
But the browser compatibility table says it's values can be `caret`, `events`, `plaintext-only`, `typing`
Also note [that page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contentEditable) says the values also can be `inherit`

### What did you expect to see?

1. Add some description about `caret`, `events`, `plaintext-only`, `typing` values
1. Correct the allowed values

### Do you have any supporting links, references, or citations?

https://w3c.github.io/contentEditable/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/contenteditable`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/contenteditable/index.md
* Last commit: https://github.com/mdn/content/commit/b279919de5d228c3818714fd01852a4ba1b7fabc
* Document last modified: 2022-10-10T06:50:47.000Z

</details>

**Comment by OnkarRuikar** [comment]
As per the [latest spec on 7th December 2023](https://html.spec.whatwg.org/multipage/interaction.html#contenteditable) only valid values are `""`, `true`, `false`, and `plaintext-only`. Implicit value is `inherit`. 
And both the documents cover these.

**Comment by dabuside** [comment]
> As per the [latest spec on 7th December 2023](https://html.spec.whatwg.org/multipage/interaction.html#contenteditable) only valid values are `""`, `true`, `false`, and `plaintext-only`. Implicit value is `inherit`. And both the documents cover these.

w3c's spec(Editor's draft) didn't match whatwg's spec.
They are conflicted.

**Comment by dancer1325** [comment]
Could we take advantage of this issue, and create a PR to remove the reference about `inherit` or specify it better in  https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contentEditable ?

@OnkarRuikar / @dabuside

**Comment by OnkarRuikar** [comment]
> Could we take advantage of this issue, and create a PR to remove the reference about `inherit` or specify it better in https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contentEditable ?
> 
> I can create the PR if you agree with. @OnkarRuikar / @dabuside

Yes, we need to update the doc.
As per the specs `inherit` is not a value but the default state:
> The attribute's [missing value default](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#missing-value-default) and [invalid value default](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#invalid-value-default) are both the `inherit state`. The inherit state indicates that the element is editable (or not) based on the parent element's state.

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/31935
