### ISSUE TITLE
Issue with "URLSearchParams": (short summary here please)

### ISSUE THREAD

**Issue by syldeville** [mdn/content#2205]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

#### What information was incorrect, unhelpful, or incomplete?
In Examples, it uses a `for x of [] loop`, when it should be `for x **in** {}` since URLSearchParams returns an object, not an array.

#### Specific section or headline?
In the first Examples headline

#### What did you expect to see?
//Iterate the search parameters.
for (let p in searchParams) {
  console.log(p);
}

#### Did you test this? If so, how?
Yes, I tested this exact piece of code in TypeScript.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/urlsearchparams`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/urlsearchparams/index.html
* Last commit: https://github.com/mdn/content/commit/dad0283e67a05c6e904a7cf30f4529257b28fe98
* Document last modified: 2020-12-21T19:02:54.000Z

</details>

**Comment by Rumyra** [comment]
Hi @syldeville thanks for the issue, however the code in the page is correct to use `of` as it's iterating over the values within the object (of works with array like objects) - if you were to use `in` you iterate over the properties within that object:

Using `of` would log `foo 1, bar 1`

Using `in` would log `append, delete, get, getAll` etc
