### ISSUE TITLE
Link Does Not Go to Expected Content

### ISSUE THREAD

**Issue by Ordeyn** [mdn/content#22065]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility#people_with_mobility_impairments

### What information was incorrect, unhelpful, or incomplete?

In the first paragraph, final sentence: the link shown as "head pointer" with the url "https://www.performancehealth.com/baseball-cap-head-pointer" does not go to the expected product.

### What did you expect to see?

Here is an alternative product to link to: [https://www.performancehealth.com/adjustable-headpointer#sin=26972](url)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/accessibility/what_is_accessibility`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/accessibility/what_is_accessibility/index.md
* Last commit: https://github.com/mdn/content/commit/904cdf09c7e328b7a15a6a4db6bc6bd31f969cce
* Document last modified: 2022-09-09T05:00:53.000Z

</details>

**Comment by bsmth** [comment]
Hi @Ordeyn thanks a lot for raising this one 🙌🏻. Would you like to open a pull request to fix it?

**Comment by Ordeyn** [comment]
Sure! I'll read up on the process and get that pull request made.
