### ISSUE TITLE
"Black screen" video playing on Slack

### ISSUE THREAD

**Issue by barcadams0** [mdn/content#2207]
Dear Firefox community,
I faced an issue today. I uploaded a video to a Slack forum thread, it is embededd , I can see the videos' "screen" but when I press play, i got only a black screen with audio. I've already checked the forums considering this issue, in any case disabling hardware accelaration and disabling extension were advised, I tried this disabling these, but nothing happened.
Of course I have the latest version of Firefox
What can be done, or will it be fixed by an update?
![kép](https://user-images.githubusercontent.com/71493000/107359822-721ccb00-6ad5-11eb-9119-fd22e9cbaa9f.png)

Thanks in advance,
Yours sincerely,
Ádám

**Comment by chrisdavidmills** [comment]
See https://github.com/mdn/content/issues/2082#issuecomment-775239514
