### ISSUE TITLE
Inconsistent name of reduce accumulator argument

### ISSUE THREAD

**Issue by stuymedova** [mdn/content#22098]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/reduce

### What specific section or headline is this issue about?

"Try it"

### What information was incorrect, unhelpful, or incomplete?

I believe an embedded interactive example need to be updated here, for the language to be consistent with the rest of the page, specifically `previousValue` to be changed to `accumulator`.

### What did you expect to see?

`accumulator` in place of `previousValue`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/typedarray/reduce`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/reduce
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/typedarray/reduce/index.md
* Last commit: https://github.com/mdn/content/commit/ce2909126eb09e44c9f48d9f65d072acae827749
* Document last modified: 2022-09-13T07:09:29.000Z

</details>

**Comment by Josh-Cena** [comment]
@stuymedova Now that https://github.com/mdn/content/pull/22099 is merged, would you like to update the interactive example? You can edit the code here: https://github.com/mdn/interactive-examples/tree/main/live-examples/js-examples

**Comment by stuymedova** [comment]
Just updated in [#2322](https://github.com/mdn/interactive-examples/pull/2322) and [#2323](https://github.com/mdn/interactive-examples/pull/2323). Thank you for an opportunity.

**Comment by sideshowbarker** [comment]
All patches landed — thanks much
