### ISSUE TITLE
[WebAPI] Ship Web MIDI API

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#22111]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Most of the work done for this already, most recently as items linked from #21951 - e.g. https://github.com/mdn/browser-compat-data/pull/18160

We will need:
-  BCD 
  - mark as FF108 release and delete the old notes.
  - Search on `dom.webmidi.enabled` as this is what is now default true except on Android
  -  If FF site add on docs exist, then link them from the release.
- Release note

There is nothing in experimental features.
Note,  `dom.webmidi.gated` preference is on by default and will disappear from the docs following this change. That's OK IMO - it was only there as an intermediate step when it wasn't possible to get site permission add ons.

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1795025

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
@sethidden The short version is that you should pretend that mechanism for getting an extension never existed and use a version of Firefox nightly greater than 107. Firefox will generate the addon - so as a developer you don't have to do anything. As a user you will have to acknowledge a prompt and install the plugin. 

The new system allows more customized prompting than just using the permissions API and provides a consistent mechanism for a user to disable permissions (i.e. through the add ons config page). 

The versions of FF around 100-104 are now unusable with this feature. From 105 you could set `dom.webmidi.gated=false` to disable the feature.

The compatibility data has been updated in source, but has not yet updated on the live site.

**Comment by hamishwillee** [comment]
Status:
- [ ] BCD
- [ ] Docs
- [ ] Release notes
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
Closing as bcd should go through at some point 👍
