### ISSUE TITLE
[CSS] Ship trigonometric functions and constants

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#22115]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

This enables pref `layout.css.trig.enabled` by default - this was added in #19832 (FF105).

We will need to add release note, remove the experimental features entry and update BCD. Other work may be needed - depends on updates made in #19832 

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1787070

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

## Related tasks and issues

- [x] https://github.com/mdn/content/pull/22153
- [x] BCD https://github.com/mdn/browser-compat-data/pull/18178

**Comment by bsmth** [comment]
FYI, added this prematurely here, you can probably reuse:

- https://github.com/mdn/content/pull/21844/files

(since [removed](https://github.com/mdn/content/pull/22001/files))

**Comment by hamishwillee** [comment]
Thanks @bsmth - I haven't assigned this to me (yet), so it may well be that _you_ are the one who gets to reuse it :-)

**Comment by bsmth** [comment]
> so it may well be that _you_ are the one who gets to reuse it :-)

Very good, I've gone ahead and assigned this one 👍🏻

**Comment by bsmth** [comment]
There doesn't appear to be any follow-up tasks on this so I'm closing as done now
