### ISSUE TITLE
<meta> ref page doesn't cover <meta name="format-detection">

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#2211]
As mentioned here: http://www.html-5.com/metatags/meta-format-detection.html

We should probably add information about this to the page, and a BCD entry, etc.

**Comment by dhananjayd1729** [comment]
Hey @chrisdavidmills, I would like to know more about this issue(what information should we put there?)

**Comment by shikharcodes** [comment]
Hey @chrisdavidmills, I'm interested to know a bit more in detail about what changes have to be made to this page. Can you please guide me? Also, I'm interested to try and resolve this issue.

**Comment by chrisdavidmills** [comment]
@shikharcodes Sure thing.

The page linked to above talks about a `format-detection` value of the `<meta name>` attribute. If I were working on this, I would:

* Test it to see if it actually does result in the described behavior
* If so, add an entry for it in a suitable place on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name. I highly suspect it is a non-standard Apple extension to HTML, so it would go in this section: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name#other_metadata_names
* Also add an entry for this value to the browser compat data project. The data for html/meta.elements.name starts here: https://github.com/mdn/browser-compat-data/blob/master/html/elements/meta.json#L435

**Comment by thiagoschreck** [comment]
Any news regarding this? I just found myself not able to find any documentation on mdn

**Comment by chrisdavidmills** [comment]
@shikharcodes are you still interested in working on this issue? No worries if not, but I'm just checking in. Thanks!

**Comment by shikharcodes** [comment]
I'm not working on this currently @chrisdavidmills, you can assign it to someone else if needed. Thanks!

**Comment by shikharcodes** [comment]
> I'm not working on this currently @chrisdavidmills, you can assign it to someone else if needed. Thanks!

If this issue remains unresolved when I check back after a few days, I'll try to resolve it then.

**Comment by shikharcodes** [comment]
Hey @chrisdavidmills, I searched about this `<meta name>` tag and noticed that it does result in the behaviour that is described here: http://www.html-5.com/metatags/meta-format-detection.html

Also, I noticed that the tag details were given here on Apple's documentation archive: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html

So, can we say that it a standard Apple extension to HTML or not?

**Comment by sideshowbarker** [comment]
> So, can we say that it a standard Apple extension to HTML or not?

No, we can’t. It’s not standard at all — and not on track to being standardized (no issues or PRs in https://github.com/whatwg/html/search?q=format-detection) — but instead was unilaterally created by Apple and doesn’t even work reliably cross-browser (or even in desktop maybe — instead on mobile).

And Apple already has it documented at https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW5

If/when the situation changes and there’s new information about this becoming on track to being standardized, this can be revisited.

**Comment by shikharcodes** [comment]
> > So, can we say that it a standard Apple extension to HTML or not?
> 
> No, we can’t. It’s not standard at all — and not on track to being standardized (no issues or PRs in https://github.com/whatwg/html/search?q=format-detection) — but instead was unilaterally created by Apple and doesn’t even work reliably cross-browser (or even in desktop maybe — instead on mobile).
> 
> And Apple already has it documented at https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW5
> 
> If/when the situation changes and there’s new information about this becoming on track to being standardized, this can be revisited.

Okay @sideshowbarker, thanks for this input.
