### ISSUE TITLE
Incorrect mention of permanently forbidden access in 403 Forbidden

### ISSUE THREAD

**Issue by smessie** [mdn/content#22125]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

### What specific section or headline is this issue about?

403 Forbidden, intro

### What information was incorrect, unhelpful, or incomplete?

> The access is permanently forbidden and tied to the application logic, such as insufficient rights to a resource.

### What did you expect to see?

> The access is tied to the application logic, such as insufficient rights to a resource.

### Do you have any supporting links, references, or citations?

https://www.rfc-editor.org/rfc/rfc7231#section-6.5.3

### Do you have anything more you want to share?

Stating that the access is permanently forbidden is incorrect according to the official specification

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/403`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/403/index.md
* Last commit: https://github.com/mdn/content/commit/abe3b8d2d441e399a03be72e76d6c39296ebd73e
* Document last modified: 2022-10-18T16:47:45.000Z

</details>

**Comment by bsmth** [comment]
Hi @smessie, thanks for opening the issue. Would you like to open a pull request to address this one?
