### ISSUE TITLE
incorrect example

### ISSUE THREAD

**Issue by ahmadothman98** [mdn/content#22155]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

### What information was incorrect, unhelpful, or incomplete?

the example provided suggests that  `.day.dark-scheme` have ` {background: #333; color: white;}`  properties which is not true for the image

### What did you expect to see?

`
.day.dark-scheme{
    background: #eee;
    color: black;
}
`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@media/prefers-color-scheme`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@media/prefers-color-scheme/index.md
* Last commit: https://github.com/mdn/content/commit/4b203cb449fb3a39b836dc77874fc16d39254915
* Document last modified: 2022-11-03T06:52:44.000Z

</details>

**Comment by bsmth** [comment]
Hi @ahmadothman98, thanks for opening the issue. In the section you're referencing, it's not an image, but an example generated by [combining the CSS and HTML code blocks](https://github.com/mdn/content/blob/4b203cb449fb3a39b836dc77874fc16d39254915/files/en-us/web/css/@media/prefers-color-scheme/index.md?plain=1#L38-L98) (using `EmbedLiveSample`) on the page so it's directly tied to the CSS code shown. 

Let us know if that makes sense and if you still think there's an issue there. Thanks :)

**Comment by Josh-Cena** [comment]
Closing for now, because there's nothing to "fix" when we just serve an example with its outcome.
