### ISSUE TITLE
Document HTMLInputElement's (type=file) cancel event

### ISSUE THREAD

**Issue by evilpie** [mdn/content#22157]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

### What specific section or headline is this issue about?

Events

### What information was incorrect, unhelpful, or incomplete?

The `cancel` event is missing.

### What did you expect to see?

A new page for the cancel event with an example.

### Do you have any supporting links, references, or citations?

https://bugzilla.mozilla.org/show_bug.cgi?id=1719703
https://html.spec.whatwg.org/#show-the-picker,-if-applicable
https://html.spec.whatwg.org/#event-cancel

**Comment by bsmth** [comment]
Hi @evilpie 👋🏻 I've self-assigned this one, I can take a look when I have some bandwidth

**Comment by evilpie** [comment]
It would be nice to have this.

**Comment by teoli2003** [comment]
Yes, this is landing into Chromium. Do we know in which version?

**Comment by estelle** [comment]
Tasks to fix this:

- [ ] Created page https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/cancel_event
- [ ] Add `cancel` to events on  https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement#events
- [ ] Add `cancel` to the technical summaries of appropriate HTML elements 

    
The HTMLDialogElement has a cancel event. Are these different?
Also, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#technical_summary - the technical summer on dialog does not have a link to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog. It should.
