### ISSUE TITLE
Maybe mention `about:config` setting `dom.enable_performance_observer` and/or that github.com requires it to work properly ?

### ISSUE THREAD

**Issue by correabuscar** [mdn/content#22172]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver

### What information was incorrect, unhelpful, or incomplete?

No mention of `about:config` setting `dom.enable_performance_observer` being `true` for when this is enabled.

### What did you expect to see?

A mention of `about:config` setting `dom.enable_performance_observer`, maybe even mention that it shouldn't be set to `false` to mitigate against Spectre, because it's not necessary (anymore).

### Do you have anything more you want to share?

Would be nice to mention that this is a required firefox feature for github to work properly. https://github.com/github/browser-support/issues/28#issue-1440953988

Thanks to their site https://github.github.com/browser-support/  which showed a red `!` on the `PerformanceObserver Constructor` as not being available but required for github to work properly, I was able to figure out what I needed to do to make things work on github. 
 With it disabled(ie. `dom.enable_performance_observer=false`), I wasn't getting any updates, the notifications blue dot wouldn't appear unless I manually refreshed the webpage, I wouldn't see any new comments/updates if I were sitting on an issue or PR page, unless I F5/refreshed the webpage manually, and visiting a notification wouldn't move the scroll to the specific item in question, it would always just be on the top of the issue instead. When creating a new gist, changing to public gist on the green button would still show secret gist on the button even though clicking it would create the chosen public gist.

I don't know how to write all this myself in that section, or even if it's all acceptable to do so there. That's why I'm just letting you know about it here.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/performanceobserver`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/performanceobserver/index.md
* Last commit: https://github.com/mdn/content/commit/66c9543af6a0cf1baf89d5b0c972ee7dd08663b0
* Document last modified: 2022-11-05T00:48:48.000Z

</details>

**Comment by bsmth** [comment]
Hi @correabuscar thanks a lot for raising the issue, I'm glad it's been resolved and I think this issue should be a good hint for anyone else experiencing this. Regarding your suggestion; the [MDN documentation is browser-agnostic](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/What_we_write) so we don't add in hints for Firefox preferences under those pages. 

It's also worth highlighting that changing some the defaults configuration via `about:config` may lead to some pages behaving in unexpected ways (see the [config editor docs](https://support.mozilla.org/en-US/kb/about-config-editor-firefox)).

I'm going to close this one for now, thanks again :)

**Comment by correabuscar** [comment]
Oh, you're absolutely right, I didn't realize that the MDN documentation is browser-agnostic! I guess, I saw "developer.mozilla" in the url and the fact that I was using Firefox(by Mozilla), and I wrongly assumed that this website is about Firefox stuff...

Your answer, from above, is much appreciated and of course I agree with everything you said.
All the best!
