### ISSUE TITLE
Dead links/projects on "Adding captions and subtitles to HTML video"

### ISSUE THREAD

**Issue by Poopooracoocoo** [mdn/content#22176]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video

### What specific section or headline is this issue about?

Plugins

### What information was incorrect, unhelpful, or incomplete?

Playr is dead.
LeanBack Player is dead.
SublimeVideo is dead.

https://videosws.praegnanz.de/ hasn't been updated since June 2018. Is there a more up-to-date comparison of HTML5 video players?

### What did you expect to see?

I was hoping to see what video players fed subtitles to Firefox's picture-in-picture so I can decide on a video player for my own website.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/guide/audio_and_video_delivery/adding_captions_and_subtitles_to_html5_video`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/audio_and_video_delivery/adding_captions_and_subtitles_to_html5_video/index.md
* Last commit: https://github.com/mdn/content/commit/03c5110696fb433c13f3ccf63266d8affe446d8a
* Document last modified: 2022-09-22T05:07:28.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #22178 with a fix that removes the entire Plugins list. For the rationale about why the article is better off without that Plugins list, see the description there.

> I was hoping to see what video players fed subtitles to Firefox's picture-in-picture so I can decide on a video player for my own website.

That’s a reasonable information need, but it does not seem to be one that MDN is well-suited to providing.

A site such as https://softwarerecs.stackexchange.com/ seems like a better place to get that kind of information — either by searching for existing questions and answers there, or else by asking there a question like _“I’m trying to decide on a video player for my own website. Here are the ones I’ve considered so far. Are there others I should consider?”_

**Comment by Poopooracoocoo** [comment]
My apologies but I received no answer on that site. Do _you_ know which video players feed subtitles to Firefox's PiP?
