### ISSUE TITLE
Grids tutorial wording: “when content is placed _outside of_ that grid” is confusing and possibly incorrect

### ISSUE THREAD

**Issue by chaoslloyd** [mdn/content#22170]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids

### What specific section or headline is this issue about?

Wording in a tutorial.

### What information was incorrect, unhelpful, or incomplete?

The following sentence is found in the CSS Grid tutorial:

"The implicit grid is created when content is placed _outside of_ that grid, such as into our rows."

### What did you expect to see?

The italicized words — outside of — are confusing and, at least to this learner, seem incorrect or at the very least counterintuitive. I reread this sentence about ten times, trying to understand what those words meant in this context before simply taking a deep and moving ahead with the tutorial.  

I'm not sure if a simple word swap would solve the problem, but "in," "into," "on," "onto," and "along" all seem both more intuitive to me and more indicative of what's actually happening here.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/css_layout/grids`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/grids/index.md
* Last commit: https://github.com/mdn/content/commit/4b9fefebc6d21e003c8f31b40d98136a7a4b5a95
* Document last modified: 2022-10-01T03:00:18.000Z

</details>

**Comment by bsmth** [comment]
Hi @chaoslloyd, thanks a lot for opening the issue. Would you like to open a pull request that resolves this?

**Comment by chaoslloyd** [comment]
How does one do this?

**Comment by bsmth** [comment]
> How does one do this?

We've put together some [contribution docs](https://github.com/mdn/content/blob/main/CONTRIBUTING.md) if you would like to take a look through and give it a shot. Feel free to reply if you're stuck or need some help.
