### ISSUE TITLE
Examples of isolation hard to understand

### ISSUE THREAD

**Issue by synox** [mdn/content#22185]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/isolation

### What specific section or headline is this issue about?

Forcing a new stacking context for an element

### What information was incorrect, unhelpful, or incomplete?

Looking at the `Result` section, it is not obvious for me what to look for. Especially mix-blend-mode is not something I knew before.  
Moreover, in the first example with the firefox logo, it is not obvious which variant retains the original firefox colors. maybe a more drastic effect would make it more obvious. 

### What did you expect to see?

A simpler example, where the class names simple logical names, instead of `a`, `b, `c`, etc. Also have some partial overlap to demonstrate z-index. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/isolation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/isolation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/isolation/index.md
* Last commit: https://github.com/mdn/content/commit/fb2af1f15456199685a9f4fbaf8c9d003a2bf91f
* Document last modified: 2022-09-27T02:27:51.000Z

</details>

**Comment by Josh-Cena** [comment]
It has been improved in https://github.com/mdn/content/pull/24469. Because `mix-blend-mode` is one of the few use cases of this property, I think it's fine that we keep mentioning it (and it may help you learn another useful feature too).
