### ISSUE TITLE
navigator.mediaDevices.getUserMedia in Ventura 13.0 (22A380)

### ISSUE THREAD

**Issue by valComisso** [mdn/content#22187]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

### What specific section or headline is this issue about?

camera access

### What information was incorrect, unhelpful, or incomplete?

Compatibility with the new MacOS operating system (VENTURA). Since the update Camera access is working very slow and this leads to bad user experience.
DEVICE DATA:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/98831956/200837400-9add87dd-3c82-4d90-a494-4b3f140ceadf.png">
Macbook Pro - chip: Apple M1 - 8GB - Disco de arranque: Macintosh HD - macOS : Ventura 13.0

CODE: 
  navigator.mediaDevices.getUserMedia({
            audio: true, video: videoConfig
        }).then((stream) => {})

### What did you expect to see?

Support or update for the new MacOS operating system

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mediadevices/getusermedia`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediadevices/getusermedia/index.md
* Last commit: https://github.com/mdn/content/commit/19dbdc2139ab1c68651da2b9338061d64567665d
* Document last modified: 2022-10-30T06:16:29.000Z

</details>

**Comment by bsmth** [comment]
Hi @valComisso thanks for opening the issue. Usually [what we're writing about at MDN Web Docs](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/What_we_write) is browser support and functionality, so we rarely (if ever) have any references to OS-level issues or compatibility. I'd be happy to get another opinion on this, but I think this might be out-of-scope for the docs here.

**Comment by valComisso** [comment]
> Hola@valComissogracias por abrir el tema. Por [lo general, lo que escribimos en MDN Web Docs](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/What_we_write) es la compatibilidad y la funcionalidad del navegador, por lo que rara vez (o nunca) tenemos referencias a problemas o compatibilidad a nivel del sistema operativo. Me encantaría obtener otra opinión sobre esto, pero creo que esto podría estar fuera del alcance de los documentos aquí.

Muchas gracias!! espero tu respuesta! 😊

**Comment by bsmth** [comment]
I'm going to close this one for now. Thanks a lot, @valComisso 👍🏻
