### ISSUE TITLE
Incorrect unspecified value in usage comment?

### ISSUE THREAD

**Issue by davidmirandabluestem** [mdn/content#22196]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/globalPrivacyControl

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

Comment says:

// prints "specified" if Sec-GPC header is not present.

### What did you expect to see?

Is this supposed to be?

// prints "unspecified" if Sec-GPC header is not present.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/globalprivacycontrol`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/globalPrivacyControl
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/globalprivacycontrol/index.md
* Last commit: https://github.com/mdn/content/commit/161d14143bce668a6d33415d58f349423b3d3758
* Document last modified: 2022-10-23T07:17:42.000Z

</details>

**Comment by wbamberg** [comment]
> Is this supposed to be?
>
> // prints "unspecified" if Sec-GPC header is not present.

Looks like it! Thank you for filing. Would you like to file a PR to fix it: https://github.com/mdn/content/edit/main/files/en-us/web/api/navigator/globalprivacycontrol/index.md ? (totally fine if you don't want to :))

**Comment by davidmirandabluestem** [comment]
Thank you, I opened the following PR for this issue: https://github.com/mdn/content/pull/22200
