### ISSUE TITLE
FontFaceSet Example output correction

### ISSUE THREAD

**Issue by MarekOCLC** [mdn/content#22195]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

Incorrect example:

If the font given in the font specification does not exist, this function returns `true`:
```
console.log(document.fonts.check("12px NonExistingFont"));
// true
```

### What did you expect to see?

Correction, `true` should be `false`:

If the font given in the font specification does not exist, this function returns `false`:
```
console.log(document.fonts.check("12px NonExistingFont"));
// false
```

### Do you have any supporting links, references, or citations?

`console.log(document.fonts.check("12px NonExistingFont"));` returns `false` in Chrome Version 107.0.5304.87 (Official Build) (arm64)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/fontfaceset/check`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fontfaceset/check/index.md
* Last commit: https://github.com/mdn/content/commit/b9ff6d9960e91ff4ba27d0d675c85063b57a4198
* Document last modified: 2022-10-07T21:16:19.000Z

</details>

**Comment by bsmth** [comment]
Hi @MarekOCLC , thanks for raising this one. A check on Firefox shows it to return `true` like the example.

Fx version: `108.0a1 (2022-10-25) (64-bit)`:

```javascript
console.log(document.fonts.check("12px NonExistingFont"));
// true
```

This probably needs more investigation to determine if that's intentional (implementation deviating between browsers) or a bug.

**Comment by Josh-Cena** [comment]
See https://github.com/mdn/content/issues/22044 and https://github.com/mdn/content/issues/21880
