### ISSUE TITLE
 Trailing slash on void elements has no effect and interacts badly with unquoted attribute values.

### ISSUE THREAD

**Issue by pdewouters** [mdn/content#22215]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#examples

### What information was incorrect, unhelpful, or incomplete?

The W3C validator seems to recommend not using trailing slashes on void elements but the examples have them.

### What did you expect to see?

```
<meta charset="utf-8">

<!-- Redirect page after 3 seconds -->
<meta http-equiv="refresh" content="3;url=https://www.mozilla.org">
```

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/meta`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/meta/index.md
* Last commit: https://github.com/mdn/content/commit/8507170b71a6612358bdf2d9ec47b4e9b825bd78
* Document last modified: 2022-11-01T04:26:00.000Z

</details>

**Comment by bsmth** [comment]
Hi @pdewouters thanks for opening this one. There is an existing [GitHub discussion](https://github.com/mdn/mdn-community/discussions/242) on this topic, so I would encourage you to add your feedback there. I will close this one for the moment as any changes will be decided based on the outcome of that discussion.

Thank you :)
