### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Snuff-Daddy** [mdn/content#22227]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/Presentation

### What specific section or headline is this issue about?

clip-rule

### What information was incorrect, unhelpful, or incomplete?

"nonezero"

### What did you expect to see?

"nonzero"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/attribute/presentation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/Presentation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/presentation/index.md
* Last commit: https://github.com/mdn/content/commit/a03b4b0e9aaac7409ff1ce974ab1bf2f40c81e03
* Document last modified: 2022-10-30T18:14:37.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks - yes it is. Fixed in #22233. This issue will automatically close when the PR is merged.
