### ISSUE TITLE
Wrong code

### ISSUE THREAD

**Issue by sabest2022** [mdn/content#22246]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects

### What specific section or headline is this issue about?

Wrong content

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects#creating_new_objects

On this page under “using a constructor function, there is a code that is wrong and should be changed to class! 

### What did you expect to see?

It should be right info, none of those codes work!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/working_with_objects`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/working_with_objects/index.md
* Last commit: https://github.com/mdn/content/commit/510396940bbdd630c0bd9ae8c8a3946be05d4390
* Document last modified: 2022-11-08T00:45:32.000Z

</details>

**Comment by Josh-Cena** [comment]
How does the code not work? Do you have a demo?
