### ISSUE TITLE
Array.prototype[@@iterator](): if-condition doesn't work for primitives

### ISSUE THREAD

**Issue by dctii** [mdn/content#22250]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator

### What specific section or headline is this issue about?

'Handling strings and string arrays with the same function'

### What information was incorrect, unhelpful, or incomplete?

The problem is with the example here: [Handling strings and string arrays with the same function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator#handling_strings_and_string_arrays_with_the_same_function)

The `TypeError` below is thrown when verbatim inputting the code from the subsection:

<img width="1487" alt="SCR-20221111-jme" src="https://user-images.githubusercontent.com/61774862/201437566-00028d3d-441b-494d-a5cf-4d1c5d738ca1.png">

I found a way to get the desired result. Read below and I hope it helps.

### What did you expect to see?

Terminal Output:
```
a
b
c
a
b
c
123 is not an iterable object.
```

### Do you have any supporting links, references, or citations?

I used this [web page on https://futurestud.io](https://futurestud.io/tutorials/check-if-a-value-is-iterable-in-javascript-or-node-js) to help me find a workaround, but ended up using one slightly different to the one on that web page.

I did this to figure out the what the return values would be:

```
let it = 123;
let that = it[Symbol.iterator];
console.log(typeof it); // number
console.log(typeof that); // undefined

let it2 = "abc";
let that2 = it2[Symbol.iterator];
console.log(typeof it2); // string
console.log(typeof that2); // function
```

Then, I concluded that changing the if-condition in `function logIterable(it)` should contain the condition `typeof it[Symbol.iterator] !== 'function'`. The complete code that I modified to generate the expected output that the MDN example had intended is here:

```
function logIterable(it) {
  if (typeof it[Symbol.iterator] !== 'function') {
    console.log(it, "is not an iterable object.");
    return;
  }
  for (const letter of it) {
    console.log(letter);
  }
}
const arr = ['a','b','c'];
const str = "abc";
const num = 123;

logIterable(["a","b","c"]);
// a
// b
// c
logIterable("abc");
// a
// b
// c
logIterable(123); // 123 is not an iterable object.
```

Screenshot of the output:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/61774862/201438437-2d5b3dcb-867c-4a86-8380-8f03806d6bb5.png">

### Do you have anything more you want to share?

What I am using:
  macOS Ventura, Mac M1, Darwin arm64 22.1.0
  VS Code v1.73.1 (Universal)
  node v16.18.1
  nodemon v2.0.20

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/@@iterator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/@@iterator/index.md
* Last commit: https://github.com/mdn/content/commit/0826a9e4582499e62efad3d3e9d29adb1c31cfe2
* Document last modified: 2022-09-22T05:04:41.000Z

</details>

**Comment by Josh-Cena** [comment]
Thanks, your proposed code looks better to me :) PRs welcome.

**Comment by dctii** [comment]
> Thanks, your proposed code looks better to me :) PRs welcome.

PR has been made. I did not include how I arrived at the conclusion to use the if-condition that I did though, as I thought it may be unnecessarily verbose for the documentation, although it might aid novices like myself.

And for immediate reference, how I arrived at the conclusion as included in this ticket:
```
let it = 123;
let that = it[Symbol.iterator];
console.log(typeof it); // number
console.log(typeof that); // undefined

let it2 = "abc";
let that2 = it2[Symbol.iterator];
console.log(typeof it2); // string
console.log(typeof that2); // function
```
