### ISSUE TITLE
TextDecoderOptions.ignoreBOM is missing

### ISSUE THREAD

**Issue by jespertheend** [mdn/content#22268]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/TextDecoder

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

The `options` only lists `fatal`, `ignoreBOM` is missing.

### What did you expect to see?

`ignoreBOM` being listed and an explanation of what it does.

### Do you have any supporting links, references, or citations?

https://encoding.spec.whatwg.org/#dom-textdecoderoptions-ignorebom

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/textdecoder/textdecoder`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/TextDecoder
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/textdecoder/textdecoder/index.md
* Last commit: https://github.com/mdn/content/commit/000708a81fa086c5de95112ea61373eca73be415
* Document last modified: 2022-10-04T04:15:22.000Z

</details>

**Comment by bsmth** [comment]
Hi @jespertheend , thanks for flagging the issue. Would you like to open a pull request that adds these changes?
