### ISSUE TITLE
alignment-baseline useable on <text>

### ISSUE THREAD

**Issue by Snuff-Daddy** [mdn/content#22260]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline

### What information was incorrect, unhelpful, or incomplete?

&lt;text&gt; is not listed as a supported element of alignment-baseline.  However, there is an example that shows that it is.  Also, check baseline-shift for the same problem.

### What did you expect to see?

&lt;text&gt; supported

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/attribute/alignment-baseline`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/alignment-baseline/index.md
* Last commit: https://github.com/mdn/content/commit/a03b4b0e9aaac7409ff1ce974ab1bf2f40c81e03
* Document last modified: 2022-10-30T18:14:37.000Z

</details>

**Comment by Josh-Cena** [comment]
Related: https://github.com/mdn/content/issues/10137

The CSS spec for `alignment-baseline` says it applies to SVG text content elements, which includes `text`, `textPath`, and `tspan` (`tref` is deprecated). However there seems to be a Firefox bug.
