### ISSUE TITLE
Incorrect formal definition for background-position-x Percentages

### ISSUE THREAD

**Issue by ppeyliang** [mdn/content#22262]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x

### What specific section or headline is this issue about?

Formal definition

### What information was incorrect, unhelpful, or incomplete?

Percentages: refer to width of background positioning area minus `height` of background image

### What did you expect to see?

Percentages: refer to width of background positioning area minus `width` of background image

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/background-position-x`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/background-position-x/index.md
* Last commit: https://github.com/mdn/content/commit/642f2385b7cf791b3a40a81a17752f5b0c3208ea
* Document last modified: 2022-09-27T02:28:24.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/data/pull/625 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
