### ISSUE TITLE
Issue with "Element.classList": The wrong attribute "dir" is set for the Examples

### ISSUE THREAD

**Issue by Leolik** [mdn/content#2227]
MDN URL: https://developer.mozilla.org/ru/docs/Web/API/Element/classList

**What information was incorrect, unhelpful, or incomplete?**

For the Russian translation, there is an incorrect attribute `dir="rtl"` for the "Examples" section.

![image](https://user-images.githubusercontent.com/273519/107435877-ce1b3a00-6b3d-11eb-812a-5ad4958921c0.png)

**What did you expect to see?**

correct attribute `dir='ltr'`

**Comment by mohitdmak** [comment]
I can rectify 👍

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
