### ISSUE TITLE
No mention of JavaScript on this page, when it's one the only way to make it do something (other than using it inside of a form)

### ISSUE THREAD

**Issue by nathnolt** [mdn/content#22274]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

### What specific section or headline is this issue about?

First explanatory section

### What information was incorrect, unhelpful, or incomplete?

I think it should have a mention of JavaScript.

### What did you expect to see?

Having a mention of JavaScript, like rewriting the current sentence:

> Once activated, it then performs a programmable action, such as submitting a [form](https://developer.mozilla.org/en-US/docs/Learn/Forms) or opening a dialog.

To something like
 Once activated, it submits a form [form](https://developer.mozilla.org/en-US/docs/Learn/Forms) or performs a programmable action using [JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript), such as opening a dialog.

### Do you have any supporting links, references, or citations?

No

### Do you have anything more you want to share?

No

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/button`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/button/index.md
* Last commit: https://github.com/mdn/content/commit/7594b50698a76ce79209b159835e615052915723
* Document last modified: 2022-10-31T06:32:10.000Z

</details>

**Comment by bsmth** [comment]
Hi @nathnolt, thanks for opening the issue. Would you like to open a pull request to address this problem?

**Comment by kylewcode** [comment]
@bsmth I would like to work on a pull request if @nathnolt does not want to do so.

**Comment by bsmth** [comment]
Hi @kylewcode, that would be great! I've assigned you to reflect that you intend to fix this, but feel free to undo that at any point if you can't continue 🙌🏻

**Comment by nathnolt** [comment]
It's all fine by me
