### ISSUE TITLE
caption-side should have multiple spec links

### ISSUE THREAD

**Issue by estelle** [mdn/content#22271]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side

### What specific section or headline is this issue about?

specifications & syntax

### What information was incorrect, unhelpful, or incomplete?

The specs lead to https://w3c.github.io/csswg-drafts/css-logical/#caption-side which defines two values; different from those listed in the syntax box. 

caption side is also defined at https://w3c.github.io/csswg-drafts/css2/#propdef-caption-side with inline-start and inline-end. I believe `left` and `right` were once defined as well, but not finding that at the moment (nor did I look too hard). This css2 link should likely be in the spec list.

### What did you expect to see?

the specs for top and bottom

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/caption-side`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/caption-side/index.md
* Last commit: https://github.com/mdn/content/commit/fb2af1f15456199685a9f4fbaf8c9d003a2bf91f
* Document last modified: 2022-09-27T02:27:51.000Z

</details>

**Comment by OnkarRuikar** [comment]
The `left` and `right` properties were proposed for CSS 2, but removed from the final CSS 2.1 specification and only work in Firefox:
- https://github.com/w3c/csswg-drafts/issues/497
- https://github.com/w3c/csswg-drafts/commit/b80bb357f9eff783325def5318064f0a5c90f26a
