### ISSUE TITLE
It seems as though the example output is only working for width.  Height is remaining the same value?

### ISSUE THREAD

**Issue by MountainMan87119** [mdn/content#22289]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event

### What specific section or headline is this issue about?

Window Size Logger

### What information was incorrect, unhelpful, or incomplete?

The output data seems to not include valid changes data concerning height.

### What did you expect to see?

As I resized my browser, the data for width updates each time as expected,
however, making the browser taller or shorter had no corresponding effect on the example's hight data.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/resize_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/resize_event/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by wbamberg** [comment]
It's because the example is in an iframe, so height and width at the height and width of the iframe, not the MDN page. If you open the example in a separate window: https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/Window/resize_event/_sample_.window_size_logger.html it works as expected.

Perhaps this example could explain this, and add a link to open the output in a separate window?

**Comment by MountainMan87119** [comment]
Ah.

No, my bad.  That was mentioned further up the page.

I will attempt to scrub the ticket or at least acknowledge Closed/Solved.
Although, yep, adding a line of text noting that, right in the outlined box
of the example might
save folk who have an attention span as short as I apparently did, from
minor confusion.

Cheers!
~B.

**Comment by wbamberg** [comment]
I think it's quite easy to miss that note, and if you filed an issue, it's likely that many others will have been confused, but just didn't file.
