### ISSUE TITLE
Hidden paragraph BCD data still exists in content and in code

### ISSUE THREAD

**Issue by peterbe** [mdn/content#2228]
In https://github.com/mdn/yari/issues/1191 we made the text:
```html
<div class="hidden">The compatibility table on this page is generated from structured data. If you'd like to contribute to the data, please check out <a href="https://github.com/mdn/browser-compat-data">https://github.com/mdn/browser-compat-data</a> and send us a pull request.</div>
```
be something that's part of the `<BrowserCompatibilityTable>` component. So every appearance of it in the content is redundant. This issue is about cleaning this up from the content.

**Comment by peterbe** [comment]
@nschonni Let's tackle this one once we've taken care of all the excess `class="external"` on all external links.

**Comment by peterbe** [comment]
It's clearly still there a lot:

```
MOZILLA/MDN/content  main ✔
▶ rg 'The compatibility table' | wc -l
    1247
```

**Comment by teoli2003** [comment]
I think this has to stay open until all are removed. I think it is my fault if it has been closed as I link PR #5330 to it, even if it is a partial fix.

**Comment by peterbe** [comment]
Clearly some have been removed compared to by Feb 9 comment above:

```
▶ rg 'The compatibility table' | wc -l
    1222

```

**Comment by peterbe** [comment]
Bha! What's going on. I didn't mean for this to be closed. Sorry.

**Comment by teoli2003** [comment]
> Clearly some have been removed compared to by Feb 9 comment above:
> 
> ```
> ▶ rg 'The compatibility table' | wc -l
>     1222
> ```

I noticed that it was near 1400 yesterday, meaning it was climbing. That's why I started removing them.

I guess people are cloning pages than modifying them.

**Comment by teoli2003** [comment]
We have removed the hidden paragraph BCD data from mdn/content.
` rg 'The compatibility table' | wc -l
       2`

This 2 are not from such paragraph but from the contribute area explaining how to put compatibility tables in page.

@peterbe Is there still something to do here, or can we close this issue?

**Comment by peterbe** [comment]
There might be some manual searching where it has minor spelling differences that the python script can't pick up. 
Otherwise, the next thing to do is to re-apply that Python script on mdn/translated-content :)

**Comment by teoli2003** [comment]
I ran the script with different needles, and manually fixed the remaining issues. :-), so I'm fairly confident for mdn/content.

I'm a bit afraid to look at the size of mdn/translated-content :-)

**Comment by peterbe** [comment]
Let's now redirect to https://github.com/mdn/translated-content/issues/1008

**Comment by sideshowbarker** [comment]
I’m closing this here because per https://github.com/mdn/content/issues/2228#issuecomment-849962754 it seems to be resolved for the mdn/content repo — and because the follow-up issue for that mdn/translated-content repo has been raised at https://github.com/mdn/translated-content/issues/1008.

But if I’m mistaken and this should in fact remain open, then somebody please do go ahead and re-open it.
