### ISSUE TITLE
Document user activation requirement of the Fullscreen API

### ISSUE THREAD

**Issue by foolip** [mdn/content#22303]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen

### What information was incorrect, unhelpful, or incomplete?

Implementations of the Fullscreen API have always required "user activation" to go fullscreen, such as a click event. The documentation on MDN doesn't make any mention of this.

### What did you expect to see?

Probably link to a common page describing user activation in general, and expand the `toggleFullscreen()` example to use a "click" event handler, so that it can be copy-pasted and basically work.

### Do you have any supporting links, references, or citations?

In the spec this is documented here:
https://fullscreen.spec.whatwg.org/#dom-element-requestfullscreen

And the requirement to consume the user gesture is being added here:
https://github.com/whatwg/fullscreen/pull/153

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/requestfullscreen`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/requestfullscreen/index.md
* Last commit: https://github.com/mdn/content/commit/a243190b798aa57b6cc08b9ef3216aed8ab9c895
* Document last modified: 2022-09-22T16:39:52.000Z

</details>

**Comment by hamishwillee** [comment]
This is mentioned in the "Security" section: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen#security

Perhaps not visible enough. Propose #22387 as a fix.

**Comment by hamishwillee** [comment]
@foolip I am closing this as "incorrect". The data is there, and in the intended place. The fact that the place was not sufficiently visible is a different problem. I am chasing up how that should be discussed in #22415 22387
