### ISSUE TITLE
Issue with "Fetch API": strikethrough in content is confusing

### ISSUE THREAD

**Issue by toshkv** [mdn/content#2231]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#differences_from_jquery

#### What information was incorrect, unhelpful, or incomplete?
This text containing multiple strikethroughs is confusing:

fetch() won't can receive cross-site cookies; you can’t can establish a cross site session using fetch. Set-Cookie headers from other sites are silently ignored.

#### Specific section or headline?
Differences from jQuery

#### What did you expect to see?
A clearly stated sentence without strikethroughs.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/fetch_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/fetch_api/index.html
* Last commit: https://github.com/mdn/content/commit/3870228ca560ac809cb60ec9a7d461ccc9064ee3
* Document last modified: 2021-02-04T17:32:39.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Thanks for reporting.

If you want to take on it yourself, the file to edit is

https://github.com/mdn/content/blob/91d2f42aa3eef88a18be47c6cdb099e5b338dc21/files/en-us/web/api/fetch_api/index.html#L39-L40

**Comment by chrisdavidmills** [comment]
I've just fixed this; see https://github.com/mdn/content/commit/86bb421e7c11c261442d15ca765e36d9f96f5cbf

Thanks for reporting it @toshkv ; I agree that it was a bit confusing.
