### ISSUE TITLE
String.p.trim(): The definition of whitespace is too vague

### ISSUE THREAD

**Issue by TracyGJG** [mdn/content#22323]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

### What specific section or headline is this issue about?

Function description for String.prototype.trim

### What information was incorrect, unhelpful, or incomplete?

The definition of whitespace should not use terms like 'etc.' that leaves the definition vague and incomplete.

### What did you expect to see?

Instead of `Whitespace in this context is all the whitespace characters (space, tab, no-break space, etc.) and all the line terminator characters (LF, CR, etc.).`  it should be specific and detail exactly what characters the term `whitespace` includes. 

An alternative text (subject to accuracy) might be `Whitespace in this context is all the whitespace characters (space, tab, no-break space, vertical tab, form feed) and line terminator characters (LF & CR), defined by code points (in hex): x20, x09, xA0, x0B, x0C, x0A & x0D respectively.`

### Do you have any supporting links, references, or citations?

A [Microsoft](https://learn.microsoft.com/en-us/cpp/c-language/white-space-characters?view=msvc-170) reference defines whitespace as:
`Space, tab, line feed (newline), carriage return, form feed, and vertical tab characters are called "white-space characters" because they serve the same purpose as the spaces between words and lines on a printed page.` 

In the [ECMA-404 specification](https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf) for the JSON data format, whitespace is defined as just four code points as follows:
` Whitespace is any sequence of one or more of the following code points: character tabulation (U+0009), line feed (U+000A), carriage return (U+000D), and space (U+0020).`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/trim`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/trim/index.md
* Last commit: https://github.com/mdn/content/commit/cdc8fd7feab0cf6fab5512b4847e420094302271
* Document last modified: 2022-10-20T06:57:52.000Z

</details>

**Comment by Josh-Cena** [comment]
Thanks for the report—it's on my todolist to improve these string method pages. A quick way to fix this issue is to link to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#white_space.
