### ISSUE TITLE
Object.create — Polyfill Mistake

### ISSUE THREAD

**Issue by GarrettS** [mdn/content#2232]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#polyfill
Polyfill strategy has _**_always_**_ been a bad idea. 

The strategy is to see if `Object.create` exists and if it doesn't, add it, but with different functionality. This creates wrong expectations where other code with the same global global context might have a check as:
```
if (Object.create) { 
 let n = Object.create(null)
```
 
And that will have unexpected results wherever `Object.create` is not natively supported and "polyfilled" with something else that behaves differently. Granted, `Object.create` is widely supported, but this is and always has been a terrible strategy, as discussed when it was first introduced.

An acceptable approach that does not cause such problems is to create your own function. 
```
function createObject(proto, props) {
  if (!/object|function/.test(typeof proto)) {
    throw new TypeError("createObject first parameter must be an object");
  }
  if (typeof Object.create !== "function") {
  } else {
    // Implementation.
  }
}
```

**Comment by Ryuno-Ki** [comment]
So … your suggestion is to replace the polyfill code?

**Comment by GarrettS** [comment]
> So … your suggestion is to replace the polyfill code?

Yes. I propose polyfills be removed; possibly supplanted by adapter functions.

**Comment by Ryuno-Ki** [comment]
Gotcha.
@mdn/yari-content-js will look into it, I guess:
https://github.com/mdn/content/blob/main/REVIEWING.md#topic-review-owners
