### ISSUE TITLE
call() example doesn't work in Node

### ISSUE THREAD

**Issue by dctii** [mdn/content#22325]
### MDN URL

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call)

### What specific section or headline is this issue about?

[Using call() to invoke a function and without specifying the first argument](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call#using_call_to_invoke_a_function_and_without_specifying_the_first_argument)

### 1st Example:
```
// var creates a property on the global object
var globProp = 'Wisen';

function display() {
  console.log(`globProp value is ${this.globProp}`);
}

display.call(); // Logs "globProp value is Wisen"
```
Does not return expected output, but returns `globalProp value is undefined`:

![image](https://user-images.githubusercontent.com/61774862/202043766-b899619d-5658-481b-9a35-a8f66cb43fc4.png)

### What did you expect to see?

"globProp value is Wisen"

### Do you have any supporting links, references, or citations?

I don't have any supporting links, references, or citations. I tested the code out independently with this:

VS Code Version: 1.73.1 (Universal)
node v16.18.1
nodemon v2.0.20

### Do you have anything more you want to share?

Below are ways that I tried to test the code out to see what the output would be. I found a way to get the expected output, but then the intent of the subsection would be, I think, disproven since it requires a local value assignment to be done within `function display()`.

#### 1.1 `this.globProp` is `undefined` initially, but it can be defined manually
```
var globProp = 'Wisen';
console.log(this.globProp); // undefined
this.globProp = 'Wisen'; // define 'this.globProp'
console.log(this.globProp); // 'Wisen'
```

Screenshot of output:
![image](https://user-images.githubusercontent.com/61774862/202047383-ea2e62c6-3717-41c8-b904-429f5841c5cf.png)

#### 1.2 Even after 'this.globalProp' is defined globally, its global definition doesn't transmit to the function's local environment, with or without using the call method on display().

```
var globProp = 'Wisen';
this.globProp = 'Wisen';

function display() {
  console.log(`globProp value is ${this.globProp}`); // undefined
}
display(); // 'globProp value is undefined'
display.call(); // 'globProp value is undefined'
```

Screenshot of output:

![image](https://user-images.githubusercontent.com/61774862/202048033-2ec5af45-0038-41af-bf1f-2207d03c1c58.png)

#### 2.1 Longer form:

```
var globProp = 'Wisen';

function display() {
  this.globProp = globProp;
  console.log(`globProp value is ${this.globProp}`);

}

display.call(); // Logs "globProp value is Wisen"
```
#### 2.2 Truncated:
```
var globProp = 'Wisen';

function display() {
  console.log(`globProp value is ${globProp}`);

}
display.call(); // Logs "globProp value is Wisen"
```

Screenshot of output:

![image](https://user-images.githubusercontent.com/61774862/202047135-ea7a8b80-1160-4af3-9f68-12ee6bd7fd8c.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/function/call`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/function/call/index.md
* Last commit: https://github.com/mdn/content/commit/9e52d335675a9f7daa34b5e24c9b1292dbf23b2e
* Document last modified: 2022-10-31T06:22:03.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi—when running inside Node, CJS modules are wrapped into functions, so `var` declarations do not become properties on the global object. You can still verify it like this, though:

```js
function display() {
  console.log(this === globalThis);
}

display.call(); // true
```

Generally, the examples involving `this` behave differently in Node, and that's not a big problem since we are mainly concerned with scripts in browsers. Now that I'm done updating the `this` reference, I will be taking a look at the `call()` and `apply()` pages and see what I can do to make them cross-platform.

**Comment by dctii** [comment]
> Hi—when running inside Node, CJS modules are wrapped into functions, so `var` declarations do not become properties on the global object. You can still verify it like this, though:
> 
> ```js
> function display() {
>   console.log(this === globalThis);
> }
> 
> display.call(); // true
> ```
> 
> Generally, the examples involving `this` behave differently in Node, and that's not a big problem since we are mainly concerned with scripts in browsers. Now that I'm done updating the `this` reference, I will be taking a look at the `call()` and `apply()` pages and see what I can do to make them cross-platform.

Alright, thanks a lot for that. I appreciate the response and you helping me understanding how to verify it. I tested this out on a couple of different "JS playgrounds" to see what would happen. The miniature JS code-runner on MDN web docs produced the same unexpected result that I got through Node.

#### ❌ MDN Web Docs JS Demo Box
<img width="1054" alt="SCR-20221115-mgh" src="https://user-images.githubusercontent.com/61774862/202052336-f3c66144-7fae-4d06-96be-c4539dfa2d29.png">

Link to the page where this demo box was: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call)

#### ✅ jsfiddle.net 
<img width="1288" alt="SCR-20221115-mhg" src="https://user-images.githubusercontent.com/61774862/202052129-32d8f8b3-afa1-48d8-9bd1-ae6139ed159e.png">

#### ✅ codepen.io
<img width="1066" alt="SCR-20221115-mi7" src="https://user-images.githubusercontent.com/61774862/202052134-a3c89d1f-cb9b-423a-a838-6c4962c78fa2.png">

#### ✅ Google Chrome Developer JavaScript Console
![SCR-20221115-mji](https://user-images.githubusercontent.com/61774862/202052198-693a9685-32df-4682-823e-e3677844b4cb.png)
