### ISSUE TITLE
Why portal element is not defined by a void tag?

### ISSUE THREAD

**Issue by MenaiAla** [mdn/content#22328]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/portal

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/portal#basic_example

### What information was incorrect, unhelpful, or incomplete?

Your definition of `<portal>`:

> The <portal> [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element enables the embedding of another HTML page into the current one for the purposes of allowing smoother navigation into new pages.

The current example:

```html
<portal id="exampleportal" src="https://example.com/"></portal>
```

### What did you expect to see?

```html
<portal id="exampleportal" src="https://example.com/"/>
```

### Do you have any supporting links, references, or citations?

NO.

### Do you have anything more you want to share?

NO.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/portal`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/portal
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/portal/index.md
* Last commit: https://github.com/mdn/content/commit/8507170b71a6612358bdf2d9ec47b4e9b825bd78
* Document last modified: 2022-11-01T04:26:00.000Z

</details>

**Comment by sideshowbarker** [comment]
The reason MDN doesn’t document the `portal` element as a void element is that it’s not a void element — the spec that defines it does not define it as a void element.

See https://wicg.github.io/portals/#the-portal-element and see examples at https://github.com/WICG/portals etc.
