### ISSUE TITLE
URL.pathname ambiguous: does it permit or not permit the empty string?

### ISSUE THREAD

**Issue by HansBrende** [mdn/content#22333]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/URL/pathname

### What specific section or headline is this issue about?

URL.pathname

### What information was incorrect, unhelpful, or incomplete?

It is unclear whether you mean (A):

> The pathname property of the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) interface is 
(a string containing an initial / followed by the path of the URL, not including the query string or fragment) 
(or the empty string if there is no path).

or (B):

> The pathname property of the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) interface is 
a string containing an initial / followed by 
(the path of the URL, not including the query string or fragment (or the empty string if there is no path)).

### What did you expect to see?

Clarification as to whether the pathname must always begin with a leading `/`, or if it permits the empty string.

In reading (A) above, it permits the empty string. In reading (B) above, it does **not** permit the empty string.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/url/pathname`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URL/pathname
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/url/pathname/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/22335. I have some queries in that PR but shouldn't prevent this PR from being closed
