### ISSUE TITLE
Intent to document: Permissions-Policy

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#22347]
It's time to play with this one again ;-)

There is a change to Chromium that adds wildcards to `Permission-Policy` origins: https://chromestatus.com/feature/5170361717489664. Unfortunately, MDN currently only documents [Feature-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy), and it wouldn't make a lot of sense to put this change inside those docs.

So I'm going to have a go at getting `Permissions-Policy` documented once and for all.

Things to do:

* Change all the `Feature-Policy` BCD to `Permissions-Policy` and update the support versions. add alternative names for the browsers that did support `Feature-Policy` items (Fx and Saf only supported it via the `<iframe allow="">` attribute.)
  * For the moment, keep `Feature-Policy` _and_ `Permissions-Policy` so that if this gets merged and used on the site before the content updates are merged, the `Feature-Policy` pages don't break.
  * Include an entry for the new Chrome 108 feature — “Wildcards in origin values”
* Update the `Feature-Policy` header page and its directive pages to say `Permissions-Policy`. @jpmedley nearly got there a while ago — see https://github.com/mdn/content/issues/1831, and I'll definitely use that list as a basis for my work.
  * Need to move these pages using the `move` command (see https://github.com/chrisdavidmills/content/blob/main/CONTRIBUTING.md#moving-documents) so that the redirects are set up successfully.
* Add any new directives that are missing
* Make sure the landing pages are updated to change names and talk about the new syntax. See
  * https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy
  * https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy
  * Again, these need to be moved with the `move` comment
* Make sure the Permissions-Policy landing page is updated to talk about the relationship between it and the Permissions API; see https://github.com/mdn/content/issues/13003
* Document https://chromestatus.com/feature/5170361717489664
* Update the [`HTTPSidebar`](https://github.com/mdn/yari/blob/main/kumascript/macros/HTTPSidebar.ejs) macro so that it links to the new `Permissions-Policy` pages, not `Feature-Policy`.

Useful pages:

1. https://developer.chrome.com/en/docs/privacy-sandbox/permissions-policy/
2. https://github.com/w3c/webappsec-permissions-policy/blob/main/features.md

**Comment by hamishwillee** [comment]
@chrisdavidmills That sounds awesome. Last time we went around this it wasn't clear that we woudn't be better off duplicating the Feature-Policy docs and BCD for Permission-Policy. Now I think that it doesn't matter what we do - we need these docs!!!

**Comment by chrisdavidmills** [comment]
Fixed via https://github.com/mdn/content/pull/22439
