### ISSUE TITLE
The description of isConnected doesn't match the spec text

### ISSUE THREAD

**Issue by a4sriniv** [mdn/content#22346]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected

### What information was incorrect, unhelpful, or incomplete?

The HTML spec has the definition as "An element is connected if its shadow-including root is a document." 

The MDN description seems to indicate that a node being connected indirectly to a ShadowRoot is sufficient to be considered "connected", the ShadowRoot doesn't need to be indirectly connected to a Document. This doesn't match the spec text which requires it to be indirectly connected to a Document.

### What did you expect to see?

Perhaps the following text: "The read-only isConnected property of the Node interface returns a boolean indicating whether the node is connected (directly or indirectly) to the Document object".

### Do you have any supporting links, references, or citations?

https://dom.spec.whatwg.org/#connected

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/node/isconnected`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/node/isconnected/index.md
* Last commit: https://github.com/mdn/content/commit/20a58f1383da377a634b48902bff9b4fde9227c3
* Document last modified: 2022-09-11T19:36:48.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #22570 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
