### ISSUE TITLE
Code mirroring in "function*"

### ISSUE THREAD

**Issue by Adriegh** [mdn/content#2235]
Hello!
As said in title, I found that one of div's with code in article "function*" has a reversed or mirrored state.
Problem with article in russian language. Div right below "yield*" example. Pre element inside it has attribute "dir="rtl"" wich cause mirroring.
Link to the page: [function*](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/function*)

**Comment by mohitdmak** [comment]
Hey @Adriegh , the very same issue which you found was raised in issue #2227  and I had made a PR for rectifying it.
But mdn is not currently making changes to translated contents.
You can refer to https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for more details
So @chrisdavidmills  I guess this issue would have to be closed right ?

**Comment by chrisdavidmills** [comment]
Yes. Thank you @mohitdmak
