### ISSUE TITLE
dataset is also available on SVGElement

### ISSUE THREAD

**Issue by Joozty** [mdn/content#22352]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset

### What information was incorrect, unhelpful, or incomplete?

The documentation states that the dataset is only available on HTMLElement which seems to be wrong. According to the spec, it is defined on Element

### What did you expect to see?

Element.dataset in the heading instead of HTMLElement.dataset

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/dom.html#dom-dataset-dev

```js
const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
svg.dataset
// returns DOMStringMap {}
svg instanceof HTMLElement
// returns false
svg instanceof Element
// returns true
```

**Comment by sideshowbarker** [comment]
Yeah, an element created with a `http://www.w3.org/2000/svg` namespace is never going to be an `HTMLElement`.

But if you instead do:

```javascript
const p = document.createElement("p")
e instanceof HTMLElement
// returns true
```
And the https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset page documents the `dataset` property of the `HTMLElement` object.

> The documentation states that the dataset is only available on HTMLElement

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset doesn’t say it’s _only_ available on `HTMLElement` — instead it just documents that it’s available on `HTMLElement`, period.

> which seems to be wrong. According to the spec, it is defined on Element

https://html.spec.whatwg.org/multipage/dom.html#elements-in-the-dom:dom-dataset documents is as being a member of the `HTMLOrSVGElement` mixin, and at https://html.spec.whatwg.org/multipage/dom.html#elements-in-the-dom:htmlorsvgelement, the spec documents that the `HTMLElement` object includes the `HTMLOrSVGElement` mixin.

https://developer.mozilla.org/en-US/docs/Web/API/SVGElement documents that the `SVGElement` object has a `dataset` property.

I guess what’s misleading here is that if you follow the [`SVGElement.dataset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) link on that https://developer.mozilla.org/en-US/docs/Web/API/SVGElement, it takes you to the https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset page — and I guess that’s less than ideal, but it’s somewhat a consequence of the fact that we don’t document mixins as such in MDN.

**Comment by wbamberg** [comment]
> I guess what’s misleading here is that if you follow the [`SVGElement.dataset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) link on that https://developer.mozilla.org/en-US/docs/Web/API/SVGElement, it takes you to the https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset page — and I guess that’s less than ideal, but it’s somewhat a consequence of the fact that we don’t document mixins as such in MDN.

Yes, this bit is surely just wrong. It's a redirect:

```
/en-US/docs/Web/API/SVGElement/dataset	/en-US/docs/Web/API/HTMLElement/dataset
```

Given that we don't document mixins, we have to document the features they contain separately on the interfaces they they inherit from. So the best thing to do would be to write a page at https://developer.mozilla.org/en-US/docs/Web/API/SVGElement/dataset, and change that link to point to it.

**Comment by Josh-Cena** [comment]
Cross linking https://github.com/mdn/content/pull/6519
