### ISSUE TITLE
Active learning: Launch countdown repeatedly crashing page

### ISSUE THREAD

**Issue by Mizan95** [mdn/content#22364]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code

### What specific section or headline is this issue about?

Active learning: Launch countdown

### What information was incorrect, unhelpful, or incomplete?

The information is correct. However, when I attempt to use the live code editor, the page freezes and I receive a browser alert stating that the page has stopped responding.
I tried the page on two separate devices and two separate browsers. Chrome 107.0.5304.110 on Ubuntu (Linux) and Edge 107.0.1418.42  on Windows 10 .

### What did you expect to see?

The page not to stop responding

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/looping_code`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/looping_code/index.md
* Last commit: https://github.com/mdn/content/commit/d169fd2b21950bc0c0976ebbee74054692e33162
* Document last modified: 2022-09-26T17:50:45.000Z

</details>

**Comment by bsmth** [comment]
Hi @Mizan95 , thanks a lot for reporting this one. I can't reproduce this one.

__System details:__
Browser: Firefox 109.0a1 (2022-11-16) (64-bit)
OS: macOS 13.0.1 (22A400)

Could you tell us what kind of input you've added [into the example section](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code#active_learning_launch_countdown), if anything?
