### ISSUE TITLE
Video buffering: code example only working partially

### ISSUE THREAD

**Issue by Stehlampe2020** [mdn/content#22362]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/buffering_seeking_time_ranges

### What specific section or headline is this issue about?

Creating our own Buffering Feedback

### What information was incorrect, unhelpful, or incomplete?

The code example shows the browser-specific audio controls plus an own play and buffer indicator. The play indicator gets correctly updated when the actual play time changes. The browser-specific audio controls also have a buffering indicator which after some time of just waiting on the page jumps to some point in the audio. The new buffering indicator stays at 0% width even if the audio is playing normally.   
I have no idea why it's not working on the buffer indicator but working on the playing indicator.

### What did you expect to see?

I expected to see the buffering indicator always at least a little bit ahead of the play indicator.

### Do you have anything more you want to share?

Screen recording:   
https://user-images.githubusercontent.com/94976382/202396570-0eb2a665-3505-452a-adfc-65fde6b87c69.mp4   
   
(Note: the code example page seen in the video just takes the three input boxes, generates a HTML document in string form and puts it in the IFrame's `srcdoc` attribute) 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/guide/audio_and_video_delivery/buffering_seeking_time_ranges`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/buffering_seeking_time_ranges
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/audio_and_video_delivery/buffering_seeking_time_ranges/index.md
* Last commit: https://github.com/mdn/content/commit/bb7e3c7303746408072ddf4cc646e28d7e14214a
* Document last modified: 2022-09-14T06:47:31.000Z

</details>

**Comment by Stehlampe2020** [comment]
A few minutes after posting this bug report I noticed that the linked code example works - occasionally.   
Sometimes it shows the buffering like the native controls but sometimes it doesn't. On my own code snippet page it works never although I never had any problems with the code snippet page.   

<details>
<summary>Code snippet URL</summary>
<a target="_blank" href="https://www.lampe2020.de/codeschnipsel/?JavaScript=window.onload%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20audio%20%3D%20document.getElementById('my-audio')%3B%0A%0A%20%20audio.addEventListener('progress'%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20const%20duration%20%3D%20audio.duration%3B%0A%20%20%20%20if%20(duration%20%3E%200)%20%7B%0A%20%20%20%20%20%20for%20(let%20i%20%3D%200%3B%20i%20%3C%20audio.buffered.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20if%20(%0A%20%20%20%20%20%20%20%20%20%20audio.buffered.start(audio.buffered.length%20-%201%20-%20i)%20%3C%0A%20%20%20%20%20%20%20%20%20%20audio.currentTime%0A%20%20%20%20%20%20%20%20)%20%7B%0A%20%20%20%20%20%20%20%20%20%20document.getElementById('buffered-amount').style.width%20%3D%20%60%24%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20(audio.buffered.end(audio.buffered.length%20-%201%20-%20i)%20*%20100)%20%2F%20duration%0A%20%20%20%20%20%20%20%20%20%20%7D%25%60%3B%0A%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D)%3B%0A%0A%20%20audio.addEventListener('timeupdate'%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20const%20duration%20%3D%20audio.duration%3B%0A%20%20%20%20if%20(duration%20%3E%200)%20%7B%0A%20%20%20%20%20%20document.getElementById('progress-amount').style.width%20%3D%20%60%24%7B%0A%20%20%20%20%20%20%20%20audio.currentTime%20%2F%20duration%20*%20100%0A%20%20%20%20%20%20%7D%25%60%3B%0A%20%20%20%20%7D%0A%20%20%7D)%3B%0A%7D%3B&CascadingStyleSheet=.buffered%20%7B%0A%20%20height%3A%2020px%3B%0A%20%20position%3A%20relative%3B%0A%20%20background%3A%20%23555%3B%0A%20%20width%3A%20300px%3B%0A%7D%0A%0A%23buffered-amount%20%7B%0A%20%20display%3A%20block%3B%0A%20%20height%3A%20100%25%3B%0A%20%20background-color%3A%20%23777%3B%0A%20%20width%3A%200%3B%0A%7D%0A%0A.progress%20%7B%0A%20%20margin-top%3A%20-20px%3B%0A%20%20height%3A%2020px%3B%0A%20%20position%3A%20relative%3B%0A%20%20width%3A%20300px%3B%0A%7D%0A%0A%23progress-amount%20%7B%0A%20%20display%3A%20block%3B%0A%20%20height%3A%20100%25%3B%0A%20%20background-color%3A%20%23595%3B%0A%20%20width%3A%200%3B%0A%7D%0A&HyperTextMarkupLanguage=%3Caudio%20id%3D%22my-audio%22%20preload%20controls%3E%0A%20%20%3Csource%20src%3D%22http%3A%2F%2FjPlayer.org%2Faudio%2Fmp3%2FMiaow-07-Bubble.mp3%22%20type%3D%22audio%2Fmpeg%22%20%2F%3E%0A%3C%2Faudio%3E%0A%3Cdiv%20class%3D%22buffered%22%3E%0A%20%20%3Cspan%20id%3D%22buffered-amount%22%3E%3C%2Fspan%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22progress%22%3E%0A%20%20%3Cspan%20id%3D%22progress-amount%22%3E%3C%2Fspan%3E%0A%3C%2Fdiv%3E%0A">https://www.lampe2020.de/codeschnipsel/?JavaScript=window.onload%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20audio%20%3D%20document.getElementById('my-audio')%3B%0A%0A%20%20audio.addEventListener('progress'%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20const%20duration%20%3D%20audio.duration%3B%0A%20%20%20%20if%20(duration%20%3E%200)%20%7B%0A%20%20%20%20%20%20for%20(let%20i%20%3D%200%3B%20i%20%3C%20audio.buffered.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20if%20(%0A%20%20%20%20%20%20%20%20%20%20audio.buffered.start(audio.buffered.length%20-%201%20-%20i)%20%3C%0A%20%20%20%20%20%20%20%20%20%20audio.currentTime%0A%20%20%20%20%20%20%20%20)%20%7B%0A%20%20%20%20%20%20%20%20%20%20document.getElementById('buffered-amount').style.width%20%3D%20%60%24%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20(audio.buffered.end(audio.buffered.length%20-%201%20-%20i)%20*%20100)%20%2F%20duration%0A%20%20%20%20%20%20%20%20%20%20%7D%25%60%3B%0A%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D)%3B%0A%0A%20%20audio.addEventListener('timeupdate'%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20const%20duration%20%3D%20audio.duration%3B%0A%20%20%20%20if%20(duration%20%3E%200)%20%7B%0A%20%20%20%20%20%20document.getElementById('progress-amount').style.width%20%3D%20%60%24%7B%0A%20%20%20%20%20%20%20%20audio.currentTime%20%2F%20duration%20*%20100%0A%20%20%20%20%20%20%7D%25%60%3B%0A%20%20%20%20%7D%0A%20%20%7D)%3B%0A%7D%3B&CascadingStyleSheet=.buffered%20%7B%0A%20%20height%3A%2020px%3B%0A%20%20position%3A%20relative%3B%0A%20%20background%3A%20%23555%3B%0A%20%20width%3A%20300px%3B%0A%7D%0A%0A%23buffered-amount%20%7B%0A%20%20display%3A%20block%3B%0A%20%20height%3A%20100%25%3B%0A%20%20background-color%3A%20%23777%3B%0A%20%20width%3A%200%3B%0A%7D%0A%0A.progress%20%7B%0A%20%20margin-top%3A%20-20px%3B%0A%20%20height%3A%2020px%3B%0A%20%20position%3A%20relative%3B%0A%20%20width%3A%20300px%3B%0A%7D%0A%0A%23progress-amount%20%7B%0A%20%20display%3A%20block%3B%0A%20%20height%3A%20100%25%3B%0A%20%20background-color%3A%20%23595%3B%0A%20%20width%3A%200%3B%0A%7D%0A&HyperTextMarkupLanguage=%3Caudio%20id%3D%22my-audio%22%20preload%20controls%3E%0A%20%20%3Csource%20src%3D%22http%3A%2F%2FjPlayer.org%2Faudio%2Fmp3%2FMiaow-07-Bubble.mp3%22%20type%3D%22audio%2Fmpeg%22%20%2F%3E%0A%3C%2Faudio%3E%0A%3Cdiv%20class%3D%22buffered%22%3E%0A%20%20%3Cspan%20id%3D%22buffered-amount%22%3E%3C%2Fspan%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22progress%22%3E%0A%20%20%3Cspan%20id%3D%22progress-amount%22%3E%3C%2Fspan%3E%0A%3C%2Fdiv%3E%0A</a>
</details>

**Comment by Stehlampe2020** [comment]
Ok, the MDN linked snippet now suddenly works (mine not), over the slower network (9mbit/s on bredbandskollen.se, test server Malmö) in the bus in Kalmar Län, Småland...

**Comment by bsmth** [comment]
Thanks @Stehlampe2020 for reporting and testing. I'm glad it's resolved for you so I will go ahead and close the issue. If you think this is a mistake, feel free to comment and let me know.

Thank you :)

**Comment by Stehlampe2020** [comment]
@bsmth You should look at the Firefox SNAP package to see if there's something wrong that prevents this from working.   
And it still doesn't work reliably outside of JSBin...

**Comment by bsmth** [comment]
Hi @Stehlampe2020 thanks for the reply. If this issue still persists for you and you have ruled out network issues you mentioned in your comment above, it might be worth checking Bugzilla for Firefox. You can find out information for filing a report on the [how to report a bug](https://wiki.mozilla.org/BMO/How_to_Use_Bugzilla#How_to_report_a_bug) page. 

Thank you :)

**Comment by Stehlampe2020** [comment]
It's definetly not the network, the audio plays and the native indicator shows the buffering. But I'll see if I just have a problem with the code snippet page which could break the JS code.   But I think I'll keep this issue closed.
