### ISSUE TITLE
<ol> element missing from attribute reference listing elements that can have a 'type' attribute

### ISSUE THREAD

**Issue by YecineM** [mdn/content#22378]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

### What specific section or headline is this issue about?

The "type" attribute in the attribute list.

### What information was incorrect, unhelpful, or incomplete?

The _elements_ for the **type** _attribute_ are incomplete.

### What did you expect to see?

They should include **ol**.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol

**Comment by bsmth** [comment]
Hi @YecineM, thanks for reporting the issue. Would you like to open a pull request that adds `<ol>` to the list?

**Comment by YecineM** [comment]
Wow, thank you for the quick reactions, guys.
I'm just a newbie, and I had a PR run failure for some reason. It says there's no "common ancestor" between main and my fork branch.

**Comment by bsmth** [comment]
> It says there's no "common ancestor" between main and my fork branch.

Thanks @YecineM, this is a known issue in an action used in our CI at the moment, we expect it to be fixed soon. Please ignore this failure for the moment.
