### ISSUE TITLE
add BigInt on lazy equal table

### ISSUE THREAD

**Issue by yukulele** [mdn/content#2237]
BigInt should be added to this table:\
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#loose_equality_using

Specification:\
https://tc39.es/ecma262/#sec-abstract-equality-comparison

**Comment by Kim-R2O** [comment]
I will work on it :)

**Comment by chrisdavidmills** [comment]
@Kim-R2O Assigned; thanks for your interest in helping out!

**Comment by NegiAkash890** [comment]
@chrisdavidmills  Can I work on this issue ?

**Comment by sideshowbarker** [comment]
@Kim-R2O already opened #2285 for this, with a patch
