### ISSUE TITLE
Spread syntax - Incorrect note regarding availability of Javascript-native deep-clone operations

### ISSUE THREAD

**Issue by michal-weglarz** [mdn/content#22371]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

### What specific section or headline is this issue about?

Copy an array

### What information was incorrect, unhelpful, or incomplete?

The note in "Copy an array" section goes: "(...) no native operation in JavaScript does a deep clone", which is not true since there's a native method [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) that creates a deep clone of a given value using the structured clone algorithm.

### What did you expect to see?

I'd expect to see the "(...) no native operation in JavaScript does a deep clone" text deleted from the page and replaced it with mention that there's a native solution to deep-clone issue using [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone).

### Do you have any supporting links, references, or citations?

[MDN - Spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)
[MDN - structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone)
[MDN - Deep copy](https://developer.mozilla.org/en-US/docs/Glossary/Deep_copy)

### Do you have anything more you want to share?

Using the example from the note.

Current version:
```js
const a = [[1], [2], [3]];
const b = [...a];

b.shift().shift();
console.log(b);
// [[2], [3]]
console.log(a);
// [[], [2], [3]] <-- 'a' is affected

```

Using `structuredClone`:
```js
const a = [[1], [2], [3]];
const b = structuredClone(a);

b.shift().shift();
console.log(b);
// [[2], [3]]
console.log(a)
// [[1], [2], [3]] <-- 'a' is not affected
```
![Screenshot 2022-11-17 at 15 20 50](https://user-images.githubusercontent.com/37783495/202472063-558fc9be-3a3d-49cd-a29f-fdb05ee1e9fb.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/spread_syntax`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/spread_syntax/index.md
* Last commit: https://github.com/mdn/content/commit/9e52d335675a9f7daa34b5e24c9b1292dbf23b2e
* Document last modified: 2022-10-31T06:22:03.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi—`structuredClone` is not a _JavaScript_ method; it's a _WebAPI_ method. Plus, it doesn't deep copy all objects—only those that it supports.

**Comment by michal-weglarz** [comment]
You're right - my bad. Thanks for pointing that out.
Although, do you think it might be useful to have a short mention of `structuredClone` on that page? E.g. "No native operation in JavaScript does a deep clone, however the _WebAPI_ method `structuredClone` could be used in certain cases to deep copy values of selected types"

**Comment by Josh-Cena** [comment]
Sounds good—if you want to send a PR, I can review it.

**Comment by michal-weglarz** [comment]
Sure, I'll do that.
