### ISSUE TITLE
WebGL tutorial page doesn't match the linked source code

### ISSUE THREAD

**Issue by EwanRoycroft** [mdn/content#22399]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context

### What specific section or headline is this issue about?

"Creating the square plane" and "Rendering the scene"

### What information was incorrect, unhelpful, or incomplete?

The code snippets in these sections do not match those linked at the bottom of the page ("[View the complete code](https://github.com/mdn/dom-examples/tree/main/webgl-examples/tutorial/sample2)"). The article has not been updated since commit [dc98024](https://github.com/mdn/dom-examples/commit/dc98024cf19144945acb4ba2e0f66d0d4be8c8f5), which removes an unnecessary call to `bindBuffer`.

This is confusing if you're trying to follow the tutorial. In my case, I copied the [following lines](https://github.com/mdn/dom-examples/blob/c8ca119face7852cf0a428506610ae0cf81de1e3/webgl-examples/tutorial/sample2/webgl-demo.js#L61-L66) from the repository:
```js
// Here's where we call the routine that builds all the
// objects we'll be drawing.
initBuffers(gl);

// Draw the scene
drawScene(gl, programInfo);
```

And received the following error for [this line](https://github.com/mdn/dom-examples/blob/4f305d21de796432dac2e9f2961591e4b7f913c0/webgl-examples/tutorial/sample2/webgl-demo.js#L156):
```
Uncaught TypeError: Cannot read properties of undefined (reading 'position')
```

### What did you expect to see?

The tutorial should match the complete source code.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webgl_api/tutorial/adding_2d_content_to_a_webgl_context`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/tutorial/adding_2d_content_to_a_webgl_context/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by EwanRoycroft** [comment]
Looks like you made some useful changes, thanks for this @wbamberg!

**Comment by wbamberg** [comment]
No problem! If you still find any issues please let us know. These kind of pages are really hard to maintain :).
