### ISSUE TITLE
Broken link: no "Usage" section in "console" page

### ISSUE THREAD

**Issue by mikecat** [mdn/content#22398]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/console

### What specific section or headline is this issue about?

Examples / Logging to console

### What information was incorrect, unhelpful, or incomplete?

https://github.com/mdn/content/blob/a941ce3c1339cb40fb81128b95fd9dad912ca53e/files/en-us/web/api/window/console/index.md?plain=1#L35

This part has a link to "Usage" section of [console](https://developer.mozilla.org/en-US/docs/Web/API/console), but the "console" page (link destination) doesn't have "Usage" section.

### What did you expect to see?

A meaningful link (to an existing section of a page, or to a page without specifying sections)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/console`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/console
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/console/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by wbamberg** [comment]
This should probably link to https://developer.mozilla.org/en-US/docs/Web/API/console#examples.
