### ISSUE TITLE
Issue with "What is a URL?": possible issue with description of Authority portion of URL

### ISSUE THREAD

**Issue by SeaView1** [mdn/content#2239]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL

#### What information was incorrect, unhelpful, or incomplete?
Text "Therefore, the colon is not **preceded** by two slashes and only acts as a delimiter between the scheme and mail address."

#### Specific section or headline?
Authority
[https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#authority](url)

#### What did you expect to see?
Text "Therefore, the colon is not **followed** by two slashes and only acts as a delimiter between the scheme and mail address."

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/common_questions/what_is_a_url`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/common_questions/what_is_a_url/index.html
* Last commit: https://github.com/mdn/content/commit/9ee6731d7b66ed8c9b5a5ae86fedb3c361525760
* Document last modified: 2021-02-02T17:13:57.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update it 👍

**Comment by SeaView1** [comment]
Thank you @CreaTorAlexander  :+1:

**Comment by chrisdavidmills** [comment]
Assigned; thanks @CreaTorAlexander !

**Comment by SeaView1** [comment]
Thank you @chrisdavidmills  :+1:

**Comment by avivmu** [comment]
@SeaView1 Thanks for opening this.
I just want to add a small remark; while encountering small problems like this I prefer to submit a PR directly (instead of opening an issue) - it will save a little bit of time. If you are unfamiliar with the process, [this repo README](https://github.com/mdn/content#simple-changes) provides a guide for doing it.

**Comment by SeaView1** [comment]
@CreaTorAlexander and @chrisdavidmills - thanks again for your swift response on this.

**Comment by SeaView1** [comment]
Good point @avivmu , thanks for that suggestion and the link. I hadn't seen this README (as you correctly guessed!) and will bear this in mind next time.

**Comment by CreaTorAlexander** [comment]
You're welcome  @SeaView1
