### ISSUE TITLE
Issue with "protocol_handlers": …

### ISSUE THREAD

**Issue by AxelNennker** [mdn/content#224]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/protocol_handlers

#### What information was incorrect, unhelpful, or incomplete?
Assuming that most developers are like me and want to add an extension for a protocol not in the list of allowed protocols, I suggest to use `ext-foo` in the example not `magnet`.

Actually I am starting to implement an extension for the `openid` protocol as specified here:
https://bitbucket.org/openid/connect/src/master/openid-connect-self-issued-v2-1_0.md

#### Specific section or headline?
Example

#### What did you expect to see?
use "ext-foo" in the example?

Add a comment to the irc webextension example repeating the allowed list.

#### Did you test this? If so, how?
I copied the open-irc example and changed the protocol. The new extension does not run.
The error message is:
`o: installTemporaryAddon: Error: Error: Could not install add-on at '/Users/axelnennker/development/webextensions/openid-siop': Error: Extension is invalid`

A better error message would be nice but that is another issue.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/protocol_handlers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/protocol_handlers
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/add-ons/webextensions/manifest.json/protocol_handlers/index.html
* Report started: 2020-12-15T10:13:18.926Z

</details>

**Comment by AxelNennker** [comment]
https://github.com/mdn/content/pull/280

**Comment by Ryuno-Ki** [comment]
Since #280 was merged, does that imply, that this issue is resolved?
