### ISSUE TITLE
Options header in comic sans font

### ISSUE THREAD

**Issue by its-pablo** [mdn/content#22405]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API

### What specific section or headline is this issue about?

Options

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/78528552/202823719-6e7d2625-75a0-4f9d-88a4-60eaaf1aeab7.png)
The options header is in a weird small comic sans font. I tried fixing this myself but I couldn't really tell what was wrong; it seemed fine in the md file

### What did you expect to see?

The normal header, not the small comic sans one

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_locks_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_locks_api/index.md
* Last commit: https://github.com/mdn/content/commit/f7dae62645a2c735ed6f6ed63f664bf279fdfc4b
* Document last modified: 2022-09-09T05:19:45.000Z

</details>

**Comment by Josh-Cena** [comment]
Can't reproduce:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/55398995/202831139-337b8945-167f-4385-8e93-31fe7ca6894c.png">

Please give the browser and OS version, and test if it persists after refreshing/restarting browser. In any case, this should belong in Yari.

**Comment by its-pablo** [comment]
Google Chrome 103.0.5060.53 / Chrome OS
![image](https://user-images.githubusercontent.com/78528552/202833742-18c36d4b-aeb3-49b0-b3e8-04675d120dc9.png)
What exactly is Yari?

**Comment by Josh-Cena** [comment]
This repo contains Markdown files only. The rendering engine and the platform is hosted in https://github.com/mdn/yari

**Comment by its-pablo** [comment]
Alright! I'll open the issue there then.
