### ISSUE TITLE
roundRect()'s radii can be a DOMPointInit

### ISSUE THREAD

**Issue by Kaiido** [mdn/content#22408]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/roundRect

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/roundRect#parameters

### What information was incorrect, unhelpful, or incomplete?

The `radii` parameter is said to be either a number or a list.

### What did you expect to see?

The `radii` parameter can also be a `DOMPointInit` object (basically any object with `{x, y}` properties) or a list of such objects, or a list mixing numbers and such objects.  
Passing such an object as radii (or in the list) will modify the arc drawing the rounded rectangle. I'm not sure how this should be worded though.

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/canvas.html#2dcontext:dom-context-2d-roundrect
> ```idl
> optional (unrestricted double or DOMPointInitor sequence<(unrestricted double or DOMPointInit)>) radii = 0
> ```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/roundrect`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/roundRect
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/roundrect/index.md
* Last commit: https://github.com/mdn/content/commit/b4ab53fbe1501dcd6d7691e81aa67b459f995bce
* Document last modified: 2022-09-22T04:14:06.000Z

</details>

**Comment by dtrannam** [comment]
@Kaiido Hi Kaiido, I'd like to take this issue if you can assign so I can start contributing

**Comment by Kaiido** [comment]
@dtrannam I can't officially assign the issue to you (I've no power), but you should be fine writing a PR and I'd be glad to do a technical review of it.
And be sure to have a look at https://github.com/mdn/content/blob/main/CONTRIBUTING.md
