### ISSUE TITLE
"world" option missing for `registerContentScript`

### ISSUE THREAD

**Issue by marvinhagemeister** [mdn/content#22409]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/RegisteredContentScript

### What specific section or headline is this issue about?

Property list, "world" is missing.

### What information was incorrect, unhelpful, or incomplete?

Chrome and Edge have an additional property `"world"` for registered content scripts. See: https://developer.chrome.com/docs/extensions/reference/scripting/#property-RegisteredContentScript-world

### What did you expect to see?

The "world" property is missing.

### Do you have any supporting links, references, or citations?

https://developer.chrome.com/docs/extensions/reference/scripting/#property-RegisteredContentScript-world

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/RegisteredContentScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
* Last commit: https://github.com/mdn/content/commit/1ee49b729dc4cd02b862d910f279861f4b30e704
* Document last modified: 2022-09-09T05:03:45.000Z

</details>

**Comment by bsmth** [comment]
Hi @marvinhagemeister, thanks a lot for raising this one. Would you like to open a pull request to add it to the list?
