### ISSUE TITLE
Issue with "background-attachment": "local" and "fixed" doesn't work in Safari 14

### ISSUE THREAD

**Issue by trcat** [mdn/content#2242]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment

#### What information was incorrect, unhelpful, or incomplete?
`background-attachment: local` and `background-attachment: fixed` doesn't work in Safari 14

#### Specific section or headline?
Browser compatibility

#### What did you expect to see?
`background-attachment: local` and `background-attachment: fixed` should work in Safari 14, because it worked in Safari 5 as shown in the document

#### Did you test this? If so, how?
the online test in this page doesn't work when I opened in Safari 14,

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/background-attachment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/background-attachment/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by rachelandrew** [comment]
@trcat is this in iOS Safari or desktop?

**Comment by chrisdavidmills** [comment]
Hi @rachelandrew ! Did you start work on this yet? If not, can I please steal it for use with onboarding a new contributor?

**Comment by rachelandrew** [comment]
@chrisdavidmills no, other than asking the question above, go for it!

**Comment by trcat** [comment]
> @trcat is this in iOS Safari or desktop?

is desktop
