### ISSUE TITLE
Closing dialog with Escape key

### ISSUE THREAD

**Issue by bibhas2** [mdn/content#22430]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

### What specific section or headline is this issue about?

The [Advanced example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#advanced_example) section

### What information was incorrect, unhelpful, or incomplete?

The ``<dialog>`` element has a strange behavior. If you close the dialog using the Escape key or a button without a ``value`` attribute then the ``returnValue`` property is left unchanged. Any dialog ``close`` event handler that relies on the ``returnValue`` to determine which button was clicked can easily come to the wrong conclusion.

Steps to reproduce the problem in the example given on this page.

1. Click the **Update details** button.
2. Click **Confirm**. You will see the message ``default button clicked``.
3. Click the **Update details** button again.
4. Hit ``Esc`` key to close the dialog.
5. The message will incorrectly show ``default button clicked``. The timestamp will be updated.

This is a most unusual behavior for the ``<dialog>`` element that borders on being a defect. In any case, the documentation needs to point this out. One way to work around this issue is to reset the ``returnValue`` to undefined before opening the dialog. For example:

```javascript
favDialog.returnValue = undefined;
favDialog.showModal();
```

Now, when you close the dialog using the ``Esc`` key the ``returnValue`` will be undefined. 

You can also define the cancel button without a value.

```html
<button>Cancel</button>
```

Now the cancel button and the ``Esc`` key will behave the same way. That is, they will close the dialog with the ``returnValue`` set to undefined.

### What did you expect to see?

The effect of the ``Esc`` key or a button without a ``value`` on ``returnValue`` needs to be discussed. Almost any use of a dialog is vulnerable to defect unless this issue is addressed correctly. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/dialog/index.md
* Last commit: https://github.com/mdn/content/commit/7594b50698a76ce79209b159835e615052915723
* Document last modified: 2022-10-31T06:32:10.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/25794
