### ISSUE TITLE
createImageBitmap method lists elements as arguments

### ISSUE THREAD

**Issue by gsnedders** [mdn/content#22447]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap#parameters

### What information was incorrect, unhelpful, or incomplete?

> An image source, which can be an [`<img>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img), SVG [`<image>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image), [`<video>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video), [`<canvas>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas), [HTMLImageElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement), [SVGImageElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGImageElement), [HTMLVideoElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement), [HTMLCanvasElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement), [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob), [ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData), [ImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap), or [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) object.

### What did you expect to see?

It doesn't make sense to list both `<img>` and `HTMLImageElement` here: the only way to pass an element to a DOM API is via its DOM node, which is an HTMLImageElement.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/createimagebitmap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/createimagebitmap/index.md
* Last commit: https://github.com/mdn/content/commit/da88b2f3a23b9d93f083003f13c06f9d96073f6a
* Document last modified: 2022-09-13T05:21:27.000Z

</details>

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/22473
