### ISSUE TITLE
Some APIs are not listed while saying "a list of all the APIs"

### ISSUE THREAD

**Issue by mikecat** [mdn/content#22441]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API

### What specific section or headline is this issue about?

Specifications

### What information was incorrect, unhelpful, or incomplete?

The page stats **all the APIs** in

> This is a list of all the APIs that are available.

However, there are some APIs that aren't listed up. Some examples of such unlisted APIs are:

* [Web NFC API - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_NFC_API)
* [Web Serial API - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API)

### What did you expect to see?

Actually all APIs are listed up.

At least all APIs that have pages in MDN are listed up.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/index.md
* Last commit: https://github.com/mdn/content/commit/6fefcdd237a377af5c066dc2734c118feadbbef9
* Document last modified: 2022-09-02T12:08:42.000Z

</details>

**Comment by wbamberg** [comment]
This is very likely because those pages are missing an entry in the [GroupData.json](https://github.com/mdn/content/blob/main/files/jsondata/GroupData.json) file, which tells that macro which links to add, and also tells the sidebar macro what to build.

I've done a bit of digging and it looks like the following APIs don't have an entry in GroupData:

```
/content/files/en-us/web/api/user-agent_client_hints_api
/content/files/en-us/web/api/webotp_api
/content/files/en-us/web/api/idle_detection_api
/content/files/en-us/web/api/trusted_types_api
/content/files/en-us/web/api/web_nfc_api
/content/files/en-us/web/api/insertable_streams_for_mediastreamtrack_api
/content/files/en-us/web/api/web_serial_api
/content/files/en-us/web/api/webrtc_statistics_api
/content/files/en-us/web/api/device_memory_api
/content/files/en-us/web/api/resource_timing_api
/content/files/en-us/web/api/badging_api
/content/files/en-us/web/api/svg_api
/content/files/en-us/web/api/remote_playback_api
/content/files/en-us/web/api/force_touch_events
/content/files/en-us/web/api/inputdevicecapabilities_api
```

(there are some others that don't at the moment, but we are already planning ti take care of them)

**Comment by skyclouds2001** [comment]
Currently status of these apis

`/content/files/en-us/web/api/user-agent_client_hints_api` added via https://github.com/mdn/content/pull/22693
`/content/files/en-us/web/api/webotp_api` added via https://github.com/mdn/content/pull/22693
`/content/files/en-us/web/api/idle_detection_api` added via https://github.com/mdn/content/pull/22693
`/content/files/en-us/web/api/trusted_types_api` added via https://github.com/mdn/content/pull/22693
`/content/files/en-us/web/api/web_nfc_api` added via https://github.com/mdn/content/pull/22693
`/content/files/en-us/web/api/insertable_streams_for_mediastreamtrack_api`
`/content/files/en-us/web/api/web_serial_api`
`/content/files/en-us/web/api/webrtc_statistics_api`
`/content/files/en-us/web/api/device_memory_api`
`/content/files/en-us/web/api/badging_api` adding via https://github.com/mdn/content/pull/29900
`/content/files/en-us/web/api/svg_api`
`/content/files/en-us/web/api/remote_playback_api`
`/content/files/en-us/web/api/force_touch_events`
`/content/files/en-us/web/api/inputdevicecapabilities_api`

**Comment by wbamberg** [comment]
Great work @skyclouds2001 !!
