### ISSUE TITLE
.get() in Headers does not return all headers

### ISSUE THREAD

**Issue by rugk** [mdn/content#2244]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/en-US/docs/Web/API/Headers

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

Try it out in a JS console:
```js
const test = new Headers();
test.append("bla", 1);
test.get();
```

Results in:
> TypeError: Not enough arguments to Headers.get.

in Firefox 64

or
> TypeError: Headers.get requires at least 1 argument, but only 0 were passed

in Firefox 66

Whereas ` test.get("bla")` results in `1`, as expected.

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

I hope only the doc is wrong. I do not expect Firefox implements it in such a bluntly wrong way…

**Comment by himanshugarg** [comment]
Is this stiill an issue? `get()` returns only the requested header as documented and there is no `getAll()`?

**Comment by rugk** [comment]
well… looked at it again and you seem to be correct, there is no problem like this anymore.
