### ISSUE TITLE
Rework/delete event guide pages

### ISSUE THREAD

**Issue by Elchi3** [mdn/content#2245]
This is a work item for mdn/sprints#685.

We need to decide what to do with the pages in this tree https://developer.mozilla.org/en-US/docs/Web/Guide/Events and redirect, delete, or rework the pages.

@chrisdavidmills says "Looks like a lot of it can probably be deleted...I cover events for beginners in the learning area pretty well."

The pages are:

- [x] https://developer.mozilla.org/en-US/docs/Web/Guide/Events
- [x] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events
- [x] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Event_handlers
- [x] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events
- [x] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mouse_gesture_events
- [x] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events
- [x] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Orientation_and_motion_data_explained
- [x] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Overview_of_Events_and_Handlers
- [x] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Touch_events_(Mozilla_experimental)
- [x] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Using_device_orientation_with_3D_transforms

**Comment by chrisdavidmills** [comment]
@hamishwillee this is an oldie but goldie, and related to the events ref stuff you are currently doing. Maybe you could grab this one once you are done with the other bit?

**Comment by hamishwillee** [comment]
Yes I can :-). Ping me if you get back here again and I have not taken it up.

**Comment by Ryuno-Ki** [comment]
*pings @hamishwillee

**Comment by hamishwillee** [comment]
Thanks. I have taken this up. On my queue after FF87 stuff.

**Comment by hamishwillee** [comment]
Overview/thinking

- https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events 
  - Guide a really good intro. Does not provide detail on particular APIs. That's OK
  - Could use some minor reworking - e.g. inline event handlers deprecate, so lets present last. If we can pull "other event concepts" up a level they would be more visible in the sidebar.
  - Misses some more advanced topics like the custom event stuff. 

Some of these docs like the media events guide show specific use cases. I think those should be in the "Using" docs and linked from the developer guide. 

- [ ] https://developer.mozilla.org/en-US/docs/Web/Guide/Events - Keep? but cut way back to just be a thin list of links to other resources. Essentially just to have an expected main entry point. 
 
- [ ] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Event_handlers - Propose delete, but advice needed on where to put the bits.
  - has section on detecting if event handler properties exist - worth adding to intro?
  - section on `onthingy` attributes, and how you have to use setAttribute to modify them. Could this live elsewhere? I think the main point could perhaps go in https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute

- [ ] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Overview_of_Events_and_Handlers - Propose delete but some things may be capturable (see bleow)
  - What I see as interesting in this (possibly) is 
     - the event hierarchy diagram (incomplete) - could maybe usefully move to https://developer.mozilla.org/en-US/docs/Web/API/Event
     - is advice to initialise code based on completion of loading here still relevant? Feels like it is, but most of the examples seem to got on buttons that you couldn't click anyway unless loading/rendering was complete.

- [ ] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events - Embed in intro doc? Custom Event API ? TBD.
  - Covers creating and triggering your own events. I think is useful and is not covered elsewhere. Part of this and related, is triggering/simulating browser events.
  - We need to keep info.
  - Obvious place is as a section in the intro doc: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events but that doc is already pretty monolithic. 

- [ ] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Touch_events_(Mozilla_experimental) - Move under https://developer.mozilla.org/en-US/docs/Web/API/ and slap the obsolete tagging on it.
  - Only docs of deprecated/superseded MOZ touch API, discontinued in FF17.

- [ ] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events - Propose delete
  - Only has links to HTMLMediaElement events. Table has nothing more than https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement#events 
  - The [Event reference](https://developer.mozilla.org/en-US/docs/Web/Events) links to many more media events of different types. 
  - On the other hand, does have a simple overview of how it is used.
  - Maybe reduce/rework to link to the different media APIs. Minimally could remove most of this by 

- [ ] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mouse_gesture_events - Move to FF add-ons section?
  - Contains docs about non-standard MOZ gesture events (e.g. MozSwipeGesture). These are for chrome add-ons only (not web pages) and don't appear to be documented anywhere else. 
  - I tend to think perhaps NOT in this section, though possibly in add ons (and linked if we keep this section). What's our position on add-ons etc now? 
  - Generally would be good to clarify the gestures story somewhere. There is no summary or API info. From what I can see it is
     -  this mouse API for MOZ add ons. 
     - non-standard WebKit specific events on Element e.g. [gesturestart_event](https://developer.mozilla.org/en-US/docs/Web/API/Element/gesturestart_event). 
     - non-standard IE events on Element - e.g. [MSGestureChange](https://developer.mozilla.org/en-US/docs/Web/API/Element/MSGestureChange_event)
     - Deprecated/non-standard Mozilla touch events: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Touch_events_(Mozilla_experimental)
     - [Touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) - widely supported API that can be used for gestures. Could be wrong.
     - So perhaps adding the text "gesture" in the touch event section of the reference would be useful, and either delete this or more likely move it to some kind of Mozilla add on section. 

- [ ] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Orientation_and_motion_data_explained AND  https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Using_device_orientation_with_3D_transforms - Perhaps combine and move under Device Orientation & Motion API.
  - only peripherally about events.
  - Event is experimental, but looks to me that it is on-spec and widely used https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientation_event (Propose remove that experimental tagging).
  - could be combined into one doc. 
  - Further, these closely related to https://developer.mozilla.org/en-US/docs/Web/API/Detecting_device_orientation, which is NOT linked from many places. 
  - I'd like to combine ALL of these, and perhaps move under /Web/API/ as an "API" doc. I.e. Device Orientation & Motion API.

- [ ] https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events - merge into https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent
   - Is deprecated and should not be used so definitely not something that should be in this guide.
   - Though this "used" to be event and is the kind of thing usually done by events so the "newish" [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) replacement is a *surprise*. 
   - Propose add a note at the end of the event reference that points to this obsverver. Perhaps a "deprecated" section, or a "Related APIs". Are there other similar observers?

**Comment by hamishwillee** [comment]
Penultimate step in this is to find a home for the orientation/motion topics under events:
- [Orientation and motion data explained](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Orientation_and_motion_data_explained) - useful guide to the co-ordinate systems for events. This 
- [Using device orientation with 3D transforms](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Using_device_orientation_with_3D_transforms) - uses `deviceorientation` to map device to CSS coordinate system

Other relevant docs:
- [Web APIs > Detecting device orientation](https://developer.mozilla.org/en-US/docs/Web/API/Detecting_device_orientation)
  - This covers the deviceorientation and device motion events too. It is below the API doc but not linked anywhere. 
  - It refers to the  [Orientation and motion data explained](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Orientation_and_motion_data_explained) and might merge with it.

- [Window.ondeviceorientationabsolute](https://developer.mozilla.org/en-US/docs/Web/API/Window/ondeviceorientationabsolute) - corresponding docs missing. Looks like this is absolute-only version of orientation relative to earth frame, based on compass.
- [Window.deviceorientation_event](https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientation_event) and [Window.ondeviceorientation](https://developer.mozilla.org/en-US/docs/Web/API/Window/ondeviceorientation)
  - Marked experimental, but looks like the main API 
  - Documented as relative to earth frame, but has absolute and relative value. Various docs indicate it is not standardised and some systems do relative, some absolute. Not clear what relative "means".
- [Window.orientationchange](https://developer.mozilla.org/en-US/docs/Web/API/Window/orientation) (also the event). This is the angle relative to the natural device orientation of the screen. So relative to the deviceorientation. 
  - Marked as deprecated, but not clear what should be used?
  - There is also [Screen.onorientationchange](https://developer.mozilla.org/en-US/docs/Web/API/Screen/onorientationchange) that is also deprecated and FF only.
- [CSS Object Model (CSSOM) > Managing screen orientation](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Managing_screen_orientation) - this looks OK but refers to deprecated [Screen.onorientationchange](https://developer.mozilla.org/en-US/docs/Web/API/Screen/onorientationchange) 

Sideways on this we also have
- [Window.devicemotion_event](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicemotion_event) (and friends)
- [Google doc on topic](https://developers.google.com/web/fundamentals/native-hardware/device-orientation)
Anyway, 
- [Chrome 50 info on change that confuses me](https://developers.google.com/web/updates/2016/03/device-orientation-changes)

**Comment by hamishwillee** [comment]
This is complete. Well, in fact I might do a little more on orientation change (as discussed here: https://github.com/mdn/content/issues/2245#issuecomment-822971334) but that is orthogonal to the whole event guide question.
