### ISSUE TITLE
Missing page: navigator.unregisterProtocolHandler(scheme, url)

### ISSUE THREAD

**Issue by estelle** [mdn/content#22458]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator

### What specific section or headline is this issue about?

Missing API

### What information was incorrect, unhelpful, or incomplete?

missing content, The BCD is there according to caniuse. https://caniuse.com/mdn-api_navigator_unregisterprotocolhandler

### What did you expect to see?

https://html.spec.whatwg.org/multipage/system-state.html#custom-handlers

A link to unregisterprotocolhandler and navigator/APIunregisterprotocolhandler page

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/system-state.html#custom-handlers

**Comment by sideshowbarker** [comment]
@anthonymcglone2022 — thanks, now assigned to you
