### ISSUE TITLE
Example custom select is not keyboard focusable

### ISSUE THREAD

**Issue by 2kool2** [mdn/content#22513]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#customizing_select_styles

### What information was incorrect, unhelpful, or incomplete?

The example is incomplete.
While the custom select options accept tab key interaction, the custom select itself doesn't appear in the keychain and cannot be activated by keyboard. 
You have to click with a mouse first, then you can use the tab key.

### What did you expect to see?

I expected the custom select to appear in the keychain.
That is, findable and operable via keyboard only.

### Do you have anything more you want to share?

Perhaps adding tabindex=0 to the custom select would suffice, but I've not tested.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/select`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/select/index.md
* Last commit: https://github.com/mdn/content/commit/7d86bc540b9aa3d8d4a8d3109667f73d0b3ff701
* Document last modified: 2022-11-02T05:33:58.000Z

</details>

**Comment by advitiya7** [comment]
Hey i want to contribute to this,csn anyone  please explain the problem? Thank you

**Comment by 2kool2** [comment]
> Hey i want to contribute to this,csn anyone please explain the problem? Thank you

In the final example "Result", the "Custom controls" component doesn't appear in the keyboard chain. 
That is, if I move keyboard focus onto the preceding "Standard controls" select, then press the TAB key, keyboard focus should move into the Custom Control. It doesn't, focus moves to the next anchor "Technical summary".

Does that help any?

**Comment by advitiya7** [comment]
What does keyboard focus mean? Like i am not able to get the problem

**Comment by advitiya7** [comment]
Is there some way i can experience it or observe what is going wrong

**Comment by 2kool2** [comment]
> Is there some way i can experience it or observe what is going wrong

Navigate to the page anchor: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#technical_summary

With the keyboard, press SHIFT + TAB.

Keyboard focus moves from the anchor to the "Standard controls" select element under the heading Result.
Which probably has a blue outline indicating focus.
It shouldn't of landed there.
It should've moved focus to the "Custom controls" dropdown.

**Comment by advitiya7** [comment]
hey @2kool2 the keycode for the event is 13 i think if we change the  code to this `if(event.shiftKey` && event.keyCode == 9) { 
  //shift was down when tab was pressed
}
it might work i am not able to inspect and change the code to see it and when i build it's showing some error please check if this work so share the repo where the page html is located 

thanks

**Comment by advitiya7** [comment]
> > Hey i want to contribute to this,csn anyone please explain the problem? Thank you
> 
> In the final example "Result", the "Custom controls" component doesn't appear in the keyboard chain. That is, if I move keyboard focus onto the preceding "Standard controls" select, then press the TAB key, keyboard focus should move into the Custom Control. It doesn't, focus moves to the next anchor "Technical summary".
> 
> Does that help any?

i have corrected this it is now moving to custom controls on pressing `tab`

**Comment by advitiya7** [comment]
> > > Hey i want to contribute to this,csn anyone please explain the problem? Thank you
> > 
> > 
> > In the final example "Result", the "Custom controls" component doesn't appear in the keyboard chain. That is, if I move keyboard focus onto the preceding "Standard controls" select, then press the TAB key, keyboard focus should move into the Custom Control. It doesn't, focus moves to the next anchor "Technical summary".
> > Does that help any?
> 
> i have corrected this it is now moving to custom controls on pressing `tab`

[Screencast from 02-04-23 11:35:37 PM IST.webm](https://user-images.githubusercontent.com/98165017/229370753-e52b0797-9030-46e8-934b-24cf3d0c5f97.webm)
you can see the screencast it is now working but only when i make changes in html by doing inspect element ,the same change is not showing while i change the code via editor don't know what the issue

**Comment by 2kool2** [comment]
Screencast looks good, though I'd need to test code in-situ to fully confirm.

**Comment by advitiya7** [comment]
@2kool2 i just changed the tab index in the html , it is working by inspecting the local host mdn website and making the changes there but. Not when i make the same change in the actual codebase

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/33859
