### ISSUE TITLE
Low constrast link in heading

### ISSUE THREAD

**Issue by duongdominhchau** [mdn/content#2251]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators

Here is what I see on my computer:

![image](https://user-images.githubusercontent.com/56427890/107517501-69fd8200-6be0-11eb-9d98-e04a60244b6e.png)

The dark background seem out of place, other heading levels don't have dark background. I'm using dark theme, if that helps.

**Comment by NegiAkash890** [comment]
I would like to help here .

**Comment by chrisdavidmills** [comment]
@NegiAkash890 I've assigned you to the issue, thanks for your interest!

Please ask questions if you need any help. Start by having a look at this repo's README file, which included information to get you started, including how to set up and run Yari/MDN locally, so you cna test your changes before filing a PR.

**Comment by steggald** [comment]
Hello, I am new to this I have started to work on this but have just realized it has been assigned to someone else, can I still commit my changes?
what I have done is removed the <a></> sections from the <h3></h3> headings in the html.
Regards
David

**Comment by duongdominhchau** [comment]
@NegiAkash890 If you have not started yet, please wait for my PR #2261 or pull from my fork. I apologize for the inconvenience. I didn't see the notification of the assignment, so I have done some work after you are assigned to the issue.

By the way, there is a related problem in <https://developer.mozilla.org/en-US/docs/mozilla/projects/nss/ssl_functions/sslfnc> and nearby pages. This page is filled with no-href `<a>` tags, which makes nearly the whole page decorated as non-clickable links. I haven't checked if there is any page referencing these tags yet.

**Comment by peterbe** [comment]
@chrisdavidmills is right. The headings shouldn't have `<a>` tags in them. 
Soon, this will be automatically [flagged as a flaw](https://github.com/mdn/yari/issues/2593).

**Comment by chrisdavidmills** [comment]
Apologies @NegiAkash890  (and @steggald ). @duongdominhchau enthusiatically went ahead and fixed the issue that they filed.

This is fine — it is most important that we get these issues fixed. We can always find you some other issues to work on — please ping me in any other issues that interest you.
