### ISSUE TITLE
[import()] missing information on `options` feature 

### ISSUE THREAD

**Issue by yinonov** [mdn/content#22541]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import

### What specific section or headline is this issue about?

support table - options

### What information was incorrect, unhelpful, or incomplete?

[browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#browser_compatibility) table presents an `options` feature for import. nowhere on the page I could find any reference or more details on what it really means

<img width="509" alt="image" src="https://user-images.githubusercontent.com/15140652/204024699-105543f9-28dd-4d59-8558-0dab103926e9.png">

### What did you expect to see?

information on the presented feature. I wondering what that is

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/import`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/import/index.md
* Last commit: https://github.com/mdn/content/commit/0ad08fe1d8830f11e0314733f56e391affc1fe94
* Document last modified: 2022-11-17T13:58:24.000Z

</details>

**Comment by Josh-Cena** [comment]
Pending PR #19588. See issue #19220
