### ISSUE TITLE
[import()] module 'load' member is wrong?

### ISSUE THREAD

**Issue by yinonov** [mdn/content#22540]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import

### What specific section or headline is this issue about?

Importing modules with a non-literal specifier

### What information was incorrect, unhelpful, or incomplete?

[Importing modules with a non-literal specifier](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#importing_modules_with_a_non-literal_specifier)

presents a way to dynamically import modules in parallel.
The part of `module.load` throws `module.load is not a function`

### What did you expect to see?

a reference to a module model is missing in page and it's impossible to understand what members its interface includes.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/import`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/import/index.md
* Last commit: https://github.com/mdn/content/commit/0ad08fe1d8830f11e0314733f56e391affc1fe94
* Document last modified: 2022-11-17T13:58:24.000Z

</details>

**Comment by Josh-Cena** [comment]
We didn't provide an example of what the module looks like for other examples either, and this text clearly mentions that each module exports a function called `load`. Did you export it?

**Comment by yinonov** [comment]
I was confused to think module object has a `load` function.

I did run the example and noticed the resolved object contains the fetched module content. However, side effects within a module (e.g. `console.log`) didn't run. That's a gotcha might be useful to mention

**Comment by Josh-Cena** [comment]
That's interesting—side effects always run. That's how the `load` function's value gets initialized at all. Do you have code examples?

**Comment by yinonov** [comment]
sorry, rechecked and I was wrong. side effects do run. apologize for the trouble 🙏
