### ISSUE TITLE
Typo in "expressions & operators -> this" 

### ISSUE THREAD

**Issue by psychologyandfreedom** [mdn/content#22551]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

### What specific section or headline is this issue about?

"Function Context"

### What information was incorrect, unhelpful, or incomplete?

"The value of this is not the object that has the function **as an own property**, but the object that is used to call the function..." 

### What did you expect to see?

"The value of this is not the object that has the function as **its** own property, but the object that is used to call the function..." 

### Do you have any supporting links, references, or citations?

n/a

### Do you have anything more you want to share?

n/a

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/this`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/this/index.md
* Last commit: https://github.com/mdn/content/commit/0ad08fe1d8830f11e0314733f56e391affc1fe94
* Document last modified: 2022-11-17T13:58:24.000Z

</details>

**Comment by Josh-Cena** [comment]
"Own property" is a specific term in JavaScript. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties. Your proposed change means the exact same thing.

**Comment by sideshowbarker** [comment]
Closing this per https://github.com/mdn/content/issues/22551#issuecomment-1328084370
