### ISSUE TITLE
Issue with "Document.readyState": Are sub-resources like scripts still loading when readyState is "interactive"

### ISSUE THREAD

**Issue by jeremycook** [mdn/content#2256]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState#different_states_of_readiness

#### What information was incorrect, unhelpful, or incomplete?
The example code has the following comment that does not indicate if scripts are still loading when readyState is "interactive".

```javascript
// But sub-resources such as images, stylesheets and frames are still loading.
```

#### Specific section or headline?
Different states of readiness

#### What did you expect to see?
I was wondering if scripts are considered sub-resources like images, stylesheets and frames like in the above readyState "interactive" example code comment?

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/readystate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/document/readystate/index.html
* Last commit: https://github.com/mdn/content/commit/9917bf17a97973166bb3cb3812a496e4117a778f
* Document last modified: 2021-01-11T13:30:57.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I would consider scripts as sub-resources like images, stylesheets and frames.
I can update it :+1:

**Comment by Ryuno-Ki** [comment]
Give it a shot, @CreaTorAlexander!
