### ISSUE TITLE
Issue with "FetchEvent.respondWith()": (short summary here please)

### ISSUE THREAD

**Issue by tejohnso** [mdn/content#2258]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/respondWith

#### What information was incorrect, unhelpful, or incomplete?

The Browser Compatibility indicates no support in Safari (Desktop) which is contradicted in [Is ServiceWorker Ready](https://jakearchibald.github.io/isserviceworkerready/index.html#fetchevent.respondwith()) referenced in the See Also section.

#### Specific section or headline?

Browser Compatibility

#### What did you expect to see?

Safari 11.1+ support as indicated [here](https://jakearchibald.github.io/isserviceworkerready/index.html#fetchevent.respondwith())

#### Did you test this? If so, how?

Yes, using a Browserstack live session on Safari 11.1 and the [test](https://jakearchibald.github.io/isserviceworkerready/demos/fetchevent/) included on the [Is ServiceWorker Ready](https://jakearchibald.github.io/isserviceworkerready/index.html#fetchevent.respondwith()) site.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/fetchevent/respondwith`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/respondWith
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/fetchevent/respondwith/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by Ryuno-Ki** [comment]
You might need to fill the ticket with https://github.com/mdn/browser-compat-data/issues - a new release there will be catched in other parts of MDN and then trigger an update of the table.
