### ISSUE TITLE
Issue with "Document.cookie": document.cookie is empty which causes an Exception

### ISSUE THREAD

**Issue by avivmu** [mdn/content#2260]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#example_2_get_a_sample_cookie_named_test2

#### What information was incorrect, unhelpful, or incomplete?
Looking at the DevTools I saw that `document.cookie` was empty (`""`) (**after** adding the `test1` and `test2` cookies), which caused the `TypeError`:

> Example_2_Get_a_sample_cookie_named_test2:52 Uncaught TypeError: Cannot read property 'split' of undefined
    at Example_2_Get_a_sample_cookie_named_test2:52

#### Specific section or headline?
In example 2:
```
document.cookie = "test1=Hello";
document.cookie = "test2=World";

const cookieValue = document.cookie
  .split('; ')
  .find(row => row.startsWith('test2'))
  .split('=')[1];

function alertCookieValue() {
  alert(cookieValue);
}
```
I don't know much about cookies so cannot add a resolution

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/cookie`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/document/cookie/index.html
* Last commit: https://github.com/mdn/content/commit/3c8dd140b3925bf8f7b00d0972f27c5760f5c6a3
* Document last modified: 2021-01-15T13:22:56.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Hm, it works for me. Let's see, whether someone else has an idea.

**Comment by chrisdavidmills** [comment]
This worked for for me too. I'm closing this as "works for me"

**Comment by jpmedley** [comment]
What browsers are all of you using? Older APIs can have implementation variations that aren't intended by the spec. This is why specs switched from descriptive paragraphs to algorithms a few years ago. This could indicate a problem with a single browser's implementation that needs to be referred to an appropriate spec committee.

**Comment by avivmu** [comment]
I'm using Chrome Version 88.0.4324.96 (Official Build) (64-bit).
When I start the page I see this error:

> Example_2_Get_a_sample_cookie_named_test2:52 Uncaught TypeError: Cannot read property 'split' of undefined
    at Example_2_Get_a_sample_cookie_named_test2:52

And `document.cookie` is

> document.cookie
"lux_uid=161462363048649720; _ga=GA1.2.1034672815.1614623635; _gid=GA1.2.2027093868.1614623635; _gat=1"

Running the example throws:

> Example_2_Get_a_sample_cookie_named_test2:55 Uncaught ReferenceError: Cannot access 'cookieValue' before initialization
    at alertCookieValue (Example_2_Get_a_sample_cookie_named_test2:55)
    at HTMLButtonElement.onclick (Example_2_Get_a_sample_cookie_named_test2:42)
alertCookieValue @ Example_2_Get_a_sample_cookie_named_test2:55
onclick @ Example_2_Get_a_sample_cookie_named_test2:42

**Comment by avivmu** [comment]
Feel free to close
