### ISSUE TITLE
Page about margin collapse could explicitly explain that it doesn't apply to Flexbox

### ISSUE THREAD

**Issue by elpres** [mdn/content#22608]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing

### What information was incorrect, unhelpful, or incomplete?

It would be great to see a mention of the fact that margins don't collapse in a container with `display: flex`. I was debugging a layout issue with two adjacent margins not collapsing (`flex-direction: column`, two `div`s above each other, the first one had a `margin-bottom`, the second a `margin-top`, touching each other), read the entire page and concluded that there is no apparent reason why the margin collapse doesn't happen. I was able to figure it out after some trial and error, and also found this helpful comment on StackOverflow: https://stackoverflow.com/a/43882888/727288

### What did you expect to see?

I guess, technically, the list under "Margin collapsing occurs in three basic cases:" should be expanded by including another condition, specifically that it only occurs in a block formatting context, and by explicitly pointing out that Flexbox doesn't count (Grid surely also doesn't, but in that case I wouldn't even expect margins to collapse in the first place).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_box_model/mastering_margin_collapsing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_box_model/mastering_margin_collapsing/index.md
* Last commit: https://github.com/mdn/content/commit/71c4bc0b6329ec40ddbefd8d3124547e91cfa612
* Document last modified: 2022-09-28T03:40:57.000Z

</details>

**Comment by vedant-z** [comment]
@elpres Do I need to add follow note under section "Some things to note" ?

Margins don't collapse in a container with display: flex

**Comment by vedant-z** [comment]
@elpres Do I need to add following note under section "Some things to note" ?

Margins don't collapse in a container with display: flex

**Comment by elpres** [comment]
Yeah, that sounds like a good way to put it.
