### ISSUE TITLE
performance.getEntries[*] does not return all entry types

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#22619]
See https://w3c.github.io/timing-entrytypes-registry/#dfn-availablefromtimeline - entries that are not marked as "Available in timeline" are not returned by a call to `performance.getEntries()`, although they are passed to the PerformanceObserver.

**Comment by Elchi3** [comment]
Would you expect a note for this on the getEntries* pages? Or a more involved comparison between getEntries* and PerformanceObserver in the guide? (or both? :) )

**Comment by wbamberg** [comment]
> Would you expect a note for this on the getEntries* pages? Or a more involved comparison between getEntries* and PerformanceObserver in the guide? (or both? :) )


Definitely a list of supported entry types in all `getEntries*` pages. I mean, it's a clear limitation of the API: if I call `performance.getEntries();` and I don't see any `"event"` entries, I don't expect to have to visit the guide page to see what's going on.

I had totally assumed that `getEntries*` and `PerformanceObserver` were essentially equivalent in terms of what they would return.

The guide is more of a judgement call but I would probably mention it there too.

> 
> In Chrome's console, there is this warning:
> 
> `performance.getEntriesByType("largest-contentful-paint");`
> 
> > Deprecated API for given entry type.
