### ISSUE TITLE
XPath translate function documentation has error in output

### ISSUE THREAD

**Issue by MatthijsM** [mdn/content#22616]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/translate

### What specific section or headline is this issue about?

Notes (second example)

### What information was incorrect, unhelpful, or incomplete?

I came here to learn how to use translate (so I'm no expert) but it seems like the output for the second example is incorrect.

> The quick red fox.

### What did you expect to see?

Shouldn't it be "The quick red fex."? I know this doesn't make the outcome as "clean" but I think it will cause less confusion.

**Comment by vedant-z** [comment]
@MatthijsM Shouldn't the output be --> The quick red fdx.

Let me know if I am wrong and what's the correct output in that case, I will update the doc and make a PR

**Comment by MatthijsM** [comment]
Oh yeah! Yes, that is what it should be.

**Comment by bsmth** [comment]
Thanks, both for investigating. Should we maybe change the example to something else? Having `brown` -> `red` would be great if it works like a regex, but it's  more like [1:1 translation of characters](http://xpather.com/):

```
translate('The quick brown fox.', 'T .', 't-_')
-> the-quick-brown-fox_

translate('Web/XPath/Functions/format-number', '/WXPF-', ',wxpf_')
-> web,xpath,functions,format_number
```

**Comment by KSSaiTeja** [comment]
could you please assign it to me

**Comment by hamishwillee** [comment]
@KSSaiTeja If you want to work on this just create a PR, and in that PR add the text `Fixes #22616`.

(We no longer directly assign - you just check for existing PR links on an issue you are interested in - if there are none then you can create a PR and start working).

**Comment by KSSaiTeja** [comment]
thanks for the reply @hamishwillee i'll raise a PR with your suggestion

**Comment by KSSaiTeja** [comment]
@hamishwillee could you please confirm me what changes should i have to make..?

**Comment by KSSaiTeja** [comment]
@hamishwillee please respond to my comment

**Comment by hamishwillee** [comment]
The minimal fix is to change O to E.

![image](https://github.com/mdn/content/assets/5368500/8baeeaf6-1ffa-4936-9007-822ba19df6dd)

This whole document could be improved. If I was doing this I would make the examples into live examples: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples#traditional_live_samples

I would also completely rewrite the text to make it clear that this is not a string replacement or regexp - it's more like a substitution cypher. So if a letter in the nth position of originalLetters appears in string, then it is replaced by the letter at the nth position in replacementLetters

```
translate(string, originalLetters, replacementLetters)
```

**Comment by KSSaiTeja** [comment]
ok thanks for the information.. i will start working on this

**Comment by KSSaiTeja** [comment]
changed this.. but took your words into consideration.. so i will rewrite the example and after that i will raise a PR :D

**Comment by KSSaiTeja** [comment]
@bsmth thanks for merging my PR.. and i will look forward to contribute more to MDN

**Comment by bsmth** [comment]
Thank you @KSSaiTeja welcome aboard 🙌🏻
