### ISSUE TITLE
Using Custom Element doc not match with example

### ISSUE THREAD

**Issue by samarsault** [mdn/content#22626]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

### What specific section or headline is this issue about?

Autonomous custom elements

### What information was incorrect, unhelpful, or incomplete?

According to the doc, code for defining the functionality of custom elements should be written in the `connectedCallback` lifecycle method. In the attached example, however, it is written inside `constructor`, which the doc advocates not to use  because the attributes are not initialized by then. However, we are able to use element functionality like `this.getAttribute` in the example without any issues.

### What did you expect to see?

Custom element functionality can be written inside constructor

### Do you have any supporting links, references, or citations?

https://github.com/mdn/web-components-examples/blob/main/popup-info-box-web-component/main.js

### Do you have anything more you want to share?

<img width="808" alt="Screenshot 2022-11-30 at 1 52 59 PM" src="https://user-images.githubusercontent.com/2987087/204744500-24689c43-d42b-49ca-80ec-fce7b1096513.png">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/web_components/using_custom_elements/index.md
* Last commit: https://github.com/mdn/content/commit/3afc4a9557e0c71cbcf5491975d8edec38422247
* Document last modified: 2022-10-20T19:29:00.000Z

</details>

**Comment by vedant-z** [comment]
@samarsault Is it okay if I just remove that last line as there are no issues with it?
