### ISSUE TITLE
Issue with "sslfnc": (short summary here please)

### ISSUE THREAD

**Issue by NegiAkash890** [mdn/content#2262]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/SSL_functions/sslfnc

#### What information was incorrect, unhelpful, or incomplete?
Some links are broken and as well as few  <a> ( anchor tags ) are'nt displayed incorrectly .

#### Specific section or headline?
Links below 
Chapter 4
SSL Functions

This chapter describes the core SSL functions.

Some <a> tags styling like 

Initializing Multi-Processing with a Shared SSL Server Cache 

#### Did you test this? If so, how?
By clicking the links .

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/projects/nss/ssl_functions/sslfnc`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/SSL_functions/sslfnc
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/projects/nss/ssl_functions/sslfnc/index.html
* Last commit: https://github.com/mdn/content/commit/2b7177d176999a0291d681289dc3132412097f3b
* Document last modified: 2021-01-07T08:27:04.000Z

</details>

**Comment by NegiAkash890** [comment]
I would like to fix the same issue .

**Comment by chrisdavidmills** [comment]
OK, assigned!

**Comment by NegiAkash890** [comment]
@chrisdavidmills I am working on this issue and  I just want to ask for few things before I make any major Changes .
1 ) All the headings and even the paragraph are inside the <a> tags which  are not currently being used ( leads to 404 page ) .  
     I just want to ask whether I should remove all the anchors tags ( wherever necessary  from heading and paragraph) .
2 ) Some of links leads to 404 page , so after fixing the above problem ( with heading and paragraph ) I will be requiring a little     help to find the links that direct user to correct page .

Thank You !

**Comment by NegiAkash890** [comment]
@chrisdavidmills I am working on this issue and I just want to ask for few things before I make any major Changes .

1 ) All the headings and even the paragraph are inside the <a> tags which are not currently being used ( leads to 404 page or some random number ) . I just want to ask whether I should remove all the anchors tags ( wherever necessary from heading and paragraph) .
2 ) Some of links leads to 404 page , so after fixing the above problem ( with heading and paragraph ) I will be requiring a little help to find the links( hrefs ) that direct user to correct page .

Thank You !

**Comment by NegiAkash890** [comment]
Hi , @chrisdavidmills  I am working on this issue and I just want to ask for few things before I make any major Changes .
1 ) All the headings and even the paragraph are inside the <a> tags which are not currently being used ( leads to 404 page ) .
    Some just like : <a id="1202784"> </a>  (which leads to nowhere in the page)
    I just want to ask whether I should remove all the anchors tags ( wherever necessary from heading and paragraph) .

2 ) Some of links leads to 404 page , so after fixing the above problem ( with heading and paragraph ) I will be requiring a little help to find the links that direct user to correct page .

Thank You !

**Comment by NegiAkash890** [comment]
Hi , @chrisdavidmills  I am working on this issue and I just want to ask for few things before I make any major Changes .
1 ) All the headings and even the paragraph are inside the `<a>` tags which are not currently being used ( leads to 404 page ) .
    Some just like :` <a id="1202784"> </a> ` (which leads to nowhere in the page)
    I just want to ask whether I should remove all the anchors tags ( wherever necessary from heading and paragraph) .

2 ) Some of links leads to 404 page , so after fixing the above problem ( with heading and paragraph ) I will be requiring a little help to find the links that direct user to correct page .

Thank You !

**Comment by NegiAkash890** [comment]
Hi , @chrisdavidmills  I am working on this issue and I just want to ask for few things before I make any major Changes .

1)  All the headings and even the paragraph are inside the `<a>` tags which are not currently being used ( leads to 404 page ) .
     Something  just like : `<a id="1202784"> </a>`  (which leads to nowhere in the page)
     I just want to ask whether I should remove all the anchors tags ( wherever necessary from heading and paragraph) .

2 ) Some of links leads to 404 page , so after fixing the above problem ( with heading and paragraph ) . 
     I will be requiring a little  help to find the links that directs user to correct page .  

Thank You !

**Comment by NegiAkash890** [comment]
Hi , @chrisdavidmills I am working on this issue and I just want to ask for few things before I make any major Changes .

1) All the headings and even the paragraph are inside the `<a> ` tags which are not currently being used ( leads to 404 page ) .
    Something just like : `<a id="1202784"> </a>` (which leads to nowhere in the page)
    I just want to ask whether I should remove all the anchors tags ( wherever necessary from heading and paragraph) .

2) Some of links leads to 404 page , so after fixing the above problem ( with heading and paragraph ) .
I will be requiring a little help to find the links that directs user to correct page .

Thank You !

**Comment by chrisdavidmills** [comment]
@NegiAkash890 Looking at this in a bit more detail, I'd actually suggest that you work on something else. This isn't an important part of the docs, from an MDN perspective (we are waiting for the Firefox engineers to migrate this off MDN, as it is not relevant to our core mission)

We have planty of API issues in our list that are way more useful to work on.

If you really want to work on this, then sure, I'm not going to stop you. It would be good to get rid of all the unnecessary anchors, definitely. I probably can't help you with fixing all the broken links. I don't know much about NSS, or where the links should go to.

**Comment by Ryuno-Ki** [comment]
That being said, removing the anchors alone is worth submitting a PR.

**Comment by NegiAkash890** [comment]
Thanks  @chrisdavidmills and @Ryuno-Ki  for helping me out here . As @chrisdavidmills  mentioned that it will be a good idea 
to let  Firefox engineers handle this issue as there are many things that need to be considered before making any major changes to the page . So I only fixed the anchors tags at the top of the page that were broken .
