### ISSUE TITLE
Issue with "Set": Demo code throws unexpected errors due to variable declarations

### ISSUE THREAD

**Issue by Ctrl-Alt-Zen** [mdn/content#2263]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

#### What information was incorrect, unhelpful, or incomplete?

The demonstration code threw uncaught errors. Variables were undeclared or referenced inconsistently.

#### Specific section or headline?

/*demo code quoted below throws several errors, mySet2  and set1, set2 are not declared */

mySet2 = new Set([1, 2, 3, 4])  
mySet2.size                    // 4
[...mySet2]                    // [1, 2, 3, 4]

// intersect can be simulated via
let intersection = new Set([...set1].filter(x => set2.has(x)))

// difference can be simulated via
let difference = new Set([...set1].filter(x => !set2.has(x)))

#### What did you expect to see?

//correction 1

let mySet2 = new Set([1, 2, 3, 4])  
console.log(mySet2.size)                    // 4
console.log([...mySet2])                    // [1, 2, 3, 4]

//correction 2

// intersect can be simulated via
let intersection = new Set([...mySet].filter(x => mySet2.has(x)))

// difference can be simulated via
let difference = new Set([...mySet].filter(x => !mySet2.has(x)))

#### Did you test this? If so, how?

ran demo code and corrected code on 
https://jscomplete.com/playground
produced correct console output after corrections were put in

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/set/index.html
* Last commit: https://github.com/mdn/content/commit/2ef7bb784bf1036ad7886b64e6451a68e573a44b
* Document last modified: 2021-01-15T08:25:52.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update it 👍

**Comment by Ctrl-Alt-Zen** [comment]
The rest of the tutorial was super helpful, thanks for quick response 🙂

**Comment by CreaTorAlexander** [comment]
I know it throws an error, but I think the console.logs shouldn't be in the example. @chrisdavidmills will console.logs() placed in examples?

**Comment by Ctrl-Alt-Zen** [comment]
console.log(mySet)   

... is used earlier in the same Set tutorial code. Not really a concern of mine one way or other, just following the example above from the same article.

Also not personally opinionated about mySet vs mySet1 etc but the code MUST compile

**Comment by CreaTorAlexander** [comment]
Well, in my PR I put it inside console.log()`s. I named it now mySet1 and mySet2. I think it is not a good name scheme to call the variables mySet and mySet2.

**Comment by Ctrl-Alt-Zen** [comment]
Good fix, and you're right that "mySet, mySet2" isn't very intuitive

**Comment by CreaTorAlexander** [comment]
@Ctrl-Alt-Zen I have updated the commit and I decided now to remove the `console.log's` from the example. The reason was at the mySet1 example there weren't any logs when showing has or size.
```
mySet1.has(o)       // true

mySet1.size         // 5
```
It is probably because it looks cleaner in the examples and th // indicates that here is a console.log.

But it is a good question when to use logs in the examples and when not but to answer this we have to ask a technical writer.

@Elchi3 can you answer this?

**Comment by Ryuno-Ki** [comment]
I think, I've seen `// => 5` as a notation to demark expected console outputs a few years ago.

**Comment by Elchi3** [comment]
> It is probably because it looks cleaner in the examples and the _//_ indicates that here is a _console.log_.
> 
> But it is a good question when to use logs in the examples and when not but to answer this we have to ask a technical writer.
> 
> @Elchi3 can you answer this?

I've avoided `console.log` in pure JS code blocks as well. I think the comments are sufficient enough as you say.
Only when showing code in an HTML code example (so JS inside `<script>`), I've made sure to use `console.log`.
