### ISSUE TITLE
The example provided on the page: borderify, doesn't work in firefox. Works on chromium though.

### ISSUE THREAD

**Issue by bshyamkumar** [mdn/content#22646]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

### What specific section or headline is this issue about?

Example doesn't work

### What information was incorrect, unhelpful, or incomplete?

I am a newbie to extension development. So, I have no idea what is wrong. However, it works on Chromium. So, I suspect something is incompatible with Firefox, or something in my firefox settings is not compatible with this extension. (Other extensions work fine.)

### What did you expect to see?

I expected to see a red border when I navigate to mozilla.org

### Do you have any supporting links, references, or citations?

No

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/your_first_webextension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/your_first_webextension/index.md
* Last commit: https://github.com/mdn/content/commit/ccb4006f14df723bf3bf6952bdbab03e31e65067
* Document last modified: 2022-09-27T22:35:00.000Z

</details>

**Comment by rebloor** [comment]
@bshyamkumar I have tested the extension on Firefox 107, and it works as expected. If you're still having issues, I suggest you post a query on the [Add-ons forum](https://discourse.mozilla.org/c/add-ons).
