### ISSUE TITLE
Object.preventExtension is not different from seal or freeze with respect to prevent changing [[prototype]]

### ISSUE THREAD

**Issue by jho1965us** [mdn/content#22642]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

Unlike [Object.seal()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal) and [Object.freeze()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze), Object.preventExtensions() invokes an intrinsic

### What did you expect to see?

Like instead of unlike

### Do you have any supporting links, references, or citations?

In Chrome console both

    Object.setPrototypeOf(Object.freeze({}),{})

and

    Object.setPrototypeOf(Object.seal({}),{})

throws

    TypeError: #<Object> is not extensible

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/preventextensions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/preventextensions/index.md
* Last commit: https://github.com/mdn/content/commit/9e52d335675a9f7daa34b5e24c9b1292dbf23b2e
* Document last modified: 2022-10-31T06:22:03.000Z

</details>

**Comment by Josh-Cena** [comment]
> Unlike [`Object.seal()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal) and [`Object.freeze()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze), `Object.preventExtensions()` invokes an intrinsic JavaScript behavior and cannot be replaced with a composition of several other operations.

This means:

1. `Object.preventExtensions()` invokes an intrinsic JavaScript behavior and cannot be replaced with a composition of several other operations.
2. [`Object.seal()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal) and [`Object.freeze()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) do not directly correspond to an intrinsic behavior, and can be replaced with a composition of several other operations. Indeed, they can be trivially implemented with `Object.preventExtensions()` + `Object.getOwnPropertyDescriptor()` + `Object.defineProperty()`.

I don't really see how it can be interpreted as if they don't prevent extensions: it's only saying they "can be replaced with a composition of several other operations".

**Comment by Josh-Cena** [comment]
Closing, because I think the current text is correct and can't find a better way to frame it.
