### ISSUE TITLE
Conflicting information in `USBDevice.controlTransferIn()` and `USBDevice.controlTransferOut()`

### ISSUE THREAD

**Issue by vajahath** [mdn/content#22652]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/USBDevice

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/USBDevice#:~:text=USBDevice.controlTransferIn()

### What information was incorrect, unhelpful, or incomplete?

On the main page, it says

> [USBDevice.controlTransferIn()](https://developer.mozilla.org/en-US/docs/Web/API/USBDevice/controlTransferIn) Experimental
Returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that resolves with a [USBInTransferResult](https://developer.mozilla.org/en-US/docs/Web/API/USBInTransferResult) when a command or status operation has been transmitted **to the USB device.**

On the [USBDevice.controlTransferIn()](https://developer.mozilla.org/en-US/docs/Web/API/USBDevice/controlTransferIn) page it says:

> The controlTransferIn() method of the [USBDevice](https://developer.mozilla.org/en-US/docs/Web/API/USBDevice) interface returns a [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that resolves with a [USBInTransferResult](https://developer.mozilla.org/en-US/docs/Web/API/USBInTransferResult) when the result of a command or status request has been received **from the USB device**.

I'm having difficulty in understanding which is correct.

The same is applicable in the `USBDevice.controlTransferOut()` section as well.

Also please verify all the `USBDevice.xxxxxOut` and `USBDevice.xxxxxIn` methods in that page.

### What did you expect to see?

Information in both pages should be in sync and correct

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/usbdevice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/USBDevice
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/usbdevice/index.md
* Last commit: https://github.com/mdn/content/commit/758b1253ca3478c06a1a575965fd32ac1e2bdda2
* Document last modified: 2022-11-15T16:45:25.000Z

</details>

**Comment by hamishwillee** [comment]
@vajahath Thanks for posting - you're absolutely correct. I fixed up the in/out pages in #22670
