### ISSUE TITLE
Save the Day the link is broken

### ISSUE THREAD

**Issue by kylepl** [mdn/content#22669]
### MDN URL

https://developer.mozilla.org/en-US/docs/Games/Examples

### What information was incorrect, unhelpful, or incomplete?

[Save the Day](https://ga.me/games/save-the-day) is broken.

### What did you expect to see?

A working link.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/games/examples`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Examples
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/examples/index.md
* Last commit: https://github.com/mdn/content/commit/23aed0231c16d44b6e77a5c7c032ed099a30c1f1
* Document last modified: 2022-09-07T09:02:05.000Z

</details>

**Comment by kylepl** [comment]
So is Polycraft.

**Comment by Tomi-3-0** [comment]
Could you shed more light on your issue

**Comment by jasonjg** [comment]
[ga.me](https://ga.me/) has a message on its homepage that the site is offline.

**Comment by kylepl** [comment]
I don't have any knowledge of where it should be. If there is no obvious
replacement, I would just remove the affected games and their links.
