### ISSUE TITLE
navigator.permissions.query({name:'camera'}) is not working in Safari and Firefox

### ISSUE THREAD

**Issue by vikasm98** [mdn/content#22663]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/permissions

### What specific section or headline is this issue about?

navigator.permissions.query({name:'camera'})

### What information was incorrect, unhelpful, or incomplete?

when I use this `navigator.permissions.query({name:'camera'})` in Safari(version 14.1.2 ) it is showing Error
```
Unhandled Runtime Error
TypeError: undefined is not an object (evaluating 'navigator.permissions.query')
```

 and in FireFox (version 107.0.1) it is showing the Error
` TypeError: 'camera' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.`

### What did you expect to see?

I would expect this method `navigator.permissions.query({name:'camera'})` working in safari and Firefox in both mobile and desktop browsers

### Do you have any supporting links, references, or citations?

<img width="1018" alt="Screenshot 2022-12-01 at 8 42 47 PM" src="https://user-images.githubusercontent.com/104773175/205088836-e4a02949-ede0-4346-b6a4-8d1c9f7394f8.png">
<img width="1018" alt="Screenshot 2022-12-01 at 8 43 04 PM" src="https://user-images.githubusercontent.com/104773175/205088902-a34051dc-ada4-49d1-9b36-b418666d9652.png">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/permissions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/permissions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/permissions/index.md
* Last commit: https://github.com/mdn/content/commit/4b4638246aad5d39b9a2e5c572b179b4c39c0a84
* Document last modified: 2022-09-09T05:17:24.000Z

</details>

**Comment by hamishwillee** [comment]
The page is correct. It indicates that the `navigator.permissions` can be used to query for permissions. What permissions are supported is covered in the object that this property returns. YOu can see that `camera` is not supported in Firefox and Safari if you follow the link to the https://developer.mozilla.org/en-US/docs/Web/API/Permissions object.

Thanks for posting!
