### ISSUE TITLE
[WebExtensions] webRequest.onBeforeRequest example is outdated

### ISSUE THREAD

**Issue by caugner** [mdn/content#22679]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest#examples

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The section says:

> This code cancels requests for images that are made to URLs under "https://mdn.mozillademos.org/" (to see the effect, visit any page on MDN that contains images, such as [webRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest)):

However, we're no longer referencing images via mdn.mozillademos.org in content (it's discouraged and we'll decomission that domain at some point), so the example no longer works.

### What did you expect to see?

Maybe the domain in the example could simply be replaced by `developer.mozilla.org`, as the example only blocks images. 🤔 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/webrequest/onbeforerequest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/webrequest/onbeforerequest/index.md
* Last commit: https://github.com/mdn/content/commit/4b10cb28d5eee0e952b2d84bd1b23cc53daa93b7
* Document last modified: 2022-11-30T17:53:16.000Z

</details>

**Comment by niloysikdar** [comment]
Hi @caugner @sideshowbarker, I would like to work on this issue. It'll be really great if you can assign me this issue.

**Comment by niloysikdar** [comment]
Hi @sideshowbarker, I have opened a Pull Request (#22694) with the fixes. Can you check once if everything is fine?
