### ISSUE TITLE
The page should include that, if the user holds down the Shift key the context menu will be displayed

### ISSUE THREAD

**Issue by def00111** [mdn/content#22697]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event

### What information was incorrect, unhelpful, or incomplete?

Any right-click event that is not disabled (by calling the event's [preventDefault()](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) method) will result in a contextmenu event being fired at the targeted element.

### What did you expect to see?

Maybe something like this: "In Firefox, if the user holds down the Shift key while opening the context menu will not prevent it from opening."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/contextmenu_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/contextmenu_event/index.md
* Last commit: https://github.com/mdn/content/commit/1732201134d732af9bfd49ee9e10f7e2086cc783
* Document last modified: 2022-10-14T07:09:52.000Z

</details>

**Comment by hamishwillee** [comment]
> Any right-click event that is not disabled (by calling the event's [preventDefault()](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) method) will result in a contextmenu event being fired at the targeted element.

> Maybe something like this: "In Firefox, if the user holds down the Shift key while opening the context menu will not prevent it from opening."

1. The two statements above appear to have nothing to do with each other.
2. I don't know what the second statement means (the English is broken)

Are you saying
- normally if you do a right click the context menu will be displayed
- but on firefox if you hold down the shift key and do a right click the context menu is not displayed? Or something else?

**Comment by aloopuri** [comment]
I think he's trying to say the opposite.

In the example given at the bottom of the page, you cannot open the context menu with right-click on the first paragraph. But on firefox if you use shift+right-click on it, you can still open the context menu even if it has been disabled.
