### ISSUE TITLE
[page types] Define page types for HTML

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#22705]
Part of https://github.com/mdn/content/issues/15539.

In https://docs.google.com/spreadsheets/d/14RX8EEKPpeYkP2cF5Y_ZKF3JpNJ_24OL7stvZWNJLIY/edit#gid=2083448819, in the "HTML" tab, I've listed every page under https://developer.mozilla.org/en-US/docs/Web/HTML and made an initial determination about the page type.

Apart from the generic "guide" and "landing page" types, I have come up with just:

```
HTML attribute (52)
HTML attribute value (11)
HTML element (156)
```

In the IA attributes are a mess, we have them in at least three places:
- global attributes under https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes
- some non-global attributes under https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
- some other non-global attributes under some element

Some day we should sort this out but I don't think it affects page types.
From a page types perspective, I opted not to have a separate type for "global attributes". AFAICT they are structurally the same, they just apply to a different set of elements.

I opted to call input types "HTML element" to align with the general fiction we have of treating them as individual elements. I think this is a reasonable approach although we do have an organizational problem that they live under another element page. This is especially confusing since we also have some attributes under element pages.

An alternative I suppose could be to call input types "HTML attribute value" pages, which is technically correct. But it is perhaps less helpful.

******

BTW I wanted to do this now because removing [one of the places we use tags](https://github.com/mdn/yari/blob/2720d1f9998be94428a822dcc06946d6a53879d0/kumascript/macros/CSSInfo.ejs#L44) depends on having HTML element page types.

**Comment by hamishwillee** [comment]
@wbamberg Sounds reasonable; nothing you're proposing here makes things "any worse".

Would a new page **HTML > Script > type** be "HTML attribute" page type? I am actually considering doing the page **HTML > Script > type > importmap** for the JSON import map format - Presume I can call that page a "HTML attribute value"

**Comment by wbamberg** [comment]
> @wbamberg Sounds reasonable; nothing you're proposing here makes things "any worse".
> 
> Would a new page **HTML > Script > type** be "HTML attribute" page type? I am actually considering doing the page **HTML > Script > type > importmap** for the JSON import map format - Presume I can call that page a "HTML attribute value"

Yes, exactly. When I was looking at this I was thinking about the importmap problem, and was pleased to see that there seemed to be some precedent for this option.

**Comment by teoli2003** [comment]
I'm 100% with the OP. I think the page types make sense, and the two problems (IA of attributes, and page types of <input type>) can be solved like this today until we tackle them independently.
