### ISSUE TITLE
Issue with "Replaced Element": stub page from wiki migration

### ISSUE THREAD

**Issue by nschonni** [mdn/content#2270]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Replaced_Element

#### What information was incorrect, unhelpful, or incomplete?

Looks like a stub generated from the old Wiki setup. Not sure if it should just be deleted till content is added

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/replaced_element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Replaced_Element
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/svg/replaced_element/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by Ryuno-Ki** [comment]
This page actually is referenced in the `_wikihistory.json` with a list of contributors:

* kscarfone => @kscarfone
* Jeremie => 1.521 results, so I'm not tagging.
* ethertank => @ethertank
* Anonymous

Do you remember what you did on 16th January 2019 when this page was created?

**Comment by teoli2003** [comment]
I created the PR as this skipped through.

I would say that this page is much older than 2019, given the 3 authors. (And Jeremie is @JeremiePat , the former SVG leader on MDN)
