### ISSUE TITLE
malware evidence or my fakin misery life?

### ISSUE THREAD

**Issue by chaosrestricted** [mdn/content#22739]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed

### What specific section or headline is this issue about?

 Cross-Origin Request Blocked:

### What information was incorrect, unhelpful, or incomplete?

Basic function 'Transfer Domain' is read only. From this state I evaluate that none function work properly. I decide to inspect and first picture of dashboard confess that this web is abusing and trying to manipulate.
Content seems ugly and messy. Very hard operated instead the simple and clear instructions, since non operational. Articles I had spotted missing. 

### What did you expect to see?

The truly internet.

### Do you have any supporting links, references, or citations?

ross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cloudflare.zendesk.com/embeddable/config. (Reason: CORS request did not succeed). Status code: (null)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/cors/errors/corsdidnotsucceed`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/errors/corsdidnotsucceed/index.md
* Last commit: https://github.com/mdn/content/commit/0c410538f50487e8b0f419e11e24ad5adb60bf36
* Document last modified: 2022-11-23T00:02:38.000Z

</details>

**Comment by schalkneethling** [comment]
@chaosrestricted, please note that we have dozens of people watching this repository. For every comment posted, or issue opened, these people may receive a notification.

Please be respectful of other people’s time and attention, and avoid taking actions that might cause excessive notifications. Issues should describe a problem or propose an actionable solution. Please use the [MDN Web Docs feedback repository](https://github.com/mdn/feedback/discussions) if a discussion is needed.

Also, please remember that the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) govern all participation in these open spaces. We enforce these to maintain a healthy and inviting community experience for everyone.

It is unclear from your description what problem your are reporting. Our issues are meant for clearly defined bugs that are reproducible and actionable. If you are having problems using `fetch`, `XMLHTTPRequest`, or `CORS` in general, we would suggest you post the question on [StackOverflow](https://stackoverflow.com) as that is a more appropriate channel when asking for help with code.

If there is something specific on the https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed page that is incorrect, please try to reword your description to point to the exact problem and your suggestion for how we could help.

**Comment by Josh-Cena** [comment]
This seems like one of those "malware" spam posts.
