### ISSUE TITLE
[CSS] Enable container queries on Nightly

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#22735]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Work has been done around this and as it's a 'feature group' there may not be any bcd or rel notes per se, but worth checking

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1801123

## Related issues and pull requests

- [x] content https://github.com/mdn/content/pull/22766
- [x] BCD https://github.com/mdn/browser-compat-data/pull/18379

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by bsmth** [comment]
We mention container query length units: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#container_query_length_units

We can make this more generic to "container queries" and mention the units as part of this feature flag.

-[ ] Update experimental features to say that it's enabled in Nightly by default in 109

**Comment by bsmth** [comment]
Closing this one as done now ✅
