### ISSUE TITLE
[CSS] Enable mod() and rem() functions

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#22734]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Assuming part of css functions general work, but bcd and release note will be needed

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1785117

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by ramiy** [comment]
Documenting [[css-value-4]](https://w3c.github.io/csswg-drafts/css-values/#round-func) `rem()` and `mod()` functions:

**mdn/browser-compat-data:**

* CSS `rem()` - https://github.com/mdn/browser-compat-data/pull/17872
* CSS `mod()` - https://github.com/mdn/browser-compat-data/pull/17873

**mdn/content:**

* CSS `rem()` - https://github.com/mdn/content/pull/23183
* CSS `mod()` - 

**mdn/data:**

* Syntax - https://github.com/mdn/data/pull/593

**Comment by ramiy** [comment]
@Rumyra @dipikabh I need your help merging the two BCD prs.

**Comment by dipikabh** [comment]
> @Rumyra @dipikabh I need your help merging the two BCD prs.

Looks like they've already been merged now

**Comment by ramiy** [comment]
All the pull requests were merged. You can close this issue.

**Comment by Rumyra** [comment]
Thanks @ramiy 👍
