### ISSUE TITLE
Misprint in https://developer.mozilla.org/ru/docs/Web/Guide/CSS/Visual_formatting_model page

### ISSUE THREAD

**Issue by b0risfen** [mdn/content#2274]
In the link (and chapter title) https://developer.mozilla.org/ru/docs/Web/Guide/CSS/Visual_formatting_model#%D0%B1%D0%BB%D0%BE%D1%87%D0%BD%D1%8B%D0%B5_%D1%8D%D0%BA%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B_%D0%B8_%D0%B1%D0%BB%D0%BE%D0%BA-%D0%B1%D0%BE%D0%BA%D1%81%D1%8B
wrote "эклементы" instead of correct "элементы
![Screenshot](https://user-images.githubusercontent.com/77898301/107578572-94f5cf00-6bfc-11eb-8470-5fc8b46d9fe3.jpg)
"

**Comment by Ryuno-Ki** [comment]
Thank you for reporting. Sadly, Russian translations aren't updated for now.
See https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
