### ISSUE TITLE
Erroneous description of EPSILON

### ISSUE THREAD

**Issue by EricPostpischil** [mdn/content#22759]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/EPSILON

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

The text says of EPSILON, which has the value 2^-52, “This is the smallest value that can be added to 1 to get a distinct number,…” This is incorrect; adding (2^-53+2^-105) to 1 will yield a distinct number, due to rounding. EPSILON would be correctly defined as the difference between 1 and the next representable number.

### What did you expect to see?

“This is the difference between 1 and the next greater number representable in the Number format,…”

### Do you have anything more you want to share?

Observe the JavaScript code “console.log(1.3e-16 + 1)” prints “1.0000000000000002”, showing the result of the addition is distinct from 1 even though 1.3e-16 is less than EPSILON (about 2.22e-16).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/number/epsilon`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/EPSILON
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/number/epsilon/index.md
* Last commit: https://github.com/mdn/content/commit/1385fea4712555f57e501269381951c613839fd7
* Document last modified: 2022-11-21T15:42:30.000Z

</details>

**Comment by Josh-Cena** [comment]
Makes sense to me. Do you want to send a PR?

**Comment by EricPostpischil** [comment]
> Makes sense to me. Do you want to send a PR?

Sorry, I looked at the contribution guide and balked at the number of documents referred to (code of conduct, MDN guidelines, writing style guide, etiquette, and more) plus indications I ought to install Node.js and Yarn so that I can build the site and check changes. Too much for a one-time minor correction. Although now I see a simplified procedure under “Simple changes,” so I could take a stab at it. But I am okay if somebody else does it; I do not need credit or anything.

				— edp (Eric Postpischil)
				https://edp.org

… then anyone who leaves behind him a written manual, and likewise anyone who receives it, in the belief that such writing will be clear and certain, must be exceedingly simple-minded… — Plato, in Phaedrus
