### ISSUE TITLE
[page types] Define page types for HTTP

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#22761]
Part of https://github.com/mdn/content/issues/15539.

In https://docs.google.com/spreadsheets/d/14RX8EEKPpeYkP2cF5Y_ZKF3JpNJ_24OL7stvZWNJLIY/edit#gid=2083448819, in the "HTTP" tab, I've listed every page under https://developer.mozilla.org/en-US/docs/Web/HTTP and made an initial determination about the page type.

I've come up with the following types:

```
guide                                      38
HTTP content security policy directive     31
HTTP CORS error                            15
HTTP feature policy directive              29
HTTP header                               121
HTTP header attribute                       1
HTTP method                                 9
HTTP status code                           54
landing page                                4
```

I'm a bit unhappy that we have a single "HTTP header attribute" page, which is https://developer.mozilla.org/en-US/docs/web/http/headers/set-cookie/samesite. I wonder if we could fold it into https://developer.mozilla.org/en-US/docs/web/http/headers/set-cookie.

Otherwise this seems like a reasonable list.

**Comment by teoli2003** [comment]
> I'm a bit unhappy that we have a single "HTTP header attribute" page, which is https://developer.mozilla.org/en-US/docs/web/http/headers/set-cookie/samesite. I wonder if we could fold it into https://developer.mozilla.org/en-US/docs/web/http/headers/set-cookie.

Yes, this page is difficult to navigate from and to.

I don't think we can fold it entirely into `set-cookie`, but I think we can deal with it by:
1. Checking/Updating `set-cookie` to describe the modern value
2. Merge the sections about dealing with problems into the guide about [HTTP Cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies), eventually adding a second part specific to same-site cookies.

**Comment by wbamberg** [comment]
> I don't think we can fold it entirely into `set-cookie`, but I think we can deal with it by:
> 
>     1. Checking/Updating `set-cookie` to describe the modern value
> 
>     2. Merge the sections about dealing with problems into the guide about [HTTP Cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies), eventually adding a second part specific to same-site cookies.

I like this plan!

**Comment by teoli2003** [comment]
I think we can move forward with this plan.

Just listing the entries here as checkboxes so we can track progress:

- [ ] Update meta docs about these types
- [ ] `guide` – 38 pages
- [ ] `http-csp-directive` (HTTP content security policy directive) – 31 pages
- [ ] `http-cors-error` (HTTP CORS error) – 15 pages
- [ ] `http-feature-policy-directive (HTTP feature policy directive) – 29 pages
- [ ] `http-header`(HTTP header) – 121 pages
- [ ] Special case for `set-cookie`
- [ ] `http-method`(HTTP method) – 9 pages
- [ ] `http-status-code` (HTTP status code) – 54 pages
- [ ] landing page

**Comment by wbamberg** [comment]
@teoli2003 I have a dodgy script I can use to apply the page-type values we have agreed. The main thing blocking this is set-cookie - if you wanted to resolve this per https://github.com/mdn/content/issues/22761#issuecomment-1339897136 that would be great.

**Comment by wbamberg** [comment]
With https://github.com/mdn/content/pull/26102 merged, we can close this issue.
