### ISSUE TITLE
Misleading text in calc() doc

### ISSUE THREAD

**Issue by jharrilim** [mdn/content#22805]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/calc

### What specific section or headline is this issue about?

The first paragraph

### What information was incorrect, unhelpful, or incomplete?

The statement:

> It can be used anywhere a [`<length>`](https://developer.mozilla.org/en-US/docs/Web/CSS/length), [`<frequency>`](https://developer.mozilla.org/en-US/docs/Web/CSS/frequency), [`<angle>`](https://developer.mozilla.org/en-US/docs/Web/CSS/angle), [`<time>`](https://developer.mozilla.org/en-US/docs/Web/CSS/time), [`<percentage>`](https://developer.mozilla.org/en-US/docs/Web/CSS/percentage), [`<number>`](https://developer.mozilla.org/en-US/docs/Web/CSS/number), or [`<integer>`](https://developer.mozilla.org/en-US/docs/Web/CSS/integer) is allowed.

There is a caveat in which `calc()` cannot be used as a number. [If we take a look at the syntax for percentage](https://developer.mozilla.org/en-US/docs/Web/CSS/percentage#syntax), we'll see that it states:

> The `<percentage>` data type consists of a [`<number>`](https://developer.mozilla.org/en-US/docs/Web/CSS/number) followed by the percentage sign (%).

If you were to try to substitute `<number>` with a calc expression, such as:

```css
.class {
  background-position: calc(100 / 200 * 3)%;
}
```

It would not be valid.

### What did you expect to see?

A mention of this caveat, and likely the removal of the word "anywhere".

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/CSS/percentage#syntax

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/calc`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/calc
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/calc/index.md
* Last commit: https://github.com/mdn/content/commit/6be1b954a117202d7635caeec74ebbbde984d3f3
* Document last modified: 2022-09-26T22:47:43.000Z

</details>

**Comment by bsmth** [comment]
Thanks @jharrilim I agree that `anywhere` is ambiguous. I'll open a PR to address this 👍🏻
