### ISSUE TITLE
Implement onscrollend event handler

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#22814]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

onscrollend

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1797013
https://bugzilla.mozilla.org/show_bug.cgi?id=1803435

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

https://github.com/mdn/mdn/issues/252

## Related pull requests and issues

- [x] Content https://github.com/mdn/content/pull/22894
- [x] BCD https://github.com/mdn/browser-compat-data/pull/18407
- [x] Relnote (Experimental) https://github.com/mdn/content/pull/22904

**Comment by bsmth** [comment]
__Resources:__
- https://chromestatus.com/feature/5186382643855360
- https://drafts.csswg.org/cssom-view/#scrolling

__Related pull requests:__
- [x] https://github.com/whatwg/html/pull/8433

__Bugzilla:__
- [ ] landed in Fx 108 https://bugzilla.mozilla.org/show_bug.cgi?id=1797013

**Comment by dlrobertson** [comment]
FWIW I just landed the change to enable scrollend events by default, see [bug 1797013](https://bugzilla.mozilla.org/show_bug.cgi?id=1797013).

**Comment by bsmth** [comment]
This is complete for 108 including nightly & experimental release notes.

For Fx 109 stable release, we need to move out the experimental note into the release notes.

**Comment by dlrobertson** [comment]
> This is complete for 108 including nightly & experimental release notes.
> 
> For Fx 109 stable release, we need to move out the experimental note into the release notes.

:+1: just read the MDN doc and it looks great! Thanks!

**Comment by bsmth** [comment]
Closing this one as done now ✅
