### ISSUE TITLE
populatedb.js file link broken

### ISSUE THREAD

**Issue by mishalp** [mdn/content#22816]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

### What specific section or headline is this issue about?

Testing — create some items

### What information was incorrect, unhelpful, or incomplete?

in the "Testing — create some items" section the link for populatedb.js not working

### What did you expect to see?

able to download populatedb.js

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/279b00edfd26006afcb6b1e2293350c4b333ab10
* Document last modified: 2022-10-31T01:01:07.000Z

</details>

**Comment by hamishwillee** [comment]
What error are you seeing when you try it? I'll test it out next week.

I understand MongoDb may have made some changes that could be causing this problem.

**Comment by mishalp** [comment]
I found the solution, it is the problem of github CDN , the domain of the link is changed from "githubusercontent.com" to "githack.com" . So I opened a PR to solve this issue #22834. Hope you will accept the PR

**Comment by Josh-Cena** [comment]
Closing per https://github.com/mdn/content/pull/22834#issuecomment-1344850758; the link is working for me as well. It would be weird if `raw.githubusercontent.com` stopped working.
