### ISSUE TITLE
http.headers.Sec-Fetch-User - Values Description

### ISSUE THREAD

**Issue by Simbiat** [mdn/content#2283]
#### What information was incorrect, unhelpful, or incomplete?
Values for the header have incorrect (switched) descriptions

#### What did you expect to see?
As per https://www.w3.org/TR/fetch-metadata/#sec-fetch-user-header if user activated requested, the header should report `?1`, but description says, that this is the case for `?0`

#### Did you test this? If so, how?
Did not test this specifically, but regular navigations in Edge 88 do report `?1`

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Sec-Fetch-User`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-User
* Report started: 2021-02-11T13:48:52.670Z

</details>

**Comment by Simbiat** [comment]
It is, yes, but I did not find the link to report it that way on the page, so used the one clearly available (=  Sorry for any inconvenience.

**Comment by CreaTorAlexander** [comment]
I can update it 👍

**Comment by Ryuno-Ki** [comment]
@CreaTorAlexander it's yours!
