### ISSUE TITLE
Example leads to an error

### ISSUE THREAD

**Issue by Budescu-Eftimie** [mdn/content#22835]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

Trying to run the for loop example lead to an error:
<blockquote>Uncaught ReferenceError: a is not defined</blockquote>
<p>
In the example provided inside the console.log on the left side of the = operator **a** is outside of the embedded expression while on the right side of the = operator **a** is inside the embedded expression.</p>
<pre class="brush: js notranslate"><code><span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">,</span> j <span class="token operator">=</span> <span class="token number">9</span><span class="token punctuation">;</span> i <span class="token operator">&lt;=</span> <span class="token number">9</span><span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">,</span> j<span class="token operator">--</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">a[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>i<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">][</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>j<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">] = </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>a<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">[</span>j<span class="token punctuation">]</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre>

### What did you expect to see?

a successful, accessible example

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/comma_operator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/comma_operator/index.md
* Last commit: https://github.com/mdn/content/commit/0ad08fe1d8830f11e0314733f56e391affc1fe94
* Document last modified: 2022-11-17T13:58:24.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, the value of `a` is elided in this example. You can trivially fix it by providing an array yourself.

**Comment by Budescu-Eftimie** [comment]
Hello, ok.
I provided the following array:
const a = [[0,1,2,34,5,6,7,8,9],[0,1,2,34,5,6,7,8,9]]

It does not work.
It's my array wrong?
What should the array look like ?



vin., 9 dec. 2022, 06:07 Joshua Chen ***@***.***> a scris:

**Comment by Josh-Cena** [comment]
It's a diagonal matrix that iterates from 0 to 9, so you need to provide a 10×10 matrix.

```js
const a = Array.from({ length: 10 }, () => Array.from({ length: 10 }, Math.random));
```

**Comment by Budescu-Eftimie** [comment]
You are right. Thank you.
