### ISSUE TITLE
Use `gap` instead of `margin`.

### ISSUE THREAD

**Issue by joaojgabriel** [mdn/content#22855]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox

### What specific section or headline is this issue about?

Split navigation

### What information was incorrect, unhelpful, or incomplete?

Verbatim:
"we are using margins on the flex items to create a gap between items, and a negative margin on the container in order that the items still remain flush with the right and left edges. Until the `gap` properties from the Box Alignment specification are implemented in flexbox, we have to use margins in this way if we want to create a gutter between items."

Then, in the example:
```css
nav ul {
  display: flex;
  margin: 0 -10px;
}

nav li {
  margin: 0 10px;
}
```

### What did you expect to see?

```css
nav ul {
  display: flex;
  gap: 20px;
}
```

It seems as if `gap` has already been implemented in Flexbox; even the [isolated Webkit bug](https://bugs.webkit.org/show_bug.cgi?id=225278) was apparently resolved.

### Do you have any supporting links, references, or citations?

[Can I use Flexbox gap](https://caniuse.com/flexbox-gap)

### Do you have anything more you want to share?

I'm only a beginner and don't yet feel comfortable on suggesting changes that involve specs directly, so the issue is to anyone who does, look into and maybe change it if they see fit.

**Comment by wbamberg** [comment]
See also https://github.com/mdn/content/issues/23221.
