### ISSUE TITLE
Incorrect use of the word "parallel" in documentation about Promises

### ISSUE THREAD

**Issue by eduarddejong** [mdn/content#22867]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises

### What specific section or headline is this issue about?

Multiple sentences talking about executing Promises "in parallel"

### What information was incorrect, unhelpful, or incomplete?

Hi! I am reading the pages about Promises in JavaScript, in order to get better understanding of this feature of JavaScript.
But I am also reading multiple sources elsewhere on the internet about concurrency and parallelism, and what people say about JavaScript.

As far as I understand, JavaScript is really a single-threaded language. With the only exception of the so called "Web Workers API", but which is a very different thing.

Promises are just asynchronous operations all within the same thread.

According to Wikipedia (https://en.wikipedia.org/wiki/Concurrent_computing), there's an important difference between the definitions of the words "concurrent" and "parallel":
"In parallel computing, execution occurs at the same physical instant: for example, on separate processors of a multi-processor machine, with the goal of speeding up computations—parallel computing is impossible on a (one-core) single processor, as only one computation can occur at any instant (during any single clock cycle).[a] By contrast, concurrent computing consists of process lifetimes overlapping, but execution need not happen at the same instant."

To clarify: 1 thread means using 1 CPU at the same time. So that means that true parallelism is impossible.

### What did you expect to see?

Update the documentation in such a way that it correctly explains that Promises run concurrently but not in parallel. 

### Do you have any supporting links, references, or citations?

https://en.wikipedia.org/wiki/Concurrent_computing
https://en.wikipedia.org/wiki/Parallel_computing

### Do you have anything more you want to share?

Correct me if I am wrong of course.
But if Promises really run in parallel, then JavaScript has to be multi-threaded and not single-threaded.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/using_promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/using_promises/index.md
* Last commit: https://github.com/mdn/content/commit/79f307ce6c91d661aa024addea2f6631f4853e47
* Document last modified: 2022-12-04T16:59:19.000Z

</details>

**Comment by chinu-anand** [comment]
Hi @Josh-Cena, I would like to work on this issue. I will be grateful for this.

**Comment by Josh-Cena** [comment]
@chinu-anand You can just go ahead and send the PR without being assigned, but I've assigned you anyway.
