### ISSUE TITLE
Issue with "<dialog>: The Dialog element": (short summary here please)

### ISSUE THREAD

**Issue by tamccullough** [mdn/content#2289]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

#### What information was incorrect, unhelpful, or incomplete?
I am running Firefox 85.0.1 (64-bit)
Ubuntu 20.02.2 LTS

`The <dialog> API is not supported by this browser`

#### Specific section or headline?
Doesn't function

#### What did you expect to see?
I expected to see the dialog popup

#### Did you test this? If so, how?
yes. Works in chrome.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/html/element/dialog/index.html
* Last commit: https://github.com/mdn/content/commit/bae04313dc3e19e4a5df529b97d5548c91f39b1f
* Document last modified: 2020-12-30T11:54:07.000Z

</details>

**Comment by chrisdavidmills** [comment]
Hi @tamccullough ! 

The browser compat table Firefox section includes a dropdown arrow — if you click that, it reveals the full information. Basically, we've supported it for a long time, but behind a flag in release (it's on by default in Nightly).

I'm closing this now, but feel free to chime in again if you've got more thoughts aobout this.

**Comment by tamccullough** [comment]
Hi. Thanks!

Sorry, I just discovered that I needed to set - dom.dialog_element.enabled - to true.
