### ISSUE TITLE
WASM spec links are broken

### ISSUE THREAD

**Issue by petercockerell-brt** [mdn/content#22908]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format

### What specific section or headline is this issue about?

The Simplest Module

### What information was incorrect, unhelpful, or incomplete?

There's an external link to the **binary format** of WASM, but it's broken. The link address is https://webassembly.github.io/spec/core/binary/index.html#high-level-structure.

### What did you expect to see?

Clicking the link to take me to a valid page. I got a 404 instead.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/webassembly/understanding_the_text_format`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/understanding_the_text_format/index.md
* Last commit: https://github.com/mdn/content/commit/d606f8dc936dcf766e1540f687eba8dc9dd9ed13
* Document last modified: 2022-09-19T05:46:09.000Z

</details>

**Comment by hamishwillee** [comment]
It's not just that link - almost everything on https://webassembly.github.io/ appears to be gone. I've asked whether this is temporary, and what the preferred alternative is in https://github.com/WebAssembly/spec/issues/1568

**Comment by ngzhian** [comment]
Huh, it could be some issue with this https://github.com/WebAssembly/spec/actions/runs/3678564687
Could be a accidental push. Let investigate.
