### ISSUE TITLE
[HTTP] Content Security Policy reports to include "effective-directive" and "status-code"

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#22907]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document
- Doc on MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#violation_report_syntax
- BCD and relnote to be updated

## Related Gecko bugs
https://bugzilla.mozilla.org/show_bug.cgi?id=1192684

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

__Related issues and pull requests:__

- [x] Content https://github.com/mdn/content/pull/23404
- [x] BCD https://github.com/mdn/browser-compat-data/pull/18557
- [x] Content (API pages) https://github.com/mdn/content/pull/23433

**Comment by bsmth** [comment]
Asked for clarification in bugzilla on scope for any outstanding changes (API / BCD) but relnote is done alongside content additions with example payloads for a CSP report body with these props.

**Comment by bsmth** [comment]
Closing for the moment as I don't see other outstanding work to be done for the moment. Any follow-up tasks taken from Bugzilla will be included and linked to from this issue. Omitting `dev-doc-complete` until there is a confirmation on the bug.
