### ISSUE TITLE
Obsolete code is referenced in the text

### ISSUE THREAD

**Issue by petercockerell-brt** [mdn/content#22909]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format

### What specific section or headline is this issue about?

Calling the function

### What information was incorrect, unhelpful, or incomplete?

In the paragraph that begins 

> Next, we'll load our binary into a typed...

this is no longer true. The code actually fetches the WASM and calls instantiateStreaming(). There is no longer an array called `addCode`.

### What did you expect to see?

A correct description of the code example.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/webassembly/understanding_the_text_format`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/understanding_the_text_format/index.md
* Last commit: https://github.com/mdn/content/commit/d606f8dc936dcf766e1540f687eba8dc9dd9ed13
* Document last modified: 2022-09-19T05:46:09.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/26934
