### ISSUE TITLE
Section on "relative selectors" mentions "anchor element" with incorrect link?

### ISSUE THREAD

**Issue by impressivewebs** [mdn/content#22917]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors

### What specific section or headline is this issue about?

Structure of a selector

### What information was incorrect, unhelpful, or incomplete?

The paragraph under "Relative selectors" says:

> A selector that represents an element relative to one or more anchor elements preceded by a combinator. Relative selectors that don't begin with an explicit combinator have an implied descendant combinator.

The words "anchor elements" is linked to [the page on pseudo-classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes). Is this a mistake? What is meant here by "anchor elements"? It doesn't seem to be the anchor element/tag (i.e. `<a>`). I'm not sure what it should be linked to or if the wording needs to be changed.

### What did you expect to see?

Not sure, the link is incorrect and the context is unclear as to what was meant.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_selectors/index.md
* Last commit: https://github.com/mdn/content/commit/2393cdd9715c0b42a575bf9b8f8c2d95457e5294
* Document last modified: 2022-11-04T23:04:38.000Z

</details>

**Comment by bsmth** [comment]
Thanks both. The linked pull request correctly addresses the problem, it should point to the anchor element.

**Comment by Sriparno08** [comment]
Welcome, @bsmth!

**Comment by impressivewebs** [comment]
@Sriparno08 @bsmth Ok, I see the PR. However, I don't think this addresses the original underlying problem: Why is the anchor element even mentioned in this context? This paragraph is discussing "relative selectors" and it says:

> A selector that represents an element relative to one or more anchor elements preceded by a combinator.

I don't think that's a correct description. Why are "relative" selectors only limited to use with the anchor element? Am I not understanding what is meant by "relative selector" here?

**Comment by bsmth** [comment]
Thanks @impressivewebs, you're right, the "anchor" is not referring to [`<a>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) at all, but has unfortunate overlap of terminology. The pseudo-classes page describes this:

>The element that a pseudo-class is attached to is defined as an anchor element (e.g., "button" in case `button:hover`).

The spec has [this example](https://drafts.csswg.org/selectors/#overview):

```css
E:has(rs1, rs2, …)
```

Which is described as

>an E element, if there exists an element that matches either of the [relative selectors](https://drafts.csswg.org/selectors/#relative-selector) rs1 or rs2, when evaluated with E as the [anchor elements](https://drafts.csswg.org/selectors/#relative-selector-anchor-elements)
