### ISSUE TITLE
structuredClone shows transferables as top-level argument rather than `transfer` option

### ISSUE THREAD

**Issue by glasser** [mdn/content#22942]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

The Syntax section (example and Parameters) shows that the "transferables" are provided as the second argument. But the examples in the "Transferring values" subsection, linked spec, and linked polyfills all suggest that this is in fact provided as a `transfer` option inside the second argument.

### What did you expect to see?

I think this array should be provided as `{ transfer: transferables }` instead of just `transferables`. But I've never heard of this function before so I'm not quite bold enough to file a PR.

### Do you have any supporting links, references, or citations?

The rest of the page. Everything linked from it.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/structuredclone`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/structuredClone
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/structuredclone/index.md
* Last commit: https://github.com/mdn/content/commit/16e398809d62247dbadc89ff4024a0ffa4781f0e
* Document last modified: 2022-09-13T06:27:50.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! I think you are right and if you want to file a PR to fix this I'd be happy to review it.

We'd need to fix not just the "Syntax" code block but also the parameter description, to say something like:

```
- `options` {{optional_inline}}
  - : An object with the following property:
    - `transfer`
      - : An array of [transferable objects](/en-US/docs/Glossary/Transferable_objects) ...
```
