### ISSUE TITLE
Detailed rundown of Web Storage capacities returns a "Site not found" error

### ISSUE THREAD

**Issue by hayleyashby7** [mdn/content#22948]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

The link highlighted below
![image](https://user-images.githubusercontent.com/15215740/207601487-867322a8-1b3f-45db-91e8-3383cb51012b.png)

goes to https://dev-test.nemikor.com/web-storage/support-test/ which is currently showing a "Site Not Found" error from DreamHost.
![image](https://user-images.githubusercontent.com/15215740/207602065-bc0bb262-6289-4d1e-b40f-37ff70135146.png)

### What did you expect to see?

It should link to a page showing a detailed rundown of all the storage capacities for various browsers for the Web Storage API

### Do you have any supporting links, references, or citations?

MDN page - https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#browser_compatibility

Broken link - https://dev-test.nemikor.com/web-storage/support-test/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_storage_api/using_the_web_storage_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_storage_api/using_the_web_storage_api/index.md
* Last commit: https://github.com/mdn/content/commit/c17005028352d193561ac44b0bdb09792773a687
* Document last modified: 2022-10-25T03:13:58.000Z

</details>

**Comment by dawei-wang** [comment]
The link works for me when I click on the text from the page. It may have been an issue on their end.

**Comment by sideshowbarker** [comment]
@hayleyashby7 I notice that in the issue description you state that the link goes to `https://dev-test.nemikor.com/web-storage/support-test/` — but I suspect you’re seeing that because you’re using an extension such as HTTP Everywhere that converts non-https links into https links.

The actual link in the article is to `http://dev-test.nemikor.com/web-storage/support-test/` (non-https), and as noted in https://github.com/mdn/content/issues/22948#issuecomment-1351921101, that URL works as expected.

So I’m going ahead and closing this, but feel free to comment further, and this issue could be revisited if needed.

**Comment by wbamberg** [comment]
@sideshowbarker , do you think this is a useful link? It says it's a link to "a detailed rundown of all the storage capacities for various browsers" but it seems to be a link to a page that asks me to run some unspecified tests on my browser, presumably so it can tell me the characteristics of my browser, which doesn't seem so useful in this context.

**Comment by sideshowbarker** [comment]
> @sideshowbarker , do you think this is a useful link? It says it's a link to "a detailed rundown of all the storage capacities for various browsers" but it seems to be a link to a page that asks me to run some unspecified tests on my browser, presumably so it can tell me the characteristics of my browser, which doesn't seem so useful in this context.

Good point — and on top of that, given it’s an insecure link to an obscure third-party site that we know nothing about, it seems prudent to remove it regardless.

Opened #23035 for that.
