### ISSUE TITLE
"the request's destination. This is a string indicating the type of content being requested."

### ISSUE THREAD

**Issue by mikemaccana** [mdn/content#22955]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Request

### What specific section or headline is this issue about?

Request.destination

### What information was incorrect, unhelpful, or incomplete?

It seems very unlikely that "the request's destination" indicates "the type of content being requested". I suspect this is an error but am unsure.

### What did you expect to see?

Not sure. "destination" doesn't sound like content type but "url" is already the destination.

### Do you have anything more you want to share?

Thanks for reading!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/request`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Request
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/request/index.md
* Last commit: https://github.com/mdn/content/commit/06105598d11001e9f12d80ad05087f1df3c0634b
* Document last modified: 2022-10-10T09:00:13.000Z

</details>

**Comment by evilpie** [comment]
The description is correct. For example the request "destination" of an <img> tag's `src` is always an "image", because that is only type of content it can be used for.

I agree the name destination might be confusing, but that is not going to change now.

**Comment by sideshowbarker** [comment]
@evilpie Do think there’s any possible clarification that could be added here? Or do think this should be closed?

**Comment by evilpie** [comment]
Sure a better description should be good. Maybe someone can also come up with a good explanation why it's called destination.

**Comment by wbamberg** [comment]
I don't think there's a lot we can do here. Yes, it's not a very obvious name, but "a string indicating the type of content being requested" seems right, and the linked page goes into a lot of detail about it.

The only thing I would do is delete "Returns a string describing the request's destination", which doesn't tell you anything except perhaps to mislead one into thinking that the next sentence is wrong.
