### ISSUE TITLE
Issue with ":visited": Needs to mention background-color only works with a default color.

### ISSUE THREAD

**Issue by nessthehero** [mdn/content#2295]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:visited

#### What information was incorrect, unhelpful, or incomplete?

Article mentions that background-color is a supported style of :visited, but this is partially true. The style only works if the anchor tag already has a background color property. Otherwise, it is ignored.

#### Specific section or headline?

Privacy restrictions

#### What did you expect to see?

A note regarding this behavior.

#### Did you test this? If so, how?

Yes, I created a codepen with this demonstrated.

https://codepen.io/nessthehero/pen/poNNdoQ

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_visited`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:visited
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/_colon_visited/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this 👍

**Comment by CreaTorAlexander** [comment]
What would be the best? Shall I put a paragraph below the enumeration of the css properties 
`Allowable CSS properties are color, background-color, border-color, border-bottom-color, border-left-color, border-right-color, border-top-color, column-rule-color, outline-color, text-decoration-color, and text-emphasis-color.`
*Note: background-color will only be applicable if the anchor tag already has the background-color property.*

Also I haven't tried it but I would assume that this behavior will be the same for the other css properties.

**Comment by Ryuno-Ki** [comment]
@CreaTorAlexander I assigned it to you.

Perhaps start with the note and then add additional properties once it's in?
The commit message then could have a „relates to #<Issue_ID>” instead of „fixes #<Issue_ID>”.

**Comment by rachelandrew** [comment]
This is actually covered in the examples and the info above them: https://developer.mozilla.org/en-US/docs/Web/CSS/:visited#examples

**Comment by chrisdavidmills** [comment]
Thanks @rachelandrew ; yeah, looks like we can close this.
