### ISSUE TITLE
Misleading example at "A long-running synchronous function"

### ISSUE THREAD

**Issue by takrishna** [mdn/content#22974]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing

### What specific section or headline is this issue about?

A long-running synchronous function

### What information was incorrect, unhelpful, or incomplete?

The example given under this section misleads us into believing that by using asynchronous programming one could execute expensive/cpu hungry/long running code blocks without blocking the UI. In reality the mechanisms offered by Javascript only defers the execution until the next tick, at which point once the long running code block starts executing it would block the UI. Particularly the below section:

> You'll find that while our generatePrimes() function is running, our program is completely unresponsive: you can't type 
> anything, click anything, or do anything else.

> This is the basic problem with long-running synchronous functions. What we need is a way for our program to:
> 
> Start a long-running operation by calling a function.
> Have that function start the operation and return immediately, so that our program can still be responsive to other events.
> Notify us with the result of the operation when it eventually completes.
> That's precisely what asynchronous functions can do. The rest of this module explains how they are implemented in JavaScript.

A network call happens via web-api which does not block the UI - perhaps because it is threaded by the browser.

### What did you expect to see?

I think this example should be removed or even better that we move this to a new section with title - what async programing does not do - at least we make it clear that any code block or function call should not be long running otherwise it would block the UI.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/introducing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/introducing/index.md
* Last commit: https://github.com/mdn/content/commit/05d8b0eb3591009b6b7fee274bb7ed1bc5638f18
* Document last modified: 2022-09-14T12:03:40.000Z

</details>

**Comment by wbamberg** [comment]
-> https://github.com/mdn/content/pull/31204
