### ISSUE TITLE
content outdate: the new Edge browsers will not insert bidirectional control characters

### ISSUE THREAD

**Issue by yin1999** [mdn/content#22977]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString#avoid_comparing_formatted_date_values_to_static_values

### What information was incorrect, unhelpful, or incomplete?

The new Edge browsers will not insert bidirectional control characters, and the formatted string is not the same as the example form.

```js
new Date("2019-01-01T01:00:00Z").toLocaleString("en-US", {timeZone: "UTC"})  === "1/1/2019, 1:00:00 AM" // true
```

![image](https://user-images.githubusercontent.com/15844309/207863888-162177ce-9cdb-40a9-8747-3e989a569d08.png)

### What did you expect to see?

Update this part (maybe remove it): example and description.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/tolocalestring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/tolocalestring/index.md
* Last commit: https://github.com/mdn/content/commit/2eb202adbe3d83292500ed46344d63fbbae410b5
* Document last modified: 2022-12-13T19:22:57.000Z

</details>

**Comment by Josh-Cena** [comment]
I think the idea of this section is still valid, but maybe we have to state it without giving an example... I believe all major implementations use the ICU database these days, which means there's probably little variation.
