### ISSUE TITLE
console.group() needs examples illustrating the use of the label parameter

### ISSUE THREAD

**Issue by DanielFlaum** [mdn/content#22972]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/console/group

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The examples are missing illustrations of how the `label` parameter to `console.group()` can and should be used.

### What did you expect to see?

Examples illustrating the effects of using a label, possibly with advice on intended use.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/console/group`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/console/group
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/console/group/index.md
* Last commit: https://github.com/mdn/content/commit/da88b2f3a23b9d93f083003f13c06f9d96073f6a
* Document last modified: 2022-09-13T05:21:27.000Z

</details>

**Comment by postmeback** [comment]
Hi,

I came up with the below example

`
```html
console.group('My Group');
console.log('This is a log inside the group');
console.warn('This is a warning inside the group');
console.error('This is an error inside the group');
console.groupEnd();
```

**Comment by Josh-Cena** [comment]
Hi, the example is already here: https://developer.mozilla.org/en-US/docs/Web/API/console#using_groups_in_the_console

The "label" is exactly functioning as a display label for the group without additional semantics.
