### ISSUE TITLE
E-mail and Email Is Spelled Differently on Page

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#22984]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks

### What specific section or headline is this issue about?

E-mail links

### What information was incorrect, unhelpful, or incomplete?

On this page the heading "E-mail links" is spelled with a dash but in other parts of the page there is no dash. I assume you have a standard way of spelling the word.

I'm not sure how the "In this article" navigation is created so that file might nee to be updated too.

### What did you expect to see?

I expected to see a consistent spelling of the word e-mail whichever way you spell it.

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/creating_hyperlinks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/creating_hyperlinks/index.md
* Last commit: https://github.com/mdn/content/commit/d02c96125b0958bf5bd1bcaf345cb997cf48ce13
* Document last modified: 2022-11-14T23:47:20.000Z

</details>

**Comment by estelle** [comment]
This is a bigger issue than just one page. MDN has 123 occurrences of `e-mail` and approx 220 occurrences of `email` outside of code blocks (i.e. not include `type="email"` or as a variable name), so we likely need an official policy. There are also 13 occurrences of `emails` and 1 `e-mails`.

**Comment by jfc3-dol** [comment]
Glad I could be helpful, but I didn't think it would be that involved.

Good luck figuring out which is the best way to go.

**Comment by dipikabh** [comment]
Both the spellings are correct as per the web. Our MDN writing style guide [prescribes](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#preferred_style_guides) the MS style guide, [which says](https://learn.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/hyphens#compound-nouns):

> Compound nouns
> 
> Hyphenate compound nouns when one of the words is abbreviated.
> **Examples**
> e-book
> e-commerce
> **Exception** email

The MDN writing style guide currently [states](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#hyphens):

> Hyphens
> 
> Hyphenated compounds should be used when the last letter of the prefix is a vowel and is the same as the first letter of the root.
> **Correct**: email, re-elect, co-op
> **Incorrect**: e-mail, reelect, coop

I believe we should choose "email" as a policy, update our writing style guide, and update all "e-mail" instances.

**Comment by hamishwillee** [comment]
Fixed in #23049. Thanks for posting. Thanks for finding the rule @dipikabh .
