### ISSUE TITLE
Unused CSS class in Fieldset and Legend demos

### ISSUE THREAD

**Issue by lavenderlens** [mdn/content#230]
In the Fieldset page at **content/files/en-us/web/html/element/fieldset/** 
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset

And in the Legend page at **content/files/en-us/web/html/element/legend/** 
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend

in the CSS tab of the demo there is a class `.output`

This is not referenced in the HTML and so should be removed on both pages as it is potentially confusing.

This is my first comment on MDN so please excuse me if I've not done this correctly.

**Comment by bershanskiy** [comment]
@lavenderlens This CSS is actually used by the demos, it applies to the whole example, which has class `output`. You can see that by deleting these CSS rules in the editor on the left (the output on the right changes).

**Comment by chrisdavidmills** [comment]
@bershanskiy is correct here. The `output` class is applied to the entire `<div>` that wraps the example output. A great way to check it out is to right click on the output window, select "Inspect", and have a look at it in your browser's developer tools.

No worries on the comment, by the way — you submitted it correctly, and you should always ask if something does not seem right. Thanks for taking an interest!
