### ISSUE TITLE
Outdated content for margin-trim

### ISSUE THREAD

**Issue by nt1m** [mdn/content#23012]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/margin-trim

### What information was incorrect, unhelpful, or incomplete?

See latest spec: https://w3c.github.io/csswg-drafts/css-box-4/#margin-trim

`all` and `in-flow` values don't exist.

### What did you expect to see?

Up-to-date content.

### Do you have any supporting links, references, or citations?

https://w3c.github.io/csswg-drafts/css-box-4/#margin-trim

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/margin-trim`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/margin-trim
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/margin-trim/index.md
* Last commit: https://github.com/mdn/content/commit/6a4ff1ba12d84b8e369cd00fb3660bc805f93b79
* Document last modified: 2022-09-27T03:53:16.000Z

</details>

**Comment by dipikabh** [comment]
**Update** to the requirement expressed in this issue:

In addition to removing the outdated `all` and `in-flow`, the following values need to be documented: `block`, `inline`, `block-start`, `block-end`, `inline-start`, and `inline-end`.
