### ISSUE TITLE
Property listed as unsupported on Firefox for Android, but @supports still fires for it

### ISSUE THREAD

**Issue by DavidJCobb** [mdn/content#23027]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/shape-image-threshold

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

The property is listed as supported on Firefox for Desktop, but unsupported for Firefox for Android, However, the `@supports` media rule indicates that the property is supported on both platforms.

### What did you expect to see?

If the property does not function as intended on Firefox for Android, but still registers as supported when using `@supports`, then there should be a note of this.

I haven't bothered to see if the property _does_ function as intended on Android. The `@supports` query is my only use case at present.

### Do you have anything more you want to share?

The following properties on other articles have the same issue; this form only lets me report one article at a time and making separate issues for these seems like a waste:

* overscroll-behavior-block
* overscroll-behavior-inline

In case the context helps: I need to target smartphones with CSS to offer a touch-friendly layout. The only usable media queries for this task [are unreliable in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1806259) and apparently [have been for four years](https://bugzilla.mozilla.org/show_bug.cgi?id=1493128). I can use `@-moz-document url-prefix()` to target Firefox in general, but I need some way of targeting the Android version in specific in order to complete my task. I was hoping to find a property I could use `@supports` on, though that is increasingly seeming like a long shot.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/shape-image-threshold`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/shape-image-threshold
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/shape-image-threshold/index.md
* Last commit: https://github.com/mdn/content/commit/413355c790c4102eea5937465ea610938327fe56
* Document last modified: 2022-09-27T03:53:49.000Z

</details>

**Comment by Josh-Cena** [comment]
Probably fixed by https://github.com/mdn/browser-compat-data/pull/19552/
