### ISSUE TITLE
Issue with "await": (short summary here please)

### ISSUE THREAD

**Issue by raisen** [mdn/content#2302]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

#### What information was incorrect, unhelpful, or incomplete?
...however it can be used on it's own with JavaScript modules

#### Specific section or headline?
Above syntax

#### What did you expect to see?
...however it can be used on its own with JavaScript modules

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/await`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/operators/await/index.html
* Last commit: https://github.com/mdn/content/commit/3b26d3bc849cd84ff37ae85b9a8292267726df0b
* Document last modified: 2021-02-08T17:40:47.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update it
