### ISSUE TITLE
Issue with "Installing and uninstalling web apps": (short summary here please)

### ISSUE THREAD

**Issue by sizvix** [mdn/content#2305]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Developer_guide/Installing

#### What information was incorrect, unhelpful, or incomplete?
iOs image icon is full width size , insteed of a little icon. Size are removed ...

#### Specific section or headline?
iOs part

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/progressive_web_apps/developer_guide/installing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Developer_guide/Installing
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/progressive_web_apps/developer_guide/installing/index.html
* Last commit: https://github.com/mdn/content/commit/88b8dc61828f0c111b5eda4197921dcf153f3b0f
* Document last modified: 2020-12-15T16:53:05.000Z

</details>

**Comment by NegiAkash890** [comment]
I think here issue can be fixed by making use of inline CSS . Because if we directly target the `<img>` then it will affect all the other images on the page .  Please correct me if i am wrong .
