### ISSUE TITLE
Warning on webRequest.onAuthRequired

### ISSUE THREAD

**Issue by erosman** [mdn/content#23064]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onAuthRequired

### What specific section or headline is this issue about?

Additional objects

### What information was incorrect, unhelpful, or incomplete?

> **Warning**: Unlike Chrome, Firefox will return the requested host instead of the proxy requesting the authentication, even if `isProxy` is `true`.

### What did you expect to see?

In practice e.g. `Firefox -> proxy -> target website`, Firefox returns the proxy host, like Chrome, **as it should**, otherwise  authentication (sending username/password) to proxy server would not be possible.

```
"challenger": {
  "host": "104.254.***.***",
  "port": 1234
},
```

**Comment by rebloor** [comment]
@erosman do you have any evidence or testing to support this change?

**Comment by erosman** [comment]
> @erosman do you have any evidence or testing to support this change?

Initially, I did ask in `chat.mozilla.org` for clarification on what the above mentioned note is meant for, but got no response.

In addition to my own proxy extension ([FoxyPAC](https://addons.mozilla.org/en-US/firefox/addon/foxypac/)) , I am also the developer of 3 others ([FoxyProxy Standard](https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/), [FoxyProxy Basic](https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-basic/), [GeoShift](https://addons.mozilla.org/en-US/firefox/addon/geoshift/)) and have not observed what was mentioned in the **warning**.

It might be that the note was valid at the time that it was added and the API was updated later.

Although, there are areas where Firefox returns _"requested host instead of the proxy"_ (_SSL certificate issues for example_). those are not related to `webRequest.onAuthRequired`.

There is also an ambiguity in the API since "it returns the IP of the proxy instead of the IP of the requested host" (_there is a closed bug for it on bugzilla_).

The following example which is proxied via "209.208.000.000", shows that `challenger` returns the proxy (_not the requested host_):

```js
browser.webRequest.onAuthRequired.addListener(e => console.log(e), {urls: ['<all_urls>']});

{
  "requestId": "12135",
  "url": "https://github.com/foxyproxy/browser-extension",
  "method": "GET",
  "type": "main_frame",
  "timeStamp": 1665324199466,
  "tabId": 164,
  "frameId": 0,
  "parentFrameId": -1,
  "incognito": false,
  "thirdParty": false,
  "cookieStoreId": "firefox-default",
  "statusCode": 407,
  "statusLine": "HTTP/1.0 407 Proxy Authentication Required",
  "scheme": "basic",
  "realm": "Web-Proxy",
  "isProxy": true,
  "challenger": {
    "host": "209.208.000.000",
    "port": 4443
  },
  "proxyInfo": {
    "connectionIsolationKey": "",
    "failoverTimeout": 1800,
    "host": "209.208.000.000",
    "port": 4443,
    "proxyAuthorizationHeader": "",
    "proxyDNS": false,
    "type": "https",
    "username": ""
  },
  "ip": "209.208.000.000",
  "frameAncestors": [],
  "urlClassification": {
    "firstParty": [],
    "thirdParty": []
  },
  "requestSize": 0,
  "responseSize": 0
}
```

**Comment by rebloor** [comment]
Many thanks, @erosman appreciate you taking the time to clarify
