### ISSUE TITLE
CSSAnimatedProperties.ejs outputs wrong property

### ISSUE THREAD

**Issue by apasov** [mdn/content#2307]
In mdn/data v2.0.12 "notAnimatable" animation type was added.
https://github.com/mdn/data/commit/1356fbb72029d2121c0ae5dc4d24a0f99afc37c5

But `text-combine-upright ` is now in the list https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties.
This should be fixed.

**Comment by CreaTorAlexander** [comment]
I can update this :+1:

**Comment by Ryuno-Ki** [comment]
Assigned it to you, @CreaTorAlexander

**Comment by CreaTorAlexander** [comment]
Or maybe unassign me I don't understand the issue. @apasov in the list on the site you have shared I can neither find text-combine-upright nor notAnimatable. What should be updated on this site?

**Comment by Ryuno-Ki** [comment]
https://github.com/mdn/content/blob/a7af6d344bdc50b39a17c4c0328d580199d612b4/files/en-us/web/css/css_animated_properties/index.html#L17

Hm, perhaps worth to move Yari as the macro resides in

https://github.com/mdn/yari/blob/9e3e569ce8df374a50e343da791eb245420106e4/kumascript/macros/CSSAnimatedProperties.ejs

I cannot tell, which version of `@mdn/data` is loaded there, though.

**Comment by apasov** [comment]
>> in the list on the site you have shared I can neither find text-combine-upright nor notAnimatable.

@CreaTorAlexander  you cannot find text-combine-upright because it was already fixed in `mdn/yari`

https://github.com/mdn/yari/commit/d9cd44c5abffb0f9c0d32d7a94e995dd844b112e#diff-982726822c448ae241ef1e2eba35739cde84008c9c9fe5954b5a06e977cc7d5bR16

and notAnimatable is not intended to be there at all.

>>What should be updated on this site?

`CSSAnimatedProperties.ejs` should be updated.

@Ryuno-Ki I believe the latest version of `mdn/data`  is loaded there

**Comment by Ryuno-Ki** [comment]
@apasov So is there something to do _here_?
If not, could you close the issue?
