### ISSUE TITLE
Documentation of postMessage() with transferable data is hard to understand

### ISSUE THREAD

**Issue by Petrux99** [mdn/content#23099]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects

### What specific section or headline is this issue about?

Transferring objects between threads

### What information was incorrect, unhelpful, or incomplete?

To me the relationship between the first and second argument to postMessage() is not clear. Initially I assumed that on the receiving end I would receive two arguments, the normal copied data and then an array containing the transferred data. I understand now that the second argument means something along the lines of: "Out of the data I send in arg 1, here is a list of references to things that should be transferred rather than copied".

Maybe this relationship can be made clearer? And maybe it can be mentioned that they way you receive data doesn't change at all.

### What did you expect to see?

An example of how to receive transferred data. Once I understood more about how this works, I rather expect the relationship between the two arguments to be explained clearly, as the mechanism is not super intuitive. Also, it might be useful to explain that all of these work (which might also not be obvious):

`postMessage(myObj, [myObj])`
`postMessage(myObj, [myObj.someProp])`
`postMessage({ foo: myObj }, [myObj])`

### Do you have any supporting links, references, or citations?

I got help from this SO answer, where someone also complains in a comment he/she "couldn't find a decent example on MDN": https://stackoverflow.com/questions/16071211/using-transferable-objects-from-a-web-worker :)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/transferable_objects`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Transferable_objects
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/transferable_objects/index.md
* Last commit: https://github.com/mdn/content/commit/04e75ce1f83a591a576f52b143f195133bfcbe96
* Document last modified: 2022-09-10T06:36:08.000Z

</details>

**Comment by Josh-Cena** [comment]
This is a glossary entry, which is meant to be brief and only providing definition for the term. If you need the API documentation, please see [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)'s own page. (Note though that I think the `postMessage()` call is wrong as it's missing `origin`)

**Comment by sideshowbarker** [comment]
Agreed with @Josh-Cena that the https://developer.mozilla.org/en-US/docs/Glossary/Transferable_objects content is already much too long to be appropriate for having in the Glossary. So to be able to make further refinements to it when needed (because despite being misplaced in the Glossary, it’s still valuable content that a lot work has already gone into), I opened https://github.com/mdn/content/pull/23109 with a change that moves it to https://developer.mozilla.org/en-US/docs/Web/API/Transferable_objects.

That’ll allow us to make an update to it for this issue, if needed — and for future updates when other issues related to the content come in.

**Comment by Petrux99** [comment]
> This is a glossary entry, which is meant to be brief and only providing definition for the term. If you need the API documentation, please see [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)'s own page. (Note though that I think the `postMessage()` call is wrong as it's missing `origin`)

I agree it makes sense to keep the glossary entry short. I didn't think about the distinction between glossary and API docs when filing this. However, I think the information I felt is missing is not currently to be found in the API docs.

Regarding `origin` missing in my example calls, it's because I was actually coming from https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/postMessage, where that parameter is not applicable. Good point though and something to keep in mind of course if such examples are to be included somewhere.

**Comment by Petrux99** [comment]
> Agreed with @Josh-Cena that the https://developer.mozilla.org/en-US/docs/Glossary/Transferable_objects content is already much too long to be appropriate for having in the Glossary. So to be able to make further refinements to it when needed (because despite being misplaced in the Glossary, it’s still valuable content that a lot work has already gone into), I opened #23109 with a change that moves it to https://developer.mozilla.org/en-US/docs/Web/API/Transferable_objects.
> 
> That’ll allow us to make an update to it for this issue, if needed — and for future updates when other issues related to the content come in.

Great idea to move this info to somewhere where it's natural to elaborate on it further.

Thanks both for your quick input and actions!
