### ISSUE TITLE
Issue with "Advanced techniques: Creating and sequencing audio": oscillators/buffers starts are not scheduled

### ISSUE THREAD

**Issue by robsco-git** [mdn/content#2310]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Advanced_techniques

#### What information was incorrect, unhelpful, or incomplete?
`time` needs to be passed as an argument to `playSweep`, `playPulse`, `playNoise`, and `playSourceNode` so that these functions can start the relevant oscillators/buffers at the correctly scheduled time. Please see https://github.com/cwilso/metronome/blob/fc0cab510f9d7c4bccf16d8f3f011b67d62ec369/js/metronome.js#L66 as an example of what I mean. Without passing time to these relevant start methods, they will start playing audio as soon as they can but they should be scheduled to start (play) at `nextNoteTime`.

After typing the above I saw a fix is available to the example: https://github.com/mdn/webaudio-examples/pull/37

#### Specific section or headline?
Throughout the article.

#### What did you expect to see?
Scheduled oscillator/buffer starts.

#### Did you test this? If so, how?
I built a sample app based of the code but I was having issues keeping audio playback starts/events in time.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/web_audio_api/advanced_techniques`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Advanced_techniques
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/web_audio_api/advanced_techniques/index.html
* Last commit: https://github.com/mdn/content/commit/9fe6b6233764f2e961c7760e14a37c86708dbf74
* Document last modified: 2020-12-15T02:04:17.000Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting, @robsco-git .

@Rumyra knows this area very well, so I've assigned her to this one, and requested that she reviews the PR.

**Comment by Rumyra** [comment]
This PR deals with this issue https://github.com/mdn/content/pull/2445 - I'll close once this has merged.

Thank you @robsco-git hope this helps 🙏
