### ISSUE TITLE
Change to a more clear message

### ISSUE THREAD

**Issue by JuergenPurtz** [mdn/content#23112]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target

### What specific section or headline is this issue about?

try_it

### What information was incorrect, unhelpful, or incomplete?

I'm not a native English speaker. Unfortunately, I erroneously translated the message "Foo() must **be** called with new" in my head to just the opposite: "Foo() must **have been** called with the new operator". Hence I get confused about the behavior of the invocation. Please consider changing the message to a more clear version in active tense, e.g., "You must call Foo() with 'new'. Abort. ". 

### What did you expect to see?

just the opposite behavior

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/new.target`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/new.target/index.md
* Last commit: https://github.com/mdn/content/commit/0f248adcab759bdad247a5dbfb7da12dc32bce59
* Document last modified: 2022-12-13T20:26:24.000Z

</details>

**Comment by Josh-Cena** [comment]
This does seem a bit ambiguous. I keep reading it the wrong way as well. For reference, here are the engines' error messages for `Map()`:

```
$ eshost -e "Map()"
#### engine262

TypeError: [Function: Map] cannot be invoked without new

#### GraalJS

TypeError: Constructor Map requires 'new'

#### JavaScriptCore

TypeError: calling Map constructor without new is invalid

#### SpiderMonkey

TypeError: calling a builtin Map constructor without new is forbidden

#### V8

TypeError: Constructor Map requires 'new'
```

Changing our message to one of the above seems good enough. This needs to be done in [interactive-examples](https://github.com/mdn/interactive-examples)

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/interactive-examples/pull/2377
