### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getByteTimeDomainData

### ISSUE THREAD

**Issue by Puddingsan** [mdn/content#2313]
# Request type
Correction or update

## Page to change
https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getByteTimeDomainData
--AND--
https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getFloatTimeDomainData

# Details
For both the aforementioned articles there exists the same discrepancy.

Second paragraph on page states:
"If the array has fewer elements than the AnalyserNode.fftSize, excess elements are dropped. If it has more elements than needed, excess elements are ignored."

Second sentence under the 'Parameters' section reads:
"If the array has fewer elements than the AnalyserNode.frequencyBinCount, excess elements are dropped. If it has more elements than needed, excess elements are ignored."

Seeing as the frequencyBinCount is half the fftSize, one of the sentences is incorrect - I believe the frequencyBinCount to be the correct parameter.

Both sentences are in need of grammatical adjustment - when the array has fewer elements than required, the missing elements are not "excess" and "dropped".

Kind regards, Nick

**Comment by CreaTorAlexander** [comment]
I can update this :+1:

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander assigned; thanks!

**Comment by CreaTorAlexander** [comment]
On the first site the information is just redundant. I would prefer to remove the second paragraph and let it stay in the *Parameters* Section.
