### ISSUE TITLE
Custom Character Class Regex syntax is listed under the Groups and back references category in the table

### ISSUE THREAD

**Issue by JamieVaughn** [mdn/content#23148]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

### What specific section or headline is this issue about?

Table with caption "Special characters in regular expressions."

### What information was incorrect, unhelpful, or incomplete?

There is syntax for custom Character Classes listed under the Groups & backreferences category

### What did you expect to see?

I expected to see these two syntax examples: `[xyz]`, `[^xyz]` under the Character Classes row in the table that has the caption "Special characters in regular expressions." on this page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

### Do you have any supporting links, references, or citations?

This image shows the custom character classes listed in the wrong category of Groups and backreferences:
![image](https://user-images.githubusercontent.com/27257424/209281825-c72b8f37-9926-4491-90e3-faa6f40542a1.png)

While elsewhere, MDN documentation includes the custom character class syntax as part of the Character Classes category. For example in this article:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes#types

**Comment by Josh-Cena** [comment]
To whoever works on this: please make sure all lists in the table are in sync with their respective pages. There are multiple places where things are missing.
