### ISSUE TITLE
Create plan for retitling WebAPI/JavaScript ref pages

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#2314]
Now that we have done research into the API ref naming problem, the clear winner seems to be to lower-camel-case the interface name for instance members, to imply it is an object instance rather than an interface, e.g.

`XMLHttpRequest.open()` -> `xmlHttpRequest.open()`

This satisfies the worries of the spec folks, as well as not causing any detriment to our primary target audience or SEO.

This task is about creating a plan to implement these changes.

# Acceptance criteria

1. - [ ] Create a list of JavaScript objects and WebAPI interfaces that need dealing with.
2. - [ ] Write a plan of exactly what need to be done in each case
3. - [ ] Update the MDN page type templates as appropriate
4. - [ ] Do the required work on a small sample of interface pages (say, 2 JS objects and 2 WebAPI interfaces) and get a further round of feedback to make sure we are going in the right direction before we go any further.

# Tasks

See above

**Comment by sideshowbarker** [comment]
Superseded by https://github.com/mdn/content/discussions/5121
