### ISSUE TITLE
Issue with "Promise.prototype.then()": Incorrect parameters explaination

### ISSUE THREAD

**Issue by ddomen** [mdn/content#2315]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

#### What information was incorrect, unhelpful, or incomplete?
In the parameters section there is written

> If it is not a function, it is internally replaced with an "Identity" function (it returns the received argument).

which is incorrcect

#### Specific section or headline?
[Paragraph](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#parameters)

#### What did you expect to see?

> If it is not a function, it is ignored.

#### Did you test this? If so, how?
If the argument of `then` is a function, it behavies like descripted. If it is a constant (like a number) it is just ignored.

```js
new Promise(r => r(54))
    .then(() => 22)
    .then(console.log)
// expected 22, printed 22

new Promise(r => r(54))
    .then(22)
    .then(console.log)
// expected 22, printed 54
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise/then`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/promise/then/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this 👍

**Comment by evilpie** [comment]
The comment seem correct. The identity function is `a => a`.

**Comment by ddomen** [comment]
> The comment seems correct. The identity function is `a => a`.

I see what you state, but it is not clear. In the sentence `(it returns the received argument)` is unclear if the argument is just that of the "identity function" or if it is the argument of the `then` method. I could expect to be `.then(22)` equals to `.then(() => 22)` from that sentence, which is not (`.then(22)` equals `.then(a => a)`).

Maybe the correction at this point could be 

> If it is not a function, the argument is ignored and it is used an "Identity" function (it returns the `fulfillment value`).

**Comment by davegregg** [comment]
How about this?

> If this argument is not a function, it is ignored. Instead, an "Identity" function (`x => x`) is used in its place, passing the `fulfillment value` on for the next `Promise` method which may be added to the chain.

The next paragraph (`onRejected`) uses nearly identical language to the `onFulfilled` paragraph. So, I'd recommend updating the language there, as well. But in both Chrome and Firefox, appears to be ignored so completely that it is as though no argument had been supplied at all.

If this is true, here is the language I'll propose:

> If this argument is not a function, it is ignored entirely: as though the `onRejected` argument had not been supplied.

But someone should check the spec and perhaps the implementation in V8 or SpiderMonkey.
