### ISSUE TITLE
Incorrect example for unicode regex property escapes

### ISSUE THREAD

**Issue by wolfbeast** [mdn/content#23160]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes

### What specific section or headline is this issue about?

Shorthand for Script is incorrect per the spec.

### What information was incorrect, unhelpful, or incomplete?

```
// Using the short name Sc for the Script property
mixedCharacters.match(/\p{Sc=Cyrillic}/u); // Л
```

### What did you expect to see?

```
// Using the short name Sc for the Script property
mixedCharacters.match(/\p{Script=Cyrillic}/u); // Л
```

### Do you have anything more you want to share?

Trying to use the example threw me for a loop because it failed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions/unicode_property_escapes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/unicode_property_escapes/index.md
* Last commit: https://github.com/mdn/content/commit/effd5de5e42bfe045c3bf44b2d7b14f4d6146785
* Document last modified: 2022-12-13T19:13:40.000Z

</details>

**Comment by Josh-Cena** [comment]
It should be lowercase `sc`, not `Sc`.
