### ISSUE TITLE
Issue with "Document Object Model (DOM)": (The parenthetical aside/qualification interrupts complete sentence?)

### ISSUE THREAD

**Issue by dhscratch** [mdn/content#2317]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model

#### What information was incorrect, unhelpful, or incomplete?
**From the opening paragraph, second sentence**: 

> "_Usually, that means JavaScript, although modeling HTML, SVG, or XML documents as objects are not part of the core JavaScript language, as such_."

I think the syntax is off here. The above is basically stating: "That means JavaScript [...] are not part of the core JavaScript language," which of course doesn't make any sense.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document_object_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/document_object_model/index.html
* Last commit: https://github.com/mdn/content/commit/88b8dc61828f0c111b5eda4197921dcf153f3b0f
* Document last modified: 2020-12-15T16:53:05.000Z

</details>

**Comment by Rumyra** [comment]
See https://github.com/mdn/content/pull/2392
