### ISSUE TITLE
Add the `event.target.result` information to `IDBRequest`

### ISSUE THREAD

**Issue by gintominto5329** [mdn/content#23184]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/IDBRequest

### What specific section or headline is this issue about?

The value `event.target.result` is not mentioned, and needs manual trial to find out

### What information was incorrect, unhelpful, or incomplete?

Whenever any of the member functions of [`IDBObjectStore`](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore), like `get`, `delete`, `count`, `put`, ... are called, an object of `IDBRequest` returned, and the result can be accessed using its `success` event, but what(if at all), would be there in `event.target.result`, is not mentioned, and needs manual trial, to find out the result,

It would be very helpful, if this information gets added to the doc.

Thanking you,

### What did you expect to see?

For example, 
The `event.target.result` of the `IDBRequest`, returned by `IDBObjectStore.count()`, is a numeric value, but its not mentioned, 

This may seem like a simple example, but 
Can anyone tell without trial that, 
What is the value `event.target.result` of the `IDBRequest`, returned by `IDBObjectStore.delete(key)`,
Is it the `keyPath` of the deleted object, or null, or something else,

### Do you have any supporting links, references, or citations?

Its very simple just use the console

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/idbrequest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBRequest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/idbrequest/index.md
* Last commit: https://github.com/mdn/content/commit/4deda8776019992a83a25313817c0de3b16bef7a
* Document last modified: 2022-11-26T10:31:25.000Z

</details>

**Comment by wbamberg** [comment]
If I understand you right, I think the fix here is to check that all methods that return an `IDBRequest` say what the `result` property of that request will be if the request succeeds. Just like how these days with `Promise`-returning APIs we say things like "Returns a `Promise` that resolves to an array of strings" or something like that.

For example here: https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/count#return_value we should say something like:

> An [`IDBRequest`](https://developer.mozilla.org/en-US/docs/Web/API/IDBRequest) object. If the request succeeds, the object's `result` property will be the total number of records that match the provided query, or if no query was provided, the total number of records in the store.

Does that sound right?

**Comment by gintominto5329** [comment]
Yes
