### ISSUE TITLE
Video example in the section - 'fixing the problem with stop propagation' doesn't work

### ISSUE THREAD

**Issue by ambujsahu81** [mdn/content#23181]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#fixing_the_problem_with_stoppropagation

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#fixing_the_problem_with_stoppropagation

### What information was incorrect, unhelpful, or incomplete?

Video example in `fixing_the_problem_with_stoppropagation`  section doesn't work.

Error in console : `Failed to load resource: net::ERR_CONNECTION_TIMED_OUT .`

**Browser**

- Chrome Version 108.0.5359.125
- Microsoft Edge Version 108.0.1462.54 

### What did you expect to see?

The Example doesn't work as clicking in the box also do not hide the video. Must be due to the err in console.

**Comment by wbamberg** [comment]
This works fine for me:

![stop-prop](https://user-images.githubusercontent.com/432915/209718774-ddfd5e5a-9dad-4cc6-91b3-3912e849d6fc.gif)

> Error in console : Failed to load resource: net::ERR_CONNECTION_TIMED_OUT .

Perhaps you have a network problem? This error doesn't sound at all related to the example.

**Comment by ambujsahu81** [comment]
It is still not working me. 
And it should be related to the example as once the video is played thereafter clicking on the box should hide it. But it not working like that for me at least.

https://user-images.githubusercontent.com/118078892/209719841-a2943787-22f6-4dd7-8ba1-4e8274dcdade.mp4

**Comment by wbamberg** [comment]
Can you access https://raw.githubusercontent.com at all? From the last screenshot it looks like you can't, which would prevent the example from working. But that would be a network problem at your end, not a problem with the example as such.

It's not great to server media from https://raw.githubusercontent.com. It would be better to use an example video served locally to the page but we can't do that while https://github.com/mdn/yari/pull/7605 is not resolved.

Can you access https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm ? Maybe we could use that instead.

**Comment by ambujsahu81** [comment]
[https://raw.githubusercontent.com](https://raw.githubusercontent.com/) is not accessible to me. 
This link is working though [https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm]( https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm).  If this issue depends on any other  issue [https://github.com/mdn/yari/pull/7605](https://github.com/mdn/yari/pull/7605) than may be we can wait for it resolve first.

**Comment by wbamberg** [comment]
No worries, it's easy to use that other video -> https://github.com/mdn/content/pull/23226 .
