### ISSUE TITLE
clipboard.readText() is behind flag on Firefox

### ISSUE THREAD

**Issue by guest271314** [mdn/content#23188]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

### What specific section or headline is this issue about?

However, while navigator.clipboard.readText() and navigator.clipboard.writeText() work on all browsers

### What information was incorrect, unhelpful, or incomplete?

clipboard.readText() is behind flag on Firefox dom.events.asyncClipboard.readText in about:config, which is also not mentioned on https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText.

### What did you expect to see?

Conspicuous notes on both https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText and https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard stating the flag that needs to be used on Firefox to enable navigator.clipboard.readText() and removal of the claim 

> However, while navigator.clipboard.readText() and navigator.clipboard.writeText() work on all browsers

which is not accurate when running Nightly 110 out of the box.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.md
* Last commit: https://github.com/mdn/content/commit/05d8b0eb3591009b6b7fee274bb7ed1bc5638f18
* Document last modified: 2022-09-14T12:03:40.000Z

</details>

**Comment by Josh-Cena** [comment]
The BCD indicate that Firefox now support reading clipboard, with a lot of notes. I'm going to close this as completed but please let me know if there's anything else to add.
