### ISSUE TITLE
Typo in "Structuring the Web with HTML" Page

### ISSUE THREAD

**Issue by Sriparno08** [mdn/content#23213]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML

### What specific section or headline is this issue about?

See Also

### What information was incorrect, unhelpful, or incomplete?

Under the section "Web forms", there is a line that says:

> However, for historical and technical reasons it's not always obvious how to use them to their full potential.

There should be comma after the word "reasons".

### What did you expect to see?

The line should be changed to:

> However, for historical and technical reasons, it's not always obvious how to use them to their full potential.

### Do you have anything more you want to share?

GitHub URL: https://github.com/mdn/content/edit/main/files/en-us/learn/html/index.md

**Comment by Josh-Cena** [comment]
Please refrain from submitting issues about typos; just send the PR right away.

**Comment by Sriparno08** [comment]
Alright, @Josh-Cena 👍
