### ISSUE TITLE
Flexbox guide doesn't include the `gap` property

### ISSUE THREAD

**Issue by weibeld** [mdn/content#23221]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Mastering_Wrapping_of_Flex_Items#creating_gutters_between_items
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox#split_navigation

### What specific section or headline is this issue about?

- Creating gutters between items
- Split navigation

### What information was incorrect, unhelpful, or incomplete?

Sections explains old way using negative margins for creating gaps between flexbox items, instead of [`gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/gap):

> When wrapping flex items, the need to space them out is likely to arise. You can see from the live example below that in order to create gaps that do not also create a gap at the edges of the container, we need to use **negative margins on the flex container itself**. Any border on the flex container is then moved to a second wrapper in order that the negative margin can pull the items up to that wrapper element.
It is this requirement **that the `gap` properties, once implemented, will solve for us**. Proper gaps only happen on the inside edges of items.

And:

> Also in this example we are using margins on the flex items to create a gap between items, and a **negative margin on the container** in order that the items still remain flush with the right and left edges. **Until the `gap` properties from the Box Alignment specification are implemented** in flexbox, we have to use margins in this way if we want to create a gutter between items.

### What did you expect to see?

Update instructions to use `gap`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_flexible_box_layout/mastering_wrapping_of_flex_items`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Mastering_Wrapping_of_Flex_Items
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_flexible_box_layout/mastering_wrapping_of_flex_items/index.md
* Last commit: https://github.com/mdn/content/commit/71c4bc0b6329ec40ddbefd8d3124547e91cfa612
* Document last modified: 2022-09-28T03:40:57.000Z

</details>

**Comment by dostonnabotov** [comment]
Hi, @weibeld! 

I agree that the contents need to be updated mentioning the use of the `gap` property, which is already supported in all browsers, except for [IE and Opera Mini](https://caniuse.com/flexbox-gap). 

By the way, I didn't know that you can replicate the `gap` property with negative margins. Really cool trick! 😃

I would be happy to pick it up and solve this issue :)
