### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by jwilson5153** [mdn/content#23222]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML

### What specific section or headline is this issue about?

htnl example doc

### What information was incorrect, unhelpful, or incomplete?

The code did not contain links to the css and js files and no mention was made about adding them.

### What did you expect to see?

I expected either the links to be included int he html file or instructions about the need to add the links.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/the_head_metadata_in_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/the_head_metadata_in_html/index.md
* Last commit: https://github.com/mdn/content/commit/fc294fbbf432b5b210e0394e23b5c8950e81d734
* Document last modified: 2022-10-26T04:12:56.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing!

Isn't that described in https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#applying_css_and_javascript_to_html ?
