### ISSUE TITLE
Incorrect explanation of interaction between exponentiation and unary operators

### ISSUE THREAD

**Issue by peetklecha** [mdn/content#23235]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

### What specific section or headline is this issue about?

Notes list, under Table

### What information was incorrect, unhelpful, or incomplete?

The operand of unary operators (precedence 14; excluding prefix increment/decrement) cannot be an exponentiation ** (precedence 13) without grouping, or there will be a [SyntaxError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError). That means, although -1 ** 2 is technically unambiguous, the language requires you to use (-1) ** 2 instead.

### What did you expect to see?

The left operand of an exponentiation (precedence 13) cannot be a unary operation (precedence 14; excluding prefix increment/decrement) without grouping, or there will be a [SyntaxError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError). That means, although -1 ** 2 is technically unambiguous, the language requires you to use (-1) ** 2 instead.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/operator_precedence/index.md
* Last commit: https://github.com/mdn/content/commit/fe3b1f7aac210e72df7273b1a10ed4771fa2a2bf
* Document last modified: 2022-12-19T09:48:47.000Z

</details>

**Comment by Josh-Cena** [comment]
No need for "excluding prefix increment/decrement", because "unary operator" in this context refers specifically to those with precedence 14. Otherwise you'll need to exclude `new` and `yield` as well. But the suggestion makes sense otherwise.
