### ISSUE TITLE
CSS hsl() syntax: commas or not?

### ISSUE THREAD

**Issue by theking2** [mdn/content#23236]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl

### What specific section or headline is this issue about?

Try it and the rest

### What information was incorrect, unhelpful, or incomplete?

In the try it section the hsl value list has no commas. In there remaing part it is a comman separated list. In the whole page there is no mention of commas or not. 

### What did you expect to see?

A section describing using commans

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/color_value/hsl`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/color_value/hsl/index.md
* Last commit: https://github.com/mdn/content/commit/6be1b954a117202d7635caeec74ebbbde984d3f3
* Document last modified: 2022-09-26T22:47:43.000Z

</details>

**Comment by Josh-Cena** [comment]
Isn't it already in the syntax box?

```css
/* Syntax with space-separated values */
hsl(hue saturation lightness)
hsl(hue saturation lightness / alpha)

/* Syntax with comma-separated values */
hsl(hue, saturation, lightness)
hsl(hue, saturation, lightness, alpha)
```

This syntax is used across `rgb` and other colors as well.

**Comment by wbamberg** [comment]
We should be clearer here and update these pages though. AIUI the comma-separate form is a legacy form used for compatibility. We should document space-separated with a note saying that comma-separated is supported as a legacy form. We should (IMO) update the whole page to use space-separated, except a single example under "Examples" to show the legacy form.

I just filed https://github.com/mdn/content/pull/23238 to add formal syntax for color functions, which helps somewhat (and shows only space-separated form.

See also https://w3c.github.io/csswg-drafts/css-color/#color-syntax-legacy .

**Comment by theking2** [comment]
Looking at the hsla() page I suggest to show the current level 4 syntax first and at the end include a section "Legacy" showing legacy syntax and not the other way around. People will probably from top and not from the bottom.
