### ISSUE TITLE
Typo: Invalid value for path 'name' in Django Tutorial 'Book detail page'/'URL mapping' section

### ISSUE THREAD

**Issue by yvuyiv-samvirk** [mdn/content#23257]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views#url_mapping_2

### What information was incorrect, unhelpful, or incomplete?

`path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail')`

Looks like name='book-detail' is incorrect

### What did you expect to see?

`path('book/<int:pk>', views.BookDetailView.as_view(), name='book_detail')`

'book_details' with underscore

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/django/generic_views`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/generic_views/index.md
* Last commit: https://github.com/mdn/content/commit/0c410538f50487e8b0f419e11e24ad5adb60bf36
* Document last modified: 2022-11-23T00:02:38.000Z

</details>

**Comment by hamishwillee** [comment]
It's not incorrect - you'd have to justify why using a hyphen doesn't work for this to be valid.
