### ISSUE TITLE
Issue with "Navigation and resource timings": Equation of Load event duration is incorrect.

### ISSUE THREAD

**Issue by bovidiu** [mdn/content#2326]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Performance/Navigation_and_resource_timings

#### What information was incorrect, unhelpful, or incomplete?

`load = timing.loadEventEnd - timing.loadEventEnd`

The above equation results in 0 and it doesn't measure the load time.

#### Specific section or headline?
Section: [Load Event Duration](https://developer.mozilla.org/en-US/docs/Web/Performance/Navigation_and_resource_timings#load_event_duration)
#### What did you expect to see?

`load = timing.loadEventEnd - timing.loadEventStart`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/performance/navigation_and_resource_timings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Performance/Navigation_and_resource_timings
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/performance/navigation_and_resource_timings/index.html
* Last commit: https://github.com/mdn/content/commit/bce51b500504bd745c64798777fc8b13f0db596e
* Document last modified: 2021-01-25T01:36:01.000Z

</details>

**Comment by bovidiu** [comment]
If what i've expected to see is correct, i can do the change and submit a PR.

**Comment by chrisdavidmills** [comment]
@bovidiu thanks for the offer to fix this, however @NegiAkash890 already fixed it. Thanks also for reporting this in the first place.

@NegiAkash890 thanks for the fix!
