### ISSUE TITLE
Issue with "UI pseudo-classes": Typo in a sentence and additional information would be helpful

### ISSUE THREAD

**Issue by flaugher** [mdn/content#2328]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes

#### What information was incorrect, unhelpful, or incomplete?
There is a typo in a sentence.  See below.

Also, further down in the same section referenced below, you show the following code:

content: '✖';
content: '✓';

It would be helpful to the reader to add a note that describes how to enter the "x" and checkmark characters from one's keyboard.

#### Specific section or headline?
"Styling controls based on whether their data is valid"

#### What did you expect to see?
I believe you meant to say the following in the first sentence of the second paragraph:
You can target form controls using the :valid and :invalid pseudo-classes.

Currently it says:
You can target from control using the :valid and :invalid pseudo-classes.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/ui_pseudo-classes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/forms/ui_pseudo-classes/index.html
* Last commit: https://github.com/mdn/content/commit/ae7855b7d2e257273ab276daa9565de2786947b1
* Document last modified: 2021-01-27T07:44:46.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this 👍

**Comment by CreaTorAlexander** [comment]
I did a PR for the grammar misstakes.

> Also, further down in the same section referenced below, you show the following code:
> 
> content: '✖';
> content: '✓';

I don't believe a note is neccessary. I think it is just some content and you can replace it for everything else like *right* or *wrong* as text.

And when you really interested how to do this then you can google it.

**Comment by rachelandrew** [comment]
Closing as fixing PR is merged.
