### ISSUE TITLE
Issue with "Visual-js game engine": Broken images

### ISSUE THREAD

**Issue by nschonni** [mdn/content#2329]
MDN URL: https://developer.mozilla.org/en-US/docs/Games/Visual-js_game_engine

#### What information was incorrect, unhelpful, or incomplete?

Running fixes from the commanline flags a few images that look like there were from a LinkedIn CDN that no longer exists
```
Skipping https://media.licdn.com/mpr/mpr/AAEAAQAAAAAAAAjQAAAAJDU2ODFjZmU3LWZlOWEtNDVhNS1hOTE0LWRhNDM4MTMzZTZlYg.png (404)
Skipping https://media.licdn.com/mpr/mpr/AAEAAQAAAAAAAAjbAAAAJDQ0MjZhOWRmLTg1Y2YtNGRhZS1iYjA3LWRmODIwYmNhZTczNw.png (404)
Skipping https://media.licdn.com/mpr/mpr/AAEAAQAAAAAAAAlmAAAAJGZkMjhjMjRlLWM0ZGItNDQ3ZS04ZDViLTkyMjlmYmJkNDM0NQ.png (404)
Skipping https://media.licdn.com/mpr/mpr/AAEAAQAAAAAAAAgoAAAAJDExNDYxY2NjLWZjZmQtNDQzMy04ZjI4LWMxODUwNTllMzVlNA.png (404)
Skipping https://media.licdn.com/mpr/mpr/AAEAAQAAAAAAAAfvAAAAJDMxMDZlZTNiLTA1MDItNDQ0ZS04OTA5LTVmNTk1YmNmMTEyNg.png (404)
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/games/visual-js_game_engine`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Visual-js_game_engine
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/games/visual-js_game_engine/index.html
* Last commit: https://github.com/mdn/content/commit/d966c94580a6dcc0ce0f7f04a95fb4ed21d37837
* Document last modified: 2021-01-23T12:35:22.000Z

</details>

**Comment by hamishwillee** [comment]
Images not on wayback machine. These would have to be regenerated (if someone thinks topic is still useful).

**Comment by chrisdavidmills** [comment]
To whoever fixes this — you'd have to recreate the images that are missing, although my immediate reaction to this is that perhaps you should check the instructions to see if this content is out of date, and if so, delete it.

**Comment by Blakelist7** [comment]
@hamishwillee Could you explain more about this issue?

**Comment by hamishwillee** [comment]
@Blakelist7 Yes. Essentially there are missing images in this page. The only way we can get them back is to actually go through the example and recreate them.  
But my first impression is that the example itself might be out of date. So when whoever takes this on does the work, they should decide whether the example is still useful and delete it if not.

**Comment by himanshugarg** [comment]
The MDN URL: [https://developer.mozilla.org/en-US/docs/Games/Visual-js_game_engine](https://developer.mozilla.org/en-US/docs/Games/Visual-js_game_engine) is no more. This may no longer be an issue.
