### ISSUE TITLE
Meta viewport should be unarchived and moved out of /Mozilla

### ISSUE THREAD

**Issue by dontcallmedom** [mdn/content#233]
I believe the content of the page at https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag is still needed and useful; I'm guessing it's been archived because it was under the /Mozilla hierarchy, but unless there is another MDN page documenting this, it feels like it should be re-instated and moved to a more appropriate place in the MDN hierarchy

**Comment by chrisdavidmills** [comment]
Yes, I agree with this.

I reckon it should probably go under https://developer.mozilla.org/en-US/docs/Web/HTML.

The source of this page is at https://github.com/mdn/archived-content/blob/main/files/en-us/mozilla/mobile/viewport_meta_tag/index.html

@peterbe, can I just pick your brains for a second on how we'd go about moving this?

I'm assuming that in a new branch I'd:

1. Copy this content into a new folder in the right place on the `content` repo.
2. Put a new redirect entry into https://github.com/mdn/content/blob/main/files/en-us/_redirects.txt for this move?
3. Submit a PR for those changes?

Is there anything else I've not considered here?

**Comment by vkWeb** [comment]
@chrisdavidmills once @peterbe confirm the steps, I'm ready to get this done.

**Comment by peterbe** [comment]
> Yes, I agree with this.
> 
> I reckon it should probably go under https://developer.mozilla.org/en-US/docs/Web/HTML.
> 
> The source of this page is at https://github.com/mdn/archived-content/blob/main/files/en-us/mozilla/mobile/viewport_meta_tag/index.html
> 
> @peterbe, can I just pick your brains for a second on how we'd go about moving this?
> 
> I'm assuming that in a new branch I'd:
> 
>     1. Copy this content into a new folder in the right place on the `content` repo.
> 
>     2. Put a new redirect entry into https://github.com/mdn/content/blob/main/files/en-us/_redirects.txt for this move?
> 
>     3. Submit a PR for those changes?
> 
> 
> Is there anything else I've not considered here?

Well, to be clear about the meaning of "copy this content"...
You need to open both the `index.html` and the `raw.html` from the mdn/archived-content/files/en-us/mozilla/mobile/viewport_meta_tag and take the front-matter from the `index.html` but the HTML from the `raw.html` and combine them into a new `index.html` file in mdn/content. 

But you can instead help @fiji-flo with the review of https://github.com/mdn/yari/pull/2244/files by trying it out in your `mdn/yari` instance. I've only tested it for a whole tree (`--foldersearch`)
But mind you, if you use that tool, it will respect the OLD folder path. So you'll want to correct that afterwards. 
E.g. 
```
▶ yarn tool unarchive /path/to/mdn/archived-content/files/en-us/mozilla/mobile/viewport_meta_tag/index.html
```

Happy to help over a Slack or Zoom session if in doubt.

**Comment by vkWeb** [comment]
@peterbe Oh, I understand the steps. I'm preparing the PR, sending soon. 

For now, I'm doing this manually by hand, later when the tool gets merged we can use it to fix further archived content.
