### ISSUE TITLE
Issue with "Insecure passwords": (short summary here please)

### ISSUE THREAD

**Issue by ALEXdiver0** [mdn/content#2330]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Insecure_passwords

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/security/insecure_passwords`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Insecure_passwords
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/security/insecure_passwords/index.html
* Last commit: https://github.com/mdn/content/commit/7d8db8578f5147417a4ec9850570f49464226d5c
* Document last modified: 2020-12-21T22:01:57.000Z

</details>

**Comment by CreaTorAlexander** [comment]
@ALEXdiver0  What is the issue on the provided site?
