### ISSUE TITLE
Missing import makes tests fail in Django Tutorial Part 10: Testing a Django web application

### ISSUE THREAD

**Issue by mireille-raad** [mdn/content#23319]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing

### What specific section or headline is this issue about?

Testing views with forms

### What information was incorrect, unhelpful, or incomplete?

The code fragment in the section on testing forms fails because there is a missed import.

### Code 
```python 
from catalog.forms import RenewBookForm

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)
...

```

### Error

```
======================================================================
ERROR: catalog.tests.test_views (unittest.loader._FailedTest.catalog.tests.test_views)
----------------------------------------------------------------------
ImportError: Failed to import test module: catalog.tests.test_views
Traceback (most recent call last):
  File "/redacted-path/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/redacted-path/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/redacted-path/locallibrary/catalog/tests/test_views.py", line 171, in <module>
    @permission_required('catalog.can_mark_returned')
     ^^^^^^^^^^^^^^^^^^^
NameError: name 'permission_required' is not defined

----------------------------------------------------------------------
```

There is a simple fix, which is adding the following import:

```from django.contrib.auth.decorators import permission_required```

### What did you expect to see?

The tests don't fully run. Adding the import fixes that issue.

### Do you have anything more you want to share?

The PR is simple, I am happy to do it if you want. It is a simple one line to insert before the `@permission_required` check.

```python 
from catalog.forms import RenewBookForm
+ from django.contrib.auth.decorators import permission_required

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)
...

```

**Comment by hamishwillee** [comment]
@mireille-raad The import should have been added above that code when you followed the tutorial in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms#view

Specifically, there is a bit of code here that you are supposed to copy into the bottom of locallibrary/catalog/views.py.

```
import datetime

>>>>>> from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from catalog.forms import RenewBookForm

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
...
```

So I believe this to be a bug in following the tutorial rather than the test code itself. 
One way to verify this is to run the tests in the project I wrote by following the tutorial - you can see the line here: https://github.com/mdn/django-locallibrary-tutorial/blob/main/catalog/views.py#L88

Thanks for taking the time to report this. I am pleased that you were able to debug the problem and solve it on your own. That's pretty much mastery of the material.

**Comment by mireille-raad** [comment]
Thank you so much for pointing out that I simply missed the import from an earlier code block. 🤦‍♀️   Sorry for wasting some of your time.

**Comment by hamishwillee** [comment]
No need to be sorry. I'm stoked that you debugged the problem yourself :-). Made it very easy for me to check and confirm that I hadn't made a mistake.
