### ISSUE TITLE
Error in documented behaviour from observed using `clear` in elements following wrapped boxes 

### ISSUE THREAD

**Issue by Prakhar0409** [mdn/content#23317]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Floats#clearing_boxes_wrapped_around_a_float

### What specific section or headline is this issue about?

Clearing boxes wrapped around a float

### What information was incorrect, unhelpful, or incomplete?

In the problem statement, MDN points to the fact that using `clear` in elements after `floating` a div in a wrapped box does not work.
```
Once again, this is because the float has been taken out of normal flow. Clearing the following element won't work as it did before. 
```
But it does work in several major browsers like brave (Version 1.46.144 Chromium: 108.0.5359.128) /firefox (108.0.1) and safari

### What did you expect to see?

I guess the behaviour in older browsers used to be what is described, but clear property does seem to work now.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/css_layout/floats`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Floats
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/floats/index.md
* Last commit: https://github.com/mdn/content/commit/1d5bdfc4d4b76e14ebe2ee970e62ea851b5c6137
* Document last modified: 2022-12-26T01:34:04.000Z

</details>

**Comment by KianYang-Lee** [comment]
@Prakhar0409 if you followed the instructions, you should end up with the expected behaviour as displayed by the article here:

![image](https://user-images.githubusercontent.com/49669630/211149967-392dbf53-e72c-4cf2-9ace-80457f9e9264.png)

You have to remove the following class:
```css
.cleared {
  clear: left;
}
```

But it does sound confusing to me with this line `Clearing the following element won't work as it did before....`, as we have removed the `clear` property. Perhaps we can come up with a better wordings.

**Comment by Prakhar0409** [comment]
Oh Agreed. That statement is certainly confusing. I did keep the `cleared` class. Alright thanks for the clarification.

**Comment by KianYang-Lee** [comment]
Maybe we can change that particular statement to something along this line:

Changing from:
`Clearing the following element won't work as it did before. This is a problem if you want the box to wrap jointly around the floated item as well as the text of the first paragraph that wraps around the float, while also having the following content cleared of the box`

to ->:

`You might expect that by jointly wrapping the floated box and the text of first paragraph that wraps around the float, you will have subsequent content to be cleared of the box. But this is not the case, as shown above.`
