### ISSUE TITLE
What exactly does "unnested" mean?

### ISSUE THREAD

**Issue by WofWca** [mdn/content#23322]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts

### What specific section or headline is this issue about?

Move event listeners

### What information was incorrect, unhelpful, or incomplete?

> Registered listeners may need to be restructured to the synchronous pattern, moved to the top-level, and unnested

What exactly does it mean? Probably that you can't put it inside an `if` block, right? What about a bare code block (like `{ alert(1); }`)? Also no? Then what about the ternary operator?

```js
(typeof browser !== 'undefined' ? browser : chrome).browser.runtime.onStartup.addListener(...
```

Or something like this:

```js
const addOnStartupListener = (...args) => browser.runtime.onStartup.addListener(...args)
addOnStartupListener(...
```

seems nested to me, no?

And would https://github.com/mozilla/webextension-polyfill work?

### What did you expect to see?

A more clear description of what works and what doesn't.

### Do you have any supporting links, references, or citations?

[Chrome docs](https://developer.chrome.com/docs/extensions/mv2/background_migration/#listeners) are as vague.

### Do you have anything more you want to share?

The polyfill seems to be working for me right now, but I don't know if I should rely on this.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/background_scripts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
* Last commit: https://github.com/mdn/content/commit/05d8b0eb3591009b6b7fee274bb7ed1bc5638f18
* Document last modified: 2022-09-14T12:03:40.000Z

</details>

**Comment by Rob--W** [comment]
A nested event in JS is to register an event listener within another callback or event listener.

The addition "and unnested" should be removed; it's already implied by being "top-level". I question why we have the content of the "Move event listeners" section. All useful information is already expressed in an earlier section, at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts#add_listeners . The statement "Listeners must be registered synchronously from the start of the page." from there summarizes the requirements.

**Comment by WofWca** [comment]
I'm not sure if the issue is fully addressed. If the only requirement is that

> "Listeners must be registered synchronously from the start of the page."

Then IMU the "top-level" part also needs to be removed, because for

```javascript
function initListeners() {
  browser.tabs.onUpdated.addListener(() => {
    // ...
  });
}
initListeners();
```

the listener is not at the top-level (it's inside the function), but it is called synchronously, which should work.
