### ISSUE TITLE
Issue with "HTTP range requests": The response to a web server URL request for the http/1.1 range specified in the current example is incorrect.

### ISSUE THREAD

**Issue by hochan222** [mdn/content#2332]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

#### What information was incorrect, unhelpful, or incomplete?

Incomplete now.

An example server specified in [mdn: developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests's Multipart ranges](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests).  
In the curl request below I was able to get the following response:  
```
curl http://www.example.com -i -H "Range: bytes=0-50, 100-150"
HTTP/1.1 206 Partial Content
Accept-Ranges: bytes
Age: 257454
Cache-Control: max-age=604800
Content-Type: text/html; charset=UTF-8
Date: Sat, 13 Feb 2021 08:40:42 GMT
Etag: "3147526947+ident"
Expires: Sat, 20 Feb 2021 08:40:42 GMT
Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
Server: ECS (sjc/16C5)
Vary: Accept-Encoding
X-Cache: HIT
Content-Length: 312


--3d6b6a416f9b5
Content-Type: text/html; charset=UTF-8
Content-Range: bytes 0-50/1256

<!doctype html>
<html>
<head>
    <title>Example Do
--3d6b6a416f9b5
Content-Type: text/html; charset=UTF-8
Content-Range: bytes 100-150/1256

eta http-equiv="Content-type" content="text/html; c
--3d6b6a416f9b5--
```

According to RFC 7233 4.1, it says:
> If multiple parts are being transferred, the server generating the 206 response MUST generate a "multipart/byteranges" payload, as defined in Appendix A, and a Content-Type header field containing the multipart/byteranges media type and its required boundary parameter.

There is no specification in the spec that it can be created without including the following header ```boundary=THIS_STRING_SEPARATES``` in any part. However, the response to my curl response has no ```boundary=THIS_STRING_SEPARATES``` part.

Are there any specifications I don't know? Or in the response above, where does the information about boundary appear?

In the MDN example, the response to the URL contains boundary. But now, when I make a request to the same web server URL, the response to the above question comes. It was the web server URL selected by the official homepage at the moment, so that there is a main reason for that, even if another response comes. Of course, the web server is wrong if it is according to the specifications, but there may be changes after that that I do not know. I asked a question to be sure. 

If the web server is implemented incorrectly, I'm requested to change to a different web server URL.

#### Specific section or headline?

HTTP/1.1 Range_requests: Multipart ranges

#### What did you expect to see?

Contain ```Content-Type: multipart/byteranges; boundary=3d6b6a416f9b5``` header with my curl response.

#### Did you test this? If so, how?

I tested it on mac with iterm, bash. The result is the same as above, there is no boundary in the content-type.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/range_requests`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/range_requests/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by mnot** [comment]
That's an implementation bug on the `https://www.example.com` site -- see, e.g., 

~~~
> curl https://www.mozilla.org/en-US/ -i -H "Range: bytes=0-50, 100-150"
HTTP/2 206 
date: Fri, 16 Jul 2021 03:48:39 GMT
content-type: multipart/byteranges; boundary=00000000000005025603
...
~~~

**Comment by sideshowbarker** [comment]
Thanks @mnot. Closing per https://github.com/mdn/content/issues/2332#issuecomment-881155698 since as far as I understand there’s no specific error in the MDN described here that needs fixing. (But if I’m incorrect, then reopening this and having further discussion would be appropriate.)
