### ISSUE TITLE
Incorrect navigation order for CSS building blocks > Cascade, specificity, and inheritance

### ISSUE THREAD

**Issue by KianYang-Lee** [mdn/content#23332]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

### What information was incorrect, unhelpful, or incomplete?

When clicking the `next` button in the bottom page of https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance, it navigates to [The box model](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model) instead of [CSS selectors](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors), which should be the next according to the content outline attached below:

![image](https://user-images.githubusercontent.com/49669630/210298783-dcdd3143-670d-4a9d-b5f9-f817573fbe07.png)

### What did you expect to see?

Navigates to [CSS selectors](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors)

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
* Last commit: https://github.com/mdn/content/commit/cc777b1616329c579055f63fb4120ccdb78f0fd2
* Document last modified: 2022-12-19T01:58:52.000Z

</details>

**Comment by dostonnabotov** [comment]
Hi, @KianYang-Lee! When inspecting the code, the next link was directing to the `box-model`. 

```md
{{PreviousMenuNext("Learn/CSS/Building_blocks/Selectors/Combinators", "Learn/CSS/Building_blocks/The_box_model", "Learn/CSS/Building_blocks")}}
```

As you've said, it should redirect to `https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors`, which can be fixed by replacing those links:

```md
{{PreviousMenuNext("Learn/CSS/Building_blocks/Selectors/Combinators", "Learn/CSS/Building_blocks/Selectors", "Learn/CSS/Building_blocks")}}
```

I would be happy to pick it up and solve this issue :)

**Comment by sideshowbarker** [comment]
> I would be happy to pick it up and solve this issue :)

@dostonnabotov 👍 please do go ahead and open a pull-request
