### ISSUE TITLE
Intent to document: WebGPU

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#23336]
I'm going to start documenting WebGPU:

* https://chromestatus.com/feature/6213121689518080 
* Specs/explainer:
  * https://gpuweb.github.io/gpuweb
  * https://gpuweb.github.io/gpuweb/wgsl
  * https://gpuweb.github.io/gpuweb/explainer

This API will first be available by default in Chrome 113 ish, but I'm going to get an early start because it is so massive.

Also see my research doc here, for more details: https://docs.google.com/document/d/10wW89xkXN_9fztLUZ9uzKoP9lMbOa02w9dG0qY7geow/edit#. This will evolve over time

**Comment by Josh-Cena** [comment]
@chrisdavidmills Any remaining work for this?

**Comment by chrisdavidmills** [comment]
I'm not sure why this got reopened; I think any other updates to WebGPU should be handled as separate work items.
