### ISSUE TITLE
Broken link on https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#test_your_skills!

### ISSUE THREAD

**Issue by KianYang-Lee** [mdn/content#23339]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

### What specific section or headline is this issue about?

Broken link

### What information was incorrect, unhelpful, or incomplete?

As shown in the image, the link below points to https://developer.mozilla.org/en-US/docs/Learn/CSS/the_box_model, which is a broken link.

![image](https://user-images.githubusercontent.com/49669630/210321649-be8dc1e2-f713-43c2-8ea1-cd9dae620fa4.png)

### What did you expect to see?

Link to correct page, which should be https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
* Last commit: https://github.com/mdn/content/commit/cc777b1616329c579055f63fb4120ccdb78f0fd2
* Document last modified: 2022-12-19T01:58:52.000Z

</details>

**Comment by bsmth** [comment]
Thanks @KianYang-Lee :+1:, would you like to have a go at fixing this via a pull request? The page source can be found here: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md

**Comment by KianYang-Lee** [comment]
OK sure, let me work on it @bsmth

**Comment by bsmth** [comment]
Thanks @KianYang-Lee for the fix!
