### ISSUE TITLE
Issue with "Cross-Origin Resource Sharing (CORS)": URL to the article "cross-origin sharing from a server perspective (with PHP code snippets)" Incorrect

### ISSUE THREAD

**Issue by dantclee** [mdn/content#2333]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

#### What information was incorrect, unhelpful, or incomplete?
The URL to the article "cross-origin sharing from a server perspective (with PHP code snippets)" is the same URL as above.  This is incorrect.

#### Specific section or headline?
"Who should read this article?"

#### What did you expect to see?
When I click the link, I expect to see another article.

#### Did you test this? If so, how?
Yes, I click on the link of "cross-origin sharing from a server perspective (with PHP code snippets)". 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/cors/index.html
* Last commit: https://github.com/mdn/content/commit/ab9358ed0569ab871e9ad702c51b07e262e8beaf
* Document last modified: 2021-01-25T11:14:10.000Z

</details>

**Comment by steggald** [comment]
Hello 
I would be happy to work on this however I'm not sure which article the link is supposed to go to instead, does the correct page exist? If so where would I find it?
Regards 
David

**Comment by dantclee** [comment]
> 
> 
> Hello
> I would be happy to work on this however I'm not sure which article the link is supposed to go to instead, does the correct page exist? If so where would I find it?
> Regards
> David

I don't know the correct link.  I suggest that you ask the author.

**Comment by steggald** [comment]
Ok, how would I find the author and not just a contributor?

**Comment by dantclee** [comment]
I do not know.

**Comment by hamishwillee** [comment]
Thanks for posting this. The fix in this case is to just remove the problem sentence, which I have done in #2464.
