### ISSUE TITLE
x, y, z - which could be between 0 and 1

### ISSUE THREAD

**Issue by andre-kornetzky** [mdn/content#23338]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate3d

### What specific section or headline is this issue about?

values

### What information was incorrect, unhelpful, or incomplete?

Is it really correct that the values for x, y and z must be in the range 0 to 1? Then rotations around the diagonal through the second and fourth quadrants would not be possible. Negative values were also used in the examples.

### What did you expect to see?

I don't know the specification. But it doesn't make mathematical sense like that.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/transform-function/rotate3d`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate3d
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/transform-function/rotate3d/index.md
* Last commit: https://github.com/mdn/content/commit/dcce3ac7d3b86a3165c5949bcf8053efea24c7a8
* Document last modified: 2022-10-25T04:34:34.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by #23381
