### ISSUE TITLE
There is no example page above in https://developer.mozilla.org/en-US/docs/Web/API/Window/personalbar

### ISSUE THREAD

**Issue by xBZZZZ** [mdn/content#23345]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/personalbar

### What specific section or headline is this issue about?

Notes

### What information was incorrect, unhelpful, or incomplete?

When you load the example page above, the browser displays the following dialog: 

### What did you expect to see?

<table border="10"><tr><th><em>example page source code here</em></th></tr></table>

When you load the example page above, the browser displays the following dialog: 

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/Window/personalbar#notes

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/personalbar`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/personalbar
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/personalbar/index.md
* Last commit: https://github.com/mdn/content/commit/671a9451b7d4ce19ea2ca2967ba79f4e4fdf2142
* Document last modified: 2022-10-28T04:09:40.000Z

</details>

**Comment by Josh-Cena** [comment]
Red: #15656, #13729
