### ISSUE TITLE
Move content from the `src` section in `@font-face` out to the sub page

### ISSUE THREAD

**Issue by bsmth** [mdn/content#23341]
> The [`src` section in `@font-face`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#src) is large, and links to a more information than the sub page [`src`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src). The docs in the sub page are nowhere near as exhaustive - they omit `format` and `tech`. 
Further, this top level doc does the `tech()` as bullets - IMO they should be definition lists to make them linkable. 

_Originally posted by @hamishwillee in https://github.com/mdn/content/pull/23085#discussion_r1052943016_

**Comment by dipikabh** [comment]
Thanks for taking this on, @bsmth 🙌
