### ISSUE TITLE
MDN glossary cannot be displayed

### ISSUE THREAD

**Issue by somlyaip** [mdn/content#23342]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies#iframes_in_detail

### What information was incorrect, unhelpful, or incomplete?

When I try the example code to embedding MDN glossary I got an error in my browser's Console:

`Refused to display 'https://developer.mozilla.org/' in a frame because it set 'X-Frame-Options' to 'deny'.`

`x-frame-options` response header is `DENY` for request `GET https://developer.mozilla.org/en-US/docs/Glossary`

### What did you expect to see?

An embedded MDN glossary

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/other_embedding_technologies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.md
* Last commit: https://github.com/mdn/content/commit/e0bc3b1323c17ae8dba3f1d7cf482f37faa36a06
* Document last modified: 2022-11-27T10:30:43.000Z

</details>

**Comment by bsmth** [comment]
Hi @somlyaip thanks for opening the issue.

This is the intended behavior of the example code. If you have a look further down on the page, there's a Security Concerns section: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies#security_concerns


>Instead of the page you expected, you'll probably see some kind of message to the effect of "I can't open this page", and if you look at the Console in the [browser developer tools](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools), you'll see a message telling you why. In Firefox, you'll get told something like The loading of "https://developer.mozilla.org/en-US/docs/Glossary" in a frame is denied by "X-Frame-Options" directive set to "DENY". This is because the developers that built MDN have included a setting on the server that serves the website pages to disallow them from being embedded inside <iframe>s (see [Configure CSP directives](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies#configure_csp_directives), below.)

The example is designed to show limitations of embedding content and how to restrict what pages people can embed in iframes in their own pages. 

I hope that helps :)

**Comment by somlyaip** [comment]
Hi @bsmth thanks for your reply. Yeah, I found your linked content right now on my own way too. Sry I was to eager 🥲 You are absolutely right, it is not an issue. But perhaps a 'usability problem'? What do you think, wouldn't be nice If you draw your student's attention to this error right below the example? Just to avoid confusion.

**Comment by bsmth** [comment]
Yeah I agree it's not the nicest way to introduce the concept. We should add a sentence that states you will find an error if you copy-paste the code directly and the explanation for this is in the article below.

**Comment by somlyaip** [comment]
Thank you. Btw, you are doing a good job 👍 MDN learning materials are awesome! Thanks for it.

**Comment by bsmth** [comment]
Thanks @somlyaip, great to hear 🙌🏻
