### ISSUE TITLE
Lead section for xml/html DOM Text Node seems to provide an incorrect example

### ISSUE THREAD

**Issue by KilianKilmister** [mdn/content#23353]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Text

### What specific section or headline is this issue about?

Lead Section

### What information was incorrect, unhelpful, or incomplete?

Claim of there only being 3 text nodes in the given example.

### What did you expect to see?

At least 5 text nodes

### Do you have any supporting links, references, or citations?

Based on opening a file with the content in a browser and running a TreeWalker over it.

### Do you have anything more you want to share?

Regarding the following section, the statement about there being only three text nodes is incorrect, right?

> To understand what a text node is, consider the following document:
>
> ```html
> <html lang="en" class="e">
>   <head>
>     <title>Aliens?</title>
>   </head>
>   <body>
>     Why yes.
>   </body>
> </html>
> ```
>
> In that document, there are three text nodes, with the following contents:
>
> - "Aliens?" (the contents of the title element)
> - "\n" (after the </head> end tag, a newline followed by a space)
> - "Why yes.\n" (the contents of the body element)
>
> Each of those text nodes is an object that has the properties and methods documented in this article.

I really don't see how that number was determined. Opening a local file with that content in a browser (Safari and Chrome) and running a TreeWalker over it will yield 5 text nodes instead. I'm astonishingly incapable with HTML, so I'm really not sure what to think.

Tree Walker:

```js
function textNodesUnder (el) {
  let node
  const res = []
  const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT, null, false)
  while ((node = walker.nextNode())) res.push(node)
  console.log(res.map(({ nodeValue }) => nodeValue))
}

textNodesUnder(document) 
```

Result:

```json
[
  "\n    ",
  "Aliens?",
  "\n  ",
  "\n  ",
  "\n    Why yes.\n  \n\n"
]
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/text/index.md
* Last commit: https://github.com/mdn/content/commit/579788ba8fe61b6c7dddaec09dee7b33d6548a4d
* Document last modified: 2022-10-10T08:54:45.000Z

</details>

**Comment by Josh-Cena** [comment]
For contributors, two ways to fix this issue:

1. Revert the code block to pre-https://github.com/mdn/content/pull/19890.

```html
<html lang="en" class="e"><head><title>Aliens?</title></head>
 <body>Why yes.
</body></html>
```

You would need to remember to add `html-nolint` to the code fence.

2. Update the explaining text so it is consistent with the new code block.

Either solution is fine.

**Comment by dostonnabotov** [comment]
Hi, @Josh-Cena! I would be happy to pick this issue and fix it.

Also, when I run that code, I got the following result:

```
[
  "\n    ", 
  "Aliens?", 
  "\n  ", 
  "\n  ", 
  "\n    Why yes.\n  ", 
  "\n"
]
```

which is little different than what @KilianKilmister has.

**Comment by Josh-Cena** [comment]
@dostonnabotov I can't get your result. Maybe you've inserted the code as a script tag?

**Comment by dostonnabotov** [comment]
> I can't get your result. Maybe you've inserted the code as a script tag?

@Josh-Cena, I linked JavaScript with the script tag `<script src="index.js"></script>`. Perhaps, it's effect on how it outputs.

If this one is the correct output (by @KilianKilmister), I can use it to update the explaining text:

```
[
  "\n    ",
  "Aliens?",
  "\n  ",
  "\n  ",
  "\n    Why yes.\n  \n\n"
]
```

**Comment by Josh-Cena** [comment]
Indeed, you are not supposed to insert the script tag. If you just open the HTML code as-is, and run the script directly in your console, you should get the right result.

**Comment by AbidemiT** [comment]
Hello @dostonnabotov were you able to resolve this? if no i will like to pick this up

**Comment by dostonnabotov** [comment]
> Hello @dostonnabotov were you able to resolve this? if no i will like to pick this up

Hi, @AbidemiT. Sorry for the delay. Yes, resolved it
