### ISSUE TITLE
"createIndex()'s objectParameters" might be correct instead of "optionalParameters"

### ISSUE THREAD

**Issue by mikecat** [mdn/content#23359]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

### What information was incorrect, unhelpful, or incomplete?

This page and some other pages (listed below) has this phrase:

> see createIndex()'s optionalParameters.

The "optionalParameters" part looks weird not to be written as "optional parameters", assuming that this simply means general parameters that are not required.

Seeing the linked page [IDBObjectStore.createIndex()](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/createIndex#parameters), I found a parameter `objectParameters`.

Therefore, I think replacing "optionalParameters" in the phrase by "objectParameters" may be better.

### What did you expect to see?

If this is the case, replace "optionalParameters" with "objectParameters" to correctly refer to the 3rd argument of `IDBObjectStore.createIndex()`.

Another option is renaming the parameter (both the `IDBObjectStore.createIndex()` page and the references) to `options` to match the specification.

### Do you have any supporting links, references, or citations?

The specification: [Indexed Database API 3.0](https://w3c.github.io/IndexedDB/#ref-for-dom-idbobjectstore-createindex%E2%91%A0)

### Do you have anything more you want to share?

Other pages with the phrase:

* [IDBIndex - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex)
* [IDBIndex.isAutoLocale - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex/isAutoLocale)
* [IDBIndex.locale - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex/locale)
* [IDBLocaleAwareKeyRange - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/IDBLocaleAwareKeyRange)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/indexeddb_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/indexeddb_api/index.md
* Last commit: https://github.com/mdn/content/commit/1e0a2838cb7781245288eec60fbf7606bb6ac8dc
* Document last modified: 2022-10-24T15:41:47.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing, @mikecat !

> Another option is renaming the parameter (both the IDBObjectStore.createIndex() page and the references) to options to match the specification.

This is a better choice I think. `options` is a pretty standard thing to call these things.
