### ISSUE TITLE
Multiple elements on `:nth-col` and `:nth-last-col` are missing or incorrect

### ISSUE THREAD

**Issue by yarusome** [mdn/content#23365]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-col

### What specific section or headline is this issue about?

Title, specifications, bowser compatibility

### What information was incorrect, unhelpful, or incomplete?

  1. The two pseudo-classes are named as `:nth-col` and `:nth-last-col` both in the titles and in the left navigation column, inconsistent with `:nth-child()`, `:nth-last-child()`, `:nth-of-type()`, `:nth-last-of-type()`.
  2. No experiment icon shows on the left of the two pseudo-classes in the navigation column.
  3. No specification links.
  4. No BCD data.

### What did you expect to see?

  1. The two pseudo-classes be named as `:nth-col()` and `:nth-last-col()` both in the titles and in the left navigation column.
  2. Experiment icons on the left of the two pseudo-classes in the navigation column.
  3. Specification links pointing to [Selector Level 4 #the-nth-col-pseudo](https://w3c.github.io/csswg-drafts/selectors/#the-nth-col-pseudo) and [Selector Level 4 #nth-last-col-pseudo](https://w3c.github.io/csswg-drafts/selectors/#nth-last-col-pseudo).
  4. BCD data on the two pseudo-classes.

**Comment by KianYang-Lee** [comment]
Good day, I can take this issue and make relevant fixes.

**Comment by sideshowbarker** [comment]
@KianYang-Lee Yes — resolving this issue should also include updating the BCD data

**Comment by KianYang-Lee** [comment]
Well @sideshowbarker I can help to resolve this issue if you can provide a simple guide or link on how to update the BCD data, as this is my first time doing this.

**Comment by dawei-wang** [comment]
Hi @KianYang-Lee, here is a link on how to update BCD: https://github.com/mdn/browser-compat-data/blob/main/docs/contributing.md#updating-the-compat-data 
The writing guidelines page may also be helpful. https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Compatibility_tables

**Comment by KianYang-Lee** [comment]
OK please assign me and I will work on this later today, thanks

**Comment by KianYang-Lee** [comment]
Refering to here [Data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md) for BCD, since as of now no browser supports this feature, it should not be added into BCD (proposed in https://github.com/mdn/browser-compat-data/pull/10619). So, point 2, 3 and 4 is not applicable anymore in this case as they should not be included in BCD yet. I have made a PR which should partially resolve this issue, for now at least.
