### ISSUE TITLE
Issue with "Window.showOpenFilePicker()": spec link appears to be broken

### ISSUE THREAD

**Issue by somebody1234** [mdn/content#2337]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker

#### What information was incorrect, unhelpful, or incomplete?
AFAICT, the spec should point [here](https://wicg.github.io/file-system-access/#api-showopenfilepicker). Currently, it appears to point to an invalid page with the title "Unknown"

#### Specific section or headline?
Specifications

#### What did you expect to see?
Link to some page, with appropriate title.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/showopenfilepicker`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/window/showopenfilepicker/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update it 👍

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander the spec information is pulled from the SpecData file inside Yari: https://github.com/mdn/yari/blob/master/kumascript/macros/SpecData.json

It looks like this spec has not been added to the spec data, hence it is not finding it, and it is coming up as "Unknown". Looks like the correct spec to be added is this: https://wicg.github.io/file-system-access/

Before you have a go at adding it, check to see if there is an existing PR to add this, which may have just been forgotten about.

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills what is the best way to check if there is a existing PR? It would be very uncomfortable checking 73 PR's manually.

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander I was going to say go to https://github.com/mdn/yari/pulls and use the filters bar to search for obvious keywords like "file system access"...

...but then I found it ;-)

https://github.com/mdn/yari/pull/2151

Looks like this was already added: https://github.com/mdn/yari/blob/master/kumascript/macros/SpecData.json#L837

But as "File System Access API", not "File System Access", hence it coming up as "Unknown" on the page.
