### ISSUE TITLE
Add sanity checks for _redirects.txt

### ISSUE THREAD

**Issue by bershanskiy** [mdn/content#234]
1. Ensure that in _redirects.txt redirect destinations actually exist
    Some redirect destinations in `_redirects.txt` do not actually exist in `content`. There probably should be a sanity-test that ensures the destination of the redirect actually exists.

<details>

<summary>Example: A bunch of non-existent links with "User:maybe"</summary>

/en-US/docs/Inbox/User:maybe	/en-US/docs/User%3Amaybe
/en-US/docs/Inbox/User:maybe/webidl_mdn	/en-US/docs/User%3Amaybe/webidl_mdn
/en-US/docs/Inbox/User:maybe/webidl_mdn/Apps_API	/en-US/docs/User%3Amaybe/webidl_mdn/Apps_API
/en-US/docs/Inbox/User:maybe/webidl_mdn/BluetoothAdapter	/en-US/docs/User%3Amaybe/webidl_mdn/BluetoothAdapter
/en-US/docs/Inbox/User:maybe/webidl_mdn/BluetoothAdapter_API	/en-US/docs/User%3Amaybe/webidl_mdn/BluetoothAdapter_API
/en-US/docs/Inbox/User:maybe/webidl_mdn/BrowserElement	/en-US/docs/User%3Amaybe/webidl_mdn/BrowserElement
/en-US/docs/Inbox/User:maybe/webidl_mdn/BrowserElementCommon	/en-US/docs/User%3Amaybe/webidl_mdn/BrowserElementCommon
/en-US/docs/Inbox/User:maybe/webidl_mdn/BrowserElementPrivileged	/en-US/docs/User%3Amaybe/webidl_mdn/BrowserElementPrivileged
/en-US/docs/Inbox/User:maybe/webidl_mdn/BrowserElement_API	/en-US/docs/User%3Amaybe/webidl_mdn/BrowserElement_API
/en-US/docs/Inbox/User:maybe/webidl_mdn/Credential	/en-US/docs/User%3Amaybe/webidl_mdn/Credential
/en-US/docs/Inbox/User:maybe/webidl_mdn/CryptoKey	/en-US/docs/User%3Amaybe/webidl_mdn/CryptoKey
/en-US/docs/Inbox/User:maybe/webidl_mdn/DOMApplication	/en-US/docs/User%3Amaybe/webidl_mdn/DOMApplication
/en-US/docs/Inbox/User:maybe/webidl_mdn/DOMApplicationsManager	/en-US/docs/User%3Amaybe/webidl_mdn/DOMApplicationsManager
/en-US/docs/Inbox/User:maybe/webidl_mdn/DOMApplicationsRegistry	/en-US/docs/User%3Amaybe/webidl_mdn/DOMApplicationsRegistry
/en-US/docs/Inbox/User:maybe/webidl_mdn/FIDOCredentialInfo	/en-US/docs/User%3Amaybe/webidl_mdn/FIDOCredentialInfo
/en-US/docs/Inbox/User:maybe/webidl_mdn/FIDOCredentials	/en-US/docs/User%3Amaybe/webidl_mdn/FIDOCredentials
/en-US/docs/Inbox/User:maybe/webidl_mdn/FIDO_API	/en-US/docs/User%3Amaybe/webidl_mdn/FIDO_API
/en-US/docs/Inbox/User:maybe/webidl_mdn/SubtleCrypto	/en-US/docs/User%3Amaybe/webidl_mdn/SubtleCrypto
/en-US/docs/Inbox/User:maybe/webidl_mdn/SubtleCrypto_API	/en-US/docs/User%3Amaybe/webidl_mdn/SubtleCrypto_API
/en-US/docs/Inbox/User:maybe/webidl_mdn/Window	/en-US/docs/User%3Amaybe/webidl_mdn/Window
/en-US/docs/Inbox/User:maybe/webidl_mdn/XMLHttpRequest	/en-US/docs/User%3Amaybe/webidl_mdn/XMLHttpRequest
/en-US/docs/Inbox/User:maybe/webidl_mdn/XMLHttpRequest_API	/en-US/docs/User%3Amaybe/webidl_mdn/XMLHttpRequest_API
</details>

2. "Compress" redirects
    If there are two redirects, pageA -> pageB and pageB -> pageC, then the first redirect should be changed to pageA -> pageC.

<details>
<summary>The first three redirect destinations should point to final destinations.</summary>

/en-US/docs/window.releaseEvents	/en-US/docs/Web/API/window.releaseEvents
/en-US/docs/window.resizeBy	/en-US/docs/Web/API/window.resizeBy
/en-US/docs/window.resizeTo	/en-US/docs/Web/API/window.resizeTo

/en-US/docs/Web/API/Window.releaseEvents	/en-US/docs/Web/API/Window/releaseEvents
/en-US/docs/Web/API/Window.resizeBy	/en-US/docs/Web/API/Window/resizeBy
/en-US/docs/Web/API/Window.resizeTo	/en-US/docs/Web/API/Window/resizeTo

</details>

**Comment by peterbe** [comment]
Yes please to all of it! 

Can you take a look at https://github.com/mdn/content/pull/269 too?

By the way, a tricky thing is that some "to-URLs" (i.e. "from-URL -> to-URL") might point to something that's outside `CONTENT_ROOT`. I.e. `archived-content`. 
So it might be tricky to break on some of these. 
But honestly, if the to-URL leads to nowhere, assuming it's not a `https://`, it really should go away or be moved to `fundamental-redirects/index.js` which is probably a better place for large clusters of redirects that are due to someone renaming a whole tree.

**Comment by himanshugarg** [comment]
Apparently the current redirect script compresses the redirects and also checks for file existence. Is there more to fix in the _redirects.txt or in the script?

**Comment by teoli2003** [comment]
I also understand that this issue is fixed. I'm going forward and closing this. Feel free to reopen, with a indication of what is still missing, if i'm mistaken.
