### ISSUE TITLE
Issue with "ParentNode.append()": (short summary here please)

### ISSUE THREAD

**Issue by angelinama** [mdn/content#2341]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append

#### What information was incorrect, unhelpful, or incomplete?
append() has return value and it returns the parentNode

#### Did you test this? If so, how?
Yes. Use chrome dev tools and tried on a jquery object

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/parentnode/append`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/parentnode/append/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I tried in Chrome dev tools and I received just undefined
![Bildschirmfoto 2021-02-14 um 08 17 08](https://user-images.githubusercontent.com/44900696/107870915-313e0100-6e9d-11eb-8d11-849f4be3b148.png)

**Comment by rachelandrew** [comment]
According to the spec it returns undefined: https://dom.spec.whatwg.org/#dom-parentnode-append

Can you show us the code you used to test this @angelinama

**Comment by angelinama** [comment]
@rachelandrew Thanks for quick response, Rachel! So what I did is something like comparing a jquery node and the return value of node.append(), they are the same node:
`var testEl = $("<ul>");
var newEl = testEl.append("<li>coffee</li>");
console.log(testEl === newEl);`

Also, the other thing is you can chain multiple append(), i.e. `testEl.append("<li>latte</li>").append("<li>milk teat</li>")`.
If append() returns no value, then after the first append(), it should give error like "Cannot read property 'append' of undefined".

**Comment by angelinama** [comment]
> I tried in Chrome dev tools and I received just undefined
> ![Bildschirmfoto 2021-02-14 um 08 17 08](https://user-images.githubusercontent.com/44900696/107870915-313e0100-6e9d-11eb-8d11-849f4be3b148.png)
> 
> Also referencing this [article](https://www.javascripttutorial.net/javascript-dom/javascript-append/#:~:text=Introduction%20to%20JavaScript%20append()%20method&text=The%20append()%20method%20has,()%20method%20implicitly%20returns%20undefined%20.)
> 
> > The append() method has no return value. It means that the append() method implicitly returns undefined.
> 
> It says the _append()_ method has no return value.

I think we are referring to different append() function here, I am referring to JQuery but this is vanilla JS. Sorry I should clarify on the description that I am referring to JQuery

**Comment by CreaTorAlexander** [comment]
@angelinama maybe I am wrong here but shouldn't you then check the JQuery's documentation?
https://api.jquery.com/append/

**Comment by rachelandrew** [comment]
Yes, I think we are talking about jQuery here and not the standard function. I'm going to close this as I don't think we need to change MDN docs.
