### ISSUE TITLE
Clarification on the change from "logical nullish assignment" to "nullish coalescing assignment"

### ISSUE THREAD

**Issue by andywillis** [mdn/content#23419]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment

### What specific section or headline is this issue about?

Both heading and content

### What information was incorrect, unhelpful, or incomplete?

It's not really clear whether "Nullish coalescing assignment" is the new name for "Logical nullish assignment". It's still referred to the latter in most circles, but the bookmark I have [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment) redirects to this page.

A paragraph explaining the change would be useful.

### What did you expect to see?

A paragraph explaining the name change since "logical nullish assignment" is still used a lot.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/nullish_coalescing_assignment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/nullish_coalescing_assignment/index.md
* Last commit: https://github.com/mdn/content/commit/0f248adcab759bdad247a5dbfb7da12dc32bce59
* Document last modified: 2022-12-13T20:26:24.000Z

</details>

**Comment by Josh-Cena** [comment]
Please see https://github.com/mdn/content/pull/21904. You are right that "Nullish coalescing assignment" is the "new name" that replaces "Logical nullish assignment".

The name we choose is purely editorial; there's no strong rationale along the line of correctness. It's only for the sake of consistency.

**Comment by andywillis** [comment]
@Josh-Cena thanks very much for the clarification.
