### ISSUE TITLE
Unable to run website following instructions on README

### ISSUE THREAD

**Issue by KianYang-Lee** [mdn/content#23452]
### MDN URL

https://github.com/mdn/content

### What specific section or headline is this issue about?

README.md

### What information was incorrect, unhelpful, or incomplete?

I tried to spin up MDN website locally by following the README guide in this repository, however it failed to spin up and the error response is as follow (during `yarn`): 

```
error /home/kianyang/repos/mdn/content/node_modules/gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /home/kianyang/repos/mdn/content/node_modules/gifsicle
Output:
⚠ Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: 1: autoreconf: not found


    at /home/kianyang/repos/mdn/content/node_modules/bin-build/node_modules/execa/index.js:231:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I did try to spin up MDN website by following README guide using Yari repository, and it works. Just wondering what is the best solution here.

### What did you expect to see?

Successful spin up of local MDN website.

**Comment by himanshugarg** [comment]
Hello [KianYang-Lee](https://github.com/KianYang-Lee). Try - `sudo apt-get install autoconf `or the equivalent for your OS.

**Comment by KianYang-Lee** [comment]
Yup it works! Thanks @himanshugarg sorry for overlooking that.
