### ISSUE TITLE
Inconsistent CSS with displayed embed examples for positioning 

### ISSUE THREAD

**Issue by KianYang-Lee** [mdn/content#23450]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Introduction

### What specific section or headline is this issue about?

Introduction to CSS layout

### What information was incorrect, unhelpful, or incomplete?

The first embed example does not mark the second box as red background (with class="positioned") while the next ones do.

#### Simple positioning example
![image](https://user-images.githubusercontent.com/49669630/211130578-9c63b169-785f-4b67-b69f-8f88f3d6fc05.png)

#### Relative positioning example
![image](https://user-images.githubusercontent.com/49669630/211130582-9532de34-afe9-4471-a252-c01918c84ff7.png)

Also, the CSS shown does not include the styling for border and color for "positioned" class, suggest to include that too to avoid confusion.

```css
.positioned {
  position: relative;
  top: 30px;
  left: 30px;
}
```

would gladly prep a PR if the moderator(s) agree with my proposed changes.

### What did you expect to see?

The  paragraph with class of "positioned" should also have red as background color to help readers better identifying the differences. Also, the border and color styling should also be included in the CSS shown too.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/css_layout/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/introduction/index.md
* Last commit: https://github.com/mdn/content/commit/7d2071f78f38f8be38888a32c599aebba348941b
* Document last modified: 2022-09-13T12:22:39.000Z

</details>

**Comment by ambujsahu81** [comment]
Also would it make more sense to change to title from `Simple positioning example` to `static positioning example` because all the example are related to the previous section which tell us - There are five types of positioning you should know about: `Static positioning , Relative positioning, Absolute positioning, Fixed positioning, Sticky positioning.`

**Comment by dipikabh** [comment]
What specific section or headline is this issue about?
[Positioning techniques](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Introduction#positioning_techniques)
