### ISSUE TITLE
-webkit-text-stroke is unexpectedly part of WHATWG standard

### ISSUE THREAD

**Issue by JakeQZ** [mdn/content#23463]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke

### What specific section or headline is this issue about?

-webkit-text-stroke

### What information was incorrect, unhelpful, or incomplete?

The content reads as if this is a W3C standard CSS property, which it is not.  It is a vendor-specific extension.  It might currently be supported by all major browsers, but that is not guaranteed to be the case in future.

### What did you expect to see?

Warnings at least including something like the following which is seen on other pages for vendor-specific CSS extensions:

> **Non-standard:** This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/-webkit-text-stroke`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/-webkit-text-stroke/index.md
* Last commit: https://github.com/mdn/content/commit/44439c7254c9da1797e4438bade0f8e8984cbc35
* Document last modified: 2022-09-27T22:38:41.000Z

</details>

**Comment by Josh-Cena** [comment]
There's indeed a WHATWG spec for it: https://compat.spec.whatwg.org/#the-webkit-text-stroke It's for compatibility, but a spec is a spec, and all conforming browsers implement it. This warrants its categorization as standardized in BCD, per [BCD policy](https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md#status-information).

**Comment by JakeQZ** [comment]
> There's indeed a WHATWG spec for it

Perhaps, then, an explanation as to why/how a vendor-prefixed property is part of a general (non-vendor-specific) spec, and reassurance that it is, would not go amiss.

I expect there are a few other properties this also applies to.

It probably wouldn't need a separate BCD flag.  The mere combination of `standard_track: true` and that it uses a vendor prefix should be sufficient.

An info box at the top of the page (where other warnings might appear) could be worded somthing like this:

> Although this property has a vendor prefix, it is part of the [specification(s)](#specifications) given below, and supported by all conforming browsers.

WDYT?

**Comment by Josh-Cena** [comment]
I'm not the right person to make decisions about making widespread content changes in CSS docs, but overall I feel like there's an over-fear of vendor-specific or proprietary features. Sometimes the continued usage of a feature necessitates it to become standardized, regardless of its apparent proprietariness. In JS, things like `__proto__` and `escape()` are deprecated (because they were once non-standard) but still standardized due to compatibility concerns. In any case, we can hear the CSS maintainers' opinion on this.

**Comment by hamishwillee** [comment]
The fact that it is marked as standard in BCD and has a link to the relevant specification is what tells you that this is indeed standard - irrespective of the odd naming. If someone wants to check the spec link that is what they will see, so there is no ambiguity.

The concern for me is that there are likely other cases; unless we can guarantee to find and add a note to all cases then adding another thing that people need to consider when looking at this I'd say no to MDN docs update. 

What wouldn't hurt is the addition of a note like the one above to BCD. That provides additional information that people can use or not, but doesn't add any expectation on how BCD will document similar cases. Make sense?

**Comment by hamishwillee** [comment]
Closing because IMO while this is "odd", it respects MDN conventions and is not ambigous.
