### ISSUE TITLE
Intent to document: Fed CM

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#23484]
I'm going to start documenting The FedCM API at some point soon:

* https://chromestatus.com/feature/6438627087220736
* Spec: https://fedidcg.github.io/FedCM/

This API was first made available in Chrome 108, with iframe support being added in 110 (https://chromestatus.com/feature/5162418615877632)

**Comment by Josh-Cena** [comment]
Should be fixed by #23675
