### ISSUE TITLE
Misleading CSS specifity calculation

### ISSUE THREAD

**Issue by veyndan** [mdn/content#23501]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#specificity_2

### What information was incorrect, unhelpful, or incomplete?

The amount of specificity a selector has is measured using three different values (or components), which can be thought of as ID, CLASS, and ELEMENT columns in the hundreds, tens, and ones place:

### What did you expect to see?

The wording of this led me to believe that 11 element selectors would trump a single class selector.

For example, using the aforementioned definition, `color: green` should be applied, when in fact `color: blue` would be applied.

```css
/* specificity: 0-0-11 = 0 hundreds + 0 tens + 11 ones ==11 */
p p p p p p p p p p p {
  color: green;
}

/* specificity: 0-1-0 = 0 hundreds + 1 tens + 0 ones ==10 */
.foo {
  color: blue
}
```

I only realised that this assumption might be wrong once I reached the following text in the same section (emphasis mine):

> Selectors 3 and 4 are competing over the styling of the link's text color. The second one wins and makes the text white because although it has one less element selector, the missing selector is swapped out for a class selector, **which has more weight than infinity element selectors**. The winning specificity is 1-1-3 vs. 1-0-4.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
* Last commit: https://github.com/mdn/content/commit/53a524bbd91f49db87d49c14f3656530f192b36d
* Document last modified: 2023-01-05T22:18:42.000Z

</details>

**Comment by Bchenevey** [comment]
I ran into this same issue, but there are some things to consider:

- The first thought exercise (hundreds, tens, ones place) is just for visualization. 
- The true weighting system is identified shortly after some examples have been provided and the reader has a chance to use the visualization method of the three columns 
- The only time this would be an issue is if the reader, on their own volition, decided to stop reading this section in between the first introduction and the true meaning.

This is a tutorial for beginners, and the way the content is laid out is meant to be easily understandable and digested as they progress through it. I am of the opinion that the current documentation is okay, and may even be more beneficial than introducing the visualization and true weights at the same time. 

What are the chances that someone gets to this point in the tutorial, stops before the real weights are introduced, and then creates a webpage where they run into this specific issue?

**Comment by Josh-Cena** [comment]
I agree with @Bchenevey. We even have a note specifically calling out for this confusion:

> For example, a million class selectors combined would not be able to overwrite the specificity of one id selector.

"Hundreds" and "tens" can be used outside of base-10 as well. We are probably dealing with "base-infinity numbers" here, where there's never carrying forward.
