### ISSUE TITLE
Modules guide explanation about read-only binding is vague

### ISSUE THREAD

**Issue by GuichiZhao** [mdn/content#23505]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

### What information was incorrect, unhelpful, or incomplete?

>Note: Although imported features are available in the file, they are read only views of the feature that was exported. You >cannot change the variable that was imported, but you can still modify properties similar to const. Additionally, these >features are imported as live bindings, meaning that they can change in value even if you cannot modify the binding unlike const.

I read the content 5 times and still can not understand what it is talking about and it seems pretty contradicted to me.
In my understanding, the feature is **read only views**, **so cannot change**. On the other hand, it **can still modify properties similar to const**

The feature can or can not be changed on the earth

### What did you expect to see?

A clear documentation

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/modules`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/modules/index.md
* Last commit: https://github.com/mdn/content/commit/8a72e8bc250e2b5d51e17bd59bc94300849c14b5
* Document last modified: 2022-12-19T01:49:48.000Z

</details>

**Comment by Josh-Cena** [comment]
The confusion comes from the words "read-only" and "change", which are very vague. Specifically, we are talking about _re-assignments_ being disallowed.

```js
import foo from "foo";

foo.bar = 1; // allowed and works as expected
foo = 2; // throws error
```

See also: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#imported_values_can_only_be_modified_by_the_exporter
