### ISSUE TITLE
Issue with "String.prototype.replaceAll()": captures of named groups are not mentioned as argument to function 

### ISSUE THREAD

**Issue by JohnyL** [mdn/content#2350]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll

#### What information was incorrect, unhelpful, or incomplete?
Captures of named groups are not mentioned as the argument to the function. It is the last argument, which comes after "string" (The whole string being examined). Also (maybe it's not important to mention), named groups _also_ appear in positional groups arguments (see the example below - group _g3_).

#### Specific section or headline?
"Specifying a function as a parameter"

#### Did you test this? If so, how?
This codes proves that last argument is an object holding all named captures (parameter _named_):
```js
const testRegex = () => {
   const str = "I love JavaScript"
   const regex = /(J)ava(S)crip(?<last>t)/g
   const str2 = str.replaceAll(regex, (match, g1, g2, g3, index, whole, named) => {
      console.log(`match: ${match}`)
      console.log(`g1: ${g1}`)
      console.log(`g2: ${g2}`)
      console.log(`g3: ${g3}`)
      console.log(`index: ${index}`)
      console.log(`whole: ${whole}`)
      console.log(named)
   })
   console.log(`str2: ${str2}`)
}
```
The output is:
![image](https://user-images.githubusercontent.com/7391680/107887631-79e6d000-6f18-11eb-82de-ab63a3e19115.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/replaceall`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/string/replaceall/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this :+1:

**Comment by alDuncanson** [comment]
Hi, is anyone assigned to this? 

I was looking for a good first issue to help with

**Comment by chrisdavidmills** [comment]
@alDuncanson thanks for the offer of help. You are now assigned!

**Comment by JohnyL** [comment]
@alDuncanson Taking into account that this is _30 minute task_ and today is May, I do _hope_ someone is assigned. 😆

**Comment by sideshowbarker** [comment]
@alDuncanson Do you still plan to work on this issue?

**Comment by alDuncanson** [comment]
Hi, sorry after I picked this up I've been a bit busy and haven't had a chance to get around to it.

I can unassign to open it for you and others 👌🏻

**Comment by Prerna237** [comment]
@chrisdavidmills : I've got this. I can fix it.

**Comment by Prerna237** [comment]
@JohnyL : There seems to be an issue. When I run your code on my Chrome's console (v89), it works fine. But when I run it on the code editor that is present on MDN pages for demos, it is throwing an error. 

![image](https://user-images.githubusercontent.com/9744854/124348793-bd14b780-dc09-11eb-8f02-2730e12c38b9.png)

When I comment out the line where 'named' is being logged out, it is working fine. Any idea what the issue could be?
