### ISSUE TITLE
Add documentation of sms: anchor links

### ISSUE THREAD

**Issue by bdombro** [mdn/content#23526]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

### What information was incorrect, unhelpful, or incomplete?

Incomplete: documentation of the sms: prefix for anchor links and what browsers support it

### What did you expect to see?

documentation of the sms: prefix for anchor links and what browsers support it

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/a`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/a/index.md
* Last commit: https://github.com/mdn/content/commit/7cc4c9d83ea081ff9214716564be6e9c34515db7
* Document last modified: 2022-12-29T00:49:03.000Z

</details>

**Comment by estelle** [comment]
It's supported in FF only (and not on iOS, as that is webkit)
https://github.com/mdn/content/pull/29101

**Comment by estelle** [comment]
fixed by https://github.com/mdn/content/pull/29101
