### ISSUE TITLE
Confusion about section - Percentage margins and padding

### ISSUE THREAD

**Issue by BigNose-Chen** [mdn/content#23540]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS

### What information was incorrect, unhelpful, or incomplete?

Hello MDN and MDN web developers!

I was learning CSS-Sizing items in CSS Chapter and found that the section Percentage margins and padding metions

> When you use margin and padding set in percentages, the value is calculated from the inline size of the containing block — therefore the width when working in a horizontal language. In our example, all of the margins and padding are 10% of the width.

When I tried the sample code and opened the development tools, I found that the margins and padding were indeed the same length. However, they are 10% of the width of their parent element (`<body>` element).

Shouldn't it state here that it is a percentage of the parent element's width? Or am I misunderstanding?

Thanks for your reply in advance! Love you all!

### What did you expect to see?

A easy explanation would be fine :) 

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS#percentage_margins_and_padding

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/sizing_items_in_css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/sizing_items_in_css/index.md
* Last commit: https://github.com/mdn/content/commit/dd52f7e4915810060d525ce62a870dcf1ae17a63
* Document last modified: 2022-11-30T07:34:47.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, it does say it's the parent element:

> the value is calculated from the inline size of the containing block

"Containing block" = "Block containing the current block" = "Parent".

**Comment by Josh-Cena** [comment]
Going to close because the terminology is proper here
