### ISSUE TITLE
Browser compatibility table for Trusted Types API not rendering

### ISSUE THREAD

**Issue by abhn** [mdn/content#23546]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

Browser compatibility table is missing
<img width="676" alt="image" src="https://user-images.githubusercontent.com/6270406/211783806-77f0a758-384a-4996-81dd-a0cefe225946.png">

### What did you expect to see?

Browser compatibility table should be displayed with the relevant details

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/trusted_types_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/trusted_types_api/index.md
* Last commit: https://github.com/mdn/content/commit/79a6c26708e50c6965c58dd325ceb3ebcd28b926
* Document last modified: 2022-12-01T14:59:16.000Z

</details>

**Comment by sideshowbarker** [comment]
What’s reported here is expected behavior. There’s not a missing table — instead, see the paragraph there, which says:

> _See the compatibility data for each of the Trusted Types API interfaces._

But maybe there’s something more we could do here to make things more clear

**Comment by abhn** [comment]
Got it, and thank you for clarifying it for me.
