### ISSUE TITLE
Minor correction: various vs varying

### ISSUE THREAD

**Issue by mattkeanny** [mdn/content#23544]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_works

### What specific section or headline is this issue about?

#what_happens_if_a_browser_encounters_css_it_doesnt_understand

### What information was incorrect, unhelpful, or incomplete?

The last sentence reads
"We will look at many more ways to support **varying** browsers in later lessons."

### What did you expect to see?

"We will look at many more ways to support **various** browsers in later lessons."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/first_steps/how_css_works`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_works
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/first_steps/how_css_works/index.md
* Last commit: https://github.com/mdn/content/commit/b9b108d8d99d7ca39676acf433058ebf0c458473
* Document last modified: 2022-12-15T22:26:45.000Z

</details>

**Comment by sideshowbarker** [comment]
@Jeymen, do you plan on opening a pull request with the fix from https://github.com/Jeymen/content/commit/6c025cb79f8ccef3680c1429d9d070aedceff6ae ?
