### ISSUE TITLE
Confusing > (&gt;) in note's hyperlink.

### ISSUE THREAD

**Issue by jhenly** [mdn/content#23568]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

### What specific section or headline is this issue about?

The `Note:` under the `Throws` section.

### What information was incorrect, unhelpful, or incomplete?

Towards the end of the note, there is a hyperlink with the following text:

`does not > restrict this value`

I'm not sure if the `&gt;` in the hyperlink is an artifact from some ill-formatted HTML or if it carries some other meaning.

### What did you expect to see?

I did not expect to see a `>` (`&gt;`) in the hyperlink text.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/getcomputedstyle`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/getcomputedstyle/index.md
* Last commit: https://github.com/mdn/content/commit/8318078e0cf65cd4d56e80376c03019dcb292dc1
* Document last modified: 2022-09-13T20:24:51.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing, @jhenly ! Yes, this is an error (introduced in https://github.com/mdn/content/pull/16282/files#diff-253c59603cb0b514c9876f5d0e82fdd1f48693bfe85182efd6a637094a9df916) and the `>` should just be deleted.
