### ISSUE TITLE
Intl Number Formatting for US currency with locale ar (arabic) shows differently in chrome and firefox

### ISSUE THREAD

**Issue by VRachna13-Github** [mdn/content#23578]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

### What specific section or headline is this issue about?

Arabic locale shows different formatting for US currency in firefox

### What information was incorrect, unhelpful, or incomplete?

In Chrome
console.log(new Intl.NumberFormat('ar', { style: 'currency', currency: 'USD' }).format(number));
// output: "US$ 123,456.79"

In firefox
console.log(new Intl.NumberFormat('ar', { style: 'currency', currency: 'USD' }).format(number));
// output: "١٢٣٬٤٥٦٫٧٩ US$"

### What did you expect to see?

Intl.NumberFormat should the below regardless of the browser
// output: "US$ 123,456.79"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/index.md
* Last commit: https://github.com/mdn/content/commit/54dc4f860070a2e9857be06d391c6c181f0a4573
* Document last modified: 2022-12-22T00:51:29.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, the behavior of `Intl` is not guaranteed to be the same across platforms, and it's not possible for MDN to document every implementation divergence. If you believe that one of the browsers' behavior is incorrect (as in, an Arabic speaker would point that out as a formatting mistake), please report it to the implementor's bug tracker.
