### ISSUE TITLE
Why it still displays 204 in your page and actually now we think it should be 200 instead of 204? Thanks for your listening and I'm waiting for answer

### ISSUE THREAD

**Issue by ly521ly** [mdn/content#23571]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

### What information was incorrect, unhelpful, or incomplete?

the status code is 204 rather than 200??

### What did you expect to see?

the response from the writer and I want to see the version 2018 for this page, when I see the page "https://github.com/Kong/kong/issues/4008"

### Do you have anything more you want to share?

https://github.com/Kong/kong/issues/4008

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/preflight_request`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/preflight_request/index.md
* Last commit: https://github.com/mdn/content/commit/ed947b2c608428b62a60f07d09dc543f732dc09b
* Document last modified: 2022-09-21T02:09:26.000Z

</details>

**Comment by sideshowbarker** [comment]
The spec doesn’t prescribe what status code to return. See https://stackoverflow.com/a/46028619 for details.

To make that all more clear, I guess we could add a new subsection to the https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request that says something about the status code for the preflight response.
