### ISSUE TITLE
Missing information about the use of nonce on CSP

### ISSUE THREAD

**Issue by halans** [mdn/content#23588]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

### What specific section or headline is this issue about?

unsafe_inline_script

### What information was incorrect, unhelpful, or incomplete?

The section describes the use of a nonce-source to only allow specific inline script blocks. 
But this nonce value is supposed to be random per HTTP request, not a static random value, identical on each request? 
To me, this isn't really reflected in the page's content as such. 

### What did you expect to see?

That the random nonce value should only be used for a single HTTP request, and should change accordingly upon each request using a cryptographically secure random token generator.

### Do you have any supporting links, references, or citations?

https://content-security-policy.com/nonce/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/script-src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/script-src/index.md
* Last commit: https://github.com/mdn/content/commit/da3a21c6c5629c2c4921ef028b0a4df4cfadf28d
* Document last modified: 2022-09-13T11:32:27.000Z

</details>

**Comment by hamishwillee** [comment]
Fixed by @arminv - thanks for posting @halans
