### ISSUE TITLE
<html> lang attribute "zh-CN", "zh-TW" does not conform BCP 47 Language Subtag Registry

### ISSUE THREAD

**Issue by WinstonSung** [mdn/content#23596]
### MDN URL

* https://developer.mozilla.org/zh-CN/
* https://developer.mozilla.org/zh-TW/

### What specific section or headline is this issue about?

`<html lang="*"`

### What information was incorrect, unhelpful, or incomplete?

* `<html lang="zh-CN" `
* `<html lang="zh-TW" `

### What did you expect to see?

* `<html lang="zh-Hans-CN" `
* `<html lang="zh-Hant-TW" `

### Do you have any supporting links, references, or citations?

* Language Subtag Registry - IANA: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
  `zh-CN` and `zh-TW` aren't listed; however, `zh-Hans-CN` and `zh-Hant-TW` are listed

### Do you have anything more you want to share?

* Might be related: https://github.com/mdn/yari/blob/b2dbb35/libs/constants/index.js#L37-L45

**Comment by yin1999** [comment]
This is the issue of the yari platform. @sideshowbarker, could you transfer this to there.

I'd like to deal with this in mdn/yari#7921.

**Comment by sideshowbarker** [comment]
> Never mind. This should related to [mdn/yari#6282](https://github.com/mdn/yari/pull/6282).

So are you saying we should still also keep this mdn/content issue open?

**Comment by yin1999** [comment]
> we still need to correct the language tags: use `zh-Hant-TW` or `zh-Hant` for locale `zh-TW`.

resolved in mdn/yari#7921.

We will get `zh-Hans` tag for `zh-CN` and `zh-Hant` tag for `zh-TW` after the next deployment.

**Comment by yin1999** [comment]
> @yin1999 , I'm a bit confused, can we close this now?

I think we could. As the lang attribute has been replaced and the localization of landing page is only the platform issue (mdn/yari#6282).

**Comment by WinstonSung** [comment]
@yin1999 

It seems the issue has been misunderstanded.

This issue is for `<hrml lang` attribute instead of `<link hreflang` .

**Comment by yin1999** [comment]
> It seems the issue has been misunderstood.
> 
> This issue is for `<html lang` attribute instead of `<link hreflang` .

Oh yes, sorry. I would create another PR to fix this. Thanks for the note :)
