### ISSUE TITLE
Issue with "How to convert code samples to be "live"": …

### ISSUE THREAD

**Issue by sidharthv96** [mdn/content#236]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Convert_code_samples_to_be_live

#### What information was incorrect, unhelpful, or incomplete?
[NeedsLiveSample](https://developer.mozilla.org/en-US/docs/tag/NeedsLiveSample) link is broken.

#### Specific section or headline?
Where does it need to be done?

#### What did you expect to see?
List of articles with Tags

#### Did you test this? If so, how?
Yes, by opening the link. It threw a `Page not found`
![image](https://user-images.githubusercontent.com/10703445/102220501-e9374800-3f06-11eb-99e4-f166a805891b.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/howto/convert_code_samples_to_be_live`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Convert_code_samples_to_be_live
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/contribute/howto/convert_code_samples_to_be_live/index.html
* Report started: 2020-12-15T00:57:07.005Z

</details>

**Comment by chrisdavidmills** [comment]
Those kinds of links aren't going to work any more, unfortunately. I've fixed this issue (for this page at least) in https://github.com/mdn/content/pull/200
