### ISSUE TITLE
Typing error : exemple for two types of quotes inside attribute values

### ISSUE THREAD

**Issue by Martininjapan** [mdn/content#23603]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started

### What specific section or headline is this issue about?

Single or double quotes?

### What information was incorrect, unhelpful, or incomplete?

`<a href="https://www.example.com" title="Isn't this fun?">A link to my example.</a>`

Type of quotes are the same. However they should be different like this : " " and ' ' 

### What did you expect to see?

`<a href="https://www.example.com" title='Isn't this fun?'>A link to my example.</a>`

**Comment by Josh-Cena** [comment]
Hi, "the other type of quote" is referring to the single quote used as an apostrophe in `"Isn't this fun?"`.
