### ISSUE TITLE
HTMLInputElement lacks documentation for selectionStart, selectionEnd, selectionDirection

### ISSUE THREAD

**Issue by sersorrel** [mdn/content#23606]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

### What specific section or headline is this issue about?

Instance properties

### What information was incorrect, unhelpful, or incomplete?

The HTMLInputElement [is defined](https://html.spec.whatwg.org/multipage/input.html#the-input-element:dom-textarea/input-selectionstart) to have selectionStart, selectionEnd, and selectionDirection properties (these are also mentioned in relation to `<input>` elsewhere on MDN, e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password#:~:text=You%20can%20also%20use%20selectionStart%20and%20selectionEnd), but these are only mentioned on [the HTMLTextAreaElement page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement).

### What did you expect to see?

I would expect to see documentation like that found on the page for HTMLTextAreaElement: https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement#:~:text=for%20the%20control.-,selectionDirection,-string%3A%20Returns

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/input.html#the-input-element:dom-textarea/input-selectionstart

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlinputelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlinputelement/index.md
* Last commit: https://github.com/mdn/content/commit/066257cb0d23e29e269703450e4b1216a65e3b26
* Document last modified: 2022-10-10T08:28:51.000Z

</details>

**Comment by MaruthiKo** [comment]
Would love to work on this issue

**Comment by Josh-Cena** [comment]
Hi @sersorrel, the properties are already documented here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#instance_properties_that_apply_only_to_visible_elements_containing_text_or_numbers Are you requesting more documentation, or are you asking for separate pages to be written for these properties?

**Comment by sersorrel** [comment]
huh, I could have sworn they weren't mentioned when I filed the issue, but that text is there even as far back as [last year](https://web.archive.org/web/20221231184709/https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement), so I guess I missed it. (maybe I stopped looking at "Instance properties related to the parent form"? no idea...)

apologies for the pointless issue!

**Comment by Josh-Cena** [comment]
Thanks, let's close this issue, then. There are a lot of pages to be written here, but they are already tracked by the broken links.
