### ISSUE TITLE
CSS “Type, class, and ID selectors”: CSS selectors subarticles should show in the left sidebar

### ISSUE THREAD

**Issue by rvass** [mdn/content#23645]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors

### What information was incorrect, unhelpful, or incomplete?

The articles are not in the sidebar

### What did you expect to see?

the articles in the sidebar

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors/type_class_and_id_selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/type_class_and_id_selectors/index.md
* Last commit: https://github.com/mdn/content/commit/dd52f7e4915810060d525ce62a870dcf1ae17a63
* Document last modified: 2022-11-30T07:34:47.000Z

</details>

**Comment by KianYang-Lee** [comment]
If referring to the guide at https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks , these are the sub-articles. Do we want them in the sidebar? It might make it a bit crowded IMO

![image](https://user-images.githubusercontent.com/49669630/212551609-8b92b70a-1bfd-47a4-adda-77c1af548ec0.png)

**Comment by hamishwillee** [comment]
This should be done at same time as https://github.com/mdn/content/issues/23538
