### ISSUE TITLE
Passing arguments by value

### ISSUE THREAD

**Issue by JuergenPurtz** [mdn/content#23653]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions

### What specific section or headline is this issue about?

Description of passing arguments by value

### What information was incorrect, unhelpful, or incomplete?

Your description of passing arguments as _passed by value_ is correct. But at some other sides (non-MDN) the argument-passing of **objects** is sometimes called _passed by reference_. I propose to emphasize in some way the paragraph where passing is described, e.g. by adding a sub-header like _Passing arguments_.

### What did you expect to see?

Some emphasizes on this issue.

### Do you have any supporting links, references, or citations?

https://www.geeksforgeeks.org/pass-by-value-and-pass-by-reference-in-javascript/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/functions/index.md
* Last commit: https://github.com/mdn/content/commit/932d29dc294a5354bdc05fce93cbd2358e7b2839
* Document last modified: 2022-12-31T03:23:48.000Z

</details>

**Comment by Josh-Cena** [comment]
The heading would be hard to insert with the current structure, because this paragraph is a natural derivative from the previous paragraph explaining the difference between parameters and arguments. What about extracting the entire "parameters and arguments" section into a new subheading?

**Comment by JuergenPurtz** [comment]
Yes, a subheading may help. Possibly it's also helpful to consider what I have written in https://en.wikibooks.org/w/index.php?title=JavaScript/Functions&stable=0#Call-by-value, especially "Note 1".
