### ISSUE TITLE
Missing attributes for the `<mo>` element

### ISSUE THREAD

**Issue by yarusome** [mdn/content#23669]
### MDN URL

https://developer.mozilla.org/docs/Web/MathML/Element/mo

### What specific section or headline is this issue about?

Attributes

### What information was incorrect, unhelpful, or incomplete?

Two attirbutes acceptable by the `<mo>` element, as specified by [MathML Core](https://www.w3.org/TR/mathml-core) (as well as legacy [MathML 3](https://www.w3.org/TR/MathML3/)), are missing, i.e. `form` and `largeop`.

### What did you expect to see?

Descriptions of these two attributes and their BCD.

### Do you have any supporting links, references, or citations?

  1. Acceptable attributes of the `<mo>` element in MathML Core: https://www.w3.org/TR/mathml-core/#operator-fence-separator-or-accent-mo
  2. The example showing use of these attributes, including `form` and `largeop`: https://www.w3.org/TR/mathml-core/#mo-example
  3. Details about the `form` attribute: https://www.w3.org/TR/mathml-core/#dfn-form
  4. Details about the `largeop` attribute: https://www.w3.org/TR/mathml-core/#ref-for-dfn-largeop-4

**Comment by fred-wang** [comment]
Thanks, I submitted some PR:

https://github.com/mdn/content/pull/23769
https://github.com/mdn/browser-compat-data/pull/18685

`form` is mentioned in the link "whose default values depend on the operator's form and content:" ; ideally we should elaborate about this on MDN.
