### ISSUE TITLE
[Web API] Updates to WebRTC RTCRtpParameters.set(get)Parameters etc

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#23677]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

There's two bugs related to web RTC so would be good to tackle them together.

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1401592
and
https://bugzilla.mozilla.org/show_bug.cgi?id=1676855

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
@Rumyra @dletorey I'm not volunteering to own this (yet). Its a mess, and since I don't understand the API I might not be the best person. I have started part of the work though - trying to work out what is delivering and updating bits of BCD.

Status:

- [ ] BCD
  - [ ]  https://github.com/mdn/browser-compat-data/pull/18832
  - [ ]  https://github.com/mdn/browser-compat-data/pull/18833
  - [ ]

**Comment by Rumyra** [comment]
I've added a note to take a better look at WebRTC moving forward - thanks @hamishwillee
