### ISSUE TITLE
Issue with "The JavaScript input interpreter": (short summary here please)

### ISSUE THREAD

**Issue by solutayo** [mdn/content#2367]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter

#### What information was incorrect, unhelpful, or incomplete?
"You can also select a range of lines in the editing pane, and run just the code on those lines."

#### Specific section or headline?
    Multi-line mode

#### What did you expect to see?
I expected that only the lines I selected will be executed, when I clicked run, rather, it executed all the code. So selecting some lines, does not have any effect.

#### Did you test this? If so, how?
I wrote four lines of JavaScript code, then I selected the last two lines, and clicked "Run"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/web_console/the_command_line_interpreter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/tools/web_console/the_command_line_interpreter/index.html
* Last commit: https://github.com/mdn/content/commit/f09df82fe5ed37804f1ba63ad3d740428cb7e552
* Document last modified: 2021-02-02T17:19:28.000Z

</details>

**Comment by chrisdavidmills** [comment]
@solutayo yes, looks like you are right here. I've tested it, and it doesn't seem to work for me either.

I've removed that line — see https://github.com/mdn/content/commit/7529c9923e0f47c32d405f79dffdf0a22d57153e

Thanks for reporting this, much appreciated!

**Comment by solutayo** [comment]
But, that capability will be of great value

**Comment by chrisdavidmills** [comment]
> But, that capability will be of great value

I agree that it would be useful, but this is not the right place to suggest new Firefox features. I'm not sure where the right place is, to be honest.

**Comment by solutayo** [comment]
Well, I think the feature was probably implemented and working, when the documentation was put in place, if not, why will it be documented! So, it is not a new feature, it is probably broken
