### ISSUE TITLE
[HTML] input type color list attribute

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#23684]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- NA - Interactive example and data repos are updated if appropriate
- NA - The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [X] Add entry to Firefox release notes if feature is enabled in release
- NA - Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

List attribute for `<input type="color">`

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=960984

## Other

- [X] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [X] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [X] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by dipikabh** [comment]
Content page exists: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

Content needs to be added for the `list` attribute and BCD and relnotes need to be updated.

Missing documentation for the `autocomplete` attribute can also be added.

**Comment by teoli2003** [comment]
Note that if a `autocomplete` attribute document is added, `HTMLInputElement.autocomplete` on the mdn-gaps list should be added simultaneously. (This should be fairly simple to be done by the person documenting the `autocomplete` attribute.

**Comment by dipikabh** [comment]
The `list` attribute is currently only supported in Firefox on Windows and Linux. 
It is not yet supported in Firefox on macOS and Android (https://bugzilla.mozilla.org/show_bug.cgi?id=1805397).

**Comment by dipikabh** [comment]
@teoli2003 Looks like there is already documentation for the autocomplete attribute (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) linked from the [input element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete) page

**Comment by teoli2003** [comment]
Ha ok. The `autocomplete` _ API property_ is missing, but it is outside the scope if you don't add the attribute here. (We'll get back to it at some point).
