### ISSUE TITLE
[CSS] Enable CSS named pages on Nightly

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#23682]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

CSS named pages need documenting, see https://drafts.csswg.org/css-page-3/

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1787947

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by dletorey** [comment]
[Content](https://github.com/mdn/content/pull/24485)
[BCD](https://github.com/mdn/browser-compat-data/pull/18922)

**Comment by dletorey** [comment]
Merged now
