### ISSUE TITLE
Code example is incorrect

### ISSUE THREAD

**Issue by Kernix13** [mdn/content#23702]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_Classes

### What specific section or headline is this issue about?

Private fields

### What information was incorrect, unhelpful, or incomplete?

Accessing the 1st index of `this.values` should be `255` but it shows as `0`. Am I missing something or should the value be 255?

```js
const red = new Color(255, 0, 0);
red.values[0] = 0;
console.log(red.values[0]); // 0
```

### What did you expect to see?

the first value of this.values should be 255.

### Do you have any supporting links, references, or citations?

Basic array bracket syntax.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/using_classes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_Classes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/using_classes/index.md
* Last commit: https://github.com/mdn/content/commit/e859bb74eb8b230a987db7a1dba3e685da0dec56
* Document last modified: 2023-01-03T03:52:41.000Z

</details>

**Comment by Josh-Cena** [comment]
Why? Line 2 in your excerpt already assigns `values[0]` as `0`.

**Comment by Josh-Cena** [comment]
I'll close it for now as it's a misunderstanding, but open to more discussions if there's something truly misleading.

**Comment by Kernix13** [comment]
Values is an array and the value at position 0 is 255. Is there something that I am missing?

**Comment by Josh-Cena** [comment]
Yes—line 2 says `red.values[0] = 0;`. Did you experiment?

**Comment by Kernix13** [comment]
I messed up - sorry to waste your time.
