### ISSUE TITLE
The page you requested was removed

### ISSUE THREAD

**Issue by Venom5001** [mdn/content#23717]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Keyboard

### What specific section or headline is this issue about?

The article doesn't show when clicked on

### What information was incorrect, unhelpful, or incomplete?

It displays only "the page you requested was removed"

### What did you expect to see?

a news article about a person left permanently disabled

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/accessibility/understanding_wcag/keyboard`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Keyboard
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/understanding_wcag/keyboard/index.md
* Last commit: https://github.com/mdn/content/commit/1e607fb7d77c5571973c0f6425492fc04e9189d5
* Document last modified: 2022-09-30T18:42:31.000Z

</details>

**Comment by bsmth** [comment]
Closing this one as it looks invalid.
