### ISSUE TITLE
Broken example for Number.MIN_VALUE

### ISSUE THREAD

**Issue by dsletten** [mdn/content#2372]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

The sample function multiply() on this page is broken: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_VALUE

First of all, Number.MIN_VALUE has nothing to do with -Infinity. The example is conceptually confused.

Moreover, any negative product of x and y will pass the test since Number.MIN_VALUE is a positive number.

**Comment by CreaTorAlexander** [comment]
I can update it 👍

**Comment by sideshowbarker** [comment]
@CreaTorAlexander Do you still plan to work on this or should we un-assign it?

**Comment by CreaTorAlexander** [comment]
@sideshowbarker I have seen I am not assigned but yes it can re-assigned :+1:

**Comment by himanshugarg** [comment]
I've created a PR in mdn/interactive-examples for this issue. Hope nothing more is required here, apart from updates on the PR, if any. Thanks

**Comment by himanshugarg** [comment]
Possible duplicate issue #7975 is closed (but the fix still isn't live yet?)

**Comment by sideshowbarker** [comment]
> Possible duplicate issue #7975 is closed but the fix still isn't live (yet?)

@teoli2003 Any idea? I would think that because #7975 was merged 16 days ago, that fix must be live in production already.

**Comment by teoli2003** [comment]
I don't know what the publication rules of mdn/interactive-examples (is this daily, or does it need an manual push?) for this repo are. I think @wbamberg will now.

**Comment by Elchi3** [comment]
Looks like deployment changed to GitHub actions recently. https://github.com/mdn/interactive-examples/pull/1889

**Comment by escattone** [comment]
Our interactive-example deployments stopped working a week or more ago when we ran out of credits within Travis. We've since moved off Travis and onto GitHub Actions, and as of this morning, deployments are working again. This example has now been updated. Sorry for the inconvenience over the last week or more. Thanks for your patience.
