### ISSUE TITLE
Is the parameter description accurate?

### ISSUE THREAD

**Issue by wxuanwxwx** [mdn/content#23733]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/DocumentType/after

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

Only one element is allowed on the document, and multiple common nodes cannot be added

### What did you expect to see?

Prompt information of only one element is allowed on the document

### Do you have any supporting links, references, or citations?

![image](https://user-images.githubusercontent.com/52122314/213063693-8105018c-65be-4024-a09e-2cd8fdea6031.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/documenttype/after`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DocumentType/after
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/documenttype/after/index.md
* Last commit: https://github.com/mdn/content/commit/4e233c16c6f0d347972c5c762f5b836318a46124
* Document last modified: 2022-09-13T05:27:14.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
The [Exceptions](https://developer.mozilla.org/en-US/docs/Web/API/DocumentType/after#exceptions) section indicates that a `DOMException` is "_Thrown when the node cannot be inserted at the specified point in the hierarchy._" It is clear enough that only valid DOM modifications are permitted by the [`after`](https://developer.mozilla.org/en-US/docs/Web/API/DocumentType/after) method. This page is the wrong location to enumerate all the HTML validity rules. Readers should be familiar with HTML basics, including [Anatomy of an HTML document](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics#anatomy_of_an_html_document).

**Comment by wbamberg** [comment]
It is confusing though. I think part of the issue here is that this is specced as a method on the [`ChildNode`](https://dom.spec.whatwg.org/#childnode) mixin, some of whose implementations (like `Element`) can take multiple parameters. We used to document this on `ChildNode`, but it got demixed (duplicated) among the implementations in https://github.com/mdn/content/pull/6432.

So now the description in the `DocumentType` page says it can take multiple parameters although (IIUC) it never actually can, and that seems confusing to me. So maybe it might be helpful to say that although the general form of this API accepts multiple nodes, in practice it can't when called on a `DocumentType`.

**Comment by Andrew-Cottrell** [comment]
> So now the description in the `DocumentType` page says it can take multiple parameters although (IIUC) it never actually can, and that seems confusing to me. So maybe it might be helpful to say that although the general form of this API accepts multiple nodes, in practice it can't when called on a `DocumentType`.

It can take multiple comment nodes in addition to the root element node. So, it might be helpful to say that here it can't accept multiple element nodes. But is it worth the effort of clarifying the contextual validity rules for each DOM manipulation method? Or can the DOM documentation assume the reader is familiar with the HTML validity rules. For example, should [`Element.after()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/after) mention it would be invalid to attempt to insert a `tbody` element when the parent is not a `table` element?

**Comment by wbamberg** [comment]
Fair enough. Let's close this then.
