### ISSUE TITLE
Nobody supports `require-sri-for` anymore

### ISSUE THREAD

**Issue by mozfreddyb** [mdn/content#23768]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-sri-for

### What specific section or headline is this issue about?

Browser support data

### What information was incorrect, unhelpful, or incomplete?

As the person who developed (and removed) `require-sri-for`, I believe this never shipped in any other browser except Firefox.

I think the current as well as the historic data is incorrect

### What did you expect to see?

Adjusted browser support data AND a general update on the article. I think it's a mere historical artifact.

### Do you have any supporting links, references, or citations?

This will need some more digging but here are some starters

https://bugs.chromium.org/p/chromium/issues/detail?id=618924#c1
https://github.com/w3c/webappsec-subresource-integrity/pull/82
https://bugzilla.mozilla.org/show_bug.cgi?id=1386214

### Do you have anything more you want to share?

Happy to help here or via email if something is unclear

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/require-sri-for`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-sri-for
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/require-sri-for/index.md
* Last commit: https://github.com/mdn/content/commit/8e1f45b8c0a3671f6e3de43c0764ad610aa345dd
* Document last modified: 2022-09-14T09:06:12.000Z

</details>

**Comment by mozfreddyb** [comment]
Apparently, Chrome implemented it, but it was always behind "experimental web platform features" before it was removed https://security.stackexchange.com/questions/180450/why-does-chrome-tell-me-that-the-csp-require-sri-for-directive-is-implemented

**Comment by wbamberg** [comment]
Our policy on MDN is that we can delete docs for features that have not been supported by any major browsers for at least 2 years. From the look of your links this feature does meet these criteria, so the cleanest thing to do is remove it. We don't in general document things for historical interest.

@mozfreddyb , does that sound to you like a reasonable solution?

**Comment by mozfreddyb** [comment]
Well, I don't have a strong prefrence. The main thing that irked me is that it was never supported in Chrome and thus never shipped anywhere fully. But the documentation seemed to say otherwise.

I'm happy with whatever resolution fits best for MDN :)
