### ISSUE TITLE
Text Change under the "Form elements and box-sizing" Heading

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#23777]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_media_form_elements

### What specific section or headline is this issue about?

Form elements and box-sizing

### What information was incorrect, unhelpful, or incomplete?

instead o the text being "...then add **these** back in when styling particular controls:" under the xxx heading, shouldn't it be "...then add **them** back in when styling particular controls:"? 
I made the text I changed bold to make it easier to spot.

### What did you expect to see?

n/a

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/images_media_form_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_media_form_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/images_media_form_elements/index.md
* Last commit: https://github.com/mdn/content/commit/dd52f7e4915810060d525ce62a870dcf1ae17a63
* Document last modified: 2022-11-30T07:34:47.000Z

</details>

**Comment by Josh-Cena** [comment]
Is there a difference? "These" is a pronoun as well—you can say "add this to the soup", so you can of course say "add these to the soup".

**Comment by jfc3-dol** [comment]
@Josh-Cena 
It could go either way. I guess it's easier to read and understand for me, at least.

**Comment by Josh-Cena** [comment]
I double checked. "These" is the only correct one in this context, because it's referring to the CSS properties below. "Them" can only refer to what's _before_ the pronoun, while "these" can refer to anything that the sentence is semantically pointing towards. I will close it as the current text is grammatically correct and the suggestion is not really a clear improvement.
