### ISSUE TITLE
Please Add :focus to the Code Example to Show Not everyone Uses a Mouse

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#23773]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_media_form_elements

### What specific section or headline is this issue about?

Styling text input elements

### What information was incorrect, unhelpful, or incomplete?

Wouldn't it be a good idea to add "**, input[type="submit"]:focus**" to the following code to show people that not everyone uses a mouse to hover and others use a keyboard?

input[type="submit"]:hover, input[type="submit"]:focus {
  background-color: #333;
}

**NOTE** - It might make sense to then add a note after the code example to explain why it is there. You also might want to have ":active" option too for other browsers, like old IE ones that someone might still be using.

### What did you expect to see?

That when I tab to the "Submit" button the focus changes and not only if I use a mouse.

### Do you have any supporting links, references, or citations?

No, only accessible/usability best practice.

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/images_media_form_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_media_form_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/images_media_form_elements/index.md
* Last commit: https://github.com/mdn/content/commit/dd52f7e4915810060d525ce62a870dcf1ae17a63
* Document last modified: 2022-11-30T07:34:47.000Z

</details>

**Comment by teoli2003** [comment]
(Note that this will only be fixed once css-examples is deployed, but that's a matter of days)
