### ISSUE TITLE
Issue with "Django Tutorial Part 8: User authentication and pe…": (short summary here please)

### ISSUE THREAD

**Issue by infinite-light** [mdn/content#2378]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication

#### What information was incorrect, unhelpful, or incomplete?

topic : project urls.
where and how to enter:
accounts/ login/ [name='login']
accounts/ logout/ [name='logout']
accounts/ password_change/ [name='password_change']
accounts/ password_change/done/ [name='password_change_done']
accounts/ password_reset/ [name='password_reset']
accounts/ password_reset/done/ [name='password_reset_done']
accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/ reset/done/ [name='password_reset_complete']
no proper guidelines

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/authentication`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/server-side/django/authentication/index.html
* Last commit: https://github.com/mdn/content/commit/edbcbfa37c7807eefc5346c734cfc55d3dcc2c8a
* Document last modified: 2021-01-25T07:12:53.000Z

</details>

**Comment by hamishwillee** [comment]
Hi, I'll try look at this Friday.

**Comment by infinite-light** [comment]
Thanks

**Comment by infinite-light** [comment]
Hi, Sorry sir.
I got the point. it is not the code, I have to enter some where. it is the error I see in browser. now i got the point. thanks for reaching me out.

**Comment by hamishwillee** [comment]
I think you're saying you no longer need help on this? I'll close then - reopen if I am incorrect.
