### ISSUE TITLE
Issue with "Base64": tons of deleted content

### ISSUE THREAD

**Issue by bulk88** [mdn/content#2380]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Base64

#### What information was incorrect, unhelpful, or incomplete?

Many links online on MDN and SO and around the web hard link to
 
https://web.archive.org/web/20200223114419/https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding

that describes binary vs utf8 vs base64 vs strings vs array buffers. The bottom 3/4ths of the archive.org page can't be found in 2021 on MDN. Since the wiki history is gone, IDK why this valuable content was deleted.

#### What did you expect to see?

Content archived by archive.org see https://web.archive.org/web/20200223114419/https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/base64`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Base64
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/glossary/base64/index.html
* Last commit: https://github.com/mdn/content/commit/e4e516b4d3e7950d5ca790de28d5796143bd5b03
* Document last modified: 2021-01-13T11:04:14.000Z

</details>

**Comment by sideshowbarker** [comment]
We fixed this in https://github.com/mdn/content/pull/6105
