### ISSUE TITLE
Please expand section on Promises.all(), to answer unresolved questions. . .

### ISSUE THREAD

**Issue by jsbiff** [mdn/content#23807]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises

### What specific section or headline is this issue about?

Promise.all()

### What information was incorrect, unhelpful, or incomplete?

In the previous example of using a Promise without .all(), you showed how to chain to then use the .json() method.

In the section for Promise.all(), you don't really show how that would combine that way, but, how are you going to make use of the data for the object you just fetch'ed, if you don't chain it?

Related is, how do you find the name of the fetcher that is being processed? Currently, the example uses a for-each loop to loop through the responses (which can be returned in any order). The example shows how to access the response url, but it would be nice to identify which response you are working with (so that you can, e.g. assign the data to a local variable for each specific URL) using something shorter than the url (although, I suppose you could assign the url strings themselves to a var, and compare the response url to the var; but it seems like you should be able to identify it some other way that doesn't require a potentially longish string compare).

### What did you expect to see?

Additional information that answers those questions.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/promises/index.md
* Last commit: https://github.com/mdn/content/commit/0c410538f50487e8b0f419e11e24ad5adb60bf36
* Document last modified: 2022-11-23T00:02:38.000Z

</details>

**Comment by wbamberg** [comment]
I'm not sure I quite understand the questions, but:

> In the previous example of using a Promise without .all(), you showed how to chain to then use the .json() method.
> 
> In the section for Promise.all(), you don't really show how that would combine that way, but, how are you going to make use of the data for the object you just fetch'ed, if you don't chain it?

As the page says "Sometimes, you need all the promises to be fulfilled, **but they don't depend on each other.**". In the previous example they do depend on each other, so it isn't really a suitable use for `all()`.

> Related is, how do you find the name of the fetcher that is being processed? Currently, the example uses a for-each loop to loop through the responses (which can be returned in any order).

I'm not really sure what "the name of the fetcher" means, but as the doc says "the then() handler is called with an array of all the responses, **in the same order that the promises were passed into all()**" , not "any order". So the API guarantees that `responses[0]` is the response for `fetchPromise1`.

**Comment by Josh-Cena** [comment]
Closing because all information is already present in the doc
