### ISSUE TITLE
"Automatically removing filling animations" and several related docs are incorrect and/or extremely confusing

### ISSUE THREAD

**Issue by ninevra** [mdn/content#23811]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Animation#automatically_removing_filling_animations

### What specific section or headline is this issue about?

Automatically removing filling animations

### What information was incorrect, unhelpful, or incomplete?

- Page says `"remove"` event is fired when animation is put into `"active"` replace state, but actually after a `"remove"` event the replace state [must be `"removed"`](https://w3c.github.io/csswg-drafts/web-animations-1/#removing-replaced-animations), and `"active"` is the initial/default state
- [`Animation.replaceState`](https://developer.mozilla.org/en-US/docs/Web/API/Animation/replaceState) page says that `"removed"` is for when an animation is "explicitly removed", but it's not clear if or how that's possible.
- The [example](https://mdn.github.io/dom-examples/web-animations-api/replace-indefinite-animations.html) doesn't actually demonstrate all of the things it claims (for example, it does not print the replace state at any relevant point).
- [`Animation.commitStyles()`](https://developer.mozilla.org/en-US/docs/Web/API/Animation/commitStyles) and the aforementioned example claim that the end state is written, but spec says the [current state](https://w3c.github.io/csswg-drafts/web-animations-1/#dom-animation-commitstyles) is written; see also #20086
- probably more things

### What did you expect to see?

Clear docs with supporting examples, terminology used in a manner consist with its meaning in the spec?

### Do you have any supporting links, references, or citations?

See links above.

### Do you have anything more you want to share?

I'm not exactly a subject matter expert here, I might be (am) very confused.

**Comment by ninevra** [comment]
I'd like to put some work into this and a couple other omissions and unclear parts of the Web Animations docs, if that would be welcome. There are a lot of little things missing or unclear.

Should I open issues for everything individually, or just for large or conceptual issues? I see the [pull request guidelines](https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests) say that PRs should only be filed with a linked issue and only after that issue receives maintainer interaction; but it doesn't look like that's actually the [norm](https://github.com/mdn/content/pulls?q=is%3Apr+is%3Aopen+-linked%3Aissue) [here](https://github.com/mdn/content/pulls?q=is%3Apr+is%3Aopen+linked%3Aissue+), and it does add a substantial amount of work.

**Comment by wbamberg** [comment]
Hey, @ninevra , thanks for offering to help!

I don't think you need to file issues for everything. I think it can help you avoid wasting effort if you put a lot of time into a PR that for whatever reason isn't needed, but if you are confident that the changes are needed (which it sounds like you are, and for good reasons) I would say go for it.

See also https://github.com/mdn/content/issues/10318 which I have been meaning to get around to for ages. I would love it if the examples here are [real live samples](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples#traditional_live_samples) and not GIFs, and that we stopped linking to outside sources for examples.

**Comment by ninevra** [comment]
Cool! Thanks for clarifying.
