### ISSUE TITLE
punctuation mark missed 

### ISSUE THREAD

**Issue by javodmutalliboev** [mdn/content#23816]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS

### What specific section or headline is this issue about?

<a href="/en-US/docs/Learn/CSS/Building_blocks">CSS building blocks</a>

### What information was incorrect, unhelpful, or incomplete?

", its time to dive a bit deeper."  

### What did you expect to see?

", it's time to dive a bit deeper." or ", it is time to dive a bit deeper."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/index.md
* Last commit: https://github.com/mdn/content/commit/4f6ba2f5a1615fe155292cac416c7ab6b9d711ec
* Document last modified: 2022-09-11T17:33:19.000Z

</details>

**Comment by Adi-ty** [comment]
I would like to take this issue can you assign it to me
