### ISSUE TITLE
Issue with "Document.exitFullscreen()": Minor spelling mistake

### ISSUE THREAD

**Issue by Master613** [mdn/content#2381]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/exitFullscreen

#### Did you test this? If so, how? No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/exitfullscreen`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/exitFullscreen
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/document/exitfullscreen/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by CreaTorAlexander** [comment]
Where is the spelling misstake?

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander  "Document Exited form Full screen mode" should be "Document Exited from Full screen mode"

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills okay, didn't see 😄  I can update it 👍

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills okay, didn't see 😄 I can update it 👍

cool, assigning you now
