### ISSUE TITLE
Almost duplicates of CSS Paged Media

### ISSUE THREAD

**Issue by yarusome** [mdn/content#23828]
### MDN URL

https://developer.mozilla.org/docs/Web/CSS/Paged_Media

### What information was incorrect, unhelpful, or incomplete?

The content on [Paged Media](https://developer.mozilla.org/docs/Web/CSS/Paged_Media) almost duplicates that on [CSS Paged Media](https://developer.mozilla.org/docs/Web/CSS/CSS_Pages).

### What did you expect to see?

The two pages be merged, preferably under the name "CSS Paged Media" since it's the name of this CSS module (although a few properties are defined in the [CSS Fragmentation Module](https://w3c.github.io/csswg-drafts/css-break/)).

**Comment by MaruthiKo** [comment]
Hi I would love to work this issue

**Comment by MaruthiKo** [comment]
So now to solve the issue:
Is merging Paged Media Content into CSS Paged Media and removing Paged Media file enough?
If there is any mistake in this approach please let me know

**Comment by Josh-Cena** [comment]
To anyone working on this, here are the steps you need to take:

1. Use `yarn content delete Web/CSS/Paged_Media --redirect Web/CSS/CSS_paged_media` to merge them.
2. The "Paged media" contains a better description that you should copy to "CSS paged media":
   > The CSS paged media module controls the presentation of content for print or any other media that splits content into discrete pages. It allows you to set page breaks, control printable area, style left and right pages differently, and control breaks inside elements.
3. The "CSS paged media" is missing the `orphans` and `widows` properties and the `page-break-*` properties need to be renamed to `break-*`.
