### ISSUE TITLE
Sintax error

### ISSUE THREAD

**Issue by Shevotool** [mdn/content#23829]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics

### What specific section or headline is this issue about?

You've been using objects all along

### What information was incorrect, unhelpful, or incomplete?

structures that we've been looking at here, albeit more complex ones than in our own basic custom examples.

this last paragraph it says "albeit more", it should say "a bit more". 

### What did you expect to see?

"a bit more

### Do you have any supporting links, references, or citations?

[You've been using objects all along](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics#youve_been_using_objects_all_along)
As you've been going through these examples, you have probably been thinking that the dot notation you've been using is very familiar. That's because you've been using it throughout the course! Every time we've been working through an example that uses a built-in browser API or JavaScript object, we've been using objects, because such features are built using exactly the same kind of object structures that we've been looking at here, albeit more complex ones than in our own basic custom examples.

**Comment by teoli2003** [comment]
Albeit is correct, it means though: https://dictionary.cambridge.org/dictionary/english/albeit

I'm going to close this issue. Albeit I'm ok with somebody submitting a simpler version of the sentence, it is not an issue and could stay like this (or be simplified).
