### ISSUE TITLE
No keyboard support on synth page.

### ISSUE THREAD

**Issue by CTimmerman** [mdn/content#23825]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Simple_synth

### What specific section or headline is this issue about?

Result

### What information was incorrect, unhelpful, or incomplete?

The sample lacks keyboard support and i could not find the sample source control flow.

### What did you expect to see?

Keyboard support like i added to my copy.

### Do you have any supporting links, references, or citations?

https://ctimmerman.github.io/synth

### Do you have anything more you want to share?

How to PR the live samples?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_audio_api/simple_synth`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Simple_synth
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_audio_api/simple_synth/index.md
* Last commit: https://github.com/mdn/content/commit/8318078e0cf65cd4d56e80376c03019dcb292dc1
* Document last modified: 2022-09-13T20:24:51.000Z

</details>

**Comment by sideshowbarker** [comment]
> How to PR the live samples?

The live sample uses the code blocks from the article itself — so if you create a PR with the requisite changes to the code blocks of the article itself, then those changes will be reflected in the live sample.
