### ISSUE TITLE
beforeunload event guide references custom event.returnValue, but that is deprecated

### ISSUE THREAD

**Issue by mvl22** [mdn/content#23837]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

### What specific section or headline is this issue about?

#examples, #browser_compatibility, #compatibility_notes

### What information was incorrect, unhelpful, or incomplete?

Three sections of this page cover use of `event.returnValue` to set a custom navigate-away message:

- The example unhelpfully shows "`return event.returnValue = "Are you sure you want to exit?";`" which people will no doubt copy and paste into their own code.
- "Activation using event.returnValue = "string";"
- "Starting with Firefox 44, Chrome 51, Opera 38, and Safari 9.1, a generic string not under the control of the webpage will be shown instead of the returned string."

However, as noted in that third point, the first example is now unhelpful as it suggests a custom message can be set.

### What did you expect to see?

The following changes are needed:

- **Most importantly**, the example giving `return event.returnValue = "Are you sure you want to exit?";` should now presumably be `return event.returnValue = '';`
- The browser compatibility table should have a new row documenting browser status showing when event.returnValue stopped being configurable with a custom message.
- `Starting with ... will be shown` should be reworded to `Since ... is shown` as the current wording implies forthcoming rather than implemented.
- The statement ``Chrome displays the string, "Do you want to leave this site? Changes you made may not be saved."`` should now read `Chrome displays the string, "Leave site? Changes you made may not be saved."`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/beforeunload_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/beforeunload_event/index.md
* Last commit: https://github.com/mdn/content/commit/a243190b798aa57b6cc08b9ef3216aed8ab9c895
* Document last modified: 2022-09-22T16:39:52.000Z

</details>

**Comment by Adi-ty** [comment]
Do you mind elaborating on how the browser compatibility table should be changed and what should be added in it.

**Comment by mvl22** [comment]
> Do you mind elaborating on how the browser compatibility table should be changed and what should be added in it.

This is definitely the least important of the changes.

My suggestion was that the current textual description:

"In older browsers, the return value of the event is displayed in this dialog. Starting with Firefox 44, Chrome 51, Opera 38, and Safari 9.1, a generic string not under the control of the webpage will be shown instead of the returned string."

be represented also in that table. That said, it could be hard to represent this in a clean way as the table implies feature presence rather than removal.

The left cell title could be "Setting of custom message 🗑️" and then the data as above, namely Firefox, Chrome, Opera and Safari all showing "❌ No". I don't know the behaviour of other browsers, but the page text also leaves that currently undefined anyway.

**Comment by Adi-ty** [comment]
Ok, can I make a PR making other changes leaving this browser compatibility table as it is

**Comment by wbamberg** [comment]
Filed https://github.com/mdn/browser-compat-data/pull/20709 for the BCD part. I think after that we should be able to remove the browser versions listed in this page.

**Comment by Josh-Cena** [comment]
This should be adequately documented now
