### ISSUE TITLE
Improving README.md mdn/content

### ISSUE THREAD

**Issue by CreaTorAlexander** [mdn/content#2384]
I was reading the README.md (maybe a bit late since I am contributing for a week 😄 )

And I was a bit confused about the step 6 inside *More substantial changes*

> Instead of having to type export EDITOR=code every time prior to yarn start, you can instead store this in your personal .env file. It might not exist so you might need to create one. For example:
> 
> echo 'EDITOR=code' >> .env
> yarn start

I think it would be helpful to tell the prospective contributor in which directory the .env should be.
From my point of view I would assume it will be in the /Users/username directory because there are also the files .zshrc .bash .bashrc .pyenv and the other configuration / enviroment files. 
I am unsure shall it be in my home directory or in the project directory?

**Comment by Ryuno-Ki** [comment]
The project directory.
The „global” environment variables for all projects would be put in your $HOME (either as `.profile`, which would also be respected on SSH into that machine, or in .bashrc/.zshrc as export).

**Comment by chrisdavidmills** [comment]
I agree that this could be clearer, so I've created a PR to add this in: https://github.com/mdn/content/pull/2388

**Comment by sideshowbarker** [comment]
Closing this issue as resolved by https://github.com/mdn/content/pull/2388
