### ISSUE TITLE
The image element is considered an inline element

### ISSUE THREAD

**Issue by gonzo-eyeball** [mdn/content#23841]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks

### What specific section or headline is this issue about?

Block level links

### What information was incorrect, unhelpful, or incomplete?

The Block level links section of the creating hyperlinks article describes images as block level elements. But images are considered inline elements.

### What did you expect to see?

I expected to see images described as inline elements.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/creating_hyperlinks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/creating_hyperlinks/index.md
* Last commit: https://github.com/mdn/content/commit/d05f7e910c03168355f5ac96ee3724edd76573f4
* Document last modified: 2022-12-19T18:38:16.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much for reporting. Would you like to create a PR with a fix? Perhaps using a `div` element even a `<p>` with the whole element surrounded rather than an img (I think that's OK, though kind of odd!)

**Comment by gonzo-eyeball** [comment]
I don't know anything about this behind the scenes stuff. I just did what mikoMK asked me to do on Mozilla Discourse.

    On Monday, January 23, 2023 at 04:40:55 PM CST, Hamish Willee ***@***.***> wrote:  
 
 


Thanks very much for reporting. Would you like to create a PR with a fix? Perhaps using a div element even a <p> with the whole element surrounded rather than an img (I think that's OK, though kind of odd!)

**Comment by hamishwillee** [comment]
Thanks. No problem. I've tagged as help wanted so someone can fix.

**Comment by hiteshvijayhv** [comment]
Can I make a PR?

**Comment by gonzo-eyeball** [comment]
I think I am supposed to respond yes so I say yes.

    On Wednesday, January 25, 2023 at 11:42:39 PM CST, Hitesh ***@***.***> wrote:  
 
 


Can I make a PR?

**Comment by hamishwillee** [comment]
If someone wants to be assigned they can add a note with their github handle here and someone will assign them. Probably me.

**Comment by gonzo-eyeball** [comment]
Okay.
Again this is stuff that I haven't learned about yet.
Craig

    On Thursday, January 26, 2023 at 03:59:22 PM CST, Hamish Willee ***@***.***> wrote:  
 
 


If someone wants to be assigned they can add a note with their github handle here and someone will assign them. Probably me.

**Comment by Adi-ty** [comment]
Hey @hamishwillee can I be assigned here my github handle is ` Adi-ty ` and also should can you elaborate on should I surround the ` <img /> ` with div ?

> If someone wants to be assigned they can add a note with their github handle here and someone will assign them. Probably me.

**Comment by hamishwillee** [comment]
@Adi-ty assigned to you. 

Yes, I think  you might put a div around the img and then the `a` around the div. That would retain most of the example. Obviously with corresponding changes to the description.

**Comment by Adi-ty** [comment]
Ok will making these changes soon

**Comment by Adi-ty** [comment]
Hey @hamishwillee I have made the changes and have made a PR you can provide review and merge if everything is good or suggest changes if needed

**Comment by estelle** [comment]
I think the tutorial has issues here. Images are indeed inline elements, so using an image as the example when the header reads "block level links" will confuse a lot of people.

the example should likely be making the h1 company name a link to the home page, and then separate out that images can also be encased in a `<a>`, and show that as a separate example.
