### ISSUE TITLE
why is ChildNode.remove() experimental and "should not be used in production code"?

### ISSUE THREAD

**Issue by danieltroger** [mdn/content#2385]
https://github.com/mdn/content/blob/main/files/en-us/web/api/childnode/remove/index.html#L8

and here in the left sidebar: https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove

IMO it has been around way too long to be considered experimental

**Comment by wbamberg** [comment]
I agree, it shouldn't be marked experimental. The fix I think is to remove the "Experimental" tag at https://github.com/mdn/content/blob/3b4fbae4677601eaa72441a0010c7906a4f9aed6/files/en-us/web/api/childnode/remove/index.html#L8. I'll do it tomorrow unless you or someone else would like to.

(Note that the BCD table also indicates experimental-ness (e.g. https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/getLayoutMap#browser_compatibility), and is more likely to be correct, so where they disagree I'd tend to trust the table.)

BTW it looks like we have 1181 pages under Web/API marked as experimental. I wonder how many really are...

**Comment by danieltroger** [comment]
Thanks for your input @wbamberg. I made a PR, don't want to let the opportunity of being listed as MDN contributor slide 😄 

> BTW it looks like we have 1181 pages under Web/API marked as experimental. I wonder how many really are...

Yeah, good question. Would be nice to have removal of experimental status automated somehow…
