### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by ccchips1949** [mdn/content#23878]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Getting_started_with_WebGL

### What specific section or headline is this issue about?

canvas will not run because .css is missing

### What information was incorrect, unhelpful, or incomplete?

I had an old copy of the shader tutorial and when I put the .css file and html file into this tutorial, it showed a blank canvas.

### What did you expect to see?

A blank canvas

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webgl_api/tutorial/getting_started_with_webgl`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Getting_started_with_WebGL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/tutorial/getting_started_with_webgl/index.md
* Last commit: https://github.com/mdn/content/commit/e826ecdcc6ff759c8441f62ef17f54bf666a4c1c
* Document last modified: 2022-12-07T12:37:36.000Z

</details>

**Comment by bsmth** [comment]
Hi @ccchips1949 thanks a lot for opening the issue. If the tutorial has been updated to exclude .css assets, then there's not much to fix from our side. You can see the latest changes to the example here: https://github.com/mdn/dom-examples/commit/b12b3a9e85747d3432135e6efa5bbc6581fc0774

You should get the latest version of the example files here and let us know how it works: https://github.com/mdn/dom-examples/tree/main/webgl-examples/tutorial/sample1

I hope that helps

**Comment by wbamberg** [comment]
Closing in the absence of a response, per https://github.com/mdn/content/issues/23878#issuecomment-1404827727.
