### ISSUE TITLE
Example not working on Safari

### ISSUE THREAD

**Issue by Legend-Master** [mdn/content#23886]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

### What information was incorrect, unhelpful, or incomplete?

> `@media (prefers-reduced-motion)`

This syntax doesn't work in Safari

### What did you expect to see?

Use `(prefers-reduced-motion: no-preference)` or `(prefers-reduced-motion: reduce)` instead

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@media/prefers-reduced-motion`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@media/prefers-reduced-motion/index.md
* Last commit: https://github.com/mdn/content/commit/580e18ec363ab91b5edf4c76f6d49a5075141191
* Document last modified: 2023-01-07T01:25:01.000Z

</details>

**Comment by hamishwillee** [comment]
How did you test - run the page with mac system preferences set? What versions of mac?

@estelle The default appears to be `reduce` for chrome and firefox if you use the media query, but the spec doesn't say this. Is there a convention for CSS - i.e. should we put default next to reduce option in the syntax?

**Comment by Legend-Master** [comment]
I don't actually have a mac/ios device, one of my friends told me my site is broken, and after some time I figured out it's because I was listening to transition event and since this media query didn't work, there's never a transition happen, and he's using iPad Safari 16.1, reduced motion no

My code was like
```css
@media not (prefers-reduced-motion) {
	dialog {
		transition: 0.2s;
	}
}
```
```ts
const shouldReduceMotion = window.matchMedia('(prefers-reduced-motion)')

export function closeDialog(dialog: HTMLDialogElement) {
	dialog.classList.add('closed')
	if (shouldReduceMotion.matches) {
		dialog.close()
	} else {
		dialog.addEventListener(
			'transitionend',
			() => {
				dialog.close()
			},
			{ once: true }
		)
	}
}
```

He didn't have reduced motion set, and `@media not (prefers-reduced-motion)` didn't match, `window.matchMedia('(prefers-reduced-motion)')` is not matched as well

**Comment by hamishwillee** [comment]
@queengooborg Is iOS Safari something you have the hardware to test this with? It's a potential BCD issue.

**Comment by queengooborg** [comment]
The example from the MDN article is working just fine for me on my iPhone with iOS 16.3, turning reduced motion to On.  Rather than using `@media not (prefers-reduced-motion) {`, try inverting your code to the following:

```css
dialog {
	transition: 0.2s;
}

@media (prefers-reduced-motion) {
	dialog {
		transition: 0;
	}
}
```

**Comment by Legend-Master** [comment]
I just tried this with my friend, so yeah, my bad, it's not `@media (prefers-reduced-motion)` not working, it's `@media not` not working on Safari, I tried to do something like `@media not (min-width: 10000px)`, it won't match either (which will definitely match on Chrome and Firefox)
