### ISSUE TITLE
The shift right operator requires a supplemental description

### ISSUE THREAD

**Issue by YangFong** [mdn/content#23883]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Right_shift

### What information was incorrect, unhelpful, or incomplete?

I've found that using the shift right operator is problematic when numeric values are larger than the 32-bit integer range.

![573f24f741b04cbd420ea7c65e5331b](https://user-images.githubusercontent.com/70502828/214574551-782de947-cfaa-4139-ba55-8657591b7008.png)

### What did you expect to see?

Hopefully a note can be added to the unexpected behavior of using the displacement operator when the value is too large.

**Comment by Josh-Cena** [comment]
We already have a mention here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc#using_bitwise_no-ops_to_truncate_numbers I think it's sufficient to add a sentence to all bitwise operation pages like:

> Do not use `>> 0` to truncate numbers to integers; use [`Math.trunc()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc#using_bitwise_no-ops_to_truncate_numbers) instead.

**Comment by Adi-ty** [comment]
> We already have a mention here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc#using_bitwise_no-ops_to_truncate_numbers I think it's sufficient to add a sentence to all bitwise operation pages like:
> 
> > Do not use `>> 0` to truncate numbers to integers; use [`Math.trunc()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc#using_bitwise_no-ops_to_truncate_numbers) instead.

Where should this message of not using `>> 0` be added on the page

**Comment by Josh-Cena** [comment]
At the end of "description" seems good to me. You can either put it in a note box or not.

**Comment by Adi-ty** [comment]
Hey @Josh-Cena please review my PR related to this check if everything is good with the note

**Comment by Josh-Cena** [comment]
Actually, I see we already have a sentence here:

> number not within the 32-bit bounds will over-/underflow.

So I'd say the current text is not too bad. #23913 is still a useful improvement, though.
