### ISSUE TITLE
'commit' does not existr and its page needs to be deleted

### ISSUE THREAD

**Issue by greggman** [mdn/content#23893]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/commit

### What specific section or headline is this issue about?

The entire page

### What information was incorrect, unhelpful, or incomplete?

The function does not exist

### What did you expect to see?

No function called `commit`

### Do you have any supporting links, references, or citations?

https://github.com/whatwg/html/issues/8777

### Do you have anything more you want to share?

https://jsgist.org/?src=f11d6ede9ad5c47a874f3c75a0ea164b

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webglrenderingcontext/commit`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/commit
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webglrenderingcontext/commit/index.md
* Last commit: https://github.com/mdn/content/commit/c575deb5f1775b532360c612a85b35a5ff9525d9
* Document last modified: 2022-09-13T06:51:25.000Z

</details>

**Comment by Kaiido** [comment]
To be clear, while there is a plan to remove it from the specs (https://github.com/whatwg/html/pull/3872) this method is implemented in Firefox as the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/commit#browser_compatibility) states.  
On a lower note, it's also accessible in Chromium under the "Experimental Web Platform features" flag.   
So stating "The function does not exist" doesn't seem entirely correct.  

I believe MDN should wait to see how https://github.com/whatwg/html/pull/3872 evolves and if this method is indeed removed from the specs, then a deprecation note should be added to this page.

**Comment by greggman** [comment]
I'd argue being under a flag is hardly "it exists". If the page is not going to be removed it should be marked as not available except with special flags

**Comment by Kaiido** [comment]
It's available in Firefox without a flag, only Chrome hides it behind a flag. The table is right.

**Comment by greggman** [comment]
It is not available in firefox without a flag. Run the test above

**Comment by Kaiido** [comment]
Oh my bad, I mixed up with the 2D one, which is available in Firefox and hidden under a flag in Chrome ([that table](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvasRenderingContext2D/commit#browser_compatibility) is also wrong then).
