### ISSUE TITLE
[MDN] JavaScript -- syntax_errors_round_two Outdated Info

### ISSUE THREAD

**Issue by kcisneros** [mdn/content#23891]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong#syntax_errors_round_two

### What information was incorrect, unhelpful, or incomplete?

The documentation says: `This time the error being reported is "TypeError: lowOrHi is null", on line 78` but when I am going through the tutorial, the error messaging being reported to me is: `number-game-errors.html:78 Uncaught TypeError: Cannot set properties of null (setting 'textContent') at HTMLInputElement.checkGuess (number-game-errors.html:78:29)`.

As a beginner, it was confusing to see the different wording. They're both `TypeError`'s and it is saying `null` but it didn't line up with what the documentation had, so I was worried something else was wrong. The fix is still the same, just this one part was different.

### What did you expect to see?

I expected to see this messaging: `number-game-errors.html:78 Uncaught TypeError: Cannot set properties of null (setting 'textContent') at HTMLInputElement.checkGuess (number-game-errors.html:78:29)`. I am using Chrome Version 109.0.5414.87 (Official Build) (x86_64) and am on Mac OS Ventura 13.1.

### Do you have anything more you want to share?

If other folks are seeing the same thing, I can open a PR to update the wording and attach a new screenshot. Thank you for taking time to look into this.

This screenshot below is what I am seeing on my end with the different messaging:

<img width="406" alt="syntax_errors_round_two" src="https://user-images.githubusercontent.com/16183934/214703815-de24dd57-2492-4159-a4ef-00d15655198d.png">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/what_went_wrong`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/what_went_wrong/index.md
* Last commit: https://github.com/mdn/content/commit/83902c1d651951f01bb5ed9bde2a393f07904049
* Document last modified: 2022-11-17T06:05:23.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing, and sorry to take so long to look at this.

The main issue here is that the exact error message logged varies from one browser to another. So in this case, Chrome gives us:

> Uncaught TypeError: Cannot set properties of null (setting 'textContent')

...but Firefox gives us:

> Uncaught TypeError: can't access property "textContent", lowOrHi is null

The "TypeError" bit you can rely on being the same from one browser to another, but the part after that can vary (and can vary even across two versions of the same browser - even the Firefox message quoted above is not quite the same as that given in the page).

So it would probably be good for this page to acknowledge this, giving some alternative messages for different browsers, and making it clear that the exact wording might differ. We should also update these screenshots, they're pretty out of date.
