### ISSUE TITLE
Fix a typo: Array's method to Array like method

### ISSUE THREAD

**Issue by MAHIN0093** [mdn/content#23905]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments

### What specific section or headline is this issue about?

arguments is an array-like object

### What information was incorrect, unhelpful, or incomplete?

arguments is an array-like object, which means that arguments has a [length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/length) property and properties indexed from zero, but it doesn't have [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array)'s built-in methods like [forEach()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) or [map()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map).

### What did you expect to see?

arguments is an array-like object, which means that arguments has a [length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/length) property and properties indexed from zero, but it doesn't have [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) like built-in methods like [forEach()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) or [map()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map).

**Comment by Adi-ty** [comment]
Please assign this to me

**Comment by Josh-Cena** [comment]
See #23905
