### ISSUE TITLE
issue with Example of this with Callbacks in strict mode, especially the output of setTimeout `undefined` is wrong

### ISSUE THREAD

**Issue by MananDesai54** [mdn/content#23928]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#callbacks

### What information was incorrect, unhelpful, or incomplete?

information was incorrect, 
```
function logThis() {
  "use strict";
  console.log(this);
}

[1, 2, 3].forEach(logThis); // undefined, undefined, undefined
setTimeout(logThis, 1000); // undefined
```
Here the output of `setTimeout(logThis, 1000);` is undefined which is wrong

### What did you expect to see?

Here the output of `setTimeout(logThis, 1000);` is undefined but after running it the actual output is `window`

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/questions/73457834/why-does-a-callback-in-settimeout-have-this-window-even-in-strict-mode
https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-settimeout-dev

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/this`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/this/index.md
* Last commit: https://github.com/mdn/content/commit/0f248adcab759bdad247a5dbfb7da12dc32bce59
* Document last modified: 2022-12-13T20:26:24.000Z

</details>

**Comment by Josh-Cena** [comment]
Thanks for the report. I should have tested my code 😅 This could be fixed by both updating the [`setTimeout()`](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout) reference, and, in lack of a better example, removing the `setTimeout(logThis, 1000)` line.
