### ISSUE TITLE
Example Links Under the "Styling some links" Heading are Only Using Color to Denote a Link

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#23934]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links

### What specific section or headline is this issue about?

Styling some links

### What information was incorrect, unhelpful, or incomplete?

The example links for Firefox, Chrome, and Edge under the "Styling some links" section heading only uses color to denote it's a link. The same issues applies to the "Including Icons on Links".

Only using color to denote the links is difficult for those with color deficiency/ are colorblind to tell the difference between the link and standard text. Looking at the current at first, I didn't realize visually that there were links until I looked closer and saw they were green.

For the starting example, it might make sense to have underlines or some other means than only color. Then when you navigate to the links, the underline will go away.

### What did you expect to see?

I expected links to not only be denoted by color and have an underline or other visual way too.

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/styling_text/styling_links`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/styling_text/styling_links/index.md
* Last commit: https://github.com/mdn/content/commit/56ea541086af91e970f89550da86d8ba47b6e0cb
* Document last modified: 2022-11-15T02:27:08.000Z

</details>

**Comment by Sriparno08** [comment]
Hey, I would like to work on this!

**Comment by wbamberg** [comment]
Thanks you @Sriparno08 , please go ahead! It might also be worth choosing a more contrasting color for the links, I could hardly see the difference.

**Comment by Sriparno08** [comment]
Alright, @wbamberg! Let's see what I can do!

**Comment by Sriparno08** [comment]
Hey @wbamberg, how's it looking?

![Screenshot 2023-01-28 124959](https://user-images.githubusercontent.com/89148144/215252886-79d6cc77-85be-4a95-a293-91d68e305e51.png)

I haven't added an underline yet as the hover mode already has one, created using border-bottom. So, it was looking kind of odd. Hence, I went for this version!

**Comment by jfc3-dol** [comment]
@wbamberg 

Color shouldn't be the only way to denote a link.

So it would be best if you started with the underline being there on the link and then removed it when a user either hovers or focuses on the link.

**Comment by wbamberg** [comment]
@Sriparno08 , thanks! As @jfc3-dol says, if the links aren't underlined then it can be hard for people to tell that they are links.

Also it would be best to file a PR and ask for feedback that way.

**Comment by Sriparno08** [comment]
Hey, I have made a PR! Check it out!
