### ISSUE TITLE
Printing guide lacks information under media queries section

### ISSUE THREAD

**Issue by novellac** [mdn/content#23968]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Guide/Printing

### What specific section or headline is this issue about?

Using media queries to improve layout

### What information was incorrect, unhelpful, or incomplete?

There is a headline, but no information in the section.

### What did you expect to see?

I expected to see:
- An explanation of why users might want to use a media query for print
- Instructions on how to use the print media query (could be an expansion of [Targeting media types](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#targeting_media_types), or just a link to it)
- Information on browser support for the print query
- If applicable, any tips for differing common paper sizes (A4 vs 8x11, etc.)

### Do you have any supporting links, references, or citations?

[Link to the heading in question](https://developer.mozilla.org/en-US/docs/Web/Guide/Printing#using_media_queries_to_improve_layout)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/guide/printing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Printing
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/printing/index.md
* Last commit: https://github.com/mdn/content/commit/1f3cb2a075350c2e85fbe59a5594180590e30ebf
* Document last modified: 2022-11-29T01:41:15.000Z

</details>

**Comment by MaruthiKo** [comment]
Would Love to work on this issue
