### ISSUE TITLE
Document CharacterData

### ISSUE THREAD

**Issue by Elchi3** [mdn/content#2396]
https://developer.mozilla.org/en-US/docs/Web/API/CharacterData is incomplete. None of the sub pages exist but they should. CharacterData is a core DOM API that is well supported and that should have proper docs.

This came up in https://github.com/mdn/content/pull/2394 where I removed the weird NonDocumentTypeChildNode mixin, so don't worry about that anymore.

CharacterData is the parent interface for Text, ProcessingInstruction, and Comment nodes, so when creating the pages and example code, you probably want to show how to use CharacterData methods like `appendData()` with something concrete like  https://developer.mozilla.org/en-US/docs/Web/API/Text nodes.

**Comment by Ryuno-Ki** [comment]
Is there a list of all pages that are missing?

**Comment by rachelandrew** [comment]
@Ryuno-Ki yup, just look at the page, the ones highlighted in red are not written. Usually with these interface pages, whoever documented the interface will add all of the links to the missing property pages.

BCD will also expose this to you if the BCD has been completed for everything in the API, or ideally take a look at the spec to check. There are a lot of interfaces that are like this.

**Comment by Elchi3** [comment]
Yep, what Rachel says. BCD is already complete for this one.

**Comment by Ryuno-Ki** [comment]
Oh, okay. I thought we would have a meta-issue for tracking them.

**Comment by Elchi3** [comment]
This got done 🎉
