### ISSUE TITLE
“Block and inline layout in normal flow”: Misleading Statement

### ISSUE THREAD

**Issue by joelc0193** [mdn/content#23979]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flow_Layout/Block_and_Inline_Layout_in_Normal_Flow

### What specific section or headline is this issue about?

Elements participating in an inline formatting context

### What information was incorrect, unhelpful, or incomplete?

that content now defines the height of the line box on that line.

### What did you expect to see?

since that content spans two lines, it now defines the height of the line boxes on those two lines.

### Do you have anything more you want to share?

The <strong> element changes the height of two line boxes not one.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_flow_layout/block_and_inline_layout_in_normal_flow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flow_Layout/Block_and_Inline_Layout_in_Normal_Flow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_flow_layout/block_and_inline_layout_in_normal_flow/index.md
* Last commit: https://github.com/mdn/content/commit/71c4bc0b6329ec40ddbefd8d3124547e91cfa612
* Document last modified: 2022-09-28T03:40:57.000Z

</details>

**Comment by MaruthiKo** [comment]
Hi, I would like to work on this issue
