### ISSUE TITLE
Why is the "Changing element levels" section in the "Inline elements" doc not also in the "Block-level elements" doc?

### ISSUE THREAD

**Issue by joelc0193** [mdn/content#23974]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements

### What specific section or headline is this issue about?

N/A

### What information was incorrect, unhelpful, or incomplete?

N/A

### What did you expect to see?

[This section](https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements#changing_element_levels) should also be in this doc.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements#changing_element_levels

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/block-level_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/block-level_elements/index.md
* Last commit: https://github.com/mdn/content/commit/4a2b6cafbf9bc5b006eedbdf0e9fdf2c8626d5b6
* Document last modified: 2023-01-18T07:45:13.000Z

</details>

**Comment by MaruthiKo** [comment]
Hi, I would love to work on this issue
