### ISSUE TITLE
“Layout and the containing block”: Block container inserted into article but never defined

### ISSUE THREAD

**Issue by joelc0193** [mdn/content#23972]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block

### What specific section or headline is this issue about?

Identifying the containing block, Some examples

### What information was incorrect, unhelpful, or incomplete?

First says:

Most often, the containing block is the [content area](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model#content_area) of an element's nearest [block-level](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements) ancestor.

Then later says:

In this example, the paragraph is statically positioned, so its containing block is [`<section>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) because it's the nearest ancestor that is a block container.

### What did you expect to see?

The definition of "block container" somewhere earlier in the article.

First it is said that the containing block is the content area of the element's nearest **block-level** ancestor. Then is says that the reason that `<section>` is the containing block of `<p>` is because it is a **block container**.

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/a/75091021/8386132

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/containing_block`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/containing_block/index.md
* Last commit: https://github.com/mdn/content/commit/71c4bc0b6329ec40ddbefd8d3124547e91cfa612
* Document last modified: 2022-09-28T03:40:57.000Z

</details>

**Comment by MaruthiKo** [comment]
Hi I would like to work on this issue

**Comment by Josh-Cena** [comment]
Should be fixed by https://github.com/mdn/content/pull/24298
