### ISSUE TITLE
Custom Validity not Showing

### ISSUE THREAD

**Issue by raulvillajr95** [mdn/content#23998]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation

### What specific section or headline is this issue about?

Limiting the size of a file before its upload

### What information was incorrect, unhelpful, or incomplete?

The example doesn't actually show a custom validity message when you upload a file over 75kB

### What did you expect to see?

A custom validity message

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/constraint_validation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/constraint_validation/index.md
* Last commit: https://github.com/mdn/content/commit/4a2b6cafbf9bc5b006eedbdf0e9fdf2c8626d5b6
* Document last modified: 2023-01-18T07:45:13.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. Fixed now by https://github.com/mdn/content/pull/34129
