### ISSUE TITLE
The syntax of avc1 codec parameter should be 'avc1.[PPCCLL]'

### ISSUE THREAD

**Issue by dreifachstein** [mdn/content#24012]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter

### What specific section or headline is this issue about?

Codec options by container

### What information was incorrect, unhelpful, or incomplete?

> avc1.oo[.PPCCLL] (AVC video)

The `.oo` part should be removed. PPCCLL is OTI for avc1.

### What did you expect to see?

avc1[.PPCCLL] (AVC video)

### Do you have any supporting links, references, or citations?

RFC 6381:
>   ... the second element
>   (referred to as 'avcoti' in the formal syntax) is the hexadecimal
>   representation of the following three bytes in the (subset) sequence
>   parameter set Network Abstraction Layer (NAL) unit specified in
>   [[AVC](https://datatracker.ietf.org/doc/html/rfc6381#ref-AVC)]:
>    (1)  profile_idc,
>.   (2)  the byte containing the constraint_set flags (currently
>           constraint_set0_flag through constraint_set5_flag, and the
>           reserved_zero_2bits), and
>    (3)  level_idc.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/media/formats/codecs_parameter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/media/formats/codecs_parameter/index.md
* Last commit: https://github.com/mdn/content/commit/e60194342c9666ad8a2e6e5e6c25705fe818bcde
* Document last modified: 2023-01-16T17:27:46.000Z

</details>

**Comment by MaruthiKo** [comment]
Hi, I would love to work on this issue
