### ISSUE TITLE
Link points to itself

### ISSUE THREAD

**Issue by zeritonius** [mdn/content#24016]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

### What specific section or headline is this issue about?

Link points to itself

### What information was incorrect, unhelpful, or incomplete?

`Note: The property names in this index do not include the [JavaScript names](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#index) where they differ from the CSS standard names.`
The link to JavaScript names points to itself.

### What did you expect to see?

I was expecting to see a different page, containg info about the JavaScript names. More exactly, I was expecting to see how CSS properties names are transformed into JavaScript names, like animation-timing-function turning into animationTimingFunction

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/reference/index.md
* Last commit: https://github.com/mdn/content/commit/4d06fc1379fdb3d032b02e6dcc6e7e7fab72954e
* Document last modified: 2023-01-05T20:15:41.000Z

</details>

**Comment by MaruthiKo** [comment]
Hi I would love to work on this issue
