### ISSUE TITLE
Using fetch: explain more about what body/header does

### ISSUE THREAD

**Issue by JTtime** [mdn/content#24043]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

### What specific section or headline is this issue about?

Explaination of Body

### What information was incorrect, unhelpful, or incomplete?

Body is that part of fetch POST method, which is actually passed to the server. Nowhere it is written which will hint to the necessity of the body. Even in fetch(https://developer.mozilla.org/en-US/docs/Web/API/fetch)

As a newbie, I was clueless as what part of fetch(url, { options }) is supplied to the body containing user data. Experience Professional may not need that explaination, but as a newbie trying to learn from MDN Docs will definitely search for that information. 

### What did you expect to see?

purpose of body and header options inside fetch (POST) method
I think, body is that part of fetch data, for which fetch POST operation exists. so,  pls give due importance to that part
regarding header, I am still clueless as what difference it makes if I dont include header or what all options I can use inside header

### Do you have any supporting links, references, or citations?

Unfortunately, after surfing google, I realised that most of the articles on fetch is written by professionals and all have ignored the fact that, newbies will not assume neccessity of body and headers

### Do you have anything more you want to share?

.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/fetch_api/using_fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fetch_api/using_fetch/index.md
* Last commit: https://github.com/mdn/content/commit/1511e914c6b1ce6f88056bfefd48a6aa585cebce
* Document last modified: 2022-09-09T05:10:34.000Z

</details>

**Comment by wbamberg** [comment]
https://github.com/mdn/content/commit/47767e72f8ba04ca936d53d480c9dcedc2db9687 in https://github.com/mdn/content/pull/34278 is trying to fix this issue.
