### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by pcwSlide** [mdn/content#24041]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API

### What specific section or headline is this issue about?

 event output page - no variables

### What information was incorrect, unhelpful, or incomplete?

I am assuming the web storage page set variables with localStorage.
I assumed the event output page would show the data - I could change it - go back and the changes would be seen.

### What did you expect to see?

Data in the  event output page

### Do you have anything more you want to share?

I am actually tracking down why the File protocol does not work with local storage. I see it's part of the specification and you guys have decided to leave it opaque.

The problem is it works in all the other main browsers and to my students - look bad, Can I use a content policy rule to read and write to a folder using File in Firefox?

Thanks

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_storage_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_storage_api/index.md
* Last commit: https://github.com/mdn/content/commit/01d83d9cabd8d7861af35e118af3b8f83ba937ce
* Document last modified: 2022-09-21T00:43:09.000Z

</details>

**Comment by pcwSlide** [comment]
What I mean is reading localstorage from 2 different tabs in Firefox. Works elsewhere.

**Comment by pcwSlide** [comment]
Sorry..
This is the main page: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API
This is linked from that page: https://mdn.github.io/dom-examples/web-storage/ 

Using the latest firefox and the second link above I set some data
![image](https://user-images.githubusercontent.com/4927646/217242607-f377aeb2-e212-4c12-a921-04d8f8ef72bd.png)

Then I clicked on the Storage Event Output link.  
![image](https://user-images.githubusercontent.com/4927646/217243313-5ce68a0f-d883-43e2-b9b3-2092dbe223ce.png)

The idea I assume is that the localStorage data will be read by the second page? Of course it is not - I know why. I am reporting to you that it is not working.
Can you follow this? Am I not understanding the process?

**Comment by bsmth** [comment]
Hi @pcwSlide, if you keep both tabs open and change the values in the "Web storage" page, you should be able to see this updated in the "event output" page:

![image](https://user-images.githubusercontent.com/43580235/217256415-438309c6-d85b-4c98-a423-4c56197a2eaf.png)

Does that make sense?

**Comment by pcwSlide** [comment]
What browser are you using?

**Comment by pcwSlide** [comment]
Firefox 109.0.1 (64-bit) Win 10
Ahh ok - if you have both tabs open - make the changes - simple go to the other tab.
This to me is not intuitive nor the way we use the web. I assumed you would enter the data and click to see it read on the other window. Also - why does this not work?

**Comment by bsmth** [comment]
Hi @pcwSlide - the event page updates when storage events occur (a change happens) : https://github.com/mdn/dom-examples/blob/main/web-storage/event.js

It does not populate this form with any items currently in the storage by default. There is an event listener which triggers updates to the form when storage is modified: https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event

I would close this issue now as, let me know if that answers your questions. :)
