### ISSUE TITLE
<input type="week"> doc: example image for Edge browser is outdated

### ISSUE THREAD

**Issue by Francesco-Casablanca** [mdn/content#24047]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/week

### What information was incorrect, unhelpful, or incomplete?

I am surfing with microsoft edge browser and the paragraph about the edge control being more elaborate does not correspond to reality (see image)

### What did you expect to see?

I expected to see an input dialog similar to the one described below (see image).

looks like the edge browser is now aligned to other browsers

### Do you have any supporting links, references, or citations?

![image](https://user-images.githubusercontent.com/70393821/215989275-ff7b47e6-4dfc-4f5e-a2ec-88e10c39650b.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/week`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/week
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/week/index.md
* Last commit: https://github.com/mdn/content/commit/256f83064a7cc588df6d7c635e9db28e7572665a
* Document last modified: 2023-01-31T20:42:02.000Z

</details>

**Comment by yogitheboss** [comment]
hi everyone I want to work on this issue, 
do we need to remove the entire subsection for edge as it's working as other browsers or is there something I am missing?
I checked it on my local device as well. The week slider is same as chrome.

**Comment by HIRUT4528** [comment]
hello, everyone, I found  **interesting article**, regarding date pickers, here is the link:  [The woes of date input](http://html5doctor.com/the-woes-of-date-input/)
