### ISSUE TITLE
Boolean definition in HTML

### ISSUE THREAD

**Issue by estelle** [mdn/content#24085]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Boolean

### What information was incorrect, unhelpful, or incomplete?

Setting open, open="", open="false", or even open="😛" means open is set. That is the definition of boolean attributes in HTML. See https://codepen.io/estelle/pen/NWBEzoY and the second paragraph in https://developer.mozilla.org/en-US/docs/Glossary/Enumerated

We should amend the https://developer.mozilla.org/en-US/docs/Glossary/Boolean to add the HTML equivalent of what is on https://developer.mozilla.org/en-US/docs/Glossary/Enumerated

### What did you expect to see?

An explanation of what boolean means in HTML

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/boolean`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Boolean
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/boolean/index.md
* Last commit: https://github.com/mdn/content/commit/9d53a300e0baae28dcad8c60080fa0152dd2b023
* Document last modified: 2023-01-13T15:50:18.000Z

</details>

**Comment by HCY123902** [comment]
Hello, can I work on this
