### ISSUE TITLE
JS names for CSS properties

### ISSUE THREAD

**Issue by estelle** [mdn/content#24084]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

### What specific section or headline is this issue about?

Notes

### What information was incorrect, unhelpful, or incomplete?

The text includes this important statement:

> CSS property values may be accessed using the getPropertyValue(propName) API or by indexing directly into the object such as obj['z-index'] or obj.zIndex.

Which likely deserves it's own page.

### What did you expect to see?

A link to a document describing https://drafts.csswg.org/cssom/#css-property-to-idl-attribute or, possibly, 

```js 
let availableProps = getComputedStyle(document.body);
let list = [];
for(cssProp in availableProps) { 
  if(!/\-/.test(cssProp) && /^[a-z]/.test(cssProp)) {
    list.push(cssProp);
  }
}
console.log(list);
``` 
as a live example in the page

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/getcomputedstyle`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/getcomputedstyle/index.md
* Last commit: https://github.com/mdn/content/commit/76264bba2d8b68b00de3eca0ad1e64c4aa77af39
* Document last modified: 2023-01-12T04:22:58.000Z

</details>

**Comment by MaruthiKo** [comment]
So to solve this issue we need to create a new document with a brief about css-property-to-idl-attribute and an example that supports the breif

**Comment by Josh-Cena** [comment]
I'm not sure why we need a new document for this—we can document it on one API page and then link other pages that use the same behavior (like... `Element#style`? I don't know) to it. However the example would be cool.

**Comment by OnkarRuikar** [comment]
Why do we need `!/\-/.test(cssProp)`? No IDL name has `-` in it.
