### ISSUE TITLE
Issue with "WindowOrWorkerGlobalScope.fetch()": (short summary here please)

### ISSUE THREAD

**Issue by cakoose** [mdn/content#2409]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch

#### What information was incorrect, unhelpful, or incomplete?

The documentation for the "credentials" init parameter says that it affects whether credentials are set.

It also seems to control whether cookies in the response are accepted, at least in Chrome.  I personally observed this behavior and so did others: https://github.com/github/fetch/issues/386#issuecomment-243223273

#### Specific section or headline?

See above.

#### What did you expect to see?

MDN often has browser-specific notes.  This issue was pretty time-consuming to debug, so I think it would be worth calling it out in the MDN docs.

#### Did you test this? If so, how?

Using the network tab in Chrome.  See link to GitHub issue above.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/windoworworkerglobalscope/fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/windoworworkerglobalscope/fetch/index.html
* Last commit: https://github.com/mdn/content/commit/b39d9fe963b489691a0835cdb1bcc077168cd9c6
* Document last modified: 2021-02-11T16:28:01.000Z

</details>

**Comment by cakoose** [comment]
Thanks; I really like the new wording!

**Comment by sideshowbarker** [comment]
@cakoose Thank you very much for having taken time to report this. It really was in need of being changed.

Note that I also updated the corresponding section of the Fetch spec — 

* https://github.com/mdn/content/commit/24dade#diff-fdb3058c581d609c8df4123526d5b4185e211ffd2a1bc68fe6471d468c5bc81bR86
* https://fetch.spec.whatwg.org/#concept-request-credentials-mode

So by raising this issue — resulting in MDN and the spec updated — I think you’ve really helped save other developers a lot of time and frustration in the future.
