### ISSUE TITLE
`color-contrast()` no longer exists

### ISSUE THREAD

**Issue by svgeesus** [mdn/content#24109]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-contrast

### What specific section or headline is this issue about?

Outdated information

### What information was incorrect, unhelpful, or incomplete?

There is no `color-contrast()` anymore, it is renamed [`contrast-color()`](https://drafts.csswg.org/css-color-6/#colorcontrast) and there is no stable syntax yet.

### What did you expect to see?

Up to date information

### Do you have any supporting links, references, or citations?

https://drafts.csswg.org/css-color-6/#colorcontrast

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/color_value/color-contrast`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-contrast
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/color_value/color-contrast/index.md
* Last commit: https://github.com/mdn/content/commit/6be1b954a117202d7635caeec74ebbbde984d3f3
* Document last modified: 2022-09-26T22:47:43.000Z

</details>

**Comment by teoli2003** [comment]
Thank you. As nobody is implementing it yet, let's wait before updating it.

**Comment by svgeesus** [comment]
The issue is that people *are* implementing it (the old one) so the page is actively misleading.

**Comment by teoli2003** [comment]
Not sure what you mean by "implementing" it. Browser vendors are using the specs and not MDN to implement stuff.
Once one implements the feature with the new name, there will be a signal telling us that this landed.

**Comment by svgeesus** [comment]
Ah, I see what you mean. Fair enough!

**Comment by teoli2003** [comment]
Note that I'm keeping this open as it is valid; I only want to wait before updating the page, as the spec may change again – or not –, saving work if this is happening again.

**Comment by Josh-Cena** [comment]
Closing in favor of https://github.com/mdn/content/issues/36904
