### ISSUE TITLE
Documentation for WebDriver Commands is incomplete

### ISSUE THREAD

**Issue by palpalpalpal** [mdn/content#24145]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/WebDriver/Commands

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/WebDriver/Commands#browser_compatibility

### What information was incorrect, unhelpful, or incomplete?

All links in this table’s first column seem to be dead.

### What did you expect to see?

Working links.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/webdriver/commands`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/WebDriver/Commands
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/webdriver/commands/index.md
* Last commit: https://github.com/mdn/content/commit/a9005b03657fb1332dfa66515ff4f42f5a8bb56b
* Document last modified: 2022-09-05T02:59:05.000Z

</details>

**Comment by bsmth** [comment]
Hi @palpalpalpal - it looks like only the following list of commands have documentation pages at the moment: https://developer.mozilla.org/en-US/docs/Web/WebDriver#commands
