### ISSUE TITLE
Issue with "Client-side storage": mismatch in variable names?

### ISSUE THREAD

**Issue by BonyBloke** [mdn/content#2414]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

#### What information was incorrect, unhelpful, or incomplete?
In line 14 in note storage source code, the database is called `notes_db`. But the subsequent codes specify it as `notes_os`. This causes a DOMException error "`notes_os` is not a known object store name".
[https://github.com/mdn/learning-area/blob/master/javascript/apis/client-side-storage/indexeddb/notes/index.js](url)

#### Specific section or headline?
Working through a note storage example

#### Did you test this? If so, how?
I tried retyping all of the codes myself, to no avail. Then I tried to compare my code with the source code, with no major differences found except some minor ones (e.g arrow function and template literal). I even used the source code itself, but the problem still persisted. Finally I changed the code in line 14 to `let request = window.indexedDB.open('notes_os', 1);`, and the issue vanished.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/client-side_storage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/javascript/client-side_web_apis/client-side_storage/index.html
* Last commit: https://github.com/mdn/content/commit/ec2b6064788da26d520a8256d0e05a7875b50f78
* Document last modified: 2021-01-27T07:12:04.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update it 👍

**Comment by chrisdavidmills** [comment]
I'm not convinced that our code is wrong. `notes_db` specifies the notes database, whereas `notes_os` refers to the notes object store inside the database.

You can see our finished version here: 

* Live example: https://mdn.github.io/learning-area/javascript/apis/client-side-storage/indexeddb/notes/
* Source code: https://github.com/mdn/learning-area/blob/master/javascript/apis/client-side-storage/indexeddb/notes/index.js

This uses `notes_db` in line 14, and it works just fine. I wonder could there be something else going on here?

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/2414#issuecomment-780432196
