### ISSUE TITLE
Outdated labels table

### ISSUE THREAD

**Issue by dawei-wang** [mdn/content#24149]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/MDN_content

### What specific section or headline is this issue about?

 What we need help with

### What information was incorrect, unhelpful, or incomplete?

The table links lead to issue labels that are blank.

### What did you expect to see?

I expected to see an updated table and text introducing the table.

### Do you have any supporting links, references, or citations?

https://github.com/mdn/content/issues?q=is%3Aissue+is%3Aopen+label%3A%22time%3A+-30mins%22 
https://github.com/mdn/content/issues?q=is%3Aissue+is%3Aopen+label%3A%22time%3A+-3hr%22
https://github.com/mdn/content/issues?q=is%3Aissue+is%3Aopen+label%3A%22time%3A+-2days%22

### Do you have anything more you want to share?

FWIW , I like the time-based labeling scheme because it helped me manage my time. Small, medium, and large effort are harder to quantify. I would like to know the reasoning behind changing the labels.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community/mdn_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community/MDN_content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/mdn_content/index.md
* Last commit: https://github.com/mdn/content/commit/4c6b993ad0d43bc679688a3488e13a4ec0b2c3ec
* Document last modified: 2023-01-26T17:04:22.000Z

</details>

**Comment by Josh-Cena** [comment]
> I would like to know the reasoning behind changing the labels.

Here's some relevant conversation:

> Florian Scholz: I know GitHub labels are being work on, I'm just here to say that labels like "https://github.com/mdn/content/labels/time%3A%20-30mins" with the tooltip "Less than 30 mins. A quick task." are not encouraging 😄 30 minutes for whom?! More like 300 minutes for me to read into the details of this one, for example https://github.com/mdn/content/issues/4713
>
> Brian Smith: Totally agree, I think the original purpose of these was for contributors to gauge how much time they would need to fix something. We might move to something more generic like
>
> ```
> effort: small - Task is a small effort.
> effort: medium - Task is a medium effort.
> effort: large - Task is large effort.
> ```
>
> Florian Scholz: That looks much better. I mean sometimes changing one sentence can take 2 hours whereas creating a new page can be like 20 minutes if you know the subject well etc.

FWIW, these labels are kind of arbitrarily assigned anyway, and there isn't a fixed metric about what's a small vs. medium task. It could well turn out that a seemingly small task would need to involve tens of pages to be fixed properly.

**Comment by dawei-wang** [comment]
Thanks for the insight @Josh-Cena. I'll go ahead and change the links to reflect the small, medium, and large effort labels. It doesn't help our readers much if links lead to blank pages.
