### ISSUE TITLE
`a`, `b`, `c` and `d` in setTransform have an incorrect explanation

### ISSUE THREAD

**Issue by BlobTheKat** [mdn/content#24165]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setTransform

### What specific section or headline is this issue about?

#Parameters

### What information was incorrect, unhelpful, or incomplete?

> a (m11)
> Horizontal scaling. A value of 1 results in no scaling.

> b (m12)
> Vertical skewing.

> c (m21)
> Horizontal skewing.

> d (m22)
> Vertical scaling. A value of 1 results in no scaling.

This is misleading and is not how transformation matrices work

### What did you expect to see?

Described in terms of scaling and skewing, it makes no sense to define the purpose of `a`, `b`, `c` and `d` individually, as only together can they perform scaling and skewing.

As an example, the shape can still have a positive non-zero area even when both `a` and `d` are both 0.
The area could also be zero even when `a` and `d` are both 1, which of course would not make sense if scaling was solely represented by `a` and `d`.

In essence, the intuitiveness of scaling and skewing are not compatible.
It would make more sense to describe these as values in a transformation matrix, similar to how it is explained in getTransform, or even https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/matrix
Alternatively, they could be described in terms of scaling and rotating, such that
`a = cos(rot) * x_scale`
`b = sin(rot) * x_scale`
`c = -sin(rot) * y_scale`
`d = cos(rot) * y_scale`

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/matrix

https://en.wikipedia.org/wiki/Transformation_matrix#Examples_in_2_dimensions
(Although in the article a stretching matrix is represented by [k, 0, 0, 1], this is actually a simplification that assumes no rotation, and could explain the origin of this mistake)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/settransform`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setTransform
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/settransform/index.md
* Last commit: https://github.com/mdn/content/commit/90ffef849d3f869365c67f9bc457518afdec2bac
* Document last modified: 2023-01-07T11:51:52.000Z

</details>

**Comment by BlobTheKat** [comment]
any update/thoughts? This issue seems dead. Maybe I'm just impatient...

**Comment by Josh-Cena** [comment]
@BlobTheKat I agree with the issue. Some thoughts:

1. The descriptions are accurate if the other parameters are 1, which I think is the assumption here.
2. Issues labeled with https://github.com/mdn/content/labels/help%20wanted are welcoming contributors and probably not being worked on by maintainers when it's buried this deep.
