### ISSUE TITLE
Variables are not containers or storage boxes

### ISSUE THREAD

**Issue by lolaswift** [mdn/content#24186]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables

### What specific section or headline is this issue about?

Above "declaring a variable" there is the note

### What information was incorrect, unhelpful, or incomplete?

"Note: We say variables contain values. This is an important distinction to make. Variables aren't the values themselves; they are containers for values. You can think of them being like little cardboard boxes that you can store things in."

### What did you expect to see?

JavaScript variables are not containers or storage boxes. They are simply names or labels and they reference values which are stored in the heap memory. This is valid for both primitives and objects.

### Do you have any supporting links, references, or citations?

This is what I understand from the source code of chrome v8 engine. Unless Firefox JavaScript engine does it differently.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/variables`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/variables/index.md
* Last commit: https://github.com/mdn/content/commit/fc294fbbf432b5b210e0394e23b5c8950e81d734
* Document last modified: 2022-10-26T04:12:56.000Z

</details>

**Comment by Josh-Cena** [comment]
"Contain" is used in a metaphorical sense. You can say "a variable identifies a value", but we find it less intuitive. The key observation is that "a variable is a value" is wrong—not in an implementation sense, but in a conceptual sense.

**Comment by lolaswift** [comment]
Hi Josh, thank you very much for your quick response and for your explanation. I understand what the article was trying to accomplish since it teaches the very basics of JavaScript. I like the approach but in my humble of opinion, the example or the metaphor was just wrong if under the hood variables were implemented using pointers and pointer tagging, for example.  It builts a wrong mental model for beginners and it will confuse them very much when they try to get deeper and learn how JavaScript really works. I might be wrong because I'm not familiar with the implementation in the spidermonkey engine. MDN is the authoritive source of info about JavaScript. Even for tutorials for beginners, better teach the right thing right from the beginning.  Thank you again.
