### ISSUE TITLE
The definition of globalThis under nodejs is not updated

### ISSUE THREAD

**Issue by dong-lufei** [mdn/content#24193]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

The current nodejs global already has global, globalThis，
Your documentation above is wrong and not clear enough （“In Node.js none of these work, and you must instead use global.”）

**Comment by Josh-Cena** [comment]
This entire paragraph is about "Historically, accessing the global object has required different syntax in different JavaScript environments." It provides context for why the API is necessary.
