### ISSUE TITLE
Styling links as buttons

### ISSUE THREAD

**Issue by FelixHohgraebe** [mdn/content#24264]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links

### What specific section or headline is this issue about?

Styling links as buttons

### What information was incorrect, unhelpful, or incomplete?

Helllo,

when I try to drag and drop a button in the example the button stays red(active) is this supposed to be this way? 

Thanks

### What did you expect to see?

not be active

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/styling_text/styling_links`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/styling_text/styling_links/index.md
* Last commit: https://github.com/mdn/content/commit/56ea541086af91e970f89550da86d8ba47b6e0cb
* Document last modified: 2022-11-15T02:27:08.000Z

</details>

**Comment by FelixHohgraebe** [comment]
I just tested with chrome browser. There it worked as expected.

**Comment by sanjarcode** [comment]
I don't see a problem here. Chrome and Browser behave exactly the same.

**Comment by FelixHohgraebe** [comment]
Okay I got it thank you for answering

**Comment by sanjarcode** [comment]
You're welcome. Can you close the issue now?
