### ISSUE TITLE
MediaDevices»getDisplayMedia(): Incorrect mention of default values

### ISSUE THREAD

**Issue by eladalon1983** [mdn/content#24267]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia

### What information was incorrect, unhelpful, or incomplete?

Some of the reported default values are incorrect. For example, `selfBrowserSurface` is documented as defaulting to `'include'`, but the spec authors explicitly avoided specifying a default, and even went so far as to mention that the UA may ignore the value provided. So each UA can actually have a different default value.

In practice, I have actually just finished a gradual rollout in Chrome that, among other things, changed the default value (for Chrome) from `'include'` to `'exclude'`. (Chrome Developers article pending.)

### What did you expect to see?

See above.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mediadevices/getdisplaymedia`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediadevices/getdisplaymedia/index.md
* Last commit: https://github.com/mdn/content/commit/83eccbfdb3d06b3c156dd12db48f1da2e738eaca
* Document last modified: 2022-12-19T19:02:47.000Z

</details>

**Comment by beaufortfrancois** [comment]
@chrisdavidmills Can you update our MDN doc accordingly?

**Comment by teoli2003** [comment]
Is the default the same on all Chromium browsers? Also, I wonder if we should add an entry for the default change in bcd.

**Comment by eladalon1983** [comment]
Non-Chromium browsers have not yet implemented these controls; at least, not last time I checked. With `selfBrowserSurface` specifically, this only applies with tab-capture, and only Chromium-based browsers support that atm.

**Comment by teoli2003** [comment]
Yes, my question was, do all Chromium-based browsers use the same default?

**Comment by eladalon1983** [comment]
> Yes, my question was, do all Chromium-based browsers use the same default?

Starting m112 at the latest, they will.

**Comment by chrisdavidmills** [comment]
@beaufortfrancois @eladalon1983 I've started working on this now.

@teoli2003 can you please assign this to me?
