### ISSUE TITLE
Make sure pages for features on WindowOrWorkerGlobalScope describe the correct means of accessing

### ISSUE THREAD

**Issue by jpmedley** [mdn/content#2427]
Best described with Philip's quote from #1940. This issue is about making soure the descriptions are clear. It takes no position on the suggestion to put the referenced items under `Global_Obects/`.

>For all of the methods on WindowOrWorkerGlobalScope, I believe invoking them directly as fetch() rather than self.fetch() is idiomatic. They are: atob(), btoa(), clearInterval(), clearTimeout(), createImageBitmap(), fetch(), queueMicrotask(), setInterval(), setTimeout().
>
>For attributes, while they can be accessed directly, I think for at least these it's more idiomatic to access them via the global object, because it makes it clear they're not local variables: self.crossOriginIsolated, self.isSecureContext, self.origin.
>
>Then there's caches and indexedDB, where I suspect there's more variation in style. I'd certainly write indexedDB.open(...), but the example uses window.indexedDB.open('toDoList').
>
>On the URL, another option would be /api/Global_Objects/fetch, more analogous to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt
>
>I think that looking at the members of Window and WorkerGlobalScope will reveal more tricky cases. I think especially a method like window.resizeTo(), which it can be invoked as just resizeTo(), would not be great to give the same treatment as fetch().

Here's the start of a list. I do not claim it is complete.

- [ ] atob()
- [ ] btoa()
- [ ] clearInterval()
- [ ] clearTimeout()
- [ ] createImageBitmap()
- [ ] fetch()
- [ ] queueMicrotask()
- [ ] setInterval()
- [ ] setTimeout()
- [ ] crossOriginIsolated
- [ ] isSecureContext
- [ ] origin
- [ ] resizeTo

**Comment by himanshugarg** [comment]
Verified these are invoked consistently directly:-

- [ ]  atob() - https://developer.mozilla.org/en-US/docs/Web/API/atob
- [ ] btoa() - https://developer.mozilla.org/en-US/docs/Web/API/btoa
- [ ] clearInterval() - https://developer.mozilla.org/en-US/docs/Web/API/clearInterval
- [ ] clearTimeout() - https://developer.mozilla.org/en-US/docs/Web/API/clearTimeout
- [ ] createImageBitmap() - https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap
- [ ] fetch() - https://developer.mozilla.org/en-US/docs/Web/API/Fetch
- [ ] queueMicrotask() - https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask
- [ ] setInterval() - https://developer.mozilla.org/en-US/docs/Web/API/setInterval
- [ ] setTimeout() - https://developer.mozilla.org/en-US/docs/Web/API/setTimeout

And these attributes somewhat inconsistently used like this :-
- [ ] self.crossOriginIsolated - https://developer.mozilla.org/en-US/docs/Web/API/crossOriginIsolated **but see the example**
- [ ] self.isSecureContext - https://developer.mozilla.org/en-US/docs/Web/API/isSecureContext
- [ ] self.origin - https://developer.mozilla.org/en-US/docs/Web/API/origin
- [ ] window.resizeTo - https://developer.mozilla.org/en-US/docs/Web/API/Window/resizeTo

What changes are required for this issue now?

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/2427#issuecomment-917018354
