### ISSUE TITLE
Preferences for the GeometryUtils experimental features seem switched. 

### ISSUE THREAD

**Issue by TheNewsYorkTime** [mdn/content#24278]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features

### What specific section or headline is this issue about?

GeometryUtils methods: convertPointFromNode(), convertRectFromNode(), and convertQuadFromNode(); GeometryUtils method: getBoxQuads()

### What information was incorrect, unhelpful, or incomplete?

The listed preference controlling the convertQuadFromNode() method, and others is listed as "layout.css.getBoxQuads.enabled". The preference controlling the getBoxQuads() method is " 	layout.css.convertFromNode.enable" 

### What did you expect to see?

The preferences switched as to how they appear currently. 

### Do you have any supporting links, references, or citations?

Other than the page itself, no. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/firefox/experimental_features`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/experimental_features/index.md
* Last commit: https://github.com/mdn/content/commit/20a8f191d22e2a058303a7845d087911a042fd9e
* Document last modified: 2023-02-06T10:59:08.000Z

</details>

**Comment by Shivam-Amin** [comment]
I read the issue documentation & would love to contribute to it.  👍 
**Please assign it to me.**
