### ISSUE TITLE
Issue with "List of default Accept values": wrong Accept header info for Firefox 66+

### ISSUE THREAD

**Issue by sophiebits** [mdn/content#2430]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values

#### What information was incorrect, unhelpful, or incomplete?

The "Default values" section says that Firefox uses `*/*` starting with Firefox 66, but I just tested in Firefox 79 and in the network devtools I see the header used:

`Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`

Needs to be reviewed for accuracy against the Firefox source code and change history.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/content_negotiation/list_of_default_accept_values`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/content_negotiation/list_of_default_accept_values/index.html
* Last commit: https://github.com/mdn/content/commit/1c9812a9e1d357d10490c0455d989c02975981cc
* Document last modified: 2021-02-01T06:36:10.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can work on it. 👍

**Comment by chrisdavidmills** [comment]
Thanks for offering to help with this, @CreaTorAlexander. Feel free ask if you need any help.

**Comment by CreaTorAlexander** [comment]
I will check it later on my own in Firefox but before

> Needs to be reviewed for accuracy against the Firefox source code and change history.

wouldn't it be easier to ask someone of the Firefox team about this?

**Comment by sophiebits** [comment]
I guess I don't care (I'm not the one you'd be asking), but my default is to try to avoid taking up people's time with questions that I can find the answer to myself! Plus, the source code is more authoritative for what actually happened (although it may have less context about _why_).

**Comment by chrisdavidmills** [comment]
> I guess I don't care (I'm not the one you'd be asking), but my default is to try to avoid taking up people's time with questions that I can find the answer to myself! Plus, the source code is more authoritative for what actually happened (although it may have less context about _why_).

Yup, I'd agree with this entirely.

Plus it is often challenging to figure out who to ask ;-)

**Comment by hamishwillee** [comment]
I have fixed this in #2465

Reason being that the default updated in FF86 and while I had updated the image accept value, missed this one. I am pretty sure */* was just an error (that I made).

**Comment by sophiebits** [comment]
Wow thanks!

**Comment by chrisdavidmills** [comment]
> Wow thanks!

You are most welcome; thanks a lot for reporting it in the first place.

**Comment by hamishwillee** [comment]
Yes, thanks. PS I had to do a further update on this today in https://github.com/mdn/content/pull/2590 - that cleans up a missing bit of the picture between FF66 and FF72
