### ISSUE TITLE
 MDN Web Docs, at the start of the sentence, should be hyperlinked to redirect to https://developer.mozilla.org/

### ISSUE THREAD

**Issue by itundefined** [mdn/content#24315]
### MDN URL

https://github.com/mdn/content and https://github.com/mdn

### What specific section or headline is this issue about?

in the first line of first word 

### What information was incorrect, unhelpful, or incomplete?

 MDN Web Docs, at the start of the sentence, should be hyperlinked to redirect to https://developer.mozilla.org/

there are two readme files on the URLs -

1.) https://github.com/mdn/content
2.) https://github.com/mdn 

In these readme files, there is no hyperlinks in the sentence  MDN Web Docs that should redirect to the official site.

### What did you expect to see?

a hyperlink instead of finding a hyperlink in the sidebar it is easy to just press on it and go to the site.a

### Do you have any supporting links, references, or citations?

yeah, so many other repositories are using the hyperlink on the readme file. 

### Do you have anything more you want to share?

https://github.com/josdejong/mathjs

**Comment by Preshh0** [comment]
@itundefined, are you working on this?

**Comment by itundefined** [comment]
It's been resolved, i already added url @Preshh0

**Comment by Preshh0** [comment]
Okay!
