### ISSUE TITLE
Problem with section relative to multiple checkboxes having same name

### ISSUE THREAD

**Issue by fpierrat** [mdn/content#24312]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/HTML/Element/input/checkbox

### What specific section or headline is this issue about?

Gérer plusieurs cases à cocher

### What information was incorrect, unhelpful, or incomplete?

There might be a type in this section.
Trying to get something similar to this example working, with PHP server-side:
```
<fieldset>
  <legend>Veuillez sélectionner vos intérêts :</legend>
  <div>
    <input type="checkbox" id="coding" name="interest" value="coding">
    <label for="coding">Développement</label>
  </div>
  <div>
    <input type="checkbox" id="music" name="interest" value="music">
    <label for="music">Musique</label>
  </div>
</fieldset>

```
I couldn't get all values server-side that way.
I had to modify as follows:
`name="interest[]"`  instead of  `name="interest"`

### What did you expect to see?

I expexted to get a array of values of checked boxes server-side.
Instead of that, I only got one value.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/html/element/input/checkbox`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTML/Element/input/checkbox
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/html/element/input/checkbox/index.md
* Last commit: https://github.com/mdn/translated-content/commit/d9e0352b7e53ba0e5ea4e4422e80776b35509f1b
* Document last modified: 2022-11-03T04:28:29.000Z

</details>

**Comment by estelle** [comment]
when you use the same name for multiple checkboxes, the response when the form is submitted is a string of name/value pairs separated, like all the forms controls submitted, with an ampersand. It needs to be parsed server side as an associative array to capture all the values. On the french page, this is addressed in the example with the following explanation:

> Si les deux cases sont cochées lorsque le formulaire est envoyé, la chaîne des paires nom/valeur qui sera envoyée au serveur sera : interest=coding&interest=music.

This is an issue with your server code, not with HTML, which has pretty much always done it this way, as explained in the MDN doc.
