### ISSUE TITLE
Window.localStorage documentation should include an example of using JSON.stringify and JSON.parse to store and retrieve (serialize and deserialize) objects

### ISSUE THREAD

**Issue by alvyynm** [mdn/content#24356]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

### What specific section or headline is this issue about?

The article is incomplete

### What information was incorrect, unhelpful, or incomplete?

There's no mention of the ability to store objects or arrays in localStorage.

### What did you expect to see?

How to store arrays or objects in localStorage by first converting them to strings using `JSON.stringify()`.
How to retrieve arrays or objects from localStorage by using the `localStorage.getItem('key')` method and passing the data using `JSON.parse()` to convert it back to JS arrays or objects

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/localstorage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/localstorage/index.md
* Last commit: https://github.com/mdn/content/commit/7060fc880765875bbee8d5cd8f54e9170eb2691d
* Document last modified: 2023-01-03T09:36:43.000Z

</details>

**Comment by sanjarcode** [comment]
`localStorage` is meant for storing strings only, you cannot _directly_ store any other data type. The `JSON.stringify` and `JSON.parse` technique is a useful thing.

You can add a side node mentioning this.

**Comment by alvyynm** [comment]
Ooh. After reading the documentation `JSON.stringify` and `JSON.parse` on mdn, I get it now. Regardless, an example will do because someone may be interested in that in the future.
