### ISSUE TITLE
Issue with "WebGLRenderingContext.bindFramebuffer()": No description of behavior when framebuffer is null

### ISSUE THREAD

**Issue by 20kdc** [mdn/content#2435]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bindFramebuffer

#### What information was incorrect, unhelpful, or incomplete?

Does not describe that `framebuffer` is optional, and that passing null returns the target to being the canvas.

#### Specific section or headline?

Parameters, primarily (though an example may be of use)

#### What did you expect to see?

Wording along the lines of "If `framebuffer` is `null`, then the canvas (which has no `WebGLFramebuffer` object) is bound."

#### Did you test this? If so, how?

I have not particularly tested this right now.
However, confirmation of this can be found in the WebGL specification - where the canvas is described as "default framebuffer provided by the context" - as linked by the page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webglrenderingcontext/bindframebuffer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bindFramebuffer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webglrenderingcontext/bindframebuffer/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can work on it :+1:

**Comment by Ryuno-Ki** [comment]
@CreaTorAlexander Do it!
