### ISSUE TITLE
Issue with "HTMLScriptElement.referrerPolicy": (short summary here please)

### ISSUE THREAD

**Issue by YuJianrong** [mdn/content#2436]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement/referrerPolicy

#### What information was incorrect, unhelpful, or incomplete?
The code in the `Examples` section is incorrect

#### Specific section or headline?
`Examples`

```Javascript
var scriptElem = document.createElement("script");
scriptElem.src = "/";
scriptElem.referrerPolicy = "unsafe-url";
document.body.appendChild(script);
```

#### What did you expect to see?
```Javascript
var scriptElem = document.createElement("script");
scriptElem.src = "/";
scriptElem.referrerPolicy = "unsafe-url";
document.body.appendChild(scriptElem);
```

Diff:
`document.body.appendChild(script);` change to `document.body.appendChild(scriptElem);`

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlscriptelement/referrerpolicy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement/referrerPolicy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlscriptelement/referrerpolicy/index.html
* Last commit: https://github.com/mdn/content/commit/9917bf17a97973166bb3cb3812a496e4117a778f
* Document last modified: 2021-01-11T13:30:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Fixed in #2437
