### ISSUE TITLE
Replacing references to DOM (Core) Level 1 with those to DOM Living Standard

### ISSUE THREAD

**Issue by yarusome** [mdn/content#24364]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/Using_the_W3C_DOM_Level_1_Core

### What information was incorrect, unhelpful, or incomplete?

This page refers to [Document Object Model (Core) Level 1](https://www.w3.org/TR/REC-DOM-Level-1/level-one-core.html) at various places to illustrate the use of the DOM API, but that spec is way outdated and has been effectively replaced by [DOM Living Stardard](https://dom.spec.whatwg.org/), therefore referring to the old spec now seems misleading for beginners.

### What did you expect to see?

All the references to Document Object Model (Core) Level 1 be replaced by those to DOM Living Stardard, possibly with updates that better reflect the use of the current spec.

### Do you have any supporting links, references, or citations?

Document Object Model (Core) Level 1: https://www.w3.org/TR/REC-DOM-Level-1/level-one-core.html
DOM Living Stardard: https://dom.spec.whatwg.org/

**Comment by teoli2003** [comment]
Thank you, I opened a PR to get it fixed.

I took a different approach: I revamped (minimally) the article to make it independent of the spec and removed the links to the spec altogether (that is what we are doing everywhere. Ideally, we don't have links to the spec as everything should be described in the article – the terminology and audience of the specs are pretty different from MDN; specs describe the ideal world, while MDN aims to describe the actual implementations.
