### ISSUE TITLE
Problem with 500 interval server error

### ISSUE THREAD

**Issue by netvisionbgd** [mdn/content#24363]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

### What specific section or headline is this issue about?

I dont know why I have this error

### What information was incorrect, unhelpful, or incomplete?

Hi guy, 

my site https://dentalcigota.com/ generate 500 internal server error. When I click on site open normaly, site dont have noindex tag what is problem?

### What did you expect to see?

<img width="1280" alt="Screenshot 2023-02-12 at 08 51 27" src="https://user-images.githubusercontent.com/67223766/218299787-49464346-7472-4a02-9778-39e1d2d12047.png">

### Do you have any supporting links, references, or citations?

https://dentalcigota.com/ Also google search console dont crawl this page. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/500`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/500/index.md
* Last commit: https://github.com/mdn/content/commit/e5c97c58a289fb4d3b200174bdcf597bf3c14df4
* Document last modified: 2023-02-06T11:00:50.000Z

</details>

**Comment by teoli2003** [comment]
The error means there is an error on the server. There is little the browser or the client can try (except control its request if it is locally crafted).

The error is likely on the server side. I suggest asking your question on a specialized website like StackOverflow, as we don't have the bandwidth to answer support requests.

I'm closing this issue. If I've misunderstood you and you were reporting a problem in the documentation, feel free to reopen it while providing more information so we can understand the problem.

Thanks for your interest.
