### ISSUE TITLE
Web/HTTP/Headers/DNT: has ambigious deprecation notice

### ISSUE THREAD

**Issue by ckiee** [mdn/content#24368]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT

### What specific section or headline is this issue about?

The deprecation notice and metadata tags

### What information was incorrect, unhelpful, or incomplete?

The browser compatibility section lists only Safari as unsupported, and [this press](https://www.computerworld.com/article/3338086/why-apple-is-disabling-safari-s-do-not-track-feature) makes it seem like a marketing decision to me, and [the W3C spec also looks healthy](https://w3c.github.io/dnt/drafts/tracking-dnt.html#reg.DNT)? I don't understand how [GPC](https://en.wikipedia.org/wiki/Do_Not_Track#Global_Privacy_Control) is replacing DNT when it's [still a proposal](https://privacycg.github.io/gpc-spec/#sotd).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/dnt`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/dnt/index.md
* Last commit: https://github.com/mdn/content/commit/36001a269f4d7b2b3ac6de79e942a5f849bb87d8
* Document last modified: 2022-09-09T05:53:39.000Z

</details>

**Comment by hamishwillee** [comment]
This content updated follows this BCD update: https://github.com/mdn/browser-compat-data/commit/ece749a857818136f954593c0368db26f10cf949

As it says in this spec:

> Since its last publication as a Candidate Recommendation, there has not been sufficient deployment of these extensions (as defined) to justify further advancement, nor have there been indications of planned support among user agents, third parties, and the ecosystem at large. The working group has therefore decided to conclude its work and republish the final product as this Note, with any future addendums to be published separately.

So I'm guessing this note does not really count as a "spec".

**Comment by Josh-Cena** [comment]
That's right. We'll track further docs work in https://github.com/mdn/content/issues/12912. You can see that issue and the other linked issues.
