### ISSUE TITLE
[Web API] Support RTCInboundRtpStreamStats.trackIdentifier

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#24397]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1804676

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
Status

- BCD - https://github.com/mdn/browser-compat-data/pull/18910 (big job, have to create the whole dict
- Docs
- Release note
- dev-doc-complete

**Comment by hamishwillee** [comment]
@Rumyra FYI, invested lots of time on the BCD on this one, which has slowed me down a lot. Waiting on Vinyl for advice on how to progress that https://github.com/mdn/browser-compat-data/pull/18910#issuecomment-1447363100 - I think we'll have to be pragmatic and allow "supported in greater than" markup.

**Comment by Rumyra** [comment]
Let's create a separate project @hamishwillee - do you want to outline it here https://github.com/mdn/mdn/issues/new?assignees=&labels=proposal%2Cneeds+triage&template=content-or-feature-suggestion.yml&title=Enter+your+proposal+here and we'll run it aside from the ff project?

**Comment by hamishwillee** [comment]
@Rumyra Done - project is here: https://github.com/mdn/mdn/issues/384

I've updated this issue, which is now "done".
