### ISSUE TITLE
[Behind pref] [HTTP] Early hints

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#24392]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103

BCD needs an update

## Related Gecko bugs

Strangely we have two bugs for this, one nightly one beta 🤷‍♀️ - I think we put in release notes and dev-doc-complete both

https://bugzilla.mozilla.org/show_bug.cgi?id=1810543
https://bugzilla.mozilla.org/show_bug.cgi?id=1813035

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
This is support for HTTP status response [103](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103) in early beta/dev, etc - essentially everything except release (nightly is a "lesser" update, that was superseded). Action is to add experimental feature, update BCD and make sure the HTTP page is up to date.

Status:

- [ ] experimental features
- [ ] Docs
- [ ] BCD
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
Awesome - thanks @hamishwillee
