### ISSUE TITLE
[SVG] context-fill and context-stroke

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#24399]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

The original bug says these attributes don't work in marker content and has been fixed, however we do not have docs on either of these attributes

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=752638

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

__Related issues and pull requests:__
- [x] content & relnote https://github.com/mdn/content/pull/24837
- [x] BCD https://github.com/mdn/browser-compat-data/pull/19022

**Comment by bsmth** [comment]
See codepen to repro `stroke="context-stroke" fill="context-fill"`:

https://codepen.io/bsmth/pen/vYzKyGe

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">

  <style>
    path {
      marker: url(#circle);
    }
  </style>

  <path d="M 10,10 30,10 h 10" stroke="black" />
  <path d="M 10,20 30,20 h 10" stroke="blue" fill="red" />
  <path d="M 10,30 30,30 h 10" stroke="red" fill="none" />

  <marker id="circle" markerWidth="6" markerHeight="6" refX="3" refY="3" markerUnits="strokeWidth">
    <circle cx="3" cy="3" r="2" stroke="context-stroke" fill="context-fill" />
  </marker>

</svg>
```

**Comment by bsmth** [comment]
Setting this to `done` now, (bonus) BCD still has to land, but there's nothing else left here I can see outstanding.

**Comment by bsmth** [comment]
Closing this as completed now with related PRs merged.
