### ISSUE TITLE
[CSS] Implement page-orientation in @page rules for pages

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#24390]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

https://w3c.github.io/csswg-drafts/css-page/#page-orientation-prop

Needs addition to @page mdn page

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1673987

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by dletorey** [comment]
- [Content PR](https://github.com/mdn/content/pull/25176)
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/19075)
- [Data PR](https://github.com/mdn/data/pull/648)

**Comment by dletorey** [comment]
Just awaiting confirmation on whether this has been released in FF111 nightly or not before completing the Experimental release notes

**Comment by Rumyra** [comment]
Do we have an update @dletorey ?

**Comment by dletorey** [comment]
There is now, it turns out I may have discovered another bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1824852

**Comment by dletorey** [comment]
Updated the Label as the new [associated bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1824852) has pushed this to Firefox 113

**Comment by dletorey** [comment]
Added the Experimental release note and mentioned some inconsistencies on the Bug
