### ISSUE TITLE
[Behind Pref] [Web API] Implement worker modules

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#24402]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

We have a few things dotted about about this, so not sure if there's much else to document. Rel note & bcd as per

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1247687
https://bugzilla.mozilla.org/show_bug.cgi?id=1812628 - Behind pref

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
Status:

- [ ] Release notes
- [ ] BCD 
  - [ ] https://github.com/mdn/browser-compat-data/pull/19044
  - [ ] https://github.com/mdn/browser-compat-data/pull/19045 - tidy up
- [ ] Docs
- [ ] dev-doc-complete

**Comment by hamishwillee** [comment]
Closing. Core work done. I'll keep an eye on the clean up item, but not hopeful I'll get a clear answer from anyone.

**Comment by okikio** [comment]
Does Firefox support module workers now? I thought it would be announced in the Firefox 111 announcement but it wasn't

**Comment by WolfgangDrescher** [comment]
Yes it does, but you have to enable it manually via `about:config` and set `dom.workers.modules.enabled` to `true`.

https://caniuse.com/mdn-api_worker_worker_ecmascript_modules

I wonder when it will be enabled by default.

**Comment by okikio** [comment]
Thanks 👍🏽

**Comment by hamishwillee** [comment]
> I wonder when it will be enabled by default.

Probably not long. Support for dynamic import of modules into workers was just added (behind pref - I htink in 113). I _think_ the goal was to release this when support for both was available, so probably after a release (or two) of hardening.

**Comment by okikio** [comment]
Awesome 👌

**Comment by adamziel** [comment]
This only covers web workers, not service workers, right? [WordPress Playground](https://github.com/WordPress/wordpress-playground/issues/1196#issuecomment-2050000266) builds its service worker to an ES Module in local development mode, and that doesn't work on Firefox. The production build produces a regular JavaScript file and works without issues.

**Comment by hamishwillee** [comment]
@adamziel At the time I wrote this static import of modules in service workers was planned (and I think came in full support for the spec came in  FF114). 

The spec authors weren't sure what to do with dynamic import, as per https://github.com/w3c/ServiceWorker/issues/1585. This might have changed - I'm not tracking it.

**Comment by adamziel** [comment]
@hamishwillee oh, I meant service workers with `type: 'module'`, not dynamic imports specifically:

```js
	await navigator.serviceWorker.register(scriptUrl, {
		type: 'module',
	});
```

**Comment by hamishwillee** [comment]
You mean "does firefox support service workers of type "module"? Probably not. 

I base this on https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register#module  which says 

> ['module'](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register#module)
The loaded service worker is in an [ES module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) and the import statement is available on worker contexts. For ES module compatibility info, see the [browser compatibility data table for the ServiceWorker interface](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker#browser_compatibility).

If you look at [browser compatibility data table for the ServiceWorker interface](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker#browser_compatibility). it says FF service workers do not have "Support for ECMAScript modules"
