### ISSUE TITLE
Issue with "Positioning": (short summary here please)

### ISSUE THREAD

**Issue by sasan89** [mdn/content#2443]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning

#### What information was incorrect, unhelpful, or incomplete?
The example shown (iframe) for absolute positioning is wrong. It includes z-index and other stuff. The linked file below (at the note card) is pointing to the correct file, but the shown example in the section is wrong.

#### Specific section or headline?
Absolute Positioning

#### What did you expect to see?
The correct example :)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/css_layout/positioning`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/positioning/index.html
* Last commit: https://github.com/mdn/content/commit/293976c443ef65833556360ffa0ad563b6bf3373
* Document last modified: 2021-02-14T14:15:53.000Z

</details>

**Comment by chrisdavidmills** [comment]
Argh, that was a mess! Thanks for reporting ;-)

So this happened because the embedding macro call was embedding all code found beneath the "Absolute positioning" H2, including the code under the H3s.

I've fixed it by adding in a hidden H3 above the basic abs pos code, and referencing that in the macro call instead, so it only embeds the code from under that H3.

**Comment by chrisdavidmills** [comment]
See https://github.com/mdn/content/commit/1993848b2ab85e24cc09c876f770389fa4f048ba for the fix. This should be live in a day or so.

**Comment by sasan89** [comment]
Thanks for your rapid response. 🙏

**Comment by chrisdavidmills** [comment]
> Thanks for your rapid response. 🙏

You are most welcome.
