### ISSUE TITLE
Documentation for container queries give the impression that style container queries are supported

### ISSUE THREAD

**Issue by wkillerud** [mdn/content#24458]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@container

### What specific section or headline is this issue about?

Style container queries

### What information was incorrect, unhelpful, or incomplete?

- The section explains style container queries with an example of a query on a standard property.
- The compatibility table lists `@container` as fully supported in major browsers.
- Style container queries are _not_ supported. As of writing, Chrome has [intent to ship style container queries for custom properties](https://groups.google.com/a/chromium.org/g/blink-dev/c/ACL23q_nbK0/m/PaNJ81_qDAAJ?pli=1) only.

### What did you expect to see?

Some sort of indication that style container queries are not yet ready to use, either in the section itself or the compatibility table.

Maybe also an example with a custom property instead of a standard property, since that seems to be shipping first (or _at all_).

### Do you have any supporting links, references, or citations?

[Thread discussing Chrome intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/ACL23q_nbK0/m/PaNJ81_qDAAJ?pli=1), with links to standards GitHub repos for further details.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@container`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@container
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@container/index.md
* Last commit: https://github.com/mdn/content/commit/a1c9469832aaee308627d8387283b7da3f9cf49c
* Document last modified: 2023-02-02T17:42:40.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting @wkillerud - I can take a look at improving the page to reflect support status more clearly - I've assigned myself to the issue in the meantime.
