### ISSUE TITLE
`Response.text()` can throw a `TypeError`

### ISSUE THREAD

**Issue by jespertheend** [mdn/content#24466]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Response/text

### What specific section or headline is this issue about?

Return value

### What information was incorrect, unhelpful, or incomplete?

It says that it returns "A Promise that resolves with a String."
But in reality it's possible for this promise to reject with a TypeError.

### What did you expect to see?

Mentioning of the rejected promise similar to what's shown at https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions

### Do you have any supporting links, references, or citations?

https://fetch.spec.whatwg.org/#concept-body-consume-body mentions:
> If object is [unusable](https://fetch.spec.whatwg.org/#body-unusable), then return [a promise rejected with](https://webidl.spec.whatwg.org/#a-promise-rejected-with) a [TypeError](https://webidl.spec.whatwg.org/#exceptiondef-typeerror).

which is called by https://fetch.spec.whatwg.org/#dom-body-text

### Do you have anything more you want to share?

- [`Response.arrayBuffer()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/arrayBuffer)
- [`Response.blob()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/blob)
- [`Response.formData()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/formData)
- [`Response.json()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/json)
- [`Response.text()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/text)

all refer to [`consume body`](https://fetch.spec.whatwg.org/#concept-body-consume-body) in the spec, and would benefit from similar documentation.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/response/text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/response/text/index.md
* Last commit: https://github.com/mdn/content/commit/16e398809d62247dbadc89ff4024a0ffa4781f0e
* Document last modified: 2022-09-13T06:27:50.000Z

</details>

**Comment by BartoszKlonowski** [comment]
@sideshowbarker @Josh-Cena I will work on it!
