### ISSUE TITLE
Accept file types can be overridden

### ISSUE THREAD

**Issue by vtechmonkey** [mdn/content#24462]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept

### What specific section or headline is this issue about?

accept attribute

### What information was incorrect, unhelpful, or incomplete?

This document says that 

> Often you won't want the user to be able to pick any arbitrary type of file; instead, you often want them to select files of a specific type or types. For example, if your file input lets users upload a profile picture, you probably want them to select web-compatible image formats, such as [JPEG](https://developer.mozilla.org/en-US/docs/Glossary/JPEG) or [PNG](https://developer.mozilla.org/en-US/docs/Glossary/PNG).

> 
I'm not sure what happens on windows, but on mac although files type not listed under the 'accept' attribute are greyed out I can easily upload those files by clicking on 'show options' in the mac file upload dialog and selecting  'all files' from my mac, then all files are not greyed out and I can upload files that are NOT listed as accepted. 

### What did you expect to see?

I expected the article to point out that this attribute can be overwritten and is not to be used as a secure way to prevent certain files types from being uploaded. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/accept`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/accept/index.md
* Last commit: https://github.com/mdn/content/commit/4a2b6cafbf9bc5b006eedbdf0e9fdf2c8626d5b6
* Document last modified: 2023-01-18T07:45:13.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
The [Overview](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept#overview) section explicitly points out that this attribute does not prevent certain files types from being uploaded.

> The `accept` attribute doesn't validate the types of the selected files; it provides hints for browsers to guide users towards selecting the correct file types. It is still possible (in most cases) for users to toggle an option in the file chooser that makes it possible to override this and select any file they wish, and then choose incorrect file types.
> 
> Because of this, you should make sure that expected requirement is validated server-side.

Is there anything you think needs to be changed or added?

**Comment by Josh-Cena** [comment]
Closing per https://github.com/mdn/content/issues/24462#issuecomment-1447932403; the note already explicitly says "toggle an option in the file chooser".
