### ISSUE TITLE
Drop "in this module" from Learn

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#24467]
I proposed this in https://github.com/orgs/mdn/discussions/328: many people are +1 and noone is against. So let's do it.

This means removing the entire "In this module" section from the Learn docs (for example: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#in_this_module).

Since there are a few hundred pages, it would be good to do the work in a few PRs, maybe one for each section of Learn:

- [x] [Getting started with the web](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web)
- [x] [HTML — Structuring the web](https://developer.mozilla.org/en-US/docs/Learn/HTML)
- [x] [CSS — Styling the web](https://developer.mozilla.org/en-US/docs/Learn/CSS)
- [x] [JavaScript — Dynamic client-side scripting](https://developer.mozilla.org/en-US/docs/Learn/JavaScript)
- [x] [Web forms — Working with user data](https://developer.mozilla.org/en-US/docs/Learn/Forms)
- [x] [Accessibility — Make the web usable by everyone](https://developer.mozilla.org/en-US/docs/Learn/Accessibility)
- [x] [Performance — Making websites fast and responsive](https://developer.mozilla.org/en-US/docs/Learn/Performance)
- [x] [MathML — Writing mathematics with MathML](https://developer.mozilla.org/en-US/docs/Learn/MathML)
- [x] [Tools and testing](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing)
- [x] [Server-side website programming](https://developer.mozilla.org/en-US/docs/Learn/Server-side)

**Comment by dawei-wang** [comment]
It seems that the "in this module section" was not included in any MathML page when they were written.

**Comment by Graywolf9** [comment]
Thank you so much! If it is already in the sidebar I agree totally

**Comment by wbamberg** [comment]
Thanks for all your work on this @dawei-wang ! And thanks @drybalka for your CSS PR and originally motivating this change!
