### ISSUE TITLE
The problem of Task3

### ISSUE THREAD

**Issue by PiKaQiang** [mdn/content#24505]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Selectors_Tasks

### What specific section or headline is this issue about?

Task3

### What information was incorrect, unhelpful, or incomplete?

In the html source code of Task3, the the attr 'href' of element <a> have a problem, the protocol type http should be https, http will 
cause the [a:link] invalid. By my test, https can solve the problem. I don't know what happens, may be my question.

### What did you expect to see?

`<a href="https://example.com">bonus vobis</a>`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors/selectors_tasks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Selectors_Tasks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/selectors_tasks/index.md
* Last commit: https://github.com/mdn/content/commit/4f6ba2f5a1615fe155292cac416c7ab6b9d711ec
* Document last modified: 2022-09-11T17:33:19.000Z

</details>

**Comment by PankajBorde** [comment]
I want to work on this issues , assign to me
