### ISSUE TITLE
icecandidate_event update the meaning of null candidate

### ISSUE THREAD

**Issue by bardiharborow** [mdn/content#2450]
# Request type

- [ ] New documentation
- [x] Correction or update

# Details
See [icecandidate event](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/icecandidate_event).

The code sample in "Sharing a new candidate" checks if event.candidate is truthy before delivering it to the remote peer. "Indicating the end of a generation of candidates" says that events where `event.candidate == ""` should be delivered, but [the empty string is falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) in JavaScript and this signal would not be delivered. "Indicating that ICE gathering is complete" says that events where `event.complete == null` should not be delivered but then refers to the `event.candidate == true` test.

There is clearly a nuance here that I'm missing, but in any case this may need to be clarified. An uninformed reader would form the conclusion that actually a `event.complete != null` test is needed.

There's also mixed references to RTCPeerConnectionIceEvent (bluelinked) and RTCPeerIceCandidateEvent (redlinked), not sure if that's intentional.

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Check the meaning of null candidate and update examples accordingly
* Update any text to reflect changes

**Comment by sideshowbarker** [comment]
@dontcallmedom This seems like something that a contributor with WebRTC domain knowledge could make short work of. Do you think there’s any chance we could rope in somebody to take a look at it?

**Comment by fippo** [comment]
the recommendation to only signal non-null candidates is a pretty old one (2013?) which predates the icegatheringstatechange event. You should actually signal when you have gathered all candidates so the other side knows.

> "Indicating the end of a generation of candidates" says that events where event.candidate == "" should be delivered,

This part actually works as intended since that candidate has event.candidate set to {candidate: "", sdpMid: ...}
Tagging @docfaraday who knows most about that end-of-candidates candidate but I might take this one

**Comment by Rumyra** [comment]
@danjenkins would you happen to be able to help with the above issue?
