### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by JaydenWN** [mdn/content#24536]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay

### What specific section or headline is this issue about?

Date.prototype.getDay()

### What information was incorrect, unhelpful, or incomplete?

For the day of the month, see Date.prototype.getDate(). Should be linked to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth

### What did you expect to see?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/getday`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/getday/index.md
* Last commit: https://github.com/mdn/content/commit/c4e3558ee1045803df4a685f11f94dca273cd5fe
* Document last modified: 2022-12-13T19:20:00.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! "Day of the month" means "the 21st", "the 15th", etc, so `getDate` is correct. Should it be "get the month" without "the day of", `getMonth` would be correct.
