### ISSUE TITLE
console.log, weird inclusion of "JSON.parse()" in usage suggestion/example.

### ISSUE THREAD

**Issue by MvGulik** [mdn/content#24567]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/console/log

### What specific section or headline is this issue about?

Logging objects

### What information was incorrect, unhelpful, or incomplete?

Don't use console.log(obj), use console.log(**JSON.parse**(JSON.stringify(obj))). 

### What did you expect to see?

Don't use console.log(obj), use console.log(JSON.stringify(obj)). 

### Do you have any supporting links, references, or citations?

None that I can think of.

### Do you have anything more you want to share?

Suggesting using "**console.log(JSON.parse(JSON.stringify(obj)))**" makes not sense to me (_without additional related context on the parse() part that is, if there is any for this case_) as it will just output the same output string as "**console.log(obj)**".

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/console/log`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/console/log
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/console/log/index.md
* Last commit: https://github.com/mdn/content/commit/da88b2f3a23b9d93f083003f13c06f9d96073f6a
* Document last modified: 2022-09-13T05:21:27.000Z

</details>

**Comment by Josh-Cena** [comment]
`console.log` has different formatting for objects; it just looks nicer.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/55398995/219956051-f15956b2-7b70-4f00-a342-d281189a5ce6.png">

`JSON.parse(JSON.stringify(obj))` is a very common technique to clone an object. It stands as an idiom on its own. I don't think you have to individually justify the use of `JSON.parse`.
