### ISSUE TITLE
not obvious that `content` works with `::marker`

### ISSUE THREAD

**Issue by estelle** [mdn/content#24600]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/content

### What specific section or headline is this issue about?

examples

### What information was incorrect, unhelpful, or incomplete?

Most people don't know that content can be used on `::marker` in addition to `::before` and `::after`. I added it to the see also section, but it would be good to include an example showing `::marker` to make developers aware of this capability..

### What did you expect to see?

an example using `::marker`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/content/index.md
* Last commit: https://github.com/mdn/content/commit/4e002d26cb032c915aeee366f922f23cbacd8bf1
* Document last modified: 2023-02-11T03:07:14.000Z

</details>

**Comment by OnkarRuikar** [comment]
Now such example does exist on the page: https://developer.mozilla.org/en-US/docs/Web/CSS/content#adding_text_to_list_item_counters
