### ISSUE TITLE
Issue with "CSSUnparsedValue.forEach()": syntax clarifications

### ISSUE THREAD

**Issue by J4ku8** [mdn/content#2462]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSSUnparsedValue/forEach

#### What information was incorrect, unhelpful, or incomplete?
Are you sure about this syntax? 
"
CSSUnparsedValue.forEach(function callback(currentValue[, index[, array]]) {
    // your iterator
}[, thisArg]);
"

#### Specific section or headline?
CSSUnparsedValue.forEach(function callback(currentValue[, index[, array]]) {
    // your iterator
}[, thisArg]);

#### What did you expect to see?
Something else then this

#### Did you test this? If so, how?
I tried, bud in the end, I ended up with classic JS forEach.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/cssunparsedvalue/foreach`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSSUnparsedValue/forEach
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/cssunparsedvalue/foreach/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Just in case you got confused: `[, index]`, `[, array]` and `[, thisArg]` demark optional arguments to the function.

In #2202 we're discussing on phrasing them differently going forward.

**Comment by CreaTorAlexander** [comment]
> I tried, bud in the end, I ended up with classic JS forEach.

Could you share this classic forEach? I suppose you just got confused by the notation

```javascript
const arr = [5, 4, 3, 2, 1]
// ------------Callback function
// -----------------(..) => {}-------- 
arr.forEach((x,ind) => {console.log(x*ind)});
//----------^ ^^[,index]
// --------Current Val

```
Also you could apply the other optional arguments

**Comment by J4ku8** [comment]
Hi Alexander,
 Thank you for responding.

This is forEach I ended with, actually it is standart JS forEach seems to me.
And I’ do not know why it is mentioned as a part of CSSUnparsedValue.
let values = new CSSUnparsedValue(['30', '60'])
    console.log(values.keys())
    values.forEach(el => {
      console.log(el)
    })


Best regards,
JT

**Comment by CreaTorAlexander** [comment]
@J4ku8 ah okay I understand.
Yes, I agree I also don't understand why it is explicit say *CSSUnparsedValue.forEach()* with the *forEach()* explicit in it.

**Comment by CreaTorAlexander** [comment]
@Rumyra here we have the old BNF Syntax with [,optional1][, optional2] shouldn't it be updated to the new syntax with

```
forEach(element)
forEach(element, index)
forEach(element, index, array)
```

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander Yes, this would also be good.

**Comment by Rumyra** [comment]
> @Rumyra here we have the old BNF Syntax with [,optional1][, optional2] shouldn't it be updated to the new syntax with
> 
> ```
> forEach(element)
> forEach(element, index)
> forEach(element, index, array)
> ```

Thank you - yes I'll update the 'update syntax' bullet to be more explicit

**Comment by sideshowbarker** [comment]
The Syntax section of https://developer.mozilla.org/en-US/docs/Web/API/CSSUnparsedValue/forEach has subsequently been updated, so I’m going ahead and closing this.
