### ISSUE TITLE
Issue with "Django Tutorial Part 11: Deploying Django to produ…": (short summary here please)

### ISSUE THREAD

**Issue by j-driller** [mdn/content#2466]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment

#### What information was incorrect, unhelpful, or incomplete?
on https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment 

#### Specific section or headline?
"We can then push our app to the Heroku repository as shown below. This will upload the app, package it in a dyno, run collectstatic, and start the site.

git push heroku master"   <<<< ERROR! Deprecated...

#### What did you expect to see?
git push heroku main 

#### Did you test this? If so, how?
Yes, changed it to main and it worked...

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/server-side/django/deployment/index.html
* Last commit: https://github.com/mdn/content/commit/edbcbfa37c7807eefc5346c734cfc55d3dcc2c8a
* Document last modified: 2021-01-25T07:12:53.000Z

</details>

**Comment by j-driller** [comment]
Github deprecated master to main and you have corrected an earlier reference, but not this one.... hope it helps someone...

**Comment by hamishwillee** [comment]
Thanks. Hmmm, Heroku say they support both: https://devcenter.heroku.com/articles/git#deploying-code

I'll tidy.
