### ISSUE TITLE
the spec isn't the most recent

### ISSUE THREAD

**Issue by estelle** [mdn/content#24669]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/visibility

### What specific section or headline is this issue about?

specification

### What information was incorrect, unhelpful, or incomplete?

It's listed as CSS2 only, but it's also defined in display: https://w3c.github.io/csswg-drafts/css-display/#visibility

### What did you expect to see?

https://w3c.github.io/csswg-drafts/css-display/#visibility listed as the spec url

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/visibility`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/visibility
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/visibility/index.md
* Last commit: https://github.com/mdn/content/commit/413355c790c4102eea5937465ea610938327fe56
* Document last modified: 2022-09-27T03:53:49.000Z

</details>

**Comment by teoli2003** [comment]
Thank you. The PR has been merged in bcd; the MDN content will be updated after the next BCD package publication (usually on Mondays and Thursdays, but this can vary a bit)
