### ISSUE TITLE
Video not playing in the Active Learning section

### ISSUE THREAD

**Issue by BleedingJustice** [mdn/content#24697]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/How_does_the_Internet_work

### What specific section or headline is this issue about?

Active Learning

### What information was incorrect, unhelpful, or incomplete?

The 5 minute video would not load and kept trying to refresh
[https://www.youtube.com/watch?v=7_LPdttKXPc](url)

The 9 minute video would not load and kept trying to refresh
https://www.youtube.com/watch?v=x3c1ih2NJEg[](url)

### What did you expect to see?

The videos

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/common_questions/web_mechanics/how_does_the_internet_work`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/How_does_the_Internet_work
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/web_mechanics/how_does_the_internet_work/index.md
* Last commit: https://github.com/mdn/content/commit/0c9a70feab345069bca415c05bf6afcf43d6d03a
* Document last modified: 2023-02-08T22:16:17.000Z

</details>

**Comment by nreef12** [comment]
These videos are hosted on YouTube, meaning it's not a problem with MDN. Check your internet connection and try again

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/24697#issuecomment-1438776689
