### ISSUE TITLE
Request.integrity: new request doesn't contain integrity

### ISSUE THREAD

**Issue by goldingdamien** [mdn/content#24728]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Request/integrity

### What specific section or headline is this issue about?

Examples does not work

### What information was incorrect, unhelpful, or incomplete?

According to the example, the below is supposed to work:

```js
const myRequest = new Request('flowers.jpg');
const myIntegrity = myRequest.integrity;
```

However, I am unable to get an integrity by referencing a file by URL.
I don't understand how it would be theoretically possible because the integrity according to my understanding is based on the file content which would require an async function execution.

### What did you expect to see?

I expect to see an example that can be easily copied or slightly edited to make work, and any necessary hints where confusion may be likely.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/request/integrity`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Request/integrity
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/request/integrity/index.md
* Last commit: https://github.com/mdn/content/commit/2937558d5ed1e03d7f60b2de71dd9c17f490166e
* Document last modified: 2023-02-19T10:03:58.000Z

</details>

**Comment by Josh-Cena** [comment]
`myRequest.integrity` is exactly what you passed to construct the request, i.e. the expected hash, not the actual hash. You need this to get something non-empty:

```js
const myRequest = new Request("flowers.jpg", { integrity: "foo" });
const myIntegrity = myRequest.integrity;
```

The current example does seem a bit useless.

**Comment by goldingdamien** [comment]
That makes more sense. Thank you for the explanation.
I thought JavaScript may include a way to generate the integrity from the file contents and found the MDN link, but could not get it to work. I guess I will need to use one of the examples here: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by Josh-Cena** [comment]
Generating integrity is usually a server-side and user-agent thing, so JavaScript as a client-side scripting language would not care about this. If you are using JS on the server-side (a la Node), you may find some npm library to do this.
