### ISSUE TITLE
Issue in Array.prototype.filter() article

### ISSUE THREAD

**Issue by JaySPatel2962** [mdn/content#24741]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

### What specific section or headline is this issue about?

first line of the Array.prototype.filter() article

### What information was incorrect, unhelpful, or incomplete?
The filter() method creates a **shallow copy** of a portion of a given array.
this line is wrong in the article.

### What did you expect to see?

filter function **not return a shallow copy** of the original array.
It return **deep copy** or create a new reference of filtered array.
this same issue also in **Array.prototype.slice()** article, check this too.

### Do you have any supporting links, references, or citations?

I have an example of this. You can easily understand this.

ex.
  const words = ['spray', 'limit', 'elite', 'exuberant', 'destruction', 'present'];
  
  const result = words.filter(word => word.length > 6);
  
  result[0] = "Jay Patel";    // change the first element of the filtered array
  
  // **not change in original array**
  console.log("original array = ", words);
  // Expected output: Array ['spray', 'limit', 'elite', 'exuberant', 'destruction', 'present']

  console.log("filtered and changed array = ", result);
  // Expected output: Array [**"Jay Patel"**, "destruction", "present"]

**Comment by wang-zhong** [comment]
That's not the correct way to test shallow copy.

const words = [{id:1, text:'spray'}, {id:2, text:'limit'}, {id:3, text:'exuberant'}]
const result = words.filter(word => word.text.length > 6)
result[0].id = 4
console.log(words[2].id) // 4 so the doc is correct

**Comment by JaySPatel2962** [comment]
> That's not the correct way to test shallow copy.
> 
> const words = [{id:1, text:'spray'}, {id:2, text:'limit'}, {id:3, text:'exuberant'}] const result = words.filter(word => word.text.length > 6) // => result: [{id:3, text: 'exuberant'}] result[0].id = 4 // this changes words too console.log(words[2].id) // 4 so the doc is correct

for array of objects, this concept is true.
but what in case of array of primitive values?

**Comment by wang-zhong** [comment]
shallow/deep copy is meant for reference types, not primitives.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/24741#issuecomment-1439821975 and https://github.com/mdn/content/issues/24741#issuecomment-1439863695

**Comment by Josh-Cena** [comment]
See also https://github.com/mdn/content/issues/17889 and various other issues that come up by searching "shallow copy"

**Comment by JaySPatel2962** [comment]
const words = [{id:1, text:'spray'}, {id:2, text:'limit'}, {id:3, text:'exuberant'}]
const result = words.filter(word => word.text.length > 6) // => result: [{id:3, text: 'exuberant'}]
result[0].id = 4 // this changes words too
console.log(words[2].id) // 4 so the doc is correct

@wang-zhong 
I think you have to give this example in the mdn article so that others can understand easily.

**Comment by Josh-Cena** [comment]
You can find it in https://developer.mozilla.org/en-US/docs/Glossary/Shallow_copy.
