### ISSUE TITLE
<script type=module async> explanation incorrectly says it defers

### ISSUE THREAD

**Issue by dieulot** [mdn/content#24754]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

### What specific section or headline is this issue about?

async

### What information was incorrect, unhelpful, or incomplete?

> For [module scripts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules), if the async attribute is present then the scripts and all their dependencies will be executed in the defer queue, therefore they will get fetched in parallel to parsing and evaluated as soon as they are available.

### What did you expect to see?

What happens with async module scripts is, as far as I know and understand from the spec, what’s explained in the part of that sentence. Just like non-module scripts. But the part about “the defer queue” is confusing, as `async` has nothing to do with `defer`.

My guess is that the writer naively called what happened with the dependency chain a “defer queue” even though `defer` is something totally different in the context of loading scripts.

### Do you have any supporting links, references, or citations?

Spec (with a neat diagram): https://html.spec.whatwg.org/multipage/scripting.html#attr-script-async

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/script`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/script/index.md
* Last commit: https://github.com/mdn/content/commit/f2ad7c5bfe075511f5a5c2a040e54889a2158d3b
* Document last modified: 2023-02-20T14:39:34.000Z

</details>

**Comment by Anurella** [comment]
@sideshowbarker can this be assigned to me 

suggested modification:
1. it will be to remove the "defer queue" word, as there is a placement in a queue that allows the parallel fetching 
2. or to rephrase into this - "For [module scripts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules), if the async attribute is present then the scripts and all their dependencies will get fetched in parallel to parsing and evaluated as soon as they are available."


excerpt from [here](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-async)
