### ISSUE TITLE
broken image on A2HS page

### ISSUE THREAD

**Issue by davidbielik** [mdn/content#24766]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen

### What specific section or headline is this issue about?

A2HS on Desktop

### What information was incorrect, unhelpful, or incomplete?

[This image](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen/chrome-desktop-a2hs-banner.png) is broken.

```
<img src="/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen/chrome-desktop-a2hs-banner.png" alt="Install prompt prompts for installing or cancelling the awesome fox picture." loading="lazy">
```

<img width="820" alt="image" src="https://user-images.githubusercontent.com/7410770/220745181-d9d24c3f-5b1b-49e2-ab79-16f6d9cf35b6.png">

### What did you expect to see?

A working image

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/progressive_web_apps/add_to_home_screen`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/add_to_home_screen/index.md
* Last commit: https://github.com/mdn/content/commit/af2fad21d50b2fff447a4b1c7cbdc76f4deb3474
* Document last modified: 2022-12-14T09:27:00.000Z

</details>

**Comment by Josh-Cena** [comment]
This page has been removed as part of #25888
