### ISSUE TITLE
event doesnt fire on fully cached pages (no event appears to)

### ISSUE THREAD

**Issue by Montclair** [mdn/content#24770]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/pageshow_event

### What information was incorrect, unhelpful, or incomplete?

This gives the impression that on a fully cached page, the event will fire.  That is not true.

### What did you expect to see?

Due to browser caching and the content of the page, the event may not fire.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/pageshow_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/pageshow_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/pageshow_event/index.md
* Last commit: https://github.com/mdn/content/commit/bb8221e061bba27dbdbe5a3698b6c69febf0bc70
* Document last modified: 2023-02-19T07:19:47.000Z

</details>

**Comment by Josh-Cena** [comment]
@Montclair It has been a while but I'd like some clarification please. What steps did you take to observe this issue? Here's a local server I set up:

```js
Bun.serve({
  fetch(req) {
    return new Response(
      `<!doctype html>
<html>
  <body>
    <a href="/${Math.random()}">Random link</a>
    <script>
      window.addEventListener("pageshow", () => {
        alert("Page show");
      });
    </script>
  </body>
</html>`,
      {
        headers: {
          "Content-Type": "text/html",
        },
      },
    );
  },
});
```

And then whenever I click a link or go back, I always get an alert. `pageshow` also doesn't have anything to do with resource loading or caching—it's always fired when this page is navigated to (i.e. it appears on top of the history stack).

**Comment by Montclair** [comment]
This was so long ago, that I honestly don't remember, and worked around the issue.

**Comment by Josh-Cena** [comment]
In that case I'm close it for now because there's not enough information for it to be actionable, but if you found a case, just let me know with a comment.
