### ISSUE TITLE
syntax is missing

### ISSUE THREAD

**Issue by estelle** [mdn/content#24786]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/container-type

### What specific section or headline is this issue about?

missing formal definition and syntax

### What information was incorrect, unhelpful, or incomplete?

two sections of the doc are missing

### What did you expect to see?

formal definion and syntax

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/container-type`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/container-type
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/container-type/index.md
* Last commit: https://github.com/mdn/content/commit/489dbd4d8e2e099733d3bb04ad3f97678c54ac8e
* Document last modified: 2023-02-21T22:18:29.000Z

</details>

**Comment by advitiya7** [comment]
@estelle can you please explain the issue ?
