### ISSUE TITLE
tr heigh is works in Firefox but not in Chrmium, and this is not mentioned

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mdn/content#2479]
on this [page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr)

I tried [Pull Request](https://github.com/mdn/content/pull/2404#event-4351689994), but looks like some expert needed.

**Comment by teoli2003** [comment]
height is not an attribute of <tr> according to the spec.
It also doesn't appear on the webidl of HTMLTableRowElement in the [spec](https://html.spec.whatwg.org/multipage/tables.html#the-tr-element), in [Firefox](https://hg.mozilla.org/mozilla-central/file/tip/dom/webidl/HTMLTableRowElement.webidl), or in [Blink](https://chromium.googlesource.com/chromium/blink/+/816df4354aab5d56f983f51f252f5c8667f35092/Source/WebCore/html/HTMLTableRowElement.idl).

I would be surprised that it actually works in Firefox. (But I like surprises).

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/2479#issuecomment-856660364
