### ISSUE TITLE
Question mark in interactive example needs styling for keyboard focus

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#24806]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Practical_positioning_examples

### What specific section or headline is this issue about?

A sliding hidden panel

### What information was incorrect, unhelpful, or incomplete?

After going to the hidden info panel example page ( https://mdn.github.io/learning-area/css/css-layout/practical-positioning-examples/hidden-info-panel.html ), under the "A sliding hidden panel" heading in the Note section, there is no indication when I tab to the item that I'm there and the question mark can be clicked or use the space bar to activate it to see the additional content.

**NOTE** - You might also want to update the example/information on the page to explain how to make the question mark keyboard accessible. Or at least mention earlier than the end of the main page that it's not that accessible.

### What did you expect to see?

I expected to see some type focus when tabbing to the question mark. So a person  knows that they are there and can open item.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/css_layout/practical_positioning_examples`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Practical_positioning_examples
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/practical_positioning_examples/index.md
* Last commit: https://github.com/mdn/content/commit/1b6001b69cb763c78222ac0049af533b1e614271
* Document last modified: 2023-02-17T19:36:39.000Z

</details>

**Comment by Anurella** [comment]
@sideshowbarker should a text be added to the page that the user should click on the question mark, if yes you can assign this task to me and allow me access to the [repo](https://github.com/mdn/learning-area)

@jfc3-dol It seems the notice about the non-accessibility at the end of the practice is teacher indicating what is wrong with the approach taken hoping that the student would want to attempt their own version that is accessible and more practical.

**Comment by jfc3-dol** [comment]
@Anurella 
Thanks, for the explanation, and good luck getting it fixed.

**Comment by OnkarRuikar** [comment]
> I expected to see some type focus when tabbing to the question mark. So a person knows that they are there and can open item.

The prose does say: `In addition, the effect is not great in terms of accessibility; the label is not focusable by default, and the non-semantic use of the form elements could cause issues with screen readers.`\
More features could be added to the demo, but author has kept it simple and intention is not to make it full proof.

Focus indicator could be added to the label using something like following:
```css
body:has(input:focus) > label {
    border: 2px dashed blue;
}
```
But this would be beyond the scope.

> should a text be added to the page that the user should click on the question mark

The prose does say that, "The final example we'll present here is a panel that slides on and off the screen at the press of an icon".

**Comment by Anurella** [comment]
@OnkarRuikar, aside from the styling you posted, what would you suggest is the best fix, and how can I help?

**Comment by Josh-Cena** [comment]
From https://github.com/mdn/content/issues/30473: we need to fix the [Tabbed info box](https://mdn.github.io/learning-area/css/css-layout/practical-positioning-examples/info-box.html) example too.
