### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by alvinhui** [mdn/content#2480]
Content: https://github.com/mdn/content/blob/main/files/en-us/web/media/formats/index.html#L34
Link: /en-US/docs/Web/Media/Formats/Images_for_web_designers

And I will suggest move "Image file type and format guide" section belongs to "Media file types and codecs".

**Comment by hamishwillee** [comment]
That file does not exist but the  material is covered in the image file format guide - so I removed the section and merged the info in https://github.com/mdn/content/pull/2592

> And I will suggest move "Image file type and format guide" section belongs to "Media file types and codecs".

This is a perfectly reasonable suggestion, but I am still not going to do it. In my opinion images are still the most important topic covered here. So even though it is just "another media type", having it separate makes the most important doc for most readers very obvious. 
I would probably accept a PR if someone else felt strongly the other way. 

Thanks very much for posting this!

**Comment by alvinhui** [comment]
> That file does not exist but the material is covered in the image file format guide - so I removed the section and merged the info in #2592
> 
> > And I will suggest move "Image file type and format guide" section belongs to "Media file types and codecs".
> 
> This is a perfectly reasonable suggestion, but I am still not going to do it. In my opinion images are still the most important topic covered here. So even though it is just "another media type", having it separate makes the most important doc for most readers very obvious.
> I would probably accept a PR if someone else felt strongly the other way.
> 
> Thanks very much for posting this!

Image as the basis of multimedia, a single chapter is reasonable. I don't think it's too controversial.

**Comment by hamishwillee** [comment]
Then make your own PR :-)
