### ISSUE TITLE
Bottom class="prev-next" is missing

### ISSUE THREAD

**Issue by JaspaB** [mdn/content#24824]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Classes_in_JavaScript

### What specific section or headline is this issue about?

Bottom class="prev-next"

### What information was incorrect, unhelpful, or incomplete?

Missing buttons in the bottom

### What did you expect to see?

The buttons

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/classes_in_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Classes_in_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/classes_in_javascript/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by sidverma32** [comment]
@sideshowbarker  can i pick this issue?

**Comment by sidverma32** [comment]
@sideshowbarker  Raised PR. Also i would like to know how to become member of this amazing community [MDN] as i have already contributed multiple PRs in this repository.
