### ISSUE TITLE
Invalid `import().then()` example

### ISSUE THREAD

**Issue by szmarczak** [mdn/content#24838]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import

### What specific section or headline is this issue about?

Module namespace object

### What information was incorrect, unhelpful, or incomplete?

```js
// my-module.js
export function then() {
  console.log("then() called");
}
```

```js
// main.js
import * as mod from "/my-module.js";

import("/my-module.js").then((mod2) => {
  // Logs "then() called"
  console.log(mod === mod2); // false
});
```

### What did you expect to see?

`false` to be logged as well. I tested both on latest Firefox and Chrome and only `then() called` gets logged.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/import`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/import/index.md
* Last commit: https://github.com/mdn/content/commit/0f3738f6b1ed1aa69395ff181207186e1ad9f4d8
* Document last modified: 2023-02-21T00:33:34.000Z

</details>

**Comment by szmarczak** [comment]
It hangs because `then` should be an executor: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise#parameters

It never resolves so it never gets logged.

**Comment by Josh-Cena** [comment]
Yes, I think for us to showcase it properly, let's use your suggested example with `resolve()`
