### ISSUE TITLE
Clarification for hue-rotate

### ISSUE THREAD

**Issue by DenianArthurShades** [mdn/content#24839]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/hue-rotate

### What specific section or headline is this issue about?

hue-rotate()

### What information was incorrect, unhelpful, or incomplete?

The statement "The hue-rotate() CSS function rotates the hue of an element and its contents.".

hue-rotate is implemented as a rotation matrix (or equivalent function) applied to an RGB color "vector". This is true in every browser and on every operating system I have seen. You can see the difference in this screenshot of a comparison page I created.

![image](https://user-images.githubusercontent.com/9946964/221169525-ae522d07-b5d6-4684-b0b0-d2bf8a8f6a70.png)

As a result, this filter does not behave as I believe a professional with knowledge of colors would expect it to.

### What did you expect to see?

A reference to how the filter is impllemented.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/filter-function/hue-rotate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/hue-rotate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/filter-function/hue-rotate/index.md
* Last commit: https://github.com/mdn/content/commit/66944f622b6b51bc9c24bebbbea242138d910600
* Document last modified: 2023-02-21T05:45:53.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this one @DenianArthurShades - would you like to open a PR to improve the section?
