### ISSUE TITLE
Issue with "Intl.NumberFormat": Units + quotes inconsistency

### ISSUE THREAD

**Issue by pmpinto** [mdn/content#2483]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

#### What information was incorrect, unhelpful, or incomplete?
Both points under `#using_style_and_unit`:

Point 1:
The first example uses `pt-PT` for the locale and `mile-per-hour` for the `unit`. We don't really use mph in Portugal. It's just odd to see these 2 things together. We use kph.

Point 2:
The quotes inconsistency in this block is driving me nuts. You seem to be using single quotes on this page at least, so that's what I would suggest here as well.

Thanks ✌️ 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/index.html
* Last commit: https://github.com/mdn/content/commit/3a528f87018c714901a23421f78b9a6cb84182cd
* Document last modified: 2021-01-03T18:23:07.000Z

</details>

**Comment by chrisdavidmills** [comment]
Some good points here, thanks for reporting these problems @pmpinto !

I've fixed these issues in https://github.com/mdn/content/commit/c267fd1ace913dd72a3351eea8cad93a7cf9c99a
