### ISSUE TITLE
 Add a new option "ImageOrientation: none" to CreateImageBitmap 

### ISSUE THREAD

**Issue by yiyix** [mdn/content#24857]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap

### What specific section or headline is this issue about?

options

### What information was incorrect, unhelpful, or incomplete?

"options" is defined as follows: "Specifies whether the image should be presented as is or flipped vertically. Either none (default) or flipY."

### What did you expect to see?

Specifies whether the image should be presented as is, ignoring the orientation specified in its metadata or flipped vertically. Either from-image(default), none or flipY.

**Comment by mzur** [comment]
I find the new wording potentially hard to understand. What about this: "Specifies whether the image orientation should be determined based on the image metadata, the image encoding (ignoring the metadata) or based on the metadata and flipped vertically. One of `from-image` (default), `none` or `flipY`.

**Comment by teoli2003** [comment]
`none` isn't listed in the spec. Do browsers implement it?

**Comment by Josh-Cena** [comment]
For a bit more context: in https://github.com/mdn/content/issues/23564 / https://github.com/whatwg/html/pull/8710, `none` is renamed to `from-image`. Then, in this issue and https://github.com/whatwg/html/pull/8687 (not merged yet), `none` is added back with a different meaning, so overall they match CSS `image-orientation`.

**Comment by Josh-Cena** [comment]
@OnkarRuikar This issue is about a new option called `"none"` that's not merged into the spec yet.

**Comment by hamishwillee** [comment]
BCD stuff being fixed by https://github.com/mdn/browser-compat-data/pull/23480

**Comment by hamishwillee** [comment]
@Josh-Cena I've removed "needs BCD update". This was fixed in https://github.com/mdn/browser-compat-data/pull/23480

I say fixed, but I mean "fudged", in that the old meaning of `none` has been purged. The new meaning is the new planned implementation, which is only done by deno. It is marked as non-standard until the spec accepts the change to get `none`.
