### ISSUE TITLE
incomplete concept

### ISSUE THREAD

**Issue by elbrant** [mdn/content#24859]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong

### What specific section or headline is this issue about?

A logic error

### What information was incorrect, unhelpful, or incomplete?

The following sentence structure is incomplete. An editing error, I'm sure, but I don't know what the author was trying to say, so.... I don't feel like I would be able to edit it properly.

>[A logic error](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong#a_logic_error)
>
>  "... the "random" number you've got to guess is always 
> 1. Definitely not quite how we want the game to play out!"

### What did you expect to see?

No expectations, just a 'heads up'. I would fix it if I knew what the edit was meant to be.

### Do you have any supporting links, references, or citations?

[A logic error](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong#a_logic_error)

### Do you have anything more you want to share?

Thanks for all your hard work  :)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/what_went_wrong`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/what_went_wrong/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by teoli2003** [comment]
There is no error: as your browser wrapped between  _always_ and _1_, it gave you the (wrong) understanding that _1_ is a beginning of an ordered list.

This is not the case: on my larger screen, I get:
![Capture d’écran 2023-02-25 à 06 48 55](https://user-images.githubusercontent.com/1466293/221340983-0e1ff6f0-f6b3-46e6-b368-3cefb63d28f0.png)

(I don't see how we could fix it for every screen size)

Hope this helps

**Comment by teoli2003** [comment]
"the constant value 1" ?

**Comment by wbamberg** [comment]
We could reword so "1" isn't at the end of the sentence?

> At this point, the game should play through fine, however after playing through a few times you'll undoubtedly notice that the game always chooses 1 as the "random" number you've got to guess. Definitely not quite how we want the game to play out!

(and/or code format "1" as "`1`")

**Comment by teoli2003** [comment]
Good idea, @wbamberg. I filed a PR with your proposal (including the code format). This should indeed work for every screen size.
