### ISSUE TITLE
"Declaring properties with var" still references var

### ISSUE THREAD

**Issue by pvbestinfoo** [mdn/content#24864]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_semicolon_before_statement

### What specific section or headline is this issue about?

Declaring properties with var

### What information was incorrect, unhelpful, or incomplete?

It is written "You cannot declare properties of an object or array with a *var* declaration."; but the exemple text shows "const" declaration. Seems a little bit confusing...
![image](https://user-images.githubusercontent.com/123185835/221349200-83983752-d018-4a72-8698-5fbdbb208357.png)

### What did you expect to see?

title "Declaring properties with *var* or *const*"
...
"You cannot declare properties of an object or array with a *var* or *const* declaration."
...
"Instead, omit the *var* or *const* keyword:"

### Do you have any supporting links, references, or citations?

-

### Do you have anything more you want to share?

-

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/missing_semicolon_before_statement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_semicolon_before_statement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/missing_semicolon_before_statement/index.md
* Last commit: https://github.com/mdn/content/commit/9c4fb236cd9ced12b1eb8e7696d8e6fcb8d8bad3
* Document last modified: 2023-02-21T01:35:45.000Z

</details>

**Comment by Shivam-Amin** [comment]
I read the documentation & would love to work on this issue.
And should I add an example for var keyword in it?

**Comment by Josh-Cena** [comment]
@Shivam-Amin You should be changing the prose to make it say "`let`, `const`, or `bar` declaration".

**Comment by Shivam-Amin** [comment]
Ok understood.
