### ISSUE TITLE
Filter function demo is not working

### ISSUE THREAD

**Issue by nkarl** [mdn/content#24874]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function

### What specific section or headline is this issue about?

Result from the demo code is not working.

### What information was incorrect, unhelpful, or incomplete?

Result is not working.

### What did you expect to see?

The filter functions (blue, opacity, invert, etc) would produce some effect with the slider.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/filter-function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/filter-function/index.md
* Last commit: https://github.com/mdn/content/commit/66944f622b6b51bc9c24bebbbea242138d910600
* Document last modified: 2023-02-21T05:45:53.000Z

</details>

**Comment by yarusome** [comment]
The demo works in my browser. What OS and what version of which browser do you use? Are you using any filtering extensions?

**Comment by nkarl** [comment]
I apologize for the late reply. I have just checked again and it is still not working on my end.

I am running version 110.0.1 on Windows 11 Pro. I tried again with extensions disabled and it's still the same.

**Comment by yarusome** [comment]
I've opened a PR to fix it. The weird thing is that the demo code was changed a month ago, but it worked for me last week :/
