### ISSUE TITLE
Promise Rejected

### ISSUE THREAD

**Issue by mjrfxci** [mdn/content#24872]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises

### What information was incorrect, unhelpful, or incomplete?

When I try to use the URL in this example. I get the same error always:

GET https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json net::ERR_FAILED
(anonymous) @ VM65:1

Uncaught (in promise) TypeError: Failed to fetch
    at <anonymous>:1:22
(anonymous) @ VM65:1
Promise.then (async)
(anonymous) @ VM65:3

### What did you expect to see?

I was expecting to see what's inside the text

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/promises/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by sideshowbarker** [comment]
I can navigate https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json and see its contents.

I can also access it with Fetch from frontend JavaScript code.
