### ISSUE TITLE
Separate examples for each text fragment part

### ISSUE THREAD

**Issue by riverleaf** [mdn/content#24914]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Text_fragments

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

Information is correct but no examples linking to MDN pages are NOT highlighting any text that is supposed to be highlighted in Safari. However, Safari does highlights **text fragments** on personal websites, on wikimedia.org etc. Therefore, some code on the MDN developer.mozilla.org site is blocking the highlight action. The action to find the text fragment works, but the highlight is blocked. Blocking the highlight is unexpected.
Further, far more understandable if you provide in 'Examples' section five (5) examples. For example, complete syntax for each of text=, textStart, textEnd, prefix-, -suffix.
Further, the required 'a' tag should be included for all examples: for example,
text=
&lt;a href="example.com#:~:text=for%20use"&gt;for use&lt;/a&gt;
textStart... and so on.

### What did you expect to see?

Highlighted text on linked example pages. Also, separate examples for text=, textStart, textEnd, prefix-, -suffix. ;

### Do you have any supporting links, references, or citations?

https://www.freecodecamp.org/news/how-you-can-share-links-that-anchor-to-any-text-on-a-webpage/

### Do you have anything more you want to share?

Text fragments work very well on most sites.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/text_fragments`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Text_fragments
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/text_fragments/index.md
* Last commit: https://github.com/mdn/content/commit/e87af7c2d48e6679acbb5172836e81fe2bc30f2d
* Document last modified: 2023-02-22T08:23:01.000Z

</details>

**Comment by wbamberg** [comment]
Sorry to be slow looking at this.

> Information is correct but no examples linking to MDN pages are NOT highlighting any text that is supposed to be highlighted in Safari. 

It works for me with Safari 16.1:

![text-fragment](https://github.com/mdn/content/assets/432915/f20ffd30-3d07-46ac-aac1-3427d1a315aa)

Am I missing something?

I think I agree with you about the other points though. Also, linking to MDN seems like it might easily get out of date. We could link only to to example.org perhaps.

**Comment by Josh-Cena** [comment]
Looking at this again:

- Safari 16.1 does support text fragments. MDN has a lot of client side magic that seems to block highlighting but that's a platform thing. (Similarly the scroll-to-anchor thing never works).
- The `<a>` tag is implied and is kind of redundant to be explicitly noted everywhere. It's not always the case that it's in an `a` tag; for example you can directly copy this URL into the browser and navigate there.
- We do provide standalone examples for each kind of text fragment. We have examples with textStart, textStart + textEnd, textStart + prefix, textStart + suffix, etc.
