### ISSUE TITLE
Phrasing is misleading

### ISSUE THREAD

**Issue by joelc0193** [mdn/content#24918]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

### What specific section or headline is this issue about?

Active learning: Implementing your own responsive images

### What information was incorrect, unhelpful, or incomplete?

Use srcset/size to create a resolution switcher example, either to serve the same size image at different resolutions, or different image sizes at different viewport widths.

### What did you expect to see?

Use srcset/size to create a resolution switcher example, either to serve the same size image at different resolutions depending on the device resolution, or to serve different image sizes depending on the viewport widths.

### Do you have anything more you want to share?

The word "at" means something different in each occurrence:

1. "same size image at different resolution": Here, "at" means "with".
2. "different image sizes at different viewport widths": Here, "at" means" depending on the".

This is unclear to the reader, who could be stuck wondering what they're being asked to do.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by CBID2** [comment]
Hi @sideshowbarker! 😄 I'm here to help! 👍🏾

**Comment by CBID2** [comment]
> > Hi @sideshowbarker! 😄 I'm here to help! 👍🏾
> 
> Excellent 🎉 Thanks much ー it's all yours

Here's my [PR](https://github.com/mdn/content/pull/25188) @sideshowbarker! 😄 Let me know if changes are needed.
