### ISSUE TITLE
Interpretation of percentage values in grid-gap

### ISSUE THREAD

**Issue by fischhase** [mdn/content#24933]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/gap

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

/* One <percentage> value */
gap: 16%;
gap: 100%;

### What did you expect to see?

Percentage values at grid-gap leads to problems in calculating the height of the grid element. This happens in Firefox, Chrome, Opera and Edge (tested). 
So it should be mentioned in this manual.
Thank you

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/gap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/gap
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/gap/index.md
* Last commit: https://github.com/mdn/content/commit/73091fbe590d96857d743eaeec5aee4a8101994f
* Document last modified: 2023-02-21T05:50:15.000Z

</details>

**Comment by yarusome** [comment]
The spec does have a section for this: [Percentages In `gap` Properties](https://w3c.github.io/csswg-drafts/css-align/#gap-percent), so it *is* the expected result, although it seems a bit difficult to me to concisely explain what's going on here.
