### ISSUE TITLE
Maybe add a section about an easy to make mistake when deleting query parameters while looping over URLSearchParams?

### ISSUE THREAD

**Issue by danieltroger** [mdn/content#24958]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/keys

### What information was incorrect, unhelpful, or incomplete?

I know that when iterating over an array with [].forEach one has to be careful to not delete items from the array, or forEach will skip things. But I never thought of this occuring with the iterator returned by URLSearchParams.keys().

I think it could be good to add a notice/section about it to the documentation page, but I'm not sure. Maybe I'm just stupid to assume that it's _ever_ ok to delete anything while iterating?

### Note

When iterating over the keys in URLSearchParams keys will be skipped if you delete something from the parameters. For example in the example below the loop never visits "test2".

```
const params = new URLSearchParams("?test=Hello&test2=lovely&test3=world");
for (const key of params.keys()) {
  if (key === "test") {
    params.delete(key);
  }
  console.log("Iterated over key", key, "while deleting");
}
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/urlsearchparams/keys`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/keys
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/urlsearchparams/keys/index.md
* Last commit: https://github.com/mdn/content/commit/3ca86db64959ed9dc6c8021dc3eb89e82a6628c7
* Document last modified: 2023-02-19T08:14:59.000Z

</details>

**Comment by wbamberg** [comment]
You mean something like this:

```js
const searchParams = new URLSearchParams("deleteme1=value1&deleteme2=value2&key3=value3");

// Display the keys
const keys = searchParams.keys();
for (const key of searchParams.keys()) {
  if (key.startsWith("deleteme")) {
  searchParams.delete(key)
  }
}

console.log(searchParams);
// URLSearchParams { deleteme2 → "value2", key3 → "value3" }
```

?

It seems like a helpful thing to add. My only reservation is whether this is such a generic problem, that comes up in a lot of different contexts, and documenting it everywhere it comes up would not be practical.

@Josh-Cena , do you think this could fit into `iterable` documentation, or is it better here, or somewhere else?

**Comment by Josh-Cena** [comment]
I think it's fine to put this in iterable. There's a uniform reason why mutations impact iteration: iterables are inherently lazy for various reasons (memory, time, etc.), so they will never be able to snapshot the entire state (otherwise they could just return a static array instead). However, the _actual_ way in which mutations impact iteration is a bit tricky to document well, because it inevitably needs to refer to the underlying algorithm.
