### ISSUE TITLE
window:error event interface and cancelling

### ISSUE THREAD

**Issue by GeorgianStan** [mdn/content#24957]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event

### What specific section or headline is this issue about?

event type, usage notes

### What information was incorrect, unhelpful, or incomplete?

**Event type**
Is mentioned that the [event type](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event#event_type) is `UIEvent`.

**Usage notes**
In [usage notes](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event#usage_notes) is mentioned:

> Unlike other events, the error event is canceled by returning true from the handler instead of returning false. When canceled, the error won't appear in the console, but the current script will still stop executing.

### What did you expect to see?

**Event type***
If we run this code we'll see in the console that the error is of type `ErrorEvent`.
In [HTML spec](https://html.spec.whatwg.org/multipage/indices.html#event-error) is mentioned the same.

```js
window.addEventListener("error", (event) => {
  console.log(event); // event is of type ErrorEvent
});

const badCode = "const s;";
eval(badCode);
```

**Usage notes**

The `return` statement doesn't seem to have an impact, Regardless of the returned value: `return true` or `return false` the error message is displayed in the console.  This event it looks like is similar with [unhandledrejection](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event#preventing_default_handling) and `event.preventDefault()` must be used, so that the message is not printed to the console.

### Do you have any supporting links, references, or citations?

[discussions page](https://github.com/mdn/content/discussions/24950)

**Comment by wbamberg** [comment]
As far as I can tell: the bit about `UIEvent` looks just wrong and it should be `ErrorEvent`.

The bit about cancelling the event is a bit more complicated. I think:
- if you listen for an event using `addEventListener`, yes, you cancel it using `preventDefault()`. And that works fine for `Window`'s `error` event as well.
- but if you listen using the `on`- event handler property, then most of these can _also_ cancel by returning `false`. Try this:

```html
<textarea>Type in me!</textarea>
```

```js
document.querySelector("textarea").onkeydown = (e) => {
	return false;
};
```

Except that for `Window`'s `onerror` handler, this is reversed, and you have to return `true` to cancel:

```html
<button id="error">Error!</button>
```

```js
window.onerror = () => {
	console.log("cancelled!");
	return true;
};
```

The spec also discusses this: https://html.spec.whatwg.org/multipage/webappapis.html#eventhandler.
This is so weird that it definitely seems worth documenting, but that page should be clearer that it is only talking about the event handler property (`onerror`) here.

Does that make sense?

**Comment by GeorgianStan** [comment]
Therefore, looks like `UIEvent` should be replaced with `ErrorEvent` and the documentation should be extended to cover both ways of canceling the event: `return true` for `.onerror` and `preventDefault()` for `addEventListener`.
