### ISSUE TITLE
catName undefined

### ISSUE THREAD

**Issue by david-shiko** [mdn/content#24959]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Test_your_skills:_Object_basics

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Test_your_skills:_Object_basics#object_basics_1

### What information was incorrect, unhelpful, or incomplete?

const cat = {
  name : 'Bertie',
  breed : 'Cymric',
  color : 'white',
  greeting: function() {
    console.log('Meow!');
  }
}

// Put your code here

// Don't edit the code below here

let para1 = document.createElement('p');
let para2 = document.createElement('p');

para1.textContent = `The cat's name is ${ catName }.`;
para2.textContent = `The cat's color is ${ cat.color }.`;

section.appendChild(para1);
section.appendChild(para2);

### What did you expect to see?

const cat = {
  name : 'Bertie',
  breed : 'Cymric',
  color : 'white',
  greeting: function() {
    console.log('Meow!');
  }
}

// Put your code here

// Don't edit the code below here

let para1 = document.createElement('p');
let para2 = document.createElement('p');

para1.textContent = `The cat's name is ${ cat.name }.`;
para2.textContent = `The cat's color is ${ cat.color }.`;

section.appendChild(para1);
section.appendChild(para2);

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/test_your_skills_colon__object_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Test_your_skills:_Object_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/test_your_skills_colon__object_basics/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by teoli2003** [comment]
Isn't the task about creating this variable and initializing it?

**Comment by david-shiko** [comment]
> Isn't the task about creating this variable and initializing it?

oops, sorry, u rigth.
 I just met `ReferenceError: catName is not defined` title and reported it :)

**Comment by teoli2003** [comment]
No problem. I'm closing this then.
