### ISSUE TITLE
Populatedb.js now gives an error when run due to Mongoose dropping support for callback() function on March 23rd

### ISSUE THREAD

**Issue by ying-lenny** [mdn/content#24972]
### MDN URL

https://raw.githubusercontent.com/mdn/express-locallibrary-tutorial/main/populatedb.js

### What specific section or headline is this issue about?

Testing - create some items

### What information was incorrect, unhelpful, or incomplete?

When trying to run `node populatedb <your mongodb url>`, an error occurs stating `MongooseError: Model.prototype.save() no longer accepts a callback` linking to the first function calling callback() on line 109

### What did you expect to see?

Data is expected to appear in the mongoDB collection online but is unable to be added due to the aforementioned error

### Do you have any supporting links, references, or citations?

[The official Mongoose change logs](https://github.com/Automattic/mongoose/blob/master/CHANGELOG.md) state in the 23-03-2023 update notes that

> BREAKING CHANGE: remove support for callbacks #11431

meaning the file will no longer post data as intended

**Comment by hamishwillee** [comment]
Thanks. The tutorial was written and tested against Mongoose 5. It needs to be updated but this will not be immediate.

**Comment by Neil-Carruthers** [comment]
> Thanks. The tutorial was written and tested against Mongoose 5. It needs to be updated but this will not be immediate as it will take significant work.

@hamishwillee How much work would it be to notify readers that they need to use a version no later than 6 in order to follow the tutorial? Right now it instructs readers to download the latest version of Mongoose.
I suggest replacing `npm install mongoose` with `npm install mongoose@6.9.0` [here](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#install_mongoose)

**Comment by hamishwillee** [comment]
@Neil-Carruthers Good suggestion - done in #25095. I had hoped to avoid this by doing the required updates - but I can't fit it in in a timely manner - really this should be done with a full update to await/async behaviour across the whole example.

**Comment by hamishwillee** [comment]
This is now fixed entirely. Thanks for reporting.
