### ISSUE TITLE
A first splash into JavaScript does not explain template literals before use

### ISSUE THREAD

**Issue by gerardmac** [mdn/content#24987]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash

### What information was incorrect, unhelpful, or incomplete?

This code was written in the article _A first splash into JavaScript_
``guesses.textContent += `${userGuess} `;``
In the complete code on another page the above line is replaced by:
`guesses.textContent += userGuess + ' ';`
which makes the effect of the earlier line here apparent but doesn't give a clear explanation of its syntax.

The article is aimed at newcomers to JavaScript, however there is no previous reference to the meaning of `${}` and a Google search provides no help.   

### What did you expect to see?

More detail

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/a_first_splash`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/a_first_splash/index.md
* Last commit: https://github.com/mdn/content/commit/7ff26ceb6c6f1400d4297b22cb92e3786e35eac7
* Document last modified: 2023-02-26T18:57:36.000Z

</details>

**Comment by wbamberg** [comment]
The expression"

```
`${userGuess} `
```
... is a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), which in this case has the effect of concatenating the `userGuess` variable and the space character. So it's equivalent to `userGuess + " "` but is more "modern", and is the recommended approach in our style guide.

But I agree actually that it's much less clear than `userGuess + " "`, especially in this case where we're concatenating with a space. We could use `userGuess + " "` although at some point that'll probably upset a linter.

Or we could do something quite different like keeping all the guesses and writing out `previousGuesses.join(", ");`.

@teoli2003 , @Josh-Cena , thoughts?

**Comment by teoli2003** [comment]
Using template literals without defining them is not the right thing to do, for sure.

Given they are the modern way of doing this, should we not update the section about concatenation to explain them? (And move the section about shorthand operators above, using `+=` with numbers, and not strings, as an example).

**Comment by Josh-Cena** [comment]
I'm always extremely confused by what concepts should be familiar at which point, because programming education is filled with black boxes and "things you don't need to understand at this point". As such I don't have much opinion about this, but I agree with @teoli2003 that we should put template literals far before concatenation and say you should prefer the former.
