### ISSUE TITLE
SVG custom contrast() implementation using <filter>

### ISSUE THREAD

**Issue by estelle** [mdn/content#24989]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/filter

### What specific section or headline is this issue about?

There's no contrast filter page

### What information was incorrect, unhelpful, or incomplete?

The SVG {{SVGElement("filter")}} element is used to define custom filter effects that can then be referenced by {{htmlattrxref("id")}}. The `<filter>`'s {{SVGElement("feComponentTransfer")}} primitive enables pixel-level color remapping. To alter the contrast, include linear {{SVGElement("feFuncR")}} (red), {{SVGElement("feFuncB")}} (blue), and {{SVGElement("feFuncG")}} (green) primitives with the `slope` attribute value defining the contrast multiplier and the `intercept` attribute.

```svg
<svg role="none">
  <filter id="contrast">
    <feComponentTransfer>
      <feFuncR type="linear" slope="[amount]" intercept="-(0.5 * [amount]) + 0.5"/>
      <feFuncG type="linear" slope="[amount]" intercept="-(0.5 * [amount]) + 0.5"/>
      <feFuncB type="linear" slope="[amount]" intercept="-(0.5 * [amount]) + 0.5"/>
    </feComponentTransfer>
  </filter>
</svg>
```

Given the above, the following two statements will produce the same results

```css
.filter {
  filter: contrast(2);
}
.filter {
  filter: url(#contrast);
}
```

To create a filter that doubles the original contrast, we set the `slope` attribute to 2, for 200%, and the `intercept` attribute set to the `-(0.25 * [2.00]) + 0.5`, which is `-0.5`.

```svg
<svg role="none">
  <filter id="contrast">
    <feComponentTransfer>
      <feFuncR type="linear" slope="2" intercept="-0.5"/>
      <feFuncG type="linear" slope="2" intercept="-0.5"/>
      <feFuncB type="linear" slope="2" intercept="-0.5"/>
    </feComponentTransfer>
  </filter>
</svg>
```

### What did you expect to see?

A page where including the above would  makes sense.

**Comment by Josh-Cena** [comment]
@estelle: it is unclear what you want to see documented. Do you want this as an example on the `filter` page? It looks to me a re-implementation of `contrast()`, which I assume is the intention.

**Comment by Josh-Cena** [comment]
Looks like it's fixed in https://github.com/mdn/content/pull/24990
