### ISSUE TITLE
Incomplete, misleading, example of attr()

### ISSUE THREAD

**Issue by karlkaspar** [mdn/content#24983]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/attr

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/27421479/222132922-476e169c-2396-4dcf-a468-458c566d3cb3.png)

### What did you expect to see?

This example proves nothing else but the incapability of the author to turn the background-color to lime.
Please, make a proper example where you modify anything but a pseudo element.
I can't get it to work with nothing but pseudo elements.
![image](https://user-images.githubusercontent.com/27421479/222133688-bb90fa42-0cc7-4625-adc0-79c13d08701e.png)

Even though it is stated that it works with regular elements, it simply does not work.
So you guys have an incomplete example of attr()

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/attr`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/attr
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/attr/index.md
* Last commit: https://github.com/mdn/content/commit/42c1bb8c259f3f57de9f38600776cf273e3addda
* Document last modified: 2023-02-21T06:27:49.000Z

</details>

**Comment by teoli2003** [comment]
![Capture d’écran 2023-03-01 à 13 13 05](https://user-images.githubusercontent.com/1466293/222136189-e73f7940-1112-4400-9587-d9bcd677b09e.png)


According to the table at the bottom of the article, no browser supports this yet.

**Comment by Josh-Cena** [comment]
Yes, we even have an experimental banner for this specific example.
