### ISSUE TITLE
Misleading operator precedence AND over OR

### ISSUE THREAD

**Issue by adrianbienias** [mdn/content#25011]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

### What specific section or headline is this issue about?

Table

### What information was incorrect, unhelpful, or incomplete?

Logical AND (&&) operator is placed above OR (||) operator.
Because of short-circuiting, this precedence cannot be satisfied, thus AND and OR have the same precedence.

### What did you expect to see?

Logical AND operator should have the same precedence as OR operator.

### Do you have any supporting links, references, or citations?

In the following example, function isn't evaluated at all because of short-circuiting on OR operator, thus higher precedence of AND isn't satisfied.
```
true || alert("foo") && "bar"
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/operator_precedence/index.md
* Last commit: https://github.com/mdn/content/commit/0f3738f6b1ed1aa69395ff181207186e1ad9f4d8
* Document last modified: 2023-02-21T00:33:34.000Z

</details>

**Comment by Josh-Cena** [comment]
Please see https://github.com/mdn/content/issues/19387. Precedence affects evaluation _result_, not evaluation _order_—operands are always evaluated left-to-right, and short-circuiting allows you to skip evaluation of certain operands. The short-circuiting section also has a paragraph saying:

> Only C() is evaluated, despite && having higher precedence. This does not mean that || has higher precedence in this case — it's exactly because (B() && A()) has higher precedence that causes it to be neglected as a whole.

**Comment by adrianbienias** [comment]
@Josh-Cena I've read that part, but it still doesn't make sense to me to have AND higher in the table than OR.

Instead, I'd expect the table to communicate that both have the same precedence.

`true || alert("foo") && "bar"` works differently (by evaluating the function) than `alert("foo") && "bar" || true`

Where's that precedence of `&&` clearly visible to be higher than `||`?
Can you provide an example?

**Comment by Josh-Cena** [comment]
Let's not think in terms of short-circuiting: if these operands have different precedences, the evaluation result will be entirely different.

```js
(false && true) || true; // true
false && (true || true); // false
```

We proposed a post-order traversal model, and you could use that to understand this behavior.

```
true || alert("foo") && "bar":

          ||
 ┌────────┴────────┐
true               &&
          ┌────────┴────────┐
     alert("foo")           "bar"
```

The traversal starts at `||`, then visits its left child which is `true`. Because this node is already truthy, the right child is not visited, hence the entire `alert("foo") && "bar"` expression is not evaluated.

```
alert("foo") && "bar" || true:

                       ||
              ┌────────┴────────┐
              &&               true
     ┌────────┴────────┐
alert("foo")         "bar"
```

The traversal starts at `||`, then visits its left child which is `alert("foo") && "bar"`. Because this node is now the left operand, it's always evaluated, hence `alert()` is called.

You may try this yourself to verify that it cannot work under any other precedence order.

**Comment by adrianbienias** [comment]
> Let's not think in terms of short-circuiting
Right, I narrowed my vision to short-circuiting and had a feeling that above all precedence there's all mighty short-circuiting.

That post-order traversal model helps to clearly see how things work, but it's still counter-intuitive for me to treat higher precedence operators as children and lower precedence operators as parents.

Those _higher_ and _lower_ words just implies that I expect those things to be placed higher/lower on the tree as well, not the opposite.

Anyway, thanks for your help!
