### ISSUE TITLE
[Devtools] Enable color scheme simulation on all channels

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#2501]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. color scheme simulation in devtools. This needs a rel note. The feature is already documented here — https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS — but the references to where it is supported need changing, and the UI has changed too, so new screenshots needed. See if it is mentioned anywhere else too.

## Related Gecko bugs

1. - [ ] [Enable color scheme simulation on all channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1692272)
1. - [ ] [Enable color scheme simulation (devtools.inspector.color-scheme-simulation.enabled)](https://bugzilla.mozilla.org/show_bug.cgi?id=1679408)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
Quick review
- [ ] BCD - NA
- [ ] Interactive example - NA
- [ ] Docs
   - [ ] [How_to/Examine_and_edit_CSS > View @media rules for color-scheme-preference  ](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#view_media_rules_for_color-scheme-preference) - Update the UI and screenshots. Needs a bit of clarification.
   - [ ] [@media/prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) - needs cross-link to the debugging tool
   - [ ] [Remove from experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features)
   - [ ] Release note

**Comment by hamishwillee** [comment]
FYI, done, but I'm checking that I understand how this works in https://github.com/mdn/content/pull/2562#issuecomment-786420642

**Comment by chrisdavidmills** [comment]
This one can be closed too. Nice work!
