### ISSUE TITLE
ARRAY SLICE returns a deep copy

### ISSUE THREAD

**Issue by Satish8798** [mdn/content#25036]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

### What specific section or headline is this issue about?

Array.prototype.slice()

### What information was incorrect, unhelpful, or incomplete?

The slice() method returns a [shallow copy](https://developer.mozilla.org/en-US/docs/Glossary/Shallow_copy) of a portion of an array into a new array object selected from start to end (end not included) where start and end represent the index of items in that array. The original array will not be modified.

### What did you expect to see?

As I am practicing with slice function, I observed that slice is returning a deep copy , when we update the copy object that we got from slice is not affecting the source object. In this documentation, it is mentioned as a shallow copy. same thing I found in Array.from() also.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/slice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/slice/index.md
* Last commit: https://github.com/mdn/content/commit/194d3e00cb93a6e5ea44812548f4131cb17f0381
* Document last modified: 2023-02-21T00:33:25.000Z

</details>

**Comment by Josh-Cena** [comment]
Please see https://github.com/mdn/content/issues/17889
