### ISSUE TITLE
Deprecated read-only property in use within Example 4 source code

### ISSUE THREAD

**Issue by Phil-G-94** [mdn/content#25044]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls/Example_4

### What specific section or headline is this issue about?

Handling the control value

### What information was incorrect, unhelpful, or incomplete?

The source code for the final example shows use of they deprecated KeyboardEvent.keyCode read-only property. 

The article code correctly uses KeyboardEvent.key, so there is a disparity between the two. 

### What did you expect to see?

Use of KeyboardEvent.key only across both article and example source code.

### Do you have any supporting links, references, or citations?

Article code: 

```
    select.addEventListener('keyup', (event) => {
      let index = getIndex(select);

      // When the user hits the down arrow, we jump to the next option
      if (event.key === "ArrowDown" && index < optionList.length - 1) {
        index++;
      }

      // When the user hits the up arrow, we jump to the previous option
      if (event.key === "ArrowUp" && index > 0) {
        index--;
      }
```

Example source code: 
```
    select.addEventListener('keyup', (event) => {
      let index = getIndex(select);

      if (event.keyCode === 27) {
        deactivateSelect(select);
      }
      if (event.keyCode === 40 && index < optionList.length - 1) {
        index++;
      }
      if (event.keyCode === 38 && index > 0) {
        index--;
      }

```

### Do you have anything more you want to share?

Happy to fix it myself if I am correct in thinking the use of .keyCode should be replaced with .key. Please advise next steps as first issue/fix for me. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/how_to_build_custom_form_controls/example_4`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls/Example_4
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_build_custom_form_controls/example_4/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by teoli2003** [comment]
`keyCode` is indeed deprecated in favour of `key`.  A PR to fix it is welcome and we will happily review it. (Mention this issue when you open it so that we can close it when the PR is merged)

**Comment by Phil-G-94** [comment]
Thank you @teoli2003. Is there a point in you 'assigning' this to me before I progress, or shall I just progress to making proposed changes & PR?

**Comment by teoli2003** [comment]
I've assigned it to you (no real need, but this tells others you are working on the issue.)

Feel free to fix both problems in one PR.
