### ISSUE TITLE
when using FormData objects to send a post  XMLHttpRequest，the content-type  default is 'multipart/form-data'

### ISSUE THREAD

**Issue by smartLe061225** [mdn/content#25045]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#using_formdata_objects

### What information was incorrect, unhelpful, or incomplete?

As I mention in the title，when using FormData objects to send a post  XMLHttpRequest，the content-type  default is 'multipart/form-data'. I guess that it's unuseful to set enctype value ‘text/plain’ for form element, in other word, the content-type will be  'multipart/form-data' when thie client-agent  post  XMLHttpRequest in this position.

 <p>The text/plain encoding is not supported by the FormData API.</p>
 
 the html template above is found in 'https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#using_formdata_objects' segment. I guss the correct description should be:
  <p>The text/plain encoding is supported by the FormData API.</p>

### What did you expect to see?

<p>The text/plain encoding is supported by the FormData API.</p>

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/xmlhttprequest/using_xmlhttprequest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
* Last commit: https://github.com/mdn/content/commit/92435b5f26c680a2314d392ef06f479216f0b4dd
* Document last modified: 2023-02-27T14:15:34.000Z

</details>

**Comment by Josh-Cena** [comment]
This section is removed in https://github.com/mdn/content/pull/25383
