### ISSUE TITLE
[CSS] activation behavior and :link/:visited/:any-link matching for <link>s

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#2506]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. activation behavior and :link/:visited/:any-link matching for `<link>`s

## Related Gecko bugs

1. - [x] [Remove activation behavior and :link/:visited/:any-link matching for `<link>`s](https://bugzilla.mozilla.org/show_bug.cgi?id=1687538)

Needs investigation to figure out what to write for this.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
@chrisdavidmills not sure we need to do much more than the updates I made, this was already the behaviour in Chrome, I'm not sure anyone was using this behaviour so it probably doesn't warrant a BCD update. It's really a spec simplification.

**Comment by chrisdavidmills** [comment]
@rachelandrew it does seem very weird and unlikely that anyone would want to style `<link>` elements full stop. But you never know. Do you think it'd be good to add a simple note to the existing data points, just in case? Something like "From version 87 onwards, `:link` no longer matches `<link>` elements"?

**Comment by rachelandrew** [comment]
@chrisdavidmills so :visited already has this as a separate line mentioning Chrome https://developer.mozilla.org/en-US/docs/Web/CSS/:visited

Do we want to unify them at this point? Either by adding the same line for the others mentioning Firefox as well, or making it a note on all?

**Comment by chrisdavidmills** [comment]
Hrm, it looks like that is kind of the "standard" or "expected" behavior, so I'd instead remove the Chrome note, and add notes just on Firefox for when that behavior is deviated from. It'd be a lot easier that way, IMO. Unless of course Safari, IE, etc. used to behave like that. Sounds like potentially a lot of work for something so minor, which I guess is why you were questioning it in the first place ;-)

But I feel like a precedent has been set by the Chrome note, so we need to do _something_ here.

**Comment by rachelandrew** [comment]
I think this was an interop thing where it had to be decided one way or another and actually put into the spec. Looks like Safari need to update too https://github.com/whatwg/html/pull/6269

**Comment by chrisdavidmills** [comment]
OK, cool. Let's go with my plan then, just adding notes for Fx/Safari? We shouldn't need to add notes for older stuff like IE...

**Comment by rachelandrew** [comment]
ok, I have had a go at that in https://github.com/mdn/browser-compat-data/pull/9305

**Comment by ddbeck** [comment]
OK, coming over here from https://github.com/mdn/browser-compat-data/pull/9305#issuecomment-789927430. Here's what I said in [my review](https://github.com/mdn/browser-compat-data/pull/9305#pullrequestreview-603167102):

> I think we need to go the opposite direction here and make the other features more closely resemble `:visited` with a `not_match_link` subfeature. This has three benefits:
> 
>  1. We don't add an asterisk to most of the top-row `:visited` entries for something that's (now) standardized.
> 
>  2. We don't add a couple dozen notes for data that can be represented structurally. The subfeature gets the benefit of consistency checks, while notes don't.
> 
>  3. We can reduce the absolute number of notes by dropping all the redundant "Chromium has never…" notes.

@chrisdavidmills, you proposed the subfeature structure in https://github.com/mdn/browser-compat-data/pull/4817. What made you turn on it?

**Comment by chrisdavidmills** [comment]
@ddbeck ack, I don't even remember that conversation ;-|

So much stuff, y'know? ;-)

Looking at it again, I just felt that it seemed a bit weird having a separate row for something that almost feels like expected behavior rather than a separate feature...but then again, you've got some points here too, and it sounds like you think that having the subfeature would be easier to check and less confusing. You know the data better than me, so I'm happy to defer to you opinion here, to a large degree.

Sorry for the confusion hre @rachelandrew . What option seems better to you, from a user standpoint?

**Comment by chrisdavidmills** [comment]
OK, this one has stalled, so I'll make a decision. Let's go with the original structure that we had in place, with a `not_match_link` subfeature, instead of what I suggested above.

Sorry about that @rachelandrew .

**Comment by rachelandrew** [comment]
sorry missed this, I'll sort this today.

**Comment by chrisdavidmills** [comment]
> sorry missed this, I'll sort this today.

No worries, and cheers!
