### ISSUE TITLE
event.buttons is 0 for pointerleave event that leaves browser window too fast

### ISSUE THREAD

**Issue by musodojo** [mdn/content#25062]
For elements at the very edge of the browser window, a pointerleave event with pointer down engaged (e.g. left mouse button) reports no buttons down when the pointer leaves the browser at high speed.

**Comment by wbamberg** [comment]
Thanks for filing! But I'm not sure whether this is a bug with MDN documentation or something else. If it is a bug with the docs, please indicate where in the docs the problem is, and what it ought to say instead.

**Comment by musodojo** [comment]
Apologies - I should have filed a bug report with Firefox development!

**Comment by wbamberg** [comment]
No worries @musodojo .
