### ISSUE TITLE
populatedb.js file doesn't work anymore, mongoose no longer accepts callbacks.

### ISSUE THREAD

**Issue by Stonehagen** [mdn/content#25069]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

### What specific section or headline is this issue about?

Testing — create some items

### What information was incorrect, unhelpful, or incomplete?

The populatedb.js file does not work anymore, because mongoose no longer accepts callbacks.

### What did you expect to see?

A populated Database

### Do you have any supporting links, references, or citations?

throw new MongooseError('Model.prototype.save() no longer accepts a callback');

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by hamishwillee** [comment]
Yeah, its a duplicate. If you use Mongoose 5 this will work.

**Comment by davidko5** [comment]
So I should remove the 7th version mongoose npm package and install mongoose v5 instead ?

**Comment by hamishwillee** [comment]
Yes. I have updated the docs to say install mongoose@6.9.0 as this is the last version that works. This is obviously just a patch - at some point soon I hope to rewrite the tutorial to use async/await and we can then use mongoose 7.
