### ISSUE TITLE
[CSS] remove -moz-outline-radius

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#2507]
## Acceptance criteria

1. - [ ] The listed features are documented sufficiently on MDN
2. - [ ] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. removal of -moz-outline-radius

## Related Gecko bugs

1. - [ ] [outline should follow shape of border-radius (remove -moz-outline-radius)](https://bugzilla.mozilla.org/show_bug.cgi?id=315209)

Looks fairly simple — rel note, BCD, page update, to document a prefixed alias removal?

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
@chrisdavidmills I think this is only enabled in Nightly right now. By the looks of it the pre checks for a Nightly build - and comments on the bug mention "when it ships", I have asked. If so it is probably too soon to do the BCD for the removal etc.

**Comment by rachelandrew** [comment]
Answered immediately - not in release 87 but here is the bug to enable it https://bugzilla.mozilla.org/show_bug.cgi?id=1694146

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills I think this is only enabled in Nightly right now. By the looks of it the pre checks for a Nightly build - and comments on the bug mention "when it ships", I have asked. If so it is probably too soon to do the BCD for the removal etc.

Perfect. I was just about to jump on here and make you aware of this (I just found out!), but you beat me to it ;-)

**Comment by rachelandrew** [comment]
So not sure there is anything to do here, a note on experimental features?

**Comment by chrisdavidmills** [comment]
Sounds like it.

**Comment by rachelandrew** [comment]
@chrisdavidmills done, and looks like I'll be revisiting it for the 88 release.

**Comment by chrisdavidmills** [comment]
I'm going to close this for now; I'll write a new issue for the final enabling.
