### ISSUE TITLE
Using_the_JavaScript_API: Youtube link issue

### ISSUE THREAD

**Issue by AndriiMaliuta** [mdn/content#25079]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API#viewing_wasm_in_developer_tools

### What information was incorrect, unhelpful, or incomplete?

Link to youtube video leads to 404:
 [WebAssembly debugging with Firefox DevTools](https://www.youtube.com/watch?v=R1WtBkMeGds)

### What did you expect to see?

video present to watch

### Do you have any supporting links, references, or citations?

https://www.youtube.com/watch?v=R1WtBkMeGds

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/webassembly/using_the_javascript_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/using_the_javascript_api/index.md
* Last commit: https://github.com/mdn/content/commit/fe898ddf33314ee129256c3862c5c53106eeec1f
* Document last modified: 2023-02-23T10:05:41.000Z

</details>

**Comment by hound77** [comment]
@AndriiMaliuta I would like to work on this issue.

**Comment by hound77** [comment]
@AndriiMaliuta from where I will get link to the video to update it in code?

**Comment by hound77** [comment]
@wbamberg In that case please assign me I will work on this issue.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/pull/25244. Thanks @hound77 !
