### ISSUE TITLE
Image files with spaces

### ISSUE THREAD

**Issue by timotay01** [mdn/content#25081]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Node_server_without_framework

### What specific section or headline is this issue about?

variable exists seems to resolve to false when an image file has a space

### What information was incorrect, unhelpful, or incomplete?

404.html is shown if entering the full url for an image with space in filename

### What did you expect to see?

the displayed image

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/node_server_without_framework`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Node_server_without_framework
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/node_server_without_framework/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by sideshowbarker** [comment]
It’s not clear what problem with the https://developer.mozilla.org/en-US/docs/Learn/Server-side/Node_server_without_framework article is being described here. Please clarify and add more details.
