### ISSUE TITLE
[DevTools] Allow devtools to toggle the :target pseudo-class

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#2508]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Allow devtools to toggle the :target pseudo-class

## Related Gecko bugs

1. - [x] [Allow devtools to toggle the :target pseudo-class](https://bugzilla.mozilla.org/show_bug.cgi?id=1689899)

Pretty simple; adding another pseudo-class to the pseudo-class display selector in the CSS rules view

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
The work for this was done by the developer in https://github.com/mdn/content/pull/2020. I've removed the draft on that and it is ready to go in.

**Comment by chrisdavidmills** [comment]
This can be closed; awesome!
