### ISSUE TITLE
Document HTML popover attribute (and related features)

### ISSUE THREAD

**Issue by annevk** [mdn/content#25125]
The HTML Standard now defines a `popover` attribute as well as some APIs around that. Most of it can be found here: https://html.spec.whatwg.org/multipage/popover.html.

There are still some issues outstanding, one which will significantly impact some of the related attributes: https://github.com/whatwg/html/pull/8962. Otherwise this is ready for being documented.

**Comment by hamishwillee** [comment]
From https://github.com/whatwg/html/pull/8221, there are three implementation bugs filed but no releases:
- Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1307772
- Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1808823
- Safari: https://bugs.webkit.org/show_bug.cgi?id=250171

Normally the precondition for documentation would be at least one released, or at least testable, implementation. So it might be worth waiting before this gets done. @Rumyra perhaps add to project backlog?

**Comment by teoli2003** [comment]
I think we also need bcd for `ToggleEvent` and members, as well as documentation for `ToggleEvent.*` members as `popover` is a `ToggleEvent`. (Not sure if it was already implemented, or speced, before)

**Comment by Mark-MetaSource** [comment]
popover attribute was used in AngularJS 1.5. It was renamed to uib-popover in later releases however any web site using AngularJS early versions will break due to this addition. Documentation note that reflects this could be useful.

**Comment by Josh-Cena** [comment]
Fixed in https://github.com/mdn/content/pull/26413
