### ISSUE TITLE
[CSS] ::first-letter pseudo-element should consider both characters within letter combinations like the Dutch "ij"

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#2512]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. ::first-letter pseudo-element should consider both characters within letter combinations like the Dutch "ij"

## Related Gecko bugs

1. - [x] [::first-letter pseudo-element should consider both characters within letter combinations like the Dutch "ij"](https://bugzilla.mozilla.org/show_bug.cgi?id=92176)

::first-letter is already documented, but the page needs sorting out. There is already a note about this problem, which needs modifying, and there is a completely separate BCD entry just for this problem, which needs updating.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
I feel we should just take a moment to celebrate the fact that bug was opened 20 years ago.

**Comment by chrisdavidmills** [comment]
> I feel we should just take a moment to celebrate the fact that bug was opened 20 years ago.

Indeed ;-)

**Comment by chrisdavidmills** [comment]
This one is definitely done; closing!
