### ISSUE TITLE
[CSS] Disable theme-related CSS media queries features when not in chrome context

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#2515]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Disable theme-related CSS media queries features when not in chrome context

## Related Gecko bugs

1. - [x] [Disable theme-related CSS media queries features when not in chrome context](https://bugzilla.mozilla.org/show_bug.cgi?id=787521)

Most of these do not have their own page, or are even mentioned at all on MDN. Where they do, the pages seem to be archived. I'd remove the archived pages, remove the other mentions (e.g. on the Mozilla Extensions page), and write a rel note.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
I think this is done in the above PRs.

**Comment by chrisdavidmills** [comment]
OK, this is done!
