### ISSUE TITLE
[HTTP] Set referrer policy default to strict-origin-when-cross-origin

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#2516]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate - NA
4. - [x] The content has been reviewed as needed

## Features to document

1. Set referrer policy default to strict-origin-when-cross-origin

## Related Gecko bugs

1. - [x] [Set referrer policy default to strict-origin-when-cross-origin](https://bugzilla.mozilla.org/show_bug.cgi?id=1589074)

Looks like probably a pretty small change — rel note, page change, BCD entry?

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
- [ ] BCD is updated
- [ ] Release note
- [ ] Dev-doc-complete
- [ ] Docs
  - [ ] [HTTP/Headers/Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer)
      - [ ] Needs a bit of a tidy. Doesn't really talk about the Referrer-Policy, and has text that talks about one aspect of that. 
  - [ ] [Referer header: privacy and security concerns](https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns)
     - [ ] Need to think a bit more on this. But I think it worth noting that the defaults do help you. 
  - [ ] [HTTP/Headers/Referrer-Policy ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)
     - [ ] BCD update required to move note on the preference into the BCD itself
     - [ ] BCD update to change default setting
     - [ ] Doc update to change default setting. 

Not under our control but this also refers to the old default: https://infosec.mozilla.org/guidelines/web_security.html#referrer-policy

**Comment by hamishwillee** [comment]
@chrisdavidmills FYI This is pretty much done except for adding back browser preference notes in https://github.com/mdn/content/pull/2954 . The BCD will go in shortly.

**Comment by chrisdavidmills** [comment]
Done, and closed!
