### ISSUE TITLE
Missing HTMLAllCollection

### ISSUE THREAD

**Issue by daiwanxing** [mdn/content#25178]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/all

### What specific section or headline is this issue about?

HTMLAllCollection

### What information was incorrect, unhelpful, or incomplete?

While I was browsing `Document.all`, I found an object I had never heard of - HTMLAllCollection, I want figure out what that used for, but mdn not record this api
### 

### What did you expect to see?

add new content for HTMLAllCollection

**Comment by teoli2003** [comment]
Yes, this is an interface I would like to see documented. We don't have enough time for the moment, but I would happily review a PR. 

For anybody wanting to document it, the spec is there: https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#the-htmlallcollection-interface

**Comment by daiwanxing** [comment]
Thanks your reply, Maybe I'll do it in my free time.
