### ISSUE TITLE
Missing documentation of methods and properties of `HTMLOptionsCollections`

### ISSUE THREAD

**Issue by yarusome** [mdn/content#25190]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionsCollection

### What specific section or headline is this issue about?

"Instance properties" and "Instance methods"

### What information was incorrect, unhelpful, or incomplete?

The `HTMLOptionsCollection` interface has the `add()` and `remove()` methods, and the `selectedIndex` property, all of which are not documented on the MDN page. Apart from this, the `length` property is not documented on a separate page.

### What did you expect to see?

Docs for these methods and properties.

### Do you have any supporting links, references, or citations?

HTML standard: https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#the-htmloptionscollection-interface

### Do you have anything more you want to share?

The `HTMLSelectElement` interface also has the mentioned methods and properties, which function like their `HTMLOptionsCollection` counterparts.

**Comment by teoli2003** [comment]
Thank you. Yes, these pages are among the missing ones on MDN. We would like to see them documented, although we currently don't have the bandwidth to create them ourselves. 

I would happily review a PR.

**Comment by postmeback** [comment]
Please assign it to me, I would love to contribute on this.

@teoli2003 @Josh-Cena

**Comment by Josh-Cena** [comment]
@postmeback You don't need assignment to work on anything. You could simply send a PR that links to this issue.

**Comment by teoli2003** [comment]
I recommend you start witha PR with one page. Feel free to ask any question.

**Comment by postmeback** [comment]
https://github.com/mdn/content/pull/26724

Kindly review and provide me feedback. Would love to update it, as per the teams suggestion.

@teoli2003 @Josh-Cena

**Comment by yarusome** [comment]
@postmeback A pass-by comment: The review happens in the PR and usually it's better to ask for a review from the actually assigned member there instead of here.

**Comment by postmeback** [comment]
As my open source focus has shifted, I wish to get unassigned from this ticket.

Thanks, everyone, for your time and feedback.

**Comment by Brian-Pob** [comment]
I am interested in taking this on. Though I probably won't be able to make any significant changes any time soon. I need to do more research into the APIs mentioned as well as how to write with multiple pages in mind.

Thanks.

**Comment by hamishwillee** [comment]
@Brian-Pob You can certainly do so. We no longer assign issues directly. If you want to work on something you create a PR to fix it and cross link to here from it by adding  `Fixes #25190` in the PR's description. Conversely, if you are thinking of taking on an issue, you check that there are no PRs linked to it (right now there are none, so this is free).

**Comment by Josh-Cena** [comment]
Hi! I'm closing this in favor of https://github.com/mdn/mdn/issues/520 so it can be done in a more organized way.
