### ISSUE TITLE
There is something wrongs with description of 'Object.create(proto, propertiesObject)'

### ISSUE THREAD

**Issue by lxc512157407** [mdn/content#25193]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create

### What specific section or headline is this issue about?

There are something wrongs with description of 'Object.create(proto, propertiesObject)'

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/11299246/223909171-7d064196-cf52-4905-8055-0fc37e559c06.png)
`/**
 * method1 is equal method2.they have same effects.
 * @type {{pro1_true: {enumerable: boolean, value: string}, pro1_false: {enumerable: boolean, value: string}}}
 */
let properties={
    pro1_true:{
        value:'pro1_1',
        enumerable:true,
    },
    pro1_false:{
        value:'pro2',
        enumerable:false,
    },

}
let tmp={a:1}
// method1
let obj=Object.create(tmp);
Object.defineProperties(obj,properties);

// method2
let obj1=Object.create(tmp,properties);
console.info(Object.getOwnPropertyDescriptors(obj))

Object.keys(obj).forEach(val=>console.info(val))
Object.keys(obj1).forEach(val=>console.info(val));`

### What did you expect to see?

![image](https://user-images.githubusercontent.com/11299246/223910317-597e4fee-b982-458e-82b1-66160298a5e1.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/create`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/create/index.md
* Last commit: https://github.com/mdn/content/commit/fcd80ee4c8477b6f73553bfada841781cf74cf46
* Document last modified: 2023-02-21T01:57:14.000Z

</details>

**Comment by lxc512157407** [comment]
There are a standards of ecmascript.
https://tc39.es/ecma262/#sec-object.create
![image](https://user-images.githubusercontent.com/11299246/223910930-5bb9be05-6701-4d63-9e9d-37539690f9af.png)

**Comment by Josh-Cena** [comment]
Hi, "whose enumerable own properties" refer to the properties of `propertiesObject` itself. For example, if you have this:

```js
const properties = Object.create(null, {
  nonEnumerable: { value: 1 },
});

const obj = Object.create(null, properties);
```

Then `nonEnumerable` will not show up in `obj`, because it's not an enumerable property of `properties`. In the spec, you should be looking at [`ObjectDefineProperties`](https://tc39.es/ecma262/#sec-objectdefineproperties), which says:

> For each element nextKey of keys, do
>   a. Let propDesc be ? props.[[GetOwnProperty]](nextKey).
>   b. If propDesc is not undefined and propDesc.[[Enumerable]] is true, then
>     i. Let descObj be ? [Get](https://tc39.es/ecma262/#sec-get-o-p)(props, nextKey).
>     ii. Let desc be ? [ToPropertyDescriptor](https://tc39.es/ecma262/#sec-topropertydescriptor)(descObj).
>     iii. Append the pair (a two element [List](https://tc39.es/ecma262/#sec-list-and-record-specification-type)) consisting of nextKey and desc to the end of descriptors.

Note how it uses `props.[[GetOwnProperty]]` and checks `propDesc.[[Enumerable]]`. They correspond to the "enumerable own".

**Comment by lxc512157407** [comment]
I see .you are right. thank you much !
