### ISSUE TITLE
Various issues with "instanceof": a weird claim, typos...

### ISSUE THREAD

**Issue by jakseb** [mdn/content#2521]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof

### Description > [instanceof and multiple context (e.g. frames or windows)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_context_e.g._frames_or_windows)

> For instance, `[] instanceof window.frames[0].Array` will return `false`, because **`Array.prototype !== window.frames[0].Array`** and **arrays** inherit from the former.

I believe the inequality should be `Array.prototype !== window.frames[0].Array.prototype`. In addition, 'arrays' alone might suggest that *all* arrays inherit from `Array.prototype`, including those from `frames[0]`. I think that needs to be clarified, e.g. 'arrays created in the current context'.

> For example, checking if a **Nodes** is a SVGElement in a different context, you can use myNode instanceof myNode.ownerDocument.defaultView.SVGElement.

It should be 'Node', not 'Nodes'.

### Examples > [Demonstrating that String and Date are of type Object and exceptional cases](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#demonstrating_that_string_and_date_are_of_type_object_and_exceptional_cases)

> However, objects created with the object literal notation are an exception here: Although the prototype is `undefined`, `instanceof Object` returns `true`.

It is not true that the prototype is `undefined`. It's `Object.prototype`, which is even stated in the code that follows. Thus, there's nothing exceptional here. I think the paragraph quoted above should be removed and some adjustments should be made to the rest of the section (including its title).

### Other

Maybe it might be a good idea to mention shortly the role of `Symbol.hasInstance`?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/instanceof`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/instanceof/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this 👍

**Comment by chrisdavidmills** [comment]
Happy to let you give it a go; thanks a lot for all your enthusiasm, @CreaTorAlexander !

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills I enjoy contributing to mdn/content 😄
