### ISSUE TITLE
Issue with "MediaStreamTrack: mute event": onunmute example has typo

### ISSUE THREAD

**Issue by stephenlindauer** [mdn/content#2522]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/mute_event

#### What information was incorrect, unhelpful, or incomplete?
The second half of the second example looks to be attempting to demonstrate the `onunmute` event handler property, however instead of `unmute`, it says `mute`.

```
            v-- this looks wrong
musicTrack.mute = event = > {
  document.getElementById("timeline-widget").style.backgroundColor = "#fff";
}
```

#### Specific section or headline?
[Examples](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/mute_event#examples)

#### What did you expect to see?

```
musicTrack.onunmute = event = > {
  document.getElementById("timeline-widget").style.backgroundColor = "#fff";
}
```

#### Did you test this? If so, how?
No, but [the MediaStreamTrack.onunmute page](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/onunmute) shows the correct behavior that I believe was desired in the example.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediastreamtrack/mute_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/mute_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediastreamtrack/mute_event/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this 👍
