### ISSUE TITLE
MIME error

### ISSUE THREAD

**Issue by LeCharles97** [mdn/content#25245]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

### What specific section or headline is this issue about?

Deploying static content to pages

### What information was incorrect, unhelpful, or incomplete?

I keep receiving this error
 'Loading module from “https://lecharles97.github.io/cfg-dataB/src/main.jsx” was blocked because of a disallowed MIME type (“text/jsx”). cfg-dataB'

### What did you expect to see?

I expect the project to be deployed correctly

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/x-content-type-options`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/x-content-type-options/index.md
* Last commit: https://github.com/mdn/content/commit/c44653e3f3502fbda86ba392ed8058e1e3a0a0de
* Document last modified: 2023-03-03T04:38:28.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing problems in the MDN documentation.

It looks like you are seeking help with your code. Unfortunately, we don't have enough availability to help you.

If you have a problem with your code, I suggest you ask your question on a specialized website like [StackOverflow](https://stackoverflow.com/questions).

I'm closing this issue. If I've misunderstood you and you were reporting a problem in the documentation, feel free to reopen it while providing more information so we can understand the problem.

Thanks for your interest.
