### ISSUE TITLE
WebRTC "Perfect negotiation" page missing from sidebar

### ISSUE THREAD

**Issue by wolfgang42** [mdn/content#25257]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation

### What specific section or headline is this issue about?

Sidebar

### What information was incorrect, unhelpful, or incomplete?

I spent ages trying to debug negotiation problems before I found this article.

### What did you expect to see?

It seems like it's supposed to be in the Guides section of the sidebar? (It is in [that section on the main page](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API#guides) but I didn't notice it there.)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webrtc_api/perfect_negotiation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webrtc_api/perfect_negotiation/index.md
* Last commit: https://github.com/mdn/content/commit/4f0f7386262363103a3e9cf482bb348d8570b331
* Document last modified: 2023-02-19T08:44:25.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing, @wolfgang42 ! https://github.com/mdn/content/pull/25261 ought to take care of this.
