### ISSUE TITLE
Issue with "Using Promises": (short summary here please)

### ISSUE THREAD

**Issue by paras-jft** [mdn/content#2525]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises

#### What information was incorrect, unhelpful, or incomplete?
While explaining the timing concept with Promises, "Wait" function is called with no argument,

#### Specific section or headline?

Timing

#### What did you expect to see?
 Wait (1000)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/using_promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/using_promises/index.html
* Last commit: https://github.com/mdn/content/commit/2812703fe5f905cbbb7aa5eaee2c2026d53af508
* Document last modified: 2021-02-18T07:11:32.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I will take a look at it 👍

**Comment by Ryuno-Ki** [comment]
@CreaTorAlexander Let me know when you feel confident in resolving it.

**Comment by CreaTorAlexander** [comment]
@Ryuno-Ki yes I feel confident.

Which amount of MS should I pass to the example or can I just take 1000?

`wait(1000).then(() => console.log(4));`

To wait 1 second?

**Comment by Ryuno-Ki** [comment]
The original suggestion was 1s, so `1000` sounds reasonable.

**Comment by avivmu** [comment]
What is the problem with `wait()` without arguments? It will call [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout) with 0 which will be executed the next event loop

**Comment by CreaTorAlexander** [comment]
@avivmu because it makes no sense

`const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
`
Here we explicit define the parameter *ms* for wait and then we are not using it.

**Comment by avivmu** [comment]
I read the mentioned section. I agree that explicit is better. Lets change it to `wait(0)` (not 1000) because we want to show that even though we run the `setTimeout()` immediately, `console.log(4)` gets called last ([As this article explains](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide#tasks_vs_microtasks))

**Comment by CreaTorAlexander** [comment]
Okay, I will update it 👍
