### ISSUE TITLE
Missing Semicolons in Two Interactive Examples From the Pseudo-Classes and Pseudo-Elements Page

### ISSUE THREAD

**Issue by MoradEnCours** [mdn/content#25274]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Pseudo-classes_and_pseudo-elements

### What specific section or headline is this issue about?

Generating content with ::before and ::after

### What information was incorrect, unhelpful, or incomplete?

The interactive editor shows a semicolon being added at the end of content property line in the example that uses an empty string, however the two previous examples did not appear to include a semicolon.

### What did you expect to see?

Semicolons being used in each example.

### Do you have any supporting links, references, or citations?

The example that shows a semicolon being used:
![image](https://user-images.githubusercontent.com/77248542/224554287-190c5301-20b5-4d36-8161-9a5cb8568737.png)

Previous examples that don't use a semicolon:
![image](https://user-images.githubusercontent.com/77248542/224554329-8063b64f-dda1-4402-92df-3957060ae5d2.png)
![image](https://user-images.githubusercontent.com/77248542/224554354-7ec7b47c-7d64-40f1-8aa5-58c5f781ae47.png)

### Do you have anything more you want to share?

I am still learning so there might be a reason why those examples do not use a semicolon but I considered mentioning this observation nevertheless in case it underlines an inconsistency, which would be easily resolvable.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors/pseudo-classes_and_pseudo-elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Pseudo-classes_and_pseudo-elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/pseudo-classes_and_pseudo-elements/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by yarusome** [comment]
The informative [railroad diagram](https://w3c.github.io/csswg-drafts/css-syntax-3/#declaration-list-diagram) in the *CSS Syntax Module* spec shows that the semicolon terminating the last declaration in a block is optional. However, as this page is for learning pseudo-classes and pseudo-elements, such syntactic distraction is unnecessary. I've opened a PR to fix it.
