### ISSUE TITLE
slice create deep copy or shallow copy?

### ISSUE THREAD

**Issue by divesham** [mdn/content#2529]
in this link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

let shallowCopy = fruits.slice() // this is how to make a copy
// ["Strawberry", "Mango"] 

name shoud be deepCopy 

explnation :- 
let arr1 = [-12, 12, 23, 1, 0, 3]
let arr2= arr1.slice();
console.log(arr1 === arr2) will print false because both are pointing to different reference

**Comment by CreaTorAlexander** [comment]
@divesham the name is correct. It is a shallow copy because  when it would contain other objects it will only copy the references and not the referenced objects key values.

**Comment by divesham** [comment]
let arr1 = [-12, 12, 23, 1, 0, 3]
let arr2= arr1.slice();
arr1 and arr2 pointing to same reference?
if yes then console.log(arr1 === arr2) should print false

**Comment by CreaTorAlexander** [comment]
No they don't point to the same reference

Slice returns a new array

> Return value
> A new array containing the extracted elements.

And this new array you are assigning to arr2. That is why consoloe log shows false.

**Comment by wbamberg** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice#description talks a bit about this but it might be worth expanding it and making it more explicit? (for example, it mentions shallow copy, and it describes the copy behavior, but it doesn't explicitly link the described behavior to the term "shallow copy".

Or, maybe better, having an example under https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice#examples that illustrates shallow copy?

**Comment by CreaTorAlexander** [comment]
I would say this site is about the method slice and about copying, shallow- and deep Copys are a topic in their own right. I would suggest doing a link to a website which explains shallor-deep copy.

**Comment by sideshowbarker** [comment]
The `shallowCopy` variable name in the example is appropriate, given that https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice explicitly says, *“The slice() method returns a shallow copy of a portion of an array”*

**Comment by gaurpiyush001** [comment]
> @divesham the name is correct. It is a shallow copy because when the array would contain other objects it will only copy the references and not the referenced objects itself.
> 
> Here is a good article
> https://medium.com/@manjuladube/understanding-deep-and-shallow-copy-in-javascript-13438bad941c

@CreaTorAlexander here now there two arrays which is shown by @divesham are not containing any nesting of object, so slice operator will create copy of new array at different reference hence when you change/alter something in new array it will not be reflected in previous array
So for an object which not nested(means it is containing object inside object), in that case slice will surely create a Deep Copy

**Comment by wbamberg** [comment]
A deep copy just is a copy that copies the contents of nested objects. A copy that doesn't do that is a shallow copy. So a copy that's "a deep copy except for nested objects" is a shallow copy.

In your example:

```js
arr1 = [1, 2, 'John', 'Peterson', 7]
arr2 = arr1.slice(1)
arr2[2] = 'Raddison'
console.log(arr1)
console.log(arr2)
```

...yes, changes made to `arr2` are not reflected in `arr1` because `arr2` is a copy, it;s not a reference to the same array. But it's a shallow copy.

**Comment by gaurpiyush001** [comment]
@wbamberg Okay Thank You very Much sir, now I understood the concept

**Comment by wbamberg** [comment]
@gaurpiyush001 you're welcome, and I'm glad I could help!

**Comment by ColtHands** [comment]
Wait, no, that's completely wrong, `.slice()` creates a deep copy with non primitive values shallow copied.

```js
let arr = [1,2,3]
let shallowCopy = arr // this is a shallow copy

let sliced = arr.slice() // this is a deep copy
```

Here if you change array's values _in place_ the original array values will not change, it only affects non primitive values.

So that the correct wording would be _`.slice() creates a **deep copy** of an array with non primitive values being shallow copied`

```js
let obj = { hello: 'world' }

let arr = [obj, obj] // [{ hello: 'world' },  { hello: 'world' }]

let sliced = arr.slice()

sliced[0] = 'deep'

console.log(arr) // [{ hello: 'world' },  { hello: 'world' }]
console.log(sliced) // ['deep',  { hello: 'world' }]

sliced[1].hello = 'shallow'

console.log(arr) // [{ hello: 'shallow' },  { hello: 'shallow' }]
console.log(sliced) // ['deep',  { hello: 'shallow' }]
```

**Comment by hamishwillee** [comment]
@ColtHands No. As @wbamberg says above "A deep copy just is a copy that copies the contents of nested objects. A copy that doesn't do that is a shallow copy. So a copy that's "a deep copy except for nested objects" is a shallow copy."
