### ISSUE TITLE
Wrong browser compatibility table on search/get

### ISSUE THREAD

**Issue by jscher2000** [mdn/content#25297]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/search/get

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

The embedded table is search/search rather than search/get

### What did you expect to see?

Table for search/get

### Do you have anything more you want to share?

It is kind of hard to report issues.

**Comment by jscher2000** [comment]
I don't know how you pull the data, but it's over here:

https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/search.json#L5

**Comment by wbamberg** [comment]
Thank you @jscher2000 ! The problem is that the `browser-compat` front matter key in the page is wrong: https://github.com/mdn/content/blob/9ea5c846813ed4285ddb4fb53f86f39d4be06754/files/en-us/mozilla/add-ons/webextensions/api/search/get/index.md?plain=1#L5.
