### ISSUE TITLE
http/1.1 400 bad request

### ISSUE THREAD

**Issue by kiptoooo** [mdn/content#25308]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

### What specific section or headline is this issue about?

extensions on chrome

### What information was incorrect, unhelpful, or incomplete?

my internet download manager is not downloading

### What did you expect to see?

download

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/400`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/400/index.md
* Last commit: https://github.com/mdn/content/commit/45d4569a5f7c2a4e614b8e950b9e56fa890b9fed
* Document last modified: 2023-03-03T04:42:31.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing problems in the MDN documentation.

It looks like you are seeking help with your code. Unfortunately, we don't have enough availability to help you.

If you have a problem with your code, I suggest you ask your question on a specialized website like [StackOverflow](https://stackoverflow.com/questions).


I'm closing this issue. If I've misunderstood you and you were reporting a problem in the documentation, feel free to reopen it while providing more information so we can understand the problem.

Thanks for your interest.
