### ISSUE TITLE
unexisting anchor in keydown_event

### ISSUE THREAD

**Issue by Graywolf9** [mdn/content#25319]
https://github.com/mdn/content/blob/de7e9d9937d2daab9a555e24fb498a09fdd7043d/files/en-us/web/api/element/keydown_event/index.md?plain=1#L74

```
[Keyboard locations](#keyboard_locations). 
```

is pointing to an unexisting anchor, that also are mentioning an unexisting section

**Comment by teoli2003** [comment]
Thank you for the report!

I would happily review a PR:
- The slug to use: /en-US/docs/Web/API/KeyboardEVent#keyboard_locations
- Three files have this problem: the reported `keydown_event`, but also `keyup_event` and `keypress_event`.

**Comment by teoli2003** [comment]
Note that the sentence should also be rewritten as the section is on another page.
