### ISSUE TITLE
Error: could not find syntax for this item with {{csssyntax}}

### ISSUE THREAD

**Issue by Graywolf9** [mdn/content#25321]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-float-edge

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-float-edge#formal_syntax

### What information was incorrect, unhelpful, or incomplete?

The macro is rendering an error

### What did you expect to see?

CSS Syntax

### Do you have anything more you want to share?

![imagen](https://user-images.githubusercontent.com/13079269/225092189-e5d2000b-e9e8-40ef-8457-5f1e06e5976d.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/-moz-float-edge`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-float-edge
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/-moz-float-edge/index.md
* Last commit: https://github.com/mdn/content/commit/c6dbc4ff96451887b908b46c8e70bcfec1c2c48c
* Document last modified: 2023-02-26T04:54:36.000Z

</details>

**Comment by teoli2003** [comment]
Non standard, and deprecated. I think we decided to hardcode or remove the section. In this case, I don't think the Formal Syntax section is needed. cc/ @wbamberg

**Comment by wbamberg** [comment]
> Non standard, and deprecated. I think we decided to hardcode or remove the section. In this case, I don't think the Formal Syntax section is needed. cc/ @wbamberg

Yes, agreed.
