### ISSUE TITLE
Issue with "Advanced text formatting": affirmations for positive thinking website no longer exists

### ISSUE THREAD

**Issue by eamc317** [mdn/content#2533]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting

The "Active Learning: Who Said That?" exercise uses a link to http://www.affirmationsforpositivethinking.com, which no longer exists and is for sale.  

(This link isn't vital for the exercise, just that it might link to something inappropriate later on.)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/advanced_text_formatting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.html
* Last commit: https://github.com/mdn/content/commit/201f6cfd272aa6d7d0bc8e9fa53cbf5fbe5abb87
* Document last modified: 2021-02-13T11:21:31.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can remove the link 👍

**Comment by Ryuno-Ki** [comment]
Do it!
