### ISSUE TITLE
Window.postMessage() missing options parameter

### ISSUE THREAD

**Issue by Meir017-msft** [mdn/content#25342]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

### What information was incorrect, unhelpful, or incomplete?

The documentation is incorrect and does not match the official documentation at https://html.spec.whatwg.org/multipage/web-messaging.html#posting-messages

![image](https://user-images.githubusercontent.com/121931056/225311091-08bd2a2a-8166-44f6-b822-6ad95c3e4766.png)

![image](https://user-images.githubusercontent.com/121931056/225311234-0a1f7b18-5abb-4d3c-8c6b-c2cb8f8b695b.png)

### What did you expect to see?

The correct documentation as seen in the https://html.spec.whatwg.org website

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/web-messaging.html#posting-messages

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/postmessage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/postmessage/index.md
* Last commit: https://github.com/mdn/content/commit/ef312020adf3378840034006be4d657fd0490977
* Document last modified: 2023-02-20T00:37:20.000Z

</details>

**Comment by advitiya7** [comment]
hey i want to contribute to this i just have to remove the original one and change it to the documentation given in the link? is that right?

**Comment by Josh-Cena** [comment]
To whoever is working on this: please check all `postMessage()` pages and make sure they are all updated!

**Comment by skyclouds2001** [comment]
- [ ] `Window.postMessage()`
- [x] `Worker.postMessage()` #29227 
- [x] `DedicatedWorkerGlobalScope.postMessage()` #29228 
- [ ] `Client.postMessage()` #29187 
- [x] `ServiceWorker.postMessage()`
- [ ] `MessagePort.postMessage()`
- [x] `BroadcastChannel.postMessage()`

And that's all

**Comment by Josh-Cena** [comment]
@skyclouds2001 Thanks a lot for working on this!
