### ISSUE TITLE
[CSS] Enable linear-easing-function for all channels

### ISSUE THREAD

**Issue by bsmth** [mdn/content#25357]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- [x] [`linear()`](https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function#linear_easing_function) easing function
- [ ] `layout.css.linear-easing-function.enabled` set to true by default for stable

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1819447

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

## Related issues and pull requests

- [x] BCD https://github.com/mdn/browser-compat-data/pull/19179
- [x] relnote https://github.com/mdn/content/pull/26315

**Comment by Elchi3** [comment]
BCD: https://github.com/mdn/browser-compat-data/pull/19179
