### ISSUE TITLE
[CSS] Implement CSS exponential functions

### ISSUE THREAD

**Issue by bsmth** [mdn/content#25353]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

>This bug is about implementing the remaining math functions that we don't support inside calc().
> Code for existing math functions is in [here](https://searchfox.org/mozilla-central/rev/9dfda5ccb0fc42d7666a54b1caf1af6525e49694/servo/components/style/values/specified/calc.rs#33), and it should be trivial to expand to the new functions.
> Functions that need implementing are:
>
>    Exponential functions (https://drafts.csswg.org/css-values-4/#exponent-funcs)
>    Sign related functions (https://drafts.csswg.org/css-values-4/#sign-funcs)

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1814469

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by dletorey** [comment]
Only the [Exponential functions](https://drafts.csswg.org/css-values-4/#exponent-funcs) are working the [Sign Functions](https://drafts.csswg.org/css-values-4/#sign-funcs) have been moved out to another ticket: [1814588](https://bugzilla.mozilla.org/show_bug.cgi?id=1814588)

**Comment by dletorey** [comment]
Associated Pull Requests

- [Content](https://github.com/mdn/content/pull/26187)
- [Browser Compat Data](https://github.com/mdn/browser-compat-data/pull/19366)
- [Firefox Release](https://github.com/mdn/content/pull/26203)
