### ISSUE TITLE
Issue with "Client-side form validation": (short summary here please)

### ISSUE THREAD

**Issue by pahlers** [mdn/content#2535]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

#### What information was incorrect, unhelpful, or incomplete?

The link [https://www.webfx.com/blog/web-design/best-practices-for-hints-and-validation-in-web-forms/](https://www.webfx.com/blog/web-design/best-practices-for-hints-and-validation-in-web-forms/) used in the article doesn't give information about form validation.

#### Specific section or headline?

> How can I help the user to correct invalid data?

#### What did you expect to see?

Links to articles about form validation.

#### Did you test this? If so, how?

Clink on the link in your article.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/form_validation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/form_validation/index.html
* Last commit: https://github.com/mdn/content/commit/ae7855b7d2e257273ab276daa9565de2786947b1
* Document last modified: 2021-01-27T07:44:46.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can work on it 👍  @Ryuno-Ki do you think we should remove the link or replace it by a good ressource?

**Comment by Ryuno-Ki** [comment]
If you can find a good resource, replace it. Otherwise remove (to avoid causing confusion).
Pay attention to pick a relevant source:
https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Editorial#relevance

**Comment by avivmu** [comment]
I found [this article from the same author](https://www.webfx.com/blog/web-design/10-tips-for-optimizing-web-form-submission-usability/), on the same website, so maybe replace instead of remove?

**Comment by CreaTorAlexander** [comment]
Yes, sounds good I will replace it.
