### ISSUE TITLE
 Uncaught ReferenceError: AJAXSubmit is not defined  (The little vanilla framework)

### ISSUE THREAD

**Issue by Franck78** [mdn/content#25365]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest

### What specific section or headline is this issue about?

The little vanilla framework

### What information was incorrect, unhelpful, or incomplete?

```
<form
      action="register.php"
      method="post"
      onsubmit="AJAXSubmit(this); return false;">
```

The _little vanilla framework_ proposes 4 examples. for using 'something'.

Problem is, **AJAXSubmit** is not a function anywhere.

Yet , I can upload a file to my little IOT thing running on ESP32.

My quick conclusion is that this is totally useless !?!?!?!?

### What did you expect to see?

not quite sure. Understanding the 'why' of such a complicated thing for something apparently working without this thing ?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/xmlhttprequest/using_xmlhttprequest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
* Last commit: https://github.com/mdn/content/commit/92435b5f26c680a2314d392ef06f479216f0b4dd
* Document last modified: 2023-02-27T14:15:34.000Z

</details>

**Comment by Franck78** [comment]
```
01:07:29,821 Uncaught ReferenceError: formeElement is not defined
    AJAXSubmit http://10.0.0.97/update:320
    onsubmit http://10.0.0.97/update:1
```

after renaming **XHRSubmit** to **AJAXSubmit**, new syntax error....

search for 'forme'Element

formElement


After fixing thie 'forme' another bug

 **Uncaught TypeError: req.sendAsBinary is not a function
    submitData http://10.0.0.97/update:202
    processStatus http://10.0.0.97/update:222
    pushSegment http://10.0.0.97/update:229
    SubmitRequest http://10.0.0.97/update:275
    AJAXSubmit http://10.0.0.97/update:323
    onsubmit http://10.0.0.97/update:1**


I think I'm reading/using crap here.

**Comment by teoli2003** [comment]
I've been tempted (for a long time now) to delete the whole section about this framework. @Franck78: what do you think?

**Comment by Franck78** [comment]
Hello Jean ves

I'm not qualified to answer this question. 

Apparently, this example is obsolete deprecated. It would be good for a beginner (me) to not waste time on it. So, yes delete, gray, add tag obsolete, dereference.

Thank you
Franck

**Comment by Franck78** [comment]
Again here, I read the code with obsoleted **sendAsBinary** call:

https://developer.mozilla.org/fr/docs/Web/API/File_API/Using_files_from_web_applications#manipuler_le_processus_de_t%C3%A9l%C3%A9chargement_pour_un_fichier



I doubt I will find what I want
```
<input type='file'>
```
simply linked to a progress
```
<label for="file">File progress:</label>
<progress id="file" max="100" value="70"> 70% </progress>
```

**Comment by teoli2003** [comment]
This second report is unrelated to the first one. It is a translation problem: can you open an issue [there](https://github.com/mdn/translated-content/issues)? The translation team will look at it.

We need to keep the issues separated else they'll never get fixed.

Thank you for the report!

**Comment by Franck78** [comment]
I don't understand ;)
The second link is another place where I red useless code (because using the deprecated call) and not being aware.
I don't see translation fix. 

The warning exists. But after the code example. My logic would be 'fix the code' or 'delete it'. 

Same spirit for IE5 IE6. Why waste time (of the reader) about that dead browser. 

Apparently, I'm the only one on earth wanting to associate a '**progress**' to a download  (XMLHttpRequest) !

If you want to replace useless little vanilla framework ;)

```
<script>
"use strict";
  function AJAXSubmit (myForm) {
    let xhr = new XMLHttpRequest();
    xhr.open("POST", "/binupdate");
    xhr.upload.addEventListener("progress", ({loaded, total}) =>{
      let progressBar = document.getElementById('fileprogress');
      progressBar.value = Math.floor((loaded / total) * 100);
    });

    let data = new FormData(myForm);
    xhr.send(data);
  }
</script>
   form enctype='multipart/form-data' onsubmit='AJAXSubmit(this); return false;'>
   <input type='file' name='update' accept='.bin'>
   <progress id='fileprogress' max='100' value='0'>0%</progress></h1>
   <button id='mysubmit'>Update</button>
  </form>
```

**Comment by teoli2003** [comment]
By the second report, I meant the one about `sendAsBinary` that is on a translated page and no more on the English page; it means that to fix this one, the translation has to be updated (cc/ @SphinxKnight )

I don't see a mention of IE5-6 on both pages (but I looked very quickly); we are removing them little by little anyway. Note that MDN is about 11000 pages in English, so maintaining it is a huge task. A few years ago we had mentions of Netscape and the Mosaic…

Finally, you may want to learn the Fetch API, which is a modern alternative to XHR.

**Comment by teoli2003** [comment]
If you see some, feel free to open an issue. We are removing these little by little. Thank you!

**Comment by Franck78** [comment]
Comme cette prothèse d'émulation ?

https://developer.mozilla.org/fr/docs/Web/API/Element/classList

 _prothèse d'émulation_  ah ah really sometimes, translation should not occur. Primary reason I avoid as much as possible translated doc.

**Comment by teoli2003** [comment]
This repository only deals with the English version of the MDN. For a problem in the French version, you need to open it in the mdn/translated-content repository. Thank you!

Note that the IE 5-6 mentions have been removed before 2021 in English (before we moved to GitHub).

I'm closing this issue as the original report is now fixed. Thank you for reporting it.
