### ISSUE TITLE
use of the word "proximity" in CSS cascade

### ISSUE THREAD

**Issue by OTaku10** [mdn/content#25369]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers

### What specific section or headline is this issue about?

Review of the cascade concept

### What information was incorrect, unhelpful, or incomplete?

The word "proximity" is used to refer the idea of "order of appearance".
In CSS Cascading and Inheritance Level 6, "proximity' is defined in a different way (for scope). 
Therefore, the use of this term in that article could be misleading.

### What did you expect to see?

"order of appearance", instead of "proximity" to indicate that the last declaration in document order wins.

### Do you have any supporting links, references, or citations?

- https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade

This one uses "order of appearance" to indicate the same concept.

### Do you have anything more you want to share?

I am not a native English speaker. It is possible that I am missing some context.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_layers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_layers/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by estelle** [comment]
thank. you're correct. PR submitted.
