### ISSUE TITLE
[WebAPI] Remove MutableFile/FileHandle support (IndexedDB)

### ISSUE THREAD

**Issue by bsmth** [mdn/content#25360]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

It appears this feature is removed due to low adoption / reducing maintenance burden.

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1500343

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by teoli2003** [comment]
Given that these interfaces are behind a flag for a year, have no bcd, and **create confusion** (as they got renamed several times, and some of the renamings came back to the original name if I remember well), I propose deleting the page without waiting for the two years.

**Comment by hamishwillee** [comment]
@teoli2003 I agree - these moved behind a pref on Firefox in 102 but were already getting very very low use in FF80 ish and already disabled in the others. I don't think having them will add any value.

Status:

- [ ] Release note
- [ ] Docs
- [ ] BCD - not required - already removed everywhere.
- [ ] dev-doc-complete
