### ISSUE TITLE
Issue with "How to structure a web form": (providing unlocalized instructions for date formatting)

### ISSUE THREAD

**Issue by AndySky21** [mdn/content#2537]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form

#### What information was incorrect, unhelpful, or incomplete?
In step 6, example code, you inserted a `<em>formatted as mm/dd/yyyy</em>` element. Apart from the fact that you might offer the same instruction with a `placeholder` or a `title` attribute, this is bad for 2 reasons:
- Card expiry date usually consists of just a month/year date
- `<input type="date">` is formatted according to user's locale, so for an Italian like me the order is dd/mm/yyyy. You are providing conflictual pieces of information. 
`placeholder` is HTML5 feature, so browser either support both it and `<input type="date">`, or none. If the order is relevant, or if you do not want to mention a polyfill at that point, or you want to keep such an instruction, it would be more convenient to express a date in separate `input` or `select` controls, in the preferred order.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/how_to_structure_a_web_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_structure_a_web_form/index.html
* Last commit: https://github.com/mdn/content/commit/ae7855b7d2e257273ab276daa9565de2786947b1
* Document last modified: 2021-01-27T07:44:46.000Z

</details>

**Comment by chrisdavidmills** [comment]
To whoever fixes this — follow @AndySky21 's pointers above on what should change here. This is important contextual information to get right.

**Comment by Biki-das** [comment]
I am ready to contribute this one abd mailed @AndySky21

**Comment by himanshugarg** [comment]
The page now has this which addresses both the format and placeholder issues. Is there more requested here:-

```html
<input type="text" id="expiration" required="true" placeholder="MM/YY" pattern="^(0[1-9]|1[0-2])\/([0-9]{2})$">
```

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/2537#issuecomment-991875158

**Comment by hamishwillee** [comment]
Thanks @himanshugarg - There might still be room for improvement, but the core points have been addressed. Closing - if there is more to be done then a new issue can be raised.
