### ISSUE TITLE
lose live example at fullscreenchange_event

### ISSUE THREAD

**Issue by daiwanxing** [mdn/content#25374]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenchange_event

### What information was incorrect, unhelpful, or incomplete?

I want to make sure, is there a live example missing from this article, if so, I'd be happy to submit a PR for it

### What did you expect to see?

add live example

**Comment by wbamberg** [comment]
Hi @daiwanxing ! You're most welcome to try!

One tricky thing might be that the spec (https://fullscreen.spec.whatwg.org/#security-and-privacy-considerations) requires a special `allowfullscreen` permission when in an iframe (which the live samples are).

You can request this permission by passing an [extra argument to the macro](https://github.com/mdn/yari/blob/8645872c6ea5781c655d28fd26266126e23bd5fc/kumascript/macros/EmbedLiveSample.ejs#L13). See, for example, https://github.com/mdn/content/blob/4c7603922dab3781bfcea3c971c717683d908c37/files/en-us/web/api/screen_capture_api/using_screen_capture/index.md?plain=1#L319.

**Comment by daiwanxing** [comment]
Thanks for your reply, I'll try it now
