### ISSUE TITLE
Parameter instead of argument?

### ISSUE THREAD

**Issue by TimoKinnunen** [mdn/content#25381]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash

### What specific section or headline is this issue about?

I would use 'parameters' instead of 'arguments' below. 

### What information was incorrect, unhelpful, or incomplete?

Add the following line below your checkGuess() function:

guessSubmit.addEventListener('click', checkGuess);
Copy to Clipboard
Here we are adding an event listener to the guessSubmit button. This is a method that takes two input values (called arguments) 

### What did you expect to see?

Parameters go into the function and transform to arguments inside the function. I mean this description "takes two input values (called arguments)" is wrong.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/a_first_splash`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/a_first_splash/index.md
* Last commit: https://github.com/mdn/content/commit/7ff26ceb6c6f1400d4297b22cb92e3786e35eac7
* Document last modified: 2023-02-26T18:57:36.000Z

</details>

**Comment by Josh-Cena** [comment]
"A method takes two arguments":

```js
doSomething(1, 2); // It takes arguments when you call it
```

"A method has two parameters":

```js
function doSomething(a, b) {}
// It has parameters when you define it
```

So the current text is correct. In general, MDN uses "arguments" and "parameters" interchangeably.
