### ISSUE TITLE
IDBObjectStore.openCursor incorrect direction docs

### ISSUE THREAD

**Issue by bigcupcoffee** [mdn/content#25385]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/openCursor#parameters

### What specific section or headline is this issue about?

IDBObjectStore.openCursor direction argument

### What information was incorrect, unhelpful, or incomplete?

`prev` option gets very confusing (The cursor is opened at the start(??) of the store) until you find out that it's just incorrectly documented specifically on this page.

### What did you expect to see?

Definitely not that `direction=prev` would open cursor at the start of the store.

### Do you have any supporting links, references, or citations?

Example of properly documented `openKeyCursor`: https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/openKeyCursor#parameters.
Properly documented `IDBCursor.direction`: https://developer.mozilla.org/en-US/docs/Web/API/IDBCursor/direction#value

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/idbobjectstore/opencursor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/openCursor
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/idbobjectstore/opencursor/index.md
* Last commit: https://github.com/mdn/content/commit/387d0d4d8690c0d2c9db1b85eae28ffea0f3ac1f
* Document last modified: 2023-02-20T04:32:55.000Z

</details>

**Comment by bsmth** [comment]
Thanks for opening the issue @bigcupcoffee - leaving a spec reference:

https://w3c.github.io/IndexedDB/#ref-for-dom-idbcursordirection-prev

>"[prev](https://w3c.github.io/IndexedDB/#dom-idbcursordirection-prev)"
>
>    This direction causes the cursor to be opened at the end of the [source](https://w3c.github.io/IndexedDB/#cursor-source). When iterated, the [cursor](https://w3c.github.io/IndexedDB/#cursor) should yield all records, including duplicates, in monotonically decreasing order of keys.
