### ISSUE TITLE
Issue with "Proxy Auto-Configuration (PAC) file": (short summary here please)

### ISSUE THREAD

**Issue by dh94** [mdn/content#2541]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file

#### What information was incorrect, unhelpful, or incomplete?

typo in api usage in examples

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file#example_2_2

#### What did you expect to see?

`localHostOrDoaminIs` to be `localHostOrDomainIs`

#### Did you test this? If so, how?

with my eyes :) 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/proxy_servers_and_tunneling/proxy_auto-configuration_pac_file`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/proxy_servers_and_tunneling/proxy_auto-configuration_pac_file/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by CreaTorAlexander** [comment]
@dh94 good eyes :) I will update it 👍

**Comment by sideshowbarker** [comment]
Closed by https://github.com/mdn/content/commit/0ef83fb47c9a12cad9dffe2dc5b54a08d8fcdc7a

**Comment by sideshowbarker** [comment]
(Re)closing this. (I can’t remember why I had reopened it…)
