### ISSUE TITLE
Chrome Developer Tools is able to Accesss Private Methods and properties

### ISSUE THREAD

**Issue by Christone007** [mdn/content#25411]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Classes_in_JavaScript

### What specific section or headline is this issue about?

Encapsulation

### What information was incorrect, unhelpful, or incomplete?

attempts to accesss private data properties and methods outside a class is expected to produce a syntax error. However, this is not the case when the examples were tried on Chrome Console.

### What did you expect to see?

```myExample.#somePrivateMethod()``` 
Expected a syntax error but got the method's output instead.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/classes_in_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Classes_in_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/classes_in_javascript/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by Josh-Cena** [comment]
Thanks, I think a note is worthwhile, but anything devtools does doesn't change the fundamental way of how the language works.
