### ISSUE TITLE
Optimizing window.onresize url fails.

### ISSUE THREAD

**Issue by azeek21** [mdn/content#25420]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event

### What specific section or headline is this issue about?

Window: resize event.

### What information was incorrect, unhelpful, or incomplete?

Url to optimizing window.resize failst with error below: 
```
Secure Connection Failed

An error occurred during a connection to web.archive.org. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG
* The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
* Please contact the website owners to inform them of this problem.
```
The url causing the issue : [URL](https://web.archive.org/web/20220714020647/https://bencentra.com/code/2015/02/27/optimizing-window-resize.html) 

### What did you expect to see?

[This page](https://bencentra.com/code/2015/02/27/optimizing-window-resize.html) was expected to show up I guess.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/resize_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/resize_event/index.md
* Last commit: https://github.com/mdn/content/commit/bb8221e061bba27dbdbe5a3698b6c69febf0bc70
* Document last modified: 2023-02-19T07:19:47.000Z

</details>

**Comment by Josh-Cena** [comment]
This seems like a transient connection issue. I can see the content.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/55398995/225991493-d90f1649-3b8c-495f-a528-b5efb48b344d.png">
