### ISSUE TITLE
Incorrect animation type link of `box-shadow`

### ISSUE THREAD

**Issue by yarusome** [mdn/content#25425]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow

### What specific section or headline is this issue about?

Formal definition

### What information was incorrect, unhelpful, or incomplete?

The "Animation type" row of the `box-shadow` CSS property has a link pointing to https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow#Interpolation, which doesn't exist.

### What did you expect to see?

The link point to https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow#interpolation (note the case), just like what the [`text-shadow`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow#formal_definition) property does.

### Do you have anything more you want to share?

~The link in the "Animation type" row of both `box-shadow` and `text-shadow` has a really lengthy `title` attribute, the content of which almost duplicates that in the "Interpolation" subsection of `box-shadow`.~ All the special animation types have such `title` attributes, so never mind.

**Comment by estelle** [comment]
Yay team!

**Comment by wbamberg** [comment]
Thanks for investigating, Estelle!

IMO we shouldn't close this until the new mdn/data is released and deployed.

**Comment by Josh-Cena** [comment]
Should be fixed now
