### ISSUE TITLE
Get rid of `reference` glossary page?

### ISSUE THREAD

**Issue by estelle** [mdn/content#25435]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Reference

### What specific section or headline is this issue about?

Is this page useful? 

### What information was incorrect, unhelpful, or incomplete?

There are no links to this page, and it's not useful.

https://developer.mozilla.org/en-US/docs/Glossary/Object_reference is also meh, but at least has a few pages linking to it. Maybe it can redirect to this, and this page can be improved?

As we use the term "reference" for our documentation, this page is even less than helpful

### What did you expect to see?

not this

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Reference
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/reference/index.md
* Last commit: https://github.com/mdn/content/commit/4bd65a01204446af2254bb8864bd22ad87bc86b0
* Document last modified: 2023-02-21T22:21:49.000Z

</details>

**Comment by hamishwillee** [comment]
@dawei-wang or @estelle Are you planning to improve the object reference topic? If not, perhaps create a separate issue for that now that this has been redirected?
