### ISSUE TITLE
Docs for <script type="importmap"> missing information about order

### ISSUE THREAD

**Issue by chenasraf** [mdn/content#25430]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap

### What specific section or headline is this issue about?

Exceptions

### What information was incorrect, unhelpful, or incomplete?

There is another type of error which can occur, when the importmap is loaded too late. 
On Chrome, I am getting this error:

```
An import map is added after module script load was triggered.
```

### What did you expect to see?

It is never mentioned in the docs where this should be placed. For example, should this be above any `type="module`"? What about `type="modulepreload"`? I expect to see limitations about when it is usable. In some cases, external tools might need modifying just to have the ability to add script tags above some auto-generated tags, which cause this feature not to work (at least on Chrome).

### Do you have any supporting links, references, or citations?

The [relevant HTML standard](https://html.spec.whatwg.org/multipage/webappapis.html#import-map) specifies:

> Import maps are currently disallowed once any module loading has started, or once a single import map is loaded. These restrictions might be lifted in future specification revisions.

As such I believe it should be noted in the MDN documentation as well.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/script/type/importmap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/script/type/importmap/index.md
* Last commit: https://github.com/mdn/content/commit/5c30b5e4e57d1a77ce56b88b3de1171d57562808
* Document last modified: 2023-03-09T08:24:08.000Z

</details>

**Comment by hamishwillee** [comment]
Hmmm. You're right, this is not as obvious in the docs as it should be.

Currently this is mentioned in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap#syntax

> Only the first import map in the document with an inline definition is processed; any additional import maps and external import maps are ignored. An [error event](https://developer.mozilla.org/en-US/docs/Web/API/Element/error_event) is fired at script elements with type="importmap" that are not processed (are ignored).

We also mention that the map should appear first here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#importing_modules_using_import_maps :

> There can only be one import map in the document, and because it is used to resolve which modules are loaded in both static and dynamic imports, it must be declared before any <script> elements that import modules.

> What about `modulepreload`

It's the same rule as other modules - once any modules are loading the importmap can't be loaded. If the modulepreload depends on something in the map then resolving the specifier will fail. https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-modulepreload-module-script-graph

I don't think we need to say anything specific about this case - it is implied as preloading is loading.


I've attempted a fix to make the restrictions far more obvious in https://github.com/mdn/content/pull/25469
