### ISSUE TITLE
Several CSS property pages don't show the "Formal definition" section normally

### ISSUE THREAD

**Issue by yarusome** [mdn/content#25441]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/page

### What specific section or headline is this issue about?

Formal definition

### What information was incorrect, unhelpful, or incomplete?

The pages of the following properties:

  1. [`font-palette`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-palette)
  2. [`font-variant-emoji`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-emoji)
  3. [`page`](https://developer.mozilla.org/en-US/docs/Web/CSS/page)
  4. [`view-transition-name`](https://developer.mozilla.org/en-US/docs/Web/CSS/view-transition-name)

have the "Formal definition" section showing:

>Value not found in DB!

The first two do lack data in [mdn/data](https://github.com/mdn/data/blob/main/css/properties.json), but their "Formal syntax" sections show normally. The even weirder thing is that the last two do have data on [Line 7658](https://github.com/mdn/data/blob/main/css/properties.json#L7658) and on [Line 9476](https://github.com/mdn/data/blob/main/css/properties.json#L9476), but their "Formal definition" sections still go wrong.

Tangentially related: https://github.com/mdn/yari/issues/8436

### What did you expect to see?

The "Formal definition" section show normally.

**Comment by yarusome** [comment]
Incidentally, the pages for [`container`](https://developer.mozilla.org/en-US/docs/Web/CSS/container), [`container-name`](https://developer.mozilla.org/en-US/docs/Web/CSS/container-name), [`container-type`](https://developer.mozilla.org/en-US/docs/Web/CSS/container-type) all lack the "Formal definition" and "Formal syntax" sections, and the corresponding data.

**Comment by teoli2003** [comment]
Formal definition comes out of mdn/data; formal syntax out of w3c/webref.

**Comment by wbamberg** [comment]
> The even weirder thing is that the last two do have data on [Line 7658](https://github.com/mdn/data/blob/main/css/properties.json#L7658) and on [Line 9476](https://github.com/mdn/data/blob/main/css/properties.json#L9476), but their "Formal definition" sections still go wrong.

I reckon that's because we haven't made a release of mdn/data since February 2nd: https://github.com/mdn/data/releases/tag/v2.0.31.

**Comment by teoli2003** [comment]
We should update mdn/data, then request a release of mdn/data. @yarusome can you create the missing entries there? I'll happily review them.
