### ISSUE TITLE
Error with the correct solution in abbreviation active learning

### ISSUE THREAD

**Issue by Engineers-Lab** [mdn/content#25455]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting

### What specific section or headline is this issue about?

Abbreviation active learning

### What information was incorrect, unhelpful, or incomplete?

the show solution button does not implement the correction abbreviation tag as described in the course.

### What did you expect to see?

when the button "show solution" is clicked it should show this 
<p>The <abbr title="National Aeronautics and Space Administration">NASA</abbr>, sure does some exciting work.</p>

and not this 

<p><abbr>NASA</abbr>, the National Aeronautics and Space Administration, sure does some exciting work.</p>

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/advanced_text_formatting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.md
* Last commit: https://github.com/mdn/content/commit/af0e71822122feda89495ab9215c131bbe34d65c
* Document last modified: 2023-03-12T06:56:30.000Z

</details>

**Comment by wbamberg** [comment]
It is correct, isn't it? The example asks us to mark up the abbreviation in:

```html
<p>NASA, the National Aeronautics and Space Administration, sure does some exciting work.</p>
```

...and the solution is:

```html
<p><abbr>NASA</abbr>, the National Aeronautics and Space Administration, sure does some exciting work.</p>
```

...we add the `<abbr>` markup around "NASA". It's not asking us to remove the expanded version.
