### ISSUE TITLE
Fix issue or issues please

### ISSUE THREAD

**Issue by Ballin4once** [mdn/content#25450]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/DocumentType

### What specific section or headline is this issue about?

https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html

### What information was incorrect, unhelpful, or incomplete?

****https://github.githubassets.com/assets/vendors-node_modules_primer_view-components_app_components_primer_primer_js-node_modules_gith-6a1af4-df3bc95b06d3.js

### What did you expect to see?

I did not expect to see anything

### Do you have any supporting links, references, or citations?

user-agent-reduction-origin-trial-and-dates.html

### Do you have anything more you want to share?

none

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/documenttype`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DocumentType
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/documenttype/index.md
* Last commit: https://github.com/mdn/content/commit/f45409ba2169ff05e433d21aa4ee0424079916b8
* Document last modified: 2023-02-20T07:35:10.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing problems in the MDN documentation.

It looks like you are seeking help with your code. Unfortunately, we don't have enough availability to help you.

If you have a problem with your code, I suggest you ask your question on a specialized website like [StackOverflow](https://stackoverflow.com/questions).


I'm closing this issue. If I've misunderstood you and you were reporting a problem in the documentation, feel free to reopen it while providing more information so we can understand the problem.

Thanks for your interest.
