### ISSUE TITLE
Wrong DNS acronym explaination

### ISSUE THREAD

**Issue by kermit-the-hermit** [mdn/content#25460]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works

### What specific section or headline is this issue about?

DNS explained

### What information was incorrect, unhelpful, or incomplete?

DSN is explained as Domain Name Servers

### What did you expect to see?

Domain Name System

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/how_the_web_works`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/how_the_web_works/index.md
* Last commit: https://github.com/mdn/content/commit/7ff26ceb6c6f1400d4297b22cb92e3786e35eac7
* Document last modified: 2023-02-26T18:57:36.000Z

</details>

**Comment by hamishwillee** [comment]
Tt's simplistic but but that's about the right level for the learn section. I have tidied this in a very basic way to address the terminology in https://github.com/mdn/content/pull/25466
