### ISSUE TITLE
Incorrect API call in documents

### ISSUE THREAD

**Issue by jzombie** [mdn/content#25464]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Build_a_phone_with_peerjs/Connect_peers/Get_microphone_permission

### What specific section or headline is this issue about?

Incorrect getUserMedia call.

### What information was incorrect, unhelpful, or incomplete?

The casing for "mediaDevices" is incorrect in the following screenshot.

![Screen Shot 2023-03-19 at 5 06 33 PM](https://user-images.githubusercontent.com/1139657/226215476-f4500887-985b-4e30-91ff-3dd1a9e58e21.png)

### What did you expect to see?

It should be `navigator.mediaDevices.getUserMedia`.

### Do you have any supporting links, references, or citations?

Yes, the following code on the page has the correct call:

`/* global Peer */

/**
 * Gets the local audio stream of the current caller
 * @param callbacks - an object to set the success/error behavior
 * @returns {void}
 */

function getLocalStream() {
  navigator.mediaDevices
    .getUserMedia({ video: false, audio: true })
    .then((stream) => {
      window.localStream = stream;
      window.localAudio.srcObject = stream;
      window.localAudio.autoplay = true;
    })
    .catch((err) => {
      console.error(`you got an error: ${err}`);
    });
}

getLocalStream();
`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webrtc_api/build_a_phone_with_peerjs/connect_peers/get_microphone_permission`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Build_a_phone_with_peerjs/Connect_peers/Get_microphone_permission
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webrtc_api/build_a_phone_with_peerjs/connect_peers/get_microphone_permission/index.md
* Last commit: https://github.com/mdn/content/commit/65cd9754ed95f116b641c68cad80f14ecf580b41
* Document last modified: 2023-01-21T12:18:52.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks! This will be fixed by https://github.com/mdn/content/pull/25465
