### ISSUE TITLE
interval variable is not in scope of cancel method

### ISSUE THREAD

**Issue by joopringelberg** [mdn/content#25480]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/ReadableStream

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The scope of the variable 'interval' is unclear. We cannot say whether the cancel function actually has access to it!
In your running example, the cancel function cannot.

### What did you expect to see?

let interval;
const stream = new ReadableStream({
  start(controller) {
  ...

### Do you have any supporting links, references, or citations?

.

### Do you have anything more you want to share?

.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/readablestream/readablestream`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/ReadableStream
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/readablestream/readablestream/index.md
* Last commit: https://github.com/mdn/content/commit/3b22c657f659c249cbe6e4fc6794370a5cb67a72
* Document last modified: 2023-03-01T11:11:40.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by #25480
