### ISSUE TITLE
Issue with "Promise.any()": (short summary here please)

### ISSUE THREAD

**Issue by unkn0wn3rr0r** [mdn/content#2549]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any

#### What information was incorrect, unhelpful, or incomplete?
When i click on the Run button it outputs incorrect data.

#### Specific section or headline?
 - JavaScript Demo: Promise.any()

#### What did you expect to see?
- // expected output: "quick"
- but got: Error: Promise.any is not a function

#### Did you test this? If so, how?
Refreshed my browser (i am using chrome), but it is still not working.
But it is working on Brave browser.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise/any`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/any/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this 👍

**Comment by avivmu** [comment]
Make sure your browser [supports this feature](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any#browser_compatibility)

**Comment by chrisdavidmills** [comment]
I've tried this on both Chrome and Firefox, and it works in both places. We've had a few reports of problems with this example recently, so it'd be good to get to the bottom of this problem.

**Comment by himanshugarg** [comment]
Didn't work for me on an older Ubuntu VM with FF 78 but [that's to be expected](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any#browser_compatibility). Worked fine on FF 95 and Chrome 96 both on Win 7. Is this issue still seen on supported browser versions?

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/2549#issuecomment-991887198.

**Comment by unkn0wn3rr0r** [comment]
Just tried it myself now and it seems to be working as expected.
