### ISSUE TITLE
"Your connection to this site isn't secure" when testing blob example

### ISSUE THREAD

**Issue by jzatarain** [mdn/content#25515]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Blob

### What specific section or headline is this issue about?

Creating a blob

### What information was incorrect, unhelpful, or incomplete?

When you run the example and click on "[Open the array URL](blob:https://yari-demos.prod.mdn.mozit.cloud/feb26af7-6e4e-40ab-87bd-9fcf33dd68a8)", you get a new tab with the "Your connection to this site isn't secure" message.

### What did you expect to see?

That the site is marked as secure.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/blob`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Blob
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/blob/index.md
* Last commit: https://github.com/mdn/content/commit/af0e71822122feda89495ab9215c131bbe34d65c
* Document last modified: 2023-03-12T06:56:30.000Z

</details>

**Comment by wbamberg** [comment]
Which browser are you running? This works for me in the current Firefox and Chrome:

![blob](https://user-images.githubusercontent.com/432915/228645315-83ee491f-1475-4c3f-b141-32563e1406c6.gif)

**Comment by jzatarain** [comment]
Edge
You didn't click on the information icon in your gif.

**Comment by wbamberg** [comment]
>  You didn't click on the information icon in your gif.

Ah, you didn't include that instruction. I think `blob` URLs are not HTTPS URLs. So I'm not sure that there is any error in the documentation here.

**Comment by Josh-Cena** [comment]
Chrome shows this icon for any connection that's not `https`. `blob` URLs are by definition unencrypted but it's okay since it should be pure data. I don't think we need to change anything either—there's nothing immediately concerning about an "insecure connection" when it's not HTTP. This is a general principle and doesn't have to be stated on this page.
