### ISSUE TITLE
SVG <image> element supports animated GIF

### ISSUE THREAD

**Issue by awehring** [mdn/content#25543]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image

### What specific section or headline is this issue about?

`<image>`

### What information was incorrect, unhelpful, or incomplete?

The second paragraph in this section says:

"The only image formats SVG software must support are [JPEG](https://developer.mozilla.org/en-US/docs/Glossary/JPEG), [PNG](https://developer.mozilla.org/en-US/docs/Glossary/PNG), and other SVG files. Animated [GIF](https://developer.mozilla.org/en-US/docs/Glossary/GIF) behavior is undefined."

### What did you expect to see?

With current Browsers animated GIF images are supported too (FireFox 111.0.1 as well as current Chrome,  Chromium, Safari, Android Samsung browser, Android Opera).

### Do you have anything more you want to share?

You can test it with with a SVG file that contains:

```
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
  viewBox="0 0 150 150" enable-background="new 0 0 100 100" xml:space="preserve">
  <image href="https://upload.wikimedia.org/wikipedia/commons/d/d7/Muybridge_horse_gallop_animated_2.gif" height="150" width="150" />
</svg>
```

The horse gallops when you open the SVG file in a browser. 
Tested with FireFox 111.0.1 as well as current Chrome,  Chromium, Safari, Android Samsung browser, Android Opera.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/element/image`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/image/index.md
* Last commit: https://github.com/mdn/content/commit/b4f998244660723175f8e06b5d77f68cfb1d1f1a
* Document last modified: 2023-03-06T23:38:10.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! This paragraph says "SVG software must support"; it says neither what they do support nor what web browsers support. It's true that you must not assume GIFs are supported everywhere (as some SVG mediums are not animatable at all). Traditionally, the SVG docs are very unbiased towards browsers and cares a lot about non-browser environments such as InkScape, so not sure if anything is to be done here. I will close this issue for now.
