### ISSUE TITLE
Forbid links to localhost with Markdownlint

### ISSUE THREAD

**Issue by teoli2003** [mdn/content#25542]
### Summary

This happens in https://github.com/mdn/content/pull/23675

A few links lead to `https://localhost:5042/...`.

These are always erroneous. We should:

- Raises a flaw
- Magically convert them to `/...` (like we do for `https://developer.mozilla.org/`)

### URL

None that I know.

### Reproduction steps

1. Create a Markdown link in a page like `[HTMLElement](https://localhost:5042/en-US/docs/Web/API/HTMLElement)`
2. Build the page

### Expected behavior

A flaw is reported.
The link is transformed into the equivalent of `[HTMLElement](/en-US/docs/Web/API/HTMLElement)`

### Actual behavior

No flaw reported
A broken link.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Android

### Anything else?

I think we can solve this issue by adding an extra alternative at: https://github.com/mdn/yari/blob/main/build/flaws/broken-links.ts#L232

Something similar to:

![Capture d’écran 2023-03-22 à 10 37 54](https://user-images.githubusercontent.com/1466293/226862222-9b68d8b1-7062-4924-b582-c972cc88a78d.png)

But for `https://localhost[:wxyz]?`

If this is the right way, I can create a PR.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by hamishwillee** [comment]
This is a good catch @teoli2003 !
