### ISSUE TITLE
Toggling  is not working as described 

### ISSUE THREAD

**Issue by jo777750** [mdn/content#25552]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/flex

### What specific section or headline is this issue about?

Examples- Setting flex: auto

### What information was incorrect, unhelpful, or incomplete?

The example code doesnt WORK (toggle) as described in the example, browser : MICROSOFT EDGE Version 111.0.1661.44 (Official build) (64-bit) or in jsfiddle

### What did you expect to see?

toggling as descibed in the mdn example

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/flex`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/flex
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/flex/index.md
* Last commit: https://github.com/mdn/content/commit/66944f622b6b51bc9c24bebbbea242138d910600
* Document last modified: 2023-02-21T05:45:53.000Z

</details>

**Comment by wbamberg** [comment]
It would be helpful for the example to:
- explain what is supposed to happen when you click
- show the hidden JS
