### ISSUE TITLE
Accessing WebAssembly memory using TypedArrays is incorrect on Big Endian systems

### ISSUE THREAD

**Issue by majaha** [mdn/content#25569]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Memory

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The examples access values from WebAssembly using `new Uint32Array`:
```javascript
  const summands = new Uint32Array(memory.buffer);
...
  const values = new Uint32Array(obj.instance.exports.memory.buffer);
```

However in the [Uint32Array docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array) it says:

>The Uint32Array typed array represents an array of 32-bit unsigned integers in the platform byte order. If control over byte order is needed, use [DataView](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView) instead.

(This is backed up by the ECMAScript spec: [Typed Arrays are integer-indexed exotic objects](https://tc39.es/ecma262/#sec-properties-of-typedarray-instances), [which have the [[Get]] internal method](https://tc39.es/ecma262/#sec-integer-indexed-exotic-objects-get-p-receiver), which calls [IntegerIndexedElementGet](https://tc39.es/ecma262/#sec-integerindexedelementget), which calls [GetValueFromBuffer](https://tc39.es/ecma262/#sec-getvaluefrombuffer), which uses the platforms endianness in steps 8 and 9.)

However the [WebAssembly docs](https://webassembly.github.io/spec/core/syntax/instructions.html?highlight=endian#memory-instructions) say:

> All values are read and written in _**little endian**_ byte order.

So it appears that the example will return incorrect results on big-endian systems.

### What did you expect to see?

An example using a `DataView.setInt32(byteOffset, value, littleEndian)` instead.

Exposing endian-ness like this has worrying implications for web page portability.
If this is a real portability pitfall, there should be warnings about it on the WebAssembly.memory and TypedArray pages.

### Do you have any supporting links, references, or citations?

I've already seen this pattern proliferating in several other places, such as:

- [wasm-bindgen](https://crates.io/crates/wasm-bindgen) (I think)
- Tutorials [1](https://ariya.io/2019/05/basics-of-memory-access-in-webassembly) [2](https://www.oreilly.com/library/view/webassembly-the-definitive/9781492089834/ch04.html) [3](https://rob-blackbourn.github.io/blog/webassembly/wasm/array/arrays/javascript/c/2020/06/07/wasm-arrays.html)
- Questions [1](https://groups.google.com/g/teavm/c/BlO4lkGNi40) [2](https://stackoverflow.com/questions/41875728/pass-a-javascript-array-as-argument-to-a-webassembly-function)
- [MDN: Using the WebAssembly Javascript API](https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API)
- [webassembly.org: Understanding the JS API](https://webassembly.org/getting-started/js-api/)

So the amount of code already using this buggy pattern is already probably quite large.

### Do you have anything more you want to share?

Perhaps javascript could use a `LittleEndianTypedArray` or similar. And maybe `new Uint32Array(wasmmemory.buffer)` should throw a type error, only allowing `Uint8Array` and `Int8Array`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/webassembly/javascript_interface/memory`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Memory
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/javascript_interface/memory/index.md
* Last commit: https://github.com/mdn/content/commit/fe898ddf33314ee129256c3862c5c53106eeec1f
* Document last modified: 2023-02-23T10:05:41.000Z

</details>

**Comment by Josh-Cena** [comment]
This needs edits on both JS and WASM pages, but I'm not sure who we should ask for advice...

**Comment by hamishwillee** [comment]
@MendyBerger Something you could advise on?

**Comment by MendyBerger** [comment]
This sounds like an interesting problem, I'll try to make a bit more research on this.

**Comment by MendyBerger** [comment]
@sunfishcode would you be willing to advise here?
I'm assuming that the `Uint32Array` constructor is converting the data into the platforms endianness, but I can't find any documentation to back that up.

**Comment by Josh-Cena** [comment]
Based on the outcome of https://es.discourse.group/t/is-accessing-webassembly-memory-using-typedarrays-incorrect-on-big-endian-systems/1696/4, we shouldn't be using anything other than 8-bit typed arrays and `DataView` to view memory. I will try to update the content.

**Comment by Josh-Cena** [comment]
@michaelficarra It is the docs' duty to point out potential portability issues, and the more we inform, the better—the ultimate weighing of impact will still be on the readers, but at least they know. This is the same reason why we discourage Annex B (like `substr()`, not more confusing things like non-strict block-scoped functions)—the reason given is that "this may not work everywhere" (although in practice the chance is precisely 0), not "because the committee regrets them". In addition, as mhofman said on Discourse, using typed arrays imposes additional assumptions on the underlying memory's data type and may not make sense. Thanks for pointing out though, I may not use words as strong as "the only safe option".

**Comment by Josh-Cena** [comment]
I've sent https://github.com/mdn/content/pull/33960
