### ISSUE TITLE
Keyboard shortcuts table suggest accesskeys aren't supported in Safari and Chrome on Mac, as well as in Edge on Windows

### ISSUE THREAD

**Issue by hannajones** [mdn/content#25608]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey

### What information was incorrect, unhelpful, or incomplete?

This table seems to be a bit inaccurate:

<img width="719" alt="Screen Shot 2023-03-24 at 2 25 57 PM" src="https://user-images.githubusercontent.com/15138046/227609357-c5bf43e8-0479-4ede-9363-9af1319a4a54.png">

* It makes it look like accesskeys are not supported in Safari and Chrome on mac, but `ctrl` + `opt` + `key` appears to work in both cases
* It also makes it look like Edge on Windows doesn't support accesskeys, but `alt` + `key` seems to work

### What did you expect to see?

It would be nice to have the table fully reflect what I'm experiencing testing accesskeys in different browsers.

### Do you have any supporting links, references, or citations?

Those keyboard shortcuts in the different browser/platform combinations can be tested via this simple demo: https://jsfiddle.net/hmjones/5tzxfvo0/5/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/accesskey`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/accesskey/index.md
* Last commit: https://github.com/mdn/content/commit/ba96f2f183353872db6d9242c7d2dffe2dbc0c35
* Document last modified: 2023-02-24T05:52:35.000Z

</details>

**Comment by advitiya7** [comment]
hey i want to contribute to this issue can you assign this to me?
thanks
