### ISSUE TITLE
> https://app.sender.net/complete-registration/address

### ISSUE THREAD

**Issue by Oladayo4150** [mdn/content#25638]
> https://app.sender.net/complete-registration/address

My location

_Originally posted by @Oladayo4150 in https://github.com/Oladayo4150/Becky/issues/5#issuecomment-1483900720_

**Comment by Oladayo4150** [comment]
Yes that was my location

**Comment by teoli2003** [comment]
Hi!

Please don't use this repository as a sandbox to test GitHub. It is a production repository, and each time numerous reviewers get notified.

To learn GitHub, you can create a new repository. You can delete it afterward.

Thank you!
