### ISSUE TITLE
Object.vallues deoes not return an array of strings as stated

### ISSUE THREAD

**Issue by domleonard** [mdn/content#25644]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

The [Description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values#description) for `Object.values()` states

> `Object.values()` returns an array whose elements are strings corresponding to the enumerable string-keyed property values found directly upon object. ...

This reads as if the returned array contains strings, which is  not generally true.

### What did you expect to see?

A description whose first sentence reads more like

> `Object.values()` returns an array whose elements are the values of the enumerable, own properties of its object argument. ...

### Do you have anything more you want to share?

```js
console.log( Object.values( { a:[], s: "string", n: 0, sym: Symbol(), u: undefined} ))
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/values`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/values/index.md
* Last commit: https://github.com/mdn/content/commit/fcd80ee4c8477b6f73553bfada841781cf74cf46
* Document last modified: 2023-02-21T01:57:14.000Z

</details>

**Comment by Josh-Cena** [comment]
Welcoming a PR that changes it to:

> `Object.values()` returns an array whose elements are values corresponding to
