### ISSUE TITLE
Comparable Attribute for Select Element

### ISSUE THREAD

**Issue by txwizard** [mdn/content#25640]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/size

### What information was incorrect, unhelpful, or incomplete?

The first sentence is "The size attribute defines the width of the [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) and the height of the [<**select**>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) element." (emphasis mine)

I read the remaining content in search of an explanation of how to set the horizontal size of a select element. Although the article ends with cross references to **maxlength** and **minlength**, there is no further explanation of how to set the horizontal size of a select element.

A single sentence that explains how to set the horizontal width of a **select** element would be a huge improvement in the usability of the page.

### What did you expect to see?

I expected to see at least a short phrase that said how to set the horizontal width of a **select** element.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/size`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/size
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/size/index.md
* Last commit: https://github.com/mdn/content/commit/ba96f2f183353872db6d9242c7d2dffe2dbc0c35
* Document last modified: 2023-02-24T05:52:35.000Z

</details>

**Comment by estelle** [comment]
The first paragraph includes `If CSS targets the element with properties impacting the width, CSS takes precedence`. The presentation layer is the purview of CSS. CSS can (and should) be used to style the width of the select, and all elements in an HTML document.
