### ISSUE TITLE
Issue with "accesskey": (Chrome for Linux keyboard combo incorrect)

### ISSUE THREAD

**Issue by thdoan** [mdn/content#2565]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey

#### What information was incorrect, unhelpful, or incomplete?
I think the accesskey table is incorrect. According to https://en.wikipedia.org/wiki/Access_key, Chrome for Linux accesskey combo is `Alt + key`, not `Shift + Alt + key`.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/global_attributes/accesskey`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/accesskey/index.html
* Last commit: https://github.com/mdn/content/commit/74a4a9283e1aa5c7f23e31c142010f7e539f736f
* Document last modified: 2021-02-10T17:57:43.000Z

</details>

**Comment by avivmu** [comment]
Well according to Wikipedia:

> Alt+⇧ Shift is required in some circumstances

So we should update the docs accordingly

**Comment by Ryuno-Ki** [comment]
https://github.com/mdn/content/blob/f4b133613b01bbf5e700d42317ece3fd6dceeac2/files/en-us/web/html/global_attributes/accesskey/index.html#L55

would be the line in need of an update.

**Comment by thdoan** [comment]
If Chrome for Linux works like Chrome for Windows, then reserved keyboard shortcuts would require `Shift+Alt`. From my testing these are currently four reserved keyboard shortcuts in Chrome for Windows, so `accesskey` assigned to these letters require `Shift+Alt`:

- `Alt+D` - Jump to the address bar
- `Alt+E` - Open the menu
- `Alt+F` - Open the menu
- `Alt+S` - ???

I don't have access to Chrome for Linux, so someone should verify what the reserved keyboard shortcuts by using this pen I created for testing:

https://codepen.io/thdoan/pen/ZEBXwjE

**Comment by Ryuno-Ki** [comment]
*fires up Chromium on Sabayon Linux

<kbd>Alt</kbd>+<kbd>D</kbd> jumps to address bar
<kbd>Alt</kbd>+<kbd>E</kbd> opens the menu
<kbd>Alt</kbd>+<kbd>F</kbd> opens the menu

I couldn't get <kbd>Alt</kbd>+<kbd>1</kbd> up to <kbd>9</kbd> to do anything (with or without <kbd>Shift</kbd>)
Plus, most special characters are placed awkward on a German keyboard layout (I could get some, like <kbd>.</kbd>, <kbd>,</kbd> or even <kbd>=</kbd> to trigger with <kbd>Alt</kbd>, though).

**Comment by thdoan** [comment]
Eeek.... no wonder MDN says "Because of these issues, it is generally advised not to use accesskeys for most general-purpose websites and web apps." ^_^
