### ISSUE TITLE
Non-`Window` properties and methods

### ISSUE THREAD

**Issue by alattalatta** [mdn/content#25652]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window

### What specific section or headline is this issue about?

"Instance properties implemented from elsewhere", "Instance methods implemented from elsewhere"

### What information was incorrect, unhelpful, or incomplete?

In #13727, `DOMMatrix` `DOMPoint`, etc. were removed from `Window` as they don't belong to `Window` itself, just exposed through it. In the same fashion, `caches` should be removed from the page.

### What did you expect to see?

It is not in `Window` page.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/index.md
* Last commit: https://github.com/mdn/content/commit/987d231a2e930dcffdaa97891322153f81b9268c
* Document last modified: 2023-03-22T20:52:16.000Z

</details>

**Comment by alattalatta** [comment]
On a second look, it's in [WindowOrWorkerGlobalScope](https://html.spec.whatwg.org/multipage/webappapis.html#windoworworkerglobalscope) but since mixin documentation is gone from MDN I guess it does belong to `Window`.

**Comment by teoli2003** [comment]
Yes. `Window` is a bit of a misleading name. It should be `WindowGlobalScope`, but nobody imagined several scopes back in the time of DOM1.
