### ISSUE TITLE
Django Tutorial part 9, Testing the page

### ISSUE THREAD

**Issue by fuad47** [mdn/content#25674]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms

### What specific section or headline is this issue about?

Django Tutorial part 9, Testing the page

### What information was incorrect, unhelpful, or incomplete?

> > We can add a link to our renew page next to each item using the template code below.

 `{% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}`
I think the term `bookinst.id` in this statement is confusing that's why at least should be changed to `copy.id `for beginners and given a clue that it may be used in **book_detail.html** , personally as a beginner, it made a big trouble to me until I find out that I should have used **copy.id** not **bookinst.id** in my **book_detail.html** template, which final working version became like this:

```
   {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
      <h5><a href="{% url 'renew-book-librarian' copy.id %}">Renew</a></h1>
    {% endfor %}
```

### What did you expect to see?

copy.id

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/django/forms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/forms/index.md
* Last commit: https://github.com/mdn/content/commit/91f718b7c3212d210deedbf2be12241b753dd82a
* Document last modified: 2023-03-25T07:30:48.000Z

</details>

**Comment by hamishwillee** [comment]
@fuad47 What I think you're fundamentally saying is that you think that the term "copy" is easier to understand than "book instance", where both terms represent particular instances or copies of an abstract book.

I agree that "copy" is a well understood term, and it would do no harm were it used. On the other hand, at this point in the tutorial we've been talking about books and bookinstances for 9 parts of the tutorial, so few people should find this confusing.

The main problem here is the cost of change. I have used BookInstance as a term throughout the tutorial and in the demo code and images. If I was going to change this I would change it consistently everywhere, in every instance and image. So it would have to be a pretty worrying issue for me to make all those fixes. I don't think it is.

So thank you for posting, but I am going to close this as "not going to fix".

**Comment by fuad47** [comment]
Why I particularly used the term **copy.id** because, it was previously used in tutorial part 6, on the other hand if changing all instances makes some trouble I suggest to add at least the for loop statement to make things more clearer for a beginner learner like this:  
```
{% for bookinst in book.bookinstance_set.all %}
      {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
```

**Comment by hamishwillee** [comment]
Reopening. I'm looking at other things now, but I will look at this again this week. Thanks.

**Comment by hamishwillee** [comment]
@fuad47 - you make a very good point. A particular implementation of the all book instance page created by a user may have a slightly different implementation, and certainly need not call it's loop variable `bookinst`. So copying that code verbatim might not work.

I have chosen to fix this in #25691 by providing an implementation of the challenge that uses `bookinst` and explaining better where the code goes - as you say, inside a for loop!

Thanks for your peristence.

**Comment by fuad47** [comment]
I am just trying to give back your teams' efforts for the development community as much as I can.

**Comment by hamishwillee** [comment]
Much appreciated!!!!
