### ISSUE TITLE
Update docs to use current method on beforeunload_event / onbeforeunload?

### ISSUE THREAD

**Issue by elvey** [mdn/content#25686]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

### What specific section or headline is this issue about?

quoted below. 

### What information was incorrect, unhelpful, or incomplete?

Page states: 
> The HTML specification states that authors should use the [Event.preventDefault()](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) method instead of using [Event.returnValue](https://developer.mozilla.org/en-US/docs/Web/API/Event/returnValue) to prompt the user. However, this is not yet supported by all browsers.

If I'm not mistaken, this is outdated; the linked page indicates all (current listed) browsers support Event.preventDefault.  Thus should this be changed?  And if so, then the example on the page should also be changed to use Event.preventDefault(), no?  (I'm not competent/confident enough to make the changes myself; just muddling through.)

### What did you expect to see?

Maybe swap in this sentence? :  

>This is now supported by all browsers.

And update the example code to _____.  (I don't know.)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/beforeunload_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/beforeunload_event/index.md
* Last commit: https://github.com/mdn/content/commit/73b724ad82b94d2a4c314924218367cea2740e97
* Document last modified: 2023-03-16T15:51:10.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

Yes, I think you are right.

> Maybe swap in this sentence? :
>
>> This is now supported by all browsers.

No need to say this. We could just delete "However, this is not yet supported by all browsers."

> And update the example code to _____. (I don't know.)

I guess just remove the `return` statement?

There are a lot of other updates we could make to that https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event#compatibility_notes section, but without getting into that, the above changes would be useful.

> I'm not competent/confident enough to make the changes myself

Please feel free to try if you want to: you should be able to expect helpful feedback :).

**Comment by elvey** [comment]
Thanks for the kind note and encouragement, but I feel I ought not submit a code change I haven't tested.  
I just noticed #23837 is related.  I'm also now thinking I'm over my head: While the linked page indicates all (current listed) browsers support preventDefault ( https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault ) the page this issue is connected to shows very limited support for "Activation using event.preventDefault()".

**Comment by wbamberg** [comment]
> Thanks for the kind note and encouragement, but I feel I ought not submit a code change I haven't tested. I just noticed #23837 is related. I'm also now thinking I'm over my head: While the linked page indicates all (current listed) browsers support preventDefault ( https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault ) the page this issue is connected to shows very limited support for "Activation using event.preventDefault()".

Oh yes, you're right: https://codepen.io/willbamberg/pen/vYzPWjj lets you switch between two ways to cancel the event - they both work for Firefox but only `returnValue` works for Chrome. So it seems like the compat is right here, and we should not update the doc.

Thanks anyway for filing!
