### ISSUE TITLE
`start_url` is doc'd as optional, but is actually an installability requirement for chromium-based browsers

### ISSUE THREAD

**Issue by captainbrosset** [mdn/content#25697]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Manifest/start_url

### What information was incorrect, unhelpful, or incomplete?

The page says that this manifest member is optional, and might even be ignored by user agents, but it is part of the required members for chromium-based browsers to consider a PWA installable.

### What did you expect to see?

* The table at the top should probably say something like "Mandatory: Yes for installed PWAs, No otherwise". Although, I don't know why would someone use a manifest other than to make their app installable anyway.
* The note about the member being purely advisory should be checked against actual browser implementations. Is that really the case?
* There should be a note about the fact that the member is a PWA installability requirement on chromium-based browsers. We should also check if safari on iOS requires this member for their add-to-home-screen feature, and whether Firefox on Android also requires it.

### Do you have any supporting links, references, or citations?

See this section: https://developer.mozilla.org/en-US/docs/web/progressive_web_apps/guides/making_pwas_installable#the_web_app_manifest

And this article: https://web.dev/install-criteria/#criteria

**Comment by wbamberg** [comment]
> The table at the top should probably say something like "Mandatory: Yes for installed PWAs, No otherwise". Although, I don't know why would someone use a manifest other than to make their app installable anyway.

I'm not sure what "Mandatory" means here tbh. [The spec](https://w3c.github.io/manifest/#web-application-manifest) has them all as optional:

> A [manifest](https://w3c.github.io/manifest/#dfn-manifest) can have any of the following members at its root, all of which are optional. The members can appear in any order.

It seems we mark only `name` and `icons` as mandatory. I wonder if the intention of "Mandatory" was always "Mandatory (for PWAs)"? In which case we should add something about `display` or `display_override` - and again, check the cross-browser story for these.

**Comment by captainbrosset** [comment]
It would be great to do some research into whether manifests are used outside of the PWA use case. My intuition is that, currently, there doesn't seem to be a reason to add a manifest to your site unless it's also installable as a PWA. But it's worth reseaching whether this is true or not. Maybe the theme_color member is used in some browsers to style the browser UI? Maybe the icon is used when pinning a site to a browser's sidebar (some browsers have those)? There could be other use cases.

If that's the case, I do believe we should make the docs clearer about this. This probably means adding an intro paragraph somewhere that says that, in theory, manifest members are all optional, and that browsers may choose to use any of them for various browser use cases. And then, go on to explain the PWA use case where some manifest members suddenly become a lot more important.

I don't know what that means for the Mandatory field on each member reference page though.
