### ISSUE TITLE
Issue with code demo: Code demo of snippets disappears in Firefos Developer Edition

### ISSUE THREAD

**Issue by jlamasfripp** [mdn/content#2570]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/gradient

#### What information was incorrect, unhelpful, or incomplete?
Code demos loads but disappears after load is complete when using the web with FireFox DEveloper Edition. It does not happens only in gradients page, but everywhere.

#### Specific section or headline?
All code demos

#### What did you expect to see?
The gradient demo (or the code demo, or the HTML demo, or js, etc...)

#### Did you test this? If so, how?
Yes, realoading (?)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/gradient`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/gradient
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/gradient/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by chrisdavidmills** [comment]
I just tried this page specifically in Firefox developer edition, and I can see the examples absolutely fine.

I did notice that the heights on the examples were too small and had vertical scroll bars, so I filed https://github.com/mdn/content/commit/95b02ba8004a86b259cec61905821663522cda14 to fix that.

Is that what you mean? Or can't you see the examples at all?

**Comment by Ryuno-Ki** [comment]
@jlamasfripp Would you be able to record a screencast showing it? Or take a picture once the code demo disappeared?
(Ideally with the Console of DevTools open)

**Comment by Rumyra** [comment]
Is this still an issue @jlamasfripp ?

**Comment by sideshowbarker** [comment]
Closing this for lack of response.
