### ISSUE TITLE
cssText is not blocked

### ISSUE THREAD

**Issue by a123b456c789** [mdn/content#25707]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src

### What specific section or headline is this issue about?

"As well as styles that are applied in JavaScript by setting the style attribute directly, or by setting cssText"

### What information was incorrect, unhelpful, or incomplete?

> As well as styles that are applied in JavaScript by setting the style attribute directly, or by setting [cssText](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/cssText):
> ```
> document.querySelector("div").setAttribute("style", "display:none;");
> document.querySelector("div").style.cssText = "display:none;";
> ```
> However, styles properties that are set directly on the element's [style](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style) property will not be blocked, allowing users to safely manipulate styles via JavaScript:
> 
> ```
> document.querySelector("div").style.display = "none";
> ```

The snippet `document.querySelector("div").style.cssText = "display:none;";` works in modern versions of Chrome (Version 111.0.5563.65) & Edge (Version 111.0.1661.54) - I did not test on other browsers. I believe this also contradicts the following snippet `document.querySelector("div").style.display = "none";` as both act on an element's `style` attribute

Example php code (I know I'm sorry)
```
<?php
header("Content-Security-Policy: default-src 'none'; script-src 'self'; style-src 'self'; ");
$script1 = "<script src='./test/test.js'></script>";
$style1 = '<link href="./test/style.css" rel="stylesheet" />';
echo $style1 . PHP_EOL;
echo "<button id='myButton1' class='badButton'>Button 1</button>" . PHP_EOL;
echo $script1 . PHP_EOL;

```

test/test.js
```
function wellDefinedClickHandler() {
  const myButton1 = document.getElementById('myButton1')
  document.querySelector("button").setAttribute("style", "display:none;");
  document.querySelector("button").style.cssText = 'display:none'; // y u work
}
const myButton1 = document.getElementById('myButton1');
myButton1.addEventListener("click", wellDefinedClickHandler);
```

test/style.css
```
.badButton {
    background: blue;
}
```

### What did you expect to see?

I expected `document.querySelector("div").style.cssText = "display:none;";` not to work, and I think it should be removed as it is not enforced by the CSP directive

### Do you have anything more you want to share?

![misleading - Copy](https://user-images.githubusercontent.com/129200570/228295176-df15d90d-49f4-47f7-83ce-d7958fde30bc.PNG)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/style-src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/style-src/index.md
* Last commit: https://github.com/mdn/content/commit/c44653e3f3502fbda86ba392ed8058e1e3a0a0de
* Document last modified: 2023-03-03T04:38:28.000Z

</details>

**Comment by Josh-Cena** [comment]
Duplicate of https://github.com/mdn/content/issues/11697. Nice reproduction, though!
