### ISSUE TITLE
Document String.prototype.isWellFormed and toWellFormed

### ISSUE THREAD

**Issue by Elchi3** [mdn/content#25737]
### MDN URL

https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String

### What specific section or headline is this issue about?

Methods

### What information was incorrect, unhelpful, or incomplete?

There are two new methods missing: String.prototype.isWellFormed and toWellFormed

### What did you expect to see?

 String.prototype.isWellFormed and toWellFormed per https://tc39.es/proposal-is-usv-string/#sec-string.prototype.towellformed

### Do you have any supporting links, references, or citations?

Shipped in Safari 16.4 and Chrome 111
I opened a BCD PR: https://github.com/mdn/browser-compat-data/pull/19276

### Do you have anything more you want to share?

More info https://github.com/tc39/proposal-is-usv-string

**Comment by Josh-Cena** [comment]
I would consider it fixed
