### ISSUE TITLE
 Provide sample code with fetch()

### ISSUE THREAD

**Issue by theking2** [mdn/content#25740]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects

### What specific section or headline is this issue about?

Show samples with the alternative `fetch()` syntax

### What information was incorrect, unhelpful, or incomplete?

All information as far as I've checked is correct.

### What did you expect to see?

What I'm missing is an example with `fetch()` and/or `await fetch()` syntax as well

### Do you have anything more you want to share?

I'm not sure if there is a policy to (still or also) use XHR sample code. But my guess for most applications we are moving towards a Promise- paradigm of coding. Please let me know if I'm wrong in that.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/formdata/using_formdata_objects`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/formdata/using_formdata_objects/index.md
* Last commit: https://github.com/mdn/content/commit/0444ab41bb372e63b3345f50e5b1e4e6a96c21d5
* Document last modified: 2023-02-24T12:04:34.000Z

</details>

**Comment by wbamberg** [comment]
Oh, this got fixed in https://github.com/mdn/content/pull/30295, as part of https://github.com/mdn/content/issues/30131. 🎉
