### ISSUE TITLE
Error with hadRecentInput property

### ISSUE THREAD

**Issue by MehseinJohan** [mdn/content#25741]
### MDN URL

https://github.com/mdn/content/blob/main/files/en-us/web/api/layoutshift/hadrecentinput/index.md?plain=1

### What specific section or headline is this issue about?

LayoutShift.hadRecentInput

### What information was incorrect, unhelpful, or incomplete?

Hello team,

When trying to integrate the function described in the page, I get rejected by the editor with : 
"Property 'hadRecentInput' does not exist on type 'PerformanceEntry'"

Could you please help ?

Thank you,

Regards,

Johan

### What did you expect to see?

No error.

### Do you have anything more you want to share?

I'm using VS Code along with Playwright framework (TypeScript, Node.js).

**Comment by Josh-Cena** [comment]
Hi, as indicated by the page, this is an experimental feature. Your error is reported by TypeScript, which does not ship typings for experimental APIs. You have to ignore the errors using `// @ts-expect-error`.
