### ISSUE TITLE
Linked github code doesn't match what's on the page

### ISSUE THREAD

**Issue by AlxD137** [mdn/content#25750]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting

### What specific section or headline is this issue about?

Representing Computer Code

### What information was incorrect, unhelpful, or incomplete?

The link to other-semantics.html (https://github.com/mdn/learning-area/blob/main/html/introduction-to-html/advanced-text-formatting/other-semantics.html) gives you code that is slightly different than the code it says it is on the page.

### What did you expect to see?

I expected the github link to display the same code that is in the snippet below the code, or vice versa. They should match.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/advanced_text_formatting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.md
* Last commit: https://github.com/mdn/content/commit/af0e71822122feda89495ab9215c131bbe34d65c
* Document last modified: 2023-03-12T06:56:30.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting this @AlxD137 - there's a fix incoming linked above 👍🏻

**Comment by bsmth** [comment]
I'll follow up shortly to mention it's an excerpt, not the entire file from the learning area 👍
