### ISSUE TITLE
Wrong word used

### ISSUE THREAD

**Issue by Yasmyn-Gomez** [mdn/content#25753]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model

### What specific section or headline is this issue about?

The box model and inline boxes

### What information was incorrect, unhelpful, or incomplete?

In the last sentence of the second paragraph it states "The horizontal padding, margins, and borders move other content away from the box.", but after playing with the numbers in the interactive editor, the horizontal properties (top or bottom) do not affect the spacing between the `<span>` and the rest of the content, as seen if writing `margin-top: 30px;`, for example.

### What did you expect to see?

After reading it over and over, because I couldn't see how the horizontal properties would change the display, I would have expected to see  "The vertical padding, margins, and borders move other content away from the box."

### Do you have any supporting links, references, or citations?

Not really, just the interactive editor. I am new to this :)

### Do you have anything more you want to share?

No. But thank you so much for all your work creating those pages. They are VERY useful :)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/the_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/the_box_model/index.md
* Last commit: https://github.com/mdn/content/commit/7ff26ceb6c6f1400d4297b22cb92e3786e35eac7
* Document last modified: 2023-02-26T18:57:36.000Z

</details>

**Comment by wbamberg** [comment]
> the horizontal properties (top or bottom) 

I think the page uses "horizontal" to mean left and right, which is the common usage. See also https://github.com/mdn/content/issues/21628.

Since we changed the reference pages for this, perhaps we should change this too? @teoli2003, you reviewed  https://github.com/mdn/content/pull/21641, what do you think?

**Comment by Yasmyn-Gomez** [comment]
I understand what you mean. Although I think it could be confusing to understand it from that perspective without any heads up in the page, since all along they kept using top&bottom and left&right even on the links to the properties they used.

**Comment by teoli2003** [comment]
We should not use vertical/horizontal. For years, people mix them: this proves that there is something unclear with them.
