### ISSUE TITLE
Please provide a working example for @property

### ISSUE THREAD

**Issue by jo777750** [mdn/content#25776]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@property

### What specific section or headline is this issue about?

@property

### What information was incorrect, unhelpful, or incomplete?

the url doesnt give a complete information to beginners as to how to use it..please provide a detailed working example with some html ,JS code,CSS

### What did you expect to see?

I wanna see a complete practical working example as to how @property is being used

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@property`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@property
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@property/index.md
* Last commit: https://github.com/mdn/content/commit/5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e
* Document last modified: 2023-02-21T06:49:52.000Z

</details>

**Comment by postmeback** [comment]
My 2cents:

```html
@property --primary-color {
  syntax: '<color>';
  initial-value: blue;
}

body {
  color: var(--primary-color);
}
```


Explanation:

In this example, we define a custom property named --primary-color using the @property rule. We specify the syntax as <color>, meaning it expects a valid color value. The initial value is set to blue.

Later, in the body selector, we use the var() function to reference the --primary-color variable. This allows us to apply the custom color value to the text color of the body element.

**Comment by postmeback** [comment]
If the above example looks fine. I can go ahead and create a PR.

**Comment by postmeback** [comment]
Can the above example be reviewed by the maintainers?

**Comment by jo777750** [comment]
I am not contact for this...
