### ISSUE TITLE
Example uses nonexistent IDBCursor#value property

### ISSUE THREAD

**Issue by wxuanwxwx** [mdn/content#25792]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/IDBCursor/delete

### What specific section or headline is this issue about?

Example error

### What information was incorrect, unhelpful, or incomplete?

Is there an IDBCursor. value attribute?

### What did you expect to see?

Should objectStore.get(cursor.key) be used

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/idbcursor/delete`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBCursor/delete
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/idbcursor/delete/index.md
* Last commit: https://github.com/mdn/content/commit/387d0d4d8690c0d2c9db1b85eae28ffea0f3ac1f
* Document last modified: 2023-02-20T04:32:55.000Z

</details>

**Comment by Josh-Cena** [comment]
Actually the doc is correct. If you read https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/openCursor, you see that the result is actually https://developer.mozilla.org/en-US/docs/Web/API/IDBCursorWithValue, which does have a `value`.
