### ISSUE TITLE
Issue with "MediaRecorder.requestData()": (short summary here please)

### ISSUE THREAD

**Issue by mannion** [mdn/content#2579]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/requestData

#### What information was incorrect, unhelpful, or incomplete?
If MediaRecorder.state is not "recording", raise a DOM InvalidState error and terminate these steps. If MediaRecorder.state is "recording", continue to the next step.

#### What did you expect to see?
If MediaRecorder.state is "inactive", raise a DOM InvalidState error and terminate these steps. If MediaRecorder.state is not "inactive", continue to the next step.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediarecorder/requestdata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/requestData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediarecorder/requestdata/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this :+1:
