### ISSUE TITLE
Missing browser compatibility table

### ISSUE THREAD

**Issue by josephbcasey** [mdn/content#25793]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Managing_screen_orientation

### What specific section or headline is this issue about?

Missing browser compatibility table

### What information was incorrect, unhelpful, or incomplete?

The blue 'notecard' div at the top of the page says: Experimental: This is an experimental technology
Check the Browser compatibility table carefully before using this in production.

However, there is no Browser compatibility table on the page. 

### What did you expect to see?

A browser compatibility table.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/css_object_model/managing_screen_orientation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Managing_screen_orientation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/css_object_model/managing_screen_orientation/index.md
* Last commit: https://github.com/mdn/content/commit/b280ea1234452ff553caa466bf532a66ba51db01
* Document last modified: 2023-02-19T06:34:57.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing!

This API is not experimental, so we should remove the `{{SeeCompatTable}}` macro call.
