### ISSUE TITLE
Odd API in polyfill

### ISSUE THREAD

**Issue by robmcm** [mdn/content#25804]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback

### What specific section or headline is this issue about?

See Also

### What information was incorrect, unhelpful, or incomplete?

The polyfill has a questionable implementation of `timeRemaining` which increases with time rather than decreasing as per the spec.

### What did you expect to see?

A polyfill that reflects the spec.

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/requestidlecallback/#example-2 

https://www.w3.org/TR/requestidlecallback/#the-idledeadline-interface 

> When the timeRemaining() method is invoked on an [IdleDeadline](https://www.w3.org/TR/requestidlecallback/#dom-idledeadline) object it MUST return the remaining duration before the deadline expires as a [DOMHighResTimeStamp](https://www.w3.org/TR/hr-time-3/#dom-domhighrestimestamp), which SHOULD be enough to allow measurement while preventing timing attack - see "Privacy and Security" section of [[HR-TIME](https://www.w3.org/TR/requestidlecallback/#bib-hr-time)]. This value is calculated by performing the following steps:

### Do you have anything more you want to share?

I have raised an issue on the polyfill to ask why it was implemented like this.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/requestidlecallback`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/requestidlecallback/index.md
* Last commit: https://github.com/mdn/content/commit/bb8221e061bba27dbdbe5a3698b6c69febf0bc70
* Document last modified: 2023-02-19T07:19:47.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing, @robmcm !

Link to the upstream issue: https://github.com/behnammodi/polyfill/issues/22.

**Comment by Josh-Cena** [comment]
I propose we should remove the polyfill link because the repo doesn't seem widely used.

@behnammodi Do you have more information here?

**Comment by behnammodi** [comment]
I think I made a mistake and `timeRemaining` implementation should be something like:
 
 https://github.com/behnammodi/polyfill/blob/e27dd5a590ff8c2b9f4b34cf307e76efdc239e14/window.polyfill.js#L18

```js
...
  timeRemaining: function () {
    return Math.max(0, timeout - (performance.now() - start));
  },
...
```
