### ISSUE TITLE
/en-US/…/List_of_default_Accept_values source links not working

### ISSUE THREAD

**Issue by Fanolian** [mdn/content#2580]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values

Many source links in comment columns no longer work. The links do not link to specific code revisions and thus the content may have been moved to other lines.

Example:
In section **Default values**, comment for Firefox says:

> In Firefox 65 and earlier, this value can be modified using the network.http.accept.default parameter. (source)

and the source links to https://hg.mozilla.org/mozilla-central/file/tip/modules/libpref/init/all.js#l1750 which is no longer relevant.

As for linking Firefox content, [Searchfox](https://searchfox.org/) may be a better option than https://hg.mozilla.org/?

Thanks.

**Comment by hamishwillee** [comment]
@chrisdavidmills This is a valid criticism. I suggest that:-
- By default we use searchfox for FF links. If nothing hits, then the link is deleted.
- Any broken link to old code on other browsers just gets deleted.

My reasoning is that actually source links are of limited use to the main audience, and they are worse than useless if broken. 

OK?

**Comment by chrisdavidmills** [comment]
@hamishwillee yes, WFM!
