### ISSUE TITLE
Explain what stable sorting means

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/content#2583]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In https://github.com/mdn/browser-compat-data/pull/4559, an entry for stable sorting was added.  We should add a section explaining what that means, as well as code examples.

**Comment by Ryuno-Ki** [comment]
@vinyldarkscratch It took quite a while, but this issue finally got resolved today. Thank you for bringing it up.
