### ISSUE TITLE
Rationale for second parameter in MutationObserver callback?

### ISSUE THREAD

**Issue by danbae56** [mdn/content#25839]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/MutationObserver

### What specific section or headline is this issue about?

#parameters

### What information was incorrect, unhelpful, or incomplete?

From the documentation shown on this and related pages, it is unclear why the callback function has to take the `MutationObserver` itself as a second parameter. To me it looks strange that the MutationObserver should have to reference itself in its callback, especially if we write the observer definition as follows:

`const obs = new MutationObserver((list, obs) => /*do something*/);`

Moreover, in the example given on the page, the `observer` parameter can be omitted from the callback without any effect on the result.

However, I am certain that there are instances when this parameter is necessary and useful – but I would have liked to see this demonstrated or explained. The examples I can come up with at least do fine with only the first parameter.

### What did you expect to see?

An explanation and/or an example of an instance when the second parameter is useful in the callback.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mutationobserver/mutationobserver`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/MutationObserver
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mutationobserver/mutationobserver/index.md
* Last commit: https://github.com/mdn/content/commit/2ba2c0efbdf0c34b1da02203e4e84b571c883629
* Document last modified: 2023-02-28T14:00:22.000Z

</details>

**Comment by Josh-Cena** [comment]
The second parameter is useful for multiple cases where the object is not readily available as a variable, for example:

```js
registerObserver(new MutationObserver(() => {
  // How do you access the observer?
}));

function getObserver() {
  return new MutationObserver(() => {
    // How do you access the observer?
  });
}
```

It's usually useful for disconnecting within the callback.
