### ISSUE TITLE
Spread syntax is not an operator

### ISSUE THREAD

**Issue by guest271314** [mdn/content#25838]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

### What specific section or headline is this issue about?

Reference/Operators/Spread_syntax

### What information was incorrect, unhelpful, or incomplete?

Spread syntax is not an operator.

### What did you expect to see?

Spread syntax is in the "Operators" directory on MDN.

### Do you have any supporting links, references, or citations?

- [What is SpreadElement in ECMAScript documentation? Is it the same as Spread syntax at MDN?](https://stackoverflow.com/questions/37151966/what-is-spreadelement-in-ecmascript-documentation-is-it-the-same-as-spread-synt)
- [Is it spread "syntax" or the spread "operator"?](https://stackoverflow.com/questions/44934828/is-it-spread-syntax-or-the-spread-operator)
I did the research and located the origin of the usage of "spread operator"

- [[AskJS] Who first used the term "spread operator" re spread syntax ...?](https://www.reddit.com/r/javascript/comments/xhhqsz/askjs_who_first_used_the_term_spread_operator_re/)

Specifically, https://www.reddit.com/r/javascript/comments/xhhqsz/comment/iozf2ij/

> So far the earliest usage I have located is https://www.oneminutecoder.com/
> 
> > Jan 28, 2009 — An Example Of JavaScript ...spread operator ...
> 
> Following the TC39 proposal we still find that language https://github.com/tc39/proposal-object-rest-spread/blob/7d6d8a5de6ca75c2370cdef764b935fc864e52de/Rest.md.
> 
> This dates to 2014 https://github.com/tc39/proposal-object-rest-spread.

Spread syntax articlae needs to be moved to a directory other than "Operators" to avoid perpetuating confusion from MDN as the source, e.g, [What are the three periods......?](https://www.reddit.com/r/learnjavascript/comments/128rxcy/what_are_the_three_periods/).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/spread_syntax`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/spread_syntax/index.md
* Last commit: https://github.com/mdn/content/commit/0f3738f6b1ed1aa69395ff181207186e1ad9f4d8
* Document last modified: 2023-02-21T00:33:34.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! This section is called "expressions and operators" in both the sidebar and the landing page. Its slug is "Operators" for historical reasons and changing it at this point is unnecessary. There are other things that are expressions but not operators yet are in this section, such as `null` and `import.meta`. The fact that we repeatedly clarify that spread syntax is not an operator is sufficient.

**Comment by guest271314** [comment]
> Hi! This section is called "expressions and operators" in both the sidebar and the landing page. Its slug is "Operators" for historical reasons and changing it at this point is unnecessary. There are other things that are expressions but not operators yet are in this section, such as `null` and `import.meta`. The fact that we repeatedly clarify that spread syntax is not an operator is sufficient.
> 
> Furthermore, it's not very problematic to think of it as a unary operator. It's just that spread can only be contextually used within an object/array literal/function call.

The information is wrong. We are not dealing with "think of it as", we are dealing with technical facts. The fact is developers in the field are quoting MDN and perpetuating the incorrect notion that spread syntax is an "operator". Changing the path is necessary. Then you need to change the `null` and `import.meta` locations, too. That is the point of having a section at the bottom of all MDN pages to report problems with the content in the page - not to shrug the clear error off as being too much work to change for "historical reasons".

**Comment by guest271314** [comment]
@Josh-Cena What other content in MDN Web site do you _know_ is not true and correct; is wrong; yet you refuse to modify for "historical reasons"? Surely you must know that means MDN is _not_ a reliable source for information, and all MDN pages are suspect.

**Comment by Josh-Cena** [comment]
@guest271314 The slug is not a source of information—it's an opaque, abstract representation of our information architecture. If you find problems with the actual content (prose, sidebar, browser compatibility, etc.) feel free to point them out, but we will not unnecessarily change the slugs. This section is always called "expressions and operators".

**Comment by guest271314** [comment]
> @guest271314 The slug is not a source of information—it's an opaque, abstract representation of our information architecture. If you find problems with the actual content (prose, sidebar, browser compatibility, etc.) feel free to point them out, but we will not unnecessarily change the slugs. This section is always called "expressions and operators".
> 
> I'm curious what others think. @mdn/yari-content-javascript I've thought about changing the slug segment from "Operators" to "Expressions", but the number of redirects it adds and possible SEO problems are daunting.

Everything on MDN is a source of information. In a domain full of spurious claims, extraneous hype, and deliberate lies, here we are 25 years into Mozilla and "possible SEO problems are daunting" is a concern expressed by a Member of the personnel tasked with managing content on MDN?

Who cares about "SEO"?

What matters is true and correct information. At least to me. Perhaps that is why I have banned by multiple organizations. True and correct information is not as important to them as [Popularity](https://brendaneich.com/2008/04/popularity/).

Just adjust your robots.txt file, roll onto Google Developer Console, update there, etc. Done. Now you are publishing accurate information.

I vet any and all spurious claims published by anybody within the domains I am engaged in constructive activity. 

Good enough ain't good enough. Ask a roofer.

```
var raw_mdn_url = 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax';
var mdn_url = new URL(raw_mdn_url);
var expressions_is_in_url = mdn_url_parts.find((part) => /expressions/i.test(part));
var operators_is_in_url = mdn_url_parts.find((part) => /operators/i.test(part));
console.assert(expressions_is_in_url, {expressions_is_in_url});
console.assert(operators_is_in_url, {operators_is_in_url})
```

**Comment by guest271314** [comment]
You'll need this for the above code to demonstrate what I am conveying

```
var mdn_url_parts = mdn_url.pathname.split('/').filter(Boolean);
```

Be the hallmark. Folks are linking to MDN in the wild all of the time. You are already well-established as quasi-canonical source for developer information. Be impeccable with your publications. That's what this whole business about asking if there is any content that is wrong on the page is about. Yes, the URL is wrong. It doesn't contain the term "Expressions", which is a different technical term from "Operators". 

The only action I can take here is performing my due diligence. That's what I've done here. 

Personally, I don't settle.
