### ISSUE TITLE
imagesrcset and imagesizes on link element

### ISSUE THREAD

**Issue by schalkneethling** [mdn/content#2586]
## URL(s)
No page currently exists(I believe)

## Request type
- [x] New documentation

## Details

While reading the HTML spec, as one does :), I stumbled across two attributes I have not heard of before related to the `link` element. The attributes are `imagesrcset` and `imagesizes`.

At first, I thought it related to `rel="icon"` somehow but, after some experimentation, it seemed unlikely. I opened an issue on whatwg/html and received clarity on the situations.

https://github.com/whatwg/html/issues/5604

It seems that there is no content related to these attributes on MDN. According to Domenic, Chrome has supported these for ~15 months now. There is currently a PR open to clarify its use https://github.com/whatwg/html/pull/5606

Seems like we might want to add some docs on this to MDN?

**Comment by estelle** [comment]
The [`<link>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) page contains information about `imagesrcset` and `imagesizes` in the attribute list and BCD:

> [imagesrcset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-imagesrcset)
For rel="preload" and as="image" only, the imagesrcset attribute is [a sourceset attribute](https://html.spec.whatwg.org/multipage/images.html#srcset-attribute) that indicates to preload the appropriate resource used by an img element with corresponding values for its srcset and sizes attributes.

> [imagesizes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-imagesizes)
For rel="preload" and as="image" only, the imagesizes attribute is [a sizes attribute](https://html.spec.whatwg.org/multipage/images.html#sizes-attribute) that indicates to preload the appropriate resource used by an img element with corresponding values for its srcset and sizes attributes.
