### ISSUE TITLE
PR reviews in Q2 2023

### ISSUE THREAD

**Issue by teoli2003** [mdn/content#25868]
This issue aims at giving visibility to the much-needed and time-consuming activity of reviewing the numerous PRs created daily.

### How does it work?

This issue is (or will be soon) displayed in the [MDN roadmap](https://github.com/orgs/mdn/projects/26/views/7). That way, people consulting it know that PR reviewing is a significant task that must be done.

### Who gets assigned to it?

If you regularly review PRs, you get added as an assignee of this issue, or listed as such in the issue. This will show that you participate in this effort. You are not committing to perform  X, or Y reviews each day or week, and you don't need to link PRs to this issue. Nothing else changes.

The number of assignees is limited, so we'll use this field for the most active reviewers. Others will be recognized inside comments here.

### What does it change, then?

Practically, nothing changes when reviewing PRs. The only difference is the added visibility for this task.
Each Quarter we will create such an issue to display actual people doing the reviews during a Quarter.

### How many reviews do I need to perform to be assigned here?

There are no precise rules: regular reviewers (maintainers) get assigned at the creation of this issue. We will add more as the Quarter goes by, as maintainers want to recognize the valuable work of others.

**This is an experiment. We will evaluate its outcome at the end of the Quarter**

**Comment by teoli2003** [comment]
Thanks all for the PRs review this Quarter! I'm closing this as Q2 is over!

**Comment by Josh-Cena** [comment]
TBH I don't find this issue quite useful—maintainers review whatever PR they have the time and confidence reviewing anyway.

**Comment by hamishwillee** [comment]
@Josh-Cena This is just a way of providing recognition of  the efforts of those who do reviews. I'm not sure what is then done with this information - or if this is just something we glory on at the end of each month. Either way, as long as it adds no admin burden to me "no skin off my nose".
