### ISSUE TITLE
FileSystemDirectoryHandle.values() return value is incorrect

### ISSUE THREAD

**Issue by basedest** [mdn/content#25876]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle/values

### What specific section or headline is this issue about?

Return Value

### What information was incorrect, unhelpful, or incomplete?

FileSystemDirectoryHandle.values() returns FileSystemDirectoryIterator, not an Array.

### What did you expect to see?

"FileSystemDirectoryIterator"

### Do you have any supporting links, references, or citations?

https://fs.spec.whatwg.org/#api-filesystemdirectoryhandle-asynciterable

### Do you have anything more you want to share?

![image](https://user-images.githubusercontent.com/77895649/229521103-9133c0d3-fb33-43c3-a3f6-d35afa2db876.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/filesystemdirectoryhandle/values`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle/values
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/filesystemdirectoryhandle/values/index.md
* Last commit: https://github.com/mdn/content/commit/c88a329069328522a5c20c054f9dbced9967dbd4
* Document last modified: 2023-02-20T08:12:58.000Z

</details>

**Comment by hound77** [comment]
@basedest I want to work on this issue.

**Comment by teoli2003** [comment]
@hound77 The bug is yours. You don't need to ask for permission to work on an issue. Just create a PR. (I have assigned it to you but no need for it)

**Comment by Josh-Cena** [comment]
The `entries()`, `keys()`, and `values()` docs are all terribly questionable. Please make sure they are all updated, as well as the description on the landing page.

I am unassigning @hound77 to unblock others from working on this.
