### ISSUE TITLE
Don't recommend navigator.doNotTrack (which is also deprecated)?

### ISSUE THREAD

**Issue by pdehaan** [mdn/content#25884]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT#reading_do_not_track_status_from_javascript

### What information was incorrect, unhelpful, or incomplete?

The example says:

> ### [Reading Do Not Track status from JavaScript](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT#reading_do_not_track_status_from_javascript)
> The user's DNT preference can also be read from JavaScript using the [`Navigator.doNotTrack`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack) property:
> ```js
> navigator.doNotTrack; // "0", "1" or null
> ```

But if I click through to https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack, it also says:

> _**Deprecated:** This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack#browser_compatibility) at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time._

### What did you expect to see?

Maybe delete the mention of `doNotTrack` if it isn't a valid alternative.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/dnt`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/dnt/index.md
* Last commit: https://github.com/mdn/content/commit/83d678b2a3fd3eabf88ad22f8924a0ccad17eb00
* Document last modified: 2023-03-20T21:38:08.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, the entire do-not-track feature set is deprecated, including the JS accessor and its HTTP header. It's fine to reference one deprecate property from another.
