### ISSUE TITLE
PaintWorkletGlobalScope nav link broken on CSS Painting API page

### ISSUE THREAD

**Issue by birdsarah** [mdn/content#25880]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSS_Painting_API

### What specific section or headline is this issue about?

Left nav

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/1796208/229557866-f75b3ef6-f19b-4a0d-a311-a82a0a5922d4.png)

When clicking on [PaintWorkletGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/PaintWorkletGlobalScope)

get a 404 

![image](https://user-images.githubusercontent.com/1796208/229558035-1df8dd30-0cbe-4e12-a3e7-2daca5c4d3e6.png)

### What did you expect to see?

I'm not sure if I look at  link like https://developer.mozilla.org/en-US/docs/Web/API/PaintWorklet/devicePixelRatio

It say it's PaintWorkletGlobalScope.devicePixelRatio but it's listed as an instance property of PaintWorklet.

**Comment by teoli2003** [comment]
Thank you. Yes, this page is among the missing ones on MDN. We would like to see them documented, although we currently don't have the bandwidth to create them ourselves.

**Comment by wbamberg** [comment]
Also though, these pages are wrong, as the report says:

> I'm not sure if I look at link like https://developer.mozilla.org/en-US/docs/Web/API/PaintWorklet/devicePixelRatio
>
> It say it's PaintWorkletGlobalScope.devicePixelRatio but it's listed as an instance property of PaintWorklet.

There doesn't seem to be any such interface as `PaintWorklet`: https://drafts.css-houdini.org/css-paint-api/#paint-worklet.

**Comment by teoli2003** [comment]
OMG! You are right! What a mess.

I cleaned it a bit in #25895 and in mdn/browser-compat-data#19313: we don't want to have wrong interfaces/member names. There would be a lot more to do, but this is not for now.
