### ISSUE TITLE
Issue with "WebSocket.send()": Exceptions thrown listed is incorrect

### ISSUE THREAD

**Issue by mofojed** [mdn/content#2589]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/send

#### What information was incorrect, unhelpful, or incomplete?
In the Exceptions Thrown section, it says the `INVALID_STATE_ERR` exception is thrown when `send` is called while the connection is not `OPEN`. That is incorrect, as an exception is only called in the `CONNECTING` state; if `CLOSING` or `CLOSED`, send just discards the data. Refer to RFC: https://html.spec.whatwg.org/multipage/web-sockets.html#dom-websocket-send
Or run the following snippet in a browser console: 
```
var ws = new WebSocket("wss://invalid-ws-url.com");
setTimeout(() => ws.send("Hello"), 5000);
```

#### Specific section or headline?
Exceptions thrown->INVALID_STATE_ERR

#### What did you expect to see?
Should say it only throws in the state is `CONNECTING`. Should probably mention in the description of the method that it doesn't do anything if the connection is already closed, and the onus is on the user to check the `readyState` before calling `send`.

#### Did you test this? If so, how?
Ran a snippet in the browser console:
```
var ws = new WebSocket("wss://invalid-ws-url.com");
setTimeout(() => ws.send("Hello"), 5000);
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/websocket/send`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/send
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/websocket/send/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can take a look at it 👍

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander assigned, thanks!

And thanks to @mofojed for reporting this.

**Comment by CreaTorAlexander** [comment]
@mofojed when will the INVALID_STATE_ERR be thrown? I found a disscusion on GitHub where they talked about this, is it thrown when it has no readyState?

**Comment by Rumyra** [comment]
@CreaTorAlexander "If the readyState attribute is CONNECTING" see the first line here: https://html.spec.whatwg.org/multipage/web-sockets.html#dom-websocket-send

Should just be a case of modifying the line "The connection is not currently OPEN." under "INVALID_STATE_ERR".

Let me know if you have any questions 👍

**Comment by CreaTorAlexander** [comment]
Okay perfect, thanks for your help 👍

**Comment by abdelrazek-alaa** [comment]
I have free time now , i would like to help.
