### ISSUE TITLE
Clarification Needed: Specificity Weight for Password Input Type with Required Attribute in CSS Specification

### ISSUE THREAD

**Issue by sundicide** [mdn/content#25890]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

### What specific section or headline is this issue about?

Matching selector

### What information was incorrect, unhelpful, or incomplete?

The original description is below

> If the password input type is nested in an element with id="myApp" set, the specificity weight will be 1-2-1.

But without `required` attribute, 1-2-1 specificity weight doesn't work.

So, I think it's a incomplete description and it should be fix like a same way with previous paragraph.

> The specificity for a required input nested in an element with attribute id="myApp" is 1-2-1, based on one ID, two pseudo-classes, and one element type.

(This paragraph contains `required` and it works perfectly)

### What did you expect to see?

If the password input type with required is nested in an element with id="myApp" set, the specificity weight will be 1-2-1.

### Do you have anything more you want to share?

please check my codepen link

[https://codepen.io/sundicide/pen/PodMLJz](https://codepen.io/sundicide/pen/PodMLJz)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/specificity`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/specificity/index.md
* Last commit: https://github.com/mdn/content/commit/18fa416bd2ee3e34fe7086cf57b0e5474738d6c4
* Document last modified: 2023-03-12T22:40:47.000Z

</details>

**Comment by estelle** [comment]
Your sentence is more explicit and improves the explanation. Added "good first issue" to see if someone new or relatively new wants to take this on.
