### ISSUE TITLE
Deviation of the `overflow-clip-margin` page from the spec

### ISSUE THREAD

**Issue by yarusome** [mdn/content#25906]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-clip-margin

### What information was incorrect, unhelpful, or incomplete?

`overflow-clip-margin` has added `<visual-box>` as a value in https://github.com/w3c/csswg-drafts/issues/5801 for a while, but the MDN page has not updated to reflect this change. Specifically:

  1. The "Syntax" section has no `<visual-box>` example.
  2. The "Computed value" item in the "Formal definition" section is now different from the spec. (Incidentally, the current item is also corrupted.)
  3. No seperate item in the BCD table showing the support statuses of the `<visual-box>` value, but only mentioned in the Firefox implementation info.

### What did you expect to see?

There're two ways to move forward:

  1. Update everything related to the syntax change to match the spec.
  2. Follow the precedent of the [`cross-fade()`](https://developer.mozilla.org/en-US/docs/Web/CSS/cross-fade) to document the discrepancy between the spec and implementations instead.

### Do you have any supporting links, references, or citations?

The current definition of `overflow-clip-margin` in the spec:
https://w3c.github.io/csswg-drafts/css-overflow/#overflow-clip-margin

**Comment by wbamberg** [comment]
Thank you for filing, @yarusome !

>     1. Update everything related to the syntax change to match the spec.
> 
>     2. Follow the precedent of the [`cross-fade()`](https://developer.mozilla.org/en-US/docs/Web/CSS/cross-fade) to document the discrepancy between the spec and implementations instead.
> 

I guess because browsers don't support `<visual-box>`? I would suggest (1), plus adding a subfeature to the BCD for the `<visual-box>` value, marking it as unsupported.

This case seems different from (and simpler than) `cross-fade()`, because with that there are two quite different implementations, and it's not really feasible to explain the implemented behavior in BCD.

Does that make sense?

**Comment by yarusome** [comment]
@wbamberg If no one else takes the task, I'd open related PRs following the first way later. (I've been a bit busy this week.)

**Comment by wbamberg** [comment]
That would be great, @yarusome !

**Comment by Josh-Cena** [comment]
Closing in favor of https://github.com/mdn/browser-compat-data/issues/19333 since the content seems up to date
