### ISSUE TITLE
Issue with "Function": There no longer seems to be any treatment for constructor functions

### ISSUE THREAD

**Issue by randycasburn** [mdn/content#2599]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function

#### What information was incorrect, unhelpful, or incomplete?
Where did the description of constructor functions go? I'm not referring to Class constructors, I'm referring to function declarations used as constructor functions for creating objects.

#### Specific section or headline?
Constructor Function 

#### What did you expect to see?

How to use a function declaration as a constructor function.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/function/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment]
Heads-up @Elchi3

**Comment by sideshowbarker** [comment]
@Elchi3 is this something that got changed when the reorg of the related docs was done? Should we label this as help wanted?

**Comment by Elchi3** [comment]
I don't think this is that. The reorg that happened a year ago or so created https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Function which is the `Function()` constructor and not functions as constructors ala `Foo()`.

Happy to label as help wanted.

**Comment by wbamberg** [comment]
I'm not sure what this issue is referring to. If it is talking about using functions as constructors, isn't this effectively covered in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new ?

**Comment by wbamberg** [comment]
OK, but the actual content you're looking for is that covered in the page for `new`? So this is really an issue about navigation (i.e. finding this content) rather than missing content?

If so I'm not sure we should link there from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function, since that's the page for the `Function` global object. But maybe we could mention it in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions ?
