### ISSUE TITLE
Add new `<search>` element to docs

### ISSUE THREAD

**Issue by YummyBacon5** [mdn/content#26006]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search

### What information was incorrect, unhelpful, or incomplete?

There's now a new `<search>` element in the [HTML spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-search-element), created about two weeks ago, which is not yet included in these docs.

### What did you expect to see?

Documentation about the element

### Do you have any supporting links, references, or citations?

* https://html.spec.whatwg.org/multipage/grouping-content.html#the-search-element
* https://github.com/whatwg/html/commit/c598ff023f081dd3f03b2e43177a632fb7dc92ec

### Do you have anything more you want to share?

This new element should also be mentioned on the [`<input type="search">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search), [`role="search"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/search_role) and [`role="searchbox"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/searchbox_role) pages.

**Comment by bsmth** [comment]
CCing @schalkneethling

**Comment by bsmth** [comment]
For future when someone works on a PR to add this, Domenic has kindly offered to review:

__related issues and pull requests:__
* [x] https://github.com/whatwg/html/pull/7320
* https://github.com/mdn/mdn/issues/385
