### ISSUE TITLE
Redirect for /en-US/docs/Web/Guide/API/DOM/Events/Mutation_events

### ISSUE THREAD

**Issue by Krinkle** [mdn/content#26030]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Events/Mutation_events

### What specific section or headline is this issue about?

Page not found

### What information was incorrect, unhelpful, or incomplete?

Yes

### What did you expect to see?

https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent

### Do you have any supporting links, references, or citations?

Incoming links from StackOverflow, blogs, mailing lists, social media posts.

### Do you have anything more you want to share?

I attempted to fix this myself, however it appears redirects are not kept in easy-to-edit content files. The `_redirects.txt` file indicates one must use yarn, which implies a fork and a local clone of the very large repository. I did that, but my isolated environment then failed because the repo also requires Node 18, which is too new to install in this environment.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mutationevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mutationevent/index.md
* Last commit: https://github.com/mdn/content/commit/5a6f98403115fb88a4a123caf35e85e06ac0e3ee
* Document last modified: 2023-03-15T02:55:06.000Z

</details>

**Comment by hound77** [comment]
@Krinkle I want to work on this issue
