### ISSUE TITLE
Add info about autoplaying multiple media with one user event

### ISSUE THREAD

**Issue by lucia-gomez** [mdn/content#26036]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide

### What information was incorrect, unhelpful, or incomplete?

Would be great to have an example or explanation about limitations related to playing multiple pieces of media in response to a single user-initiated event. I just found this isn't possible- I was trying to play a video and a separate piece of audio in one onclick handler. No matter what, one of them wouldn't play. I don't see anything in the docs that suggests this shouldn't be possible. In my case, thankfully I was able to get around this by muting the video. 

### What did you expect to see?

See above

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/media/autoplay_guide`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/media/autoplay_guide/index.md
* Last commit: https://github.com/mdn/content/commit/fa8a44b8bff24a4032181c4fd155c459c0dc9161
* Document last modified: 2023-03-13T07:09:38.000Z

</details>

**Comment by Josh-Cena** [comment]
@lucia-gomez Would be helpful if you can post what code you have tried. If we are to include this in content we have to understand why it can't work by principle.

**Comment by Josh-Cena** [comment]
Closing unless more information can be provided
