### ISSUE TITLE
Confusing about which HTML file should be edited

### ISSUE THREAD

**Issue by zzz6519003** [mdn/content#26042]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

### What information was incorrect, unhelpful, or incomplete?

in "Using the npm package on the web" part

we are in site folder now

> Finally, we need to modify the HTML file; open the index.html file and replace the current contents with the following:

where does the index.html exsist?

### What did you expect to see?

~

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/webassembly/rust_to_wasm`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/rust_to_wasm/index.md
* Last commit: https://github.com/mdn/content/commit/5e1bc6616b6583ddb723fba8815c5a183c63a8a5
* Document last modified: 2023-02-23T16:22:50.000Z

</details>

**Comment by yarusome** [comment]
It's created in the previous [section](https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm#using_the_package_on_the_web).

**Comment by zzz6519003** [comment]
```
cd pkg
npm link

```
cd ..
mkdir site
cd site
npm link hello-wasm

```

```

**Comment by zzz6519003** [comment]
then we did this

**Comment by wbamberg** [comment]
As https://github.com/mdn/content/issues/26042#issuecomment-1501047519 says, it's created in the previous section, at https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm#using_the_package_on_the_web. Before the part about using it with npm.

**Comment by Josh-Cena** [comment]
@wbamberg In that section, the HTML file is created within the `hello-wasm` folder. However, in this section, we have already cd'ed into the `site` folder, which is a sibling folder. If we are to modify the original index.html we need to make it clear that we are going back.
