### ISSUE TITLE
Please specify that `openWindow()` and `focus()` only works when the user clicked on a notification

### ISSUE THREAD

**Issue by adriancuadrado** [mdn/content#26048]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WindowClient/focus

### What information was incorrect, unhelpful, or incomplete?

The paragraph that contains the following text:

> The `focus()` method of the [`WindowClient`](https://developer.mozilla.org/en-US/docs/Web/API/WindowClient) interface gives user input focus to the current client and returns a [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that resolves to the existing [`WindowClient`](https://developer.mozilla.org/en-US/docs/Web/API/WindowClient).

### What did you expect to see?

It should be also stated that it will only work when the user clicked on a notification, and only during the click handler. Also, you can only call either `openWindow()` or `focus()`, but not both, and only once.

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/a/34250261

> Your code works fine for me, so I'll explain the requirements for using `openWindow` / `focus`, and how you can avoid the "Not allowed to [open|focus] a window" error message.
> 
> `clients.openWindow()` and `windowClient.focus()` are only allowed after clicking the notification (in Chrome 47 at least), and at most **one** of these methods can be called, for the duration of the click handler. This behavior was specified in https://github.com/slightlyoff/ServiceWorker/issues/602.
> 
> If your `openWindow` / `focus` call is rejected with error message
> 
> > "Not allowed to open a window." for `openWindow`  
> > "Not allowed to focus a window." for `focus`
> 
> then you didn't satisfy the requirements of `openWindow` / `focus`. For example (all points also apply to `focus`, not just `openWindow`).
> 
> - `openWindow` was called while the notification wasn't clicked.
> - `openWindow` was called after the `notificationclick` handler returned, and you did not call `event.waitUntil` with a promise.
> - `openWindow` was called after the promise passed to `event.waitUntil` was resolved.
> - The promise was not resolved, but it took "too long" ([10 seconds in Chrome][1]), so the temporary permission to call `openWindow` expired.
> 
> It is really necessary that `openWindow` / `focus` is called at most once, and before the `notificationclick` handler finishes.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/windowclient/focus`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowClient/focus
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/windowclient/focus/index.md
* Last commit: https://github.com/mdn/content/commit/73b724ad82b94d2a4c314924218367cea2740e97
* Document last modified: 2023-03-16T15:51:10.000Z

</details>

**Comment by zehawki** [comment]
The example shown here https://developer.mozilla.org/en-US/docs/Web/API/Clients/openWindow#examples also needs an update. It is calling `.focus()` after `.openWindow()` and with that I get `InvalidAccessError: Not allowed to focus a window.`
