### ISSUE TITLE
does not work in firefox focus

### ISSUE THREAD

**Issue by steniovm** [mdn/content#26054]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API

### What specific section or headline is this issue about?

https://mdn.github.io/dom-examples/drag-and-drop/copy-move-DataTransfer.html

### What information was incorrect, unhelpful, or incomplete?

I didn't identify where the problem is, but I know it didn't work in firefox focus for android.
the same happened to the application I'm developing using this resource, it works perfectly in Chrome for pc, Chrome for android and in firefox for pc, but in firefox focus for android it doesn't work.

### What did you expect to see?

Work equally on any platform.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/html_drag_and_drop_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/html_drag_and_drop_api/index.md
* Last commit: https://github.com/mdn/content/commit/e7d6e30b66982eedfc53367020a3de8218a44975
* Document last modified: 2023-03-22T09:48:09.000Z

</details>

**Comment by teoli2003** [comment]
This looks like a bug in Firefox Focus… Have you reported it to them?

**Comment by steniovm** [comment]
I haven't reported it yet, I thought it was more likely to be a bug in the code, but I'll report it.

**Comment by Josh-Cena** [comment]
I'm going to close this for now. If we can confirm that it's a bug on a certain browser, you may want to send an issue to browser-compat-data.
