### ISSUE TITLE
The meter bar example is slightly off compared to its description above

### ISSUE THREAD

**Issue by Junaid-1993** [mdn/content#26059]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls

### What specific section or headline is this issue about?

Meters and progress bars

### What information was incorrect, unhelpful, or incomplete?

In the meter section, the article explains about different attributes of the `<meter>` element. Like the lower, medium, and higher parts of the range. While explaining the `optimum` attribute in the second bullet point it states:

- If the `optimum` value is in the medium part of the range, the lower range is considered to be an **average** part, the medium range is considered to be the preferred part, and the higher range is considered to be **average** as well.

But later it states with the example:

Such a bar is created by using the `meter` element. This is for implementing any kind of meter; for example, a bar showing the total space used on a disk, **which turns red when it starts to get full.**

`<meter min="0" max="100" value="75" low="33" high="66" optimum="50">75</meter>`

But it will **never turn red** as the value of the `optimum` attribute is in the medium part of the range `50` and according to the second bullet point the lower and higher parts of the range will be **average** meaning **yellow**.

### What did you expect to see?

In order for the above statement to be true 

> which turns red when it starts to get full.

We need to change the value of the `optimum` attribute so that it is in the lower part of the range then it will turn **red** when it starts to get full. Any value between `0` and `33 `like:

`<meter min="0" max="100" value="60" low="33" high="66" optimum="25">75</meter>`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/other_form_controls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/other_form_controls/index.md
* Last commit: https://github.com/mdn/content/commit/af0e71822122feda89495ab9215c131bbe34d65c
* Document last modified: 2023-03-12T06:56:30.000Z

</details>

**Comment by Josh-Cena** [comment]
The optimum should be `0`. Welcoming PRs.

**Comment by Junaid-1993** [comment]
If you check the code in this article the `meter` will **never turn red** because the value of the `optimum` is in the medium part of the range, so the lower range is considered to be an average part which will be yellow, the medium range is considered to be the preferred part which will be green, and the higher range is considered to be average as well which will also be yellow.

The statement says:

- Such a bar is created by using the `meter` element. This is for implementing any kind of meter; for example, a bar showing the total space used on a disk, **which turns red when it starts to get full**.

`<meter min="0" max="100" value="75" low="33" high="66" optimum="50">75</meter>`

This above statement is making confusion because below code and statement do not align well.

**Comment by Josh-Cena** [comment]
@Junaid-1993, I'm not sure what your comment is adding to your issue; to clarify, I'm saying to fix this issue, we should change the optimum to 0.

**Comment by Junaid-1993** [comment]
We should change the `optimum` to between `min` and `low` values so that the `meter` will work as expected. So **25** will be a good value in this case.

`<meter min="0" max="100" value="60" low="33" high="66" optimum="25">75</meter>`

**Comment by Josh-Cena** [comment]
I'm saying the optimum should be 0. It doesn't make sense to set it to any value above 0.

**Comment by Junaid-1993** [comment]
okay, `0` will also work. The value of `optimum` should be `0` like the below code.

`<meter min="0" max="100" value="60" low="33" high="66" optimum="0">75</meter>`

**Comment by Vibs21** [comment]
Hi @Josh-Cena, I have followed your instructions and made the necessary changes can you please look into the PR, please let me know if there any other changes are required. Thank You :)

**Comment by Josh-Cena** [comment]
You are sending the PR to your fork, not our repo.
