### ISSUE TITLE
Non-existent CSS data type `<translation-value>`

### ISSUE THREAD

**Issue by yarusome** [mdn/content#26062]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/translation-value

### What information was incorrect, unhelpful, or incomplete?

There's no `<translation-value>` data type defined in CSS. CSS Transforms Module only uses the term "translation-value" (note the absence of angled brackets) in the [definition](https://w3c.github.io/csswg-drafts/css-transforms/#funcdef-transform-translate) of the `translate()` function.

### What did you expect to see?

The [`<translation-value>`](https://developer.mozilla.org/en-US/docs/Web/CSS/translation-value) page be removed.

The valuable part on the page is the "Example" section. But since it demonstrates both `translate*()` and `rotate()`, the example can be disentangled and added into the "Example" sections of other transform functions.

### Do you have any supporting links, references, or citations?

The spec:
https://w3c.github.io/csswg-drafts/css-transforms/

**Comment by hamishwillee** [comment]
Yes, it looks like its just a convenient way to refer to the parameters passed to `translate()`, but with no other useful defined meaning as you would expect for a data type. It isn't linked from anywhere, except the sidebar.

I think I'd just move the example to the tranlsate() docs and perhaps in rotate() put a note that links to that - i.e. under the heading: https://developer.mozilla.org/en-US/docs/Web/CSS/rotate#examples

@yarusome Do you want to PR the change?

**Comment by yarusome** [comment]
@hamishwillee I'd like to make a PR.

On a second look, the `rotate*()` functions used in the example are more for an auxilliary purpose. To move forward, I could place this exmaple on the [`translate`](https://developer.mozilla.org/en-US/docs/Web/CSS/translate#examples) page (with some adaptations) or on the [`transform`](https://developer.mozilla.org/en-US/docs/Web/CSS/transform#examples) page. I'm not sure which is better, though.

**Comment by hamishwillee** [comment]
Thank you!
- is it because the rotate functions are used for an auxiliary purpose I recommend we link to the example from the rotate() page as kind of "additional info".
-  I'd probably put on the `translate()` page with few, if any, modifications.

**Comment by yarusome** [comment]
@hamishwillee After being reminded of the `translate()` *function*, I found that the [example](https://developer.mozilla.org/en-US/docs/Web/CSS/translation-value#result) on the `<translation-value>` page is simply an excerpt of [that](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#result) on the `<transform-function>` page. So maybe the `<translation-value>` page can be removed directly. (Sorry for the insufficient investigation prior to filing this issue :pray:)

Could I go ahead this way (plus checking if any other page points to this one)?

**Comment by hamishwillee** [comment]
@yarusome Yes - sounds like a good plan. Note though, it might not be me reviewing it, so possibly that person might have further suggestions.

I did a search on the source and found no links to this page.

**Comment by yarusome** [comment]
I have thus closed my PR. Hope someone else with a complete dev environment to make the deletion.

**Comment by hamishwillee** [comment]
Thanks @yarusome ! All merged now.
