### ISSUE TITLE
Logging requests tutorial doesn't work on some sites

### ISSUE THREAD

**Issue by Inspirateur** [mdn/content#26067]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests

### What specific section or headline is this issue about?

Logging requests

### What information was incorrect, unhelpful, or incomplete?

The logging request tutorial just doesn't work on some sites, due to the "Content Security Policy".

CSP documentation page has not proven helpful at all to solve or explain the issue either.

### What did you expect to see?

A warning about errors that might occur due to CSP, with a link to an explanation of why the error is happening and how to prevent it.

### Do you have any supporting links, references, or citations?

Try it on this site for example:  
https://www.carrefour.fr/s?filters%5Bproduct.categories.id%5D%5B0%5D=1952&q=pain&sq=pain&noRedirect

You will get the following error if you try to search a product:  
`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/intercept_http_requests`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/intercept_http_requests/index.md
* Last commit: https://github.com/mdn/content/commit/d86e14de2e66319fc0a0ec0539a05400dea5a453
* Document last modified: 2023-03-07T05:20:12.000Z

</details>

**Comment by rebloor** [comment]
@Inspirateur This issue is not caused by the logging example. The CSP error is independent of the example and is either an issue with the website or an issue caused by another extension you are using. If you need further assistance, your best option is the post a query on the [add-on forum](https://discourse.mozilla.org/c/add-ons/35)
