### ISSUE TITLE
Issue with "Using the Web Animations API": (short summary here please)

### ISSUE THREAD

**Issue by bartek-szymanski** [mdn/content#2606]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API/Using_the_Web_Animations_API

#### What information was incorrect, unhelpful, or incomplete?

Animation of the "Alice falling down the rabbit hole" has a color change that is not visible well enough on the screen in case of a lot of light in the room. 

It's an example, and as such should show very clearly what's happening with very distinct colors.   

#### Specific section or headline?

Animation of the "Alice falling down the rabbit hole".

#### What did you expect to see?

Clear example, using distinct colors, to see the difference, the key change in the animation.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/web_animations_api/using_the_web_animations_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API/Using_the_Web_Animations_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_animations_api/using_the_web_animations_api/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update it. Which color would you suggest?

**Comment by chrisdavidmills** [comment]
I don't think we need to update this. I appreciate the concern here, but the color change is supposed to be subtle, and updating all the examples would be a pain.
