### ISSUE TITLE
Define and add page-type header for MathML

### ISSUE THREAD

**Issue by teoli2003** [mdn/content#26082]
Part of https://github.com/mdn/content/issues/15539.

In this [spreadsheet](https://docs.google.com/spreadsheets/d/18kHw9xfivLopBECkmy5AZz6W44q4_0GqRlSDUizm_c4/edit#gid=0), I've listed every page under https://developer.mozilla.org/en-US/docs/Web/MathML and made an initial determination about the page type.

I've come up with the following types:
```
guide             5
mathml-element   29
mathml-attribute  8 (the extra global attributes)
landing page      5
```
For a total of 47 pages.

This seems like a good list to me, very similar to the one we used for HTML (but simpler).

Adding a `page-type` in the YAML header will not directly affect the pages. We plan to:
- update the sidebar to use them instead of the hierarchy (we did this for other sidebars, and thus lower the complexity of the platform)
- add some page-type related checks (like defining and imposing a set structure), but we have not set a date for this (or even precise plans)

Given there are only 47 pages, the PR is already ready locally.

cc/ @wbamberg @fred-wang

**Comment by wbamberg** [comment]
Makes sense to me, @teoli2003 !
