### ISSUE TITLE
Some issues / inconsistencies on the <tr> reference page

### ISSUE THREAD

**Issue by glmvc** [mdn/content#26088]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr

### What specific section or headline is this issue about?

Some content of the article

### What information was incorrect, unhelpful, or incomplete?

1. The two paragraphs below the interactive example would somehow fit better on the overall [`<table>` reference page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table)?
  At least the first paragraph should belong to the [`<td>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td#rowspan), with `colspan` and `rowspan` being the attributes of it
  Also, the reference to the [HTML tables](https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables) section in the learning area would definitely make more sense in the [`table` reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table), in my opinion.
2. Here are also a few examples for correct table markup and styling. But shouldn't this examples be also moved to the [`<table>` reference page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table)?
  Of course, the examples also show how to use the `<tr>` element, but not explicitly.
  On the [`<td>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td#examples) and [`<th>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#examples) reference pages under the "Examples" sections there is just the sentence "See `<table>` for examples on `<td>` / `<th>`."
3. Under each of two HTML code blocks is an identical paragraph starting with "The differences that matter here [...]". It seems that the [second one](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr#explicitly_specifying_table_content_groups) was just a copy and paste error (from the [example above](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr#row_and_column_spanning)).
  The second paragraph should be about the use of the `<thead>` and `<tbody>` elements + `scopes` - not about `colspan` and `rowspan`.
  The "intro" sentence under the [heading of this example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr#explicitly_specifying_table_content_groups), should maybe also be adapted, commenting the additional use of `<thead>` and `<tbody>` elements...

### What did you expect to see?

I think it's just inconsistent, as I described above.
As a reader, I was also wondering how the examples are directly connected to the `<tr>` element itself...

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/tr`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/tr/index.md
* Last commit: https://github.com/mdn/content/commit/fa8a44b8bff24a4032181c4fd155c459c0dc9161
* Document last modified: 2023-03-13T07:09:38.000Z

</details>

**Comment by postmeback** [comment]
I went through the entire page, but i was unable to find any inconsistency. Maybe the page has been updated already. Would you like to recheck ?

**Comment by Josh-Cena** [comment]
@postmeback The issue description says exactly what needs to be updated. Namely the examples aren't illustrative and need to be moved, and there are some out-of-place paragraphs.

**Comment by glmvc** [comment]
@Josh-Cena Thank you for the clarification! I'm missing some feedback. Or do you agree with the points I have listed and I can just start making the improvements as time allows and create a pr?

**Comment by estelle** [comment]
Here's some general feedback:

- Table examples should use best practices. This means use `thead`, `tbody`, `caption`, etc., unless explaining why they're not being used.
- Examples that include a new element or feature should link to that element or feature. For example, if you include a `col` or `colgroup` in an example, link to those.
- Examples focused on attributes should be on the page on which the attribute is set. For example, styling a 
   - `col` should be on the `col` page. 
   - `colspan` and `rowspan` should be on the `th` and `td` pages. 
   - Striping rows should be on the `tr` page.
 - Information in example tables should be the type of data you would expect to see in the cell. Notably, content in a `tfoot` should be table footer content, such as "sum" or average", or a `th` matching the look of the header
