### ISSUE TITLE
Spread syntax (...)

### ISSUE THREAD

**Issue by bkwdev183** [mdn/content#26099]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

### What specific section or headline is this issue about?

Spread in object literals

### What information was incorrect, unhelpful, or incomplete?

const obj1 = { foo: "bar", x: 42 };
const obj2 = { foo: "baz", y: 13 };

const clonedObj = { ...obj1 };
// { foo: "bar", x: 42 }

const mergedObj = { ...obj1, ...obj2 };
// { foo: "baz", x: 42, y: 13 }

### What did you expect to see?

const obj1 = { foo: "bar", x: 42 };
const obj2 = { foo: "baz", y: 13 };

const clonedObj = { ...obj1 };
// { foo: "bar", x: 42 }

const mergedObj = { ...obj1, ...obj2 };
//{ "foo": "bar", "x": 42,  "foo": "baz", "y": 13}

### Do you have any supporting links, references, or citations?

not needed you will see it

### Do you have anything more you want to share?

have a good day!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/spread_syntax`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/spread_syntax/index.md
* Last commit: https://github.com/mdn/content/commit/0f3738f6b1ed1aa69395ff181207186e1ad9f4d8
* Document last modified: 2023-02-21T00:33:34.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! If property names are duplicated, the latter overrides the former. You will see the indicated output if you run it yourself. An object can never have two keys with the same name.

<img width="286" alt="image" src="https://user-images.githubusercontent.com/55398995/231031399-ac920a0e-1bad-41e1-a7db-66d7ebf18b60.png">
