### ISSUE TITLE
Conflict in documentation in specifying "default" locale

### ISSUE THREAD

**Issue by gpbmike** [mdn/content#26090]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

### What specific section or headline is this issue about?

Using Options

### What information was incorrect, unhelpful, or incomplete?

In the examples, to use the browser's "default" locale, you are instructed to use "default".

```js
// to specify options but use the browser's default locale, use 'default'
console.log(new Intl.DateTimeFormat("default", options).format(date));
// "12/19/2012, 19:00:00"
```

This conflicts with the ["locales argument" section of the `Intl` documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#locales_argument) which says

> `undefined` (or omitted): The implementation's default locale will be used.

### What did you expect to see?

I would expect both places to use the "default" string, or both places to use `undefined`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/datetimeformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/datetimeformat/index.md
* Last commit: https://github.com/mdn/content/commit/01bf58c144237c1fc75cf7135491346778591f09
* Document last modified: 2023-04-08T17:33:52.000Z

</details>

**Comment by Josh-Cena** [comment]
Using `undefined` or `[]` is the specified way to get the default locale; frankly this is my first time seeing `"default"`, and I need to do some research to see where it's mapped (definitely not in the ES spec).
