### ISSUE TITLE
Demo doesn't work for me in Firefox 111.0 on Windows 11

### ISSUE THREAD

**Issue by mvark** [mdn/content#26101]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API

### What specific section or headline is this issue about?

Demo, Browser Support

### What information was incorrect, unhelpful, or incomplete?

According to the Browser Support section, the sample is supposed to work in Firefox. In Firefox 111.0 on Windows 11, media.webspeech.synth.enabled flag is true by default in about:config

From Firefox Developer Tools, I see that error is for this reason -
Uncaught ReferenceError: webkitSpeechRecognition is not defined
    <anonymous> https://mdn.github.io/dom-examples/web-speech-api/speech-color-changer/script.js:1

### What did you expect to see?

I expect sample to work in Firefox

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_speech_api/using_the_web_speech_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_speech_api/using_the_web_speech_api/index.md
* Last commit: https://github.com/mdn/content/commit/73b724ad82b94d2a4c314924218367cea2740e97
* Document last modified: 2023-03-16T15:51:10.000Z

</details>

**Comment by teoli2003** [comment]
![Capture d’écran 2023-04-11 à 06 53 51](https://user-images.githubusercontent.com/1466293/231059799-cc9edb29-4424-45df-b05a-5a65d19948f0.png)

Speech recognition is not supported by Firefox.

**Comment by mvark** [comment]
Please have the existing documentation changed in the Browser Support section to indicate that Speech recognition is not currently supported by Firefox

**Comment by hamishwillee** [comment]
We generally try and avoid having browser support statements in the user guide for just this reason - it is hard to maintain. 

What I have done is removed the section altogether. Users will have to check the specific APIs they are using.

**Comment by mvark** [comment]
In that Browser Support section, a link to a browser feature comparison table on a site like https://caniuse.com/ could be provided so that readers can still know about evolving changes.

**Comment by hamishwillee** [comment]
Yes it could. But I have chosen not to - we tend to have browser compat sections in these top level guides only when there is very limited support for an API.

FYI I wouldn't link to caniuse in any case, since that is derived from the MDN browser data. I'd just select the top few interfaces in the API and list them at the end of the doc. It is possible this will be requested by the reviewer of the PR.
