### ISSUE TITLE
JavaScript: Add article listing and explaining automatic features of iterables

### ISSUE THREAD

**Issue by a2sheppy** [mdn/content#2610]
It's currently hard to find specific information about what an iterable object actually has in it automatically upon creation. Does it automatially have a `forEach()` method without having to explicitly define one? That kind of thing.

There should be an article "Standard features of iterables in JavaScript" that lists these (with multiple sections to provide separate lists if there are different scenarios or types of iterable).

**Comment by himanshugarg** [comment]
The set - `for...of` loops, the spread operator, `yield*`, and destructuring assignment - is documented in 
1. [Iteration Protocols > Syntaxes expecting iterables](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#syntaxes_expecting_iterables) and also a little differently in 
2. [Iterators and Generators > Syntaxes expecting iterables](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#syntaxes_expecting_iterables)

**Comment by sideshowbarker** [comment]
@himanshugarg Thanks — so do you think this issue can be closed?

**Comment by himanshugarg** [comment]
Yes because those sections catalog the requested syntaxes, which a new article might duplicate.

**Comment by sideshowbarker** [comment]
OK, thanks @himanshugarg — closing per https://github.com/mdn/content/issues/2610#issuecomment-910057379
