### ISSUE TITLE
Issue with inheritance with classes: examples are an anti-pattern 

### ISSUE THREAD

**Issue by TrangOul** [mdn/content#26110]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain

### What specific section or headline is this issue about?

Different ways of creating and mutating prototype chains

### What information was incorrect, unhelpful, or incomplete?

Classes in the part "[Different ways of creating and mutating prototype chains](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain#different_ways_of_creating_and_mutating_prototype_chains)". First, the class `Polygon` should be called `Rectangle`, as it has only width and height. Second, more important, `Square extends Rectangle` is a [classic OOP problem](https://en.wikipedia.org/wiki/Circle%E2%80%93ellipse_problem) which violates the [Liskov substitution principle ](https://en.wikipedia.org/wiki/Liskov_substitution_principle). By including it in the documentation, the incorrect usage is being spread among the developers.
This is exactly the same issue as [7840](https://github.com/mdn/content/issues/7840)

### What did you expect to see?

Different example classes. For consistence can be the same as in [`class` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/class).

### Do you have any supporting links, references, or citations?

[The same issue in the documentation of `class` statement](https://github.com/mdn/content/issues/7840).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/inheritance_and_the_prototype_chain`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/inheritance_and_the_prototype_chain/index.md
* Last commit: https://github.com/mdn/content/commit/d85a7ba8cca98c2f6cf67a0c44f0ffd467532f20
* Document last modified: 2023-04-05T04:57:48.000Z

</details>

**Comment by Josh-Cena** [comment]
Welcoming a PR that copies the `class` example over.
