### ISSUE TITLE
Custom design in Logseq

### ISSUE THREAD

**Issue by 12-13-mm** [mdn/content#26112]
### MDN URL

dfds

### What information was incorrect, unhelpful, or incomplete?

Hi, I came across an article about zetelkasten (note taking method) and a very sophisticated visual design of a note taking system that I would like to apply to mine in LOgseq. Therefore, I would need someone to consult the css codes for a purposeful color conversion as it looks in the pictures. My existing color design doesn't suit me and so I would like some color changes. Do you know how to do it? I know the only way would be through programming and I don't really understand that. MK - there is an article https://www.thrivinghenry.com/writings/roamkasten-a-practical-how-to-guide-to-optimize-zettelkasten-in-roam-research

### What did you expect to see?

dfsfsd

### Do you have anything more you want to share?

![image](https://user-images.githubusercontent.com/83947823/231104422-050a0af5-e177-425c-892d-2e387fc09bc7.png)
![image](https://user-images.githubusercontent.com/83947823/231104451-1d3da27e-2506-41dc-ae94-a806677eb8a1.png)
![image](https://user-images.githubusercontent.com/83947823/231104479-23302680-0ff4-4070-b2c4-14a7e67da30e.png)

**Comment by schalkneethling** [comment]
@12-13-mm, please note that we have dozens of people watching this repository. For every comment posted, these people may receive a notification.

Please be respectful of other people’s time and attention, and avoid taking actions that might cause excessive notifications. Issues should describe a problem or propose an actionable solution. Please use the [MDN Web Docs feedback repository](https://github.com/mdn/feedback/discussions) if a discussion is needed.

Also, please remember that the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) govern all participation in these open spaces. We enforce these to maintain a healthy and inviting community experience for everyone.
