### ISSUE TITLE
Define and add page-type for Web/Accessibility

### ISSUE THREAD

**Issue by teoli2003** [mdn/content#26116]
Part of https://github.com/mdn/content/issues/15539.

In this [spreadsheet](https://docs.google.com/spreadsheets/d/13b_OPfFSqaXL-WexqlPtessK_TnJtQypWtk5J5gtytc/edit#gid=0), I've listed every page under https://developer.mozilla.org/en-US/docs/Web/MathML and made an initial determination about the page type.

I've come up with the following types:
```
guide            25
aria-attribute   52
aria-role  86
landing page     5
```
For a total of 171 pages (3 pages will get merged/deleted in a first PR)

There is a need to have a better architecture for the guides: I plan to tackle this information architecture work when working on a single sidebar for the whole Web/Accessibility hierarchy.

cc/ @wbamberg @estelle

**Comment by wbamberg** [comment]
Thanks @teoli2003 !

The set of types looks good to me but 86 landing pages is surely a typo.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms is listed as a landing page, but lists three pages, two of which don't seem to exist any more. How about incorporating the remaining page, https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms/Multipart_labels, into https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms, so we just have one guide page?

**Comment by teoli2003** [comment]
> Thanks @teoli2003 !
> 
> The set of types looks good to me but 86 landing pages is surely a typo.
>
Yes, fixed! (86 roles but 5 landing pages)

> https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms is listed as a landing page, but lists three >pages, two of which don't seem to exist any more. How about incorporating the remaining page, >https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms/Multipart_labels, into >https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms, so we just have one guide page?

Sounds good to me. There will be surely more changes when we create a unified sidebar. I really like the guides we have, but they are difficult to navigate from one to the others.
