### ISSUE TITLE
Attributes documentation for HTML input elements is confusing

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#2611]
See https://discourse.mozilla.org/t/attributes-for-input-elements/43899.

We should give each input element its own "Attributes" list including all the attributes it supports (apart from the [real global ones](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes)) and scrap the "Supported common attributes" row in the blue box.

MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML

**Comment by sideshowbarker** [comment]
@estelle Are you still planning to work on this one?

**Comment by estelle** [comment]
Hoping to do it Q3
