### ISSUE TITLE
[WebAPI] WebRTC updates

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#26146]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

There's a number of RTC related bugs this month - so I'm grouping them altogether. 

## Related Gecko bugs

Implement RTCRtpSender.getCapabilities: https://bugzilla.mozilla.org/show_bug.cgi?id=1531460
Implement RTCRtpSender.setStreams(): https://bugzilla.mozilla.org/show_bug.cgi?id=1510802
Implement RTCSctpTransport and RTCPeerConnection.sctp: https://bugzilla.mozilla.org/show_bug.cgi?id=1278299
Implement RTCMediaSourceStats: https://bugzilla.mozilla.org/show_bug.cgi?id=1804678
Add support for RTCPeerConnectionState in RTCPeerConnection: https://bugzilla.mozilla.org/show_bug.cgi?id=1265827
RTCPeerConnectionStats ("peer-connection" RTCStatsType) support: https://bugzilla.mozilla.org/show_bug.cgi?id=1531087
Remove remaining mozRTC* stuff (mozRTCPeerConnection, mozRTCIceCandidate, mozRTCSessionDescription): https://bugzilla.mozilla.org/show_bug.cgi?id=1531812

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
Status

- [ ] Release note

- [ ] `RTCRtpSender.getCapabilities()` (https://bugzilla.mozilla.org/show_bug.cgi?id=1531460)
  - [ ] BCD - https://github.com/mdn/browser-compat-data/pull/19439
  - [ ] Docs: TBD
  - [ ] dev-doc-complete

- [ ] `RTCRtpSender.setStreams()`: https://bugzilla.mozilla.org/show_bug.cgi?id=1510802
  - [ ] BCD - https://github.com/mdn/browser-compat-data/pull/19439
  - [ ] Docs: TBD
  - [ ] dev-doc-complete

- [ ] RTCSctpTransport and RTCPeerConnection.sctp: https://bugzilla.mozilla.org/show_bug.cgi?id=1278299
  - [ ] BCD - https://github.com/mdn/browser-compat-data/pull/19440
  - [ ] Docs: TBD
  - [ ] dev-doc-complete

- [ ] `RTCMediaSourceStats`: (https://bugzilla.mozilla.org/show_bug.cgi?id=1804678)
  - [ ] [FF113 supports (some) media-source stats](https://github.com/mdn/browser-compat-data/pull/18910/commits/61bca21d740b54a733e711222da9ad2e459223c3)
  - [ ] Docs: TBD
  - [ ] dev-doc-complete

- [ ] [RTCPeerConnection.connectionState](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/connectionState): (https://bugzilla.mozilla.org/show_bug.cgi?id=1265827)
  - [ ] BCD https://github.com/mdn/browser-compat-data/pull/19442
  - [ ] Docs: TBD
  - [ ] dev-doc-complete

- [ ] `RTCPeerConnectionStats` ("peer-connection" RTCStatsType) support: https://bugzilla.mozilla.org/show_bug.cgi?id=1531087
  - [ ] BCD [FF113 supports peer-connection stats](https://github.com/mdn/browser-compat-data/pull/18910/commits/28f2e90e46cb74765a02e34bdf82af48419a0057)
  - [ ] Docs: TBD
  - [ ] dev-doc-complete

- [ ] Remove remaining mozRTC* stuff (mozRTCPeerConnection, mozRTCIceCandidate, mozRTCSessionDescription): https://bugzilla.mozilla.org/show_bug.cgi?id=1531812
  - [ ] BCD - none - not mentioned
  - [ ] Docs: - None - mentioned, but only in relnotes. Will mention again in relnote.
  - [ ] dev-doc-complete
