### ISSUE TITLE
[CSS] Media query updates

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#26150]
Using the task list here for the `scripting` media feature

## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- NA - Interactive example and data repos are updated if appropriate
- NA - The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- NA - Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Two which I'm grouping

## Related Gecko bugs

Implement prefers-reduced-transparency media query: https://bugzilla.mozilla.org/show_bug.cgi?id=1736914
Implement the `scripting` media feature from Media Queries Level 5: https://bugzilla.mozilla.org/show_bug.cgi?id=1166581

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by dipikabh** [comment]
Related doc issue to track prefers-reduced-transparency media query: https://github.com/mdn/content/issues/25773

**Comment by dipikabh** [comment]
Tasks for `scripting` media query:

- Update BCD - done by @CanadaHonk: https://github.com/mdn/browser-compat-data/pull/19263
