### ISSUE TITLE
[WebAPI] Enable WebGPU in Nightly by default

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#26157]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1746245 @chrisdavidmills has just documented this, so it should just be experimental features & bcd - wondering if @queengooborg can help out with bcd

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
Yes, though BCD is proving tough - i.e. working out what FF really supports is not obvious in all cases from the IDL.

Status
- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/19370
- [ ] Experimental features
- [ ] Docs 
   - [ ] [Structure clone serializable types](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#supported_types)  - might need to add some more
- [ ] dev-doc-complete
