### ISSUE TITLE
Misleading or old information about the styling of the <option> element across different browsers 

### ISSUE THREAD

**Issue by Junaid-1993** [mdn/content#26182]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling

### What specific section or headline is this issue about?

Selects and datalists

### What information was incorrect, unhelpful, or incomplete?

In this section the article explains two problems relating to styling the `<select>` and `<datalists>` elements. In the second problem, the article says:

> The second, slightly more major issue is that you don't have control over the box that appears containing the options when you click on the `<select>` box to open it. **You'll notice that the options don't inherit the font set on the parent**. 

The last line says the `<option>` element doesn't **inherit** the font set from the parent. Maybe this happens on older browsers but when I checked both on **Firefox** and **Chrome** `<option>` is inheriting the font from its parent so this line is not correct anymore in the paragraph. On the next line, it says:

> You also can't consistently set things like spacing and colors. For example, Firefox will apply [color](https://developer.mozilla.org/en-US/docs/Web/CSS/color) and [background-color](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color) when set on the `<option>` elements, **but Chrome won't**.

I checked on Chrome it also applies the **color** and **background color** properties so this statement that Chrome won't apply these properties does not make any sense because Chrome also applies these properties as well.

### What did you expect to see?

Maybe change this paragraph so that it does not create confusion between the old and modern browser's capabilities.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/advanced_form_styling`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/advanced_form_styling/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by Josh-Cena** [comment]
Should be fixed by #26538
