### ISSUE TITLE
Link for aria-description links to page for aria-describedby

### ISSUE THREAD

**Issue by kenlyon** [mdn/content#26192]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-details

### What specific section or headline is this issue about?

See Also

### What information was incorrect, unhelpful, or incomplete?

The link to `aria-description` actually links to the page for `aria-describedby`.

### What did you expect to see?

It should link to the page for `aria-description`.

**Comment by dalvg** [comment]
Thanks @kenlyon I submitted a pull request for the issue.
