### ISSUE TITLE
Using ev insted of event in IndexedDB

### ISSUE THREAD

**Issue by Bodkens** [mdn/content#26204]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB

### What information was incorrect, unhelpful, or incomplete?

As I know,  **event** is deprecated. Isn't it better to use **ev** instead of it? 

### What did you expect to see?

**ev** instead of **event**

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/indexeddb_api/using_indexeddb`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/indexeddb_api/using_indexeddb/index.md
* Last commit: https://github.com/mdn/content/commit/4b9377a26bb7094a8f13551cf328865a6457f5ee
* Document last modified: 2023-03-21T12:46:26.000Z

</details>

**Comment by teoli2003** [comment]
Event is a parameter name and can be called whatever the dev want. So event is not deprecated. It is easier to understand than a abbreviation.
