### ISSUE TITLE
Image links broken

### ISSUE THREAD

**Issue by isaacbatst** [mdn/content#2621]
Hello guys! The image links on [theses](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/figura#exemplos) examples are broken.

![Captura de tela de 2021-02-23 14-43-36](https://user-images.githubusercontent.com/18752045/108884689-a4561e80-75e5-11eb-8166-3cd5fdc92243.png)

**Comment by wbamberg** [comment]
It looks like the `src` in the example needs to be updated. See the [en-US version](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure#examples) (which does work):

```html
<!-- Just an image -->
<figure>
  <img
  src="https://developer.mozilla.org/static/img/favicon144.png"
  alt="The beautiful MDN logo.">
</figure>

<!-- Image with a caption -->
<figure>
  <img
  src="https://developer.mozilla.org/static/img/favicon144.png"
  alt="The beautiful MDN logo.">
  <figcaption>MDN Logo</figcaption>
</figure>
```

-> https://developer.mozilla.org/static/img/favicon144.png exists, https://developer.cdn.mozilla.net/media/img/mdn-logo-sm.png does not.

**Comment by Ryuno-Ki** [comment]
This is the pt-BR version. I'm assuming, it's frozen for now and won't be fixed anywhen soon.
https://hacks.mozilla.org/2021/02/mdn-localization-update-february-2021/ shares the latest public plans about MDN web docs.

**Comment by sideshowbarker** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.

**Comment by isaacbatst** [comment]
It seems we now have an [active community](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#brazilian_portuguese_pt-br) working on pt-BR.

Should re-open @sideshowbarker ?
