### ISSUE TITLE
maximumFractionDigits has no effect

### ISSUE THREAD

**Issue by ygoe** [mdn/content#26213]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

### What specific section or headline is this issue about?

maximumFractionDigits option

### What information was incorrect, unhelpful, or incomplete?

The documentation explains that an option called `maximumFractionDigits` can be set and will be used accordingly. But I cannot observe this behaviour in any browser. It's ignored when set in the constructor, so I assume it cannot be configured.

### What did you expect to see?

Here's a simple test case for the console:

`new Intl.NumberFormat({ maximumFractionDigits: 5 }).resolvedOptions().maximumFractionDigits`

This should return 5 but it returns its default value of 3. And the number formatting also caps at 3 decimals at most.

### Do you have anything more you want to share?

I want to format numbers with 1 to 5 decimals, depending on the size. None of the NumberFormat options can do this, and they even fail with manual configuration. So I guess I'll have to implement it myself, taking the decimal separator from my existing texts dictionary and using simple Math.round() and String.replace() as needed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat/index.md
* Last commit: https://github.com/mdn/content/commit/2e9aad16acccd74da48bf69d33cf358db202c51a
* Document last modified: 2023-04-11T18:58:51.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! The options must be passed as the second parameter. The first parameter is the locale. You can get the right result if you pass a locale:

```js
new Intl.NumberFormat("en-US", { maximumFractionDigits: 5 }).resolvedOptions().maximumFractionDigits;
new Intl.NumberFormat([], { maximumFractionDigits: 5 }).resolvedOptions().maximumFractionDigits;
new Intl.NumberFormat(undefined, { maximumFractionDigits: 5 }).resolvedOptions().maximumFractionDigits;
```
