### ISSUE TITLE
Missing Webauthn Conditional UI attributes

### ISSUE THREAD

**Issue by franciscofabian** [mdn/content#26227]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

### What information was incorrect, unhelpful, or incomplete?

The `webauthn` value for the `autocomplete` HMTL attribute is missing, together with the browser compatibility for that value.

### What did you expect to see?

The `webauthn` value and examples on the `autocomplete` HTML attribute, like explained here https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Conditional-UI

**Comment by Josh-Cena** [comment]
Fixed by #25922
