### ISSUE TITLE
photo generator 

### ISSUE THREAD

**Issue by kritikaniraula** [mdn/content#26228]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

### What specific section or headline is this issue about?

why is my site showing an error

### What information was incorrect, unhelpful, or incomplete?

no

### What did you expect to see?

no

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

no thankyou

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/404`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/404/index.md
* Last commit: https://github.com/mdn/content/commit/0880a90f3811475d78bc4b2c344eb4146f25f66c
* Document last modified: 2023-04-10T19:47:15.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing problems in the MDN documentation.

It looks like you are seeking help with your code. Unfortunately, we don't have enough availability to help you.

If you have a problem with your code, I would suggest you ask your question on a specialized website like [StackOverflow](https://stackoverflow.com/questions).


I'm closing this issue. If I've misunderstood you and you were reporting a problem in the documentation, feel free to reopen it while providing more information so we can understand the problem.

Thanks for your interest.
