### ISSUE TITLE
Object assignment to Node.textContent 

### ISSUE THREAD

**Issue by EvangelosKolimitras** [mdn/content#26243]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Range/setStart

### What specific section or headline is this issue about?

Invalid assignment

### What information was incorrect, unhelpful, or incomplete?

```js
const element = document.getElementById("content");
const textNode = element.childNodes[0];
const range = document.createRange();
range.setStart(textNode, 0); // Start at first character
range.setEnd(textNode, 5); // End at fifth character
document.getElementById("log").textContent = range;
```

### What did you expect to see?

```js
const element = document.getElementById("content");
const textNode = element.childNodes[0];
const range = document.createRange();
range.setStart(textNode, 0); // Start at first character
range.setEnd(textNode, 5); // End at fifth character
document.getElementById("log").textContent = range.extractContents().textContent;
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/range/setstart`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Range/setStart
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/range/setstart/index.md
* Last commit: https://github.com/mdn/content/commit/c58e8c1dd6ecbcb63894c7dd17fb9495b9511b4e
* Document last modified: 2023-04-07T19:46:21.000Z

</details>

**Comment by teoli2003** [comment]
The original code works for me.

![Capture d’écran 2023-04-17 à 07 17 21](https://user-images.githubusercontent.com/1466293/232385444-64da6df1-7df8-422f-9383-99eeadbddf94.png)

**Comment by EvangelosKolimitras** [comment]
Hmmm, that's been considered a typescript error since it is not impossible to predict if the object has a toString() method on it(or it is a prototype if it inherits Object). Using the `noEmitOnError` compiler flag will definitely prevent you from compiling. Closing since the issue is not relevant to the implementation.
