### ISSUE TITLE
Issue with "Network monitor toolbar": (short summary here please)

### ISSUE THREAD

**Issue by M1k3Mullins** [mdn/content#2624]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/toolbar

#### What information was incorrect, unhelpful, or incomplete?
the dropdown menu to throttle speeds is no longer present

#### Did you test this? If so, how?
i hit Ctrl+Shift+E to bring up the Network Monitor frame, and on the right side of ''Disable Cache'' there is a large blank space and then i have a filter box for Filter URLs. i do not have a Throttle Speed dropdown as described on the article's page.

i'm on Firefox Quantum ESR v60.9.0

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/network_monitor/toolbar`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/toolbar
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/network_monitor/toolbar/index.html
* Last commit: https://github.com/mdn/content/commit/0ea5ea66ca3ff5f0c02583c1f3606b3b7d4aee40
* Document last modified: 2021-02-02T16:28:31.000Z

</details>

**Comment by chrisdavidmills** [comment]
The article is correct for recent versions of Firefox. On the page, it says "Prior to Firefox 77, this toolbar was arranged somewhat differently."

If you are using an old ESR version, then you might just have to accept that the docs won't match your exact experience. It would be too difficult for us to arrange the docs in a way that would mirror everyone's experience, regardless of Firefox version used.
