### ISSUE TITLE
Issue with "Using IIR filters": Broken link

### ISSUE THREAD

**Issue by dsuedholt** [mdn/content#2625]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_IIR_filters

#### What information was incorrect, unhelpful, or incomplete?
The link with the text "information about the maths behind IIR filters here" (http://www.eas.uccs.edu/~mwickert/ece2610/lecture_notes/ece2610_chap8.pdf) leads to a 404.

#### Specific section or headline?
Section "The IIRFilterNode".

#### What did you expect to see?
Not a 404 page.

#### Did you test this? If so, how?
I clicked on the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/web_audio_api/using_iir_filters`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_IIR_filters
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_audio_api/using_iir_filters/index.html
* Last commit: https://github.com/mdn/content/commit/9fe6b6233764f2e961c7760e14a37c86708dbf74
* Document last modified: 2020-12-15T02:04:17.000Z

</details>

**Comment by chrisdavidmills** [comment]
Above referenced PR fixes this, so closing; thanks for reporting this, @dsuedholt !
