### ISSUE TITLE
Vendor specific value required?

### ISSUE THREAD

**Issue by crespire** [mdn/content#26256]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content#css

### What information was incorrect, unhelpful, or incomplete?

Is the `width: -moz-fit-content` line necessary in 2023?

### What did you expect to see?

Unsure, it seems `fit-content` is now supported across all browsers.

### Do you have any supporting links, references, or citations?

Most links I was able to find were dated over a decade ago, and it is unclear if `-moz-fit-content` is required as of today. I would expect a single `width: fit-content` to work across all browsers.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/fit-content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/fit-content/index.md
* Last commit: https://github.com/mdn/content/commit/66944f622b6b51bc9c24bebbbea242138d910600
* Document last modified: 2023-02-21T05:45:53.000Z

</details>

**Comment by teoli2003** [comment]
Yes, you are right. For now 2 years, all 3 major engines support it. TIme for it to go. I created a PR.
