### ISSUE TITLE
import.meta page is not directly accessible

### ISSUE THREAD

**Issue by linkleonard** [mdn/content#26257]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta

### What specific section or headline is this issue about?

The whole page

### What information was incorrect, unhelpful, or incomplete?

[The import.meta](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta) does not load when directly loaded. However, if I go to [import.meta/resolve](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve) first, and _then_ click on `import.meta` on the breadcrumbs, then I am able to view the content.

### What did you expect to see?

The documentation for `import.meta`

### Do you have anything more you want to share?

When I go to [resolve](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve) first then click on the breadcrumb

![image](https://user-images.githubusercontent.com/7253020/232562148-c3a14280-6f2d-4565-9cce-e23c3b9baf20.png)

When I then reload the page

![image](https://user-images.githubusercontent.com/7253020/232561588-af712ffb-0be8-4643-88af-cd2c33f10563.png)

**Comment by Josh-Cena** [comment]
I am very sure this is because we recently moved to Google Cloud Platform and the host believes `.meta` is an extension and doesn't add the `.html` extension.

cc @caugner

**Comment by Josh-Cena** [comment]
Should be fixed now
