### ISSUE TITLE
For...of link broken

### ISSUE THREAD

**Issue by micahbf** [mdn/content#26260]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

### What information was incorrect, unhelpful, or incomplete?

The link is broken. If you click on the suggested search for "for...of", and then click the top (correct) result, it brings you to the same broken link

### What did you expect to see?

The for...of page

**Comment by Josh-Cena** [comment]
Duplicate of https://github.com/mdn/content/issues/26257
