### ISSUE TITLE
Broken link on SVG <textPath> page

### ISSUE THREAD

**Issue by klossner** [mdn/content#26262]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath

### What specific section or headline is this issue about?

Attributes section: discussion of <path>

### What information was incorrect, unhelpful, or incomplete?

href="[/en-US/docs/Web/SVG/Content_type#path_data](view-source:https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type#path_data)" is a broken link (there's no path_data label on the Content_type page).

### What did you expect to see?

A link that isn't broken? (I'm just now learning SVG, I don't know what should be here.)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/element/textpath`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/textpath/index.md
* Last commit: https://github.com/mdn/content/commit/b4f998244660723175f8e06b5d77f68cfb1d1f1a
* Document last modified: 2023-03-06T23:38:10.000Z

</details>

**Comment by klossner** [comment]
The problem described here has not been fixed. The link is still broken.

**Comment by hamishwillee** [comment]
@klossner It takes a while for changes to be built - so the live site still goes to the wrong place. If you look at the change though, it goes to https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/path#path-data. Should fix itself in a couple of days.

**Comment by teoli2003** [comment]
If it isn't fixed in 2 days, please add a message here and we'll investigate (Usually it is max 24h, but there may be exceptions)

**Comment by klossner** [comment]
The update has appeared, but I don't think it's correct. Two problems:

1) The link in the bug description is from the <textPath> page. The target goes to #path-data, which describes path for animateMotion. It should instead go to #path-data_2 which describes path for textPath.

2) In [https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath), text refers to <path_data> (using an underscore). In [https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/path](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/path), it's <path-data> (using a hyphen). I'm not familiar with the convention used in these documents, but looking at other examples, I suspect that the underscore should change to hyphen.
