### ISSUE TITLE
Safari Support for WindowClient.navigate()

### ISSUE THREAD

**Issue by stephen-hardy** [mdn/content#26264]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WindowClient/navigate

### What specific section or headline is this issue about?

Browser Compatibility

### What information was incorrect, unhelpful, or incomplete?

I think WindowClient.navigate() works in Safari now, at least from what I can tell. I'm not sure when it started working, version-wise, because I hardly see any references to it online.

### What did you expect to see?

Full support listed for Safari 16.4 - or perhaps even earlier versions, if someone has that available to test.

### Do you have any supporting links, references, or citations?

Here is a quick way to test:

https://googlechrome.github.io/samples/service-worker/windowclient-navigate/

Past that, I tried it (from the console) on one of my own sites and it worked fine on Safari desktop and iOS.

### Do you have anything more you want to share?

I'm most curious to know how far back this support goes, but unfortunately I don't have any old devices on which to test. I'm kinda hoping that as a part of verifying this report, somebody will give some indication :)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/windowclient/navigate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowClient/navigate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/windowclient/navigate/index.md
* Last commit: https://github.com/mdn/content/commit/cc070123f72376faec06e36622c4fc723a75325f
* Document last modified: 2023-04-08T06:57:07.000Z

</details>

**Comment by hamishwillee** [comment]
It doesn't appear to work on Safari  15.6 or earlier. it does work on 16.3. I'll update BCD> Thanks for reporting!

**Comment by stephen-hardy** [comment]
Awesome! Thanks for the quick response!

Were you able to test on Safari 16-16.2, or is the status for those versions technically unknown? Just curious for my own dev/release needs. I might be able to find some v16 devices that haven't been updated, somewhere.

**Comment by hamishwillee** [comment]
Hi @stephen-hardy 
I was only able to test on 16.3 and 15.3 - Browserstack holds the last minor version of a particular version. Couldn't find any information in various release notes.

**Comment by stephen-hardy** [comment]
Yeah, I couldn't either. I'll post back here if I find 16.0-16.2 devices to test on.

**Comment by hamishwillee** [comment]
Thanks. Best place to post would be in https://github.com/mdn/browser-compat-data/ if you find an error (or https://github.com/mdn/browser-compat-data/pull/19407 if you find out before it is merged).

**Comment by Josh-Cena** [comment]
Testing support for older Safari versions is always a pain. However, if it's hard for us to run code on old Safari, it's likely going to be hard for users as well, so no reason to worry about it too much. (Apple is rather active at keeping users up-to-date.)

**Comment by stephen-hardy** [comment]
Changes were merged into MDN documentation. Support was proven back to Safari 16.0
