### ISSUE TITLE
Wrong live samples due to ambiguous headers

### ISSUE THREAD

**Issue by mikoMK** [mdn/content#26273]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table

### What specific section or headline is this issue about?

Accessibility concerns - Scoping rows and columns

### What information was incorrect, unhelpful, or incomplete?

The live sample shows all the results from the level 2 header "Examples" instead of the single result from the level 4 header "Examples" under "Accessibility concerns - Scoping rows and columns".
Macro code: `{{EmbedLiveSample('Examples')}}`

### What did you expect to see?

Displaying the correct result for the code sample above it.

### Do you have anything more you want to share?

The same problem occurs on other pages with the same structure. For example: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr#accessibility_concerns

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/26312
