### ISSUE TITLE
Intl.Locale info getters changed to methods

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#26288]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale

### What information was incorrect, unhelpful, or incomplete?

The mention of the following getters:

`calendars`, `collations`, `hourCycles`, `numberingSystems`, `timeZones`, `textInfo`, `weekInfo`.

### What did you expect to see?

They have been changed into methods: https://github.com/tc39/proposal-intl-locale-info/pull/67

The spec URLs have been removed in BCD: https://github.com/mdn/browser-compat-data/pull/19392

### Do you have any supporting links, references, or citations?

This change has been implemented in JSC: https://github.com/WebKit/WebKit/pull/10241

V8 bug: https://bugs.chromium.org/p/v8/issues/detail?id=13835&q=locale%20info&can=2

SpiderMonkey doesn't implement the locale-info proposal yet.

**Comment by OnkarRuikar** [comment]
We have to keep the property pages as it is till two years after all the browsers drop support. [[ref](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features)]

Instead we need to create new pages for methods. And put warnings on property pages saying use methods now.

**Comment by Josh-Cena** [comment]
Yes, that's the plan I think

**Comment by teoli2003** [comment]
An alternative is to keep one page and say they are methods, but some browsers implement them as properties (and once all have updated their implementation, only keep it into bcd.

**Comment by Josh-Cena** [comment]
Not sure what I should do: redirect, or new pages? I am leaning to redirects because more pages is more trouble.

**Comment by Elchi3** [comment]
> I am leaning to redirects because more pages is more trouble. Just want to make sure that everyone's comfortable with this—if so, the BCD will be changed by moving the feature and adding a note saying in certain versions it's implemented under the alternative name as an accessor property.

I'm comfortable with this and I think we have acted similar on previous cases like this.
