### ISSUE TITLE
Problem with window.devicePixelRatio example

### ISSUE THREAD

**Issue by dhoulder** [mdn/content#26316]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

### What specific section or headline is this issue about?

Example code does not match description

### What information was incorrect, unhelpful, or incomplete?

The page says…

> The updatePixelRatio() function fetches the current value of devicePixelRatio, then sets the [innerText](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText) of the element pixelRatioBox to a string which displays the ratio both as a percentage and as a raw decimal value with up to two decimal places.

No it doesn't. The innerText modification was removed in
https://github.com/mdn/content/commit/674f6853d42f54719143adea2c78623826d74190

As a result the text…

> This example demonstrates the effect of zooming the page in and out (or moving it to a screen with a different scaling factor) on the value of the property Window.devicePixelRatio. Try it and watch what happens! 

… is also wrong.

Thanks

### What did you expect to see?

The device pixel ratio in the ```Result``` box

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/devicepixelratio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/devicepixelratio/index.md
* Last commit: https://github.com/mdn/content/commit/cc070123f72376faec06e36622c4fc723a75325f
* Document last modified: 2023-04-08T06:57:07.000Z

</details>

**Comment by Josh-Cena** [comment]
cc @dawei-wang
