### ISSUE TITLE
white-space live sample text has different line breaks than HTML sample lorem ipsum

### ISSUE THREAD

**Issue by shawnjones253** [mdn/content#26338]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

### What specific section or headline is this issue about?

in_action

### What information was incorrect, unhelpful, or incomplete?

The "lorem ipsum" HTML sample has different line breaks than the actual HTML used in the live sample "result"

### What did you expect to see?

The HTML sample and the HTML used in the EmbedLiveSample should be the same

### Do you have any supporting links, references, or citations?

Compare: 

https://github.com/mdn/content/blob/main/files/en-us/web/css/white-space/index.md#html

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/white-space`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/white-space/index.md
* Last commit: https://github.com/mdn/content/commit/b82ff59aab7883b7bb2222cf9f9f9b6eed818e08
* Document last modified: 2023-02-21T06:13:19.000Z

</details>

**Comment by yarusome** [comment]
If by "HTML sample" you mean the presented layout of this text, see [How whitespace is handled by HTML, CSS, and in the DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace).
