### ISSUE TITLE
Issue with "Working with JSON": (short summary here please)

### ISSUE THREAD

**Issue by mjbmon** [mdn/content#2634]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON

#### What information was incorrect, unhelpful, or incomplete?
Your examples are fine except for one major error: they are surrounded by single quotes (') which make them invalid JSON.

#### Specific section or headline?
"JSON structure" and "Arrays as JSON"

#### What did you expect to see?
Valid JSON.

#### Did you test this? If so, how?
Yes, cut and paste into JSONLint online validator.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/objects/json`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/json/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by CreaTorAlexander** [comment]
So you mean

```
'{
^ // Should be Double quote?  
 "squadName": "Super hero squad",
  "homeTown": "Metro City",
  "formed": 2016,
  "secretBase": "Super tower",
  "active": true,
  "members": [
    {
      "name": "Molecule Man",
      "age": 29,
      "secretIdentity": "Dan Jukes",
      "powers": [
        "Radiation resistance",
        "Turning tiny",
        "Radiation blast"
      ]
    },
    {
      "name": "Madame Uppercut",
      "age": 39,
      "secretIdentity": "Jane Wilson",
      "powers": [
        "Million tonne punch",
        "Damage resistance",
        "Superhuman reflexes"
      ]
    },
    {
      "name": "Eternal Flame",
      "age": 1000000,
      "secretIdentity": "Unknown",
      "powers": [
        "Immortality",
        "Heat Immunity",
        "Inferno",
        "Teleportation",
        "Interdimensional travel"
      ]
    }
  ]
}'
^^ And here?
```

**Comment by chrisdavidmills** [comment]
That is really strange. I don't know how they got there, and I wrote this article originally...I've fixed it : https://github.com/mdn/content/commit/8a74912fd92a0e0e4f09fba7408ef4bee1f966ca

Thanks for reporting!
