### ISSUE TITLE
Error in Document.querySelectorAll () examples

### ISSUE THREAD

**Issue by acer21** [mdn/content#2635]
The first two examples of how "**Document.querySelector ()**" works are reversed

**Comment by CreaTorAlexander** [comment]
Do you mean on this site? https://developer.mozilla.org/de/docs/Web/API/Document/querySelector

**Comment by chrisdavidmills** [comment]
Which page are you finding this problem with, and what headlines are the examples under that you are claming are reversed?

**Comment by CreaTorAlexander** [comment]
Checked this page https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll 

But I can not found reversed examples.

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander if you can't find the problem either, let's just close this. Thanks for checking it out.
