### ISSUE TITLE
FF86 Release notes missing WebGL improvements?

### ISSUE THREAD

**Issue by polarathene** [mdn/content#2636]
Several articles on this release mention WebGL performance improvements, one claiming them to be quite notable because of moving the logic to it's own thread, when viewing the release notes this information is lacking.

I looked at the source [here](https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/86/index.html) and went through commit history and there seems to never have been any trace of that information related to FF86 release.

Can you please confirm if this improvement made it through to the 86.0 release?

**Comment by chrisdavidmills** [comment]
@polarathene I try to report all notable web platform changes in the release notes, based on the information I am given or can find, but I didn't see anything about this.

I've just had a look in the Firefox engineering team internal tracking tool, and can see an entry related to WebGL drawing to the GPU Process / out-of-process WebGL— I guess this is what you are talking about.

It looks like it has made the 86 release, yes.

I can add a note to the MDN release notes if you think it would help. Where did you read about this?

**Comment by polarathene** [comment]
> I can add a note to the MDN release notes if you think it would help.

I'm alright, I was just seeking confirmation that it did make it to through to the release unlike the AVIF feature that got pulled/delayed for a future release.

> Where did you read about this?

[Phoronix](https://www.phoronix.com/scan.php?page=news_item&px=Firefox-86-Released) briefly touched on it and is my main news source for linux related news.

[Linux Reviews](https://linuxreviews.org/Firefox_86_Is_Released_With_Drastically_Improved_WebGL_Performance#Vastly_Improved_WebGL_Performance) came up via Google search when seeking more information after finding nothing in the release notes. It details the improvement much better and you can probably reference that if appending to release notes.
- There's also some benchmark results comparing performance to FF84 and FF85 releases as well as among other chromium browsers with WebGL, although they don't mention if it's X11/XWayland or Wayland (which I hear with supporting DMA-BUF driver can perform quite nicely?).

**Comment by chrisdavidmills** [comment]
> I'm alright, I was just seeking confirmation that it did make it to through to the release unlike the AVIF feature that got pulled/delayed for a future release.

Yeah, that totally makes sense. I can see AVIF was mis-reported at one of the URL you included. Although you can't blame them too much. It was on our release notes until 24 hours before the actual release.

I'm going to do some digging with the engineering teams to ask about this further. I'm pretty sure the GPU thread improvements for WebGL were put into 86, but Canvas on GPU is not yet enabled in release.

**Comment by chrisdavidmills** [comment]
I've checked it out, and yes, it was enabled in release for Windows and macOS. the Linux rollout will be slightly later, AIUI.

I don't think I'm going to add this to MDN rel notes, at least not for now. We don't usually report on performance improvements for existing features, just new web platform features.

**Comment by polarathene** [comment]
> the Linux rollout will be slightly later, AIUI.

Oh.... so the improvement didn't make it to the linux release? That Linux Reviews link is reporting on improvements in WebGL performance from something different in FF86? Or was it in linux beta perhaps?

> We don't usually report on performance improvements for existing features, just new web platform features.

It seemed to be a notable improvement of 2x in their results which I'd think would be worth reporting in release notes if that were the case, I think that may have been covered in the past for major WASM performance improvements once, and maybe WebRender?

As it didn't make it to the linux build and that's all I wanted to confirm, I'm not fussed about the release notes being updated, just curious where the review sites got that information, perhaps they were keeping an eye on development activity but as a result have published some misleading information. Cheers!
