### ISSUE TITLE
Font link is invalid

### ISSUE THREAD

**Issue by petrushya** [mdn/content#26387]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Accessibility_troubleshooting

### What specific section or headline is this issue about?

ZIP containing the files that comprise the example

### What information was incorrect, unhelpful, or incomplete?

href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Sonsie+One"

### What did you expect to see?

Good  value  for attribute href on element link from "the w3c markup validation service".

### Do you have any supporting links, references, or citations?

Bad value https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Sonsie+One for attribute href on element link: Illegal character in query: | is not allowed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/accessibility/accessibility_troubleshooting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Accessibility_troubleshooting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/accessibility/accessibility_troubleshooting/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by mikoMK** [comment]
I had a quick look at how Google Fonts handles multiple fonts nowadays. "Open Sans Condensed" isn't available anymore through the "css2" end point, but when selecting "Open Sans" with the same weight, it looks like this:

HTML
```html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Sonsie+One&display=swap" rel="stylesheet">
```
CSS
```css
font-family: 'Open Sans', sans-serif;
```

This `href` passes the W3C HTML validator.

**Comment by petrushya** [comment]
If you encode "|" in ASCII format, `href` also passes W3C validation. The question is, what is true now and whether something needs to be fixed in `index.html` and `style.css` included in the zip file. Browsers open `href` in any form:
```
https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Sonsie+One
https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300%7CSonsie+One
https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&family=Sonsie+One&display=swap
```

**Comment by Josh-Cena** [comment]
I believe URL-encoding it is good enough. To do so you would need to edit `mdn/learning-area` though.

**Comment by Phil-G-94** [comment]
Hi @Josh-Cena, work still needs to be done on this? 

I can help with the edits if you point me in the right direction re URL-encoding (I'm an absolute newbie contributor).

**Comment by letsbecometechie** [comment]
Hi @Josh-Cena, is this still open?
If yes can you please assign it to me? I can take it up 👍
