### ISSUE TITLE
Issue with "Third-party APIs": …

### ISSUE THREAD

**Issue by webdev4422** [mdn/content#264]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs

#### What information was incorrect, unhelpful, or incomplete?
On YouTube section, the information about API key is not complete.

#### Specific section or headline?
YouTube example
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs#YouTube_example

#### What did you expect to see?
An item in requirements list, that tell me to enable (status  ON) the "YouTube Data API v3" on GCP APIs page.  

#### Did you test this? If so, how?
I was unable to load video from YouTube API from MDN guide, but after enabling YouTube Data API v3 (following this guide: https://developers.google.com/youtube/v3/getting-started)  - it started to work.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/third_party_apis`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/javascript/client-side_web_apis/third_party_apis/index.html
* Report started: 2020-12-15T21:14:23.152Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5822 with an update to the article. It would be great if you’re able to review that and confirm it’s now accurate.
