### ISSUE TITLE
Issue with content 

### ISSUE THREAD

**Issue by MrHeartBreaker** [mdn/content#26406]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:last-child

### What specific section or headline is this issue about?

Examples - Basic Example

### What information was incorrect, unhelpful, or incomplete?

The frame does not match with Basic Example 

The frame of styling a list is there in basic example frame;

misplace of frames;

### What did you expect to see?

Output of basic example code

### Do you have anything more you want to share?

none

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_last-child`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:last-child
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_last-child/index.md
* Last commit: https://github.com/mdn/content/commit/5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e
* Document last modified: 2023-02-21T06:49:52.000Z

</details>

**Comment by bsmth** [comment]
Hi @MrHeartBreaker - could you provide more details of what you would expect to see? The example looks like it's working as intended to me.

If you are expecting the last `<p>` element to be selected, there are two `<div>` elements to demonstrate the 'sibling' concept, does that make sense?

**Comment by MrHeartBreaker** [comment]
Hello @bsmth 
Few hours back the example was not appearing properly. Maybe issue was from my end. Sorry for the inconvenience.

**Comment by bsmth** [comment]
No problem, glad it's resolved :)
