### ISSUE TITLE
Issue with ISO 8601 compatibility

### ISSUE THREAD

**Issue by johallorb** [mdn/content#26422]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

### What specific section or headline is this issue about?

Date Time String Format

### What information was incorrect, unhelpful, or incomplete?

The date time string format does not appear to accept all parts of the ISO 8601 standard; this is with regards specifically to the time zone offset 'Z'. It appears that ±hh is part of the ISO 8601 standard, but when I attempted to use ±hh for my date time string, the parser returned NaN. However, by concatenating ':mm' to the time zone offset, the parser recognized the date.

It is misleading to state that the parser will recognize dates in the ISO 8601 format when it only recognizes date time strings from a subset of the ISO 8601 format.

For example; if you set the 'javaScriptRelease' in the example on the page to the string 1995-12-04T00:12:00+00, the parser returns NaN. If you set it to 1995-12-04T00:12:00+00:00, the parser returns 818035920000 (as expected).

### What did you expect to see?

A list of which ISO 8601 formats are recognized, and which ones are not recognized.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/parse`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/parse/index.md
* Last commit: https://github.com/mdn/content/commit/c6dbc4ff96451887b908b46c8e70bcfec1c2c48c
* Document last modified: 2023-02-26T04:54:36.000Z

</details>

**Comment by Josh-Cena** [comment]
I will be working on this page as I address https://github.com/mdn/content/issues/21188. For now you can read https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format. The only supported offset format is `±HH:mm`.
