### ISSUE TITLE
Update the PWA Badging How-To page based on a new WebKit blog

### ISSUE THREAD

**Issue by captainbrosset** [mdn/content#26430]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Display_badge_on_app_icon

### What information was incorrect, unhelpful, or incomplete?

The WebKit team recently published a very useful blog post about bading on iOS: https://webkit.org/blog/14112/badging-for-home-screen-web-apps/

Reading through it made me realize that I had missed an important aspect in this [new PWA How-to page](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Display_badge_on_app_icon) on MDN: that notification permission is required before being able to use the badging API.

We should go back and edit the page to add this information in.

@marcoscaceres by any chance, would you be interested in taking on this issue? If not, I'll eventually get to it, but it might be some time before I do.
Of course, anyone else is more than welcome to work on this!

### What did you expect to see?

Information that user permission is required, and how to request it.

### Do you have any supporting links, references, or citations?

https://webkit.org/blog/14112/badging-for-home-screen-web-apps/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/progressive_web_apps/how_to/display_badge_on_app_icon`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Display_badge_on_app_icon
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/how_to/display_badge_on_app_icon/index.md
* Last commit: https://github.com/mdn/content/commit/eaaec82a1cf81794626de7fcc02d9c26596070bf
* Document last modified: 2023-04-05T14:32:49.000Z

</details>

**Comment by kevinctofel** [comment]
I’d like to work on this as a firs-timer and dev in training. I’ll start working on my PR today if this is acceptable. Cheers!
