### ISSUE TITLE
Redundancy in the descriptions of various hue-related CSS color functions

### ISSUE THREAD

**Issue by yarusome** [mdn/content#26435]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl

### What specific section or headline is this issue about?

Values

### What information was incorrect, unhelpful, or incomplete?

[`hsl()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl), [`hwb()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb), [`lch()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lch), [`oklch()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch) explain to various depths on their `<hue>` components. Although these functions designate (slightly) different angles for the same colors, much of the details are already covered by the [`<hue>`](https://developer.mozilla.org/en-US/docs/Web/CSS/hue) page. (This page even uses the same diagram as that on the `hsl()` page.)

### What did you expect to see?

I propose to replace the descriptions on each function's page with a reference to `<hue>`, and add a few lines above the "Syntax" section on the `<hue>` page to explain for the Oklab colorspace. I'd make a PR soon if no further ideas.

**Comment by yarusome** [comment]
@bsmth There'd probably be a merge conflict with any PR to resolve #26434. Could I wait until that gets resolved first?

**Comment by bsmth** [comment]
> Could I wait until that gets resolved first?

Sounds like a plan, let's wait until the other issue is resolved 👍🏻

**Comment by yarusome** [comment]
@bsmth Because all gradient function (e.g. [`linear-gradient()`](https://drafts.csswg.org/css-images-4/#linear-gradients)) syntaxes now have the `<colorspace-interpolation-method>` component, which includes `<hue-interpolation-method>`, it seems reasonable to relocate the description for the hue interpolation method on the [`color-mix()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix#using_hue_interpolation_methods) page to the `<hue>` page itself, plus a bit more explanations.

If everything seems OK, I'd start working on this issue for the coming days.

**Comment by bsmth** [comment]
> relocate the description for the hue interpolation method on the [`color-mix()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix#using_hue_interpolation_methods) page to the `<hue>` page itself, plus a bit more explanations.

That would be really great. Please assign me / add me as a reviewer if you like 👍🏻

**Comment by yarusome** [comment]
@bsmth For the explanation to `<hue-interpolation-method>`, I constructed the following diagrams (I hope they look good in both light and dark mode):

> If `θ1' < θ2'`:
> | `shorter` / `increasing` | `longer` / `decreasing` |
> | :----------------------: | :---------------------: |
> | ![shorter_increasing](https://github.com/mdn/content/assets/97945148/9c3e2cfe-c7b2-4f5f-b2bc-2624237bf6b2) | ![longer_decreasing](https://github.com/mdn/content/assets/97945148/2eb840b9-4621-4deb-81aa-6fa8da8a58f6) |

Do you think these diagrams lack anything or could remove any elements?

**Comment by bsmth** [comment]
The diagrams look really great, well done! I checked in dark mode and the white background is better than transparency, so I wouldn't worry about that. Some questions about the info shown:

* First glance I would assume that `shorter` == `increasing` always, but you call this out beforehand `if θ1' < θ2'` - as long as we have this in the prose that decreasing/increasing will be either shorter or longer depending on the angles.
* Should we use clockwise rotation around the color wheel? Most of the [existing diagrams](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl#values) use red at 0deg (north) or am I mistaken? So increasing from [`0deg` to `180deg` (increasing)](https://codepen.io/bsmth/pen/wvYdvQB) would be a clockwise operation, what do you think?

**Comment by yarusome** [comment]
@bsmth It turns out that I inadvertently used the math convention of angles when drawing. So below is the correct diagram for `shorter` / `increasing` as you noted:

![new](https://github.com/mdn/content/assets/97945148/2c01d2ce-99f5-4199-a5a3-13a1d0b9edc2)

(I also changed from Oklch to HSL for a more traditional distribution of colors.)

**Comment by yarusome** [comment]
On a second thought, given that all gradient functions and `color-mix()` rely on `<color-interpolation-method>`, which in turn relies on `<hue-interpolation-method>`, *maybe* it's better to document these two data types on their own pages and refer to `<hue-interpolation-method>` from `<hue>`. Does this sound OK to you, @bsmth?

**Comment by bsmth** [comment]
The new diagrams look perfect to me 👍🏻.

Regarding `<hue-interpolation-method>` page, maybe this is the best way forward seeing as you pointed out we have **color** and **hue** interpolation which look mixed up on the `color-mix()` page at the moment.

**Comment by bsmth** [comment]
This was a great cleanup and refresh, @yarusome - congrats on the additions 👍🏻
