### ISSUE TITLE
It is unclear why background-attachment: fixed is said to be incompatible with background-clip: text

### ISSUE THREAD

**Issue by Kaiido** [mdn/content#26445]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment#values

### What information was incorrect, unhelpful, or incomplete?

The `fixed` section says

> (This is not compatible with [background-clip: text](https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip#values).)

However, by looking at the[ linked specs](https://w3c.github.io/csswg-drafts/css-backgrounds/#the-background-attachment), there doesn't seem to be anything suggesting so. Even [MDN's `background-clip`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip) article doesn't mention this.  

And [when testing](https://jsfiddle.net/7qasmcnb) it seems that both Safari and Chrome do handle it correctly, but it's true that apparently Firefox is buggy here (we need to [force a recalc](https://jsfiddle.net/7qasmcnb/1/) when scrolling). But that sounds just like a Firefox bug, and not a true -by design- limitation of the API.

### What did you expect to see?

Either a note in the compatibility table stating that Firefox has this bug, if it's indeed a known bug, and a link to the bugzilla issue, or a clear pointer to the specs that states that this combination is indeed not supposed to work, and in that case the same note in the `background-clip` article.  

### Do you have any supporting links, references, or citations?

I don't but that's kind of the point, I am requesting for such links, references, or citations to support the current claim.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/background-attachment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/background-attachment/index.md
* Last commit: https://github.com/mdn/content/commit/42c1bb8c259f3f57de9f38600776cf273e3addda
* Document last modified: 2023-02-21T06:27:49.000Z

</details>

**Comment by OnkarRuikar** [comment]
From the specifications point of view, the `text` value of the `background-clip` property hasn't been fully ironed out yet. Hence, it's still experimental:

> Well, recall that this property value was introduced unilaterally by one browser, meant for internal usage but exposed to the wider web, without any spec whatsoever nor particular effort on the part of that browser's engineers to specify it. Sometimes that sort of thing still works out quickly when others do the legwork, but sometimes it falls thru the cracks. This is particularly the case when the feature itself is bad, as this one is. (The use-case is great, but the way this feature solves it is bad, as it fails inaccessibly - if the image doesn't load, you're left with unreadable transparent text.) The only reason we're specifying it at all is that it's used widely enough on the public web that browsers need to support it. [[ref](https://github.com/w3c/csswg-drafts/issues/9907#issuecomment-1930785584)].

> As far as I know, the value text for background-clip is still considered experimental, it doesn't exist at all in the spec you linked to ([css-backgrounds-3]) and was introduced only [in [css-backgrounds-4]](https://drafts.csswg.org/css-backgrounds-4/#background-clip) which is marked "not ready for implementation". There are some useful notes on the history of this value in the https://github.com/w3c/csswg-drafts/issues/9907#issuecomment-1930785584. Firefox has "backported" this value for the most popular use cases only. Likely Chrome's behavior is "more correct", but it's hard to file bugs against browsers until this value is specified properly. [[ref](https://github.com/w3c/csswg-drafts/issues/10595#issuecomment-2246141459)]

I think the claim `(This is not compatible with background-clip: text.)` is not substantial and should be removed.
