### ISSUE TITLE
console.log(eval("3 + 5")); blocked by CSP error right off the bat. 

### ISSUE THREAD

**Issue by vwb3** [mdn/content#26458]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Introduction

### What specific section or headline is this issue about?

example console.log(eval("3 + 5")); firefox and mozilla run, CSP error

### What information was incorrect, unhelpful, or incomplete?

first javascript console example doesn't run. 
console.log(eval("3 + 5"));
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). debugger eval code:1
Uncaught EvalError: call to eval() blocked by CSP

### What did you expect to see?

8 printed on console. 

### Do you have anything more you want to share?

Not helpful as the first javascript code example that doesn't run. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/introduction/index.md
* Last commit: https://github.com/mdn/content/commit/4ab9dd7b9d2488b242859afa8da3e0e9aab5db31
* Document last modified: 2023-03-29T23:58:14.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! This is not an example for you to run; it's a demonstration of what entering `3 + 5` in the console is actually running behind the scenes.

**Comment by vwb3** [comment]
I get it. It has a ‘copy to the clipboard’ icon to the right of code snippet:
console.log(eval("3 + 5"));
I’ll be sure not to copy the code to the clipboard and run it.
My bad.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
