### ISSUE TITLE
Add Screen Orientation API overview page to GroupData.json

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#2645]
We have an overview page for the Screen Orientation API: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Orientation_API but it's not listed in the "overview" property of the  [GroupData.json](https://github.com/mdn/kumascript/blob/master/macros/GroupData.json) entry:

```json
        "Screen Orientation API": {
            "guides":     [ "/docs/Web/API/CSS_Object_Model/Managing_screen_orientation" ],
            "interfaces": [ "ScreenOrientation" ],
            "methods":    [],
            "properties": [ "Screen.orientation"],
            "events":     []
        },
```

We need to add an "overview" property to this entry like:

```json
        "Screen Orientation API": {
            "overview":   [ "Screen Orientation API" ], 
            "guides":     [ "/docs/Web/API/CSS_Object_Model/Managing_screen_orientation" ],
            "interfaces": [ "ScreenOrientation" ],
            "methods":    [],
            "properties": [ "Screen.orientation"],
            "events":     []
        },
```

Then we will get a link to the overview page in the list at https://developer.mozilla.org/en-US/docs/Web/API#Specifications and in API sidebars generated using [APIRef.ejs](https://github.com/mdn/kumascript/blob/master/macros/APIRef.ejs).

**Comment by teoli2003** [comment]
@escattone Sorry if I missed the PR, but does yari use the GroupData.json of mdn/content or the one on mdn/yari right now? (I remember that the move was partially done when Peter left)

**Comment by escattone** [comment]
> @escattone Sorry if I missed the PR, but does yari use the GroupData.json of mdn/content or the one on mdn/yari right now? (I remember that the move was partially done when Peter left)

@teoli2003 The move of those data JSON files is complete. It uses the JSON files (including `GroupData.json`) in `mdn/content`.

**Comment by teoli2003** [comment]
\o/ Thanks!
