### ISSUE TITLE
webpage or web page

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#26461]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/Pages_sites_servers_and_search_engines

### What information was incorrect, unhelpful, or incomplete?

I found this page trying to determine if it is correct to say "webpage" or "web page".  But this page has both!  Would it not be proper to be consistent?  I also see an inconsistency in "website" vs "web site".

### What did you expect to see?

consistent presentation

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/common_questions/web_mechanics/pages_sites_servers_and_search_engines`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/Pages_sites_servers_and_search_engines
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/web_mechanics/pages_sites_servers_and_search_engines/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by dawei-wang** [comment]
HI @JustinWebDev, per the [Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/web-world-wide-web-www), webpage and website are the correct terms to use. I'll go ahead and make a PR for this change.
