### ISSUE TITLE
Add API overview page for Geometry Interfaces

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#2647]
GroupData.json lists "Geometry Interfaces" as a Web API with the following contents:

```json
        "Geometry Interfaces": {
            "interfaces": [ "CSSMatrix",
                            "DOMMatrix",
                            "DOMMatrixReadOnly",
                            "Point" ],
            "methods":    [],
            "properties": [],
            "events":     []
        },
```

...but it doesn't have an API overview page. We should write a page and add the "overview" property to GroupData.

**Comment by sideshowbarker** [comment]
As this has been open for more than 2 years, I suggest labeling it with `backlog` and closing it for now.

**Comment by wbamberg** [comment]
I'm not sure I agree with this policy. I don't think having fewer open issues is beneficial if it means we just have more things to track in other places. It's a kind of sleight of hand.

This is still an issue, clearly stated, that people can take and work on. FWIW I fixed a very similar one, also filed > 2 years ago, about 3 weeks ago: https://github.com/mdn/content/issues/2648.
