### ISSUE TITLE
Add API overview page for File API

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#2648]
GroupData.json lists "File API" as a Web API with the following contents:

```json
        "File API": {
            "guides":     [ "/docs/Using_files_from_web_applications",
                            "/docs/Extensions/Using_the_DOM_File_API_in_chrome_code" ],
            "interfaces": [ "File",
                            "FileList",
                            "FileReader",
                            "FileReaderSync",
                            "Blob" ],
            "methods":    [],
            "properties": [],
            "events":     []
        },
```

...but it doesn't have an API overview page. We should write a page and add the "overview" property to GroupData.

**Comment by Ryuno-Ki** [comment]
Remember? We had a bugfix the other day, that was reported 20 years ago …!

**Comment by himanshugarg** [comment]
Does [this](https://developer.mozilla.org/en-US/docs/Web/API/File) qualify for the requested API overview page?

**Comment by teoli2003** [comment]
No this is the interface page of File. The File API is not only this interface, but several others.
Here is an `http://localhost:5000/en-US/docs/Web/API/Background_Fetch_API` of a simple overview page.

**Comment by wbamberg** [comment]
I'm actually going to fix this, this time.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/pull/16801 \o/
