### ISSUE TITLE
Styling or not codes in section headings?

### ISSUE THREAD

**Issue by yarusome** [mdn/content#26481]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Sizing#min-width_and_min-height_example

### What information was incorrect, unhelpful, or incomplete?

Many section headings contain short codes (e.g. for function or variable names), but some codes are wrapped in code blocks while others are not. For example:

  1. [Logical properties for sizing](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Sizing#min-width_and_min-height_example): The `min-*` CSS properties appear bare in the heading, and the first property is thus uppercased.
  2. [`log()`](https://developer.mozilla.org/en-US/docs/Web/CSS/log#sizes_based_on_log_function): The `log()` CSS function is wrapped in a code block in the heading.

The Heading levels [section](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#heading_levels) in the Writing style guidelines only states that:

> **Don't use inline styles, classes, or macros within headings.** However, you can use backticks to indicate code terms (e.g. "Using `FooBar` interface").

which results in the inconsistency since it's not definitive (as "you can" instead of "you should").

### What did you expect to see?

In my opinion, changing "you can" to "you should" (or "you must") here is the right option in order to:

  1. more clearly distinguish codes from normal texts;
  2. prevent incorrect uppercasing when function or variable names are at the start.

### Do you have anything more you want to share?

This inconsistency causes recurrent troubles for the l10n work.

**Comment by wbamberg** [comment]
Yes, [we had this discussion](https://github.com/orgs/mdn/discussions/271) and [updated the meta-docs to say "could"](https://github.com/mdn/content/pull/22472/files), but I agree, "should" would be better.

**Comment by hamishwillee** [comment]
I added a note to https://github.com/mdn/content/pull/26500#discussion_r1181319637 - my concern is that in many cases we do not. If we're going to make a "should" statement then we need to explicitly decide/state at least some of the glaring exceptions or change the. For example: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/accessKey

PS FWIW I think "should" is better. In particular in guide.
