### ISSUE TITLE
CSS @layer try-it does not work

### ISSUE THREAD

**Issue by leeyc0** [mdn/content#26502]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@layer

### What specific section or headline is this issue about?

Try-It

### What information was incorrect, unhelpful, or incomplete?

It appears the try-it box has its built-in .warning class, which overrides the .warning class in the try-it box. I have to rename the CSS class zombiewarning to make it work.

Please fix the try-it example by renaming the class to zombiewarning in both HTML and CSS.

### What did you expect to see?

As above, the CSS try-it box should work as intended

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@layer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@layer/index.md
* Last commit: https://github.com/mdn/content/commit/77eea2b80f7352068ed59a2c2fb03de4ed85e194
* Document last modified: 2023-03-23T13:48:47.000Z

</details>

**Comment by leeyc0** [comment]
Found the appropriate repo to create PR, will close this issue then.

**Comment by yarusome** [comment]
This issue should be left open and only closed by the linked PR.
