### ISSUE TITLE
Page Structures/Banners and notices may need rewording

### ISSUE THREAD

**Issue by jasonren0403** [mdn/content#26515]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Banners_and_notices

### What specific section or headline is this issue about?

How to add notice boxes

### What information was incorrect, unhelpful, or incomplete?

We don't use page tags anymore, and I have removed some occurrences in #25412. However, there are still some mentions and I am not sure how to reword or rewrite them. This somehow block the localization of the document.

> To do this, you insert the macro call at the top of the article, **and add the new tag to the list**. Once you've done that, raise a pull request and get your changes reviewed and merged. From then on, an appropriate banner will appear on the page, and **any macros that reference page tags** when looking for up-to-date articles will know that the page you've updated is deprecated, or whatever.

### What did you expect to see?

Reworded guides of 'how to add notices boxes' with up-to-date information.

### Do you have any supporting links, references, or citations?

Discussion under mdn/translated-content#13048 (in Chinese)

### Do you have anything more you want to share?

Maybe other document under 'Page Structures' need a similar update

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/writing_guidelines/page_structures/banners_and_notices`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Banners_and_notices
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
* Last commit: https://github.com/mdn/content/commit/ac5e8cb64f00cf8661a18d6fa6ebe057f646793b
* Document last modified: 2023-03-17T08:31:01.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. I've created an updated version (the banners don't depend on front metadata currently, though they should be auto inserted based on that metadata if it were up to me :-)). Let's see if that gets through.
