### ISSUE TITLE
Incorrect description of |. Bitwise OR not "pipe symbol"

### ISSUE THREAD

**Issue by blindman67** [mdn/content#26539]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/GPUCanvasContext/configure

### What specific section or headline is this issue about?

Parameters usage

### What information was incorrect, unhelpful, or incomplete?

Note that multiple possible usages can be specified by separating values with pipe symbols, for example:

### What did you expect to see?

Note that multiple possible usages can be specified using the bitwise OR operator, for example:

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/gpucanvascontext/configure`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/GPUCanvasContext/configure
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/gpucanvascontext/configure/index.md
* Last commit: https://github.com/mdn/content/commit/b6984118ac9482e683a654edfefa4b426ca3c7ca
* Document last modified: 2023-04-07T06:03:34.000Z

</details>

**Comment by advitiya7** [comment]
@Josh-Cena can you explain the issue like what all changes have to be made?

**Comment by Josh-Cena** [comment]
Yes, the issue description tells you exactly what to change and what to change it to.
