### ISSUE TITLE
Document <hr>-in-<select>

### ISSUE THREAD

**Issue by annevk** [mdn/content#26536]
As per https://github.com/whatwg/html/pull/9124 we plan on allowing `<hr>` to be used in `<select>`. Rendering-wise this already works in Chromium and WebKit (at least on macOS), but the HTML parser changes are what will make it truly useful to web developers.

**Comment by hamishwillee** [comment]
Note: The FF bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1830909 (more info in whatwg/html link provided above).

**Comment by postmeback** [comment]
As the PR got merged, this issue is good to close.

**Comment by Josh-Cena** [comment]
@postmeback There's no action taken on MDN side yet.

**Comment by Josh-Cena** [comment]
Fixed in https://github.com/mdn/content/issues/31109
