### ISSUE TITLE
Document scroll driven animations

### ISSUE THREAD

**Issue by estelle** [mdn/content#26544]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scroll_animations

### What specific section or headline is this issue about?

missing module landing page

### What information was incorrect, unhelpful, or incomplete?

https://w3c.github.io/csswg-drafts/scroll-animations/ needs a module landing page at 

We already have documentation for:
- [animation-timeline](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline) property
- [scroll-timeline](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline) shorthand property
- [scroll-timeline-axis](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline-axis)
- [scroll-timeline-name](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline-name) property

### What did you expect to see?

a module landing page.

**Comment by rachelandrew** [comment]
@estelle are you working on this? We (Chrome) are intending to ship this in [115](https://chromestatus.com/feature/6752840701706240). Before I add this to our docs list, I wanted to check if it was already in progress. We have a comprehensive article, currently in PR, as well, with lots of examples.

**Comment by estelle** [comment]
@rachelandrew Not yet. I added an "issue" so it doesn't fall thru the cracks. Realized the module landing page was not documented as I was working on scroll snap.

I am currently working on updating all the module landing pages. See https://github.com/openwebdocs/project/issues/147 for a list of "to do" items, which also shows what has already been completed. A good example for this module is https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations as that includes events.

**Comment by chrisdavidmills** [comment]
@estelle I was planning on having a go at this one next. Can you assign it to me?

**Comment by estelle** [comment]
Thanks @chrisdavidmills. I assigned this issue to you. Please take a look https://github.com/openwebdocs/project/issues/147 - the pages with checkmarks are in the newer format: 

1. brief description introducing the module's capabilities
2. As part of the description, a "X in action" demonstration example where X is the module (h3)
3. **Reference** section, including the properties, data types, glossary, events, interfaces defined in the spec.
4. **Guides**, MDN guides, learn, etc. that are on MDN
5. **Related concepts**, including properties all the above very relevant to the spec, but defined elsewhere.
6. **Specification**
7. **See also**; with links to the related modules (where the related concepts come from), tutorials and guides for those related concepts, and external links.
