### ISSUE TITLE
Navigation Buttons Missing

### ISSUE THREAD

**Issue by codetalker7** [mdn/content#2655]
It looks like the "Previous" and "Next" navigation buttons are missing at the bottom of [this](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Concepts) page.

**Comment by chrisdavidmills** [comment]
Well spotted, thanks for erporting this @codetalker7 !

I've added them in; see https://github.com/mdn/content/commit/9ac92e59230ba51bd3212e8976fd36e0d431a372
