### ISSUE TITLE
Issue with "Document and website structure": (Typo)

### ISSUE THREAD

**Issue by martian1431** [mdn/content#2658]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure

#### What information was incorrect, unhelpful, or incomplete?
aformentioned

#### Specific section or headline?
HTML layout elements in more detail

#### What did you expect to see?
aforementioned

#### Did you test this? If so, how?
I googled the word but couldn't matching results

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/document_and_website_structure`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/document_and_website_structure/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this 👍

**Comment by martian1431** [comment]
Okay cool.
