### ISSUE TITLE
Non-standard system color extensions

### ISSUE THREAD

**Issue by yarusome** [mdn/content#26596]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/system-color

### What specific section or headline is this issue about?

Firefox non-standard system color extensions

### What information was incorrect, unhelpful, or incomplete?

  1. The description for `-moz-dragtargetzone` is missing.
  2. Various descriptions misplace `` ` ``, e.g. "`-moz-ButtonHoverFace background` color" in `-moz-ButtonHoverText`.
  3. Ancient Firefox versions are mentioned. e.g. in `-moz-Combobox`:

     > In versions prior to 1.9.2, use `-moz-Field` instead.

  4. Although values are case-insensitive, the casings used in this subsection varies, e.g. `-moz-MenuBarText` and `-moz-win-mediatext`.

### What did you expect to see?

Either:

  1. the description for `-moz-dragtargetzone` added;
  2. `` ` `` be placed correctly;
  3. (optionally) references to ancient versions be removed;
  4. (optionally) casings be unified;

or maybe this subsection be removed altogether?

### Do you have anything more you want to share?

This blocks the l10n of this page.

**Comment by estelle** [comment]
We definitely need to get rid of the old version comments like "Prior to Gecko 1.9, use `-moz-CellHighlightText`.", and likely should get rid of the whole FF section.
