### ISSUE TITLE
Handling multiple checkboxes

### ISSUE THREAD

**Issue by KrzysztofPrzygoda** [mdn/content#26605]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#handling_multiple_checkboxes

### What information was incorrect, unhelpful, or incomplete?

```html
<fieldset>
  <legend>Choose your interests</legend>
  <div>
    <input type="checkbox" id="coding" name="interest" value="coding" />
    <label for="coding">Coding</label>
  </div>
  <div>
    <input type="checkbox" id="music" name="interest" value="music" />
    <label for="music">Music</label>
  </div>
</fieldset>
```

In this example you will see that we've given each checkbox the same name. If both checkboxes are checked and then the form is submitted, you'll get a string of name/value pairs submitted like this: interest=coding&interest=music. When this string reaches the server, you need to parse it other than as an associative array, so all values, not only the last value, of interest are captured. For one technique used with Python, see [Handle Multiple Checkboxes with a Single Serverside Variable](https://stackoverflow.com/questions/18745456/handle-multiple-checkboxes-with-a-single-serverside-variable), for example.

### What did you expect to see?

For multiple var values there is square bracket notation to send result as an array (`name="interest[]"`):
```html
<fieldset>
  <legend>Choose your interests</legend>
  <div>
    <input type="checkbox" id="coding" name="interest[]" value="coding" />
    <label for="coding">Coding</label>
  </div>
  <div>
    <input type="checkbox" id="music" name="interest[]" value="music" />
    <label for="music">Music</label>
  </div>
</fieldset>
```

### Do you have any supporting links, references, or citations?

https://www.php.net/manual/en/faq.html.php

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/checkbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/checkbox/index.md
* Last commit: https://github.com/mdn/content/commit/e9b1ea6ad21c6186ab07d8de4f8b967d8001eef5
* Document last modified: 2023-03-31T10:34:20.000Z

</details>

**Comment by SaurabhCha** [comment]
Hello, I can make this small change. The explanation looks correct to me. Thanks

**Comment by Josh-Cena** [comment]
This sounds like a PHP thing, not an HTML thing. It may be okay to document but if it's not in the HTML spec we need to clearly state that.

**Comment by postmeback** [comment]
I checked on internet, as per `freecodecamp`

 `The name attribute is not required but it could be helpful in the back end processing. And no, the name attribute doesn’t always have to be the same but it helps to group similar things`.
 
 And if I have fetch all the checkbox status, I would rather place it under the same class, to make it convenient.
 
 IMHO, it can be skipped.

**Comment by Josh-Cena** [comment]
@postmeback I don't see how that's relevant to the discussion here. The question is whether it's a PHP convention or whether it is implemented in other backend environments as well. It decides how we are going to demonstrate this. In addition, I strongly advise you to only use standards and original resources (such as tooling documentation or team discussions), not downstream educational resources.

**Comment by Josh-Cena** [comment]
We decided to not document this because we are not interested in documenting PHP features. Readers should find the respective documentation for their own backend.
