### ISSUE TITLE
Developer tool doesn't show correct style applied?

### ISSUE THREAD

**Issue by a10leo** [mdn/content#26601]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers

### What specific section or headline is this issue about?

Precedence order of regular cascade layers

### What information was incorrect, unhelpful, or incomplete?

![Screenshot from 2023-05-05 12-01-25](https://user-images.githubusercontent.com/132663223/236435295-4ae02674-47bb-46c1-82a4-36175f28284f.png)

### What did you expect to see?

Hi there,
I'm newbie in terms of codding but active learner, so please apology for any mistake. This is only a question for better understanding.
So am l missing something here?

In the screenshot above, developer tools:
`@layer A {
  h1 {
box-shadow: -5px 5px lightblue !important;
  }
}
`
...is overridden by unleyered h1:
`h1 {
  box-shadow: 5px 5px lightgreen !important;
}`
...but at the end, layer A box-shadow still applied. By the screenshot bellow !important layered style have precedence over unleyered !important style. So where is the point? 
Thank you,
Alex
![Screenshot from 2023-05-05 11-59-03](https://user-images.githubusercontent.com/132663223/236443290-94091260-8beb-4b59-bd1c-6049344274bf.png)

### Do you have any supporting links, references, or citations?

[https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers#precedence_order_of_regular_cascade_layers](url)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_layers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_layers/index.md
* Last commit: https://github.com/mdn/content/commit/de04c1ce2480b509c148ab13a5527dcb7406d099
* Document last modified: 2023-04-12T18:50:43.000Z

</details>

**Comment by dorward** [comment]
You appear to be reporting a bug in the **Firefox Developer Tools**, but this Github repository (and associated issue tracker) are for the MDN documentation. I believe the appropriate place to report this bug is https://firefox-dev.tools/

**Comment by Josh-Cena** [comment]
Yes, the behavior is consistent with the documentation, but the dev tools is wrong. Please report this as a bug to dev tools instead.
