### ISSUE TITLE
Issue with "Page types"

### ISSUE THREAD

**Issue by alvinhui** [mdn/content#2661]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types

**What information was incorrect, unhelpful, or incomplete?**

I think "**There are three broad categories of page types on MDN**" is incomplete.

**Specific section or headline?**

The summary paragraph.

**What did you expect to see?**

I think there should be another type, that is **Tutorial**. So how is it different from **Guide**? Following is some examples.

Guide:

- [Visualizations with Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Visualizations_with_Web_Audio_API)
- [Getting started with HTML](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started)
- [What’s in the head? Metadata in HTML](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML)

More examples: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API#guides

Tutorial:

- [How to document a CSS property](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Document_a_CSS_property)
- [Taking still photos with WebRTC](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos)
- [Improving compatibility using WebRTC adapter.js](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/adapter.js)

More examples: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API#tutorials

**Did you test this? If so, how?**

I'm still thinking about how to define these two concepts accurately. Now I just want to hear from others.

**Comment by chrisdavidmills** [comment]
I'm going to close this one. Page types is meant to cover template structures for specific reference pages. Tutorials are another type of page — you are correct, but there isn't really a single template structure that will work perfectly for all tutorials. different tutorials require different structures.

A better solution here might be to write a more general "What does a good tutorial need" type article, which I could do, but I've not got the time right now.
