### ISSUE TITLE
No documentation for css src(...)

### ISSUE THREAD

**Issue by rotu** [mdn/content#26621]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/background-image

### What specific section or headline is this issue about?

Formal Definitions, Specification

### What information was incorrect, unhelpful, or incomplete?

The formal syntax mentions:

```
<url> = 
  url( <string> <url-modifier> *)
  src( <string> <url-modifier> *)
```

But there's no mention of what the `src()` functional notation does and no page for it.

### What did you expect to see?

I expect a description or a link to the src functional notation

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/css-values-4/#funcdef-src

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/background-image`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-image
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/background-image/index.md
* Last commit: https://github.com/mdn/content/commit/2a23f650d86d4f5d948614a607224a2bd52cca33
* Document last modified: 2023-04-28T05:58:54.000Z

</details>

**Comment by teoli2003** [comment]
Which browsers support `src()`?

**Comment by rotu** [comment]
> Which browsers support `src()`?

I don’t know if any. It’s [new in CSS “Values and Units” level 4](https://www.w3.org/TR/css-values-4/#additions-L3).

**Comment by yarusome** [comment]
For now there's no test for `src()` under [css-values](https://wpt.fyi/results/css/css-values?label=experimental&label=master&aligned).

**Comment by teoli2003** [comment]
We are documenting implementations and not specifications, so let's put this on hold until there is one implementation.

**Comment by rotu** [comment]
> We are documenting implementations and not specifications, so let's put this on hold until there is one implementation.

I come to MDN to learn "what is this feature and can I use it?". I didn't know `src()` existed until I saw it in the "formal syntax" section. Unfortunately, the formal syntax section does not have a browser compatibility matrix so I had to track down the csswg spec (and the version linked from that page doesn't mention it either!). If we don't regard it as part of CSS yet, it shouldn't be mentioned in the first place.

My preferred resolution of this issue would be to somehow flag the syntax as "proposed"/"not yet standard".

Related: #22069.

**Comment by hamishwillee** [comment]
HI @rotu

Fancy seeing you here in MDN context :-). This is my other work life.

We can't don't document things or include them in the browser compatibility data unless they exist in a browser implementation. Historically there were various attempts to do so, but this is unmaintainable and unscalable. Not going to happen.

@teoli2003 That said, how is the formal syntax populated? It would be good if we could omit things from it that aren't supported anywhere - I can imagine that it should be possible to cross reference BCD.
Minimally, we might also add a note "Formal syntax is automatically generated from spec IDL and may contain unimplemented features. Check the compatibility table for implementation state".

Thoughts?

**Comment by teoli2003** [comment]
The formal syntax comes from the w3c/webref package. They include stuff from the spec. I don't have a practical solution to exclude parts of the formal syntax, but we could fix this problem using this if somebody has one.

**Comment by rotu** [comment]
Hi, @hamishwillee! Small world :-).

> Minimally, we might also add a note "Formal syntax is automatically generated from spec IDL and may contain unimplemented features. Check the compatibility table for implementation state".

I think that makes things a little more confusing. In this case, `url()` is not listed in the compatibility table on the `background-image` page nor the `<image>` page even though other things like `element()` are (`element()` isn't even described on the page, including in the formal syntax).

Even on the `url()` page [^0], the compatibility table names the feature as `<url>` which, in the formal syntax subsumes *both* the `url()` and `src()` functional notations!

[^0]: https://developer.mozilla.org/en-US/docs/Web/CSS/url#browser_compatibility

---

> The formal syntax comes from the w3c/webref package. They include stuff from the spec. I don't have a practical solution to exclude parts of the formal syntax, but we could fix this problem using this if somebody has one.

That package lists `css-values-3` as a "Candidate Recommendation Snapshot"[^1] and `css-values-4` as a "Working Draft"[^2]

[^1]: https://github.com/w3c/webref/blob/7342d3ae3b1c29292eb2887dcefcd02168d75388/ed/index.json#L21050
[^2]: https://github.com/w3c/webref/blob/7342d3ae3b1c29292eb2887dcefcd02168d75388/ed/index.json#L21118

The declaration of `src()` can be tied back to the spec version by the `dfns/css-values-4.json` file[^3].

[^3]: https://github.com/w3c/webref/blob/7342d3ae3b1c29292eb2887dcefcd02168d75388/ed/dfns/css-values-4.json#L554

So that suggests a way to detect non-standard syntax.
---

**Comment by hamishwillee** [comment]
Yeah, its messy because the BCD doesn't even list all things that are known to be implemented. It lists API methods and properties that are known to be implemented, but it doesn't list particular method arguments or return values unless there is an incompatibility, and I don't know how it works for CSS. But I still think we could play around with a note to satisfy the main point:

> This formal syntax may include features that are not implemented in browsers.


>  This formal syntax may include features that are not implemented in browsers.
> The browser compatibility provides information about features that are known to be implemented, but may not include some features if there is no compatibility issue.

With respect to infrastructure I'll leave that with @teoli2003.

**Comment by teoli2003** [comment]
We discussed it today. We agree that this is a problem we want to solve but it is a complex one. So, we are closing this but in favor of the discussion at https://github.com/orgs/mdn/discussions/442
