### ISSUE TITLE
wrong link provided

### ISSUE THREAD

**Issue by Raidennnnnn** [mdn/content#26637]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/GPURenderPassEncoder

### What information was incorrect, unhelpful, or incomplete?

A GPUComputePassEncoder object instance is created via the [GPUCommandEncoder.beginComputePass()](https://developer.mozilla.org/en-US/docs/Web/API/GPUCommandEncoder/beginComputePass) property.

### What did you expect to see?

i think this line should be 
A GPURenderPassEncoder object instance is created via the [GPUCommandEncoder.beginRenderPass()](https://developer.mozilla.org/en-US/docs/Web/API/GPUCommandEncoder/beginRenderPass) property.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/gpurenderpassencoder`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/GPURenderPassEncoder
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/gpurenderpassencoder/index.md
* Last commit: https://github.com/mdn/content/commit/dec68d9038b414114297aee9d5c0194752a0f758
* Document last modified: 2023-04-08T00:46:20.000Z

</details>

**Comment by hamishwillee** [comment]
@Sriparno08 if you create a PR and cross link that is as good as self assignment since it tells people work has been done.

**Comment by Sriparno08** [comment]
Okay, @hamishwillee.
