### ISSUE TITLE
Manifest keys action

### ISSUE THREAD

**Issue by malcolmcdixon** [mdn/content#26649]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action

### What specific section or headline is this issue about?

This key replaces browser_action in Manifest V3 extensions.

### What information was incorrect, unhelpful, or incomplete?

This SHOULD read This key replaces browser_action in Manifest V2 extensions.

### What did you expect to see?

This key replaces browser_action in Manifest V2 extensions.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action

This states Manifest version 2

**Comment by rebloor** [comment]
To avoid ambiguity, it may be been better to simplify to "This key replaces browser_action."

**Comment by malcolmcdixon** [comment]
I agree, the reference to V3 is the only misleading part.
