### ISSUE TITLE
Extra comma in code samples

### ISSUE THREAD

**Issue by weflower** [mdn/content#26652]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

### What specific section or headline is this issue about?

entire page

### What information was incorrect, unhelpful, or incomplete?

There are multiple places in the Using the Fetch API topic where the code samples contain extra commas.

For example, in the "[Uploading a file](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#uploading_a_file)" section:
```
const response = await fetch("https://example.com/profile/avatar", {
      method: "PUT",
      body: formData,
    });
```

There should not be a comma after formData, since it is the last item in the object. There are at least two other code samples that I found on the page that are similar, but I did not review all of them.

### What did you expect to see?

Correct code samples

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/fetch_api/using_fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fetch_api/using_fetch/index.md
* Last commit: https://github.com/mdn/content/commit/95e3d3c41211c04f048f13bdc24677a7ab84d764
* Document last modified: 2023-04-03T11:14:54.000Z

</details>

**Comment by Sriparno08** [comment]
If it's indeed an issue, I would like to work on this!

**Comment by Josh-Cena** [comment]
Hi, this is the style we use on MDN, and is a generally preferred style in industry. Please see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

**Comment by weflower** [comment]
@Josh-Cena thanks! I wasn't aware of that :)
