### ISSUE TITLE
site report "Page not found" for zh-CN after click "next page", but "change language" can change to zh-CN in next page

### ISSUE THREAD

**Issue by stirwl** [mdn/content#2665]
https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders
get this issue, when click "next page" in above page.

well, this probably because "next page" is using english url, while "change language" is using chinese url.
there probably be other pages which have this issue, you may kindly check it.

english url:
/zh-CN/docs/Learn/CSS/Building_blocks/Handling_different_text_directions

chinese url:
https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/%E5%A4%84%E7%90%86_%E4%B8%8D%E5%90%8C_%E6%96%B9%E5%90%91%E7%9A%84_%E6%96%87%E6%9C%AC

---
Page not found

Sorry, the page /zh-CN/docs/Learn/CSS/Building_blocks/Handling_different_text_directions could not be found.
Good news!

The page you requested doesn't exist in Chinese (Simplified) but it exists in English

Handling different text directions
/en-US/docs/Learn/CSS/Building_blocks/Handling_different_text_directions

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills what would be the steps here to solve this issue? For me it looks like doing adjustments inside the _redirects.txt is this corrrect?

**Comment by chrisdavidmills** [comment]
I'm not really what the problem is here, it seems to work OK to me...

**Comment by stirwl** [comment]
@CreaTorAlexander @chrisdavidmills 
It works to me now, too.
The page is requesting english url when I click "next page" button now.

Maybe the url is also translated to chinese before?
The browser address show english url now, even I click the chinese url. So it works.
The browser address show chinese url(https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/处理_不同_方向的_文本) when I got this issue.

**Comment by SphinxKnight** [comment]
As I understand https://github.com/mdn/content/issues/2665#issuecomment-786520237, this can be closed. If I misunderstood, please provide a screenshot incl. the URL and I'll reopen/transfer the issue to mdn/translated-content
