### ISSUE TITLE
The picture is not satisfied with the actual effect.

### ISSUE THREAD

**Issue by Jackstraw007** [mdn/content#26666]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode

### What specific section or headline is this issue about?

Examples->Result

##### In the pic
![image](https://user-images.githubusercontent.com/18254791/237024325-00543d22-b274-49c4-8f97-57b2ba7ad780.png)

##### actually
![image](https://user-images.githubusercontent.com/18254791/237024624-231ddec4-faac-4385-86ea-58d85b8f008c.png)

### What did you expect to see?

Please paste the write pic.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/writing-mode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/writing-mode/index.md
* Last commit: https://github.com/mdn/content/commit/9c27e923a7149a43309e624b44d8e2ab563607e7
* Document last modified: 2023-02-21T21:41:41.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

Are you running a Chromium browser? `sideways-lr` and `sideways-rl` are only supported in Firefox, as the compat table indicates: https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode#browser_compatibility. So it is expected for the image to differ from the live result. As the text above the image says:

> This image shows what the output should look like, in case your browser's support for writing-mode is incomplete:

For me, in Firefox the image matches, and in Chrome I see the same discrepancy as you.

**Comment by Jackstraw007** [comment]
Got it, thx.
