### ISSUE TITLE
Document PerformanceObserver.supportedEntryTypes

### ISSUE THREAD

**Issue by ddbeck** [mdn/content#2667]
## Summary

`PerformanceObserver.supportedEntryTypes` is undocumented. It'd solve a lot of compat-related problems if it were.

## Details

`PerformanceObserver.supportedEntryTypes` is undocumented, which makes it difficult to understand browser compatibility for various parts of the Performance Timeline API. The [`PerformanceObserver`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver) page doesn't mention it, except in [the compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver#browser_compatibility), which [404s](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver/supportedEntryTypes).

A few Performance Timeline APIs rely on [`entryType` string identifiers](https://w3c.github.io/timing-entrytypes-registry/#registry)—the strings provided by the `PerformanceObserver` property—such as [`Performance.getEntriesByName()`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByName). Figuring out which strings are supported without this API requires a lot of trial and error and suggests, perhaps erroneously, that the compatibility table should communicate this.

## Background

On https://github.com/mdn/browser-compat-data/issues/9128, compatibility data was requested for the useful string arguments to [`Performance.getEntriesByType()`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByType). While BCD could record such data, there's an API which can provide this information more directly to web developers and permit, for example, feature detection.

**Comment by jculver050** [comment]
Close

**Comment by jculver050** [comment]
!fix

**Comment by jculver050** [comment]
!fix

**Comment by ddbeck** [comment]
From https://github.com/mdn/browser-compat-data/issues/9128#issuecomment-785949746, @jakub-g rightly noted:

> The tricky thing is that `PerformaceObserver` is newer and less supported than `performance/getEntriesByType()`; and `PerformanceObserver.supportedEntryTypes` even less (Safari 12.1 only, for example).
> 
> […]
> 
> What I think could be done is:
> 
> 1. Update MDN content: https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByType saying that different browsers support different types of entries and that it's evolving.

**Comment by jakub-g** [comment]
[Quickly checking](https://gist.github.com/jakub-g/86e85a8b82770ff48444833ec8e99cb1), `PerformanceObserver.supportedEntryTypes` is available in Chrome 73, Firefox 68, and probably Safari 13.0 (note that bugs/release notes sometimes lie as described in gist)
