### ISSUE TITLE
link: fix examples for Apple touch icon

### ISSUE THREAD

**Issue by gianpaj** [mdn/content#26707]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link

### What specific section or headline is this issue about?

Providing icons for different usage contexts

### What information was incorrect, unhelpful, or incomplete?

Apple devices no longer check for `apple-touch-icon-precompose`

> In older versions of Safari for iOS, the [precomposed keyword](https://mathiasbynens.be/notes/touch-icons#effects) could be used to prevent iOS from adding different visual effects to the touch icon (i.e., rounded corners, drop shadow, reflective shine). Starting with iOS 7, no special effects are applied to touch icons, so there is no need to use the precomposed keyword anymore.

https://github.com/webhintio/hint/blob/main/packages/hint-apple-touch-icons/README.md#why-is-this-important

### What did you expect to see?

```
<link
  rel="apple-touch-icon"
  sizes="144x144"
  href="favicon144.png" />
...

```

### Do you have any supporting links, references, or citations?

https://github.com/webhintio/hint/blob/main/packages/hint-apple-touch-icons/README.md#why-is-this-important

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/link`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/link/index.md
* Last commit: https://github.com/mdn/content/commit/fa8a44b8bff24a4032181c4fd155c459c0dc9161
* Document last modified: 2023-03-13T07:09:38.000Z

</details>

**Comment by CBID2** [comment]
I want to work on this issue @gianpaj

**Comment by CBID2** [comment]
Hi @gianpaj! :) I finally made the PR for this issue(sorry for the delay). It's #27935
