### ISSUE TITLE
facing issue in autocomplete="off"

### ISSUE THREAD

**Issue by VirtualDharm** [mdn/content#26714]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

### What specific section or headline is this issue about?

For this reason, many modern browsers do not support autocomplete="off" for login fields:

### What information was incorrect, unhelpful, or incomplete?

For this reason, many modern browsers do not support autocomplete="off" for login fields:

If a site sets autocomplete="off" for a [`<form>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form), and the form includes username and password input fields, then the browser still offers to remember this login, and if the user agrees, the browser will autofill those fields the next time the user visits the page.
If a site sets autocomplete="off" for username and password [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) fields, then the browser still offers to remember this login, and if the user agrees, the browser will autofill those fields the next time the user visits the page.
[Preventing autofilling with autocomplete="new-password"](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password)
If you are defining a user management page where a user can specify a new password for another person, and therefore you want to prevent autofilling of password fields, you can use autocomplete="new-password".

This is a hint, which browsers are not required to comply with. However modern browsers have stopped autofilling <input> elements with autocomplete="new-password" for this very reason. For example, Firefox version 67 (see [Firefox bug 1119063](https://bugzil.la/1119063)) stopped autofilling in this case; however, Firefox 70 (see [Firefox bug 1565407](https://bugzil.la/1565407)) can suggest securely-generated passwords, but does not autofill a saved password. See the [autocomplete compat table](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#browser_compatibility) for more details.

### What did you expect to see?

I want an answer is __away the solution for this.

### Do you have any supporting links, references, or citations?

check on stackover flow

### Do you have anything more you want to share?

text me and it's solve this problem

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/security/securing_your_site/turning_off_form_autocompletion`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/security/securing_your_site/turning_off_form_autocompletion/index.md
* Last commit: https://github.com/mdn/content/commit/c6dbc4ff96451887b908b46c8e70bcfec1c2c48c
* Document last modified: 2023-02-26T04:54:36.000Z

</details>

**Comment by Josh-Cena** [comment]
This is just a verbatim copy of the doc source with no problem mentioned. Going to close for now.
