### ISSUE TITLE
Language tag "prs" appears differently on browsers.

### ISSUE THREAD

**Issue by jpark58** [mdn/content#26712]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames#try_it

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

Depending on browser, language tag "prs" appears differently.

1. On Chrome, "prs" appears to be Dari
<img width="604" alt="prs on chrome" src="https://github.com/mdn/content/assets/48766032/16ca453c-28c6-493c-ae56-c2f9d7cb554e">

2. On Edige, "prs" appears to be Persian
<img width="374" alt="prs on edge" src="https://github.com/mdn/content/assets/48766032/7775a44e-6074-47be-b43a-bbf69ae335da">

### What did you expect to see?

https://en.wikipedia.org/wiki/IETF_language_tag

As per IETF BCP 47 language tag contract, it should be Dari even on Edge.
Is this a known issue?

**Comment by jpark58** [comment]
Moving this to browser-compat-data

**Comment by Josh-Cena** [comment]
@jpark58 Unfortunately this falls under the scope of neither BCD nor content. It's part of the BCD policy to not document Intl formatter output because they can change any time depending on the browser's dataset.
