### ISSUE TITLE
rowgroup scope is not explained correctly

### ISSUE THREAD

**Issue by andypillip** [mdn/content#26722]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th

### What specific section or headline is this issue about?

rowgroup role

### What information was incorrect, unhelpful, or incomplete?

Current text:
> `rowgroup`: The header belongs to a `rowgroup` and relates to all of its cells. These cells can be placed to the right or the left of the header, depending on the value of the `dir` attribute in the `<table>`

If you think about it, this cannot be correct. A row group is obviously grouping _rows_. Therefore, the cells cannot only be right or left of the header.

Actually, the spec mentions that the header will apply to all other cells in the group, whether they are left or right does not matter.

> The row group state means the header cell applies to all the remaining cells in the row group.

To quote the stackoverflow user that brought up the issue:

> The `dir` attribute is not mentioned in the [table's 4.9.12 Processing Model specification](https://html.spec.whatwg.org/multipage/tables.html#table-processing-model), and does therefore not affect the relation of data and header cells as written in the HTML source code. The dir attribute only affects visual placement (i.e. layout) of the cells.

### What did you expect to see?

Drop the mention of `dir`?

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/tables.html#attr-th-scope-rowgroup

https://html.spec.whatwg.org/multipage/tables.html#table-processing-model

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/th`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/th/index.md
* Last commit: https://github.com/mdn/content/commit/942a529383ee7ee3996fb234187641c08935f3ff
* Document last modified: 2023-04-13T06:13:15.000Z

</details>

**Comment by CBID2** [comment]
.take
