### ISSUE TITLE
[Web API] HTTP(S) schemes in the WebSocket constructor

### ISSUE THREAD

**Issue by annevk** [mdn/content#26731]
EDIT FYI, turned this into an FF tracking bug

## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Features to document

See https://github.com/whatwg/websockets/pull/45

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1797449

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
MDN generally doesn't document until there is an implementation (there are bugs in lined whatwg item). I added the forlater tag, but not sure how that turns into an action to doc. If not before, we'll get to it when an FF bugzilla gets added for this with an implementation.

**Comment by annevk** [comment]
WebKit has an implementation on main, FWIW.

**Comment by Meir017** [comment]
Chrome shipped this in 125 - https://chromestatus.com/feature/5848709993857024

**Comment by Josh-Cena** [comment]
This has been implemented in all browsers.

**Comment by Josh-Cena** [comment]
@mdn/core-yari-content I'm not sure whether this is missed in the FF 124 release project unintentionally but I think this should be documented as an FF new feature.

**Comment by hamishwillee** [comment]
Thanks @Josh-Cena - moved it to the project. Missed because the bugzilla issue wasn't tagged as needing dev docs.

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/24218
- [ ] Docs
- [ ] release note
- [ ] dev-docs-complete
