### ISSUE TITLE
beforeunload docs say it's incompatible with BFCache

### ISSUE THREAD

**Issue by fergald** [mdn/content#26739]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

### What specific section or headline is this issue about?

#usage_notes

### What information was incorrect, unhelpful, or incomplete?

`beforeunload` events only prevent BFCaching on Mozilla. Chrome and Safari BFCache pages with a handler.

You can test it out with [this page](https://fergald.github.io/random/bfcache/beforeunload/).

The reasoning

> because many pages using this event assume that the page will not continue to exist after the event is fired

doesn't seem valid. A user may opt to remain on the page *because* of the prompt that is shown, so it's entirely expected that the page may continue to exist after the event is fired. I think perhaps this was was mistakenly copied from [the `unload` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event#usage_notes).

### What did you expect to see?

It should not that it currently blocks on Mozilla.

See [the BFCache guide](https://web.dev/bfcache/#only-add-beforeunload-listeners-conditionally) for the latest advice on use of `beforeunload` and BFCache.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/beforeunload_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/beforeunload_event/index.md
* Last commit: https://github.com/mdn/content/commit/cc070123f72376faec06e36622c4fc723a75325f
* Document last modified: 2023-04-08T06:57:07.000Z

</details>

**Comment by wbamberg** [comment]
Thank you @fergald ! I believe that this came originally from https://developer.chrome.com/blog/page-lifecycle-api/#the-beforeunload-event. From https://web.dev/bfcache/#only-add-beforeunload-listeners-conditionally it looks like this is not true any more, if it ever was!
