### ISSUE TITLE
Baseline definition can be misread

### ISSUE THREAD

**Issue by romainmenke** [mdn/content#26746]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Baseline/Compatibility

### What information was incorrect, unhelpful, or incomplete?

> A Baseline feature - such as an API, a set of CSS properties, or a JavaScript syntax - is known to work consistently in the current and previous major versions of several well-known browsers (Chrome, Edge, Firefox, and Safari).

### What did you expect to see?

I expected a less unambiguous definition.
This can be misread as "an undefined but larger number of previous major versions"

For example : 

> A Baseline feature - such as an API, a set of CSS properties, or a JavaScript syntax - is known to work consistently in the current and **the** previous major **version** of several well-known browsers (Chrome, Edge, Firefox, and Safari).

By changing `previous` to `the previous` and `versions` to `version` it becomes clear that only two versions are taken into consideration and not a larger number.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/baseline/compatibility`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Baseline/Compatibility
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/baseline/compatibility/index.md
* Last commit: https://github.com/mdn/content/commit/bb6092c4230b69c2eceae6910af68c73955cae1c
* Document last modified: 2023-05-10T14:53:07.000Z

</details>

**Comment by postmeback** [comment]
IMHO, the wordings seems to be ok. If anyone wants to go deep about every changes of any **browser**, I believe they can refer the **changelog / history / release notes** for this.

Still, it's up to the maintainers to decide.

**Comment by romainmenke** [comment]
> IMHO, the wordings seems to be ok. If anyone wants to go deep about every changes of any browser, I believe they can refer the changelog / history / release notes for this.

That was not my point :)

Baseline currently has a very strict definition which is exactly : supported since at least one major version before the current major version.

But that is not what the wording here says.
It can be read as "supported since an unknown number of previous versions".
