### ISSUE TITLE
Excuse me, could anyone give me a particular example to help me understanding what is "a complex piece of software"?

### ISSUE THREAD

**Issue by pocketdr** [mdn/content#26741]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview#the_web_server

### What information was incorrect, unhelpful, or incomplete?

> or a complex piece of software interrogating other computers (like cache, a DB server, or e-commerce servers), totally or partially generating the document on demand.

Is the additional content in brackets was added to explain "computers" or "software"?

### What did you expect to see?

I would like to obtain an example of " a complex piece of software".

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/overview`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/overview/index.md
* Last commit: https://github.com/mdn/content/commit/b0870830e4c02596ca6c501f8f8b468a917eafc2
* Document last modified: 2023-05-10T11:37:46.000Z

</details>

**Comment by wbamberg** [comment]
> Is the additional content in brackets was added to explain "computers" or "software"?

It's intended, I believe, to refer to "software". Still this is a little ambiguous, and I'm not sure "complex" is helpful in this context, so I just filed https://github.com/mdn/content/pull/26750.
