### ISSUE TITLE
For beforeunload event documentation, change userActivation type from transient to sticky

### ISSUE THREAD

**Issue by Peter-Takhar** [mdn/content#26751]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

### What specific section or headline is this issue about?

Security

### What information was incorrect, unhelpful, or incomplete?

I have a question about this sentence: 'Transient user activation is required. The user has to interact with the page or a UI element in order for this feature to work.'

Transient user activation can be programmatically determined by `navigator.userActivation.isActive`. I was confused why after the warning dialog was still popping up even after a user clicked on the page and the isActive property changed from true to false. It was behaving as if it was gated by sticky activation, not transient activation.

### What did you expect to see?

When I did a quick search through the chromium code, looks like they tested 'beforeunload' being gated by sticky activation. Maybe I was interpreting it wrong, but I think its more accurate to say 'Sticky user activation is required. The user has to interact with the page or a UI element in order for this feature to work.'. And also make changes on other pages as needed like here: https://developer.mozilla.org/en-US/docs/Web/Security/User_activation.

### Do you have any supporting links, references, or citations?

Chromium test example: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/html/browsers/browsing-the-web/unloading-documents/support/beforeunload-sticky-destination.html

### Do you have anything more you want to share?

Don't mind making changes myself if this change is needed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/beforeunload_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/beforeunload_event/index.md
* Last commit: https://github.com/mdn/content/commit/cc070123f72376faec06e36622c4fc723a75325f
* Document last modified: 2023-04-08T06:57:07.000Z

</details>

**Comment by hamishwillee** [comment]
My read of the specification is that you are correct: https://html.spec.whatwg.org/multipage/browsing-the-web.html#preventing-navigation:event-beforeunload

> all of the following are true:

>
> - unloadPromptShown is false;

> - document's [active sandboxing flag set](https://html.spec.whatwg.org/multipage/browsers.html#active-sandboxing-flag-set) does not have its [sandboxed modals flag](https://html.spec.whatwg.org/multipage/browsers.html#sandboxed-modals-flag) set;

> - document's [relevant global object](https://html.spec.whatwg.org/multipage/webappapis.html#concept-relevant-global) has [sticky activation](https://html.spec.whatwg.org/multipage/interaction.html#sticky-activation);

> - event's [canceled flag](https://dom.spec.whatwg.org/#canceled-flag) is set, or the [returnValue](https://html.spec.whatwg.org/multipage/nav-history-apis.html#dom-beforeunloadevent-returnvalue) attribute of event is not the empty string; and

> - showing an unload prompt is unlikely to be annoying, deceptive, or pointless


There are various cases where transient activation is required in that spec, but I don't think this one.
