### ISSUE TITLE
Lack of information on the differences between closing via method='dialog' and .close()  method

### ISSUE THREAD

**Issue by Endzelisp** [mdn/content#26760]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

I noticed that the article does not go into detail about the difference between closing a dialog using the method='dialog' attribute vs. using the .close() method. It would be helpful to understand if there is a difference, and if so, when it's better to use one method over the other.

### What did you expect to see?

If a difference between both approaches exist explain when do I need to use one over the other.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmldialogelement/close_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmldialogelement/close_event/index.md
* Last commit: https://github.com/mdn/content/commit/a3d9f61a8990ba7b53bda9748d1f26a9e9810b18
* Document last modified: 2023-04-07T00:39:15.000Z

</details>

**Comment by advitiya7** [comment]
as per my understanding the main difference is that the dialog attribute closes the dialog immediately while .close() method allows us to execute the code before the dialog closes and there are some timing differences too that i don't know much about @Endzelisp if this helps and if this is correct i can update the doc with some explanation and an example.
thanks

**Comment by Endzelisp** [comment]
The problem I faced was this, I'm creating a shopping-list project for practicing purposes, there I have a dialog modal form to capture user info with a button to add it as a new element to the list and also a close button ( X ) in the top right corner of the modal to close the form **without** adding a new element.

If I fill the form but instead of clicking on the save button I click on the close button it also creates a new element in the list with the info that was passed in. Then both buttons are behaving the same way.

**Comment by Endzelisp** [comment]
The dialog element article gives a useful explanation that I used to solve my problem, and was with the making use of the returnValue property.

Inside the event handler I added this:

`
  if (dialog.returnValue === "close") return
`

To finally have this:

```
UI.dialog.addEventListener("close", () => {

  if (dialog.returnValue === "close") {
    return;
  }

  // Some code doing stuff
});
```

**The Dialog element article** [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog](url)

**Comment by Endzelisp** [comment]
Despite of I solved what was happening in my code, if you think @advitiya7 that the close event article could be improved would be great. I try as much as possible to follow good practices and make the code clear and functional, but sometimes is hard when we face different ways to achieve the same result and there's no much information about what's the difference between different approaches or when to use one over the other.
