### ISSUE TITLE
Confusing naming in `WebAssembly.instantiate`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [mdn/content#26785]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiate

### What information was incorrect, unhelpful, or incomplete?

The description of the `importsObject` parameter says that it must contain "functions or `WebAssembly.Memory` objects", and all the examples are like the following:

```js
const importObject = {
  imports: {
    imported_func(arg) {
      console.log(arg);
    },
  },
};
```

With the above example and description, I expected `importObject` to be an options bag and `imports` to be the object contianing the functions/memory that can be imported by the Wasm module.

However, the reality is that WebAssemly imports are namespaced, and `imports` is just an arbitrary namespace name.

The above code `importObject` can be used by a Wasm module using an import that would be expresses as follows in JavaScript:
```js
import { imported_func } from "imports";
```

For example, given this Wasm module:
```wasm
(module
  (import "numbers" "getPI" (func $getPI (result f64)))
  (func $multiplyByPI (export "multiplyByPI") (param $num f64) (result f64)
    local.get $num
    call $getPI
    f64.mul)
)
```

the `importsObject` would be something like
```js
const importObject = {
  numbers: {
    getPI: () => Math.PI
  }
};
```

### What did you expect to see?

`imports` should be renamed to something more general, such as `namespaceA`, or even better it could include multiple namespaces:
```js
const importsObject = {
  logging: {
    log(msg) { console.log(msg) }
  },
  math: {
    multiply(a, b) { return a * b }
  }
};
```

### Do you have any supporting links, references, or citations?

https://webassembly.github.io/spec/js-api/#read-the-imports

### Do you have anything more you want to share?

Example of a Wasm module using a namespace named differently from `imports` (sorry for sending a screenshot, that website doesn't support sharing an url):
<img width="1470" alt="image" src="https://github.com/mdn/content/assets/7000710/2ff1c16d-d380-441b-b1a8-ec7384c057d1">

**Comment by MendyBerger** [comment]
I think even just renaming imports to my_imports would go a long way toward making it clear that _imports_ isn't some special keyword
