### ISSUE TITLE
Incorrect Documentation - CSS quotes are not affected by "contain: style".

### ISSUE THREAD

**Issue by howardRaul1** [mdn/content#26804]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/contain

### What specific section or headline is this issue about?

Containment and quotes

### What information was incorrect, unhelpful, or incomplete?

The documentation says that: 
"CSS quotes are similarly affected in that the content values relating to quotes are scoped to the element:"

However, this is inccorect.  I have tested the code many times.  CSS quotes are not affected by "contain: style", and there is nowhere in the W3C or WHATWG specification that says CSS quotes are affected by "contain: style".

I am using Chrome version 113, and, contrary to what the documentation says, the "first closing quote" doesn't use the outer span's closing quote.  From the screenshot below, you can see that the first closing quote clearly uses the inner span's closing quote.

![image](https://github.com/mdn/content/assets/61098455/64088674-3a10-4ba6-a062-50f3dc197967)

### What did you expect to see?

Proposed Solution 1: Update the text to say "CSS quotes are not affected by "contain: style".

Proposed Solution 2: We can remove this entire section on "Containment and quotes".

### Do you have any supporting links, references, or citations?

Please see screenshot above.

**Comment by wbamberg** [comment]
I'm not very familiar with CSS containment, but I'm not sure about this. For one thing, in Firefox 
(although not in Chrome or Safari) I do see the expected output:

<img width="756" alt="Screen Shot 2023-05-17 at 10 03 20 AM" src="https://github.com/mdn/content/assets/432915/e70e736f-6dad-4718-beb1-ae7e3e6ff013">

This example was added by @bsmth in https://github.com/mdn/content/pull/19875, and in t[he related Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1463600) it certainly seems as if containment is intended to apply to quotes. And the spec does refer to quotes at https://drafts.csswg.org/css-contain/#containment-style :

> Giving an element style containment has the following effects:
>
> * The effects of the content property’s [open-quote](https://drafts.csswg.org/css-content-3/#valdef-content-open-quote), [close-quote](https://drafts.csswg.org/css-content-3/#valdef-content-close-quote), [no-open-quote](https://drafts.csswg.org/css-content-3/#valdef-content-no-open-quote) and [no-close-quote](https://drafts.csswg.org/css-content-3/#valdef-content-no-close-quote) must be [scoped to the element’s sub-tree](https://drafts.csswg.org/css-contain/#property-scoped-to-a-sub-tree).

@bsmth , what do you think? Is there a Chrome compat issue here?

**Comment by howardRaul1** [comment]
> I'm not very familiar with CSS containment, but I'm not sure about this. For one thing, in Firefox (although not in Chrome or Safari) I do see the expected output:
> 
> <img alt="Screen Shot 2023-05-17 at 10 03 20 AM" width="756" src="https://user-images.githubusercontent.com/432915/239026013-e70e736f-6dad-4718-beb1-ae7e3e6ff013.png">
> This example was added by @bsmth in #19875, and in t[he related Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1463600) it certainly seems as if containment is intended to apply to quotes. And the spec does refer to quotes at https://drafts.csswg.org/css-contain/#containment-style :
> 
> > Giving an element style containment has the following effects:
> > 
> > * The effects of the content property’s [open-quote](https://drafts.csswg.org/css-content-3/#valdef-content-open-quote), [close-quote](https://drafts.csswg.org/css-content-3/#valdef-content-close-quote), [no-open-quote](https://drafts.csswg.org/css-content-3/#valdef-content-no-open-quote) and [no-close-quote](https://drafts.csswg.org/css-content-3/#valdef-content-no-close-quote) must be [scoped to the element’s sub-tree](https://drafts.csswg.org/css-contain/#property-scoped-to-a-sub-tree).
> 
> @bsmth , what do you think? Is there a Chrome compat issue here?

Hi @wbamberg and @bsmth,  

wbamberg is correct.  As of today (May 21, 2023), Firefox is the only browser that conforms to the spec.

How do we update the compatibility table on MDN?

**Comment by howardRaul1** [comment]
Hi @wbamberg and @bsmth,  

wbamberg is correct.  As of today (May 21, 2023), Firefox is the only browser that conforms to the spec.

How do we update the compatibility table on MDN?

**Comment by wbamberg** [comment]
> Hi @wbamberg and @bsmth,
> 
> wbamberg is correct. As of today (May 21, 2023), Firefox is the only browser that conforms to the spec.
> 
> How do we update the compatibility table on MDN?

The data for the compat tables comes from the browser-compat-data project, which is maintained in a separate repo: https://github.com/mdn/browser-compat-data, in particular https://github.com/mdn/browser-compat-data/blob/main/css/properties/contain.json.

But I'm not quite sure what the compat issue here is. It look as if everyone supports `contain: style` for counters, and it's only quotes that are affected. See the [web platform tests for contain](https://wpt.live/css/css-contain/), and specifically for [quote scoping](https://wpt.live/css/css-contain/quote-scoping-001.html) and [counters](https://wpt.live/css/css-contain/contain-style-counters-001.html).

There's also a bug for WebKit: https://bugs.webkit.org/show_bug.cgi?id=232083 but I couldn't find one for Chromium.

**Comment by howardRaul1** [comment]
WHATWG maintains HTML and JavaScript standards.

CSSWG maintains the CSS standards.

According to the CSSWG spec, style containment needs to work for both counters and quotes:

https://drafts.csswg.org/css-contain/#containment-style

----------------------------------------------------------------------
Hi @wbamberg, thanks for the links, but I have never updated the compatibility data before...Are there any instructions or FAQ out there?

**Comment by wbamberg** [comment]
> Are there any instructions or FAQ out there?

Yes! -> https://github.com/mdn/browser-compat-data/blob/main/docs/contributing.md

**Comment by bsmth** [comment]
Thanks for raising @howardRaul1 and for digging in to the topic, @wbamberg. I'd be reluctant to add BCD sub-features for style containment as:

* style
  * counters
  * quotes

Maybe this warrants [partial implementation](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#partial_implementation-requires-a-note)/

**Comment by wbamberg** [comment]
Yeah, I think partial implementation would be better than subfeatures, although I'm not a BCD style guru.

**Comment by bsmth** [comment]
Closing as fixed in https://github.com/mdn/browser-compat-data/pull/19978

Thanks @howardRaul1
