### ISSUE TITLE
NotificationOptions and Notification silent default has change

### ISSUE THREAD

**Issue by marcoscaceres** [mdn/content#26812]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Notification/silent

### What specific section or headline is this issue about?

Silent

### What information was incorrect, unhelpful, or incomplete?

Silent default is false

### What did you expect to see?

Silent default is changing to `null`

### Do you have any supporting links, references, or citations?

Please see https://github.com/whatwg/notifications/pull/194

(Not merged yet!)

**Comment by advitiya7** [comment]
@marcoscaceres i just have to change the false to null?

**Comment by Josh-Cena** [comment]
Please wait until the spec is merged and implementations have shipped this change.

**Comment by marcoscaceres** [comment]
@advitiya7, yes, just change false to null... plus explain that "when null, if a notification is silent or not is left up to the OS".

Noting this has landed in WebKit at least, but not shipped in a browser to date.
