### ISSUE TITLE
Brackets or Braces?

### ISSUE THREAD

**Issue by FKlusmann** [mdn/content#26830]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax

### What specific section or headline is this issue about?

#CSS declaration blocks

### What information was incorrect, unhelpful, or incomplete?

"Declarations are grouped in blocks, that is in a structure delimited by an opening _**brace,**_ '{' (U+007B LEFT CURLY _**BRACKET**_), and a closing one, '}' (U+007D RIGHT CURLY _**BRACKET**_). Blocks sometimes can be nested, so opening and closing _**braces**_ must be matched." 

Are we using _**curly brackets**_ or _**curly braces**_? 

### What did you expect to see?

I would like to see only one ot the other.

### Do you have any supporting links, references, or citations?

https://web.dev/learn/css/selectors/   uses "curly brackets. "

https://www.w3schools.com/css/css_syntax.asp uses "curly braces.".

### Do you have anything more you want to share?

Learning HTML-5 and CSS-3 is hard enough without inconsistent terminology.  One term with a consistant meaning would be helpful.

Thank you for reading.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/syntax`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/syntax/index.md
* Last commit: https://github.com/mdn/content/commit/13c58b0430c3972566ea2d3a254129c18b1ed800
* Document last modified: 2023-04-16T03:53:26.000Z

</details>

**Comment by Josh-Cena** [comment]
On MDN we always use "curly braces" because it's most unambiguous. "CURLY BRACKET" here is literally how it's called in Unicode. Unfortunately I don't think we can change that. There's also not a second character also called "curly bracket", so I believe it's not confusing to most.

**Comment by FKlusmann** [comment]
Thank you, Josh-Cena.
``` On MDN we **_always use_** "curly braces" ``` is not true, as seen in the paragraph I quoted in which BOTH are used. 

My suggestion is to be consistent.  

Unicode.org acknowledges both brackets and braces as seen:
https://www.unicode.org/charts/nameslist/index.html shows 
007B	 { 	Left Curly Bracket  = opening curly bracket (1.0) = left brace
007D	 } 	Right Curly Bracket = closing curly bracket (1.0) = right brace

How about note, an aside, or footnote saying something like:
The terms"Left Curly Bracket" and "Left Curly Brace" are used interchangeability to mean & #123;   
The terms"Right Curly Bracket" and "Right Curly Brace" are used interchangeability to mean & #125;

**Comment by Josh-Cena** [comment]
When I say "we use it consistently" there's naturally a prerequisite that we have to have a choice. Here we are quoting the Unicode name and have no choice. In the document you cited, only the all-caps name is "canonical"; the other names are just common aliases but do not carry the same normativeness. I think a note may help to clarify, but I highly doubt how many would be confused: how many would interpret it as something else if they don't mean `{` `}`?

**Comment by FKlusmann** [comment]
Josh-Cena,
Thank you for reading.
Have a good weekend!
