### ISSUE TITLE
The Heading Reads "Meters and progress bars" but the Content is Listed "Progress" and then "Meter"

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#26837]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls

### What specific section or headline is this issue about?

Meters and progress bars

### What information was incorrect, unhelpful, or incomplete?

Why is the heading "Meters and progress bars" but the content is listed in the opposite order "Progress" and then "Meter"?

**NOTE** - You might need to rewrite the text of the first line under the heading or reorder content sections.

### What did you expect to see?

I would expect the order of the two items to match the order of the heading.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/other_form_controls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/other_form_controls/index.md
* Last commit: https://github.com/mdn/content/commit/65b9418c7d0e3a331ac50249adf0024f44789923
* Document last modified: 2023-05-09T00:34:38.000Z

</details>

**Comment by bsmth** [comment]
Hi @jfc3-dol would you like to open a pull request to make the appropriate changes?

**Comment by jfc3-dol** [comment]
@bsmth 

Someone else can do it since I was only pointing out the issue. Plus, I am not sure of the process and can't do so on my work computer.
