### ISSUE TITLE
Josh's summer MDN projects

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#26847]
Below is a dump of all projects I have the will to complete this summer from June to August (review is appreciated for each PR). This issue is to sync my todo list with the team and the community to avoid duplicated work and let people know what I may be focusing on—I will avoid creating issues for each one of them. Items are sorted by decreasing priority, and the ones down the list may depend on items above:

- [x] Regex v flag documentation (stage 4; top priority!)
  - https://github.com/mdn/content/pull/26944
- [x] Update the `let`/`var`/`const` pages, in preparation for explicit-resource-management
  - https://github.com/mdn/content/pull/26973
- [x] Exhaustively document Date objects' primitive representations and the date string format usage, in preparation for temporal
  - https://github.com/mdn/content/pull/27005
- [ ] Align all `toString()`/`valueOf()`/`[@@toPrimitive]()` pages
- [ ] Document generator functions' and generator objects' prototype chains, in preparation for iterator-helpers
  - Note: this one is done, but I'm not sending the PR pending https://github.com/orgs/mdn/discussions/358 (or when I really feel necessary)
- [x] Make all TypedArray methods link to the array counterpart as the source of truth
  - https://github.com/mdn/content/pull/28394
- [x] Consistently mention Unicode code points and UTF-16 code units in string methods
  - https://github.com/mdn/content/pull/27545
- [ ] Align all Intl APIs' `supportedLocalesOf()` and `resolvedOptions()` methods; investigate more consistency for other methods as well
  - https://github.com/mdn/content/pull/28525
  - https://github.com/mdn/content/pull/28594
- [ ] Brief guide for all Intl APIs
- [x] Make the typed array guide more like an actual guide, with mentions of use cases and memory representation
  - https://github.com/mdn/content/pull/28628
- [ ] Split the modules guide into two parts: "JavaScript modules" and "JavaScript modules on the web", in preparation for many new module features to come
- [ ] Audit the JS guide; make sure all interesting features are introduced in the guide
- [ ] Make the errors reference more exhaustive and remove non-standard and/or outdated errors; investigate linking to these errors from API "Exceptions" section (instead of linking to the error global)
- [x] Use a consistent format for API intro paragraphs
  - https://github.com/mdn/content/pull/28456
- [ ] Investigate syncing API main pages' dl content with each subpage's description (may not be an improvement over status quo)
- [ ] Preliminary docs for big unshipped stage-3 features (explicit-resource-management, iterator-helpers, set-methods); look forward to some of them shipping this summer
  - https://github.com/mdn/content/pull/28381
  - https://github.com/mdn/content/pull/28407
  - https://github.com/mdn/content/pull/28414
  - https://github.com/mdn/content/pull/28424
  - https://github.com/mdn/content/pull/28677
  - TODOs: explicit-resource-management, shadowrealm, decorators, decorator-metadata, json-parse-with-source, regexp-modifiers, float16array, promise-with-resolvers
- [ ] Update all pages' see also section to use the new guidelines; consistently mention relevant guides and main API reference pages
  - https://github.com/mdn/content/pull/28668
  - https://github.com/mdn/content/pull/28799
- [ ] Upgrade the "closures" page to talk everything about scopes and declarations

Of course, other issues will be worked on as I receive them, others' PRs will be reviewed by me, and more casual PRs will be sent when I feel necessary.

**Comment by postmeback** [comment]
Is there any way, I can help you on this `summer internship` ?

**Comment by Josh-Cena** [comment]
@postmeback Thanks for your interest, but these are marked as my work—most of these are establishing editorial conventions so they are hard to delegate to external contributors. Also to clarify: this is not a summer internship; it's just because I'm too busy during the school term and just got more time during the break :)

**Comment by postmeback** [comment]
@Josh-Cena , thanks for the update. Hopefully, you can accomplish all the given task within time.

**Comment by chrisdavidmills** [comment]
@Josh-Cena Just as an FYI Josh (as I know you are deep into this stuff) — I was intending to start documenting JS iterator helpers very soon, and I just wanted to check that I wouldn't be overlapping with any work you are doing.

**Comment by Josh-Cena** [comment]
https://github.com/mdn/content/pull/28677

**Comment by Josh-Cena** [comment]
My summer has ended, so I'm closing this. I ended up finishing/near-finishing more than half of them, but because I spent most of the summer enjoying myself, the list is not all checked. I will continue to work on these when I have the time. My most significant effort this summer has been my https://github.com/jc-verse/mdn-checker project, which helped me make many of the refactoring PRs.

**Comment by hamishwillee** [comment]
@Josh-Cena - I can't believe you enjoyed your summer and still did all this. Thanks very very much.

**Comment by bsmth** [comment]
> @Josh-Cena - I can't believe you enjoyed your summer and still did all this. Thanks very very much.

Ditto, well done on these improvements - thank you!

**Comment by Josh-Cena** [comment]
Thanks! Working on open source is part of the process of enjoying myself as well 😀
