### ISSUE TITLE
Issue with "Date.prototype.valueOf()": (short summary here please)

### ISSUE THREAD

**Issue by DirkRedeker** [mdn/content#2684]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/valueOf

#### What information was incorrect, unhelpful, or incomplete?
The code example is wrong

#### Specific section or headline?

Code snippet

#### What did you expect to see?

const date1 = new Date(Date.UTC(96, **_1, 2,_** 3, 4, 5));

console.log(date1.valueOf());
// expected output: 823230245000

const date2 = new Date('**_02 Feb_** 1996 03:04:05 GMT');

console.log(date2.valueOf());
// expected output: 823230245000

**I expected BOTH to be FIRST or SECOND of Februray!!**

#### Did you test this? If so, how?
NO, but is obvious!

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/valueof`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/valueOf
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/valueof/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this :+1:

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander go for it! ;-)

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills where can I find the interactive exmaples?

I tried to search with find in content for *pages/js/date-valueof.html"* as specified in the html document *<div>{{EmbedInteractiveExample("pages/js/date-valueof.html")}}</div>*

But I wasn't able to find it.

**Comment by chrisdavidmills** [comment]
Interactive examples are found in https://github.com/mdn/interactive-examples

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills ah okay, ty 😄 ,  I have even contributed to interactive-examples last year :D

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills now I have updated in the other repository the file *date-valueof.js*

But the changes are not made when I run it by yarn start.

Here I changed the second parameter to a *2*
![Bildschirmfoto 2021-02-26 um 19 54 28](https://user-images.githubusercontent.com/44900696/109342643-71718c00-786c-11eb-92ad-709491005bd4.png)

but runnning on localhost with yarn it will not be affected.

![Bildschirmfoto 2021-02-26 um 19 55 27](https://user-images.githubusercontent.com/44900696/109342732-95cd6880-786c-11eb-8514-06cd39a1e5af.png)

What do I miss here?

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander The trouble here is that the `yari` and `content` repos are not connected to the `interactive-examples` repo in any way. If you've made a change to `interactive-examples` locally and/or remotely, it won't show up in your local Yari test server. It won't show up on MDN at all until it is merged, and then a build step is done to compile all the updated examples.

Fortunately, the `interactive examples` repo has its own local testing server you can use to test your changes. See https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING.md#testing for the relevant commands.

**Comment by CreaTorAlexander** [comment]
The example is actually correct. The reason why is it here *const date2 = new Date('02 Feb 1996 03:04:05 GMT');* second and here *const date1 = new Date(Date.UTC(96, 1, 2, 3, 4, 5));* is that you give the month in a range from 0 to 11 what means february is 1.

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills I think we can close this issue because the example is actually correct. I will unassign me

**Comment by chrisdavidmills** [comment]
OK, thanks @CreaTorAlexander !
