### ISSUE TITLE
Incorrect example code for Cache.matchAll

### ISSUE THREAD

**Issue by joshkel** [mdn/content#26841]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Cache/matchAll

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The example code uses the `Response` results from `matchAll` as parameters to `cache.delete`. However, according to the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Cache/delete) and TypeScript definitions, and based on my own testing, `Cache.delete` takes a Request or a URL, not a Response.

### What did you expect to see?

Valid example code

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/Cache/delete, https://w3c.github.io/ServiceWorker/#cache-delete

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/cache/matchall`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Cache/matchAll
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/cache/matchall/index.md
* Last commit: https://github.com/mdn/content/commit/1f216a70d94c3901c5767e6108a29daa48edc070
* Document last modified: 2023-04-07T06:13:50.000Z

</details>

**Comment by postmeback** [comment]
Does it help??

https://github.com/mdn/content/pull/26895

@joshkel
