### ISSUE TITLE
Firefox does not support Feature-Policy HTTP header

### ISSUE THREAD

**Issue by annevk** [mdn/content#2685]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1694922 for context. While we did implement this, we never shipped it. We plan on eventually shipping the `Permissions-Policy` HTTP header, which is the new name of this header (Feature Policy got renamed to Permissions Policy).

**Comment by chrisdavidmills** [comment]
Thanks @annevk . 

@hamishwillee , can you investigate this one? I think for now it is probably a matter of fixing the BCD for `Feature-Policy`, as we wrongly say it was shipped in 74.

Then once `Permissions-Policy` is actually shipped, we can update the docs accordingly in a DDN cycle.

**Comment by evilpie** [comment]
I had also opened https://github.com/mdn/browser-compat-data/issues/9264

**Comment by hamishwillee** [comment]
Yes. 
- [ ] [BCD update](https://github.com/mdn/browser-compat-data/pull/9280) 
- [ ] Release note removal from FF74 - done in #2702
  - I assume [Cross-Origin-Resource-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy) enabled in that release was enabled.
- [ ] Experimental features addition - done in #2702 too

Note that the BCD is the main thing. It might be time to update that to Permission-Policy - I'm in dicussion.

**Comment by hamishwillee** [comment]
All the bits of this are done, so closing.
