### ISSUE TITLE
stream is not defined

### ISSUE THREAD

**Issue by Dacodemon** [mdn/content#26867]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createBiquadFilter

### What specific section or headline is this issue about?

stream is not defined

### What information was incorrect, unhelpful, or incomplete?

I tried to run this code but on audioCtx.createMediaStreamSource(stream) stream is not defined

### What did you expect to see?

stream to be defined

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/baseaudiocontext/createbiquadfilter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createBiquadFilter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/baseaudiocontext/createbiquadfilter/index.md
* Last commit: https://github.com/mdn/content/commit/135b8311a5e3d12789e8421845be3ce026ef72b8
* Document last modified: 2023-04-06T14:57:25.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! This is an excerpt of a longer demo code. It's already mentioned in the text above:

> For more complete applied examples/information, check out our Voice-change-O-matic demo (see app.js lines 108–193 for relevant code).

**Comment by Dacodemon** [comment]
oh okay thanks, sorry for the mistake
