### ISSUE TITLE
Provide an example of SHA digesting a file

### ISSUE THREAD

**Issue by Zectbumo** [mdn/content#26872]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

This example demonstrates a simple digest of a small message which is one of the typical uses. Another typical use for a digest would be to digest a file (one larger than system memory). Would you please give an example of digesting a file that is larger than system memory?

### What did you expect to see?

An example digesting a file or file.stream()

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/subtlecrypto/digest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/subtlecrypto/digest/index.md
* Last commit: https://github.com/mdn/content/commit/101ffc9479db6aaa530f2aac3992734dd97d1b86
* Document last modified: 2023-04-08T06:08:46.000Z

</details>

**Comment by yarusome** [comment]
There's a complete example on [Non-cryptographic uses of SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API/Non-cryptographic_uses_of_subtle_crypto#hashing_a_file).

**Comment by Zectbumo** [comment]
Thank you for the link. I believe it would server users of `digest()` better if this example lived on the main API page instead of tucked away in some "non-crypto" page. It is a digest after all and common use examples of a digest should be included and not matter if it is crypto or non-crypto related.
I looked over the example and noticed it is not using best practices as it is using `ArrayBuffer` which loads the entire file into memory before processing.
Also, this document says:
> Reading the files to an ArrayBuffer using a FileReader

which it doesn't actually use a `FileReader` in the example.
