### ISSUE TITLE
Provide a definition for binding list

### ISSUE THREAD

**Issue by guest271314** [mdn/content#26875]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_operator

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_operator#using_the_comma_operator_to_join_assignments

### What information was incorrect, unhelpful, or incomplete?

Unclear whether `let a, b, c;` i use of comma operator or `BindingList`. The specification doesn't really clearly define what I `BindingList` is that I can see.

MDN does not have a `BindingList` entry.

### What did you expect to see?

Disambiguity between Comma operator and `BindlingList`.

### Do you have any supporting links, references, or citations?

- https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-comma-operator
- https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#prod-BindingList

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/comma_operator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_operator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/comma_operator/index.md
* Last commit: https://github.com/mdn/content/commit/d85a7ba8cca98c2f6cf67a0c44f0ffd467532f20
* Document last modified: 2023-04-05T04:57:48.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, anything that follows `let` is a binding list, not comma operator. Comma operator must be able to join arbitrary expressions, but `let foo(), bar()` is clearly illegal. I assume you've already read the paragraph above:

> The comma operator is completely different from commas used as syntactic separators in other locations, which include:
>
> Binding lists in `let`, `const`, or `var` declarations (`const a = 1, b = 2;`)

A "binding list" is just a list of bindings (a.k.a. variables). I don't think we can explain them further here, neither is it pedagogically valuable as long as you get how the syntax works.

**Comment by guest271314** [comment]
> Hi, anything that follows let is a binding list,

You have never actually defined what a binding list is in your documentation, so you need to do that.

> neither is it pedagogically valuable as long as you get how the syntax works.

Yes, it is valuable, else I would not have asked the question.

> I assume you've already read the paragraph above:

No. Where did you get that from?

**Comment by guest271314** [comment]
Alright, I found 

> Binding lists in [let](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let), [const](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const), or [var](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var) declarations (const a = 1, b = 2;)

MDN never bother to define what a Binding lists are.

**Comment by Josh-Cena** [comment]
A binding list is a list of bindings; a binding is an association of an identifier with a value.

I'm curious how the distinction between "binding list" and "comma operator" help you understand syntaxes—their respective syntaxes are pretty unambiguous anyway.

**Comment by guest271314** [comment]
>  but definitions are immaterial when they are disembodied from practical usage. I'm curious how the distinction between "binding list" and "comma operator" help you understand syntaxes—their respective syntaxes are pretty unambiguous anyway.

This prompted my question [What is this syntax `let main = arr, first;` ?](https://www.reddit.com/r/learnjavascript/comments/13ndhn4/what_is_this_syntax_let_main_arr_first/).

Not only is `BindingList` not defined in MDN, nor is that term clearly defined in Ecmascript specification.

This 

> Binding lists in let, const, or var declarations (const a = 1, b = 2;)

is helpful only when citing the canonical definition you provided 

> A binding list is a list of bindings; a binding is an association of an identifier with a value

with a literal `,` being written/depicted to denote the differences between Comman operator and `BindlingList`, or `SequenceExpression` (AST Explorer).

Right now we have only disparate parts of what is going on here and there, not in a single documentation demonstrating the differences between when the `,` is a `BindingList` or Comma operator, for disambiguation.

Again, you are using the term "binding list" as if you can cite the definition _you_ provided as a canonical link on MDN. You cannot do that right now.

**Comment by Josh-Cena** [comment]
Okay, let's provide a definition for "binding list". I may one day rewrite the `const`/`let`/`var` pages anyway.

**Comment by Josh-Cena** [comment]
FYI, "binding list" in the ES spec is just a grammar production. It's a convenient alias to reuse the same grammar between multiple definitions. It has no runtime significance.

**Comment by guest271314** [comment]
Yes, there is no formal definion either besides

```
BindingList[?In, ?Yield, ?Await] ,
```

which is not a `BindingList` when `var` is used

```
VariableDeclarationList[?In, ?Yield, ?Await] ,
```

A Note on `let` and Comma operator pages, linking to each other, for disambiguation, should suffice for this case - on MDN.

> FYI, "binding list" in the ES spec is just a grammar production.

There really is no "just" when dealing with technical writing. Write it out formally, with Notes, Examples, and we should really start having a Disambiguation section, where necessary.
