### ISSUE TITLE
Django virtual environment set up .zshrc not mentioned

### ISSUE THREAD

**Issue by clhjoburg** [mdn/content#2688]
On the page: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/development_environment

The documentation only discusses bash files but on MacOS Catalina and later the .zshrc file needs to be used. Furthermore this file isn't present in the home directory by default and in my case needed to be created.

Othewise, thanks for the great documentation!

**Comment by hamishwillee** [comment]
@clhjoburg Could you please create a PR to fix this? I have no mac to test any such change on.

**Comment by CreaTorAlexander** [comment]
I can update it with an alternative solution for users of zsh.

**Comment by Ryuno-Ki** [comment]
Thanks, @CreaTorAlexander

**Comment by hamishwillee** [comment]
Hi @CreaTorAlexander 
How are you going with this? Would it be better if I made the modification and then you sanity checked it?

**Comment by CreaTorAlexander** [comment]
Hi @hamishwillee 
that sounds good :+1:

**Comment by Ryuno-Ki** [comment]
Ping @hamishwillee

**Comment by hamishwillee** [comment]
Thanks, I haven't forgotten. Just not a priority IMO.
