### ISSUE TITLE
An example on calculating squares needs correction

### ISSUE THREAD

**Issue by yurigr** [mdn/content#26897]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code#calculating_squares

### What information was incorrect, unhelpful, or incomplete?

Probably, textContent should be replaced with innerText so that new line formatting '\n' becomes possible in the output. 

### What did you expect to see?

```js
function calculate() {
  for (let i = 1; i < 10; i++) {
    const newResult = `${i} x ${i} = ${i * i}`;
    results.innerText+= `${newResult}\n`; // replacement done
  }
  results.innerText+= "\nFinished!";  // replacement done
}

// this makes displaying every calculation on a new line
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/looping_code`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/looping_code/index.md
* Last commit: https://github.com/mdn/content/commit/65b9418c7d0e3a331ac50249adf0024f44789923
* Document last modified: 2023-05-09T00:34:38.000Z

</details>

**Comment by postmeback** [comment]
I believe, in this code-block, the main intention is to learn loop. Also, `textContent` makes the every calculation in a new line. 

<img width="956" alt="Moz-01" src="https://github.com/mdn/content/assets/14862687/64a75c80-d6d4-4db8-a3d8-9518d353b99d">

**Comment by hamishwillee** [comment]
Closing as invalid. 

As you can see above the code does render properly. This works because the log window is implemented as a `<pre>` element. This element respects white space and line breaks. So the line `${newResult}\n` creates a new line after each element is added.

Thanks for the suggestion though.
