### ISSUE TITLE
possibly sample code race condition

### ISSUE THREAD

**Issue by asebian** [mdn/content#26905]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#simulating_private_constructors

### What information was incorrect, unhelpful, or incomplete?

Not being an expert I wonder whether there could be a race condition issue with the static field `#isInternalConstructing` in the sample code.

### What did you expect to see?

What if we passed a static private secret instead?
```
class PrivateConstructor {
  static #secret = Math.random();

  constructor(secret) {
    if(secret !== PrivateConstructor.#secret)
      throw new TypeError("PrivateConstructor is not constructable");
  }

  static create() {
    return new PrivateConstructor(PrivateConstructor.#secret);
  }
}
```

### Do you have anything more you want to share?

Thanks for sharing!
Cheers!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/classes/private_class_fields`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/classes/private_class_fields/index.md
* Last commit: https://github.com/mdn/content/commit/1c3289e60a5d72973d49f046e457c477eff23898
* Document last modified: 2023-04-09T19:29:33.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, why would there be a race condition? The flag is set, read, then reset all synchronously; there's never another async job that causes the event loop to yield.

**Comment by asebian** [comment]
Maybe I'm wrong.
I thought if two jobs called `create` both rely on `#isInternalConstructing = true` which  is set back to `false` by the constructor finishing first.
