### ISSUE TITLE
Issue with "Headers()": the term "inherits" is misleading

### ISSUE THREAD

**Issue by Andrew-Cottrell** [mdn/content#2690]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers

#### What information was incorrect, unhelpful, or incomplete?

The term *inherits* — in a JavaScript context — implies that a change to a parent _thing_ (e.g. a prototype object) affects a child _thing_.

> the new Headers object **inherits** its data from the existing Headers object

The above sentence, in the MDN article, incorrectly implies a change to the existing Headers object affects the new Headers object.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers#parameters

#### What did you expect to see?
Another term, without a misleading implication, instead of "inherits"; for example

>the new Headers object **copies** its data from the existing Headers object

#### Did you test this? If so, how?
```
var existing = new Headers({"a": "0", "b": "1", "c": "2"});
var subject = new Headers(existing);
existing.set("d", "3");
Array.from(subject).length; // 3 rather than 4
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/headers/headers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/headers/headers/index.html
* Last commit: https://github.com/mdn/content/commit/11a98a59fca5f2e448d9e4b70e3c8a538c47b201
* Document last modified: 2021-02-19T19:45:18.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this 👍

**Comment by Ryuno-Ki** [comment]
Take it away, @CreaTorAlexander
