### ISSUE TITLE
Glossary for Baseline should be brief

### ISSUE THREAD

**Issue by estelle** [mdn/content#26912]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Baseline/Compatibility

### What information was incorrect, unhelpful, or incomplete?

Not sure if this Baseline entry is appropriate for the MDN glossary. If we keep it, we should present it like other projects. 

Perhaps using [cardDAC](https://developer.mozilla.org/en-US/docs/Glossary/CardDAV) as a template:

CardDAV (vCard Extension to {{Glossary(“WebDAV”)}}) is a {{glossary(“protocol”)}} standardized by the {{Glossary(“IETF”)}} and used to remote-access or share contact information over a {{glossary(“server”)}}.

And link to a blog post or article with all the content. 

### What did you expect to see?

If included, i expected it to be referred to as "Web Platform Baseline"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/baseline/compatibility`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Baseline/Compatibility
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/baseline/compatibility/index.md
* Last commit: https://github.com/mdn/content/commit/bb6092c4230b69c2eceae6910af68c73955cae1c
* Document last modified: 2023-05-10T14:53:07.000Z

</details>

**Comment by postmeback** [comment]
Hi @estelle ,

https://github.com/mdn/content/pull/26779
this PR may be related with this topic. Can you have a look ?

**Comment by Josh-Cena** [comment]
@estelle, could you clarify what you believe should be deleted, added, or modified?

**Comment by estelle** [comment]
> @estelle, could you clarify what you believe should be deleted, added, or modified?

The glossary entries when defining projects provide one to two sentences about the project and link to the project page. This entry reads like a cross between a blog post that should be hosted elsewhere that a glossary definition could post to and an advertisement. Most of it should be deleted.

As noted in the original issue, i think [cardDAC](https://developer.mozilla.org/en-US/docs/Glossary/CardDAV)  may be a good template for this content. It could be used a as a template:

```
CardDAV (vCard Extension to {{Glossary(“WebDAV”)}}) is a {{glossary(“protocol”)}} standardized by the {{Glossary(“IETF”)}} and used to remote-access or share contact information over a {{glossary(“server”)}}.
```
with a link to a blog post or article with all the content that is currently in the blog post, um, i mean, glossary entry.

**Comment by Josh-Cena** [comment]
Pinging @ddbeck @Rumyra @LeoMcA who probably can provide feedback here

**Comment by ddbeck** [comment]
Baseline was put in as a glossary entry as a bit of a compromise, after some discussion with @Rumyra and @LeoMcA. The page provides a definition of Baseline itself (i.e., Baseline as a work of the WebDX CG), but it also serves as reader-facing help text for the Baseline banners on reference pages (i.e., the MDN-specific presentation of Baseline in the form of banners).

An alternative we considered was putting the page in the MDN document tree (e.g., with [_Banners and notices_](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Banners_and_notices)), but that's all documentation for page authors. It seemed like a poor fit, since the audience of the Baseline glossary page is web developers.

MDN is not systematically documented _for readers_, so there's no natural home for content that helps readers understand MDN's own content conventions. If such a thing came into existence, I'd be first in line to move the Baseline page there.

**Comment by estelle** [comment]
I drafted a PR as a suggestion to make the Baseline glossary more of a "glossary" entry. https://github.com/mdn/content/pull/34385

Baseline (compatibility)

**Baseline** identifies newer web platform features, including APIs, CSS property sets, and JavaScript syntaxes, that works consistently across popular browsers. Baseline defines newer web features as being either widely available, newly available, or having limited availability in the following browsers:

- Apple Safari (iOS)
- Apple Safari (macOS)
- Google Chrome (Android)
- Google Chrome (desktop)
- Microsoft Edge (desktop)
- Mozilla Firefox (Android)
- Mozilla Firefox (desktop)

Baseline is a summary guide to browser support, but does address feature accessibility, usability, performance, security, or other concerns.

**Baseline badges**

(green image)

Features listed as widely available have a consistent history of browser support for at least 2.5 years.

(blue image)

Features listed as newly available works in all stable browser versions, but may not work with older browsers and devices.

(grey image)

Features listed with limited availability are not yet available in all browsers.

**See also**

- [Cross browser testing](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing)
- [web-platform-dx/web-features repository](https://github.com/web-platform-dx/web-features)
- [W3C WebDX Community Group](https://www.w3.org/community/webdx/)
- [mdn/browser-compat-data repository](https://github.com/mdn/browser-compat-data)

**Comment by Josh-Cena** [comment]
Should be fixed by https://github.com/mdn/content/pull/34385
