### ISSUE TITLE
When in Chrome People Can Tab to READONLY Items in the Form under Heading "Read-only and read-write"

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#26910]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes

### What specific section or headline is this issue about?

Read-only and read-write

### What information was incorrect, unhelpful, or incomplete?

When in Chrome people can tab to READONLY items in the form under the heading "Read-only and read-write".

Please see the attached screenshot.

<img width="960" alt="mdn - Read-only and read-write - in chrome people can tab to readonly items" src="https://github.com/mdn/content/assets/10423487/9df14586-7bbc-4d92-abd4-f3678c3360e8">

### What did you expect to see?

I would expect to not be able to tab to the READONLY form INPUT fields.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/ui_pseudo-classes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/ui_pseudo-classes/index.md
* Last commit: https://github.com/mdn/content/commit/65b9418c7d0e3a331ac50249adf0024f44789923
* Document last modified: 2023-05-09T00:34:38.000Z

</details>

**Comment by rschristian** [comment]
> When in Chrome people can tab to READONLY items

Why do you think this is an issue? Form items with `readonly` are still in the tab order for accessibility concerns, every browser matches behavior here.

Adding in `tabindex="-1"` a) strays from web defaults and b) reduces accessibility.

**Comment by jfc3-dol** [comment]
@rchavelas 
It seems odd to me to be able to tab to an item people can't edit or add text/content to. But if others think it's the best way, I'm okay with that.

**Comment by Josh-Cena** [comment]
Yes, we don't plan to change browser defaults here. If they believe it's reasonable for readonly fields to be tabbed into, they must have a reason (for example, it indicates field values which you will be submitting, just you have no right to edit; nevertheless you should have the right to read and access them).
