### ISSUE TITLE
Is the first $ necessary in this RegExp?

### ISSUE THREAD

**Issue by krave1986** [mdn/content#26915]
This is the code I am referencing.
https://github.com/mdn/content/blob/610522d12e27fc70bcfd67d183c7ab1f38956a62/files/en-us/web/javascript/guide/regular_expressions/groups_and_backreferences/index.md?plain=1#LL175C26-L175C27

`/(function\s+)(?<name>[$_\p{ID_Start}][$\u200c\u200d\p{ID_Continue}]*)/du`

Since `\s+` can greedily cover both spaces and line feeds, `$` in `[$\u200c\u200d\p{ID_Continue}]` can cover the line end. What is the point of the first `$` in `[$_\p{ID_Start}]`?

Can we remove it from the code? If not, why?

**Comment by Josh-Cena** [comment]
Hi! This `$` is part of a character class, so it matches the literal dollar sign character. It has to be separate because it's not a Unicode ID_Continue.
