### ISSUE TITLE
response.body is not an asynchronous iterable

### ISSUE THREAD

**Issue by zxcvc** [mdn/content#26921]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream

### What information was incorrect, unhelpful, or incomplete?

In the last example on this page try to use "for await... "of" to iterate over response.body. Since response.body is not an asynchronous iterable, the code is incorrect.

### What did you expect to see?

Delete this example.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/readablestream`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/readablestream/index.md
* Last commit: https://github.com/mdn/content/commit/d41c5446d4ef257280fae9b78e2298ced8954a95
* Document last modified: 2023-05-09T20:58:09.000Z

</details>

**Comment by Josh-Cena** [comment]
Please see the [browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#browser_compatibility). Firefox is the only browser that implements this.

**Comment by pamelafox** [comment]
@Josh-Cena I just ran into this as well. The way its worded, it sounds like it's well supported. What do you think of adding a note or link to that table?
The section in question: https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams#consuming_a_fetch_using_asynchronous_iteration

**Comment by pamelafox** [comment]
Ah, and on the page where I encountered it, there is no browser table.

**Comment by Josh-Cena** [comment]
@pamelafox It's an existing unfortunate situation that guide articles are very compatibility-unaware. This is mostly a pragmatic concern because we don't have the ability to keep compatibility notes always up-to-date, so it's kind of assumed that you would verify all features you use are available in your target environment (or use a polyfill if they are not).

**Comment by pamelafox** [comment]
Okay, fair, thanks for the reply!
