### ISSUE TITLE
Cannot See the Error Message Telling Me the E-mail Address Problem

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#26932]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

### What specific section or headline is this issue about?

Implementing a customized error message

### What information was incorrect, unhelpful, or incomplete?

I cannot see the error message telling me the e-mail address is incorrect, using Chrome on Windows 10.

Remember to check the rest of the examples on the page to see if they have error message issues too.

Please see the attached screenshot.

<img width="960" alt="mdn - I cannot see the error message telling me the e-mail address is incorrect using Chrome on Windows 10" src="https://github.com/mdn/content/assets/10423487/d96b6023-378e-4298-a6d3-f4b46b884bb7">

### What did you expect to see?

I expected to see the e-mail address error message.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/form_validation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/form_validation/index.md
* Last commit: https://github.com/mdn/content/commit/d85a7ba8cca98c2f6cf67a0c44f0ffd467532f20
* Document last modified: 2023-04-05T04:57:48.000Z

</details>

**Comment by postmeback** [comment]
`{{EmbedGHLiveSample("learning-area/html/forms/form-validation/custom-error-message.html", '100%', 80)}}`

This is the live example that is being used, not sure about the second and third parameter though. Would be nice if someone guides me

**Comment by wbamberg** [comment]
@postmeback , thank you!

This needs fixing in the https://github.com/mdn/learning-area repo.

For instance you could try adding a rule like:

```css
form. {
  margin: 3rem 0;
}
```

...to the style sheet for the page: https://github.com/mdn/learning-area/blob/f2dbab87fda2befa8fe3fde14e2e75a86e47662c/html/forms/form-validation/custom-error-message.html#L7-L14

You'd have to adjust the [height of the live sample embed](https://github.com/mdn/yari/blob/main/kumascript/macros/EmbedGHLiveSample.ejs#L7) as well, something like:

```
{{EmbedGHLiveSample("learning-area/html/forms/form-validation/custom-error-message.html", '100%', 120)}}
```

But as the issue reporter says, check all the examples (at least in this page) for the same problem.

**Comment by postmeback** [comment]
Hi @wbamberg , I have checked all the live-example in this page. Only this example has problem, others are fine.

**Comment by postmeback** [comment]
Two separate PR's are create to fix this issue. Requesting for review.

**Comment by postmeback** [comment]
Thanks @wbamberg 😃
