### ISSUE TITLE
Expect the INPUT Field LABEL to Tell Me the Minimum Length of the E-mail Address

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#26935]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

### What specific section or headline is this issue about?

A more detailed example

### What information was incorrect, unhelpful, or incomplete?

The INPUT field LABEL should tell the person that the e-mail address needs to be eight characters or more. Some people may have a shorter e-mail address like the one in the INPUT field below.

The same issue applies to the example page linked below.

**NOTE** - The example is right above the "Validating forms without a built-in API" heading.

Please see the attached screenshot.

<img width="960" alt="mdn - INPUT field LABEL needs ot tell person the minimum length of the e-mail address" src="https://github.com/mdn/content/assets/10423487/d9ee139b-00d4-4aca-86dc-e4179278fe01">

### What did you expect to see?

I would expect the INPUT field LABEL to tell me the minimum length of the e-mail address.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/form_validation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/form_validation/index.md
* Last commit: https://github.com/mdn/content/commit/d85a7ba8cca98c2f6cf67a0c44f0ffd467532f20
* Document last modified: 2023-04-05T04:57:48.000Z

</details>

**Comment by postmeback** [comment]
Hi,

If you go the source-code you will find it over there.

![image](https://github.com/mdn/content/assets/14862687/eabb848e-c010-49d6-abd0-229ac4930932)

**Comment by queengooborg** [comment]
@postmeback, the author of this issue knows that the minimum length is set to 8, so pointing out the source code for the requirement is not helpful.  What they're requesting is that the input _label_ is changed to indicate this requirement to end users.

**Comment by postmeback** [comment]
@queengooborg , thanks for pointing it out.

**Comment by irinakramer** [comment]
@queengooborg,@postmeback --- Hi guys, I'd like to work on this issue. Would it be helpful to update the label so it reads like this?
`<span>Please enter an email address at least 8 characters long:</span>`

This update would need to be done both in the index.md file and in the live result file, correct? 
https://github.com/mdn/content/edit/main/files/en-us/learn/forms/form_validation/index.md
https://mdn.github.io/learning-area/html/forms/form-validation/detailed-custom-validation.html

Thanks!!

**Comment by postmeback** [comment]
@irinakramer , I cannot help you out on this. Sorry 😞

**Comment by queengooborg** [comment]
Hey @irinakramer, thank you for your interest!  That label looks good to me, and should resolve this issue well!

For the second file (the live example), the source lives right here: https://github.com/mdn/learning-area/blob/main/html/forms/form-validation/detailed-custom-validation.html

**Comment by Rumyra** [comment]
@postmeback, please note that we have dozens of people watching this repository. For every comment posted, these people may receive a notification.

Please be respectful of other people’s time and attention and avoid taking actions that might cause excessive notifications. Issues should describe a problem or propose an actionable solution. Thank you for understanding!

**Comment by hamishwillee** [comment]
The smallest valid email is 3 characters, but the actual number of email addresses with only 8 characters is effectively 0. That's intuitively obvious, but also confirmed by this [unverified data I found on the internet and am choosing to trust :-)](https://www.atdata.com/blog/long-email-addresses#:~:text=So%20over%20the%20last%20few,show%20at%20least%2031%20characters.). Further, if you enter `a@f` you are immediately told about the requirement - so it is not like it is missing information.

Adding this extra text for a user when no "real user" will need it is pointless, and I don't think we should be showing "how to" for things that developers should not do in practice.

Note, if this was a password field then I would be supportive - if you have a password that has unexpected behaviour then you need to provide information about that up front.

Does this make sense?

@irinakramer Sorry, I appreciate that you have put work into this -  If you agree this is not needed we'll close this and the associated PRs.

**Comment by irinakramer** [comment]
@hamishwillee Thank you for the insight, it makes sense. I'm ok with closing these PRs.

**Comment by hamishwillee** [comment]
Closing. Thanks @irinakramer - appreciate you taking the time to try fix. Also @jfc3-dol for highlighting potential issues.
