### ISSUE TITLE
`animation` shorthand CSS property lacks syntax – please add

### ISSUE THREAD

**Issue by SetTrend** [mdn/content#26947]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/animation

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/animation#syntax

### What information was incorrect, unhelpful, or incomplete?

The information provided in the **Syntax** paragraph is only a collection of examples.

Please add full syntax definition according to [standard syntax notational conventions](https://www.ibm.com/docs/en/tslm/1.4.0?topic=cli-syntax-conventions).

### What did you expect to see?

An unambiguous and comprehensive syntax notation using standard syntax description conventions.

### Do you have anything more you want to share?

Please provide full, unambiguous and comprehensive syntax notation according to standard syntax description conventions to all CSS shorthand attributes (and other attributes, where applicable), so your pages will be available to be used as a reference.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/animation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/animation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/animation/index.md
* Last commit: https://github.com/mdn/content/commit/9ff91b6aef7d12e6a0ffd36de8b2d510731385eb
* Document last modified: 2023-04-26T23:25:33.000Z

</details>

**Comment by yarusome** [comment]
The standard definition is down at the "Formal syntax" [section](https://developer.mozilla.org/en-US/docs/Web/CSS/animation#formal_syntax), although the intermediate sections are indeed too lengthy to get a hint of the presence of this section.

**Comment by wbamberg** [comment]
Closed per https://github.com/mdn/content/issues/26947#issuecomment-1560926557. 

@yarusome , you might be interested in this discussion: https://github.com/orgs/mdn/discussions/218 which ran out of steam but which I think we should still consider.
