### ISSUE TITLE
"word-break: normal;" !== "word-break: break-word;"

### ISSUE THREAD

**Issue by feastdesignco** [mdn/content#26948]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

### What specific section or headline is this issue about?

Deprecation note

### What information was incorrect, unhelpful, or incomplete?

```
Note: While word-break: break-word is deprecated, it has the same effect, when specified, as word-break: normal
```

This is incorrect, as demonstrated by the on-page example: 
![image](https://github.com/mdn/content/assets/5629719/0284342a-f5b0-4cb9-811c-f5058babca52)

word-break: normal;
and
word-break: break-word; 

Function entirely different.

### What did you expect to see?

Correct information.

### Do you have any supporting links, references, or citations?

The on-page example demonstrates that this is false: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

### Do you have anything more you want to share?

Google Chrome 
Version 112.0.5615.49 (Official Build) (arm64)

MacOS Ventura
Version 13.2.1

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/word-break`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/word-break/index.md
* Last commit: https://github.com/mdn/content/commit/b82ff59aab7883b7bb2222cf9f9f9b6eed818e08
* Document last modified: 2023-02-21T06:13:19.000Z

</details>

**Comment by yarusome** [comment]
The actual note is:

> **Note:** While `word-break: break-word` is deprecated, it has the same effect, when specified, as `word-break: normal` ***and `overflow-wrap: anywhere`***[…]

which is indeed true on Firefox.

**Comment by feastdesignco** [comment]
Checked in Firefox 113.0.2 (64-bit) 

And normal and break-word behave entirely different: 

<img width="1116" alt="image" src="https://github.com/mdn/content/assets/5629719/3ad169a5-1cf0-4699-8e42-a2db89a73515">

**Comment by Josh-Cena** [comment]
@feastdesignco What @yarusome meant is that the note also tells you to add `overflow-wrap: anywhere` in order for `word-break: normal` to achieve the effect of `break-word`.
