### ISSUE TITLE
Update Browser Screenshots to recent versions in Form Examples (Learn: Basic native form controls)

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#26951]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls

### What specific section or headline is this issue about?

Single line text fields

### What information was incorrect, unhelpful, or incomplete?

I suggest updating the browser screenshots for all the Web Forms section pages since the browser version is about 40 versions behind.

Updating the content to discuss how things are currently working instead of how they worked before.

Please see the attached screenshot as an example of the older browser versions.

<img width="960" alt="mdn - I suggest updating the browser screenshots for all the Web Forms section pages since the browser version is about 40 versions behind" src="https://github.com/mdn/content/assets/10423487/f42f6f1c-c902-4c92-aefb-ea09b3a26acb">

### What did you expect to see?

I expect to see updated screenshots of browser version examples.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/basic_native_form_controls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/basic_native_form_controls/index.md
* Last commit: https://github.com/mdn/content/commit/65b9418c7d0e3a331ac50249adf0024f44789923
* Document last modified: 2023-05-09T00:34:38.000Z

</details>

**Comment by hamishwillee** [comment]
@jfc3-dol That would be really welcome - would you like to add a PR for this?

This would not be a priority for me unless I knew the underlying feature had changed, e.g. to support some new kind of UI behaviour, or customisation. Then I might bundle that as part of the technical content update.

I'll add a tag to ask for community support.

**Comment by abhishekrnjn** [comment]
Hi @hamishwillee, pls check if the code used to generate input fields are correct?

![Screenshot 2023-06-16 at 6 40 10 PM](https://github.com/mdn/content/assets/28575935/80e10c35-f115-433b-aca4-4ca6e4dcc1bf)


I got following screenshot in safari, chrome and firefox. 
![Screenshot 2023-06-16 at 6 34 39 PM](https://github.com/mdn/content/assets/28575935/afd4d3f2-5783-46fd-8a62-3a6141990ff8)

![Screenshot 2023-06-16 at 6 34 30 PM](https://github.com/mdn/content/assets/28575935/a1bc10f5-0567-4ec5-9b47-ba5b339cd50c)


![Screenshot 2023-06-16 at 6 42 33 PM](https://github.com/mdn/content/assets/28575935/e4519a1e-590a-4248-b820-fd04e5da9057)

**Comment by hamishwillee** [comment]
@abhishekrnjn Yes, that looks fine to me. Seems to match the reference docs https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled
