### ISSUE TITLE
Migration guides for deprecated apis

### ISSUE THREAD

**Issue by kball** [mdn/content#2696]
It came up in a JSParty conversation with @Elchi3 that MDN does not currently systematically include migration guides for deprecated APIs, and that this would be a great addition.

For example, as the Temporal proposal becomes widely supported, a migration guide for migrating from Date to Temporal

**Comment by Josh-Cena** [comment]
We now have the editorial convention that deprecation notices should be accompanied by a note saying what it's replaced with. In the temporal situation, `Date` is not going to be "deprecated" (maybe "discouraged"), so we won't recommend people to move off it. Moreover it's not trivial to migrate Dates to Temporals as you have to consider what you actually use your Date for. Anyway if it's just about temporal we can close it until we actually write the docs; if it's general, then it's too broad to be actionable. It has sat for 3 years and probably shouldn't be anymore.
