### ISSUE TITLE
CSS env() - case sensitive example uses no capital letters

### ISSUE THREAD

**Issue by joyously** [mdn/content#26996]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/env

### What specific section or headline is this issue about?

Example Values

### What information was incorrect, unhelpful, or incomplete?

This example:
```
/* 50px because UA properties are case sensitive */
padding: env(safe-area-inset-bottom, 50px);
```

### What did you expect to see?

I expected it to have some capital letters like:
```
/* 50px because UA properties are case sensitive */
padding: env(SAFE-area-inset-bottom, 50px);
```

### Do you have any supporting links, references, or citations?

earlier in the page, just above this example

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/env`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/env
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/env/index.md
* Last commit: https://github.com/mdn/content/commit/66944f622b6b51bc9c24bebbbea242138d910600
* Document last modified: 2023-02-21T05:45:53.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! This error was introduced by https://github.com/mdn/content/pull/22100, which should just be reverted.
