### ISSUE TITLE
Wrong information about `layout.css.scroll-linked-animations.enabled`

### ISSUE THREAD

**Issue by NatoBoram** [mdn/content#26994]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline/scroll

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

> From version 101: this feature is behind the `layout.css.scroll-linked-animations.enabled` preference (needs to be set to `true`). To change preferences in Firefox, visit `about:config`.

### What did you expect to see?

The correct information should be displayed; whatever that is

### Do you have any supporting links, references, or citations?

![image](https://github.com/mdn/content/assets/10495562/e6398f04-53f2-4372-adfe-c45e412722db)

In this screenshot, we can see that I am using Firefox `114.0b9`. As far as I know, 114 is greater than 101.

![image](https://github.com/mdn/content/assets/10495562/3b611f9d-2dfc-4219-b5e1-3720787ab867)

In this screenshot, we can see that `layout.css.scroll-linked-animations.enabled` is set to `true`. The browser was restarted after applying this change.

However, when I visit demos of this feature, it doesn't work.

Demos:

* https://scroll-driven-animations.style/#card-cover-to-fixed-header
* https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline/scroll

[Not animated header](https://github.com/mdn/content/assets/10495562/b987d586-8353-47a0-a4ab-db285bf123bc)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/animation-timeline/scroll`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline/scroll
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/animation-timeline/scroll/index.md
* Last commit: https://github.com/mdn/content/commit/42c1bb8c259f3f57de9f38600776cf273e3addda
* Document last modified: 2023-02-21T06:27:49.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

At least the version in https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline/scroll#examples works if I enable `layout.css.scroll-driven-animations.enabled` instead. But I'd need to do some more digging to understand the difference between that pref and `layout.css.scroll-linked-animations.enabled`.

**Comment by hamishwillee** [comment]
Thanks. This was renamed in https://bugzilla.mozilla.org/show_bug.cgi?id=1807685 in FF110. Should be fixed by https://github.com/mdn/browser-compat-data/pull/19982

**Comment by NatoBoram** [comment]
`layout.css.scroll-driven-animations.enabled` works! Thanks!
