### ISSUE TITLE
use of Promise.all() when tasks are not dependent on each other

### ISSUE THREAD

**Issue by sazk07** [mdn/content#27008]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Genre_detail_page

### What specific section or headline is this issue about?

# Controller

### What information was incorrect, unhelpful, or incomplete?

I am confused by this claim in one of the paragraphs in the Controller section:

> Because the two requests do not depend on each other, we use Promise.all() to run the database queries in parallel

This claim is again repeated on this page: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Home_page#controller

> Because the queries for document counts are independent of each other we use [Promise.all()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) to run them in parallel.

But on the MDN docs for [Promise.allSettled](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Home_page#controller), it is written:

> Promise.allSettled() is typically used when you have multiple asynchronous tasks that are not dependent on one another to complete successfully, or you'd always like to know the result of each promise.
> In comparison, the Promise returned by [Promise.all()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) may be more appropriate if the tasks are dependent on each other,

And again on the MDN docs for [Promise.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all#description), it is written:

>  It is typically used when there are multiple related asynchronous tasks that the overall code relies on to work successfully — all of whom we want to fulfill before the code execution continues.

This is causing confusion. Should the Express tutorial use Promise.allSettled() instead of Promise.all() because as per the claims, Promise.allSettled() is the more appropriate method for db queries that do not depend on one another?

### What did you expect to see?

use of `Promise.allSettled()` in place of `Promise.all()` in the Express tutorial if the DB queries are independent of one another. I am just learning web development from MDN docs and tutorials so this is more of a question than a claim.

### Do you have any supporting links, references, or citations?

description of Promise.allSettled on MDN page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled#description

description of Promise.all on MDN page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all#description

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/genre_detail_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Genre_detail_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/genre_detail_page/index.md
* Last commit: https://github.com/mdn/content/commit/0586fbecaf6683f5e793cd9510397b630fb43e61
* Document last modified: 2023-04-14T05:20:55.000Z

</details>

**Comment by hamishwillee** [comment]
As you've probably worked out, the two are very similar. The main difference is that promise.all() will fail as soon as any items fail. There is a comparative description I found here: https://medium.com/geekculture/what-is-the-difference-between-promise-allsettled-and-promise-all-5b9196ef8ea
