### ISSUE TITLE
Broken link under §“Parameters”

### ISSUE THREAD

**Issue by Zearin** [mdn/content#27007]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

Under the description for `options.attributeOldValue`, there is a link with the text “Monitoring attribute values”.  

It is _supposed_ to link to `https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#monitoring_attribute_values`, but there is no anchor on that page, so the reader is directed to the main `MutationObserver` page with no idea of what they were supposed to learn.

### What did you expect to see?

Well, the sentence with the broken link currently reads:

> See [Monitoring attribute values](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#monitoring_attribute_values) for details on watching for attribute changes and value recording.

So, I would expect to click on that link and start reading a section about details on watching for attribute changes and value recording.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mutationobserver/observe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mutationobserver/observe/index.md
* Last commit: https://github.com/mdn/content/commit/ef75c1741b450c2331204be5563ee964ad5f4c48
* Document last modified: 2023-04-07T06:16:45.000Z

</details>

**Comment by postmeback** [comment]
So, removing the anchor will fix the issue, I believe ?

**Comment by Zearin** [comment]
Well, I suppose. 

But does the intended destination for that link exist somewhere? It would be better to link to that instead.

**Comment by postmeback** [comment]
Requesting any of the maintainers to guide on this
