### ISSUE TITLE
CurrentColor can't be transitioned is not mentioned

### ISSUE THREAD

**Issue by skyfighteer** [mdn/content#27014]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

### What specific section or headline is this issue about?

currentColor

### What information was incorrect, unhelpful, or incomplete?

https://jsfiddle.net/bejcugz2/2/

As you can see here, currentColor does not support transition.

### What did you expect to see?

This information to be mentioned.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/color_value`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/color_value/index.md
* Last commit: https://github.com/mdn/content/commit/8daba6d316e3b68f45e09c44da9b6942307ca555
* Document last modified: 2023-05-17T14:51:11.000Z

</details>

**Comment by yarusome** [comment]
Although the [spec](https://drafts.csswg.org/css-color/#interpolation) says that:

> Interpolating to or from `currentcolor` is possible. The numerical value used for this purpose is the used value.

But apparently it's not implemented in all (any?) browsers. I couldn't find relevant test in [WPT](https://wpt.fyi/results/css/css-color), either.

**Comment by skyfighteer** [comment]
Oh, I figured it out. Despite the 'currentColor' is used in with the 'background-color', you have to transition the color, since that's what you are actually changing, regardless that it changes other values. Sorry for wasting your time :)
