### ISSUE TITLE
Vender Typo

### ISSUE THREAD

**Issue by kiskakaska** [mdn/content#27023]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/USBDevice/controlTransferIn

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

Typo of "Vender" instead of "Vendor" 

### What did you expect to see?

Vendor

### Do you have any supporting links, references, or citations?

na

### Do you have anything more you want to share?

thx

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/usbdevice/controltransferin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/USBDevice/controlTransferIn
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/usbdevice/controltransferin/index.md
* Last commit: https://github.com/mdn/content/commit/0c8a320b035cf625c1df67713a94ead2e7f3aec6
* Document last modified: 2023-04-08T06:16:25.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks! Fixed by https://github.com/mdn/content/pull/27024

FYI, pretty easy to do this kind of issue as a PR - means you don't have to explain quite so much because your fix has its own context in the page.
