### ISSUE TITLE
Explanation when "input" event is fired is missleading

### ISSUE THREAD

**Issue by scebotari66** [mdn/content#27044]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

### What specific section or headline is this issue about?

The first paragraph

### What information was incorrect, unhelpful, or incomplete?

I think mentioning that the event fires when `value` is changed is a bit misleading, since if the `value` is changed programmatically the event will not be fired.

### What did you expect to see?

A mention that it is fired when `value` is changed as a result of a user action.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/input_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/input_event/index.md
* Last commit: https://github.com/mdn/content/commit/a3d9f61a8990ba7b53bda9748d1f26a9e9810b18
* Document last modified: 2023-04-07T00:39:15.000Z

</details>

**Comment by postmeback** [comment]
Ok, now I see the point.

I would rather modify the text, for clarity purpose.

**Comment by postmeback** [comment]
PR: https://github.com/mdn/content/pull/27061
