### ISSUE TITLE
STATIC_ROOT = BASE_DIR / 'staticfiles' path won't work in previous versions of Django

### ISSUE THREAD

**Issue by ShubhamOulkar** [mdn/content#27041]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment#example_installing_locallibrary_on_railway

### What information was incorrect, unhelpful, or incomplete?

Your correct approach just crashed my deployment 
here is error msg.
STATIC_ROOT = BASE_DIR / 'staticfiles'
TypeError: unsupported operand type(s) for /: 'str' and 'str'

![image](https://github.com/mdn/content/assets/91728992/9802459d-ab11-415b-a1b5-9635d7a78beb)

After correcting path syntax as STATIC_ROOT = '{BASE_DIR} / staticfiles'.
See file path in static files correctly copied. And web deployed.

![image](https://github.com/mdn/content/assets/91728992/be2bcec2-b9b7-45a1-ba6c-b02e11d85545)

As per Django documentation read static root is a string but string concatenation is not happening because of operand. 
I just used my head to make things work for me. 

![image](https://github.com/mdn/content/assets/91728992/4fca46ff-3222-4a20-9dbf-71e342078f51)

Still I am new to this field, Feel free to guide me if I am doing something wrong. 
They just rejected merge request without giving me some hours. While checking my emails Within 1 hour I got closed. 
By the way is there method to pull requests and writing marge request. 
By the way here is the deploy website https://ebayauction.up.railway.app

### What did you expect to see?

I want know what I am doing wrong ? or What I did as correction in code,  is correct ?

### Do you have any supporting links, references, or citations?

By the way here is the deploy website https://ebayauction.up.railway.app
I have explained above.

### Do you have anything more you want to share?

![image](https://github.com/mdn/content/assets/91728992/9802459d-ab11-415b-a1b5-9635d7a78beb)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/django/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/deployment/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by Josh-Cena** [comment]
Here's how `BASE_DIR` is defined:

https://github.com/mdn/django-locallibrary-tutorial/blob/edd7b4b4370133e62b5be9ef26956a0d80e8a1ce/locallibrary/settings.py#L16

If you try `print(type(Path(__file__).resolve().parent.parent))`, you see that it's an object. Did you change the definition of `BASE_DIR` wrongly?

**Comment by ShubhamOulkar** [comment]
BASE_DIR Path definition in Django 4.2.1 
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

**Comment by Josh-Cena** [comment]
This is not what I see from the Django docs: https://docs.djangoproject.com/en/4.2/howto/overriding-templates/

But anyway, I'll let @hamishwillee confirm this and update the example repo if needed.

**Comment by Josh-Cena** [comment]
So from what I understand, the newest version of Django uses pathlib. In this case no action is required, as new learners would definitely be using the new version. It would be the reader's duty to make sure their code reconciles with what the tutorial expects, by looking at the complete GitHub repo, etc.

**Comment by hamishwillee** [comment]
> So from what I understand, the newest version of Django uses pathlib. In this case no action is required, as new learners would definitely be using the new version. It would be the reader's duty to make sure their code reconciles with what the tutorial expects, by looking at the complete GitHub repo, etc.

Yes.

The main reason though that I would not change this is that Django is opinionated. For me to diverge from the standard Django way of doing things would be confusing to readers who are cross referencing the Django docs and other tutorials. 

Never the less, thank you @ShubhamOulkar and @Josh-Cena for resolving the reasons for this. Would have taken me much longer.
