### ISSUE TITLE
In the model book.js in the Bookschema change the genre field ref from Genre to Genere as in the model genere.js the export is associated as Genere.  if not changed there is an output error for book detail page.

### ISSUE THREAD

**Issue by yogibangalore** [mdn/content#27047]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Author_list_page

### What specific section or headline is this issue about?

the book details page will err out if the Bookschema in the model book.js is not ref to Genere as the book.js model has export set to Genere 

### What information was incorrect, unhelpful, or incomplete?

In the model book.js in the Bookschema change the genre field ref from Genre to Genere as in the model genere.js the export is associated as Genere.  if not changed there is an output error for book detail page.
![Untitled](https://github.com/mdn/content/assets/22776004/de227125-50b5-4a82-bfed-01efb3671176)
![Untitled2](https://github.com/mdn/content/assets/22776004/c5166fac-90cf-4096-853a-de1f8be57110)
![Untitled3](https://github.com/mdn/content/assets/22776004/9d1eede1-9df9-421f-9242-e75703dee8ff)

### What did you expect to see?

In the model book.js in the Bookschema change the genre field ref from Genre to Genere as in the model genere.js the export is associated as Genere.  if not changed there is an output error for book detail page.
![Untitled](https://github.com/mdn/content/assets/22776004/de227125-50b5-4a82-bfed-01efb3671176)
![Untitled2](https://github.com/mdn/content/assets/22776004/c5166fac-90cf-4096-853a-de1f8be57110)
![Untitled3](https://github.com/mdn/content/assets/22776004/9d1eede1-9df9-421f-9242-e75703dee8ff)

### Do you have any supporting links, references, or citations?

In the model book.js in the Bookschema change the genre field ref from Genre to Genere as in the model genere.js the export is associated as Genere.  if not changed there is an output error for book detail page.
![Untitled](https://github.com/mdn/content/assets/22776004/de227125-50b5-4a82-bfed-01efb3671176)
![Untitled2](https://github.com/mdn/content/assets/22776004/c5166fac-90cf-4096-853a-de1f8be57110)
![Untitled3](https://github.com/mdn/content/assets/22776004/9d1eede1-9df9-421f-9242-e75703dee8ff)

### Do you have anything more you want to share?

In the model book.js in the Bookschema change the genre field ref from Genre to Genere as in the model genere.js the export is associated as Genere.  if not changed there is an output error for book detail page.
![Untitled](https://github.com/mdn/content/assets/22776004/de227125-50b5-4a82-bfed-01efb3671176)
![Untitled2](https://github.com/mdn/content/assets/22776004/c5166fac-90cf-4096-853a-de1f8be57110)
![Untitled3](https://github.com/mdn/content/assets/22776004/9d1eede1-9df9-421f-9242-e75703dee8ff)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/author_list_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Author_list_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/author_list_page/index.md
* Last commit: https://github.com/mdn/content/commit/bb6092c4230b69c2eceae6910af68c73955cae1c
* Document last modified: 2023-05-10T14:53:07.000Z

</details>

**Comment by hamishwillee** [comment]
This is incorrect. You may well have miss-spelled genre in your example genre implementation/export, but the tutorial itself is consistent and works.

You can see this in the worked (and working) example: https://github.com/mdn/express-locallibrary-tutorial
