### ISSUE TITLE
Not Able to Open Drop-down List with a Keyboard

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#27052]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls

### What specific section or headline is this issue about?

The aria-selected attribute

### What information was incorrect, unhelpful, or incomplete?

A person is not able to open a drop-down list with a keyboard. I can only open the list of items with a mouse.

The fancy drop-down list should open with either the Enter or Space bar keys.

Not able to use a keyboard to see the list of items in the drop-down list.

The example is right above the "An alternative approach: Using radio buttons" heading.

**NOTE** - When you use the arrow keys, it moves the item and the screen too.

Please see the attached screenshot of what I'm talking about.

<img width="960" alt="mdn - how to build custom form controls page - not able to open drop-down with keyboard" src="https://github.com/mdn/content/assets/10423487/c96c3f80-abea-4e49-8655-c2de0c6fa734">

### What did you expect to see?

To be able to open the drop-down list with a keyboard.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/how_to_build_custom_form_controls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_build_custom_form_controls/index.md
* Last commit: https://github.com/mdn/content/commit/bb6092c4230b69c2eceae6910af68c73955cae1c
* Document last modified: 2023-05-10T14:53:07.000Z

</details>

**Comment by postmeback** [comment]
Is it supposed to do so ?

**Comment by jfc3-dol** [comment]
@postmeback 

Yes, a typical drop-down list created with SELECT code should open with the Enter key or space bar when a user tabs to it.

Please see the example here - [Gotta Eat Here](http://gottaeathere.com/).

**Comment by Josh-Cena** [comment]
Sorry, not an expert with forms or web APIs in general. I'd say definitely get rid of deprecated APIs while you're at it and improve the rest with your discretion.

**Comment by minimalsm** [comment]
Will do :) Please assign me and I'll start work this weekend @Josh-Cena
