### ISSUE TITLE
Issue with "Guide to streaming audio and video"

### ISSUE THREAD

**Issue by alvinhui** [mdn/content#2707]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Streaming

#### What information was incorrect, unhelpful, or incomplete?

This page is not complete? If so, Please add **Draft** mode.

#### Specific section or headline?

none.

#### What did you expect to see?

Some content like https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Live_streaming_web_audio_and_video

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/media/streaming`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Streaming
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/media/streaming/index.html
* Last commit: https://github.com/mdn/content/commit/c2db00491ea7469eb08fd389c3d0f6d79dc6e9ff
* Document last modified: 2020-10-28T01:07:25.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve opened https://github.com/mdn/content/pull/2733 with a change that adds a prominent *”Draft: This is not complete“* notice to the top of the article.
