### ISSUE TITLE
Link to the \xAB notation

### ISSUE THREAD

**Issue by krave1986** [mdn/content#27091]
Hi, I am reading the code referenced below.
There is such a `\x13` notation in a string.
Do we have docs explain this notation on MDN?
I searched but with no luck.

https://github.com/mdn/content/blob/3e2369d97e2d6fbfe33a3c496a8edd90e0b539e2/files/en-us/web/api/urlsearchparams/index.md?plain=1#L133

**Comment by postmeback** [comment]
Hi @krave1986 ,

can you put the web url of the page ?

**Comment by Josh-Cena** [comment]
Yes, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#hexadecimal_escape_sequences

**Comment by krave1986** [comment]
Hi @postmeback ,
This is the url of the page I referenced:
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

**Comment by Josh-Cena** [comment]
@krave1986 Both of the outputs represent the same string value: a character U+0017. What format to use is an implementation detail of the devtools.
