### ISSUE TITLE
No difference between mouse and keyboard focus methods

### ISSUE THREAD

**Issue by Jan-Timon** [mdn/content#27093]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#basic_example

### What information was incorrect, unhelpful, or incomplete?

There is supposed to be a difference when putting focus on an element through the keyboard versus the mouse focus method. This difference is not visible in current browsers. Tested in Chrome and Firefox.

### What did you expect to see?

I expected to see a difference, because this was indicated in the text.

### Do you have anything more you want to share?

"Compare what happens when you click on the different controls with a mouse, versus when you tab through them using a keyboard. "

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_focus-visible`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_focus-visible/index.md
* Last commit: https://github.com/mdn/content/commit/5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e
* Document last modified: 2023-02-21T06:49:52.000Z

</details>

**Comment by postmeback** [comment]
This `SO` answer is very insightful. https://stackoverflow.com/a/5654509

**Comment by Josh-Cena** [comment]
@postmeback That post is from 2011, before any sane web feature existed. `:focus-visible` exists exactly to solve problems like this. 

@Jan-Timon `<input>`s are visibly focused by a click as well. The `<button>` directly below shows the difference, where clicking does not produce the focus ring. We probably want to mention that different elements have different visible focus conditions.
