### ISSUE TITLE
Issue with "Global attributes": (`translate` experimental status)

### ISSUE THREAD

**Issue by shaunbruno** [mdn/content#2710]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

#### What information was incorrect, unhelpful, or incomplete?
Term `translate` was marked as experimental (flask) on the index page, but clicking into the `translate` page makes no mention of it being an experimental attribute. Also, the topic page mentions production systems such as Google Translate currently use it - so, is it really experimental? 

#### Specific section or headline?
Section `List of global attributes`

#### What did you expect to see?
Either (1) an experimental designation on the topic page, with a corresponding explanation or (2) removal of the experimental icon from the index page.

#### Did you test this? If so, how?
No, but it sounds like Google Translate does :)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/global_attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/index.html
* Last commit: https://github.com/mdn/content/commit/74a4a9283e1aa5c7f23e31c142010f7e539f736f
* Document last modified: 2021-02-10T17:57:43.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/2722 with a fix that drops the "experimental" flag from the index page.
