### ISSUE TITLE
Assertion based on specific Platform/Compiler

### ISSUE THREAD

**Issue by Calvin-Ruiz** [mdn/content#27111]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/DataView/getUint32

### What specific section or headline is this issue about?

Head description

### What information was incorrect, unhelpful, or incomplete?

Assertion that long is 32-bit, which is not always true (64-bit under Linux, same with Windows using clang).

### What did you expect to see?

Assertion that int is 32-bit, which is true for most 32-bit and 64-bit systems.
OR avoid comparing to C type

### Do you have any supporting links, references, or citations?

https://www.ccoderun.ca/programming/2017-03-10_sizeof/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/javascript/reference/global_objects/dataview/getuint32`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/DataView/getUint32
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/dataview/getuint32/index.md
* Last commit: https://github.com/mdn/translated-content/commit/b56cdbdabebd131cde90fdc598b19a2ba289424b
* Document last modified: 2022-10-07T16:14:13.000Z

</details>

**Comment by Josh-Cena** [comment]
Yes, we should work to remove all platform-specific type references. You can see how https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#typedarray_objects does it.
