### ISSUE TITLE
MathML Core seems to have renamed columnspan to colspan in MathML mtd-element

### ISSUE THREAD

**Issue by LiraOnGithub** [mdn/content#27116]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtd

### What specific section or headline is this issue about?

Attributes

### What information was incorrect, unhelpful, or incomplete?

According to https://w3c.github.io/mathml-core/#mtd-attributes `columnspan` is now called `colspan` in MathML Core.
In the documentation of MDN only `columnspan` is mentioned.

### What did you expect to see?

I am not sure. Should both attributes be mentioned?

### Do you have any supporting links, references, or citations?

https://w3c.github.io/mathml-core/#mtd-attributes
> The name of the column spanning attribute in [[MathML3]] and earlier versions was columnspan. For consistency with [[HTML]], this specification uses colspan instead. 

### Do you have anything more you want to share?

No browser seems to support `colspan` on `mtd` from my quick testing

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/mathml/element/mtd`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mtd
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/mathml/element/mtd/index.md
* Last commit: https://github.com/mdn/content/commit/8eece0b998c23e8ea35f936d7371a169974130f5
* Document last modified: 2023-04-10T07:52:18.000Z

</details>

**Comment by bsmth** [comment]
Pinging @fred-wang for some info on this one, do you mind having a look :)

**Comment by fred-wang** [comment]
Yes, MathML WG decided that but we got pushback for some browser vendors, so we might eventually not do the renaming at the end. This is https://github.com/w3c/mathml-core/issues/180#issuecomment-1484532747 ; in chromium we are pending on the decision before shipping that feature.

cc @bkardell

**Comment by bsmth** [comment]
Thank you for the clarification 👍🏻 We can leave the issue open for the moment until there's a decision on the outcome.

**Comment by fred-wang** [comment]
Closing as the WG decided to keep the original name.

**Comment by bsmth** [comment]
Thanks for coming back and verifying 👍🏻
