### ISSUE TITLE
Node.js Native Messaging host exits

### ISSUE THREAD

**Issue by guest271314** [mdn/content#27129]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging

### What specific section or headline is this issue about?

Node.js host example here https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging#app_side.

### What information was incorrect, unhelpful, or incomplete?

Node.js host example.

### What did you expect to see?

Working example. 

The current example is incomplete.

### Do you have any supporting links, references, or citations?

Using `process.stdin.on('readable', () => {})` with `process.stdin.read()` is not ideal. Testing this code which uses a similar pattern once `new Array(13107)` (`JSON.stringify(new Array(13107)).length // 65536`) is attempted to be sent from client to host the code will break, the host won't echo the message back, see https://github.com/simov/native-messaging/issues/10. We don't get that far with the code in the documentation because the example is incomplete.

### Do you have anything more you want to share?

This https://github.com/guest271314/native-messaging-nodejs/ is a working example of a Node.js host which sends back 1 MB of data (per protocol).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/native_messaging`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/native_messaging/index.md
* Last commit: https://github.com/mdn/content/commit/d86e14de2e66319fc0a0ec0539a05400dea5a453
* Document last modified: 2023-03-07T05:20:12.000Z

</details>

**Comment by rebloor** [comment]
@guest271314 there is no timeframe

**Comment by guest271314** [comment]
Right. I can file a PR to fix this.
