### ISSUE TITLE
Interactive editor doesn't respond as expected with inheritance

### ISSUE THREAD

**Issue by Rolocar** [mdn/content#27121]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#resetting_all_property_values

### What information was incorrect, unhelpful, or incomplete?

In the interactive editor, when changing the property `all` from `unset` to `inherit`, a border is displayed in the element.

### What did you expect to see?

I expected the element to have no borders because it should inherit the properties of the body. I checked with Chrome and Firefox and worked fine, but I take me some time thinking about what the problem was.

### Do you have any supporting links, references, or citations?

No

### Do you have anything more you want to share?

![image](https://github.com/mdn/content/assets/19876722/9bf5ca6b-cb29-4c19-a2a8-24d3d2bd8a77)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
* Last commit: https://github.com/mdn/content/commit/24069b528a87249b188d6147d84f97ca1ede6dd0
* Document last modified: 2023-04-14T13:02:39.000Z

</details>

**Comment by Josh-Cena** [comment]
I agree this is somehow confusing, but it's working as intended and I don't think we have an appropriate way to fix this.
