### ISSUE TITLE
The "start" parameter of Array.prototype.copyWithin() is not optional

### ISSUE THREAD

**Issue by unadlib** [mdn/content#27127]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/copyWithin

### What specific section or headline is this issue about?

TypedArray.prototype.copyWithin()

### What information was incorrect, unhelpful, or incomplete?

https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/typedarray/copywithin/index.md

https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.copywithin

### What did you expect to see?

The "start" parameter of `TypedArray.prototype.copyWithin()`  is required.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/typedarray/copywithin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/copyWithin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/typedarray/copywithin/index.md
* Last commit: https://github.com/mdn/content/commit/194d3e00cb93a6e5ea44812548f4131cb17f0381
* Document last modified: 2023-02-21T00:33:25.000Z

</details>

**Comment by yarusome** [comment]
Did you mean to say that the `start` parameter of `Array.prototype.copyWithin()` is not optional instead?

**Comment by unadlib** [comment]
hi @yarusome, yes, this is the case according to the specification description.

**Comment by Josh-Cena** [comment]
Sure, let's make it required.

**Comment by postmeback** [comment]
Will modifying the text, resolve the purpose ?

**Comment by Phil-G-94** [comment]
Hi @Josh-Cena et al. 

Has this been resolved? Any further work that needs to be carried out?

**Comment by Josh-Cena** [comment]
@Phil-G-94 No it's not resolved. To fix this, you would need to undo https://github.com/mdn/content/pull/27141, and remove `{{optional_inline}}` from the `start` parameter of `Array.prototype.copyWithin`.

**Comment by Phil-G-94** [comment]
Hi @Josh-Cena, thank you for letting me know. Please see pull request for the fix [here](https://github.com/mdn/content/pull/27296). Apologies in advance, I think I messed up the trailing space but other than that fixed as instructed. 

Please let me know if it needs to be redone and I can get on it. 

All the best
