### ISSUE TITLE
Proxy doesn't trap "apply" for objects.

### ISSUE THREAD

**Issue by klaussguimaraes** [mdn/content#27156]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/apply

### What information was incorrect, unhelpful, or incomplete?

The handler.apply() method is a trap for the [[Call]] [object internal method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#object_internal_methods), which is used by operations such as function calls.

### What did you expect to see?

I expect `apply` to work also on objects, like applying a function to an object.

Example:
```
const Object = {Native: true};
const Handler =
{
   apply ( Target, Context, Arguments ) // Should be bound to `MyProxy` when instantiating the Proxy object.
   {
      this; // Should refer to `MyProxy` when instantiating the Proxy object, not `Handler`.
      
      Context; // Should refer to `Object` because it's what was passed through that argument.
      
      this['FirstProperty'] = 'First'; // Should call the interception function trap `set` on `MyProxy`.
      
      Context['SecondProperty'] = 'Second'; // Should set a property directly on `Object` without being trapped by the proxy.
      
      // Finally, apply the `Target` directly to the `Context` through reflection.
      return Reflect.apply(Target, Context, Arguments);
      
      // The lines below should produce maximum stack call error.
      return Reflect.apply(Target, this, Arguments);
      return Reflect.apply(Target, MyProxy, Arguments);
   }
};

const MyProxy = new Proxy(Object, Handler);

const Result = Reflect.apply(function () { this.Value = true; }, MyProxy, []);
// Should return {Native: true, FirstProperty: 'First', SecondProperty: 'Second', Value: true}
// and `Object` will be exactly like this because `set` was not defined in the handler.

// But Handler.apply is never executed. It will only work if `typeof Object` is `function`.
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/proxy/proxy/apply`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/apply
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/proxy/proxy/apply/index.md
* Last commit: https://github.com/mdn/content/commit/fcd80ee4c8477b6f73553bfada841781cf74cf46
* Document last modified: 2023-02-21T01:57:14.000Z

</details>

**Comment by Josh-Cena** [comment]
Objects don't have the [[Call]] internal method, so you can't even trap their `apply`. A proxified non-function is still a non-function. This is mentioned in both https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/apply:

> The target must be a callable itself. That is, it must be a function object.

And https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#object_internal_methods:

> Function objects also have the following internal methods:

The way you try to invoke the [[Call]] internal method is wrong. `Reflect.apply` invokes the [[Call]] method of the first argument (the function), passing the second argument as the `this` value.
