### ISSUE TITLE
"Adapting to the new multi-keyword syntax of display" has incorrect Safari support info

### ISSUE THREAD

**Issue by nt1m** [mdn/content#27162]
https://developer.mozilla.org/en-US/docs/Web/CSS/display/multi-keyword_syntax_of_display#can_i_start_to_use_the_multi-keyword_syntax

> As demonstrated above, there is not a lot of advantage in using the multi-keyword version right now; if you did, your page would only work in Firefox! Other browsers do not yet implement the multi-keyword versions. 

This is incorrect info, Safari supports the syntax since version 15. BCD & Can I Use both have the correct data.

**Comment by bsmth** [comment]
Thanks for raising @nt1m do you want to have a shot at fixing that section? There's a key for multi-keyword values already that shows support, see [the display page](https://developer.mozilla.org/en-US/docs/Web/CSS/display#browser_compatibility) and [the BCD key](https://github.com/mdn/browser-compat-data/blob/b913758d5923b1634f1ea2bae483811eafdbe095/css/properties/display.json#L625-L657).

If you wanted to embed this in the page, you can add the key to the front matter:

```md
---
title: "..."
browser-compat: css.properties.display.multi-keyword_values
---
```

and then add the section for compatibility:

```md
## Browser compatibility

{{Compat}}

```

BCD can be updated and kept in sync better than the prose. What do you think?
