### ISSUE TITLE
Issue with "Object.is()": Wrong correlation between sections

### ISSUE THREAD

**Issue by ozanmuyes** [mdn/content#2716]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is

#### What information was incorrect, unhelpful, or incomplete?
On the [Polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#polyfill) section mentioned steps doesn't correspond the "steps" on the previous ([`Using Object.is`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#using_object.is)) section.

#### Specific section or headline?
"`Using Object.is`" and "Polyfill" sections.

#### What did you expect to see?
The steps in the latter section to correspond former one.

#### Did you test this? If so, how?
Since this is more of a semantic issue there is nothing to test code-wise.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/is`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/is/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by ozanmuyes** [comment]
Also it's not clear to see which steps in question at a first glance, it would be good to have mentioned steps in the former section (i.e. what is `// Step 6.a: NaN == NaN`). Thanks in advance.

**Comment by chengjieyun59** [comment]
I can take this 👍 I'll submit a PR in a few days.

**Comment by chrisdavidmills** [comment]
@chengjieyun59 that's great, thank you for your offer of help! Don't hesitate to shout if you have any questions.

**Comment by chengjieyun59** [comment]
@ozanmuyes Submitted a fix #2793. Let me know if you have any questions, or would like me to clarify any concepts further.

**Comment by ozanmuyes** [comment]
@chengjieyun59 Thank you!
