### ISSUE TITLE
[HTTP] Replace X-Moz: Prefetch with Sec-Purpose: Prefetch

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#27171]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1836328

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
This is part of a bigger job described in #23553 around harmonizing prefetch behaviour. The status is WIP while I work out what can be done now.

Useful resources/related issues
- https://github.com/whatwg/html/pull/8111
- #23553
- https://bugzilla.mozilla.org/show_bug.cgi?id=1788167#c0


Status: 
- [ ] BCD
- [ ] Docs
  - [ ] [HTTP/Link_prefetching_FAQ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ) - very old and FF-centric. Probably delete, but perhaps data mine some of the concepts to put in new prefetch doc.
  - [ ] [Glossary: Prefetch](https://developer.mozilla.org/en-US/docs/Glossary/Prefetch) - out of date and Moz-centric. Update to reflect how browsers are supposed to work with some info on old behaviour.
  - [ ] `Sec-Purpose: Prefetch` new document
  - [ ] `Purpose` and `X-Moz: Prefect` "legacy" docs.
  - [ ] ?
- [ ] Release note
- [ ] dev-doc-complete
