### ISSUE TITLE
[CSS] Update offset-position syntax

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#27174]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- NA - Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- NA - Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1559232

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by dipikabh** [comment]
Moving this issue from Fx115 project to Fx116 projects. 
As per my tests, the expected behavior was visible only in Nightly and 115 beta (now 116 beta), but not in the now 115 stable version. As also confirmed by the engineer, this feature will be implemented in Fx116.

**Comment by dipikabh** [comment]
Task list for updating `offset-position` and related docs:

- [ ] Content update: https://github.com/mdn/content/pull/27726
- [x] Add keyword to `mdn/data`: https://github.com/mdn/data/pull/673
- [x] Add to experimental release notes:
    - https://github.com/mdn/content/pull/27730
    - https://github.com/mdn/content/pull/28036
- [x] BCD: https://github.com/mdn/browser-compat-data/pull/20250
