### ISSUE TITLE
Incorrect code snippet results for capturing group lookahead/lookbehind explanation

### ISSUE THREAD

**Issue by MrRedacted** [mdn/content#27187]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Capturing_group

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Capturing_group#description

### What information was incorrect, unhelpful, or incomplete?

The code snippet that is provided for the paragraph explaining the use of capturing groups in lookahead and lookbehind assertions ("Capturing groups can be used in lookahead and lookbehind assertions...") shows incorrect result arrays for each example execution:

`/c(?=(ab))/.exec("cab"); // ['', 'ab']`
`/(?<=(a)(b))c/.exec("abc"); // ['', 'a', 'b']`
`/(?<=([ab])+)c/.exec("abc"); // ['', 'a']; because "a" is seen by the lookbehind after the lookbehind has seen "b"`

### What did you expect to see?

The result arrays for each execution should show as follows, due to the 'c' character being a valid match for each regular expression:

`/c(?=(ab))/.exec("cab"); // ['c', 'ab']`
`/(?<=(a)(b))c/.exec("abc"); // ['c', 'a', 'b']`
`/(?<=([ab])+)c/.exec("abc"); // ['c', 'a']; because "a" is seen by the lookbehind after the lookbehind has seen "b"`

### Do you have any supporting links, references, or citations?

The following MDN documentation:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Lookahead_assertion
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Lookbehind_assertion

### Do you have anything more you want to share?

I would be happy to edit the page as needed if the issue is valid and the suggested changes are sufficient.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/regular_expressions/capturing_group`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Capturing_group
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/regular_expressions/capturing_group/index.md
* Last commit: https://github.com/mdn/content/commit/55215aa7eca819ce095866021125e3d3e4380ae8
* Document last modified: 2023-05-22T17:28:33.000Z

</details>

**Comment by Josh-Cena** [comment]
Good catch. PRs welcome
