### ISSUE TITLE
[CSS] Ship CSS nesting

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#27180]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1835066

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by Rumyra** [comment]
@dletorey FYI this _should_ be shipping in 117 (which is coming very soon) so do the MDN pages, but hold off on release notes as it might just be a 117 _not_ experimental 👍

**Comment by dletorey** [comment]
Excellent eyes all over this

**Comment by Rumyra** [comment]
Confirmed - editing this issue for 117 instead of 115

See https://bugzilla.mozilla.org/show_bug.cgi?id=1840818 - both bugs will need dev-doc-complete - but do the bcd & rel notes for 117 release rather than experimental :)

**Comment by dletorey** [comment]
A number of pages have been created:
- /en-US/docs/Web/CSS/CSS_nesting
- /en-US/docs/Web/CSS/Nesting_selector
- /en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting
- /en-US/docs/Web/CSS/CSS_nesting/Nesting_and_specificity
- /en-US/docs/Web/CSS/CSS_nesting/Nesting_at-rules

Added to the release notes for Firefox 117:
- /en-US/docs/Mozilla/Firefox/Releases/117

Updated the `CSSRef.ejs` page in Yari to show the new pages in **Guides**

## Associated Pull Requests

- [Content PR](https://github.com/mdn/content/pull/28473)
- [Browser Compat Data PR](https://github.com/mdn/browser-compat-data/pull/20523)
- [Yari PR](https://github.com/mdn/yari/pull/9469)

**Comment by estelle** [comment]
Suggested additions

- [ ] - on https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors, add add `&` to "related concepts" and the module to "see also"
- [ ] Add module to https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_cascade "see also"
- [ ] Add. nesting to https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance. I think near "The negation ... " paragraph
- [ ] Add & to the combinators: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Combinators
- [ ] Add a "chapter" on nesting in that series (if it makes sense.)
- [ ] Add nesting to https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity
- [ ] Add a sentence to https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule regarding nesting at rules (and link to the guide)
- [ ] Include cascade layer order when layers are nested to https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers#overview_of_nested_cascade_layers
- [ ] Add nesting to the see also on all of these pages?

**Comment by Rumyra** [comment]
Closing this as the work for release is done - we can review other sections as neccessary
