### ISSUE TITLE
Issue with "ScrollToOptions.behavior": Description of `auto` value is wrong, lacking historical `instant` value

### ISSUE THREAD

**Issue by n0099** [mdn/content#2719]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ScrollToOptions/behavior

#### What information was incorrect, unhelpful, or incomplete?
The `behavior: 'auto'` will not always do an instant scroll that jumps to the element as described in the doc.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/ScrollToOptions/behavior#value

#### What did you expect to see?
> auto (default): The scrolling happens with the same value of style [scroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior), which is set or inherited on the scrolling element.

#### Did you test this? If so, how?
https://github.com/Norserium/react-indiana-drag-scroll/issues/53#issuecomment-786750940

> I've tested on chrome and firefox with this change, it's still doesn't work, in fact determining `behavior: 'auto'` doesn't cancel the effect of `scroll-behavior: smooth`, and it's an expected behavior standardized by CSSOM.
> 
> [CSSOM draft](https://drafts.csswg.org/cssom-view/#scrolling) says:
> > If the user agent honors the scroll-behavior property and one of the following are true:
> > behavior is "auto" and element is not null and its computed value of the scroll-behavior property is smooth
> > behavior is smooth
> > ...then perform a smooth scroll of box to position. Otherwise, perform an instant scroll of box to position.
> 
> It's also been mentioned in [stackoverflow](https://stackoverflow.com/questions/60795723/how-to-override-the-css-scroll-behavior-with-scrollto-in-javascript) and [webkit developers](https://bugs.webkit.org/show_bug.cgi?id=188043)
> 
> But the [MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/ScrollToOptions/behavior) doesn't mention this, it just says: `auto: The scrolling happens in a single jump.`, it's only correct when there's no `scroll-behavior: smooth` style applied on the scrolling elements. In wild, I've seen some websites use `body { scroll-behavior: smooth; }` to make all scrolling executed by js is smooth.
> 
> According to the previous stackoverflow answer, the only available workaround for compatible elements with `scroll-behavior: smooth` style is adding `scroll-behavior: auto !important;` after https://github.com/Norserium/react-indiana-drag-scroll/blob/329221fc52a79b0af7dc9f3b6fb088535a206879/src/style.css#L3
> 
> So I think there's a lack of 'instant' value of ScrollToOptions in CSSOM to allow using js to perform instant scroll without touching style temporarily.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/scrolltooptions/behavior`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ScrollToOptions/behavior
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/scrolltooptions/behavior/index.html
* Last commit: https://github.com/mdn/content/commit/11a98a59fca5f2e448d9e4b70e3c8a538c47b201
* Document last modified: 2021-02-19T19:45:18.000Z

</details>

**Comment by n0099** [comment]
I've [noticed](https://github.com/Norserium/react-indiana-drag-scroll/issues/53#issuecomment-786780193) there's also an undocumented `instant` value available in firefox and chrome ([demo](https://jsfiddle.net/fr7m40kw/)), it will always jumpy scroll to element no matter how the `scroll-behavior` style is set.

In [this email list](https://lists.w3.org/Archives/Public/www-style/2013Mar/0315.html), it's seems firefox implmented `instant` value before chrome.
> So Gecko internally has:
> 
> enum ScrollMode { INSTANT, SMOOTH, NORMAL };
> 
> INSTANT is what scrollTo and scrollBy do. NORMAL is done as one scroll,
> but possibly async. SMOOTH will do smooth scrolling if the user has
> that enabled, and behave like NORMAL otherwise.

**Comment by myakura** [comment]
the value `instant` was the former name of `auto`.
https://github.com/w3c/csswg-drafts/commit/21b1748b746bc7aa5eb1b00fd7c1a53c2235efcb

**Comment by n0099** [comment]
> the value `instant` was the former name of `auto`.
> [w3c/csswg-drafts@21b1748](https://github.com/w3c/csswg-drafts/commit/21b1748b746bc7aa5eb1b00fd7c1a53c2235efcb)

but browsers treat them as different behavior.

**Comment by cmawhorter** [comment]
mdn now reflects "instant" as an allowed option but i'm seeing no mention of it in the [the spec](https://w3c.github.io/csswg-drafts/cssom-view/#concept-instant-scroll) linked there apart from being the previous name for auto.  should it be on mdn as gospel?

i _want_ to have an instant option, but it seems premature to have it on that page unless i'm not looking at the right spec doc.

**Comment by n0099** [comment]
These spec won't address behaviors on historical or living browsers that might not match with its expecting standard, that's why the mdn should hint this point.
