### ISSUE TITLE
Different info about DOMContentLoaded event on Window and Document object

### ISSUE THREAD

**Issue by just-boris** [mdn/content#27197]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event

### What specific section or headline is this issue about?

Document: DOMContentLoaded event

### What information was incorrect, unhelpful, or incomplete?

The [document's version of this event description](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event) says this

> The DOMContentLoaded event fires when the initial HTML document has been completely loaded and parsed, without waiting for stylesheets, images, and subframes to finish loading.
 
The [window version](https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event) has an extra line about deferred scripts

> The DOMContentLoaded event fires when the HTML document has been completely parsed, and all deferred scripts (<script defer src="…"> and <script type="module">) have downloaded and executed. It doesn't wait for other things like images, subframes, and async scripts to finish loading.

This is confusing, because in fact it is the same event bubbling up and therefore has the same semantics on both

### What did you expect to see?

Ideally, this should be a single article. The event is being dispatched on the document. Window receives it as a part of the bubbling process, nothing custom there

### Do you have any supporting links, references, or citations?

Spec sources

* [DOMContentLoaded is described here, with document as a target](https://html.spec.whatwg.org/multipage/indices.html#events-2)
* [All events bubble up from document to window](https://dom.spec.whatwg.org/#:~:text=the%20document%E2%80%99s%20relevant%20global%20object)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document/domcontentloaded_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/domcontentloaded_event/index.md
* Last commit: https://github.com/mdn/content/commit/41a8b9c9832359d445d136b6d7a8a28737badc6b
* Document last modified: 2023-04-07T05:52:28.000Z

</details>

**Comment by wbamberg** [comment]
@Elchi3 what is the policy for events that bubble? It seems to make sense only to document them on the `Document`.

FWIW the extra detail added to `Window`'s version comes from https://github.com/mdn/content/pull/19924.

**Comment by Elchi3** [comment]
> @Elchi3 what is the policy for events that bubble? It seems to make sense only to document them on the `Document`.

Yes, see https://developer.mozilla.org/en-US/docs/Web/API/Serial#events where we mention the events but the docs are under `SerialPort`. I guess `Window` could do the same by pointing to the events under `Document`. Does that make sense?

**Comment by wbamberg** [comment]
> Does that make sense?

I'm not sure about this. It would mean adding a lot of duplicate items to the pages - for example, all the `Element` events that bubble would have to be listed both in `Document` and in `Window`, AFAIK. Would be really hard to maintain. I think it's better just to expect people understand bubbling and document them on the original interface. Or perhaps I just don't understand events.

**Comment by Elchi3** [comment]
Yeah, on such large interfaces it probably doesn't make sense to list all the events that bubble. Probably it is enough to say that there is bubbling going on and from which interfaces it occurs so readers can get a list from there.

**Comment by Josh-Cena** [comment]
So what's the plan here—to merge the `Window` page into the `Document` page because they are the same event? And maybe reapply #19924 to the `Document` version?

**Comment by wbamberg** [comment]
> So what's the plan here—to merge the `Window` page into the `Document` page because they are the same event? And maybe reapply #19924 to the `Document` version?

Yes, I think that would be for the best.
