### ISSUE TITLE
Global functions missing from the "Web API" page

### ISSUE THREAD

**Issue by yarusome** [mdn/content#27212]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API

### What information was incorrect, unhelpful, or incomplete?

Global functions such as [`setTimeout()`](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout) and [`structuredClone()`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) are missing from this reference page.

Side note: the [section heading](https://developer.mozilla.org/en-US/docs/Web/API#specifications) "Specifications" is definitely incorrect here.

### What did you expect to see?

Global functions be listed there.

**Comment by postmeback** [comment]
I can add the missing Global functions on this page. Will that be sufficient ?

**Comment by wbamberg** [comment]
Yes, we should have a way to do this. But also I think the way we represent globals is not ideal. See https://github.com/orgs/mdn/discussions/360. I mean, there isn't really a single collection of "globals" - there are different scopes, which have different but overlapping sets of globals.

**Comment by postmeback** [comment]
I went through the discussion. What i would suggest is to mention that "**Global is context / scope specific**" and "**certain properties may overlap**" in the description / ideal place.

**Comment by Josh-Cena** [comment]
See also: https://github.com/mdn/content/issues/22441

**Comment by skyclouds2001** [comment]
The global properties and global functions are in fact those properties or functions that exposed via `WindowOrWorkerGlobalScope`, which is mixed with `Window` and `WorkerGlobalScope`

So personal opinion, I'm not quite agree that we should mention interfaces' members
