### ISSUE TITLE
Inconsistent Values definition

### ISSUE THREAD

**Issue by hjp** [mdn/content#27217]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side

### What specific section or headline is this issue about?

Syntax/Values and Formal Syntax

### What information was incorrect, unhelpful, or incomplete?

The section Values lists 6 possible values (top, bottom, block-start, block-end, inline-start, inline-end), but the section Formal syntax lists only 2 (top, bottom).

### What did you expect to see?

The information in both sections should be consistent.

### Do you have anything more you want to share?

Limited testing indicates that both Firefox (114) and Chromium (113) support only `top`  and `bottom` but not the other 4.
If those 4 values are retained the compatibility chart should also be amended to show which browser supports which values.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/caption-side`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/caption-side/index.md
* Last commit: https://github.com/mdn/content/commit/42c1bb8c259f3f57de9f38600776cf273e3addda
* Document last modified: 2023-02-21T06:27:49.000Z

</details>

**Comment by yarusome** [comment]
The reason for the "Values" and "Formal syntax" section is probably that [mdn/yari](https://github.com/mdn/yari/pull/8986) hasn't updated the webref/css dependency for a long time, which is blocked by the pending refactoring of the `{{CSSSyntax}}` [macro](https://github.com/mdn/yari/blob/main/kumascript/src/lib/css-syntax.ts) used in the "Formal syntax" section.

As for the discrepancy between the "Formal syntax" section and the support statuses of browsers: "Formal syntax" builds on webref/css, which simply crawls specs without checking for support statuses.

**Comment by Josh-Cena** [comment]
We will track this in https://github.com/mdn/content/issues/22271
