### ISSUE TITLE
Document missing components' bahavior for CSS color functions?

### ISSUE THREAD

**Issue by yarusome** [mdn/content#27218]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

### What information was incorrect, unhelpful, or incomplete?

CSS Color 4 introduced the [concept](https://drafts.csswg.org/css-color-4/#missing) of missing color components, and all modern color [syntaxes](https://drafts.csswg.org/css-color-4/#color-syntax-modern) accept `none` as a result. This feature is quite useful for [interpolation](https://drafts.csswg.org/css-color-4/#interpolation-missing), however:

  - There's no BCD for this feature yet;
  - I couldn't find relevant test in [WPT](https://wpt.fyi/results/css/css-color/animation/color-interpolation.html?label=master&label=experimental&aligned).

This implies a widespread addition to color-related MDN pages, but it seems to need less effort than `<hue>`.

cc @bsmth

### What did you expect to see?

Info on missing color components on MDN, or leave it as it is now.

### Do you have any supporting links, references, or citations?

See links above in the text.

**Comment by bsmth** [comment]
Thanks a lot for raising it. That's a good point and we don't go into detail about it. Support seems to be fine in Fx: https://codepen.io/bsmth/pen/xxQZvrB

I think we should check support and mention it in the docs. And this is also a good hint from the spec:

>Explicitly specifying missing components can be useful to achieve an effect where you only want to interpolate certain components of a color.

**Comment by yarusome** [comment]
Since any color component can be missing, a careful way of documentation is needed here to avoid massive duplicate info on every color function page. I'm thinking to:

  - Leave the descriptions for each component as it is;
  - Add a note at the end of the "Values" section for color functions like this:

    > **Note:** `L`, `C`, `H`, or `A` can also be specified as `none`. See [missing components](#) for details.

    … where "missing components" points to the following subsection;

  - Add a "Missing components" subsection at the end of the "Syntax" [section](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword) section on `<color>`, which corresponds to [4.4. "Missing" Color Components and the 'none' Keyword](https://drafts.csswg.org/css-color-4/#missing);
  - Add an "Interpolation with missing components" subsection at the end of the "Interpolation" [section](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#interpolation), which corresponds to [12.2. Interpolating with Missing Components](https://drafts.csswg.org/css-color-4/#interpolation-missing).

Is this OK to go?

**Comment by bsmth** [comment]
This all sounds good to me, this would be a nice way to reduce the amount of repetition across pages. The interpolation with missing components could do with an example, but we can take a look at the review stage 👍🏻
