### ISSUE TITLE
CSS selector landing page v. module & sidebar

### ISSUE THREAD

**Issue by estelle** [mdn/content#27238]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors

### What specific section or headline is this issue about?

Should this be a guide?

### What information was incorrect, unhelpful, or incomplete?

There is no CSS selectors module page. One would expect this document, with the URL `CSS/CSS_selectors` would be a module page like most of the other modules and like most of the URLs that start with `CSS_`. We need a module page for the selector specification, and it should be at this URL.

Additionally, in the sidebar, pseudo-elements and pseudo-classes, both of which are selectors defined in the selector specification, have their own top-level nav heading rather than being nested under the selectors heading.

![Screen Shot showing the sidebar as described in the issue](https://github.com/mdn/content/assets/69888/173576f7-a291-405d-963e-426f4823e96e)

### What did you expect to see?

1. https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors as a `page-type: css-module`
2. pseudos being nested within selectors on the sidebar

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_selectors/index.md
* Last commit: https://github.com/mdn/content/commit/e87af7c2d48e6679acbb5172836e81fe2bc30f2d
* Document last modified: 2023-02-22T08:23:01.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed in https://github.com/mdn/content/pull/28062
