### ISSUE TITLE
No compatibility data found for css.selectors:-moz-drag-over

### ISSUE THREAD

**Issue by jasonren0403** [mdn/content#27256]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-drag-over

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

An error shown that there is no compatibility data.

### What did you expect to see?

compatibility data for css.selectors:-moz-drag-over, or "no compatibility data" if there is still none available

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_-moz-drag-over`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-drag-over
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_-moz-drag-over/index.md
* Last commit: https://github.com/mdn/content/commit/5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e
* Document last modified: 2023-02-21T06:49:52.000Z

</details>

**Comment by daiwanxing** [comment]
And Found another same one: https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-focusring

**Comment by bsmth** [comment]
Just FYI, it's easier to list the pages under CSS pseudos that **have** BCD:

- [`:-moz-broken`](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-broken)
- [`:-moz-only-whitespace`](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-only-whitespace)
- [`:-moz-submit-invalid`](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-submit-invalid)
- [`:-moz-window-inactive`](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-window-inactive)

I'm not sure how urgent it is to have BCD for the missing pages as most of these are vendor-specific and won't have support in browsers other than Fx anyway. These additions look only useful for historic reasons to understand which version they were added to Fx and their status (experimental / deprecated). Does that make sense or do you have other reasons to check BCD for these?

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/27247
