### ISSUE TITLE
Basic controls exercises

### ISSUE THREAD

**Issue by Ariech** [mdn/content#27258]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Test_your_skills:_Basic_controls

### What specific section or headline is this issue about?

Examples of finished exercises

### What information was incorrect, unhelpful, or incomplete?

"Try updating the live code below to recreate the finished example:". However, I can't see the finished example to know what to aim for.

### What did you expect to see?

Finished example

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/test_your_skills_colon__basic_controls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Test_your_skills:_Basic_controls
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/test_your_skills_colon__basic_controls/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by Phil-G-94** [comment]
Hi @Ariech, hope you're well. 

I've gone through these sections myself so completely understand the frustration with incomplete sections etc. I faced this same issue myself. 
If you'd like to progress and measure your work against something, I recommend comparing against this MD doc: 

https://github.com/mdn/learning-area/blob/main/html/forms/tasks/basic-controls/marking.md

Most (if not all) section tasks you go through will have a marking.md document you can compare your solution against so you can know what to aim for.

**Comment by Phil-G-94** [comment]
Hi @Ariech, 

My pleasure. Thank you for the reply, glad at least some of it was helpful. 

All good here and hope likewise with you :) 

Side note: did you mean to re-open the issue?

**Comment by bsmth** [comment]
Thanks, both, I'm going to close this one as resolved, if you think this is a mistake, please let me know. Thank you :)

**Comment by Phil-G-94** [comment]
Thank you @bsmth :)
