### ISSUE TITLE
Float dont take care about his translate

### ISSUE THREAD

**Issue by JulienSuan** [mdn/content#27257]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_shapes/Shapes_from_images

### What specific section or headline is this issue about?

when I translate my element who contain float, my <p> dont take care of this changment

### What information was incorrect, unhelpful, or incomplete?

incomplete : image with translate 

### What did you expect to see?

something who explain this

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_shapes/shapes_from_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_shapes/Shapes_from_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_shapes/shapes_from_images/index.md
* Last commit: https://github.com/mdn/content/commit/e1b6d7d2d02a07f7e86268c81678713fad4d9a5d
* Document last modified: 2023-05-25T23:48:32.000Z

</details>

**Comment by JulienSuan** [comment]
> 
"when I translate my element who contain float, my paragraph

dont take care of this changment"

**Comment by JulienSuan** [comment]
Ok i found a solution nevermind !

**Comment by postmeback** [comment]
Please close the issue, if it is no more relevant. 😃
