### ISSUE TITLE
Reference to Mozilla SVG Project

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#2729]
I figured to clean up the SVG section of MDN and ran into broken reference to „Mozilla SVG Project” on `/en-US/docs/Web/SVG`.

Since it's marked as archived on https://www-archive.mozilla.org/projects/svg/index.html I guess, it's purged from MDN Web Docs?
(I couldn't even find it on the production search as a result).

**Comment by himanshugarg** [comment]
Sorry, the issue isn't obvious. Some broken links? Do they still exist? Or they need targets?

**Comment by Ryuno-Ki** [comment]
It looks like the link got dropped with https://github.com/mdn/content/commit/82a7fbd2b14c904ae7651bc8e144982837d1257a#diff-9c75e607d36f0ab4bd85fce7b11f14005a1f89dd6312271a289a7a75914f5cf6 in #2731

https://github.com/mdn/content/blob/45a7c78ec1b5fbe7aa9107059a15e9e2c142f834/files/en-us/web/svg/index.html#L67

Closing.
