### ISSUE TITLE
Clarity on JSON.Parse

### ISSUE THREAD

**Issue by LRagji** [mdn/content#27292]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse

### What specific section or headline is this issue about?

The reviver parameter

### What information was incorrect, unhelpful, or incomplete?

As stated in documentation "The reviver is called with the object containing the property being processed as `this`", not sure what this line means, as i understand it if i call `this` in the reviver function then i should get the object on which the key is located (since it does depth first), but instead i always get `global` object, is the interpretation wrong or the implementation broken..
Code:
```
 const r = (key, value) => {
        console.log(`T: ${this} K: ${key} V: ${value}`)
        return null;
    }
   JSON.parse('{"name":{ "something": { "testk": "testv" } }}', r);
```

### What did you expect to see?

`this` to be equal to the parent object on which the key being parsed is.

### Do you have any supporting links, references, or citations?

TS typings seems to have extra argument(this) for reviver function in like `(method) JSON.parse(text: string, reviver?: ((this: any, key: string, value: any) => any) | undefined): any` 

vs in chrome if you run the function with 3 args the last argument seems to have some magic object
**code**:
```
const r = (t,key, value) => {
        console.log(`T: ${t} K: ${key} V: ${JSON.stringify(value)}`)
        return null;
    }
JSON.parse('{"name":{ "something": { "testk": "testv" } }}', r);
```
**output**:
```
T: testk K: testv V: {"source":"\"testv\""}
VM115:2 T: something K: [object Object] V: {}
VM115:2 T: name K: [object Object] V: {}
VM115:2 T:  K: [object Object] V: {}
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/json/parse`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/json/parse/index.md
* Last commit: https://github.com/mdn/content/commit/6a0f9553932823cd0c4dcf695d4b4813474964fb
* Document last modified: 2023-04-12T16:34:04.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! Arrow functions don't have their own `this` binding. You need to use a normal function.

```js
function r(key, value) {
  console.log("T", this, "K", key, "V", value);
  return value;
}
JSON.parse('{"name":{ "something": { "testk": "testv" } }}', r);
```
