### ISSUE TITLE
CSS @font-face/baseline semantics

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#2730]
There's a reference from https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alphabetic to `@font-face/baseline` which is currently broken.

I checked the `@font-face` page on the CSS section and could not find any reference to `baseline` there.
Since the context is

> It has the same syntax and semantics as the baseline descriptor within an @font-face.

a simple removal is not an option either.
Where can I find the semantics defined nowadays?

**Comment by rachelandrew** [comment]
It looks like the baseline descriptor went at some early point in CSS Fonts 3. I did have a bit of a search for the resolution for it, this is therefore an SVG rather than CSS issue. I'm not sure who would be best to ask about this though.

**Comment by rachelandrew** [comment]
also, given this refers to something that is deprecated, possibly not super important unless other things refer to the same descriptor.

**Comment by Ryuno-Ki** [comment]
Okay, cool. I'm part of the SVG review group, so might find time to do some research as well.
Thanks for the info you found already!

**Comment by Josh-Cena** [comment]
Since `alphabetic` itself has been unshipped in all browsers, I think this is no longer worth fixing (as fixing requires actually describing what the value is). As such I'll close it, and then after a few months this page will be eligible for removal altogether.
