### ISSUE TITLE
The behavior of 'overflow: overlay;' is changed in Chrome (and others?) to be exactly the same as 'auto'

### ISSUE THREAD

**Issue by hakanedison** [mdn/content#27322]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter

### What information was incorrect, unhelpful, or incomplete?

The behavior of 'overlay' is described as "Overlay scrollbars are placed over the content, not in a gutter, and are usually partially transparent.", "Overlay scrollbars do not consume space." and more. Also in the section [Overlay scrollbars](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter#overlay_scrollbars).

### What did you expect to see?

The behavior for 'overlay' described correctly.

### Do you have any supporting links, references, or citations?

[overflow:overlay aliases overflow:auto](https://chromestatus.com/feature/5194091479957504)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/scrollbar-gutter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/scrollbar-gutter/index.md
* Last commit: https://github.com/mdn/content/commit/9428e6f9ac2fd4166b5cf245fb674123209787ff
* Document last modified: 2023-02-21T06:10:16.000Z

</details>

**Comment by wbamberg** [comment]
@hakanedison , this page is describing the general concept of overlay scrollbars (in contrast to "classic" scrollbars), which are a thing independent of the `overlay` value of `overflow`.

**Comment by hakanedison** [comment]
@wbamberg What page do you meen?

**Comment by wbamberg** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter , the page linked in the report.
