### ISSUE TITLE
Math 2 Step 4 is too hard

### ISSUE THREAD

**Issue by JamesC01** [mdn/content#27320]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Math

### What specific section or headline is this issue about?

Math 2 Task, step 4

### What information was incorrect, unhelpful, or incomplete?

I know this sounds silly, but I think step 4 of Math 2 is too hard. It relies on you to somehow figure out that you need to place parentheses in very specific spots. I've been into programming for years and even I got stuck on that. It's far more of a math problem than a javascript learning exercise.

### What did you expect to see?

A mention of parentheses, or perhaps just an easier question that doesn't rely on you randomly guessing to wrap certain parts of the calculation in parentheses. I understand that it says to not modify the operators or numbers, but I still think the step isn't clear enough. Maybe even mentioning the specific lines you should modify. "Original calculations" doesn't make it _too_ clear what I should be editing. Should I be editing the calculations that were there, or the ones that I added in the first step? It's not clear.

I think giving a hint, along the lines of "You'll need to change the precedence." Would make it much more clear what you're meant to be doing.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/test_your_skills_colon__math`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Math
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/test_your_skills_colon__math/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by Josh-Cena** [comment]
Even when I know it's about changing precedence, I still have little idea about how I should do it. I think it's fine if we just remove this step.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/pull/27628 and associated PRs.
