### ISSUE TITLE
Issue with "float": Embedded result demo can't be opened in Firefox 

### ISSUE THREAD

**Issue by felipecalvo** [mdn/content#2732]
MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/float

#### What information was incorrect, unhelpful, or incomplete?
![image](https://user-images.githubusercontent.com/11304439/109360864-ada1ee00-7866-11eb-959f-28aad184b627.png)

#### Specific section or headline?
Ejemplos / Resultado

#### What did you expect to see?
The demo.

#### Did you test this? If so, how?
Yes, just loading the page in Firefox.

<details>
<summary>MDN Content page report details</summary>

* Folder: `es/web/css/float`
* MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/float
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/css/float/index.html
* Last commit: https://github.com/mdn/translated-content/commit/null
* Document last modified: 2020-11-07T16:01:06.351Z

</details>

**Comment by chrisdavidmills** [comment]
Apologies, but we are not currently making changes to translations. See https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
