### ISSUE TITLE
Misleading description on max css

### ISSUE THREAD

**Issue by a2937** [mdn/content#27331]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/max

### What specific section or headline is this issue about?

Try it 

### What information was incorrect, unhelpful, or incomplete?

The statement `Think of the max() value as providing the minimum value a property can have.`  is worded somewhat awkwardly. It implies that the value returned is the smallest of a series of numbers. Even though in the example , it returns the largest of the values. 

### What did you expect to see?

Well in this case , something more along the lines like `Think of the max() value will always return the largest value a property can be.` or something like "The max() value will always be the largest of a series of comma-separated values" 

 In the example given , it pointed out that will always be at least 400px but if the view-port grows; it will grow larger because of the view-port unit size. 

### Do you have any supporting links, references, or citations?

https://www.w3schools.com/cssref/func_max.php

### Do you have anything more you want to share?

The page for [min](https://developer.mozilla.org/en-US/docs/Web/CSS/min#try_it) will need to be updated as well if this issue is accepted. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/max`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/max
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/max/index.md
* Last commit: https://github.com/mdn/content/commit/7a9f9baa25d9a7313bd6c62ef5ef585b28459c58
* Document last modified: 2023-02-21T06:01:00.000Z

</details>

**Comment by abhishekrnjn** [comment]
Hi @a2937,
Doc seems incorrect to me too. Also in the syntax part it says "The max() function takes one or more comma-separated expressions as its parameter, with the largest (most positive) expression value used as the value of the property to which it is assigned."

**Comment by yarusome** [comment]
See also #24833.

**Comment by bsmth** [comment]
Thanks for raising it, it's indeed awkward. You can see from the [recent improvements](https://github.com/mdn/content/pull/24942/files#diff-6160fdca938bd1e0ae42fd53d880b845d90ce75ddac8dfae1b2af70cbf6e6356R81) on the `min-max-clamp()` function that the concept for using it in this way is to pick the maximum value from a list:

```css
font-size: max(4vw, 2em, 2rem);
```

And to use whichever is largest as the value you do not want your styles to go below under different conditions.

In this case, I think we might be able to improve it with something along the lines of 'applying this declaration to the `<h1>` element, you can make sure that the element `font-size` does not go below the largest of any of the three values` - does that make sense?
