### ISSUE TITLE
Bad Request - Header Field Too Long

### ISSUE THREAD

**Issue by yesams** [mdn/content#27348]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431

### What specific section or headline is this issue about?

Login into univeristy website

### What information was incorrect, unhelpful, or incomplete?

Bad Request - Header Field Too Long

I see this message appearing a lot suddenly when I try to open a site that requires a loging page. Not so when I use another browser e.g. Safari.

Can't copy the urls since it refers to a secure environment 

### What did you expect to see?

Expected the login screen to appear.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/431`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/431/index.md
* Last commit: https://github.com/mdn/content/commit/0880a90f3811475d78bc4b2c344eb4146f25f66c
* Document last modified: 2023-04-10T19:47:15.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing, @yesams ! As far as I can see this isn't an issue with the MDN documentation, so I'm closing it. If there is a documentation issue, please feel free to re-open and describe the issue.
