### ISSUE TITLE
Outdated info about what APIs browsers support to query via Permissions API

### ISSUE THREAD

**Issue by Dimas-e63s** [mdn/content#27341]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API/Using_the_Permissions_API

### What specific section or headline is this issue about?

About general usage of the API

### What information was incorrect, unhelpful, or incomplete?

> "The only two APIs currently recognized by the Permissions API in Chrome are [Geolocation](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation) and Notification, with Firefox also recognizing [Push](https://developer.mozilla.org/en-US/docs/Web/API/Push_API) and WebMIDI."

It's no longer correct, Firefox already implemented the ability to query the status of Geolocation API, as well as Chrome is implemented the query of the status of  Notification API permissions and Web Midi API

### What did you expect to see?

I think the better option is to link to the [Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API#browser_compatibility) table for the reader to refer to. Also, I believe that this cited paragraph can be removed completely because it misleads rather than helpmisleads

### Do you have any supporting links, references, or citations?

Cited paragraph:  [Using_the_Permissions_API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API/Using_the_Permissions_API#the_trouble_with_asking_for_permission%E2%80%A6)
Cited compatibility table: [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API#browser_compatibility)

**Comment by skyclouds2001** [comment]
Since the text can not be found, I guess the issue has already fixed yet

**Comment by skyclouds2001** [comment]
> Since the text can not be found, I guess the issue has already fixed yet

@Josh-Cena

**Comment by Josh-Cena** [comment]
Fixed already in https://github.com/mdn/content/pull/27817
