### ISSUE TITLE
Slightly misleading wording around Atomics.wait/Async

### ISSUE THREAD

**Issue by WebReflection** [mdn/content#27356]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/wait

### What specific section or headline is this issue about?

The Note

### What information was incorrect, unhelpful, or incomplete?

**Note:** This operation only works with a shared [Int32Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array) or [BigInt64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array) and may not be allowed on the main thread.

### What did you expect to see?

It's a bit of a brainstorming session or just plain wrong wording to me ... to use a *SharedArrayBuffer* I don't strictly need to "*share*" an *Int32Array* or even a *BigInt64Array*, all I need to do is to use these **views** to deal with the received *SharedArrayBuffer*.

In short, I've found a bit misleading the concept of "*a shared Int32Array*" as that can't be used as transferable + it really doesn't need to be posted at all to coordinate *Atomics* operations, as 2 `new Int32Array(sab)` in both main thread and the worker would do just fine, and the memory consumption, after a structured clone algorithm, won't grant or guarantee any memory saving in passing along these references, instead of the raw *SharedArrayBuffer*, also used in most blog posts examples.

### Do you have any supporting links, references, or citations?

My recent blog post around *SharedArrayBuffer and Atomics* show, and live test, that no view is strictly needed to operate, and a reference to such buffer would be enough: https://webreflection.medium.com/about-sharedarraybuffer-atomics-87f97ddfc098

Do I need to change those examples because my understanding and working code is somehow *wrong* and those buffers need to be posted already as `Int32Array`?

Is this rather a hint that there's no need to create multiple `Int32Array` on both sides?

I am fully open to learn more here, and eventually fix that blog post too, thanks!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/atomics/wait`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/wait
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/atomics/wait/index.md
* Last commit: https://github.com/mdn/content/commit/a92a2bb31cf5d79808878701f0344a4eabf12963
* Document last modified: 2023-04-06T04:58:26.000Z

</details>

**Comment by Josh-Cena** [comment]
I reckon you probably know more about shared memory than most contributors here, so if you have any concrete ideas feel free to send a PR :)

**Comment by WebReflection** [comment]
OK, this is how I would probably rephrase it:

### wait
**Note:** This operation only works with a shared buffer handled by [Int32Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array) or [BigInt64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array) and may not be allowed on the main thread.

### waitAsync
**Note:** This operation only works with a shared buffer handled by [Int32Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array) or [BigInt64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array).

**Comment by Kaiido** [comment]
I personally find this rewording a bit more misleading. To me this would mean that the methods expect the `SharedArrayBuffer` instance, while what they accept is the `TypedArray` view, not the buffer.  
If you look at the error message you pasted in your blog post for ***Why not TextEncoder to populate?***, you can see that your browser also uses a similar wording "*The provided Uint8Array value must not be shared*".  

Finally, I'm not sure what's your point about the transferability of the `TypedArray`, a `SharedArrayBuffer` isn't transferable anyway.

**Comment by Josh-Cena** [comment]
I think the idea is that the `Int32Array` is not shared, but it's a view to a shared buffer. What about:

> **Note:** This operation only works with an [`Int32Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array) or [`BigInt64Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array) that is a view of a `SharedArrayBuffer`.

**Comment by WebReflection** [comment]
> To me this would mean that the methods expect the SharedArrayBuffer instance, while what they accept is the TypedArray view, not the buffer.

that's wrong. you can `postMessage` just the `SharedArrayBuffer` and everything would be fine, you don't need to share any view with it *but* a view containing a *SharedArrayBuffer* is able to do Atomics operations in it.

The view is not mandatory at all, which was the point I've tried to make in here.

**Comment by Josh-Cena** [comment]
> The view is not mandatory at all

The view is mandatory because you cannot directly pass the buffer as an argument to `Atomics.wait`. I think that's the main confusion point here.

**Comment by WebReflection** [comment]
that *share* is the misleading part ... 

> This operation only works with a shared [Int32Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array) or [BigInt64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array) and may not be allowed on the main thread

what you *share* form a thread to a main is the *SharedArrayBuffer*, not its view, as its view won't be shared (nor be transferable) so that particular wording is misleading because the view and the *share* concept don't have any relationship.

**Comment by WebReflection** [comment]
The PR looks good though and it addresses my point, thanks!

**Comment by Kaiido** [comment]
@WebReflection your proposed wording was making it sound like the methods were expecting the `SharedArrayBuffer` object. That's what I was pointing out. 

Yes we all agree that the colloquial "shared view" is a bit misleading, though your point on transferrability doesn't hold since you have to postMessage a `SharedArrayBuffer` the same than a view of it: neither can be transferred. If we want to be pedantic not even the SharedArrayBuffer object is shared, only the memory both objects (the one in the main thread and the copy) point to is.
