### ISSUE TITLE
Some images are not displayed correctly

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#27351]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_backgrounds_and_borders/Resizing_background_images

### What information was incorrect, unhelpful, or incomplete?

Hello,

Some images are not displayed correctly:
- Tiling a large image
- contain
- cover

### What did you expect to see?

images are displayed correctly

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_backgrounds_and_borders/resizing_background_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_backgrounds_and_borders/Resizing_background_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_backgrounds_and_borders/resizing_background_images/index.md
* Last commit: https://github.com/mdn/content/commit/883b021c97375f872d0702f0d0747b1373155cef
* Document last modified: 2023-05-24T20:30:20.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting this @DomOBU - could you provide some information about your browser version & OS. This works as expected for me (Firefox 115.0a1):

![image](https://github.com/mdn/content/assets/43580235/fd29c423-2e9e-407b-a215-ba621b4b44a0)
