### ISSUE TITLE
The Indonesian translated content does not match the original page

### ISSUE THREAD

**Issue by mfaridw** [mdn/content#2736]
![Screenshot at 2021-02-27 11-10-17](https://user-images.githubusercontent.com/20721671/109375082-8a218680-78ec-11eb-8e4d-b800380343fb.png)

**Comment by CreaTorAlexander** [comment]
As far as I know the mdn/content doesn't tackle translation issues at the moment @mfaridw

**Comment by chrisdavidmills** [comment]
Apologies, but we are not currently making changes to translations. See https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
