### ISSUE TITLE
Incorect content in Django Local Library Tutorial

### ISSUE THREAD

**Issue by SoSaymon** [mdn/content#27374]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views

### What specific section or headline is this issue about?

View (class based)

### What information was incorrect, unhelpful, or incomplete?

After copying the code of the `BookListView` and `BookDetailView` class, I get the error `TemplateDoesNotExist at /catalog/books/` [screenshot](https://imgur.com/a/IEpzFb0). Link to my repo is [here](https://github.com/SoSaymon/django-local-library/commit/7232fca9451109b5e65346441891100e252dec10)

### What did you expect to see?

To make the code work you need to add `template_name` to the class with the name of the HTML file

```python
class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

    template_name = 'book_list.html'
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/django/generic_views`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/generic_views/index.md
* Last commit: https://github.com/mdn/content/commit/65b9418c7d0e3a331ac50249adf0024f44789923
* Document last modified: 2023-05-09T00:34:38.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you, but is incorrect.

As stated in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views#view_class-based

> That's it! The generic view will query the database to get all records for the specified model (Book) then render a template located at /locallibrary/catalog/templates/catalog/book_list.html (which we will create below). Within the template you can access the list of books with the template variable named object_list OR book_list (i.e. generically "<the model name>_list").

Note the really odd path suggested - you have put your files in the wrong place. 

You only need the template_name to put the files somewhere else or give them a name you like more.

There is a worked example you can compare to in https://github.com/mdn/django-locallibrary-tutorial
