### ISSUE TITLE
table align issue

### ISSUE THREAD

**Issue by caish156** [mdn/content#27373]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Issues

### What specific section or headline is this issue about?

table attribute margin-left & margin-right

### What information was incorrect, unhelpful, or incomplete?

_Set [margin-left] and [margin-right]to auto or [margin] to 0 auto to achieve an effect that is similar to the align attribute._
Can you please provide me a combination of margin: / " __ , __ /". which can align table in right.

### What did you expect to see?

table in right side

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

using microsoft edge Version 114.0.1823.43 (Official build) (64-bit)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community/issues`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community/Issues
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/issues/index.md
* Last commit: https://github.com/mdn/content/commit/ac5dfaa2f71a7381cd8fdd4cb554507f375ac19c
* Document last modified: 2023-02-26T18:54:50.000Z

</details>

**Comment by dscotese** [comment]
@caish156 You entered the link to the guidelines to opening and working on issues rather than a page that describes aligning tables.  I think you were talking about https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table, and if so, please edit your description to correct the link at the top to that one.

**Comment by Josh-Cena** [comment]
`align="right"` is margin-right: 0; margin-left: auto;`, and `align="center"` is `margin-right: auto; margin-left: auto;`
