### ISSUE TITLE
Issue with "Binary strings": …StringView's hyperlinks are broken

### ISSUE THREAD

**Issue by jasontwuk** [mdn/content#274]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMString/Binary

#### What information was incorrect, unhelpful, or incomplete?
StringView's hyperlinks are broken.

#### Specific section or headline?
They are at the bottom of the web page, please see the highlighted area in the image below.
![StringView](https://user-images.githubusercontent.com/13745974/102313531-b58d0a00-3f68-11eb-92ae-5fb9ad3d5b4e.png)

#### What did you expect to see?
It seems like "StringView" has been archived, so maybe those links should be removed from this page?https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Code_snippets/StringView_library

#### Did you test this? If so, how?
Yes, I tried to open those links in my browser.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/domstring/binary`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMString/Binary
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/domstring/binary/index.html
* Report started: 2020-12-16T06:17:56.068Z

</details>

**Comment by chrisdavidmills** [comment]
I'd agree with removing mention of `StringView`. It's a platform feature, and not relevant to web devs.

**Comment by jasontwuk** [comment]
Hi Chris, thank you for the reply.
is that ok I PR this issue?

**Comment by chrisdavidmills** [comment]
@jasontwuk yes, please do!
