### ISSUE TITLE
[Behind pref] change togglePopover to return a boolean

### ISSUE THREAD

**Issue by josepharhar** [mdn/content#27417]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/togglePopover

### What information was incorrect, unhelpful, or incomplete?

The togglePopover article is not up to date with this spec change: https://github.com/whatwg/html/pull/9393

### What did you expect to see?

We are modifying togglePopover to return a boolean. It will return true if the popover is open after calling togglePopover, otherwise false.

**Comment by hamishwillee** [comment]
MDN documents things once there is a browser implementation (specifically Safari, Chromium, Firefox). The linked item indicates WebKit has done this but not showing up in Internet search. Is this in a Safari release yet?

**Comment by josepharhar** [comment]
I don't think safari has released this behavior yet.
It should be released in chrome 116 in august

**Comment by hamishwillee** [comment]
Thanks. Feel free to ping here if you see any of them appearing in the wild. If nothing else, our process will catch a firefox release.

**Comment by Rumyra** [comment]
FF bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1833570 - we can make this change. I've added to our FF project

**Comment by hamishwillee** [comment]
I've written the docs, but the change does not appear to actually work/return a boolean (at least in FF117). So waiting on confirmation: https://bugzilla.mozilla.org/show_bug.cgi?id=1833570#c16

Status
- [ ] BCD
- [ ] Release note
- [ ] Docs - #27942
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
I just came to ref that above bug @hamishwillee - seems its in 117 👍

**Comment by hamishwillee** [comment]
Yes, which is why I labeled as 117 :-)

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/20439
- [ ] Docs #28310
- [ ] Experimental features
- [ ] dev-docs-complete

**Comment by Rumyra** [comment]
lgtm - thanks @hamishwillee @josepharhar
