### ISSUE TITLE
Issue with "Installing LocalLibrary on PWS/Cloud Foundry": (short summary here please)

### ISSUE THREAD

**Issue by richajak** [mdn/content#2742]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Installing_on_PWS_Cloud_Foundry

#### What information was incorrect, unhelpful, or incomplete?
The guideline is not relevant anymore as Pivotal (the company) has stopped its service as of Sep 17 2020

https://blog.run.pivotal.io/pivotal-web-services-end-of-availability-announcement-and-timeline/

#### Specific section or headline?

Whole article

#### What did you expect to see?

Delete this article

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/installing_on_pws_cloud_foundry`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Installing_on_PWS_Cloud_Foundry
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/installing_on_pws_cloud_foundry/index.html
* Last commit: https://github.com/mdn/content/commit/3f0d70a833121be094f90194c23b3acfb19539fa
* Document last modified: 2021-01-29T00:55:21.000Z

</details>

**Comment by richajak** [comment]
also the link at https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs

Installing LocalLibrary on PWS/Cloud Foundry
This article provides a practical demonstration of how to install LocalLibrary on the Pivotal Web Services PaaS cloud — this is a full-featured, open source alternative to Heroku, the PaaS cloud service used in Part 7 of the tutorial, listed above. PWS/Cloud Foundry is definitely worth checking out if you are looking for an alternative to Heroku (or another PaaS cloud service), or feel like trying something different.

**Comment by sideshowbarker** [comment]
Thanks for the heads-up — I’ve opened https://github.com/mdn/content/pull/2743 with a change which removes that article, as well as the links to it from other articles.
