### ISSUE TITLE
Paragraph with an ill-advised point of view.

### ISSUE THREAD

**Issue by N8HSU** [mdn/content#27438]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_web_server

### What specific section or headline is this issue about?

Section: Static vs. dynamic content

### What information was incorrect, unhelpful, or incomplete?

The last paragraph was both unhelpful and insulting. It states, "Unless you want to learn web server programming (which is an exciting area in itself!), you don't need to create your own application server. That's just [reinventing the wheel]". I am seeking that very help for a micro-controller project. So, I click on the hyperlink to go get it, but, got the Wikipedia definition of the expression. This shows narrow-mindedness assuming that students here only want to develop for corporate sites and belittles those that do need "web server programming" for valid reasons. 

### What did you expect to see?

Do not judge that its a waste of time. Just state its beyond the scope and point us to where we can get it. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/common_questions/web_mechanics/what_is_a_web_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_web_server
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/web_mechanics/what_is_a_web_server/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by bsmth** [comment]
Thanks for raising the issue @N8HSU - I think the original intention of this section was to emphasize that there are many off-the-shelf application server technologies that will help beginners get started with a website such as a blog, and it might be worth trying those first. I've reworded it in the linked PR, with a link to the server-side pathway for those who want to dip into that area.

**Comment by bsmth** [comment]
@N8HSU Would you mind giving some more information as to what you expected to see?

It would also be interesting to know:
* What kind of server are you looking to build?
  * what functionality should it have?
* What device are you using?
* which programming language does the micro-controller run?


Thanks :)

**Comment by hamishwillee** [comment]
Fixed by https://github.com/mdn/content/pull/27452 . If this does not do what you need @N8HSU , please raise a new issue with more specific information.
