### ISSUE TITLE
german page "Logische Operatoren" has a broken iframe

### ISSUE THREAD

**Issue by Felix-Puetz** [mdn/content#2745]
![image](https://user-images.githubusercontent.com/50131232/109387727-59991700-7903-11eb-9860-10ad6cc1ab58.png)

The embeded iframe calling the url `https://interactive-examples.mdn.mozilla.net/pages/js/expressions-logicaloperator.html` seems to be broken

Im was using the following browser:
Google Chrome - Version 88.0.4324.190 (Official Build) (64-Bit)

**Comment by chrisdavidmills** [comment]
Apologies, but we are not currently making changes to translations. See https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
