### ISSUE TITLE
CSS :has() is the conceptual counterpart of a RegEx lookahead

### ISSUE THREAD

**Issue by porg** [mdn/content#27464]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:has

### What specific section or headline is this issue about?

None in particular.

### What information was incorrect, unhelpful, or incomplete?

Two aspects to possibly include into the article. See next section.

## Info worth adding into the article

The CSS `:has()` selector is conceptional very closely related to a lookahead in RegEx.
  - I think that would be worth to mention either inline (where appropriate) or in a dedicated "Related / Other" section.

Because, that's how some folks will search for it.
- E.g. one person in 2012 asked for https://stackoverflow.com/questions/10865285/positive-lookahead-in-css when this was yet not possible
- So adding this info will be some SEO.
- And when just reading over the related RegEx concept, without a prior search for "lookahead", some readers may still get their personal "Aha/Heureka" moment, which helps them to connect some learnings/knowhow in their mind.

## Question which the article could / should answer

- Is a negative lookahead possible by wrapping a `:not()` within a `:has()` ?
  - E.g. `h2:has(not(+ p.intro))` would select a `h2`, except when it is followed by a `p` element with a `.intro` class (the negative lookahead part).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_has`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:has
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_has/index.md
* Last commit: https://github.com/mdn/content/commit/5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e
* Document last modified: 2023-02-21T06:49:52.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi @porg, while I may see why this is useful for some readers' comprehension, I'm fairly sure there will be few contributors or maintainers will know how to put these ideas down in words. I'm going to label this as https://github.com/mdn/content/labels/help%20wanted and we would appreciate you sending a PR.

**Comment by porg** [comment]
- I was able to roughly circumscribe what info would have helped me.
- But I fear I am not versed enough in the subject domain of CSS to write that properly.
- Hopefully someone can make that editorial contribution.

**Comment by porg** [comment]
Thanks a lot for that editorially great contribution!
