### ISSUE TITLE
border-style inset behaves like ridge, outset behaves like groove with border-collapse

### ISSUE THREAD

**Issue by nguyenvantungisme** [mdn/content#27475]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/border-collapse

### What specific section or headline is this issue about?

Wrong content

### What information was incorrect, unhelpful, or incomplete?

This part : When cells are collapsed, the [border-style](https://developer.mozilla.org/en-US/docs/Web/CSS/border-style) value of **inset behaves like groove, and outset behaves like ridge**.

### What did you expect to see?

Edit : inset behaves like ridge, outset behaves like groove

### Do you have any supporting links, references, or citations?

border-style inset behaves like ridge, outset behaves like groove

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/border-collapse`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/border-collapse
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/border-collapse/index.md
* Last commit: https://github.com/mdn/content/commit/42c1bb8c259f3f57de9f38600776cf273e3addda
* Document last modified: 2023-02-21T06:27:49.000Z

</details>

**Comment by Josh-Cena** [comment]
`border-style` would also need to be updated.
