### ISSUE TITLE
CSP error when following instructions

### ISSUE THREAD

**Issue by danielhoherd** [mdn/content#27491]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/What_are_browser_developer_tools

### What specific section or headline is this issue about?

The Javascript Console

### What information was incorrect, unhelpful, or incomplete?

The page asks the user to paste the following code:
```js
const myWordmark = document.createElement("img");
myWordmark.setAttribute(
  "src",
  "https://blog.mozilla.org/press/wp-content/themes/OneMozilla/img/mozilla-wordmark.png"
);
document.querySelector("h1").appendChild(myWordmark);
```

When doing this, the user is greeted with the following error:

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://blog.mozilla.org/press/wp-content/themes/OneMozilla/img/mozilla-wordmark.png (“img-src”).
```

### What did you expect to see?

I'm honestly not sure because I couldn't get it to work.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/common_questions/tools_and_setup/what_are_browser_developer_tools`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/What_are_browser_developer_tools
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/tools_and_setup/what_are_browser_developer_tools/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. The CSP for this page allows:
```
'self'
*.githubusercontent.com
*.googleusercontent.com
*.gravatar.com
mozillausercontent.com
firefoxusercontent.com
profile.stage.mozaws.net
profile.accounts.firefox.com
mdn.dev
interactive-examples.mdn.mozilla.net
interactive-examples.mdn.allizom.net
wikipedia.org
upload.wikimedia.org
www.google-analytics.com
www.gstatic.com
```

So I have fixed this up by replacing the image with one that is allowed. See https://github.com/mdn/content/pull/27492
