### ISSUE TITLE
Issue with "data-*": ('semicolon' does not match presented unicode value)

### ISSUE THREAD

**Issue by shaunbruno** [mdn/content#2751]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*

#### What information was incorrect, unhelpful, or incomplete?
"the name must not contain any semicolon (U+003A);"

'semicolon' does not match unicode value (it matches the 'colon' value)

#### Specific section or headline?
data-* top level content

#### What did you expect to see?
Either 
"the name must not contain any colon (U+003A);"
OR
"the name must not contain any semicolon (U+003B);"

#### Did you test this? If so, how?
"\u003a" == ':'
// => true
"\u003b" == ';' 
// => true

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/global_attributes/data-_star_`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/data-_star_/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by CreaTorAlexander** [comment]
Can update this 👍

**Comment by CreaTorAlexander** [comment]
Thanks for reporting this.

I created PR https://github.com/mdn/content/pull/2754 to fix this
