### ISSUE TITLE
Issue with "Django Tutorial Part 7: Sessions framework": (short summary here please)

### ISSUE THREAD

**Issue by CodeByLine** [mdn/content#2752]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Sessions

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/sessions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Sessions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/sessions/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by CodeByLine** [comment]
The session count goes up by 2 each time.

**Comment by CreaTorAlexander** [comment]
Thanks for reporting this. I will take a look at it :+1:

**Comment by Ryuno-Ki** [comment]
Looking forward to it, @CreaTorAlexander

**Comment by hamishwillee** [comment]
Please leave this one for me :-)

**Comment by CreaTorAlexander** [comment]
Sure, go for it @hamishwillee

**Comment by CodeByLine** [comment]
Not sure what to make of it, but the issue got resolved after restarting the computer. My apologies if this was on my end.

**Comment by hamishwillee** [comment]
I think it probably was. I tested and reviewed the code and it looks fine. Not a problem though - had this been an error we needed to know. Thanks :-)
