### ISSUE TITLE
Regroup the page types for CSS selectors

### ISSUE THREAD

**Issue by yarusome** [mdn/content#27526]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::cue

### What information was incorrect, unhelpful, or incomplete?

CSS selector pages have various page types such as "css-combinators" (e.g. [Adjacent sibling combinator](https://github.com/mdn/content/blob/main/files/en-us/web/css/adjacent_sibling_combinator/index.md?plain=1)) and "css-pseudo-element" (e.g. [::cue](https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_cue/index.md?plain=1)), but this categorization seems both redundent and insufficient to some extent.

**Redundency:** The pages under [Expressions and operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators) for JavaScript are functionally similar to CSS selectors pages, but those pages don't get to (nor need to) be further grouped like "assignment operators" and "logical operators".

**Insufficiency:** Current page types don't differentiate `::cue` and `::cue()` (this pair should also have separate pages like the next pair do), nor [`:host`](https://developer.mozilla.org/en-US/docs/Web/CSS/:host) and [`:host()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:host_function).

### What did you expect to see?

Regroup the page types for CSS selectors as:

- css-selector
- css-pseudo-class
- css-pseudo-class-function
- css-pseudo-element
- css-pseudo-element-function

**Comment by Josh-Cena** [comment]
Related: https://github.com/mdn/content/issues/27238

For my education, why is a combinator a selector? Or are you saying that class selectors, etc. must be combined with combinators to form a complex selector, so they should be the same thing?

**Comment by yarusome** [comment]
@Josh-Cena I was mainly thinking about the use of page types for macros since macros treat combinators and selectors alike.

You're right about combinators being different from selectors, but there's an unfortunate example from the [spec](https://drafts.csswg.org/selectors/#table-pseudos) itself that intermixes these two concepts.

**Comment by yarusome** [comment]
Now I think `page-title` isn't thr right place to embed such info only needed for macros. A much better solution is the smart macro refactoring raised in [discussions/350](https://github.com/orgs/mdn/discussions/350).
