### ISSUE TITLE
List-style-type needs a pointer to Ready-made Counter Styles

### ISSUE THREAD

**Issue by r12a** [mdn/content#27539]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type

### What information was incorrect, unhelpful, or incomplete?

Information about custom counter styles.

### What did you expect to see?

The article at https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style has a section entitled [Ready-made counter styles](https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style#ready-made_counter_styles) which should probably also be added to this article about list-style-type, as it is relevant and useful in both locations.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/list-style-type`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/list-style-type/index.md
* Last commit: https://github.com/mdn/content/commit/73091fbe590d96857d743eaeec5aee4a8101994f
* Document last modified: 2023-02-21T05:50:15.000Z

</details>

**Comment by ilanchezhian-m** [comment]
Hey, can I get assigned to this issue?

**Comment by Josh-Cena** [comment]
We no longer assign issues to external contributors. Please just send a PR if you want to work on it.

**Comment by ilanchezhian-m** [comment]
okay, Thanks!
