### ISSUE TITLE
Issue with "Global attributes": “exportparts” needs to be properly documented

### ISSUE THREAD

**Issue by shaunbruno** [mdn/content#2753]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

#### What information was incorrect, unhelpful, or incomplete?
Global attribute `exportparts` has a link to url:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/exportparts

That links to a not found page (see attached screenshot)
![Screen Shot 2021-02-27 at 12 22 57 PM](https://user-images.githubusercontent.com/757901/109399264-aa564300-78f6-11eb-879d-046a13257d6f.png)

#### Specific section or headline?
List of global attributes

#### What did you expect to see?
Either (1) no link or (2) a found page

#### Did you test this? If so, how?
Clicked the link (see attached screenshot).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/global_attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/index.html
* Last commit: https://github.com/mdn/content/commit/bf7c25cfa1e9e632ee1ea058e124d6cad8153643
* Document last modified: 2021-02-26T18:20:08.000Z

</details>

**Comment by NegiAkash890** [comment]
![Screenshot from 2021-02-28 20-12-31](https://user-images.githubusercontent.com/55234838/109422450-8c293980-7a01-11eb-9b3b-9fe431ab0a65.png)

Hi , on hovering over the "exportparts" section it clearly starts that "This is an experimental that should not be used in the production code" implies that it's not written yet  . For confirmation  I also searched up for the file , but it wasn't there :) .

**Comment by shaunbruno** [comment]
> ![Screenshot from 2021-02-28 20-12-31](https://user-images.githubusercontent.com/55234838/109422450-8c293980-7a01-11eb-9b3b-9fe431ab0a65.png)
> 
> Hi , on hovering over the "exportparts" section it clearly states that "This is an experimental that should not be used in the production code" implies that it's not written yet . For confirmation I also searched up for the file , but it wasn't there :) .

I agree that messaging is useful. From my perspective (a user perspective), the issue is the dead link. It's OK if the page isn't written => just remove the link. 

Or else I would expect the linked page to, at minimum, provide a skeleton page related to `exportparts`, confirming it's an experimental feature, and sharing what content is available.

**Comment by NegiAkash890** [comment]
Thanks @shaunbruno . I absolutely agree with you . I believe that mdn will soon add the missing page and the issue will be fixed : )

**Comment by hamishwillee** [comment]
> "This is an experimental that should not be used in the production code" implies that it's not written yet . For confirmation I also searched up for the file , but it wasn't there :) .

Actually all that "experimental" tells you is that the feature is either still in a draft spec, or has only been implemented in a very small number of browsers. Or to put it another way, we typically remove that tag when the feature is in 2 or more browsers and the spec if approved. 

The fact that it is missing just means that no one has had time to do the work yet. We'd welcome a PR with the missing document!

**Comment by himanshugarg** [comment]
The dead link is "no more" and links to itself. We can close this issue, I think.

**Comment by estelle** [comment]
The link is broken in the BCD. 
Also, since it is implemented in all browsers, should likely get an explanation longer than 1 sentence.

**Comment by luwes** [comment]
> The value of the attribute should be a space-separated list of part names

should be 

> The value of the attribute should be a comma-separated list of part names


see https://drafts.csswg.org/css-shadow-parts/#exportparts-attr

**Comment by estelle** [comment]
https://github.com/mdn/content/pull/18799
