### ISSUE TITLE
DOMPoint creation API and example

### ISSUE THREAD

**Issue by alaindebecker** [mdn/content#27548]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/DOMPoint

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

I found no (=not at all) example on how to create a new DOMPoint. Nor not any arguments are need to.

### What did you expect to see?

var xy = new DOMPoint(x, y, z?, and others )
or 
var xy = DOMPoint(what in hell should I put here ?)

### Do you have anything more you want to share?

Please that it exists (I really congratulate the developers) but would only be lpeased if I can use it.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/dompoint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMPoint
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/dompoint/index.md
* Last commit: https://github.com/mdn/content/commit/8f91a466f5a6d1e238ed209f36f9b506fc73ee0d
* Document last modified: 2023-02-20T11:07:33.000Z

</details>

**Comment by Josh-Cena** [comment]
The constructor is documented in a separate page. https://developer.mozilla.org/en-US/docs/Web/API/DOMPoint/DOMPoint
