### ISSUE TITLE
There is an easier way to get form data

### ISSUE THREAD

**Issue by David263** [mdn/content#27543]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/elements

### What specific section or headline is this issue about?

(Not sure which section is best)

### What information was incorrect, unhelpful, or incomplete?

[I tried to edit this page myself, but could not figure out how to do it in GitHub. I have not been able to find understandable instructions for using GitHub.]

This page explains how to get a Collection of form elements. Even after converting this Collection to an array, it is still a list of elements, which is rarely needed. More common is the need for an object that maps Names to Values for each field of the form.

This is much easier to program just by using the Form element. Use form.length to get the length of the form data, then use a for loop to construct the object.

Here is a code example:

```
var form=document.getElementById(formID);
var pairs={};
for (var i=0; i<form.length ;i++)
    pairs[form[i].name]=form[i].value;
j=JSON.stringify(pairs,null,3);
alert(j);

```

### What did you expect to see?

I wanted an easy way to obtain the form data in JavaScript.

### Do you have any supporting links, references, or citations?

See https://stackoverflow.com/questions/39247160/javascript-formdata-to-array/76548330#76548330 .

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlformelement/elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlformelement/elements/index.md
* Last commit: https://github.com/mdn/content/commit/a3d9f61a8990ba7b53bda9748d1f26a9e9810b18
* Document last modified: 2023-04-07T00:39:15.000Z

</details>

**Comment by yarusome** [comment]
The core lines in your code can be rewritten using the modern syntax:

```js
let data = Object.fromEntries(
  [...form.elements].map((el) => [el.name, el.value])
);
```

That said, the main issue in the proposed SO code is that it just doesn't work as expected for `<form>` elements containing `<fieldset>` elements, as each `<input>` inside it, usually with `type="checkbox"` or `type="radio"`, will become separated entries in the constructed object.

**Comment by David263** [comment]
Yes, I noticed that some DOM apis ignore certain Form fields. I don't see any problem with using your code, since the new ECMA syntax has been available for several years. But if a truly back-compatible solution must be posted in MDN, then simply extend my code to account for fieldset and any other bugs in the fromEntries method. The revised code will work in almost all browsers, except maybe Lynx.

**Comment by Josh-Cena** [comment]
I'm closing because as as @yarusome said, it doesn't work with complex form structures. Usig the `FormData` constructor is much more resilient and makes your code easier to read too. The `element`s API is precisely for when you want to do something with the elements, not the data, such as setting things to disabled, or transforming the values. The SO question claimed that `formData.entries()` doesn't work with old browsers, but it's more than 6 years old in all major browsers, which per our guidelines is stable enough for production and we will not recommend practices to work around it.
