### ISSUE TITLE
operator ++ ..... return problem 

### ISSUE THREAD

**Issue by facucarattoli** [mdn/content#27541]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Increment§

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

```js
let x = 3;
const y = x++;

console.log(`x:${x}, y:${y}`);
// Expected output: "x:4, y:3"

let a = 3;
const b = ++a;

console.log(`a:${a}, b:${b}`);
// Expected output: "a:4, b:4"
```

### What did you expect to see?

I think that this is information is wrong because `const y = x++ ;   y:3`
This should return `y:4 `

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/increment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Increment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/increment/index.md
* Last commit: https://github.com/mdn/content/commit/93d2d79c1c68af93f2730d27cdea9d527eee0d7a
* Document last modified: 2023-03-28T05:38:31.000Z

</details>

**Comment by Josh-Cena** [comment]
Have you tried?

<img width="279" alt="image" src="https://github.com/mdn/content/assets/55398995/5a47eeed-7e12-414c-887a-b843d87a2048">

`x++` returns the value _before_ incrementing `x`. This is written explicitly in the documentation.
