### ISSUE TITLE
Issue with "Array": nav left sidebar bad link for 'Array' - /Global_Objects//Array  ('//' !)

### ISSUE THREAD

**Issue by tshinnic** [mdn/content#2755]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

#### What information was incorrect, unhelpful, or incomplete?

In the left sidebar, under "**Related Topics**" - "Standard built-in objects", the next link "Array" says 
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects//Array
but when clicked goes to 
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects_Array
which gets "page not found"

The correct link would be the original page 
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

#### Specific section or headline?

Left navigation sidebar

#### What did you expect to see?

Link as seen in the breadcrumbs, without the repeated '//'

#### Did you test this? If so, how?

Looked on other pages within the Array subject pages

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

.

When you are able to add more orientation for potential helpers, could you add pointers to where {{jsref}} and {{jsxref}} thingies are now found/sourced, and generalities like where/how the sidebars get added?

**Comment by tshinnic** [comment]
Situation also seen elsewhere, like
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/has
has in the left sidebar, under "**Related Topics**" - "Standard built-in objects", the next link "Map" as
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects//Map
which again gives page not found

**Comment by chengjieyun59** [comment]
I noticed the same thing today. This is seen in all Global_Objects, but I'm having a hard time pinpointing which file the issue lives in. I've searched for these in the cloned repo in VScode to no avail:
`Reference/Global_Objects/`
`Reference/Global_Objects_`
`Reference/Global_Objects//`
`Related Topics`
`Standard built-in objects`

We need to find the file that generates the left navigation sidebar, which I assume isn't hard-coded in HTML, but perhaps in JavaScript.

**Comment by CreaTorAlexander** [comment]
Do we have to update the link inside *_redirects.txt*?

**Comment by chrisdavidmills** [comment]
I think I know what's wrong here. The macro that generates this left hand sidebar is https://github.com/mdn/yari/blob/main/kumascript/macros/JSRef.ejs, and it should just be come kind of simple path building issue. I'll give it a go.

**Comment by tshinnic** [comment]
You had mentioned JSRef. I looked and 4 days ago change https://github.com/mdn/yari/commit/80df68cc04ef3f1782dd46ca50bb55f7d2f066a4#diff-768ca40d7ee2c26f2e17fbfe07ee535a5b812b83f989fa9ba9b729492c7c4b7e 
updated line 35 https://github.com/mdn/yari/blob/main/kumascript/macros/JSRef.ejs#L35

Looking at that makes me wonder if that didn't *add* an extra '/' at the end - compare number of slashes before and after.

The timing sure is suspicious, no?

**Comment by chrisdavidmills** [comment]
> You had mentioned JSRef. I looked and 4 days ago change [mdn/yari@80df68c#diff-768ca40d7ee2c26f2e17fbfe07ee535a5b812b83f989fa9ba9b729492c7c4b7e](https://github.com/mdn/yari/commit/80df68cc04ef3f1782dd46ca50bb55f7d2f066a4#diff-768ca40d7ee2c26f2e17fbfe07ee535a5b812b83f989fa9ba9b729492c7c4b7e)
> updated line 35 https://github.com/mdn/yari/blob/main/kumascript/macros/JSRef.ejs#L35
> 
> Looking at that makes me wonder if that didn't _add_ an extra '/' at the end - compare number of slashes before and after.
> 
> The timing sure is suspicious, no?

Ah, good investigating! I wouldn't say suspicious, but it does like a bug was possibly introduced.

**Comment by peterbe** [comment]
Fixed by https://github.com/mdn/yari/pull/3077
