### ISSUE TITLE
Does the Page Still Need Reference IE8 and IE9?

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#27569]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction

### What specific section or headline is this issue about?

Initial Planning

### What information was incorrect, unhelpful, or incomplete?

The following sentence references IE8 and IE9. Do we still need to have it there? 

It should also provide an acceptable experience on IE 8 and 9, and be accessible with WCAG AA compliance.

NOTE - There might be other places on this page or others in this section that needs reworking to remove the reference to older IEs.

### What did you expect to see?

Not to reference older IE browsers.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/cross_browser_testing/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/cross_browser_testing/introduction/index.md
* Last commit: https://github.com/mdn/content/commit/07236a4a6d5767b50d35225ba66d63553e950963
* Document last modified: 2023-04-16T05:41:38.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, no, fixed in https://github.com/mdn/content/pull/27578. Generally anything about having to do something "in particular" on IE should be removed. The only time to keep it is in the context of "remember how it was back in the day :-).
