### ISSUE TITLE
Opera Changed the URL of Their Bug Reporting

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#27570]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction

### What specific section or headline is this issue about?

Reporting bugs

### What information was incorrect, unhelpful, or incomplete?

The link to report Opera bugs ( https://help.opera.com/en/computer-bug-wizard/ ) has moved to https://opera.atlassian.net/servicedesk/customer/portal/9.

Part of the issue is the old URL is still there, telling a person to go to the new location.

### What did you expect to see?

The link to point to the most recent bug reporting page.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/cross_browser_testing/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/cross_browser_testing/introduction/index.md
* Last commit: https://github.com/mdn/content/commit/07236a4a6d5767b50d35225ba66d63553e950963
* Document last modified: 2023-04-16T05:41:38.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much - this has been fixed by https://github.com/mdn/content/pull/27576. 

FWIW For these kind of fixes, you might want to just create a PR by clicking the Edit link on the bottom of the page.
