### ISSUE TITLE
better example for pointerLockElement property

### ISSUE THREAD

**Issue by allan-bonadio** [mdn/content#27609]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/pointerLockElement

### What specific section or headline is this issue about?

example

### What information was incorrect, unhelpful, or incomplete?

```js
if (document.pointerLockElement === canvasElement) {
  console.log("The pointer lock status is now locked");
  // Do something useful in response
} else {
  console.log("The pointer lock status is now unlocked");
  // Do something useful in response
}
```

### What did you expect to see?

```js
let el = document.pointerLockElement;
if (el) {
  console.log(`The pointer IS locked! on to an element <${el.localName} ${ el.id ? 'id=' + el.id : '' } >`);
} else {
  console.log(`I guess the pointer's not locked in this document ${location.href}`);
}
```

That should print:
The pointer IS locked! on to an element `<nav  >`
if a `<nav>` element has the lock.

### Do you have anything more you want to share?

I promise I tested the above code in my app.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document/pointerlockelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/pointerLockElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/pointerlockelement/index.md
* Last commit: https://github.com/mdn/content/commit/41a8b9c9832359d445d136b6d7a8a28737badc6b
* Document last modified: 2023-04-07T05:52:28.000Z

</details>

**Comment by Josh-Cena** [comment]
We may have both examples, but I think the current one looks more real-world-relevant.

**Comment by Josh-Cena** [comment]
Okay then we need to change the log message. The point of this example is that you can lock onto a particular canvas (which seems more useful than keeping track of whatever the pointer is locked onto).
