### ISSUE TITLE
Document: exitPointerLock() needs one reminder

### ISSUE THREAD

**Issue by allan-bonadio** [mdn/content#27612]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/exitPointerLock

### What specific section or headline is this issue about?

should remind reader of a gotcha

### What information was incorrect, unhelpful, or incomplete?

Often, the method to do and undo something are on the same object.  But not in this case.  So, you should remind them.

### What did you expect to see?

This call is on the document, where as requestPointerLock() is on the element itself.
myDiv.requestPointerLock()
document.exitPointerLock()

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document/exitpointerlock`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/exitPointerLock
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/exitpointerlock/index.md
* Last commit: https://github.com/mdn/content/commit/41a8b9c9832359d445d136b6d7a8a28737badc6b
* Document last modified: 2023-04-07T05:52:28.000Z

</details>

**Comment by codecruisedor** [comment]
Hello, @allan-bonadio Greetings! As far as I understand we need to inform the user that 'exitPointerLock()' is called on the document, whereas 'requestPointerLock()' which can be used to request a pointer lock is called on an element.. is this correct?

Also, where do we want this information to be displayed exactly?
