### ISSUE TITLE
srcdocs page does not include anchor tags caveat

### ISSUE THREAD

**Issue by LucasBersier** [mdn/content#27630]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/srcdoc

### What specific section or headline is this issue about?

General

### What information was incorrect, unhelpful, or incomplete?

Using an iframe with a srcdoc that includes an anchor tag, such as:

```html
<iframe srcdoc="<html><a href='#tag'>go to tag</a><h1 id='tag'>Tag</h1></html>"></iframe>
```

Will not work, as the anchor tag should start with `about:srcdoc`

### What did you expect to see?

Should give some info or warning that if one chooses to use srcdoc, they would need to use another method of rendering anchor links. Using simply `#tag` will redirect the whole iframe to another location, (and likely have a XSS error)

```html
<iframe srcdoc="<html><a href='about:srcdoc#tag'>go to tag</a><h1 id='tag'>Tag</h1></html>"></iframe>
```

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/questions/42475012/how-to-make-href-anchors-in-iframe-srcdoc-actually-work

https://en.wikipedia.org/wiki/About_URI_scheme#Standardization

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmliframeelement/srcdoc`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/srcdoc
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmliframeelement/srcdoc/index.md
* Last commit: https://github.com/mdn/content/commit/a3d9f61a8990ba7b53bda9748d1f26a9e9810b18
* Document last modified: 2023-04-07T00:39:15.000Z

</details>

**Comment by Josh-Cena** [comment]
This should be added to the [`<iframe>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) HTML documentation.
