### ISSUE TITLE
Issue with "Demos of open web technologies": (Old links)

### ISSUE THREAD

**Issue by h1z1** [mdn/content#2764]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Demos_of_open_web_technologies

#### What information was incorrect, unhelpful, or incomplete?

Many of the links are either outdated, insecure (no SSL), or have SSL related errors (self-signed certs, etc).  

Examples:

http://www.double.co.nz/video_test/video.svg

Redirects to blushcoder.co.nz

blushicoder.nz appears to have been reorganized as the URL is not /video_test/ rather by date.

ex 

https://bluishcoder.co.nz/./tags/video/index.html

Even then in this case it's unclear where the original link is.

#### Specific section or headline?

No idea what "headline" refers to.  

#### What did you expect to see?
Updated / correct links

#### Did you test this? If so, how?

Clicked on random links in Firefox.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/demos_of_open_web_technologies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Demos_of_open_web_technologies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/demos_of_open_web_technologies/index.html
* Last commit: https://github.com/mdn/content/commit/6ea40ef768005776b5e95c8c29d092133b0af692
* Document last modified: 2020-12-29T13:09:26.000Z

</details>

**Comment by chrisdavidmills** [comment]
To whoever fixes this — my first instinct was to just say "delete this", as it is a maintenance burden. But then I checked the GA rtaffic, and we actually get quite a lot of traffic to this page. It would perhaps be better to run through all the demos and delete the links that no longer work, and then in topic areas that don't have many demos, look for a few links (say about 3-5 per topic area) to add in.

I'd recommend looking at including demo links from API reference pages and MDN demo repos, which are likely to go out of date less frquently.

 For example, for Web Audio API, start by looking at these pages:

* https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API
* https://github.com/mdn/webaudio-examples/

**Comment by Blakelist7** [comment]
Hey, @Ryuno-Ki could you specific which topics need to be deleted/updated? So that topics that have very less or not at all traffic can be removed from here.

**Comment by Ryuno-Ki** [comment]
I don't have access to analytics, but @peterbe does as far as I know. (Chris left the company a few weeks ago so likely cannot look them up either).

**Comment by Blakelist7** [comment]
Hey, @peterbe can you help us here?

**Comment by peterbe** [comment]
We don't publish pageview numbers. But we do publish a normalized comparison we call "popularity".
https://raw.githubusercontent.com/mdn/content/main/files/popularities.json 
It's primarily used to be able to say "this page is more popular than that page" without getting into specific numbers. 
But you can nevertheless use it if you want to find out if a page is popular or not based on a judgment of the number. 

As you can see `/en-US/docs/Web/Demos_of_open_web_technologies`  appears quite high up in that file.

**Comment by peterbe** [comment]
But most importantly, as Chris suggested, let's focus on getting rid of really bad external links on https://developer.mozilla.org/en-US/docs/Web/Demos_of_open_web_technologies

**Comment by Blakelist7** [comment]
I don't know why I am a bit confused here, but please help me understand. Let's take `Web Audio API` for instance. We have to check all the examples that are under it and replace them with some other examples like let's take one to be <a href="https://mdn.github.io/webaudio-examples/audiocontext-states/">AudioContext states demo</a>
right?
