### ISSUE TITLE
Tutorial is missing a step & has dead link

### ISSUE THREAD

**Issue by hi-squeaky** [mdn/content#27649]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started

### What specific section or headline is this issue about?

Active learning: Adding some features to an HTML document

### What information was incorrect, unhelpful, or incomplete?

In the section titled "Active learning: Adding some features to an HTML document" there is this instruction to be read:

```
Just below the opening tag of the [<body>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body) element, add a main title for the document. This should be wrapped inside an <h1> opening tag and </h1> closing tag.
    Edit the paragraph content to include text about a topic that you find interesting.
    Make important words stand out in bold by wrapping them inside a <strong> opening tag and </strong> closing tag.
    Add a link to your paragraph, as [explained earlier in the article](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#active_learning_adding_attributes_to_an_element).
    Add an image to your document. Place it below the paragraph, as [explained earlier in the article](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#empty_elements). Earn bonus points if you manage to link to a different image (either locally on your computer, or somewhere else on the web).
```

I was following the steps in this article, and as there was no earlier mentioning of adding an image to the HTML code. I clicked on the link to see where I had missed that part, but the URL or anchor point that the link refers to does not seem to exist:

_Add an image to your document. Place it below the paragraph, as [explained earlier in the article](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#empty_elements). Earn bonus points if you manage to link to a different image (either locally on your computer, or somewhere else on the web)._

Plus the title "Adding some features to _an_ HTML document" is incorrect I think? English is not my native language.

### What did you expect to see?

Omitting the part about adding an image would make the most sense.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/getting_started/index.md
* Last commit: https://github.com/mdn/content/commit/1a6750e8c67def29c053b507a80a5ec0e751c307
* Document last modified: 2023-06-12T15:49:46.000Z

</details>

**Comment by CBID2** [comment]
I can do it
