### ISSUE TITLE
`tabs.TabStatus` get `undefined`

### ISSUE THREAD

**Issue by uiolee** [mdn/content#27640]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/TabStatus

### What information was incorrect, unhelpful, or incomplete?

`tabs.TabStatus` was incorrect.

`tabs` object has not `TabStatus` key, but has `status` key.

### What did you expect to see?

`tabs.TabStatus`. expect to get a normal return, but get `undefined`.

### Do you have anything more you want to share?

```javascripts
browser.tabs.query({ active: true, currentWindow: true }).then((tabs) => {
  console.log(Object.keys(tabs[0]));
});

```

`tabs` object has not `TabStatus` key, but has `status` key.

```javascripts
["id",
"index",
"windowId",
"highlighted",
"active",
"attention",
"pinned",
"status",
"hidden",
"discarded",
"incognito",
"width",
"height",
"lastAccessed",
"audible",
"mutedInfo",
"isArticle",
"isInReaderMode",
"sharingState",
"successorTabId",
"cookieStoreId",
"url",
"title",
"favIconUrl"]
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/tabs/tabstatus`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/TabStatus
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/tabs/tabstatus/index.md
* Last commit: https://github.com/mdn/content/commit/d6856a051d0ba078ec1d24b80908b1ca174917db
* Document last modified: 2023-03-07T05:27:34.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! `tabs.TabStatus` is a _type_, not a _property_. To check the property name, you need to go to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab. It's not ideal that here `status` is typed as "Either loading or complete", without referring to `tabs.TabStatus`, but there's nothing wrong here.

**Comment by uiolee** [comment]
Thanks.
I misread.
