### ISSUE TITLE
Page says "Structured clone algorithm" is used for runtime.Port.postMessage towards native app, but not true for sending ArrayBuffer

### ISSUE THREAD

**Issue by rrika** [mdn/content#27665]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities

### What specific section or headline is this issue about?

Data cloning algorithm

### What information was incorrect, unhelpful, or incomplete?

runtime.Port.postMessage is described to use the "Structured clone algorithm" which according to https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm does support ArrayBuffer objects. However, any attempt to send an ArrayBuffer to a native app results in the arrival of {}, so there must be limitations not documented.

### What did you expect to see?

Description of limitations of what can be sent to a native app

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/chrome_incompatibilities`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
* Last commit: https://github.com/mdn/content/commit/d86e14de2e66319fc0a0ec0539a05400dea5a453
* Document last modified: 2023-03-07T05:20:12.000Z

</details>

**Comment by hamishwillee** [comment]
Actually, it says here https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#data_cloning_algorithm that different algorithms are used on different browsers.

I assume you are using Firefox? What version?

The list in https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm reflects what works in web APIs/workers. There might be specific exceptions for extensions. 
@rebloor - do you know who would know?

**Comment by rrika** [comment]
I'm using Firefox version 111.0.1 on Linux (a bit outdated, March 14)

**Comment by rebloor** [comment]
@Rob--W @rpl can you offer any insight here?

**Comment by Rob--W** [comment]
Native Messaging only supports JSON-serialized messages: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging#exchanging_messages

If you have reasons for non-JSON messages, file a feature request in the WECG with the use case.
