### ISSUE TITLE
Missing properties on PushSubscription#toJSON

### ISSUE THREAD

**Issue by alii** [mdn/content#27676]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/toJSON

### What information was incorrect, unhelpful, or incomplete?

There are properties that are missing in this documentation. For example `.expirationTime` and `.keys` will exist on the toJSON method in Chrome, but are not documented here.

### What did you expect to see?

A list of all properties that this method returns.

### Do you have any supporting links, references, or citations?

TypeScript says that this is the returned object (from lib.dom.d.ts):
```ts
type EpochTimeStamp = number;

// ...

interface PushSubscriptionJSON {
    endpoint?: string;
    expirationTime?: EpochTimeStamp | null;
    keys?: Record<string, string>;
}
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/pushsubscription/tojson`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/toJSON
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/pushsubscription/tojson/index.md
* Last commit: https://github.com/mdn/content/commit/c58e8c1dd6ecbcb63894c7dd17fb9495b9511b4e
* Document last modified: 2023-04-07T19:46:21.000Z

</details>
```[tasklist]
### Tasks
```

**Comment by heybereket** [comment]
Definitely agree. I can take a look at this when I get some time. Seems pretty interesting. Thanks, alistair!

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/29397
