### ISSUE TITLE
Mention of the synchronous Nature of Web storage

### ISSUE THREAD

**Issue by Biki-das** [mdn/content#27686]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#basic_concepts

### What information was incorrect, unhelpful, or incomplete?

The web Storage API methods are synchronous in Nature and a mention about it is important, as reading the Data from local Storage or even writing to it may take time and as it is synchronous it can affect the performance as the main thread operations would be consumed by it.

### What did you expect to see?

Few lines explaining the synchronous Nature of The Web Storage w

### Do you have any supporting links, references, or citations?

https://web.dev/storage-for-the-web/

clearly states in the localStorage section about it's synchronous Nature

**Comment by Biki-das** [comment]
@Josh-Cena i can work on it! could you assign me

**Comment by Josh-Cena** [comment]
No need to be assigned; you can just go ahead and send the PR.
