### ISSUE TITLE
<easing-functions> page has "step()" not "steps()" 4 times in .png file

### ISSUE THREAD

**Issue by sidewayss** [mdn/content#27695]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function

### What specific section or headline is this issue about?

Step Easing Function

### What information was incorrect, unhelpful, or incomplete?

Incorrect function name, step() not steps() e.g. step(2, jump-start).  There are four of them in this .png.  I too am befuddled by the fact that it's a "step function" but it's named "steps".  Even the heading calls it the "Step easing function".  Regardless, that's the way it is, so this .png, the one with 4 diagrams, is wrong.  I would fix it myself and create a PR, but I am not good with non-SVG graphics (non-text-specified graphics) and I don't see the source for this .png file in content\files\en-us\web\css\easing-function.  The .png files there look different than the ones in the docs page online.

### What did you expect to see?

steps(2, jump-start)    steps(4, jump-end)
steps(5, jump-none)    steps(3, jump-both)

### Do you have anything more you want to share?

![image](https://github.com/mdn/content/assets/15235202/a9d6decd-9003-414f-b088-f0a293847bab)

**Comment by yarusome** [comment]
Good catch! I just corrected my mistakes in the PR.

**Comment by sidewayss** [comment]
If you're working on this now you might want to indicate the default jump value for `steps()`.  I believe it's `end` aka `jump-end`, but I didn't get that from this page or this one, which also describes `steps()`: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function

**Comment by sidewayss** [comment]
You might also note that in the same way that `jump-both` effectively adds a step, `jump-none`  effectively subtracts a step.  That's farther up on the page.
