### ISSUE TITLE
HTML/CSS parser and interactive tool

### ISSUE THREAD

**Issue by 1der1** [mdn/content#27701]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Demos

### What information was incorrect, unhelpful, or incomplete?

A tool to parse and interactively edit CSS would be very helpful.

### What did you expect to see?

The free website editor at 1der1.com can parse HTML/CSS. Then you can interactively edit.

### Do you have any supporting links, references, or citations?

The free website editor can parse HTML/CSS. Then you can interactively edit.
Examples:
https://1der1.com/blogs/news

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/demos`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Demos
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/demos/index.md
* Last commit: https://github.com/mdn/content/commit/4ee1eab3843582647f22a18f1b642813940a52cb
* Document last modified: 2023-03-14T04:11:48.000Z

</details>

**Comment by Josh-Cena** [comment]
We now have https://developer.mozilla.org/en-US/play, which should satisfy this need :)
