### ISSUE TITLE
Please clarify that map() *can* modify the original object properties in an array of objects

### ISSUE THREAD

**Issue by digeomel** [mdn/content#27713]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

### What information was incorrect, unhelpful, or incomplete?

I just spent some time trying to explain to a *senior* developer that he was using `map()` the wrong way.
He had written `map()` on its own, without an assignment or even a return statement, on an array of objects, modifying each object in it, and it worked, exactly like `forEach()`. IMHO this is bad practice and a side-effect that is very confusing.

### What did you expect to see?

I expect to see a clear warning that `map()` *can* modify object properties in the *original* array, if it's iterating over an array of objects and not primitive types, **but this should be discouraged**.

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/questions/35922429/why-does-a-js-map-on-an-array-modify-the-original-array

https://dev.to/lofiandcode/can-map-mutate-the-original-array-yes-dmb

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/map`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/map/index.md
* Last commit: https://github.com/mdn/content/commit/59c445ffa5b31083d0f54ba3ee5788b17b8b8329
* Document last modified: 2023-06-27T12:49:23.000Z

</details>

**Comment by digeomel** [comment]
@Josh-Cena  I have struggled to find this sentence and only now that you wrote it I managed to find it. IMHO, and as supported by the links that I attached, this is not clear to all developers. It should be placed in a warning message, just like the one above it about concurrent modifications.
I also think an example with object property manipulations would clarify better.

**Comment by postmeback** [comment]
If an object destructuring example is required for `map`, then the below mentioned code can be considered

````js
const freeProduct = function(products) {
  return products.map(x => {
    return {
      ...x,
      productType: "free"
    };
  });
};
````

**Comment by Josh-Cena** [comment]
We should generally avoid callouts. The warning is there because the behavior relies on some arbitrary internal implementation detail of how the array is traversed. As for your case, the code may be confusing and/or non-idiomatic, but it doesn't generate potentially non-deterministic behavior, so a separate paragraph should suffice. But I think an example could be worthwhile.

**Comment by digeomel** [comment]
@postmeback this has nothing to do with object destructuring. This is only about the anti-pattern of using `map()` like this:

```javascript
function returnModifiedArray(originalArrayOfObjects) {
    originalArrayOfObjects.map((obj) => {
        obj.someProp = modifyProp(obj.someProp);
    });
    return originalArrayOfObjects;
}
```
