### ISSUE TITLE
Incomplete information on page - Packet Management Basics on MDN 

### ISSUE THREAD

**Issue by effaf** [mdn/content#27729]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management

### What specific section or headline is this issue about?

Having fun with Parcel

### What information was incorrect, unhelpful, or incomplete?

I followed all the instructions and include 'parcel' as a dependency in my project. Post this I tried making changes in my index.html file but they did not appear live (I added a <p> element in my index.html). I ignored it and proceed further. Copied the contents mentioned in the guide to my index.js (Date dependency). When I refreshed my html, I could not see the changes live. I then added a <script> tag to my html, and it then installed the dependency automatically.

I think the guide overlook the instruction of connecting the index.html to index.js using the script tag. I am a beginner, and I might be wrong. Please let me know if I am thinking right. 

P.S. - My file names are index.html and index.js. It still did not work. (If that might be one of the reasons).  

### What did you expect to see?

I expected to see an instruction asking to connect index.html to index.js using the script element in the html file. 

### Do you have anything more you want to share?

I am a novice and I might be wrong. I think parcel dependency should handle it, but I guess it did not. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/package_management`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
* Last commit: https://github.com/mdn/content/commit/ba1f12d2b57a1ea352fb870c944d78ae134b95cc
* Document last modified: 2023-05-08T15:27:45.000Z

</details>

**Comment by Josh-Cena** [comment]
The `index.html` file, when it was first introduced, contains this:

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>My test page</title>
  </head>
  <body>
    <script src="./index.js"></script>
  </body>
</html>
```

Does yours look the same?

**Comment by effaf** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>First Parcel Node App</title>
</head>
<body>
    <h1>Wassup my g's</h1>
</body>
</html>

Not the same. My index.html looks a bit different. I added a few tags (h1,p).

**Comment by Josh-Cena** [comment]
Yes, you would need to follow the tutorial—the very beginning tells you you need the `<script src="./index.js"></script>`.

**Comment by effaf** [comment]
Okay, I did not copy and paste the code. My bad. Thank you for the clarification!
