### ISSUE TITLE
table-layout: Cells in subsequent rows *do* affect column widths.

### ISSUE THREAD

**Issue by howardRaul1** [mdn/content#27728]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout

### What specific section or headline is this issue about?

"Values" Section

### What information was incorrect, unhelpful, or incomplete?

Documentation stated:
 "Cells in subsequent rows do not affect column widths." 

But they do.

### What did you expect to see?

Cells in subsequent rows *do* affect column widths.

### Do you have any supporting links, references, or citations?

Two JsFiddle exaxmples:

https://jsfiddle.net/emmaJsFiddle/1wz3s6ob/3/
https://jsfiddle.net/emmaJsFiddle/6jontbyx/1/

**Comment by OnkarRuikar** [comment]
If you don't set width on table then the fixed layout is not used, instead automatic layout algorithm is used:

> The table’s width may be specified explicitly with the [width](https://drafts.csswg.org/css2/#propdef-width) property. A value of [auto](https://drafts.csswg.org/css2/#valdef-width-auto) (for both 'display: table' and 'display: inline-table') means use the [automatic table layout](https://drafts.csswg.org/css2/#auto-table-layout) algorithm. [[ref]](https://drafts.csswg.org/css2/#fixed-table-layout)

Demo: https://jsfiddle.net/xqoLh9c0/

**Comment by howardRaul1** [comment]
> 

Hi @OnkarRuikar ,

Thanks for the spec reference.

I think the typo here is this part:

    " or by the width of the first row of cells"

Cells in subsequent rows *do* affect column widths, even if the first row of cells has a fixed width.  The sentence above should be removed.

https://jsfiddle.net/f7te2Ls3/

If we need to assign an explicit width to &lt;table> to keep the table in "fixed" mode, then this is a key fact that should be stated in the MDN docs.

**Comment by howardRaul1** [comment]
> > Cells in subsequent rows do affect column widths, even if the first row of cells has a fixed width. The sentence above should be removed.
> > [jsfiddle.net/f7te2Ls3](https://jsfiddle.net/f7te2Ls3/)
> 
> Your example has tow flaws:
> 
> 1. First, it still doesn't assign fix width to the table, so it keeps using the auto layout algorithm.
> 2. Lets assume we've given the table `width: 100px`. The selector ` tr:first-child td` selects **both** the cells in the first row. So they both get explicit width of 1px. As per following line in the specification the remaining space(table width - 2px) is equally divided among the columns so both columns get equal width(50px).
> 
> > If the table is wider than the columns, the extra space should be distributed over the columns.
> 
> Here is a demo correcting your example step by step: https://jsfiddle.net/wLd3y7p1/1/
> 
> > If we need to assign an explicit width to `<table>` to keep the table in "fixed" mode, then this is a key fact that should be stated in the MDN docs.
> 
> This is being addressed in #27736

Hi @OnkarRuikar ,

The documentation did not make "assigning a fix width to the table" a mandatory prerequisite for "Cells in subsequent rows do not affect column widths.".

The way the documentation is written right now, it is saying that there are two potential prerequisites for the final condition.  Either prerequisite will trigger the final condition (meaning that we don't need both prerequisites to be true).

Potential Prerequisites:
1) Table and column widths are set by the widths of table and col elements
2) Table and column widths are set by the width of the first row of cells.

Final Condition:
*  Cells in subsequent rows do not affect column widths.

____________________________________________________________
Please review, thanks.

**Comment by OnkarRuikar** [comment]
> The documentation did not make "assigning a fix width to the table" a mandatory prerequisite

Yes, that information was missing from the page. And the PR https://github.com/mdn/content/pull/27736/files is trying to add that information to the document.
