### ISSUE TITLE
[CSS] (motion-1) Support `<basic-shape> || <coord-box>` for `offset-path`

### ISSUE THREAD

**Issue by bsmth** [mdn/content#27747]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- NA - Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

- https://bugzilla.mozilla.org/show_bug.cgi?id=1598156
- https://bugzilla.mozilla.org/show_bug.cgi?id=1837305

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by dipikabh** [comment]
Tasks for update docs related to this feature update:

- [ ] Content
    - [ ] [offset-path](https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path) page
    - [ ] Check other related pages ([Basic shapes](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_shapes/Basic_shapes))
- [ ] [offset-path in mdn/data](https://github.com/mdn/data/blob/main/css/properties.json#LL7264): 
    - update syntax
    - update `animationType`
- [ ] Release notes
- [ ] BCD

**Comment by bsmth** [comment]
Everything looks completed, so I'm closing as done now, thanks Dipika 🙌🏻
