### ISSUE TITLE
GeneratorFunction.prototype.prototype is misleading/incorrect

### ISSUE THREAD

**Issue by mdsaifullah365** [mdn/content#27740]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator

### What specific section or headline is this issue about?

Constructor

### What information was incorrect, unhelpful, or incomplete?

In the mentioned section, it says, _"In fact, there's no JavaScript entity that corresponds to the Generator constructor. There's only a hidden object which is the prototype object shared by all objects created by generator functions. This object is often stylized as Generator.prototype to make it look like a class, but it should be more appropriately called [GeneratorFunction.prototype.prototype](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction), because GeneratorFunction is an actual JavaScript entity."

But in reality GeneratorFunction.prototype.prototype returns undefined. The correct ways to access Generator.prototype are:
1. GeneratorFunction.prorotype.__proto__ (not recommended) 
2. generatorObject.__proto__.__proto__ (not recommended)
3. Object.getPrototypeOf(GeneratorFunction.prorotype); (recommended) 

In summary, if we consider GeneratorFunction.prototype.prototype as a pseudo code, then its okay. But it may arise confusions sometimes. 

### What did you expect to see?

In fact, there's no JavaScript entity that corresponds to the Generator constructor. There's only a hidden object which is the prototype object shared by all objects created by generator functions. This object is often stylized as Generator.prototype to make it look like a class, but it should be more appropriately called [Object.getProrotypeOf(GeneratorFunction.prototype)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction), because GeneratorFunction is an actual JavaScript entity.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/generator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/generator/index.md
* Last commit: https://github.com/mdn/content/commit/ef30b142b03870b8ca70919f1a65a96736898c3a
* Document last modified: 2023-06-18T23:55:42.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! It's mentioned at the very beginning of this page that `GeneratorFunction` is not a global.

> Note that GeneratorFunction is not a global object. It can be obtained with the following code:
>
> ```js
> const GeneratorFunction = function* () {}.constructor;
> ```

Try this:

<img width="855" alt="image" src="https://github.com/mdn/content/assets/55398995/2032de77-aa67-4b5f-ac56-cec942e9ce54">

`GeneratorFunction.prototype.prototype` is indeed `generatorObject.__proto__.__proto__`, but it's not `GeneratorFunction.prototype.__proto__`—the latter is `Iterator.prototype`. I have made a diagram that you can view in https://github.com/orgs/mdn/discussions/358, but due to that discussion, I cannot send a PR. It is in my [TODO list](https://github.com/mdn/content/issues/26847) to make all of this more explicit, though.

**Comment by mdsaifullah365** [comment]
Thanks for clarifying. I thought `GeneratorFunction` is referred as a real generator function instance. But you mention that it is actually referred as `function* ( ) { }.constructor`. In that case, it is perfectly correct. Thanks again.
