### ISSUE TITLE
[JS]  Enable NumberFormat v3

### ISSUE THREAD

**Issue by bsmth** [mdn/content#27746]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

- https://bugzilla.mozilla.org/show_bug.cgi?id=1795756

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by Elchi3** [comment]
Would be great to get a review on https://github.com/mdn/browser-compat-data/pull/20262

**Comment by hamishwillee** [comment]
I'm still checking the status of this. But minimally
- [`PluralRules` constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules)
  - These probably : [[MinimumIntegerDigits]], [[MinimumFractionDigits]], [[MaximumFractionDigits]], [[MinimumSignificantDigits]], [[MaximumSignificantDigits]], [[RoundingType]],
  - These in the new proposal and no docs, maybe no BCD [[RoundingMode]], [[RoundingIncrement]], [[TrailingZeroDisplay]] 
  - [`PluralRules.resolvedOptions()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/resolvedOptions) this takes some of the new options. Might have a BCD option.
  - [`PluralRules.selectRange()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/selectRange) - new and documented. But need to sanity check. Perhaps with live example or interactive example: 
  
Intl docs seem pretty complete but have some experimental markup that needs to be checked- removed - such as `negative` in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#signdisplay
