### ISSUE TITLE
[API] Enable `fontBoundingBox{Ascent|Descent}` attributes in canvas `TextMetrics`

### ISSUE THREAD

**Issue by bsmth** [mdn/content#27758]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

```diff
 - name: dom.textMetrics.fontBoundingBox.enabled
   type: RelaxedAtomicBool
-  value: false
+  value: true
   mirror: always
```

Example [wpt](https://hg.mozilla.org/mozilla-central/file/16840df74cb464240b2097b0eff2bdf163498154/testing/web-platform/tests/html/canvas/element/drawing-text-to-the-canvas/2d.text.measure.fontBoundingBox.html):

<details>

```html
<script>
var t = async_test("Testing fontBoundingBox");
_addTest(function(canvas, ctx) {

  deferTest();
  var f = new FontFace("CanvasTest", "/fonts/CanvasTest.ttf");
  document.fonts.add(f);
  document.fonts.ready.then(() => {
      step_timeout(t.step_func_done(function () {
          ctx.font = '50px CanvasTest';
          ctx.direction = 'ltr';
          ctx.align = 'left'
          // approx_equals because font metrics may be rounded slightly differently by different platforms/browsers.
          assert_approx_equals(ctx.measureText('A').fontBoundingBoxAscent, 50 * 1745 / 1024, 1, "unexpected fontBoundingBoxAscent");
          assert_approx_equals(ctx.measureText('A').fontBoundingBoxDescent, 50 * 805 / 1024, 1, "unexpected fontBoundingBoxDescent");

          assert_approx_equals(ctx.measureText('ABCD').fontBoundingBoxAscent, 50 * 1745 / 1024, 1, "unexpected fontBoundingBoxAscent");
          assert_approx_equals(ctx.measureText('ABCD').fontBoundingBoxDescent, 50 * 805 / 1024, 1, "unexpected fontBoundingBoxDescent");
      }), 500);
  });

});
</script>
```

</details>

## Related Gecko bugs

- https://bugzilla.mozilla.org/show_bug.cgi?id=1801198

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/20357
- [ ] Docs
- [ ] Release note
- [ ] dev-doc-complete

**Comment by bsmth** [comment]
Closing as done now, ty 👍🏻
