### ISSUE TITLE
No mention of CSPs frame-ancestors.

### ISSUE THREAD

**Issue by simon-friedberger** [mdn/content#27754]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

### What specific section or headline is this issue about?

See also

### What information was incorrect, unhelpful, or incomplete?

This should mention CSP and frame-ancestors because that is, usually, necessary for using this feature correctly.

### What did you expect to see?

A link to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/iframe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/iframe/index.md
* Last commit: https://github.com/mdn/content/commit/e04d8d2766c468f149445c0bf438d09f9b2d188c
* Document last modified: 2023-06-13T08:10:47.000Z

</details>

**Comment by hamishwillee** [comment]
@simon-friedberger Thanks. Would you like to create a PR?
