### ISSUE TITLE
Issue with "<input type="text">": Misleading info on id attribute in HTML form

### ISSUE THREAD

**Issue by golemarms** [mdn/content#2776]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text

#### What information was incorrect, unhelpful, or incomplete?
HTML form example implies that that `id` attribute, rather than `name` attribute will be sent to the server as data key

#### Specific section or headline?
[Basic Example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#basic_example)

```
<form>
  <div>
    <label for="uname">Choose a username: </label>
    <input type="text" id="uname" name="name">
  </div>
  <div>
    <button>Submit</button>
  </div>
</form>
```

When submitted, the data name/value pair sent to the server will be `uname=Chris` (if "Chris" was entered as the input value before submission)

#### What did you expect to see?
When submitted, the data name/value pair sent to the server will be `name=Chris` (if "Chris" was entered as the input value before submission)

#### Did you test this? If so, how?
Cross-checked this against the [corresponding section](https://developer.mozilla.org/en-US/docs/Learn/Forms/Your_first_form#sending_form_data_to_your_web_server) from the mdn forms tutorial

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/text/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by chrisdavidmills** [comment]
Yes, this is a typo and should be fixed. Thanks for reporting this @golemarms !
