### ISSUE TITLE
only supported in firefox

### ISSUE THREAD

**Issue by SkinnyKenneth** [mdn/content#27761]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Location/reload

### What specific section or headline is this issue about?

parameters

### What information was incorrect, unhelpful, or incomplete?

it states that it is only supported in firefox, but according to caniuse it is supported on all browsers.

![Skjermbilde 2023-07-04 155608](https://github.com/mdn/content/assets/134853391/f55d0eb4-332f-441d-a6ad-c467db03400b)

![Skjermbilde 2023-07-04 155936](https://github.com/mdn/content/assets/134853391/8102c10e-7273-42f2-b2e7-03d5a1607496)

### What did you expect to see?

updated information

### Do you have any supporting links, references, or citations?

![Skjermbilde 2023-07-04 155936](https://github.com/mdn/content/assets/134853391/159e3c13-dff1-48bf-9a36-0db645ab95a2)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/location/reload`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Location/reload
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/location/reload/index.md
* Last commit: https://github.com/mdn/content/commit/0ffa1eef854b3815efa60f3cdf07a756f1506614
* Document last modified: 2023-05-22T15:14:13.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, the Firefox-only feature is the `forceGet` parameter, not the entire function.

The caniuse data for this comes _from_ MDN (browser-compat-data), so there's no point to be proven here :)
