### ISSUE TITLE
"auto" description is incorrect, for minmax()

### ISSUE THREAD

**Issue by howardRaul1** [mdn/content#27767]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/minmax

### What specific section or headline is this issue about?

"Values" Section

### What information was incorrect, unhelpful, or incomplete?

For the "auto" keyword, the first sentence is incorrect:

"As a maximum, identical to max-content".

### What did you expect to see?

- auto, as a maximum, is ***not*** identical to max-content.

### Do you have any supporting links, references, or citations?

https://jsfiddle.net/emmaJsFiddle/ju4myqz7/

**Comment by OnkarRuikar** [comment]
It's not incorrect, it's just that some key information is missing:
> `auto`
As a maximum: represents the largest [max-content contribution](https://drafts.csswg.org/css-sizing-3/#max-content-contribution) of the [grid items](https://drafts.csswg.org/css-grid/#grid-item) occupying the [grid track](https://drafts.csswg.org/css-grid/#grid-track); however, unlike [max-content](https://drafts.csswg.org/css-grid/#valdef-grid-template-columns-max-content), _**allows expansion of the track by the [align-content](https://drafts.csswg.org/css-align-3/#propdef-align-content) and [justify-content](https://drafts.csswg.org/css-align-3/#propdef-justify-content) properties.**_
> spec [[ref]](https://drafts.csswg.org/css-grid/#valdef-grid-template-columns-auto)

By default `justify-content` has value `normal` which is equivalent to `stretch`: it stretches the elements. [[ref]](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#normal). That is why the `auto` in minmax takes maximum allowed value in the cell.

Your demo with `justify-content: start` set: https://jsfiddle.net/wgpdm9fe/
