### ISSUE TITLE
missing pattern.png

### ISSUE THREAD

**Issue by rokam48** [mdn/content#27774]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page

### What specific section or headline is this issue about?

Starting Point

### What information was incorrect, unhelpful, or incomplete?

The pattern.png file is not loading. Thus I am unable to download it as well. Whenever I try to save it via the right-click menu, it saves a file with .htm extension. 

### What did you expect to see?

A pattern.png file for me to save and use.

### Do you have any supporting links, references, or citations?

https://github.com/mdn/learning-area/blob/main/html/multimedia-and-embedding/mdn-splash-page-start/pattern.png

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/mozilla_splash_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/mozilla_splash_page/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>

**Comment by Josh-Cena** [comment]
<img width="1114" alt="Screenshot 2023-07-05 at 18 51 45" src="https://github.com/mdn/content/assets/55398995/df34a34a-c5ab-4cab-9558-b97455c583a5">

**Comment by rokam48** [comment]
Clicking on 'Download raw file' is not working for me either. In fact, I'm unable to download images in the 'originals' directory too.

**Comment by rokam48** [comment]
I found the problem. It's my network. I use Jio network, and it has decided to block raw.githubusercontent.com. I switched to a different network and now it loads the file.
