### ISSUE TITLE
Note in IndexedDB API page that directs users to libraries in See Also section no longer relevant

### ISSUE THREAD

**Issue by chunkily** [mdn/content#27788]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

### What specific section or headline is this issue about?

The second note underneath the first paragraph

### What information was incorrect, unhelpful, or incomplete?

The note's contents suggest for programmers to "try libraries in the See also section" that I believe were removed in #27565.

### What did you expect to see?

I expected the note to no longer be there.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/indexeddb_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/indexeddb_api/index.md
* Last commit: https://github.com/mdn/content/commit/66a187ca15aff789cdb6d9860e612eb184667f8b
* Document last modified: 2023-06-28T07:22:17.000Z

</details>

**Comment by hamishwillee** [comment]
Good point thanks - fixed by #27808
