### ISSUE TITLE
AI Help compromises data authenticity

### ISSUE THREAD

**Issue by develleoper** [mdn/content#27799]
### MDN URL

https://developer.mozilla.org/en-US/plus/ai-help/

### What information was incorrect, unhelpful, or incomplete?

"AI" as presented here is merely a language model, does not truly have any actual understanding of its subject material, and cannot guarantee accuracy beyond "this is statistically probable to be an answer, based off word associations in our data set".

For a _reference document_, any potential misinformation is unacceptable and will lead naive devs to misunderstand their own craft.

### What did you expect to see?

No "AI Help" feature.

### Do you have anything more you want to share?

Those responsible for this hastily deployed feature need to remember that there is an actual process already in place around deployments, and bypassing them with unapproved _(and unwanted)_ features compromises MDN's continued role as the industry-respected, authoritative source of truth that it is.

**Comment by Josh-Cena** [comment]
You can join the discussion in https://github.com/mdn/yari/issues/9230. I think most writers are as crossed as you are, but there's little we can do.

**Comment by Be-ing** [comment]
> there's little we can do

You can take the content and code and host it on another domain.
