### ISSUE TITLE
"loadstart" event not linked to from <audio>/<video> pages

### ISSUE THREAD

**Issue by SimonSimCity** [mdn/content#27820]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

### What specific section or headline is this issue about?

Events

### What information was incorrect, unhelpful, or incomplete?

One of the guides (https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Cross-browser_audio_basics#loadstart) mentions an event called `loadstart`.

Because I wanted to get more information about when this event triggers and how I could use it, I went over to the documentation of the element, but couldn't find the event there: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#events

I just checked for the video-element and it seems its missing there as well.

### What did you expect to see?

Some documentation explaining when `loadstart` is fired, or - in case it doesn't exist - remove it from the guide (https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Cross-browser_audio_basics#loadstart).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/audio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/audio/index.md
* Last commit: https://github.com/mdn/content/commit/942a529383ee7ee3996fb234187641c08935f3ff
* Document last modified: 2023-04-13T06:13:15.000Z

</details>

**Comment by Josh-Cena** [comment]
We only need to link to https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadstart_event. You can always use the search if you are unable to find something :)
