### ISSUE TITLE
The example of <Select strong words> button only worked correctly in Firefox

### ISSUE THREAD

**Issue by qibing147147** [mdn/content#27824]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Selection/addRange#examples

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

The `Select strong words` button worked incorrectly in Chrome or Safari.

### What did you expect to see?

Fix the description or make the example work in Chrome and safari.

**Comment by Josh-Cena** [comment]
There's a note at the very top of this example:

> Note: Currently only Firefox supports multiple selection ranges, other browsers will not add new ranges to the selection if it already contains one.

What else do you suggest adding?

**Comment by qibing147147** [comment]
> There's a note at the very top of this example:
> 
> > Note: Currently only Firefox supports multiple selection ranges, other browsers will not add new ranges to the selection if it already contains one.
> 
> What else do you suggest adding?

sorry. I did not notice that.
