### ISSUE TITLE
`required` attribute missing spec link

### ISSUE THREAD

**Issue by estelle** [mdn/content#27849]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required

### What specific section or headline is this issue about?

specification

### What information was incorrect, unhelpful, or incomplete?

missing data

### What did you expect to see?

link to https://html.spec.whatwg.org/multipage/input.html#the-required-attribute

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/required`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/required/index.md
* Last commit: https://github.com/mdn/content/commit/942a529383ee7ee3996fb234187641c08935f3ff
* Document last modified: 2023-04-13T06:13:15.000Z

</details>

**Comment by Josh-Cena** [comment]
I don't know how BCD works for HTML, but since `required` is an attribute shared by `select`, `input`, etc., does that mean we need multiple BCD keys?

**Comment by hamishwillee** [comment]
Yes, there are separate entries in BCD for each `required` associated with different HTML elements. 

@queengooborg Why do you think `html.elements.select.required` is the most appropriate to use? I would have assumed that for common docs for a non-global attribute you'd list all the relevant keys for the applicable HTML elements.

**Comment by queengooborg** [comment]
I did a search and I did not find the `required` attribute documented on any other elements, including in the global attributes list.

**Comment by hamishwillee** [comment]
Lots of hits
![image](https://github.com/mdn/content/assets/5368500/16b60830-fbb2-4828-a417-d2e0711ec2a0)

**Comment by hamishwillee** [comment]
I.e. I'm not arguing whether it is specifically documented on other elements. I'm arguing that this doc does not specify the element, so should have the BCD for all relevant.

**Comment by queengooborg** [comment]
> Lots of hits
> 
> ![image](https://github.com/mdn/content/assets/5368500/16b60830-fbb2-4828-a417-d2e0711ec2a0)
> 
> 

Those entries are ones in the API folder, not the HTML folder.  😛

**Comment by hamishwillee** [comment]
Oh yeah, only two in the HTML.
![image](https://github.com/mdn/content/assets/5368500/4541bc8a-21ef-40a1-b2d1-ce10eb620f38)

Given they mirror, doesn't that mean BCD is missing a lot of data?

**Comment by hamishwillee** [comment]
In other words, it looks like this is a BCD issue (as @Josh-Cena thought) - can we assume mirroring and use the web API keys?

**Comment by queengooborg** [comment]
> Given they mirror, doesn't that mean BCD is missing a lot of data?

By "mirror", do you mean that the data is identical between the API counterparts and the HTML element data?

> can we assume mirroring and use the web API keys?

No, we should not be using the BCD identifiers for the API counterparts of these features.  If anything, adding the missing features to the HTML elements would be the right move for BCD.


> I don't know how BCD works for HTML, but since `required` is an attribute shared by `select`, `input`, etc., does that mean we need multiple BCD keys?

I think that this may be a case where we need to update MDN's documentation to better match what the structure _should_ be in BCD, much like what was done for events.

**Comment by hamishwillee** [comment]
> I think that this may be a case where we need to update MDN's documentation to better match what the structure should be in BCD, much like what was done for events.

I think you are suggesting that, for example, all the Web API and corresponding HTML elements would be done as one entity in docs and in BCD? 

If so, I'm not sure "how" mirrored they are - if not perfectly matched this can't work. I suspect we're talking adding missing items to BCD. Also challenging, but workable.

**Comment by queengooborg** [comment]
No, actually the opposite: separating the attribute.  This is a single page to refer to the attribute on many elements, but it would be better to create pages for each individual element.

**Comment by hamishwillee** [comment]
Hmmm, so 18 new pages and 16-ish new BCD entries. It makes sense, but you can see why it was combined into one page.

**Comment by estelle** [comment]
https://github.com/mdn/content/pull/31856 removed the compat from this page
