### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by uiolee** [mdn/content#27853]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Tips

### What specific section or headline is this issue about?

Using advanced JavaScript features from ECMAScript 2015 and 2016

### What information was incorrect, unhelpful, or incomplete?

a broken link `[supports many features of ECMAScript 2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_6_support_in_Mozilla)`

### What did you expect to see?

accurate content

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/tips`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Tips
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/tips/index.md
* Last commit: https://github.com/mdn/content/commit/d86e14de2e66319fc0a0ec0539a05400dea5a453
* Document last modified: 2023-03-07T05:20:12.000Z

</details>

**Comment by Josh-Cena** [comment]
This entire page looks outdated and unrelated to web extensions. @mdn/yari-content-mozilla-add-ons can we just remove this?

**Comment by Rob--W** [comment]
That entire page can be removed. I came across it before and thought that I took the steps to remove it. Since the page is still obviously online, I guess that my thought stopped at being a thought without action.
