### ISSUE TITLE
Scroll-driven animations: preference name changed

### ISSUE THREAD

**Issue by scheinercc** [mdn/content#27855]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#scroll-driven_animations

### What specific section or headline is this issue about?

Scroll-driven animations

### What information was incorrect, unhelpful, or incomplete?

Preference name says `layout.css.scroll-linked-animations.enabled` but should be `layout.css.scroll-driven-animations.enabled`

### What did you expect to see?

Tested in 117.0a1 (2023-07-09) (64-bit) the preference name is `layout.css.scroll-driven-animations.enabled`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/firefox/experimental_features`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/experimental_features/index.md
* Last commit: https://github.com/mdn/content/commit/50cf3d2facde8370e5d21195fc46aa3ebb173931
* Document last modified: 2023-07-05T09:12:03.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you. Fixed by https://github.com/mdn/content/pull/27868
