### ISSUE TITLE
Little correction for isolation

### ISSUE THREAD

**Issue by gadhdhds** [mdn/content#2788]
https://developer.mozilla.org/en-US/docs/Web/CSS/isolation

Right after the Demo, it says: _This property is especially helpful when used in conjunction with mix-blend-mode._

I would add that it is often used in conjunction with [z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index) too, since it creates a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) which does not interact with the content surrounding it.

This is especially true for the body, which has a default z-index of _auto_ and prevents the user from interacting with elements with a negative z-index if isolation is set to _none_.

See [here](https://coder-coder.com/z-index-isnt-working/) for more information.

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/commit/d55d6fc72a5b1ca3447cb71716ae6f94d7f023d1
