### ISSUE TITLE
Explanation is contradictory to the Code being explained.

### ISSUE THREAD

**Issue by meetanoopverma** [mdn/content#27897]
### MDN URL

https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/object_building_practice/index.md?plain=1#L188-L189

### What specific section or headline is this issue about?

Section: Updating the ball's data

### What information was incorrect, unhelpful, or incomplete?

Line 188 says: (the ball is going off the bottom edge)

### What did you expect to see?

Line 188 should say that (the ball is going off the top edge)

### Do you have any supporting links, references, or citations?

![Screenshot 2023-07-12 162228](https://github.com/mdn/content/assets/94305004/a9d4fcb8-ed93-4236-9b2a-27f3c7fa0cc5)

### Do you have anything more you want to share?

While you correct this Line 188 then Please look into the Line 189 which also require similar modification.

**Comment by Josh-Cena** [comment]
See https://github.com/mdn/content/pull/27898#pullrequestreview-1526210790
