### ISSUE TITLE
Challenge for "Django Tutorial Part 9: Working with forms" is not consistent for BookDelete

### ISSUE THREAD

**Issue by acuglar** [mdn/content#27895]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms#challenge_yourself

### What information was incorrect, unhelpful, or incomplete?

The challenge proposes to replicate the approach taken in Author for Book but in the case of deletion it does not apply because there are BookInstance related to Book, therefore generating RestrictedError exception:

#catalog.models
class BookInstance(models.Model):
     ...
     book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
![image](https://github.com/mdn/content/assets/68908962/b05292a0-f1d7-4e80-a73a-67b57044981d)

### What did you expect to see?

I expected to see some context and suggested approach to the case.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/django/forms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/forms/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by hamishwillee** [comment]
You're right :-(. 

The [worked version of the Django tutorial](https://github.com/mdn/django-locallibrary-tutorial) goes only as far as this challenge - it didn't create or delete bookinstances, so deletion of books that have an associated bookinstance had not been tested. Also not covered in the https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing section.

The Django project does not provide clear advice on this. However the generally accepted answer on the Internet is to either override the post or the delete to catch the error and provide a new view or message in this case. The examples below catch the protected case, but the restricted case would be similar.
- Post - https://www.appsloveworld.com/django/100/94/handle-protect-error-in-django-deleteview
- Delete - https://www.appsloveworld.com/django/100/101/how-to-send-error-message-from-django-deleteview

This would require some implementation, testing and documentation.
