### ISSUE TITLE
Incorrect Instructions on How to Enable Tabbing Using Firefox

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#27900]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility

### What specific section or headline is this issue about?

Using native keyboard accessibility

### What information was incorrect, unhelpful, or incomplete?

The text related to enabling the ability to use the tab key in Firefox for Mac is incorrect.

I searched my machine, and the way to enable them has changed from what is listed below, but I couldn't find how to do it without searching for it. So you might want to update this:

"Firefox for the Mac doesn't do tabbing by default. To turn it on, you have to go to **Preferences > Advanced > General**, then...".

I made the text bold to make it easier to spot.

**NOTE** - The part about "**Mac's System Preferences**" might need updating too. It looks like the instructions for Safari need updating, since the option to check is on the **General** tab instead of the **Advanced** tab.

### What did you expect to see?

I expected the instructions to be up to date.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/cross_browser_testing/accessibility`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/cross_browser_testing/accessibility/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/33419
