### ISSUE TITLE
Explain how to put dialog elements in the top layer

### ISSUE THREAD

**Issue by DanKaplanSES** [mdn/content#27912]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Popover_API

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/Popover_API#concepts_and_usage

### What information was incorrect, unhelpful, or incomplete?

The page says:

> Popovers which are created using the popover API are always non-modal. If you want to create a modal popover, a [\<dialog>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) element is the right way to go, although bear in mind that **\<dialog> elements are not put in the [top layer](https://developer.mozilla.org/en-US/docs/Glossary/Top_layer) by default** — popovers are.

This implies it is possible to put a \<dialog> element in the top layer, but I haven't found anything explaining how to do this. 

On the other hand, I'm wondering if there's a typo here. According to [step 8. in this spec](https://html.spec.whatwg.org/multipage/interactive-elements.html#dom-dialog-showmodal), \<dialog> elements opened with `showModal` _are_ added to the top layer. 

Perhaps this paragraph intended to refer to **non-modal** \<dialog> elements instead of all \<dialog> elements; elements opened with `show` don't have a similar step in the spec. Either way, I'd like to see how to put a \<dialog> element in the top layer when it doesn't start there.

### What did you expect to see?

I expected to see a link to--or an explanation of--how to put a \<dialog> element into the top layer. This information should probably be added to [the \<dialog> element page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog). When I search that page, I don't see the top layer mentioned anywhere.

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/interactive-elements.html#dom-dialog-showmodal

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/popover_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Popover_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/popover_api/index.md
* Last commit: https://github.com/mdn/content/commit/e0d92259b485a219840367cf4e23a7069f192eec
* Document last modified: 2023-07-03T09:21:02.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/31866
