### ISSUE TITLE
Related pages links on WebAssembly pages are broken

### ISSUE THREAD

**Issue by thanatos** [mdn/content#2797]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Instance/Instance

#### What information was incorrect, unhelpful, or incomplete?

On the sidebar, there is a section, "Related pages". All of the links under this section are broken.

![image](https://user-images.githubusercontent.com/90853/109589580-89e5de80-7ad8-11eb-9a70-8c4c2ab6e426.png)

I've used the `WebAssembly.Instance` page as an example, but the "Related pages" links are broken on all of the WebAssembly pages, AFAICT.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/webassembly/instance/instance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Instance/Instance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/webassembly/instance/instance/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment]
I can’t reproduce this. For me, clicking on any of those links navigates me to what I’d expect; for example, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module

What do you get navigated to instead?

**Comment by NegiAkash890** [comment]
Hi , @sideshowbarker ,  I tested  all the above links by clicking and they all are leading to "Page Not Found" page .

**Comment by sideshowbarker** [comment]
> Hi , @sideshowbarker , I tested all the above links by clicking and they all are leading to "Page Not Found" page .

Hi @NegiAkash890 — that’s really odd, because I don’t get a 404 for any of them

Maybe @mdn/core-yari-content may know what might be going on here

**Comment by CreaTorAlexander** [comment]
I tested it in Chrome *Version 87.0.4280.141 (Offizieller Build) (64-Bit)* and it works fine.

**Comment by chrisdavidmills** [comment]
I've tested all the links in Firefox, Chrome, and Safari, and they work fine for me. This is a really strange one.

**Comment by Ryuno-Ki** [comment]
@thanatos Can you share the link you end up on when clicking WebAssembly.Instance?
(Also, does a private window / Incognito mode reproduces this behaviour for you?)

Works for me on Firefox for Linux.

**Comment by sideshowbarker** [comment]
Closing for lack of response
