### ISSUE TITLE
Rust to Wasm Node 20

### ISSUE THREAD

**Issue by akirataguchi115** [mdn/content#27989]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_Wasm

### What specific section or headline is this issue about?

Making our package available to npm

### What information was incorrect, unhelpful, or incomplete?

One of the devDependencies is webpack-cli but after the last suggested command "npm run serve" the terminal outputs the following:
```
> serve
> webpack-dev-server

The command moved into a separate package: @webpack-cli/serve
Would you like to install serve? (That will run npm install -D @webpack-cli/serve) (yes/NO) : n
@webpack-cli/serve needs to be installed in order to run the command.
```

Yes leads to unresolvable dependency errors. No leads to
`@webpack-cli/serve needs to be installed in order to run the command.`

### What did you expect to see?

I expected the HTTP server to run without errors.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/webassembly/rust_to_wasm`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_Wasm
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/rust_to_wasm/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

**Comment by bsmth** [comment]
Hi @akirataguchi115 - thanks for reporting this one. I recently ran through the steps for this tutorial without any issues. I can take another look to be sure, I wonder if it's because of my local setup (I'll need to confirm). In the meantime, would you mind giving some system information, OS, node & npm version?

**Comment by akirataguchi115** [comment]
Hi! Thanks for the reply. MacBook Air M2, Ventura 13.4.1, Node 20.4.0 and npm 9.7.2 .

**Comment by bsmth** [comment]
I ran through this again and this tutorial is targeting node 16:

```bash
nvm use 16
Now using node v16.19.0 (npm v8.19.3)
npm install
npm run serve

...

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /

...

    + 36 hidden modules
ℹ ｢wdm｣: Compiled successfully.
```

I added this caveat here: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_Wasm#install_node.js_and_npm

But we should make some updates to make this compatible with 20, ideally

**Comment by bsmth** [comment]
OK I got this to run with the following config:

```bash
which node
... nvm/versions/node/v20.4.0/bin/node
```

package.json:

```json
{
  "engines": {
    "node": ">=20.0.0"
  },
  "scripts": {
    "start": "webpack-dev-server --config webpack.config.js"
  },
  "dependencies": {
    "hello-wasm": "^0.1.0"
  },
  "devDependencies": {
    "webpack": "^5.88.2",
    "webpack-cli": "^5.1.4",
    "webpack-dev-server": "^4.15.1"
  }
}
```

webpack.config.js:

```js
const path = require("path");
module.exports = {
  entry: "./index.js",
  experiments: {
    asyncWebAssembly: true,
  },
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "index.js",
  },
  mode: "development",
};
```

Running:

```bash
npm start

> start
> webpack-dev-server --config webpack.config.js

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.0.46:8080/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8080/
<i> [webpack-dev-server] Content not from webpack is served from '[redacted]' directory
asset index.js 273 KiB [emitted] (name: main)
asset b3baed19049d00bea52c.module.wasm 17 KiB [emitted] [immutable]
asset pkg_hello_wasm_js.index.js 6.18 KiB [emitted]
runtime modules 33.2 KiB 17 modules
modules by path ./ 178 KiB
  modules by path ./node_modules/webpack-dev-server/client/ 71.8 KiB 16 modules
  modules by path ./node_modules/webpack/hot/*.js 5.3 KiB 4 modules
  modules by path ./node_modules/html-entities/lib/*.js 81.8 KiB
    ./node_modules/html-entities/lib/index.js 7.91 KiB [built] [code generated]
    + 3 modules
  ./index.js 105 bytes [built] [code generated]
  ./node_modules/ansi-html-community/index.js 4.16 KiB [built] [code generated]
  ./node_modules/events/events.js 14.5 KiB [built] [code generated]
modules by path ../pkg/ 2.66 KiB (javascript) 17 KiB (webassembly)
  ../pkg/hello_wasm.js 157 bytes [built] [code generated]
  ../pkg/hello_wasm_bg.js 2.44 KiB [built] [code generated]
  ../pkg/hello_wasm_bg.wasm 60 bytes (javascript) 17 KiB (webassembly) [built] [code generated]
webpack 5.88.2 compiled successfully in 163 ms
^C<i> [webpack-dev-server] Gracefully shutting down. To force exit, press ^C again.
```

Things to get this to work:

1. use latest webpack* versions
2. add `start` script pointing to local webpack config
3. enable `asyncWebAssembly: true,` to webpack config
4. `npm start`

**Comment by akirataguchi115** [comment]
Thanks for the reply, initial workaround and the solution! Should I keep this issue open but change the title to f.ex. "Rust to Wasm Node 20"?

**Comment by bsmth** [comment]
>Thanks for the reply, initial workaround and the solution!

My pleasure 🙌🏻 

>Should I keep this issue open but change the title to f.ex. "Rust to Wasm Node 20"?

Please do, I will open a pull request shortly to update the tutorial. Thanks a lot 👍🏻
