### ISSUE TITLE
Update the new link for JSX in React docs

### ISSUE THREAD

**Issue by meetanoopverma** [mdn/content#27986]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started

### What specific section or headline is this issue about?

How does React use JavaScript?

### What information was incorrect, unhelpful, or incomplete?

At Line 108, To read more about JSX, check out the React team's [JSX In Depth](https://reactjs.org/docs/jsx-in-depth.html) article, the link embedded points to the old docs of the react library. Please replace this old URL with the updated one.

### What did you expect to see?

Replace the old URL with new https://react.dev/learn/writing-markup-with-jsx

### Do you have any supporting links, references, or citations?

![MDN Link Updation](https://github.com/mdn/content/assets/94305004/5fa2ffb3-a53b-4d0d-a91d-b32adc6e6177)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting this one @meetanoopverma - would you like to open a pull request for this one or should I go ahead and change it?

**Comment by bsmth** [comment]
Great, I can review when you're ready 👍

**Comment by meetanoopverma** [comment]
@bsmth I have opened a PR with title **Update the JSX In Depth link inside index.md #27988**
Please review it. Thanks in advance.

**Comment by bsmth** [comment]
Thanks @meetanoopverma for your fix and welcome aboard. If you're looking for other ways to contribute, we have a [contributor task board](https://github.com/orgs/mdn/projects/25). Issues labeled with `good first issue` are a great place to start.

Thank you :)
