### ISSUE TITLE
<slot> missing from Flow content element list

### ISSUE THREAD

**Issue by speedyhoon** [mdn/content#27991]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories

### What specific section or headline is this issue about?

Flow content

### What information was incorrect, unhelpful, or incomplete?

The `<slot>` element is missing from the Flow content list of elements. I noticed it was included in Phrasing content, but not Flow content.

If the `<slot>` element is not meant to be missing in Flow content, then I don't think the Phrasing content should be described as `a subset of Flow content` (under the Phrasing content heading) and the [Venn diagram](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories/content_categories_venn.png) is wrong.

### What did you expect to see?

The `<slot>` element should appear under the `<select>` element within the Flow content section.

### Do you have any supporting links, references, or citations?

No, I didn't look at the docs... 😆  
Either the `<slot>` element is also Flow content, or the [Venn diagram](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories/content_categories_venn.png) is wrong and some Phrasing content is outside of Flow content.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/content_categories`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/content_categories/index.md
* Last commit: https://github.com/mdn/content/commit/c302e71520c9df718363d8ce81d93568ff84be14
* Document last modified: 2023-05-22T12:42:48.000Z

</details>

**Comment by Josh-Cena** [comment]
Yes, it's missing from the list. Here are some others:

- `<bdi>` is phrasing
- `<a>` is interactive only if `href` is present
- `<dialog>` is flow
- `<search>` is flow
- Text is flow

**Comment by ir3ne** [comment]
@Josh-Cena I can `.take` it.
