### ISSUE TITLE
Assess the docs regarding the code style guide

### ISSUE THREAD

**Issue by queengooborg** [mdn/content#27992]
Now that we use Prettier, a lot of our code formatting is now consistent.  With this in mind, a lot of the points that we mention in the code styling guide are now redundant, since Prettier handles them, and more.  It may be good to go through and revise these docs accordingly.

**Comment by bsmth** [comment]
I think this one fixes the issue:

- [x] https://github.com/mdn/content/pull/28017

**Comment by queengooborg** [comment]
Yep, that PR fixed this!
