### ISSUE TITLE
"such as the IP address of the client" -- this part looks wrong

### ISSUE THREAD

**Issue by vakatov** [mdn/content#28015]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host

### What specific section or headline is this issue about?

The overview section of X-Forwarded-Host

### What information was incorrect, unhelpful, or incomplete?

"it exposes privacy sensitive information, such as the IP address of the client. Therefore the user's privacy must be kept in mind when deploying this header."

### What did you expect to see?

"such as the IP address of the client" -- why? This header only exposes the host (name or IP) to which the client is *sending the HTTP request*, not the client host name.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/x-forwarded-host`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/x-forwarded-host/index.md
* Last commit: https://github.com/mdn/content/commit/0880a90f3811475d78bc4b2c344eb4146f25f66c
* Document last modified: 2023-04-10T19:47:15.000Z

</details>

**Comment by sideshowbarker** [comment]
@vakatov Thanks for catching this and reporting it. I’ve raised #28073 with a fix.  After that fix is merged, this issue will automatically be marked as resolved, and closed.

**Comment by vakatov** [comment]
@sideshowbarker -- neat. Thanks!
