### ISSUE TITLE
TS version support

### ISSUE THREAD

**Issue by FlorianBarbet** [mdn/content#28031]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError

### What specific section or headline is this issue about?

browser compatibility

### What information was incorrect, unhelpful, or incomplete?

We've my work-mates we've face to a weird behavior on our IDE. AggregateErrors was available in some projects and unavailable on others (no completion, then build faillure).

![image](https://github.com/mdn/content/assets/28789447/b34a0848-0169-43b4-a628-012f7062e38c)

After an analysis, we've seen that is due to version of Typescript. AggregateErrors seems to be available since es2021. Good news because the projects that not recognized AggregateErrors were in es2020 !

### What did you expect to see?

I expect to see a new column with the TS version compatibility

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/aggregateerror`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/aggregateerror/index.md
* Last commit: https://github.com/mdn/content/commit/6a0f9553932823cd0c4dcf695d4b4813474964fb
* Document last modified: 2023-04-12T16:34:04.000Z

</details>

**Comment by Josh-Cena** [comment]
We don't document TS compatibility because it's not a browser. I guess you mean "ES version". That's tracked in https://github.com/mdn/browser-compat-data/issues/14835.
