### ISSUE TITLE
setter - the word consr is shown instead of const

### ISSUE THREAD

**Issue by charlyrmm92** [mdn/content#28039]
### MDN URL

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Functions/set

### What specific section or headline is this issue about?

definiendo_un_setter_en_un_objecto_existente_usando_defineproperty

### What information was incorrect, unhelpful, or incomplete?

The expression:
consr o = {a: 0};

### What did you expect to see?

I expect to see:
const o = {a: 0};

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set#defining_a_setter_on_existing_objects_using_defineproperty

**Comment by charlyrmm92** [comment]
Fixing here:
https://github.com/charlyrmm92/translated-content/commit/69b6ed9d344bbbee4f83f8ede655a5304581cc9f

**Comment by Graywolf9** [comment]
Hello! @charlyrmm92 this kind of issues should be filled in https://github.com/mdn/translated-content/issues

Thank you so much for your help!
