### ISSUE TITLE
Typo Needs Correcting

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#28060]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Performance

### What specific section or headline is this issue about?

See also

### What information was incorrect, unhelpful, or incomplete?

In the sentence below word "ad" which was made bold to make it easier to spot needs to be changed. I think it should be "**at**" but am not positive.

Here we'll introduce many of these features **ad** the basic level and provide links to deeper dives to improve performance for each topic.

Another sentence with an issue is the one below. 

This helps to improve performance across **difference** devices.

The word "difference" should be "different". I made the text bold so it is easier to spot.

### What did you expect to see?

A non confusing sentence.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/performance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/performance/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting @jfc3-dol - linked a pull request above that fixes these two 👍🏻
