### ISSUE TITLE
Dead link in Command line crash course - Installing Prettier

### ISSUE THREAD

**Issue by devusexu** [mdn/content#28071]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line

### What specific section or headline is this issue about?

Installing Prettier

### What information was incorrect, unhelpful, or incomplete?

The link in below sentence is dead (page not found).
You can now run the file locally using the [npx](https://nodejs.dev/learn/the-npx-nodejs-package-runner/) tool.

### What did you expect to see?

npx introduction site

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line#navigation_on_the_command_line:~:text=You%20can%20now%20run%20the%20file%20locally%20using%20the%20npx%20tool

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/command_line`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting @devusexu - I think the CLI docs for `npx` are better here as it looks like there's no official guide any longer.
