### ISSUE TITLE
Recommend changing the name of this attribute

### ISSUE THREAD

**Issue by thomasherbertoh** [mdn/content#28087]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce

### What information was incorrect, unhelpful, or incomplete?

The word "nonce" means pedophile in British English.

### What did you expect to see?

A better attribute name could be `single_use` or similar.

### Do you have any supporting links, references, or citations?

https://dictionary.cambridge.org/dictionary/english/nonce

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/nonce`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/nonce/index.md
* Last commit: https://github.com/mdn/content/commit/ba96f2f183353872db6d9242c7d2dffe2dbc0c35
* Document last modified: 2023-02-24T05:52:35.000Z

</details>

**Comment by Josh-Cena** [comment]
This is not the place to submit feature requests—we document the web, as is. We don't make standards. In addition, this ship has already sailed—chances to change it are thin.
