### ISSUE TITLE
Issue with "Report": (short summary here please)

### ISSUE THREAD

**Issue by jamster10** [mdn/content#2811]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Report

#### What information was incorrect, unhelpful, or incomplete?
Bad URL: By sending requests to the endpoints defined via the Report-To HTTP header.
Report-To is not a header but a directive for CSP. The link should be:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to

#### Specific section or headline?
The beginning section as noted above

#### What did you expect to see?
This content: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/report`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Report
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/report/index.html
* Last commit: https://github.com/mdn/content/commit/996f4e99ba32a9d06bdeeaaa5f9222827a6f054b
* Document last modified: 2021-01-20T09:39:22.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@jamster10 Mind sharing what made you close this issue?

**Comment by jamster10** [comment]
I came across this document,

 https://www.w3.org/TR/reporting/#examples

Which implied that this was a way to set things up, with Report-To being
used as a header. So while the link is dead, and does need to link
somewhere, I wasn't sure if it was to link to the CSP directive page like I
suggested, or I misunderstood the initial writers intent, and it should
link to a page for the actual Report-To header which isn't written yet.

I suppose either way I could have left the issue open though.
