### ISSUE TITLE
Page example seem doesn't work in playground

### ISSUE THREAD

**Issue by dequadelisonz** [mdn/content#28124]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/pow

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

pow() examples seems don't work when i change pow() argument values in the playground.

### What did you expect to see?

Changing argument values of pow() i expect to see text height change in playground.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/pow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/pow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/pow/index.md
* Last commit: https://github.com/mdn/content/commit/676065ed85f246825b45579ac6228e41357dbdad
* Document last modified: 2023-04-22T05:15:34.000Z

</details>

**Comment by Josh-Cena** [comment]
pow doesn't work in any browser yet. See https://github.com/mdn/content/issues/26636

**Comment by dequadelisonz** [comment]
Ok thanks, hope it will soon.
