### ISSUE TITLE
Issue with "Perceived performance": Wording in paragraph is difficult to understand

### ISSUE THREAD

**Issue by itskitto** [mdn/content#2812]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/Perceived_performance

#### What information was incorrect, unhelpful, or incomplete?
Reading through this article, there was a particular sentence that was a bit harder to comprehend. Not something I could easily PR to suggest changes.

#### Specific section or headline?
The last paragraph of the "Perceived performance" subsection

> UI lack or responsiveness and jank both harm perceived performance. Even though a task may take a long time, though, there are ways to make it seem faster. There are several tips to improving perceived performance.

#### What did you expect to see?
I understand the overall goal of the paragraph but the flow of reading made it difficult on the first pass or even second pass when reading.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/performance/perceived_performance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/Perceived_performance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/performance/perceived_performance/index.html
* Last commit: https://github.com/mdn/content/commit/b14cfcbed1b586c80fda09c69d9cc450b9fdb887
* Document last modified: 2021-01-26T09:06:39.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. I think the doc is all hard to read. Fixed in https://github.com/mdn/content/pull/2918
