### ISSUE TITLE
Document Iterator Helper Objects

### ISSUE THREAD

**Issue by guest271314** [mdn/content#28134]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator

### What information was incorrect, unhelpful, or incomplete?

Iterator helpers are nt documented.

### What did you expect to see?

Iterator helpers documented.

### Do you have any supporting links, references, or citations?

- https://tc39.es/proposal-iterator-helpers/#sec-iterator-helper-objects
- https://tc39.es/proposal-iterator-helpers/#sec-iteratorprototype.drop
- https://tc39.es/proposal-iterator-helpers/#sec-iteratorprototype.take

et al.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/iterator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/iterator/index.md
* Last commit: https://github.com/mdn/content/commit/b5c766f4eecb4fcf9d8ba175caddb94f7c3e9d20
* Document last modified: 2023-05-01T00:22:52.000Z

</details>

**Comment by Josh-Cena** [comment]
Iterator helpers are not shipped in any browser yet.

**Comment by guest271314** [comment]
> Iterator helpers are not shipped in any browser yet.

Yes, they are. Defined in Version 117.0.5905.0 (Developer Build) (64-bit). It shouldn't matter if they are shipped or nor, they are written out in the Ecmascript specification. Thus this issue.

![Screenshot_2023-07-23_10-29-54](https://github.com/mdn/content/assets/4174848/1f0a5e7b-12be-4cf1-8ae9-55d2860d800a)

**Comment by guest271314** [comment]
That is Chromium Version 117.0.5905.0 (Developer Build) (64-bit).

**Comment by guest271314** [comment]
- https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/iterator-helpers.tq;l=436?q=iterator%20drop%20take%20file:v8%20-file:test%2F%20-file:devtools%20-file:out%2F%20-file:gen%2F&ss=chromium
- https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/iterator-helpers.tq;l=331?q=iterator%20drop%20take%20file:v8%20-file:test%2F%20-file:devtools%20-file:out%2F%20-file:gen%2F&ss=chromium

**Comment by guest271314** [comment]
> Iterator helpers are not shipped in any browser yet.

FYI. I fetch Firefox Nightly, Chromium Developer Build, Node.js nightly, and Deno every few days. 

I would strongly encourage you to do the same before claiming what is and is not implemented in a given browser and JavaScript engine.

**Comment by Josh-Cena** [comment]
> they are written out in the Ecmascript specification.

It is a stage-3 proposal, which is not considered part of the specification.

A single preview browser version is still too early. There's no need to assume that I am uninformed about the progress of new JS features; there are certain things that are shipped or close to being shipped but do not meet MDN's criteria for documentation.

**Comment by guest271314** [comment]
I didn't assume you are uninformed. I suggested you make sure you are informed, to stay on par with the curve of what vendors are shipping. I just happened to be experimenting with `Symbol.iterator` and saw `take()` and `drop()` defined. Asked a question https://groups.google.com/a/chromium.org/g/chromium-dev/c/AnGDEVxjGnM/m/MdzOjm9MAwAJ?utm_medium=email&utm_source=footer&pli=1, then did more research and found this https://2ality.com/2022/12/iterator-helpers.html but nothong on MDN about those methods. 

These things are moving. And just because Firefox does not implement something or X feature is at X stage does not mean the feature shouldn't be documented. Chromium implemented transferable streams long before Firefox caught on. People in the field are making use of File System Access API even though I think that is still a WICG draft. Just clearly write out N feature is Draft, just like in the browser compatibility chart on pages. I suspect Iterator Helpers ain't going anywhere. So you have an opportunity to do something now, instead of waiting for exactly what?

**Comment by Josh-Cena** [comment]
We have a clear checklist for whether a feature can be documented: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/What_we_write#when_we_document_a_new_technology We have to wait until it's shipped or planned for shipping in at least one stable browser version, and the spec is not expected to change.

You as a contributor can of course start documenting it yourself if you so wish, and we are open to review it, just beware that we won't merge it before the checklist for inclusion is met (at which time the team will be motivated to document it ourselves anyway).

**Comment by hamishwillee** [comment]
Thanks very much for posting - its good to have the tracking bugs with useful links to spec, explainers, etc. @Josh-Cena is correct - we'd dearly love to start documenting early but the team is too small to keep docs properly maintained for APIs that are still evolving. Better to have nothing than incorrect content.

**Comment by guest271314** [comment]
Clearly the below list items are met in this case. 

> - Specified in a specification document published under a reliable standards organization (such as W3C, WHATWG, Khronos, IETF, etc.) and has reached a reasonable level of stability (e.g., a W3C working draft or candidate recommendation or when the specification is looking fairly stable judging by the flow of issues filed against it).
> - Implemented consistently in at least one browser, with other browser developers showing signs of interest (such as an active ticket or an "intent to implement" process is in effect).

I'll ask the author of this https://2ality.com/2022/12/iterator-helpers.html write up if they want to contribute their work on MDN Web Docs.

> Thanks very much for posting - its good to have the tracking bugs with useful links to spec, explainers, etc. @Josh-Cena is correct - we'd dearly love to start documenting early but the team is too small to keep docs properly maintained for APIs that are still evolving. Better to have nothing than incorrect content.

The team is adequate. I brought this up. You folks fielded this. In the time taken to try to claim this ain't shipped, ain't up to snuff, and MDN Web Docs ain't got enough folks to stay up t date with "new technology" we could have put something together for this and moved on to the next "new technology". I ain't in to excuses. Let's get it done.

**Comment by hamishwillee** [comment]
Thanks - we'll welcome the contribution, or do it when we're sure it is stable enough to proceed.

**Comment by guest271314** [comment]
> or do it when we're sure it is stable enough to proceed.

See, that qualification is clearly met per the criteria listed, so it not necessary nor applicable in this case. I already emailed the author of the linked article/blog entry to see if they are alright with republishing their work on MDN Web Docs or wants to write up something to fix this issue.

**Comment by Josh-Cena** [comment]
No need—I already have draft branches locally for every stage 3 proposal. (See https://github.com/mdn/content/issues/26847) I will post it whenever Chrome's implementation is shipped to stable.

**Comment by guest271314** [comment]
Then there is no lack of staff. You're on it. Just checked Chrome Version 115.0.5790.102 (Official Build) unknown (64-bit) where `StringIterator` `[[Prototype]]` is `Object`; on Chromium Version 117.0.5905.0 (Developer Build) (64-bit) `StringIterator` `[[Prototype]]` is `[[Iterator]]`.

**Comment by guest271314** [comment]
@Josh-Cena @hamishwillee While you are around could you kindly review this PR https://github.com/mdn/content/pull/27228 so that MDN has a working Node.js Native Messaging host published instead of the current incomplete, non-working example published on MDN Web Docs?

**Comment by Josh-Cena** [comment]
The _value_ of `StringIterator.[[Prototype]]` has never changed; it's always the `Iterator` intrinsic. The only thing that may have changed is its console representation.

**Comment by guest271314** [comment]
> The _value_ of `StringIterator.[[Prototype]]` has never changed; it's always the `Iterator` intrinsic. The only thing that may have changed is its console representation.

How do you know?

**Comment by Josh-Cena** [comment]
Because it's required by the spec? :) See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator

**Comment by guest271314** [comment]
You are speculating unless you have run the code on Chromium 117.

**Comment by guest271314** [comment]
Earlier you claimed Iterator Helpers have not been shipped in any browser. Now you are divining what the prototype looks like without testing. We were good at when Chrome ships in Stable. Now you are quoting MDN claiming what is and is not defined on the prototype. Slow down, as you were.

**Comment by Josh-Cena** [comment]
`Iterator` has always been an intrinsic object, with or without iterator helpers. The only thing that the iterator helpers proposal adds are extra methods such as `take()` and `map()`.

What code do you suggest me trying, that would prove that the value of `""[Symbol.iterator]().__proto__.__proto__` is different between Chrome 115 and 117?

**Comment by guest271314** [comment]
Just look at the ``[[Prototype]]``. It's different between Chromium 117 and Chrome 115.

**Comment by guest271314** [comment]
You obviously have not tested. Everything matters.

**Comment by guest271314** [comment]
I have stuff to do right now. I'll show the difference later if you have not tested yourself by then.

**Comment by Josh-Cena** [comment]
I'm saying sure, the console output may have changed, but that's not worth noticing because these devX changes can come at any time. You would need to prove to me that some JavaScript code's behavior has changed that's not related to console output.

**Comment by guest271314** [comment]
![Screenshot_2023-07-25_18-19-35](https://github.com/mdn/content/assets/4174848/aac6456a-f6be-4101-abf0-dd3e51dd5454)
![Screenshot_2023-07-25_18-19-14](https://github.com/mdn/content/assets/4174848/0121e595-4b69-4090-be07-cdb288d2431c)

**Comment by Josh-Cena** [comment]
Again, console output has no significance—it's only a quality-of-life devX improvement. `[[Prototype]]: Iterator` and `[[Prototype]]: Object` refer to the exact same object: the `%Iterator.prototype%` intrinsic.

**Comment by guest271314** [comment]
It's different. Everything matters. If everything didn't matter commits wouldn't be given a uinque identifier. The `[[Prototype]` object is now an `Iterator` not an `Object`. That is a significant change.

**Comment by guest271314** [comment]
I'll explain why everything matters. Per the Screen Capture specification there is now a constraint named `systemAudio`. The problem is Chrome and Chromium authors refuse to capture monitor devices on Linux - before `systemAudio` constraint was defined. So that is misleading. At best Tab audio can be captured on Chrome or Chromium. 

Per Media Capture and Streams specification a `MediaStreamTrack` of kind audio MUST produce silence. On Chrome and Chrome a `MediaStreamTrack` of kind audio does not produce silence.

Per Web Speech API a well-formed SSML document should be parsed. The problem is the specification does not define a means to notify the speech synthesis engine that input is SSML and not plain text.

Now, given the above, per the plain language of the specifications, we should be able to capture audio output of `window.speechSynthesis.speak()` using `systemAudio` constraint of `navigator.mediaDevices.getDisplayMedia({video: true, audio:true, systemAudio: 'include'})`, however, more problems than the one listed above happens, `speechSynthesis.speak()` audio output is nout routed through the Tab, coupled with `systemAudio` not really meaning system audio.

The relevance is the details, where all details matter when we are vetting claims, errors, or omissions of specifications, implementations, or for that matter any claim whatsoever by anybody.

I'm just interested in up to date documentation about new technologies in the domain of Web API's, HTML, CSS, DOM, JavaScript, WebAssembly. Everybody doesn't implement everything everybody else does. Everybody doesn't test new implementations constantly. I filed this issue because Iterator Helpers are implemented and shipped in Chromium 117. Just like Nightly links to "What's new" in "About Nightly", I guest MDN Web Docs should consider maintaining a "What's new" re what Edge, Nightly, Chromium unstable channels have shipped.

**Comment by Josh-Cena** [comment]
> The [[Prototype]] object is now an Iterator not an Object. 

I'm still not sure what you are insisting. The only thing that has changed is the displayed name. It still refers to the exact same object, now with more properties.

Anyway, I'll pause this thread. Rest assured that this will be on the website some time soon.

**Comment by zloirock** [comment]
@guest271314 a simple explainer:

```js
''[Symbol.iterator](); // => String Iterator
''[Symbol.iterator].__proto__; // => %StringIteratorPrototype%
''[Symbol.iterator].__proto__.__proto__; // => %IteratorPrototype%, ES6+ %StringIteratorPrototype% prototype is %IteratorPrototype%
''[Symbol.iterator].__proto__.__proto__.__proto__ === Object.prototype; // => true, ES6+ %IteratorPrototype% prototype is Object.prototype
const IteratorPrototype = [].values().__proto__.__proto__;
IteratorPrototype[Symbol.iterator]() === IteratorPrototype; // true, ES6+ %IteratorPrototype% has @@iterator property

// what's new in the prototype chain from Chrome 117:
typeof IteratorPrototype.map === 'function'; // new helpers added to %IteratorPrototype%
String(IteratorPrototype) === '[object Iterator]'; // @@toStringTag added to %IteratorPrototype%
```

We could see it on your screens:

![image](https://github.com/mdn/content/assets/2213682/cb944dc7-5f27-4e3b-a756-dd9ed58a0e26)

**Comment by guest271314** [comment]
@zloirock 

Chromium 117
> constructor: ƒ Iterator()
Firefox Nightly 117
> constructor: function Object()
​​​​

**Comment by zloirock** [comment]
Yep, it's too.

**Comment by guest271314** [comment]
This `Iterator` doesn't exist on Chrome 115 and Firefox 117

> prototype:  Iterator {constructor: ƒ, reduce: ƒ, toArray: ƒ, forEach: ƒ, some: ƒ, …}

**Comment by zloirock** [comment]
I wrote about changes in the prototype chain that you mentioned above - sure, it's not the only change of this proposal -)

**Comment by zloirock** [comment]
BTW if someone will document it, don't forget to add [links to `core-js` polyfills](https://github.com/zloirock/core-js#iterator-helpers) -)

**Comment by chrisdavidmills** [comment]
This has come up on my work list for new Chrome items to document on MDN, so I'll take this on, unless anyone else is already doing it (I'll check this too!)
