### ISSUE TITLE
Video Autoplay Should Not be Used All the Time

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#28154]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Performance/video

### What specific section or headline is this issue about?

Video autoplay

### What information was incorrect, unhelpful, or incomplete?

I think a **NOTE** should be added to remind people **NOT** to use autoplay for other videos that people need to watch. Because those using assistive technologies like a screen reader can not hear their technology over the sound from a video, it's also distracting to people attempting to do other things on the page, such as read when there is sound or even moment.

### What did you expect to see?

I expected the NOTE to mention the above in the documentation.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/performance/video`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/video
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/performance/video/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you. I wouldn't be as strong as "must not", but maybe "generally should not". This is an accessibility consideration so worth mentioning, but what the developer does depends on their use case.

@estelle Are there any other accessibility concerns here that you know of? i.e. enough to warrant an accessibility section? Or a note might be sufficient?

**Comment by estelle** [comment]
This isn't the right page for this information. This page is about performance. A half sentence can be added to the autoplay section, linking to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attributes.

the example does have "muted" in the code. 
that said, i don't see why that example is in a performance tutorial as it doesn't have anything to do with video perf. The next section is about removing audio from muted videos, so combining the two sections into one about the performance of autolooping background videos should always be muted, so remove the sound.
