### ISSUE TITLE
ProcFile and runtime.txt not needed for hosting on Railway

### ISSUE THREAD

**Issue by tomjames156** [mdn/content#28166]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Communication_channels

### What specific section or headline is this issue about?

Update the app for Railway

### What information was incorrect, unhelpful, or incomplete?

ProcFile is no longer used to host Django apps on Railway rather a railway.json file containing the build commands is used. The runtime.txt file is not really neccessary for hosting on Railway.

### What did you expect to see?

![Screenshot (542)](https://github.com/mdn/content/assets/87436553/6ed5d085-3956-4587-90de-855b30371e2e)

This is a template for hosting Django applications on Railway Forked from Railway's GitHub page

### Do you have any supporting links, references, or citations?

[A link that hosts a template of a Django app and forks the hosted app to your GitHub account](https://railway.app/new/template/GB6Eki)

[The error encountered if the ProcFile method is used](https://res.cloudinary.com/practicaldev/image/fetch/s--bvXmeTnb--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/zd8c2cb3rnq4wl5cvsih.png)

[Github Repository for a Django App i recently hosted on Railway](https://github.com/tomjames156/Sticky-Notes)

### Do you have anything more you want to share?

I am open to fixing the issue🙂.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community/communication_channels`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community/Communication_channels
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/communication_channels/index.md
* Last commit: https://github.com/mdn/content/commit/931114bbe0f107b920f4a56d5b7b5c13acf4804f
* Document last modified: 2023-07-12T13:58:46.000Z

</details>

**Comment by sideshowbarker** [comment]
> I am open to fixing the issue🙂.

Cool — it’s not assigned to you (cc @hamishwillee)

**Comment by hamishwillee** [comment]
Railway has just stopped the non-free tier. Well, it's still free-ish, but you need a credit card. That's not great for a lot of potential users who might not have access. So I am considering moving the tutorial from using Railway to PythonAnywhere — they have a free plan where you can host one app as a subdomain. 

@tomjames156 Upshot, if you make this change can you please try and keep the procfile information in place, but make some note that it is not used on Railway. That way if I need to use the Procfile on whatever other service we support, the docs don't have to change too much.

**Comment by hamishwillee** [comment]
Also note, that while the railway.json works, it isn't needed either. Procfile is much more widely used for this kind of thing.

**Comment by tomjames156** [comment]
ok thanks, so in essence the change isn't really necessary 😅.

**Comment by hamishwillee** [comment]
Correct. It is possible of course that railway.json let's you do other cool stuff you can't do in a procfile. But I'd like to keep this as generic as possible in case we do have to move the infrastructure.

I think I'll close this for now :-).
