### ISSUE TITLE
Issue with "Python binding for NSS": (maintainer & bug repo invalid)

### ISSUE THREAD

**Issue by nodenineinc** [mdn/content#2816]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Python_binding_for_NSS

#### What information was incorrect, unhelpful, or incomplete?
Hello.  I recently filed a bug for this package via the listed bugzilla link and was informed by the new package maintainer that the bug repo is incorrect as well as the contact info you still have listed for this project.  Apparently the principal developer you have listed (John Dennis) has retired and nobody at redhat has credentials to the PyPI account either to be able to maintain this package further.

I'm unfortunately just trying to install the freeipa-client components on an Arch-Linux system for a client and the python-nss package is a listed dependency, and with it failing to build, the host system is stuck unable to complete installing the IPA Client.  Not sure if Mozilla, the FreeIPA team, or who else might need to be involved in discussions as far as how to overcome this package no longer building and any dependencies requiring this python component.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/projects/nss/python_binding_for_nss`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Python_binding_for_NSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/projects/nss/python_binding_for_nss/index.html
* Last commit: https://github.com/mdn/content/commit/8c1ca6575872d0de37e76f859e8e535638322bb5
* Document last modified: 2021-02-02T17:19:18.000Z

</details>

**Comment by chrisdavidmills** [comment]
@beurdouche is the main NSS maintainer left at Mozilla. He might have some thoughts on this.

**Comment by chrisdavidmills** [comment]
Hrm, this is not something we are likely to work on, as the NSS docs are not in our remit, and are in the process of being moved off MDN. I'll leave it open in case we can find anyone to help.

**Comment by beurdouche** [comment]
I asked a few days ago and nobody answered. My conclusion is that it is not maintained, so not worth the trouble.

**Comment by chrisdavidmills** [comment]
@beurdouche OK, thanks! Do you want me to just delete that page? Or leave it in until it moves off MDN so you can decide what to do with it later?

**Comment by beurdouche** [comment]
I think leaving it is ok for now. Thanks : )

**Comment by chrisdavidmills** [comment]
OK, let's close this one then. Thanks for the input.
