### ISSUE TITLE
Improve description of Number.isNaN()

### ISSUE THREAD

**Issue by gevuong** [mdn/content#28173]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

### What specific section or headline is this issue about?

The second part of the first sentence in the page.

### What information was incorrect, unhelpful, or incomplete?

The first sentence states the following: `The Number.isNaN() static method determines whether the passed value is the number value NaN, and returns false if the input is not of the Number type.`

I think the second part of the sentence, `and returns false if the input is not of the Number type`, may be inaccurate (or confusing) because:

1. `NaN` is considered a Number type when checking its type using `typeof`.
2. Therefore, passing `NaN` as the input would return `true`, not `false`.

### What did you expect to see?

I think I expected to see something like, `The Number.isNaN() static method determines whether the passed value is the number value NaN, and returns false if the input is not NaN.`

**Comment by Josh-Cena** [comment]
The first half of the sentence already covers everything "The Number.isNaN() static method determines whether the passed value is the number value NaN". The second half is only added to distinguish from `isNaN()`, which may return `true` for non-number inputs. The current text is not wrong—it does return `true` only if the input is `NaN`; it always returns `false` if the input is non-number.

**Comment by gevuong** [comment]
Oh right, I see. Sorry, I misunderstood the statement 😅

**Comment by gevuong** [comment]
After reviewing it once more, I think I understand why I was confused.

I misunderstood the second half, `and returns false if the input is not of the Number type`, and thought `Number.isNaN()` returns false _only_ if the input is a non-number type. But that's not true. An input can be a number type and still return `false` (ie. `Number.isNaN(5))`.

With your explanation of why the second half was added, to distinguish from `isNaN()` which can return `true` for non-number inputs, it made more sense. Thanks for the clarification.
