### ISSUE TITLE
Error in NUMERIC, BITWISE section of docs (left vs right)

### ISSUE THREAD

**Issue by vorton55** [mdn/content#28176]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Numeric

### What specific section or headline is this issue about?

In the BITWISE section, "Right shift" incorrectly described

### What information was incorrect, unhelpful, or incomplete?

[Left shift](https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Numeric/Left_shift)
Used for performing a bitwise left-shift.

[**Right shift**](https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Numeric/Right_shift)
Used for performing a bitwise **left-shift.  <<=== ERROR!**

### What did you expect to see?

I expected to see:
"Used for performing a bitwise **right**-shift."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/webassembly/reference/numeric`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Numeric
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/reference/numeric/index.md
* Last commit: https://github.com/mdn/content/commit/fe898ddf33314ee129256c3862c5c53106eeec1f
* Document last modified: 2023-02-23T10:05:41.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. I’ve opened #28181 with a fix. After that fix is merged, this issue will automatically be marked as resolved, and closed.
