### ISSUE TITLE
Recommendation: Offer justifications as to why the MDN style guide recommendations exist

### ISSUE THREAD

**Issue by returnMarcco** [mdn/content#28185]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript

### What specific section or headline is this issue about?

The whole document

### What information was incorrect, unhelpful, or incomplete?

All information was useful and well put together, however justifications for the recommended DOs and DO NOTs are non-existent.

### What did you expect to see?

justifications for the recommended DOs and DO NOTs.
E.g. Why should we not use function expressions to declare functions? Why should we use single-line comments in-lieu of multi-line comments? etc.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
* Last commit: https://github.com/mdn/content/commit/d85a7ba8cca98c2f6cf67a0c44f0ffd467532f20
* Document last modified: 2023-04-05T04:57:48.000Z

</details>

**Comment by Josh-Cena** [comment]
These are arbitrary stylistic decisions. Some are just because some team members believe "it looks better". The point of a style guide is to fix these stylistic decisions and then make sure everyone sticks to it.
