### ISSUE TITLE
"Avoid using multiple h1 tags" is incorrect 

### ISSUE THREAD

**Issue by ned-martin** [mdn/content#28215]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

### What specific section or headline is this issue about?

Avoid using multiple h1 tags

### What information was incorrect, unhelpful, or incomplete?

The article specifies multiple times that using multiple h1 tags should be avoided. This is technically incorrect and is representative of someone's personal bias on the matter. 

The suggested method of using a H1 tag to duplicate the page title, then using H2 tags for top-level headings, while it may work for some content, is an incorrect representation of content that has more than one top-level heading. The page <title> attribute is *not* automatically synonymous with a single H1 tag, and not all content fits into the structure of a single top-level heading with multiple sub-headings. Suggesting that HTML code should not reflect the reality of the content is wrong.

### What did you expect to see?

Heading tags (h1, h2, etc.) should be used to correctly model the semantic structure of content. If the content has more than one top-level heading, then more than one H1 tag should be used. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/heading_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/heading_elements/index.md
* Last commit: https://github.com/mdn/content/commit/37163d27e0625a83a3f8633fe58b9041867adeaa
* Document last modified: 2023-05-19T17:19:46.000Z

</details>

**Comment by Josh-Cena** [comment]
See also https://github.com/orgs/mdn/discussions/232. What example do you have where a page has multiple headings and cannot have an adequate overall heading? Even for something like a blog landing page, it can have a descriptive title like "My blog".

**Comment by estelle** [comment]
The text reads "avoid". That is correct.

It is best practice to avoid more than one h1. If there is a case in which the content has more than one top-level heading, then more than one H1 tag can be used. There are exceptions to every rule. "Avoid" rather than "It's invalid to... " of "Don't" means just that; avoid, but there are exceptions.

**Comment by estelle** [comment]
As nothing needs to be edited, closing.

**Comment by ned-martin** [comment]
> The text reads "avoid". That is correct.

This is incorrect. If your content semantically has multiple top level headings, then you should *not* avoid using multiple H1 tags for those headings. The correct structure in that case would be to use multiple H1 tags.

The MDN reference should only provide accurate and factual information. It is not the place for personal opinions. If your personal opinion is that it makes more sense to have one H1 tag, then feel free to use that on your sites, but do not put it on the MDN reference as it is not a factually correct statement.

The amount of H1 tags used should match the structure of the content being marked up.

**Comment by ned-martin** [comment]
> What example do you have where a page has multiple headings and cannot have an adequate overall heading?

What example do you have where a page containing multiple H1 tags causes any type of issue?

It is incredibly naive to assume that everyone's content on the internet matches a narrow-minded definition of a structure with a single top level heading, shared with the page title tag, and then multiple subheadings.

You are effectively assuming that the H1 tag is synonymous with the page title tag, and that the H2 tag is effectively then used as the top level content heading tag.

I would argue that this is incorrect and that the H1 tag should be used as the top level content tag, and that the page title tag should be used for the page title. This is how it is used in most other documents (such as Microsoft Word documents for example), and HTML needs to be able to mark up similar semantic structures in a similar way.

**Comment by estelle** [comment]
As you believe us to be naive and narrow-minded, you may prefer contributing elsewhere.

**Comment by bsmth** [comment]
Hi @ned-martin - taking part in-person and in online spaces or projects such as this repository, you must adhere to the code of conduct and community guidelines, including politeness and staying respectful when disagreements arise. Being rude toward other community members is not tolerated. Please familiarize yourself with the [Open source etiquette](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette#be_polite_be_kind_avoid_incendiary_or_offensive_language) guide and the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/). Thank you.
