### ISSUE TITLE
Broken navigation links

### ISSUE THREAD

**Issue by Eroppo** [mdn/content#2822]
Buttons "Forward" at [Sessions](https://developer.mozilla.org/ru/docs/Learn/Server-side/Django/Sessions) and "Back" at [Forms](https://developer.mozilla.org/ru/docs/Learn/Server-side/Django/Forms) leads to [authentication_and_sessions](https://developer.mozilla.org/ru/docs/Learn/Server-side/Django/authentication_and_sessions) with Page not found error: the correct url is [Authentication](https://developer.mozilla.org/ru/docs/Learn/Server-side/Django/Authentication)

**Comment by chrisdavidmills** [comment]
Apologies, but we are not currently making changes to translations. See https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
