### ISSUE TITLE
Working examples of promises

### ISSUE THREAD

**Issue by karelvaculik** [mdn/content#28236]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises

### What specific section or headline is this issue about?

The whole page

### What information was incorrect, unhelpful, or incomplete?

Would it be possible to add more working examples into the guide about promises, please? The page shows many code snippets and talks about various features of promises, but the first real working example is in approximately the first 1/3 of the page in section "Chaining after a catch". Before that, there are many examples with `doSomething` and other functions / promises, but none of them work on their own.

I am aware of the initial information
> Since most people are consumers of already-created promises, this guide will explain consumption of returned promises before explaining how to create them.

but as somebody going from a background without promises, I find it more difficult to go through this page than it could be IMHO. I was reading all pages of this JavaScript Guide from the start and here I feel that I need to study promises elsewhere first and then get back here to be able to "complete" the vague examples.

Or if a reader is supposed to study the reference page for Promise first, can this recommendation be added to the top of the page, please?

### What did you expect to see?

I would like to see more working examples with promises, because having only non-working code or pseudo-code seems like half information when in fact we could have full information available.

**Comment by wbamberg** [comment]
FWIW there's a much more hands-on guide to promises at https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises.

**Comment by lyndipc** [comment]
I agree that the promises section mentioned by @karelvaculik is kind of unclear. Can I work on this?

**Comment by Josh-Cena** [comment]
To fix this, we only need to add a  basic implementation for all functions mentioned on this page `doSomething`, etc.
