### ISSUE TITLE
Issue with "Compiling from Rust to WebAssembly": (short summary here please)

### ISSUE THREAD

**Issue by benbyford** [mdn/content#2824]
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

#### What information was incorrect, unhelpful, or incomplete?
Would be useful to show how to use on the web without bundlers e.g. webpack as it is not always nessacary to use them and hides important implementation steps.

#### Specific section or headline?
Using the package on the web

#### What did you expect to see?
Rust binary used on the web with no dependencies

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/rust_to_wasm`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/rust_to_wasm/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by chrisdavidmills** [comment]
Hi @benbyford ! This issue did not get much traction, so I'm wondering if you could provide a bit more detail about what you'd like to see, or maybe even help to write the content? That last part was a bit cheeky, but on a serious note, we might be able to find more contributors to help if we have a clearer plan of what content you'd like to see. thanks!

**Comment by benbyford** [comment]
Hi!
I write html5 games sometimes and would love to learn more about using wasm to do it. however i dont use React and bundlers so really looking for what a barebones implementation looks like, which tbh I'm suprised you didnt have :( 

Love to write it myself but would need to find sometime to learn and then write about it.... so if someone else can do it first that would be awesome, as i might be a while.

**Comment by chrisdavidmills** [comment]
> Hi!
> I write html5 games sometimes and would love to learn more about using wasm to do it. however i dont use React and bundlers so really looking for what a barebones implementation looks like, which tbh I'm suprised you didnt have :(
> 
> Love to write it myself but would need to find sometime to learn and then write about it.... so if someone else can do it first that would be awesome, as i might be a while.

No worries at all. We'll see if we can find someone to add this content.

**Comment by mireille-raad** [comment]
I am interested in figuring this out. I will submit a PR if/when I do.

**Comment by chrisdavidmills** [comment]
> I am interested in figuring this out. I will submit a PR if/when I do.

That would be great, thanks for considering this, @mireille-raad. If you do move forward with working this out, and want to create the content to explain it, let me know so I can assign you to this issue. Thanks!

**Comment by MendyBerger** [comment]
@mireille-raad wandering if you're working on this or else I might be able to hack something together

**Comment by mireille-raad** [comment]
@MendyBerger  that would be great, please go ahead.

**Comment by chrisdavidmills** [comment]
Assigned; thanks @MendyBerger !
