### ISSUE TITLE
createNodeIterator: Use Best Practice Example

### ISSUE THREAD

**Issue by erosman** [mdn/content#28256]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/createNodeIterator

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The example shows:

```js
let currentNode;
while ((currentNode = nodeIterator.nextNode())) {
  pars.push(currentNode);
}
```

### What did you expect to see?

It would be worthwhile to use the best practice in the above example as shown in the following section i.e.
```js
while ((currentNode = nodeIterator.nextNode()) !== null) {
  // ...
}
```

### Do you have any supporting links, references, or citations?

> [while: Using an assignment as a condition](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/while?retiredLocale=de#using_an_assignment_as_a_condition)
> 
> But the real best practice is to go a step further and make the code even more clear — by adding a comparison operator to turn the condition into an explicit comparison:
> 
> ```js
> const iterator = document.createNodeIterator(document, NodeFilter.SHOW_COMMENT);
> let currentNode;
> while ((currentNode = iterator.nextNode()) !== null) {
>   console.log(currentNode.textContent.trim());
> }
> ```

**Comment by Josh-Cena** [comment]
See https://github.com/mdn/content/issues/28257#issuecomment-1657185526: I think the current style is better and I would be rephrasing thé `while` page instead.
