### ISSUE TITLE
Don't add asyncHandler install

### ISSUE THREAD

**Issue by BodNS** [mdn/content#28271]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_detail_page

### What specific section or headline is this issue about?

Controller

### What information was incorrect, unhelpful, or incomplete?

Note: We don't need to require any additional modules in this step, as we already imported the dependencies when we implemented the home page controller.

### What did you expect to see?

Note: We need to require express-async-handler in this step, all others requieres we already imported the dependencies when we implemented the home page controller.

npm i express-async-handler

### Do you have any supporting links, references, or citations?

exports.book_detail = asyncHandler(async (req, res, next) => {

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/book_detail_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_detail_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/book_detail_page/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. However the book controller was imported and required when we set up our routes:
- https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#create_the_route-handler_callback_functions
- https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#book_controller

So by the time we get to the document you are pointing at, the handler should already be present.

Closing
