### ISSUE TITLE
[Nightly + pref][JS] Implement ArrayBuffer.prototype.transfer() proposal

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#28285]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1841113

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
@Josh-Cena FYI, seeing as how you've done the work so far I've assigned you. Added me as well for the FF part of things. Have you looked at browser compat yet?

**Comment by Josh-Cena** [comment]
Um, sorry, no—I'm not very keen with adding BCD (I don't even have the repo cloned locally, and using github.dev feels like using another one's computer). Would be great if you can do that ^^

(FWIW, I have these branches prepared locally anyway, and whenever I see a release available I send the PR.)

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD
- [ ] Docs - #28381
- [ ] Release note
- [ ] dev-doc-complete

**Comment by bsmth** [comment]
Closing this as done now, thanks all
