### ISSUE TITLE
CORS: Allow particular Range header values without a preflight

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#28281]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- n/a Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- n/a Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1733981

__Notes:__

- WPT: https://wpt.fyi/results/cors/cors-safelisted-request-header.any.html?label=master&label=experimental&aligned
  - src: https://github.com/rayankans/wpt/blob/master/cors/cors-safelisted-request-header.any.js
- https://fetch.spec.whatwg.org/#concept-request-add-range-header

__Related issues and pull requests:__

- [x] https://github.com/mdn/content/pull/14657
- [x] Content & Relnote - https://github.com/mdn/content/pull/28733
- [x] BCD https://github.com/mdn/browser-compat-data/pull/20605

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
@bsmth This requires a BCD update because the behaviour, as implemented by the browser, has changed.

**Comment by bsmth** [comment]
There's been some content improvements landed in the linked PRs above. Searching for related issues surfaced the following that can be addressed in follow-ups:

- [ ] https://github.com/mdn/content/issues/18237 (better linking between `Range` request and [`Accept-Ranges` response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges).)
- [ ] https://github.com/mdn/content/issues/24625 ("blob: URLs now support Range headers. This impacts both fetch() and XMLHttpRequest.")
- [ ] https://github.com/mdn/content/issues/26733

**Comment by dlrobertson** [comment]
> the docs changes are mainly in this (now-merged) PR: #28733 which includes [preview builds of the diff for convenience](https://github.com/mdn/content/pull/28733#issuecomment-1691638628). 

Awesome! Thanks for working on this and getting the docs changed!
