### ISSUE TITLE
[SVG] <script> with type="module" doesn't work when placed inside <svg> element

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#28294]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

This just looks like a bug fix, but worth seeing if any updates are needed

__Related issues and pull requests:__

- [x] Relnote https://github.com/mdn/content/pull/28372
- [x] BCD https://github.com/mdn/browser-compat-data/pull/20502

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1839954

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
I would have thought BCD update to https://developer.mozilla.org/en-US/docs/Web/SVG/Element/script#browser_compatibility ?

Given this is a new feature not compatible with the earlier releases.

**Comment by bsmth** [comment]
>I would have thought BCD update to https://developer.mozilla.org/en-US/docs/Web/SVG/Element/script#browser_compatibility ?

I don't think this breaks compatibility, but it's worth adding keys for `defer` and `sync` to BCD actually.

- SVG spec: https://svgwg.org/svg2-draft/interact.html#ScriptElement
- HTML spec: https://html.spec.whatwg.org/multipage/scripting.html#attr-script-async

**Comment by hamishwillee** [comment]
> I don't think this breaks compatibility,

If something didn't work (and the spec said it should), and later you add support for that feature, it's a compatibility change that should be recorded in BCD. To me this is no different than the HTML `<script>` element entry `type.module` - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script. 

But I have done no actual research, so sorry if I am missing something.

**Comment by bsmth** [comment]
>If something didn't work (and the spec said it should), and later you add support for that feature, it's a compatibility change that should be recorded in BCD.

Very good, in this case it's another instance of inheriting behavior from elsewhere, where the spec says:

>A ‘[script](https://svgwg.org/svg2-draft/interact.html#ScriptElement)’ element is equivalent to the ‘[script](https://svgwg.org/svg2-draft/interact.html#ScriptElement)’ element in HTML

My only concern is content duplication, and including/duplicating all <script> attrs under SVG script, also.

BCD open here for these inclusions:
- [ ] https://github.com/mdn/browser-compat-data/pull/20502

**Comment by hamishwillee** [comment]
> My only concern is content duplication, and including/duplicating all <script> attrs under SVG script, also.

Unfortunately, unless SVG and HTML actually mirror in terms of the version in which they are supported across all our supported browsers, I don't see that we have any choice but to duplicate. If they do match, then we could reasonably consider some kind of merging of the data. IN that case BCD would have to invest some time to define the rules of how that would work - because right now they are separate and clearly separate.

Anyway, thanks for sorting this.

**Comment by bsmth** [comment]
> I don't see that we have any choice but to duplicate.

I think we have to do this, yes. I've opened https://github.com/mdn/browser-compat-data/issues/20590 to track this for the moment.

**Comment by bsmth** [comment]
Closing this one as done with follow-ups tracked in BCD for other SVG attrs for `<script>`
