### ISSUE TITLE
Issue with "title": "Hovering here will show nothing." shows something when hovering

### ISSUE THREAD

**Issue by ArguiS** [mdn/content#28297]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title

#### What information was incorrect, unhelpful, or incomplete?
In the results there are two \<p\>. one with an empty title and one with a specified title attribute. hovering over the second one (the one with the empty title) should show nothing but it shows in an title "title attribute inheritance sample" (it generally shows that in the whole result container, not the second \<p\> perse, its still very confusing and distracting.)

#### Specific section or headline?
[Title attribute inheritance](https://mdn1.moz.one/en-US/docs/Web/HTML/Global_attributes/title#title_attribute_inheritance) > Result

#### What did you expect to see?
Nothing

#### Did you test this? If so, how?
Refreshing site and using different browser, chrome works as it should, firefox v114 & v117 ironically not

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/global_attributes/title`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title
* GitHub URL: https://github.com/mdn/content/blob/style/old/files/en-us/web/html/global_attributes/title/index.md
* Last commit: https://github.com/mdn/content/commit/426485595b1be50e2af91764fbfd94c04c3c36a5
* Document last modified: 2022-02-18T11:38:26.000Z

</details>

**Comment by Josh-Cena** [comment]
It's fixed now in Firefox
