### ISSUE TITLE
[CSS] support contain-intrinsic-size: auto none

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#28292]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1835813

__Related issues and pull requests:__

- [x] Relnote https://github.com/mdn/content/pull/28522
- [x] BCD https://github.com/mdn/browser-compat-data/pull/20532
- [x] Content  https://github.com/mdn/content/pull/28618
- [x] data https://github.com/mdn/data/pull/684
 
## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by bsmth** [comment]
There's a WPT for this:

- https://wpt.fyi/results/css/css-sizing/contain-intrinsic-size/auto-014.html?run_id=5182508746932224&run_id=5094004100694016&run_id=5117497412419584&run_id=5115791261827072&run_id=5188381779165184
- Passes in `117.0a1`: http://wpt.live/css/css-sizing/contain-intrinsic-size/auto-014.html
- [Source on GH](https://github.com/web-platform-tests/wpt/blob/master/css/css-sizing/contain-intrinsic-size/auto-014.html)

**Comment by bsmth** [comment]
Closing as done now
