### ISSUE TITLE
[CSS] Sign-Related Functions: abs() and sign()

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#28293]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1814588

## Features to document

We already have some pages for these:

- [`abs()`](https://developer.mozilla.org/en-US/docs/Web/CSS/abs)
- [`sign()`](https://developer.mozilla.org/en-US/docs/Web/CSS/sign)

What's missing is BCD and Relnote.

Note that this brings it out of experimental status.

## Related issues and pull requests

- [x] Relnote: https://github.com/mdn/content/pull/28370
- [x] BCD: https://github.com/mdn/browser-compat-data/pull/20471

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by evilpie** [comment]
`sign` and `abs` are not enabled by default in 117. They are going to be shipped together with other new math functions in https://bugzilla.mozilla.org/show_bug.cgi?id=1814589.

**Comment by bsmth** [comment]
Amended BCD:

- [x] https://github.com/mdn/browser-compat-data/pull/20471

**Comment by bsmth** [comment]
As BCD & Relnote changes have landed, setting this as done now.

**Comment by bsmth** [comment]
All looks complete on this, closing as done now
