### ISSUE TITLE
[CSS] Enable math-style and math-depth by default

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#28290]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [n/a] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [n/a] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

- Enabled by default https://bugzilla.mozilla.org/show_bug.cgi?id=1845516
- Implementation: https://bugzilla.mozilla.org/show_bug.cgi?id=1667090

__Related issues and pull requests:__

- BCD
  - [x] `math-depth`, `font-size: math` https://github.com/mdn/browser-compat-data/pull/20417
  - [x] `math-style`: https://github.com/mdn/browser-compat-data/pull/20425
- [x] Relnote: https://github.com/mdn/content/pull/28447
- [x] Examples: https://github.com/mdn/content/pull/28454

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by bsmth** [comment]
I'm rolling the "implementation" and "enabled" issues into this one so we cover both here. BCD has been kindly taken care of already.

TODO for this:

- [ ] Relnote & removal from experimental features (linked above)
- [ ] Examples (incoming)

**Comment by bsmth** [comment]
There doesn't look like anything else outstanding for this so I am closing as done
