### ISSUE TITLE
app wont be installed

### ISSUE THREAD

**Issue by ARiyou2000** [mdn/content#28305]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable

### What information was incorrect, unhelpful, or incomplete?

after clicking install app nothing will happen

### What did you expect to see?

app installed in my Android or Chrome browser 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/progressive_web_apps/guides/making_pwas_installable`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/guides/making_pwas_installable/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by wbamberg** [comment]
Hi! Thanks for filing. You'll need to provide more information than this for us to be able to look into it.
- Do you have a minimal example you can share, that would enable us to reproduce it?
- Is there a specific part of https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable you can point to, that is incorrect?

**Comment by wbamberg** [comment]
No response -> closing.
