### ISSUE TITLE
More differences between HTML dir and CSS direction

### ISSUE THREAD

**Issue by NeilWix** [mdn/content#28320]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/direction

### What specific section or headline is this issue about?

Last paragraph of the "try it" section

### What information was incorrect, unhelpful, or incomplete?

no mention that the HTML dir also have an auto valuehas

### What did you expect to see?

an explicit mention of this difference

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/direction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/direction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/direction/index.md
* Last commit: https://github.com/mdn/content/commit/46cdbd128c81afe8e7488b913bbd8b161f5323e1
* Document last modified: 2023-05-22T22:14:54.000Z

</details>

**Comment by kemilbeltre** [comment]
I think it's not necessary as we are not defining `dir` in this page. For that we have this specification in: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#dir.

**Comment by Josh-Cena** [comment]
I agree, it's not meant as an exhaustive comparison as they serve very different purposes in the first place.
