### ISSUE TITLE
Callback Function

### ISSUE THREAD

**Issue by DataToolGuy** [mdn/content#28326]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Callback_function

### What specific section or headline is this issue about?

error in code example:  Uncaught ReferenceError: doSomething is not defined

### What information was incorrect, unhelpful, or incomplete?

I tried to run the code as given on the page in FireFox's console but it did not work.
Error: Uncaught ReferenceError: doSomething is not defined
    <anonymous> debugger eval code:3
Code:
let value = 1;

doSomething(() => {
  value = 2;
});

console.log(value);

### What did you expect to see?

A result of 2 is what the page says I should see.

From the context of the explanation around the code, I expected the sample code to actually work.

### Do you have anything more you want to share?

ran the code as given in FireFox's console

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/callback_function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Callback_function
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/callback_function/index.md
* Last commit: https://github.com/mdn/content/commit/766ba3b1169c752e415fbc30cf0a1067ba9b8a78
* Document last modified: 2023-06-29T04:24:48.000Z

</details>

**Comment by Josh-Cena** [comment]
This is not intended to be an executable example. As indicated below, we don't know the implementation of `doSomething` and that's the point. We also gave a few examples of sync and async callbacks.
