### ISSUE TITLE
The hyperlink to under the text "Keith Peters" redirects to his inactive twitter account.

### ISSUE THREAD

**Issue by meetanoopverma** [mdn/content#28336]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript

### What specific section or headline is this issue about?

See also

### What information was incorrect, unhelpful, or incomplete?

The hyperlink redirects to the inactive twitter handle of the Keith Peters. He has moved his social handle to mstdn.social

### What did you expect to see?

I wish this link to redirect to his new mstdn.social handle or point to his blog repository. Please have a look at the screenshot attached to get the accurate info. I can open a PR to fix this issue.

![Screenshot 2023-08-02 095950](https://github.com/mdn/content/assets/94305004/f1ff3b8f-fb74-4ee6-aab1-e2135e39fbc2)

### Do you have any supporting links, references, or citations?

His new social profile link is https://mstdn.social/@bit101
His blog repository is placed at https://www.bit-101.com/blog/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>

**Comment by meetanoopverma** [comment]
@bsmth Hi, Can you please have a look?

**Comment by hamishwillee** [comment]
@meetanoopverma Please don't ping specific reviewers. We all have our own priorities, and will take issues when and as they fit our skills and priorities. 

FWIW I would just remove the name and link. Would you like to create a PR for this?

**Comment by meetanoopverma** [comment]
Thanks for the response. I have created a PR to fix this. Kindly review it.

**Comment by Josh-Cena** [comment]
You've created a PR to your own fork. That is not our content.
