### ISSUE TITLE
LockManager request return type information inconsistent

### ISSUE THREAD

**Issue by stanleyk** [mdn/content#28339]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/LockManager/request

### What specific section or headline is this issue about?

Return value

### What information was incorrect, unhelpful, or incomplete?

It is not clear, whether the `request()` method returns 

> a Promise that resolves with undefined

as stated in the first paragraph, or

> A Promise that resolves (or rejects) with the result of the callback after the lock is released, or rejects if the request is aborted.

as stated in the Return value section.

According to my testing, Chrome 115 has it implemented the other way. But for example https://www.npmjs.com/package/@types/web-locks-api has it typed the undefined way. I am not sure, what the expected behavior is.

### What did you expect to see?

Consistent information about the return type. I would edit the page myself but I am not sure what the intended behavior actually is.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/lockmanager/request`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/LockManager/request
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/lockmanager/request/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by Josh-Cena** [comment]
The return value was fixed in https://github.com/mdn/content/pull/27130, but not the intro.

I dunno why `@types/web-locks-api` types it the other way (I looked but there doesn't seem to be a spec change). Maybe they used MDN docs and got it wrong too.
