### ISSUE TITLE
Table height attribute

### ISSUE THREAD

**Issue by EzioMercer** [mdn/content#28346]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table

### What specific section or headline is this issue about?

Attributes

### What information was incorrect, unhelpful, or incomplete?

There is no information about `height` attribute of table. [There is no `height` attribute in specification](https://www.w3.org/TR/html401/struct/tables.html#h-11.2.1) but many users try to set this attribute and as an result a several browsers (including Firefox) uses this attribute. So it is very confusing that we don't have attribute but it works

### What did you expect to see?

I expect to see a little information about absence attribute `height`. There should be a warning like:
> Still some browsers interpret attribute `height` anyway [it is not part of official documentation](https://www.w3.org/TR/html401/struct/tables.html#h-11.2.1)

### Do you have any supporting links, references, or citations?

As you can see the question [Setting the height of a table in HTML has no effect](https://stackoverflow.com/questions/14809502/setting-the-height-of-a-table-in-html-has-no-effect) has about 34K (at the moment of submitting this issue) views which means that many people try to use this attribute and get confused

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/table`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/table/index.md
* Last commit: https://github.com/mdn/content/commit/48838af610dd803130997115dbe274a5a19c532e
* Document last modified: 2023-06-29T18:59:13.000Z

</details>

**Comment by rimjhp-06** [comment]
Hi,
Can you assign this issue to me?

**Comment by rimjhp-06** [comment]
Hi,

I have raised a PR. Can someone review it and let me know if any changes are required?

**Comment by EzioMercer** [comment]
@rimjhp-06 Thanks for helping!
