### ISSUE TITLE
Django Tutorial (Local Library) Part 8 os needs to be imported for newer versions

### ISSUE THREAD

**Issue by clhjoburg** [mdn/content#2836]
When setting up authentication views on this page (https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication) an error occurs 'os is not defined'. os is not imported by default in Django 3.1 onwards so the tutorial has to state that this needs to be imported into settings.py or otherwise be altered to use pathlib.

Thanks

**Comment by hamishwillee** [comment]
Thanks very much. Yes, this got reported a couple of weeks ago. Just fixed it in https://github.com/mdn/content/pull/2919
