### ISSUE TITLE
outdated use of @font-face in "Learn to style HTML using CSS -> Web fonts"

### ISSUE THREAD

**Issue by mireille-raad** [mdn/content#2837]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts

#### What information was incorrect, unhelpful, or incomplete?

```
@font-face {
  font-family: 'ciclefina';
  src: url('fonts/cicle_fina-webfont.eot');
  src: url('fonts/cicle_fina-webfont.eot?#iefix') format('embedded-opentype'),
         url('fonts/cicle_fina-webfont.woff2') format('woff2'),
         url('fonts/cicle_fina-webfont.woff') format('woff'),
         url('fonts/cicle_fina-webfont.ttf') format('truetype'),
         url('fonts/cicle_fina-webfont.svg#ciclefina') format('svg');
  font-weight: normal;
  font-style: normal;
}

```

#### Detailed problem

The @font-face article on mdn is on [this link](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face ):

It uses this definition:
```
@font-face {
  font-family: "Open Sans";
  src: url("/fonts/OpenSans-Regular-webfont.woff2") format("woff2"),
       url("/fonts/OpenSans-Regular-webfont.woff") format("woff");
}
```

SVG is depreciated/not recommend
<img width="1004" alt="Screen Shot 2021-03-03 at 12 02 47 PM" src="https://user-images.githubusercontent.com/521705/109857971-7e013600-7c18-11eb-80f8-71f8c6025e7f.png">

it seems that `woff` and `woff2` are recommended
<img width="988" alt="Screen Shot 2021-03-03 at 12 03 04 PM" src="https://user-images.githubusercontent.com/521705/109857993-83f71700-7c18-11eb-8b5b-3fd0b7c3bc5a.png">

This makes the font-face use in this article outdated or confusing or extra work for people. 

#### What did you expect to see?

This page has really high SEO. It is what I always end-up on after googling. A different/better use of the font-face should be used. It might make it less overwhelming for new comers as a bonus.

I could do a PR but changing the code means we should change the context and the reference to a few other things like the font-squirrel generator (which Mozilla Firefox tells me has 18 trackers  😛  ).

## Question

Is this page up for re-write? I could do a PR suggesting some fixes and simplification. Should I do it?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/styling_text/web_fonts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/styling_text/web_fonts/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by rachelandrew** [comment]
@mireille-raad very happy if you want to do a PR, let me know if you need any help.

The instructions for getting the project set up locally are in the Readme.

**Comment by mireille-raad** [comment]
I am on it 😄

**Comment by Ryuno-Ki** [comment]
@mireille-raad I can't wait to see what you come up with :)

**Comment by mireille-raad** [comment]
@rachelandrew, I checked caniuse.com  

WOFF has been supported:

- on IE9 since 2011
- on safari iOS since 2012 
- Android since 2013 

Here is the link https://caniuse.com/mdn-css_at-rules_font-face_woff (screenshots are on the bottom)

In the current mdn text on [this link](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts), there is this paragraph:
> Browsers support different font formats, so you'll need multiple font formats for decent cross-browser support. For example, most modern browsers support WOFF/WOFF2 (Web Open Font Format versions 1 and 2), the most efficient format around, but older versions of IE only support EOT (Embedded Open Type) fonts, and you might need to include an SVG version of the font to support older versions of iPhone and Android browsers. We'll show you below how to generate the required code.

Can I totally remove the EOT/SVG parts? or should I move them to a  section for "supporting old browsers"?  

I looked up the % of users who could be affected if a web dev did not include these. The total is 0.11%. 

On one hand, this is a learning tutorial and it helps having it be concise and clear. But deleting stuff might make the life of that lone developer looking to support ancient browser a smidge more hard.

Let me know what you think I should do.

## Screenshots

### IE9
<img width="481" alt="Screen Shot 2021-03-08 at 5 15 27 PM" src="https://user-images.githubusercontent.com/521705/110398868-fd847000-8031-11eb-925f-d30e25113f8e.png">

## iOS
<img width="452" alt="Screen Shot 2021-03-08 at 5 15 46 PM" src="https://user-images.githubusercontent.com/521705/110399005-40dede80-8032-11eb-8f9b-1cc89d71c1ca.png">

## Android
<img width="444" alt="Screen Shot 2021-03-08 at 5 15 39 PM" src="https://user-images.githubusercontent.com/521705/110399015-463c2900-8032-11eb-85df-40dc5bc27742.png">

**Comment by rachelandrew** [comment]
@mireille-raad if we are doing something based on browser support then the preference would be to test it rather than relying on Can I Use data. The data you are referencing actually came from MDN, so would be good to confirm it.

If that is correct however then I think you can remove the SVG stuff completely.

**Comment by chrisdavidmills** [comment]
@mireille-raad are you still interested in submitting a PR to fix this? If not, then that's OK, but we'd like to unassign it so someone else can have a go at it.

Thanks.

**Comment by mireille-raad** [comment]
I'll submit a PR today or tomorrow, if not plz reassign... sorry got busy with stuff.

**Comment by chrisdavidmills** [comment]
> I'll submit a PR today or tomorrow, if not plz reassign... sorry got busy with stuff.

No worries at all; we'd still love to have your contribution!

**Comment by mireille-raad** [comment]
@chrisdavidmills, I submitted PR https://github.com/mdn/content/pull/3283 . Let me know if you want to discuss it / go over the content.

**Comment by rachelandrew** [comment]
@mireille-raad apologies, that's assigned to me and somehow I missed the notification. I'll take a look tomorrow.
