### ISSUE TITLE
aria-label can be used on non-interactive elements

### ISSUE THREAD

**Issue by luce-carevic** [mdn/content#28397]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

### What information was incorrect, unhelpful, or incomplete?

>The aria-label attribute defines a string value that labels an interactive element.

>The aria-label attribute is intended for interactive elements only.

> **Note:** `aria-label` is intended for use on interactive elements, or elements made to be interactive via other ARIA declarations, when there is no appropriate text visible in the DOM that could be referenced as a label

### What did you expect to see?

For the first sentence, I would expect the mdn page to use the same definition as the [Accessible Rich Internet Applications (WAI-ARIA) 1.2 W3C Recommendation](https://www.w3.org/TR/wai-aria-1.2/#aria-label).

>Defines a string value that labels the current element.

For the other paragraphs, I would simply delete them since it's not accurate (and contradicts the rest of the doc).

### Do you have any supporting links, references, or citations?

Official spec: https://www.w3.org/TR/wai-aria-1.2/#aria-label

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/accessibility/aria/attributes/aria-label`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/attributes/aria-label/index.md
* Last commit: https://github.com/mdn/content/commit/07f0cf4375aaa02e1071d8bd0e8518db7609b7a9
* Document last modified: 2023-07-17T23:05:13.000Z

</details>

**Comment by bsmth** [comment]
Thanks for opening the issue. For context, this wording was introduced here: https://github.com/mdn/content/pull/10575#discussion_r753715233
