### ISSUE TITLE
Strange behavior of getSelection

### ISSUE THREAD

**Issue by ghazpar** [mdn/content#28396]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection

### What specific section or headline is this issue about?

Section "Related objects" at bottom of page

### What information was incorrect, unhelpful, or incomplete?

> It is worth noting that currently getSelection() doesn't work on the content of [<textarea>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) and [<input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) elements in Firefox and Edge (Legacy).

Is this a Firefox feature or is it a bug? If it's a bug, why has it not been fixed after all these years?

https://bugzilla.mozilla.org/show_bug.cgi?id=85686

The incorrect information is that Edge also shares this bug. If it was true in the past, it is no longer true. I have tested Chrome, Safari, Edge, and Opera, and none of them exhibit this behavior, only Firefox.

https://jsfiddle.net/AVLCY/1/

### What did you expect to see?

I expect that this bug be fixed and that this whole paragraph be removed!

If a selection exists, I expect that `window.getSelection()` returns this selection no matter the element type. Otherwise, the method should be called `getSelectionExceptForFormElements` ;-)

### Do you have any supporting links, references, or citations?

https://bugzilla.mozilla.org/show_bug.cgi?id=85686
https://jsfiddle.net/AVLCY/1/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/getselection`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/getselection/index.md
* Last commit: https://github.com/mdn/content/commit/cc070123f72376faec06e36622c4fc723a75325f
* Document last modified: 2023-04-08T06:57:07.000Z

</details>

**Comment by Josh-Cena** [comment]
You found a browser inconsistency that's already documented, and this bug is already tracked. We don't control the development of Firefox so there's nothing we can do to expedite the process. The latest comment in that bug has already mentioned that it's a hole in the specification. In this case I don't think anything can be changed about the content: we can only faithfully record the status of the web.
