### ISSUE TITLE
Missing curly braces in code example

### ISSUE THREAD

**Issue by jalal-hejazi** [mdn/content#28409]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/do...while

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

The code example is missing a pair of curly braces

### What did you expect to see?

do {
  statement
} while (condition);

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/do...while`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/do...while
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/do...while/index.md
* Last commit: https://github.com/mdn/content/commit/0f3738f6b1ed1aa69395ff181207186e1ad9f4d8
* Document last modified: 2023-02-21T00:33:34.000Z

</details>

**Comment by Josh-Cena** [comment]
The curly braces are optional. As mentioned in the syntax description, you only need them when you want to put multiple statements.
