### ISSUE TITLE
Example given on blockquote page is incorrect according to the HTML spec

### ISSUE THREAD

**Issue by drastus** [mdn/content#28401]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

The example given places the attribution for the quotation inside `blockquote` element, which incorrect according to the HTML specification.

### What did you expect to see?

The example should place the quotation attribution outside the `blockquote` element, eg. in `figcaption` element:

```
<figure>
  <blockquote cite="https://www.huxley.net/bnw/four.html">
    <p>Words can be like X-rays, if you use them properly—they’ll go through anything. You read and you’re pierced.</p>
  </blockquote>
  <figcaption>—Aldous Huxley, <cite>Brave New World</cite></figcaption>
</figure>
```

### Do you have any supporting links, references, or citations?

The HTML specification (https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element) states: “Attribution for the quotation, if any, must be placed outside the `blockquote` element.” 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/blockquote`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/blockquote/index.md
* Last commit: https://github.com/mdn/content/commit/e04d8d2766c468f149445c0bf438d09f9b2d188c
* Document last modified: 2023-06-13T08:10:47.000Z

</details>

**Comment by Josh-Cena** [comment]
We're back at it again... Before we proceed we should really figure out what the standard practice is. See https://github.com/mdn/interactive-examples/issues/2563.

cc @estelle @aardrian @myfonj should you be interested

**Comment by drastus** [comment]
Placing attribution in `figcaption` is one of the possibilities. If this example causes problems with screen readers, `figcaption` can be replaced with `p`, which is still correct HTML and, I guess, screen readers friendly.

**Comment by aardrian** [comment]
On vacation so this is brief. I edited the current advice. You can read the original issue or read the results of my own SR testing:
https://adrianroselli.com/2023/07/blockquotes-in-screen-readers.html
