### ISSUE TITLE
Inconsistent max size of ArrayBuffer on 32-bit systems

### ISSUE THREAD

**Issue by Sc00bz** [mdn/content#28404]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length

### What specific section or headline is this issue about?

The description, "What went wrong?", and "Valid cases"

### What information was incorrect, unhelpful, or incomplete?

This says "2^31-1 (2GiB-1)":
https://github.com/mdn/content/blob/8fb5853ceee5db8ac6e1c564c6dda4b3f5ec86c5/files/en-us/web/javascript/reference/errors/invalid_array_length/index.md?plain=1#L13
vs

This says "2^32-1 (2GiB-1)" even though that's 4GiB-1:
https://github.com/mdn/content/blob/8fb5853ceee5db8ac6e1c564c6dda4b3f5ec86c5/files/en-us/web/javascript/reference/errors/invalid_array_length/index.md?plain=1#L36
This says "2^32-1 (2GiB-1)" again:
https://github.com/mdn/content/blob/8fb5853ceee5db8ac6e1c564c6dda4b3f5ec86c5/files/en-us/web/javascript/reference/errors/invalid_array_length/index.md?plain=1#L38
This shows 2^32-1 as valid:
https://github.com/mdn/content/blob/8fb5853ceee5db8ac6e1c564c6dda4b3f5ec86c5/files/en-us/web/javascript/reference/errors/invalid_array_length/index.md?plain=1#L72

### What did you expect to see?

Either "2^31-1 (2GiB-1)" or "2^32-1 (4GiB-1)" everywhere for ArrayBuffer max size on 32-bit systems. If I were to guess, I'd think it's suppose to be "2^32-1 (4GiB-1)" vs "2^31-1 (2GiB-1)" and "2^32-1 (2GiB-1)".

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/invalid_array_length`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/invalid_array_length/index.md
* Last commit: https://github.com/mdn/content/commit/6d606174faaedaa5dee7b7ebd87602cd51e5dd7e
* Document last modified: 2023-07-24T23:45:00.000Z

</details>

**Comment by Josh-Cena** [comment]
See https://github.com/mdn/content/pull/7866; the correct value should be 2<sup>31</sup> - 1 (2GiB - 1). PRs welcome.

**Comment by Sc00bz** [comment]
Ah looks like I guessed wrong and fixed it.

**Comment by Sc00bz** [comment]
Sorry I accidentally made a PR to my branch.
