### ISSUE TITLE
Circular wording between SVG and viewBox defining

### ISSUE THREAD

**Issue by gdennie** [mdn/content#28416]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Positions

### What specific section or headline is this issue about?

What are pixels

### What information was incorrect, unhelpful, or incomplete?

The whole SVG canvas here is 200px by 200px in size. However, the viewBox attribute defines the portion of that canvas to display. These 200x200 pixels display an area that starts at user unit (0,0) and spans 100x100 user units to the right and to the bottom. This effectively zooms in on the 100x100 unit area and enlarges the image to double size.

### What did you expect to see?

note sure...

### Do you have anything more you want to share?

The paragraph states that `viewBox` defines the portion of the `canvas` to display while the SVG element defines the canvas. Yet, the SVG element is also magnifying a portion the of the canvas defined by viewBox. Rather circular.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/tutorial/positions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Positions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/tutorial/positions/index.md
* Last commit: https://github.com/mdn/content/commit/b4f998244660723175f8e06b5d77f68cfb1d1f1a
* Document last modified: 2023-03-06T23:38:10.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! There's no circular wording here.

- The whole SVG canvas here is 200px by 200px in size. This is defined by `width="200" height="200"`. The "SVG canvas" is an abstract concept now and the physical value of "1px" is not certain yet. However it defines the coordinate system that all strokes and objects will use.
- However, the viewBox attribute defines the portion of that canvas to display. This is defined by `viewBox="0 0 100 100"`. There's now a smaller "box" put somewhere on this canvas that the user can actually see.
- These 200x200 pixels display an area that starts at user unit (0,0) and spans 100x100 user units to the right and to the bottom. So, we clip everything outside the viewbox, then stretch what's inside the viewbox to the same size as the previous canvas size (controlled by `preserveAspectRatio`).
- This effectively zooms in on the 100x100 unit area and enlarges the image to double size. "This" does not refer to `<svg>`. It refers to the interaction between the `width`/`height` and the `viewBox`. We drew things on a 200x200 canvas, took a 100x100 portion of it, then stretched it to 200x200 again, and that gets displayed.

If you are still confused about `viewBox`, you should read [its reference](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox).
