### ISSUE TITLE
No page for HTMLSelectElement.value

### ISSUE THREAD

**Issue by Sammeeey** [mdn/content#28418]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

### What information was incorrect, unhelpful, or incomplete?

While doing the Svelte tutorial (part: [*Select bindings*](https://learn.svelte.dev/tutorial/select-bindings)), I had difficulties to understand that the `value` attribute of `<selected>` always contains the value of the selected `<option>`.

In fact the [MDN article about the `<select>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) doesn't mention `value` as an attribute of `<select>` nor does it describe the above mentioned relation between the values of `<selected>` & its `<options>`.

### What did you expect to see?

I expected to see...
1. something that doesn't only describe that the options have `value` attributes, but the `<selected>` element as well.
2. a description of the relation between the value of `<selected>` & its `<options>`.

### Do you have any supporting links, references, or citations?

What helped me to understand & try out the relation (as mentioned above) was the interactive example of [w3schools Select value Property](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_select_value).

```html
<!DOCTYPE html>
<html>
<body>

<form>
  Select your favorite fruit:
  <select id="mySelect">
    <option value="apple">Apple</option>
    <option value="orange">Orange</option>
    <option value="pineapple">Pineapple</option>
    <option value="banana">Banana</option>
  </select>
</form>

<p>Click the button to change the selected fruit to banana.</p>

<button type="button" onclick="myFunction()">Try it</button>

<script>
function myFunction() {
  let val = document.getElementById("mySelect").value
  alert(val)             // (*)
}
</script>

</body>
</html>
```

I added the (*)-line so that I could see the changing value of `<selected>` in action (depending on the selected option.

### Do you have anything more you want to share?

I'm sure that the relation between `<select>` and its `<options>` is described somewhere (on a lower level(?)) - probably some article that describes general behavior of form elements.
But (especially for a beginner - like me) it would be super helpful to at least have a link to such an article - or better: a description right in the relation right in this article.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/select`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/select/index.md
* Last commit: https://github.com/mdn/content/commit/07f0cf4375aaa02e1071d8bd0e8518db7609b7a9
* Document last modified: 2023-07-17T23:05:13.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! There's no `value` attribute for `<select>`. There is, however, an IDL property called `value` for `HTMLSelectElement`. This property reflects the value of the `<option>` that is selected. Unfortunately that page hasn't be written yet: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement

As a general principle, IDL attributes and HTML attributes are always separate and we won't excessively compare them to avoid confusion. You will need to read https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#content_versus_idl_attributes to understand more.

**Comment by wbamberg** [comment]
> There is, however, an IDL property called `value` for `HTMLSelectElement`. This property reflects the value of the `<option>` that is selected. Unfortunately that page hasn't be written yet: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement
> 

I believe this is tracked by https://github.com/openwebdocs/project/issues/153
