### ISSUE TITLE
Implicit role for `<summary>` element

### ISSUE THREAD

**Issue by Mintoo200** [mdn/content#28446]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary

### What specific section or headline is this issue about?

[Technical summary](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary#technical_summary)

### What information was incorrect, unhelpful, or incomplete?

The implicit ARIA role for the `<summary>` element is `button`

### What did you expect to see?

I don't know, the spec says that the implicit role is supposed to be `generic` but that many browsers use `button` instead. But chrome uses `generic` and firefox uses `summary`.
Maybe it would be less confusing (given the already very confusing situation) to have a specific message or something ?
Something like what is in the spec : "generic, note that many agents will use the button role instead"

### Do you have any supporting links, references, or citations?

> [No corresponding role](https://w3c.github.io/html-aria/#dfn-no-corresponding-role)
NOTE
Many, but not all, user agents expose the summary element with an implicit ARIA role=[button](https://w3c.github.io/html-aria/#index-aria-button).

-- [specification of the `<summary>` element](https://w3c.github.io/html-aria/#el-summary)

<div>
<figure>
  <img width="488" alt="" src="https://github.com/mdn/content/assets/25901730/829211ac-52b0-4b85-8f61-22debefeb33a">
  <figcaption>Chrome uses `generic` in the form of an implementation specific role `DisclosureTriangle`</figcaption>
</figure>
</div>

<div>
<figure>
  <img width="348" alt="" src="https://github.com/mdn/content/assets/25901730/6ab80ecc-881e-4019-8650-19df1c80bc5d">
  <figcaption>Firefox uses `summary` which is not documented on MDN</figcaption>
</figure>
</div>

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/summary`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/summary/index.md
* Last commit: https://github.com/mdn/content/commit/942a529383ee7ee3996fb234187641c08935f3ff
* Document last modified: 2023-04-13T06:13:15.000Z

</details>

**Comment by Brian-Pob** [comment]
> Firefox uses `summary` which is not documented on MDN

Interesting that Mozilla's docs don't indicate the role that their browser uses.

I would like to take on this issue. I can test this on the some of most common browsers that [CanIUse](https://caniuse.com/?search=summary) checks against and update the docs accordingly.

**Comment by scottaohara** [comment]
there's a misunderstanding here.  "no corresponding role" doesn't mean generic - it just means there is no specific ARIA role that the element maps to.

The role/mapping for HTML elements happens in HTML AAM, not the ARIA in HTML spec.  The technical summary table - which pulls information from the ARIA in HTML spec, should just be updated to reference what the spec says, rather than the outdated implicit aria role that's listed.

Further, the ARIA in HTML spec informatively indicates what the elements' implicit role is.  HTML AAM is the spec is where the actual role is defined - or in this case where there is no corresponding role, where the specific a11y api roles are defined for each platform.

It does seem odd that MDN references the ARIA in HTML spec content, but doesnt link to it in the specifications section.

**Comment by Brian-Pob** [comment]
>  "no corresponding role" doesn't mean generic - it just means there is no specific ARIA role that the element maps to

I did not know this. Thanks for the clarification.

> Further, the ARIA in HTML spec informatively indicates what the elements' implicit role is. HTML AAM is the spec is where the actual role is defined...

I was also not aware of the different a11y related specs for HTML. This was very informational for me who is just starting to learn more about a11y. Thank you for your response!

**Comment by Mintoo200** [comment]
> "no corresponding role" doesn't mean generic

I didn't know that either. In the light of this information I believe there are other issues to open. For instance, the `<div>` element :

> Implicit ARIA role: No corresponding role

— [`<div>`: The Content Division element – MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div#technical_summary)

> role=[generic](https://w3c.github.io/html-aria/#index-aria-generic)

— [Accessibility considerations for authors – W3C](https://w3c.github.io/html-aria/#el-div)

> wai-aria-1.2: generic role

— [HTML AAM – W3C](https://w3c.github.io/html-aam/#el-div)

Just wanted to make sure I understood correctly before I went opening issues willy-nilly.
