### ISSUE TITLE
api.console.assert - Output format detail

### ISSUE THREAD

**Issue by TheBicPen** [mdn/content#28451]
#### What information was incorrect, unhelpful, or incomplete?
On NodeJS v14, the textual representation of objects varies between the 2 forms of `console.assert()`. More detail beyond "This parameter gives you additional control over the format of the output" would be helpful.

#### What did you expect to see?
A mention of the specific differences between the textual representations. In particular that the 2nd form provides more useful printouts in practice.

#### Did you test this? If so, how?
On NodeJS v14.19.0:
```
> console.assert(false, {}); 
Assertion failed: [object Object]
undefined
> console.assert(false, "", {}); 
Assertion failed:  {}
undefined
> console.assert(false, "", JSON.stringify({})); 
Assertion failed:  {}
undefined
```

On Firefox:
![image](https://user-images.githubusercontent.com/23622288/163471694-6b0f7d01-3af2-4e7d-a799-64076a451bb6.png)

<details>
<summary>MDN page report details</summary>

* Query: `api.console.assert`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/console/assert
* Report started: 2022-04-14T20:26:29.165Z

</details>

**Comment by Josh-Cena** [comment]
Closing in favor of the more detailed https://github.com/mdn/content/issues/29172
