### ISSUE TITLE
Are H elements block or inline?

### ISSUE THREAD

**Issue by David263** [mdn/content#28475]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

### What specific section or headline is this issue about?

(not sure)

### What information was incorrect, unhelpful, or incomplete?

There are many characteristics listed for the H elements, but the basic one, whether they are block or inline, doesn't seem to be mentioned at all.

### What did you expect to see?

(the answer, which isn't obvious: it could be either)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/heading_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/heading_elements/index.md
* Last commit: https://github.com/mdn/content/commit/f68fe1eb729010e938a90f6f2bc66512ce3d9a7a
* Document last modified: 2023-07-31T12:45:16.000Z

</details>

**Comment by Arisch24** [comment]
Ok, thank you for letting me know I will work on it.

**Comment by David263** [comment]
I just checked the page, and there is no instance of the string "block" anywhere on it, so this issue is still Open.

**Comment by Arisch24** [comment]
Its appearing for me @David263.

![image](https://github.com/mdn/content/assets/85163746/4e6d422b-7580-46de-98f3-b4b8b1c57a5b)

**Comment by David263** [comment]
I guess I'm not seeing the latest version. But just mentioning "their containing block" is not adequate. There should be a stand-alone statement in the page for every element stating whether it is block-level or inline-level. It is an important and basic fact that greatly affects CSS programming of the 'display' property: blocks extend to the end of the viewport on the right end, and blocks cannot be nested inside of inline elements are two obvious differences. The special category of inline-block is also important, but no elements are inline-block (or flex) by default.
