### ISSUE TITLE
XML error showing on ::marker

### ISSUE THREAD

**Issue by cathrin-will** [mdn/content#28486]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::marker

### What specific section or headline is this issue about?

headline: Try it

### What information was incorrect, unhelpful, or incomplete?

Just below there is an issue instead of whatever it might be showing to do with ::marker we see an error message `This XML file does not appear to have any style information associated with it. The document tree is shown below.`

### What did you expect to see?

An example of ::marker

### Do you have any supporting links, references, or citations?

n/a

### Do you have anything more you want to share?

n/a

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_doublecolon_marker`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::marker
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_marker/index.md
* Last commit: https://github.com/mdn/content/commit/5e7d1f9ae2cce0cb3f7693dfb8dc6e8d375b2231
* Document last modified: 2023-07-18T00:16:24.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising, we'll take a look shortly

**Comment by bsmth** [comment]
Details here: https://github.com/mdn/interactive-examples/pull/2175

**Comment by bsmth** [comment]
Fixed by https://github.com/mdn/interactive-examples/pull/2585
