### ISSUE TITLE
Interface data is not updated automatically anymore

### ISSUE THREAD

**Issue by Elchi3** [mdn/content#28484]
### MDN URL

https://github.com/mdn/content/blob/main/files/jsondata/InterfaceData.json

### What information was incorrect, unhelpful, or incomplete?

In https://github.com/mdn/content/pull/11056 we introduced a process that updates https://github.com/mdn/content/blob/main/files/jsondata/InterfaceData.json automatically.

It looks like the last time this produced a PR was in February?
https://github.com/mdn/content/pull/24856

### What did you expect to see?

More recent PRs that update interface data based on the latest webref package.

**Comment by Elchi3** [comment]
I think the long-term fix here should be to retrieve the data directly from webref and not copy its data into InterfaceData.json, but for now I think it would be good to fix the update script at least.

**Comment by bsmth** [comment]
The error in the workflow is:

```
The specified node version file at: /home/runner/work/content/content/.nvmrc does not exist
```

https://github.com/mdn/content/actions/workflows/interfacedata-updater.yml
