### ISSUE TITLE
Example has inconsistent formatting, hard to see difference between examples

### ISSUE THREAD

**Issue by That-Guy977** [mdn/content#28490]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

Halfway through the example source, the formatting changes, presumably due to the length of the element. This makes it hard to compare or note the differences between each example.

### What did you expect to see?

Consistent formatting that aids in making the example easily understandable.

### Do you have anything more you want to share?

This likely affects multiple other pages with boilerplate-ish element attributes.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/attribute/stroke-dasharray`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/stroke-dasharray/index.md
* Last commit: https://github.com/mdn/content/commit/5f7c22deaa74973658257aeaa012ac2ec0be87ae
* Document last modified: 2023-05-21T00:26:03.000Z

</details>

**Comment by That-Guy977** [comment]
This likely affects multiple other pages with "boilerplate"-ish element attributes

**Comment by That-Guy977** [comment]
Seems like this kind of style of example would fit well with many other examples, lgtm

**Comment by bsmth** [comment]
Super, I've opened a PR to fix this (linked above).
