### ISSUE TITLE
Broken images on example

### ISSUE THREAD

**Issue by leleoalmeida** [mdn/content#28499]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

### What information was incorrect, unhelpful, or incomplete?

Images are broken.

### What did you expect to see?

Apparently the example is broken, and images aren't loading properly

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@media/prefers-color-scheme`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@media/prefers-color-scheme/index.md
* Last commit: https://github.com/mdn/content/commit/c51e0599ea09c0e6d035c635db9f48ad1f241490
* Document last modified: 2023-07-05T05:48:35.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for reporting, there's already an issue for this in Yari https://github.com/mdn/yari/issues/9463

I will close this one so we can track it there.

Thank you :)
