### ISSUE TITLE
Issue with "NSS Tools": Source code not availlable on GitHub

### ISSUE THREAD

**Issue by pruthig** [mdn/content#2849]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/tools

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/projects/nss/tools`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/tools
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/projects/nss/tools/index.html
* Last commit: https://github.com/mdn/content/commit/8c1ca6575872d0de37e76f859e8e535638322bb5
* Document last modified: 2021-02-02T17:19:18.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@pruthig What's the matter with this page?
(If you did not intended to open an issue, please just close it. No hard feelings)
