### ISSUE TITLE
"Using Shadow DOM" has confusing statements about prototype pollution and extensions

### ISSUE THREAD

**Issue by alesandroortiz** [mdn/content#28508]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM

### What specific section or headline is this issue about?

"Basic Usage", paragraph talking about shadow DOM security

### What information was incorrect, unhelpful, or incomplete?

There are at least two confusing or inaccurate statements in the following quoted paragraph. It talks about `attachShadow()` potentially being vulnerable to prototype pollution attacks to force `{mode: "open"}` when a caller might have used `{mode: "closed"}` for security reasons.

> Note that within the same JavaScript realm, this is not a fully secure way to hide the shadow root, because code can override Element.prototype.attachShadow so it always uses mode: "open", as this blog post shows. However, unless you are in an environment where malicious code manipulating globals is a concern, you likely don't have to worry about this. Furthermore, because web extensions don't have access to the window's globals, this still reliably protects the shadow DOM from web extensions.

The paragraph appears to state that a page's shadow DOM API calls are safe from prototype pollution attacks by extensions (`...protects [the web page's] shadow DOM from web extensions`). However, this is **not accurate**.

After looking at the page history, the paragraph was updated to resolve issue #7049 (closed with PR #27449). Seems like the intent of this paragraph was to state that the shadow DOM **of** extensions are protected **from** web pages.
However, this is also **not an accurate statement**, even it the paragraph had been written more clearly to better convey the intended message.

### 1st clarification: Web page's shadow DOM API calls can be manipulated by extensions
A web page's shadow DOM API calls are **not** protected from extensions. Extensions can in fact manipulate the window's globals.

An extension can pollute the prototype for a page before page JS runs when a content script is injected with [`extensionTypes.document_start`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extensionTypes/RunAt). This can be done by either specifying [`scripting.ExecutionWorld.MAIN`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/ExecutionWorld) option in content script configuration or by injecting main-world JS from a content script running in isolated world. (The last one being more dependent on timing.)

### 2nd clarification: Extension shadow DOM API calls can be manipulated by web pages in certain circumstances
Extension JS is not always protected from prototype pollution when using the shadow DOM API. It is only protected if the extension JS is running in an isolated world and uses shadow DOM APIs exclusively within the isolated world. It is not protected if extension JS uses the shadow DOM API in the main world (which is possible via the two main-world-injection methods described in the first clarification).

### New section suggestion
Overall, this security note feels like it should almost be in its own section due to the nuances. A dedicated section can better focus on the different scenarios based on whose DOM is meant to be protected (i.e. based on whether the shadow DOM API is used by a web page or an extension).

### What did you expect to see?

Clearer, more nuanced statements about the security of Shadow DOM API calls.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_components/using_shadow_dom`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_components/using_shadow_dom/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by wbamberg** [comment]
> Extension JS is not always protected from prototype pollution when using the shadow DOM API. It is only protected if the extension JS is running in an isolated world and uses shadow DOM APIs exclusively within the isolated world. It is not protected if extension JS uses the shadow DOM API in the main world (which is possible via the two main-world-injection methods described in the first clarification).

I'm not sure this is true, is it? I was under the impression that at least in Firefox X-ray vision protects extensions from this: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts#xray_vision_in_firefox.

I'm not sure about the other way (i.e. whether web pages are isolated from changes made by content scripts) or what happens in Chrome.

That said I'm not sure what the threat model `mode: "closed"` is supposed to protect people from. I mean if you are in an environment where a hostile party can redefine your prototypes isn't it pretty much game over for anything?

**Comment by wbamberg** [comment]
> A web page's shadow DOM API calls are not protected from extensions. Extensions can in fact manipulate the window's globals.

Agreed. AFAICT an extension will always be able to manipulate a web page, using `"MAIN"` in Chrome or waiving XRay vision in Firefox.

> Extension JS is not always protected from prototype pollution when using the shadow DOM API. It is only protected if the extension JS is running in an isolated world and uses shadow DOM APIs exclusively within the isolated world. It is not protected if extension JS uses the shadow DOM API in the main world (which is possible via the two main-world-injection methods described in the first clarification).

Well, sort of. But this is a deliberate choice by the extension author, to give up protection, isn't it? It's not like a web page can manipulate an extension unless the extension explicitly allows it. So this case seems less clear cut.

> After looking at the page history, the paragraph was updated to resolve issue https://github.com/mdn/content/issues/7049 (closed with PR https://github.com/mdn/content/pull/27449). Seems like the intent of this paragraph was to state that the shadow DOM of extensions are protected from web pages.

Yes, it does seem like https://github.com/mdn/content/issues/7049 wants to be about protecting extensions from web pages, and not vice versa, and the current page doesn't reflect that.

But also I'm wondering: doesn't this whole discussion just collapse into isolated/not isolated worlds? Because I thought that if an (isolated world) extension manipulates the DOM, then its changes aren't visible to the page anyway, whether or not it sets `{mode: "open"}`. So `mode` seems quite irrelevant to this conversation. And, as you say, if an extension waives isolated-worldness, then prototype pollution becomes possible as a means to circumvent `closed`.

So maybe it's better not to characterize `mode` as a security feature at all, more like one that discourages pages from peeking at the internal implementation of a custom element. This also reflects https://hayatoito.github.io/2016/shadowdomv1/#a-closed-shadow-root:

>  Shadow DOM is not a security mechanism. Please do not use Shadow DOM if you want a security. Nothing prevents Element.prototype.attachShadow from being hijacked.
