### ISSUE TITLE
History API pushState size limit for Firefox is given as 640K in one article, and 16 MiB in another

### ISSUE THREAD

**Issue by liuxuelian0929** [mdn/content#28516]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/History/pushState

### What information was incorrect, unhelpful, or incomplete?

[Working with the History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API) this document say that the state object impose a size limit of 640k characters on the serialized representation of a state object.

### What did you expect to see?

Change size limit to correct number.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/history/pushstate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/History/pushState
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/history/pushstate/index.md
* Last commit: https://github.com/mdn/content/commit/a3d9f61a8990ba7b53bda9748d1f26a9e9810b18
* Document last modified: 2023-04-07T00:39:15.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. I’ve opened #28518 with a fix. After that fix is merged, this issue will automatically be marked as resolved, and closed.
