### ISSUE TITLE
Consider moving the gradient and image functions in the structure

### ISSUE THREAD

**Issue by rachelandrew** [mdn/content#2852]
I am working on #2432 and raising some issues for that project.

The gradient functional notations are currently listed directly under CSS/

To make these consistent with other functions (such as the functions for transform-function) they should really be listed under https://developer.mozilla.org/en-US/docs/Web/CSS/gradient

However gradients are also part of image https://developer.mozilla.org/en-US/docs/Web/CSS/image

We have other image functional notations that should, in this scheme, be moved under the image data type. So the options are:

1. Move the image functions `image()` and `image-set()` under `<image>` and move the gradient functions under `<gradient>`.
2. Move the image functions `image()` and `image-set()`, and `<gradient>` under `<image>` and move the gradient functions to under `<gradient>`.
3. Leave it all alone and pretend we haven't seen it.

**Comment by chrisdavidmills** [comment]
I would go for 1. I like the idea of having functions consistently under their related data types, but I don't think creating a multi-level data-types hierarchy is really helpful for users, and it will probably create a bunch of confusion for us in certain situations in the future.

**Comment by rachelandrew** [comment]
That would be my preference but thought I should check in case anyone had any strong feelings in another direction.

**Comment by rachelandrew** [comment]
@chrisdavidmills I've tried to move these using the yarn move command, and it rewrites the slugs and wikihistory, but doesn't move the files or change the redirects file. No error. I get the message "Moved 1 documents".

I'm on Windows... maybe a path issue? 

Can I do this move manually please?

**Comment by chrisdavidmills** [comment]
@fiji-flo hello sir! We've got more problems with yarn contrent move and redirects here. What should Rachel do in this situation?

**Comment by fiji-flo** [comment]
@rachelandrew can you add a comment with the command you ran? Happy to debug this. Also good to know we have more active Windows users!

**Comment by rachelandrew** [comment]
@fiji-flo below is the command and output. This is at the Windows Command Prompt rather than Linux via WSL.

This changed the slug in the file and wikihistory but did not move anything or update redirects.

```
C:\Users\rache\local\mdn\mdn-content>yarn content move "Web/CSS/image()" "Web/CSS/image/image()" en-US
yarn run v1.22.4
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/tool/cli.js move "Web/CSS/image()" "Web/CSS/image/image()" en-US
Will move 1 documents from Web/CSS/image() to Web/CSS/image/image() for en-US
Web/CSS/image/image() → Web/CSS/image/image()
? Proceed? Yes
Moved 1 documents.
Done in 6.75s.
```

**Comment by fiji-flo** [comment]
```
git status
On branch main
Your branch is ahead of 'origin/main' by 1567 commits.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	renamed:    files/en-us/web/css/image()/index.html -> files/en-us/web/css/image/image()/index.html

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   files/en-us/_redirects.txt
	modified:   files/en-us/_wikihistory.json
	modified:   files/en-us/web/css/image/image()/index.html
```

That's the output of `git status` running on `content/main` can you make sure you're up to date using `yarn up-to-date-check`. I'll boot up my Windows to see if it's a platform specific issue.

**Comment by fiji-flo** [comment]
Same result on Windows (Powershell) for me.

**Comment by rachelandrew** [comment]
this is still a problem for me, and I'm up to date, having it now on another issue. Although I do now get an error message of "Cannot read property trim of undefined."

**Comment by fiji-flo** [comment]
@rachelandrew I can reproduce the "Cannot read property trim of undefined.". Looking for the root-cause.

**Comment by fiji-flo** [comment]
@rachelandrew could you update and try again. "Cannot read property trim of undefined." is fixed. And for me it worked on Windows in Power Shell and Command Prompt.

If it still fails can you tell me what git binary you're using?
