### ISSUE TITLE
Masonry page states Firefox exclusive; Safari 17 supports it.

### ISSUE THREAD

**Issue by QINGCHARLES** [mdn/content#28541]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Masonry_layout

### What specific section or headline is this issue about?

Feature is also available in Safari 17 (Beta and Technology Preview)

### What information was incorrect, unhelpful, or incomplete?

Feature is also available in Safari 17 (Beta and Technology Preview)

### What did you expect to see?

> **Warning:** This feature is only implemented in Safari 17 (Beta and Technology Preview), and in Firefox, where it can be enabled by setting the flag `layout.css.grid-template-masonry-value.enabled` to `true` in `about:config`, in order to allow testing and providing of feedback.

### Do you have any supporting links, references, or citations?

See all references here:

https://github.com/mdn/browser-compat-data/issues/19080

### Do you have anything more you want to share?

Proposed text:

> **Warning:** This feature is only implemented in Safari 17 (Beta and Technology Preview), and in Firefox, where it can be enabled by setting the flag `layout.css.grid-template-masonry-value.enabled` to `true` in `about:config`, in order to allow testing and providing of feedback.

**Comment by hamishwillee** [comment]
Thanks. Should be fixed by https://github.com/mdn/content/pull/28546
