### ISSUE TITLE
"nth-child" is, surprisingly, applied to the child, not the parent

### ISSUE THREAD

**Issue by David263** [mdn/content#28544]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child

### What specific section or headline is this issue about?

(unsure)

### What information was incorrect, unhelpful, or incomplete?

Even after I read this article several times, I still thought that this operator selected the nth child of a given parent. It is the obvious conclusion from the name "nth-child".

### What did you expect to see?

There needs to be a clarification that what this operator does is, given the child of a parent, selects (detects) whether that child is the nth child of the parent. Therefore, this operator operates on the child, not the parent node.

If you want a specific css rule to run when the nth child of a parent is hovered over, for example, you must write n separate statements, the first of which is `parent>child:nth-child(1):hover {}`. This example should appear in this article.

### Do you have any supporting links, references, or citations?

(No; I discovered this by discussing a time-consuming CSS programming error of mine with ChatGPT, then experimenting).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_nth-child`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_nth-child/index.md
* Last commit: https://github.com/mdn/content/commit/764b291098cfe575374580844f1a91e7d814a8d3
* Document last modified: 2023-06-21T22:40:10.000Z

</details>

**Comment by OnkarRuikar** [comment]
> If you want a specific css rule to run when the nth child of a parent is hovered over, for example, you must write n separate statements, the first of which is parent>child:nth-child(1):hover {}. 

Using the latest [:has()](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) pseudo-class parent class can be selected `parent:has(child:hover)`. Depending on your use case you don't have to write n rules: https://jsfiddle.net/0z6r731a/8/

**Comment by David263** [comment]
I'm not sure why this Issue has been closed. My request for clarification of the article has not yet been done.

**Comment by estelle** [comment]
the PR is merged. It will not be live until tomorrow.

**Comment by David263** [comment]
Is it live yet? I don't know how to get informed.

**Comment by bsmth** [comment]
@David263 there is a nightly build, which means you will have to wait up to 24 hours to see your changes. See https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests

>Viewing published changes: Content updated on mdn/content goes live within a day of merging via a site rebuild once every 24 hours.
