### ISSUE TITLE
<input type="range">: slider-vertical to be removed from Chrome

### ISSUE THREAD

**Issue by stevennyman** [mdn/content#28550]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

### What specific section or headline is this issue about?

Creating vertical range controls (under 'Examples')

### What information was incorrect, unhelpful, or incomplete?

The `slider-vertical` CSS property will apparently be removed from Chrome.

There is also a section that describes usage of `writing-mode: bt-lr`, which, according to the "Putting it all together" section, only applies for Pre-Blink Edge.

### What did you expect to see?

It is not clear how to create a vertical slider in a way that would continue to render correctly in the future across all browsers.

It would also be helpful to note the pending removal of `slider-vertical` in the "Non-standard keywords" section of https://developer.mozilla.org/en-US/docs/Web/CSS/appearance#syntax

### Do you have any supporting links, references, or citations?

https://github.com/w3c/csswg-drafts/issues/8743

On pages with a vertical slider, the Chrome console shows: `The keyword 'slider-vertical' specified to an 'appearance' property is not standardized. It will be removed in the future.`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/range`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/range/index.md
* Last commit: https://github.com/mdn/content/commit/e04d8d2766c468f149445c0bf438d09f9b2d188c
* Document last modified: 2023-06-13T08:10:47.000Z

</details>

**Comment by wbamberg** [comment]
See also https://github.com/mdn/content/pull/32142.

**Comment by Josh-Cena** [comment]
I'm not sure if there's anything else to be done, as BCD documents the removal and the content mentions this is intended to support old browsers. Considering it fixed by https://github.com/mdn/content/pull/32142.
