### ISSUE TITLE
ResizeObserverEntry: Wrong definition of instance properties

### ISSUE THREAD

**Issue by tobiu** [mdn/content#28589]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry

### What specific section or headline is this issue about?

top level definition plus example

### What information was incorrect, unhelpful, or incomplete?

borderBoxSize & contentBoxSize are described as objects, but inside browser implementations (tested in chrome, firefox & safari)

devicePixelContentBoxSize  is described as an object, but inside browser implementations (tested in chrome & firefox, safari not there yet)

<img width="511" alt="Screenshot 2023-08-16 at 20 26 13" src="https://github.com/mdn/content/assets/1177434/5c7dd856-a58a-4a7e-8031-c2ec2b7e382d">

### What did you expect to see?

borderBoxSize, contentBoxSize & devicePixelContentBoxSize getting described as arrays.

inside the example, the code breaks: `entry.contentBoxSize.inlineSize` instead of `entry.contentBoxSize[0].inlineSize`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/resizeobserverentry`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/resizeobserverentry/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

See also https://github.com/mdn/content/issues/18818, https://github.com/mdn/content/issues/22799, https://github.com/mdn/content/pull/5853/. It looks like we missed this page though.
