### ISSUE TITLE
Misplacement of content

### ISSUE THREAD

**Issue by 0xkrnn** [mdn/content#28621]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON

### What information was incorrect, unhelpful, or incomplete?

I think **working with json** branch was in wrong place could you verify that.

### What did you expect to see?

Change the woring with json to another place

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/json`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/json/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by Josh-Cena** [comment]
I don't quite get what's wrong here, but I can verify that it's in the right place.
