### ISSUE TITLE
Consider change in terminology

### ISSUE THREAD

**Issue by evolutionxbox** [mdn/content#28620]
On the following line, the term "dictionary" is used, but this term is not effectively defined elsewhere in the documentation and likely relies on the user having previously learned the term from a non-JavaScript based language.

https://github.com/mdn/content/blob/51af37123c2eec86e517e6a4cea5e3c30d534a5e/files/en-us/web/api/fetch_api/using_fetch/index.md#L461

May we change this to be "object" since that is more consistent with the JavaScript language?

**Comment by hamishwillee** [comment]
Thanks. Should be fixed in #28637
