### ISSUE TITLE
Undefined terminology, with no link

### ISSUE THREAD

**Issue by David263** [mdn/content#28626]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translateY

### What specific section or headline is this issue about?

Mostly in the Try It section

### What information was incorrect, unhelpful, or incomplete?

There are a number of advanced mathematical terms that are used without either a definition, a link to further information, or an asterisk to further information. These include the following: "Homogeneous coordinates on ℝℙ^3" and "the ordinate of the translating vector". I have a reasonable grasp of math, yet I have no idea what these might mean.

I know it is fun to show off your knowledge, MDN. But you also have a mandate to be helpful to readers with a reasonable level of education. You need a separate page to explain terms like these **in depth**, with links to that page wherever you use such terminology.

### What did you expect to see?

I expected definitions, links to further information, or asterisks to further information.

### Do you have any supporting links, references, or citations?

I wish I could point to good documentation, but I've never heard of this terminology myself. If I had to guess, I would say it has something to do with the brain-heavy SVG technology. Just a guess, though.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/transform-function/translatey`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translateY
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/transform-function/translatey/index.md
* Last commit: https://github.com/mdn/content/commit/b82ff59aab7883b7bb2222cf9f9f9b6eed818e08
* Document last modified: 2023-02-21T06:13:19.000Z

</details>

**Comment by Josh-Cena** [comment]
The idea of `translateY` by itself is simple, and these just provide additional insights for people already familiar with transformations. If one doesn't get the terms, it's not a big deal as the intuition is already there. It's okay to link to Wikipedia for these pages if needed.

**Comment by David263** [comment]
That is all obvious. My issue stands. Here's a little more explanation: most MDN pages are clear and self-contained. This issue is a rare case where MDN does not do its job well. It can and should be fixed. Agreed?

**Comment by Josh-Cena** [comment]
Indeed. As I said—a Wikipedia link for each header would be helpful here.

**Comment by David263** [comment]
I'm afraid I must disagree. Wikipedia has different standards from MDN. But if WP does have the perfect explanation for each of these terms, then WP would be acceptable. I don't have the time to do that research; quite busy with a project.
