### ISSUE TITLE
"Report the content Issue" is not gramatically correct.

### ISSUE THREAD

**Issue by aim12340** [mdn/content#28622]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::target-text

### What specific section or headline is this issue about?

Found a content problem with this page?

### What information was incorrect, unhelpful, or incomplete?

[Report the content issue](https://github.com/mdn/content/issues/new?template=page-report.yml&mdn-url=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FCSS%2F%3A%3Atarget-text&metadata=%3C%21--+Do+not+make+changes+below+this+line+--%3E%0A%3Cdetails%3E%0A%3Csummary%3EPage+report+details%3C%2Fsummary%3E%0A%0A*+Folder%3A+%60en-us%2Fweb%2Fcss%2F_doublecolon_target-text%60%0A*+MDN+URL%3A+https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FCSS%2F%3A%3Atarget-text%0A*+GitHub+URL%3A+https%3A%2F%2Fgithub.com%2Fmdn%2Fcontent%2Fblob%2Fmain%2Ffiles%2Fen-us%2Fweb%2Fcss%2F_doublecolon_target-text%2Findex.md%0A*+Last+commit%3A+https%3A%2F%2Fgithub.com%2Fmdn%2Fcontent%2Fcommit%2F5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e%0A*+Document+last+modified%3A+2023-02-21T06%3A49%3A52.000Z%0A%0A%3C%2Fdetails%3E).

### What did you expect to see?

"Report the content Issue" is not gramatically correct.

The text of this link would be better as "Report a content issue" or "Report an issue with the content".

Just reporting it for the irony :)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_doublecolon_target-text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::target-text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_target-text/index.md
* Last commit: https://github.com/mdn/content/commit/5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e
* Document last modified: 2023-02-21T06:49:52.000Z

</details>

**Comment by Josh-Cena** [comment]
"The content issue" refers to "a content problem" that you "found with this page".

**Comment by aim12340** [comment]
I understand that, but it's bad wording.

It says that there is an error on the page, and that there is only one error.  By saying "The content issue", you are telling me that "The content issue" exists.

It's the same difference as between "Report the problem" and "Report a problem".

**Comment by Josh-Cena** [comment]
This section is nested under the title "found a problem with this page?", so everything indeed assumes you already found a problem :)

**Comment by aim12340** [comment]
OK, in that contect it does make sense thanks.
