### ISSUE TITLE
Issue with explanations, and  order of tokens 

### ISSUE THREAD

**Issue by CBID2** [mdn/content#28636]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

### What information was incorrect, unhelpful, or incomplete?

While I was working on a PR to solve this [issue](https://github.com/mdn/content/issues/20180), @dipikabh pointed out that there were some organizational issues. 

### What did you expect to see?

Fuller explanations 

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete

**Comment by bsmth** [comment]
I think we're missing some context on what's missing exactly. Do you have other information about the problem?

**Comment by CBID2** [comment]
> I think we're missing some context on what's missing exactly. Do you have other information about the problem?

I don't know @bsmth. @dipikabh, brought up this issue, so I'm hoping they'll elaborate on this.

**Comment by dipikabh** [comment]
Hello @CBID2. As previously mentioned in the [last PR](https://github.com/mdn/content/pull/28509#pullrequestreview-1581091235), I noticed that our documentation could benefit from additional details about sections, tokens, and their order in the [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) attribute page.

This concern was also highlighted in the [original issue](https://github.com/mdn/content/issues/20180):

> It’s not even clear that the autocomplete attribute accepts a token list

and

> An explanation that one can use sections in the attribute

If it's possible for you to enhance the existing documentation based on the spec, that would be wonderful. However, if you have other priorities, feel free to close this issue and focus on other open issues.

**Comment by CBID2** [comment]
> Hello @CBID2. As previously mentioned in the [last PR](https://github.com/mdn/content/pull/28509#pullrequestreview-1581091235), I noticed that our documentation could benefit from additional details about sections, tokens, and their order in the [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) attribute page.
> 
> 
> 
> This concern was also highlighted in the [original issue](https://github.com/mdn/content/issues/20180):
> 
> 
> 
> > It’s not even clear that the autocomplete attribute accepts a token list
> 
> 
> 
> and
> 
> 
> 
> > An explanation that one can use sections in the attribute
> 
> 
> 
> If it's possible for you to enhance the existing documentation based on the spec, that would be wonderful. However, if you have other priorities, feel free to close this issue and focus on other open issues.

Thanks for clarifying @dipikabh. I'll work on it :)

**Comment by dipikabh** [comment]
> Thanks for clarifying @dipikabh. I'll work on it :)

Awesome!

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/32789
