### ISSUE TITLE
vertical writing for the text

### ISSUE THREAD

**Issue by ariwijaya075** [mdn/content#28642]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode

### What specific section or headline is this issue about?

the vertical texts

### What information was incorrect, unhelpful, or incomplete?

About the sideways-rl and sideways-lr in the css styling. In my google chrome it doesn't work. But that's not the main problem here.

Further scrolling down, i saw that the in the list of supported browsers, the browser titles inside the table are written in a vertical position that i wanted to use and it's even display in my google chrome as the author intended (instead of keep being written horizontally like other examples), but there's NO ANY documentation regarding it. 

### What did you expect to see?

Please provide how you write those "supported browsers" titles in a vertical manner. In which it keeps being written vertically even in chrome

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/writing-mode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/writing-mode/index.md
* Last commit: https://github.com/mdn/content/commit/fab1f9cef824066b3ce6a5b25f6c6db539f5d042
* Document last modified: 2023-07-18T00:07:20.000Z

</details>

**Comment by wbamberg** [comment]
It looks like it uses `transform: rotate(180deg);`:

<img width="295" alt="Screen Shot 2023-08-18 at 12 00 40 AM" src="https://github.com/mdn/content/assets/432915/79b68dd8-4059-472a-8fb9-947df3d9c487">

**Comment by bsmth** [comment]
Thanks for opening the issue @ariwijaya075 and for the response, Will. 

I think we can add a new example at the end that shows how this works:

- [ ] https://github.com/mdn/content/pull/28645

There's also a codepen here: https://codepen.io/bsmth/pen/eYbYgjg


I hope that answers your question!
