### ISSUE TITLE
`URLSearchParams.prototype[@@iterator]()` is missing

### ISSUE THREAD

**Issue by fisker** [mdn/content#28640]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams

### What information was incorrect, unhelpful, or incomplete?

Should add a page for it like [`Map.prototype[@@iterator]()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/@@iterator)

### What did you expect to see?

Documentation for `URLSearchParams.prototype[@@iterator]()`.

**Comment by Josh-Cena** [comment]
Web APIs do not document well-known symbols because they are implementation details. The landing page already explicitly documents that it's iterable, so I think this is all good and follows our guidelines. We may make all of this more structured in the future; see https://github.com/openwebdocs/project/issues/159

**Comment by fisker** [comment]
Kind of miss leading that there is no `@@iterator` on left side under `Instance methods`. I thought it's not iterable..。

**Comment by Josh-Cena** [comment]
Web APIs in general tend to be more high-level and focus on the majority of use cases. For example, we may assume that an average developer neither knows what `@@iterator` means nor how an iterable object should be iterated, so spelling it out on the landing page is perhaps more pragmatic.

**Comment by fisker** [comment]
Good to know, I'll try to read the text instead of search for `@@iterator`. 😄

**Comment by fisker** [comment]
@Josh-Cena A off topic question.

Unlike `@@iterator` it's normally simple enough to explain with a code block, the up coming `@@dispose` may need a page to explain what have done for complex web stuff. Will we consider document it in future? (Since you said "Web APIs do not document well-known symbols")

**Comment by Josh-Cena** [comment]
That's a good question! My feeling is that we don't usually worry about cleanup logic to start with, so maybe not. At most we would have an example saying "you should probably use `using` so it gets properly cleaned up". But I'm not a web API author and the decision is far from finalized, so don't take my word for it 😄

**Comment by fisker** [comment]
Thank you!
