### ISSUE TITLE
RTCDataChannel Syntax > JS Example lists incorrect method

### ISSUE THREAD

**Issue by zsteele-openeye** [mdn/content#28650]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/closing_event

### What specific section or headline is this issue about?

Syntax > JS Example

### What information was incorrect, unhelpful, or incomplete?

The Syntax > JS Example lists "onbufferedamountlow" instead of "onclosing"

### What did you expect to see?

I expected the example to show "onclosing"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/rtcdatachannel/closing_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/closing_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/rtcdatachannel/closing_event/index.md
* Last commit: https://github.com/mdn/content/commit/954612667bafd71241a93e8554e8f11afc474ff3
* Document last modified: 2023-04-07T19:50:09.000Z

</details>

**Comment by bsmth** [comment]
Hi @zsteele-openeye - thanks for raising this one, and it looks like you're right. Would you like to open a pull request to fix this?

**Comment by zsteele-openeye** [comment]
@bsmth , I'll give it a shot. This is my first time doing this, may need some help getting it right.

**Comment by bsmth** [comment]
Thanks for reporting and fixing, welcome aboard!
