### ISSUE TITLE
AudioContext api increases db level on AudioContext resume

### ISSUE THREAD

**Issue by KO81** [mdn/content#28657]
Hello.
This issue only exists on mozilla based browsers. the AudioContext db level or volume level increases on AudioContext resume. even if i set the maxDecibels to 0 and channelInterpretation to 'discrete'. is there mozilla fix for it? any help would be kind.

**Comment by KO81** [comment]
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0 with webgpu enabled

**Comment by Josh-Cena** [comment]
We don't develop Firefox. Please send this issue to https://bugzilla.mozilla.org/home.
