### ISSUE TITLE
Formal definition of text-wrap missing

### ISSUE THREAD

**Issue by the-bokya** [mdn/content#28662]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap

### What specific section or headline is this issue about?

Formal definition

### What information was incorrect, unhelpful, or incomplete?

It is empty and shows the following error as content: "Value not found in DB!"

### What did you expect to see?

Formal definition of the css property.

### Do you have any supporting links, references, or citations?

The problem is [here](https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap#formal_definition)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/text-wrap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/text-wrap/index.md
* Last commit: https://github.com/mdn/content/commit/55f0d5d6ab74b22b3298ea33c10fabdbd996ce93
* Document last modified: 2023-07-12T15:05:03.000Z

</details>

**Comment by OnkarRuikar** [comment]
Will be automatically fixed, in a day or two, after https://github.com/mdn/data/releases/tag/v2.0.33 is updated in `mdn/yari` and goes live on MDN site.

**Comment by Josh-Cena** [comment]
Fixed now
