### ISSUE TITLE
Example is unfinished

### ISSUE THREAD

**Issue by skyfighteer** [mdn/content#28660]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form

### What specific section or headline is this issue about?

the final example

### What information was incorrect, unhelpful, or incomplete?

If you look at the HTML of the last example, the editor forgot to remove the `"<form> ... </form>"` at the end, and put the actual inputs inside.

### What did you expect to see?

What was written in the example.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/how_to_structure_a_web_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_structure_a_web_form/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this one @skyfighteer - there should be a fix incoming in the linked PR 👍🏻
