### ISSUE TITLE
Incorrect internal link in the CSS transform reference page

### ISSUE THREAD

**Issue by harounach** [mdn/content#28661]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/transform

### What specific section or headline is this issue about?

Transform order

### What information was incorrect, unhelpful, or incomplete?

When clicking on the "applied in order from right to left" link in the "values" under "Syntax" does not jump to the "Transform order"  title.

The problem is the incorrect URL fragment "#transform-order" instead of "#transform_order".

### What did you expect to see?

When clicking on the "applied in order from right to left" link jump to the "Transform order" section

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/transform`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/transform/index.md
* Last commit: https://github.com/mdn/content/commit/fab1f9cef824066b3ce6a5b25f6c6db539f5d042
* Document last modified: 2023-07-18T00:07:20.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you - Onkar fixed this in @28665
