### ISSUE TITLE
Screen global coordinates definition needed

### ISSUE THREAD

**Issue by David263** [mdn/content#28676]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/screenX

### What specific section or headline is this issue about?

(several sections)

### What information was incorrect, unhelpful, or incomplete?

There is no good definition here for "screen/global coordinates". Does it refer to the computer screen? Does it refer to the browser viewport? Is it, as usual, increasingly negative to indicate the down direction, starting from 0 at the top? An MDN article should not leave the reader asking such questions, when (I assume) they can be answered simply and clearly.

### What did you expect to see?

A clear definition of screen coordinates for screenX and screenY, and similarly for the other types of coordinate systems used by mouse events.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mouseevent/screenx`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/screenX
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mouseevent/screenx/index.md
* Last commit: https://github.com/mdn/content/commit/ef75c1741b450c2331204be5563ee964ad5f4c48
* Document last modified: 2023-04-07T06:16:45.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting this one @David263 - screen coordinates is defined here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSSOM_view/Coordinate_systems and global is possibly adding some confusion. I've proposed some changes in the linked PR above which I hope clears that up.
