### ISSUE TITLE
Chrome intents to remove non-standard appearance keywords

### ISSUE THREAD

**Issue by 1jj** [mdn/content#28687]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/appearance

### What specific section or headline is this issue about?

Non-standard keywords

### What information was incorrect, unhelpful, or incomplete?

See
https://groups.google.com/a/chromium.org/g/blink-dev/c/gfxScdL8O3g/m/ZY9CbTdNBAAJ

Some of the keywords to remove are listed as "Non-standard keywords" (this list seems incomplete anyway).
There is no info what thouse do currently (same as `auto`?). Seems this needs some update after removing.

j.j.

### What did you expect to see?

.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/appearance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/appearance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/appearance/index.md
* Last commit: https://github.com/mdn/content/commit/42c1bb8c259f3f57de9f38600776cf273e3addda
* Document last modified: 2023-02-21T06:27:49.000Z

</details>

**Comment by OnkarRuikar** [comment]
[Feature: Remove non-standard appearance keywords](https://chromestatus.com/feature/5066630972833792)

> a console warning will be shown, but the keyword **will be recognized as a valid value**.

Shouldn't we wait till they are completely gone (not in dev trials, behind flag)?

**Comment by stevennyman** [comment]
See also #28550 which is affected by the removal of one of these keywords

**Comment by hamishwillee** [comment]
> Shouldn't we wait till they are completely gone (not in dev trials, behind flag)?

I tend to agree. Once that happens isn't the process to wait 2 years before removing content? If so, I'd go through the list and for chrome entries update to "Chrome < 115" (or similar). Not sure it is worth making the list accurate though by adding the missing items.

Good news is that none of these are in the compatibility data so don't have to update that.

**Comment by bsmth** [comment]
Thanks for flagging this.

>I'd go through the list and for chrome entries update to "Chrome < 115" (or similar). 

I think this is a good idea. I've recently touched this page, so I'm assigning myself to test the values and add some info on support.
