### ISSUE TITLE
Issue with "Element.getElementsByTagName()": (short summary here please)

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#2868]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element

#### What information was incorrect, unhelpful, or incomplete?
The left-side list of pages/articles has every link duplicated.  E.g.,
ariaAtomic
ariaAtomic

This is on every page Element page.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/getelementsbytagname`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagName
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/getelementsbytagname/index.html
* Last commit: https://github.com/mdn/content/commit/56d9a678477f0e79232caa8169114519bf02a44a
* Document last modified: 2021-02-19T19:41:18.000Z

</details>

**Comment by sideshowbarker** [comment]
heads-up @mdn/core-yari-content

**Comment by Ryuno-Ki** [comment]
Already addressed in https://github.com/mdn/yari/issues/3119 with an open PR https://github.com/mdn/yari/pull/3131

**Comment by sideshowbarker** [comment]
Closing as a duplicate per https://github.com/mdn/content/issues/2868#issuecomment-791204537.

**Comment by sideshowbarker** [comment]
@JustinWebDev Thanks for catching this and reporting it — if you’re keen to know when the fix for this lands, please follow mdn/yari#3131
