### ISSUE TITLE
"Define your app icons" uses themed icons for its maskable icon example, rather than shaped adaptive icons

### ISSUE THREAD

**Issue by NotWoods** [mdn/content#28681]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Define_app_icons

### What specific section or headline is this issue about?

Support masking

### What information was incorrect, unhelpful, or incomplete?

The Android screenshot showcases a homescreen using [monochrome icons](https://w3c.github.io/manifest/#monochrome-icons-and-solid-fills), not [maskable icons](https://w3c.github.io/manifest/#icon-masks). But while monochrome icons are specced, they haven't been implemented in Chrome yet for homescreen icons. (Only for shortcut icons in Android and Chrome OS.)

![The Android 13 home screen, showing circular and color themed app icons](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Define_app_icons/android-13-home-screen.png)

On Android, "adaptive icons" refers to icons adapting to both shape and color. Maskable icons correspond to [different shapes](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#different-shapes), whereas monochrome icons correspond to [color selection](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming).

### What did you expect to see?

I figure the docs should either:
- use a different screenshot and remove the text around "themed" Android icons, which corresponds to monochrome
- add details about monochrome and how it will be used for themed icons with a note that it's not available on Chrome yet

### Do you have any supporting links, references, or citations?

- https://w3c.github.io/manifest/#monochrome-icons-and-solid-fills
- https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

### Do you have anything more you want to share?

Monochrome icon support is a bit difficult to represent right now. Last I checked,
- it is supported for shortcut/right click/long press icons in Android and Chrome OS
- it is supported for notification icons in Chrome OS
- it is not supported for homescreen/launcher/app icons
- it is not supported for Windows jump menu/right click icons

**Comment by captainbrosset** [comment]
Thinking about it some more, I'm of the opinion that we should go with your first approach: remove mentions of themes, remove the unrelated screenshot, and make sure this section is purely about masks. 
As for adding another section about monochrome, I don't think we should do it, since it's not supported anywhere yet.
I'll provide a PR soon.
