### ISSUE TITLE
HTMLElement.dataset: using the `in` operator is unsafe

### ISSUE THREAD

**Issue by imdfl** [mdn/content#28693]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset

### What specific section or headline is this issue about?

Accessing Values

### What information was incorrect, unhelpful, or incomplete?

The `in` operator is exposed to the usual risk of prototype pollution, so anything added to Object.prototype and other classes in the inheritance chain of `DOMStringMap` will be `in` the dataset but not in `hasOwnProperty` .

### What did you expect to see?

Change `in` to `hasOwnProperty` or add a caveat.

### Do you have any supporting links, references, or citations?

```javascript
	Object.prototype.bad = function() { console.log("bad prop")};
	var e = document.body.querySelector("#test"); // <span id="test" data-man="1">
	console.log("man", "man" in e.dataset, "bad", "bad" in e.dataset); // man true, bad true
	console.log("man", e.dataset.hasOwnProperty("man"), 
            "bad", e.dataset.hasOwnProperty("bad"));// man true, bad false

```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/dataset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/dataset/index.md
* Last commit: https://github.com/mdn/content/commit/a3d9f61a8990ba7b53bda9748d1f26a9e9810b18
* Document last modified: 2023-04-07T00:39:15.000Z

</details>

**Comment by Josh-Cena** [comment]
Yes let's both add a `Object.hasOwn` example (avoid using `hasOwnProperty`, if you are worried about prototypical pollution) and add a caveat to the `in` example. Using `in` still seems more natural and "mostly" safe.

**Comment by imdfl** [comment]
If "mostly" safe is a legit criterion for production, I can probably close half the issues currently assigned to me across my projects... Anyway, thanks for taking note.

**Comment by Josh-Cena** [comment]
To make `in` unsafe, you have to either (a) have untrusted code running on your webpage that may modify prototypes or (b) be using a dynamic string key not controlled by you. The second isn't the case for this example, and if you enter the realm of (a) you have a whole lot of other troubles to deal with (e.g. `array.map((x) => x)` would not be safe either), so we usually don't assume that happens.
