### ISSUE TITLE
Demo link broken

### ISSUE THREAD

**Issue by CredAbility** [mdn/content#28700]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebOTP_API

### What specific section or headline is this issue about?

Link The for "Try this demo using a phone"

### What information was incorrect, unhelpful, or incomplete?

It's a link to a glitch page

### What did you expect to see?

A link to a phone demo

### Do you have any supporting links, references, or citations?

The link is https://web-otp.glitch.me/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webotp_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebOTP_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webotp_api/index.md
* Last commit: https://github.com/mdn/content/commit/7468f701870fbff4f845f8d39d8bc2f17b3636ce
* Document last modified: 2023-08-03T08:44:56.000Z

</details>

**Comment by Josh-Cena** [comment]
We'll track this in https://github.com/mdn/content/issues/25349. This example was at least accessible two months ago, but now it's not just nonfunctional (as reported), but unavailable :)
