### ISSUE TITLE
2 identical links in "See also" section of "Responsive web design"

### ISSUE THREAD

**Issue by EzioMercer** [mdn/content#28722]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Responsive_web_design

### What specific section or headline is this issue about?

See also

### What information was incorrect, unhelpful, or incomplete?

In the "See also" section we have 2 identical links:

+ [Summary and resources](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps)
+ [Pros and cons of going responsive](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps)

### What did you expect to see?

I expect to see one of them or have 2 different links

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/responsive_web_design`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Responsive_web_design
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/responsive_web_design/index.md
* Last commit: https://github.com/mdn/content/commit/ada5fa5ef15eadd44b549ecf906423b4a2092f34
* Document last modified: 2023-06-08T13:19:16.000Z

</details>

**Comment by bsmth** [comment]
Thanks for flagging, @EzioMercer - I will have a shot at fixing 👍🏻
