### ISSUE TITLE
Incorrect return value for OfflineAudioContext.startRendering

### ISSUE THREAD

**Issue by Allie-Howe** [mdn/content#28732]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/startRendering

### What specific section or headline is this issue about?

Return value

### What information was incorrect, unhelpful, or incomplete?

The return value is listed as "None (undefined)"

### What did you expect to see?

"A [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) resolving to an [AudioBuffer](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer)"

### Do you have any supporting links, references, or citations?

The 'Examples' section below 'Return value', states that "When the startRendering() promise resolves, rendering has completed and the output AudioBuffer is returned out of the promise."

### Do you have anything more you want to share?

<img width="648" alt="image" src="https://github.com/mdn/content/assets/32961755/e7ebadc1-9c44-40f0-9bae-8b366f05b3af">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/offlineaudiocontext/startrendering`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/startRendering
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/offlineaudiocontext/startrendering/index.md
* Last commit: https://github.com/mdn/content/commit/312081aabba3885b35a81107b3c2fc53428896c5
* Document last modified: 2023-04-07T06:19:30.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. THis should be fixed by https://github.com/mdn/content/pull/28742
