### ISSUE TITLE
Explain why tabindex may not be used on the dialog element

### ISSUE THREAD

**Issue by jespertheend** [mdn/content#28750]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

### What specific section or headline is this issue about?

The red warning at the top.

### What information was incorrect, unhelpful, or incomplete?

There's a big scary warning saying
> *Warning:* The `tabindex` attribute must not be used on the `<dialog>` element.

But this is rather unhelpful, because it doesn't explain what the consequences are of doing this. It's also a bit ambiguous whether you shouldn't use `tabindex` on the `<dialog>` element itself or on any element inside of it. Though I reckon it's the former.

### What did you expect to see?

An explanation of what the downsides are of using `tabindex`, or no warning at all.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/dialog/index.md
* Last commit: https://github.com/mdn/content/commit/e04d8d2766c468f149445c0bf438d09f9b2d188c
* Document last modified: 2023-06-13T08:10:47.000Z

</details>

**Comment by jespertheend** [comment]
Seems like this was added in #22480 because it's in the spec. But I wonder why the spec says this.

**Comment by jespertheend** [comment]
The only thing I could find about it was this: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24714
But I'm still not sure what this means. Most browsers are particularly lax when it comes to non conforming pages.

**Comment by wbamberg** [comment]
@estelle , can you help with this?
