### ISSUE TITLE
Document syntax restrictions for functional `id`s

### ISSUE THREAD

**Issue by cw118** [mdn/content#28752]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector

### What specific section or headline is this issue about?

Syntax -> Exceptions (or wherever the information should go)

### What information was incorrect, unhelpful, or incomplete?

A contributor on translated-content (@AppyGG) asked about adding an example to the `querySelector` page to explain how to deal with CSS `id`s that start with a number.

### What did you expect to see?

If possible, a note, example, or some sort of mention regarding this special case. Below is the example proposed by @AppyGG in mdn/translated-content#14872, though I think it could also be helpful to give an example of how to escape `id`s starting with a number as explained in [this StackOverflow post/answer](https://stackoverflow.com/questions/20306204/using-queryselector-with-ids-that-are-numbers):

> **Note :** If the selector selects an `id` and this `id` starts with a number (0-9), a syntax error is returned.

```html
<div id="0123"></div>
<div id="abcd"></div>

<script>
  document.querySelector("#0123"); // syntax error
  document.querySelector("#abcd"); // selects the second div
</script>
```

### Do you have any supporting links, references, or citations?

From the translated-content PR:

- [StackOverflow discussion about this problem](https://stackoverflow.com/questions/20306204/using-queryselector-with-ids-that-are-numbers)
- [W3Docs about HTML5 IDs](https://www.w3docs.com/snippets/html/which-are-the-valid-values-for-the-id-attribute.html#:~:text=In%20HTML5%2C%20the%20id%20attribute,id%20attribute%20is%20case%20sensitive.)

### Do you have anything more you want to share?

cf. mdn/translated-content#14872 for the related pull request.

**Comment by cw118** [comment]
Hi @mdn/yari-content-web-api, any feedback on this?

**Comment by AppyGG** [comment]
Hi, do you want me to open a pull request with the changes mentioned before ?

**Comment by cw118** [comment]
> Hi, do you want me to open a pull request with the changes mentioned before ?

That would be great, yes! We may receive feedback sooner on the PR than on this issue. Let me know if help is needed :)

**Comment by wbamberg** [comment]
Thanks for the nudge, @cw118 !

We should document this but I'm not sure where would be best. If my understanding is right, the issue is that while (for example) "123" is a valid value for an HTML `class` attribute, it's not valid in a CSS selector, so it must be escaped. 

So if we only fix this in the web/API docs, we have to fix it four times (in all the querySelector/querySelectorAll pages), and that still isn't a complete fix, since it doesn't account for using these values in CSS rules, which (for example) can't make use of [CSS.escape()](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape_static), so need a different treatment.

We do already say that the argument to `querySelector` must be a valid CSS selector. Unfortunately we don't (AFAICS) describe clearly what that means. It seems that ideally we'd have one place where we describe these rules and this issue about HTML, and what to do about it, and then link there from places like `querySelector`, to flesh out "valid CSS selector".

I wonder if something like https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax could be a home for this kind of information?

Does this make sense to you?

**Comment by cw118** [comment]
@wbamberg This makes sense, thank you so much for the detailed explanation!

Personally, I think that maybe the information on the meaning of a valid CSS selector could be written in one of the [CSS selectors guides](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors#guides), but I am not sure.

Perhaps the [page about CSS selector structure](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors/Selector_structure), though the beginning of this page mentions invalid selectors without defining them: "If any selector in a non-forgiving selector list is invalid, the entire selector list is invalidated."

The page https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax also briefly mentions that [all selectors of a group of selectors must be valid](https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax#css_rulesets), but it does not seem to explain further either (so perhaps it would be best/simplest to add the explanation before this sentence?):

> This leads to an important consequence: if one single basic selector is invalid, like when using an unknown pseudo-element or pseudo-class, the whole selector is invalid and therefore the entire rule is ignored (as invalid too).

**Comment by Josh-Cena** [comment]
There is already similar information on https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

**Comment by cw118** [comment]
> There is already similar information on https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

Ah I did not see that, thank you! Should mentions of (in)valid CSS selectors link to that page then?

**Comment by wbamberg** [comment]
Oh, good find @Josh-Cena . I think there are still some gaps/problems though, including:

- I assume this also applies to `class` but there is nothing corresponding in https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class
- although it talks about how to escape CSS, there's nothing on how to do that

I'm not sure if I'm overthinking this, but maybe we could do something like:

1. document the rules for a valid **CSS identifier** - I think this is captured in the specs in places like https://drafts.csswg.org/css-syntax-3/#ident-token-diagram and https://www.w3.org/TR/CSS21/syndata.html#characters. This could include, what the valid characters are and how to escape characters. Perhaps we could have this as a section in https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax ?

2. in the pages for [class](https://developer.mozilla.org/en-US/docs/Web/CSS/Class_selectors) and [id](https://developer.mozilla.org/en-US/docs/Web/CSS/ID_selectors) selectors, say that the selector value must be a valid CSS identifier, and link to (1).

3. In all the querySelector* pages, make sure we say that the argument must be a valid CSS selector. We could also mention the implications of this for class and id selectors, and link to [`CSS.escape()`](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape_static).

4. In the pages for HTML class and id attributes, recommend that values restrict themselves to valid CSS identifiers, even though that's not strictly necessary, and link to the corresponding pages in (2).

Also cc @estelle in case I'm totally wrong about this.

**Comment by Josh-Cena** [comment]
For reference: https://github.com/mdn/content/pull/25292

**Comment by estelle** [comment]
My suggestions:

1. add syntax ~~rules~~ ==suggestions== to https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class.
2. add escaping when about suggestions aren't followed to https://developer.mozilla.org/en-US/docs/Web/CSS/Class_selectors and https://developer.mozilla.org/en-US/docs/Web/CSS/ID_selectors
3. Link querySelector to both of those explanations.

And, reading what @wbamberg wrote, we're in 100% agreement. So, ... 

"Yeah, what he said!"

**Comment by dipikabh** [comment]
An outline of what needs to be done to fix this issue is captured in Will's comment: https://github.com/mdn/content/issues/28752#issuecomment-1707035191
