### ISSUE TITLE
[DevTools] Allow shape highlighter for offset-path property

### ISSUE THREAD

**Issue by bsmth** [mdn/content#28757]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1838226

Other bugs for shape editors to-be-implemented for:

-  path(): https://bugzilla.mozilla.org/show_bug.cgi?id=1841239
-  xywh(): https://bugzilla.mozilla.org/show_bug.cgi?id=1841235
-  rect(): https://bugzilla.mozilla.org/show_bug.cgi?id=1841237
-  ray(): https://bugzilla.mozilla.org/show_bug.cgi?id=1841240

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by dipikabh** [comment]
The support for shapes (except inset()) in the `offset-path` property is behind preferences:
`layout.css.motion-path-basic-shapes.enabled`
`layout.css.basic-shape-rect.enabled`
`layout.css.basic-shape-xywh.enabled`
`layout.css.motion-path-ray.enabled`


For inset(), in Fx117 and in Nightly, the offset-path shape is highlighted:

----
![screenshot to show shape editor in firefox developer tools that highlights the selected inset shape](https://github.com/mdn/content/assets/23019147/bde44f7a-ed63-4e2d-bc69-6e437dc5bd85)
---


Shape editors to-be-implemented for:
- path(): https://bugzilla.mozilla.org/show_bug.cgi?id=1841239
- xywh(): https://bugzilla.mozilla.org/show_bug.cgi?id=1841235
- rect(): https://bugzilla.mozilla.org/show_bug.cgi?id=1841237
- ray(): https://bugzilla.mozilla.org/show_bug.cgi?id=1841240

For now, I'm moving this out of the Fx117 project and will take this up when there is an update on the shape editors in DevTools and when the shapes are enabled by default in `offset-path`.
