### ISSUE TITLE
Error in formatting date

### ISSUE THREAD

**Issue by BV-utkarsh** [mdn/content#28766]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

### What specific section or headline is this issue about?

Limitation

### What information was incorrect, unhelpful, or incomplete?

While doing an timezone conversion of date with timezone "Asia/Calcutta" whose time ends like "27-08-2023 00:59"
it is converting it to "27-08-2023 24:59"
which is invalid date as 24 can't any minutes in it it should

```
new Intl.DateTimeFormat('en-CA', {
				year: 'numeric',
				month: '2-digit',
				day: '2-digit',
				hour: '2-digit',
				minute: '2-digit',
				hour12: false,
				timeZone: new Intl.DateTimeFormat().resolvedOptions().timeZone
			}).format(new Date("2023-08-27 00:59"))
```

### What did you expect to see?

I should have get "27-08-2023 00:59"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/datetimeformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/datetimeformat/index.md
* Last commit: https://github.com/mdn/content/commit/70f09675ddcfc75a3bb66d2dce4cf82738948a37
* Document last modified: 2023-08-21T07:19:52.000Z

</details>

**Comment by Josh-Cena** [comment]
I can only reproduce this in Chrome, not Safari or Firefox. Intl does not specify what exactly to be returned, so implementations are often free to provide their own heuristics. If you believe this is a bug with Chrome, please report it to their bug tracker. We will not document every implementation diversion.
