### ISSUE TITLE
text-emphasis and related longhand-properties do inherit

### ISSUE THREAD

**Issue by Rolf-B** [mdn/content#28767]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis

### What specific section or headline is this issue about?

Formal Definition

### What information was incorrect, unhelpful, or incomplete?

Spec and Section "Try it" say that the property is inherited, but the formal definition says otherwise.

### What did you expect to see?

Inherited: YES

### Do you have any supporting links, references, or citations?

https://drafts.csswg.org/css-text-decor/#propdef-text-emphasis-style
https://drafts.csswg.org/css-text-decor/#propdef-text-emphasis-color

### Do you have anything more you want to share?

I would have created a pull request, but the index.md file in text-emphasis just contains a {{CSSInfo}} macro or whatever this is and I couldn't find out where this macro pulls its data from. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/text-emphasis`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/text-emphasis/index.md
* Last commit: https://github.com/mdn/content/commit/b82ff59aab7883b7bb2222cf9f9f9b6eed818e08
* Document last modified: 2023-02-21T06:13:19.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing, @Rolf-B !

> I would have created a pull request, but the index.md file in text-emphasis just contains a {{CSSInfo}} macro or whatever this is and I couldn't find out where this macro pulls its data from.

The values for this are pulled from https://github.com/mdn/data/, specifically:

- https://github.com/mdn/data/blob/07e64622c94d5187f63f5f248004cce3b501f1cf/css/properties.json#L9248-L9263
- https://github.com/mdn/data/blob/07e64622c94d5187f63f5f248004cce3b501f1cf/css/properties.json#L9280-L9295

... so if you wish, you could file a PR there.
