### ISSUE TITLE
'Descendant combinator' used without explanation or cross-reference

### ISSUE THREAD

**Issue by sjlearmonth** [mdn/content#28760]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors

### What specific section or headline is this issue about?

The universal selector

### What information was incorrect, unhelpful, or incomplete?

It selects everything in the document (or inside the parent element if it is being chained together with another element and a descendant combinator).

### What did you expect to see?

I expected to read an explanation about what a descendent combinator is before using the term for the first time in the context of the universal selector. Also, it is not explained what chained together means in the context of this sentence.

### Do you have any supporting links, references, or citations?

No.

### Do you have anything more you want to share?

No.

**Comment by bsmth** [comment]
Thanks for raising this one. I think we can link to https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Combinators#descendant_combinator at the very least. I will take a look shortly 👀
