### ISSUE TITLE
precedence order in important flag

### ISSUE THREAD

**Issue by ehsanmehrali** [mdn/content#28774]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers

### What specific section or headline is this issue about?

Cascade layers-Precedence order of regular cascade layers

### What information was incorrect, unhelpful, or incomplete?

In the first example of this section (Precedence order of regular cascade layers), in the explanation section after the example, in the fourth paragraph, the third line is explained as follows:
-While normal unlayered styles override all normal styles set in a layer, **_with important styles, the precedence order is reversed; unlayered important styles have lower precedence than layered styles._** 

### What did you expect to see?

in this example: **_box-shadow: 5px 5px lightgreen !important;_** which is styled in the unlayered and ignores all the box-shadow that are placed inside the layers.
And this contradicts the explanation of this section. 
I'm learning and I'm a little confused.

### Do you have any supporting links, references, or citations?

![mdn-css-layers](https://github.com/mdn/content/assets/140562533/7a173f8c-5f0b-4760-b817-7a611a030690)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_layers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_layers/index.md
* Last commit: https://github.com/mdn/content/commit/2b62e1479f620f4b9f740e34d14581d8531e251e
* Document last modified: 2023-08-20T23:06:38.000Z

</details>

**Comment by mikoMK** [comment]
Thanks for opening this issue.

This is a bug in the DevTools. The rendered box shadow is `box-shadow: -5px -5px lightblue !important;` from layer A. That shows that unlayered `!important` styles indeed have lower precedence than `!important` styles in layers as the article describes.
This bug has been fixed in Firefox 117 that was release a few days ago.

**Comment by ehsanmehrali** [comment]
Thank you for replying.
Yes, you are right. This issue has been fixed in the Firefox DevTools.
