### ISSUE TITLE
Poor Explanation of the target Parameter In JavaScript's Array copyWithin Method

### ISSUE THREAD

**Issue by tjakubiec218** [mdn/content#28787]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

When explaining the target parameter, it starts explaining it by saying "Zero-based index at which to copy the sequence to, converted to an integer" and then more stuff after that. I have no issue with the more stuff after that.

### What did you expect to see?

By explaining it as "zero-based index at which to copy the sequence to..." it gives the impression that this target parameter is fixed throughout the entire run of the function. This of course is not the case as after the first item is copied, if there are more items to copy, the target index moves up by one.

I expected to see that concept explained within the explanation of the parameter.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin

**Comment by Josh-Cena** [comment]
`start` and `end` together define a sequence. `target` is where this entire sequence is copied "to". The sequence's position is uniquely determined by its starting position. Perhaps we can make it slightly clearer that `target` is where the start is, but the current text is not wrong.

**Comment by tjakubiec218** [comment]
Yeah that's all I meant. Make it clearer that target is where the start is because upon first glance/read I got the impression that target was fixed throughout the entire run of the function, and was then confused when it wasn't.

**Comment by Josh-Cena** [comment]
If you think of `target` as where the entire sequence is copied to, then it's indeed "fixed", because there's only one copying. If you understand it as where individual elements are copied to, then sure, it gets shifted. But it's easier to explain in terms of the former and avoid implying that elements are copied one-by-one.

**Comment by tjakubiec218** [comment]
I appreciate the explanation provided. I now appreciate keeping the explanation correct with what happens technically (one single copy), and not confusing the explanation with trying to imply that elements are copied one-by-one. I'll close this issue.
