### ISSUE TITLE
Object() constructor page: new Object() vs Object() differences not noted in Return value section

### ISSUE THREAD

**Issue by mreswick** [mdn/content#28789]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/Object

### What specific section or headline is this issue about?

The note in Syntax section: "Note: Object() can be called with or without new, but sometimes with different effects. See Return value"

### What information was incorrect, unhelpful, or incomplete?

The above-quoted note under the "Syntax" section on the `Object()` constructor page does not appear to be addressed in the "Return value" section it references. That note states there are some situations in which there are differences between using the `Object()` constructor with `new` as opposed to not (ie, differences between `Object()` vs `new Object()`), and says to look in the "Return value" section of that page for more info on that. However, any such differences do not appear to be addressed there.

### What did you expect to see?

A section of text, be it under "Return value" to match the above-quoted note or otherwise, that describes the differences, if any, between using the `Object()` constructor with `new` vs without.

### Do you have any supporting links, references, or citations?

[ECMA spec on `Object()` constructor](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-object-constructor)

### Do you have anything more you want to share?

The page on the `Object()` constructor appears to currently be incomplete.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/object`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/Object
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/object/index.md
* Last commit: https://github.com/mdn/content/commit/27180875516cc311342e74b596bfb589b7211e0c
* Document last modified: 2023-08-24T22:55:36.000Z

</details>

**Comment by Josh-Cena** [comment]
It does. `super()` is basically `new Object()`, except with a different `new.target`. Therefore:

- If `Object()` is _called_ (without `new`), the argument is always significant.
- If `Object()` is _constructed_ (with `new`), the argument may or may not be significant, depending on the value of `new.target`.

**Comment by mreswick** [comment]
Ok, thanks for that explanation and the quick response. That makes sense now.

Are there any other differences, such as from ES5? I saw a [post](https://stackoverflow.com/questions/30801497/new-object-vs-object-in-the-ecmascript-spec) on StackOverflow in regards to ES5 about implementation behavior such as for `new Object(window)`, but I guess that no longer is applicable? Just want to make sure that page is complete.

**Comment by Josh-Cena** [comment]
No, as far as I know—they should be equivalent for object inputs, post-ES6.

**Comment by mreswick** [comment]
Thanks for all the info!
