### ISSUE TITLE
:blank selector page does not consider the `:blank` `@page` pseudo-class which is different

### ISSUE THREAD

**Issue by AlaskanEmily** [mdn/content#28809]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:blank

### What specific section or headline is this issue about?

The entire page

### What information was incorrect, unhelpful, or incomplete?

This page does not include any information on the CSS page3 information about the `:blank` pseudo-class for `@page` rules, which has a different meaning. This page is linked to by content about `@page`, which may be confusing.

### What did you expect to see?

Additional information about the other `:blank` pseudo-class for page-rules.

### Do you have any supporting links, references, or citations?

https://drafts.csswg.org/css-page-3/#blank-pseudo

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_blank`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:blank
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_blank/index.md
* Last commit: https://github.com/mdn/content/commit/5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e
* Document last modified: 2023-02-21T06:49:52.000Z

</details>

**Comment by OnkarRuikar** [comment]
This user input related `:blank` is not the same as printing related `@page :blank`. The links on [@page documentation](https://web.archive.org/web/20230826005804/https://developer.mozilla.org/en-US/docs/Web/CSS/@page#formal_syntax) are wrong. Browser compatibility for them will be tracked separately.

We need to create a separate page for `@page :blank` but it seems no browser supports it. For now we can remove the `:blank` and `@page :blank` associations from MDN.
