### ISSUE TITLE
Topic to be more explained

### ISSUE THREAD

**Issue by hiteshgrovr** [mdn/content#28804]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

### What specific section or headline is this issue about?

Explanation

### What information was incorrect, unhelpful, or incomplete?

Any topic has missing explanation... each property has value but not enough information to explain it for each property like W3Schools. Please provide the proper explanation too.

### What did you expect to see?

Any topic has missing explanation... each property has value but not enough information to explain it for each property like W3Schools. Please provide the proper explanation too.

### Do you have any supporting links, references, or citations?

Any topic has missing explanation... each property has value but not enough information to explain it for each property like W3Schools. Please provide the proper explanation too.

### Do you have anything more you want to share?

Any topic has missing explanation... each property has value but not enough information to explain it for each property like W3Schools. Please provide the proper explanation too.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/color-scheme`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/color-scheme/index.md
* Last commit: https://github.com/mdn/content/commit/856b52f634b889084869d2ee0b8bb62c084be04d
* Document last modified: 2023-07-17T22:37:27.000Z
 m
</details>

**Comment by wbamberg** [comment]
This issue report doesn't give us enough concrete detail to be usable.

What specific information is missing in https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme?

What is in w3schools that is missing here? I can't find any page on w3schools for the `color-scheme` property.
