### ISSUE TITLE
Issue with "Generator.prototype.return()": If no parameter is set, it actually returns undefined

### ISSUE THREAD

**Issue by hendryl** [mdn/content#2881]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/return

#### What information was incorrect, unhelpful, or incomplete?
This specific line is incorrect:

> If no argument is provided, the value property of returned object is the same as if .next()

#### Specific section or headline?

Examples section - Using return()

#### What did you expect to see?
If no argument is provided, the value property of returned object is always `undefined`.

#### Did you test this? If so, how?
This is the code I used for testing:
```
function* gen() {
    yield 1;
    yield 2;
  }
  
  const g = gen();
  
  console.log(g.next())     // { value: 1, done: false }
  console.log(g.return())   // { value: undefined, done: true }
```
If the line was correct, the returned object should be `{ value: 2, done: true }`. This returns `{ value: undefined, done: true }` instead.

I tested this in Chrome 88.0.4324.190, Firefox 86, Node v12.21.0 and Node v14.16.0. All of them behaved the same.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/generator/return`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/return
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/generator/return/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/3901 with a fix.
