### ISSUE TITLE
Components.utils.isDeadWrapper() not working correctly.

### ISSUE THREAD

**Issue by mhdzumair** [mdn/content#2882]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Dead_object

#### What information was incorrect, unhelpful, or incomplete?
Components.utils.isDeadWrapper() method is not working correctly.

#### Specific section or headline?
Checking if an object is dead

#### What did you expect to see?
I want to check the opened tab closed or not.

#### Did you test this? If so, how?
When I use these Components.utils.isDeadWrapper method in my extension than the new page refreshing again and again and again. It's weird. Then my pc get stuck little. Then I immediately remove extension and webpage. But However the Unprivileged code with try block is working good.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/dead_object`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Dead_object
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/dead_object/index.html
* Last commit: https://github.com/mdn/content/commit/6fe447217e08a28cf17b8896545f98d098582ac3
* Document last modified: 2021-02-19T20:01:33.000Z

</details>

**Comment by wbamberg** [comment]
What kind of extension are you writing? [Firefox WebExtensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) don't get  access to the `Components` object - and Firefox hasn't supported any other type of extension for years.

If you want to interact with tabs in a WebExtension, use the [`tabs`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs) API.

**Comment by mhdzumair** [comment]
Is that `tabs` api permission is necessary to work with isDeadWrapper method.? I create extension for some automation task and remove ads (i intend to isDeadWrapper method to check the popup window is closed or not without getting `tabs` permission. I used try except block for managing that one.). I only used content script. Actually I couldn't check the logs becuase, whenever insert condition for Components.utils.isDeadWrapper(adswindow) then that tab keep refreshing and stuck so i qiuckly remove debugging extension. BTW my extension source: [ads_fucker](https://github.com/mhdzumair/ads_fucker)

**Comment by mhdzumair** [comment]
Coorect me if i'm wrong, The [TypeError: can't access dead object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Dead_object) page is not mentioned any permission need for using that method. Since content script running in page context i thought this method will be Xrayed because of privileged code

**Comment by rebloor** [comment]
@mhdzumair [As mentioned](https://github.com/mdn/content/issues/2882#issuecomment-791593512)  Firefox WebExtensions don't get access to the Components object. You may be able to get further assistance by posting information about what you want to achieve on the [Add-ons forum](https://discourse.mozilla.org/c/add-ons).
