### ISSUE TITLE
`isTrusted` property in `Event` isn't indicated whether this event was generated by a user action

### ISSUE THREAD

**Issue by EdgarChen** [mdn/content#28837]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted

### What specific section or headline is this issue about?

property description

### What information was incorrect, unhelpful, or incomplete?

MDN says
> The isTrusted read-only property of the [Event](https://developer.mozilla.org/en-US/docs/Web/API/Event) interface is a boolean value that is true when the event was generated by a user action, and false when the event was created or modified by a script or dispatched via [EventTarget.dispatchEvent()](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent).

But the focus event is filed with isTrusted = true even if the focus is changed by calling `focus()` on a element in script without a user action, e.g. page calls `focus()` to focus a element right after it's loaded.

What outlined in the [spec](https://dom.spec.whatwg.org/#dom-event-istrusted) is:
> [isTrusted](https://dom.spec.whatwg.org/#dom-event-istrusted) is a convenience that indicates whether an [event](https://dom.spec.whatwg.org/#concept-event) is [dispatched](https://dom.spec.whatwg.org/#concept-event-dispatch) by the user agent (as opposed to using [dispatchEvent()](https://dom.spec.whatwg.org/#dom-eventtarget-dispatchevent)). The sole legacy exception is [click()](https://html.spec.whatwg.org/multipage/interaction.html#dom-click), which causes the user agent to dispatch an [event](https://dom.spec.whatwg.org/#concept-event) whose [isTrusted](https://dom.spec.whatwg.org/#dom-event-istrusted) attribute is initialized to false.

### What did you expect to see?

Perhaps something in line with the spec.

### Do you have any supporting links, references, or citations?

https://dom.spec.whatwg.org/#dom-event-istrusted

**Comment by Josh-Cena** [comment]
`.focus()` "looks more like" a user action than `dispatchEvent(new FocusEvent())`. The idea is that you could trust the properties installed on the event you received, because the event object itself is synthesized by the UA. But perhaps aligning with the spec is better.
