### ISSUE TITLE
Outdated/incorrect statement about FocusEvent order

### ISSUE THREAD

**Issue by vHeemstra** [mdn/content#28835]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent

### What specific section or headline is this issue about?

Order of events

### What information was incorrect, unhelpful, or incomplete?

The text states that the **UI Events specification** (referenced with [this link](https://w3c.github.io/uievents/#events-focusevent-event-order)) states a ***different event order*** than **most current browser implementations**. It then lists the event order according to the specification, followed by the event order of the typical browser implementation.

However, the listed "specification's order" is incorrect.
If you follow the link, it shows the exact same order as the "typical browser implementation".

### What did you expect to see?

Perhaps the specifications have changed, but the mentioned difference between these two lists of event order is either outdated or incorrect. Both the referenced specification and the typical browser implementation have the same order.

If there actually (still) is a difference between the event order in current browsers and the specification, than the text is incorrect and maybe the reference link as well.

### Do you have any supporting links, references, or citations?

https://w3c.github.io/uievents/#events-focusevent-event-order

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/focusevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/focusevent/index.md
* Last commit: https://github.com/mdn/content/commit/c88a329069328522a5c20c054f9dbced9967dbd4
* Document last modified: 2023-02-20T08:12:58.000Z

</details>

**Comment by wbamberg** [comment]
Yes, see https://github.com/w3c/uievents/issues/88.
