### ISSUE TITLE
[CSS] Add font-synthesis-position property 

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#28841]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

[css-fonts-4][css-fonts-5] 
https://bugzilla.mozilla.org/show_bug.cgi?id=1849010

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by dletorey** [comment]
## Associated Pull Requests

- [Content PR](https://github.com/mdn/content/pull/29108)
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/20688)
- [interactive-examples PR](https://github.com/mdn/interactive-examples/pull/2613)
- [data PR](https://github.com/mdn/data/pull/691)
