### ISSUE TITLE
[DevTools] Display a warning when 'empty-cells' is used on invalid elements

### ISSUE THREAD

**Issue by bsmth** [mdn/content#28847]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

warning i.e. "<strong>{ $property }</strong> has no effect on this element since it can only be applied to table cells."

## Related Gecko bugs

- https://bugzilla.mozilla.org/show_bug.cgi?id=1583906 and:
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1583912 (Display a warning when column-related properties are used on non-multi-column containers)
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1842174 (Report ignored properties on ::first-line pseudo-elements)

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by Rumyra** [comment]
As we don't document devtools - I'm closing this 👍
