### ISSUE TITLE
[Nightly] [HTTP] GPC needs a UI setting instead of CONFIG changes

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#28854]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

> This exposes the `navigator.globalPrivacyControl` boolean in workers and websites, on Nightly only for now.

Also see [this comment in bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1830623#c24)

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1830623

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
It's behind 
- Adds `Navigator.globalPrivacyControl` behind a pref `privacy.globalprivacycontrol.functionality.enabled` that is enabled by default in nightly. Note however that this is non-obvious - the [StaticPrefList.yaml](https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml) says `false` but it is set true on nightly here https://searchfox.org/mozilla-central/source/browser/app/profile/firefox.js (or at least it appears to be, and is enabled on my version).
-  Will need a BCD and docs entry
- https://globalprivacycontrol.org/ explain how this works. Still not read yet so might be more to this

**Comment by Jayboyokok** [comment]
Does this feature cause my device to operate different at night? Do I get a say in matters? I don't use Firefox, Safari, and trying to get away from chrome. Catastrophe!!!!
