### ISSUE TITLE
Example "Without & nesting selector" uses "&" anyway

### ISSUE THREAD

**Issue by pbb72** [mdn/content#28868]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting

### What specific section or headline is this issue about?

Without & nesting selector

### What information was incorrect, unhelpful, or incomplete?

The live example shown under this heading, uses the "&" selector despite claiming not to. This gives the wrong impression about what is supported.

### What did you expect to see?

I expected the live example to fail on Chrome 116.

### Do you have any supporting links, references, or citations?

Remove the CSS code block that includes the & nesting selector, and the example fails.

### Do you have anything more you want to share?

I am somewhat uncertain if I am correct, as I can not find any references that nesting selection without & is not supported, but it is the behavior I am seeing.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_nesting/using_css_nesting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_nesting/using_css_nesting/index.md
* Last commit: https://github.com/mdn/content/commit/13746bf1d5d8e5c7c7bce5e1281e6eeee77b3d44
* Document last modified: 2023-08-29T11:29:06.000Z

</details>

**Comment by bsmth** [comment]
CCing @dletorey for a look 👀

**Comment by dletorey** [comment]
It appears that both CSS code blocks are being loaded in both result blocks which means that the the example with the `&` is over-writing the other version due to the cascade.

I shall split these two examples out so they are distinct from each other.
