### ISSUE TITLE
<base> does not support data: and javascript: URLs

### ISSUE THREAD

**Issue by annevk** [mdn/content#28865]
This has been implemented for quite a while in Chromium and WebKit, but was not yet standardized. That is being addressed now in https://github.com/whatwg/html/pull/9665 and it might also be worth documenting on MDN.

**Comment by hamishwillee** [comment]
Thanks. Yes it should be documented in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base and I guess also https://developer.mozilla.org/en-US/docs/Web/API/HTMLBaseElement

It it that https and http are the only real valid base URL protocols following this change or are there others? (it would be better to write "only https and http are allowed" than "data and javascript URLs are forbidden).

**Comment by annevk** [comment]
No, all schemes are allowed, except for "data" and "javascript".
