### ISSUE TITLE
Write a glossary entry for "Camel case"

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#28882]
"Camel case" is a jargon term that we use here and there but don't define. We should have a short glossary entry we can link to.

See also: https://github.com/mdn/content/pull/28879, https://github.com/mdn/content/pull/28881.

**Comment by SoundaryaKoutharapu** [comment]
Hey! can I jump in and tackle this one?
Let me know if it's up for grabs.

**Comment by Josh-Cena** [comment]
I think it would be more efficient that I help with this.

@wbamberg what about other casings? If we do this I'm tempted to do so for PascalCase, snake_case, and kebab-case as well (maybe SCREAM_CASE, but there are too many names for this)

**Comment by wbamberg** [comment]
@Josh-Cena I'm happy for you to write this, or to do it myself.

> @wbamberg what about other casings? If we do this I'm tempted to do so for PascalCase, snake_case, and kebab-case as well (maybe SCREAM_CASE, but there are too many names for this)

I think in general these conventions are reasonable subjects for glossary entries, in that they're bits of jargon that can be given relatively short definitions, but the article using them doesn't want to define them inline every time.

I think "camel case" is the most practically important one, because there's no concise non-jargon term, and the convention comes up on the web platform a lot. While "kebab case" also comes up it seems a bit easier to express without jargon (lowercase, hyphenated), and it is likely to be better for readers to do that than to send them to a glossary page. "Snake case" doesn't come up as often on the web. "Pascal case" is an interesting one, Wikipedia treats it as a variant of camel case. I don't think arguing about whether pascal case is a variant of camel case or not is a good use of our time, as long as we are clear and consistent.

But I'm not against having pages for all the main conventions.

**Comment by nithinkodadhavadee** [comment]
can I create these entries in the Glossary? I am assuming I'll have to create a directory for each of the cases inside the [Glossary](https://github.com/mdn/content/tree/main/files/en-us/glossary) and put the description inside the index.md file
