### ISSUE TITLE
possible issue in code example

### ISSUE THREAD

**Issue by ezekiel747** [mdn/content#28899]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Manifest/launch_handler

### What specific section or headline is this issue about?

launch_handler example - wrong code?

### What information was incorrect, unhelpful, or incomplete?

the second code example, the one with an array format, contains only one string with two values:
"client_mode": ["focus-existing, auto"]

### What did you expect to see?

i think it should be two string values in that array instead, not only one string:
"client_mode": ["focus-existing", "auto"]

### Do you have any supporting links, references, or citations?

https://wicg.github.io/web-app-launch/#dfn-client_mode

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/manifest/launch_handler`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/launch_handler
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/manifest/launch_handler/index.md
* Last commit: https://github.com/mdn/content/commit/0c015b80f786ecc4547c3e37a70c7f6aafdfbf74
* Document last modified: 2023-06-28T16:16:20.000Z

</details>

**Comment by wbamberg** [comment]
Yes, looks like a typo. Thank you for filing!
