### ISSUE TITLE
bug: Missing tutorial link on Performance API documentation 

### ISSUE THREAD

**Issue by prabodhmeshram** [mdn/content#28898]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Performance_API

### What specific section or headline is this issue about?

Tutorials

### What information was incorrect, unhelpful, or incomplete?

The tutorials section has missing link to the article that has been mentioned on the page

### What did you expect to see?

The article should have link for users to navigate

### Do you have any supporting links, references, or citations?

![image](https://github.com/mdn/content/assets/6660187/87053b9f-dc14-4589-93ab-ce369b006ca3)

**Comment by hamishwillee** [comment]
True. If you look in the preceding section [How tos](https://developer.mozilla.org/en-US/docs/Web/API/Performance_API#how-tos) there are many more links. I presume these are  links for topics we'd like to be written to fully cover the topic..

@chrisdavidmills @Elchi3 Is there a particular "plan" to populate these links?  I think it is fine to have "wanted links" like this, but should they be done as (broken) links?

**Comment by Elchi3** [comment]
This is my fault. I had this as my to-do list in some PR and then it got merged without me removing the planned items. I will remove it. Sorry.

**Comment by Elchi3** [comment]
The project to finish this work is described in https://github.com/openwebdocs/project/issues/157.
