### ISSUE TITLE
[WebExt] Expose HTTPS-Only preference in privacy.network

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#289]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Exposing HTTPS-Only preference in privacy.network

## Related Gecko bugs

1. - [ ] [Expose HTTPS-Only preference in privacy.network](https://bugzilla.mozilla.org/show_bug.cgi?id=1678306)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by chrisdavidmills** [comment]
Hi @caitmuenster ! I wanted to just ping you about this item — is there anything to add to the MDN docs for this? We've got the Fx 85 release coming in 8 days, so we've got a bit of time.

**Comment by caitmuenster** [comment]
Thanks @chrisdavidmills! Once the two linked PRs are merged, this will be good to close.

**Comment by chrisdavidmills** [comment]
Merged, so closing! Thanks @caitmuenster
