### ISSUE TITLE
overscroll-behavior can stop scroll chaining for iframes

### ISSUE THREAD

**Issue by simevidas** [mdn/content#28904]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

> Note that this property applies only to scroll containers. In particular, since an <iframe> is not a scroll container, this property cannot be used to stop scroll chaining for iframes.

### What did you expect to see?

The property can stop scroll chaining for iframes. To do this, the iframed document has to have the following style.

```css
html, body {
  overscroll-behavior-y: contain;
}
```

Test page: https://codepen.io/simevidas/full/RwEGwpm

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/overscroll-behavior`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/overscroll-behavior/index.md
* Last commit: https://github.com/mdn/content/commit/9e521726ed1d605756b73a788eaa55498d540821
* Document last modified: 2023-07-24T14:11:48.000Z

</details>

**Comment by OnkarRuikar** [comment]
- Related to https://github.com/mdn/content/pull/20706

We can add this workaround to the note.

Why do we need to set it on `<html>` element, simply setting it on `<body>` won't do?

**Comment by simevidas** [comment]
According to my tests, to make it work in Safari and Firefox, it needs to be set on `<html>`, and for Chrome it needs to be set on `<body>`.
