### ISSUE TITLE
Active Learning Frame Reset Issue

### ISSUE THREAD

**Issue by robmats99** [mdn/content#28907]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started

### What specific section or headline is this issue about?

Active learning: Adding attributes to an element

### What information was incorrect, unhelpful, or incomplete?

I created a link in the iframe "frame_active_learning_adding_attributes_to_an_element" that was supposed to go to google.com but I did not set the target attribute. I then pressed the link and the frame went to an error screen and will not go back to it's original state even after refreshing the page.

### What did you expect to see?

A refresh button outside of the iframe that would allow you to refresh it in case you break it.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/getting_started/index.md
* Last commit: https://github.com/mdn/content/commit/8d0cbeacdc1872f7e4d966177151585c58fb879e
* Document last modified: 2023-08-02T17:32:22.000Z

</details>

**Comment by wbamberg** [comment]
Yes, I can see that this example makes it easy to do something like this. We should fix that, but...

>  I then pressed the link and the frame went to an error screen and will not go back to it's original state even after refreshing the page.

...in case you need it to get un-stuck: hard-refreshing the page (how to do this is browser and platform dependent, but it's shift+command+r on Firefox on macos) should work to reset the example.

**Comment by robmats99** [comment]
That worked, thank you! 

Just curious, would a PR that added an external reset button to just that iframe be accepted or would there have to be an effort to add that functionality to all similar iframes?

**Comment by wbamberg** [comment]
You're welcome!

> would a PR that added an external reset button to just that iframe be accepted or would there have to be an effort to add that functionality to all similar iframes?

That would need a platform change, and it's a very niche problem: it's only because this is an editable example in which you add a link that it has the potential to go wrong like this. So if possible, I think we ought to fix this in content. There's nothing about this tutorial that _needs_ the example to be a link: for example, we could ask the reader to add an `<img>` instead, which also has some interesting attributes but doesn't bring the possibility of completely breaking the example editor. So that seems like a simpler fix to me.

**Comment by robmats99** [comment]
> I think we ought to fix this in content. There's nothing about this tutorial that needs the example to be a link: for example, we could ask the reader to add an <img> instead, which also has some interesting attributes but doesn't bring the possibility of completely breaking the example editor

That sounds good! I'll get to work on it then.

**Comment by wbamberg** [comment]
OK, sounds great! Let me know if you have any questions.

**Comment by robmats99** [comment]
Hi @wbamberg, quick question. In reference to my PR above #29157, do I need to update the branch consistently until I get a review or do I risk getting it rejected?

Thank you so much!

**Comment by wbamberg** [comment]
Hi @robmats99 ! Thank you for your PR, I did see it and will get to it soon, unless someone else does.

> Hi @wbamberg, quick question. In reference to my PR above #29157, do I need to update the branch consistently until I get a review or do I risk getting it rejected?

No, you don't have to worry about that :).
