### ISSUE TITLE
Formal syntax wrong

### ISSUE THREAD

**Issue by jimmonte** [mdn/content#28900]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust

### What specific section or headline is this issue about?

Formal syntax

### What information was incorrect, unhelpful, or incomplete?

Formal syntax should optionally include ex-height | cap-height | ch-width | ic-width | ic-height

### What did you expect to see?

See above

### Do you have any supporting links, references, or citations?

View link given on page for reference

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-size-adjust`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-size-adjust/index.md
* Last commit: https://github.com/mdn/content/commit/c77cfcd17e85db6c1b93160c70668f2ff6c2809c
* Document last modified: 2023-07-20T07:38:29.000Z

</details>

**Comment by wbamberg** [comment]
This is because the algorithm we use to get the CSS syntax explicitly excludes numbered versions of the specs, and considers the unnumbered version to be the "current spec": https://github.com/mdn/yari/pull/4656#issuecomment-1113508815.

I'm not sure if this is a good policy or not, though, and it's unfortunate that the policy is different in BCD, which supplies the URL that appears in the "Specifications" section :(.

**Comment by wbamberg** [comment]
I've started a discussion -> https://github.com/orgs/mdn/discussions/442

**Comment by OnkarRuikar** [comment]
It doesn't matter in this case, just for info, we are stuck on an 9 month old version of `@webref/css`(v6.7.1) package:
- https://github.com/mdn/yari/pull/9285

**Comment by wbamberg** [comment]
Yes, although as you say that is not relevant to this issue. I think it would be great if Yari extracted the csssyntax code to a separate package, and I have made a start at this in https://www.npmjs.com/package/query-css-syntax, which supports webref 6 and is what I am using for content embedding. But I don't know if Yari wants to do that.

**Comment by OnkarRuikar** [comment]
> I have made a start at this in [npmjs.com/package/query-css-syntax](https://www.npmjs.com/package/query-css-syntax), which supports webref 6

It would be really great if webref provided these easy retrieval APIs out of the box.

**Comment by bsmth** [comment]
> We are stuck on an 9 month old version of `@webref/css`(v6.7.1) package

There's a PR to upgrade to 6.0.0 here:

- [ ] https://github.com/mdn/yari/pull/9621

**Comment by teoli2003** [comment]
We discussed it today. We agree that this is a problem we want to solve, but it is a complex one. So, we are closing this but in favor of the discussion at https://github.com/orgs/mdn/discussions/442
