### ISSUE TITLE
Confusing docs

### ISSUE THREAD

**Issue by govindrai** [mdn/content#28913]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Decrement

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

It could be correct, but seems confusing:

> If used postfix, with operator after operand (for example, x--), the decrement operator decrements and returns the value before decrementing.
>
> If used prefix, with operator before operand (for example, --x), the decrement operator decrements and returns the value after decrementing.

### What did you expect to see?

Should these instead state?:

If used postfix, with operator after operand (for example, x--), the decrement operator ~decrements and~ returns the value before decrementing.

If used prefix, with operator before operand (for example, --x), the decrement operator ~decrements and~ returns the value after decrementing.

or maybe?:

If used postfix, with operator after operand (for example, x--), the decrement operator ~decrements and~ returns the value **before the decrement**.

If used prefix, with operator before operand (for example, --x), the decrement operator ~decrements and~ returns the **value after the decrement**.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/decrement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Decrement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/decrement/index.md
* Last commit: https://github.com/mdn/content/commit/f616cb604af851f77f8cd59368e94ee3e43a8838
* Document last modified: 2023-08-15T14:59:44.000Z

</details>

**Comment by Josh-Cena** [comment]
"Decrement" is an action. Both your suggested change and the original text is correct, but the original is more comprehensive as it both discusses the side effect of the operation and its return value.
