### ISSUE TITLE
Issue with "scaleX()": (angles of the element)

### ISSUE THREAD

**Issue by ahmadalzoubi13579** [mdn/content#2892]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scaleX()

#### What information was incorrect, unhelpful, or incomplete?

- the image is completely misleading 

- `the angles of the element are not conserved`

#### What did you expect to see?

`the angles of the element are conserved` 

#### Did you test this? If so, how?

yes, [example](https://codepen.io/MrGuko/pen/abBadox)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/transform-function/scalex()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scaleX()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/transform-function/scalex()/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by NegiAkash890** [comment]
I tested it in  your code pen and I think it should be `The scaling is not isotropic, and the angles of the element are not conserved when argument to scaleX function is negative` .

**Comment by gogoIsComing** [comment]
@NegiAkash890 yes, but what i mean that `right angles still right angles` even when argument to scaleX function is negative.

**Comment by Josh-Cena** [comment]
In mathematics, when we say "a transform does not preserve X", it does not mean "X is always changed", it means "X is not always not changed". There will always be trivial cases where X could be conserved, like right angles here.

Accepting a PR to make it say

> The scaling is not isotropic, and the angles of the element are generally not conserved, except for multiples of 90 degrees.
