### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by 7777chaitanya** [mdn/content#28937]
### MDN URL

https://github.com/mdn/content/tree/main/files/en-us/web/javascript/reference/statements/try...catch/index.md

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#description

### What information was incorrect, unhelpful, or incomplete?

Below is a line from the page I am having issue with, 

> You can nest one or more try statements. If an inner try statement does not have a catch block, the enclosing try statement's catch block is used instead.

If the inner try both does not have a corresponding catch block, will it not throw a syntax error? Please check the code example below,

```javascript
try{
  try{
    throw new Error('nested try Error')
  }
}
catch(e){
  console.log(e)
}
```

### What did you expect to see?

Every try block should have it's corresponding catch or finally block.

**Comment by Josh-Cena** [comment]
A `try` statement without a `catch` block is a `try` statement with a `finally` block—"while being syntactically valid" is implied :)
