### ISSUE TITLE
api.Navigator.requestMIDIAccess - broken link

### ISSUE THREAD

**Issue by mikecat** [mdn/content#28959]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

The page linked from "site permission add-on" (expand "requestMIDIAccess" on Firefox to see)

```
https://support.mozilla.org/en-US/kb/site-permission-addons
```

Shows "Page Not Found".

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Maybe this page should be linked:

```
Site Permission Add-ons | Firefox Help
https://support.mozilla.org/en-US/kb/site-permission-add-ons
```

### Did you test this? If so, how?

Opened the link on Firefox 117.0 (x64)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.requestMIDIAccess`
* Report started: 2023-09-05T18:13:58.610Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much for reporting. This was fixed by https://github.com/mdn/browser-compat-data/pull/20618 three days ago, but the information has not yet appeared on MDN. The actual link is: https://support.mozilla.org/en-US/kb/site-permission-add-ons
