### ISSUE TITLE
Range HTTP Header offsets are inclusive

### ISSUE THREAD

**Issue by abursavich** [mdn/content#28957]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range

### What specific section or headline is this issue about?

Directives and Examples

### What information was incorrect, unhelpful, or incomplete?

The description of `range-end` in the Directives section is imprecise and doesn't clarify if it's inclusive or not.

The examples in the Examples section have mixed implications.

This example implies it's not inclusive:
> The following example requests three separate parts of a file, from 200-1000 (the first 800 bytes), ...
>
> Range: bytes=200-1000, 2000-6576, 19000-

This example implies that it is inclusive:
> This example requests the first 500 and last 500 bytes of the file. The request may be rejected by the server if these ranges overlap (i.e. the file is less than 1000 bytes long).
>
> Range: bytes=0-499, -500

### What did you expect to see?

The Directive descriptions should be precise and the Examples section should match.

The Directives descriptions on the [Content-Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/) HTTP Header page are great.

> `<range-start>`
>
> An integer in the given unit indicating the start position (zero-indexed & inclusive) of the request range.

> `<range-end>`
>
> An integer in the given unit indicating the end position (zero-indexed & inclusive) of the requested range.

### Do you have any supporting links, references, or citations?

https://httpwg.org/specs/rfc7233.html#byte.ranges

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/range`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/range/index.md
* Last commit: https://github.com/mdn/content/commit/5e9631df85d021e84133e14f4bd3c712e4f8fe08
* Document last modified: 2023-08-25T00:21:46.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting @abursavich - that's a good one to clarify. I've assigned myself so it's on my todo list. 👍🏻

**Comment by hamishwillee** [comment]
Also for bytes units that the ranges are byte _offsets_ and hence are indexed from zero. So if you have 10000 bytes and you wanted to specify the last one you'd use -9999
