### ISSUE TITLE
Issue with "@import": incorrect link to chrome url

### ISSUE THREAD

**Issue by RawmanGrey** [mdn/content#2896]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@import

#### What information was incorrect, unhelpful, or incomplete?
link to non-existing page: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/The_Chrome_URL 

#### Specific section or headline?
Under Syntax heading, in url section <a> element has link heading non-existing page.

#### What did you expect to see?
some content  : )

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/@import`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@import
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@import/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by chrisdavidmills** [comment]
We can just delete the content about using this for mozilla internals; "Note that the URL..." onwards.

**Comment by CreaTorAlexander** [comment]
I can update it 👍
