### ISSUE TITLE
The enumeration of the values of platform property has duplicates.

### ISSUE THREAD

**Issue by krave1986** [mdn/content#28966]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform

### What specific section or headline is this issue about?

Value

### What information was incorrect, unhelpful, or incomplete?

There are 2 `"linux x86_64"` listed in the enumeration of the possible values of `platform` property.

### What did you expect to see?

Replace one of the two `"linux x86_64"` with another possible value.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/platform`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/platform/index.md
* Last commit: https://github.com/mdn/content/commit/ef75c1741b450c2331204be5563ee964ad5f4c48
* Document last modified: 2023-04-07T06:16:45.000Z

</details>

**Comment by bsmth** [comment]
Thanks for raising this one. The spec lists `"Linux x86_64", "Linux armv81"` so I'm guessing this is what the duplicate should be. Would you like to open a pull request to fix this?

**Comment by krave1986** [comment]
Thanks! I have opened a pull request to fix this.
It is #28984 .
