### ISSUE TITLE
The link is not opening correctly

### ISSUE THREAD

**Issue by gusega** [mdn/content#28979]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Text_fragments

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/Text_fragments#:~:text=of%20that%20section%2C%20for%20example

### What information was incorrect, unhelpful, or incomplete?

The link after https://developer.mozilla.org/en-US/docs/Web/Text_fragments#:~:text=of%20that%20section%2C%20for%20example won't navigate to the page fragment

chrome version:

version 116.0.5845.140 (Official Build) (x86_64)

### What did you expect to see?

That it correctly navigates to the fragment.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/text_fragments`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Text_fragments
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/text_fragments/index.md
* Last commit: https://github.com/mdn/content/commit/9aaaa8597f2b1b952a9ed116cbe48e4810254cea
* Document last modified: 2023-09-04T14:39:07.000Z

</details>

**Comment by hamishwillee** [comment]
I am not sure I understand the problem but I don't think this is valid. On Chrome 116, if I select https://developer.mozilla.org/en-US/docs/Web/Text_fragments#:~:text=of%20that%20section%2C%20for%20example then I am taken to the correct section, which is hightlighted:

![image](https://github.com/mdn/content/assets/5368500/f8df91dd-5c45-4d74-afb1-8a8ac9bb03d5)

If I then click the next link https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#browser_compatibility I am taken to where I expect.

![image](https://github.com/mdn/content/assets/5368500/2746c24f-a440-41fe-9f70-5eb970561f24)

So these links both work as expected and if they don't I'd say it was a browser issue, not an MDN issue.

**Comment by gusega** [comment]
I just clicked on the link from my mobile (chrome) amd that wont correctly
scroll to the fragment location either

Op vr 8 sep. 2023 04:45 schreef Hamish Willee ***@***.***>:

**Comment by hamishwillee** [comment]
If the link target is already shown when the page is loaded it doesn't necessarily scroll, but the target text should be slightly highlighted. Either way, this is not an MDN defect.

It may be a browser issue - you could test with this URL https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#:~:text=downgrade:-,the%20referer,be%20sent,-to%20origins (which will need to scroll to be displayed). In this case you could raise a bug against Chrome browser.

**Comment by gusega** [comment]
The link you provided opens and scrolls to the fragment correctly. Thanks I will open the issie with chrome.

**Comment by hamishwillee** [comment]
Thanks. If that link text is visible when chrome opens the link (the original link) then there is no bug to report. The browser has to scroll it into view if it is not visible, not if it is visible.

**Comment by gusega** [comment]
I think this may be the cause of the issue https://bugs.chromium.org/p/chromium/issues/detail?id=1417660&q=component%3ABlink%3EScroll
