### ISSUE TITLE
Reconciling base64 in Data URLs to URL-safe base64

### ISSUE THREAD

**Issue by FrugalGuy** [mdn/content#28974]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs

### What specific section or headline is this issue about?

Encoding data into base64 format

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs#encoding_data_into_base64_format says:

> [Encoding data into base64 format](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs#encoding_data_into_base64_format) 
Base64 is a group of binary-to-text encoding schemes that represent binary data in an [ASCII](https://developer.mozilla.org/en-US/docs/Glossary/ASCII) string format by translating it into a radix-64 representation. By consisting only of ASCII characters, base64 strings are generally url-safe, and that's why they can be used to encode data in Data URLs.

This didn't sound right, given I know classic base64 is **not** URL-safe. The next paragraph says:

>[Encoding in JavaScript](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs#encoding_in_javascript)
The Web APIs have native methods to encode or decode to base64: [Base64](https://developer.mozilla.org/en-US/docs/Glossary/Base64).

Reading that reference link confirms:

> A common variant is "Base64 URL safe", which omits the padding and replaces +/ with -_ to avoid characters that might cause problems in URL path segments or query parameters.

This combination is pretty confusing, and the statement "base64 strings are generally url-safe" is simply untrue.

### What did you expect to see?

I expected to see some mention of why non-safe URL characters in base64 encoding are not an issue for Data URLs. Maybe worded like this:

> [Encoding data into base64 format](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs#encoding_data_into_base64_format) 
Base64 is a group of binary-to-text encoding schemes that represent binary data in an [ASCII](https://developer.mozilla.org/en-US/docs/Glossary/ASCII) string format by translating it into a radix-64 representation. By consisting only of printable characters, we can safely encode binary data in Data URLs.  Generally base64 is not URL-safe because it includes the characters `+` and `/`, but because Data URLs have no URL path segments or query parameters this encoding is safe in this context.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Glossary/Base64

> A common variant is "Base64 URL safe", which omits the padding and replaces +/ with -_ to avoid characters that might cause problems in URL path segments or query parameters.

### Do you have anything more you want to share?

Consider whether to add to https://developer.mozilla.org/en-US/docs/Glossary/Base64 this sentence:

Note that URL-safe base64 is not needed or supported in [Data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs#encoding_data_into_base64_format).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/basics_of_http/data_urls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/data_urls/index.md
* Last commit: https://github.com/mdn/content/commit/997a0ec66e1514b7269076195b2419db334e876e
* Document last modified: 2023-08-29T04:27:41.000Z

</details>

**Comment by Josh-Cena** [comment]
Base64 is "generally" safer than the raw binary, but indeed the paragraph should be more nuanced here.
