### ISSUE TITLE
Firefox: <hue-interpolation-method> page doesn't render example

### ISSUE THREAD

**Issue by sidewayss** [mdn/content#28986]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/hue-interpolation-method

### What specific section or headline is this issue about?

Examples/Result

### Firefox 117:
![image](https://github.com/mdn/content/assets/15235202/65c6c289-e48b-4c35-8508-675b86379195)

### Chrome 116:
![image](https://github.com/mdn/content/assets/15235202/5e1c1139-3017-46e6-8376-51dadb2eb467)

### What did you expect to see?

What Chrome displays

### Do you have anything more you want to share?

HTML/CSS don't throw errors or complain to the console much, so it's hard to tell what the offending item might be, otherwise I might have attempted to correct it...

**Comment by sidewayss** [comment]
fyi - The example here renders properly in Firefox: https://developer.mozilla.org/en-US/docs/Web/CSS/color-interpolation-method

Why are these two CSS types separate? Looks to me that one is used exclusively by `color-mix()`, the other is used exclusively by the gradient functions.  Are they used elsewhere?  Sorry, I know this isn't the W3C, but you all seem to know about these things, so I'm asking.

**Comment by sidewayss** [comment]
Commenting out the <color-interpolation-method> it renders in Firefox, see [this playground edit](https://developer.mozilla.org/en-US/play?id=lIKciakGox6VEPZEASydybWDP614gRHCDrmcXZapWc4l3XQJI8r%2Bx6O3KgBsv5V6nbVoN50e5yCGTTEq).

Yet similar text appears in the <color-interpolation-method> page and that renders properly.  If you copy that working text into this playground it fails to render.  See the `.hsl` class style [here](https://developer.mozilla.org/en-US/play?id=56PIckygWaC6vYCKt3QPW33fqFqWt3sVxaa2mJuW2ZdEXJ2haO%2FwEOiZmAcwMzzZQdmD8VyTQ8396aEJ).

The order of the arguments is different across these two pages, but it doesn't matter, that's not the problem.

I have assumed this is an issue with the docs page, not a Firefox issue...

**Comment by Josh-Cena** [comment]
Hi! As indicated in the [compat table](https://developer.mozilla.org/en-US/docs/Web/CSS/hue-interpolation-method#css.types.image.gradient.conic-gradient.hue_interpolation_method) right below, this feature isn't supported in Firefox yet.

FYI, you can view CSS errors in the inspector:

<img width="1034" alt="image" src="https://github.com/mdn/content/assets/55398995/2e3b83d7-3fab-4fce-9aae-9e6d57355aa3">

**Comment by sidewayss** [comment]
Thanks for the info.  I should have scrolled farther down the page.  Yet it works in the `<color-interpolation-method>` page's example.

**Comment by yarusome** [comment]
@sidewayss What you mentioned about `<color-interpolation-method>` is a fair point, and I have added fallback styles for `<hue-interpolation-method>` like the other page has in #28943.
