### ISSUE TITLE
Issue with "Blob.text()": Opera is supporting blob.text()

### ISSUE THREAD

**Issue by T410** [mdn/content#2898]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Blob/text

#### What information was incorrect, unhelpful, or incomplete?
The `Browser compatibility` section shows that Opera is not supporting this method

#### Specific section or headline?
Browser compatibility

#### What did you expect to see?
I expected to see that `blob.text()` will not work on Opera

#### Did you test this? If so, how?
I have tested this code block in Opera's developer console and it works.
```
const blob = new Blob([JSON.stringify({hello: "world"}, null, 2)], {type : 'application/json'});
const text = await blob.text();
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/blob/text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Blob/text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/blob/text/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by CreaTorAlexander** [comment]
This would then also affect this table https://caniuse.com/?search=blob 
Because it says also that it isn't supporting it.

**Comment by Ryuno-Ki** [comment]
The compat table is maintained in https://github.com/mdn/browser-compat-data/blob/320ed5108b7f4831f72d7f28cf62b90c262b4fb8/api/Blob.json - please fill an issue there.

**Comment by Rumyra** [comment]
Hi @T410 just wondering if you filed this issue with browser compat data as mentioned above - thanks 🙏

**Comment by T410** [comment]
Hey @Rumyra, thanks for reminding me 🙏. Just filled the issue now
https://github.com/mdn/browser-compat-data/issues/9469

**Comment by Rumyra** [comment]
Yay - thanks so much @T410 🎉
