### ISSUE TITLE
Typo and missing link in the article Starting our Svelte to-do list app

### ISSUE THREAD

**Issue by Junaid-1993** [mdn/content#28994]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_Todo_list_beginning

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_Todo_list_beginning#accessibility_features_of_the_to-do_list

### What information was incorrect, unhelpful, or incomplete?

1) In the section [Accessibility features of the to-do list](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_Todo_list_beginning#accessibility_features_of_the_to-do_list) of article [Starting our Svelte to-do list app](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_Todo_list_beginning) the second code snippet which represents `ul` element in the **Svelte** has a typo in the attribute that is it says `className` instead of `class`:

```
<ul
  role="list"
  className="todo-list stack-large"
  aria-labelledby="list-heading">
```
I think this section was copied from the **React** tutorial article which has the same code snippet. **React** uses `className` but **Svelte** uses `class`. I think we should change it like so:

```
<ul
  role="list"
  class="todo-list stack-large"
  aria-labelledby="list-heading">
```
2) Also the paragraph below this code snippet mentions **Scott O'Hara's article "Fixing Lists"** exactly like in the **React** article's [Accessibility features](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_todo_list_beginning#accessibility_features) section but here the link is missing it is not in the `anchor` tag. We should also provide a link to the article.

### What did you expect to see?

`class` attribute instead of `className` in the **svelte** code snippet and provide a link for **Scott O'Hara's article "Fixing Lists"**

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_Todo_list_beginning
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by Aditi002-holo** [comment]
Hi, can I work on this issue? Let me know. Thanks.
