### ISSUE TITLE
Two Missing Members

### ISSUE THREAD

**Issue by ToBeJazz** [mdn/content#28998]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Manifest

### What specific section or headline is this issue about?

Members

### What information was incorrect, unhelpful, or incomplete?

These members are missing:
"lang"
"dir"

### What did you expect to see?

The members "lang" and "dir"

### Do you have any supporting links, references, or citations?

https://w3c.github.io/manifest/#web-application-manifest

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/manifest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/manifest/index.md
* Last commit: https://github.com/mdn/content/commit/0c015b80f786ecc4547c3e37a70c7f6aafdfbf74
* Document last modified: 2023-06-28T16:16:20.000Z

</details>

**Comment by ToBeJazz** [comment]
Also, the member "dir" is missing.

**Comment by Josh-Cena** [comment]
Thanks for the issue, please see https://github.com/mdn/content/pull/26306
