### ISSUE TITLE
Issue with "X-Frame-Options": …

### ISSUE THREAD

**Issue by plynchnlm** [mdn/content#290]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

#### What information was incorrect, unhelpful, or incomplete?
The page renders blank in Edge.
Edge version: Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

#### Did you test this? If so, how?
Edge's developer tools reports this exception:
[object Error]: {description: "Object doesn't support property or method 'flat'", message: "Object doesn't support property or method 'flat'", number: -2146827850, stack: "TypeError: Object doesn't support property or method 'flat' at Anonymous function (https://developer.mozilla.org/static/js/6.1f772781.chunk.js:1:12198) at H (https://developer.mozilla.org/static/js/6.1f772781.chunk.js:1:12157) at al (https://developer.mozilla.org/static/js/2.cb5ec81e.chunk.js:2:102598) at Vl (https://developer.mozilla.org/static/js/2.cb5ec81e.chunk.js:2:112253) at Hi (https://developer.mozilla.org/static/js/2.cb5ec81e.chunk.js:2:155944) at Cu (https://developer.mozilla.org/static/js/2.cb5ec81e.chunk.js:2:142339) at Ou (https://developer.mozilla.org/static/js/2.cb5ec81e.chunk.js:2:142273) at xu (https://developer.mozilla.org/static/js/2.cb5ec81e.chunk.js:2:142136) at mu (https://developer.mozilla.org/static/js/2.cb5ec81e.chunk.js:2:139100) at Anonymous function (https://developer.mozilla.org/static/js/2.cb5ec81e.chunk.js:2:88479)"}

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/x-frame-options`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/headers/x-frame-options/index.html
* Report started: 2020-12-16T12:53:02.307Z

</details>

**Comment by hamishwillee** [comment]
@chrisdavidmills This is a browser/infrastructure error (non rendering page in a particular browser). The version reported (Edge 44) is old - version 77 works fine. 

IMO this version is too old to bother with. Should this be closed "not going to fix" or be raised against the Yari repo (after validation)?

**Comment by chrisdavidmills** [comment]
I doubt the engineers will get round to seriously looking into this; they've got much bigger problems to look into right now.
