### ISSUE TITLE
CHIPS no longer requires Path=/

### ISSUE THREAD

**Issue by GREsau** [mdn/content#29001]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies

### What specific section or headline is this issue about?

The note under "How does CHIPS work?"

### What information was incorrect, unhelpful, or incomplete?

> Partitioned cookies must be set with Secure and Path=/.

### What did you expect to see?

No requirement on the `Path` attribute - it used to be required to be `/` but this requirement was removed last year

### Do you have any supporting links, references, or citations?

The Path requirement was removed in https://github.com/privacycg/CHIPS/pull/49

### Do you have anything more you want to share?

The same (out-of-date) note is present on this page: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#partitioned_cookie

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/privacy/partitioned_cookies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/privacy/partitioned_cookies/index.md
* Last commit: https://github.com/mdn/content/commit/e74627e6fd9ba19696b918c2bdddfff8aa160787
* Document last modified: 2023-07-04T10:01:14.000Z

</details>

**Comment by Josh-Cena** [comment]
cc @chrisdavidmills—the referenced PR was merged far before https://github.com/mdn/content/pull/23495. I wonder if you were aware of that change?
