### ISSUE TITLE
Request's `input` argument does not follow the specification

### ISSUE THREAD

**Issue by Seblor** [mdn/content#29025]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Request/Request

### What specific section or headline is this issue about?

Parameter > `input`

### What information was incorrect, unhelpful, or incomplete?

> `input`
> Defines the resource that you wish to fetch. This can either be:
> [...]
> - A [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) object, **effectively creating a copy**.
> - [...]

The "effectively creating a copy" part is misleading. Here is what the spec says on the `input` parameter:

> request = new [Request](https://fetch.spec.whatwg.org/#dom-request)(input [, init])
> Returns a new request whose [url](https://fetch.spec.whatwg.org/#dom-request-url) property is input if input is a string, **and input’s [url](https://fetch.spec.whatwg.org/#dom-request-url) if input is a [Request](https://fetch.spec.whatwg.org/#request) object**.

So according to the spec, only the URL is ported over from the argument, nothing else (including the body for example, which would be expected according to the MDN description)

### What did you expect to see?

Replace the second element of the list with something akin to:

> A [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) object, using its URL to create the new Request.

### Do you have any supporting links, references, or citations?

Specification link: https://fetch.spec.whatwg.org/#ref-for-dom-request%E2%91%A0

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/request/request`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Request/Request
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/request/request/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by Seblor** [comment]
I could make the PR, but I'm not sure if I'm the one misunderstanding something.

**Comment by Josh-Cena** [comment]
PR welcome :)

**Comment by mzdr** [comment]
Just wondering, is the last paragraph on the Request page correct as well?

> You may also pass a [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) object to the Request() constructor to create a copy of the Request (This is similar to calling the [clone()](https://developer.mozilla.org/en-US/docs/Web/API/Request/clone) method.)
>  
> `const copy = new Request(myRequest);`

**Comment by Seblor** [comment]
I'm not sure either. After re-reading the spec, it does seem like the body should actually be copied over with other properties (starting at step 34 of the "new Request(input, init) constructor steps").

However, I do not know the exhaustive list of properties so I cannot say if actually is similar to the clone method.

**Comment by Josh-Cena** [comment]
Have you tested and found evidence otherwise, or is this all spec reading? Some tests would be appreciated.

**Comment by Seblor** [comment]
Chrome seems to cary over the `body`, but as seen in the issue referenced above, Bun doesn't seem to work that way. So I was checking around the spec and it was kind of unclear, whereas the MDN said that is behaves like the `clone()` method, which is not how the spec seems to frame it.

Basically, it boils down to whether JS is *supposed* to behave like the `clone()` method, if it was misinterpreted (or V8 took some liberties) or if Bun's has a bug and does not respect the spec.

**Comment by Josh-Cena** [comment]
Chrome is surely spec-compliant, otherwise you would see lots of bug reports already. Bun is new and implements its own set of web APIs, and it's highly possible that they made mistakes somewhere.

**Comment by mzdr** [comment]
@Seblor I think we can close this one, don’t we?

**Comment by Seblor** [comment]
Yeah, probably
