### ISSUE TITLE
Wrong Type

### ISSUE THREAD

**Issue by ToBeJazz** [mdn/content#29028]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Manifest/shortcuts

### What specific section or headline is this issue about?

Type

### What information was incorrect, unhelpful, or incomplete?

Even though the array contains objects the type should be "array", right ?

### What did you expect to see?

Type "Array"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/manifest/shortcuts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/shortcuts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/manifest/shortcuts/index.md
* Last commit: https://github.com/mdn/content/commit/0c015b80f786ecc4547c3e37a70c7f6aafdfbf74
* Document last modified: 2023-06-28T16:16:20.000Z

</details>

**Comment by proplayer919** [comment]
All (except null-prototype objects) objects in JavaScript inherit from the ``Object`` class (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)).

**Comment by ToBeJazz** [comment]
Then why is this type "Array" ?: https://developer.mozilla.org/en-US/docs/Web/Manifest/icons

**Comment by wbamberg** [comment]
Thanks for filing, @ToBeJazz ! Yes, it should be `Array`. Of course an array is also an object, but calling it an array is more helpful!
