### ISSUE TITLE
Differences between the displayed example and the associated links

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#29021]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning

### What information was incorrect, unhelpful, or incomplete?

Hello,

Some examples displayed on the page do not match the links provided.

This is the case, for example, for "Absolute positioning" with the link "https://mdn.github.io/learning-area/css/css-layout/positioning/3_absolute-positioning.html".
The associated source is consistent with this link.

### What did you expect to see?

Restore example/link consistency.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/css_layout/positioning`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/positioning/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>

**Comment by caugner** [comment]
I had a look and didn't see any major differences, but I found at least a minor one.

- The content has:
    https://github.com/mdn/content/blob/94b831a74e8f29ab59825dd3e97f389c3a335855/files/en-us/learn/css/css_layout/positioning/index.md?plain=1#L167-L171
- The learn area has (see [here](https://github.com/mdn/learning-area/blob/c754e63586d8d897ebee120fe4dcd320e1eefef1/css/css-layout/positioning/3_absolute-positioning.html#L39)):
    ```html
        <p class="positioned">Now I'm absolutely positioned, I'm not playing by the rules any more!</p>
    ```

@DomOBU Did you see any other differences except for the text of the yellow paragraph?

**Comment by caugner** [comment]
@DomOBU Thank you! Was this the only difference that you noticed, or were there others?

**Comment by estelle** [comment]
Thanks!
