### ISSUE TITLE
Issue with "Native messaging": Nothing happens when i send message in both direction.

### ISSUE THREAD

**Issue by ozaik** [mdn/content#2903]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging

#### What information was incorrect, unhelpful, or incomplete?
Native messaging example didn't work on mac.
When i lauch the [demo](https://github.com/mdn/webextensions-examples/tree/master/native-messaging)
I didn't got any error in the terminal. But when i tried send message to native app nothing happen.
Same from the native app. The message is correctly send but nothing is handled with the event listener in my add-on.
And i didn't got any error in the web browser console. The extension is correctly linked to the app but the message transfer seem to be blocked by the os.

I'm on macOS Big Sur Version 11.2.2
Firefox version : Version 86.0 (64 bits)
Native application using python : 3.8.2

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/native_messaging`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/native_messaging/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by caitmuenster** [comment]
Hi @ozaik, have you tried asking for help about this on the [community forum](https://discourse.mozilla.org/c/add-ons/development/108)?
