### ISSUE TITLE
Wrong explanation of the example inside Inline formatting context

### ISSUE THREAD

**Issue by xianshenglu** [mdn/content#29035]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Inline_formatting_context#core_concepts

### What specific section or headline is this issue about?

Core concepts

### What information was incorrect, unhelpful, or incomplete?

> In the example below, the two ([`<div>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div)) elements with the black borders form a [block formatting context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context), inside which each word participates in an inline formatting context.

### What did you expect to see?

> In the example below, inside the two ([`<div>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div)) elements, each word participates in an inline formatting context.

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/questions/16381473/is-a-block-formatting-context-created-by-an-element-with-a-border

### Do you have anything more you want to share?

The definition of [BFC](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context)

**Comment by Rumyra** [comment]
For anyone picking up this issue reword

> In the example below, the two ([<div>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div)) elements with the black borders form a [block formatting context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context)

to

> In the example below, the two ([<div>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div)) elements (shown with black borders) form a [block formatting context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context)

To avoid confusion

**Comment by PrajwalBorkar** [comment]
> For anyone picking up this issue reword
> 
> > In the example below, the two `<div>` elements with the black borders form a [block formatting context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context)
> 
> to
> 

> To avoid confusion

Hi @Rumyra Can you explain if I need to modify the changes because the line mentioned here 
> > In the example below, the two `<div>` elements (shown with black borders) form a [block formatting context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context)

does not match with the changes proposed.

**Comment by xianshenglu** [comment]
@PrajwalBorkar @Rumyra  Hi, thanks for your responses.
To make it clear, I think the explanation "the two `div` elements form a BFC." is incorrect. They don't form a BFC according to the definition of [BFC](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context).

My concern is the content itself, not how it is expressed.

**Comment by Josh-Cena** [comment]
It should say

> the two (`<div>`) elements with the black borders are part of a [block formatting context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_display/Block_formatting_context), while each of them establishes an inline formatting context that each word participates in.

"Two divs form a BFC" is jarring, because a formatting context can only be established by a single container. Therefore the only logical interpretation is that it means to say "the collection of the two divs are part of a BFC".
