### ISSUE TITLE
Advanced HTML text task's finished example is missing title attribute on <abbr> elements

### ISSUE THREAD

**Issue by Amer-Adel** [mdn/content#29046]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_Advanced_HTML_text

### What specific section or headline is this issue about?

Task 2

### What information was incorrect, unhelpful, or incomplete?

"The finished example should look like this:" should edit:
1- adding the expansions to the `<abbr>` elements `title` attribute so they can display as tooltips and remove them from the plain text as you do in the second paragraph live code but doesn't in the finished example!

### What did you expect to see?

Here is the write code according to your task description:
```html
<blockquote cite="https://developer.mozilla.org/en-US/docs/Learn/Accessibility"><p><abbr title="Hypertext Markup Language">HTML</abbr> is by default accessible, if used correctly.</p></blockquote>

<p><abbr title="Cascading Style Sheets">CSS</abbr> can also be used to make web pages more, or less, accessible.</p>
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/test_your_skills_colon__advanced_html_text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_Advanced_HTML_text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/test_your_skills_colon__advanced_html_text/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>

**Comment by Josh-Cena** [comment]
Welcoming PRs to edit https://github.com/mdn/learning-area/blob/main/html/introduction-to-html/tasks/advanced-text/advanced-text2-finished.html

**Comment by SoundaryaKoutharapu** [comment]
@Josh-Cena 
I have opened a pr regarding the issue.
can you please look into it?

**Comment by SoundaryaKoutharapu** [comment]
Hello @caugner,

I noticed that my initial pull request, mdn/learning-area#667 addressing issue #29046, was opened before another PR, yet the second PR was ultimately merged. I'm reaching out to seek clarification and better understand the decision-making process.

Could you kindly provide insight into why the second PR, https://github.com/mdn/learning-area/pull/671, was favored for merging over the initial submission? This information would be valuable for me to align with project priorities and guidelines in the future.

Thank you for your time and consideration. Your guidance will help me contribute more effectively to the project.
