### ISSUE TITLE
docs: Using Native Keyboard Accessibility section out of date with MacOS Ventura.

### ISSUE THREAD

**Issue by ericrbg** [mdn/content#29050]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility

### What specific section or headline is this issue about?

Common accessibility issues (using_native_keyboard_accessibility)

### What information was incorrect, unhelpful, or incomplete?

For Firefox for Mac, it is told that tab focus doesn't work properly. For fixing this, it is suggested that you: "... open your Mac's System Preferences app, then go to Keyboard > Shortcuts, then select the All Controls radio button." However, since the Ventura upgrade, this is not the workflow, and so I am not sure how to change this.

### What did you expect to see?

A version of this solution that also works for MacOS Ventura.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/cross_browser_testing/accessibility`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/cross_browser_testing/accessibility/index.md
* Last commit: https://github.com/mdn/content/commit/7a81d16fadbe5cbee1ad2f8d0ddccda846f4034c
* Document last modified: 2023-08-24T08:40:42.000Z

</details>

**Comment by dipikabh** [comment]
The instructions need to be updated for Firefox and MacOS.

**Comment by ironnysh** [comment]
Hi, I'm using Firefox 121.0 on MacOS Sonoma (14.2.1 ), and it seems that by default, tabbing is enabled, and the _Always use the cursor keys to navigate within pages_ is unchecked.

In any case, the current steps to reach the required settings are:
- [Firefox](https://support.mozilla.org/en-US/kb/firefox-options-preferences-and-settings#w_general-panel): Open Settings/Preferences and scroll down to **Browsing**.
- [MacOS](https://support.apple.com/en-is/guide/mac-help/mchlp1399/14.0/mac/14.0)*: Open System Settings > Keyboard, and toggle **Keyboard Navigation** on or off.

*Relevant to Ventura and Sonoma

**Comment by schalkneethling** [comment]
Hey @ironnysh - Thank you for the information. I checked and it will solve the problem raised here. Do you want to open a pull request to fix the issue?

**Comment by ironnysh** [comment]
Hi @schalkneethling, thanks for confirming.
Sure, I'd love to, but it might take a day or two, though. Hope it's okay :-)

**Comment by ironnysh** [comment]
Hi @schalkneethling, all done!
