### ISSUE TITLE
Wrong type of ServiceWorkerRegistration.sync property in sidebar of Background Synchronization API

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#29059]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API

### What information was incorrect, unhelpful, or incomplete?

In {{DefaultAPISidebar("Background Sync")}} sidebar, the `ServiceWorkerRegistration.sync` is incorrectly marked as a method.

### What did you expect to see?

`ServiceWorkerRegistration.sync` should be a property.

### Do you have any supporting links, references, or citations?

See https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/sync

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/background_synchronization_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/background_synchronization_api/index.md
* Last commit: https://github.com/mdn/content/commit/7b3ccaec4a93584da12939587ea746acaabe30bc
* Document last modified: 2023-04-13T13:28:29.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing, @skyclouds2001 ! -> https://github.com/mdn/content/pull/29079.
