### ISSUE TITLE
Property lastPacketSentTimestamp does not exist on RTCOutboundRtpStreamStats

### ISSUE THREAD

**Issue by chingucoding** [mdn/content#29067]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/RTCOutboundRtpStreamStats/lastPacketSentTimestamp

### What specific section or headline is this issue about?

The entire page

### What information was incorrect, unhelpful, or incomplete?

The [WebRTC Specification](https://www.w3.org/TR/webrtc-stats/#dom-rtcoutboundrtpstreamstats) does not define a property called `lastPacketSentTimestamp`. The property also does not exist when polling WebRTC Stats in Chrome and inspecting the `outbound-rtp` object.

### What did you expect to see?

Not a property being documented that does in fact not exist.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/rtcoutboundrtpstreamstats/lastpacketsenttimestamp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCOutboundRtpStreamStats/lastPacketSentTimestamp
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/rtcoutboundrtpstreamstats/lastpacketsenttimestamp/index.md
* Last commit: https://github.com/mdn/content/commit/fbbef300a9a819cdda1171355da5787ad7cdbb6d
* Document last modified: 2023-06-05T21:54:44.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. Should be fixed by #29127
