### ISSUE TITLE
Text-wrap: balance (maximum number of lines)

### ISSUE THREAD

**Issue by KevinCocquyt39** [mdn/content#29065]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap

### What specific section or headline is this issue about?

text-wrap: balance

### What information was incorrect, unhelpful, or incomplete?

The documentation says it's maximum 4 lines or less, but in a recent video of Learn With Jason and Una Kravets, she tells that the Chromium team upped that number (but couldn't remember the exact number anymore).

### What did you expect to see?

The correct number of maximum lines although not sure where to look that up... Maybe by contacting the Chromium team?

### Do you have any supporting links, references, or citations?

https://www.youtube.com/watch?v=LjwNXASSfq8 (around the 30 minute mark).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/text-wrap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/text-wrap/index.md
* Last commit: https://github.com/mdn/content/commit/55f0d5d6ab74b22b3298ea33c10fabdbd996ce93
* Document last modified: 2023-07-12T15:05:03.000Z

</details>

**Comment by OnkarRuikar** [comment]
The [new limit is six](https://github.com/GoogleChrome/developer.chrome.com/pull/6844).

**Comment by estelle** [comment]
According to the specification, `text-wrap` is a shorthand property for `text-wrap-mode` and `text-wrap-style`. This entire document needs to be rewritten.

**Comment by Rumyra** [comment]
To whoever picks this up - check the ref doc against the spec and update

**Comment by dletorey** [comment]
This is in the [PR that I have submitted](https://github.com/mdn/content/pull/30435)

> `balance`
> Text is wrapped in a way that best balances the number of characters on each line, enhancing layout quality and legibility. Because counting characters and balancing them across multiple lines is computationally expensive, this value is only supported for blocks of text spanning a limited number of lines (**six for Chromium and ten for Firefox**).

**Comment by estelle** [comment]
This seems to have been addressed in https://github.com/mdn/content/pull/30435, so closing. Please feel free to re-open or submit a new issue if there are additional questions or issues. Thanks.
