### ISSUE TITLE
svg mask-image is totally not working 

### ISSUE THREAD

**Issue by bcjohnblue** [mdn/content#29068]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Applying_SVG_effects_to_HTML_content

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/SVG/Applying_SVG_effects_to_HTML_content#example_masking

### What information was incorrect, unhelpful, or incomplete?

The [Example: Masking](https://developer.mozilla.org/en-US/docs/Web/SVG/Applying_SVG_effects_to_HTML_content#example_masking) section doesn't work in Chrome and Safari.  

Chrome 
The background color is not from the svg mask-image.
<img width="760" alt="image" src="https://github.com/mdn/content/assets/21099079/456b6c29-8b75-4d8f-b760-5ec27eb06a88">

Safari
It is totally not working and show nothing.
<img width="677" alt="image" src="https://github.com/mdn/content/assets/21099079/d8cb96ad-98e1-4c5d-8b0a-79373ccdbf87">

### What did you expect to see?

It should render the mask-image of svg.

### Do you have any supporting links, references, or citations?

The author of this article [mask-image](
https://css-tricks.com/almanac/properties/m/mask-image/#:~:text=It%20kinda%20looks%20like%20you%20could%20snag%20that%20SVG%20mask%20and%20apply%20it%20to%20other%20elements%20with%20mask%2Dimage%3A%20url(%23mask)%3B%20but%20I%20don%E2%80%99t%20find%20that%20actually%20works.%20It%20only%20works%20within%20SVG%2C%20and%20has%20a%20nasty%20side%20effect%20of%20entirely%20erasing%20an%20image%20if%20used%20outside%20the%20SVG.) also claim that the svg mask-image is not actually works.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/applying_svg_effects_to_html_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Applying_SVG_effects_to_HTML_content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/applying_svg_effects_to_html_content/index.md
* Last commit: https://github.com/mdn/content/commit/b4f998244660723175f8e06b5d77f68cfb1d1f1a
* Document last modified: 2023-03-06T23:38:10.000Z

</details>

**Comment by caugner** [comment]
Thanks for flagging, @bcjohnblue. 👍 

Firefox seems to be the only browser to render the mask correctly. Chrome and Safari only partially support masking (cf. the [BCD table](https://developer.mozilla.org/en-US/docs/Web/CSS/mask#browser_compatibility), click on the Chrome/Safari cells), which explains the rendering you see.

Interestingly, using the prefixed property `--webkit-mask` in Chrome results in the same rendering as Safari.

As these are browser bugs, I'm going ahead and close this issue.

PS: Unprefixed masking support for Chrome seems to be tracked in [bug 432153](https://bugs.chromium.org/p/chromium/issues/detail?id=432153).
