### ISSUE TITLE
Document limitation of ogg opus playback on firefox linux

### ISSUE THREAD

**Issue by itzexor** [mdn/content#29082]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers

### What specific section or headline is this issue about?

Containers#ogg

### What information was incorrect, unhelpful, or incomplete?

Firefox Linux has had a bug with ogg opus (but not webm opus) for at least 8 months now that I have reported with 0 responses. I suggest that this limitation is documented so that people like me don't waste our time attempting to use the format in a capacity that the browser cannot actually support.

### What did you expect to see?

Firefox Linux 64 bit with Ogg Opus specifically is limited to files shorter than 12h 35m 39s. If you try to play a file back longer than this, the length is truncated and exhibits seeking issues.

### Do you have any supporting links, references, or citations?

https://bugzilla.mozilla.org/show_bug.cgi?id=1810378

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/media/formats/containers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/media/formats/containers/index.md
* Last commit: https://github.com/mdn/content/commit/d68dc0cf0f0caff5572ce83cb28df898ac815e40
* Document last modified: 2023-08-16T21:34:20.000Z

</details>

**Comment by dipikabh** [comment]
We need to add a note about the current limitation of ogg opus files on Firefox Linux

**Comment by Berthje** [comment]
I can do this!
