### ISSUE TITLE
Singlequotes in JSON.parse()

### ISSUE THREAD

**Issue by ghost** [mdn/content#29088]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse

### What specific section or headline is this issue about?

JSON.parse() does not allow single quotes

### What information was incorrect, unhelpful, or incomplete?

According to https://datatracker.ietf.org/doc/html/rfc8259#section-7 there should be no need to escape singlequotes, which implies that they should be allowed, but JSON.parse() does not allow them.

### What did you expect to see?

I would expect singlequotes to be allowed at least, when they are escaped.

### Do you have any supporting links, references, or citations?

https://datatracker.ietf.org/doc/html/rfc8259#section-7

### Do you have anything more you want to share?

Even escaping singlequotes does not work.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/json/parse`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/json/parse/index.md
* Last commit: https://github.com/mdn/content/commit/dfaf34a863a88fa9260b71adddf832cd4c6aee47
* Document last modified: 2023-09-12T21:30:33.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! When we say "single quotes not allowed" and as the examples have testified, we mean they are not allowed as string literal delimiters. You can surely use them as literal characters inside string literals.

**Comment by jahr0** [comment]
Hi Josh-Cena, thanks for thy reply, but I guess it's not that accurate or I simply don't get it. In my code, I have to JSON.parse('{"Auf'm Eck 1":[{"flurstnr":"123","gemarkung":"Unbekannt","flstkennz":"01234","flur":"1"}]}'). Notice the single quote a) inside the first key as well as b) the obligatory singlequotes at the beginning and the end of the whole parsable. Without the singlequotes b) it is not possible to parse the string. I find it contradictory when you say, they are allowed inside string litarals, which is obviously not the case as my example a) states. What exactly do you mean? Do you have a solution? As a workaround, I have replaced the singlequote a) with the tick ´, but it is just a workaraound.

**Comment by Josh-Cena** [comment]
The sentence "JSON.parse() does not allow single quotes" says about one very specific case: you can't use single quotes as string literal delimiters. I.e. you cannot parse `{'foo': 1}`, but only `{"foo": 1}`. It doesn't say anything about the delimiters for the JSON string itself, nor what characters can a string literal contain inside.

**Comment by wbamberg** [comment]
> Hi Josh-Cena, thanks for thy reply, but I guess it's not that accurate or I simply don't get it. In my code, I have to JSON.parse('{"Auf'm Eck 1":[{"flurstnr":"123","gemarkung":"Unbekannt","flstkennz":"01234","flur":"1"}]}'). Notice the single quote a) inside the first key as well as b) the obligatory singlequotes at the beginning and the end of the whole parsable. Without the singlequotes b) it is not possible to parse the string. I find it contradictory when you say, they are allowed inside string litarals, which is obviously not the case as my example a) states. What exactly do you mean?

I might be misunderstanding you here, but it sounds like you are saying: trying to run this code:

```
JSON.parse('{"Auf'm Eck 1":[{"flurstnr":"123","gemarkung":"Unbekannt","flstkennz":"01234","flur":"1"}]}')
```

...gives an error, which is contrary to Josh's assertion that single quotes are allowed inside strings in JSON. Is that right?

If so, the problem with that code is that it's not a valid string, because JS interprets the second `'` as a string delimiter, and then the rest of the string doesn't make sense. Even just declaring that as a string won't work either, without getting JSON involved:

```
const s = '{"Auf'm Eck 1":[{"flurstnr":"123","gemarkung":"Unbekannt","flstkennz":"01234","flur":"1"}]}'
// Uncaught SyntaxError: unexpected token: identifier
```

If you change it so the argument to `parse()` is a valid string (for example by using backticks around the whole thing), you can include single quotes inside JSON strings just fine:

```
JSON.parse(`{"Auf'm Eck 1":[{"flurstnr":"123","gemarkung":"Unbekannt","flstkennz":"01234","flur":"1"}]}`) 
```

Escaping the single quotes inside the JSON strings, and using single quotes for the whole thing also works:

```
JSON.parse('{"Auf\'m Eck 1":[{"flurstnr":"123","gemarkung":"Unbekannt","flstkennz":"01234","flur":"1"}]}') 
```

...as does escaping all the double quotes around the JSON strings, and using double quotes for the whole thing:

```
JSON.parse("{\"Auf'm Eck 1\":[{\"flurstnr\":\"123\",\"gemarkung\":\"Unbekannt\",\"flstkennz\":\"01234\",\"flur\":\"1\"}]}") 
```
