### ISSUE TITLE
Provide examples for calling map() with three-parameter callback

### ISSUE THREAD

**Issue by 0wis** [mdn/content#29080]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

### What specific section or headline is this issue about?

Try It or Syntax

### What information was incorrect, unhelpful, or incomplete?

It was not clear to me that Array.prototype.map() callback function needed 3 parameters. 

### What did you expect to see?

At least an example in the Try it section with more than one parameter in the callback function, like : 
`// Using the index parameter`
`const map2 = array1.map((x, i) => x * i); `

`console.log(map2);`
`// Expected output: Array [0, 4, 18, 48]`

Maybe the Syntax definition should have one more line : 
`map(callbackFn(element, index, array), thisArg)`

### Do you have any supporting links, references, or citations?

The one item of the [example section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#examples) of the guide is giving some more explanation and a counter-exemple of what could happen if this point is not understood. This section is itself citing its [inspiring blogpost](https://wirfs-brock.com/allen/posts/166).

The [ECMAScript specification](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.map) is clearer.

### Do you have anything more you want to share?

Issue came while learning on [FreeCodeCamp](https://www.freecodecamp.org/), doing the ["Implement map on a prototype"](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype) challenge.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/map`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/map/index.md
* Last commit: https://github.com/mdn/content/commit/e01fd6206ce2fad2fe09a485bb2d3ceda53a62de
* Document last modified: 2023-09-07T01:45:56.000Z

</details>

**Comment by Josh-Cena** [comment]
In the [parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#parameters) section, we already gave the exact description of the three parameters. We can perhaps provide an example, but we can't change the syntax; your proposal isn't how the syntax works (that isn't how you would call `map()`). Did you miss the parameters description?
