### ISSUE TITLE
"Using the Notifications API" code does not show a notification

### ISSUE THREAD

**Issue by Archaeopteryx** [mdn/content#29109]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

### What specific section or headline is this issue about?

the code example at the end of page

### What information was incorrect, unhelpful, or incomplete?

The button "View live result of the example above" opens a blank page but it should have a button "Notify me!".
If one clicks the "Play" button at the top of the JS code box and the button there, no notification is shown but the console on that page logs:
InvalidAccessError: A parameter or an operation is not supported by the underlying object

### What did you expect to see?

Notification(s)

### Do you have anything more you want to share?

Applies to both Firefox and Chrome

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/notifications_api/using_the_notifications_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/notifications_api/using_the_notifications_api/index.md
* Last commit: https://github.com/mdn/content/commit/381c51574a3e6a07ee09c63493452440f046038d
* Document last modified: 2023-08-24T22:17:15.000Z

</details>

**Comment by hamishwillee** [comment]
When I try clicking the link in MDN the runner page (live result) is completely empty and reports an error:

>  "Clear-Site-Data header on 'https://live.mdnplay.dev/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API/runner.html?id=tag_example': Unrecognized type: "*"."

@wbamberg Any idea on how we're supposed to debug this kind of thing?

**Comment by wbamberg** [comment]
> When I try clicking the link in MDN the runner page (live result) is completely empty and reports an error:
> 
> > "Clear-Site-Data header on 'https://live.mdnplay.dev/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API/runner.html?id=tag_example': Unrecognized type: "*"."
> 
> @wbamberg Any idea on how we're supposed to debug this kind of thing?

No idea, it's a black box for me. I assume this is a regression caused by the Play feature. We could file it as a bug there. Or we could get these things working by porting them to GH live samples.

**Comment by hamishwillee** [comment]
I vote for porting to GH live examples. Unfortunately the last case I tried that I ran into MDN CSP restrictions. We really need a way to set CSP within examples on an per-page basis. I've asked :-(.

Someone should try that at least. I've added Help wanted. Might look at it later in the month if no one else does.

**Comment by Josh-Cena** [comment]
Cross linking https://github.com/mdn/content/issues/31194 and https://github.com/mdn/content/issues/34103 — I think these three have the same issue

**Comment by Josh-Cena** [comment]
I've opened https://github.com/mdn/content/issues/34350 to fix these issues systematically. We'll make sure they work
