### ISSUE TITLE
Issue with "Cross-Origin Resource Sharing (CORS)": (short summary here please)

### ISSUE THREAD

**Issue by jamiecahill** [mdn/content#2911]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

#### What information was incorrect, unhelpful, or incomplete?
The link [Server-Side Access Control (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) simply points back to this page. Is this intended?

#### Specific section or headline?
Examples of Access Control Scnearios
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#examples_of_access_control_scenarios

#### What did you expect to see?
I expected a link to a different page that detailed server side CORS

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/index.html
* Last commit: https://github.com/mdn/content/commit/7a1b21998c8c4dc473b1ab14e38c4079d1695b24
* Document last modified: 2021-03-02T09:32:02.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. Fixed by deleting the paragraph in #2913. The doc was removed at some point and redirected (back) to this page. 

FYI there is an issue somewhere to add a flaw checker to help us spot these kind of self links. Should be along sometime soon.
