### ISSUE TITLE
Typing mistake

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#29110]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Practical_positioning_examples

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Practical_positioning_examples#styling_our_tabs

### What information was incorrect, unhelpful, or incomplete?

Hello,

You should certainly read:
.info-box li a:active {
instead of
.info-box li a**.**active {

The mistake also appears on the fr page. It should appear in all translations of the page.

### What did you expect to see?

Replace . by :

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/css_layout/practical_positioning_examples`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Practical_positioning_examples
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/practical_positioning_examples/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>

**Comment by SoundaryaKoutharapu** [comment]
@DomOBU Hey, Can I tackle this one if it's up for grabs.

**Comment by wbamberg** [comment]
Thanks for filing, @DomOBU , but I think this is not a mistake.

From the prose:

> Secondly, we'll set a rule that puts the same styling on one of the tabs when a **class** of active is present on it. 

...and later on in the JS:

> A **class** of active is set on the tab that was clicked on — remember from earlier that this class has an associated rule in the CSS that sets the same [color](https://developer.mozilla.org/en-US/docs/Web/CSS/color) and [background-color](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color) on the tab as the panels are styled with.

It is a bit confusing. The corresponding panel has a class of `active-panel`, we could call it `active-tab`. Or rename them both to `current-tab` and `current-panel`.

I guess a bigger worry is whether the techniques being taught here are not very current - if we were doing this today wouldn't we use grid or flexbox?
