### ISSUE TITLE
missing CSS Properties

### ISSUE THREAD

**Issue by ToBeJazz** [mdn/content#29111]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column

### What information was incorrect, unhelpful, or incomplete?

Missing CSS Properties:
grid-column-gap
grid-gap
grid-row-gap

### What did you expect to see?

To see the CSS Properties both in the list and on their own pages.

### Do you have anything more you want to share?

Is it a coincidence that the three missing properties are for "gap" something ?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/grid-column`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/grid-column/index.md
* Last commit: https://github.com/mdn/content/commit/5e7d1f9ae2cce0cb3f7693dfb8dc6e8d375b2231
* Document last modified: 2023-07-18T00:16:24.000Z

</details>

**Comment by ToBeJazz** [comment]
I now see that those three properties were renamed...

**Comment by Josh-Cena** [comment]
That's right. It comes up if you search for it:

<img width="1110" alt="image" src="https://github.com/mdn/content/assets/55398995/ad3b83ff-0523-448f-9a87-5262ffc21e8c">
