### ISSUE TITLE
Arrow function | Invocation context

### ISSUE THREAD

**Issue by a-brcic** [mdn/content#29132]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

### What information was incorrect, unhelpful, or incomplete?

class SomeClass {
  constructor() {
    this.name = "Something Good";
  }

  register() {
    const that = this; // Do we need const that = this since arrow functions inherit this value of the function that contains them?
    window.addEventListener("keydown", (e) => {
      that.someMethod(e);
    });
  }

  someMethod(e) {
    console.log(this.name);
    switch (e.keyCode) {
      case 5:
        // some code here…
        break;
      case 6:
        // some code here…
        break;
    }
  }
}

const myObject = new SomeClass();
myObject.register();

### What did you expect to see?

class SomeClass {
  constructor() {
    this.name = "Something Good";
  }

  register() {
    window.addEventListener("keydown", (e) => {
      this.someMethod(e);
    });
  }

  someMethod(e) {
    console.log(this.name);
    switch (e.keyCode) {
      case 5:
        // some code here…
        break;
      case 6:
        // some code here…
        break;
    }
  }
}

const myObject = new SomeClass();
myObject.register();

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/eventtarget/addeventlistener`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/eventtarget/addeventlistener/index.md
* Last commit: https://github.com/mdn/content/commit/3f6726b293a7ae1a428db4a983ebfd2826750ce5
* Document last modified: 2023-09-14T09:44:11.000Z

</details>

**Comment by Josh-Cena** [comment]
This comes from our migration to arrow functions. PRs welcome, but please be careful to align the code with the existing description.

**Comment by a-brcic** [comment]
Sure, thanks.
https://github.com/mdn/content/pull/29150
