### ISSUE TITLE
Issue with "Web technology for developers": (short summary here please)

### ISSUE THREAD

**Issue by Attila111111** [mdn/content#2915]
MDN URL: https://developer.mozilla.org/en-US/docs/Web

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/index.html
* Last commit: https://github.com/mdn/content/commit/f99dbe91376f2861bf7c0469b51001a2434cc3c7
* Document last modified: 2021-02-03T17:13:49.000Z

</details>

**Comment by hamishwillee** [comment]
Closing as there is no information on an issue to be fixed.

**Comment by Attila111111** [comment]
`

`
