### ISSUE TITLE
Wrong Text

### ISSUE THREAD

**Issue by 11AMER** [mdn/content#29152]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Debugging_HTML

### What specific section or headline is this issue about?

summary

### What information was incorrect, unhelpful, or incomplete?

This also marks the end of the Introduction to HTML module learning articles — now you can go on to testing yourself with our assessments: the first one is linked below.

### What did you expect to see?

In the next article we will learn how to "Marking up a letter"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/debugging_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Debugging_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/debugging_html/index.md
* Last commit: https://github.com/mdn/content/commit/8d0cbeacdc1872f7e4d966177151585c58fb879e
* Document last modified: 2023-08-02T17:32:22.000Z

</details>

**Comment by ChristianCCastro** [comment]
Tienes razón ayudame

**Comment by hamishwillee** [comment]
Thanks, but the existing text is correct. 

The

**Comment by hamishwillee** [comment]
IS
