### ISSUE TITLE
Clarify wording around "string representation" in console.* related functions

### ISSUE THREAD

**Issue by jcbhmr** [mdn/content#29172]
<details><summary>old text</summary>

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/console/assert

### What specific section or headline is this issue about?

The part about passing in objects

### What information was incorrect, unhelpful, or incomplete?

What should this print?
```js
console.assert(false, { a: 1 })
```

In the spec text https://console.spec.whatwg.org/#assert it would _seem_ (from my limited understanding) that it should forward everything to `Logger()` and it should print `Assertion failed  ▶ { a: 1 }` like most other console methods do. That's what Chrome and Firefox do at least.

![image](https://github.com/mdn/content/assets/61068799/2b1f5ace-5f6f-4b91-b9bc-731a31c98cb7)
![image](https://github.com/mdn/content/assets/61068799/c3cf19ae-0431-45d5-aa81-35312c5e1e77)

...but then on MDN there's this text: https://developer.mozilla.org/en-US/docs/Web/API/console/assert

![image](https://github.com/mdn/content/assets/61068799/263e1528-e5a7-44fe-bd3c-1d24e35e52cf)
![image](https://github.com/mdn/content/assets/61068799/2f3f096a-ac4b-4617-b11d-55ced2b75c93)

which reads (to me at least; i could be mistaken) that passing `console.assert(false, {a:1},{b:2})` will do `String()` or similar on each of those `{a:1}` objects
...which would seem to indicate that Node.js has the right idea:
![image](https://github.com/mdn/content/assets/61068799/932e51f0-3ac8-4e7a-aa77-a3ee88d9daaf)

idk man, I'm just a bit confused which one is "right" 😂

### What did you expect to see?

Rephrase the text to be a bit more clear on whether "The string representations of each of these objects are appended together in the order listed and output." means _perform string coercion_ or _print a fancy object repr_.

or idk maybe a little note or some screenshots of what happens sorta like https://developer.mozilla.org/en-US/docs/Web/API/console#using_groups_in_the_console which has a very nice image

or maybe a little note about how Node.js has a slightly different way of doing it 🤷‍♂️

### Do you have any supporting links, references, or citations?

https://console.spec.whatwg.org/#assert
<img width=300 src="https://github.com/nodejs/node/assets/61068799/0fd91b8a-18be-477b-830f-2eb1758c7aad">
<img width=300 src="https://github.com/nodejs/node/assets/61068799/e3b7a32d-f5e8-4a1b-9540-4f5021e0351f">

https://github.com/nodejs/node/issues/49680

https://github.com/whatwg/console/issues/77

</details>

Right now in a lot of the console.* methods there's this type of language used:
![image](https://github.com/mdn/content/assets/61068799/e2a289b5-8eea-49eb-94c6-8defd0c3af07)

This is potentially confusing. It seems to indicate that said objects will all be `.toString()`-ed and concatenated together, sorta like this:
```js
// obj1 … objN
// A list of JavaScript objects to output. The string representations of each
// of these objects are appended together in the order listed and output.
console.info = (...objN) => {
  underlyingPrint(objN.map(x => String(x)).join(" "))
}
```

but that's obviously NOT what it means to convey. Instead, it means to convey that these objects are "inspected" or "pretty printed" and then "shown" (not necessarily "printed") to the console in the specified order.

The issue at hand: Should this change?

If so, here's an idea:

<table><th>before <th>after
<tr><td>

obj1 … objN
A list of JavaScript objects to output. The string representations of each of these objects are appended together in the order listed and output.

<td>

obj1 … objN
A list of non-string values to inspect in the console. The method of inspection is implementation defined. Browser consoles have interactive consoles, while text-based output may pretty-print the objects.

</table>

idk tho. something more clear like that

affected pages that i could find:
- https://developer.mozilla.org/en-US/docs/Web/API/console/info
- https://developer.mozilla.org/en-US/docs/Web/API/console/warn
- https://developer.mozilla.org/en-US/docs/Web/API/console/error
- https://developer.mozilla.org/en-US/docs/Web/API/console/debug
- https://developer.mozilla.org/en-US/docs/Web/API/console/assert

console.trace() has a pretty decent description https://developer.mozilla.org/en-US/docs/Web/API/console/trace
> objects Optional
> Zero or more objects to be output to console along with the trace. These are assembled and formatted the same way they would be if passed to the [console.log()](https://developer.mozilla.org/en-US/docs/Web/API/console/log) method.

**Comment by OnkarRuikar** [comment]
> 2 Let message be a string without any formatting specifiers indicating generically an assertion failure (such as "Assertion failed").
>
> 4.2 If [Type](https://tc39.github.io/ecma262/#sec-ecmascript-data-types-and-values)(first) is not String, then [prepend](https://infra.spec.whatwg.org/#list-prepend) message to data.

As per the specs data objects are to be appended to a string (message). So the NodeJS's output `Assertion failed: [object Object]` is correct as per the specs.
```
const obj = {a:1};
const message = "Assertion failed: " + obj;
// Assertion failed: [object Object]
```
Unlike NodeJs, browsers can show interactable objects in the logs.  Because the console logs are part of the developer tools in browsers, it is a good feature to show the objects like that. It saves us from doing `console.assert(false, JSON.strigify(obj))`.

**Comment by jcbhmr** [comment]
@OnkarRuikar Isn't `...data` an _array_ though? 🤔 'cause you can definitely pass as much stuff as you want like `console.assert(false, ...Array.from({length:100}).fill({}))`

![image](https://github.com/mdn/content/assets/61068799/dc1ab156-26a9-4bb7-850c-884714d6d3f8)
![image](https://github.com/mdn/content/assets/61068799/1c103476-2014-4b95-a897-f4fa8ef219f1)

its just that first bit that's a bit off.

and then  "If [Type](https://tc39.github.io/ecma262/#sec-ecmascript-data-types-and-values)(first) is not String, then [prepend](https://infra.spec.whatwg.org/#list-prepend) message to data." just prepends that  "Assertion failed" message to the data array? right?

```js
function assert(condition, ...data) {
  if (condition) return
  const message = "Assertion failed"
  if (data.length === 0) {
    data.push(message)
  } else {
    const first = data[0]
    if (typeof first !== "string") {
      data.unshift(message)
    } else {
      const concat = message + ": " + first
      data[0] = concat
    }
  }
  Logger("assert", data)
}
```

---

> Unlike NodeJs, browsers can show interactable objects in the logs. Because the console logs are part of the developer tools in browsers, it is a good feature to show the objects like that. It saves us from doing console.assert(false, JSON.strigify(obj)).

you're correct, however Node.js does do some inspection like `console.log({a:1})` shows a fancy `{ a: 1 }` prettyprint instead of just `[object Object]` which is nice and i was wondering which was correct in the `console.assert()` case.

**Comment by Josh-Cena** [comment]
Note that console spec is not a strict spec, per se—it's an attempt to find the greatest common divisor of all existing implementations. Therefore a lot of things are left very ambiguous, and so is the documentation... I'm inclined to say this is a bug in Node.

**Comment by jcbhmr** [comment]
I got my answer about "which is correct" from the whatwg/console folks: https://github.com/whatwg/console/issues/226#issuecomment-1725454190

I've switched this issue title/text to be focused on **improving the wording about "string representation concatenated together"** which is more on-topic as far as MDN content is concerned. 👍

let me know your thoughts! ❤
