### ISSUE TITLE
docs: Clarify @container Behavior Regarding Height in Query Conditions

### ISSUE THREAD

**Issue by thedevsouvik** [mdn/content#29180]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@container

### What specific section or headline is this issue about?

On these section [Logical keywords in container queries](https://developer.mozilla.org/en-US/docs/Web/CSS/@container#logical_keywords_in_container_queries)

### What information was incorrect, unhelpful, or incomplete?

While demonstrating multiple conditions can be applied in container query with ```or``` keyword there has a condition related to css ```height``` property, which is a totally misinformation, because currently ```container query``` doesn't have the ability to style base on height of the container element.

Check it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/@container#browser_compatibility:~:text=%40container%20%28width%20%3E%20400px%29%20and%20%28height%20%3E%20400px%29%20%7B%0A%20%20/*%20%3Cstylesheet%3E%20*/%0A%7D%0A%0A%40container%20%28width%20%3E%20400px%29%20or%20%28height%20%3E%20400px%29%20%7B%0A%20%20/*%20%3Cstylesheet%3E%20*/%0A%7D)

### What did you expect to see?

These could be something like these 
```
@container (width > 400px) or (width < 800px)
```
instead of 
```
@container (width > 400px) or (height > 400px)
````
Or it could be great if it has support for css ```HEIGHT``` property as well like ```WIDTH``` in container query condition.

### Do you have any supporting links, references, or citations?

[Docs Reference Link](https://developer.mozilla.org/en-US/docs/Web/CSS/@container#browser_compatibility:~:text=%40container%20%28width%20%3E%20400px%29%20and%20%28height%20%3E%20400px%29%20%7B%0A%20%20/*%20%3Cstylesheet%3E%20*/%0A%7D%0A%0A%40container%20%28width%20%3E%20400px%29%20or%20%28height%20%3E%20400px%29%20%7B%0A%20%20/*%20%3Cstylesheet%3E%20*/%0A%7D)

### Do you have anything more you want to share?

It could be more interesting if it have support for css ```HEIGHT``` property as well like ```WIDTH``` in container query.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@container`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@container
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@container/index.md
* Last commit: https://github.com/mdn/content/commit/3d4edafe934c84878d2a46d8c22911ba351b7261
* Document last modified: 2023-07-18T02:17:17.000Z

</details>

**Comment by OnkarRuikar** [comment]
@thedevsouvik the spec does list `height` as size feature: https://drafts.csswg.org/css-contain-3/#height

**Comment by thedevsouvik** [comment]
@OnkarRuikar Thanks for pointing that out!
You're right, the ```height``` property in ```container queries``` isn't widely supported yet, but ya its mentioned in the spec (draft).
