### ISSUE TITLE
Shambolic

### ISSUE THREAD

**Issue by CodaCodr** [mdn/content#29197]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/display

### What specific section or headline is this issue about?

All of it

### What information was incorrect, unhelpful, or incomplete?

All of it!

### What did you expect to see?

A regular, well-put-together MDN document. Helpful but succinct prose describing the many and various properties for `display`. This reads like a half dozen different people wrote it, after a few too many beers, late on a Friday night.

### Do you have any supporting links, references, or citations?

Just try to find in-depth info on, for example, `display:table-cell`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/display`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/display
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/display/index.md
* Last commit: https://github.com/mdn/content/commit/c77cfcd17e85db6c1b93160c70668f2ff6c2809c
* Document last modified: 2023-07-20T07:38:29.000Z

</details>

**Comment by wbamberg** [comment]
I'm closing this. If you'd like to report problems with this or any other page, please do it politely and with respect for the people who contribute to the site.

**Comment by CodaCodr** [comment]
@wbamberg. Sure. Go ahead. That'll be sure to fix it.
