### ISSUE TITLE
[CSS] implement :focus-visible pseudo-class (rename/alias :-moz-focusring)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#292]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. `:focus-visible`

## Related Gecko bugs

1. - [x] [implement :focus-visible pseudo-class (rename/alias :-moz-focusring)](https://bugzilla.mozilla.org/show_bug.cgi?id=1445482) — probably a fairly small task; the [:focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) page is already pretty up-to-date, probably just needs a rel note and a BCD update? Check the page too...

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
I think this is complete, I've set the bug to dev-doc-complete.

**Comment by chrisdavidmills** [comment]
Yup, agreed!

**Comment by hamishwillee** [comment]
FYI https://github.com/mdn/content/pull/1388
