### ISSUE TITLE
SpeechSynthesisUtterance event.elapsedTime returns milliseconds, not seconds

### ISSUE THREAD

**Issue by josephrocca** [mdn/content#29214]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/end_event

### What information was incorrect, unhelpful, or incomplete?

This:
```
`Utterance has finished being spoken after ${event.elapsedTime} seconds.`
```
should say milliseconds instead of seconds. Just tested it to confirm, and elapsedTime is indeed milliseconds as I suspected.

### What did you expect to see?

See above.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/speechsynthesisutterance/end_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/end_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/speechsynthesisutterance/end_event/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! It is very useful if you could provide the browser version for testing, as everything can vary between browsers. In this case you should read https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisEvent/elapsedTime as there's a historical change that Chrome doesn't implement yet.
