### ISSUE TITLE
undefined relList

### ISSUE THREAD

**Issue by yuanyq-Cloud** [mdn/content#29224]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement/relList

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

```html
const links = document.getElementsByTagName("link");
const length = links.length;
for (const link of links) {
  const listLength = list.length;
  console.log("New link found.");
  relList.forEach((relEntry) => {
    console.log(relEntry);
  });
}
```

### What did you expect to see?

```html
for (const link of links) {
  const relList = link.relList;
  console.log("New link found.");
  relList.forEach((relEntry) => {
    console.log(relEntry);
  });
}
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmllinkelement/rellist`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement/relList
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmllinkelement/rellist/index.md
* Last commit: https://github.com/mdn/content/commit/595cba0e07c70eda7f08a12890e00ea0281933d3
* Document last modified: 2023-04-07T00:32:52.000Z

</details>

**Comment by Josh-Cena** [comment]
We just need to change `relList.forEach` to `link.relList.forEach`; no need for the extra declaration.
