### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#29235]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_images/Using_CSS_gradients

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_images/Using_CSS_gradients#plaid_gradient

### What information was incorrect, unhelpful, or incomplete?

Hello,

I usually use the fr pages .
I regularly consult the en-us pages.

In the "Plaid gradient" example, when comparing with the version of the fr page, isn't there duplicate code at the end of the source of the example ?

### What did you expect to see?

If necessary, remove the duplicate code.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_images/using_css_gradients`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_images/Using_CSS_gradients
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_images/using_css_gradients/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by Josh-Cena** [comment]
There are two `background` properties, but as the description states, this is intentional:

> In the first background declaration we listed every color stop separately. The second background property declaration using the multiple position color stop syntax:

Because support for the multiple position color stop syntax is less universal, this means older browsers will fall back to the first declaration when the second fails to parse. This also helps with conceptual understanding of the syntax.
