### ISSUE TITLE
`Element.requestPointerLock()` conflict of Standard

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#29259]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock

### What information was incorrect, unhelpful, or incomplete?

Pointer Lock 2.0 standard still require Element.requestPointerLock() to be a sync function and does not return a promise
Also, it does not support passing the `options` parameter

Though many browsers has already accomplish those behaviors, see https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock#browser_compatibility

### What did you expect to see?

Maybe it is better to mark standard behavior in main body and unstandard behavior in additonal content, for example, in a note

### Do you have any supporting links, references, or citations?

https://w3c.github.io/pointerlock/#extensions-to-the-element-interface

![image](https://github.com/mdn/content/assets/95597335/99d7398a-ef65-4db0-98ea-5c3404eeaa73)

https://github.com/mdn/content/issues/11327

Additional lock options to requestPointerLock (not merge yet) https://github.com/w3c/pointerlock/pull/49

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/requestpointerlock`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/requestpointerlock/index.md
* Last commit: https://github.com/mdn/content/commit/bbf7f25f9cf95fb154e2740a9fdc9c02818981bf
* Document last modified: 2023-04-07T05:55:26.000Z

</details>

**Comment by zfox23** [comment]
Oh man! This is a deceptively complex issue.

There's a tension between four things here:
1. [The draft specification for "`Element.requestPointerLock()` 2.0"](https://w3c.github.io/pointerlock/#dom-element-requestpointerlock), which specifies that the function is **synchronous**.
2. The current browser implementation in Firefox, which is **synchronous** and returns `undefined`. This is opposite what the current MDN page says, and in-line with the draft specification linked in (1)!
3. The current browser implementations in all browsers _except_ Firefox, which is **asynchronous** and returns a `Promise`. This is what the current MDN content documents.
4. The note in the MDN content, which states: "Note: Some browsers do not yet support the promise version of requestPointerLock(),". The "yet" implies that browsers will begin implementing the **async** version of this API, when it's actually likelier that browsers will begin implementing the **synchronous** version of the API...maybe?

So perhaps the right thing to do is one or more of:
1. Move the "...Some browsers do not yet support..." note to the top of the page.
2. Change the note to make no mention of time (i.e. remove "yet" and "older").
3. Change the note to direct people to the BCD table to make sure they're implementing this functionality based on their target browsers.
4. Change the note to mention that the specification for this feature is changing, and browser vendors may decide to change their implementation at any time.

WDYT?

**Comment by Rumyra** [comment]
Yes @zfox23 that sounds like the right thing to do 👍
