### ISSUE TITLE
Precedence for postfix incremental and assignment operators.

### ISSUE THREAD

**Issue by VovaSv** [mdn/content#29269]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence

### What specific section or headline is this issue about?

Precedence for postfix incremental and assignment operators.

### What information was incorrect, unhelpful, or incomplete?

It's not clear the precedence for postfix incremental and assigement operators.
According to table the **postfix incremental** 'i++' has higher precedence then assigment '='.

But in example below the precedence  work differently.
let i = 1;
let result = i++;
//result = 1, i =2

Can you please add more clarification for this section or I missed something?

### What did you expect to see?

 More clear explanation for this section.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/operator_precedence/index.md
* Last commit: https://github.com/mdn/content/commit/4c26e8a3fb50d06963b06017f51ce19364350564
* Document last modified: 2023-08-11T08:07:46.000Z

</details>

**Comment by Josh-Cena** [comment]
Operator precedence merely affects the grouping of expressions (i.e. where parentheses are implicitly added). It doesn't tell you about the return values of each expression. Postfix operators always returns the operands value and _then_ increments. Please read https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Increment

Also, note that the `=` in `let x = 1` is not an assignment operator. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let

If `=` has higher precedence than `++`, then your expression would become `(result = i)++`, which is illegal syntax.

**Comment by VovaSv** [comment]
**Thank you for your answer.** 

1) Regarding assignment: 
We just could took such example:
```
line 0: let i = 0;
line 1:  i = i++;
```

When JS newcomers see the precedence table list, they see postfix increment has precedence (15) and assignment (2) so automatically this will lead to scenario like (I will do increment then assignment although postfix increment return  it's value then increment).
Maybe at least need add some notes regarding this scenario.

2) If we will take example below again:
line 0: let i = 0;
line 1: let result = 0;
line 3:  result = i++;

So correct precedence scenario for this I think is as below and we can add such notes in table list: 
Postfix: when **result = i++;**  is basically  **i = (result = i) + 1** 
Prefix: when **result = ++i;**  is basically  **result = i = i + 1** 
Please correctly me if I'm wrong.

**Comment by Josh-Cena** [comment]
Again, precedence doesn't tell you about what an expression returns. It tells you the order in which they are evaluated. This is made very clear on this page already.

**Comment by VovaSv** [comment]
Hi,
I'm not talking about  what an expression returns in scope of precedence and so on, just wanted to check if possible to add more clarifications or some notes regarding combination of (prefix/postfix and assignment).

I just saw questions related to this topic in many forums, stackoverflow and Udemy courses when people explain it slightly wrong without understands the main concept with reference to 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence.

If you say that "This is made very clear on this page already" so I'm ok with this.

Thank you for your time.
