### ISSUE TITLE
The link to the posted message on Twitter is broken

### ISSUE THREAD

**Issue by yin1999** [mdn/content#29268]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Security_vulnerability_response

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Security_vulnerability_response#steps_taken

### What information was incorrect, unhelpful, or incomplete?

The link written [here](https://github.com/mdn/content/blob/197ae3ed1a9fc06927dee66e892fcffb059b9d91/files/en-us/mdn/community/contributing/security_vulnerability_response/index.md?plain=1#L34) is broken.

### What did you expect to see?

I could not find the retweeted message, not sure how should we fix this.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community/contributing/security_vulnerability_response`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Security_vulnerability_response
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/contributing/security_vulnerability_response/index.md
* Last commit: https://github.com/mdn/content/commit/aa66311219951396e7305df61eb31831360d2c79
* Document last modified: 2023-02-24T01:20:34.000Z

</details>

**Comment by wbamberg** [comment]
I think it would be OK to delete the link.

**Comment by yin1999** [comment]
> I think it would be OK to delete the link.

Or, should we replace this with the link to [MozDevNet](https://twitter.com/MozDevNet).

**Comment by wbamberg** [comment]
TBH I'm not that sure what the point of this page is. Perhaps is a kind of playbook for maintainers to know how to respond to these kinds of issues? Either way I don't think linking to the mozdevnet Twitter account in general, or the specific retweet, really adds much. It would be fine just to say something like "We raised awareness of this issue by tweeting from our official Twitter account."
