### ISSUE TITLE
Specificity of button:not(#mainBtn, .cta) is given as 1-0-1

### ISSUE THREAD

**Issue by prakharanand2000** [mdn/content#29276]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

### What specific section or headline is this issue about?

under the Specificity section in the selector, identifiers, classes, elements, total specificity table

### What information was incorrect, unhelpful, or incomplete?

Specificity of button:not(#mainBtn, .cta) is given as 1-0-1

### What did you expect to see?

button:not(#mainBtn, .cta) has 1 element due to the button type selector, 1 class due to the .cta class selector and 1 identifier due to the #mainBtn id selector. The pseudo-class not() does not contribute to the specificity. Hence, the specificity should be 1-1-1 instead of 1-0-1.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
* Last commit: https://github.com/mdn/content/commit/5f0a9e8c258072ed8146401584162c232331c77d
* Document last modified: 2023-09-15T00:23:30.000Z

</details>

**Comment by Josh-Cena** [comment]
Please read https://developer.mozilla.org/en-US/docs/Web/CSS/:not. There are two selectors combined here: `button` and `:not()`. The specificity of the latter is the specificity of the most specific selector in its arguments list, in this case an ID selector, so the `:not()` selector also has the specificity of an ID selector, making this selector 1-0-1 overall. The class selector is not counted.
