### ISSUE TITLE
Obsolete link

### ISSUE THREAD

**Issue by AdusGaming** [mdn/content#29272]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/development_environment

### What specific section or headline is this issue about?

Other Python tools

### What information was incorrect, unhelpful, or incomplete?

The link to django aware linters is obsolete

### What did you expect to see?

The django aware linters website or link, but the target website apparently has restructured

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/django/development_environment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/development_environment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/development_environment/index.md
* Last commit: https://github.com/mdn/content/commit/6b01400b286e8bdfa7060d56af84757dd4b8de48
* Document last modified: 2023-07-31T00:02:50.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. I don't think this link is necessary in any case, so have removed in#29274
