### ISSUE TITLE
Missing property `WindowClient.ancestorOrigins`

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#29281]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WindowClient

### What information was incorrect, unhelpful, or incomplete?

Missing property `WindowClient.ancestorOrigins`

### What did you expect to see?

Adding a page for `WindowClient.ancestorOrigins`, and update the description of `WindowClient` interface

### Do you have any supporting links, references, or citations?

https://w3c.github.io/ServiceWorker/#windowclient

![image](https://github.com/mdn/content/assets/95597335/a5bcbb86-aec1-44c2-aa41-834e54acbd25)

![image](https://github.com/mdn/content/assets/95597335/47e17e55-614e-4d98-ae94-9506a1fe7460)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/windowclient`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowClient
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/windowclient/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by hamishwillee** [comment]
@skyclouds2001 Thanks. Yes it is definitely time for this page to be created, or at very least a descriptive entry to be added to this page. Were you interested in creating a PR to contribute?

**Comment by skyclouds2001** [comment]
> @skyclouds2001 Thanks. Yes it is definitely time for this page to be created, or at very least a descriptive entry to be added to this page. Were you interested in creating a PR to contribute?

Got it , I will do this in a few days
