### ISSUE TITLE
Navigator.permissions always returns prompt on firefox mobile. Even after the permission is granted.

### ISSUE THREAD

**Issue by rahul002211** [mdn/content#29291]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/permissions

### What information was incorrect, unhelpful, or incomplete?

This api doesn't work on firefox mobile

### What did you expect to see?

Should've worked on firefox mobile. But it doesn't

### Do you have any supporting links, references, or citations?

fff

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/permissions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/permissions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/permissions/index.md
* Last commit: https://github.com/mdn/content/commit/ef75c1741b450c2331204be5563ee964ad5f4c48
* Document last modified: 2023-04-07T06:16:45.000Z

</details>

**Comment by Josh-Cena** [comment]
We need a way to reproduce it so we can know whether it's a bug in FF or something worth documenting.
