### ISSUE TITLE
Reporting API page describes v0 API and should mention the v1 API

### ISSUE THREAD

**Issue by jyasskin** [mdn/content#29292]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Reporting_API

### What information was incorrect, unhelpful, or incomplete?

The page describes the `Report-To` HTTP header, but the spec it links to, https://w3c.github.io/reporting/, doesn't mention that header anymore. The [Chrome implementation status](https://web.dev/reporting-api/) post says that's the legacy Reporting API.

### What did you expect to see?

Documentation for the current version of https://w3c.github.io/reporting/ and the [Reporting-Endpoints](https://w3c.github.io/reporting/#reporting-endpoints) header.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/reporting_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Reporting_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/reporting_api/index.md
* Last commit: https://github.com/mdn/content/commit/b0870830e4c02596ca6c501f8f8b468a917eafc2
* Document last modified: 2023-05-10T11:37:46.000Z

</details>

**Comment by Rumyra** [comment]
Adding this to the roadmap backlog

**Comment by Josh-Cena** [comment]
@hamishwillee FYI

**Comment by hamishwillee** [comment]
Thanks, this will be fixed by https://github.com/mdn/content/pull/35602, which is waiting on review.
