### ISSUE TITLE
<Switch> Statement Issue In react-router-dom

### ISSUE THREAD

**Issue by Muhammad-Umer-07** [mdn/content#29296]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/switch

### What specific section or headline is this issue about?

Switch component is no longer working using react-router@5.2.0

### What information was incorrect, unhelpful, or incomplete?

The developers are unaware that how to tackle this issue as you guys have not mentioned about this update in your documentation. If you can suggest and alternate, then that will be highly appreciated by the Dev community.

### What did you expect to see?

Updated Documentation

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/element/switch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/switch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/switch/index.md
* Last commit: https://github.com/mdn/content/commit/76600240fbe75e083e964bc3707cce81e99999c2
* Document last modified: 2023-05-22T06:13:12.000Z

</details>

**Comment by Josh-Cena** [comment]
Nowhere on MDN are we using react-router or `<Switch>`. The page you discovered is an SVG element, which is a browser API, not a react-router API. You would need to ask the RR team for more docs.
