### ISSUE TITLE
[JS] `Intl.Collator` `collation` constructor option 

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#293]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. `Intl.Collator` `collation` constructor option. Not yet documented on [Collator()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/Collator) constructor page, will need adding, perhaps with an example, and updated BCD?

## Related Gecko bugs

1. - [x] [Add support for a "collation" property to the options-bag passed to Intl.Collator](https://bugzilla.mozilla.org/show_bug.cgi?id=1670062)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
There is a good description of what this change means in https://github.com/tc39/ecma402/issues/380

- [ ] BCD: https://github.com/mdn/browser-compat-data/pull/8471
- [ ] Interactive example:  https://github.com/mdn/interactive-examples/pull/1748 - NOTE this is not of collation, but is showing an "option".
- [ ] Docs: https://github.com/mdn/content/pull/788
- [ ] Note to inform Dev team: https://bugzilla.mozilla.org/show_bug.cgi?id=1670062#c5

FYI some other minor fixes to docs in there to0 - e.g. caseFirst option was not documented.

@chrisdavidmills Ready for review at your convenience.

**Comment by chrisdavidmills** [comment]
OK, set to dev-doc-complete, and closing!
