### ISSUE TITLE
Document that MouseEvent.movementX/movementY are 0 for events other than `mousemove`

### ISSUE THREAD

**Issue by mnoorenberghe** [mdn/content#29315]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementX

### What information was incorrect, unhelpful, or incomplete?

> movementX/movementY must be zero for all mouse events except mousemove.

https://w3c.github.io/pointerlock/#dom-mouseevent-movementx

This should be documented as I tried to use it for `mouseenter`.

### What did you expect to see?

"movementX/movementY must be zero for all mouse events except `mousemove`."

### Do you have any supporting links, references, or citations?

https://w3c.github.io/pointerlock/#dom-mouseevent-movementx

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mouseevent/movementx`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementX
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mouseevent/movementx/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by Namchee** [comment]
Hi @Josh-Cena, may I contribute on this one?

**Comment by Josh-Cena** [comment]
No need to ask. If you want to work on it, just send a PR.
