### ISSUE TITLE
Window: beforeunload event: Clarify whether an empty string should trigger the confirmation dialog

### ISSUE THREAD

**Issue by ivangreene** [mdn/content#29314]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

### What specific section or headline is this issue about?

Examples, Compatibility notes

### What information was incorrect, unhelpful, or incomplete?

1. One of the examples shows setting `returnValue` to an empty string
2. The Compatibility notes says:
> When this event returns (or sets the returnValue property to) a value other than null or undefined, the user will be prompted to confirm the page unload

### What did you expect to see?

1. The empty string should not be recommended in the example (use a non empty string)
2. The empty string should be mentioned in the compatibility note (...value other than null or undefined **or the empty string**...)
3. Perhaps a compatibility row should be added to indicate the support for this

### Do you have any supporting links, references, or citations?

It appears that the empty string is no longer supported by Chrome as of 117: https://chromestatus.com/feature/4968823574233088

And [the spec it links to](https://html.spec.whatwg.org/multipage/browsing-the-web.html#checking-if-unloading-is-user-canceled) says:
> the `returnValue` attribute of event is not the empty string

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/beforeunload_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/beforeunload_event/index.md
* Last commit: https://github.com/mdn/content/commit/367358d6847aa1766344951207dfd79d5c073a66
* Document last modified: 2023-08-04T07:15:35.000Z

</details>

**Comment by Rumyra** [comment]
This page has been updated since this issue was raised - the above issue appears to have been rectified https://github.com/mdn/content/commit/5765d9697cdba4cdbcc45afd98f47ba3c1416024 - I'm closing 👍
