### ISSUE TITLE
++ and -- are the only postfix operators in JavaScript?

### ISSUE THREAD

**Issue by amarphule** [mdn/content#29322]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_operators

### What specific section or headline is this issue about?

Expressions and operators

### What information was incorrect, unhelpful, or incomplete?

++ and -- are the **_only postfix_** operators in JavaScript.

### What did you expect to see?

we can use ++ and -- operators as prefix as well as postfix.

### Do you have any supporting links, references, or citations?

Please check the document, in the description section 2nd and 3rd paragraphs we used the ++ and -- operators as prefix.
[For reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Increment#description)

### Do you have anything more you want to share?

```
let x = 9;
 x++;
 x++;
let postfixPlus = x;         // postfixPlus = 11
x-- ;
x--;
let postfixMinus = x;     // postfixMinus =  9

let  y = 5
++y;
++y;
let prefixPlus = y;      // prefixPlus = 7
--y;
--y;
let prefixMinus = y;   // prefixMinus  = 5
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/expressions_and_operators`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_operators
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/expressions_and_operators/index.md
* Last commit: https://github.com/mdn/content/commit/d71b141d2d18b96639547856714df19cefacfebf
* Document last modified: 2023-08-12T02:11:54.000Z

</details>

**Comment by Josh-Cena** [comment]
"++ and -- are the only postfix operators in JavaScript." and "++ and -- are only postfix operators" are two sentences. The former means there are no other postfix operators (which is true). The latter means these two in particular cannot be anything other than postfix (which is false).
