### ISSUE TITLE
Missing parameters for console.dir() 

### ISSUE THREAD

**Issue by mitz-lad** [mdn/content#29329]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/console/dir

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

There are further parameters to`console.dir` I knew there was a way to show all values for nested items but couldn't find the documentation for it. I'm not sure what other options are available.

### What did you expect to see?

Something to describe `console.dir(obj, { depth: null });` and if there are any other options me or other people are unaware of.

### Do you have any supporting links, references, or citations?

I finally found the answer on this article https://dev.to/samueldjones/using-console-dir-to-print-javascript-objects-in-the-console-3jkh

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/console/dir`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/console/dir
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/console/dir/index.md
* Last commit: https://github.com/mdn/content/commit/d76defab4ca13261e9de81ae1df125345f847b0a
* Document last modified: 2023-04-07T05:46:57.000Z

</details>

**Comment by vrun1208** [comment]
Hi, @Josh-Cena, If no one is working on this one, I would like to work

**Comment by wbamberg** [comment]
Thanks for filing!

The first thing to say about this is that console has very variable support among browsers: there's a basic set of features they all support, then different browsers add all kinds of extra features of their own.

As the MDN page says:

> The console.dir() static method displays an interactive list of the properties of the specified JavaScript object. The output is presented as a hierarchical listing with disclosure triangles that let you see the contents of child objects.

This does show "all values for nested items", you just have to expand them. I've checked this in Chrome and Firefox, using the `nestedObject` referenced in the article you linked (https://dev.to/samueldjones/using-console-dir-to-print-javascript-objects-in-the-console-3jkh).

I don't see that passing `{ depth: null }` in Chrome makes any difference, I get the exact same output with or without it. In Firefox it looks like it thinks the options object is another object to render, which might be a Firefox bug. But I don't see the behavior described in the article, in any browser. Do you? Which browsers do you see it in?

**Comment by Josh-Cena** [comment]
Cross-posting from our private conversation: I checked Chrome source code and my current conclusion is that Chrome does not use the `options` parameter at all, although unlike Firefox it also only prints the first argument.

**Comment by mitz-lad** [comment]
This would be relevant to server console behaviour, my assumption was that you have node.js listed in the compatibility table so the information would be relevant. Another assumption I'm making here is that all information related to a method e.g.`console.dir` is reported and are not restricted to just functionality available in browsers. Although I can see why omitting irrelevant information may serve majority of users. 

In my case I was expecting that everything there is to know about `console.dir` would be available on this page.

**Comment by wbamberg** [comment]
> This would be relevant to server console behaviour, my assumption was that you have node.js listed in the compatibility table so the information would be relevant. 

It is, but neither this issue nor the linked blog post mentioned that this was a Node-specific thing. I think we should probably document this option ([and the others](https://nodejs.org/docs/latest/api/console.html#consoledirobj-options)) in the page, and add some subfeatures into BCD to describe the support for them.
