### ISSUE TITLE
Issue with "Element: touchmove event": (short summary here please)

### ISSUE THREAD

**Issue by Mewarcreations** [mdn/content#2932]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/touchmove_event

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/touchmove_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/touchmove_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/touchmove_event/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by CreaTorAlexander** [comment]
And what is the issue with the touchmove event that you have observed?

**Comment by sideshowbarker** [comment]
@Mewarcreations Do you a suggestion about some part of https://developer.mozilla.org/en-US/docs/Web/API/Element/touchmove_event that you believe should be updated or changed?

**Comment by sideshowbarker** [comment]
Closing for lack of response.
