### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by kamal1958** [mdn/content#29330]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Home_page

### What specific section or headline is this issue about?

runserverr

### What information was incorrect, unhelpful, or incomplete?

I could not find my problem. I received this error 
![image](https://github.com/mdn/content/assets/114066288/22a1e05c-f3f6-405b-8d34-303a0ba19cca)
<img width="960" alt="first" src="https://github.com/mdn/content/assets/114066288/087f9ba9-a71d-4916-b583-e92d2baa6fc2">

### What did you expect to see?

this
![image](https://github.com/mdn/content/assets/114066288/161c777b-8043-4934-9a34-447e3b6007a4)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/django/home_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Home_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/home_page/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by hamishwillee** [comment]
Did you follow the instructions in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website#hooking_up_the_url_mapper ?

Specifically the instruction to add this code:
```
# Use include() to add paths from the catalog application
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]
```

Include is added by the import above.

**Comment by kamal1958** [comment]
it is already added
    On Friday, 29 September 2023 at 04:01:17 am GMT+3, Hamish Willee ***@***.***> wrote:  
 
 


Did you follow the instructions in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website#hooking_up_the_url_mapper ?

Specifically the instruction to add this code:
# Use include() to add paths from the catalog application
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

Include is added by the import above.

**Comment by hamishwillee** [comment]
I think you might be saying that you already have this line and you are still getting the error. In that case I can't help you directly - I know the tutorial works, because I have worked through it. Perhaps the next step might be for you to check your code against the test version: https://github.com/mdn/django-locallibrary-tutorial
