### ISSUE TITLE
Inaccurate description of metrics retrieval from first available font in `font-size-adjust`

### ISSUE THREAD

**Issue by drott** [mdn/content#29339]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust

### What specific section or headline is this issue about?

Description of usage of first available font.

### What information was incorrect, unhelpful, or incomplete?

> Uses the <number> value for the specified <font-metric> from the first available font that is able to provide the desired metric. 

This sentence is not accurate. `from-font` uses the value from the first available font, whether it has the value or not. If it does not, a value is likely synthesized. 

### What did you expect to see?

Strip the last part of the sentence.

### Do you have any supporting links, references, or citations?

See also https://github.com/w3c/csswg-drafts/issues/6384

https://drafts.csswg.org/css-fonts-5/#font-size-adjust-prop:~:text=Computes%20to%20the%20%3Cnumber%3E%20corresponding%20to%20the%20specified

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-size-adjust`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-size-adjust/index.md
* Last commit: https://github.com/mdn/content/commit/75d94518e16b4354cd57f74f13710ca27791019a
* Document last modified: 2023-09-25T16:24:26.000Z

</details>

**Comment by OnkarRuikar** [comment]
The discussion https://github.com/w3c/csswg-drafts/issues/6384 hasn't concluded yet. But it makes sense to keep the value consistent with the first available font.
