### ISSUE TITLE
captureVisibleTab not working in mv3

### ISSUE THREAD

**Issue by neelabh-smartbear** [mdn/content#29338]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureVisibleTab

### What information was incorrect, unhelpful, or incomplete?

<all_urls> needs to be specified under host_permissions in mv3 and also after doing that too captureVisibleTab is coming as undefined.
Pls update the docs as per mv3

### What did you expect to see?

Docs should specify the correct way as per mv3 

### Do you have any supporting links, references, or citations?

no experimented and it didn't 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/tabs/capturevisibletab`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureVisibleTab
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/tabs/capturevisibletab/index.md
* Last commit: https://github.com/mdn/content/commit/d6856a051d0ba078ec1d24b80908b1ca174917db
* Document last modified: 2023-03-07T05:27:34.000Z

</details>

**Comment by rebloor** [comment]
@neelabh-smartbear I see that you have noted that the [related bugzlla item](https://bugzilla.mozilla.org/show_bug.cgi?id=1855677) can be closed. Also, the documentation states. "Your extension can check whether it has all the required permissions immediately after installation using [permissions.contains](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/contains). If it doesn't have the necessary permissions, it can request them using [permissions.request](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request). Providing an onboarding step to explain why some permissions are necessary before requesting them might also be helpful."
