### ISSUE TITLE
browser.webRequest.filterResponseData does not exist

### ISSUE THREAD

**Issue by CadmanW** [mdn/content#29354]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

when i test my extension using the extension tester in about:debugging , I get an error saying that browser.webRequest.filterResponceData(); is not a function. the exact error i get is as follows:

TypeError: browser.webRequest.filterResponseData is not a function

### What did you expect to see?

correct documentation

### Do you have anything more you want to share?

```js
// this is my background script
function listener(details) {
    let filter = browser.webRequest.filterResponseData(details.requestId);

    filter.ondata = (event) => {
        // my code
    };
};

browser.webRequest.onBeforeRequest.addListener(
    listener,
    {
        urls: ["https://exampleurl.com"],
    }
);
```
### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
* Last commit: https://github.com/mdn/content/commit/03d9b93f9ecb9cf805e3b017bd24fe60e33b8c10
* Document last modified: 2023-07-14T00:48:26.000Z

</details>

**Comment by CadmanW** [comment]
in my code i spelled response correctly, i just misspelled it in the "What information was incorrect, unhelpful, or incomplete?" section on accident.

**Comment by hamishwillee** [comment]
Are you saying it is not a function? The error just means that the function is not present - are you using a [supported browser](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData#browser_compatibility) - firefox?

**Comment by CadmanW** [comment]
Yes I'm using the latest version of Firefox, but for some reason I'm
getting an error saying that it's not a function, when I'm very certain it
is a function

**Comment by hamishwillee** [comment]
@rebloor Is this something you can advise on?

**Comment by CadmanW** [comment]
I solved the issue, my vsc was corrupted and it was storing bad data,
re-download it ad it works 👍
