### ISSUE TITLE
Issue with "Text": Text.assignedSlot is listed twice

### ISSUE THREAD

**Issue by pufferfish101007** [mdn/content#2935]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Text

#### What information was incorrect, unhelpful, or incomplete?
The read-only property Text.assignedSlot is listed twice, with slightly differing definitions for each.

#### Specific section or headline?
Proerties

#### What did you expect to see?
One definition of Text.assignedSlot.

#### Did you test this? If so, how?
n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/text/index.html
* Last commit: https://github.com/mdn/content/commit/0e626a4ff6dbc6c68f6c0ede4765a10baf4fc9ff
* Document last modified: 2021-02-10T11:28:11.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this :+1:

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills what does needs-triage mean?

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander we are soon starting to run a proper triage process on new issues, adding better information to them that will help contributors fix bugs more easily. 

But it doesn't mean you can't pick up an issue. If you know what to do already and want to take it on, I'm happy to assign you.

**Comment by CreaTorAlexander** [comment]
In the spec it says

> 4.2.2.3. Finding slots and slottables
> To find a slot for a given slottable slottable and an optional open flag (unset unless stated otherwise), run these steps:
> 
> If slottable’s parent is null, then return null.
> 
> Let shadow be slottable’s parent’s shadow root.
> 
> If shadow is null, then return null.
> 
> If the open flag is set and shadow’s mode is not "open", then return null.
> 
> Return the first slot in tree order in shadow’s descendants whose name is slottable’s name, if any, and null otherwise.
https://dom.spec.whatwg.org/#find-a-slot

So I would prefer to leave the first 

> Text.assignedSlot Read only
> Returns a HTMLSlotElement representing the <slot> the node is inserted in.
https://developer.mozilla.org/en-US/docs/Web/API/Text


What do you think?

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander yeah, the first one sounds like a better definition. I did wonder if we should say something about the conditions under which it returns null, but I think that information can be left for the actual `assignedSlot()` page.
