### ISSUE TITLE
External link points to broken site

### ISSUE THREAD

**Issue by JackieChainnn** [mdn/content#29368]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events

### What specific section or headline is this issue about?

[HTML5 and Server-sent events] (https://dsheiko.com/weblog/html5-and-server-sent-events/) in Other Resource section

### What information was incorrect, unhelpful, or incomplete?

This site does not work because of hosting problem

### What did you expect to see?

You should fix the error or replace by a new source.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/server-sent_events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/server-sent_events/index.md
* Last commit: https://github.com/mdn/content/commit/c2274293475b0a5b4febf85a49c1f91bf43ebac7
* Document last modified: 2023-05-03T02:24:26.000Z

</details>

**Comment by Josh-Cena** [comment]
We could probably remove a few other links on this page too. I'll discuss.
