### ISSUE TITLE
Issue with "Web fonts": (Font Squirrel website not working)

### ISSUE THREAD

**Issue by martian1431** [mdn/content#2936]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts

#### What information was incorrect, unhelpful, or incomplete?
The Webfont generator link is not working. I cannot access www.fontsquirrel.com.

#### Specific section or headline?
Generating the required code

#### What did you expect to see?
I expected to be taken to the Webfont generator website

#### Did you test this? If so, how?
1. I made sure my internet is working.
2. I tried to ping the site that is hosting the Webfont generator.
3. Cleared browser history.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/styling_text/web_fonts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/styling_text/web_fonts/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by rachelandrew** [comment]
The Font Squirrel website appears to be loading now so I think this must have been a temporary thing.

**Comment by chrisdavidmills** [comment]
Phew! I rely on that site such a lot ;-)
