### ISSUE TITLE
Cookie Examples Broken

### ISSUE THREAD

**Issue by Josh-Grafman** [mdn/content#29370]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

None of the examples for setting and showing cookies seem to be working properly. I would check all of them on this page.

### What did you expect to see?

Expected outputs and behavior from all the examples on the page.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document/cookie`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/cookie/index.md
* Last commit: https://github.com/mdn/content/commit/e8850ae74ede8d67f643a857a8c236d66f757f73
* Document last modified: 2023-09-24T23:47:14.000Z

</details>

**Comment by Josh-Cena** [comment]
What doesn't work as expected? Could you provide your browser version and screenshots?
