### ISSUE TITLE
Navigator permissions query midi status always set to prompt

### ISSUE THREAD

**Issue by mrybak834** [mdn/content#29372]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/requestMIDIAccess

### What specific section or headline is this issue about?

Security requirements

### What information was incorrect, unhelpful, or incomplete?

In the function on the page:

```
navigator.permissions.query({ name: "midi", sysex: true }).then((result) => {
  if (result.state === "granted") {
    // Access granted.
  } else if (result.state === "prompt") {
    // Using API will prompt for permission
  }
  // Permission was denied by user prompt or permission policy
});
```

the result state is never "granted", rather always "prompt", after obtaining midi access like so:

```
let midi = null;
navigator.requestMIDIAccess().then(onMIDISuccess, onMIDIFailure);

function onMIDISuccess(midiAccess) {
  midi = midiAccess;

  navigator.permissions.query({ name: "midi", sysex: true }).then((result) => {...
}
```

### What did you expect to see?

Expected that `result.state` would be "granted" but it is always "prompt".

### Do you have anything more you want to share?

Firefox Developer Edition 119.0b3 (64-bit)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/requestmidiaccess`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/requestMIDIAccess
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/requestmidiaccess/index.md
* Last commit: https://github.com/mdn/content/commit/ef75c1741b450c2331204be5563ee964ad5f4c48
* Document last modified: 2023-04-07T06:16:45.000Z

</details>

**Comment by hamishwillee** [comment]
1. Do you have the https://support.mozilla.org/en-US/kb/site-permission-add-ons installed for Firefox?
2. Your code above does not request `sysex` in `MIDIOptions` - so you haven't actually asked for the correct permission you are later testing for.

**Comment by hamishwillee** [comment]
I'm going to close this because I think it is invalid based on ^^^^
