### ISSUE TITLE
Missing Specifications data of `FormData.entries()` and `FormData.keys()` and `FormData.values()`

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#29378]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FormData

### What information was incorrect, unhelpful, or incomplete?

For:
https://developer.mozilla.org/en-US/docs/Web/API/FormData/keys
https://developer.mozilla.org/en-US/docs/Web/API/FormData/values
https://developer.mozilla.org/en-US/docs/Web/API/FormData/entries
the specifications data is missing

### What did you expect to see?

Having Specifications data of `FormData.entries()` and `FormData.keys()` and `FormData.values()`

> Also I would like to fix this issue, but I'm not sure how to fix it

### Do you have any supporting links, references, or citations?

https://xhr.spec.whatwg.org/#formdata

```
interface FormData {
  ...
  iterable<USVString, FormDataEntryValue>;
}
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/formdata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FormData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/formdata/index.md
* Last commit: https://github.com/mdn/content/commit/00a9eb81f3e6dfb9776d1eaa2aa731c6ef5b657b
* Document last modified: 2023-05-08T21:25:02.000Z

</details>

**Comment by Josh-Cena** [comment]
Let's track this in https://github.com/mdn/content/issues/6891
