### ISSUE TITLE
Overscroll-Behavior is not working

### ISSUE THREAD

**Issue by mshajid** [mdn/content#29384]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior

### What information was incorrect, unhelpful, or incomplete?

I don't see any value in overscroll behavior such as none, contain, and auto. All those does the same. that's leading me to confusion and it doesn't help me to understand the variants of the overflow values. 

### What did you expect to see?

I expected to see the right output. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/overscroll-behavior`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/overscroll-behavior/index.md
* Last commit: https://github.com/mdn/content/commit/a4b661ab67e434b6737a826eab4260e3413d06c1
* Document last modified: 2023-09-06T03:25:27.000Z

</details>

**Comment by Josh-Cena** [comment]
Please give your browser version and screen recordings showing the behavior

**Comment by OnkarRuikar** [comment]
To experience this on a PC you need to use [mouse wheel to scroll inner element](https://www.youtube.com/watch?v=lkaWjWhMQ3E). Difference between `none` and `contain` can be observed only on devices that have [scroll bouncing effect](https://www.youtube.com/shorts/4EMYPY_qjTU) e.g. iphone, ipads etc.

**Comment by myselfprincee** [comment]
> To experience this on a PC you need to use [mouse wheel to scroll inner element](https://www.youtube.com/watch?v=lkaWjWhMQ3E). Difference between `none` and `contain` can be observed only on devices that have [scroll bouncing effect](https://www.youtube.com/shorts/4EMYPY_qjTU) e.g. iphone, ipads etc.

I guess Android phones also have this bouncy effect right ??

**Comment by estelle** [comment]
The try it at the top shows the values of auto, contain, and none. This issue is addressed in the page. Closing. If that wasn't the issue, please create a new issue with a bit more specifics so we know what needs to be addressed. Thanks.
