### ISSUE TITLE
Ambiguous text

### ISSUE THREAD

**Issue by 11AMER** [mdn/content#29396]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies

### What specific section or headline is this issue about?

Use HTTPS

### What information was incorrect, unhelpful, or incomplete?

Note: [GitHub pages](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/Using_GitHub_pages) allow content to be served via HTTPS by default, so it is useful for hosting content. If you are using a different hosting provider and are not sure, ask them about it.
--------
What is that I'm not sure about

### What did you expect to see?

...not sure about your hoisting security

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/other_embedding_technologies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.md
* Last commit: https://github.com/mdn/content/commit/8d0cbeacdc1872f7e4d966177151585c58fb879e
* Document last modified: 2023-08-02T17:32:22.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. Fixed by #29407
