### ISSUE TITLE
Since Firefox 52, DragEvent.dataTransfer becomes `null` when in debugger.

### ISSUE THREAD

**Issue by Iziminza** [mdn/content#29399]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/DragEvent

### What specific section or headline is this issue about?

Instance properties, dataTransfer

### What information was incorrect, unhelpful, or incomplete?

Since Firefox 52, this property becomes `null` when in debugger. This should be documented, since the fact that you are debugging should not normally change code behaviour!

### What did you expect to see?

Text like "Note that this property may be set to `null` when debugging in Firefox."

### Do you have any supporting links, references, or citations?

Yes: https://stackoverflow.com/questions/43180248/firefox-ondrop-event-datatransfer-is-null-after-update-to-version-52

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/dragevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DragEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/dragevent/index.md
* Last commit: https://github.com/mdn/content/commit/f45409ba2169ff05e433d21aa4ee0424079916b8
* Document last modified: 2023-02-20T07:35:10.000Z

</details>

**Comment by Josh-Cena** [comment]
Thanks for the information. We'll track this in https://github.com/mdn/content/issues/11670
