### ISSUE TITLE
Ambiguous text

### ISSUE THREAD

**Issue by Cxumhe** [mdn/content#29403]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts

### What specific section or headline is this issue about?

the description of unicode-range in the last **Note** block.

### What information was incorrect, unhelpful, or incomplete?

the referance page of the unicode-range CSS descriptor https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range says "If the page doesn't use any character in this range, the font is not downloaded; if it uses at least one, the whole font is downloaded.",but the guide said "in supporting browsers, only the specified characters will be downloaded".I don't know which is correct.

### What did you expect to see?

i want you to correct it.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/styling_text/web_fonts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/styling_text/web_fonts/index.md
* Last commit: https://github.com/mdn/content/commit/45268b07c84a04b45d46bcdf104e2b33be00adcf
* Document last modified: 2023-07-17T22:36:05.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you - good catch. The range indicates the characters which might be present in the font, and hence tells the browser whether it is worth downloading the font for a page. I.e. the reference is correct.

Fixed by https://github.com/mdn/content/pull/29408
