### ISSUE TITLE
Issue with "Document: drag event": example behaves strange around text selection

### ISSUE THREAD

**Issue by Janpot** [mdn/content#2941]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/drag_event

#### What information was incorrect, unhelpful, or incomplete?

The example behaves incorrectly in certain circumstances. This isn't exactly a critical bug, but people may inadvertently copy the example without realising it fails on edge-cases. Basically, it's possible to select the text inside the dive and drag that. I suppose in the `dragstart` event handler there should be a verification that the dragged element is the intended div and nothing else?

In firefox the text selection is clearly visible, but in Chrome there isn't such feedback.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/Document/drag_event#examples

#### What did you expect to see?

Either the text is draggable, but not accepted by the dropzone, and/or the text is not selectable

#### Did you test this? If so, how?

firefox:
![reviews](https://user-images.githubusercontent.com/2109932/110338842-c4df9900-8027-11eb-9423-8c2892b35921.gif)

chrome:
![chrome](https://user-images.githubusercontent.com/2109932/110339769-cfe6f900-8028-11eb-9ca2-75663002656d.gif)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/drag_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/drag_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/drag_event/index.html
* Last commit: https://github.com/mdn/content/commit/9917bf17a97973166bb3cb3812a496e4117a778f
* Document last modified: 2021-01-11T13:30:57.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this :+1:

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Update the example to test for a div element, so the text doesn't drag - include a comment to explain in the code

**Comment by sidverma32** [comment]
@Rumyra If this issue is still open and nobody is working on it , can i take this up?

**Comment by hamishwillee** [comment]
@sidverma32 Assigned to you! Thanks very much.

**Comment by sidverma32** [comment]
> To whoever fixes this issue, it looks like the following is needed:
> 
> * Update the example to test for a div element, so the text doesn't drag - include a comment to explain in the code

Just to clarify my approach here, if the expectation is what @Rumyra mentioned then we need to `clone an identical div inside of the parent and set that to be draggable.`
If doing this is fine @hamishwillee  then will update the code accordingly.
