### ISSUE TITLE
Some missing web app manifest member

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#29418]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Manifest

### What information was incorrect, unhelpful, or incomplete?

Some web app manifest member documentation has not been written

* `dir` see https://w3c.github.io/manifest/#dir-member
* `lang` see https://w3c.github.io/manifest/#lang-member
* `iarc_rating_id` see https://w3c.github.io/manifest-app-info/#iarc_rating_id-member
* `note_taking` see https://wicg.github.io/manifest-incubations/#note_taking-member

Maybe more members' documentation were not written yet, also

### What did you expect to see?

Adding those missing manifest member

### Do you have any supporting links, references, or citations?

The standard that I have checked yet:

* https://w3c.github.io/manifest/
* https://w3c.github.io/manifest-app-info/
* https://wicg.github.io/manifest-incubations/

Maybe there are more standards I've not checked

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/manifest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/manifest/index.md
* Last commit: https://github.com/mdn/content/commit/0c015b80f786ecc4547c3e37a70c7f6aafdfbf74
* Document last modified: 2023-06-28T16:16:20.000Z

</details>

**Comment by skyclouds2001** [comment]
- [ ] dir
- [ ] lang
- [ ] iarc_rating_id
- [ ] note_taking

**Comment by Josh-Cena** [comment]
Please see https://github.com/mdn/content/pull/26306

Perhaps instead of hiding them, we should mention that they are specced but never implemented?
