### ISSUE TITLE
optional_permissions: missing entries 

### ISSUE THREAD

**Issue by erosman** [mdn/content#29417]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions

### What specific section or headline is this issue about?

API permissions

### What information was incorrect, unhelpful, or incomplete?

Missing the following which are included in the Browser compatibility

- browsingData
- pkcs11
- proxy
- sessions

### What did you expect to see?

Missing items added

### Do you have any supporting links, references, or citations?

Refer to the Browser compatibility of the same page

### Do you have anything more you want to share?

Please also note the incorrect alphabetical sorting

> - debugger
> - devtools
> - declarativeNetRequestFeedback
> - downloads

**Comment by rebloor** [comment]
See also, https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77

**Comment by Anurella** [comment]
@sideshowbarker I think I can handle this.
