### ISSUE TITLE
Missing compatibility table Status 102

### ISSUE THREAD

**Issue by Somentus** [mdn/content#29424]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/102

### What specific section or headline is this issue about?

Deprecated header

### What information was incorrect, unhelpful, or incomplete?

"see the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/102#browser_compatibility) at the bottom of this page to guide your decision"
There is no compatibility table or section on this page, the link does nothing.

### What did you expect to see?

A compatibility table for the HTTP 102 status code.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/102`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/102
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/102/index.md
* Last commit: https://github.com/mdn/content/commit/592f6ec42e54981b6573b58ec0343c9aa8cbbda8
* Document last modified: 2023-07-25T00:27:48.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @Somentus 

This is a valid bug, but we're unlikely to fix it. The reasons being that 
1. for many HTTP status codes "supported" means nothing to a web browser. So adding compatibility information would probably be an empty table of "don't know".
2. This is deprecated and should not be used. It is very old though. Simply not worth chasing support information.
3. The header which says "see table below" hard codes that text. Most of the time it is accurate. We're not likely to fix it to allow us to be more accurate in cases like this.

Thanks for taking the time to post those.

FYI @teoli2003
