### ISSUE TITLE
Firefox user agent string reference has wrong information about Gecko and Firefox version

### ISSUE THREAD

**Issue by rdsedmundo** [mdn/content#29427]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox

### What information was incorrect, unhelpful, or incomplete?

> rv:geckoversion indicates the release version of Gecko (such as "17.0"). In recent browsers, geckoversion is the same as firefoxversion.

This is no longer true since the Gecko version is frozen in 109.0. See:

https://bugzilla.mozilla.org/show_bug.cgi?id=1805967
https://github.com/browserslist/browserslist-useragent/issues/80

### What did you expect to see?

`geckoversion` should not be said to be the same as `firefoxversion`.

### Do you have any supporting links, references, or citations?

https://bugzilla.mozilla.org/show_bug.cgi?id=1805967

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/user-agent/firefox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/user-agent/firefox/index.md
* Last commit: https://github.com/mdn/content/commit/5767d8da976ac5f53142a83dd1552490223ba42e
* Document last modified: 2023-07-27T01:20:07.000Z

</details>

**Comment by Rumyra** [comment]
For anyone who picks up this issue the page needs to be edited as detailed above
