### ISSUE TITLE
Incorrect description of relative path behavior

### ISSUE THREAD

**Issue by casey** [mdn/content#29431]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL

### What specific section or headline is this issue about?

Examples of relative URLs

### What information was incorrect, unhelpful, or incomplete?

The relative path:

`Skills/Infrastructure/Understanding_URLs`

Resolved on a page served at:

`https://developer.mozilla.org/en-US/docs/Learn`

Is given as:

`https://developer.mozilla.org/en-US/docs/Learn/Skills/Infrastructure/Understanding_URLs`.

### What did you expect to see?

I believe this is incorrect. Since `https://developer.mozilla.org/en-US/docs/Learn` doesn't end with a slash, the relative URL should be interpreted as relative to `https://developer.mozilla.org/en-US/docs/`, giving `https://developer.mozilla.org/en-US/docs/Skills/Infrastructure/Understanding_URLs`.

### Do you have any supporting links, references, or citations?

See [this w3.org page](https://www.w3.org/TR/WD-html40-970917/htmlweb.html), specifically:

```
5.1.2 Relative URLs
A relative URL (defined in [[RFC1808]](https://www.w3.org/TR/WD-html40-970917/references.html#ref-RFC1808)) doesn't contain any protocol or machine information. Its path generally refers to a resource on the same machine as the current document. Relative URLs may contain relative path components (".." means one level up in the hierarchy defined by the path), and may contain fragment identifiers.

Relative URLs are resolved to full URLs using a base URL. [[RFC1808]](https://www.w3.org/TR/WD-html40-970917/references.html#ref-RFC1808) defines the normative algorithm for this process.

As an example of relative URL resolution, assume we have the base URL "http://www.acme.com/support/intro.html". The relative URL in the following markup for a hypertext link:

  <A href="suppliers.html">Suppliers</A>
would expand to the full URL "http://www.acme.com/support/suppliers.html", while the relative URL in the following markup for an image

  <IMG src="../icons/logo.gif" alt="logo">
would expand to the full URL "http://www.acme.com/icons/logo.gif".
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/common_questions/web_mechanics/what_is_a_url`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/web_mechanics/what_is_a_url/index.md
* Last commit: https://github.com/mdn/content/commit/8d0cbeacdc1872f7e4d966177151585c58fb879e
* Document last modified: 2023-08-02T17:32:22.000Z

</details>

**Comment by Rumyra** [comment]
Thanks for raising the issue @casey however the example is correct - as mentioned underneath on the page

> Because that URL does not start with /, the browser will attempt to find the document in a subdirectory of the one containing the current resource. So in this example, we really want to reach this URL: https://developer.mozilla.org/en-US/docs/Learn/Skills/Infrastructure/Understanding_URLs.

If the example were to start with `/` the eventual url would be `https://developer.mozilla.org/Skills/Infre...`

**Comment by casey** [comment]
Hi @Rumyra, thanks for responding! Let me clarify:

The URL `Skills/Infrastructure/Understanding_URLs` while on the `https://developer.mozilla.org/en-US/docs/Learn` would resolve to `https://developer.mozilla.org/en-US/docs/Skills/Infrastructure/Understanding_URLs`, but the example has it as `https://developer.mozilla.org/en-US/docs/Learn/Skills/Infrastructure/Understanding_URLs`. Because `https://developer.mozilla.org/en-US/docs/Learn` does not end with a slash, the final path component, `Learn` of the base URL is removed before appending the relative URL. But it looks like it isn't removed before appending it.

Ideally, the docs would have two examples, one where the base url has a slash, and one which doesn't. E.g.:

```
base: https://developer.mozilla.org/en-US/docs/Learn
relative: Skills/Infrastructure/Understanding_URLs
result: https://developer.mozilla.org/en-US/docs/Skills/Infrastructure/Understanding_URLs
```

And:

```
base: https://developer.mozilla.org/en-US/docs/Learn/
relative: Skills/Infrastructure/Understanding_URLs
result: https://developer.mozilla.org/en-US/docs/Learn/Skills/Infrastructure/Understanding_URLs
```

Since this is somewhat subtle behavior which is easy to get wrong.

**Comment by casey** [comment]
Hi @Rumyra, any chance you could take a look at this again? I'm pretty sure it's wrong.

> If the example were to start with `/` the eventual url would be `https://developer.mozilla.org/Skills/Infre...`

The issue here is that the base URL does not having a trailing slash, so when appending a relative URL, the last component of the base URL is removed.
