### ISSUE TITLE
ambiguous sentence

### ISSUE THREAD

**Issue by 11AMER** [mdn/content#29438]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web

### What specific section or headline is this issue about?

What is SVG?

### What information was incorrect, unhelpful, or incomplete?

At the simplest end of the spectrum

### What did you expect to see?

Also you've got elements for creating popular simple shapes...

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by wbamberg** [comment]
I think the existing sentence is fine.

**Comment by 11AMER** [comment]
> I think the existing sentence is fine.

What is the point of it? I am not a native English speaker!
