### ISSUE TITLE
Wrong Explain

### ISSUE THREAD

**Issue by 11AMER** [mdn/content#29454]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web

### What specific section or headline is this issue about?

The quick way: img element

### What information was incorrect, unhelpful, or incomplete?

(External stylesheets invoked from the SVG file take no effect.)
The CSS file it is the one who select the SVG elements!

### What did you expect to see?

(External stylesheets or inline styles on that image doesn't effect on the SVG elements).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by queengooborg** [comment]
The existing explanation is accurate; your proposed explanation is not.  The line indicates that inline styles are the _only_ way to style the SVG if it is loaded as an `<img>` element.  Closing.
