### ISSUE TITLE
Image not readable under dark theme

### ISSUE THREAD

**Issue by T3sT3ro** [mdn/content#29468]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

### What information was incorrect, unhelpful, or incomplete?

The image is unreadable in the dark theme.

![image](https://github.com/mdn/content/assets/5300963/83f21cb6-a840-4dd7-9075-f0bf94f89330)

### What did you expect to see?

Readable image in dark mode, maybe SVG with white colors when dark theme is displayed, or at least an image with solid background.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/cors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/index.md
* Last commit: https://github.com/mdn/content/commit/84754c3b02ab532e9a89db6a51356f78628ff05f
* Document last modified: 2023-08-10T15:21:15.000Z

</details>

**Comment by zfox23** [comment]
Hi @T3sT3ro 😄. Great find!
