### ISSUE TITLE
Outdated info regarding fade and fade() options in text-overflow?

### ISSUE THREAD

**Issue by Andre601** [mdn/content#29466]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow#values

### What information was incorrect, unhelpful, or incomplete?

The page mentions `fade` and `fade(<length>|<percent>)` as available options for the `text-overflow` option.

However, setting either of these reports them as invalid `text-overflow` option in the Browser itself (When viewing through dev-tools) and the mentioned effect is not set.

### What did you expect to see?

Up-to-date information of the state of the above mentioned options.

### Do you have anything more you want to share?

I encountered this using Firefox `118.0.1 (64-Bit)`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/text-overflow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/text-overflow/index.md
* Last commit: https://github.com/mdn/content/commit/c77cfcd17e85db6c1b93160c70668f2ff6c2809c
* Document last modified: 2023-07-20T07:38:29.000Z

</details>

**Comment by OnkarRuikar** [comment]
As per the "current" specification v3 [`CSS Overflow Module Level 3`](https://drafts.csswg.org/css-overflow/#text-overflow) the property has only two values `clip | ellipsis`.
However there is level 4 specification is being worked on [`CSS Overflow Module Level 4`](https://drafts.csswg.org/css-overflow-4/#text-overflow) according to it the property can have `clip | ellipsis | <string> | fade | <fade()>` values.

At the moment no browser has implemented  `fade` and `fade()`. I think we need to add these properties to [the browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow#browser_compatibility) showing `No support` status.
