### ISSUE TITLE
Issue with "Window.getComputedStyle()": (There should be comma between arguments)

### ISSUE THREAD

**Issue by manaskhandelwal** [mdn/content#2946]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

#### What information was incorrect, unhelpful, or incomplete?
`var style = window.getComputedStyle(element [, pseudoElt]);`

<br />

#### Specific section or headline?
> Syntax Of getComputedStyle
> **Link:** https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle#syntax

<br />

#### What did you expect to see?
`var style = window.getComputedStyle(element, [pseudoElt]);`

<br />

#### Did you test this? If so, how?
**Using VS Code:**
> https://i.stack.imgur.com/QWe7b.png

**Using Chrome Dev Tools:**
> Gives error: `Uncaught SyntaxError: Unexpected token ','`
> https://i.stack.imgur.com/YIxp5.png
> https://i.stack.imgur.com/mRINF.png

<br />

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/getcomputedstyle`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/getcomputedstyle/index.html
* Last commit: https://github.com/mdn/content/commit/11a98a59fca5f2e448d9e4b70e3c8a538c47b201
* Document last modified: 2021-02-19T19:45:18.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can fix this 👍

**Comment by hamishwillee** [comment]
Just FYI @manaskhandelwal you are misinterpreting the syntax. This is a particular notation (BNF) which is a compact way of showing the various options. So you are interpreting `var style = window.getComputedStyle(element [, pseudoElt]);` as a function taking a variable and an array, while actually it is a compact form of showing the two ways you can use the function
```
var style = window.getComputedStyle(element);
var style = window.getComputedStyle(element , pseudoElt);
```
We are aware this confuses some people and are now working (slowly) to simply show all the options in the syntax box. See 
https://developer.mozilla.org/en-US/docs/MDN/Structures/Syntax_sections

**Comment by CreaTorAlexander** [comment]
@hamishwillee for instance I thought it has to be like

required paramter , <optional parameter>'s. 

I haven't thought that it should be *element, array* I thought the comma is misplaced and I think @manaskhandelwal thought the same.
Actually I still don't understand what the reason is that the comma is there at the beginning of the square brackets

**Comment by hamishwillee** [comment]
> Actually I still don't understand what the reason is that the comma is there at the beginning of the square brackets :D

Because the bracket indicates the beginning of the optional part. So if you have no extra argument, you don't have the comma either. If the comma was before the bracket then you'd be implying that this is a desirable syntaxt 
```
var style = window.getComputedStyle(element, );
```

**Comment by chrisdavidmills** [comment]
@hamishwillee I think a better course of action here would be to update the syntax box on the page to the multi-line version. This is something that a contributor like @CreaTorAlexander could happily do.

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills we have fixed it in https://github.com/mdn/content/pull/2950
