### ISSUE TITLE
`overscroll-behavior: contain` example specifies "or refreshes" when it shouldn't

### ISSUE THREAD

**Issue by zfox23** [mdn/content#29473]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior#values

### What specific section or headline is this issue about?

Values

### What information was incorrect, unhelpful, or incomplete?

The doc says:
> Default scroll overflow behavior is observed inside the element this value is set on (e.g. "bounce" effects **or refreshes**)...

The "or refreshes" part shouldn't be there, because native browser navigation isn't allowed when `overscroll-behavior: contain` is set.

### What did you expect to see?

> Default scroll overflow behavior is observed inside the element this value is set on (e.g. "bounce" effects)...

### Do you have any supporting links, references, or citations?

This issue was borne from a conversation with @dlrobertson of the Firefox Layout/Asynchronous Panning and Zooming (APZ) team, who said:

> - The issue had to do with the `overscroll-behavior` docs
> - specifically the `contain` docs say `... (e.g. "bounce" effects or refreshes)`
> - [The spec for contain](https://drafts.csswg.org/css-overscroll/#valdef-overscroll-behavior-contain) indicates all [non-local-boundary-default-action](https://drafts.csswg.org/css-overscroll/#non-local-boundary-default-action) (including navigation) are not allowed
> - Note the spec example [here](https://drafts.csswg.org/css-overscroll/#example-64e64c20) indicates "A page wants to implement their own pull-to-refresh effect when `contain` is used"
> - So simply "or refreshes" should probably be removed from the MDN docs for `overscroll-behavior: contain`
> - That being said browser implementations are a bit all over the place here... We don't ship pull to refresh to the release channel and there are some implementation bugs out there
> - Botond Ballo, the tech lead of APZ discovered this... He's real helpful and knowledgeable on APZ things

### Do you have anything more you want to share?

This is my first submitted issue to MDN 🎉 yay

**Comment by theres-waldo** [comment]
Thanks for filing!

To provide some additional corroboration that the intent is for `overscroll-behavior: contain` to disable pull-to-refresh, [this blog post](https://developer.chrome.com/blog/overscroll-behavior/#disabling-pull-to-refresh) on the Chrome blog specifically gives that as an example as well.
