### ISSUE TITLE
Include information/section on "Method definitions in object literals"

### ISSUE THREAD

**Issue by DanKaplanSES** [mdn/content#29489]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

### What specific section or headline is this issue about?

[Method definitions in classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions#method_definitions_in_classes)

### What information was incorrect, unhelpful, or incomplete?

_From my perspective_, this is incomplete:

> Public instance methods are defined on the prototype property of the class and are thus shared by all instances of the class. They are writable, non-enumerable, and configurable.

### What did you expect to see?

I'm browsing the documentation because I'm trying to learn the difference between these two:

```js
class ClassWithPublicInstanceMethod {
  publicMethod() {
    return "hello world";
  }
}

const objectLiteralMethod = {
  publicMethod() {
    return "hello world";
  }
}
```

But as far as I can tell, the article only explains this for classes. If it mentions how this works on object literals, none of the following section names imply that. This also seems like the most appropriate article for this information; if it's documented elsewhere, I'm not sure where else to look.

I found some information in another page: [Object initializer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#method_definitions). It doesn't answer my question, but maybe it could be linked to and/or updated to include the answer instead? I don't prefer the latter: I wouldn't expect the information to be there when there's another article title "Method definitions." 

### Do you have any supporting links, references, or citations?

n/a

### Do you have anything more you want to share?

It might make sense to create a whole new section for this information? This section is called "[Method definitions in classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions#method_definitions_in_classes)", but I'm looking for information regarding "Method definitions in object literals."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/functions/method_definitions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/functions/method_definitions/index.md
* Last commit: https://github.com/mdn/content/commit/4f86aad2b0b66c0d2041354ec81400c574ab56ca
* Document last modified: 2023-09-12T03:52:28.000Z

</details>

**Comment by Josh-Cena** [comment]
This section is the only section discussing method definition in classes; everything else is about object literals (or at least, common features between the two). What information are you looking for exactly?

**Comment by DanKaplanSES** [comment]
@Josh-Cena 

> Method definitions in object literals are too straightforward: foo() {} is exactly equivalent to foo: function () {}, except for the two differences already listed. It doesn't make sense to talk about them in isolation.

The article is well written so I understand the two _differences_ between `foo() {}` and `foo: function () {}`, but what are the _similarities_? Specifically, are object literal functions/methods "writable, enumerable, and configurable?" I think, "Yes," but this issue is about documenting it like it's done for class methods.
