### ISSUE TITLE
`FileSystemHandle.remove()` should not be marked as non-standard

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#29528]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle/remove

### What information was incorrect, unhelpful, or incomplete?

`FileSystemHandle.remove()` method should not be marked as deprecated

### What did you expect to see?

remove mark of deprecated in glossary and macros, also may update the Specifications section

### Do you have anything more you want to share?

https://github.com/WICG/file-system-access/pull/283 Already Closed
https://github.com/whatwg/fs/pull/9 Still Open

In fact, https://github.com/WICG/file-system-access/pull/283 was simply moved to https://github.com/whatwg/fs/pull/9 

It is simply a developing proposal

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/filesystemhandle/remove`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle/remove
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/filesystemhandle/remove/index.md
* Last commit: https://github.com/mdn/content/commit/5885c6c72de0970c0eb264d02808658465bf1cee
* Document last modified: 2023-08-02T14:09:01.000Z

</details>

**Comment by Josh-Cena** [comment]
We need to update the BCD status first. The content markers merely reflect the BCD status.
