### ISSUE TITLE
Subgrid Compatibility is out of date

### ISSUE THREAD

**Issue by snowe2010** [mdn/content#29538]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Subgrid

### What specific section or headline is this issue about?

Subgrid browser support at the very top of the article

### What information was incorrect, unhelpful, or incomplete?

It states "Baseline: Not widely supported" and that Edge and Chrome do not support subgrid, while the Browser Compatibility section at the bottom states that it's supported everywhere but Opera and Samsung.

### What did you expect to see?

Statement that it is widely supported, or to at least match the data at the bottom of the article in the Browser Compatibility section. 

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Subgrid#browser_compatibility

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_grid_layout/subgrid`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Subgrid
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_grid_layout/subgrid/index.md
* Last commit: https://github.com/mdn/content/commit/01a2d3d4649b9fde1bab58e9073b1913ead710d4
* Document last modified: 2023-08-01T04:43:35.000Z

</details>

**Comment by Lymah123** [comment]
Hi, can I work on it?

**Comment by hamishwillee** [comment]
@Lymah123 Not this one.

**Comment by hamishwillee** [comment]
Thanks for posting, but this issue is invalid. As per the header (expand it) both current and last version must have support for this to be "wide support":
![image](https://github.com/mdn/content/assets/5368500/cae408fd-4729-46a5-ac11-93027fac8517)

But the current version of chrome is 117, so this only just got added. Shortly after Chrome goes to 118 this should then update too.

**Comment by snowe2010** [comment]
Hm. I thought it had been available in chromium for years now. Guess I just never noticed since I use FF. Sorry for the bother!

**Comment by hamishwillee** [comment]
Not a bother at all!
