### ISSUE TITLE
不知道造轮子项目的用处有多大，很害怕烂大街的项目，一些什么商城博客外卖之类的项目都已经烂没了，造轮子项目也早已被大量使用两三年了，不知道在轮子项目如今还能有多大作用。

### ISSUE THREAD

**Issue by Charlesjourdain** [mdn/content#29545]
不知道造轮子项目的用处有多大，很害怕烂大街的项目，一些什么商城博客外卖之类的项目都已经烂没了，造轮子项目也早已被大量使用两三年了，不知道在轮子项目如今还能有多大作用。

_Originally posted by @KatanabeToru in https://github.com/erdengk/excellent-wheel/issues/9_

**Comment by hamishwillee** [comment]
Closing. This looks like spam
