### ISSUE TITLE
Incomplete info at 'Installing' Section

### ISSUE THREAD

**Issue by CatherineCampbell117** [mdn/content#29542]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

### What specific section or headline is this issue about?

Installing

### What information was incorrect, unhelpful, or incomplete?

I went through all the steps up to the point of installing my first extension. In the Firefox about:debugging page, when I go to 'Load Temporary Add-on' and select any file in my new directory for the extension, I get this error 'manifest .permissions is undefined'. Presumably having completed all the steps correctly, I'm guessing other users will have the same problem.

![image](https://github.com/mdn/content/assets/80588492/fe04ec8b-ef1e-4a46-9d5d-5c121d5a3353)

### What did you expect to see?

I think the manifest file either needs to be updated on this page with the manifest.permissions or a section on dealing with this error needs to be added.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/your_first_webextension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/your_first_webextension/index.md
* Last commit: https://github.com/mdn/content/commit/8d0cbeacdc1872f7e4d966177151585c58fb879e
* Document last modified: 2023-08-02T17:32:22.000Z

</details>

**Comment by rebloor** [comment]
@CatherineCampbell117 i've just tried the example and was able to load it without issue. Could you restart the browser and try again? If you're still having issues, could you confirm the extension code you are using?

**Comment by CatherineCampbell117** [comment]
Hi,

Thanks for getting back to me.

I have tested it by using the exact code from the tutorial and it works.
However, if I change any of the values, for example, name, directory name,
or icons, it gives me the error. Here is the code I have been using:

*Folder on VS Code::*
[image: image.png]

*JavaScript file:*
document.body.style.border = "5px solid red";

*Manifest file:*
{
    "manifest_version": 1,
    "name": "Meye",
    "version": "1.0",

    "description": "Adds a red border to all webpages matching mozilla.org."
,

    "icons": {
      "SVG": "icons/border-48.svg"
    },

    "content_scripts": [
      {
        "matches": ["*://*.mozilla.org/*"],
        "js": ["borderify.js"]
      }
    ]
  }

**Comment by rebloor** [comment]
@CatherineCampbell117 the issue is `"manifest_version": 1,` – 1 is not a valid manifest version. There are two valid manifest versions, 2 and 3. Admittedly, this could be more explicitly documented on [manifest_version](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/manifest_version). Feel free to create a separate issue if you think a documentation update would be helpful, or just submit a PR for a documentation change
