### ISSUE TITLE
`Window.setImmediate()` and `Window.clearImmediate()` should be marked as non_standard and deprecated

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#29540]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate

### What information was incorrect, unhelpful, or incomplete?

`Window.setImmediate()` and `Window.clearImmediate()` should be marked as non_standard and deprecated

1. none of major browser has finished this api (only node accomplished this api)

2. the draft standard https://w3c.github.io/setImmediate/ is no longer working on

3. it seems that chromium and firefox will not accomplish this api

### What did you expect to see?

add non_standard and deprecated macros and header

also may update the browser-compat-data if needed

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate

https://developer.mozilla.org/en-US/docs/Web/API/Window/clearImmediate

https://w3c.github.io/setImmediate/

https://bugs.chromium.org/p/chromium/issues/detail?id=146172

https://bugzilla.mozilla.org/show_bug.cgi?id=686201

![image](https://github.com/mdn/content/assets/95597335/1fa58492-32e9-45ae-8bc4-f4365b943f3b)

![image](https://github.com/mdn/content/assets/95597335/ba02d16c-0297-41e9-845b-3ff852d6e002)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/setimmediate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/setimmediate/index.md
* Last commit: https://github.com/mdn/content/commit/bd4e8bce64f6e5d3d07ddf8c1cbb5aaffe060d0c
* Document last modified: 2023-09-01T03:14:41.000Z

</details>

**Comment by Josh-Cena** [comment]
These pages and their BCD entries probably qualify for removal already.

**Comment by hamishwillee** [comment]
> These pages and their BCD entries probably qualify for removal already.

The criteria for removal as I understand it is "in no browser (I presume including node) for more than 2 years".

Anyway, I've created the PR for BCD here https://github.com/mdn/browser-compat-data/pull/20919 - easier to get PRs evaluated than issues. When that goes in (or not) it will be clear what has to happen here for content.
