### ISSUE TITLE
Wrong information on docs:

### ISSUE THREAD

**Issue by ARS-coding** [mdn/content#29557]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Safe/HTTP

### What specific section or headline is this issue about?

A call to an idempotent but non-safe method:

### What information was incorrect, unhelpful, or incomplete?

DELETE HTTP method is not idempotent.

### What did you expect to see?

PUT HTTP method being used as an explample of idempotent method.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/safe/http`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Safe/HTTP
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/safe/http/index.md
* Last commit: https://github.com/mdn/content/commit/ada5fa5ef15eadd44b549ecf906423b4a2092f34
* Document last modified: 2023-06-08T13:19:16.000Z

</details>

**Comment by wbamberg** [comment]
https://www.rfc-editor.org/rfc/rfc9110#name-idempotent-methods indicates that DELETE is idempotent: 

> A request method is considered "idempotent" if the intended effect on the server of multiple identical requests with that method is the same as the effect for a single such request. Of the request methods defined by this specification, [PUT](https://www.rfc-editor.org/rfc/rfc9110#PUT), [DELETE](https://www.rfc-editor.org/rfc/rfc9110#DELETE), and safe request methods are idempotent.

**Comment by Josh-Cena** [comment]
Unless further evidence is provided, closing as a misunderstanding
