### ISSUE TITLE
GPUTexture usage tables reference GPUBufferUsage object

### ISSUE THREAD

**Issue by sahilshahpatel** [mdn/content#29561]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/GPUTexture/usage

### What specific section or headline is this issue about?

Under "value", the usage table

### What information was incorrect, unhelpful, or incomplete?

The table uses `GPUTextureUsage` for the first couple flags, but then uses `GPUBufferUsage` for `GPUBufferUsage.TEXTURE_BINDING` for example. In practice when using Google Chrome for WebGPU, using `GPUBufferUsage.TEXTURE_BINDING` caused issues while using `GPUTextureUsage.TEXTURE_BINDING` worked well. Therefore I believe this is a typo.

### What did you expect to see?

I expected to see all usage flags under `GPUTextureUsage.*`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/gputexture/usage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/GPUTexture/usage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/gputexture/usage/index.md
* Last commit: https://github.com/mdn/content/commit/b6984118ac9482e683a654edfefa4b426ca3c7ca
* Document last modified: 2023-04-07T06:03:34.000Z

</details>

**Comment by caugner** [comment]
I looked at the [WebGPU Specification](https://gpuweb.github.io/gpuweb/#texture-usage) and verified that those should all be `GPUTextureUsage` flags, not `GPUBufferUsage` flags.

@sahilshahpatel Are you interested in opening a PR to resolve the issue?

**Comment by sahilshahpatel** [comment]
@caugner This is my first PR here, but I believe I've done what's necessary. Let me know if I messed up!
