### ISSUE TITLE
Game development tutorials: var instead of let on tutorial page

### ISSUE THREAD

**Issue by 19g9nd** [mdn/content#29577]
### MDN URL

https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Finishing_up

### What specific section or headline is this issue about?

Compare your code

### What information was incorrect, unhelpful, or incomplete?

On the page at the end of the tutorial, it is possible to compare your code with the source code (Compare your code), but there is the use of var instead of let and also == instead of ===. 
![image](https://github.com/mdn/content/assets/113902162/10330173-af84-48f2-901a-6621b61d905b)

### What did you expect to see?

That`s what the user sees on the tutorial page:
![image](https://github.com/mdn/content/assets/113902162/f6a95b3d-1026-43ae-9b07-9270d7aedb40)
VS Compare your code:
![image](https://github.com/mdn/content/assets/113902162/3556438c-85b2-4e10-8bca-ecdf9b6d0885)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/games/tutorials/2d_breakout_game_pure_javascript/finishing_up`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Finishing_up
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/tutorials/2d_breakout_game_pure_javascript/finishing_up/index.md
* Last commit: https://github.com/mdn/content/commit/56db19e6b8d19932c1b6150bc42e752e12a2b21f
* Document last modified: 2023-06-28T16:09:36.000Z

</details>

**Comment by caugner** [comment]
It looks like this issue applies to all tutorials in the Game development section, i.e. the JSFiddles all use `var`, while the instructions on the pages already use `let` and `const`.

**Comment by wbamberg** [comment]
It would be better to convert the jsfiddle embeds into live samples, so they can be managed alongside the rest of the docs.

Or maybe one day we will be brave enough to sunset the Game dev section...

**Comment by caugner** [comment]
@wbamberg Opened https://github.com/mdn/mdn/issues/468 for the jsfiddle-to-live-sample conversion. 😉

**Comment by bsmth** [comment]
@caugner, the original issue is fixed in https://github.com/mdn/content/pull/32258 although there are some JSFiddles left over in other pages.

**Comment by bsmth** [comment]
I'm going to close this one as done now because the linked PR fixes this - we will be checking the other JSFiddles for `var` etc. if we choose to incorporate them in the same way. Thank you :)
