### ISSUE TITLE
Issue with "IIFE": example doesn’t actually show a case where an IIFE is necessary

### ISSUE THREAD

**Issue by ankit9607** [mdn/content#2958]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/IIFE

#### What information was incorrect, unhelpful, or incomplete?

(function () {
    var aName = "Barry";
})();
// Variable aName is not accessible from the outside scope
aName // throws "Uncaught ReferenceError: aName is not defined"

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Glossary/IIFE#examples

#### What did you expect to see?

Achieving the same result with function declaration and function expression, so what make it special in IIFE.

function foo(){
	var aName="Barry";
};
foo(); //I called the function to replicate effect of IIFE that function was called.
// Variable aName is not accessible from the outside scope
aName // throws "Uncaught ReferenceError: aName is not defined"

var foo = function(){
	var aName="Barry";
};

foo();
// Variable aName is not accessible from the outside scope
aName // throws "Uncaught ReferenceError: aName is not defined"

#### Did you test this? If so, how?

Yes tested on raw js file.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/iife`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/IIFE
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/iife/index.html
* Last commit: https://github.com/mdn/content/commit/78db9a278d0b412b147c26df27eb3d843ba832e3
* Document last modified: 2020-12-30T11:27:15.000Z

</details>

**Comment by NegiAkash890** [comment]
In the first example we should `console.log(aName) ` . Correct Me if i am wrong . 


Screenshot :

![Screenshot from 2021-03-09 10-09-52](https://user-images.githubusercontent.com/55234838/110420157-c315e400-80c0-11eb-845f-2e38e4f976e1.png)

**Comment by ankit9607** [comment]
Hi Akash,

Yes, In order to see the result on console, we have to call console.log,
but as you can see in the example its says, If you access the
variable aName its value will be (Reference Error or "Barry") string or
reference error. which is perfectly fine.

**Comment by chrisdavidmills** [comment]
To whoever fixes this: it looks like we need to update the example as indicated above.

**Comment by longm89** [comment]
@ankit9607 You have a wonderful remark! 
@chrisdavidmills Could I work on fixing this?

**Comment by chrisdavidmills** [comment]
@longm89 you certainly can. Thanks for the help!

**Comment by longm89** [comment]
@chrisdavidmills Thanks a lot, I added some use cases of IIFE.
