### ISSUE TITLE
Link to Unicode

### ISSUE THREAD

**Issue by xfq** [mdn/content#29587]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/I18N

### What information was incorrect, unhelpful, or incomplete?

The link to [Unicode](https://www.techtarget.com/whatis/definition/Unicode) seems to require signing in to see it.

### What did you expect to see?

Users don’t need to sign in to see content, and preferably the content should be written by i18n/Unicode experts.

### Do you have any supporting links, references, or citations?

Maybe it can link to https://www.w3.org/TR/i18n-glossary/#dfn-unicode ?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/i18n`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/I18N
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/i18n/index.md
* Last commit: https://github.com/mdn/content/commit/ada5fa5ef15eadd44b549ecf906423b4a2092f34
* Document last modified: 2023-06-08T13:19:16.000Z

</details>

**Comment by caugner** [comment]
> The link to [Unicode](https://www.techtarget.com/whatis/definition/Unicode) seems to require signing in to see it.

For me, the link doesn't require me to sign in. Can you share a screenshot?

**Comment by wbamberg** [comment]
I don't have to sign in either. However it would be better IMO to use https://developer.mozilla.org/en-US/docs/Glossary/Unicode as the link target, as it is essentially a glossary entry.

**Comment by xfq** [comment]
Here's the screenshot:

<img width="1680" alt="Screen Shot 2023-10-16 at 16 23 54" src="https://github.com/mdn/content/assets/2863444/0266a046-69b9-4eda-a2f9-b4dfc2693701">

**Comment by xfq** [comment]
> it would be better IMO to use https://developer.mozilla.org/en-US/docs/Glossary/Unicode as the link target, as it is essentially a glossary entry.

Sounds good to me.

**Comment by caugner** [comment]
I was able to reproduce the login by visiting a different TechTarget article before, but linking to the Glossary makes sense.
