### ISSUE TITLE
Links to i18n resources

### ISSUE THREAD

**Issue by xfq** [mdn/content#29588]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/I18N

### What specific section or headline is this issue about?

See also

### What information was incorrect, unhelpful, or incomplete?

The "[i18n on W3C](https://www.w3.org/International/questions/qa-i18n.en#Internationalization)" link has a broken fragment.

### What did you expect to see?

The correct URI is https://www.w3.org/International/questions/qa-i18n.en#i18n . Alternatively, it could link to the [About](https://www.w3.org/International/i18n-drafts/nav/about#what) page or the [Activity home page](https://www.w3.org/International/).

Also, I would suggest adding a link to [the list of i18n articles](https://www.w3.org/International/articlelist), since most of them are targeting web developers.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/i18n`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/I18N
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/i18n/index.md
* Last commit: https://github.com/mdn/content/commit/ada5fa5ef15eadd44b549ecf906423b4a2092f34
* Document last modified: 2023-06-08T13:19:16.000Z

</details>

**Comment by adeyinkaezra123** [comment]
Hi, can I work on this?

**Comment by wbamberg** [comment]
The link was removed in https://github.com/mdn/content/pull/29713, so I'm closing this one.

**Comment by xfq** [comment]
I think it would be useful to add a link to the W3C i18n site. Here are a few examples that I think are useful:

The [Internationalization Glossary](https://www.w3.org/TR/i18n-glossary/) provides definitions for terms related to i18n that web developers might want to know.

There are many [i18n-related tests](https://www.w3.org/International/i18n-tests/) that web developers can look at to understand how well an i18n-related feature is implemented. Although MDN browser-compat-data also has some similar results, interested developers can often see the test result visually, and it is categorized according to language/script and features, which could provide a new perspective (compared with MDN).

There are many [articles](https://www.w3.org/International/articlelist) for web developers to learn how to properly internationalize a website when using HTML and CSS. This kind of information is often missing on MDN but is important.

**Comment by wbamberg** [comment]
I'll merge a PR to add these links to the page, if you would like to make one.
