### ISSUE TITLE
Browsers supporting issue with sizes attribute.

### ISSUE THREAD

**Issue by Amer-Adel** [mdn/content#29590]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

### What specific section or headline is this issue about?

Resolution switching: Different sizes

### What information was incorrect, unhelpful, or incomplete?

1- The sizes attribute doesn't work on mobile browsers while it should be supported, and they just display the biggest source in the `srcset`
2- Also PC Browsers if the media conditions don't match, they display the biggest source in the `srcset` also instead of the default size in `sizes` attribute

### What did you expect to see?

Solutions or explanations for that.

### Do you have any supporting links, references, or citations?

[Browser Supporting](https://caniuse.com/?search=sizes)
[Example](https://codepen.io/11AMER/pen/yLGwNLx)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>

**Comment by dipikabh** [comment]
Hello @Amer-Adel, thank you for bringing up this issue.

Before we proceed to look into this further, could you provide some more details:

- Could you share the mobile browsers and their versions where you observed the `sizes` attribute not working. Also note that the [Browser compatibility table on the `<img>` page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#browser_compatibility) shows the `sizes` attribute supported on mobile browsers.
- For desktop browsers, could you confirm if you've already tried the hints provided in the [Note: When testing this with a desktop browser...](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_different_sizes) regarding checking the viewport size and using developer tools to see which images were loaded?

Thanks!
