### ISSUE TITLE
The `shadowrootmode` attribute on `<template>` is about to be standardized

### ISSUE THREAD

**Issue by mfreed7** [mdn/content#29600]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

### What specific section or headline is this issue about?

Attributes

### What information was incorrect, unhelpful, or incomplete?

See https://github.com/whatwg/html/pull/5465 which is going to land soon. When it does, the `shadowrootmode` attribute on the `<template>` element will be standardized. 

The MDN page here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template#attributes looks like this:

> In Chromium-based browsers, the `<template>` element also supports a non-standard [`shadowrootmode` attribute](https://github.com/mfreed7/declarative-shadow-dom/blob/master/README.md#syntax), as part of an experimental ["Declarative Shadow DOM"](https://developer.chrome.com/articles/declarative-shadow-dom/) proposal. In supporting browsers, a `<template>` element with the `shadowrootmode` attribute is detected by the HTML parser and immediately applied as the shadow root of its parent element. `shadowrootmode` can take a value of open or closed; these are equivalent to the open and closed values of the [`Element.attachShadow()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow) mode option.

That should be updated to remove the "Chromium-based browsers" language, etc., and refer to the spec.

### What did you expect to see?

See above.

### Do you have any supporting links, references, or citations?

See above.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/template`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/template/index.md
* Last commit: https://github.com/mdn/content/commit/cefb02847d4edd8ac462275a1c5eb23bdfcfef69
* Document last modified: 2023-08-17T03:58:28.000Z

</details>

**Comment by Rumyra** [comment]
Thanks for raising the issue @mfreed7 - do you have any browser implementation bugs?

**Comment by mfreed7** [comment]
> Thanks for raising the issue @mfreed7 - do you have any browser implementation bugs?

Sure!
- https://crbug.com/1379513
- https://bugzilla.mozilla.org/show_bug.cgi?id=1712140
- https://bugs.webkit.org/show_bug.cgi?id=249513

**Comment by pepelsbey** [comment]
FYI, [there’s a task](https://github.com/mdn/content/issues/31102) documenting `shadowrootmode` attribute for the upcoming Firefox 122 release (behind the flag for now, but will be enabled by default in 123).

**Comment by pepelsbey** [comment]
The shadowrootmode attribute has been properly documented in #31490

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template#attributes
