### ISSUE TITLE
media format: (Chromium-based) Edge don't need to install 'Web Media Extensions' anymore

### ISSUE THREAD

**Issue by jasonren0403** [mdn/content#29615]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers

### What specific section or headline is this issue about?

Index of media container formats (file types)

### What information was incorrect, unhelpful, or incomplete?

Under the table, OGG and WebMedia part,

> Edge requires [Web Media Extensions](https://www.microsoft.com/store/productId/9N5TDP8VCMHS) to be installed.

### What did you expect to see?

(Chromium-based) Edge don't rely on web media extensions anymore, this should be removed or changed to more accurate information.

### Do you have any supporting links, references, or citations?

```js
const testEle = document.createElement("audio");
console.log(testEle.canPlayType("audio/ogg; codecs=vorbis")); // 'probably'
```

### Do you have anything more you want to share?

![image](https://github.com/mdn/translated-content/assets/15844309/b8fe741d-33ad-4c2e-b2e6-f6c540c250cd)

_Originally posted by @yin1999 in https://github.com/mdn/translated-content/pull/16129#discussion_r1340782206_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/media/formats/containers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/media/formats/containers/index.md
* Last commit: https://github.com/mdn/content/commit/d68dc0cf0f0caff5572ce83cb28df898ac815e40
* Document last modified: 2023-08-16T21:34:20.000Z

</details>

**Comment by caugner** [comment]
Edge probably doesn't need the Web Media Extensions anymore since migrating to Chromium.

@queengooborg Have we considered adding support for specific audio/image/video formats to BCD, to replace [this table](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#browser_compatibility)?

**Comment by queengooborg** [comment]
Migrating that table has been something I've wanted to do for a long time, but I haven't been able to figure out a good place to put it.  My thought is perhaps the HTMLMediaElement API?

**Comment by caugner** [comment]
> My thought is perhaps the HTMLMediaElement API?

Would it be an option to have a new `general` top-level and put it inside in `general.media.audio/image/video`?

**Comment by Josh-Cena** [comment]
This particular issue is fixed by https://github.com/mdn/content/pull/32868. The rest can be discussed in https://github.com/mdn/content/issues/33781
