### ISSUE TITLE
Incorrect use of `picture` element

### ISSUE THREAD

**Issue by Amer-Adel** [mdn/content#29613]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page

### What specific section or headline is this issue about?

An art directed red panda

### What information was incorrect, unhelpful, or incomplete?

We want to insert a `picture` element.
We should use the picture element when we will display multiple resolution for each size, and while that can't happen because we don't have a specific display width for the two media condition (screens) because we just let the image take the full width, then we can simply just use `srcset` & `sizes` for the different sizes.

### What did you expect to see?

we want to insert an `img` element containing appropriate `src`, `alt`, `srcset` and `sizes` attributes.
Like the above section.

Or use CSS `background` property for this while it's a decoration image and I can't provide an alt value for it.

### Do you have any supporting links, references, or citations?

https://github.com/mdn/content/issues/29530

[What exactly should you write inside your alt attribute?](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML#alternative_text)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/mozilla_splash_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/mozilla_splash_page/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>

**Comment by caugner** [comment]
@Amer-Adel As far as I can see, you already mention this issue in https://github.com/mdn/content/issues/29530:

> Also in the art Art direction section the context of using picture for this is wrong we can easily using the first way (srcset, sizes), pictures element should use for the advanced case that when we use deferent images (for the first resolution switching Or art direction) and then will use a also the second way (srcset with x-descriptors) to provide different resolutions for each specific image size.

Therefore I'm closing this issue as duplicate. 😉

**Comment by Amer-Adel** [comment]
Just for reference to its different places.
