### ISSUE TITLE
Import expression operator precedence

### ISSUE THREAD

**Issue by lucasdomanico** [mdn/content#29614]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence

### What information was incorrect, unhelpful, or incomplete?

I think this page is missing import expression operator precedence.

### What did you expect to see?

the correct order of import expression.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/operator_precedence/index.md
* Last commit: https://github.com/mdn/content/commit/4c26e8a3fb50d06963b06017f51ce19364350564
* Document last modified: 2023-08-11T08:07:46.000Z

</details>

**Comment by Josh-Cena** [comment]
Yes we can add it. It's exactly equal to a function call.
