### ISSUE TITLE
`calc()` syntax and linked specification are at odds

### ISSUE THREAD

**Issue by andyearnshaw** [mdn/content#29628]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/calc

### What specific section or headline is this issue about?

Syntax (or Specifications)

### What information was incorrect, unhelpful, or incomplete?

The syntax for multiplication and division is wrong, according to the linked specification.

> [`*`](https://developer.mozilla.org/en-US/docs/Web/CSS/calc#sect2)
> Multiplication. At least one of the arguments must be a [`<number>`](https://developer.mozilla.org/en-US/docs/Web/CSS/number).
> 
> [`/`](https://developer.mozilla.org/en-US/docs/Web/CSS/calc#sect3)
> Division. The right-hand side must be a [`<number>`](https://developer.mozilla.org/en-US/docs/Web/CSS/number).

The linked specification says:

> In previous versions of this specification, multiplication and division were limited in what arguments they could take, to avoid producing more complex intermediate results (such as 1px * 1em, which is [`<length>`](https://drafts.csswg.org/css-values/#length-value)²) and to make division-by-zero detectable at parse time. This version now relaxes those restrictions.

### What did you expect to see?

I'm not sure (otherwise I would have edited it). The page should be consistent with the specification it links to so, either the syntax and compatibility table sections need updating, or a link to the older syntax should be added.

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/css-values-4/#calc-type-checking

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/calc`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/calc
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/calc/index.md
* Last commit: https://github.com/mdn/content/commit/2adfb8760ac42c80966080e2e84211b14e43b589
* Document last modified: 2023-07-18T00:15:42.000Z

</details>

**Comment by pepelsbey** [comment]
Hey! Good catch, it seems like the specification has indeed relaxed the requirements for `*` and `/`. It should be easy to solve by removing the last sentence for each item and leaving just the operator's name. I don’t think it’s worth mentioning the previous limiting syntax since browsers support the newer one.

**Comment by mattdecamp** [comment]
I can jump in and handle this edit.
