### ISSUE TITLE
ARIA Authoring Practices have moved

### ISSUE THREAD

**Issue by DerKoun** [mdn/content#29627]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/cell_role

### What specific section or headline is this issue about?

Specifications

### What information was incorrect, unhelpful, or incomplete?

"ARIA Authoring Practices # cell" is a dead link (technically not dead, but the expected content is no longer there)

### What did you expect to see?

The expected document/article, if it is still available somewhere.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/accessibility/aria/roles/cell_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/cell_role
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/roles/cell_role/index.md
* Last commit: https://github.com/mdn/content/commit/fc87076c029203dd27ddfd37fff45748b94e4c54
* Document last modified: 2023-09-06T08:38:55.000Z

</details>

**Comment by caugner** [comment]
Verified that the link points to [this Content Moved](https://w3c.github.io/aria-practices/#cell) page, but note that the `#cell` anchor already didn't exist in the [last version available in the Wayback Machine](https://web.archive.org/web/20230221103723/https://w3c.github.io/aria-practices/#cell).

The ARIA Authoring Practice Guide is now available at https://www.w3.org/WAI/ARIA/apg/. According to the [index](https://www.w3.org/WAI/ARIA/apg/example-index/), the most likely replacement would be the [Table example](https://www.w3.org/WAI/ARIA/apg/patterns/table/examples/table/).

Note that this affects 49 files: https://github.com/search?q=repo%3Amdn%2Fcontent%20%22https%3A%2F%2Fw3c.github.io%2Faria-practices%2F%22&type=code

**Comment by zfox23** [comment]
I will take this on.
