### ISSUE TITLE
What is the "Reduced time precision" example conveying?

### ISSUE THREAD

**Issue by DanKaplanSES** [mdn/content#29634]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime#reduced_time_precision

### What information was incorrect, unhelpful, or incomplete?

This example is confusing me:

```js
// reduced time precision (2ms) in Firefox 60
new Date().getTime();
// 1519211809934
// 1519211810362
// 1519211811670
// …

// reduced time precision with `privacy.resistFingerprinting` enabled
new Date().getTime();
// 1519129853500
// 1519129858900
// 1519129864400
// …
```

Why is one line of code printing 3+ lines of output? Is this what I might see if I ran the first line 3+ times, or is it what I would see if I saved the first line and a variable and printed the variable 3+ times? I'm assuming the former, but I'm not confident in my interpretation.

### What did you expect to see?

Based on some tests, I'm going to assume this was trying to convey what you would see if you ran the same line three times. Here's what I would expect to see:

```js
// reduced time precision (2ms) in Firefox 60
new Date().getTime();
// 1519211809934
new Date().getTime();
// 1519211810362
new Date().getTime();
// 1519211811670
// …

// reduced time precision with `privacy.resistFingerprinting` enabled
new Date().getTime();
// 1519129853500
new Date().getTime();
// 1519129858900
new Date().getTime();
// 1519129864400
// …
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/gettime`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/gettime/index.md
* Last commit: https://github.com/mdn/content/commit/5c3c25fd4f2fbd7a5f01727a65c2f70d73f1880a
* Document last modified: 2023-09-12T04:14:14.000Z

</details>

**Comment by Josh-Cena** [comment]
You are right—multiple `getTime` calls would make more sense. The same example is reused in many places involving reduced time precision, and we need to update all of them.
