### ISSUE TITLE
RTCRtpSender links to RTCRtpReceiver.transform, not RTCRtpSender.transform

### ISSUE THREAD

**Issue by PMohanJ** [mdn/content#29640]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender#instance_properties

### What information was incorrect, unhelpful, or incomplete?

In the [instance properties](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender#instance_properties) section, the last property is explaining about `RTCRtpScriptTransform`, but the heading is mistakenly referring to `RTCRtpReceiver.transform`.

### What did you expect to see?

The heading should be changed to  `RTCRtpScriptTransform`. 

### Do you have anything more you want to share?

Kindly let me know if this is done intentionally or else I'd like a create a PR for this issue.

**Comment by caugner** [comment]
It looks like the heading is correct, since it is about the `[RTCRtpReceiver.transform](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpReceiver/transform)` property, but I agree that the paragraph is somewhat confusing.

For example, it could be changed to:

> An [RTCRtpScriptTransform](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpScriptTransform) **which can be**  used to insert a transform stream (...)

**Comment by PMohanJ** [comment]
Apologies, I didn't read the paragraph completely. Indeed the [RTCRtpReceiver](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpReceiver) has a property named transform which in turn is an object of `RTCRtpScriptTransform`. 
But nonetheless, the page is explaining about `RTCRtpSender` interface then the appropriate property should be `[RTCRtpSender.transform](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/transform)` not the `RTCRtpReceiver.transform`
