### ISSUE TITLE
I try to add latitude and longitud to a INPUT TEXT without succes

### ISSUE THREAD

**Issue by rudva** [mdn/content#29651]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/Using_the_Geolocation_API

### What specific section or headline is this issue about?

Javascriot

### What information was incorrect, unhelpful, or incomplete?

Everything works fine, I try to insert the latitude and longitude in a INPUT TEXT but is not working. 

Any idea of the script how should be? I try this
`document.getElementById("TXTloclat").value = latitude;
document.getElementById("TXTloclon").value = longitude;`

where TXTloclat and TXTloclon are the name and Id for the INPUT TEXTs

### What did you expect to see?

the value of latitude and longitude to pass as POST variable

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/geolocation_api/using_the_geolocation_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/Using_the_Geolocation_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/geolocation_api/using_the_geolocation_api/index.md
* Last commit: https://github.com/mdn/content/commit/0444ab41bb372e63b3345f50e5b1e4e6a96c21d5
* Document last modified: 2023-02-24T12:04:34.000Z

</details>

**Comment by caugner** [comment]
@rudva Could you insert your example into [the Playground](https://developer.allizom.org/en-US/play) and use the "Share" button to share it with us?

**Comment by Josh-Cena** [comment]
This looks like a question rather than a problem with our content.
