### ISSUE TITLE
backdrop-filter article states that a transparent background is required, but that doesn't seem to be the case

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [mdn/content#29667]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

### What specific section or headline is this issue about?

backdrop-filter

### What information was incorrect, unhelpful, or incomplete?

The article states:

> Because it applies to everything behind the element, to see the effect you must make the element or its background at least partially transparent.

However, when I inspect the demos on that page in Chrome 117 and remove the semi-transparent background color, it still works:

![Inspecting a demo of backdrop-filter on MDN. Some text is overlaid on a photo of a hot air balloon. The browser dev tools are open and the background-color property has been removed from the overlay, which still maintains its blur effect.](https://github.com/mdn/content/assets/19352442/b96f1e30-b8ba-4749-95e4-6cd219f54707)

Repro here: https://jsfiddle.net/wa91g3hx/25/

### What did you expect to see?

If this is true, the article should clarify why/what happens if a background color is omitted.

### Do you have any supporting links, references, or citations?

https://jsfiddle.net/wa91g3hx/25/

**Comment by OnkarRuikar** [comment]
> However, when I ... remove the semi-transparent background color, it still works:

When you don't set `background-color` property on an element [it gets `transparent` background](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color#formal_definition). `transparent` is the default background color for all the elements. The statement correctly says if you can't have fully transparent background then at least have semi transparent background to see the `backdrop-filter` effects.

Try setting background-color to red: `background-color: red`. Then changing backdrop-filter values will have no effect.
