### ISSUE TITLE
Proxy example in the `No private property forwarding` section looks incorrect

### ISSUE THREAD

**Issue by yiskang** [mdn/content#29673]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

### What specific section or headline is this issue about?

Example for the function one in the private property section is incorrect

### What information was incorrect, unhelpful, or incomplete?

This example in [No private property forwarding](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#no_private_property_forwarding) causes misleading.

```js
class Secret {
  #x = 1;
  x() {
    return this.#x;
  }
}

const aSecret = new Secret();
const proxy = new Proxy(aSecret, {
  get(target, prop, receiver) {
    const value = target[prop];
    if (value instanceof Function) {
      return function (...args) {
        return value.apply(this === receiver ? target : this, args); //!<<< here is incorrect;
      };
    }
    return value;
  },
});
console.log(proxy.x());
```

### What did you expect to see?

It should be `...args`, not `args`. Otherwise, the function cannot receive the correct function inputs.

```js
alue.apply(this === receiver ? target : this, ...args);
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/proxy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/proxy/index.md
* Last commit: https://github.com/mdn/content/commit/fb85334ffa4a2c88d209b1074909bee0e0abd57a
* Document last modified: 2023-09-25T07:33:31.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! `apply` accepts an array of args, `call` accepts them as an arguments list. Please see their docs.
