### ISSUE TITLE
Content bug: CSS Style is misleading

### ISSUE THREAD

**Issue by craigmccauley** [mdn/content#2967]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions#using_transitions_to_make_javascript_functionality_smooth

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions#using_transitions_to_make_javascript_functionality_smooth

## What is the problem?

The css in the page and in the fiddle uses 
```css
  border-radius: 50px;
  width: 50px;
  height: 50px;
```

## What did you expect to see?

I would expect the border-radius value to be half the value of a side of a square div.

Either
```css
  border-radius: 25px;
  width: 50px;
  height: 50px;
```
or
```css
  border-radius: 50px;
  width: 100px;
  height: 100px;
```

## Did you test this? If so, how?

Yes, new jsfiddle.
https://jsfiddle.net/8van0beh/

**Comment by rachelandrew** [comment]
Yep, this is valid. I also wonder why this is a jsfiddle rather than one of our own examples. @chrisdavidmills shall I move it?

**Comment by chrisdavidmills** [comment]
> Yep, this is valid. I also wonder why this is a jsfiddle rather than one of our own examples. @chrisdavidmills shall I move it?

Yes, it'd be better to include this a live sample/embedded GH sample
