### ISSUE TITLE
Link on MDN that should lead to code for the exercise "conditionals 3" is wrong

### ISSUE THREAD

**Issue by orussmann** [mdn/content#29687]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Conditionals

### What specific section or headline is this issue about?

Conditionals 3

### What information was incorrect, unhelpful, or incomplete?

This is the link, that's supposed to lead to the code for the exercise "Conditionals 3". It's wrong.

https://github.com/mdn/learning-area/blob/main/javascript/building-blocks/tasks/conditionals/conditionals4-download.html

### What did you expect to see?

This should be the correct link: 

https://github.com/mdn/learning-area/blob/main/javascript/building-blocks/tasks/conditionals/conditionals3-download.html

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/test_your_skills_colon__conditionals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Conditionals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/test_your_skills_colon__conditionals/index.md
* Last commit: https://github.com/mdn/content/commit/f75b51f54a0f712f29a81b628b8bf2962d972277
* Document last modified: 2023-08-17T22:56:26.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting! This is fixed in https://github.com/mdn/content/pull/28625
