### ISSUE TITLE
TextDecoderStream constructor ignoreBOM option missing

### ISSUE THREAD

**Issue by Reububble** [mdn/content#29681]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/TextDecoderStream/TextDecoderStream

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

I'm pretty sure the options parameter allows for an optional key "ignoreBOM" with boolean value.

### What did you expect to see?

The options parameter should provide detail about the ignorBOM key

### Do you have any supporting links, references, or citations?

https://encoding.spec.whatwg.org/#ref-for-dom-textdecoderstream%E2%91%A0 constructor step 5

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/textdecoderstream/textdecoderstream`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TextDecoderStream/TextDecoderStream
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/textdecoderstream/textdecoderstream/index.md
* Last commit: https://github.com/mdn/content/commit/2c6e4dc4393fb1e60d4ff293f011b62b23659cab
* Document last modified: 2023-05-03T05:11:42.000Z

</details>

**Comment by SoundaryaKoutharapu** [comment]
Hi @Josh-Cena 
 I would like to get started with this issue.
 
 can you confirm, is this fine to proceed with a PR.
 
 **ignoreBOM** 

- Default: `false`

The `ignoreBOM` parameter is an optional configuration setting for the `TextDecoderStream` constructor. It specifies whether to ignore or consider the Byte Order Mark (BOM) when decoding text streams. The BOM is a special character sequence at the beginning of some text files, which indicates the byte order and encoding of the text.

By default, the `ignoreBOM` parameter is set to `false`, which means that the decoder will consider and respect the BOM in the input stream. When `ignoreBOM` is `false`, the decoder will determine the character encoding based on the presence of the BOM in the input data.

If you set `ignoreBOM` to `true`, the decoder will disregard the BOM in the input data. This is useful in cases where you want to handle text streams without considering the BOM.

**Example:**

```javascript
const decoder = new TextDecoderStream("utf-8", { ignoreBOM: true });

**Comment by Josh-Cena** [comment]
The content is good, but the structure does not meet conventions. I would suggest you look around and see how existing options are documented.

**Comment by Josh-Cena** [comment]
Fixed in https://github.com/mdn/content/pull/30864
