### ISSUE TITLE
DataTransfer is not only used for Drag & Drop

### ISSUE THREAD

**Issue by lionel-rowe** [mdn/content#29696]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer

### What specific section or headline is this issue about?

Multiple sections/articles

### What information was incorrect, unhelpful, or incomplete?

Top sidebar heading of https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer is "HTML Drag and Drop API"; main description states "is used to hold the data that is being dragged during a drag and drop operation"; similar wording throughout the article.

Similar wording is pervasive throughout all the pages relating to `DataTransfer`. For example, https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setData and https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/getData refer to the data that's set/retrieved as "drag data".

### What did you expect to see?

Removal of wording that implies `DataTransfer` is exclusively used for drag-and-drop, and add mention of other use cases where relevant.

### Do you have any supporting links, references, or citations?

* https://w3c.github.io/clipboard-apis/#clipboardevent-clipboarddata
* https://stackoverflow.com/questions/47172409/how-to-set-file-objects-and-length-property-at-filelist-object-where-the-files-a

### Do you have anything more you want to share?

Examples of non-drag-and-drop use cases:

* `ClipboardEvent#clipboardData` is a `DataTransfer` object (used in clipboard events like `copy`):
    ```js
    document.addEventListener('copy', (e) => {
        assert(e.clipboardData instanceof DataTransfer)
        e.clipboardData.setData('text/html', '<h1>hello world</h1>')
    })
    ```
* Manually creating a `DataTransfer` object to programmatically generate a `FileList` to add files to an `<input type="file">`:
    ```js
    const dt = new DataTransfer()
    dt.items.add(new File(['hello world'], 'hello.txt'))
    
    assert(dt.files instanceof FileList)
    document.querySelector('input[type=file]').files = dt.files
    ```

Possibly other use cases I'm not aware of.

**Comment by caugner** [comment]
I can confirm the issue, but note that the HTML Standard [has a similar wording](https://html.spec.whatwg.org/multipage/dnd.html#the-datatransfer-interface):

> [DataTransfer](https://html.spec.whatwg.org/multipage/dnd.html#datatransfer) objects are used to expose the [drag data store](https://html.spec.whatwg.org/multipage/dnd.html#drag-data-store) that underlies a drag-and-drop operation.

However, it would be good if MDN's [DataTransfer](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer) page would reference the usage by the Clipboard API, and possibly the use case for programmatically generating a `FileList`.

**Comment by skyclouds2001** [comment]
I think that since `DataTransfer` interface is defined in [Drag and Drop API](https://html.spec.whatwg.org/multipage/dnd.html), it is no problem if mainly discuss about its relationship with Drag and Drop API.
But it is not a bad idea to mention some other usages about `DataTransfer`

**Comment by skyclouds2001** [comment]
and beside `ClipboardEvent.clipboardData` and manually creating a DataTransfer object, another possible usage is about `InputEvent.dataTransfer`

**Comment by lionel-rowe** [comment]
> I think that since `DataTransfer` interface is defined in [Drag and Drop API](https://html.spec.whatwg.org/multipage/dnd.html), it is no problem if mainly discuss about its relationship with Drag and Drop API.

Yeah, I guess it was originally designed for that and later reused for other use cases (e.g. it still has a `dropEffect` property even if it's not used for drag-and-drop). But I don't think things like "is used to hold the data that is being dragged during a drag and drop operation" adequately define `DataTransfer` any more, even if they did when it was first added to the spec.
