### ISSUE TITLE
:first-of-type – a question

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#29701]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:first-of-type

### What information was incorrect, unhelpful, or incomplete?

Hello,

In the example “Nested elements” I have no problem with the result except for this line.
  ``<div>This <span>nested `span` gets styled</span>!</div>``
The structure is:   `<div><span>…</span></div>`
Why is this line styled?

Above it there is this line:
  ``<div>This <span>nested `span` is first</span>!</div>``
And the structure is the same:   `<div><span>…</span></div>`

Thank you for your answer.

### What did you expect to see?

An answer to my question

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_first-of-type`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:first-of-type
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_first-of-type/index.md
* Last commit: https://github.com/mdn/content/commit/5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e
* Document last modified: 2023-02-21T06:49:52.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, `article :first-of-type` means "any element that's the first child with its type of its parent". Note that the `article` selector merely scopes `:first-of-type` to **any** descendant of `article`.

In this tree (with IDs added for easy referencing):

```html
<article>
  <div id="d1">This `div` is first!</div>
  <div id="d2">This <span id="s1">nested `span` is first</span>!</div>
  <div id="d3">
    This <em id="e1">nested `em` is first</em>, but this <em id="e2">nested `em` is last</em>!
  </div>
  <div id="d4">This <span id="s2">nested `span` gets styled</span>!</div>
  <p id="p1">This `p` qualifies!</p>
  <div id="d5">This is the final `div`.</div>
</article>
```

1. `d1` is the first `div` child of its parent, the `article`, so it's selected.
2. `d2` is not the first `div` child of its parent, the `article`.
3. `s1` is the first `span` child of its parent, `d2`.
4. `e1` is the first `em` child of its parent, `d3`.
5. `e2` is not the first `em` child of its parent, `d3`.

Does that make sense?
