### ISSUE TITLE
process of submitting edits to MDN is expensive

### ISSUE THREAD

**Issue by gdennie** [mdn/content#29711]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX

### What information was incorrect, unhelpful, or incomplete?

It would be useful to be able to edit pages without the ceremony of a fork.

### What did you expect to see?

the presence of an edit button that expedites the submission of a change request

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mouseevent/offsetx`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mouseevent/offsetx/index.md
* Last commit: https://github.com/mdn/content/commit/ef75c1741b450c2331204be5563ee964ad5f4c48
* Document last modified: 2023-04-07T06:16:45.000Z

</details>

**Comment by wbamberg** [comment]
You can edit pages directly on GitHub: from, say, https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX, click "View the source of GitHub", then follow the process here: https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files.
