### ISSUE TITLE
HTMLSelectElement.checkValidity() return type should be "boolean", not "none"

### ISSUE THREAD

**Issue by SlimerDude** [mdn/content#29726]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/checkValidity

### What specific section or headline is this issue about?

Return value

### What information was incorrect, unhelpful, or incomplete?

The return value is listed as `none` but the description says it may return a boolean.

Also, other `checkValidity()` methods report a boolean return type.

### What did you expect to see?

Something like:

Returns `true` if the value of the element has no validity problems; otherwise returns `false`.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/checkValidity
https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/checkValidity
https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/checkValidity

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlselectelement/checkvalidity`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/checkValidity
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlselectelement/checkvalidity/index.md
* Last commit: https://github.com/mdn/content/commit/595cba0e07c70eda7f08a12890e00ea0281933d3
* Document last modified: 2023-04-07T00:32:52.000Z

</details>

**Comment by Josh-Cena** [comment]
For context, this page didn't use to have a return value section, and then we said all methods without return value should explicitly say they return "none", which creates some wrong fixes for pages simply lacking them.

**Comment by viditagrawal56** [comment]
Hey @Josh-Cena  I would like to work on the this issue please assign me

**Comment by Josh-Cena** [comment]
We don't assign people. Just send a PR.
