### ISSUE TITLE
Possibly incorrect information on boolean attributes

### ISSUE THREAD

**Issue by siddheshranade** [mdn/content#29729]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML

### What information was incorrect, unhelpful, or incomplete?

The page says:
> It is worth noticing that a boolean attribute is true when it is present, and false when it is absent.

And then gives the following code example:
`
<input type="checkbox" checked />
<input type="checkbox" checked="" />
<input type="checkbox" checked="true" />
<input type="checkbox" checked="false" />
<input type="checkbox" checked="any value" />`

This is all true, but conditionally. If the boolean attribute is set to false, it becomes false as if it didn't exist. This is true at least for JSX code in React. 

For example:
`return (
    <option value="test" disabled={false}> 
      // {...}
    </option>
)`

This will *not* disable the <option> tag even though the `disabled` attribute is present, because it is specifically set to false.

I don't know enough context to be confident about this, hence am submitting an issue instead of editing the docs directly.

### What did you expect to see?

See above.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/boolean/html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/boolean/html/index.md
* Last commit: https://github.com/mdn/content/commit/ada5fa5ef15eadd44b549ecf906423b4a2092f34
* Document last modified: 2023-06-08T13:19:16.000Z

</details>

**Comment by Josh-Cena** [comment]
JSX is not HTML. In JSX, `foo` is just a shorthand for `foo={true}`, but in HTML `foo="anything"` results in `foo={true}`. There's no way to explicitly declare it as `false`. We don't document JSX because it's not a web standard; you should find JSX reference materials elsewhere.
