### ISSUE TITLE
"invert" or "auto" ?

### ISSUE THREAD

**Issue by ToBeJazz** [mdn/content#29723]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/outline-color

### What information was incorrect, unhelpful, or incomplete?

Differs from https://drafts.csswg.org/css-ui/#outline-color that says that "auto" is the only keyword value and the initial/default value.

### What did you expect to see?

"auto" as the keyword value and the initial value.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/outline-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/outline-color
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/outline-color/index.md
* Last commit: https://github.com/mdn/content/commit/fab1f9cef824066b3ce6a5b25f6c6db539f5d042
* Document last modified: 2023-07-18T00:07:20.000Z

</details>

**Comment by caugner** [comment]
**Summary**: The [Values](https://developer.mozilla.org/en-US/docs/Web/CSS/outline-color#values) section on MDN lists the `invert` keyword (and not `auto`), whereas the [CSS UI draft](https://drafts.csswg.org/css-ui/#outline-color) lists `auto` (but not `invert`).
