### ISSUE TITLE
Mention to the next article in the prerequisites!

### ISSUE THREAD

**Issue by Amer-Adel** [mdn/content#29724]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_is_structured

### What specific section or headline is this issue about?

Prerequisites:

### What information was incorrect, unhelpful, or incomplete?

and an idea of [How CSS works](https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_works).
It's confusing to mention to the next step as a prerequisite!

### What did you expect to see?

Delete it, replace it by one of the above section which teach us how to use CSS if that the is the point!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/first_steps/how_css_is_structured`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_is_structured
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/first_steps/how_css_is_structured/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by collinsnji** [comment]
Perhaps swapping the order of the pages would make more sense since the "[How CSS works](https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_works)" page provides a context that is needed to understand some of the concepts in the "[How CSS is structured](https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_is_structured) article?

**Comment by caugner** [comment]
The following screenshot visualizes the problem that the "Prerequisites" mentions "How CSS works", which is chronologically the "Next" page (linked above).


![Image](https://github.com/mdn/content/assets/495429/df04e210-57f9-4b90-bede-2e1c6f511716)
