### ISSUE TITLE
It's hard to find "HTML Entities" via Search

### ISSUE THREAD

**Issue by CodaCodr** [mdn/content#29730]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Reference

### What specific section or headline is this issue about?

HTML reference/ Search in general

### What information was incorrect, unhelpful, or incomplete?

The HTML section, I suppose. I can't for the life of me find "HTML Entities", "HTML character entities" "&lt;" ...

### What did you expect to see?

A list of them. I found them in the end by going offsite to DDG and searching, which took me to the Glossary and lo and behold, they are.

https://developer.mozilla.org/en-US/docs/Glossary/Entity

How come search can't find them with perfectly reasonable search phrases?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/reference/index.md
* Last commit: https://github.com/mdn/content/commit/ba96f2f183353872db6d9242c7d2dffe2dbc0c35
* Document last modified: 2023-02-24T05:52:35.000Z

</details>

**Comment by CodaCodr** [comment]
Turns out they're incomplete, anyway. I ended up here...

https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references

**Comment by Josh-Cena** [comment]
There was https://github.com/mdn/content/issues/20189, but it was resolved with an IMO nonexhaustive fix...

**Comment by CodaCodr** [comment]
> but it was resolved with an IMO nonexhaustive fix...

Indeed. Doesn't come close to satisfying the Issue topic/title.

**Comment by zfox23** [comment]
Fascinating! Search is hard.

@caugner - do you have any suggestions to make it easier for folks to find "HTML Character Entity/Entities" via Search?

**Comment by CodaCodr** [comment]
> Fascinating! Search is hard.

"Hard" I'd file under "possible but difficult". In this case, it's actually _impossible_.

**Comment by caugner** [comment]
@zfox23 Good question!

It looks like searching for ["html entity"](https://developer.allizom.org/en-US/search?q=HTML+entity) (singular) actually finds the page, while ["html entities"](https://developer.allizom.org/en-US/search?q=HTML+entities) doesn't.

There's really two solutions:

1. Trivial: Make sure that "HTML entities" (plural) is mentioned in the title or content of the page. 
2. Non-trivial: Consider [stemming](https://www.elastic.co/guide/en/elasticsearch/reference/current/stemming.html) in our [ElasticSearch setup](https://github.com/mdn/yari/blob/16c3faa2feccd270d9e0023cd86102b6f732146d/deployer/src/deployer/search/models.py#L200-L226).

Does that help?

PS: I would assume there is a reason why we don't have stemming enabled in our full-text search. Maybe it doesn't work well with all the technical keywords and feature names.

**Comment by zfox23** [comment]
Yes, that makes sense, thank you @caugner! I've [opened a PR](https://github.com/mdn/content/pull/29855) to alleviate this issue, although I recognize that there may be further improvements we'll want to make to Search.

**Comment by zfox23** [comment]
Since https://github.com/mdn/content/pull/29855 is merged, I'm going to close this issue. If someone in this thread believes there's more work to be done, please feel free to reply. Thanks for the discussion!
