### ISSUE TITLE
Using promises: Reenforce samples with correct or incorrect ways for the same code?

### ISSUE THREAD

**Issue by attilalearning** [mdn/content#29742]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises

### What specific section or headline is this issue about?

You might see this expressed with arrow functions instead:

### What information was incorrect, unhelpful, or incomplete?

The 2nd JS code after the arrow functions "headline" could better be understood IF there was the correct way of writing the same shown JS code. So, beside:

```
doSomething()
  .then((url) => {
    // I forgot to return this
    fetch(url);
  })
  .then((result) => {
    // result is undefined, because nothing is returned from
    // the previous handler.
    // There's no way to know the return value of the fetch()
    // call anymore, or whether it succeeded at all.
  });

```
It would be very beneficial IF the correct way was also shown, for instant comprehension.

### What did you expect to see?

See the above "What information was incorrect, unhelpful, or incomplete?"

### Do you have anything more you want to share?

I had a bit of a trouble, referencing to the above JS code (the one returning nothing after fetch(url); So, hopefully, I have done the right pointer for it?

Moreover, when I was reading this article on MDN, and when the idea of a positive (or correct) example would have helped to be displayed, I wanted to instantly stop and suggest this. Only, to find out, that I need to log in to Github. This has lowered my will of improving this article by any suggestion. Luckily, I had a Github account and I took the effort to log in. Imagine if a newcomer is reading up on this... who may not have a Github account? Or, if it was a different website I had to log in to, in order to make this suggestion? Would I have created an account there? Probably not, and, I would have just left my suggestion to fade away.

The easier it will be to contribute, the MORE PEOPLE WILL contribute.

PS: after me completing the required fields on the Github page, I could not press on the "submit new issue" button... what a... disappointment? And loss of time? I somewhat figured out that I have not added a Title!!! I believe, VERY FEW people will have the patience to go this far! Hence, no suggestions for you guys?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/using_promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/using_promises/index.md
* Last commit: https://github.com/mdn/content/commit/f1d6263254646ef9c03cfd4b684716a13fe56686
* Document last modified: 2023-10-07T20:19:37.000Z

</details>

**Comment by Josh-Cena** [comment]
I symphasize the inconvenience, but it is not a net downside. The bar of entry has successfully created a more constructive and professional issue environment. Had we allowed everyone to submit issues, we will be faced with many times more duplicates and spam. In fact, even with the current barrier of entry, MDN's issue and PR backlog is already clogged with many low-effort posts (of course, yours isn't one of them).

**Comment by caugner** [comment]
As for the reported issue, I agree that there could be a good example following immediately after the first bad example:

![Image](https://github.com/mdn/content/assets/495429/e1a7dc79-86bd-477b-b9dc-ccd159e95a46)

But it also looks like those "bad examples" could be made more concise and/or moved into the [Common mistakes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#common_mistakes) section.

**Comment by Rumyra** [comment]
For whoever picks up this issue - please refer to @caugner 's comment above on how to improve the article

**Comment by Josh-Cena** [comment]
Hi, I'm going to incorporate the changes into https://github.com/mdn/content/pull/29746, so no need for another PR :) It's been a while but I'll get there
