### ISSUE TITLE
Using promises: Bad example VS good example

### ISSUE THREAD

**Issue by attilalearning** [mdn/content#29743]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises

### What specific section or headline is this issue about?

"This may be worse if you have race conditions"

### What information was incorrect, unhelpful, or incomplete?

When I looked at the JS code:

```
const listOfIngredients = [];

doSomething()
  .then((url) => {
    // I forgot to return this
    fetch(url)
      .then((res) => res.json())
      .then((data) => {
        listOfIngredients.push(data);
      });
  })
  .then(() => {
    console.log(listOfIngredients);
    // Always [], because the fetch request hasn't completed yet.
  });
```
I could not really understand where the error was? Where should have been a return? Again, a simple good example would have been useful, one that particularly explains or points out where the return should have been in this bad example?

Further, I noticed, the "good" example was beneath the bad one, however, I could not see the difference! I had to copy paste the code in two notepads one by the other to NOTICE (after a minute or so) the actual difference was very subtle when reading... there was a { ... } bracket in the bad one, that was missing in the good one, etc.

### What did you expect to see?

Please see the above section "What information was incorrect, unhelpful, or incomplete?"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/using_promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/using_promises/index.md
* Last commit: https://github.com/mdn/content/commit/f1d6263254646ef9c03cfd4b684716a13fe56686
* Document last modified: 2023-10-07T20:19:37.000Z

</details>

**Comment by collinsnji** [comment]
Adding an indication of where the return statement should have been in the bad example would clarify this a bit more. I can work on this.

**Comment by caugner** [comment]
Related: https://github.com/mdn/content/issues/29742

**Comment by zfox23** [comment]
> Adding an indication of where the return statement should have been in the bad example would clarify this a bit more. I can work on this.

I appreciate your willingness to work on this issue, @collinsnji! I will assign this issue to you. If you would no longer like to work on this issue, or we don't hear from you in a few days, I'll open the issue back up to the community.
