### ISSUE TITLE
max-block-size is missing fit-content description

### ISSUE THREAD

**Issue by graymatter00** [mdn/content#29741]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/max-block-size

### What specific section or headline is this issue about?

Syntax and Values

### What information was incorrect, unhelpful, or incomplete?

The Syntax and Values sections do not have a description for the `fit-content` property.  They both mention the `fit-content()` function.  Both of these are included in the Browser Compatibility section.

### What did you expect to see?

A Sybtax and Values description for the `fit-content` property.

### Do you have any supporting links, references, or citations?

https://caniuse.com/?search=max-block-size

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/max-block-size`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/max-block-size
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/max-block-size/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by caugner** [comment]
The `fit-content()` function is documented on [a separate page](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content_function), so maybe the `fit-content` text could link there:

https://github.com/mdn/content/blob/dd4d084ae96d26ea5a11fac778109fa547a8aa9c/files/en-us/web/css/max-block-size/index.md#L58-L59
