### ISSUE TITLE
Difficulty reading dark mode image

### ISSUE THREAD

**Issue by Amer-Adel** [mdn/content#29755]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_works

### What specific section or headline is this issue about?

How does CSS actually work?

### What information was incorrect, unhelpful, or incomplete?

The diagram offers a simple view of the process.

### What did you expect to see?

Make its `background-color` value something like `#6e6e6e` instead of `#000` and `#fff`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/first_steps/how_css_works`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_works
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/first_steps/how_css_works/index.md
* Last commit: https://github.com/mdn/content/commit/8d0cbeacdc1872f7e4d966177151585c58fb879e
* Document last modified: 2023-08-02T17:32:22.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting @Amer-Adel - there's a linked PR that will fix this.
