### ISSUE TITLE
meta is an element

### ISSUE THREAD

**Issue by AnthonyRKing** [mdn/content#29769]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag

### What information was incorrect, unhelpful, or incomplete?

i) Page refers to the meta viewport 'tag'. We are constructing a meta viewport 'element' here (using a tag). Page seems to think tag is the object rather than the syntax to define the element.

ii) Under 'Background', P2:
'Some mobile devices and other narrow screens render pages in a virtual window or viewport, which is usually wider than the screen, and then shrink the rendered result down so it can all be seen at once. Users can then pan and zoom...'
- If the whole display is on the screen, you won't then be able to pan. This sentence (mentioning pan) doesn't work with the rest of the paragraph around it, even if you were to switch 'pan' with 'zoom' to make the bit quoted above work.

### What did you expect to see?

Better prose(?!?!?)

### Do you have anything more you want to share?

Referring to elements as tags is endemic. Leaders such as MDN should pro-actively discourage this backwards nomenclature.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/viewport_meta_tag`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/viewport_meta_tag/index.md
* Last commit: https://github.com/mdn/content/commit/c51e0599ea09c0e6d035c635db9f48ad1f241490
* Document last modified: 2023-07-05T05:48:35.000Z

</details>

**Comment by estelle** [comment]
When `<meta>` is used, MDN prose uses "`<meta>` element" or "the opening `<meta>` tag". 

There is no "viewport element, and "meta viewport 'element'" isn't correct either, but  "viewport `<meta>` element" can be used.

**Comment by zfox23** [comment]
I believe @estelle's answer takes care of this issue, so I am closing it. @AnthonyRKing - if you think there's more to discuss, please reply to this issue.

**Comment by AnthonyRKing** [comment]
On my 1st point, I interpret that Estelle's response would be in support of changing the title of the page from 'Viewport meta tag' to 'Viewport meta element' along with similar updates in the page.

Her response doesn't address the 2nd point (you can't pan an image that fills the viewport), and remains uncommented on. I suggest that the paragraph in question just needs a little re-work.

**Comment by zfox23** [comment]
Upon second review, I see what you're saying. I'll reopen this and open a PR soon.

**Comment by zfox23** [comment]
In thinking about this more and figuring out something that I believe myself, I opened a new PR:
https://github.com/mdn/content/pull/29915

The PR makes subtle changes that I believe satisfy the spirit of this issue.
