### ISSUE TITLE
Missing `Keyboard` interface `layoutchange` event

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#29762]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Keyboard

### What information was incorrect, unhelpful, or incomplete?

Missing `Keyboard` interface `layoutchange` event

### What did you expect to see?

Missing `Keyboard` interface `layoutchange` event, as it was provided in https://wicg.github.io/keyboard-map with `Keyboard.getLayoutMap()`

### Do you have any supporting links, references, or citations?

See the standard https://wicg.github.io/keyboard-map

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/keyboard`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Keyboard
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/keyboard/index.md
* Last commit: https://github.com/mdn/content/commit/21d3e89589aaf9e5cfa667de679134513ab833f3
* Document last modified: 2023-02-28T12:02:51.000Z

</details>

**Comment by caugner** [comment]
The `layoutchange` is mentioned in the Draft's [Keyboard Events](https://wicg.github.io/keyboard-map/#keyboard-events) section.
