### ISSUE TITLE
CSS selectors page doesn't mention which selectors are case-sensitive

### ISSUE THREAD

**Issue by Amer-Adel** [mdn/content#29775]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors

### What information was incorrect, unhelpful, or incomplete?

Unmention to Case-sensitivity!

### What did you expect to see?

Mention to it: the type selectors are case-insensitiv, while class and id selectors are not.
Unless you want us to learn by trying!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors/type_class_and_id_selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/type_class_and_id_selectors/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>

**Comment by caugner** [comment]
This Learn page doesn't mention case-sensitivity, but the [Attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) reference page does:

> If the attribute value is case sensitive, like [class](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class), [id](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id), and [data-*](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) attributes, the attribute selector value match is case-sensitive.

I think the Learn section intentionally doesn't cover every detail, but I'll defer to others to decide here.

**Comment by Amer-Adel** [comment]
> This Learn page doesn't mention case-sensitivity, but the [Attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) reference page does:
> 
> > If the attribute value is case sensitive, like [class](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class), [id](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id), and [data-*](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) attributes, the attribute selector value match is case-sensitive.
> 
> I think the Learn section intentionally doesn't cover every detail, but I'll defer to others to decide here.

Just because that was open in the next article [Case-sensitivity](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors#case-sensitivity).
