### ISSUE TITLE
[CSS] Implement text-wrap:balance

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#29787]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1731541

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by bsmth** [comment]
See also https://github.com/mdn/content/issues/30338

**Comment by pepelsbey** [comment]
@dletorey are we planning to mention that `text-wrap: balance` is behind the flag in 120? I checked the beta, and it seems like we’re only planning to release it in 121.

![Image](https://github.com/mdn/content/assets/105274/0ecddbe9-8726-427e-89ca-7d24956bbbed)

**Comment by dletorey** [comment]
> @dletorey are we planning to mention that `text-wrap: balance` is behind the flag in 120? I checked the beta, and it seems like we’re only planning to release it in 121.
> 
> ![Image](https://user-images.githubusercontent.com/105274/284531103-0ecddbe9-8726-427e-89ca-7d24956bbbed.png)

Yes, I should have this complete today/tomorrow

**Comment by dletorey** [comment]
Pull Requests:
- [Content](https://github.com/mdn/content/pull/30435)
- [Browser Compat Data](https://github.com/mdn/browser-compat-data/pull/21311)

**Comment by pepelsbey** [comment]
@dletorey it seems like `text-wrap: balance` is missing from 120 release notes though it was shipped behind a flag. Do you think you can create a separate PR to mention it in the release notes?

**Comment by dletorey** [comment]
> @dletorey ~it seems like `text-wrap: balance` is missing from 120 release notes though it was shipped behind a flag. Do you think you can create a separate PR to mention it in the release notes?~
> 
> Nevermind :) Let’s just try to merge your content PR then.
@pepelsbey 
This is in the experimental release page and the release for 121
