### ISSUE TITLE
[HTML] implement source media

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#29788]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- N/A Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- N/A Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1836128

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by dipikabh** [comment]
- Relevant page and section on MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source#media
- Link in the bug: [Re-add <source media> for media elements (https://github.com/whatwg/html/pull/9341)](https://github.com/whatwg/html/pull/9341)
- The above PR opened this issue on `mdn/content`: https://github.com/mdn/content/issues/27079. The following two PRs capture the work done to update docs for `media` in `<source>`:
   - https://github.com/mdn/content/pull/29580
   - https://github.com/mdn/content/pull/29584

To do:

- [ ] Update Fx120 release notes
- [ ] Check if BCD update required (also cross-check https://github.com/mdn/browser-compat-data/pull/21083)
