### ISSUE TITLE
[JS] Implement new Date() format

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#29789]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=449921

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by Josh-Cena** [comment]
Hi @Rumyra, we don't document date string formats, both in content and BCD. It's a pragmatic concern because we can't even be nearly exhaustive about them. In this case I don't think there's anything actionable—you may add a release note entry, but I'm not even sure if that helps anyone.

**Comment by zfox23** [comment]
That's helpful and makes sense! Thank you for the context, @Josh-Cena. I'll add a release note entry for completeness.

**Comment by Rumyra** [comment]
Thank @Josh-Cena ! And thank you for the release note @zfox23 that is still necessary :D
