### ISSUE TITLE
[CSS][Nightly only] Disable `-moz-transform*` and `-moz-transition*` properties

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#29785]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1855763

https://bugzil.la/390936 (CSS `zoom`)

__Related issues and pull requests:__

- Content https://github.com/mdn/content/pull/29815
- content clean-up https://github.com/mdn/content/pull/29911
- BCD (`zoom`) https://github.com/mdn/browser-compat-data/pull/21122
- BCD (`-moz-` prefixes): https://github.com/mdn/browser-compat-data/pull/21195

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by bsmth** [comment]
Related discussion on CSS `zoom`: https://github.com/w3c/csswg-drafts/issues/5623

**Comment by bsmth** [comment]
Note for myself to check `-moz-transform*` props and others under the pref:

```
+if (IsCSSPropertyPrefEnabled("layout.css.prefixes.transforms")) {
+  Object.assign(gCSSProperties, {
+    "-moz-transform": {
+      domProp: "MozTransform",
+      inherited: false,
+      type: CSS_TYPE_SHORTHAND_AND_LONGHAND,
+      alias_for: "transform",
+      subproperties: ["transform"],
+    },
+    "-moz-transform-origin": {
+      domProp: "MozTransformOrigin",
+      inherited: false,
+      type: CSS_TYPE_SHORTHAND_AND_LONGHAND,
+      alias_for: "transform-origin",
+      subproperties: ["transform-origin"],
+    },
+    "-moz-perspective-origin": {
+      domProp: "MozPerspectiveOrigin",
+      inherited: false,
+      type: CSS_TYPE_SHORTHAND_AND_LONGHAND,
+      alias_for: "perspective-origin",
+      subproperties: ["perspective-origin"],
+    },
+    "-moz-perspective": {
+      domProp: "MozPerspective",
+      inherited: false,
+      type: CSS_TYPE_SHORTHAND_AND_LONGHAND,
+      alias_for: "perspective",
+      subproperties: ["perspective"],
+    },
+    "-moz-backface-visibility": {
+      domProp: "MozBackfaceVisibility",
+      inherited: false,
+      type: CSS_TYPE_SHORTHAND_AND_LONGHAND,
+      alias_for: "backface-visibility",
+      subproperties: ["backface-visibility"],
+    },
+    "-moz-transform-style": {
+      domProp: "MozTransformStyle",
+      inherited: false,
+      type: CSS_TYPE_SHORTHAND_AND_LONGHAND,
+      alias_for: "transform-style",
+      subproperties: ["transform-style"],
+    },
+  });
+}
```

**Comment by zcorpan** [comment]
Note that the changes for zoom, -moz-transform and -moz-transition only affect Firefox Nightly currently, not beta or stable.

cc @emilio

**Comment by bsmth** [comment]
Thank you @zcorpan! I've opened a PR linked above that clarifies this ([preview for convenience](https://pr30089.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Firefox/Experimental_features#zoom_property)). 

I've grouped the `-moz-` removals under `zoom` for now and put in separate sections for `transform*` and `transition*` in case only one of these change status again in future.

**Comment by bsmth** [comment]
As of now, one remaining BCD pull request is awaiting review & merge, but there's nothing else outstanding on this one, so I'm closing as done.
