### ISSUE TITLE
Service Worker diagram (and maybe others) aren't visible in dark-mode

### ISSUE THREAD

**Issue by aryanpingle** [mdn/content#29794]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

### What specific section or headline is this issue about?

Custom responses to Requests

### What information was incorrect, unhelpful, or incomplete?

The service worker fetch diagram is really cool, but is sadly kinda broken when viewing the page in dark-mode. Attaching the SVG here, you can see the problem on GitHub's dark-mode:

![sw-fetch](https://github.com/mdn/content/assets/49340972/28aa8d3d-a446-4acd-b027-66bbfd072ed4)

### What did you expect to see?

Icons, text and background with the proper color and contrast appropriate for the page's dark-mode.

### Do you have any supporting links, references, or citations?

[This section contains the SVG in question](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers/sw-fetch.svg)

### Do you have anything more you want to share?

You can inject a style directly into the SVG so that it changes its colors for a dark-mode enabled page. Something simple like:

```html
<svg>
    <style>
        html.dark {
            /* make the colors white or something */
        }
    </style>
    
    <!-- Normal SVG here -->
</svg>
```

**Comment by aryanpingle** [comment]
@Josh-Cena you're right, just tried it out and SVG's loaded via `<img>` can't query the page state.

Another possible solution is to have an optional dark-mode-svg that is loaded only when the user is using/toggles the dark-mode theme. That way it could be incrementally adopted - only SVGs that _really_ need them can have the dark-mode variant, and you won't have to worry about every other svg.

... but I can only imagine how many build system changes that would entail, so probably not an urgent issue. Y'all can close this issue, hopefully mdn/yari#9863 gets merged soon 🤞

**Comment by Josh-Cena** [comment]
We (I, at least) would definitely want to address the dark mode image theming. I would prefer the SVG itself to be inlined, so we can do fun things with it, but a [GitHub-style themed image](https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/) would be cool, too.
