### ISSUE TITLE
Issue with "Grammar and types": can't figure out a way this syntax can be legal

### ISSUE THREAD

**Issue by gondooley** [mdn/content#2980]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types

#### What information was incorrect, unhelpful, or incomplete?
There is a snippet given
```
// Construct an HTTP request prefix used to interpret the replacements and construction
POST`http://foo.org/bar?a=${a}&b=${b}
     Content-Type: application/json
     X-Credentials: ${credentials}
     { "foo": ${foo},
       "bar": ${bar}}`(myOnReadyStateChangeHandler);
```
I cannot construct any POST function which would allow the parenthesized `(myOnReadyStateChangeHandler)` at the end. It seems to be illegal syntax in and of itself.

#### Did you test this? If so, how?
I made several attempts to make a function called POST which would allow a browser or parser to tolerate the parenthesized variable at the end. I experimented with the idea that is was an extra argument to be passed or that the whole thing was a way of defining a dynamic function name. It simply will not parse.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/grammar_and_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/grammar_and_types/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/3629 with a fix.
