### ISSUE TITLE
Broken Link of "Browser-level image lazy loading for the web"

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#29816]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Performance/HTML

### What specific section or headline is this issue about?

Lazy loading images

### What information was incorrect, unhelpful, or incomplete?

When I attempted to look at the "Browser-level image lazy loading for the web" article, I got a page not found/Service Unavailable error message.

The article might have been moved somewhere else.

### What did you expect to see?

To see the article.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/performance/html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/performance/html/index.md
* Last commit: https://github.com/mdn/content/commit/c75b7911b520a770c081003cf0e3baaf7034adaf
* Document last modified: 2023-10-13T13:06:04.000Z

</details>

**Comment by wbamberg** [comment]
I get a redirect to https://web.dev/articles/browser-level-image-lazy-loading from that link.

**Comment by Rohxn16** [comment]
i can fix that.

**Comment by Rohxn16** [comment]
can you tell me where exactly is the link that is broken?

**Comment by jfc3-dol** [comment]
Attached is a screenshot showing where it is located, but I assume you are wondering where in the code base it is located, and I don't know that.

<img width="960" alt="mdn - Browser-level image lazy loading for the web link location" src="https://github.com/mdn/content/assets/10423487/32a91867-98f4-4667-aa09-244990419b02">

**Comment by Rohxn16** [comment]
nope i wanted it on the screen, thanks. Can I get this assigned or should I start working on it?

**Comment by jfc3-dol** [comment]
**NOTE** - The link "Lazy loading video" ( https://web.dev/lazy-loading-video/ ) gets redirected too.

You might want to  check other on this page.

**Comment by Rohxn16** [comment]
sure

**Comment by jfc3-dol** [comment]
This might be a more significant issue with other pages in the MDN documentation that the WEB.DEV links could be redirected.

**Comment by OnkarRuikar** [comment]
> This might be a more significant issue with other pages

Yes, ~411 links need update.

**Comment by jfc3-dol** [comment]
Not sure how things are done with MDN, but I think a new/larger issue should be created that contains all the pages that need links fixed as a list with checkboxes. So they can be marked off as they are fixed.

Good luck.

**Comment by OnkarRuikar** [comment]
> Not sure how things are done with MDN, but I think a new/larger issue should be created that contains all the pages that need links fixed as a list with checkboxes. So they can be marked off as they are fixed.

- No need. All the required changes are being pull in https://github.com/mdn/content/pull/29821
It was done using small JavaScript code.
