### ISSUE TITLE
React ToDo List with axios

### ISSUE THREAD

**Issue by DanielPath** [mdn/content#2981]
Hello

It is a fantastic [tutorial](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_todo_list_beginning)! 

Thank you very much!

I got it running and thought I would use it for further learning.

My goal is to replace

const DATA = [
  { id: "todo-0", name: "Eat", completed: true },
  { id: "todo-1", name: "Sleep", completed: false },
  { id: "todo-2", name: "Repeat", completed: false }
];

with actual data in index.js

For this I used axios within the index.js and I'm able to get data there.

The problem where I'm missing something is, how to pass it to the props in

`ReactDOM.render(<App tasks={DATA} />, document.getElementById('root'));`

I have tried lots of approaches but I am stuck in any way, so I figured somewhere I'm using the wrong logic.

One of the attempt was to build a class within index.js and render it from there

  `render() {
    return (
    /*<ul>
      { this.state.records.map(record => <li>{record.name}</li>)}
    </ul>*/
      <App tasks={this.state.records} />
    );
  }`

In the above example it is working with:  `this.state.records.map` within the `<ul>`
but fails to pass it with `<App tasks={this.state.records} />`

If you are able to give me a pointer, I would greatly appreciate it!

Thank you very much!

Daniel

**Comment by DanielPath** [comment]
**Sorry I should have checked the preview! I'm new on github...**

`ReactDOM.render(<App tasks={DATA} />, document.getElementById('root'));`

I have tried lots of approaches but I am stuck in any way, so I figured somewhere I'm using the wrong logic.

One of the attempt was to build a class within index.js and render it from there

`render() {
    return (
    /*<ul>
      { this.state.records.map(record => <li>{record.name}</li>)}
    </ul>*/
      <App tasks={this.state.records} />
    );
  }`

In the above example it is working with:  `this.state.records.map` within the `<ul>`
but fails to pass it with `<App tasks={this.state.records} />`

**Comment by chrisdavidmills** [comment]
@DanielPath sorry for taking a long time to get back to you on this. You'd probablt get a quicker response if you posted this question on a dedicated React forum of some kind. This isn't really a place for general technical support about topics that aren't covered in our articles. Although it might be nice to add such a thing at some point in the future.

Glad you enjoyed the tutorials, and good luck.
