### ISSUE TITLE
Not all observers will be removed when one call observe with same target node

### ISSUE THREAD

**Issue by luckylooke** [mdn/content#29814]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe#reusing_mutationobservers

### What information was incorrect, unhelpful, or incomplete?

It says:
> all existing observers are automatically removed from all targets being observed

it sounds like total disaster, that all observers will be removed, but specification says something much much lighter, that all transient observers will be removed which is much much lower damage

> For each node of this’s node list, remove all transient registered observers whose source is registered from node’s registered observer list.

https://dom.spec.whatwg.org/#interface-mutationobserver section with `observe()` method steps

### What did you expect to see?

Something more clear that only transient observers are removed with briefly explanation of what those are.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mutationobserver/observe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mutationobserver/observe/index.md
* Last commit: https://github.com/mdn/content/commit/0029350cf0aa473b0f14cfda0365b15655aadd4e
* Document last modified: 2023-06-07T12:27:03.000Z

</details>

**Comment by senocular** [comment]
Noticed this one today. Not sure transient observers need to be covered. I think it just needs to point out that if you observe a target that's already being observed by this observer, the old options will be replaced with the new options for that target. In either case, as far as the user is concerned, all other targets are untouched when observing a new, or existing target.
