### ISSUE TITLE
box-shadow does not apply to <tr> tag in Safari

### ISSUE THREAD

**Issue by ForceAwakenz** [mdn/content#29839]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Applies to | all elements. It also applies to ::first-letter.

### What did you expect to see?

Applies to | all elements. It also applies to ::first-letter.

Exception: doesn't apply to tr tag in Safari

### Did you test this? If so, how?

Yes, I had a bug report in my project, where this issue was found.
Also I tested it in codepen, to play around.

### Do you have anything more you want to share?

It worth checking if thead, tbody also are able to drop shadow in Safari.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.box-shadow`
* Report started: 2023-10-23T07:53:11.980Z

</details>

**Comment by caugner** [comment]
The issue about the highlighted text in the [Formal definition](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow#formal_definition) section:

<img width="1150" alt="image" src="https://github.com/mdn/content/assets/495429/4c2cc989-797f-4ff4-8bf2-f6f32cfc75b9">

**Comment by ForceAwakenz** [comment]
> MDN Playground
Sure: https://developer.mozilla.org/en-US/play?id=vVumy4KW0Sa1T%2FipHVid22%2FdOO0UcaWi1awY9T%2FVBxVsi0rmN7YOgHV4wHxUJKIUM5y8FgWuckH7Rrex

**Comment by caugner** [comment]
Thank you @ForceAwakenz, I verified with your Share that the box-shadow on the `tr` is not rendered in Safari, while it is rendered in Firefox and Chrome:

| Firefox | Chrome | Safari |
|--------|--------|--------|
| <img width="748" alt="image" src="https://github.com/mdn/content/assets/495429/47a1a71b-dc32-4482-81b3-ff937cb22dc0"> | <img width="716" alt="image" src="https://github.com/mdn/content/assets/495429/27a33191-bed4-4878-8f39-d2cfcd350fba"> | <img width="469" alt="image" src="https://github.com/mdn/content/assets/495429/a10cc7b6-9784-4858-9549-8913eb2971e9"> |

**Comment by caugner** [comment]
@ForceAwakenz Can you please report the issue using Apple's [Feedback Assistant](https://feedbackassistant.apple.com/) (you'll need an Apple ID)?

**Comment by ForceAwakenz** [comment]
> @ForceAwakenz Can you please report the issue using Apple's [Feedback Assistant](https://feedbackassistant.apple.com/) (you'll need an Apple ID)?

![image](https://github.com/mdn/content/assets/83182111/9a8e02f2-103a-4a28-a399-d72468805ba0)

Didn't work out for some reason. 🤷‍♂️

**Comment by caugner** [comment]
@ForceAwakenz If you still experience this issue, please retry reporting it to Apple.

As this is a browser bug, I'm going ahead and close this issue as "won't fix".
