### ISSUE TITLE
CSS style appears wrong 

### ISSUE THREAD

**Issue by lnbEli** [mdn/content#29848]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form

### What specific section or headline is this issue about?

The headers (Card type, Email, Password etc. are aligned incorrectly

### What information was incorrect, unhelpful, or incomplete?

The headers (Card type, Email, Password, Card type, Card number, Expiration date are all aligned incorrectly. Link to live view of form is not the same as screenshot. 

### What did you expect to see?

![Screenshot 2023-10-27 at 11 32 52](https://github.com/mdn/content/assets/137424458/52b9b1ec-c41d-44c8-a271-9abc7fc61058)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/how_to_structure_a_web_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_structure_a_web_form/index.md
* Last commit: https://github.com/mdn/content/commit/7c36ed67cb4325ea08a813af49d47caef6df8020
* Document last modified: 2023-08-21T22:29:20.000Z

</details>

**Comment by bsmth** [comment]
Thanks for raising this one, there's a PR to fix this here: https://github.com/mdn/content/pull/29838

**Comment by bsmth** [comment]
This is now fixed in the linked PR - thanks for reporting!
