### ISSUE TITLE
Unreadable images with dark theme on

### ISSUE THREAD

**Issue by uniresuto** [mdn/content#29840]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages

### What specific section or headline is this issue about?

Transparent images

### What information was incorrect, unhelpful, or incomplete?

A lot of images have transparent background and with dark mode activated text on them becomes unreadable.

like this:
![image](https://github.com/mdn/content/assets/85786513/03b67d86-edf3-4ad4-8b02-1c5ab28b9c08)

### What did you expect to see?

Expected to see something like this:
![image](https://github.com/mdn/content/assets/85786513/2f6d6374-7e6d-4651-88fd-ef3674820472)

**Comment by Josh-Cena** [comment]
Please see https://github.com/mdn/content/issues/29794
