### ISSUE TITLE
Bug of `{{DefaultAPISidebar("Badging API")}}`

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#29853]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Badging_API

### What information was incorrect, unhelpful, or incomplete?

the {{DefaultAPISidebar("Badging API")}} is completely empty without anything, whether the api summary or its methods

### What did you expect to see?

ditto

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/badging_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Badging_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/badging_api/index.md
* Last commit: https://github.com/mdn/content/commit/835d6632d59993861a0458510402787f8a2c3cb3
* Document last modified: 2023-10-25T17:27:32.000Z

</details>

**Comment by caugner** [comment]
The sidebar for the Badging API does not have any items, because the [GroupData.json](https://github.com/mdn/content/blob/main/files/jsondata/GroupData.json) has no "Badging API" entry.
