### ISSUE TITLE
Selected attribute in bookinstance_form.pug example is set to a string, this does not set initial selection as intended

### ISSUE THREAD

**Issue by PeterHellmuth** [mdn/content#29859]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_BookInstance_form

### What specific section or headline is this issue about?

The view bookinstance_form.pug in this tutorial has an incorrect line of code that does not produce expected results 

### What information was incorrect, unhelpful, or incomplete?

For this section of the bookinstance .pug view the end html result for a selected option is `<option selected="selected">` due to this ternary operator:
```
for book in book_list
          option(value=book._id, selected=(selected_book==book._id.toString() ? 'selected' : false) ) #{book.title}
```
This will not load the intended initial option later in the tutorial when this form is fed a selected_book value from implementing a bookinstance_update GET method in the bookinstance controller.

The attribute should be simply present in the html, for example `<option selected>`

### What did you expect to see?

I am unsure of the .pug syntax, but the view should output an html option tag like `<option selected>` for the selected option.

Possibly this would be the correct way to write this in pug:
```
for book in book_list
          option(value=book._id, (selected_book==book._id.toString() ? 'selected' : '') ) #{book.title}
```

### Do you have any supporting links, references, or citations?

The selected attribute of the option tag is a boolean attribute, it should be present to indicate initial selection, not set to a string.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_bookinstance_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_BookInstance_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_bookinstance_form/index.md
* Last commit: https://github.com/mdn/content/commit/8a07b51f108bc73040f3ef6cef7ca192342846f2
* Document last modified: 2023-07-19T10:40:53.000Z

</details>

**Comment by hamishwillee** [comment]
The code is actually correct and if you test it you will find that it works. 
From the spec:

> If the attribute is present, its value must either be the empty string or a value that is an ASCII _case-insensitive match for the attribute's canonical name_, with no leading or trailing whitespace."

However it is an unfamiliar and uncommon way of doing things. So I have updated this in #29892. Even though this now defines `selected=""` in pug, this will show as the bare `selected` when you view the tag in source.

Thanks for posting - good to make things as straightforward as possible.
