### ISSUE TITLE
Confusing claim on JS for :fullscreen

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#29856]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

> In this example, the color of a button is changed depending on whether or not the document is in fullscreen mode. This is done without needing to specifically apply style changes using JavaScript.

In a web development support group on Matrix, a beginner was confused by the last sentence.
The example showed a demo with a button, but no event handler on the button to [toggle fullscreen mode](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API/Guide#activating_fullscreen_mode).

As such the example appears to be incomplete.

### What did you expect to see?

I could imagine that either JS is added to request fullscreen mode (as hinted in other places on the subject) or that F11 is an OS-supported way to enter the fullscreen mode or that a sentence is added to explain, that the example is valid once the fullscreen mode is entered.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_fullscreen`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_fullscreen/index.md
* Last commit: https://github.com/mdn/content/commit/6b1e3eebf22abf1b73bb219581335b1147b75d7a
* Document last modified: 2023-03-12T09:29:44.000Z

</details>

**Comment by chrisdavidmills** [comment]
@Ryuno-Ki I think https://github.com/mdn/content/pull/29951 fixes this issue. Let me know if you agree, and therefore if we can close this issue. Thanks!

**Comment by Ryuno-Ki** [comment]
@chrisdavidmills I've talked back to the person of the support room I mentioned and got confirmation that the new version clarifies the situation.

My apologies for not being able to pick up my work here. COVID struck me down and I'm only now recovering slowly.

@yookoala Thanks for picking this up!
