### ISSUE TITLE
Missing documentation of `WorkerGlobalScope.rejectionhandled` and `WorkerGlobalScope.unhandledrejection`

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#29869]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope

### What information was incorrect, unhelpful, or incomplete?

`WorkerGlobalScope.rejectionhandled` and `WorkerGlobalScope.unhandledrejection` are in standard, but there documentation is not written yet

see https://html.spec.whatwg.org/multipage/workers.html#the-workerglobalscope-common-interface

also, in WorkerGlobalScope summary, these two properties are incorrectly marked as non_standard

### What did you expect to see?

ditto.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/workerglobalscope`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/workerglobalscope/index.md
* Last commit: https://github.com/mdn/content/commit/997a0ec66e1514b7269076195b2419db334e876e
* Document last modified: 2023-08-29T04:27:41.000Z

</details>

**Comment by caugner** [comment]
It looks like the [WorkerGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope) section is outdated and as such incomplete.

The `rejectionhandled` and `unandledrejection` event types are now mentioned in the standard, and should be documented.
