### ISSUE TITLE
Issue with "Date.prototype.toUTCString()": (CSS refused to apply due to strict MIME checking)

### ISSUE THREAD

**Issue by joeldunstanADP** [mdn/content#2988]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toUTCString

#### What information was incorrect, unhelpful, or incomplete?
The css for the page isn't loading due to a MIME type error
![image](https://user-images.githubusercontent.com/70308671/110569605-d308f300-81a8-11eb-9e6a-bd31ac603bf9.png)

#### Specific section or headline?
Entire page

#### Did you test this? If so, how?
Opened in multiple browsers, and on multiple computers
![image](https://user-images.githubusercontent.com/70308671/110569774-106d8080-81a9-11eb-9776-bfcf83673499.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/toutcstring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toUTCString
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/toutcstring/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment]
I can’t reproduce this. https://developer.mozilla.org/static/css/main.1a22eae5.chunk.css is the current stylesheet that document is served with, at it’s correctly served as `text/css`:

```
$ curl -I https://developer.mozilla.org/static/css/main.1a22eae5.chunk.css
HTTP/2 200
content-type: text/css; charset=utf-8
```
…and same for the stylesheet shown in the https://user-images.githubusercontent.com/70308671/110569605-d308f300-81a8-11eb-9e6a-bd31ac603bf9.png image —

```
$ curl -I https://developer.mozilla.org/static/css/main.d8c1813a.chunk.css
HTTP/2 200
content-type: text/css; charset=utf-8
```

**Comment by joeldunstanADP** [comment]
I've reloaded the page and can't reproduce either, not sure what happened

**Comment by sideshowbarker** [comment]
Thanks for reporting it. It’s imaginable it might happen again for others, so it’s good to have a record here.
