### ISSUE TITLE
Possibly incorrect code example about namespace prefixes

### ISSUE THREAD

**Issue by kmdouglass** [mdn/content#29888]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course

### What specific section or headline is this issue about?

Declaring namespace prefixes

### What information was incorrect, unhelpful, or incomplete?

I believe that the first code example is missing the `xlink` namespace prefix on the `href` parameter. Currently, the example is:

```
<svg
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <script href="cool-script.js" type="text/ecmascript" />
</svg>
```

The second paragraph that follows this example states:

> As their name suggests, namespace prefixes are used to prefix parameter and element names. This is done by putting the namespace prefix and a colon before the parameter name as shown on the <script> element in the example above. This tells the user agent that the particular parameter belongs to the namespace assigned to the namespace prefix (XLink), and is a parameter that can be used with the same meaning on other elements.

which leads me to believe that the `href` parameter of the `script` element is missing a prefix. Additionally, the above paragraph is confusing because it states that the `xlink` prefix should go before the `script` element, not the `href` parameter.

### What did you expect to see?

```
<svg
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <script xlink:href="cool-script.js" type="text/ecmascript" />
</svg>
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/namespaces_crash_course`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/namespaces_crash_course/index.md
* Last commit: https://github.com/mdn/content/commit/32d1c9ff83019f8efae3e7987a55e83035e4b926
* Document last modified: 2023-08-25T22:38:09.000Z

</details>

**Comment by pepelsbey** [comment]
Hey! Good catch :) There’s definitely a mistake here. As for the confusing paragraph, it kind of makes sense:

> This is done by putting the namespace prefix and a colon **before the parameter name** as shown on the <script> element in the example above.

It doesn’t sound confusing to me, but feel free to suggest a better wording :)

**Comment by kmdouglass** [comment]
Thanks @pepelsbey 

Actually, on second reading, I think the paragraph is only confusing when the code example is wrong. I think that fixing the code example is sufficient.
