### ISSUE TITLE
Lack of mention of namespaced attributes in https://developer.mozilla.org/en-US/docs/Web/CSS/Namespace_separator

### ISSUE THREAD

**Issue by lwchkg** [mdn/content#29918]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Namespace_separator

### What specific section or headline is this issue about?

Lack of mention of namespaced attribute

### What information was incorrect, unhelpful, or incomplete?

As title

### What did you expect to see?

Something like https://oreillymedia.github.io/Using_SVG/extras/ch03-namespaces.html

In which the most important part is given in the screenshot:
![image](https://github.com/mdn/content/assets/4113719/1da07f88-37c1-4b12-afd7-b2afab163205)

### Do you have any supporting links, references, or citations?

https://oreillymedia.github.io/Using_SVG/extras/ch03-namespaces.html

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/namespace_separator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Namespace_separator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/namespace_separator/index.md
* Last commit: https://github.com/mdn/content/commit/b85bf9fcc2c0062a765d104799d7d45d9e9b13bb
* Document last modified: 2023-07-22T00:55:30.000Z

</details>

**Comment by pepelsbey** [comment]
Hello! It’s a nice book you’re quoting :) But I’d say that the `@namespace` usage is covered enough in both examples on that page: [one](https://developer.mozilla.org/en-US/docs/Web/CSS/Namespace_separator#css) and [two](https://developer.mozilla.org/en-US/docs/Web/CSS/Namespace_separator#css_2). If you have any specific ideas on how to improve existing examples even further, please let us know or send a PR.
