### ISSUE TITLE
Demo of font-variant-caps not only applies to captial letters as described

### ISSUE THREAD

**Issue by robopzet** [mdn/content#29910]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-caps

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

The description of the property states it _controls the use of alternate glyphs for **capital letters**._. (emphasis mine)

When selecting the examples with the value `small-caps` and `all-small-caps` not only the uppercase character changes, but all text, including lowercase.

### What did you expect to see?

Only the first character, the uppercase **D** to change.

Or, if the behavior is correct, a description that does not state it only applies to capital letters.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-variant-caps`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-caps
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-variant-caps/index.md
* Last commit: https://github.com/mdn/content/commit/53e79df7874e919c9f7f74281347613edc6711af
* Document last modified: 2023-10-04T19:15:37.000Z

</details>

**Comment by pepelsbey** [comment]
Hello! Good catch :) This property applies to all letters, not just capital ones. [The spec](https://www.w3.org/TR/css-fonts-4/#font-variant-caps-prop) is clear about this:

> This property allows the selection of alternate glyphs used for small or petite capitals or for titling.

Feel free to suggest a better wording.

**Comment by BartoszKlonowski** [comment]
I would like to work on this! @pepelsbey please assign me if possible, so I have that on my mind.

**Comment by pepelsbey** [comment]
@BartoszKlonowski, you got it! Thank you :)
