### ISSUE TITLE
`URL.canParse()` may mark as experimental

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#29932]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/URL/canParse_static

### What information was incorrect, unhelpful, or incomplete?

`URL.canParse()` may mark as experimental

### What did you expect to see?

see https://github.com/mdn/browser-compat-data/issues/21131

### Do you have any supporting links, references, or citations?

https://caniuse.com/?search=URL%3A%20canParse

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/url/canparse_static`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URL/canParse_static
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/url/canparse_static/index.md
* Last commit: https://github.com/mdn/content/commit/7c7a078585a36eef960de1d93d28b20691486b99
* Document last modified: 2023-06-26T03:46:21.000Z

</details>

**Comment by Josh-Cena** [comment]
Our status perfectly mirrors BCD, so there's no need for an issue here.

**Comment by skyclouds2001** [comment]
Thanks, I'll pay attention to this
