### ISSUE TITLE
`window.ondragdrop` property should regard as event rather than a property

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#29935]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/ondragdrop

### What information was incorrect, unhelpful, or incomplete?

`window.ondragdrop` property should regard as event rather than a property

### What did you expect to see?

change `window.ondragdrop` property to `window.dragdrop` event

### Do you have any supporting links, references, or citations?

see its content example

```js
window.addEventListener("dragdrop", testfunc, false)
```

it seems that `window.ondragdrop = testfunc` can also be used as `window.addEventListener("dragdrop", testfunc)`

---

additionally, this handler seemed to be no longer supported by major browsers, include `Chrome` `Edge` `Firefox`, as I tested, so it is not easy to test it; also no compat data and can i use data is found

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/ondragdrop`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/ondragdrop
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/ondragdrop/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by caugner** [comment]
The [ondragdrop](https://developer.mozilla.org/en-US/docs/Web/API/Window/ondragdrop) page documents a feature that has been deprecated in favor of the [Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API). This API includes several `drag*` events and a `drop` event, but it looks like `dragdrop` is not part of it, and not mentioned as an event in the [HTML spec](https://html.spec.whatwg.org/multipage/indices.html) either. Furthermore I couldn't see any effect when [running the content example in the Playground](https://developer.mozilla.org/en-US/play?id=Ve%2BpmwVdZcJn8oP2gznZWTUfCXU6LLfTb7qsjb2SvyapmADtlwmuHcxygrz32E3%2FeW12HmWnXmCA9w0r).

Based on this, I don't think it makes sense to change the page, and I'm going ahead and close this issue as wontfix.

If you have any additional information in favor of your proposal, please don't hesitate to leave a comment.

**Comment by skyclouds2001** [comment]
Honestly, the most information I get are mainly from the content itself, also from firefox bug report https://bugzilla.mozilla.org/buglist.cgi?quicksearch=ondragdrop

The content suggest that it is a proposal only available to firefox (also may be available in Netscape according to firefox bug report) and has removed since Firefox 50. That's why test it will takeno effect. (assume that the content is correct)

And the content also suggest that it have to be used via addEventListener and can not used via `ondragdrop` property in firefox. (also assume that the content is correct)

So it means that the two usage are also possible: `ondrapdrop=handle` and `addEventListener('drapdrop', handle)`, also checked from https://bugzilla.mozilla.org/show_bug.cgi?id=50582

It means that `drapdrop` is an event, so it can both use in the two ways above

In early documentations, most events are documentated not as event but as `on*` event handle properties, it seems that `ondragdrop` is a left un-updated documentation

I understand that currently most browsers do not support for this proposal and so maybe it is not quite necessary to update the documentation as nobody may use this; but maybe it is better to ducumented it as `drapdrop` event better than `ondragdrop` property
