### ISSUE TITLE
Incorrect explanation of example in 'Requesting multiple ranges'

### ISSUE THREAD

**Issue by jrandall** [mdn/content#29964]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range#requesting_multiple_ranges

### What specific section or headline is this issue about?

Requesting multiple ranges

### What information was incorrect, unhelpful, or incomplete?

An example Range header is given:
```
Range: bytes=200-1000, 2000-6576, 19000-
```

The text above this begins by saying: "The following example requests three separate parts of a file, from 200-1000 (the first 800 bytes),"

This seems to be doubly wrong. For one thing, the bytes from 200 to 1000 are not the first bytes of the file. Also, the range from 200-1000 consist of 801 bytes, not 800 bytes. This is very misleading as it suggests that the range end may not be inclusive. 

### What did you expect to see?

Either the text or the example should be changed. 

If the example is changed to match the text, I believe it should be: 
```
Range: bytes=0-799, 2000-6576, 19000-
```

If the text is changed to match the example, I believe it should be:
"The following example requests three separate parts of a file, from 200-1000 (the 801 bytes from 200 to 1000),"

### Do you have any supporting links, references, or citations?

RFC9110 makes it very clear that the start and end ranges are inclusive, and gives an example of 0-499 referring to the first 500 bytes: https://www.rfc-editor.org/rfc/rfc9110#section-14.1.2

### Do you have anything more you want to share?

It might also be helpful to make a note elsewhere in this page to state clearly that the specified range positions are inclusive. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/range`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/range/index.md
* Last commit: https://github.com/mdn/content/commit/5e9631df85d021e84133e14f4bd3c712e4f8fe08
* Document last modified: 2023-08-25T00:21:46.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting @jrandall - you're correct and I've assigned myself on this one, I'll get around to it shortly.

**Comment by bsmth** [comment]
There's a PR to address this here:

- [ ] https://github.com/mdn/content/pull/29980
