### ISSUE TITLE
V8 String maximum length

### ISSUE THREAD

**Issue by OMartinez-NeT** [mdn/content#29967]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length

### What specific section or headline is this issue about?

V8 String maximum length

### What information was incorrect, unhelpful, or incomplete?

> In V8 (used by Chrome and Node), the maximum length is 2 ^ 29 - 24 (~1GiB). On 32-bit systems, the maximum length is 2 ^ 28 - 16 (~512MiB).

However from this [comment](https://github.com/nodejs/node/issues/35973#issuecomment-722253319) and this [one](https://github.com/nodejs/node/issues/35973#issuecomment-722265686) it seems the maximum length is 512MiB instead of 1GiB

### What did you expect to see?

> In V8 (used by Chrome and Node), the maximum length is 2 ^ 29 - 24 (~512MiB). On 32-bit systems, the maximum length is 2 ^ 28 - 16 (~256MiB).

### Do you have any supporting links, references, or citations?

[V8 String definition](https://github.com/nodejs/node/blob/eb24573987b27ad516b5bc86bfb320660540e2bf/deps/v8/include/v8.h#L3004-L3007)

**Comment by Josh-Cena** [comment]
In the comment you quoted:

> `((1 << 29) - 24)` = 536870888 = 512M (which is the current browser limit in Chrome too)

Is `((1 << 29) - 24)` the character limit or the byte limit? In the second quote you have, the referenced code is setting the maximum _length_. But remember that each JS character is actually 2 bytes (under UTF16), so 512M characters is going to occupy 1GiB of space.

**Comment by caugner** [comment]
FWIW The String max length was increased for 64-bit in [this V8 commit](https://github.com/v8/v8/commit/e8c9649e2570c7e278e70a6584738a3c3f828b2b), and [the value has not changed since](https://github.com/v8/v8/blame/04f51bc70a38fbea743588e41290bea40830a486/include/v8-primitive.h#L121-L127).

**Comment by OMartinez-NeT** [comment]
Hey @Josh-Cena thanks for getting back to me

>  Are you running into actual problems with a string occupying more than 512MiB but less than 1GiB, or are you simply trying to cross-compare two sources?

I'm simply trying to cross-compare two sources. 

> Is ((1 << 29) - 24) the character limit or the byte limit?

It seems the byte limit. 

I did this example: 
```js
const fs = require('fs');
const MB_FILE = 512;

const str = 'a'.repeat(MB_FILE * 1024 * 1024);
const blob = new Blob([str], { type: 'text/plain' });

blob.arrayBuffer().then((buffer) => {
   fs.writeFileSync(`${MB_FILE}MB.txt`, Buffer.from(buffer));
   console.log('saved');
});
```

I got `Invalid string length` but If I change `MB_FILE` for 511, the file is saved with a file size of 535MB. So I wonder 

> But remember that each JS character is actually 2 bytes (under UTF16), so 512M characters is going to occupy 1GiB of space.

511M characters should occupy 1GiB of space in the example above but it didn't. What did I miss? thanks!

**Comment by stof** [comment]
Be careful. The default encoding for Blob is UTF-8, not UTF-16. So checking the size of the file on the filesystem won't tell you the size of the JS string in memory.

**Comment by Josh-Cena** [comment]
We care about the string's length limit, not when it's saved to a file, so the only line relevant is: `const str = 'a'.repeat(MB_FILE * 1024 * 1024);` In UTF16, basic Chinese characters such as `汉` occupy the same space as `a`, so the only difference between your two examples is `MB_FILE` being 512 in the first and 511 in the second. This proves that the length limit is between 2^29 - 2^20 and 2^29 characters, which fits the documentation description.
