### ISSUE TITLE
Illogical mention to the specificity of Pseudo-elements, Pseudo-classes

### ISSUE THREAD

**Issue by Amer-Adel** [mdn/content#29978]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

### What specific section or headline is this issue about?

Specificity

### What information was incorrect, unhelpful, or incomplete?

- An element selector is less specific; it will select all elements of that type that appear on a page, so it has less weight. Pseudo-element selectors have the same specificity as regular element selectors.
- A class selector is more specific; it will select only the elements on a page that have a specific class attribute value, so it has more weight. Attribute selectors and pseudo-classes have the same weight as a class.

--------

Why you mention to the specificity of Pseudo-elements, Pseudo-classes, while there is no other way to target the pseudo element other than the Pseudo-element's selector or target an element in a specific state other than the element is pseudo-element's selector.

So, they are the only way for selecting their elements and there are no other selectors to conflict with each other in the specificity, they are just following the cascade concept to resolve their conflicts.

### What did you expect to see?

Delete the two mentions to Pseudo-elements, Pseudo-classes, because that is illogical, they shouldn't have a specificity.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
* Last commit: https://github.com/mdn/content/commit/5f0a9e8c258072ed8146401584162c232331c77d
* Document last modified: 2023-09-15T00:23:30.000Z

</details>

**Comment by OnkarRuikar** [comment]
The statements are according to the current specs: [[](https://drafts.csswg.org/selectors/#specificity-rules)]
>- count the number of class selectors, attributes selectors, and pseudo-classes in the selector (= B)
>- count the number of type selectors and pseudo-elements in the selector (= C)

> they shouldn't have a specificity.

But they do compete with other selectors. See a demo https://jsfiddle.net/kmbdz6fs/1/
You need to raise the issue at source i.e. specs repo https://github.com/w3c/csswg-drafts/issues

**Comment by Rumyra** [comment]
Agree with @OnkarRuikar - this is not an issue

**Comment by Amer-Adel** [comment]
You are right, it's being clear for me from here [Specificity](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#specificity_2)
Thanks for you, and sorry for this wrong issue.
