### ISSUE TITLE
Is the value attribute supported on the textarea tag?

### ISSUE THREAD

**Issue by IDrumsey** [mdn/content#29982]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

### What specific section or headline is this issue about?

textarea

### What information was incorrect, unhelpful, or incomplete?

It says
> <textarea> does not support the value attribute.

The attribute seems to work contrary to the docs.

### What did you expect to see?

Maybe clarification on why it works but isn't supported. unless the docs are wrong.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/textarea`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/textarea/index.md
* Last commit: https://github.com/mdn/content/commit/62b2885cf645395c39081f8ffa8f6023d7d1bc0b
* Document last modified: 2023-07-31T13:02:39.000Z

</details>

**Comment by caugner** [comment]
@IDrumsey Can you provide an example of the value attribute on the `<textarea>` doc working?

In this [Playground share](https://developer.mozilla.org/en-US/play?id=vzNSYbbIhsoy3xPaiK897XkprDKyDAJ8GTLn7wqMRqiE8dOCDohLUzk2tVyUCIqw4j8LvbXUV5G%2B4Qtw), I see an empty textarea despite the value, as I would expect.

**Comment by Josh-Cena** [comment]
You are probably confusing `<textarea value>` with `HTMLTextAreaElement#value`. You can do `areaElement.value` but not set it in HTML.
