### ISSUE TITLE
Page need updating: grid is supported

### ISSUE THREAD

**Issue by estelle** [mdn/content#29997]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Grid_layout_and_progressive_enhancement

### What information was incorrect, unhelpful, or incomplete?

There's a fallback section. That is not needed.

### What did you expect to see?

relevant content.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_grid_layout/grid_layout_and_progressive_enhancement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Grid_layout_and_progressive_enhancement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_grid_layout/grid_layout_and_progressive_enhancement/index.md
* Last commit: https://github.com/mdn/content/commit/c51e0599ea09c0e6d035c635db9f48ad1f241490
* Document last modified: 2023-07-05T05:48:35.000Z

</details>

**Comment by caugner** [comment]
@estelle When you say "fallback section" do you refer to a specific section of the page? It looks like you might be referring to the [A solution using feature queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Grid_layout_and_progressive_enhancement#a_solution_using_feature_queries) section?

**Comment by estelle** [comment]
I removed the fallback section forgetting that i had opened this issue. Issue is resolved, so closing.
