### ISSUE TITLE
`History: pushState() method` section-content is confusing

### ISSUE THREAD

**Issue by zjlovezj** [mdn/content#30014]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/History/pushState

### What specific section or headline is this issue about?

section-content

### What information was incorrect, unhelpful, or incomplete?

> This method is [asynchronous](https://developer.mozilla.org/en-US/docs/Glossary/Asynchronous). Add a listener for the [popstate](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event) event in order to determine when the navigation has completed. The state parameter will be available in it.

### What did you expect to see?

`This method is asynchronous.` sort of implies that the popstate event listener got a event when history.push has resolved.

And how do the user know when history.push has resolved? Or maybe it doesn't matter.

popstate event may never fired as [popstate](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event) described.

I think it should made clear that history.push trigger no events, correct me if I'm wrong.

### Do you have anything more you want to share?

From blank page to abc.html, abc.html includes below js
```js
history.pushState({a: 1}, '');
history.pushState({a: 2}, '');
```
If pushState without change url, at least in Chrome, 
1. click browser Back button will go back to the blank page
2. do history.back() will stay at the abc.html and trigger a popstate event

Maybe this behavior worth a notice.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/history/pushstate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/History/pushState
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/history/pushstate/index.md
* Last commit: https://github.com/mdn/content/commit/ab8736c08a6664970fec04088182b8c5e29a570a
* Document last modified: 2023-09-27T04:57:54.000Z

</details>

**Comment by wbamberg** [comment]
I'm not very familiar with this API and our docs on it (especially the guide) are very confusing, but yes, this looks like a mistake to me. `pushState()` doesn't cause a navigation, it just adds an entry to the history. So "when the navigation has completed" is not connected to `pushState()` completing, right?

This paragraph was added in https://github.com/mdn/content/pull/25702, to match some APIs like [`forward()`](https://developer.mozilla.org/en-US/docs/Web/API/History/forward) that _do_ cause a navigation. I wonder if this was an error - @teoli2003 do you know?
