### ISSUE TITLE
Explanation of http code 304 - Not Modified, has the word OR but should have AND

### ISSUE THREAD

**Issue by chdb** [mdn/content#30016]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304

### What information was incorrect, unhelpful, or incomplete?

"This happens when the request method is a [safe] method, such as [GET] or [HEAD], **OR** when the request is conditional and uses an [If-None-Match] or an [If-Modified-Since] header."

### What did you expect to see?

"This happens when the request method is a [safe] method, such as [GET] or [HEAD], **AND** when the request is conditional and uses an [If-None-Match] or an [If-Modified-Since] header."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/304`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/304/index.md
* Last commit: https://github.com/mdn/content/commit/c15a06bd8bf9c4b859c7eef07f014517ed3f72df
* Document last modified: 2023-04-12T08:48:18.000Z

</details>

**Comment by bsmth** [comment]
Thanks for opening this one @chdb - I think the original is correct as the conditionals (specifically https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) can be used with other methods. I'm going to close this one, but if you think I've made a mistake, please reply here! Thank you :)

**Comment by chdb** [comment]
Thanks for your quick response. 
However the rfc does not seem to agree with you. I think it is saying that 304 can only happen in response to conditional GET or HEAD requests. 
https://www.rfc-editor.org/rfc/rfc9110#status.304
So I still think the MDN text is misleading - it says EITHER the request is Safe OR it is Conditional. BUT I think the request has to be both Safe AND Conditional.

Admittedly, owing to the peculiarities of English, the MDN  text is a bit ambiguous, and unfortunately my suggested text (above) is no better. 
I would replace it with this-
"This happens when the request has a [safe] method, such as [GET] or [HEAD], and is conditional: having an [If-None-Match] or an [If-Modified-Since] header."

**Comment by bsmth** [comment]
> However the rfc does not seem to agree with you. I think it is saying that 304 can only happen in response to conditional GET or HEAD requests.
> https://www.rfc-editor.org/rfc/rfc9110#status.304

😄 thanks a lot for pointing it out, that looks correct, indeed, that's the crux of it:

>a conditional GET or HEAD request

Would you like to open a pull request for this or shall I go ahead and suggest changes?

**Comment by chdb** [comment]
Please go ahead with whatever changes you think right. I just wanted to ask
about this as a complete amateur - I don't really have
any expertise.
