### ISSUE TITLE
Url has some undocumented formats

### ISSUE THREAD

**Issue by EdgardoArriagada** [mdn/content#30017]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Location/assign

### What specific section or headline is this issue about?

#parameters

### What information was incorrect, unhelpful, or incomplete?

the section only talks about adding a full url as string, but there are different behaviors depending on the string given

I.E

In my browser I have open the url
`https://developer.mozilla.org/en-US/docs/Web/API/Location/assign`

If I open the console and execute:

`document.location.assign("/foo")`
the browser will redirect to: `https://developer.mozilla.org/foo`

`document.location.assign("bar")`
the browser will redirect to: `https://developer.mozilla.org/en-US/docs/Web/API/Location/bar`

I have identified these two so far

### What did you expect to see?

the complete list of available formats to pass to the assign method with their corresponding behavior (maybe touch the #example section as well)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/location/assign`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Location/assign
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/location/assign/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by Rumyra** [comment]
Worth adding an example for relative urls below the absolute example

**Comment by BartoszKlonowski** [comment]
I will work on this!
