### ISSUE TITLE
Content update: performance.mark|measure x UserTiming Level 3

### ISSUE THREAD

**Issue by jakub-g** [mdn/content#3001]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Performance/mark
https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure

## Specific page section or heading?

- Return value
- Specifications
- parameters

## What is the problem?

- New version of spec (UT L3) was released: https://www.w3.org/TR/user-timing-3/
- Shipped in [Chrome 78](https://www.chromestatus.com/feature/5149401886490624) and will ship soon in [Safari 14.1](https://webkit.org/blog/11333/release-notes-for-safari-technology-preview-115/). [Not yet in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1581705)
- It makes `performance.mark|measure` return `PerformanceMark` `PerformanceMeasure` (and not `void`)

![image](https://user-images.githubusercontent.com/1437027/110644805-c048eb00-81b5-11eb-8e27-250a24166f6c.png)

- `perf.mark` accepts  `startTime` param: 

```
      performance.mark('a', {startTime: 900})
      performance.mark('b', {startTime: 999})
      performance.measure('a->b', 'a', 'b')
```

![image](https://user-images.githubusercontent.com/1437027/110645601-685eb400-81b6-11eb-89cd-76e38b5c89ca.png)

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Add the updated return value info https://developer.mozilla.org/en-US/docs/Web/API/Performance/mark with link to https://developer.mozilla.org/en-US/docs/Web/API/PerformanceMark
* Add the updated return value info https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure with link to https://developer.mozilla.org/en-US/docs/Web/API/PerformanceMeasure

**Comment by CreaTorAlexander** [comment]
I can update this :+1:

**Comment by ayushi2019031** [comment]
I would like to work on this issue

**Comment by Rumyra** [comment]
Please feel free to @ayushi2019031 ☺️ Just assign yourself and let me know if you have any questions 👍

**Comment by himanshugarg** [comment]
Hi, let me know if you need different changes for this one.
