### ISSUE TITLE
Browser_action Manifest Key

### ISSUE THREAD

**Issue by CatherineCampbell117** [mdn/content#30025]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

It mentions in the first sentence that all properties are optional to use in the browser_action key. But it says on this doc https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Toolbar_button that there is a mandatory key of "deafult_icons" under the section 'Specifying the browser action'.

### What did you expect to see?

Conflicting information so not sure which one is correct

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/browser_action`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/manifest.json/browser_action/index.md
* Last commit: https://github.com/mdn/content/commit/0364790c3bb0eb7a6105d71670458191e0207fe4
* Document last modified: 2023-08-27T17:11:00.000Z

</details>

**Comment by rebloor** [comment]
Thanks for reporting this @CatherineCampbell117 I've now applied a fix. The short answer is none of the properties are mandatory.
