### ISSUE TITLE
Distasteful image text

### ISSUE THREAD

**Issue by MrAntix** [mdn/content#30046]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API/android-notification.png

Task "Bury Gran..." really?

### What did you expect to see?

something less flippant

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/notifications_api/using_the_notifications_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/notifications_api/using_the_notifications_api/index.md
* Last commit: https://github.com/mdn/content/commit/aee894b73fc73f51ce911c3f937695b8d1ee627e
* Document last modified: 2023-09-15T05:34:27.000Z

</details>

**Comment by hamishwillee** [comment]
@chrisdavidmills Do you think you could regenerate that image?

**Comment by hamishwillee** [comment]
Thanks very much!
