### ISSUE TITLE
IFrame Post message , Message Event Can't able listen  on Window 11 but  it is work for mac

### ISSUE THREAD

**Issue by saisuresh-banc91** [mdn/content#30066]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/message_event

### What information was incorrect, unhelpful, or incomplete?

```
window.addEventListener("message", (event) => {
  console.log(`Received message: ${event.data}`);
});
```
incomplete

### What did you expect to see?

For Window 11 why it is not worked ?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/message_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/message_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/message_event/index.md
* Last commit: https://github.com/mdn/content/commit/cc070123f72376faec06e36622c4fc723a75325f
* Document last modified: 2023-04-08T06:57:07.000Z

</details>

**Comment by caugner** [comment]
Hi @saisuresh-banc91, it looks like the message event is [supported in all browsers](https://developer.mozilla.org/en-US/docs/Web/API/Window/message_event#browser_compatibility). The example shows in what context the message event appears.

You can find a more complete example on the [Window: postMessage() method](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) article (which is linked in the "See also" section) in the [Examples section](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#examples).

I will go ahead and close this issue, but feel free to reopen it with more details about what content issue you're seeing.

**Comment by saisuresh-banc91** [comment]
Thanks @caugner
