### ISSUE TITLE
Express Tutorial Part 7: Railway isn't free anymore and its link is broken

### ISSUE THREAD

**Issue by iamashay** [mdn/content#30067]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment

### What specific section or headline is this issue about?

Example: Installing LocalLibrary on Railway

### What information was incorrect, unhelpful, or incomplete?

Since Railway has discontinued their free starter plan, this page needs to be updated. Instead of starter plan where $5 was renewed monthly, Railway now provides one time $5 as [free trial](https://docs.railway.app/reference/pricing#free-trial). 
Also, the link to Railway.app's docs are broken in the MDN tutorial here:

>-  Railway has a [starter plan](https://docs.railway.app/reference/plans#starter-plan) free tier that is really free, albeit with some limitations. The fact that it is affordable for all developers is really important to MDN!
>- Other limitations can be found in the [Railway plan documentation](https://docs.railway.app/reference/plans#starter-plan).

Some of the points also need to be updated which talks about the discontinued starter plan:

> The starter plan only offers 500 hours of continuous deployment time each month, and $5 of credit that is consumed based on usage. At the end of each month the hours and credit are reset and any projects must be redeployed. These constraints mean that you could run this tutorial continuously for about 21 days, which is more than enough for development and testing. However you wouldn't be able to use this plan for a "real" production site.

### What did you expect to see?

The content needs to be updated to reflect the new free trial plan of Railway.app. Since railway still provide free plan (with limitations), the content can just be updated to include this new plan and its limitations instead.

### Do you have any supporting links, references, or citations?

[Railway Will Be Discontinuing Free Plans](https://inleo.io/@geekgirl/railway-will-be-discontinuing-free-plans)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/deployment/index.md
* Last commit: https://github.com/mdn/content/commit/83f30ecaaeb6227dc0d4551f71eb8be1cacb8e94
* Document last modified: 2023-09-27T17:37:07.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for sharing the pricing changes (heads up to @hamishwillee who wrote this section).

**Comment by hamishwillee** [comment]
Thanks very much. I was aware they'd made some changes, but they've gone every further. 

I'm not sure what to do here. I moved from Heroku to Railway earlier in the year because Heroku removed their free plan. Now Railway have done the same thing. The free plan is important for accessibility but I really don't want to have to migrate "yet again" because it takes quite a lot of testing and update time. 

I guess if we can find an alternative it is worth it. ...

**Comment by joaodinizgit** [comment]
Hi @hamishwillee, replit.com have a free plan. I have a node/express web application there. But, I think next year they will remove the free plan.

**Comment by hamishwillee** [comment]
THanks @joaodinizgit ! "But, I think next year they will remove the free plan." - what makes you think that - have they announced it or is this just a feeling?

**Comment by joaodinizgit** [comment]
@hamishwillee, They announced this: "Starting on January 1st, 2024, Deployments will become the only way to host on Replit.". And to deploy, users will have to update to paid one.

**Comment by hamishwillee** [comment]
Though glitch does look kind of cool, need to be aware that the cost of migrating the docs is not trivial.

**Comment by bsmth** [comment]
>We don't need to do the second part - if there are no free options (ongoing) then Railway is no worse than any other option.

That's true.

>Though glitch does look kind of cool, need to be aware that the cost of migrating the docs is not trivial.

Yeah, something for our wishlist for '24? 😄

**Comment by hamishwillee** [comment]
> Yeah, something for our wishlist for '24? 😄

Maybe! I spent an hour looking at glitch last night. Actually getting this to work was zero work - just imported from github https://scintillating-decisive-valley.glitch.me/catalog/book/6572a7ba80c473a749e3b433 

My concern is that I don't know how realistic glitch is - i.e. Railway and Heroku are much more reflective of services people might use. So it's free, but is it a useful starting point example for real deployment? I wonder if we can have both - this is what you do for Railway, but here is Glitch too.
