### ISSUE TITLE
Synchronous and asynchronous requests guide is missing from the XMLHttpRequest sidebar 

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/content#30070]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests

### What specific section or headline is this issue about?

Web API  XMLHttpRequest Guides

### What information was incorrect, unhelpful, or incomplete?

The information was incomplete. 
1. Starting from https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests it can be seen in the breadcrumbs that Synchronous and asynchronous requests is under the XMLHttpRequest section. 
2. Upon returning to XMLHttpRequest  page using the breadcrumb link, it can be noticed that the Synchronous_and_Asynchronous_Requests page link is missing from that article/ sidebar. 
![image](https://github.com/mdn/content/assets/53306802/d6755f29-469e-4f50-aea4-dcb0070ce3a2)

### What did you expect to see?

A way of navigating from one page to another. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/xmlhttprequest/synchronous_and_asynchronous_requests`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/xmlhttprequest/synchronous_and_asynchronous_requests/index.md
* Last commit: https://github.com/mdn/content/commit/592f6ec42e54981b6573b58ec0343c9aa8cbbda8
* Document last modified: 2023-07-25T00:27:48.000Z

</details>

**Comment by caugner** [comment]
It looks like the guide is missing in the GroupData:

https://github.com/mdn/content/blob/3acbf8b5c5abd42812e7a8fcfca9f41e935b7456/files/jsondata/GroupData.json#L2325-L2330

**Comment by wbamberg** [comment]
XMLHttpRequest is a mess here.

What should happen is we should have an [API landing page](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types#api_landing_page) for the XHR spec, listing the interfaces defined in the spec and giving an overview. This should have the DefaultAPISidebar sidebar, and have the guide pages under it.

Then we should have an [API interface page](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types#api_reference_page) for the.`XMLHttpRequest` interface, listing its members. This should have the APIRef sidebar, and have the interface members like `send()` underneath it.

Instead, https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest is a weird hybrid - the page content looks like an interface page, but it uses DefaultAPISidebar and has guides under it. This means that the interface members don't appear in its sidebar, and links to the guide pages and other interfaces don't appear in the page content.

We should have:
- a new overview page called "XMLHttpRequest API" or something, that looks like an API landing page
- move the guide pages under there
- make the current XMLHttpRequest page use the APIRef sidebar
