### ISSUE TITLE
`pretty` value in the `text-wrap` doc is not fully documented

### ISSUE THREAD

**Issue by Christopher-Hayes** [mdn/content#30073]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap

### What specific section or headline is this issue about?

Syntax, Values, Formal Syntax

### What information was incorrect, unhelpful, or incomplete?

The `pretty` value only shows up in the "Formal Syntax" section. Not mentioned in either "Syntax" or "Values".

### What did you expect to see?

Seems like `pretty` should also show up in the "Syntax" section if it's in the "Formal Syntax" section.

It would also be helpful for `pretty` to be in the "Values" section which would explain what `pretty` does, (and ideally how it compares to `balance`)

### Do you have any supporting links, references, or citations?

`pretty` is mentioned in the W3C working draft here:

https://www.w3.org/TR/css-text-4/#valdef-text-wrap-style-pretty
> 'pretty' Specifies the UA should bias for better layout over speed, and is expected to consider multiple lines, when making break decisions. Otherwise equivalent to [auto](https://www.w3.org/TR/css-text-4/#valdef-text-wrap-style-auto),

> NOTE: The [auto](https://www.w3.org/TR/css-text-4/#valdef-text-wrap-style-auto) value will typically map to Web browsers’ speedy legacy line breaking, which has so far used first-fit/greedy algorithms that can often give sub-optimal results. UAs can experiment with better line breaking algorithms with this default value, but as optimal results often take more time, [pretty](https://www.w3.org/TR/css-text-4/#valdef-text-wrap-style-pretty) is offered as an opt-in to take more time for better results. The pretty value is intended for body text, where the last line is expected to be a bit shorter than the average line; the [balance](https://www.w3.org/TR/css-text-4/#valdef-text-wrap-style-balance) value is intended for titles and captions, where equal-length lines of text tend to be preferred; and the [stable](https://www.w3.org/TR/css-text-4/#valdef-text-wrap-style-stable) is intended for sections that are, or are likely become toggled as, editable.

### Do you have anything more you want to share?

I also noticed the W3C working draft documents an `auto` value, which MDN doesn't mention. I _would_ say `auto` should be added too; however, I'm noticing that Chrome's current implementation does not support `auto` as a valid value.

**New spec note** - This is a very much WIP / new spec. The W3C working draft was updated as recently as October 20, 2023. The current MDN page may very well be based on an older version of the working draft.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/text-wrap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/text-wrap/index.md
* Last commit: https://github.com/mdn/content/commit/6c78931afe30206bc980c15a7376b0469d4ab815
* Document last modified: 2023-09-13T18:51:11.000Z

</details>

**Comment by Christopher-Hayes** [comment]
I'm not used to reading W3C working drafts. What's a little confusing is the properties `text-wrap` is actually a combination of both `text-wrap-mode` and `text-wrap-style`. What I'm talking about above, and what the MDN doc mostly discusses is `text-wrap-style`. But, based on the W3C spec, `text-wrap` should also support the modes, `wrap` and `nowrap`.

Not sure if `text-wrap-style` is expected to become a separate property, but at the moment Chrome's implementation doesn't support it.

**Comment by wbamberg** [comment]
Yes, see also https://github.com/mdn/content/issues/29065#issuecomment-1718146724.

**Comment by pepelsbey** [comment]
Just like for #29065, we need to wait a bit until both spec and implementation settle before documenting it. The `text-wrap: balance` is coming in Firefox 121 (the second independent implementation) in December and we’re going to spend some time rewriting the docs to support the release.
