### ISSUE TITLE
Issue "Django Tutorial Part 10": test file structure

### ISSUE THREAD

**Issue by kuihlein** [mdn/content#30075]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing#test_structure_overview

### What specific section or headline is this issue about?

Test structure overview

### What information was incorrect, unhelpful, or incomplete?

I followed the tutorial and put all test files exactly where described. 

> ```bash
> catalog/
>   /tests/
>     __init__.py
>     test_models.py
>     test_forms.py
>     test_views.py
> ``` 
> Extract from the tutorial.

### What did you expect to see?

I expected to run the tests and get the result as descibed in the tutorial.

> ```bash
> $ python3 manage.py test
> 
> Creating test database for alias 'default'...
> setUpTestData: Run once to set up non-modified data for all class methods.
> setUp: Run once for every test method to setup clean data.
> Method: test_false_is_false.
> setUp: Run once for every test method to setup clean data.
> Method: test_false_is_true.
> setUp: Run once for every test method to setup clean data.
> Method: test_one_plus_one_equals_two.
> .
> ======================================================================
> FAIL: test_false_is_true (catalog.tests.tests_models.YourTestClass)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "D:\GitHub\django_tmp\library_w_t_2\locallibrary\catalog\tests\tests_models.py", line 22, in test_false_is_true
>     self.assertTrue(False)
> AssertionError: False is not true
> 
> ----------------------------------------------------------------------
> Ran 3 tests in 0.075s
> 
> FAILED (failures=1)
> Destroying test database for alias 'default'...
> ```
> Extract from the tutorial

But instead I got the following error. 

> ```bash
> $ python3 manage.py test
> Traceback (most recent call last):
>   File "/Users/USER/projects/research/mozilla-django-tutorial/locallibrary/manage.py", line 22, in <module>
>     main()
>   File "/Users/USER/projects/research/mozilla-django-tutorial/locallibrary/manage.py", line 18, in main
>     execute_from_command_line(sys.argv)
>   File "/opt/homebrew/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
>     utility.execute()
>   File "/opt/homebrew/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/opt/homebrew/lib/python3.11/site-packages/django/core/management/commands/test.py", line 24, in run_from_argv
>     super().run_from_argv(argv)
>   File "/opt/homebrew/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/opt/homebrew/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
>     output = self.handle(*args, **options)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/django/core/management/commands/test.py", line 68, in handle
>     failures = test_runner.run_tests(test_labels)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/django/test/runner.py", line 1048, in run_tests
>     suite = self.build_suite(test_labels, extra_tests)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/django/test/runner.py", line 898, in build_suite
>     tests = self.load_tests_for_label(label, discover_kwargs)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/django/test/runner.py", line 872, in load_tests_for_label
>     tests = self.test_loader.discover(start_dir=label, **kwargs)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 334, in discover
>     tests = list(self._find_tests(start_dir, pattern))
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 397, in _find_tests
>     yield from self._find_tests(full_path, pattern)
>   File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 389, in _find_tests
>     tests, should_recurse = self._find_test_path(full_path, pattern)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 441, in _find_test_path
>     raise ImportError(
> ImportError: 'tests' module incorrectly imported from '/Users/USER/mozilla-django-tutorial/locallibrary/catalog/tests'. Expected '/Users/USER/mozilla-django-tutorial/locallibrary/catalog'. Is this module globally installed?
> ```

I tried a few things an it worked for me, when I changed the filestructure to the following: 

```bash
catalog/
tests/
  __init__.py
  test_models.py
  test_forms.py
  test_views.py
locallibrary/
db.sqlite3
[...]
``` 

Now I get the following response and it seems to work. But unfortunately its a different structure to the one explained in the tutorial or shown in the ["solutions" github repository](https://github.com/mdn/django-locallibrary-tutorial).

```bash
$ python3 manage.py test
Found 3 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
setUpTestData: Run once to set up non-modified data for all class methods.
setUp: Run once for every test method to setup clean data.
Method: test_false_is_false.
.setUp: Run once for every test method to setup clean data.
Method: test_false_is_true.
FsetUp: Run once for every test method to setup clean data.
Method: test_one_plus_one_equals_two.
.
======================================================================
FAIL: test_false_is_true (tests.test_models.YourTestClass.test_false_is_true)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/USER/mozilla-django-tutorial/locallibrary/tests/test_models.py", line 20, in test_false_is_true
    self.assertTrue(False)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

### Do you have any supporting links, references, or citations?

- Django Version: 4.2.1
- Python Version: 3.11.6
- OS: macOS Ventura 13.6

### Do you have anything more you want to share?

I'm not sure if this is somehow my fault or a bug int the tutorial.

**Comment by hamishwillee** [comment]
Hi @kuihlein 

You have taken this code from the overview in section "### What does Django provide for testing?". That is intended to be learning material explaining what tests are available - it isn't expected to be runnable code and hasn't been tested as such. 

The actual code that you have to implement starts at the section "Test structure overview" . You can tell the stuff you have to implement because the instructions are explicit and say things like "Create a file structure as shown above".

If you get stuck, then you can check out the worked project here https://github.com/mdn/django-locallibrary-tutorial/tree/main/catalog/tests and see how your code differs.
