### ISSUE TITLE
The AbortSignal.any static method not documented

### ISSUE THREAD

**Issue by stof** [mdn/content#30095]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal

### What specific section or headline is this issue about?

Static methods

### What information was incorrect, unhelpful, or incomplete?

`AbortSignal` has a `any` static method allowing to combine several other signals. This method is not documented (except in the browser compatibility table because BCD has data for it, but it links to a non-existent page).

### What did you expect to see?

I would expect this method to be documented.

### Do you have any supporting links, references, or citations?

https://chromestatus.com/feature/5202879349522432

**Comment by caugner** [comment]
I can confirm that [the spec mentions](https://dom.spec.whatwg.org/#interface-AbortSignal) the static `any` method, and it is not yet documented on MDN.

**Comment by skyclouds2001** [comment]
the https://github.com/mdn/content/pull/27424 is already working
