### ISSUE TITLE
Pairing dns-prefetch and preconnect

### ISSUE THREAD

**Issue by jquinc30** [mdn/content#30096]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch

### What specific section or headline is this issue about?

#best_practices

### What information was incorrect, unhelpful, or incomplete?

`preconnect` will perform the dns lookup but also establishes a connection to a server where `dns-prefetch` will only do the first part.

The best practice encourage to use both:
> The logic behind pairing these hints is because support for dns-prefetch is better than support for preconnect.

### What did you expect to see?

As the support for `preconnect` seems to be pretty ok now and httpS is the standard (where the potential gain of `preconnect` is at the maximum), I think that pairing is no more useful.
I was expected to be encouraged to only use `preconnect`

### Do you have any supporting links, references, or citations?

https://caniuse.com/link-rel-dns-prefetch

https://caniuse.com/link-rel-preconnect

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/performance/dns-prefetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/performance/dns-prefetch/index.md
* Last commit: https://github.com/mdn/content/commit/e74627e6fd9ba19696b918c2bdddfff8aa160787
* Document last modified: 2023-07-04T10:01:14.000Z

</details>

**Comment by pepelsbey** [comment]
Hello! Good catch :) I agree that support is good enough for this hint to become obsolete. However, I would keep this note:

> If a page needs to make connections to many third-party domains…
