### ISSUE TITLE
browser compatibility

### ISSUE THREAD

**Issue by NonoSIBULE** [mdn/content#30099]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

### What specific section or headline is this issue about?

browser compatibility

### What information was incorrect, unhelpful, or incomplete?

i am unable to access chattool because none of the browsers are compatible

### What did you expect to see?

the site being able to log in

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

### Do you have anything more you want to share?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/user-select`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/user-select
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/user-select/index.md
* Last commit: https://github.com/mdn/content/commit/bb6092c4230b69c2eceae6910af68c73955cae1c
* Document last modified: 2023-05-10T14:53:07.000Z

</details>

**Comment by teoli2003** [comment]
Which chattool are ou trying to access?

**Comment by queengooborg** [comment]
Looks like this is spam, closing.
