### ISSUE TITLE
request.body is undefined in the example, not a ReadableStream

### ISSUE THREAD

**Issue by poef** [mdn/content#30104]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Request/body

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The example states:

```
const request = new Request("/myEndpoint", {
  method: "POST",
  body: "Hello world",
});

request.body; // ReadableStream
```

But if you run this in Firefox, `request.body` is instead `undefined`. The body is set in the request, just not accessible. If you run

```
let text = await request.text()
```

Then `text` is correctly set to 'Hello world'.

### What did you expect to see?

An explanation of cases where you can actually read `request.body`, and why it isn't available here would be helpful.

I've tried to see if it is a CORS issue, or perhaps tied to HTTP vs HTTPS, but the code behaves the same in all cases, and not as expected from the example.

### Do you have anything more you want to share?

![image](https://github.com/mdn/content/assets/1006453/989494b9-5f6c-4de4-870a-9686bbc600bc)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/request/body`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Request/body
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/request/body/index.md
* Last commit: https://github.com/mdn/content/commit/954612667bafd71241a93e8554e8f11afc474ff3
* Document last modified: 2023-04-07T19:50:09.000Z

</details>

**Comment by Josh-Cena** [comment]
Please see https://developer.mozilla.org/en-US/docs/Web/API/Request/body#browser_compatibility. It's not implemented in Firefox.
