### ISSUE TITLE
texSubImage3D has wrong values for format param

### ISSUE THREAD

**Issue by nkronlage** [mdn/content#30128]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/texSubImage3D

### What specific section or headline is this issue about?

format parameter

### What information was incorrect, unhelpful, or incomplete?

It lists a lot of invalid formats.

For example, lists gl.R8 but that is not valid, but g.RED is.

### What did you expect to see?

The values seen in the OpenGL documentation: https://registry.khronos.org/OpenGL-Refpages/gl4/html/glTexSubImage3D.xhtml

Specifically:

GL_RED, GL_RG, GL_RGB, GL_BGR, GL_RGBA, GL_DEPTH_COMPONENT, and GL_STENCIL_INDEX

### Do you have any supporting links, references, or citations?

https://registry.khronos.org/OpenGL-Refpages/gl4/html/glTexSubImage3D.xhtml

https://registry.khronos.org/webgl/specs/latest/2.0/#TEXTURE_TYPES_FORMATS_FROM_DOM_ELEMENTS_TABLE

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webgl2renderingcontext/texsubimage3d`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/texSubImage3D
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl2renderingcontext/texsubimage3d/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by caugner** [comment]
Note that the page is part of the WebGL documentation on MDN, not OpenGL.

It looks like the [linked WebGL 2.0 specification](https://registry.khronos.org/webgl/specs/latest/2.0/#3.7.6) does list those formats, so I would say the MDN documentation is correct.

But I defer to an export for WebGL to make a final assessment.

**Comment by nkronlage** [comment]
The table does not list R8 under the `format` column so it also shows the MDN page is incorrect.

I think texSubImage3D should do what texImage3D does for `format` param - just link to that table: https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/texImage3D

If you want to see the error when you pass R8 for format to texSubImage3D, you can paste the following sample in to the box at https://www.javascripture.com/WebGLRenderingContext#texSubImage2D and click run:

```
<canvas id='canvas' width='200' height='200'></canvas>
<script src='/webgl-debug.js'></script>
<script>
    var canvas = document.getElementById('canvas');
    var gl = canvas.getContext('webgl2');
    gl = WebGLDebugUtils.makeDebugContext(gl); // Remove this in production code


    // Make a texture to store the random data
    var texture = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_3D, texture);

    var textureWidth = 4;
    var textureHeight = 4;
    var textureDepth = 4;

    var data = new Uint8Array(4 * textureWidth * textureHeight * textureDepth);
    for (var i = 0; i < data.length; i++) {
      data[i] = Math.random() * 256;
    }
    // Load the data into the texture
    gl.texImage3D(gl.TEXTURE_3D, 0, gl.RGBA, textureWidth, textureHeight, textureDepth, 0, gl.RGBA, gl.UNSIGNED_BYTE, data);
    
    // Load a subset of the texture
    gl.texSubImage3D(gl.TEXTURE_3D, 0, 0, 0, 0, textureWidth, textureHeight, textureDepth, gl.R8, gl.UNSIGNED_BYTE, data);
 </script>
```

Note, this sample doesn't actually render anything so you'll only get an error when it's wrong, but won't see anything if it succeeded.

![image](https://github.com/mdn/content/assets/444248/35cff749-48ec-4bbf-822f-bbab363faec3)
