### ISSUE TITLE
The element matched by :only-of-type do not need a parent element.

### ISSUE THREAD

**Issue by lsc9** [mdn/content#30138]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:only-of-type

### What specific section or headline is this issue about?

The selected element does not have to have a parent element

### What information was incorrect, unhelpful, or incomplete?

`Note: As originally defined, the selected element had to have a parent. Beginning with Selectors Level 4, this is no longer required.`

### What did you expect to see?

remove this note.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_only-of-type`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:only-of-type
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_only-of-type/index.md
* Last commit: https://github.com/mdn/content/commit/5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e
* Document last modified: 2023-02-21T06:49:52.000Z

</details>

**Comment by pepelsbey** [comment]
Hey! Thank you for bringing this up :)

To be honest, I can’t even find this limitation mentioned [in the Level 3 spec](https://www.w3.org/TR/selectors-3/#only-of-type-pseudo). But even if it’s there, this is not relevant anymore, and this note is rather confusing: it looks like it’s trying to say something important but ends it with “nah, never mind”.

Feel free to send a PR removing this note, there’s no need for it anymore.

**Comment by lsc9** [comment]
> Hey! Thank you for bringing this up :)
> 
> To be honest, I can’t even find this limitation mentioned [in the Level 3 spec](https://www.w3.org/TR/selectors-3/#only-of-type-pseudo). But even if it’s there, this is not relevant anymore, and this note is rather confusing: it looks like it’s trying to say something important but ends it with “nah, never mind”.
> 
> Feel free to send a PR removing this note, there’s no need for it anymore.

If there is no such restriction, you need to delete the note. If there is, there is no need to delete it.

**Comment by pepelsbey** [comment]
> Do we need to test this on major browsers before removing the note?

```css
html:only-of-type {
  background-color: tomato;
}
```

This snippet makes `<html>` tomato in Firefox, Safari, and Chrome, although the root element doesn’t have parents. So I guess it’s supported in all major browsers.

**Comment by pepelsbey** [comment]
The only place I could find that mentioned parent for `:only-of-type` is the 12-year-old [version the Level 3 spec](https://www.w3.org/TR/2011/REC-css3-selectors-20110929/#only-of-type-pseudo).

> Represents an element that has a parent element and whose parent element has no other element children with the same expanded element name.

All later versions of the spec don’t mention this limitation. It should be safe to remove, considering everything.

**Comment by OnkarRuikar** [comment]
We need to update https://developer.mozilla.org/en-US/docs/Web/CSS/:only-child as well.
