### ISSUE TITLE
Issue with "SpeechSynthesisUtterance.rate": (demo is incomplete)

### ISSUE THREAD

**Issue by chrisribe** [mdn/content#3013]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/rate

#### What information was incorrect, unhelpful, or incomplete?
The html part of the demo is missing

#### What did you expect to see?
The full working demo

#### Did you test this? If so, how?
I recreated a working one here.
https://jsfiddle.net/chrisribe/2wt0qn5f/18/

I is based off of this github repo.
https://github.com/mdn/web-speech-api/tree/master/speak-easy-synthesis

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/speechsynthesisutterance/rate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/rate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/speechsynthesisutterance/rate/index.html
* Last commit: https://github.com/mdn/content/commit/11a98a59fca5f2e448d9e4b70e3c8a538c47b201
* Document last modified: 2021-02-19T19:45:18.000Z

</details>

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Add an explainer underneath the Examples section describing what the code is doing
* Add the HTML form from the example repo https://github.com/mdn/web-speech-api/blob/master/speak-easy-synthesis/index.html
* Add a link to both the example repo code https://github.com/mdn/web-speech-api/tree/master/speak-easy-synthesis and working example https://mdn.github.io/web-speech-api/speak-easy-synthesis/
