### ISSUE TITLE
Specifications and Browser Compatibility are red error boxes on Private Properties page

### ISSUE THREAD

**Issue by sidewayss** [mdn/content#30134]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties

### What specific section or headline is this issue about?

Specifications and Browser Compatibility

### What information was incorrect, unhelpful, or incomplete?

There is an error here, no actual content.

### What did you expect to see?

Actual content, as on other pages.  I know this used to be correct here, not sure when it broke.

**Comment by Josh-Cena** [comment]
My bad :)
