### ISSUE TITLE
[XHR] Replace XMLHttpRequest with fetch() in Web/API

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#30131]
Part of https://github.com/openwebdocs/project/issues/156.

This issue is to track replacement of XHR in code examples with `fetch()`.

I've just searched for `XMLHttpRequest` and got hits in the following subtrees of Web/API, excluding things which are obviously part of the XHR documentation itself:

- [x] [`AudioBufferSourceNode`](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode)
- [x] [`AudioProcessingEvent`](https://developer.mozilla.org/en-US/docs/Web/API/AudioProcessingEvent)
- [x] [`BaseAudioContext`](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext)
- [x] [`Beacon API`](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API) (false positive)
- [x] [`ConvolverNode`](https://developer.mozilla.org/en-US/docs/Web/API/ConvolverNode)
- [x] [`Document`](https://developer.mozilla.org/en-US/docs/Web/API/Document)
- [x] [`Document Object Model`](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model)
- [x] [`DOMParser`](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) (false positive)
- [x] [`EventTarget`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget)
- [x] [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File)
- [x] [`File and Directory Entries API`](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API)
- [x] [`File API`](https://developer.mozilla.org/en-US/docs/Web/API/File_API)
- [x] [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData)
- [x] [`FormDataEvent`](https://developer.mozilla.org/en-US/docs/Web/API/FormDataEvent)
- [x] [`History API`](https://developer.mozilla.org/en-US/docs/Web/API/History_API)
- [x] [`IndexedDB API`](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API)
- [x] [`MediaSource`](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource)
- [x] [`Navigator`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator) (false positive)
- [x] [`OfflineAudioContext`](https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext)
- [x] [`PerformanceResourceTiming`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming) (false positive)
- [x] [`ProgressEvent`](https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent) (false positive)
- [x] [`PushManager`](https://developer.mozilla.org/en-US/docs/Web/API/PushManager)
- [x] [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request)
- [x] [`Service Worker API`](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) (false positive)
- [x] [`ServiceWorkerRegistration`](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration)
- [x] [`SourceBuffer`](https://developer.mozilla.org/en-US/docs/Web/API/SourceBuffer)
- [x] [`Streams API`](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API)
- [x] [`Web Audio API`](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API)
- [x] [`Web Authentication API`](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API) (false positive)
- [x] [`Web Workers API`](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API)
- [x] [`WebRTC API`](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API)
- [x] [`Worker`](https://developer.mozilla.org/en-US/docs/Web/API/Worker)
- [x] [`XMLSerializer`](https://developer.mozilla.org/en-US/docs/Web/API/XMLSerializer)
- [x] [`XSLTProcessor`](https://developer.mozilla.org/en-US/docs/Web/API/XSLTProcessor)

I've deliberately not tried very hard to look for false positives at this point, so there are definitely going to be some in there.

**Comment by wbamberg** [comment]
I think the example at https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#handling_the_upload_process_for_a_file should stay XHR, because it wants to show upload progress, and AFAIK, XHR is still the best way to do this (though there is work to support it in `fetch()` (https://github.com/whatwg/fetch/issues/607).

**Comment by teoli2003** [comment]
Yes, it makes sense: Once browsers will  provide such a feature with fetch() we will update this entry; meanwhile we should keep it.

Maybe add an explicit sentence saying the Fetch API doesn't allow for this use case?

**Comment by wbamberg** [comment]
This is done! 🎉
