### ISSUE TITLE
Confusing demo

### ISSUE THREAD

**Issue by jimmonte** [mdn/content#30159]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/order

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

Maybe it is just me, but figuring out what this demo does was far more complicated than the order keyword itself. Why are there 4 selections to control one box?
![2023-11-09 10_38_31-order - CSS_ Cascading Style Sheets _ MDN](https://github.com/mdn/content/assets/33158815/610cbc7c-f922-4027-bcef-4c28332afc9a)

### What did you expect to see?

One input area controlling one box position would be clearer.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/order`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/order
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/order/index.md
* Last commit: https://github.com/mdn/content/commit/fab1f9cef824066b3ce6a5b25f6c6db539f5d042
* Document last modified: 2023-07-18T00:07:20.000Z

</details>

**Comment by Sriparno08** [comment]
I think it's the MDN way of showing a live demo.

If you take a look at the 'Try it' section in the [position](https://developer.mozilla.org/en-US/docs/Web/CSS/position) documentation, you will notice that all the input areas are controlling a single box (the second one), just like in the [order](https://developer.mozilla.org/en-US/docs/Web/CSS/order) documentation.

So, I guess it's alright.

**Comment by jimmonte** [comment]
As I wrote before, it may be just how I am viewing it, although the action of the `position` demo mentioned was completely clear immediately. With the `order` example, there are 4 input boxes on the left and 4 "regular" boxes in the display. Someone might get the idea that there is some correlation here. There also is no reason apparent from the demo why the third input box with order: 2; should go before the boxes with text "Order 2" written in it. Also text like "Order 2" does not directly tell someone that the item has "order: 2;"  applied to it. There are several mental translations that need to be made in this example and combined, I think that they make it a bit unclear.

**Comment by Sriparno08** [comment]
Good point 👍

Let's see what the maintainers have to say.

**Comment by jimmonte** [comment]
Some suggestions to make the demo clearer:
1. Switch from vertical (row) to horizontal (column) flex direction. This change will allow more boxes to be added to the demo without wrapping and more text to be written on one line.
2. Increase the number of boxes to a number substantially greater than the number of input boxes, say at least six.
3. Change text in the boxes like "Order 2" to something looking more like CSS, say style="order: 2;".
4. Have the box whose style is being set by the input on the left display that input as its text, again something like "style=...".
5. Avoid duplicate order values since the demo cannot provide information on what their relative positions should be without displaying the source code generated by the input and the rest of the demo code.

**Comment by jimmonte** [comment]
Some suggestions to make the demo clearer:
1. Switch from a flex direction of row to column to allow more items to be added without wrapping and to allow more text to be written on a single line.
2. Increase the number of fixed-order boxes to an amount substantially greater than the number of input areas, say at least six to make it clearer that the input areas are not related to these boxes.
3. Change the text in these boxes to something looking like CSS, such as "style='order: 2;'" instead of "Order 2"
4. Display the CSS of the box being ordered as its text, again something like "style= 'order: 2;'".
5. Avoid duplicate order values since there is no way to show which one should be ordered first without displaying the generated source code.

**Comment by OnkarRuikar** [comment]
> With the order example, there are 4 input boxes on the left and 4 "regular" boxes in the display. Someone might get the idea that there is some correlation here.

There are 5 boxes and one of them is saying "Order me" :smile:.
The 4 selectables on the left are 4 different values to be applied on the "Order me" element. They've been made editable so that readers can play with the values there itself.

> 1. Switch from a flex direction of row to column to allow more items to be added without wrapping and to allow more text to be written on a single line.
> 2. Increase the number of fixed-order boxes to an amount substantially greater than the number of input areas, say at least six to make it clearer that the input areas are not related to these boxes.
> 3. Change the text in these boxes to something looking like CSS, such as "style='order: 2;'" instead of "Order 2"
> 4. Display the CSS of the box being ordered as its text, again something like "style= 'order: 2;'".

:+1: Converting flex flow to column with box text `order: 2;` will be more helpful.
But more boxes will lead to scrollbars and ordering effect won't be easy to perceive. Simple instruction text before the demo would clear the confusions.

> 5. Avoid duplicate order values since there is no way to show which one should be ordered first without displaying the generated source code.

But it demos a key concept that if elements have same order then they honor document order among themselves. Here "Order me" is being placed before all `order:2` is because it is the first element mentioned in the source code. This certainly needs to be asserted in the document.
