### ISSUE TITLE
findByIdAndRemove depricated?

### ISSUE THREAD

**Issue by Shahad7** [mdn/content#30152]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Delete_author_form

### What specific section or headline is this issue about?

delete author post route

### What information was incorrect, unhelpful, or incomplete?

I believe the findByIdAndRemove function doesn't exist anymore. It was throwing an error and I couldn't find the function in the mongoosejs ofiicial docs. I was following the tutorial

### What did you expect to see?

a function that deletes the record ofc!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/delete_author_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Delete_author_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/delete_author_form/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much - this should be fixed by https://github.com/mdn/content/pull/30230

**Comment by Shahad7** [comment]
Hey, so should i close the issue now? This is the first time i am opening
an issue

**Comment by hamishwillee** [comment]
Hi @Shahad7 No need thanks. If you look at the issue I created it has `Fixes 30152` in the description. What that means is that as soon as the PR is merged this issue will automatically close.

We do it that way because sometimes a reviewer will reject a PR fix as "not good enough" - in which case this issue would remain open until it was actually fixed.

**Comment by Shahad7** [comment]
Oh okayy
