### ISSUE TITLE
pushState does NOT fire popstate

### ISSUE THREAD

**Issue by mtkopone** [mdn/content#30178]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/History/pushState

### What specific section or headline is this issue about?

History: pushState() method

### What information was incorrect, unhelpful, or incomplete?

The page says: _"Add a listener for the [popstate](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event) event in order to determine when the navigation has completed. The state parameter will be available in it."_

Yet the popState page (https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event) says: _Note that just calling history.pushState() or history.replaceState() won't trigger a popstate event. The popstate event will be triggered by doing a browser action such as a click on the back or forward button (or calling history.back() or history.forward() in JavaScript)._

_

### What did you expect to see?

I'd expect it to say e.g. _"You cannot listen for state changes using popstate, so maybe you should reconsider your entire approach."_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/history/pushstate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/History/pushState
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/history/pushstate/index.md
* Last commit: https://github.com/mdn/content/commit/ab8736c08a6664970fec04088182b8c5e29a570a
* Document last modified: 2023-09-27T04:57:54.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! I closed this yesterday in https://github.com/mdn/content/pull/30169, and the fix should be live on the site in the next few hours.

**Comment by mtkopone** [comment]
Thx!
