### ISSUE TITLE
img and code show different error messages

### ISSUE THREAD

**Issue by NahuelLu** [mdn/content#30182]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form

### What specific section or headline is this issue about?

The last img that shows error

### What information was incorrect, unhelpful, or incomplete?

The error message contained in the image is incorrect.
More above the article shows a code that the error message must be "Genre name must contain at least 3 characters"

### What did you expect to see?

"Genre name must contain at least 3 characters"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_genre_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_genre_form/index.md
* Last commit: https://github.com/mdn/content/commit/8d0cbeacdc1872f7e4d966177151585c58fb879e
* Document last modified: 2023-08-02T17:32:22.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you. THis will be fixed by #30226
