### ISSUE TITLE
Value `run-in` missing from display

### ISSUE THREAD

**Issue by 747** [mdn/content#30201]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/display

### What specific section or headline is this issue about?

Outside

### What information was incorrect, unhelpful, or incomplete?

Description about a value `run-in` is missing. Is it intentional? The value does not particularly seem deprecated or something in [the CSS spec](https://drafts.csswg.org/css-display-3/#valdef-display-run-in).

It looks inconsistent because the keyword does appear in [the description of `flow`](https://developer.mozilla.org/en-US/docs/Web/CSS/display#flow) and [the formal syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/display#formal_syntax) of the same page.

### What did you expect to see?

Some description about `run-in`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/display`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/display
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/display/index.md
* Last commit: https://github.com/mdn/content/commit/c77cfcd17e85db6c1b93160c70668f2ff6c2809c
* Document last modified: 2023-07-20T07:38:29.000Z

</details>

**Comment by OnkarRuikar** [comment]
From the [history](https://caniuse.com/run-in) browsers stopped supporting the `run-in` value. And the spec hasn't ironed out the feature in order for [browsers to start working on it](https://bugzilla.mozilla.org/show_bug.cgi?id=2056#c96).

As per a policy MDN doesn't document something which hasn't been implemented in any browser.

**Comment by 747** [comment]
> As per a policy MDN doesn't document something which hasn't been implemented in any browser.

@OnkarRuikar Thank you for your input. I have nothing to say with the policy, but the criterion you give does not seem right. I can easily find [something nobody has implemented](https://developer.mozilla.org/en-US/docs/Web/CSS/initial-letter-align) documented on MDN. What is the actual border of documentable and undocumentable?

**Comment by OnkarRuikar** [comment]
> I can easily find [something nobody has implemented](https://developer.mozilla.org/en-US/docs/Web/CSS/initial-letter-align) documented on MDN. 

That one was documented in Wiki era before MDN was moved to GitHub and Yari.

> What is the actual border of documentable and undocumentable?

As far as I know officially features are added/removed [near a browser release](https://github.com/mdn/content/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Firefox+120%22). For the definition of irrelevant feature [this document](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features) can be referred.

If one wants they can submit a PR. But by the time a feature goes live it changes most of the time so pre-documenting it adds to maintenance.

**Comment by 747** [comment]
@OnkarRuikar So, can I understand that `initial-letter-align` is an odd one and not mentioning `run-in` is correct here? If that is the case, is it better to remove `run-in` from the section "flow" too?

> If its outer display type is `inline` or `run-in`, and it is participating in a block or inline formatting context, then it generates an inline box. Otherwise it generates a block container box.

I find a term pointing nowhere pretty cryptic.

**Comment by bsmth** [comment]
Hi both, thanks for reporting and for checking the status. These are the only two pages mentioning it anywhere (prose, code, etc.):

* https://developer.mozilla.org/en-US/docs/Web/CSS/display-inside
* https://developer.mozilla.org/en-US/docs/Web/CSS/display

There's [guidelines for removal](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete#guidelines_for_removing_content) which it looks like `run-in` meets. The alternative is to add a warning, but from the caniuse page, browsers haven't supported it in almost 10 years, so it's safe to remove in my opinion.
