### ISSUE TITLE
`await` in document.ready or any other UI event

### ISSUE THREAD

**Issue by BSarmady** [mdn/content#30214]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

### What specific section or headline is this issue about?

Entire await, async and all examples

### What information was incorrect, unhelpful, or incomplete?

Every sample in this page just runs the async function on top level javascript, and none of them explains how to wait for UI of the page become ready.

### What did you expect to see?

Since this is `Web Docs`, I'm expecting to see at list one example of integration of results into a Javascript running in an HTML page.

Yes, I know you can create one more script tag at the end of the page and await function in there so the UI is rendered and available. but I find it really terrible solution specially when we have a `document.ready` event that you can bind the event even at top of the page.

I like to see at least one example showing how to do `await` in document.ready event or any other event in fact.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/await`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/await/index.md
* Last commit: https://github.com/mdn/content/commit/3c33463072905e81ac620dd9780313369029b498
* Document last modified: 2023-06-29T17:06:46.000Z

</details>

**Comment by Josh-Cena** [comment]
What is `document.ready`? Do you mean the jQuery `$(document).ready()`? Could you tell me what that means in plain JS—does it use `document.readyState`, `document.DOMContentLoaded`, or something else? What is your desired effect? You can explain with whatever code you feel is closest to being correct.

**Comment by BSarmady** [comment]
@Josh-Cena 
All of them actually. 

It was kind of hard to figure out without a document telling you that you can async all DOM events. I had to yolo it and it worked.

```javascript
$(async function () { ... });

onreadystatechange = async function(){ ... };

addEventListener("readystatechange", async function(e){ ... });

addEventListener("DOMContentLoaded", async function(e){ ... });

```
