### ISSUE TITLE
Discourages use of eval() but doesn’t suggest alternatives

### ISSUE THREAD

**Issue by RickBullotta** [mdn/content#30248]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval

### What specific section or headline is this issue about?

Use of eval()

### What information was incorrect, unhelpful, or incomplete?

The docs strongly discourage use of eval() and claim that there are better alternatives, but don’t provide any further information as to those alternatives.

### What did you expect to see?

Links or depf alternatives to eval()

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/eval`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/eval/index.md
* Last commit: https://github.com/mdn/content/commit/4c26e8a3fb50d06963b06017f51ce19364350564
* Document last modified: 2023-08-11T08:07:46.000Z

</details>

**Comment by Josh-Cena** [comment]
Please see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval! for alternatives. It's linked to from the top banner.
