### ISSUE TITLE
pipeThrough conflicting return value

### ISSUE THREAD

**Issue by Reububble** [mdn/content#30256]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/pipeThrough

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

The options parameter description specifies 3 optional properties, and each one says that the method returns a promise

### What did you expect to see?

This method returns a ReadableStream. Errors are set to handled.

### Do you have any supporting links, references, or citations?

https://streams.spec.whatwg.org/#rs-pipe-through

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/readablestream/pipethrough`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/pipeThrough
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/readablestream/pipethrough/index.md
* Last commit: https://github.com/mdn/content/commit/d41c5446d4ef257280fae9b78e2298ced8954a95
* Document last modified: 2023-05-09T20:58:09.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. The method returns a promise that fulfills to the `readablestream` end or rejects with an error. That said, I completely agree that the text in the options is incorrect where it is because it is not correct if read assuming the values are true or false.

This should be fixed by #30327

**Comment by Reububble** [comment]
Sorry, that's not quite right. The method does not return a `Promise<ReadableStream>`, it returns a `ReadableStream`. It's clear in the spec, but you can also just `new Blob(["hi"]).stream().pipeThrough(new TextDecoderStream())` and see the return type for yourself.

**Comment by hamishwillee** [comment]
@Reububble Thanks very much - that was a bit dumb. Can you check the new version. The spec actually doesn't say anything about errors from using pipeThrough so I think all we need is the options to remove mention of the promise.

If this is not right, can you please propose alternatives?

**Comment by Reububble** [comment]
I think this is right.
