### ISSUE TITLE
Color Wheel SVG has wrong color

### ISSUE THREAD

**Issue by jamienk** [mdn/content#30266]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/hue/color_wheel.svg

### What specific section or headline is this issue about?

Image embedded, e.g., in https://developer.mozilla.org/en-US/docs/Web/CSS/hue

### What information was incorrect, unhelpful, or incomplete?

The SVG has in incorrect line in its inline STYLE:

`<div xmlns="http://www.w3.org/1999/xhtml" style="background:conic-gradient(red,#ff0,#0f0,#0ff,#00f,#f0f,red);**background:conic-gradient(in hsl longer hue,red,red);**border-radius:50%;height:100%;width:100%" />`

`background:conic-gradient(red,#ff0,#0f0,#0ff,#00f,#f0f,red);` is correct, but the next bit of CSS `background:conic-gradient(in hsl longer hue,red,red);` takes priority and makes the color wheel be completely red

### What did you expect to see?

Expected to see color wheel, see red circle instead

**Comment by bsmth** [comment]
Thanks for raising @jamienk - the hue interpolation method in conic gradients isn't fully supported in Firefox yet. This looks as expected in Chrome, for instance. See https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/conic-gradient#browser_compatibility

Are you using Nightly? This change may be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1852513 

I think we can remove the `background:conic-gradient(in hsl longer hue,red,red);` style for the moment, what do you think?

cc @yarusome

**Comment by OnkarRuikar** [comment]
Even with Firefox the issue shouldn't arise:

![1](https://github.com/mdn/content/assets/87750369/21c2aab4-0971-48ef-85e3-d1aa198e2f8d)
The unsupported property value becomes invalid so the first value `conic-gradient(red,#ff0,#0f0,#0ff,#00f,#f0f,red)` gets used. I am confuse in which case it would show only red wheel?

We can fortify the implementation with `@supports`: https://github.com/mdn/content/pull/30275

**Comment by bsmth** [comment]
This is actually an Fx bug in hue interpolation when start and end angles are equal, see https://bugzilla.mozilla.org/show_bug.cgi?id=1864851
