### ISSUE TITLE
Replace Wikipedia reference with official site

### ISSUE THREAD

**Issue by clairestreb** [mdn/content#30279]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/HTTP_3

### What specific section or headline is this issue about?

referring to wikipedia

### What information was incorrect, unhelpful, or incomplete?

On the [HTTP/3](https://developer.mozilla.org/en-US/docs/Glossary/HTTP_3) web page, please replace:
**[HTTP/3](https://en.wikipedia.org/wiki/HTTP/3) on Wikipedia**
with something like:
**[HTTP/3 on IETF](https://httpwg.org/specs/rfc9114.html on the official IETF HTTP Working Group)**

### What did you expect to see?

An official reference.

### Do you have any supporting links, references, or citations?

Yes, I provided the official site to the HTTP protocol

### Do you have anything more you want to share?

As a skilled, professional, senior software engineer, I suggest you do not use Wikipedia as a reference since it downgrades your reputation in the software industry. Indeed, it is an unreliable source in many universities and journals, simply search the internet for wikipedia unreliable.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/http_3`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/HTTP_3
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/http_3/index.md
* Last commit: https://github.com/mdn/content/commit/ada5fa5ef15eadd44b549ecf906423b4a2092f34
* Document last modified: 2023-06-08T13:19:16.000Z

</details>

**Comment by hamishwillee** [comment]
MDN aims to provide a simple version of the specifications that is at aimed at web developers rather than browser developers. For that reason it is better to link to the more "human facing" docs on Wikipedia than the specification - even though it might not be canonical.

If MDN ever has a dedicated page for HTTP3 we'll use that instead.

Closing as "not planned"

**Comment by Josh-Cena** [comment]
> As a skilled, professional, senior software engineer, I suggest you do not use Wikipedia as a reference since it downgrades your reputation in the software industry. Indeed, it is an unreliable source in many universities and journals, simply search the internet for wikipedia unreliable.

To add on to this: we do not find Wikipedia unreliable, particularly in the tech field. Perhaps it is less reliable in the sciences, where it is easier to tweak reality and include personal beliefs, but in technology, truth is easily verifiable and quite saliant. I also don't think people go around spreading false information about HTTP3—there's little motivation to do so. Wikipedia is not good for quoting in an academic context, but it is usually a good digest of advanced materials in an educational context.
