### ISSUE TITLE
change .textContent of input to .value

### ISSUE THREAD

**Issue by roudlek** [mdn/content#30271]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction#adding_a_child_element

### What specific section or headline is this issue about?

adding_a_child_element

### What information was incorrect, unhelpful, or incomplete?

for input we use .value to target the text
Javascript code not working properly in that snppet !

### What did you expect to see?

```js
const story = document.body.querySelector(".story");

const setText = document.body.querySelector("#set-text");
setText.addEventListener("click", () => {
// this line
  story.value = "It was a dark and stormy night...";
});

const clearText = document.body.querySelector("#clear-text");
clearText.addEventListener("click", () => {
//and this one
  story.value = "";
});
```

### Do you have any supporting links, references, or citations?

https://www.w3schools.com/jsref/prop_text_value.asp

### Do you have anything more you want to share?

keep it up !

**Comment by pepelsbey** [comment]
Hey! Thank you for bringing this up :) You got the point here: yes, you’re supposed to use `.value` for setting the text of a form element. But in this case, it’s tricky: `<textarea>` is both an input and an element that can have some content inside:

```html
<textarea>content</textarea>
<textarea value="value"></textarea>  <!-- Not gonna work -->
```

Though you cannot set the value via attribute, it works via DOM. So it’s complicated :) But in this case, setting `textContent` for an element capable of having text content works just fine. That’s why [the demo](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction#result) works in all browsers.

I’m going to close this issue for now. But let me know if you have any other thoughts on improving this example. Thanks!
