### ISSUE TITLE
Issue with "pointer-events": Incorrect Pointer Events link 

### ISSUE THREAD

**Issue by hostcomm-steve** [mdn/content#3027]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

#### What information was incorrect, unhelpful, or incomplete?

"Pointer Events" link is incorrect.

#### Specific section or headline?

"Related Topics"

#### What did you expect to see?

Should probably be: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events

#### Did you test this? If so, how?

Click the link... page not found.
Search "Pointer Events" - link found (3rd result iirc).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/pointer-events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/pointer-events/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update it :+1:

**Comment by wbamberg** [comment]
Thanks for filing, @hostcomm-steve , and for volunteering to fix this @CreaTorAlexander !

That link is being added by the [notorious CSS sidebar macro](https://discourse.mozilla.org/t/css-sidebar-proposal/49500), which is finding it in mdn/data under the `groups` property: https://github.com/mdn/data/blob/02b809df8af32dcea260ea0964a6d6b431191562/css/properties.json#L7490-L7498.

Although I can see why you might think that, it's not supposed to go to https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events. It's supposed to go to a page describing the module (or specification) where this property is defined, like. say, https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model.

So what should it be? It looks as if the `pointer-events` property is [currently defined in the SVG specification](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events#specifications), which means it doesn't have a home in a CSS module. But it also looks like there is a desire to move it into the CSS Basic User Interface module (https://wiki.csswg.org/spec/css4-ui#pointer-events), which seems like a good idea. So perhaps changing the `groups` to "CSS Basic User Interface" might be a good fit.

(Having said that I'd like us to change the CSS sidebar system to be more sensible, which will make this whole problem go away. So perhaps we can just do nothing about this problem for now.)

**Comment by rachelandrew** [comment]
@wbamberg it is going into css-ui-4 the resolution is here https://github.com/w3c/csswg-drafts/issues/4438#issuecomment-550570928 

So yes, I think moving the group would be a good plan which should solve this particular problem at least. 

I'll go make a PR on the data repo to sort it.
