### ISSUE TITLE
Describe direct and indirect eval differences in each bullet point

### ISSUE THREAD

**Issue by DanKaplanSES** [mdn/content#30281]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval

### What specific section or headline is this issue about?

Direct and indirect eval

### What information was incorrect, unhelpful, or incomplete?

In this issue, I'm referring to the contents between these two lines of text (exclusive):

> Indirect eval can be seen as if the code is evaluated within a separate `<script>` tag. This means:
> ...
> ### Never use eval()!

The `...` is a bullet point list containing explanations and examples of the differences between the two eval modes.

### What did you expect to see?

It's difficult for me to parse some bullet points because:

1. The text (as opposed to the example code) sometimes explains one eval mode but not the other. On the other hand, sometimes it explains both:
   1. At first glance, it can appear like a bullet point only applies to one mode even though that's not the case.
   2. It can take more effort to read example code than an English sentence.
1. Some text is written in negative form—e.g., "**In**direct eval **would not** inherit the strictness of the surrounding context"—which, in my opinion, is harder to read than positive form: "Direct eval inherits the strictness of the surrounding context."
1. Some example code blocks contain examples of both modes, some contain only one mode. 
   1. This can obscure where a bullet point starts and where it ends.
   2. This makes it challenging to scan for differences between the two modes.
1. There is another section named `Using indirect eval()`, giving me a sense that some information is divided between both sections.
   1. Even if this isn't true, it gives me the impression that neither section is comprehensive.

### Do you have anything more you want to share?

Apologies if my wording offended anyone. My intent was to be concise, not rude. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/eval`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/eval/index.md
* Last commit: https://github.com/mdn/content/commit/4c26e8a3fb50d06963b06017f51ce19364350564
* Document last modified: 2023-08-11T08:07:46.000Z

</details>

**Comment by Josh-Cena** [comment]
@DanKaplanSES I'm not sure what exactly you'd like see changed.

> The text (as opposed to the example code) sometimes explains one eval mode but not the other. On the other hand, sometimes it explains both:

If we say "indirect eval works X way" it's implied that "direct eval works not X way". For example if we say "Direct eval may have access to additional contextual expressions." then it's fairly apparent that "Indirect eval does not have access to additional contextual expressions."

> Some text is written in negative form—e.g., "Indirect eval would not inherit the strictness of the surrounding context"

We try to make the subject of every sentence be "indirect eval", because these are all natural conclusions from the fact that "Indirect eval can be seen as if the code is evaluated within a separate `<script>` tag."

> Some example code blocks contain examples of both modes, some contain only one mode.

Well, the other case is just an error.

> There is another section named Using indirect eval()

That is a subsection of "Never use eval()!" and is supposed to offer one alternative to using `eval()`, which is... to use indirect eval.

**Comment by Josh-Cena** [comment]
Closing since I think the current structure is good enough.
