### ISSUE TITLE
Popover API conflates Esc dismiss with light dismiss

### ISSUE THREAD

**Issue by lukewarlow** [mdn/content#30309]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Popover_API/Using#auto_state_and_light_dismiss

### What specific section or headline is this issue about?

auto state, and "light dismiss"

### What information was incorrect, unhelpful, or incomplete?

> The popover can be "light dismissed" — this means that you can hide the popover by clicking outside it or pressing the Esc key.

### What did you expect to see?

This text conflates two separate concepts, light dismiss is the clicking outside to close behaviour, the escape key (and android back gesture) isn't part of this.

### Do you have any supporting links, references, or citations?

https://github.com/whatwg/html/issues/9373#issuecomment-1720157787

### Do you have anything more you want to share?

The HTML spec itself might be ambiguous here and if so needs improvements too, but it feels right to correct it in MDN.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/popover_api/using`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Popover_API/Using
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/popover_api/using/index.md
* Last commit: https://github.com/mdn/content/commit/bb6092c4230b69c2eceae6910af68c73955cae1c
* Document last modified: 2023-05-10T14:53:07.000Z

</details>

**Comment by pepelsbey** [comment]
Hey! Good catch :) Is it safe to say that this event categorization is certain enough in the spec to be documented the same way on MDN?

**Comment by lukewarlow** [comment]
https://html.spec.whatwg.org/multipage/interaction.html#close-requests-and-close-watchers

Should be the bit of the html spec that the escape key is handled by. I think the spec is probably correct enough to document. Idk if closewatcher itself is documented in MDN yet. But even if it's just separated from click outside for now I think that's enough.

**Comment by pepelsbey** [comment]
The CloseWatcher is not currently documented on MDN, but I think it doesn’t stop us from fixing this.

Feel free to suggest a PR!

**Comment by hamishwillee** [comment]
Fixed by #30890 - thanks @BartoszKlonowski !
