### ISSUE TITLE
Issue with "A re-introduction to JavaScript (JS tutorial)": world's most misunderstood programming language link

### ISSUE THREAD

**Issue by laurabartha** [mdn/content#3030]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript

#### What information was incorrect, unhelpful, or incomplete?

The page linked to regarding javascript being misunderstood(http://crockford.com/javascript/javascript.html) has a section blaming this on "amateur" developers. In a resource geared towards introducing people to javascript, this messaging is counterproductive. No one wants to join a community where the established members hate the new members for being new.

#### Specific section or headline?
 Very first paragraph under the title.

#### What did you expect to see?
As this is a content issue, I'd just like to see this link removed. Perhaps a less novice-blaming one could be found if citation standards need to be met. Maybe it's also an opportunity to mention a rift between academia and industry, seeing how prevalent javascript is in industry. There's even a reddit thread referencing the link and how outdated it is. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/a_re-introduction_to_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/a_re-introduction_to_javascript/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by chrisdavidmills** [comment]
@laurabartha I could not agree with this more. I've created https://github.com/mdn/content/commit/7e5c6b09faade6344e8df0428db9cadeced523b7 to remove it. Thanks for reporting this.
