### ISSUE TITLE
[JS] Implement the Promise.withResolvers proposal

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#30334]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1845586

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
@Josh-Cena How's this coming along? Do you need any help/support  - e.g. for BCD, release note, whatever?

**Comment by Josh-Cena** [comment]
BCD data is there. Sorry, maybe the assignment is confusing—I really only meant to help with docs and BCD (although data is taken care of by Florian this time). The only thing remaining is release notes.

**Comment by hamishwillee** [comment]
Thanks @Josh-Cena . That's cool, but no real way to tell this from the issue. If you get assigned one again, can you dual assign me as a helper for the boring bits?

**Comment by hamishwillee** [comment]
@Josh-Cena Should we mention this in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises ? 

I was thinking a short section before https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#creating_a_promise_around_an_old_callback_api ?

**Comment by hamishwillee** [comment]
> Ah yes, of course 😄 I only refrained from doing that in the first place because I'm not sure if I should get ahead of myself and assume it's always you handling JS stuff.

There I was assuming you'd do all the JS stuff :-). As long as we know who's responsible for what then no probs. I'd actually prefer you do it - that way it will be right. I use my own status post to track what has been done https://github.com/mdn/content/issues/30334#issuecomment-1846429147

**Comment by Josh-Cena** [comment]
> Should we mention this in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises ?
> 
> I was thinking a short section before https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#creating_a_promise_around_an_old_callback_api ?

My stance is no. This is an advanced feature that most users won't use (and actually should be discouraged from using, IMO, but this API is new and industry practices haven't standardized). The guide article mostly takes about _using_ promises, not _creating_ promises, so that brief mention of the `Promise` constructor should suffice.

**Comment by Rumyra** [comment]
Thanks both for your work on this!
