### ISSUE TITLE
[Page Not Found] - JavaScript technologies overview

### ISSUE THREAD

**Issue by JejTr** [mdn/content#30345]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/JavaScript_technologies_overview

### What specific section or headline is this issue about?

Standardization process

### What information was incorrect, unhelpful, or incomplete?

> The current committee-approved snapshot of ECMA-262 can be found in [PDF form](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-262.pdf)

Page Not Found.  

### What did you expect to see?

ECMA's 262 pdf or the exclusion of the link as the html version is preserved.

### Do you have any supporting links, references, or citations?

**Broken Link: https://ecma-international.org/publications/files/ECMA-ST/ECMA-262.pdf**

_Refernce Page: https://ecma-international.org/publications-and-standards/standards/ecma-262/
Pdf Printed Version Link: https://ecma-international.org/wp-content/uploads/ECMA-262_14th_edition_june_2023.pdf_

### Do you have anything more you want to share?

no coment

**Comment by bsmth** [comment]
Thanks a lot for raising this one. I think we can mention in prose that it's available as PDF / HTML and link to https://ecma-international.org/publications-and-standards/standards/ecma-262/ instead.
