### ISSUE TITLE
Range: should mention Accept-Ranges

### ISSUE THREAD

**Issue by 3052** [mdn/content#30358]
this page:

https://developer.mozilla.org/docs/Web/HTTP/Headers/Range

makes no mention of the Accept-Ranges header:

https://developer.mozilla.org/docs/Web/HTTP/Headers/Accept-Ranges

which if the server is not sending that, likely means it does not accept range requests. so I think its important that the Range page note that detail.

**Comment by bsmth** [comment]
Thanks for raising this! I had a look at [the RFC](https://www.rfc-editor.org/rfc/rfc9110#section-14.3-6) and if the server doesn't accept range requests, it may return `Accept-Ranges: none`, but this is not foolproof:

>A client MAY generate range requests regardless of having received an Accept-Ranges field. The information only provides advice for the sake of improving performance and reducing unnecessary network transfers. Conversely, a client MUST NOT assume that receiving an Accept-Ranges field means that future range requests will return partial responses. The content might change, the server might only support range requests at certain times or under certain conditions, or a different intermediary might process the next request. A server that does not support any kind of range request for the target resource MAY send
>
>     Accept-Ranges: none
>
>to advise the client not to attempt a range request on the same request path. The range unit "none" is reserved for this purpose.


It's worth mentioning in the article, though. I'll assign myself on this one.
