### ISSUE TITLE
Information missing in HTTP TRACE method documentation

### ISSUE THREAD

**Issue by joaoportela** [mdn/content#30367]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/TRACE

### What specific section or headline is this issue about?

First section

### What information was incorrect, unhelpful, or incomplete?

In the second paragraph we can read: "excluding some fields described below". But there is no other paragraph, nothing bellow describing those fields.

### What did you expect to see?

An inline explanation of which fields are excluded or an actual paragraph bellow with that information.

If I understood correctly, the excluded headers are headers that might contain sensitive data, like credentials or cookies or proxy authentication.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/methods/trace`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/TRACE
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/methods/trace/index.md
* Last commit: https://github.com/mdn/content/commit/0880a90f3811475d78bc4b2c344eb4146f25f66c
* Document last modified: 2023-04-10T19:47:15.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. This should be fixed by https://github.com/mdn/content/pull/30385
