### ISSUE TITLE
Raw template literals could use better explanation: latex is confusing and regexps unmentioned

### ISSUE THREAD

**Issue by johnhawkinson** [mdn/content#30389]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

### What specific section or headline is this issue about?

Raw strings

### What information was incorrect, unhelpful, or incomplete?

Raw strings are a confusing subtopic of template literals. They have some value, but the MDN article doesn't do a good job of explaining them or giving useful examples. The `latex` example presented is not given sufficient context to be useful, and there is no example using regular expressions, where (it seems to me) raw strings can give some real value.

I'd be happy to submit a pull request with the text following the `<hr>` tag below for regular expressions.
I am less sure what's appropriate for the `latex` example.

#### Regular Expressions

With respect to regular expressions, raw strings allow you to avoid double-escaping backslashes (just as the `/foobar/` regexp literal does) at the same time as allowing a delimiter that is not `/` (as is available in many other languages). 
For instance, an example like this might be helpful:

<hr>

Combining a `String.raw` template literal with the `new RegExp()` constructor allows you to create regular expressions with an alternative delimiter other than a forward slash (`/`) without requiring double-escaping (`\\`) of regular expression escape sequences. This is especially valuable in strings that contain a lot of slashes, such as file paths or URLs.

```js
// A String.raw template allows a fairly readable regular expression matching a URL:
const mdnJS_srtl = new RegExp(String.raw`https://developer\.mozilla\.org/en-US/docs/Web/JavaScript/Reference/`);

// The same thing with a regexp literal looks like this, with \/ for each forward slash:
const mdnJS_rl = /https:\/\/developer\.mozilla\.org\/en-US\/docs\/Web\/JavaScript\/Reference\//;

// And the same thing written with the RegExp constructor and a traditional string literal, with \\. for each period:
const mdnJS_str = new RegExp('https://developer\\.mozilla\\.org/en-US/docs/Web/JavaScript/Reference/');

console.log(mdnJS_srtl.source == mdnJS_rl.source)
// true
console.log(mdnJS_srtl.source == mdnJS_str.source)
// true
console.log(mdnJS_srtl.source)
// https:\/\/developer\.mozilla\.org\/en-US\/docs\/Web\/JavaScript\/Reference\/
```

#### The `latex` tag

The page sketches an example of a `latex` tag template literal, but doesn't explain why it might be useful:

```js
function latex(str) {
  return { cooked: str[0], raw: str.raw[0] };
}

latex`\unicode`;

// { cooked: undefined, raw: "\\unicode" }
```

It appears that this would need to be used in some context where code expected an object with a raw attribute, and mostly ignored presence of the cooked attribute. I don't know quite what that context would be. I suppose it could be something like:

```js
beginObject= latex`\documentclass{article}`;
// {  "cooked": "documentclass{article}",  "raw": "\\documentclass{article}"
console.log(`It's normal in LaTeX to begin your document with ${beginObject.raw}`);
```

But this feels convoluted and confusing. I don't understand why it's the example.
A more straightforward way to write this would be either:

```js
beginString = String.raw`\documentclass{article}`;
console.log(`It's normal in LaTeX to begin your document with ${beginString}`);
```

Or if the goal is to demonstrate the value of tagged templates, then a simpler template:

```js
function LaTeX(str) { 
  return str.raw[0];
}

beginString = LaTeX`\documentclass{article}`;
console.log(`It's normal in LaTeX to begin your document with ${beginString}`);
```

Because I'm not sure what the current example is trying to demonstrate, I'm not sure how to improve the example to show it better. Help?

### Do you have any supporting links, references, or citations?

I've found very few examples of raw strings in template literals for regular expressions.
I suspect they would be a more used pattern if they were better understood and explained.

There are some decent examples as https://exploringjs.com/impatient-js/ch_template-literals.html#raw-string-literals although it doesn't explain the outer delimiter advantage.

One not-very-helpful-place is this optional ESlint rule, https://eslint.org/docs/latest/rules/prefer-regex-literals, which discourages the use of the `new RegExp()` constructor in place of regexp literals for static content.
So that rule also disallows

```js
new RegExp(String.raw`^\d\.$`);
```

which is an example of this. But this ESlint rule is not enabled by default (and probably should not be, because of the readability value of raw strings combined with RegExp literals).

### Do you have anything more you want to share?

I had trouble finding the history of who wrote the text about the `latex` template and whether there was originally more to the example.

The text is essentially unchanged since cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630 when it was imported from the prior MDN system, which I guess was a wiki stored in SQL? I'm not sure where to find that history, if it even matters.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/template_literals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/template_literals/index.md
* Last commit: https://github.com/mdn/content/commit/cbfc561e5e577975a51acceadbd7d2fec9b8e45e
* Document last modified: 2023-11-14T13:08:57.000Z

</details>

**Comment by Josh-Cena** [comment]
Feel free to add an example with regexes. The LaTeX example is directly taken from the original proposal: https://tc39.es/proposal-template-literal-revision/ I think the intention is a LaTeX renderer implemented in JS, which does not seem like a totally obscure use case. Identity tags such as `` html`<foo>` `` are also widely used by formatters to provide embedded code formatting, syntax highlighting, etc.

**Comment by johnhawkinson** [comment]
@Josh-Cena:
> Feel free to add an example with regexes.

Thanks. The text I offered following the horizontal rule was written in the style of the page and intended to be such an example. Sounds like there's not much feedback on that, perhaps it's fine as-is.

> The LaTeX example is directly taken from the original proposal: https://tc39.es/proposal-template-literal-revision/ I think the intention is a LaTeX renderer implemented in JS, which does not seem like a totally obscure use case.

Curiously, the example there doesn't actually define the function. It could just as easily be the simpler

```js
function LaTeX(str) { 
  return str.raw[0];
}

beginString = LaTeX`\documentclass{article}`;
console.log(`It's normal in LaTeX to begin your document with ${beginString}`);
```

that I offered. The point I was trying to make was that our examples of raw template strings should be as complex as they need to be, but no more complex. And not only is the `latex()` example unnecessarily complex, by returning an object with `raw` and `cooked` attributes (where the `raw` attribute is potentially confusing since the first  parameter to the template tag function also has a `raw` attribute, although they are different things), it is also incomplete, since it doesn't show you what to do with such an Object.

> Identity tags such as `` html`<foo>` `` are also widely used by formatters to provide embedded code formatting, syntax highlighting, etc.

Yes, I didn't mean to imply anything by omission of anything about that section of the page. Although I am…not sure that example is as clear as it could be. I do find it a little confusing, but I haven't sat down and stared at it.


> The key idea we want to convey is that it's not solely useful for `String.raw` to get the raw string content; you can also use it to directly embed arbitrary text that may contain escape sequences. For example, `` buildRegExp`https://${foo}\.mozilla\.org` `` would be a far better example, where `buildRegExp` will automatically regex-escape the embedded expression. Does that make sense?

(I assume you mean "raw strings are are useful with more than `String.raw`")

I think this is an important question about which there is some dispute!

Is it clearer to write:

```js
const foo = 'developer';
const buildRegExp = (strings, ...values) => new RegExp(String.raw({ raw: strings }, ...values)); 
const re1 = buildRegExp`https://${foo}\.mozilla\.org`;
```

Or to write:

```js
const foo = 'developer';
const re2 = new RegExp(String.raw`https://${foo}\.mozilla\.org`);
```

I tend to think the second, `re2`, is clearer, because it doesn't require the reader to understand how template tag functions work or their properties, but it does require knowledge of `String.raw` (although if you don't understand `String.raw` you can still get the gist).

The former, `re1`, is arguably more elegant, and makes use of the templating feature.

(It is also buggy -- it returns `https:\/\/developer.mozilla.org` instead of `https:\/\/developer\.mozilla\.org`. Oops? I'm not sure why…maybe that shows my lack of understanding here...)

But the examples we give on the page shouldn't show off complexity for complexity's sake, they should use it to accomplish real goals and encourage good coding.

**Comment by Josh-Cena** [comment]
> perhaps it's fine as-is.

Yes, looks good at a glance. We can talk about the exact change to make after you submit a PR.

> since it doesn't show you what to do with such an Object.

The proposal already says it's for "a LaTeX processor". For example, it could be rendering LaTeX source to an HTML tree. It doesn't have to return the object you mentioned, and the tag you hypothesized does look somewhat unuseful.

> (I assume you mean "raw strings are useful with more than `String.raw`")

Yes, thank you, my language skills are failing me 😄

I should give you more information about `buildRegExp`:

```js
const escapeRegExp = (s) => s.replace(/[\^$\\.*+?()[\]{}|]/gu, "\\$&");
const buildRegExp = (strings, ...values) => new RegExp(String.raw({ raw: strings }, ...values.map(escapeRegExp)));
const prefix = "blog.developer";
const pattern = buildRegExp`https://${prefix}\.mozilla\.org`;

console.log(pattern.test("https://blogxdeveloper.mozilla.org")); // false
```

It automatically escapes the embedded expression, so that you can never have regex injection.

**Comment by johnhawkinson** [comment]
(Submitted a PR for the regexp part.)

> > since it doesn't show you what to do with such an Object.
> 
> The proposal already says it's for "a LaTeX processor". For example, it could be rendering LaTeX source to an HTML tree. It doesn't have to return the object you mentioned, and the tag you hypothesized does look somewhat unuseful.

Just to be clear, my comments were not about the 2016 draft proposal you cited (which does indeed discuss a "LaTeX processor") but rather were about the current MDN page, which uses it as an example after referencing "embedding of languages."

Also, earlier you said:

> I think the intention is a LaTeX renderer implemented in JS, which does not seem like a totally obscure use case.

I don't think I should have let that go by. A LaTeX renderer in JavaScript is absolutely an obscure use case! Although it may be the case that such a renderer might be written, it would be extremely difficult! LaTeX is super-complicated and is its own language (arguably maybe three of them? TeX, LaTeX, web/tangle/weave; what about metafont?). Now, it's much easier to imagine JS code that processes LaTeX without rendering it (e.g. a code formatter) or that handles a narrow small domain of it (equation/math formatting? Not that that is in any way "small" even if it's narrow). Or we could accept we have very different definitions of "obscure" :) .

> I should give you more information about `buildRegExp`

Gosh. That example seems sufficiently advanced to make me even more concerned about putting it on this MDN page. I think it would require a lot of explanation to be useful. Given that we have a

It uses two tagged template literals, nested. Like, it's cool and all, but I'm not sure it's the best example. I'm not sure what we're trying to show, but it seems like we need to show the more basic building blocks (at a minimum) before putting them together in a fashion like this.

Perhaps more significantly, it appears to suffer from the same bug I identified earlier in my own off-the-cuff example, that the rawness of the later escaped dots is lost and they turn into regular dots:

```js
console.log(pattern.test("https://blog.developerXmozilla.org"));
// true
```

Now, of course, the fact that the example we're discussing here is buggy is not in of itself evidence that it is too complicated an example for the MDN page, but it is a hint about that…

**Comment by Josh-Cena** [comment]
> A LaTeX renderer in JavaScript is absolutely an obscure use case!

Okay, a "not so obscure use case if you have to reach out for the `raw` property without using `String.raw`"—is that better? 😄

The `raw` property is in the first place a somewhat advanced feature that most people won't care about. It's like `Reflect`/`Proxy`/`WeakMap` etc.—they are most useful as implementation details of higher-level features. In the case of `raw`, most people would just be interested to use the `String.raw` function.

> That example seems sufficiently advanced to make me even more concerned about putting it on this MDN page.

We have examples that are on par with and much deeper in complexity than this example. I wouldn't sweat.

> Given that we have a _See Also_ link to [ES6 in Depth: Template strings](https://hacks.mozilla.org/2015/05/es6-in-depth-template-strings-2/), it seems like the kind of thing that could be referenced but not actually included.

Very well; I wouldn't call that article as being very in depth, but sure it frees us from the burden of showing real-world tag functions.

> `buildRegExp` uses two tagged template literals, nested.

If you mean `String.raw`, we already explained right below that it's only a trick to build an "identity" tag. We can also get away with this:

```js
const buildRegExp = (strings, ...values) => new RegExp(
  values.reduce(
    (acc, cur, i) => acc + escapeRegExp(cur) + strings.raw[i + 1],
    strings[0],
  ),
);
```

> Perhaps more significantly, it appears to suffer from the same bug I identified earlier in my own off-the-cuff example, that the rawness of the later escaped dots is lost and they turn into regular dots:

Great spot, my bad. Changing it to

```js
const buildRegExp = (strings, ...values) => new RegExp(String.raw(strings, ...values.map(escapeRegExp)));
```

would fix it. The example with `reduce` above is adjusted accordingly. And the bug is much more apparent in that form—`strings[i + 1]` may be undefined, only `strings.raw[i + 1]` is always a string.

Thinking more about it, I think it's not necessary to mention regexes altogether (although it would still be a great use case for the `String.raw` page, as your PR has already added). Instead, we could simply state that "in order for the `String.raw` tag to be able to preserve all kinds of raw strings, we must allow arbitrary escape sequences, otherwise there are valid raw strings that cannot be represented by the `String.raw` tag", and then show a simple regex and LaTeX as some examples. Does that make sense?

**Comment by Josh-Cena** [comment]
I believe we've addressed all concerns in https://github.com/mdn/content/pull/30404. Please let me know if there's anything else confusing about raw strings.
