### ISSUE TITLE
CSS/@media/resolution - add dppx examples

### ISSUE THREAD

**Issue by scheinercc** [mdn/content#30393]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution

### What information was incorrect, unhelpful, or incomplete?

Looking at [CSS/@media/resolution](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution)  I was searching for a device pixel density example.

only after finding [CSS/@media/-webkit-device-pixel-ratio](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-device-pixel-ratio) I found again what I was looking for.

### What did you expect to see?

Additionally to the DPI examples, it might be helpful to have some DPPX examples, like the ones here:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-device-pixel-ratio#implementation

### Do you have any supporting links, references, or citations?

see above

### Do you have anything more you want to share?

Happy to add something, if someone else thinks this is a worth while change.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@media/resolution`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@media/resolution/index.md
* Last commit: https://github.com/mdn/content/commit/0fd3414a0e35e6e30a2cd34977de607a23000bef
* Document last modified: 2023-03-22T10:04:06.000Z

</details>

**Comment by bsmth** [comment]
Thanks for the suggestion. I think it's a nice addition to show the other possible units:

* https://drafts.csswg.org/css-values-4/#resolution-value
* https://developer.mozilla.org/en-US/docs/Web/CSS/resolution#syntax

```css
@media (resolution: 2dppx) {
  ...
}

@media (resolution: 120dpcm) {
 ...
}

@media (resolution: 1x) {
  ...
}
```

Do you want to open a pull request for this?
