### ISSUE TITLE
I was wondering. Do you think it is a fault that  the run-result and corresponding resource code not match.

### ISSUE THREAD

**Issue by Zhengchen2029** [mdn/content#30395]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr

### What specific section or headline is this issue about?

match between code and result

### What information was incorrect, unhelpful, or incomplete?

![image](https://github.com/mdn/content/assets/88416387/33b67849-8e1c-4ffd-92c6-66e74ec0b484)

### What did you expect to see?

no attibute of title

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/abbr`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/abbr/index.md
* Last commit: https://github.com/mdn/content/commit/a4f2bbc328279ca53e558cb29117ad85e933cb3d
* Document last modified: 2023-04-29T04:16:31.000Z

</details>

**Comment by Josh-Cena** [comment]
This title is the title of the entire iframe, not the title of the abbreviation. You can hover anywhere within the window and the title will appear.

**Comment by Zhengchen2029** [comment]
原来如此
3q,
