### ISSUE TITLE
justify-content stretch value is difficult to understand

### ISSUE THREAD

**Issue by gpoole** [mdn/content#30415]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#values

### What information was incorrect, unhelpful, or incomplete?

The explanation for the `stretch` value for `justify-content` has a note included which says:

> Note: While stretch is supported by flexible boxes (flexbox), when applied on a flexbox, as stretching is controlled by [flex](https://developer.mozilla.org/en-US/docs/Web/CSS/flex), stretch behaves as start.

### What did you expect to see?

I think the note is worded in a confusing way and the underlying concept is somewhat confusing and needs to be elaborated. From reading the spec, it sounds like `stretch` has no effect when used with flexbox, since the sizing for children is controlled entirely by their `flex` property. Assuming then it must exist only for being used with other systems like `grid` and it being valid syntax is just a quirk of them sharing the `justify-content` property? If so, perhaps it would be clearer to say:

> Note: `stretch` has no effect on the sizing of children of flexboxes, since their stretching behaviour is controlled only by [flex](https://developer.mozilla.org/en-US/docs/Web/CSS/flex). When used on a flexbox, `stretch` has exactly the same meaning as `flex-start`. `stretch` is only useful for controlling the sizing of children of grids.

### Do you have any supporting links, references, or citations?

> The [justify-content](https://drafts.csswg.org/css-align-3/#propdef-justify-content) property applies along the [main axis](https://drafts.csswg.org/css-flexbox-1/#main-axis), but since stretching in the main axis is controlled by [flex](https://drafts.csswg.org/css-flexbox-1/#propdef-flex), [stretch](https://drafts.csswg.org/css-align-3/#valdef-align-content-stretch) behaves as [flex-start](https://drafts.csswg.org/css-align-3/#valdef-self-position-flex-start).

From https://drafts.csswg.org/css-align-3/#distribution-flex

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/justify-content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/justify-content/index.md
* Last commit: https://github.com/mdn/content/commit/5e7d1f9ae2cce0cb3f7693dfb8dc6e8d375b2231
* Document last modified: 2023-07-18T00:16:24.000Z

</details>

**Comment by OnkarRuikar** [comment]
> Assuming then it must exist only for being used with other systems like grid and it being valid syntax is just a quirk of them sharing the `justify-content` property?

It can be said other way round. `justify-content` can have `stretch` value and for flex layout it works as `flex-start`.

> **Note:** stretch has no effect on the sizing of children of flexboxes

Not true. For `flex: 1 0 auto` it works as `start`.
