### ISSUE TITLE
Inconsistent syntax in repeated code snippets

### ISSUE THREAD

**Issue by columk1** [mdn/content#30443]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_book_form

### What specific section or headline is this issue about?

Controller—post route

### What information was incorrect, unhelpful, or incomplete?

The section begins by showing the full router function. Then we see sections from this function repeated in smaller snippets, accompanied by explanations.

The following syntax is used for one of the repetitions which doesn't match the syntax used in the complete function.
```javascript
    if (!Array.isArray(req.body.genre)) {
      req.body.genre =
        typeof req.body.genre === "undefined" ? [] : [req.body.genre];
    }
```

This is inconsistent with the rest of the tutorial. Except for this case the smaller explainer snippets always match the code from the larger initial snippets. One of these syntax choices should be settled on. 

I was going to make a PR to bring the one rogue snippet in line but I'd like advice since there is another option to update the original snippet to the ternary version. The Update Book form page and the example project would also have to be updated since they use the same code.

### What did you expect to see?

I expected the smaller explainer snippet to match the initial snippet containing the complete function: 
```javascript
    if (!(req.body.genre instanceof Array)) {
      if (typeof req.body.genre === "undefined") req.body.genre = [];
      else req.body.genre = new Array(req.body.genre);
    }
```
This is the code that is used elsewhere in the tutorial, and in the example application.

### Example file
The syntax in the provided example/demo also uses `instanceof`:
https://github.com/mdn/express-locallibrary-tutorial/blob/main/controllers/bookController.js

### Update Book form
Likewise the syntax in the Update Book form page uses `instanceof`:
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Update_Book_form

**Comment by Josh-Cena** [comment]
The former is a much clearer and more robust way. Accepting PRs to make everything use that style.
