### ISSUE TITLE
PWA is now supported by safari on desktop

### ISSUE THREAD

**Issue by JOJOforshaun** [mdn/content#30463]
### MDN URL

https://developer.mozilla.org/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable

### What specific section or headline is this issue about?

zh-CN: https://developer.mozilla.org/zh-CN/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#%E6%B5%8F%E8%A7%88%E5%99%A8%E6%94%AF%E6%8C%81
en-US: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#browser_support

### What information was incorrect, unhelpful, or incomplete?

Safari on macOS Sonoma may introduce the PWA support. The following content may be out-of-date:

```md
On desktop:

- Firefox and Safari do not support installing PWAs on any desktop operating systems.
```

### What did you expect to see?

Update this section with the [BCD table](https://developer.mozilla.org/en-US/docs/Web/Manifest#browser_compatibility).

### Do you have any supporting links, references, or citations?

https://www.apple.com.cn/macos/sonoma/

### Do you have anything more you want to share?

<img width="1062" alt="1700704934037" src="https://github.com/mdn/translated-content/assets/63553362/807a63cc-6524-428f-b8c8-adbde0e2ab5d">

**Comment by pepelsbey** [comment]
Hey! Good catch :) This note is definitely outdated. Safari supports adding **any** website to the dock [since version 17](https://developer.apple.com/documentation/safari-release-notes/safari-17_1-release-notes#Web-Apps), and only on macOS Sonoma, I believe. [Here’s the user guide](https://support.apple.com/en-us/104996). As for developers, some things could be customized via web manifest. I couldn’t find any documentation apart from [this 15-minute video](https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes):

- You can hide the browser toolbar using `"display": "standalone"`
- You can scope links using `"scope"` key

And that’s about it. But it’s still valuable information to have on this guide page. Feel free to send a PR if you’re up for it :)

**Comment by captainbrosset** [comment]
Safari doesn't support PWA per say. It supports installing any site as an app. Edge supports this too (`...` > **Apps** > **Install this site as an app**).

Supporting installing any site as an app doesn't mean supporting installing PWAs.

PWA is defined as a set of criteria (which, for a long time, have been manifest + https + sw) that, when met, make the browser **promote** the app as an installable experience. So far, browsers have done this via the URL bar. 

Safari doesn't promote high-quality PWAs via a browser UI affordance. It lets users install any site they want. That's great, but it's just not PWA as we've been defining it for years.

Based on this, I wouldn't add Safari to the **Making PWAs installable** guide. Maybe we could add a section that says something like: "Some browsers support installing any sites as apps, but that's not related to PWA".

**Comment by pepelsbey** [comment]
> Safari doesn't support PWA per se. It supports installing any site as an app.

I meant to say the same thing, but then I realized that they support configuring installed web apps: hide/show browser controls, scope links, show badges, and send push notifications. The same way PWAs do that: via the web manifest. So it could be more than just a website’s icon in the dock if your app supports it.

Yes, they call it *WA, not PWA and the number of supported features is smaller, but for PWA developers it’s an opportunity to get a wider compatibility for their app. I wouldn’t hide this information from the page.

**Comment by captainbrosset** [comment]
I agree with mentioning Safari's ability to install sites as app somewhere in the docs. We can add a See also/Notes/Related section somewhere that mentions it (as well as Edge's ability to do the same thing, perhaps).

This guide is really about making PWAs (in the strict sense of the term) installable, by meeting the criteria in place in those browsers that do support installing PWAs. And we should try to not detract too much from this and confuse people.

**Comment by pepelsbey** [comment]
> We can add a See also/Notes/Related section somewhere that mentions it 

@captainbrosset I like the idea of grouping Safari and Edge into “PWA light” kind of section! Do you think you have time to send in a PR? At least from the Edge’s perspective, so we could complete it with the info about Safari’s behavior/features later. Or both, if you’re up for it :)

**Comment by pepelsbey** [comment]
@JOJOforshaun thank you for reporting this issue! It should be fixed now in https://github.com/mdn/content/pull/30875

Feel free to update the translation you mentioned earlier.

**Comment by yin1999** [comment]
Thank you guys. I'll update the translated content mentioned by @JOJOforshaun.
