### ISSUE TITLE
Clarify Terminology Around Mathematical Operations in JavaScript

### ISSUE THREAD

**Issue by DevNdamase** [mdn/content#30479]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math

### What specific section or headline is this issue about?

Basic math in JavaScript  -  Arithmetic Operators 

### What information was incorrect, unhelpful, or incomplete?

> Arithmetic operators are the basic operators that we use to do sums in JavaScript:

- The term _**sum**_ typically refers to the process of _**addition**_ exclusively. 
- However, in JavaScript, mathematical operations extend beyond mere _addition_ to include _subtraction,_ _multiplication,_ _division_ etc.
- To capture the broader scope of these mathematical processes, it is often more precise to employ terms such as _**mathematical calculations**_ or _**arithmetic operations**_.

![mdn-img](https://github.com/mdn/content/assets/102190131/efa8ecc7-ca3a-49f4-823e-ab09551fa7ab)

### What did you expect to see?

> Arithmetic operators are the fundamental operators used for performing mathematical calculations in JavaScript:

- I replaced the word _**sums**_ with _**mathematical calculations**_ .
- I also modified the sentence for better readability.

### Do you have any supporting links, references, or citations?

1. [Mometrix Academy](https://www.mometrix.com/academy/addition-subtraction-multiplication-and-division/)

![math-img](https://github.com/mdn/content/assets/102190131/ddb49247-49cf-4481-9f75-e48546444601)

2. [MathIsFun](https://www.mathsisfun.com/basic-math-definitions.html)

![math-img-2](https://github.com/mdn/content/assets/102190131/d63ec713-d1ab-4ddc-8115-c682b7344b00)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/math`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/math/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by hamishwillee** [comment]
Yes, it would be good to replace the word "sums" with "mathematical calculations". Would you like to create a PR for this?

**Comment by DevNdamase** [comment]
Yes, I'd be happy to create a Pull Request. Thank you!

**Comment by DevNdamase** [comment]
Yes, I'd be happy to create a Pull Request. Thank you!
