### ISSUE TITLE
Section on "relative selectors" requires explanation and examples

### ISSUE THREAD

**Issue by baharev** [mdn/content#30477]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors/Selector_structure

### What specific section or headline is this issue about?

Relative selector

### What information was incorrect, unhelpful, or incomplete?

It is my understanding that **relative selectors only work in certain contexts**, see [Selectors Level 4, W3C Working Draft, 11 November 2022](https://www.w3.org/TR/selectors-4/#relative):

> 3.4. Relative Selectors
> 
> Certain contexts may accept relative selectors, which are a shorthand for selectors that represent elements relative to one  or more relative selector anchor elements

It is my understanding that the argument of `:has()` is such a context. But what other contexts exist?

This requirement (that relative selectors only work in certain contexts) is currently not mentioned in that section, and only the last example shows the `:has()` but it is not explained at all what that example does. The first two examples are unclear to me and are not explained either.

Related issue:  https://github.com/mdn/content/issues/22917

### What did you expect to see?

A clear explanation of the contexts where relative selectors are accepted.

Then, each example should be explained in detail just like in the paragraph right above the Relative selectors, in the last paragraph of the Complex selectors section.

### Do you have any supporting links, references, or citations?

 [3.4. Relative Selectors in Selectors Level 4, W3C Working Draft, 11 November 2022](https://www.w3.org/TR/selectors-4/#relative)

**Comment by Josh-Cena** [comment]
`:has` is the only thing accepting relative selectors. https://github.com/search?q=repo%3Amdn%2Fdata+relative-selector&type=code

**Comment by baharev** [comment]
@Josh-Cena Thank you for the info. 

> `:has` is the only thing accepting relative selectors, as of now.

This piece of information should be in that section on relative selectors.

> The text is not wrong, and it's written that way to be future-proof.

I personally find the current text incomprehensible and confusing, even if it is not wrong.

> I wonder, why are you interested in knowing all contexts that accept relative selectors, rather than [...]

I was expecting several contexts, that's all. Good to know that currently there is only one.

**Comment by Josh-Cena** [comment]
`:has` is only given as an example; even with more such contexts in the future, the current text won't be wrong. We simply don't find it necessary to give an exhaustive list of relative selector contexts, neither do we think we can invest the time to keep it up-to-date. It's the same reason why we are removing such categorization-by-feature lists everywhere—for example, the list of animatable properties is also gone.

> I personally find the current text incomprehensible and confusing

In what way is it confusing? You are presented with potentially incomplete information but the purpose of this sentence is not to give you exhaustive information anyway.

**Comment by baharev** [comment]
I did **NOT** ask for an exhaustive list of all the possible contexts where relative selectors are accepted, and I was **NOT** suggesting creating and maintaining such an exhaustive list on the MDN website either.

> In what way is it confusing?  You are presented with potentially incomplete information

1.  It is not made clear and explicit that relative selectors only work in certain contexts (only in a single context currently). This is a crucial piece of information that is currently missing on the MDN website.
2.  As I understand it, the first two examples are invalid (wrong) because we don't have `has:` in them. In Visual Studio Code I get the following error: *"at-rule or selector expected"* if I try to use them.
3. The examples are not explained at all. What are the first two examples supposed to do?
4.  The issue [#22917](https://github.com/mdn/content/issues/22917) with the anchor element was "solved" by simply not explaining what the anchor element is supposed to be. What would be the anchor element in the first two examples?

**Suggestion**

1. Please consider simply copying the paragraph from: [3.4. Relative Selectors in Selectors Level 4, W3C Working Draft, 11 November 2022](https://www.w3.org/TR/selectors-4/#relative). It at least makes it explicit that relative selectors only work in certain contexts.
2. All the examples should be valid. This currently means that they all should use `has:`.
3. Then, each example should be explained in detail just like in the paragraph right above the Relative selectors, in the last paragraph of the Complex selectors section.
4. In the explanation of the examples, please mention which element is the anchor element.

**Comment by Josh-Cena** [comment]
Okay, I think I get the idea better now :)
