### ISSUE TITLE
Issue with "z-index": Syntax code block doesn't include 'revert' in the valid Global values

### ISSUE THREAD

**Issue by 0xdevalias** [mdn/content#3047]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/z-index

#### What information was incorrect, unhelpful, or incomplete?

Within the code block that shows possible global values we see the following:

```css
/* Global values */
z-index: inherit;
z-index: initial;
z-index: unset;
```

Yet it seems we can also use the global `revert` here as well:

- https://developer.mozilla.org/en-US/docs/Web/CSS/revert

#### Specific section or headline?

Syntax

#### What did you expect to see?

```diff
  /* Global values */
  z-index: inherit;
  z-index: initial;
+ z-index: revert;
  z-index: unset;
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/z-index`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/z-index
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/z-index/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can add it 👍

**Comment by chrisdavidmills** [comment]
I'm not convinced that we ever added `revert` to any property page's global values (I think we just added it to the [`all`](https://developer.mozilla.org/en-US/docs/Web/CSS/all) page).

It would be good to start off by checking this, and if not, writing some kind of a script that could crawl through the css property pages and add it to all of them that need it.

**Comment by rachelandrew** [comment]
agreed, seems like a job for a script. Then we can just keep an eye out for any that got missed. I've fixed a couple of syntax boxes that had something odd in them recently.

If we could compare a list of the pages this script caught with a list of all property pages then I could go round the ones that didn't get updated and find out why.

**Comment by sideshowbarker** [comment]
All the changes for this have been merged, so I’m going ahead and closing this (with thanks to @0xdevalias for having raised it to everybody’s awareness so that it could get fixed).
