### ISSUE TITLE
Issue with "Document: scroll event": Bubbles summary is inaccurate

### ISSUE THREAD

**Issue by andrewnicols** [mdn/content#3048]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/scroll_event

#### What information was incorrect, unhelpful, or incomplete?
This event does not always bubble.

When the target is the document it will fire at the target (document) and it will bubble.
When the target is not the document, it will fire at the target, but it will not bubble.

#### Specific section or headline?
Bubbles: Yes

#### What did you expect to see?
Yes[1]

[1]: Scroll events only bubble when the scrolled element was the document.
Scroll events do not bubble when a child element is scrolled. 

See the CSSOM View Module specification section 12.2 (https://drafts.csswg.org/cssom-view/#scrolling-events):

> When asked to run the scroll steps for a Document doc, run these steps:
> 
> 1. For each item target in doc’s pending scroll event targets, in the order they were added to the list, run these substeps:
>    1.  If target is a Document, fire an event named scroll that bubbles at target.
>    2. Otherwise, fire an event named scroll at target.
> 2. Empty doc’s pending scroll event targets.

#### Did you test this? If so, how?
Yes.

* I set the max-height of an element with long content to a lower value so that it overflows.
* Add a scroll event listener to the document, and the parent element
```
document.addEventListener('scroll', window.console.log);
$0.parentElement.addEventListener('scroll', window.console.log);
```
Then scroll the Node content

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/scroll_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/scroll_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/scroll_event/index.html
* Last commit: https://github.com/mdn/content/commit/56d9a678477f0e79232caa8169114519bf02a44a
* Document last modified: 2021-02-19T19:41:18.000Z

</details>

**Comment by andrewnicols** [comment]
I see there is a reference from Document.scroll_event to Element.scroll_event.

I'd suggest referencing this somewhere near the top of the document as it is not immediately clear that they differ.

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Modify the top sentence to be more explicit around document and element:  'document view has been scrolled. For element scrolling see...' with a link to element.scroll page

**Comment by mirexdoors** [comment]
Hello, mind I take this one?

**Comment by chrisdavidmills** [comment]
> Hello, mind I take this one?

Please do! Thanks for your interest in helping out!
