### ISSUE TITLE
MediaStreamAudioSourceNode recommends unsupported API

### ISSUE THREAD

**Issue by gavinlefebvre** [mdn/content#3050]
https://github.com/mdn/content/blob/f4b8c9ce03bfab2b2a81dc45aa108d1a58aaf301/files/en-us/web/api/mediastreamaudiosourcenode/index.html#L78

While MediaStreamTrackAudioSourceNode seems appealing, it is supported only by Firefox, so its use probably shouldn't be advised against.

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Remove the above sentence
* Add a note to explain the difference between MediaStreamTrackAudioSourceNode and MediaStreamAudioSourceNode with relevant link to doc
* Review MediaStreamTrackAudioNode and possibly add a note there as well

**Comment by mirexdoors** [comment]
Hello. Can I take this?

**Comment by chrisdavidmills** [comment]
@mirexdoors yes, you certainly can. Thanks for the help!
