### ISSUE TITLE
FOV graphic should use different angles for the view cones of each eye

### ISSUE THREAD

**Issue by felixniemeyer** [mdn/content#30516]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Fundamentals

### What specific section or headline is this issue about?

Field of View

### What information was incorrect, unhelpful, or incomplete?

I was confused for a second because the image with the head and the two view cones for the eyes are simply translated but not rotated. 

"A human eye is able to take in a FOV of around 135°. Assuming a person has two healthy eyes, the total field of view ends up being about 200° to 220° wide. Why is the FOV wider with two eyes, but not double the single-eye FOV? It's because the two eyes' FOVs overlap a lot."

### What did you expect to see?

in the image, the cones should be slightly rotated away from each other. 

### Do you have anything more you want to share?

If you agree this would be useful, I can do it!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webxr_device_api/fundamentals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Fundamentals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webxr_device_api/fundamentals/index.md
* Last commit: https://github.com/mdn/content/commit/4f0f7386262363103a3e9cf482bb348d8570b331
* Document last modified: 2023-02-19T08:44:25.000Z

</details>

**Comment by zfox23** [comment]
Hi @felixniemeyer :) can you please help me understand why the cones should be slightly rotated away from each other? is that how the human eyes work?

**Comment by felixniemeyer** [comment]
Hey :) 
I think that your right eye's FOV is limited by your nose to the left and goes more to the right. 
Your left eye is limited by your nose on the right. 
So even when your eyes are pointing to the same target (which they usually do ^^), the FOV cones of both eyes are turned away from the nose a bit. 
The way the current image shows it, does not match the statement below the image: 
"A human eye is able to take in a FOV of around 135°. Assuming a person has two healthy eyes, the total field of view ends up being about 200° to 220° wide. Why is the FOV wider with two eyes, but not double the single-eye FOV? It's because the two eyes' FOVs overlap a lot."

The two eye's FOVs don't overlap through translation but through rotation...

Does it become clearer now? 

Here is a quick sketch of a face from above: 
![image](https://github.com/mdn/content/assets/5720176/7d981244-be5a-4aad-9bb1-34b6a11d3767)
 
If the FOVs where just shifted left and right, the effective angle would depend on the distance and converge quickly to 135, the angle of a single eye. 

I'm not a human biology expert and maybe the view field of an eye is also rotated outwards by the population of the retina with cells. 

Fact is, the described change from 135 with one eye to 220 with two eyes requires a rotary overlap not a translatory one.
So either the text is false or the image does not accurately represent the text. (I'm being very accurate here.)

**Comment by zfox23** [comment]
> Fact is, the described change from 135 with one eye to 220 with two eyes requires a rotary overlap not a translatory one.

I am also not a biologist, so I don't have primary knowledge about this subject. Do you have a source for this information? It doesn't intuitively seem correct to me; my intuition says that our increased field of view from two eyes is not because of a difference in rotation but due to the fact that our noses aren't in the way of both eyes simultaneously. In other words, it seems to me like each eye would have that full 220 degree field of vision, if our noses weren't in the way. AFAIK, our eyes rotating "in" or "out" has more to do with focus than field of vision.

I've been trying to find sources for this specific information, but I'm surprised that it's such a challenge and that I haven't been able to thus far.

**Comment by felixniemeyer** [comment]
I completely agree with your intuition: 

```
my intuition says that our increased field of view from two eyes is not because of a difference in rotation but due to the fact that our noses aren't in the way of both eyes simultaneously.
```

And because of that, the two cones have to be rotated outwards in the schematic.

**Comment by zfox23** [comment]
This is fun!

I think I see what you're saying now. I had to draw a diagram similar to what you already drew in order to understand it myself:

![image](https://github.com/mdn/content/assets/3409031/a0b053d4-66ea-4602-af5a-0bfc80b43406)

This is what you mean, right?

I would love it if you came up with a better "field of view" graphic for this page, and also updated the prose to mention that one eye can't see the full 220 degrees because our noses are in the way.

Is that something that you can take on?

**Comment by felixniemeyer** [comment]
Exactly, your diagram nails it. 
I just tried to create a tidy schematic with inkscape and it's harder than I expected. Just when I tried to save v1 inkscape crashed xD

Anyways, I was inspired by this: 
![image](https://github.com/mdn/content/assets/5720176/df4aba5c-3928-4179-8b18-43cfd27a5b7c)
from this interesting article: [https://dl.acm.org/doi/fullHtml/10.1145/3554921](https://dl.acm.org/doi/fullHtml/10.1145/3554921)

Honestly, i think it might be easier for me to code svg than using Inkscape, lol.

**Comment by felixniemeyer** [comment]
I gave Inkscape another chance: 
![schematic-plain-final](https://github.com/mdn/content/assets/5720176/5a8b4a80-6c3e-4c66-bbe6-82b362ac7ff8)

I'm quite happy with the result. 
The original text would not have to be changed in my opinion. It's quite accurate. 

If you like, I can create a fork exchange the image and create a pull request for this. 

Thanks!

**Comment by zfox23** [comment]
That's a fantastic graphic, @felixlinker, and definitely an improvement over the existing one! Please do open a PR. You can set me as the reviewer and I'll take a look. I'm glad you decided to stick with it.

**Comment by felixlinker** [comment]
I second that @felixniemeyer should open a PR ;)

**Comment by zfox23** [comment]
OOPS! hehe. sorry about that! that is one way to "increase engagement"...

**Comment by felixniemeyer** [comment]
Hehe, little name confusion. Funny, how you handled it :) 
I created the pull request :arrow_up:
