### ISSUE TITLE
Issue with "JavaScript typed arrays": (Web Page is not working)

### ISSUE THREAD

**Issue by RajaSardar** [mdn/content#3051]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/typed_arrays`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/typed_arrays/index.html
* Last commit: https://github.com/mdn/content/commit/7f82e5ad1b593a2b1f3f43c7a1931ba05dc22cbb
* Document last modified: 2021-03-09T01:51:57.000Z

</details>

**Comment by CreaTorAlexander** [comment]
What do you mean by Web Page is not working?

**Comment by chrisdavidmills** [comment]
We can close this due to lack of information. If you did have something concrete to report, please open another issue and include more details.
