### ISSUE TITLE
Issue with "Node": ProcessingInstruction IS Based on CharacterData

### ISSUE THREAD

**Issue by abdwalfa** [mdn/content#3052]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node

#### What information was incorrect, unhelpful, or incomplete?

> These include Attr, CharacterData (which Text, Comment, and CDATASection are all based on), **_ProcessingInstruction_**, DocumentType, Notation, Entity, and EntityReference.

It doesn't explicitly say ProcessingInstruction isn't Based on CharacterData, but it implies it when ProcessingInstruction is not grouped with the other nodes inside the parentheses.

#### What did you expect to see?

> These include Attr, CharacterData (which Text, Comment, CDATASection and **_ProcessingInstruction_** are all based on), DocumentType, Notation, Entity, and EntityReference.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/node`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/node/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by NegiAkash890** [comment]
I can fix this !

**Comment by chrisdavidmills** [comment]
@NegiAkash890 Assigned; thanks for offering to fix it!
