### ISSUE TITLE
If possible, include an example of importing from an embedded module

### ISSUE THREAD

**Issue by DanKaplanSES** [mdn/content#30520]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#examples

### What information was incorrect, unhelpful, or incomplete?

If possible—and I mean this literally, I don't know if this can be done—can an example be added that shows how to import from an embedded module? 

If this isn't possible, can it be explicitly stated somewhere?

### What did you expect to see?

I'm trying to find the syntax to import from an embedded script module. e.g.,:

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>title</title>
    <script type="module">
        export const x = 1;
    </script>
    <script type="module">
        import { x } from // what do I type here?
    </script>
  </head>
  <body>
  </body>
</html>
```

I don't know if this syntax is possible, but I expected to find an answer to that within this page.

### Do you have anything more you want to share?

I also looked for an answer here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/script`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/script/index.md
* Last commit: https://github.com/mdn/content/commit/922c2b0f37e2f13887c50efe47e62bc23d94c3aa
* Document last modified: 2023-10-16T10:14:26.000Z

</details>

**Comment by Josh-Cena** [comment]
Hmmm, good question. I don't think you can do that. It's not very common to inline modules in an HTML file.

**Comment by Abdulrazzaq2** [comment]
The main benefit of export/import is to use external files to import it and  when importing , we always need a file to be imported and for js we need file.js extension, otherwise not working. So importing and exporting at same **HTML** file  isn't working`(path can't access lines in such a file)` because no need to do it as a programmer.  Hope you understand

**Comment by DanKaplanSES** [comment]
@Abdulrazzaq2 Correct me if I'm wrong, but it sounds like you haven't read the body of my issue?

**Comment by Abdulrazzaq2** [comment]
@DanKaplanSES i read it and even test the code.
 browsers doesn't directly support importing from embedded modules within an HTML file. This means that you cannot directly import from the <script> tag inside the HTML,
 **but** you can achieve the same functionality by bundling the embedded modules using tools like `webpack` or `rollup` so it will create separate files for your module. test the tools hope it will work then.

**Comment by DanKaplanSES** [comment]
@Abdulrazzaq2 
> i read it and even test the code.

My mistake. 

> This means that you cannot directly import from the <script> tag inside the HTML

That's fine: I just think that should be documented somewhere.

**Comment by Abdulrazzaq2** [comment]
@DanKaplanSES 
Thanks and any  other thing that you would like to ask, I hope that I will be helpful for it.
I would recommend to use external file.js and import it  inside the tag `<script type= "module"> ` this way is the preferred one to use import method between HTML and JS, Thanks for reading.
