### ISSUE TITLE
Tutorials shouldn’t be created around credit card data

### ISSUE THREAD

**Issue by lineus** [mdn/content#30539]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements

### What specific section or headline is this issue about?

The example web component that relates to credit cards

### What information was incorrect, unhelpful, or incomplete?

I was not expecting to see my browser at the ready to fill in my credit card info into an mdn tutorial. It’s probably almost certainly benign, but I think the example should stay out of my pocket, figuratively and literally.

### What did you expect to see?

Anything that doesn’t involve precious financial data potentially being leaked from my browser into your example.

### Do you have any supporting links, references, or citations?

It’s really just a feeling. Kinda like if my browser kept a cache of pictures of me in my underwear and your example triggered the browser to populate an upload form to mastodon or something.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_components/using_custom_elements/index.md
* Last commit: https://github.com/mdn/content/commit/bdb05e102fe86556abbc4fd70ad05064fe1bc917
* Document last modified: 2023-10-29T05:07:34.000Z

</details>

**Comment by hamishwillee** [comment]
1. Your credit card data may be auto-filled into the browser form, but is not stored or sent anywhere by Mozilla/MDN. There is no data leak or privacy issue.
2. How to work with forms is something that web developers need to learn. This is a safe space to do it.
