### ISSUE TITLE
Promise.resolve() is incomplete or incorrect

### ISSUE THREAD

**Issue by zjlovezj** [mdn/content#30530]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve

### What specific section or headline is this issue about?

section-content and Description

### What information was incorrect, unhelpful, or incomplete?

The section-content says ->

> if the value is a [thenable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables), Promise.resolve() will call the then() method with two callbacks it prepared;

It's incomplete to describe the behavior, for example what if the then() throw an exception and the then should always be called asynchronously. 
So I think it's more accurate to say: for thenable case, it will return new Promise(resolve => resolve(value)).
And it's the same behavior as the non-thenable case, maybe these two case should merge.

The description says -> 

> If a thenable is passed, the returned promise will adopt the state of that thenable by calling the then method and passing a pair of resolving functions as arguments.

It's also incomplete.
So link to the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise#resolver_function might be more accurate.

### What did you expect to see?

Be more clear about thenable(not a instance of promise), it's just the `new Promise(resolve => resolve(value))`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise/resolve`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/resolve/index.md
* Last commit: https://github.com/mdn/content/commit/4c26e8a3fb50d06963b06017f51ce19364350564
* Document last modified: 2023-08-11T08:07:46.000Z

</details>

**Comment by Josh-Cena** [comment]
We already both mentioned `new Promise((resolve) => resolve(value))` and linked to the resolver function before your quoted text. Your quoted text may be incomplete, but the purpose here is not to be exhaustive—it's only to be useful for practical purposes. Throwing an error is outside of the domain of practical usage and always relies on careful testing (although you can be assured that in no case would a promise adoption cause a synchronous error). Your quoted text is also not in contradiction with your explanation: when we say "will call the then() method", we never said it does so synchronously. We only said it "will" be called, and the exact timing needs to be checked in the description. Technical documentation is not about describing behavior in an axiomatic sense; it's also about appealing to developer intuitions about what distinct cases there are to consider to understand its behavior intuitively. The remaining pieces of technical details can be filled in by other parts, such as the resolver function section.

That's a long way to say thank you for being so careful, but MDN chooses to be "less correct" in this case to not fuss up most readers' minds. People want to read a page and quickly understand how something works "in normal circumstances" before tending to edge cases.

**Comment by zjlovezj** [comment]
Thank you for the detailed response.
I did miss the part which mentioned the resolver function.

My feeling is that `new Promise(resolve => resolve(value))` is more direct and distinct, maybe it's worth putting it in the section-content part.
Today a very good programmer told me that how to implement Promise.resolve using this page, and he seems never have a good read about the description, just like me:)
