### ISSUE TITLE
Improvement `Specifications` section by specificing `spec-urls` front matter key for API summary pages

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#30542]
### What information was incorrect, unhelpful, or incomplete?

The https://github.com/mdn/content/discussions/4920 discussed whether to specific `browser-compat-data` front matter key for *API summary pages* without a conclusion, it also discuss the better usage of `spec-urls` front matter key

And, to generate {{Specifications}} macros, the page will use `spec-urls` front matter key by default, or use `browser-compat` front matter key as fallback if `spec-urls` not specific, see https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Specification_tables also https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Compatibility_tables

The question is, currently the `browser-compat` front matter key specificed in *API summary pages* is referred to an interface or anything else, the result is that the {{Specifications}} will referred to the interface or anything else according to the `browser-compat` front matter key; also, if *API summary pages* specific multpile `browser-compat` front matter key, the {{Specifications}} will referred to multpile specifications which may in fact linked to the same API standard documentation

currently we could improve this by specificing `spec-urls` front matter key for *API summary pages*

---

for example:

```md
---
title: Remote Playback API
slug: Web/API/Remote_Playback_API
page-type: web-api-overview
browser-compat: api.RemotePlayback
<!-- add the line below -->
spec-urls: https://w3c.github.io/remote-playback/
---
```

### What did you expect to see?

specific `spec-urls` front matter key for *API summary pages*

**Comment by Foxhgf** [comment]
https://harun.yoo7.com

**Comment by skyclouds2001** [comment]
> https://harun.yoo7.com

?

**Comment by hamishwillee** [comment]
> currently we could improve this by specificing spec-urls front matter key for API summary pages

That's questionable. The discussion in https://github.com/mdn/content/discussions/4920 is attempting to resolve that question "where should compatibility and specification information be included". If we agree it makes sense to include this information then we'd decide how we solve it - this way or some other way.

IMO this should be closed and the discussion in 4920 continued to some kind of resolution. Perhaps take it to the next community call?

**Comment by teoli2003** [comment]
How to display compatibility in API summary pages is a tricky question:
- what is included in a given API?
- do we want a single value for the whole API or all the "gory" details?
- how do we maintain it? I'm afraid the list of `spec-url` entries on these pages will become outdated.

I think we should **not** display them **for now**. There is work at the WebDX group about defining feature groups. API will be part of it: once we have this bit, we should have a clearer view. The baseline idea (display a single entry summarizing BCD) may solve the problem of API overview pages.

Not that the problem here is not real, I think the solution is premature and we should close this (for the moment).

**Comment by skyclouds2001** [comment]
i. current there has not reached a conclusin abort how to do with *Specifications* section in the *web-api-overview* pages
ii. the `{{Specifications}}` macros generation will use `browser-compat` front matter key by default if `spec-urls` front matter key not specificed
iii. if the `browser-compat` front matter key in the *web-api-overview* pages were passing multpile values, the `{{Specifications}}` macros will generate multpile items, like [https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API)
iv. in iii situation, these items refer to the same standard, just with different hash to link to different interfaces or extensions
v. this can be improved by specfic the `spec-urls` front matter key to the standard whole link (not the one refer to one interface or extension of the API)

**Comment by skyclouds2001** [comment]
see https://github.com/mdn/content/pull/16266 for more information
