### ISSUE TITLE
Typo "fours others"

### ISSUE THREAD

**Issue by Jaiket** [mdn/content#30549]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API

### What specific section or headline is this issue about?

Cue Payload

### What information was incorrect, unhelpful, or incomplete?

fours others

### What did you expect to see?

four others

### Do you have any supporting links, references, or citations?

> She loves animals and has two dogs, three cats and one rabbit.

https://dictionary.cambridge.org/grammar/british-grammar/number

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webvtt_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webvtt_api/index.md
* Last commit: https://github.com/mdn/content/commit/d3cdafcdb4d22e5c55771501e7c80451a96aa032
* Document last modified: 2023-03-12T06:37:36.000Z

</details>

**Comment by Himanshuch8055** [comment]
Nice catch. !Attempt
