### ISSUE TITLE
Broken link to pseudo-class ":state"

### ISSUE THREAD

**Issue by Jaiket** [mdn/content#30554]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

### What specific section or headline is this issue about?

Alphabetical index

### What information was incorrect, unhelpful, or incomplete?

:state() 

### What did you expect to see?

I expected a link to an explanatory page, just as there is for all the other entries in this list.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/CSS/:state (page not found)
https://stackoverflow.com/questions/64913536/how-does-the-css-pseudo-class-state-work
https://wicg.github.io/custom-state-pseudo-class/

### Do you have anything more you want to share?

After some web-searching with limited knowledge of the subject, I believe this entry is an error. Although custom-states are being experimented, I could not find any unbroken reference to an experimental pseudo-class named ":state".

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/pseudo-classes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/pseudo-classes/index.md
* Last commit: https://github.com/mdn/content/commit/ff07c2fc3bee874e6f1e7398c42cfa702d520009
* Document last modified: 2023-06-13T19:08:55.000Z

</details>

**Comment by bsmth** [comment]
Thanks for raising this one @Jaiket - this is currently being worked on at the moment:

* Experimental features: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#custom_element_state_pseudo-class

* Current browser support: https://wpt.fyi/results/css/selectors/parsing/parse-state.html?label=experimental&label=master&aligned

* Explainer: https://github.com/WICG/custom-state-pseudo-class/blob/main/explainer.md#example


I'm going to close this issue as we can track documentation work at: https://github.com/mdn/content/issues/30339

Thanks a lot :)
