### ISSUE TITLE
Alphabetical index is not alphabetical within list-entries for 'f' and 'p'

### ISSUE THREAD

**Issue by Jaiket** [mdn/content#30553]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

### What specific section or headline is this issue about?

Alphabetical index

### What information was incorrect, unhelpful, or incomplete?

    [:first](https://developer.mozilla.org/en-US/docs/Web/CSS/:first)
    [:first-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child)
    [:first-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-of-type)
    [:fullscreen](https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen)
    [:future](https://developer.mozilla.org/en-US/docs/Web/CSS/:future) Experimental
    [:focus](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus)
    [:focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible)
    [:focus-within](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within)

and

    [:past](https://developer.mozilla.org/en-US/docs/Web/CSS/:past) Experimental
    [:picture-in-picture](https://developer.mozilla.org/en-US/docs/Web/CSS/:picture-in-picture)
    [:placeholder-shown](https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown)
    [:paused](https://developer.mozilla.org/en-US/docs/Web/CSS/:paused)
    [:playing](https://developer.mozilla.org/en-US/docs/Web/CSS/:playing) 

### What did you expect to see?

    [:first](https://developer.mozilla.org/en-US/docs/Web/CSS/:first)
    [:first-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child)
    [:first-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-of-type)
    [:focus](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus)
    [:focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible)
    [:focus-within](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within)
    [:fullscreen](https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen)
    [:future](https://developer.mozilla.org/en-US/docs/Web/CSS/:future) Experimental

and

    [:past](https://developer.mozilla.org/en-US/docs/Web/CSS/:past) Experimental
    [:paused](https://developer.mozilla.org/en-US/docs/Web/CSS/:paused)
    [:picture-in-picture](https://developer.mozilla.org/en-US/docs/Web/CSS/:picture-in-picture)
    [:placeholder-shown](https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown)
    [:playing](https://developer.mozilla.org/en-US/docs/Web/CSS/:playing)

### Do you have anything more you want to share?

I looked for "future" at the end of the "f" entry, which ends with "focus-within", and concluded that it was not in the list.
I checked the other entries, which appear to be correct.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/pseudo-classes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/pseudo-classes/index.md
* Last commit: https://github.com/mdn/content/commit/ff07c2fc3bee874e6f1e7398c42cfa702d520009
* Document last modified: 2023-06-13T19:08:55.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for pointing it out :) Would you like to open a pull request for these changes?

**Comment by Jaiket** [comment]
@bsmth I think so, although I haven't understood the processes of the collaborative work going on here, or much at all about coding. I'll look up how i go about it :)

**Comment by OnkarRuikar** [comment]
> @bsmth I think so, although I haven't understood the processes of the collaborative work going on here, or much at all about coding. I'll look up how i go about it :)

This one is easy you can [submit changes directly from a web browser](https://github.com/mdn/content/blob/main/CONTRIBUTING.md#simple-changes). There is a `Edit the page on GitHub` link at the bottom of the page.

**Comment by Jaiket** [comment]
@OnkarRuikar thanks for the info. I forked, edited and previewed. The preview is not the same as the public page, but looks like this on most (all?) lines :
{{CSSxRef(":active")}}
Is this OK? Is it because the CSS is not applied to the preview?

**Comment by OnkarRuikar** [comment]
> Is this OK? Is it because the CSS is not applied to the preview?

Yes it is perfectly fine. GitHub shows preview for the markdown only. The actual page rendering (CSS and Js stuff) automatically happens somewhere else we don't have to worry about it. After changing the code just submit the changes and create a PR.

In PR description put following to link the PR to this issue: `Fixes https://github.com/mdn/content/issues/30553`

**Comment by Jaiket** [comment]
I fixed the code and issued a pull request.
I could not find how to edit my fork directly on github without downloading some local *.js and another file. I had not committed the edit immediately following the creation of my fork because I was unsure of the preview as mentioned above.
Was there a way to edit my fork simply on github? Instead, I just started again from the original online page and was guided towards a fork of my fork.

**Comment by bsmth** [comment]
Thanks @Jaiket for raising the issue and fixing 🎉 welcome!

**Comment by teoli2003** [comment]
Pas de problèmes; tout le monde est passé par une phase de découverte. 😉 C'est normal!

**Comment by Josh-Cena** [comment]
Ce que @teoli2003 a dit. Merci pour votre contribution et bienvenue à bord!

By the way, you were not the first to have missed the title and everyone makes such mistakes :)
