### ISSUE TITLE
Missing return in Promise example

### ISSUE THREAD

**Issue by Nerdman4U** [mdn/content#30555]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises

### What specific section or headline is this issue about?

Should there be a return before call "doSomethingOptional(result)"?

### What information was incorrect, unhelpful, or incomplete?

```
doSomethingCritical()
  .then((result) =>
    doSomethingOptional(result)
      .then((optionalResult) => doSomethingExtraNice(optionalResult))
      .catch((e) => {}),
  ) // Ignore if optional stuff fails; proceed.
  .then(() => moreCriticalStuff())
  .catch((e) => console.error(`Critical failure: ${e.message}`));
```

### What did you expect to see?

```
doSomethingCritical()
  .then((result) =>
    return doSomethingOptional(result)
      .then((optionalResult) => doSomethingExtraNice(optionalResult))
      .catch((e) => {}),
  ) // Ignore if optional stuff fails; proceed.
  .then(() => moreCriticalStuff())
  .catch((e) => console.error(`Critical failure: ${e.message}`));
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/using_promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/using_promises/index.md
* Last commit: https://github.com/mdn/content/commit/efe078ff491a32b7e73488128344acaa80936ff1
* Document last modified: 2023-11-23T07:11:29.000Z

</details>

**Comment by skyclouds2001** [comment]
I think there cannot be a `return` because there use a simplified usage on written type of arrow function

```js
doSomethingCritical()
  .then((result) =>
    doSomethingOptional(result)
      .then((optionalResult) => doSomethingExtraNice(optionalResult))
      .catch((e) => {}),
  ) // Ignore if optional stuff fails; proceed.
  .then(() => moreCriticalStuff())
  .catch((e) => console.error(`Critical failure: ${e.message}`));
```

is like

```js
doSomethingCritical()
  .then((result) => (
    doSomethingOptional(result)
      .then((optionalResult) => doSomethingExtraNice(optionalResult))
      .catch((e) => {}),
    )
  ) // Ignore if optional stuff fails; proceed.
  .then(() => moreCriticalStuff())
  .catch((e) => console.error(`Critical failure: ${e.message}`));
```

or

```js
doSomethingCritical()
  .then((result) => {
    return doSomethingOptional(result)
      .then((optionalResult) => doSomethingExtraNice(optionalResult))
      .catch((e) => {}),
  }
  ) // Ignore if optional stuff fails; proceed.
  .then(() => moreCriticalStuff())
  .catch((e) => console.error(`Critical failure: ${e.message}`));
```

**Comment by Nerdman4U** [comment]
Hi, thanks, i see it now too. Great work, well done examples and
instructions.
Sincerely
Joni

su 26. marrask. 2023 klo 16.18 skyclouds2001 ***@***.***)
kirjoitti:
