### ISSUE TITLE
The space-key doesn't work like the other keys in event.key

### ISSUE THREAD

**Issue by ralf3u** [mdn/content#30562]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

### What specific section or headline is this issue about?

The space-key doesn't work like the other keys in event.key

### What information was incorrect, unhelpful, or incomplete?

incorrect:
The headline is "Examples". In fact there is only one example because there is only one JavaScript. So, the headline should be "Example".

incomplete:
a)
I miss an explication why the space-key doesn't work like the other keys.  In the given example I can't write something like: `case "Space":`. I don't know why it is not possible.
b)
I miss code about how to catch the space-key.

### What did you expect to see?

see my explication above

### Do you have any supporting links, references, or citations?

https://www.freecodecamp.org/news/javascript-keycode-list-keypress-event-key-codes/
In the Headline "A Full List of Key Event Values":
In the column "EVENT.KEY", the KEY NAME space has no entry.
In the column "NOTES" there is this text for the KEY NAME space:
"The event.key value is a single space."

### Do you have anything more you want to share?

Here I found a solution how to catch the space-key:
https://stackoverflow.com/questions/69769777/event-key-spacebar-works-not-correct
To catch the space-key:
if (event.key === ' ') {
    //Do something for "space" key press.
  }
So, could you please add the code just above in the example?
Thank you in advance for an optimization of the webpage.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/keyboardevent/key`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/keyboardevent/key/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by ralf3u** [comment]
I forgot to mention where I would put the code mentioned above. I would paste it in the example right under this line:
```(event) => {```

**Comment by pepelsbey** [comment]
Hey! Good catch :) It would be a good addition to this page to have an example of Space key detection in the list of all examples. Or even add a note describing what is happening. I don’t entirely agree with the “Examples” title being wrong: it’s a single code snippet showing how to handle multiple keys.

Feel free to send a PR adding this case and a note, or let’s wait for someone from the community to pick this up. Thanks!
