### ISSUE TITLE
has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

### ISSUE THREAD

**Issue by ravisingh0009** [mdn/content#3056]
has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by chrisdavidmills** [comment]
Is this a problem with a specific MDN page? What is the problem? Have you tested it? How should the page be updated?

There is no information here that allows me to take any action to fix an issue, therefore I'm closing this.
