### ISSUE TITLE
Outdated guidance 

### ISSUE THREAD

**Issue by jwhitenerUDM** [mdn/content#30572]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Privacy/Storage_access_policy/Errors/CookieBlockedTracker

### What specific section or headline is this issue about?

What went wrong?

### What information was incorrect, unhelpful, or incomplete?

Directions to the relevant settings does not match the path in Firefox 119.0.1 (Windows).  The directions say "The permission can be changed or removed by: Going to Preferences > Content Blocking"

There is no "Preferences" or "Content Blocking" options that I could find.

### What did you expect to see?

My best guess is the current path is Settings > Privacy & Security > and then "Manage Exceptions" under Enhanced Tracking Protection.  However, I'm not certain what the best advice is.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/privacy/storage_access_policy/errors/cookieblockedtracker`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Privacy/Storage_access_policy/Errors/CookieBlockedTracker
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/privacy/storage_access_policy/errors/cookieblockedtracker/index.md
* Last commit: https://github.com/mdn/content/commit/4a6dacf8c68925a8538585be3b2728bcb271241e
* Document last modified: 2023-07-24T23:58:21.000Z

</details>

**Comment by bsmth** [comment]
Hi @jwhitenerUDM - thanks for reporting. There's just been an update landed in https://github.com/mdn/content/pull/30480 which changes the language to "Privacy & Security > Enhanced Tracking Protection", although "Preferences" remains. The [SUMO docs mention "Preferences"](https://support.mozilla.org/en-US/kb/firefox-options-preferences-and-settings) so this looks correct to me.

**Comment by jwhitenerUDM** [comment]
Thanks, Brian!

Have a great day.

Jon

--
Jon Whitener
Web Information Coordinator
Marketing & Communications Dept.
University of Detroit Mercy
https://udmercy.edu/web

**Comment by bsmth** [comment]
Not a problem. I'm going to close this one as done, have a great day, too 👋🏻
