### ISSUE TITLE
Remove or fix example of custom select element

### ISSUE THREAD

**Issue by estelle** [mdn/content#30574]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

### What specific section or headline is this issue about?

customizing_select_styles

### What information was incorrect, unhelpful, or incomplete?

In the https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#customizing_select_styles example:
The selects have no labels.
both have the same id
there's a ton of CSS that could be hidden
should we add this to an ARIA page and remove it from select?

### What did you expect to see?

valid HTML
brief, easy to follow code examples

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/select`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/select/index.md
* Last commit: https://github.com/mdn/content/commit/07f0cf4375aaa02e1071d8bd0e8518db7609b7a9
* Document last modified: 2023-07-17T23:05:13.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/33859
