### ISSUE TITLE
Suggestions does not appear when typing in the output "Choose a flavor:" field (Android)

### ISSUE THREAD

**Issue by sv-calin** [mdn/content#30571]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

### What specific section or headline is this issue about?

Output section / "Choose a flavor:" field

### What information was incorrect, unhelpful, or incomplete?

While using a mobile device, when starting to type somthing in the "Choose a flavor:" field (Output section) suggestions are not shown.

### What did you expect to see?

Suggestions being shown like on the desktop version: 

![image](https://github.com/mdn/content/assets/107036654/235f722f-5547-4f1f-b1ba-10713d2c0a42)

### Do you have any supporting links, references, or citations?

From [webcompat](https://github.com/webcompat/web-bugs) repository: https://github.com/webcompat/web-bugs/issues/130289

https://github.com/mdn/content/assets/107036654/406f2f3e-5170-449b-93ce-3a2d771aa7aa

**Comment by Josh-Cena** [comment]
Are you suggesting this is a content bug (that `datalist` does not require a dropdown to be displayed), a browser compat bug (that mobile browsers should be recorded as partial implementation), or a platform bug (that MDN has some code preventing the dropdown from showing on our site)? This would determine which repo we should move the issue to.

**Comment by sv-calin** [comment]
I was referring to the datalist to be displayed when trying to type something (e.g. "C") on Android the same as on Desktop but I guess the behaviour is different on Mobile. (not a dev btw)

What's the correct behaviour on Mobile, suggestions displayed on the on screen keyboard like on Chrome? if thats the case I guess thats a browser issue.

![image](https://github.com/mdn/content/assets/107036654/406fc45c-a778-4812-ae12-58a14cab3721)

**Comment by caugner** [comment]
As per the [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist#browser_compatibility) data, Firefox only partially supports the `<datalist>` element, with the notable limitation on Android that "The dropdown menu containing available options does not appear.".

I will go ahead and close this issue, as it describes a browser limitation, not an issue in the MDN content.
