### ISSUE TITLE
Be explicit about what makes a session cookie a session cookie

### ISSUE THREAD

**Issue by michaelmcandrew** [mdn/content#30593]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

### What specific section or headline is this issue about?

Session cookies

### What information was incorrect, unhelpful, or incomplete?

It would be good to be explicit about what makes a session cookie a session cookie.

> Session cookies are deleted when the current session ends. The browser defines when the "current session" ends, and some browsers use session restoring when restarting. This can cause session cookies to last indefinitely.

### What did you expect to see?

Maybe just add this in brackets,

> Session cookies  (i.e. cookies without a `Max age` or `Expires` attribute) are deleted...

### Do you have anything more you want to share?

I'm reasonably sure what I have said above it correct but it would be good to have it corroborated.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/cookies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cookies/index.md
* Last commit: https://github.com/mdn/content/commit/0573275b2354be5e6ba961c544b8e3a06103648b
* Document last modified: 2023-11-09T07:40:53.000Z

</details>

**Comment by IAfanasov** [comment]
I think the linked merged PR should have closed this ticket. Should we close it manually?

**Comment by michaelmcandrew** [comment]
Happy to close.
