### ISSUE TITLE
Issue with "backdrop-filter": (listed as unsupported on Opera)

### ISSUE THREAD

**Issue by onlyphantom** [mdn/content#3059]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

#### What information was incorrect, unhelpful, or incomplete?
This CSS property is listed as unsupported by Opera, but as of the last few versions this has been supported. 

#### Specific section or headline?
Browser Compatibility > Opera.

#### What did you expect to see?
On Opera version 74, this CSS property is supported without any vendor prefixes, so expected to see a check under Browser Compatibility.

#### Did you test this? If so, how?
Yes, tested it on Opera 74. 

<img width="1177" alt="Screen Shot 2021-03-12 at 18 13 30" src="https://user-images.githubusercontent.com/16984453/110932973-badad480-835e-11eb-9f2f-00b93f4af53c.png">

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/backdrop-filter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/backdrop-filter/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by rachelandrew** [comment]
Looks like this needs updating in the compat data - thanks for spotting it!

**Comment by rachelandrew** [comment]
This has now been fixed in the data - will show up on the page when BCD updates.
