### ISSUE TITLE
IE is No Longer a Supported Browser So Reference to It Should Be Removed

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#30603]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started

### What specific section or headline is this issue about?

Requirements

### What information was incorrect, unhelpful, or incomplete?

Since IE is no longer a supported browser, the sentence needs to be reworked to remove the reference. For example, "Also, bear in mind that React and ReactDOM produce apps that only work on a fairly modern set of browsers like Firefox, Microsoft Edge, Safari, or Chrome when working through these tutorials."

Please see the attached screenshot.

<img width="960" alt="mdn - getting started with react - IE no longer supported browser" src="https://github.com/mdn/content/assets/10423487/9182f833-2a98-47d8-a11e-bb9d3ef3c014">

### What did you expect to see?

I expected that the reference to EI would be removed, but figure there are many in the documentations that aslo would need to be changed.

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
* Last commit: https://github.com/mdn/content/commit/c6b858c55966a86d617768faa303ecb5803f8178
* Document last modified: 2023-09-24T16:27:26.000Z

</details>

**Comment by pepelsbey** [comment]
Hey! Good point :) This note won’t be helpful information to anyone reading this in 2023. Even though the scope of updating the whole tutorial might be pretty big, it won’t hurt to update the parts that stick out the most.

Feel free to suggest a fix via PR if you have time. Thanks!
