### ISSUE TITLE
Issue with "General asynchronous programming concepts": Web Workers Missing Code

### ISSUE THREAD

**Issue by denik1981** [mdn/content#3060]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Concepts

#### What information was incorrect, unhelpful, or incomplete?
Missing Code inside the test file simple-sync-worker.html (No date calculations as it is mentioned)

#### Specific section or headline?
JavaScript is single-threaded
`javascript/asynchronous/introducing/simple-sync-worker.html`

#### What did you expect to see?
_"This is a rewrite of our previous example that calculates the 10 million dates in a separate worker thread"._
The written code actually do nothing. No dates are calculated.

#### Did you test this? If so, how?
Yes, I ran it from the test button it is provided on the learning guide.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/concepts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Concepts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/concepts/index.html
* Last commit: https://github.com/mdn/content/commit/9ac92e59230ba51bd3212e8976fd36e0d431a372
* Document last modified: 2021-02-24T12:12:03.000Z

</details>

**Comment by chrisdavidmills** [comment]
@denik1981 having looked at this, the dates are calulated in the [worker.js](https://github.com/mdn/learning-area/blob/master/javascript/asynchronous/introducing/worker.js). The `postMessage()` call to `worker.js` causes the dates to be calculated; if you look inside the worker.js file, you'll see that the code is placed inside an `onmessage` handler.

So things are happening here. Do you think this needs some more explanation adding to the article?

**Comment by RHONDAKNOWLES** [comment]
> MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Concepts
> 
> #### What information was incorrect, unhelpful, or incomplete?
> Missing Code inside the test file simple-sync-worker.html (No date calculations as it is mentioned)
> 
> #### Specific section or headline?
> JavaScript is single-threaded
> `javascript/asynchronous/introducing/simple-sync-worker.html`
> 
> #### What did you expect to see?
> _"This is a rewrite of our previous example that calculates the 10 million dates in a separate worker thread"._
> The written code actually do nothing. No dates are calculated.
> 
> #### Did you test this? If so, how?
> Yes, I ran it from the test button it is provided on the learning guide.
> 
> MDN Content page report details

islandluckaccount

**Comment by RHONDAKNOWLES** [comment]
loginme in  free games
