### ISSUE TITLE
Promise.withResolvers() Specifications is broken

### ISSUE THREAD

**Issue by sidewayss** [mdn/content#30606]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers

### What specific section or headline is this issue about?

#specifications

### What information was incorrect, unhelpful, or incomplete?

It's a red "not found" error block:

![image](https://github.com/mdn/content/assets/15235202/f68847bb-5c94-427f-9319-fc5a57b72657)

### What did you expect to see?

Not an error.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise/withresolvers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/withresolvers/index.md
* Last commit: https://github.com/mdn/content/commit/6af0c0d0b640e756765976ad854f4cc64c2f911c
* Document last modified: 2023-11-23T07:51:03.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed and not a content issue anyway :)
