### ISSUE TITLE
Issue with "Cross-Origin Resource Sharing (CORS)": (short summary here please)

### ISSUE THREAD

**Issue by johnye2e** [mdn/content#3062]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

#### What information was incorrect, unhelpful, or incomplete?

No event listeners are registered on any **XMLHttpRequest.upload** object used in the request; these are accessed using the **XMLHttpRequest.upload** property.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests

#### What did you expect to see?

Perhaps:

No event listeners are registered on any **XMLHttpRequest** object used in the request; these are accessed using the **XMLHttpRequest.upload** property.

#### Did you test this? If so, how?

-

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/index.html
* Last commit: https://github.com/mdn/content/commit/f89d77db60b18d8b4592a038d9c2b13d08faa9db
* Document last modified: 2021-03-07T23:18:07.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this. The object where the event listeners get registered is actually the `XMLHttpRequestUpload` object, and what’s sort of inherently confusing about this is that given an `XMLHttpRequest` instance `xhr`, accessing the `xhr.upload` property is how you get an `XMLHttpRequestUpload` object. But basically the only purpose of getting an `XMLHttpRequestUpload` object is to attach event listeners to it.

But you’re correct that “XMLHttpRequest.upload” isn’t strictly an object; instead, accessing the `.upload` property from an `XMLHttpRequest` instance returns an `XMLHttpRequestUpload` object — and then attaching event listeners to that `XMLHttpRequestUpload` object is what will trigger a preflight.

So in #3138 I’ve tried to revise the language to make it more clear what we’re talking about.
