### ISSUE TITLE
Issue with "<option>: The HTML Option element": Describe what CSS is supported

### ISSUE THREAD

**Issue by thany** [mdn/content#3063]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option

#### What information was incorrect, unhelpful, or incomplete?
There is no description of what CSS is supported on `<option>` elements. Even though most web developers know there they are limited in some way, it's hard to remember is what way they are limited. Therefor it's really helpful to know what exactly is and isn't supported.

#### Specific section or headline?
Maybe something like "Supported CSS properties"?

#### What did you expect to see?
A list of CSS proprties that work on this element (or indeed a list of the ones that aren't).

#### Did you test this? If so, how?
Wouldn't know what there is to test here.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/option`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/option/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by chrisdavidmills** [comment]
We'll triage this properly later on, but my immediate feeling is that we should think carefully about how we do this. If we have a list of CSS properties that work and don't work on each HTML element, that could be a lot of work, and a lot of the lists could look very similar.

Instead, I'd advise that we either just link to a place where styling is talked about (for example in this case, we have https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling), or include an optional section that covers exceptions and noteworthy gotchas about styling that element.

Indeed, we started to do that on a few elements, e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#styling_with_css, so this is probably the way to go if we did want to include something.

**Comment by wbamberg** [comment]
> include an optional section that covers exceptions and noteworthy gotchas about styling that element.

I like this, and when we defined page types for HTML elements we included "Styling with CSS" as an optional prose section.

**Comment by chrisdavidmills** [comment]
> > include an optional section that covers exceptions and noteworthy gotchas about styling that element.
> 
> I like this, and when we defined page types for HTML elements we included "Styling with CSS" as an optional prose section.

Great, thanks for confirming that @wbamberg ! I had a suspicion that you did, but I couldn't find the evidence to confirm it ;-)

**Comment by rachelandrew** [comment]
I'll take a look at this, but agree we don't want to list all possible styling options (with form elements there are browser differences too, so just because something can apply doesn't mean it will).

**Comment by thany** [comment]
@chrisdavidmills It wasn't my intention to suggest adding a whitelist of CSS properties to each and every element. Most elements can accept any CSS property, but there are just a handful of elements that do indeed come with a few catches and gotchas. I feel it's important to list only those (or link to where that's described) and leave out what comes natural, to prevent the forest from obscuring the trees.

@rachelandrew Agreed. Browser differences are a pain to maintain. But for lots of elements and attributes, that's what MDN is already doing, at least to a degree. So then, what's a few exceptional styling gotchas on maybe a handful of elements, in addition to the support tables that are already there?

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills It wasn't my intention to suggest adding a whitelist of CSS properties to each and every element. Most elements can accept any CSS property, but there are just a handful of elements that do indeed come with a few catches and gotchas. I feel it's important to list only those (or link to where that's described) and leave out what comes natural, to prevent the forest from obscuring the trees.

Cool, I think we are in agreement there then.

**Comment by rachelandrew** [comment]
I think what needs to happen here is that individual issues should be raised for any element that comes with "gotchas".

@thany feel free to raise individual issues (or indeed a PR) for any individual page that you think could do with a "Styling with CSS" section as described above. But I'm going to close this due to being a bit broad and non-specific.

**Comment by thany** [comment]
No offense, but this issue actually started with one very specific case, but the discussion moved into a more general direction after that. So, I should just recreate this issue then because it's already quite specific, or...?
