### ISSUE TITLE
Broken link to downloading MS Edge VMs

### ISSUE THREAD

**Issue by behkod** [mdn/content#30636]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Supporting_Older_Browsers

### What specific section or headline is this issue about?

Testing older browsers

### What information was incorrect, unhelpful, or incomplete?

The hyperlink under text "[a range of Virtual Machines available for free download](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)" is broken, seems the page is no longer available at Microsoft, or they prefer tools like MS Edge WebDriver.

### What did you expect to see?

The link containing VMs to download.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/css_layout/supporting_older_browsers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Supporting_Older_Browsers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/supporting_older_browsers/index.md
* Last commit: https://github.com/mdn/content/commit/289d6314f3368aa3e28524e7d090f6e9c704e3b1
* Document last modified: 2023-11-28T20:48:44.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for reporting @behkod 

>prefer tools like MS Edge WebDriver.

I think this is the case, indeed. I think it's worth pointing to WebDriver instead.

**Comment by OnkarRuikar** [comment]
I think that link points to [VMs for testing Edge legacy(without chromium) and IE 11](https://www.bleepingcomputer.com/news/microsoft/microsoft-offers-free-windows-10-vms-for-edge-legacy-testing/) . Those browsers are long gone and we have evergreen browsers now.



> I think it's worth pointing to WebDriver instead.

[It doesn't seem like it is possible to test older versions of Edge](https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp&form=MA13LH#download-microsoft-edge-webdriver) using the WebDriver.

So, considering [the discussion about documenting old browsers](https://github.com/mdn/content/discussions/14953#discussioncomment-2567723), and 6 months have passed, we can simply remove the paragraph and IE related sections from the page.

**Comment by bsmth** [comment]
>[It doesn't seem like it is possible to test older versions of Edge](https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp&form=MA13LH#download-microsoft-edge-webdriver) using the WebDriver.

ah-ha

>we can simply remove the paragraph and IE related sections from the page

yes, I agree, let's remove it 👍🏻
