### ISSUE TITLE
[JS] Document the .at() proposal

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#307]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1.  `.at()`. From some simple testing, it looks like this is supported in Chrome Canary (89) and Firefox Nightly (85), but not release versions yet (see https://bugzilla.mozilla.org/show_bug.cgi?id=1681371, for example). I still think it is worth documenting; I reckon we need pages for:
   * `String.prototype.at()`
   * `Array.prototype.at()`
   * `TypedArray.prototype.at()`
   * Anything else?

## Related Gecko bugs

1. - [x] [Implement the .at() proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1658308)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Rumyra** [comment]
Just reminding myself to update this page as well https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/@@unscopables

**Comment by Rumyra** [comment]
- [ ] Interactive examples for array, string & typedarray: see https://github.com/mdn/interactive-examples/pull/1753
- [ ] New docs
  - [ ] array
  - [ ] string
  - [ ] typed array
- [ ] Updating existing object pages
- [ ] @@unscopables
- [ ] BCD
- [ ] Experimental features page

**Comment by Rumyra** [comment]
Added note to experimental features https://github.com/mdn/content/pull/1525

**Comment by Rumyra** [comment]
Added to @@unscopables https://github.com/mdn/content/pull/1526

**Comment by Rumyra** [comment]
content PR https://github.com/mdn/content/pull/1216

**Comment by Rumyra** [comment]
Apart from review of the content and dev-doc-complete flag, my todo lists are done for this @chrisdavidmills

**Comment by chrisdavidmills** [comment]
Yay, set to dev-doc-complete. I'll ask Florian about what to do for the spec thing.

**Comment by Rumyra** [comment]
I believe this is done \o/ everything should be merged... I'm moving it 🆒

**Comment by chrisdavidmills** [comment]
Woo hoo!
