### ISSUE TITLE
Autocomplete attribute supports multiple values

### ISSUE THREAD

**Issue by jlous** [mdn/content#30706]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

### What information was incorrect, unhelpful, or incomplete?

no mention of support for multiple tokens

### What did you expect to see?

Documentation of the attribute supporting multiple space-separated values, except for "on" and "off", which must stand alone

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/autocomplete`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/autocomplete/index.md
* Last commit: https://github.com/mdn/content/commit/835d6632d59993861a0458510402787f8a2c3cb3
* Document last modified: 2023-10-25T17:27:32.000Z

</details>

**Comment by estelle** [comment]
didn't see this issue, but fixed it in https://github.com/mdn/content/pull/32789
