### ISSUE TITLE
Usage of {{AvailableInWorkers}} is not mentioned in writing-guide templates

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#30710]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types

### What information was incorrect, unhelpful, or incomplete?

1. the *Page_types* instructors doesn't mention the usage of macros `{{AvailableInWorkers}}` 

including:
https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_landing_page_template
https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_reference_page_template
https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_constructor_subpage_template
https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_property_subpage_template
https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_method_subpage_template
https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_event_subpage_template

neither in macros part https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Macros

~the position to place `{{AvailableInWorkers}}` macros may need to speificed, as it is under discussion~

*it seems that it reached a conclusion that, {{AvailableInWorkers}} should be placed as the top of the article*

2. the usage of `{{Compat}}` and `{{specifications}}` is not correct, it is no longer to passing parameters

3. the `{{Interface_Overview}}` in fact doesn't existed

### What did you expect to see?

add content of the usage of macros `{{AvailableInWorkers}}`

### Do you have any supporting links, references, or citations?

-

### Do you have anything more you want to share?

also notice https://github.com/mdn/yari/issues/10009 and https://github.com/mdn/yari/pull/10029, the content may need to reflect the change when they have done

reference to https://github.com/mdn/yari/blob/main/kumascript/macros/AvailableInWorkers.ejs

**Comment by hamishwillee** [comment]
Have you got a link to the discussion? 

Right now the `{{AvailableInWorkers}}` should be applied to every interface, function, property, method where it applies at the end of the first section (i.e. before Syntax). I think it should also appear in the API overview, but not in Using guides. This is how it has been done so far, and is fairly consistent.

This can be documented now. If it changes, following discussion we can update.

Did you want to take care of this?

**Comment by skyclouds2001** [comment]
> Have you got a link to the discussion?
> 
> Right now the `{{AvailableInWorkers}}` should be applied to every interface, function, property, method where it applies at the end of the first section (i.e. before Syntax). I think it should also appear in the API overview, but not in Using guides. This is how it has been done so far, and is fairly consistent.
> 
> This can be documented now. If it changes, following discussion we can update.
> 
> Did you want to take care of this?

I'd love to do this

**Comment by skyclouds2001** [comment]
> Have you got a link to the discussion?
> 
> Right now the `{{AvailableInWorkers}}` should be applied to every interface, function, property, method where it applies at the end of the first section (i.e. before Syntax). I think it should also appear in the API overview, but not in Using guides. This is how it has been done so far, and is fairly consistent.
> 
> This can be documented now. If it changes, following discussion we can update.
> 
> Did you want to take care of this?

emmm, currently I did not create a discussion yet

**Comment by hamishwillee** [comment]
> I'd love to do this

That would be great thank you.
I wouldn't create a discussion yet. This kind of thing is already being discussed in the bigger context of "all headers".

**Comment by skyclouds2001** [comment]
Since https://github.com/mdn/yari/pull/10029 is on working, this could be put afterwards until that work has been done

**Comment by Josh-Cena** [comment]
@skyclouds2001 I figured I could probably ask here, but was there a discussion on our usage of `{{AvailableInWorkers}}`? I find it kind of redundant to add this banner to each interface member—if the whole interface is exposed to workers, then surely each member is. There's no exception. It's not like the experimental status where you could ever have an interface not exposed but its members exposed.

**Comment by skyclouds2001** [comment]
> I figured I could probably ask here, but was there a discussion on our usage of `{{AvailableInWorkers}}`?

No, i believe there is no one (though https://github.com/orgs/mdn/discussions/650 maybe be related)

> I find it kind of redundant to add this banner to each interface member—if the whole interface is exposed to workers, then surely each member is. There's no exception.

No, there is a few cases that an interface and one of its property or method may have different scope expose.
For example: `StorageManager` for `Window` & `Worker` but `StorageManager.persist()` only of `Window` (https://storage.spec.whatwg.org/);
`MediaSource` for `Window` & `DedicatedWorker` but `MediaSource.handle` only for `DedicatedWorker`.
There is more cases in some interface like `WorkerNavigator`.

So I believe though in most cases it seems to be redundant, but it make sense
