### ISSUE TITLE
In the context of arguments, what exactly is "a list of <x>"?

### ISSUE THREAD

**Issue by DanKaplanSES** [mdn/content#30727]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/console

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/console#outputting_text_to_the_console

### What information was incorrect, unhelpful, or incomplete?

This is a question with the potential for a follow-up PR. It's about this paragraph, emphasis mine:

> There are two ways to use each of the output methods; you can pass in **a list of objects** whose string representations get concatenated into one string, then output to the console, or you can pass in a string containing zero or more substitution strings followed by a list of objects to replace them.

This might be overly pedantic, but my first interpretation of this phrase was `console.log([obj1, ... objN])`. I'm 99% sure it meant `console.log(obj1, ... objN)` instead (no array). I considered creating a PR to remove "the ambiguity," but I think I need clarity first, as this could just be my misunderstanding. 

1) Is this a situation where the English language is imprecise and it could mean both?
2) Was my initial interpretation incorrect?
3) Or does `a list of <x>` precisely mean passing `x1, ... xN` and not `[x1, ... xN]`?

Depending on the answer(s), I might attempt to clarify details in this paragraph and a couple of following sentences.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/console`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/console
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/console/index.md
* Last commit: https://github.com/mdn/content/commit/c367939020b2cbd60da7bd56a14670659d5e9491
* Document last modified: 2023-11-29T07:09:38.000Z

</details>

**Comment by hagenhaus** [comment]
Hi @DanKaplanSES, `console.log`, `console.info`, `console.warn`, `console.error`, and `console.debug` accept a variable number of arguments of **any data type**:

```
const s = 'String';
const b = true;
const n = 45;
const o = { name: 'Maple', genus: 'Acer' };
const a = ['Red', 'Yellow', 'Blue'];
console.log(s, b, n, o, a);
// Output:
// String true 45 { name: 'Maple', genus: 'Acer' } [ 'Red', 'Yellow', 'Blue' ]
```

So, _variable number of arguments_ seems more accurate to me than _list of objects_, and the former seems to render moot the ambiguity surrounding the phrase _list of whatever_.

To your point, when I read _list of arguments_, I think of this:

```
console.log(s, b, n, o, a);
```

But, I do think that some folks might interpret _list of whatever_ as an array.

**Comment by DanKaplanSES** [comment]
@hagenhaus 
> So, _variable number of arguments_ seems more accurate to me ...

Agreed. That's probably better than what I would've come up with, so I hope you don't mind me using it in [my PR](https://github.com/mdn/content/pull/31181).

**Comment by teoli2003** [comment]
Reopening per https://github.com/mdn/content/pull/31181#issuecomment-1865199080
