### ISSUE TITLE
Unwritten documentation of Permissions-Policy directives

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#30758]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy

### What information was incorrect, unhelpful, or incomplete?

- [ ] cross-origin-isolated

~here are many Permissions-Policy directives that have its browser compat data, but does not have its documentation yet~

~`attribution-reporting`~
~`browsing-topics`~

~here are also many Permissions-Policy directives that at least one browser platform, but does not have its browser compat data or documentation yet~

~here is two much so I do not list these here~

~> a list of supported Permissions-Policy directives of current browser can be tested via `document.featurePolicy.features()`~

### What did you expect to see?

.

**Comment by anushatomar13** [comment]
Hey @skyclouds2001 !
I would love to work on this issue. It would be great if you could please assign it to me!
Thanks!

**Comment by skyclouds2001** [comment]
> Hey @skyclouds2001 ! I would love to work on this issue. It would be great if you could please assign it to me! Thanks!

Sorry, I can't assign this issue to you, because I don't have the permission

But if you are eager to work on this issue, it's fine just to create a pull request that will fix this issue

**Comment by Josh-Cena** [comment]
- `attribution-reporting`: https://github.com/mdn/content/pull/33172
- `browsing-topics`: https://github.com/mdn/content/pull/30107

I have counted the following permission features available in Chrome by default that are not documented:

- `clipboard-read`
- `clipboard-write`
- `cross-origin-isolated`
- `interest-cohort`
- `join-ad-interest-group`
- `keyboard-map`
- `private-aggregation`
- `private-state-token-issuance`
- `private-state-token-redemption`
- `run-ad-auction`
- `shared-storage-select-url`
- `shared-storage`
- `sync-xhr`
- `unload`

Some are mentioned elsewhere while others are totally undocumented on MDN.

**Comment by hamishwillee** [comment]
FYI the clipboard API ones are a little complicated in that clipboard-read is not in the spec, and neither clipboard-read or write are intended to be implemented by Firefox. Covered here https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#security_considerations . I omitted docs for those when I did the rest of the API :-(.

**Comment by skyclouds2001** [comment]
> * cross-origin-isolated

I've fired https://github.com/mdn/browser-compat-data/issues/24843 to includes those Permissions-Policy directives that havn't added its data yet.

SO here I've update the list to show those that has bcd but haven't documented

**Comment by skyclouds2001** [comment]
seems cross-origin-isolated is the only one with bcd but without documetation, I'll close this issue
