### ISSUE TITLE
Canvas Tutorial, Images aren't always loaded before drawing to the canvas

### ISSUE THREAD

**Issue by MelissaLarsonHarney** [mdn/content#30782]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images

### What specific section or headline is this issue about?

"Example: Framing and Image" and "Art Gallery Example"

### What information was incorrect, unhelpful, or incomplete?

The images aren't checked to see if they're loaded before drawing to the canvas(es). This means that sometimes only a few images draw, sometimes none of the images in the examples draw. The first time I loaded the page, the art gallery example didn't draw the pictures or frames. This issue also happens if you click 'play' to open the examples in the Playground.

![image](https://github.com/mdn/content/assets/89538246/5930846c-63bc-446d-8891-60b240b897cb)

![image](https://github.com/mdn/content/assets/89538246/8e1d464d-1f52-4b03-a770-d24b1ea249a5)

### What did you expect to see?

The pictures drawing properly to the canvas.

### Do you have anything more you want to share?

I'm not sure if there is a better way to do this but, you could add an event listener to the window checking that it's been loaded before calling the draw() function?

window.addEventListener("load", (event) => {
  draw();
});

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvas_api/tutorial/using_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/using_images/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this one, I can also reproduce this. It might be good to use [image.complete ](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/complete) for this to check if an image is loaded and draw it, otherwise `image.onload` / addEventListener. I didn't have much luck with `window.addEventListener("load"...`
