### ISSUE TITLE
[XHR] Replace XMLHttpRequest with fetch() in Learn

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#30788]
Part of https://github.com/openwebdocs/project/issues/156.

I've just searched for `XMLHttpRequest` and got hits in the following pages under Learn:
- [x] [/learn/tools_and_testing/cross_browser_testing/javascript/](https://developer.mozilla.org/en-US/docs/learn/tools_and_testing/cross_browser_testing/javascript/)
- [x] [/learn/tools_and_testing/cross_browser_testing/accessibility/](https://developer.mozilla.org/en-US/docs/learn/tools_and_testing/cross_browser_testing/accessibility/) - false positive
- [x] [/learn/server-side/apache_configuration_htaccess/](https://developer.mozilla.org/en-US/docs/learn/server-side/apache_configuration_htaccess/) - false positive
- [x] [/learn/accessibility/wai-aria_basics/](https://developer.mozilla.org/en-US/docs/learn/accessibility/wai-aria_basics/)
- [x] [/learn/javascript/client-side_web_apis/](https://developer.mozilla.org/en-US/docs/learn/javascript/client-side_web_apis/) - false positive
- [x] [/learn/javascript/client-side_web_apis/fetching_data/](https://developer.mozilla.org/en-US/docs/learn/javascript/client-side_web_apis/fetching_data/) - false positive
- [x] [/learn/javascript/asynchronous/promises/](https://developer.mozilla.org/en-US/docs/learn/javascript/asynchronous/promises/) - false positive
- [x] [/learn/javascript/client-side_web_apis/introduction/](https://developer.mozilla.org/en-US/docs/learn/javascript/client-side_web_apis/introduction/) - false positive
- [x] [/learn/javascript/asynchronous/introducing/](https://developer.mozilla.org/en-US/docs/learn/javascript/asynchronous/introducing/) - false positive
- [x] [/learn/css/css_layout/practical_positioning_examples/](https://developer.mozilla.org/en-US/docs/learn/css/css_layout/practical_positioning_examples/)
- [x] [/learn/forms/](https://developer.mozilla.org/en-US/docs/learn/forms/)
- [x] [/learn/forms/sending_forms_through_javascript/](https://developer.mozilla.org/en-US/docs/learn/forms/sending_forms_through_javascript/)

**Comment by teoli2003** [comment]
🕺
