### ISSUE TITLE
<use> svg example is not respecting the stroke override

### ISSUE THREAD

**Issue by MadMango** [mdn/content#30832]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use

### What specific section or headline is this issue about?

The example section.

### What information was incorrect, unhelpful, or incomplete?

In the example, the third circle has `stroke="red"` but it's still blue.

### What did you expect to see?

I was expecting to see a red stroke.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/element/use`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/use/index.md
* Last commit: https://github.com/mdn/content/commit/32d1c9ff83019f8efae3e7987a55e83035e4b926
* Document last modified: 2023-08-25T22:38:09.000Z

</details>

**Comment by ShubhamOulkar** [comment]
@MadMango , `stroke='red'` is ignored because stroke was already set on myCircle shape. ` <circle id="myCircle" cx="5" cy="5" r="4" stroke="blue" />` so it is blue.

**Comment by ShubhamOulkar** [comment]
@MadMango, it's ok. Happen with every one  😊
