### ISSUE TITLE
Update `rgba()` and `hsla()` in prose and code to use latest syntax

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#30844]
In light of the latest syntax changes for [`rgb()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb) and [`hsl()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl) functions, we need to update occurrences of these functions in prose and code in the `mdn/content` repository.

### New syntax

The new syntax omits commas, uses a slash (/) to separate the alpha value, and expresses the alpha value as a percentage. The `rgba()` and `hsla()` functions have been replaced with `rgb()` and `hsl()`, respectively.

e.g., `rgba(0, 0, 0, 0.25)` is now `rgb(0 0 0 / 25%)`

### Related PRs

Other PRs related to this change covered the following areas:
- `mdn/css-examples` repository: mdn/css-examples#158
- Learn area in `mdn/content`: mdn/content#30604
- CSS ref articles under `web/css`: https://github.com/mdn/content/pull/31453

These PRs can be used as a reference to update the function occurrences.

### What's required

1. Update all instances of `rgba()` and `hsla()` to the new `rgb()` and `hsl()` syntax in the `mdn/content` repository.
2. Ensure that any content linking to code in other repositories is updated to reflect the new syntax.

**Note:** Some judgment calls will be required in certain cases. For example, in the directory `/en-us/mozilla/firefox/releases/`, some instances might need to be left as they are for historical context.

### Contributing to this issue

We're actively seeking the help of our contributors to assist us with this task. If you're interested in contributing, please feel free to ask any questions or request guidance if needed. We value and appreciate your help in keeping MDN content up-to-date!

**Comment by teoli2003** [comment]
Should we remove uses of `rgba()` too? (I've seen some left in css-examples at least)

That way all rgba() will be rgb() and all rgb() will have the new syntax (same for hsla/hsl)

**Comment by bsmth** [comment]
> Should we remove uses of `rgba()` too? (I've seen some left in css-examples at least)
> 
> That way all rgba() will be rgb() and all rgb() will have the new syntax (same for hsla/hsl)

That's covered in the list items in the requirements section 👍🏻

**Comment by Ojas13-git** [comment]
Is this issue closed? if not please can you assign it to me mam?

**Comment by dipikabh** [comment]
Thank you @ShubhamOulkar and @FormularSumo for your contributions to update MDN docs! 🙏

**Comment by FormularSumo** [comment]
Hi @dipikabh! I believe there are still a few more syntaxes in need of updating outside of the web area. For example, in the games area. I'm planning on doing them soon now that the previous PR updating the web area has been merged!

**Comment by dipikabh** [comment]
Thanks @FormularSumo, let's keep this issue open then

**Comment by FormularSumo** [comment]
I have one tiny query about _redirects that I've just asked on the above PR, otherwise I believe all legacy rgba() and hsla() syntaxes have now been updated where appropriate!

**Comment by FormularSumo** [comment]
Given that https://github.com/mdn/content/pull/32295 has been merged, I'm happy that all outdated uses of rgba() and hsla() have been removed and for this issue to be closed!
