### ISSUE TITLE
Add Default value to HTML attribute: maxlength

### ISSUE THREAD

**Issue by erosman** [mdn/content#30852]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength

### What information was incorrect, unhelpful, or incomplete?

Missing default value

### What did you expect to see?

Default value is 524,288

### Do you have any supporting links, references, or citations?

https://www.w3schools.com/tags/att_input_maxlength.asp

**Comment by skyclouds2001** [comment]
the standard on https://html.spec.whatwg.org/multipage/input.html#the-maxlength-and-minlength-attributes never mention the `maxlength` has a default value, is it true?

**Comment by Josh-Cena** [comment]
w3schools is outdated. Chrome used to set this non-standard upper bound but I believe they have since removed this default. We only document the spec on MDN, unless the reality is proven otherwise.
