### ISSUE TITLE
onDOMContentLoaded as referenced in the documentation but doesn't exist?

### ISSUE THREAD

**Issue by DanKaplanSES** [mdn/content#30861]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event#syntax

### What information was incorrect, unhelpful, or incomplete?

> ## Syntax
> 
> Use the event name in methods like {{domxref("EventTarget.addEventListener", "addEventListener()")}}, or set an event handler property.
> 
> ```js
> addEventListener("DOMContentLoaded", (event) => {});
> 
> onDOMContentLoaded = (event) => {};
> ```

I'm inferring from that last line of code that `onDOMContentLoaded` should exist in the global scope, but it isn't defined in Firefox or Chrome's console. 

![image](https://github.com/mdn/content/assets/373675/0a62c152-1842-424c-8c77-b7c09d7e5987)

### What did you expect to see?

I expected `onDOMContentLoaded` to exist on the page. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document/domcontentloaded_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/domcontentloaded_event/index.md
* Last commit: https://github.com/mdn/content/commit/367358d6847aa1766344951207dfd79d5c073a66
* Document last modified: 2023-08-04T07:15:35.000Z

</details>

**Comment by DanKaplanSES** [comment]
okay it appears that `onDOMContentLoaded` works as expected if you assign to it. I expected it to be like [`onload`](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event), where it defaults to `null` if it isn't explicitly assigned. This is an interesting difference between the two.

**Comment by Kaiido** [comment]
> okay it appears that `onDOMContentLoaded` works as expected if you assign to it. I expected it to be like [`onload`](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event), where it defaults to `null` if it isn't explicitly assigned. This is an interesting difference between the two.

No, there is no such thing as `onDOMContentLoaded`, you probably left an event listener while doing your tests.  
I'm asking for removal in https://github.com/mdn/content/pull/31723

**Comment by DanKaplanSES** [comment]
> > okay it appears that `onDOMContentLoaded` works as expected if you assign to it. I expected it to be like [`onload`](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event), where it defaults to `null` if it isn't explicitly assigned. This is an interesting difference between the two.
> 
> No, there is no such thing as `onDOMContentLoaded`, you probably left an event listener while doing your tests. I'm asking for removal in #31723

In that case, I'm confused about why it "works as expected" when you assign to it:

 ```html
<html>
  <head>
    <script>
      addEventListener("DOMContentLoaded", (event) => {
        alert(`onDOMContentLoaded`);
      });
    </script>
  </head>
  <body></body>
</html>
```

This gives me an alert when I open the file locally.

**Comment by Kaiido** [comment]
But your issue (and #31723) are about a supposed `window.onDOMContentLoaded`. Your snippet doesn't has it. 
Of course `addEventListener("DOMContentLoaded")` works.

**Comment by DanKaplanSES** [comment]
> But your issue (and #31723) are about a supposed `window.onDOMContentLoaded`. Your snippet doesn't has it. Of course `addEventListener("DOMContentLoaded")` works.

Bah, sorry! Yes you are right; I got confused.
