### ISSUE TITLE
Example code does not work

### ISSUE THREAD

**Issue by devaw-de** [mdn/content#30881]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/returnValue

### What specific section or headline is this issue about?

examples

### What information was incorrect, unhelpful, or incomplete?

The supplied code does not work as intended.
The log does not update when a selection in the form is made.
Clicking the input element of type `submit` with the name `Xbutton` works as intended.
Clicking the button of type `submit` labeled `Confirm` does not update the log as described in the article.

### What did you expect to see?

The selection of the form `favAnimal` should be displayed.

### Do you have anything more you want to share?

I suspect this might not be a problem with the documentation but with the implementation of `returnValue`.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmldialogelement/returnvalue`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/returnValue
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmldialogelement/returnvalue/index.md
* Last commit: https://github.com/mdn/content/commit/5ce6d5b38ec46374bbbf50b84b6105b5d1750911
* Document last modified: 2023-08-13T22:45:58.000Z

</details>

**Comment by caugner** [comment]
Hi @devaw-de, what makes you think that the `returnValue` should include the value of `favAnimal`?

As far as I can see in Firefox, the `returnValue` contains the content of the `value="..."` attribute of the triggered submit buttons (`confirmBtn` for the "Confirm" button", and `X` for the "X" button), whereas triggering the reset button ("Reset")` does not influence the dialog's `returnValue`. This looks like it is in accordance to what is explained above the example:

> The following example displays a button to open a {{htmlelement("dialog")}} containing a form via the `showModal()` method.
> The script assigns the `returnValue` an initial value of `initialValue`.
> The confirm button (`confirmBtn`) submits the form with validation and the "X" button submits the form without validation. Submitting a form with a `method="dialog"` closes the dialog and sets the return value to the `value`, if any, of the `button` or `input` elements of `type=submit`.
> The reset button has an event handler that closes the dialog; it has no impact on the `returnValue`. Neither does closing the dialog with the <kbd>Esc</kbd> key.
