### ISSUE TITLE
Issue with "prefers-reduced-motion": (short summary here please)

### ISSUE THREAD

**Issue by Dani3lNL** [mdn/content#3088]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

#### What information was incorrect, unhelpful, or incomplete?
the media-feature is **not** present anymore in FF 86.0.1...

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/@media/prefers-reduced-motion`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@media/prefers-reduced-motion/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by rachelandrew** [comment]
@Dani3lNL I'll need some more information as I just tested this in Firefox on Windows and it works as expected, Firefox supports the `prefers-reduced-motion` media feature.

**Comment by Dani3lNL** [comment]
Sorry, had forgotten that the feature had to be added manually, closed.
