### ISSUE TITLE
Missing examples for decimal alignment in table

### ISSUE THREAD

**Issue by ricardo-reis-1970** [mdn/content#30889]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-align

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The examples are all trivial and virtually need not be there. Start, center, or justify are notions all of us have quite honed, and these pages are typically not for non-tech people, dare I say.

However, the single most demanding example, alignment of numbers in a column by their decimal point, is blatantly missing. A mention is made to add this to the cell elements and... my browser (Chrome 120, Debian 12, Gnome 43) is simply ignored with a ⚠️ and a message of "Invalid property value."when I try a character:
```css
table tbody tr td {
  text-align: "." right;
}
```

It's everythinbg but clear where to apply this CSS rule. I tried all the way up to applying it to `table`, to the same result. Should I be applying this to a table `col` instead? This would make sense, but it should also be in the documentation, as it is mentioned.

### What did you expect to see?

Either an example of aligning by `<string>` or a link to one.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/text-align`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/text-align/index.md
* Last commit: https://github.com/mdn/content/commit/b82ff59aab7883b7bb2222cf9f9f9b6eed818e08
* Document last modified: 2023-02-21T06:13:19.000Z

</details>

**Comment by OnkarRuikar** [comment]
> The examples are all trivial and virtually need not be there. Start, center, or justify are notions all of us have quite honed, and these pages are typically not for non-tech people, dare I say.

Yes, the target audience is very broad including students and beginners.

> However, the single most demanding example, alignment of numbers in a column by their decimal point, is blatantly missing.

The "current" (implemented by all the browsers) version of the spec is `CSS Text Module Level 3` it [doesn't include `<string>` value](https://drafts.csswg.org/css-text/#text-align-property). [No browser has implemented](https://wpt.fyi/results/css/css-text/text-align?label=experimental&label=master&aligned) the `<string>` yet. So, working example can't be provided at the moment.

The `<string>` value [is being proposed in the next version](https://drafts.csswg.org/css-text-4/#text-align-property) of the draft spec `CSS Text Module Level 4`. And this is how it will look: https://drafts.csswg.org/css-text-4/#example-6a3cc5d3 . The draft versions of specs undergoes a lot of changes till they get implemented so there is no point in documenting such feature ahead of time.

**Comment by caugner** [comment]
I find it confusing that the [Syntax section](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align#syntax) contains examples for this, although neither the Formal syntax nor the BCD data mention this experimental feature. Shouldn't those be removed or at least accompanied by a disclaimer?

https://github.com/mdn/content/blob/accea788eb69e095eb351563de2a2a1bae59143d/files/en-us/web/css/text-align/index.md#L27-L29

**Comment by OnkarRuikar** [comment]
> Shouldn't those be removed or at least accompanied by a disclaimer?

These were documented in Wiki Era in html docs. I guess we didn't have a rule before to not document un-implemented features.

I think we should remove this from syntax.
