### ISSUE TITLE
Error.prototype.stack: non-standard but universally supported

### ISSUE THREAD

**Issue by sidewayss** [mdn/content#30906]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack

### What specific section or headline is this issue about?

The red Non-standard block at the very top of the page

### What information was incorrect, unhelpful, or incomplete?

It needs clarity, and leading with the red block is misleading because the feature is fully supported by every browser listed at the bottom of the very same page. Yes, it is not in the spec, at least not in [the document linked](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-error-objects) in the MDN page for the `Error` object. But it is supported everywhere except the more minor mobile browsers, where [caniuse.com lists support as "unknown"](https://caniuse.com/?search=stack).

### What did you expect to see?

I would prefer to see this Non-standard notice at the bottom of the page, directly above the Browser Compatibility section. I would also prefer to see additional text that explains the wide support but lack of a defined standard.  Browser Compatibility already has a warning about non-standard, in addition to this red block. If support is really so wide, maybe the block shouldn't be red?

I submit this as an issue because I don't know what MDN policy is for something like this.  I can submit a PR to make changes to this, if someone authorized here deems it worthy of change.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/error/stack`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/error/stack/index.md
* Last commit: https://github.com/mdn/content/commit/5c3c25fd4f2fbd7a5f01727a65c2f70d73f1880a
* Document last modified: 2023-09-12T04:14:14.000Z

</details>

**Comment by hamishwillee** [comment]
The note is strictly accurate - the stack is not part of any specification. I take your point though.
IMO the heading should stay where it is (mostly because this is policy and we might automate insertion at some point). IT would be reasonable to have another note immediately below that states that while non-standard this is broadly supported.

@wbamberg @teoli2003 Do you have a view?

**Comment by sidewayss** [comment]
> IT would be reasonable to have another note immediately below that states that while non-standard this is broadly supported.

That sounds like what @Josh-Cena did in #30908, along with a link to the proposed standard.

**Comment by hamishwillee** [comment]
Ah, yes it does. Somehow missed seeing Josh's PR.
