### ISSUE TITLE
What "The options parameter" means in "Browser compatibility" section

### ISSUE THREAD

**Issue by SeifESlimene** [mdn/content#30911]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

import keyword has only one parameter which is "moduleName" so what does the "The options parameter" means here?

### What did you expect to see?

nothing about these stuff appears in the "Browser compatibility" section because it's not relevant.

### Do you have any supporting links, references, or citations?

No, just asking for clarification.

### Do you have anything more you want to share?

Nothing more.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/import`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/import/index.md
* Last commit: https://github.com/mdn/content/commit/3918b803fda416a26fc2b7a62976d2cd87187460
* Document last modified: 2023-12-06T23:05:33.000Z

</details>

**Comment by Josh-Cena** [comment]
See https://github.com/mdn/content/issues/29572. Closing in favor of that!

**Comment by SeifESlimene** [comment]
Sorry but I don't see any answer related to my question!

**Comment by Josh-Cena** [comment]
This parameter is part of the import attributes feature. You can read it here: https://github.com/tc39/proposal-import-attributes That issue is tracking the inclusion of this feature in the docs.
