### ISSUE TITLE
Add Some Explanation And Example

### ISSUE THREAD

**Issue by samcode-web-hi-you** [mdn/content#30916]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/background-color

### What specific section or headline is this issue about?

Lack Of Explanation

### What information was incorrect, unhelpful, or incomplete?

Explanation On Each Codition They Aren't Available Like For Global Value And What Is HSL HSLA Or HWB. Also % (prcentage) Isn't Defined Well, 
 

### What did you expect to see?

I Think Little Explanation Will Help New Users Or New Comers To Get Better Learning And Understanding.

### Do you have any supporting links, references, or citations?

Not Like I Have Fully Known Website Or Area Where Everything Is Expalined Completely But I Want MDN To Do So.  So That New User Will Get To Learn Everything In Betterr Way Without Searching For A Terminology Or Terms.

### Do you have anything more you want to share?

They Can Simply Come To MDN And Get Everything Without The Help Of Google Or Any Other Website.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/background-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-color
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/background-color/index.md
* Last commit: https://github.com/mdn/content/commit/2adfb8760ac42c80966080e2e84211b14e43b589
* Document last modified: 2023-07-18T00:15:42.000Z

</details>

**Comment by Josh-Cena** [comment]
The description comes from https://developer.mozilla.org/en-US/docs/Web/CSS/color_value. We don't want to duplicate explanations.
