### ISSUE TITLE
Unlike stated, Chrome disallows URL authentication credentials only in subresources and not always (and thus is not stricter than Firefox)

### ISSUE THREAD

**Issue by wichmannpas** [mdn/content#30921]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication

### What specific section or headline is this issue about?

Access using credentials in the URL

### What information was incorrect, unhelpful, or incomplete?

It states that Chrome strips out authentication credentials from the URL (citing a Chrome issue that does not state that), thus implying that Chrome was stricter than Firefox. In fact, Chrome does so only for URLs in subresources (https://codereview.chromium.org/2651943002). When a user manually enters a URL with auth credentials, Chrome opens it, respects the credentials and does not even show a warning (unlike Firefox).

### What did you expect to see?

Either a more precise wording, or a better example that is indeed stricter than Firefox.

### Do you have any supporting links, references, or citations?

https://codereview.chromium.org/2651943002

Unfortunately, I did not yet find any useful and reliable resources for further browsers. Apparently, Internet Explorer has been stricter here, but that is clearly not a relevant reference anymore as well.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/authentication`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/authentication/index.md
* Last commit: https://github.com/mdn/content/commit/592f6ec42e54981b6573b58ec0343c9aa8cbbda8
* Document last modified: 2023-07-25T00:27:48.000Z

</details>

**Comment by bsmth** [comment]
Thanks @wichmannpas - I think the linked PR resolves the issue, what do you think?

**Comment by wichmannpas** [comment]
Thanks for merging! Yes, I think so, too. Should your suggestion to use a more browser-neutral wording be tracked in another issue?
