### ISSUE TITLE
British Library website is down since November '23

### ISSUE THREAD

**Issue by bsmth** [mdn/content#30929]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML#understanding_license_types

### What specific section or headline is this issue about?

All rights reserved

### What information was incorrect, unhelpful, or incomplete?

https://www.bl.uk/ website is down from an ongoing DDoS. The following article URL leads to a placeholder: https://www.bl.uk/business-and-ip-centre/articles/fair-dealing-copyright-explained

### What did you expect to see?

A working external resource

### Do you have any supporting links, references, or citations?

>Our website is currently unavailable
Last updated: 6pm on Friday, 8 December 2023.
> We're experiencing a major technology outage following a cyber-attack affecting our website, online systems and services, and some onsite services. However, our buildings are still open as usual. We anticipate restoring more services in the next few weeks, but disruption to certain services is now expected to persist for several months.

**Comment by hamishwillee** [comment]
@bsmth What's this issue supposed to achieve? I mean reading this it looks like you want to see https://www.bl.uk/ up and running, but that is outside the control of anyone reading this issue. 

It's supposed to be temporary and if you can't trust the British Library who can you trust. So I'd assume we just live with the broken link until it gets fixed.

**Comment by bsmth** [comment]
> What's this issue supposed to achieve? 

Well, now it's a "known issue".

> So I'd assume we just live with the broken link until it gets fixed.

We can do. It's a broken outbound link since a while now, if it turns out to be not-so-temporary, we can remove or replace it.

**Comment by hamishwillee** [comment]
Meh. I'd rather _not_ know about this "known issue" :-). Unless perhaps the "What did you expect to see?" is changed to something actionable by someone in this community - such as "delete the link"

**Comment by bsmth** [comment]
Righto! I've opened a PR (linked) to swap it out for an alternative instead.
