### ISSUE TITLE
State explicitly that robots.txt and noindex are not alternatives

### ISSUE THREAD

**Issue by SethFalco** [mdn/content#30955]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name#other_metadata_names

### What specific section or headline is this issue about?

Other metadata names

### What information was incorrect, unhelpful, or incomplete?

This problem is more about interpretation than the content itself, but I think the content could be reworded to bring more clarity to the differences between using `robots.txt` and `noindex`.

The following statement gave me the impression that `robots.txt` can be used as an alternative to values like `noindex`:

> The robot still needs to access the page in order to read these rules. To prevent bandwidth consumption, use a [_robots.txt_](https://developer.mozilla.org/en-US/docs/Glossary/Robots.txt) file.
> 
> — https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name#other_metadata_names

"these", referring to `index`, `noindex`, `follow`, and `nofollow`.

### What did you expect to see?

First, I think it'd be better to say the following rather than instructing the user to use `robots.txt`, which makes clearer it's something to investigate and not a clear path forward.

> To prevent bandwidth consumption, consider using a [_robots.txt_](https://developer.mozilla.org/en-US/docs/Glossary/Robots.txt) file.

It would also help to explicitly clarify that `robots.txt` is not always a replacement for `noindex` and `nofollow`, etc.

The `robots.txt` file is exclusively for the crawlability of a page, and not an indicator of what a crawler would otherwise do with URLs to that page if found another way.

One notable difference being that appearing in `robots.txt` doesn't mean it won't appear in search results, just that the page itself won't be crawled for metadata, so search engines can't populate the description etc. It can still discover the URL and index it via crawling other first or third-party pages, or through the site's own `sitemap.xml`.

I think a good way to approach this would be to have two lists, when to prefer `robots.txt` and when not to prefer `robots.txt`.

### Do you have any supporting links, references, or citations?

It would be nice to add a warning that effectively clarified the following information:

> **Warning**: Don't use a robots.txt file as a means to hide your web pages (including PDFs and other text-based formats supported by Google) from Google search results. 
> 
> If other pages point to your page with descriptive text, Google could still index the URL without visiting the page. If you want to block your page from search results, use another method such as password protection or [**noindex**](https://developers.google.com/search/docs/crawling-indexing/block-indexing).
> 
> **If your web page is blocked with a robots.txt file**, its URL can still appear in search results, but the search result will [not have a description](https://support.google.com/webmasters/answer/7489871).
> 
> — https://developers.google.com/search/docs/crawling-indexing/robots/intro#what-is-a-robots.txt-file-used-for

**Comment by bsmth** [comment]
Thanks a lot for the suggestion @SethFalco - would you like to open a pull request to clarify this?
