### ISSUE TITLE
Wrong descriptiotn of one-time-code

### ISSUE THREAD

**Issue by jackyhallyday** [mdn/content#30952]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

### What specific section or headline is this issue about?

Values

### What information was incorrect, unhelpful, or incomplete?

"one-time-code"
A one-time password (OTP) for verifying user information, most commonly a phone number used as an additional factor in a sign-in flow.

### What did you expect to see?

It's not a phone number, but a code received by SMS, e-mail or in a phone app.

### Do you have any supporting links, references, or citations?

Webkit (https://webkit.org/blog/14787/webkit-features-in-safari-17-2/'):
"Previously supported in Safari through other technology, the ability to have input fields that suggest **_received one-time codes_** is now available in WKWebView for iOS 17.2 and iPadOS 17.2."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/autocomplete`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/autocomplete/index.md
* Last commit: https://github.com/mdn/content/commit/835d6632d59993861a0458510402787f8a2c3cb3
* Document last modified: 2023-10-25T17:27:32.000Z

</details>

**Comment by anushatomar13** [comment]
Hey @jackyhallyday ! I would love to work on this issue. It would be great if it could be assigned to me.
Thanks!

**Comment by hamishwillee** [comment]
Thanks for this. I've fixed it in https://github.com/mdn/content/pull/31012 

FYI @anushatomar13 on MDN we no longer directly assign issues. Instead, if you create a PR to fix the problem, and link it by having `Fixes #30952` in the PR description, you have effectively self-assigned it to yourself :-). Before taking an issue you should check there is no PR already created.
