### ISSUE TITLE
Showing XML Error instead of embeded content

### ISSUE THREAD

**Issue by dorfsmay** [mdn/content#30962]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Groups_and_backreferences

### What specific section or headline is this issue about?

"Try it" section at the top

### What information was incorrect, unhelpful, or incomplete?

Instead of showing an interactive example it shows an XML Error:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
</Error>
```

### What did you expect to see?

An interactive example.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions/groups_and_backreferences`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Groups_and_backreferences
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/groups_and_backreferences/index.md
* Last commit: https://github.com/mdn/content/commit/c6f0f106b9083984dbf597678def6561729bb459
* Document last modified: 2023-09-07T01:22:04.000Z

</details>

**Comment by bsmth** [comment]
Thanks for raising this one. It looks like the example's been renamed:

https://github.com/mdn/interactive-examples/commit/a5d0158962a94d764e8a72a6fda19b368a1c68f8

Should be 

```diff
- regexp-groups-ranges.html
+ regexp-groups-backreferences.html
```
