### ISSUE TITLE
Unwritten documentation of CSP directives (fenced frames - `fenced-frame-src`)

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#30960]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

### What information was incorrect, unhelpful, or incomplete?

the documentation of `fenced-frame-src` content security policy directive has added browser compat data yet, but its documentation hasn't been written yet

### What did you expect to see?

-

**Comment by anushatomar13** [comment]
Hey @skyclouds2001 ! I would love to work on this issue. It would be great if it could be assigned to me!
Thanks!

**Comment by hamishwillee** [comment]
@skyclouds2001 @anushatomar13 No one assigns anything anymore on MDN. 

- If you want to work on something you create a PR  and in the new PR description you have the link `Fixes <#id-of-associated-issue>`. That creates a link that fixes this issue when the PR is merged and is visible on the issue.
- If you're thinking about taking an issue you first check if such a PR is already linked.
- If you're creating an issue that you plan on working on, then you can add a note saying you want to work on it in the issue to "kind of" reserve it.

**Comment by bsmth** [comment]
⚠️ Heads-up @anushatomar13 and others, this is being worked on at https://github.com/mdn/content/pull/30874

You should track the progress of the PR by @chrisdavidmills to avoid having your valuable time lost through duplicating work! I hope that helps :)

**Comment by skyclouds2001** [comment]
> ⚠️ Heads-up @anushatomar13 and others, this is being worked on at #30874
> 
> You should track the progress of the PR by @chrisdavidmills to avoid having your valuable time lost through duplicating work! I hope that helps :)

Thanks for noticing, since it is on working, this issue could be finely closed
