### ISSUE TITLE
Issue with "Number.isFinite()": …

### ISSUE THREAD

**Issue by guganems** [mdn/content#310]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite

#### What information was incorrect, unhelpful, or incomplete?
It also checks whether the Number is NaN or not. Since typeof NaN is Number, I think it should be noticed, that Number.isFinite not only checks if the number is positive or negative infinity, also it's, let's say, numberness.

#### Specific section or headline?
The problem I think found is in the method definition

#### What did you expect to see?
The Number.isFinite() method determines whether the passed value is a finite number — that is, it checks that a number is neither positive nor negative Infinity since JavaScript has both. Also, it checks that number is not NaN.

#### Did you test this? If so, how?
I tested it like that:
console.log(Number.isFinite(NaN));

and the result was -> false

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/number/isfinite`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/number/isfinite/index.html
* Report started: 2020-12-16T17:00:49.726Z

</details>

**Comment by Elchi3** [comment]
Fixed by https://github.com/mdn/content/pull/990
