### ISSUE TITLE
::cue - Try it - Need for explanation

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#31009]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::cue

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/::cue#try_it

### What information was incorrect, unhelpful, or incomplete?

Hello,

I've copied the "Try it" example to my laptop.
The HTML, CSS, mp4 and vtt files are in the same directory.

When I run the HTML file, I get this error message (see attachment).
What could be the explanation?

Thanks for your feedback.

![cue Capture](https://github.com/mdn/content/assets/95876663/3ec53bca-957b-4dd8-b548-0be7ad40f8aa)

### What did you expect to see?

Be able to view subtitles

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_doublecolon_cue`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::cue
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_cue/index.md
* Last commit: https://github.com/mdn/content/commit/5fea7c9593f5e4b4ef13ec65064acf1eabf01e4e
* Document last modified: 2023-02-21T06:49:52.000Z

</details>

**Comment by OnkarRuikar** [comment]
The [`src` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track#src) on `<track>` requires a URL with same origin. This depends on the value of [`crossorigin`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) attribute.

Browsers tend to give very few privileges to resources loaded from local disk. So resources from 'null' origin are not allowed.

I suggest you run `python3 -m http.server` in the directory containing the html file and open `http://0.0.0.0:8000/` in a browser.
