### ISSUE TITLE
No information about "cancel" event on HTMLInputElement page

### ISSUE THREAD

**Issue by Cipscis** [mdn/content#31014]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

### What specific section or headline is this issue about?

Events

### What information was incorrect, unhelpful, or incomplete?

The "cancel" event for the HTMLInputElement, which is fired when a picker for an input element with type "file" is cancelled without the value being changed, is not mentioned anywhere on the HTMLInputElement page.

### What did you expect to see?

The HTMLInputElement page should mention the "cancel" event, and link to its documentation.

### Do you have any supporting links, references, or citations?

The "cancel" event for `<input type="file">` elements was added to the HTML standard in July 2021: https://github.com/whatwg/html/pull/6735

[HTML spec - cancel event](https://html.spec.whatwg.org/#event-cancel)
[HTML spec - Common input element APIs](https://html.spec.whatwg.org/#common-input-element-apis)

This feature has been supported by all modern browsers since May 2023. According to CanIUse, it currently has 83.62% global browser support. Support for this feature is already included in mdn/browser-compat-data and displays on the HTMLInputElement page.

**Comment by bsmth** [comment]
As far as I remember, this is under https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/cancel_event

`HTMLElement` instead of specifically `HTMLInputElement`, although BCD puts it under HTMLInputElement`: https://github.com/ntdiary/browser-compat-data/blob/main/api/HTMLInputElement.json#L201-L239

**Comment by bsmth** [comment]
Indeed, there's a larger discussion about where this should live in https://github.com/mdn/content/pull/30946

**Comment by dipikabh** [comment]
Related issue on BCD open here: https://github.com/mdn/browser-compat-data/issues/21585

**Comment by dipikabh** [comment]
Hello @Cipscis, pinging to check if you'd be interested in opening a PR as per the approach proposed in https://github.com/mdn/content/pull/30946#issuecomment-1862136744.

**Comment by skyclouds2001** [comment]
I notice #28639, which tend to add the `cancel` event to `<input>` element, where move the `cancel` event from `HTMLDialogElement` to `HTMLInputElement`

**Comment by Josh-Cena** [comment]
Related: https://github.com/mdn/content/issues/31910

**Comment by Josh-Cena** [comment]
So is the conclusion to keep the page at `HTMLElement`? I'm not sure what the conclusion is or if we reached one.

**Comment by dipikabh** [comment]
The conclusion from https://github.com/mdn/content/pull/30946 was to keep the event with the defining interface `HTMLElement`.

I agree with the proposal in https://github.com/mdn/content/pull/30946#issuecomment-1862136744, that is:
- Just like on the [`<video>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#events) page, add Events tables to [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) and [`<dialog>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) pages.
- Add links on [`HTMLInputElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) and [`HTMLDialogElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement) pages to the `cancel` event, describing when it is fired. Readers are often looking for the event info on these subclasses.

    For example, the `cancel` event info has been added to the [`<input type="file">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#detecting_cancellations) page via [pull/29639](https://github.com/mdn/content/pull/29639/files#diff-4910910cd74414f4ea72536a41fa5ffe6e457e71e7e5e69e8f7297ea7bba9354). Similar info or links need to be added to `HTMLInputElement` and `HTMLDialogElement` pages for improving discoverability.

**Comment by Josh-Cena** [comment]
I'm not _entirely_ sure if documenting events in the HTML reference is a good idea since you are almost always listening for events in JS instead of HTML, but if we already have that precedent it sounds reasonable.

**Comment by Josh-Cena** [comment]
I, by chance, cycled back to this issue. I strongly believe the page move in https://github.com/mdn/content/pull/29639 should be reverted and we should have separate `cancel` pages for `HTMLInputElement` and `HTMLDiaglogElement`. They have entirely different firing conditions and behaviors, causing issues such as https://github.com/mdn/content/issues/31910. They even have separate BCD entries. I don't see reasons to conflate them.

**Comment by FurryR** [comment]
:+1: Agree. I think I've made a mistake, therefore we do really need these two pages to be separated.

**Comment by skyclouds2001** [comment]
* HTMLInputElement (type = 'file')

  * fired when user does not change file selection
  * bubble = true
  * cancelable = false

![image](https://github.com/user-attachments/assets/63220a9a-b9be-49d8-a8c5-a9571f8ff8ee)

* HTMLDialogElement

  * fired when dialog close
  * bubble = false
  * cancelable = true

![image](https://github.com/user-attachments/assets/a57e0d99-67fd-4709-b15f-a947a4dcb842)
