### ISSUE TITLE
Issue with "JavaScript basics": (myHeading.textContent should be changed to myHeading.innerHTML)

### ISSUE THREAD

**Issue by rogomichael** [mdn/content#3102]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics

#### What information was incorrect, unhelpful, or incomplete?
The code did not run as expected

#### Specific section or headline?
myHeading.textContent = 'Mozilla is cool, ' + storedName;
myHeading.textContent = `Mozilla is cool, ${myName}`;

#### What did you expect to see?
I expected to see a response in the page due to JS code addition

#### Did you test this? If so, how?
I tested it on several browsers and it did not work! Until I checked the source code on Github!

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/javascript_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/javascript_basics/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Please be more specific about what you mean by *“The code did not run as expected”*.

1. What is the behavior you expected?
2. What is the actual behavior you see instead?
3. What are the exact error messages that the browser logs in the devtools console?

**Comment by chrisdavidmills** [comment]
@rogomichael I've tested this code many times, and it definitely works. Try checking your version against our finished version to see what might be different:

Live version: https://mdn.github.io/beginner-html-site-scripted/
Source code: https://github.com/mdn/beginner-html-site-scripted/blob/gh-pages/scripts/main.js

**Comment by sideshowbarker** [comment]
Closing for lack of response
