### ISSUE TITLE
Anchor link by anchor id # doesn't focus the link in view on loading webpage

### ISSUE THREAD

**Issue by cargilcm** [mdn/content#31037]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/File_System_API#api.filesystemfilehandle

### What specific section or headline is this issue about?

Api fillesystemhandle

### What information was incorrect, unhelpful, or incomplete?

The href id may not be in the source code

### What did you expect to see?

If you tap on the header it causes the page to scroll to that link/header

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/File_System_API#api.filesystemfilehandle

### Do you have anything more you want to share?

support for api.FileSystemFileHandle is interesting, major browsers supporting it but only way to access it (ie thru window.showOpenFilePicker()) is non existent in the same browsers

**Comment by hamishwillee** [comment]
All headings on MDN automatically get an anchor based on their name and area also set as a link target to that same id. This makes it very easy to determine the appropriate anchor URL by just clicking on the heading. In the particular case of https://developer.mozilla.org/en-US/docs/Web/API/File_System_API#api.filesystemfilehandle if you click the heading, that is indeed navigating back to this heading. If you look at the source you can see the id and the href.

![image](https://github.com/mdn/content/assets/5368500/1fc54156-b630-422c-90c1-3b78f584e0b0)

So the behaviour that you are describing (I think) is expected. Closing as not a defect.

**Comment by cargilcm** [comment]
Thanks, should have been able to incorrect the code myself and see this. Oddly, on my Motorola 5g phone, with chrome 120.0.6099.115 the URL that refers to the anchor id "api.filesystemhandle" (https://developer.mozilla.org/en-US/docs/Web/API/File_System_API#api.filesystemfilehandle) does not bring the headline into view or cause any scrolling whatsoever. 

I'm not familiar with the internals of how mobile browsers work but Firefox for Android loads the page with the headline in focus correctly.

Firefox details:
120.1.1 (Build #2015990546), 287644eb76+
GV: 120.0.2-20231208211905
AS: 120.0.2

![Screenshot_20231217-184835.png](https://github.com/mdn/content/assets/332197/a2b5c263-f8a6-4fe0-8d6b-8f9e70ceba02)

![Screenshot_20231217-184842.png](https://github.com/mdn/content/assets/332197/44b6a4e9-f1fa-40fc-bdf7-f8fa978f0eb6)

**Comment by hamishwillee** [comment]
Thanks. If browsers don't do the "right thing" with this valid HTML that's a browser issue, not an MDN issue :-)
