### ISSUE TITLE
Filling in test details on LambdaTest programmatically Section Confusion

### ISSUE THREAD

**Issue by ShamarYarde** [mdn/content#31074]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment

### What specific section or headline is this issue about?

Filling in test details on LambdaTest programmatically

### What information was incorrect, unhelpful, or incomplete?

The entire section looks like it implies that the commands should be ran inside a Bash terminal shell instead of it being another line of code inside the `lambdatest_google_test.js` file after the `driver` object has been created.

### What did you expect to see?

A successful result after running either `driver.executeScript("lambda-status=passed");` or `driver.executeScript("lambda-status=failed");` inside a Bash terminal shell.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.md
* Last commit: https://github.com/mdn/content/commit/d2402a11e1289b811e11883e5e126657357b84c7
* Document last modified: 2023-12-15T03:41:27.000Z

</details>

**Comment by hamishwillee** [comment]
I'm not sure I read it that way - I mean it starts with an example that you are supposed to copy into a file. 

I think I'd need to see a PR to understand this.

**Comment by ShamarYarde** [comment]
@hamishwillee I created the [corrected misleading text](https://github.com/mdn/content/pull/31092#issuecomment-1859511160) PR with I thought was supposed to happen.
