### ISSUE TITLE
[CSS] motion 1 - offset

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#31099]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

Grouping these as they're related and all shipping bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1598151
https://bugzilla.mozilla.org/show_bug.cgi?id=1598152
https://bugzilla.mozilla.org/show_bug.cgi?id=1598159

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by dipikabh** [comment]
Tasks for this issue:

- Update BCD for:
   (Note: Cross-check updates in https://github.com/mdn/browser-compat-data/pull/21678) 
  - [ray()](https://developer.mozilla.org/en-US/docs/Web/CSS/ray#browser_compatibility)
  - [offset-position](https://developer.mozilla.org/en-US/docs/Web/CSS/offset-position#browser_compatibility)
  - [basic-shape, coord-box, url() in offset-path](https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path#browser_compatibility)
- Add to release notes
- Remove from [experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features): ray(), offset-position, url()
- Remove experimental banner from [ray()](https://developer.mozilla.org/en-US/docs/Web/CSS/ray)
