### ISSUE TITLE
[WebAPI] showPicker method doesn't work on week and month input

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#31097]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1853797

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by Rumyra** [comment]
@hamishwillee I'm assigning to you as you've already touched this one - seems it has been fixed, so can update bcd

**Comment by hamishwillee** [comment]
Actually this went into FF121 - Originally this looked like a bug fix (and it is) but because this was never recorded as supported it "counts" as a release. I've added relnote.

Status

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/21577
- [ ] Release note #31132
- [ ] dev-docs-complete
