### ISSUE TITLE
[Nightly][JS] Add Intl.Segmenter API

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#31098]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1423593

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
@Josh-Cena Is this something you're interested in doing the "actual work" for? I can take care of release note etc

**Comment by Josh-Cena** [comment]
This has been shipped in other browsers for years, so I believe there's no content work; you can take care of browser compat etc. and do a sanity check on the docs. I can review any content changes if necessary.

**Comment by hamishwillee** [comment]
Thanks @Josh-Cena - I didn't even look at it before you asked which was dumb. No work for you.

**Comment by hamishwillee** [comment]
This is nightly only. It is already well documented so mostly just BCD and experimental features.

Status

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/21711
- [ ] Docs
- [ ] Experimental features
- [ ] dev-docs-complete

**Comment by pepelsbey** [comment]
I wonder if it’s a Nightly only or will be enabled by default in 122, [see my question](https://bugzilla.mozilla.org/show_bug.cgi?id=1423593#c57)

**Comment by bsmth** [comment]
Everything looks complete for this so I'm closing as done. Thanks all!
