### ISSUE TITLE
Issue with "PUT API": …

### ISSUE THREAD

**Issue by nschonni** [mdn/content#311]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Tools/PUT_API

#### What information was incorrect, unhelpful, or incomplete?

This speaks more to the old Wiki setup that no longer applies with the migration. Probably better to just delete

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/tools/put_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Tools/PUT_API
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/tools/put_api/index.html
* Report started: 2020-12-16T17:26:21.936Z

</details>

**Comment by sideshowbarker** [comment]
Agreed it seems that should just be deleted.

**Comment by jpmedley** [comment]
The point is probably moot, but I was told three years ago that the PUT API had long since been disabled.

**Comment by chrisdavidmills** [comment]
Closing, as I've deleted this page in https://github.com/mdn/content/pull/1098
