### ISSUE TITLE
N.A. [HTTP] Enable DefaultURI use for unknown schemes

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#31100]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1603699

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [ ] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
This looks like an effectively "internal" change to me. I am querying in https://bugzilla.mozilla.org/show_bug.cgi?id=1603699#c13

**Comment by erosman** [comment]
@hamishwillee I was faced with a situation where the absence of information became relevant in https://github.com/foxyproxy/browser-extension/issues/120#issuecomment-1906836130 .
There was no information on [Firefox 122 for developers](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/122) either.

**Comment by hamishwillee** [comment]
@erosman Thanks. I asked this question in https://bugzilla.mozilla.org/show_bug.cgi?id=1603699#c13

> What is the direct impact of this change to website-developers? What should they do differently because of this?
> Can you explain what documents we might need to touch?

Same question to you - what would have made this visible to you? Perhaps an update to add a note to the constructor browser compatibility entry here: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL ?

It could say something like "From version 122 the host and port are parsed for unknown protocols/schemes" ?

**Comment by erosman** [comment]
> It could say something like "From version 122 the host and port are parsed for unknown protocols/schemes" ?

Or maybe... "Prior to version 122, `host`, `hostname`, & `port` were not returned for unknown protocols/schemes."

**Comment by hamishwillee** [comment]
Thanks, I like that more.
