### ISSUE TITLE
Array.prototype.sort(): "Sorting with map": looks like example is pointless, or I do not understand it

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mdn/content#3115]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#sorting_with_map

https://github.com/mdn/content/blob/9d64d8266823b0ed778baea1664f602ecbfde5d1/files/en-us/web/javascript/reference/global_objects/array/sort/index.html#L224-L245

By the [library link from the article](https://github.com/Pimm/mapsort) I found better explanation of this idea. I mean we should add more accent about performance, by adding a call to some expensive function.

**Comment by hamishwillee** [comment]
@vitaly-zdanevich Do you think you could create a PR to to improve it (without copying the other article)? From the maintainer point of view it is much easier to review and suggest improvements than come up with our own wording.
