### ISSUE TITLE
Note about WebAssembly.Module

### ISSUE THREAD

**Issue by allan-bonadio** [mdn/content#31182]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Module/Module

### What specific section or headline is this issue about?

introduction

### What information was incorrect, unhelpful, or incomplete?

Intro should include this note.  I was very confused when I first started doing Emscripten; I was learning WebAssembly at the same time.

Note: Emscripten uses a global variable Module (that is, window.Module) to hold its data.  This is NOT the same as WebAssembly.Module, and is unrelated.

### What did you expect to see?

warning should have been there

### Do you have any supporting links, references, or citations?

a whole page describing this poorly-named object:

https://emscripten.org/docs/api_reference/module.html

### Do you have anything more you want to share?

Thanks for doing all the hard work to keep MDN updated!  It's my main go-to source for JS, HTML, CSS and almost everything else in MDN!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/webassembly/javascript_interface/module/module`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Module/Module
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/javascript_interface/module/module/index.md
* Last commit: https://github.com/mdn/content/commit/d23f8c5c52bdfb6151476a2574e72d323d0d30f4
* Document last modified: 2023-11-20T17:47:35.000Z

</details>

**Comment by pepelsbey** [comment]
Hey! That’s a very good point. I expect people coming from Emscripten to learn more about Wasm on MDN might be easily confused by two different Modules. Feel free to send a PR with such a note, or maybe someone from the community can help with that.
