### ISSUE TITLE
Taking still photos with getUserMedia() example gives InvalidAccessError

### ISSUE THREAD

**Issue by AlecWood** [mdn/content#31194]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API/Taking_still_photos

### What specific section or headline is this issue about?

OPening the example in playground

### What information was incorrect, unhelpful, or incomplete?

There is an error message in the console thus "InvalidAccessError: A parameter or an operation is not supported by the underlying object" and the page does not function - no camera selection, no image capture etc

![image](https://github.com/mdn/content/assets/12714159/c4c35ae7-cbf1-4f7b-be93-dcc4299b01cf)

### What did you expect to see?

A box with a preview of my webcam and a button to capture an image from it

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/media_capture_and_streams_api/taking_still_photos`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API/Taking_still_photos
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/media_capture_and_streams_api/taking_still_photos/index.md
* Last commit: https://github.com/mdn/content/commit/cbd8527cf4df0464c4724b73161e4f7721301616
* Document last modified: 2023-12-18T03:14:54.000Z

</details>

**Comment by AlecWood** [comment]
Browser was current version of Firefox on Windows 11 x64

**Comment by Josh-Cena** [comment]
I've opened https://github.com/mdn/content/issues/34350 to fix these issues systematically. We'll make sure they work
