### ISSUE TITLE
Asking for help to understand

### ISSUE THREAD

**Issue by YecineM** [mdn/content#31195]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block

### What specific section or headline is this issue about?

Calculating percentage values from the containing block

### What information was incorrect, unhelpful, or incomplete?

I have a little issue with the note that says:
> Note: A block container (such as an inline-block, block, or list-item element) either contains only inline-level boxes participating in an inline formatting context, or only block-level boxes participating in a block formatting context. An element is a block container only if it contains block-level or inline-level boxes.

Can someone please clarify this?
I find it hard yo understand. In fact, I didn't understand it at all, sorry 😔
I thought block elements can perfectly contain inline and block children at the same time, so the "either, or" is a little ambiguous for me.

### What did you expect to see?

If this needs to be assigned a standalone section, why not, with a small example maybe.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/containing_block`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/containing_block/index.md
* Last commit: https://github.com/mdn/content/commit/856b52f634b889084869d2ee0b8bb62c084be04d
* Document last modified: 2023-07-17T22:37:27.000Z

</details>

**Comment by OnkarRuikar** [comment]
> I thought block elements can perfectly contain inline and block children at the same time, so the "either, or" is a little ambiguous for me.

Actually inline content in such cases is wrapped around `anonymous block box`. [[specs](https://www.w3.org/Style/css2-updates/css2/visuren.html#anonymous-block-level)]:
> ```html
> <DIV>
>    Some text
>    <P>More text
> </DIV>
> ```
> (and assuming the DIV and the P both have 'display: block'), the DIV appears to have both inline content and block content. To make it easier to define the formatting, we assume that there is an anonymous block box around "Some text".
> In other words: if a block container box (such as that generated for the DIV above) has a block-level box inside it (such as the P above), then we force it to have only block-level boxes inside it.

**Comment by YecineM** [comment]
@OnkarRuikar Wow, thank you so much.
That's totally new and relevant information to me.

**Comment by OnkarRuikar** [comment]
> A block container only contains block-level or inline-level boxes.

That's what the previous statement in the note says. Considering there are other containers like table, grid, flex etc. as well so the author might have used the indirect `An element is a block container only if it contains block-level or inline-level boxes` statement.

**Comment by YecineM** [comment]
Got it, it makes sense, thank you 😀

**Comment by estelle** [comment]
Thanks Onkar!
