### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by linchenlinchen** [mdn/content#31192]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Issues

### What specific section or headline is this issue about?

error in page https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function

### What information was incorrect, unhelpful, or incomplete?

There is

>Note how the promise chain is not built-up in one go. Instead, the promise chain is constructed in stages as control is successively yielded from and returned to the async function. As a result, we must be mindful of error handling behavior when dealing with concurrent asynchronous operations.
>
>For example, in the following code an unhandled promise rejection error will be thrown, even if a .catch handler has been configured further along the promise chain. This is because p2 will not be "wired into" the promise chain until control returns from p1.

but code is:

```js
async function foo() {
  const p1 = new Promise((resolve) => setTimeout(() => resolve("1"), 1000));
  const p2 = new Promise((_, reject) => setTimeout(() => reject("2"), 500));
  const results = [await p1, await p2]; // Do not do this! Use Promise.all or Promise.allSettled instead.
}
foo().catch(() => {}); // Attempt to swallow all errors...
```

it seems that `resolve("1")` should be replace by `reject("1")`

### What did you expect to see?

```js
async function foo() {
  const p1 = new Promise((resolve) => setTimeout(() => resolve("1"), 1000));
  const p2 = new Promise((_, reject) => setTimeout(() => reject("2"), 500));
  const results = [await p1, await p2]; // Do not do this! Use Promise.all or Promise.allSettled instead.
}
foo().catch(() => {}); // Attempt to swallow all errors...
```

it seems that `resolve("1")` should be replace by `reject("1")`

### Do you have any supporting links, references, or citations?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community/issues`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community/Issues
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/issues/index.md
* Last commit: https://github.com/mdn/content/commit/a15be9cc426c19e3a1a510a49c4615d56ba4415d
* Document last modified: 2023-10-11T13:06:39.000Z

</details>

**Comment by ayushjha119** [comment]
@linchenlinchen assign this issue to me , i would i like to contribute to this

**Comment by Josh-Cena** [comment]
The code accurately reflects the prose. You can try this yourself and see that an uncaught rejection is generated, which is exactly what's supposed to happen (because we are still awaiting on `p1`, but `p2` has already rejected, so it stays rejected). Your provided "expect to see" section is also exactly the same as the original code so I'm not sure what to do here.
