### ISSUE TITLE
Conflicting Information regarding storage onChanged

### ISSUE THREAD

**Issue by erosman** [mdn/content#31203]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/onChanged

### What specific section or headline is this issue about?

changes

### What information was incorrect, unhelpful, or incomplete?

Due to extension bug reports, I had to test the output of `onChanged` and I found out that there are conflicting information on MDN which led to the issue.

> [storage.onChanged](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/onChanged#changes)
> 
> `object`. Object describing the change. This object contains properties for all the keys in the storage area included in the [storageArea.set](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/set) call, even if key values are unchanged.

> [storage.StorageArea.onChanged](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/onChanged#changes)
> 
> `object`. Object describing the change. This contains one property for each key that changed. The name of the property is the name of the key that changed, and its value is a [storage.StorageChange](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageChange) object describing the change to that item.

First one says: "all the keys in the storage area, even if key values are unchanged"
Second one says: "one property for each key that changed."

After further testing both APIs `storage.onChanged` & `storage.sync.onChanged`:

- Firefox `onChanged` returns all the keys in the storage area, even if all values are unchanged
- Chrome `onChanged` returns only the changed values (event doesn't fire when there is no change)

### What did you expect to see?

no conflicting information

### Do you have anything more you want to share?

See also:
- [Bug 1833153: storage.sync should not emit onChanged events for calls that are not resulting into changes to the store data](https://bugzilla.mozilla.org/show_bug.cgi?id=1833153)

**Comment by rebloor** [comment]
@erosman from your testing, did you determine whether the statement that "When this event is triggered by `storageArea.set`, it's possible to receive a callback when there is no change to the underlying data." is still correct? Do you get a call back with an empty object if there are no changes?

**Comment by erosman** [comment]
@rebloor After further testing, I had to correct & update the test results.

The issue can now be summarised as:

- Confusing text for the 2 APIs
- Inconsistency between Chrome & Firefox implementations
