### ISSUE TITLE
gecko_android in FF: entries of availabiliy in FF are wrong since Dec. 14th 23

### ISSUE THREAD

**Issue by opto** [mdn/content#31242]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings

### What information was incorrect, unhelpful, or incomplete?

addons are now available for FF on Android

### What did you expect to see?

update text and the compatibility list at the bottom

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/browser_specific_settings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/manifest.json/browser_specific_settings/index.md
* Last commit: https://github.com/mdn/content/commit/bf754e9a6e92327840cb5e186deee1042c8b48e3
* Document last modified: 2023-04-25T02:51:38.000Z

</details>

**Comment by teoli2003** [comment]
I see this:
![image](https://github.com/mdn/content/assets/1466293/32d679c8-c0c8-4df8-9d70-8182019c50c4)
Do you mean a more recent date should be written than what appears now?

**Comment by opto** [comment]
this seems to be wrong by now:
<img width="305" alt="image" src="https://github.com/mdn/content/assets/204256/7c42fe1e-0cb7-4733-a034-1aa1aca1879b">

**Comment by teoli2003** [comment]
![Capture d’écran 2023-12-23 à 07 30 19](https://github.com/mdn/content/assets/1466293/e9253963-6ef1-4845-9684-d9a062eb71ab)

**Comment by rebloor** [comment]
This information is correct.

- `gecko_android` is not supported/used by desktop Firefox extensions
- when `gecko_android` isn't provided, Firefox for Android uses the values of `gecko.strict_min_version` and `gecko.strict_max_version` (as noted in the documentation).

Extensions for AFF have been available for some time. The [December 14 announcement](https://blog.mozilla.org/en/mozilla/new-extensions-youll-love-now-available-on-firefox-for-android/) was the outcome of an initiative to make more extensions available, it didn't reflect any underlying change in these features on that date.
