### ISSUE TITLE
Issue with "Array.prototype.forEach()": misleading words "ascending order"

### ISSUE THREAD

**Issue by amandeepmicro** [mdn/content#3125]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

#### What information was incorrect, unhelpful, or incomplete?
In the first line of Description it says that "forEach() calls a provided callback function once for each element in an array in ascending order". However the words " ascending order "   is misleading. 

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#description

#### What did you expect to see?
I expect to see  "forEach() calls a provided callback function once for each element in an array in ascending index order (skipping indices that were never assigned a value)."

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/foreach`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/foreach/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this 👍
