### ISSUE TITLE
Issue with "Cross-Origin-Opener-Policy": (short summary here please)

### ISSUE THREAD

**Issue by KaycoinsInc** [mdn/content#3127]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/cross-origin-opener-policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/cross-origin-opener-policy/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, but there is no information on the problem here. I am closing. Feel free to reopen with the information requested in the template above.
