### ISSUE TITLE
CSSConditionRule.conditionText property is readonly

### ISSUE THREAD

**Issue by thomashigginbotham** [mdn/content#31279]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSSConditionRule/conditionText

### What specific section or headline is this issue about?

Multiple sections

### What information was incorrect, unhelpful, or incomplete?

The description and example of the CSSConditionRule.conditionText property says that it can be set to a new value. However, the CSS WG decided that the property should be readonly.

The [CSS spec](https://www.w3.org/TR/css-conditional-3/#the-cssconditionrule-interface) does not appear to have been updated with this decision, but no browsers currently support setting the property.

### What did you expect to see?

The page indicates the property is readonly or that no browsers are in compliance with the spec as it currently exists.

### Do you have any supporting links, references, or citations?

https://github.com/w3c/csswg-drafts/issues/6819

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/cssconditionrule/conditiontext`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSSConditionRule/conditionText
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/cssconditionrule/conditiontext/index.md
* Last commit: https://github.com/mdn/content/commit/d76defab4ca13261e9de81ae1df125345f847b0a
* Document last modified: 2023-04-07T05:46:57.000Z

</details>

**Comment by skyclouds2001** [comment]
[the published version of the spec](https://www.w3.org/TR/css-conditional-3/) is not mark it as read-only, but [the draft version](https://drafts.csswg.org/css-conditional-3/) has marked it as read-only yet

**Comment by Josh-Cena** [comment]
There's no example for setting `conditionText`. We should:

- Remove the `text = "(min-width: 400px)";` as it does nothing (it just changes the variable to something else)
- Apply our usual conventions for readonly properties (change the description text, add readonly badge to the landing page, etc.)

I'm not sure if compatibility data or mentioning historical behavior is necessary here, as no browser ever supported it correctly (as mentioned in https://github.com/w3c/csswg-drafts/issues/6819).
