### ISSUE TITLE
<canvas> tag doesn't seem to be working properly

### ISSUE THREAD

**Issue by mLaneK** [mdn/content#31288]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code

### What specific section or headline is this issue about?

'Why are loops useful ?'

### What information was incorrect, unhelpful, or incomplete?

It looks like the canvas is supposed to fill a larger area than it does

### What did you expect to see?

I expected to see the whole canvas tag being taken up. Hope this helps!
<img width="1426" alt="Screenshot 2023-12-25 at 07 29 54" src="https://github.com/mdn/content/assets/141520908/6675c142-a451-4688-ab9c-61502b0d83b2">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/looping_code`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/looping_code/index.md
* Last commit: https://github.com/mdn/content/commit/289d6314f3368aa3e28524e7d090f6e9c704e3b1
* Document last modified: 2023-11-28T20:48:44.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for reporting this one. There's a linked PR above that fixes this! 🙌🏻

**Comment by Josh-Cena** [comment]
Should be fixed now

**Comment by mLaneK** [comment]
That’s so great thank you for the update ♥️ Catch ya on the flip,Mason LaneOn Jun 10, 2024, at 11:58, Joshua Chen ***@***.***> wrote:﻿
Should be fixed now
