### ISSUE TITLE
CorsProblem

### ISSUE THREAD

**Issue by michili** [mdn/content#31305]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors

### What specific section or headline is this issue about?

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://localhost:5000/get_usernames. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).

### What information was incorrect, unhelpful, or incomplete?

I run a apache server. a website frontend is communicating with a python backend. the backend reads a csv file and upon a get-request it sends data to tebsite which is displaying it. local it works very well.
from a remote computer the display of the page is perfect, but no data is trasferred:
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://localhost:5000/get_usernames. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).

### What did you expect to see?

the index.html is displaying the names in a combibox

### Do you have anything more you want to share?

the .py imports flask-cors...
from flask import Flask, request, jsonify
from flask_cors import CORS

import csv

app = Flask(__name__)
CORS(app)  # Dies aktiviert CORS für alle Routen

# Pfad zur
csv_file_path = 'assets/pws.csv'

def get_usernames():
    usernames = []
    with open(csv_file_path, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            usernames.append(row[0])
    print("Benutzernamen abgerufen:", usernames)
    return usernames

def authenticate_user(username, password):
    # Authentifizierung überprüfen
    with open(csv_file_path, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            if row[0] == username and row[1].strip() == password:
                return 1  # Authentifizierung erfolgreich
    return 0  # Authentifizierung fehlgeschlagen

@app.route('/get_usernames', methods=['GET'])
def send_usernames():
    usernames = get_usernames()
    return jsonify({'usernames': usernames})

@app.route('/authenticate', methods=['POST'])
def authenticate():
    data = request.get_json()
    username = data['username']
    password = data['password']

    result = authenticate_user(username, password)

    return jsonify({'result': result})

if __name__ == '__main__':
    app.run(port=5000)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/cors/errors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/errors/index.md
* Last commit: https://github.com/mdn/content/commit/93c9f9954bd14ae8877973e5fe3c1d8378e56f92
* Document last modified: 2023-12-15T05:50:02.000Z

</details>

**Comment by Josh-Cena** [comment]
Please debug CORS errors yourself—MDN is not a help forum.
