### ISSUE TITLE
Code example using fetch() API does not work in browser console

### ISSUE THREAD

**Issue by authentictech** [mdn/content#31309]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises

### What specific section or headline is this issue about?

Using the fetch() API

### What information was incorrect, unhelpful, or incomplete?

The first code example directs the user to enter the code into the browser console. However, using the code in the browser console produces the following:

`Content-Security-Policy: The page's settings blocked the loading of a resource at https://mdn.github.io/learning-area/javascript/apis/fetching-data/can-store/products.json ("connect-src").`

and:

`Promise { <state>: "rejected", <reason>: TypeError } ​ <state>: "rejected" ​ <reason>: TypeError: NetworkError when attempting to fetch resource. ​ `

### What did you expect to see?

The code should have produced the response from the fetch() command, and logged it to the console, as described in the article.

```
Promise { <state>: "pending" }
Started request…
Received response: 200
```

### Do you have anything more you want to share?

The code works as described when included in a web page rather than using the browser console. Perhaps the page from which the resource is being fetched does not permit fetch() operations initiated from a browser console for some security reason?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/promises/index.md
* Last commit: https://github.com/mdn/content/commit/791523a75763f24624602a2071d5b69272854710
* Document last modified: 2023-12-11T19:32:32.000Z

</details>

**Comment by skyclouds2001** [comment]
That's an issue relates with Content Security Policy, as my understanding, it has no relationship with any code bug itself

**Comment by wbamberg** [comment]
When you say "browser console" do you actually mean the Firefox "Browser console" (which won't work), or the plain "Console" that's part of the Firefox devtools (see https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/What_are_browser_developer_tools#the_javascript_console)?

I'm pretty sure that if you follow the instructions in the note at the start of https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises#using_the_fetch_api, and use the plain "Console", then this guide works.

**Comment by bsmth** [comment]
Thanks a lot! This seems to be resolved in https://github.com/orgs/mdn/discussions/478 so I'm closing as done.

>I'm pretty sure that if you follow the instructions in the note at the start of https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises#using_the_fetch_api, and use the plain "Console", then this guide works.

I didn't notice this at first, that's good to highlight.
