### ISSUE TITLE
Inconsistent gradient documentation

### ISSUE THREAD

**Issue by jimmonte** [mdn/content#31307]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/gradient

### What specific section or headline is this issue about?

Syntax and Formal syntax

### What information was incorrect, unhelpful, or incomplete?

The syntax section does not describe repeating conic gradients while the formal syntax describes neither these nor ordinary conic gradients.

### What did you expect to see?

Consistency and completeness

### Do you have any supporting links, references, or citations?

The CSS level 4 link on the page describes conic and repeating conic gradients

### Do you have anything more you want to share?

https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/conic-gradient
and
https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-conic-gradient
have formal syntax sections that describe these types. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/gradient`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/gradient
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/gradient/index.md
* Last commit: https://github.com/mdn/content/commit/5e7d1f9ae2cce0cb3f7693dfb8dc6e8d375b2231
* Document last modified: 2023-07-18T00:16:24.000Z

</details>

**Comment by OnkarRuikar** [comment]
The [PR fixing this](https://github.com/mdn/content/pull/31625) adds a mention of repeating conic gradient in the syntax section. 

Formal syntax section is auto generated by `mdn/yari` repo and the major fixing work is in progress. So formal syntax section can't be updated in this repo.
