### ISSUE TITLE
Issue with "<input type="url">": URLs leading to different id are wrong

### ISSUE THREAD

**Issue by RedHotRojo** [mdn/content#3131]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url

#### What information was incorrect, unhelpful, or incomplete?
If you go to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url#additional_attributes and attempt to click on the links listed under "Attribute" they do not lead you anywhere. 

Also, the links under https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url#non-standard_attributes lead nowhere. Underneath it, there is incomplete code rendered as: {{page("/en-US/docs/Web/HTML/Element/input/text", "autocorrect", 0, 1, 2)}}

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url#additional_attributes and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url#non-standard_attributes

#### What did you expect to see?
The Additional Attribute page should have `htmlattrdef` added before the current id. For example, the current link id is .../url#list when it should be .../url#htmlattrdeflist

As for the non-standard attributes, I wanted to see autocorrect and mozactionhint

#### Did you test this? If so, how?
I tested the id for the Additional Attribute page by using the id the section mentions.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/url`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/url/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by rachelandrew** [comment]
Thanks for reporting this @RedHotRojo looks like the links got messed up at some point, I'll sort that out.

**Comment by rachelandrew** [comment]
This was fixed in #5510
