### ISSUE TITLE
Note about specificity doesn't make any sense in this page

### ISSUE THREAD

**Issue by TrachukBohdan** [mdn/content#31376]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors

### What information was incorrect, unhelpful, or incomplete?

<img width="1060" alt="Screenshot 2023-12-28 at 22 49 59" src="https://github.com/mdn/content/assets/13988978/b6ee479c-e36e-494e-82e5-dea0377fd4f5">
 
at this point user doesn't know about specificity yet, because chapter [Cascade, specificity, and inheritance](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance) goes after it

### What did you expect to see?

Removed note about specificity

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors/type_class_and_id_selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/type_class_and_id_selectors/index.md
* Last commit: https://github.com/mdn/content/commit/62b157fcb817f10340021e93ef29b754e440ff69
* Document last modified: 2023-11-01T16:56:42.000Z

</details>

**Comment by AYUKARLINA** [comment]
![FB_IMG_17034310421624581](https://github.com/mdn/content/assets/155115910/2725a73e-3bb0-4467-8dc4-93bc14e5aac3)
$350
