### ISSUE TITLE
Issue with "HmacKeyGenParams": default key length for HMAC(SHA-256)

### ISSUE THREAD

**Issue by constcrist** [mdn/content#3140]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HmacKeyGenParams

#### What information was incorrect, unhelpful, or incomplete?
length Optional
A Number — the length in bits of the key. If this is omitted the length of the key is equal to the length of the digest generated by the digest function you have chosen. Unless you have a good reason to use a different length, omit this property and use the default.

#### Specific section or headline?
Properties

#### What did you expect to see?
A _default_ key length of 256 bits for SHA256 based HMAC.

#### Did you test this? If so, how?
Generated a key for HMAC(SHA256) with _default_ length, dumped the CryptoKey object into the developer console (both on firefox and on chrome) and the key length was 512 and not 256.
I wrote a lot more details in my cryptoexchange question here:
https://crypto.stackexchange.com/questions/88669/generating-hmacsha256-keys-using-webcrypto-derivekey-api

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/hmackeygenparams`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HmacKeyGenParams
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/hmackeygenparams/index.html
* Last commit: https://github.com/mdn/content/commit/9917bf17a97973166bb3cb3812a496e4117a778f
* Document last modified: 2021-01-11T13:30:57.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! I think the docs are wrong.

[The spec says](https://www.w3.org/TR/WebCryptoAPI/#hmac-keygen-params):

> dictionary HmacKeyGenParams : Algorithm {
>
>  // The inner hash function to use.
  required HashAlgorithmIdentifier hash;
>
>  // The length (in bits) of the key to generate. If unspecified, the
  // recommended length will be used, which is **the size of the associated hash function's block size**.
  [EnforceRange] unsigned long length;
};

....i.e. it's the block size, not the output size.

Which gives us:

```

async function gen(hash) {

  const key = await window.crypto.subtle.generateKey(
      {
        name: "HMAC",
        hash: hash
      },
      true,
      ["sign", "verify"]
    );
  console.log(key.algorithm.length);
}

gen("SHA-1");    //  512
gen("SHA-256");  //  512
gen("SHA-384");  // 1024
gen("SHA-512");  // 1024
```

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Update info as per comment above

**Comment by junjunjunk** [comment]
Hi. I'll take this issue.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/pull/4527  - thanks @junjunjunk !
