### ISSUE TITLE
"DOM request": the phrase found in the AbortSignal and AbortController pages seems improper.

### ISSUE THREAD

**Issue by pygy** [mdn/content#31427]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AbortController

### What information was incorrect, unhelpful, or incomplete?

[Web/API/AbortSignal](https://github.com/mdn/content/blob/93049469e756abab8a25a98dbc7786abdd811ec0/files/en-us/web/api/abortcontroller/index.md?plain=1#L27) says

> The **`AbortSignal`** interface represents a signal object that allows you to communicate with a DOM request (such as a fetch request) and abort it if required via an {{domxref("AbortController")}} object.

[API/AbortController](https://github.com/mdn/content/blob/93049469e756abab8a25a98dbc7786abdd811ec0/files/en-us/web/api/abortcontroller/index.md?plain=1#L12) says 

> [...] Communicating with a DOM request is done using an {{domxref("AbortSignal")}} object.

The "DOM request" phrase is used further in these pages, and it seems improper as these have nothing to do with the DOM.

That language isn't found elsewhere on MDN nor in the [Fetch standard](https://fetch.spec.whatwg.org/).

### What did you expect to see?

"HTTP request", "Fetch request", or "Web request" maybe?

I'm not sure what's more appropriate.

**Comment by wbamberg** [comment]
I agree "DOM request" is weird. I suppose the reason behind not just using "fetch request" is that this mechanism could be used with other APIs, not just Fetch. See also (from https://developer.chrome.com/blog/abortable-fetch/):

> This API is provided by [the DOM standard](https://dom.spec.whatwg.org/#aborting-ongoing-activities), and that's the entire API. It's deliberately generic so it can be used by other web standards and JavaScript libraries.

Maybe "asynchronous operation (such as a fetch request)"?

**Comment by pygy** [comment]
It looks like AbortController has indeed grown past Fetch and is used in other APIs.

Does "asynchronous operation" makes consensus?

**Comment by wbamberg** [comment]
It seems reasonable to me. Would you like to file a PR to make this update, or shall I?

**Comment by pygy** [comment]
Incoming...
