### ISSUE TITLE
Issue with "HTMLImageElement.naturalWidth": (short summary here please)

### ISSUE THREAD

**Issue by davidmaxwaterman** [mdn/content#3143]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/naturalWidth

#### What information was incorrect, unhelpful, or incomplete?
Apparently, naturalWidth/Height does not necessarily match the size of the source image. When chrome is running on low-end hardware, it will scale down the image and it is that size that is represented by naturalWidth/Height.

https://bugs.chromium.org/p/chromium/issues/detail?id=1187043#c7

#### Specific section or headline?
Not sure.

#### What did you expect to see?
I expected to be informed of this fact.
As a side note, I also would find it very useful to have an API that does give the dimensions of the source image (even though there are work-arounds to find that).

#### Did you test this? If so, how?
You need a 'low end' device to test on. In my case, it is a VKWorld F1.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlimageelement/naturalwidth`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/naturalWidth
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlimageelement/naturalwidth/index.html
* Last commit: https://github.com/mdn/content/commit/11a98a59fca5f2e448d9e4b70e3c8a538c47b201
* Document last modified: 2021-02-19T19:45:18.000Z

</details>

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Check the bug linked above - it's helpful info
* Add a note to include browsers might intervene, resize an image and thus not return original source width & height

**Comment by teoli2003** [comment]
@davidmaxwaterman This is a great report! Thanks a lot for it. I hope the PR makes it a little bit more clear for other developers.
