### ISSUE TITLE
Isn't "422 Unprocessable Entity" the correct name?

### ISSUE THREAD

**Issue by xpe** [mdn/content#31454]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422

### What specific section or headline is this issue about?

422 Unprocessable Content

### What information was incorrect, unhelpful, or incomplete?

I believe the title "422 Unprocessable Content" is out of date. I think the correct title should be "422 Unprocessable Entity".

### What did you expect to see?

"422 Unprocessable Entity"

### Do you have any supporting links, references, or citations?

Per https://datatracker.ietf.org/doc/html/rfc4918#section-11.2

> The 422 (Unprocessable Entity) status code means the server understands the content type of the request entity (hence a 415 (Unsupported Media Type) status code is inappropriate), and the syntax of the request entity is correct (thus a 400 (Bad Request) status code is inappropriate) but was unable to process the contained instructions. For example, this error condition may occur if an XML request body contains well-formed (i.e., syntactically correct), but semantically erroneous, XML instructions.

I noticed this because the Rust [http crate](https://docs.rs/http/latest/src/http/status.rs.html#452) uses "Unprocessable Entity" as well:

```rs
    /// 422 Unprocessable Entity
    /// [[RFC4918](https://tools.ietf.org/html/rfc4918)]
    (422, UNPROCESSABLE_ENTITY, "Unprocessable Entity");
```

### Do you have anything more you want to share?

I haven't followed the relevant RFCs closely in a while. Please educate me if I've gotten this wrong; if so, then the Rust `http` crate has gotten it wrong too.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/422`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/422/index.md
* Last commit: https://github.com/mdn/content/commit/0880a90f3811475d78bc4b2c344eb4146f25f66c
* Document last modified: 2023-04-10T19:47:15.000Z

</details>

**Comment by Josh-Cena** [comment]
This was changed in https://github.com/mdn/content/pull/24866. You can check the more up-to-date links there. (The MDN page also has a spec link to RFC9110.)

**Comment by albannurkollari** [comment]
Hi. I just encountered into this mismatch too. Too my surprise, the official document stand correct with the MDN one but at least in Chrome all 422 are labelled as `Unprocessable Entity`.

Do you reckon this is a Chrome issue? @Josh-Cena 
Thanks in advance!

**Comment by Josh-Cena** [comment]
Yeah, very likely. I'm on vacation so I can't check, but it would be helpful to search through Chrome issues and maybe send one if nothing comes up.
