### ISSUE TITLE
It wont capitalize anything...?

### ISSUE THREAD

**Issue by Ari32602** [mdn/content#31450]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize

### What specific section or headline is this issue about?

It wont capitalize anything...?

### What information was incorrect, unhelpful, or incomplete?

Hi there, maybe it's just because I'm new to code, but I tried typing in all the boxes from the program on the page, but absolutely none of them would auto-capitalize! I know that the code was correct (seeing as it was prewritten on the page as an example) so I'm rather lost. I am using the right kind of browser btw!

### What did you expect to see?

The correct outcome from the code provided.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/autocapitalize`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/autocapitalize/index.md
* Last commit: https://github.com/mdn/content/commit/337fde08da46e0861c40458357831bba582439c5
* Document last modified: 2023-12-04T14:28:33.000Z

</details>

**Comment by hamishwillee** [comment]
Ah, but did you read the description - this only works for voice and virtual keyboard entry?

I don't think this is particularly obvious by the time you get to the example. Fixed in #31452

**Comment by Ari32602** [comment]
Ah my apologies, I didn’t see that! Thank you 😅
