### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by skyfighteer** [mdn/content#31469]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/transition-behavior

### What specific section or headline is this issue about?

CSS

### What information was incorrect, unhelpful, or incomplete?

The two properties we want to animate are opacity and transform**)**:

The parenthesis is a mistake I believe.

### What did you expect to see?

No parenthesis.

**Comment by ibrahimkhled** [comment]
> ### MDN URL
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/transition-behavior
> 
> ### What specific section or headline is this issue about?
> 
> CSS
> 
> ### What information was incorrect, unhelpful, or incomplete?
> 
> The two properties we want to animate are opacity and transform**)**:
> 
> The parenthesis is a mistake I believe.
> 
> ### What did you expect to see?
> 
> No parenthesis.
> 
> ### Do you have any supporting links, references, or citations?
> 
> _No response_
> 
> ### Do you have anything more you want to share?
> 
> _No response_
