### ISSUE TITLE
Float seems to be more compatible than cssFloat.

### ISSUE THREAD

**Issue by hezedu** [mdn/content#31481]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/float

### The MDN Note:
Note: If you're referring to this property from JavaScript as a member of the [HTMLElement.style](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style) object, modern browsers support float, but in older browsers you have to spell it as cssFloat. This was an exception to the rule, that the name of the DOM member is the [camel-case](https://developer.mozilla.org/en-US/docs/Glossary/Camel_case) name of the hyphenated CSS name (because "float" is a reserved word in JavaScript, as seen in the need to escape "class" as "className" and escape <label>'s "for" as "htmlFor").

But looking at the compatibility, float seems to be better.

float on caniuse.com: https://caniuse.com/?search=float
float on MDN: https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/cssFloat

cssFloat on caniuse.com: https://caniuse.com/?search=cssFloat
cssFloat on MDN: https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/cssFloat

### What did you expect to see?

---

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/float`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/float
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/float/index.md
* Last commit: https://github.com/mdn/content/commit/6aa664dc5ccb5edf0897f99ad5feb59325dff831
* Document last modified: 2023-09-08T01:05:56.000Z

</details>

**Comment by dipikabh** [comment]
@hezedu, you're right that `cssFloat` is mostly used in older browsers, which is what the "Note" aims to convey.

However, I saw room for improving the "Note" to make the text clearer, so I've opened a pull request.
