### ISSUE TITLE
Clipboard API Glitch demo is not working

### ISSUE THREAD

**Issue by rhuanbarreto** [mdn/content#31485]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

### What information was incorrect, unhelpful, or incomplete?

On the "See also" section, the demo on glitch is not working.
Error is:
> Oops! This project isn't running.
> It looks like this project isn't running because the version of [Node.js](https://nodejs.org/en/about) it relies on is too old.
> If this is your project, head on over to the [Glitch Editor](https://glitch.com/edit/#!/async-clipboard-api) so you can fix the required Node version in your package.json file, or head over to [the Help Center page on supported Node versions](https://help.glitch.com/hc/en-us/articles/16287495688845) to learn more.

### What did you expect to see?

A demo on glitch

### Do you have any supporting links, references, or citations?

https://async-clipboard-api.glitch.me/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/clipboard_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/clipboard_api/index.md
* Last commit: https://github.com/mdn/content/commit/c316bf6663d2ae19a4afa841a3c5f996e8338af6
* Document last modified: 2023-11-03T08:47:35.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing @rhuanbarreto ! I will look into replacing this with an example in the page.

**Comment by skyclouds2001** [comment]
relates with https://github.com/mdn/content/pull/31483 and https://github.com/mdn/content/pull/31489

**Comment by wbamberg** [comment]
It looks like https://github.com/mdn/content/pull/31489 just removed the links, so let's just close this.
