### ISSUE TITLE
Issue with "Gecko Logging": (add example for activiting multiple loggers)

### ISSUE THREAD

**Issue by mbrodesser** [mdn/content#3150]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Gecko_Logging

#### What information was incorrect, unhelpful, or incomplete?

Missing example. E.g. `MOZ_LOG="SpellChecker:5,InlineSpellChecker:5"`.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Gecko_Logging#enabling_logging

#### What did you expect to see?
The information how to activate multiple loggers. That is, they have to be delimited by commas. E.g.: `MOZ_LOG="SpellChecker:5,InlineSpellChecker:5"`

#### Did you test this? If so, how?
Locally.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/developer_guide/gecko_logging`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Gecko_Logging
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/developer_guide/gecko_logging/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can add the example 👍

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander Simple example needs adding. Go for it!
