### ISSUE TITLE
Add information to `DOMParser.parseFromString` page about the `includeShadowRoots` option

### ISSUE THREAD

**Issue by thescientist13** [mdn/content#31501]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

Per the [Chrome Developer docs](https://developer.chrome.com/docs/css-ui/declarative-shadow-dom#parser-only), there is reference to a third parameter to `parseFromString` that handles parsing Declarative Shadow DOM
```html
<script>
  const html = `
    <div>
      <template shadowrootmode="open"></template>
    </div>
  `;
  const div = document.createElement('div');
  div.innerHTML = html; // No shadow root here

  const fragment = new DOMParser().parseFromString(html, 'text/html', {
    includeShadowRoots: true
  }); // Shadow root here
</script>
```

### What did you expect to see?

I would like to see the content expanded to include the third param and some details about the option and why it would be used.  For example, the Chrome docs frame it as such:
> _To avoid some important security considerations, Declarative Shadow Roots also can't be created using fragment parsing APIs like `innerHTML` or `insertAdjacentHTML()`. The only way to parse HTML with Declarative Shadow Roots applied is to pass a new includeShadowRoots option to `DOMParser`:_

### Do you have any supporting links, references, or citations?

Here is a thread from **WHATWG/dom** GitHub discussion regarding its participation in the Declarative Shadow DOM spec
https://github.com/whatwg/dom/issues/912#issuecomment-732476002

### Do you have anything more you want to share?

It seems like this might make a good companion to https://github.com/mdn/content/issues/29600 ?

----

Happy to help contribute to drafting this content if you would like.  👍

**Comment by pepelsbey** [comment]
Hey! Great idea :) We’re currently documenting [`shadowrootmode`](https://github.com/mdn/content/issues/31102) and [`clonable`](https://github.com/mdn/content/issues/31108) for the upcoming Firefox 122 release (behind the flag for now, but it will be enabled by default in 123). Feel free to go ahead and send a PR with the `includeShadowRoots` option as well.

**Comment by thescientist13** [comment]
Thanks, I'll get started on that PR then!

> _Though I’m curious what’s the browser support for `includeShadowRoots`. I couldn’t find it in BCD, apart from the [parseFromString](https://github.com/mdn/browser-compat-data/blob/main/api/DOMParser.json#L83) method itself._

I can try and take a look into that.  Is it just a matter of getting an official response from each vendor a confirmation of what version that feature was added in?  (Apologies, haven't worked with BCD myself).

I found this [blog post from Webkit](https://webkit.org/blog/13851/declarative-shadow-dom/) about Declarative Shadow DOM which calls out `DOMParser` but not specifically `includeShadowRoots`.  Not sure if that is helpful...

**Comment by thescientist13** [comment]
With some help from the WCCG, I was pointed to the WPT which shows that `includeShadowRoots` is under test
https://wpt.fyi/results/shadow-dom/declarative/declarative-shadow-dom-opt-in.html?label=experimental&label=master&aligned

And that is being shown in reports
![Screenshot 2024-01-21 at 12 52 55 PM](https://github.com/mdn/content/assets/895923/80af13c0-7b07-491f-8380-817d16428e7a)

It's called out as _"(includingShadowRoots is historical)"_ and It's not mentioned in [the spec](https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#dom-domparser-parsefromstring).

Additionally [this comment](https://github.com/web-platform-tests/wpt/pull/42833#issuecomment-1785670941) implies that the explanation for these then is that it's not going to be standardized.

----

So I wonder then if the goal here with this particular content around `includeShadowRoots` should be more focused on capturing from a historical perspective and that it is not a standard, and thus should encourage readers to use / look to the alternative options instead?
- https://github.com/whatwg/html/pull/9538
- https://wpt.fyi/results/html/webappapis/dynamic-markup-insertion/html-unsafe-methods?label=master&label=experimental&aligned&q=setHTMLUnsafe
- https://wpt.fyi/results/html/webappapis/dynamic-markup-insertion/html-unsafe-methods?label=master&label=experimental&aligned

There is a tracking item for this content as well -  https://github.com/mdn/mdn/issues/459

**Comment by pepelsbey** [comment]
> It’s not mentioned in the spec
> It’s not going to be standardized

I’m afraid this changes everything. Thank you so much for bringing this to our attention, filing the issue, and opening a draft PR. We really appreciate it! However, since the options param is [not in the spec](https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#dom-domparser-parsefromstring-dev) and hence why the WPT tests fail. It is also not a part of BCD.

I’ll have to close it since we’re not documenting features that aren’t in the spec or the browsers, even for historical reasons. I’m sorry for confusing you earlier.

**Comment by thescientist13** [comment]
Alrighty.

Do you think there's any value on starting on https://github.com/mdn/mdn/issues/459 at all, or is it too soon for that one?  It's in WPT and the spec PR was merged but not sure around the sanitization efforts / parameters called out in that description.

Either way, happy to support on this now or in the future when MDN is ready for it.  👍

**Comment by pepelsbey** [comment]
@thescientist13 thank you! It seems like the `setHTMLUnsafe` and `parseHTMLUnsafe` methods [were implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=1712140) behind the flag in Firefox 122 and will be shipped by default in 123. It means we have a stable spec and at least one implementation with other browsers ready to follow. That’s a perfect case for documenting this on MDN :)
