### ISSUE TITLE
Issue with "Truthy": (Other empty strings such as " ", "  ", etc evaluate to Falsy as well in Microsoft Edge (Chromium Browser))

### ISSUE THREAD

**Issue by programmer101010** [mdn/content#3151]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Truthy

#### What information was incorrect, unhelpful, or incomplete?

" ", "  ", "   ", etc also all evaluate to Falsy statements in Microsoft Edge 89 (A Chromium browser) but more testing would be needed in other contents.  Please update this to other answers on stackoverflow as well.

#### Specific section or headline?

Falsy section

#### What did you expect to see?

A Truthy evaluation for "", " ", 

#### Did you test this? If so, how?

Using the debugging console on a blank page in Microsoft Edge.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/truthy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Truthy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/truthy/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Can you please describe exactly how you are testing, and provide a reproducible, runnable test case?

**Comment by sideshowbarker** [comment]
Closing for lack of response
