### ISSUE TITLE
`<param>` attribute deprecated - missing sources

### ISSUE THREAD

**Issue by Sebastian-Brud-Tectonic** [mdn/content#31523]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/param

### What specific section or headline is this issue about?

deprecated: `<param>`: The Object Parameter element

### What information was incorrect, unhelpful, or incomplete?

It is said that this element is deprecated, contrary to multiple sources. It was deprived of a very specific behavior, but there are still use cases like providing dynamic parameters to an SVG image.

* https://chromestatus.com/feature/6283184588193792 <-- `<param>` was not removed, just a particular behaviour/attribute is no longer a part of its implementation

### What did you expect to see?

Either sources for deprecation statement (along with W3C recommendation or a doc) and a verified link to one of browsers' code that would suggest `<param>` element removal.

### Do you have any supporting links, references, or citations?

* https://chromestatus.com/feature/6283184588193792
* https://www.w3.org/TR/SVGParamPrimer/
* https://www.w3.org/TR/2012/WD-html-markup-20121025/param.html - pretty old
* latest spec: https://html.spec.whatwg.org/ (no word about <param> element being deprecated or obsolete)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/param`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/param
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/param/index.md
* Last commit: https://github.com/mdn/content/commit/942a529383ee7ee3996fb234187641c08935f3ff
* Document last modified: 2023-04-13T06:13:15.000Z

</details>

**Comment by Josh-Cena** [comment]
See https://github.com/mdn/content/pull/15225 for context

**Comment by wbamberg** [comment]
> Either sources for deprecation statement (along with W3C recommendation or a doc) and a verified link to one of browsers' code that would suggest `<param>` element removal.

Obsoletion is not the same as removal. For backwards compatibility browsers support many deprecated and obsolete features.
 
> * latest spec: https://html.spec.whatwg.org/ (no word about  element being deprecated or obsolete)

Isn't its presence in [section 16.2, "Non-conforming features",](https://html.spec.whatwg.org/#non-conforming-features) enough? "Elements in the following list are entirely obsolete, and must not be used by authors".

**Comment by teoli2003** [comment]
> Isn't its presence in [section 16.2, "Non-conforming features",](https://html.spec.whatwg.org/#non-conforming-features) enough? "Elements in the following list are entirely obsolete, and must not be used by authors".

Yes, this is enough to mark them as deprecated.

We could add a note at the end of the description saying to use `<object data>` instead.

**Comment by Sebastian-Brud-Tectonic** [comment]
That is exactly what I was looking for. You are right about deprecation.

The comment about replacement (`data` attribute and adding sources) would be sufficient ❤️

**Comment by teoli2003** [comment]
Do you want to create the PR?

**Comment by Sebastian-Brud-Tectonic** [comment]
@bsmth - I am utmost grateful for your effort and terribly sorry for late response. I've been busy for two weeks and could not find enough time to resolve it myself.

Much appreciated

**Comment by bsmth** [comment]
> I am utmost grateful for your effort and terribly sorry for late response. I've been busy for two weeks and could not find enough time to resolve it myself.
> 
> Much appreciated

Not a problem, you're very welcome 🙌🏻
