### ISSUE TITLE
File API missing "type" under Instance Properties

### ISSUE THREAD

**Issue by kczx3** [mdn/content#31532]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/File

### What specific section or headline is this issue about?

Instance Properties

### What information was incorrect, unhelpful, or incomplete?

The browser compatbility table shows the `type` property however, up above in the Instance Properties section, there is no reference to the `type` property.

### What did you expect to see?

A paragraph explaining the `type` instance property.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/file`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/file/index.md
* Last commit: https://github.com/mdn/content/commit/8fd2ee72038310e3ecc387df235ffac1cb08775c
* Document last modified: 2023-12-02T09:32:56.000Z

</details>

**Comment by kczx3** [comment]
I guess this might be covered by the sentence stating that `File` also inherits properties from the `Blob` interface.  So if that is sufficient then please close this.

**Comment by skyclouds2001** [comment]
Yes, it was removed in https://github.com/mdn/content/pull/29539, so the BCD need to update, too

**Comment by wbamberg** [comment]
Sounds like we can close this?
