### ISSUE TITLE
MDN CSS Transitions example does not work in (at least) Firefox

### ISSUE THREAD

**Issue by onwsk8r** [mdn/content#31534]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_transitions/Using_CSS_transitions

### What specific section or headline is this issue about?

Transitioning display and content-visibility

### What information was incorrect, unhelpful, or incomplete?

The example at the bottom of the section defines a CSS transition as follows:

```css
  transition:
    opacity 1s,
    display 1s allow-discrete;
```

When running the example, however, the transition never plays. The JS that shows/hides the element works as expected.. Just no CSS transition.

### What did you expect to see?

A css transition

### Do you have anything more you want to share?

There's a keyframe definition (I think? A CSS selector that starts with `@`) that does not appear to be referenced anywhere - perhaps that's the issue.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_transitions/using_css_transitions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_transitions/Using_CSS_transitions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_transitions/using_css_transitions/index.md
* Last commit: https://github.com/mdn/content/commit/bed59f268d5e299beb538e435f08c4f4ce685980
* Document last modified: 2023-11-20T15:37:12.000Z

</details>

**Comment by Josh-Cena** [comment]
Please read https://developer.mozilla.org/en-US/docs/Web/CSS/@starting-style#browser_compatibility. `@starting-style` is not supported yet in Firefox.
