### ISSUE TITLE
CSP: style-src not restricting element.style.cssText assignment

### ISSUE THREAD

**Issue by qfan** [mdn/content#31533]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src

### What specific section or headline is this issue about?

Violation Cases

### What information was incorrect, unhelpful, or incomplete?

The "Violation Cases" section claims that `cssText` cannot be assigned to, when the example rule is `Content-Security-Policy: style-src https://example.com/`.

`
document.querySelector("div").style.cssText = "display:none;";
`

However, both Chrome and Firefox allow this operation when the example CSP is set.

![image](https://github.com/mdn/content/assets/1900202/260a8cb6-efa9-4f21-94e6-9fe579e99d0c)

### What did you expect to see?

Either:

1. Remove "cssText" from the Violation Cases, if it's supposed to be allowed in this case, OR,
2. Add browser compatibility example showing that both Chrome and Firefox do not implement according to spec.

### Do you have any supporting links, references, or citations?

![image](https://github.com/mdn/content/assets/1900202/6f9b34bb-d057-42ec-a922-0625c9e750fb)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/style-src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/style-src/index.md
* Last commit: https://github.com/mdn/content/commit/ebc9954c53b92385b8a99d7be95bd63c789bc029
* Document last modified: 2023-08-28T23:01:12.000Z

</details>

**Comment by Josh-Cena** [comment]
Duplicate of https://github.com/mdn/content/issues/11697
