### ISSUE TITLE
Possible typo in exception reasons text

### ISSUE THREAD

**Issue by schalkneethling** [mdn/content#31562]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define

### What specific section or headline is this issue about?

Exceptions

### What information was incorrect, unhelpful, or incomplete?

The second reason an exception can be thrown currently reads as follows:

> The extends option is specified and it is a valid custom element name

### What did you expect to see?

I assume it is meant to read:

> The extends option is specified and it is **not** a valid custom element name

### Do you have any supporting links, references, or citations?

N/A

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/customelementregistry/define`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/customelementregistry/define/index.md
* Last commit: https://github.com/mdn/content/commit/66b6d40a37daef8aa0013c44c310eeb2f0bcd7e1
* Document last modified: 2023-10-22T00:42:05.000Z

</details>

**Comment by Josh-Cena** [comment]
This is correct. You cannot extend another custom element. https://html.spec.whatwg.org/multipage/custom-elements.html#dom-customelementregistry-define-dev

> If extends is not null, then:
>
> If extends is a valid custom element name, then throw a "NotSupportedError" DOMException.
