### ISSUE TITLE
ClipboardEvent availability confusion

### ISSUE THREAD

**Issue by Faithfinder** [mdn/content#31564]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData

### What specific section or headline is this issue about?

Baseline compatibility banner

### What information was incorrect, unhelpful, or incomplete?

I'm confused about compatibility banner stating "Limited availability", while the full compatibility table it's linking to shows 2017 as the latest implementation.

### What did you expect to see?

Header and table data matching up

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/clipboardevent/clipboarddata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/clipboardevent/clipboarddata/index.md
* Last commit: https://github.com/mdn/content/commit/d76defab4ca13261e9de81ae1df125345f847b0a
* Document last modified: 2023-04-07T05:46:57.000Z

</details>

**Comment by hamishwillee** [comment]
Yes. That's wrong. Querying.

**Comment by skyclouds2001** [comment]
this is dumplite with https://github.com/mdn/yari/issues/10199, which previously issued at mdn/content but later moved to mdn/yari

**Comment by hamishwillee** [comment]
Closing. The MDN team don't maintain or have any control over this data so there is nothing people monitoring this repo can do about it.

Can you please repost in https://github.com/web-platform-dx/web-features , which is where the data is maintained?

**Comment by foolip** [comment]
https://github.com/web-platform-dx/web-features/issues/495 track the general problem in web-features. I think that @LeoMcA has already arranged to hide the Baseline banner on the affected pages until we fix this.

**Comment by bsmth** [comment]
Thank you @foolip 🙏🏻

**Comment by foolip** [comment]
I've also filed https://github.com/web-platform-dx/web-features/issues/572 about the specific issue with clipboard.
