### ISSUE TITLE
Baseline component seems to show incorrect Baseline status or BCD is incorrect

### ISSUE THREAD

**Issue by schalkneethling** [mdn/content#31566]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:defined

### What specific section or headline is this issue about?

The Baseline component

### What information was incorrect, unhelpful, or incomplete?

As can be seen in the screenshots below, Baseline indicated that the pseudo-class has limited availability seemingly because of a lack of support in Firefox and Safari. However, the compat table seems to indicate full support across all browsers.

### Baseline

![Alert box with a caution icon and text: "Limited availability. This feature is not Baseline because it does not work in some of the most widely-used browsers.](https://github.com/mdn/content/assets/10350960/34cc0145-6f4b-437d-b909-ec63dbda13f2)

### BCD

![Chart titled "Browser compatibility" showing support levels for a feature across different browsers. There's a link to report problems on GitHub.](https://github.com/mdn/content/assets/10350960/e924dbbe-3f80-4682-b087-26a3b7713d4a)

### What did you expect to see?

Baseline in green status.

### Do you have any supporting links, references, or citations?

CanIUse also seems to suggest a green Baseline status: https://caniuse.com/?search=:defined

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_defined`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:defined
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_defined/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by OnkarRuikar** [comment]
AFAIK baseline indicates status of all the features under a feature-group and not just one feature. Not all features under [`custom-elements v1`](https://github.com/web-platform-dx/web-features/blob/dfcd560dd00299d338ae3cdbf013b84d892056f2/feature-group-definitions/custom-elements.yml#L14) spec have been implemented by all the browsers. [[ref](https://github.com/web-platform-dx/web-features/pull/444)]

ping @ddbeck

**Comment by teoli2003** [comment]
Yari controls these banners. Nothing we can do on mdn/content.

Closing in favour of the issue in Yari.

**Comment by foolip** [comment]
I've filed https://github.com/web-platform-dx/web-features/issues/571 to sort this out in web-features.
