### ISSUE TITLE
Django built in authentication system no longer accepts GET method for requests against logout url

### ISSUE THREAD

**Issue by Neil-Carruthers** [mdn/content#31569]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication

### What specific section or headline is this issue about?

Logout template

### What information was incorrect, unhelpful, or incomplete?

"If you navigate to the logout URL (http://127.0.0.1:8000/accounts/logout/) then you'll see some odd behavior — your user will be logged out sure enough, but you'll be taken to the Admin logout page. That's not what you want, if only because the login link on that page takes you to the Admin login screen (and that is only available to users who have the is_staff permission)."

### What did you expect to see?

I expected to be able to see the custom logged_out.html page upon visiting the accounts/logout URI

### Do you have any supporting links, references, or citations?

https://docs.djangoproject.com/en/5.0/releases/4.1/#features-deprecated-in-4-1  GET method is deprecated

### Do you have anything more you want to share?

The "Testing in templates"  section will also need to be updated.  Specifically the  `<a href="{% url 'logout' %}?next={{ request.path }}">Logout</a>` element should probably be replaced with a POST form.

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/django/authentication`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/authentication/index.md
* Last commit: https://github.com/mdn/content/commit/93c9f9954bd14ae8877973e5fe3c1d8378e56f92
* Document last modified: 2023-12-15T05:50:02.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you. Yes, we haven't updated to Django 5 yet. I've assigned to me, but I'm away for two weeks from now and will not get to this until mid Feb at earliest.

**Comment by ShubhamOulkar** [comment]
@hamishwillee, can I push some PR's ? I am doing it from yesterday.

**Comment by hamishwillee** [comment]
@ShubhamOulkar If you want to create PRs they would be welcome. BUT, please make all changes as a PR to https://github.com/mdn/django-locallibrary-tutorial first, with explanation, so we can test them. Once that's done we make the same changes to this content repo.
