### ISSUE TITLE
Documents in different languages vary widely

### ISSUE THREAD

**Issue by Otto-J** [mdn/content#31575]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation

### What information was incorrect, unhelpful, or incomplete?

see
zh-cn https://developer.mozilla.org/zh-CN/docs/Web/API/NetworkInformation
en https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation

Documents in different languages vary widely

It is recommended to re-translate the Chinese, or synchronize the English part.

### What did you expect to see?

See the content of the more complete `conction`, which is now missing a lot of introductions

in Chinese:
版本内容差异较大，看中文不知道还有很多其他字段。兼容性更多的应该是`effectiveType`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/networkinformation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/networkinformation/index.md
* Last commit: https://github.com/mdn/content/commit/bb60fadaa7423d2195ae8727f197fa4361aa09df
* Document last modified: 2023-02-20T08:52:54.000Z

</details>

**Comment by Josh-Cena** [comment]
You need to send this to https://github.com/mdn/translated-content instead. cc @mdn/yari-content-zh

**Comment by yin1999** [comment]
Thank you @Otto-J, @Josh-Cena. I'll take this :)

**Comment by yin1999** [comment]
fixed in mdn/translated-content#17883

**Comment by Otto-J** [comment]
nice!
