### ISSUE TITLE
Issue with "<details>: The Details disclosure element": Invalid HTML

### ISSUE THREAD

**Issue by timbomckay** [mdn/content#3160]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

#### What information was incorrect, unhelpful, or incomplete?

[W3C Validator](https://validator.w3.org/) apparently considers a `<details>` without a `<summary>` to be invalid html but MDN has text & examples that show it without. 

> **Error**: Element `details` is missing a required instance of child element `summary`.

#### Specific section or headline?

- Second paragraph implies summary is optional.
    > **If the first child** of the `<details>` element is a `<summary>`...
- [A simple disclosure example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#a_simple_disclosure_example)

#### What did you expect to see?

Obviously the simple disclosure example shows how a browser will render a details element without a summary implying that it does actually work, but curious if W3C Validator is incorrect or if it's a fallback for details to show something. Guess I'd like to see either a warning saying "_W3C considers this invalid code but it's not because..._" or some other explanation.

#### Did you test this? If so, how?

I pasted the code from Simple Disclosure Example into the W3C Validator tool.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/details`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/details/index.html
* Last commit: https://github.com/mdn/content/commit/edae9945e6581feb70bed87eb9b4e3ba41d314d3
* Document last modified: 2021-01-07T15:27:42.000Z

</details>

**Comment by evilpie** [comment]
> The first summary element child of the element, if any, represents the summary or legend of the details. If there is no child summary element, the user agent should provide its own legend (e.g. "Details").

https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element

Doesn't sound to me like having no summary element is invalid.

**Comment by wbamberg** [comment]
Thanks for filing @timbomckay !

The [spec](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element) says:

> Content model:
>    One summary element followed by flow content.

...which implies that it is mandatory, but also says:

> If there is no child summary element, the user agent should provide its own legend (e.g. "Details").

...so the fallback behavior is also specced.

> curious if W3C Validator is incorrect

IIRC @sideshowbarker maintains this. I expect that (1) the validator is correct, it is invalid but (2) browsers should also implement the fallback. So our example ought to be rewritten to highlight that ("you shouldn't do this, but look, the browser will supply a fallback").

**Comment by sideshowbarker** [comment]
> I expect that (1) the validator is correct,

Yeah, the validator is conforming to the spec requirements on this.

> it is invalid

Yes. Because the spec says, *“One `summary` element followed by flow content”*, it means if there’s no `summary` element, then no flow content is allowed either. If the spec wanted to allow the `summary` element to be omitted, the spec would instead say, *“One optional `summary` element followed by flow content”* or *“Zero or one `summary` element followed by flow content”*.

> but (2) browsers should also implement the fallback

Right — so, it’s not contradictory: The Content Model part states the requirement that authors must follow, and the other part states what browsers must do if authors ignore that requirement.
