### ISSUE TITLE
SMIL is not an extension of SVG

### ISSUE THREAD

**Issue by stcucufa** [mdn/content#31610]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_animation_with_SMIL

### What specific section or headline is this issue about?

Introduction

### What information was incorrect, unhelpful, or incomplete?

The very first sentence of the article states: “[Synchronized Multimedia Integration Language](https://www.w3.org/TR/REC-smil/) (SMIL) is an extension of [SVG](https://developer.mozilla.org/en-US/docs/Web/SVG) allowing to animating SVG elements.”

### What did you expect to see?

SMIL is not an extension of SVG; as far as I can tell, SMIL predates SVG. It is a completely self-contained language that deals with timing and synchronization in general and not just animations. This document should mention the SMIL Animation specification (see below) rather than SMIL as a whole, and not imply that SMIL is an extension of SVG, but rather that SVG makes use of this separate spec for animation purposes.

### Do you have any supporting links, references, or citations?

The [SVG 1.1 spec itself](https://www.w3.org/TR/SVG11/animate.html#AnimationElementsIntro) states:

The SYMM Working Group, in collaboration with the SVG Working Group, has authored the [SMIL Animation specification](http://www.w3.org/TR/2001/REC-smil-animation-20010904/) [[SMILANIM](https://www.w3.org/TR/SVG11/refs.html#ref-SMILANIM)], which represents a general-purpose XML animation feature set. SVG incorporates the animation features defined in the SMIL Animation specification and provides some SVG-specific extensions.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/svg_animation_with_smil`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_animation_with_SMIL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/svg_animation_with_smil/index.md
* Last commit: https://github.com/mdn/content/commit/b68049936ef4d1328e07065eafc87e3e43e826af
* Document last modified: 2023-12-20T15:10:27.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this, that's a nice distinction to make there. I'll open a PR for the linked branch to improve that section 👍🏻
