### ISSUE TITLE
The find.highlightResults() page does not say whether the highlights from the last find.highlightResults() call are erased or not

### ISSUE THREAD

**Issue by aljohnston112** [mdn/content#31623]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/find/highlightResults

### What specific section or headline is this issue about?

find.highlightResults()

### What information was incorrect, unhelpful, or incomplete?

The page says "Note that the stored results are global across all extensions, so for example, if extension A calls find("apple"), then extension B calls find("banana"), then if extension A calls highlightResults(), the results for "banana" will be highlighted."

What if you perform the calls find("apple"), highlightResults(),  find("banana"),  highlightResults() in that order? Do both words get highlighted?

I ask because I would like to make a plugin that can highlight found words different colors where the words are in a displayed PDF file. In the example above, it would highlight all occurrences of "apple" one color and all occurrences of "banana" another color. I am searching the API for ways to do that. Any pointers to the correct way to do this would be wonderful.

### What did you expect to see?

Clarification of what happens when the methods find("apple"), highlightResults(),  find("banana"),  highlightResults() are called in the order they appear.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/find/highlightresults`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/find/highlightResults
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/find/highlightresults/index.md
* Last commit: https://github.com/mdn/content/commit/2c5465eab20015868a1eeca59c5623d37b105f7c
* Document last modified: 2023-03-07T05:35:11.000Z

</details>

**Comment by rebloor** [comment]
As noted on find.find() "This function stores the results internally, so the next time any extension calls [find.highlightResults()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/find/highlightResults), then the results of this find call will be highlighted, until the next time someone calls find()." So, each call to find() overwrites the previous results.

You may be able to get some information about how to achieve what you want y posting on the [forum](https://discourse.mozilla.org/c/add-ons).
