### ISSUE TITLE
Live code example broken on `cancel` event page

### ISSUE THREAD

**Issue by sophiebits** [mdn/content#31621]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/cancel_event

### What information was incorrect, unhelpful, or incomplete?

If I click "Play" on either example, the JavaScript section of the resulting window that opens is blank.

### What did you expect to see?

Working code.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/cancel_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/cancel_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/cancel_event/index.md
* Last commit: https://github.com/mdn/content/commit/0900a5665090b4dc3b4936af5a48591521032bfd
* Document last modified: 2023-11-20T15:02:33.000Z

</details>

**Comment by skyclouds2001** [comment]
Interstingly, if directly control via script in the devtools console, everything is fine.
However, click the button takes not effect.
It seems that the script part is not included for unknown reason.

**Comment by wbamberg** [comment]
One weird thing in that page is that the argument to the macro: `{{ EmbedLiveSample('dialog_cancel', '100%', '100px') }}` does not match the heading: `\<dialog> element`.
