### ISSUE TITLE
What's the difference between a class prototype property and a function prototype property?

### ISSUE THREAD

**Issue by DanKaplanSES** [mdn/content#31649]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/prototype

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/prototype#value

### What information was incorrect, unhelpful, or incomplete?

Apologies upfront for misusing terminology. I'm still learning. By "class prototype property" I'm referring to the second line of this code:

   ```js
   class X { };
   X.prototype;
   ```

I'm assuming this is very similar to the topic of this article, the function instance `prototype` property.

---

The article says:

> Property attributes of Function: prototype
> --
> Writable | yes
> Enumerable | no
> Configurable | no
> 
> Note: The prototype property of [classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) is not writable.

1. Is this the only difference between the function prototype property and the class prototype property? 
   1. Regardless, could this be explicitly stated in the note for clarification?
3. Is there a reference article about the the _class prototype property_? The link in the note goes to a reference to classes in general, but I'm looking for something as focused as this function prototype article.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/function/prototype`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/prototype
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/function/prototype/index.md
* Last commit: https://github.com/mdn/content/commit/c2274293475b0a5b4febf85a49c1f91bf43ebac7
* Document last modified: 2023-05-03T02:24:26.000Z

</details>

**Comment by Josh-Cena** [comment]
A class is a type of function, so yes, everything else discussed here applies. What should we add? We never say classes are any different from functions in other places anyway.

**Comment by dipikabh** [comment]
@Josh-Cena would it help to further clarify the "Note" like so:

"Note: Classes are a type of function, so most of the same rules apply. However, the prototype property of a class is not directly accessible or modifiable from within an instance of that class."

> Is there a reference article about the the class prototype property? 

@DanKaplanSES, we do have a page on [Object prototypes](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes) but it does not have a specific mention of prototype property of a class. As Josh mentioned, a class is a type of function and the above note should be sufficient to highlight the differences between the two.

**Comment by DanKaplanSES** [comment]
@dipikabh I hope it's okay to reply even though you asked @Josh-Cena and not me: I think that note you wrote is a good solution that would resolve the original issue. Thanks.

**Comment by dipikabh** [comment]
Thanks @DanKaplanSES for opening the PR!
