### ISSUE TITLE
Missing reference/content

### ISSUE THREAD

**Issue by smith558** [mdn/content#31667]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals

### What specific section or headline is this issue about?

Fundamental text and font styling

### What information was incorrect, unhelpful, or incomplete?

The second paragraph states:

> If you have worked with HTML or CSS already, e.g., **by working through these tutorials in order**, then you know that text inside an element is laid out inside the element's content box. It starts at the top left of the content area (or the top right, in the case of RTL language content), and flows towards the end of the line.

The issue is with the part "**by working through these tutorials in order**". I just went through all the preceding materials and I believe this has not been covered anywhere.

### What did you expect to see?

The material covered in previous articles or a reference to an external article/documentation.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/styling_text/fundamentals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/styling_text/fundamentals/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by OnkarRuikar** [comment]
There is a note below the paragraph:
> Note: If the above paragraph leaves you feeling confused, then no matter — go back and review our [Box model](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model) article to brush up on the box model theory before carrying on.

I've submitted a [PR](https://github.com/mdn/content/pull/31678) to remove the unnecessary statement.

**Comment by smith558** [comment]
> There is a note below the paragraph:
> 
> > Note: If the above paragraph leaves you feeling confused, then no matter — go back and review our [Box model](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model) article to brush up on the box model theory before carrying on.
> 
> I've submitted a [PR](https://github.com/mdn/content/pull/31678) to remove the unnecessary statement.

Yes, but the article referenced does not contain content relevant to the topic. Reading the "Box model" article, there is no mention of how text behaves in relation to the content box.

**Comment by smith558** [comment]
> remove the unnecessary statement.

I think that may end up unhelpful rather than helpful.

**Comment by smith558** [comment]
> @smith558 I believe that's what the paragraph explains:
> 
> > It starts at the top left of the content area (or the top right, in the case of RTL language content), and flows towards the end of the line. Once it reaches the end, it goes down to the next line and flows to the end again. This pattern repeats until all the content has been placed in the box. Text content effectively behaves like a series of inline elements, being laid out on lines adjacent to one another, and not creating line breaks until the end of the line is reached, or unless you force a line break manually using the [](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br) element.

If that's all there is to explain then yes. The note and the "by working through these tutorials in order" part suggested that perhaps there's more and that it has been covered in previous articles (which it was not).
