### ISSUE TITLE
Using Storage change event on same page.

### ISSUE THREAD

**Issue by IDrumsey** [mdn/content#31665]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event

### What specific section or headline is this issue about?

Note: This won't work on the same page that is making the changes

### What information was incorrect, unhelpful, or incomplete?

Entire Note
```
Note: This won't work on the same page that is making the changes — it is really a way for other pages on the domain using the storage to sync any changes that are made. Pages on other domains can't access the same storage objects.
```

This note is a little unclear. What does the "same page" mean?

For instance, if I'm on `/myroute1` and I go into the dev tools and manually update the value, does that mean the code for `/route1` won't catch the event if I do `window.addEventListener("storage", (e) => {console.log(e.newValue)})`. I've tried this and it seems to work.

### What did you expect to see?

Clarification on what it means that it doesn't work *on the same page*.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/storage_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/storage_event/index.md
* Last commit: https://github.com/mdn/content/commit/cec2a003b670c686f1df5dba16d3b02073ad6711
* Document last modified: 2023-11-29T14:16:37.000Z

</details>

**Comment by skyclouds2001** [comment]
I think here if we use "same browser context" is better than "same page"

**Comment by skyclouds2001** [comment]
> For instance, if I'm on `/myroute1` and I go into the dev tools and manually update the value, does that mean the code for `/route1` won't catch the event if I do `window.addEventListener("storage", (e) => {console.log(e.newValue)})`. I've tried this and it seems to work.

Yes, in this case, if edit in devtools, it will trigger `storage` event. But if it is edit storage via script in the same browser context, it will not trigger the `storage` in the same browse context.
