### ISSUE TITLE
Update usage for {{AvailableInWorkers}}

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#31675]
the https://github.com/mdn/yari/pull/10029 brings additional ability to better reflect features' scope (and https://github.com/mdn/yari/pull/10968 which add one more case)

the issue is intended to track those features that need to update when the macros change landed (see https://github.com/mdn/yari/blob/main/kumascript/macros/AvailableInWorkers.ejs)

also reference to https://github.com/sindresorhus/globals

test with https://worker-playground.glitch.me/

the list is as follows:

```[tasklist]
### tasks
- [ ] #33477 
- [ ] #33225
- [ ] #32945
- [ ] #32942
- [ ] #32949
- [ ] WebUSB API, give up
- [ ] #32944
- [ ] #30191
- [ ] #33202 
- [ ] #35596 
- [ ] #33044
- [ ] #33052 
- [ ] #33056
- [ ] #33055
- [ ] #33061
- [ ] #33062
- [ ] #33091
- [ ] #33092
- [ ] #33093
- [ ] #33074
```

a full list is as follows:

* WebCodecs API, of https://w3c.github.io/webcodecs/
  * `AudioDecoder`
  * `VideoDecoder`
  * `AudioEncoder`
  * `VideoEncoder`
  * `EncodedAudioChunk`
  * `EncodedVideoChunk`
  * `AudioData`
  * `VideoFrame`
  * `VideoColorSpace`
  * `ImageDecoder`
  * `ImageTrackList`
  * `ImageTrack`
  * above in Window, DedicatedWorker
* WebRTC API, of https://w3c.github.io/webrtc-encoded-transform/
  * `RTCEncodedAudioFrame`
  * `RTCEncodedVideoFrame`
  * `SFrameTransformErrorEvent`
  * `SFrameTransform`
  * above in Window, DedicatedWorker
  * `DedicatedWorkerGlobalScope.rtctransform`
  * `KeyFrameRequestEvent`
  * `RTCTransformEvent`
  * above only in DedicatedWorker
* XMLHTTPRequest API, of https://xhr.spec.whatwg.org/
  * `XMLHttpRequest`
  * `XMLHttpRequestUpload`
  * `XMLHttpRequestEventTarget`
  * both in Window, DedicatedWorker, SharedWorker
* Web Serial API, of https://wicg.github.io/serial/
  * `WorkerNavigator.serial`
  * only in DedicatedWorker
  * `Serial`
  * `SerialPort`
  * both only in Window, DedicatedWorker
* WebUSB API, of https://wicg.github.io/webusb/
  * `WorkerNavigator.usb`
  * in DedicatedWorker, SharedWorker
  * `USBConnectionEvent`
  * `USBInTransferResult`
  * `USBOutTransferResult`
  * `USBIsochronousInTransferPacket`
  * `USBIsochronousInTransferResult`
  * `USBIsochronousOutTransferPacket`
  * `USBIsochronousOutTransferResult`
  * `USBDevice`
  * `USBConfiguration`
  * `USBInterface`
  * `USBAlternateInterface`
  * `USBEndpoint`
  * both in Window, DedicatedWorker, SharedWorker
* File API, of https://w3c.github.io/FileAPI/
  * `FileReaderSync`
  * only in DedicatedWorker, SharedWorker
  * `URL.createObjectURL()`
  * `URL.revokeObjectURL()`
  * in Window, DedicatedWorker, SharedWorker
* File System API, of https://fs.spec.whatwg.org/
  * `FileSystemSyncAccessHandle`
  * `FileSystemFileHandle.createSyncAccessHandle()`
  * both only in DedicatedWorker
* Web Worker API, of https://html.spec.whatwg.org/multipage/workers.html
  * `WorkerGlobalScope`
  * `WorkerNavigator`
  * `WorkerLocation`
  * above only in Worker
  * `Worker`, only in Window, DedicatedWorker, SharedWorker
  * `DedicatedWorkerGlobalScope`, only in DedicatedWorker
  * `SharedWorkerGlobalScope`, only in SharedWorker
* Service Worker API, of https://w3c.github.io/ServiceWorker/
  * `ServiceWorkerGlobalScope`
  * `Client`
  * `WindowClient`
  * `Clients`
  * `ExtendableEvent`
  * `FetchEvent`
  * `ExtendableMessageEvent`
  * both only in ServiceWorker
* Cookie Store API, of https://wicg.github.io/cookie-store/
  * `CookieStore` (except for `change` event)
  * `CookieStoreManager`
  * `ServiceWorkerRegistration.cookies`
  * above both in Window, ServiceWorker
  * `ExtendableCookieChangeEvent`
  * `ServiceWorkerGlobalScope.cookieStore`
  * `ServiceWorkerGlobalScope: cookiechange` event
  * above both only in ServiceWorker
* Notifications API, of https://notifications.spec.whatwg.org/
  * `NotificationEvent`
  * `ServiceWorkerGlobalScope: notificationclick` event
  * `ServiceWorkerGlobalScope: notificationclose` event
  * both only in ServiceWorker
* Content Index API, of https://wicg.github.io/content-index/spec/
  * `ContentIndexEvent`
  * `ServiceWorkerGlobalScope: contentdelete` event
  * both only in ServiceWorker
* Payment Handler API, of https://w3c.github.io/payment-handler/
  * `CanMakePaymentEvent`
  * `ServiceWorkerGlobalScope: canmakepayment` event
  * `PaymentRequestEvent`
  * `ServiceWorkerGlobalScope: paymentrequest` event
  * both only in ServiceWorker
* Background Fetch API, of https://wicg.github.io/background-fetch/
  * `BackgroundFetchEvent`
  * `BackgroundFetchUpdateUIEvent`
  * `ServiceWorkerGlobalScope: backgroundfetchsuccess` event
  * `ServiceWorkerGlobalScope: backgroundfetchfail` event
  * `ServiceWorkerGlobalScope: backgroundfetchabort` event
  * `ServiceWorkerGlobalScope: backgroundfetchclick` event
  * both only in ServiceWorker
* Web Background Synchronization API, of https://wicg.github.io/background-sync/spec/
  * `SyncEvent`
  * `ServiceWorkerGlobalScope: sync` event
  * both only in ServiceWorker
* Web Periodic Background Synchronization API, of https://wicg.github.io/periodic-background-sync/
  * `PeriodicSyncEvent`
  * `ServiceWorkerGlobalScope: periodicsync` event
  * both only in ServiceWorker
* Push API, of https://w3c.github.io/push-api/
  * `PushMessageData`
  * `PushEvent`
  * `PushSubscriptionChangeEvent`
  * `ServiceWorkerGlobalScope: push` event
  * `ServiceWorkerGlobalScope: pushsubscriptionchange` event
  * both only in ServiceWorker

**Comment by Josh-Cena** [comment]
@skyclouds2001 It's not easy to tell what tasks are left and when the issue could be considered done
