### ISSUE TITLE
using js in a script tag while running live server on VS CODE requires defer after the script tag to work. 

### ISSUE THREAD

**Issue by JonathanParham** [mdn/content#31691]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math

### What specific section or headline is this issue about?

running js in a browser

### What information was incorrect, unhelpful, or incomplete?

The js doesnt work correctly on a live server without defer added to the script tag. 

### What did you expect to see?

js code in vs code live server. 

### Do you have any supporting links, references, or citations?

https://forum.freecodecamp.org/t/javascript-code-not-running-on-a-live-sever-nor-local-host/463159/4

they discuss this issue here. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/math`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/math/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by wbamberg** [comment]
Can you please indicate exactly where there's a problem in MDN? Your report points to a section "running js in a browser" in the page https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math, but that section does not appear in that page.

**Comment by MohammedAslam106** [comment]
The defer means parsing HTML and downloading the javascript at the same time. Not including defer in the script tag doesn't bother the operation. It just slows down the HTML rendering because the HTML will stop parsing until the javascript code is downloaded on the browser.

**Comment by wbamberg** [comment]
I know what defer means. I'm asking where there is a problem in MDN.

**Comment by MohammedAslam106** [comment]
> I know what defer means. I'm asking where there is a problem in MDN.

I'm sorry, I'm not referring to you. I'm telling the author of this issue riser. And to close this issue.
