### ISSUE TITLE
[Tools] The option -r of rmdir not supported on Windows/mac

### ISSUE THREAD

**Issue by briannguyen2299** [mdn/content#31712]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line

### What specific section or headline is this issue about?

Creating, copying, moving, removing

### What information was incorrect, unhelpful, or incomplete?

The option `-r` of `rmdir` has been not supported on **Window 10**.

### What did you expect to see?

Use `/s` instead.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/command_line`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
* Last commit: https://github.com/mdn/content/commit/dfedc6e2f59e7072a9ced35ce4049a906438d74c
* Document last modified: 2023-08-11T00:30:18.000Z

</details>

**Comment by bsmth** [comment]
Thanks for raising this one, there's a note here: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line#introducing_command_options

That says to use the `man` command to find out the available options. It's tricky to cover all types of shells in one guide, and the options for each utility per shell available per OS and per OS version, so I'm not sure to list the correct command per setup is feasible. For instance, on my machine, I cannot use `rmdir -r` either, I have to use `rm -r` ; `rmdir` will not remove a directory that is not empty.

Maybe a note about portability (near the top of the article) and how commands can be different depending on the version? Hints to use `man command`, `which command`, and `command --version` (if it supports it?)
