### ISSUE TITLE
Test your skills: Object basics

### ISSUE THREAD

**Issue by wonland** [mdn/content#31721]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Test_your_skills:_Object_basics

### What specific section or headline is this issue about?

Test your skills: Object basics

### What information was incorrect, unhelpful, or incomplete?

The live code is different from the provided starting point code at https://github.com/mdn/learning-area/blob/main/javascript/oojs/tasks/object-basics/object-basics4-download.html

Also, there is a line that says "Try updating the live code below to recreate the finished example:", but there doesn't appear to be a link to that example.

### What did you expect to see?

Live code identical to the provided starting point code at https://github.com/mdn/learning-area/blob/main/javascript/oojs/tasks/object-basics/object-basics4-download.html

The line that says "Try updating the live code below to recreate the finished example:" should provide a link to that example.

### Do you have anything more you want to share?

Really curious about how the live example is solved!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/test_your_skills_colon__object_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Test_your_skills:_Object_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/test_your_skills_colon__object_basics/index.md
* Last commit: https://github.com/mdn/content/commit/c64e813d8ab9dbe22cbc049c26f7c6703370a2b7
* Document last modified: 2023-10-23T08:57:58.000Z

</details>

**Comment by ShubhamOulkar** [comment]
Needs changes in file https://github.com/mdn/learning-area/blob/main/javascript/oojs/tasks/object-basics/object-basics4-download.html.

it is same file [object-basics3-download.html](https://github.com/mdn/learning-area/blob/main/javascript/oojs/tasks/object-basics/object-basics3-download.html)
