### ISSUE TITLE
Mention HTML Standard in media element pseudo-classes

### ISSUE THREAD

**Issue by annevk** [mdn/content#31746]
Some pseudo-classes require host language integration. It might be useful to point out where that is defined.

In https://github.com/whatwg/html/pull/10051 we're adding host integration for the media element pseudo-classes to HTML.

**Comment by Josh-Cena** [comment]
If I understand correctly, there's no content change except to add one spec link?

**Comment by annevk** [comment]
I think so. Assuming the pseudo-classes are all covered.
