### ISSUE TITLE
CustomElementRegistry.define() "This feature is not Baseline because it does not work in some of the most widely-used browsers."

### ISSUE THREAD

**Issue by conartist6** [mdn/content#31764]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define

### What specific section or headline is this issue about?

Baseline

### What information was incorrect, unhelpful, or incomplete?

It is incomplete to the point of incorrect to say that browsers do not support this API. Some features of the API, features which are completely undocumented on this page, are not universally implemented. People need to know that what is actually described on this page is baseline usable!

### What did you expect to see?

Baseline: Widely Available

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/customelementregistry/define`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/customelementregistry/define/index.md
* Last commit: https://github.com/mdn/content/commit/66b6d40a37daef8aa0013c44c310eeb2f0bcd7e1
* Document last modified: 2023-10-22T00:42:05.000Z

</details>

**Comment by bsmth** [comment]
Hi @conartist6 - thanks a lot for opening this one. Please report this issue to https://github.com/web-platform-dx/web-features.

**Comment by foolip** [comment]
I've reported https://github.com/web-platform-dx/web-features/issues/571 for this issue.
