### ISSUE TITLE
Mention that offsetWidth value is integer and getBoundingClientRect().width is a decimal point number

### ISSUE THREAD

**Issue by jonex2** [mdn/content#31779]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Determining_the_dimensions_of_elements

### What specific section or headline is this issue about?

How much room does it use up?

### What information was incorrect, unhelpful, or incomplete?

I would mention that offsetWidth and offsetHeight values are integers and getBoundingClientRect().width and getBoundingClientRect().height are decimal point numbers. This is important if you need exact dimensions of an element.

### What did you expect to see?

Add my described information in the text 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/css_object_model/determining_the_dimensions_of_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Determining_the_dimensions_of_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/css_object_model/determining_the_dimensions_of_elements/index.md
* Last commit: https://github.com/mdn/content/commit/b280ea1234452ff553caa466bf532a66ba51db01
* Document last modified: 2023-02-19T06:34:57.000Z

</details>

**Comment by Josh-Cena** [comment]
Sure
