### ISSUE TITLE
C# WebSocket server example: Incompatible type for "offset"

### ISSUE THREAD

**Issue by SamHobbsOrg** [mdn/content#31774]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_server

### What specific section or headline is this issue about?

wsserver.cs in "Put together"

### What information was incorrect, unhelpful, or incomplete?

From the following lines:
`for (ulong i = 0; i < msglen; ++i)
    decoded[i] = (byte)(bytes[offset + i] ^ masks[i % 4]);`
I got the error _CS0034: Operator '+' is ambiguous on operands of type 'int' and 'ulong'_. I fixed the problem by making `offset` a `ulong`. I do not know if that is the best solution.

Otherwise, the sample works.

### What did you expect to see?

A clean build.

### Do you have any supporting links, references, or citations?

Try the build yourself.

### Do you have anything more you want to share?

No

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/websockets_api/writing_websocket_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_server
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/websockets_api/writing_websocket_server/index.md
* Last commit: https://github.com/mdn/content/commit/0bced7ea55d93bc774e632611353bd76b6269c9e
* Document last modified: 2023-11-23T07:58:58.000Z

</details>

**Comment by sambatya1** [comment]
Hello! Try
  ... decoded[i] = (byte)(bytes[**(ulong)**offset + i] ^ masks[i % 4]);

**Comment by Josh-Cena** [comment]
The `offset` variable should be declared as a `ulong` in the first place.

**Comment by ramshankarb** [comment]
Hi ! I would like to work on this issue.
