### ISSUE TITLE
SVG namespaces only work in XHTML, not HTML

### ISSUE THREAD

**Issue by sirreal** [mdn/content#31783]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course

### What specific section or headline is this issue about?

declaring_namespaces

### What information was incorrect, unhelpful, or incomplete?

There's an HTML example like this:

```html
<html
  lang="en"
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:svg="http://www.w3.org/2000/svg">
  <body>
    <h1>SVG embedded inline in XHTML</h1>
    <svg:svg width="300px" height="200px">
      <svg:circle cx="150" cy="100" r="50" fill="#ff0000" />
    </svg:svg>
  </body>
</html>
```

The SVG namespaces don't work in any major, modern browser as far as I can tell. All the namespaced elements seem to be treated as custom elements `SVG:SVG` instead of elements from the namespace `svg`.

You can see that the [SVG is not rendered here](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3Chtml%0A%20%20lang%3D%22en%22%0A%20%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxhtml%22%0A%20%20xmlns%3Asvg%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%20%20%3Cbody%3E%0A%20%20%20%20%3Ch1%3ESVG%20embedded%20inline%20in%20XHTML%3C%2Fh1%3E%0A%20%20%20%20%3Csvg%3Asvg%20width%3D%22300px%22%20height%3D%22200px%22%3E%0A%20%20%20%20%20%20%3Csvg%3Acircle%20cx%3D%22150%22%20cy%3D%22100%22%20r%3D%2250%22%20fill%3D%22%23ff0000%22%20%2F%3E%0A%20%20%20%20%3C%2Fsvg%3Asvg%3E%0A%20%20%3C%2Fbody%3E%0A%3C%2Fhtml%3E).

[Here, with the namespace prefixed removed, the svg is rendered as expected.](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3Chtml%0A%20%20lang%3D%22en%22%0A%20%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxhtml%22%0A%20%20xmlns%3Asvg%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%20%20%3Cbody%3E%0A%20%20%20%20%3Ch1%3ESVG%20embedded%20inline%20in%20XHTML%3C%2Fh1%3E%0A%20%20%20%20%3Csvg%20width%3D%22300px%22%20height%3D%22200px%22%3E%0A%20%20%20%20%20%20%3Ccircle%20cx%3D%22150%22%20cy%3D%22100%22%20r%3D%2250%22%20fill%3D%22%23ff0000%22%20%2F%3E%0A%20%20%20%20%3C%2Fsvg%3E%0A%20%20%3C%2Fbody%3E%0A%3C%2Fhtml%3E)

### What did you expect to see?

The HTML example explaining namespaces should work.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/namespaces_crash_course`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/namespaces_crash_course/index.md
* Last commit: https://github.com/mdn/content/commit/3c455281da6c6a000cba4bef573c999e91ae8cb7
* Document last modified: 2023-11-18T20:49:25.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! As the title says, this file is XHTML, not HTML. You need to make the browser render it as XHTML instead. For example, you could name your file with the .xhtml extension then view it with `file://` or use a local HTTP server.

<img width="1042" alt="image" src="https://github.com/mdn/content/assets/55398995/05be12a5-5db3-467f-aea2-a317983ecfe1">

We should probably mention that it only works with XML syntax but not HTML syntax.
