### ISSUE TITLE
Date.prototype.setMinutes, the minutes value is not between 0 and 59

### ISSUE THREAD

**Issue by harm-meijer** [mdn/content#31800]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMinutes

### What specific section or headline is this issue about?

minutesvalue

### What information was incorrect, unhelpful, or incomplete?

The minutes value is not between 0 and 59, if a value is higher than 60 or lower than zero then minutes are added (can be negative) to the date calculated in the following way: minutes passed - minutes of the date. Reference [here](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date.prototype.setminutes)

### What did you expect to see?

Not sure how to write this in documentation but minutes can be negative and higher than 60 as long as it is a finite number (see information that is incorrect).

### Do you have any supporting links, references, or citations?

https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date.prototype.setminutes

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/setminutes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMinutes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/setminutes/index.md
* Last commit: https://github.com/mdn/content/commit/6bd17cb9cbc2d11163617b9f71706e93fdd743c8
* Document last modified: 2023-04-28T03:58:12.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, what the language accepts is different from what it "conceptually represents". For example, you can pass a string too, and it will be coerced to a number, but that is not what you conceptually expect. The behavior you described is already mentioned below:

> If a parameter you specify is outside of the expected range, other parameters and the date information in the [`Date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) object are updated accordingly. For example, if you specify `100` for `secondsValue`, the minutes is incremented by 1 (`minutesValue + 1`), and 40 is used for seconds.
