### ISSUE TITLE
margin-left don't applies to ::first-line

### ISSUE THREAD

**Issue by Akindin** [mdn/content#31806]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/margin-left

### What specific section or headline is this issue about?

Formal Definition applies to

### What information was incorrect, unhelpful, or incomplete?

margin-left doesn't work on ::first-line pseudoelement

### What did you expect to see?

first line of text to have indentation

### Do you have any supporting links, references, or citations?

https://codepen.io/Akindin/pen/MWxmqVg

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/margin-left`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/margin-left
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/margin-left/index.md
* Last commit: https://github.com/mdn/content/commit/5e7d1f9ae2cce0cb3f7693dfb8dc6e8d375b2231
* Document last modified: 2023-07-18T00:16:24.000Z

</details>

**Comment by Akindin** [comment]
Same with margin-right

**Comment by MohammedAslam106** [comment]
The following properties apply to the ::first-line pseudo-element:

font properties
color properties
background properties
word-spacing
letter-spacing
text-decoration
vertical-align
text-transform
line-height
clear

We need to change the applies to section.

Source: https://www.w3schools.com/css/css_pseudo_elements.asp

**Comment by ferdnyc** [comment]
Indeed; the behavior can be confusing, too, because `margin` properties **do** apply to `::first-letter` (as the documentation claims), just not `::first-line`.

The content of Formal Definition sections is  auto-generated from data in the `mdn/data` repo, specifically (in this case) https://github.com/mdn/data/blob/main/css/properties.json which does (incorrectly) claim, for `margin-left`:

```json
   "alsoAppliesTo": [ 
     "::first-letter", 
     "::first-line" 
   ], 
```

That should just be:
```json
   "alsoAppliesTo": [ 
     "::first-letter"
   ],
```

I'll correct the `margin-{left,right,top,bottom}` definitions in that data, check for any other properties that claim `::first-line` support when they shouldn't, and open a PR in `mdn/data` to get that fixed. Thanks, @Akindin !

**Comment by wbamberg** [comment]
I wonder why though, [the spec for `:first-line` says](https://drafts.csswg.org/css-pseudo/#first-line-pseudo):

> The following CSS properties apply to a ::first-line pseudo-element:
> ...
> any other properties defined to apply to [::first-line](https://drafts.csswg.org/css-pseudo/#selectordef-first-line) by their respective specifications

...and [the spec for `margin` says](https://drafts.csswg.org/css-box/#placement):

> All properties in this module apply to the [::first-line](https://www.w3.org/TR/css-pseudo-4/#selectordef-first-line) and [::first-letter](https://www.w3.org/TR/css-pseudo-4/#selectordef-first-letter) pseudo-elements.

So is this nonstandard? (though it seems like Firefox, Chrome, and Safari all don't support it)

**Comment by ferdnyc** [comment]
@wbamberg Fair question!

I think the definition of [`::first-line`](https://www.w3.org/TR/selectors-3/#first-line) in [[SELECTORS-3]](https://www.w3.org/TR/selectors-3/) may be the overriding one, and it doesn't mention any such delegation. Only:

> The [::first-line](https://www.w3.org/TR/selectors-3/#sel-first-line) pseudo-element is similar to an inline-level element, but with certain restrictions. The following CSS properties apply to a [::first-line](https://www.w3.org/TR/selectors-3/#sel-first-line) pseudo-element: font properties, color property, background properties, ‘word-spacing’, ‘letter-spacing’, ‘text-decoration’, ‘text-transform’, ‘line-height’. UAs may apply other properties as well.

**Comment by ferdnyc** [comment]
(Or, well, not overriding, but what's implemented at the moment. [[CSS-PSEUDO-4]](https://www.w3.org/TR/css-pseudo-4/#first-line-inheritance) perhaps isn't implemented in the browsers yet?)

**Comment by ferdnyc** [comment]
CanIUse [entry for `::first-line`](https://caniuse.com/css-first-line) also cites SELECTORS-3 as the spec that defines it.
