### ISSUE TITLE
<input type="search"> missing search event in technical summary

### ISSUE THREAD

**Issue by flip111** [mdn/content#31810]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

### What specific section or headline is this issue about?

Technical summary

### What information was incorrect, unhelpful, or incomplete?

Events

### What did you expect to see?

change, input and search

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/search_event

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/search`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/search/index.md
* Last commit: https://github.com/mdn/content/commit/72ca3d725e3e56b613de3ac9727bd0d6d619c38a
* Document last modified: 2024-01-08T13:33:20.000Z

</details>

**Comment by bsmth** [comment]
Thanks for raising @flip111 - indeed @MohammedAslam106 has the answer. I'm not sure if it's a strict editorial guideline, but I have not found any other non-standard (or experimental / deprecated) events in any technical summary section, so this is the reason it's not included. I'm going to close as not planned, but feel free to reply or let me know if you think I've made a mistake. Thank you :)
