### ISSUE TITLE
Issue with "Browser storage limits and eviction criteria": (Imprecise storage limit definition.)

### ISSUE THREAD

**Issue by bart5** [mdn/content#3181]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria

#### What information was incorrect, unhelpful, or incomplete?

Information about storage limit calculation.

#### Specific section or headline?

"The global limit is calculated as 50% of free disk space. In Firefox, an internal browser tool called the Quota Manager keeps track of how much disk space each origin is using up, and deletes data if necessary.

So if your hard drive is 500 GB, then the total storage for a browser is 250 GB."

#### What did you expect to see?

I would like to know if 50% quota is calculated from free disk space (as the first sentence suggests), or total disk space (as the last sentence makes me think).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/indexeddb_api/browser_storage_limits_and_eviction_criteria`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/indexeddb_api/browser_storage_limits_and_eviction_criteria/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Update the paragraph under Storage Limits to be more explicit as to how much space is available

**Comment by ayushi2019031** [comment]
I would like to work on this

**Comment by hamishwillee** [comment]
Thanks @ayushi2019031 you're assigned :-)
