### ISSUE TITLE
Editable code not functioning properly.

### ISSUE THREAD

**Issue by GodProZEE** [mdn/content#31817]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals

### What specific section or headline is this issue about?

Active learning: More color choices

### What information was incorrect, unhelpful, or incomplete?

The code sometimes displays the outputs that should be there **after** writing the code for all the color outputs. Sometimes writing the correct code doesn't show any change in the live output. The function that would change the color hasn't even been called in the screenshot attached below, yet it gives the output, even after pressing reset.

### What did you expect to see?

When the section of code that needs to be written by us hasn't been written, there shouldn't be any change in the live output. Instead, it automatically shows output that should be there after the solution has been typed out.

### Do you have anything more you want to share?

![image](https://github.com/mdn/content/assets/100044640/2c49439d-cb5c-4e95-9169-dc4d0241e0b3)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/conditionals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/conditionals/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by wbamberg** [comment]
Hmm, maybe the same issue as https://github.com/mdn/content/issues/29421 ? I wonder how many more of these there are.
