### ISSUE TITLE
Issue with the section 'Specificity' on MDN Page

### ISSUE THREAD

**Issue by sunit-developer** [mdn/content#31822]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

### What specific section or headline is this issue about?

Specificity

### What information was incorrect, unhelpful, or incomplete?

I think there is a mistake with this. Please see the attached screenshot.
<img width="452" alt="MDN issue" src="https://github.com/mdn/content/assets/157181137/2ee0c98f-322f-4b85-a03a-61dcaec3b0e5">

### What did you expect to see?

I expect to see this:
<img width="578" alt="Solution" src="https://github.com/mdn/content/assets/157181137/9e9df1b9-9523-4030-9666-b4fdae691127">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by OnkarRuikar** [comment]
A paragraph before the table on the same page says:
> The negation ([:not()](https://developer.mozilla.org/en-US/docs/Web/CSS/:not)), relational selector ([:has()](https://developer.mozilla.org/en-US/docs/Web/CSS/:has)), the matches-any ([:is()](https://developer.mozilla.org/en-US/docs/Web/CSS/:is)) pseudo-classes, and [CSS nesting](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Nesting_and_specificity) themselves don't add to specificity, but their parameters or nested rules do. The specificity weight that each contributes to the specificity algorithm is the specificity weight of the selector in the parameter or nested rule with the greatest weight.

Not all the selectors in `:not()` are considered. Only the selector with the greatest weight (`#mainBtn`) inside `:not()` is cosidered. So `1-0-1` is correct.

**Comment by sunit-developer** [comment]
Thank you so much @OnkarRuikar for clarifying this to me. I got it and I agree that 1-0-1 is correct.

I do apologize for any inconvenience.

Thank you again.😊

**Comment by sunit-developer** [comment]
Thank you so much @OnkarRuikar for clarifying this to me. I got it and I agree that 1-0-1 is correct.

I do apologize for any inconvenience.

Thank you again.😊
