### ISSUE TITLE
When writing in English, write English

### ISSUE THREAD

**Issue by gggustafson** [mdn/content#31831]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics

### What specific section or headline is this issue about?

General

### What information was incorrect, unhelpful, or incomplete?

The use of "single quote" to specify an apostrophe.
The use of "double quote" to specify a quotation mark. 

### What did you expect to see?

English - not techno-babble.

### Do you have any supporting links, references, or citations?

Try any English writing guide.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/javascript_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/javascript_basics/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>

**Comment by Josh-Cena** [comment]
"Single quote" and "double quote" are a proper English terms. "Apostrophe" is a different thing although it often is the same character as "single quote". And MDN is technical documentation, so we do use technical jargon. Not in this case, though.
