### ISSUE TITLE
Incorrect Pseudo-Class Category Implied

### ISSUE THREAD

**Issue by JosephChemaly** [mdn/content#31837]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Pseudo-classes_and_pseudo-elements

### What specific section or headline is this issue about?

Simple pseudo-class example

### What information was incorrect, unhelpful, or incomplete?

At the end of the section, `:invalid` is implied to be a structural pseudo-class (as opposed to a user-action pseudo class).

### What did you expect to see?

I expect to see it removed, or moved under the _User-action pseudo-classes_ subheading

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors/pseudo-classes_and_pseudo-elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Pseudo-classes_and_pseudo-elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/pseudo-classes_and_pseudo-elements/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by dipikabh** [comment]
Hello @JosephChemaly, in the section you've pointed out, the text says:

> All pseudo-classes behave in this same kind of way. They target some bit of your document that is in a certain state, behaving as if you had added a class into your HTML. Take a look at some other examples on MDN:
> 
> - [:last-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:last-child)
> - [:only-child](https://developer.mozilla.org/en-US/docs/Web/CSS/:only-child)
> - [:invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid)

This list is quite generic and is not suggestive of any category. Given that the first two pseudo-classes in the list are both [structural](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes#tree-structural_pseudo-classes), I can see how it can give the impression that they all share a category.

Regarding the categorization of `:invalid`, it falls under [input pseudo-classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes#input_pseudo-classes). `:invalid` is somewhat related to user interaction with forms, so it can be easily mistaken as a [user action pseudo class](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes#user_action_pseudo-classes).

I am closing this issue for now. If you believe your concern hasn't been fully addressed, please reopen this issue and ping me.

Thank you for using MDN!
