### ISSUE TITLE
cancelAnimationFrame using mismatched time values in sample

### ISSUE THREAD

**Issue by james-rae** [mdn/content#31840]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

In the sample, the `progress` variable is calculated by subtracting `Date.now()` from the callback time parameter.

In testing, `Date.now()` is epoch time, and the parameter to `requestAnimationFrame` looks like milliseconds since the session start.

So `progress` ends up being around negative 54 years 😄 .

### What did you expect to see?

Matching time basis. I believe something like this would work, but not sure what is preferred or standard (which is why I'm logging and not PR'ing a fix).

```
const start = document.timeline.currentTime;
```

### Do you have any supporting links, references, or citations?

[This MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now) claims `Date.now()` is epoch.

[This MDN page](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#parameters) claims the `requestAnimationFrame` parameter is equivalent to ` document.timeline.currentTime`.

I've also run the sample snippet in the MDN sandbox to confirm the values 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/cancelanimationframe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/cancelanimationframe/index.md
* Last commit: https://github.com/mdn/content/commit/843f6ef086591bcf46edc3959559836f22228922
* Document last modified: 2023-12-14T14:06:45.000Z

</details>

**Comment by dipikabh** [comment]
Hi @james-rae, thanks for raising your concern and for waiting to get this addressed.

It seems valid that the calculation of the start time and the interval need to based on the same time reference. One way to fix this is to change:

`const progress = timestamp - start;`

to 

`const progress = Date.now() - start;`

in which case, the `timestamp` argument in the `step` function can be omitted.

Alternatively, `const start = document.timeline.currentTime;` would also work.

Would you be interested in opening a PR to submit the fix?

**Comment by Victor-M-Giraldo** [comment]
Hey, would it be possible for me to take this?

**Comment by hamishwillee** [comment]
@Victor-M-Giraldo You can take any issue you like. The way this is handled is that you create a PR with the fix, and in the description add the line:
```
Fixes #31840
```

That adds a link to this issue so that it will be closed if your PR is accepted. Further, the existence of a link in this issue tells other readers that the problem is being worked on by someone else.

**Comment by Victor-M-Giraldo** [comment]
> @Victor-M-Giraldo You can take any issue you like. The way this is handled is that you create a PR with the fix, and in the description add the line:
> 
> ```
> 
> Fixes #31840
> 
> ```
> 
> 
> 
> That adds a link to this issue so that it will be closed if your PR is accepted. Further, the existence of a link in this issue tells other readers that the problem is being worked on by someone else.

Ah okay, understood. Thanks.
