### ISSUE TITLE
Internal links to headers not working on Pull_requests page

### ISSUE THREAD

**Issue by minaelee** [mdn/content#31859]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests

### What specific section or headline is this issue about?

All links to header anchor links in document

### What information was incorrect, unhelpful, or incomplete?

Links to other pages or sites work, but any links that direct elsewhere on the same page do nothing when clicked. 

Example: 
Near the top of the document, there are these three links:
>See the sections [Before you start](https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests#before-you-start), [Open a pull request](https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests#open-a-pull-request), and [After you open a pull request](https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests#after-you-open-a-pull-request) to learn more about our processes.

These are formatted correctly in Markdown for an internal link:
```
[Before you start](https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests#before-you-start)
[Open a pull request](https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests#open-a-pull-request)
[After you open a pull request](https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests#after-you-open-a-pull-request)
```

Yet do nothing when clicked. Tested in latest versions of Chrome & Safari on macOS and Chrome for Android. Same behavior in all.

I checked other pages and they did not seem to have a similar issue with internal links, such as https://developer.mozilla.org/en-US/docs/MDN/Community/Roles_teams - click the very first link for 'roles' and it will function as expected.

### What did you expect to see?

The links take you to the part of the page with the corresponding anchor/heading.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community/pull_requests`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/pull_requests/index.md
* Last commit: https://github.com/mdn/content/commit/bd939ba6c0cb26c61d85e74a75ae4a0c678e79d4
* Document last modified: 2023-11-08T16:43:10.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for bringing it up! I believe @dipikabh is going to work on these pages soon. The anchors are actually `#before_you_start` not `#before-you-start` (I think some IDEs automatically add the hyphenated version in Markdown docs)

**Comment by dipikabh** [comment]
Thanks for flagging these non-working links, @minaelee!
