### ISSUE TITLE
`@charset` is not deprecated

### ISSUE THREAD

**Issue by romainmenke** [mdn/content#31882]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@charset

### What specific section or headline is this issue about?

The intro

### What information was incorrect, unhelpful, or incomplete?

> The `@charset` [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) rule specifies the character encoding used in the style sheet. Although the first character in `@charset` is the @ symbol, it is not an [at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule). The [CSS syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_syntax) module deprecates this rule, defining it as an unrecognized legacy rule to be dropped when a stylesheet is grammar-checked, but it is [fully supported in all browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/@charset#browser_compatibility).

### What did you expect to see?

The current wording implies to CSS authors that `@charset` is deprecated.

While the specification only mentions a change in how `@charset` is parsed and exposed.
The feature was not deprecated.

Something like this might be better :

> The `@charset` [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) rule specifies the character encoding used in the style sheet. Although the first character in `@charset` is the @ symbol, it is not an [at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule). It is a specific byte sequence that can only be placed at the very beginning of a stylesheet.

### Do you have any supporting links, references, or citations?

https://github.com/w3c/csswg-drafts/issues/9838

**Comment by bsmth** [comment]
This was introduced in https://github.com/mdn/content/pull/31076 - @estelle do you want to take a look?

**Comment by estelle** [comment]
The CSS syntax module relevant part is https://drafts.csswg.org/css-syntax/#charset-rule.

> The algorithm used to [determine the fallback encoding](https://drafts.csswg.org/css-syntax/#determine-the-fallback-encoding) for a stylesheet looks for a specific byte sequence as the very first few bytes in the file, which has the syntactic form of an [at-rule](https://drafts.csswg.org/css-syntax/#at-rule) named "@charset".

> However, there is no actual [at-rule](https://drafts.csswg.org/css-syntax/#at-rule) named @charset. When a stylesheet is actually parsed, any occurrences of an [@charset](https://drafts.csswg.org/css-syntax/#at-ruledef-charset) rule must be treated as an unrecognized rule, and thus dropped as invalid when the stylesheet is grammar-checked.

> NOTE: In CSS 2.1, [@charset](https://drafts.csswg.org/css-syntax/#at-ruledef-charset) was a valid rule. Some legacy specs may still refer to a @charset rule, and explicitly talk about its presence in the stylesheet.

The current MDN text reads:

> The [CSS syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_syntax) module deprecates this rule, defining it as an unrecognized legacy rule to be dropped when a stylesheet is grammar-checked, but it is [fully supported in all browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/@charset#browser_compatibility).

To me, the current MDN text is a good reflection of the spec.

**Comment by romainmenke** [comment]
The spec text is aimed at implementers.

For CSS authors it isn't relevant how implementers parse `@charset`. It is only relevant how the feature works as a whole.

For CSS authors no part of the feature was deprecated.
It also isn't relevant to them that historically it was parsed differently in the distant past.

I also do not agree that the current MDN text reflects the specification in any way.

In the spec it is a note, separate from the main section. In the mdn text it is part of the first paragraph. This places greater importance on this aspect.

The mdn text associates browser support with the deprecation and legacy status by placing it in a single sentence. While support should be irrelevant here because the feature isn't deprecated as a whole.

-------

I know the current text is causing confusion.
See : https://github.com/stylelint/stylelint/issues/7492#issuecomment-1905709454

Do you foresee an issue for CSS authors in changing the text as I suggested?

**Comment by Josh-Cena** [comment]
My opinions:

1. The _feature_ of `@charset` as a special syntax is in no way deprecated and we should call that out.
2. The _syntax_ of `@charset` as an at-rule is deprecated, in the sense that in an alternative world it would just be a syntax error when encountered not at the start of the sheet. However under the status quo, all that developers would care about is that it has no effect.

Therefore I think what would both reflect the spec and developer intuition is:

1. Stop calling it an at-rule. Call it a special directive or whatever CSS terminology there is.
2. Say that it only works at the very top of the sheet and is ignored in other places.
3. Remove all mentions of deprecation; this feature is not going to be removed and I don't believe any existing behavior will be stripped in the future.

**Comment by OnkarRuikar** [comment]
To add more info to the context:

> Stylesheet authors should author their stylesheets in UTF-8, and ensure that either an HTTP header (or equivalent method) declares the encoding of the stylesheet to be UTF-8, or that the referring document declares its encoding to be UTF-8. (In HTML, this is done by adding a <meta charset=utf-8> element to the head of the document.)
>
> If neither of these options are available, authors should begin the stylesheet with a UTF-8 BOM or the exact characters
> `@charset "utf-8";`

From above note in the spec it seems `@charset` is the last resort to specify the .css file encoding, if all other mechanisms are not available.

So they suggest:
- use HTTP header [`Content-Type`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) 
- or `<meta charset=utf-8>` in HTML docs
- or use [UTF-8 BOM](https://www.w3.org/International/questions/qa-byte-order-mark#bomwhat). Make sure your IDE/editor does this.
- or use string directive `@charset "utf-8";`. I think this is good to have if you are not sure how your .css library is going to get deployed and edited. You may have special text, e.g. `content: "शैली";`, in some rule.

***

There is , however, [a deprecation mentioned](https://drafts.csswg.org/css-syntax/#environment-encoding) in the same section of the spec:
> The concept of [environment encoding](https://drafts.csswg.org/css-syntax/#environment-encoding) only exists for compatibility with legacy content. New formats and new linking mechanisms should not provide an environment encoding, so the stylesheet defaults to UTF-8 instead in the absence of more explicit information.

This is about mentioning encoding while linking style sheets from other languages, e.g. HTML, XML.  And we have already addressed it on MDN: [the `charset` attribute ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#charset) on `<link>` element has been [marked deprecated in 2017](https://github.com/mdn/browser-compat-data/commit/937dcf696593c69b6f19328d90a35dcb4fdf2744#diff-32d079958f0c9f60abd695ade70458e3db096ad173867bcef06f76b54afabe06R104). Point being instead of specifying encoding on each css liking tag, specify it in the doc header.

**Comment by bsmth** [comment]
Regarding Josh's comment above, is the language in the "[changes in this spec](https://drafts.csswg.org/css-syntax/#changes-CR-20140220)" section helpful to refer to it as an 'encoding declaration'?

>`@charset` is no longer a valid CSS rule (there’s just an encoding declaration that looks like a rule named `@charset`)
