### ISSUE TITLE
report-to cannot accept a URI

### ISSUE THREAD

**Issue by supersime** [mdn/content#31881]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

### What specific section or headline is this issue about?

Enabling Reporting

### What information was incorrect, unhelpful, or incomplete?

The example shows report-to as a URI. But this is not valid, it must be a groupname.

### What did you expect to see?

A valid example! This current example is misleading.

### Do you have any supporting links, references, or citations?

https://content-security-policy.com/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/csp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/csp/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for flagging this one; I believe I mistakenly introduced that. Some references:

* https://w3c.github.io/webappsec-csp/#directive-report-uri
* https://www.w3.org/TR/reporting-1/#examples
