### ISSUE TITLE
No referer header on the Document Picture in Picture request

### ISSUE THREAD

**Issue by KetaoChen** [mdn/content#31899]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/DocumentPictureInPicture/requestWindow

### What specific section or headline is this issue about?

The request from the document picture in picture does not have a referer. 

### What information was incorrect, unhelpful, or incomplete?

The API and media request from my website have authentication logic based on the value of referer header. However, the request from the document picture in picture window does not have a referer header, which can result in http 403 error. 

### What did you expect to see?

The http request from Document Picture in Picture window has the same referer header as the origin window. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/documentpictureinpicture/requestwindow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DocumentPictureInPicture/requestWindow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/documentpictureinpicture/requestwindow/index.md
* Last commit: https://github.com/mdn/content/commit/4bb7edfa824ee4790abe60637b7876acd3eb827d
* Document last modified: 2023-11-01T23:12:59.000Z

</details>

**Comment by Josh-Cena** [comment]
This has nothing to do with `requestWindow`, which just opens up a new window. You would need to adjust the code yourself, such as by using `referrerPolicy`. If you think it's a browser bug, you can also report it to the respective browser, or to the spec. There's no MDN docs bug here.
