### ISSUE TITLE
Issue with "ParentNode.append()": Missing Browser compatibility

### ISSUE THREAD

**Issue by vrana** [mdn/content#3190]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append

#### What information was incorrect, unhelpful, or incomplete?

The *Browser compatibility* table is missing.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/parentnode/append`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/parentnode/append/index.html
* Last commit: https://github.com/mdn/content/commit/56d9a678477f0e79232caa8169114519bf02a44a
* Document last modified: 2021-02-19T19:41:18.000Z

</details>

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* It does appear that the browser compat data is missing - either that or the provided link is incorrect.
* Once resolved, this page (plus prepend and parentNode) need browser compat data adding

**Comment by Elchi3** [comment]
I'm currently reworking these docs. It is a mixin page that needs refactoring. It will soon appear as

Document.append()
Document.Fragmentappend()
Element.append()

and the different compat data for each of these methods will be there (change already made in BCD).

**Comment by Rumyra** [comment]
Amazing - thank you @Elchi3 ! I'll admit I was a bit confused I didn't find it in BCD ☺️

**Comment by Elchi3** [comment]
This got done :)
