### ISSUE TITLE
parentElement/parentNode should clarify the difference

### ISSUE THREAD

**Issue by 3052** [mdn/content#31900]
this page:

https://developer.mozilla.org/docs/Web/API/Node/parentElement

only references Node.parentNode in the See also section. this page:

https://developer.mozilla.org/docs/Web/API/Node/parentNode

only references Node.parentElement in the See also section. a natural question after viewing these two pages would be "what is the difference?"; this question goes unanswered

**Comment by bsmth** [comment]
Thanks a lot for raising this one @3052 - the answer is in the first sentence of each of the articles:

>parentNode ... returns the parent of the specified node in the DOM tree.

And

>parentElement ... returns the DOM node's parent [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element), or null if the node either has no parent, or its parent isn't a DOM [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element).

I think these are pretty good to differentiate, but maybe an example might help, what do you think?

**Comment by 3052** [comment]
no, I dont think the current pages are acceptable. the nature question that one will have is:

> what is the difference between parentElement and parentNode 

that question might be implicitly answered by reading the two pages and comparing, but it would be MUCH better if a sentence/paragraph/section was adding explicitly comparing the two
