### ISSUE TITLE
Doesn't every input need a name attribute?

### ISSUE THREAD

**Issue by davidstaab** [mdn/content#31918]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form

### What specific section or headline is this issue about?

Active learning: building a form structure

### What information was incorrect, unhelpful, or incomplete?

In step 5, we create the final input of the form, whose id is "expiration". That input doesn't have a name attribute. Isn't this wrong? Doesn't it mean the data won't be submitted with everything else in the form?

### What did you expect to see?

I expected to see a name attribute in this element:
``` html
<input
      type="text"
      id="expiration"
      required
      placeholder="MM/YY"
      pattern="^(0[1-9]|1[0-2])\/([0-9]{2})$" />
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/how_to_structure_a_web_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_structure_a_web_form/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by dipikabh** [comment]
Good catch, @davidstaab! Do you want to open a pull request to submit the fix?

**Comment by davidstaab** [comment]
Done. PR #32073
