### ISSUE TITLE
cancel event incorrectly defined as not bubbling for <input>

### ISSUE THREAD

**Issue by mary-ext** [mdn/content#31910]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/cancel_event

### What information was incorrect, unhelpful, or incomplete?

`<input type=file>` does in fact bubble `cancel` events if you cancel the file picker dialog.

### What did you expect to see?

Differentiate between `<dialog>` and `<input>`, because this got me while I was building a file picker inside a dialog, cancelling the file picker dialog closes the dialog as well due to it being bubbled.

- `<dialog>`: does not bubble
- `<input>`: does bubble

### Do you have any supporting links, references, or citations?

https://codepen.io/mary-ext/pen/ExMwGwr

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/cancel_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/cancel_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/cancel_event/index.md
* Last commit: https://github.com/mdn/content/commit/682c529a1be5f26ae378cb6affd56cdc15dddd4d
* Document last modified: 2024-01-15T09:26:24.000Z

</details>

**Comment by Josh-Cena** [comment]
Related: https://github.com/mdn/content/issues/31014
