### ISSUE TITLE
parseInt with 0x and 0

### ISSUE THREAD

**Issue by DarioViva42** [mdn/content#31921]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

If the input string, with leading whitespace and possible +/- signs removed, begins with 0x or 0X (a zero, followed by lowercase or uppercase X), radix is assumed to be 16 and the rest of the string is parsed as a hexadecimal number.

### What did you expect to see?

If the input string, with leading whitespace and possible +/- signs removed, begins with 0x or 0X (a zero, followed by lowercase or uppercase X), radix is assumed to be 10 and the rest of the string is parsed as a hexadecimal number.

### Do you have anything more you want to share?

Maybe I misunderstand this, but the fallowing javascript produces 16:
```js
parseInt(0xa, 16);
```
While the fallowing produces 10:
```js
parseInt(0xa, 10);
```
And the fallowing also produces 10:
```js
parseInt(0xa, 0);
```
So it seems to me, that 0 is behaving as 10 not as 16.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/parseint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/parseint/index.md
* Last commit: https://github.com/mdn/content/commit/a3102e6154717a0dda3f3e1b759b1c9e0f0b7275
* Document last modified: 2023-12-29T14:17:41.000Z

</details>

**Comment by Josh-Cena** [comment]
`0xa` is a number literal. It represents the exact same value as `10`, so it makes no difference to `parseInt`: you are essentially calling `parseInt("10", 16")` and `parseInt("10", 10)`. As mentioned in the parameter description, you should always pass strings to `parseInt`. `parseInt("0xa", 16)` will do what you want.
