### ISSUE TITLE
Connection: Keep-Alive - Docs state it is blocked in Safari when using HTTP2/3, is no longer blocked

### ISSUE THREAD

**Issue by DuncanWilder** [mdn/content#31923]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive states that requests with `Connection: Keep-Alive` set in Safari will fail when a request is made with HTTP2 or HTTP3. This is no longer the case (at least for HTTP3 requests in Safari 17.2.1)

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

Requests with `Connection: Keep-Alive` set in Safari to fail

### Did you test this? If so, how?

I created a basic Code Sandbox environment which make a request with the appropriate headers.

Hopefully this link will work for you to verify https://codesandbox.io/p/devbox/http2-keep-alive-fixed-w3wxzs

| Image | Description |
|--------|--------|
| ![Screenshot 2024-01-25 at 15 19 29](https://github.com/mdn/browser-compat-data/assets/5629994/b678286b-65b0-4a67-8b4b-eb330f1673ef) | Request working using http3 |
| ![Screenshot 2024-01-25 at 15 19 32](https://github.com/mdn/browser-compat-data/assets/5629994/870cf1cd-c64f-43b4-b39b-b240ef35fb69) | Showing appropriate header set |

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

It looks like this issue was originally raised in 2020 https://github.com/mdn/browser-compat-data/issues/6154

Page in question https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive

**Comment by Josh-Cena** [comment]
Hello, `Connection` is a forbidden header name. It's not possible to change it using `fetch`. `Connection: keep-alive` is already sent by browsers by default.

Furthermore, this note is saying that _responses_ that claim to be HTTP/2 but contain this header are treated as malformed when received. It's not saying that Safari prevents _requests_ of these forms to be sent.
