### ISSUE TITLE
WRONG: wrong warning for `CSS` `::part()`. It warns "Limited availability", but actually not.

### ISSUE THREAD

**Issue by BobH-Official** [mdn/content#31932]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::part

### What specific section or headline is this issue about?

Limited availability

### What information was incorrect, unhelpful, or incomplete?

It warned `Limited availability` at the start of the page. But according to the [browser compatibility on the same page](https://developer.mozilla.org/en-US/docs/Web/CSS/::part#browser_compatibility), all popular browsers support this feature. And according to [caniuse.com](https://caniuse.com/mdn-css_selectors_part) every browsers support， too.

### What did you expect to see?

Remove this warning message.

### Do you have any supporting links, references, or citations?

MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/::part#browser_compatibility

Can I Use: https://caniuse.com/mdn-css_selectors_part

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_doublecolon_part`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::part
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_part/index.md
* Last commit: https://github.com/mdn/content/commit/1c4eb0bfb5f72a26fcc21a83fac91aa3e66c2fb8
* Document last modified: 2024-01-02T16:00:45.000Z

</details>

**Comment by bsmth** [comment]
Hi @BobH-Official thanks a lot for opening this. Could you please report this issue to https://github.com/web-platform-dx/web-features? Thank you

**Comment by foolip** [comment]
I've filed https://github.com/web-platform-dx/web-features/issues/571 which covers the feature including `::part()` currently.
