### ISSUE TITLE
WebGL uniformMatrix[234]fv() method documentation is wrong.

### ISSUE THREAD

**Issue by leecommamichael** [mdn/content#31939]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/uniformMatrix

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

> A [GLboolean](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Types) specifying whether to transpose the matrix. **Must be false.**

### What did you expect to see?

This can be true **or** false.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webglrenderingcontext/uniformmatrix`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/uniformMatrix
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webglrenderingcontext/uniformmatrix/index.md
* Last commit: https://github.com/mdn/content/commit/eda49877b9078b24cd18f794470e5e225add9b94
* Document last modified: 2023-04-08T06:46:30.000Z

</details>

**Comment by vallentin** [comment]
> Must be `false`. 

- Is actually correct for [`WebGLRenderingContext.uniformMatrix`] (1.0)
- However, for [`WebGL2RenderingContext.uniformMatrix`] (2.0) is not

See more in #32836

[`WebGLRenderingContext.uniformMatrix`]: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/uniformMatrix
[`WebGL2RenderingContext.uniformMatrix`]: https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/uniformMatrix
