### ISSUE TITLE
No mention of "as" attribute

### ISSUE THREAD

**Issue by Akindin** [mdn/content#31960]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

### What information was incorrect, unhelpful, or incomplete?

No mention of as attribute

### What did you expect to see?

Mention of "as" attribute that is used in tag <link>

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#as

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/index.md
* Last commit: https://github.com/mdn/content/commit/fbabe3a287a1608f47f1146ee02013a486819f84
* Document last modified: 2023-07-04T07:44:28.000Z

</details>

**Comment by bsmth** [comment]
Hi @Akindin - thanks a lot for reporting this one. Would you like to open a PR to add it?

A spec link for reference:

https://html.spec.whatwg.org/multipage/semantics.html#attr-link-as

**Comment by Akindin** [comment]
@bsmth I would like to, but I don't know how

**Comment by bsmth** [comment]
Thanks @dawei-wang 👍🏻 

@Akindin, you can have a look at the linked pull request as an example of the process. If you need some more info, take a look here:

https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests
