### ISSUE TITLE
Only the backslash is removed from the value of the string

### ISSUE THREAD

**Issue by yanhaij** [mdn/content#31962]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types

### What specific section or headline is this issue about?

Escaping characters

### What information was incorrect, unhelpful, or incomplete?

This description is not accurate. "The backslash and line break are both removed from the value of the string." 
Because the line break is actually still stored in the value of the string.

### What did you expect to see?

The backslash is removed from the value of the string.

### Do you have any supporting links, references, or citations?

```js
const str =
  "this string \
is broken \
across multiple \
lines.";
console.log(str); // this string is broken across multiple lines.
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/grammar_and_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/grammar_and_types/index.md
* Last commit: https://github.com/mdn/content/commit/f138c70dc26c91451efa8401d1ca11efd8b33e41
* Document last modified: 2023-11-23T05:40:53.000Z

</details>

**Comment by Josh-Cena** [comment]
Have you tried?

<img width="360" alt="image" src="https://github.com/mdn/content/assets/55398995/421491e8-44ee-496c-bbaa-a2e7f6f03f9b">
