### ISSUE TITLE
Issue with "How the Web works": Packets Explained section uses TCP limitation to explain IP packet design

### ISSUE THREAD

**Issue by tjr226** [mdn/content#3197]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works

#### What information was incorrect, unhelpful, or incomplete?

An analogy explaining why packets are small relies on a TCP feature, the connection between two computers.

#### Specific section or headline?

Packets explained

#### What did you expect to see?

Something like this

"Packets are small for multiple reasons. They are sometimes dropped or corrupted, and it's easier to replace small packets. Additionally, the packets will likely be routed along different paths, making the whole exchange faster."

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/how_the_web_works`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/how_the_web_works/index.html
* Last commit: https://github.com/mdn/content/commit/5a6c608bd83fa2f3ba82c48ce4add6bc7891249b
* Document last modified: 2021-01-22T11:46:18.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can work on this :+1:

**Comment by chrisdavidmills** [comment]
Great, thanks!

**Comment by chrisdavidmills** [comment]
I'm glad this is being sorted out, BTW, this looks like something I have been taught wrongly, and carried with me for many years. It would be good to get @tjr226 's revuew once the PR has been submitted.

**Comment by ayushi19031** [comment]
I want to work on this. Thank you!!

**Comment by chrisdavidmills** [comment]
@ayushi19031 thanks for your interrest. First of all we'll check whether the current assignee is still interested in working on it.

@CreaTorAlexander this one has been with you for a while now. Do you think you will get to it in the next few days? I think I'd prefer to assign it to Ayushi to have a go at, if that's OK with you.

**Comment by CreaTorAlexander** [comment]
@chrisdavidmills I am not so active at the moment. You can reassign it 👍

**Comment by chrisdavidmills** [comment]
OK, thanks @CreaTorAlexander !

@ayushi19031 , I'll assign you now.

**Comment by ayushi19031** [comment]
Thank you
Will work on this
Sorry for the delay

**Comment by ayushi2019031** [comment]
Hi, I have made a PR to fix the issue. Please check. Thank you!!

**Comment by chrisdavidmills** [comment]
This has been resolved, so closing. Thanks @ayushi19031 !

**Comment by tjr226** [comment]
Hi - what's the best ticket to watch for when this change is shipped to the
docs?

I haven't contributed to this project before, so I'm not sure how to follow
the different issues around "strict mode"

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works

Tim Rooney
415.271.6119
