### ISSUE TITLE
[ExprFeature][CSS] :state() should be allowed after ::part()

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#31971]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

`::part`
- https://github.com/mdn/content/issues/31932
- https://github.com/mdn/content/issues/23471

`:state()`
- From https://bugzilla.mozilla.org/show_bug.cgi?id=1866351#c7 it appears that current docs using `:--foo` are now wrong. Fixes in #31258 need review.
- BCD

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1866351

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
Status

- [ ] Docs
- [ ] BCD 
  - [ ] https://github.com/mdn/browser-compat-data/pull/22083
  - [ ] part
- [ ] Release note
- [ ] dev-docs-complete

**Comment by Josh-Cena** [comment]
I'll consider this done
