### ISSUE TITLE
Missing method call with nanoid

### ISSUE THREAD

**Issue by DevAtREC** [mdn/content#31994]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_interactivity_events_state

### What specific section or headline is this issue about?

Deleting tasks from state and UI

### What information was incorrect, unhelpful, or incomplete?

In the source for App.jsx, after the text "At this point, your App.jsx file should look like this:" is the following function

  function addTask(name) {
    const newTask = { id: `todo-${nanoid}`, name, completed: false };
    setTasks([...tasks, newTask]);
  }

### What did you expect to see?

I believe the assignment of newTask should look like this

const newTask = { id: `todo-${nanoid()}`, name, completed: false };

with parentheses after nanoid, denoting a function call.  In other words the assignment of newTask should be the same as found in the last code section of the "Adding a Task" section.

### Do you have anything more you want to share?

Yes, thanks very much for the React articles.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_interactivity_events_state
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.md
* Last commit: https://github.com/mdn/content/commit/32f666e453bdb8c93d305075453b6e304cae94de
* Document last modified: 2024-01-10T13:40:02.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this one @DevAtREC , would you like to open a pull request to make the changes?

**Comment by DevAtREC** [comment]
Pull request submitted a moment ago.  Thank you, @bsmth.

**Comment by bsmth** [comment]
Well done 🎉  

(fixed in https://github.com/mdn/content/pull/32087)
