### ISSUE TITLE
Issue with "this": …

### ISSUE THREAD

**Issue by mishotek** [mdn/content#320]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

#### What information was incorrect, unhelpful, or incomplete?
Text is aligned right in one of examples

#### Specific section or headline?
Examples
this in function contexts

#### What did you expect to see?
The text should be on the left

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/this`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/operators/this/index.html
* Report started: 2020-12-16T20:09:25.019Z

</details>

**Comment by mishotek** [comment]
![image](https://user-images.githubusercontent.com/15323936/102401229-6b556880-3ffc-11eb-90f1-371e01ee8a0c.png)

**Comment by sideshowbarker** [comment]
Fixed by adf4741f5356efdb5f0736f79f200809993ff2b0.
