### ISSUE TITLE
More clarification maybe required

### ISSUE THREAD

**Issue by ShiviPro** [mdn/content#32002]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block

### What specific section or headline is this issue about?

Identifying the containing block

### What information was incorrect, unhelpful, or incomplete?

In _point number four_, where the list of additional CSS properties affecting the _containing block_ for _absolutely positioned elements_ is mentioned; it might not be clear to the reader if it's because of **all** or **any** of the below-mentioned points. 

There is **or** used among individual point contents, but is it enough to imply the **individuality** of each list point ?

The fifth example does clarify that it's **any** of those aforementioned points(by just setting `transform` to a value other than `none`), but it appears only near the end of the page.

### What did you expect to see?

Wouldn't it be better if it was clarified then & there ?
It may be rephrased by just adding "any of" like so: 
> If the position property is absolute or fixed, the containing block may also be formed by the edge of the padding box of the nearest ancestor element that has `any of `the following:

This is what I think. I'm open to any other ideas.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/containing_block`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/containing_block/index.md
* Last commit: https://github.com/mdn/content/commit/856b52f634b889084869d2ee0b8bb62c084be04d
* Document last modified: 2023-07-17T22:37:27.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this one @ShiviPro - yes I think that's the right clarification to add. Would you like to open a pull request to change this?

**Comment by ShiviPro** [comment]
> Thanks a lot for raising this one @ShiviPro - yes I think that's the right clarification to add. Would you like to open a pull request to change this?

My pleasure @bsmth 
I'd love to open a PR.
