### ISSUE TITLE
The 'Sharing Files' example doesn't work on iOS

### ISSUE THREAD

**Issue by Seanitzel** [mdn/content#32019]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

### What specific section or headline is this issue about?

About the 'Sharing Files' example

### What information was incorrect, unhelpful, or incomplete?

Web Share is supposed to work on iOS Safari(as seen in the support table)
But it doesn't

### What did you expect to see?

An example that works on a supported device

### Do you have any supporting links, references, or citations?

Everything is on the page

### Do you have anything more you want to share?

Actually yes, I've found that sharing files only works as expected when the only property of the share object is the `files` array.
I think that's what the example should show, and maybe show an image or video share as well.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/share`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/share/index.md
* Last commit: https://github.com/mdn/content/commit/0f20b09ca00bc43ff68a212a4c9aa6a81bd0bd40
* Document last modified: 2023-10-30T22:09:50.000Z

</details>

**Comment by Josh-Cena** [comment]
Does't work for me on iPhone 13, Latest iOS & Safari. Output is "Your system doesn't support sharing these files" but I'm not sure why exactly or how to grant it permissions.

**Comment by OnkarRuikar** [comment]
Looks like it is a security issue. File sharing from these iframes is not allowed.

The code does work on iPadOS 17.4.1 but when hosted on on its own page: https://m8v7cc-1234.csb.app/ ([sandbox.io code](https://codesandbox.io/p/devbox/share-filessadfs-m8v7cc))

Let me know if the website works on your devices. Then we'll host the demo on [mdn.github.io](https://mdn.github.io/css-examples/animation-frames-timing-function/)

**Comment by Josh-Cena** [comment]
Can confirm it works standalone. Is it possible to make it work with some iframe `allow` attribute?

**Comment by OnkarRuikar** [comment]
> Is it possible to make it work with some iframe `allow` attribute?

Aah! There is a bug in the macro code: https://github.com/mdn/yari/pull/11292

**Comment by Josh-Cena** [comment]
Actually it seems to work now, closing
