### ISSUE TITLE
First sentence very academic and hard to understand

### ISSUE THREAD

**Issue by MoritzGiessmann** [mdn/content#32042]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dfn

### What specific section or headline is this issue about?

Main headline

### What information was incorrect, unhelpful, or incomplete?

The first sentence of the article.

> The `<dfn>` HTML element is used to indicate the term being defined within the context of a definition phrase or sentence. The ancestor `<p>` element, the `<dt>`/`<dd>` pairing, or the nearest `<section>` ancestor of the `<dfn>` element, is considered to be the definition of the term.

### What did you expect to see?

A more understandable, less academic sounding version of the text. Since I am not a native speaker, I did not dare to come up with a solution.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/dfn`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dfn
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/dfn/index.md
* Last commit: https://github.com/mdn/content/commit/e04d8d2766c468f149445c0bf438d09f9b2d188c
* Document last modified: 2023-06-13T08:10:47.000Z

</details>

**Comment by Josh-Cena** [comment]
Which specific phrase is hard to understand?

**Comment by MoritzGiessmann** [comment]
It may be just me, but I find the structure complicated to understand and the words are one technical term after another. If it was possible to split the sentences into multiple simpler parts, that would help.

**Comment by Josh-Cena** [comment]
The first sentence is hard to be broken down further. The second sentence could be reformatted as a list but the terms here are accurate and should be accessible given enough thought.

**Comment by mozfreddyb** [comment]
In the end, evaluating writing complexity is a subjective matter. But to add another opinion, I too find the wording complicated and would not be able to use a `dfn` element based on the article as it is right now. 

Many writing guides encourage people to favor active language over passive expressions. I think getting rid of "is used to", "term being defined" or "is considered" would be useful.

The repetition within "indicate a definition within the context of a definition phrase" is also worth untangling. The repitition of "definition" confused the heck out of me :-)

How about something like this?

```The <dfn> HTML element indicates a definition. The <dfn> element should be used in a complete definition statement, where the ancestor <p> element, the <dt>/<dd> pairing, or the nearest <section> ancestor of the <dfn> element, is considered to be the full definition of the term.```

**Comment by Josh-Cena** [comment]
One slight fix: "indicates a term to be defined". Other than that this looks great.
