### ISSUE TITLE
No mention of buffered attribute

### ISSUE THREAD

**Issue by Akindin** [mdn/content#32048]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

### What specific section or headline is this issue about?

Attributes

### What information was incorrect, unhelpful, or incomplete?

No mention of buffered attribute that contains time range of already buffered media. Same issue for audio tag page https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

### What did you expect to see?

Mention that buffered attribute can be specified to show time range of already buffered media

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/video`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/video/index.md
* Last commit: https://github.com/mdn/content/commit/d99316c13088f49762ad0f83b0cfe060a84be3bb
* Document last modified: 2024-01-28T04:31:13.000Z

</details>

**Comment by skyclouds2001** [comment]
I guess this must be a mistake, the `buffered` attribute is not in the standard, neither https://html.spec.whatwg.org/multipage/media.html#the-audio-element nor https://html.spec.whatwg.org/multipage/media.html#the-video-element

Though there existed a `buffered` property on `HTMLMediaElement` that will be inherited by `HTMLAudioElement` and `HTMLVideoElement`
