### ISSUE TITLE
Wrong output of `console.log()`

### ISSUE THREAD

**Issue by Amer-Adel** [mdn/content#32047]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_parenthesis_after_argument_list

### What specific section or headline is this issue about?

Unterminated strings

### What information was incorrect, unhelpful, or incomplete?

// '"Java" + "Script" = "JavaScript"'

### What did you expect to see?

// "Java" + "Script" = "JavaScript"

**Comment by Jaycat66** [comment]
> ### MDN URL
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_parenthesis_after_argument_list
> 
> ### What specific section or headline is this issue about?
> 
> Unterminated strings
> 
> ### What information was incorrect, unhelpful, or incomplete?
> 
> // '"Java" + "Script" = "JavaScript"'
> 
> ### What did you expect to see?
> 
> // "Java" + "Script" = "JavaScript"

**Comment by Josh-Cena** [comment]
Hi, on this page all string outputs are wrapped in quotes to make it more explicit that we are printing a string. It's not just this single case; you can tell from other examples above such as `// "PI: 3.141592653589793"`. Different browsers may choose to emit different texts in real life.
