### ISSUE TITLE
Missed information about the returned type of space character returned from Intl.NumberFormat.format

### ISSUE THREAD

**Issue by Dimas-e63s** [mdn/content#32059]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/format

### What information was incorrect, unhelpful, or incomplete?

Documentation didn't mention, that `Intl.NumberFormat.format` returns string value with space character having 160 unicode code (NO-BREAK SPACE) instead of 32 unicode space (SPACE) that is used most of the time in strings

### What did you expect to see?

I propose to add a warning or info alert component (better a warning) with information, that developers need to keep in mind that the returned string of `Intl.NumberFormat.format` will have 160 unicode code (NO-BREAK SPACE) space instead of 32 unicode space (SPACE).
So the comparison of two values, one as a returned value from the `Intl.NumberFormat.format` and the second one as a string equivalent will result in false when using the strict equality operator (===)

### Do you have any supporting links, references, or citations?

https://github.com/nodejs/node/issues/24674
https://stackoverflow.com/questions/55335550/two-instances-of-same-string-value-are-not-equal
https://stackoverflow.com/questions/54242039/intl-numberformat-space-character-does-not-match

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat/format`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/format
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
* Last commit: https://github.com/mdn/content/commit/fb85334ffa4a2c88d209b1074909bee0e0abd57a
* Document last modified: 2023-09-25T07:33:31.000Z

</details>

**Comment by Josh-Cena** [comment]
It is a general rule that you should never compare formatting output to static values. It's already mentioned here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

> Note: Most of the time, the formatting returned by `toLocaleString()` is consistent. However, the output may vary with time, language, and implementation — output variations are by design and allowed by the specification. You should not compare the results of `toLocaleString()` to static values.

Why are you testing the formatted output?

**Comment by Dimas-e63s** [comment]
@Josh-Cena thanks for the response!

Answering your question of why am I testing the formatted output. It's a part of an automated test suite, where I need to verify that the number is rendered in the component in the currency format.

I didn't know about the relationship between the `Internalization API` and the algorithm of the `toLocaleString()` Numbers' prototype method, where it was mentioned that values shouldn't be compared, as well as X people, who were using `Internalization API` and were creating questions on StackOverflow when they were getting `false` value when trying compare static value with the result of `Intl.NumberFormat.format`. It's unclear from the Internalization API docs, that such a relationship exists, but on the different page of the docs

My questions are:
- what do you think am I misusing the Internalization API, when trying to format number to currency and test against it?
- should we include some information in the Internalization API to raise awareness of people who are using this API about the differences between returned result and static value?

**Comment by Josh-Cena** [comment]
> what do you think am I misusing the Internalization API, when trying to format number to currency and test against it?

You are using it right to format it; I'm pretty sure you are not supposed to test against it, or at least not against static strings. A better option is just to assert that the final text is not the input (i.e. it has undergone some type of formatting).

> should we include some information in the Internalization API to raise awareness of people who are using this API about the differences between returned result and static value?

Yes. I'm not sure exactly how, though. I personally don't want to see this note copy/pasted on every Intl page, but it's actually a pervasive misunderstanding, so I would say at least we should add it to `Intl.{DateTimeFormat,NumberFormat}.format`, since the `toLocaleString` counterparts already have this note.
