### ISSUE TITLE
The `x` and `y` attributes on text is actually a list

### ISSUE THREAD

**Issue by Mbodin** [mdn/content#32081]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text

### What specific section or headline is this issue about?

About the `x` and `y` attributes

### What information was incorrect, unhelpful, or incomplete?

As I understand the specification, one can place several values in the `x` and `y` attributes: https://www.w3.org/TR/SVG2/text.html#TextElementXAttribute What is presented in the page is thus incomplete, and the provided `Value type` for these attribute feels misleading.

### What did you expect to see?

I would have expected the `Value type` for `x` and `y` to be a list of values, as well as some explanation/example when the user puts in more than one values.

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/SVG2/text.html#TextElementXAttribute

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/element/text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/text/index.md
* Last commit: https://github.com/mdn/content/commit/5f7c22deaa74973658257aeaa012ac2ec0be87ae
* Document last modified: 2023-05-21T00:26:03.000Z

</details>

**Comment by ferdnyc** [comment]
(This also applies to `<tspan>` and deprecated `<tref>`, as well.)

**Comment by Josh-Cena** [comment]
For tspan, see https://github.com/mdn/content/issues/13831

**Comment by dipikabh** [comment]
The `x`, `y`, `dx`, `dy` value descriptions on the https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text page need to be updated to reflect support for a list of comma or space separated values, preferably with a supporting example.
