### ISSUE TITLE
ResizeObserver behaves differently depending on the window object on which it is called

### ISSUE THREAD

**Issue by guillaumebrunerie** [mdn/content#32095]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Resize_Observer_API

### What information was incorrect, unhelpful, or incomplete?

In applications with several windows, the ResizeObserver API behaves differently depending on whether it is called as `new ResizeObserver` or `new otherWindow.ResizeObserver`, but I couldn’t find any information at all about this behavior on MDN.

### What did you expect to see?

I expected to see a section (either in this page or in the ResizeObserver page) explaining that for applications with several windows, it is important to call `new otherWindow.ResizeObserver` and not simply `new ResizeObserver` as the later will not work properly.

### Do you have anything more you want to share?

Here is an example, click on the button and then resize the text area. Only the `popup.ResizeObserver` updates properly. Tested in both Chrome and Firefox.
https://codepen.io/Latcarf/pen/RwdyLXr?editors=0010

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/resize_observer_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Resize_Observer_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/resize_observer_api/index.md
* Last commit: https://github.com/mdn/content/commit/835d6632d59993861a0458510402787f8a2c3cb3
* Document last modified: 2023-10-25T17:27:32.000Z

</details>

**Comment by Josh-Cena** [comment]
Most DOM APIs will not work cross-realm because they are implicitly tied to the initial browsing context. I don't think it's worth adding to each MDN page as the probability of this happening is low, and for specific real-world engineering cases it's better discussed on a forum like StackOverflow.
