### ISSUE TITLE
Issue with documentation on the CSS pseudo element ::part()

### ISSUE THREAD

**Issue by codeandcloud** [mdn/content#32091]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::part

### What specific section or headline is this issue about?

Section just after heading says not widely supported, browser compatibility says otherwise

### What information was incorrect, unhelpful, or incomplete?

It says "Limited availbility" on the top section after the title.  
i.e., Not widely supported in Firefox/Safari
![image-1](https://github.com/mdn/content/assets/872421/6b1f3ff1-0762-4fc4-b1af-4de0c93c1711)
Browser Compatibility table says otherwise
![image-2](https://github.com/mdn/content/assets/872421/f5690c7d-f304-4472-a0ed-ccc90251aff9)

### What did you expect to see?

Consistency with the two sections or an explanation

### Do you have any supporting links, references, or citations?

Link: https://caniuse.com/mdn-css_selectors_part

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_doublecolon_part`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::part
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_part/index.md
* Last commit: https://github.com/mdn/content/commit/1c4eb0bfb5f72a26fcc21a83fac91aa3e66c2fb8
* Document last modified: 2024-01-02T16:00:45.000Z

</details>

**Comment by skyclouds2001** [comment]
you need to fire an issue about baseline at https://github.com/web-platform-dx/web-features instead

**Comment by hamishwillee** [comment]
Thanks. I'm closing this. The MDN team responsible for content don't have any ability to affect that banner, as noted ^^^, can you please re-raise this in the repo https://github.com/web-platform-dx/web-features

Closing.
