### ISSUE TITLE
Add "window.pageYOffset" and "window.pageXoffset" attributes description

### ISSUE THREAD

**Issue by polikm5** [mdn/content#32102]
please add "window.pageYOffset" and "window.pageXoffset" attributes description even if "window.scrollY" and "window.scrollX" are better.if i dont'know "window.pageXoffset" is equal to "window.scrollX", i will feel confused.

document: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollX

**Comment by bsmth** [comment]
Thanks a lot for reporting. This has been removed in https://github.com/mdn/content/pull/30529

Both are listed under https://developer.mozilla.org/en-US/docs/Web/API/Window as aliases and there's an example on both pages for `pageXOffset` and `pageYOffset` so I'm not sure what other improvements we can make. I'm going to close as won't fix for now, if you think I've made a mistake, feel free to reply and let me know what would improve the pages! Thank you :)
