### ISSUE TITLE
"autocomplete" attribute in Note Section Needs Fixing

### ISSUE THREAD

**Issue by ShubhamOulkar** [mdn/content#32105]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button#sect15

### What information was incorrect, unhelpful, or incomplete?

url referencing to `/button#autocomplete`

### What did you expect to see?

change to `/input#autocomplete`

change `<button>` element to `<input>` element in the note. 

### Do you have any supporting links, references, or citations?

none

### Do you have anything more you want to share?

none

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/button`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/button/index.md
* Last commit: https://github.com/mdn/content/commit/56f8b4b735a0c02f958121e29f0ec7adc890e7d1
* Document last modified: 2024-01-24T07:16:41.000Z

</details>

**Comment by skyclouds2001** [comment]
Yes, this is something that be left and not fixed in #31605

**Comment by Josh-Cena** [comment]
@dipikabh This issue is only about  a broken link. Could you update this issue title/description about what else needs to be done, or otherwise send a new issue?

**Comment by dipikabh** [comment]
Yeah, the issue reported here is fixed, so this can be closed. Thanks for the nudge, @Josh-Cena.
