### ISSUE TITLE
Proposal to remove page as manifest attribute is obsolete

### ISSUE THREAD

**Issue by Akindin** [mdn/content#32110]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html/manifest

### What information was incorrect, unhelpful, or incomplete?

Attribute itself is obsolete and not supported by modern browsers

### What did you expect to see?

Removal of the page

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/html/manifest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html/manifest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/html/manifest/index.md
* Last commit: https://github.com/mdn/content/commit/9dd7741a7e6bf4ba4341f4f039c9d8cad666e90f
* Document last modified: 2023-06-17T12:09:22.000Z

</details>

**Comment by wbamberg** [comment]
MDN's policy is to keep docs for 2 years after the last browser drops support for it. Since [Safari 16.3 was released in 2023](https://github.com/mdn/browser-compat-data/blob/69c6f1a47e5f35a1b97c2c3c8b942e1fa191ce6a/browsers/safari.json#L244-L250), it looks like we are not ready for this yet.

**Comment by Akindin** [comment]
Okay, added to the calendar
