### ISSUE TITLE
Promise.prototype.finally does not return an equivalent promise as stated in the docs

### ISSUE THREAD

**Issue by russelldavis** [mdn/content#32131]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

### What specific section or headline is this issue about?

Intro section, Return value section

### What information was incorrect, unhelpful, or incomplete?

The intro and the return value section both say that `finally` returns an equivalent promise, which is incorrect. If both the original promise and the return promise are successfully fulfilled, they will fulfill with the same value. But that doesn't make them equivalent. The returned promise can resolve at a different time than the original promise, and it can reject with a different reason than the original promise (or reject when the original promise fulfills).

Relatedly, the return value section says: "Otherwise, the return value of the handler does not affect the state of the original promise." This statement is misleading -- the return value of the handler can *never* afect the state of the original promise. Promise chaining never affects the state of the thing you chained off of. What the author meant to say is probably something like "The fulfilled value of the promise returned by the handler is ignored. If the handler's promise and the original promise are both fulfilled, the returned promise will fulfill with the value of the original promise."

### What did you expect to see?

Don't describe the return value as an equivalent promise. Clarify how the returned promise works.

### Do you have anything more you want to share?

Looks like the change was made at #16747 (cc @allan-bonadio @teoli2003 @OnkarRuikar)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise/finally`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
* Last commit: https://github.com/mdn/content/commit/88d71e500938fa8ca969fe4fe3c80a5abe23d767
* Document last modified: 2023-09-01T00:27:24.000Z

</details>

**Comment by Josh-Cena** [comment]
I probably won't have time to update this myself in the next few weeks, but yes your suggestions are justified. Feel free to send a PR.
