### ISSUE TITLE
Baseline widget incorrectly indicates "Limited availability"

### ISSUE THREAD

**Issue by opus131** [mdn/content#32138]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::part

### What specific section or headline is this issue about?

Baseline widget

### What information was incorrect, unhelpful, or incomplete?

The baseline widget shows "Limited availability", but based on the Browser compatibility table it should show "Baseline Widely available".

### What did you expect to see?

I expected the baseline widget to show "Baseline Widely available"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_doublecolon_part`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::part
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_part/index.md
* Last commit: https://github.com/mdn/content/commit/1c4eb0bfb5f72a26fcc21a83fac91aa3e66c2fb8
* Document last modified: 2024-01-02T16:00:45.000Z

</details>

**Comment by LeoMcA** [comment]
Thanks for reporting this: there's a wider issue at play which we're attempting to fix upstream, but for now I've added this page to a blocklist to temporarily hide the Baseline banner.
