### ISSUE TITLE
The example does not render

### ISSUE THREAD

**Issue by a0m0rajab** [mdn/content#32145]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Range/getClientRects

### What information was incorrect, unhelpful, or incomplete?

The example in this webpage is not rendering, it would be great if it rendered.	

![image](https://github.com/mdn/content/assets/18273833/32899b76-eaba-4cca-b4fd-30d8b94c28e8)

### What did you expect to see?

rendered version of the example. 

![image](https://github.com/mdn/content/assets/18273833/a995bdbf-5b5c-4c32-aea0-e56d765d147c)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/range/getclientrects`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Range/getClientRects
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/range/getclientrects/index.md
* Last commit: https://github.com/mdn/content/commit/1299320cc1dc0cfbca3de8bfc301b785ee30b2e8
* Document last modified: 2023-05-13T05:41:22.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing! I think this is a platform regression: the macro call doesn't pass any parameters, and this ought to (and used to) work, but now apparently it doesn't. Workaround is to pass a parameter identifying the section in which the source for the example can be found: https://github.com/mdn/content/pull/32203.
