### ISSUE TITLE
Issue with "Virtual ARM Linux environment": The repository does not have a Release file

### ISSUE THREAD

**Issue by drac98** [mdn/content#3214]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Virtual_ARM_Linux_environment

#### Specific section or headline?
Install the required software

#### Did you test this? If so, how?
Yes. I tried to add the Linaro's repository. It gave the following error.

Err:20 http://ppa.launchpad.net/linaro-maintainers/tools/ubuntu bionic Release                                                         
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
...                             
Reading package lists... Done 
E: The repository 'http://ppa.launchpad.net/linaro-maintainers/tools/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/developer_guide/virtual_arm_linux_environment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Virtual_ARM_Linux_environment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/developer_guide/virtual_arm_linux_environment/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by chrisdavidmills** [comment]
@drac98 I'm sorry you are having a problem with this page. Unfortunately this content is not in the MDN writing team's remit, so this is unlikely to be worked on any time soon. You'd probably be better off finding a dedicated Firefox help forum to ask in, for example in the [Mozilla Matrix server](https://wiki.mozilla.org/Matrix).

**Comment by himanshugarg** [comment]
This page no longer exists. We might as well close this bug.

**Comment by sideshowbarker** [comment]
> This page no longer exists. We might as well close this bug.

Yup — thanks
