### ISSUE TITLE
input type time and datetime-local don't match :out-of-range

### ISSUE THREAD

**Issue by Akindin** [mdn/content#32156]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/max

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

"Note: When the data entered by the user doesn't adhere to the maximum value set, the value is considered invalid in constraint validation and will match the [:invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid) and [:out-of-range](https://developer.mozilla.org/en-US/docs/Web/CSS/:out-of-range) pseudo-classes."

### What did you expect to see?

Clarifying information about input type date and datetime-local

### Do you have any supporting links, references, or citations?

https://codepen.io/Akindin/pen/yLwqvvJ

### Do you have anything more you want to share?

Was tested in 
Google Chrome Version 121.0.6167.140 (Official Build) (64-bit)
Yandex Browser 24.1.0.2571 (64-bit)
Mozilla Firefox 122.0.1 (64-bit)
Edge Version 121.0.2277.98 (64-bit)
Opera One(version: 106.0.4998.70)
Brave [Version 1.62.156]

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/max`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/max
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/max/index.md
* Last commit: https://github.com/mdn/content/commit/940cd0b4ec3a07a5d5895459145cee15065fbb2c
* Document last modified: 2023-04-17T00:05:31.000Z

</details>

**Comment by Josh-Cena** [comment]
They work for me:

<img width="975" alt="image" src="https://github.com/mdn/content/assets/55398995/d1e8b9e3-0a3f-494f-b8c7-cf2b8cfda7af">

I'm on macOS. Maybe it's a system issue?

**Comment by Josh-Cena** [comment]
Closing, but still welcoming follow-ups and may re-open.

This could possibly be an operating system issue, although unlikely.
