### ISSUE TITLE
Col as a child of colgroup

### ISSUE THREAD

**Issue by JustTheCoolest** [mdn/content#32172]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col

### What specific section or headline is this issue about?

Introduction paragraph

### What information was incorrect, unhelpful, or incomplete?

The para makes it sound like col must be in a colgroup, but that is not true

### What did you expect to see?

Rewrite the paragraph to clarify its intent without leading to this misconception

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/html401/struct/tables.html#h-11.2.4.2%22%3EW3C:~:text=They%20may%20appear%20inside%20or%20outside%20an%20explicit%20column%20group%20(i.e.%2C%20COLGROUP%20element).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/col`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/col/index.md
* Last commit: https://github.com/mdn/content/commit/fffabdeeb9a069e40a070dadeedc93298b2aca7e
* Document last modified: 2024-01-25T23:02:20.000Z

</details>

**Comment by Rumyra** [comment]
Hi @JustTheCoolest thanks for raising the issue.

The spec you have linked to is out of date - here is the current https://html.spec.whatwg.org/multipage/tables.html#the-col-element - as it states

> Contexts in which this element can be used: As a child of a colgroup element that doesn't have a span attribute.

So the MDN page is correct
