### ISSUE TITLE
Errors are already resolved

### ISSUE THREAD

**Issue by roy9495** [mdn/content#32195]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong

### What information was incorrect, unhelpful, or incomplete?

This [page](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong) refers to errors in code found on this [page](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash). However, it seems like the errors have already been fixed on the latter page.

### What did you expect to see?

Intentionally introducing bugs in the code to test the user's ability to find and resolve them with the help of the reference page https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/what_went_wrong`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/what_went_wrong/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>
```[tasklist]
### Tasks
```

**Comment by wbamberg** [comment]
Thanks for filing! Can you please be more specific about where the links are?

In https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong, under the heading "An erroneous example", I see links to:
- https://mdn.github.io/learning-area/javascript/introduction-to-js-1/troubleshooting/number-game-errors.html
- https://github.com/mdn/learning-area/blob/main/javascript/introduction-to-js-1/troubleshooting/number-game-errors.html

Both these pages have the expected errors: the first is the app, which does not work, and the second is the code, which includes errors like [`guessSubmit.addeventListener('click', checkGuess);`](https://github.com/mdn/learning-area/blob/93f1e27ea8f0e935c71709ce6bef8595629ff570/javascript/introduction-to-js-1/troubleshooting/number-game-errors.html#L86).

I don't see anywhere in the body of https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong that links to https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash. Can you point it out?

**Comment by roy9495** [comment]
Hi, in the first paragraph, it is mentioned 
~~~md
When you built up the "Guess the number" game in the previous article, you may have found that it didn't work. Never fear — this article aims to save you from tearing your hair out over such problems by providing you with some tips on how to find and fix errors in JavaScript programs.
~~~

**Comment by wbamberg** [comment]
Thanks for the clarification. What it's saying is that when you wrote the program, you might have had problems, and this article is going to show how to fix problems. I don't think there is an issue here.
