### ISSUE TITLE
meta: Only allow "Squash and merge" commits for this repo?

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/content#322]
See discussion in https://github.com/mdn/content/pull/314#pullrequestreview-554057697. We could limit reviewers to doing only "Squash and merge" commits, while still allowing, on demand, "Rebase and merge" commits (by admins).

The advantages of only allowing "Squash and merge" commits are:

* it keeps the https://github.com/mdn/content commit history clear, with informative commit messages
* it ensures that https://github.com/mdn/content commit shows every commit with a hyperlink to its associated PR
* it prevents making reviewers have to decide what kind of merges they should do, but not knowing how to choose

**Comment by vkWeb** [comment]
> We could limit reviewers to doing only "Squash and merge" commits, while still allowing, on demand, "Rebase and merge" commits (by admins). 

+1. We can mention admins when rebase & merge looks as the right choice.

**Comment by sideshowbarker** [comment]
Closing this, as the current state of things doesn’t seem to be causing any real problems for us
