### ISSUE TITLE
A JavaScript value of type symbol is not an object.

### ISSUE THREAD

**Issue by hagenhaus** [mdn/content#32207]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

### What specific section or headline is this issue about?

Constructor

### What information was incorrect, unhelpful, or incomplete?

This section states that `Symbol()` "Creates a new Symbol object." It doesn't. `Symbol()` creates a (primitive) value of type `symbol`. Note that `BigInt` and `Symbol` are similar in that both return `TypeError` when call as a constructor (with the `new` operator) and both return a primitive value when called as a function. There is an argument to be made that neither is a constructor function object at all, but ECMA-262 groups them with constructors. I like how the MDN `BigInt` page deals with this ambiguity. The Constructor section on the `BigInt` page states, "The `BigInt()` function returns primitive values of type `BigInt`." I suggest you do the same in the Constructor section of the `Symbol` page: "The `Symbol()` function returns primitive values of type `Symbol`."

### What did you expect to see?

The `Symbol()` function returns primitive values of type `Symbol`.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/BigInt

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/symbol`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/symbol/index.md
* Last commit: https://github.com/mdn/content/commit/e01fd6206ce2fad2fe09a485bb2d3ceda53a62de
* Document last modified: 2023-09-07T01:45:56.000Z

</details>

**Comment by Josh-Cena** [comment]
PRs welcome to make it say:

> Creates a new Symbol value.

**Comment by hagenhaus** [comment]
Glad to make appropriate changes to this page and submit a PR by Wednesday 2/14. Thanks.
