### ISSUE TITLE
Issue with "String.prototype.trimStart() ": (It also removes \n \r)

### ISSUE THREAD

**Issue by ssoni2074** [mdn/content#3221]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart

#### What information was incorrect, unhelpful, or incomplete?
It is documented that **trimStart() method removes whitespace from the beginning of a string.** 
But I can see that this is also removing characters like \n and \r (for other characters I didn't verified ).It should be made clear here! what it is supposed to remove. 

For trim() it is documented that **The trim() method removes whitespace from both ends of a string. Whitespace in this context is all the whitespace characters (space, tab, no-break space, etc.) and all the line terminator characters (LF, CR, etc.).**

#### What did you expect to see?
Only white spaces are removed and not other characters as per documentation

#### Did you test this? If so, how?
YES.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/trimstart`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/trimstart/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment]
> But I can see that this is also removing characters like \n and \r (for other characters I didn't verified ).It should be made clear here! what it is supposed to remove.

\n and \r are widely understand to be whitespace characters. The MDN glossary entry for “whitespace” at https://developer.mozilla.org/en-US/docs/Glossary/Whitespace says:

> The Infra Living Standard defines five characters as “ASCII whitespace”: U+0009 TAB, U+000A LF, U+000C FF, U+000D CR, and U+0020 SPACE.

\n is U+000A LF, and \r is U+000D CR

The https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart article doesn’t use the word “space” — it intentionally uses the specific word “whitespace”, to indicate it affects more than just space characters.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/3221#issuecomment-800838157
