### ISSUE TITLE
Issue with "Pretty-print a minified file": (short summary here please)

### ISSUE THREAD

**Issue by advantipro-gmbh** [mdn/content#3222]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Pretty-print_a_minified_file

#### What information was incorrect, unhelpful, or incomplete?
"Note: if you want to prettify some inline JavaScript code, just double click the code in the inspector pane."

#### Specific section or headline?
End of article, just above "Found a problem with this page?"

#### What did you expect to see?
This does not work for me.  I double-click the line of JS in the Inspector and Debugger, neither opens as Pretty Print.  JS in minified, but inline, within the HTML page source.
macOS: Catalina, 10,15,7
Firefox: 86,0,1

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/debugger/how_to/pretty-print_a_minified_file`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Pretty-print_a_minified_file
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/debugger/how_to/pretty-print_a_minified_file/index.html
* Last commit: https://github.com/mdn/content/commit/23eebf57a003f8a933aad06436d78fe127f8223e
* Document last modified: 2021-02-02T16:49:47.000Z

</details>

**Comment by chrisdavidmills** [comment]
Needs further looking at, but on quick inspection, I am able to confirm that double clicking some JS code somewhere inside the HTML source doesn't prettify it (at least, that's my understanding of what "inline JS" means)

**Comment by advantipro-gmbh** [comment]
> ...that's my understanding of what "inline JS" means
Correct, thanks, double-clicking this:
![image](https://user-images.githubusercontent.com/22052631/111455428-136ef080-8716-11eb-8a84-b0df90fe924b.png)
Becomes this:
![image](https://user-images.githubusercontent.com/22052631/111455519-2ed9fb80-8716-11eb-872e-e07833cb69df.png)
