### ISSUE TITLE
Dot notation can be used to set member names dynamically

### ISSUE THREAD

**Issue by Feeqi** [mdn/content#32221]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics#setting_object_members

### What information was incorrect, unhelpful, or incomplete?

From MDN article
- *One useful aspect of bracket notation is that it can be used to set not only member values dynamically, but member names too. Let's say we wanted users to be able to store custom value types in their people data, by typing the member name and value into two text inputs. We could get those values like this:*
- Acrodding to the article:
 - This work:
```js
const myDataName = nameInput.value;
const myDataValue = nameValue.value;
person[myDataName] = myDataValue;
```  
 - This won't work
 ```js
const myDataName = nameInput.value;
const myDataValue = nameValue.value;
person.myDataName = myDataValue;
```

### What did you expect to see?

This code also works
```js
const myDataName = nameInput.value;
const myDataValue = nameValue.value;
person.myDataName = myDataValue;
```

### Do you have any supporting links, references, or citations?

![first-contribute](https://github.com/mdn/content/assets/159620441/cfef6d78-397c-4dd2-8988-04e5c865058f)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/basics/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by srikanth-kandi** [comment]
I think you might have misunderstood the code example provided,

### Current Behaviour

```js
const myDataName = "height";
const myDataValue = "1.75m";
person[myDataName] = myDataValue;
```
running this code will create a key `height` with a value of `1.75m` within the `person` object like below

```js
person = {
  height: '1.75m'
}
```

In this case, if we access the `height` key using dot notation `person.height` will return `1.75m`.

### Expecting behaviour

The code you are expecting to work using dot notation will create a key `myDataName` with a value of `1.75m` within the `person` object like below

```js
const myDataName = "height";
const myDataValue = "1.75m";
person.myDataName = myDataValue;
```

```js
person = {
  myDataName: '1.75m'
}
```

So if we now access the `height` key using dot notation `person.height` will return `undefined`.

I hope you got a clarity about both are not same.

**Comment by Josh-Cena** [comment]
What @srikanth-kandi said.
