### ISSUE TITLE
paint-order also applies to HTML content (not only SVG)

### ISSUE THREAD

**Issue by mrego** [mdn/content#32236]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/paint-order

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

`paint-order` is already supported for HTML content in Firefox and Safari, and the feature [is coming to Chrome](https://groups.google.com/a/chromium.org/g/blink-dev/c/-eflVqNCtDY/m/jPnpYMhMAAAJ). It might be nice to include a example without SVG in this page.

### What did you expect to see?

A new example without using SVG for this property.
Maybe we need even a new entry in the browser compatibility table, as support in non SVG content has come later to browsers.

### Do you have any supporting links, references, or citations?

Intent-to-ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/-eflVqNCtDY/m/jPnpYMhMAAAJ
Example (works in Firefox and Safari or with the runtime flag in Chrome): https://jsfiddle.net/4mh71efb/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/paint-order`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/paint-order
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/paint-order/index.md
* Last commit: https://github.com/mdn/content/commit/0b26e0b94c77c3d34f0b8b77ba624a7323ccfdad
* Document last modified: 2023-04-07T05:18:00.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for opening this one @mrego. It might be nice to fix BCD for this also (I can do this if you like). The I2S is a great resource to dig through, I will also leave this as useful to track implementation bugs:

- https://issues.chromium.org/issues/41372165#comment6
