### ISSUE TITLE
Term "retailers" seems out of context

### ISSUE THREAD

**Issue by klequis** [mdn/content#32230]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Routers

### What specific section or headline is this issue about?

Routers #1

### What information was incorrect, unhelpful, or incomplete?

It took me a while to guess what the term "retailers" refers to and I am still not really sure. My best guess it is companies that sell routing equipment. However I would never think of these as retailers. That's more like Best Buy or something.

### What did you expect to see?

Something that tells the reader what a retailer is.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/routers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Routers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/routers/index.md
* Last commit: https://github.com/mdn/content/commit/ada5fa5ef15eadd44b549ecf906423b4a2092f34
* Document last modified: 2023-06-08T13:19:16.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. Yes, that whole sentence adds no value. Should be fixed by https://github.com/mdn/content/pull/32231
