### ISSUE TITLE
CSS snippet missing overflow: auto;

### ISSUE THREAD

**Issue by imadajerry** [mdn/content#32249]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type

### What specific section or headline is this issue about?

CSS code snippet

### What information was incorrect, unhelpful, or incomplete?

overflow: auto; was not written in the code snippet which makes the code work

### What did you expect to see?

For the code to work just by using the html and css given in the page. The code did not write overflow: auto; to be written in code snippet.

### Do you have any supporting links, references, or citations?

By trying to use the code written in the web page.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/scroll-snap-type`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/scroll-snap-type/index.md
* Last commit: https://github.com/mdn/content/commit/835d6632d59993861a0458510402787f8a2c3cb3
* Document last modified: 2023-10-25T17:27:32.000Z

</details>

**Comment by bsmth** [comment]
Hi @imadajerry - thanks for raising this one.

I took a look and the example looks like it's working as expected to me. Could you provide some more information about what you think it should look like?
