### ISSUE TITLE
<dialog> return value example combines two conflicting approaches

### ISSUE THREAD

**Issue by danevans** [mdn/content#32242]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

### What specific section or headline is this issue about?

Handling the return value from the dialog

### What information was incorrect, unhelpful, or incomplete?

The sample JavaScript includes
```javascript
// "Favorite animal" input sets the value of the submit button
selectEl.addEventListener("change", (e) => {
  confirmBtn.value = selectEl.value;
});
```
but `confirmBtn.value` is never read because `favDialog.close(selectEl.value);` sets the `favDialog.returnValue`.

This example feels like it is trying to show two different, conflicting ways to pass the return value. Either as the argument to the `.close` method or as the value of the `confirmBtn`.

### What did you expect to see?

There are two possible fixes and I'm not sure which ones is preferred. If I knew I would have opened a PR.

#### 1. Take the line:
```html
<button id="confirmBtn" value="default">Confirm</button>
```
and add the `formmethod` attribute:
```html
<button id="confirmBtn" value="default" formmethod="dialog">Confirm</button>
```
then delete this event handler entirely
```javascript
// Prevent the "confirm" button from the default behavior of submitting the form, and close the dialog with the `close()` method, which triggers the "close" event.
confirmBtn.addEventListener("click", (event) => {
  event.preventDefault(); // We don't want to submit this fake form
  favDialog.close(selectEl.value); // Have to send the select box value here.
});
```
now clicks on `confirmBtn` should use the value of the button being set in the change listener.

#### 2. Delete the change listener entirely (these lines):
```javascript
// "Favorite animal" input sets the value of the submit button
selectEl.addEventListener("change", (e) => {
  confirmBtn.value = selectEl.value;
});
```

### Do you have any supporting links, references, or citations?

The [docs for the `.close` method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close) say:
>  An optional string may be passed as an argument, updating the `returnValue` of the dialog.

Alternatively the [docs for the `returnValue`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/returnValue) say:
> Submitting a form with a `method="dialog"` closes the dialog and sets the return value to the `value`, if any, of the `button` or `input` elements of `type=submit`.

### Do you have anything more you want to share?

Both examples seem useful so it might help people to include both just separated so it's clear what the difference between using the `.close` method and the `formmethod="dialog"` with button values is.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/dialog/index.md
* Last commit: https://github.com/mdn/content/commit/9d1f2bdacf5cd7d1cd266c0c51e2d6e9a0f5e15c
* Document last modified: 2024-01-22T09:31:01.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this one. I had a look through and I think I prefer the second option to delete the listener:

```diff
-// "Favorite animal" input sets the value of the submit button
-selectEl.addEventListener("change", (e) => {
-  confirmBtn.value = selectEl.value;
-});
```

Would you like to open a PR for it? I'm happy to review 👍🏻

**Comment by danevans** [comment]
@bsmth sorry I took a while to respond but I opened a PR that is ready for review.

**Comment by estelle** [comment]
```
// "Favorite animal" input sets the value of the submit button
selectEl.addEventListener("change", (e) => {
  confirmBtn.value = selectEl.value;
});
```

The purpose of that function is to update the value of the submit button (it says so in the comments). The submit button is what gets returned. So it's indirectly setting it, but making it apparent to the reader.
This code was intentional. If it's confusing, it should be fixed, but it is important to show both methods.
