### ISSUE TITLE
KeyframeEffect is not defined: jest unit testing

### ISSUE THREAD

**Issue by federicomichela** [mdn/content#3225]
Hi everyone, I wrote a vue component that uses web animations api.

When I run the code it works just fine, but when I run the unit test I keep getting:

**ReferenceError: KeyframeEffect is not defined**

I'm using typescript, Vue3 and  jest. 

I've also installed the Web Animations API  polyfill npm package.

Am I missing something?

**Comment by himanshugarg** [comment]
Thanks @federicomichela for the bug report. Would you be able to add a link to the documentation you are following and a code sample of where the issue shows?

**Comment by sideshowbarker** [comment]
Closing for lack of response
