### ISSUE TITLE
Communication email addresses not able to receive mails

### ISSUE THREAD

**Issue by glmvc** [mdn/content#32302]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Communication_channels

### What specific section or headline is this issue about?

Mailing list

### What information was incorrect, unhelpful, or incomplete?

> For any nonpublic communication, send an email to [mdn-admins](mailto:mdn-admins@mozilla.org).

Sending an email to the given address returns:
`Your message wasn't delivered to mdn-admins@mozilla.org because the address couldn't be found, or is unable to receive mail.`

### What did you expect to see?

A working email address to which mails can be sent.

### Do you have anything more you want to share?

I checked [MDN on GitHub](https://github.com/mdn) and the organization's address is [mdn-github@mozilla.com](mailto:mdn-github@mozilla.com).

I've also tried sending an email to this address, but with following response/error:
>We're writing to let you know that the group you tried to contact (mdn-github) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
>...

It seems that the error is on the mozilla.com side. I can send emails to other addresses without any problems.
Are these official MDN communication email addresses?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community/communication_channels`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community/Communication_channels
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/communication_channels/index.md
* Last commit: https://github.com/mdn/content/commit/bd939ba6c0cb26c61d85e74a75ae4a0c678e79d4
* Document last modified: 2023-11-08T16:43:10.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for reporting, you can get in touch at `mdn-web-docs@mozilla.com` if you need to privately contact the team. This is fixed in the linked PR 👍🏻

**Comment by glmvc** [comment]
Thanks for the fix and the corrected address!
