### ISSUE TITLE
Issue with resizing of textarea elements in the example

### ISSUE THREAD

**Issue by mfialko** [mdn/content#32314]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

### What specific section or headline is this issue about?

Section - Examples, Chapter: Disabled and readonly, Example in result

### What information was incorrect, unhelpful, or incomplete?

It appears that the textarea elements in the example are reacting very sensitively to resizing via mouse movement. While you can freely resize the element, at a certain point, it unexpectedly jumps to a minimal height. Could you please address this issue? A video demonstrating the problem is attached for reference. Thank you.

https://github.com/mdn/content/assets/34963401/6f79bd53-ed64-4867-9147-c4c8455b02a8

### What did you expect to see?

I expect to see smooth resizing behaviour. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/textarea`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/textarea/index.md
* Last commit: https://github.com/mdn/content/commit/337fde08da46e0861c40458357831bba582439c5
* Document last modified: 2023-12-04T14:28:33.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for reporting this, I've opened a PR which I think improves these examples
