### ISSUE TITLE
Issue with "<set>": Seems to work with Firefox

### ISSUE THREAD

**Issue by vanillajonathan** [mdn/content#3231]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/set

#### What information was incorrect, unhelpful, or incomplete?
The browser compatibility table shows unknown status for Firefox but it actually seems to work.

#### Specific section or headline?
Browser compatibility

#### What did you expect to see?
Set listed as supported in Firefox.

#### Did you test this? If so, how?
Yes, the MDN page includes a black square that you can click on.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/element/set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/set
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/set/index.html
* Last commit: https://github.com/mdn/content/commit/33839eef38d5debdbb69297001771eeb527a0df5
* Document last modified: 2021-01-02T19:18:52.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for posting. Yes it does. Fixed in https://github.com/mdn/browser-compat-data/pull/9510

**Comment by himanshugarg** [comment]
The bcd table is updated. Is there more to this issue?

**Comment by vanillajonathan** [comment]
No it seems fine now, I'll close this issue as I consider it resolved.
