### ISSUE TITLE
aria-controls Associated Interfaces links to ariaBusy page

### ISSUE THREAD

**Issue by lukewarlow** [mdn/content#32332]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls#associated_interfaces

### What specific section or headline is this issue about?

Associated Interfaces

### What information was incorrect, unhelpful, or incomplete?

Page about aria-controls links to ariaBusy

### What did you expect to see?

It should link to ariaControls and reference the ariaControls property instead of ariaBusy

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/accessibility/aria/attributes/aria-controls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/attributes/aria-controls/index.md
* Last commit: https://github.com/mdn/content/commit/7e1956dbec8369ae5533be89e21cbce2d5a2ae1c
* Document last modified: 2024-02-07T15:42:45.000Z

</details>

**Comment by bsmth** [comment]
This is fixed in https://github.com/mdn/content/pull/32327, thanks a lot for reporting!
