### ISSUE TITLE
[Border-image generator] `border-style: solid` missing from CSS output

### ISSUE THREAD

**Issue by strarsis** [mdn/content#3233]
## URL(s)
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Border-image_generator

## Request type
- [ ] New documentation
- [x] Correction or update

## Details
The `CSS Code` section of the Border-image generator doesn't include the CSS declaration `border-style: solid;` which is required for all border-images without fill to be displayed in Chrome (and apparently prevents offset-differences in other browsers like Firefox, even when a fill is used, at least for the preview). As this CSS declaration is always required for proper display, it should also be always included in the generated `CSS Code` section, so developers won't be confused for why the border image for the copied CSS doesn't work:
```css
/* [...] */
border-style: solid;
````

## Related
https://github.com/mdn/sprints/issues/3210

**Comment by strarsis** [comment]
@chrisdavidmills: I ran into this issue again today (generating new border images using the generator on MDN).
It would be nice to have this fixed. I am sure, some develops become frustrated when the border simply doesn't want to show up in Chrome or has different offsets in other browsers.

**Comment by jsnkuhn** [comment]
Can confirm that there does seem to be an inconsistency between Firefox and Chrome on whether `border-image-width` alone is enough to render the `border-image` and that including a `border` declaration irons out the inconsistency (Will open a bug for this if one doesn't already exist). Seems like a best practice to include a fall back `border` declaration anyway just in case the `border-image-source` doesn't load or doesn't load right away.

It's the third div that's the heart of this in the codepen below. Firefox renders the border but Chrome does not.
https://codepen.io/jsnkuhn/pen/oNZqKwz?editors=0100

**Comment by jsnkuhn** [comment]
here are some possible fallback borders for each image: https://codepen.io/jsnkuhn/pen/xxqJrzj?editors=0100

**Comment by jsnkuhn** [comment]
updated longer image paths cause awkward box overflow. Still copy-able just visually a bit off: 
![image](https://user-images.githubusercontent.com/1286791/122760361-a614b380-d260-11eb-9575-d207965d4c9a.png)

**Comment by strarsis** [comment]
@jsnkuhn: Would it make sense to make the value elements adjust to their content heights, then nothing would overflow/scrolling.

**Comment by jsnkuhn** [comment]
looks like the shorter file paths are back so no overflow anymore but yeah nixing the set height would solve the trouble for good. My guess is the set height is there because of the `float` based layout. This must have been made when border-image was new and there were no other options. For long term probably best to redo the layout with flex and grid.

**Comment by strarsis** [comment]
@jsnkuhn: Could you also take a look at this issue? https://github.com/mdn/sprints/issues/3217#issuecomment-1008045159
It would be nice if the translated pages also get the updated Border image generator (from the English page).

**Comment by strarsis** [comment]
@jsnkuhn: Concerning the issue with the code not fitting into the DIV, what about using the CSS [`resize`](https://developer.mozilla.org/en-US/docs/Web/CSS/resize) property? This seems to be a simple solution.

**Comment by jsnkuhn** [comment]
@strarsis it looks like the border image generator is part of a different repo: https://github.com/mdn/css-examples/issues maybe we should move conversation over there. I have a pull request in for the overflow issue.

**Comment by strarsis** [comment]
@jsnkuhn: Great idea! This repository here is already very full with issues and PRs from all over the place.
