### ISSUE TITLE
Reverted [WebAPI] Enable Screen Wake Lock API by default

### ISSUE THREAD

**Issue by pepelsbey** [mdn/content#32338]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

- [Enable Screen Wake Lock API by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1874849)

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment]
Pretty much all work needed for this done API it went preview. Mostly its BCD, Release note.

Status:
- [ ] BCD https://github.com/mdn/browser-compat-data/pull/22255
- [ ] Docs
- [ ] Release note (add)
- [ ] Experimental feature (removal)
- [ ] dev-docs complete

**Comment by hamishwillee** [comment]
Unfortunately this was reverted to preview in https://bugzilla.mozilla.org/show_bug.cgi?id=1883724. So now I have to undo this stuff :-(

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/22583
- [ ] Release/Experimental features
- [ ] dev-doc-complete

**Comment by pepelsbey** [comment]
Thank you! Closing this one. Will create a new one once they’re ready to ship.
