### ISSUE TITLE
[Border-image generator]: Blue-white stripes example top/bottom borders missing

### ISSUE THREAD

**Issue by strarsis** [mdn/content#3234]
## URL(s)
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Border-image_generator
(Blue-white stripes example, 5th sample from the left at time of writing)

## Request type
- [ ] New documentation
- [x] Correction or update

## Details
When you visit the Border-image generator and select the blue-white stripes example (5th from the left), 
the upper and lower borders are missing from the result. The reason is that for this sample the top and bottom values of both, `border-image-slice` and `border-image-width`, are incorrectly set to `0.0` and aren't equal to the left and right values.

## Related
https://github.com/mdn/sprints/issues/3217

**Comment by jsnkuhn** [comment]
Is this really a mistake or is this example trying to show that you don't have to use all the sides of a source image?

**Comment by strarsis** [comment]
@jsnkuhn: Good point! I tried to find the author of that config (git blame), but this happened before the initial commit.
https://github.com/mdn/content/blame/8f18853974a69e0d60b3b2d8d10290c8b27417ad/files/en-us/web/css/css_background_and_borders/border-image_generator/index.html#L1957

So whether this is a design intent or not is not clear. What speaks against it is that the border image source image contains then unused graphic at the top and bottom edges.

**Comment by jsnkuhn** [comment]
Other thing about this example is that these days the diagonal stripes would more likely be done with a `repeating-linear-gradient` than an actual image.

**Comment by strarsis** [comment]
Yes, that would be more elegant. The border-image approach (e.g. with SVG) is suitable for custom borders that can't be replicated with available CSS gradients (or not trivially).
