### ISSUE TITLE
Document Digest Fields per rfc9530 and redirect `Digest` and `Want-Digest` header pages

### ISSUE THREAD

**Issue by Elchi3** [mdn/content#32364]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest

### What information was incorrect, unhelpful, or incomplete?

The https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Want-Digest HTTP header reference pages are outdated.

RFC9530 is new https://www.rfc-editor.org/rfc/rfc9530:

> This document defines HTTP fields that support integrity digests. The Content-Digest field can be used for the integrity of HTTP message content. The Repr-Digest field can be used for the integrity of HTTP representations. Want-Content-Digest and Want-Repr-Digest can be used to indicate a sender's interest and preferences for receiving the respective Integrity fields.

> This document obsoletes RFC 3230 and the Digest and Want-Digest HTTP fields.

### What did you expect to see?

HTTP header reference docs for:

- Content-Digest
- Repr-Digest
- Want-Content-Digest
- Want-Repr-Digest

And probably a supporting guide page, integration into the rest of the HTTP docs, etc.

### Do you have any supporting links, references, or citations?

https://www.rfc-editor.org/rfc/rfc9530

### Do you have anything more you want to share?

In BCD we removed the obsolete rfc urls already: https://github.com/mdn/browser-compat-data/pull/22263

**Comment by bsmth** [comment]
The following PR adds the missing pages:

- [x] https://github.com/mdn/content/pull/26885

It looks like we still need BCD for this, and "a supporting guide page" as you mentioned.

**Comment by bsmth** [comment]
There's no BCD for this as there's no browser support (this is application/implementation-specific). Some improvements landed here, so I would close as done for now:

- [x] https://github.com/mdn/content/pull/36879

**Comment by bsmth** [comment]
I would also link to this as the first BCD entry for traceability: https://github.com/mdn/browser-compat-data/pull/4600
