### ISSUE TITLE
Outdated Content In Express Tutorial Part 7

### ISSUE THREAD

**Issue by mohammednumaan** [mdn/content#32378]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment#example_hosting_on_railway

### What specific section or headline is this issue about?

Example: Hosting on Railway

### What information was incorrect, unhelpful, or incomplete?

The instructions for connecting a MongoDB database in Railway are outdated due to recent changes in the way database services work in Railway. The **Connect** tab for adding a *MongoDB connection URL* is no longer available. To resolve this issue, I believe we need to create a **Variable Reference** to the variable that stores the connection string.

### What did you expect to see?

I expected a "Connect Tab" to be displayed when selecting the added MongoDB service in the Railway project as mentioned in the Express Tutorial.

### Do you have any supporting links, references, or citations?

https://docs.railway.app/guides/variables#reference-variables

### Do you have anything more you want to share?

I'll be happy to work on this issue and make necessary changes.

**Comment by hamishwillee** [comment]
Fixed by #32381

**Comment by hamishwillee** [comment]
Thanks for the issue report and the fix.
