### ISSUE TITLE
Why here is said that Badges supported on android?

### ISSUE THREAD

**Issue by FY0u11** [mdn/content#32386]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Display_badge_on_app_icon

### What specific section or headline is this issue about?

Badges on android

### What information was incorrect, unhelpful, or incomplete?

[Mobile support](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Display_badge_on_app_icon#mobile_support)

Badges are supported on mobile operating systems, including Chromium-based browsers running on Android and in Safari on iOS and iPadOS, starting with iPadOS 16.4.

### What did you expect to see?

I'm expecting to see that badges are not supported on Android because here is said so https://developer.mozilla.org/en-US/docs/Web/API/Navigator/setAppBadge

Also I tried to check it manually. Badges are not shown.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/setAppBadge

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/progressive_web_apps/how_to/display_badge_on_app_icon`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Display_badge_on_app_icon
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/how_to/display_badge_on_app_icon/index.md
* Last commit: https://github.com/mdn/content/commit/2077d0702d038c9ccc743a53d8ad1c0c21fef5be
* Document last modified: 2024-01-28T23:01:02.000Z

</details>

**Comment by wbamberg** [comment]
@captainbrosset , do you have insight here? I'm not really set up to test this on Android. Certainly it looks like either this article or the BCD are wrong.

**Comment by captainbrosset** [comment]
You're right, `setAppBadge` doesn't do anything on Chrome on Android. I tested manually, and tthis chrome article confirms it: https://developer.chrome.com/docs/capabilities/web-apis/badging-api#support
So, we need to fix the docs.
