### ISSUE TITLE
Code snippet using the void return of canvas toBlob() function

### ISSUE THREAD

**Issue by tmessaoudi** [mdn/content#32385]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write#write_canvas_contents_to_the_clipboard

### What information was incorrect, unhelpful, or incomplete?

The code example is using canvas toBlob the wrong way (according to [MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob)) : 
- No callback is provided to the function toBlob() 
- It's using the void return of function toBlob() instead of using the callback

### What did you expect to see?

Something using toDataUrl() like in this doc https://web.dev/patterns/clipboard/copy-images : 
```js
// Get canvas can add an event handler for the click event.
const canvas = document.getElementById("canvas");
canvas.addEventListener("click", copyCanvasContentsToClipboard());

async function copyCanvasContentsToClipboard() {
  // Copy canvas to blob
  const url = canvas.toDataURL();
  const blob = await fetch(url).then(response => response.blob());
  // Create ClipboardItem with blob and it's type, and add to an array
  const data = [new ClipboardItem({ [blob.type]: blob })];
  // Write the data to the clipboard
  await navigator.clipboard.write(data);
}
```

It may be slower than just using toBlob(), but it's simpler. Actually it may be better to use the toBlob() just to see how we use the toBlob with simple code.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

My typescript types looks like that 
```    
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLCanvasElement/toBlob) */
    toBlob(callback: BlobCallback, type?: string, quality?: any): void;
```

### Do you have anything more you want to share?

I only tested manually and locally the corrected snippet I provided, but I didn't even try to use the toBlob() api. Maybe there is a better way with toBlob()

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/clipboard/write`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/clipboard/write/index.md
* Last commit: https://github.com/mdn/content/commit/7087ffd50a4d81d1b91fe603c26456e9ce398574
* Document last modified: 2024-01-09T04:36:06.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this one. I've opened a fairly small PR linked above which fixes this without going too overboard on adding somewhere to paste the image and adding it back to the DOM.
