### ISSUE TITLE
Issue with "BigInt": (short summary here please)

### ISSUE THREAD

**Issue by concastinator** [mdn/content#3241]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

#### What information was incorrect, unhelpful, or incomplete?

At the very bottom of the page, there is the text "Is this helpful?", followed by two buttons: "Yes" and "No".

#### What did you expect to see?

Clicking on any of the two should trigger some action, right?

#### Did you test this? If so, how?

Clicking on any of them doesn't trigger anything, nothing happens.

#### Test set-up

Firefox 86.0.1 64bit for Windows 10. The only extension is uBlock Origin, but I have disabled it for this test.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/bigint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/bigint/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by chrisdavidmills** [comment]
@concastinator Ah, this is part of the Test 262 report widget. I just tested the buttons; pressing either one of them makes the buttons disappear, and a message appear saying "Thank you for your feedback". Did you not get this?

**Comment by concastinator** [comment]
@chrisdavidmills No, *absolutely* nothing visible happens.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills No, _absolutely_ nothing visible happens.

Hrm, I really don't know why. We'll have to check this out further.

**Comment by sideshowbarker** [comment]
I believe this was fixed by https://github.com/mdn/content/commit/fdfdb1b3b280cd4f922e7b9bca4a6cf3eb8fd73a https://github.com/mdn/content/pull/3375 — which completely removed the Test 262 report widget.
