### ISSUE TITLE
HTTP messages are not encoded in ASCII

### ISSUE THREAD

**Issue by yecril23pl** [mdn/content#32428]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages

### What information was incorrect, unhelpful, or incomplete?

> HTTP messages are composed of textual information encoded in ASCII

### What did you expect to see?

[HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP) messages shall be composed of textual information and binary data.

*Message headers* shall contain textual information encoded in [UTF-8](https://developer.mozilla.org/en-US/docs/Glossary/UTF-8).

Textual information within *message body* shall be encoded using a suitable binary representation, usually  [UTF-8](https://developer.mozilla.org/en-US/docs/Glossary/UTF-8).  The encoder shall be specified in the `Content-Type` header. 

Binary data shall consist of an octet stream transmitted over the network.

Message body may be encoded or compressed for transmission.

### Do you have any supporting links, references, or citations?

1. [ASCII](https://developer.mozilla.org/en-US/docs/Glossary/ASCII)

### Do you have anything more you want to share?

While we could describe [HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP) before 2007 here, such a description would be confusing and/or repulsive to the reader.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/messages`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/messages/index.md
* Last commit: https://github.com/mdn/content/commit/b807e2f1e2e66a5642209d6d02c582c69cfda04c
* Document last modified: 2024-02-12T21:33:12.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for the issue - this is definitely wrong. Fixed by #32434
