### ISSUE TITLE
Defining ([^\d])

### ISSUE THREAD

**Issue by ItsDuGuRu** [mdn/content#32422]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

### What specific section or headline is this issue about?

```js
const newString = "abc12345#$*%".replace(/([^\d]*)(\d*)([^\w]*)/, replacer);
```

### What information was incorrect, unhelpful, or incomplete?

The group refers to the non-digit character class, \D in the above title. I consulted the reference guide to \d and \D and there was only example referring to digits and non-digits which led me to the conclusion that the group ([^\d]) would include #$*% for newstring. console.log(newString); // abc - 12345 - #$*% implys some sort of non word character set which excludes #$*%.

### What did you expect to see?

I expected to see a ^\d explanation that said that in the realm of only non-digits, a non-word character wasn't under consideration.

### Do you have any supporting links, references, or citations?

This was found under the JS replacer function in the string.prototype.rep[lace() method explaination.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/replace`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/replace/index.md
* Last commit: https://github.com/mdn/content/commit/fb85334ffa4a2c88d209b1074909bee0e0abd57a
* Document last modified: 2023-09-25T07:33:31.000Z

</details>

**Comment by Josh-Cena** [comment]
Hey, `[^\d]` refers to all non-digit characters, including `#$*%`. However here `#$*%` is matched by the last capturing group because characters before it are already consumed. What are you confused about?

```
abc12345#$*%
---=====....
 |   |   |----- matched by ([^\w]*)
 |   |--------- matched by (\d*)
 |------------- matched by ([^\d]*)
```

**Comment by ItsDuGuRu** [comment]
I was looking at “abc12345#$*%” as a distinct object. In the reference text I read the original string is not mutated, the string evaluated left to right, then a new string is returned. The “*” in ([^\d]*) tells me that I need zero or more items from the target object so I’m thinking “abc#$*%” is remembered via “P1”. It appears my confusion is not understanding the mechanics of @@whateverappropriate.



As I read your note your diagram implies that as the string was “consumed” as you say the P1 evaluation terminated at index 3, first digit. Had the string been “abc#$*%12345” P1 = “abc#$*%”, I’m thinking. If this is so I was confused when juggling the definitions of flags, g in particular, precedent of evaluation, and all of the other rules involved in the evaluating a stream of “stuff”. In another life I was more privileged in that I also defined the SW/FW that drove my HW. Perhaps for select examples, a step by step of what the SW was doing would have been a big help. We can’t expose the SW itself but a verbal step by step would be handy and not violate the definition of “Object”s.



HomeFrontGuRu = on this occasion not so GuRu 😊.
