### ISSUE TITLE
Groups and backreferences examples need explanations

### ISSUE THREAD

**Issue by ItsDuGuRu** [mdn/content#32435]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Groups_and_backreferences

### What specific section or headline is this issue about?

Using groups and back references

### What information was incorrect, unhelpful, or incomplete?

I find the guides regarding regexp very confusing.  I observed the following in my console. With this, the colorized characters in the code lines, and the guides I haven't a clue how the output happened. Is there any further detail I can study to explain the output of "'" and '"' ?

```js
const quote = `Single quote "'" and double quote '"'`;
const regexpQuotes = /(['"]).*?\1/g;
for (const match of quote.matchAll(regexpQuotes)) {
  console.log(match[0]);
}
```

### What did you expect to see?

??

### Do you have any supporting links, references, or citations?

I have only the pages provided in these guides. If there are further reference materials I would appreciate a link.

### Do you have anything more you want to share?

Back in the DOS days, we were privileged to have the code so we could verify what action was caused by the various ticks and clicks. That's gone now but step by steps or state diagrams with regard to the code would be very helpful and not violate the obscuration principles of the objects in question.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions/groups_and_backreferences`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Groups_and_backreferences
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/groups_and_backreferences/index.md
* Last commit: https://github.com/mdn/content/commit/65d7bdee2bada8efc396dc34cac1fd7e874236f1
* Document last modified: 2023-12-12T15:10:34.000Z

</details>

**Comment by Josh-Cena** [comment]
What are you confused about? This regex matches two quotes of the same kind and anything that comes in between, so it outputs a double-quote-enclosed single quote, and a single-quote-enclosed double quotes.
