### ISSUE TITLE
http.server is not a static file server

### ISSUE THREAD

**Issue by yecril23pl** [mdn/content#32446]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/set_up_a_local_testing_server

### What specific section or headline is this issue about?

running_server-side_languages_locally

### What information was incorrect, unhelpful, or incomplete?

**Python**'s `http.server` (or `SimpleHTTPServer` for Python 2) module is useful, but it is merely a static file server; it doesn't know how to run code written in languages such as **Python**, **PHP** or **JavaScript**.

### What did you expect to see?

**Python**'s `http.server` module can also be used with option `--cgi` to invoke server-side CGI scripts.  Those scripts shall be executable files or Python scripts placed at the location `/cgi-bin/`.  They accept CGI environment variables and the request in binary standard input (`stdin.buffer`) and emit the reply onto binary standard output (`stdout.buffer`).  If your CGI script is written in **Python**, you may use the `multipart` module to process the request.

### Do you have any supporting links, references, or citations?

[CGIHTTPRequestHandler](https://docs.python.org/3/library/http.server.html#http.server.CGIHTTPRequestHandlerhttps://docs.python.org/3/library/http.server.html#http.server.CGIHTTPRequestHandler)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/common_questions/tools_and_setup/set_up_a_local_testing_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/set_up_a_local_testing_server
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/tools_and_setup/set_up_a_local_testing_server/index.md
* Last commit: https://github.com/mdn/content/commit/f21b731803ee077d060a11038d9b284bab37ecc3
* Document last modified: 2023-12-15T08:52:13.000Z

</details>

**Comment by hamishwillee** [comment]
The audience here is primarily people who are interested in toy examples and/or learning about a framework, and/or running MDN examples. The server used is largely an afterthought - getting up and running quickly is what is important. 

We obviously shouldn't say it isn't capable of things that it is capable of, but it is not suitable for the main audience.

If there are great links on how to set up for various types of code we can add those.

**Comment by yecril23pl** [comment]
# Example
## Script cgi-bin/reflector.py
```python
#!/usr/bin/python3
# coding=ISO-8859-1
from os import environ
from multipart import parse_form
import html
from sys import stdin,  stderr
from logging import log, INFO

A, B, F = (  0o1,	'Vt queant laxis resonare fibris\r\n'
'Mira gestorum famuli tuorum\r\n', None)

def on_param (param):
	global A, B
	if param .field_name	 == b'A':
		A = param .value .decode ()
	else:
		B = param .value .decode ()

def on_file (file):
	global F
	F = file .file_name .decode ()

method = environ .get ( 'REQUEST_METHOD' )

if method   == 'POST':
	parse_form (  {
	  'Content-Type' :environ .get ('CONTENT_TYPE')	  ,
	  'Content-Length' : environ .get ('CONTENT_LENGTH')  },
	   stdin .buffer  , on_param  , on_file)

print ('CONTENT-TYPE: TEXT/HTML; CHARSET=UTF-8\r\n\r\n'
'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN >'
'<HTML LANG="en" >'
'<TITLE >Data reflector</TITLE ><H2 >%s</H2 >'
'<FORM'
' METHOD=POST ACTION="reflector.py" ENCTYPE="MULTIPART/FORM-DATA" >'
'<OL >'
'<LI >'
'<LABEL >A string parameter: <INPUT TYPE=TEXT NAME=A VALUE="%s" ></LABEL >'
'<LI >'
'<LABEL >'
'Multiline text:'
'<TEXTAREA NAME=B ROWS=10 COLS=80 >%s</TEXTAREA ></LABEL >'
'<LI >'
'<LABEL >Choose any file: <INPUT TYPE=FILE NAME=F ></LABEL >'
' = <INPUT TYPE=TEXT READONLY VALUE="%s" >'
'</OL >'
'<P >'
'<LABEL >'
'Press to review your subission: <INPUT TYPE=SUBMIT ></LABEL >'
'</FORM >' %
 tuple  (html .escape  (  '%s' % it)   for it in   (method, A, B, F))
)
```
## Run server
```sh
chmod +x cgi-bin/reflector.py && python3 -m http.server --cgi
```
## Test
```sh
xdg-open 'http://0.0.0.0:8000/cgi-bin/reflector.py'
```

**Comment by hamishwillee** [comment]
Yeah, that proves my point - way more complicated than in Django say doing `python manage.py runserver`. This isn't a document about `http.server` - it's about how you can easily serve your code.
