### ISSUE TITLE
slope is not deprecated

### ISSUE THREAD

**Issue by estelle** [mdn/content#32449]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/slope

### What specific section or headline is this issue about?

deprecated header

### What information was incorrect, unhelpful, or incomplete?

the slope attribute is listed as useful for font-face, but never supported and deprecated.

`slope` is an attribute of the `<feComponentTransfer>` element's children: `<feFuncR>`, etc., and is supported, not deprecated, as far as I can tell.

### What did you expect to see?

the slope page being up to date, and about it's use within `<feComponentTransfer>`, not font-face.

### Do you have any supporting links, references, or citations?

see https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComponentTransfer. It's also in the css filter effects pages.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/attribute/slope`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/slope
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/slope/index.md
* Last commit: https://github.com/mdn/content/commit/b4f998244660723175f8e06b5d77f68cfb1d1f1a
* Document last modified: 2023-03-06T23:38:10.000Z

</details>

**Comment by Anurella** [comment]
@bsmth  
I think the steps to the page's modification might look like the below 

1. remove the deprecated message at the top
2. rewrite what the slope attribute indicates and include this line (You can use this attribute with the following SVG element: <feComponentTransfer>)
3. the current usage note is valid 
4. the specification link will be updated to [this](https://svgwrite.readthedocs.io/en/latest/classes/fe_component_transfer.html)

Are you okay with the outline above? If yes, please assign me to the issue. Also, should we add an example section to it or just link to the element where it plays a role?

**Comment by bsmth** [comment]
__For anyone taking this:__ the duplicate/closed https://github.com/mdn/content/issues/24935 has more context ℹ️

**Comment by estelle** [comment]
> The [<feFuncR>](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncR), [<feFuncB>](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncB), [<feFuncG>](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncG), and [<feFuncA>](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncA) elements all support the slope attribute, and use it to set values for linear filters, such as brightness. This page says it's deprecated and only relevant to font. I arrived at the page from https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute#transfer_function_attributes. It is definitely not deprecated.
