### ISSUE TITLE
contextmenu attribute is obsolete

### ISSUE THREAD

**Issue by Akindin** [mdn/content#32448]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contextmenu

### What information was incorrect, unhelpful, or incomplete?

Page existence is unnecessary

### What did you expect to see?

Absence of this page

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/contextmenu`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contextmenu
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/contextmenu/index.md
* Last commit: https://github.com/mdn/content/commit/a34d62daf2294f7f4d1f339cee60ba58c109ae01
* Document last modified: 2024-02-10T01:15:07.000Z

</details>

**Comment by hamishwillee** [comment]
@queengooborg This was removed from FF, the last browser, in release 84 - December 15, 2020. Isn't BCD supposed to auto-remove these things a couple of years after last use?

@Akindin Thanks for this. Content removal usually follows compatibility data removal.

**Comment by queengooborg** [comment]
While not quite automatic, we do have a linter script for finding and removing obsolete features.  However, it is only enabled for some categories since we haven't yet updated mdn-bcd-collector coverage for all categories and synchronized the results -- the HTML category is not tracked by the linter currently.  This feature does meet removal qualifications though!

**Comment by Akindin** [comment]
P.S. This attribute also mentioned on this two pages
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

**Comment by Akindin** [comment]
@queengooborg is there a way to remove article, or how issue should be resolved?

**Comment by hamishwillee** [comment]
I've added a PR to remove it in https://github.com/mdn/browser-compat-data/pull/22593. IF that gets accepted we can remove this one.

**Comment by Akindin** [comment]
PR is accepted thanks to everyone for participation.

**Comment by hamishwillee** [comment]
FYI, you don't need to close this. It gets done when the content PR gets removed. Cheers.
