### ISSUE TITLE
menuitem element should be removed as obsolete

### ISSUE THREAD

**Issue by Akindin** [mdn/content#32458]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem

### What information was incorrect, unhelpful, or incomplete?

Page existence is unnecessary

### What did you expect to see?

Absence of this page

### Do you have any supporting links, references, or citations?

Corresponding element interface https://developer.mozilla.org/en-US/docs/Web/API/HTMLMenuItemElement

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/menuitem`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/menuitem/index.md
* Last commit: https://github.com/mdn/content/commit/76600240fbe75e083e964bc3707cce81e99999c2
* Document last modified: 2023-05-22T06:13:12.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting this. We typically defer to BCD guidelines for removing obsolete data (to avoid duplicating policies and conversations around these rules). A feature or technology is a candidate for removal if:

>a feature was implemented and has since been removed from all browsers dating back two or more years ago

which matches this case, so I think removal of both of these pages is acceptable.

**Comment by bsmth** [comment]
I've opened a Discussion about this removal here: https://github.com/orgs/mdn/discussions/668

**Comment by bsmth** [comment]
@Akindin there's no opposition in the linked discussion to removing the pages, so it looks fine to proceed with deletions like https://github.com/mdn/content/pull/24886. Do you want to do this or do you want to leave it to someone else?
