### ISSUE TITLE
The url address on iana.org where the HTTP field name registrations are referenced has changed.

### ISSUE THREAD

**Issue by taylanbildik** [mdn/content#32453]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

### What specific section or headline is this issue about?

HTTP headers

### What information was incorrect, unhelpful, or incomplete?

The url address of the registered http headers referenced to iana.org under the title has changed.

The links to "IANA registry" and "registry of proposed new HTTP headers" have been moved to the following address.

Url: https://www.iana.org/assignments/http-fields/http-fields.xhtml

### The current paragraph is as follows:

Custom proprietary headers have historically been used with an X- prefix, but this convention was deprecated in June 2012 because of the inconveniences it caused when nonstandard fields became standard in [RFC 6648](https://datatracker.ietf.org/doc/html/rfc6648); others are listed in an [IANA registry](https://www.iana.org/assignments/message-headers/message-headers.xhtml#perm-headers), whose original content was defined in [RFC 4229](https://datatracker.ietf.org/doc/html/rfc4229). IANA also maintains a [registry of proposed new HTTP headers](https://www.iana.org/assignments/message-headers/message-headers.xhtml#prov-headers).

### The paragraph with updated url addresses should be as follows.

Custom proprietary headers have historically been used with an X- prefix, but this convention was deprecated in June 2012 because of the inconveniences it caused when nonstandard fields became standard in [RFC 6648](https://datatracker.ietf.org/doc/html/rfc6648); others are listed in an [IANA registry](https://www.iana.org/assignments/http-fields/http-fields.xhtml), whose original content was defined in [RFC 4229](https://datatracker.ietf.org/doc/html/rfc4229). IANA also maintains a [registry of proposed new HTTP headers](https://www.iana.org/assignments/http-fields/http-fields.xhtml).

### Do you have any supporting links, references, or citations?

On iana.org, this url address change is specified as follows.

>Note
HTTP field name registrations have been moved to [https://www.iana.org/assignments/http-fields] 
per [[RFC-ietf-httpbis-semantics-19](https://www.iana.org/go/draft-ietf-httpbis-semantics-19)].

**Comment by bsmth** [comment]
Super, thank you for raising this. I've opened a PR which updates these (linked above).
