### ISSUE TITLE
Uninitialized const, let, var

### ISSUE THREAD

**Issue by ItsDuGuRu** [mdn/content#32459]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var

### What specific section or headline is this issue about?

Wherever generic memory is allocated.

### What information was incorrect, unhelpful, or incomplete?

The following code is only an example. At the time "let myArray" is evaluated I assume some space is reserved and since "myArray" only implies an Array in the mind of us users, is it possible while explaining the scoping et al for these named memory allocations that through prototyping, I assume, these generic naming strings assume the proper object characteristics. That is to say, how does the string myArray become a bonified Array? In this user's mind, it's via the mechanics of "while", and I'm sure somewhere in the reading materials in javascript speak, all is defined, but for those that get wrapped around the axil on the detail clarification via example would help.

```js
const myRe = /ab*/g;
const str = "abbcdefabh";
let myArray;
while ((myArray = myRe.exec(str)) !== null) {
  let msg = `Found ${myArray[0]}. `;
  msg += `Next match starts at ${myRe.lastIndex}`;
  console.log(msg);
}
```

### What did you expect to see?

Nothing. What I've observed is that "things" are defined using the technical terminology, quite necessary, and examples are employed possibly using yet-to-be-defined "stuff".  An abbreviated explanation, like what I've observed in the groups and backreferences section, would be helpful to the novice. 

### Do you have anything more you want to share?

In all these materials are excellent.  My experience as a designer may have made me detail-picky as I read each word and then attempt to sypher an author's meaning.  I also read my study materials twice. So as far as the above-mentioned short example explanations an ah-ha moment occurs on the second pass as the look-ahead "Stuff" is then known.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/var`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/var/index.md
* Last commit: https://github.com/mdn/content/commit/4f86aad2b0b66c0d2041354ec81400c574ab56ca
* Document last modified: 2023-09-12T03:52:28.000Z

</details>

**Comment by Josh-Cena** [comment]
Variable declarations do not do any memory allocation themselves. Only expressions such as object initializers, function calls, etc. can allocate memory. Variables themselves only let you hold a reference to the allocated memory. Furthermore, variable names have absolutely no connection with the memory type they actually hold. To be familiar with language basics, please start by reading the [learning docs](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics) or the [guide](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Introduction). We can add one sentence here explaining that uninitialized variables basically carry no memory.

**Comment by ItsDuGuRu** [comment]
Thanks for the update. I perceive my issues are attempting to attach “in the beginning” definitions to the modern day. That is, Yee-ole ARPANET before WWW and BASIC/Fortran before Simula whatever that are? BUT! With a few re-reads and a few hints the reorientation in the basics are becoming clear. Thus far I believe I’ve figured out all, the [ ‘” ] and uninitialized  let, var, …, issues. Thanks for your patients. :)

I don’t know if any official “case closed” is necessary, but I’m good-to-go now, and no return is necessary.

B Safe
B Healthy
B Good
B Happy
B Loved
B Free
