### ISSUE TITLE
Add HTTP to proxy.ProxyInfo 'proxyAuthorizationHeader'

### ISSUE THREAD

**Issue by erosman** [mdn/content#32475]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/ProxyInfo

### What specific section or headline is this issue about?

proxyAuthorizationHeader

### What information was incorrect, unhelpful, or incomplete?

Subsequent to [Bug 1794464: Allow HTTP authentication in proxy.onRequest](https://bugzilla.mozilla.org/show_bug.cgi?id=1794464) change `HTTPS` to `HTTP/HTTPS`

### What did you expect to see?

For example:

`string`. This string, if set to non-empty, is passed directly as a value to the [Proxy-Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization) request header sent to HTTP/HTTPS proxies as part of HTTP/HTTPS and CONNECT requests. In other words, this can be used to directly authenticate to HTTP/HTTPS proxies that allow (non-challenging) authentication.

### Do you have any supporting links, references, or citations?

Refer to the above Bugzilla link

**Comment by erosman** [comment]
### Note
Section [connectionIsolationKey](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/ProxyInfo#connectionisolationkey) may also require an update.
Verification is requested in the above bug.

**Comment by Rob--W** [comment]
> ### Note
> 
> Section [connectionIsolationKey](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/ProxyInfo#connectionisolationkey) may also require an update. Verification is requested in the above bug.

Responded at https://bugzilla.mozilla.org/show_bug.cgi?id=1794464#c14

The incorrect documentation was added at https://github.com/mdn/content/pull/17958.
