### ISSUE TITLE
Statement about applicable object-position and object-fit is wrong (?)

### ISSUE THREAD

**Issue by tpraxl** [mdn/content#32474]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

### What specific section or headline is this issue about?

Positioning and scaling

### What information was incorrect, unhelpful, or incomplete?

As a [replaced element](https://developer.mozilla.org/en-US/docs/Web/CSS/Replaced_element), the position, alignment, and scaling of the embedded document within the <iframe> element's box, can be adjusted with the [object-position](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) and [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) properties.

I tried to apply `iframe { object-fit: contain; }` with several combinations of explicit `width` & `height`, `overflow: hidden`, even using the deprecated `scrolling` attribute of the `<iframe>`. It doesn't seem to work. 

So either the rule "replaced element -> can be used with object-fit and object-position" is wrong, because it is only applicable to images and videos, or we should really provide an example.

### What did you expect to see?

Either I would have expected not to see this paragraph at all, or I would have expected `object-fit` and `object-position` to work.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/iframe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/iframe/index.md
* Last commit: https://github.com/mdn/content/commit/fdd3ac5598c3ddceb71e59949b003936ae99f647
* Document last modified: 2024-02-22T19:57:33.000Z

</details>

**Comment by OnkarRuikar** [comment]
`object-position` does work in FIrefox: https://developer.mozilla.org/en-US/play?id=M%2BIuRXx6jXT3WN%2FzFjlc5FQ1p%2B8VB0qGSpBnv%2F4B8bTvJRCQtdgRm9Qi%2BaXMV3jGMLkxAnciNkCPtL9a

![1](https://github.com/mdn/content/assets/87750369/b47cdda2-334d-4989-aceb-84c98a8fbdeb)

`object-fit` doesn't work in any browser. As iframe can't affect content layout.
