### ISSUE TITLE
chrome bug fixed

### ISSUE THREAD

**Issue by eyaler** [mdn/content#32484]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check

### What specific section or headline is this issue about?

chrome bug

### What information was incorrect, unhelpful, or incomplete?

the chrome bug mentioned in the main text and the compatibility table was fixed afaiu in feb 2023 

### What did you expect to see?

as the page was modified in july 2023 i expected it to include feb 2023 changes

### Do you have any supporting links, references, or citations?

https://issues.chromium.org/issues/40893726

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/fontfaceset/check`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fontfaceset/check/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this one @eyaler, I've opened up some PRs that should fix this in content and in BCD.
