### ISSUE TITLE
Content bug: js_event_object_hierarchy.svg contains unsafe HTML

### ISSUE THREAD

**Issue by peterbe** [mdn/content#3248]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Overview_of_Events_and_Handlers

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Overview_of_Events_and_Handlers#the_event_object_hierarchy

## What is the problem?

There's a file attachment there, this:
https://github.com/mdn/content/blob/main/files/en-us/web/guide/events/overview_of_events_and_handlers/js_event_object_hierarchy.svg
It contains `onclick` handlers which we consider "unsafe". 
The checker for that was introduced *after* this file was added to the git repo. 

## What did you expect to see?

Seeing that it's just an image, perhaps it doesn't need to be interactive. 

## Did you test this? If so, how?

Manual testing.

**Comment by sideshowbarker** [comment]
e42cebf5938b547df043ac16a6d19201f9800ae6 deleted the files/en-us/web/guide/events/index.html and added a /en-US/docs/Web/Guide/Events → /en-US/docs/Web/Events redirect and in https://developer.mozilla.org/en-US/docs/Web/Events there’s no `#the_event_object_hierarchy` anchor/section, and no images anywhere in that article.

So I’m going ahead ad closing this.
