### ISSUE TITLE
Introducing Constructors

### ISSUE THREAD

**Issue by BigShuff** [mdn/content#32488]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics

### What specific section or headline is this issue about?

The example that follows this line "Constructors, by convention, start with a capital letter and are named for the type of object they create. So we could rewrite our example like this:  JS"

### What information was incorrect, unhelpful, or incomplete?

Please understand I don't feel confident enough to say that the following is definitely an error but for the life of me I cant see that that the code is required. And therefore found it confusing. I have put the code in question in bold.
_Note this constructor is as I see it fine the each new object will be the value of the argument._
function createPerson(name) {
  const obj = {};
  obj.name = name;
  obj.introduceSelf = function () {
    console.log(`Hi! I'm ${this.name}.`);
  };
  return obj;
}

The bold code seems to have no meaning? 
const salva = createPerson("Salva");
**salva.name;**
salva.introduceSelf();
// "Hi! I'm Salva."

const frankie = createPerson("Frankie");
**frankie.name;**
frankie.introduceSelf();
// "Hi! I'm Frankie."

### What did you expect to see?

I don't think the code has any meaning even when removed the names are still given to each object

### Do you have any supporting links, references, or citations?

This code with the lines in question commented out still produces the same result.

function createPerson(name) {
    const obj = {};
    obj.name = name;
    obj.introduceSelf = function () {
      console.log(`Hi! I'm ${this.name}.`);
    };
    return obj;
  }

const salva = createPerson("Salva");
//salva.name;
salva.introduceSelf();
// "Hi! I'm Salva."

const frankie = createPerson("Frankie");
//frankie.name;
frankie.introduceSelf();
// "Hi! I'm Frankie."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/basics/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by BigShuff** [comment]
Sorry not very confident of Pull Requests just checked the relevant help
page but to be honest I haven't time to read it all. Would you like to do
it on my behalf. Sorry for invading your time.
Thanks

**Comment by wbamberg** [comment]
Not at all, it's fine :). Thank you for finding the error and taking the time to file a bug.
