### ISSUE TITLE
Content-Disposition: parameter filename* is forbidden in a part

### ISSUE THREAD

**Issue by yecril23pl** [mdn/content#32483]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

### What specific section or headline is this issue about?

filename_2

### What information was incorrect, unhelpful, or incomplete?

> `filename*` is preferred over `filename` when both are understood.

### What did you expect to see?

`filename*` is preferred over `filename` when both are understood.  In particular, `filename*` is *not understood* in a message body of type `multipart/form-data`.

### Do you have any supporting links, references, or citations?

[Returning Values from Forms: multipart/form-data](https://www.rfc-editor.org/rfc/rfc7578.html#section-4.2)

### Do you have anything more you want to share?

This is an important step to understand the following facts:

1. The `filename` parameter is the only way to specify the file name of a file uploaded from a form  (as suggested by the given examples&mdash;but it should be stated explicitly).
2. The value of the `filename` parameter shall be encoded as [UTF-8](https://developer.mozilla.org/en-US/docs/Glossary/UTF-8) or as an [URI component](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent()) (mandatory if the file name contains a `%`).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-disposition`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-disposition/index.md
* Last commit: https://github.com/mdn/content/commit/369b8ec2c87b6c5b01d1527fddb6810ded3be782
* Document last modified: 2023-12-16T06:56:50.000Z

</details>

**Comment by dipikabh** [comment]
Thanks @yecril23pl for bringing this to our attention.

There is room to both clarify and improve the existing text, especially how `multipart/form-data` handles filenames.

For anyone looking to fix this issue, please refer to following portion from the spec (https://www.rfc-editor.org/rfc/rfc7578.html#section-4.2) to convey the right message in docs:

> In most multipart types, the MIME header fields in each part are
>    restricted to US-ASCII; for compatibility with those systems, file
>    names normally visible to users MAY be encoded using the percent-
>    encoding method in [Section 2](https://www.rfc-editor.org/rfc/rfc7578.html#section-2), following how a "file:" URI
>    [[URI-SCHEME](https://www.rfc-editor.org/rfc/rfc7578.html#ref-URI-SCHEME)] might be encoded.
> 
>    NOTE: The encoding method described in [[RFC5987](https://www.rfc-editor.org/rfc/rfc5987)], which would add a
>    "filename*" parameter to the Content-Disposition header field, MUST
>    NOT be used.
> 
>    Some commonly deployed systems use multipart/form-data with file
>    names directly encoded including octets outside the US-ASCII range.
>    The encoding used for the file names is typically UTF-8, although
>    HTML forms will use the charset associated with the form.

Note also that we have a glossary page on [percent-encoding](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding).

**Comment by Josh-Cena** [comment]
Should be fixed by https://github.com/mdn/content/pull/34304—I didn't see this earlier.
