### ISSUE TITLE
[Web Bluetooth] Unclear wording abuot the Bluethoot interface returning something

### ISSUE THREAD

**Issue by nicolo-ribaudo** [mdn/content#32529]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth

### What information was incorrect, unhelpful, or incomplete?

> The `Bluetooth` interface of the [Web Bluetooth API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API) returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

### What did you expect to see?

As far as I understand, `Bluethoot` cannot be called (`Bluethoot()`) or constructed (`new Bluethoot()`). How can it return a promise?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/bluetooth`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/bluetooth/index.md
* Last commit: https://github.com/mdn/content/commit/676b6ef50b4e4ca45149e5942a21a538fa5c9119
* Document last modified: 2023-12-19T12:57:32.000Z

</details>

**Comment by nicolo-ribaudo** [comment]
I completely misread and assumed that "interface" means that it's an object.

**Comment by hamishwillee** [comment]
Absolutely! Thanks - fixed in https://github.com/mdn/content/pull/32533
