### ISSUE TITLE
Chunk sizes are wrong in the example

### ISSUE THREAD

**Issue by abhimp** [mdn/content#32528]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding

### What specific section or headline is this issue about?

Examples -> Chunked encoding

### What information was incorrect, unhelpful, or incomplete?

HTTP/1.1 200 OK
Content-Type: text/plain
Transfer-Encoding: chunked

7\r\n
Mozilla\r\n
**~11~**\r\n
Developer Network\r\n
0\r\n
\r\n

### What did you expect to see?

HTTP/1.1 200 OK
Content-Type: text/plain
Transfer-Encoding: chunked

7\r\n
Mozilla\r\n
**17**\r\n
Developer Network\r\n
0\r\n
\r\n

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/transfer-encoding`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/transfer-encoding/index.md
* Last commit: https://github.com/mdn/content/commit/0880a90f3811475d78bc4b2c344eb4146f25f66c
* Document last modified: 2023-04-10T19:47:15.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this one @abhimp - the [chunked part](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding#chunked) is "the length of the current chunk in hexadecimal format" so `7` would be `7` and [`17` would be `11` in hex](https://www.rapidtables.com/convert/number/decimal-to-hex.html), so it appears the example is correct.

I'm going to close this one for now, but if you have any other comments or if you think I've made a mistake, feel free to reply. Thank you :)
