### ISSUE TITLE
This was very helpful

### ISSUE THREAD

**Issue by jsf80238** [mdn/content#32531]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash

### What information was incorrect, unhelpful, or incomplete?

I did not see a way to register my appreciation other than to open this ticket, which can be closed immediately.

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash was very helpful!
Thank you for providing it.

### What did you expect to see?

I did not see a way to register my appreciation other than to open this ticket, which can be closed immediately.

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash was very helpful!
Thank you for providing it.

**Comment by chrisdavidmills** [comment]
@jsf80238 thank you so much for the kind words! I wrote the original version of this article, and I am so glad you found it helpful.
