### ISSUE TITLE
WebGL textures tutorial fsSource out of sync with GH, unclear which is correct

### ISSUE THREAD

**Issue by dektar** [mdn/content#32537]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL

### What specific section or headline is this issue about?

Fragment Shader code

### What information was incorrect, unhelpful, or incomplete?

the fsSource causes errors when running the program
Specifically, https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL#the_fragment_shader, I get errors about both `out vec4 fragColor;` and `fragColor = texture(uSampler, vTextureCoord);`

### What did you expect to see?

https://github.com/mdn/dom-examples/blob/main/webgl-examples/tutorial/sample6/webgl-demo.js shows the correct fsSource:
```
const fsSource = `
  varying highp vec2 vTextureCoord;

  uniform sampler2D uSampler;

  void main(void) {
    gl_FragColor = texture2D(uSampler, vTextureCoord);
  }
`;
```

Pasting this in instead of what was in the tutorial works

### Do you have any supporting links, references, or citations?

https://github.com/mdn/dom-examples/blob/main/webgl-examples/tutorial/sample6/webgl-demo.js

### Do you have anything more you want to share?

Thanks for the helpful tutorials!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webgl_api/tutorial/using_textures_in_webgl`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/tutorial/using_textures_in_webgl/index.md
* Last commit: https://github.com/mdn/content/commit/005cc1fd55aadcdcbd9aabbed7d648a275f8f23a
* Document last modified: 2024-01-15T21:58:53.000Z

</details>

**Comment by Josh-Cena** [comment]
Based on https://github.com/mdn/content/pull/30461, it appears that this change is intentional per the latest spec. Can someone confirm which one actually works?

**Comment by LordArugula** [comment]
> Based on #30461, it appears that this change is intentional per the latest spec. Can someone confirm which one actually works?

I have the same issue as dektar. The current code in the tutorial does not work, but the code in the completed demo works for me, though.
