### ISSUE TITLE
Deprecation of Warning header should link to alternative or new way of doing things.

### ISSUE THREAD

**Issue by tgrushka** [mdn/content#32564]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Warning

### What specific section or headline is this issue about?

Deprecated

### What information was incorrect, unhelpful, or incomplete?

Incomplete: No indication or pointer to replacement for the Warning header. A lot of proxy, etc. apps are using this to indicate error status. It is a long-standing standard and thus deprecation warrants explanation and a link to the new way of doing things. This is a problem on many MDN pages.

### What did you expect to see?

A link to what should be used instead.

### Do you have any supporting links, references, or citations?

No, no idea what is the replacement. I just ran into this header using a proxy library. We can't read minds of people that devise these deprecations, what are we supposed to do instead if not use this on any new web sites or apps? If okay to use on backends or apps, and only deprecated in end-user browsers, this should be indicated. But still, an alternative should be provided.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/warning`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Warning
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/warning/index.md
* Last commit: https://github.com/mdn/content/commit/501093f8973bf996ff5fa0fbf4e4146090cb08b5
* Document last modified: 2023-08-03T08:49:27.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. The stated reason in the spec for this is that the header is NOT widely used, which makes me think that the spec authors don't agree that this is used in a lot of apps. 
In any case, I completely agree in principle that if we know the reason and alternatives then this should be captured. Fixed in https://github.com/mdn/content/pull/32602
