### ISSUE TITLE
Issue with "Object.prototype.toString()": (short summary here please)

### ISSUE THREAD

**Issue by stevenharderjr** [mdn/content#3257]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString

#### What did you expect to see?

Reference to, comparison with, and possibly recommendation for, String().

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/tostring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/tostring/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by stevenharderjr** [comment]
If it's unclear, I'm talking about String() called as a function, not as a constructor.

**Comment by dev-nicolaos** [comment]
I can work on this
