### ISSUE TITLE
Confusion content

### ISSUE THREAD

**Issue by ngnguyen1** [mdn/content#32576]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions#function_declarations

### What information was incorrect, unhelpful, or incomplete?

> ... so if the code within the body of a function assigns a completely new value to a parameter that was passed to the function, the change **is not reflected globally or in the code which called that function.**

But the example code right below the above paragraph showing is the change is reflect to the global object **myCar**.

### What did you expect to see?

the paragraph should change to 
> ... the change is reflected globally or in the code which called that function.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/functions/index.md
* Last commit: https://github.com/mdn/content/commit/e3faa375b0179de77a5eff00074e3d168a0a904c
* Document last modified: 2023-10-04T23:23:49.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, "assign a completely new value to a parameter" is different from "change the property of a parameter". `a = 1` doesn't stick; `a.foo = 1` sticks.
