### ISSUE TITLE
Navigating to curriculum page while running the site locally breaks the server.

### ISSUE THREAD

**Issue by kenedyolisi** [mdn/content#32599]
### MDN URL

https://developer.mozilla.org/en-US/curriculum/

### What information was incorrect, unhelpful, or incomplete?

When you navigate to this page, the localhost server stops.

### What did you expect to see?

Maybe 404 page but the server continues running.

### Do you have anything more you want to share?

![image](https://github.com/mdn/content/assets/66219869/c778e2ff-d3c5-493f-a8f7-adbd1da7cf7d)

**Comment by bsmth** [comment]
Hi @kenedyolisi, thanks for reporting - you need to have the curriculum repo cloned and available as an environment var in order for these pages to work. Something like this:

```bash
git clone mdn/curriculum
# you already have mdn/content cloned, but for illustration:
git clone mdn/content
cd content
echo 'CURRICULUM_ROOT=../curriculum' >> .env
yarn && yarn start
```

Maybe we should add this to the documentation in this repository

**Comment by kenedyolisi** [comment]
I think that is a good idea (should be added to documentation). Thanks.
