### ISSUE TITLE
Write docs for IDL properties exposed by WAI-ARIA

### ISSUE THREAD

**Issue by tim-we** [mdn/content#32591]
ARIA attributes such as `aria-controls` have associated properties on the `Element` interface (e.g. `Element.ariaControlsElements`). However there are no MDN pages for those properties yet. 

Currently Safari is the only browser that has implemented those properties.

### Missing pages

- [ ] `ElementInternals.ariaActiveDescendantElement`
- [ ] `ElementInternals.ariaControlsElements`
- [ ] `ElementInternals.ariaDescribedByElements`
- [ ] `ElementInternals.ariaDetailsElements`
- [ ] `ElementInternals.ariaErrorMessageElements`
- [ ] `ElementInternals.ariaFlowToElements`
- [ ] `ElementInternals.ariaInvalid`
- [ ] `ElementInternals.ariaLabelledByElements`
- [ ] `ElementInternals.ariaOwnsElements`
- [ ] `Element.role`
- [ ] `Element.ariaActiveDescendantElement`
- [ ] `Element.ariaControlsElements`
- [ ] `Element.ariaDescribedByElements`
- [ ] `Element.ariaDetailsElements`
- [ ] `Element.ariaErrorMessageElements`
- [ ] `Element.ariaFlowToElements`
- [ ] `Element.ariaInvalid`
- [ ] `Element.ariaLabelledByElements`
- [ ] `Element.ariaOwnsElements`

It was suggested by @bsmth in the thread of #32327 to create a ticket for this.

**Comment by Josh-Cena** [comment]
I've added all properties reported as missing from https://dontcallmedom.github.io/mdn-gaps/

**Comment by Josh-Cena** [comment]
Hi! I'm closing all issues that are in https://openwebdocs.github.io/web-docs-backlog/all/. These features are automatically in our backlog and don't need separate issues to track.
