### ISSUE TITLE
The word "contorno" is misspelled

### ISSUE THREAD

**Issue by eliuddyn** [mdn/content#326]
https://developer.mozilla.org/es/docs/Web/CSS/border

Where?
Section: BORDERS VS CONTORNOS

Los **conronos** nunca toman espacio, ya que se dibujan fuera del contenido de un elemento.

**Comment by hamishwillee** [comment]
Hi @eliuddyn ,
The MDN team don't have bandwidth to maintain translations, but we'd love a PR - do you think you could create one?

**Comment by nschonni** [comment]
https://github.com/mdn/translated-content

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations at the moment. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
