### ISSUE TITLE
user-select contain is obsolete

### ISSUE THREAD

**Issue by Akindin** [mdn/content#32607]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

### What information was incorrect, unhelpful, or incomplete?

Mention of contain value

### What did you expect to see?

No contain value or more clear warning that this attribute has no effect in modern browsers

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/user-select`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/user-select
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/user-select/index.md
* Last commit: https://github.com/mdn/content/commit/bb6092c4230b69c2eceae6910af68c73955cae1c
* Document last modified: 2023-05-10T14:53:07.000Z

</details>

**Comment by Josh-Cena** [comment]
It's not obsolete; it's in the spec but not implemented by any browser yet. This is faithfully represented in the [table](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select#browser_compatibility).
