### ISSUE TITLE
All major browsers now support `display: contents`

### ISSUE THREAD

**Issue by yin1999** [mdn/content#32605]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/display

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Relationship_of_flexbox_to_other_layout_methods#flexbox_and_display_contents

### What information was incorrect, unhelpful, or incomplete?

[The document](https://github.com/mdn/content/blob/cc032eaae8b14c1253216ded69c076242c4f757c/files/en-us/web/css/css_flexible_box_layout/relationship_of_flexbox_to_other_layout_methods/index.md?plain=1#L105) states that current browsers have limited support for `display: contents`. This description is outdated as all major browsers now support this value.

### What did you expect to see?

update this statement

### Do you have any supporting links, references, or citations?

caniuse: https://caniuse.com/css-display-contents

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/display`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/display
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/display/index.md
* Last commit: https://github.com/mdn/content/commit/afaf3aeeffa8408cf0a8a46c3d8fb0d347aad9f5
* Document last modified: 2024-01-30T05:28:18.000Z

</details>

**Comment by evelinabe** [comment]
I was looking into this with the intention of helping with the issue. However, from my understanding the note is still correct. It specifies that the current implementations in most browsers interferes with accessibility. This is also what is being stated on canius when hovering the statuses (see image below).

My suggestion is to close this issue without further action.

<img width="1298" alt="screenshot of css display:contents on canius.com" src="https://github.com/mdn/content/assets/19805312/b4f0afbc-d67f-4e70-91f7-4baab02d0aff">

**Comment by yin1999** [comment]
The the implementation issue is already stated above this paragraph (see the warning), and the issue exists in both Firefox and Chrome. It is still inappropriate to say "Firefox supports `display: contents` already, the value is being implemented in Chrome" here.

**Comment by evelinabe** [comment]
Added a PR to update this statement.

**Comment by yin1999** [comment]
> ~You're right, added a PR to update this statement.~
> 
> Issue has been solved in #34149 , please close this issue.

Yes, the relevant content has been updated! I'm going to close this :)
