### ISSUE TITLE
http link error on .../WebAssembly/Reference

### ISSUE THREAD

**Issue by tkuhtliaw** [mdn/content#32611]
### MDN URL

https://developer.mozilla.org/en-US/docs/WebAssembly/Reference

### What specific section or headline is this issue about?

WebAssembly instruction reference

### What information was incorrect, unhelpful, or incomplete?

3 http link errors in this page:
![linkErr](https://github.com/mdn/content/assets/162700119/e6d7bd45-a905-422d-bbf0-978dfff53093)

### What did you expect to see?

use the 3 hyper links

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/webassembly/reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Reference
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/reference/index.md
* Last commit: https://github.com/mdn/content/commit/c681ed89305afd56d54ba6671673680bea041670
* Document last modified: 2023-11-03T06:30:13.000Z

</details>

**Comment by wbamberg** [comment]
@tkuhtliaw , did you close this for a reason? It looks like a valid issue to me.

**Comment by tkuhtliaw** [comment]
> @tkuhtliaw , did you close this for a reason? It looks like a valid issue to me.

Thank you. I have opened  it again.

**Comment by wbamberg** [comment]
@MendyBerger , this page and its subpages were added by you in https://github.com/mdn/content/pull/12784, it looks like the intention was to add the remaining pages at a future date. What do you think we should do here? My opinion would be to remove these links, and possibly add them back when there are targets for them. (I suppose we could even comment them out if we want to keep them as a reminder.)

**Comment by MendyBerger** [comment]
Yeah that seems like a good idea, comment them out until they're added.

**Comment by tkuhtliaw** [comment]
Please mark a [TODO] so that peaple will wait for it.
