### ISSUE TITLE
querySelectorAll() does not state how the results are sorted

### ISSUE THREAD

**Issue by juanlanus** [mdn/content#32615]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll

### What information was incorrect, unhelpful, or incomplete?

Incomplete: IMO the docs should state how are the reslts sorted. 

### What did you expect to see?

The [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element) method querySelectorAll() returns a static (not live) [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) representing a list of elements matching the specified group of selectors which are descendants of the element on which the method was called, ****sorted by their appearance order inside the queried scope****. (or whatever, I don't know)

### Do you have anything more you want to share?

I'm so glad MDN displaced the infamous "HTML school" or whatever it's name was, a truly SEO master job!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/queryselectorall`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/queryselectorall/index.md
* Last commit: https://github.com/mdn/content/commit/b85bf9fcc2c0062a765d104799d7d45d9e9b13bb
* Document last modified: 2023-07-22T00:55:30.000Z

</details>

**Comment by hamishwillee** [comment]
For whoever looks at this, 
- I'm not sure that the sort order is considered "relevant"- it certainly hasn't been highlighted in the spec so I wouldn't be planning my code around any particular sorting result.
- I think the order is the order of appearance the DOM tree, including shadow DOM. There is some question in the spec about how pseudo elements should be traversed. Relevant spec part here: https://drafts.csswg.org/selectors-4/#match-against-tree
