### ISSUE TITLE
Description for Array.from is incorrect

### ISSUE THREAD

**Issue by tibrogargan** [mdn/content#32623]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

The description states that the method takes "an [iterable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol) or [array-like](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections#working_with_array-like_objects) object".

### What did you expect to see?

"an [iterable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol) or any value that can be coerced to an [array-like](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections#working_with_array-like_objects) object"

### Do you have any supporting links, references, or citations?

Using the definition of [array-like object](https://262.ecma-international.org/14.0/#sec-lengthofarraylike),  If the existing description were correct `Array.from` should fail if passed any JavaScript primitive that is not iterable.  (e.g. boolean,  Number).

This may have arisen as Step 6 of the ECMAScript Reference for [Array.from](https://262.ecma-international.org/14.0/#sec-array.from) claims that it assumes that `items` is an array-like object.  However this may be a simplification as it then coerces `items` into an array-like variable, `array-like` in step 7 (or throws a TypeError).  Step 7 would be unnecessary if the method only allowed array-like objects at this point.

### Do you have anything more you want to share?

The code below shows that `Array.from` accepts boolean primitives, which do not meet the definition of `array-like object`
```
Array.from(false) // Does not throw an error
false.length // Throws an error
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/from`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/from/index.md
* Last commit: https://github.com/mdn/content/commit/fb85334ffa4a2c88d209b1074909bee0e0abd57a
* Document last modified: 2023-09-25T07:33:31.000Z

</details>

**Comment by Josh-Cena** [comment]
A method that we claim to "take a value of type X" does not necessarily fail on other kinds of inputs. Many methods are declared to "accept an index" or "accept a string", but that doesn't mean you cannot pass an object and have it implicitly coerced to the target type. Parameter coercion is such a widespread feature that it's not worth mentioning on every page. Moreover, it also doesn't mean you should do so, as it's both bug prone and confusing. MDN promotes good practices by helping you stay within the boundaries of "good semantics".
