### ISSUE TITLE
:-moz-broken example doesn't work

### ISSUE THREAD

**Issue by Akindin** [mdn/content#32625]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-broken

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

Example doesn't show anything on Firefox 123.0.1 (64-bit)

### What did you expect to see?

bisque background and padding for broken image

### Do you have anything more you want to share?

It seems like this feature doesn't work in modern Firefox, I tried testing it on local example and it didn't work.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_-moz-broken`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-broken
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_-moz-broken/index.md
* Last commit: https://github.com/mdn/content/commit/c6dbc4ff96451887b908b46c8e70bcfec1c2c48c
* Document last modified: 2023-02-26T04:54:36.000Z

</details>

**Comment by hamishwillee** [comment]
Correct. Removed from content in 119. Note you should be avoiding anything marked as deprecated in any case.

**Comment by hamishwillee** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/22592
