### ISSUE TITLE
AnalyzerNode::getByteFrequencyData claims that an element in the Uint8array is set to negative infinity

### ISSUE THREAD

**Issue by alexvitkov** [mdn/content#32640]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getByteFrequencyData#array

### What specific section or headline is this issue about?

The `array` parameter

### What information was incorrect, unhelpful, or incomplete?

For the `array` parameter in `AnalyzerNode::getByteFrequencyData`, the docs claim that
> The Uint8array that the frequency domain data will be copied to. For any sample which is silent, the value is -Infinity

This is wrong since an Uint8 cannot be set to negative infinity.
It was probably copy-pasted from `getFloatFrequencyData`, which does the same as this method, but fills out a `Float32Array` instead of a `Uint8array`

### What did you expect to see?

It shouldn't be claimed that an uint8 will be set to negative infinity.

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/32813
