### ISSUE TITLE
Instructions of "Configuring Firefox for FIPS 140-2" partially obsolete or inaccurate

### ISSUE THREAD

**Issue by Ricky-Tigg** [mdn/content#3264]
Hello. The instructions of the article _Configuring Firefox for FIPS_ 140-2 at [https://support.mozilla.org/en-US/kb/Configuring%20Firefox%20for%20FIPS%20140-2](https://support.mozilla.org/en-US/kb/Configuring%20Firefox%20for%20FIPS%20140-2) are partially obsolete regards to an up-to-date application release.

#### What information was incorrect or incomplete?
_Step 1: Disable SSL 2 and SSL 3, leaving only TLS_
- _Advanced_ panel is not present
- _Use SSL 3.0_ and  _Use TLS 1.0_ boxes are not present

_Step 3: Disable all the non-FIPS TLS cipher suites in about:config_
- List of implemented ciphers is inaccurate

#### What did you expect to see?
_Step 1: Disable SSL 2 and SSL 3, leaving only TLS_
- Correct path: _Privacy & Security_ | <kbd>Security Devices</kbd>

_Step 3: Disable all the non-FIPS TLS cipher suites in about:config_
- The accurate list of implemented ciphers, which results from keyword "_ssl3_" in search field, is:
_security.ssl3.dhe_rsa_aes_128_sha
security.ssl3.dhe_rsa_aes_256_sha
security.ssl3.ecdhe_ecdsa_aes_128_gcm_sha256
security.ssl3.ecdhe_ecdsa_aes_128_sha
security.ssl3.ecdhe_ecdsa_aes_256_gcm_sha384
security.ssl3.ecdhe_ecdsa_aes_256_sha
security.ssl3.ecdhe_ecdsa_chacha20_poly1305_sha256
security.ssl3.ecdhe_rsa_aes_128_gcm_sha256
security.ssl3.ecdhe_rsa_aes_128_sha
security.ssl3.ecdhe_rsa_aes_256_gcm_sha384
security.ssl3.ecdhe_rsa_aes_256_sha
security.ssl3.ecdhe_rsa_chacha20_poly1305_sha256
security.ssl3.rsa_aes_128_gcm_sha256
security.ssl3.rsa_aes_128_sha
security.ssl3.rsa_aes_256_gcm_sha384
security.ssl3.rsa_aes_256_sha
security.ssl3.rsa_des_ede3_sha_

#### Did you test this?
Firefox for Fedora - 1.0, version 86.0.1.

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @Ricky-Tigg . Would you be interested in filing a PR to update this information? Unfortunately this content is not a priority for the MDN writer's team, so we are unlikely to work on it any time soon.

**Comment by Ricky-Tigg** [comment]
I certainly would. Since it's the very first time i am asked a _PR_, i investigated and conceived that the closest eligible interpretation could be '_Pull request_'. Is it even that what you referred to?

**Comment by chrisdavidmills** [comment]
> I certainly would. Since it's the very first time i am asked a _PR_, i investigated and conceived that the closest eligible interpretation could be '_Pull request_'. Is it even that what you referred to?

Yes, that is correct. Happy to help, if you've got any questions!

**Comment by Ricky-Tigg** [comment]
Good news then. After having red the well written guide _Learn more about pull requests._ i understood that the knowledge of the repository model – e.g _shared_ – is a requisite,  then the use a _topic branch_ would be recommended. In order to feel what it would be to create one on the dedicated page i clicked <kbd>New pull request</kbd> . Are the button <kbd>base:'main'</kbd> | <kbd>comparee:'main'</kbd> involved as prerequisite to the action of clicking <kbd>Create pull request</kbd>?

**Comment by chrisdavidmills** [comment]
You've basically got your version of the codebase, and a pull request involves comparing it against the main version of the code base, to see if the changes in your version are fine, or need changing, etc.

I wrote a guide on the easiest/way to set that up, here: https://developer.mozilla.org/en-US/docs/MDN/Contribute/GitHub_beginners

**Comment by Ricky-Tigg** [comment]
**Actual situation:** I am not yet allowed to click <kbd>Create pull request</kbd>.

Is there a way to ensure that this repository – **mdn/content** – is  even the one that contains the texts i referred to in this report in order to determine that it is the one to be forked then cloned as suggested in your guide?

The public SSH key that i added to GitHub has been granted with _read-write_ permissions. Does the sentence "_you must have read permissions to a repository can create a pull request, but you must have write permissions to create a branch._" at https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request refer to those SSH key permissions?

![public_SSH_key_imported_to github](https://user-images.githubusercontent.com/26058215/112821688-a9e4cf80-908f-11eb-8ea0-320b0da2f5c4.png)

**Comment by chrisdavidmills** [comment]
> **Actual situation:** I am not yet allowed to click Create pull request.
> 
> Is there a way to ensure that this repository – **mdn/content** – is even the one that contains the texts i referred to in this report in order to determine that it is the one to be forked then cloned as suggested in your guide?

Yes. If you want to edit an MDN page, you can find exactly which GitHub source page needs to be edited by going to the bottom of the page and following the "Source on GitHub" link. 

> 
> The public SSH key that i added to GitHub has been granted with _read-write_ permissions. Does the sentence "_you must have read permissions to a repository can create a pull request, but you must have write permissions to create a branch._" at https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request refer to those SSH key permissions?

Everyone gets read permissions by default, unless the repository in question is private, or you have been blocked from it due to bad behavior.

You must have write permissions to be able to create a branch on a repository. This is why we tell you to fork the repository first, and then create a branch to work in, on your own fork. You get write permissions automatically on your own repos.

To answer your question, no, this isn't affected by the SSH key permissions. What the SSH key does is verify you as a trusted user, so that when you clone or push to repos, you can do so quickly and easily. If you don't have an SSH key set up, you can still do the things mentioned in my article, but you'll have to enter your username and password to authentiate each time, which gets annoying after a while. Setting up an SSH key means that you'll no longer have to do that every time.

**Comment by Ricky-Tigg** [comment]
_Source on GitHub_ | Its presence may vary. The page of the guide you wrote contains it, while the page this report was written against, does not. Do you know a workaround to locate on GitHub the repository it is associated with?

**Comment by chrisdavidmills** [comment]
@Ricky-Tigg I am so sorry! I've just looked at the original URL you reported, and realized that it is a support.mozilla.org (SuMo) URL, not a developer.mozilla.org (MDN) URL. SuMo is a separate project from MDN, and so the content is not kept in the same place, or edited in the same way.

I asked their product manager about it, and she said that you can find out how to edit SuMo articles here — https://support.mozilla.org/en-US/kb/edit-knowledge-base-article. You need to sign up and sign in, but after that you cna start editing articles.

Again, sorry for the false start here. I don't consider it to be a complete waste of time, as GitHub is a very popular tool these days, and you'll be bound to run into it for other projects too.

**Comment by Ricky-Tigg** [comment]
That's thanks to person like you, there are few of them we both know that (at most one out of 1024), that great achievements are made possible in an ethical manner. Persons who have the less reason to apologize – and are likely to always do – are precisely those very persons. You had all reasons not to apologize regards to that case. That's me here that even wasted someone's time, yours indeed.

As so many others worldwide, _MDN_ understood early the benefits brought by the platform created by Linus Torvalds, enough to decide to work on it. _SuMo_ has not yet. The present service is so convenient that it shall be considered a sufficient reason in itself for considering to no more open any new account – a _SuMo_ account;  I do not have.

Since i won't be in situation to work on the text originally reported, unless _SuMo_ does decide to work any soon on this platform too, that endangers the project i had assigned to myself by welcoming your decent proposition, and hence operate via pull request. As a coincidence the article at https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/FIPS_Mode_-_an_explanation, which has a link _Source on GitHub_* present that leads to this repository. contains a link that leads to that page whose article is the one i reported against. 

(*) Presence of _Source on GitHub_ is a wise principle; is it a specificity of MDN?

Isn't there a legitimate need to prevent readers of this article from reporting to a non valid project maintenance page, just as I did? The file associated to this article may require minor changes such as:

**existent**: "_Instructions for how to configure Firefox into FIPS mode may be found on support.mozilla.com._"
**into:**"_Instructions for how to configure Firefox into FIPS mode may be found on support.mozilla.com, which is maintained by SuMo project, separate from MDN, and not hosted on GitHub platform._"

Then I would have to keep on following your guide and eventually the one at https://github.com/mdn/content/blob/main/README.md#simple-changes. Is that a quit bad idea?

**Comment by chrisdavidmills** [comment]
@Ricky-Tigg If I understand correctly, you are asking if you should make the change you suggested above, in the "existent" and "into" lines. I'd say no — we link to so many different other sites (many of them other Mozilla resources, but lots of others besides), that it would be impossible to keep all of this kind of information up-to-date, and I don't really think it is our responsibility to keep people informed of this either.

We do include an "external link" icon on links to non-developer.mozilla.org URLs, and I think it is reasonable to assume that most readers will think that other sites may have different contribution mechanisms to the one they are on.

The fact that you went wrong here, I think, is more to do with me giving you incorrect expetations initially ;-)

**Comment by Ricky-Tigg** [comment]
You had a correct interpretation of "_existent_" ,"_into_". Accurate mentions should have been respectively "_original_", "_modified_".. In the article at https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/FIPS_Mode_-_an_explanation, that statement may be subject to wrong interpretation:

**original:** "_In FIPS Mode, every user must have a good strong "master password", and must enter it each time he starts or restarts Firefox"_

Here is the chronological steps to enable FIPS 140-2 mode. For the purpose of the task, the creation of a profile – then within protocol page **about:profiles** – is appropriated.
1. Setting password; Note: **it is allowed to be set as weak as one character!**
2. Observing the usual guidance of that SuMo article.

There is indeed no protocol implemented to enforce the observance or rules governing at the creation of strong random passwords. Such ones' entropy range in bits would be **96–128**. '`pwmake <entropy-bits>`' would suit well for the purpose. 

**modified:** "_In order to comply with FIPS 140-2 , a master password has to be set; this one should be a strong random password, typically whose entropy range in bits is **96–128**, which is to be entered each time along with starting or restarting Firefox."_
