### ISSUE TITLE
Issue with "Using Fetch": (short summary here please)

### ISSUE THREAD

**Issue by Andrew-Cottrell** [mdn/content#3265]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

#### What information was incorrect, unhelpful, or incomplete?
End-of-line comment in `Headers` example that incorrectly indicates the `Headers.prototype.get` method returns an empty array. The method actually returns `null` for missing header names.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#headers

https://github.com/mdn/content/blob/f37c24de21200c64921064e536ea591d71df6cb3/files/en-us/web/api/fetch_api/using_fetch/index.html#L323

#### What did you expect to see?

``` console.log(myHeaders.get('X-Custom-Header')); // null```

#### Did you test this? If so, how?

I ran the example code in various browsers: Chrome 89, EdgeHTML 18, Firefox 52.9.0, and SeaMonkey 2.49.5

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/fetch_api/using_fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fetch_api/using_fetch/index.html
* Last commit: https://github.com/mdn/content/commit/f37c24de21200c64921064e536ea591d71df6cb3
* Document last modified: 2021-03-02T22:00:49.000Z

</details>

**Comment by NegiAkash890** [comment]
I can fix this!

**Comment by chrisdavidmills** [comment]
@NegiAkash890 thanks; assigned!
