### ISSUE TITLE
SKILL TEST

### ISSUE THREAD

**Issue by oneofrookie** [mdn/content#32653]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_Links

### What specific section or headline is this issue about?

skill test

### What information was incorrect, unhelpful, or incomplete?

Sorry, there's no problem with the content.
But I can't find any code cases that can be used to verify if I'm correct.

### What did you expect to see?

Add correct test code while verifying the correctness of user code.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_Links

### Do you have anything more you want to share?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/test_your_skills_colon__links`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_Links
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/test_your_skills_colon__links/index.md
* Last commit: https://github.com/mdn/content/commit/c64e813d8ab9dbe22cbc049c26f7c6703370a2b7
* Document last modified: 2023-10-23T08:57:58.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this one. There's a marking guide for these tasks at https://github.com/mdn/learning-area/blob/main/html/introduction-to-html/tasks/links/marking.md

There's a link to this at the Learn area index: https://developer.mozilla.org/en-US/docs/Learn#tasks_and_assessments

I hope that helps!

**Comment by dipikabh** [comment]
Closing this issue Brian has provided the answer in the previous comment.
