### ISSUE TITLE
WriteableStream constructor example code TextEncoder error

### ISSUE THREAD

**Issue by Reububble** [mdn/content#32655]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WritableStream/WritableStream

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

`TextEncoder.encode` has one parameter but two are used. The second argument should only be present for `TextDecoder.decode`

### What did you expect to see?

`const encoded = encoder.encode(message);`

### Do you have any supporting links, references, or citations?

Spec:
https://encoding.spec.whatwg.org/#ref-for-dom-textencoder-encode%E2%91%A0
Full example (which does not have this issue)
https://github.com/mdn/dom-examples/blob/main/streams/simple-writer/index.html

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/writablestream/writablestream`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WritableStream/WritableStream
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/writablestream/writablestream/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. This will be fixed by https://github.com/mdn/content/pull/32692
