### ISSUE TITLE
Issue with "Normal Flow": (short summary here please)

### ISSUE THREAD

**Issue by FrOz3nFir3** [mdn/content#3266]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow

#### What information was incorrect, unhelpful, or incomplete?
By default, a block level element's content is **100%** of the width of its parent element
100% here is incorrect.
#### Specific section or headline?
How are elements laid out by default?

#### What did you expect to see?
By default, a block level element's content is **auto** of the width of its parent element
**auto** should be there.
#### Did you test this? If so, how?
https://stackoverflow.com/questions/17468733/difference-between-width-auto-and-width-100-percent/17468803#:~:text=8%20Answers&text=The%20initial%20width%20of%20a,total%20width%20of%20the%20element.
by default browsers add auto and not 100%.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/css_layout/normal_flow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/normal_flow/index.html
* Last commit: https://github.com/mdn/content/commit/98e438b7d2e79c7dc04c72ca7e2f3bf36a84940f
* Document last modified: 2021-01-22T05:20:39.000Z

</details>

**Comment by rachelandrew** [comment]
auto isn't really useful here as we aren't talking about the actual value, but rather what people see (though 100% is also confusing). The spec uses available space, which is probably the edit to make, "fills the available inline space" or something similar.

The stuff about stretch fit sizing is here: https://www.w3.org/TR/css-sizing-3/#auto-box-sizes

**Comment by FrOz3nFir3** [comment]
Great Reading skills, you paid attention to tiny details! 
Actually found an article on MDN itself which might correctly describe :-
A Block-level element occupies the entire horizontal space of its parent element (container).

https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements
