### ISSUE TITLE
Hosting on Glitch Problem

### ISSUE THREAD

**Issue by EmilyErickson** [mdn/content#32678]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment

### What specific section or headline is this issue about?

Example: Hosting on Glitch

### What information was incorrect, unhelpful, or incomplete?

I had a bit of difficulty deploying the project on Glitch.
The current Glitch site doesn't support node versions higher than 16. They do seem to be working on a new site - https://blog.glitch.com/post/rebuilding-glitch - which could solve the issue. When I tried to import my project with Glitch while following the tutorial, I could not get it to work. I had to change the required node version to ">= 16.0" in my package.json file and run "npm install" on Glitch. That forced Glitch to use a higher version of node and allowed my project to run. I don't know if this is something that needs addressed in the MDN tutorial or not, but I wanted to give a heads up about it.

### What did you expect to see?

I think if students are directed to change the node version in their package.json file and then run "npm install" on Glitch, it would fix the version discrepancy problem.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/deployment/index.md
* Last commit: https://github.com/mdn/content/commit/7890a47ba8fa8fa59bc8f45679f8e1dbfadf4284
* Document last modified: 2024-02-22T23:29:35.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks Emily. It is worth mentioning. I've assigned to myself and will look at it when I have bandwidth.

**Comment by hamishwillee** [comment]
Fixed in #32695
