### ISSUE TITLE
does not work properly in mobile safari

### ISSUE THREAD

**Issue by JackKirk** [mdn/content#32673]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API/Taking_still_photos

### What specific section or headline is this issue about?

code

### What information was incorrect, unhelpful, or incomplete?

does not work correctly in mobile safari - video panel remains black

### What did you expect to see?

video from camera

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/media_capture_and_streams_api/taking_still_photos`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API/Taking_still_photos
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/media_capture_and_streams_api/taking_still_photos/index.md
* Last commit: https://github.com/mdn/content/commit/005cc1fd55aadcdcbd9aabbed7d648a275f8f23a
* Document last modified: 2024-01-15T21:58:53.000Z

</details>

**Comment by Josh-Cena** [comment]
This information is not enough to take action. We'll track it in #31194 instead
