### ISSUE TITLE
Content category is missing

### ISSUE THREAD

**Issue by kirabug** [mdn/content#32674]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary

### What specific section or headline is this issue about?

Technical Summarys

### What information was incorrect, unhelpful, or incomplete?

Pretty much all the other pages have a first row describing the content category for the tag. This page does not. I'm assuming the category is "none" but since I'm still learning to grok the criteria I don't want to edit it and be wrong.

### What did you expect to see?

I expected to see an additional row at the top of the table populated with the element's content category. 

### Do you have any supporting links, references, or citations?

There's a good example on the Search page https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search

### Do you have anything more you want to share?

You rock

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/summary`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/summary/index.md
* Last commit: https://github.com/mdn/content/commit/56f8b4b735a0c02f958121e29f0ec7adc890e7d1
* Document last modified: 2024-01-24T07:16:41.000Z

</details>

**Comment by dipikabh** [comment]
Hello @kirabug, thanks for using MDN!

Adding the row for Category as none in this case would be correct indeed. Would you be interested in opening a pull request to update the doc?
