### ISSUE TITLE
<figcaption> : accessible description or accessible name of <figure>?

### ISSUE THREAD

**Issue by kantoche** [mdn/content#32698]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure

### What specific section or headline is this issue about?

Section "Usage notes"

### What information was incorrect, unhelpful, or incomplete?

Are you sure that "The `<figcaption>` provides the [accessible description](https://developer.mozilla.org/en-US/docs/Glossary/Accessible_description) for the parent `<figure>`" ? 

### What did you expect to see?

It should be rather the accessible name.

### Do you have any supporting links, references, or citations?

Several opposite facts: 
- Accessibility tree in the developper tools of Firefox (or others browsers) considered figcaption as the "name" of the figure element ;
- The WAI tutorial proposes the use of aria-labelledby (and not aria-describedby) to reinforce the programmatic association (see https://www.w3.org/WAI/tutorials/images/groups/): 
```
<figure role="group" aria-labelledby="fig11">
<img src="/WAI/content-images/wai-tutorials/images/castle-etching.jpg" alt="The castle has one tower, and a tall wall around it.">
<figcaption id="fig11">Charcoal on  wood. Anonymous, circa 1423.</figcaption>
</figure>
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/figure`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/figure/index.md
* Last commit: https://github.com/mdn/content/commit/fdd3ac5598c3ddceb71e59949b003936ae99f647
* Document last modified: 2024-02-22T19:57:33.000Z

</details>

**Comment by estelle** [comment]
Thank you for catching this error. I submitted a PR to fix it. https://github.com/mdn/content/pull/33931
