### ISSUE TITLE
Misleading examples of invalid dates

### ISSUE THREAD

**Issue by roxkisrover** [mdn/content#32718]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_date

### What specific section or headline is this issue about?

Invalid cases

### What information was incorrect, unhelpful, or incomplete?

Out of three example cases only second one throws an exception in Firefox:

`new Date("2014-25-23").toISOString();`

Checked on Firefox 123.0.1 (64-bit), MacOS 14.4, Apple M1 Pro chip

Also an example about NaN in Firefox `Date.parse("foo-bar 2014"); // NaN` actually returns 1388512800000

This may depend on locale settings, but if so it should at least be specified.

### What did you expect to see?

The list of variants that are validated to throw Range Error in latest browser versions, or added specified version and conditions in which it can be reproduced.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/invalid_date`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_date
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/invalid_date/index.md
* Last commit: https://github.com/mdn/content/commit/6d606174faaedaa5dee7b7ebd87602cd51e5dd7e
* Document last modified: 2023-07-24T23:45:00.000Z

</details>

**Comment by Josh-Cena** [comment]
Thanks, see https://github.com/mdn/content/pull/32727
