### ISSUE TITLE
Example Extensions are either discontinued or link to a dead link

### ISSUE THREAD

**Issue by jartdian** [mdn/content#32717]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/What_are_WebExtensions

### What specific section or headline is this issue about?

The example extensions

### What information was incorrect, unhelpful, or incomplete?

Amazon Assistant for Firefox (discontinued)
OneNote Web Clipper (dead link)
MyWeb New Tab (dead link)

### What did you expect to see?

Expected to be directed into a functional or actual extension addon page

### Do you have any supporting links, references, or citations?

[Amazon Assistant for Firefox](https://addons.mozilla.org/en-US/firefox/addon/amazon-browser-bar/)
[OneNote Web Clipper](https://addons.mozilla.org/en-US/firefox/addon/onenote-clipper/)
[MyWeb New Tab](https://chrome.google.com/webstore/detail/myweb-new-tab/cnbiadnhebmicjcbpgajglfemclnlagh)

### Do you have anything more you want to share?

At the start of this issue page it suggests that if i want i can change this page myself. 
However there are couple of questions i have before doing that.

1. If i am to remove a bad link/addon, what do i replace it with? Is the addon choice personal?
2. If i remove the discontinued amazon addon , i would also have to remove the image from that webpage, do i have to insert a new image of a different addon? (preferably the first one in the examples)

I could do all the above, but i would like assurance first, since this will be my first real issue. 
You could assign it to me if the above text makes sense.
Thank you

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/what_are_webextensions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/What_are_WebExtensions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/what_are_webextensions/index.md
* Last commit: https://github.com/mdn/content/commit/b943c9373931bc3e728e245594d2394192bee73a
* Document last modified: 2024-01-03T05:37:51.000Z

</details>

**Comment by rebloor** [comment]
Fixed by https://github.com/mdn/content/pull/31945
