### ISSUE TITLE
The example doesn't work as described

### ISSUE THREAD

**Issue by savostin** [mdn/content#32730]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef

### What specific section or headline is this issue about?

The example code

### What information was incorrect, unhelpful, or incomplete?

The counter continues to increment even after the element is deleted. 
const element = this.ref.deref();
always returns the element even if it's deleted.

### What did you expect to see?

The code should stop counting.

### Do you have any supporting links, references, or citations?

Just add console.log(element) and it continue even after 5 seconds.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/weakref`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/weakref/index.md
* Last commit: https://github.com/mdn/content/commit/c2445ce1dc3a0170e2fbfdbee10e18a7455c2282
* Document last modified: 2023-09-12T02:17:31.000Z

</details>

**Comment by Josh-Cena** [comment]
Please see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#notes_on_weakrefs. There is no guarantee of when garbage collection happens, or if it happens at all. It could definitely be the case that the engine decides to never recycle something in a weak ref.
