### ISSUE TITLE
"Returns an equivalent Promise"

### ISSUE THREAD

**Issue by DanKaplanSES** [mdn/content#32736]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally#return_value

### What information was incorrect, unhelpful, or incomplete?

The first sentence of the Return Value section says, "Returns an equivalent [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)." I'm not sure what this means. Equivalent to what?

If I had to guess, I think it's saying, "Equivalent to what would be returned if the `finally` weren't written." 

### What did you expect to see?

n/a

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise/finally`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
* Last commit: https://github.com/mdn/content/commit/88d71e500938fa8ca969fe4fe3c80a5abe23d767
* Document last modified: 2023-09-01T00:27:24.000Z

</details>

**Comment by Josh-Cena** [comment]
> Equivalent to what would be returned if the finally weren't written.

Yes basically, "equivalent" is a shorthand of saying "fulfilled with the same value, or rejected with the same reason".
