### ISSUE TITLE
Single SELECT "labeled" with a FIELDSET and LEGEND? (bad or even invalid use for FIELDSET?)

### ISSUE THREAD

**Issue by alanfluff** [mdn/content#32749]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

### What specific section or headline is this issue about?

Customizing select styles

### What information was incorrect, unhelpful, or incomplete?

Under [this section](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#customizing_select_styles) (heading, <q>Customizing select styles</q>), the HTML model used is a single `select` (no other interactive elements) inside a `fieldset`. Nowhere else on the page is the `select` "labeled" with a `fieldset` + `legend`, which is great, since the [HTML Living spec](https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element) notes `fieldset` is for a <q> set of form controls</q> (plural):

> The `fieldset` element represents a set of form controls (or other content) grouped together, optionally with a caption. The caption is given by the first `legend` element that is a child of the `fieldset` element, if any. The remainder of the descendants form the group.

[This MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset) also notes `fieldset` are to <q>group several controls</q> (again, plural):

> The `fieldset` HTML element is used to group several controls as well as labels (`label`) within a web form.

So is it even valid, let alone exemplary, that a **single** `select` is *effectively* being labeled by a `fieldset` (+`legend`)?

Shouldn't it be labeled with a `label` as it is elsewhere on the page?

I assume it is effectively invalid to use `fieldset` (+`legend`) to contain a single interactive element, given the wording of the spec' (and the wording in the MDN stated page)?

### What did you expect to see?

`label` not `fieldset` used as the label in the code example.

### Do you have any supporting links, references, or citations?

See above.

### Do you have anything more you want to share?

I use these docs to demonstrate best practices and I either want to understand how the code used at present is a best practice, and learn from it, or, if I am correct and it is poor, I would love the page to be changed so I can continue to link to it to demonstrate how `select` is used and not "pollute" that demo by people seeing it being "wrongly" labeled.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/select`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/select/index.md
* Last commit: https://github.com/mdn/content/commit/fdd3ac5598c3ddceb71e59949b003936ae99f647
* Document last modified: 2024-02-22T19:57:33.000Z

</details>

**Comment by chrisdavidmills** [comment]
@alanfluff Yup, I agree with you here. While I don't think using a `<fieldset>` like this is invalid, I also appreciate that it is intended to group a set of controls. For example, a group of radio buttons would be fine, but not one select box.

There are other problems with this demo too — duplicate IDs, and the selectors used are way over the top.

I'll have a go at fixing this up.
