### ISSUE TITLE
CSS View transitions: Add a note that view transitions are immediately skipped when page is hidden

### ISSUE THREAD

**Issue by noamr** [mdn/content#32748]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API

### What information was incorrect, unhelpful, or incomplete?

Probably https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API#controlling_animations_with_javascript

### What did you expect to see?

A short note about the transition only working if the page is visible throughout.

### Do you have any supporting links, references, or citations?

https://drafts.csswg.org/css-view-transitions-1/#page-visibility-change-steps

**Comment by bsmth** [comment]
Thanks a lot for raising. I've added a note and some other improvements in the linked PR.
