### ISSUE TITLE
OAC header directive mis-specified

### ISSUE THREAD

**Issue by cberman** [mdn/content#32751]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin-Agent-Cluster

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin-Agent-Cluster#directives

### What information was incorrect, unhelpful, or incomplete?

the directive is written as if this is a request header and discusses a mobile experience, contradicting the rest of the page

### What did you expect to see?

the directive specifications should reflect the nature of the header, that is, that it is instructing the browser to handle the document differently

### Do you have any supporting links, references, or citations?

the directive seems to be copied from here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Mobile

### Do you have anything more you want to share?

thanks!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/origin-agent-cluster`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin-Agent-Cluster
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/origin-agent-cluster/index.md
* Last commit: https://github.com/mdn/content/commit/19c50d80f92ec9df02b8a955ac8130bab3c37985
* Document last modified: 2023-12-02T07:22:31.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for raising this one, it looks like a leftover from another article, indeed. There's a PR linked above that should fix this. Thank you :)

**Comment by cberman** [comment]
The PR looks great, thanks for the precise explanation and link to further documentation!

**Comment by bsmth** [comment]
You're very welcome, and it's thanks to your report, so thank you, too! 👏🏻
