### ISSUE TITLE
Issue with "Using data attributes": (short summary here please)

### ISSUE THREAD

**Issue by medoalmdar** [mdn/content#3278]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/howto/use_data_attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/howto/use_data_attributes/index.html
* Last commit: https://github.com/mdn/content/commit/1ba2b0ab9aedc5be8e609e7e974132bb704967a5
* Document last modified: 2021-03-07T09:26:31.000Z

</details>

**Comment by CreaTorAlexander** [comment]
What issue with the data attributes have you found?

**Comment by medoalmdar** [comment]
> عنوان URL لـ MDN: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
> 
> #### ما هي المعلومات التي كانت غير صحيحة أو غير مفيدة أو غير كاملة؟
> #### قسم معين أو عنوان رئيسي؟
> #### ماذا كنت تتوقع أن ترى؟
> #### هل اختبرت هذا؟ إذا كان الأمر كذلك ، فكيف؟
> تفاصيل تقرير صفحة محتوى MDN

اريد استرجاع الملفات المحذوفه وجميع تحركات جميل
