### ISSUE TITLE
ChannelMergerNode contradiction: Channel count mode = "explicit" Channel count = 2 (not used in the default count mode)

### ISSUE THREAD

**Issue by gls-manifold** [mdn/content#32783]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ChannelMergerNode

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/API/ChannelMergerNode
Channel count mode =  	"explicit"
Channel count = 2 (not used in the default count mode)

But:
https://developer.mozilla.org/en-US/docs/Web/API/AudioNode/channelCountMode#explicit
explicit
The number of channels is defined by the value of channelCount.

### What did you expect to see?

I think it should be something like (not used in the default count mode), not (not used in this Node).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/channelmergernode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ChannelMergerNode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/channelmergernode/index.md
* Last commit: https://github.com/mdn/content/commit/fa1301aead2cee37516b7ad5a5ec2fb21e004227
* Document last modified: 2023-04-06T05:00:32.000Z

</details>

**Comment by Josh-Cena** [comment]
I'm having a hard time understanding this. What do you expect to see?

**Comment by Josh-Cena** [comment]
Closing, but still welcoming follow-ups and may re-open.
