### ISSUE TITLE
Content bug: Invalid (insecure) image on en-US/docs/Web/MathML/Authoring

### ISSUE THREAD

**Issue by peterbe** [mdn/content#3280]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/MathML/Authoring

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/MathML/Authoring#input_box

## What is the problem?

https://github.com/mdn/content/blob/81b36b59628b00d7b3510de4ebeb00f0cbef12d5/files/en-us/web/mathml/authoring/index.html#L319
It references an image that can't be loaded because it's using a self-sign cert. 
The URL is `https://www.bluegriffon.com/public/shots/mathml-shot1.png"`

## What did you expect to see?

A working image. 

## Did you test this? If so, how?

Try going to the image URL directly.

**Comment by sideshowbarker** [comment]
Fixed by 53ea0fd #4946
