### ISSUE TITLE
Incorrect value for silent samples in AnalyserNode.getByteFrequencyData

### ISSUE THREAD

**Issue by kentslaney** [mdn/content#32803]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getByteFrequencyData

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

It says that any silent sample returns `-Infinity`, but that isn't possible with a `Uint8Array`. I assume it was accidentally copied from the `AnalyserNode.getFloatFrequencyData` description.

### What did you expect to see?

an array of 0s

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/analysernode/getbytefrequencydata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getByteFrequencyData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/analysernode/getbytefrequencydata/index.md
* Last commit: https://github.com/mdn/content/commit/005cc1fd55aadcdcbd9aabbed7d648a275f8f23a
* Document last modified: 2024-01-15T21:58:53.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. Should be fixed by #32813
