### ISSUE TITLE
Object.create don't do shallow copies... Does?

### ISSUE THREAD

**Issue by bsshenrique** [mdn/content#32815]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Deep_copy

### What specific section or headline is this issue about?

https://github.com/mdn/content/blob/main/files/en-us/glossary/shallow_copy/index.md?plain=1#L27

### What information was incorrect, unhelpful, or incomplete?

"In JavaScript, standard built-in object-copy operations (spread syntax, Array.prototype.concat(), Array.prototype.slice(), Array.from(), Object.assign(), and **Object.create()**) do not create deep copies (instead, they create shallow copies)."

`Object.create()` is same as `obj1 = obj2` and we can verify this writing something like that:
```JavaScript
const original = {
  value: 'X',
  object: {
    value: 'Y'
  }
};

// Copy by reference
const copy1 = original;
const copy2 = Object.create(original);
// Shallow copy
const copy3 = Object.assign({}, original);

// A function to just help us
function print(o) {
  return `value: ${o.value} | object.value: ${o.object.value}`
}

original.value = 'A'
original.object.value = 'B'

console.log(
  '\n',
  `Copy 1: ${print(copy1)}\n`,
  `Copy 2: ${print(copy2)}\n`,
  `Copy 3: ${print(copy3)}\n`,
)
```

We'll see something like:

```PlainText
 Copy 1: value: A | object.value: B
 Copy 2: value: A | object.value: B
 Copy 3: value: X | object.value: B
```

As we can see, when using `Object.create()` the top level `value` changes.

To be considered a `Shallow Copy` instruction this should not be happen, according to [this page](https://developer.mozilla.org/en-US/docs/Glossary/Shallow_copy):

> For shallow copies, only the top-level properties are copied, not the values of nested objects. Therefore:
> Re-assigning top-level properties of the copy does not affect the source object.
> Re-assigning nested object properties of the copy does affect the source object.

### What did you expect to see?

"In JavaScript, standard built-in object-copy operations (spread syntax, Array.prototype.concat(), Array.prototype.slice(), Array.from(), Object.assign()) do not create deep copies (instead, they create shallow copies)."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/deep_copy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Deep_copy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/deep_copy/index.md
* Last commit: https://github.com/mdn/content/commit/1c285cab12ee953a74d38a0800951126b48e1a81
* Document last modified: 2023-08-12T02:08:39.000Z

</details>

**Comment by Josh-Cena** [comment]
`Object.create` does not create a copy. It creates an object with the passed object as its prototype, which breaks our definition of "copy" by the "structurally equivalent prototype chain" criterion.

I don't know why `Object.create` is mentioned as a copying technique. Welcoming a PR to remove it.
