### ISSUE TITLE
Navigator: cookieEnabled warning regarding Safari is outdated

### ISSUE THREAD

**Issue by omar-rahman-dev** [mdn/content#32845]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/cookieEnabled

### What specific section or headline is this issue about?

The first note

### What information was incorrect, unhelpful, or incomplete?

`Note: When the browser is configured to block third-party cookies, and navigator.cookieEnabled is invoked inside a third-party iframe, it returns true in Safari, Edge Spartan and IE (while trying to set a cookie in such scenario would fail). It returns false in Firefox and Chromium-based browsers.`

### What did you expect to see?

Safari technical preview 188 and latest webkit update has fixed navigator.cookieEnabled for Safari returning the correct value.

### Do you have any supporting links, references, or citations?

https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-188
https://bugs.webkit.org/show_bug.cgi?id=267789

**Comment by kaushik95** [comment]
I would like to work on this issue.
