### ISSUE TITLE
Firefox 55.0.3 issue

### ISSUE THREAD

**Issue by luongmbptrung** [mdn/content#32856]
### MDN URL

seller.printerval.com

### What specific section or headline is this issue about?

I am using firefox version 55.0.3, currently I am uploading images to the web printerval. com, but when clicking Save it doesn't work

### What information was incorrect, unhelpful, or incomplete?

I am using firefox version 55.0.3, currently I am uploading images to the web printerval. com, but when clicking Save it doesn't work, the browser doesn't have any movement. 2 days ago everything was normal. Is there any way to fix the error of not being able to Save on the website without upgrading to the new version? I tried doing it on another computer and the latest versions of Chrome and Firefox were still normal

### What did you expect to see?

Fix this issue without upgrading

### Do you have anything more you want to share?

I think Web server of it has benn upgraded to refuse Firefox 55

**Comment by wbamberg** [comment]
This doesn't seem to be an MDN issue.
