### ISSUE TITLE
CSS property -webkit-mask-attachment is obsolete

### ISSUE THREAD

**Issue by Akindin** [mdn/content#32858]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-attachment

### What information was incorrect, unhelpful, or incomplete?

Property is obsolete

### What did you expect to see?

Removal of the page

### Do you have any supporting links, references, or citations?
Also mention on this page should be removed
https://developer.mozilla.org/en-US/docs/Web/CSS/WebKit_Extensions

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/-webkit-mask-attachment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-attachment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/-webkit-mask-attachment/index.md
* Last commit: https://github.com/mdn/content/commit/c77cfcd17e85db6c1b93160c70668f2ff6c2809c
* Document last modified: 2023-07-20T07:38:29.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. This will be fixed by the linked issues.
