### ISSUE TITLE
Create Genre Form: Collation() Method Absent from Initial Code

### ISSUE THREAD

**Issue by MeanderingBrook** [mdn/content#32865]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form

### What specific section or headline is this issue about?

Controller—post route

### What information was incorrect, unhelpful, or incomplete?

The initial code example EXCLUDES the collation() Method; the collation() Method is subsequently narrated in the detailed walk-through, but included in the specific code extract on determining whether the newly-named Genre already exists in the database

### What did you expect to see?

The use of the collation() Method should be included in both full code block, initially provided, and the duplicate-search-specific code extract provided subsequently

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_genre_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_genre_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_genre_form/index.md
* Last commit: https://github.com/mdn/content/commit/d2adfc444695707570fae98fbfa1a98a8ef067ce
* Document last modified: 2023-12-18T06:32:16.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you. This will be fixed by #32907
