### ISSUE TITLE
URL text fragments: can prefix/suffix be separated from the linked text?

### ISSUE THREAD

**Issue by johndeighan** [mdn/content#32871]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Text_fragments

### What specific section or headline is this issue about?

Examples with prefix- and/or -suffix

### What information was incorrect, unhelpful, or incomplete?

In the first example, the word "for" is hilighted because it's preceded by the word "asking". However, it doesn't really immediately precede the word "asking" because there's an intervening space. Are spaces ignored when checking if one string precedes another? Are other whitespace ignored? Or perhaps any text is ignored, i.e. "precede" means it's somewhere in the preceding text. This should be clarified.

### What did you expect to see?

I don't know - depends on how it works.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/text_fragments`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Text_fragments
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/text_fragments/index.md
* Last commit: https://github.com/mdn/content/commit/835d6632d59993861a0458510402787f8a2c3cb3
* Document last modified: 2023-10-25T17:27:32.000Z

</details>

**Comment by Josh-Cena** [comment]
See spec:

> Context terms are used to disambiguate the target text fragment. The context terms can specify the text immediately before (prefix) and immediately after (suffix) the text fragment, allowing for whitespace.
