### ISSUE TITLE
Method or property?

### ISSUE THREAD

**Issue by wysiwyg-data** [mdn/content#32886]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getHourCycles

### What specific section or headline is this issue about?

Obtaining supported hour cycles

### What information was incorrect, unhelpful, or incomplete?

When copied and pasted into the <script></script> section of the header of a test web page, the following code returns:
"Uncaught TypeError: arEG.getHourCycles is not a function" in the browser console.

```
<script>
    const arEG = new Intl.Locale("ar-EG");
    console.log(arEG.getHourCycles());
</script>
```

### What did you expect to see?

As the section (and code) state, the expected result is:
```
["h12"]
```

### Do you have any supporting links, references, or citations?

**System**:
- Operating System: Kubuntu 22.04
- KDE Plasma Version: 5.24.7
- KDE Frameworks Version: 5.92.0
- Qt Version: 5.15.3
- Kernel Version: 5.15.0-101-generic (64-bit)
- Graphics Platform: X11
- Processors: 4 × Intel® Core™ i5-6500 CPU @ 3.20GHz
- Memory: 15.5 GiB of RAM
- Graphics Processor: Mesa Intel® HD Graphics 530

**Web server**:
- Apache/2.4.52 (Ubuntu)
- PHP Version 8.1.2-1

**Browser**:
- Google Chrome
- Version 123.0.6312.86 (Official Build) (64-bit)

### Do you have anything more you want to share?

In order to obtain the expected result, the following code was used instead:
```
<script>
    const arEG = new Intl.Locale("ar-EG");
    console.log(arEG.hourCycles); 
</script>
```
The offending function ```getHourCycles()``` is replaced by the property ```hourCycles``` obtained through inspection of the ```Locale``` object.
Perhaps this is due to the compatibility between Chrome and this JavaScript prototype?
Or because I'm a relatively new JS programmer and perhaps missing an essential step...?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/locale/gethourcycles`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getHourCycles
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/locale/gethourcycles/index.md
* Last commit: https://github.com/mdn/content/commit/27180875516cc311342e74b596bfb589b7211e0c
* Document last modified: 2023-08-24T22:55:36.000Z

</details>

**Comment by Josh-Cena** [comment]
Please see the browser compatibility table. Chrome does not implement `getHourCycles` yet. The note at the very top of this page also reminds you of this.
