### ISSUE TITLE
Issue with "Document.cookie": (short summary here please)

### ISSUE THREAD

**Issue by trrapp12** [mdn/content#3288]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

#### Specific section or headline?
All example section alert buttons

#### What did you expect to see?

example 1 should show "name=oeschger" or "favorite_food=tripe", but gives a message "an embedded page at yari-demos.prod.mdn.mozit.cloud says"

#### Did you test this? If so, how?

see above

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/cookie`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/cookie/index.html
* Last commit: https://github.com/mdn/content/commit/48fca0c614add538e95f1075b2777fc396023d31
* Document last modified: 2021-03-16T07:50:01.000Z

</details>

**Comment by CreaTorAlexander** [comment]
Also it should use an event listener instead of the html onclick attribute.

Besides the *Do Once* Example can be executed more than once and if the last two examples should also be live demonstrations then there are buttons missing.

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Update the live examples within the page

**Comment by shuta13** [comment]
I would like to work on this issue.

**Comment by hamishwillee** [comment]
Thanks @shuta13 - that would be great - assigned to you.

**Comment by NegiAkash890** [comment]
The PR is successfully merged , this issue can closed now.

**Comment by sideshowbarker** [comment]
Thanks for the heads-up, @NegiAkash890 

Closing this as fixed by https://github.com/mdn/content/pull/5031
