### ISSUE TITLE
Missing a key difference: Firefox does CORS preflight request, Chrome doesn't

### ISSUE THREAD

**Issue by thdoan** [mdn/content#32912]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities

### What specific section or headline is this issue about?

Not sure

### What information was incorrect, unhelpful, or incomplete?

Making fetch requests was failing only in Firefox, but succeeded in Chrome and Edge. After lots of research, I confirmed it was because Firefox was performing a CORS preflight request in the fetch, whereas Chrome/Edge wasn't. You should add a section to highlight this difference.

### What did you expect to see?

I expected either a section pointing out this crucial difference, or Firefox is updated to behavior similar to Chrome and Edge (no CORS preflight requests).

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/a/73388604/452587

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/chrome_incompatibilities`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
* Last commit: https://github.com/mdn/content/commit/7d1685e832a40071b006e12794c038157b7e4955
* Document last modified: 2023-11-15T06:44:56.000Z

</details>

**Comment by dotproto** [comment]
Can you provide more details about the inconsistencies you observed? I put together [a test CORS extension](https://gist.github.com/dotproto/b7492afe26b9eb49154eb4dd8c546f43) and ran it in both Chrome and Firefox. I also tested with host permissions both granted and restricted. In my tests I did not observe any inconsistencies between the preflight behavior of either browser. All tests were performed on macOS 14.4.1. 

At the moment my best guess is that your are developing a Manifest V3 extension and have not manually granted the extension it's requested host permissions. Firefox's current design restricts host permission grants for Manifest V3 extensions at install time. There are a couple of relevant issues on Bugzilla related to this such as
[1770698](https://bugzilla.mozilla.org/show_bug.cgi?id=1770698) and [1839129](https://bugzilla.mozilla.org/show_bug.cgi?id=1839129).

<details><summary>Screenshot: Chrome 123 - host permissions granted</summary>

![Chrome 123 - host permissions granted](https://github.com/mdn/content/assets/1047763/d00751cf-8ed6-44d6-a02e-6e50f5610edc)

</details>

<details><summary>Screenshot: Firefox Nightly 126.0a1 - host permissions granted</summary>

![Firefox Nightly 126.0a1 - host permissions granted](https://github.com/mdn/content/assets/1047763/d3365753-58de-4d65-bf5e-328cd4901509)

</details>

<details><summary>Screenshot: Chrome 123 - host permissions NOT granted</summary>

![Chrome 123 - host permissions NOT granted](https://github.com/mdn/content/assets/1047763/6b97a058-e039-4860-a760-5f022edc68bc)

</details>

<details><summary>Screenshot: Firefox Nightly 126.0a1 - host permissions NOT granted</summary>

![Screenshot 2024-04-09 at 4 26 10 PM](https://github.com/mdn/content/assets/1047763/658debd6-2b1d-4f93-9b9f-b2b26a052672)

</details>

**Comment by thdoan** [comment]
@dotproto it's easy enough to replicate, but before I spend time to put together a demo extension for you to replicate, can you confirm whether this is by design? I run into CORS only when making requests from the options page, but it works fine from background page. If this is by design, then we can close this.

**Comment by thdoan** [comment]
I'm closing this since I just created a minimal extension and was not able to reproduce the issue again.
