### ISSUE TITLE
Focusvisible example is not working

### ISSUE THREAD

**Issue by snixdad** [mdn/content#32925]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus

### What specific section or headline is this issue about?

Focus on a button using focusvisible

### What information was incorrect, unhelpful, or incomplete?

The button "Click to set focus and focusvisible on 'Button'" does **not** cause the 'Button' button to have a focus ring. In other words, it has exactly the same effect as the "Click to set focus on 'Button" button.

The focusvisible object does not seem to work in my own code, either.

Is focusvisible not supported under Chrome Version 123.0.6312.86 (Official Build) (64-bit)?

### What did you expect to see?

After clicking the right-most of the three buttons, I expected to see a focus ring around the "Button" button. That button does receive focus, but it doesn't display the focus ring unless I tab into it.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/focus`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/focus/index.md
* Last commit: https://github.com/mdn/content/commit/a3d9f61a8990ba7b53bda9748d1f26a9e9810b18
* Document last modified: 2023-04-07T00:39:15.000Z

</details>

**Comment by wbamberg** [comment]
> Is focusvisible not supported under Chrome Version 123.0.6312.86 (Official Build) (64-bit)?

Yes, as noted in the Browser compatibility table: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#browser_compatibility.

It works in Firefox.

**Comment by snixdad** [comment]
Thank you for your message. My bad for not checking the browser
compatibility table. And bad on Chrome for not supporting the parameter.
It is bad UI to allow focus to change to a button programmatically while
providing no visible indication focus has changed!

--
Ed

Edward J. Langer (pronouns: he | him | his)

Phone:

(301) 610-9060

Mail:

***@***.***

Linkedin:

linkedin.com/in/edlanger

**Comment by wbamberg** [comment]
No problem, it's easy to miss compat, but always worth checking. Hopefully Chrome will add support for it soon :).
