### ISSUE TITLE
Missing BREW verb

### ISSUE THREAD

**Issue by gtbot2007** [mdn/content#32938]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

### What specific section or headline is this issue about?

N/A

### What information was incorrect, unhelpful, or incomplete?

Doesn't mention BREW verb

### What did you expect to see?

BREW verb

### Do you have any supporting links, references, or citations?

RFC 2324
RFC 7168

**Comment by teoli2003** [comment]
THe Coffee Pot interface was an April's fool joke. If we documented the [418](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418) status code (to be sure that nobody think there is a missing status code, and reuse it), I don't think that adding the `BREW` joke verb is useful.

**Comment by teoli2003** [comment]
Because nobody implements it.
