### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

### ISSUE THREAD

**Issue by ioeti** [mdn/content#32943]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

### What specific section or headline is this issue about?

What is the meaning of this ????

### What information was incorrect, unhelpful, or incomplete?

Attempting any of these when the canvas is tainted will cause a SecurityError to be thrown. **This protects users from having private data exposed by using images to pull information from remote websites without permission.**

### What did you expect to see?

How can I get my private data exposed by looking on an image , may be doing whatever in a canvas , this even from a remote website without permission ????

Someone , writing this here, hopefully just had greater mental problems and it is better now.

Where is my private data located, if not given by Google.com or Facebook.com using their services as my passport ? 
To open my camera, I have to give permission, to open my screen sharing , I need to permit, to open my audio, I need to permit... so WITHOUT PERMISSION ????? from whom ? Google Inc. ?

Who gets protected here , the website sharing an image with the rest of the world , may be investing in Google Ads, or the person having found the image and looking at it ?

### Do you have any supporting links, references, or citations?

Problem 1 : I am on local device with local loaded file:///xyz.html ...

It is a mobile phone , I want to shoot a photo and render it into html ...

I use, if I manage to trick the browser, or image upload or streaming for my own camera on my own device ... and obtain CORS error , as we never considered CORS origin null !!!!!

To do that I need to connect by https: to the internet, just loading  a Javascript function null(){ return true;} and I am able to use my own canvas ....

If there are mental instable persons around here , there is a good news , we do have doctors, which can help. 

javascript :
                 allowTaint: true;
                    foreignObjectRendering: true;
                    img.crossOrigin = '*';

php : 
// Allow cross-origin requests
// Allow cross-origin requests and disable CORS protection
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');

// Check if it's an OPTIONS request (preflight check for CORS)
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    header('HTTP/1.1 200 OK');
    exit();
}

// Check if it's an OPTIONS request (preflight check for CORS)
if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    header('HTTP/1.1 200 OK');
    exit();
}

// Check if it's a POST request
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    header('HTTP/1.1 200 OK');
}

### Do you have anything more you want to share?

But we can play the following, give me access to your videocamera, then take a photo of your credit card front and backwards, and then digit your secret code on a paper... and take a photo too... or write it with your mouse or finger into a canvas... so I will use a canvas to combine all three things together and take your money from your account ... (if there is any) 

This really needs protection...

Best regards, and stop writing about my security made by someone using my data to offer me the best siuted publicity to my needs, I never requested, in the first 3 pages of the search engines, before finding the Wikipedia link I was looking for.

Obvious, it is for my security, as Wikipedia is a dangerous think from the dark web.

Claudio Klemp

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/cors_enabled_image`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/cors_enabled_image/index.md
* Last commit: https://github.com/mdn/content/commit/5afc72ba4e64ba90815d6a435a5300fd77d11fdf
* Document last modified: 2024-03-05T05:35:49.000Z

</details>

**Comment by hamishwillee** [comment]
Closing as 
- Gibberish
- Contrary to the [participation guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
