### ISSUE TITLE
[CSS] Implement zoom property for CSS

### ISSUE THREAD

**Issue by pepelsbey** [mdn/content#32957]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

- [Implement zoom property for CSS (bug 390936)](https://bugzilla.mozilla.org/show_bug.cgi?id=390936)

⚠️ Double-check whether it’s shipping in 126.

If not, check/update how it’s documented and mention it in the experimental features.

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by dletorey** [comment]
### Related issues and pull requests

- [Content PR](https://github.com/mdn/content/pull/33473)
- [Data PR](https://github.com/mdn/data/pull/736)
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/22972)
- [Firefox Release note PR](https://github.com/mdn/content/pull/33512)
