### ISSUE TITLE
Improvement Suggestion: Correct Anchor Name for Link

### ISSUE THREAD

**Issue by MadScientisto23** [mdn/content#32961]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

### What specific section or headline is this issue about?

Temporal dead zone (TDZ) section

### What information was incorrect, unhelpful, or incomplete?

The anchor name in the link did not match the heading in the documentation. The heading is 'Temporal dead zone (TDZ)', but the anchor name in the link was 'temporal_dead_zone_tdz'. This mismatch caused the link navigation to fail.

### What did you expect to see?

I expected to click on the link and get to the correct position in the page https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let
So it does not confuse the person learning, who will have to ctrl+f to find the section Temporal dead zone (TDZ)

### Do you have anything more you want to share?

This is my first time posting an issue. I read the guidelines so I think this is okay.
To solve this issue it would be necessary to change line 20 from:
.../en-US/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz ...

to 
.../en-US/docs/Web/JavaScript/Reference/Statements/let#Temporal_dead_zone_TDZ ...

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/hoisting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/hoisting/index.md
* Last commit: https://github.com/mdn/content/commit/8fb5853ceee5db8ac6e1c564c6dda4b3f5ec86c5
* Document last modified: 2023-08-04T20:49:43.000Z

</details>

**Comment by Josh-Cena** [comment]
If you click on the "Temporal dead zone (TDZ)" heading, you see that its anchor name is exactly `#temporal_dead_zone_tdz`. The fact that it doesn't auto scroll is a long-known problem, and could be specific to Chrome.
