### ISSUE TITLE
Phaser Canvas game not working on Android

### ISSUE THREAD

**Issue by Passionate-coder997** [mdn/content#3296]
It shows a black screen only no game output

**Comment by chrisdavidmills** [comment]
What does? Where can we find it? You need to provide some information if we are to fix an issue ;-)

**Comment by Passionate-coder997** [comment]
I had followed this tutorial(code) shown here:
https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_breakout_game_Phaser/Randomizing_gameplay#compare_your_code

but it doesn't show any output, it shows a black screen when I run the game in my samsung mobile(A6+). You can check it out at: https://passionate-coder997.github.io/Phaser-breakout/

**Comment by chrisdavidmills** [comment]
@Passionate-coder997 your version doesn't seem to work for me either. Our version is available at https://end3r.github.io/Gamedev-Phaser-Content-Kit/demos/lesson16.html — do you want to try this one and let me know if it works for you?

**Comment by Ryuno-Ki** [comment]
I guess, that means, it works for @Passionate-coder997.

(@end3r Don't delete that repo :D)

**Comment by end3r** [comment]
@Ryuno-Ki I'm not planning to :)
