### ISSUE TITLE
Add macOS Safari support to Progressive Web Apps

### ISSUE THREAD

**Issue by martensjrm** [mdn/content#32969]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Installing

### What specific section or headline is this issue about?

Apple is unique when it comes to PWAs: PWAs can be installed on macOS from any browser except Safari. The opposite is true for iOS versions before 16.4, where PWAs could only be installed in Safari. 

### What information was incorrect, unhelpful, or incomplete?

Apple does allow you to add PWA's in Safari nowadays. By clicking Share > Add to Dock.

### What did you expect to see?

Apple added PWA support in Safari since macOS Sonoma. Its support was limited on iOS before 16.4, where PWAs could only be installed in Safari. PWAs can be installed on iOS/iPadOS 16.4 or later from any supporting browser.

### Do you have any supporting links, references, or citations?

https://support.apple.com/en-us/104996

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/progressive_web_apps/guides/installing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Installing
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/guides/installing/index.md
* Last commit: https://github.com/mdn/content/commit/ec9e109c42eeb2b910dc11b7d7d5c7e251bf4f89
* Document last modified: 2023-11-23T07:12:12.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/33768
