### ISSUE TITLE
Instructions Missing for "Move the Ball" Tutorial Page

### ISSUE THREAD

**Issue by j-otokoyama** [mdn/content#32979]
### MDN URL

https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Move_the_ball

### What specific section or headline is this issue about?

Compare Your Code

### What information was incorrect, unhelpful, or incomplete?

In the "Compare Your Code" section of "Move The Ball" the instruction is good. It goes over creating the draw function, making the ball move, clearing the canvas and cleaning up your code. However, at the end, in "Compare Your Code" the function startGame and the event listener for the runButton button event for startGame are provided without any explanation for why and what they are doing. Furthermore you're adding and not explaining an anonymous function as well as the "this" keyword, not to mention there is no coverage of how and where the button goes in the HTML as well as how its to be sytled.

### What did you expect to see?

The tutorial is great. With basic to little and maybe even no experience with javaScript, I think the common learner can follow what you are explaining. However, when you just magically throw concepts in and don't explain to and teach the learner, you leave them behind.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Move_the_ball#next_steps

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/games/tutorials/2d_breakout_game_pure_javascript/move_the_ball`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Move_the_ball
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/tutorials/2d_breakout_game_pure_javascript/move_the_ball/index.md
* Last commit: https://github.com/mdn/content/commit/3bc416fc6a43fe903ae2eb09c2515699f4cee0ef
* Document last modified: 2024-02-14T08:21:57.000Z

</details>

**Comment by hamishwillee** [comment]
Thank for taking the time to post. Reading the [very first page in this tutorial](https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript) it says:

> To get the most out of this series of articles you should already have basic to intermediate [JavaScript](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics) knowledge. After working through this tutorial you should be able to build your own Web games.

Given that this is about Canvas/games, which are relatively advanced concepts, I think you can reasonably expect that a user should know enough HTML to understand what is going on with a button and listener. So I don't think this is unreasonable.

That said, if you would like to add a line or two explaining "Note, this code adds a button and event listener to start the game" and link to sections that explain those concepts, that would be welcome. Would that be OK?

**Comment by Josh-Cena** [comment]
Yeah. There are two things.

1. This code is specific to our environment.

   > Live samples run automatically on these pages, so we've added a "start game" button. This is useful to avoid games starting automatically and triggering alerts or other events too often.
   
   You don't need it in your own code. It's a great skill in reading learning materials to ignore things you don't know, knowing it doesn't matter.
2. We assume you do know JS basics. If you don't know JS, you should probably learn the language before learning how to apply the language to real work use cases.

I don't think it's worthwhile explaining something you aren't supposed to have in your code anyway, and the quoted note should suffice.
