### ISSUE TITLE
Wrong example description

### ISSUE THREAD

**Issue by ceciliamarnero** [mdn/content#32983]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Combinators

### What specific section or headline is this issue about?

In this next example, we have an unordered list, nested inside of which is an ordered list. The child combinator selects only those `<li>` elements which are direct children of a `<ul>`, and styles them with a top border.

### What information was incorrect, unhelpful, or incomplete?

Example is: 

```html
<ul>
  <li>Unordered item</li>
  <li>Unordered item
    <ol>
      <li>Item 1</li>
      <li>Item 2</li>
    </ol>
  </li>
</ul>
```

So is actually the other way around: the ordered list is nested inside the unordered.

### What did you expect to see?

In this next example, we have an ordered list, nested inside of which is an unordered list. The child combinator selects only those `<li>` elements which are direct children of a `<ul>`, and styles them with a top border.

### Do you have any supporting links, references, or citations?

n/a

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors/combinators`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Combinators
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/combinators/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing!

"unordered list, nested inside of which is an ordered list" means that there is an ordered list nested in an unordered list. That's what the "of which" is doing.

"unordered list, nested inside an ordered list" would be the reverse.

So it is correct, but it is confusingly worded!

"In this next example, we have an ordered list, nested inside an ordered list." would surely be clearer.

**Comment by ceciliamarnero** [comment]
Oh I get it now! yes, you're right, but now you suggest ordered nested inside ordered again:

> "In this next example, we have an ordered list, nested inside an ordered list."

did you mean _"In this next example, we have an ordered list, nested inside an **un**ordered list"_ ?  If so, and if you allow me one suggestion, I'd remove the last comma to make it more direct like so:

"In this next example, we have an ordered list nested inside an unordered list."

**Comment by wbamberg** [comment]
> Oh I get it now! yes, you're right, but now you suggest ordered nested inside ordered again:
> 
> > "In this next example, we have an ordered list, nested inside an ordered list."
> 
> did you mean _"In this next example, we have an ordered list, nested inside an **un**ordered list"_ ?

Oh sorry yes, that is what I meant :).

> If so, and if you allow me one suggestion, I'd remove the last comma to make it more direct like so:
> 
> "In this next example, we have an ordered list nested inside an unordered list."

Sounds great! Would you like to file a PR to make this change? No problem if not, I will take care of it.

**Comment by ceciliamarnero** [comment]
I'd love to if you told me how please!

**Comment by wbamberg** [comment]
Yes, of course. The easiest way is probably to edit the file through the GitHub UI in the browser. To do that go to the file at https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/combinators/index.md?plain=1 and click the pencil icon:

<img width="1136" alt="Screen Shot 2024-04-08 at 9 47 30 AM" src="https://github.com/mdn/content/assets/432915/85ef121c-0f54-44ce-ae2a-fb7568c5dd28">

...and it should walk you through the process.

- It will probably ask you to fork the repository.
- After you've done that you will be able to edit the file, then you can click "Commit changes"
- Then it will ask you to add a commit message and click "Propose changes".
- Then it will show you the difference between the current file and the one with your change, and you click "Create pull request" to create the PR

There is a good-looking but slightly out of date guide to it here: https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github/ as well.
