### ISSUE TITLE
The `manifest` attribute of `<html>` element are no longer supported by the major browsers

### ISSUE THREAD

**Issue by yin1999** [mdn/content#32980]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html/manifest

### What information was incorrect, unhelpful, or incomplete?

The `manifest` attribute support has been removed from all major browsers, with the information provided by the [bcd](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html/manifest#browser_compatibility), only firefox supported this attribute in the past. And the related "AppCache" feature has also been removed from [Chromium](https://web.dev/articles/appcache-removal) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1619673).

So, should we remove this document and the related [Browser compatibility data](https://github.com/mdn/browser-compat-data/blob/e62344a1b6423a861633eb754b2725b2f6f6b013/html/elements/html.json#L43-L88).

If so, I'd like to help with this :)

### What did you expect to see?

See above.

### Do you have any supporting links, references, or citations?

- WHATWG: whatwg/html#6153
- Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1619673
- web.dev: https://web.dev/articles/appcache-removal

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/html/manifest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html/manifest
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/html/manifest/index.md
* Last commit: https://github.com/mdn/content/commit/0fe8f4d7e9cd5b1b6a39e9fa047468206d3c3ca2
* Document last modified: 2024-02-10T09:45:11.000Z

</details>

**Comment by estelle** [comment]
It has been deprecated for a while. I think we can safely remove it.

**Comment by jeremyredhead** [comment]
> with the information provided by the [bcd](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html/manifest#browser_compatibility), only firefox supported this attribute in the past

I'm confused, [the BCD you linked](https://github.com/mdn/browser-compat-data/blob/e62344a1b6423a861633eb754b2725b2f6f6b013/html/elements/html.json#L43-L88) seems to indicate that Chrome, Safari, and even poor old Internet Explorer once supported the `manifest` attribute? If I'm reading the table correctly

**Comment by yin1999** [comment]
> > with the information provided by the [bcd](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html/manifest#browser_compatibility), only firefox supported this attribute in the past
> 
> I'm confused, [the BCD you linked](https://github.com/mdn/browser-compat-data/blob/e62344a1b6423a861633eb754b2725b2f6f6b013/html/elements/html.json#L43-L88) seems to indicate that Chrome, Safari, and even poor old Internet Explorer once supported the `manifest` attribute? If I'm reading the table correctly

Yes, Chrome did support it in the past, I misread the relevant information. I have corrected the description.
