### ISSUE TITLE
Issue with "PannerNode.coneOuterAngle": Image not show

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [mdn/content#3299]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/coneOuterAngle

#### What information was incorrect, unhelpful, or incomplete?
the image not show "https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/coneOuterAngle/pannernode-orientation.png"

#### Specific section or headline?
the `Example` section.

#### What did you expect to see?
seems like the image must be "https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/orientationX/pannernode-orientation.png"

#### Did you test this? If so, how?
i can see the source code, it making a ref `<p>{{page("/en-US/docs/Web/API/PannerNode/orientationX","Example")}}</p>` , and the image are write in the page [`PannerNode/orientationX`](https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/orientationX) and work OK on that page, but in ref mode , it broken.

BTW: maybe other ref will have similer issue.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/pannernode/coneouterangle`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/coneOuterAngle
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/pannernode/coneouterangle/index.html
* Last commit: https://github.com/mdn/content/commit/babc0473793bbe3cfa66cd96fae7f84348be373b
* Document last modified: 2021-02-08T10:05:46.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update it 👍

**Comment by Rumyra** [comment]
Thanks @CreaTorAlexander - seems like the image source just needs an edit

**Comment by CreaTorAlexander** [comment]
How does it work with the {{page}}? I am pretty sure I updated it to the correct path but it doesn't seems to work.

**Comment by Rumyra** [comment]
@CreaTorAlexander it was a little more complicated than I first thought sorry...

The {{page}} macro means the example is being pulled from the orientationX property page (actually happens on a number of the panner node property pages) - so the page that needed to be fixed was https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/orientationX

I've opened a PR for it^^ but I thought I should explain in case you come across it again :)

**Comment by CreaTorAlexander** [comment]
Okay, good to know, thanks for your explanation :smile:
