### ISSUE TITLE
[CSS][WebAPI] Enable :state() and CustomStateSet by default

### ISSUE THREAD

**Issue by pepelsbey** [mdn/content#33018]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Features to document

- CSS: `:state()`
- JS: `CustomStateSet`

## Related Gecko bugs

- [Enable CustomStateSet by default (bug 1887543)](https://bugzilla.mozilla.org/show_bug.cgi?id=1887543)

⚠️ Double-check whether it’s shipping in 126.

If not, check/update how it’s documented and mention it in the experimental features.

**Note**: This was earlier targeted only for the Nightly ([1887467#c10](https://bugzilla.mozilla.org/show_bug.cgi?id=1887467#c10)) but is shipping by default now ([1887543](https://bugzilla.mozilla.org/show_bug.cgi?id=1887543)).

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD ?
- [ ] Docs - NA. Lots of work done for this in FF121 and it looks good.
- [ ] Release note/Experimental features #33098
- [ ] dev-docs-complete ?

**Comment by rachelandrew** [comment]
Chrome updates in 125 (release to stable on the 14th May) and fixes the issue mentioned [in the docs here](https://developer.mozilla.org/en-US/docs/Web/API/CustomStateSet#compability_with_dashed-ident_syntax). Rather than "some versions" it might be good to say "before Chrome 125".

**Comment by hamishwillee** [comment]
Thanks @rachelandrew - fixed in https://github.com/mdn/content/pull/33572. Note that just says "check `:state()`. Better future proofing/we try not to mention specific browser versions because that dates badly.
