### ISSUE TITLE
Multi-word font-family names can appear unquoted

### ISSUE THREAD

**Issue by GlenErrands** [mdn/content#33024]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

### What specific section or headline is this issue about?

Formal Syntax

### What information was incorrect, unhelpful, or incomplete?

The production rules for \<family-name> and \<generic-family> both contain a production to \<custom-ident>+ (please note the "+"). This would mean that several \<custom-ident> in sequence, separated by white-space (not by comma) would be considered a valid family-name. Ist this really the case?

### What did you expect to see?

I did expect to see the rules without "+" suffixing \<custom-ident>:

\<family-name> = 
\<string> | \<custom-ident>

\<generic-family> = generic(\<custom-ident>) | \<string> | \<custom-ident>

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-family`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-family/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by Josh-Cena** [comment]
This is exactly what the spec says: https://drafts.csswg.org/css-fonts/#family-name-syntax So yeah, custom ident can appear multiple times. In the spec:

> If a sequence of identifiers is given as a \<family-name>, the computed value is the name converted to a string by joining all the identifiers in the sequence by single spaces.

Maybe this should be in the docs, if it's not already

**Comment by wbamberg** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident doesn't seem especially bad to me.

> several <custom-ident> in sequence, separated by white-space (not by comma) would be considered a valid family-name. Is this really the case?

I think this is covered in https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#valid_family_names: you don't have to quote a family name, even if it contains spaces. So `font-family: Gill Sans;` is allowed, although it isn't good practice, and in terms of the formal syntax, consists to two space-separated `<custom-ident>` values.

**Comment by Josh-Cena** [comment]
Ah it says "custom ident" but my mind said "custom property name". It now makes more sense. Maybe no action is necessary.

**Comment by GlenErrands** [comment]
Thanks, @wbamberg and @Josh-Cena for looking into and clarifying the topic that quickly! Your explanations definitely make sense.

**Comment by wbamberg** [comment]
Thank you @GlenErrands . Although the formal syntax is correct, I think there are legitimate issues with the way the syntax is described in this page, so let's keep this open.

**Comment by Josh-Cena** [comment]
@wbamberg What issues do you have in mind?

**Comment by wbamberg** [comment]
Yeah that wasn't very helpful, sorry :).

There are a couple of things.

One that's hard to fix now is that the formal syntax has the new syntax for `<generic-family>`, which does not restrict authors to a list of keywords, and which adds a `generic()` functional notation: https://drafts.csswg.org/css-fonts-4/#generic-family-name-syntax. As far as I'm aware, browsers don't support this, and (therefore) we don't document it in the rest of the page, so the page is incoherent. This is a manifestation of https://github.com/orgs/mdn/discussions/442, which is a really gnarly problem.

The other though is that the non-formal syntax is a bit vague about the rules for `<family-name>`:

> The name of a font family. For example, "Times" and "Helvetica" are font families. Font family names containing whitespace should be quoted. For example: "Comic Sans MS".

AFAIK the precise definition is: it can be a `<string>` value or a space-separated sequence of `<custom-ident>` values. We have precise definitions of both of these, in https://developer.mozilla.org/en-US/docs/Web/CSS/string and https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident, so we should link to them. We should also distinguish between (1) the syntax rules and (2) good practices, as they are described in https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#valid_family_names, and should probably link there too. So maybe something like:

> The name of a font family. This must be either a single {{cssxref("string")}} value or a sequence of {{cssxref("custom-ident")}} values. See also [Valid family names](#valid_family_names).

Then also in the first para of https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#valid_family_names, we should link to https://developer.mozilla.org/en-US/docs/Web/CSS/string and https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident, something like:

> A font family name must either be given as a single {{cssxref("string")}} value, or as a sequence of one or more {{cssxref("custom-ident")}} values. String values must be quoted but may contain any Unicode character. Custom identifiers are not quoted, but require that certain characters must be escaped.
