### ISSUE TITLE
[WebAPI] Implement URL.parse()

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33080]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [ ] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

[Implement URL.parse() (bug 1887611)](https://bugzilla.mozilla.org/show_bug.cgi?id=1887611)

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/22854
- [ ] Docs
- [ ] Release note #33206
- [ ] dev-docs-complete

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/22854
- [ ] Docs
- [ ] Release note
- [ ] dev-docs-complete
