### ISSUE TITLE
[WebAPI] Update RTCIceCandidate member attribute and parsing

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33085]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

[Bug 1322186: Make RTCIceCandidate members readonly and add members parsed from candidate string](https://bugzilla.mozilla.org/show_bug.cgi?id=1322186)

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
FF126 updates [`RTCIceCandidate`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate) to match spec, with the excetion of two missing properties: [`relayProtocol`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/relayProtocol), [`url`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/url) (will be added by https://bugzilla.mozilla.org/show_bug.cgi?id=1886013).

Changes:
- Existing properties now read-only: [`candidate`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/candidate), [`sdpMid`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/sdpMid), [`sdpMLineIndex`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/sdpMLineIndex), [`usernameFragment`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/usernameFragment)
- The `toJSON()` method now returns an object that matches the format of the object passed to the [`RTCIceCandidate` constructor](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/RTCIceCandidate) (a `RTCIceCandidateInit` according to spec)
- New properties: [`foundation`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/foundation), [`component`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/component), [`priority`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/priority), [`address`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/address), [`protocol`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/protocol), [`port`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/port), [`type`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/type), [`tcpType`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/tcpType), [`relatedAddress`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/relatedAddress), [`relatedPort`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/relatedPort), [`usernameFragment`](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/usernameFragment)

Might also be updates to `RTCIceCandidatePairStats`

**Comment by hamishwillee** [comment]
Status

- [ ] BCD - waiting on BCD team
- [ ] Docs - none required as far as I can tell.
- [ ] Release note
- [ ] dev-docs-complete
