### ISSUE TITLE
[Invalid][WebAPI] Update getAttribute behvior for XUL elements

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33089]
## Acceptance criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes for enabled/preview features
- [ ] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

[Bug 232598: getAttribute for xul-elements should return null for unset attributes](https://bugzilla.mozilla.org/show_bug.cgi?id=232598)

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Status: My guess is that this has no MDN impact (XUL is internal). But asking in https://bugzilla.mozilla.org/show_bug.cgi?id=232598#c27

**Comment by hamishwillee** [comment]
There is [nothing to do here](https://bugzilla.mozilla.org/show_bug.cgi?id=232598#c27). This is essentially a fix to a 21 year old internal feature. Closing
