### ISSUE TITLE
[WebAPI] Implement IDBFactory.databases()

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33084]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Features to document

MDN page: https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/databases
Required: [BCD](https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/databases#browser_compatibility) and release note updates

## Related Gecko bugs

[Implement IDBFactory.databases() to enumerate IndexedDB databases (bug )](https://bugzilla.mozilla.org/show_bug.cgi?id=934640)

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD - waiting on BCD team
- [ ] Docs #33113
- [ ] Release notes
- [ ] dev-doc-complete

**Comment by dipikabh** [comment]
Thank you, Hamish!
