### ISSUE TITLE
[HTTP] Import zstd library

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33086]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Features to document

MDN page: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding#zstd
BCD to be updated:
- Firefox version: https://github.com/mdn/browser-compat-data/blob/main/http/headers/Content-Encoding.json#L100
- MDN URL is no longer valid:
```
             "description": "<code>zstd</code>",
             "mdn_url": "https://developer.mozilla.org/docs/Web/HTTP/Headers/Zstandard_compression",
```

## Related Gecko bugs

[Bug 1871963: Import zstd library](https://bugzilla.mozilla.org/show_bug.cgi?id=1871963)

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Still not sure it is just content encoding affected. 

Status:

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/22838
- [ ] Docs
- [ ] Release notes
- [ ] dev-doc-complete
