### ISSUE TITLE
[CSS] Support for the from keyword in relative color syntax

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33082]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

[[css-color] Parse the `from` keyword for relative color syntax (bug 1889133)](https://bugzilla.mozilla.org/show_bug.cgi?id=1889133)

Note: Needs to be checked if this is available by default or behind a preference

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by bsmth** [comment]
All of the linked PRs are merged so I'm closing as done ✅
