### ISSUE TITLE
Issue with "<input type="checkbox">": value example too small and doesn't work

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#3308]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#value

#### What information was incorrect, unhelpful, or incomplete?
The height on the iframe needs to be set so the content isn't clipped.  (The grey overlay is another bug.)

![image](https://user-images.githubusercontent.com/40804543/111851254-89bf4e80-88e0-11eb-9ae5-96cf22ea6cd8.png)

The example doesn't seem to be useful.  I can check the box, hit Subscribe, but nothing happens.  Is is supposed to demonstrate something other than rendering of the HTML?

#### Specific section or headline?
Value

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/checkbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/checkbox/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much @JustinWebDev . I've fixed the truncation in  #3349

> The example doesn't seem to be useful. I can check the box, hit Subscribe, but nothing happens. Is is supposed to demonstrate something other than rendering of the HTML?

When you hit the example it is submitting the checkbox value to the server. But as it states in the text this has no client-side effect. So there is no real point to this example, other than perhaps to show that the value has no client side effect. 

IMO it should either be removed or a note added to make this clear. I'm not sure the best way, but have asked on PR.
