### ISSUE TITLE
[WebAPI] Implement context loss for CanvasRenderingContext2D

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33090]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

[Bug 1887729: Implement context loss for CanvasRenderingContext2D](https://bugzilla.mozilla.org/show_bug.cgi?id=1887729)

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/22852
- [ ] Docs
- [ ] Release note
- [ ] dev-docs-complete
- [ ]

**Comment by dipikabh** [comment]
Closing this issue as all the listed tasks are marked done.
