### ISSUE TITLE
[css] circle() - Typo?

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#33107]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/circle

### What information was incorrect, unhelpful, or incomplete?

Hello,

In Values/shape-radius/farthest-side,
it is written "For circles, this is the closest side in any dimension."
should we read ? "For circles, this is the farthest side in any dimension."

### What did you expect to see?

Correction if there is a typo

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/basic-shape/circle`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/circle
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/basic-shape/circle/index.md
* Last commit: https://github.com/mdn/content/commit/3a1ad1fcf1a399211b333eed524fe9df13bdb62b
* Document last modified: 2023-08-17T16:25:41.000Z

</details>

**Comment by hamishwillee** [comment]
> should we read ? "For circles, this is the farthest side in any dimension."

Thank you. I think so. Fixed by #33108. Let's see what the reviewers say.
