### ISSUE TITLE
Add details information,  list all patterns layout modes

### ISSUE THREAD

**Issue by zhangenming** [mdn/content#33125]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout

### What information was incorrect, unhelpful, or incomplete?

https://drafts.csswg.org/css-flexbox/#:~:text=CSS%202.1%20defined,applications%20and%20webpages.

I don't know all of them 
There's another one I know (grid)
Hope this page will list all of them

### What did you expect to see?

lits all layout modes

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/css_layout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/index.md
* Last commit: https://github.com/mdn/content/commit/26e2f9883e0e73def04c0e86fec6da3ec42e66b3
* Document last modified: 2024-03-05T14:49:38.000Z

</details>

**Comment by Josh-Cena** [comment]
What you are quoting is merely the possible values of https://developer.mozilla.org/en-US/docs/Web/CSS/display. Our guide does cover those. Unless there's anything specific we are missing, I don't think this issue is actionable.
