### ISSUE TITLE
Issue with "PaymentRequest: paymentmethodchange event": incorrect domxref output

### ISSUE THREAD

**Issue by mems** [mdn/content#3313]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/paymentmethodchange_event

#### What information was incorrect, unhelpful, or incomplete?

```
<p>Before the event handler returns, it calls the event's {{domxref("PaymentRequestUpdateEvent.updateWith", "PaymentMethodChangeEvent.updateWith", "updateWith()")}} method to integrate the changes into the request.</p>
```

Is rendered as:

```html
<p>Before the event handler returns, it calls the event's <a href="/en-US/docs/Web/API/PaymentRequestUpdateEvent/updateWith#updatewith()" title="PaymentMethodChangeEvent.updateWith"><code>PaymentMethodChangeEvent.updateWith.updateWith()</code></a> method to integrate the changes into the request.</p>
```
Note the `PaymentMethodChangeEvent.updateWith.updateWith()`

#### Specific section or headline?

"Examples"

#### What did you expect to see?

Some thing like `PaymentRequestUpdateEvent.updateWith()` or `PaymentMethodChangeEvent.updateWith()`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/paymentrequest/paymentmethodchange_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/paymentmethodchange_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/paymentrequest/paymentmethodchange_event/index.html
* Last commit: https://github.com/mdn/content/commit/9917bf17a97973166bb3cb3812a496e4117a778f
* Document last modified: 2021-01-11T13:30:57.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. Definitely a bug there. Fixed by #3341
