### ISSUE TITLE
"Sticky positioning is a hybrid of relative and fixed positioning" is slightly confusing

### ISSUE THREAD

**Issue by abhay27chauhan** [mdn/content#33146]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/position#sticky_positioning

### What specific section or headline is this issue about?

Sticky positioning

### What information was incorrect, unhelpful, or incomplete?

**In the first line it is written** -> Sticky positioning can be thought of as a hybrid of relative and fixed positioning when its nearest scrolling ancestor `is the viewport`.

### What did you expect to see?

**imo but it should be** -> Sticky positioning can be thought of as a hybrid of relative and fixed positioning when its nearest scrolling ancestor `is in the viewport`

**Comment by Josh-Cena** [comment]
The current text is correct because "fixed" is always relative to the viewport, while "sticky" is relative to the scrolling ancestor. I'm not sure how we can improve it here but this whole thing is a big confusing.
