### ISSUE TITLE
Issue with "WebAssembly Concepts": non-obvious performance comparison

### ISSUE THREAD

**Issue by MaxGraey** [mdn/content#3315]
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Concepts

#### What information was incorrect, unhelpful, or incomplete?

> It generates a small bundle and its performance is slightly slower compared to C or Rust

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/WebAssembly/Concepts#using_assemblyscript

#### What did you expect to see?

This is a very contradictory assessment of the situation. I can give a few examples where AssemblyScript is not inferior and sometimes even surpasses performance [1](https://github.com/AssemblyScript/examples/tree/master/n-body#benchmark), [2](https://jtiscione.github.io/webassembly-wave/index.html) and [3](https://github.com/mapbox/mapbox-gl-js/issues/4835#issuecomment-415191951). If we compare just low-level pure performance, then AS, C and Rust are approximately at the same performance level. If you use complex abstractions, then Rust is really ahead.

I advise you to remove the mention of performance and code size. In addition, these are the parameters that are constantly being improved in all the languages ​​mentioned.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/concepts`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Concepts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/concepts/index.html
* Last commit: https://github.com/mdn/content/commit/89127d859f5761d1e862f5895f259894307ebfff
* Document last modified: 2021-03-11T18:26:20.000Z

</details>

**Comment by MaxGraey** [comment]
Hi again. 
If I open a PR that removes these things, will no one mind?

**Comment by sideshowbarker** [comment]
@MaxGraey Please do go ahead and open a PR for it. The rationale given in the issue description is convincing.
