### ISSUE TITLE
Multiple broken links on the HTTP Headers page

### ISSUE THREAD

**Issue by the-lazy-learner** [mdn/content#33168]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

### What specific section or headline is this issue about?

Redirects, Security, Server-Sent Events, Other

### What information was incorrect, unhelpful, or incomplete?

The webpage for HTTP Headers seems to have a few broken links that currently redirect to a 404 Page Not Found page instead. Examples of this could be found in the screenshot attached.

### What did you expect to see?

Opening these specific links should also redirect to a valid MDN page with additional information on the said header. 

### Do you have any supporting links, references, or citations?

![image](https://github.com/mdn/content/assets/13695177/d17a3399-db33-4730-902f-ed50e1a00b64)

The broken links are highlighted in red on the website.

**Comment by bsmth** [comment]
Thanks a lot for reporting this one. These are all acting as placeholders meant to link to pages that are not yet written. I will be looking at these pages soon and I think we can remove the links if the content remains, or add the missing pages. Either way, there shouldn't be broken links here.

**Comment by Josh-Cena** [comment]
Duplicate of https://github.com/mdn/content/issues/1458
