### ISSUE TITLE
MediaRecorder - can't use audio mime types

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [mdn/content#3317]
## What page(s) did you find the problem on?

No page in particular, I just feel like the documentation is extremely confusing on how to record **audio only** streams. See example below.

## Specific page section or heading?
 
N/A

## What is the problem?

I expected to be able to record audio blobs following a call to `navigator.mediaDevices.getUserMedia({audio: true, video: false})` but it seems like only video mime types are available.

## What did you expect to see?

Expected to be able to, for example, record `audio/mp4` blobs.

## Did you test this? If so, how?

The following block of code throws the error: Uncaught (in promise) DOMException: MediaRecorder constructor: Video cannot be recorded with audio/mp4 as it is an audio type
This is not a helpful error message at all because I am not trying to record any video.

```
navigator.mediaDevices.getUserMedia({audio: true}).then((stream) => {
    
    var mediaRecorder = new MediaRecorder(stream, {mimeType: 'audio/mp4'});

    mediaRecorder.ondataavailable = function(event) {
        var blob = event.data;
        if (blob && blob.size > 0) {
            sendBlobToServer(blob);
        }
    };

    mediaRecorder.start(5000);
})
```

**Comment by asiakay** [comment]
Hello @FredericoCoelhoNunes  I'm wondering if even though there is no video being recorded, the video field might need to be included as a parameter bool, video: false...

**Comment by Rumyra** [comment]
Agree with @asiakay 

To whoever fixes this issue, it looks like the following is needed:

* Test the code with parameter `video: false`
* If this is correct make it more explicit through MediaRecorder docs & getUserMedia method

**Comment by dontcallmedom** [comment]
The error message (from Firefox) is confusing but the problem is not that the browser is trying to record video, but rather that the MIME type is not supported - the code above works with `audio/webm`.

**Comment by dontcallmedom** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1708123 for the confusing Firefox error message

**Comment by Rumyra** [comment]
Thanks so much @dontcallmedom - I think this solves the issue.

Media types are well documented already https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/mimeType
