### ISSUE TITLE
[WebAPI] Add support for shadow DOM selection

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33180]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [ ] Add/remove entry to Firefox experimental features page for preference/released features

## Features to document

- Selection.getComposedRanges() API - allows web authors to get selection endpoints across the shadow boundaries
- Selection.direction API - exposes the direction of the selection
- Specification: https://www.w3.org/TR/selection-api/
- Preference: `dom.shadowdom.selection_across_boundary.enabled`
- [Enabled only in Nightly](https://hg.mozilla.org/integration/autoland/file/tip/modules/libpref/init/StaticPrefList.yaml#l4593):
```
# Whether allowing selection across the boundary
# between shadow DOM and light DOM.
# This is based on https://github.com/mfreed7/shadow-dom-selection
- name: dom.shadowdom.selection_across_boundary.enabled
  type: bool
  value: @IS_NIGHTLY_BUILD@
  mirror: always
```

## Related Gecko bugs

[Bug 1867058: Add the initial support for shadow dom selection](https://bugzilla.mozilla.org/show_bug.cgi?id=1867058)

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD
  - [ ] `Selection.direction` https://github.com/mdn/browser-compat-data/pull/22854
  - [ ] `Selection.getComposedRanges()` TBD
- [ ] Docs
- [ ] Release note
- [ ] Experimental features
- [ ] dev-docs-complete

**Comment by dipikabh** [comment]
Closing this as all tasks seem completed. Thanks, Hamish!
