### ISSUE TITLE
Issue with "Document: keydown event": (Firefox returns 229 key code in one onKeyDown event)

### ISSUE THREAD

**Issue by abonzer** [mdn/content#3320]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event

#### What information was incorrect, unhelpful, or incomplete?
Since Firefox 65, the keydown and keyup events are now fired during IME composition

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/keydown_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/keydown_event/index.html
* Last commit: https://github.com/mdn/content/commit/56d9a678477f0e79232caa8169114519bf02a44a
* Document last modified: 2021-02-19T19:41:18.000Z

</details>

**Comment by hamishwillee** [comment]
@abonzer I understand what you are saying, but I don't understand why this information is seen as "incorrect, unhelpful, or incomplete?"

Can you please explain what you mean?


@chrisdavidmills The text in question is shown here. What this says is that in FF65 we fixed a bug. Shouldn't that be a note in the BCD? If so, is it worth fixing (do you want me to fix it?)

![image](https://user-images.githubusercontent.com/5368500/111924643-b13d3380-8af9-11eb-8925-21814559689c.png)

**Comment by chrisdavidmills** [comment]
@hamishwillee yeah, that info should probably be in BCD. You can fix it if you like, although I don't see this as the most urgent thing to worry about right now. It would be good to have more information about what is wrong, which I see you've requested already.

**Comment by hamishwillee** [comment]
Thanks @chrisdavidmills 
You're right. NOt a priority. 

@abonzer Essentially before FF65 the spec said that key up/down events might be fired or might be suppressed when using a key entry mechanism for other languages (e.g. pinyin). From FF65 we make it clear that this **will** be sent - to be compatible with other main browsers like chrome.

I am closing this. Feel free to reopen if you can provide more information about the problem with this document.
