### ISSUE TITLE
Firefox does support Popover API

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#33218]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Popover_API

### What specific section or headline is this issue about?

Limited availability

### What information was incorrect, unhelpful, or incomplete?

This article says that Firefox does not support this API
![image](https://github.com/mdn/content/assets/40804543/ac030fa2-7ac0-46ba-bbb1-c44ea1ae7d1e)

### What did you expect to see?

That Firefox does support the API (as of 125)

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/125#apis

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/popover_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Popover_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/popover_api/index.md
* Last commit: https://github.com/mdn/content/commit/f8730b451b37940432ea4203fa78a0454e3efee6
* Document last modified: 2024-01-23T15:49:46.000Z

</details>

**Comment by hamishwillee** [comment]
@LeoMcA Is this something that will fix itself in a few days? 

FF is still indicating that 125 is a preview release too, and that became the official release on April 16.

**Comment by foolip** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Popover_API#browser_compatibility depends on https://github.com/mdn/browser-compat-data/pull/22848 being released and MDN upgrading BCD.

The Baseline banner depends on a new release of web-features, which I'm doing in https://github.com/web-platform-dx/web-features/pull/932.

**Comment by hamishwillee** [comment]
THanks all. Closing as the data on the page is now correct.

**Comment by foolip** [comment]
@queengooborg is there a BCD issue tracking making releases soon after updates to browser release data, as discussed earlier this week?

**Comment by queengooborg** [comment]
There is, yes: https://github.com/mdn/browser-compat-data/issues/22919
