### ISSUE TITLE
Issue with "transform": (short summary here please)

### ISSUE THREAD

**Issue by wkz3w59** [mdn/content#3321]
MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/transform

#### What information was incorrect, unhelpful, or incomplete?
" Les transformations qui sont composées entre elles sont appliquées dans l'ordre, de gauche à droite."

#### Specific section or headline?
transform-function

#### What did you expect to see?
" Les transformations, qui sont composées entre elles de gauche à droite, sont donc appliquées de droite à gauche."
See English version : "The transform functions are multiplied in order from left to right, meaning that composite transforms are effectively applied in order from right to left."
Imho mentionning two opposite orders in the same line leads to confusion. Users think of composite transforms as successive operations, which are applied from right to left and not "de gauche à droite".
 
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/css/transform`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/transform
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/transform/index.html
* Last commit: https://github.com/mdn/translated-content/commit/3a83f263f9f234d89316c91c3a57ca346efccfcd
* Document last modified: 2021-03-18T19:18:24.000Z

</details>

**Comment by CreaTorAlexander** [comment]
This should be moved to the *translated-content* repository.

@wkz3w59 would you like to change the content and submit a PR?

**Comment by wkz3w59** [comment]
I don't know how to change the content, and no idea of what a PR is. I know nothing about github.
All I know is that the content in the French translation was wrong, I already reported the error yesterday and it was replaced by another error.

**Comment by CreaTorAlexander** [comment]
> I already reported the error yesterday and it was replaced by another error.

You mean in the content of the site was replaced by another translation error?

> I don't know how to change the content, and no idea of what a PR is. I know nothing about github.


Okay, I will update it 👍  or if you want I can guide you how to update the content.

**Comment by tristantheb** [comment]
Hello @wkz3w59,

This problem has been dealt with and has been sent to production, after checking the page, it now has the correct translation :)

[This issue can be closed]

**Comment by wkz3w59** [comment]
Seems fine for me now. Thank you.
