### ISSUE TITLE
Issue with "Using your new knowledge": Typo "plus the starting point CSS in the head"

### ISSUE THREAD

**Issue by ElijahLynn** [mdn/content#3322]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Using_your_new_knowledge

#### What information was incorrect, unhelpful, or incomplete?
"plus the starting point CSS in the head"

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Using_your_new_knowledge#starting_point

#### What did you expect to see?
"put the starting point CSS in the head"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/first_steps/using_your_new_knowledge`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Using_your_new_knowledge
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/first_steps/using_your_new_knowledge/index.html
* Last commit: https://github.com/mdn/content/commit/ae7855b7d2e257273ab276daa9565de2786947b1
* Document last modified: 2021-01-27T07:44:46.000Z

</details>

**Comment by hamishwillee** [comment]
The English is correct - it means "the file with the HTML and CSS". I have reworded to make this a little easier to read. Thanks for posting.

**Comment by ElijahLynn** [comment]
> The English is correct

Gotcha, thanks for rewording it. Going back it does seem correct, but somehow I was confused when I read it:
> This is a single page with the HTML, plus the starting point CSS in the head of the document.
