### ISSUE TITLE
Default `step` value for `datetime-local` input is incorrect

### ISSUE THREAD

**Issue by laurencejp** [mdn/content#33238]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/step

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/step#syntax

### What information was incorrect, unhelpful, or incomplete?

The default value for `step` in the table in this section for the `datetime-local` input type is listed as "1 (second)". However, on the page for the `datetime-local` input type, the default value is listed as 60 seconds.

### What did you expect to see?

The default to be listed as "60 (seconds)" as it is for the `time` input type.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/step`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/step
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/step/index.md
* Last commit: https://github.com/mdn/content/commit/1582d17d5c39869980f3dc4a249a09292976acfe
* Document last modified: 2024-01-27T10:11:15.000Z

</details>

**Comment by estelle** [comment]
Thank you for finding and filing this issue. I submitted a PR to correct it. https://github.com/mdn/content/pull/33928
