### ISSUE TITLE
There is no 'instant' option in 'behavior'

### ISSUE THREAD

**Issue by QT-HH** [mdn/content#33246]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

### What information was incorrect, unhelpful, or incomplete?

There is no 'instant' option in 'behavior'

behavior option has only 'auto', 'smooth' option.

### What did you expect to see?

no 'instant' option in document

### Do you have anything more you want to share?

It's also scroll(), scrollTo() ...
every scroll API has 'instant' option in document.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/scrollintoview`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/scrollintoview/index.md
* Last commit: https://github.com/mdn/content/commit/bbf7f25f9cf95fb154e2740a9fdc9c02818981bf
* Document last modified: 2023-04-07T05:55:26.000Z

</details>

**Comment by wbamberg** [comment]
> There is no 'instant' option in 'behavior'

There is, though: https://drafts.csswg.org/cssom-view/#enumdef-scrollbehavior.

**Comment by Josh-Cena** [comment]
Related: https://github.com/w3c/csswg-drafts/pull/8107, https://github.com/mdn/content/pull/25467
