### ISSUE TITLE
Issue with "Window.confirm()": (incorrect description of the message parameter)

### ISSUE THREAD

**Issue by GaborLajos** [mdn/content#3324]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm

#### What information was incorrect, unhelpful, or incomplete?
The description of the message parameter refers to the alert dialog instead of the confirm dialog

#### Specific section or headline?
Syntax / Parameters / message

#### What did you expect to see?
A string you want to display in the confirm dialog.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/confirm`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/confirm/index.html
* Last commit: https://github.com/mdn/content/commit/6c2523b8365f2bef7b26dee75ac7c74e686f3f62
* Document last modified: 2021-02-24T02:44:05.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this 👍
