### ISSUE TITLE
autocapitalize=off is considered deprecated by wpt

### ISSUE THREAD

**Issue by valkum** [mdn/content#33258]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize

### What information was incorrect, unhelpful, or incomplete?

According to https://github.com/web-platform-tests/wpt/blame/55cb997b1b096774ac1b8f386b7f4e871e3902e1/html/editing/editing-0/autocapitalization/autocapitalize.html#L33 `on` and `off` are deprecated.
If I change the attribute in the inspector `off` gets replaced by `none` immediately.

This can lead to hydration errors if your server render lib such as `react-dom` take the given value for granted, but your browser normalizes the value to `none`.

### What did you expect to see?

Some mentions about the status of `off` and `on`.

### Do you have any supporting links, references, or citations?

https://github.com/web-platform-tests/wpt/blame/55cb997b1b096774ac1b8f386b7f4e871e3902e1/html/editing/editing-0/autocapitalization/autocapitalize.html#L33

https://phabricator.services.mozilla.com/D86674#2839687

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/autocapitalize`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/autocapitalize/index.md
* Last commit: https://github.com/mdn/content/commit/26ea1a065b861bb59ae1dd14dea053e62ad39969
* Document last modified: 2024-01-02T04:26:07.000Z

</details>

**Comment by estelle** [comment]
The values is still in the spec: https://html.spec.whatwg.org/multipage/interaction.html#attr-autocapitalize, and it works as expected (test the linked page's example on your phone)

nothing to fix, so closing.
