### ISSUE TITLE
Express Tutorial Part 4: Routes and Controllers - Add a word to the sentence.

### ISSUE THREAD

**Issue by Crn0** [mdn/content#33268]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes

### What specific section or headline is this issue about?

adding "or" before "author" would clarify that the form can be used to delete any of those items individually.

### What information was incorrect, unhelpful, or incomplete?

[catalog/object/id/delete — The form to delete a specific book, bookinstance, genre, author with the given _id field value (e.g. /catalog/book/584493c1f4887f06c0e67d37/delete)](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#routes_needed_for_the_locallibrary:~:text=catalog/%3Cobject%3E/%3Cid%3E/delete%20%E2%80%94%20The%20form%20to%20delete%20a%20specific%20book%2C%20bookinstance%2C%20genre%2C%20author%20with%20the%20given%20_id%20field%20value%20(e.g.%20/catalog/book/584493c1f4887f06c0e67d37/delete))

### What did you expect to see?

The form to delete a specific book, bookinstance, genre, **or** author with the given id field value (e.g. /catalog/book/584493c1f4887f06c0e67d37/delete).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/routes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/routes/index.md
* Last commit: https://github.com/mdn/content/commit/9271ab7ac342e3f817269b6da764aaafc0441ee2
* Document last modified: 2023-10-18T18:14:32.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, fixed by https://github.com/mdn/content/pull/33273
