### ISSUE TITLE
Issue with "Feature-Policy": document-domain enabled/disabled

### ISSUE THREAD

**Issue by abdwalfa** [mdn/content#3326]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy

#### What information was incorrect, unhelpful, or incomplete?
It says here:

> When this policy is **disabled**, attempting to set document.domain will fail and cause a SecurityError DOMException to be thrown.

but in this page: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/document-domain

> When this policy is **enabled**, attempting to set document.domain will fail and cause a SecurityError DOMException to be thrown.

also here: https://developer.mozilla.org/en-US/docs/Web/API/Document/domain#failures

> Failures
The setter will throw a "SecurityError" DOMException in several cases:
> 
>- The document-domain Feature-Policy is **enabled**

#### What did you expect to see?
"disabled" in both pages where it is "enabled".

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/feature-policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/feature-policy/index.html
* Last commit: https://github.com/mdn/content/commit/52e3f3e2883851af19e35fd55b5fc59b517620c6
* Document last modified: 2021-02-26T09:16:49.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve raised https://github.com/mdn/content/pull/3900 with a fix.
