### ISSUE TITLE
starting code for task5 is incomplete

### ISSUE THREAD

**Issue by Lime-sisi** [mdn/content#33261]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Selectors_Tasks

### What specific section or headline is this issue about?

task 5 

### What information was incorrect, unhelpful, or incomplete?

Among 5 tasks, the last starting code of TASK 5 lacks link to CSS file

### What did you expect to see?

I expect to see that starting code for task 5 is as complete as other 4, which contains link to stylesheet.

### Do you have any supporting links, references, or citations?

No

### Do you have anything more you want to share?

<img width="739" alt="Screenshot 2024-04-24 at 1 11 36 PM" src="https://github.com/mdn/content/assets/96743084/2bc99c37-fca9-42a2-9576-cddc60454adc">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors/selectors_tasks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Selectors_Tasks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/selectors_tasks/index.md
* Last commit: https://github.com/mdn/content/commit/c64e813d8ab9dbe22cbc049c26f7c6703370a2b7
* Document last modified: 2023-10-23T08:57:58.000Z

</details>

**Comment by caugner** [comment]
I can understand the issue, the starting point for task 4 points [here](https://github.com/mdn/css-examples/blob/c0bf2b25720971a4f2a1d7a1d969efcfcf59052d/learn/tasks/selectors/combinators-download.html#L6) and the `styles.css` file is in the parent directory, so it is not trivial to download.
