### ISSUE TITLE
Use ::after to including icons on links

### ISSUE THREAD

**Issue by yinhx3** [mdn/content#33281]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links

### What specific section or headline is this issue about?

Including icons on links

### What information was incorrect, unhelpful, or incomplete?

Using ::after to including icons on links is easier than using background.
The docs itself use ::after to do so.

### What did you expect to see?

Use ::after to including icons on links as the main content.
Point out using background to including icons as the legacy practice.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/styling_text/styling_links`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/styling_text/styling_links/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by hamishwillee** [comment]
I agree. Would you like to make this change?
