### ISSUE TITLE
Issue with "<h1>–<h6>: The HTML Section Heading elements": (short summary here please)

### ISSUE THREAD

**Issue by sentasker** [mdn/content#3329]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/heading_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/heading_elements/index.html
* Last commit: https://github.com/mdn/content/commit/c40f133b4ed8474730029e68a397aaebb042266b
* Document last modified: 2021-03-01T15:30:53.000Z

</details>

**Comment by sentasker** [comment]
Issue with <h1-<h6..
< h 1> to < h 6 > the most important <16> heading

**Comment by CreaTorAlexander** [comment]
What exactly is the problem on this page?

**Comment by hamishwillee** [comment]
I can't see any problem. I have closed this. 

@sentasker If there is actually a problem, please reopen with information about the specific heading and section where you see it and an explanation (i.e. fill in the template up the top of the page)
