### ISSUE TITLE
Does bzip compression relate to the `Accept-Patch` header?

### ISSUE THREAD

**Issue by T34-active** [mdn/content#33294]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Patch

### What information was incorrect, unhelpful, or incomplete?

The content encoding doesn't seem to have anything to do with this document, so please check if you need to remove the content from the English document.

### What did you expect to see?

I hope this problem is solved by replacing or modifying the text

**Comment by hamishwillee** [comment]
Thanks @T34-active - agreed - should be fixed by #33303
