### ISSUE TITLE
<hgroup> tag is deprecated in HTML5 specifications, but it is not included in "Obsolete and deprecated elements" in the page

### ISSUE THREAD

**Issue by manav-sharma69** [mdn/content#33304]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element

### What specific section or headline is this issue about?

Obsolete and deprecated elements

### What information was incorrect, unhelpful, or incomplete?

`<hgroup>` tag is deprecated in HTML5 specifications, but it is not included in "Obsolete and deprecated elements" in the HTML elements reference page. Instead it is present inside the [Content Sectioning section](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#content_sectioning).

### What did you expect to see?

To see some sort of notification or information regarding the `<hgroup>` tag.
On one hand, there's the public link of *WG Decision on request to drop hgroup from HTML5* (linked below) and on the other hand, neither [HTML Standard](https://html.spec.whatwg.org/) nor the [working draft of W3](https://www.w3.org/TR/2011/WD-html5-20110405/spec.html) specify `<hgroup>` as deprecated or obsolete. 

### Do you have any supporting links, references, or citations?

Here are some links to support it:

- [HTML5 Doctor](https://html5doctor.com/the-hgroup-element/)
- [WG Decision on request to drop hgroup from HTML5](https://lists.w3.org/Archives/Public/public-html-admin/2013Apr/0003.html)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/index.md
* Last commit: https://github.com/mdn/content/commit/7baf5fb133bae54cbd625eb6807ab55666da8d86
* Document last modified: 2024-04-09T10:32:54.000Z

</details>

**Comment by wbamberg** [comment]
`<hgroup>` is not deprecated in that WHATWG spec, which is the relevant spec here.

See also:
- https://github.com/mdn/content/issues/11153
- https://github.com/mdn/content/pull/18530
