### ISSUE TITLE
Content bug: scrollbar-width demo box does not work in Chrome

### ISSUE THREAD

**Issue by jakub-g** [mdn/content#3331]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width

## Specific page section or heading?

Demo just in the beginning

## What is the problem?

See screenshot Firefox vs Chrome 89.
Note: the `scrollbar-width` feature is Firefox only for now, but here the issue is with the demo box itself.

![image](https://user-images.githubusercontent.com/1437027/111908666-5acce800-8a5a-11eb-8fec-5d8c90adfae7.png)
![image](https://user-images.githubusercontent.com/1437027/111908670-5bfe1500-8a5a-11eb-8c9d-a77460ca240c.png)

**Comment by rachelandrew** [comment]
@jakub-g this seems to be expected behaviour. If the browser doesn't support the demo the box just shows the syntax.

**Comment by jakub-g** [comment]
Ah ok, that was not clear to me. I was thinking the demo box is broken, mainly due to its huge size :)
Thanks for response @rachelandrew
