### ISSUE TITLE
Correction: At most one task is completed before microtasks are run

### ISSUE THREAD

**Issue by vinhill** [mdn/content#33327]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide/In_depth

### What specific section or headline is this issue about?

Event loops

### What information was incorrect, unhelpful, or incomplete?

> Each agent is driven by an event loop, which collects any user and other events, enqueuing tasks to handle each callback. It then runs any pending JavaScript tasks, then any pending microtasks, then performs any needed rendering and painting before looping again to check for pending tasks.

### What did you expect to see?

I do not know what would be correct, but I expect something like
> ... It then runs at most one pending JavaScript task ...

### Do you have any supporting links, references, or citations?

This is at least in conflict with the [microtask guide](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide#microtasks)
> First, each time a task exits, the event loop checks to see if the task is returning control to other JavaScript code. If not, it runs all of the microtasks in the microtask queue.

Also, a code example in Firefox:
```
setTimeout(() => {
  console.log("a");
  queueMicrotask(() => console.log("c"))
})
setTimeout(() => console.log("b"))
```
result: "a c b"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/html_dom_api/microtask_guide/in_depth`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide/In_depth
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/html_dom_api/microtask_guide/in_depth/index.md
* Last commit: https://github.com/mdn/content/commit/56c76424a5edb45f6716ac4ee48861dac8e7ae38
* Document last modified: 2023-08-04T07:12:32.000Z

</details>

**Comment by dipikabh** [comment]
Thanks @vinhill for opening this issue. The text can indeed be improved for clarity and accuracy.

Based on the [microtask guide](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide#microtasks), "any pending" can definitely be updated to "one pending". But then moving on to microtasks, we can add the nuance about when microtasks are run, that is, "When that task exits and is not returning control to other JavaScript code, it runs all pending microtasks."

Would you be interested in opening a PR to submit a fix?

**Comment by vinhill** [comment]
Thanks for triaging.

I'm not fully familiar with the event loop. I submitted an issue rather than a PR in case someone more knowledgeable identifies additional aspects to be improved.

I'll see whether I find the time this week to submit a fix and read through the remainder of the page.

**Comment by vinhill** [comment]
Fixed by commit https://github.com/mdn/content/commit/06cdd3a0fe4079360fa0bffb6329e9dc95029dac
