### ISSUE TITLE
Issue with "Audio and video manipulation": no usage of intermediary <canvas> element in the code example

### ISSUE THREAD

**Issue by tadjik1** [mdn/content#3333]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_manipulation

Hello, I misunderstood part of the article which shows an example of grayscaling video.

#### What information was incorrect, unhelpful, or incomplete?

It says in the beginning that in order to process with video frame an intermediary <canvas> element should be used:

```
The general technique is to:

Write a frame from the <video> element to an intermediary <canvas> element.
Read the data from the intermediary <canvas> element and manipulate it.
Write the manipulated data to your "display" <canvas>.
Pause and repeat.
```

However later in the same article same canvas element used for "write a frame", "read data" and "write the manipulated data".

```js
this.video = document.getElementById("my-video");
this.c1 = document.getElementById("my-canvas");
this.ctx1 = this.c1.getContext("2d");

...
computeFrame: function() {
  this.ctx1.drawImage(this.video, 0, 0, this.width, this.height);
  var frame = this.ctx1.getImageData(0, 0, this.width, this.height);
  var l = frame.data.length / 4;
  
  for (var i = 0; i < l; i++) {
    var grey = (frame.data[i * 4 + 0] + frame.data[i * 4 + 1] + frame.data[i * 4 + 2]) / 3;
    
    frame.data[i * 4 + 0] = grey;
    frame.data[i * 4 + 1] = grey;
    frame.data[i * 4 + 2] = grey;
  }
  this.ctx1.putImageData(frame, 0, 0);
  
  return;
}
...

```

#### Specific section or headline?

Video manipulation:
https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_manipulation#video_manipulation

#### What did you expect to see?
Usage of different <canvas> elements.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/guide/audio_and_video_manipulation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_manipulation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/audio_and_video_manipulation/index.html
* Last commit: https://github.com/mdn/content/commit/1d83cd41017e16c13363c2d4db3b8d4a5b4edf0e
* Document last modified: 2021-03-17T14:32:50.000Z

</details>

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* The 'intermediary' canvas element is not needed -> check the example code on the page, however it should work as is
* Remove references to the intermediary canvas element in the opening explanation
* Possibly add a note to say you can create the same effect with CSS filters

**Comment by tadjik1** [comment]
@Rumyra interesting! 
But won't it lead to some visual glitches if processing takes long? As far as I understood in that case this "intermediate" frame will be displayed on canvas. Am I right that intermediate canvas is needed when you want to process video but don't want to display original frames?

**Comment by Rumyra** [comment]
I think you have highlighted that there's possibly a bigger issue that the article needs a bit of modernising @tadjik1 - if you want to process video frames to display on canvas you should consider using streams and/or workers/offscreencanvas.

I'm going to keep this issue and fix as is for now - but contemplate whether processing video performantly could be something to also address. If so I'm leaning towards a separate issue.

Happy to hear your thoughts :)

**Comment by tadjik1** [comment]
@Rumyra that sounds good to me, you are absolutely right!

I'd like to prepare PR for this issue :)

**Comment by tadjik1** [comment]
thanks for the help @Rumyra!

**Comment by Rumyra** [comment]
Thank *you* @tadjik1 - this is awesome 😎
