### ISSUE TITLE
Definition of "same-site" is not correct

### ISSUE THREAD

**Issue by sashee** [mdn/content#33348]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Site

### What specific section or headline is this issue about?

Directives/same-site

### What information was incorrect, unhelpful, or incomplete?

According to the current wording a request is considered same-site if only the port is different. But it is also set to same-site for different subdomains.

For example, when I send this request from https://samesitedemo-attacker.jub0bs.com/:

```
fetch("https://samesitedemo.jub0bs.com/readcookie", {method: "POST", headers: {"Content-Type": "application/x-www-form-urlencoded"}, credentials: "include"})
```

The request headers I see in the Chromium devtools are:

```
:authority: samesitedemo.jub0bs.com
:method: POST
Content-Length: 0
Content-Type: application/x-www-form-urlencoded
Cookie: StrictCookie=foo; __Host-abc=val
Origin: https://samesitedemo-attacker.jub0bs.com
Referer: https://samesitedemo-attacker.jub0bs.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
...
```

Notice that ```Sec-Fetch-Site``` is ```same-site``` but the originating domain (```https://samesitedemo-attacker.jub0bs.com```) is different than the target domain (```https://samesitedemo.jub0bs.com```).

### What did you expect to see?

```same-site``` is set when the scheme + (eTLD+1) is the same for the originator and the target (ref: https://web.dev/articles/schemeful-samesite). I'd expect this is more pronounced in the documentation page.

For example:

> The request initiator and the server hosting the resource have the same scheme and registrable domain (its public suffix plus one subdomain) but not necessarily have the exact domains or ports.
>
> See the [Public suffix list](https://publicsuffix.org/list/public_suffix_list.dat)
>
> Examples:
> * ```https://example.com``` and ```https://sub.example.com```, as their registrable domains are the same (public suffix is ```.com```, plus one subdomain is ```example.com``` for both cases)
> * ```https://test.github.io``` and ```https://sub.test.github.io```, same reason (public suffix is ```github.io```)
> * ```https://example.com``` and ```https://example:8443.com```, as only the port is different

### Do you have anything more you want to share?

I was reading the https://jub0bs.com/posts/2021-01-29-great-samesite-confusion/ article and made some tests when I realized that the documentation on MDN is not correct.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/sec-fetch-site`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Site
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/sec-fetch-site/index.md
* Last commit: https://github.com/mdn/content/commit/835d6632d59993861a0458510402787f8a2c3cb3
* Document last modified: 2023-10-25T17:27:32.000Z

</details>

**Comment by wbamberg** [comment]
Yes, we do have a proper definition of this at https://developer.mozilla.org/en-US/docs/Glossary/Site, which this page should probably be linking to.
