### ISSUE TITLE
glossary: external see-also link

### ISSUE THREAD

**Issue by PassionPenguin** [mdn/content#33349]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/baseline

### What specific section or headline is this issue about?

see also

### What information was incorrect, unhelpful, or incomplete?

link https://en.wikipedia.org/wiki/baseline was kind of a disambigious wiki page. should it be about baseline_(typography) or just the disambigious page itself?### 

### What did you expect to see?

na

**Comment by wbamberg** [comment]
Thanks for filing! Yes, I think it would be best just to link to https://en.wikipedia.org/wiki/Baseline_(typography) here.

**Comment by PassionPenguin** [comment]
last modified #26676, where in the merge, `baseline/compatibilitiy` was added and `baseline` was modified to a disambigious link.

however, the wikipedia disambigious page got so many unrelated information that is unrelevent to the glossary (`baseline*`) we describe here.

will it be better to link to baseline(typograph) and add a link to baseline(configuration management?), or just delete the link in baseline, add it respectively in `baseline/compatibility` & `baseline/typography`

<img width="971" alt="Screenshot 2024-05-02 at 9 25 52 AM" src="https://github.com/mdn/content/assets/41184947/12f70848-4f65-4691-8d8e-8e8b76d149a5">
