### ISSUE TITLE
Subresource Integrity check on Request instance with integrity property

### ISSUE THREAD

**Issue by juandelacruz23** [mdn/content#33356]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

### What specific section or headline is this issue about?

How browsers handle Subresource Integrity

### What information was incorrect, unhelpful, or incomplete?

Checking the article for the [integrity property](https://developer.mozilla.org/en-US/docs/Web/API/Request/integrity) in the Request interface, it links to the article for Subresource Integrity. 

While reading that article, I was left wondering if, when using the Fetch api, passing a Request instance with an integrity value would be validated by the browser, just as if the property was set on the attribute of a script tag.

### What did you expect to see?

If this check also applied to requests that have an integrity check set in JavaScript, through `Request`'s constructor.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/security/subresource_integrity`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/security/subresource_integrity/index.md
* Last commit: https://github.com/mdn/content/commit/864e7a830d3f658b4cd87098428097bda5ee5b84
* Document last modified: 2024-01-02T08:34:12.000Z

</details>

**Comment by Josh-Cena** [comment]
Yes it does. See https://fetch.spec.whatwg.org/#main-fetch, step 22

**Comment by juandelacruz23** [comment]
> Yes it does. See https://fetch.spec.whatwg.org/#main-fetch, step 22

Should this be added somewhere in that page?

**Comment by Josh-Cena** [comment]
Yes
