### ISSUE TITLE
The MDN acronym is never spelled out anywhere

### ISSUE THREAD

**Issue by xuhdev** [mdn/content#33362]
### MDN URL

N/A

### What information was incorrect, unhelpful, or incomplete?

MDN, as in the title of the website, is an acronym that is used in many places on the website. However, it is never spelled out anywhere. This leads to guesswork from a reader (maybe it is "Mozilla Developer Network"? "Mozilla Development Network"? "Mozilla Documentation Network"?)

This guesswork also hinders citation in formal occasions.

### What did you expect to see?

At least MDN should be spelled once in the [about](https://developer.mozilla.org/en-US/about) page.

**Comment by Josh-Cena** [comment]
"MDN" is not an acronym. It previously stood for "Mozilla Developer Network" but is now just a brand by itself. Its full name is "MDN Web Docs".
