### ISSUE TITLE
Issue with "BigInt": Adding n to a literal creates a bigint primitive, not a BigInt object

### ISSUE THREAD

**Issue by mt-xing** [mdn/content#3336]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

#### What information was incorrect, unhelpful, or incomplete?

This page reads:
> A BigInt is created by appending n to the end of an integer literal — 10n — or by calling the function BigInt().

where earlier a `BigInt` was defined to be an object:

> BigInt is a built-in object that provides a way to represent whole numbers...

This is, however, incorrect, as appending `n` to the end of an integer or calling the function `BigInt()` creates a `bigint` primitive, not a `BigInt` object.

Indeed, both `1n instanceof BigInt` and `BigInt(1) instanceof BigInt` will fail.

#### Specific section or headline?

BigInt > Description

First sentence

#### What did you expect to see?

I assume `BigInt` should have just been lowercase, as in:
> A bigint is created by appending n to the end of an integer literal — 10n — or by calling the function BigInt().

Although it may be a good idea to explicitly specify that it's a primitive that's being created.

Other MDN pages do correctly refer to the primitive by its lowercase name:

https://developer.mozilla.org/en-US/docs/Glossary/Primitive

> There are 7 primitive data types: string, number, bigint, boolean, undefined, symbol, and null.

#### Did you test this? If so, how?

Chrome dev console, running both:
```
1n instanceof BigInt
// Produces false
```
as well as
```
BigInt(1) instanceof BigInt
// Produces false
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/bigint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/bigint/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks very much for catching this and for reporting it — I’ve opened https://github.com/mdn/content/pull/3354 with a change to address it. It seems that making the article be clear on this requires more than changing the first paragraph — so I updated it throughout to consistently use the term “BigInt value” (without monospace formatting), and to state at the beginning of the article that a “BigInt value” just means a `bigint` primitive.

That’s consistent with the terminology used in the ES spec:

https://tc39.es/ecma262/#sec-terms-and-definitions-bigint-value
> ### 4.4.28 BigInt value
> primitive value corresponding to an arbitrary-precision integer value
