### ISSUE TITLE
Mixed Format of Lists in content

### ISSUE THREAD

**Issue by PassionPenguin** [mdn/content#33372]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN

### What specific section or headline is this issue about?

definition_lists

### What information was incorrect, unhelpful, or incomplete?

mixed recommendation of list format

```markdown
- term1

  - : My description of term1

- `term2`

  - : My description of term2

    It can have multiple paragraphs, and code blocks too:

    ```js
    const thing = 1;
    ```
```

and with no empty line between list item-sublist/another list item (both, generated the same result in both gfm and yari)

```markdown
- `param1`, `param2`, `param3`
  - : My description of params 1, 2, and 3
```

we have more than 10k list with no empty line between, and 1559 list with empty line between.

### What did you expect to see?

```markdown
- term1
  - : My description of term1
- `term2`
  - : My description of term2

    It can have multiple paragraphs, and code blocks too:

    ```js
    const thing = 1;
    ```
```

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

**Comment by Josh-Cena** [comment]
This is how Prettier formats Markdown. We use empty lines if the sublist has more than 1 paragraph of content.
