### ISSUE TITLE
Interactive example/docs: input type="month"

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#3339]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month#handling_browser_support

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month#handling_browser_support

"Handling Browser Support"

## What is the problem?

See markup - months make assumptions about timezone. If input succeeds, text is wrong.

![image](https://user-images.githubusercontent.com/5368500/111923808-15a9c400-8af5-11eb-9cc7-612fcc008249.png)

## What did you expect to see?

Month range allowed, and text format only visible if pattern succeeds.

## Did you test this? If so, how?

Navigated to page :-). This follows on from review for #3268

**Comment by sidverma32** [comment]
@mirunacurtean  Anyone is working on this or can i take this up?

**Comment by hamishwillee** [comment]
@sidverma32 I think I'll just fix this one. Thanks for offering though.

**Comment by hamishwillee** [comment]
Fixed. Note that the pattern part of this issue was incorrect - that bit of the example was fine.
