### ISSUE TITLE
SVG presentation properties not included in CSS cascade information

### ISSUE THREAD

**Issue by BeksOmega** [mdn/content#33402]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade

### What specific section or headline is this issue about?

Maybe https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade#author_styles_inline_styles_layers_and_precedence

### What information was incorrect, unhelpful, or incomplete?

There's no reference to how presentation attributes (e.g. `<path fill="#fff" ... />`) in svg are considered. I assumed that they were treated as inline styles, but this is incorrect.

### What did you expect to see?

Presentation attributes are treated as having 0-specificity, and being first in the order of author styles.

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/SVG11/styling.html#:~:text=For%20user%20agents,%E2%80%98style%E2%80%99%20attributes.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/cascade`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/cascade/index.md
* Last commit: https://github.com/mdn/content/commit/88930816e169c5b51afdfcd22c3b2c54383a22b7
* Document last modified: 2023-11-22T13:04:52.000Z

</details>

**Comment by hariharan0905** [comment]
@BeksOmega can you please assign me!!

**Comment by BeksOmega** [comment]
Hiya @hariharan0905 I'm not a maintainer on this repo, just someone filing a bug =) Once the maintainers have time to take a look they'll see if it makes sense to fix this!

**Comment by hariharan0905** [comment]
@BeksOmega thank you for your infromation!

**Comment by hariharan0905** [comment]
@BeksOmega ok sure!
