### ISSUE TITLE
code is messed up

### ISSUE THREAD

**Issue by lakenov** [mdn/content#33424]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi

### What specific section or headline is this issue about?

the code for 3rd place on the bdi example is messed up and doesnt show 3rd correctly

### What information was incorrect, unhelpful, or incomplete?

the code is <li><span class="name">سما</span>: 3rd place</li>
it needs to be <li><span class="name">سما</span>: <bdi>3rd place</bdi></li>      to have it showing up proper

### What did you expect to see?

the 3 in the right place

### Do you have anything more you want to share?

have a good day :)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/bdi`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/bdi/index.md
* Last commit: https://github.com/mdn/content/commit/fdd3ac5598c3ddceb71e59949b003936ae99f647
* Document last modified: 2024-02-22T19:57:33.000Z

</details>

**Comment by lakenov** [comment]
not showing up properly but <bdi> before 3rd place and then </bdi>

**Comment by wbamberg** [comment]
> I think the intention there is to show that if you write code like that, the output will be messed up.

Yes, exactly, the messed-upness of (3) is intentional.
