### ISSUE TITLE
there is a error in the sample code of reverse

### ISSUE THREAD

**Issue by khoudj** [mdn/content#33437]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse

### What specific section or headline is this issue about?

The code sample

### What information was incorrect, unhelpful, or incomplete?

const reversed = array1.reverse();
console.log('reversed:', reversed);
// Expected output: "reversed:" Array ["three", "two", "one"]

### What did you expect to see?

const reversed = array1.reverse();
console.log('reversed:', reversed);
// Expected output: "reversed:" Array ["two", "three", "one"]

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/reverse`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/reverse/index.md
* Last commit: https://github.com/mdn/content/commit/e01fd6206ce2fad2fe09a485bb2d3ceda53a62de
* Document last modified: 2023-09-07T01:45:56.000Z

</details>

**Comment by Josh-Cena** [comment]
Current output is correct.

<img width="798" alt="image" src="https://github.com/mdn/content/assets/55398995/42843887-908e-4994-95a7-b1c40863fe52">
