### ISSUE TITLE
Issue with "color-scheme": some content does not display

### ISSUE THREAD

**Issue by ende124** [mdn/content#3343]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

#### What information was incorrect, unhelpful, or incomplete?
Two sections, formal definition and formal syntax seems to have some kind of error.
![image](https://user-images.githubusercontent.com/3050747/111930533-79160080-8ab9-11eb-8227-c226af44ccb8.png)

#### Specific section or headline?
formal definition and formal syntax

#### What did you expect to see?
Some actual information

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/color-scheme`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/color-scheme/index.html
* Last commit: https://github.com/mdn/content/commit/dc1fa46e0ed0142547ab1961d8b5b5dd60daf1af
* Document last modified: 2021-03-19T09:25:45.000Z

</details>

**Comment by rachelandrew** [comment]
@ende124 thanks for the report - the PR for this content comes from another repo and is just waiting to be merged, then it will show up.
