### ISSUE TITLE
Issue with "JSON.stringify()": Reference doesn't work. Status 502.

### ISSUE THREAD

**Issue by pheianox** [mdn/content#3344]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

Link "[not a completely strict subset of JavaScript](http://timelessrepo.com/json-isnt-a-javascript-subset)" redirects to a page with 502 server error.

Section: **Issue with plain JSON.stringify for use as JavaScript**

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/json/stringify`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/json/stringify/index.html
* Last commit: https://github.com/mdn/content/commit/48fca0c614add538e95f1075b2777fc396023d31
* Document last modified: 2021-03-16T07:50:01.000Z

</details>

**Comment by Elchi3** [comment]
Thanks for your report! I think we should remove the link.

**Comment by pheianox** [comment]
My pleasure!

**Comment by CreaTorAlexander** [comment]
I created #3396 to fix this
