### ISSUE TITLE
Computers DO NOT start counting at zero!

### ISSUE THREAD

**Issue by JMarkMurphy** [mdn/content#33440]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Arrays

### What specific section or headline is this issue about?

Note in Arrays

### What information was incorrect, unhelpful, or incomplete?

The notes says "Computers start counting at zero". This is incorrect. In reality computers start counting at whatever arbitrary number you like. When speaking of Array indexes It might seem correct to blame computers for the starting point, but Many languages, like BASIC, Fortran, COBOL, and R, start numbering array indexes at 1, and some (e.g. PL/1) even allow you to start and stop array indexes at any arbitrary number. And in fact, Javascript doesn't always start counting at 0. array.length tells the number of available slots counting from 1, string.length tells the number of characters in the string counting from 1.

### What did you expect to see?

It would be more accurate to say "Javascript starts indexing arrays at zero" because it is the language, not the computer that defines where array indexing starts. And in fact, Javascript doesn't always start counting at 0. array.length tells the number of available slots counting from 1, string.length tells the number of characters in the string counting from 1.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/arrays`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Arrays
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/arrays/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by hamishwillee** [comment]
Completely agree with your point and proposed solution. We'd welcome a PR patch if you have time?
