### ISSUE TITLE
Issue with "Symbol": First section could use a re-write

### ISSUE THREAD

**Issue by jocassid** [mdn/content#3345]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

#### What information was incorrect, unhelpful, or incomplete?

unhelpful

#### Specific section or headline?

This section starts with the sentence "The data type symbol is a primitive data type."

#### What did you expect to see?

This could use a better explanation as to what symbols are and why a programmer might want to explicitly use one.  I gather it has something to do with symbol tables (something i didn't learn about till my compilers course in college).  The sentence beginning with "The Symbol() function ..." doesn't make sense.  I think that's a grammatical error (comma splice or run-on).

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/symbol`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/symbol/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this issue.

> This could use a better explanation as to what symbols are and why a programmer might want to explicitly use one.

I agree. So I’ve opened https://github.com/mdn/content/pull/3413 with patch that changes the opening paragraph to this:

> `Symbol` is a built-in object whose constructor returns a **symbol** primitive — also called a **Symbol value** or just a **Symbol** — that’s guaranteed to be unique. Symbols are often used to add unique property keys to an object that won’t collide with keys any other code might add to the object, and which are hidden from any mechanisms other code will typically use to access the object. That enables a form of weak encapsulation, or a weak form of information hiding.

That’s still a bit long, but I think that makes the purpose of Symbols in JavaScript much more clear.

> The sentence beginning with "The Symbol() function ..." doesn't make sense. I think that's a grammatical error (comma splice or run-on).

Yeah, that entire sentence wasn’t really serving any useful purpose anyway — so I completely removed it.
