### ISSUE TITLE
Confusing wording around return value of RTCPeerConnection.createOffer

### ISSUE THREAD

**Issue by srujzs** [mdn/content#33453]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createOffer

### What specific section or headline is this issue about?

Return value

### What information was incorrect, unhelpful, or incomplete?

In the main section, the return value is described as:

> The return value is a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) which, when the offer has been created, is resolved with a [RTCSessionDescription](https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescription) object containing the newly-created offer.

But then in the "Return value" section, it states:

> A [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) whose fulfillment handler will receive an object conforming to the [RTCSessionDescriptionInit](https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescription/RTCSessionDescription#rtcsessiondescriptioninit) dictionary which contains the SDP describing the generated offer. That received offer should be delivered through the signaling server to a remote peer.

which seems incompatible, or at the very least, confusing.

### What did you expect to see?

The sections describing the return value should be the same.

**Comment by Josh-Cena** [comment]
Do you mean that `RTCSessionDescriptionInit` and `RTCSessionDescription` are incompatible? The correct one should be `RTCSessionDescriptionInit` per spec. Technically, the two objects have the same properties so it shouldn't be _too_ jarring_, but it's not an `RTCSessionDescription` instance.

**Comment by srujzs** [comment]
`RTCSessionDescription` seems to have an extra `toJSON` method which `RTCSessionDescriptionInit` does not. For the most part, they're similar enough, but having inconsistent wording is a little bit confusing.
