### ISSUE TITLE
Documentation page introducing CSS paint() feature not working

### ISSUE THREAD

**Issue by a-figerou** [mdn/content#33480]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/image/paint

### What specific section or headline is this issue about?

Play https://developer.mozilla.org/en-US/play

### What information was incorrect, unhelpful, or incomplete?

The page is presenting an CSS animation called play() and in order to see it in action, the user click on the button PLAY. It opens in new tab https://developer.mozilla.org/en-US/play. 

### What did you expect to see?

We should be able to see the text getting colorful. Or at least warn the user it is not a working feature for Firefox according to:
https://developer.mozilla.org/en-US/docs/Web/API/PaintWorkletGlobalScope

### Do you have any supporting links, references, or citations?

The console of https://developer.mozilla.org/en-US/play, display on the page, is indicating:
    TypeError: CSS.paintWorklet is undefined

### Do you have anything more you want to share?

Environment:
Firefox

**Comment by caugner** [comment]
FWIW The [browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/CSS/image/paint#browser_compatibility) on the page indicates that Firefox does not support `paint()`.

**Comment by Josh-Cena** [comment]
Indeed, neither `paint()` nor `CSS.paintWorklet` is supported in Firefox. Please check compatibility before using any API, both in the MDN playground and in your own code.
