### ISSUE TITLE
Issue with link on page about logical borders

### ISSUE THREAD

**Issue by CodyMaster007** [mdn/content#33489]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders

### What specific section or headline is this issue about?

Rounded corners

### What information was incorrect, unhelpful, or incomplete?

In a note, link on page about logical borders is incorrect. Check in image below
![image](https://github.com/mdn/content/assets/82391244/04d31924-100a-4e45-a20b-f4e75a543294)

### What did you expect to see?

I expected to see link on another page

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/backgrounds_and_borders`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/backgrounds_and_borders/index.md
* Last commit: https://github.com/mdn/content/commit/4d4e7617f5d573bbf8f51333b959c73b10262d52
* Document last modified: 2024-04-30T06:47:37.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting. It looks like the link is missing an open bracket, like:

```diff
- properties]/en-US/docs/Web/CSS...
+ properties](/en-US/docs/Web/CSS...
```

here:

```md
> **Note:** Like with the border properties above, these border-radius properties also have mapped [_logical_ border-radius properties](/en-US/docs/Web/CSS/CSS_logical_properties_and_values#properties_for_border_radius).
```

https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/backgrounds_and_borders/index.md?plain=1#L296

Would you like to open a PR to fix it?

**Comment by CodyMaster007** [comment]
Yeah
