### ISSUE TITLE
[CSS] Implement @starting-style

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33518]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

[Bug 1834876](https://bugzilla.mozilla.org/show_bug.cgi?id=1834876): [css-transitions-2] Implement `@starting-style` to fill in initial state for CSS transitions

## Related pages on MDN

https://developer.mozilla.org/en-US/docs/Web/CSS/@starting-style

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by dletorey** [comment]
- [Experimental Release note PR](https://github.com/mdn/content/pull/33679)
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/23138)
