### ISSUE TITLE
[CSS][Nightly] Enable relative color syntax on nightly

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33517]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

[Bug 1893965](https://bugzilla.mozilla.org/show_bug.cgi?id=1893965): [css-color] Enable relative color syntax on nightly

Also check doc issue https://github.com/mdn/content/issues/33586.
Both bugs [1893965](https://bugzilla.mozilla.org/show_bug.cgi?id=1893965) and [1889561](https://bugzilla.mozilla.org/show_bug.cgi?id=1889561) are part of [1701488: interop-2024-relative-color-syntax](https://bugzilla.mozilla.org/show_bug.cgi?id=1701488)

## Related pages on MDN

- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_colors/Relative_colors
- https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by pepelsbey** [comment]
- https://github.com/mdn/browser-compat-data/pull/23210

**Comment by dletorey** [comment]
## Associated Pull Requests

- [Firefox Experimental release not PR](https://github.com/mdn/content/pull/34053)
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/23340)

**Comment by dipikabh** [comment]
Closing this as related docs have been updated
