### ISSUE TITLE
Issue with "From object to iframe — other embedding technologi…": (link to Peter Elst article + Flash player example)

### ISSUE THREAD

**Issue by RPIERIS** [mdn/content#3351]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies

#### What information was incorrect, unhelpful, or incomplete?
The link provided to "Peter Elst was already writing some years ago" takes you to a page that [reads Google plus is no longer available](https://plus.google.com/+PeterElst/posts/P5t4pFhptvp).

Also wondering if Adobe flash is now blocked if this [demonstration](https://mdn.github.io/learning-area/html/multimedia-and-embedding/other-embedding-technologies/embed-flash.html) 

#### Specific section or headline?
[Under the <Embed> and <object> elements](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies#the_%3Cembed%3E_and_%3Cobject%3E_elements) for the flash player 

[Peter Elst is in the Case against plugins section](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies#the_case_against_plugins)

#### What did you expect to see?
An article by Peter Elst

#### Did you test this? If so, how?
Yes by opening up the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/other_embedding_technologies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.html
* Last commit: https://github.com/mdn/content/commit/9e18a29da5ea7868959189d327309c4ad1e581bb
* Document last modified: 2021-03-18T14:53:09.000Z

</details>

**Comment by rachelandrew** [comment]
@RPIERIS thanks for the report.

For anyone updating this, the page needs updating with regard to the above link, demo, and the note about Flash which is now outdated.
