### ISSUE TITLE
[CSS] Implement margin at-rules

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33519]
## Acceptance criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes for enabled/preview features
- [ ] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

- [Bug 1833466](https://bugzilla.mozilla.org/show_bug.cgi?id=1833466): Implement CSSMarginRule
- Related - [Bug 856371](https://bugzilla.mozilla.org/show_bug.cgi?id=856371): [css3-page] implement @page margin boxes
- Preference: `layout.css.margin-rules.enabled`

Spec:
- https://drafts.csswg.org/css-page-3/#margin-at-rules
- https://drafts.csswg.org/cssom/#the-cssmarginrule-interface

## Related pages on MDN

- https://developer.mozilla.org/en-US/docs/Web/CSS/@page#margin_at-rules
- https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by pepelsbey** [comment]
- BCD https://github.com/mdn/browser-compat-data/pull/23167

**Comment by pepelsbey** [comment]
The feature is only partially implemented behind the flag. Moved the task to the backlog.
