### ISSUE TITLE
is Object.create(null) has prototype?

### ISSUE THREAD

**Issue by pengzhijian** [mdn/content#33547]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain

### What information was incorrect, unhelpful, or incomplete?

![image](https://github.com/mdn/content/assets/133614612/0ed0e2dd-be6f-49c9-8c73-9b186f301be2)
![image](https://github.com/mdn/content/assets/133614612/50569c26-7474-4f85-99f9-8588360a2fe8)

### What did you expect to see?

this article say each object has an internal link to another object called its prototype.But other say Also allows the creation of objects without a prototype, using Object.create(null).I want know which is right.

**Comment by xBZZZZ** [comment]
I think these mean same thing:
- object has no prototype
- object's prototype is `null`

**Comment by Josh-Cena** [comment]
We should remove the mention of `Object.create(null)`, as literally every other object creation method allows null prototypes here. I also think "without a prototype" is technically wrong but I think few people go into that level of detail as "null prototype" and "no prototype" are generally the same thing.

**Comment by ajeetgill** [comment]
@pengzhijian In js, yes every object has a internal `[[Prototype]]` "link" which points to some prototype.
Now this prototype for new objects is `Object.prototype` by default, i.e. new objects can not have their `[[Prototype]]` link be pointed to `null' (to not have a prototype).

So to create objects with `null` as their `[[Prototype]]`, we do,
```js
const obj = {};
Object.getPrototypeOf(obj) == Object.prototype  // initially, true

obj.__proto__ = null // now the [[Prototype]] is null
Object.getPrototypeOf(obj) == Object.prototype  // false
```
The step which took two lines, can now be completed in one line `Object.create(null)`.
In both cases, the [[Prototype]] is pointing to an object, it's just in `obj = {}` that prototype object has some key-value pairs.
In contrast to `Object.create(null)`, whose 'prototype' object has no key-value pairs.

So from this point of view, technically the screenshot is correct, it's just the confusing way 'Prototype' gets used, even after going through ES-specs I'm slightly confused.

**Comment by ajeetgill** [comment]
@pengzhijian In js, yes every object has a internal `[[Prototype]]` "link" which points to some 'prototype object'.
For new objects created in manner, `let obj = {};`, the default 'prototype object' is `Object.prototype`, i.e. these new objects can not have their `[[Prototype]]` link be pointed to `null' (often said as "to not have a prototype").

So to create objects with `null` as their `[[Prototype]]`, we do,
```js
let obj = {};
Object.getPrototypeOf(obj) == Object.prototype  // true

obj.__proto__ = null // now the [[Prototype]] is null
Object.getPrototypeOf(obj) == Object.prototype  // false
```
With `Object.create(null)` what took two lines, now takes one line.
In both cases, the [[Prototype]] is pointing to an 'prototype object', it's just in `obj = {}` that 'prototype object' has some pre-existing key-value pairs (`Object.prototype`). In contrast to `Object.create(null)`, whose 'prototype object' has no key-value pairs.

In the screenshot, I agree, _"without a prototype"_ can be confusing if taken too literally.
Other than that, on technicality the screenshot is correct.
