### ISSUE TITLE
text-wrap-style Values

### ISSUE THREAD

**Issue by xBZZZZ** [mdn/content#33549]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap-style

### What specific section or headline is this issue about?

Values

### What information was incorrect, unhelpful, or incomplete?

<ul><li><blockquote cite="https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap-style#values"><dl><dt id="auto"><a href="#auto"><code>auto</code></a></dt><dd><p>Text does not wrap across lines. It will overflow its containing element rather than breaking onto a new line.</p></dd></dl></blockquote>but<pre lang="html">&lt;div style="text-wrap-style:auto;width:3em;">hello world&lt;/div></pre>is 2 lines (testing with librewolf 125.0.3-1)</li><li><blockquote cite="https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap-style#values"><dl><dt id="pretty"><a href="#pretty"><code>pretty</code></a></dt><dd><p>Results in the same behavior as <code>wrap</code>, except that the user agent will use a slower algorithm that favors better layout over speed. This is intended for body copy where good typography is favored over performance (for example, when the number of <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/orphans">orphans</a> should be kept to a minimum).</p></dd><dt id="stable"><a href="#stable"><code>stable</code></a></dt><dd><p>Results in the same behavior as <code>wrap</code>, except that when the user is editing the content, the lines that come before the lines they are editing remain static rather than the whole block of text re-wrapping.</p></dd></dl></blockquote><q cite="https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap-style#values">same behavior as <code>wrap</code></q> doesn't make sense because <code>text-wrap-style:wrap;</code> is invalid</li></ul>

### What did you expect to see?

I don't know.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap-style#values

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/text-wrap-style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap-style
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/text-wrap-style/index.md
* Last commit: https://github.com/mdn/content/commit/69f98c69898886886f3267a4fa5f450f32133ca1
* Document last modified: 2024-03-23T00:11:39.000Z

</details>

**Comment by Josh-Cena** [comment]
Pinging @dletorey since this is new content

**Comment by dletorey** [comment]
@xBZZZZ thank you for bringing this up.

Here is the associated [Pull Request](https://github.com/mdn/content/pull/34036)
