### ISSUE TITLE
The text does not get updated with the code

### ISSUE THREAD

**Issue by txikilopez** [mdn/content#33540]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math

### What specific section or headline is this issue about?

Active learning: sizing a canvas box

### What information was incorrect, unhelpful, or incomplete?

When changing values of X and Y in the code, I was expecting the string below the canvas to update to the new X and Y values. But they always show: "The rectangle is 50px wide and 50px high."

### What did you expect to see?

I was expecting for it to update when the values were changed in each exercise

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/math`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/math/index.md
* Last commit: https://github.com/mdn/content/commit/151cdeeba58ffc07f8673af4e303cb1fcbba1bff
* Document last modified: 2024-04-29T15:59:22.000Z

</details>

**Comment by Josh-Cena** [comment]
The code to edit is in https://github.com/mdn/learning-area/blob/main/javascript/introduction-to-js-1/maths/editable_canvas.html
