### ISSUE TITLE
Wrong attr of HTML `body` tag

### ISSUE THREAD

**Issue by xyy94813** [mdn/content#33559]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body

### What specific section or headline is this issue about?

Attributes.onundo and Attributes.onredo

### What information was incorrect, unhelpful, or incomplete?

Don't see any info about `onundo` and `onredo` attr in HTML Spec.

Is the two attrs exist??

### What did you expect to see?

If attrs do not exist, remove it.
if attrs is experimental or deprecated, mark it.
Sync all translated content.

### Do you have any supporting links, references, or citations?

- https://html.spec.whatwg.org/multipage/sections.html#the-body-element
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLBodyElement
- https://www.webkitx.com/doc/light/WebKitXCEF3Lib~WebKitXCEF3~OnRedo_EV.html
- https://www.webkitx.com/doc/light/WebKitXCEF3Lib~WebKitXCEF3~OnUndo_EV.html

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/body`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/body/index.md
* Last commit: https://github.com/mdn/content/commit/829db137a01feb14af7beaec178a3ea0118b4777
* Document last modified: 2024-03-25T18:37:02.000Z

</details>

**Comment by estelle** [comment]
removed in #33930
