### ISSUE TITLE
[Web API] Enable `dom.events.asyncClipboard.clipboardItem` by default

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33565]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

[Bug 1887845](https://bugzilla.mozilla.org/show_bug.cgi?id=1887845): Enabled `dom.events.asyncClipboard.clipboardItem` by default

## Features to document

- It was enabled on Nightly in Firefox 122 (see [doc issue](https://github.com/mdn/content/issues/31104)).
- "Intent to ship"
  - Summary:  Enable clipboard.read()/write() by default on all channels
  - Standard: https://w3c.github.io/clipboard-apis

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Status

- [ ] BCD
  - [ ] https://github.com/mdn/browser-compat-data/pull/23075
  - [ ] ?
- [ ] Docs
- [ ] Release note
- [ ] Experimental features
- [ ] dev-docs-complete

**Comment by bsmth** [comment]
All looks done here, so closing as completed now! Thank you!
