### ISSUE TITLE
[JS] Ship new set methods

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33563]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [ ] Add/remove entry to Firefox experimental features page for preference/released features

## Features to document

Spec: https://github.com/tc39/proposal-set-methods

## Related Gecko bugs

[Bug 1868423](https://bugzilla.mozilla.org/show_bug.cgi?id=1868423): Ship new set methods proposal

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
@Josh-Cena G'day - this something you've already done work on/plan to do? There's also #33561 for FF127

**Comment by Josh-Cena** [comment]
There are already docs; you can handle the release notes and BCD parts 😄

**Comment by hamishwillee** [comment]
This ships the following [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) methods:

- [`Set.prototype.intersection()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/intersection) — Returns a new set containing elements in both this set and the given set.
- [`Set.prototype.union()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/union) — Returns new set containing all elements in this set and the given set.
- [`Set.prototype.difference()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/difference) — Returns a new set containing elements in this set but not in the given set.
- [`Set.prototype.symmetricDifference()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/symmetricDifference) — Returns new set containing elements that are in either this set or the given set, but not in both.
- [`Set.prototype.isSubsetOf()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/isSubsetOf) — Returns a boolean indicating if all elements of this set are in the given set.
- [`Set.prototype.isSupersetOf()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/isSupersetOf) — Returns a boolean indicating if all elements of the given set are in this set.
- [`Set.prototype.isDisjointFrom()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/isDisjointFrom) — Returns a boolean indicating if this set has no elements in common with the given set.

Status:

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/23089
- [ ] Docs - NA - look good.
- [ ] release note
- [ ] dev-docs-complete
