### ISSUE TITLE
Issue with "IDBRequest": please describe onupgradeneeded event

### ISSUE THREAD

**Issue by rootflood** [mdn/content#3356]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBRequest

please describe onupgradeneeded event because that exist on https://developer.mozilla.org/en-US/docs/Web/API/IDBOpenDBRequest

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Update the IDBOpenDBRequest page to explain it is inherited from the IDBRequest interface

NB the `onupgradeneeded` event is not available using the IDBRequest interface - only IDBOpenDBRequest

**Comment by Whitrooke** [comment]
I'd like to give this a shot!

**Comment by Rumyra** [comment]
Great @Whitrooke 🙌 Feel free to assign yourself and ask any questions you may have here 👍

**Comment by Whitrooke** [comment]
This may be a somewhat silly question, but what steps are necessary to be able to assign myself to this issue? Apologies for my naivity

**Comment by teoli2003** [comment]
You can't yourself. Only Collaborator+ can assign somebody. Done now.

**Comment by Rumyra** [comment]
Thanks @teoli2003 👍

**Comment by teoli2003** [comment]
@whitrooke did all the work here!

Closing this now.
