### ISSUE TITLE
[JS] Implement Float16Array

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33561]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

[Bug 1833647](https://bugzilla.mozilla.org/show_bug.cgi?id=1833647): Implement Float16Array

## Features to document

From "Intent to prototype"
- Summary: Float16Array is a new typed array analogous to existing typed arrays like Float32Array. Float16 is widely used for GPU computation in applications where speed and memory use are more important than precision; having Float16Array in JavaScript will facilitate passing data to the GPU.
- Specification: https://github.com/tc39/proposal-float16array
- Preference: `javascript.options.experimental.float16array`

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by Josh-Cena** [comment]
I'll handle the docs part

**Comment by hamishwillee** [comment]
Thanks @Josh-Cena - when you're done cross link here please.

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD
- [ ] Docs #33652
- [ ] Experimental features
- [ ] dev-docs-complete

**Comment by hamishwillee** [comment]
@Josh-Cena Have you got a timeline/PR for the interactive examples part of this?

**Comment by Josh-Cena** [comment]
I'm sorry, traveling for the past weeks. I will send a PR for the interactive example soon (this week). We would at least need BCD to be merged too though.

**Comment by hamishwillee** [comment]
Thanks. BCD merged yesterday.
