### ISSUE TITLE
IMPORTANT description and example missing

### ISSUE THREAD

**Issue by riverleaf** [mdn/content#33573]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

incomplete but required
`<base href="https://www.example.com/" />`
`<base target="_blank" />`
`<base target="_top" href="https://example.com/" />`

### What did you expect to see?

new heading
Off-page and In-page anchors

new content
`<base>` would require related(?) developments in [HTML6](https://makb183.com/html6-everything-you-need-to-know-about-the-future-of-html/#html-6-release-date-when-can-we-expect-it). Through technological expansion, `<base>` tags may help site visitors to contextually organize browser in-tab and off-tab browsing. We require 2 universal user controls to enable user contextual selection for exactly 2 on-off toggles in all browsers. Toggle 1 concurrently cycles in-tab/off-tab browsing to content within the currently active page. Toggle 2 concurrently cycles in-tab/off-tab browsing to content on any other active Internet page. HTML `<base>` arguments would continue to over-ride the new in-tab/off-tab browser user control toggles, protecting existing technologies and security conventions.  
https://www.w3schools.com/tags/att_base_target.asp
https://www.w3schools.com/tags/att_target.asp
[Security use case - Linkedin](https://www.linkedin.com/pulse/html-base-tag-amal-karunakaran#:~:text=Security%20%2D%20use%20case,improving%20security%20in%20some%20cases.)
Regardless...

new heading
`<base>` argument syntax hierarchy FURTHER development required

description missing
It is important that `<base href[="https"] target="_blank">` be followed by `<base target="_self">`. These two `base` values on the same page regulate off-tab and in-tab navigation. Those links with the `https` target will open html page addressess in new tabs. While links with the `#` target will open bookmarks  on the same base targets [plural] page in the same browser tab. Each base target argument must be placed in a separate `<base>` element tag. E.g. ,

example missing
`<base href[="https"] target="_blank">`
`<base target="_self">``

### Do you have any supporting links, references, or citations?

_No-Response_

### Do you have anything more you want to share?

2024 May 12, Safari 17.4.1 requires that both `<base>` targets must be placed in the following order.  First, `base href[="https"] target="_blank"` followed by the `base target="_self"`. So that the browser can access described html document external `_blank` and interna `_self`l link behaviors. Thus deploying the herein described ease-of-use Base URL element metadata accessibility efficiencies.

<img width="942" alt="Screen Shot 2024-05-12 at 19 44 55" src="https://github.com/mdn/content/assets/6208716/8e3d6dcd-89d4-42df-a951-87dc93dd8258">
(Safari default settings)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/base`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/base/index.md
* Last commit: https://github.com/mdn/content/commit/0af6781c93ffe3d011a060b4e517187cf780e93a
* Document last modified: 2024-03-14T00:21:52.000Z

</details>

**Comment by riverleaf** [comment]
It is noted that this html base element development is occurring during several months of globally disruptive cyber attack against all Region 3 online activity. Such that national governments are pushing a public WARNING to all citizens. The warning broadcasts are that all citizens must engage all online activity with special caution.

**Comment by riverleaf** [comment]
QUESTION !! What 2 terms license or distinguish <base  href target> vs. <base target> ?
Are "href" and "simple" good terms ?
Regardless,, how many  kinds of <base> exist ? 
Can MDN objectively classify <base> element types ? "There are 'n' kinds of....

**Comment by bsmth** [comment]
I'm closing as wontfix as the current documentation matches the referenced spec.
