### ISSUE TITLE
content Error

### ISSUE THREAD

**Issue by MohammedAmer1993** [mdn/content#33588]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

### What specific section or headline is this issue about?

What cookies are used for

### What information was incorrect, unhelpful, or incomplete?

4. The **browser** checks the session ID and, if it is still valid, sends the user a personalized version of the new page. If it is not valid, the session ID is deleted and the user is shown a generic version of the page (or perhaps shown an "access denied" message and asked to sign in again).

### What did you expect to see?

I think it should be the server instead of the browser like 
"
4. The **server** checks the session ID and, if it is still valid, sends the user a personalized version of the new page. If it is not valid, the session ID is deleted and the user is shown a generic version of the page (or perhaps shown an "access denied" message and asked to sign in again).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/cookies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cookies/index.md
* Last commit: https://github.com/mdn/content/commit/79d97ef1e24ab610a0691931826f027e162409b1
* Document last modified: 2024-05-07T07:58:05.000Z

</details>

**Comment by BrianJDrake** [comment]
Resolved by #33546.

**Comment by wbamberg** [comment]
> Resolved by #33546.

👍
