### ISSUE TITLE
[CSS] Support alt text in the `content` property

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#33590]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [ ] Add/remove entry to Firefox experimental features page for preference/released features

## Features to document

Updates might likely include:
- https://developer.mozilla.org/en-US/docs/Web/CSS/content#browser_compatibility
- Review of https://developer.mozilla.org/en-US/docs/Web/CSS/content#adding_an_image_with_alternative_text to check if any improvements are needed
- Release note

## Related Gecko bugs

[Bug 1281158](https://bugzilla.mozilla.org/show_bug.cgi?id=1281158): Implement alternative text for 'content' property

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by dletorey** [comment]
It's looking like this is going to be [released in Firefox 128](https://bugzilla.mozilla.org/show_bug.cgi?id=1281158#c31)

**Comment by dletorey** [comment]
### Related issues and pull requests

- [Content PR](https://github.com/mdn/content/pull/33834)
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/23199)
- [Firefox Release Note PR](https://github.com/mdn/content/pull/33835)

**Comment by dipikabh** [comment]
Closing this as all related tasks seem to be completed. Thanks, Dave!
