### ISSUE TITLE
Limitations of `path()` basic shape

### ISSUE THREAD

**Issue by estelle** [mdn/content#33593]
> The required `<string>` is a single [SVG Path](/en-US/docs/Web/SVG/Attribute/d) string encompassed in quotes with numeric values representing pixel units.

The path page should include the above and following information:

> While the `path()` function allows reuse of the SVG path syntax to define more arbitrary shapes than allowed by more specialized shape functions, it requires writing a path as a single string (which is not compatible with, for example, building a path piecemeal with `var()` and inherits a number of limitations from SVG, such as implicitly only allowing the `px` unit.

_Originally posted by @estelle in https://github.com/mdn/content/pull/33446#discussion_r1599064232_

**Comment by dipikabh** [comment]
`path()` is not supported in the `shape-outside` property:
- https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/path#browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside#browser_compatibility

This needs to be explicitly mentioned in both `path()` and `shape-outside` pages.

The following updates are especially needed on the `shape-outside` page:
- Remove use of `path()` in `shape-outside` from the [Syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside#syntax) examples.
- Update description of `<basic-shape>` in [Values](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside#values), which says `path()` is supported in spec level 2:

  > The float area is computed based on the shape created by of one of [inset()](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/inset), [circle()](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/circle), [ellipse()](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/ellipse), [polygon()](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/polygon) or, as added in the level 2 specification, path().

   There's no mention of it in https://drafts.csswg.org/css-shapes-2/#shape-outside-property.
