### ISSUE TITLE
No WebExtensions subsidebar for devtools.{inspectedWindow,devtools.network,panel}

### ISSUE THREAD

**Issue by ariasuni** [mdn/content#336]
When going to [`devtools.inspectedWindow`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.inspectedWindow), [`devtools.network`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.network) or [`devtools.panels` page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels), the methods, properties and events of the namespace aren’t show in the WebExtensions sidebar like it is for other namespaces (such as [`bookmarks`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks)).

**Comment by chrisdavidmills** [comment]
That particular bit of the sidebar is generated by the following macro code:

https://github.com/mdn/yari/blob/master/kumascript/macros/WebExtAPISidebar.ejs

If you look at these lines: https://github.com/mdn/yari/blob/master/kumascript/macros/WebExtAPISidebar.ejs#L120

It looks like the subpages are being added based on whether they have specific tags.

But if you look at a handful of those pages' source code, e.g.

* https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/devtools.panels/elementspanel/index.html
* https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/devtools.panels/elements/index.html
* https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/devtools.panels/create/index.html
* https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/devtools.panels/onthemechanged/index.html

You'll see that they don't have those tags included in the metdata/frontmatter.

Do you fancy adding the tags to those pages (on at least one tree) to see if that fixes the problem?
