### ISSUE TITLE
Define a `packageManager` field in `package.json`

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#33630]
If the local project is running using `yarn` set up by `corepack`, when running the project, the  terminal will report an warning:

![image](https://github.com/mdn/content/assets/95597335/3ceaf821-ac76-4a61-a712-3ced4fe38886)

and will automatically add a `packageManager` field in `package.json`:

![image](https://github.com/mdn/content/assets/95597335/3b838818-5fd6-47c3-8737-16ff070c4dce)

This is not good, as the automatically generated one has a hash which is not required. Contrbutors may also include the auto-made change in PR unexpectly

Add a `packageManager` field in `package.json`, like:

```json
{
  // ...
  "packageManager": "yarn@1.22.19",
  // ...
}
```

Also do the same at mdn/translate-content and other repos

see the official documentation for `packageManager` field: https://nodejs.org/api/packages.html#packagemanager

**Comment by Josh-Cena** [comment]
cc @OnkarRuikar I think we should do this

**Comment by OnkarRuikar** [comment]
I've created [a PR](https://github.com/mdn/content/issues/33630) to add the field.

Point to note is Corepack is still experimental and [dependabot doesn't support it](https://github.com/dependabot/dependabot-core/issues/4830). Considering yarn [slow release frequency](https://github.com/yarnpkg/yarn/releases) this doesn't affect anything.
