### ISSUE TITLE
minimalDays could use more explanation

### ISSUE THREAD

**Issue by jamiebuilds** [mdn/content#33645]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getWeekInfo

### What information was incorrect, unhelpful, or incomplete?

The description as is left me confused if I should care about this information or not. It would be useful to explain what it's for.

### What did you expect to see?

Something like:

> For calculating a date's week date (ex. The 20th week of the year) which start on `firstDay`. In some locales the first week date can be as little as one day long, in others it may require four days to be considered the first week, leaving the first few days as part of the last week of the previous year.

### Do you have any supporting links, references, or citations?

- https://en.wikipedia.org/wiki/ISO_week_date
- https://en.wikipedia.org/wiki/Leap_week_calendar

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/locale/getweekinfo`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getWeekInfo
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/locale/getweekinfo/index.md
* Last commit: https://github.com/mdn/content/commit/fb85334ffa4a2c88d209b1074909bee0e0abd57a
* Document last modified: 2023-09-25T07:33:31.000Z

</details>

**Comment by minimalsm** [comment]
Yeah definitely not very clear. 

How about adding additional information below the properties:

The `minimalDays` property determines how many days must be in the first week of a month or year for it to be considered a full week. In some locales, the first week can be as short as one day, while in others, it may need at least four days to be considered the first week. This can result in the first few days of January being part of the last week of the previous year.
