### ISSUE TITLE
Issue with "Coordinate systems": z-index is reversed

### ISSUE THREAD

**Issue by builder60** [mdn/content#3367]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSSOM_View/Coordinate_systems

The explanation for z-index says "This specifies the distance away from the viewer if positive and toward the viewer if negative." which is reversed. An element with a larger z-index will "hide" or appear closer (smaller distance) to the viewer than an element with a smaller  z-index.

#### Specific section or headline?
The third paragraph in the "Dimensions" section, last sentence.

#### What did you expect to see?
The opposite explanation for z-index.

#### Did you test this? If so, how?
I recently build an application where elements had to appear "over" each other.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/cssom_view/coordinate_systems`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSSOM_View/Coordinate_systems
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/cssom_view/coordinate_systems/index.html
* Last commit: https://github.com/mdn/content/commit/85a8e65d648b60fb244f2ca8c0fc519ea9b55626
* Document last modified: 2021-01-19T06:15:11.000Z

</details>

**Comment by sideshowbarker** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSSOM_View/Coordinate_systems doesn’t mention anything about z-index; instead the *“This specifies the distance away from the viewer if positive and toward the viewer if negative”* is about the *z-coordinate*; that is, the general concept of the *z-coordinate*, which is something related to, but different than, “z-index” — which in the web platform, has a more-specific, well-defined meaning.

Anyway, from my limited knowledge of 3-D graphics APIs, I think the following statement isn’t actually wrong:

> When drawing 3D graphics, or using a third dimension to layer objects from front to back, the z-coordinate is also used. This specifies the distance away from the viewer if positive and toward the viewer if negative.

At least for OpenGL — which is perhaps the most widely-used 3D graphics API — I think that does actually describe the default. But in practice, you can basically just flip the direction of the z axes when you write code. And so it’s somewhat pointless to explicitly state which was is positive and which is negative.

So I agree a change should be made here, but I think that statement should be rewritten to remove altogether any mention of which direction is positive/negative for the z-coordinate; for example, something like this:

> When drawing 3D graphics, or using a third dimension to layer objects from front to back, the z-coordinate is also used. The z-coordinate is measured along the axes that runs into the screen and away from the viewer, and out from the screen and toward the viewer.

…but really I think that, ideally, somebody with some strong domain knowledge about 3D graphics should review this and sign off on some wording for a change.

**Comment by builder60** [comment]
I could agree with what you said about Z coordinates in a 3D system, but
this page is trying to explain coordinates as they apply to CSS. So,
*somewhere* on the page there should be an explanation of how z-index
relates to these coordinate systems. A brief explanation of using z-index
to emulate 3D in a 2D display would also fit nicely on this page.

Jon

**Comment by stacker60** [comment]
Adding on to @sideshowbarker's comment above, maybe something along the lines of this:

> When drawing 3D graphics, or using a third dimension to layer objects from front to back, the z-coordinate is also used. The z-coordinate is measured along the axes that runs into the screen and away from the viewer, and out from the screen and toward the viewer. Within CSS, the z-index attribute can be used to control which objects appear to be more toward the viewer.  See [Introducing z-index](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning#introducing_z-index) for more information.
