### ISSUE TITLE
About global scope and script scope

### ISSUE THREAD

**Issue by Arman19941113** [mdn/content#33677]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Scope

### What information was incorrect, unhelpful, or incomplete?

<img width="735" alt="image" src="https://github.com/mdn/content/assets/35905177/6ea2116d-a792-4078-8db6-a037cc3df39c">

### What did you expect to see?

I think there might be a script scope?

```html
<body>
  <script>
    const x = 1

    function a () {
      debugger
      console.log(x)
    }
    a()
  </script>
</body>
```

<img width="558" alt="image" src="https://github.com/mdn/content/assets/35905177/c019078c-4bfe-45de-ba2e-bfed64f41f8d">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/scope`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Scope
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/scope/index.md
* Last commit: https://github.com/mdn/content/commit/ada5fa5ef15eadd44b549ecf906423b4a2092f34
* Document last modified: 2023-06-08T13:19:16.000Z

</details>

**Comment by minimalsm** [comment]
Hey @Arman19941113, I understand the confusion here!

The "Script" scope you see in the debugger is a way to show variables declared at the top level of the script (provided by the browser's JavaScript engine). These are actually part of the global scope but are shown separately to help distinguish them from other truly global variables (e.g., those on the window object). Hope that helps!

**Comment by Josh-Cena** [comment]
@minimalsm is pretty correct. The "global scope" contains variables in the global scope that are also on the global object. The "script scope" contains lexically declared variables in the global scope. The difference to you as a developer is pretty minimal.
