### ISSUE TITLE
Manifest#orientation: should link to screen orientation API landing page

### ISSUE THREAD

**Issue by benjamingwynn** [mdn/content#33670]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Manifest/orientation

### What specific section or headline is this issue about?

Note under orientation

### What information was incorrect, unhelpful, or incomplete?

> Note: The orientation can be changed at runtime via the [Screen Orientation API](https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation).

### What did you expect to see?

> Note: The orientation can be read at runtime via the [Screen Orientation API](https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation)

### Do you have any supporting links, references, or citations?

According to https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation

> The orientation **read-only** property of the [Screen](https://developer.mozilla.org/en-US/docs/Web/API/Screen) interface returns the current orientation of the screen.

Read-only being the important part, the note from Manifest/orientation above says it can be changed.

### Do you have anything more you want to share?

Thank you for all the hard work maintaining MDN! 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/manifest/orientation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/orientation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/manifest/orientation/index.md
* Last commit: https://github.com/mdn/content/commit/0c015b80f786ecc4547c3e37a70c7f6aafdfbf74
* Document last modified: 2023-06-28T16:16:20.000Z

</details>

**Comment by Josh-Cena** [comment]
`screen.orientation` being read-only doesn't mean you can't change it. Please see https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock. I think we should link to the API landing page instead of the property here.
