### ISSUE TITLE
Issue with "Django Tutorial Part 2: Creating a skeleton websit…": (short summary here please)

### ISSUE THREAD

**Issue by McRoche764** [mdn/content#3368]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website

#### What information was incorrect, unhelpful, or incomplete?
There's an exceptions at run time in the local server settings 
line 81, in (module) 
    'name': os.path.join(BASE_DIR, 'db.sqlite3'),
the command returned 'NameError: name 'os' is not defined
#### Specific section or headline?

Running the website
#### Did you test this? If so, how?

No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/skeleton_website`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/skeleton_website/index.html
* Last commit: https://github.com/mdn/content/commit/fc36604b19a172f3fbedb2629e2403180f2eda55
* Document last modified: 2021-03-19T23:16:59.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. The use of OS in the import should not be there. From a coding point of view it is fine (if you import OS) but the django framework doesn't do it that way. This is fixed as part of https://github.com/mdn/content/pull/2919
