### ISSUE TITLE
Typos in text for method getHourCycles(), most likely due to copy/paste

### ISSUE THREAD

**Issue by jackdeguest** [mdn/content#33689]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getHourCycles

### What specific section or headline is this issue about?

The Example section

### What information was incorrect, unhelpful, or incomplete?

There is a sentence that states (emphasis added):

> If the Locale object doesn't have a hourCycle already, getHourCycles() lists all commonly-used **collation types** for the given Locale.

### What did you expect to see?

This should instead be:

> If the Locale object doesn't have a hourCycle already, getHourCycles() lists all commonly-used hour cycle identifiers for the given Locale.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/locale/gethourcycles`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getHourCycles
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/locale/gethourcycles/index.md
* Last commit: https://github.com/mdn/content/commit/27180875516cc311342e74b596bfb589b7211e0c
* Document last modified: 2023-08-24T22:55:36.000Z

</details>

**Comment by Josh-Cena** [comment]
Good catch 👍
