### ISSUE TITLE
PaintSize and PaintRenderingContext2D undocumented

### ISSUE THREAD

**Issue by camelCaseEnjoyer** [mdn/content#33681]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSS_Painting_API

### What specific section or headline is this issue about?

Sidebar link to the interface PaintSizes

### What information was incorrect, unhelpful, or incomplete?

PaintSize links to https://developer.mozilla.org/en-US/docs/Web/API/PaintSize , which brings up a Page Not Found error. 

### What did you expect to see?

The description of the PaintSize interface if it exists, or no entry on the sidebar if it does not exist.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/css_painting_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS_Painting_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/css_painting_api/index.md
* Last commit: https://github.com/mdn/content/commit/3b39e41fb9393a13b16aaf58ba25174a62205041
* Document last modified: 2024-01-17T12:49:19.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! I'm closing all issues that are in https://openwebdocs.github.io/web-docs-backlog/all/. These features are automatically in our backlog and don't need separate issues to track.
