### ISSUE TITLE
Need example of details with name attribute

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [mdn/content#33693]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

### What specific section or headline is this issue about?

Missing example

### What information was incorrect, unhelpful, or incomplete?

"Details" describes the attribute "name", but I'm missing a example

### What did you expect to see?

Please add an example for attribute "name"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/details`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/details/index.md
* Last commit: https://github.com/mdn/content/commit/983529c264f474e6e6680bd9de7bdf32ff52ec96
* Document last modified: 2024-03-20T12:35:44.000Z

</details>

**Comment by estelle** [comment]
fixed in https://github.com/mdn/content/pull/33926
