### ISSUE TITLE
Mixed content article should switch from the notion of active/passive content to blocked/upgradable content

### ISSUE THREAD

**Issue by mozfreddyb** [mdn/content#33696]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

### What specific section or headline is this issue about?

This is about the whole article

### What information was incorrect, unhelpful, or incomplete?

The Mixed Content spec has migrated away from the terminology "active" and "passive" content.

### What did you expect to see?

 There is only blocked and upgradable content now.
With https://www.w3.org/TR/mixed-content/, the difference is that everything is considered "blocked" except img, audio and video elements - which are considered upgradable.

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/mixed-content/

### Do you have anything more you want to share?

Firefox is making this switch in 127 which ships on June 11th. I am working on an accompanying blog post, that I am willing to share with MDN content authors. Ping me via email (fbraun-at-mozilla.com) or Mozilla slack.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/security/mixed_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/security/mixed_content/index.md
* Last commit: https://github.com/mdn/content/commit/e83ffbefa9c37bed243a4fda930e75f1be91a3b4
* Document last modified: 2023-12-20T07:21:28.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @mozfreddyb  - this should be looked at as part of https://github.com/mdn/content/issues/33592 - no one is assigned to that yet

**Comment by mozfreddyb** [comment]
> Chrome shipped this in 2020, I believe. [WebKit has a positive standards position](https://github.com/WebKit/standards-positions/issues/124) and an implementation behind a flag, but did not ship yet. I am expecting them to follow soon.

FWIW, this will be shipped in Safari 18. https://webkit.org/blog/15443/news-from-wwdc24-webkit-in-safari-18-beta/
