### ISSUE TITLE
Incorrect validation description

### ISSUE THREAD

**Issue by rbquantori** [mdn/content#33695]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

### What specific section or headline is this issue about?

validation

### What information was incorrect, unhelpful, or incomplete?

It is said that

> Radio buttons don't participate in constraint validation; they have no real value to be constrained.

### What did you expect to see?

However, they do participate in at least `required` validation, here's screenshot from FireFox, but all other major browsers also implement this: 
<img width="280" alt="image" src="https://github.com/mdn/content/assets/101616878/e20eead1-d820-4d28-be60-7d8117e2ffc7">

### Do you have anything more you want to share?

here's the code used to make the screenshot:
```html
      <input type="radio" required name="foo" value="bar" id="bar" /><label for="bar">bar</label>
      <input type="radio" required name="foo" value="kar" id="kar" /><label for="kar">kar</label>
      <input type="radio" required name="foo" value="jar" id="jar" /><label for="jar">jar</label>
      <input type="radio" required name="foo" value="dar" id="dar" /><label for="dar">dar</label><br />
```
So the name is the same and one or more radio buttons have `required` attribute.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/radio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/radio/index.md
* Last commit: https://github.com/mdn/content/commit/72ca3d725e3e56b613de3ac9727bd0d6d619c38a
* Document last modified: 2024-01-08T13:33:20.000Z

</details>

**Comment by estelle** [comment]
Changed to:

> While radio buttons have no real value to be constrained, if any radio button in a same-name group of radio buttons has the `required` attribute set, and none of the radio buttons is checked, the [`valueMissing`](/en-US/docs/Web/API/ValidityState/valueMissing) property of a {{domxref("ValidityState")}} object will return true during validation.
