### ISSUE TITLE
Going to `devtools.panels.ExtensionSidebarPane.setPage()` page doesn’t show WebExtensions sidebar

### ISSUE THREAD

**Issue by ariasuni** [mdn/content#337]
Going to [`devtools.panels.ExtensionSidebarPane.setPage() page`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels/ExtensionSidebarPane/setPage) doesn’t show WebExtensions sidebar like other items from the WebExtensions API.

**Comment by chrisdavidmills** [comment]
I had a look, and the sidebar macro was missing. Thanks for reporting this. I've fixed it now with https://github.com/mdn/content/commit/b08487155fc8112f2482b03c7b2160f92e424971
