### ISSUE TITLE
A non-interactive code example

### ISSUE THREAD

**Issue by lkintact** [mdn/content#33705]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flow_layout/Block_and_inline_layout_in_normal_flow

### What specific section or headline is this issue about?

Elements participating in an inline formatting context

### What information was incorrect, unhelpful, or incomplete?

The first code example in the `Elements participating in an inline formatting context` section is not interactive, i.e. changing the code doesn't change the result displayed above. The `Reset` button doesn't work either.

### What did you expect to see?

.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_flow_layout/block_and_inline_layout_in_normal_flow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flow_layout/Block_and_inline_layout_in_normal_flow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_flow_layout/block_and_inline_layout_in_normal_flow/index.md
* Last commit: https://github.com/mdn/content/commit/6eaa592b20fb3a93d97517b90a5e2d99a32af5a7
* Document last modified: 2024-01-08T20:02:57.000Z

</details>

**Comment by pepelsbey** [comment]
Nice catch! Thank you :) It was fixed in mdn/css-examples#182
