### ISSUE TITLE
Perhaps a typo

### ISSUE THREAD

**Issue by lkintact** [mdn/content#33706]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Visual_formatting_model

### What specific section or headline is this issue about?

Block boxes

### What information was incorrect, unhelpful, or incomplete?

There seems to be a typo in this part:
"As described in CSS display, it is possible for a box to be a block-level box _**, but not**_ also a block container"

The correct variant is probably this:
"As described in CSS display, it is possible for a box to be a block-level box **_and_** also a block container".

Otherwise that contradicts the previous sentence:
"A block box is a block-level box that is also a block container".

### What did you expect to see?

.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/visual_formatting_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Visual_formatting_model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/visual_formatting_model/index.md
* Last commit: https://github.com/mdn/content/commit/afaf3aeeffa8408cf0a8a46c3d8fb0d347aad9f5
* Document last modified: 2024-01-30T05:28:18.000Z

</details>

**Comment by Josh-Cena** [comment]
A block box is a block-level box that is also a block container. But a block-level box is not always a block container. As already said in parentheses, it might be flex or grid container.
