### ISSUE TITLE
Part of the example provided is factually incorrect

### ISSUE THREAD

**Issue by jackdeguest** [mdn/content#33719]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getWeekInfo

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

The last example provided is factually incorrect. It currently states:

```
const msBN = new Intl.Locale("ms-BN");
console.log(msBN.getWeekInfo()); // { firstDay: 7, weekend: [5, 7], minimalDays: 1 }
// Brunei weekend is Friday and Sunday but not Saturday
```

Running this in a web browser that supports `getWeekInfo()`, such as Safari, produces:

```
{firstDay: 1, weekend: [6, 7], minimalDays: 1}
```

Thus, the value for property `firstDay` is `1` and not `7` and the array value for `weekend` property is `[6,7]` and not `[5,7]`

The Unicode CLDR (Common Locale Data Repository) also confirms this.

For the value of `firstDay` property, see the [XML file supplementalData.xml at line 4676](https://github.com/unicode-org/cldr/blob/2dd06669d833823e26872f249aa304bc9d9d2a90/common/supplemental/supplementalData.xml#L4676) or, alternatively, the [weekData.json at line 81](https://github.com/unicode-org/cldr-json/blob/0876ec40e13d54c0a6b6456392802d4de7e059cb/cldr-json/cldr-core/supplemental/weekData.json#L81)

For the value of `weekend` property, see the [XML file supplementalData.xml at line 4723](https://github.com/unicode-org/cldr/blob/2dd06669d833823e26872f249aa304bc9d9d2a90/common/supplemental/supplementalData.xml#L4723) which does not contain the territory `BN`, or alternatively, the [JSON file weekData.json at line 212](https://github.com/unicode-org/cldr-json/blob/0876ec40e13d54c0a6b6456392802d4de7e059cb/cldr-json/cldr-core/supplemental/weekData.json#L212)

### What did you expect to see?

If you really want to pick an outlier, then pick the locale `ar-AF` whose weekend starts on Thursday and ends on Friday:

```
new Intl.Locale('ar-AF').getWeekInfo();
// {firstDay: 6, weekend: [4, 5], minimalDays: 1}
```

Otherwise, it is best to remove this last example, since it is almost identical (except for the value `minDays` as the locale `en-GB` mentionned just above it.

### Do you have any supporting links, references, or citations?

The Unicode Common Locale Data Repository itself with the links provided.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/locale/getweekinfo`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getWeekInfo
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/locale/getweekinfo/index.md
* Last commit: https://github.com/mdn/content/commit/fb85334ffa4a2c88d209b1074909bee0e0abd57a
* Document last modified: 2023-09-25T07:33:31.000Z

</details>

**Comment by Josh-Cena** [comment]
Thanks, please go ahead and make modifications as you see fit. I do think it would be interesting to see some non-canonical examples.
