### ISSUE TITLE
Incorrect reference to screen method

### ISSUE THREAD

**Issue by jpleasant** [mdn/content#33721]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Managing_screen_orientation

### What specific section or headline is this issue about?

Screen Orientation API

### What information was incorrect, unhelpful, or incomplete?

An example given in the api shows:

```js
screen.addEventListener("orientationchange", () => {
  console.log(`The orientation of the screen is: ${screen.orientation}`);
});
```

The correct version should be:

```js
screen.orientation.addEventListener("orientationchange", () => {
  console.log(`The orientation of the screen is: ${screen.orientation}`);
});
```

### What did you expect to see?

The method on the screen object refers to "addEventListener" this isn't directly on the object but on the orientation property object. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/css_object_model/managing_screen_orientation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Managing_screen_orientation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/css_object_model/managing_screen_orientation/index.md
* Last commit: https://github.com/mdn/content/commit/c51e0599ea09c0e6d035c635db9f48ad1f241490
* Document last modified: 2023-07-05T05:48:35.000Z

</details>

**Comment by jpleasant** [comment]
accidentally closed

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/33742 and then https://github.com/mdn/content/pull/34586
