### ISSUE TITLE
Using 点 as an example for text-emphasis-style feels weird exclamation mark

### ISSUE THREAD

**Issue by igorsantos07** [mdn/content#33723]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-style

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

点 is Chinese for "dot". Hence, using that character as a emphasis marker is literally writing "dot" above every symbol, instead of _placing a dot_ there. I exemplified this on the issue title; it's like ending a sentence with `exclamation mark` instead of the actual `!` symbol.

This what a native Chinese colleague of mine told me when I presented her the several examples, so she could select a marker for us to use when localizing our system into Chinese. Unless any Asian style guide shows multiple options, including 点 as a valid option for emphasis markers, I would strongly suggest removing it from the Syntax section. The `x` there is understandable not as a letter X, but as an X marker, but 点 would have only one meaning in that scenario - the "dot" word.

### What did you expect to see?

Several valid and really-used examples of markers.

### Do you have any supporting links, references, or citations?

The official [Chinese style guide](http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf) doesn't seem to give any example, but it does use small dots below words in some places (e.g. page 13, entry 4.12.3.1).

The [W3C](https://drafts.csswg.org/css-text-decor/#text-emphasis-style-property) won't specify any example characters, so it could be considered ambiguous. However, [Wikipedia doesn't list 点 as a usual option](https://en.wikipedia.org/wiki/Emphasis_mark), although it lists all the other circle/sesame versions as specified by CSS. Specifically on the [Chinese punctuation article](https://en.wikipedia.org/wiki/Chinese_punctuation#Typographic_styles) (where that char comes from), there's nothing but mentions of the dot; no 点. Emphasis markers are not mentioned in [Japanese](https://en.wikipedia.org/wiki/Japanese_punctuation) or [Korean](https://en.wikipedia.org/wiki/Korean_punctuation) punctuation articles.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/text-emphasis-style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-style
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/text-emphasis-style/index.md
* Last commit: https://github.com/mdn/content/commit/b82ff59aab7883b7bb2222cf9f9f9b6eed818e08
* Document last modified: 2023-02-21T06:13:19.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing!

Perhaps it would be OK just to remove this example.

**Comment by ronkorving** [comment]
I can confirm that in Japanese, the character's meaning is the same, and you wouldn't use it this way either.

**Comment by igorsantos07** [comment]
I'm not sure how opinionated MDN docs can be, but if you look around the web for other guides on how to use `text-emphasis`, the dot char is quite widespread. I wouldn't be surprised if this is because it's currently an example in MDN, the source many devs use for web tech knowledge.

Thus, it _could_ be helpful if there was a small explanation that, while previous versions used that char, that's really not used at all in actual languages. This could help clear up the confusion a bit.

Having examples with actual Asian languages would be beneficial as well, given those properties are not even intended to be used with western writing. But then I guess I'm digressing a bit and should open a new issue with this suggestion?

**Comment by Josh-Cena** [comment]
I can confirm that this is never used in Chinese. I have never seen anything other than dots and underline for emphasis in Chinese (italics are mostly for translated works and is really just a different font in Chinese). I think the original intention (assuming there was one) is to demonstrate astral characters as markers, but I don't know what will be more appropriate—maybe heart characters?

Btw I do wonder if emojis work here

**Comment by wbamberg** [comment]
Filed https://github.com/mdn/content/pull/33822 to do the simplest thing here, but open to suggestions of course.

**Comment by igorsantos07** [comment]
> Btw I do wonder if emojis work here
@Josh-Cena they do. I saw that in one of the articles that also copied the 点 usage. 
What would be astral characters? (sorry if I'm going too much off topic, but Google didn't help much)

**Comment by Josh-Cena** [comment]
Astral characters are non-BMP characters: https://www.quora.com/Why-are-unicode-characters-outside-the-BMP-called-astral

They are particularly hard to deal with in JS because their UTF-16 encoding takes more than 1 code unit and naïve index-based operations fail on them. However since CSS is UTF-8 based I don't think it's relevant. I was using the wrong term there; I meant multi-character grapheme clusters. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_points_and_grapheme_clusters

**Comment by wbamberg** [comment]
> multi-character grapheme clusters

[per-spec](https://drafts.csswg.org/css-text-decor/#valdef-text-emphasis-style-string), it should: 

> Display the given string as marks. Authors should not specify more than one [character](https://drafts.csswg.org/css-text-4/#character) in <string>. The UA may truncate or ignore strings consisting of more than one grapheme cluster.
