### ISSUE TITLE
To view Form data on Chrome Dev Tools no longer under Headers tab, but under the new Payload tab

### ISSUE THREAD

**Issue by onyedikachi23** [mdn/content#33729]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data

### What specific section or headline is this issue about?

On the client side: defining how to send the data

### What information was incorrect, unhelpful, or incomplete?

Under the section [Viewing HTTP requests](https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data#viewing_http_requests), the directions on how to view the form data on Chrome Dev Tools instructed that the Form data can be viewed unders the Headers tab.  

### What did you expect to see?

I'm using Chrome browser - _**Version 124.0.6367.210 (Official Build) (64-bit)**_ and the Form data isn't under the headers tab but under the new **Payload** tab:
<img width="455" alt="Chrome Dev Tools screenshot" src="https://github.com/mdn/content/assets/118916044/6ea12f52-ff60-4181-a524-ae601241b03d">

### Do you have any supporting links, references, or citations?

Update your chrome browser and try to view the form data as directed in the article.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/sending_and_retrieving_form_data`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/sending_and_retrieving_form_data/index.md
* Last commit: https://github.com/mdn/content/commit/9087a17d60546adb8806da3b7c575b6adb8aebd1
* Document last modified: 2024-03-15T12:24:46.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you. Would you like to submit a pull request with this changed?

**Comment by onyedikachi23** [comment]
Yes, I'd like to.
