### ISSUE TITLE
TypedArray subclass pages say contents are initialized to 0

### ISSUE THREAD

**Issue by rhashimoto** [mdn/content#33743]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array

### What specific section or headline is this issue about?

main heading

### What information was incorrect, unhelpful, or incomplete?

For each of [BigInt64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array), [BigUint64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array), [Float32Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array), etc. (all the TypedArray subclasses), the initial description contains:

> The contents are initialized to 0. [or 0n]

This initialization is only done if the TypedArray subclass is created by passing a length to the constructor. It is not done if the instance is created from an existing array or a buffer.

Try this in a console:

```javascript
const b0 = new Uint8Array([42]);
const b1 = new Uint8Array(b0.buffer);
console.log(b1[0]);  // <= prints 42, *not* 0
```

### What did you expect to see?

It should say something like:

> The contents are initialized to 0 [or 0n for BigInt64Array or BigUint64Array] if constructed with only a length.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/float32array`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/float32array/index.md
* Last commit: https://github.com/mdn/content/commit/e01fd6206ce2fad2fe09a485bb2d3ceda53a62de
* Document last modified: 2023-09-07T01:45:56.000Z

</details>

**Comment by Josh-Cena** [comment]
It should say "initialized to 0 unless an existing buffer is provided".

**Comment by rhashimoto** [comment]
> It should say "initialized to 0 unless an existing buffer is provided".

That isn't quite correct, either. For example:

```javascript
new Uint8Array([1, 2, 3]);
```

Here a buffer is not provided and the array is not initialized to 0.
