### ISSUE TITLE
Add a warning/suggestion to canvas.toDataURL to prefer toBlob

### ISSUE THREAD

**Issue by evilpie** [mdn/content#33748]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

### What information was incorrect, unhelpful, or incomplete?

toDataURL creates huge strings, which can be inefficient memory-wise. Due to the URL size limit in Firefox (and other browsers?) `toDataURL` can actually return strings that are too large to be parsed when assigned to e.g. `img.src`.

### What did you expect to see?

I think it would be useful to have an information box on the toDataURL page to suggest using toBlobURL in combination with URL.createObjectURL instead, i.e. [this example](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob#getting_a_file_representing_the_canvas).

### Do you have any supporting links, references, or citations?

https://bugzilla.mozilla.org/show_bug.cgi?id=1898679

**Comment by hamishwillee** [comment]
This is a good idea, but I'd be tempted by a warning box rather than just a note. 

@evilpie Is there an approximate image size in some meaningful unit (pixels?) at which we can tell people they really need to worry?

**Comment by gijsk** [comment]
> @evilpie Is there an approximate image size in some meaningful unit (pixels?) at which we can tell people they really need to worry? Or is it a matter that always recommending via toBlobUrl makes sense?

I'm not @evilpie but I'd suggest just always recommending `toBlobUrl`. `data` URIs, even at smaller sizes, mean that the browser has to keep a copy of the data as a string (as you can call `getAttribute` on the image where you assign to `src`, or read its `src` property), which duplicates the contents of the data. Even though a 1MB data URI "works" pretty well in browsers, it's a lot of data that the browser has to copy around in memory etc. `blob` URIs are always more efficient.

Of course `data` URIs have their place for e.g. 1x1 pixel things but as long as any warning isn't overbearing that seems fine to me.
