### ISSUE TITLE
your documentation

### ISSUE THREAD

**Issue by graememorris** [mdn/content#33758]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/--*

### What specific section or headline is this issue about?

css, custom properties (CSS variables)

### What information was incorrect, unhelpful, or incomplete?

not just this section - in general - your documentation is abstruse, bloated, saturated with pointless detail.

### What did you expect to see?

i wanted to know whether these variables need to be strings or integers or well-formed arrays/objects, whatever.
i find a long example with seventeen iterations of colour values and no definition of anything that might help - this means not only do i get an irrelevant crock i can't use, i have to read it all to make sure it really is that useless.

### Do you have any supporting links, references, or citations?

have a look at the site https://legacy.cplusplus.com/reference/
it contains dozens of small, clear, very readable, inevitably functional examples of important C and C++ functions.
users can cut and paste and modify them easily and without wasting time.
your examples - where they exist at all - seem to have been written as proof of how clever you all are.

### Do you have anything more you want to share?

it wouldn't be hard to write better documentation than you have - in many cases it would be hard to come up with WORSE.
i am sure lots of people would try to help with this endeavour, but how can they?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/--_star_`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/--*
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/--_star_/index.md
* Last commit: https://github.com/mdn/content/commit/1c4eb0bfb5f72a26fcc21a83fac91aa3e66c2fb8
* Document last modified: 2024-01-02T16:00:45.000Z

</details>

**Comment by hamishwillee** [comment]
Closing, because this issue report is not actionable.

Feel free to repost the specific issue you have a problem with, which I believe is:

> i wanted to know whether these variables need to be strings or integers or well-formed arrays/objects, whatever.
