### ISSUE TITLE
Incorrect analogy of promise chains resembling a stack in documentation

### ISSUE THREAD

**Issue by Maddily** [mdn/content#33788]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

### What specific section or headline is this issue about?

Chained Promises

### What information was incorrect, unhelpful, or incomplete?

The documentation on the MDN page [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#chained_promises) uses an analogy to describe the behavior of promise chains: "The promises of a chain are nested in one another, but get popped like the top of a stack. The first promise in the chain is most deeply nested and is the first to pop." This analogy is misleading because it inaccurately describes the order in which promises are resolved. A stack follows a Last In, First Out (LIFO) order, while promises in a chain are resolved in a First In, First Out (FIFO) order, more like a queue.

### What did you expect to see?

I expected to see a description that accurately reflects the sequential nature of promise chains. A correct explanation would clarify that promises in a chain are executed in the order they are created, with each promise waiting for the previous one to resolve.

## Suggested Revision:
The promises in a chain are executed in sequence, where each promise waits for the previous one to resolve before continuing. The first promise in the chain is the first to be resolved, and subsequent promises are resolved in the order they appear in the chain.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/index.md
* Last commit: https://github.com/mdn/content/commit/10b342385644e822d123694ad3bc8c2ca9abb2dc
* Document last modified: 2023-11-29T09:09:55.000Z

</details>

**Comment by Ashish-CodeJourney** [comment]
Raised a PR for the same
https://github.com/mdn/content/pull/33790

Please review, suggestions will be appriciated

**Comment by Maddily** [comment]
Thank you everyone for your work on this issue and for the improvements made to the documentation. The changes address the concerns I raised and provide a much clearer explanation. I appreciate the effort put into this.

I'm closing this issue now. Thanks again!
