### ISSUE TITLE
Anchor tech summary does not list permitted content types in a meaningful way

### ISSUE THREAD

**Issue by andrewnicols** [mdn/content#33814]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

### What specific section or headline is this issue about?

Technical summary

### What information was incorrect, unhelpful, or incomplete?

It lists Permitted content as "Transparent", but there is no mention of whether it accepts Flow content, Phrasing content, etc.
The link to [Transparent content model](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#transparent_content_model) is gibberish, contains a confusing example and statement ("If those elements were removed, this fragment would still be valid HTML (if not correct English)."), and does not list any types.

### What did you expect to see?

A statement that an anchor may not contain a block-level element such as a div, preferably by listing Permitted content as "phrasing content" or similar.

### Do you have any supporting links, references, or citations?

MDN _used_ to say this in October 2021:
https://web.archive.org/web/20211028103045/https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#properties

> [Transparent](https://web.archive.org/web/20211028103045mp_/https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#transparent_content_model), containing either [flow content](https://web.archive.org/web/20211028103045mp_/https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#flow_content) (excluding [interactive content](https://web.archive.org/web/20211028103045mp_/https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#interactive_content)) or [phrasing content](https://web.archive.org/web/20211028103045mp_/https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content).

This was removed before November 2021:
https://web.archive.org/web/20211105095924/https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#properties

> [Transparent](https://web.archive.org/web/20211105095924mp_/https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#transparent_content_model), except that no descendant may be [interactive content](https://web.archive.org/web/20211105095924mp_/https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#interactive_content) or an [a](https://web.archive.org/web/20211105095924mp_/https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) element, and no descendant may have a specified [tabindex](https://web.archive.org/web/20211105095924mp_/https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) attribute.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/a`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/a/index.md
* Last commit: https://github.com/mdn/content/commit/61d93eba51427ab94e66f8d904c27552f1abfde3
* Document last modified: 2024-04-15T08:05:13.000Z

</details>

**Comment by andrewnicols** [comment]
Change appears to be from https://github.com/mdn/content/pull/10247 and correct per the spec so I have also raised an [issue against the spec](https://github.com/whatwg/html/issues/10372) because the spec is either so convoluted as to be meaningless, or has banned the use of spans in an anchor which will break a _lot_ of content.

**Comment by andrewnicols** [comment]
Okay, it seems that the following is missing from MDN:

> The content model of a [transparent](https://html.spec.whatwg.org/multipage/dom.html#transparent) element is derived from the content model of its parent element: the elements required in the part of the content model that is "transparent" are the same elements as required in the part of the content model of the parent of the transparent element in which the transparent element finds itself.

Meanwhile the MDN definition does not mention the inheritted type at all, there is the entire content:

> If an element has a transparent content model, then its contents must be structured such that they would be valid HTML 5, even if the transparent element were removed and replaced by the child elements.

**Comment by estelle** [comment]
I think the `<a>` page is fine, and can remain unchanged.

My suggestion would be to provide better examples of transparent content on https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#transparent_content_model. For example, make the `<del>` delete an entire paragraph. (most don't know you can to `<del><p>text</p><p>more text</p></del>`

**Comment by andrewnicols** [comment]
I think that this is incomplete still, as I noted above, the MDN description of Transparent content is still missing any mention of the content model.

IN particular the spec states:

> the elements required in the part of the content model that is "transparent" are the same elements as required in the part of the content model of the parent of the transparent element in which the transparent element finds itself.

The current wording essentially has the same meaning, but is so confusing as to be meaningless:

> If an element has a transparent content model, then its contents must be structured such that they would be valid HTML, even if the transparent element were removed and replaced by the child elements.

I think this needs to be much simpler and clearer because _both_ of these are confusing as hell to read.

**Comment by estelle** [comment]
@andrewnicols Please file a PR with suggested edits.
