### ISSUE TITLE
Issue with "BluetoothRemoteGATTCharacteristic.writeValue()": Function not marked as deprecated

### ISSUE THREAD

**Issue by jeroen1602** [mdn/content#3382]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValue

#### What information was incorrect, unhelpful, or incomplete?

This method is deprecated in the spec, but it is not reflected on the site.
[Spec source](https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetoothremotegattcharacteristic-writevalue)
[Spec github issue](https://github.com/WebBluetoothCG/web-bluetooth/issues/238)

#### What did you expect to see?

A messages marking this method as deprecated and linking to the new `writeValueWithoutResponse` and `writeValueWithResponse`.

#### Did you test this? If so, how?

Not sure what there is to test.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/bluetoothremotegattcharacteristic/writevalue`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValue
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/bluetoothremotegattcharacteristic/writevalue/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. We’ll also need to update https://github.com/mdn/browser-compat-data for this, so I’ll make the changes in both places

**Comment by sideshowbarker** [comment]
* Opened https://github.com/mdn/content/pull/3418 for the MDN update
* Opened https://github.com/mdn/browser-compat-data/pull/9572 for the BCD update
