### ISSUE TITLE
Coercion text possibly inacurate

### ISSUE THREAD

**Issue by justincorrigible** [mdn/content#33824]
What's mentioned here https://github.com/mdn/content/blob/76960f06597294df2d93ebb9960ad40c909c7cb5/files/en-us/web/javascript/reference/global_objects/number/index.md?plain=1#L89C38-L89C144 may not be accurate anymore.

`Number(undefined)` and `Number(NaN)` do not return 0 but `NaN`, when I tried them just now (in Firefox' console).
Perhaps I'm doing something wrong? if so, please disregard and close this ticket.

**Comment by Josh-Cena** [comment]
This section talks about INTEGER COERCION, not NUMBER COERCION. See the paragraph above:

> Some operations expect integers, most notably those that work with array/string indices, date/time components, and number radixes.

So, please try `[1, 2, 3][undefined]` and you will get `1` instead of `undefined`.
