### ISSUE TITLE
date-in-GMTString-format => date-in-UTCString-format

### ISSUE THREAD

**Issue by xaverfleer** [mdn/content#33821]
### MDN URL

https://developer.mozilla.org/en-US/docs/web/api/document/cookie#write_a_new_cookie

### What specific section or headline is this issue about?

Write a new cookie

### What information was incorrect, unhelpful, or incomplete?

;expires=date-in-GMTString-format: [...]

### What did you expect to see?

;expires=date-in-UTCString-format: [...]

### Do you have any supporting links, references, or citations?

[T]he Java Date class had a method called toGMTString — which was poorly named, because the [Greenwich Mean Time](https://en.wikipedia.org/wiki/Greenwich_Mean_Time) is not equivalent to the [Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time), while JavaScript dates always operate by UTC time. For web compatibility reasons, toGMTString remains as an alias to toUTCString, and they refer to the exact same function object. 

src: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toUTCString#aliasing

### Do you have anything more you want to share?

I love your work. Thank you!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document/cookie`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/cookie/index.md
* Last commit: https://github.com/mdn/content/commit/fbc9980c0718c3ead40863b20a74fc8535ebcc85
* Document last modified: 2024-05-22T05:25:56.000Z

</details>

**Comment by Ashish-CodeJourney** [comment]
Raised a PR related to the same
https://github.com/mdn/content/pull/33830

Please check preview here
https://pr33830.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Document/cookie
