### ISSUE TITLE
yield* has unexpected result when internal generator body contains a 'return'

### ISSUE THREAD

**Issue by DustinX** [mdn/content#33852]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield*

### What specific section or headline is this issue about?

"iterator" 'return's don't behave the same way as the external 'generator' returns

### What information was incorrect, unhelpful, or incomplete?

In the description paragraph, it has these sentences:

> Then, each time the next() method of the generator is called, yield* calls the iterator's next() method, passing the argument received by the generator's next() method (always undefined for the first call), and yielding the same result object as what's returned from the iterator's next() method. If the iterator result has done: true, then the yield* expression stops executing and returns the value of that result.

This isn't exactly right, according to my tests.
The internal generator (called 'iterator' in these docs) behaves differently from the external generator with respect to how it handles it's "return" line.  

Normally with generators, a 'return' line is like another 'yield' line, but with 'done' set to 'true'.
Related, the last yield in a generator without a 'return' provides an object like {value: x, done: false}, and then a .next() call after that provides an object like {value: undefined, done: true}.  This result is also skipped, if we were waiting for a 'done: true', when using 'yield*', presumably as a convenience to avoid unneeded empty values. 

I'd say this is a 'gotcha' that could be called out.

Example:
```
  const generatorFunction = function* () {
    yield 1;
    return 2;
  };

  const generator = generatorFunction();

  console.log(generator.next());  // { value: 1, done: false }
  console.log(generator.next());  // { value: 2, done: true }
  console.log(generator.next());  // { value: undefined, done: true }
```

However, when a generator is used by a 'yield*' expression, that 'return' line gets ignored.

Example:
```

  const generatorFunction = function* () {
    yield 1;
    return 2;
  };

  const generator = generatorFunction();

// ^^ same code as before

  const anotherGeneratorFunction = function* () {
    yield* generator;
    yield 3;
    return 4;
  };

  const anotherGenerator = anotherGeneratorFunction();

  console.log(anotherGenerator.next()); // { value: 1, done: false }
// Note: "value: 2" is 'lost', compared to when calling '.next' on 'generator' directly
  console.log(anotherGenerator.next()); // { value: 3, done: false }
  console.log(anotherGenerator.next()); // { value: 4, done: true }
  console.log(anotherGenerator.next()); // { value: undefined, done: true }
```

Execution environment: Node.js v20.11.1

### What did you expect to see?

Setting aside for the moment I don't know exactly why it behaves this way, aside from "that's what the spec says", I think the description could be more clear about how this case works.  Maybe calling it out as "special" behavior when using '*yield'.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/yield_star_`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield*
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/yield_star_/index.md
* Last commit: https://github.com/mdn/content/commit/c6f0f106b9083984dbf597678def6561729bb459
* Document last modified: 2023-09-07T01:22:04.000Z

</details>

**Comment by DustinX** [comment]
I think this line could be changed:

>  If the iterator result has done: true, then the yield* expression stops executing and returns the value of that result.

It is more like:

>  If the iterator result has done: true, then the yield* expression stops executing, ignores that result, returns execution to the parent generator, and returns the next yielded value.

**Comment by Josh-Cena** [comment]
@DustinX: we never said the inner result with `done: true` is ever yielded by the outer generator. It is never. We say:

> If the iterator result has `done: true`, then the `yield*` expression stops executing and returns the value of that result.

The value is returned by the `yield*` expression to the generator body. For example:

```js
function *genA() {
  yield 1;
  return 1;
}

function *genB() {
  yield 1;
}

function *gen() {
  console.log(yield *genA());
  console.log(yield *genB());
}

console.log([...gen()]);

// Output:
// 1
// undefined
// [1, 1]
```

What can we change?

**Comment by Josh-Cena** [comment]
Closing because this is correct. Let me know if there's anything we can clarify, but I personally think it's unambiguous.

**Comment by DustinX** [comment]
I see.  In 'generator lingo' the current text does differentiate between 'yield' and 'return', so, that's fine.
