### ISSUE TITLE
[WebAPI] 127Beta?: Ship webgl.drawingBufferColorSpace

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#33850]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Features to document

[`WebGLRenderingContext.drawingBufferColorSpace`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/drawingBufferColorSpace) and [`WebGL2RenderingContext.drawingBufferColorSpace`](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext) appear to have been shipped in FF127 beta 

Seeking confirmation of final 127 shipping in https://bugzilla.mozilla.org/show_bug.cgi?id=1885491#c2

## Related Gecko bugs

[1885491: Ship webgl.drawingBufferColorSpace](https://bugzilla.mozilla.org/show_bug.cgi?id=1885491 )

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Waiting on release confirmation in https://bugzilla.mozilla.org/show_bug.cgi?id=1885491#c2

Status

- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/23198
- [ ] Docs - needs [WebGL2RenderingContext.drawingBufferColorSpace](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext)
- [ ] Release note
- [ ] Dev docs complete

**Comment by hamishwillee** [comment]
FYI, looks like a bug that this isn't behind a pref, but as per https://bugzilla.mozilla.org/show_bug.cgi?id=1885491#c4 it counts as shipped, at least for now.

**Comment by Elchi3** [comment]
Fwiw, this was backed out in 130: https://bugzilla.mozilla.org/show_bug.cgi?id=1909559

**Comment by hamishwillee** [comment]
Thanks @Elchi3 - I'll look at it in https://github.com/mdn/content/issues/35422
