### ISSUE TITLE
exercise 3

### ISSUE THREAD

**Issue by CSchmidtRaab** [mdn/content#33866]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_variables

### What specific section or headline is this issue about?

exercise 3

### What information was incorrect, unhelpful, or incomplete?

I'm new to this so I don't know how to fix this, but I just noticed it. In exercise 3, instead of '62' (20 + 42), the result of the code runs into '4220'. 

### What did you expect to see?

I expected the code to return '62' instead of '4220'.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/test_your_skills_colon__variables`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_variables
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/test_your_skills_colon__variables/index.md
* Last commit: https://github.com/mdn/content/commit/c64e813d8ab9dbe22cbc049c26f7c6703370a2b7
* Document last modified: 2023-10-23T08:57:58.000Z

</details>

**Comment by Josh-Cena** [comment]
`myAge` right now is a string. You need to convert it to a number first using `myAge = Number(myAge);` so that `+ 20` does number addition instead of string concatenation.
