### ISSUE TITLE
Dead Link to SVG Gallery

### ISSUE THREAD

**Issue by ChrisJones79** [mdn/content#33865]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG

### What specific section or headline is this issue about?

Examples Section

### What information was incorrect, unhelpful, or incomplete?

There are bullet list items linking to examples. The gallery example links to a broken page. The broken page is https://www1.plurib.us/svg_gallery/. None of the examples appear, just boxes, and clicking them brings up a 500 error.

### What did you expect to see?

SVG gallery, examples.

### Do you have any supporting links, references, or citations?

https://www1.plurib.us/svg_gallery/

### Do you have anything more you want to share?

I would just remove the link. Perhaps find a newer gallery to link to.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/index.md
* Last commit: https://github.com/mdn/content/commit/210a9c7ff102fc1eca3cd21e2b2b3a0c3eb4fe10
* Document last modified: 2024-05-03T12:43:08.000Z

</details>

**Comment by wbamberg** [comment]
Thank you for filing! Yes, I agree we should just delete the broken link.
