### ISSUE TITLE
CSS Anchor Article was removed

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [mdn/content#33868]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/anchor

### What specific section or headline is this issue about?

CSS

### What information was incorrect, unhelpful, or incomplete?

The whole post about CSS Anchor positioning was removed

### What did you expect to see?

All the information you usally see about this kind of stuff

### Do you have any supporting links, references, or citations?

This Google site is linking to this part of the docs: https://developer.chrome.com/blog/anchor-positioning-api

**Comment by wbamberg** [comment]
It's not been removed, it hasn't been added yet: https://github.com/mdn/content/pull/33058.
