### ISSUE TITLE
Mention that other data types can be used to index objects

### ISSUE THREAD

**Issue by amirhoseinsalimi** [mdn/content#33872]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures

### What specific section or headline is this issue about?

Objects -> Properties

### What information was incorrect, unhelpful, or incomplete?

The statement "Property keys are either strings or symbols." is incorrect because it omits the fact that numbers can also be used directly as property keys in JavaScript objects. While it is true that numbers are implicitly converted to strings, they can still be assigned as property keys. For clarity and completeness, this behavior should be explicitly mentioned in the documentation.

### What did you expect to see?

I expected the documentation to state that property keys in JavaScript can be strings, numbers, or symbols. Specifically, the documentation should clarify that while numbers used as property keys are internally converted to strings, they can still be used directly in the code. This clarification would provide a more accurate and complete understanding of how property keys work in JavaScript objects.

### Do you have any supporting links, references, or citations?

[MDN Web Docs - Objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/data_structures`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/data_structures/index.md
* Last commit: https://github.com/mdn/content/commit/c3c81e79b3bc798ffb69e80e93c10f74fb27467f
* Document last modified: 2023-12-20T02:24:39.000Z

</details>

**Comment by Josh-Cena** [comment]
Why numbers specifically? You can do `obj[true] = 1`, that doesn't mean booleans can also be property keys.

Open to adding a sentence saying you can use other data types such as numbers to index an object but they get coerced to strings.

**Comment by amirhoseinsalimi** [comment]
Will do.

**Comment by amirhoseinsalimi** [comment]
This is interesting by the way. TypeScript types specify that object keys can only be of types `string | number | symbol`. This is where I learned that `number` type can be used as keys. I'm curious why TS doesn't let `boolean`s as object keys. (I'm also totally aware that this doesn't have anything to do with plain JS or MDN docs).

TypeScript behavior:

![Screenshot from 2024-06-02 13-53-06](https://github.com/mdn/content/assets/25503371/693e4d24-7e97-40b8-b571-165de41e2fa0)

BTW you are correct, the type coercion happens for both numbers and booleans keys. JS behavior:

![image](https://github.com/mdn/content/assets/25503371/7f2fe29a-655f-495d-9231-8c66f28f471b)

**Comment by Josh-Cena** [comment]
TS needs to make a balance between "what actually happens" and "what developers expect". For example you should be able to index an array with arbitrary numbers but not arbitrary strings, so it has to have some way to express that. Template literal types `` `${number}` `` came very late and is not really how people think about their types.
