### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by marvinhagemeister** [mdn/content#33879]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin

### What information was incorrect, unhelpful, or incomplete?

The image that is supposed to show the differences between the various values cannot be found. The URL returns a 404:

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin/canvas_linejoin.png

### What did you expect to see?

The image

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/linejoin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/linejoin/index.md
* Last commit: https://github.com/mdn/content/commit/0a881eea07f0cec6ca4ed85a24af43b367a9f80d
* Document last modified: 2024-03-11T23:42:25.000Z

</details>

**Comment by estelle** [comment]
found the image!
