### ISSUE TITLE
Link not opening

### ISSUE THREAD

**Issue by Shubham-Lal** [mdn/content#33870]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Add_a_hit_map_on_top_of_an_image

### What specific section or headline is this issue about?

The site "thenewcode.com" can't be reached

### What information was incorrect, unhelpful, or incomplete?

At the very end of this [article](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Add_a_hit_map_on_top_of_an_image#step_3_make_sure_it_works_for_everybody), the paragraph referencing this line
_If you must use image maps, you may want to look into [Matt Stow's jQuery plugin.](https://github.com/stowball/jQuery-rwdImageMaps) Alternatively, Dudley Storey demonstrates a way to [use SVG for an image map effect,](https://thenewcode.com/696/Using-SVG-as-an-Alternative-To-Imagemaps) along with a subsequent [combined SVG-raster hack](https://thenewcode.com/760/Create-A-Responsive-Imagemap-With-SVG) for bitmap images._
the link of `use SVG for an image map effect,` and `combined SVG-raster hack` is not accessible.

### What did you expect to see?

I should have been redirected to blog or doc with the implementation of image maps using SVG.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/howto/add_a_hit_map_on_top_of_an_image`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Add_a_hit_map_on_top_of_an_image
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/howto/add_a_hit_map_on_top_of_an_image/index.md
* Last commit: https://github.com/mdn/content/commit/8d766d1d1c60a2d6d2c95bd2aa9d0b297d9c70ac
* Document last modified: 2023-12-04T12:04:17.000Z

</details>

**Comment by Ashish-CodeJourney** [comment]
There's some problem with that site "https://thenewcode.com/" or maybe site is down, documentation is fine.

**Comment by wbamberg** [comment]
We should remove these links IMO.

**Comment by vvswps** [comment]
We can add a link to the archived website on web.archive.org

https://web.archive.org/web/20231116144953/https://thenewcode.com/696/Using-SVG-as-an-Alternative-To-Imagemaps

As this is a static website and the content is unlikely to change in future

**Comment by hamishwillee** [comment]
It generally isn't a good idea to add links to web archives, because often by the time a resource is only available there it is really only of historical interest. By way of example, this particular link is to SVG1.1 code that might not even work on modern browsers.

If someone wants to invest the time to retest and pull that example into the MDN then that might be OK, but otherwise I'd first test to see if you can find some good and more recent examples, or follow @wbamberg advice above and delete the links.

**Comment by estelle** [comment]
We should not be encouraging image maps, and definitely not suggesting JS plugins. I removed the paragraph in https://github.com/mdn/content/pull/33922

**Comment by Ashish-CodeJourney** [comment]
> We should not be encouraging image maps, and definitely not suggesting JS plugins. I removed the paragraph in #33922

looks good but removing it completely doesn't makes, atleast there should be some information

> We should not be encouraging image maps, and definitely not suggesting JS plugins. I removed the paragraph in #33922

looks good
