### ISSUE TITLE
runtime.getPlatformInfo() can be called on other contexts as well, I guess

### ISSUE THREAD

**Issue by denilsonsa** [mdn/content#33874]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getPlatformInfo

### What information was incorrect, unhelpful, or incomplete?

> This can only be called in the background script context.

### What did you expect to see?

Given that wording, I assumed that API was only available on a background script (or service worker), and wouldn't be available on a popup (AKA browser action).

But when I tried it myself, it worked just fine inside a browser action page. So… I'm confused. Is it supposed to work "anywhere" in an extension context? Where is it not supposed to work?

### Do you have any supporting links, references, or citations?

I also quickly checked <https://developer.chrome.com/docs/extensions/reference/api/runtime#method-getPlatformInfo> and couldn't find any restriction information, but I didn't read the whole page and I may have missed.

### Do you have anything more you want to share?

Can someone please check if there are restrictions on calling that function? What are those restrictions? I believe that sentence is outdated (based on a quick test), but I don't know.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/runtime/getplatforminfo`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getPlatformInfo
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/runtime/getplatforminfo/index.md
* Last commit: https://github.com/mdn/content/commit/43e3ff826b7b755b05986c99ada75635c01c187c
* Document last modified: 2024-01-22T01:22:45.000Z

</details>

**Comment by Ashish-CodeJourney** [comment]
Raised a PR related to the same https://github.com/mdn/content/pull/33890
Please check 
suggestions appriciated :)
