### ISSUE TITLE
Document how to escape CSS attribute selectors

### ISSUE THREAD

**Issue by DanKaplanSES** [mdn/content#33886]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

### What information was incorrect, unhelpful, or incomplete?

Given `[attr=value]` as a CSS selector, I have the following questions.

### `attr` questions
1. What characters are allowed for `attr`?
2. Are there `attr` characters that need to be escaped?
    1. If yes, what are these characters and how do you escape them?
3. Are you allowed to wrap `attr` in quotes?
    1. If yes, which quotes are allowed? `'`, `"`, `` ` ``?

### `value` questions
1. What characters are allowed for `value`?
2. Are there `value` characters that need to be escaped?
    1. If yes, what are these characters and how do you escape them?
3. Are quotes required?
4. Which quotes are allowed to wrap `value`? `'`, `"`, `` ` ``?
5. How do you escape nested quotes within `value`?

If these questions are too low level for the article, it would be nice to link to where (some of?) the answers can be found. I looked at [the specification linked in the article](https://drafts.csswg.org/selectors/#attribute-selectors), but I didn't see this documented there either.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/attribute_selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/attribute_selectors/index.md
* Last commit: https://github.com/mdn/content/commit/8d4fb1e2934111a13989d2796152dc601468e7b5
* Document last modified: 2024-03-25T22:39:01.000Z

</details>

**Comment by estelle** [comment]
This content could be added to https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors or https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors, or a new guide altogether.

The case sensitivities is discussed at https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors/Selectors_and_combinators#attribute_selectors

**Comment by estelle** [comment]
Committed a PR to address this issue.
All the quotes questions are addressed in https://developer.mozilla.org/en-US/docs/Web/CSS/string, which is now linked from the page.
