### ISSUE TITLE
Conflict on information about CDATA in HTML

### ISSUE THREAD

**Issue by Jamstah** [mdn/content#33894]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CDATASection

### What specific section or headline is this issue about?

> Note: CDATA sections should not be used within HTML they are considered as comments and not displayed.

### What information was incorrect, unhelpful, or incomplete?

This information says that CDATA sections are treated like comments, but in [createCDATASection](https://developer.mozilla.org/en-US/docs/Web/API/Document/createCDATASection) it says:
> This will only work with XML, not HTML documents (as HTML documents do not support CDATA sections); attempting it on an HTML document will throw NOT_SUPPORTED_ERR. 

These statements conflict. Either its supported as a comment, or its not supported.

### What did you expect to see?

Consistent information

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/cdatasection`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CDATASection
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/cdatasection/index.md
* Last commit: https://github.com/mdn/content/commit/b280ea1234452ff553caa466bf532a66ba51db01
* Document last modified: 2023-02-19T06:34:57.000Z

</details>

**Comment by estelle** [comment]
These statements are not in conflict. If a CDATA block is included within markup, it will not be visible - That is what the first statement states. It basically fails silently.

The second statement addresses creating CDATA sections via JavaScript. JavaScript will throw errors when an error is encountered.

I did update the codeblock from HTML to XML in the [CDATASection](https://developer.mozilla.org/en-US/docs/Web/API/CDATASection) page, as that was indeed inaccurate.

**Comment by Jamstah** [comment]
Thanks, the codeblock change helps.

I still think they conflict. One says they are treated as comments (and therefore supported, as comments). The other says they are not supported at all.

But I also don't mind if this gets closed without fixing that, I know what I need to know :)

**Comment by Josh-Cena** [comment]
@Jamstah: HTML never throws errors. If something isn't supported, it's just ignored.

**Comment by Josh-Cena** [comment]
That's not because it's CDATA. That's because it begins with `<!` and ends with `>`. Even `<!a>` will become a comment.
