### ISSUE TITLE
Global class constructors incorrectly links to Object.prototype.constructor

### ISSUE THREAD

**Issue by std4453** [mdn/content#33893]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

### What specific section or headline is this issue about?

Instance properties => `Map.prototype.constructor`

### What information was incorrect, unhelpful, or incomplete?

The `Map.prototype.constructor` entry under *Instance properties* section links to [`Object.prototype.constructor`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor).

Yet in the description, it states that:

> For Map instances, the initial value is the [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/Map) constructor.

where the link here correctly refers to the `Map()` constructor.

### What did you expect to see?

The `Map.prototype.constructor` should correctly link to [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/Map).

### Do you have any supporting links, references, or citations?

According to [the standard](https://tc39.es/ecma262/multipage/keyed-collections.html#sec-map.prototype.constructor):

> The initial value of Map.prototype.constructor is [%Map%](https://tc39.es/ecma262/multipage/keyed-collections.html#sec-map-constructor).

There should be no reason for `Map.prototype.constructor` to link to `Object.prototype.constructor`.

### Do you have anything more you want to share?

Related source code: 

https://github.com/mdn/content/blame/d377045efe5d13531b73f8823301f8cc1dc58f84/files/en-us/web/javascript/reference/global_objects/map/index.md#L314

The modification was made by commit [d19dc315](https://github.com/mdn/content/commit/d19dc31570f62196a5837be38bd0b11c45e67b05#diff-24d0aab1f8d007cc2fac950232b782271f892761ed5a9c9a6e1f72a5d7ccbe90), which fixes #24658 .

It seems that the commit has modified a bunch of files for global objects, linking all their constructors to `Object.prototype.constructor`, which I believe is a mistake. All those links should be modified to link to their actual constructor pages.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/map`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/map/index.md
* Last commit: https://github.com/mdn/content/commit/8a9085b96d0135920be9b281d4500ff72a7a8369
* Document last modified: 2024-03-11T23:58:09.000Z

</details>

**Comment by Josh-Cena** [comment]
The `Object.prototype.constructor` page purposedly talks about the `constructor` property that every object has, not just `Object.prototype.constructor` itself. We link to this one because we want to talk about the _property_, not the _value_ of that property.

**Comment by std4453** [comment]
> The `Object.prototype.constructor` page purposedly talks about the `constructor` property that every object has, not just `Object.prototype.constructor` itself. We link to this one because we want to talk about the _property_, not the _value_ of that property.

I get your point, the link is trying to tell people "this is a constructor property and you might want to learn more about constructors".

Still I do find it confusing that a link which says `Map.prototype.constructor` jumps to `Object.prototype.constructor`. Maybe we could do it the same way as for `@@toStringTag` properties:

> [Map.prototype[@@toStringTag]](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#map.prototypetostringtag)
> 
> The initial value of the [@@toStringTag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag) property is the string "Map". This property is used in [Object.prototype.toString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString).

Thus be like:

> [Map.prototype.constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#map.prototypeconstructor)
>
> The [constructor function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor) that created the instance object. For Map instances, the initial value is the [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/Map) constructor.

**Comment by Josh-Cena** [comment]
The `Object.prototype.constructor` page talks about a property called `constructor` on objects. It talks about neither constructor functions themselves nor the `Object.prototype.constructor` property itself exclusively. The `@@toString` situation is just because we don't have a "catch-all" page for `@@toString` properties, and since well-known symbols are meant to be used as properties anyway the `Symbol.*` pages serve the dual purpose for describing the symbol and the property keyed by that symbol. Our reasoning is that if you click on the `Map.prototype.constructor` page, you are not interested in the `Map()` constructor (otherwise you would just use the other link that has the exact title), but why map instances have this property called `constructor` that happens to have the value `Map`, which the linked page will tell you.
