### ISSUE TITLE
broken link to frameworks

### ISSUE THREAD

**Issue by Smaddermand** [mdn/content#33948]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction

### What specific section or headline is this issue about?

Introducing Express

### What information was incorrect, unhelpful, or incomplete?

the link "Node web frameworks" to https://expressjs.com/en/resources/frameworks.html is broken

### What did you expect to see?

a webpage with frameworks using node

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/introduction/index.md
* Last commit: https://github.com/mdn/content/commit/2528ef17bf90b1822940066c9365641181c5e8e1
* Document last modified: 2024-03-01T02:30:38.000Z

</details>

**Comment by ragul1697** [comment]
It is an issue with Express.js page. The requested resource is not available for English version. But it is available in Slovak language.
Check here: https://expressjs.com/sk/resources/frameworks.html

**Comment by Josh-Cena** [comment]
The page was removed in https://github.com/expressjs/expressjs.com/pull/1484. It was erroneously not removed for sk. I think we should remove the link without replacement because none of these are exactly widely used today.

**Comment by Smaddermand** [comment]
Alright.Yes, good idea. Couldn't recognize any of them really :)
