### ISSUE TITLE
HTML Demo for ::backdrop pseudo-element has invisible button

### ISSUE THREAD

**Issue by RobinHohm** [mdn/content#33957]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop

### What specific section or headline is this issue about?

HTML Demo for ::backdrop pseudo-element

### What information was incorrect, unhelpful, or incomplete?

In the HTML Demo, the button to show the dialog is invisible.

### What did you expect to see?

I expected the button to be visible.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_doublecolon_backdrop`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_backdrop/index.md
* Last commit: https://github.com/mdn/content/commit/1c4eb0bfb5f72a26fcc21a83fac91aa3e66c2fb8
* Document last modified: 2024-01-02T16:00:45.000Z

</details>

**Comment by Josh-Cena** [comment]
Can you add some screenshots? What's your browser version? It works for me:

<img width="792" alt="image" src="https://github.com/mdn/content/assets/55398995/f5f2aa8a-dd99-456c-8b6d-4e540c77a1f7">

**Comment by estelle** [comment]
i also changed the example:  originally it was a screenshot of a video. in #34076 I changed it to a dialog with a rainbow background. Hopefully that addresses the issue.

**Comment by Josh-Cena** [comment]
@wbamberg: no one knows what this issue is asking about so we'll likely close it after a while anyway 🤷‍♂️

**Comment by wbamberg** [comment]
Yeah I know, but I didn't want to close it right away after https://github.com/mdn/content/pull/34076 was merged, because that's not related.

**Comment by Josh-Cena** [comment]
Closing, but still welcoming follow-ups and may re-open.
