### ISSUE TITLE
Issue with "Responsive images": cannot see a change to the image

### ISSUE THREAD

**Issue by RPIERIS** [mdn/content#3397]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

#### What information was incorrect, unhelpful, or incomplete?
I am using Firefox developer edition on the section [Resolution Switching: Same size, Different resolutions](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_same_size_different_resolutions) and I cannot see a change to the image. This is not the case when I use Chrove Developer edition. [Please note I was looking at the html on github](https://mdn.github.io/learning-area/html/multimedia-and-embedding/responsive-images/srcset-resolutions.html).

#### Specific section or headline?
See above

#### What did you expect to see?
I expected the image size to physically change

#### Did you test this? If so, how?
I used Chrome developer edition and it changed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.html
* Last commit: https://github.com/mdn/content/commit/49f606217b82a761b6b52946ea4da3752d2375ee
* Document last modified: 2021-02-09T19:08:28.000Z

</details>

**Comment by rachelandrew** [comment]
@RPIERIS what steps did you take to see/not see the change?

We have had a few reports on this page and I've never been able to figure out what people are actually reporting, so this would be helpful to know!

**Comment by RPIERIS** [comment]
@rachelandrew I think I misunderstood what was expected. 

I am specifically looking at the [srcset-resolutions.html](https://mdn.github.io/learning-area/html/multimedia-and-embedding/responsive-images/srcset-resolutions.html). This is in the [Resolution switching: Same size, different resolutions](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_same_size_different_resolutions) section. 

I expected the images to get bigger or smaller  320w 480w 640w based on the screen size and due to responsiveness. The chrome browser appears to change the dimensions while on firefox developer there is overflow with no change. I think I confused responsiveness with resolution. Let me know if I have misunderstood. BTW thanks for Grid by example.

**Comment by OnkarRuikar** [comment]
> I expected the images to get bigger or smaller 320w 480w 640w based on the screen size and due to responsiveness.

The image shouldn't change size as the [width has explicitly been set to `320px`](https://github.com/mdn/learning-area/blob/6191b97cfcef225e14a48e8582ab2c2aabe4649c/html/multimedia-and-embedding/responsive-images/srcset-resolutions.html#L10). The demo is all about showing bigger images(in same screen size) on higher quality screens(e.g. Apple devices) for better experience.

**Comment by teoli2003** [comment]
Maybe there is some text to improve to make this clearer?

**Comment by mattdecamp** [comment]
What may help is an aside reminding the reader that though the example uses images with different widths, because the CSS constrains the width to 320px, we only need to think of the larger images as richer versions of the default one.

If users read this section immediately after the previous one ([Resolution switching: Different sizes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_different_sizes)), I could see that some could be confused about the expected result.
