### ISSUE TITLE
Missing "zstd" compression in CompressionStream

### ISSUE THREAD

**Issue by truongan07** [mdn/content#33971]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CompressionStream/CompressionStream

### What information was incorrect, unhelpful, or incomplete?

CompressionStream does not support "zstd" compression

### What did you expect to see?

```js
const compression = new CompressionStream("zstd");
const decompression = new DecompressionStream("zstd")
```

### Do you have anything more you want to share?

```js
(async () => {
  const compression = async item => {
    const compression = new CompressionStream('zstd'), writer = compression.writable.getWriter();
    
    writer.write(item);
    writer.close();
    
    return await new Response(compression.readable).arrayBuffer();
  };

  const decompression = async compress => {
    const decompression = new DecompressionStream('zstd'), writer = decompression.writable.getWriter();
  
      writer.write(compress);
      writer.close();
      
      return await new Response(decompression.readable).arrayBuffer();
  };
	
  const text = 'this is text';
  const encoder = new TextEncoder;
  const compress = await compression(encoder.encode(text));
  
  console.log('compress = ', compress);
  
  const decompress = await decompression(compress);
  const decoder = new TextDecoder;
  
  console.log('decompress = ', decompress);
  console.log('text = ', decoder.decode(decompress));
```

**Comment by hamishwillee** [comment]
Thanks, but I am closing as invalid. This format isn't expected to be supported in the spec - it isn't a valid compression option, and isn't documented as being supported.

**Comment by Josh-Cena** [comment]
This is not part of the spec. If you want to see it supported, send the issue to the spec instead.

**Comment by truongan07** [comment]
it isn't a valid compression option ?

![image](https://github.com/mdn/content/assets/141234261/17c3b416-1999-47d9-a47d-d3893d64f679)

**Comment by Josh-Cena** [comment]
@truongan07 That's what the _browser_ supports. What this particular API supports is specified by https://compression.spec.whatwg.org/#compression-stream
