### ISSUE TITLE
[CSS] Remove support for the 'align-tracks' and 'justify-tracks' properties (css-grid-3)

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#33989]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1900195

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by dletorey** [comment]
Awaiting on confirmation that these pages `align-tracks` and `justify-track` should be removed and all references to them removed.

I have done this, pre-emptively, and can be found in [this branch](https://github.com/CodeRedDigital/content/tree/33989-remove-support-for-a-j-tracks)

I have also removed the reference from the Experimental Features and added a note on the 128 page in [this branch](https://github.com/CodeRedDigital/content/tree/33989-remove-support-for-a-j-tracks-ff-release)

**Comment by pepelsbey** [comment]
I’d also suggest updating the BCD entries for these properties: [align-tracks.json](https://github.com/mdn/browser-compat-data/blob/main/css/properties/align-tracks.json) and [justify-tracks.json](https://github.com/mdn/browser-compat-data/blob/main/css/properties/justify-tracks.json). They are marked as experimental and not deprecated, which is no longer true.

```json
"status": {
  "experimental": true,
  "standard_track": true,
  "deprecated": false
}
```

I think it should be `false`, `false`, `true`, given the lack of implementation and the removal from the spec.

**Comment by dletorey** [comment]
> I’d also suggest updating the BCD entries for these properties: [align-tracks.json](https://github.com/mdn/browser-compat-data/blob/main/css/properties/align-tracks.json) and [justify-tracks.json](https://github.com/mdn/browser-compat-data/blob/main/css/properties/justify-tracks.json). They are marked as experimental and not deprecated, which is no longer true.
> 
> ```json
> "status": {
>   "experimental": true,
>   "standard_track": true,
>   "deprecated": false
> }
> ```
> 
> I think it should be `false`, `false`, `true`, given the lack of implementation and the removal from the spec.

This has already been done in my absence

**Comment by dletorey** [comment]
@pepelsbey Done

**Comment by dletorey** [comment]
> @pepelsbey Done [mdn/browser-compat-data#23648](https://github.com/mdn/browser-compat-data/pull/23648)

Closed this pull request as both of these properties have now been deleted
