### ISSUE TITLE
the link to "EdgeHTML issue tracker" is broken

### ISSUE THREAD

**Issue by xiaoranya** [mdn/content#33982]
### MDN URL

- zh-CN: https://developer.mozilla.org/zh-CN/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction
- en-US: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction

### What specific section or headline is this issue about?

- zh-CN: [报告程序错误](https://developer.mozilla.org/zh-CN/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction#%E6%8A%A5%E5%91%8A%E7%A8%8B%E5%BA%8F%E9%94%99%E8%AF%AF)
- en-US: [Reporting bugs](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction#reporting_bugs)

### What information was incorrect, unhelpful, or incomplete?

The link to [EdgeHTML issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/) is broken.

### What did you expect to see?

Remove or replace this broken link.

### Do you have any supporting links, references, or citations?

EdgeHTML issue tracker is the issue reporting program for old version of Edge
[Microsoft Edge Feedback](https://www.microsoft.com/en-us/edge/feedback) - official feedback page
[Microsoft Edge Insider](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/tools_and_testing/cross_browser_testing/introduction`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/Tools_and_testing/Cross_browser_testing/Introduction
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/tools_and_testing/cross_browser_testing/introduction/index.md
* Last commit: https://github.com/mdn/translated-content/commit/575a845e54e5482ee16654ee561e74f4d6bb969c
* Document last modified: 2024-05-09T04:40:34.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for reporting this. I'm proposing to remove it for now, alternatively, we can link to the support forum, but I don't think it's really suitable here.
