### ISSUE TITLE
[WebAPI] RTCRtpParameters.codecs aren't populated

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#33988]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Features to document

Needs a little investigation but initially looks like bcd update

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1534687

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Adds support for [`RTCRtpReceiver.getParameters()`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpReceiver/getParameters) and the returned object including the [codecs](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpReceiver/getParameters#codecs) object.

Relevant tests https://wpt.live/webrtc/RTCRtpParameters-codecs.html (and I guess https://wpt.live/webrtc/RTCRtpReceiver-getParameters.html)

Need to check the docs, but I can see that the spec does not quite match our docs for returned values.

dictionary [RTCRtpCodecParameters](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcodecparameters) : [RTCRtpCodec](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcodec) {
  required [octet](https://webidl.spec.whatwg.org/#idl-octet) [payloadType](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcodecparameters-payloadtype);
};

dictionary [RTCRtpCodec](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcodec) {
  required [DOMString](https://webidl.spec.whatwg.org/#idl-DOMString) [mimeType](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcodec-mimetype);
  required [unsigned long](https://webidl.spec.whatwg.org/#idl-unsigned-long) [clockRate](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcodec-clockrate);
  [unsigned short](https://webidl.spec.whatwg.org/#idl-unsigned-short) [channels](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcodec-channels);
  [DOMString](https://webidl.spec.whatwg.org/#idl-DOMString) [sdpFmtpLine](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcodec-sdpfmtpline);
};

Status

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/23364
- [ ] Docs
- [ ] Release note
- [ ] dev-docs-complete
