### ISSUE TITLE
Issue with "font-variant-numeric": fonts cannot be loaded from mdn.mozillademos.org

### ISSUE THREAD

**Issue by arafalov** [mdn/content#340]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric

#### What information was incorrect, unhelpful, or incomplete?
Demonstration did not work as the font did not load, due to CORS
Error message (one of several similar): _Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mdn.mozillademos.org/files/15757/SourceSansPro-Regular.otf. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)._

#### Specific section or headline?
Setting ordinal numeric forms

#### What did you expect to see?
1st, 2nd, 3rd with special glyphs

#### Did you test this? If so, how?
Looked in Firefox 83 on Mac

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/font-variant-numeric`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/font-variant-numeric/index.html
* Report started: 2020-12-17T03:15:23.011Z

</details>

**Comment by sideshowbarker** [comment]
hmm yeah, confirmed Access-Control-Allow-Origin response header in the response:
```
$ curl -i -H "Origin: https://developer.mozilla.org" \
 https://mdn.mozillademos.org/files/15757/SourceSansPro-Regular.otf
HTTP/2 302
content-type: text/html; charset=utf-8
content-length: 0
location: https://media.prod.mdn.mozit.cloud/attachments/2018/01/12/15757/3aa894e5587d8f14121cb3766c2538ce/SourceSansPro-Regular.otf
cache-control: public, max-age=900
content-language: en-US
date: Thu, 17 Dec 2020 03:56:16 GMT
etag: "d41d8cd98f00b204e9800998ecf8427e"
last-modified: Fri, 12 Jan 2018 17:44:58 GMT
server: gunicorn/20.0.4
strict-transport-security: max-age=63072000
x-content-type-options: nosniff
x-frame-options: ALLOW-FROM developer.mozilla.org
x-xss-protection: 1; mode=block
x-cache: Miss from cloudfront
via: 1.1 9ce6b85b5dbb12a973d757da5a634a48.cloudfront.net (CloudFront)
x-amz-cf-pop: NRT12-C3
x-amz-cf-id: BkZtJM_2xgJYOaWejXjYJaQFU5J2hRpykzAe7KElJ2T1BecdukCX4w==
```
But I guess that’s because it’s a 302 redirect rather than a 200 OK success response.

If the URL is changed to the `location` value of that 302, we get the Access-Control-Allow-Origin header as expected:

```
$ curl -i -H "Origin: https://developer.mozilla.org" \
 https://media.prod.mdn.mozit.cloud/attachments/2018/01/12/15757/3aa894e5587d8f14121cb3766c2538ce/SourceSansPro-Regular.otf
HTTP/2 200
content-type: application/font-sfnt
content-length: 229588
date: Thu, 17 Dec 2020 03:58:30 GMT
access-control-allow-origin: *
access-control-allow-methods: GET, HEAD
access-control-max-age: 3000
cache-control: public,max-age=31536000,immutable
last-modified: Tue, 17 Dec 2019 00:26:58 GMT
etag: "5e1d162e634a102d7da8db597825a764"
server: AmazonS3
vary: Origin
x-cache: Miss from cloudfront
via: 1.1 6d1bfe5b3d4a6b51cc08e4ee91516591.cloudfront.net (CloudFront)
x-amz-cf-pop: NRT12-C5
x-amz-cf-id: pWjcnQBUDHjvWmXnyOBtaH7sc2u2rxZjPSFPoeEeNd_mZKGNhMVqzQ==
```
But I don’t think we want to use that `https://media.prod.mdn.mozit.cloud` URL in MDN.

It seems the server configuration for https://mdn.mozillademos.org needs to be updated such that it adds the Access-Control-Allow-Origin header to 3xx redirects, not just to success responses.

**Comment by rachelandrew** [comment]
Other demos where we have had CORS issues I've been moving to the css-examples repo https://github.com/mdn/css-examples and embedding the live example from there, we were having these issues before the move to Yari.

So I can take the same approach with this one.
