### ISSUE TITLE
misspelled word in en-US version of this page.

### ISSUE THREAD

**Issue by CHINCHUDO** [mdn/content#34005]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/autofocus

### What specific section or headline is this issue about?

The last sentence of the second paragraph

### What information was incorrect, unhelpful, or incomplete?

In the paragraph that has the following sentence: "If there are several, the first element with the attribute set inserted, usually the first such element on the page, get the initial focus." the fourth to last word, "get", should be "gets" because it is referring to the "first such element". So, "the first element gets the initial focus" and not "the first element get the initial focus." 

### What did you expect to see?

"gets" not "get"

I expected to see, "If there are several, the first element with the attribute set inserted, usually the first such element on the page, gets the initial focus."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/autofocus`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/autofocus
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/autofocus/index.md
* Last commit: https://github.com/mdn/content/commit/2c22a294a6394a439cb9496a70c46fee69f31ff7
* Document last modified: 2024-01-02T05:43:29.000Z

</details>

**Comment by wbamberg** [comment]
-> https://github.com/mdn/content/pull/34011
