### ISSUE TITLE
Tutorial is asking you to show subtitles when the browser blocks them by default

### ISSUE THREAD

**Issue by TheNemPlayer** [mdn/content#34004]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content

### What specific section or headline is this issue about?

Active learning: Embedding your own audio and video

### What information was incorrect, unhelpful, or incomplete?

For an added bonus, you could try researching text tracks, and work out how to add some captions to your video.

### What did you expect to see?

I expected the tutorial to mention on how to allow the index.html to allow subtitles.

### Do you have any supporting links, references, or citations?

I get the error: 

`Security Error: Content at file:///C:/Users/XXX/index.html may not load data from file:///C:/Users/XXX/media/audio.vtt. `

### Do you have anything more you want to share?

I tried many different solutions but nothing worked for me.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/video_and_audio_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/video_and_audio_content/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by bookofbash** [comment]
@TheNemPlayer 

What else have you tried?

You may be looking for this:

https://developer.mozilla.org/en-US/docs/Web/Media/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video#modifications_to_the_html_and_css

**Comment by Josh-Cena** [comment]
This page (maybe others that discuss similar things) should mention that it needs a local HTTP server to work.

**Comment by TheNemPlayer** [comment]
@bookofbash 

Sorry for the late response, I tried adding a users.json file to the config, I tried messing with local group policies, and some other stuff I can't remember right now, but also small things like putting the files in different locations and stuff like that. Nothing worked though, it gives the option for the caption it just doesn't allow the file to be read even though I am confident I wrote it correctly - it's a very simple file there's not much in it so I don't know how I could even make a mistake I can't notice.

**Comment by TheNemPlayer** [comment]
@bookofbash

Sorry for the late response, I tried adding a users.json file to the config, I tried messing with local group policies, and some other stuff I can't remember right now, but also small things like putting the files in different locations and stuff like that. Nothing worked though, it gives the option for the caption it just doesn't allow the file to be read even though I am confident I wrote it correctly - it's a very simple file there's not much in it so I don't know how I could even make a mistake I can't notice.

I accidentally closed it, my bad. I'm new to github issues.

**Comment by TheNemPlayer** [comment]
@Josh-Cena 

I went through the whole tutorial in order, I never remember reading something like that even though it's _possible_ I may have and dismissed it, but I doubt it.

**Comment by Josh-Cena** [comment]
Hence why I suggest it be added :)

**Comment by TheNemPlayer** [comment]
@Josh-Cena 

My bad, I thought you said that it _already_ should say that it needs to be like that, as in it already most likely says it. I agree.
