### ISSUE TITLE
Clarify or replace "additional lines of processing"

### ISSUE THREAD

**Issue by ElvenMonky** [mdn/content#34006]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

"If the body has additional lines of processing" in "The braces can only be omitted if the function directly returns an expression. If the body has additional lines of processing, the braces are required — and so is the return keyword." is a little misleading.
Because e.g.:
```
(a) => (
    a = [3,2,1],
    delete a[1],
    a.reduce((x,y) => x+y)
)
```
Is completely valid expression, that consists of multiple expressions and has additional lines. Quick search for term "lines of processing" does not return anything relevant.

### What did you expect to see?

I would expect something like "If the body has to include statements". (Although, any program can be written with only expressions)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/functions/arrow_functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/functions/arrow_functions/index.md
* Last commit: https://github.com/mdn/content/commit/e3faa375b0179de77a5eff00074e3d168a0a904c
* Document last modified: 2023-10-04T23:23:49.000Z

</details>

**Comment by Josh-Cena** [comment]
> I would expect something like "If the body has to include statements".

Agreed
