### ISSUE TITLE
Issue with "The Netscape XSLT/XPath Reference": broken links

### ISSUE THREAD

**Issue by shrgabor** [mdn/content#3401]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/XSLT/Transforming_XML_with_XSLT/The_Netscape_XSLT_XPath_Reference

#### What information was incorrect, unhelpful, or incomplete?
Reference links are pointing to the wrong url. 
Whenever I click a clink it navigates to a 404 page.

#### Specific section or headline?
Wrong url:
https://developer.mozilla.org/en-US/XPath/Functions/system-property

#### What did you expect to see?
Working url:
https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/system-property

#### Did you test this? If so, how?
I manually changed the url, and it worked. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/xslt/transforming_xml_with_xslt/the_netscape_xslt_xpath_reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/XSLT/Transforming_XML_with_XSLT/The_Netscape_XSLT_XPath_Reference
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/xslt/transforming_xml_with_xslt/the_netscape_xslt_xpath_reference/index.html
* Last commit: https://github.com/mdn/content/commit/3e3c4a2dd55408946bc5c4119b7f599f88c2387d
* Document last modified: 2020-12-31T13:18:14.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened #3403 with a fix.
