### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by edocnikufesin** [mdn/content#34025]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Models

### What specific section or headline is this issue about?

Difining the LocalLibrary Models - Genre Model - final paragraph

### What information was incorrect, unhelpful, or incomplete?

Here we don't need to do anything else, but you can define multiple constrainst a field or fields. 

### What did you expect to see?

Here we don't need to do anything else, but you can define multiple constraints to a field or fields. 

or

Here we don't need to do anything else, but you can define multiple constraints against a field or fields. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/django/models`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Models
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/models/index.md
* Last commit: https://github.com/mdn/content/commit/f7f7ccaf09b65b66e0c995e6df53888288411770
* Document last modified: 2024-02-28T05:13:14.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @edocnikufesin - this will be fixed by https://github.com/mdn/content/pull/34028. Feel free to create PRs for this kind of typo - they are even easier to review.
