### ISSUE TITLE
[WebAPI] Syntax examples for all methods are missing target

### ISSUE THREAD

**Issue by bergus** [mdn/content#34048]
The syntax examples introduced in #13301 should have a target/receiver of the method call and property assignment.

For example https://developer.mozilla.org/en-US/docs/Web/API/FileReader/load_event

> ```js
> addEventListener("load", (event) => {});
> 
> onload = (event) => {};
> ```

should be

```js
fileReader.addEventListener("load", (event) => {});

fileReader.onload = (event) => {};
```

I'm not sure how many pages are affected by this, or how to easily mass-edit them, so I'm posting an issue not a PR.

**Comment by Josh-Cena** [comment]
Hi, we never add the target for methods, because people often take them as global variables or that you must use an identifier to get them. You can check all other instance methods' syntax. Is this particularly confusing for event listeners?

**Comment by Josh-Cena** [comment]
I have previously said similar things: https://github.com/mdn/content/issues/17981 but I don't know what people generally feel about changing the syntax conventions.

**Comment by wbamberg** [comment]
The current format of the "Syntax" box was decided on in https://github.com/mdn/content/issues/2202, as part of https://github.com/openwebdocs/project/issues/26. If we wanted to revisit it, it would be better to [open a discussion](https://github.com/orgs/mdn/discussions) than an issue: that said I don't know if there's much appetite for reanimating this conversation now.

**Comment by bergus** [comment]
@wbamberg thanks for the link! From what I read in #2202 that discussion was about converting bnf syntax for optional parameters to multiline syntax examples, not about dropping the target object.
Anyhow, @Josh-Cena already did open https://github.com/orgs/mdn/discussions/148 so I'll chime in there
