### ISSUE TITLE
Firefox Nightly (128) now supports ExecutionWorld MAIN

### ISSUE THREAD

**Issue by danielhjacobs** [mdn/content#34043]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/ExecutionWorld

### What specific section or headline is this issue about?

Type

### What information was incorrect, unhelpful, or incomplete?

Support for MAIN on Firefox does not mention version 128 supporting it.

### What did you expect to see?

I'd suggest the following:

MAIN was not supported in Firefox until version 128. If you wish to support older versions of Firefox, JavaScript code running in the isolated content script sandbox can use the Firefox "Xray vision" feature, as described in [Share objects with page scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts).

### Do you have any supporting links, references, or citations?

https://bugzilla.mozilla.org/show_bug.cgi?id=1736575

Still marked as dev-doc-needed

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/scripting/executionworld`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/ExecutionWorld
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/scripting/executionworld/index.md
* Last commit: https://github.com/mdn/content/commit/3d9e8e50f02c36bf22f54703c6ff3559bf05edec
* Document last modified: 2024-03-06T01:46:11.000Z

</details>

**Comment by danielhjacobs** [comment]
See also https://github.com/mdn/browser-compat-data/issues/23325

**Comment by rebloor** [comment]
I'm closing to avoid duplication as the dev-doc-needed flag on https://bugzilla.mozilla.org/show_bug.cgi?id=1736575 is sufficient.
