### ISSUE TITLE
[HTTP] Update Image Accept Header

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#34047]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Features to document

Update https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values with new image accept header:
```
image/webp,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5
```
Or depending on `image.avif.enabled` and `image.jxl.enabled`
```
image/avif,image/jxl,image/webp,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5
image/avif,image/webp,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5
image/jxl,image/webp,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5
```
New document accept header:
```
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/png,image/svg+xml,*/*;q=0.8
```
or variations of the following depending on the image prefs
```
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/jxl,image/webp,image/png,image/svg+xml,*/*;q=0.8
```

NOTE - also check this header isn't documented or linked elsewhere

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1711622

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Status

- [ ] BCD
- [ ] Docs #34245
- [ ] Release note/expr features
- [ ] Dev-docs-complete

**Comment by MasterInQuestion** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1879929
    The relevant files should be: https://searchfox.org/mozilla-central/search?q=http.accept

    That not exist in source: mostly couldn't exist in program.
