### ISSUE TITLE
In the list example screenshot, hummus is misspelled as humous.

### ISSUE THREAD

**Issue by txikilopez** [mdn/content#34059]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents

### What specific section or headline is this issue about?

last exercise - shopping list

### What information was incorrect, unhelpful, or incomplete?

misspelled hummus in shopping list screenshot example

### What did you expect to see?

hummus

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/manipulating_documents`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/client-side_web_apis/manipulating_documents/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting. I've opened a PR linked above that should fix this.
