### ISSUE TITLE
No mention of important difference between `revert-layer` and `revert`

### ISSUE THREAD

**Issue by benface** [mdn/content#34064]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer

### What information was incorrect, unhelpful, or incomplete?

There is an important distinction between `revert-layer` and `revert` that this page does not mention (in fact, it even says that `revert-layer` works exactly like `revert` outside of cascade layers, but it's not true): `revert-layer` preserves presentational hints (see https://github.com/w3c/csswg-drafts/issues/7087) while `revert` doesn't. [This article](https://www.mayank.co/blog/revert-layer/#the-nuclear-reset) taught me this.

### What did you expect to see?

In the [Revert-layer vs. revert](https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer#revert-layer_vs._revert) section, the following:

> However, if the `revert-layer` keyword is set on a property outside a layer, the value of the property will roll back to the default value established by the user agent's stylesheet (or by user styles, if any exist). So in this scenario, the `revert-layer` keyword behaves like the [`revert`](https://developer.mozilla.org/en-US/docs/Web/CSS/revert) keyword.

should read more like this:

> However, if the `revert-layer` keyword is set on a property outside a layer, the value of the property will roll back to any value set by presentational hints (e.g. the `width` or `height` attributes in HTML), defaulting to the value established by the user agent's stylesheet (or by user styles, if any exist). So in this scenario, the `revert-layer` keyword behaves very similarly to the [revert](https://developer.mozilla.org/en-US/docs/Web/CSS/revert) keyword, with the exception that `revert` considers presentational hints to be part of the author origin, so it reverts them too.

### Do you have any supporting links, references, or citations?

- https://github.com/w3c/csswg-drafts/issues/6659
  - Resulting spec diff: https://github.com/w3c/csswg-drafts/commit/d7f41c4c276303fc6c1e00101019ba5cf98a0c8f
- https://github.com/w3c/csswg-drafts/issues/7087
  - Resulting spec diff: https://github.com/w3c/csswg-drafts/commit/20d186b88d15decfe4780efcf8599c1f9391d623

### Do you have anything more you want to share?

Thank you!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/revert-layer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/revert-layer/index.md
* Last commit: https://github.com/mdn/content/commit/0053e22667809069b5a62c3de80122cdb65d611c
* Document last modified: 2023-03-22T10:52:42.000Z

</details>

**Comment by Josh-Cena** [comment]
Could you report the data error to https://github.com/mdn/browser-compat-data instead? We are keeping the other part here.

**Comment by benface** [comment]
Ah, thanks @Josh-Cena, but looks like [it's already been reported](https://github.com/mdn/browser-compat-data/issues?q=is%3Aissue+is%3Aopen+revert-layer). I will edit my first post to focus on the other issue.
