### ISSUE TITLE
Content bug: Bad jsref code

### ISSUE THREAD

**Issue by evilpie** [mdn/content#3407]
Noticed this in #3360.

```
files/en-us/web/api/arraybufferview/index.html
11:<p>{{JSRef("Global_Objects", "TypedArray", "Int8Array,Uint8Array,Uint8ClampedArray,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array")}}</p>

files/en-us/web/api/buffersource/index.html
11:<div>{{JSRef("Global_Objects", "ArrayBuffer")}}</div>
```
>For the two calls in question, it looks like an attempt to make a useful sidebar but that doesn't work this way. Usually the sidebar call for API/ pages is {{APIRef}}, so you could change these to use that and see what gets rendered.

@Elchi3

**Comment by Elchi3** [comment]
Opened https://github.com/mdn/content/pull/3408
