### ISSUE TITLE
<details> element, open attribute

### ISSUE THREAD

**Issue by davanT420** [mdn/content#34086]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

### What specific section or headline is this issue about?

open attribute

### What information was incorrect, unhelpful, or incomplete?

The following note:

Note: You have to remove this attribute entirely to make the details hidden. open="false" makes the details visible because this attribute is Boolean.

is not correct. You do not need to remove this attribute, but you have to set it to false, as in open=false (and not open = String(false), like in the example).

### What did you expect to see?

See above: the note is incorrect.

### Do you have any supporting links, references, or citations?

Tested on Iridium v116, 64 bit (a Chromium clone) and Firefox Version 123.0.1 (64-bit).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/details`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/details/index.md
* Last commit: https://github.com/mdn/content/commit/bd5e6a973f2706bb902ee915e751614d3a4af5aa
* Document last modified: 2024-06-11T09:53:22.000Z

</details>

**Comment by Josh-Cena** [comment]
Could you provide your HTML code?

There's nothing called `open = String(false)` in HTML. Are you writing in some other templating language?

**Comment by davanT420** [comment]
No, ofcourse there isn't: the note surrounds the false with double quotes, which you'd only do with strings, not with booleans.

**Comment by Josh-Cena** [comment]
There's no string or Boolean in HTML. Please read https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML.

**Comment by davanT420** [comment]
I see now: I was working with this attribute in javascript, dynamically setting open/close for the <details> tag.

**Comment by Josh-Cena** [comment]
I see. For JavaScript you should read https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement/open instead.

**Comment by davanT420** [comment]
Thanks for that piece of info -- the mistake lies with me: you can close that issue.Thanks again;On 12 Jun 2024, at 21:16, Joshua Chen ***@***.***> wrote:﻿
I see. For JavaScript you should read https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement/open instead.
