### ISSUE TITLE
Various Node subclass replaceWith methods should link to each other

### ISSUE THREAD

**Issue by jeremyredhead** [mdn/content#34084]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceWith

### What specific section or headline is this issue about?

See also

### What information was incorrect, unhelpful, or incomplete?

the pages aren't very well interlinked

### What did you expect to see?

the pages be interlinked

### Do you have any supporting links, references, or citations?

[Element.replaceWith][] does not mention CharacterData.replaceWith or DocumentType.replaceWith
[DocumentType.replaceWith][] does not mention CharacterData.replaceWith
[CharacterData.replaceWith][] does not mention Element.replaceWith or DocumentType.replaceWith

[Element.replaceWith]: https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceWith#see_also
[DocumentType.replaceWith]: https://developer.mozilla.org/en-US/docs/Web/API/DocumentType/replaceWith#see_also
[CharacterData.replaceWith]: https://developer.mozilla.org/en-US/docs/Web/API/CharacterData/replaceWith#see_also

### Do you have anything more you want to share?

the [Node.replaceChild](https://developer.mozilla.org/en-US/docs/Web/API/Node/replaceChild#oldchild) docs mention/suggest using [Element.replaceWith()](https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceWith) instead, but don't mentioned CharacterData.replaceWith or DocumentType.replaceWith, and b/c those pages don't link to each other either, this led to me concluding that replaceWith was not usable in all practical situations until i did more research, when in fact it is, and replaceWith is very awesome and cool

**Comment by Josh-Cena** [comment]
We should do the same for other `ChildNode` methods, including `before`, `after`, and `remove`.
