### ISSUE TITLE
terms "this", "target", "recipient", "window", "origin" appear indistinctly used

### ISSUE THREAD

**Issue by u-an-i** [mdn/content#34090]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

### What specific section or headline is this issue about?

multiple

### What information was incorrect, unhelpful, or incomplete?

> [targetOrigin](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#targetorigin) Optional
Specifies what the origin of this window must be for the event to be dispatched,

"this"

> Any window (including, for example, http://evil.example.com) can send a message to any other window

"window"

### What did you expect to see?

depending on what is really meant, I expected to see "this" replaced by "the intended recipient" and "window" replaced by "contentWindow within the iframe hierarchy from top to every iframe below of the current document"

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

"window": can a post occur to another tab? another users PC's tab? a server? any browser's having the same document open?

how is targetOrigin safety? If the iframe src can be changed away while posting to its contentWindow or the to-be-sender's page is copied and run on a malicious host, that host can simply replace the text inside the JavaScript code of postMessage.

postMessage operates on a contentWindow already obtained. It is not BroadcastChannel.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/postmessage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/postmessage/index.md
* Last commit: https://github.com/mdn/content/commit/45fdc5d8cce894088d4c270b8f160841ecb11a2a
* Document last modified: 2024-04-26T17:21:55.000Z

</details>

**Comment by Ashish-CodeJourney** [comment]
> ### MDN URL
> https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
> 
> ### What specific section or headline is this issue about?
> multiple
> 
> ### What information was incorrect, unhelpful, or incomplete?
> > [targetOrigin](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#targetorigin) Optional
> > Specifies what the origin of this window must be for the event to be dispatched,
> 
> "this"
> 
> > Any window (including, for example, http://evil.example.com) can send a message to any other window
> 
> "window"
> 
> ### What did you expect to see?
> depending on what is really meant, I expected to see "this" replaced by "the intended recipient" and "window" replaced by "contentWindow within the iframe hierarchy from top to every iframe below of the current document"
> 
> ### Do you have any supporting links, references, or citations?
> no
> 
> ### Do you have anything more you want to share?
> "window": can a post occur to another tab? another users PC's tab? a server? any browser's having the same document open?
> 
> how is targetOrigin safety? If the iframe src can be changed away while posting to its contentWindow or the to-be-sender's page is copied and run on a malicious host, that host can simply replace the text inside the JavaScript code of postMessage.
> 
> postMessage operates on a contentWindow already obtained. It is not BroadcastChannel.
> 
> ### MDN metadata
> Page report details

Raised a PR related to the same Please check
https://github.com/mdn/content/pull/34114

Check Preview here
https://pr34114.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Window/postMessage

**Comment by u-an-i** [comment]
@Ashish-CodeJourney i thank you. i added a "review".
