### ISSUE TITLE
Issue with "Match patterns in extension manifests": (short summary here please)

### ISSUE THREAD

**Issue by AbuseCRole** [mdn/content#3409]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/match_patterns`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/match_patterns/index.html
* Last commit: https://github.com/mdn/content/commit/3e5d8947cf03d1ae758aff8926c04c38eca2db2a
* Document last modified: 2021-02-01T10:33:54.000Z

</details>

**Comment by caitmuenster** [comment]
Hi @AbuseCRole, this issue needs more information to be actionable.
