### ISSUE TITLE
Typo error in If-Modified-Since page makes content seem seem wrong and/or confusing

### ISSUE THREAD

**Issue by jonhelfman** [mdn/content#34123]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since

### What specific section or headline is this issue about?

last sentence of first paragraph

### What information was incorrect, unhelpful, or incomplete?

This line seems wrong: Unlike [If-Unmodified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Unmodified-Since), If-Modified-Since can only be used with a [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) or [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD).

### What did you expect to see?

One of the 'If-Modified-Since' terms should be 'Last-Modified-Since' for the sentence to make sense. But it isn't clear which one should be changed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/if-modified-since`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/if-modified-since/index.md
* Last commit: https://github.com/mdn/content/commit/0880a90f3811475d78bc4b2c344eb4146f25f66c
* Document last modified: 2023-04-10T19:47:15.000Z

</details>

**Comment by Josh-Cena** [comment]
The first one says "If-Unmodified-Since". What's confusing?

**Comment by low-perry** [comment]
@jonhelfman I think, there is nothing wrong with the statement. It just making a comparison, and stating the fact that, `If-Modified-Since` can only be used with a `GET` or `HEAD`method.
[Read this](https://www.w3.org/Protocols/HTTP/HTRQ_Headers.html#if-modified-since).

**Comment by jonhelfman** [comment]
It seems to be comparing A with A, which doesn't make sense. The expectation is that A would be compared with B, right?

**Comment by jonhelfman** [comment]
OK. Nevermind. I realize now that I was misreading the text. My bad. Sorry for the problem.
