### ISSUE TITLE
Service Workers are no longer a requirement for PWA installation

### ISSUE THREAD

**Issue by FormularSumo** [mdn/content#34124]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Installable_PWAs

### What specific section or headline is this issue about?

Requirements

### What information was incorrect, unhelpful, or incomplete?

It used to be the case that for Chromium-based browsers a Service Worker needed to be registered in order for a PWA to be installable, but this requirement was removed around a year ago. You can find the current list of requirements here https://web.dev/articles/install-criteria. In Safari and Firefox, Service Workers have never been required for a PWA to be installable, so it's not longer the case that any browser requires this.

### What did you expect to see?

Service Workers not to be mentioned as a requirement

**Comment by Ashish-CodeJourney** [comment]
> ### MDN URL
> https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Installable_PWAs
> 
> ### What specific section or headline is this issue about?
> Requirements
> 
> ### What information was incorrect, unhelpful, or incomplete?
> It used to be the case that for Chromium-based browsers a Service Worker needed to be registered in order for a PWA to be installable, but this requirement was removed around a year ago. You can find the current list of requirements here https://web.dev/articles/install-criteria. In Safari and Firefox, Service Workers have never been required for a PWA to be installable, so it's not longer the case that any browser requires this.
> 
> ### What did you expect to see?
> Service Workers not to be mentioned as a requirement
> 
> ### Do you have any supporting links, references, or citations?
> _No response_
> 
> ### Do you have anything more you want to share?
> _No response_

Raised a PR related to the same 
https://github.com/mdn/content/pull/34155

Check previews here
https://pr34155.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging
https://pr34155.content.dev.mdn.mozit.cloud/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Installable_PWAs
