### ISSUE TITLE
MIME type for JPG is not image/jpeg, it is image/jpg

### ISSUE THREAD

**Issue by cellog** [mdn/content#34128]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

### What specific section or headline is this issue about?

JPEG mime type

### What information was incorrect, unhelpful, or incomplete?

in all current browsers, when uploading a jpeg or jpg, the browser reports its mime type to the server as `image/jpg`, not `image/jpeg`

### What did you expect to see?

the correct MIME type

### Do you have any supporting links, references, or citations?

<img width="777" alt="image" src="https://github.com/mdn/content/assets/98250/0ed9e2dc-3171-4081-bac4-368e91d951ca">

**Comment by Josh-Cena** [comment]
https://stackoverflow.com/questions/33692835/is-the-mime-type-image-jpg-the-same-as-image-jpeg

Could you give an example of `image/jpg`?

**Comment by cellog** [comment]
correction: this is a bug in Ruby on Rails, not in MDN
