### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by JamesHertz** [mdn/content#34136]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors

### What specific section or headline is this issue about?

Pseudo-classes and pseudo-elements

### What information was incorrect, unhelpful, or incomplete?

When talking about pseudo-elements it uses double colon (`::`) but that's incorrect.

### What did you expect to see?

If you look at this other [link from mozzila](https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child) and if you write some css you will see clearly it's not a double colon (`::`) but a single colon (`:`).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by Josh-Cena** [comment]
Double colon is for pseudo-elements. Single colon is for pseudo-classes. They are not the same.
