### ISSUE TITLE
Issue with "CanvasRenderingContext2D.createConicGradient()": (short summary here please)

### ISSUE THREAD

**Issue by sinafap** [mdn/content#3417]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createConicGradient

#### What information was incorrect, unhelpful, or incomplete?
 image doesn't show

#### Specific section or headline?
Examples

#### What did you expect to see?
an image

#### Did you test this? If so, how?
no

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/createconicgradient`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createConicGradient
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/createconicgradient/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by chrisdavidmills** [comment]
@sinafap do you mean the image under "Rectangle result"? I can see it fine.

This feature does have [limited browser support](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createConicGradient#browser_compatibility); you may well be using a non-supporting browser.
