### ISSUE TITLE
Number.prototype.toString() on numbers that CAN be represented in float64 but not exactly in toString()

### ISSUE THREAD

**Issue by ArchivingToolsForWBM** [mdn/content#34180]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString

### What specific section or headline is this issue about?

Did not mention that toString() may round a number DESPITE the value can be represented in 64-bit double precision floats

### What information was incorrect, unhelpful, or incomplete?

On this article about [toFixed()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) when set to have 0 decimal digits, it represents some representable float64 values that ``toString()`` cannot:
```
1000000000000000128).toString(); // '1000000000000000100'
(1000000000000000128).toFixed(0); // '1000000000000000128'
```

That should be mentioned in ``Number.prototype.toString()`` article that there are numbers that can be represented in double-precision but not so using ``.toString(10)``

### What did you expect to see?

It must mention what the toFixed() article states about toFixed vs toString

**Comment by Josh-Cena** [comment]
@ArchivingToolsForWBM While you are correct that `1000000000000000128 === 1000000000000000100`, `1000000000000000128` is the precise representation of the float value. It's still worth documenting that `toString` does not use this precise representation.
