### ISSUE TITLE
Document Storage Buckets API

### ISSUE THREAD

**Issue by neila-a** [mdn/content#34185]
The [Storage Buckets API](https://github.com/WICG/storage-buckets) is now implemented in Microsoft Edge 127 (not tested in other browsers), and I think it should be added to MDN.

**Comment by Josh-Cena** [comment]
Hi! I'm closing all issues that are in https://openwebdocs.github.io/web-docs-backlog/all/. These features are automatically in our backlog and don't need separate issues to track.
