### ISSUE TITLE
Palpable content on the Content category page is somewhat incomplete.

### ISSUE THREAD

**Issue by low-perry** [mdn/content#34199]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories

### What specific section or headline is this issue about?

https://html.spec.whatwg.org/multipage/dom.html#palpable-content

### What information was incorrect, unhelpful, or incomplete?

The [palpable content](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#palpable_content) does not include a list of elements that belong to that category.

### What did you expect to see?

It would be nice to add some example elements that are considered to be [palpable](https://html.spec.whatwg.org/multipage/dom.html#palpable-content) such as `<a>`, `<address>`, `<article>`, `<audio>` etc.

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/dom.html#palpable-content

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/content_categories`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/content_categories/index.md
* Last commit: https://github.com/mdn/content/commit/542c81306d3c34c32aabbf57a7a5d2c3b97b2d4c
* Document last modified: 2024-06-05T06:48:56.000Z

</details>

**Comment by pepelsbey** [comment]
Hey! Good catch :) This section is surely missing some examples of elements in this category.

If you’re up to it, please go ahead and suggest a PR adding this info. Otherwise, someone from the community will pick it up.

**Comment by low-perry** [comment]
Sure i got it!
