### ISSUE TITLE
Issue with "JavaScript modules": missing a section on where modules meet top-level scope of web pages

### ISSUE THREAD

**Issue by ajvincent** [mdn/content#342]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

#### What information was incorrect, unhelpful, or incomplete?

Something that isn't clear about ES6 modules is how to connect between values a module defines and web globals like _window_, _document_, etc.  It's not immediately obvious which globals are available, and how to safely adjust a module so that if it loads in a non-browser environment, everything still works.

For example, in the referenced basic_modules/modules/canvas.js file, the _create()_ function references the document global.  I would expect if I loaded this module in a nodejs environment that I couldn't execute the create() function (unless I was using jsdom or something similar).

I'm really looking for best practices regarding modules that depend on a DOM being present versus modules that are independent of having a DOM.  

One of my own modules has this block of code after the export lines defining these values:
```javascript
export function cloneNodesContentsOnly(node) {
  // ...
}

if (typeof window === "object") {
  window.cloneNodesContentsOnly = cloneNodesContentsOnly;
  // ...
}
```

If it was documented that this is preferable, fine.  If the recommendation is to put these window property definitions in another module script that imports the DOM-independent module, fine.  I'm just not sure what's a good practice versus a bad practice.

#### Specific section or headline?

I think this needs to be a new section adjacent to "Browser Support".

#### What did you expect to see?

* A general guidance on globals exposed to modules beyond the ECMAScript standard
  * NodeJS
  * Web browser environments  
  * A list of the kinds of globals exposed (window, document, etc.) - but not necessarily all of them
* Best practices on exposing modules' exports as properties of the window global
* Best practices on separating web-dependent module exports from web-agnostic module exports

#### Did you test this? If so, how?

Only minimally using NodeJS, Puppeteer and Firefox.  I have a pet project which has several (but not many, yet) JavaScript components, and a dependency on the order of script loading, so using ES6's import mechanisms would be very convenient.  

Also, I want to develop modules that don't necessarily rely on the DOM, so I can unit-test them without going through Puppeteer.  Then I want to know how to safely expose their defined values to web pages loading those modules.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/modules`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/guide/modules/index.html
* Report started: 2020-12-17T05:26:11.941Z

</details>

**Comment by Ryuno-Ki** [comment]
@ajvincent As a starting point, you could look for Best Practices regarding „isomorphic JavaScript”. That is, JavaScript that can run both, on a server as well as inside a browser.

Some bundlers might convert code into „UMD” (Universal Module Definition), so it can be loaded via `require` (= CommonJS), `define` (= AMD) or `import (ES module).

**Comment by Josh-Cena** [comment]
I have thought about it in the past few weeks—no great ideas at the moment, my thoughts are a bit all over the place. I can definitely take a look and at least write something about it.

**Comment by sideshowbarker** [comment]
> I have thought about it in the past few weeks—no great ideas at the moment, my thoughts are a bit all over the place. I can definitely take a look and at least write something about it.

Excellent — that’d be great. I’ll go ahead and assign it to you, but if at any time you decide you still want it on your plate, feel free to un-assign it.

**Comment by ajvincent** [comment]
Thank you very much for this.
