### ISSUE TITLE
OGG video format does not fallback on chrome desktop

### ISSUE THREAD

**Issue by michael-harvey** [mdn/content#34217]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#multiple_sources

### What information was incorrect, unhelpful, or incomplete?

On Chrome desktop the video format fallback example doesn't fallback to another video format as intended. 

Chrome has deprecated the ogg video format but still supports ogg audio. This leads to just audio playing rather than the video falling back to another format source.

### What did you expect to see?

I expected the video to fail to play the ogg format, and fallback to the alternative sources provided, video/avi or video/mp4.

### Do you have any supporting links, references, or citations?

Chrome platform deprecation notice
https://chromestatus.com/feature/5158654475239424

Ogg Vorbis audio format browser support
https://caniuse.com/ogv

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/video`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/video/index.md
* Last commit: https://github.com/mdn/content/commit/bde0cb215d1d307c08678abe6623fc0d39f4cf7f
* Document last modified: 2024-06-14T19:00:31.000Z

</details>

**Comment by FormularSumo** [comment]
I've just been doing my own research on Theora's removal from Chromium and Firefox, and come across this. I've opened [an issue](https://github.com/Fyrd/caniuse/issues/7104) on the caniuse repo with all the info but TLDR I don't think any Chromium browsers support Theora playback anymore, and Firefox is in the process of removing it. As well as the PR linked above there's a couple other pages which reference browser support for Theora which are in need of updating now.

There might be more, but the two pages I've come across are https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#theora and https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content#using_multiple_source_formats_to_improve_compatibility. They both pretty much need updating to say that Theora probaly shouldn't be used now, including updating the browser compatiblity and pointing towards modern alternatives (like VP9/AV1). The second article should probably also mention AV1 alongside the webm container but that's perhaps a separate issue.

**Comment by FormularSumo** [comment]
Would it be possible to re-open this issue until the other outdated Theora pages have been updated, perhaps changing the name of the issue to be a bit less specific? If not I can open a new one it just makes sense to track it in one place I think.

**Comment by FormularSumo** [comment]
@chrisdavidmills pinging in case you missed this
