### ISSUE TITLE
Hoisting Type 3 behavior inconclusive

### ISSUE THREAD

**Issue by alimalim77** [mdn/content#34219]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

### What specific section or headline is this issue about?

Issue related to Types of Hoisting Behavior

### What information was incorrect, unhelpful, or incomplete?

On completion of overview of Hoisting, there are four types of behavior in hoisting, the third behavior is explained as: _The declaration of the variable causes behavior changes in its scope before the line in which it is declared._ 

### What did you expect to see?

It makes it confusing to understand what declaration is being discussed, the initial and previous one and also there is no mention of temporal dead zone which seems okay if it is discussed later.

### Do you have any supporting links, references, or citations?

It should be self-explanatory on what part of code is talked here especially talking about TDZ would be more appropriate here in case of let, const and class instead of introducing them later.

**Comment by Josh-Cena** [comment]
We are trying to be as general as possible and not be solely confined to lexical declarations. Lexical declarations affect the scope by preventing the variable from being used before its declaration, as discussed later. It could well be that other declarations show other kind of "scope tainting".
