### ISSUE TITLE
POST requests and 301/302 status codes

### ISSUE THREAD

**Issue by rafaelgieschke** [mdn/content#34222]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301

### What information was incorrect, unhelpful, or incomplete?

The sentence "Even if the specification requires the method (and the body) not to be altered when the redirection is performed, not all user-agents conform here - you can still find this type of bugged software out there." on https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302 and the similar sentence "Note: Although the [specification](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301#specifications) requires the method and the body to remain unchanged when the redirection is performed" on https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301 are plainly wrong nowadays.

### What did you expect to see?

The Fetch Standard [requires](https://fetch.spec.whatwg.org/#ref-for-concept-response-status%E2%91%A0%E2%91%A2) user agents to change the method to `GET` (iff it originally was `POST`), the HTTP specification [permits ("MAY")](https://www.rfc-editor.org/rfc/rfc9110#status.302) them to do so.

### Do you have any supporting links, references, or citations?

- https://fetch.spec.whatwg.org/#ref-for-concept-response-status%E2%91%A0%E2%91%A2
- https://www.rfc-editor.org/rfc/rfc9110#status.302
- https://www.rfc-editor.org/rfc/rfc9110#status.301

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/301`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/301/index.md
* Last commit: https://github.com/mdn/content/commit/0880a90f3811475d78bc4b2c344eb4146f25f66c
* Document last modified: 2023-04-10T19:47:15.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting this. The linked PR resolves this issue if you want to have a look at the changes.
