### ISSUE TITLE
Issue with "Images in HTML": (The Code is not Hightlighted)

### ISSUE THREAD

**Issue by MenaiAla** [mdn/content#3423]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML

#### What information was incorrect, unhelpful, or incomplete?

The code should be highlighted.

#### Specific section or headline?

[Annotating images with figures and figure captions](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML#annotating_images_with_figures_and_figure_captions)

#### What did you expect to see?

Highlited code like the above one.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/images_in_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by rachelandrew** [comment]
Thanks for the report @MenaiAla I've just submitted a PR which will fix this.
