### ISSUE TITLE
Restore paragraph on Web Storage API page about old versions of Safari

### ISSUE THREAD

**Issue by RudeySH** [mdn/content#34248]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API#private_browsing_incognito_modes

### What specific section or headline is this issue about?

Private Browsing / Incognito modes

### What information was incorrect, unhelpful, or incomplete?

Before May 26 2023, the "Private Browsing / Incognito modes" section used to contain a paragraph about various strategies that browsers have in regards to storage APIs, and how older versions of Safari made storage available but impossible to write to. The paragraph was removed in #26796, but I am arguing that this should not have been removed.

### What did you expect to see?

Most of the information that was present in the removed paragraph is still useful information today. I would suggest restoring the paragraph, or perhaps moving it to [Storage quotas and eviction criteria](https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#private_browsing). Here's the exact paragraph text:

> Most browsers have opted for a strategy where storage APIs are still available and seemingly fully functional, with the one big difference that all stored data is wiped after the browser is closed. For these browsers there are still different interpretations of what should be done with existing stored data (from a regular browsing session). Should it be available to read when in Private mode? Then there are some browsers, most notably old versions of Safari, that have opted for a solution where storage is available, but is empty and has a quota of 0 bytes assigned, effectively making it impossible to write data to it.

I've read through the conversation in the PR (#26796) in which the paragraph was removed. I believe the paragraph was removed because of either of these two reasons:
- The paragraph is no longer applicable to newer versions of Safari.
- There is a different page on MDN about storage quotas that includes a short section about private browsing. (https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#private_browsing)

However, I don't think these were good reasons.
- While it is true that newer versions of Safari works differently, this paragraph was always about **older** versions of Safari. It is still useful information for those who need to support older browsers.
- The page about storage quotas mentions private browsing, but does not explicitly mention (for example) that it is impossible to write data to storage in older versions of Safari. Perhaps it was the plan of the author(s) to move the deleted paragraph to the page about storage quotas, but that never happened.

**Comment by wbamberg** [comment]
On MDN we have a policy of not documenting things that have not been supported by browsers for >2 years, because otherwise there are so many old/obsolete behaviors and features that the docs would become unmanageable.

Do you know how old the "older versions of Safari" are?

**Comment by RudeySH** [comment]
I think the issue affects Safari 10 and earlier. Safari 11 came out 7 years ago.

**Comment by Josh-Cena** [comment]
Okay; that seems too old to fit MDN's document policy.

Safari's also special in this regard because Apple is somewhat aggressive at pushing users to update. Safari is strongly coupled to the OS version and once the OS stops being maintained it's safe to assume that you don't need to support that Safari version because those users are already on their own. Since even Big Sur is now EOL, I don't think we should continue to maintain documentation for Safari 10.
