### ISSUE TITLE
Change word whitelist -> allowlist

### ISSUE THREAD

**Issue by JohnLindahlTech** [mdn/content#34249]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

### What specific section or headline is this issue about?

whitelisting_external_scripts_using_hashes

### What information was incorrect, unhelpful, or incomplete?

Usage of the word whitelist

### What did you expect to see?

Usage of the word allowlist

### Do you have any supporting links, references, or citations?

Prior discussions was held in https://github.com/mdn/content/pull/7396

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/script-src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/script-src/index.md
* Last commit: https://github.com/mdn/content/commit/8685d6ebfdb0450c46454ee715cafaa53317a4e2
* Document last modified: 2023-10-19T09:27:24.000Z

</details>

**Comment by Josh-Cena** [comment]
Welcoming another search&replace

**Comment by DanielVenable** [comment]
I could do this. Can you assign me?
