### ISSUE TITLE
Document writeValueWithResponse() and writeValueWithoutResponse() methods of BluetoothRemoteGATTCharacteristic

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/content#3426]
`BluetoothRemoteGATTCharacteristic` has `writeValue()` method that’s now deprecated and that’s essentially been replaced by `writeValueWithResponse()` and `writeValueWithoutResponse()` methods:

https://webbluetoothcg.github.io/web-bluetooth/#ref-for-dom-bluetoothremotegattcharacteristic-writevaluewithresponse①

However, at MDN we don’t yet have articles for those methods.

**Comment by wbamberg** [comment]
Also remember to update https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValue when we have something to point it at.

**Comment by wbamberg** [comment]
This seems to have been fixed by https://github.com/mdn/content/pull/6436 .
