### ISSUE TITLE
MouseEvent: movementX shown as limited availability in Baseline despite wide support

### ISSUE THREAD

**Issue by manngo** [mdn/content#34263]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementX

### What specific section or headline is this issue about?

The Baseline

### What information was incorrect, unhelpful, or incomplete?

The Baseline

### What did you expect to see?

According to the Browser Compatibility chart, every major browser has supported this feature for close to a decade. Should the baseline be updated to reflect this?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mouseevent/movementx`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementX
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mouseevent/movementx/index.md
* Last commit: https://github.com/mdn/content/commit/a4d1cfeb99732a7e883409da26e4343a161ef304
* Document last modified: 2024-01-15T09:46:58.000Z

</details>

**Comment by bsmth** [comment]
Thanks for filing this. The individual feature has wide support, but is part of a feature group (`pointer-lock`) that does not: https://github.com/mdn/browser-compat-data/blob/5810bdd95efc1d1a4bfb06a9f1b4c2ac9ed2170d/api/MouseEvent.json#L560

CCing @foolip and @ddbeck for a look 👀

**Comment by ddbeck** [comment]
The point lock spec defined `movement{X,Y}` so there were swept up into that feature—which has a much more complex support situation than using the properties alone.

I've filed https://github.com/web-platform-dx/web-features/pull/1263 to add a new "mouse events" feature that will correct the record for this.

**Comment by Josh-Cena** [comment]
Closing for now, since it's not a content issue and we have the PR already.
