### ISSUE TITLE
 "rect()" function does not show any image

### ISSUE THREAD

**Issue by manav-sharma69** [mdn/content#34270]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

No image is rendered when "rect()" method is selected for clip-path. 
![rect_not_working](https://github.com/mdn/content/assets/157268750/671dfaf8-5a3d-4fa3-98b7-07a7531984de)

### What did you expect to see?

Expected to see an image with some applied effects of `clip-path` property.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/clip-path`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/clip-path/index.md
* Last commit: https://github.com/mdn/content/commit/8cd08162e592c1baf5d888f4c5a08a58360344b5
* Document last modified: 2024-05-27T15:46:50.000Z

</details>

**Comment by Josh-Cena** [comment]
Hello, please check https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/rect#browser_compatibility: Chrome doesn't support `rect` as `clip-path`. The example works in Firefox.
