### ISSUE TITLE
ByteLengthQueuingStrategy constructor syntax should match guidelines

### ISSUE THREAD

**Issue by johntalton** [mdn/content#34282]
The constructor to the `ByteLengthQueuingStrategy` looks to reference `highWaterMark` directly (as if a number type).

Where it is likely `QueuingStrategyInit` (or colloquial `{ highWaterMark }`) was the intention.

[https://streams.spec.whatwg.org/#blqs-class-definition](https://streams.spec.whatwg.org/#blqs-class-definition)

here:
https://developer.mozilla.org/en-US/docs/Web/API/ByteLengthQueuingStrategy/ByteLengthQueuingStrategy

this may be a common shorthand for all the queuing strategy pages?
https://developer.mozilla.org/en-US/docs/Web/API/CountQueuingStrategy/CountQueuingStrategy

thanks for you time

**Comment by Josh-Cena** [comment]
Are you suggesting that the parameter should not be called `highWaterMark` in the syntax box?

**Comment by johntalton** [comment]
I think using the colloquial version is fine - most people don't consider the `QueuingStrategyInit` "type" thingy anyways...

so i was expecting:  
```
new ByteLengthQueuingStrategy({ highWaterMark })
```
(see the added `{` and `}` :) )

With the wording shuffled to indicate it is a parameter of the options, and not of the constructor itself.

**Comment by Josh-Cena** [comment]
That would not be how we write syntax boxes. It would look like this:


And then:

~~~md
## Syntax

```js
new ByteLengthQueuingStrategy(options)
```

### Parameters

- `options`
  - : An object with the following property:
    - `highWaterMark`
      - : Description
~~~
