### ISSUE TITLE
Missing `view-transition-class` content

### ISSUE THREAD

**Issue by cssinate** [mdn/content#34288]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/view-timeline

### What information was incorrect, unhelpful, or incomplete?

URL above isn'taccurate. There should be a new article under `view-*` called `view-transition-class` based on the [view-transition-class prop in the view-transitions-2 module](https://www.w3.org/TR/css-view-transitions-2/#view-transition-class-prop). This is a working draft, and the property is working in Chrome/Edge.

### What did you expect to see?

See above

### Do you have any supporting links, references, or citations?

- https://www.w3.org/TR/css-view-transitions-2/#view-transition-class-prop
- https://developer.chrome.com/docs/web-platform/view-transitions/same-document#view-transition-class

**Comment by Josh-Cena** [comment]
Are there related features in the new spec we might be missing? From a quick eyeball we could be missing a few.

**Comment by OnkarRuikar** [comment]
The BCD entry does exist https://github.com/mdn/browser-compat-data/blob/main/css/properties/view-transition-class.json

**Comment by Josh-Cena** [comment]
Hi! I'm closing all issues that are in https://openwebdocs.github.io/web-docs-backlog/all/. These features are automatically in our backlog and don't need separate issues to track.
