### ISSUE TITLE
Setting body element color doesn't override the default anchor tag color

### ISSUE THREAD

**Issue by kelvinmacharia254** [mdn/content#34294]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

### What specific section or headline is this issue about?

Controlling inheritance

### What information was incorrect, unhelpful, or incomplete?

` body {
color: green;
}`

### What did you expect to see?

From the example given on controlling inheritance. The links turns green giving a notion that changing color of the body automatically overrides the color of the children anchor tags. I expect the anchors to retain the color blue which is the default unless the inheritance is explicitly set.

### Do you have any supporting links, references, or citations?

I tried the code out as it is in the example and it didn't  work as per example's expectations and I made this conclusion.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.md
* Last commit: https://github.com/mdn/content/commit/4bddde3e2b86234eb4594809082873fc5bf00ee3
* Document last modified: 2024-01-01T12:19:59.000Z

</details>

**Comment by Josh-Cena** [comment]
> I tried the code out as it is in the example and it didn't work as per example's expectations

We have a hosted example right there that shows the intended effect. Does your own experiment show something different, or are you just confused by why it looks that way?

**Comment by kelvinmacharia254** [comment]
Just  had a closer look and I was actually confused. Part of learning. The
content is perfect. Apologies for raising unnecessary issues.
Next time will take my time to understand deeper and raise issues then.

*Kind Regards,*
*Kelvin Macharia*
