### ISSUE TITLE
Remove 2 links to yari-demos.prod.mdn.mozit.cloud

### ISSUE THREAD

**Issue by caugner** [mdn/content#34326]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event#window_size_logger

### What specific section or headline is this issue about?

Window size logger

### What information was incorrect, unhelpful, or incomplete?

There are two links to `yari-demos.prod.mdn.mozit.cloud`, which is now decommissioned: https://github.com/search?q=org%3Amdn+yari-demos+repo%3Amdn%2Fcontent&type=code

The other occurence is in the Writing guidelines and suggests to use these links:  https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples#grouping_code_blocks

### What did you expect to see?

The links may be replaced by something like this: https://live.mdnplay.dev/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples/_sample_.grouping_code_blocks_by_heading.html?id=grouping_code_blocks_by_heading&amp;url=%2Fen-US%2Fdocs%2FMDN%2FWriting_guidelines%2FPage_structures%2FLive_samples

**Comment by Josh-Cena** [comment]
The window size logger link should be replaced with the `LiveSampleLink` macro (proof of why this macro is useful).
