### ISSUE TITLE
calc-constant renamed to calc-keyword

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#34348]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/calc-constant

### What information was incorrect, unhelpful, or incomplete?

There's no Formal syntax for this page (part of https://github.com/mdn/content/issues/18780), because "calc-constant" isn't a thing the spec talks about.

### What did you expect to see?

The spec talks about two things:

- `<calc-keyword>`, which includes `e`, `pi`, `infinity`, `-infinity`, `NaN` (i.e. what the page talks about)
- `#calc-constants` (as an anchor), which only includes `e` and `pi`

Our formal syntax for `calc()` already gives the definition for `calc-keyword`, so maybe that should be the title of the page.

### Do you have any supporting links, references, or citations?

WebRef has `<calc-keyword>`; https://drafts.csswg.org/css-values/#calc-syntax

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/calc-constant`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/calc-constant
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/calc-constant/index.md
* Last commit: https://github.com/mdn/content/commit/fb1c7f8985e4c4142f482f809366e3cba6b96b94
* Document last modified: 2023-05-25T14:11:05.000Z

</details>

**Comment by wbamberg** [comment]
It was renamed in https://github.com/w3c/csswg-drafts/commit/5da0b7eec74efc032c8c4d1d0727538b88b53075 apparently.
