### ISSUE TITLE
Issue with "Recording a media element": (short summary here please)

### ISSUE THREAD

**Issue by hanlonjimmy** [mdn/content#3437]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Recording_a_media_element

#### What information was incorrect, unhelpful, or incomplete?
in the result, section the link   **"take a look at all the code"**  links to 

https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/MediaStream_Recording_API/Recording_a_media_element/_samples_/Example

#### Specific section or headline?
Result 

#### What did you expect to see?
link to the code  

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediastream_recording_api/recording_a_media_element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Recording_a_media_element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediastream_recording_api/recording_a_media_element/index.html
* Last commit: https://github.com/mdn/content/commit/11a98a59fca5f2e448d9e4b70e3c8a538c47b201
* Document last modified: 2021-02-19T19:45:18.000Z

</details>

**Comment by Rumyra** [comment]
To whoever fixes this issue, it looks like the following is needed:

* Make sure 'take a look at all the code link' under the Result header links to the source code
* Keep the link to the demo, but label it correctly e.g 'here is the code running'

**Comment by nayaldivya** [comment]
Hi @Rumyra, I've to keep the link same but change the label from"take a look at all the code" to "here is the code running". This is my understanding of your comment.  Please correct me if I'm wrong.

**Comment by Rumyra** [comment]
Yes @nayaldivya - we usually have two links: One to the source code and one to the working demo.

A good example is here https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_Web_Audio_API - underneath the first image of the boombox there's a 'Check out the demo' link _and_ 'see the source code'.

Applying something similar to the above page would solve the issue and improve 👍

**Comment by nayaldivya** [comment]
Thanks for the feedback @Rumyra. I'll try to fix and improve the issue upto my best capabilities.

**Comment by nayaldivya** [comment]
Hi @Rumyra, sorry for disturbing again but I didn't find any repository containing the code mentioned in the issue. Can you please help me with it.

**Comment by Rumyra** [comment]
My apologies @nayaldivya I have dug into this a bit further and I think my instructions were misleading. The demo is being generated from the code within the page, rather than held in a separate repository.

While I do think that demo should be in the dom-examples repo https://github.com/mdn/dom-examples - I also think that's out of scope for this issue.

Instead I would change the line in question to:

```
<p>You can {{LiveSampleLink("Example", "view the full demo here")}}, and use your browsers developer tools to inspect the page and look at all the code, including the parts hidden above because they aren't critical to the explanation of how the APIs are being used.</p>
```

I hope that helps :)

**Comment by nayaldivya** [comment]
Thank you so much @Rumyra for the guidance.

**Comment by Rumyra** [comment]
Thank _you_ so much @nayaldivya for your help 🙌
