### ISSUE TITLE
MongoServerError: Invalid namespace specified 'local_library/.genres'

### ISSUE THREAD

**Issue by SillyBorbo** [mdn/content#34388]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

### What specific section or headline is this issue about?

Testing - Create Some Items

### What information was incorrect, unhelpful, or incomplete?

Followed the tutorial exactly. When trying to run `node populatedb <mongodb url>`, I get the error "MongoServerError: Invalid namespace specified 'local_library/.genres" (code: 73). I'm very new to this and don't know what the problem is. I copy-pasted all of the code to ensure that I didn't mistype anything. And yes, I followed the steps to set up mongodb cloud.

### What did you expect to see?

The script should complete without error.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/bbac122a6c93af0df62f51ec87f6955869901602
* Document last modified: 2024-03-27T08:03:37.000Z

</details>

**Comment by hamishwillee** [comment]
Did you do the challenge? https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#genre_model_-_challenge!

The error seems to indicate that mongodb doesn't know about genres so it is possibly you didn't do that bit?

The populate.db assumes you did (I might need to make that clear - this is something you have to do)

**Comment by SillyBorbo** [comment]
Yes, challenge was done. I edited populatedb.js to skip genres and it has the same error with authors. Maybe this is a networking issue with mongodb? I am doing this on my work computer. I also know next to nothing about networking.

**Comment by SillyBorbo** [comment]
I finally found the problem. My mongodb url looked like:
`...mongodb.net/local_library/?retryWrites=true...`
When I removed the "/" just before the "?"
`...mongodb.net/local_library?retryWrites=true...`
It worked. I guess it was just my mistyping.

**Comment by SillyBorbo** [comment]
Now that I notice it, the error message
`Invalid namespace specified 'local_library/.genres'`
actually shows the problem. I expect that the "/" after local_library wouldn't be there if genres truly didn't exist and I had typed the correct url.

**Comment by hamishwillee** [comment]
Glad you worked it out. Something for me to remember if I see the URL again.
