### ISSUE TITLE
Make attribute lists in HTML element pages link to attribute reference pages

### ISSUE THREAD

**Issue by milesatstetson** [mdn/content#34390]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

### What specific section or headline is this issue about?

Attributes - rel description

### What information was incorrect, unhelpful, or incomplete?

I think that the [rel](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#rel) should include a link to https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel ?

### What did you expect to see?

Either a listing of the rel property or link to the page that describes what the options are for the rel property.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/a`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/a/index.md
* Last commit: https://github.com/mdn/content/commit/bde0cb215d1d307c08678abe6623fc0d39f4cf7f
* Document last modified: 2024-06-14T19:00:31.000Z

</details>

**Comment by MadGanGithub** [comment]
Hey @milesatstetson, I would like to work on this issue

**Comment by Josh-Cena** [comment]
Actually I'm removing https://github.com/mdn/content/labels/good%20first%20issue here. We should not update this single occurrence; we should make all attribute lists in the element pages are linking to the attribute reference, if one exists. @MadGanGithub feel free to send a PR but the work should be more significant than a one-line change here.
