### ISSUE TITLE
Several CSSRule interfaces refer to now deprecated type attribute

### ISSUE THREAD

**Issue by rachelandrew** [mdn/content#344]
While working on `CSSPropertyRule` I took a look at other already documented `CSSRule` interfaces, for example https://developer.mozilla.org/en-US/docs/Web/API/CSSPageRule

These refer in their summary to the type attribute which returns an integer depending on the page rule in question. This is now deprecated in the spec (https://drafts.csswg.org/cssom/#cssrule) and we should update these interfaces accordingly. I would suggest mentioning this somewhere in the body as a deprecated attribute.

The CSSRule page mentions the property https://developer.mozilla.org/en-US/docs/Web/API/CSSRule with no detail that it is deprecated. It also links to the information on the wiki which gives a message that this is now out of date: https://wiki.csswg.org/spec/cssom-constants

It would probably be worth reviewing them at the same time for any other changes in the spec.

cc: @jpmedley

**Comment by rachelandrew** [comment]
Having looked at this a bit more it seems that all that has been documented is the top level page for each interface so there are a whole bunch of missing subpages to create.

**Comment by jpmedley** [comment]
We sort of talked about this this morning. Your email made me realize that
this isn't quite covered.

   - The pages for the deprecated properties, methods, whatever, need to
   have the {{Deprecated_header}} macro at the top.
   - The BCD for those interface members needs to be updated to set
   deprecated equal to true.
   - On the interface page in the list of member definitions, add
   the {{deprecated_inline()}} macro in line with the member name. Put it
   after the {{readonlyInline}} macro.

And to reaffirm, please add the missing subpages.

Thank you for all of your help.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*
