### ISSUE TITLE
Issue with "DOM Property Viewer": incorrect keyboard shortcut for opening the viewer

### ISSUE THREAD

**Issue by lkintact** [mdn/content#3440]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/DOM_Property_Viewer

#### What information was incorrect, unhelpful, or incomplete?
There's a paragraph in the page:
`Once enabled, you can open the DOM Property Viewer by selecting "DOM" from the Web Developer submenu in the Firefox Menu Panel (or Tools menu if you display the menu bar or are on macOS), or by pressing its Ctrl + Shift + W keyboard shortcut.`,
but <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>w</kbd> closes the Firefox window, not opens the viewer.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/dom_property_viewer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/DOM_Property_Viewer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/dom_property_viewer/index.html
* Last commit: https://github.com/mdn/content/commit/23eebf57a003f8a933aad06436d78fe127f8223e
* Document last modified: 2021-02-02T16:49:47.000Z

</details>

**Comment by himanshugarg** [comment]
At least in/until Firefox 78, `Ctrl + Shft + W` was the suggested shortcut which, as documented on mdn and reported in this issue, closes the window:-
![image](https://user-images.githubusercontent.com/2392803/147685012-c94479ca-46e1-4fd7-8a6e-51042d557c48.png)

In Firefox 95, the menu has changed and the shortcut is gone.

**Comment by hamishwillee** [comment]
Yeah, this is a 5 year old bug caused by change to underlying platforms: https://bugzilla.mozilla.org/show_bug.cgi?id=1269509
It is still set as D in https://searchfox.org/mozilla-central/source/devtools/client/locales/en-US/startup.properties#187

I'll do a quick revision.
