### ISSUE TITLE
Minor issue: It should've been "height", not "width".

### ISSUE THREAD

**Issue by penguinness** [mdn/content#34408]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow

### What specific section or headline is this issue about?

"How are elements laid out by default?"

### What information was incorrect, unhelpful, or incomplete?

The example says "Because of margin collapsing, we are separated by the width of one of our margins, not both."

### What did you expect to see?

It should have been  "Because of margin collapsing, we are separated by the _height_ of one of our margins, not both."

### Do you have any supporting links, references, or citations?

The same document says "Collapsing margins is only relevant in the vertical direction.", which implies that heights collapse, not widths.

### Do you have anything more you want to share?

<img width="495" alt="image" src="https://github.com/mdn/content/assets/92165891/79c14c49-8a31-4527-afe1-faa48590c360">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/css_layout/normal_flow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/normal_flow/index.md
* Last commit: https://github.com/mdn/content/commit/289d6314f3368aa3e28524e7d090f6e9c704e3b1
* Document last modified: 2023-11-28T20:48:44.000Z

</details>

**Comment by Josh-Cena** [comment]
We should avoid saying either "width" or "height" because margins are one-dimensional things. I think "size" or "space" are fine.

**Comment by penguinness** [comment]
> We should avoid saying either "width" or "height" because margins are one-dimensional things. I think "size" or "space" are fine.

Yes, but margin collapse is only relevant in the vertical direction. Any word other than "height" in the context of margin collapse is confusing imo.
