### ISSUE TITLE
<meter> examples have confusing meter bars inline

### ISSUE THREAD

**Issue by PrimeLemur** [mdn/content#34413]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter

### What specific section or headline is this issue about?

Examples: Simple Example: HTML: first example shown

### What information was incorrect, unhelpful, or incomplete?

> I see:
![image](https://github.com/mdn/content/assets/132648930/5bdf9172-ec94-459c-a934-d4221ee32fe4)
This is the HTML from the example:

```html
<p>
  Heat the oven to <meter min="200" max="500" value="350">350 degrees</meter>.
</p>
```

### What did you expect to see?

I suspect the page author intended the example to render as:
![image](https://github.com/mdn/content/assets/132648930/5bef1238-c97e-4429-b82c-ff3abf20774a)
I produced this output by moving the closing tag:
```html
<p>
  Heat the oven to <meter min="200" max="500" value="350"></meter> 350 degrees.
</p>
```
This tag closure is more consistent with the 2nd example in the same section on the same page.
I'm not entirely certain what the example's author intended to happen in the example, but I think its reasonable to assume the text "350 degrees." was meant to be displayed after the meter.

### Do you have anything more you want to share?

I am using MS Edge (Version 125.0.2535.85 (Official build) (64-bit)) to view the MDN examples. I don't currently have access to other browsers for comparison. Sorry I couldn't be more helpful. This is my first Git issue submission.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/meter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/meter/index.md
* Last commit: https://github.com/mdn/content/commit/0f4b28bdc51e89cd25d132b9db12e3e903a9c5aa
* Document last modified: 2024-04-05T16:12:20.000Z

</details>

**Comment by PrimeLemur** [comment]
I didn't escape the html for the example & my solution.

This is the html from the example on MDN.
...
<p>
  Heat the oven to <meter min="200" max="500" value="350">350 degrees</meter>.
</p>
```

This is what I think it should look like:
...
<p>
  Heat the oven to <meter min="200" max="500" value="350"></meter> 350 degrees.
</p>
...
My bad. Hope this makes it clearer.

**Comment by Josh-Cena** [comment]
Hello! This is a bit confusing but intentional. The idea is that the text and the meter bar show the exact same content, so only one of them is displayed. The text is meant as a fallback text for (a) screen readers (b) browsers that don't support meter bars (c) any other cases when the bar doesn't show.

Is this a bad example? I'd say yes because you would never do this. I think both examples on this page should be replaced with something more realistic.

**Comment by PrimeLemur** [comment]
Thank you for the response & clarifying what was intended. From the perspective of someone unfamiliar with the `<meter>` tag, it is confusing, and as you say, the stated example scenario is part of the problem. Even a one-line explanation of what the example demonstrates would've helped. Having an instruction to heat an oven to a temperature, when there is only a meter without any numeric guidance, is so counter-intuitive, I couldn't reconcile the idea that it might have been intentional. Thanks for adjusting the issue title, too.
