### ISSUE TITLE
What does "nothing is extracted" mean?

### ISSUE THREAD

**Issue by johndeighan** [mdn/content#34419]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

### What specific section or headline is this issue about?

several

### What information was incorrect, unhelpful, or incomplete?

The phrase "nothing is extracted" doesn't tell me what return value I should expect. If that phrase means that I'll get an empty array back, you should say that.

### What did you expect to see?

what value will be returned

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/slice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/slice/index.md
* Last commit: https://github.com/mdn/content/commit/85d7482697cc2bf407c58e809a2a754180d6714c
* Document last modified: 2024-02-08T03:28:22.000Z

</details>

**Comment by low-perry** [comment]
@johndeighan , it is stated at the description of the method, that `slice()` returns a shallow copy of the array that we call the method upon, meaning that when nothing is extracted from the original array, `slice()` would return an empty array.
Although I do believe , that this documentation needs some more clarification, especially when the `end` optional parameter is explained.
