### ISSUE TITLE
overflow-{x,y}: clip/visible interaction is inaccurate

### ISSUE THREAD

**Issue by rscharfer** [mdn/content#34436]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

> Setting one direction to visible (the default) while setting the other to a different value results in visible behaving as auto.

Not correct because you can have one direction set to `visible` and the other set to `clip` and the `visible` will still behave as `visible`

### What did you expect to see?

The bullet point maybe should just not be there.

### Do you have anything more you want to share?

Chrome browser MacOS Monterey

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/overflow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/overflow/index.md
* Last commit: https://github.com/mdn/content/commit/2109843d4c4f24aa9d8ee29d4ba4a82665934ea4
* Document last modified: 2024-05-14T05:25:20.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! This is directly translated from the [spec](https://drafts.csswg.org/css-overflow/#overflow-control):

> The [visible](https://drafts.csswg.org/css-overflow/#valdef-overflow-visible)/[clip](https://drafts.csswg.org/css-overflow/#valdef-overflow-clip) values of [overflow](https://drafts.csswg.org/css-overflow/#propdef-overflow) compute to [auto](https://drafts.csswg.org/css-overflow/#valdef-overflow-auto)/[hidden](https://drafts.csswg.org/css-overflow/#valdef-overflow-hidden) (respectively) if one of [overflow-x](https://drafts.csswg.org/css-overflow/#propdef-overflow-x) or [overflow-y](https://drafts.csswg.org/css-overflow/#propdef-overflow-y) is neither visible nor clip.

So it appears we should say "setting the other to any value except `visible` or `clip`" for both this point and the one below.

**Comment by low-perry** [comment]
@Josh-Cena  the statement about clip, is wrong. Eg:
```css
overflow-x: clip;
overflow-y:scroll;
