### ISSUE TITLE
improvements on glossary links in see-also

### ISSUE THREAD

**Issue by PassionPenguin** [mdn/content#34451]
## Background

Currently glossary links are mixed in different formats. Label of such links can be improved for:

- in non-glossary entries, to specify that links in the list are points to *Glossary* pages, rather than Guides or References.
- in glossary entries, to clarify that links are points to *Related* terms (against the current glossary page or Glossary mainpage)
- link to /docs/Glossary itself is indeed unnecessary

## Related suggestions

@dipikabh recommends to make the label of all these glossary links more readable (i.e. `Glossary` => `Related glossary terms`):

> Fair enough point about listing the terms. What do you think about preceding the list with a phrase ending in colon, such as "Related glossary terms:". It's a nuance but might be helpful instead of just saying "Glossary".
>
> ```markdown
> - Related glossary terms:
>   - {{Glossary("Term1")}}
>   - {{Glossary("Term2")}}
> ```
>
> - We need to qualify "Glossary" slightly considering we're already on a glossary page.
> - It would be nice to say upfront before the list that the links are glossary terms and not guide or reference pages (so not the last suggestion).
>
> _Originally posted by @dipikabh in https://github.com/mdn/content/pull/34165#discussion_r1655241066 and https://github.com/mdn/content/pull/34095#issuecomment-2194523190_

@bsmth recommends to remove the link of the label (i.e. link points to `/docs/Glossary`)> > This can be merged. Keeping it open for a short time in case we want to apply changes similar to #34165.

> Thanks a lot! I also think the changes look good, with one comment that I think linking to `/Glossary` is not necessary, so I would just prefer to do this:
> 
> ```markdown
> - Glossary
>   - {{Glossary("Term1")}}
>   - {{Glossary("Term2")}}
> ```
> 
> Or indeed
> 
> ```markdown
> - {{Glossary("Term1")}}
> - {{Glossary("Term2")}}
> ```
>
> _Originally posted by @bsmth in https://github.com/mdn/content/pull/34095#issuecomment-2194168271_

**Comment by dipikabh** [comment]
Thanks @PassionPenguin for opening the issue and the PR to resolve the inconsistencies. Brian and I will discuss the style to adopt for the glossary terms in "See also" and will get back to you on the PR.

Thanks for your efforts!
