### ISSUE TITLE
[CSS] Hide :-moz-submit-invalid behind a pref

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#3446]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Hide :-moz-submit-invalid behind a pref

## Related Gecko bugs

1. - [x] [Hide :-moz-submit-invalid behind a pref](https://bugzilla.mozilla.org/show_bug.cgi?id=1694129). We have [a page](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-submit-invalid) for this; I'd expect the fix here to just involve updating the BCD to say it is behind a pref from 88 onwards, and add a rel note to say it has been effectively hidden from web content.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
Added to release notes, BCD as linked above, set bug to dev-doc-complete.

**Comment by chrisdavidmills** [comment]
I'm gonna close this one; The BCD needs finalizing, but it's a very minor update.
