### ISSUE TITLE
Change use of "has a name" for arrow functions which are "always unnamed"

### ISSUE THREAD

**Issue by senocular** [mdn/content#34488]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

> Arrow functions are always unnamed. If the arrow function needs to call itself, use a named function expression instead. You can also assign the arrow function to a variable so it has a name.

Specifically the first and last parts seem contradictory:

> Arrow functions are always unnamed.

and

> ...assign the arrow function to a variable so it has a name.

### What did you expect to see?

Something to the effect of:

> You can also assign the arrow function to a variable so you could refer to it through that variable.

Or something not suggesting the arrow function would be named.

### Do you have any supporting links, references, or citations?

https://tc39.es/ecma262/#sec-static-semantics-hasname

`HasName` returns false for all arrow functions.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/functions/arrow_functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/functions/arrow_functions/index.md
* Last commit: https://github.com/mdn/content/commit/9562249b86b8ba8f477f30e0fc3886996c896bfb
* Document last modified: 2024-06-10T06:41:59.000Z

</details>

**Comment by Josh-Cena** [comment]
Yeah, "so you could refer to it through that variable" sounds much better.

**Comment by mathdebate09** [comment]
A good-first! Can you assign this to me so I can work on it and submit a PR?

**Comment by Josh-Cena** [comment]
We don't assign. Please just send a PR.
