### ISSUE TITLE
Express-introduction: Broken link

### ISSUE THREAD

**Issue by Sokolan** [mdn/content#34481]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction#rendering_data_views

### What information was incorrect, unhelpful, or incomplete?

The provided link to the list of [template engines](https://expressjs.com/en/resources/template-engines.html) is broken.

### What did you expect to see?

working link.

### Do you have any supporting links, references, or citations?

After taking a look at the express github repo it seems like they've [removed the page](https://github.com/expressjs/expressjs.com/pull/1484).
The same PR also removed another broken link which was [mentioned here](https://github.com/mdn/content/pull/34002).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/introduction/index.md
* Last commit: https://github.com/mdn/content/commit/e7d7c8739cd6315a32400e76de2ec79594e86d8a
* Document last modified: 2024-06-10T14:32:11.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting. We could replace with https://expressjs.com/en/guide/using-template-engines.html, what do you think?

**Comment by Sokolan** [comment]
That link is already provided in the end of the template section:
For more information see [Using template engines with Express](https://expressjs.com/en/guide/using-template-engines.html) (Express docs).
I think it would be a duplication, and there's a minimal information regarding what template engines work with express (from the provided link):
> Some popular template engines that work with Express are [Pug](https://pugjs.org/api/getting-started.html), [Mustache](https://www.npmjs.com/package/mustache), and [EJS](https://www.npmjs.com/package/ejs). The [Express application generator](https://expressjs.com/en/starter/generator.html) uses [Jade](https://www.npmjs.com/package/jade) as its default, but it also supports several others.

I'm currently studying the subject (that's why I've stumbled the broken link) so maybe I'm maybe I'm wrong about it.

**Comment by hamishwillee** [comment]
Thanks. That is so annoying - we only fixed up the original link in March https://github.com/mdn/content/pull/32461/.

I'll fix this with some words about the supported versions. Note, not quite those words though, since we don't want to recommend Jade, which become Pug.

**Comment by hamishwillee** [comment]
Done in #34527
