### ISSUE TITLE
Operator "sides" should rather be called "operands"

### ISSUE THREAD

**Issue by wzychla** [mdn/content#34490]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_convert_BigInt_to_number

### What information was incorrect, unhelpful, or incomplete?

*The two sides of an arithmetic operator ...*

*explicitly coerce one side to a*

In both these cases, "sides" should rather be refrred to as "operands". Arithmetic operators have "operands" rather than "sides". "Sides" is mostly used when the assignment operator is referred to.

### What did you expect to see?

*The two sides of an arithmetic operator ...* -> *The two operands of an arithmetic operator ...*

*explicitly coerce one side to a* -> *explicitly coerce one operand to a*

### Do you have any supporting links, references, or citations?

https://en.wikipedia.org/wiki/Operation_(mathematics)

In mathematics, an operation is a function which takes zero or more input values (also called **operands or arguments**) to a well-defined output value. 

https://en.wikipedia.org/wiki/Operand

In mathematics, an operand is the object of a mathematical operation, i.e., it is the object or quantity that is operated on

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/cant_convert_bigint_to_number`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_convert_BigInt_to_number
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/cant_convert_bigint_to_number/index.md
* Last commit: https://github.com/mdn/content/commit/6d606174faaedaa5dee7b7ebd87602cd51e5dd7e
* Document last modified: 2023-07-24T23:45:00.000Z

</details>

**Comment by Josh-Cena** [comment]
Actually I don't think this is an issue worth fixing. Operators can have "left-hand side" and "right-hand side" and they are collectively called "sides". Of course you can also have "left operand" and "right operand" but I don't want to establish a preference for either. See for example this Firefox error: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unparenthesized_unary_expr_lhs_exponentiation which explicitly calls the "operand" as "left-hand side".
