### ISSUE TITLE
Issue with "yield": Broken link to legacy generator function article

### ISSUE THREAD

**Issue by impressivewebs** [mdn/content#345]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield

#### What information was incorrect, unhelpful, or incomplete?
The link to the legacy generator function is broken. It points to:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/Legacy_generator_function

#### Specific section or headline?
Opening section.

#### What did you expect to see?
I believe it's supposed to now point to the following link:

https://developer.mozilla.org/en-US/docs/Archive/Web/JavaScript/Legacy_generator_function_statement

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/yield`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/operators/yield/index.html
* Report started: 2020-12-17T08:23:37.664Z

</details>

**Comment by chrisdavidmills** [comment]
Ooops, I just fixed with issue with a direct commit , and then saw Mike's fix ;-/

**Comment by chrisdavidmills** [comment]
Not sure what happens now.

https://github.com/mdn/content/commit/eb93c88ba757b73a7edbb5abdcc02d5eac5dae1d

**Comment by vkWeb** [comment]
Fixed with: https://github.com/mdn/content/commit/eb93c88ba757b73a7edbb5abdcc02d5eac5dae1d by @chrisdavidmills. Hence, closing.
