### ISSUE TITLE
Class placed on form not body

### ISSUE THREAD

**Issue by chriskmamo** [mdn/content#34504]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls

### What specific section or headline is this issue about?

Bringing your control to life with JavaScript

### What information was incorrect, unhelpful, or incomplete?

```
<body>
  <form class="no-widget">
```

### What did you expect to see?

```
<body class="no-widget">
  <form>
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/how_to_build_custom_form_controls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_build_custom_form_controls/index.md
* Last commit: https://github.com/mdn/content/commit/aa5cd008f866b855beba47c183176670f4876b65
* Document last modified: 2024-03-15T10:24:53.000Z

</details>

**Comment by Josh-Cena** [comment]
This became wrong in https://github.com/mdn/content/pull/31224.
