### ISSUE TITLE
Issue with "RTCPeerConnection: negotiationneeded event": Typo in code samples

### ISSUE THREAD

**Issue by CesarVonc** [mdn/content#3450]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/negotiationneeded_event

#### What information was incorrect, unhelpful, or incomplete?
There is error in the code example on the "catch" line, a bracket is missing :
  .catch(err => {
    /* handle error */
  );

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/rtcpeerconnection/negotiationneeded_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/negotiationneeded_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/rtcpeerconnection/negotiationneeded_event/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/3482 with a fix
