### ISSUE TITLE
scope default value "auto" is not mentioned (HTMLTableCellElement)

### ISSUE THREAD

**Issue by caugner** [mdn/content#34537]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement/scope

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement/scope#value

### What information was incorrect, unhelpful, or incomplete?

The values listed don't include the default value "auto", as mentioned in the standard.

### What did you expect to see?

The default value "auto" should have been mentioned.

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/tables.html#the-th-element

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmltablecellelement/scope`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement/scope
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmltablecellelement/scope/index.md
* Last commit: https://github.com/mdn/content/commit/390e2cf1cba988c680713050f5a8d619f9882c3d
* Document last modified: 2024-05-03T00:49:14.000Z

</details>

**Comment by Josh-Cena** [comment]
I believe this is a spec editorial mistake. There's no `auto` keyword in either content attribute or IDL. Before https://github.com/whatwg/html/pull/9952, the spec only defined four keywords and `auto` was only defined as a state (attained when the attribute is missing or invalid) and not as a keyword. Try it yourself:

```html
<html>
  <table>
    <tr>
      <th scope="auto" id="f">Test</th>
    </tr>
  </table>
  <script>
    console.log(f.scope)
  </script>
</html>
```

It logs the empty string, not `auto`.

@annevk could you confirm?

**Comment by Josh-Cena** [comment]
Thank you for the prompt action (and the acknowledgment)! 😄
