### ISSUE TITLE
Image is broken in The general HTTP authentication framework

### ISSUE THREAD

**Issue by Mohitkumar6122** [mdn/content#34536]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication

### What information was incorrect, unhelpful, or incomplete?

Information Incomplete

### What did you expect to see?

A sequence diagram illustrating HTTP messages between a client and a server lifeline.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/authentication`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/authentication/index.md
* Last commit: https://github.com/mdn/content/commit/fa33a91a01e9e6868def6945ed66a07662284795
* Document last modified: 2024-06-21T18:56:42.000Z

</details>

**Comment by pransh15** [comment]
Hi @Mohitkumar6122 👋 

Thanks for submitting this issue. I noticed the following image on the page, which appears to illustrate the sequence you mentioned:
![basic-auth](https://github.com/mdn/content/assets/18158596/d7f93abd-2b12-4253-95b3-72d11f406e30)

Could you please provide more details regarding the issue with the image? Are you experiencing difficulties viewing the image on this page?

**Comment by Mohitkumar6122** [comment]
@pransh15 I'm getting the following issue 
![image](https://github.com/mdn/content/assets/47894634/2bb70520-b9fb-49bc-bc3b-eaa93cd81d81)

**Comment by bsmth** [comment]
Thanks for reporting. Could you give us some more information so we can look into it? It would be helpful to know:

* Browser & version
* Any extensions running?
* Operating system

Also, do you see the same issue when you use a private session or clear your cache? Thank you!

**Comment by Mohitkumar6122** [comment]
@bsmth Its working fine after clearing cache. 
Browser: Chrome
OS: Mac

**Comment by Mohitkumar6122** [comment]
@bsmth I'm getting this from the document response with 200 status 
I believe, there is some problem in generating the HTML with image from the server. 
![image](https://github.com/mdn/content/assets/47894634/01967628-356f-428e-bb73-ebccabd21a4d)

**Comment by bsmth** [comment]
Hi @Mohitkumar6122 is this still an issue? Can you see the following resource?

https://mdn.github.io/shared-assets/images/diagrams/http/authentication/basic-auth.svg

**Comment by Mohitkumar6122** [comment]
Yeah @bsmth, I'm able to see the image
I guess there was some issue with the browser cache

**Comment by bsmth** [comment]
OK, thank you! Glad it's working again!
