### ISSUE TITLE
Example for "HTML attribute: Boolean Attributes" is for "itemscope", not for boolean attributes.

### ISSUE THREAD

**Issue by RobBednark** [mdn/content#34530]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

### What specific section or headline is this issue about?

Boolean Attributes

### What information was incorrect, unhelpful, or incomplete?

The following appears to be examples for `itemscope`, not for `Boolean Attributes`:

```html
<div itemscope>This is valid HTML but invalid XML.</div>
<div itemscope=itemscope>This is also valid HTML but invalid XML.</div>
<div itemscope="">This is valid HTML and also valid XML.</div>
<div itemscope="itemscope">
  This is also valid HTML and XML, but perhaps a bit verbose.
</div>
```

### What did you expect to see?

Examples for boolean attributes, per the line:
>  The following examples are valid ways to mark up a boolean attribute:

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/index.md
* Last commit: https://github.com/mdn/content/commit/bf671984cfef2f7c6419571d834a146c5424ac10
* Document last modified: 2024-06-05T02:54:28.000Z

</details>

**Comment by RobBednark** [comment]
Now that I read it again, I think I'm wrong.  It appears `itemscope` is the boolean attribute being used in the example.  I hadn't fully understood content vs IDL attributes, and was expecting/hoping to see an IDL example here. 

I think this can be closed, but please confirm.

**Comment by Josh-Cena** [comment]
Right, this is talking about HTML boolean attributes, and `itemscope` is a boolean attribute.
