### ISSUE TITLE
[CSS] Remove :-moz-ui-invalid default style sheet rules and its novalidate handling

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#3454]
## Acceptance criteria

1. - [ ] The listed features are documented sufficiently on MDN
2. - [ ] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Remove :-moz-ui-invalid default style sheet rules and its novalidate handling.

## Related Gecko bugs

1. - [ ] [Remove :-moz-ui-invalid default style sheet rules and its novalidate handling](https://bugzilla.mozilla.org/show_bug.cgi?id=1693969). Hrm, I'm not really sure what this one requires. Bit of investigation needed.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
@chrisdavidmills not sure there is anything really to do here, this is the pseudo that is now renamed and standardized so this seems to be a cleanup from that.

**Comment by chrisdavidmills** [comment]
@rachelandrew fair enough. Can probably close this one then.
