### ISSUE TITLE
[CSS] :user-valid and :user-invalid pseudo-classes

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#3455]
## Acceptance criteria

1. - [ ] The listed features are documented sufficiently on MDN
2. - [ ] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. :user-valid
2. :user-invalid

## Related Gecko bugs

1. - [ ] [Implement the user-valid and user-invalid pseudo-classes](https://bugzilla.mozilla.org/show_bug.cgi?id=1694141). We have a [:user-invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid) page, but not a :user-valid one. So bit of page creation, BCD updates, and interactive example creation? Quite an involved one, this, but should be fun.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
@chrisdavidmills we do have https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-ui-valid (which is the one flagged for removal but I think is the pair to  https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid which also mentions the -moz property).

I'm thinking to rename this page.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills we do have https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-ui-valid (which is the one flagged for removal but I think is the pair to https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid which also mentions the -moz property).
> 
> I'm thinking to rename this page.

Ah, good call — yup, makes sense!

**Comment by rachelandrew** [comment]
@chrisdavidmills I still can't move things https://github.com/mdn/content/issues/2852#issuecomment-809239028

Can I just do these by hand? I was doing before and nothing terrible happened. It's a bit of a blocker otherwise.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills I still can't move things [#2852 (comment)](https://github.com/mdn/content/issues/2852#issuecomment-809239028)
> 
> Can I just do these by hand? I was doing before and nothing terrible happened. It's a bit of a blocker otherwise.

For now, just go for it, until this gets fixed.

**Comment by rachelandrew** [comment]
The linked PRs I think sort this one. I've also updated the release notes and the Bugzilla bug.

**Comment by chrisdavidmills** [comment]
Closing this one; only a few merge conflicts to fix up.
