### ISSUE TITLE
[CSS] image-set() support

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#3456]
## Acceptance criteria

1. - [ ] The listed features are documented sufficiently on MDN
2. - [ ] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. image-set() as a value for content and cursor properties.
2. image-set() function in general

## Related Gecko bugs

1. - [ ] [Support image-set() on the cursor property](https://bugzilla.mozilla.org/show_bug.cgi?id=1695402). Probably just needs an example adding to the [cursor](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) page, rel note and BCD?
1. - [ ] [Support image-set() on the content property](https://bugzilla.mozilla.org/show_bug.cgi?id=1695403). Same as above, but for the [content](https://developer.mozilla.org/en-US/docs/Web/CSS/content) property?
1. - [ ] [Enable layout.css.image-set.enabled in all channels.](https://bugzilla.mozilla.org/show_bug.cgi?id=1698133). Update [image-set()](https://developer.mozilla.org/en-US/docs/Web/CSS/image-set()) page and BCD, add rel note?

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
@chrisdavidmills This isn't actually in the spec yet for cursor (although it does say that UAs can support image) https://github.com/w3c/csswg-drafts/issues/5831

So we probably don't want to add too much to the page right now. I'm wondering about BCD for cursor also? Should I add a line about support for `<image>`? As that is really where `image-set()` comes from, this is a change to allow the cursor property to support `<image>`, the but of implementation in 88 is adding the support for image-set to cursor.
