### ISSUE TITLE
[CSS] ruby CSS updates

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#3457]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. ruby-position alternate value 
2. visibility:collapse on ruby annotations

## Related Gecko bugs

1. - [x] [[css-ruby] alternating sides for ruby-position](https://bugzilla.mozilla.org/show_bug.cgi?id=1694748). Add the alternate value to the ruby-position [page](https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-position), provide an example and get rid of the Experimental banner, update BCD, add rel note?
1. - [x] [[css-ruby] visibility:collapse on ruby annotations](https://bugzilla.mozilla.org/show_bug.cgi?id=1697529). Add visibility-collapse support for ruby properties, including BCD, rel note? Not sure which properties — investigation needed.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
I think once the above are emerged this one is done.

**Comment by chrisdavidmills** [comment]
This one looks great, so closing. Thanks @rachelandrew !
