### ISSUE TITLE
Error in WeakMap cache example

### ISSUE THREAD

**Issue by samueldcorbin** [mdn/content#34583]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#caching

### What information was incorrect, unhelpful, or incomplete?

The example shows caching the value of an objection->object function into a WeakMap, which is fine, but the discussion below it says:

>  Moreover, even if the input is never passed in again, the result still remains forever in the cache.

This is very confusing/misleading/arguably incorrect. If the input is garbage collected, and there are no other strong references to the result remaining, the result becomes eligible for garbage collection.

### What did you expect to see?

A correct explanation about the lifetime of objects in the cache indicating that whenever the input is garbage collected, the entry is removed and the result becomes eligible for garbage collection if there are no other strong references to it.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/weakmap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/weakmap/index.md
* Last commit: https://github.com/mdn/content/commit/41cddfdaeed4a73fb8234c332150df8e54df31e9
* Document last modified: 2023-11-08T04:45:53.000Z

</details>

**Comment by Josh-Cena** [comment]
Yep you are right. It should be slightly more nuanced and say "the result still remains forever in the cache as long as the key is alive".
