### ISSUE TITLE
[CSS] Menlo as new default monospace font on macOS

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#3458]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Menlo as the new default monospace font on macOS

## Related Gecko bugs

1. - [x] [Use Menlo as the default monospace font on macOS](https://bugzilla.mozilla.org/show_bug.cgi?id=1342741). Not really 100% sure what we need to add to MDN for this, beyond perhaps a rel note. Investigation needed.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
Added to the release notes and checked that we don't list these defaults anywhere, which I don't think we do. So have marked the bug complete in Bugzilla.
