### ISSUE TITLE
KeyboardEvent: code does not produce ShiftRight

### ISSUE THREAD

**Issue by Kjm379** [mdn/content#34606]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

### What specific section or headline is this issue about?

Try it out

### What information was incorrect, unhelpful, or incomplete?

We do not get the code value of "ShiftRight" key.

### What did you expect to see?

The code value of "ShiftRight" is shown.

### Do you have any supporting links, references, or citations?

https://mike3.net/piano   The site is in Japanese.

Pressing Shift left moves the register to the left, but pressing Shift right does not change the register.

### Do you have anything more you want to share?

No, I do not have.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/keyboardevent/code`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/keyboardevent/code/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by Josh-Cena** [comment]
cc @mdn/yari-content-ja Do you have any insights about the Japanese keyboard layout?

**Comment by Kjm379** [comment]
Yes, I do. We get the key value of Shift right in Firefox. We also get the key values in Chrome and Edge in Windows 10, but we cannot get the value in Windows 11.

**Comment by Josh-Cena** [comment]
Hmmm. That sounds more like a Windows 11 and/or Chrome bug, if the result is inconsistent between Win10 and Win11.

**Comment by Kjm379** [comment]
Thanks for your comments. I have reported trouble with Chrome and Edge, but no improvement; I have not reported any trouble to Microsoft.

**Comment by Josh-Cena** [comment]
I'm closing this because it's a really, really niche browser bug to say the best, since it only happens on a specific OS/browser/locale combination, and not something we should document.
