### ISSUE TITLE
[WebAPI] AbortSignal.abort()

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#3460]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. AbortSignal.abort()

## Related Gecko bugs

1. - [x] [Implement AbortSignal.abort() static method](https://bugzilla.mozilla.org/show_bug.cgi?id=1698468). Doesn't look like this has been documented yet (see [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal)). Page to add, BCD, rel note?

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
Tracking/TBD

- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate - NA
- [ ] Docs - see #3616
- [ ] Release note
- [ ] Docs-dev-complete

**Comment by chrisdavidmills** [comment]
We are done on this one; closing!
