### ISSUE TITLE
[WebAPI] Disable Presentation API on GeckoView Nightly

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#3461]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Disable Presentation API on GeckoView Nightly

## Related Gecko bugs

1. - [x] [Disable Presentation API on GeckoView Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1697680). [Presentation API](https://developer.mozilla.org/en-US/docs/Web/API/Presentation_API) pages need BCD updating to make situation make sense. Not sure if this should be marked deprecated, as Chrome still supports it fine? Might be worth diggig into backstory here to see why this is happening.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
Status review.

Looks like it was removed in desktop FF61 and this removes it from android in FF88 (testing that theory in the BCD and bug). It would still be "experimental" as only in chrome and FF had behind preference. Does not seem to be deprecated - it is more a case that we don't implement it right. IMO no work needs to be done on the docs themselves other than release notes.

- [ ] [BCD](https://github.com/mdn/browser-compat-data/pull/9670) - in review
- [ ] Interactive example ... - NA
- [ ] [dev-doc-complete note added](https://bugzilla.mozilla.org/show_bug.cgi?id=1697680#c13) - note added confirming status
- [ ]  dev-doc-complete tag removal - for ChrisM
- [ ] Release note
- [ ] Experimental features

**Comment by chrisdavidmills** [comment]
Completed, and closed! Thanks @hamishwillee !
