### ISSUE TITLE
[HTTP] Disable FTP

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#3462]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Disable FTP

## Related Gecko bugs

1. - [x] [Disable FTP on beta and release](https://bugzilla.mozilla.org/show_bug.cgi?id=1691890). Not sure how we want to communicate this, beyond a rel note.
1. - [x] [FTP removal and testing with addons](https://bugzilla.mozilla.org/show_bug.cgi?id=1626365). Not sure what needs documenting about this.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
Tracking
- [ ] BCD is updated - for `browserSettings.ftpProtocolEnabled`
- [ ] Interactive example and data repos are updated if appropriate - NA
- [ ] [Release note] TBD needs update
- [ ] [dev-doc-complete note] TBD
- [ ] [dev-doc-complete note] - ChrisM to do when above point complete
- [ ] [Experimental features] TBD - needs update


Check of other docs
- [ ] [Learn > Common questions > How much does it cost](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/How_much_does_it_cost#browsers) - mentions FTP option. Needs to be fixed up.
- [ ] [Mozilla > Add-ons > Browser Extensions > JavaScript APIs > browserSettings > browserSettings.ftpProtocolEnabled](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/ftpProtocolEnabled) - Now [always disabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1626365) and there is a BCD impact.
- [ ] [FTP proxy settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings) - includes FTP - need to check if still present.
- [ ] [Work with the Bookmarks API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Work_with_the_Bookmarks_API) - I'm guessing if you can't get FTP in tab you can't bookmark?
- [ ] [Building on Windows with SFU (Interix)](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Building_on_Windows_with_SFU_(Interix)) - bunch of ftp:// links - what happens with these from FF88? (also do proper search on that)
- [ ] [Experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#FTP_support_disabled) - update what actually happened.

**Comment by hamishwillee** [comment]
@chrisdavidmills The tracking got a bit messy. Basically what remains for review is:
- protocol handler changes
  - #3866 - update to release note and protocol handler page
  - BCD update https://github.com/mdn/browser-compat-data/pull/9775
- Non-core changes related to removal of FTP - i.e. stuff that might still not "fail" but makes less sense. 
  - BCD https://github.com/mdn/browser-compat-data/pull/9775
  - #3868 Docs

**Comment by chrisdavidmills** [comment]
OK, all done, and closing!
