### ISSUE TITLE
Missing - A very useful code example that previously existed

### ISSUE THREAD

**Issue by klude-au** [mdn/content#34641]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/RequestInit

### What information was incorrect, unhelpful, or incomplete?

One of the fetch API page used to contain a code with all the options and their defaults. 
Previously I could get is with a google search and a couple of clicks. This code is nowhere to be found. 

When coding I used to just go to this page and copy this code. 
It was a good reference point to go to. 
I now don't remember the exact url but it looked as given in the 'What did you expect to see?' section below.

The current document is good for reading/study but this example helps with coder ergonomics.

Please can you put it back or point me to the page?

### What did you expect to see?

```
    async fetch(url = '', data = {}) {
        // Default options are marked with *
        const response = await fetch(url, {
            method: 'POST', // *GET, POST, PUT, DELETE, etc.
            mode: 'cors', // no-cors, *cors, same-origin
            cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
            credentials: 'same-origin', // include, *same-origin, omit
            headers: {
                'Content-Type': 'application/json'
                // 'Content-Type': 'application/x-www-form-urlencoded',
            },
            redirect: 'follow', // manual, *follow, error
            referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
            body: JSON.stringify(data) // body data type must match "Content-Type" header
        });
        return response.json(); // parses JSON response into native JavaScript objects
    }    
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/requestinit`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RequestInit
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/requestinit/index.md
* Last commit: https://github.com/mdn/content/commit/413ce1e7bc8b6cacd8eea9d9b1c3dc972c118f4d
* Document last modified: 2024-07-02T23:49:10.000Z

</details>

**Comment by Josh-Cena** [comment]
The same thing was said in https://github.com/mdn/content/pull/34278#issuecomment-2205091230. It's not good coding style to copy boilerplate, because redundant default options are going to confuse readers. Rather, understand each part of it and only specify the options you actually need.
