### ISSUE TITLE
Attributes for template and slot are missing

### ISSUE THREAD

**Issue by stephanboeni** [mdn/content#34651]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

### What specific section or headline is this issue about?

Attribute list

### What information was incorrect, unhelpful, or incomplete?

Attributes for template and slot are missing

### What did you expect to see?

Attribute name also for slot.
Attribute open and closed also for template.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/index.md
* Last commit: https://github.com/mdn/content/commit/bf671984cfef2f7c6419571d834a146c5424ac10
* Document last modified: 2024-06-05T02:54:28.000Z

</details>

**Comment by Josh-Cena** [comment]
Hello! The attribute table is not meant to be exhaustive and we are refactoring that in https://github.com/mdn/content/issues/27733 to make it even clearer that this is the case. You should read the references of the HTML elements to understand what attributes each one takes.
