### ISSUE TITLE
Issue with "calc()": (short summary here please)

### ISSUE THREAD

**Issue by posel** [mdn/content#3466]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/calc()

#### What information was incorrect, unhelpful, or incomplete?
calc in FF does not calculate with more than 2 operators with different units. Chrome and Edge works correctly

#### Specific section or headline?
Unfunctional example:
@media (min-height: 60em) {
  .fp--dashboard {
    max-height: calc(100vh - 3% - 5em);
    background-color: beige !important;
  }
}

background settings works - so that style is loaded, but the height settings does not. Also check/uncheck in browser style explorer makes nor. However changing to the 
calc(100vh - 5em - 5em)
works.

#### What did you expect to see?
The same behaiviour as in the Chrome / Edge

#### Did you test this? If so, how?
the page behaves incorrectly -

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/calc()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/calc()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/calc()/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by chrisdavidmills** [comment]
@posel this sounds like it is an issue in the behavior of Firefox itself, rather than an issue with our page...in which case you should file a bug at https://bugzilla.mozilla.org.

I'm therefore closing this; if I've misunderstood, feel free to clarify, and we can reopen and continue.
