### ISSUE TITLE
border-spacing default is 2px

### ISSUE THREAD

**Issue by kzhui125** [mdn/content#34671]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/border-spacing

### What information was incorrect, unhelpful, or incomplete?

https://www.w3schools.com/csSref/pr_border-spacing.php

Default value: 2px

for example:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Separated (and thus separate) cell borders</title>
    <style type="text/css">
        html {
            background: silver;
        }

        body {
            background: white;
            padding: 1em;
        }

        table {
            border-collapse: separate;
            width: 300px;
            height: 300px;
        }

        #t2 {
            /* border-spacing: 2px; */
        }

        td {
            border: 30px solid black;
            padding: 30px;
        }

        tr:nth-child(2) td:nth-child(2) {
            border-color: gray;
        }
    </style>
</head>

<body>

    <table id="t2">
        <tr>
            <td>cell one</td>
            <td>cell two</td>
        </tr>
        <tr>
            <td>cell three</td>
            <td>cell four</td>
        </tr>
    </table>

</body>

</html>
```

### What did you expect to see?

initial value for border-spacing should be 2px instead of 0.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/border-spacing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/border-spacing
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/border-spacing/index.md
* Last commit: https://github.com/mdn/content/commit/b319e190a9f9df504e84f8b49d06008f6d60b396
* Document last modified: 2024-04-25T16:23:45.000Z

</details>

**Comment by OnkarRuikar** [comment]
It is correct as per [the specification](https://drafts.csswg.org/css2/#separated-borders) which is `0`.

It's the browsers that set it to `2px` in the user agent stylesheet:
> ![1](https://github.com/mdn/content/assets/87750369/d58e9b2b-b530-40f4-91e8-9485bad31d16)

**Comment by kzhui125** [comment]
thanks
