### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by alittlebitofit** [mdn/content#34673]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment

### What specific section or headline is this issue about?

Setup the web app

### What information was incorrect, unhelpful, or incomplete?

WGSI should be WSGI in point number 6.

### What did you expect to see?

WSGI

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/django/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/deployment/index.md
* Last commit: https://github.com/mdn/content/commit/4d9375ca739df44ef52cd026de9a20aaff60d9aa
* Document last modified: 2024-03-27T14:08:59.000Z

</details>

**Comment by Josh-Cena** [comment]
Do you want to make a PR?

**Comment by alittlebitofit** [comment]
> Do you want to make a PR?

Yes, thank you. I just sent a PR.
