### ISSUE TITLE
Issue with "Using CSS gradients": Incorrect image on gradients page

### ISSUE THREAD

**Issue by elly-annvandieren** [mdn/content#3467]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Using_CSS_gradients

#### What information was incorrect, unhelpful, or incomplete?
The image in the "Using Angles" section is wrong. 90deg and -90 degree do not show the right gradients. 

#### Specific section or headline?
Using Angles

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_images/using_css_gradients`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Using_CSS_gradients
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_images/using_css_gradients/index.html
* Last commit: https://github.com/mdn/content/commit/892665a4c27da31a26d22578335377549324bb88
* Document last modified: 2021-03-23T04:34:40.000Z

</details>

**Comment by lucalves** [comment]
Hello @elly-annvandieren, which test did you do to inform that it is incorrect? I tested it here and the results were identical to the images.

**Comment by sideshowbarker** [comment]
Closing for lack of response
