### ISSUE TITLE
The link to "value" is not working

### ISSUE THREAD

**Issue by penguinness** [mdn/content#34682]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents

### What specific section or headline is this issue about?

Active learning: A dynamic shopping list

### What information was incorrect, unhelpful, or incomplete?

The hyperlink to "value" in the sentence "Inside the function body, start off by storing the current value of the input element in a variable." is not working.

### What did you expect to see?

I expected the link to show me information about value.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents#active_learning_a_dynamic_shopping_list

### Do you have anything more you want to share?

<img width="841" alt="image" src="https://github.com/mdn/content/assets/92165891/33bc56a3-ea2a-49f6-8cc4-ca911bef3e84">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/manipulating_documents`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/client-side_web_apis/manipulating_documents/index.md
* Last commit: https://github.com/mdn/content/commit/7e97f3c5ada65b6638909bde92881a4b8d46a2b8
* Document last modified: 2024-07-02T03:47:33.000Z

</details>

**Comment by Josh-Cena** [comment]
When you hover over it, it already tells you why:

> This is a link to an unwritten page

Creation of this page is tracked in https://github.com/mdn/mdn/issues/520.
