### ISSUE TITLE
Concatenation in context section gives no prompt

### ISSUE THREAD

**Issue by pirut** [mdn/content#34687]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings

### What specific section or headline is this issue about?

Concatenation in context

### What information was incorrect, unhelpful, or incomplete?

```html
<button>Press me</button>
<div id="greeting"></div>

```

```js
const button = document.querySelector("button");

function greet() {
  const name = prompt("What is your name?");
  const greeting = document.querySelector("#greeting");
  greeting.textContent = `Hello ${name}, nice to see you!`;
}

button.addEventListener("click", greet);

```

There is no prompt that gets thrown when you click the button in the playground.

### What did you expect to see?

I expected to see a prompt asking for my name

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/strings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/strings/index.md
* Last commit: https://github.com/mdn/content/commit/23e1a97d50050a3b3518a4b2f67ccf42e5fd75b7
* Document last modified: 2024-06-28T03:14:04.000Z

</details>

**Comment by Josh-Cena** [comment]
Tracked in https://github.com/mdn/content/issues/7566
