### ISSUE TITLE
Incorrect casing in example of node.nodeName

### ISSUE THREAD

**Issue by John-Page** [mdn/content#34685]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Node

### What specific section or headline is this issue about?

Instance property Node.nodeName

### What information was incorrect, unhelpful, or incomplete?

The description is silent on the case of the node names returned.    In practice when I try it, the names are uppercase such as DIV.   Except text nodes return lowercase #text.    I know I should be defensive as normalize the case before I test them,    

### What did you expect to see?

It would be good if the issue was addressed.  If there is no standard,  perhaps say that and suggest we should expect either case when testing them.    

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/node`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/node/index.md
* Last commit: https://github.com/mdn/content/commit/bb60fadaa7423d2195ae8727f197fa4361aa09df
* Document last modified: 2023-02-20T08:52:54.000Z

</details>

**Comment by Josh-Cena** [comment]
This is documented here: https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeName but I think the example given on the overview page (`"audio"`) is incorrect.
