### ISSUE TITLE
[WebAPI] Implement CSSPageDescriptors

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#34702]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [ ] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1890842

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Confirmations happening in https://bugzilla.mozilla.org/show_bug.cgi?id=1890842#c9

Status

- [ ] BCD 
   - [ ] https://github.com/mdn/browser-compat-data/pull/23730
   - [ ] I think we also need to update https://developer.mozilla.org/en-US/docs/Web/API/CSSPageRule/style in BCD to indicate that its type changed from `CSSStyleDeclaration` to `CSSPageDescriptors`
- [ ] Docs
  - [ ] `CSSPageDescriptors`
  - [ ] [`CSSPageRule.style`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPageRule/style)
  - [ ] ?
- [ ] Release note
- [ ] dev-docs-complete

**Comment by hamishwillee** [comment]
Thanks @Elchi3 . I actually already documented them because my testing showed they existed and when I saw https://github.com/mdn/browser-compat-data/pull/23730 it looked like it covered all the properties. So no docs work here.

**Comment by Elchi3** [comment]
Thanks Hamish, looks like https://github.com/mdn/content/pull/35291 removed them.
