### ISSUE TITLE
[SVG] support viewport and screen options for non-scaling-stroke

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#34704]
## Acceptance criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes for enabled/preview features
- [ ] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1904891

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by dletorey** [comment]
This has been reversed and is not being shipped:
https://groups.google.com/a/mozilla.org/g/dev-platform/c/D-7LtjA-kUw/m/BtWktZ_qAQAJ
> In the end we decided not to implement screen or viewport support as we found an addendum to the SVG spec that removes them.
