### ISSUE TITLE
[WebAPI] Support for WebCrypto Curve25519: Ed25519

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#34708]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1804788

Additionally there is this bug with dev-doc-needed, but not sure if anything is needed https://bugzilla.mozilla.org/show_bug.cgi?id=1905120

### Related issues and pull requests

- [x] https://github.com/mdn/content/issues/30886
- [x] https://github.com/mdn/browser-compat-data/pull/22033

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by bsmth** [comment]
See also:

- [x] https://github.com/mdn/browser-compat-data/pull/22033

**Comment by hamishwillee** [comment]
Status:

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/23925
- [ ] Docs
- [ ] Release notes
- [ ] dev-docs-complete

**Comment by Frosne** [comment]
Hi, a small passing-by comment. 

Curve25519 is presented with 2 algorithms, Ed25519 and X25519. We have not yet landed X25519, this is the tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1904836

**Comment by hamishwillee** [comment]
@Frosne Thank you very much. I will update the information in compatibility data. W.r.t. to your responses on https://bugzilla.mozilla.org/show_bug.cgi?id=1804788#c27 - very helpful. I had missed wrap/unwrap() so more work to be done.
Much appreciated. If I have questions I will certainly follow up (probably on github, as I am doing the docs).

**Comment by Frosne** [comment]
Hi, just for your information, I have landed X25519 WebCrypto code : https://bugzilla.mozilla.org/show_bug.cgi?id=1904836
