### ISSUE TITLE
Broken link on `en-US/docs/Web/CSS/ident` page

### ISSUE THREAD

**Issue by romanstetsyk** [mdn/content#34739]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/ident

### What specific section or headline is this issue about?

`Syntax` section

### What information was incorrect, unhelpful, or incomplete?

There is a broken link in the sixth bullet point. The link text is `escaped character`, and its `href` is https://developer.mozilla.org/en-US/docs/Web/CSS/escaping_characters
The link leads to a page that says, 'Page not found.'

### What did you expect to see?

The correct page

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/ident`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/ident
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/ident/index.md
* Last commit: https://github.com/mdn/content/commit/4f7063ea23163a1f40fbb6fefdc731f30c24e2b2
* Document last modified: 2024-07-03T17:41:18.000Z

</details>

**Comment by Josh-Cena** [comment]
It should be `#escaping_characters`; it's missing a `#`.

**Comment by romanstetsyk** [comment]
Simple as that! I'll make a PR in a few minutes
