### ISSUE TITLE
Demo for "rect" doesnt work on Chrome

### ISSUE THREAD

**Issue by voidraymk1** [mdn/content#34741]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

### What specific section or headline is this issue about?

Demo-CSS

### What information was incorrect, unhelpful, or incomplete?

5th example (clip-path: rect(5px 5px 160px 145px round 20%);) doesnt work on Chrome

### What did you expect to see?

For it to work like on Firefox

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/clip-path`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/clip-path/index.md
* Last commit: https://github.com/mdn/content/commit/8cd08162e592c1baf5d888f4c5a08a58360344b5
* Document last modified: 2024-05-27T15:46:50.000Z

</details>

**Comment by Josh-Cena** [comment]
Please see https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape#browser_compatibility; Chrome does not support `rect()` in `clip-path`.
