### ISSUE TITLE
Issue with "Firefox Developer Tools": possibly outdated information on menu item name

### ISSUE THREAD

**Issue by lkintact** [mdn/content#3474]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools

#### What information was incorrect, unhelpful, or incomplete?
There's a phrase in the page: `You can open the Firefox Developer Tools from the menu by selecting Tools > Web Developer > Toggle Tools`. The last menu item's name in Firefox 87.0 is `Web Developer Tools`, not `Toggle Tools`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/index.html
* Last commit: https://github.com/mdn/content/commit/d354eede5b9fe8095e514664d307a1e6d2a32832
* Document last modified: 2021-02-02T17:10:43.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this :+1:

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander thanks; assigned!

**Comment by himanshugarg** [comment]
This is not an issue on Firefox 86 - [Screenshot](https://i.imgur.com/uh8HTym.png)

**Comment by lkintact** [comment]
FWIW, for me in Firefox 88.0.1 on Windows it's `Tools > Browser Tools > Web Developer Tools`.

**Comment by himanshugarg** [comment]
Ok. Looks like the string changed in 87 where this issue was originally
found. Thanks for the update.

**Comment by hamishwillee** [comment]
I've merged #3484 with fix (kindly provided by @CreaTorAlexander). This matches the update I did recently to https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox#toolbox
