### ISSUE TITLE
"use" svg example has errors

### ISSUE THREAD

**Issue by georgernstgraf** [mdn/content#34753]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

The third circle was obviously meant to have a red stroke which it does not have, neither in a current firefox nor edge browser. The third circle is still displayed blue.

It's about this line:

```html
<use href="#myCircle" x="20" fill="white" stroke="red" />
```

### What did you expect to see?

a red circle on the right.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/element/use`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/use/index.md
* Last commit: https://github.com/mdn/content/commit/2f43f506240fa6c866cc3bc2d018364ae49421d9
* Document last modified: 2024-04-02T11:27:49.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting this one. I think you may have missed the prose above the example:

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use#example

>The following example shows how to use the use element to draw a circle with a different fill and stroke color. In the last circle, stroke="red" will be ignored because stroke was already set on myCircle. 

Does that make sense?

**Comment by georgernstgraf** [comment]
Oh it does. I'm sorry, and thank you too!

**Comment by bsmth** [comment]
Great, I'm glad that's cleared up 🙌🏻
