### ISSUE TITLE
Missing CSS properties defined in SVG

### ISSUE THREAD

**Issue by estelle** [mdn/content#34763]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/

### What specific section or headline is this issue about?

missing content: Several formerly SVG-only features are now supported as CSS properties. They need to be documented.

### What information was incorrect, unhelpful, or incomplete?

These pages are missing:

- [x] [`clip-rule`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-rule)
- [x] [`color-interpolation-filters`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-interpolation-filters) (Redirects to SVG)
- [x] [`cx`](https://developer.mozilla.org/en-US/docs/Web/CSS/cx)
- [x] [`cy`](https://developer.mozilla.org/en-US/docs/Web/CSS/cy)
- [x] [`dominant-baseline`](https://developer.mozilla.org/en-US/docs/Web/CSS/dominant-baseline) (Redirects to SVG)
- [x] [`fill`](https://developer.mozilla.org/en-US/docs/Web/CSS/fill) (Redirects to SVG)
- [x] [`fill-opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/fill-opacity) (Redirects to SVG)
- [x] [`fill-rule`](https://developer.mozilla.org/en-US/docs/Web/CSS/fill-rule) (Redirects to SVG)
- [x] [`marker`](https://developer.mozilla.org/en-US/docs/Web/CSS/marker) 
- [x] [`marker-end`](https://developer.mozilla.org/en-US/docs/Web/CSS/marker-end) (Redirects to SVG)
- [x] [`marker-mid`](https://developer.mozilla.org/en-US/docs/Web/CSS/marker-mid) (Redirects to SVG)
- [x] [`marker-start`](https://developer.mozilla.org/en-US/docs/Web/CSS/marker-start) (Redirects to SVG)
- [x] [`r`](https://developer.mozilla.org/en-US/docs/Web/CSS/r)
- [x] [`rx`](https://developer.mozilla.org/en-US/docs/Web/CSS/rx)
- [x] [`ry`](https://developer.mozilla.org/en-US/docs/Web/CSS/ry)
- [x] [`shape-rendering`](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-rendering) (Redirects to SVG)
- [x] [`stop-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/stop-color) (Redirects to SVG)
- [x] [`stop-opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/stop-opacity) (Redirects to SVG)
- [x] [`stroke`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke) (Redirects to SVG)
- [x] [`stroke-dasharray`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-dasharray) (Redirects to SVG)
- [x] [`stroke-dashoffset`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-dashoffset) (Redirects to SVG)
- [x] [`stroke-linecap`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-linecap) (Redirects to SVG)
- [x] [`stroke-linejoin`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-linejoin) (Redirects to SVG)
- [x] [`stroke-miterlimit`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-miterlimit) (Redirects to SVG)
- [x] [`stroke-opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-opacity) (Redirects to SVG)
- [x] [`stroke-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-width) (Redirects to SVG)
- [x] [`text-anchor`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-anchor) (Redirects to SVG)
- [x] [`vector-effect`](https://developer.mozilla.org/en-US/docs/Web/CSS/vector-effect)
- [x] [`x`](https://developer.mozilla.org/en-US/docs/Web/CSS/x)
- [x] [`y`](https://developer.mozilla.org/en-US/docs/Web/CSS/y)

Please update the [spreadsheet of missing properties](https://docs.google.com/spreadsheets/d/1ZBwg8OHefqzMjlTnHs9px6cBRLQQO49MKZQiiMoqc1A/edit?usp=sharing) if working on this project. Thank you.

### What did you expect to see?

these properties documented

### Do you have any supporting links, references, or citations?

https://drafts.fxtf.org/fill-stroke/

**Comment by meyerweb** [comment]
I should be able to work on this.  If anyone else wants to work on this, let me know so we don’t step on each other’s toes.

**Comment by estelle** [comment]
> I should be able to work on this. If anyone else wants to work on this, let me know so we don’t step on each other’s toes.

Please "claim" the page you're working on by checking the checkbox 
   - [X] Someone is working on this one

**Comment by Josh-Cena** [comment]
@estelle How was the list made? For example, properties defined in https://drafts.csswg.org/css-inline-3/, such as `baseline-shift`, have SVG pages but not CSS pages, and I don't see them in this table.

**Comment by estelle** [comment]
Removing `word-wrap` from this issue as it is unrelated to SVG.
All SVG properties have now been documented.
This project is complete and can be closed when the PRs are merged.
