### ISSUE TITLE
shorthand property list: missing properties

### ISSUE THREAD

**Issue by estelle** [mdn/content#34788]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties

### What specific section or headline is this issue about?

see also 

### What information was incorrect, unhelpful, or incomplete?

The see also section includes a list of the shorthand properties. Instead, this list should be its own section with a header.
This list should include all the shorthand properties; the missing ones , such as  `position-try`, need to be added to the list.

### What did you expect to see?

either no list or a complete list.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/shorthand_properties`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/shorthand_properties/index.md
* Last commit: https://github.com/mdn/content/commit/693c8b0befd8ca3d2ea20a7988d844e21309264a
* Document last modified: 2024-03-19T11:43:29.000Z

</details>

**Comment by estelle** [comment]
These are the ones I found:

-webkit-text-stroke
-webkit-border-before
-webkit-mask-box-image
all
animation
animation-range
background
border
border-block
border-block-end
border-block-start
border-bottom
border-color
border-image
border-inline
border-inline-end
border-inline-start
border-left
border-radius
border-right
border-style
border-top
border-width
column-rule
columns
contain-intrinsic-size
container
flex
flex-flow
font
font-synthesis
font-variant
gap
grid
grid-area
grid-column
grid-row
grid-template
inset
inset-block
inset-inline
list-style
margin
margin-block
margin-inline
mask
mask-border
offset
outline
overflow
overscroll-behavior
padding
padding-block
padding-inline
place-content
place-items
place-self
position-try
scroll-margin
scroll-margin-block
scroll-margin-inline
scroll-padding
scroll-padding-block
scroll-padding-inline
scroll-timeline
text-decoration
text-emphasis
text-underline-position
text-wrap
transition
view-timeline

**Comment by Josh-Cena** [comment]
Do you think it's better to remove the list or complete it @estelle? Are contributors expected to just copy the list over?

**Comment by estelle** [comment]
> Do you think it's better to remove the list or complete it @estelle? Are contributors expected to just copy the list above over?

There's no other list of shorthand properties that I know of, so i think we should actually keep the list but improve it. I set "good first issue" as the task is straightforward, and i don't have time to do it today. The task is to:
1) remove the current list from the see also section. 
2) double check that the list included above does indeed only include shorthand properties, 
2) check that the list didn't miss any shorthand properties, then 
3) create links for each shorthand as `{{cssxref("<property-name>")}}`, 
4) create a new section, and copy the list into a new section,
