### ISSUE TITLE
availability is incorrect for `@property`

### ISSUE THREAD

**Issue by trusktr** [mdn/content#34793]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@property

### What specific section or headline is this issue about?

The availability box at the top

### What information was incorrect, unhelpful, or incomplete?

It says it is not out in Firefox yet, but it just came out in FF 128! 🎉🥳🚀🎆  

### What did you expect to see?

Newly available in all browsers.

### Do you have any supporting links, references, or citations?

The compatibility at the bottom of the page says so hehe:

https://developer.mozilla.org/en-US/docs/Web/CSS/@property#browser_compatibility

### Do you have anything more you want to share?

Maybe the availability box is behind in getting updated? Is it automatic?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@property`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@property
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@property/index.md
* Last commit: https://github.com/mdn/content/commit/6fb57501591e0f774f9907d0881afe2000ba9071
* Document last modified: 2024-06-11T21:48:54.000Z

</details>

**Comment by Josh-Cena** [comment]
The top banner is not controlled by us. This is tracked in https://github.com/mdn/yari/issues/11366; the baseline package is always going to be slightly outdated.
