### ISSUE TITLE
Issue with "Referrer-Policy": Missing close parenthesis

### ISSUE THREAD

**Issue by spikecodes** [mdn/content#3479]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#directives

#### What information was incorrect, unhelpful, or incomplete?
There is a missing close parenthesis (`)`) in the description of the `no-referrer-when-downgrade` directive.

##### `no-referrer-when-downgrade`
> Send the origin, path, and querystring in Referer when the protocol security level stays the same or improves (HTTP→HTTP, HTTP→HTTPS, HTTPS→HTTPS. Don't send the Referer header for requests to less secure destinations (HTTPS→HTTP, HTTPS→file). 

#### What did you expect to see?
Instead of:
> (HTTP→HTTP, HTTP→HTTPS, HTTPS→HTTPS.

I expected to see:
> (HTTP→HTTP, HTTP→HTTPS, HTTPS→HTTPS).

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/referrer-policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/referrer-policy/index.html
* Last commit: https://github.com/mdn/content/commit/fc36604b19a172f3fbedb2629e2403180f2eda55
* Document last modified: 2021-03-19T23:16:59.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/3481 with a fix

**Comment by spikecodes** [comment]
Thank you for the prompt response. The pull request fix looks good!
