### ISSUE TITLE
font-palette demo may have rapid flashing

### ISSUE THREAD

**Issue by 2-www** [mdn/content#34790]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-palette

### What specific section or headline is this issue about?

Animating between two palettes

### What information was incorrect, unhelpful, or incomplete?

i opened the docs page, the demo font failed to load, and the text in serif font started flashing between black and white a few times a second

### What did you expect to see?

not frequent flashing when the font fails to load.
for example, have a toggle between the two states, for example a checkbox or a button, instead of an auto playing loop

### Do you have any supporting links, references, or citations?

https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold.html
> Individuals who have photosensitive seizure disorders can have a seizure triggered by content that flashes at certain frequencies for more than a few flashes.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-palette`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-palette
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-palette/index.md
* Last commit: https://github.com/mdn/content/commit/f22871b46c95c8f4d877c11587081d63bafed012
* Document last modified: 2024-02-29T21:45:29.000Z

</details>

**Comment by OnkarRuikar** [comment]
@2-www could you share your environment details? Such as the browser name, browser version, and operating system.

Let me know if [this fix](https://pr34802.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/font-palette#result) works.
