### ISSUE TITLE
Issue with "Django Tutorial Part 11: Deploying Django to produ…": (short summary here please)

### ISSUE THREAD

**Issue by TuanLuu54** [mdn/content#3480]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment

#### What information was incorrect, unhelpful, or incomplete?
Run: `python3 manage.py runserver` got error at section: 
```
STATIC_ROOT = BASE_DIR / 'staticfiles'  #. os.path.join(BASE_DIR, 'staticfiles')
```

#### Specific section or headline?
config `setting.py` in `Serving static files in production`

#### What did you expect to see?
```
STATIC_ROOT = BASE_DIR + '/staticfiles'  #. os.path.join(BASE_DIR, 'staticfiles')
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/deployment/index.html
* Last commit: https://github.com/mdn/content/commit/50bbefdadc6bfcb8860efdb95be1b9b538d119ff
* Document last modified: 2021-02-24T03:37:45.000Z

</details>

**Comment by nayaldivya** [comment]
Hey @hamishwillee, if you don't mind, I'd like to try my hands on this issue.

**Comment by hamishwillee** [comment]
@nayaldivya Please don't. It was fixed last week in another PR. Just waiting for that to merge.

**Comment by hamishwillee** [comment]
Actually, that other PR did fix this. However I've made the change #3507 to remove the comment.

Note, this should not have been a problem because it is a comment, and should not affect building. However the comment is unhelpful anyway, so removed.
