### ISSUE TITLE
String.prototype.slice() endIndex conversion behavior is incorrect

### ISSUE THREAD

**Issue by iam-pranjal1** [mdn/content#34804]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice

### What specific section or headline is this issue about?

If indexEnd is cannot be converted to a number to the end of the string, slice() extracts to the end of the string.

### What information was incorrect, unhelpful, or incomplete?

```js
let fullName = "Pranjal";

console.log(`The length of the ${fullName}  ${fullName.length} `);  //lenght is 7

console.log("When the endIndex can't converted into the number  ",fullName.slice(0,'q'));
```

### What did you expect to see?

However, according to the statement output should be Pranjal but it gives output as an empty string.

### Do you have any supporting links, references, or citations?

https://replit.com/@pranjalcodesai/endIndex-handling-or-Stringprototypeslice

### Do you have anything more you want to share?

In the above code, my fullName (variable) length is 7.
I passed endIndex as 'q' a character that can't converted to a number.
However, according to the statement output should be Pranjal but it gives output as an empty string.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/slice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/slice/index.md
* Last commit: https://github.com/mdn/content/commit/4406757f6bb4404b5309756bac2acb994c169e40
* Document last modified: 2024-06-04T07:12:37.000Z

</details>

**Comment by Josh-Cena** [comment]
Thanks for the issue! You are right, `indexEnd` being `undefined` is treated differently from when it can't be converted to a number:

> 8. If end is undefined, let intEnd be len; else let intEnd be ? [ToIntegerOrInfinity](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tointegerorinfinity)(end).

And ToIntegerOrInfinity would convert `NaN` to `0` instead of `Infinity`, so anything that can't be converted is in fact equal to `0`.

**Comment by iam-pranjal1** [comment]
> Thanks for the issue! You are right, `indexEnd` being `undefined` is treated differently from when it can't be converted to a number:
> 
> > 8. If end is undefined, let intEnd be len; else let intEnd be ? [ToIntegerOrInfinity](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tointegerorinfinity)(end).
> 
> And ToIntegerOrInfinity would convert `NaN` to `0` instead of `Infinity`, so anything that can't be converted is in fact equal to `0`.
@Josh-Cena 
Thanks for considering my issues and clarifying them.
