### ISSUE TITLE
No information about the triggering reflow in the `innerText` property page.

### ISSUE THREAD

**Issue by cvgalagan** [mdn/content#34831]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText

### What information was incorrect, unhelpful, or incomplete?

There isn't any information about the triggering reflow and why it happens, unlike [the page](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext) about `textContent` property. 

### What did you expect to see?

The page includes information about the reflow process because it extremely influences performance. The same information is contained within [the page](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext) about the `textContent` property.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/innertext`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/innertext/index.md
* Last commit: https://github.com/mdn/content/commit/a3d9f61a8990ba7b53bda9748d1f26a9e9810b18
* Document last modified: 2023-04-07T00:39:15.000Z

</details>

**Comment by Josh-Cena** [comment]
This is tracked in https://github.com/mdn/content/issues/26330
