### ISSUE TITLE
[WebAPI] GeolocationCoordinates & GeolocationPosition should expose to.JSON()

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#34841]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [ ] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1890706

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Status

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/23730
- [ ] Docs - already good [`GeolocationCoordinates.toJSON()`](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/toJSON), [`GeolocationPosition.toJSON()`](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPosition/toJSON)
- [ ] Release note
- [ ] dev-docs-complete

**Comment by hamishwillee** [comment]
FYI @Josh-Cena I don't close my FF issues because originally I assumed that whoever is going through and finalising the release might want to do that as part of agreeing "yes, all this work is done". 

I suspect that no one does that so happy for you to close these and perhaps I should start doing so.

**Comment by Josh-Cena** [comment]
Ah OK. I was asking on Slack when y'all would like Firefox issues to be closed, but it got buried among many other messages. I assumed that the project board was good enough for tracking purposes so I was aggressive with closing FF issues. In the future I would close after the release is done.

**Comment by hamishwillee** [comment]
@Josh-Cena I think it is better to beg forgiveness than ask for permission in this case. Please close aggressively (or to suit your process) and if anyone complains we can adjust - and you can blame me :-)
