### ISSUE TITLE
[Glossary] Static site generator (SSG)

### ISSUE THREAD

**Issue by bsmth** [mdn/content#34867]
### Proposal

We should have a glossary page for SSGs

### Tasks

- [ ] SSG Glossary entry

### Are you willing to support this work?

yes

**Comment by estelle** [comment]
Should we do a SSR - server side rendering page?

**Comment by Josh-Cena** [comment]
I'm happy to write it if you send an issue

**Comment by estelle** [comment]
> I'm happy to write it if you send an issue

https://github.com/mdn/content/issues/36183 😃
