### ISSUE TITLE
Content bug: many syntax snippets incorrectly use static Interface.member style

### ISSUE THREAD

**Issue by foolip** [mdn/content#3487]
## What page(s) did you find the problem on?

I found and fixed a number of these in https://github.com/mdn/content/pull/3452.

## What is the problem?

The syntax snippets have been copied from the page title, and can be something like `var sinkId = HTMLMediaElement.sinkId`. This doesn't work, because `sinkId` is not a static member of `HTMLMediaElement`, it's on the prototype.

## What did you expect to see?

Examples like this need to be `var sinkId = mediaElement.sinkId` or similar.

## Did you test this? If so, how?

I searched using `git grep -E '= [A-Z][A-Za-z0-9]+\.'`. Many legitimate cases like `Math.*` and `JSON.*` show up, but there are still many incorrect cases left.

**Comment by foolip** [comment]
This came up in https://discourse.mozilla.org/t/incorrect-titles-for-method-property-articles/31641.

**Comment by sideshowbarker** [comment]
This is now being tracked in https://github.com/mdn/content/discussions/5121
