### ISSUE TITLE
Content bug: Missing documentation on WebAuthn Level 2 additions

### ISSUE THREAD

**Issue by dontcallmedom** [mdn/content#3488]
## What page(s) did you find the problem on?
https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse
https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/authenticatorSelection
https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/attestation
https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/extensions
https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/getClientExtensionResults
https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorResponse/clientDataJSON

## What is the problem?
The Web Authentication Level 2 specification introduces a number of changes that have not been reflected in the MDN documentation yet:
*  AuthenticatorAttestationResponse.getAuthenticatorData(), AuthenticatorAttestationResponse.getPublicKey() and AuthenticatorAttestationResponse.getPublicKeyAlgorithm() aren't documented in https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse
* the residentKey parameter of authenticatorSelection is not documented in 
https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/authenticatorSelection
* the value "enterprise" is not documented in
https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/attestation
* appid, appidExclude, credProps, largeBlob aren't documented in
https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/extensions
* conversely, authnSel, exts, uvi, loc, biometricPerfBounds are listed there, but have been removed from level 2
* none of the output extensions (not even the level 1)  are documented
in https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/getClientExtensionResults
* the "crossOrigin" property of AuthenticatorResponse.clientDataJSON is
not documented in
https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorResponse/clientDataJSON
* in that same page, tokenBindingId should be renamed tokenBinding

(as initially [reported in the WebAuthn Adoption Community Group](https://lists.w3.org/Archives/Public/public-webauthn-adoption/2021Mar/0003.html))

**Comment by chrisdavidmills** [comment]
I'm thinking maybe you could grab this one @Rumyra , you know, once we get into your "next phase of MDN work"

**Comment by Rumyra** [comment]
Thanks @chrisdavidmills 😅 going to modify the labels to reflect 👍

**Comment by dontcallmedom** [comment]
@rumyra is this being part of planned work at this time? I'm trying to figure if/how to bring outside resources to work on this. Thanks!

**Comment by Rumyra** [comment]
Hi @dontcallmedom :) No being the short answer - only because resources for it are thin on the ground. If there's someone suitable please by all means bring them - happy to help support 👍

**Comment by chrisdavidmills** [comment]
Thanks @Josh-Cena ; I had a look at the list, and I'm pretty sure all of these items got done. So, closing.
