### ISSUE TITLE
Cache API is listed as a Service Worker API, but the API is not specific to Service Workers

### ISSUE THREAD

**Issue by mfulton26** [mdn/content#34889]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Cache

### What specific section or headline is this issue about?

.sidebar-inner-nav

### What information was incorrect, unhelpful, or incomplete?

The first listed `.section` is to [Service Worker API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) but this can be misleading. I work with various engineers who still think that `caches` can only be used in service workers. 😞 

### What did you expect to see?

Nothing that could lead someone to gather that the Cache API is only available in and useful in service workers.

### Do you have any supporting links, references, or citations?

The page itself mentions this:

> You don't have to use it in conjunction with service workers, even though it is defined in the service worker spec.

But as `caches` is defined in the `window` I'd like to see that better represented.

### Do you have anything more you want to share?

MDN is great. I am grateful for all the well-organized, thorough documentation available!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/cache`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Cache
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/cache/index.md
* Last commit: https://github.com/mdn/content/commit/89c435da452257b944b403cc9e45036fcb22590e
* Document last modified: 2024-02-05T10:15:39.000Z

</details>

**Comment by Josh-Cena** [comment]
Are you saying the sidebar should not say "Service Worker API"? Every interface has to be associated with an API group, and because this one is defined in the service worker spec, it's the best place to put it, because we can't invent new API names.

**Comment by mfulton26** [comment]
> Are you saying the sidebar should not say "Service Worker API"?

Ideally, yes.

> Every interface has to be associated with an API group

[IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) is its own group. Could "Cache API" be made to put it under so that folks viewing the sidebar won't view `Cache` as something under/specific-to the Service Worker API?

**Comment by Josh-Cena** [comment]
IndexedDB API has its own [spec](https://w3c.github.io/IndexedDB/), so I'm not sure why it should be something else. Every spec creates one API group; sometimes we can merge multiple specs into one group, but I don't think we've ever split a spec into multiple groups, because that means we have to invent names ourselves. This is the same situation as https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer: `DataTransfer` is used in many APIs, but it's defined in HTML Drag & Drop, so that's reflected in the sidebar, although the content will mention it can be used for other purposes. That's just an MDN convention and doesn't map to any normative statements / suggestions.

**Comment by mfulton26** [comment]
Okay. I'm glad I'm learning here. I do feel like it can be a little misleading: a big bold section name that says what spec it comes from can be interpreted as what scope it is applicable for at a quick glance. I do think folks should actually _read_ things at which point this wouldn't be a concern. I'm not sure what to suggest so we should probably close this. I appreciate you exploring this with me.

**Comment by Josh-Cena** [comment]
> a big bold section name that says what spec it comes from can be interpreted as what scope it is applicable for at a quick glance

Unfortunately that's not true: it just tells you what you can typically use it for. Of course you can still use utility interfaces for totally unrelated purposes.


> I do think folks should actually _read_ things at which point this wouldn't be a concern.

My thought too. If `Cache` exists in window and `Window.caches` exists, what's there stopping you from using it even if you don't use service workers? Names are, well, just names after all. They don't control you.

Thanks for understanding!
