### ISSUE TITLE
Issue with "Planned changes to shared memory": Not planned anymore.

### ISSUE THREAD

**Issue by Elchi3** [mdn/content#3489]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes

#### What information was incorrect, unhelpful, or incomplete?
The presented changes aren't planned anymore. They are shipped in Firefox and in Chrome at least.

#### Specific section or headline?
No specific headline. Context of the whole page.

#### What did you expect to see?

COOP and COEP explained so that I can use SAB.

#### Did you test this? If so, how?
I didn't! It came up in https://github.com/mdn/browser-compat-data/pull/9600#discussion_r601284484

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/sharedarraybuffer/planned_changes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/sharedarraybuffer/planned_changes/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by hamishwillee** [comment]
This will also require a BCD update.
