### ISSUE TITLE
inset-area is now renamed to position-area

### ISSUE THREAD

**Issue by nt1m** [mdn/content#34893]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/inset-area
https://developer.mozilla.org/en-US/docs/Web/CSS/inset-area_value

### What information was incorrect, unhelpful, or incomplete?

inset-area name got changed to position-area

### What did you expect to see?

position-area

### Do you have any supporting links, references, or citations?

CSSWG resolution: https://github.com/w3c/csswg-drafts/issues/10209#issuecomment-2221005001
Chrome intent to ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/D-vUkcOSHEg/m/WZ8hHHVbAgAJ

**Comment by chrisdavidmills** [comment]
Thanks for filing, @nt1m!

I've got this on my radar already. It is scheduled to ship in Chrome 129 in early September, so if I start this in mid-August, we should be all good.
