### ISSUE TITLE
Issue with "this": …

### ISSUE THREAD

**Issue by Vterebenin** [mdn/content#349]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

#### What information was incorrect, unhelpful, or incomplete?
In "this in function contexts" part text direction having rtl direction somehow.

#### Specific section or headline?
In "this in function contexts" part

#### What did you expect to see?
It probably has to be ltr rather than rtl

#### Did you test this? If so, how?
Reloaded page several times and tried different resolutions. And there is still incorrect direction somehow. 
I think, that it could be easily fixed, if you guys change the attribute 'dir' of this part, i guess?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/this`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/operators/this/index.html
* Report started: 2020-12-17T10:58:05.034Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I think we have this fixed in the sources, by https://github.com/mdn/content/commit/adf4741 (see https://github.com/mdn/content/issues/320).
