### ISSUE TITLE
Pointer Events incoherence 

### ISSUE THREAD

**Issue by erwanvivien** [mdn/content#34904]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Using_Pointer_Events

### What specific section or headline is this issue about?

Tracking new touches

### What information was incorrect, unhelpful, or incomplete?

https://github.com/mdn/content/blob/main/files/en-us/web/api/pointer_events/using_pointer_events/index.md?plain=1#L73-L88

### What did you expect to see?

variable `i` is not defined, `touches` is not defined I think it should be `ongoingTouches` as for `i` I'm not sure 

Happy to do a pull request but I don't know about `i` would probably be replaced by 
```js
  const idx = ongoingTouchIndexById(evt.pointerId);
```

**Comment by Josh-Cena** [comment]
This example is clearly buggy but we don't know what the intent is. Would be cool if you or someone else can figure it out. The best outcome is if it can be turned into a live sample.

**Comment by erwanvivien** [comment]
I'm not familiar with the process for "if it can be turned into a live sample" could you explain a bit more?

**Comment by Josh-Cena** [comment]
See our documentation: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples A live sample is an embedded iframe showing the rendered output of the code blocks on this page.

**Comment by erwanvivien** [comment]
Thanks Josh will check

**Comment by erwanvivien** [comment]
I've put up a draft PR if you want to guide me

I've added only the code... I'm not great for the explanations
