### ISSUE TITLE
Typo: React interactivity: Editing, filtering, conditional rendering

### ISSUE THREAD

**Issue by chasead91** [mdn/content#34912]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_interactivity_filtering_conditional_rendering

### What specific section or headline is this issue about?

Editing from the UI

### What information was incorrect, unhelpful, or incomplete?

Code snip after 8th paragraph from the top (previous line is "At this point, your Todo.jsx file should look like this:").

The onClick event handler on the  delete button in the viewTemplate constant currently shows an extra closing curly bracket:

onClick={() => {
    setEditing(true);
}}>

### What did you expect to see?

onClick={() => {
    setEditing(true);
}>

**Comment by Josh-Cena** [comment]
The current one is correct. The outer bracket is for embedded JSX expressions, the inner bracket is for the callback body.
