### ISSUE TITLE
Enhancement: Open external links in a new tab

### ISSUE THREAD

**Issue by harisalimughal** [mdn/content#34916]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Functions

### What specific section or headline is this issue about?

Prerequisites section

### What information was incorrect, unhelpful, or incomplete?

Currently, external links open in the same tab, disrupting the user experience by making it difficult to navigate back to the MDN documentation after visiting an external link.

### What did you expect to see?

I expected external links to open in a new tab, allowing users to explore external resources without losing their place in the MDN documentation.

### Do you have anything more you want to share?

To improve the user experience, I suggest adding the target="_blank" attribute to all external links in the markdown files. This ensures that external links open in a new tab, preventing users from losing their place in the documentation. Here's an 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/functions/index.md
* Last commit: https://github.com/mdn/content/commit/7e97f3c5ada65b6638909bde92881a4b8d46a2b8
* Document last modified: 2024-07-02T03:47:33.000Z

</details>

**Comment by Josh-Cena** [comment]
Which links are you referring to? External links on the page already open in new tables.

**Comment by harisalimughal** [comment]
I'm talking about the links like if you go on this page [Js Functions](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Functions#functions_versus_methods). If you look in start of the page there is a table having link to "JavaScript first steps" under "Prerequisites". It opens in the same tab. There are lots of other links of this type which open in the same tab.

**Comment by Josh-Cena** [comment]
These pages are not external links. Internal links are expected to open in the same tab—that's a design feature, not a bug. Internal links that open in new tabs loose context of the page (such as focus) and are very hostile to screen readers. If you want to open in a new tab, Ctrl+click it instead.
