### ISSUE TITLE
Descriptions of orientation values missing

### ISSUE THREAD

**Issue by jms72** [mdn/content#34927]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Manifest/orientation

### What information was incorrect, unhelpful, or incomplete?

It's not obvious what the different values mean. E.g. `portrait-primary` what does it mean?

Also what is the default if none is specified.

### What did you expect to see?

An explanation for each value, and which is the default.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/manifest/orientation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/orientation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/manifest/orientation/index.md
* Last commit: https://github.com/mdn/content/commit/de2ef1e9950eebbacdd55f072dfe03014d113bbd
* Document last modified: 2024-07-13T01:34:51.000Z

</details>

**Comment by Josh-Cena** [comment]
There is no default value. If unspecified, it just means the app can be rotated freely. I believe if specified, rotating the device no longer changes the orientation, and it can only be changed programmatically, but it would be useful to verify that. The orientation values are defined in https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock; we should link to it.
