### ISSUE TITLE
Behavior of colors in gradient-images differes between browsers

### ISSUE THREAD

**Issue by htran-ubed** [mdn/content#34926]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

### What specific section or headline is this issue about?

Styling based on color schemes

### What information was incorrect, unhelpful, or incomplete?

Missing information on behavior when using scheme-dependent color in gradient functions.

### What did you expect to see?

Colors like Canvas, CanvasText and light-dark(silver, blue) are rendered as expected for the different color-schemes.

However, when used inside an image-gradient, the gradient-colors respect the color-scheme in Firefox, but not in Chrome and Safari.

`div {
	color-scheme: light dark;
	color: CanvasText;
	border: 4px solid light-dark(silver, blue);
	background-image: linear-gradient(Canvas, light-dark(silver, blue));
}
.light {
	color-scheme: light;
}
.dark {
	color-scheme: dark;
}`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/color-scheme`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/color-scheme/index.md
* Last commit: https://github.com/mdn/content/commit/5f13cbe7517ce96deeb521d4c8e6923266a22913
* Document last modified: 2024-04-25T17:43:13.000Z

</details>

**Comment by htran-ubed** [comment]
This seems to be a browser issue for certain cases. I found that it all seems to work for CSS properties in child elements, or when assigning the linear-gradient to a CSS variable first.

**Comment by htran-ubed** [comment]
This seems to be a browser issue for certain cases. I found that it all seems to work for CSS properties in child elements, or when assigning the linear-gradient to a CSS variable first.

**Comment by Josh-Cena** [comment]
Could you make a self-contained example illustrating your issue?

```html
<!doctype html>
<html>
  <head>
    <title></title>
    <meta charset="utf-8" />
    <style>
      section {
        margin: 10px;
      }
      div {
        color-scheme: light dark;
        color: CanvasText;
        border: 4px solid light-dark(silver, blue);
        width: 400px;
        height: 400px;
        background-image: linear-gradient(Canvas, light-dark(silver, blue));
      }
      .light {
        color-scheme: light;
      }
      .dark {
        color-scheme: dark;
      }
    </style>
  </head>
  <body>
    <div class="light"></div>
  </body>
</html>
```

This displays the right colors when you change the class name of the `div` in Chrome/Safari.

**Comment by htran-ubed** [comment]
```<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Light dark</title>
	<style>
		:root {
			color-scheme: light dark;
			--background: linear-gradient(Canvas, light-dark(lightblue, darkblue));
		}

		div, header, main, footer {
			margin: 15px;
			padding: 10px;
			text-align: center;
			border: 2px solid CanvasText;
		}

		div {
			font-family: Verdana;		
			width: 400px;

			color: CanvasText;
			font-weight: bold;
			background-image: var(--background);			
		}

		.light {
			color-scheme: light;
		}

		.dark {
			color-scheme: dark;
		}

		header {
			background-image: linear-gradient(Canvas, light-dark(lightblue, darkblue));
		}

		main {
			background-color: Canvas;
		}

		footer {
			background-image: var(--background);
		}
	</style>
</head>
<body>
	<div>
		<header>Header</header>
		<main>Normal <input value="normal" /></main>
		<footer>Footer</footer>
	</div>

	<div class="light">
		<header>Header</header>
		<main>Light <input value="light" /></main>
		<footer>Footer</footer>
	</div>

	<div class="dark">
		<header>Header</header>
		<main>Dark <input value="dark" /></main>
		<footer>Footer</footer>
	</div>
</body>
</html>

**Comment by OnkarRuikar** [comment]
> This seems to be a browser issue for certain cases. I found that it all seems to work when assigning the linear-gradient to a CSS variable first.

Looks like [a bug](https://issues.chromium.org/issues/354255356) to me:

https://github.com/user-attachments/assets/06f3ef69-7ef1-440c-8f87-aa1c69f7b76c

**Comment by Josh-Cena** [comment]
Closing it as a browser bug; would see how the Chromium bug turns out and action accordingly (i.e. reopen if the content is actually wrong).
