### ISSUE TITLE
Very minor typo - "it's" should be "its".  "it's" is a contraction, "its" is possessive.

### ISSUE THREAD

**Issue by LarryAnglin** [mdn/content#3493]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await

#### What information was incorrect, unhelpful, or incomplete?
Incorrect use of "it's" vs. "its".

#### Specific section or headline?
The await keyword

#### What did you expect to see?
 "...however it can be used on its own with JavaScript modules."  instead of "... however it can be used on it's own with JavaScript modules."

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/async_await`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/async_await/index.html
* Last commit: https://github.com/mdn/content/commit/fc36604b19a172f3fbedb2629e2403180f2eda55
* Document last modified: 2021-03-19T23:16:59.000Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this, @LarryAnglin ! Fixed with https://github.com/mdn/content/commit/79f50609cb6bcb66e36cc3f9c4fa0537870b1b9a
