### ISSUE TITLE
Only the request to access the Notifications API is restricted to user interaction

### ISSUE THREAD

**Issue by jwatt** [mdn/content#34945]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API

### What specific section or headline is this issue about?

Concepts and usage

### What information was incorrect, unhelpful, or incomplete?

The text says:

> going forward browsers will explicitly disallow notifications not triggered in response to a user gesture

That's incorrect. Only requests to access the Notifications API are restricted to being made in response to a user gesture. Once that's obtained, notifications are not restricted.

### What did you expect to see?

At this point the restriction has been in place so long that I suggest simply deleting this entire paragraph, and in the preceeding paragraph (the one just before the example) replace this text:

> This should be done in response to a user gesture, such as clicking a button, for example

with:

> This method can only be called when handling a user gesture, such as when handling a mouse click. For example:

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/notifications_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/notifications_api/index.md
* Last commit: https://github.com/mdn/content/commit/e4c0939929e1b3e1fa3fd3da82b827fca3ed4c79
* Document last modified: 2024-03-06T06:22:42.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @jwatt - much appreciated and fixed in https://github.com/mdn/content/pull/34959

Note that I had to say "This method **should** only be called ..." because there is no evidence I can see that the spec requires transient activation or that the other browsers enforce that. The browser compat data does still indicate this need for Firefox.

**Comment by jwatt** [comment]
Looks good to me. Thanks, Hamish!
