### ISSUE TITLE
deleteFromDocument deletes more than just text

### ISSUE THREAD

**Issue by John-Page** [mdn/content#34943]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Selection/deleteFromDocument

### What specific section or headline is this issue about?

First paragraph

### What information was incorrect, unhelpful, or incomplete?

It says the method deletes the  text in the selection   This implies (to me anyway) that it deleted the text nodes or perhaps empties them out.   In my tests it actually deletes everything in the selection.    I have a div full of text, embedded divs., images etc.  If I select the whole thing and call  deleteFromDocument(), the embedded divs imgs etc are completely removed.    (That's good - that's what was hoping).  

### What did you expect to see?

Clarity on what is actually removed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/selection/deletefromdocument`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Selection/deleteFromDocument
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/selection/deletefromdocument/index.md
* Last commit: https://github.com/mdn/content/commit/f2f9346c0c0e9f6676f2df9f1850933e274401de
* Document last modified: 2023-04-08T06:00:31.000Z

</details>

**Comment by Josh-Cena** [comment]
This method just calls https://developer.mozilla.org/en-US/docs/Web/API/Range/deleteContents, and I agree both methods' pages are very thin. They should mention what exactly gets deleted.
