### ISSUE TITLE
Outdated links to dev.opera articles are redirected to blogs.opera.com/news

### ISSUE THREAD

**Issue by tineprincic1** [mdn/content#34951]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works

### What specific section or headline is this issue about?

Links under "See also" section are outdated

### What information was incorrect, unhelpful, or incomplete?

The following links are all redirected to https://blogs.opera.com/news/. I was unable to find the articles on the web.
The links that do not work:
[HTTP — an Application-Level Protocol]
[HTTP: Let's GET It On!]
[HTTP: Response Codes]

### What did you expect to see?

The linked articles on the dev.opera website.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/how_the_web_works`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/how_the_web_works/index.md
* Last commit: https://github.com/mdn/content/commit/d451eec65d8fc6cdc0d0b8a8033c11f4625b0000
* Document last modified: 2023-11-17T05:50:24.000Z

</details>

**Comment by gagan-bhullar-tech** [comment]
@Josh-Cena Unable to find correct links in  https://blogs.opera.com/news.  Can you please point me where can I find the links.

**Comment by Josh-Cena** [comment]
I don't know where they are or if they still exist at all. If no one is able to point us to the new location we may need to remove these links entirely.
