### ISSUE TITLE
Wrong mention of inline layers in example

### ISSUE THREAD

**Issue by DrFlowerkick** [mdn/content#34953]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers

### What specific section or headline is this issue about?

Determining the precedence based on the order of layers

### What information was incorrect, unhelpful, or incomplete?

Unde the example it states "In this example, there are two inline layers A and B without styles, a block of unlayered styles, and two blocks of styles in named layers A and B." The mentioned layers A and B are defined with "@layer A, B;" in the CSS code block.

### What did you expect to see?

A and B are not inline layers, but instead "normal" author layers.

### Do you have any supporting links, references, or citations?

A few sentences above it states "Inline styles are declared using the [style attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style)."

### Do you have anything more you want to share?

Thanks for your great guides :)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_layers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_layers/index.md
* Last commit: https://github.com/mdn/content/commit/4a7f7ed0652478c50443f74acc3d969342dd312b
* Document last modified: 2024-06-10T14:33:06.000Z

</details>

**Comment by Josh-Cena** [comment]
Based on this text I think this is strictly referring to the `@layer A, B;` part, but I don't know why we are calling them "inline layers"; we haven't used this terminology anywhere else.

@estelle wrote this so perhaps she can clarify.

**Comment by estelle** [comment]
> Based on this text I think this is strictly referring to the `@layer A, B;` part, but I don't know why we are calling them "inline layers"; we haven't used this terminology anywhere else.
> 
> @estelle wrote this so perhaps she can clarify.

I should not have used the term "inline".  I should have used "statement".
