### ISSUE TITLE
Summary paragraph for HTTP status code 412 refers to If-None-Match but this should be If-Match

### ISSUE THREAD

**Issue by jesperdj** [mdn/content#34965]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412

### What specific section or headline is this issue about?

Summary paragraph (at the top)

### What information was incorrect, unhelpful, or incomplete?

The paragraph says: "...when the condition defined by the [If-Unmodified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Unmodified-Since) or [If-None-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) headers is not fulfilled"

### What did you expect to see?

"...when the condition defined by the [If-Unmodified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Unmodified-Since) or [If-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match) headers is not fulfilled"

Status code 412 should be returned if you update an entity (POST / PATCH / PUT) and the value in the If-Match header is not up-to-date with what the server thinks it should be. The paragraph refers to If-None-Match, but this should be If-Match.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests

**Comment by Josh-Cena** [comment]
@bsmth could you take a look at this and possibly add it to https://github.com/mdn/content/pull/34620?

**Comment by bsmth** [comment]
Nice, thank you for reporting and for tagging me, Josh. The linked PR should address this issue.
