### ISSUE TITLE
firstInstance only supported if requested, otherwise only works if firstInstance is 0

### ISSUE THREAD

**Issue by jagenjo** [mdn/content#34976]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/GPURenderPassEncoder/drawIndexedIndirect

### What specific section or headline is this issue about?

firstInstance

### What information was incorrect, unhelpful, or incomplete?

No info about firstInstance not working if not requested on device.

### What did you expect to see?

"firstInstance must be 0 unless you require "indirect first instance" for device.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/gpurenderpassencoder/drawindexedindirect`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/GPURenderPassEncoder/drawIndexedIndirect
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/gpurenderpassencoder/drawindexedindirect/index.md
* Last commit: https://github.com/mdn/content/commit/89c435da452257b944b403cc9e45036fcb22590e
* Document last modified: 2024-02-05T10:15:39.000Z

</details>

**Comment by Josh-Cena** [comment]
Relevant spec:

> The value corresponding to firstInstance must be 0, unless the ["indirect-first-instance"](https://gpuweb.github.io/gpuweb/#indirect-first-instance) [feature](https://gpuweb.github.io/gpuweb/#feature) is enabled. If the ["indirect-first-instance"](https://gpuweb.github.io/gpuweb/#indirect-first-instance) [feature](https://gpuweb.github.io/gpuweb/#feature) is not enabled and firstInstance is not zero the [drawIndexedIndirect()](https://gpuweb.github.io/gpuweb/#dom-gpurendercommandsmixin-drawindexedindirect) call will be treated as a no-op.
