### ISSUE TITLE
Playground example not working in deleteFromDocument page

### ISSUE THREAD

**Issue by gagan-bhullar-tech** [mdn/content#34970]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Selection/deleteFromDocument

### What information was incorrect, unhelpful, or incomplete?

Playground example not working. Reproducible steps:

1. Go to https://developer.mozilla.org/en-US/docs/Web/API/Selection/deleteFromDocument
2. Click on `play` icon in example
3. Select text in the console
4. Click `Delete selected text` button

### What did you expect to see?

Playground example should delete selected text.

**Comment by Josh-Cena** [comment]
Which browser are you using? Works in my Chrome, Firefox, and Safari.

**Comment by Josh-Cena** [comment]
Ah, I see you are trying to delete things from the console. That's not how it works. The console is not part of the page. You need to select a part of the text that says "Try highlighting some of the text in this paragraph. Once you do, you can remove the selected content by clicking the button below.".
