### ISSUE TITLE
minor issue with Active learning: More color choices

### ISSUE THREAD

**Issue by Blitzbitz** [mdn/content#34992]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals

### What specific section or headline is this issue about?

function outputDocument(code)  on line 770

### What information was incorrect, unhelpful, or incomplete?

[Active learning: More color choices]
The option values are in lowercase , the label values have an uppercase first letter.
 

### What did you expect to see?

The live example doesn't the option values  this so I assumed the option values would match the label values.
I was able to find the mistake using show solution, but not before being confused as to why my code wasn't working

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/conditionals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/conditionals/index.md
* Last commit: https://github.com/mdn/content/commit/af1e384356e21dbcc573d1c1cc015ec79c644de1
* Document last modified: 2024-06-14T05:38:35.000Z

</details>

**Comment by Josh-Cena** [comment]
Open to add one sentence after this line:

> For each case, the choice should equal one of the possible `<option>` values that can be selected, that is, `white`, `black`, `purple`, `yellow`, or `psychedelic`.

Which says something similar to:

> Note that the option values are lowercase, while the option _labels_, as displayed in the live output, are capitalized. You should use the lowercase values in your code.

Do you want to try to send a PR?
