### ISSUE TITLE
Issue with "object-fit": there's no DIVs in the example HTML

### ISSUE THREAD

**Issue by rodrigo1406** [mdn/content#3499]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

#### What information was incorrect, unhelpful, or incomplete?
missing DIVs

#### Specific section or headline?
Examples/HTML

#### What did you expect to see?
The DIVs where the IMGs are contained

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/object-fit`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/object-fit/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by NegiAkash890** [comment]
Hi, I think that the example is working fine even without making use of `<div>`. If  `<div>`  serves no purpose in this example then it can be removed from the stylesheet as well. Correct me if I am wrong?

This can be removed <be> : 
![Screenshot from 2021-03-28 21-03-13](https://user-images.githubusercontent.com/55234838/112757871-241e4100-9009-11eb-9941-226476f760e4.png)
