### ISSUE TITLE
Interactive explorer of Location anatomy clips last "l" of "protocol"

### ISSUE THREAD

**Issue by rjray** [mdn/content#34999]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Location

### What specific section or headline is this issue about?

Location anatomy

### What information was incorrect, unhelpful, or incomplete?

The black background on each segment's name does not fully cover the word "protocol". The last letter ("l") is outside the box.

This is only occurring on Firefox (Linux, from Mozilla deb package, version 128.0). When I brought up the page in Chrome (also on Linux) the display was correct.

![image](https://github.com/user-attachments/assets/79e387fe-da89-4411-9aab-6fcc49e48051)

### What did you expect to see?

The background color should cover the full word.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/location`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Location
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/location/index.md
* Last commit: https://github.com/mdn/content/commit/005cc1fd55aadcdcbd9aabbed7d648a275f8f23a
* Document last modified: 2024-01-15T21:58:53.000Z

</details>

**Comment by Josh-Cena** [comment]
Is it a window dimensions issue, or a font issue?

I doubt this issue can be helped if the container is just too narrow; overflowing text seems like reasonable behavior.

**Comment by rjray** [comment]
I doubt it's a dimensions issue. My window defaults to being 1280 in width. In addition, I stretched the window much wider and the issue remained.

**Comment by Josh-Cena** [comment]
This is likely a font issue. The "protocol" text is implemented as having the same width as the text it's describing (`https:`), so if `https:` gets narrower than it should, then the "protocol" text overflows. Maybe we can make the URL font even bigger?
