### ISSUE TITLE
Wrong return value of `queryPermission`

### ISSUE THREAD

**Issue by Juraj-Masiar** [mdn/content#34993]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle/queryPermission

### What specific section or headline is this issue about?

Return value

### What information was incorrect, unhelpful, or incomplete?

A [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that resolves to a [PermissionStatus](https://developer.mozilla.org/en-US/docs/Web/API/PermissionStatus) object.

### What did you expect to see?

A [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that resolves to a [PermissionStatus.state](https://developer.mozilla.org/en-US/docs/Web/API/PermissionStatus/state) string.

### Do you have any supporting links, references, or citations?

Specification says it returns a string:
https://wicg.github.io/file-system-access/#api-filesystemhandle-querypermission

Screenshot of the proof:
![image](https://github.com/user-attachments/assets/c2242fff-268e-41ea-87ae-59392fe463c9)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/filesystemhandle/querypermission`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle/queryPermission
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/filesystemhandle/querypermission/index.md
* Last commit: https://github.com/mdn/content/commit/be3c45cd7a4d5c04139eceae10f7368251cdca64
* Document last modified: 2024-05-13T06:15:07.000Z

</details>

**Comment by Juraj-Masiar** [comment]
Note that although the examples are correct, there are unnecessary parentheses around the await:
```
  if ((await fileHandle.queryPermission(opts)) === "granted") {
  // instead use:
  if (await fileHandle.queryPermission(opts) === "granted") {
```
To verify, see the docs for operator priority:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence

**Comment by Josh-Cena** [comment]
@Juraj-Masiar: our code is formatted by Prettier, which takes care of parentheses. It adds redundant brackets in this case so the code is more readable and obvious in what it's doing.

This page and `requestPermission` were changed in https://github.com/mdn/content/pull/29529. I believe @skyclouds2001 made a mistake because `PermissionStatus` and `PermissionState` are not the same thing and we don't document `PermissionState` because it's a simple enum. I would personally just revert that PR. Would you like to do it?

**Comment by Juraj-Masiar** [comment]
Thanks Josh for the info!
I don't feel comfortable enough to do the revert, so please, if you know how, do it :). 
But yeah, the original list of enum values sounds also OK.
Thank you!

**Comment by skyclouds2001** [comment]
Yes, this is a mistake and @Juraj-Masiar is correct. I will do the fix quickly.

**Comment by skyclouds2001** [comment]
> I would personally just revert that PR.

Well, revert here is also not a correct way to resolve this issue, as this method return a Promise, but it says a string.
