### ISSUE TITLE
Wrong redirection

### ISSUE THREAD

**Issue by duongdominhchau** [mdn/content#350]
Accessing https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Publishing_your_WebExtension on Firefox Dev 85b2 leads to <https://developer.mozilla.org/https:_extensionworkshop.com/documentation/publish/package-your-extension>.The correct destination is https://extensionworkshop.com/documentation/publish/package-your-extension/

**Comment by chrisdavidmills** [comment]
Interesting. If you look at the entry in our [redirects file](https://raw.githubusercontent.com/mdn/content/main/files/en-us/_redirects.txt), it looks to be correct:
```
/en-US/docs/Mozilla/Add-ons/WebExtensions/Publishing_your_WebExtension	https://extensionworkshop.com/documentation/publish/package-your-extension/
```

But the redirect is being handled incorrectly.

@peterbe , is this another one you can take a look at?

**Comment by peterbe** [comment]
I'm on it.

**Comment by peterbe** [comment]
First of all, the local development needs to be fixed. I can clearly see that it's in there in the `content/files/en-us/_redirects.txt` but still I get a 404 on the local server
```
▶ curl -I http://localhost:5000/en-US/docs/Mozilla/Add-ons/WebExtensions/Publishing_your_WebExtension
HTTP/1.1 404 Not Found
```

**Comment by peterbe** [comment]
[Here](https://s3.console.aws.amazon.com/s3/object/mdn-content-prod?region=us-west-2&prefix=main/en-us/docs/mozilla/add-ons/webextensions/publishing_your_webextension)'s the explanation why it's going wrong:
<img width="1182" alt="Screen Shot 2020-12-17 at 10 38 29 AM" src="https://user-images.githubusercontent.com/26739/102509023-0ded0600-4054-11eb-985f-2e77a470d821.png">

Now I need to figure out how that could have happened.

**Comment by peterbe** [comment]
I ran a complete `yarn build` and then ran `poetry run deployer upload ../client/build --no-progressbar`. And I added some print logging to what it would attempt to upload. It attempted:

```
REDIRECT 'main/en-us/docs/mozilla/add-ons/webextensions/prerequisities' ==> '/en-US/docs/Mozilla/Add-ons/WebExtensions/Prerequisites'
REDIRECT 'main/en-us/docs/mozilla/add-ons/webextensions/promoting_your_extension_or_theme' ==> '/https://extensionworkshop.com/documentation/publish/promoting-your-extension'
REDIRECT 'main/en-us/docs/mozilla/add-ons/webextensions/publishing_your_webextension' ==> '/https://extensionworkshop.com/documentation/publish/package-your-extension'
REDIRECT 'main/en-us/docs/mozilla/add-ons/webextensions/retiring_your_extension' ==> '/https://extensionworkshop.com/documentation/manage/retiring-your-extension'
REDIRECT 'main/en-us/docs/mozilla/add-ons/webextensions/sidebars' ==> '/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Sidebars'
```
So pretty clearly there's a but there somewhere.

**Comment by peterbe** [comment]
Fixed by https://github.com/mdn/yari/pull/2181
