### ISSUE TITLE
Element.querySelectorAll() examples: HTML & JS don't correspond

### ISSUE THREAD

**Issue by mr-bronson** [mdn/content#35003]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

In first example, in the HTML, the div elements set the `class` name.  But in the JS for that example, the query selector uses the `data-name` attribute.

Also, they all use `document.querySelectorAll` though they are purported to be examples of `Element.querySelectorAll`.

### What did you expect to see?

The second commented-out example in the JS is the one that corresponds to the HTML code.  If the name of the example is "dataset selector & attribute selectors", then the HTML should probably use some data-* attributes.  There should be at least one relevant example, i.e. corresponding to the HTML, that isn't commented out.  The other examples probably aren't helpful, but a link to an overview of [Attribute Selectors](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors) would be helpful.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/queryselectorall`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/queryselectorall/index.md
* Last commit: https://github.com/mdn/content/commit/dc7167c80c8b387bcd54636ac8692ec465603121
* Document last modified: 2024-05-28T12:29:13.000Z

</details>

**Comment by Josh-Cena** [comment]
This bug has existed since day 1 on GitHub. I think we should just change `data-name` to `class`. I agree we should remove the commented-out examples and provide a link to attribute selectors in the prose instead. Do you want to submit a PR?
