### ISSUE TITLE
Issue with "SubtleCrypto.exportKey()": (The title of the export example for JWK is incorrect)

### ISSUE THREAD

**Issue by cpawamgit** [mdn/content#3501]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/exportKey

#### What information was incorrect, unhelpful, or incomplete?
The title of the export example for JWK is incorrect :

it is "JSON Web Key import"

and should be "JSON Web Key export"

#### Specific section or headline?
JSON Web Key import

#### What did you expect to see?
JSON Web Key export

#### Did you test this? If so, how?
There is not much test to do, just check the webpage, it's a human error

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/subtlecrypto/exportkey`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/exportKey
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/subtlecrypto/exportkey/index.html
* Last commit: https://github.com/mdn/content/commit/48fca0c614add538e95f1075b2777fc396023d31
* Document last modified: 2021-03-16T07:50:01.000Z

</details>

**Comment by CreaTorAlexander** [comment]
Thanks for reporting it. I created PR https://github.com/mdn/content/pull/3523 to fix this issue.
