### ISSUE TITLE
Adding width to empty columns changes nothing

### ISSUE THREAD

**Issue by Evergard** [mdn/content#35014]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Basics#active_learning_colgroup_and_col

### What information was incorrect, unhelpful, or incomplete?

Adding a width to the columns doesn't really do anything?

### What did you expect to see?

Columns' width to change after giving a style of `width: 42px;`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/tables/advanced`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/tables/advanced/index.md
* Last commit: https://github.com/mdn/content/commit/8badc6cef8a77fbf1ba8054555097565d0a7dbc9
* Document last modified: 2024-04-02T07:13:49.000Z

</details>

**Comment by Josh-Cena** [comment]
This seems like a general programming question rather than a bug with our content. Please ask in a Q&A community such as StackOverflow instead.

**Comment by Evergard** [comment]
> This seems like a general programming question rather than a bug with our content. Please ask in a Q&A community such as StackOverflow instead.

hmm, ok i guess...

I checked MDN's own live preview and disabling the width in style doesn't change anything either. I just fail to see its purpose in the 'Active Learning' part

**Comment by Josh-Cena** [comment]
Did you send the issue with the right MDN URL? Maybe you are referring to another page , because this page has no "Active Learning" section.

**Comment by Josh-Cena** [comment]
Did you send the issue with the right MDN URL? This page doesn't mention "width" at all.

**Comment by Evergard** [comment]
oh my.

So sorry about that! I've updated the URL now. forgive me -.-

**Comment by Josh-Cena** [comment]
I think the issue is that `width: 42px;` is too narrow, since it has a minimum length of 70.3px. Maybe we should set it to something bigger, such as `100px`. Setting `width: 100px;` has an effect for you, right?

**Comment by Evergard** [comment]
Yes, indeed. Uhmm, can I do the PR myself? Hehe

**Comment by Josh-Cena** [comment]
Yeah, of course. This would also require a change to the learning-area repo to update the example code.

**Comment by Evergard** [comment]
sorry about this shoddy issue post ill do better next time

**Comment by Josh-Cena** [comment]
No worries! Thanks for the followups.
