### ISSUE TITLE
Not working link inside "HTMLSelectElement: checkValidity() method" page

### ISSUE THREAD

**Issue by arbutnar** [mdn/content#35022]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/checkValidity

### What information was incorrect, unhelpful, or incomplete?

![Screenshot 2024-07-24 134233](https://github.com/user-attachments/assets/0d8b5257-dcb8-46c7-b668-b04c87b5a6fe)

### What did you expect to see?

I expect to see a working link. The documentation about the invalid event has been written.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/checkValidity
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event

### Do you have anything more you want to share?

thank you for your precious documentation

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlselectelement/checkvalidity`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/checkValidity
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlselectelement/checkvalidity/index.md
* Last commit: https://github.com/mdn/content/commit/02fd6de308678aaea8e971e4fe38c52aa55c7b26
* Document last modified: 2024-03-26T10:17:44.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! The `invalid` event of `HTMLInputElement` and `HTMLSelectElement` are two distinct events, so they would get two pages. We are aware of all broken links in MDN, so there's no need to send issues for each one separately.
