### ISSUE TITLE
New <url> and src() pages

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#35029]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/url

### What specific section or headline is this issue about?

This page

### What information was incorrect, unhelpful, or incomplete?

This page conflates `<url>` with `url()`. Many pages that accept `<url>` wrongly link here.

### What did you expect to see?

`<url>` is not just `url()`; it also consists of `src()`, which is like `url()` except literal URLs must be quoted, allowing things like `src(var(--my-src))`.

### Do you have any supporting links, references, or citations?

https://drafts.csswg.org/css-values/#urls

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/url`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/url
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/url/index.md
* Last commit: https://github.com/mdn/content/commit/875d97804293021faaf66c16a76e2f31a6df56e1
* Document last modified: 2024-05-06T13:36:09.000Z

</details>

**Comment by OnkarRuikar** [comment]
No browser has implemented the `src()` function yet, so we should not create a page for it.
