### ISSUE TITLE
[import()] Mentions that you *need* to destructure to access the default export

### ISSUE THREAD

**Issue by pmoleri** [mdn/content#35034]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import

### What specific section or headline is this issue about?

[Importing Defaults](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#importing_defaults)

### What information was incorrect, unhelpful, or incomplete?

You need to destructure and rename the "default" key from the returned object.

### What did you expect to see?

You can get the default export by reading the "default" key from the returned object.

To destructure the object and read the default key it needs to be renamed because `default` is a reserved keyword.

### Do you have any supporting links, references, or citations?

In the same page:
> The module namespace object is a sealed object with null prototype. This means all string keys of the object correspond to the exports of the module [...], with the default export available as a key called default.

I also tested in Chrome and Firefox I can read it as `object.default` with no destructuring.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/import`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/import/index.md
* Last commit: https://github.com/mdn/content/commit/6e93ec8fc9e1f3bd83bf2f77e84e1a39637734f8
* Document last modified: 2024-07-13T00:55:27.000Z

</details>

**Comment by Josh-Cena** [comment]
You mean when you destructure, you need to rename?

Yeah, a one-sentence addition sounds fine to me.

**Comment by Josh-Cena** [comment]
Ah I see what you mean. Well, we could change it to:

> If you are destructuring the imported module namespace object, then you must rename the `default` key because `default` is a reserved word.

**Comment by pmoleri** [comment]
Yes. The first time that I read it I thought that it meant that destructuring was the only way to get the default.
That last rephrasing looks good to me.
