### ISSUE TITLE
missing description for pointer-events: bounding-box value

### ISSUE THREAD

**Issue by eyaler** [mdn/content#35164]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

### What information was incorrect, unhelpful, or incomplete?

missing description for bounding-box property

### What did you expect to see?

description for bounding-box property

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/pointer-events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/pointer-events/index.md
* Last commit: https://github.com/mdn/content/commit/7427496bfd56c7a469b08ad0a7fc7708da508254
* Document last modified: 2024-06-12T03:25:34.000Z

</details>

**Comment by Josh-Cena** [comment]
`bounding-box` seems at-risk: https://github.com/w3c/svgwg/issues/573

**Comment by OnkarRuikar** [comment]
The value is part of the [SVG/pointer-value](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointer-events#usage_notes) property. Raised [a BCD issue](https://github.com/mdn/browser-compat-data/issues/23994) to track the browser support.
