### ISSUE TITLE
Setting Up the MongoDB Database seems to have outdated screenshot in Step 4

### ISSUE THREAD

**Issue by RHieger** [mdn/content#35173]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

### What specific section or headline is this issue about?

Setting Up the MongoDB database

### What information was incorrect, unhelpful, or incomplete?

In Step 4 of the process, a screenshot of the **Security Quickstart** screen on the Mongo Atlas website does not match what is currently on their website.

Rather than having a section that begins with the question _"Where would you like to connect from?"_ there is a shorter dialogue box with a button at its bottom that says **Choose a connection method** as shown below:

<img width="798" alt="Screenshot 2024-07-26 at 19 23 27" src="https://github.com/user-attachments/assets/52904e57-fdde-4bdf-9ac2-747588467e1e">

Upon clicking that button, you see the following dialogue box:

<img width="798" alt="Screenshot 2024-07-26 at 19 25 45" src="https://github.com/user-attachments/assets/d9f442ff-e35a-4bf8-af1d-ad671e711001"> 

It is unclear which method would be the correct connection method for use in this tutorial.

This dialogue box is considerably different than the one depicted in the tutorial, as shown in the screenshot below:

<img width="726" alt="Screenshot 2024-07-26 at 19 30 16" src="https://github.com/user-attachments/assets/8223f9b4-c273-4762-b72a-5062eb9ce7f5">

### What did you expect to see?

I was expecting to see a dialogue box corresponding to what is currently at this point in the tutorial, not the dialogue box shown above.

### Do you have any supporting links, references, or citations?

Here is the precise link on the MongoDB Atlas website at which the unexpected dialogue box occurred:

https://cloud.mongodb.com/v2/66a428e0cd7f465e74f3bc1d#/overview?automateSecurity=true&connectCluster=library-cluster

### Do you have anything more you want to share?

None of the options offered in the new dialogue box seem to conform to what is in the tutorial, at least as far as I can tell. Hopefully this information can be updated before too long.

Thank you.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/3dd00b3b77e2e79c7d92f0b6c4f4665d54500a0e
* Document last modified: 2024-07-25T20:15:13.000Z

</details>

**Comment by Josh-Cena** [comment]
It was _just_ changed 10 months ago in https://github.com/mdn/content/pull/29389. It's really annoying if the UI keeps changing. Maybe we should find a way to not have this kind of step-by-step walkthrough, for example by pointing to their docs.

**Comment by RHieger** [comment]
This might be the most appropriate solution to the problem, given that the interface is such a moving target.

**Comment by hamishwillee** [comment]
@Josh-Cena @RHieger I couldn't agree more that it is a pain in the neck.

The question I ask myself though is whether removing this tutorial, or at least some of it, will result in fewer requests or more, and whether the cost of maintenance /verifying that the setup works will be increased or reduced.

I'm _fairly sure_ that the cost would be much higher if we linked to the docs. I base this on the few times I have tried setting this up from memory/following mongodb docs - it hasn't worked very well because there are a lot of options to get through. I always end up back at this tutorial so I know that the result is repeatable. 

I wish it were otherwise, but we should fix the screenshots. @RHieger would you like to work out how to do so from the Mongo Db docs and post an update? :-) . Me either. But I will get to it at some point soon.

**Comment by Josh-Cena** [comment]
> I'm fairly sure that the cost would be much higher if we relied on the mongodb docs. I base this on the few times I have tried setting this up from memory/following those docs - it hasn't worked very well because there are a lot of options to get through. I always end up back at this tutorial so I know that the result is repeatable.

It would be a big pity for them if our docs are better at introduction than their own docs!

**Comment by hamishwillee** [comment]
> It would be a big pity for them if our docs are better at introduction than their own docs!

Our docs are a much better introduction _for our very specific and narrow use case_ :-).  You might of course work out how to work with this tutorial from their docs - its just going to be harder because they have to cover many possible configurations.

**Comment by hamishwillee** [comment]
Fixed by #35206
