### ISSUE TITLE
Issue with "mask-position": Example is not working because of CORS block.

### ISSUE THREAD

**Issue by CarrotB** [mdn/content#3518]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/mask-position

#### What information was incorrect, unhelpful, or incomplete?
The example under Examples section uses a svg image for mask-image ( the url: https://mdn.mozillademos.org/files/12676/star.svg), which didn't set CORS header correctly and being blocked by browser.

#### Specific section or headline?
Examples

#### What did you expect to see?
A star-masked gradient.

#### Did you test this? If so, how?
Nope, but the console message says it load and clear.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/mask-position`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/mask-position
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/mask-position/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by CarrotB** [comment]
After checking on some other CSS properties under mask, there're more pages using this svg, for example, mask-size, mask-origin, mask-composite.
Don't know if there're more pages using files under that domain, but guess it's kinda easy to fix if CORS headers can be added.

**Comment by rachelandrew** [comment]
@CarrotB I'm moving these to the examples repo when I spot them, so I'll move this one too. Thanks for the report!
