### ISSUE TITLE
animation-timing-function neglects to mention linear() easing function

### ISSUE THREAD

**Issue by mr-bronson** [mdn/content#35187]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function

### What information was incorrect, unhelpful, or incomplete?

Only the linear keyword is mentioned, not the linear() function described [here](https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function#linear-easing-function).  It does show up in the [Formal syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function#formal_syntax), but it does not appear in the [Syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function#syntax), [Values](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function#values) or [Examples](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function#examples) sections.

### What did you expect to see?

It should be described, just as the other functions are.

### Do you have anything more you want to share?

There are some other issues that affect this page and the [\<easing-function>](https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function#linear-easing-function) page.

1. The Formal syntax, although it does seem to match the [specification](https://drafts.csswg.org/css-easing/#funcdef-linear) is deceiving.  Although it says `<linear-stop-list> = [ <linear-stop> ]#` it is functionally `<linear-stop-list> = [ <linear-stop> ]#{2,}` because the specification says:
> If there are less than two items in _stopList_, then return _failure_.

The [Try it](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function#try_it) demo at the top either understands this limitation or reacts to an error by showing a yellow X when only one point is given.  If only one is given, the declaration fails and reverts to a valid declaration, if given, or the default `ease`.  So the descriptions on these pages should make it clear that there must be at least two points.

2. The specification which the [animation-timing-function](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function) page links to knows nothing of the linear() function.  It simply says "The syntax for the [linear easing function](https://www.w3.org/TR/css-easing-1/#linear-easing-function) is simply the **linear** keyword."  If the linear() function is going to be listed in the Formal syntax and hopefully soon in the sections above that, then it seems like the specification linked to should reflect that.

3. On the [\<easing-function>](https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function) page, it says:
> Each point or \<linear-stop> in the list is specified as a [\<number>](https://developer.mozilla.org/en-US/docs/Web/CSS/number) between 0 and 1.
> ... The value should be between 0 and 1...

But then it gives as the very first thing in the Syntax section the example: `linear(1, -0.5, 0)`.  This does seem to work, as do all sorts of positive and negative values outside the range of 0 to 1.  As the [spec](https://drafts.csswg.org/css-easing/#easing-functions) says:
> The output progress value is a real number in the range [-∞, ∞].

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/animation-timing-function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/animation-timing-function/index.md
* Last commit: https://github.com/mdn/content/commit/4e508e2f543c0d77c9c04f406ebc8e9db7e965be
* Document last modified: 2024-07-26T14:38:02.000Z

</details>

**Comment by OnkarRuikar** [comment]
1. Created [a PR](https://github.com/w3c/csswg-drafts/pull/10643) in spec to fix the syntax.
2. Created [a PR](https://github.com/mdn/browser-compat-data/pull/23992) in BCD to add the level 2 spec to the list.
3. Rest is being fixed in https://github.com/mdn/content/pull/35240
