### ISSUE TITLE
Browsers do not ignore initializers in for-in loops

### ISSUE THREAD

**Issue by SheepTester** [mdn/content#35208]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features

### What specific section or headline is this issue about?

Statements, "Initializers in `var` declarations"

### What information was incorrect, unhelpful, or incomplete?

The article claims,

> Initializers in `var` declarations of [`for...in`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) loops headers are deprecated and produce [syntax errors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_for-in_initializer) in strict mode. They are silently ignored in non-strict mode.

However, in at least Firefox and Chrome, the initializer is not ignored:

```js
for (var isEmpty = true in {}) isEmpty = false
isEmpty // true

for (var isEmpty = true in window) isEmpty = false
isEmpty // false
```

### What did you expect to see?

I think the sentence could be reworded to avoid implying that the initializer expression doesn't run. I think the "They are silently ignored in non-strict mode." can just be removed

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/deprecated_and_obsolete_features`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/deprecated_and_obsolete_features/index.md
* Last commit: https://github.com/mdn/content/commit/1b2c87c20466d2a3eec9b3551c269f9aff8f5762
* Document last modified: 2024-07-25T21:53:55.000Z

</details>

**Comment by Josh-Cena** [comment]
We should definitely change it to something more rigorous and reality-matching. Since only `var` initializers are allowed, I think something like this is better: the initializer expression is evaluated and assigned to the variable, but the value would be immediately reassigned on the first iteration of the loop.
