### ISSUE TITLE
Wrong case???

### ISSUE THREAD

**Issue by arz1gwa** [mdn/content#35207]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website

### What specific section or headline is this issue about?

Don't forget to backup to GitHub

### What information was incorrect, unhelpful, or incomplete?

In Django Part 2, heading 'Don't forget to backup' in the line
git checkout -b skeleton_website # Create and activate a new branch "skeleton_website"
I kept getting this error _'fatal: Cannot update paths and switch to branch 'skeleton_website' at the same time._' until I changed the -b to -B. Does that only happen in Windows?
Windows 11 Pro 23h2, Django 4.2.12, Git 2.45.2.windows.1

### What did you expect to see?

Switched to a new branch 'skeleton_website'

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/django/skeleton_website`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/skeleton_website/index.md
* Last commit: https://github.com/mdn/content/commit/cde9330e9bbaddea72febf44dcc3a7db16fe1a11
* Document last modified: 2024-07-26T02:12:21.000Z

</details>

**Comment by hamishwillee** [comment]
`git checkout -b <branchname>` is correct on all platforms - I work on both Windows and Linux. I can't explain your problem but the tutorial is correct.

**Comment by Josh-Cena** [comment]
I also don't know why. Which shell are you using? Git bash, WSL, or something else?

**Comment by Josh-Cena** [comment]
I would assume the content is correct and works for everyone else, unless more information can be provided.
