### ISSUE TITLE
Historical 'New in JavaScript 1.1-1.8.5' docs should be restored

### ISSUE THREAD

**Issue by eligrey** [mdn/content#35233]
### MDN URLs

- https://developer.mozilla.org/en/New_in_JavaScript_1.1
- https://developer.mozilla.org/en/New_in_JavaScript_1.2
- https://developer.mozilla.org/en/New_in_JavaScript_1.3
- https://developer.mozilla.org/en/New_in_JavaScript_1.4
- https://developer.mozilla.org/en/New_in_JavaScript_1.5
- https://developer.mozilla.org/en/New_in_JavaScript_1.6
- https://developer.mozilla.org/en/New_in_JavaScript_1.7
- https://developer.mozilla.org/en/New_in_JavaScript_1.8
- https://developer.mozilla.org/en/New_in_JavaScript_1.8.1
- https://developer.mozilla.org/en/New_in_JavaScript_1.8.5

### What information was incorrect, unhelpful, or incomplete?

It appears that the previous official Mozilla docs for 'New in JavaScript 1.1-1.8.5' are no longer available on MDN. Those docs should still be kept available for historical reference purposes. Other sites link to these pages[1], including many Firefox release notes[2], and people shouldn't have to update these links to mirrors with unknown reliability.

I understand that these release notes ending coincided with the trademark rights for JavaScript being transferred from Sun to Oracle, but you should still have had a license for this documentation at the time from Sun. If you didn't, Oracle may already be able to sue anyways (IANAL & TINLA), so restoring these docs shouldn't make a difference.

1. [https://github.com/eligrey/async.js](https://github.com/eligrey/async.js#:~:text=making%20applications%20in-,JavaScript%201.7,-or%20higher.%20It)
2. https://github.com/search?q=repo%3Amdn%2Fcontent%20%22New%20in%20JavaScript%22&type=code

### What did you expect to see?

Assuming that Mozilla had the appropriate trademark license at the time of publication, these docs should be restored.

### Do you have any supporting links, references, or citations?

MDN was previously used for official publication of 'New in JavaScript' release notes by Mozilla.

**Comment by hamishwillee** [comment]
MDN is not an museum  - the target audience is current developers who want to use the web platform. So I expect these were removed as irrelevant, and just more fluff for our intended audience.

**Comment by eligrey** [comment]
It was being used as the official authoritative source at the time, and these pages are directly linked to in at least 4 Firefox releases according.

What is the cut-off for legacy/'museum content'?

**Comment by hamishwillee** [comment]
I have no idea what the cutoff is. The links from firefox release notes should be cleaned up too - probably just deleted.

@Josh-Cena Do we have a formal policy on cleanup of these old notes?

**Comment by Josh-Cena** [comment]
I have no idea of Firefox release note policies, and myself, being a history fan, would not particularly care about reading release notes for history. So it would be up to the Mozilla team to decide.

**Comment by hamishwillee** [comment]
@Josh-Cena The relevant discussion here is removal of the javascript notes - the FF notes was more of an aside

https://developer.mozilla.org/en/New_in_JavaScript_1.1
https://developer.mozilla.org/en/New_in_JavaScript_1.2
https://developer.mozilla.org/en/New_in_JavaScript_1.3
https://developer.mozilla.org/en/New_in_JavaScript_1.4
https://developer.mozilla.org/en/New_in_JavaScript_1.5
https://developer.mozilla.org/en/New_in_JavaScript_1.6
https://developer.mozilla.org/en/New_in_JavaScript_1.7
https://developer.mozilla.org/en/New_in_JavaScript_1.8
https://developer.mozilla.org/en/New_in_JavaScript_1.8.1
https://developer.mozilla.org/en/New_in_JavaScript_1.8.5

**Comment by Josh-Cena** [comment]
Aren't these things also pertaining to Firefox's releases? I'm not very knowledgeable about ancient JavaScript but my understanding was that these version numbers were invented and used by Netscape.

**Comment by eligrey** [comment]
Those were used as late as 2009 by Mozilla iirc.

**Comment by hamishwillee** [comment]
2009 predates this github repo by many years. It is quite likely that the old data didn't even make it across from the wiki infrastructure. 
I don't think anyone is going to have any particular sadness about an odd missing doc reported against Firefox 4.

I'm closing this. However if you can find a copy of the original docs somewhere and what to post them yourself then perhaps we could find a place to put them - hard to know without seeing them and not worth the time to do more than the casual search I just tried on github and the wayback machine.
