### ISSUE TITLE
Add fixed

### ISSUE THREAD

**Issue by seregadushka** [mdn/content#35232]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/position

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

"fixed"  in Example

### What did you expect to see?

all 5 properties 

### Do you have any supporting links, references, or citations?

simple expample

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/position`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/position
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/position/index.md
* Last commit: https://github.com/mdn/content/commit/fc1cc5684c98d19816d5cc81702d70f2a0debbad
* Document last modified: 2024-07-26T14:35:43.000Z

</details>

**Comment by hamishwillee** [comment]
There is an example of using fixed positioning https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed_positioning

If that doesn't do what you want, can you explain the problem in more detail?

**Comment by seregadushka** [comment]
In DEMO ! Position has 5 properties  only. We have 4 in Demo. Where is position fixed in Demo ?

**Comment by queengooborg** [comment]
The interactive examples at the top of the page are not meant to be an extensive list of all the possible values of a CSS property, just a few examples to demonstrate the property in general.  Additionally, it was decided that the `fixed` value was not needed in the interactive example; see https://github.com/mdn/interactive-examples/issues/1900.

**Comment by seregadushka** [comment]
`Additionally, it was decided that the fixed value was not needed in the interactive example; `
I wonder who made this one-man decision that prevents the entire global community from learning CSS.

**Comment by queengooborg** [comment]
Sorry if a decision from lots of discussion across lots of time with lots of folks is not what you were hoping, but I fail to see how it "prevents [...] learning CSS" when the information is available on the webpage, and you just have to...you know...scroll down.

Please be respectful when writing comments, as per the Mozilla Community Participation Guidelines.

**Comment by seregadushka** [comment]
Illustrative examples are important. Especially when only 20% is enough to complete the presentation. As a member of the Mozilla community, I would prefer to see scrolling and all 10-15 options for any properties there.  And scrolling is not an excuse. More like stupidity. 
```
scrollbar-width: none;
	overflow: auto; 
```
The phrase "a large number of people " means one thing . There are no such people, as there was no discussion itself. It's obvious. 
I have often come across the opinion " is not necessary to go to Mozilla at all. All the knowledge is not there. " This is your merit. 
But you have a very stylish screen with max-width: 1000px. When people already have 4K monitors . There is no place to post examples here. They are not needed. The design of a blank page is much more important.

**Comment by queengooborg** [comment]
I'm locking this thread because you are continuing to be disrespectful.  Please note that continued violation of the community guidelines may result in removal from participation in MDN projects.
