### ISSUE TITLE
Wrong header name in the preflight protocol diagram

### ISSUE THREAD

**Issue by mkorvas** [mdn/content#35253]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

### What specific section or headline is this issue about?

Preflighted requests

### What information was incorrect, unhelpful, or incomplete?

The SVG diagram suggests the first response from the server should contain the "Access-Control-Request-Headers" header, however implementig the server like that still results in my browser erring with "CORS Missing Allow Header".

### What did you expect to see?

I believe the header sent in this server response should be "Access-Control-**Allow**-Headers" instead, as also the text below the SVG diagram suggests.

### Do you have anything more you want to share?

I tried to update the SVG file on Github myself but I didn't find it (using the file search input field). I guess it's maintained elsewhere.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/cors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/index.md
* Last commit: https://github.com/mdn/content/commit/ef46a4ac6bfec3e33c9209244e7cb1a9206165d6
* Document last modified: 2024-07-25T21:29:40.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! I think you are right.

> I tried to update the SVG file on Github myself but I didn't find it (using the file search input field). I guess it's maintained elsewhere.

It's at https://github.com/mdn/shared-assets/tree/main/images/diagrams/http/cors .

**Comment by bsmth** [comment]
Thank you, both! It's fixed in the linked PR and the rest of the prose/code snippets on the page looks like it's aligned.
