### ISSUE TITLE
Issue with "Functions": Inaccurate expression

### ISSUE THREAD

**Issue by akasuv** [mdn/content#3525]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions#name_conflicts

#### What information was incorrect, unhelpful, or incomplete?

In the last paragraph of *Name conflicts* section,  it says

> The name conflict happens at the statement `return x` and ...

<img width="241" alt="CleanShot 2021-03-26 at 17 49 29@2x" src="https://user-images.githubusercontent.com/30253166/112613945-a49f3f00-8e5b-11eb-8127-a216b865ab6c.png">

but the return statement in the above code example is actually `return x * 2` not `return x`;

#### Specific section or headline?

Name conflicts

#### What did you expect to see?

It should be *"The name conflict happens at the statement `return x * 2`"*

#### Did you test this? If so, how?

I don't think this needs a test.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/functions/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/commit/f4881c46930ea78e17e8e0ba2aa574523ac560c0
