### ISSUE TITLE
Formal Syntax Font Shorthand uses font-width instead of font-stretch

### ISSUE THREAD

**Issue by jorenbroekema** [mdn/content#35265]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font

### What specific section or headline is this issue about?

Formal Syntax

### What information was incorrect, unhelpful, or incomplete?

The font-width definitions are wrong, it's supposed to be font-stretch.

Incorrect:

font = 
  [\[](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#brackets) [\[](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#brackets) [<'font-style'>](https://developer.mozilla.org/en-US/docs/Web/CSS/font-style) [||](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#double_bar) \<font-variant-css2\> [||](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#double_bar) [<'font-weight'>](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) [||](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#double_bar) \<font-width-css3\> [\]](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#brackets)[?](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#question_mark) [<'font-size'>](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size) [\[](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#brackets) / [<'line-height'>](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height) [\]](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#brackets)[?](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#question_mark) [<'font-family'>](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) [\]](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#brackets)  [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  \<system-family-name\>

Correct:
font = 
  [\[](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#brackets) [\[](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#brackets) [<'font-style'>](https://developer.mozilla.org/en-US/docs/Web/CSS/font-style) [||](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#double_bar) [<'font-variant-css2'>](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant) [||](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#double_bar) [<'font-weight'>](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) [||](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#double_bar) [<'font-stretch-css3>'](https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch) [\]](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#brackets)[?](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#question_mark) [<'font-size'>](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size) [\[](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#brackets) / [<'line-height'>](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height) [\]](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#brackets)[?](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#question_mark) [<'font-family'>](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) [\]](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#brackets)  [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  \<system-family-name\>

---

A bit lower into the formal syntax, incorrect:

\<font-width-css3> = 
  normal           [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  ultra-condensed  [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  extra-condensed  [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  condensed        [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  semi-condensed   [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  semi-expanded    [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  expanded         [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  extra-expanded   [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  ultra-expanded

Correct:

\<font-stretch-css3> = 
  normal           [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  ultra-condensed  [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  extra-condensed  [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  condensed        [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  semi-condensed   [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  semi-expanded    [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  expanded         [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  extra-expanded   [|](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#single_bar)
  ultra-expanded

### What did you expect to see?

See above

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#font-prop

### Do you have anything more you want to share?

I wanted to contribute but the [Contributing guidelines](https://github.com/mdn/content/blob/main/CONTRIBUTING.md) don't explain where I can find the definitions that are included in the markdown files with `{{foo}}`, in this case it's https://github.com/mdn/content/blob/main/files/en-us/web/css/font/index.md?plain=1#L112C3-L112C12 (CSSSyntax) definition that seems to be incorrect.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font/index.md
* Last commit: https://github.com/mdn/content/commit/3fd4e2ff8c4da3b4ff7be34eeda4dd0cbbfc1a15
* Document last modified: 2023-08-16T01:37:31.000Z

</details>

**Comment by OnkarRuikar** [comment]
It is correct as per [the latest specs](https://drafts.csswg.org/css-fonts/#font-prop). The `font-stretch` got renamed to `font-width`:
- https://drafts.csswg.org/css-fonts/#font-stretch-desc
- https://github.com/w3c/csswg-drafts/issues/551#issuecomment-1885196273

The `font-stretch` is now a legacy alias for the new name `font-width`.

**Comment by jorenbroekema** [comment]
Ah interesting, but then the other references on the MDN page that still call it font stretch need to be fixed I guess?

**Comment by Josh-Cena** [comment]
Yep, please see https://github.com/mdn/content/issues/34347
