### ISSUE TITLE
[HTTP] CSP: Implement report-to

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#35279]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Features to document

Docs worth a check, but looks like a bcd/release note task

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1391243

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
Trying to work out how it all works - https://bugzilla.mozilla.org/show_bug.cgi?id=1391243#c11

Note, behind a pref - not in release.

Status: 

- [ ] BCD
- [ ] Docs
- [ ] Dev-docs-complete
- [ ] Experimental Features/Release note

**Comment by armenzg** [comment]
Is there a Bugzilla ticket tracking removing the requirement of a preference to be set?

**Comment by hamishwillee** [comment]
> Is there a Bugzilla ticket tracking removing the requirement of a preference to be set?

No idea sorry. I've moved on from this task, which is for MDN tracking anyway. Perhaps ask in Bugzilla?
