### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by iamvldmrbrvkv** [mdn/content#35270]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#evaluation_order

### What information was incorrect, unhelpful, or incomplete?

The initializer is evaluated during instance creation, at the start of the constructor (for base classes) or immediately **before** the super() call returns (for derived classes).

### What did you expect to see?

The initializer is evaluated during instance creation, at the start of the constructor (for base classes) or immediately **after** the super() call returns (for derived classes).

### Do you have anything more you want to share?

Only when parent class is fully initialized and returns, child class initializers starts evaluated and added fields to 'this'.
```js
// The order of evaluation and initialization of fields in parent and child classes
// Definition of ParentClassEvaluation
class ParentClassEvaluation {
  // Step 1: The expression for the initializer of parentField is saved here.
  parentField = "parentIinitializer";
  
  // Step 2: Definition of the parent class constructor
  constructor(firstName) {
    // This is called during the creation of an instance.
    // Evaluation of initializer: This is the moment when, during instance creation, the initializer expression is actually executed and the value is assigned to the field. Thus, at this stage, the initializer expression "parentIinitializer" is assigned to the parentField.
    // this.parentField and this.firstName are available here.
    this.firstName = firstName;
    this.parentField = "newParentField"; // Here parentField is reassigned.
  }
}

// Definition of ChildClassEvaluation (subclass of ParentClassEvaluation)
class ChildClassEvaluation extends ParentClassEvaluation {
  // Step 3: The expression for the initializer of childField is saved here.
  childField = "childdInitializer";
  
  // Step 4: Definition of the child class constructor
  constructor(firstName, secondName) {
    // Step 5: super() is called to initialize the parent class
    super(firstName);
    
    // this.parentField and this.firstName are already initialized and available.
    // After returning from super(), the fields of the current class are initialized.
    // Evaluation of initializer: This is the moment when, during instance creation, the initializer expression is actually executed and the value is assigned to the field. Thus, at this stage, the initializer expression "childdInitializer" is assigned to the childField.
    // this.childField is available here.
    this.secondName = secondName; // secondName is initialized.
    this.childField = "newChildField"; // childField is reassigned here.
  }
}

// Step 6: Creating an instance of ChildClassEvaluation
const instanceFromChildClassEvaluation = new ChildClassEvaluation('Vladimir', 'Borovikov');

// Step 7: Output the instance to see the field values
console.log(
  "instanceFromChildClassEvaluation",
  instanceFromChildClassEvaluation
);
```

/* Step-by-step evaluation:
1. The expression for the initializer of parentField is saved here.
Note: This occurs before the execution of the ParentClassEvaluation constructor.

2. Execution of the parent class constructor:

The ParentClassEvaluation constructor is called with the parameter firstName.
The initializer expression "parentIinitializer" is assigned to the parentField.
this.firstName is assigned the value of the firstName parameter ("Vladimir").
this.parentField is reassigned with the value "newParentField".

3. The expression for the initializer of childField is saved here.
Note: This occurs before the execution of the ChildClassEvaluation constructor.

4. Execution of the child class constructor:

The ChildClassEvaluation constructor is called with the parameters firstName and secondName.
super(firstName) is called, which executes the ParentClassEvaluation constructor as described in Step 2.
After returning from super(firstName), the initializer expression "childdInitializer" is assigned to the childField, this.secondName is assigned the value of the secondName parameter ("Borovikov").
this.childField is reassigned with the value "newChildField".

Final structure of the object:

instanceFromChildClassEvaluation will have the following fields:
parentField: 'newParentField',
firstName: 'Vladimir',
childField: 'newChildField',
secondName: 'Borovikov'

When we output the instance to the console, the result will be:

instanceFromChildClassEvaluation {
  parentField: 'newParentField',
  firstName: 'Vladimir',
  childField: 'newChildField',
  secondName: 'Borovikov'
}

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/classes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/classes/index.md
* Last commit: https://github.com/mdn/content/commit/1b2c87c20466d2a3eec9b3551c269f9aff8f5762
* Document last modified: 2024-07-25T21:53:55.000Z

</details>

**Comment by Josh-Cena** [comment]
A function can't do anything "after" it returns because control has already shifted to another part of the program. Similarly `super()` can't do anything after it has returned because now it's already the constructor itself that's evaluating. Therefore all logic of `super()` must be executed **before** `super()` returns. "Immediately before `super()` returns" is otherwise identical to "Immediately after `super()` returns", because no code can execute in between these two time points—does that make sense?

**Comment by iamvldmrbrvkv** [comment]
It means that child class constructor function create blank object - which is 'this', then we call parent constructor via super(), with 'this' context, like ParentClassConstructor.call(this, ...arguments), ParentClassConstructor just initialized fields in 'this', there no return keyword, only AFTER this step - after ParentClassConstructor fully executed, then the child pre saved initializer expression is actually executed and the value is assigned to the field in 'this'. In this case maybe replace 'or immediately before the super() call returns (for derived classes)' with 'or immediately after the super() fully executed (for derived classes'?

It's the same:
```js
function ParentConsructorEvaluation(firstname) {
  this.parentField = "parentIinitializer"
  this.first = firstname
}

function ChildConsructorEvaluation(firstname, secondName) {
  ParentConsructorEvaluation.call(this, firstname) // only after parent constructor finished execution, child field are initialized
  this.childField = "childdInitializer";
  this.second = secondName
}

const instanceFromChildConstructorEvaluation = new ChildConsructorEvaluation('Vladimir', 'Borovikov');

console.log('instanceFromChildConstructorEvaluation', instanceFromChildConstructorEvaluation)

class ParentClassEvaluation {
  parentField = "parentIinitializer";
  constructor(firstName) {
    this.firstName = firstName;
    this.parentField = "newParentField";
  }
}

class ChildClassEvaluation extends ParentClassEvaluation {
  childField = "childdInitializer";
  constructor(firstName, secondName) {
    super(firstName);
    this.secondName = secondName;
    this.childField = "newChildField";
  }
}

const instanceFromChildClassEvaluation = new ChildClassEvaluation('Vladimir', 'Borovikov');

console.log(
  "instanceFromChildClassEvaluation",
  instanceFromChildClassEvaluation
);
```

**Comment by Josh-Cena** [comment]
This steps describes what happens _within_ `super()`—think about `super` as a function. It must do something when you call it. The last step it does, before it returns to the current constructor, is to initialize the fields.

**Comment by Josh-Cena** [comment]
It is immaterial to show me any code, because what you are proposing to change is not provable through code. "Immediately before returning" and "immediately after returning" are two adjacent points in time and there's nothing observable that can happen in between. Please read the [spec](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-super-keyword-runtime-semantics-evaluation):

> [SuperCall](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-SuperCall) : super [Arguments](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-Arguments)
> 1. Let newTarget be [GetNewTarget](https://tc39.es/ecma262/multipage/executable-code-and-execution-contexts.html#sec-getnewtarget)().
> 2. [Assert](https://tc39.es/ecma262/multipage/notational-conventions.html#assert): newTarget [is an Object](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-object-type).
> 3. Let func be [GetSuperConstructor](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-getsuperconstructor)().
> 4. Let argList be ? [ArgumentListEvaluation](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-runtime-semantics-argumentlistevaluation) of [Arguments](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-Arguments).
> 5. If [IsConstructor](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-isconstructor)(func) is false, throw a TypeError exception.
> 6. Let result be ? [Construct](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-construct)(func, argList, newTarget).
> 7. Let thisER be [GetThisEnvironment](https://tc39.es/ecma262/multipage/executable-code-and-execution-contexts.html#sec-getthisenvironment)().
> 8. Perform ? thisER.BindThisValue(result).
> 9. Let F be thisER.[[FunctionObject]].
> 10. [Assert](https://tc39.es/ecma262/multipage/notational-conventions.html#assert): F is an ECMAScript [function object](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#function-object).
> 11. Perform ? [InitializeInstanceElements](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-initializeinstanceelements)(result, F).
> 12. Return result.

This is what happens when you call `super()`. The last step, right before it returns, is to initialize instance elements.

**Comment by iamvldmrbrvkv** [comment]
That means when parent  super() constructor executed and just before 12. Return result  in 11 step initialize own fields and child fields, then return result in  12. Return result, and back to the current child constructor? To difficult, chat GPT can't explain, thank you so much!
