### ISSUE TITLE
The word "bad scheme" is not clear when talking the promise rejected situation

### ISSUE THREAD

**Issue by qiulang** [mdn/content#35276]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

### What specific section or headline is this issue about?

The section "Checking response status"

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_response_status says

> The promise returned by fetch() will reject on some errors, such as a network error or a bad scheme.

What is the **bad scheme** here ?  Can the document give some examples ?

### What did you expect to see?

I would like to know what bad scheme is as I would like to when fetch will reject promise.

So far I can see network error and abort will reject the promise. I think fetch will also reject incorrect header setting, but what others ? 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/fetch_api/using_fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fetch_api/using_fetch/index.md
* Last commit: https://github.com/mdn/content/commit/58ad1df59f2ffb9ecab4e27fe1bdf1eb5a55f89b
* Document last modified: 2024-07-24T01:12:06.000Z

</details>

**Comment by Josh-Cena** [comment]
The guide is not the place to look for exhaustive information. We didn't elaborate on this because it's not the point of this tutorial or even this section. If you want to find all error conditions, read the reference instead: https://developer.mozilla.org/en-US/docs/Web/API/Window/fetch#exceptions
