### ISSUE TITLE
[JS] Implement Regular Expression Pattern Modifiers proposal

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#35285]
## Acceptance criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes for enabled/preview features
- [ ] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1899813

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by Josh-Cena** [comment]
Linking https://github.com/mdn/content/pull/34863; I made a typo because `const pattern = /(?:var|let|const) (?i:foo|bar)\b/i;` should be `const pattern = /(?:var|let|const) (?i:foo|bar)\b/;`, but I was too lazy to follow up for a fix, so that could be part of this work.

**Comment by dletorey** [comment]
This is currently not working in Firefox Beta 130 but is working in Firefox Nightly 131.0a1 (2024-08-28) 

So possibly rolling over to 131 release.

**Comment by dletorey** [comment]
## Associated PRs

- [Firefox Release PR](https://github.com/mdn/content/pull/35622)
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/24241)

**Comment by Josh-Cena** [comment]
https://github.com/mdn/content/issues/36117

**Comment by Josh-Cena** [comment]
https://github.com/mdn/content/issues/36117
