### ISSUE TITLE
CSS :defined pseudo-class: Improve example and fix typo

### ISSUE THREAD

**Issue by mr-bronson** [mdn/content#35296]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:defined

### What information was incorrect, unhelpful, or incomplete?

First, a typo in the first paragraph:
> ... built in to the browser ...

Should be:
> ... built into the browser ...

[source](https://dictionary.cambridge.org/dictionary/english/build-into)

Second, the example given is bad on multiple levels.
1. If the point of the example is to show what difference it makes, then it seems like you'd want to allow some time for the user to look at it while it's `:not(:defined)`.  As is, the element is only `display: none` for the split second it takes to load the page.
2. The example makes the styling completely irrelevant.  In the HTML, before the upgrade, it's an empty element with no margin, borders, etc., and so occupies no space, making it invisible.  So the `display: none` isn't making any visible change.
3. The constructor does something which is against the "conformance requirements" given in [the spec](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance).  It sort of works, thanks to the `defer` attribute of the script tag (which is not mentioned at all on this page; you have to look at the github hosted files, as this page makes it appear that the JS comes first and then the HTML).  This delayed execution makes the `<simple-custom>` element be upgraded after its creation.  But that doesn't negate the fact that the constructor is contrary to the requirements.

> The element's attributes and children must not be inspected, as in the non-[upgrade](https://html.spec.whatwg.org/multipage/custom-elements.html#upgrades) case none will be present, and relying on upgrades makes the element less usable.

And as [MDN explains](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#implementing_a_custom_element) when linking to this spec:
> At this point, you should not inspect the element's attributes...

It's quite normal for examples to be frivolous or silly, but we should not be confusing learners by giving them examples that are so blatantly against the spec.

4. The example is over-complicated.  There's no need to trot out a shadow root or add a `div` with text based on some attribute that we weren't supposed to read in the constructor.  You don't need the constructor to do anything, as the point of the example is merely about whether the tag has been defined.  Readers can learn elsewhere about how to make author-defined elements useful.

### What did you expect to see?

Here's a suggestion of how to improve the example.  It could be even simpler, but I think this largely fixes the deficiencies I noted above.
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>:defined demo</title>
    <script>
function defineSimpleCustom() {
  customElements.define("simple-custom",
    class extends HTMLElement {
      constructor() {
        super();
      }
    }
  );
  document.getElementById("button1").remove();
}
    </script>
    <style>
      p {
        background: yellow;
      }

      :defined {
        font-style: italic;
      }

      simple-custom {
        text-transform: uppercase;
        background: cyan;
      }

      simple-custom:not(:defined) {
        display: none;
      }
    </style>
  </head>
  <body>
    <h1><code>:defined</code> demo</h1>

    <p>The <code>&lt;simple-custom&gt;</code> element type is <simple-custom>NOT</simple-custom> undefined.</p>

    <button id="button1" onclick="defineSimpleCustom()">Define <code>&lt;simple-custom&gt;</code></button>    

  </body>
</html>
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_defined`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:defined
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_defined/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by liuyangcharlie** [comment]
Happened to come across the `:defined` pseudo-class doc and had some similar thoughts.

The updated example that @mr-bronson shared surely makes the example better-illustrated to some extent.

Probably we can add more straightforward instructions to `button1` to make users more aware of what they should do to see the changes:

```
<p>Click the button below to make <code>&lt;simple-custom&gt;</code> a custom element.</p>
<button id="button1" onclick="defineSimpleCustom()">Define <code>&lt;simple-custom&gt;</code></button>
```
