### ISSUE TITLE
Manifest version 2 or lower supports "scripts" according to the extension implementation

### ISSUE THREAD

**Issue by joshi008** [mdn/content#35308]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background

### What specific section or headline is this issue about?

background

### What information was incorrect, unhelpful, or incomplete?

Manifest version 2 or lower supports "scripts" according to the extension implementation

### What did you expect to see?

2 or lower

### Do you have any supporting links, references, or citations?

https://developer.chrome.com/docs/extensions/reference/manifest/background

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/background`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/manifest.json/background/index.md
* Last commit: https://github.com/mdn/content/commit/51ddae7fc3de3712eef57434f8fc85c1e10bc67b
* Document last modified: 2023-11-24T19:24:58.000Z

</details>

**Comment by joshi008** [comment]
Error I got while using manifest version 3 and scripts:
`'background.scripts' requires manifest version of 2 or lower.`

**Comment by PassionPenguin** [comment]
yes `background.scripts` requires manifest v2 or lower in Chromium, but what we said in the table at the very beginning denotes `background` itself - `background.service_worker` can be used in manifest v3.

(manifest v1 has been deprecated long time ago. you cant even load them in any modern browser?)

**Comment by rebloor** [comment]
We don't document anything as supporting manifest V1 for the reason noted by @PassionPenguin
