### ISSUE TITLE
Incorrect wording

### ISSUE THREAD

**Issue by John-Page** [mdn/content#35317]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker/filter

### What specific section or headline is this issue about?

First paragraph

### What information was incorrect, unhelpful, or incomplete?

The first para reads: " read-only property returns a NodeFilter ".    There is only one nodeFilter acive in a TreeWalker instance so it shold say "the" instead of "a".

### What did you expect to see?

. . . .read-only property returns **the** NodeFilter . . .

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/treewalker/filter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker/filter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/treewalker/filter/index.md
* Last commit: https://github.com/mdn/content/commit/6f42d4c0bcc46d06ebcd084588f43768332bd2eb
* Document last modified: 2024-01-08T10:32:33.000Z

</details>

**Comment by Josh-Cena** [comment]
I personally don't think it matters since it says "a NodeFilter that is the filtering object associated", so it immediately clarifies that it's a singleton. Nevertheless accepting a PR to make it simply say "the `NodeFilter` associated with the `TreeWalker`".

**Comment by John-Page** [comment]
Good, OK.  The way it is makes it sound like it creates a new instance of a
filter object.   Like a factory method.
