### ISSUE TITLE
scripting.RegisteredContentScript: says `world` property is not supported: Support was added in Firefox 128

### ISSUE THREAD

**Issue by gorhill** [mdn/content#35315]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/RegisteredContentScript

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

It says `world` is not supported in Firefox.

### What did you expect to see?

`world` being supported in Firefox 128.

### Do you have any supporting links, references, or citations?

<https://bugzilla.mozilla.org/show_bug.cgi?id=1736575#c16>:

> This adds support for the world:"MAIN" option to the following parts of the scripting API, including tests:
> 
>    ...
>    scripting.registerContentScripts
>    ...

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/RegisteredContentScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
* Last commit: https://github.com/mdn/content/commit/b8a00c993f386a9ab7944fccd636f52041a3828c
* Document last modified: 2024-07-26T03:15:09.000Z

</details>

**Comment by hamishwillee** [comment]
@rebloor Is this something missed in web extensions updates?

**Comment by rebloor** [comment]
@hamishwillee this was updated in https://github.com/mdn/browser-compat-data/pull/23539 as noted in the bugzilla comment https://bugzilla.mozilla.org/show_bug.cgi?id=1736575#c20. However, the updated BCD isn't yet published although the release note is: https://bugzilla.mozilla.org/show_bug.cgi?id=1736575#c20 (see the  eighth item).
