### ISSUE TITLE
Domain Hijacking for links to Inclusive Design Principles website

### ISSUE THREAD

**Issue by djm1176** [mdn/content#35316]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

### What information was incorrect, unhelpful, or incomplete?

There is a link on the page for webkit scrollbar css styling that links to https://inclusivedesignprinciples.org/#be-consistent. This domain looks to be to a scam/slot gambling site. It looks like the correct link should be *.info instead of *.org

### What did you expect to see?

A website that isn't a scam and provides documentation

### Do you have any supporting links, references, or citations?

https://inclusivedesignprinciples.org/#be-consistent (SCAM) vs https://inclusivedesignprinciples.info/#be-consistent (Correct)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_doublecolon_-webkit-scrollbar`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_-webkit-scrollbar/index.md
* Last commit: https://github.com/mdn/content/commit/4cb569f768ec9529724f8fb06539f2903a583a41
* Document last modified: 2024-07-26T15:45:53.000Z

</details>

**Comment by bsmth** [comment]
Thanks for raising and fixing. Just for good measure, I ran a search through https://github.com/mdn/translated-content and found no occurrences 👍🏻
