### ISSUE TITLE
Containing_block: content-visibility can form a new containing block

### ISSUE THREAD

**Issue by ajvincent** [mdn/content#35312]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block

### What specific section or headline is this issue about?

Identifying the containing block

### What information was incorrect, unhelpful, or incomplete?

"If the position property is absolute or fixed, the containing block may also be formed" missed a mention of the content-visibility CSS property being set to auto.

### What did you expect to see?

The content-visibility should be listed as a cause of a container block.

### Do you have any supporting links, references, or citations?

- https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility#auto
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Using_CSS_containment#contain_values
   "The layout container is a [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block) for absolute- and fixed-positioned descendants."

**Comment by estelle** [comment]
Thank you @ajvincent for reporting this, and thank you @OnkarRuikar for fixing it!
