### ISSUE TITLE
SecurityPolicyViolationEvent docs have unexpected HTTP sidebar

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#35320]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/SecurityPolicyViolationEvent

### What information was incorrect, unhelpful, or incomplete?

This page and all its member pages have the HTTP sidebar.

### What did you expect to see?

A normal APIRef sidebar containing instance properties.

### Do you have any supporting links, references, or citations?

This was changed in https://github.com/mdn/content/pull/15774 and @wbamberg commented with the same concern.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/securitypolicyviolationevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SecurityPolicyViolationEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/securitypolicyviolationevent/index.md
* Last commit: https://github.com/mdn/content/commit/6d194a9afcce7beef0082c1dc50644bd0fcda635
* Document last modified: 2023-02-19T09:03:59.000Z

</details>

**Comment by hamishwillee** [comment]
Yeah, it's fired when you have a violation, so not surprising. I'll deal with this as part of https://github.com/mdn/content/issues/35279

**Comment by hamishwillee** [comment]
Should be fixed by #35384
