### ISSUE TITLE
HTTP headers page should exhaustively list all documented headers

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#35325]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

### What information was incorrect, unhelpful, or incomplete?

While it's known that some headers on this page are undocumented (https://github.com/mdn/content/issues/1458), there are even more documented headers that are not listed on this page.

### What did you expect to see?

Things like `Accept-Charset` should be listed on this page.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/index.md
* Last commit: https://github.com/mdn/content/commit/cb132bc83b660e51be8959de5336c00b08030104
* Document last modified: 2024-08-01T16:24:09.000Z

</details>

**Comment by bsmth** [comment]
Thanks, Josh. I can take this one if that sounds good to you.

**Comment by bsmth** [comment]
I have the following list:

```
accept-charset
accept-patch
accept-post
content-digest
content-dpr
digest
dnt
dpr
expect-ct
index.md
observe-browsing-topics
origin-agent-cluster
reporting-endpoints
repr-digest
sec-browsing-topics
sec-ch-prefers-reduced-transparency
sec-websocket-accept
set-login
viewport-width
want-content-digest
want-digest
want-repr-digest
```
