### ISSUE TITLE
"Web-based protocol handlers" should not be a subpage of `navigator.registerProtocolHandler`

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/content#35330]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler/Web-based_protocol_handlers

### What information was incorrect, unhelpful, or incomplete?

This page's location is wrong.

### What did you expect to see?

A guide page should not be a subpage of an interface method; this is undiscoverable.

I'm unsure where it can be moved to, though, since this seems like a small topic.

### Do you have any supporting links, references, or citations?

https://github.com/mdn/content/pull/35177#discussion_r1693795754

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/registerprotocolhandler/web-based_protocol_handlers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler/Web-based_protocol_handlers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/registerprotocolhandler/web-based_protocol_handlers/index.md
* Last commit: https://github.com/mdn/content/commit/8d5440dbd259fd6eea32b4f4a200f25257d1bf41
* Document last modified: 2024-07-27T04:44:44.000Z

</details>

**Comment by wbamberg** [comment]
I think technically the answer to this, within the context of the Web API IA is: move it under https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API. But 

But perhaps a more helpful thing to do would be to cut this down a bit and merge it into https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler.

**Comment by Josh-Cena** [comment]
The HTML_DOM_API is such a huge area, though, and it's hard to say why `registerProtocolHandler` has any close relationship to things like HTML elements, other than being defined in the HTML spec.

**Comment by wbamberg** [comment]
Yeah, that's why I think #2 is more helpful. The underlying issue is that the organization (IA) of Web/API is not very effective any more, but fixing that is quite a huge task that noone wants to invest in -> https://github.com/openwebdocs/project/issues/76.

**Comment by Josh-Cena** [comment]
I would also be happy with deleting this page :)

**Comment by wbamberg** [comment]
+1 if there would be nothing worth incorporating into the method page. I didn't look at it in enough detail to know (but there's clearly stuff that could be removed, such as old Firefox screenshots).

**Comment by Josh-Cena** [comment]
Yeah, clarification: meant "take what's useful, if there is, into the method page, then delete it"

**Comment by wbamberg** [comment]
> "take what's useful, if there is, into the method page, then delete it"

@Josh-Cena , I will take a look at this.
