### ISSUE TITLE
HTML Weekly dated updated automatically

### ISSUE THREAD

**Issue by suitcase06** [mdn/content#3533]
ENGLISH
Hello, 
I am creating a web page. I will make Live Web Conferences every Wednesday at 8:00 pm. I want to integrate an HTML code in my page that will allow the date of the next Wednesday to be displayed when the user arrives on my page. The Wednesday date will be automatically adjusted every week. 

I am on System.io, an equivalent of ClickFunnel in the US.

Thanks for your help! 
Martin

FRANCAIS
Bonjour, 
Je suis en train de créer une page internet. Je vais faire des conférences tous les mercredi  chaque semaine à 20h00. Je désire intégrer un Code HTML qui va permettre que la date du mercredi prochain s'affiche lorsque l'internaute arrivera sur ma page. La date du mercredi s'ajustera automatiquement chaque semaine. 

Je suis sur System.io un équivalent de ClickFunnel américain.

Merci de votre aide! 
Martin

**Comment by chrisdavidmills** [comment]
Hi there. This isn't a coding help forum. This is for issues relating to content on the https://developer.mozilla.org site.
