### ISSUE TITLE
Ambiguous wording

### ISSUE THREAD

**Issue by John-Page** [mdn/content#35365]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration

### What specific section or headline is this issue about?

First paragraph

### What information was incorrect, unhelpful, or incomplete?

The phrase "Text decorations are drawn across descendant text elements. "    While correct it initially confused me because the word "descender" has a specific meaning in typography.   It is the part of a glyph that hangs dow below the baseline as in the letters p and y.  So it reads to a typographer at first glance as  "the underline cuts through the descenders of the glyph.    Which is true, but not what you meant.

### What did you expect to see?

Perhaps "Text decorations are added to the text of the element and all its child elements"  Or something like that...

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/text-decoration`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/text-decoration/index.md
* Last commit: https://github.com/mdn/content/commit/b782b7d57e7040d5d9644a19017f4683044b5c90
* Document last modified: 2023-04-20T16:59:46.000Z

</details>

**Comment by Josh-Cena** [comment]
"Descendant" and "descender" are different words. "Descendant" is also a technically precise and unambiguous term in CSS; see [descendant combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator), for example.

**Comment by John-Page** [comment]
I know that!   I am just offering better wording.   You don't seem to want
any suggestions. I think I will just stop submitting them.
