### ISSUE TITLE
Add prominent note to `FontFaceSet.check()` about non-existent fonts

### ISSUE THREAD

**Issue by schuetzm** [mdn/content#35369]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check

### What specific section or headline is this issue about?

Intro

### What information was incorrect, unhelpful, or incomplete?

This method returns `true` if the requested font doesn't exist, which is really counter-intuitive (I understand it's for privacy reasons).

### What did you expect to see?

There should be a prominent note in the intro that this function cannot be used to check whether a particular font style can be rendered as requested, but that it is only meant for avoiding the font swap problem.

**Comment by AshmitGupta** [comment]
@mdn/mdn-community-engagement Can I work on this issue?
