### ISSUE TITLE
colspan="2" attribute on the tfoot td dont match expected results as presented on the image of the table rendered.

### ISSUE THREAD

**Issue by kelvinmacharia254** [mdn/content#35368]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Styling_tables

### What specific section or headline is this issue about?

html code

### What information was incorrect, unhelpful, or incomplete?

The html code on the <tfoot> of the table is:

`<tfoot>
            <tr>
                <th scope="row">Total albums</th>
                <td colspan="2">77</td>
            </tr>
        </tfoot>`
        

### What did you expect to see?

It should be:

`<tfoot>
            <tr>
                <th scope="row">Total albums</th>
                <td colspan="3">77</td>
            </tr>
        </tfoot>`
        
        
The colspan should be equal to 3 to span the remaining 3 columns instead of 2. This will match the image of the finished and styled table presented in the example.

### Do you have any supporting links, references, or citations?

Test the code again to see result.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/styling_tables`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Styling_tables
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/styling_tables/index.md
* Last commit: https://github.com/mdn/content/commit/adc54f35f47b9d5e4a4f3a88bc9f70b26d8026e0
* Document last modified: 2024-07-01T16:03:18.000Z

</details>

**Comment by Josh-Cena** [comment]
This is correct. Try it:

<img width="690" alt="image" src="https://github.com/user-attachments/assets/c07d5ce3-99b7-4f60-ac99-b5eaa4e06524">

Did you notice that the "Total albums" `th` has `colspan="2"` too?

**Comment by kelvinmacharia254** [comment]
I missed that
