### ISSUE TITLE
Spelling of color/colour doesn't match spelling in Webextensions Examples

### ISSUE THREAD

**Issue by GrippenDynamik** [mdn/content#35404]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests

### What specific section or headline is this issue about?

Managed storage manifests

### What information was incorrect, unhelpful, or incomplete?

https://github.com/mdn/webextensions-examples/tree/main/favourite-colour uses the British spelling "colour" everywhere.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#managed_storage_manifests uses the American spelling "color" in 6 locations.

Before you accuse me of being pedantic:
The extension ID must be exactly the same everywhere in the extension.
(same for the names of the storage keys)
Otherwise, the extension won't work.

And this happens when someone downloads the extension from https://github.com/mdn/webextensions-examples/tree/main/favourite-colour but copies the storage manifest from https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#managed_storage_manifests

### What did you expect to see?

The same spelling of color/colour everywhere.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/native_manifests`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/native_manifests/index.md
* Last commit: https://github.com/mdn/content/commit/d0346a05802ecb2f40b4c1e1fa1d69edeaff9886
* Document last modified: 2024-08-08T17:51:46.000Z

</details>

**Comment by Josh-Cena** [comment]
This should be fixed as part of https://github.com/mdn/content/issues/35404 but that PR is currently stalled so hopefully we can have a separate fix.

**Comment by AshmitGupta** [comment]
Can I work on this? 
Do we want all the spellings to be 'color' or 'colour' or either (just the same throughout the page)?

PS: First time contirbutor

**Comment by Josh-Cena** [comment]
You should modify all, but only, the references to the `favourite-colour` web-extensions example. I reckon that it's safe if you just search&replace all `favourite-color` occurrences in the `mozilla/add-ons` folder—there are two files. We also have `favorite-color` but those look unrelated to the external example.
