### ISSUE TITLE
415 response should use Accept-Post not Accept

### ISSUE THREAD

**Issue by lsc4719** [mdn/content#35414]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415

### What specific section or headline is this issue about?

examples

### What information was incorrect, unhelpful, or incomplete?

In examples, `Accept` header of responses should be changed to `Accept-Post` according to following MDN documents.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Post
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept

### What did you expect to see?

Accept-Post

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Post
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept

### Do you have anything more you want to share?

Thank you for your service.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/415`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/415/index.md
* Last commit: https://github.com/mdn/content/commit/ba53fe04589c36a2210d7549c003f3016093ef8e
* Document last modified: 2024-07-24T12:45:06.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you very much. This will be fixed by #35424
