### ISSUE TITLE
Misleading Explanation of Single-Value Syntax for `transform-origin`

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [mdn/content#35411]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

In the MDN documentation for the transform-origin property, it states:

If a single [\<length>](https://developer.mozilla.org/en-US/docs/Web/CSS/length) or [\<percentage>](https://developer.mozilla.org/en-US/docs/Web/CSS/percentage) value is defined, it represents the horizontal offset.

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin#syntax

This explanation can be misleading because when the keywords `top` and `bottom` are used, they affect the vertical axis rather than the horizontal one. In these cases, the horizontal axis defaults to center.

The W3C specification clarifies this behaviour:

If only one value is specified, the second value is assumed to be [center](https://www.w3.org/TR/css-transforms-1/#valdef-transform-origin-center). If one or two values are specified, the third value is assumed to be 0px.

Here’s the relevant link to the W3C spec: https://www.w3.org/TR/css-transforms-1/#transform-origin-property

This might confuse readers, so I suggest revising the documentation to accurately reflect the behaviour when only one value is specified.

### What did you expect to see?

Update the single use `keyword` values behaviour description for `transform-origin` property.

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/css-transforms-1/#transform-origin-property

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/transform-origin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/transform-origin/index.md
* Last commit: https://github.com/mdn/content/commit/fc1cc5684c98d19816d5cc81702d70f2a0debbad
* Document last modified: 2024-07-26T14:35:43.000Z

</details>

**Comment by Josh-Cena** [comment]
The sentence you quoted explicitly says "if a length or percentage is used". There's no mention of `top` or `bottom` at all.

**Comment by JayaKrishnaNamburu** [comment]
Right below the syntax the keywords are being mentioned under the "One value syntax" section.

The value must be a [<length>](https://developer.mozilla.org/en-US/docs/Web/CSS/length), a [<percentage>](https://developer.mozilla.org/en-US/docs/Web/CSS/percentage), or one of the keywords left, center, right, top, and bottom.

Should that be highlighted the keyword values behave in a different way as well ?

**Comment by Josh-Cena** [comment]
The first sentence tells you what happens if you use a length or a percentage. The second sentence tells you that apart from length or percentage, single-values can also be a single keyword. If you want to understand what the keywords mean, you have to keep reading on because it's explained in the "values" section. The current form follows our syntax section structure and is factually correct.
