### ISSUE TITLE
Issue with "OpenSearch description format": How to add a search engine programmatically?

### ISSUE THREAD

**Issue by tomprince** [mdn/content#3542]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/OpenSearch

#### What information was incorrect, unhelpful, or incomplete?

From the introduction,

> can be installed programmatically as described in [Adding search engines from web pages](https://developer.mozilla.org/en-US/docs/Web/OpenSearch)

links back to itself, but doesn't appear to have any description of how to add a search engine programmatically.

#### What did you expect to see?

Either a link to a different page, or a specific heading of the same page, or no mention of adding an engine programmatically.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/opensearch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/OpenSearch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/opensearch/index.html
* Last commit: https://github.com/mdn/content/commit/4a23c30c528fa31a276b2f0448b650556e42fdf1
* Document last modified: 2021-03-17T03:44:53.000Z

</details>

**Comment by chrisdavidmills** [comment]
To whoever handles this issue: I can't find the content this link is supposed to link to. I would suggest adding a section to the main OpenSearch page covering how to do this, and then link it to that section.

**Comment by teoli2003** [comment]
I wonder if there is actually anything to do programmatically. I think each browser will detect the search engine and allow to add it (more or less easily).

What about slightly rephrasing and link it to this: https://www.howtogeek.com/114176/how-to-easily-create-search-plugins-add-any-search-engine-to-your-browser/ ?

@chrisdavidmills , @tomprince: what do you think about it?
