### ISSUE TITLE
Link address error

### ISSUE THREAD

**Issue by itldg** [mdn/content#35427]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSS_Painting_API

### What specific section or headline is this issue about?

CSS Painting API

### What information was incorrect, unhelpful, or incomplete?

Link Pointing Error

### What did you expect to see?

Correct Jump Link

### Do you have any supporting links, references, or citations?

PaintRenderingContext2D and PaintSize 

Link address error

### Do you have anything more you want to share?

![image](https://github.com/user-attachments/assets/ff446bb2-2d4d-4571-9c26-52f865996c69)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/css_painting_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSS_Painting_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/css_painting_api/index.md
* Last commit: https://github.com/mdn/content/commit/3b39e41fb9393a13b16aaf58ba25174a62205041
* Document last modified: 2024-01-17T12:49:19.000Z

</details>

**Comment by Josh-Cena** [comment]
If you look at the link on the page, you see that its page hasn't been written yet. This is already tracked in https://openwebdocs.github.io/web-docs-backlog/all/
