### ISSUE TITLE
`Content-type` -> `Content-Type` casing errata

### ISSUE THREAD

**Issue by lsc4719** [mdn/content#35430]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT

### What specific section or headline is this issue about?

request example

### What information was incorrect, unhelpful, or incomplete?

https://github.com/mdn/content/blob/1a7695e13c51d85a81e3e5d85feedbc5dbd2a379/files/en-us/web/http/methods/put/index.md?plain=1#L58-L59

`Content-type`
`Content-length`

This is not wrong but conventionally unnatural.

### What did you expect to see?

`Content-Type`
`Content-Length`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/index.md
* Last commit: https://github.com/mdn/content/commit/b76266228bd0900aa1256902c7858971156a58c9
* Document last modified: 2024-07-25T19:07:12.000Z

</details>

**Comment by Josh-Cena** [comment]
HTTP headers are case-insensitive.

OK if someone wants to do a global search&replace for canonical header names. There seem to be a few of them.

**Comment by lsc4719** [comment]
Cause it's not incorrect, I close this issue.
