### ISSUE TITLE
Click event: not any focusable element triggers a click when enter/space is pressed

### ISSUE THREAD

**Issue by Mika56** [mdn/content#35450]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event

### What specific section or headline is this issue about?

Element: click event

### What information was incorrect, unhelpful, or incomplete?

Third bullet says:

> the Space key or Enter key is pressed while the element is focused

My reading is that any element that is currently focused will trigger a `click` when space or enter key is pressed (including elements made focusable by `tabindex`). This is not the case.

### What did you expect to see?

I'm not certain, but being focused is not the only requirement for this to work

### Do you have any supporting links, references, or citations?

Chrome bug: https://issues.chromium.org/issues/40776466 (won't fix)

Discussed in: #30263

Merged in: #30671 

### Do you have anything more you want to share?

Sample code found on Chrome bug: https://jsfiddle.net/yonran/pmkGN/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/click_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/click_event/index.md
* Last commit: https://github.com/mdn/content/commit/d0b23f3f26637aa405ee9ee0a0892fc6e9b742ef
* Document last modified: 2024-07-26T02:56:49.000Z

</details>

**Comment by Josh-Cena** [comment]
This seems like a web compat concern, rather than an intentional decision, that non-native controls don't trigger click. In this case it should be a note with a link to the said Chromium issue.

**Comment by Mika56** [comment]
The behavior is the same on Firefox 129 (I had it tested on Edge before). While this may be a web compat issue, if no browser has this behavior, then this bullet point is always wrong

**Comment by Josh-Cena** [comment]
This bullet is "in spirit" correct, and is in reality correct for native controls. It should be worded like this:

> - Any user interaction that is equivalent to a click, such as pressing the Space key or Enter key is pressed while the element is focused.
>
> > [!NOTE]
> > In practice, browsers don't fire this event for non-native control elements (such as a `<div>` with `tabindex="0"`). See [Chromium issue](https://issues.chromium.org/issues/40776466) for the reason.

**Comment by Mika56** [comment]
That would work for me :)
