### ISSUE TITLE
awkward sentence

### ISSUE THREAD

**Issue by laurelthorburn** [mdn/content#35459]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_size_and_style_queries

### What information was incorrect, unhelpful, or incomplete?

"To prevent an element from being a size container, set container-type: normal. This removes containment, meaning the element isn't a size container (it can still be a [style container](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_size_and_style_queries#container_style_queries)."

### What did you expect to see?

either end the parentheses or remove it.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_containment/container_size_and_style_queries`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_size_and_style_queries
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
* Last commit: https://github.com/mdn/content/commit/bb48907e64eb4bf60f17efd7d39b46c771d220a0
* Document last modified: 2024-08-13T13:25:16.000Z

</details>

**Comment by Josh-Cena** [comment]
It just needs a parenthesis before the period. Do you want to make a PR?
