### ISSUE TITLE
Mention tab-size in white-space

### ISSUE THREAD

**Issue by jenstroeger** [mdn/content#35462]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

### What information was incorrect, unhelpful, or incomplete?

The page mentions the tab character in several places without going into more detail about how a tab is interpreted. It took me a while to find out about [tab-size](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size) and that — apparently — the default tab is interpreted as a width of 8 spaces ([link](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size#comparing_to_the_default_size)).

### What did you expect to see?

Some mention, perhaps a section mentioning tab interpretation, of the treatment of tab characters.

### Do you have anything more you want to share?

Happy to submit a PR if that helps.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/white-space`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/white-space/index.md
* Last commit: https://github.com/mdn/content/commit/9231a7046973685f4600e1891fa644ecce41ef3b
* Document last modified: 2024-07-26T14:44:17.000Z

</details>

**Comment by Josh-Cena** [comment]
Is it sufficient for you if we add `tab-size` to the see also?

**Comment by jenstroeger** [comment]
Yes, I think that’d be great!
