### ISSUE TITLE
Bundlers recommend worker URLs to be fully resolved

### ISSUE THREAD

**Issue by qiulang** [mdn/content#35475]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

### What specific section or headline is this issue about?

Spawning a dedicated worker

### What information was incorrect, unhelpful, or incomplete?

Almost all bundlers need to pass a URL to the Worker constructor instead of a string literal,

```
const worker = new Worker( new URL( './worker.js', import.meta.url ) ); // bundlers need this instead of the next one
const worker = new Worker( './worker.js' ); 
```

Vite: https://v3.vitejs.dev/guide/features.html#web-workers
Webpack  https://webpack.js.org/guides/web-workers/
snowpack https://www.snowpack.dev/guides/web-worker/
parcel https://parceljs.org/languages/javascript/#web-workers

It will be helpful to explain why (and when) we need URL not a string literal. I also suggest add this information here https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker

### What did you expect to see?

Explain when and why we should use `new Worker( new URL( './worker.js', import.meta.url ) );` not `new Worker( './worker.js' );`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_workers_api/using_web_workers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_workers_api/using_web_workers/index.md
* Last commit: https://github.com/mdn/content/commit/b065c09b79d18abf0f04778c9307e1c312b8c6f9
* Document last modified: 2024-08-02T15:47:51.000Z

</details>

**Comment by Josh-Cena** [comment]
Bundlers need to do this because the output files have a drastically different folder structure from the input files. We don't have this constraint and we just show you an example using bare-bones JavaScript. It is your responsibility to adapt it to your environment, including using any other URL that works in your setup.

That said, I think it's fine to point this out and link to the bundlers' docs, if necessary.

**Comment by qiulang** [comment]
We can't live without bundler when doing web app development so I think it is better to point this out.
