### ISSUE TITLE
Request's mode incorrectly documented

### ISSUE THREAD

**Issue by annevk** [mdn/content#35488]
In https://developer.mozilla.org/en-US/docs/Web/API/Request/mode it states

> Prevents the method from being anything other than HEAD, GET or POST, and the headers from being anything other than [CORS-safelisted request headers](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_request_header).

However, that is incorrect. The only no-CORS headers that are safelisted are here: https://fetch.spec.whatwg.org/#no-cors-safelisted-request-header-name. And that's a subset of the CORS-safelisted requested headers.

This probably came to be when the `Range` header was added for CORS.

Context: https://github.com/whatwg/fetch/issues/1310#issuecomment-2293381855. Credit: @anson0370.

**Comment by wbamberg** [comment]
Am I right in thinking that https://github.com/whatwg/fetch/blob/1dc1b034b208faf6652dced19954f67717da9ba1/review-drafts/2024-06.bs#L1985-L1988 also ought to be updated?

> "no-cors"
>
>    Restricts requests to using [CORS-safelisted methods](https://fetch.spec.whatwg.org/#cors-safelisted-method) and [CORS-safelisted request-headers](https://fetch.spec.whatwg.org/#cors-safelisted-request-header). Upon success, fetch will return an [opaque filtered response](https://fetch.spec.whatwg.org/#concept-filtered-response-opaque).

**Comment by sideshowbarker** [comment]
> Am I right in thinking that [whatwg/fetch@`1dc1b03`/review-drafts/2024-06.bs#L1985-L1988](https://github.com/whatwg/fetch/blob/1dc1b034b208faf6652dced19954f67717da9ba1/review-drafts/2024-06.bs#L1985-L1988) also ought to be updated?
> 
> > "no-cors"
> > Restricts requests to using [CORS-safelisted methods](https://fetch.spec.whatwg.org/#cors-safelisted-method) and [CORS-safelisted request-headers](https://fetch.spec.whatwg.org/#cors-safelisted-request-header). Upon success, fetch will return an [opaque filtered response](https://fetch.spec.whatwg.org/#concept-filtered-response-opaque).

No, that’s the request’s “credentials mode” https://fetch.spec.whatwg.org/#concept-request-credentials-mode, right?

Whereas, `no-cors` is a value for the request’s “mode” https://fetch.spec.whatwg.org/#concept-request-mode

**Comment by sideshowbarker** [comment]
> > `no-cors` is a value for the request’s “mode” [fetch.spec.whatwg.org#concept-request-mode](https://fetch.spec.whatwg.org/#concept-request-mode)
> 
> That's the bit I quoted (the green note):
>
> Am I misreading it?

You’re not misreading — I just misread your earlier comment…

So yeah, you’re right — that note should be updated
