### ISSUE TITLE
Issue with "Web APIs": The specifications section is ambiguous

### ISSUE THREAD

**Issue by wlnirvana** [mdn/content#3549]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API#specifications

Some specs are not listed, in particular the [XMLHttpRequest][1].

Some non-specs are listed, for example the canvas API and history API are not specs by themselves, but just one chapter/section of the HTML living standard.

I'm a bit puzzling what criteria are used here?

[1]:https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/yari/pull/3354 with a fix.
