### ISSUE TITLE
JavaScript closures can have less than 3 scopes

### ISSUE THREAD

**Issue by senocular** [mdn/content#35513]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures

### What specific section or headline is this issue about?

Closure scope chain

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures#closure_scope_chain

> Every closure has three scopes:
>
> 1. Local scope (Own scope)
> 2. Enclosing scope (can be block, function, or module scope)
> 3. Global scope

### What did you expect to see?

Something to the effect of

> Every closure has at least two scopes:
>
> 1. Local scope (own scope)
> 2. One or more enclosing scopes (can be block, function, module scope, and/or global scope)

### Do you have any supporting links, references, or citations?

A function in global does not prevent it from being a closure. As the [first paragraph](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures) states states, 

> In JavaScript, closures are created every time a function is created, at function creation time.

This includes functions created in global.

The [spec](https://tc39.es/ecma262/#sec-ordinaryfunctioncreate) also does not omit setting `[[Environment]]` based on whether or not the current lexical environment is global. Its always set.

This is observed when calling functions in other frames.

```js
function getNewArray() {
    return new Array()
}

// iframe is a reference to another frame with a copy of the
// getNewArray function defined in its own global scope
const iframeGetNewArray = iframe.contentWindow.getNewArray

console.log(getNewArray() instanceof Array) // true
console.log(iframeGetNewArray() instanceof Array) // false
// ^ Array created from iframe's global env, not this global env
// since iframeGetNewArray, as a closure, brought with it its
// definition's lexical environment
```

### Do you have anything more you want to share?

I don't know how useful it is to have this as a list.  The first paragraph of the page also states:

> a closure gives you access to an outer function's scope from an inner function.

So the reader should already know at least 2 scopes are involved. The point this section is trying to make is that all accessible scopes are available to the closure. Not sure if a bullet list is necessary to convey that.

I also struggled with how global was to be represented in the list format.  Beyond the local scope you have at least global, or if not just global, one or more other scopes along with global.

Of course global can largely be implied given that its "global", but given you can have multiple globals at play (e.g. iframes) I think being more explicit would be better. Doing so could affect more than just the referenced text in the page.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/closures`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/closures/index.md
* Last commit: https://github.com/mdn/content/commit/0b0cac4814d37f8a62d69de1b0d76dbe20d085ec
* Document last modified: 2024-07-25T21:56:18.000Z

</details>

**Comment by Josh-Cena** [comment]
Yeah, I think you can reword that however you think is better, or even just take it out. I also don't know why the next sentence starts with "A common mistake" when it's at most an oversight.
