### ISSUE TITLE
Browsers interpret flex shorthand to have 0% flex-basis

### ISSUE THREAD

**Issue by camsteffen** [mdn/content#35515]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/flex

### What information was incorrect, unhelpful, or incomplete?

The flex shorthand like `flex: 1` sets flex-basis to `0` according to spec. However browsers today are not in compliance with this spec, and set the basis to `0%`. This has real implications especially in flexbox-driven layouts, where the parent height is not explicitly defined.

### What did you expect to see?

MDN docs should provide a hint that the flex-basis might be `0%` rather than `0`, depending on the browser.

### Do you have any supporting links, references, or citations?

https://github.com/w3c/csswg-drafts/issues/5742

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/flex`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/flex
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/flex/index.md
* Last commit: https://github.com/mdn/content/commit/2f27f95a09883099eeaa0edf0647be922c280ad6
* Document last modified: 2024-08-10T06:25:54.000Z

</details>

**Comment by Josh-Cena** [comment]
We have never mentioned `0%` and `0` being different for flex-basis, so this needs updates to both `flex` and `flex-basis` to explain the situation.

**Comment by OnkarRuikar** [comment]
This is [a browser bug](https://issues.chromium.org/issues/40816609). The browsers didn't change after the [specs changed it back to `0` from `0%`](https://drafts.csswg.org/css-flexbox/#change-2015-flex-basis-zero).

Percent values [don't behave the same](https://drafts.csswg.org/css-flexbox/#flex-basis-property) with flex-basis. Could you provide a minimal reproducible where `0` and `0%` produce different outputs?

I tried with the following code but couldn't reproduce the difference:
```html
<!doctype html>
<html>
  <body>
    <style>
      * {
        box-sizing: border-box;
      }

      .flex-container {
        background-color: wheat;
        display: flex;

        /* toggle width */
        awidth: 800px;
      }

      .item {
        background-color: blue;
        color: white;
        font-family: monospace;
        border: 1px double lime;
      }

      .one {
        flex: 1 1 0;
      }

      .two {
        flex: 1 1 0%;
      }
      
      .three {
        flex: 1;
      }
    </style>

    <div class="flex-container">
      <div class="item one">
        one ispsum dolara lorem ispsum dolara lorem ispsum dolara
      </div>
      <div class="item two">
        two ispsum dolara lorem ispsum dolara lorem ispsum dolara
      </div>
      <div class="item three">
        two ispsum dolara lorem ispsum dolara lorem ispsum dolara
      </div>
    </div>
    <script>
      const ele = document.querySelector(".item.two");
      const style = window.getComputedStyle(ele);
      console.log(style.getPropertyValue("flex"));
    </script>
  </body>
</html>
```

**Comment by camsteffen** [comment]
[Example](https://codesandbox.io/p/sandbox/flex-shorthand-y9l4rv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm01izfzr00063b6j3ong2150%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm01izfzq00023b6jj9hvqfnb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm01izfzq00033b6jdcs9ugyx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm01izfzr00053b6jlgc6uifs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm01izfzq00023b6jj9hvqfnb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm01izfzq00013b6j7f7rf4is%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522cm01izfzq00023b6jj9hvqfnb%2522%252C%2522activeTabId%2522%253A%2522cm01izfzq00013b6j7f7rf4is%2522%257D%252C%2522cm01izfzr00053b6jlgc6uifs%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm01izfzq00043b6jjl0ti5q4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cm01izfzr00053b6jlgc6uifs%2522%252C%2522activeTabId%2522%253A%2522cm01izfzq00043b6jjl0ti5q4%2522%257D%252C%2522cm01izfzq00033b6jdcs9ugyx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm01izfzq00033b6jdcs9ugyx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

(also posted in https://github.com/w3c/csswg-drafts/issues/5742)

**Comment by camsteffen** [comment]
This snippet of the CSS spec for [flex-basis](https://drafts.csswg.org/css-flexbox/#propdef-flex-basis) describes the problem fairly well:

> For all values other than [auto](https://drafts.csswg.org/css-flexbox/#valdef-flex-basis-auto) and [content](https://drafts.csswg.org/css-flexbox/#valdef-flex-basis-content) (defined above), [flex-basis](https://drafts.csswg.org/css-flexbox/#propdef-flex-basis) is resolved the same way as [width](https://drafts.csswg.org/css-sizing-3/#propdef-width) in horizontal writing modes [[CSS2]](https://drafts.csswg.org/css-flexbox/#biblio-css2), except that if a value would resolve to [auto](https://drafts.csswg.org/css-sizing-3/#valdef-width-auto) for width, it instead resolves to content for flex-basis. For example, percentage values of flex-basis are resolved against the flex item’s containing block (i.e. its [flex container](https://drafts.csswg.org/css-flexbox/#flex-container)); and if that containing block’s size is [indefinite](https://drafts.csswg.org/css-flexbox/#definite), the used value for flex-basis is content.

The slippery part is getting a parent element with an indefinite width/height.

I'm just not sure what is the approach for integrating really fine details like this into MDN docs. I suppose it's a non-goal for MDN to represent any and all information found in the CSS spec.

**Comment by Josh-Cena** [comment]
> I suppose it's a non-goal for MDN to represent any and all information found in the CSS spec.

It's hard to draw the line, but I'd say we should be a _superset_ of the spec and anything explicitly called out in the spec should also be mentioned by us while any interaction not explicitly mentioned in the spec may also be interesting to developers. Here we definitely need to document the difference between `0` and `0%`.

**Comment by OnkarRuikar** [comment]
So there are two thing to point out here:
1. `flex: 1` doesn't expand to `flex: 1 1 0` in browsers
2. Flex-basis `0` is not the same as `0%`

**Comment by OnkarRuikar** [comment]
FYI, I raised [a bug](https://issues.chromium.org/issues/361372992) in Chromium and here is what a maintainer said:
> Thanks for the bug report. If we do this change it'll likely break a large number of sites expecting the old behaviour unfortunately. (flexbox is used everywhere today - the bar for changing something as fundamental as this is super high now).
>
> I've filed an issue on the CSSWG to reflect what the browsers are currently doing and change flex:1 back to setting a flex-basis of 0% instead of 0px. See: https://github.com/w3c/csswg-drafts/issues/10782

Also, see https://github.com/w3c/csswg-drafts/issues/5742#issuecomment-2311482423
