### ISSUE TITLE
Add glossary: cloud

### ISSUE THREAD

**Issue by estelle** [mdn/content#35519]
### MDN URL

https://developer.mozilla.org/en-US/docs/glossary

### What specific section or headline is this issue about?

glossary

### What information was incorrect, unhelpful, or incomplete?

We mention "cloud" and "cloud computing" but don't really define it. WOuld be good to include a brief definiton.

### What did you expect to see?

cloud included in the MDN glossary.

**Comment by cwangsanata** [comment]
Where is cloud and cloud computing mentioned in the other docs?

**Comment by estelle** [comment]
It's mentioned 30 times in 17 different pages.

**Comment by hamishwillee** [comment]
FWIW "cloud computing" is mentioned zero times in the docs. I searched on that, and not "cloud". Definitely think this is worth a glossary entry.
