### ISSUE TITLE
Missing CSS property: word-wrap

### ISSUE THREAD

**Issue by estelle** [mdn/content#35521]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/word-wrap

### What specific section or headline is this issue about?

CSS properties

### What information was incorrect, unhelpful, or incomplete?

the `word-wrap` property, supported in all browsers, part of CSS Text 3, is not documented

### What did you expect to see?

the property documented.

**Comment by Josh-Cena** [comment]
I don't think there's anything interesting to be documented about it. Usually for legacy aliases a redirect would suffice.
