### ISSUE TITLE
Missing CSS properties: flood-color, flood-opacity, and lighting-color

### ISSUE THREAD

**Issue by estelle** [mdn/content#35520]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/lighting-color

### What specific section or headline is this issue about?

CSS properties

### What information was incorrect, unhelpful, or incomplete?

the page above redirects to the SVG attribute.
These properties are baseline since  2018-01-29

### What did you expect to see?

documentation for the `flood-color`, `flood-opacity`, and `lighting-color` css filter effect properties supported on some SVG elements

**Comment by Josh-Cena** [comment]
@estelle FYI I've closed all new documentation requests that can are in the web docs backlog because the docs backlog has effectively the same purpose. These properties are also in the backlog.
