### ISSUE TITLE
Example Creating a modal dialog

### ISSUE THREAD

**Issue by nils-boernsen-dev** [mdn/content#35532]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

### What specific section or headline is this issue about?

Creating a modal dialog

### What information was incorrect, unhelpful, or incomplete?

I am trying to teach myself HTML, CSS and JavaScript. Therefore I look a lot the MDN pages for that purpose. 
When I tried to follow the given examples for the HTML-Element `<dialog>`, I had problems with the example given in section creating a modal dialog. The given JS-Code in these lines

```js
const dialog = document.querySelector("dialog");
const showButton = document.querySelector("dialog + button");
const closeButton = document.querySelector("dialog button");
```

returned a null value for dialog, showButton and closeButton.
I searche the internet for dealing with that issue and found a solution under the following link:
https://stackoverflow.com/questions/20495960/document-queryselector-is-null-error
One proposed solution there was to load the JS-script using the defer attribute. When I added this to the `<script>` command in the <head> area of my HTML document, i. e.
        `<script src="main.js" defer></script>`
Everything worked as intended.

### What did you expect to see?

Not null values for dialog, showButton and CloseButton (s. above)

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/questions/20495960/document-queryselector-is-null-error

### Do you have anything more you want to share?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/dialog/index.md
* Last commit: https://github.com/mdn/content/commit/be7cf520036291031985ab0b38c487539b1faa9d
* Document last modified: 2024-08-01T23:51:43.000Z

</details>

**Comment by Josh-Cena** [comment]
This is the general style of these examples. You are expected to know how to apply scripts to HTML such that they are run after DOM is loaded. If you don't already, consider starting with our learning guide: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript#how_do_you_add_javascript_to_your_page

**Comment by nils-boernsen-dev** [comment]
Hi Joshua,
Thank you for the hint. I will look at the First_steps page, that you
attached. This was my first feedback to MDN. So please excuse me that I
have not the knowledge yet, that is assumed. I thought my feedback could
help others in a similar situation like mine.

Am Di., 20. Aug. 2024 um 17:49 Uhr schrieb Joshua Chen <
***@***.***>:
