### ISSUE TITLE
More a question than an Issue with "A re-introduction to JavaScript (JS tutorial)": Code with '(function() ... )()'

### ISSUE THREAD

**Issue by 552020** [mdn/content#3553]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript

#### What information was incorrect, unhelpful, or incomplete?

I#m having kind of hard times to understand what does "(function() ... )()" means, since I never met anything starting with a parentheses I guess.

#### Specific section or headline?

In the section "Functions". This paragraph:

[This is semantically equivalent to the function avg() form. It's extremely powerful, as it lets you put a full function definition anywhere that you would normally put an expression.] This enables all sorts of clever tricks. Here's a way of "hiding" some local variables — like block scope in C:

var a = 1;
var b = 2;

(function() {
  var b = 3;
  a += b;
})();

a; // 4
b; // 2

The first part of the paragraph, that I put in square brackets is perfectly clear, the rest at least for me not clear at all. 

#### What did you expect to see?

Maybe a link to  an article that would let a newbie understand what this code means:

 (function() {
  var b = 3;
  a += b;
})();

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/a_re-introduction_to_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/a_re-introduction_to_javascript/index.html
* Last commit: https://github.com/mdn/content/commit/187777c2a06009c7a876e712f3cb8b3fd236ae7d
* Document last modified: 2021-03-23T20:51:38.000Z

</details>

**Comment by sideshowbarker** [comment]
> Maybe a link to an article that would let a newbie understand what this code means:
> 
> (function() {
> var b = 3;
> a += b;
> })();

It’s an IIFE (Immediately Invoked Function Expression) https://developer.mozilla.org/en-US/docs/Glossary/IIFE. But it’s not a good example of an IIFE. I’ll try to see if I can come up with a better one to replace it (along with adding an explanation).

**Comment by sideshowbarker** [comment]
OK, I’ve opened https://github.com/mdn/content/pull/3698 with some changes to flesh out the information about anonymous functions and IIFEs.
