### ISSUE TITLE
Issue with "scale()" and other transforms: NOT recognised by newer browsers but works fine in older ones

### ISSUE THREAD

**Issue by needforsuv** [mdn/content#3554]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale()

#### What information was incorrect, unhelpful, or incomplete?
Browser support; Edge 84 (possibly broken earlier) doesn't recognise scale on its own outside of transform

#### Specific section or headline?
Browser support

#### What did you expect to see?
Note that scale on its own has been depreciated for newer browsers!

#### Did you test this? If so, how?
Chrome 51: Scale works on its own, and can be stacked with transform functions.
Edge: Can only have 1 transform function.

example:
.css-selector{
    transform: transformfunctionhere(); /*this works in both C51 and E84*/
scale: (scalearguments); /*this doesn't work or do anything since the browser (E84) says its unrecognised*/
}
SAME THING with other transforms like translate and rotate, which used to work fine on their own, but now HAVE to be inside transform in newer browsers to do anything at all.

This is A REGRESSION! How is anyone supposed to override/set a single transform function for newer browsers now?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/transform-function/scale()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/transform-function/scale()/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by chrisdavidmills** [comment]
This sounds like a problem with Edge, not the MDN documentation. Maybe when they moved to Chromium, they didnt end up enabling these functions for some reason?

**Comment by rachelandrew** [comment]
Our docs look to be correct as per the spec, unless there is some other info I think this is a browser issue.

**Comment by rachelandrew** [comment]
Closing as we seem to be correct as per spec, please re-open if there is some more info that suggests we should change something.

**Comment by needforsuv** [comment]
Has this been tested with anything other than edge 84?

If the chrome equivalent also doesn't work (can't test for obvious reasons that one can only have one chrome version on any pc) with transform functions (scale, rotate, etc.) outside of a transform wrapper, then it is indeed a regression.

Using them outside of a transform wrapper, official or not, if it stopped working after a certain chromium version (excluding edge now as that is the only browser to have changed major engines), should be noted.

Obviously, one way around the limitation would be to use css variables inside a transform function, possibly nested, and use more css to target for those variables.

Since it doesn't state on the page or the css documentation whether using the functions (scale, rotate, etc.) outside of a transform wrapper is official (rather, it suggests it is intended to be used inside the transform function), I thought this could be a potential issue or quirk.
