### ISSUE TITLE
OWD Project: Add missing form related API docs

### ISSUE THREAD

**Issue by estelle** [mdn/content#35544]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/

### What specific section or headline is this issue about?

The documents listed below, which are listed in the [Missing Form API spreadsheet](https://docs.google.com/spreadsheets/d/1DGVmfg-lgPODAft_h4yzgkO6t4RExQeRcz8UHfDpjb4/edit?usp=sharing) are missing and need to be documented.

### What information was incorrect, unhelpful, or incomplete?

The following pages are missing:
(please claim and update the [google spreadsheet](https://docs.google.com/spreadsheets/d/1DGVmfg-lgPODAft_h4yzgkO6t4RExQeRcz8UHfDpjb4/edit?usp=sharing)

- [x] [`HTMLButtonElement.reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/reportValidity)
- [x] [`HTMLButtonElement.checkValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/checkValidity)
- [x] [`HTMLButtonElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/form)
- [x] [`HTMLButtonElement.formAction`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/formAction)
- [x] [`HTMLButtonElement.formEnctype`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/formEnctype)
- [x] [`HTMLButtonElement.formMethod`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/formMethod)
- [x] [`HTMLButtonElement.formNoValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/formNoValidate)
- [x] [`HTMLButtonElement.formTarget`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/formTarget)
- [x] [`HTMLButtonElement.name`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/name)
- [x] [`HTMLButtonElement.setCustomValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/setCustomValidity)
- [x] [`HTMLButtonElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/validationMessage)
- [x] [`HTMLButtonElement.validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/validity)
- [x] [`HTMLButtonElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/value)
- [x] [`HTMLButtonElement.willValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/willValidate)
- [x] [`HTMLDataListElement.options`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDataListElement/options)
- [x] [`HTMLFieldSetElement.reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/reportValidity)
- [x] [`HTMLFieldSetElement.elements`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/elements)
- [x] [`HTMLFieldSetElement.type`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/type)
- [x] [`HTMLFieldSetElement.name`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/name)
- [x] [`HTMLFieldSetElement.checkValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/checkValidity)
- [x] [`HTMLFieldSetElement.disabled`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/disabled)
- [x] [`HTMLFieldSetElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/form)
- [x] [`HTMLFieldSetElement.setCustomValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/setCustomValidity)
- [x] [`HTMLFieldSetElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/validationMessage)
- [x] [`HTMLFieldSetElement.validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/validity)
- [x] [`HTMLFieldSetElement.willValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/willValidate)
- [x] [`HTMLFormElement.autocomplete`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/autocomplete)
- [x] [`HTMLFormElement.checkValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/checkValidity)
- [x] [`HTMLFormElement.noValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/noValidate)
- [x] [`HTMLInputElement.list`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/list)
- [x] [`HTMLInputElement.minLength`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/minLength)
- [x] [`HTMLInputElement.valueAsDate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/valueAsDate)
- [x] [`HTMLInputElement.accept`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/accept)
- [x] [`HTMLInputElement.alt`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/alt)
- [x] [`HTMLInputElement.autocomplete`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/autocomplete)
- [x] [`HTMLInputElement.checked`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/checked)
- [x] [`HTMLInputElement.defaultChecked`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/defaultChecked)
- [x] [`HTMLInputElement.defaultValue`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/defaultValue)
- [x] [`HTMLInputElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/form)
- [x] [`HTMLInputElement.formAction`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/formAction)
- [x] [`HTMLInputElement.formEnctype`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/formEnctype)
- [x] [`HTMLInputElement.formMethod`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/formMethod)
- [x] [`HTMLInputElement.formNoValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/formNoValidate)
- [x] [`HTMLInputElement.formTarget`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/formTarget)
- [x] [`HTMLInputElement.height`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/height)
- [x] [`HTMLInputElement.indeterminate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/indeterminate)
- [x] [`HTMLInputElement.max`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/max)
- [x] [`HTMLInputElement.maxLength`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/maxLength)
- [x] [`HTMLInputElement.min`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/min)
- [x] [`HTMLInputElement.name`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/name)
- [x] [`HTMLInputElement.pattern`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/pattern)
- [x] [`HTMLInputElement.placeholder`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/placeholder)
- [x] [`HTMLInputElement.readOnly`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/readOnly)
- [x] [`HTMLInputElement.required`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/required)
- [x] [`HTMLInputElement.size`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/size)
- [x] [`HTMLInputElement.src`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/src)
- [x] [`HTMLInputElement.step`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/step)
- [x] [`HTMLInputElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/validationMessage)
- [x] [`HTMLInputElement.validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/validity)
- [x] [`HTMLInputElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/value)
- [x] [`HTMLInputElement.valueAsNumber`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/valueAsNumber)
- [x] [`HTMLInputElement.width`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/width)
- [x] [`HTMLInputElement.willValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/willValidate)
- [x] [`HTMLLegendElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLegendElement/form)
- [x] [`HTMLMeterElement.high`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement/high)
- [x] [`HTMLMeterElement.low`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement/low)
- [x] [`HTMLMeterElement.max`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement/max)
- [x] [`HTMLMeterElement.min`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement/min)
- [x] [`HTMLMeterElement.optimum`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement/optimum)
- [x] [`HTMLMeterElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement/value)
- [x] [`HTMLObjectElement.reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/reportValidity)
- [x] [`HTMLOptGroupElement.disabled`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptGroupElement/disabled)
- [x] [`HTMLOptGroupElement.label`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptGroupElement/label)
- [x] [`HTMLOptionElement.defaultSelected`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/defaultSelected)
- [x] [`HTMLOptionElement.disabled`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/disabled)
- [x] [`HTMLOptionElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/form)
- [x] [`HTMLOptionElement.index`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/index)
- [x] [`HTMLOptionElement.label`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/label)
- [x] [`HTMLOptionElement.selected`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/selected)
- [x] [`HTMLOptionElement.text`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/text)
- [x] [`HTMLOptionElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/value)
- [x] [`HTMLOptionsCollection.add`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionsCollection/add)
- [x] [`HTMLOptionsCollection.length`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionsCollection/length)
- [x] [`HTMLOptionsCollection.remove`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionsCollection/remove)
- [x] [`HTMLOptionsCollection.selectedIndex`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionsCollection/selectedIndex)
- [x] [`HTMLOutputElement.reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/reportValidity)
- [x] [`HTMLOutputElement.checkValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/checkValidity)
- [x] [`HTMLOutputElement.defaultValue`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/defaultValue)
- [x] [`HTMLOutputElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/form)
- [x] [`HTMLOutputElement.htmlFor`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/htmlFor)
- [x] [`HTMLOutputElement.name`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/name)
- [x] [`HTMLOutputElement.setCustomValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/setCustomValidity)
- [x] [`HTMLOutputElement.type`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/type)
- [x] [`HTMLOutputElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/validationMessage)
- [x] [`HTMLOutputElement.validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/validity)
- [x] [`HTMLOutputElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/value)
- [x] [`HTMLOutputElement.willValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/willValidate)
- [x] [`HTMLSelectElement.autocomplete`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/autocomplete)
- [x] [`HTMLSelectElement.reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/reportValidity)
- [x] [`HTMLSelectElement.length`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/length)
- [x] [`HTMLSelectElement.multiple`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/multiple)
- [x] [`HTMLSelectElement.name`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/name)
- [x] [`HTMLSelectElement.required`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/required)
- [x] [`HTMLSelectElement.size`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/size)
- [x] [`HTMLSelectElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/validationMessage)
- [x] [`HTMLSelectElement.validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/validity)
- [x] [`HTMLSelectElement.willValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/willValidate)
- [x] [`HTMLTextAreaElement.autocomplete`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/autocomplete)
- [x] [`HTMLTextAreaElement.selectionDirection`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/selectionDirection)
- [x] [`HTMLTextAreaElement.setRangeText`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/setRangeText)
- [x] [`HTMLTextAreaElement.reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/reportValidity)
- [x] [`HTMLTextAreaElement.minLength`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/minLength)
- [x] [`HTMLTextAreaElement.textLength`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/textLength)
- [x] [`HTMLTextAreaElement.checkValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/checkValidity)
- [x] [`HTMLTextAreaElement.cols`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/cols)
- [x] [`HTMLTextAreaElement.defaultValue`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/defaultValue)
- [x] [`HTMLTextAreaElement.disabled`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/disabled)
- [x] [`HTMLTextAreaElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/form)
- [x] [`HTMLTextAreaElement.maxLength`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/maxLength)
- [x] [`HTMLTextAreaElement.name`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/name)
- [x] [`HTMLTextAreaElement.placeholder`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/placeholder)
- [x] [`HTMLTextAreaElement.readOnly`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/readOnly)
- [x] [`HTMLTextAreaElement.required`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/required)
- [x] [`HTMLTextAreaElement.rows`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/rows)
- [x] [`HTMLTextAreaElement.select`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/select)
- [x] [`HTMLTextAreaElement.selectionEnd`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/selectionEnd)
- [x] [`HTMLTextAreaElement.selectionStart`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/selectionStart)
- [x] [`HTMLTextAreaElement.setCustomValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/setCustomValidity)
- [x] [`HTMLTextAreaElement.setSelectionRange`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/setSelectionRange)
- [x] [`HTMLTextAreaElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/validationMessage)
- [x] [`HTMLTextAreaElement.validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/validity)
- [x] [`HTMLTextAreaElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/value)
- [x] [`HTMLTextAreaElement.willValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/willValidate)
- [x] [`HTMLTextAreaElement.wrap`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/wrap)

### What did you expect to see?

complete docs

**Comment by Josh-Cena** [comment]
@estelle I believe the "Add to BCD" section of the spreadsheet is irrelevant, as BCD scope is automatically sourced from webref, so there's practically no chance that it doesn't cover something in the spec.

**Comment by Josh-Cena** [comment]
@estelle I'm looking at https://docs.google.com/spreadsheets/d/1lvITVZJM8dx8s_Kee5UNI1hDfPNF0gXQwjPop5xIF5E/edit and I'm wondering if you missed a few.

- `HTMLFormElement.rel`
- `HTMLFormElement.relList`
- `HTMLInputElement.dirName`
- `HTMLObjectElement.getSVGDocument()`
- `HTMLTextAreaElement.dirName`

In addition the sheet also lists some deprecated properties, but understood if you want to deprioritize them.

**Comment by estelle** [comment]
This project was for baseline widely available features. 
I have been debating whether to do all form features (first "newly available", then "limited") or all non-svg-related widely available features next.

**Comment by Josh-Cena** [comment]
Ah ok, I didn't see they are baseline low. `HTMLObjectElement.getSVGDocument` is baseline high though.

**Comment by estelle** [comment]
object is not a form control.

It is in https://github.com/openwebdocs/project/issues/214 though
