### ISSUE TITLE
WorkerGlobalScope.importScripts URLs relative to what base URL?

### ISSUE THREAD

**Issue by stbergmann** [mdn/content#35568]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts

### What specific section or headline is this issue about?

Syntax: Parameters

### What information was incorrect, unhelpful, or incomplete?

> If the URL is relative, it is relative to the HTML document's base URL.

Is it really the HTML document's base URL that is being used here?  I didn't manage to drill down to the bottom of the <https://spec.whatwg.org/> specs, but from some experiments it looks like what is being used here as base URL by recent Chrome and Firefox at least, is the URL of the script with which the given worker was constructed.

### What did you expect to see?

not 100% sure what I expect, see above; that's why I ask

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/workerglobalscope/importscripts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/workerglobalscope/importscripts/index.md
* Last commit: https://github.com/mdn/content/commit/542ef6cfd82288925e0a9238b47933f03e2dddca
* Document last modified: 2023-08-04T05:38:55.000Z

</details>

**Comment by Josh-Cena** [comment]
I believe you are right: it should be relative to the worker's URL.
