### ISSUE TITLE
Broken Link. Page not found. 

### ISSUE THREAD

**Issue by pheianox** [mdn/content#3557]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML

In the sidebar there is a section called **Documentation**. Within that, there's a subsection **Useful lists**, it has a broken link with the name of `Pages tagged "HTML"`. 

Link name: `Pages tagged "HTML"`. 
Link URL: `https://developer.mozilla.org/en-US/docs/tag/HTML`. (Page not Found).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/index.html
* Last commit: https://github.com/mdn/content/commit/2d48835e97e7d226431f2be1a74558117fb44d0e
* Document last modified: 2021-02-03T18:43:39.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve raised https://github.com/mdn/yari/pull/3352 with a fix
