### ISSUE TITLE
Define the autocorrect attribute as standard

### ISSUE THREAD

**Issue by annevk** [mdn/content#35593]
It's being added to HTML in https://github.com/whatwg/html/pull/5841 and is already implemented by Chrome and Safari per comments there. (MDN seems to only list Safari though.)

**Comment by hamishwillee** [comment]
@annevk I can't see evidence that Chrome actually implemented this in that link - and it doesn't pass the tests https://wpt.live/html/editing/editing-0/autocorrection/autocorrection.html except for "Test autocorrection in an editing host.".

Am I missing something?

**Comment by annevk** [comment]
I'm not sure. In the HTML PR someone pointed out Chromium code that shows there's an implementation, but perhaps it never shipped. It also wasn't fully compliant.

Safari should soonish ship fully compliant behavior. The failing tests are not something I would expect web developers to run into when using this though. See https://github.com/WebKit/WebKit/commit/28a8a4b35f3332e595d58745699986a271dcd941 for the changes made to WebKit if you're interested.

**Comment by danielhjacobs** [comment]
This was the Chromium code seemingly: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/ime/input_method_controller.cc;l=1711-1716;drc=f83b758b5980e3fb3eafa11bab38116206907459

**Comment by hamishwillee** [comment]
Fixed by  #35692
