### ISSUE TITLE
Client toolchain example has docs/repo mismatch in `vite.config.js`

### ISSUE THREAD

**Issue by xander-doom** [mdn/content#35595]
### What information was incorrect, unhelpful, or incomplete?

There is a breaking code mismatch between what is in the docs and what is in the repo **which prevents the GitHub Pages site from displaying the commit graph.**

In "Introducing a complete toolchain" the following code is supplied for `vite.config.js`:

```js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
```
This works fine locally, but fails when deployed to GitHub Pages.

**Adding `base: "client-toolchain-example"`, to the `defineConfig` (as it is in the repository) fixes the behavior.**

```js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  base: "client-toolchain-example",
});
```

### What did you expect to see?

It doesn't make sense for the user to specify the `base:` when creating `vite.config.js` since they have not created the repository yet. So I believe there should be a short blurb in "Deploying our app" that instructs the user to add the `base: {repoName}` line to their `vite.config.js`. Perhaps with an explanation of why it is necessary because it's unclear (to me) why this difference in behavior between dev and prod environments exists.

### Do you have any supporting links, references, or citations?

related PRs:

- [x] mdn/client-toolchain-example#2 
- [x] mdn/client-toolchain-example#3

### Do you have anything more you want to share?

To reproduce the behavior delete `base: "client-toolchain-example",` from `vite.config.js`. It will still work locally, but break when deployed on GitHub.

This is my first JavaScript project. Thanks for the guide :)

**Comment by bsmth** [comment]
See

* https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain#javascript_transformation
* https://github.com/mdn/client-toolchain-example/blob/main/vite.config.js
