### ISSUE TITLE
image width & height

### ISSUE THREAD

**Issue by niexiaofei1988** [mdn/content#356]
[view](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Debugging_CSS)
[File url](https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/debugging_css/index.html)

why set img width and height ?  be out of shape

<img width="893" alt="1" src="https://user-images.githubusercontent.com/16014141/102502058-1fb4c480-40b9-11eb-93b8-45e82652f352.png">

when i open in new tab is ok

<img width="1440" alt="2" src="https://user-images.githubusercontent.com/16014141/102502162-4115b080-40b9-11eb-984f-5994e89c00b4.png">

**Comment by chrisdavidmills** [comment]
@escattone this is a widespread problem, it seems, when a specific `height` is set on an image. Can we run an automated fix on these at some point?

**Comment by escattone** [comment]
@chrisdavidmills Yes, we definitely can. Would this apply to all images?

**Comment by chrisdavidmills** [comment]
Yes, and image that has a width and height set on it, just needs the width.

**Comment by peterbe** [comment]
I'd rather we don't have inline styles at all and instead use `<img src="..." width="123" height="412">` where these numbers would come from a node library that finds out what the dimensions are of the file. 
The advantage of setting the `height` attribute is that it tells the browser to allocate that amount of height for when the image finishes loading and that means that any content *below* the image now "shift" once the image comes in. Also, why can't I find an MDN equivalent of [this article](https://web.dev/cls/)?

But perhaps it's worth a quick search-and-replace script, today, to make these image stretches go away nowish.

**Comment by Ryuno-Ki** [comment]
This appears to be fixed.

**Comment by niexiaofei1988** [comment]
Looks like it's alright, Thanks for your hard word
