### ISSUE TITLE
Issue with "Perceived performance": Promotional link

### ISSUE THREAD

**Issue by lxg** [mdn/content#3560]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/Perceived_performance

#### What information was incorrect, unhelpful, or incomplete?

In the “Minimize initial load” section, there is a link to a Magento-related webpage which has little to do with the topic is of a promotional nature.

#### Specific section or headline?

Minimize initial load

#### What did you expect to see?

Not a link referring to an external, irrelevant webpage.

#### Did you test this? If so, how?

Clicked and read the target page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/performance/perceived_performance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/Perceived_performance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/performance/perceived_performance/index.html
* Last commit: https://github.com/mdn/content/commit/151b4cdee8781d2992bdce26db2f2a4c75a9f2ca
* Document last modified: 2021-03-09T08:52:08.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/3563 with a fix
