### ISSUE TITLE
Missing doc: -webkit-fill-available

### ISSUE THREAD

**Issue by DrippingMellow** [mdn/content#35618]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/WebKit_Extensions

### What specific section or headline is this issue about?

D-I

### What information was incorrect, unhelpful, or incomplete?

There is an extension missing

### What did you expect to see?

I expected: `-webkit-fill-available` to see.

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/a/68270606/23058836

### Do you have anything more you want to share?

It's like `fit-content(stretch)`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/webkit_extensions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/WebKit_Extensions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/webkit_extensions/index.md
* Last commit: https://github.com/mdn/content/commit/bb48907e64eb4bf60f17efd7d39b46c771d220a0
* Document last modified: 2024-08-13T13:25:16.000Z

</details>

**Comment by OnkarRuikar** [comment]
The `-webkit-fill-available` is a value, not a property. So why do we need a separate page for it? It is an alias of `stretch` value which we've [documented recently](https://developer.mozilla.org/en-US/docs/Web/CSS/width#stretch).

The related discussion can be found in https://github.com/mdn/content/issues/29887#issuecomment-2289294005 .

**Comment by DrippingMellow** [comment]
I see, I didn't know that it was value.

I didn't want it to have a separate page, just maybe mentioned somewhere. The Reason for that is, that it took a long time to find information about it and its relation to `stretch`. But I've found it now; it's just hidden at first. 

1. You need to go down to [Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/width#browser_compatibility).
2. In the row for the stretch value click a version (everything except Firefox)

It's just really hard to find it when searching. Not to mention, you can't find it when searching on the MDN website itself.

Still, I thank you for your help.

**Comment by Josh-Cena** [comment]
This should get a mention on said page.
