### ISSUE TITLE
Two identical examples

### ISSUE THREAD

**Issue by 0-6-1-7** [mdn/content#35663]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get

### What specific section or headline is this issue about?

Chrome examples

### What information was incorrect, unhelpful, or incomplete?

Both examples are absolutely identical.
![mis](https://github.com/user-attachments/assets/ad99e9f9-24b9-4907-8b7a-f6c27b729ee4)

### What did you expect to see?

Emm... Some differences?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/storage/storagearea/get`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/get/index.md
* Last commit: https://github.com/mdn/content/commit/b8a00c993f386a9ab7944fccd636f52041a3828c
* Document last modified: 2024-07-26T03:15:09.000Z

</details>

**Comment by Josh-Cena** [comment]
MDN now exclusively uses arrow functions. We should just remove the first block.
