### ISSUE TITLE
Issue with "Content-Security-Policy-Report-Only": deprecated report-uri recommended

### ISSUE THREAD

**Issue by MarcelloTheArcane** [mdn/content#3566]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only

#### What information was incorrect, unhelpful, or incomplete?

I'm trying to sort out reporting on my Content-Security-Policy, and following the guide here shows examples using the `report-uri` directive.  However, according to the `report-uri` page (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri), this is deprecated in favour of `report-to`.

In addition, the `report-to` page recommends looking at this page to get information on how to use it, however there are no examples given, only `report-uri` ones.

#### Specific section or headline?

Any code examples

#### What did you expect to see?

`report-to` examples, instead of deprecated `report-uri` examples.  Or actually, both, since `report-to` isn't supported by all browsers yet.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy-report-only`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy-report-only/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by bsmth** [comment]
This should be fixed in https://github.com/mdn/content/pull/23404 so I'm going to close this as done now. Thank you :)
