### ISSUE TITLE
Corrupted files on github

### ISSUE THREAD

**Issue by patrick-here** [mdn/content#35671]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content

### What specific section or headline is this issue about?

Video and Audio on the web

### What information was incorrect, unhelpful, or incomplete?

The section includes a link to a github page with sample mp4 and webm files (rabbit320.mp4,webm).  However those files seem to be corrupted. They don't play using the sample code in a browser and even the "Celluloid" video player (on ubuntu) rejects them as "Unrecognized file format". 

### What did you expect to see?

A valid video file playing

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/video_and_audio_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/video_and_audio_content/index.md
* Last commit: https://github.com/mdn/content/commit/d71da812ee94c20658cb1916a123a42254ea545c
* Document last modified: 2024-08-07T22:02:28.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! They play on my mac. Try the following two URLs: https://mdn.github.io/learning-area/html/multimedia-and-embedding/video-and-audio-content/rabbit320.mp4 https://mdn.github.io/learning-area/html/multimedia-and-embedding/video-and-audio-content/rabbit320.webm

If they don't play on your device, it's possible that it's a device specific issue.
