### ISSUE TITLE
Issue with "Introduction to the server side": JavaScript (NodeJS) is better than NodeJS (JavaScript).

### ISSUE THREAD

**Issue by francoistm** [mdn/content#3568]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction

#### What information was incorrect, unhelpful, or incomplete?
[...] examples of popular server-side web languages include PHP, Python, Ruby, C#, and NodeJS (JavaScript).[...]

#### Specific section or headline?
Are server-side and client-side programming the same?

#### What did you expect to see?
It is a good idea to replace "NodeJS (JavaScript)" by "JavaScript (NodeJS)". I see many people thinking NodeJS is a language. Node is a runtime. JavaScript is the language. I didn't edit it directly in the article because I wanted to know if this "mistake" was made on purpose for better understanding or not.  

#### Did you test this? If so, how?
no test needed

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/first_steps/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/first_steps/introduction/index.html
* Last commit: https://github.com/mdn/content/commit/bd456157e7e89cc2c936f7dbdaf9d919890d4743
* Document last modified: 2021-02-04T15:48:30.000Z

</details>

**Comment by sideshowbarker** [comment]
> It is a good idea to replace "NodeJS (JavaScript)" by "JavaScript (NodeJS)". I see many people thinking NodeJS is a language. Node is a runtime. JavaScript is the language. I didn't edit it directly in the article because I wanted to know if this "mistake" was made on purpose for better understanding or not.

Please do go ahead and open a pull request for it — that rationale is convincing.
