### ISSUE TITLE
[WebAssembly] Ship exnref

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#35696]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1908375

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
> Note, I have NOT assigned this to me. It is probably going to be horrible and time consuming, and IMO not a high priority for the majority of MDN readers.  I will take it if no one else does, but deal with it over time.

I don't understand how references work in WASM and our docs don't help. I'm seeking help in https://github.com/WebAssembly/exception-handling/issues/280#issuecomment-2381865896 https://bugzilla.mozilla.org/show_bug.cgi?id=1908375#c5 . 

- [ ] BCD
- [ ] Docs
- [ ] Release note
- [ ] dev-docs-complete

**Comment by dletorey** [comment]
## PRs

- [Firefox release note PR](https://github.com/mdn/content/pull/36131)

**Comment by eqrion** [comment]
@hamishwillee Hi Hamish. The 'exnref' (and exception-handling feature in general) are intended to be used inside wasm functions for making source language (e.g. C++ try/catch/finally) exception handling work on the web. It does this using some new value types and instructions that can be used inside a wasm module.

Looking over our existing MDN docs, there is no pre-existing reference on value types/instructions. The closest is this walkthrough on creating a wasm module using the text format (https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format#exploring_fundamentals).

I don't think it makes sense to expand the walkthrough with this new types, as that would defeat the purpose of an overview. This new feature really would need to be part of some reference on wasm instructions, which MDN doesn't have. Adding one would be neat, but a ton of work, and also sort of niche (most web developers will get a compiled wasm from a compiler, not hand write one). So I'd think we probably don't need to extend MDN for this wasm feature.

**Comment by hamishwillee** [comment]
Thanks @eqrion - very happy to take this as "no further work" for the reasons you have given!
