### ISSUE TITLE
[WebAPI] Remove gfx.offscreencanvas.enabled pref

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#35701]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated - NA
- [ ] Interactive example and data repos are updated if appropriate - NA
- [ ] The content has been reviewed as needed - NA

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete` - Done already
- [ ] Add entry to Firefox release notes for enabled/preview features - NA
- [ ] Add/remove entry to Firefox experimental features page for preference/released features - NA

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1914083

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1914083#c8 there is nothing to do here and I am suprised this was added to the list because I marked it as "dev-doc-complete" a couple of weeks ago.

This is just removal of a pref that has been enabled by default for a while - so a no-op.
