### ISSUE TITLE
Enlace no funciona

### ISSUE THREAD

**Issue by edikuba** [mdn/content#3570]
En: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Functions
En: "Como alternativa, puedes utilizar la propiedad [arguments.callee](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/es/Referencia_de_JavaScript_1.5/Funciones/arguments/callee) (que no se recomienda)." El enlace es incorrecto
El enlace correcto es:  https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Function/caller

**Comment by sideshowbarker** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
