### ISSUE TITLE
Clarification for the SVG relative length normalized diagonal may be helpful

### ISSUE THREAD

**Issue by herrstrietzel** [mdn/content#35712]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/r

### What specific section or headline is this issue about?

"When the value is set as a percentage, it refers to the normalized diagonal of the current SVG viewport."

### What information was incorrect, unhelpful, or incomplete?

I think it's helpful what "normalized diagonal" actually means and how it's calculated.

To my own surprise the [W3C SVG (2 draft) spec](https://svgwg.org/svg2-draft/coords.html#Units) (albeit containing suggested enhancements which may probably never be implemented) provides a very concise explanation:   

> For any other length value expressed as a percentage of the [SVG viewport](https://svgwg.org/svg2-draft/coords.html#TermSVGViewport), the percentage must be calculated as a percentage of the normalized diagonal of the ‘[viewBox](https://svgwg.org/svg2-draft/coords.html#ViewBoxAttribute)’ applied to that viewport. If no ‘[viewBox](https://svgwg.org/svg2-draft/coords.html#ViewBoxAttribute)’ is specified, then the normalized diagonal of the [SVG viewport](https://svgwg.org/svg2-draft/coords.html#TermSVGViewport) must be used. The normalized diagonal length must be calculated with sqrt((width)**2 + (height)**2)/sqrt(2)

So including the calculation  `sqrt((width)**2 + (height)**2)/sqrt(2)` might be a good idea.

### What did you expect to see?

The revised paragraph may look something like this:  

> When the value is set as a percentage, it refers to the normalized diagonal of the current SVG viewport. The normalized diagonal is calculated like this `sqrt((width)**2 + (height)**2)/sqrt(2)`

### Do you have any supporting links, references, or citations?

https://svgwg.org/svg2-draft/coords.html#Units

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/attribute/r`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/r
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/r/index.md
* Last commit: https://github.com/mdn/content/commit/29a5380c100ee4ca462db3690ad4065a9d23895c
* Document last modified: 2024-08-10T06:14:47.000Z

</details>

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by herrstrietzel** [comment]
@maher-nakesh: Pardon, me but responding with a obscure link without referring to the simple suggestion to revise the current documentation appears slightly "phishy".

**Comment by Josh-Cena** [comment]
Don't worry, it's probably spam.

**Comment by herrstrietzel** [comment]
A simple solution may also to link to the respective spec https://svgwg.org/svg2-draft/coords.html#Units  in the specs footer.
