### ISSUE TITLE
Issue with "Applying styles and colors": (A createConicGradient example-Live Sample no display)

### ISSUE THREAD

**Issue by mayukhkchanda** [mdn/content#3571]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors

#### What information was incorrect, unhelpful, or incomplete?
No display in the _A createConicGradient example_ section's _Live sample_ area .When inspected the following exception is shown:
**A_createConicGradient_example:50 Uncaught TypeError: ctx.createConicGradient is not a function
    at draw (A_createConicGradient_example:50)
    at A_createConicGradient_example:72**

As the method _createConicGradient()_ is experimental and not yet available in most browsers, it would be helpful notifying the same to the readers. This would help readers to be cautious before using the method directly.

#### Specific section or headline?
A createConicGradient example -> Live sample display

#### What did you expect to see?
The _Live sample_ display should be shown alongside the _Screenshot_ display. Both the displays should be same. Instead the _Live sample_ display was blank.

#### Did you test this? If so, how?
Test Environment:
Browsers -> Microsoft Edge Version 89.0.774.57  (64-bit),Google Chrome Version 89.0.4389.90 (64-bit)
OS-> Edition-Windows 10 Pro 64-bit, Version- 20H2, Build-19042.867

Steps to reproduce:
1.Navigate to [https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors](url) page
2. Scroll to the _A createConicGradient example_
3.  _Live sample_ display is blank(Expected same as _Screenshot_ display)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvas_api/tutorial/applying_styles_and_colors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/applying_styles_and_colors/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by mayukhkchanda** [comment]
Attached is a screenshot of the A createConicGradient example-Live Sample no display issue
![Live_sample_no_display](https://user-images.githubusercontent.com/77236334/112729654-51a8b300-8f53-11eb-9f88-533cadb22ddc.png)

**Comment by sideshowbarker** [comment]
I can’t reproduce this in any current browsers. Although the browser-compat table claims Chrome requires the `#new-canvas-2d-api` to enable `createConicGradient` support, as far as I can see it works in Chrome without that needing to be enabled. And current Safari and Firefox both support it.
