### ISSUE TITLE
`PopStateEvent.hasUAVisualTransition` is not described

### ISSUE THREAD

**Issue by bramus** [mdn/content#35719]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent

### What specific section or headline is this issue about?

Instance properties

### What information was incorrect, unhelpful, or incomplete?

`hasUAVisualTransition` is not described under [Instance properties](https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent#instance_properties). It is listed in the [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent#browser_compatibility) table, though.

### What did you expect to see?

For `hasUAVisualTransition` to be listed under [Instance properties](https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent#instance_properties)

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-popstateevent-interface

### Do you have anything more you want to share?

This also applies to `NavigateEvent.hasUAVisualTransition`, specced in https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-navigateevent-interface. The `hasUAVisualTransition` instance property is not described in `NavigateEvent`’s list of [Instance properties](https://developer.mozilla.org/en-US/docs/Web/API/NavigateEvent#instance_properties).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/popstateevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/popstateevent/index.md
* Last commit: https://github.com/mdn/content/commit/55de68017f98094f45addb3ebaa0f7f52024f60b
* Document last modified: 2023-03-29T06:38:14.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi there, thanks for the issue! We have a backlog of docs to write: https://openwebdocs.github.io/web-docs-backlog/all/ and both of the said properties are in this backlog, so I'm closing this as a duplicate. Because they aren't implemented in many browsers, they are currently not prioritized.

**Comment by bramus** [comment]
> We have a backlog of docs to write […] and both of the said properties are in this backlog, so I'm closing this as a duplicate.

Perfect!

> Because they aren't implemented in many browsers, they are currently not prioritized.

As a heads up: this is coming to Safari 18, in addition to Chrome already shipping these.

**Comment by Josh-Cena** [comment]
Yeah I can see that from the web docs backlog. So it should be interoperable soon.
