### ISSUE TITLE
Location: port property incorrectly documented

### ISSUE THREAD

**Issue by rotu** [mdn/content#35732]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Location/port

### What specific section or headline is this issue about?

Example and description

### What information was incorrect, unhelpful, or incomplete?

Example and description are incorrect according to Firefox, Chrome, and Safari.

Description:
> The port property of the [Location](https://developer.mozilla.org/en-US/docs/Web/API/Location) interface is a string containing the port number of the URL. If the URL does not contain an explicit port number, it will be set to ''.

Example:
```
// Let's an <a id="myAnchor" href="https://developer.mozilla.org:443/en-US/docs/Location.port"> element be in the document
const anchor = document.getElementByID("myAnchor");
const result = anchor.port; // Returns:'443'
```

```js
let a = document.createElement("a");
a.href = 'https://developer.mozilla.org:443/en-US/docs/Location.port';
console.log(a.port) // prints ""
```

### What did you expect to see?

Port seems to be null if the url has the default port for the protocol, not just if it's unset.

If the example was correct, it should probably have an indication of WHEN it changed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/location/port`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Location/port
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/location/port/index.md
* Last commit: https://github.com/mdn/content/commit/1238ffad886924b20549d0cf3adca735cb0d074f
* Document last modified: 2023-11-26T22:27:03.000Z

</details>

**Comment by Josh-Cena** [comment]
We should add the same info as https://developer.mozilla.org/en-US/docs/Web/API/URL/port.

**Comment by rotu** [comment]
Even that could use rewording.

> The `port` property of the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) interface is a string containing the port number of the URL.

Maybe instead something like "The port property is a string which is either "" or the port number of the URL."

A `URL` object normalizes it to "" if the same as the per-protocol default. But I'm not sure if that means the `Location` object must do the same.

**Comment by skyclouds2001** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/port also need update, too

**Comment by skyclouds2001** [comment]
And another issue is that the example is says *HTMLAnchorElement.port*, not *Location.port*
