### ISSUE TITLE
Issue with "Debugger keyboard shortcuts": (short summary here please)

### ISSUE THREAD

**Issue by jmronco** [mdn/content#3573]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Debugger/Keyboard_shortcuts

#### What information was incorrect, unhelpful, or incomplete?
Keyboard shortcut for add a new breakpoint (Ctrl + B) after I find the line I want to add a breakpoint on a JSF file (Ctrl + G and then press Enter, the line I would like to add as a breakpoint is painted yellow)
![Version Information](https://user-images.githubusercontent.com/27731374/112734275-7f760380-8f23-11eb-8e88-dc0b3e635139.png)
) doesn't work  (version 87.0 (64-bit), last version)

#### Specific section or headline?
JSF file on the Debugger Developer Tools after I find the line I want to add a breakpoint on a JSF file (Ctrl + G and then press Enter, the line I would like to add as a breakpoint is painted yellow)

#### What did you expect to see?
I expected to see a new breakpoint added, and it didn't happened anything, not even the tag painted blue

#### Did you test this? If so, how?
Yes, by pressing Ctrl and then the letter B after I find the line I want to add a breakpoint on a JSF file (Ctrl + G and then press Enter, the line I would like to add as a breakpoint is painted yellow)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/debugger/keyboard_shortcuts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Debugger/Keyboard_shortcuts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/debugger/keyboard_shortcuts/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by hamishwillee** [comment]
Hi @jmronco 

I think you are saying that using `Ctrl + B` on a JSF file does not toggle breakpoint on and off. Is that correct?
Can you provide a URL on the Internet that we can use to replicate this, ideally with the line where you couldn't set the breakpoint? (that's what we really want in the issue template when we say "Did you test this? If so, how?" - otherwise we have to set up our own environment, files etc).

**Comment by jmronco** [comment]
Hi @hamishwillee I figured it out how to do it, so thank you so much for answer me anyway. Regards!
