### ISSUE TITLE
clip is deprecated

### ISSUE THREAD

**Issue by lor3k** [mdn/content#35743]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications

### What information was incorrect, unhelpful, or incomplete?

`clip` is deprecated; don't suggest to use it

### What did you expect to see?

I would remove solution with `clip` from the examples

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/file_api/using_files_from_web_applications`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/file_api/using_files_from_web_applications/index.md
* Last commit: https://github.com/mdn/content/commit/88467d31d2ad7bdfade8b38ec69f6702fee080d1
* Document last modified: 2024-09-02T17:10:57.000Z

</details>

**Comment by herrstrietzel** [comment]
Probably, this CSS part on "[Using a label element to trigger a hidden file input element](https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#using_a_label_element_to_trigger_a_hidden_file_input_element)"

for a **screen-reader-only** class should just be synchronized with the current recommendation on [a11yproject.](https://www.a11yproject.com/posts/how-to-hide-content/) - adding the more modern `clip-path: inset(50%);` property.   

```
.visually-hidden {
  clip: rect(0 0 0 0);
  clip-path: inset(50%);
  height: 1px;
  overflow: hidden;
  position: absolute;
  white-space: nowrap;
  width: 1px;
}
```
