### ISSUE TITLE
The Set has a compatibility issue with the Samsung browser

### ISSUE THREAD

**Issue by NataliiaZhurbenko** [mdn/content#35742]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

### What information was incorrect, unhelpful, or incomplete?

I used the Set to remove duplicates in the array, but the images from the array were not displayed on the Samsung browser on the phone and tablet

### What did you expect to see?

the images from the array are displayed on the Samsung browser

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/set/index.md
* Last commit: https://github.com/mdn/content/commit/8421c0cd94fa5aa237c833ac6d24885edbc7d721
* Document last modified: 2024-07-25T21:32:46.000Z

</details>

**Comment by Josh-Cena** [comment]
Could you elaborate? What's your code and what's the result?

**Comment by Josh-Cena** [comment]
Closing until more information is given; from the current information, it doesn't appear like it's a problem with `Set` itself but some other unsupported web API.
