### ISSUE TITLE
wrong variable name in exercise

### ISSUE THREAD

**Issue by klaczynski** [mdn/content#35748]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Arrays

### What specific section or headline is this issue about?

Arrays 3

### What information was incorrect, unhelpful, or incomplete?

The exercise starts with `let myArray =`
and it should start with `let myString =`

### What did you expect to see?

`Ryu,Ken,Chun-Li,Cammy,Guile,Sakura,Sagat,Juri`
instead shows 
`ReferenceError: myString is not defined`

### Do you have anything more you want to share?

On further working through the exercise I see myArray isn't wrong, but the example is setup in a way that does not show the text as you work through it.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/test_your_skills_colon__arrays`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Arrays
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/test_your_skills_colon__arrays/index.md
* Last commit: https://github.com/mdn/content/commit/bc0d0d1ef796435e969f6d65c7e5d3c08f4023aa
* Document last modified: 2024-07-25T21:20:22.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi, you are supposed to create the `myString` variable yourself in step 4.

**Comment by klaczynski** [comment]
Thank you I do understand that.  I think I did not write out my concern well.  This is my proposed change:

let myArray = [ "Ryu", "Ken", "Chun-Li", "Cammy", "Guile", "Sakura", "Sagat", "Juri" ];
let newArr = [];

// Add your code here

// Don't edit the code below here!

section.innerHTML = ' ';

let para1 = document.createElement('p');
let para2 = document.createElement('p');
para1.textContent = myArray;
para2.textContent = newArr;

section.appendChild(para1);
section.appendChild(para2);

**Comment by Josh-Cena** [comment]
We don't promise that the starting point of the example works. You are supposed to make it work, importantly _without_ editing the code below.
