### ISSUE TITLE
Number.prototype.valueof doesn't have information about error

### ISSUE THREAD

**Issue by Akindin** [mdn/content#35747]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/valueOf

### What specific section or headline is this issue about?

Syntax > Return Value

### What information was incorrect, unhelpful, or incomplete?

No information about type error

### What did you expect to see?

Information about TypeError which happens when called with this value other than number, such as 5..valueOf.call('432')

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/number/valueof`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/valueOf
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/number/valueof/index.md
* Last commit: https://github.com/mdn/content/commit/27180875516cc311342e74b596bfb589b7211e0c
* Document last modified: 2023-08-24T22:55:36.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! Most methods throw an error when not called on a value of this instance. We don't think this is useful to document in the general case, just like when we say "this parameter has to be a string", it's implied that passing a non-string can cause any behavior including throwing an error (e.g. if you pass a symbol). Rather, for those that happen to be valid when called on other instances, we have a special section saying it's generic. For examples, see `Array` methods and `Promise` methods.

**Comment by Akindin** [comment]
@Josh-Cena okay, but I thought about consistency, because for example this page tells about TypeError https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean/toString, so why others don't

**Comment by Josh-Cena** [comment]
Those are ancient docs. If you see them, you are welcome to remove them for consistency and I will merge one, but I think it's extremely low-priority. It's fine to have extra information but it's not worth the effort to either remove them or propagate them everywhere.
