### ISSUE TITLE
SMIL animation elements have 'fill' attribute that is linked incorrectly

### ISSUE THREAD

**Issue by anechunaev** [mdn/content#35760]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateMotion

### What specific section or headline is this issue about?

Attributes

### What information was incorrect, unhelpful, or incomplete?

Under the section of Animation Attributes, Animation Timing Attributes the attribute `fill` linked to incorrect page. It is linked to an attribute that defines the color of a graphical element.

### What did you expect to see?

Attribute `fill` for SMIL element should link to the description of animation timing attribute.

### Do you have any supporting links, references, or citations?

Link to the specification of the `fill` attribute: [Animation §19.2.8](https://www.w3.org/TR/SVG11/animate.html#FillAttribute)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/element/animatemotion`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateMotion
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/animatemotion/index.md
* Last commit: https://github.com/mdn/content/commit/b64f587034fbb610fe12ad819b0384f4f4ce1d4f
* Document last modified: 2024-08-15T13:05:18.000Z

</details>

**Comment by Josh-Cena** [comment]
Doesn't the linked page already say that?

> The SVG fill attribute can be used to define the final animation state with the following SVG elements:

Our SVG attribute docs are not namespaced by elements.

**Comment by anechunaev** [comment]
That's correct, thank you. I'm sorry, I just saw at the top of the page description of the graphical attribute and assumed that there is no info about animation on this page. That is a little bit confusing, but ok. I guess I can close the issue.
