### ISSUE TITLE
The RegExp.prototype.dotAll documentation has the potential to be misinterpreted with regard to matching astral characters

### ISSUE THREAD

**Issue by nordzilla** [mdn/content#35777]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll#description

### What information was incorrect, unhelpful, or incomplete?

The following phrase is misleading:

> This effectively means the dot will match any character on the Unicode Basic Multilingual Plane (BMP). To allow it to match astral characters, the u (unicode) flag should be used. Using both flags in conjunction allows the dot to match any Unicode character, without exceptions.

### What did you expect to see?

The reason I ended up on the [`RegExp.prototype.dotAll`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll)  page is because I had a portion of a regex that utilized `.*`, which stopped at a newline character when I wanted it to match newlines.

I obviously don't have data on this, but I would imagine that this is a common reason for someone to end up on this page. 

The aforementioned paragraph is quite misleading in this context:
> This effectively means the dot will match any character on the Unicode Basic Multilingual Plane (BMP). To allow it to match astral characters, the u (unicode) flag should be used. Using both flags in conjunction allows the dot to match any Unicode character, without exceptions.

If the reader's brain is already primed with the problem of "my `.*` regex may stop at some characters. That's why I need the `dotAll` flag," then the way this paragraph reads makes it seem like a regex with `.*` will _also_ stop at the first astral character it encounters unless the unicode flag is enabled. 

However, this is not true. While the `.` won't be able to parse the surrogate pairs of astral characters into a single character, when combined with `*` as `.*` it _will_ continue through all of the content. 

This means that `/.*/s` is effectively no different than `/.*/su` in terms of what it is able to match, as far as I can tell. However `/./s` and `/./su` would behave differently. 

When I saw that my `/.*/s` regex (without the unicode flag) was still matching sequences of astral characters, I thought the docs were out of date. 

### Do you have any supporting links, references, or citations?

The docs should be more clear about this case, that even though `.` on its own will not match astral characters as a single character, `.*` will still match astral characters without issue. 

### Do you have anything more you want to share?

**Different**

```javascript
"😄".match(/./)

Array [ "\ud83d" ]
```
```javascript
"😄".match(/./u)

Array [ "😄" ]
```

---

**Not Different**

```javascript
"😄".match(/.*/)

Array [ "😄" ]
```
```javascript
"😄".match(/.*/u)

Array [ "😄" ]
```

**Comment by Josh-Cena** [comment]
I can see how this may be confusing, so accepting a reword if you have suggestions.

**Comment by nordzilla** [comment]
Thanks for triaging this so fast!

I intentionally did not include any corrections here, because I wasn't sure that I would be the best person to explain it.

**Original**
> This effectively means the dot will match any character on the Unicode Basic Multilingual Plane (BMP). To allow it to match astral characters, the u (unicode) flag should be used. Using both flags in conjunction allows the dot to match any Unicode character, without exceptions.

**Improvement**

I think I would just add a note specific to this use case:

> This effectively means the dot will match any character on the Unicode Basic Multilingual Plane (BMP). To allow it to match astral characters, the u (unicode) flag should be used. Using both flags in conjunction allows the dot to match any Unicode character, without exceptions.
> 
> Note that while the dot will not match an astral character as a single entity without the u (unicode) flag, it will match the first code point of that character. This means that a pattern such as `.*` is still capable of matching astral characters as part of a larger context without the u (unicode) flag. 

I'm a little hesitant to say "it will match the first code point," as I'm not sure if "code point" is the best technical term to use here. 

---

 Please feel free to modify or reword any of the above as you see fit.

**Comment by Josh-Cena** [comment]
What about the following:

> This effectively means the dot will match any UTF-16 code units. Characters not in the Unicode Basic Multilingual Plane (BMP) are represented as [surrogate pairs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_points_and_grapheme_clusters), so without the `u` flag, they are matched by two `.` characters. However, a pattern such as `.*` is still capable of _consuming_ astral characters as part of a larger context without the `u` (unicode) flag. To allow `.` to match astral characters, the `u` (unicode) flag should be used. Using both flags in conjunction allows the dot to match any Unicode character in a more expectable manner.

The dot can match the second code unit of a surrogate pair too :)

**Comment by nordzilla** [comment]
> What about the following:
> 
> > This effectively means the dot will match any UTF-16 code unit. Characters not in the Unicode Basic Multilingual Plane (BMP) are represented as [surrogate pairs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_points_and_grapheme_clusters), so without the `u` flag, they are matched by two `.` characters instead of one. However, a pattern such as `.*` is still capable of _consuming_ astral characters as part of a larger context without the `u` (unicode) flag. To allow `.` to match astral characters, the `u` (unicode) flag should be used. Using both flags in conjunction allows the dot to match any Unicode character in a more expectable manner.
> 
> The dot can match the second code unit of a surrogate pair too :)

I think that's an improvement!

Thank you for correcting my misunderstanding of the usage of "code points."

---

Just one more thought:

I know it's not this page's job to explain the terms "BMP" and "astral," but I don't think it's immediately clear that "Characters not in the Unicode Basic Multilingual Plane (BMP)" (used first) are the same as "astral characters" (used second) to someone who has never encountered these terms. 

As such, this may be a further clarity improvement:

```diff
-Characters not in the Unicode Basic Multilingual Plane (BMP) are represented as...
+Characters not in the Unicode Basic Multilingual Plane (BMP), also known as astral characters, are represented as...
```

**Comment by Josh-Cena** [comment]
Looks good 👍 do you want to want to send a PR implementing this?

**Comment by nordzilla** [comment]
Will do!
