### ISSUE TITLE
Invalid function argument

### ISSUE THREAD

**Issue by abyssofbirds** [mdn/content#35790]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/at

### What specific section or headline is this issue about?

Examples => Return the last character of a string

### What information was incorrect, unhelpful, or incomplete?

The argument of the returnLast function is designated in the description as a string, and in the source code as arr, or Array.

### What did you expect to see?

function returnLast(str) {
  return str.at(-1);
}

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/at`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/at
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/at/index.md
* Last commit: https://github.com/mdn/content/commit/c2445ce1dc3a0170e2fbfdbee10e18a7455c2282
* Document last modified: 2023-09-12T02:17:31.000Z

</details>

**Comment by Josh-Cena** [comment]
Welcoming a PR to change the variable name :)
