### ISSUE TITLE
Django Tutorial Part 10: Testing a Django web application - 'sessions' database

### ISSUE THREAD

**Issue by giovanniferretti** [mdn/content#3579]
Hi, apparently for Django versions >= 2.2 a small addition is needed to get tests that involve `self.client.login()` to work - you need to a reference to the 'sessions' database to get the tests to run. Easy workaround is to declare `databases = '__all__'` when creating an instance of the TestCase base class (e.g. from the tutorial, when creating the `LoanedBookInstancesByUserListViewTest` class, and this gets done in the section where tests on viewsrestricted to logged-in users are demonstrated.

Failure to do so causes the following error:

`AssertionError: Database queries to 'sessions' are not allowed in this test. Add 'sessions' to catalog.tests.test_views.LoanedBookInstancesByUserListViewTest.databases to ensure proper test isolation and silence this failure.`

Affected docs:
- [Django Tutorial Part 10: Testing a Django web application](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing)
- https://github.com/mdn/django-locallibrary-tutorial/blob/master/catalog/tests/test_views.py#L56

**Comment by hamishwillee** [comment]
Hi @giovanniferretti 

Thanks for posting this. I cannot reproduce the problem - the example code for this tutorial does not have this fix or the problem running the tests: https://github.com/mdn/django-locallibrary-tutorial#quick-start

I am wondering if perhaps you're missing the sessions line here: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Sessions#enabling_sessions ?

Perhaps if you uploaded a version of your code to github we might compare the differences to the "official" example?  Please reopen if you are able to do so and we can discuss further.

**Comment by giovanniferretti** [comment]
I think I overlooked a difference between the code in the tutorial and how I implemented it - I used created a separate database to manage session-related entries. To be clear I'm using one database for the actual data (authors, books, etc...) and a separate database for session management. I think that could explain the error I was getting.

**Comment by hamishwillee** [comment]
Yes. So not a bug in the tutorial :-). Thanks for letting me know.

**Comment by giovanniferretti** [comment]
@hamishwillee definitely not a bug, sorry for crying wolf :)
