### ISSUE TITLE
Body part of HTTP Requests section refers to responses instead of requests

### ISSUE THREAD

**Issue by emw7** [mdn/content#35808]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages#body

### What information was incorrect, unhelpful, or incomplete?

The body section of the [HTTP Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages#http_requests) refers to responses while it concerns requests. In fact some parts seems to a copy and paste from the body section of the HTTP Responses chapter. 

### What did you expect to see?

The body section of the [HTTP Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages#http_requests) must refer to requests

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/messages`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/messages/index.md
* Last commit: https://github.com/mdn/content/commit/ae86913908651e6008079242691e06b5e01d1c78
* Document last modified: 2024-08-30T00:59:43.000Z

</details>

**Comment by bsmth** [comment]
Well spotted, thanks for reporting. I think this page deserves a refresh to fix this plus a few other pieces, such as diagrams.

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/35970
