### ISSUE TITLE
include a Set-Cookie section 

### ISSUE THREAD

**Issue by escolatecnica** [mdn/content#35814]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302

### What specific section or headline is this issue about?

optional content

### What information was incorrect, unhelpful, or incomplete?

There was no section about handling or setting cookies.  I arrived here from googling about 302, where in my http response there was a Set-Cookie with path=/, for example: 
< Content-Lenght: 0
< Location: https://adfs.xyz.com/oauth2/authorize?client_id=klm&redirect_uri=https%3A%2F%2Fintranet.xyz.com%2Fcallback.jsf
< SetCookie: JSESSIONID=AbCdEf123;path=/
<

### What did you expect to see?

An additional section after Content length about cookies

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/status/302`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/302/index.md
* Last commit: https://github.com/mdn/content/commit/6d81ba6606ce5473cadd085c37eaf4960e99a238
* Document last modified: 2024-09-03T15:53:46.000Z

</details>

**Comment by hamishwillee** [comment]
Thank, but I don't _think_ this is needed/the right information to add.

The server might set a cookie in any response: the fact that you happened to get one alongside the HTTP 302 has nothing to do with this particular response code, so doesn't belong in this documentation. Or to put it another way, we'd have to add information about cookies to every single status code, and that doesn't make sense.
