### ISSUE TITLE
调用不到setFloat16方法，原型中也没发现这个方法

### ISSUE THREAD

**Issue by WgcYage** [mdn/content#35823]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setFloat16

### What specific section or headline is this issue about?

.setFloat16()

### What information was incorrect, unhelpful, or incomplete?

调用不到setFloat16方法，原型中也没发现这个方法

### What did you expect to see?

修改这个页面，或者修改这个页面适用的版本？

### Do you have any supporting links, references, or citations?

Error: view.setFloat16 is not a function

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/dataview/setfloat16`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setFloat16
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/dataview/setfloat16/index.md
* Last commit: https://github.com/mdn/content/commit/fb442649a7e91a177a582a3e9c6e1a95a9e8dda5
* Document last modified: 2024-06-03T00:22:11.000Z

</details>

**Comment by Josh-Cena** [comment]
Check out https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setFloat16#browser_compatibility please
