### ISSUE TITLE
wrong example in Intl.ListFormat.formatToParts(list)

### ISSUE THREAD

**Issue by mdissel** [mdn/content#35833]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat#using_formattoparts

### What specific section or headline is this issue about?

wrong example

### What information was incorrect, unhelpful, or incomplete?

Example is wrong

{ "type": "literal", "value": ", and " },

should be (without the komma)

{ "type": "literal", "value": " and " },

```
const list = ["Motorcycle", "Bus", "Car"];
console.log(
  new Intl.ListFormat("en-GB", {
    style: "long",
    type: "conjunction",
  }).formatToParts(list),
);

// [ { "type": "element", "value": "Motorcycle" },
//   { "type": "literal", "value": ", " },
//   { "type": "element", "value": "Bus" },
//   { "type": "literal", "value": ", and " },
//   { "type": "element", "value": "Car" } ];`
```

### What did you expect to see?

{ "type": "literal", "value": " and " },

### Do you have any supporting links, references, or citations?

https://playcode.io/2003110

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/listformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/listformat/index.md
* Last commit: https://github.com/mdn/content/commit/4436acdeb5087c7fc5afc58fc8b475e30481c801
* Document last modified: 2024-07-24T20:49:37.000Z

</details>

**Comment by Josh-Cena** [comment]
Do you want to send a PR to fix this?
