### ISSUE TITLE
MDN incorrectly claims the spec allows `datalist` on `type=password`

### ISSUE THREAD

**Issue by zcorpan** [mdn/content#35837]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

### What information was incorrect, unhelpful, or incomplete?

> The specification allows linking `<datalist>` with a [password](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password) type

This is incorrect, the spec does not allow that.

### What did you expect to see?

The `list` attribute only applies for certain input types (include a list of all types where it applies and doesn't apply).

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/input.html#the-input-element%3Aconcept-input-apply (the row for `list`)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/datalist`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/datalist/index.md
* Last commit: https://github.com/mdn/content/commit/b7955e77cd4293adf45ef23686df50b0305f02ad
* Document last modified: 2024-07-25T21:13:49.000Z

</details>

**Comment by Josh-Cena** [comment]
The PR was https://github.com/mdn/content/pull/14834, which actually quotes the same table😅 We should just remove this example.
