### ISSUE TITLE
Add missing info about scrollbar-width intended use case

### ISSUE THREAD

**Issue by skyfighteer** [mdn/content#35835]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width

### What information was incorrect, unhelpful, or incomplete?

include this information from the spec: 

"The primary purpose of this property is not to allow authors to chose [sic] a particular scrollbar aesthetic for their pages, but to let them indicate for certain small or cramped elements of their pages that a smaller scrollbar would be desirable."

### What did you expect to see?

Information about the purpose, as one might think this property is a way to make the scrollbar thinner to make it look more modern or similar.

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/css-scrollbars-1/#:~:text=The%20primary%20purpose%20of%20this%20property%20is%20not%20to%20allow%20authors%20to%20chose%20a%20particular%20scrollbar%20aesthetic%20for%20their%20pages%2C%20but%20to%20let%20them%20indicate%20for%20certain%20small%20or%20cramped%20elements%20of%20their%20pages%20that%20a%20smaller%20scrollbar%20would%20be%20desirable.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/scrollbar-width`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/scrollbar-width/index.md
* Last commit: https://github.com/mdn/content/commit/fc1cc5684c98d19816d5cc81702d70f2a0debbad
* Document last modified: 2024-07-26T14:35:43.000Z

</details>

**Comment by muchafm** [comment]
Hi @skyfighteer and @Josh-Cena, I made a suggestion, and I'd appreciate any feedback on it when you have the time :slightly_smiling_face: I hope it fixes this issue
