### ISSUE TITLE
`capture` attribute is not in the spec

### ISSUE THREAD

**Issue by estelle** [mdn/content#35842]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

### What specific section or headline is this issue about?

attributes

### What information was incorrect, unhelpful, or incomplete?

the capture attribute is not listed in the specification

### What did you expect to see?

the documentation noting that the attribute listed in not in the HTML spec 
(actually, i expected to see capture in the spec, since it is supported)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/file`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/file/index.md
* Last commit: https://github.com/mdn/content/commit/b7955e77cd4293adf45ef23686df50b0305f02ad
* Document last modified: 2024-07-25T21:13:49.000Z

</details>

**Comment by Josh-Cena** [comment]
@estelle `capture` is defined by the HTML media capture spec, just like `attributionsrc` is from the attribution reporting spec. I don't know if it's ever intended to be merged into HTML, but it's definitely not non-standard if you think so. https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture tells you more about it.
