### ISSUE TITLE
Clipboard API example iframe - permission policy error

### ISSUE THREAD

**Issue by RyanFarrah67** [mdn/content#35862]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read#examples

### What information was incorrect, unhelpful, or incomplete?

The examples set in the Clipboard API don't work, when copying an image as indicated in the doc to paste it, nothing happens, only errors are thrown.

These demos are presented through an Iframe which causes permission policy issues.

### What did you expect to see?

The examples are to work correctly when copying and pasting the image and no errors are to be thrown.

## OS

Linux Ubuntu 22.04

### Google Chrome 

`127.0.6533.72 `

The error appears in the `DevTools` console and the iframe.

![Capture d’écran du 2024-09-12 22-40-41](https://github.com/user-attachments/assets/feb18d00-dc2a-40bb-8be4-277f6decee49)

### Firefox 

`130.0`

The error appears directly in the Iframe itself `Error: Clipboard read operation is not allowed.`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/clipboard/read`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/clipboard/read/index.md
* Last commit: https://github.com/mdn/content/commit/c7edf2734fccb185c5e93ee114ea3d5edc0177b5
* Document last modified: 2024-07-26T02:57:09.000Z

</details>

**Comment by hamishwillee** [comment]
Are you sure? This is what I see on Firefox

![image](https://github.com/user-attachments/assets/c04d30be-a810-4df0-9ff0-edbeed34096d)

Permission-Policies are supposed to first be set by the server and then that subset can be granted if also set on the frame. Firefox doesn't care about the server so we are able to set the permissions just on the frame.

**Comment by RyanFarrah67** [comment]
This is what I get : 

![image](https://github.com/user-attachments/assets/39bb9575-d0b7-4eba-b92d-522a9387f739)

Strangely, the first left click on the second box does nothing, I need to click a second time for the error to appear.

**Comment by hamishwillee** [comment]
Can you please try pressing Play and seeing what happens if you run it using the playground?

**Comment by RyanFarrah67** [comment]
![image](https://github.com/user-attachments/assets/e5f4f0c3-d2fd-4c35-b8da-0e21ab14e632)

**Comment by hamishwillee** [comment]
Thanks @OnkarRuikar !
