### ISSUE TITLE
FF131 for developers links an incorrect bugzilla

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [mdn/content#35869]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/131#apis

### What specific section or headline is this issue about?

Removals > APIs

### What information was incorrect, unhelpful, or incomplete?

see https://github.com/mdn/content/pull/35804

On the releases 131 page, the bugzilla linked for `altitudeAngle` and `azimuthAngle` is [Firefox bug 1909673](https://bugzilla.mozilla.org/show_bug.cgi?id=1909673) when it should be [1656377](https://bugzilla.mozilla.org/show_bug.cgi?id=1656377)

### What did you expect to see?

[1656377](https://bugzilla.mozilla.org/show_bug.cgi?id=1656377)

### Do you have any supporting links, references, or citations?

see https://github.com/mdn/content/pull/35804

**Comment by ramyaparimi** [comment]
Hello! Can I be assigned to this issue?

**Comment by ragul1697** [comment]
You can directly work on this issue and make a PR.
