### ISSUE TITLE
Issue with "CSS reference": (short summary here please)

### ISSUE THREAD

**Issue by hosseinse1919** [mdn/content#3588]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

#### What information was incorrect, unhelpful, or incomplete?
in side you forgot to add border in properties 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/reference/index.html
* Last commit: https://github.com/mdn/content/commit/7fcf9ca9a833f9061137cb0de847a71c4ed2277f
* Document last modified: 2021-03-17T13:56:51.000Z

</details>

**Comment by hosseinse1919** [comment]
![image](https://user-images.githubusercontent.com/39802485/112743459-be9c6700-8fac-11eb-9097-40b08ed3208d.png)

**Comment by hosseinse1919** [comment]
also "gap"

**Comment by hosseinse1919** [comment]
"fill"

**Comment by rachelandrew** [comment]
I can see `border` and `gap` in the list, and `fill` is an SVG attribute https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill

`border` is the first `border-*` property, and `gap` the second item under G.

**Comment by hosseinse1919** [comment]
yep  here it is but it is not in list of properties in side 

![image](https://user-images.githubusercontent.com/39802485/112753331-6c7b3600-8fec-11eb-8228-5e81bddd5d5b.png)

**Comment by hosseinse1919** [comment]
yep i see gap too it is grid gap but now browsers (i checked chrome) support   it  for display : flex too .

**Comment by rachelandrew** [comment]
It's just the gap property as supported everywhere. Look down the page for gap and you will see that flex support is detailed.

**Comment by rachelandrew** [comment]
> yep here it is but it is not in list of properties in side

I don't understand I'm afraid. The border property is listed.

**Comment by hosseinse1919** [comment]
![image](https://user-images.githubusercontent.com/39802485/112758220-5c6e5100-9002-11eb-9a6d-013cacfd21cc.png)

**Comment by hosseinse1919** [comment]
border is not exist in this list

**Comment by hosseinse1919** [comment]
sorry  my first language is not English so my text may be very bad to read .. lol
