### ISSUE TITLE
Reflect.construct(): newTarget description incorrectly refers to the prototype of the constructor

### ISSUE THREAD

**Issue by ajvincent** [mdn/content#35895]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/construct#newtarget

### What specific section or headline is this issue about?

Parameters: newTarget

### What information was incorrect, unhelpful, or incomplete?

"which usually specifies the prototype of the returned object." - this is incorrect.

### What did you expect to see?

Something along the lines of "the function you called `new` with".  

### Do you have any supporting links, references, or citations?

- [new.target on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target)
- [test-262 tests for Reflect.construct() using functions](https://github.com/tc39/test262/blob/main/test/built-ins/Reflect/construct/return-with-newtarget-argument.js)
- [a test I wrote for Reflect.construct() using classes and proxies](https://github.com/ajvincent/es-membrane/blob/8e665c75ebafd655439996fb1ff2ab5efc78a674/_00_ecma_references/spec/constructTrap.ts#L82)

**Comment by Josh-Cena** [comment]
So I think "the value of `new.target`" sufficiently captures all the guaranteed semantics about this parameter, and anything else after it is just us trying to be helpful and talking about what happens in the general case. Normally object creation uses `new.target.prototype` as the prototype so this is certainly not wrong, but I would not be opposed to changing it to your suggestion.

**Comment by ajvincent** [comment]
FYI, I had to rewrite my construct-trap test for more clarity as to how it works.

**Comment by Josh-Cena** [comment]
Feel free to send a PR btw and we can discuss the wording, but I think your suggestion looks good.
