### ISSUE TITLE
Page content - HTML does not work, needs updating to match github index.html 

### ISSUE THREAD

**Issue by ChrisHe** [mdn/content#35907]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/CycleTracker/JavaScript_functionality

### What specific section or headline is this issue about?

The HTML as given on the page does not work, 

### What information was incorrect, unhelpful, or incomplete?

the html given on the page is incorrect. Specifically fails at this line because previous ``const pastPeriodContain `` line is missing from top of file. There are also some othr minor errors
``pastPeriodContainer.textcontent = ""; ``
FIX: update page html section to match the github page, which does work!

### What did you expect to see?

HTML sections should match the github index.html page

### Do you have any supporting links, references, or citations?

No

### Do you have anything more you want to share?

No

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/progressive_web_apps/tutorials/cycletracker/javascript_functionality`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/CycleTracker/JavaScript_functionality
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/tutorials/cycletracker/javascript_functionality/index.md
* Last commit: https://github.com/mdn/content/commit/e03b13c7e157ec7b7bb02a6c7c4854b862195905
* Document last modified: 2024-07-30T04:48:57.000Z

</details>

**Comment by OnkarRuikar** [comment]
@ChrisHe What section on the page are you referring to? In the [Render data to screen](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/CycleTracker/JavaScript_functionality#render_data_to_screen) section the tutorial does ask learner to add `const pastPeriodContainer = document.getElementById("past-periods");`.

**Comment by ChrisHe** [comment]
My apologies, you are right, I had used the code at Form Submission section, missed the added const later in the article.
The change of textContent to innerHTML (used on github page) will not stop it working, so does not matter!
Sorry for wasting your time!
