### ISSUE TITLE
Use <p> instead of <ul> for form sections

### ISSUE THREAD

**Issue by Boodac** [mdn/content#35917]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Your_first_form

### What specific section or headline is this issue about?

The `<label>`, `<input>`, and `<textarea>` elements

### What information was incorrect, unhelpful, or incomplete?

The HTML snippet for using the first form doesn't make use of modern HTML form tags.

### What did you expect to see?

Instead of organizing the form as an unordered list, I expected to see some use of things like fieldset, legend, optgroup, et cetera.

Previous education has led me to understand that forms are not unordered lists, and there are semantic/accessibility issues with the current tutorial.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/your_first_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Your_first_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/your_first_form/index.md
* Last commit: https://github.com/mdn/content/commit/b76266228bd0900aa1256902c7858971156a58c9
* Document last modified: 2024-07-25T19:07:12.000Z

</details>

**Comment by Josh-Cena** [comment]
@estelle what say you?

**Comment by estelle** [comment]
We can change the list to four paragraphs, but we shouldn't add additional features to this page. Those are covered in later tutorials in the series.
