### ISSUE TITLE
MDN correction suggestion

### ISSUE THREAD

**Issue by madeli64** [mdn/content#35919]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML

### What specific section or headline is this issue about?

Annotating images with figures and figure captions

### What information was incorrect, unhelpful, or incomplete?

 I read this article in MDN about Images in HTML :
"Therefore, captions and alt text shouldn't just say the same thing, because **they both appear when the image is gone**.". I think there is an error in the phrase I quoted. The &lt;figcaption&gt; does not like _alt_ in &lt;img&gt; tag!

### What did you expect to see?

I know it's a fact when the same text be in _alt_ and &lt;figcaption&gt; after failing to load the image alt will appear and it's redundant but I mean it's could be better to said in better way to stop mis-understanding peoples newly begin to learn!

### Do you have anything more you want to share?

![image](https://github.com/user-attachments/assets/fad30f3f-5dd5-4e8b-b950-e910cc0c2200)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/images_in_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.md
* Last commit: https://github.com/mdn/content/commit/d71da812ee94c20658cb1916a123a42254ea545c
* Document last modified: 2024-08-07T22:02:28.000Z

</details>

**Comment by Josh-Cena** [comment]
This is correct. It says exactly what we mean: whenever the `alt` text gets used at all, its information should not duplicate the caption. Either you never use the `alt` and only the caption is shown, or the `alt` text has the same information as the caption. In both cases the `alt` is useless and you may be even better off just removing it.

**Comment by madeli64** [comment]
Do you think this phrase "they both appear when the image is gone." is correct?
My interpretation of this sentence is that both items appear when the image has difficulty to upload.

**Comment by Josh-Cena** [comment]
Yes. If the image doesn't show, then both the alt and the caption are shown.
