### ISSUE TITLE
Wrong counting 

### ISSUE THREAD

**Issue by MustafaElghisha** [mdn/content#35920]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Semantics

### What specific section or headline is this issue about?

Semantic elements

### What information was incorrect, unhelpful, or incomplete?

*These are some of the roughly 100 semantic [elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) available:*
And then you listed only 14 elements which can be a bit confusing for the readers 

### What did you expect to see?

These are some of the roughly 10 semantic [elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) available:*

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/semantics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Semantics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/semantics/index.md
* Last commit: https://github.com/mdn/content/commit/50e5e8a9b8a6b7d0dd9877610c9639d8b90f329f
* Document last modified: 2024-07-08T11:56:20.000Z

</details>

**Comment by Josh-Cena** [comment]
There are about 100 semantic elements. This list is incomplete, hence "SOME of the elements".

**Comment by MustafaElghisha** [comment]
Thank you for the clarification.
