### ISSUE TITLE
Content bug: ''compatibility table'' link  is not invalid

### ISSUE THREAD

**Issue by kazuhitonakayama** [mdn/content#3593]
## What page(s) did you find the problem on?
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText#browser____compatibility
<img width="1421" alt="Screen Shot 2021-03-28 at 19 47 39" src="https://user-images.githubusercontent.com/50609459/112749684-e3b9c580-8ffe-11eb-8e68-97ba91afb96d.png">

## What is the problem?
''compatibility table'' link is not invalid.

## What did you expect to see?
When that link is clicked, the page should transition to a table like the following.
![image](https://user-images.githubusercontent.com/50609459/112749711-27143400-8fff-11eb-8b2c-9f4951736097.png)

## Did you test this? If so, how?
No , I don't test.

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. That entire note is no longer necessary, so the best thing to do is to drop it completely — and I’ve raised https://github.com/mdn/content/pull/3596 to do that.

**Comment by kazuhitonakayama** [comment]
@sideshowbarker 
Thank you for your comment and Pull Request🎉
