### ISSUE TITLE
Large bounds are not required to cause rounding

### ISSUE THREAD

**Issue by per-reimers-profcon** [mdn/content#35933]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

"If extremely large bounds are chosen (2**53 or higher), it's possible in extremely rare cases to reach the usually-excluded upper bound."

### What did you expect to see?

"It's possible in extremely rare cases to reach the usually-excluded upper bound, especially if large bounds are chosen."

### Do you have anything more you want to share?

```
const almost_1 = 0.9999999999999999;
Math.random = () => almost_1;

// Example from page, supposedly always returns numbers less than max
function getRandomArbitrary(min, max) {
  return Math.random() * (max - min) + min;
}

console.log(getRandomArbitrary(1, 3)); // Logs 3
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/math/random`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/random/index.md
* Last commit: https://github.com/mdn/content/commit/8421c0cd94fa5aa237c833ac6d24885edbc7d721
* Document last modified: 2024-07-25T21:32:46.000Z

</details>

**Comment by per-reimers-profcon** [comment]
> The large bounds have nothing to do with it. So the statement could be, "It's possible in extremely rare cases(when Math.random() returns `0.9999999999999999`) the returned random number to reach the usually excluded upper bound."

Well, not quite. As the bounds get larger, the more common it becomes for a rounding error to cause the upper bound to be reached. I'd guess the probability doubles as the bounds doubles.

> Or the function could be written as:
> 
> ```js
> const almost_1 = 0.9999999999999999;
> Math.random = () => almost_1;
> 
> // Example from page, supposedly always returns numbers less than max
> function getRandomArbitrary(min, max) {
>   return (Math.random() - 0.0000000000000001) * (max - min) + min;
> }
> 
> console.log(getRandomArbitrary(1, 3)); // Logs 2.9999999999999996
> ```

No, that won't work if Math.random returns 0:

```js
Math.random = () => 0;

// Adjusted example, I disagree with
function getRandomArbitrary(min, max) {
  return (Math.random() - 0.0000000000000001) * (max - min) + min;
}

console.log(getRandomArbitrary(1, 3)); // Logs 0.9999999999999998
```

This might be better:

```js
Math.random = () => 0.9999999999999999;

// Adjusted example, with special check
function getRandomArbitrary(min, max) {
  const result = Math.random() * (max - min) + min;
  if (result >= max) return min; // Handle floating point rounding error
  return result;
}

console.log(getRandomArbitrary(1, 3)); // Logs 1 now.
```

**Comment by OnkarRuikar** [comment]
> As the bounds get larger, the more common it becomes for a rounding error to cause the upper bound to be reached. 

You are right. My point is that the possibility exists across the range, not just with larger bounds.

>  `if (result >= max) return min; // Handle floating point rounding error`

Returning `min` is the best tradeoff :slightly_smiling_face:.

Fixing the code blocks would be better than explaining the rounding error cases.

**Comment by per-reimers-profcon** [comment]
> > As the bounds get larger, the more common it becomes for a rounding error to cause the upper bound to be reached.
> 
> You are right. My point is that the possibility exists across the range, not just with larger bounds.

That's true. We probably shouldn't be too specific since I don't think we really know.
 
> > `if (result >= max) return min; // Handle floating point rounding error`
> 
> Returning `min` is the best tradeoff 🙂. But the probability of returning `min` would increase with bigger bounds.

That might be true.

> How about the following?
> 
> ```js
> function getRandomArbitrary(min, max) {
>   let result = max;
>   while(result >= max) {
>      result = Math.random() * (max - min) + min;
>   }
>   return result;
> }
> ```

Good in theory, but it would be nicer if it would handle min >= max gracefully. If a beginner tries the wrong way around they would get an infinite loop.

> Fixing the code blocks would be better than explaining the rounding error cases.

Hmm, I disagree. I think accurate documentation is more important. Example code is nice and useful, but not required.
