### ISSUE TITLE
Contradictory Information

### ISSUE THREAD

**Issue by fweth** [mdn/content#35939]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul

### What specific section or headline is this issue about?

Nesting a list

### What information was incorrect, unhelpful, or incomplete?

It says here at [technical summary](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul#technical_summary)

> Permitted content: Zero or more `<li>`, `<script>` and `<template>` elements.

but above at [nested lists](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul#nesting_a_list) they do exactly the opposite, putting `<ul>`s inside an `<ul>` without wrapping it in `<li>`s.

### What did you expect to see?

Technical summary seems correct. Weirdly, if you adhere to the spec, the default styling is off. Maybe that's a problem of the rendering engine?

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/ul`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/ul/index.md
* Last commit: https://github.com/mdn/content/commit/9c09b183a5ce844a75c2f22e909d03f71ca329fc
* Document last modified: 2024-07-26T02:20:41.000Z

</details>

**Comment by fweth** [comment]
Sorry, my bad, I misread!

**Comment by Josh-Cena** [comment]
All the `ul`s in the nested lists example are wrapped in `li`, no?
