### ISSUE TITLE
Dataset property is not read-only

### ISSUE THREAD

**Issue by tylernygrendc** [mdn/content#35959]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset

### What specific section or headline is this issue about?

Introduction

### What information was incorrect, unhelpful, or incomplete?

The dataset property is not read-only. However, the first sentence in this article states "The dataset read-only property of the HTMLElement interface provides read/write access to custom data attributes (data-*) on elements."

### What did you expect to see?

The dataset property of the HTMLElement interface provides read/write access to custom data attributes (data-*) on elements.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/dataset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/dataset/index.md
* Last commit: https://github.com/mdn/content/commit/e9e2ec643ac69c132f31427a0b586ab2cf83ed58
* Document last modified: 2024-07-26T02:56:30.000Z

</details>

**Comment by Josh-Cena** [comment]
When we say "read-only" property, it means the _property_ is read-only: that is, you can't reassign it like `e.dataset = ...`. It doesn't imply that the object held as the property's value is read-only.

**Comment by tylernygrendc** [comment]
Thank you for teaching me something!
