### ISSUE TITLE
Reference to Photon

### ISSUE THREAD

**Issue by LutzHarder** [mdn/content#35963]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/What_will_your_website_look_like

### What specific section or headline is this issue about?

First things first - Note

### What information was incorrect, unhelpful, or incomplete?

You are still referencing to the Photon Design System. By following the link, I get to Acorn, and learn that Photon has been replaced.

### What did you expect to see?

A reference to Acorn.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/what_will_your_website_look_like`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/What_will_your_website_look_like
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
* Last commit: https://github.com/mdn/content/commit/865acb22b74a49927b98267566369d4677414f53
* Document last modified: 2024-07-25T20:50:24.000Z

</details>

**Comment by Josh-Cena** [comment]
For posterity, this is not discovered by my redirection checker because the photon link redirects to a login page and I exclude any login redirect
