### ISSUE TITLE
Issue with "<input type="tel">": (Accepting alphabets which are infinite )

### ISSUE THREAD

**Issue by anjali1102** [mdn/content#3599]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel

#### What information was incorrect, unhelpful, or incomplete?

![-input-type-tel-HTML-HyperText-Markup-Language-MDN](https://user-images.githubusercontent.com/56559378/112752407-7acb5100-8ff0-11eb-834d-fa3c7ece2376.png)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/tel`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/tel/index.html
* Last commit: https://github.com/mdn/content/commit/d39ab1b220958bea9f389d417f40692c4dcd8881
* Document last modified: 2021-03-18T09:32:12.000Z

</details>

**Comment by anjali1102** [comment]
hey @chrisdavidmills Can I take up the issue?

**Comment by chrisdavidmills** [comment]
I don't think there is anything to do here. You can enter any character you want into the form, but it will only show strings to be valid if they follow the pattern, e.g. 333-333-3333. Try it and see.

**Comment by rachelandrew** [comment]
I agree there isn't anything to do here, please re-open if you believe that there is.
