### ISSUE TITLE
strongly recommend a new automation system - vite.js

### ISSUE THREAD

**Issue by Cecil0o0** [mdn/content#35991]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Installing_basic_software

### What specific section or headline is this issue about?

What tools do the professionals use?

### What information was incorrect, unhelpful, or incomplete?

unordered item **an automation system** is correct and very helpful for me, but I found it lacks some automation systems, this infomation seems to be incomplete because of outdated.

### What did you expect to see?

There are more project for automation, some of those are popular, widely used, there is a automation tool called [vite](https://vitejs.dev).

1. I expected to see [vite](https://vitejs.dev) in this ** an automation system** section.
2. if possible, sort it into first place, because I think it's a fast, easy-to-use, rapidly growing up, modern automation system for web development.

### Do you have any supporting links, references, or citations?

Here some links as context:
official website: https://vitejs.dev
official GitHub repository: https://github.com/vitejs/vite
NPM registry: https://www.npmjs.com/package/vite

### Do you have anything more you want to share?

I want to share about it's rapidly growing up, at the moment I create this issue, `vite` has reached 59% percent of `webpack`, measured with weekly download, as displayed in webpage below:

https://npmtrends.com/grunt-vs-gulp-vs-vite-vs-webpack.

**Comment by Josh-Cena** [comment]
The last four bullets need to be gone.

- FTP is no longer relevant for any sufficiently modern server. Either use git or use SSH.
- "Automation system" seems very outdated and we'd rather call Webpack/Vite bundlers. Grunt/Gulp are general-purpose automation tools but they are very legacy.
- The "library & frameworks" bullet basically says nothing about what we need to install.

Instead, these points should be replaced with one paragraph that says "For more information about other project-specific tools, especially for client-side web development, see our [Understanding client-side web development tools](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools) guide."
