### ISSUE TITLE
Wrong syntax of column-width, not actually implemented

### ISSUE THREAD

**Issue by Eccenux** [mdn/content#36001]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/column-width

### What specific section or headline is this issue about?

Formal syntax

### What information was incorrect, unhelpful, or incomplete?

```
column-width = 
  auto                                |
  <length [0,∞]>                      |
  min-content                         |
  max-content                         |
  fit-content( <length-percentage> )  

<length-percentage> = 
  <length>      |
  <percentage>  
```

### What did you expect to see?

```
column-width = 
  auto                                |
  <length [0,∞]>                      |
```

### Do you have any supporting links, references, or citations?

Here is the current syntax:
https://www.w3.org/TR/css-multicol-1/#propdef-column-width

This is an autocomplete in Chrome (similar in Firefox):
![screen from Chrome devtools](https://github.com/user-attachments/assets/177670bb-9d86-4b90-9ba0-534aa8ca41bc)

As you can see, `auto | <length [0,∞]>` is what's actually implemented in browsers.

Note that additions to `column-width` were already considered _at-risk_ in Level 3: https://www.w3.org/TR/css-sizing-3/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/column-width`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/column-width
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/column-width/index.md
* Last commit: https://github.com/mdn/content/commit/9231a7046973685f4600e1891fa644ecce41ef3b
* Document last modified: 2024-07-26T14:44:17.000Z

</details>

**Comment by Josh-Cena** [comment]
We don't use the published w3 specs as source, because those are arbitrarily cut versions. Check the latest syntax at https://drafts.csswg.org/css-sizing/#column-sizing.

**Comment by Eccenux** [comment]
Well in that case the compat tabel is wrong (browsers clearly don't implement additional sizing):
https://github.com/mdn/browser-compat-data/issues/24493

**Comment by Eccenux** [comment]
Sorry to bother you, but I also noticed that the compatibility table is wrong, assuming this is correct: `min-content, max-content, fit-content( <length-percentage> )`.

These values are not included in the [Syntax section](https://developer.mozilla.org/en-US/docs/Web/CSS/column-width#syntax), either in the syntax examples or in the value descriptions.
