### ISSUE TITLE
Issue with "HTML: HyperText Markup Language": Broken Link. Status 404 (Page not found).

### ISSUE THREAD

**Issue by pheianox** [mdn/content#3602]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML

#### What information was incorrect, unhelpful, or incomplete?
Broken Link directing to a page with a status of 404 (Page not  found)

<hr>

#### Specific section or headline?

`NOTE: The link is covered inside the details HTML tag. So it's not that easy to find it.`

Sidebar > Documentation > Contribute > "HTML doc status"

<hr>

Link name: **HTML doc status**

Link URL: **https://developer.mozilla.org/en-US/docs/MDN/Doc_status/HTML**

<hr>

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/index.html
* Last commit: https://github.com/mdn/content/commit/2d48835e97e7d226431f2be1a74558117fb44d0e
* Document last modified: 2021-02-03T18:43:39.000Z

</details>

**Comment by hamishwillee** [comment]
@chrisdavidmills This link problem reported here (https://developer.mozilla.org/en-US/docs/MDN/Doc_status/HTML) appears to be pulled in from `{{HTMLSidebar}}`. I'd have guessed a defunct mechanism for tracking "to do" work on HTML. 

Another nearby link that is broken shown below is supposed to be a link to a page of tagged content, but also gives 404. 
![image](https://user-images.githubusercontent.com/5368500/112771751-20c29e00-9079-11eb-89ee-a83ae34e6bfe.png)

Delete both links from the macro?

**Comment by skyline1983skyliny** [comment]
?????????????

**Comment by pheianox** [comment]
Yes, those are the two broken links. Needs to be fixed. I could fix that, but I didn't find the {{HTMLSidebar}}.

**Comment by hamishwillee** [comment]
Thanks @pheianox , I can find the sidebar. But we need to find the "right" way to fix this. The first one shown above already fixed.

**Comment by sideshowbarker** [comment]
I went ahead and opened https://github.com/mdn/yari/pull/3367 with a change that drops all the “Doc status” links.
