### ISSUE TITLE
Doesn't `background-position-x` not support `Side-relative values`?

### ISSUE THREAD

**Issue by xiaolinggnb** [mdn/content#36036]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x

### What specific section or headline is this issue about?

CSS Doc

### What information was incorrect, unhelpful, or incomplete?

Below info in https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x#syntax
```CSS
/* Side-relative values */
background-position-x: right 3px;
background-position-x: left 25%;
```

### What did you expect to see?

I think this part should be removed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/background-position-x`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/background-position-x/index.md
* Last commit: https://github.com/mdn/content/commit/b90786a572bd01af9063ac5e515850c6bb5ddb89
* Document last modified: 2023-12-08T09:31:32.000Z

</details>

**Comment by Josh-Cena** [comment]
Check https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x#browser_compatibility please.

**Comment by xiaolinggnb** [comment]
Got it, Thank you for your reminder.

**Comment by xiaolinggnb** [comment]
> Check https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x#browser_compatibility please.

Got it, Thank you for your reminder.
