### ISSUE TITLE
AbortController.timeout max value

### ISSUE THREAD

**Issue by 3dyuval** [mdn/content#36044]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout_static

### What specific section or headline is this issue about?

Parameters / time

### What information was incorrect, unhelpful, or incomplete?

The max value in `ms` for AbortController.timeout is unknown.

### What did you expect to see?

For comparison, setTimeout() has [Maximum delay value](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#maximum_delay_value) explicitly specifing the max value is `2,147,483,647`ms

### Do you have any supporting links, references, or citations?

No,I would like to inquire

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/abortsignal/timeout_static`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout_static
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/abortsignal/timeout_static/index.md
* Last commit: https://github.com/mdn/content/commit/15f0b5552bc9c2ea1f32b0cd5ee840a7d43c887e
* Document last modified: 2024-05-07T14:57:03.000Z

</details>

**Comment by Josh-Cena** [comment]
Any value that does not cause it to throw a `TypeError` behaves as expected. We could clarify that it must be a valid non-negative [safe integer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger).

**Comment by BartoszKlonowski** [comment]
I will work on this!
@Josh-Cena please assign me if possible, so I can see it on my list.

**Comment by Josh-Cena** [comment]
Sure, if it helps you I'm happy to assign.
