### ISSUE TITLE
EmbedLiveSample simultaneously displays examples

### ISSUE THREAD

**Issue by bobort** [mdn/content#36049]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav

### What specific section or headline is this issue about?

Examples Results

### What information was incorrect, unhelpful, or incomplete?

When reviewing the results window, I expected to see the results of the previous block of code. Instead, it shows the results of the previous two blocks of code. I mistakenly thought that the nav element in the prose section was converting the prose into a list and rendering that before the prose was rendered. I would show two results windows--one under each code block. I would split the examples apart.

### What did you expect to see?

When reviewing the results window, I expected to see the results of the previous block of code.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/nav`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/nav/index.md
* Last commit: https://github.com/mdn/content/commit/9231a7046973685f4600e1891fa644ecce41ef3b
* Document last modified: 2024-07-26T14:44:17.000Z

</details>

**Comment by Josh-Cena** [comment]
Thanks for the report. Each `EmbedLiveSample` consumes all code blocks in its subsection, so we need to put the two examples under different h3 headings. If you (or someone else) wants to send a PR, you can check out https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples for guidelines.

**Comment by bobort** [comment]
I'm new to open contributions, and I attempted this pull request:
https://github.com/mdn/content/pull/36052
