### ISSUE TITLE
Issue with "CSS Animations tips and tricks": Why there are two nested requestAnimationFrame?

### ISSUE THREAD

**Issue by MenaiAla** [mdn/content#3605]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Tips

#### What information was incorrect, unhelpful, or incomplete?

In Javascript Snippet, I've noticed that there are two nested `requestAnimationFrame` but I don't understand the reason behind them.

#### Specific section or headline?

[Javascript Content](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Tips#javascript_content)

#### What did you expect to see?

Only one `requestAnimationFrame`.

#### Did you test this? If so, how?

```Javascript
const runButton= document.getElementById("runButton");

runButton.addEventListener("click", (event) => {
  document.querySelector("div").classList.remove("changing");
  window.requestAnimationFrame((event) => {
    document.querySelector("div").classList.add("changing");
  });
});
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_animations/tips`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Tips
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_animations/tips/index.html
* Last commit: https://github.com/mdn/content/commit/85a8e65d648b60fb244f2ca8c0fc519ea9b55626
* Document last modified: 2021-01-19T06:15:11.000Z

</details>

**Comment by Kaiido** [comment]
It's explained in the paragraph right below:

> 2. To be sure that the styles are recalculated, we use window.requestAnimationFrame(), specifying a callback. Our callback gets executed just before the next repaint of the document. The problem for us is that because it's before the repaint, the style recomputation hasn't actually happened yet! So...
> 3. Our callback cleverly calls requestAnimationFrame() a second time! 

Arguably that second callback could rather have been in a `setTimeout` since there is no real need for waiting a full frame again, or even they could have forced a reflow synchronously, but the content is fine and IMM well explained.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/3605#issuecomment-809135569
