### ISSUE TITLE
Incorrect description of function output for getFloatFrequencyData()

### ISSUE THREAD

**Issue by gabriel-bric-yud** [mdn/content#36071]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getFloatFrequencyData

### What specific section or headline is this issue about?

In the initial description

### What information was incorrect, unhelpful, or incomplete?

"Each array value is a sample, the magnitude of the signal at a particular time." 

### What did you expect to see?

This is incorrect, as each array value is not a sample but the amplitude of a specific frequency component of the audio signal at that moment as directed by the fftSize. This is stated correctly in the next line: "Each item in the array represents the decibel value for a specific frequency." 

### Do you have any supporting links, references, or citations?

This next line of the article states: "Each item in the array represents the decibel value for a specific frequency." So that is one of my sources.

### Do you have anything more you want to share?

Seems like it was copy and pasted sentence from getFloatTimeDomainData() article. It doesn't hold true for this function.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/analysernode/getfloatfrequencydata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getFloatFrequencyData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/analysernode/getfloatfrequencydata/index.md
* Last commit: https://github.com/mdn/content/commit/d26705ee1fb754fb4c5f6e4a03b7b008eb3b8687
* Document last modified: 2024-01-21T12:09:36.000Z

</details>

**Comment by Josh-Cena** [comment]
This was changed in https://github.com/mdn/content/pull/25878. Welcoming fixes.
