### ISSUE TITLE
Bad RegExp

### ISSUE THREAD

**Issue by srkleiman** [mdn/content#36083]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email

### What specific section or headline is this issue about?

Basic validation

### What information was incorrect, unhelpful, or incomplete?

The RE for email validation has an unescaped '/' at the 22nd character.

### What did you expect to see?

``/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/``

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input/email`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/email/index.md
* Last commit: https://github.com/mdn/content/commit/245715b48674c1729cb63417e4a27628e30ae28c
* Document last modified: 2024-08-03T13:26:37.000Z

</details>

**Comment by Josh-Cena** [comment]
The "22nd character" is inside a character class and slashes don't need to be escaped there.

**Comment by srkleiman** [comment]
Chrome dev console thought it terminated the RegExp.Sent from my iPhoneOn Sep 27, 2024, at 10:49 AM, Joshua Chen ***@***.***> wrote:﻿
The "22nd character" is inside a character class and slashes don't need to be escaped there.

**Comment by Josh-Cena** [comment]
<img width="648" alt="image" src="https://github.com/user-attachments/assets/cc772434-cc0f-45fe-b82a-07ecd34d73de">
