### ISSUE TITLE
justify-all unsupported

### ISSUE THREAD

**Issue by calebfoss** [mdn/content#36091]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-align

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/text-align#values

### What information was incorrect, unhelpful, or incomplete?

This section lists justify-all as a valid value for this property, but attempting to use it in the example editor displays an X. On Firefox, I see that this value is invalid. It is not listed in the browser compatibility section.

### What did you expect to see?

If justify-all is supported by some browsers, including that information would be very helpful. If not, it would be best to remove it.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/text-align`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/text-align/index.md
* Last commit: https://github.com/mdn/content/commit/eeabc0774ceb0b7447febce6f9743b903815b95b
* Document last modified: 2024-07-24T23:33:28.000Z

</details>

**Comment by Josh-Cena** [comment]
It is listed in the spec but none of the browsers implement it: https://wpt.fyi/results/?label=master&label=experimental&aligned&q=text-align-justifyall

I'm not sure what to do. My understanding is that BCD doesn't want to include features not implemented anywhere, and in principle the content should ignore it too, but the formal syntax is not controlled by us so it will be displayed there anyway, which may be even more confusing.

**Comment by calebfoss** [comment]
Thank you for the explanation! Am I understanding correctly that because it's in the spec, it must be documented in the values section but because it has no support, should not be documented in the browser compatibility section? Would it be possible to include a note in the description of the value? Or in the general description for the property if not?

**Comment by Josh-Cena** [comment]
The usual policy is that features not implemented anywhere would not get any mention on MDN, at least not masquerading as real references. However, the formal syntax block is pulled in from an external dataset w3c/webref, so it would be always displayed there, and our experience is that readers often get confused and say "why is this value in formal syntax but not documented anywhere". I'm not sure what we should do to be least confusing—my personal opinion is to add a row in the browser compat table with all "No", but I'm not sure if that fits BCD policies.

**Comment by hamishwillee** [comment]
The correct MDN fix here is to remove `text-align: justify-all;` entirely from this page as unimplemented. Yes this will remain in the formal syntax, and yes that is confusing. That is the policy though.

> "No", but I'm not sure if that fits BCD policies.

It doesn't fit with policy. 

This has come up a bunch of time. IMO we should auto-add a note with formal syntax noting that this may contain values that are not implemented anywhere. But I'm not in charge.

I guess another way would be for yari to post-process the BCD and auto-add "not supported" for things that are in formal syntax or IDL but not documented.
