### ISSUE TITLE
Issue with "What is CSS?": browser compatibility chart appears in wrong place

### ISSUE THREAD

**Issue by jeffreyclu** [mdn/content#3609]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS

#### What information was incorrect, unhelpful, or incomplete?
The browser compatibility chart for renders incorrectly on the page. The HTML structure has the [compat chart after the penultimate paragraph](https://github.com/mdn/content/blob/b3ab98cf8f26707fced69d99670670ce20ea4bbe/files/en-us/learn/css/first_steps/what_is_css/index.html#L114) but on the browser, it appears before any of the paragraphs.

#### Specific section or headline?
Section: Browser Support

#### What did you expect to see?
I expected to see the compat chart after the paragraph, "What follows is the compat data chart for the CSS font-family property."

#### Did you test this? If so, how?
Tested in the browser: Google Chrome Version 89.0.4389.90 (Official Build) (x86_64) on Mac OS X 11.2.3 (20D91).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/first_steps/what_is_css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/first_steps/what_is_css/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, it's a result of the macro moving the table up. Fixed in #3610

**Comment by jeffreyclu** [comment]
Nice 😀
