### ISSUE TITLE
speak content

### ISSUE THREAD

**Issue by eskuye11** [mdn/content#36106]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Issues

### What specific section or headline is this issue about?

window.speechSynthesis.speak(utterance);

### What information was incorrect, unhelpful, or incomplete?

I was working on quiz app, and this program have to read the content of the questions out-loud. 
the problem is, it can't read the blank line. ' ______ '  
it read that like  "underscore underscore underscore underscore underscore"

### What did you expect to see?

I want that read link 'blank'

I am using ( db.json ) to store my questions react as a front end.
how can I fix this . . .   please help me

Eskinder
eskinder@negash.net

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community/issues`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community/Issues
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/issues/index.md
* Last commit: https://github.com/mdn/content/commit/a966a8b4eade72a13de8a688c13f2d5056321f02
* Document last modified: 2024-09-27T10:24:11.000Z

</details>

**Comment by Josh-Cena** [comment]
This is a browser issue, not an issue with our content. Please ask it on a Q&A forum such as StackOverflow.

**Comment by eskuye11** [comment]
Thank you for your immediate response !

    On Sunday, September 29, 2024 at 03:32:14 PM EDT, Joshua Chen ***@***.***> wrote:  
 
 


This is a browser issue, not an issue with our content. Please ask it on a Q&A forum such as StackOverflow.
