### ISSUE TITLE
[HTTP] Pref off HTTP/2 push

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#36116]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- n/a Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features (disabled)
- n/a Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1915848

__Related issues and pull requests:__

- [x] Relnote: https://github.com/mdn/content/pull/36148
- [x] Content: https://github.com/mdn/content/pull/36149

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by bsmth** [comment]
There's nothing else outstanding on this now, so this can be closed as complete.
