### ISSUE TITLE
Learn: 'What is a URL?' Clarify Explanation of Anchors in URL Anatomy Section

### ISSUE THREAD

**Issue by Bhavani-Bolloju** [mdn/content#36111]
### Proposal

In the ["What is a URL?"](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL) section of the MDN documentation, where the anatomy of a URL is described, the explanation of the [Anchor](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL#anchor) could be made clearer.

Currently, the phrase "anchor to another part of the resource itself" could benefit from further clarification. It is important to distinguish between a path, which points to a resource on the server, and an anchor, which points to a location within a resource that has already been loaded in the browser.

**Why It Is Needed:**

The existing explanation might be difficult for some readers to fully grasp, particularly those who are new to web development. By making the distinction between a path and an anchor clearer, readers can better understand the exact purpose of the anchor in a URL.

**Proposed Revision:**

> "An anchor refers to a location within a resource loaded in a browser, acting as an identifier to locate a specific part of the resource, giving the browser the directions to show the content located at that identified part. If the anchor is part of an HTML document, the browser scrolls to the identifier. For videos or audio files, the browser skips to the specified timestamp. The part that follows the #, also known as fragment identifier, is never sent to the web server with the request."

This revised explanation is easier to understand and makes it clear the role of an anchor in the context of a URL to readers.

Also the fact that the fragment identifier is never to sent to the server as part of the URL makes it more sense to emphasize on "**An anchor refers to a location within a resource loaded in a browser**" this part of the explanation.

### Browser support

Not applicable. This proposal is for a documentation update and does not involve any changes to browser features or functionality.

### Tasks

- The proposed content needs to be updated in the relevant section of the MDN documentation.

### Dependencies

- No

### Additional information

The proposal is to improve the clarity of the "anchor" explanation in the "what is URL?" section of the MDN documentation, To simplify the understanding to the role of anchor.

### Are you willing to support this work?

Yes, I am willing to support this work. I can assist with any further revisions or clarifications that might be needed during the review process.

**Comment by hamishwillee** [comment]
Thanks. I'm closing this because I strongly disagree.

If you read the document there is no confusion - and this suggestions makes it harder to understand what is going on. The structure of the document is such that as you progress through the text the difference between an anchor and a path is already completely clear. 

Could it be improved? Perhaps. You could move the anchor section above the parameters. You could also change "#SomewhereInTheDocument is an anchor to another part of the resource itself." to "#SomewhereInTheDocument is an anchor to a location within the resource."
