### ISSUE TITLE
[JS] Implement Promise.try

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#36118]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1905364

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by chrisdavidmills** [comment]
BCD updated in https://github.com/mdn/browser-compat-data/pull/24608

**Comment by chrisdavidmills** [comment]
Content PR to add it to experimental features (currently behind a pref): https://github.com/mdn/content/pull/36166

**Comment by hamishwillee** [comment]
According to BCD discussion this is in nightly/behind pref.

Status:

- [ ] BCD https://github.com/mdn/browser-compat-data/pull/24608
- [ ] Docs
- [ ] Release note/experimental features
- [ ] dev-docs complete
