### ISSUE TITLE
[JS] Release JSON.parse with source

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#36113]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [ ] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1913085

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by chrisdavidmills** [comment]
Content: https://github.com/mdn/content/pull/36175

**Comment by Rumyra** [comment]
FYI this has been reverted - I can tidy up the release notes, but @hamishwillee would you be able to look at bcd?

**Comment by hamishwillee** [comment]
@Rumyra Done - reverted BCD in https://github.com/mdn/browser-compat-data/pull/24833

Note, this didn't have an experimental features record originally, but you might want to add one.

**Comment by Rumyra** [comment]
Thanks so much @hamishwillee - yes I'll tidy this up when I edit the notes

For more reference https://bugzilla.mozilla.org/show_bug.cgi?id=1925334

**Comment by bsmth** [comment]
There's a PR to move under "Experimental" here: 

- [ ] https://github.com/mdn/content/pull/36553

**Comment by Josh-Cena** [comment]
I think despite all chaos the docs work are all completed
