### ISSUE TITLE
Not sure "heuristics" is the right word here

### ISSUE THREAD

**Issue by BillNMA** [mdn/content#36135]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Turning_off_form_autocompletion

### What specific section or headline is this issue about?

Disabling autocompletion

### What information was incorrect, unhelpful, or incomplete?

heuristics for complying vary by browser

### What did you expect to see?

compliance varies by browser

### Do you have any supporting links, references, or citations?

https://www.merriam-webster.com/dictionary/heuristic

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/security/practical_implementation_guides/turning_off_form_autocompletion`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Turning_off_form_autocompletion
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/security/practical_implementation_guides/turning_off_form_autocompletion/index.md
* Last commit: https://github.com/mdn/content/commit/75e254fe894a22724a3d01ef6b20b9848e9f5309
* Document last modified: 2024-06-24T13:06:40.000Z

</details>

**Comment by hamishwillee** [comment]
Good point. Will be fixed by https://github.com/mdn/content/pull/36136
