### ISSUE TITLE
Not having an example

### ISSUE THREAD

**Issue by a0m0rajab** [mdn/content#36134]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside

### What information was incorrect, unhelpful, or incomplete?

The second example was not showing how to print the page, if we had a print button like the first example it would be awesome
https://github.com/mdn/content/blob/main/files/en-us/web/css/page-break-inside/index.md?plain=1

### What did you expect to see?

I would expect to test the print page example in this one. 

### Do you have anything more you want to share?

d

**Comment by Josh-Cena** [comment]
This example does not pertain to printed media at all. It's showing how you can use `break-inside` to avoid column breaks in a multi-column layout.
