### ISSUE TITLE
crypto.randomUUID claims to have been available for 6.5 years more than it has

### ISSUE THREAD

**Issue by bakkot** [mdn/content#36155]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

### What specific section or headline is this issue about?

the "baseline" header, when you click through to expand it:

![Screenshot 2024-10-01 at 4 44 45 PM](https://github.com/user-attachments/assets/f90b4566-aed0-426e-8d6b-a6fc23aa87e2)

### What information was incorrect, unhelpful, or incomplete?

> It’s been available across browsers since July 2015.

### What did you expect to see?

> It’s been available across browsers since March 2022.

(or something like that - per the compat data at the bottom of the page, it shipped in Safari on 2022-03-14.)

### Do you have anything more you want to share?

I couldn't figure out where the "July 2015" claim comes from. The compat data seems to be correct as far as I can tell.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/crypto/randomuuid`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/crypto/randomuuid/index.md
* Last commit: https://github.com/mdn/content/commit/cc27a64bb555b250cf0984a3a744e5fd251e3565
* Document last modified: 2024-09-25T06:14:43.000Z

</details>

**Comment by Josh-Cena** [comment]
Here is the full data file: https://github.com/web-platform-dx/web-features/blob/main/features/web-cryptography.yml.dist

Baseline is calculated per feature group, not per feature, so it's often really confusing for feature groups that expand over time. I think this is tracked by https://github.com/mdn/yari/issues/11546.
