### ISSUE TITLE
Safari 18 no longer supports storage.local.get by passing an object with object names as keys and the default value as value.

### ISSUE THREAD

**Issue by here-nerd** [mdn/content#36152]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get

### What specific section or headline is this issue about?

Browser Compatibility --> Safari

### What information was incorrect, unhelpful, or incomplete?

Since Safari 18, calling the get API with this form:
`let gettingItem = browser.storage.local.get({
  kitten: "no kitten",
  monster: "no monster",
  grapefruit: {
    name: "Grape Fruit",
    eats: "Water",
  },
});`

Always return undefined.

### What did you expect to see?

An implementation note that Safari has limited support on this api.

### Do you have any supporting links, references, or citations?

https://developer.apple.com/forums/thread/765169

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/storage/storagearea/get`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/get/index.md
* Last commit: https://github.com/mdn/content/commit/b8a0743ca8b1e1b1b1a95cc93a4413c020f11262
* Document last modified: 2024-09-01T17:04:58.000Z

</details>

**Comment by rebloor** [comment]
This issue was fixed according to the [WebKit PR](https://github.com/WebKit/WebKit/pull/34507) linked from the [forum post](https://developer.apple.com/forums/thread/765169).
