### ISSUE TITLE
CSP: Document http->https, and wss being allowed in `'self'`

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#36168]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src has a note:

<img width="730" alt="Screen Shot 2024-10-02 at 12 00 50 PM" src="https://github.com/user-attachments/assets/ed7dfd91-faa6-4e17-bf81-6087072bc807">

This is I think out of date but it refers to an interesting spec change that we should document: https://github.com/w3c/webappsec-csp/commit/0e81d81b64c42ca3c81c048161162b9697ff7b60.

> `http:` is not equivalent to `http: https:`, and `ws:` to `ws: wss:`.
Likewise, handling for `'self'` now includes `https:` and `wss:` on
the protected resource's host.

(I think "not" above should be "now")

The idea I think is that:
- if you specify `http:` as the scheme in a source expression, the browser will allow `https:`
- if you specify `ws:` as the scheme in a source expression, the browser will allow `wss:`
- if you specify `'self'` in a source expression, then `wss:` is allowed for the scheme if the rest of the origin matches

**Comment by hamishwillee** [comment]
FWIW

1. the ability to specify http and https in a schema is very new https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket#url - less than a year. 
2. For this case I think I would have expected a compat data update.
