### ISSUE TITLE
Remove deprecated displaySurface "application" value.

### ISSUE THREAD

**Issue by konhof** [mdn/content#36160]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings

### What specific section or headline is this issue about?

Instance properties of shared screen tracks > displaySurface > application

### What information was incorrect, unhelpful, or incomplete?

It looks like "application" enum value is deprecated?

This page still lists it, but it's been removed in https://github.com/w3c/mediacapture-screen-share/pull/243 and it's also not mentioned on the linked https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/displaySurface page.

### What did you expect to see?

No "application" value.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mediatracksettings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediatracksettings/index.md
* Last commit: https://github.com/mdn/content/commit/c9e9f9f4faf2e8a5985e5834d9424557341f33c9
* Document last modified: 2024-05-14T06:06:42.000Z

</details>

**Comment by Josh-Cena** [comment]
It was removed in https://github.com/mdn/content/pull/22733 but we didn't update the landing page.
