### ISSUE TITLE
Missing documentation for `ErrorEvent` properties

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#36178]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent

### What information was incorrect, unhelpful, or incomplete?

documentation for `ErrorEvent` properties are missing

### What did you expect to see?

add documentation

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/webappapis.html

**Comment by Josh-Cena** [comment]
Hi @skyclouds2001, I'm closing all missing documentation issues, because we already have https://openwebdocs.github.io/web-docs-backlog/all/, and all APIs there are automatically considered in the backlog and don't need separate issues to track. Feel free to send PRs directly.

**Comment by skyclouds2001** [comment]
Got it! Maybe it is worth mentioning in https://github.com/mdn/content/blob/main/.github/ISSUE_TEMPLATE/config.yml, to avoid similar issues to be created

**Comment by Josh-Cena** [comment]
It's not dogmatic—sometimes they have clear defined boundaries and are immediately actionable and we keep the issue.
