### ISSUE TITLE
Readonly elements are focusable

### ISSUE THREAD

**Issue by Asmatzaile** [mdn/content#36213]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes

### What specific section or headline is this issue about?

Read-only and read-write

### What information was incorrect, unhelpful, or incomplete?

In a similar manner to :disabled and :enabled, the :read-only and :read-write pseudo-classes target two states that form inputs toggle between. Read-only inputs have their values submitted to the server, but the user can't edit them, whereas read-write means they can be edited — their default state.

----

If you try the live example, you'll see that the top set of form elements are not focusable, however, the values are submitted when the form is submitted. We've styled the form controls using the :read-only and :read-write pseudo-classes, like so:

### What did you expect to see?

In a similar manner to :disabled and :enabled, the :read-only and :read-write pseudo-classes target two states that form inputs toggle between. As with disabled inputs, the user can't edit read-only inputs, but their values will be submitted to the server. Read-write means they can be edited — their default state.

----

If you try the live example, you'll see that the top set of form elements are not editable, however, the values are submitted when the form is submitted. We've styled the form controls using the :read-only and :read-write pseudo-classes, like so:

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/ui_pseudo-classes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/ui_pseudo-classes/index.md
* Last commit: https://github.com/mdn/content/commit/27a7cd721d227deb47b8b6837d8eba0a0ae06ffb
* Document last modified: 2024-07-25T20:44:14.000Z

</details>

**Comment by piall** [comment]
I would like to work on this issue.
