### ISSUE TITLE
[JS] Improve explanation of globalThis and this in global scope

### ISSUE THREAD

**Issue by Rewwoken** [mdn/content#36214]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

### What specific section or headline is this issue about?

Description

### What information was incorrect, unhelpful, or incomplete?

> The `globalThis` property provides a standard way of accessing the global `this` value (and hence the global object itself) across environments.

> To help you remember the name, just remember that in global scope the `this` value is `globalThis`.

In Node.js the `this` value in global scope references the `module.exports`, not the `globalThis`. This can confuse people, since it says about the behaviour _across environments_.

### What did you expect to see?

> Remember that in the browser's global scope, `this` refers to `globalThis`. In Node.js, however, `this` in the global scope refers to `module.exports`, not the global object. To access the global object in both environments, always use `globalThis`.

### Do you have any supporting links, references, or citations?

[Node.js playground](https://stackblitz.com/edit/node-wsyubm?file=index.js)
[Browser playground](https://codepen.io/Rewwoken/pen/MWNereM)

**Comment by Josh-Cena** [comment]
In a CommonJS module, the top level scope is not the global scope. (Neither are ES modules.) Every CJS module is wrapped into a function, with `this` passed as `module.exports`. Only the top level of a non-module script in the browser is actually in the global scope.
