### ISSUE TITLE
Value not found in DB! found in some documents

### ISSUE THREAD

**Issue by givvemee** [mdn/content#36233]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/stop-color

### What specific section or headline is this issue about?

Value not found in DB! found in some documents

### What information was incorrect, unhelpful, or incomplete?

I guess there's some issue in DB. 

### What did you expect to see?

That part is written as {{CSSInfo}} in code. 

### Do you have any supporting links, references, or citations?

<img width="728" alt="스크린샷 2024-10-07 20 36 57" src="https://github.com/user-attachments/assets/1c8f33f9-e679-4212-a1fa-ae83625b7dd4">

**Comment by skyclouds2001** [comment]
the full list can be found here https://jc-verse.github.io/mdn-graph/warnings

![image](https://github.com/user-attachments/assets/93625f7c-b192-4443-9e6c-f26bb69d74ec)

**Comment by Josh-Cena** [comment]
Yep, we know about it already. Since it's not a content issue and we already have a way to track it, I'm closing this for now. And thanks @skyclouds2001 for following up.
