### ISSUE TITLE
Missing an attribute: specularConstant

### ISSUE THREAD

**Issue by LibraSun** [mdn/content#36238]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpotLight

### What specific section or headline is this issue about?

ATTRIBUTES

### What information was incorrect, unhelpful, or incomplete?

No mention is made of the **specularConstant** attribute, which represents the ks value in the Phong shading model. Should be included, as it is part of the **feSpecularLighting** spec.

### What did you expect to see?

specularConstant listed just before specularExponent

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/specularConstant

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/element/fespotlight`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpotLight
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/fespotlight/index.md
* Last commit: https://github.com/mdn/content/commit/3a1ef2abc8233835f0b0cc73afaf36e44edaf4a1
* Document last modified: 2024-02-28T23:56:15.000Z

</details>

**Comment by Josh-Cena** [comment]
I don't see `specularConstant` here: https://drafts.fxtf.org/filter-effects/#feSpotLightElement do you have proof that `specularConstant` is supported for `feSpotLightElement`?

**Comment by LibraSun** [comment]
Only indirectly:
(A) It *is mentioned* on the page you linked me to:
[image: image.png]
(B) Gemini AI engine refers to it when asked.
(C) The page I linked you to on MDN defines it.
(D) Setting 'specularConstant' to different values in SVG editors has
visible and profound effects in their image Preview pane.
(E) Specifically, this attribute is supported and flyout explanation
provided by VSCode extensions like "SVG".

**Comment by Josh-Cena** [comment]
Please check the following pages:

- https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpecularLighting
- https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpotLight
- https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/specularConstant

They are consistent about one thing: `specularConstant` is an attribute of `feSpecularLighting`, not an attribute of `feSpotLight`.

>  It *is mentioned* on the page you linked me to:

I can't see the image on GitHub, but all mentions of the `specularConstant` attribute are from the `feSpecularLighting` element, not `feSpotLight`.

> Gemini AI engine refers to it when asked.

Never ever trust AI responses about technical facts.

> The page I linked you to on MDN defines it.

That page explicitly says it's only supported for `feSpecularLighting`.

Please make sure that you are not mixing up `feSpecularLighting` and `feSpotLight`. I'm closing this for now, but if there's actually proof that browsers support `specularConstant` on the `feSpotLight` element, via a code example that can be directly viewed in browser, I'm happy to reopen.

**Comment by LibraSun** [comment]
You are definitely right and clearly I had become confused between two
different SVG primitives, sorry.
