### ISSUE TITLE
Use of different color scheme in examples

### ISSUE THREAD

**Issue by kenjarna** [mdn/content#36268]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/::after

### What specific section or headline is this issue about?

Examples, under Accessibility

### What information was incorrect, unhelpful, or incomplete?

In the example detailing how to use ::after pseudo element, the colors red and green are used to color the text. It's a pretty minor issue given the text also displays the use of the element, but it'd be nice to really see the color differences too :).

### What did you expect to see?

Different colors to highlight the use of ::after psudeo element text.

### Do you have anything more you want to share?

You should choose different colors as red/green colorblindness is pretty common. I'm not sure if this is an issue on other pages, but just as a pointer for documentation :). 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_doublecolon_after`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::after
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_after/index.md
* Last commit: https://github.com/mdn/content/commit/4cb569f768ec9529724f8fb06539f2903a583a41
* Document last modified: 2024-07-26T15:45:53.000Z

</details>

**Comment by OnkarRuikar** [comment]
@kenjarna does [this change](https://pr36299.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/::after#result) look good to you?

**Comment by jolka-ef** [comment]
Hi, 
Sorry for jumping into the conversation.
According to information provided on https://www.nceas.ucsb.edu/sites/default/files/2022-06/Colorblind%20Safe%20Color%20Schemes.pdf

You can use some colors from colorblind safe palettes.
For example :
violet and pink
rgb(046 037 133) and rgb(159 074 150)

blue and yellow
rgb(000 114 178) and rgb(230 159 000)

**Comment by kenjarna** [comment]
Thank you for sharing that @jolka-ef! 

I'd think either of those combinations suggested will work swimmingly @OnkarRuikar. Doc makers choice at that point :). Thank you for working on this and getting it resolved so quickly.
