### ISSUE TITLE
Documentation only: Content suggestion: include a link to Web Speech API on main API page?

### ISSUE THREAD

**Issue by rowild** [mdn/content#3627]
## What is the new suggestion?
There is a Web Speech API and it even has its own "starting page": https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API
But there is no link on the APIs overview page in the "Sepcification" section on top: https://developer.mozilla.org/en-US/docs/Web/API

I would think that is should be listed there, too. But I might be wrong. If so, would anybody mind to explain, why it is not listed there? Thank you!

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/yari/pull/3383 with a fix.
