### ISSUE TITLE
Web Audio Editor was depricated

### ISSUE THREAD

**Issue by gls-manifold** [mdn/content#36282]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Tools

### What information was incorrect, unhelpful, or incomplete?

> ### [Firefox](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Tools#firefox)
> 
> Firefox offers a native [Web Audio Editor](https://firefox-source-docs.mozilla.org/devtools-user/web_audio_editor/index.html).

Unfortunately this is not the case, it has been a long time since this tool has been available.

### What did you expect to see?

Some actual information or a path on how to find this tool.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_audio_api/tools`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Tools
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_audio_api/tools/index.md
* Last commit: https://github.com/mdn/content/commit/b065c09b79d18abf0f04778c9307e1c312b8c6f9
* Document last modified: 2024-08-02T15:47:51.000Z

</details>

**Comment by Josh-Cena** [comment]
We need to remove this page since there's close to zero useful information here.

**Comment by wbamberg** [comment]
> We need to remove this page since there's close to zero useful information here.

Yes, I was going to say the same thing.
