### ISSUE TITLE
Web Codecs API lost Audio interfaces informations in FF130 release notes

### ISSUE THREAD

**Issue by woody-li** [mdn/content#36290]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/130

### What specific section or headline is this issue about?

APIs

### What information was incorrect, unhelpful, or incomplete?

The Web Codecs API only includes Video interfaces, but lost Audio interfaces. 

### What did you expect to see?

Add Audio related interfaces:

- AudioData
- AudioDecoder
- AudioEncoder
- EncodedAudioChunk

### Do you have any supporting links, references, or citations?

https://github.com/mdn/browser-compat-data/pull/24331
https://bugzilla.mozilla.org/show_bug.cgi?id=1908572#c11

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/firefox/releases/130`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/130
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/130/index.md
* Last commit: https://github.com/mdn/content/commit/2cca85442dcfa50e82bffb7e2c0dbae4c5158256
* Document last modified: 2024-09-05T23:03:53.000Z

</details>

**Comment by Josh-Cena** [comment]
@hamishwillee

**Comment by hamishwillee** [comment]
Thanks, will be fixed by #36395
