### ISSUE TITLE
HTML button: SVG star looks incorrect

### ISSUE THREAD

**Issue by salty-horse** [mdn/content#36301]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

### What specific section or headline is this issue about?

Accessibility

### What information was incorrect, unhelpful, or incomplete?

The star image in the Result section looks incorrect, with its two "legs" going straight down instead of sideways.

### What did you expect to see?

The star should look proper.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/button`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/button/index.md
* Last commit: https://github.com/mdn/content/commit/ed06a82c69130a7337393cc231ab73a21c1430f3
* Document last modified: 2024-09-23T14:22:38.000Z

</details>

**Comment by jolka-ef** [comment]
I want to work on this one. The SVG path is incorrect.
