### ISSUE TITLE
Example demonstrates different `font-variant-ligatures` values, but they have no effect. Examples' specified font-family not in use.

### ISSUE THREAD

**Issue by gima** [mdn/content#36306]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The Result doesn't show any difference between the different `font-variant-ligatures` valued `<p>`aragraphs.

### What did you expect to see?

The different `font-variant-ligatures` values should affect which ligatures the example paragraphs texts show, just like to page documents should happen.

### Do you have anything more you want to share?

The Example specifies "Lora" `font-family`, but the browser Web Developer Tools' "Fonts"-tab shows that the system's default font is being used istead (which possibly doesn't have any ligatures).
Maybe there's a problem somewhere in the page's CSS, which causes the desired font not to be loaded correctly.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-variant-ligatures`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-variant-ligatures/index.md
* Last commit: https://github.com/mdn/content/commit/8d8f3f44b498aef7b8cf2729d5656f96d2ff6ae5
* Document last modified: 2024-07-18T11:38:59.000Z

</details>

**Comment by Josh-Cena** [comment]
<img width="561" alt="image" src="https://github.com/user-attachments/assets/f5c50277-ad64-4cbf-8d51-86bce6a55fe5">

It's loaded in my browser. It could be because you could not connect to Google Fonts, so the asset failed to load.
