### ISSUE TITLE
Issue with "function*": Some typos in the last paragraph

### ISSUE THREAD

**Issue by kashifshamaz21** [mdn/content#3631]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*

#### What information was incorrect, unhelpful, or incomplete?
```Much like a return statement, an error is thrown inside the generator will make the generator finished -- unless caught within the generator's body.```

#### Specific section or headline?
`an error is thrown inside the generator will make the generator finished`

#### What did you expect to see?
`when an error is thrown inside the generator, it will make the generator finish`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/function_star_`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/function_star_/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/3659 with a fix.

**Comment by kashifshamaz21** [comment]
Thanks @sideshowbarker for the prompt update :)
