### ISSUE TITLE
link incorrect

### ISSUE THREAD

**Issue by SkepticaLee** [mdn/content#36332]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

The link for the text "until-found" directs to the page for "hidden"

### What did you expect to see?

the page for "until-found"

### Do you have any supporting links, references, or citations?

No

### Do you have anything more you want to share?

No

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/index.md
* Last commit: https://github.com/mdn/content/commit/87b1277782f71a58693aeb6a83464e3ccabbfa20
* Document last modified: 2024-08-20T17:59:26.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, but this link is correct - `until-found` is an allowed value of the `hidden` global attribute.

Arguably this would benefit from a "Values" section and an explicit link, but that is not the model for the attributes page, so it is not an error per-se.
