### ISSUE TITLE
Mention rem unit on rem() function page

### ISSUE THREAD

**Issue by HillyButterfly** [mdn/content#36340]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/rem

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/rem

### What information was incorrect, unhelpful, or incomplete?

The text in this section does not seem to fit the context of CSS as we know it. It describes a function rem() that sounds like a mathematical operation for calculating the residual value, similar to the modulus operator % in programming languages such as JavaScript. However, this is not a standard function in CSS.

In CSS, “rem” is used as a unit of measurement and not as a function for mathematical calculations.

### What did you expect to see?

In CSS, “rem” is used as a unit of measurement and not as a function for mathematical calculations. So I expected to see information about that unit. In this context, the word "rem" means "root element".

### Do you have any supporting links, references, or citations?

https://www.w3schools.com/cssref/tryit.php?filename=trycss_unit_rem

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/rem`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/rem
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/rem/index.md
* Last commit: https://github.com/mdn/content/commit/8ac73df2fbe2c88d8649fcb006dcde098616c723
* Document last modified: 2024-06-22T02:03:07.000Z

</details>

**Comment by Josh-Cena** [comment]
We don't document units as separate pages. This page talks about the `rem()` function. If you want to read about the `rem` unit, see https://developer.mozilla.org/en-US/docs/Web/CSS/length.

We should probably add a link to the `<length>` page, both in the see also and as a note in the introduction that says "to read about the unit `rem`, see the `<length>` page".

**Comment by HillyButterfly** [comment]
But there is not such a thing as a css rem() function. It doesn't exist.

Op di 15 okt. 2024 16:10 schreef Joshua Chen ***@***.***>:

**Comment by Josh-Cena** [comment]
This page tells you exactly what it does and how to use it?
