### ISSUE TITLE
Add subpixel tolerance for scrollHeight demo

### ISSUE THREAD

**Issue by Nugget8** [mdn/content#36365]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight

### What specific section or headline is this issue about?

"Checking that the user has read a text" example result

### What information was incorrect, unhelpful, or incomplete?

On Google Chrome and Microsoft Edge, when scrolling all the way through the example's "result", the browser won't get down to the very last pixel when scrolling with a mouse and the checkbox won't get enabled even if the scrollbar down arrow is clicked. The only way to get the maximum scrollTop is to select the last row(s) of the text content.

### What did you expect to see?

Some isRead() tolerance in the example itself to avoid problems like this.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/scrollheight`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/scrollheight/index.md
* Last commit: https://github.com/mdn/content/commit/d0b23f3f26637aa405ee9ee0a0892fc6e9b742ef
* Document last modified: 2024-07-26T02:56:49.000Z

</details>

**Comment by Josh-Cena** [comment]
Let's add a 10px allowance. Have you tried if that works for you? Because in my Chrome it works without adding any wiggle room.

**Comment by Nugget8** [comment]
I found out that if I change my browser window zoom it works properly. It just happens that my window.innerHeight at 100% zoom is 729.60 px which won't get the scrollbar to the very bottom under normal circumstances (mouse scrolling or scrollbar buttons).

**Comment by Nugget8** [comment]
Glad it is mentioned, but it can be quite confusing if the example doesn't work as expected :)

**Comment by Pengwin001** [comment]
what is this?
