### ISSUE TITLE
textarea incorrect information

### ISSUE THREAD

**Issue by davanT420** [mdn/content#36369]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

### What specific section or headline is this issue about?

<textarea> does not support the value attribute.

### What information was incorrect, unhelpful, or incomplete?

The sentence "<textarea> does not support the value attribute." is incorrect: textarea does have a value attribute.

### What did you expect to see?

<textarea> does support the value attribute.

### Do you have any supporting links, references, or citations?

The information is correct on the [HTMLTextArea page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/value), where it is noted that:

"The value property of the [HTMLTextAreaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement) interface represents the value of the [<textarea>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) element as a string, which is an empty string if the widget contains no content. It returns or sets the raw value contained in the control."

### Do you have anything more you want to share?

A lot, but probably NSFW.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/textarea`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/textarea/index.md
* Last commit: https://github.com/mdn/content/commit/783ffd9c1cf35421242e028a1b8743cf2b1918dd
* Document last modified: 2024-10-08T05:47:21.000Z

</details>

**Comment by Josh-Cena** [comment]
The `textarea` HTML element does not have the `value` attribute, meaning you cannot do

```html
<textarea value="foo"></textarea>
```

Instead you must do

```html
<textarea>foo</textarea>
```

The `HTMLTextAreaElement` JS interface's properties are unrelated to what HTML attributes are supported.
