### ISSUE TITLE
Issue with "HTMLObjectElement": property 'tabindex' links to 'type' page

### ISSUE THREAD

**Issue by targumon** [mdn/content#3637]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement

#### What information was incorrect, unhelpful, or incomplete?
The page list properties which are linked to a dedicated page for each property - one of them is wrong.

#### Specific section or headline?
The property `HTMLObjectElement.tabindex` has a link to https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/type

#### What did you expect to see?
I expected a link to https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/tabindex (which doesn't seem to exist)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlobjectelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlobjectelement/index.html
* Last commit: https://github.com/mdn/content/commit/068e0f6bfb252775eb9835632c3b0083259c9fcc
* Document last modified: 2021-01-25T04:06:51.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/3666 with a fix
