### ISSUE TITLE
Specify that "canplay" event, not being fired by mobile Safari on Audio

### ISSUE THREAD

**Issue by hugmouse** [mdn/content#36378]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplay_event

### What information was incorrect, unhelpful, or incomplete?

`canplay` event doesn't fire on iOS 17 mobile Safari for Audio

### What did you expect to see?

Just add a note about the fact that, at least on iOS 17, Safari doesn't fire this event anymore, and it can't be used to check if we can play audio in the moment. As a workaround, you can use `loadedmetadata` or add `autoplay` to every single audio tag and pause it immediately - I think in that case Safari will actually fire this event.

### Do you have any supporting links, references, or citations?

"HTMLAudioElement issues in iOS 17.4": https://forums.developer.apple.com/forums/thread/748001

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlmediaelement/canplay_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplay_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlmediaelement/canplay_event/index.md
* Last commit: https://github.com/mdn/content/commit/b71d118ffc6d72b77efad9661110fcc9ede464eb
* Document last modified: 2024-07-25T14:22:56.000Z

</details>
```[tasklist]
### Tasks
```

**Comment by hugmouse** [comment]
This commit might be related to this issue as well: https://github.com/WebKit/WebKit/commit/d0b6e889f00ee859d4f9ed8f7119a3ed3f5ad7cf

But this one related to Video, not Audio.

**Comment by Josh-Cena** [comment]
Have you filed an issue to Webkit? We don't document browser bugs.
