### ISSUE TITLE
webRequest.onCompleted example doesn't work

### ISSUE THREAD

**Issue by TheYellowArchitect** [mdn/content#36383]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onCompleted

### What specific section or headline is this issue about?

The example

### What information was incorrect, unhelpful, or incomplete?

```js
let target = "https://developer.mozilla.org/*";

/*
e.g.
"https://developer.mozilla.org/en-US/"
200

or:

"https://developer.mozilla.org/en-US/xfgkdkjdfhs"
404
*/
function logResponse(responseDetails) {
  console.log(responseDetails.url);
  console.log(responseDetails.statusCode);
}

browser.webRequest.onCompleted.addListener(logResponse, { urls: [target] });
```

I copy-pasted the above and changed the target to youtube, and used it as an extension for mozilla firefox. This is the error I got: 

`TypeError: browser.webRequest is undefined`

### What did you expect to see?

The above `console.log` message

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/webrequest/oncompleted`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onCompleted
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/webrequest/oncompleted/index.md
* Last commit: https://github.com/mdn/content/commit/b8a0743ca8b1e1b1b1a95cc93a4413c020f11262
* Document last modified: 2024-09-01T17:04:58.000Z

</details>

**Comment by rebloor** [comment]
@TheYellowArchitect the response suggests that you aren't running the code in the webextenstion content. Please check StackOverflow, post to the [forum](https://discourse.mozilla.org/c/add-ons), or reopen this issue with full details and how you were running the code. Thanks.
