### ISSUE TITLE
Issue with "Referrer-Policy": (short summary here please)

### ISSUE THREAD

**Issue by evilpie** [mdn/content#3640]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

#### What information was incorrect, unhelpful, or incomplete?

> Firefox version 87: network.http.referer.userControlPolicy

#### What did you expect to see?

I am not sure why the documentation claims that the pref name is `network.http.referer.userControlPolicy` again in 87. I can only find references to `network.http.referer.defaultPolicy`:

https://searchfox.org/mozilla-central/rev/d58860eb739af613774c942c3bb61754123e449b/modules/libpref/init/StaticPrefList.yaml#8599

The default value did change in 87 via https://bugzilla.mozilla.org/show_bug.cgi?id=1589074.

#### Did you test this? If so, how?

https://searchfox.org only finds some random reference to userControlPolicy in a test.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/referrer-policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/referrer-policy/index.html
* Last commit: https://github.com/mdn/content/commit/4238cc9a7eddd2ae555cb024bde3ac0c0d3e5b61
* Document last modified: 2021-03-25T08:20:39.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @evilpie , I think I screwed up. In any case, have checked the code and fixed this up in #3648
