### ISSUE TITLE
performance.memory is incorrectly marked as available in Web Workers

### ISSUE THREAD

**Issue by Le0Developer** [mdn/content#36402]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Performance/memory

### What specific section or headline is this issue about?

"Note: This feature is available in Web Workers."

### What information was incorrect, unhelpful, or incomplete?

#36181 incorrectly marked `performance.memory` as being available in Web Workers – it isn't.

### What did you expect to see?

No "Note: This feature is available in Web Workers" alert.

### Do you have any supporting links, references, or citations?

1. Run `new Worker("data:text/javascript," + encodeURIComponent("console.log(performance.memory)"))` in your console
2. Observe `undefined` being logged

**Comment by Josh-Cena** [comment]
@skyclouds2001 FYI

**Comment by skyclouds2001** [comment]
per [BCD](https://github.com/mdn/browser-compat-data/blob/main/api/Performance.json#L739), this feature is not standard and only supported in chromium-based browsers

as for my test using https://worker-playground.glitch.me/ also indicate this feature is only available in worker

also confirmed in [chromium source code](https://github.com/chromium/chromium/blob/main/third_party/blink/renderer/core/timing/performance.idl#L68)

**Comment by Josh-Cena** [comment]
I think you mean "only available on window"? The IDL in Chromium also says it's only exposed on window.

**Comment by skyclouds2001** [comment]
> I think you mean "only available on window"? The IDL in Chromium also says it's only exposed on window.

Yes
