### ISSUE TITLE
`Promise.try` is missing arguments

### ISSUE THREAD

**Issue by CanadaHonk** [mdn/content#36413]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/try

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

> `Promise.try(func)`
> A function that is called synchronously with no arguments.

### What did you expect to see?

`Promise.try(func, ...args)`

### Do you have any supporting links, references, or citations?

Spec: https://tc39.es/proposal-promise-try/#sec-promise.try

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise/try`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/try
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/try/index.md
* Last commit: https://github.com/mdn/content/commit/b67fd42cfb01dd4d9504c4182b462851588a0bad
* Document last modified: 2024-09-07T02:12:32.000Z

</details>

**Comment by Josh-Cena** [comment]
Wow, it was added _8 months ago_—how did I miss it?!

Thanks for filing!
