### ISSUE TITLE
Missing info on EventSource

### ISSUE THREAD

**Issue by kipraskrasilnikas** [mdn/content#36416]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/EventSource

### What information was incorrect, unhelpful, or incomplete?

There is absolutely no specification on what the URL should look like and what it should be returning. Cause in the examples there is an incomplete url being used and it is absolutely unclear what it should do. 

By logic, it should be returning SSE messages and the eventSource should be catching them, but that's not the case at all it seems.

### What did you expect to see?

1. How to properly see the error messages you are receiving, cause now onerror just returns an error event with absolutely no useful information
2. What the called url should look like and what exact formatting and messages EventSource is expecting, what it returns. Overall how the object is used, initialized and how it handles things in detail

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/eventsource`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventSource
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/eventsource/index.md
* Last commit: https://github.com/mdn/content/commit/f216422c99b6c7014e398803b70600501bce8a48
* Document last modified: 2024-10-16T05:12:45.000Z

</details>

**Comment by Josh-Cena** [comment]
Have you read https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events?

**Comment by kipraskrasilnikas** [comment]
No, thanks


2024-10-20, sk, 20:07 Joshua Chen ***@***.***> rašė:

**Comment by kipraskrasilnikas** [comment]
Ok, it's still unclear what the url parameter should look like. Can it only
be a file or any endpoint that returns a SSE stream?

2024-10-21, pr, 12:09 Kipras Krasilnikas ***@***.***>
rašė:

**Comment by kipraskrasilnikas** [comment]
Because I input a good url, but the eventSource keeps failing and it's
absolutely unclear why


2024-10-21, pr, 12:13 Kipras Krasilnikas ***@***.***>
rašė:

**Comment by kipraskrasilnikas** [comment]
I'm getting no error, my messages just do not show up in event source
listeners, even though I am debugging them, the code is reached, and they
are formatted correctly.

However, when I add the onerror handler to EventSource, I always get the
"EventSource failed" error event after subscribing. And the event doesn't
have any useful info that I'm aware of. I debugged and the correct function
is called and everything should be in order, print the message as well, but
it just doesn't get to EventSource for some reason.

Pagarbiai,
Kipras Krasilnikas


2024-10-21, pr, 15:23 Joshua Chen ***@***.***> rašė:

**Comment by Josh-Cena** [comment]
Could you give a complete, runnable example for us to try?

**Comment by Josh-Cena** [comment]
Could you give a complete, runnable example for us to try?

**Comment by kipraskrasilnikas** [comment]
Hello, gmail doesn't let me include a .rar file (even though I removed the
executable) so I'll drop the code as text

main.go:

package main

import (
    "fmt"
    "io"
    "net/http"
    "sync"
    "time"
)

type Message struct {
    ID      int
    Topic   string
    Content string
}

var (
    topics    = make(map[string]chan Message)
    messageId int
    mu        sync.Mutex
)

func main() {
    fmt.Println("Starting Infocenter Service...")
    fmt.Println("Server is running at http://localhost:8080/infocenter")

    // Serve static files from the "static" directory
    fs := http.FileServer(http.Dir("./static"))
    http.Handle("/static/", http.StripPrefix("/static/", fs)) // Serve
static files

    fmt.Println("esam maine")

    // Registering handlers
    http.HandleFunc("/infocenter/", infocenterHandler)
    http.ListenAndServe(":8080", nil)
}

func infocenterHandler(w http.ResponseWriter, r *http.Request) {
    topic := r.URL.Path[len("/infocenter/"):] // Extract topic from URL

    if topic == "" {
        homepageHandler(w, r) // Call the homepage if no topic is specified
        return
    }

    if r.Method == http.MethodGet {
        receiveMessages(w, topic)
    } else if r.Method == http.MethodPost {
        sendMessage(w, r, topic) // Call function to send the message
    } else {
        // Handle unsupported methods
        http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
    }
}

// TO DO: Remake this to handle multiple clients
func receiveMessages(w http.ResponseWriter, topic string) {
    w.Header().Set("Access-Control-Allow-Origin", "*")
    w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
    w.Header().Set("Access-Control-Expose-Headers", "Content-Type")

    w.Header().Set("Content-Type", "text/event-stream")
    w.Header().Set("Cache-Control", "no-cache")
    w.Header().Set("Connection", "keep-alive")

    mu.Lock()
    // topicExists := false
    if _, exists := topics[topic]; !exists {
        topics[topic] = make(chan Message)
        // topicExists = true
    }
    mu.Unlock()

    // if topicExists {
    fmt.Printf("Listening to topic: %s\n", topic)

    ch := topics[topic]

    go func() {
        defer func() {
            mu.Lock()
            select {
            case _, ok := <-ch:
                if ok {
                    close(ch)
                }
            default:
                // Channel is already empty or closed
            }

            delete(topics, topic) // Remove the topic from the topics map
            mu.Unlock()
        }()

        timeoutTime := 30
        timeout := time.After(time.Duration(timeoutTime) * time.Second)

        for {
            select {
            case msg, ok := <-ch:
                if !ok {
                    return // Channel is closed, exit
                }

                fmt.Fprintf(w, "id: %d\nevent: msg\ndata: %s\n\n", msg.ID,
msg.Content)
                w.(http.Flusher).Flush()

                fmt.Println("listening")
                fmt.Printf("id: %d\nevent: msg\ndata: %s\n\n", msg.ID, msg.
Content)
            case <-timeout:
                // Send a timeout event before disconnecting
                fmt.Printf("event: timeout\ndata: %ds\n\n", timeoutTime)

                fmt.Fprintf(w, "event: timeout\ndata: %ds\n\n", timeoutTime)
                w.(http.Flusher).Flush() // Flush the response writer

                return
            }
        }
    }()
    // }
}

// Potential improvement: save messages when clients are not listening and
let clients catch up after they start
func sendMessage(w http.ResponseWriter, r *http.Request, topic string) {
    body, err := io.ReadAll(r.Body)

    if err != nil {
        http.Error(w, err.Error(), http.StatusInternalServerError)
        return
    }

    mu.Lock()

    if ch, exists := topics[topic]; exists {
        messageId++ // Increment the message ID
        message := Message{ID: messageId, Topic: topic, Content: string(body
)}

        fmt.Printf("\nmessage id: %d, %s, %s\n", message.ID, message.Topic,
message.Content)

        // Send the message to the channel for this topic
        select {
        case ch <- message:
            // Message sent successfully
        default:
            // If the channel is full, we skip sending to avoid blocking
            fmt.Printf("Message dropped for topic: %s\n", topic)
        }
    }

    mu.Unlock()

    w.WriteHeader(http.StatusNoContent) // Send HTTP 204 No Content response
}

func homepageHandler(w http.ResponseWriter, r *http.Request) {
    http.ServeFile(w, r, "./static/index.html") // Serve the static HTML
file
}

// topicsToString returns a string representation of the current topics and
their channels
func topicsToString() string {
    mu.Lock()         // Lock to safely access shared map
    defer mu.Unlock() // Ensure the mutex is unlocked when this function
returns

    if len(topics) == 0 {
        return "No topics available."
    }

    result := "Current Topics:\n"
    for topic, ch := range topics {
        result += fmt.Sprintf("Topic: %s, Channel: %p\n", topic, ch) // %p
to print the channel's pointer
    }
    return result
}


static/index.html:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="
https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="
***@***.***/dist/js/bootstrap.bundle.min.js
" integrity=
"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
crossorigin="anonymous"></script>
    <link rel="stylesheet" href="
***@***.***/dist/css/bootstrap.min.css"
integrity=
"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
crossorigin="anonymous">
    <script src="
***@***.***/dist/js/bootstrap.min.js"
integrity=
"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
crossorigin="anonymous"></script>
    <title>Infocenter Service</title>
</head>
<body class="p-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2 class="mb-4">Welcome to the Infocenter Service!</h2>

                <div class="mb-3">
                    <h4>Input a topic:</h4>
                    <input type="text" id="topic" class="form-control" />
                </div>

                <div class="mb-4">
                    <h4>Write a message you want to send to the topic:</h4>
                    <textarea id="message" class="form-control" rows="4"></
textarea>
                </div>

                <div class="mb-4 d-flex">
                    <button id="subscribe" class="btn btn-outline-secondary
me-2">Subscribe to topic</button>
                    <button id="sendMessage" class="btn
btn-outline-secondary">Send message</button>
                </div>

            </div>

            <div class="col-md-6">
                <h2>Incoming Messages</h2>
                <div id="messageBox" class="border p-3" style="height:
400px; overflow-y: auto; background-color: #f8f9fa;"></div>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            // isigilink i flow
            var es = null;
            var url = 'http://localhost:8080/infocenter/';

            function write_message(e) {
                console.log('event received', e);

                var messageDiv = $("<div></div>").addClass("message");
                var messageContent = `
                    <strong>Id:</strong> ${e.lastEventId} <br>
                    <strong>Event:</strong> ${e.type} <br>
                    <strong>Message:</strong> ${e.data} <br><br>
                `;

                console.log(messageContent)
                messageDiv.html(messageContent);
                $("#messageBox").append(messageDiv);
                $("#messageBox").scrollTop($("#messageBox")[0].scrollHeight
);
            }

            $('#subscribe').on('click', function(e) {
                e.preventDefault();
                if (es != null) {
                    es.close();
                }

                var topic = $('#topic').val();

                if (!topic) {
                    alert('Please input a topic');
                    return; // Exit if the topic is empty or undefined
                }

                // TO DO: make this a global constant
                es = new EventSource(`${url}${topic}`);
                console.log(`${url}${topic}`);

                es.addEventListener('msg', write_message);
                es.addEventListener('timeout', write_message);

                es.onerror = function(event) {
                    console.error('EventSource failed:', event);
                    // Check for additional error details
                    if (event.readyState === EventSource.CLOSED) {
                        console.error('EventSource connection closed.');
                    } else if (event.readyState === EventSource.CONNECTING)
{
                        console.error('EventSource connecting...');
                    }
                   es.close(); // Close on error
                };
            });

            $('#sendMessage').on('click', function(e) {
                var topic = $('#topic').val(); // Get the value of the
#topic input
                var message = $('#message').val();

                if (!message) {
                    alert('Please input a message');
                    return
                }

                $.ajax({
                    url: `${url}${topic}`,
                    type: "POST",
                    data: message,
                    error: function (error) {
                        console.log(`Error ${error}`);
                    }
                });
            });
        });
    </script>
</body>
</html>


2024-10-22, an, 17:02 Joshua Chen ***@***.***> rašė:
>
> Could you give a complete, runnable example for us to try?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by kipraskrasilnikas** [comment]
I figured out that the problem is that I am running the
subscription/listening of the topic in another thread and the
receiveMessages function ends and returns a Request before it can actually
listen to what messages are coming

2024-10-24, kt, 10:57 Kipras Krasilnikas ***@***.***>
rašė:

**Comment by Josh-Cena** [comment]
OK this seems fixed.

In the future, please comment on GitHub instead of responding with email. This way, you can use Markdown formatting, instead of your whole message becoming plain text.

**Comment by kipraskrasilnikas** [comment]
Oh my bad, will do next time!
