### ISSUE TITLE
maxTouchPoints are different (depending which browser is used) !

### ISSUE THREAD

**Issue by osworx** [mdn/content#36410]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/maxTouchPoints

### What specific section or headline is this issue about?

returned number(s)

### What information was incorrect, unhelpful, or incomplete?

Why is there a difference between FireFox 131.0.3 (64-Bit) and Chrome 130.0.6723.59

FF reports 1 while Chrome 0 (same do Opera and MS Edge). 

### What did you expect to see?

Same value o with all browsers .. of course ..

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/maxtouchpoints`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/maxTouchPoints
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/maxtouchpoints/index.md
* Last commit: https://github.com/mdn/content/commit/ef75c1741b450c2331204be5563ee964ad5f4c48
* Document last modified: 2023-04-07T06:16:45.000Z

</details>

**Comment by Josh-Cena** [comment]
Which device are you using? On my mac both browsers report zero. Do you have any external inputs connected?

**Comment by Josh-Cena** [comment]
Closing. This is likely a browser bug and you'd rather get confirmation from developers of Firefox before making an MDN issue.
