### ISSUE TITLE
Truthy should be Truey

### ISSUE THREAD

**Issue by Rhialto** [mdn/content#36411]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/Truthy

### What specific section or headline is this issue about?

Truthy

### What information was incorrect, unhelpful, or incomplete?

If falsey is false-like (and that makes sense), then true-like is truey. 

And truthy is truth-like, which is something else, even though it is related. The two truth values are true and false.

### What did you expect to see?

Truey instead of Truthy.

### Do you have any supporting links, references, or citations?

Common construction of the English language.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/glossary/truthy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Truthy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/truthy/index.md
* Last commit: https://github.com/mdn/content/commit/50e5e8a9b8a6b7d0dd9877610c9639d8b90f329f
* Document last modified: 2024-07-08T11:56:20.000Z

</details>

**Comment by Josh-Cena** [comment]
"Truthy" is the standard terminology.

**Comment by Rhialto** [comment]
If you agree it doesn't make much sense, you could add a footnote or something. Somebody pointed me to this page as an authority that "truthy" was correct, probably assuming that MDN did invent it.

**Comment by Josh-Cena** [comment]
"Truthy" is indeed correct, and it's far more than "because MDN invented it". I can't tell you when it was first invented, but names are arbitrary and you just have to accept this inconsistency. I don't think it's confusing enough to add a footnote. And if you insist, you can still call it "truey" as long as both parties understand it.
