### ISSUE TITLE
Issue with "What went wrong? Troubleshooting JavaScript": correct line reference - use let instead of var

### ISSUE THREAD

**Issue by mtcarvalho** [mdn/content#3641]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong

#### What information was incorrect, unhelpful, or incomplete?
The above information:

This error generally means that you have missed a semicolon at the end of one of your lines of code, but it can sometimes be more cryptic. For example, if we change this line inside the `checkGuess()` function:

`var userGuess = Number(guessField.value);`

to

`var userGuess === Number(guessField.value);`

is incorrect, in the [original](https://github.com/mdn/learning-area/blob/master/javascript/introduction-to-js-1/troubleshooting/number-game-errors.html) HTML file we can see in line 57 that the line is:

`let userGuess = Number(guessField.value);`

the documentation also emphasizes that we should not use var. Thus, I think that this minor fix should be corrected.

#### Specific section or headline?

[SyntaxError: missing ; before statement](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong#syntaxerror_missing_before_statement)

#### What did you expect to see?

`let userGuess = Number(guessField.value);`

#### Did you test this? If so, how?

Yes, I searched for the text `var userGuess = Number(guessField.value);` and I didn't found it, so I noticed this error.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/what_went_wrong`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/what_went_wrong/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/3657 with a fix.

**Comment by sideshowbarker** [comment]
oops I see there’s already an open PR — will merge that one instead
