### ISSUE TITLE
Possible Inaccuracy in Documentation: Cross-Domain XHR Requests by Content Scripts

### ISSUE THREAD

**Issue by DDDDD12138** [mdn/content#36438]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#content_scripts_2

### What information was incorrect, unhelpful, or incomplete?

In browser extensions, the statement that content scripts can make cross-domain XHR requests may be incorrect.

![image](https://github.com/user-attachments/assets/3492cafb-8847-49b4-bcf8-88bcd86d6ca2)

### What did you expect to see?

The documentation might benefit from a clarification that content scripts are usually subject to the same-origin policy and cannot make cross-domain XHR requests without proper CORS configuration or by using background scripts.

**Comment by dotproto** [comment]
Thanks for calling this out. I suspect that this line was true when it was added and we didn't catch it when content scripts became subject to the injection context's CORS restrictions.

**Comment by DDDDD12138** [comment]
Do we need to update the documentation now? I think we can remove that sentence, as this is no different from ordinary scripts anymore.

> Can I contribute to it?
