### ISSUE TITLE
Content-Length is not documented as a CORS-safelisted header

### ISSUE THREAD

**Issue by osher** [mdn/content#36455]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_request_header

### What specific section or headline is this issue about?

CORS-safelisted request header

### What information was incorrect, unhelpful, or incomplete?

It does not list the `Content-Length` header

### What did you expect to see?

`Content-Length` to at least be mentioned

### Do you have any supporting links, references, or citations?

I found this issue that sais that Content-Length was accepted as a safe-cors header:
https://github.com/mdn/content/issues/2503

### Do you have anything more you want to share?

I know `Content-Length` is set automatically, but it's an essential part of the protocol and it is safe-listed - I believe it should at least be mentioned...

**Comment by osher** [comment]
🤔 
since this header is being usually set automatically and is not provided by the user-code, 

Alternatively - the page can clarify it lists only headers that can be provided by the user-code,  🤨 but that will raise questions that will be answered by giving `content-length` as an example... 😛

**Comment by wbamberg** [comment]
`Content-Length` is defined as a CORS-safelisted **response** header, not a CORS-safelisted **request** header:

- CORS-safelisted request headers: https://fetch.spec.whatwg.org/#cors-safelisted-request-header
- CORS-safelisted response headers: https://fetch.spec.whatwg.org/#cors-safelisted-response-header-name

It's already listed as such in https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header (as https://github.com/mdn/content/issues/2503#issuecomment-787599722 notes).
