### ISSUE TITLE
console.assert syntax should add namespace prefix

### ISSUE THREAD

**Issue by benlesh** [mdn/content#36463]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/console/assert_static

### What specific section or headline is this issue about?

Syntax

### What information was incorrect, unhelpful, or incomplete?

The example shows `assert` being called as though it's a globally available function. It exists on `console` as `console.assert`

### What did you expect to see?

`console.assert()` calls... or at the very least, `assert` being destructured or otherwise referenced off of `console`.

### Do you have anything more you want to share?

It was a source of confusion for a coworker.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/console/assert_static`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/console/assert_static
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/console/assert_static/index.md
* Last commit: https://github.com/mdn/content/commit/18a5b7e39a1cb4653207cc476c681120cc62d260
* Document last modified: 2024-07-13T02:28:29.000Z

</details>

**Comment by wbamberg** [comment]
Actually I'm wrong about that. For statics we do show the interface: https://developer.mozilla.org/en-US/docs/Web/API/Response/redirect_static. So we should presumably make this change.

**Comment by Josh-Cena** [comment]
We need to fix this for all console methods. I presume it's because console methods weren't used to be documented as static.

**Comment by benlesh** [comment]
Thank you!

![im-doing-my-part-serious](https://github.com/user-attachments/assets/d0af4057-f3b0-41d7-aaa4-1aa1b690c6c5)
