### ISSUE TITLE
place-items applies to more than just grid and flexbox

### ISSUE THREAD

**Issue by davidsgrogan** [mdn/content#36469]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/place-items

### What specific section or headline is this issue about?

Right under the h1 header

### What information was incorrect, unhelpful, or incomplete?

in a relevant layout system such as [Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout) or [Flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout).

### What did you expect to see?

Not sure exactly, but the existing text misleads authors to think that place-items and its constituent justify-items and align-items don't apply to block level boxes because grid and flex are explicitly listed. See https://crbug.com/374801318

These properties do apply to block-level boxes.

### Do you have any supporting links, references, or citations?

https://drafts.csswg.org/css-align/#justify-block

Says that justify-self applies to block-level boxes

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/place-items`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/place-items
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/place-items/index.md
* Last commit: https://github.com/mdn/content/commit/b2833ddfd45cae1bb5e050d24637865e9327408d
* Document last modified: 2024-10-08T20:52:06.000Z

</details>

**Comment by yisibl** [comment]
@estelle Can you add a new category in Browser compatibility to document its compatibility?

**Comment by yisibl** [comment]
I think the description in the [place-self](https://developer.mozilla.org/en-US/docs/Web/CSS/place-self) property needs to be updated as well.

**Comment by estelle** [comment]
> I think the description in the [place-self](https://developer.mozilla.org/en-US/docs/Web/CSS/place-self) property needs to be updated as well.

https://github.com/mdn/browser-compat-data/issues/24844
