### ISSUE TITLE
Confusing note about presentation attributes

### ISSUE THREAD

**Issue by page200** [mdn/content#36483]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointer-events

### What information was incorrect, unhelpful, or incomplete?

> As a presentation attribute [pointer-events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) can be used as a CSS property.

### What did you expect to see?

> Since pointer-events is a so-called [presentation attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute#presentation_attributes), there is also [a CSS property with the same name and purpose](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events).

### Do you have anything more you want to share?

Similarly in other articles.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/attribute/pointer-events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointer-events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/pointer-events/index.md
* Last commit: https://github.com/mdn/content/commit/a7615ee2f9e22946edff7633962bc1d9eee9e0ad
* Document last modified: 2024-07-25T22:03:15.000Z

</details>

**Comment by Josh-Cena** [comment]
How are they different? They mean the exact same thing to me.

**Comment by page200** [comment]
The current text has wrong grammar, uses "as" twice in a confusing way, the presentation attribute name links to the CSS property (they have the same name and purpose, but they aren't the same thing)...

**Comment by Josh-Cena** [comment]
The first part of the sentence, "As a presentation attribute," means that "`pointer-events` is a presentation attribute". As such, the same identifier called `pointer-events` can also be used as a CSS property. There's no grammar error. It's the same structure as "As a maintainer, I can approve changes to MDN".

The wording is concise but there's no room of ambiguity. You cannot possibly interpret it as anything other than "the same identifier `pointer-events` can be used as a CSS property". "All presentation attribute names are also CSS property names" is the rule to remember.

**Comment by page200** [comment]
If you don't understand my posts, as you wrote in your first post, it might be easier to let another maintainer handle this.

> the same identifier called `pointer-events` can also be used as a CSS property.

The text sounds like the presentation attribute (not the identifier) can be used as a CSS property.

And the hyperlink (that according to your statement should link to the identifier) doesn't link to the identifier nor to the presentation attribute, it links to the CSS property.

> It's the same structure as "As a maintainer, I can approve changes to MDN".

The current text has the same structure as "As a maintainer [missing comma] Josh-Cena (link to website of another person called Josh-Cena who isn't a maintainer but a medic) can work as a medic." In that universe, being a maintainer guarantees that there's an identically named medic, and the quoted text should convey that info, but doesn't.

**Comment by Josh-Cena** [comment]
> The current text sounds like the presentation attribute (not the identifier) can be used as a CSS property.

"An attribute can be used as a property" can't be interpreted in any sense other than "use the same key-value pair, but change the syntax so it makes sense in the given context". I doubt anyone would interpret that as:

```css
.my-elem {
  pointer-events="none"
}
```

The comma after "As..." is optional. It links to the CSS property because we are talking about it in that context. Again, if we want to be maximally verbose we would say "As a presentation attribute, `pointer-events` can be used as a CSS property, see the [`pointer-events`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) CSS property", but I don't think there's any other logical interpretation of the current text anyway.

**Comment by page200** [comment]
> "An attribute can be used as a property" can't be interpreted in any sense other than [...]

"An attribute can be used as a property" is incorrect. An attribute cannot be used as a CSS property. There is a CSS property with the same name and purpose, but it's not an attribute.

> It links to the CSS property because we are talking about it in that context.

"As a presentation attribute" isn't talking about a CSS property, it's talking about a presentation attribute.

Using two "as" is confusing.

The current text has the same structure as "As a maintainer Josh-Cena (link to website of another person called Josh-Cena who isn't a maintainer but a TV presenter) can make a TV programme about web development [i.e. achieve the same goal, namely that people will be informed, but through a different mechanism]." In that universe, being a maintainer guarantees that there's an identically named TV presenter, and the quoted text should convey that info, but doesn't.

**Comment by page200** [comment]
Why is this fix not planned?

**Comment by hamishwillee** [comment]
@Josh-Cena Fixed this in #38203 - standardizing the text like this:

> As a presentation attribute, `Xxxxx` also has a CSS property counterpart: {{cssxref("Xxxxx")}}. When both are specified, the CSS property takes priority.
