### ISSUE TITLE
`top` and `left` is supported in Firefox >= 109

### ISSUE THREAD

**Issue by danny0838** [mdn/content#36509]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create

### What specific section or headline is this issue about?

parameters

### What information was incorrect, unhelpful, or incomplete?

The description of `top` and `left` says `In Firefox, this value currently is ignored for popups (bug 1271047) but can be set using browser.windows.update().`

### What did you expect to see?

The issue should be applied only for Firefox < 109.

### Do you have any supporting links, references, or citations?

[Bug 1271047](https://bugzilla.mozilla.org/show_bug.cgi?id=1271047)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/windows/create`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/windows/create/index.md
* Last commit: https://github.com/mdn/content/commit/b8a0743ca8b1e1b1b1a95cc93a4413c020f11262
* Document last modified: 2024-09-01T17:04:58.000Z

</details>

**Comment by Piyush-r-bhaskar** [comment]
Hi @danny0838 

I would like to express my interest in working on this issue. If possible, could you assign this task to me?

Could you please guide me on how to locate this mdn page in github.
![image](https://github.com/user-attachments/assets/c004178e-7f7e-445a-bf14-0685dd2b3b29)


Thank You 😊

**Comment by hamishwillee** [comment]
@Piyush-r-bhaskar FYI we don't assign issues anymore - you start the issue, and at the end of the description add text `Fixes #36509`. That will cross link to this issue and make it clear to others that you are working on it.

**Comment by Piyush-r-bhaskar** [comment]
Perfect 🙂
