### ISSUE TITLE
[JavaScript] Ship Uint8Array to/from base64 and hex

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#36547]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Features to document

https://github.com/tc39/proposal-arraybuffer-base64

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1917885 (and meta https://bugzilla.mozilla.org/show_bug.cgi?id=1862220)

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by hamishwillee** [comment]
@Josh-Cena You probably already have hidden docs for https://github.com/tc39/proposal-arraybuffer-base64 right? Can you take that on? Shipping in FF133

**Comment by Josh-Cena** [comment]
Beat you to it! => https://github.com/mdn/content/pull/36387

**Comment by Josh-Cena** [comment]
Would appreciate if you can fill in the BCD though, there's probably also Safari data to track and I got lazy.

**Comment by hamishwillee** [comment]
@Josh-Cena Sure can re BCD! Glad you sorted this.

**Comment by Rumyra** [comment]
Collector is here https://github.com/mdn/browser-compat-data/pull/24863
