### ISSUE TITLE
Lack of links to documents for download

### ISSUE THREAD

**Issue by xiaolinggnb** [mdn/content#36568]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids

### What specific section or headline is this issue about?

Nesting grids and subgrid

### What information was incorrect, unhelpful, or incomplete?

The chapter does not provide the corresponding file download links and `see it live` section, 2 examples are not, which is a bit incongruous with the previous, although clicking on the sample code of the `play` can be found in the source code, I do not know whether there is an omission

### What did you expect to see?

It is recommended to add the file download link and `see it live` content, in line with the previous documentation.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/css_layout/grids`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/grids/index.md
* Last commit: https://github.com/mdn/content/commit/44b18841ff739fbf1a5450805d85f839fa3e68a5
* Document last modified: 2024-07-25T20:16:09.000Z

</details>

**Comment by xiaolinggnb** [comment]
Like these 2 files, I copied the code from the Doc's play area, but not saw them on the github repo.
[Grids.zip](https://github.com/user-attachments/files/17567413/Grids.zip)

**Comment by bsmth** [comment]
>I did review your docs carefully, and it seems there isn’t a prompt mentioning that the complete code can be viewed in the playground. 

I'm adding this wherever appropriate now so that it's easier to figure out how to view and edit the complete source for the live samples. Thank you and I hope that helps!
