### ISSUE TITLE
Browser compatibility table reports two time the same "partitioned property" 

### ISSUE THREAD

**Issue by daniele-orlando** [mdn/content#36592]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CookieChangeEvent

### What specific section or headline is this issue about?

Browser compatibility table

### What information was incorrect, unhelpful, or incomplete?

Browser compatibility table reports two time the same "partitioned property".

### What did you expect to see?

I would expect to see only one occurrence of the "partitioned property" record.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/cookiechangeevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CookieChangeEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/cookiechangeevent/index.md
* Last commit: https://github.com/mdn/content/commit/de4bd74771b88bb6352c1136b608811edf24ffda
* Document last modified: 2024-07-28T04:59:38.000Z

</details>

**Comment by Josh-Cena** [comment]
This is working as intended. If you look closely these entries are indented, indicating that they are subfeature of `changed` and `deleted` respectively.
