### ISSUE TITLE
Issue with "WAI-ARIA basics": …

### ISSUE THREAD

**Issue by thierryk** [mdn/content#366]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Accessibility/WAI-ARIA_basics

#### What information was incorrect, unhelpful, or incomplete?

The article suggests that an element with `role=tablist` **_contains_** the tabs of a tab panel. 

#### Specific section or headline?

> New roles — tablist, tab, tabpanel — these identify the important areas of the tabbed interface — the container for the tabs, the tabs themselves, and the corresponding tabpanels.

#### What did you expect to see?

New roles — tablist, tab, tabpanel — these identify the important areas of the tabbed interface — the container for the tabs *(or the container used for referencing the tabs)*, the tabs themselves, and the corresponding tabpanels.

#### Did you test this? If so, how?

Using "skip links" for tabs is not mandatory to create a tab panel. A `tablist` can be empty as long as it references the tabs via `aria-owns`. For example:
```html
<div role="tablist" aria-owns="tpw-0-0-t tpw-0-1-t tpw-0-2-t tpw-0-3-t"></div> 
```

Here is a live example: https://tabpanelwidget.com

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/accessibility/wai-aria_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Accessibility/WAI-ARIA_basics
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/accessibility/wai-aria_basics/index.html
* Report started: 2020-12-17T05:01:10.260Z

</details>

**Comment by chrisdavidmills** [comment]
To whoever fixes this, you need to update the description as suggested.

**Comment by thierryk** [comment]
@chrisdavidmills if you're ok with my *description*, I can do the PR

**Comment by chrisdavidmills** [comment]
@thierryk I'd be happy for you to do so. Assigning; thanks!

**Comment by thierryk** [comment]
@chrisdavidmills As far as I know, there is no example of tabpanel using **empty** `tablist` in the wild (apart from http://tabpanelwidget.com).
Let me know if you think I should link to it as an example.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills As far as I know, there is no example of tabpanel using **empty** `tablist` in the wild (apart from http://tabpanelwidget.com).
> Let me know if you think I should link to it as an example.

Yes, that sounds like a good idea to me.

**Comment by thierryk** [comment]
Oops, I should not have mentioned this issue in my "own" PR (that was not the plan).

Here is the PR that was supposed to close this issue: https://github.com/mdn/content/pull/3235

**Comment by thierryk** [comment]
Reopening to keep it open until #3235 goes through.
