### ISSUE TITLE
Outdated spec link

### ISSUE THREAD

**Issue by calebfoss** [mdn/content#36601]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/XPath/Introduction_to_using_XPath_in_JavaScript

### What specific section or headline is this issue about?

Introduction

### What information was incorrect, unhelpful, or incomplete?

The link [DOM 3 XPath](https://www.w3.org/TR/2004/NOTE-DOM-Level-3-XPath-20040226/) points to a spec page with a red dialog that pops up reading
> This version is outdated!
and linking to [the current version](https://www.w3.org/TR/DOM-Level-3-XPath/)

### What did you expect to see?

the current version](https://www.w3.org/TR/DOM-Level-3-XPath/) of the spec page

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/xpath/introduction_to_using_xpath_in_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/XPath/Introduction_to_using_XPath_in_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/xpath/introduction_to_using_xpath_in_javascript/index.md
* Last commit: https://github.com/mdn/content/commit/bea339d321513fc6d66d95c8f0305b9387fa57bb
* Document last modified: 2024-10-25T23:05:38.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting. The PR that fixes this ended up removing the link completely instead up pointing to https://www.w3.org/TR/DOM-Level-3-XPath/
