### ISSUE TITLE
Lexical Grammar - ID_Start not applied to _ or $

### ISSUE THREAD

**Issue by sidewayss** [mdn/content#36610]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#identifiers

### What specific section or headline is this issue about?

#identifiers

### What information was incorrect, unhelpful, or incomplete?

This is not an issue with the page so much as an issue in the page it links to, or the Unicode chars themselves.  This was the only place I could find to call it out.  This section of this page links [here](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5Cp%7BID_Start%7D). That page on util.unicode.org filters unicode chars using `\p{ID_Start}`, but it does not include `_` or `$` in the results.

Is there another place to report this?  Is it not a bug and something that the MDN docs page should mention?  Is it a non-issue?

### What did you expect to see?

I expect to see `_` or `$` in the search results.

**Comment by Josh-Cena** [comment]
Why should _ and $ be ID_Start? Are you proposing to change the Unicode spec, or do you just believe it's a bug with the util?

Our page already says they are not ID_Start, which is why we have to use `[$_\p{ID_Start}]`.

**Comment by sidewayss** [comment]
The page says:
> In JavaScript, identifiers are commonly made of alphanumeric characters, underscores (_), and dollar signs ($). Identifiers are not allowed to start with numbers. However, JavaScript identifiers are not only limited to [ASCII](https://developer.mozilla.org/en-US/docs/Glossary/ASCII) — many Unicode code points are allowed as well. Namely, any character in the [ID_Start](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5Cp%7BID_Start%7D) category can start an identifier, while any character in the [ID_Continue](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5Cp%7BID_Continue%7D) category can appear after the first character.

Yes, it mentions _ and $, but I inferred that all of the valid start characters would be in ID_Start.  Maybe that's my personal inference, but IMO the docs page implies it.

**Comment by sidewayss** [comment]
Feel free to close this if I'm making a pointless fuss.

**Comment by sidewayss** [comment]
To sum up: I would suggest clarifying that _ and $ are not in ID_Start.  I can submit the PR if you agree.  Otherwise go ahead and close this.

**Comment by Josh-Cena** [comment]
Yes, a note clarifying that _ and $ are valid in identifier start but are not ID_Start won't hurt, and similarly for U+200C (ZWNJ) and U+200D (ZWJ) w.r.t. ID_Continue. As to why, I'm not sure, probably because Unicode only intends to include things that look like words:

> The formal syntax provided here captures the general intent that an identifier consists of a string of characters beginning with a letter or an ideograph, and followed by any number of letters, ideographs, digits, or underscores. It provides a definition of identifiers that is guaranteed to be backward compatible with each successive release of Unicode, but also adds any appropriate new Unicode characters.

**Comment by sidewayss** [comment]
If the why is not clear, then I'll leave it out.  Or maybe just say is that JavaScript uses ID_Start and ID_Continue, but adds to them for its own purposes.  I'll try to post the PR later today.  Thanks.

**Comment by sidewayss** [comment]
I created this PR: #36619 and all checks have passed.
