### ISSUE TITLE
Error on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

### ISSUE THREAD

**Issue by jemandy** [mdn/content#36627]
On page https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base ,
I believe the following to be incorrect.  

> In-page anchors
> 
> Links pointing to a fragment in the document — e.g. `<a href="#some-id">` — are resolved with the `<base>`, triggering an HTTP request to the base URL with the fragment attached.
> 
> For example, given `<base href="https://example.com/">` and this link:` <a href="#anchor">To anchor</a>`. The link points to https://example.com/#anchor.

I believe that fragment-only href's are unaffected by the base element, that `<a href="#anchor">` will link internally to an anchor in the document in which it occurs.  If given `<base href="https://example.com/">` in the document at https://elpmaxe.com/, then I believe `<a href="#anchor">` will link to `https://elpmaxe.com/#anchor` , not `https://examplecom/#anchor` .

Disclaimer: i am not an HTML Standard expert.

**Comment by Josh-Cena** [comment]
You are saying an explicit note is wrong, which in itself is very unlikely. I also cannot reproduce it. Try the following HTML:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <base href="https://example.com/">
</head>
<body>
  <a href="#foo">To anchor</a>
</body>
</html>
```

It opens the page at `https://example.com/#foo`.

If you have evidence suggesting otherwise, we are happy to investigate further.
