### ISSUE TITLE
Issue with "<input type="checkbox">": (short summary here please)

### ISSUE THREAD

**Issue by sayax** [mdn/content#3662]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

#### What information was incorrect, unhelpful, or incomplete?
Please provide additional information about checkbox

input type checkbox has 2 more attributes, such as:
true-value=""
false-value=""

#### What did you expect to see?
information about true-value and false-value

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/checkbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/checkbox/index.html
* Last commit: https://github.com/mdn/content/commit/4c33fc2919a9523a76430bfe1427e6af2f122b2f
* Document last modified: 2021-03-23T09:09:06.000Z

</details>

**Comment by chrisdavidmills** [comment]
@sayax I can't find any evidence of these attributes existing; they don't appear in the WHATWG spec. Where are you finding this information? Are they browser-specific extensions maybe?

**Comment by sayax** [comment]
> @sayax I can't find any evidence of these attributes existing; they don't appear in the WHATWG spec. Where are you finding this information? Are they browser-specific extensions maybe?

i found it in an issue and checked in a browser (works on chrome opera safari) myself
<input
        type="checkbox"
        name="checkbox"
        true-value="yes"
        false-value="no"
      >
      
emitted value on checked is yes, on unchecked is no
so i thought i should report it here

**Comment by chrisdavidmills** [comment]
@sayax I can't seem to get this to work in any browser, nor can I find any information about them on the web. Can you send me the issue you mentioned? Is this a framework-specific feature?

**Comment by sayax** [comment]
Closing this issue due to inaccuracy, this was framework specific feature
