### ISSUE TITLE
oklch typo in note

### ISSUE THREAD

**Issue by magicdawn** [mdn/content#36669]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch

### What specific section or headline is this issue about?

Values

### What information was incorrect, unhelpful, or incomplete?

![image](https://github.com/user-attachments/assets/e160074e-3920-4d55-aef3-eb158aff0926)

### What did you expect to see?

- we can define lightness with number 0-1 `oklch(0.1 0 0)`
- we can define lightness with percentage 0%-100% `oklch(10% 0 0)`
- when used in relative colors: `l` is a number (0-1 inclusive)

so I don't understand where the note means `Here 100% is equal to the number 100 for the L value and 0.4 for the C value.` ?

----

and I have tested the L value

![image](https://github.com/user-attachments/assets/f082fae3-70af-4836-8cb0-1e76d33540c8)
![image](https://github.com/user-attachments/assets/f624dc76-d5b6-4879-9008-2557081fa8bc)

![image](https://github.com/user-attachments/assets/da389fb1-8565-4ec1-91c5-4e6ff36f1a1d)
![image](https://github.com/user-attachments/assets/7501cde8-ef4b-4218-a514-40ac68a0e406)

---

So I believe this note is obselete and should be removed. and add to `hsl` since relative hsl `100 is equivalent to 100%.` https://drafts.csswg.org/css-color-5/#relative-HSL

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/color_value/oklch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/color_value/oklch/index.md
* Last commit: https://github.com/mdn/content/commit/71a0a05c518c3a4c2588f4c7e256b02605550295
* Document last modified: 2024-10-17T19:17:21.000Z

</details>

**Comment by Josh-Cena** [comment]
This was just added in https://github.com/mdn/content/pull/33048, so I don't think it's obsolete, likely just a misunderstanding. @estelle?

**Comment by estelle** [comment]
The note was incorrect.

L is a `<number>` that corresponds to the Lightness; 1.0 is equivalent to 100%.

C is a `<number>` that corresponds to the chroma. 0.4 is equivalent to 100%.

H is a `<number>` that corresponds to the hue, in degrees, normalized to a [0, 360] range. 90 is equivalent to 90deg.

alpha is a `<number>` that corresponds to the alpha transparency. 1.0 is equivalent to 100%.

Fixed in #36682
