### ISSUE TITLE
PBKDF2 is dropped from deriveKey algorithm parameter

### ISSUE THREAD

**Issue by bschick** [mdn/content#36708]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey

### What specific section or headline is this issue about?

Parameters

### What information was incorrect, unhelpful, or incomplete?

PBKDF2 is a valid algorithm for derviceKey, but it was dropped from the documentation in https://github.com/mdn/content/pull/34989 (presumably by mistake).

### What did you expect to see?

The algorithm parameter should include a bullet containing:

> - For [PBKDF2](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey#pbkdf2), pass a [Pbkdf2Params](https://developer.mozilla.org/en-US/docs/Web/API/Pbkdf2Params) object.

### Do you have any supporting links, references, or citations?

[Example](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey#pbkdf2_derive_aes_key_from_password) on this page show how a key is derived with the PBKDF2 algorithm.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/subtlecrypto/derivekey`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/subtlecrypto/derivekey/index.md
* Last commit: https://github.com/mdn/content/commit/00f46adb5616d826821d63b11eac285faf1cf4a5
* Document last modified: 2024-10-16T07:58:28.000Z

</details>

**Comment by Josh-Cena** [comment]
@hamishwillee could confirm

**Comment by hamishwillee** [comment]
Yes, does look like I deleted it by mistake. Looks like @wbamberg is sorting it out in #36719. Thanks for posting.
