### ISSUE TITLE
Simple Way to View Firefox Cookies - a one-liner, e.g. Firefox > Hamburger  > Settings > Privacy & Sec > etc.... simples !

### ISSUE THREAD

**Issue by mick9** [mdn/content#36709]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

### What specific section or headline is this issue about?

Simple Way to View Firefox Cookies - a one-liner, e.g. Firefox > Hamburger  > Settings > Privacy & Sec > etc.... simples !

### What information was incorrect, unhelpful, or incomplete?

All advice found on the web is too complex, buried, obscure, obyuse, written leaving too much work to do.

### What did you expect to see?

Something like a one-liner as the answer to my question e.g.:
Firefox > Hamburger  > Settings > Privacy & Sec > etc..etc... simples !

### Do you have any supporting links, references, or citations?

https://duckduckgo.com/?hps=1&q=how+to+view+cookies+in+Firefox&atb=v402-1&ia=web
Direct Answer: To view cookies in Firefox, follow these steps:
    Open the Firefox browser and navigate to the website that you want to view the cookies for.
    Press Ctrl + Shift + I (Windows/Linux) or Command + Option + I (Mac) to open the Developer Tools.
    In the Developer Tools, click on the Storage tab.
    In the Storage tab, click on the Cookies button.
    You will see a list of cookies stored for the website. You can sort the list by Name, Domain, Path, Size, and Created.
... too complicated

### Do you have anything more you want to share?

A simple answer could be (for example):
ctr-alt-c > f1
... simples  !

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/cookies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cookies/index.md
* Last commit: https://github.com/mdn/content/commit/aece74ade419cfba12136025c0c5275b093ab082
* Document last modified: 2024-10-23T12:50:22.000Z

</details>

**Comment by bsmth** [comment]
Thanks for raising this one! There's a note here on the page already: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#data_storage

>To see stored cookies (and other storage that a web page is using) you can use the [Storage Inspector](https://firefox-source-docs.mozilla.org/devtools-user/storage_inspector/index.html) in Firefox Developer Tools, or the [Application panel](https://developer.chrome.com/docs/devtools/progressive-web-apps) in Chrome Developer Tools.

I think this is okay to link to Firefox source documentation in this case instead of saying which menus to open (because this often changes), the source docs have a better chance at staying up-to-date. I would close this for now. Thanks a lot! :)

**Comment by mick9** [comment]
Thank you :)
