### ISSUE TITLE
Tags within the title element, whose their content are converted to strings rather than ignored.

### ISSUE THREAD

**Issue by liuxuelian** [mdn/content#36702]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLTitleElement/text

### What information was incorrect, unhelpful, or incomplete?

I open this native page in Chrome, Firefox browser, their representations are the same.
<img width="270" alt="image" src="https://github.com/user-attachments/assets/e5b02212-500b-49a9-89ab-57a851b910d3">

### What did you expect to see?

"tags within the element and their content are converted to strings."

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmltitleelement/text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLTitleElement/text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmltitleelement/text/index.md
* Last commit: https://github.com/mdn/content/commit/7cc15fff0f1284ece460597b9717ca20350a1fa9
* Document last modified: 2023-12-26T10:28:50.000Z

</details>

**Comment by Josh-Cena** [comment]
Both this and the `<title>` page need fixing. `<title>` does not accept non-text children, so in fact anything that even looks like HTML tags are in fact just pure text content.

**Comment by liuxuelian** [comment]
And [HTML elements reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#document_metadata) page also needs to be fixed.
