### ISSUE TITLE
color-mix() examples not W3C compliant

### ISSUE THREAD

**Issue by rupumped** [mdn/content#36714]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The example CSS provided in the Examples section of the color-mix article is not W3C compliant.

Copy:
```
li:nth-child(1) {
  background-color: color-mix(in oklab, #a71e14 0%, white);
}

li:nth-child(2) {
  background-color: color-mix(in oklab, #a71e14 25%, white);
}

li:nth-child(3) {
  background-color: color-mix(in oklab, #a71e14 50%, white);
}

li:nth-child(4) {
  background-color: color-mix(in oklab, #a71e14 75%, white);
}

li:nth-child(5) {
  background-color: color-mix(in oklab, #a71e14 100%, white);
}

li:nth-child(6) {
  background-color: color-mix(in oklab, #a71e14, white);
}
```
into [W3C's Nu HTML checker](https://validator.w3.org/nu/#textarea), making sure to select "CSS."

The validator finds six errors, one for each instance of color-mix. For example:
`background-color`:` color-mix(in oklab,#a71e14 0%,white)` is not a `background-color` value.

### What did you expect to see?

The validator should output "Document checking completed. No errors or warnings to show."

### Do you have anything more you want to share?

Despite not passing the validation checker, it does work as expected in browser. I wonder if this is a problem with the validation checker.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/color_value/color-mix`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/color_value/color-mix/index.md
* Last commit: https://github.com/mdn/content/commit/bc3edf4e334c7d804b513d086ba733e6e045c322
* Document last modified: 2024-09-28T23:34:04.000Z

</details>

**Comment by Josh-Cena** [comment]
All of these conform to the formal syntax, so the only logical conclusion is that the validator's CSS parser is too old and does not parse this.
