### ISSUE TITLE
The autocomplete nickname is not working in Google Chrome.

### ISSUE THREAD

**Issue by amirfarzamnia** [mdn/content#36715]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

### What specific section or headline is this issue about?

This documentation says that we can use "nickname" as the value of the "autocomplete" attribute in HTML inputs.

### What information was incorrect, unhelpful, or incomplete?

This documentation states that "nickname" can be used as a value for the `autocomplete` attribute in HTML input fields. However, when I try the following code:

```html
<input type="text" autocomplete="nickname">
```

Google Chrome's developer console displays an error, indicating that this `autocomplete` value is invalid.

### What did you expect to see?

I expected this value to work without triggering an issue.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes/autocomplete`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/autocomplete/index.md
* Last commit: https://github.com/mdn/content/commit/06b418a190b8e4a46682ab706d14984e7db34862
* Document last modified: 2024-09-11T03:36:25.000Z

</details>

**Comment by amirfarzamnia** [comment]
![image](https://github.com/user-attachments/assets/63aa5772-2fb8-4733-b0be-0d0f1cc7eedb)
![image](https://github.com/user-attachments/assets/3386dac9-f4b6-46ac-8e26-9bc8d1070612)

**Comment by estelle** [comment]
It's in the spec: see the list of values #3: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls:-the-autocomplete-attribute

**Comment by caugner** [comment]
Thank you, this was already reported in https://github.com/mdn/browser-compat-data/issues/20827, so I'm closing this issue as a duplicate. What we would typically do in this case is to add a BCD-subfeature to capture that this value is not supported in Chrome.

@amirfarzamnia Did you have a chance and check if the feature works in Firefox and/or Safari?

**Comment by amirfarzamnia** [comment]
> Thank you, this was already reported in [mdn/browser-compat-data#20827](https://github.com/mdn/browser-compat-data/issues/20827), so I'm closing this issue as a duplicate. What we would typically do in this case is to add a BCD-subfeature to capture that this value is not supported in Chrome.
> 
> @amirfarzamnia Did you have a chance and check if the feature works in Firefox and/or Safari?

Unfortunately not.
