### ISSUE TITLE
Inconsistent min-height (prose vs code)

### ISSUE THREAD

**Issue by felixrabe** [mdn/content#36725]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS

### What specific section or headline is this issue about?

min- and max- sizes

### What information was incorrect, unhelpful, or incomplete?

While text says `150 pixels` in relation to `min-height`, the code example reads:

```
min-height: 100px;
```

### What did you expect to see?

Consistent number for text and code, either 100px or 150px.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/sizing_items_in_css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/sizing_items_in_css/index.md
* Last commit: https://github.com/mdn/content/commit/033285c99a8e1bc05b646ff19b70d2e8b86dff46
* Document last modified: 2024-11-07T11:59:36.000Z

</details>

**Comment by bsmth** [comment]
Thanks! The examples have had some minor tweaks recently, and the prose needs to be updated to reflect that.

**Comment by bsmth** [comment]
Fixed in https://github.com/mdn/content/pull/36729
