### ISSUE TITLE
Issue with "alarms": Missing details about execution context

### ISSUE THREAD

**Issue by Juraj-Masiar** [mdn/content#3672]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/alarms

#### What information was incorrect, unhelpful, or incomplete?
The documentation is a bit vague about execution context - are alarms global for whole extension or for the execution context only? If I create one in background script, will the `onAlarm` handler fire in extension tab or in content script (and vice versa)? Is it even accessible in content scripts?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/alarms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/alarms
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/alarms/index.html
* Last commit: https://github.com/mdn/content/commit/b3eebddc4c3a897597e3602655d596eed67851b6
* Document last modified: 2021-01-29T09:29:22.000Z

</details>

**Comment by rpl** [comment]
> The documentation is a bit vague about execution context - are alarms global for whole extension or for the execution context only? If I create one in background script, will the `onAlarm` handler fire in extension tab or in content script (and vice versa)? Is it even accessible in content scripts?

- the alarms registered are associated to the whole extension (e.g. any extension page can call the alarms API method to manage the registered alarms and subscribe an onAlarm event listener), consistently to most of the WebExtensions API
- the alarms API is not available to content script (but it is available in any extension page, e.g. extension page tab / background page / popup page / sidebar page etc), the subset of the APIs available to the content scripts are described in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#webextension_apis

**Comment by Juraj-Masiar** [comment]
Thanks Luca!
I will add this info to the docs later today.
