### ISSUE TITLE
rgb only required 3 values

### ISSUE THREAD

**Issue by BrotherBlazzard** [mdn/content#36743]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class

### What specific section or headline is this issue about?

background declaration within the .editorial CSS rule

### What information was incorrect, unhelpful, or incomplete?

background: rgb(255, 0, 0, 0.25);

### What did you expect to see?

background: rgba(255, 0, 0, 0.25);

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/class`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/class/index.md
* Last commit: https://github.com/mdn/content/commit/ddc0d10f9df181bd034e99b9a93488ee47414dfd
* Document last modified: 2024-08-15T05:21:40.000Z

</details>

**Comment by Josh-Cena** [comment]
`rgb()` is preferred over `rgba()` and they mean exactly the same. See https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb.
