### ISSUE TITLE
Issue with "WebGL best practices": requestPostAnimationFrame not available in browsers

### ISSUE THREAD

**Issue by mmarczell-graphisoft** [mdn/content#3675]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices

#### What information was incorrect, unhelpful, or incomplete?
The page advises that non-trivial WebGL apps should use `requestPostAnimationFrame`. However AFAIK no browser supports this API, the spec is not even completed yet. While Googling I've bumped into mentions of a polyfill, however the only polyfill I've found was this ([found here](https://hackmd.io/@jgilbert/WebGLBestPractices))
```
if (!window.requestPostAnimationFrame) {
   window.requestPostAnimationFrame = function(task) {
      requestAnimationFrame(() => {
         setTimeout(task, 0);
      });
   }
}
```
and this seems so simple it raises the question: does this really do what this API should or is it just a rough approximation, with none of the performance characteristics of the real thing, until real support comes to browsers?

All in all I think the best practices guide should either not recommend an API that's not available yet, or provide a link to a trusted polyfill with discussion on how closely it emulates the real thing.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#use_requestpostanimationframe_not_requestanimationframe

#### What did you expect to see?
Immediately actionable unambiguous advice.

#### Did you test this? If so, how?
I've confirmed that the API is not available in Chrome, Firefox or Safari.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl_api/webgl_best_practices`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/webgl_best_practices/index.html
* Last commit: https://github.com/mdn/content/commit/56d9a678477f0e79232caa8169114519bf02a44a
* Document last modified: 2021-02-19T19:41:18.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for this. Good point. Fixed by @sideshowbarker in #11085
