### ISSUE TITLE
typo in status options code

### ISSUE THREAD

**Issue by thedavedrop** [mdn/content#36816]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_BookInstance_form

### What specific section or headline is this issue about?

bookinstance.js code sample

### What information was incorrect, unhelpful, or incomplete?

had "option(value=val*)= val" in two spots

### What did you expect to see?

needs to be "option(value=val*) #{val}" for the combo box options to display properly

### Do you have anything more you want to share?

this tutorial is AWESOME!!!  thank you so much for creating and hosting it!  i have learned a TON!!!

-dave

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_bookinstance_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_BookInstance_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_bookinstance_form/index.md
* Last commit: https://github.com/mdn/content/commit/8d5440dbd259fd6eea32b4f4a200f25257d1bf41
* Document last modified: 2024-07-27T04:44:44.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you, but that is incorrect and the existing code works fine - see  the test project https://github.com/mdn/express-locallibrary-tutorial

This change should not work, because it removes the text from the options that are displayed - i.e. you render as 
```
<option value="Maintenance" id="val"></option>
```

rather than

```
<option value="Maintenance">Maintenance</option>
```

I suspect your original code is wrong - the code in MDN does not have `"option(value=val*)= val"` - i.e. note the missing `*` below

```
    div.form-group
      label(for='status') Status:
      select#status.form-control(name='status' required)
        option(value='') --Please select a status--
        each val in ['Maintenance', 'Available', 'Loaned', 'Reserved']
          if undefined===bookinstance || bookinstance.status!=val
            option(value=val)= val
          else
            option(value=val selected)= val
```
