### ISSUE TITLE
WebCodecs API is widely supported

### ISSUE THREAD

**Issue by quinton-ashley** [mdn/content#36829]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder

### What specific section or headline is this issue about?

Baseline support banner info is incorrect

### What information was incorrect, unhelpful, or incomplete?

Baseline support banner info says "Limited Availability" yet the compatibility table shows widely available support among all major browsers except Firefox for Android. 

### What did you expect to see?

Baseline support banner should state "Widely Available". Firefox should be marked as having some support and Safari should be fully checked green.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/videoencoder`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/videoencoder/index.md
* Last commit: https://github.com/mdn/content/commit/3789de65bd11453c4cb24625723f81a7e8fcdd56
* Document last modified: 2024-05-08T04:36:35.000Z

</details>

**Comment by quinton-ashley** [comment]
I just saw on https://caniuse.com/webcodecs that Safari only has video encoding support and there seems to be some issues with WebCodecs in desktop Firefox, maybe the "limited availability" status is correct for now.

**Comment by skyclouds2001** [comment]
> I just saw on https://caniuse.com/webcodecs that Safari only has video encoding support and there seems to be some issues with WebCodecs in desktop Firefox, maybe the "limited availability" status is correct for now.

Agree

**Comment by LeoMcA** [comment]
Thanks for filing, but Firefox for Android support is required for a feature to be Baseline: closing this issue.
