### ISSUE TITLE
[CSS] Unclear that the new `src(…)` function has (very) limited availability

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/content#36831]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/url_value

### What information was incorrect, unhelpful, or incomplete?

It is unclear that the new [`src(…)` function](https://drafts.csswg.org/css-values/#url-value) is still unsupported in any major browser, and <https://github.com/mdn/browser-compat-data/pull/25081> was closed.

### What did you expect to see?

That the new `src(…)` function is marked as having limited to no availability.

### Do you have any supporting links, references, or citations?

* **Spec URL:** https://drafts.csswg.org/css-values/#urls
* **Firefox bug:** [Bug 1707923 - [css‑values] Support the `src()` function in the CSS `<url>` type](https://bugzil.la/1707923)
* **`@mdn/browser‑compat‑data` PR:** <https://github.com/mdn/browser-compat-data/pull/25081>

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/url_value`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/url_value
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/url_value/index.md
* Last commit: https://github.com/mdn/content/commit/5178e1e7c9edf0c9c652275ae62f090042ce2422
* Document last modified: 2024-09-04T23:29:15.000Z

</details>

**Comment by wbamberg** [comment]
> with a separate note that says "there's a url() alternative called src() that has the exact same functionality but slightly different syntax, but it's not implemented anywhere".

I'm not sure we should even do this, since that isn't actionable information.

**Comment by Josh-Cena** [comment]
Yes but:

1. That's the reason why we have `<url>` and `url()` as separate entities so it gives context and rationale
2. At some point people would definitely say "you are missing something from the spec" so we should preempt that question

**Comment by OnkarRuikar** [comment]
If no browser has implemented it, then, as per our policy, shouldn't we just remove it from the content?
It is mentioned only on two pages, 4 times in total. The syntax section is also manually crafted.

**Comment by wbamberg** [comment]
> At some point people would definitely say "you are missing something from the spec" so we should preempt that question

People say this about other things that aren't implemented, and our answer is always the same: we don't document things that aren't implemented. Why is this different?

**Comment by wbamberg** [comment]
> That's the reason why we have <url> and url() as separate entities so it gives context and rationale

Maybe this is enough of a reason. IDK. I don't think omitting `src()` is too bad for this, but I suppose that's a matter of opinion.
