### ISSUE TITLE
Issue with "Making PWAs work offline with Service workers": error in code, missing async

### ISSUE THREAD

**Issue by DegrangeM** [mdn/content#3684]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers

The code in `clearing the cache` section (https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers#clearing_the_cache) produce the following error :

`Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules`

The line triggering the error is 
```javascript
await caches.delete(key);
```

Replacing 

```javascript
await Promise.all(keyList.map((key) => {
```

 with

```javascript
await Promise.all(keyList.map(async (key) => {
```

seems to fix the error.

However as I am not an expert with promise and async things I let you double check if there is really an error and if it's the right fix.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/progressive_web_apps/offline_service_workers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/offline_service_workers/index.html
* Last commit: https://github.com/mdn/content/commit/a82bd45f5612a917a5e90584fcd30b43b096c4ce
* Document last modified: 2021-03-05T07:20:21.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. I couldn’t see any good reason for using `await` in that example code at all, so in https://github.com/mdn/content/pull/3706, I replaced the code with a simpler rewrite that achieves the same thing without using `await` at all — like this:

```js
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keyList) => {
    Promise.all(keyList.map((key) => {
      if (key === cacheName) { return; }
      caches.delete(key);
    }))
  })());
});
```
That also seems more readable than the `await`-based code that’s in the article now.
