### ISSUE TITLE
Code on this page is wrong and buggy

### ISSUE THREAD

**Issue by mukuld** [mdn/content#36867]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_building_practice

### What specific section or headline is this issue about?

The provided code

### What information was incorrect, unhelpful, or incomplete?

The code is simply wrong. The working version of the code on Github pages is completely different the the code provided on this page.

Having incorrect code hurts people who rely on these pages to learn the language and can turn them away.

### What did you expect to see?

Working and correct code.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/object_building_practice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_building_practice
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/object_building_practice/index.md
* Last commit: https://github.com/mdn/content/commit/bc0d0d1ef796435e969f6d65c7e5d3c08f4023aa
* Document last modified: 2024-07-25T21:20:22.000Z

</details>

**Comment by Josh-Cena** [comment]
The code on GitHub is outdated; the code in content represents the most up-to-date version. We could update all the learning area code to accurately mirror content but that's a huge effort; instead, recently, we are starting to remove externally hosted code if applicable. In the meantime, if you want to make a PR to learning-area to update the code there instead, you are very welcome to.
