### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Xyncgas** [mdn/content#3691]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

#### What information was incorrect, unhelpful, or incomplete?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching/http_cache_type.png
For the description in the picture for local cache, CACH was spelled instead of CACHE

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/caching`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/caching/index.html
* Last commit: https://github.com/mdn/content/commit/48fca0c614add538e95f1075b2777fc396023d31
* Document last modified: 2021-03-16T07:50:01.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/3699 with a fix.
