### ISSUE TITLE
XMLHttpRequest "Receiving binary data in older browsers" section contains spammy link in code sample

### ISSUE THREAD

**Issue by broofa** [mdn/content#36924]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Sending_and_Receiving_Binary_Data

### What specific section or headline is this issue about?

Code sample containing a link [in comment] to http://mgran.blogspot.com

### What information was incorrect, unhelpful, or incomplete?

"http://mgran.blogspot.com" now goes to a (turkish?) spam site ☹️ 

### What did you expect to see?

At a minimum the "http://mgran.blogspot.com"  should be removed.

... but at this point maybe just remove the whole "Receiving binary data in older browsers" section?   The article it's based on is almost 20 years old, and the `XMLHttpRequest#responseType` property (which is the preferred solution, right?) has been [broadly supported for over a decade](https://caniuse.com/mdn-api_xmlhttprequest_responsetype).

I.e. the population of readers that will find this section of use is probably vanishingly small at this point.

### Do you have any supporting links, references, or citations?

https://web.archive.org/web/20070716163515/http://mgran.blogspot.com/2006_08_01_archive.html

**Comment by bsmth** [comment]
Thanks for flagging. I think it's a good idea to remove the whole section. We could keep the archive.org link in 'See also' in case that's of historic interest, but generally I agree.

- responseType compat https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType#browser_compatibility
