### ISSUE TITLE
`mdn.svg` files not loading

### ISSUE THREAD

**Issue by joshuanianji** [mdn/content#36935]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/object-position

### What information was incorrect, unhelpful, or incomplete?

The MDN logos do not load under Examples > Positioning Image Content. Not sure if this is a result of the build process, since the images load locally.

This is what the page looks like right now (I'm using firefox)

<img width="1464" alt="Screenshot 2024-11-22 at 8 01 34 PM" src="https://github.com/user-attachments/assets/887976b4-a5a4-4379-83ca-48b85ee22f5e">

### What did you expect to see?

This is what it looks like locally:

<img width="1457" alt="Screenshot 2024-11-22 at 8 03 51 PM" src="https://github.com/user-attachments/assets/e02a0746-5547-4f4f-8ce5-ee544308ba56">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/object-position`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/object-position
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/object-position/index.md
* Last commit: https://github.com/mdn/content/commit/fc1cc5684c98d19816d5cc81702d70f2a0debbad
* Document last modified: 2024-07-26T14:35:43.000Z

</details>

**Comment by Ashish-CodeJourney** [comment]
Not sure what is the exact reason behind 
It's working locally

when I opened https://developer.mozilla.org/en-US/docs/Web/CSS/object-position for the first time it said that 
`https://interactive-examples.mdn.mozilla.net/pages/css/object-position.html is unreachable.`
after refreshing 2-3 times it worked 
I closed the browser and opened it again
same behavior again.

**Comment by wbamberg** [comment]
Thanks for filing! This was a regression in the MDN platform, fixed now.
