### ISSUE TITLE
The NOTE has MM Instead of EM

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#37007]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning

### What specific section or headline is this issue about?

Introducing top, bottom, left, and right

### What information was incorrect, unhelpful, or incomplete?

In the NOTE (see below) under the heading  has MM instead of EM. I made the text bold to make it easier to spot.

**Note**: The values of these properties can take any units you'd reasonably expect: pixels, **mm**, rems, %, etc.

### What did you expect to see?

I expected EM instead of MM with the other options of pixel, rems, percentage, etc.

### Do you have any supporting links, references, or citations?

nope

### Do you have anything more you want to share?

nope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/css_layout/positioning`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/positioning/index.md
* Last commit: https://github.com/mdn/content/commit/44b18841ff739fbf1a5450805d85f839fa3e68a5
* Document last modified: 2024-07-25T20:16:09.000Z

</details>

**Comment by Josh-Cena** [comment]
`mm` is an [absolute length unit](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#absolute_length_units) used as an example. `em` would be slightly duplicative with `rem`, so it's not wrong for us to continue to use `mm`.

**Comment by jfc3-dol** [comment]
Thanks, didn't realize MM (Millimeters) was an option absolute length unit.
