### ISSUE TITLE
Content bug: Link to closed survey

### ISSUE THREAD

**Issue by ninofiliu** [mdn/content#3701]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

## Specific page section or heading?

This part

> TC39 is working on Temporal, a new Date/Time API.
Read more about it on the Igalia blog and fill out the survey. It needs real-world feedback from web developers, but is not yet ready for production use!

## What is the problem?

The link to the survey points to a closed survey. Maybe it should be deleted altogether? I don't know if the survey is gonna reopen but I guess it won't

If this should be deleted, I'd be happy to to the fix PR, [I'm familiar w/ the flow](https://github.com/mdn/content/pull/1207) :)

**Comment by chrisdavidmills** [comment]
> The link to the survey points to a closed survey. Maybe it should be deleted altogether? I don't know if the survey is gonna reopen but I guess it won't

I think the blog post is still useful, but we should delete the link to the survey off our page.

> If this should be deleted, I'd be happy to to the fix PR, I'm familiar w/ the flow :)

Yes please @ninofiliu !
