### ISSUE TITLE
Example on page about async iterators instead demonstrates a sync iterator.

### ISSUE THREAD

**Issue by Hexstream** [mdn/content#37048]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncIterator/Symbol.asyncIterator

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

The example demonstrates a sync iterator instead of an async iterator.

### What did you expect to see?

An example demonstrating an async iterator.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/asynciterator/symbol.asynciterator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncIterator/Symbol.asyncIterator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/asynciterator/symbol.asynciterator/index.md
* Last commit: https://github.com/mdn/content/commit/6fbdb78c1362fae31fbd545f4b2d9c51987a6bca
* Document last modified: 2024-07-15T11:50:05.000Z

</details>

**Comment by Josh-Cena** [comment]
There should be no interactive example on this page. Welcoming PRs to remove it.

**Comment by Hexstream** [comment]
Very well, but I'm too busy to onboard myself for that kind of contribution, so I'll leave the glory to someone else. :)

**Comment by Hexstream** [comment]
@Josh-Cena @jolka-ef Thank you both!

(It took a while for the live page to update, I expected a nearly instantaneous update...)
