### ISSUE TITLE
Issue with "TimeRanges": normalized TimeRanges can be empty

### ISSUE THREAD

**Issue by abdwalfa** [mdn/content#3705]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TimeRanges

#### What information was incorrect, unhelpful, or incomplete?

> The term "[normalized TimeRanges object](https://www.w3.org/TR/html52/semantics-embedded-content.html#normalized-timeranges-object)" indicates that ranges in such an object are ordered, don't overlap, **aren't empty**, and don't touch (adjacent ranges are folded into one bigger range).

but according to the [spec](https://www.w3.org/TR/html52/semantics-embedded-content.html#normalized-timeranges-object) which is referenced on the same line, this is incorrect:

> In other words, the ranges in such an object are ordered, don’t overlap, and don’t touch (adjacent ranges are folded into one bigger range). **A range can be empty** (referencing just a single moment in time)

#### What did you expect to see?
remove the incorrect info and maybe add this line:
> The term "normalized TimeRanges object" indicates that ranges in such an object are ordered, don't overlap, and don't touch (adjacent ranges are folded into one bigger range) **but they can be empty.**

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/timeranges`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TimeRanges
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/timeranges/index.html
* Last commit: https://github.com/mdn/content/commit/da549aa60ae6b86acbb6cde16cdbb0613338ae31
* Document last modified: 2021-02-10T18:04:37.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/3708 with a fix.
