### ISSUE TITLE
`Object.hasOwn()`: incorrect baseline date availability

### ISSUE THREAD

**Issue by rakleed** [mdn/content#37064]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn

### What specific section or headline is this issue about?

Baseline

### What information was incorrect, unhelpful, or incomplete?

It’s been available across browsers since July 2015.

### What did you expect to see?

It’s been available across browsers since March 2022.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn#browser_compatibility - Safari

### Do you have anything more you want to share?

I could not find any mention of the year in https://github.com/mdn/browser-compat-data and https://github.com/web-platform-dx/web-features, only browser versions are indicated there.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/hasown`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/hasown/index.md
* Last commit: https://github.com/mdn/content/commit/fb85334ffa4a2c88d209b1074909bee0e0abd57a
* Document last modified: 2023-09-25T07:33:31.000Z

</details>

**Comment by Josh-Cena** [comment]
Baseline dates are computed in groups, and this one has been attributed to the "object" group, here: https://github.com/web-platform-dx/web-features/blob/eae1f06f186a83d004c125d90856498ce3d9f726/features/object-object.yml.dist#L306 so it does not reflect the support of the specific method itself. This is discussed in https://github.com/mdn/yari/issues/11546.
