### ISSUE TITLE
[BUG] Why Chrome have limited support

### ISSUE THREAD

**Issue by jcubic** [mdn/content#37080]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture

### What specific section or headline is this issue about?

Baseline

### What information was incorrect, unhelpful, or incomplete?

Baseline says that Edge fully support this API, but Chrome don't support it. Something is off. Both browsers are based on the same project. As seen on the chart.

### What did you expect to see?

Chrome to support the API

### Do you have any supporting links, references, or citations?

The chart at the bottom of the page

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/screen_capture_api/using_screen_capture`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
* Last commit: https://github.com/mdn/content/commit/4f35a8237ee0842beb9cfef3354e05464ad7ce1a
* Document last modified: 2024-07-26T03:46:04.000Z

</details>

**Comment by Josh-Cena** [comment]
Chrome is unsupported because it's not supported on Chrome Android. Edge on the other hand has no separately recorded mobile distribution.
