### ISSUE TITLE
SVG/Attribute/x - example

### ISSUE THREAD

**Issue by DomOBU** [mdn/content#37099]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x#use

### What information was incorrect, unhelpful, or incomplete?

Hello,

Is the example provided with the `use` element the correct example?
It seems more appropriate for the `rect` element.

Kind regards

### What did you expect to see?

Taking this information into account if it is relevant

**Comment by bsmth** [comment]
I had a look and I think the current doc is correct, the example at the bottom of the page is talking about x coordinate in a rect:

```svg
<rect x="220" y="20" width="60" height="60" fill="red" />
```

And the `<use>` section is talking about what `x` controls in a `<use>` element:

```svg
<use href="#myCircle" x="10" fill="blue" />
```

Does that make sense or have I misunderstood?

**Comment by himanshugarg** [comment]
> we are in a ‘use’ paragraph and that ‘use’ is not mentioned in the example and that only ‘rect’ is mentioned.

Yes, that's the sense I got too. However if `Examples` stands independently this PR could be declined. Thanks

**Comment by bsmth** [comment]
No problem. The structure of the page is:

* Elements
  * `feblend`
  * `fecolormatrix`
  * …
  * `use`
* Examples

Where **examples** picks a common / straightforward element to display, so I'm not sure what to fix there. Let me know if that clears it up or if you think there's still something wrong. TY!

**Comment by bsmth** [comment]
I'm going to close this, but if I've made a mistake, reply and let me know! Thanks!
