### ISSUE TITLE
should 1st code fragment include link to ./webgl.css ?

### ISSUE THREAD

**Issue by fwmc** [mdn/content#37097]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context

### What specific section or headline is this issue about?

Including the glMatrix library

### What information was incorrect, unhelpful, or incomplete?

    <link rel="stylesheet" href="./webgl.css" type="text/css" />

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webgl_api/tutorial/adding_2d_content_to_a_webgl_context`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/tutorial/adding_2d_content_to_a_webgl_context/index.md
* Last commit: https://github.com/mdn/content/commit/9a4005caa5cc13f5174e3b8981eeec5631ed83d1
* Document last modified: 2024-10-28T12:46:03.000Z

</details>

**Comment by wbamberg** [comment]
Yeah, I think this `<link>` line should be removed. I reworked these pages in https://github.com/mdn/content/pull/22564, and the corresponding code in https://github.com/mdn/dom-examples/pull/187.

In https://github.com/mdn/dom-examples/pull/187 I removed the inclusions of `webgl.css` in the code (as noted in the description for that PR) but I probably missed it in this page.

**Comment by wbamberg** [comment]
Good catch! If you'd like to file a PR to remove that line, I'll merge it :)

**Comment by caugner** [comment]
Fixed via https://github.com/mdn/content/pull/37125.
