### ISSUE TITLE
Major Documentation Oversight -- What is MDN?

### ISSUE THREAD

**Issue by vwheeler63** [mdn/content#37109]
### MDN URL

https://developer.mozilla.org/en-US/

### What specific section or headline is this issue about?

Landing Page and About Page

### What information was incorrect, unhelpful, or incomplete?

This issue is about information that is MISSING.

Specifically, I am a 32-veteran software and firmware developer (new at web development), and wanted to learn some more details about CSS (psuedo-elements and psuedo-classes and anchor-positioning), and ran into the MDN website.

The first question I asked is:

- "What is MDN?"
- Then "What does M D and N stand for?"

This should be answered by the very first sentence readable on the page (or at least very near the top).  (A positively *great* example of this is [here](https://developer.mozilla.org/en-US/docs/Web/CSS), about CSS, which immediately answers both questions.)  But it is not answered anywhere on the page, and it is also not answered in the [About Page](https://developer.mozilla.org/en-US/about) nor in the [README document](https://github.com/mdn/content/blob/main/README.md).

5 minutes later and I STILL had not found out what MDN stood for!  (I guessed because of the similarity to "MSDN", but I still don't know if I guessed correctly, though I did find mention of the word "Developer" after the word "formerly" after I had dug far enough to find the GitHub hosting repository for the website's content.) 

This is kind of a big oversight considering answering the question, "What is it?" is the first place a new reader goes mentally, because it answers for him/her, "Why could this website be valuable to me?".

The basic questions all documentation should answer IMMEDIATELY (especially when hosted on-line) are (because the reader wants to know "Is this the place I should be looking to answer my current question?"):

1. What is it?
2. What does it do?
3. Why does it exist?

in broad terms, in order to orient the new reader.

And I am very glad the content of this website is hosted on GitHub!  *Thank you for that!*

### What did you expect to see?

The answers to the above basic 3 questions.

### Do you have any supporting links, references, or citations?

http://crystal-clear-research.com/code_documentation/

### Do you have anything more you want to share?

Thank you for being here on GitHub!  What a nice choice given that "many heads are better than one"!  :-)

**Comment by Rumyra** [comment]
Hi @vwheeler63 thank you for the suggestion!

We recently launched a new 'About' page which explains MDN https://developer.mozilla.org/en-US/about and are looking at further updates to make this information more prominent moving forward 👍

**Comment by vwheeler63** [comment]
Hi, Ruth!  ( @Rumyra )  Sounds and looks awesome!
