### ISSUE TITLE
[ko] Update kumascript related to secureContext

### ISSUE THREAD

**Issue by ohprettyhak** [mdn/content#37108]
### Summary

Many documents use `secureContext_header` and `secureContext_inline`, but they have not been translated into Korean.

### URL

https://developer.mozilla.org/ko/docs/Web/API/PushSubscription (secureContext_header)
https://developer.mozilla.org/ko/docs/Web/API/Clipboard_API (secureContext_inline)

### Reproduction steps

1. Navigate any Korean-translated documents using a security context header or badge.

### Expected behavior

The text related to the security context should be shown in Korean.

For Header: `이 기능은 일부 또는 모든 지원 브라우저의 보안 컨텍스트 (HTTPS)에서만 사용할 수 있습니다.`
For Badge: `이 기능은 보안 컨텍스트 (HTTPS)에서만 사용할 수 있습니다`

### Actual behavior

Currently, the text related to the security context is shown in English.

For Header:  `This feature is available only in secure contexts (HTTPS), in some or all supporting browsers.`
For Badge:  `This feature is available only in secure contexts (HTTPS)`

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Android

#### 1) header
<img width="600" alt="image" src="https://github.com/user-attachments/assets/f92526c3-35e9-4a8f-b84a-60809f17fef8">

#### 2) badge
<img width="428" alt="image" src="https://github.com/user-attachments/assets/d6840883-5a2b-4fa2-baf0-d47183e24d7b">

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by ohprettyhak** [comment]
@argl If the `L10n-Template.json` file is updated, should I understand that Yari's KumaScript gets automatically updated as well?

**Comment by argl** [comment]
This comes at an unfortunate point in time, since we are in the process of changing out a huge part of our rendering pipeline from yari to the new [rari](https://github.com/mdn/rari) system. The new rari code uses the json file mentioned above, the deprecated yari code uses `kumascript/secureContext_header.ejs`. I would opt to go with the future implementation, thats is why I transferred this ticket to `content`. Content is also where those translations ultimately should be managed, that is the reason for the change.

I expect rari to be rolled out before the end of the year.

**Comment by ohprettyhak** [comment]
> This comes at an unfortunate point in time, since we are in the process of changing out a huge part of our rendering pipeline from yari to the new [rari](https://github.com/mdn/rari) system. The new rari code uses the json file mentioned above, the deprecated yari code uses `kumascript/secureContext_header.ejs`. I would opt to go with the future implementation, thats is why I transferred this ticket to `content`. Content is also where those translations ultimately should be managed, that is the reason for the change.
> 
> I expect rari to be rolled out before the end of the year.

Thank you for the explanation. I will add the translations to the JSON file and submit a new Merge Request.
