### ISSUE TITLE
Regular expressions Modifier: (?ims-ims:...) #Matching certain words case-insensitively

### ISSUE THREAD

**Issue by Invalid-Username404** [mdn/content#37113]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Modifier

### What specific section or headline is this issue about?

Matching certain words case-insensitively

### What information was incorrect, unhelpful, or incomplete?

const pattern = /(?:var|let|const) (?i:foo|bar)\b/i;

pattern.test("let foo;"); // true
pattern.test("const BAR = 1;"); // true
pattern.test("Let foo be a number"); // false

### What did you expect to see?

The "-" after the first "?" is missing which turned into a non-capturing group.
const pattern = /(?-i:var|let|const) (?i:foo|bar)\b/i;

pattern.test("let foo;"); // true
pattern.test("const BAR = 1;"); // true
pattern.test("Let foo be a number"); // false

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/regular_expressions/modifier`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Modifier
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/regular_expressions/modifier/index.md
* Last commit: https://github.com/mdn/content/commit/cd0230e0a3ee63fdf289d7eef37301002fa2345e
* Document last modified: 2024-10-19T01:08:14.000Z

</details>

**Comment by Josh-Cena** [comment]
Great job being the first to discover this typo (which I've noticed for a while but never fixed it)! However, my typo was because I added `i` to the flag list—we should remove that. The first group is actually intended to be a non-capturing group.

**Comment by Invalid-Username404** [comment]
Thank you for the clarification. I noticed some issues in the JavaScript reference and apologize for not reporting them.
