### ISSUE TITLE
Examples are Broken (Empty White Box)

### ISSUE THREAD

**Issue by machineghost** [mdn/content#37126]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

### What specific section or headline is this issue about?

All of the examples

### What information was incorrect, unhelpful, or incomplete?

The examples display nothing.

### What did you expect to see?

Example dialogs (from the code it looked like they had a button in them).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/dialog/index.md
* Last commit: https://github.com/mdn/content/commit/d2421d25d1676cc11b01cc4981061e4d0aa78e95
* Document last modified: 2024-10-29T20:01:28.000Z

</details>

**Comment by Josh-Cena** [comment]
I cannot reproduce this, and while we receive many reports about dialog examples not working (most recently https://github.com/mdn/content/issues/37132), I have never seen anyone else complaining that everything is blank. It is likely your privacy configuration or network. You can look at the devtools console and see if there are any connection errors or blocked warnings.
