### ISSUE TITLE
some pages of chinese version  lost in web development part

### ISSUE THREAD

**Issue by Hercules11** [mdn/content#3712]
https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types
https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls
https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes

**Comment by sideshowbarker** [comment]
@mdn/yari-content-zh

**Comment by t7yang** [comment]
Translation is contribute by community, this is not a issue at all.

@Hercules11 you can submit your translation for those articles if you like.
Repo for translation is [mdn/translated-content](https://github.com/mdn/translated-content).

@sideshowbarker this is safe to closed.

**Comment by sideshowbarker** [comment]
Thanks @t7yang
