### ISSUE TITLE
Content suggestion: Guide info on Polyfill section placement in relation to others

### ISSUE THREAD

**Issue by AdrianSkar** [mdn/content#3714]
## What is the new suggestion?

Include some info on the guidelines on where to position Polyfill sections (couldn't find any). 

## Why is it important or useful?
For instance, the [DOMContentLoaded event](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event) page [shows it](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event#polyfill) before [the examples](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event#examples) while having it below (less use cases?) would make more sense, especially considering Polyfill sections usually take a significant amount of space.

**Comment by chrisdavidmills** [comment]
@AdrianSkar we've wanted to get rid of polyfills on MDN for quite some time, as evidenced by this thread: https://discourse.mozilla.org/t/mdn-rfc-001-mdn-wiki-pages-shouldnt-be-a-distributor-of-polyfills/24500

Basically, it is too much work to maintain polyfill code for a large number of features, on top of all the other work we have to do.

An ideal alternative would be to agree on a standard way of linking to an external service that would provide polyfills.

**Comment by AdrianSkar** [comment]
> 
> 
> @AdrianSkar we've wanted to get rid of polyfills on MDN for quite some time, as evidenced by this thread: https://discourse.mozilla.org/t/mdn-rfc-001-mdn-wiki-pages-shouldnt-be-a-distributor-of-polyfills/24500
> 
> Basically, it is too much work to maintain polyfill code for a large number of features, on top of all the other work we have to do.
> 
> An ideal alternative would be to agree on a standard way of linking to an external service that would provide polyfills.

I agree. So I guess further related contributions (like changing their placement) are better postponed until and agreement is reached on that thread?
Thank you.

**Comment by chrisdavidmills** [comment]
> I agree. So I guess further related contributions (like changing their placement) are better postponed until and agreement is reached on that thread?

Yes, I'd say so.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/3714#issuecomment-811740510
