### ISSUE TITLE
SameSite behaviour incorrectly described in the Security/Practical Implementation Guide for cookies

### ISSUE THREAD

**Issue by social-anthrax** [mdn/content#37154]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Cookies

### What specific section or headline is this issue about?

SameSite description does not match with "Using HTTP Cookies"

### What information was incorrect, unhelpful, or incomplete?

The Same-Site description lists that Cookies are omitted in same-origin contexts (e.g. navigating a.example.com to b.example.com). This conflicts with the information in the [Cookies MDN page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#controlling_third-party_cookies_with_samesite) and in [PortSwigger's SameSite blog post](https://portswigger.net/web-security/csrf/bypassing-samesite-restrictions). 

### What did you expect to see?

I would expect for this behaviour to not be listed as an example.

### Do you have any supporting links, references, or citations?

- https://portswigger.net/web-security/csrf/bypassing-samesite-restrictions
- https://gist.github.com/oscarychen/4a6568da34817fc2ba98a5068da5ec70#cookie-attributes
- https://security.stackexchange.com/a/223477
- https://www.thinktecture.com/en/identityserver/samesite-cookies-in-a-nutshell/

### Do you have anything more you want to share?

N/A

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/security/practical_implementation_guides/cookies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Cookies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/security/practical_implementation_guides/cookies/index.md
* Last commit: https://github.com/mdn/content/commit/5c000c8621145c6915f3d545b505c216317bc64a
* Document last modified: 2024-07-26T02:23:10.000Z

</details>

**Comment by wbamberg** [comment]
Yes, this seems to be wrong (surely all same-origin requests are by definition same-site requests). @chrisdavidmills , what do you think?

I'm also not sure how SameSite protects against clickjacking. I thought with clickjacking, the user is clicking on the target site, so it will be same-site?

We also have a definition of [site](https://developer.mozilla.org/en-US/docs/Glossary/Site) that is helpful in places we have to talk about same-site, it would be good to link that.

**Comment by social-anthrax** [comment]
Yes, afaik all same-origin requests are same site requests given site is normally defined as the eTLD+1 taking into consideration the [Public Suffix List](https://publicsuffix.org/), whilst the origin is normally used to describe the full domain. 

For your second point, if you have same-site strict it should only send cookies if you're referred to the site from the same site, meaning if you click on a link the referrer should be the attacker webpage rather than the vulnerable site.

**Comment by wbamberg** [comment]
> For your second point, if you have same-site strict it should only send cookies if you're referred to the site from the same site, meaning if you click on a link the referrer should be the attacker webpage rather than the vulnerable site.

Oh I see, thank you! https://javascript.info/clickjacking#samesite-cookie-attribute has more on this. We should probably explain this more, too, but that could be a different issue.
