### ISSUE TITLE
Array.prototype.every() check returns true on an empty array

### ISSUE THREAD

**Issue by marciamoss** [mdn/content#37150]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every

### What specific section or headline is this issue about?

Array.prototype.every()

### What information was incorrect, unhelpful, or incomplete?

When array is empty the check returns true for any condition

### What did you expect to see?

I would expect a false if there are no elements to satisfy the condition.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/every`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/every/index.md
* Last commit: https://github.com/mdn/content/commit/57375b77984037c614982a9327bc96101824db89
* Document last modified: 2023-11-27T08:17:23.000Z

</details>

**Comment by Josh-Cena** [comment]
This is already mentioned on this page.

> every acts like the "for all" quantifier in mathematics. In particular, for an empty array, it returns true. (It is [vacuously true](https://en.wikipedia.org/wiki/Vacuous_truth) that all elements of the [empty set](https://en.wikipedia.org/wiki/Empty_set#Properties) satisfy any given condition.)
