### ISSUE TITLE
Typos on `Trailing commas` page

### ISSUE THREAD

**Issue by Hexstream** [mdn/content#37181]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

### What specific section or headline is this issue about?

`Description` and `Trailing commas in literals`

### What information was incorrect, unhelpful, or incomplete?

`particular` should be `particularly`.

`arrays literals` should be `array literals`.

### What did you expect to see?

No typo.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/trailing_commas`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/trailing_commas/index.md
* Last commit: https://github.com/mdn/content/commit/eb7cf694c19b31ee8826f22eaac6c12e808b1e50
* Document last modified: 2024-08-19T18:20:37.000Z

</details>

**Comment by bsmth** [comment]
Hi there, thanks for reporting. Would you like to open a PR that fixes this?

**Comment by Hexstream** [comment]
Sorry, I'm too busy to onboard myself for that kind of contribution, [as previously said](https://github.com/mdn/content/issues/37048#issuecomment-2512332573).
