### ISSUE TITLE
Typo on `super` page: `seeked` should be `sought`.

### ISSUE THREAD

**Issue by Hexstream** [mdn/content#37214]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super

### What specific section or headline is this issue about?

Methods that read super.prop do not behave differently when bound to other objects

### What information was incorrect, unhelpful, or incomplete?

`seeked` should be `sought`.

### What did you expect to see?

No typo.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/super`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/super/index.md
* Last commit: https://github.com/mdn/content/commit/1492f12d54c344b099dc49fe291c24c8b41abd90
* Document last modified: 2024-09-19T16:23:30.000Z

</details>

**Comment by sujitmohanty** [comment]
Hi! I have just made a PR after fixing the typo.
