### ISSUE TITLE
space is more than just space

### ISSUE THREAD

**Issue by DNS-Leo** [mdn/content#37237]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Regex_character_class_escape_in_class_range

### What specific section or headline is this issue about?

Invalid cases

### What information was incorrect, unhelpful, or incomplete?

\s is a character class escape for whitespace

### What did you expect to see?

\s is a character class escape for whitespace, tabs and newlines.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/regex_character_class_escape_in_class_range`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Regex_character_class_escape_in_class_range
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/regex_character_class_escape_in_class_range/index.md
* Last commit: https://github.com/mdn/content/commit/6aaba8ce85edc3a92fd5e804002cc609c31ce73f
* Document last modified: 2024-07-17T02:35:13.000Z

</details>

**Comment by Josh-Cena** [comment]
All of the characters you mentioned are "whitespace". "Whitespace" is not the same as "space". See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Character_class_escape
