### ISSUE TITLE
ASP.NET is not a server-side web language, it is a web framework that supports the programming languages C#, F# and VB!

### ISSUE THREAD

**Issue by asadullahehsan** [mdn/content#37244]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript

### What specific section or headline is this issue about?

Server-side versus client-side code

### What information was incorrect, unhelpful, or incomplete?

In the documents it is written that:

> Examples of popular server-side web languages include PHP, Python, Ruby, ASP.NET, and even JavaScript!

ASP.NET is NOT a language. It is a web framework which is used to build web apps and services using .NET and C#.
If I make an analogy, ASP.NET is like Express.js framework, .NET SDK is like Node.js runtime, and C# is the programming language like JavaScript.

### What did you expect to see?

You may write C# instead of ASP.NET.

### Do you have any supporting links, references, or citations?

https://dotnet.microsoft.com/en-us/apps/aspnet
https://dotnet.microsoft.com/en-us/learn/dotnet/what-is-dotnet
https://dotnet.microsoft.com/en-us/languages/csharp

### Do you have anything more you want to share?

![ASP NET Core](https://github.com/user-attachments/assets/d307883f-e53e-4ef6-b324-0a1b93761439)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/what_is_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/what_is_javascript/index.md
* Last commit: https://github.com/mdn/content/commit/245715b48674c1729cb63417e4a27628e30ae28c
* Document last modified: 2024-08-03T13:26:37.000Z

</details>

**Comment by wbamberg** [comment]
It would also be fine IMO just to delete ASP.NET from the list, it doesn't aspire to be complete.

**Comment by asadullahehsan** [comment]
Okay, I will delete it.
