### ISSUE TITLE
Incomplete sentence on `Background Tasks API` page.

### ISSUE THREAD

**Issue by Hexstream** [mdn/content#37247]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API

### What specific section or headline is this issue about?

Adding text to the log

### What information was incorrect, unhelpful, or incomplete?

This sentence is incomplete (nonsensical) towards the end:

> `logFragment` will accumulate log entries until the next time `updateDisplay()` is called because the DOM for the changes.

This should probably be something like (just adding "is ready"):

> `logFragment` will accumulate log entries until the next time `updateDisplay()` is called because the DOM is ready for the changes.

### What did you expect to see?

A complete sentence.

### Do you have anything more you want to share?

Perhaps the preceding sentence could be fused with this one to avoid repeating `logFragment`?

> Then we append the new element to the end of the pseudo-DOM in `logFragment`, which will accumulate log entries until the next time `updateDisplay()` is called because the DOM is ready for the changes.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/background_tasks_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Background_Tasks_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/background_tasks_api/index.md
* Last commit: https://github.com/mdn/content/commit/be8f7f155a48e11b30c240f8731afb1845f85378
* Document last modified: 2024-07-26T03:28:38.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. Agreed. Fixed by #37283

**Comment by Hexstream** [comment]
Awesome, thanks!
