### ISSUE TITLE
Variable Fonts example code not matching description

### ISSUE THREAD

**Issue by matthewlst** [mdn/content#37243]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_fonts/Variable_fonts_guide

### What specific section or headline is this issue about?

"Example for a standard upright (Roman) font" and "Example for a font that contains only italics and no upright characters"

### What information was incorrect, unhelpful, or incomplete?

Each of these sections provides a sample @font-face definition and a description. The descriptions discuss `oblique 0deg` and `oblique 14deg` values, but I didn't see any such value in the sample code.

### What did you expect to see?

If the example is correct as-is (e.g., the oblique values are implied), the wording could be improved to clarify. Otherwise, the code block could be updated to add some code related to `oblique`, or the description altered to remove such references. 

### Do you have any supporting links, references, or citations?

It seems the descriptions were added in `796096b` without a change to the code.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_fonts/variable_fonts_guide`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_fonts/Variable_fonts_guide
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_fonts/variable_fonts_guide/index.md
* Last commit: https://github.com/mdn/content/commit/498b20f9027718a6873b85307e8a91e1a554d1e5
* Document last modified: 2024-12-12T21:39:43.000Z

</details>

**Comment by OnkarRuikar** [comment]
The example is correct as-is.  We meant to imply `font-style: oblique 0deg` and `font-style: oblique 0deg 20deg` are equivalent to `font-style: normal`. Submitted [a PR](https://github.com/mdn/content/pull/37258) to rephrase the sentences.
