### ISSUE TITLE
Web APIs breadcrumb navigation should place interfaces below APIs

### ISSUE THREAD

**Issue by scottdotweb** [mdn/content#37241]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document

### What information was incorrect, unhelpful, or incomplete?

The [`Document`](https://developer.mozilla.org/en-US/docs/Web/API/Document) interface is a subset of the [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model) API. However, both of them appear at the same level within the breadcrumb navigation:

* References > Web APIs > Document Object Model (DOM)
* References > Web APIs > Document

There's a link to the DOM section at the top of the left hand side navigation, but as soon as you scroll that it's no longer visible. Navigating from an interface to its parent API is common and this impedes that.

### What did you expect to see?

The breadcrumb navigation should present the full path to interfaces, accurately conveying their relationship to their parent API. In the case of `Document` that would be:

* References > Web APIs > Document Object Model (DOM) > Document

This would allow the parent API to be reachable by a single click at all times.

**Comment by Josh-Cena** [comment]
Hi, this is the architecture we've chosen: interfaces are siblings of API overviews, not subpages. The reason being, not all interfaces clearly belong to one API: `Navigator`, `Window`, `Element`, etc. often have properties that are defined by other specs, making the architecture extremely confusing if each interface has to belong to one interface.
