### ISSUE TITLE
Issue with "Location: reload()": forceReload parameter (archaeological context)

### ISSUE THREAD

**Issue by iyerusad** [mdn/content#3726]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Location/reload

#### What information was incorrect, unhelpful, or incomplete?
I am working on an older application and am trying to find more information about `location.reload(forceReload: true/false)`. Specifically when it disappeared.

It appears forceReload was a parameter previously handled by browsers. Reason for removal appears to be "[not being in the specification](https://stackoverflow.com/a/55127750)".

For archaeological/historical purposes, I was wondering if it was possible to have the historical context available.

#### Specific section or headline?
`See Also` section would of made sense. e.g.:

> See also:
> - The Location interface it belongs to.
> - Similar methods: Location.assign() and Location.replace().
> - **Deprecated:** location.reload(forceReload)

#### What did you expect to see?
Documentation of (now) deprecated parameter forceReload.
- [Extra nice] Browser matrix of up to when feature was supported
  - Alternatively, ballpark (or specific) date(s) when forceReload was removed from browser engines.
- [Nice to have] What replaced it?/Alternatives to achieve similar result e.g. `window.location.href = window.location.href`

#### Did you test this? If so, how?
n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/location/reload`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Location/reload
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/location/reload/index.html
* Last commit: https://github.com/mdn/content/commit/56d9a678477f0e79232caa8169114519bf02a44a
* Document last modified: 2021-02-19T19:41:18.000Z

</details>

**Comment by sideshowbarker** [comment]
I finally got around to writing up a change related to this issue — see #7492.
