### ISSUE TITLE
It’s called the “View Transition API”, not “View Transitions API”

### ISSUE THREAD

**Issue by bramus** [mdn/content#37265]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API

### What information was incorrect, unhelpful, or incomplete?

The API is called the View Transitions API, which you use to create View Transitions.

### What did you expect to see?

The correct name to be used

### Do you have any supporting links, references, or citations?

https://drafts.csswg.org/css-view-transitions-1/
https://developer.chrome.com/blog/view-transitions-misconceptions#naming-things

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/view_transitions_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/view_transitions_api/index.md
* Last commit: https://github.com/mdn/content/commit/c420b9b3126451f53d112afe33e007d6efdb605d
* Document last modified: 2024-10-25T22:00:44.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting, @bramus - there's a fix on the way in the linked PR

**Comment by bramus** [comment]
Thanks for the fast PR and merge!
