### ISSUE TITLE
content disappeared

### ISSUE THREAD

**Issue by WreckitJaden** [mdn/content#37280]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Introduction

### What specific section or headline is this issue about?

CSS Layout

### What information was incorrect, unhelpful, or incomplete?

I was working through the introduction to CSS Layout module. It is the first one in the module. I went to the washroom, came back, and the content I was just reading and taking notes on seems to have disappeared. Upon scrolling to the bottom of the page, I see that the module is probably being updated by MDN (it says last updated December 19th, 2024 aka today). 

Just confirming that the CSS layout module just received significant modifications so as to not think I am dreaming.

### What did you expect to see?

The _Introduction to CSS Layout_  article I was just working through

### Do you have any supporting links, references, or citations?

<img width="211" alt="Screenshot 2024-12-19 at 2 01 18 PM" src="https://github.com/user-attachments/assets/0b078519-094c-4d30-8578-41a900ad7803" />
<img width="322" alt="Screenshot 2024-12-19 at 2 01 31 PM" src="https://github.com/user-attachments/assets/f9d0a9de-ffe5-4e91-b9a1-d68bcfb15461" />
<img width="377" alt="Screenshot 2024-12-19 at 2 01 42 PM" src="https://github.com/user-attachments/assets/c812355a-91ad-43b3-bb69-4d52bc8e40f2" />

here are some of the images I took screenshots of for my notes. 

### Do you have anything more you want to share?

Very helpful notes folks, thanks for them. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn_web_development/core/css_layout/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn_web_development/core/css_layout/introduction/index.md
* Last commit: https://github.com/mdn/content/commit/5b20f5f4265f988f80f513db0e4b35c7e0cd70dc
* Document last modified: 2024-12-19T15:37:45.000Z

</details>

**Comment by bsmth** [comment]
Hi there, thanks a lot for reporting.

>Just confirming that the CSS layout module just received significant modifications so as to not think I am dreaming.

You are not dreaming, we just landed some large restructuring changes in the Learn Web Development section, and you were browsing the pages while this was being deployed. We are going to publish a blog post about the changes shortly and you can learn more about this move here: https://github.com/orgs/mdn/discussions/750

Apologies if this was confusing, and many thanks for checking that this was intentional 🙏🏻

**Comment by WreckitJaden** [comment]
Ok, good to know. Thank you and no worries.
