### ISSUE TITLE
CSS styling basics | "Handling conflicts" module no longer contains "Order of cascade layers" section

### ISSUE THREAD

**Issue by icouldbez1** [mdn/content#37290]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Handling_conflicts#order_of_cascade_layers

### What specific section or headline is this issue about?

CSS styling basics | Section "Order of cascade layers" in "Handling conflicts" module

### What information was incorrect, unhelpful, or incomplete?

Yesterday, I read "Cascade, specificity, and inheritance" module, which is now called ["Handling conflicts"](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Handling_conflicts), that introduced cascade layers with syntax and short example at the end before offering passing a test. Currently, corresponding "Order of cascade layers" section is absent. This section was also (and still is) referenced in ["Task 2"](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Cascade_tasks#task_2) of the skill test ["The Cascade"](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Cascade_tasks) because "Task 2" is all about `@layer`. Unfortunately, the link doesn't reach its desired destination due to absence of `#order_of_cascade_layers` ID in "Handling conflicts" module markup.

### What did you expect to see?

Presence of "Order of cascade layers" section in "Handling conflicts" module of "CSS styling basics".

### Do you have any supporting links, references, or citations?

- Module ["Handling conflicts](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Handling_conflicts)" that no longer has "Order of cascade layers" section.
- ["Task 2"](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Cascade_tasks#task_2) of skill test "Test your skills: The Cascade" which is referenced in [section](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Handling_conflicts#test_your_skills!) of module above .
- [Absent section](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Handling_conflicts#order_of_cascade_layers) that is referenced in the content of "Task 2".

I also include commit changes that affected it:
- [508-578 lines](https://github.com/mdn/content/commit/5b20f5f4265f988f80f513db0e4b35c7e0cd70dc#diff-5c3de3249fd6cda2a7c0eed5c9819b3c4feccde9fd34d19910dfa65bef183c71L508-L578) were removed which caused "Order of cascade layers" to disappear. 
- [71](https://github.com/mdn/content/commit/5b20f5f4265f988f80f513db0e4b35c7e0cd70dc#diff-36f8c428737f805af14799a394a9f49e4fa1ce241b1a01a9147e038244967efbR71) line that updates the link in "Task 2" which references currently absent section.

_Note: Due to commit size, browser takes some time to scroll to specified location._

### Do you have anything more you want to share?

"Handling conflicts" module references skill test.
![image](https://github.com/user-attachments/assets/2c4c140c-1e9b-49a7-9ead-ed2ec03975cf)

Skill test's "Task 2" references absent section of module above.
![image](https://github.com/user-attachments/assets/8f67766b-8ed8-42bd-b7a5-7af9096d6e4a)

Thanks!

**Comment by chrisdavidmills** [comment]
Thanks for reporting this, @icouldbez1! I've just submitted a PR that fixes the problem. Let me know if you think anything else needs to be done.
