### ISSUE TITLE
British spelling of words vs US spelling

### ISSUE THREAD

**Issue by nschonni** [mdn/content#373]
Wondering if words like:
- organise
- behaviour
- neighbour
- colour
- ...

As a Canadian these spellings make sense, but since the local is indicated as `en-US`, should the be changed to the US spelling?

**Comment by chrisdavidmills** [comment]
> As a Canadian these spellings make sense, but since the local is indicated as `en-US`, should the be changed to the US spelling?

Yes, they should.

**Comment by hamishwillee** [comment]
> Yes, they should.

Boo. Hiss.

**Comment by chrisdavidmills** [comment]
> > Yes, they should.
> 
> Boo. Hiss.

I don't make the rules. I just enforce them ;-)

(Disclaimer, for those who don't know: I'm a Brit...)

**Comment by hamishwillee** [comment]
Ha, just following orders eh? 

I'm going to close this as "answered".

**Comment by nschonni** [comment]
Fair enough, I was going to leave it open till there had been PRs for the various words, but that can be done either way

**Comment by hamishwillee** [comment]
Also fair enough @nschonni - feel free to reopen!

**Comment by nschonni** [comment]
I can't re-open something a maintainer closes :wink:

**Comment by Ryuno-Ki** [comment]
Bummer!
I really do love the British spelling.

(And be it to remind US people, that there are more people on the world than them :-D)

**Comment by himanshugarg** [comment]
> organise
> behaviour
> neighbour
> colour

The examples above do not appear in mdn/content except inside code, some nss release notes, or in style guides. Is there more to fix as part of this?

**Comment by hamishwillee** [comment]
Thanks @himanshugarg Good point.

We need mechanisms to stop them creeping back over time (added as a question to https://github.com/mdn/content/issues/10787). But yes, if they are fixed now we should close this.
