### ISSUE TITLE
Issue with "inputmode": Should probably discuss interaction with input type

### ISSUE THREAD

**Issue by alanhogan** [mdn/content#3732]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

#### What information was incorrect, unhelpful, or incomplete?

I didn’t see any reference on the page to `input type`, which also tends to have the effect described here. How do they interact?

#### Specific section or headline?

n/a

#### What did you expect to see?

Discussion and reference to `input type`

#### Did you test this? If so, how?

n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/global_attributes/inputmode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/inputmode/index.html
* Last commit: https://github.com/mdn/content/commit/de55fa4a8e01168166a58e3537d2ad6b94b0b8ab
* Document last modified: 2021-01-12T06:48:24.000Z

</details>

**Comment by Master613** [comment]
@alanhogan It does say that if a certain type of data is required, they should use the `type` attribute for that specific data

**Comment by sideshowbarker** [comment]
I’ve opened https://github.com/mdn/content/pull/11114 with a change that adds a clarifying paragraph.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
