### ISSUE TITLE
Suggestion about "WindowOrWorkerGlobalScope.setTimeout()": linking "mixin" to the "mixin" article in the glossary? 

### ISSUE THREAD

**Issue by 552020** [mdn/content#3735]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout

#### What information was incorrect, unhelpful, or incomplete?

It's highly probable that the JS-learner will read the word "mixin" for the first time in this article. 

Coming from "[Using Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises)" then you read "[Creating a Promise around an old callback API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#creating_a_promise_around_an_old_callback_api)", and then you read [setTimeout()](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout) function, where you find for the first time the concept "mixin".

#### Specific section or headline?

The very first sentence: "The setTimeout() method of the WindowOrWorkerGlobalScope **mixin** (and successor to Window.setTimeout()) sets a timer which executes a function or specified piece of code once the timer expires."

#### What did you expect to see?

It would be nice I guess if the word "mixin" had a link to: https://developer.mozilla.org/en-US/docs/Glossary/Mixin. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/windoworworkerglobalscope/settimeout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/windoworworkerglobalscope/settimeout/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/3740 with a fix
