### ISSUE TITLE
I found a possible typo

### ISSUE THREAD

**Issue by imnoahnovak** [mdn/content#37352]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API/Using_the_Permissions_API

### What specific section or headline is this issue about?

Typo on the first sentence under "The trouble with asking for permission..."

### What information was incorrect, unhelpful, or incomplete?

> Permissions on the Web **are a** necessary evil, but they are not much fun to deal with as developers.

### What did you expect to see?

> Permissions on the Web **aren't** necessary evil, but they are not much fun to deal with as developers.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API/Using_the_Permissions_API#the_trouble_with_asking_for_permission%E2%80%A6

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/permissions_api/using_the_permissions_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API/Using_the_Permissions_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/permissions_api/using_the_permissions_api/index.md
* Last commit: https://github.com/mdn/content/commit/3fde60e07c74ad4954a0c77fdd80958c7d07f088
* Document last modified: 2024-09-19T23:36:38.000Z

</details>

**Comment by Josh-Cena** [comment]
This is not a typo. "A necessary evil" means it's a pain but it's necessary for the sake of security.
