### ISSUE TITLE
Appendchild is working with multiple node elements

### ISSUE THREAD

**Issue by gomszab** [mdn/content#37358]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild

### What information was incorrect, unhelpful, or incomplete?

 The documentations mentioned "appendChild(aChild)" and we can call it only with one parameter, but the following code snipet is also working fine. "Note: Unlike this method, the [Element.append()](https://developer.mozilla.org/en-US/docs/Web/API/Element/append) method supports multiple arguments and appending strings. You can prefer using it if your node is an element." is a wrong note. It's tested on the latest Edge, Chrome, and FF.
 
 ```
form.appendChild(
        createInputField(form,"writer:","writer"),
        createInputField(form,"from: ", "from"),
        createInputField(form,"book1: ", "book1"),
        createInputField(form,"book2: ", "book2"),
    )```

### What did you expect to see?

```
appendChild(param1)
appendChild(param1, param2)
appendChild(param1, param2, /* …, */ paramN)
```
and the function can handle multiple parameters as the Element.append

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<!-- Do not make changes below this line -->
<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/node/appendchild`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/node/appendchild/index.md
* Last commit: https://github.com/mdn/content/commit/5f76b99045f87349ed030bbd6a3c2e43badb3c22
* Document last modified: 2024-11-22T16:43:48.000Z

</details>

**Comment by Josh-Cena** [comment]
Could you show a self-contained and runnable example?

**Comment by gomszab** [comment]
Sorry, I had a mistake.
I just made custom functions, and call them inside the function. In my custom functions I called the appendchild too, which appended my elements to the same component what I put to the function as a first parameter.
