### ISSUE TITLE
Issue with "NSPR functions": (short summary here please)

### ISSUE THREAD

**Issue by dominusmi** [mdn/content#3736]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Reference/NSPR_functions

#### What information was incorrect, unhelpful, or incomplete?
All the documentation links are broken

#### Specific section or headline?
-

#### What did you expect to see?
-

#### Did you test this? If so, how?
-

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/projects/nss/reference/nspr_functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Reference/NSPR_functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/projects/nss/reference/nspr_functions/index.html
* Last commit: https://github.com/mdn/content/commit/e7adae4c255ddbe6412a546794d12f746104b299
* Document last modified: 2021-03-24T11:41:35.000Z

</details>

**Comment by chrisdavidmills** [comment]
It doesn't look like any of those pages actually exist. This documentation is of low priority to the MDN team, so we won't be writing them any time soon, and in fact the NSS documentation is moving off MDN soon. So I'm closing this.
