### ISSUE TITLE
Issue with "counter-set": (What's difference between counter-set and counter-reset?)

### ISSUE THREAD

**Issue by MenaiAla** [mdn/content#3737]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/counter-set

#### What information was incorrect, unhelpful, or incomplete?

I've read about [counter-reset](https://developer.mozilla.org/en-US/docs/Web/CSS/counter-reset) and [counter-set](https://developer.mozilla.org/en-US/docs/Web/CSS/counter-set) and I just confused the difference between them.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/counter-set`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/counter-set
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/counter-set/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by rachelandrew** [comment]
Hi @MenaiAla, as the first line of `counter-set` mentions, it will "only create new counters if there isn't already a counter of the given name on the element."

Do you have an example of the problem that you have?

**Comment by sideshowbarker** [comment]
Closing for lack of response
