### ISSUE TITLE
Issue with "background-color": incorrect use of "transparent" vs "opaque"

### ISSUE THREAD

**Issue by bartvanandel** [mdn/content#3739]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-color

#### What information was incorrect, unhelpful, or incomplete?

In the examples, the alpha value is described as "transparent" but actually it should be "opaque", e.g., this comment is incorrect:
```css
background-color: hsla(50, 33%, 25%, 0.75);  /* 75% transparent */
```

I didn't look further but I suspect the same mistake can be found in other places where `rgba(...)` or `hsva(...)` etc are used.

#### Specific section or headline?

Examples

#### What did you expect to see?

```css
background-color: hsla(50, 33%, 25%, 0.75);  /* 75% opaque, i.e. 25% transparent */
```

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/background-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-color
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/background-color/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can work on this issue 👍
