### ISSUE TITLE
URL Examples

### ISSUE THREAD

**Issue by yatiraaja** [mdn/content#37455]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/URI

### What specific section or headline is this issue about?

URL Examples At The End of Article

### What information was incorrect, unhelpful, or incomplete?

The Examples at the end of the Article are Titled URL. There are a few URN's listed in the content so it should be titled URI.

### What did you expect to see?

URI instead of URL at the end of the section with heading Examples and titled URL

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/uri`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/URI
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/uri/index.md
* Last commit: https://github.com/mdn/content/commit/5b20f5f4265f988f80f513db0e4b35c7e0cd70dc
* Document last modified: 2024-12-19T15:37:45.000Z

</details>

**Comment by Josh-Cena** [comment]
Hi! "URL" is the code block language and it's the canonical identifier for strings that represent URLs. In fact, "URI" is no longer a concept. The WHATWG URL spec intends to unify everything as "URL" and obsolete the concept of "URI". As such, we would not be changing the code block language; rather, we would soon look into replacing all "URI" with "URL" on MDN.

**Comment by yatiraaja** [comment]
Happy New Year & Hi to everyone,

Thanks for the reply. Never anticipated one.
