### ISSUE TITLE
Issue with "Signaling and video calling": (short summary here please)

### ISSUE THREAD

**Issue by sebbes-at-deepgram** [mdn/content#3750]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling

#### What information was incorrect, unhelpful, or incomplete?
In the "Signaling transaction flow", the link to the big schema points to (https://media.prod.mdn.mozit.cloud/attachments/2016/01/27/12363/9d667775214ae0422fae606050f60c1e/WebRTC%20-%20Signaling%20Diagram.svg which is not the same as the schema being displayed.

#### Specific section or headline?
"Signaling transaction flow"

#### What did you expect to see?
A link to https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling/webrtc_-_signaling_diagram.svg

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webrtc_api/signaling_and_video_calling`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webrtc_api/signaling_and_video_calling/index.html
* Last commit: https://github.com/mdn/content/commit/48fca0c614add538e95f1075b2777fc396023d31
* Document last modified: 2021-03-16T07:50:01.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/3762 with a fix
