### ISSUE TITLE
Issue with "How do you upload your files to a web server?": (short summary here please)

### ISSUE THREAD

**Issue by chungnampark** [mdn/content#3751]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Upload_files_to_a_web_server

#### What information was incorrect, unhelpful, or incomplete?

I could not connect to the website(http://demozilla.examplehostingprovider.net).  
I assume that this is because the hosting provider (Example Hosting Provider) has turned into a commercial  entity after this article was written.  Am I right? 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/common_questions/upload_files_to_a_web_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Upload_files_to_a_web_server
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/upload_files_to_a_web_server/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by mformihir** [comment]
@chungnampark I believe the URL (http://demozilla.examplehostingprovider.net) is only listed for demonstration purposes. 

As the article mentions, 
> For this example, we'll suppose that our hosting provider (the service that will host our HTTP web server) is a fictitious company "Example Hosting Provider" whose URLs look like this: mypersonalwebsite.examplehostingprovider.net.

The hosting provider is a **fictitious company**. The article mentions the fictitious website as an example so that readers understand better. Usually, people buy personal domains which may look like this, for them, this example would help.

@sideshowbarker, please verify.

**Comment by hamishwillee** [comment]
@mformihir Is correct. The company isn't real. @chungnampark If you still find this confusing, or thing that other's might, we would accept a change to put that text "fictitious" in bold (or similar) to make it more obvious.

**Comment by mformihir** [comment]
@hamishwillee should I proceed with a pull request to make "fictitious" bold?

**Comment by hamishwillee** [comment]
@mformihir If you think it is confusing, then yes please (assuming you think that highlighting the word is sufficient). Thanks!

**Comment by chungnampark** [comment]
Thanks, guys, for your kind explanation!
