### ISSUE TITLE
Issue with "NotificationAction": Code example incorrect

### ISSUE THREAD

**Issue by githubber-pixel** [mdn/content#3753]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/NotificationAction

#### What information was incorrect, unhelpful, or incomplete?
The code example has `self.registration`, but registration is not a property of self.

#### Specific section or headline?
Example

#### What did you expect to see?
I don't exactly expect to see anything in particular, but I want to know the correct code.

#### Did you test this? If so, how?
I did test this to see if it worked or not.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/notificationaction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/NotificationAction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/notificationaction/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #11108 with a fix.
