### ISSUE TITLE
Issue with "Plugin Roadmap for Firefox": /en-US/docs/Plugins/Flash_Activation:_Browser_Comparison not found

### ISSUE THREAD

**Issue by grahamperrin** [mdn/content#3761]
MDN URL: https://developer.mozilla.org/en-US/docs/Plugins/Roadmap

#### What information was incorrect, unhelpful, or incomplete?

Reference to https://developer.mozilla.org/en-US/docs/Plugins/Flash_Activation:_Browser_Comparison

* not found

#### Specific section or headline?

https://github.com/mdn/content/commit/b1653ad891e52df521e11c85cbc7aaf80ba9980d#diff-6279703f10afa55f96b3063976ed58885c0a4ba8c6c4716d7f2577c18873fc9eR11

#### What did you expect to see?

Maybe an archived document. 

Here's a capture in the Wayback Machine: 

<https://web.archive.org/web/20210123190346/https://developer.mozilla.org/en-US/docs/Plugins/Flash_Activation:_Browser_Comparison>

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/plugins/roadmap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Plugins/Roadmap
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/plugins/roadmap/index.html
* Last commit: https://github.com/mdn/content/commit/c45665984d990171c7a1b269f0074c34ddfb3d02
* Document last modified: 2021-01-22T08:11:48.000Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting, @grahamperrin ! Removed in https://github.com/mdn/content/commit/566e300571c9ed1eaf92b7ce660cb19481d0a8fc

**Comment by grahamperrin** [comment]
Thank you
