### ISSUE TITLE
Issue with "font-weight": broken result in german version

### ISSUE THREAD

**Issue by behren** [mdn/content#3768]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight

#### What information was incorrect, unhelpful, or incomplete?
In the German version of the page, the example result is broken. It wants me to "open the embedded page in a new tab for security reasons" but the page can not be found: 

`Sorry, the page /de/docs/Web/CSS/font-weight/_samples_/Beispiele could not be found.`

#### Specific section or headline?
`Beispiel`

#### What did you expect to see?
The result of the example.

#### Did you test this? If so, how?
Yes, I tried to access the results with the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/font-weight`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-weight/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by chrisdavidmills** [comment]
Apologies, but we are not accepting changes to this locale right now; see https://github.com/mdn/translated-content#tier-1-locales for an explanation of which locales are currently active, and why. https://github.com/mdn/translated-content#promoting-an-inactive-locale-to-tier-1 is also useful.
