### ISSUE TITLE
Issue with "image-set()": (How to set background-image with image-set?)

### ISSUE THREAD

**Issue by MenaiAla** [mdn/content#3771]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image-set()

#### What information was incorrect, unhelpful, or incomplete?

I want to set the background for the body using `image-set` :

```css
body {
  background-image: image-set(
    "./images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg"
  );
}

```
#### Specific section or headline?

[Using image-set() to provide alternative background-image options](https://developer.mozilla.org/en-US/docs/Web/CSS/image-set()#using_image-set_to_provide_alternative_background-image_options)

#### What did you expect to see?
The body will change its background.

#### Did you test this? If so, how?

[Codesandox example](https://codesandbox.io/s/vigilant-bash-hdovd?file=/src/styles.css)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/image-set()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image-set()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/image-set()/index.html
* Last commit: https://github.com/mdn/content/commit/099184d196e3c4ff58921c5972d1284e16a66534
* Document last modified: 2021-03-31T14:21:28.000Z

</details>

**Comment by rachelandrew** [comment]
@MenaiAla what is the issue you are reporting with the documentation?

In your example, your CSS isn't loading at all, I don't think it is linked in, but you also need to have a resolution, which you don't have. https://developer.mozilla.org/en-US/docs/Web/CSS/image-set()#values

**Comment by rachelandrew** [comment]
Here is an example: https://codepen.io/rachelandrew/pen/baac3914bf11c3e2f8aec3c1e9a5b671

**Comment by MenaiAla** [comment]
@rachelandrew , in your [example ](https://codepen.io/rachelandrew/pen/baac3914bf11c3e2f8aec3c1e9a5b671)you provided `url` inside the `image-set` while in the documentation it does not exist.

**Comment by rachelandrew** [comment]
I'm about to make a PR which has a better example :)
