### ISSUE TITLE
Issue with "accesskey": example doesn't work on Firefox

### ISSUE THREAD

**Issue by ottworks** [mdn/content#3781]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey

#### What information was incorrect, unhelpful, or incomplete?
When I pressed alt + shift + s, the history menu opened up.

#### Specific section or headline?
HTML Demo: accesskey

#### What did you expect to see?
The example button being activated by pressing alt + shift + s

#### Did you test this? If so, how?
Pressing alt + shift + s

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/global_attributes/accesskey`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/accesskey/index.html
* Last commit: https://github.com/mdn/content/commit/0f7902d7ca027d71cdf33ecba0d9de65c387e5f8
* Document last modified: 2021-02-24T03:43:50.000Z

</details>

**Comment by rachelandrew** [comment]
@ottworks this seems to work, you do need to focus the iframe of the example however by clicking into it first.
