### ISSUE TITLE
Issue with "Proxy Auto-Configuration (PAC) file": The `alert` function is incorrectly linked.

### ISSUE THREAD

**Issue by Xeoth** [mdn/content#3782]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file

#### What information was incorrect, unhelpful, or incomplete?

The `alert()` function in the *Predefined functions and environment* section incorrectly links to `Window.alert`.

#### Specific section or headline?

As mentioned above, *Predefined functions and environment*. More specifically, under the *Logging utility* point.

#### What did you expect to see?

A section of the article explaining that the `alert()` function logs its output to the Browser Console.

#### Did you test this? If so, how?

I used the `alert()` function and instead of a standard webpage popup alert I got the output in the Browser Console.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/proxy_servers_and_tunneling/proxy_auto-configuration_pac_file`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/proxy_servers_and_tunneling/proxy_auto-configuration_pac_file/index.html
* Last commit: https://github.com/mdn/content/commit/fc36604b19a172f3fbedb2629e2403180f2eda55
* Document last modified: 2021-03-19T23:16:59.000Z

</details>

**Comment by teoli2003** [comment]
@xeoth, good catch!
