### ISSUE TITLE
Issue with "RegExp.prototype.hasIndices": broken interactive example

### ISSUE THREAD

**Issue by peterbe** [mdn/content#3784]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/hasIndices

#### What information was incorrect, unhelpful, or incomplete?

The interactive example is broken because https://interactive-examples.mdn.mozilla.net/pages/js/regexp-prototype-hasindices.html is 404'ing. 

#### Specific section or headline?

Interactive examples

#### What did you expect to see?

An interactive example

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/regexp/hasindices`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/hasIndices
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/regexp/hasindices/index.html
* Last commit: https://github.com/mdn/content/commit/f8b6ed3c94b3659bb7d947d4c3290d53304e7648
* Document last modified: 2021-03-22T09:18:17.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks @peterbe  . This works fine now :-
![image](https://user-images.githubusercontent.com/2392803/132129733-a6d48bf2-2dec-4f74-8ebd-4704c3fc870d.png)

**Comment by teoli2003** [comment]
Closing per the last comment. Thanks.
