### ISSUE TITLE
Issue with "Images in HTML": Invalid citation for recommending putting images in a specific folder

### ISSUE THREAD

**Issue by djalilhebal** [mdn/content#3814]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML

#### What information was incorrect, unhelpful, or incomplete?

Neither the [current Google Developers' page][google-current] nor the [referenced Google Support page (archived)][google-archived] mentions anything about putting photos/illustrations in an "images" directory/subpath.  
(Kinda relevant: The **archived** page recommended separating adult images from the rest and putting them in `adult/`.)

[google-current]: https://developers.google.com/search/docs/advanced/guidelines/google-images?visit_id=637531258100048864-3018538391&rd=1
[google-archived]: https://web.archive.org/web/20201111165011/https://support.google.com/webmasters/answer/114016

#### Specific section or headline?
"How do we put an image on a webpage?"

> If the image was in an images subdirectory, which was inside the same directory as the HTML page (which Google recommends for SEO/indexing purposes), then you'd embed it like this:
> [...]

#### What did you expect to see?
Something more factual or up-to-date(?).
The link to Google Image's Best Practices page should be updated as well (if we still need it).

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/images_in_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.html
* Last commit: https://github.com/mdn/content/commit/96c87f23821cb93c5e5917c2ad956b41809acfb9
* Document last modified: 2021-03-24T10:03:05.000Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @djalilhebal . It looks like this URL is out of date, so I've just removed the link; see https://github.com/mdn/content/commit/c4b2d25d04d21121f7d3e66da414c1e3107dff9f
