### ISSUE TITLE
Issue with "ISP": (short summary here please)

### ISSUE THREAD

**Issue by Mommy17181921** [mdn/content#3815]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/ISP

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/isp`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/ISP
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/isp/index.html
* Last commit: https://github.com/mdn/content/commit/84eac7b54de6366dd67384f4f7d5f082f22fd7f4
* Document last modified: 2021-01-13T11:01:45.000Z

</details>

**Comment by CreaTorAlexander** [comment]
Which issue have you found with the ISP?
