### ISSUE TITLE
Issue with "Reflect.construct()": (short summary here please)

### ISSUE THREAD

**Issue by inger-na** [mdn/content#3825]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/construct

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/reflect/construct`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/construct
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/reflect/construct/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details> missing e in console.log in section Reflect.construct() vs Object.create()

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve raised https://github.com/mdn/content/pull/3828 with a fix
