### ISSUE TITLE
Issue with "Object.prototype.isPrototypeOf()": No comparative `false` examples

### ISSUE THREAD

**Issue by SampsonCrowley** [mdn/content#3831]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isPrototypeOf

#### What information was incorrect, unhelpful, or incomplete?
Every single example returns `true`, with no contrasting `false` examples

#### Specific section or headline?
All examples in both sections

#### What did you expect to see?
a `false` example for comparison. Users who are trying to learn what `isProtoypeOf` actually is doing don't really gain as much information when every example they see says that `isPrototypeOf` returns `true`, without any contrasting examples of that would return `false` to compare against.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/isprototypeof`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isPrototypeOf
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/isprototypeof/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/3834 with a fix
