### ISSUE TITLE
5. "Issues" with "An overview of HTTP": Meaning of the first image,  second image , meaning of "layered structure", meaning of "application layer",  

### ISSUE THREAD

**Issue by 552020** [mdn/content#3838]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview

#### What information was incorrect, unhelpful, or incomplete?

I'm coming from the Codecademy Full-Stack-Path, that references really often to the MDN documentation. I'm a lerner not an expert. Sorry if I put all the 5 Issues in a single request!

I'll ask some questions about the document: 

- Regarding the section "An Overview of HTTP"

1. Regarding the first image in the document: I'm not sure if this is a good representation of what the Internet is, since it put the server and the client outside the Internet as if the Internet would be like a proxy. But maybe I missunderstand what the Internet is

2. Regarding the second image in the document: I sincerely don't understand what this image is meant to explain. The image is in my opinion not self-explaining and it's not fully explained in the text before or after it. 

- Regarding the section [Components of HTTP-based systems](https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview#components_of_http-based_systems), subsection: Proxies.

3. Regarding the sentence: "Due to the layered structure of the Web stack, most of these operate at the transport, network or physical levels, becoming transparent at the HTTP layer and potentially making a significant impact on performance."

For me at this point the expression "the layered structure of the Web stack" was not clear to me and also the expression "HTTP layer". The whole layers thing was not clear to me. So I went back to the startpoint of the guide [HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP) with the idea that this information was given previously and in fact the concept of layer is central in the short introduction to the tutorials.

4. Regarding the concept of layer in [HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP)

The expression "application layer" in the first sentence of the section ("Hypertext Transfer Protocol (HTTP) is an application-layer protocol for transmitting hypermedia documents, such as HTML.") is explained with an Hyperlink to the page [Application Layer](https://en.wikipedia.org/wiki/Application_layer) in Wikipedia. The first sentence of the Wikpage is this one: "An application layer is an abstraction layer that specifies the shared communications protocols and interface methods used by hosts in a communications network". It defines "application layer" as an "abstraction layer" referring for the explanation to the Wikipage [Abstraction Layer](https://en.wikipedia.org/wiki/Abstraction_layer). The first sentence of the article is: "In computing, an abstraction layer or abstraction level is a way of hiding the working details of a subsystem, allowing the separation of concerns to facilitate interoperability and platform independence. Examples of software models that use layers of abstraction include the OSI model for network protocols, OpenGL and other graphics libraries." with 5 hyperlinks connected to different concepts. We end up "understanding" that an application layer is a way of hiding the working details of a subsystem. I find it still kind of fuzzy, and I ask myself I there is no better way to explain direct in the original article what a application layer is. 

5. Application Layer in the Glossary. 

I checked also for "Application Layer in the Glossary. Everytime I want to search something in the Glossary I've to google "MDN Glossary" with the concept I'm looking for cause I can't find a way to access it. It should be linked in "References and Guides" I would say but it's not. 

I understand that this tutorial is written by experts and I'm not saying that they should be written in a way I get it immediately. I wanted just to express the point that some learners maybe could not get it so easily. I guess I've a general idea of how the communication between clients and servers (with the whole proxies in between) works with single requests from the client to the servers (and with the  concerning the different parts that should be successively  loaded (html, css, js, extra-contents and so on) but I find the explanation of the layer structure confusing and a little bit too layered! :-) 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/overview`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/overview/index.html
* Last commit: https://github.com/mdn/content/commit/0d19eee95a1c7c6b774cf4fbda4b98ab6f3d9c1a
* Document last modified: 2021-02-16T14:32:31.000Z

</details>

**Comment by Josh-Cena** [comment]
1. First image is redone in https://github.com/mdn/content/pull/34251.
2. Second image should be familiar to people with network background, but even if not, the paragraph below provides the necessary information (that HTTP builds over TCP). You don't need to worry about other parts in the diagram if you don't understand them.
3. (and 4) you correctly realized that "layered" means "abstraction". It is an abstract concept but understanding comes with time; I don't think MDN can do a much better job than Wikipedia. I think this paragraph already provides a good hint of what "layer" intends to mean:
   > In reality, there are more computers between a browser and the server handling the request: there are routers, modems, and more. Thanks to the layered design of the Web, these are hidden in the network and transport layers. HTTP is on top, at the application layer. Although important for diagnosing network problems, the underlying layers are mostly irrelevant to the description of HTTP.
5. This will be part of https://github.com/orgs/mdn/discussions/662

Since I think this page is meant as an overview, not a guide, and certainly not a tutorial, it has the right level of specificity. The only potential inaccuracy in the diagram is addressed. This issue has also been open for >3years without anyone wanting to do further elaborations, so I think we should call it done.
