### ISSUE TITLE
Issue with "Window.localStorage": (short summary here please)

### ISSUE THREAD

**Issue by dirkroorda** [mdn/content#3840]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

#### What information was incorrect, unhelpful, or incomplete?

What if the protocol is `file:`

#### What did you expect to see?

How the origin of is defined if the protocol is `file:`, and more importantly, 

1. whether different files have different origins
2. whether the answer to question 1 is browser dependent

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/localstorage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/localstorage/index.html
* Last commit: https://github.com/mdn/content/commit/11a98a59fca5f2e448d9e4b70e3c8a538c47b201
* Document last modified: 2021-02-19T19:45:18.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/3843 with a change that adds the following text:

> <p>For documents loaded from <code>file:</code> URLs (that is, files opened in the browser directly from the user’s local filesystem, rather than being served from a web server) the requirements for <code>localStorage</code> behavior are undefined and may vary among different browsers.</p>
> 
> <p>In all current browsers, <code>localStorage</code> seems to return a different object for each <code>file:</code> URL — in other words, each <code>file:</code> URL seems to have its own unique local-storage area. But there are no guarantees about that behavior, so you shouldn’t rely on it — because, as mentioned above, the requirements for <code>file:</code> URLs remains undefined. So it’s possible that browsers may change their <code>file:</code> URL handling for <code>localStorage</code> at any time — and in fact some browsers <em>have</em> changed their handling for it over time.</p>

**Comment by dirkroorda** [comment]
Excellent!
The important thing I infer from your text is, that `localStorage` is available for `file:` origins.
And in order to use it reliably, you have to do your own key management, in order separate the keys for different `file:` origins.
I add a prefix to every key (did that anyway).
Many thanks!
