### ISSUE TITLE
Issue with "Using the MediaStream Recording API": with firefox 87, the audio is truncated

### ISSUE THREAD

**Issue by Franck-rouille** [mdn/content#3842]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Using_the_MediaStream_Recording_API

#### What information was incorrect, unhelpful, or incomplete?
The demo https://mdn.github.io/web-dictaphone/ of the dictaphone is OK with Chrome, but with firefox87, the audio is truncated: if I record 10seconds, I've only got 2 seconds of audio recorded. If I record 20seconds, I've only got 4 or 5 seconds of audio recorded.

#### Specific section or headline?
https://mdn.github.io/web-dictaphone/

#### What did you expect to see?
I expected to listen all the audio recorded with firefox87.

#### Did you test this? If so, how?
Yes, with Chrome it's OK but not with firefox87.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediastream_recording_api/using_the_mediastream_recording_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Using_the_MediaStream_Recording_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediastream_recording_api/using_the_mediastream_recording_api/index.html
* Last commit: https://github.com/mdn/content/commit/a796a31de50096a113a67649205dfe4313202531
* Document last modified: 2021-02-26T22:08:27.000Z

</details>

**Comment by sideshowbarker** [comment]
I can’t reproduce this in current Firefox — so it seems it must have gotten fixed in the meantime
