### ISSUE TITLE
Question about editing MDN

### ISSUE THREAD

**Issue by David263** [mdn/content#3844]
I have been an MDN editor in the past, and I used an online editing mode that was very convenient. Now, all I can find is a guide for editing the files in GitHub. Was the online editing and publishing mode eliminated, or am I just not logged in correctly?

**Comment by tristantheb** [comment]
Hello 😃,

The old system of editing pages has been removed and replaced by editing HTML pages through GitHub!
We now use Yari to edit the pages from a Node server to be installed. If you want to continue to contribute to the MDN by correcting pages, adding, etc., you should now go through GitHub ^^

All you need to know about installing the English repository is here: https://github.com/mdn/content/blob/main/README.md#making-contributions
And the how to contribute pages have also been updated to explain how to contribute to MDN on GitHub: https://developer.mozilla.org/en-US/docs/MDN/Contribute

This change will be accompanied in the future by changes to pages and KumaScript. HTML pages will be written in MarkDown and KumaScript tags will gradually be replaced by regular HTML.

You can find various explanations of these changes here:
- https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/
- https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/
- https://hacks.mozilla.org/2020/12/welcome-yari-mdn-web-docs-has-a-new-platform/

I hope I have answered your question and provided the information you needed to understand what was going on with the MDN and why the edit buttons were removed :)

**Comment by David263** [comment]
While I don't have the time to learn all these procedures, I am glad to hear that GitHub is now used for MDN page storage. If I wish to edit pages, I will simply create an Issue, like this one that I just created: https://github.com/mdn/content/issues/3850. Then someone more able than I can do the editing. Thank you for your complete answer.

**Comment by sideshowbarker** [comment]
> If I wish to edit pages, I will simply create an Issue, like this one that I just created: #3850.

To be clear: That’s a perfectly fine way to help get changes made. You have no obligation to make changes directly yourself. So any time you spot a problem in an article, please don’t hesitate to just raise an issue here about it with the details. It‘s much better to have any issue on record than it is to have any problem continue to go on unfixed.

**Comment by tristantheb** [comment]
Contributing to the MDN does not oblige anyone to use Git commands, GitHub forks etc..., creating an Issue is already a contribution ;)

Afterwards, if one day you want to start getting your hands in the machine and thus start touching Git and GitHub, you will have contributors and reviewers present to help you if you have questions ^^

And the big guide /Contribution can also help you to gradually learn what you need to know to get started on GitHub ;D

I can only say thank you for continuing to contribute in your own way!

**Comment by sideshowbarker** [comment]
I’m gonna go ahead and close this out as resolved by https://github.com/mdn/content/issues/3844#issuecomment-813510898
