### ISSUE TITLE
Content suggestion: WebAPI Deprecated List

### ISSUE THREAD

**Issue by Dmole** [mdn/content#3851]
We have a list for the deprecated JavaScript language features;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features

## What is the new suggestion?
We should have a list for the deprecated JavaScript Web API features;
https://developer.mozilla.org/en-US/docs/Web/Reference/API

## Why is it important or useful?
1. Developer time; linters should be able to find this class of bug before runtime 
2. Security; JavaScript sloppiness can has led to security issues in the past, the ability to check would reduce the surface area.
3. Consistency; deprecation is [not consistently marked](https://github.com/mdn/content/issues/3852) with {{deprecated_function}}, {{deprecated_parameter}}, {{deprecated_type}}, etc and [some documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard) recommends using [deprecated features](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand).
4. Document-er time; [list what doesn't need documentation](https://github.com/jpmedley/mdn-helper/blob/main/config/default.json#L22).

### How many pages are likely to be needed?
1

### How much time do you think this work should take? A few hours? A week? A month?
a day for someone in the know to make a script to generate a list, and another script to auto tag linked pages. Another week to work out the edge cases and tag things consistently. 

### Will the work enable learners or professionals to achieve their goals better?
yes

### Does it address critical needs in the web industry?
yes; mdn has the only web API documentation now that Microsoft is using Chrome

### Is the work an operational necessity, i.e. is not having it a security risk?
yes

### Does the content help make the web more ethical?
no

## Other supporting information
https://github.com/mdn/content/issues/2086

**Comment by hamishwillee** [comment]
I don't see this as really useful for the broad community, or particularly a security risk. It is useful if the BCD and the MDN content match in this respect.

**Comment by sideshowbarker** [comment]
This doesn’t seem to have generated interest among the MDN core maintainers — as https://github.com/mdn/content/issues/3851#issuecomment-834128432 alludes to. And nobody in the community has stepped forward to commit to putting work into it. So it would seem to make sense to go ahead and close it out rather than keeping it open indefinitely without anything ever being done for it.
