### ISSUE TITLE
Issue with "white-space": what does "hang" mean?

### ISSUE THREAD

**Issue by arigoldx** [mdn/content#3860]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

#### What information was incorrect, unhelpful, or incomplete?

The article is fantastic except that I can't figure out what "hang" means. I googled a bit and found [an article](https://www.bigbrandsystem.com/white-space/) but that makes it seems like it's a vertical property only while I'm guessing the MDN docs refer to it being both horizontal and vertical.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#values

#### What did you expect to see?

A definition of "hang" :)

#### Did you test this? If so, how?

I tried different settings in my browser's dev tools but couldn't see anything that would show how `pre-wrap` has end-of-line-spaces as "hang" while `break-spaces` has end-of-line-spaces as "wrap".

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/white-space`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/white-space/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by rachelandrew** [comment]
Hi @arigoldx I have just submitted a PR to clarify this, I don't expect you would see anything different. If white space hangs then it can affect the size of the box (as calculated for intrinsic sizing). I've added a note, along with an explanation of what white space actually is with regard to this property.
