### ISSUE TITLE
Content bug: Add text explaining that prompt/confirm/alert might not be shown, or might not wait

### ISSUE THREAD

**Issue by mfreed7** [mdn/content#3861]
## What page(s) did you find the problem on?

Similar/same content on these three pages:

- https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt
- https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm
- https://developer.mozilla.org/en-US/docs/Web/API/Window/alert

## Specific page section or heading?

"Notes" in all cases

## What is the problem?

See https://crbug.com/892953 for additional context and information. But the short answer is that these three APIs (`window.prompt`, `window.confirm`, and `window.alert`) might not always result in a visible dialog. For example, in Chromium, if another tab is made visible, the prompt/dialog will not be shown.

This confuses developers, so it would be good to call this out in the MDN docs.  For example, see [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=892953#c3) from a developer, calling out that MDN says nothing about this behavior.

## What did you expect to see?

More docs here.

## Did you test this? If so, how?

N/A

@jpmedley

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/3864 with a change for review.
