### ISSUE TITLE
Issue with "Fundamental text and font styling": (short summary here please)

### ISSUE THREAD

**Issue by RPIERIS** [mdn/content#3872]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals

#### What information was incorrect, unhelpful, or incomplete?
The link in [Font Families](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals#font_families) which is in the sentence which ends with "it will just use a browser **default font**" takes you back to the same page.

#### Specific section or headline?
In the Font families section

#### What did you expect to see?
Open up a page to some new MDN content.

#### Did you test this? If so, how?
I opened the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/styling_text/fundamentals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/styling_text/fundamentals/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/3873 with a fix.
