### ISSUE TITLE
Issue with "Auto-placement in CSS Grid Layout": (short summary here please)

### ISSUE THREAD

**Issue by Dorin-David** [mdn/content#3874]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout

#### What information was incorrect, unhelpful, or incomplete?
The example with the images, towards the end of the article, does not show the images but only the placeholders. 

#### Specific section or headline?
"Use cases for auto-placement"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_grid_layout/auto-placement_in_css_grid_layout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_grid_layout/auto-placement_in_css_grid_layout/index.html
* Last commit: https://github.com/mdn/content/commit/fc36604b19a172f3fbedb2629e2403180f2eda55
* Document last modified: 2021-03-19T23:16:59.000Z

</details>

**Comment by rachelandrew** [comment]
@Dorin-David looks like the placeholder site has gone.

I'll replace them with actual images - thanks for letting us know!
