### ISSUE TITLE
Issue with "If-Modified-Since": request should be resource

### ISSUE THREAD

**Issue by ldoblies** [mdn/content#3875]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since

#### What information was incorrect, unhelpful, or incomplete?

"request" should instead be "resource"

#### Specific section or headline?
In the first paragraph:

"If the **request** has not been modified since, the response will be a 304 without any body"

#### What did you expect to see?

"If the **resource** has not been modified since, the response will be a 304 without any body"

#### Did you test this? If so, how?

checked the french version

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/if-modified-since`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/if-modified-since/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/3877 with a fix
