### ISSUE TITLE
Issue with "MitM": Use gender-neutral language

### ISSUE THREAD

**Issue by apolakipso** [mdn/content#3880]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/MitM

#### What information was incorrect, unhelpful, or incomplete?
Aiming to remove exclusionary language, an alternative for "man-in-the-middle" that is already being used in a few places is "manipulator-in-the-middle".

While other gender-neutral variants like "monster-in-the-middle" exist, this has the added benefit of also clarifying the concept and containing no bias whatsoever.

Note: While this is currently not listed on Wikipedia, it's in active use in the security community, see links below. Googling the term also brings up MitM content rightaway.

- https://portswigger.net/daily-swig/mitm
- https://www.zaproxy.org/docs/desktop/start/features/intercept/
- https://owasp.org/www-community/attacks/Manipulator-in-the-middle_attack

#### Specific section or headline?
The preferred meaning of the initialism

#### What did you expect to see?
> A Manipulator-in-the-middle attack (MitM) intercepts a communication between two systems.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/mitm`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/MitM
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/mitm/index.html
* Last commit: https://github.com/mdn/content/commit/49f606217b82a761b6b52946ea4da3752d2375ee
* Document last modified: 2021-02-09T19:08:28.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/3884 with a change for review.

**Comment by apolakipso** [comment]
> Thanks for raising this — I’ve opened #3884 with a change for review.
Thank you! Since opening a similar issue on OWASP.org, I have found a more suitable alternative that the security community is already adopting (see https://github.com/OWASP/www-community/pull/400), namely "manipulator-in-the-middle". 
Should I modify this issue or make a new one?

**Comment by sideshowbarker** [comment]
> Thank you! Since opening a similar issue on OWASP.org, I have found a more suitable alternative that the security community is already adopting (see [OWASP/www-community#400](https://github.com/OWASP/www-community/pull/400)), namely **"manipulator-in-the-middle"**.

ah wow yeah, that’s great — I’ll update the PR I raised

> Should I modify this issue or make a new one?

Please go ahead and modify this one — there’s no need for new one
