### ISSUE TITLE
Issue with "<text>": (short summary here please)

### ISSUE THREAD

**Issue by rgchris** [mdn/content#3882]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text#usage_notes

#### What information was incorrect, unhelpful, or incomplete?

States that 'Text Content Elements' are permitted content of the `<text>` element

#### Specific section or headline?

Usage Notes

#### What did you expect to see?

'Text Content Child Elements'

#### Did you test this? If so, how?

A nested `<text>` element does not appear in an SVG image in Firefox

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/element/text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/text/index.html
* Last commit: https://github.com/mdn/content/commit/4a810357cb7f1a75de023c65fc0c83a884bd2b08
* Document last modified: 2021-03-25T00:07:10.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/yari/pull/3456 with a fix.
