### ISSUE TITLE
Issue with "CSSNumericValue.to()": Mistake in example

### ISSUE THREAD

**Issue by Qendolin** [mdn/content#3894]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSSNumericValue/to

#### What information was incorrect, unhelpful, or incomplete?

The example code is `console.log(CSS.px("23").to("com").toString());`

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/CSSNumericValue/to#examples

#### What did you expect to see?

`"com"` is not a valid unit and should be `"cm"` to convert to centimeters.

#### Did you test this? If so, how?

Running `console.log(CSS.px("23").to("com").toString());` gives error `Failed to execute 'to' on 'CSSNumericValue': Invalid unit for conversion`. Works fine with `"cm"` as unit

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/cssnumericvalue/to`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSSNumericValue/to
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/cssnumericvalue/to/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve raised https://github.com/mdn/content/pull/3897 with a fix.
