### ISSUE TITLE
meta[name=theme-color]' is not supported by Edge, Firefox, Firefox Android, Opera, Safari, iOS Safari.

### ISSUE THREAD

**Issue by divyaarali** [mdn/content#3906]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/meta/name/theme-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/meta/name/theme-color/index.html
* Last commit: https://github.com/mdn/content/commit/690965e33f6663ef450e6ed9edd9a7e7f73f96c5
* Document last modified: 2021-03-27T00:58:07.000Z

</details>

**Comment by divyaarali** [comment]
plz solve this problem

**Comment by chrisdavidmills** [comment]
The compat data on the page looks accurate, and consistent with what you are saying. I don't see that there is anything that needs fixing on this page, so I am closing this issue,

**Comment by divyaarali** [comment]
Ok thank you for ur response  Sent from Mail for Windows 10 From: Chris MillsSent: Wednesday, April 7, 2021 4:40 PMTo: mdn/contentCc: divyaarali; AuthorSubject: Re: [mdn/content] meta[name=theme-color]' is not supported by Edge, Firefox, Firefox Android, Opera, Safari, iOS Safari. (#3906) The compat data on the page looks accurate, and consistent with what you are saying. I don't see that there is anything that needs fixing on this page, so I am closing this issue,—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
