### ISSUE TITLE
Issue with "String": UTF-32 escape codes don't seem to exist

### ISSUE THREAD

**Issue by verhovsky** [mdn/content#3907]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String

#### What information was incorrect, unhelpful, or incomplete?

This information:

> \u{X} ... \u{XXXXXX}
> (where X…XXXXXX is 1–6 hex digits; range of 0x0–0x10FFFF) 
> | 
> UTF-32 code unit / Unicode code point between U+0000 and U+10FFFF

#### Specific section or headline?

Escape notation

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#escape_notation

#### What did you expect to see?

I expected 

`\u1`

to work on Chrome 89.0.4389.95 or Node JS v14.14.0

#### Did you test this? If so, how?

Chrome console:

```js
'\u1'
VM44:1 Uncaught SyntaxError: Invalid Unicode escape sequence
```

NodeJS:

```js
> '\u1'
'\u1'
 ^^^^

Uncaught SyntaxError: Invalid Unicode escape sequence
> '\u7'
'\u7'
 ^^^^

Uncaught SyntaxError: Invalid Unicode escape sequence
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/index.html
* Last commit: https://github.com/mdn/content/commit/d31a8fcf7cf24e2f6b2ea8805db2e79bf8ff8474
* Document last modified: 2021-03-24T02:44:55.000Z

</details>

**Comment by sideshowbarker** [comment]
> I expected
> 
> `\u1`
> 
> to work on Chrome 89.0.4389.95 or Node JS v14.14.0

In the `\u{X} ... \u{XXXXXX}` part of the docs cited, the `{` and `}` braces are literal characters that must be included.

In other words, rather than `\u1` or `\u7` you’d need to do this:

```
\u{1}
\u{7}
```

**Comment by verhovsky** [comment]
Oh, that makes sense. Sorry.

**Comment by sideshowbarker** [comment]
> Oh, that makes sense. Sorry.

No worries — I blame the docs for lacking any actual examples there in-context. I think I’ll raise a PR to add some.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/3911 with some refinements to that table that I think might help make it more clear.
