### ISSUE TITLE
Issue with "Element.scrollIntoViewIfNeeded()": (Does not work on firefox)

### ISSUE THREAD

**Issue by UmerDaraz163** [mdn/content#3909]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded

#### What information was incorrect, unhelpful, or incomplete?

This does not work in firefox and if we use simple scrollIntoView, that's not smooth.

#### Specific section or headline?

This does not work in firefox and if we use simple scrollIntoView, that's not smooth.
#### What did you expect to see?
If scroll into view if needed does not work then it must be smooth with simple scroll into view

#### Did you test this? If so, how?
I'm using botui.js and tested with that

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/scrollintoviewifneeded`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/scrollintoviewifneeded/index.html
* Last commit: https://github.com/mdn/content/commit/dc9089417852530f233c345bd6821d6e06f11b1e
* Document last modified: 2020-12-18T10:05:08.000Z

</details>
This does not work in firefox and if we use simple scrollIntoView, that's not smooth.

**Comment by chrisdavidmills** [comment]
`scrollIntoViewIfNeeded()` doesn't work on Firefox, and that is what our compat data reports, so there is no documentation bug to fix here. If you want to report a problem with Firefox's support for a web platform feature, the place to do that is https://bugzilla.mozilla.org.
