### ISSUE TITLE
Issue with "display": …

### ISSUE THREAD

**Issue by NanoCarbon** [mdn/content#391]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/display

#### What information was incorrect, unhelpful, or incomplete?
"none" is a possible value.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/manifest/display`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/display
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/manifest/display/index.html
* Report started: 2020-12-18T02:49:54.090Z

</details>

**Comment by rachelandrew** [comment]
@NanoCarbon this is `display` for Web App Manifests rather than the CSS `display` property. 

You might be looking for: https://developer.mozilla.org/en-US/docs/Web/CSS/display

**Comment by peterbe** [comment]
Close?
