### ISSUE TITLE
Content bug: Broken link on `lang` attribute page

### ISSUE THREAD

**Issue by mehulkar** [mdn/content#3919]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang

## Specific page section or heading?

Under `Language tag syntax` right below the demo and blue "notecard". Specific text is:

> Even if the lang attribute is set, it may not be taken into account, as the xml:lang attribute has priority.

## What is the problem?

The `xml:lang` text links to https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/xml:lang, but this page is 404.

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/3931 with a fix
