### ISSUE TITLE
Issue with "What will your website look like?": (short summary here please)

### ISSUE THREAD

**Issue by swittig307** [mdn/content#3922]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/What_will_your_website_look_like

#### What information was incorrect, unhelpful, or incomplete?
The info on Google images licensing is no longer current, they have changed it to only 2 options neither of which is the one you recommend.

#### Specific section or headline?
Google Image

#### Did you test this? If so, how?
Went to Google and tried to pick and option that no longer existed in the format given by the instructions.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/what_will_your_website_look_like`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/What_will_your_website_look_like
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/what_will_your_website_look_like/index.html
* Last commit: https://github.com/mdn/content/commit/5a6c608bd83fa2f3ba82c48ce4add6bc7891249b
* Document last modified: 2021-01-22T11:46:18.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can work on this issue 👍

**Comment by CreaTorAlexander** [comment]
I have to take a new screenshot for this issue. Where should I store this screenshot, and are there any things I should consider?

**Comment by sideshowbarker** [comment]
> I have to take a new screenshot for this issue. Where should I store this screenshot

You should put it in the https://github.com/mdn/content/tree/main/files/en-us/learn/getting_started_with_the_web/what_will_your_website_look_like directory.

> and are there any things I should consider?

There’s a linter which runs automatically to check that the file is compressed sufficiently. If that linter reports the file as not being sufficiently compressed, there’s a command you can run to compress it. But anyway, if that happens, we could deal with that when we get there.
