### ISSUE TITLE
Issue with "HTML table advanced features and accessibility": Does not use gender neutral language

### ISSUE THREAD

**Issue by WillowP** [mdn/content#3925]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced

#### What information was incorrect, unhelpful, or incomplete?
Using "he or she" instead of "they" or "the user".

I'd be happy to fix this myself as a first contribution to the project :)

#### Specific section or headline?
Paragraph near the top:

> As you can infer from the brief example above, the caption is meant to contain a description of the table contents. This is useful for all readers wishing to get a quick idea of whether the table is useful to them as they scan the page, but particularly for blind users. Rather than have a screenreader read out the contents of many cells just to find out what the table is about, **he or she** can rely on a caption and then decide whether or not to read the table in greater detail.

#### What did you expect to see?
"they" or "the user"

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/tables/advanced`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/tables/advanced/index.html
* Last commit: https://github.com/mdn/content/commit/bd456157e7e89cc2c936f7dbdaf9d919890d4743
* Document last modified: 2021-02-04T15:48:30.000Z

</details>

**Comment by WillowP** [comment]
Upon searching the project in GitHub I also found:

## Use "he or she"
https://github.com/mdn/content/blob/7c0211cabf93b5708c34981c49dbe7bf9e38da4c/LICENSE.md
https://github.com/mdn/content/blob/c7d9128559ed9526914c9be5bb461445fde5866a/files/en-us/learn/javascript/building_blocks/functions/index.html

Changes to `LICENSE.md` might need to be reviewed by a lawyer?

## Use "he/she"
https://github.com/mdn/content/blob/7c0211cabf93b5708c34981c49dbe7bf9e38da4c/LICENSE.md
https://github.com/mdn/content/blob/4d0fd582e15ab46773c913636ce157b24ae59064/files/en-us/web/api/credentialscontainer/index.html


Again, happy to fix these myself and make a PR if that's acceptable.

**Comment by sideshowbarker** [comment]
As far as the license language, it seems Creative Commons has acknowledged the problem and they plan to make a change —

https://creativecommons.org/legal-code-errata/ mentions this:

> ### Issues by legal tool
> ### CC0 1.0
> 
> **Non-inclusive pronouns.** The two instances of “he or she” and the two instances of “his or her” should have been written using gender-neutral pronouns (“they” and “their”). This will be changed when we next version CC0, and will be encouraged in official translations, when possible.

So maybe we could update to the next CC0 version when it becomes available (though there doesn’t seem to be much information anywhere about when that might be).

**Comment by WillowP** [comment]
Thanks both! I was thinking I could expand my search a little bit by also searching for " he " and " she ". Here's an updated list, much longer than the original:

## From initial comment on this issue
* https://github.com/mdn/content/blob/289f591f2f02be654713d409de3a8c47841acbe5/files/en-us/learn/javascript/building_blocks/functions/index.html#L260
* https://github.com/mdn/content/blob/11c96e424b376432f8ab8ebb12a40e5383e31e9d/files/en-us/web/api/credentialscontainer/preventsilentaccess/index.html#L21
* https://github.com/mdn/content/blob/4d0fd582e15ab46773c913636ce157b24ae59064/files/en-us/web/api/credentialscontainer/index.html#L34
* https://github.com/mdn/content/blob/bd456157e7e89cc2c936f7dbdaf9d919890d4743/files/en-us/learn/html/tables/advanced/index.html#L51

## Additional changes suggested
* https://github.com/mdn/content/blob/94fcf42284061ea5b05acd59e3008f5888ea46c3/files/en-us/mozilla/projects/nss/fips_mode_-_an_explanation/index.html#L27
* https://github.com/mdn/content/blob/f4fb4c2d90a134366c280eec6cb599825981ad5d/files/en-us/web/css/shape-margin/index.html#L70
* https://github.com/mdn/content/blob/11a98a59fca5f2e448d9e4b70e3c8a538c47b201/files/en-us/web/api/window/opendialog/index.html#L29
* https://github.com/mdn/content/blob/9b5cf04786dad342498374e51aacb2ccd1999aac/files/en-us/web/accessibility/accessibility_and_spacial_patterns/index.html#L52
* https://github.com/mdn/content/blob/07da89bb91dc6fc42affe7f766c4764efa0bd52b/files/en-us/web/api/notifications_api/using_the_notifications_api/index.html#L204
* https://github.com/mdn/content/blob/0d19eee95a1c7c6b774cf4fbda4b98ab6f3d9c1a/files/en-us/web/http/conditional_requests/index.html#L99
* https://github.com/mdn/content/blob/23eebf57a003f8a933aad06436d78fe127f8223e/files/en-us/tools/devtoolsapi/index.html#L525
* https://github.com/mdn/content/blob/c7d9128559ed9526914c9be5bb461445fde5866a/files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.html#L344
* https://github.com/mdn/content/blob/11a98a59fca5f2e448d9e4b70e3c8a538c47b201/files/en-us/web/api/window/open/index.html#L740

## Edge case?
* https://github.com/mdn/content/blob/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea/files/en-us/web/api/texttrackcuelist/length/index.html#L40  ...  https://github.com/mdn/content/blob/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea/files/en-us/web/api/texttrackcuelist/length/index.html#L44

I think this one is probably okay left as is, but presenting it here for you to decide. It doesn't violate the guideline:
> if you are talking about the actions of a specific man, using "he"/"his" is fine

but referring to some supreme power as male might be against the spirit of the guideline. I figured since I'm doing this review I might as well put this in here.

Suggestion: Could easily change this to be:
> Is the ruler of the universe in?
Yes, they're in - in a bad humor.

**Comment by teoli2003** [comment]
I think this has been fixed by the PR and we can close this issue? (Or did I miss something?)

**Comment by WillowP** [comment]
> I think this has been fixed by the PR and we can close this issue? (Or did I miss something?)

Thanks  for the reminder @teoli2003 . Yes, I addressed all the diversions I found in the PR. Closing now :)
