### ISSUE TITLE
Issue with "How to structure a web form": broken link

### ISSUE THREAD

**Issue by Dorin-David** [mdn/content#3932]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form

#### What information was incorrect, unhelpful, or incomplete?
A link that should point to the _form_ attribute is broken.

#### Specific section or headline?
"The `<form>` element"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/how_to_structure_a_web_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_structure_a_web_form/index.html
* Last commit: https://github.com/mdn/content/commit/0854165bda311a595f0ed481d7f12b7a33178a44
* Document last modified: 2021-03-19T00:45:46.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update the link :+1:

**Comment by Dorin-David** [comment]
The path you suggest point to an article about the  _form_ **tag**, while what it was meant in the article is the form **attribute** which allows you to link an input to a form even if the input is outside of it.

**Comment by rachelandrew** [comment]
We don't currently have docs for the `form` attribute. So the link points to the correct place, we just don't have the content.

This is related to #1712

**Comment by sideshowbarker** [comment]
At this point, there’s no broken link or the `form` attribute in article. So I guess we can assume this was subsequently fixed. But if I’ve missed something, this issue could be revisited.
