### ISSUE TITLE
Content suggestion: addEventListener fire capture before bubble handlers at target

### ISSUE THREAD

**Issue by hank121314** [mdn/content#3936]
## What is the new suggestion?
After chromium 89.0.4359.0.
When the event is in the target phase, it will trigger `{ useCapture: true }` listener, and then `{ useCapture: false }` listener. It does not depend on the order they were registered. 

## Why is it important or useful?
The description in this line:
https://github.com/mdn/content/blob/710d9171a7a1b20e797cd0c1b79a5460dcad4381/files/en-us/web/api/eventtarget/addeventlistener/index.html#L98-L102

Might confuse someone who never tries this before. 
I think we need a more precise document.

## Other supporting information

- [Chromium Commit: Fire capture before bubble handlers at target](https://github.com/chromium/chromium/commit/f73b047b99026f22c60f4541cab98346e9871f65)
- [WebKit changes 236002](https://trac.webkit.org/changeset/236002/webkit)

Thanks for the review !

MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/5221
