### ISSUE TITLE
Content suggestion: Document Headers.forEach()

### ISSUE THREAD

**Issue by cyberixae** [mdn/content#3937]
## What is the new suggestion?
The `Headers.forEach( )` is missing documentation https://developer.mozilla.org/en-US/docs/Web/API/Headers

## Why is it important or useful?
The callback seems to receive value, key instead of key, value. The programmer might or might not get this right without documentation. We need one page explaining the type of the forEach method. I imagine some page for a similar method could be used as a starting point. Might still take an hour or two to verify that this method follows te same behaviour. Adding this would reduce the amount of mistakes related to expecting the reversed callback argument order.

**Comment by Andrew-Cottrell** [comment]
If this page is added, it may be relevant to mention any browser differences and known bugs with `Headers.prototype.forEach`.

For example, [Firefox Bug 1697114](https://bugzilla.mozilla.org/show_bug.cgi?id=1697114) "Headers API iterator does not copy the list".

**Comment by isatveersingh** [comment]
**Hey folks, I want to work on it. Can any one please help me how to get started?**
I want to write documentation of **_Headers.forEach_** method.

**Comment by isatveersingh** [comment]
I am working on it.

**Comment by isatveersingh** [comment]
Hi @teoli2003 , can you please review my pull request.
