### ISSUE TITLE
Issue with "Falsy": BigInt negative zero is not a value

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [mdn/content#3944]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Falsy

#### What information was incorrect, unhelpful, or incomplete?
This line `0n, -0n | The BigInt zero and negative zero (so, also 0x0n/-0x0n).` Implies there is a BigInt negative zero which to my knowledge there is not.

#### Specific section or headline?
Complete list of JavaScript falsy values

#### What did you expect to see?
I would drop reference to -0n and -0x0n.

#### Did you test this? If so, how?
Tested in Chrome and Nodejs 14
```
BigInt('-0')         // 0n
Object.is(0, 0n)    // false
Object.is(0n, -0n)  // true
Object.is(0, 0)     // true
Object.is(0, -0)    // false
```

The BigInt spec has no mention of a BigInt negative zero `https://tc39.es/ecma262/#sec-bigint-objects` and the section `https://tc39.es/ecma262/#sec-ecmascript-language-types-number-type` covering negative zero has no mention of a BigInt negative zero.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/falsy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Falsy
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/falsy/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Yeah, agreed — `-0n` is just another way to write `0n`, so let’s change this

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/3954 with a fix which does this:

```diff
-   <td><code>0n</code>, <code>-0n</code></td>
-   <td>The {{jsxref("BigInt")}} zero and negative zero (so, also <code>0x0n</code>/<code>-0x0n</code>).</td>
+   <td><code>0n</code></td>
+   <td>The {{jsxref("BigInt")}} zero (so, also <code>0x0n</code>; and note: there is no {{jsxref("BigInt")}} negative zero — the negation of <code>0n</code> is <code>0n</code>).</td>
```
I added the explicit *“note: there is no BigInt" negative zero — the negation of `0n` is `0n`”* part to preempt somebody coming around later and asking *”Why are we documenting `-0` but not `-0n`?“*.
