### ISSUE TITLE
Issue with "Intl.RelativeTimeFormat.prototype.format()": Should mention support for "today"

### ISSUE THREAD

**Issue by mkaply** [mdn/content#3947]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/format

This documentation is great, but wanted to make one suggestion.

In this section:

Using the auto option

If numeric:auto option is passed, it will produce the string yesterday or tomorrow instead of 1 day ago or in 1 day. This allows to not always have to use numeric values in the output.

It also has support for today.

So you should add something like this:

// Format relative time using zero (0).
rtf.format(0, "day");
// > "today"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/relativetimeformat/format`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/format
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/relativetimeformat/format/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by hamishwillee** [comment]
@mkaply I agree. Would you be able to create a PR to add this information?

**Comment by jadjoubran** [comment]
✋ I can take this one
@sideshowbarker I hope I'm not spamming you with notifications, let me know if you prefer that I batch the issues that I'd like to be assigned to

**Comment by sideshowbarker** [comment]
>  @sideshowbarker I hope I'm not spamming you with notifications, let me know if you prefer that I batch the issues that I'd like to be assigned to

It’s just fine the way you’ve been doing them — it’s not spamming. Thanks much for taking these on.
