### ISSUE TITLE
Issue with "<input type="date">": broken link

### ISSUE THREAD

**Issue by seawolf42** [mdn/content#3948]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

#### What information was incorrect, unhelpful, or incomplete?
"Date and Time picker tutorial" link in "See Also" is incorrect.

#### Specific section or headline?
See Also

#### What did you expect to see?
The date & time picker tutorial

#### Did you test this? If so, how?
Click the link :)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/date`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/date/index.html
* Last commit: https://github.com/mdn/content/commit/690965e33f6663ef450e6ed9edd9a7e7f73f96c5
* Document last modified: 2021-03-27T00:58:07.000Z

</details>

**Comment by hamishwillee** [comment]
If you look at the link url it is supposed to go to a heading  [Basic native form controls](https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls) named "Date and time picker". However that heading is missing.

I think that given the other content in the linked page (and the absence of a good alternative) this would not actually add anything much to the docs that are linked from even if it existed. A quick fix would be to simply delete the link.

That said, a better fix would be to create the missing section in [Basic native form controls](https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls). Pretty good job for someone who is reading https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date and https://developer.mozilla.org/en-US/docs/Web/HTML/Date_and_time_formats - interested in creating a PR @seawolf42 ?

**Comment by seawolf42** [comment]
Normally I would love to, but I'm actually trying to find those docs because I truly have no idea what the right information is.

I would be happy to word-smith if I can get help identifying the right content or references.

**Comment by charlfields** [comment]
Looks like they moved the content from the [Basic native from controls](https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls) to the new tutorial on [HTML5 input types](https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types#date_and_time_pickers). I have created a pull request [#14317](https://github.com/mdn/content/pull/14317) to resolve the problem.

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/14317
