### ISSUE TITLE
Issue with "Create BookInstance form": (short summary here please)

### ISSUE THREAD

**Issue by Davenof** [mdn/content#3952]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_BookInstance_form

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_bookinstance_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_BookInstance_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_bookinstance_form/index.html
* Last commit: https://github.com/mdn/content/commit/adc309da4235ec6c01f40e3212168ea5b98358c9
* Document last modified: 2021-01-29T01:56:44.000Z

</details>

**Comment by hamishwillee** [comment]
Closing as this does not describe a problem
