### ISSUE TITLE
Typo under heading "Selects and Datalists"

### ISSUE THREAD

**Issue by leonard-9500** [mdn/content#396]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling

#### What information was incorrect, unhelpful, or incomplete?
In line 4 below the specified heading is the following typo. "consisent"

#### Specific section or headline?
"Selects and Datalists"

#### What did you expect to see?
"We've managed to get the basic look of the boxes looking pretty uniform and **consistent**."

#### Did you test this? If so, how?
/

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/advanced_form_styling`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/forms/advanced_form_styling/index.html
* Report started: 2020-12-18T07:37:44.847Z

</details>

**Comment by chrisdavidmills** [comment]
Fixed via https://github.com/mdn/content/commit/4ac2efe0e1200ba68faaaa119bd56f5b9bc17aef

**Comment by chrisdavidmills** [comment]
Sorry @sideshowbarker. I'll make sure I assign myself before doing such fixes in future.

**Comment by sideshowbarker** [comment]
> Sorry @sideshowbarker. I'll make sure I assign myself before doing such fixes in future.

No worries — it was fruitful in that I found another problem while looking at the source (and will raise another PR)
