### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by MishaChernov** [mdn/content#3960]
![image](https://user-images.githubusercontent.com/26045884/114135655-37d37c80-9912-11eb-9106-8215153cf15d.png)

How to reproduce: 
1. Open References & Guides
2. Scroll down and click on User Experience link

**Comment by teoli2003** [comment]
Hi, @MishaChernov !

Thanks for the report! I tried to find where this page was linked but wasn't able to  locate it. 

Could you link here the page with this broken link?

Thanks a lot for helping!

**Comment by sideshowbarker** [comment]
I also am unable to find a link to the article anywhere in the current sources. And given that we’ve gotten no response from the OP, let’s go ahead and close his.
