### ISSUE TITLE
Issue with "String.prototype.trim()": bad example with misleading description

### ISSUE THREAD

**Issue by DavidBruchmann** [mdn/content#3961]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

#### What information was incorrect, unhelpful, or incomplete?
> Another example of .trim() removing whitespace from just one side.

Her I'd expect a string with white space on both sides but that it's trimmed only on one side.  
Instead the initial string just includes whitespace on one side.

#### Specific section or headline?
Examples

#### What did you expect to see?
A solution to trim on only one side.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/trim`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/trim/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve opened https://github.com/mdn/content/pull/3962 with a change that drops that example completely.

> A solution to trim on only one side.

In JavaScript, the solution for that is to use `trimStart()` or `trimEnd()`:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimEnd

So to help make those article more discoverable I added the following to the Description section of the `trim()` article:

> To return a new string with whitespace trimmed from just one end, use `trimStart()` or `trimEnd()`.

**Comment by DavidBruchmann** [comment]
@sideshowbarker  Thanks, that looks much better now.  
Keeps perhaps to mention that **no error** is raised if it's trimmed only on the right side, one the left side or not at all if the incoming string never has corresponding surrounding white-spaces.

**Comment by sideshowbarker** [comment]
> Keeps perhaps to mention that **no error** is raised if it's trimmed only on the right side, one the left side or not at all if the incoming string never has corresponding surrounding white-spaces.

Thanks, yes, that seems worth explicitly mentioning — so I’ve opened https://github.com/mdn/content/pull/3985 with a follow-up change.

**Comment by DavidBruchmann** [comment]
Great, thanks a lot! ;-)
