### ISSUE TITLE
Issue with "Operator precedence": Spread is missing

### ISSUE THREAD

**Issue by danieltroger** [mdn/content#3965]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

#### What information was incorrect, unhelpful, or incomplete?

Where is the mf `...` operator smh 😤⁉️

#### Specific section or headline?

# Table

#### What did you expect to see?

Spread

#### Did you test this? If so, how?

Spread operator has higher precedence than most think:

```
var obj = {... undefined || {sauce: "lol"}}
```

```
> obj
< Object { sauce: "lol" }
```

I wanted to prove to my coworker that I don't need parenthesis.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/operator_precedence/index.html
* Last commit: https://github.com/mdn/content/commit/020083cf88b0d52a6f07a3d86823592f82bfcaa7
* Document last modified: 2021-04-06T10:44:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Spread syntax is intentionally not part of the [Operator precedence](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) article — because spread syntax is not an operator.

See https://stackoverflow.com/a/48656377/441757, which explains:

> Spread syntax is not an operator and therefore does not have a precedence.
> 
> It is part of the array literal and function call (and object literal) syntax.
> 
> Similarly, rest syntax is part of the array destructuring and function parameter (and object destructuring) syntax.

See also https://stackoverflow.com/questions/44934828/is-it-spread-syntax-or-the-spread-operator

cc @bergus

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/3965#issuecomment-816568541

**Comment by danieltroger** [comment]
@sideshowbarker Why did you assign this to yourself only to close it after a week? I thought you were gonna change the site and add something like "these syntaxes are often mistaken for operators, here's their precendence". Because otherwise the next person is also going to have to open an issue and you'll have to explain it again.

Thanks for the answer and links nevertheless.

**Comment by sideshowbarker** [comment]
@danieltroger You’re right. I’ll write up a PR.

**Comment by sideshowbarker** [comment]
@danieltroger Thanks for having raised this — I’ve opened https://github.com/mdn/content/pull/4208 with an update to the [Operator precedence](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) article.

**Comment by danieltroger** [comment]
Awesome, thanks!
