### ISSUE TITLE
Issue with "MouseEvent.relatedTarget": (short summary here please)

### ISSUE THREAD

**Issue by adixon-adobe** [mdn/content#3974]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/relatedTarget

#### What information was incorrect, unhelpful, or incomplete?
This page links to a "dragexit" event which 404s. It should probably point to the "dragleave" event at https://developer.mozilla.org/en-US/docs/Web/API/Document/dragleave_event

#### Specific section or headline?
The top event table

#### What did you expect to see?
A link that doesn't 404

#### Did you test this? If so, how?
Yes -- clicked the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mouseevent/relatedtarget`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/relatedTarget
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mouseevent/relatedtarget/index.html
* Last commit: https://github.com/mdn/content/commit/4c3fe0dab0b625b7cd449275e1ba453fab438cc4
* Document last modified: 2021-04-05T00:16:07.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/3986 with a fix.
