### ISSUE TITLE
Issue with "Element.ariaLive": Incorrect closing bracket

### ISSUE THREAD

**Issue by rahejar** [mdn/content#3975]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaLive

#### What information was incorrect, unhelpful, or incomplete?
Incorrect closing bracket for one of the example

#### Specific section or headline?
Under Examples section, the first line of code is
<div role="region" id="planetInfo" aria-live="polite"<

#### What did you expect to see?
The closing bracket should be >

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/arialive`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaLive
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/arialive/index.html
* Last commit: https://github.com/mdn/content/commit/2f54395e640f1ea9c03b449f0cd6ed397b5ed8d3
* Document last modified: 2021-02-25T15:23:22.000Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @rahejar ; I've raised https://github.com/mdn/content/commit/bc0294b178471534e67c4b48eea4550a6b430c6d to fix it.
