### ISSUE TITLE
Issue with "Cross-Origin Resource Sharing (CORS)": dead links to httpwg.org client-hints page

### ISSUE THREAD

**Issue by rursprung** [mdn/content#399]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

#### What information was incorrect, unhelpful, or incomplete?
the link for "DPR" points to the external URL http://httpwg.org/http-extensions/client-hints.html#dpr but this returns a 404.
the same is true for all other links which go to the same page (e.g. "Save-Data").

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests
2nd list of bullet points there (just search for "DPR", it only shows up once on the whole page)

#### What did you expect to see?
working links

#### Did you test this? If so, how?
try to follow the link for "DPR", "Save-Data" and a few others.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/cors/index.html
* Report started: 2020-12-17T01:01:55.743Z

</details>

**Comment by rursprung** [comment]
can you please re-open the issue? when i created it i mentioned only "DPR" and that's what the commit you did fixed. but ~1min after opening the issue i edited it since i noticed that other links are also pointing to the same page and are thus also dead => they haven't been fixed yet.

**Comment by sideshowbarker** [comment]
Thanks for taking time to report this. It’s fixed in the sources by #401, and will be deployed in the next update.

**Comment by sideshowbarker** [comment]
> can you please re-open the issue? when i created it i mentioned only "DPR" and that's what the commit you did fixed. but ~1min after opening the issue i edited it since i noticed that other links are also pointing to the same page and are thus also dead => they haven't been fixed yet.

ah OK — reopened now, and will raise a separate PR to fix he remaining ones. (Sorry for not having read the issue description carefully enough.)
