### ISSUE TITLE
Issue with "Element.outerHTML": firstChild and firstElementChild

### ISSUE THREAD

**Issue by landiehan** [mdn/content#3991]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML

#### What information was incorrect, unhelpful, or incomplete?
In the second example, the usage of property `firstChild` here is wrong, it will log `#text` in this context.

#### Specific section or headline?
"Examples" section.

#### What did you expect to see?
Use `firstElementChild` instead.

#### Did you test this? If so, how?
Yes, and some references:

- [Node.firstChild](https://developer.mozilla.org/en-US/docs/Web/API/Node/firstChild)
- [ParentNode.firstElementChild](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/firstElementChild)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/outerhtml`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/outerhtml/index.html
* Last commit: https://github.com/mdn/content/commit/56d9a678477f0e79232caa8169114519bf02a44a
* Document last modified: 2021-02-19T19:41:18.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can work on this 👍
