### ISSUE TITLE
Issue with "Debugging CSS": (short summary here please)

### ISSUE THREAD

**Issue by atakndogn** [mdn/content#4000]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Debugging_CSS

#### What information was incorrect, unhelpful, or incomplete?
“The below table shows the compat data for the shape-outside property.” 
The table is not below, on the contrary above. Please change the place of the table to make it more clear.

#### Specific section or headline?
Is the property and value supported by the browser you are testing in?

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/debugging_css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Debugging_CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/debugging_css/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/4026 with a possible fix
