### ISSUE TITLE
Content bug: HTMLOptionElement inherits all classes?

### ISSUE THREAD

**Issue by mfuji09** [mdn/content#4017]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement

## Specific page section or heading?

The head of the document.

## What is the problem?

The document says the interface inherits all **classes** and methods of the `HTMLElement` interface.
Isn't it all **properties** instead of all classes?

## What did you expect to see?

I assume that it should be "inherits all properties and methods of ..."

**Comment by sideshowbarker** [comment]
> I assume that it should be "inherits all properties and methods of ..."

Yes, seems so — Can you please open a PR for it?

**Comment by mfuji09** [comment]
@sideshowbarker Thank you. Yes, I will correct it.
