### ISSUE TITLE
Issue with "Test your skills: Loops 3": Solution does not match instructions

### ISSUE THREAD

**Issue by AndrewSRea** [mdn/content#4019]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Loops

#### What information was incorrect, unhelpful, or incomplete?

In the instructions for Task 3, the instructions ask "For each number that isn't a prime number, use the **continue** keyword to move on to the next loop iteration." A **continue** statement is not used in the solution.

The instructions also ask that "You should use a type of loop that you've not used in the previous two tasks."

In the Task 2 solution shown in Github, a **do...while** loop is used--and then it is used _again_ in Task 3.

#### Specific section or headline?

The **Test your skills: Loops** module accompanying the **JavaScript building blocks - Looping code** learning module.

#### What did you expect to see?

The correct solution as pertaining to the instructions given for Task 3.

#### Did you test this? If so, how?

And in actuality, the solution given does not work.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/test_your_skills_colon__loops`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Loops
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/test_your_skills_colon__loops/index.html
* Last commit: https://github.com/mdn/content/commit/88b8dc61828f0c111b5eda4197921dcf153f3b0f
* Document last modified: 2020-12-15T16:53:05.000Z

</details>

**Comment by sideshowbarker** [comment]
> In the instructions for Task 3, the instructions ask "For each number that isn't a prime number, use the **continue** keyword to move on to the next loop iteration." A **continue** statement is not used in the solution.

The https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Loops article doesn’t mention the **continue** keyword; instead it says this:

> For each number that isn't a prime number, continue on to the next loop iteration.

**Comment by sideshowbarker** [comment]
Closing for lack of response.
