### ISSUE TITLE
Issue with ":local-link": css rule not working

### ISSUE THREAD

**Issue by Dorin-David** [mdn/content#4030]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:local-link

#### What information was incorrect, unhelpful, or incomplete?
  When explaining the :local-link pseudo-class, an example follows where the local link's color is set to red. However, in the output the color is still blue. 

#### Did you test this? If so, how?
I've tried the selector on my machine, and also in Chrome, but it's not working. Can someone explain what's going on? 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_local-link`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:local-link
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_local-link/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by chrisdavidmills** [comment]
It may just not be supported/enabled anywhere yet...
@rachelandrew do you know anything about this one?

**Comment by rachelandrew** [comment]
I don't think there is any support as yet, which is why we don't have BCD.

Would be good to come up with that way to indicate no support, given the BCD folk don't want features with no support listed.

**Comment by rachelandrew** [comment]
I've raised an issue re the statement of no support https://github.com/mdn/content/issues/5118 so closing this as it's a broader issue than just this page.
