### ISSUE TITLE
Issue with "HTML attribute: pattern": missing word

### ISSUE THREAD

**Issue by Dorin-David** [mdn/content#4034]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern

#### What information was incorrect, unhelpful, or incomplete?
In the first sentence of the "**Constraint validation**" section, a phrase seems to be missing a word:
"_If the input’s value is not the empty string and the value does not match the entire regular expression, there is **a** [missing word?] from **a** patternMismatch._"

#### Specific section or headline?
"Constraint validation"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/attributes/pattern`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/pattern/index.html
* Last commit: https://github.com/mdn/content/commit/1f2db9f0a46b99c254476b5f9445a74b98a6fa30
* Document last modified: 2021-03-27T00:17:29.000Z

</details>

**Comment by teoli2003** [comment]
Thanks for the report.

 I didn't guess the missing word, so reworded a bit more.
