### ISSUE TITLE
Issue with "WindowOrWorkerGlobalScope.btoa()": Missing snippet for Unicode chars as found on DE page

### ISSUE THREAD

**Issue by ffd8** [mdn/content#4036]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa

#### What information was incorrect, unhelpful, or incomplete?
EN page is missing really helpful function from the DE page

#### Specific section or headline?
[This snippet](https://developer.mozilla.org/de/docs/Web/API/WindowOrWorkerGlobalScope/btoa#unicode-zeichenketten), contributed by [Johan Sundström](http://ecmanaut.blogspot.com/2006/07/encoding-decoding-utf8-in-javascript.html) for handling Unicode characters was provided on the DE page:
```
function utf8_to_b64(str) {
    return window.btoa(unescape(encodeURIComponent(str)));
}

function b64_to_utf8(str) {
    return decodeURIComponent(escape(window.atob(str)));
}

// Usage:
utf8_to_b64('✓ à la mode'); // JTI1dTI3MTMlMjUyMCUyNUUwJTI1MjBsYSUyNTIwbW9kZQ==
b64_to_utf8('JTI1dTI3MTMlMjUyMCUyNUUwJTI1MjBsYSUyNTIwbW9kZQ=='); // "✓ à la mode"

utf8_to_b64('I \u2661 Unicode!'); // SSUyNTIwJTI1dTI2NjElMjUyMFVuaWNvZGUlMjUyMQ==
b64_to_utf8('SSUyNTIwJTI1dTI2NjElMjUyMFVuaWNvZGUlMjUyMQ=='); // "I ♡ Unicode!"
```

When viewing the page in **EN**glish, that's no where to be found.
Adding this snippet to both EN and other languages will definitely help everyone looking into this function.

#### What did you expect to see?
Function as mentioned above on DE page

#### Did you test this? If so, how?
Changed language of page to a few different ones (Polish has this snippet) – to help all chars of the world, would be great to add to page for all languges.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/windoworworkerglobalscope/btoa`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/windoworworkerglobalscope/btoa/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by himanshugarg** [comment]
While useful in its own right, the suggested example uses several other other functions and therefore does not pass the test of [general best practices](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines). Furthermore the DE and EN pages have [diverged significantly](http://i.imgur.com/5FX9cvl.png), so some DE expertise might help to update the DE page.

**Comment by sideshowbarker** [comment]
I share the misgivings that @himanshugarg mentions. But we’ve gotten repeated requests to restore the example functions — which I why I did actually end up restoring them to the Base64 glossary entry. But since we do have them there, we don’t need to repeat the same content in the btoa() article too — so I’ve opened #8494 with a change that just adds a link from the btoa() article to the relevant section of the Base64 glossary entry.
