### ISSUE TITLE
Issue with "<feColorMatrix>": Name of this tag is case-sensitive in HTML! jQuery and devTools automatically remove cases!!!

### ISSUE THREAD

**Issue by Horiatu** [mdn/content#4038]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feColorMatrix

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/element/fecolormatrix`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feColorMatrix
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/fecolormatrix/index.html
* Last commit: https://github.com/mdn/content/commit/2ee4eb9a544f544bec4749f8b84ae09d6412fc6f
* Document last modified: 2021-03-19T22:51:19.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@Horiatu Can you provide an example of the jQuery you used which uncovered this issue?
(Vanilla JavaScript has special methods like [getElementsByTagNameNS](https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagNameNS) to query SVG).

**Comment by Horiatu** [comment]
It also have a method document.createElementNS which generates with correct caption, but somehow it still does not work…

Tx, for replay – I’ll come back if I’ll find the correct solution.

My code is now:

                const svgFilters = $("<svg></svg>", {
                    id: "svgFilters",
                    xmlns: "http://www.w3.org/2000/svg",
                    style: "display:none"
                }).appendTo("body");

                const invertMatrix = $("<filter></filter>", {
                    id: "invertMatrix"
                }).appendTo(svgFilters);
                const feInvert = document.createElementNS('http://www.microsoft.com/office/excel/', "feColorMatrix");
                feInvert.setAttributeNS('http://www.microsoft.com/office/excel/', 'type', 'matrix');
                feInvert.setAttributeNS('http://www.microsoft.com/office/excel/', 'values', '-1 0 0 0 1  0 -1 0 0 1  0 0 -1 0 1  0 0 0 1 0');
                $(feInvert).appendTo(invertMatrix);


.blackFilter {
    background-color: white;
}

.blackFilter,
.blackFilter img,
.blackFilter video,
.blackFilter .blackInkHelp {
    -webkit-filter: url(#invertMatrix);
    -moz-filter: url(#invertMatrix);
    -ms-filter: url(#invertMatrix);
    -o-filter: url(#invertMatrix);
    filter: url(#invertMatrix);
}

And the generated HTLM is:

<html lang="en-US" class="blackFilter">…

<svg id="svgFilters" xmlns="http://www.w3.org/2000/svg" style="display:none"><filter id="invertMatrix"><feColorMatrix type="matrix" values="-1 0 0 0 1  0 -1 0 0 1  0 0 -1 0 1  0 0 0 1 0"></feColorMatrix></filter></svg>

In the previous version of BlackInk Little<https://chrome.google.com/webstore/detail/blackink-little/jhpghaenkakfmpfkhokmglbhhooonbeg> (get it from chrome web store<https://chrome.google.com/webstore/category/extensions>,) was working fine…

However, the point is that you cannot create this node with document.createElement, nor with jQuery and you cannot edit with chrome dev tools, and the page should mention it!

Tx,

Horia Tudosie | Lead Developer
Esri Canada | 900-12 Concorde Pl | Toronto ON M3C 3R8
T 647-943-1841 | esri.ca<http://esri.ca/>

Register today for the virtual Esri User Conference
https://esri.com/uc

**Comment by Horiatu** [comment]
Hi André,

The only code that works is:

                $("body").append(`
<svg id='svgFilters' xmlns='http://www.w3.org/2000/svg' style='display:none'>
    <filter id='invertMatrix'>
        <feColorMatrix type='matrix' values='-1 0 0 0 1  0 -1 0 0 1  0 0 -1 0 1 0 0 0 1 0'/>
    </filter>
</svg>`);


Note: the svg node html string was appended with to a jQuery selector, but appending the filter node in an svg jQuery-generated node did now work either!

The generated code is:

<svg id="svgFilters" xmlns="http://www.w3.org/2000/svg" style="display:none">
    <filter id="invertMatrix">
        <feColorMatrix type="matrix" values="-1 0 0 0 1  0 -1 0 0 1  0 0 -1 0 1 0 0 0 1 0"></feColorMatrix>
    </filter>
</svg>

Note the </feColorMatrix> Part which was not part of my string ( as my node ends with />, but I assume this is part of what google dev tools does…
)
Tx,

Horia Tudosie | Lead Developer
Esri Canada | 900-12 Concorde Pl | Toronto ON M3C 3R8
T 647-943-1841 | esri.ca<http://esri.ca/>

Register today for the virtual Esri User Conference
https://esri.com/uc

**Comment by Ryuno-Ki** [comment]
Okay, that's something to work with.

First, keep in mind, that jQuery does not support SVG officially:
https://api.jquery.com/append/

> jQuery doesn't officially support SVG. Using jQuery methods on SVG documents, unless explicitly documented for that method, might cause unexpected behaviors. Examples of methods that support SVG as of jQuery 3.0 are addClass and removeClass.

I mentioned `createElementNS` earlier. If I look at https://stackoverflow.com/a/20852029 it looks like you can control the attributes once created with Vanilla JS and then wrapped with jQuery.

I've created a CodePen to explore it, and it seem to work: https://codepen.io/Ryuno-Ki/pen/WNRzQBG

**Comment by Horiatu** [comment]
Thanks André,

Probably you did not read my last email – I’ve said that I already have my solution.
(Here, again:
                $("body").append(`
<svg id='svgFilters' xmlns='http://www.w3.org/2000/svg' style='display:none'>
    <filter id='invertMatrix'>
        <feColorMatrix type='matrix' values='-1 0 0 0 1  0 -1 0 0 1  0 0 -1 0 1  0 0 0 1 0'/>
    </filter>
</svg>`);
)

B.T.W. The page we talk about mentions somewhere that the values in the matrix snap automatically in the range [0, 1].
Actually, as you see above, the range is [-1, 1]!

Tx,

Horia Tudosie | Lead Developer
Esri Canada | 900-12 Concorde Pl | Toronto ON M3C 3R8
T 647-943-1841 | esri.ca<http://esri.ca/>

Register today for the virtual Esri User Conference
https://esri.com/uc

**Comment by Ryuno-Ki** [comment]
I noticed it. But since it is a template literal, I figured, you might want to have another approach to it (so your IDE could hint you towards mistakes better).

Anyway, as stated, jQuery does not support SVG. Thus, I don't see the need of a hint to call the described behaviour (case-sensitivity) out.
Do we have everything here to close this issue or would you like to have something else?

**Comment by Horiatu** [comment]
Whatever…

Horia Tudosie | Lead Developer
Esri Canada | 900-12 Concorde Pl | Toronto ON M3C 3R8
T 647-943-1841 | esri.ca<http://esri.ca/>

Register today for the virtual Esri User Conference
https://esri.com/uc

**Comment by Ryuno-Ki** [comment]
I'll take that as No and go ahead to close this issue.
