### ISSUE TITLE
Issue with "Node.isConnected": (polyfill comment is incorrect)

### ISSUE THREAD

**Issue by eligrey** [mdn/content#4043]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected

#### What information was incorrect, unhelpful, or incomplete?

My public-domain `Node.isConnected` polyfill only works with EdgeHTML (Edge <= 18, pre-Edgium). Edgium already supports isConnected as correctly noted in the browser support table.

#### What did you expect to see?

Replace polyfill text with latest code on https://gist.github.com/eligrey/f109a6d0bf4efe3461201c3d7b745e8f

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/node/isconnected`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/node/isconnected/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by sideshowbarker** [comment]
Hi Eli, thanks for the heads-up about this. Current practice at MDN is to no longer maintain polyfills within MDN articles but to instead replace them with hyperlinks to wherever they’re maintained elsewhere. So I opened https://github.com/mdn/content/pull/4050 to do that.
