### ISSUE TITLE
api.Document.caretRangeFromPoint - Misleading example

### ISSUE THREAD

**Issue by coleh2** [mdn/content#4044]
The example code in the https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint article either shouldn’t prefer `document.caretPositionFromPoint` and shouldn’t only try `document.caretRangeFromPoint` if `document.caretPositionFromPoint` isn’t supported — or else the article should explain what the code is doing.

#### Did you test this? If so, how?
I clicked in the "Result" box of MDN's example page for `caretRangeFromPoint`, while using Firefox 87 on Windows 10 Home v1909. The intended effect (insertion of line-breaks) occurred. This seems to indicate that the method is supported by Firefox, when in fact it’s actually not.

So the example should either not prefer `document.caretPositionFromPoint` — and should instead only use `document.caretRangeFromPoint` — or else the article should explain what that code is doing.

<details>
<summary>MDN page report details</summary>

* Query: `api.Document.caretRangeFromPoint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint
* Report started: 2021-04-11T19:21:28.736Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/4048 with a fix that hopefully makes this more clear.
