### ISSUE TITLE
Issue with "JavaScript": link to subsection on wikipedia that doesn't exist anymore

### ISSUE THREAD

**Issue by aleoncavallo** [mdn/content#4045]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript

#### What information was incorrect, unhelpful, or incomplete?
The reference to "many non-browser environments" as https://en.wikipedia.org/wiki/JavaScript#Uses_outside_Web_pages

#### Specific section or headline?
JavaScript

#### What did you expect to see?
perhaps it was refering to: https://en.wikipedia.org/wiki/JavaScript#Other_usage

#### Did you test this? If so, how?
clicked on it...

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/index.html
* Last commit: https://github.com/mdn/content/commit/e4a9ff13724c7650db233d66aa9e8f236596c291
* Document last modified: 2021-02-21T01:18:21.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this.

> perhaps it was refering to: [en.wikipedia.org/wiki/JavaScript#Other_usage](https://en.wikipedia.org/wiki/JavaScript#Other_usage)

Yeah, seems so — so I’ve opened https://github.com/mdn/content/pull/4047 with a fix which changes it to that.
