### ISSUE TITLE
Issue with "HTML elements reference": … Missing SVG element

### ISSUE THREAD

**Issue by plfstr** [mdn/content#406]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element

#### What information was incorrect, unhelpful, or incomplete?
Should this page include the SVG element?

#### Specific section or headline?
[Image and multimedia](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#Image_and_multimedia)

#### What did you expect to see?
Details of the SVG element. It would link to an SVG page also. This supporting [SVG](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/svg) page currently does not exist.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/html/element/index.html
* Report started: 2020-12-18T13:15:23.631Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. I’ve opened #410 with a patch that adds both the `svg` element and `mathml` element too.
