### ISSUE TITLE
Issue with "cursor": Grab cursor does not work on chrome on Ubuntu

### ISSUE THREAD

**Issue by eleanorcox** [mdn/content#4064]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

#### What information was incorrect, unhelpful, or incomplete?
Not sure if this is the right repo to make an issue in but hopefully you can get this to the right people.

The "grab" cursor does not work on Chrome on Ubuntu.

#### What did you expect to see?
In the CSS demo, when "grab" is selected, the cursor on the right half should change to the grab icon. However it remains as the default cursor (a pointer). 

This behaviour is the same when developing my own projects (i.e. the cursor never appears as a "grab" cursor but is always a pointer).

#### Did you test this? If so, how?
This behaviour occurs on Chrome (version 88.0.4324.150 64-bit) on Ubuntu (version 18.04.5 LTS 64-bit). 

The cursor appears correctly on Firefox on Ubuntu. The cursor also appears correctly on Chrome on Fedora. I have not tested on Windows/MacOS.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/cursor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/cursor/index.html
* Last commit: https://github.com/mdn/content/commit/892665a4c27da31a26d22578335377549324bb88
* Document last modified: 2021-03-23T04:34:40.000Z

</details>

**Comment by rachelandrew** [comment]
@eleanorcox I think this is probably something better raised as an issue with the browser.

I had a quick search and found this https://bugs.chromium.org/p/chromium/issues/detail?id=376156 which has recent updates. I'd suggest putting together a quick test case (maybe with a video of what you see) and either posting it to the relevant bug or raising a new one.

**Comment by rachelandrew** [comment]
Closing as this seems to be a specific browser bug rather than docs.
