### ISSUE TITLE
Issue with "Using Fetch": Define and/or link to definition of CORS

### ISSUE THREAD

**Issue by CLGolden** [mdn/content#4067]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

#### What information was incorrect, unhelpful, or incomplete?
A definition of the acronym 'CORS' would be helpful.

#### Specific section or headline?
2nd paragraph

#### What did you expect to see?
A link to the right page would be useful.

#### Did you test this? If so, how?
This looks like a good reference: https://developer.mozilla.org/en-US/docs/Glossary/CORS

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/fetch_api/using_fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fetch_api/using_fetch/index.html
* Last commit: https://github.com/mdn/content/commit/979d510b4e6f72ac70bf3f8a8200eb4e9b6274a2
* Document last modified: 2021-03-27T16:24:12.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/4076 with a fix
