### ISSUE TITLE
Issue with "Learning and getting help": (some code is missing as per the description)

### ISSUE THREAD

**Issue by B-meet** [mdn/content#4068]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Learning_and_getting_help

#### What information was incorrect, unhelpful, or incomplete?
A nav menu is usually created from a <strong>list of links</strong>
```
<ul>
  <li>First menu item</li>
  <li>Second menu item</li>
  <li>Third menu item</li>
  <li>etc.</li>
</ul>
```
but the anchor tags are not included
#### Specific section or headline?
Learn and recognize the patterns

#### What did you expect to see?
I expect the code should be like 
```
<ul>
  <li><a herf="">First menu item</a></li>
  <li><a herf="">Second menu item</a></li>
  <li><a herf="">Third menu item</a></li>
  <li><a herf="">etc.</a></li>
</ul>
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/learning_and_getting_help`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Learning_and_getting_help
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/learning_and_getting_help/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by CreaTorAlexander** [comment]
Thanks for coming up with this issue. You mean *href* right?

```
<ul>
  <li><a href="">First menu item</a></li>
  <li><a href="">Second menu item</a></li>
  <li><a href="">Third menu item</a></li>
  <li><a href="">etc.</a></li>
</ul>
```

**Comment by B-meet** [comment]
Awesome, thanks! I will check it out later thank you once again buddy
