### ISSUE TITLE
Issue with "<form>": Misleading note of form `name` being deprecated.

### ISSUE THREAD

**Issue by phoenixeliot** [mdn/content#4079]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form

#### What information was incorrect, unhelpful, or incomplete?
This page says:
> `name`
> The name of the form. Deprecated as of HTML 4 (use id instead). It must be unique among the forms in a document and not an empty string as of HTML5.

For one thing, I expect "as of HTML 4" to mean "In HTML4 and every version of the HTML spec since then". It's possible the fix for this is just to replace "as of HTML 4" with "in HTML 4 but not HTML 5".

Researching the topic, it seems that
1. The HTML5 spec doesn't call things "deprecated", it calls them "obsolete"
2. The HTML5 spec allows for `name` to be used on `<form>`s

Supporting pages for this info:
https://stackoverflow.com/questions/40738589/is-using-name-attribute-deprecated-in-html5
https://html.spec.whatwg.org/index.html#attributes-1 (see the table at #attributes-1 which lists `name` as being valid for `form`

This MDN page also lists `name` as being usable on `form`: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

#### Specific section or headline?
Attributes > `name`

#### What did you expect to see?
I expected the description to say that `name` is an allowed attribute for the `form` element in HTML5. (I don't know if it's invalid for HTML4 or not, include both pieces of info if relevant)

#### Did you test this? If so, how?
n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/form/index.html
* Last commit: https://github.com/mdn/content/commit/690965e33f6663ef450e6ed9edd9a7e7f73f96c5
* Document last modified: 2021-03-27T00:58:07.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this. It seems the misstatement about the attribute being deprecated probably crept in because somebody who edited the article previously made the mistake of assuming that since the `name` attribute for the `a` element is obsolete, it must be for the `form` element too. Anyway, I’ve opened https://github.com/mdn/content/pull/4086 with a change that drops that statement.
