### ISSUE TITLE
Content suggestion: Fix a typo of `runtime.connectExternal` in a native messaging image

### ISSUE THREAD

**Issue by raviqqe** [mdn/content#4082]
## What is the new suggestion?

- Replace `connectExternal` with `connectNative` in [the native messaging image](https://github.com/mdn/content/blob/3d36450e504d7a31e73cb6667b90e69392ae8655/files/en-us/mozilla/add-ons/webextensions/native_messaging/native-messaging.png).

## Why is it important or useful?

It seems to be a typo of `connectNative` as there is no such API called `runtime.connectExternal` while we have `onConnectNative` and `onConnectExternal`.

It would be a few-minute fix and avoids confusion to developers.

## Other supporting information

- [The corresponding page on MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging)

**Comment by caitmuenster** [comment]
Thanks @raviqqe. 

If anyone would like to submit an update for this, please leave a comment here and tag me when you submit a PR for review.

**Comment by Prometheus7-creator** [comment]
I have edited the image, I will be uploading it for review.

**Comment by caitmuenster** [comment]
Thanks @Prometheus7-creator! When you open the pull request, write "Fixes #4082" at the beginning of the comment to link the PR to this issue.
