### ISSUE TITLE
Issue with "WindowOrWorkerGlobalScope.fetch()": cache option not documented

### ISSUE THREAD

**Issue by wpk-** [mdn/content#4090]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch

#### What information was incorrect, unhelpful, or incomplete?

The `cache` option is missing from the `init` argument description.

#### Specific section or headline?

Syntax > Parameters > init

#### What did you expect to see?

`cache`

#### Did you test this? If so, how?

By reading.

The examples later in the article do include the `cache` option.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/windoworworkerglobalscope/fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/windoworworkerglobalscope/fetch/index.html
* Last commit: https://github.com/mdn/content/commit/7a1b21998c8c4dc473b1ab14e38c4079d1695b24
* Document last modified: 2021-03-02T09:32:02.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/4202 with a fix.
