### ISSUE TITLE
[Documentation only] Include link to Sensor API in main "Specification" Section?

### ISSUE THREAD

**Issue by rowild** [mdn/content#4091]
Similar to #3627 I was wondering if the "Sensor API" should not also find its place in the "Specifications" section, too? A general overview page already exists:
https://developer.mozilla.org/en-US/docs/Web/API/Sensor_APIs

In #3627 chrisdavidmills added some more content, which, in a similar form, might be needed here, too.

But maybe I am wrong - then please feel free to close this issue.
Thanks!

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/yari/pull/3543 with a fix.
