### ISSUE TITLE
Issue with "static": (short summary here please)

### ISSUE THREAD

**Issue by rejhgadellaabsl** [mdn/content#4097]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static

#### What information was incorrect, unhelpful, or incomplete?

The way static properties are declared on this page are incorrect:

```
class ClassWithStaticMethod {

  static staticProperty = 'someValue';
    ^- Class properties must be methods. Expected '(' but instead saw '='.

}
```

This is how it's done:

```
class ClassWithStaticMethod {

  static get staticProperty() { return 'someValue'; }

}
```

#### Specific section or headline?

Pretty much every section, example, etc.

#### What did you expect to see?

Class properties must be methods. The syntax that is used on this page is typescript, I believe.

#### Did you test this? If so, how?

Jshint says: Class properties must be methods. Expected '(' but instead saw '='.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/classes/static`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/classes/static/index.html
* Last commit: https://github.com/mdn/content/commit/020083cf88b0d52a6f07a3d86823592f82bfcaa7
* Document last modified: 2021-04-06T10:44:09.000Z

</details>

**Comment by rejhgadellaabsl** [comment]
Minor correction; this syntax seems to work in Chrome 90 but I'm pretty sure it's not ES6 syntax. So this is a fairly new addition to the static class syntax? I guess it would help if this is mentioned and maybe add an example of how ES6 syntax would look?

**Comment by sideshowbarker** [comment]
Thanks much for raising this — I’ve opened https://github.com/mdn/content/pull/4167 with a change that updates the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static article to make more clear what’s going on.

But for the short answer, see https://github.com/tc39/proposal-class-fields#field-declarations.

And see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields#browser_compatibility for info about the current level of browser support — which is, Chrome 72+, Firefox 69+, and Safari 14+.

The Chrome and Firefox support is fairly complete, but Safari 14 support is limited to non-static class fields (though Safari Technology Preview does now support static class fields).

https://v8.dev/features/class-fields#public-class-fields is a succinct, well-written intro to it all.

The most obvious win for developers is that you no longer need to wrap a constructor around the fields — you can just declare them at the top of the class (as in the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static examples).
