### ISSUE TITLE
Issue with "Django Tutorial Part 6: Generic list and detail vi…": declare an argument => declare a parameter

### ISSUE THREAD

**Issue by andrehora** [mdn/content#4100]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views

#### What information was incorrect, unhelpful, or incomplete?

This is a quite minor detail.
It would be more correct to say: "declare a parameter" instead of "declare an argument".

"Your view must therefore declare an argument with the same name!"
=>
"Your view must therefore declare a parameter with the same name!"

#### Specific section or headline?

Advanced path matching/regular expression primer

#### What did you expect to see?

"Your view must therefore declare a parameter with the same name!"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/generic_views`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/generic_views/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks, agreed.  Will be fixed by https://github.com/mdn/content/pull/4150

**Comment by andrehora** [comment]
Fixed in #4150
