### ISSUE TITLE
Issue with "<h1>–<h6>: The HTML Section Heading elements": is multiple <h1> really bad practice?

### ISSUE THREAD

**Issue by pbb72** [mdn/content#4101]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

#### What information was incorrect, unhelpful, or incomplete?

This page makes two claims about multiple `<h1>` tags which are almost identical, and which are not supported by additional information:

* Using more than one `<h1>` will not result in an error, but is not considered a best practice. Using only one `<h1>` is beneficial for screenreader users, and SEO.
* While HTML5 allows a `<h1>` per sectioning element, it is not considered best practice, and may subvert the expectations of how screen reader users navigate.

Google has multiple times denied that multiple `<h1>` has any effect on SEO, for example see https://www.youtube.com/watch?v=zyqJJXWk0gk.

A good reference might be https://www.w3.org/TR/2014/REC-html5-20141028/sections.html#outline, which notes there are currently no graphical browsers that support the outline algorithm. However, this note should also be taken with some care, because (1) is mentions "currently" without info on when this statement was last updated, and (2) it doesn't state why the outline algorithm would be a requirement for support of multiple `<h1>`.

#### Specific section or headline?

Usage notes

#### What did you expect to see?

I would have like to see some better support for the claim, not just mentioning "best practices".

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/heading_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/heading_elements/index.html
* Last commit: https://github.com/mdn/content/commit/c40f133b4ed8474730029e68a397aaebb042266b
* Document last modified: 2021-03-01T15:30:53.000Z

</details>

**Comment by sideshowbarker** [comment]
@stevefaulkner might be able to provide details to flesh out the claims a bit more.

**Comment by pbb72** [comment]
Interestingly enough, W3C has removed any reference to multiple h1 from their spec: https://github.com/w3c/html/pull/331/commits/10088841d4ec35047a61b0f85f924c89e57fd035, while the WHATWG spec stil promotes it: https://html.spec.whatwg.org/multipage/sections.html#sample-outlines (second example).

**Comment by stevefaulkner** [comment]
In short, using Only h1’s does not convey any document hierarchy to screen reader users because its not implemented in browsers. 
these articles may be helpful:
* [Computer says no to the HTML5 outline](http://html5doctor.com/computer-says-no-to-html5-document-outline/) 
*  [A decade + a year of heading backwards](https://html5accessibility.com/stuff/2021/03/21/a-decade-a-year-of-heading-backwards/)

**Comment by pbb72** [comment]
Just out of curiosity, is there anything preventing screen readers/assistive technology from representing sectioned headers even though the browser does not explicitly implement it? There is still the hierarchy presented through the DOM. Compare this to how CSS can still represent sectioned headers visually even without explicit support.

I am aware that would require additional work for the assistive software, which the developers might not find reasonable as there are so few sites actually implementing it.

**Comment by stevefaulkner** [comment]
@pbb72

> Just out of curiosity, is there anything preventing screen readers/assistive technology from representing sectioned headers even though the browser does not explicitly implement it? There is still the hierarchy presented through the DOM. Compare this to how CSS can still represent sectioned headers visually even without explicit support.

AT use the information conveyed by browsers through the [accessibility APIs](https://w3c.github.io/html-aam/#intro_aapi), DOM hacking by AT is an inferior and depending on browser not practically possible.

**Comment by stevefaulkner** [comment]
@pbb72

> Just out of curiosity, is there anything preventing screen readers/assistive technology from representing sectioned headers even though the browser does not explicitly implement it? There is still the hierarchy presented through the DOM. Compare this to how CSS can still represent sectioned headers visually even without explicit support.

AT use the information conveyed by browsers through the [accessibility APIs](https://w3c.github.io/html-aam/#intro_aapi), DOM hacking by AT is an inferior and depending on browser not practically possible.
