### ISSUE TITLE
Issue with "list-style": (short summary here please)

### ISSUE THREAD

**Issue by plweil** [mdn/content#4103]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style

#### What information was incorrect, unhelpful, or incomplete?
Accessibility concerns
Safari has an issue whereby unordered lists with a list-style value of none applied to them will not be recognized as a list in the accessibility tree. To address this, add a zero-width space as pseudo-content before each list item to ensure the list is recognized properly. This ensures the design is unaffected by the bug fix and that list items are not improperly described.

#### Specific section or headline?
Accessibility concerns

#### What did you expect to see?
First, the implication here is that this is a Safari bug. It is not a bug; [it is by design](https://bugs.webkit.org/show_bug.cgi?id=170179l)

Second, at the very least the less-hackish workaround (role="list") should be mentioned. (I would drop the css fix, too)

See also ["'Fixing' Lists"](https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/list-style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/list-style/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by rachelandrew** [comment]
@ericwbailey do you have any thoughts on this?

**Comment by ericwbailey** [comment]
I think the bigger issue here is capturing the theme of Scott's post, namely allowing an author to allow a list to announce its presence if needed.

The ARIA "fix" is good except for situations where authors cannot access the markup, so many CMS solutions and WYSIWYG editors. The CSS solution is also a bit of a hack, but addresses the issue if you cannot edit markup.

I am thinking the accessibility concerns section could be updated to reflect this. Is that something you'd like to take on, @plweil?

**Comment by plweil** [comment]
thanks @eric  who is the primary audience for this? Developers? And do you know offhand whether Safari also does this with display: flex?

**Comment by ericwbailey** [comment]
@plweil 
>who is the primary audience for this? Developers? 

The D in MDN is a bit of a tell, but I would say anyone that is interested in working on the web 🙂

>And do you know offhand whether Safari also does this with display: flex?

Could you clarify what this means? Remove its role?

**Comment by rachelandrew** [comment]
@plweil just checking in to see if you are coming back to this?

**Comment by plweil** [comment]
> @plweil just checking in to see if you are coming back to this?

Yes, hopefully soon. Sorry for the delay.

**Comment by plweil** [comment]
@ericwbailey @rachelandrew @sideshowbarker Here's a first draft of the text; let me know what you think. Of course short code examples can be added if necessary. I would probably remove the link to the Unfettered Thoughts article and replace it with a link to Scott's post. How do I go about editing this; do I need to do a PR?

Accessibility concerns

In a notable exception, Safari will not recognize an unordered list as a list in the accessibility tree if has a list-style value of none.

The most straightforward way to address this is to add an explicit ARIA role=“list”to the <ul> element in the HTML. This will restore the list semantics without affecting the design.

CSS-only workarounds are also available for those who do not have access to the markup. One is to add a zero-width space as pseudo-content before each list item. A second approach is to apply a url value to the list-style property.

These CSS workarounds should be applied only if the HTML solution is not available, and only after testing to ensure that they don’t result in unexpected behaviors that may negatively impact users’ experiences.

**Comment by rachelandrew** [comment]
@plweil yep if you want to make the change yourself please do a PR and I'll keep an eye out for it.

**Comment by sideshowbarker** [comment]
@plweil Proposed text in https://github.com/mdn/content/issues/4103#issuecomment-857673966 looks great to me. Might also be good to get @scottaohara to look it over (and also look over the PR contents — after you raise the PR for this).

**Comment by rachelandrew** [comment]
@plweil were you going to raise a PR for this?

**Comment by plweil** [comment]
@rachelandrew Done. Sorry for the delay.

**Comment by plweil** [comment]
@rachelandrew I did submit that PR. Not long after I received a "All jobs have failed" message from PR Review Companion(?). I haven't seen that before and don't know what it means (it doesn't sound good). Right now I don't see the PR listed under PRs. I'd be happy to fix whatever might be wrong on my end, if that's where the problem lies.

**Comment by rachelandrew** [comment]
@plweil it looks like you raised it against your fork https://github.com/plweil/content/pulls

You need to make the PR against mdn/content.
