### ISSUE TITLE
Issue with "String.prototype.matchAll()": (example uses RegExp constructor function without new)

### ISSUE THREAD

**Issue by hecmec** [mdn/content#4106]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll

#### What information was incorrect, unhelpful, or incomplete?
The examples use 
`const regexp = RegExp('foo[a-z]*','g');`

#### What did you expect to see?
`const regexp = new RegExp('foo[a-z]*','g');`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/matchall`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/matchall/index.html
* Last commit: https://github.com/mdn/content/commit/020083cf88b0d52a6f07a3d86823592f82bfcaa7
* Document last modified: 2021-04-06T10:44:09.000Z

</details>

**Comment by CreaTorAlexander** [comment]
Thanks for coming up with this issue. I raised PR #4121 to solve it.
