### ISSUE TITLE
Content bug: This seems off: "sites that prevent cross-site request forgery have nothing new to fear from HTTP access control"

### ISSUE THREAD

**Issue by jmanico** [mdn/content#4111]
The main CORS page https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

States: "**_Therefore, sites that prevent cross-site request forgery have nothing new to fear from HTTP access control_**."

And this seems like the wrong message. I'd prefer to say:

**_HTTP access control does not prevent cross-site request forgery and sites still need to provide appropriate Cross Site Request Forgery defense._**

**Comment by sideshowbarker** [comment]
Thanks for catching this — I opened https://github.com/mdn/content/pull/4161 with a fix that just drops the note entirely. It seems unnecessary to mention anything at all about CSRF at that point in the article — and that note as currently written is harmful.

**Comment by jmanico** [comment]
Thank you! 😊
