### ISSUE TITLE
Issue with "Django Tutorial Part 6: Generic list and detail vi…": {{ book.author.get_absolute_url }} vs. {% url 'author-detail' book.author.pk %}

### ISSUE THREAD

**Issue by andrehora** [mdn/content#4112]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views

#### What information was incorrect, unhelpful, or incomplete?

Currently, the final note in "Challenge yourself" suggests the usage of the following code in `book_detail.html`:

```html
<p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
```
It would be nice stating that the following snippet could also be used:

```html
<p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
```

At least, adding some short discussion regarding {% url 'author-detail' book.author.pk %} vs. {{ book.author.get_absolute_url }} would make this note richer.

#### Specific section or headline?

- Challenge yourself (Note)
- Creating the Detail View template (Note) 

#### What did you expect to see?

Something like:

```html
<p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
<p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/generic_views`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/generic_views/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by hamishwillee** [comment]
@andrehora Thanks for posting this. You're correct that `get_absolute_url()` is a better approach and we should explain/compare/contrast. I have done that in https://github.com/mdn/content/pull/4150

You will note that I did it in a different place. By the time you get to "Challenge yourself" you should already have the information to do the job. So in that section I just changed to using the `get_absolute_url()` and called it the preferred method. 

Earlier in the doc there is another note which starts with "The author link in the template above has an empty URL". Here I have outlined the options with a brief coverage of the reason for choosing `get_absolute_url()`

Thanks again. I had not thought about the reason for using one or the other before - I just wanted to show both approaches.

**Comment by andrehora** [comment]
@hamishwillee Thanks a lot!
BTW, this documentation is amazing and quite well-written and explained 😄

**Comment by hamishwillee** [comment]
Thanks - glad you like them!
