### ISSUE TITLE
Issue with "Rest parameters": …

### ISSUE THREAD

**Issue by jasontwuk** [mdn/content#412]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters

#### What information was incorrect, unhelpful, or incomplete?
Those side notes end with a question mark (please see the image below), but they are not exactly a question and I think it is somehow misleading.
![screenshot](https://user-images.githubusercontent.com/13745974/102632112-80d6a980-4146-11eb-9d8f-0d0da51ab93f.png)

#### Specific section or headline?
Examples >> Using rest parameters

#### What did you expect to see?
It would be better to remove those question marks.

#### Did you test this? If so, how?
Do not need testing.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/functions/rest_parameters`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/functions/rest_parameters/index.html
* Report started: 2020-12-18T07:25:26.323Z

</details>

**Comment by sideshowbarker** [comment]
This looks like a good change to me. I recommend you go ahead and raise a pull request for it. Or otherwise, lemme know and I can.

**Comment by jasontwuk** [comment]
Great, I will raise a pull request for it. Thank you.

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/414
