### ISSUE TITLE
Issue with "Resources and URIs": (short summary here please)

### ISSUE THREAD

**Issue by SteffenKludt** [mdn/content#4125]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Resources_and_URIs

#### What information was incorrect, unhelpful, or incomplete?
page not found 

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Separating_identity_and_location_of_a_resource

#### What did you expect to see?
a page with information on "Separating identity and location of a resource: the Alt-Svc header"

#### Did you test this? If so, how?
copied the link, pasted it into address bar, loaded it -> same issue

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/resources_and_uris`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Resources_and_URIs
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/resources_and_uris/index.html
* Last commit: https://github.com/mdn/content/commit/8d4fd702d9668604cb2788da5bd9fc9b796ec30a
* Document last modified: 2021-03-17T20:27:56.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/4159 with a fix.
