### ISSUE TITLE
Issue with "Basics of HTTP": (short summary here please)

### ISSUE THREAD

**Issue by SteffenKludt** [mdn/content#4128]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP

#### What information was incorrect, unhelpful, or incomplete?
page not found

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Frame_and_message_structure_in_HTTP_2

#### What did you expect to see?
page about "Frame and message structure in HTTP/2"

#### Did you test this? If so, how?
tried to reload several times

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/basics_of_http`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/index.html
* Last commit: https://github.com/mdn/content/commit/256a46ed339594ed7c6245ab520b952ce5505681
* Document last modified: 2021-03-07T23:19:13.000Z

</details>

**Comment by jculver050** [comment]
Close
