### ISSUE TITLE
Issue with "math:min()": (short summary here please)

### ISSUE THREAD

**Issue by peterbe** [mdn/content#4138]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/EXSLT/math/min

#### What information was incorrect, unhelpful, or incomplete?

Empty notecard. 

#### Specific section or headline?

<img width="865" alt="Screen Shot 2021-04-15 at 1 25 16 PM" src="https://user-images.githubusercontent.com/26739/114912521-167cff80-9dee-11eb-8dd6-289ce8abbd90.png">

#### What did you expect to see?

Some note. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/exslt/math/min`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/EXSLT/math/min
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/exslt/math/min/index.html
* Last commit: https://github.com/mdn/content/commit/8b12e7566336b6b4ee97d87e0889bf55a7d1dde5
* Document last modified: 2021-03-17T09:53:41.000Z

</details>

**Comment by peterbe** [comment]
Similar on http://localhost:5000/en-US/docs/Web/EXSLT/math/highest

<img width="1001" alt="Screen Shot 2021-04-15 at 1 26 22 PM" src="https://user-images.githubusercontent.com/26739/114912591-2dbbed00-9dee-11eb-814d-11db939a8b7f.png">

**Comment by hamishwillee** [comment]
This will be fixed by #4146. Both these cases are removed. I also removed all the other instances in docs that use the Note macro, replacing with notecard divs.
