### ISSUE TITLE
Issue with "Element.scrollTop": note that scrollTop value is negative when display: flex and flex-direction: column-reverse used

### ISSUE THREAD

**Issue by n1kk** [mdn/content#4142]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop

#### What information was incorrect, unhelpful, or incomplete?
`scrollTop` value is negative when `display: flex` and `flex-direction: column-reverse` used.

That's not mentioned on the page, only that if you set it to a negative value it will be 0.

#### What did you expect to see?
Information when this value can be negative. Information when this change was mande. Tried on some old browser I had available, I believe Chrome (68 or around), and there the value was positive with `flex-direction: column-reverse`

#### Did you test this? If so, how?
Checked in latest Firefox, Chrome and Brave and also in old Chrome (~68)
[https://jsfiddle.net/qhua2wmz/27/](https://jsfiddle.net/qhua2wmz/27/) open console and scroll both containers

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/scrolltop`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/scrolltop/index.html
* Last commit: https://github.com/mdn/content/commit/9917bf17a97973166bb3cb3812a496e4117a778f
* Document last modified: 2021-01-11T13:30:57.000Z

</details>

**Comment by postmeback** [comment]
I would like to contribute over here.

Will adding `scrollTop value is negative when display: flex and flex-direction: column-reverse used.` be enough, or something more will be required ?

Looking for guidance
