### ISSUE TITLE
Issue with "Window.location": example#2 uses deprecated true/false paramete in call to window.reload

### ISSUE THREAD

**Issue by wdporter** [mdn/content#4143]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/location

#### What information was incorrect, unhelpful, or incomplete?
Example #2 uses deprecated API

#### Specific section or headline?
Example #2: Force reloading the current page from the server

#### What did you expect to see?
I did not expect to see window.reload(true), since the true/false parameter is deprecated, https://developer.mozilla.org/en-US/docs/Web/API/Location/reload does not mention the parameter

I'm not sure what I expected to see instead, I don't think there is an api that can actually do this

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/location`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/location
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/location/index.html
* Last commit: https://github.com/mdn/content/commit/ba4a07195d8f8f4941e7ae06118b8405f9cac9cf
* Document last modified: 2021-04-10T23:58:36.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/4160 with a fix.
