### ISSUE TITLE
Issue with "CSS Writing Modes": (short summary here please)

### ISSUE THREAD

**Issue by OsvaldoRino** [mdn/content#4147]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Writing_Modes

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_writing_modes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Writing_Modes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_writing_modes/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by hamishwillee** [comment]
Closing as this has no information on any problem
