### ISSUE TITLE
Issue with "Handling text — strings in JavaScript": (short summary here please)

### ISSUE THREAD

**Issue by RPIERIS** [mdn/content#4153]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings

#### What information was incorrect, unhelpful, or incomplete?
On Javascript first Steps you have the below code in explaining [template literals](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings#template_literals) 

```
output = `I like the song "${ song }". I gave it a score of ${ score/highestScore * 100 }%.`;
```
The output from this in the console is 
"I like the song \"Fight the Youth\". I gate it a score of 90%."

The quotation marks, i.e. "", around ${ song } should be removed.
#### Specific section or headline?
Template Literals Section in [handling text - strings in Javascript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings)

#### What did you expect to see?
I didnt expect to see "" in a template literal around the expresion ${ song }

#### Did you test this? If so, how?
Using the console

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/strings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/strings/index.html
* Last commit: https://github.com/mdn/content/commit/ce72a1b3fb7c20b29be8a61425c6ee5504196321
* Document last modified: 2021-04-13T06:10:31.000Z

</details>

**Comment by sideshowbarker** [comment]
> I didnt expect to see "" in a template literal around the expresion ${ song }

Can you explain why not? Is there a problem that it causes? The `"` characters are just literal characters that are intentionally meant to be part of the message output — they’re not being used as string-quoting characters in this context. It’s just the same as if `«` and `»` had been used rather than `"`. Right?

**Comment by RPIERIS** [comment]
You are right. My mistake. 
I forgot that the song i.e. song = `Fight the Youth`; would need to have quotes. Also I somehow thought that " is not needed with template literals... well literally. Will do more research before I put this issues in. Please close the ticket.
Have a good weekend.

**Comment by sideshowbarker** [comment]
OK thanks much, closing per https://github.com/mdn/content/issues/4153#issuecomment-821043478
