### ISSUE TITLE
Issue with "CSS Basic Box Model":  why this article not include border?

### ISSUE THREAD

**Issue by zhangenming** [mdn/content#4158]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model

#### What information was incorrect, unhelpful, or incomplete?
why this article not include border? but have margin adnd padding...Are they different?
I'm wrong or the problem with the article. Thank you

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_box_model/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by zhangenming** [comment]
![image](https://user-images.githubusercontent.com/21235555/114987007-451ad900-9ec7-11eb-8e7a-c9357d80a518.png)
There is another typesetting error. Thank you
I've seen this problem on many pages

**Comment by zhangenming** [comment]
![image](https://user-images.githubusercontent.com/21235555/114987517-d7bb7800-9ec7-11eb-981c-b4a4de5ce180.png)
**And this one,  has a blank space on each line**

**Comment by rachelandrew** [comment]
This is essentially a page for the Basic Box Model specification, borders are part of the Background and Borders specification. That said, it's not very clear. I'll see if I can make it better.

The formatting issue is a known problem and being fixed.

**Comment by zhangenming** [comment]
> The formatting issue is a known problem and being fixed.

if the ul element add any a class will fix this

![image](https://user-images.githubusercontent.com/21235555/120273515-30609c00-c2e1-11eb-89aa-225a3fa1a302.png)
