### ISSUE TITLE
PR companion is down

### ISSUE THREAD

**Issue by Elchi3** [mdn/content#4165]
It doesn't comment on PRs anymore. https://github.com/mdn/content/runs/2359767214?check_suite_focus=true

```
The virtual environment found in /home/runner/work/content/content/yari/deployer/.venv seems to be broken.
Recreating virtualenv deployer in /home/runner/work/content/content/yari/deployer/.venv
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.8.9/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deployer'
```

**Comment by peterbe** [comment]
I've made a hotfix. Can you trigger a re-run of the PR Review Companion by doing something like merging in latest `main` into some PRs and see if it works now?

**Comment by peterbe** [comment]
Oh the timing of this seems very relevant: https://github.com/mdn/content/pull/4155

**Comment by peterbe** [comment]
@nschonni Dependabot question for you... Clearly the snok/install-poetry v1.1.3 Action has a bug in it that prevents us from caching the virtualenv from the first `poetry install`. I'll "raise hell" in their repo to try to figure out what's going on. 
In the meantime, I'd like to revert https://github.com/mdn/content/pull/4155 but then Dependabot will just make a new PR again which'll get automatically merged. Do you know how to prevent a specific GitHub Action to NOT be upgraded? Normally you can tell Dependbot, in it's PRs, that you don't want it, but the bot we're using would merge it almost instantly after it has been created.

**Comment by peterbe** [comment]
@Elchi3 Seems [it worked now](https://github.com/mdn/content/runs/2362033870?check_suite_focus=true)

**Comment by peterbe** [comment]
It's 20s slower because the poetry virtualenv couldn't come from the cache.

**Comment by Elchi3** [comment]
Yup, works again now. Thanks for looking into it!
Close when you feel this is resolved.

**Comment by peterbe** [comment]
I don't understand it, but it's still happening!
https://github.com/mdn/content/runs/2363577774?check_suite_focus=true
Hi @mfuji09 Looking into it.

**Comment by peterbe** [comment]
[Fixed again](https://github.com/mdn/content/pull/4177#issuecomment-821285407)
