### ISSUE TITLE
Issue with "JavaScript": The standard for JavaScript is ECMAScript

### ISSUE THREAD

**Issue by icecream17** [mdn/content#4176]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript

#### What information was incorrect, unhelpful, or incomplete?

It says "The standard for JavaScript is ECMAScript"

Isn't ECMAScript also a language?
The specification is ECMA262 aka the ECMAScript Language Specification

#### Specific section or headline?

Paragraph 3

#### What did you expect to see?

I'm not sure what it should change to. Maybe add a note that "ECMAScript is basically the same as JavaScript"

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/index.html
* Last commit: https://github.com/mdn/content/commit/2c6f017de416f5817a109191417d549c60e90055
* Document last modified: 2021-04-14T07:08:39.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/4196 with an update that basically replaces that entire paragraph with this:

> The standards for JavaScript are the ECMAScript Language Specification (ECMA-262) and the ECMAScript Internationalization API specification (ECMA-402). The JavaScript documentation throughout MDN is based on the latest draft versions of ECMA-262 and ECMA-402. And in cases where some proposals for new ECMAScript features have already been implemented in browsers, documentation and examples in MDN articles may use some of those new features.
