### ISSUE TITLE
Issue with "box-sizing": (weird grammar in first Note just above Syntax heading)

### ISSUE THREAD

**Issue by sinkstyt** [mdn/content#4187]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing

#### What information was incorrect, unhelpful, or incomplete?
This sentence appeared:
`See WHATWG HTML for details on which is Form controls and have this behavior.`

#### Specific section or headline?
box-sizing, first section. Just above Syntax section beginning. First "Note:".

#### What did you expect to see?
perhaps:
`See WHATWG HTML for details on which Form controls also(?) have this behavior.`
or
`See WHATWG HTML for details on which elements have this (default?) behavior.`

#### Did you test this? If so, how?
I did not test this.
<img width="857" alt="Screen Shot 2021-04-16 at 2 08 30 PM" src="https://user-images.githubusercontent.com/60546681/115066297-5a8b0580-9ebd-11eb-8913-61b958852cb0.png">

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/box-sizing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/box-sizing/index.html
* Last commit: https://github.com/mdn/content/commit/50693df1e36db1d2738d676da453c37d953421dc
* Document last modified: 2021-04-08T20:45:35.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/4195 with a fix.
