### ISSUE TITLE
Issue with "mask-origin": star.svg image url can't be loaded because of CORS problem

### ISSUE THREAD

**Issue by html5maker** [mdn/content#4203]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/mask-origin

#### What information was incorrect, unhelpful, or incomplete?
https://mdn.mozillademos.org/files/12676/star.svg is cors protected and the example is not working because of that

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/CSS/mask-origin#setting_mask_origin_to_border-box

#### What did you expect to see?
star mask

#### Did you test this? If so, how?
<img width="394" alt="mask-origin - CSS: Cascading Style Sheets | MDN 2021-04-17 18-36-48" src="https://user-images.githubusercontent.com/27346151/115120132-1b87ad80-9fac-11eb-87db-78c4ab5f9147.png">

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/mask-origin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/mask-origin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/mask-origin/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by sideshowbarker** [comment]
@rachelandrew This seems to be another case like https://github.com/mdn/content/issues/340, https://github.com/mdn/content/issues/2115, and https://github.com/mdn/content/issues/3518.

I opened https://github.com/mdn/content/issues/4209 to track the general issue.
