### ISSUE TITLE
Issue with "Using the Notifications API": Link to deleted page

### ISSUE THREAD

**Issue by nuiva** [mdn/content#4211]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

#### What information was incorrect, unhelpful, or incomplete?

The page contains a link to [https://developer.mozilla.org/en-US/docs/Web/Apps/Build/User_notifications](https://developer.mozilla.org/en-US/docs/Web/Apps/Build/User_notifications), which doesn't exist.

#### Specific section or headline?

[https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API#see_also](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API#see_also)

#### What did you expect to see?

No links to missing pages.

#### Did you test this? If so, how?

Opened the link in my browser and tried searching for the page using the [search tool](https://developer.mozilla.org/en-US/search?q=user+notifications+reference).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/notifications_api/using_the_notifications_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/notifications_api/using_the_notifications_api/index.html
* Last commit: https://github.com/mdn/content/commit/6c2523b8365f2bef7b26dee75ac7c74e686f3f62
* Document last modified: 2021-02-24T02:44:05.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/4227 with a fix.
