### ISSUE TITLE
Content bug: PerformanceElementTiming

### ISSUE THREAD

**Issue by SnorlaxYum** [mdn/content#4217]
## What page(s) did you find the problem on?

[The Page](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceElementTiming)

## Specific page section or heading?

Specifications

## What is the problem?

Unknown specification

## What did you expect to see?

should be linked to this [link](Element Timing API), status should be `Editors' Draft`

## Did you test this? If so, how?

I pulled down the repository, trying to change it. But the param seems to be controlled by functions `SpecName` and `Spec2`, whose code I couldn't find. Seems like the data is fetched from somewhere else

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/4228 with a fix.
