### ISSUE TITLE
Beginner-Understanding "Issue" with "Logical AND (&&)": the short circuit evaluation and the way the operator returns the value of one of the two operands could be _maybe_ explained in a more beginner-friendly way.

### ISSUE THREAD

**Issue by 552020** [mdn/content#4218]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND

#### What information was incorrect, unhelpful, or incomplete?

No one information is incorrect or incomplete, but it was for me also not really helpful to understand the way && returns the values of its operands. 

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND#description

"Description
If expr1 can be converted to true, returns expr2; else, returns expr1."

#### What did you expect to see?

I was working on understanding the meaning of this JSX element and above all of the && operator as used here:

```
const tasty = (
  <ul>
    <li>Applesauce</li>
    { !baby && <li>Pizza</li> }
    { age > 15 && <li>Brussels Sprouts</li> }
    { age > 20 && <li>Oysters</li> }
    { age > 25 && <li>Grappa</li> }
  </ul>
);
```
To reapeat-understand the use of && in this code I went first to the page of MDN for && and I didn't get it. 

As a second reference I use normally Flanagan "The Definitive Guide of Javascript" - The && is explained in the pages 84-85 (4.10.1 Logical AND (&&)). 

Flanagan takes a little more space to explain it but it makes it understandable also for beginners. 

Sorry, that I can't help in elaborate a possible alternative explanation of the &&. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/logical_and`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/logical_and/index.html
* Last commit: https://github.com/mdn/content/commit/020083cf88b0d52a6f07a3d86823592f82bfcaa7
* Document last modified: 2021-04-06T10:44:09.000Z

</details>

**Comment by cw118** [comment]
Hello, is this issue still available? I haven't written documentation before, but I'd like to try making the edits requested. 
I have noticed, however, that similarly worded descriptions were given to the documentation for logical operator OR as well as NOT, so perhaps those would also require modifications if the logical AND page is to be altered?

**Comment by hamishwillee** [comment]
Thanks @cw118 , assigned to you. If it were me I'd start with this document and get some review before progressing to others that are similarly worded.

**Comment by cw118** [comment]
I will do just that then. Thank you so much!

**Comment by hamishwillee** [comment]
No, thank you! To me this doc definitely needs work - after reading it the clear understanding I had of the operator is gone :-(
