### ISSUE TITLE
Issue with "How to do an editorial review": broken link to Articles Needing Editorial Review

### ISSUE THREAD

**Issue by timohaver** [mdn/content#423]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Do_an_editorial_review

#### What information was incorrect, unhelpful, or incomplete?
The link to <em>articles needing editorial review</em> is not working. 

#### Specific section or headline?
What are the steps to do it?

#### What did you expect to see?
I expected to see the web page that lists articles waiting for editorial review, which used to be:
/en-US/docs/needs-review/editorial

#### Did you test this? If so, how?
Attempted to use the link from the page -- as well as the bookmarked URL -- for three consecutive days with different two browsers (FF and Safari).

=== screenshot === 
<img width="624" alt="page-not-found" src="https://user-images.githubusercontent.com/64042475/102664017-ec714480-414f-11eb-8a62-a20bc97f9b53.png">

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/howto/do_an_editorial_review`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Do_an_editorial_review
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/contribute/howto/do_an_editorial_review/index.html
* Report started: 2020-12-18T21:36:49.723Z

</details>

**Comment by sideshowbarker** [comment]
I guess https://developer.mozilla.org/en-US/docs/needs-review/editorial was a feature of the old platform (Kuma) — see https://github.com/mdn/kuma/blob/master/kuma/wiki/jinja2/wiki/list/needs_review.html — which didn’t get carried over to the new platform (Yari). Looking through the Yari sources, I can’t find any equivalent. And I guess it’s possible that the existing *“Needs editorial review”* metadata didn’t get preserved in the transition from Kuma to Yari…

cc @escattone and @peterbe

**Comment by chrisdavidmills** [comment]
I'm working through the user contribution guides gradually, and making sure that it makes sense for the new state of the site. I'll get to this one in due course.

**Comment by chrisdavidmills** [comment]
I've deleted this page altogether; see https://github.com/mdn/content/pull/1098

Closing.
