### ISSUE TITLE
Issue with "Capabilities, constraints, and settings": (short summary here please)

### ISSUE THREAD

**Issue by VictorDenisenko** [mdn/content#4236]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints

#### What information was incorrect, unhelpful, or incomplete?
"Page not found
Sorry, the page /en-US/docs/Web/API/MediaTrackSupportedConstraints/zoom could not be found."
It is for 
brightness 
colorTemperature 
contrast 
focusDistance
pan 
resizeMode 
and others.
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/media_streams_api/constraints`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/media_streams_api/constraints/index.html
* Last commit: https://github.com/mdn/content/commit/56d9a678477f0e79232caa8169114519bf02a44a
* Document last modified: 2021-02-19T19:41:18.000Z

</details>

**Comment by sideshowbarker** [comment]
Where exactly do you see that message being reported?

**Comment by VictorDenisenko** [comment]
See attachment.
 
There are almost all the references are not working.
 
Sincerely,
Victor Denisenko

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/4279 with a fix.

**Comment by VictorDenisenko** [comment]
Why the issue is closed if the links remain broken?
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/focusDistance
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/zoom
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/whiteBalanceMode
etc.

**Comment by sideshowbarker** [comment]
> Why the issue is closed if the links remain broken?

Because it’s fixed in the sources. But in can take up to 48 hours before the changes show up in the production site —

https://github.com/mdn/content/blob/main/README.md#when-will-my-change-show-up-on-the-production-mdn-site

> ### When will my change show up on the production MDN site
> 
> After your pull request is merged, it may take up to 48 hours before the change goes live on the production <https://developer.mozilla.org/> site, but it will usually be quicker.
> 
> - The complete build runs every 24h at around 7PM US/Eastern time, and is then deployed.
> - Once deployment has occurred, it can take up to 24 hours for the associated CDN caches to replace their previously-cached content with the updates.

**Comment by sideshowbarker** [comment]
> Why the issue is closed if the links remain broken?
> [developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/focusDistance](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/focusDistance)
> [developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/zoom](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/zoom)
> [developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/whiteBalanceMode](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/whiteBalanceMode)
> etc.

Ah I misread your question a bit.

We don’t plan on adding pages at https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSupportedConstraints/zoom etc.

Instead the fix was to remove hyperlinks to those pages.

The reason is, those members are all defined on the https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints itself — so there’s no need to have separate pages that just repeat the definitions that already exist on the https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints page.
