### ISSUE TITLE
mixup find vs findIndex doc?

### ISSUE THREAD

**Issue by blq** [mdn/content#4239]
The note warning: "Index 0 will be interpreted as a Falsy value in conditional statements." that is found in find() docs seems to be intended for findIndex() doc.
https://github.com/mdn/content/blob/904d4bece328bd19d8aea952aebf4ed5e05d367c/files/en-us/web/javascript/reference/global_objects/array/find/index.html#L78

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/4247 with a fix.
