### ISSUE TITLE
Incorrectness in polyfill parentNode

### ISSUE THREAD

**Issue by blq** [mdn/content#4240]
This polyfill will throw if parentNode is null while standard says missing parentNode should be treated as a silent passthrough.
(would be odd to have to check parentNode when using a method intended to remove need for parentNode checks)
https://github.com/mdn/content/blob/904d4bece328bd19d8aea952aebf4ed5e05d367c/files/en-us/web/api/childnode/remove/index.html#L59

**Comment by sideshowbarker** [comment]
Thanks for catching this. We are anyway now following a practice of no longer maintaining polyfills within MDN articles. So I’ve opened https://github.com/mdn/content/pull/4243 with a change that removes the polyfill entirely.

If you feel it’s still useful for readers to have polyfill information for ChildNode.p.remove(), and there’s a polyfill somebody’s maintaining elsewhere, we could add a link to the polyfill in the See Also section of the article.

**Comment by blq** [comment]
Ok, I appreciated PF code in the docs, but links are ok too.
I think I based my code on https://github.com/chenzhenxi/element-remove  (that correctly handles parentNode)

Thanks for fixing!

**Comment by sideshowbarker** [comment]
> Ok, I appreciated PF code in the docs, but links are ok too.
> I think I based my code on [chenzhenxi/element-remove](https://github.com/chenzhenxi/element-remove) (that correctly handles parentNode)

OK, I’ve opened https://github.com/mdn/content/pull/4337 to add a link for that.
