### ISSUE TITLE
Content bug: 404

### ISSUE THREAD

**Issue by Devon7** [mdn/content#4251]
## What page(s) did you find the problem on?
https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/start

## Specific page section or heading?
Examples

## What is the problem?
Dead 404 links to https://mdn.github.io/decode-audio-data/
and https://github.com/mdn/decode-audio-data

## What did you expect to see?
Live links.

## Did you test this? If so, how?
Click the links in the last sentence of the paragraph:

> For a more complete example showing start() in use, check out our AudioContext.decodeAudioData() example, You can also run the code example live, or view the source.

Also, the sentences should be separated by a period, not a comma.

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/4282 with a fix.
