### ISSUE TITLE
Issue with "Django Tutorial Part 9: Working with forms": extra ">" in book_renew_librarian.html

### ISSUE THREAD

**Issue by andrehora** [mdn/content#4258]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms

#### What information was incorrect, unhelpful, or incomplete?

The code snippet **book_renew_librarian.html** has an extra ">" in the `<p>` tag, which causes a bug in the generated HTML.

This code...
`<p>{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>`
... should be:
`<p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{book_instance.due_back}}</p>`

https://github.com/mdn/django-locallibrary-tutorial/blob/master/catalog/templates/catalog/book_renew_librarian.html

#### Specific section or headline?

Renew-book form using a Form and function view >> The template

#### What did you expect to see?

```
<p>{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
<p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{book_instance.due_back}}</p>
```

The latter code instead of the former.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/forms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/forms/index.html
* Last commit: https://github.com/mdn/content/commit/f1981f01e4d1b4f0dadab7f2cfc4d2195e6b09aa
* Document last modified: 2021-04-09T23:07:03.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much! Fixed by #4274
