### ISSUE TITLE
Firefox MathML Error message points to archived documentation with broken link.

### ISSUE THREAD

**Issue by sglaser** [mdn/content#4259]
Firefox console shows:

"Support for rendering stretched MathML operators with STIXGeneral fonts is deprecated and may be removed at a future date. For details about newer fonts that will continue to be supported, see https://developer.mozilla.org/docs/Mozilla/MathML_Project/Fonts"

That page has a broken link to [STIXv2.0.2.zip](https://github.com/stipub/stixfonts/raw/master/zipfiles/STIXv2.0.2.zip) 

I was able to locate the fonts in the same repository [STIX2_12-all.zip](https://github.com/stipub/stixfonts/blob/master/zipfiles/STIX2_12-all.zip) so I'm good, but the reference should get fixed.

**Comment by sideshowbarker** [comment]
https://developer.mozilla.org/docs/Mozilla/MathML_Project/Fonts is an archived article, and under the policy for archived articles, it normally wouldn’t get updated.

However, the fact that Firefox reports a console message with a link to that article makes this case a bit different. So I think someone from Mozilla needs to make the call on this one. @Rumyra?

**Comment by himanshugarg** [comment]
[The page](https://developer.mozilla.org/docs/Mozilla/MathML_Project/Fonts ) is no more. Does the message still exist? Searchfox shows no uses of [the constant defining the string](https://searchfox.org/mozilla-central/source/dom/locales/en-US/chrome/dom/dom.properties#383). 

Is there some sample code to see the current message?

**Comment by hamishwillee** [comment]
This missing page is also linked in a number of other places on MDN, including:
- https://developer.mozilla.org/en-US/docs/Web/MathML/Authoring#mathematical_fonts
- https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mi
- https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mo
- https://developer.mozilla.org/en-US/docs/Web/MathML/Element/ms

The original page source can be found here: https://github.com/mdn/archived-content/blob/main/files/en-us/mozilla/mathml_project/fonts/index.html

The easy "fix" is to redirect to that page. IMO though if those fonts are really useful then we should pull the bits that are still relevant back into MDN. 

@Rumyra @sideshowbarker Do you know much about fonts in general/MathML fonts (or can you recommend someone who would know enough to evaluate whether this content is still accurate)?

**Comment by sideshowbarker** [comment]
> @Rumyra @sideshowbarker Do you know much about fonts in general/MathML fonts (or can you recommend someone who would know enough to evaluate whether this content is still accurate)?

About MathML fonts, I reckon @fred-wang would definitely have insight

**Comment by Rumyra** [comment]
I agree @hamishwillee - maybe the thing to do here is pick out the info from the archived article and make a note in the pages that still exist that link to it.

I don't have any knowledge of MathML fonts - but will wait for insight. Then we can move forward 👍

**Comment by hamishwillee** [comment]
@fred-wang Do you think you could help us work out what in https://github.com/mdn/archived-content/blob/main/files/en-us/mozilla/mathml_project/fonts/index.html is still actually useful? 

Specifically, this page is archived, but is linked from Firefox with the note below:

> "Support for rendering stretched MathML operators with STIXGeneral fonts is deprecated and may be removed at a future date. For details about newer fonts that will continue to be supported see [the archived topic]

So we need to know if the fonts linked are useful and how they might be pulled back into the MathML docs.

Generally we probably need to look at whether the MathML docs are "about right" or need a serious revisit - any advice you had on that would be great.

**Comment by fred-wang** [comment]
Yes, I believe the fonts page is still important. Without following the installation instructions there, it's likely that MathML rendering will be very bad with the system fonts. The info should still be "about right". If someone restores the page I can later review and update it.

**Comment by sideshowbarker** [comment]
> If someone restores the page I can later review and update it.

See #8978

**Comment by hamishwillee** [comment]
Thanks @fred-wang @sideshowbarker. 

@fred-wang Restored page that now requires your review is here: https://github.com/mdn/content/blob/main/files/en-us/web/mathml/fonts/index.html

FYI The original issue description referred to a linked file `STIX2_12-all.zip` which is not/no longer in the restored page. So I am presuming the original bug was fixed before this was archived.

**Comment by sideshowbarker** [comment]
> FYI The original issue description referred to a linked file `STIX2_12-all.zip` which is not/no longer in the restored page. So I am presuming the original bug was fixed before this was archived.

I made that change after I copied it over, and did some other cleanup as well. But I’m sure I didn’t catch everything.
