### ISSUE TITLE
Issue with "animation-fill-mode": page in iframe is not found

### ISSUE THREAD

**Issue by arafalov** [mdn/content#426]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode

#### What information was incorrect, unhelpful, or incomplete?
iframe under the examples section uses non-existent URL:
/en-US/docs/Web/CSS/animation-fill-mode/_samples_/Example

#### Did you test this? If so, how?
Firefox/Mac, Also tried pasting the URL manually.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/animation-fill-mode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/animation-fill-mode/index.html
* Report started: 2020-12-18T22:44:48.086Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I raised https://github.com/mdn/content/pull/440 with a fix.

Note that if you run into other articles with this same problem: The cause in this case was that the relevant [`EmbedLiveSample` macro](https://developer.mozilla.org/en-US/docs/MDN/Structures/Live_samples#Live_sample_macros) (which takes the sample code in a given section and loads it into an iframe as an actual document) was using the ID `Example` to reference the section containing the sample code — but the section actually has the ID `Examples` (plural). So all that was needed was to change the ID reference to `Examples` in the macro call.

So going forward, if you run into other articles which have iframes that appear to be broken in the same way as this one, you could, if you want, follow https://github.com/mdn/content/blob/main/README.md#simple-changes to make a quick fix directly in the GitHub UI (that is, without necessarily needing to clone the whole repo, etc.)

But it’s also always fine to raise an issue.
