### ISSUE TITLE
Write an ”Web USB API” overview article (there are existing links to it that are 404)

### ISSUE THREAD

**Issue by rowild** [mdn/content#4267]
On this page:
https://developer.mozilla.org/en-US/docs/Web/API/USB

there is a link to the WebUSB API:
https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API

But that one leads to nowhere. 

IMO the "Web USB API" should be part of the "Specifications" section of the Web APIs overview page:
https://developer.mozilla.org/en-US/docs/Web/API
because it seems to collect all topics that are related to the USB API.

**Comment by sideshowbarker** [comment]
No Web USB API overview has been written yet, so whoever works on this would need to write that overview first.

**Comment by jpmedley** [comment]
@sideshowbarker If you can't get to this, it's under the umbrella of what Google has hired @rachelandrew.

**Comment by sideshowbarker** [comment]
> @sideshowbarker If you can't get to this, it's under the umbrella of what Google has hired @rachelandrew.

Cool — I’ve unassigned it from myself
