### ISSUE TITLE
Issue with "Using CSS transforms": broken image links

### ISSUE THREAD

**Issue by TiagoRR2** [mdn/content#4270]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transforms/Using_CSS_transforms

#### What information was incorrect, unhelpful, or incomplete?

Example images of Rotating and Skewing and Translating have broken links

#### Specific section or headline?
Rotating
Skewing and Translating

#### What did you expect to see?
The example images

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_transforms/using_css_transforms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transforms/Using_CSS_transforms
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_transforms/using_css_transforms/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by rachelandrew** [comment]
These images seem t be loading correctly for me, are you still seeing a problem @TiagoRR2

**Comment by wbamberg** [comment]
See https://github.com/mdn/yari/issues/3796.
