### ISSUE TITLE
Issue with "permissions": Article says there's no GUI

### ISSUE THREAD

**Issue by WesleyBranton** [mdn/content#4275]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions

#### What information was incorrect, unhelpful, or incomplete?
The article claims that there's no GUI in Firefox to see the permissions that an extension uses, claiming that the user needs to manually look at the manifest file. But there is the permissions tab on the Add-on manager that shows the majority of this information, with the exception of the trivial or standard permissions like the Storage API.

#### Specific section or headline?
"There is not yet a simple GUI, for users to view permissions of their installed WebExtension Add-ons.  Users must use about:debugging, go to the Add-ons section, then use the "Manifest Url" link for this Add-on. This shows raw json, which includes a "permissions" block, showing the permissions used by this addon."

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/permissions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/permissions/index.html
* Last commit: https://github.com/mdn/content/commit/2ea50386bea70c1f0db0f2631b13297f08df3680
* Document last modified: 2021-01-29T08:48:22.000Z

</details>

**Comment by caitmuenster** [comment]
Thanks for reporting this, @WesleyBranton!
