### ISSUE TITLE
Issue with "Date.prototype.getDate()": (add details for returning max month day)

### ISSUE THREAD

**Issue by jerardk** [mdn/content#4286]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDate

#### What information was incorrect, unhelpful, or incomplete?
Hello Team, first off I have major respect for the MDN documentation and community.
The below is just a suggestion that I think may further improve the docs on the `Date` functionality for many of us that use these docs as a primary source of truth.
Suggestion: maybe add a note that when a date is initialized like so: `new Date(year, month, 0);` the getDate() function will give the max day of the month

#### Specific section or headline?
Return Value section

#### What did you expect to see?
When a date is created and a value of 0 is passed as the day, the last day of the month will be returned for that month and year.

#### Did you test this? If so, how?
I've tested on the MDN site itself.  Please see screenshot here:

![image](https://user-images.githubusercontent.com/28959557/115342096-b54f8600-a177-11eb-9afd-a5a8b9c67c1d.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/getdate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/getdate/index.html
* Last commit: https://github.com/mdn/content/commit/020083cf88b0d52a6f07a3d86823592f82bfcaa7
* Document last modified: 2021-04-06T10:44:09.000Z

</details>

**Comment by Josh-Cena** [comment]
I think this is fixed by https://github.com/mdn/content/pull/17120. It has nothing to do with `getDate()` itself, but simply because the date constructor underflows and returns the last day of the previous month. (Also worth noting that the month argument is an index, so `new Date("2024", "2", 0)` actually means "getting the 0th day of the 3rd month", which is the last day of February.

**Comment by teoli2003** [comment]
Closing per comment.
