### ISSUE TITLE
Issue with "Alternative style sheets": Browser support outdated

### ISSUE THREAD

**Issue by FrankyBoy** [mdn/content#4290]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Alternative_style_sheets

#### What information was incorrect, unhelpful, or incomplete?

Pretty sure Opera does not support this feature any more since switching to Chromium base. 

#### Specific section or headline?

Browser Compatibility

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/alternative_style_sheets`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Alternative_style_sheets
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/alternative_style_sheets/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by rachelandrew** [comment]
There is a whole chunk of browser specific info at the top of this page which is out of date, in addition to BCD. The demo uses problematic (alluding to mental health conditions) terminology as well.

**Comment by FrankyBoy** [comment]
Hi, the "Yes" should still be removed from Opera in the browser compatibility table. The proper info is:
 
* <= 12:  yes
* > 12: no
