### ISSUE TITLE
Issue with "SubmitEvent.submitter": Incomplete sentence on page

### ISSUE THREAD

**Issue by techncl** [mdn/content#4291]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter

#### What information was incorrect, unhelpful, or incomplete?
It says "While this is often an <input> element whose type or a \<button> whose type is submit,"...

#### Specific section or headline?
Section

#### What did you expect to see?
I think it meant to say "While this is often an \<input> element whose type **is submit** or a \<button> whose type is submit, "
or maybe shorter:

"While this is often an \<input> or \<button> element whose type is submit,"...

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/submitevent/submitter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/submitevent/submitter/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can update this :+1:

**Comment by sideshowbarker** [comment]
@CreaTorAlexander Do you still plan to work on this? Have you raised a PR for it?

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5737 with a fix.

**Comment by techncl** [comment]
Thanks. There is a typo in your new fix, it says

While this is often an <input> element whose **type is submit or a type is submit*` 

(it repeats itself) rather than any of the sentences that I recommended.

**Comment by sideshowbarker** [comment]
> Thanks. There is a typo in your new fix, it says
> 
> While this is often an element whose *_type is submit or a type is submit_`
> 
> (it repeats itself) rather than any of the sentences that I recommended.

oops — fixed now (I think)

**Comment by techncl** [comment]
Cool; looks good. Thanks 👍
