### ISSUE TITLE
[CSS] Implement the `size-adjust` descriptor for @font-face

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#4298]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Implement the `size-adjust` descriptor for @font-face

## Related Gecko bugs

1. - [x] [Implement the `size-adjust` descriptor for @font-face rules](https://bugzilla.mozilla.org/show_bug.cgi?id=1698495). New descriptor to add to the @font-face docs, along with BCD, etc.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
I think this is behind the `layout.css.size-adjust.enabled` flag, enabled by default in Nightly.

**Comment by Rumyra** [comment]
Looks great - closing 👍
