### ISSUE TITLE
[CSS] ascent-override, descent-override, and line-gap-override descriptors

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#4299]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. ascent-override, descent-override, and line-gap-override descriptors

## Related Gecko bugs

1. - [x] [Implement ascent-override, descent-override, and line-gap-override](https://bugzilla.mozilla.org/show_bug.cgi?id=1681691). More descriptors to add.
2. - [x] [Enable the ascent-, descent-, and line-gap-override descriptors on all channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1704494). Enabling bug for the same functionality.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Rumyra** [comment]
Looks good 👍

**Comment by rachelandrew** [comment]
In fact the PR is linked above https://github.com/mdn/data/pull/485

**Comment by HolgerJeromin** [comment]
That was merged one week ago. I thought MDN is updated more often. So I asked if something is missing... Thanks for the info!
