### ISSUE TITLE
[CSS] forced-colors media query

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#4302]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. forced-colors media query

## Related Gecko bugs

1. - [x] [Enable the forced-colors media query](https://bugzilla.mozilla.org/show_bug.cgi?id=1659511). We've got [forced-colors](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors) documented already, so probably just needs a BCD update.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Rumyra** [comment]
Looks great 👍
