### ISSUE TITLE
Issue with "Firefox user agent string reference": FxiOS not included in user agent string

### ISSUE THREAD

**Issue by grantg182** [mdn/content#4303]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox

#### What information was incorrect, unhelpful, or incomplete?
[Firefox for iOS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#firefox_for_ios) does not report FxiOS in the User Agent string as it did previously, prior to iOS 13.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#firefox_for_ios

#### What did you expect to see?
Firefox actually reports the exact same user agent as Safari.

#### Did you test this? If so, how?
Inspected user agents.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/user-agent/firefox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/user-agent/firefox/index.html
* Last commit: https://github.com/mdn/content/commit/8d4fd702d9668604cb2788da5bd9fc9b796ec30a
* Document last modified: 2021-03-17T20:27:56.000Z

</details>

**Comment by dawei-wang** [comment]
Just tested this on iPhone 7 with iOS 15.7 and the latest version of Firefox for mobile and I still saw FxiOS<version>, so I'm not sure if this is a valid issue.

**Comment by Josh-Cena** [comment]
I can also see FxiOS in my UA:

![image](https://user-images.githubusercontent.com/55398995/209380125-f1898a3a-0f77-4f15-8eb7-7b25b7c3131d.jpeg)

Device is iPhone 13, iOS 16.1.1. I would assume that the info is still relevant unless there's clear counter evidence.

**Comment by mriabokliach** [comment]
Nope, currently there is no FxiOS in the user agent.

Using:
iPhone SE
iOS 16.6
Firefox 116.0

![IMG_5858](https://github.com/mdn/content/assets/62096200/7cc2e012-d3a2-4740-a4a1-daf2037c305c)

**Comment by Josh-Cena** [comment]
If the result is inconsistent on different devices, I suspect it's a bug. Let's just observe https://github.com/mozilla-mobile/firefox-ios/issues/6620 instead.

**Comment by cpeterso** [comment]
The `FxiOS` string was recently removed from Firefox iOS's UA string in https://github.com/mozilla-mobile/firefox-ios/pull/15142 because it was causing multiple web compatibility problems (such as https://github.com/mozilla-mobile/firefox-ios/issues/13294).

Confusingly, Focus iOS's UA string _does_ mention `FxiOS`, even though Focus is not Firefox iOS and Firefox iOS's UA string no longer includes `FxiOS`. Updating Focus's UA string is https://github.com/mozilla-mobile/focus-ios/issues/3054.

**Comment by cpeterso** [comment]
`FxiOS` is being added back to Firefox iOS's User-Agent string in this PR: https://github.com/mozilla-mobile/firefox-ios/pull/16176
