### ISSUE TITLE
Missing doc page for :user-valid pseudo-class

### ISSUE THREAD

**Issue by kurahaupo** [mdn/content#4304]
The [release notes for version 88](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/88) indicate that pseudo-classes `:user-valid` and `:user-invalid` are now fully supported, but only the latter is linked to its [description page](https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid).

(I'd guess that a modified clone of [`:user-invalid`](https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid) would suffice as a starting point.)

**Comment by chrisdavidmills** [comment]
Yup, we don't yet have a page for `:user-valid`, unfortunately. The blog post linked from the rel notes has a good example in it, in case that helps for now.

**Comment by kurahaupo** [comment]
I'm working up a patch to create the page, based on the w3 proposal, but I've no idea how to test for availability in other browsers, though I'd _guess_ that no others support it yet.

I've also noted a bunch of related glitches in #4310

**Comment by rachelandrew** [comment]
@kurahaupo this page is done - it's in the PR with merge conflicts I need to fix today along with a bunch of moving things as it involved renaming a prefixed property https://github.com/mdn/content/pull/3707
