### ISSUE TITLE
[CSS] Support the type() function in image-set

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#4306]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Support the type() function in image-set

## Related Gecko bugs

1. - [ ] [Support the type() function in image-set](https://bugzilla.mozilla.org/show_bug.cgi?id=1695404). New CSS function to document. Looks like it just allows you to specify a mime-type in your image-set() values, rather than just 1x, 2x, etc. So probably needs a separate page, but not much detail on there? Needs some research.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by jsnkuhn** [comment]
related #4175. Also why would the `type()` function go on a separate page? It's part of `image-set()`. Just like the `type` attribute is part of the `picture` element.

**Comment by Rumyra** [comment]
Looks great 👍
