### ISSUE TITLE
Outdated/missing doc page for :-moz-ui-valid and :-moz-ui-invalid pseudo-classes

### ISSUE THREAD

**Issue by kurahaupo** [mdn/content#4310]
In checking background details for issue #4304, I found that the `:-moz-ui-valid` pseudo class is documented but `:moz-ui-invalid` is undocumented.

Should a page be added for `:-moz-ui-invalid`?

Since `:user-valid` is supported as of Firefox v88, should `:-moz-ui-valid` be updated to highlight this?

Also, I assume that references to `:moz-ui-valid` should be to `:-moz-ui-valid`?

**Comment by rachelandrew** [comment]
this will be fixed by https://github.com/mdn/content/pull/3707
