### ISSUE TITLE
[JS] Large ArrayBuffers

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#4314]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1.  large arraybuffers

## Related Gecko bugs

1. - [x] [Flip pref for large arraybuffers](https://bugzilla.mozilla.org/show_bug.cgi?id=1703505). Possibly just needs a rel note, but see if we talk about ArrayBuffer size anywhere...

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
- pref for this is `javascript.options.large_arraybuffers`. It is not documented in [Experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features)
- [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) docs.
- [Reference/Errors/Invalid_array_length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length) will need update as it refers to the limit as being defined by 32 bit var.

Can't find anything else.

**Comment by hamishwillee** [comment]
@chrisdavidmills I think this is all done and merged except for marking the dev-doc complete https://bugzilla.mozilla.org/show_bug.cgi?id=1703505#c6

**Comment by chrisdavidmills** [comment]
Yup, agreed. Bug marked as DDC, and closed!
