### ISSUE TITLE
Issue with "tabs.onUpdated": precise that `changeInfo` doesn’t contain `favIconUrl` if the tab lose its favicon

### ISSUE THREAD

**Issue by ariasuni** [mdn/content#4324]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated

#### What information was incorrect, unhelpful, or incomplete?

The documentation lacks an important information about the behavior of the API: `changeInfo` doesn’t contain a `favIconUrl` field when a tab lose (for example, when navigating from a page with a favicon to a page which has no favicon) its favicon. so developers should check the `favIconUrl` field in `tab` if it’s important.

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1450384#c8

#### Specific section or headline?

[changeInfo](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated#changeinfo)

#### What did you expect to see?

An addition to the `faviconUrl` field description along the line: Not present when a tab lose its favicon, developers should instead check the `favIconUrl` field in the returned `tab` object.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/tabs/onupdated`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/tabs/onupdated/index.html
* Last commit: https://github.com/mdn/content/commit/a2b4daf9d130c09fce63c26d2c1172f4b716a28f
* Document last modified: 2021-03-10T16:07:39.000Z

</details>

**Comment by ariasuni** [comment]
Why was this closed? The PR is still open.

**Comment by queengooborg** [comment]
Sorry @ariasuni!  Our idle-labeler bot seems to be having some issues and isn't disabling auto-close for some reason.  We've disabled the workflow for now!
