### ISSUE TITLE
Replace exlicit IDs on headings with Yari generated versions

### ISSUE THREAD

**Issue by nschonni** [mdn/content#434]
Notice there are some duplicate IDs from old wiki copy/paste and also some invalid ID values. If there current ones are stripped off and added by Yari during the build (correctly escaped), this would probably give a more consistent experience.

Downsides to this would be that old anchors would get broken as the heading text changes, but this probably happens already.

**Comment by sideshowbarker** [comment]
I think this has already been dealt with through changes made to Yari after December when this was raised. So I’m going ahead and closing this, with a heads-up to @mdn/core.

But if I’m mistaken, of course this could be re-opened and revisited.
