### ISSUE TITLE
Issue with "Number.parseInt()": radix does seem to default to 10, at least on chrome (89.0.4389.114) and node (v14.7.0)

### ISSUE THREAD

**Issue by avivimgn** [mdn/content#4340]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt

#### What information was incorrect, unhelpful, or incomplete?
Mentioning radix does not default to 10

#### Specific section or headline?
Syntax.Parameters

#### What did you expect to see?
It does default to 10, or at least on chrome and node

#### Did you test this? If so, how?
browser console, node REPL

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/number/parseint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/number/parseint/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by wbamberg** [comment]
[The spec says](https://tc39.es/ecma262/#sec-parseint-string-radix):

> If radix is undefined or 0, it is assumed to be 10 except when the number begins with the code unit pairs 0x or 0X, in which case a radix of 16 is assumed.

So yes, the docs seem to be misleading here.

**Comment by sideshowbarker** [comment]
Thanks for raising this (and thanks @wbamberg for the spec citation) — I’ve opened https://github.com/mdn/content/pull/4546 with a fix.
