### ISSUE TITLE
Issue with "CustomElementRegistry.whenDefined()": return value is an empty Promise

### ISSUE THREAD

**Issue by tmsns** [mdn/content#4342]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined

#### What information was incorrect, unhelpful, or incomplete?

`whenDefined` does return a Promise, but it doesn't seem to contain the promise.

#### Specific section or headline?
- `Syntax`
- `Syntax` > `Return Value`

#### What did you expect to see?
- the syntax should be just `Promise` (or maybe `Promise<void>`?)
- the description of the return value should not mention anything about the constructor. Just that the promise holds `undefined`.

#### Did you test this? If so, how?
Yes, tested it in Chrome 89.0.4389.128.
Also, double checked it with the polyfill: https://github.com/webcomponents/polyfills/blob/master/packages/custom-elements/ts_src/CustomElementRegistry.ts#L309

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/customelementregistry/whendefined`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/customelementregistry/whendefined/index.html
* Last commit: https://github.com/mdn/content/commit/11a98a59fca5f2e448d9e4b70e3c8a538c47b201
* Document last modified: 2021-02-19T19:45:18.000Z

</details>

**Comment by sideshowbarker** [comment]
The wording that’s currently in that MDN article in essentially verbatim from the wording in the spec.

At https://html.spec.whatwg.org/multipage/custom-elements.html#dom-customelementregistry-whendefined-dev, the spec has this:

> Returns a promise that will be fulfilled with the custom element's constructor when a custom element becomes defined with the given name. (If such a custom element is already defined, the returned promise will be immediately fulfilled.) Returns a promise rejected with a "SyntaxError" DOMException if not given a valid custom element name.

And at https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined#syntax MDN has this:

> A Promise that will be fulfilled with the custom element's constructor when a custom element becomes defined with the given name. (If such a custom element is already defined, the returned promise will be immediately fulfilled.)

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/4342#issuecomment-828241183
