### ISSUE TITLE
Issue with "CanvasRenderingContext2D": Refers to SVGMatrix, should refer to DOMMatrix

### ISSUE THREAD

**Issue by builder60** [mdn/content#4348]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D

#### What information was incorrect, unhelpful, or incomplete?
The page says: "The methods listed below remain for historical and compatibility reasons as SVGMatrix objects are used in most parts of the API nowadays and will be used in the future instead."

When I click on SVGMatrix I see the SVGMatrix page which has a huge banner at the top saying SVGMatrix is deprecated. Further down the SVGMatrix page, the reader is referred to DOMMatrix.

#### Specific section or headline?
End of the first paragraph under the Transformations heading.

#### What did you expect to see?
The sentence in question should refer the reader directly to DOMMatrix. At first, I didn't scroll down on the SVGMatrix page so I didn't see the reference to DOMMatrix. Very frustrating.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/index.html
* Last commit: https://github.com/mdn/content/commit/9733300e646aa264e71f7e57768f1d5e08e02b0c
* Document last modified: 2021-03-03T07:08:56.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/4545 with a fix.
