### ISSUE TITLE
Issue with "JavaScript reference": Optional Chaining not include on reference

### ISSUE THREAD

**Issue by fedgrant** [mdn/content#4355]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference

#### What information was incorrect, unhelpful, or incomplete?
There is no link for optional chaining anywhere on the reference page

#### Specific section or headline?
None

#### What did you expect to see?
Link for optional chaining, maybe next to the Property accessors in the Left-hand-side expressions section. 

#### Did you test this? If so, how?
Searched for it on the page, didn't see anything. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/index.html
* Last commit: https://github.com/mdn/content/commit/4a2976fab16bb915f41600bf6d2e50523325bd46
* Document last modified: 2021-03-29T10:38:42.000Z

</details>

**Comment by wbamberg** [comment]
Good point @fedgrant . It's not obvious to me which category under https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference#expressions_and_operators it fits into though. Maybe it needs its own category? @Elchi3 , thoughts?

**Comment by Elchi3** [comment]
Below Property accessors under Left-hand-side expressions makes sense to. Thanks for the PR @fedgrant 👍
