### ISSUE TITLE
8Content bug: <TITLE OF PROBLEM>

### ISSUE THREAD

**Issue by roaddawg** [mdn/content#4361]

**Comment by roaddawg** [comment]
What do I need to do

**Comment by roaddawg** [comment]
When i went to log onto google last night the shut down and another odd looking google page appeared for me to enter pw

**Comment by roaddawg** [comment]
Same thing happened today before i ran maid pro changed pw but hackr might have the new pw

**Comment by wbamberg** [comment]
This tracker is for content issues on https://developer.mozilla.org .
