### ISSUE TITLE
Issue with "Window.open()": Incorrect statement that empty URL only works from the parent

### ISSUE THREAD

**Issue by anforowicz** [mdn/content#4363]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/open

#### What information was incorrect, unhelpful, or incomplete?

This paragraph is incorrect:

If a window with the name already exists, then url is loaded into the existing window. In this case the return value of the method is the existing window and windowFeatures is ignored. Providing an empty string for url is a way to get a reference to an open window by its name without changing the window's location. On Firefox and Chrome (at least), this only works from the same parent, ie. if the current window is the opener of the window you try to get an handle on. Otherwise the call to window.open() will just create a new window.

In particular, the following sentence is incorrect: "On Firefox and Chrome (at least), this only works from the same parent, ie. if the current window is the opener of the window you try to get an handle on."

#### What did you expect to see?

Unsure what I would expect to see.  We'd need to investigate the specs and/or the behavior in Firefox and Chrome more.

#### Did you test this? If so, how?

Yes, I am a Chrome engineer and I often author automated regression tests in Chrome that call `window.open` from a sibling of a frame (not a parent) and it works fine.  Examples:

- `SubresourceLoadingTest.SameSiteSiblingToAboutBlank_CrossSiteTop` testcase (source [here](https://source.chromium.org/chromium/chromium/src/+/master:content/browser/navigation_browsertest.cc;l=4812;drc=c91bd8ea7952b09a97c509376dc9d4371cd359cc)) opens a sibling: `ASSERT_TRUE(ExecJs(child_frame1, "child2 = window.open('', 'child2')"));`
- `ContentScriptTrackerBrowserTest.ContentScriptDeclarationInExtensionManifest_SubframeWithInitialEmptyDoc` testcase (CL [here](https://chromium-review.googlesource.com/c/chromium/src/+/2819118/2/chrome/browser/extensions/content_script_tracker_browsertest.cc#513)) also opens a sibling.

It is also possible to test this manually (I've tested in 90.0.4430.73):

1. Navigate to http://csreis.github.io/tests/cross-site-iframes.html
2. Click "Go same-site" for the only subframe
3. Open a JavaScript console for the only subframe and execute the following: `window.name = "subframe1"`
4. Click the "Add Frame" button on the page
5. Click "Go same-site" button for the 2nd subframe
6. Open a JavaScript console for the 2nd, bottom subframe and execute the following: `sibling = window.open("", "subframe1")`
7. Verify that A) no new tab/window was opened and B) the `sibling` variable points to the first subframe.

Note that the repro steps above behave in the same way even if in step 5 one clicks "Go cross-site (simple page)" (e.g. the opener and the opened window are cross-origin).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/open`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/open
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/open/index.html
* Last commit: https://github.com/mdn/content/commit/6979d7bbf100aaa0ce77aac5436da72acf538fb8
* Document last modified: 2021-04-20T07:40:28.000Z

</details>

**Comment by sideshowbarker** [comment]
Is that *"On Firefox and Chrome (at least), this only works from the same parent, ie. if the current window is the opener of the window you try to get an handle on"* sentence the only part that needs to be changed (completely removed, I guess?), or instead do the first two sentences in that paragraph also need changing?

**Comment by anforowicz** [comment]
> Is that _"On Firefox and Chrome (at least), this only works from the same parent, ie. if the current window is the opener of the window you try to get an handle on"_ sentence the only part that needs to be changed (completely removed, I guess?)

Yes, I think this is the only problematic sentence.  I think that completely removing this sentence should help.  (OTOH, please note that 1) I didn't test the behavior in Firefox and other non-Chromium-based browsers and 2) I haven't tried tracing (e.g. via `git blame` the origins of the problematic sentence.)

> or instead do the first two sentences in that paragraph also need changing?

The first two sentences look correct to me: "If a window with the name already exists, then url is loaded into the existing window. In this case the return value of the method is the existing window and windowFeatures is ignored. "

The third sentence also looks correct to me: "Providing an empty string for url is a way to get a reference to an open window by its name without changing the window's location."

The last sentence also looks correct to me: "Otherwise the call to window.open() will just create a new window."

**Comment by sideshowbarker** [comment]
> > Is that _"On Firefox and Chrome (at least), this only works from the same parent, ie. if the current window is the opener of the window you try to get an handle on"_ sentence the only part that needs to be changed (completely removed, I guess?)
> 
> Yes, I think this is the only problematic sentence. I think that completely removing this sentence should help.

OK, I’ve opened https://github.com/mdn/content/pull/4580 with a change which does tha.

(OTOH, please note that 1) I didn't test the behavior in Firefox and other non-Chromium-based browsers and 2) I haven't tried tracing (e.g. via `git blame` the origins of the problematic sentence.)

We anyway don’t actually have detailed revision history for the sources before 2020-12-15 — because when we really started managing version control for it in git. Before that, it was managed in a CMS, and we don’t any longer have logs of the revision history for that period of time.

Anyway, some parts of this article are very old, and I suspect that problematic statement was probably something that was added quite a long time ago, and nobody revisited it since then.

And regardless, we these days follow a practice of not having ad-hoc statements about browser support in the content of MDN articles but instead putting it into BCD (https://github.com/mdn/browser-compat-data). So if we were to want to have some info such as what’s in that problematic sentence, the place we should put it is anyway as note in the BCD data.

> > or instead do the first two sentences in that paragraph also need changing?
> 
> The first two sentences look correct to me: "If a window with the name already exists, then url is loaded into the existing window. In this case the return value of the method is the existing window and windowFeatures is ignored. "
> 
> The third sentence also looks correct to me: "Providing an empty string for url is a way to get a reference to an open window by its name without changing the window's location."
> 
> The last sentence also looks correct to me: "Otherwise the call to window.open() will just create a new window."

OK, thanks for confirming.
