### ISSUE TITLE
Issue with "HTMLImageElement.crossOrigin": Image not loading

### ISSUE THREAD

**Issue by pixelprogrammer** [mdn/content#4364]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/crossOrigin

#### What information was incorrect, unhelpful, or incomplete?
On the result section, I am getting an error in chrome:
`Error loading image at https://mdn.mozillademos.org/files/16797/clock-demo-400px.png`

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/crossOrigin#result

#### What did you expect to see?
The image in the result, not the error message.

#### Did you test this? If so, how?
I tested this in both Firefox and Chrome and both showed the error message.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlimageelement/crossorigin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/crossOrigin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlimageelement/crossorigin/index.html
* Last commit: https://github.com/mdn/content/commit/11a98a59fca5f2e448d9e4b70e3c8a538c47b201
* Document last modified: 2021-02-19T19:45:18.000Z

</details>

**Comment by CreaTorAlexander** [comment]
I can work on this issue. @pixelprogrammer thanks for catching this

**Comment by chrisdavidmills** [comment]
Thanks @CreaTorAlexander !

**Comment by sideshowbarker** [comment]
Thanks for catching that, and sorry for the delay but I’ve now opened https://github.com/mdn/content/pull/5878 with a fix. As soon as that PR gets merged, this issue will automatically be marked as resolved, and closed.
