### ISSUE TITLE
Content bug: Web Serial API

### ISSUE THREAD

**Issue by noahsb** [mdn/content#4366]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Serial

## Specific page section or heading?

Description

## What is the problem?

Currently, the description reads: 

> "The Serial interface of the Web Serial API provides attributes..."

Where `Web Serial API` appears as a link. However, it is currently not linked to any page.

## What did you expect to see?

While it's likely a page will eventually be created to discuss this, we should probably link to the Web Serial API documentation site to reference what we are talking about.

## Did you test this? If so, how?

Clicked `Web Serial API` link - no change

## Solution

"Web Serial API" in `Description` should route to the Web Serial API documentation website: https://wicg.github.io/serial

I'd be happy to submit a PR to address this if possible. Thanks!

**Comment by rachelandrew** [comment]
This API needs an overview page written, that is what should be linked to here.

cc: @jpmedley as I think this was one we were going to do. I'll assign it to me for now.

**Comment by rachelandrew** [comment]
The page now exists at: https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API so I'll close this, thanks for bringing it to our attention!
