### ISSUE TITLE
Issue with "LocalLibrary base template": Sidebar doesn't appear after completing all the steps

### ISSUE THREAD

**Issue by mohetti** [mdn/content#4370]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/LocalLibrary_base_template

#### What information was incorrect, unhelpful, or incomplete?
"When we get round to running our site, we should see the sidebar appear! In the next sections we will use the above layout to define the individual pages."
I might have done something wrong or my english comprehension is a bit off here (not my mothertongue). I read the text so that the sidebar should appear after completing all the steps from "LocalLibrary base template". That wasn't the case for me. It appeared after the completion of the next section => "Home page".

#### What did you expect to see?
Based on the text I expected to see the sidebar on http://localhost:3000/catalog/ or any of the other specified routes. 

#### Did you test this? If so, how?
Sorry, I

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/locallibrary_base_template`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/LocalLibrary_base_template
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/locallibrary_base_template/index.html
* Last commit: https://github.com/mdn/content/commit/b3eebddc4c3a897597e3602655d596eed67851b6
* Document last modified: 2021-01-29T09:29:22.000Z

</details>

**Comment by hamishwillee** [comment]
@mohetti - it turns out that your English is fine ;-). Fixed in #4399. Thanks very much for taking the time to let us know.

**Comment by mohetti** [comment]
I have to thank you for the overall great content you guys have put together here :) . I find this a really tough subject to get into. But you make it so comfortable for beginners to dive in and understand it bit by bit :). So thanks a lot!

**Comment by hamishwillee** [comment]
You're very welcome!
