### ISSUE TITLE
Issue with "Book list page": Author Name is not displayed in final result

### ISSUE THREAD

**Issue by mohetti** [mdn/content#4373]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_list_page

#### What information was incorrect, unhelpful, or incomplete?

Under the headline View, where  you have to create the book_list.pug following code seems to not work for me:

a(href=book.url) #{book.title}
        |  (#{book.author.name})

As soon as I replaced book.author.name with  (#{book.author.first_name} #{book.author.family_name}) it worked.

#### Specific section or headline?
HEADLINE: VIEW

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/book_list_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_list_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/book_list_page/index.html
* Last commit: https://github.com/mdn/content/commit/b3eebddc4c3a897597e3602655d596eed67851b6
* Document last modified: 2021-01-29T09:29:22.000Z

</details>

**Comment by hamishwillee** [comment]
Hi @mohetti 
What this tells you is that `author.first_name` and `author.family_name` are defined in your code, but `author.name` is not. However if you look at [the documentation of the Author model](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#author_model) you can see that we do define `author.name` (as a virtual method):
```
// Virtual for author's full name
AuthorSchema
.virtual('name')
.get(function () {
  return this.family_name + ', ' + this.first_name;
});
```
I am closing, as this is is almost certainly not an error in the tutorial.
