### ISSUE TITLE
Dead link - AJAX Getting started

### ISSUE THREAD

**Issue by Serchlord** [mdn/content#4378]
Hola! estuve revisando hoy su contenido de ajax y es muy interesante!
lo unico... no pude realizar la prueba porque el archivo test que mencionan en el ejersicio, esta con un enlace que me lleva a una pagina de "not found" ;(

saludos !

**Comment by wbamberg** [comment]
> Hi! I was reviewing your ajax content today and it is very interesting!
The only thing ... I could not perform the test because the test file mentioned in the exercise, is with a link that takes me to a "not found" page; (

Thanks for filing, @Serchlord . Can you provide a link to the page that contained the broken link?

**Comment by Serchlord** [comment]
hey!
this would be the broken link 404 Not Found (w3clubs.com)
<https://www.w3clubs.com/mozdev/test.html>
thanks for answering me! Im trying to improve my ajax skills so I drop by
this exercise but i couldnt make it...hehehe

**Comment by SphinxKnight** [comment]
https://github.com/mdn/content/blob/0e531ce3b42eebfb041583f2428c68b3eb2a1048/files/en-us/web/guide/ajax/getting_started/index.html#L216 is the only en-US file which point to the w3clubs domain (which seems dead).

The exact link exists in some localized docs (all of them being frozen at the time (except zh-tw)).

**Comment by sideshowbarker** [comment]
I’ve opened https://github.com/mdn/content/pull/5810 with a change for this.
