### ISSUE TITLE
Issue with "Client-side form validation": Link to validate.js is outdated

### ISSUE THREAD

**Issue by BulletToothTony** [mdn/content#4382]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation

#### What information was incorrect, unhelpful, or incomplete?

Link to validate.js is incorrect - link goes to https://rickharrison.github.com/validate.js/

#### Specific section or headline?

Under section 'Validating forms without a built-in API'

#### What did you expect to see?

https://rickharrison.github.io/validate.js/

#### Did you test this? If so, how?

Yes, I have tested the correct link (https://rickharrison.github.io/validate.js/) which correctly loads the validate.js github site with download links and examples

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/form_validation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/form_validation/index.html
* Last commit: https://github.com/mdn/content/commit/a5fc9f826f5b3840c482556e6f396ede0d495635
* Document last modified: 2021-02-22T12:48:01.000Z

</details>

**Comment by CreaTorAlexander** [comment]
Thanks for coming up with this, I have raised PR https://github.com/mdn/content/pull/4408 to fix this issue.
