### ISSUE TITLE
Replacing wikihistory file with SQLite database?

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#4387]
Reading https://github.com/mdn/content/pull/4338#issuecomment-825059298 I was wondering, whether it would make sense to use a SQLite3 database instead of a JSON file.

After all, it still gets tracked as a file (even when in binary format), but compresses content better.

(GitHub made me have to choose one issue type).

**Comment by peterbe** [comment]
The JSON file is 3.2MB. If it was a binary blob (probably a bit smaller) and you make 1 single character change, it would mean another 3.2MB added to the git history instead of 1 byte.
