### ISSUE TITLE
Content bug: Update supported themes properties for Firefox 89

### ISSUE THREAD

**Issue by caitmuenster** [mdn/content#4390]
We list and describe supported theming properties on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme. 

There are a couple of updates we'll need to make as a result of changes incoming from Firefox 89: 

1. `tab_background_separator` will not be supported
2. `toolbar_field_separator` will not be supported
3. `tab_line` will behave differently (it will apply a 3px border to all sides of the tab instead of a thick horizontal line to the top border) 
4. `toolbar_vertical_separator` will no longer show up near the hamburger menu

See this [blog post](https://blog.mozilla.org/addons/2021/04/19/changes-to-themeable-areas-of-firefox-in-version-89/) for examples and more descriptions.

**Comment by Shinyaigeek** [comment]
Can I pick this issue?

**Comment by chrisdavidmills** [comment]
Thanks @caitmuenster ; I've added it to the Firefox 89 project board. Did you have someone already working on this, or can @Shinyaigeek help with doing the work?

**Comment by caitmuenster** [comment]
Hi @Shinyaigeek, thank you for your willingness to help! 🙏 Here are a couple of expectations for the update: 

- When updating the properties that will no longer be supported in the Colors table, add the "thumbs down" emoji next to the property name, and add a note about the deprecation timeline in the "Description" column. See example: 

<img width="861" alt="Screen Shot 2021-04-26 at 2 09 42 PM" src="https://user-images.githubusercontent.com/23342476/116151339-57500080-a699-11eb-9806-424de43b1e4b.png">

- You'll need to update the screenshots for `tab_line` and 'toolbar_vertical_separator'. I recommend that you open a fresh profile of Firefox Beta or Nightly and install a theme like [Black Matte (Red)](https://addons.mozilla.org/en-US/firefox/addon/matte-black-red/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) and use that for the screenshot.

Feel free to tag me in your PR for review!

**Comment by Shinyaigeek** [comment]
@caitmuenster Thank you for very helpfull instruction for updates!! I sent pull request to solve this issue!! (#4648 )

**Comment by chrisdavidmills** [comment]
Looks like ths one is complete, so closing!
