### ISSUE TITLE
Issue with "Building a cross-browser extension": Firefox account two-factor authentication requirement

### ISSUE THREAD

**Issue by mariyan-borisov** [mdn/content#4395]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

#### What information was incorrect, unhelpful, or incomplete?
According to [a blog post](https://blog.mozilla.org/addons/2021/03/11/two-factor-authentication-required-for-extension-developers/), the two-factor authentication is now required for publishing a Firefox extension. The MDN article says "No" instead of "Yes" in the "Account two factor authentication" column.

#### Specific section or headline?
Extension publishing

#### What did you expect to see?
I expect the "Account two factor authentication" for "Firefox" to be "Yes".

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by caitmuenster** [comment]
Thanks @mariyan-borisov. 

This is a good first issue. If you'd like to work on it, please leave a comment here and tag me to review your PR when it is ready.

**Comment by jmrodwell** [comment]
Hi @caitmuenster I happy to take this as my first issue. Thanks.

**Comment by nirban256** [comment]
Hi! @caitmuenster happy to solve this as my first issue
