### ISSUE TITLE
Issue with "Django Tutorial Part 9: Working with forms": http://127.0.0.1:8000/catalog/author/10

### ISSUE THREAD

**Issue by andrehora** [mdn/content#4396]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms

#### What information was incorrect, unhelpful, or incomplete?

This URL...
`http://127.0.0.1:8000/catalog/authors/10`

... should be:
`http://127.0.0.1:8000/catalog/author/10`

authors => author

#### Specific section or headline?

Generic editing views>>Testing the page

#### What did you expect to see?

"Enter values for the fields and then press Submit to save the author record. You should now be taken to a detail view for your new author, with a URL of something like http://127.0.0.1:8000/catalog/author/10."

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/forms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/forms/index.html
* Last commit: https://github.com/mdn/content/commit/f1981f01e4d1b4f0dadab7f2cfc4d2195e6b09aa
* Document last modified: 2021-04-09T23:07:03.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for reporting. Fixed in #4466
