### ISSUE TITLE
Issue with "Web audio codec guide": Broken anchors

### ISSUE THREAD

**Issue by mariyan-borisov** [mdn/content#4397]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs

#### What information was incorrect, unhelpful, or incomplete?
Nothing happens when some of the anchors in the "Common codecs" is clicked.

#### Specific section or headline?
Common codecs:
* AAC
* ALAC
* AMR
* FLAC
* G.711
* G.722
* MP3

Opus and Vorbis don't seem to be affected.

#### What did you expect to see?
For example, when I click "AAC" it should take me to "AAC (Advanced Audio Coding)" section.

#### Did you test this? If so, how?
Yes. I clicked on "AAC" and nothing happened.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/media/formats/audio_codecs`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/media/formats/audio_codecs/index.html
* Last commit: https://github.com/mdn/content/commit/3bc73e4698262e60e9bcf5938dfd8d3409e8bb42
* Document last modified: 2021-03-29T10:19:09.000Z

</details>

**Comment by mariyan-borisov** [comment]
["Web video codec guide"](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs) seems to have the same issue as well: ["HEVC (H.265)"](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#hevc).

**Comment by hamishwillee** [comment]
This occurs because the content is included into the page, and the links in that included content are local anchors. I'm working on removing the page macro so I'll fix this up.
