### ISSUE TITLE
Content bug: 2,178 distinct http:// URLs 

### ISSUE THREAD

**Issue by peterbe** [mdn/content#4414]
When working on https://github.com/mdn/yari/issues/3565 I logged every time the flaw checker discovered a link to a `http://` URL.  Then I analyzed that a bit. 

- 2,178 distinct `<a href=http://...>` links in all of en-US
- 989 distinct MDN docs that have one or more of these
- 1,030 distinct domains of these 2,178 URLs
  - 73.4% will work if you just replace `http://` with `https://`
  - 26.6% will work *not* if you just replace `http://` with `https://`

So roughly 73% of 2,178 can be fixed automatically and don't need to be questioned or manually curated.

**Comment by peterbe** [comment]
Here's my log file after testing each (unique by domain) URL to see what happens if you do `url.replace('http://', 'https://')`
https://gist.github.com/peterbe/d898addf6b76b906ef3a71d5d7618b6c

**Comment by peterbe** [comment]
I think enough has been done now. We have a `build/flaws/safe-to-https-domains.json` file in Yari and we highlight use of `http://` URLs in the PR Review Companion. People are slowly working on cleaning it up.

**Comment by hamishwillee** [comment]
Thanks @peterbe - I think this approach has worked well.
