### ISSUE TITLE
Issue with "Accessibility": Broken link to AT dev

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#4426]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility

#### What information was incorrect, unhelpful, or incomplete?

The link to „Assistive technology (AT) development” is broken.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/Accessibility#other_documentation

„Assistive technology (AT) development” is a dead end.

https://github.com/mdn/content/blob/c70ad7c8f3af456eef5ce85420c3edc778694f8b/files/en-us/web/accessibility/index.html#L42-L43

#### What did you expect to see?

I could not figure out another aim in that page of the codebase. So I guess, it's „best” to remove the link :crying_cat_face: 

#### Did you test this? If so, how?

Discovered while working on #4425 by a red border.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/index.html
* Last commit: https://github.com/mdn/content/commit/2d48835e97e7d226431f2be1a74558117fb44d0e
* Document last modified: 2021-02-03T18:43:39.000Z

</details>

**Comment by sideshowbarker** [comment]
I’ve gone ahead and opened https://github.com/mdn/content/pull/5813 with a change that drops the link.
