### ISSUE TITLE
Issue with "Number.MIN_VALUE": Incorrect value mentioned in Description

### ISSUE THREAD

**Issue by kwhatmough** [mdn/content#4427]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_VALUE

#### What information was incorrect, unhelpful, or incomplete?
The excerpt below is incorrect since the value of `Number.MIN_VALUE` is 2<sup>-1074</sup>:
> `Number.MIN_VALUE` is `5e-324`

#### Specific section or headline?
The Description section.

#### What did you expect to see?
`Number.MIN_VALUE` is 2<sup>-1074</sup> or approximately `5e-324`

#### Did you test this? If so, how?
Yes I tested it successfully using the dev console of Chrome Version 90.0.4430.72 as follows:
![image](https://user-images.githubusercontent.com/649721/115918089-119afa00-a445-11eb-9372-941577243e97.png)
![image](https://user-images.githubusercontent.com/649721/115918887-17450f80-a446-11eb-9dbc-f2fc0b37fb3c.png)
As you can see, the value `5e-324` is only approximate:
![image](https://user-images.githubusercontent.com/649721/115919051-4fe4e900-a446-11eb-8775-16b1920ee600.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/number/min_value`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_VALUE
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/number/min_value/index.html
* Last commit: https://github.com/mdn/content/commit/020083cf88b0d52a6f07a3d86823592f82bfcaa7
* Document last modified: 2021-04-06T10:44:09.000Z

</details>

**Comment by sideshowbarker** [comment]
I get `5e-324` for `Number.MIN_VALUE` in every browser I’ve tested with — as well as in Node:
```
$ node
Welcome to Node.js v16.0.0.
Type ".help" for more information.
> Number.MIN_VALUE
5e-324
```
So I don’t understand what should be changed in article.

**Comment by kwhatmough** [comment]
> I get `5e-324` for `Number.MIN_VALUE` in every browser I’ve tested with — as well as in Node:
> 
> ```
> $ node
> Welcome to Node.js v16.0.0.
> Type ".help" for more information.
> > Number.MIN_VALUE
> 5e-324
> ```
> 
> So I don’t understand what should be changed in article.

@sideshowbarker The value you are seeing is only an approximation of the actual value. When JavaScript converts a number to a string, the value printed is not always the actual value. This illustrates what I mean:
![image](https://user-images.githubusercontent.com/649721/116459485-ded17700-a833-11eb-959d-8889f166cbeb.png)

The MDN page says "`Number.MIN_VALUE` is `5e-324`" which is wrong. The real value of `Number.MIN_VALUE` is 2<sup>-1074</sup>. 5 times 10<sup>-324</sup> does not equal 2<sup>-1074</sup>. The [Java SDK documentation for `Double.MIN_VALUE`](https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html) is a good example of a correct description:
> A constant holding the smallest positive nonzero value of type double, 2<sup>-1074</sup>.

The MDN page should be changed to say something like this:
`Number.MIN_VALUE` is 2<sup>-1074</sup> or approximately `5e-324`

**Comment by sideshowbarker** [comment]
Thanks for the clarifications.

After looking at the ECMAScript spec, I think we can’t actually state in MDN that there’s a precise value which all implementations a required to support — because as far as I can tell from reading the ECMAScript spec, the value is actually implementation-dependent:

https://tc39.es/ecma262/#sec-number.min_value
> The value of Number.MIN_VALUE is the smallest positive value of the Number type, which is **approximately** 5 × 10<sup>-324</sup>.
> 
> In the IEEE 754-2019 double precision binary representation, the smallest possible value is a denormalized number. If an implementation does not support denormalized values, **the value of Number.MIN_VALUE must be the smallest non-zero positive value that can actually be represented by the implementation**.

Emphasis added — the main points being that the ES spec says the value is **approximately** 5 × 10<sup>-324</sup>, and intentionally doesn’t state any more precise value than than, but in fact says the actual value can be whatever the smallest value is that the implementation is capable of handling.

So given all that, I’ll open a pull request with a patch that says something like this:

> Number.MIN_VALUE is the smallest positive number that can be represented within float precision; that is, as close as you can get to zero. That’s approximately 5e-324 (5 × 10<sup>-324</sup>). The ECMAScript spec doesn’t define a precise value that implementations are required to support — instead the spec says, “must be the smallest non-zero positive value that can actually be represented by the implementation”. But in practice, its precise value in browser engines and in Node.js is 2<sup>-1074</sup>.

**Comment by sideshowbarker** [comment]
OK, I’ve opened https://github.com/mdn/content/pull/4579 for this.

**Comment by kwhatmough** [comment]
Thank you very much. That is good to know, and is very helpful.
