### ISSUE TITLE
Issue with "<input type="datetime">": No compatibility table

### ISSUE THREAD

**Issue by eatmorepies-dev** [mdn/content#4431]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime

#### What information was incorrect, unhelpful, or incomplete?
The Deprecated section makes reference to a nonexistent "Compatibility table".

#### Specific section or headline?
Deprecated

#### What did you expect to see?
An associated Compatibility table

#### Did you test this? If so, how?
Clicking the compatibility table link in the Deprecated section. It just linked to the top of the page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/datetime`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/datetime/index.html
* Last commit: https://github.com/mdn/content/commit/0c31e2bc4d6601a079bc57521e79529539c8cf68
* Document last modified: 2021-01-20T20:24:12.000Z

</details>

**Comment by rachelandrew** [comment]
@eatmorepies-dev thanks for raising this, I don't think there is support for this feature and so we don't have a compat table for it. I'll update the note at the top.
