### ISSUE TITLE
Issue with "<input type="time">": Incorrect grammar

### ISSUE THREAD

**Issue by Frontend-io** [mdn/content#4441]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

#### What information was incorrect, unhelpful, or incomplete?
The word 'are' is missing from the line; "... and there multiple ways in which people write times, such as: ..."

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#handling_browser_support
Last line in the 3rd paragraph

#### What did you expect to see?
"... and there [ are ] multiple ways in which people write times, such as: ..."

#### Did you test this? If so, how?
No, it is simply a text.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/time`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/time/index.html
* Last commit: https://github.com/mdn/content/commit/690965e33f6663ef450e6ed9edd9a7e7f73f96c5
* Document last modified: 2021-03-27T00:58:07.000Z

</details>

**Comment by Jobtye** [comment]
Sorted #4443

**Comment by SphinxKnight** [comment]
Thanks @Jobtye for the fix :)
