### ISSUE TITLE
Issue with "HTMLSlotElement.assignedNodes()": misleading phrasing

### ISSUE THREAD

**Issue by Leokuma** [mdn/content#4446]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedNodes

#### What information was incorrect, unhelpful, or incomplete?
The article states that, if no assigned nodes are found, the function returns the slot's fallback content.

I believe that is only true if the `options` parameter is passed the value `{flatten: true}`. I think the article doesn't make that clear enough.

#### Specific section or headline?
At the very beginning of the article:
> The assignedNodes() property of the HTMLSlotElement interface returns a sequence of the nodes assigned to this slot, and if the flatten option is set to true, the assigned nodes of any other slots that are descendants of this slot. **If no assigned nodes are found, it returns the slot's fallback content**.

Same problem in these pages, which basically repeat that paragraph:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedElements
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement

#### What did you expect to see?
I think the following changes would make it clearer that the section I highlighted above only applies if `flatten` is set to `true`:

> The assignedNodes() property of the HTMLSlotElement interface returns a sequence of the nodes assigned to this slot.
>
> If the flatten option is set to true, it returns a sequence of the assigned nodes of any other slots that are descendants of this slot, and if no assigned nodes are found, it returns the slot's fallback content.

#### Did you test this? If so, how?
Same results in Firefox and Chrome:

![image](https://user-images.githubusercontent.com/9329952/115978210-3d58d580-a554-11eb-89f6-8479663ec4c9.png)

The `<button>` is part of the slot's fallback content and is only returned with `{flatten: true}`.

The [spec](https://html.spec.whatwg.org/multipage/scripting.html#htmlslotelement) seems to confirm that:

![image](https://user-images.githubusercontent.com/9329952/115978490-21563380-a556-11eb-8ce9-69a9fc07c9c1.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlslotelement/assignednodes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedNodes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlslotelement/assignednodes/index.html
* Last commit: https://github.com/mdn/content/commit/11c96e424b376432f8ab8ebb12a40e5383e31e9d
* Document last modified: 2021-03-30T03:01:23.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this — I’ve opened #11772 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
