### ISSUE TITLE
Issue with "Window.toolbar": …

### ISSUE THREAD

**Issue by nschonni** [mdn/content#446]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/toolbar

#### What information was incorrect, unhelpful, or incomplete?

The sample image from `<p>When you load the example page above, the browser displays the following dialog: <img alt="Image:Modify_any_open_window_dialog.png"></p>` is missing a source and isn't in the repo

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/toolbar`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/toolbar
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/window/toolbar/index.html
* Report started: 2020-12-19T01:56:04.527Z

</details>

**Comment by hamishwillee** [comment]
Yeah, that appears to have been missing forever (according to wayback machine) - e.g. https://web.archive.org/web/20190808182343/https://developer.mozilla.org/en-US/docs/Web/API/Window/toolbar

Most of this is so out of date I'd say pointless to keep. I have therefore removed most of it in #716. Users will still be able to find the detail on the very old versions of Firefox from a link within the doc.

**Comment by nschonni** [comment]
OK, maybe something to "archive" after you clean it up a bit

**Comment by hamishwillee** [comment]
Yes - I did that clean up in #716 :-)
