### ISSUE TITLE
Issue with "Writing style guide": Incorrect link and spelling

### ISSUE THREAD

**Issue by gojanedoe** [mdn/content#4462]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide

#### What information was incorrect, unhelpful, or incomplete?
This sentence: "For example, if you [look up "behavior"](http://www.dictionary.com/browse/behavior), you find the phrase "Chiefly British" followed by a link to the American standard form, "[behavior](http://dictionary.reference.com/browse/behavior)"." 

It seems like the example is supposed to show two spellings of behavior, one "Chiefly British" and one "American", but the links and spellings are instead the same. The link to "behavior" on Dictionary.com does _not_ contain the phrase "Chiefly British", as described above (but the link to "behaviour" does: [https://www.dictionary.com/browse/behaviour](url)).

#### Specific section or headline?
Spelling section

#### What did you expect to see?
I expected the first spelling to be "behaviour" and to link to the corresponding Dictionary.com link:

"For example, if you [look up "behaviour"](https://www.dictionary.com/browse/behaviour), you find the phrase "Chiefly British" followed by a link to the American standard form, "[behavior](http://dictionary.reference.com/browse/behavior)"." 

#### Did you test this? If so, how?
I clicked on the links to make sure they had the right examples used.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/guidelines/writing_style_guide`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/writing_style_guide/index.html
* Last commit: https://github.com/mdn/content/commit/dd445c607ac44c795081a0db56c6d1195e1ef353
* Document last modified: 2021-02-24T21:26:33.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. This will be fixed by #4465.
