### ISSUE TITLE
The CSS transform function rotate() have wrong spin example

### ISSUE THREAD

**Issue by gustavopi** [mdn/content#4463]
In the example of the rotate(45deg) the square is in fact rotated by -45deg
[https://developer.mozilla.org/pt-BR/docs/Web/CSS/transform-function/rotate()](url)

**Comment by rachelandrew** [comment]
@gustavopi the example is a live rendering of the code, so the CSS as written is what is giving the output you are seeing. Therefore I think it's correct.

**Comment by gustavopi** [comment]
The page in my language (ptBR) is not running the example anymore, FireFox is blocking the example from being executed. The page in english is ok, the box is rotating clockwise. Will see later in another browser about ptBR example...

**Comment by gustavopi** [comment]
Here is:
[https://media.prod.mdn.mozit.cloud/attachments/2015/12/14/12113/784a3c80827009d3fca248745bf64129/rotate.png](url)
This image is not showing correctly what is a 19.5deg rotation.
The example is blank in safari, in Chrome the connection with "yari-demos.prod.mdn.mozit.cloud" is refused. Thought the programmer will quickly find the right way to use rotate(), but will be nice to fix the page anyway.

**Comment by rachelandrew** [comment]
@chrisdavidmills this one also needs transferring (I don't have the ability to do it), it's raised on the Portuguese docs.

**Comment by chrisdavidmills** [comment]
Ah, in that case I'm going to close this one. `pt-BR` isn't a [tier 1 locale](https://github.com/mdn/translated-content#tier-1-locales), so we won't currently accept any changes to this content.
