### ISSUE TITLE
Issue with "Looping code": (short summary here please)

### ISSUE THREAD

**Issue by mars3812** [mdn/content#4497]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code

#### What information was incorrect, unhelpful, or incomplete?
let output = document.querySelector('.output');
output.innerHTML = '';

let i = 10;
while(i >= 0) {
 **let para** = document.createElement('p');
 if(i === 10) {
 para.textContent = 'Countdown ' + i;
 } else if(i === 0) {
  para.textContent = 'Blast off!';
 } else {
 para.textContent = i;
 }
output.appendChild(para);
 i--;
}
__________________________________
let output = document.querySelector('.output');
output.innerHTML = '';

// let i = 10;

// **const para** = document.createElement('p');
// para.textContent = ;
// output.appendChild(para);

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/looping_code`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/looping_code/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Can you please elaborate on exactly what you think needs changing?

**Comment by sideshowbarker** [comment]
Closing for lack of response.
