### ISSUE TITLE
Issue with "Test your skills: HTML text basics": (short summary here please)

### ISSUE THREAD

**Issue by migraineman** [mdn/content#4499]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/test_your_skills_colon__html_text_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/test_your_skills_colon__html_text_basics/index.html
* Last commit: https://github.com/mdn/content/commit/88b8dc61828f0c111b5eda4197921dcf153f3b0f
* Document last modified: 2020-12-15T16:53:05.000Z

</details>

**Comment by migraineman** [comment]
In html text basics 1, 2, and 3 you keep saying to make it like the finished example, but there is no finished example.

**Comment by chrisdavidmills** [comment]
This is a good point — we were saying "recreate", but really we mean "create". I've updated the wording in https://github.com/mdn/content/commit/c317bc0196ebd8b0e618b6e74e94e97728a2d372.

thanks for reporting this.
