### ISSUE TITLE
Issue with "CustomElementRegistry.whenDefined()": Missing Then 

### ISSUE THREAD

**Issue by kp2017** [mdn/content#4502]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined

**Current**
await Promise.all(promises); 
container.removeChild(placeholder); 

**should be:**
await Promise.all(promises)
.then(
container.removeChild(placeholder);)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/customelementregistry/whendefined`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/customelementregistry/whendefined/index.html
* Last commit: https://github.com/mdn/content/commit/11a98a59fca5f2e448d9e4b70e3c8a538c47b201
* Document last modified: 2021-02-19T19:45:18.000Z

</details>

**Comment by Leokuma** [comment]
Well, it's not exactly "wrong", but it could be more clear.

The problem is that the code snippet uses `await` outside of an `async` function, which is currently not supported.

It could either wrap the code in an async function or use `then()` instead of `await`.

**Comment by Blakelist7** [comment]
@sideshowbarker can I work on this?
