### ISSUE TITLE
Issue with "Express Tutorial Part 7: Deploying to production": (short summary here please)

### ISSUE THREAD

**Issue by duke33** [mdn/content#4503]
So here https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment#setting_configuration_variables

In this code:

```
>heroku config:set MONGODB_URI='mongodb+srv://cooluser:coolpassword@cluster0-mbdj7.mongodb.net/local_library?retryWrites=true'
Setting MONGODB_URI and restarting limitless-tor-18923... done, v13
MONGODB_URI: mongodb+srv://cooluser:coolpassword@cluster0-mbdj7.mongodb.net/local_library?retryWrites=true
```
MONGODB_URI should not be set in-between single quotation marks, at least, it did not work for me that way. I had to delete them to make it work. I think it is the way you are supposed to define variables in an .env file, but since I'm new to this stuff, I might be wrong.  

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/deployment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/deployment/index.html
* Last commit: https://github.com/mdn/content/commit/4b9d9a8bf3ab3db9f7b1efc89b5a91bbf459fe07
* Document last modified: 2021-03-01T12:15:15.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @duke33. Annoyingly I've changed this back and forth a few times - so I think that perhaps heroku are messing with us. 
I'll add a note that if one way doesn't work, try another.

**Comment by duke33** [comment]
Thank you @hamishwillee !
