### ISSUE TITLE
Content bug:  broken image in "Media Object" section, under "Typical use cases of Flexbox" guide

### ISSUE THREAD

**Issue by pietrop** [mdn/content#4510]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox#media_objects

## Specific page section or heading?

Typical use cases of Flexbox --> Media objects

## What is the problem?

 broken image in media Object flex box example, see screenshot below: 

<img width="797" alt="Screen Shot 2021-04-26 at 11 24 49 PM" src="https://user-images.githubusercontent.com/4661975/116180335-bab44f80-a6e6-11eb-9a00-1c961208c39f.png">

## What did you expect to see?

I expected to see a place holder image, rather then a broke one

<img width="813" alt="Screen Shot 2021-04-26 at 11 24 56 PM" src="https://user-images.githubusercontent.com/4661975/116180350-c3a52100-a6e6-11eb-9f1c-1d458038e8f0.png">

(In this example I used https://via.placeholder.com/)

## Did you test this? If so, how?

The site being used for the image, might be missing a certificate eg both https://placehold.it/60x60 and https://placehold.it give this warning if you navigate directly there

<img width="935" alt="Screen Shot 2021-04-26 at 11 27 04 PM" src="https://user-images.githubusercontent.com/4661975/116180456-ef280b80-a6e6-11eb-9350-50924548bd23.png">

and as you can see the browser shows you there's no valid certificate etc..
<img width="935" alt="Screen Shot 2021-04-26 at 11 27 07 PM" src="https://user-images.githubusercontent.com/4661975/116180462-f222fc00-a6e6-11eb-94f2-1d6a43effa83.png">

**Comment by rachelandrew** [comment]
This is now fixed, I updated the example to use a local image. Thanks for the report @pietrop
