### ISSUE TITLE
Content bug: ShadowRoot.delegatesFocus was recently incorrectly marked as deprecated

### ISSUE THREAD

**Issue by ekashida** [mdn/content#4518]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/delegatesFocus

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/delegatesFocus#deprecated

## What is the problem?

This feature was marked as deprecated:
https://github.com/mdn/content/pull/4226/files#diff-255787f14b4dfc03561fb12d48a7118a69788ca770798d0f8bdcb80b9da94299

Safari is the only browser that hasn't released this feature yet, but it has been implemented (https://bugs.webkit.org/show_bug.cgi?id=166484) and is part of their V1 Shadow DOM story (https://bugs.webkit.org/show_bug.cgi?id=148695). 

## What did you expect to see?

This feature should not be marked as deprecated.

## Did you test this? If so, how?

No.

**Comment by Elchi3** [comment]
Thanks for your issue report! This was already un-deprecated in https://github.com/mdn/content/pull/4508. Should be live on the site soon
