### ISSUE TITLE
Issue with "Using the Web Storage API": Broken External Link

### ISSUE THREAD

**Issue by mkuehn** [mdn/content#4520]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

#### What information was incorrect, unhelpful, or incomplete?

Broken link to external content.

#### Specific section or headline?

"Here is a detailed rundown of all the storage capacities for various browsers." at the bottom of the page.

#### What did you expect to see?

The external website loads.

#### Did you test this? If so, how?

Yes, by clicking on the link, which raises a security error in Chrome first, then resolves to a 404 page on the host.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/web_storage_api/using_the_web_storage_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_storage_api/using_the_web_storage_api/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by teoli2003** [comment]
Hi, @mkuehn !

Thanks for the report. It works for me: can you test it again? It may have been a temporary error on the website.

**Comment by sideshowbarker** [comment]
I’m also unable to find any link in that article which is currently broken, and we’ve gotten no response from the OP, so let’s go ahead and close those.
