### ISSUE TITLE
Issue with "ARIA: Mark role": “mark” is not a landmark role

### ISSUE THREAD

**Issue by scottaohara** [mdn/content#4525]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Mark_role

#### What information was incorrect, unhelpful, or incomplete?
`mark` is not a landmark role

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/roles/mark_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Mark_role
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/roles/mark_role/index.html
* Last commit: https://github.com/mdn/content/commit/1e8c048d86584064ca418a214063cb965fab3e71
* Document last modified: 2021-03-23T09:11:33.000Z

</details>

**Comment by Ryuno-Ki** [comment]
It's not having any implicit ARIA role at all according to https://w3c.github.io/html-aria/#el-mark

@ericwbailey What now? Deleting the page?

**Comment by scottaohara** [comment]
@Ryuno-Ki `mark` isn't even slated to officially be part of ARIA until 1.3 is released. 

it's only in the current [working draft](https://w3c.github.io/aria/#mark) and only has implementations in some browsers, if i recall correctly.

FYI: ARIA in HTML is behind on indicating the implicit ARIA roles for some HTML elements while we wait for ARIA 1.2 to leave CR.

**Comment by ericwbailey** [comment]
@Ryuno-Ki I don't think we should delete, but I do think we should strongly communicate that this is not ready for production use.

**Comment by Ryuno-Ki** [comment]
@scottaohara Do you want to give it a try?

The file in question can be found here:
https://github.com/mdn/content/blob/e36a7213f866fd96f3da87312232d2dbcb668cdb/files/en-us/web/accessibility/aria/roles/mark_role/index.html

**Comment by estelle** [comment]
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/mark_role has been updated, no longer says it's a landmark role.
