### ISSUE TITLE
Issue with "WebGL2RenderingContext.getBufferSubData()": Argument 3 does not implement interface ArrayBufferView

### ISSUE THREAD

**Issue by imadr** [mdn/content#4539]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/getBufferSubData

#### What information was incorrect, unhelpful, or incomplete?

The `dstData` argument of type `ArrayBuffer` doesn't work and results in this error:

    Uncaught TypeError: WebGL2RenderingContext.getBufferSubData: Argument 3 does not implement interface ArrayBufferView.

#### Specific section or headline?

Parameters and Examples

#### What did you expect to see?

Data from the buffer

#### Did you test this? If so, how?

Example code:

    let canvas = document.createElement("canvas");
    let gl = canvas.getContext("webgl2");
    let position_buffer = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, position_buffer);
    let positions = [
        -1.0, 1.0, 0.0,
        1.0, 1.0, 0.0,
        -1.0, -1.0, 0.0,
        1.0, -1.0, 0.0,
        1.0, 1.0, 0.0,
        -1.0, -1.0, 0.0
    ];
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(positions), gl.STATIC_DRAW);

    let arrBuffer = new ArrayBuffer(positions.length * Float32Array.BYTES_PER_ELEMENT);
    gl.getBufferSubData(gl.ARRAY_BUFFER, 0, arrBuffer);

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl2renderingcontext/getbuffersubdata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/getBufferSubData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl2renderingcontext/getbuffersubdata/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by himanshugarg** [comment]
We can close this issue as the current code no longer throws an error (and the reported version still fails):

**Comment by hamishwillee** [comment]
Thanks!
