### ISSUE TITLE
Issue with "Test your skills: Math": (short summary here please)

### ISSUE THREAD

**Issue by ghost** [mdn/content#4541]
...

**Comment by chrisdavidmills** [comment]
> "Why am I expecting people to solve quizzes with information II haven't taught them yet?"

To solve Math 3, you need to use comparison operators, which are taught at https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math#comparison_operators, in the article before the quiz.

> You should be ashamed of yourself.

What, for providing a full-featured course to allow you to learn JavaScript, FOR FREE? I know, I'm behaving terribly.

**Comment by matkoniecz** [comment]
> This stupid bullshit 

> You should be ashamed of yourself.

This kind of insults is neither helpful nor needed nor increasing chance of being treated seriously. Please avoid this.

**Comment by TheosAnthropos** [comment]
No. They're not "taught" they are mentioned. There's a difference...

**Comment by TheosAnthropos** [comment]
No. They're not "taught" they are mentioned. There's a difference...

**Comment by Ryuno-Ki** [comment]
I am wondering, whether the OP read https://github.com/mdn/content#code-of-conduct

> Everyone participating in this project is expected to follow our [Code of Conduct](https://github.com/mdn/content/blob/main/CODE_OF_CONDUCT.md).

Find them at https://www.mozilla.org/en-US/about/governance/policies/participation/

Although edited, GitHub allows for seeing the original text, which does not conform to these CoC in my opinion.

**Comment by Ryuno-Ki** [comment]
@chrisdavidmills I believe we can close (and perhaps lock) this issue.
