### ISSUE TITLE
'Issue' with "HTML attribute reference": it would be nice to have at least short overview on all possible types of attributes you can find in HTML elements.

### ISSUE THREAD

**Issue by 552020** [mdn/content#4551]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

#### What information was incorrect, unhelpful, or incomplete?

I was looking for an exact explanation from an HTML point of view of the attribute 'onclick' and I was not able to find anything in MDN. I guess this page is the page, where I think I should have founded the information I was looking for. 

I'm aware of the two articles on 'onclick' and "click events": 
- https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onclick
-  https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event

#### Specific section or headline?

The first paragraph: "Elements in HTML have attributes; these are additional values that configure the elements or adjust their behavior in various ways to meet the criteria the users want." It's clear only by the menu on the left that only the "global attributes" are taken in consideration. 

#### What did you expect to see?

I was expecting to see something like https://en.wikipedia.org/wiki/HTML_attribute that I found successively thanks to Google.  Since MDN is the reference online-resource for most of the learners it would be nice and useful to have a short introduction about all the possible kind of attributes you can find in the HTML element. A link to the cited page in wikipedia, that it seems to me to be pretty accurate, could also do the work. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/index.html
* Last commit: https://github.com/mdn/content/commit/1f2db9f0a46b99c254476b5f9445a74b98a6fa30
* Document last modified: 2021-03-27T00:17:29.000Z

</details>

**Comment by 552020** [comment]
I found now this content in MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes, cause the Wikipedia article mention it. From the page I raised the issue for is impossible to react that page. You have to click on one of the global attributes listed on the menu on the left and then click back.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5676 with a fix
