### ISSUE TITLE
Cannot read property 'getContext' of null

### ISSUE THREAD

**Issue by KingJulienN-ai** [mdn/content#4568]
MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Create_the_Canvas_and_draw_on_it

#### What information was incorrect, unhelpful, or incomplete?
From line 2 below the getContext

#### Specific section or headline?
var canvas = document.getElementById("myCanvas");
var ctx = canvas.getContext("2d");

ctx.beginPath();
ctx.rect(20, 40, 50, 50);
ctx.fillStyle = "#FF0000";
ctx.fill();
ctx.closePath();

#### What did you expect to see?
A rectangle

#### Did you test this? If so, how?
I copied this on VSCode and runned it using Chrome browser

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/games/tutorials/2d_breakout_game_pure_javascript/create_the_canvas_and_draw_on_it`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Create_the_Canvas_and_draw_on_it
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/tutorials/2d_breakout_game_pure_javascript/create_the_canvas_and_draw_on_it/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by KhooHaoYit** [comment]
Is your `canvas` exists and loaded before you run `document.getElementById("myCanvas");`??
Because the reason you got that error is that [`document.getElementById`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById) returns `null` if it can't find the element.
You can try running the code when the DOM is loaded by listening to [`DOMContentLoaded`](https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event).

**Comment by sideshowbarker** [comment]
Along with what @KhooHaoYit wrote, note also that regarding this code:

```
var canvas = document.getElementById("myCanvas");
```
… if there’s no `<canvas id=myCanvas>` element in the document, then that `canvas` variable will be null. So, for example, paste that code won’t work as-is if you just paste it into the console.

Anyway, that code example in that article will work as expected if the browser finds a `<canvas id=myCanvas>` element in the document. So I’m gonna go ahead and close this. But if you have new information or questions, feel free to comment here further.
