### ISSUE TITLE
Content suggestion: IDBVersionChangeRequest and IDBDatabase/setVersion

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#4571]
## What is the new suggestion?

/en-US/docs/Web/API/IDBVersionChangeRequest does not exist
/en-US/docs/Web/API/IDBDatabase/setVersion does not exist

## Why is it important or useful?

This will prevent first-time contributors from seeing unrelated reports to their contribution.

## Other supporting information

This came up in https://github.com/mdn/content/pull/4538#issuecomment-828736382

**Comment by chrisdavidmills** [comment]
I really don't undetstand what you're suggesting here. Can you elaborate?

**Comment by Ryuno-Ki** [comment]
https://github.com/mdn/content/pull/4538#issuecomment-828736382 shows flaws for links, for which the target page does not exist.

Namely, domxref references in

https://github.com/mdn/content/blob/e36a7213f866fd96f3da87312232d2dbcb668cdb/files/en-us/web/api/indexeddb_api/index.html#L97-L98

Either these documents need to be written or the references deleted. Either way, both were not in scope of the PR there, but I thought to not miss the opportunity to improve our docs.

**Comment by sideshowbarker** [comment]
I’ve opened https://github.com/mdn/content/pull/5814 with a change that drops the broken macro calls.
