### ISSUE TITLE
Possible mistake in documentation

### ISSUE THREAD

**Issue by ddziara** [mdn/content#4576]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/embeds

There is:
[The embeds read-only property of the Document interface returns a list of the embedded \<object> elements within the current document.]

shouldn't it be?
[The embeds read-only property of the Document interface returns a list of the embedded \<embeds> elements within the current document.]

**Comment by farhan443** [comment]
I can't see any difference between the text under "There is" and the text under "shouldn't it be?". Did you write the suggestion correctly?

**Comment by ddziara** [comment]
Hello,

difference should <object> and <embeds>. At least that was my intention.

For instance here is <embeds>: HTML DOM embeds <https://www.w3schools.com/jsref/coll_doc_embeds.asp>  Collection (w3schools.com)

And also document.embeds.length is 0 when there are embedded <object> elements.

Best Regards
Dariusz Dziara

**Comment by wbamberg** [comment]
> I can't see any difference between the text under "There is" and the text under "shouldn't it be?". Did you write them correctly?

I thought the same thing! But they looked the same because if you write HTML tags in GitHub comments, without escaping, they are interpreted as HTML. I just edited the original post to escape the tags, so you can see the difference now.

And it looks like you are right. From the [spec](https://html.spec.whatwg.org/multipage/dom.html#dom-document-embeds):

> The embeds attribute must return an HTMLCollection rooted at the Document node, whose filter matches only embed elements.

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/4640 with a fix.
