### ISSUE TITLE
Content bug: Iframe height in the Enlish version

### ISSUE THREAD

**Issue by FreePhoenix888** [mdn/content#4587]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

## Specific page section or heading?

Iframe example at the beginning.

## What is the problem?

Height is less than needed.

## What did you expect to see?

Full view of example.

**Comment by mirunacurtean** [comment]
Thank you for your contribution @FreePhoenix888!
Currently MDN is undergoing a Redesign and changes will be made that will either address or render some issues null.  As a change in iframe height would have to be something that needs to be consistent across all pages and examples, this is would be something to be discussed as part of the redesign, if needed, so I will be closing this ticket.
