### ISSUE TITLE
Issue with "Getting started with HTML": (HTML tags mistakenly written to be "case sensitive")

### ISSUE THREAD

**Issue by RizwanAhmad365** [mdn/content#4589]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started

#### What information was incorrect, unhelpful, or incomplete?
HTML tags were mistakenly written to be "case sensitive"

#### Specific section or headline?
What is HTML > Note

#### What did you expect to see?
HTML tags are not "case sensitive"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/getting_started/index.html
* Last commit: https://github.com/mdn/content/commit/75c1271189903b4d96433a34a8174175dd089ef2
* Document last modified: 2021-04-28T14:08:28.000Z

</details>

**Comment by NegiAkash890** [comment]
![Screenshot from 2021-04-29 22-26-28](https://user-images.githubusercontent.com/55234838/116589282-1de9f000-a93a-11eb-8c7b-e9629d1b26a1.png)

Hi @RizwanAhmad365 , I think you made a mistake while reading.I have attached the screenshot ;).

**Comment by RizwanAhmad365** [comment]
I didn't make a mistake,
Read it once again,

Here's what should have been written there: Tags in HTML are not
case-sensitive. This means they can be written in uppercase or lowercase

**Comment by sideshowbarker** [comment]
@RizwanAhmad365 The article says “case-insensitive”, not “case-sensitive”, right?

As in the screenshot @NegiAkash890 posted:

![image](https://user-images.githubusercontent.com/194984/116776082-c23a7680-aaa1-11eb-9617-75e84f6c2c6d.png)

**Comment by RizwanAhmad365** [comment]
wooosh
sorry my bad,
my mind was not expecting insensitive, was totally blind to it

**Comment by sideshowbarker** [comment]
> my mind was not expecting insensitive, was totally blind to it

No worries — I’ve actually had the same experience elsewhere of reading it that way. I think it happens pretty commonly.
