### ISSUE TITLE
Issue with "Fullscreen API": False statement about Document.onfullscreenchange

### ISSUE THREAD

**Issue by SDP190** [mdn/content#4590]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

#### What information was incorrect, unhelpful, or incomplete?
Documentation says:
**Document.onfullscreenchange**

> An event handler for the fullscreenchange event that's sent to a Document when that document is placed into full-screen mode, or when that document exits full-screen mode. **This handler is called only when the entire document is presented in full-screen mode**.

However, the last statement in bold which states that `document.onfullscreenchange` is only raised when entire document is presented in fullscreen, **is wrong and is simply not true**, cause the `window.document` object itself is never set to fullScreen, in fact, there is no method to request fullscreen on the document object, at max you can request for the root HTML element: `document.documentElement.requestFullScreen`.

However, the `fullscreenchange` event is always originating from a dom Element and then it **always bubble's up to the "document" object**, this bubbling happens always, even if `fullscreenchange` was requested on a deeply nested child element.

#### Specific section or headline?
Event handlers on documents

#### What did you expect to see?
This whole part in documentation is wrongly making the impression as if there were 2 types of `fullscreenchange` event, one for the document and a different for the element, that's wrong, please rewrite accordingly.

#### Did you test this? If so, how?
Yes, just assign a handler to `document.onfullscreenchange`, call `requestFullScreen `on any inner element and then see how the event is being raised in the document object via bubbling (event.eventPhase=3).

In the other hand even when calling `requestFullScreen` on the root element (document.documentElement) still the document object gets the event only via bubbling (so for root `documentElement` the eventPhase = 2, but for `document` object itself its still 3)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/fullscreen_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fullscreen_api/index.html
* Last commit: https://github.com/mdn/content/commit/18f85b7ac3d865fb56cd47bb82bf39d74c6a9c8c
* Document last modified: 2021-02-24T02:41:00.000Z

</details>

**Comment by SDP190** [comment]
Hi @chrisdavidmills 
Can you comment on this issue?

**Comment by chrisdavidmills** [comment]
@SDP190 sure; reviewed

**Comment by sideshowbarker** [comment]
Fixed in https://github.com/mdn/content/commit/202f8fa6c5c6d471b27d2030710db0fb800613af.
