### ISSUE TITLE
Content issue in PT-BR translation

### ISSUE THREAD

**Issue by saulofalcao** [mdn/content#4591]
URL:
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/if...else

![screenshot-developer mozilla org-2021 04 29-10_43_18 (1)](https://user-images.githubusercontent.com/1717262/116524989-535df180-a8d8-11eb-86f7-9bacf81d029e.jpg)

**Comment by saulofalcao** [comment]
Submitted this pull request: [](https://github.com/mdn/translated-content/pull/688)

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/translated-content/pull/688
