### ISSUE TITLE
Issue with "MVC": …

### ISSUE THREAD

**Issue by anubhab137** [mdn/content#460]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/MVC

#### What information was incorrect, unhelpful, or incomplete?
The contents in the image aren't readable enough cause it is way too much stretched vertically.

#### Specific section or headline?
Problem with the Image layout.

#### What did you expect to see?
The vertical scale of the image should be decreased. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/mvc`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/MVC
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/glossary/mvc/index.html
* Report started: 2020-12-19T09:11:23.734Z

</details>

**Comment by chrisdavidmills** [comment]
Thanks for reporting; fixed via https://github.com/mdn/content/commit/e9749644c385a3160b5d3537a199b65104e19d24
