### ISSUE TITLE
Issue with "The box model": inline vertical margin

### ISSUE THREAD

**Issue by nicoabie** [mdn/content#4605]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model

#### What information was incorrect, unhelpful, or incomplete?
The vertical margin is not respected as it says and I cannot understand why.
I've tried with the developer tools changing its value but nothing happens.

#### Specific section or headline?
[The box model and inline boxes](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model#the_box_model_and_inline_boxes)

#### What did you expect to see?
An explanation of why the vertical margin does not get applied.

#### Did you test this? If so, how?
Yes I did with the developer tools changing the values manually.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/the_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/the_box_model/index.html
* Last commit: https://github.com/mdn/content/commit/bbe23f8c130f876a407d42fa991adc676adf129f
* Document last modified: 2021-02-27T17:32:36.000Z

</details>

**Comment by rachelandrew** [comment]
@nicoabie I have just tested this and it is working as described. If I set the margin to say 70px, I get a larger margin to the left and right of the element and no margin above and below. So I need some more information about what you changed, and what you expected to see.

**Comment by rachelandrew** [comment]
Closing as this is testing correctly, please re-open if you have more info.
