### ISSUE TITLE
Content bug: Debugging_JavaScript#dump.28.29

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#4606]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#performing_computations_in_the_background

## Specific page section or heading?

> The HTML code

The very link before the next heading.

## What is the problem?

`dump` is pointing towards https://developer.mozilla.org/en-US/docs/Debugging_JavaScript#dump.28.29 - that feels wrong. The `.28.29` looks like a relict of former times.
I assume, it refers to https://developer.mozilla.org/en-US/docs/Web/API/Window/dump

## What did you expect to see?

I suggest to rewrite that section in the Web Workers document.

## Did you test this? If so, how?

It got reported by https://github.com/mdn/content/pull/4600#issuecomment-829534309

**Comment by wbamberg** [comment]
Note that the actual code this example refers to: https://github.com/mdn/fibonacci-worker/blob/master/index.html is using console.log, so it would probably be best to update the page to match.

In fact I wonder if it would be possible/better to make this a live sample, so the code won't get out of sync.

**Comment by Josh-Cena** [comment]
Fix by #5475
