### ISSUE TITLE
Issue with "Test your skills: The Box Model": Duplicated task

### ISSUE THREAD

**Issue by nicoabie** [mdn/content#4607]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Box_Model_Tasks

#### What information was incorrect, unhelpful, or incomplete?

There is a duplicated task between
[Box_Model_Tasks the_box_model_one](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Box_Model_Tasks#the_box_model_one)
and
[The_box_model playing_with_box_models](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model#playing_with_box_models)

#### Specific section or headline?

[Box_Model_Tasks the_box_model_one](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Box_Model_Tasks#the_box_model_one)

#### What did you expect to see?

A different exercise

#### Did you test this? If so, how?

This need no tests

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/box_model_tasks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Box_Model_Tasks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/box_model_tasks/index.html
* Last commit: https://github.com/mdn/content/commit/bbe23f8c130f876a407d42fa991adc676adf129f
* Document last modified: 2021-02-27T17:32:36.000Z

</details>

**Comment by rachelandrew** [comment]
The example inline is to highlight the learning, the second time is part of a check to see what people have remembered. So this seems not to be an issue. If folk remember how it works then it has achieved what it is supposed to be achieving!
