### ISSUE TITLE
Issue with "Math.abs()": …

### ISSUE THREAD

**Issue by peterbe** [mdn/content#461]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/abs

#### What information was incorrect, unhelpful, or incomplete?

There are lots of MathML errors rendering this equation

#### Specific section or headline?

Introduction

#### What did you expect to see?

No errors in the web console

#### Did you test this? If so, how?

<img width="1253" alt="Screen Shot 2020-12-19 at 9 29 00 AM" src="https://user-images.githubusercontent.com/26739/102691762-df4e6700-41dc-11eb-9e60-261ab891d3d4.png">

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/math/abs`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/abs
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/math/abs/index.html
* Report started: 2020-12-19T14:26:16.341Z

</details>

**Comment by peterbe** [comment]
When @vkWeb tested the same URL, his MathML didn't even render. 
https://github.com/mdn/content/pull/425#pullrequestreview-555857026

**Comment by vkWeb** [comment]
https://github.com/mdn/content/pull/425#issuecomment-748489457

**Comment by longm89** [comment]
@chrisdavidmills Hi Chris, could I work on this problem?

**Comment by longm89** [comment]
@chrisdavidmills Thanks. Yes, I looked at the web on my broswer Chrome and don't see any error in the console.

**Comment by longm89** [comment]
@himanshugarg Yes, you are right. I was just looking at the console in some broswers and didn't pay attention that the math equations have been changed from the first picture. The math equation is replaced by the text in this PR: https://github.com/mdn/content/commit/4281baca8760ad00236579f3ccddd055c76a4143#diff-9766a0d2e9aea268c1ebc2080abf1cd488fd48ec5990628194b1fbd8f898bcc6

**Comment by sideshowbarker** [comment]
It seems this problem was fixed in https://github.com/mdn/content/commit/4281baca8760ad00236579f3ccddd055c76a4143 https://github.com/mdn/content/pull/4085
