### ISSUE TITLE
Accessination of mdn content accessible all web applications

### ISSUE THREAD

**Issue by sunilk7213** [mdn/content#4613]
To the mdn content on github, I am Sunil Sharma from Jammu(India) I am requested to the all content authoring of all mdn content that have to use for all web applications through my android phone device-(GalaxyJ7 2016) running on all web browsers, I am urgently request to the mdn content for web applications directly that include all work on mdn content, screen reader, accessibility of all content of mdn without installing or authoring extra accessible work usage attributes on html5  on mdn, I am hardly request to the mdn content I don,t know the usage of attributes on html5 page So please refer & describe the simple way of representing authoring and working on html5 page using mdn content workflow as simple as I am used So I am urgently requested to the mdn content please reply immediately the appropriate system usage content workflow with mdn content simply on my email address -(Sunilk7213@gmail.com) and reply on my contact Numbers-(919055314316) 2-(919149884972) in India.

**Comment by chrisdavidmills** [comment]
Hi @sunilk7213 !

I'm not 100% sure what you are asking for, but it sounds like you want some help with learning how to create accessible, responsive, web sites/applications.

We have a lot of learning material about how to use HTML, CSS, and JavaScript to build we sites at https://developer.mozilla.org/en-US/docs/Learn

And more specifically on accessibility: https://developer.mozilla.org/en-US/docs/Learn/Accessibility

Also we specifically discuss the concept of responsive design here: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design

All of the content implicitly uses accessible/responsive best practices where possible.

**Comment by sunilk7213** [comment]
Dear Sir Chris Mills  I am Sunil Shrma recieved your reply about Mdn
Content, I am hardly speak to you that I can,t wish to have learn about who
to accessible Mdn Content features that is used for wor with Mdn Content
like installation of features, installation of Mozilla, firefox or
installation on my android device, because there are one device -(GalaxyJ7
2016) are available in present time, Dear Sir Chris Mills you are my
Colleague & friend on Mdn Content So I am urgentl requested an appeal to
you & Mdn Content team please support me to do work on Mdn Content directly
used with my Device -(Galaxy J7 2016) or if another use of service
conectivity like my email ***@***.***) or direct to
server settings of Mdn Content on my device or directly on my IP address
conectivity. Dear Sir Chris's Mills I am an Indian, I am do not wish to
learn about Mdn Content workflow material like who can I am work with Mdn
Content, I am do not wish to learn who to use HTML, CSS, and Java Script to
build, I am do not wish to  learn for Mozilla, firefox or  android device
accessibility of Mdn Content  material on my device,  and I am do not wish
to lear about specially discuss the concept of responsive design because
there are totally  no more knowledge of these materials described in the
above I am wish to have an accessibility to use on my device directly on
any way that are available on Mdn Content team for myself , I  am  sure
that Mdn Content team & you are 100 percentlly sure to understand my case
of issue.So I am Urgently requested to Mdn Content team If this facility
are available please provide these facilities for no cost consumption on my
device-(Galaxy J7 2016)

**Comment by chrisdavidmills** [comment]
I'm sorry, but I don't understand what you are asking for.

**Comment by sunilk7213** [comment]
Dear Sir  Chris & all the Mdn Content team unfortunately I am just saying
to that request please review previous email again, again & again for
better understand what can I am doing with accessination of all features on
my hand for working automatically & all working features is on my
fingertips and all the time 24×7 I am free to use Mdn Content framework
directly. I have to say that means supposeIf I am purchaise a new laptop or
desktop, the laptop does not work without online connection of internet &
laptop is also dead without using a hard disk including many features that
is more urgent for using the laptop, In the other sense If I am not know
who can I am use the computer for work online include many of the features
redirect for using computer and the other words  who can I am start my
computer without online  internet connectionI & without a hard disk drive,
So all of that I am said that you can provide this online connection & hard
disk for operating my computer offline or online. So the previous email is
best of my knowledge for understanding & I don,t have   to do another
beneficiary with Mdn Content I am only appeal this request for Mdn work &
accesination of Mdn Content Api,s on my fingertips.So I am urgently request
to Mdn team please review these emal,s  for better understanding & reply on
my email ***@***.***) and on my contact Numbers-(919055314316)
2-(919149884972) in India.

**Comment by sunilk7213** [comment]
To the Mdn Content ,please refer another expert If Mdn Content is not
liable to underestimate for processing any accessination of Api,s and
converting procedure of Mdn Content regarding  to my case of accelration
,Conversion, accesination of all Api,a  etc etc directly to my mobile
device -(Galaxy J7 2016)  regarding to Mdn Content Content  like-
acceleration  of all Mdn Content web Api,s for installing, downloading and
browse videos, pictures, all web applications of Mdn Content with only one
touch of my fingertips (or produce a link to connect directly with Mdn
Content) without any cost consumption If point to be not understood by Mdn
Content and  please review my case of interest step by step and intended to
reply on my email ***@***.***) or my contact Numbers in
india-(919055314316) 2-(919149884972) Immidietely.

>
>

**Comment by sunilk7213** [comment]
To the Mdn Content, I have to send several emails to the Mdn Content Team
but I can,t recieved any confirmation on my email ***@***.***)
or on my cell phone Numbers In India-(919055314316) 2-(919149884972)
because I do so hard work for the accessination of Mdn Content probe for
use of work with Mdn Content . So I am urgently request to The Mdn Content
team  If any facility are available for my future dream of accessination
directly on my cell phone device -(Galaxy J7 2016)  all the Mdn Content &
Contribution to the Mdn Content work, If this facility are available
through direct contact with Mdn Content or avail through  the Mdn Content
licence provider agreement , I am again request to the Mdn Content Team
please provide licence agreement free of cost consumption on my Mobile
device -(Galaxy J7 2016)

>
>>

**Comment by hamishwillee** [comment]
@sunilk7213 What I think you are asking is that you should be able to access all information from MDN on your phone (Galaxy J7 2016).

If so, the short answer is no.

The longer answer is that while we make "best effort" to ensure that MDN content is usable on mobile devices, please keep in mind that almost all web developers work on desktop computers (even those targeting mobile devices). That means that our key audience is desktop first. We will also not target specific devices, but rather web standards. We will consider specific cases/problems but not "everything should work on my particular phone".

If that is not an answer to your question, can you please find a native or near-native English speaker to post your question for you? 

A few other points. 
- We aren't going to phone you. 
- The people on this channel aren't necessarily going to be monitoring the support email you contacts.
- We will respond as quickly as possible, but however urgent this is for you, it is not likely to be something we can fix immediately. 

Closing as answered "for now".
