### ISSUE TITLE
Content bug: The Index page of JavaScript and CSS is missing

### ISSUE THREAD

**Issue by wenmin92** [mdn/content#4619]
## What page(s) did you find the problem on?
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Index
- https://developer.mozilla.org/en-US/docs/Web/CSS/Index

## What is the problem?
There are /topic/Index pages for other main topics(like HTML, HTTP, SVG, API etc.), but JavaScript and CSS does not.

## What did you expect to see?
Please add those Index page.

**Comment by wbamberg** [comment]
Is there something in particular you need this for? As far as I can recall these pages were built to be used internally by some template code in the old Wiki version of MDN, and were never really intended for users.

**Comment by wenmin92** [comment]
There's a tool, named [utTools](https://u.tools/), it used the Index page to [build the local verson of the MDN](https://github.com/in3102/utools-mdn-doc), maybe there are other methods to do this, but using the Index page is the simplest.

**Comment by teoli2003** [comment]
Hi!

I think that, for any tool, relying on the generated pages to work is a big risk: even if they existed, changes in the page structure, existence, … may break the tool.

I would suggest to use the extract the structure from the github repository structure instead. Theoretically it may change too, but I believe it will be much more stable.

As we don't plan on re-adding these pages, I propose to close this issue on our side.

Thanks for the report, though!  It is always nice to hear about tools re-using our content!

**Comment by wbamberg** [comment]
^ puts it better than me.
