### ISSUE TITLE
Typo in "<canvas>: The Graphics Canvas element": … in "Alternative Content" section

### ISSUE THREAD

**Issue by leonard-9500** [mdn/content#462]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas

#### What information was incorrect, unhelpful, or incomplete?
MDN Hit regions and **accessability**

#### Specific section or headline?
Section: "Alternative content"
(1st item in list)

#### What did you expect to see?
MDN Hit regions and **accessibility**

#### Did you test this? If so, how?
/

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/canvas`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/html/element/canvas/index.html
* Report started: 2020-12-19T15:34:44.234Z

</details>

**Comment by sideshowbarker** [comment]
Nice catch. Thanks for reporting this — I’ve opened #465 with a fix

**Comment by sideshowbarker** [comment]
Taking this one off my plate. @leonard-9500, if you’re interested in submitting a pull request for this yourself, we’d welcome that.

**Comment by rachelandrew** [comment]
Fixed in https://github.com/mdn/content/pull/3979
