### ISSUE TITLE
Issue with "Handling different text directions": Instructions aren't working

### ISSUE THREAD

**Issue by nicoabie** [mdn/content#4623]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Handling_different_text_directions

#### What information was incorrect, unhelpful, or incomplete?

In one of the demonstrations, the code does not work as intended following the instructions

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Handling_different_text_directions#logical_values

#### What did you expect to see?

A change in the image.

#### Did you test this? If so, how?

No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/handling_different_text_directions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Handling_different_text_directions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/handling_different_text_directions/index.html
* Last commit: https://github.com/mdn/content/commit/1fdf7958ea85bab45e1d7ba3634e9381eae937d1
* Document last modified: 2021-01-27T07:42:45.000Z

</details>

**Comment by rachelandrew** [comment]
@nicoabie are you using Firefox? There is a note in the example that this demo only works in a browser supporting logical values for float, which is I believe only Firefox right now.

I have tested the demo in Firefox and it is working.

**Comment by nicoabie** [comment]
You are completely right, I didn't read the disclaimer, sorry for that. I'm closing this issue.
