### ISSUE TITLE
Issue with "Django Tutorial Part 3: Using models": …

### ISSUE THREAD

**Issue by TripleAccountBoi** [mdn/content#463]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Models

#### What information was incorrect, unhelpful, or incomplete?
book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)

#### Specific section or headline?
BookInstance models

#### What did you expect to see?
on_delete should be set to models.CASCADE. Otherwise deleting a book that has a BookInstance will result in an error when going to BookInstances in the admin panel, because it will not be able to retrieve the title from the null Book. The problem is that (at this point in the tutorial) there is no way to delete the faulty instance and most viewers will not be aware of the shell that can be used to fix this problem.

#### Did you test this? If so, how?
I deleted the faulty instance in order to make the website work again, I made a test book and a test instance for said book, then I deleted the test book. The problem appeared again. After that I changed the on_delete argument to models.CASCADE and migrated the change , after which I repeated the test. The test was finished successfully without resulting in an error. 

#### More feedback
Debugging this problem was a good learning opportunity for a beginner like me. 
I believe teaching about the manage.py shell and adding the debugging of this problem as a challenge at the end of the article could improve the problem solving abilities and framework knowledge of the viewer. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/models`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Models
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/server-side/django/models/index.html
* Report started: 2020-12-19T15:27:06.884Z

</details>

**Comment by hamishwillee** [comment]
Thanks @TripleAccountBoi - you're correct - the current behaviour isn't acceptable. While we could use `CASCADE`, I believe a better `on_delete` option is `RESTRICT`. Rather than deleting all bookinstances when book is deleted it prevents you from deleting the book until you have deleted the instances.  That makes more sense to me:
- it is all too easy to delete the book and accidentally delete a whole lot of other things.
- This gives me the option to explain another option for on_delete ;-). 

I have done this in https://github.com/mdn/django-locallibrary-tutorial/pull/86 and will now fix up the docs.

**Comment by hamishwillee** [comment]
> Debugging this problem was a good learning opportunity for a beginner like me.
> I believe teaching about the manage.py shell and adding the debugging of this problem as a challenge at the end of the article could improve the problem solving abilities and framework knowledge of the viewer.

In principle I love this idea. In practice I don't want to have any copy-paste code that is "wrong". I will think about this.

**Comment by hamishwillee** [comment]
OK, and I have also fixed up the tutorial itself in #719 

I think that this is probably "good" once those go in. I don't think I want to use this as a debugging example "yet". Though at some point it might be worth having a debugging chapter and using this as an example there. 

Thanks VERY much for pointing out this problem!
