### ISSUE TITLE
Issue with "BigInt": (short summary here please)

### ISSUE THREAD

**Issue by DiriectorDoc** [mdn/content#4635]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

#### What information was incorrect, unhelpful, or incomplete?
When talking about BigInt division, the variable name implies the number is rounded when this is not the case.

#### Specific section or headline?
Under the **Operators** section

#### What did you expect to see?
```
92. -  const rounded = 5n / 2n
92. +  const truncated = 5n / 2n
```

#### Did you test this? If so, how?
I made sure that BigInts are truncated like this:

```javascript
var truncated1 = 14n/3n    // → 4n
var truncated2 = -14n/3n   // → -4n
```

Neither number is "rounded" a specific way. The number is truncated upon division.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/bigint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/bigint/index.html
* Last commit: https://github.com/mdn/content/commit/b741df1720fa7408fd8072ae29575b758dde42e6
* Document last modified: 2021-04-28T16:04:31.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/4639 with a fix.
