### ISSUE TITLE
Issue with "The WebSocket API (WebSockets)": Mentioning CSWSH

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#4644]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API

#### What information was incorrect, unhelpful, or incomplete?

I was thinking about mentioning [Cross-Site WebSocket Hijacking](https://christian-schneider.net/CrossSiteWebSocketHijacking.html) as I only learned about it the other day.

#### Specific section or headline?

I'm not sure. Perhaps under Guides?

#### What did you expect to see?

Security warning when using WebSockets.

#### Did you test this? If so, how?

I didn't.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/websockets_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/websockets_api/index.html
* Last commit: https://github.com/mdn/content/commit/ba4a07195d8f8f4941e7ae06118b8405f9cac9cf
* Document last modified: 2021-04-10T23:58:36.000Z

</details>

**Comment by jpmedley** [comment]
Actually, if this is an API overview page, it should have a heading 2 named "Concepts and Usage". ([Example](https://github.com/mdn/content/pull/4711/files)) Make it a heading 3 under that, and we'll try to backfill this some how.
