### ISSUE TITLE
Issue with "HTML": (short summary here please)

### ISSUE THREAD

**Issue by Body87** [mdn/content#4650]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/HTML

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/html/index.html
* Last commit: https://github.com/mdn/content/commit/84eac7b54de6366dd67384f4f7d5f082f22fd7f4
* Document last modified: 2021-01-13T11:01:45.000Z

</details>

**Comment by Brazuca228** [comment]
𝙍𝙚𝙢𝙚𝙣𝙗𝙚𝙧 𝙖𝙨 𝙡𝙤𝙣𝙜𝙚𝙧 𝙬𝙚 𝘾𝙖𝙣 𝙥𝙧𝙤𝙫𝙞𝙙𝙚 𝙩𝙝𝙚 𝙥𝙧𝙚𝙫𝙞𝙤𝙪𝙨, 𝙪𝙨𝙚𝙧 𝙣𝙖𝙢𝙚 𝙬𝙚 𝙘𝙖𝙣 𝙧𝙚𝙨𝙤𝙡𝙫𝙚𝙧 𝙩𝙝𝙚 𝙥𝙧𝙤𝙗𝙠𝙚𝙢 𝙪𝙣𝙛𝙪𝙭𝙚𝙙 𝙚𝙭𝙚𝙢𝙥𝙡𝙤 
𝙒𝙝𝙚𝙣 𝙞 𝙎𝙩𝙖𝙨𝙩𝙖𝙧𝙩 𝙖𝙩 𝙜𝙞𝙩𝙫𝙝𝙪𝙗 𝙞 𝙬𝙖𝙨 𝙠𝙣𝙤𝙬 𝙖𝙨 𝘼𝙢𝙖𝙯𝙤𝙣𝙗𝙤𝙮228 𝙤𝙧 𝘼𝙢𝙖𝙯𝙤𝙣𝙗𝙤𝙮 22
𝙏𝙝𝙚𝙢 𝙤𝙫𝙚𝙧 𝙩𝙝𝙚 𝙩𝙞𝙢𝙚 𝙞 𝙗𝙚𝙘𝙖𝙢𝙚 𝘽𝙧𝙖𝙯𝙪𝙘𝙖228 𝙤𝙧  𝘼𝙣𝙙 𝙢𝙮 𝙤𝙡𝙙𝙚𝙨𝙩 𝙚𝙢𝙖𝙞𝙡 𝘾𝙖𝙣𝙖𝙧𝙮, 𝙜𝙞𝙫𝙚 𝙨𝙤𝙢𝙚 𝙩𝙧𝙖𝙘𝙠  𝙖𝙣𝙙 𝙩𝙧𝙖𝙘𝙠 𝙞𝙨 𝙨𝙤𝙡𝙪𝙩𝙞𝙤𝙣
