### ISSUE TITLE
Issue with "Ordering Flex Items": Live examples order is mixed up

### ISSUE THREAD

**Issue by dekaskas** [mdn/content#4652]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items

#### What information was incorrect, unhelpful, or incomplete?

The 3rd code example is talking about .active class but the live example doesn't contain
such class, but the 1st live example does. It looks like the order of the live examples is wrong

3rd Example:
![image](https://user-images.githubusercontent.com/1313753/116810602-557cb600-ab4d-11eb-829f-18f22a429b00.png)

1st Example
![image](https://user-images.githubusercontent.com/1313753/116810627-7fce7380-ab4d-11eb-9f7d-687a509d96b3.png)

#### Specific section or headline?
 1st, 2nd and 3rd examples are in the wrong order

#### What did you expect to see?

The 1st example is the 3rd

The 2nd is 1st

and 3rd is second

I have previously opened the Issue but it was ignored: #4555

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_flexible_box_layout/ordering_flex_items`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_flexible_box_layout/ordering_flex_items/index.html
* Last commit: https://github.com/mdn/content/commit/8807bc0b7b90ad47c41e2d62eb369fa15e8b8f05
* Document last modified: 2021-02-16T13:14:11.000Z

</details>

**Comment by rachelandrew** [comment]
@dekaskas thanks for the report, they were indeed in the wrong order. The PR I have just made will fix that once merged.
