### ISSUE TITLE
Issue with "Handling content breaks in multicol": (short summary here please)

### ISSUE THREAD

**Issue by WainPetopia** [mdn/content#4653]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Handling_content_breaks_in_multicol

#### What information was incorrect, unhelpful, or incomplete?
Your own break-before example isn't working in the demonstration on the page (in Firefox, latest release)

#### Specific section or headline?
"Breaks before and after boxes" section

#### What did you expect to see?
There was supposed to be a column break before the h2 element "My heading", while the demonstration itself shows that this isn't working. The "My heading" appears at the bottom of the first column

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_columns/handling_content_breaks_in_multicol`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Handling_content_breaks_in_multicol
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_columns/handling_content_breaks_in_multicol/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by rachelandrew** [comment]
Hi @WainPetopia it's not supported in Firefox, the compat table on the `break-before` page shows current support https://developer.mozilla.org/en-US/docs/Web/CSS/break-before we don't tend to also spread that info around the docs because otherwise it gets really out of date.

**Comment by WainPetopia** [comment]
Thanks for the explanation :) The wording just read to me as though the reader should expect it to work (especially when viewed with the company’s own browser product!) but I’ve clearly misinterpreted it.
