### ISSUE TITLE
Issue with "Strict-Transport-Security": (short summary here please)

### ISSUE THREAD

**Issue by Jorge231** [mdn/content#4658]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/strict-transport-security`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/strict-transport-security/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by hamishwillee** [comment]
Closing - no error description
