### ISSUE TITLE
Issue with "Validators": bad URL

### ISSUE THREAD

**Issue by BrianSmall** [mdn/content#4659]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Validators

#### What information was incorrect, unhelpful, or incomplete?
Bad url: https://html.validator.pro/

#### Specific section or headline?
HTML Validator Pro

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/validators`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Validators
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/validators/index.html
* Last commit: https://github.com/mdn/content/commit/5d8fbcb7e86afaae9504eda006c8ced7396b1d34
* Document last modified: 2021-04-28T23:00:48.000Z

</details>

**Comment by hamishwillee** [comment]
The site has an expired certificate, which is why it reports as a privacy risk. However it is the correct link for the site, and is widely linked to across the internet. 

@chrisdavidmills Does MDN have a link policy? It is a crap experience to get to a "this is a risky link" page, but on the other hand, that's on the vendor, not on MDN.

**Comment by BrianSmall** [comment]
Sorry: new to the game. I was thinking that link should be https://www.htmlvalidator.com/
But now that I look more closely at the website being pointed to by https://html.validator.pro/ it seems to be an unrelated and a dead site.

**Comment by hamishwillee** [comment]
@BrianSmall Odd - that site doesn't seem dead to me. Page renders OK 

![image](https://user-images.githubusercontent.com/5368500/116833544-27ef4580-abfd-11eb-982e-057719c875ca.png)


then when I click link it takes me to http://app.validator.pro/

![image](https://user-images.githubusercontent.com/5368500/116833538-1b6aed00-abfd-11eb-873c-3ffe366c4c65.png)

**Comment by wbamberg** [comment]
> Does MDN have a link policy? It is a crap experience to get to a "this is a risky link" page, but on the other hand, that's on the vendor, not on MDN.

This is a really good question. As far as I know we don't, and I wish we did. Very often people want to add external links and it's very hard to assess whether they are likely to be kept up to date, useful, and relevant. It's worse when we have pages, or sections of pages, that are laundry lists, like https://developer.mozilla.org/en-US/docs/Web/API/Websockets_API#tools.

But I'm not sure how we could write a policy which external links we should allow, and for making sure they stay relevant.

**Comment by hamishwillee** [comment]
FWIW I don't see an easy fix for this either. I have asked for at least an external link checker so that the _broken_ links get highlighted.
