### ISSUE TITLE
Issue with "SVG Tutorial": …

### ISSUE THREAD

**Issue by yberman** [mdn/content#466]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial

#### What information was incorrect, unhelpful, or incomplete?

The links referenced within the tutorial have the wrong URL.

For example the hyperlink `https://developer.mozilla.org/en-US/Web/SVG/Tutorial/Introduction` is dead.

#### Specific section or headline?

*Introducing SVG from Scratch*

#### What did you expect to see?

It should be `https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Introduction`. Note the `docs`.

#### Did you test this? If so, how?

I clicked the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/tutorial`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/svg/tutorial/index.html
* Report started: 2020-12-19T16:22:29.279Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this. I can’t reproduce this locally, so I guess it must have already been fixed in the sources (though I can’t find any record of a change that fixed it…)

**Comment by yberman** [comment]
Looking at the file's history, It seems as though b076f9c6a04eedaa6e1854cb66f18c52dc2535ad corrected it. I am closing the issue. @sideshowbarker do you know what the release schedule of developer.mozilla.org is documented? Thank you.

**Comment by sideshowbarker** [comment]
> @sideshowbarker do you know what the release schedule of developer.mozilla.org is documented?

It’s not yet documented, and not sure myself what schedule is planned
