### ISSUE TITLE
Content bug: There are several link flaws in "Using Web Workers"

### ISSUE THREAD

**Issue by mfuji09** [mdn/content#4660]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

## Specific page section or heading?

Further examples - Performing web I/O in the background
Other types of worker

## What is the problem?

There are several links to missing pages.

/en-US/docs/Using_workers_in_extensions
/en-US/js-ctypes
{{domxref("ChromeWorker")}}

These features seem Firefox-specific and these pages are already removed.

## What did you expect to see?

Should we keep these sentences mentioning Firefox-specific articles?

**Comment by sideshowbarker** [comment]
Opened https://github.com/mdn/content/pull/5475 with a fix.
