### ISSUE TITLE
Issue with "EventTarget.addEventListener()": …

### ISSUE THREAD

**Issue by mjschlot** [mdn/content#467]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

The example under the headline "Improving scrolling performance with passive listeners" has an error.

This
`get: function() { passiveIfSupported = { passive: false }; }`
Should be:
`get: function() { passiveIfSupported = { passive: true }; }`

The fix is "true" vs "false". The example is to show how to create a passive listener if the browser supports it, but it is actually doing the opposite and creating a non-passive listener if the browser supports passive.

**Comment by sideshowbarker** [comment]
Thanks for catching this. I’ve raised #468 with a fix.
