### ISSUE TITLE
Issue with "What is a web server?": "Typo" (probably bad choice by spellchecker)

### ISSUE THREAD

**Issue by jimjdm** [mdn/content#4679]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_web_server

#### What information was incorrect, unhelpful, or incomplete?
Excusing downtime and systems troubles, a dedicated web server is always connected to the Internet.

#### Specific section or headline?
Hosting files

#### What did you expect to see?
Excluding downtime...

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/common_questions/what_is_a_web_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_web_server
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/what_is_a_web_server/index.html
* Last commit: https://github.com/mdn/content/commit/6cd8fd2ae19f2acaa1f25e538cfc55de5a03dd6f
* Document last modified: 2021-01-27T13:22:33.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you. Fixed by https://github.com/mdn/content/pull/4685
