### ISSUE TITLE
"Destructuring assignment" needs an example where the left-hand side has more variables than there are values on the right-hand side

### ISSUE THREAD

**Issue by havajsky** [mdn/content#4682]
const foo = ['one', 'two'];

const [red, yellow, orange, pink] = foo;
console.log(red); // "one"
console.log(yellow); // 
console.log(orange); // undefined
console.log(pink); // undefined

**Comment by havajsky** [comment]
PS: It's not completely obvious what happens in such case given that it could possibly result in a runtime error.
PSS: I made an error (sorry); it should be:

const foo = ['one', 'two'];

const [red, yellow, orange, pink] = foo;
console.log(red); // "one"
console.log(yellow); // "two"
console.log(orange); // undefined
console.log(pink); // undefined

**Comment by havajsky** [comment]
Similarly:

const user = {
    id: 42
}

const {id, is_verified} = user;

console.log(id); // 42
console.log(is_verified); // undefined

(At least it's 'undefined' in Chrome.)

**Comment by NegiAkash890** [comment]
I can help with this , Please let me know if the above two examples are sufficient .

**Comment by chrisdavidmills** [comment]
@NegiAkash890 assigned!

I think the first example looks fine.

For the second one, maybe it'd be more effective to show the destructuring being used during the invocation of a function, to provide the function's arguments? Then you could even add a further example to show how this can be combined with a default parameter value...?

**Comment by NegiAkash890** [comment]
Hi @chrisdavidmills , before making any changes there are few things that I want to ask :
In this section :
[Basic Variable Assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#examples)
We already have an example under the section `Basic variable assignment` . Shall I add this [example](https://github.com/mdn/content/issues/4682#issue-874808742) below the first one or modify the existing one?

**Comment by sideshowbarker** [comment]
https://github.com/mdn/content/pull/5145 has been merged, with a fix that adds an example for array destructuring. What remains to do be done for this is to get a similar object destructuring example added, along the lines discussed here and in https://github.com/mdn/content/pull/5145. @akanshgulati, it seemed better to get the existing patch in https://github.com/mdn/content/pull/5145 merged first, so you can handle the remaining part in a follow-up PR.
