### ISSUE TITLE
Error in the <ul> Html demo

### ISSUE THREAD

**Issue by learningtech4everyone** [mdn/content#4697]
There is an error in the output of the unordered list element html demo.
<ul>
    <li>Milk</li>
    <li>Cheese
        <ul>
            <li>Blue cheese</li>
            <li>Feta</li>
        </ul>
    </li>
</ul>

**Comment by chrisdavidmills** [comment]
@learningtech4everyone what page and page section did you find this demo in?

**Comment by teoli2003** [comment]
II think it is there: https://developer.mozilla.org/en-US/docs/Web/Html/Element/ul

and it looks ok to me.

I propose to close this issue, unless @learningtech4everyone can point us to the problem (and it can be reopened in that case).

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/4697#issuecomment-849468807
