### ISSUE TITLE
Content suggestion: Can we add Internal data structure used by set?

### ISSUE THREAD

**Issue by namit-piriya** [mdn/content#4712]
## What is the new suggestion?
Internal data structure used by set.

## Why is it important or useful?
Useful to know what would be the tradeoffs when a programmer uses an inbuilt set in the code. What are the time complexity and space complexity of the data structure?
How many pages are likely to be needed? 1 paragraphs on the set page.
How much time do you think this work should take? A few hours? 
Will the work enable learners or professionals to achieve their goals better? yes
Does it address critical needs in the web industry? Don't know (I need comments on this)
Is the work an operational necessity, i.e. is not having it a security risk? No security risk
Does the content help make the web more ethical? No
 -->

## Other supporting information

<!-- include any other useful supporting information, such as spec URL,
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by chrisdavidmills** [comment]
To clarify, you are talking about putting this new content on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set?

**Comment by namit-piriya** [comment]
Yes, The page has no info about the underlying data structure used in set.

**Comment by Andrew-Cottrell** [comment]
Each JavaScript engine may use a different underlying data structure. The [specification](https://262.ecma-international.org/11.0/#sec-set-objects) has the following requirement

> Set objects must be implemented using either hash tables or other mechanisms that, on average, provide access times that are sublinear on the number of elements in the collection.

The [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) page could reflect that requirement using simple language that doesn't assume the reader is familiar with the term ["sublinear"](https://en.wikipedia.org/wiki/Time_complexity#Sub-linear_time).

**Comment by sideshowbarker** [comment]
I’ve opened https://github.com/mdn/content/pull/5988 with a change that add’s @Andrew-Cottrell’s suggested text to the article.
