### ISSUE TITLE
Issue with "CSS values and units": (short summary here please)

### ISSUE THREAD

**Issue by kevinwr** [mdn/content#4714]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units

#### What information was incorrect, unhelpful, or incomplete?
I may be wrong, but it's showing:

1. "1% of viewport's width." for the `vw` length unit
2. "1% of viewport's height." for the `vh` length unit
3. "1% of viewport's smaller dimension." for the `vmin` length unit.
4. "1% of viewport's larger dimension." for the `vmax` length unit.

#### Specific section or headline?
Relative length units

#### What did you expect to see?
It is my understanding from what I've learned elsewhere that the descriptions should be:

1. "100% of viewport's width." for the `vw` length unit
2. "100% of viewport's height." for the `vh` length unit
3. "100% of viewport's smaller dimension." for the `vmin` length unit.
4. "100% of viewport's larger dimension." for the `vmax` length unit.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_values_and_units`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_values_and_units/index.html
* Last commit: https://github.com/mdn/content/commit/5dd6db35dd3b775e26a9e0a5d285a814aae346c0
* Document last modified: 2021-03-03T15:28:08.000Z

</details>

**Comment by rachelandrew** [comment]
@kevinwr this seems correct to me, each of those is describing a single unit. 1vw is 1% of the viewport width, just as 1ch is the character advance of 1 `0`.

**Comment by rachelandrew** [comment]
Closing as this seems to be correct, please re-open if you have more info.
