### ISSUE TITLE
Issue with "Introduction to events": reference to deprecated method

### ISSUE THREAD

**Issue by mtcarvalho** [mdn/content#4716]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events

#### What information was incorrect, unhelpful, or incomplete?
On [Event handler properties](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_handler_properties) section, there is a reference to [`onkeypress`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onkeypress) property.

When I was answering the "Test your skills" [exercise](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Events#events_2) of this section, I opened the `onkeypress` property because it was on "Building blocks" section, then I noticed that this method is deprecated. Shouldn't this reference be removed?

#### Specific section or headline?
[Event handler properties](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_handler_properties) section

#### What did you expect to see?
I did not expect to see a deprecated method

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/events/index.html
* Last commit: https://github.com/mdn/content/commit/3af43c1dcfb9be19c73cf3fdd1178db9c74aa064
* Document last modified: 2021-04-27T01:03:07.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @mtcarvalho . I agree. Fixed in #5074
