### ISSUE TITLE
Issue with "Introduction to HTML": Broken link

### ISSUE THREAD

**Issue by migraineman** [mdn/content#4717]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML

#### What information was incorrect, unhelpful, or incomplete?
The  Web literacy basics 1 link under See also produces a Server Not Found message.

#### Specific section or headline?
See also
Web literacy basics 1

#### What did you expect to see?
The web page for Web literacy basics 1.

#### Did you test this? If so, how?
Clicking on the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/index.html
* Last commit: https://github.com/mdn/content/commit/2c6f017de416f5817a109191417d549c60e90055
* Document last modified: 2021-04-14T07:08:39.000Z

</details>

**Comment by rachelandrew** [comment]
@chrisdavidmills has this site gone? https://teach.mozilla.org/activities/web-lit-basics/
