### ISSUE TITLE
Update JS “Trailing commas” article to cover more cases

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/content#4719]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas currently covers the use of trailing commas in object literals, array literals, and function parameters. But there are other cases where trailing commas are allowed in JavaScript — including in named imports and named exports.

In the ES spec, the set of productions that allow a trailing comma are these:

* https://tc39.es/ecma262/#prod-Elision
* https://tc39.es/ecma262/#prod-ObjectLiteral
* https://tc39.es/ecma262/#prod-ArrayLiteral
* https://tc39.es/ecma262/#prod-Arguments
* https://tc39.es/ecma262/#prod-FormalParameters
* https://tc39.es/ecma262/#prod-CoverParenthesizedExpressionAndArrowParameterList
* https://tc39.es/ecma262/#prod-NamedImports
* https://tc39.es/ecma262/#prod-NamedExports
* https://tc39.es/ecma262/#prod-QuantifierPrefix
* https://tc39.es/ecma262/#prod-annexB-InvalidBracedQuantifier

So the “Trailing commas” article should be updated to cover all those cases.

**Comment by Blakelist7** [comment]
hey @sideshowbarker can I help with this one?

**Comment by sideshowbarker** [comment]
> hey @sideshowbarker can I help with this one?

Absolutely, yes — thanks, assigned you
