### ISSUE TITLE
Issue with "Book detail page": (Typo in bookController.js code)

### ISSUE THREAD

**Issue by Yug34** [mdn/content#4745]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_detail_page

#### What information was incorrect, unhelpful, or incomplete?
A minor mistake in the code for bookController.js

#### Specific section or headline?
`            
Book.findById(req.params.id)
  .populate('author')
  .populate('genre')
  .exec(callback);
`

Should have been 
`            
Book.findById(req.params.id)
  .populate('author')
  .populate('Genre')
  .exec(callback);
`

#### What did you expect to see?
I will give you the links to it below:

#### Did you test this? If so, how?
Tested it locally, hosted the version with the mistake, and after correcting it. Here are the screenshots of the outcomes:
- [Current](https://ibb.co/y42dPN5)
- [Fixed](https://ibb.co/QMXX6cM)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/book_detail_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_detail_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/book_detail_page/index.html
* Last commit: https://github.com/mdn/content/commit/76fad2ce69f136dcf941e756070b20e1618765d2
* Document last modified: 2021-03-19T00:47:15.000Z

</details>

**Comment by hamishwillee** [comment]
@Yug34 Thank you for reporting. I think this reflects an error in your code, not the tutorial. The `populate()` call takes the name of the field to be populated, which in this case is `genre` (lower case) - you can see this defined in the book model here: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#book_model

My guess is that you have copied the book model incorrectly.

I am closing this. But if you can reproduce with the demo version of the project, feel free to reopen: https://github.com/mdn/express-locallibrary-tutorial/
