### ISSUE TITLE
Content bug: external links on "Types of attacks" page are broken 

### ISSUE THREAD

**Issue by franquil** [mdn/content#4747]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/Security/Types_of_attacks

## Specific page section or heading?

Cross-site scripting (XSS)

## What is the problem?

An external link of "seventh most common Web app vulnerability" is broken.

## What did you expect to see?

The external page should show relevant content instead of a 404 page.

## Did you test this? If so, how?

Visit [types of attacks](https://developer.mozilla.org/en-US/docs/Web/Security/Types_of_attacks#cross-site_scripting_(xss)) page, click the " seventh most common Web app vulnerability" link, it should show a relevant page.

**Comment by hamishwillee** [comment]
Thanks. Fixed in #4775 - link was on the owasp site
