### ISSUE TITLE
Issue with "Web Console": (short summary here please)

### ISSUE THREAD

**Issue by omaliachenyo14** [mdn/content#4756]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Web_Console

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/web_console`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Web_Console
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/web_console/index.html
* Last commit: https://github.com/mdn/content/commit/ac254407cc3840c17c823f8522094ef68bbb65ad
* Document last modified: 2021-02-01T08:09:48.000Z

</details>

**Comment by hamishwillee** [comment]
Invalid - no actual problem reported.
