### ISSUE TITLE
Issue with "DELETE": Documentation of DELETE method.

### ISSUE THREAD

**Issue by tarasBilobran** [mdn/content#4758]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

#### What information was incorrect, unhelpful, or incomplete?
An example of DELETE request is incomplete.

#### Specific section or headline?
Headline "Example"

#### What did you expect to see?
I guess that header "Host" is missing in that example.
Instead of
```
DELETE /file.html HTTP/1.1
```
I expect to see something like
```
DELETE /file.html HTTP/1.1
Host: foo.example
```

#### Did you test this? If so, how?
In examples of HTTP POST and PUT methods header "Host" is present.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST#example
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT#example

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/methods/delete`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/methods/delete/index.html
* Last commit: https://github.com/mdn/content/commit/8d4fd702d9668604cb2788da5bd9fc9b796ec30a
* Document last modified: 2021-03-17T20:27:56.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @tarasBilobran. You're absolutely right - the host header is mandatory for HTTP/1.1 requests. Fixed in #4774
