### ISSUE TITLE
Issue with "Functions — reusable blocks of code": (short summary here please)

### ISSUE THREAD

**Issue by nochill-1** [mdn/content#4784]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Functions

#### What information was incorrect, unhelpful, or incomplete?
Active learning: Playing with scope doesnt bring the results/ it doesnt work like the article say

#### Specific section or headline?
see above

#### What did you expect to see?
the results like in the article

#### Did you test this? If so, how?
code studio, local instance

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/functions/index.html
* Last commit: https://github.com/mdn/content/commit/5ca8caa3cc747f154ab9859c34edf65688b966ea
* Document last modified: 2021-04-19T17:18:06.000Z

</details>

**Comment by nochill-1** [comment]
Re: It seems the issue comes from bad wording. Please make it clear that the output we should see isnt in the console but printed to the page. The text makes it seems like its being output to the browser console, which is false. it outputs undefined to the console and Value:N to the page.

**Comment by chrisdavidmills** [comment]
@nochill-1 I can see how this could be a little confusing. I've updated the wording so it is clearer where the different bits are printed to: https://github.com/mdn/content/commit/d13e75c929200d2383381eb378511491469c890c
