### ISSUE TITLE
Issue with "Function return values": Now it's your turn!

### ISSUE THREAD

**Issue by nochill-1** [mdn/content#4786]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Return_values

#### What information was incorrect, unhelpful, or incomplete?
Now it's your turn!

#### Specific section or headline?
Now it's your turn!

#### What did you expect to see?
How I am supposed to do this? I tried using tips from other sites and it doesnt work. It doesnt even throw up any errors, adding code to that seems to not affect anything

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/return_values`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Return_values
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/return_values/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by Shakil-Shahadat** [comment]
You need Math.sqrt() & Math.cbrt(). Circumference one is pretty straight forward.

Just writing a function will not do anything. Try calling them and then console.log() or alert() the return value.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/4786#issuecomment-835178108
