### ISSUE TITLE
Issue with "Function return values": How to add instructions to make it clearer?

### ISSUE THREAD

**Issue by nochill-1** [mdn/content#4788]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Return_values

I want to fix the last segment and add some instructions to make it clearer, how do I go about this?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/return_values`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Return_values
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/return_values/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by Rumyra** [comment]
Hi @nochill-1 - thanks so much! There's a contribution guide here https://github.com/mdn/content/blob/main/README.md :)

**Comment by sideshowbarker** [comment]
@nochill-1 Hi — do you still plan to work on this?

**Comment by nochill-1** [comment]
Oh, sorry. Its ok now :)
