### ISSUE TITLE
Content bug: <remoce acess telemetry related

### ISSUE THREAD

**Issue by k0n34** [mdn/content#4812]
## Specific page section or heading?

all the place

## What is the problem?

remote access via chrome shutting a thread before logs being marionette

## Did you test this? If so, how?
https://firefoxci.taskcluster-artifacts.net/ElX2HcBWR1G3f-AJTyiQYg/0/public/logs/live_backing.log

https://firefoxci.taskcluster-artifacts.net/ElX2HcBWR1G3f-AJTyiQYg/0/public/test_info//system-info.log

http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd

**Comment by teoli2003** [comment]
Is this a problem on MDN documentation?
It looks like you have a problem with Firefox?

**Comment by sideshowbarker** [comment]
Closing since it’s hard to imagine what change in MDN documentation would be anticipated for this
