### ISSUE TITLE
Issue with "flex": (flex with one value)

### ISSUE THREAD

**Issue by Hatsukoi-42** [mdn/content#4813]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/flex

#### What information was incorrect, unhelpful, or incomplete?
/* One value, unitless number: flex-grow */
flex: 2;

#### Specific section or headline?
Syntax section

#### What did you expect to see?
/* One value, unitless number: flex-grow */
/* flex-basis is then equal to 0 */
flex: 2;

#### Did you test this? If so, how?
I've tested it in JsFiddle and in my project, because the behavior was different between flex and flex-grow. The EN documentation did not explain the problem but the FR documentation had this precision.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/flex`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/flex
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/flex/index.html
* Last commit: https://github.com/mdn/content/commit/1ac2fa797952528ad709df84746d642d3b60f623
* Document last modified: 2021-03-16T04:42:22.000Z

</details>

**Comment by rachelandrew** [comment]
@Hatsukoi-42 thanks for raising the issue - the linked PR adds that note.
