### ISSUE TITLE
Issue with "Date() constructor": (short summary here please)

### ISSUE THREAD

**Issue by aronbeal** [mdn/content#4817]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

#### What information was incorrect, unhelpful, or incomplete?
No information on what is returned if an invalid string is passed to the Date constructor.

#### Specific section or headline?
Wherever is appropriate.

#### What did you expect to see?
A description of what is returned when an invalid date is passed.

#### Did you test this? If so, how?
Yes, tested online, with the string 'Sa, 24 221:00 GM'

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/date`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/date/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5983 with a fix.
