### ISSUE TITLE
Issue with "grid-template-columns": (instead of ----->"min-content"((min-content, max-content)   it should have been minmax((min-content ,max-content) )

### ISSUE THREAD

**Issue by RahulAgrawal885** [mdn/content#4818]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns

#### What information was incorrect, unhelpful, or incomplete?
If used outside of minmax() notation, auto represents the range between the minimum and maxium described above. This behaves similarly to "min-content" (min-content,max-content) in most cases.

#### Specific section or headline?
auto

#### What did you expect to see?
instead of min-content , i guess it should be minmax

#### Did you test this? If so, how?
vscode

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/grid-template-columns`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/grid-template-columns/index.html
* Last commit: https://github.com/mdn/content/commit/fc36604b19a172f3fbedb2629e2403180f2eda55
* Document last modified: 2021-03-19T23:16:59.000Z

</details>

**Comment by rachelandrew** [comment]
This is fixed by https://github.com/mdn/content/pull/4958 - thanks for the report!
