### ISSUE TITLE
Issue with "Firefox": Issue with Developer guide pages

### ISSUE THREAD

**Issue by nandanraj56** [mdn/content#4826]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox

#### What information was incorrect, unhelpful, or incomplete?
Developer guide link in side developers guide section is redirecting to achieved GitHub repo page.
This link has links to everything related to "how to get and compile the Firefox source code, how to find your way around, and how to contribute to the project".
Now how can one learn or contribute? Is there any new updated article available/ going to be available? 

#### Specific section or headline?
Firefox Key resources > Developer guide

#### What did you expect to see?
See page related to how to for developers, it has every info regarding source code, how to contribute; etc

#### Did you test this? If so, how?
I tried to click on the link, but took me to achieved GitHub repo page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/firefox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/index.html
* Last commit: https://github.com/mdn/content/commit/e1f56a952e0fc1bb67fb838efc395390c135e9c5
* Document last modified: 2021-02-02T17:34:08.000Z

</details>

**Comment by chrisdavidmills** [comment]
To whoever fixes this, there are multiple parts to this.

* First of all, we have removed all non-web platform from MDN's main content. A lot of this has now stopped displaying, after moving it to archived content.
* We should update the sidebar of the MDN Firefox section to stop pointing to these redirects, so they are not useful for MDN users.
* The Firefox documentation is supposed to be moved to https://firefox-source-docs.mozilla.org/contributing/index.html. Is there any equivalent there yet? If so, we can redirect or provide links to those pages.

**Comment by Blakelist7** [comment]
@chrisdavidmills I have made the required changes for part 3 please review them and let me know if some more changes are required.
Thanks

**Comment by chrisdavidmills** [comment]
@Blakelist7 thanks for that.

For the sidebar, the following macro defines this sidebar: https://github.com/mdn/yari/blob/main/kumascript/macros/FirefoxSidebar.ejs

This needs to be updated to something more sensible for the current state of the docs.

**Comment by Blakelist7** [comment]
@sideshowbarker could you please tell me what should I replace/update in the sidebar?

**Comment by sideshowbarker** [comment]
> @sideshowbarker could you please tell me what should I replace/update in the sidebar?

I’m sorry, I don’t know myself what specifically needs changing here

**Comment by teoli2003** [comment]
@Rumyra may help you.

**Comment by Rumyra** [comment]
Thanks all!

@escattone is this getting updated with the archived content move?

**Comment by escattone** [comment]
We didn't have any plans to update this page (or any other page) as part of the plan to stop displaying all archived content on MDN, since the hope was that we'd have redirects from those archived URL's to their new locations. We had planned to stop displaying all archived content on MDN this week, but now it looks like that will be delayed, and we're still trying to determine a new plan.

**Comment by Rumyra** [comment]
Thanks @escattone ☺️ Once we've made progress on the archived content move, I'll come back to this issue 👍

**Comment by Josh-Cena** [comment]
Since Firefox docs are gone, this should be completed (especially after https://github.com/mdn/content/pull/4885)
