### ISSUE TITLE
Issue with "Object.prototype.constructor": mistake in the example

### ISSUE THREAD

**Issue by norstbox** [mdn/content#4828]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor

#### What information was incorrect, unhelpful, or incomplete?
The following line in the example code ([link](https://github.com/mdn/content/blob/13360cbad46b4ce6457f80492d73d2efd252e8a9/files/en-us/web/javascript/reference/global_objects/object/constructor/index.html#L158)):
`Child = Object.assign(Child, ParentWithStatic)  // copies over the static members from ParentWithStatic to Child`

#### Specific section or headline?
"Examples" section, last example "Let's consider one more case."

#### What did you expect to see?
Absence of that line. It breaks the example, because no error occurs here ([link](https://github.com/mdn/content/blob/13360cbad46b4ce6457f80492d73d2efd252e8a9/files/en-us/web/javascript/reference/global_objects/object/constructor/index.html#L164)):
`let startPosition = this.constructor.getStartPosition() // error undefined is not a function, since the constructor is Child`
That error is fixed by the following code snippet (with [similar line](https://github.com/mdn/content/blob/13360cbad46b4ce6457f80492d73d2efd252e8a9/files/en-us/web/javascript/reference/global_objects/object/constructor/index.html#L175))

#### Did you test this? If so, how?
Run the example

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/constructor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/constructor/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by jculver050** [comment]
Close
