### ISSUE TITLE
In the <input type="range"> article, the “screenshot” example images of controls don’t look like the actual controls in current browsers 

### ISSUE THREAD

**Issue by NerdyDeedsLLC** [mdn/content#4830]
#### What information was incorrect, unhelpful, or incomplete?
In the API description illustrating how to add both tickmarks and labelled tickmarks in conjunction with the HTML `range` subtype of the `<input>` tag, the following is what displays (on a Mac, anyway):

> ![image](https://user-images.githubusercontent.com/43561032/117557148-aa309d00-b035-11eb-84cc-ed40eed6b9e9.png)

#### What did you expect to see?
Output vaguely-consistent with the screenshot "control" portion of the sample, or an update to the CanIUse compatibility chart. That is to say:

Based on MDN continuity and consistency experienced hitherto:

> 1. I'd expect 
> ![image](https://user-images.githubusercontent.com/43561032/117557271-d26ccb80-b036-11eb-80d9-e61e46f7eabf.png)
> to look like 
> ![image](https://user-images.githubusercontent.com/43561032/117557277-e1537e00-b036-11eb-9573-4e30a851593b.png)
> 
> 2. OR The article to have a prominent "NOTE: Except on MacOS"/"M1 MacOS"/"Chrome version 90+ for OCD pedants on a Mac/etc." 
(I'll do some cross-compatibility testing when I get home; this is all I have access to right now.)
> 
> 3. OR, The CanIUse grid should be either footnote annotated or updated to reflect the data more accurately.
> ![image](https://user-images.githubusercontent.com/43561032/117557158-c16f8a80-b035-11eb-99f5-21d501d539ae.png)

#### Did you test this? If so, how?

> Just bog-standard site usage: I was looking up syntax (couldn't figure out what the `label` on the `option` wasn't rendering). I took the above screenshots myself from my active session.

#### SYSTEM DETAILS:

> #### Browser
>   - Google Chrome - Version 90.0.4430.93 (Official Build) (arm64)
> 
> ##### Operating System
>  - MacOS Big Sur v. 11.2.3 (20D91)
> 
> ##### Hardware 
>   - Mac Mini M1 (2020) 16GB/512GB

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.input-range`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range
* Report started: 2021-05-09T00:37:33.463Z

</details>

**Comment by sideshowbarker** [comment]
@NerdyDeedsLLC So is the issue that the control which Chrome displays looks different from the **Screenshot** image?

**Comment by NerdyDeedsLLC** [comment]
@sideshowbarker Really depends. I was offering 3 different solutions to the potential issue.

## Problem
Both the screenshot imagery and the functionality as described (and corroborated by the compatibility data at the bottom of the article) are erroneous in the context of Chrome for MacOs.

## Suggested Resolutions
This suggests that either:
1. A notation needs to be made describing the exception in that case (inconsistent and less likely to get reconciled when an update occurs)
2. A second screenshot should be presented for the Mac version (overly-specific to an edge-case browser/os combination)
3. If specific to Mac the compatibility data should be updated, most likely with a footnote reflecting the abbaration.
4. If specific to Chrome at large the compatibility data...
![image](https://user-images.githubusercontent.com/43561032/117590246-196cc680-b0f4-11eb-9635-511504a11d6e.png)
...should be updated to "No"
