### ISSUE TITLE
Issue with "line-height": (short summary here please)

### ISSUE THREAD

**Issue by SukaiNDure** [mdn/content#4832]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height

#### What information was incorrect, unhelpful, or incomplete?
where is the 15px from?

#### Specific section or headline?

Prefer unitless numbers for line-height values
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/line-height`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/line-height/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by rachelandrew** [comment]
@SukaiNDure the 15px value comes from the red div's font size, there is a comment in the code explaining that. Or are you referencing something else?

**Comment by rachelandrew** [comment]
Closing as no response to my question, please re-open if you have further details.
