### ISSUE TITLE
Issue with "Cascade and inheritance": (short summary here please)

### ISSUE THREAD

**Issue by ManlyElectronics** [mdn/content#4833]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

#### What information was incorrect, unhelpful, or incomplete?
the paragraph '.. CSS stands for Cascading Style Sheets, and that first word cascading is incredibly important .... As you get more practice writing CSS, however, the way it works will become more obvious to you.'
is unhelpful and objective.

#### What did you expect to see?
The following phrase expected to be more specific: 'inheritance, which means that some CSS properties by default inherit values set on the current element's parent element, and some don't. ...
- that does not help to write code, WHAT exact CSS properties inherit values by default and which are do not ? For example positioning doesn’t cascade. What other properties do and do not ? I fail to see any details in the remaining paragraphs ether. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.html
* Last commit: https://github.com/mdn/content/commit/1fdf7958ea85bab45e1d7ba3634e9381eae937d1
* Document last modified: 2021-01-27T07:42:45.000Z

</details>

**Comment by Soumyafc** [comment]
can you please tell me what do you exactly want to see in that paragraph?

**Comment by ManlyElectronics** [comment]
I expected to see definitions of the cascading and inheritance. What are differences? Plus I want to see which css elements cascading which are not. As I found out positioning doesn’t cascade, for example. What other properties do not? And the list of properties which inherit and which do not by default too. 

The good explanation of Cascading Order I found at https://www.w3schools.com/whatis/whatis_css.asp Although they do not list which properties cascade which ones do not.

**Comment by rachelandrew** [comment]
@ManlyElectronics the individual syntax block on property pages details whether a property inherits or not: https://developer.mozilla.org/en-US/docs/Web/CSS/position#formal_definition

It would be a very long list to show them all here. 

I have previously raised an issue about generating a list of properties https://github.com/mdn/content/issues/3622 I don't think it belongs on this page though, but would be good to link to if we can create it programmatically.

**Comment by rachelandrew** [comment]
Closing as there is a separate issue regarding the list of properties.
