### ISSUE TITLE
Issue with "Finishing up": (short summary here please)

### ISSUE THREAD

**Issue by swelarsson** [mdn/content#4834]
MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Finishing_up

#### What information was incorrect, unhelpful, or incomplete?
When the ball hits the floor it moves the paddle so you never die. 

#### What did you expect to see?
When the ball hits the floor, you loose a life and at the end it´s game over

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/games/tutorials/2d_breakout_game_pure_javascript/finishing_up`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Finishing_up
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/tutorials/2d_breakout_game_pure_javascript/finishing_up/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by himanshugarg** [comment]
No changes required as the text that now appears instead is correct:-

> Now, when the ball hits the bottom edge of the screen, we're subtracting one life from the lives variable.

**Comment by teoli2003** [comment]
Closing per the previous comment. Feel free to reopen if I'm mistaken.
