### ISSUE TITLE
Issue with ":is() (:matches(), :any())": can't target pseudo-elements

### ISSUE THREAD

**Issue by wenfangdu** [mdn/content#4848]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:is

#### What information was incorrect, unhelpful, or incomplete?
Currently, `is()` doc doesn't contain info that it [can't target pseudo-elements](https://drafts.csswg.org/selectors-4/#matches).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_is`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:is
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_is/index.html
* Last commit: https://github.com/mdn/content/commit/775066d2fc8d1561d5da61983d137c1297899315
* Document last modified: 2021-05-08T09:57:47.000Z

</details>

**Comment by jculver050** [comment]
Close

**Comment by wenfangdu** [comment]
@jculver050 ?

**Comment by hamishwillee** [comment]
@wenfangdu FYI @jculver050 is clearly an idiot or a bot - has posted close against a bunch of things. I will delete this comment and his comment, shortly. Ignore anything else.
