### ISSUE TITLE
Content bug: isSameNode is deprecated but not mentioned on page

### ISSUE THREAD

**Issue by davwheat** [mdn/content#4866]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Node/isSameNode

## What is the problem?

As of DOMv4, isSameNode has the same effect as `===`. This is the new preferred way to do it, and should probably be mentioned on the page.

## What did you expect to see?

Maybe a message such as...

In DOM version 4, isSameNode was deprecated in favour of an equality check with `===`. isSameNode is now an alias to this check, and `===` should be used wherever possible.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5982 with a fix.
