### ISSUE TITLE
Issue with "Object.prototype.toString()": (short summary here please)

### ISSUE THREAD

**Issue by djave-co** [mdn/content#4868]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString

#### What information was incorrect, unhelpful, or incomplete?

In the first embedded example, the `toString` function is called. Instead, it should just be envoked by logging the variable name.

#### Specific section or headline?

Line 11 of `EmbedInteractiveExample("pages/js/object-prototype-tostring.html")` (I couldn't find the source to create pull request)

#### What did you expect to see?

I expected to see:

    console.log(dog1);

instead, it reads 

    console.log(dog1.toString());

which is just the same as manually calling a function on an object. While not wrong, it doesn't illustrate the point of the `toString` method to people specifically searching for it and its use cases.

#### Did you test this? If so, how?

Removing the `.toString()` on line 11 correctly prints out 

    > Gabby

PS thanks so much for all your work on the MDN docs, they are an amazing resource 🎉

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/tostring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/tostring/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
In Chrome 90, removing `.toString()` on line 11 results in the following output
```
> Dog {name: "Gabby"}
```
In general browsers may differ in output when logging values to the console, but they are consistent when instructed to log primitive strings. I suggest the example should remain as it currently is, with an explicit call to the `toString` method.

**Comment by djave-co** [comment]
Hi Andrew,

That is a good point about the console output being a bit funky. 

My main point is that if I write

```
Dog.prototype.anyFunctionName = function dogToString() {
  return `${this.name}`;
};

console.log(dog1.anyFunctionName());
```

The output will be the same as the example of `toString`. With that in mind I wanted to illustrate that `toString` is a special case. Perhaps that line in question should read:

    console.log(dog1 + " is my dog");

That way the console (both on mdn and chrome) will output:

    > Gabby is my dog

Which is both the expected output, and shows how `toString` magically converts the object into a string.

Thanks

**Comment by Andrew-Cottrell** [comment]
I suggest it is preferable to be explicit, rather than rely on _magic_, as the result may be unexpected
```javascript
var a = {toString: () => "Gabby", valueOf: () => 123};
var b = {toString: () => "Gabby", [Symbol.toPrimitive]: () => 456};

console.log(a + " is my dog");            // "123 is my dog"
console.log(String(a) + " is my dog");    // "Gabby is my dog"
console.log(a.toString() + " is my dog"); // "Gabby is my dog"

console.log(b + " is my dog");            // "456 is my dog"
console.log(String(b) + " is my dog");    // "456 is my dog"
console.log(b.toString() + " is my dog"); // "Gabby is my dog"
```
