### ISSUE TITLE
Issue with "Advanced form styling": property "padding" repeated in the same class

### ISSUE THREAD

**Issue by danielebarell** [mdn/content#4870]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling

#### What information was incorrect, unhelpful, or incomplete?
button, label, input, select, progress, meter {
  display: block;
  font-family: inherit;
  font-size: 100%;
  padding: 0;
  margin: 0;
  box-sizing: border-box;
  width: 100%;
  padding: 5px;
  height: 30px;
}

padding is set to 0 then to 5px
#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling#what_can_be_done_about_the_ugly_elements

#### What did you expect to see?
button, label, input, select, progress, meter {
  display: block;
  font-family: inherit;
  font-size: 100%;
  /*padding reset should be 0 then we augment with some pixels*/
  padding: 5px;
  margin: 0;
  box-sizing: border-box;
  width: 100%;
  height: 30px;
}

#### Did you test this? If so, how?
Didn't test the solution, it's a minor flaw to me.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/advanced_form_styling`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/advanced_form_styling/index.html
* Last commit: https://github.com/mdn/content/commit/5fb569eddc18081727c03bb97cdb4c67f084804c
* Document last modified: 2021-04-24T03:00:55.000Z

</details>

**Comment by rachelandrew** [comment]
@danielebarell thanks for the report, the PR I have just made should fix this.

**Comment by danielebarell** [comment]
@rachelandrew 
Hi Rachel.
Happy to be helpful.  :)
I'm enjoing this form module so much. 
I'm greatful to you all.
