### ISSUE TITLE
Issue with "CSP: *-src": hash directive specified for types that are not script or inline unclear

### ISSUE THREAD

**Issue by josh-hemphill** [mdn/content#4877]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src#sources

#### What information was incorrect, unhelpful, or incomplete?

> `<hash-algorithm>-<base64-value>`
> ... In CSP 2.0, this is applied only to `inline scripts`. CSP 3.0 allows it in the case of `script-src for external scripts`.

This is specified for child-src, frame-src, worker-src, connect-src, font-src, img-src, manifest-src, media-src, object-src, and base-uri; all of which are fetch-only/do not have inlined content as far as I know. So it's not clear if or how these relate to the type of element the rest of the page describes.

Is it just a technicality of the spec that was carried over or something of that sort?

#### Specific section or headline?

Sources > `<hash-algorithm>-<base64-value>`

#### What did you expect to see?

A description of how the directive relates to the rest of the content of the page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/img-src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/img-src/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by bsmth** [comment]
Note that it looks like the content being referred to in this issue has been moved out to the index (`files/en-us/web/http/headers/content-security-policy/sources/index.md`) in https://github.com/mdn/content/commit/7cbcf01266fa25c283bd8b7acd35f856fb9a7b48
