### ISSUE TITLE
Have a consistent opening paragraph for HTML elements

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#4884]
This came out of https://github.com/mdn/content/pull/4792 , which changes the preamble bit for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button from:

"The **HTML \<button> element** represents..."

to

"The **HTML \<button>** element represents..."

It would be nice to be consistent here, and it would be good to know what people think we should use. Some options:

1) "The **HTML Content Division element (\<div>)** ..."
2) "The **HTML \<div> element** ..."
3) "The **HTML \<div>** element ..."
4) "The HTML **\<div>** element ..."
5)  "The **\<div>** element ..."

Having written all these out, I think I like 4 best. I believe the extra words in (1) was connected with SEO, but I'm not sure that's really a good reason to do it.

* the JS docs use "The **slice()** method ... ", which is more like (5)
* the CSS pages uses "The **box-shadow** [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) property ..." which is close to (4), but also links to the main CSS page. We could do the same for (4) above.
* the Web API pages seem to do "The **error()** method of the [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) interface ...", which is somewhere in the (4)/(5) territory.

**Comment by hamishwillee** [comment]
Of the options presented I prefer option 4. In particular IMO only the element itself should be highlighted in bold (and I even consider that "optional"). 

If the HTML context is important (and I think it is), then arguably this is a better approach:

![image](https://user-images.githubusercontent.com/5368500/117750918-96648100-b257-11eb-86fb-0f8a5b80a817.png)

In case it is helpful
![image](https://user-images.githubusercontent.com/5368500/117750478-d1b28000-b256-11eb-9477-2291d92e48d9.png)
