### ISSUE TITLE
Issue with "Window.open()": (short summary here please)

### ISSUE THREAD

**Issue by ZNackasha** [mdn/content#4890]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/open

#### What information was incorrect, unhelpful, or incomplete?

this does not have info on the forth paramater of open. aka replace. this parameter is used to indicate if you want to replace the current URL or not

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/open`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/open
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/open/index.html
* Last commit: https://github.com/mdn/content/commit/e126945260051a0029af1ca19056eb882bf8e2e1
* Document last modified: 2021-04-29T03:56:11.000Z

</details>

**Comment by dorward** [comment]
I don't see a 4th parameter in [the specification](https://html.spec.whatwg.org/multipage/window-object.html#dom-open)

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/4890#issuecomment-853797199

For some related background, see https://bugs.chromium.org/p/chromium/issues/detail?id=1164959

It would not be helpful to developers for MDN to document a non-standard parameter that’s not supported cross-browser in current browser engines.
