### ISSUE TITLE
Issue with "Django Tutorial Part 10: Testing a Django web appl…": assertTrue => assertEqual

### ISSUE THREAD

**Issue by andrehora** [mdn/content#4891]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing

#### What information was incorrect, unhelpful, or incomplete?

Not sure it was intentional, but here instead of using `assertTrue` (in methods `test_pagination_is_ten` and `test_lists_all_authors`):

```python
self.assertTrue(len(response.context['author_list']) == 10)
self.assertTrue(len(response.context['author_list']) == 3)
```

... it would be better to check with `assertEqual` (to facilitate debugging as suggested on page itself): 

```python
self.assertEqual(len(response.context['author_list']), 10)
self.assertEqual(len(response.context['author_list']), 3)
```

#### Specific section or headline?

LocalLibrary tests>>Views

#### What did you expect to see?

In methods `test_pagination_is_ten` and `test_lists_all_authors`:

```python
self.assertEqual(len(response.context['author_list']), 10)
self.assertEqual(len(response.context['author_list']), 3)
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/testing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/testing/index.html
* Last commit: https://github.com/mdn/content/commit/3af43c1dcfb9be19c73cf3fdd1178db9c74aa064
* Document last modified: 2021-04-27T01:03:07.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @andrehora 

Sure. Added to https://github.com/mdn/content/pull/4896
