### ISSUE TITLE
Issue with "Array.prototype.sort()": (incorrect description)

### ISSUE THREAD

**Issue by guillermovasta** [mdn/content#4895]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

"If compareFunction(a, b) returns less than 0, leave a and b unchanged." **unchanged**?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/sort`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/sort/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by wbamberg** [comment]
Can you please explain in a bit more detail what the issue is here?

**Comment by guillermovasta** [comment]
Hi @wbamberg, 
The sentence is incorrect. It should say something like "If the result is negative **a** is sorted before **b**."
Thanks

**Comment by wbamberg** [comment]
I think "unchanged" means "their positions in the array are unchanged", because `a` was before `b` already, and that's what `compareFunction` is telling us they should be. If this page said that instead, would you consider this a fix? I think "`a` is sorted before `b`" implies to me that something is being changed in the array order, which it's not, as far as I can see.

**Comment by guillermovasta** [comment]
Yes. 
Check the same page, and sentence in Spanish:

"Si `compareFunction(a, b)` es menor que 0, se sitúa `a` en un indice menor que `b`. Es decir, `a` viene primero." -> "If `compareFunction(a, b)` is less than 0, a is placed in `a` lower index than `b`. Namely, `a` comes first."

**Comment by guillermovasta** [comment]
duplicated https://github.com/mdn/content/issues/2769
