### ISSUE TITLE
Typo in "flex-grow", first paragraph

### ISSUE THREAD

**Issue by leonard-9500** [mdn/content#490]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/flex-grow

#### What information was incorrect, unhelpful, or incomplete?
"The flex-grow CSS property sets the flex grow factor of a flex **item** main size."

#### Specific section or headline?
First paragraph.

#### What did you expect to see?
"The flex-grow CSS property sets the flex grow factor of a flex **item's** main size."

#### Did you test this? If so, how?
/

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/flex-grow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/flex-grow
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/flex-grow/index.html
* Report started: 2020-12-20T08:32:06.629Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. I’ve raised https://github.com/mdn/content/pull/491 with a fix.
