### ISSUE TITLE
svg thread blocking problem

### ISSUE THREAD

**Issue by BlairOu** [mdn/content#4906]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG

#### I use animateMotion to make a SVG loadingSpinner, but the animation will be block before the page is fully loaded

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/index.html
* Last commit: https://github.com/mdn/content/commit/82a7fbd2b14c904ae7651bc8e144982837d1257a
* Document last modified: 2021-03-15T04:35:25.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Hey @BlairOu,
this sounds like a question regarding the usage of SMIL (`animateMotion` attribute in SVG).
These are best to asked on StackOverflow or that like.

This repo here is meant to document the web elements and attributes. The linked URL does not deal with `animationMotion` directly, so I'm going to close this issue.

The spec does not markup the attribute as deprecated: https://svgwg.org/specs/animations/#AnimateMotionElement
(but you might get away with a CSS `transform: rotate(360deg)`).
