### ISSUE TITLE
Issue with "Element.innerHTML": in the warning 'don't use for AMO', give a solution

### ISSUE THREAD

**Issue by opto** [mdn/content#4908]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML

#### What information was incorrect, unhelpful, or incomplete?
the yellow warning box phrases a 'don't use this for AMO submissions'

#### What did you expect to see?

tell what to use instead. In duscussions with TBSync/John Bieling for submissions to ATN, the solution was to use Element.insertAdjacentHTML() instead.

There are some links to this, but in different contexts. I wouldn't have found this as a solution without a discussion with John.

context 1: in see also. Well, there are millions of see also in MDN. No indication it would solve the submission to AMO problem.
context 2: it is mentioned here:
To insert the HTML into the document rather than replace the contents of an element, use the method insertAdjacentHTML().

-> for replacing the contents of the element, this advises against insertAdjacentHTML? But the real solution would be to use it always?

conclusion: the current text is not clear in what to do if one wants to submit to AMO or ATN.

thanks,

Klaus
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/innerhtml`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/innerhtml/index.html
* Last commit: https://github.com/mdn/content/commit/86de1299767c0d968c1dbcc29f40c95f5a7c5db9
* Document last modified: 2021-03-12T02:50:17.000Z

</details>

**Comment by chrisdavidmills** [comment]
> unfortunately not, as that inserts text.
> 
> innerHtml is about inserting html, and there are valid use cases where one wants to do that in a secure way.
> So if AMO does not accept that html is added by using innerHtml, which way of adding html does AMO accept? It would help to spell that out.

Right, I see what you mean here. I mean, I usually tend to create HTML elements with `createElement()`, set text content with `textContent`, and then assemble the fragment together with `appendChild()` calls, but I can see why this is not always ideal.

Let's ask someone. @caitmuenster , can you comment on what the AMO recommendation is for inserting HTML fragments, without using `innerHTML`? Many thanks.

**Comment by opto** [comment]
thanks. createElement can't be used:
use scenario is an app for formatted notes. Use an editor to create formatted notes, store the html note in localstorage, for later display: the ready made html needs to go into an element.

**Comment by wagnerand** [comment]
> thanks. createElement can't be used:
> use scenario is an app for formatted notes. Use an editor to create formatted notes, store the html note in localstorage, for later display: the ready made html needs to go into an element.

A cleaner way would be to store the information in a structured format (e.g. JSON) and build the DOM block from the structured data when you insert it.

**Comment by caitmuenster** [comment]
Hi @opto, you might find this article helpful: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page

In the meantime, I can tweak the warning language.

**Comment by opto** [comment]
@caitmuenster  and @wagnerand  Thanks, that link is very helpful.

my html comes from a js text editor, so it 'should' be ok - the user has no direct access to the html. But sanitizing is definitely good, I was actually looking for somewhat like that but found only stuff removing all html, which did not fit to my use case.
so thanks.
Klaus

**Comment by wagnerand** [comment]
@opto For what it's worth, the user does not need direct access to the HTML. The vulnerability here is that the user can write text in the editor that is then interpreted as HTML due to the usage of `innerHTML`. For example, the user could write something like:

```This is a <img src="" onerror="javascript:alert(1)"> test```

Passing that string to `innerHTML` causes the `img` tag to be evaluated, including the javascript code defined in the `onerror` attribute.

Generally, your add-on should not trust any information that it receives from outside of the extension. This can be a website, server, another computer, user input or even another program running on your computer. You should not trust any of such content and make sure it is properly sanitized or never evaluated.

**Comment by opto** [comment]
@wagnerand thanks for the info. I would naively have expected the js editor to mask a < in the usertext against a < in its own html. If it  sets the textContent next to the html, your concern is truely very valid.

I think there are some editors around that deliver json. The problem is that most don't work in TB in a content script, because they use internally unsafe code (e.g. ckeditor4 runs in a FF tab, but not in a TB message window, and ckeditor 5 has the wrong license).
It took me quite a while to find an editor  that is not rejected due to its internal code.  Apparently, many authors of editors know about the problem since years but haven't updated. It is still running in html documents to be displayed, it is just the content scripts rejecting those editors.

thanks,

Klaus
