### ISSUE TITLE
Issue with "linear-gradient()": About color stops.

### ISSUE THREAD

**Issue by CC2m2** [mdn/content#4918]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient()

#### What information was incorrect, unhelpful, or incomplete?
Maybe a value is wrong.

#### Specific section or headline?
Customizing Gradients.

#### What did you expect to see?
About the paragraph: "Color stops should be listed in ascending order. Subsequent color stops of lower value will override the value of the previous color stop creating a hard transition. The following changes from red to yellow at the 30% mark, and then transitions from yellow to blue over 35% of the gradient." I think the following change from red to yellow is at 40% mark not at 30% mark.

#### Did you test this? If so, how?
I tested this in my browser.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/linear-gradient()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/linear-gradient()/index.html
* Last commit: https://github.com/mdn/content/commit/25cc5c5c4f999bf49204ae067eb2c30ccb3492c8
* Document last modified: 2021-05-10T22:50:26.000Z

</details>

**Comment by wbamberg** [comment]
Yes, I think you are right. That would also make the transition from yellow to blue 25%, wouldn't it?

(40% solid red, 25% yellow-blue, 35% blue)

<img width="384" alt="Screen Shot 2021-05-14 at 11 16 00 AM" src="https://user-images.githubusercontent.com/432915/118312141-c903b900-b4a5-11eb-865a-c3a594f5eb5e.png">


I'm also not really sure what "override" means in that paragraph. "Subsequent color stops of lower value will be partially overlapped by the previous color stop" seems nearer the truth?

**Comment by CC2m2** [comment]
I think 25% yellow-blue is right. About "overlapped", I'm not sure. But it do better than "override" I think. 
And I am new to GitHub. So since the issue is solved, should I close the comment or pull a request or...?

**Comment by CC2m2** [comment]
I think 25% yellow-blue is right. About "overlapped", I'm not sure. But it do better than "override" I think. 
And I am new to GitHub. So since the issue is solved, should I close the comment or pull a request or...?

**Comment by wbamberg** [comment]
What happens next is someone opens a pull request to fix the page, it gets reviewed and merged, then we can close this issue.

If you would like to open a pull request I would be happy to review it. Otherwise I will open a pull request to fix it.

There are instructions here: https://github.com/mdn/content#making-contributions - you could probably go with https://github.com/mdn/content#simple-changes for this change.
