### ISSUE TITLE
Issue with "Element.setAttribute()": incorrect claim that use of attribute's name is non-standard

### ISSUE THREAD

**Issue by Andrew-Cottrell** [mdn/content#4921]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute

#### What information was incorrect, unhelpful, or incomplete?
> Boolean attributes are considered to be true if they're present on the element at all, regardless of their actual value; as a rule, you should specify the empty string ("") in value (some people use the attribute's name; this works but is non-standard).

I didn't expect an incorrect claim that use of the attribute's name is non-standard.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute#parameters

#### What did you expect to see?

Something like

> Boolean attributes are considered to be true if they're present on the element at all, regardless of their actual value; you should specify either the empty string ("") or the attribute's name (with no leading or trailing whitespace).

#### Did you test this? If so, how?
I checked what the HTML standard states regarding boolean attributes.

> If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

Ref: https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/setattribute`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/setattribute/index.html
* Last commit: https://github.com/mdn/content/commit/56d9a678477f0e79232caa8169114519bf02a44a
* Document last modified: 2021-02-19T19:41:18.000Z

</details>

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/issues/4921 .
