### ISSUE TITLE
Unable to access documentation for "Frame and message structure in HTTP/2"

### ISSUE THREAD

**Issue by jojorm37** [mdn/content#4922]
Hi Team,

First of all, thank you for your efforts in creating the documentation for HTTP, I was planning to learn more about HTTP2.0 implementation and came across an issue due to which I am not able to access the page. The below URL which is shared on other pages(I got redirected from https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP) as well

https://developer.mozilla.org/en-US/docs/Web/HTTP/Frame_and_message_structure_in_HTTP_2 

Error details:

Page not found
Sorry, the page /en-US/docs/Web/HTTP/Frame_and_message_structure_in_HTTP_2 could not be found.

Thanks and Regards,
Ujjwal Sharma

**Comment by hamishwillee** [comment]
Sadly the page does not exist/needs to be written. The only explanation on MDN that I know of is https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages#http2_frames

**Comment by bsmth** [comment]
This is fixed as the broken link is gone, but there is related work in:

- [ ] https://github.com/mdn/content/pull/36029
