### ISSUE TITLE
Issue with "Inheritance and the prototype chain": (short summary here please)

### ISSUE THREAD

**Issue by Walluri** [mdn/content#4928]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain

#### What information was incorrect, unhelpful, or incomplete?
Incorrect if i may say.
Present code : 
                        function Graph() {
                          this.vertices = [];
                          this.edges = [];
                        }

                        Graph.prototype = {
                          addVertex: function(v) {
                            this.vertices.push(v);
                        }
                        };

                        var g = new Graph();
                        // g is an object with own properties 'vertices' and 'edges'.
                        // g.[[Prototype]] is the value of Graph.prototype when new Graph() is executed.

Expected code : 
                        function Graph() {
                          this.vertices = [];
                          this.edges = [];
                        }

                        Graph.prototype.addVertex = function(v) {
                            this.vertices.push(v);
                        }                    

                        var g = new Graph();
                        // g is an object with own properties 'vertices' and 'edges'.
                        // g.[[Prototype]] is the value of Graph.prototype when new Graph() is executed.

#### Specific section or headline?
Section Name : With a constructor
Code under this sub section is possibly incorrect.

#### What did you expect to see?
Assigning a value to Graph.Prototype will change and break the prototype chain.
The correct code which i expected to see is above.

#### Did you test this? If so, how?
Code for testing :
var graphObject = new Graph();
console.log(graphObject);
// In the console we do not the constructor function of Graph as part of the __proto__ property

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/inheritance_and_the_prototype_chain`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/inheritance_and_the_prototype_chain/index.html
* Last commit: https://github.com/mdn/content/commit/cfb4bda4fda17e8a16f7b9c8d9ca42f15efbac13
* Document last modified: 2021-05-07T15:52:46.000Z

</details>

**Comment by jamesaucode** [comment]
Looks like it's already fixed? 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain#with_a_constructor

**Comment by teoli2003** [comment]
Yes, fixed in #6751.

(Thanks for the report!)
