### ISSUE TITLE
Issue with "RegExp.prototype.exec()": String.prototype.search() is described as returning Boolean

### ISSUE THREAD

**Issue by cdoublev** [mdn/content#493]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec

#### What information was incorrect, unhelpful, or incomplete?

`String.prototype.search()` is described as returning `true` or `false`.

#### Specific section or headline?

> If you are executing a match simply to find true or false, use RegExp.prototype.test() method or String.prototype.search() instead.

#### What did you expect to see?

```diff
- If you are executing a match simply to find true or false, use RegExp.prototype.test() method or String.prototype.search() instead.
+ If you are executing a match simply to find true or false, use RegExp.prototype.test() method instead.
+ 
+ If you are executing a match simply to find its index position in the string, use String.prototype.search() method instead.
```

#### Did you test this? If so, how?

No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/regexp/exec`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/regexp/exec/index.html
* Report started: 2020-12-20T12:51:41.544Z

</details>

**Comment by Scttpr** [comment]
#520 resolves issue with proposed changes
