### ISSUE TITLE
Issue with "Create Author form": (short summary here please)

### ISSUE THREAD

**Issue by Zheng7426** [mdn/content#4937]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_author_form

#### What information was incorrect, unhelpful, or incomplete?
Date_of_death section was missing from the /views/author_form.pug code snippet.

#### Specific section or headline?
View

#### What did you expect to see?

label(for='date_of_death')
            h5 Date of death:
            input#family_name.form-control(type='text', placeholder='mm/dd/yyyy' name='date_of_death' value=(undefined===author ? '' : author.date_of_death))

#### Did you test this? If so, how?
Yes. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_author_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_author_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_author_form/index.html
* Last commit: https://github.com/mdn/content/commit/dddbd4887e759ab5f6a2f5b181f2b3f44648b872
* Document last modified: 2021-02-24T03:28:35.000Z

</details>

**Comment by Zheng7426** [comment]
input#family_name.form-control(type='date', name='date_of_death' value=(undefined===author ? '' : author.date_of_death))

**Comment by Zheng7426** [comment]
I am sorry, I did not see that the challenge was to add the missing date_of_death field. I think we can close this now. Apologies for the mistake.

**Comment by hamishwillee** [comment]
Thanks for taking the time to let us know!
