### ISSUE TITLE
Issue with "MediaStreamTrack: ended event": note that this event is not fired when the user calls .stop() on the track

### ISSUE THREAD

**Issue by receter** [mdn/content#4939]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/ended_event

#### What information was incorrect, unhelpful, or incomplete?
It would be worth noting that this event is not fired when the user calls .stop() on the track.

Also this page should include this information somehow in my Opinion:
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack#events
ended
Sent when playback of the track ends **(when the value readyState changes to ended)**.
Also available using the onended event handler property.

In the case of calling .stop() yourself, readyState DOES change to ended but the event is not fired.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediastreamtrack/ended_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/ended_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediastreamtrack/ended_event/index.html
* Last commit: https://github.com/mdn/content/commit/c016a6b893578b1f39794983682c6d9107910226
* Document last modified: 2020-12-21T07:50:05.000Z

</details>

**Comment by Josh-Cena** [comment]
Related: https://github.com/mdn/content/pull/11372
