### ISSUE TITLE
Issue with "<iframe>: The Inline Frame element": (short summary here please)

### ISSUE THREAD

**Issue by th3N0m4d** [mdn/content#4943]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

#### What information was incorrect, unhelpful, or incomplete?

One of the iframe examples is not working. 

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#example1

#### What did you expect to see?

A page loaded into the iframe

#### Did you test this? If so, how?

I created a pin on JS Bin. The link is [here](https://jsbin.com/yasevaravi/edit?html,output).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/iframe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/iframe/index.html
* Last commit: https://github.com/mdn/content/commit/690965e33f6663ef450e6ed9edd9a7e7f73f96c5
* Document last modified: 2021-03-27T00:58:07.000Z

</details>

**Comment by F4R4N** [comment]
the source of examples (https://mdn-samples.mozilla.org/) is not working anymore.
check #4116 .
