### ISSUE TITLE
Issue with "Array.prototype.reduce()": …

### ISSUE THREAD

**Issue by tomasz13nocon** [mdn/content#495]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#Description

#### What information was incorrect, unhelpful, or incomplete?
At the end of the Description section it says:  "_It is almost always safer to provide an `initialValue`, because there can be up to four possible output types without `initialValue`, as shown in the following example:_".
However in the code that follows, the first and third invocations return `NaN` and `{ x: 2 }` respectively, not because of lack of the `initialValue` argument, but because the callback used (`maxCallback`) takes objects as arguments and returns an integer.
If we call `map` first and use the second callback, like it is further in the code, **but** we don't specify the `initialValue` the output in the first three invocations will be as expected.

So the "four different output types" are due to improper way of using `reduce` rather than lack of `initialValue`.

#### Specific section or headline?
End of the Description section

#### What did you expect to see?
`TypeError` is still expected for invocation of `reduce` on an empty array

#### Did you test this? If so, how?
```js
let maxCallback2 = ( max, cur ) => Math.max( max, cur );

// No initialValue, yet the results are correct
console.log([ { x: 2 }, { x: 22 }, { x: 42 } ].map( el => el.x ).reduce( maxCallback2 )); // 42
console.log([ { x: 2 }, { x: 22 }            ].map( el => el.x ).reduce( maxCallback2 )); // 22
console.log([ { x: 2 }                       ].map( el => el.x ).reduce( maxCallback2 )); // 2
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/reduce`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/array/reduce/index.html
* Report started: 2020-12-18T11:14:39.138Z

</details>

**Comment by kocvrek** [comment]
I would like to work on this issue.

**Comment by chrisdavidmills** [comment]
@kocvrek assigned; thanks a lot for the offer of help!

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/pull/4741, thanks @kocvrek !
