### ISSUE TITLE
Issue with "Element": Methods erroneously listed as obsolete

### ISSUE THREAD

**Issue by hasanyasin** [mdn/content#4956]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element

#### What information was incorrect, unhelpful, or incomplete?
"Obsolete methods" section lists methods that were deprecated in now deprecated DOM4, i.e. the listed methods 
`Element.getAttributeNode()`
`Element.getAttributeNodeNS()`
`Element.removeAttributeNode()`
`Element.setAttributeNode()`
`Element.setAttributeNodeNS()`
are not really obsolete anymore as they are documented in the live DOM Standard and I couldn't find any mention of these being deprecated.

#### Specific section or headline?
[Obsolete methods](https://developer.mozilla.org/en-US/docs/Web/API/Element#obsolete_methods)

#### What did you expect to see?
As none of the listed methods are obsolete, this section should be removed.

#### Did you test this? If so, how?
[Current standard, DOM](https://dom.spec.whatwg.org/#element), which is also what this page itself calls the live standard, documents each of the methods as part of `Element` interface.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/index.html
* Last commit: https://github.com/mdn/content/commit/f2a9cd26197733d09c0547ce7d750c65ca59a812
* Document last modified: 2021-04-27T06:37:39.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks for reporting @hasanyasin - fixed by @wbamberg in #4963 :-).
