### ISSUE TITLE
Issue with "HTTP": (short summary here please)

### ISSUE THREAD

**Issue by mehrdad6699** [mdn/content#4966]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/index.html
* Last commit: https://github.com/mdn/content/commit/48fca0c614add538e95f1075b2777fc396023d31
* Document last modified: 2021-03-16T07:50:01.000Z

</details>

**Comment by hamishwillee** [comment]
Closing. There is no actionable information in this report.
