### ISSUE TITLE
Issue with "Deprecated and obsolete features": unhelpful replacement suggested for Date.prototype.toGMTString

### ISSUE THREAD

**Issue by Andrew-Cottrell** [mdn/content#4967]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features

#### What information was incorrect, unhelpful, or incomplete?
> You should use `toISOString` instead of the deprecated `toGMTString` method in new code.

`toISOString` is not a suitable replacement.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features#date_methods

#### What did you expect to see?
> You should use `toUTCString` instead of the deprecated `toGMTString` method in new code.

`toUTCString ` is a suitable replacement.

#### Did you test this? If so, how?
The `Date.prototype.toGMTString` page has

> Note: `toGMTString()` is deprecated and should no longer be used. It remains implemented only for backward compatibility; please use `toUTCString()` instead.

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toGMTString

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/deprecated_and_obsolete_features`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/deprecated_and_obsolete_features/index.html
* Last commit: https://github.com/mdn/content/commit/892914472e50d4730cef36d8ab00c6f82503a5f1
* Document last modified: 2021-02-02T23:17:03.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5979 with a fix.
