### ISSUE TITLE
Issue with "font-family": Should I quote family names containing whitespaces or not?

### ISSUE THREAD

**Issue by alattalatta** [mdn/content#4970]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

#### What information was incorrect, unhelpful, or incomplete?

Description of `<family-name>` states that "Font family names containing whitespace **should** be quoted."

But even its syntax box contains `font-family: Gill Sans Extrabold, sans-serif` which makes it confusing.

#### Specific section or headline?

Values - `<family-name>`

#### What did you expect to see?

Word "should" seems too strong. Also, reasons to quote such names?

#### Did you test this? If so, how?

No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/font-family`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-family/index.html
* Last commit: https://github.com/mdn/content/commit/775066d2fc8d1561d5da61983d137c1297899315
* Document last modified: 2021-05-08T09:57:47.000Z

</details>

**Comment by wbamberg** [comment]
> reasons to quote such names?

The spec has details on the exact rules: https://drafts.csswg.org/css-fonts-4/#family-name-syntax and a similar but slightly more precise recommendation:

> To avoid mistakes in escaping, it is recommended to quote font family names that contain white space, digits, or punctuation characters other than hyphens

And yes, I agree, our syntax and examples should definitely follow the recommended practice here (see also https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#some_common_font_families).

**Comment by Blakelist7** [comment]
@wbamberg  are you expecting examples to be as in the ss.
![Screenshot from 2021-05-14 16-09-16](https://user-images.githubusercontent.com/54525960/118259548-ebf69300-b4ce-11eb-8038-fff1ea045391.png)

**Comment by Blakelist7** [comment]
I am creating a PR please see to it and let me know if it is ok  https://github.com/mdn/interactive-examples/pull/1817

**Comment by wbamberg** [comment]
I thought this issue was about making code samples in https://developer.mozilla.org/en-US/docs/Web/CSS/font-family quote font family names that contain spaces (and perhaps to sharpen the guidance at https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#valid_family_names).

There are some places in the page that have unquoted font family names with spaces, but the interactive example does quote. So I'm not sure why a fix for this issue would involve changing the interactive example.

**Comment by Blakelist7** [comment]
ohk I am really sorry I misunderstood it, for changing examples format.
I'll fix it .

**Comment by wbamberg** [comment]
@Blakelist7 , you have nothing to apologise for! I appreciate your contributions to MDN :). I'm just trying to make sure we're clear on what the issue here is.

**Comment by Blakelist7** [comment]
Ig now we're on the page:)

**Comment by Blakelist7** [comment]
Hey! @wbamberg for the time being I have fixed the issue but should we add an article regarding the same that is not compulsory to quote them but it is just a good practice. I mean something like https://mathiasbynens.be/notes/unquoted-font-family

**Comment by Blakelist7** [comment]
@alattalatta I guess we can close this issue now.

**Comment by alattalatta** [comment]
Sure, thanks. 😉
