### ISSUE TITLE
Issue with "WindowOrWorkerGlobalScope.setTimeout()": Broken section link

### ISSUE THREAD

**Issue by andyewen** [mdn/content#4971]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout

#### What information was incorrect, unhelpful, or incomplete?
Link to section "Reasons for delays longer than specified" not working.

#### Specific section or headline?
The broken link is in the description of the `delay` parameter.

#### What did you expect to see?
I expected to be directed to the "Reasons for delays longer than specified" section when I clicked the link.

#### Did you test this? If so, how?
I tested by clicking the link and it did not direct me to the section.

The problem seems to be caused by the broken link using the wrong ID. It has `href="#reasons_for_delays_longer_than_specified"` whereas the section's ID is `reasons_for_delays`. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/windoworworkerglobalscope/settimeout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/windoworworkerglobalscope/settimeout/index.html
* Last commit: https://github.com/mdn/content/commit/6cb0898a65756b28a86e46cfaaec1df6192dd4e8
* Document last modified: 2021-04-12T10:23:26.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! Yes, that looks right. But this section is terribly out of date and could use a rewrite.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/pull/4981/
