### ISSUE TITLE
Issue with "padding": (short summary here please)

### ISSUE THREAD

**Issue by HaichH** [mdn/content#4975]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/padding

#### What information was incorrect, unhelpful, or incomplete?
![image](https://user-images.githubusercontent.com/36187109/118183938-0121e200-b43b-11eb-9f73-ba6677e996ce.png)

#### Specific section or headline?
Constituent properties

#### What did you expect to see?
padding-top
padding-right
padding-bottom
padding-left

#### Did you test this? If so, how?
Codecademy and w3schools provide different answers, I also tested it on chrome 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/padding`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/padding
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/padding/index.html
* Last commit: https://github.com/mdn/content/commit/775066d2fc8d1561d5da61983d137c1297899315
* Document last modified: 2021-05-08T09:57:47.000Z

</details>

**Comment by wbamberg** [comment]
This is intentional - the order given for lists of "Constituent properties" is always alphabetical, for all longhand properties.
