### ISSUE TITLE
Issue with "Django Tutorial Part 8: User authentication and pe…": (short summary here please)

### ISSUE THREAD

**Issue by calvh** [mdn/content#4978]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication

#### What information was incorrect, unhelpful, or incomplete?
Instructions say to add the line in bold but in the code block no lines are in bold.

#### Specific section or headline?
Add the list to the sidebar

#### What did you expect to see?
A bold line in the code block

#### Did you test this? If so, how?
n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/authentication`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/authentication/index.html
* Last commit: https://github.com/mdn/content/commit/f100082a531f3eefd8e23c2eb30587388f34306d
* Document last modified: 2021-03-23T09:20:39.000Z

</details>

**Comment by hamishwillee** [comment]
Yeah, sorry about that. The toolchain got updated since I wrote this, and now bold no longer renders in code blocks. I'll fix up.
