### ISSUE TITLE
Issue with "<details>: The Details disclosure element": (short summary here please)

### ISSUE THREAD

**Issue by tanvirhasan7959** [mdn/content#4989]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/details`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/details/index.html
* Last commit: https://github.com/mdn/content/commit/1f2db9f0a46b99c254476b5f9445a74b98a6fa30
* Document last modified: 2021-03-27T00:17:29.000Z

</details>

**Comment by rachelandrew** [comment]
@tanvirhasan7959 what issue are you seeing with this page?

**Comment by sideshowbarker** [comment]
Closing for lack of response.
