### ISSUE TITLE
HTML5 Developer Guide is outdated, maybe needs a different approach

### ISSUE THREAD

**Issue by rachelandrew** [mdn/content#4992]
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5

I fixed a broken link on this page earlier which caused me to look at it, I removed a couple of very outdated things, but it seems to attempt to be a list of all things HTML5 and at this point, isn't doing a great job. In particular the stuff around APIs and CSS needs looking at.

Do we even need a special guide to HTML5 as a separate entity? I could have a bash at rewriting it but I'd be interested in other thoughts.

**Comment by Andrew-Cottrell** [comment]
In my opinion, given [W3C HTML 5.3](https://www.w3.org/TR/html53/) has been retired and current HTML is unversioned and defined by a _living standard_, it does seem a good time to remove the focus on HTML5 as a separate entity; irrespective of

> [the term "HTML5" is widely used as a buzzword to refer to modern web technologies](https://html.spec.whatwg.org/multipage/introduction.html#is-this-html5?)

**Comment by rachelandrew** [comment]
that was kind of my thinking, but would be good to get a few opinions in case anyone has an alternate view.

**Comment by wbamberg** [comment]
I saw https://github.com/mdn/content/issues/4942 and also though that this page is not very useful. My suggestion was just to make it a redirect to https://developer.mozilla.org/en-US/docs/Web/HTML.

Our top-level pages are quite disorganized and out of date in general, it would be worth having a project to try to improve them.

**Comment by rachelandrew** [comment]
Thinking about this some more, I think what I might do is:

- update the glossary page (https://developer.mozilla.org/en-US/docs/Glossary/HTML5) so it is a bit more of an explanation of what HTML5 actually is, brief explanation of what was new and the fact that it is now just HTML.
- remove the Guide to HTML5 https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5 redirect to the glossary page
- also remove this: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Introduction_to_HTML5

There is also https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/HTML5_Parser which doesn't seem all that useful now, anyone have opinions?

cc: @chrisdavidmills

**Comment by chrisdavidmills** [comment]
@rachelandrew I think this is a fine plan. Pretty much all of the "HTML5-specific" type stuff like doctype, specifying charset, etc. is covered in my [beginner's HTML stuff](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML), so you could link there if you felt like you needed to offer some kind of explanation of HTML basics after saying that HTML5 is just HTML these days, etc.

The HTML5 parser stuff doesn't seem that useful, you are right — very out of date information. Yeah, just get rid of it.

**Comment by rachelandrew** [comment]
cool, I shall get on with that. Doing a search on HTML5 in the docs brings back various places that could probably do with a small copy update to make sure we aren't giving people the impression they need to choose a flavor of HTML so I might do a bit of a trawl round of those too.

**Comment by sideshowbarker** [comment]
> There is also [developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/HTML5_Parser](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/HTML5_Parser) which doesn't seem all that useful now, anyone have opinions?

There is (was) actually some useful information for developers in that about the behavior of HTML parsers in browsers — in particular, the information about parsing SVG.

So maybe we can find a new place for that parser info — salvage the content from the repo history, and move it into some other existing article. But I’m not sure what article would be most appropriate as a place for its new life.

**Comment by sideshowbarker** [comment]
https://web.archive.org/web/20201211073827/https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/HTML5_Parser#Inline_SVG_and_MathML_support a link to the specific content I had in mind.

That has some useful info for developers, such as:

> * The DOM methods and CSS selectors behave case-sensitively, so you need to write your DOM calls and CSS selectors using the canonical case, which is camelCase for various parts of SVG such as viewBox.
>
> * The syntax `<foo/>` opens and immediately closes the foo element if it is a MathML or SVG element (i.e. not an HTML element)
> 
> * To deal with legacy pages where authors have pasted partial SVG fragments into HTML (who knows why) or used a `<math>` tag for non-MathML purposes, attempts to nest various common HTML elements as children of SVG elements (without foreignObject) will immediately break out of SVG or MathML context. This may make some typos have surprising effects.
> 
> etc.
