### ISSUE TITLE
Issue with "Express Tutorial Part 3: Using a Database (with Mo…": (short summary here please)

### ISSUE THREAD

**Issue by SatpreetMakhija** [mdn/content#4996]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

#### What information was incorrect, unhelpful, or incomplete?
terminal command

#### Specific section or headline?
Testing -- Create some items

#### What did you expect to see?
node populatedb <URL>
(but the URL needs to be inside quotations '<URL> '

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.html
* Last commit: https://github.com/mdn/content/commit/3af43c1dcfb9be19c73cf3fdd1178db9c74aa064
* Document last modified: 2021-04-27T01:03:07.000Z

</details>

**Comment by hamishwillee** [comment]
Actually that fails on Windows, while no quotes or double quotes work. I have simply stated in https://github.com/mdn/content/pull/5043 that this may be OS dependent.

Thanks for posting.
