### ISSUE TITLE
Broken mailing list link

### ISSUE THREAD

**Issue by tobeytozier** [mdn/content#4999]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility

#### What information was incorrect, unhelpful, or incomplete?
Mozilla mailing list about accessibility broken link

#### Specific section or headline?
"See also" section

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/index.html
* Last commit: https://github.com/mdn/content/commit/2d48835e97e7d226431f2be1a74558117fb44d0e
* Document last modified: 2021-02-03T18:43:39.000Z

</details>

**Comment by timohaver** [comment]
The broken link is https://lists.mozilla.org/listinfo/accessibility. Likewise, I also get a 404 error.

I checked from production desktop versions of mac FF and Brave browsers.

**Comment by chrisdavidmills** [comment]
Fixed by https://github.com/mdn/content/commit/8413a2acf8d13cc888483ee740b42c4f4307e6b1

Thanks for reporting!
