### ISSUE TITLE
Issue with "Array.prototype.push()": (short summary here please)

### ISSUE THREAD

**Issue by zachvictor** [mdn/content#5000]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push

#### What information was incorrect, unhelpful, or incomplete?
It seems incomplete or perhaps idiosyncratic to offer `Array.prototype.push.apply()` as a way to merge arrays without first giving an example of `push()` with destructuring assignment: `oneArray.push(...anotherArray)` 

#### Specific section or headline?
Merging two arrays using apply()

#### What did you expect to see?
`vegetables.push(...moreVegs)`

#### Did you test this? If so, how?
JavaScript console

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/push`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/push/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by wbamberg** [comment]
Or even [`concat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)?

I agree with you. Probably this section predates destructuring assignment and concat(). It would be good to update it.

**Comment by jadjoubran** [comment]
Happy to take this one!
My suggestion would be to rewrite it with `.push(...moreVegs)` and then add a quick mention to `concat()` as it's still used in some places, let me know if you have other thoughts

**Comment by wbamberg** [comment]
Thanks @jadjoubran ! I think your suggestion sounds perfect.

**Comment by jadjoubran** [comment]
Great! Can I get assigned please? Then I'll work on it soon
