### ISSUE TITLE
Issue with "Using Service Workers": Link to a removed section

### ISSUE THREAD

**Issue by alattalatta** [mdn/content#5004]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

#### What information was incorrect, unhelpful, or incomplete?

> **Note**: The Cache API is not supported in every browser. (See the [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#browser_compatibility) section for more information.)

The document no longer has browser compatibility section.

#### Specific section or headline?

[Install and activate: populating your cache](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#install_and_activate_populating_your_cache)'s first note block.

#### What did you expect to see?

The link and its text content should point to [`Cache`](https://developer.mozilla.org/en-US/docs/Web/API/Cache#browser_compatibility).

#### Did you test this? If so, how?

No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/service_worker_api/using_service_workers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/service_worker_api/using_service_workers/index.html
* Last commit: https://github.com/mdn/content/commit/c25f077c2c7115226143faf57f1d45c3c7fa765d
* Document last modified: 2021-04-16T05:33:19.000Z

</details>

**Comment by wbamberg** [comment]
I think we should remove this note entirely. `cache` is supported in all modern browsers and has been for years: https://developer.mozilla.org/en-US/docs/Web/API/Cache#browser_compatibility. There's always an implicit need for developers to check BCD, but there's no particular reason to highlight it here any more.
