### ISSUE TITLE
Issue with "XMLHttpRequest: load event": (short summary here please)

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#5010]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/load_event

#### What information was incorrect, unhelpful, or incomplete?
The live example appears to not be working.  The first two buttons show the same result:
_loadstart: 0 bytes transferred
error: 0 bytes transferred
loadend: 0 bytes transferred_

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/load_event#live_example

#### What did you expect to see?
clicking the buttons would illustrate the stated functionality

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/xmlhttprequest/load_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/load_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/xmlhttprequest/load_event/index.html
* Last commit: https://github.com/mdn/content/commit/9917bf17a97973166bb3cb3812a496e4117a778f
* Document last modified: 2021-01-11T13:30:57.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing!

CORS error, quelle surprise:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mdn.mozillademos.org/files/16553/DgsZYJNXcAIPwzy.jpg. (Reason: CORS header “Access-Control-Allow-Origin” missing).

@peterbe , help!

**Comment by peterbe** [comment]
Did it go away?

**Comment by wbamberg** [comment]
No, does it work for you on https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/load_event#live_example ?

**Comment by peterbe** [comment]
Ah! These errors. 
<img width="1505" alt="Screen Shot 2021-05-18 at 3 15 11 PM" src="https://user-images.githubusercontent.com/26739/118710101-d8f40380-b7eb-11eb-94c1-ec038b4d046e.png">

I'll need to familiarize myself with the example and what it's trying to show but I wonder if the quick fix is to change from:
```diff
xhrButtonSuccess.addEventListener('click', () => {
-   runXHR('https://mdn.mozillademos.org/files/16553/DgsZYJNXcAIPwzy.jpg');
+   runXHR('DgsZYJNXcAIPwzy.jpg');
});
```
But I can't even test that until we resolve https://github.com/mdn/yari/pull/3798 which is currently blocked on GitHub Actions being down :(

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/5897 with a fix.
