### ISSUE TITLE
Replace `<sup>` and `<sub>` where we can

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#5012]
Markdown doesn't provide a syntax for the `<sup>` and `<sub>` elements. In https://github.com/mdn/content/issues/4578 we decided that we would use HTML for these elements when we have to, and replace them with something equivalent where we can.

The "something equivalent" includes:

* use caret "^" for exponentiation
* use words like "first" instead of 1<sup>st</sup>
* don't mark up footnotes with `<sup>`

See https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#superscript_and_subscript.

This bug is to give us a place where we can remove the use of these elements where we can.

**Comment by sideshowbarker** [comment]
@wbamberg Closing this, as it seems we have this resolved. But of course feel free to reopen if I’m wrong

**Comment by wbamberg** [comment]
I think we are good :).
