### ISSUE TITLE
Issue with "Cache-Control": (short summary here please)

### ISSUE THREAD

**Issue by ade-owasp-sf** [mdn/content#5014]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

#### What information was incorrect, unhelpful, or incomplete?
I keep seeing in other authors' description and explanation the if you do not desire cache at all you should use

cache-control: no-cache, no-store

But your post says it should be

cache-control: no-store

And that except for max-age=0 (to invalidate existing cache, if any), any other directive used with no-store is not effective. 
#### Specific section or headline?
cache-control

#### What did you expect to see?
More visible discussion on whether or not other browsers might interpret  cache-control: no-cache, no-store  differently cache-control:  no-store

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/cache-control`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/cache-control/index.html
* Last commit: https://github.com/mdn/content/commit/8d4fd702d9668604cb2788da5bd9fc9b796ec30a
* Document last modified: 2021-03-17T20:27:56.000Z

</details>

**Comment by hamishwillee** [comment]
@ade-owasp-sf IMO this is not a reasonable bug report/issu.

Generally I think there is a lot of miss-understanding on how the directives work in the broader internet.

The document is clear on what is good with respect to ensuring a request is not cached (`cache: no-store`) and what each of the others do. If you use no-store then you're saying "don't store me in any cache". That will override "no-cache", which says "you can cache me wherever you like but you have to revalidate". There is no ambiguity here on what the docs says. 

Note that the intent of no-store is to make sure that sensitive information is not held in a cache. If you just want to make sure that you don't serve old information from a cache then you'd use no-cache, or `max-age=0` to force revalidation. 

We capture compatibility issues in the browser compatibility section. As nothing is mentioned with respect to these directives you can generally assume there is no known difference in browser behaviour.  If you found one you would report it in https://github.com/mdn/browser-compat-data

**Comment by ade-owasp-sf** [comment]
@hamishwillee Thank you for your clarification.  I have since found the base RFCs.  The MDN doc and your clarification align with the RFCs.

**Comment by hamishwillee** [comment]
Thanks very much for letting me know. I'll close this.
