### ISSUE TITLE
recording_a_media_element: video source

### ISSUE THREAD

**Issue by sonichy** [mdn/content#5015]
Click Start: NotFoundError: Requested device not found.
I want to give a src to left video, right video to record.

**Comment by Rumyra** [comment]
Hi @sonichy can you provide a url as to what page you are referring to and which section? Thank you!

**Comment by sonichy** [comment]
https://vd4.bdstatic.com/mda-mee64b27fwbhjs19/1080p/cae_h264/1621052542047291065/mda-mee64b27fwbhjs19.mp4?v_from_s=nj_haokan_4469&auth_key=1621056576-0-0-579e1f7ef4d11c1500d6d633677f9234&bcevod_channel=searchbox_feed&pd=1&pt=3&abtest=3000165_1

**Comment by Rumyra** [comment]
@sonichy from what I can gather you are looking for some help with some code you have written.

These issues are for content on MDN pages and as such I will close this issue.

If you need code help Slack Overflow might be worth trying or if you would like your code assessed you can ask on https://discourse.mozilla.org/c/mdn/learn/
