### ISSUE TITLE
Issue with "<area>": No need to mention HTML 5.3 anymore

### ISSUE THREAD

**Issue by alattalatta** [mdn/content#5016]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area

#### What information was incorrect, unhelpful, or incomplete?

The `type` attribute is described as:

> The W3C 5.3 fork of the HTML specification defines it as valid, but the canonical HTML specification doesn’t, and it has no effect in any user agents.

But since the WHATWG HTML spec (please correct me if I'm wrong) "won", it would be cleaner to remove the _canonical_ and _fork_ thing altogether.

#### Specific section or headline?

[Deprecated attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area#deprecated_attributes) > `type`

#### What did you expect to see?

Something like:

> Used to provide hint for the type of the referenced resource.

#### Did you test this? If so, how?

No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/area`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/area/index.html
* Last commit: https://github.com/mdn/content/commit/3f0471fdb1eed37a87b42cc16b8ed0e2ea096362
* Document last modified: 2021-04-15T07:24:51.000Z

</details>

**Comment by rachelandrew** [comment]
I'd agree, the useful information is that it doesn't do anything so could be safely removed if someone were to find it in their code. I've made a PR to fix. Thanks :)
