### ISSUE TITLE
Issue with "<audio>: The Embed Audio element": currentTime and duration are not attributes

### ISSUE THREAD

**Issue by alattalatta** [mdn/content#5019]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

#### What information was incorrect, unhelpful, or incomplete?

`currentTime` and `duration` are properties of `HTMLMediaElement`, but they are not content attributes of `<audio>`. Read-only attribute is weird, too.

#### Specific section or headline?

[Attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#attributes)

#### What did you expect to see?

Those two shouldn't be listed under Attributes section.

#### Did you test this? If so, how?

Checkinig HTML spec and writing `<audio currenttime="60">`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/audio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/audio/index.html
* Last commit: https://github.com/mdn/content/commit/6d8ec4b6c9cc4ecf3aebbd3d8fddafd5e979a4f7
* Document last modified: 2021-03-30T06:04:59.000Z

</details>

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/pull/5020 .
