### ISSUE TITLE
Issue with "RegExp.prototype.exec()": Why "d" flag is not working and gives "SyntaxError"

### ISSUE THREAD

**Issue by decpk** [mdn/content#5021]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec

#### What information was incorrect, unhelpful, or incomplete?
While using the **"d"** flag I got "**SyntaxError: Invalid regular expression flag**". But I've read everywhere there is no **"d"** flag in JS regex. 

#### Specific section or headline?
[return Value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec#return_value)
[Description Example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec#description)

#### What did you expect to see?
As per the exec() method there should be "d" flag and it should return "indices".

#### Did you test this? If so, how?
I've compiled the example as shown in the [Description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec#description) but It didn't execute and gives Syntax error.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/regexp/exec`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/regexp/exec/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by wbamberg** [comment]
Which browser and browser version did you see this with? The example:

```js
let re = /quick\s(brown).+?(jumps)/igd;
let result = re.exec('The Quick Brown Fox Jumps Over The Lazy Dog');
```

...works fine for me in the consoles of Firefox 88 and Chrome 90. 

I can't find good compat data for regex flags unfortunately, but the page for the corresponding property suggests that this is quite new: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/hasIndices#browser_compatibility .

It would be good if https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/RegExp#browser_compatibility had this kind of detail.

**Comment by decpk** [comment]
I'm running it into [RunJS](https://runjs.app/) and indeed it is working on all modern browser but didn't tested on old browsers. I was also checking from the [javascript.info](https://javascript.info/regexp-introduction) website. Yeah it could be possible that "d" flag is new to JS and the site it not yet updated.
