### ISSUE TITLE
Issue with "Using custom elements": (Example code fails. HTML attributes not available in constructor method.)

### ISSUE THREAD

**Issue by Neil-Haskins** [mdn/content#5022]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

#### What information was incorrect, unhelpful, or incomplete?

Before a code example it says:

> Inside the constructor, we define all the functionality the element will have when an instance of it is instantiated...

Then inside the code example we have two relevant lines

```
img.src = this.hasAttribute('img') ? this.getAttribute('img') : 'img/default.png';
```

and

```
info.textContent = this.getAttribute('data-text');
```

Using `console.log` `hasAttribute` returns false, and `getAttribute` returns null, even though the attributes are there in the HTML.

```
<popup-info img="assets/mine.png" data-text="Here is some text for the first pop up"></popup-info>
```

[This answer on StackOverflow](https://stackoverflow.com/a/42720702/1339426) suggests the reason is that html elements may not yet be available when the constructor method is called.

Moving all code after `super();` from the `constructor()` method to a `connectedCallback()` method resolved the issue for me, and the page functioned as expected.

#### Specific section or headline?

[Autonomous custom elements](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#autonomous_custom_elements)

#### What did you expect to see?

I had expected to see the custom element load with the image and text I defined in the HTML.

Instead it had the default image defined in the JavaScript, and no text.

#### Did you test this? If so, how?
```
console.log("Is an img attribute = " + this.hasAttribute('img'));
console.log("Img attribute = " + this.getAttribute('img'));
console.log(this);
```

`hasAttribute` returns false, and `getAttribute` returns null, even though the attributes are there in my HTML, and in the console using `console.log(this);`

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/web_components/using_custom_elements/index.html
* Last commit: https://github.com/mdn/content/commit/be073221bcccdab51cb726601f4368e5ed0cd72f
* Document last modified: 2021-05-13T00:31:19.000Z

</details>

**Comment by estelle** [comment]
fixed in https://github.com/mdn/content/pull/19035

**Comment by foobarbecue** [comment]
Presumably the problem here was that you didn't use `defer` the way the example does:

https://github.com/mdn/web-components-examples/blob/b33e344e2fdec2abd252ffd74f0b1677c4a7cbbf/popup-info-box-web-component/index.html#L6
