### ISSUE TITLE
Issue with "Firefox OS": Dead Firefox OS area link

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#5024]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Firefox_OS

#### What information was incorrect, unhelpful, or incomplete?

The Firefox OS area is dead.

#### Specific section or headline?

Technical reference

#### What did you expect to see?

A link into the archive?

#### Did you test this? If so, how?

I clicked the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/firefox_os`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Firefox_OS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/firefox_os/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by Ryuno-Ki** [comment]
https://github.com/mdn/content/blob/9f17495b3ebceb458aba1f8e0d38e76d271cc517/files/en-us/glossary/firefox_os/index.html#L25

is the line to update.

**Comment by Blakelist7** [comment]
@Ryuno-Ki could you please verify where it should route to?

**Comment by Ryuno-Ki** [comment]
I would assume, https://developer.mozilla.org/en-US/docs/Archive/B2G_OS is the right target.

The respective content can be found in https://github.com/mdn/archived-content/tree/main/files/en-us/archive/b2g_os

**Comment by Blakelist7** [comment]
@Ryuno-Ki changing `<a href="/en-US/Firefox_OS">` to `<a href="/en-US/docs/Archive/B2G_OS">` would do the work?

**Comment by Ryuno-Ki** [comment]
Hey @Blakelist7,

since the archive is not part of the repo, I'd assume, that locally and in CI the link appears to be broken.
However, since I showed you the production URL, it should be fine there.

Let me take a look at your PR.
