### ISSUE TITLE
Issue with "Solve common problems in your JavaScript code": add a page on how to find the value of a text input field using Javascript

### ISSUE THREAD

**Issue by RPIERIS** [mdn/content#5030]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Howto

#### What information was incorrect, unhelpful, or incomplete?
Suggesting an improvement for this section.
Is it possible to add a page on how to [find the value of a text input field using Javascript](https://www.w3docs.com/snippets/javascript/how-to-get-the-value-of-text-input-field-using-javascript.html) as in this w3 schools how to section. I think it quite a basic action. I was looking through MDN and couldnt find anything that explained this. Maybe I am at fault.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/howto`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Howto
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/howto/index.html
* Last commit: https://github.com/mdn/content/commit/ec2b6064788da26d520a8256d0e05a7875b50f78
* Document last modified: 2021-01-27T07:12:04.000Z

</details>

**Comment by Josh-Cena** [comment]
This issue has been around for two years with no additional feedback, so I think it's best that we close it. Note that the "how to" section is by no means meant to be a dump of all frequently asked questions of JS: rather, it's an overview of the JS learning area, structured as a bunch of questions. It's also not scalable for educational materials to cover every use case—rather, you should learn the concepts and methodology and find answers to your own questions independently.
