### ISSUE TITLE
Issue with "TypedArray.prototype.slice()": ("shallow copy" is misleading or confusing)

### ISSUE THREAD

**Issue by PetaSoft** [mdn/content#5035]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice

#### What information was incorrect, unhelpful, or incomplete?
You write for TypedArray.prototype.slice: "It returns a shallow copy of elements from the original typed array."

#### Specific section or headline?
[Description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice#description "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice#description")

#### What did you expect to see?
"shallow copy" is always true for TypedArrays, as TypedArrays do not store any objects, and in particular no subarrays. Therefore, "shallow copy" is misleading or confusing. Maybe You should write something like: "As TypedArrays only store primitive values, the copy is always a shallow copy of elements from the original typed array."

#### Did you test this? If so, how?
const numbers = new Uint8Array([1, 4, 9])
numbers[1] = [34, 45]  // => Uint8Array(3) [1, 0, 9]
numbers[1] = [34]  // => Uint8Array(3) [1, 34, 9]

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/typedarray/slice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/typedarray/slice/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by hamishwillee** [comment]
FWIW I don't the old wording confusing or misleading - it is strictly true.

**Comment by PetaSoft** [comment]
@hamishwillee The problem is not that the old wording is true or wrong, but it implicitly lets the reader suppose that there may also exist non shallow copies of the elements because the fact that it returns a shallow copy is explicitly emphasized. Why say that it is a shallow copy when it is always a shallow copy and cannot be anything else? I was confused by the wording, and the first thing I did, was to test whether I can store anything else other than primitive values as elements of a TypedArray though I was strictly conviinced that I cannot do that. You also have to take into account that for "normal" arrays there can exist non shallow copies, and there it is important to distinguish between shallow and non shallow copies.
I suppose that the current wording was copied from the "normal" array case without making modifications which reflect the special nature of typed arrays. I found similar cases for other methods of typed arrays, e.g. in the [description of the TypedArray.prototype.filter() method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/filter#description). There is written _"callbackFn is invoked only for indexes of the typed array which have assigned values; it is not invoked for indexes which have been deleted or which have never been assigned values."_ Of course, this statement ist true, but for typed arrays there do not exist indexes which have not an assigned value, and there do not exist indexes which have been deleted. The citied sentence makes sense for "normal" arrays as there holes, unassigned and deleted indexes can exist.

**Comment by hamishwillee** [comment]
Thanks @PetaSoft 
I disagree that it is a useful distinction to make. But I'm not expert enough in JavaScript to assess whether your concerns would be considered fair by most readers. Someone else with more experience should review this. 

@chrisdavidmills ?

**Comment by Elchi3** [comment]
> I suppose that the current wording was copied from the "normal" array case without making modifications which reflect the special nature of typed arrays.

As the original author of these pages I can confess: Yes, I copied from the array pages to create the typed array pages :-)

So far I wasn't thinking that the wording would hurt anyone. I think you are right that "shallow copies" or "assigned values" don't matter for typed arrays. These descriptions are mostly the same because that way people can be assured that the Array and TypedArray API are always the same thing basically, so no one needs to learn two different `slice` methods, for example.

The differences you point out might be worth to clear up, though.

**Comment by sideshowbarker** [comment]
I’ve opened https://github.com/mdn/content/pull/5978 with an update to the wording.
