### ISSUE TITLE
Issue with "Object.defineProperty()": (Clarity needed if configurable is true or false when extracting the meaning of this sentense)

### ISSUE THREAD

**Issue by Walluri** [mdn/content#5039]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

#### What information was incorrect, unhelpful, or incomplete?
Incomplete : For data properties, it is possible to modify the value if the property is writable, and it is possible to change writable attribute from true to false. 

#### Specific section or headline?
Sub section : Modifying a property

#### What did you expect to see?
For data properties which are configurable, it is possible to modify the value if the property is writable, and it is possible to change writable attribute from true to false. 

#### Did you test this? If so, how?
lexical error. The previous sentence implies that this line by default has configurable as true.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/defineproperty`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/defineproperty/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5977 with fix
