### ISSUE TITLE
Issue with "<meta>: The metadata element": (short summary here please)

### ISSUE THREAD

**Issue by thehatredthing** [mdn/content#5047]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

#### What information was incorrect, unhelpful, or incomplete?
"charset = This attribute declares the document's character encoding. If the attribute is present, its value must be an ASCII case-insensitive match for the string "utf-8", because UTF-8 is the only valid encoding for HTML5 documents."
And after that, the "http-equiv has the same restrictions as charset attribute".
I am not sure about it, but W3C just encourages the use of UTF-8. I read for example a newspaper which starts by "DOCTYPE html" thus is Html5, and declares http-equiv="Content-Type" content="text/html; charset=iso-8859-15. Chrome reads it perfect. The only doubt is if Chrome detects it in the mime type, when I try to do a request, I get a mimetype of only "text/html". But the thing of W3C just encourages it still should stand.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/meta`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/meta/index.html
* Last commit: https://github.com/mdn/content/commit/c40f133b4ed8474730029e68a397aaebb042266b
* Document last modified: 2021-03-01T15:30:53.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
It's probably for the best that MDN content reflects the requirement stated by the [HTML standard](https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-charset)

> The `charset` attribute specifies the character encoding used by the document. This is a character encoding declaration. If the attribute is present, its value must be an ASCII case-insensitive match for the string `"utf-8"`.

The retired [HTML 5.3 W3C Working Group Note](https://www.w3.org/TR/html53/document-metadata.html#character-encoding-declaration) has

> The only acceptable character encoding declaration for the modern web is UTF-8.
> This must be identified by the character encoding label’s value being an ASCII case-insensitive match for the string `"utf-8"`.

The `<meta>` [page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset) could note that browsers _may_ support legacy encodings with `<!DOCTYPE html>` documents, such as `"iso-8859-1"`, and also that this should not be relied upon.

**Comment by thehatredthing** [comment]
Ok, as you wish, thanks and nothing else for my part.

**Comment by rachelandrew** [comment]
I think the content we have is accurate, and I'd rather not infer that anything else might work. Closing unless anyone feels strongly I should edit something in.
