### ISSUE TITLE
Issue with "Command line crash course": grammatical error

### ISSUE THREAD

**Issue by Metafyzik** [mdn/content#5051]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line

#### What information was incorrect, unhelpful, or incomplete?
Sentence should start with capital letter.

#### Specific section or headline?
The start of the second sentence of the second paragraph under headline "Where did the terminal come from?"

#### What did you expect to see?
Capital letter. ( ".It" instead of ".it")

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/command_line`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/command_line/index.html
* Last commit: https://github.com/mdn/content/commit/3af43c1dcfb9be19c73cf3fdd1178db9c74aa064
* Document last modified: 2021-04-27T01:03:07.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @Metafyzik 

FYI, you can easily fix this kind of error yourself in github. There is a link to the source for the page at the bottom of every page:
![image](https://user-images.githubusercontent.com/5368500/118571057-a680e100-b7c0-11eb-9e54-a019750e8bfb.png)
