### ISSUE TITLE
Issue with "JavaScript/XSLT Bindings": example doesn't work

### ISSUE THREAD

**Issue by chchch** [mdn/content#5054]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/XSLT/XSLT_JS_interface_in_Gecko/JavaScript_XSLT_Bindings

#### What information was incorrect, unhelpful, or incomplete?

This example doesn't work, because XMLHttpRequest doesn't recognize the *.xsl extension as an XML file.

#### Specific section or headline?

Figure 1 : Instantiating an XSLTProcessor

#### What did you expect to see?

Possible solutions:
* use an asyncronous XMLHttpRequest, and specify the responseType as 'document'
* get responseText instead of responseXML, and then parse it with DOMParser()
* use the Fetch API, and parse with DOMParser()

#### Did you test this? If so, how?

Yes.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/xslt/xslt_js_interface_in_gecko/javascript_xslt_bindings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/XSLT/XSLT_JS_interface_in_Gecko/JavaScript_XSLT_Bindings
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/xslt/xslt_js_interface_in_gecko/javascript_xslt_bindings/index.html
* Last commit: https://github.com/mdn/content/commit/9427de4a1db1415b73ccc537eb067b850db7cd33
* Document last modified: 2020-12-17T11:19:43.000Z

</details>

**Comment by sideshowbarker** [comment]
> This example doesn't work, because XMLHttpRequest doesn't recognize the *.xsl extension as an XML file.

As far as I can see, that’s not a problem with the example code but would instead be a problem with the server from which the `example.xsl` file is served. Whatever server that `example.xsl` file is served from needs to be configured to serve `.xsl` files with a proper XML MIME type, per https://mimesniff.spec.whatwg.org/#xml-mime-type.

If the `example.xsl` file is served with an XML MIME type, then browsers will recognize it as an XML file, and the example will work.
