### ISSUE TITLE
We should decide on a label where admin's merge is required?

### ISSUE THREAD

**Issue by vkWeb** [mdn/content#506]
There have been a lot of PRs that have touched many codeowners' files. I believe (not 100% sure) each team needs to approve to get the PR greenlight which is practically not possible. Some discussions on this led to the decision that admins will merge those PRs once one or two reviewers approve.

I was thinking that we should decide on a label that we can put on PRs that are ready to merge but needs admin's power...? It will make it easy for admins to sort the PRs with that label. I propse a label on the lines: `admin merge required`.

Example: https://github.com/mdn/content/pull/450.  

PS: any thoughts on using help-wanted labels on issues to attract some more outside contribution?

cc @chrisdavidmills @peterbe @sideshowbarker.

**Comment by chrisdavidmills** [comment]
Good idea @vkWeb. I'm happy with `admin merge required` if everyone else is.

**Comment by sideshowbarker** [comment]
> Good idea @vkWeb. I'm happy with `admin merge required` if everyone else is.

Works for me (and thanks @vkWeb for taking time to propose it)

**Comment by chrisdavidmills** [comment]
Cool, I've got a second, and the label has been made, so let's close this. Thanks folks!

**Comment by peterbe** [comment]
Now we just need to learn to remember it :)

**Comment by vkWeb** [comment]
@peterbe yeah :laughing:

**Comment by vkWeb** [comment]
Btw, thanks everyone for agreeing on this! :tada:
