### ISSUE TITLE
Issue with "Data URLs": bang should also be escaped

### ISSUE THREAD

**Issue by akimd** [mdn/content#5060]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

#### What information was incorrect, unhelpful, or incomplete?

Hi,

This page states:

> If the data contains characters defined in RFC 3986 as reserved characters, or contains space characters, newline characters, or other non-printing characters, those characters must be percent-encoded (aka “URL-encoded”).

and later gives an example:

> `data:,Hello%2C%20World!`
> The text/plain data Hello, World!. Note how the comma is percent-encoded as %2C, and the space character as %20.

But [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) states:

```
      reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

So it is my reading that `!` should also be encoded, as `%21` fwiw.

#### Specific section or headline?

Section "Syntax"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/basics_of_http/data_uris`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/data_uris/index.html
* Last commit: https://github.com/mdn/content/commit/48fca0c614add538e95f1075b2777fc396023d31
* Document last modified: 2021-03-16T07:50:01.000Z

</details>

**Comment by teoli2003** [comment]
Hi, @akimd !

Thanks a lot! Good catch!

I double checked with https://www.urlencoder.org/ and fixed both occurences in the PR!
