### ISSUE TITLE
Content bug: `URLSearchParams` should use `.prototype.` notation

### ISSUE THREAD

**Issue by DerekNonGeneric** [mdn/content#5063]
## What page(s) did you find the problem on?

**Include the URL or URLs where you found the problem.**

- https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

## Specific page section or heading?

&ldquo;URLSearchParams&rdquo;

## What is the problem?

Should be `.prototype` if these are instance methods.

## What did you expect to see?

`URLSearchParams` `.prototype` *instance method*

## Did you test this? If so, how?

Nope, I have taken the word of @mathiasbynens (he is probably busy atm, so here is the bug report).

**Comment by mathiasbynens** [comment]
Writing `URLSearchParams.append` strongly suggests it's a static method (like e.g. `Array.isArray`), when in reality it's a prototype method:

```
URLSearchParams.append;
// → undefined
URLSearchParams.prototype.append;
// → ƒ append() { [native code] }
```

To resolve this confusion, I'd suggest using the `URLSearchParams.prototype.append` notation for prototype methods. If you need a shorthand, you could consider [the `#` notation i.e. `URLSearchParams#append`](https://mathiasbynens.be/notes/javascript-prototype-notation) which at least has the benefit of not being valid JavaScript syntax, making it more obvious that a shorthand is being used. But IMHO the best solution is just to use the complete `.prototype.` notation.

Note that `URLSearchParams.prototype.append` is just one particular example — MDN uses the wrong notation on many other pages.

**Comment by Elchi3** [comment]
Thanks for this issue.
Have a look at https://discourse.mozilla.org/t/incorrect-titles-for-method-property-articles/31641 for some more thoughts on this topic :)

**Comment by mathiasbynens** [comment]
@Elchi3 Thanks for the pointer. What's the current status? The discourse thread hasn't received updates in a few years, and it looks like the originally reported issue is still present ([except for the ECMAScript language features](https://discourse.mozilla.org/t/incorrect-titles-for-method-property-articles/31641/21), which you’ve carefully titled correctly — thank you!).

**Comment by DerekNonGeneric** [comment]
Updated the title of this issue. This page can be a good starting point for how we differentiate instance methods and static methods. Maybe divide the section in two parts each w/ separate subheading.

**Comment by DerekNonGeneric** [comment]
Updated the title of this issue. This page may be a good starting point for how we differentiate instance methods and static methods.

Perhaps dividing the section into two parts (each w/ separate subheading) would make a clear distinction.

After testing this on Firefox, it appears that none of these methods are static.
