### ISSUE TITLE
Issue with "Using files from web applications": (doesn't work with .tiff)

### ISSUE THREAD

**Issue by Amarantine84** [mdn/content#5069]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications

#### What information was incorrect, unhelpful, or incomplete?
Example doesn't work with .tiff files

#### Specific section or headline?
Example: Using object URLs to display images

#### What did you expect to see?
.tiff picture is displayed as well as .png, .jpg and others

#### Did you test this? If so, how?
Tried to upload .png first, then .tiff. Ok with .png, not ok with .tiff

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/file/using_files_from_web_applications`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/file/using_files_from_web_applications/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by chrisdavidmills** [comment]
Hi @Amarantine84 . To my knowledge, TIFF is not a suitable format for displaying images on the web, as it is heavy and contains a lot of information not needed for simple web dispay. I don't think any browsers support displaying TIFFs natively, although you could of course set a TIFF for download.

Have a look at https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#tiff_tagged_image_file_format for more information.
