### ISSUE TITLE
Improve xref macro explanations in commonly-used-macros document

### ISSUE THREAD

**Issue by escattone** [mdn/content#5070]
Thanks @escattone. FWIW I am really not sure about the name. But I do think we should add it to [list of commonly used macros](https://developer.mozilla.org/en-US/docs/MDN/Structures/Macros/Commonly-used_macros). 

It might be useful to generally add more docs - so we currently say "links to a path in the XXXX" but perhaps something like "cssxref links to a page in the CSS Reference (any page with a stub nested below Web/CSS/Reference).

_Originally posted by @hamishwillee in https://github.com/mdn/content/pull/4226#discussion_r632242487_

**Comment by hamishwillee** [comment]
Fixed in linked item. If there is more you think needs to be said, let me know :-)

**Comment by escattone** [comment]
Thank you @hamishwillee!
