### ISSUE TITLE
Issue with "IDBObjectStore.delete()": In the example sample, it uses a global db variable.

### ISSUE THREAD

**Issue by nathnolt** [mdn/content#5084]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/delete

#### What information was incorrect, unhelpful, or incomplete?
In the example  code sample, it uses a global db variable
```db = DBOpenRequest.result;```

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/delete#example
in the onsucces function ```DBOpenRequest.onsuccess = function(event) {```

#### What did you expect to see?
This should either become
```window.db =```

Or at the top under the ```var DBOpenRequest``` declaration, a ```var db``` line.

#### Did you test this? If so, how?

No, I just saw it.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/idbobjectstore/delete`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/delete
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/idbobjectstore/delete/index.html
* Last commit: https://github.com/mdn/content/commit/12024ee393c3fe3101b03903561c640444b38646
* Document last modified: 2021-04-08T14:57:07.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/5972 with a fix
