### ISSUE TITLE
Issue with "Function return values": (conditional test doesn't account for isNaN() coercion of empty strings to 0)

### ISSUE THREAD

**Issue by Tisbutascratchfile** [mdn/content#5086]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Return_values

#### What information was incorrect, unhelpful, or incomplete?

```
input.onchange = function() {
  const num = input.value;
  if (isNaN(num)) {
    para.textContent = 'You need to enter a number!';
  } else {
    para.textContent = num + ' squared is ' + squared(num) + '. ' +
                       num + ' cubed is ' + cubed(num) + '. ' +
                       num + ' factorial is ' + factorial(num) + '.';
  }
}
```
if `num = ''` or `num  = ' ' `
the anon function output is :  squared is 0. cubed is 0. factorial is 1.
#### Specific section or headline?
Active learning: our own return value function.
paragraph 3.

#### What did you expect to see?

'You need to enter a number!'

#### Did you test this? If so, how?

by passing empty strings and strings containing whitespace into the input.

----Suggested fix-------
```
input.onchange = function () {
        const num = input.value.trim();
        if (isNaN(num) || num == "") {...}
}

```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/return_values`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Return_values
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/return_values/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
This might be even better

```javascript
input.onchange = function () {
  const num = parseFloat(input.value);
  if (isNaN(num)) {...}
};
```

**Comment by Tisbutascratchfile** [comment]
I agree, your solution is more refined than what I've suggested and would need less explanation. 
Thank you.
