### ISSUE TITLE
Issue with "Using the aria-invalid attribute": Opening Hyperlink doesn't scroll down to the content specified in url anchor

### ISSUE THREAD

**Issue by NabeelKabeer** [mdn/content#5090]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_attribute

#### What information was incorrect, unhelpful, or incomplete?
Hyperlink provided in the page for `WAI Authoring Practices for forms` doesn't scroll down to the content section when it's opened
associated code :
https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-invalid_attribute/index.html#L132

#### Specific section or headline?
headline : `Additional resources`

#### What did you expect to see?
Either the section(`#ariaform`) was removed or might be pointing to a wrong anchor

#### Did you test this? If so, how?
Scroll down to the content section specified in the anchor tag
Either `#ariaform` achor tag doesn't exist in the hyperlinked page or might be pointing to wrong anchor

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/aria_techniques/using_the_aria-invalid_attribute`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_attribute
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-invalid_attribute/index.html
* Last commit: https://github.com/mdn/content/commit/dd7d777e06929826dbbe899084775092b15b0c7f
* Document last modified: 2021-04-17T10:45:42.000Z

</details>

**Comment by rachelandrew** [comment]
Thanks for the report @NabeelKabeer it looks like the spec has changed and the forms info is split into different sections. I think the document is a useful link however so I've just linked to the main document rather than any particular section in the linked PR.
