### ISSUE TITLE
Issue with "Element.scrollHeight": (short summary here please)

### ISSUE THREAD

**Issue by maiteeguren** [mdn/content#5101]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight

#### What information was incorrect, unhelpful, or incomplete?

The demo is not working. It doesn't reproduce the behaviour the article is explaining

#### Specific section or headline?

scrollHeight Demo

#### What did you expect to see?

The checkbox ticked after scrolling to the bottom of the text

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/scrollheight`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/scrollheight/index.html
* Last commit: https://github.com/mdn/content/commit/6c12f1de3e879c6973f0bfc1289d405f86d13c19
* Document last modified: 2021-05-06T22:47:38.000Z

</details>

**Comment by rachelandrew** [comment]
Hi @maiteeguren the checkbox isn't expected to be checked, it is disabled (so can't be checked) until the content is scrolled through. Scrolling doesn't check the checkbox.

In the linked PR I have clarified the expected behavior of the demo.
