### ISSUE TITLE
Issue with "How much does it cost to do something on the Web?": (short summary here please)

### ISSUE THREAD

**Issue by weston-verhoff** [mdn/content#5104]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/How_much_does_it_cost

#### What information was incorrect, unhelpful, or incomplete?
There was a typo in the following sentence: "- Is 95% percent reliability adequate, or do you need professional, around-the-clock service?" Percent was repeated.

#### What did you expect to see?
remove "percent"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/common_questions/how_much_does_it_cost`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/How_much_does_it_cost
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/how_much_does_it_cost/index.html
* Last commit: https://github.com/mdn/content/commit/5fb569eddc18081727c03bb97cdb4c67f084804c
* Document last modified: 2021-04-24T03:00:55.000Z

</details>

**Comment by chrisdavidmills** [comment]
Fixed by https://github.com/mdn/content/commit/1c8fe99ed1b5f273fbbb9a18d02bf55ab4554125; thanks for reporting this, @weston-verhoff !
