### ISSUE TITLE
The Developer Guides page needs some work, also assessing what is useful here.

### ISSUE THREAD

**Issue by rachelandrew** [mdn/content#5105]
I'm looking at updating the HTML5 "guide" in https://github.com/mdn/content/issues/4992, which lead me to this page  https://developer.mozilla.org/en-US/docs/Web/Guide which has a bit of an eclectic collection of things on it, some of which are quite outdated.

For example there is a guide to Web APIs https://developer.mozilla.org/en-US/docs/Web/Guide/API which covers what is already here https://developer.mozilla.org/en-US/docs/Web/API and isn't a guide.

Some links just go to the main ref, for example JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript

There are some things that are sub-sections of /guide however we also have this stuff through the docs in more relevant locations.

So, at a minimum I think I want to make sure this is up to date and actually linking to useful guides, but I think there are various things in this section that might be better relocated elsewhere in the docs, or are a bit outdated right now.

Maybe @Rumyra would have some thoughts about some of this material too.

**Comment by sigai07** [comment]
Unsubsribe

Pada tanggal Rab, 19 Mei 2021 14:07, Rachel Andrew ***@***.***>
menulis:

**Comment by Rumyra** [comment]
Hmmm - just having a click around and I agree @rachelandrew 

> So, at a minimum I think I want to make sure this is up to date and actually linking to useful guides, but I think there are various things in this section that might be better relocated elsewhere in the docs, or are a bit outdated right now.

It does appear that an update in organisation would make this a more sensible section. Basically a good ol spring clean?

Also yes this https://developer.mozilla.org/en-US/docs/Web/Guide/API is a reference not a guide and this https://developer.mozilla.org/en-US/docs/Web/API is perfectly fine as the reference. Which means we probably need a guide guide page :)

**Comment by rachelandrew** [comment]
I'll have a bash at it, I think it could be useful if it brought together some common themes with regard to stuff we do have guides for, as there is some good stuff in both the CSS and API docs. I'll raise issues for things that I think need a major update or even removal outside of tidying up the page.

**Comment by Rumyra** [comment]
Let me know if there's any pages that you need me to take a gander at... or in fact _have_ like a web api guide maybe ;)

**Comment by rachelandrew** [comment]
@Rumyra I think an actual guide to APIs would be great! Maybe a bit of an overview in terms of what is possible, good places to get started, and how our docs work?

**Comment by Rumyra** [comment]
@rachelandrew :D I was thinking something similar - I've added it to my backlog 👍

Also this might solve my personal issue of the floating houdini folder - I don't think we should have a separate folder for one intro page of houdini, (I have opinions about the buzzwordiness) but it is a useful page and should maybe go under the guides section.

**Comment by rachelandrew** [comment]
Cool, I'm going to make a PR today that tidies up the page as a starting point, and then we can add or remove things from that.

**Comment by sideshowbarker** [comment]
With three PRs (#5247,  #5248, and #5255 ) having been merged relevant to this — and no further work specifically mentioned — it seems like we can consider this resolved.
