### ISSUE TITLE
Issue with "Node.insertBefore()": referenceNode not optional

### ISSUE THREAD

**Issue by Tiefseetauchner** [mdn/content#5107]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore

#### What information was incorrect, unhelpful, or incomplete?
referenceNode
    The node before which newNode is inserted. **If this is null, then newNode is inserted at the end of parentNode's child nodes.**

#### Specific section or headline?
"If this is null, then newNode is inserted at the end of parentNode's child nodes."

#### What did you expect to see?
Nothing, this is wrong, Firefox throws `Uncaught TypeError: Node.insertBefore: At least 2 arguments required, but only 1 passed`

#### Did you test this? If so, how?
```
element.insertBefore(newEl);
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/node/insertbefore`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/node/insertbefore/index.html
* Last commit: https://github.com/mdn/content/commit/bd5cb714a9b6278c6054aed8eb62c216f4ac0897
* Document last modified: 2021-04-16T13:53:02.000Z

</details>

**Comment by himanshugarg** [comment]
Noob comment - This may not be an issue as the referenced page explicitly notes this: **referenceNode is not an optional parameter. You must explicitly pass a Node or null. Failing to provide it or passing invalid values may behave differently in different browser versions.**

**Comment by Tiefseetauchner** [comment]
Oh, I did overread that... I'm sorry, thanks for pointing it out!
