### ISSUE TITLE
Issue with "Array.prototype.filter()": Return type does a shallow copy of elements.

### ISSUE THREAD

**Issue by crazymeatball** [mdn/content#5127]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

#### What information was incorrect, unhelpful, or incomplete?
The return type description.

#### Specific section or headline?
Return Value

#### What did you expect to see?
A note in that section mentioning that all elements that pass the test are shallow-copied to the new array that is returned. It can be confusing to someone if they think that the elements are deep-copied and then modify a property on an element in either the filtered array or the original array.

#### Did you test this? If so, how?
I used Code mirror at the top of that page to modify the demo and verify the behavior in Google Chrome, Mozilla Firefox and Microsoft Edge Chromium. Here is the code:
```
const words = [
  { value: 'spray'},
  { value: 'limit'},
  { value: 'elite'},
  { value: 'exuberant'},
  { value: 'destruction'},
  { value: 'present'}
];

const result = words.filter(word => word.value.length > 6);

console.log(result);
// expected output: Array ["exuberant", "destruction", "present"]

result[0].value = 'dog'; // change "exuberant" to "dog"

console.log(result[0]);
//the first element's value property is now "dog".

console.log(words[3]);
//the fourth element in the original array, which is referenced by the first element in the filtered array, has been modified as well
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/filter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/filter/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
The default behavior for JavaScript and DOM functions is to _not_ deep-copy structures. If this needed to be mentioned for `Array.prototype.filter` then it would also need to be mentioned for many other functions. I suggest the default shallow-copy behavior be documented in a single location, perhaps on one of the [Learn JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript) pages, possibly with a brief explanation why no universally applicable [deep-copy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#deep_clone) algorithm exists in JavaScript.

**Comment by Andrew-Cottrell** [comment]
Note: glossary entries [shallow copy](https://developer.mozilla.org/en-US/docs/Glossary/Shallow_copy) and [deep copy](https://developer.mozilla.org/en-US/docs/Glossary/Deep_copy) were added to MDN on 4 February 2022 in https://github.com/mdn/content/pull/12474.

Some MDN pages, such as [`Array.prototype.slice`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice), now explicitly state a shallow copy is returned. A similar statement could be added to the MDN page for [`Array.prototype.filter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter).

**Comment by sideshowbarker** [comment]
@crazymeatball Thanks much for raising this, and @Andrew-Cottrell thanks much for the suggestions.

I’ve opened #18023 with a fix.
