### ISSUE TITLE
Issue with "permissions": Broken link to IndexedDB documentation

### ISSUE THREAD

**Issue by WesleyBranton** [mdn/content#5134]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions

#### What information was incorrect, unhelpful, or incomplete?
The `"persistent" IndexedDB database` link under the Unlimited Storage section points to a missing page.

#### Specific section or headline?
Unlimited Storage

#### What did you expect to see?
I'm assuming that it's supposed to point to [this page](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria) under the Web API section of MDN.

#### Did you test this? If so, how?
The link currently opens [this page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria), which is a non-existent article.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/permissions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by Blakelist7** [comment]
@WesleyBranton pointing to https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API will be more resourceful?
Your thoughts

**Comment by WesleyBranton** [comment]
@Blakelist7 I kind of agree with you on that one. The specific page was likely chosen because that's the page in the documentation that has information about the two storage types (persistent and temporary).
