### ISSUE TITLE
Descriptive text wrong

### ISSUE THREAD

**Issue by elegolo** [mdn/content#5143]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Matrix_math_for_the_web

#### What information was incorrect, unhelpful, or incomplete?
Descriptive text wrong after function "multiplyMatrixAndPoint": "matrix" is used instead of "point", 2 times.

#### Specific section or headline?
multiplyMatrixAndPoint, descriptive Text

#### What did you expect to see?
Now using the function above we can multiply a point by the matrix. Using the identity matrix it should return a point identical to the original, since a point multiplied by the identity matrix is always equal to itself:

#### Did you test this? If so, how?
There is nothing to test, its contextually obvious.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl_api/matrix_math_for_the_web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Matrix_math_for_the_web
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/matrix_math_for_the_web/index.html
* Last commit: https://github.com/mdn/content/commit/6c2523b8365f2bef7b26dee75ac7c74e686f3f62
* Document last modified: 2021-02-24T02:44:05.000Z

</details>

**Comment by himanshugarg** [comment]
Noob comment - Independently the statement is accurate but in this context the suggested change improves readability.

**Comment by hamishwillee** [comment]
Hi @elegolo 

Do you think you could create a PR with the fix? I'm not seeing where the problem is, but this would be obvious with a PR.

**Comment by himanshugarg** [comment]
Hi @hamishwillee , I just created one .
