### ISSUE TITLE
Issue with "Intl.NumberFormat.prototype.formatToParts()": type: 'compact' is missing

### ISSUE THREAD

**Issue by mjpieters** [mdn/content#516]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts

#### What information was incorrect, unhelpful, or incomplete?

The list of 'possible types' is incomplete, when using `Intl.NumberFormat({notation: 'compact'}).formatToParts(number)` the _magnitude_ of the value is passed in as a part with `type: 'compact'` 

#### Specific section or headline?

[*Description*](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts#Description), under the *Possible types are the following:* list.

#### What did you expect to see?

`'compact' is missing in this list, as per [EMCA 402, section 12.1.7 (PartitionNotationSubPattern)](https://tc39.es/ecma402/#sec-partitionnotationsubpattern), step 4. - c. - iv. - 2.:

> iv. Else if _p_ is equal to **"compactSymbol"**, then
> 
>    1. *[...]*
>    2. Append a new Record { [[Type]]: **"compact"**, [[Value]]: _compactSymbol_ } as the last element of _result_.

as well as step 4. - c. - v. - 2.:

> v. Else if _p_ is equal to **"compactName"**, then
> 
>    1. *[...]*
>    2. Append a new Record { [[Type]]: **"compact"**, [[Value]]: _compactName_ } as the last element of _result_.

#### Did you test this? If so, how?

JavaScript code using the part type:

```js
const compactFormat = Intl.NumberFormat('en', {
    notation: 'compact',
    compactDisplay: 'short',
    style: 'decimal',
    maximumFractionDigits: 3,
});

// formatValue(42174812) => {formatted: '42.175', magnitude: 'M'}
function formatValue(value) {
    let magnitude = '';
    return {
        formatted: compactFormat
            .formatToParts(value)
            .reduce((formatted, part) => {
            switch (part.type) {
                case 'compact':
                    magnitude = magnitude + part.value;
                    break;
                default:
                    formatted = formatted + part.value;
            }
            return formatted;
        }, ''),
        magnitude: magnitude
    };
}

console.log(formatValue(42174812));
```

outputs

```
Object { formatted: "42.175", magnitude: "M" }
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat/formattoparts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/intl/numberformat/formattoparts/index.html
* Report started: 2020-12-21T12:59:30.442Z

</details>

**Comment by mjpieters** [comment]
I've parsed the [spec source](https://github.com/tc39/ecma402/blob/master/spec/numberformat.html), extracting all `[[Type]]: *"..."*` references, which reveals a few more options that are missing:

- [12.1.6 PartitionNumberPattern](https://tc39.es/ecma402/#sec-partitionnumberpattern):
  -  step 8. - l.: `'unknown'` 

The same type is also possible via 12.1.7, step 4. - c. - viii.
 
- [12.1.7 PartitionNotationSubPattern](https://tc39.es/ecma402/#sec-partitionnotationsubpattern):
  - step 4. - c. - vi. - 2.: `'exponentSeparator'`
  - step 4. - c. - vii. - 1. - b.: `'exponentMinusSign'`
  - step 4. - c. - vii. - 3.: `'exponentInteger'`

**Comment by sideshowbarker** [comment]
@romulocintra Any chance this might be something you’d be interested writing up a PR for?

**Comment by romulocintra** [comment]
> @romulocintra Any chance this might be something you’d be interested writing up a PR for?

Sure

**Comment by Rumyra** [comment]
Hey @romulocintra is there any update here? Thanks!

**Comment by romulocintra** [comment]
> Hey @romulocintra is there any update here? Thanks!

Getting started with it !! thanks for nudging ;)

**Comment by romulocintra** [comment]
@Rumyra and @sideshowbarker  https://github.com/mdn/content/pull/20127
