### ISSUE TITLE
Issue with "runtime.sendMessage()": update example: returning a Promise is now preferred, as sendResponse() will be removed from the W3C spec

### ISSUE THREAD

**Issue by FoE-Info** [mdn/content#5169]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage

#### What information was incorrect, unhelpful, or incomplete?

Returning a Promise is now preferred, as sendResponse() will be removed from the W3C spec
nee to update the example to use a promise - sendResponse({response: "Response from background script"});

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage#examples

#### What did you expect to see?

example that complies with current recommendations

#### Did you test this? If so, how?

the example code results in a warning:
browser-polyfill.js:1075 Returning a Promise is the preferred way to send a reply from an onMessage/onMessageExternal listener, as the sendResponse will be removed from the specs (See https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/runtime/sendmessage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/runtime/sendmessage/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by rebloor** [comment]
@rpl see you are the assignee on this one, can I help move this one forward?

**Comment by rpl** [comment]
> @rpl see you are the assignee on this one, can I help move this one forward?

The warning emitted by the webextension-polyfill will be going away, the w3c specs draft the warning refers to is an obsolete draft.

I filed mozilla/webextension-polyfill#386 to track that.

**Comment by rebloor** [comment]
Thanks @rpl, from your feedback I assume that this issue is now moot so I've closed it.
