### ISSUE TITLE
Consider replacing link to Polymer with Lit in See Also section of Web Components page

### ISSUE THREAD

**Issue by rpivo** [mdn/content#5174]
https://developer.mozilla.org/en-US/docs/Web/Web_Components

<hr />

Google recommends Lit for new development in place of Polymer.

See:
https://polymer-library.polymer-project.org/3.0/docs/devguide/feature-overview
https://lit.dev/

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/5817 with a fix.
