### ISSUE TITLE
Issue with "Date() constructor": monthIndex is not 0 indexed, it's 1 indexed

### ISSUE THREAD

**Issue by emilfihlman** [mdn/content#5175]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

#### What information was incorrect, unhelpful, or incomplete?
monthIndex is not 0 indexed, it's 1 indexed

#### Specific section or headline?
Individual date and time component values

#### What did you expect to see?
Integer value representing the month, beginning with 1 for January to 12 for December.

#### Did you test this? If so, how?
Yes, on both Chrome and Firefox developer console.
new Date(2021, 2, 0).getDate(); returns 28, not 31 as expected for 1 indexed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/date`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/date/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by Blakelist7** [comment]
@emilfihlman I tested it today on Firefox console and it returned 4 and I guess that's right because it returns the index number which means index number is 4 but month number is 5. If that makes any sense.

**Comment by emilfihlman** [comment]
![Screenshot_20210521_124640](https://user-images.githubusercontent.com/9070088/119118307-c15a8c00-ba32-11eb-8850-95a1dacbaf13.png)

**Comment by Blakelist7** [comment]
> ![Screenshot_20210521_124640](https://user-images.githubusercontent.com/9070088/119118307-c15a8c00-ba32-11eb-8850-95a1dacbaf13.png)

https://www.w3resource.com/javascript-exercises/javascript-date-exercise-3.php Have a look at this, it might help you.

**Comment by Andrew-Cottrell** [comment]
Another demonstration that months are zero-indexed
```javascript
Array.from({length: 12}, (ignore, index) => console.log({number: index, string: /\d\d\s(\w*)\s\d\d\d\d/.exec(new Date(Date.UTC(2021, index, 1)).toUTCString())[1]}));
```
output in Chrome 90 is
```
{number: 0, string: "Jan"}
{number: 1, string: "Feb"}
{number: 2, string: "Mar"}
{number: 3, string: "Apr"}
{number: 4, string: "May"}
{number: 5, string: "Jun"}
{number: 6, string: "Jul"}
{number: 7, string: "Aug"}
{number: 8, string: "Sep"}
{number: 9, string: "Oct"}
{number: 10, string: "Nov"}
{number: 11, string: "Dec"}
```
The day-of-month value is one-indexed, so the value `0` causes the `Date` constructor to go back one day from the first day of the specified zero-indexed month.

**Comment by emilfihlman** [comment]
@Andrew-Cottrell I see, well, thanks for clarifying! I suppose this could be noted in the docs more clearly?

**Comment by Andrew-Cottrell** [comment]
Fortunately, we will probably have [proposal-temporal](https://github.com/tc39/proposal-temporal) in the ECMAScript specification next year and then we can polyfill or shim it as required. In particular, [`Temporal.PlainDate`](https://tc39.es/proposal-temporal/docs/plaindate.html#new-Temporal-PlainDate), and other `Temporal` routines that accept and return month numbers, use one-indexed ISO month numbers. This should make date calculations much less error prone!

After that, I expect best practise will be to avoid `Date` for calculations and to [convert](https://tc39.es/proposal-temporal/docs/cookbook.html#converting-between-temporal-types-and-legacy-date) as required. Perhaps the [`Date` page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) will make a similar recommendation once proposal-temporal is in the ECMAScript specification.

**Comment by emilfihlman** [comment]
>use one-indexed ISO month numbers. This should make date calculations much less error prone!

Imho it should absolutely be 0 indexed for everything, both month and year.

**Comment by Blakelist7** [comment]
@emilfihlman If your doubt is clear, you can close this issue.

**Comment by sideshowbarker** [comment]
Closing this since this statement is the article is true:
> Integer value representing the month, beginning with 0 for January to 11 for December
…and as the example in https://github.com/mdn/content/issues/5175#issuecomment-845965134 demonstrates.

@emilfihlman We can revisit this if you have some specific suggestions for clarifications that could be added — in which case, you could also raise a pull request with proposed text to add.

**Comment by emilfihlman** [comment]
@sideshowbarker I'm not sure how to do a pull request, but here's a proposition:

Under section 4 after the first paragraph before the explanation of the individual arguments, add a note, saying:
"The calculations on the date and time are done internally with a smaller unit and then converted back than might be expected and the results are not limited to the specified year, month, day or time exclusively. Thus specifying for example new Date(2021, 6, 0).getDate(); results in getting the number of days in June instead of some date in July."

**Comment by Blakelist7** [comment]
@emilfihlman Have a look at https://www.google.com/amp/s/www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/amp/
