### ISSUE TITLE
Issue with "402 Payment Required": … No browser compatibility table

### ISSUE THREAD

**Issue by bedrockcoder** [mdn/content#518]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402

#### What information was incorrect, unhelpful, or incomplete?
There is no browser compatibility table

#### Specific section or headline?
The browser compatibility table

#### What did you expect to see?
A browser compatibility table

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status/402`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/status/402/index.html
* Report started: 2020-12-21T14:09:47.947Z

</details>

**Comment by hamishwillee** [comment]
@ddbeck A subset of HTTP status codes have BCD entries [here](https://github.com/mdn/browser-compat-data/blob/master/http/status.json). What does it mean for a browser to "support" a status code? i.e. 400 or 200?

My _assumption_ is that very few codes actually need "support" - they just get displayed along with the message. This particular case 402 is like that. 

Have you got any general thoughts on what "needs" documentation?

**Comment by ddbeck** [comment]
I think docs for 402 makes sense—Web developers probably need to know to _not_ use this reserved code—but BCD doesn't.

All of the widely-used status codes are interesting to Web developers and merit documentation, but whether a status code needs compat data depends on whether there's actually a plausible compat risk. I think few codes actually meet that hurdle, but BCD doesn't actually provide a guideline on this. I'd probably set the criteria for inclusion like this:

---

A status code should be in BCD if one of the following is true:

1. The status code is specified in such a way that a browser would be expected to act in response to such a status code in a particular way (i.e., the spec contains some "client SHOULD" or "client MUST" text about the status code). For example, the first of every [class of status code](https://tools.ietf.org/html/rfc7231#section-6)—the x00 codes—would meet this criteria.
2. The status code is implemented in such a way that Web developers could rely on some automatic behavior in response to a status code (e.g., the spec for 301 doesn't actually require browsers to automatically follow the redirect, but they all do).

---

402 doesn't clear this bar. I'd probably omit the compat section in the page for it, or explicitly say, "You should not expect browser compatibility with this status code. It's reserved for future use and should not be implemented."

**Comment by bedrockcoder** [comment]
Alright, thanks for the response!
