### ISSUE TITLE
Issue with "Using data attributes": (ambiguous example)

### ISSUE THREAD

**Issue by David263** [mdn/content#5189]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

#### What information was incorrect, unhelpful, or incomplete?
A usage example reads `const article = document.querySelector('#electric-cars');`

#### Specific section or headline?
JavaScript access

#### What did you expect to see?
The use of querySelector to get an element by ID is surprising, since getElementById is the usual function recommended for this operation. It is therefore unclear whether the example will work using getElementById, or some other method for obtaining an element node.

#### Did you test this? If so, how?
I tested both querySelector and getElementById and found that they both work just fine. In addition, using the bare ID also works fine when the id is unambiguous (since id attributes already exist in the global 'window' namespace). Just "abc.dataset.def" works fine as an element reference, where abc is the id and def is the part of the data attribute after "data-". The text should simply indicate somehow that any method (including these three) for obtaining an element node is acceptable. I tested on Firefox 88.0.1 and Chrome 90.0.4430.212 .

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/howto/use_data_attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/howto/use_data_attributes/index.html
* Last commit: https://github.com/mdn/content/commit/c8c9495977e09fc4ccd7d7f85ff6527aa61a73cc
* Document last modified: 2021-03-23T06:42:00.000Z

</details>

**Comment by sideshowbarker** [comment]
> The use of querySelector to get an element by ID is surprising, since getElementById is the usual function recommended for this operation.

It’s not true that getElementById is “recommended” over querySelector for getting an element by ID. If anything, I think in the wider developer community, the common practice these days is to use querySelector for everything, and mostly just ignore getElementById.

> It is therefore unclear whether the example will work using getElementById, or some other method for obtaining an element node.

From the fact that this example uses querySelector, it does not follow that there’s anything unclear about whether the example will work with getElementById or some other method. There’s nothing inherently ambiguous introduced by querySelector being used here.

**Comment by David263** [comment]
I don't disagree with sideshowbarker at all. I was reflecting what I got out this page as someone reading it for the first time and really wanting to understand it. If my opinion is not accepted, so be it. I'm fine with that.

**Comment by sideshowbarker** [comment]
> I don't disagree with sideshowbarker at all. I was reflecting what I got out this page as someone reading it for the first time and really wanting to understand it. If my opinion is not accepted, so be it. I'm fine with that.

Well, upon further reflection, I agree that other developers might wonder the same thing you did — so I opened https://github.com/mdn/content/pull/5907 with an update that adds a clarifying code comment.
