### ISSUE TITLE
Issue with "List of default Accept values": wrong value for images in Safari

### ISSUE THREAD

**Issue by cadeyrn** [mdn/content#5190]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values

#### What information was incorrect, unhelpful, or incomplete?

Incorrect information for images in Safari. The MDN says:

`image/png,image/svg+xml,image/*;q=0.8,video/*;q=0.8,*/*;q=0.5`

#### Specific section or headline?

Values for an image

#### What did you expect to see?

On macOS Big Sur (where Safari supports WebP) Safaris sends the following Accept Header:

` image/webp,image/png,image/svg+xml,image/*;q=0.8,video/*;q=0.8,*/*;q=0.5`

The comment column could be used to make clear that WebP is only supported on macOS Big Sur and later versions.

#### Did you test this? If so, how?

Used the network developer tool of Safari.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/content_negotiation/list_of_default_accept_values`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/content_negotiation/list_of_default_accept_values/index.html
* Last commit: https://github.com/mdn/content/commit/b7169689fc3f0f2ea517a216494493f62467e377
* Document last modified: 2021-02-26T10:06:58.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks @cadeyrn ! I fixed in #5288 by simply listing both strings (I tried a comment too, but I found doing it this way to be better).
