### ISSUE TITLE
Issue with "Access-Control-Expose-Headers": (short summary here please)

### ISSUE THREAD

**Issue by MamaCece6** [mdn/content#5213]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/access-control-expose-headers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/access-control-expose-headers/index.html
* Last commit: https://github.com/mdn/content/commit/fdda33713520f9982b5f214bdf941cac8b64affb
* Document last modified: 2021-03-09T06:17:44.000Z

</details>

**Comment by hamishwillee** [comment]
Closing as no issue information provided.
