### ISSUE TITLE
Issue with "Using CSS gradients": (short summary here please)

### ISSUE THREAD

**Issue by Jamshaid-003** [mdn/content#5214]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Using_CSS_gradients

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_images/using_css_gradients`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Using_CSS_gradients
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_images/using_css_gradients/index.html
* Last commit: https://github.com/mdn/content/commit/892665a4c27da31a26d22578335377549324bb88
* Document last modified: 2021-03-23T04:34:40.000Z

</details>

**Comment by Jamshaid-003** [comment]
never work properly scroll bar

**Comment by rachelandrew** [comment]
@Jamshaid-003 hi - can you let me know which scroll bar you are having a problem with, along with the browser you are seeing the problem in.

**Comment by rachelandrew** [comment]
Closing as no response from OP. Feel free to reopen with more info.

**Comment by Jamshaid-003** [comment]
ok thanks to the reply back, solve the problem
