### ISSUE TITLE
Issue with "Getting started with the Web": (short summary here please)

### ISSUE THREAD

**Issue by senghour157** [mdn/content#5215]
[MDN](https://paingsenghour157.com) URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/index.html
* Last commit: https://github.com/mdn/content/commit/2f8a952fb77a77ac3837b7bf37520e99a8d4c26c
* Document last modified: 2021-02-11T13:56:08.000Z

</details>

**Comment by hamishwillee** [comment]
Closing as no information provided.
