### ISSUE TITLE
Possible misleading statement on Export documentation

### ISSUE THREAD

**Issue by ShadyStego** [mdn/content#5220]
MDN URL: https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

The content:

> Re-exporting / Aggregating
> It is also possible to "import/export" from different modules in a parent module so that they are available to import from that module. In other words, one can create a single module concentrating various exports from various modules.
> 
> This can be achieved with the "export from" syntax:
> 
> export { default as function1,
>          function2 } from 'bar.js';
> 
> Which is comparable to a combination of import and export:
> 
> import { default as function1,
>          function2 } from 'bar.js';
> export { function1 as default, function2 };
> 
> But where function1 and function2 do not become available inside the current module.
> 

Isn't the first example resulting in a named export for `function1`, whereas the second one re-exporting `function1` as default, as such they're not really comparable?

**Comment by Josh-Cena** [comment]
This has been fixed by #8852 already

**Comment by teoli2003** [comment]
Closing per comment.
