### ISSUE TITLE
Issue with "Using server-sent events": Example using a const out of its context

### ISSUE THREAD

**Issue by manwey** [mdn/content#5222]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

#### What information was incorrect, unhelpful, or incomplete?

evtSource.addEventListener("ping", function(event) {
  const newElement = document.createElement("li");
  const time = JSON.parse(event.data).time;
  newElement.textContent = "ping at " + time;
  eventList.appendChild(newElement);
});

#### Specific section or headline?

Receiving events from the server

#### What did you expect to see?

evtSource.addEventListener("ping", function(event) {
  const newElement = document.createElement("li");
  const eventList = document.getElementById("list");
  const time = JSON.parse(event.data).time;
  newElement.textContent = "ping at " + time;
  eventList.appendChild(newElement);
});

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/server-sent_events/using_server-sent_events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/server-sent_events/using_server-sent_events/index.html
* Last commit: https://github.com/mdn/content/commit/3ae7f6ff12ee7d78ee20cebdb8ea65643a9aa955
* Document last modified: 2021-04-04T04:55:44.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this — I’ve opened https://github.com/mdn/content/pull/5722 with a fix.
