### ISSUE TITLE
Issue with "Web technology for developers": …

### ISSUE THREAD

**Issue by dhein1030** [mdn/content#523]
MDN URL: https://developer.mozilla.org/en-US/docs/Web

#### What information was incorrect, unhelpful, or incomplete?
Code snippets link broken, 404 on https://developer.mozilla.org/en-US/docs/Code_snippets

#### Specific section or headline?
Code snippets,

#### What did you expect to see?
A page with code snippets

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/index.html
* Report started: 2020-12-21T15:23:59.713Z

</details>

**Comment by Scttpr** [comment]
Hi, sorry it's probably a dumb question but I can only find `web/xpath/snippets` directory which contains `snippet`.

I tried also the link in the following text which is broken too : https://developer.mozilla.org/en-US/docs/XULRunner

The weird thing for me is that I cannot find the `docs` folder even if `en-US/docs` leads to a page... Do you have some insights so I can try to resolve this issue ? :stuck_out_tongue: 

Thanks !

**Comment by chrisdavidmills** [comment]
I don't see this link on that page any more, so closing.
