### ISSUE TITLE
Issue with "Toolbox": perhaps a typo

### ISSUE THREAD

**Issue by lkintact** [mdn/content#5242]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox

#### What information was incorrect, unhelpful, or incomplete?
The article has this text: `(or Web Developer > Toggle Tools before Firefox 89)`.
For me in Firefox 88.0.1, Windows 10 Home, it's `Web Developer > Web Developer Tools`.

#### Specific section or headline?
The very first section, "Tools".

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/tools_toolbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/tools_toolbox/index.html
* Last commit: https://github.com/mdn/content/commit/6e59c64149037dd061cd56064b92ac18684368a7
* Document last modified: 2021-05-07T07:36:48.000Z

</details>

**Comment by hamishwillee** [comment]
- FF89/90: Menu > More Tools > Web Developer Tools
- FF88: Menu > Web Developer > Web Developer Tools
- FF87 (ish): Menu > Web Developer > Toggle Tools
- 
I'll tidy it up.
