### ISSUE TITLE
Bluetooth.requestDevice syntax block is misleading

### ISSUE THREAD

**Issue by foolip** [mdn/content#5244]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/requestDevice#syntax

#### What information was incorrect, unhelpful, or incomplete?

This syntax block:
```
Bluetooth.requestDevice([options])
  .then(function(bluetoothDevice) { ... })
```

This doesn't work because `requestDevice` is not a static method. The example should be something like `bluetoothDevice = await navigator.bluetooth.requestDevice([options])`, maybe with `{acceptAllDevices: true})` as the options.

This is a problem with other Bluetooth syntax blocks too, there are too many for me to fix so creating an issue.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/bluetooth`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/bluetooth/index.html
* Last commit: https://github.com/mdn/content/commit/11a98a59fca5f2e448d9e4b70e3c8a538c47b201
* Document last modified: 2021-02-19T19:45:18.000Z

</details>

**Comment by foolip** [comment]
@Elchi3 is there a generic issue for this, any scripts to help find these broken syntax blocks?

**Comment by Elchi3** [comment]
> @Elchi3 is there a generic issue for this, any scripts to help find these broken syntax blocks?

I don' think so. For `JavaScript/` I went trough and took a look at all pages with `h2#Syntax > pre`. I ran out of steam to do the same with `API/` pages.

**Comment by foolip** [comment]
Yeah, it would be a lot of work to audit all of these syntax blocks, I didn't even want to do all of Web Bluetooth, knowing that lots of them would need fixing.

I wonder if it might be possible to generate syntax blocks from Web IDL here? Then one could review the generated suggestions and replace the ones that are clearly an improvement, which I'm guessing would be >50% at least.

**Comment by sideshowbarker** [comment]
> I wonder if it might be possible to generate syntax blocks from Web IDL here? Then one could review the generated suggestions and replace the ones that are clearly an improvement, which I'm guessing would be >50% at least.

Yeah, that sounds to me like an idea worth pursuing.

**Comment by Elchi3** [comment]
Syntax blocks have been updated a lot since this issue has been opened. 
See https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/requestDevice#syntax

https://developer.mozilla.org/en-US/docs/MDN/Structures/Syntax_sections has docs on how to create proper MDN syntax sections.
