### ISSUE TITLE
Outdated info in material on XMLHttpRequest

### ISSUE THREAD

**Issue by rachelandrew** [mdn/content#5245]
I'm working on #5105 and assessing some of the material linked from that page. 

## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started#step_1_%E2%80%93_how_to_make_an_http_request

## What is the problem?

I think we could probably lose the info about IE6 at this point.

I imagine that this getting started page and also https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest which has outdated browser info on, could do with someone reviewing them. 

There is also an Ajax overview page here https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX

**Comment by Josh-Cena** [comment]
Fixed via https://github.com/mdn/content/pull/20049 and https://github.com/mdn/content/pull/9226
