### ISSUE TITLE
Issue with "SyntaxError: missing variable name": Slightly Unprofessional Looking Content

### ISSUE THREAD

**Issue by gosoccerboy5** [mdn/content#5251]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/No_variable_name

## What information was incorrect, unhelpful, or incomplete?
It's all very helpful, but the author speaks on a personal, casual level, which clashes with the style of the rest of the content, which I perceive as a slightly more technical-sounding and formal.
I would have no problem with a friendly style like this, but it seems to not match with other pages in style.

## Specific section or headline?
Not really, but the first sentence is already a bit alarming:
> The JavaScript exception "missing variable name" occurs way too often as naming things is so hard. Or maybe a comma is wrong. Check for typos!

## What did you expect to see?
I expected to see something fitting the writing style of MDN in general a bit more.

## Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/no_variable_name`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/No_variable_name
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/no_variable_name/index.html
* Last commit: https://github.com/mdn/content/commit/4a2976fab16bb915f41600bf6d2e50523325bd46
* Document last modified: 2021-03-29T10:38:42.000Z

</details>

Apologies if this isn't the right kind of issue to report - I'm new to contributing here

**Comment by jadjoubran** [comment]
I'd be happy to fix this, can I get assigned?
