### ISSUE TITLE
Content bug: Link to "falsy" does not go to right place.

### ISSUE THREAD

**Issue by timster** [mdn/content#5253]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

## Specific page section or heading?

In the second paragraph, there is a link to "falsy":

https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/nullish_coalescing_operator/index.html#L23

## What is the problem?

This link doesn't seem to go to the right place. It links to a #Description anchor which doesn't exist on the page. The page also has no reference to "falsy" on it.

## What did you expect to see?

Some page that describes what falsy is. Maybe this one?

https://developer.mozilla.org/en-US/docs/Glossary/Falsy

## Did you test this? If so, how?

Click on the link and see that it's not right.

**Comment by hamishwillee** [comment]
Thanks @timster - fixed by #5268 (yes, linking to falsy in glossary looks good to me!).
