### ISSUE TITLE
Issue with "url()": Missing parenthesis in demo code

### ISSUE THREAD

**Issue by willster277** [mdn/content#5261]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/url()

#### What information was incorrect, unhelpful, or incomplete?
On the page is the following css;
```css
mask-image: image(url(mask.png), skyblue, linear-gradient(rgba(0, 0, 0, 1.0), transparent);
```
Which is missing a closing bracket for `image`

It could be `linear-gradient` that's missing it, but that seems odd to only give the gradient a single value (would be `linear-gradient(rgba(0, 0, 0, 1.0))`).

#### Specific section or headline?
Under the title "url()" in the "/* As a parameter in another CSS function */" portion of the demo code

#### What did you expect to see?
The closing parenthesis for the `image` function, not a huge deal right now as the function has very little browser support.

#### Did you test this? If so, how?
As the image() function is not supported on any browser by default (https://developer.mozilla.org/en-US/docs/Web/CSS/image()) I didnt test this.
I did however put it into an up to date CSS linter which recognises many new/experimental properties, and it gave me an error regarding the missing `)`. I suppose that's something at least.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/url()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/url()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/url()/index.html
* Last commit: https://github.com/mdn/content/commit/25cc5c5c4f999bf49204ae067eb2c30ccb3492c8
* Document last modified: 2021-05-10T22:50:26.000Z

</details>

**Comment by teoli2003** [comment]
That sounds correct to me. I create a PR, let's see if it passes the review process.

Thanks for reporting!
