### ISSUE TITLE
Issue with "Array.prototype.reduceRight()": (initialValue parameter is listed in Syntax section as thisArg)

### ISSUE THREAD

**Issue by robertg042** [mdn/content#5262]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/ReduceRight

Also relevant to: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/reduceRight

#### What information was incorrect, unhelpful, or incomplete?
```js
reduceRight(function callbackFn(accumulator, currentValue, index, array) { ... }, thisArg)
```

#### Specific section or headline?
Syntax

#### What did you expect to see?
```js
reduceRight(function callbackFn(accumulator, currentValue, index, array) { ... }, initialValue)
```

#### Did you test this? If so, how?
Yes, FF 88 dev tools

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/reduceright`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/ReduceRight
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/reduceright/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by Elchi3** [comment]
Thanks, I recently updates the syntax blocks and missed this one 😊
Opened a PR to fix this
