### ISSUE TITLE
Issue with "<img>: The Image Embed element": (short summary here please)

### ISSUE THREAD

**Issue by kevincox** [mdn/content#5270]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-crossorigin

#### What information was incorrect, unhelpful, or incomplete?

The docs for the `crossorigin=anonymous` seems to claim that it is strictly more general than not setting the attribute, however testing on Firefox and Chromium seem to claim otherwise.

According to the document if the response does not have a valid `Access-Control-Allow-Origin` header the image will still be loaded but it will be tainted. However testing shows that the image is not loaded at all with a CORS error in the console.

#### Specific section or headline?

MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-crossorigin

#### Did you test this? If so, how?

```html
<img id="bg" src="https://i.redd.it/rq7j27b9l0171.jpg" crossorigin>
```

This image fails to load (if you are not attempting from Reddit). Removing the corssorigin makes it load.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/img`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/img/index.html
* Last commit: https://github.com/mdn/content/commit/f2a9cd26197733d09c0547ce7d750c65ca59a812
* Document last modified: 2021-04-27T06:37:39.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this — I’ve opened https://github.com/mdn/content/pull/5723 with a fix.
