### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by 1emmanuell** [mdn/content#5272]
It would be really nice and helpful if the MDN website had dark mode. Thank you.

**Comment by SphinxKnight** [comment]
Please see [mdn/yari](https://github.com/mdn/yari/) and [this discussion](https://github.com/mdn/yari/discussions/2539)

**Comment by sideshowbarker** [comment]
Closing this is as duplicate of https://github.com/mdn/yari/discussions/2539. To track progress on getting a dark mode for MDN, please consider subscribing to that issue.
