### ISSUE TITLE
Issue with "Element.ariaDisabled": Description for values is vice-versa

### ISSUE THREAD

**Issue by tomasbonco** [mdn/content#5275]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaDisabled

#### What information was incorrect, unhelpful, or incomplete?
Description for possible values is incorrect (it's vice-versa).
See W3: https://www.w3.org/TR/wai-aria-1.2/#aria-disabled

#### Specific section or headline?
Syntax > Value

#### What did you expect to see?
`"true"`
~The element is enabled.~
The element and all focusable descendants are disabled and its value cannot be changed by the user.

`"false"`
~The element and all focusable descendants are disabled and its value cannot be changed by the user.~
The element is enabled.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/ariadisabled`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaDisabled
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/ariadisabled/index.html
* Last commit: https://github.com/mdn/content/commit/2f54395e640f1ea9c03b449f0cd6ed397b5ed8d3
* Document last modified: 2021-02-25T15:23:22.000Z

</details>

**Comment by teoli2003** [comment]
Thanks a lot @tomasbonco ! Good catch! 

I'm opening a PR.
