### ISSUE TITLE
Issue with "The WebSocket API (WebSockets)": broken link

### ISSUE THREAD

**Issue by F4R4N** [mdn/content#5281]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API

#### What information was incorrect, unhelpful, or incomplete?
there is a broken link at https://caddyserver.com/docs/websocket

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API#tools

#### Did you test this? If so, how?
there is no alternative I could find in the documentation for this path to open a pull request.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/websockets_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/websockets_api/index.html
* Last commit: https://github.com/mdn/content/commit/c724c40fbb61b51644f81072865cb7692388cb95
* Document last modified: 2021-05-19T09:30:41.000Z

</details>

**Comment by teoli2003** [comment]
Hi, F4R4N.

Unlike Caddy v1, there is nothing to configure in Caddy v2 to enable Websocket: websocket proxying is enable by default.

I think we should change the link to point to https://caddyserver.com/ . What do you think?

Thanks for reporting the problematic link!

**Comment by F4R4N** [comment]
thanks @teoli2003.
