### ISSUE TITLE
Issue with "Constraint validation API": (short summary here please)

### ISSUE THREAD

**Issue by danielebarell** [mdn/content#5293]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation

#### What information was incorrect, unhelpful, or incomplete?
A little superflous code

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation#examples
In the JavaScript part the variable 'form' is created but then never used. 
```
const nameInput = document.querySelector('input');
const form = document.querySelector('form');//dan: why this?

nameInput.addEventListener('input', () => {
  nameInput.setCustomValidity('');
  nameInput.checkValidity();
});

nameInput.addEventListener('invalid', () => {
  if(nameInput.value === '') {
    nameInput.setCustomValidity('Enter your username!');
  } else {
    nameInput.setCustomValidity('Usernames can only contain upper and lowercase letters. Try again!');
  }
});
```
#### What did you expect to see?
```
const nameInput = document.querySelector('input');

nameInput.addEventListener('input', () => {
  nameInput.setCustomValidity('');
  nameInput.checkValidity();
});

nameInput.addEventListener('invalid', () => {
  if(nameInput.value === '') {
    nameInput.setCustomValidity('Enter your username!');
  } else {
    nameInput.setCustomValidity('Usernames can only contain upper and lowercase letters. Try again!');
  }
});
```

#### Did you test this? If so, how?
Actually I didn't test it

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/constraint_validation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/constraint_validation/index.html
* Last commit: https://github.com/mdn/content/commit/d5cf56f90ed1268223b96501149a7ca40b276438
* Document last modified: 2021-02-04T10:39:33.000Z

</details>

**Comment by teoli2003** [comment]
Thanks @danielebarell !

This makes sense. I opened a PR.

**Comment by danielebarell** [comment]
Thank you for the MDN article.
😊
