### ISSUE TITLE
Issue with "MathML": dev-tech-mathml not exists in Mozilla mailing lists

### ISSUE THREAD

**Issue by F4R4N** [mdn/content#5300]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/MathML

#### What information was incorrect, unhelpful, or incomplete?
the Mozilla mailing list on the page return 404.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/MathML#getting_help_from_the_community

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/mathml`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/MathML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/mathml/index.html
* Last commit: https://github.com/mdn/content/commit/70beea48a72c7dbc0d07e2a0dd9c9a95aa457d47
* Document last modified: 2021-03-26T23:17:12.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/5719 with a fix.

**Comment by F4R4N** [comment]
thanks.
