### ISSUE TITLE
Issue with "filter": ( no units for brightness at Syntax )

### ISSUE THREAD

**Issue by Guustaaf** [mdn/content#5314]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/filter

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/filter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/filter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/filter/index.html
* Last commit: https://github.com/mdn/content/commit/775066d2fc8d1561d5da61983d137c1297899315
* Document last modified: 2021-05-08T09:57:47.000Z

</details>

**Comment by SphinxKnight** [comment]
It appears that [`brightness()`](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/brightness()) only takes a value which is a number or a percentage and thus is unitless. The [signature of the function in the spec](https://drafts.fxtf.org/filter-effects/#funcdef-filter-brightness) points to the [`<number-percentage>` type](https://www.w3.org/TR/css-values-3/#typedef-number-percentage).

The page for `filter` seems correct here. Let us know with further information if you wish to reopen this.
