### ISSUE TITLE
Issue with "Create BookInstance form": (short summary here please)

### ISSUE THREAD

**Issue by krezatulpod** [mdn/content#5323]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_BookInstance_form

#### What information was incorrect, unhelpful, or incomplete?
I assume that the "title" field did not require validation since is a field of SELECT type, not the type INPUT. That's why the web user cannot specify wrong information of the type that validation verifies 

#### Specific section or headline?
body("title","Book must be specified").trim().isLength({min:1}).escape()

#### What did you expect to see?
I guess a simple requirement is enough.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_bookinstance_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_BookInstance_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_bookinstance_form/index.html
* Last commit: https://github.com/mdn/content/commit/adc309da4235ec6c01f40e3212168ea5b98358c9
* Document last modified: 2021-01-29T01:56:44.000Z

</details>

**Comment by hamishwillee** [comment]
I'm a bit confused by the question. But essentially we validate and sanitise all the data we save. You can see that below - blue box shows sanitising going on, and the object that is saved is shown in yellow
![image](https://user-images.githubusercontent.com/5368500/119942318-0489a180-bfd5-11eb-809d-39d8b8335840.png)

The title field in the form isn't used for anything but display - we don't read it or pass it to a database etc.

I am pretty sure this is invalid. Will close, but reopen if I'm way off the mark.
