### ISSUE TITLE
Issue with "Use CSS to $:;solve common problems": (short summary here please)

### ISSUE THREAD

**Issue by hamadshaikh** [mdn/content#5327]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Howto

#### What information was incorrect, un
helpful, or incomplete?
$:;

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/howto`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Howto
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/howto/index.html
* Last commit: https://github.com/mdn/content/commit/70beea48a72c7dbc0d07e2a0dd9c9a95aa457d47
* Document last modified: 2021-03-26T23:17:12.000Z

</details>

**Comment by teoli2003** [comment]
Hi! @hamadshaikh !

Thank you for opening an issue. What is the problem with this page?

You didn't give us any hint about what has to be corrected.

Thanks for your help!

**Comment by hamishwillee** [comment]
Closing as insufficient information provided.

**Comment by hamishwillee** [comment]
PS @teoli2003 Thanks for chasing up the author. We get enough of these that it is often worth closing them "by default" with a note "I'm closing for now - feel free to reopen with additional information" or whatever.

**Comment by teoli2003** [comment]
@hamishwillee Absolutely! I just don't have the rights to close it :-)
@hamadshaikh If you come back and do provide extra informatiion, feel free to reopen it (or create a new issue) !
