### ISSUE TITLE
Issue with "Using the Web Storage API": invalid Safari private browser statement

### ISSUE THREAD

**Issue by basslagter** [mdn/content#5329]
The page (https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API) states: 
"For example, Safari browser in Private Browsing mode gives us an empty localStorage object with a quota of zero, effectively making it unusable."

But this is fixed in Safari 14:
"Enabled full third-party cookie blocking, and the Storage Access API in Private Browsing mode."

**Comment by sideshowbarker** [comment]
Thanks much for catching this — I’ve opened https://github.com/mdn/content/pull/5721 with a fix.
