### ISSUE TITLE
Issue with "HTTP headers": Confusion between representation, request, response header fields

### ISSUE THREAD

**Issue by singla-shivam** [mdn/content#5339]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

#### What information was incorrect, unhelpful, or incomplete?
Representation headers are listed with request and response headers.

There are only two broad categories of headers: request headers and response headers. Some headers belong to only one category while some belong to both categories. Representation headers are different from these two. All representation headers belong to both categories. Additionally, there is one more category:- payload headers.

#### Specific section or headline?
> Headers can be grouped according to their contexts:

#### What did you expect to see?
Representation headers should be listed separately while describing groups of headers.
And if representation headers are mentioned, [payload headers](https://tools.ietf.org/pdf/rfc7231.pdf#page=18) should also be mentioned.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/index.html
* Last commit: https://github.com/mdn/content/commit/7059d0ee6cc463bdc1fce15a0475c377e54d2719
* Document last modified: 2021-05-15T03:10:09.000Z

</details>

**Comment by hamishwillee** [comment]
Yes, this is a useful distinction - I recently updated from entity headers to representation headers, but somehow missed the payload headers. Assigned to me to fix up.

**Comment by hamishwillee** [comment]
@singla-shivam Finally got to this - sorry for the delay. Feel free to comment on fix in #5753.
