### ISSUE TITLE
Issue with "Basic concepts": This is a glossary, not an introduction

### ISSUE THREAD

**Issue by meatnordrink** [mdn/content#5340]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Basic_Concepts_Behind_IndexedDB

#### What information was incorrect, unhelpful, or incomplete?
This isn't really an introduction; it's just a glossary. Just listing all the terms used, and using other terms in the glossary in the definitions, is just confusing. I think this section would be a lot more useful, and fulfill it's promise of "Basic concepts", if it followed a simple example through and used that to illustrate the basic terms. Just throwing a bunch of definitions at people isn't super helpful, in my opinion.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/indexeddb_api/basic_concepts_behind_indexeddb`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Basic_Concepts_Behind_IndexedDB
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/indexeddb_api/basic_concepts_behind_indexeddb/index.html
* Last commit: https://github.com/mdn/content/commit/12024ee393c3fe3101b03903561c640444b38646
* Document last modified: 2021-04-08T14:57:07.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5689 with an update to the article (as well as updates to the other articles which link to it).
