### ISSUE TITLE
Issue with "Link types: preload": Misleading, Possibly Incorrect Example

### ISSUE THREAD

**Issue by GusBuonv** [mdn/content#5350]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload

#### What information was incorrect, unhelpful, or incomplete?

The "[Including a MIME Type](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#including_a_mime_type)" section is misleading or incorrect.

The section provides an example in which two video sources of different media types have rel="preload" links in the head. The section text states that browsers that don't support the MP4 media type will fall back to the WebM source _and_ lose the benefits of preloading. If this is true, it is unclear why a rel="preload" link would be given in the head for the WebM media type, and the presence of this link lends itself to misunderstanding of type attribute on links. If preload benefits would not be lost in this example for browsers that support WebM but not MP4, the section text is incorrect.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#including_a_mime_type

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/link_types/preload`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/link_types/preload/index.html
* Last commit: https://github.com/mdn/content/commit/788d0bae21eea799302841d3b38ae34ec0c355e3
* Document last modified: 2021-05-20T18:18:07.000Z

</details>

**Comment by GusBuonv** [comment]
It looks like the "full source code" link for the example does not have the rel="preload" link for the WebM source, while the code on the MDN page does contain this line. I still think it would be helpful to clarify whether or not preload links have fallback behavior for media types.

**Comment by sideshowbarker** [comment]
Howdy @yoavweiss — can you confirm what the actual behavior is here per the spec requirements?

**Comment by yoavweiss** [comment]
The example is indeed not great. Browsers that support both "webm" and "mp4" would preload both.
The "best practive" in this case would be to only preload the one more likely to be loaded by the majority of your users (in this case the "mp4", as it's defined first).

**Comment by sideshowbarker** [comment]
OK, I’ve opened https://github.com/mdn/content/pull/5749 with an update that I hope will help make things more clear.
