### ISSUE TITLE
Links Missing

### ISSUE THREAD

**Issue by NegiAkash890** [mdn/content#5362]
What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Howto

## Specific page section or heading?

Looping/iterating

## What is the problem?

The last four links in the Looping/iteration .

Screenshot :
![Screenshot from 2021-05-27 11-33-04](https://user-images.githubusercontent.com/55234838/119774158-636cef00-bedf-11eb-86f2-38d990cd8df7.png)

## What did you expect to see?

Links to navigate to the respective pages.

**Comment by sideshowbarker** [comment]
> I don't see any good links, so the options are to delete the items (if they are not useful)

I went with that option, and opened https://github.com/mdn/content/pull/5680 with a patch
