### ISSUE TITLE
Issue with "<label>": (short summary here please)

### ISSUE THREAD

**Issue by sina7518** [mdn/content#5363]
MDN URL: https://developer.mozilla.org/fr/docs/Web/HTML/Element/Label

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/html/element/label`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTML/Element/Label
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/html/element/label/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1afd214b4c6ed965b75ece5e8d75febad8bc7c07
* Document last modified: 2021-05-27T00:56:56.000Z

</details>

**Comment by teoli2003** [comment]
Hi! @sina7518!

Thank you for opening an issue. What is the problem with this page? 

You didn't give us any hint about what has to be corrected.

Thanks for your help!

**Comment by hamishwillee** [comment]
Closing due to insufficient information.
