### ISSUE TITLE
Issue with "String.prototype.slice()": Paragraph about endIndex needing to be greater than seems wrong

### ISSUE THREAD

**Issue by jasonwilliams** [mdn/content#5371]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice

#### What information was incorrect, unhelpful, or incomplete?

> If endIndex is specified, endIndex should be greater than beginIndex, otherwise an empty string is returned. (For example, slice(-3, 0), slice(-1, -3), or slice(3, 1) returns "".)

This doesn't sound correct to me and adds confusion.
`endindex` can be less than `beginIndex` when you want to use negative values to trim off the end. 

```js
const a = 'hello world'
a.slice(0, -6); // "hello"
```

In the above example we have a non-empty string returned.

#### What did you expect to see?

That last paragraph can be removed

#### Did you test this? If so, how?

Yes, above

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/slice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/slice/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by teoli2003** [comment]
Hi, @jasonwilliams !

Good catch! Thanks a lot, I opened a PR to get this fixed.
