### ISSUE TITLE
[Networking] Enable SHA 256 Digest Authentication

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#5374]
## Acceptance criteria

1. - [ ] The listed features are documented sufficiently on MDN
2. - [ ] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Enable SHA 256 Digest Authentication

## Related Gecko bugs
1. - [ ] [SHA 256 Digest Authentication](https://bugzilla.mozilla.org/show_bug.cgi?id=472823). Looks like a header addition of some kind, but needs investigation.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
This was backed out 7 days ago: https://bugzilla.mozilla.org/show_bug.cgi?id=472823
I'll mark this as Closed and cancelled.
