### ISSUE TITLE
[HTTP] Ship Sec-Fetch-* (Fetch Metadata Request Headers)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#5375]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Ship Sec-Fetch-* (Fetch Metadata Request Headers)

## Related Gecko bugs
1. - [x] [Ship Sec-Fetch-* (Fetch Metadata Request Headers)](https://bugzilla.mozilla.org/show_bug.cgi?id=1695911). Enabling of some headers by default. Need to investigate which ones, and see whether they have bene documented on MDN. If so, might just require BCD update. If not, there is a bit more work to do.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
Based on source linked from bug report, relevant HTTP header are: [Sec-Fetch-Site](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Site), [Sec-Fetch-Mode](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Mode), [Sec-Fetch-User](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-User),  [Sec-Fetch-Dest](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Dest)
Each will need an update, including example code, and BCD. Also addition to release notes. These are not hidden behind pref so no need to update the dev-doc completed.

Tracking
- [ ] [Sec-Fetch-Site](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Site)
  - [ ] Docs
  - [ ] BCD
- [ ] [Sec-Fetch-Mode](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Mode)
  - [ ] Docs
  - [ ] BCD
- [ ] [Sec-Fetch-User](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-User)
  - [ ] Docs
  - [ ] BCD
- [ ] [Sec-Fetch-Dest](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Dest)
  - [ ] Docs
  - [ ] BCD
- [ ] dev-docs-complete
- [ ] Release note

**Comment by hamishwillee** [comment]
This is mostly done. Waiting on the BCD and review of the first shot at docs. BCD may confirm this is no longer experimental, in which case will have to remove that tagging from the docs.

**Comment by hamishwillee** [comment]
OK, so BCD went in. Very last part of this fixed in #5746

**Comment by Rumyra** [comment]
Brill - thank you @hamishwillee !
