### ISSUE TITLE
[WebExt] Now able to use Cache API in WebExtensions

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#5378]
## Acceptance criteria

1. - [ ] The listed features are documented sufficiently on MDN
2. - [ ] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Now able to use Cache API in WebExtensions

## Related Gecko bugs
1. - [ ] [moz-extension:// schema is not considered secure for Cache Web API](https://bugzilla.mozilla.org/show_bug.cgi?id=1575625). Looks like a rel note is definitely needed to say that Cache API can now be used in WebExt, and what's changed. Not 100% sure if this is worth mentioned in Cache API docs, but it should probably be mentioned somewhere appropriate in the WebExt docs.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Rumyra** [comment]
- [ ] bcd
- [ ] update javascript api list in web extensions page and point to web api cache page
- [ ] at some point get someone to write web ext version of cache
