### ISSUE TITLE
[CSS] Support -webkit-image-set()

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#5379]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Support -webkit-image-set()

## Related Gecko bugs
1. - [ ] [Support -webkit-image-set()](https://bugzilla.mozilla.org/show_bug.cgi?id=1709415). Update [image-set()](https://developer.mozilla.org/en-US/docs/Web/CSS/image-set()) description and BCD to say that we are supporting the -webkit- version too, for compat purposes. Also add relnote.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by rachelandrew** [comment]
@Rumyra I think this is done pending merging of the linked PRs.

**Comment by Rumyra** [comment]
Thank you @rachelandrew 👍 - I think that BCD should be merged any moment, so closing this is imminent ☺️

**Comment by rachelandrew** [comment]
Closing as everything is merged.
