### ISSUE TITLE
[JS] Ergonomic brand checks for private class fields

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#5380]
## Acceptance criteria

1. - [ ] The listed features are documented sufficiently on MDN
2. - [x] [BCD is updated](https://github.com/mdn/browser-compat-data/pull/11042)
3. - [x] Interactive example and data repos are updated if appropriate - NA
4. - [ ] The content has been reviewed as needed

## Features to document

1. Ergonomic brand checks for private class fields

## Related Gecko bugs
1. - [x] [Implement Ergonomic brand checks](https://bugzilla.mozilla.org/show_bug.cgi?id=1648090). Document this, if it is not already documented, and add BCD. This is probably behind a pref, in which case put on Experimental features page, not rel notes.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
Research:
- Not documented on MDN
- [Spec Proposal: Ergonomic brand checks for Private Fields](https://github.com/tc39/proposal-private-fields-in-in#ergonomic-brand-checks-for-private-fields) - Spec proposal
- [Ergonomic Brand Checks will ship with Firefox 90](https://spidermonkey.dev/blog/2021/05/18/ergonomic-brand-checks.html) - info about this from bug fixer MatthewG. 
- [Chrome Tracking](https://www.chromestatus.com/feature/5006138707804160) - Chrome 91
- [Chromium: Intent to Ship: Ergonomic brand checks for private fields](https://groups.google.com/a/chromium.org/g/blink-dev/c/SO8zL3dvKsI/m/wMg-UGOUAgAJ) - google group

**Comment by meyerweb** [comment]
See https://github.com/mdn/browser-compat-data/pull/11042

**Comment by Rumyra** [comment]
After looking into this a bit further I think we probably need to update the `in` page _and_ the private fields reference and possibly guide as well. Which makes this a bigger task than I thought.

For the release on Tuesday we only need one of these places so we can link from the release notes. Maybe Private fields reference? Let me know your thoughts @hamishwillee I'm sure we can get something together before Tuesday and maybe pull out anything left over into a separate issue which I'll probably add to the 'content needed' project I'm creating 👍
