### ISSUE TITLE
[JS] dayPeriod support in Intl.DateTimeFormat

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#5382]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. dayPeriod support in Intl.DateTimeFormat

## Related Gecko bugs
1. - [x] [Enable dayPeriod support in Intl.DateTimeFormat](https://bugzilla.mozilla.org/show_bug.cgi?id=1645115). Looks like we already document dayPeriod ([see for example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts#description)), but rel note needs adding, and BCD updating.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
Status
- [ ] [BCD](https://github.com/mdn/browser-compat-data/pull/10807) - In progress:
- [ ] Release note
- [ ] Docs
  - In terms of docs it doesn't seem very complicated.  I did some basic testing and it isn't in seeming to change for different setting values, so just checking I am not missing anything in https://bugzilla.mozilla.org/show_bug.cgi?id=1645115#c8
  - Then possibly just a simple example in Might be worth adding another example in the [DateTimeFormat constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat).
- [ ] dev-docs-complete - not done yet
