### ISSUE TITLE
[WebAPI] Ship 2D Canvas createConicGradient()

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#5383]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [x] The content has been reviewed as needed

## Features to document

1. Ship 2D Canvas createConicGradient()

## Related Gecko bugs
1. - [ ] [Ship createConicGradient()](https://bugzilla.mozilla.org/show_bug.cgi?id=1711724). [Already documented](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createConicGradient), probably just needs rel note and BCD updating.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by Rumyra** [comment]
- [ ] Set dev-doc-complete
- [ ] Remove from experimental and add to release
