### ISSUE TITLE
[WebAPI] Zooming parity, WheelEvent.wheelDelta

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#5385]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated
3. - [x] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Zooming parity, WheelEvent.wheelDelta

## Related Gecko bugs
1. - [x] [Cannot zoom 3D Models with mouse wheel anymore](https://bugzilla.mozilla.org/show_bug.cgi?id=1708829). New WheelEvent.wheelDelta member to document, plus BCD, relnote, etc.

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
Status 
- not clear to me exactly what broke from the bug and hence what was fixed. I think it was [WheelEvent]() but clarifying in https://bugzilla.mozilla.org/show_bug.cgi?id=1708829#c15 
- Also did cleanup prior to "real" work for this in #5778
