### ISSUE TITLE
[HTTP] Remove ftp

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#5388]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated - Not required
3. - [x] Interactive example and data repos are updated if appropriate - Not required
4. - [x] The content has been reviewed as needed

## Features to document

1. ftp has been removed in FF90. Already [disabled in 88](https://github.com/mdn/content/issues/3462) so info here should be updated/removed to reflect

## Related Gecko bugs
1. - [x] [Remove FTP support](https://bugzilla.mozilla.org/show_bug.cgi?id=1574475).

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
Most of work for this done in #5485 
- Add removal in Release notes
- Remove the preference in Experimental features
- Remove the FTP option from the proxy settings.

I still have to do a BCD update.
