### ISSUE TITLE
Issue with "HTMLInputElement.setSelectionRange()": Typo/grammatical error.

### ISSUE THREAD

**Issue by Ben-Fenner** [mdn/content#5396]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange

#### What information was incorrect, unhelpful, or incomplete?
The description reads `Note that accordingly to the...` but grammatically it should read `Note that according to the...`.

#### Specific section or headline?
It is in the first section, above the `Syntax` section.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlinputelement/setselectionrange`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlinputelement/setselectionrange/index.html
* Last commit: https://github.com/mdn/content/commit/63c69f3c933acbea9bfb24d359a7d2ffdb3c0bea
* Document last modified: 2021-02-19T19:51:22.000Z

</details>

**Comment by Ben-Fenner** [comment]
I've created a PR for the fix. I hope I've done that properly.

**Comment by teoli2003** [comment]
Well done @Ben-Fenner ! Can you close this issue? (I can't)
