### ISSUE TITLE
Issue with "Element.tagName": (short summary here please)

### ISSUE THREAD

**Issue by evasyakin** [mdn/content#5414]
MDN URL: https://developer.mozilla.org/ru/docs/Web/API/Element/tagName

#### What information was incorrect, unhelpful, or incomplete?
Возвращает HTML-тег элемента ("div", "p", "a" и т.д).

#### Specific section or headline?
Описание

#### What did you expect to see?
Возвращает HTML-тег элемента в верхнем регистре ("DIV", "P", "A", "BODY" и т.д).

#### Did you test this? If so, how?
1. Браузер выдает имя тега в верхнем регистре
2. В самой статье ниже пример с верхним регистром

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/api/element/tagname`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/Element/tagName
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/api/element/tagname/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d92cc1c1695b3dad9a208412088189841c96af44
* Document last modified: 2021-05-27T14:49:31.000Z

</details>

**Comment by sideshowbarker** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
