### ISSUE TITLE
Issue with "The stacking context": (short summary here please)

### ISSUE THREAD

**Issue by james0r** [mdn/content#5419]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

#### What information was incorrect, unhelpful, or incomplete?
This tree is representing the arrangement of elements in the DOM tree correct? It wasn't, or still isn't, totally clear to me what hierarchy it's depicting.

#### Specific section or headline?
With respect to the hierarchy tree depicted below the example diagram.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_positioning/understanding_z_index/the_stacking_context`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_positioning/understanding_z_index/the_stacking_context/index.html
* Last commit: https://github.com/mdn/content/commit/70beea48a72c7dbc0d07e2a0dd9c9a95aa457d47
* Document last modified: 2021-03-26T23:17:12.000Z

</details>

**Comment by rachelandrew** [comment]
Hi @james0r Can you explain what you expected to see? I'm just not completely sure what you are reporting.

**Comment by james0r** [comment]
Help me if I’m not understanding it correctly.
> quote_type
> In this example, every positioned element creates its own stacking context, because of their positioning and z-index values. The hierarchy of stacking contexts is organized as follows:
>
This is to say, that because all elements create their own stacking context in the same way, the hierarchy of their stacking contexts is the same as their position in the DOM tree?

Maybe it was just confusing to me where the author chose to place the hierarchy. I guess the paragraph that follows clears up some confusion I had.

Anyways, feel free to disregard this. This may be no confusion at all to others.

Thank you.

James Auble
Web Developer
1-669-251-5012
***@***.***
www.jamesauble.com
