### ISSUE TITLE
Issue with "ascent-override": (short summary here please)

### ISSUE THREAD

**Issue by benNek** [mdn/content#5424]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/ascent-override

#### What information was incorrect, unhelpful, or incomplete?

Formal definition and formal syntax are not displayed properly

![Screenshot 2021-05-28 at 14 49 58](https://user-images.githubusercontent.com/10724694/119979915-38100000-bfc4-11eb-8787-e921f7d47df7.png)

#### Specific section or headline?

* Formal definition
* Formal syntax

#### What did you expect to see?

Not errors

#### Did you test this? If so, how?

Yes

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/@font-face/ascent-override`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/ascent-override
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@font-face/ascent-override/index.html
* Last commit: https://github.com/mdn/content/commit/775066d2fc8d1561d5da61983d137c1297899315
* Document last modified: 2021-05-08T09:57:47.000Z

</details>

**Comment by rachelandrew** [comment]
Hi @benNek the data for these has been merged so it should show up soon https://github.com/mdn/data/pull/485
