### ISSUE TITLE
[Markdown] Remove inline styles from Web/API docs

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#5438]
In preparation for moving to Markdown we'll need to remove inline styles from almost all elements in our documentation. I've done this for JS and am close for CSS.

This issue is to track the work to remove them for Web/API. I count 268 pages under https://developer.mozilla.org/en-US/docs/Web/API that use the `style` attribute. Proportionately this is less than CSS, but it's still enough that I'd be very happy to have people help out with the work.

So I have crafted a spreadsheet: https://docs.google.com/spreadsheets/d/1HSt5T4b2GAsHhrJiEFGugvFWR5EcujA1-6QlRKIa53o/edit?usp=sharing to coordinate things. If you think you might want to help, ask for editor access to the spreadsheet and also add a comment here so I know who you are. Please note though that this is unlikely to be a suitable "first task" on MDN, so it would be best for people who already have some experience contributing.

My experience with the CSS docs is that many of the changes are likely to be trivial (the style can just be removed) and some are much more involved. In Markdown-land we can keep some inline styles if we really have to: in particular, we're keeping complex tables in HTML, so they can continue to contain inline styles and things will still work. But even in these cases I'd prefer us to find alternatives if we can.

**Comment by hamishwillee** [comment]
Very happy to help with this (once I have finished the Firefox updates this week). I assume more important to you than Page macro fixes.

**Comment by wbamberg** [comment]
Thanks @hamishwillee , that would be most appreciated!

**Comment by Blakelist7** [comment]
@wbamberg sure, I would like to help on this. :)

**Comment by Blakelist7** [comment]
Hey, @wbamberg please grant edit access to the spreadsheet.

**Comment by wbamberg** [comment]
https://github.com/mdn/content/pull/8503 did the last bit of this, so this issue can be closed!
