### ISSUE TITLE
Issue with "FileSystemFlags.exclusive": does not successfully replace original file

### ISSUE THREAD

**Issue by wing-scud** [mdn/content#5457]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFlags/exclusive

#### What information was incorrect, unhelpful, or incomplete?
define `dirEntry` is type of  `FileSystemDirectoryEntry`;
the condition that is file: exist, when i use
```js
dirEntry.getFile(
  fileName,
  { create: true, exclusive: false },
  (fileEntry) => {
    console.log(fileEntry);
  }
);
```

i find this condition it cant create new file to cover origin file in this page api introduction;

#### What did you expect to see?
As the page says，when i use params ,it will cover origin file

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/filesystemflags/exclusive`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFlags/exclusive
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/filesystemflags/exclusive/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by Josh-Cena** [comment]
Apparently, if you look at https://wicg.github.io/entries-api/#api-directoryentry:

> If options’s [create](https://wicg.github.io/entries-api/#dom-filesystemflags-create) member is true, [invoke](https://webidl.spec.whatwg.org/#invoke-a-callback-function) errorCallback (if given) with a newly [created](https://webidl.spec.whatwg.org/#dfn-create-exception) "[SecurityError](https://webidl.spec.whatwg.org/#securityerror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException), and abort these steps.

It's never allowed to create files/directories using this API. Minimal test:

```html
<input id="foo" type="file" />
<script>
foo.addEventListener("change", (event) => {
  const dirEntry = event.target.webkitEntries[0];
  dirEntry.getFile(
    "foo.txt",
    { create: true, exclusive: false },
    console.log,
    console.error, // DOMException: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources.
  );
});
</script>
```

We probably need to document this.

**Comment by Josh-Cena** [comment]
It's already mentioned in https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryEntry/getFile (which the original document now redirects to):

> These options are currently not useful in Web contexts.

So we can consider it fixed I guess.
