### ISSUE TITLE
Issue with "Object.create()": (Inheriting class prototypes to the right place)

### ISSUE THREAD

**Issue by Walluri** [mdn/content#5458]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create

#### What information was incorrect, unhelpful, or incomplete?
Incorrect code : Object.assign(MyClass.prototype, OtherSuperClass.prototype);
Correct code : Object.assign(  Object.getPrototypeOf(MyClass.prototype), OtherSuperClass.prototype );
Why is it incorrect  : 
When we are inheriting certain member from OtherSuperClass into MyClass, The prototype of MyClass should not contain the members. 
#### Specific section or headline?
The example below the text : "If you wish to inherit from multiple objects, then mixins are a possibility."

#### What did you expect to see?
Correct code : Object.assign(  Object.getPrototypeOf(MyClass.prototype), OtherSuperClass.prototype );

#### Did you test this? If so, how?
Example with correct code:
function Shape() {
  this.x = 0;
  this.y = 0;
}
function AnotherShape() {
  this.z = 0;
}
Shape.prototype.moveShape = function (x, y) {
  this.x = this.x + x;
  this.y = this.y + y;
};
AnotherShape.prototype.moveAnotherShape = function (z) {
  this.z = this.z + z;
};

function Rectangle() {
  Shape.call(this);
  AnotherShape.call(this);
}

Rectangle.prototype = Object.create(Shape.prototype);
Object.assign(
  Object.getPrototypeOf(Rectangle.prototype),
  AnotherShape.prototype
);
Rectangle.prototype.constructor = Rectangle;
const re = new Rectangle();
console.log(re);

Output : 
Rectangle {x: 0, y: 0, z: 0}
x: 0
y: 0
z: 0
__proto__: Shape
	constructor: ƒ Rectangle()
	__proto__: 
		moveAnotherShape: ƒ (z)
		moveShape: ƒ (x, y)
		constructor: ƒ Shape()
		__proto__: Object
		
If you change the line to : Object.assign(Rectangle.prototype, AnotherShape.prototype);
Then the wrong output will be as below :
Rectangle {x: 0, y: 0, z: 0}
x: 0
y: 0
z: 0
__proto__: Shape
	constructor: ƒ Rectangle()
	moveAnotherShape: ƒ (z)
	__proto__:
		moveShape: ƒ (x, y)
		constructor: ƒ Shape()
		__proto__: Object		
Notice the place where the "moveAnotherShape" and "moveShape" are located.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/create`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/create/index.html
* Last commit: https://github.com/mdn/content/commit/3c394e62835ef7b443fb5208343ecba892bbf6d5
* Document last modified: 2021-05-26T11:36:38.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/5488 with a fix (and after that change is merged, this issue will automatically be marked resolved, and closed.)

**Comment by Walluri** [comment]
My Pleasure, Thank you.
I had to do a lot of testing before I bring it to your notice.
