### ISSUE TITLE
Issue with "504 Gateway Timeout": (short summary here please)

### ISSUE THREAD

**Issue by Philemon333** [mdn/content#5459]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status/504`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/504/index.html
* Last commit: https://github.com/mdn/content/commit/13a27d27cfae150a44b685edd266079e9d1eb32b
* Document last modified: 2021-05-26T16:16:02.000Z

</details>

**Comment by teoli2003** [comment]
Hi @Philemon333 ! Thanks for you report.

Unfortunately, you didn't tell us what the problem with this page is.

Can you please explain it?
