### ISSUE TITLE
Issue with "<main>": Contradictory info about role

### ISSUE THREAD

**Issue by nyuszika7h** [mdn/content#5461]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

#### What information was incorrect, unhelpful, or incomplete?
The example uses `<main role="main">`, and then later on the document goes on to say "Permitted ARIA roles: No role permitted".

#### Specific section or headline?
It's at the beginning.

#### What did you expect to see?
The tag probably shouldn't have `role="main"` if it's implicit anyway, or it should be clarified that it *is* allowed to explicitly specify it if that is the case.

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/main`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/main/index.html
* Last commit: https://github.com/mdn/content/commit/96dfdd88fdbe610088a25de6ab96445caa709f21
* Document last modified: 2021-04-23T15:48:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this. I’ve opened https://github.com/mdn/interactive-examples/pull/1836 with a fix (and after that change is merged, this issue will automatically get closed).
