### ISSUE TITLE
Issue with "Developer guides": wrong link target

### ISSUE THREAD

**Issue by vicasa** [mdn/content#5462]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide

#### What information was incorrect, unhelpful, or incomplete?
Link target on "Structuring the web with HTML" is wrong. It points to https://developer.mozilla.org/en-US/docs/Learn/JavaScript

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/guide`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/index.html
* Last commit: https://github.com/mdn/content/commit/2dce739e5dea42aa62ab7f714e895d392c32d303
* Document last modified: 2021-05-28T04:42:29.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/5486 with a fix (and after that change is merged, this issue will automatically get closed).
