### ISSUE TITLE
Issue with "Network request details": (short summary here please)

### ISSUE THREAD

**Issue by moshedolev** [mdn/content#5480]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details

#### What information was incorrect, unhelpful, or incomplete?
The screen shot in the section "Network request details" demonstrates the problem perfectly. It has the tabs:
Headers
Cookies
Request
Response
Timings
Security

NOTE: There is no "Params" tab in the screenshot. In the explanations it says that there is a "Params" tab, and explains what it does.
I need this tab. It is missing in my Firefox too.

#### Specific section or headline?

Network request details

#### What did you expect to see?

The "Params" tab. It is missing in the screenshot and in my firefox too.

#### Did you test this? If so, how?

Yes. The problem appears in my firefos too. Version 88.0.1 (64-bit) win10.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/network_monitor/request_details`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/network_monitor/request_details/index.html
* Last commit: https://github.com/mdn/content/commit/d079cee1a5aa020a6657017d2a53059e2581c0ac
* Document last modified: 2021-04-14T18:12:35.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. I’ve opened https://github.com/mdn/content/pull/5484 with a fix (and after that change is merged, this issue will automatically get closed).

**Comment by hamishwillee** [comment]
Note that the request and response tabs now show all the parameters, so you don't need this tab

**Comment by moshedolev** [comment]
Yes, but in POST requests, the request tab contains only the raw payload like this:

-----------------------------8429949821708741512766920304
Content-Disposition: form-data; name="discount_start_date"

29/05/2021
-----------------------------8429949821708741512766920304
Content-Disposition: form-data; name="discount_due_date"

05/01/2022
-----------------------------8429949821708741512766920304
Content-Disposition: form-data; name="discount_desc"

21.5
-----------------------------8429949821708741512766920304
Content-Disposition: form-data; name="discount_start_date_to_add"

31/05/2021

This is inconvenient to work with. I would expect to see something like:

Param1: Value1
Param2: Value2
Param3: Value3
...

It was like that in the good old firebug addon. I really miss it.
If you can bring this format back, I would be very grateful.

Thanks so much,

Moshe Dolev



Moshe Dolev
 
From: Hamish Willee
Date: 2021-05-31 02:57
To: mdn/content
CC: moshedolev; Author
Subject: Re: [mdn/content] Issue with "Network request details": (short summary here please) (#5480)
Note that the request and response tabs now show all the parameters, so you don't need this tab
