### ISSUE TITLE
Issue with "Asynchronous JavaScript": Incorrect objective in the async/await section

### ISSUE THREAD

**Issue by syed-jamal** [mdn/content#5481]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await

The objective reads "To understand promises and how to use them." which is the objective described in the promises section. I thought a more appropriate object would be "To understand the use of async/await keywords."

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/index.html
* Last commit: https://github.com/mdn/content/commit/2c6f017de416f5817a109191417d549c60e90055
* Document last modified: 2021-04-14T07:08:39.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — it’s now fixed in the sources, by https://github.com/mdn/content/pull/5483.
