### ISSUE TITLE
Issue with "Text": Unclear description of when multiple text nodes may be created

### ISSUE THREAD

**Issue by richardkazuomiller** [mdn/content#5487]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Text

#### What information was incorrect, unhelpful, or incomplete?

The documentation for text node says:

> New documents have a single Text node for each block of text. Over time, more Text nodes may be created as the document's content changes.

It's unclear whether this is something that the user "may" as in "is allowed to" do or if it is something a browser behavior that "may" as in "might" do as a result of changes to the document.

#### Specific section or headline?

The introduction part.

#### What did you expect to see?

If anyone knows more details about how and when multiple text nodes are created, it would be great to have that on this page.

#### Did you test this? If so, how?

No, I'm not sure if it's referring to a browser trigger that can be triggered somehow or something a user can do.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/text`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Text
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/text/index.html
* Last commit: https://github.com/mdn/content/commit/f2a9cd26197733d09c0547ce7d750c65ca59a812
* Document last modified: 2021-04-27T06:37:39.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. I’ve opened #7472 with a rewrite.
