### ISSUE TITLE
Issue with "HTML table advanced features and accessibility": (<th> element not properly marked up)

### ISSUE THREAD

**Issue by adham-omran** [mdn/content#5497]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced

#### What information was incorrect, unhelpful, or incomplete?
Text displaying <th> element showing as a normal text while it should be marked up as code like the rest of the document shows similar elements.

#### Specific section or headline?
The id and headers attributes; Bullet point 2.

#### What did you expect to see?
\<th\> marked up as code, `<th>`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/tables/advanced`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/tables/advanced/index.html
* Last commit: https://github.com/mdn/content/commit/3af43c1dcfb9be19c73cf3fdd1178db9c74aa064
* Document last modified: 2021-04-27T01:03:07.000Z

</details>

**Comment by teoli2003** [comment]
Thanks a lot, @adham-omran!

I have opened a PR to fix it.
