### ISSUE TITLE
Issue with "MediaKeySession": Still considered "Experimental"?

### ISSUE THREAD

**Issue by impressivewebs** [mdn/content#550]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaKeySession

#### What information was incorrect, unhelpful, or incomplete?
The intro has the "Experimental" warning at the top of the article.

#### What did you expect to see?
Can the warning be removed, since browser support is now everywhere but old IE?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediakeysession`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaKeySession
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/mediakeysession/index.html
* Report started: 2020-12-21T23:46:53.249Z

</details>

**Comment by impressivewebs** [comment]
Note: this would also apply to any of the sub-features, methods, properties, etc. that are under this API.

**Comment by sideshowbarker** [comment]
> Can the warning be removed, since browser support is now everywhere but old IE?

Yes — thanks for catching this. You want to raise a pull request for it yourself, or should I?

**Comment by impressivewebs** [comment]
[I just did here](https://github.com/mdn/content/pull/556). I'm assuming the line I removed is the one that adds the warning. I guess I have to do that for all the sub-features too?

**Comment by sideshowbarker** [comment]
> [I just did here](https://github.com/mdn/content/pull/556). I'm assuming the line I removed is the one that adds the warning.

Yes, but see my review comment there — you don’t want to remove the whole line; instead you should remove only the `{{SeeCompatTable}}` part, but preserve the `{{APIRef("EncryptedMediaExtensions")}}` part.

> I guess I have to do that for all the sub-features too?

Yup (though the comment above also applies to the files for all the other sub-features too: you want to only remove the `{{SeeCompatTable}}` part).

**Comment by impressivewebs** [comment]
Ok, I've just pushed through all the PRs for the different pages associated with that API to have those warnings removed. Thanks for your help.

**Comment by sideshowbarker** [comment]
> Ok, I've just pushed through all the PRs for the different pages associated with that API to have those warnings removed. Thanks for your help.

Cool — thanks, I’ll take a look. (For future reference, note that you can include more than one file change in a pull request; that is, these pull requests could also have been done as a single pull request.)

**Comment by impressivewebs** [comment]
Ah yeah, I probably should have done that. But I was doing it directly on the web which seemed faster for me, but I guess it would be less work on your end if I did it the other way. Sorry about that.

**Comment by sideshowbarker** [comment]
> Ah yeah, I probably should have done that. But I was doing it directly on the web which seemed faster for me,

aha — yeah, that make sense

> but I guess it would be less work on your end if I did it the other way. Sorry about that.

Don’t be sorry :) And don’t worry about making more work for reviewers — it’s not really more work in practice. And using the web UI is a perfectly fine way to get the changes made. GitHub should rightly let you batch up a set of changes to multiple files when you make the changes using the web UI; the fact that it doesn’t is kind of an unnecessary limitation that GitHub will hopefully get fixed eventually.

But in the meantime, you contributions are very welcome, however you make them. So for the future please don’t hesitate to use the web UI to submit patches/PRs, if that’s what works best for you.

**Comment by sideshowbarker** [comment]
Well, it seems I misspoke a bit in my earlier comment. After looking back at the project docs, I see now it’s already mentioned:

https://github.com/mdn/content#more-substantial-changes

> If you need to do some work that requires changes to more than one file, like moving one or more documents, the GitHub UI is not very efficient. You'd have to make a separate pull request for every page you want to change. Instead, you're going to have to use `git` or one of the other `git`-based approaches like the [GitHub Desktop](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/github-desktop).

So if you’re making changes to multiple files, it is in fact recommended that you avoid using the GitHub UI for that.
