### ISSUE TITLE
Issue with "Response.ok": (short summary here please)

### ISSUE THREAD

**Issue by Sarcares** [mdn/content#5501]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/ok

#### What information was incorrect, unhelpful, or incomplete?

`The response was successful (status in the range 200-299) or not.`

#### Specific section or headline?

Response.ok introduction.

#### What did you expect to see?

With HTTP code 304 the application returns true.

#### Did you test this? If so, how?

My React application prints "true" also with 304 HTTP response code.
Tested with a React application front-end and an Express server for the backend.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/response/ok`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/ok
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/response/ok/index.html
* Last commit: https://github.com/mdn/content/commit/272123183064168c2fb2d01aa716f59b4117a9a8
* Document last modified: 2021-04-08T14:56:34.000Z

</details>

**Comment by sideshowbarker** [comment]
Per spec at https://fetch.spec.whatwg.org/#dom-response-ok, for the `ok` property of `Response` objects:

> The ok getter steps are to return true if this’s response’s status is an ok status; otherwise false.

And per-spec at https://fetch.spec.whatwg.org/#ok-status:

> An ok status is a status in the range 200 to 299, inclusive

So I’m going to go ahead and close this, since the MDN article matches the spec. But if you have new information — for example, an actual test case demonstrating that the `ok` property of a `Response` object ever ends up being set to true for 304 response — then this could be revisited.

**Comment by Sarcares** [comment]
I'm attaching a screenshot. If you want to see the whole code, you can look at the repositories presented during our Web Applications course. In particular, I reproduced the example using the branches "with_auth" (they authenticate the application using passport), but you can also reproduce the error using the other branches.
React Score (react client): https://github.com/polito-WA1-AW1-2021/react-scores/tree/with_auth
React Score Server (express server): https://github.com/polito-WA1-AW1-2021/react-scores-server/tree/with_auth

![example](https://user-images.githubusercontent.com/9093937/120305679-58480380-c2d1-11eb-830c-f64e850ac6da.PNG)

As you can see in the picture, when my client (on the left side) asks my server (on the right side) the list of the "courses", the server answer 304 (because the list of courses is not changed). But my client has a true value inside "response.ok" and prints the statement "response is ok".
The same behavior also happens with the list of "exams" and with checking if the user is still logged in (in that case, the application prints in the console "The value of response is: true").

I hope to be clear and helpful.

**Comment by sideshowbarker** [comment]
OK I believe what goes on here is that when the response from the server is a 304, the browser doesn’t actually use that response as-is but instead uses the previously-cached response, and the response status from that cached response.

But it would be good to get confirmation from @annevk about that.

**Comment by annevk** [comment]
That's right.
