### ISSUE TITLE
Issue with "Location: href": Difference between navigation and redirection?

### ISSUE THREAD

**Issue by MikeRich88** [mdn/content#5523]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Location/href

#### What information was incorrect, unhelpful, or incomplete?
"Setting the value of href navigates to the provided URL. If you want redirection, use (some other thing)." - It would be helpful to explain what the difference between navigation and redirection is. Google results are not immediately helpful because Google is not very good for such queries.

#### Specific section or headline?
the top

#### What did you expect to see?
That the difference is explained, or at least links to what navigation and redirection are.

#### Did you test this? If so, how?
n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/location/href`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Location/href
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/location/href/index.html
* Last commit: https://github.com/mdn/content/commit/56d9a678477f0e79232caa8169114519bf02a44a
* Document last modified: 2021-02-19T19:41:18.000Z

</details>

**Comment by rbrishabh** [comment]
I can help with this!
