### ISSUE TITLE
Issue with "Document: keydown event": (example uses deprecated keyboard event)

### ISSUE THREAD

**Issue by janusheide** [mdn/content#5532]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event

#### What information was incorrect, unhelpful, or incomplete?

Use of deprecated "KeyboardEvent.keyCode" in example

#### Specific section or headline?

The first example

#### What did you expect to see?

use of key

#### Did you test this? If so, how?

no

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/keydown_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/keydown_event/index.html
* Last commit: https://github.com/mdn/content/commit/fffe339bce9adcb9ced09d1d5eff291c105ce6ad
* Document last modified: 2021-05-29T05:32:06.000Z

</details>

**Comment by hamishwillee** [comment]
This isn't a bug because to use an IME you have no choice but to use the Keycode (i.e. I don't think there is an alternative method to achieve the goal). I think it is a little confusing though, so I have moved this into examples and tried to make the context more clear.
