### ISSUE TITLE
Issue with "ShadowRoot.mode": (short summary here please)

### ISSUE THREAD

**Issue by MohammadMD1383** [mdn/content#5539]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/mode

#### What information was incorrect, unhelpful, or incomplete?
shadow root mode is read-only!

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/shadowroot/mode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/mode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/shadowroot/mode/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by teoli2003** [comment]
Thanks. I created a PR.

**Comment by MohammadMD1383** [comment]
hmmm... also here in the example
![image](https://user-images.githubusercontent.com/69088224/120417370-f8eeff80-c373-11eb-8b92-193f938fa016.png)
we cannot change the mode

**Comment by teoli2003** [comment]
Oh yes, you are right! Can you reopen this issue while we solved it? (I can't).

A new PR will follow quickly.

**Comment by teoli2003** [comment]
Hi! @MohammadMD1383,

I've created a new example, could you review it?

Thank you!

**Comment by MohammadMD1383** [comment]
✅👍
