### ISSUE TITLE
Issue with "WindowOrWorkerGlobalScope.fetch()": Incomplete description for `TypeError` 

### ISSUE THREAD

**Issue by chq-matteo** [mdn/content#5545]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch

#### What information was incorrect, unhelpful, or incomplete?

In the page about the `fetch` method, I think the description of the `TypeError` exception is incomplete.

At [https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#exceptions](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#exceptions) under `TypeError`

The description says:

```The specified URL string includes user credentials. This information should instead be provided using an Authorization header.```

#### Specific section or headline?

At [https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#exceptions](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#exceptions) under `TypeError`

Corresponding to these source lines on github [fetch/index.html#L149-L151](https://github.com/mdn/content/blob/main/files/en-us/web/api/windoworworkerglobalscope/fetch/index.html#L149-L151)

#### What did you expect to see?

I think that it would be useful to mention that `fetch` can reject with a `TypeError` due to a ill-formed request or a network error.

If I am reading it correctly, it is part of the spec [https://fetch.spec.whatwg.org/#fetch-method](https://fetch.spec.whatwg.org/#fetch-method):

at step `2` 
```
Let requestObject be the result of invoking the initial value of Request as constructor with input and init as arguments. If this throws an exception, reject p with it and return p.
```

and `12.3`
```
If response is a network error, then reject p with a TypeError and terminate these substeps.
```

Maybe something along these lines could work:

```
TypeError
    There are several reason fetch can be interrupted with a `TypeError`:
    - it was not possible to build a `Request` object with the provided parameters (e.g. malformed url)
    - the request was interrupted due to a network error 
    - ... other reasons for fetch to reject with TypeError ... 
```

#### Did you test this? If so, how?

In the developer console of `Microsoft Edge Version 91.0.864.37 (Official build) (64-bit)`

I made a `fetch` request to a `localhost` on a closed port and checked the rejection error

```
fetch("http://localhost:8080").catch(err => console.log(err));
```

With result

```
> TypeError: Failed to fetch
```

Then I made a fetch request to a malformed url
```
fetch("k2143rjhttp://localhost:9999/hello").catch(err => console.log(err))
```

With result

```
> TypeError: Failed to fetch
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/windoworworkerglobalscope/fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/windoworworkerglobalscope/fetch/index.html
* Last commit: https://github.com/mdn/content/commit/94c536f9b3a50303a85e7963a4ff4958d1aec382
* Document last modified: 2021-05-31T17:13:02.000Z

</details>

**Comment by SaurabhCha** [comment]
Hey,
Can I please work on this issue ? I would like to start my open source contribution journey.
Thanks

**Comment by sideshowbarker** [comment]
@SaurabhCha Thanks for speaking up — I’ve assigned the issue to you.

**Comment by SaurabhCha** [comment]
@sideshowbarker Thank you for giving me a chance.
I would like to add "If the response is a network error, then it rejects the promise with a TypeError.". I looked into the error and after searching and experimenting I found its a valid reason for a fetch API to give TypeError.
Please suggest if you think I need to search more. If you think, this resolves the bug, I will commit the change and send a PR.

**Comment by sideshowbarker** [comment]
@SaurabhCha Please go ahead and open the PR

**Comment by singla-shivam** [comment]
@sideshowbarker I would like to work on this issue.

**Comment by sideshowbarker** [comment]
@singla-shivam Thanks — now assigned

**Comment by singla-shivam** [comment]
@sideshowbarker I find number of possible reasons in the spec due to which `TypeError` can be thrown. That would require examples too. How to list them? Ordered/unordered list, or table or something else? Could you please send an example link where something similar is already done?

**Comment by singla-shivam** [comment]
There are other possible places to describe all these reasons for the errors. For example-
https://developer.mozilla.org/en-US/docs/Web/API/Request/Request#errors
https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers

**Comment by singla-shivam** [comment]
>How to list them? Ordered/unordered list, or table or something else?

@sideshowbarker please guide what to do.

**Comment by sideshowbarker** [comment]
> @sideshowbarker please guide what to do.

If you put together a pull request, I would be happy to review that. If you need guidance on what decisions to make in order to put together the pull request, I’m sorry, but I don’t have any particular guidance to give about that.

> @sideshowbarker I find number of possible reasons in the spec due to which `TypeError` can be thrown. That would require examples too. How to list them? Ordered/unordered list, or table or something else? Could you please send an example link where something similar is already done?

Doing that part of the work — evaluating the various options and then making one’s own decisions and choices about what to do, and looking for precedents/examples in existing MDN content — is often what’s the most time-consuming part of coming up with a patch/pull-request for an issue. And doing that work on one’s own is what agreeing to work on an issue requires.
