### ISSUE TITLE
Issue with "Using the log role": Broken link

### ISSUE THREAD

**Issue by zackhall** [mdn/content#5550]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_log_role

#### What information was incorrect, unhelpful, or incomplete?

The working example link is broken.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/aria_techniques/using_the_log_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_log_role
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/aria_techniques/using_the_log_role/index.html
* Last commit: https://github.com/mdn/content/commit/72e0d271f16ce9d0c4389b9f525fa81e6df9c5f5
* Document last modified: 2021-02-19T18:53:08.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I spent some time looking for another site that had a working example of role=log but unfortunately I didn’t manage to find anything suitable — so I opened https://github.com/mdn/content/pull/5679 with a change that just drops the link.
