### ISSUE TITLE
Issue with "clearTimeout()": Can failure be detected?

### ISSUE THREAD

**Issue by David263** [mdn/content#5553]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/clearTimeout

#### What information was incorrect, unhelpful, or incomplete?
The page says nothing about what happens if clearTimeout is too late, and fails to deactivate a setTimeout operation. In fact, it implies that failure to clear cannot be detected.

#### Specific section or headline?
Notes 
#### What did you expect to see?
Usually when clearTimeout is issued, the setTimeout function is still in progress. However, there are race conditions where setTimeout is ending just as clearTimeout is issued. If setTimeout has just ended, but not yet been detected or handled, one may want clearTimeout to detect this as an error, but the MDN documentation is unclear as to whether this is possible or not. This can be an important error condition during asynchronous operations where setTimeout is used. Data loss or worse can result if we rely on clearTimeout to prevent a timeout in the rare case when the timeout has just happened, since this case cannot be detected either before or after the call to clearTimeout.

Of course, we can detect that setTimeout resolved much later, and so can eventually know that a call to clearTimeout failed, but only if we know to test for this unusual case. Either way, the documentation could be more helpful.

#### Did you test this? If so, how?
Asynchronous race conditions hurt my head, and can be very rare, and so I don't know how to test for them.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/windoworworkerglobalscope/cleartimeout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/clearTimeout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/windoworworkerglobalscope/cleartimeout/index.html
* Last commit: https://github.com/mdn/content/commit/94c536f9b3a50303a85e7963a4ff4958d1aec382
* Document last modified: 2021-05-31T17:13:02.000Z

</details>

**Comment by jpmedley** [comment]
I'm not sure how we proceed, but I notice that the spec doesn't specify an algorithm, so this may vary by browser. I tried going [through Chromium's code](https://source.chromium.org/chromium). It looks like a race condition is possible in Chromium forks, but my C++ is way rusty.

**Comment by David263** [comment]
If you don't see a synchronization call, such as a lock, mutex, or semaphore, you can pretty much assume the possibility of a race condition. The classical example is reading data, making a decision based on the value of the data, then writing the same data again. If we ignore race conditions, we assume that these three operations are all happening in one synchronous operation. But in the presence of asynchronous processes of any kind, the data can change immediately after it has been read. In such a case, the decision and the writing are both incorrect and data loss is likely.

**Comment by jpmedley** [comment]
I've pinged a couple of Chrome engineers who work in this area. I should probably find someone who can help test this on various platforms, but I'm actually curious about the spec situation. Sometimes raising issues like this leads to a refinement of the spec, which would be ideal here since it would ensure interoperability.

**Comment by David263** [comment]
Testing for race conditions cannot be done by external tests, since they are low-probability events. You have to actually instrument a copy of the code to make it misbehave in coordination with your testing program. Then you actually create a race condition reliably and see what really happens. As I said, this is well beyond my level of experience, as I am a simple PHP and JavaScript programmer.

**Comment by RubenArtmann** [comment]
> Testing for race conditions cannot be done by external tests, since they are low-probability events. 

shouldn't this always trigger the race if it existed?
```js
let timeouts = [];
const diffuse = ()=>{
	console.log("diffuse");
	for(let i=0; i<timeouts.length; i++) {
		if(!timeouts[i].triggered) {
			timeouts[i].diffused = true;
			clearTimeout(timeouts[i].id);
		}
	}
};
for(let i=0; i<10000; i++) {
	let timeout = {
		triggered: false,
		diffused: false,
		id: 0
 	};
	timeout.id = setTimeout(()=>{
		console.log(i);
		if(timeout.diffused) alert("race");
		timeout.triggered = true;
		
		// trigger somewhere inbetween
		if(i===100) {
			// block so timeouts could be scheduled off-main-thread/event-loop
			// if they ever were going to be
			for(let i=0; i<10000000; i++) {}
			diffuse();
		}
	},1)
	timeouts.push(timeout);
}
```
both firefox and chrome don't trigger the race condition.



https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timer-nesting-level
> 16. Wait until any invocations of this algorithm that had the same method context, that started before this one, and whose timeout is equal to or less than this one's, have completed.

> 18. Queue a global task on the timer task source given method context to run task.

seeing that all timeouts trigger in the order they were created in, makes me believe there is nothing off-main-thread/event-loop going on with timeouts in the first place.

**Comment by David263** [comment]
A very clever test program!

I changed "diffuse" (I think you meant "defuse") to "clearAll", and "diffused" (I think you meant "defused") to "cleared", and then the code started making sense. But I don't think you are testing for the same race condition. You seem to be testing for clearTimeout happening after setTimeout while you are blocking the event loop by doing a for loop. I'm not surprised that that doesn't happen.

The question remains: is it possible that clearTimeout will fail to prevent a setTimeout from completing if it happens right as the setTimeout is already completing?

It may well be that this situation is the same as simply doing a clearTimeout on a timeout that has already completed.

The point of this posting is that if clearTimeout fails, the program will need to know this if it is counting on clearTimeout preventing setTimeout from completing. So clearTimeout needs to return an error code of some sort to indicate that the setTimeout for this id has already completed. I think this makes sense. Does it make sense to you?

**Comment by RubenArtmann** [comment]
> setTimeout is already completing

what do you mean  with this?
the call to register the timeout itself running ```setTimeout(callback, 0)```
or the callback executing ```const = callback = ()=>{console.log("callback executing"});```?

> if it happens right as the setTimeout is already completing

either way, since these are pieces of javascript code executing on the event-loop/main-thread, no other javascript can execute "right as it is completing" only either before or after. If you do not understand why this is the case please look up the javascript [Eventloop](https://youtu.be/cCOL7MC4Pl0?t=139) and [why/how javascript is singlethreaded](https://stackoverflow.com/questions/21718774/how-is-javascript-single-threaded). 





> You seem to be testing for clearTimeout happening after setTimeout while you are blocking the event loop by doing a for loop

after the first setTimeout callbacks, but before all others, which are the ones actually being tested

my code tries to show what happens when:
> setTimeout has just ended, but not yet been detected or handled

it works by setting a lot of timeouts with the same delay,
then waiting for the first few to complete,
then waiting in a busy loop to make sure all timeouts should have "ended"
then call clearTimeout on all of them, 
which results in them being cancelled correctly with no "failure to clear"

meaning, that this is guaranteed to work:
```js
let executed = false;
let timeout = setTimeout(()=>{
  executed = true;
  // do your stuff
},100);
const clear = ()=>{
  clearTimeout(timeout);
  // return true it if succesfully prevented the timeout from running
  return !executed;
}
```

**Comment by David263** [comment]
Clearly, you have thought about this question much more deeply than I. I understand your point that using clearTimeout at a time when setTimeout is known not to have completed cannot fail, because the timeout event must wait for the next event loop iteration.

So I would change this issue to a request that the page explain that if a setTimeout is in progress, a clearTimeout for the same timeout is guaranteed to succeed, since any timeout event must wait for the next event loop iteration. Have I got that right?

Thank you for your experiment and your insight.

**Comment by RubenArtmann** [comment]
> Have I got that right?

Yes, but i haven't read the spec enough to know if it actually guarantees this behavior. (Though anything else would be insanity)

**Comment by Josh-Cena** [comment]
This is just about the understanding of JavaScript execution in general. There's no state where "setTimeout is ending just as clearTimeout is issued":

- Either `clearTimeout` is issued before `setTimeout` fires, in which case the callback never gets called
- Or the `setTimeout` has fired and the callback is scheduled, in which case `clearTimeout` does nothing.

"JavaScript cannot execute two functions at the same time" is the simple answer.
