### ISSUE TITLE
Convert `event` macro calls to normal links

### ISSUE THREAD

**Issue by escattone** [mdn/content#5555]
> FWIW I probably would have fixed by putting in a normal link. The Event macro isn't very useful because there aren't many documents under the events tree any more (events live under their parent element). So it made sense to me that we might consider deleting the macro.
> 
> This is still much better of course, but something to think about :-)

@hamishwillee Good points! For the English docs, I'll change these from:

```
event("Event_handlers", "event handler")
```

to:

```
<a href="/en-US/docs/Web/Events/Event_handlers">event handler</a>
```

and I guess for each of the non-English locales in mdn/translated-content use that locale instead of `en-US` as long as the document exists in that locale.

_Originally posted by @escattone in https://github.com/mdn/content/issues/5442#issuecomment-852472272_

**Comment by escattone** [comment]
cc @wbamberg

**Comment by SphinxKnight** [comment]
If I may: I'd be inclined to use the `/<locale>/` even if the target document does not exist in the locale. If that the case, the English document will be served as a fallback. And whenever the target page gets translated there is then no need to look for all the existing `/en-US/` links for this particular page under the `<locale>` tree.

**Comment by hamishwillee** [comment]
This is closed by https://github.com/mdn/content/pull/6785

@escattone Should we/can we removed the Event macro from yari? It simply isn't needed anymore.

**Comment by hamishwillee** [comment]
Might be worth doing a check. I _think_ you'll find that other than `event("Event_handlers")` the macro has already been replaced with explicit links (at least in the English version)

**Comment by teoli2003** [comment]
`rg "\{event" | wc -l` returns 1471 files with the macro (on en-US).

**Comment by Josh-Cena** [comment]
We don't have any occurrences of `\{\{ *event` left.
