### ISSUE TITLE
Content bug: Need (cross/same) origin vs site topic

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#5557]
MDN has information on what origin means but there is no real clear comparison of origin and site, and the details around that - e.g. things like eTLD+1 ("when something looks like a subdomain but isn't"). It would be good to have a canonical topic on this linked from everywhere. Something like https://web.dev/same-site-same-origin/ 

This might be linked from many many places, but starting at https://github.com/mdn/content/pull/5499/files#r642922338

MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP

**Comment by wbamberg** [comment]
We have https://developer.mozilla.org/en-US/docs/Glossary/Site now, which covers some of this ground (especially eTLD+1, schemeful/schemeless), but doesn't include a direct comparison between origin and site. Do you think that's also needed? I'm not sure where would be best for this.

**Comment by hamishwillee** [comment]
Given we also have a glossary for Origin and most of the time you link one or the other for the precise meaning I no longer think it is worth a whole comparative topic.
But I do think it wouldn't hurt to capture the difference in one of the glossary topics to highlight that there is a difference.

How about #30000 (something quite satisfying about a round numbered issue!)
