### ISSUE TITLE
Issue with "Tutorial Django Parte 3: Usando models": (short summary here please)

### ISSUE THREAD

**Issue by IveTou** [mdn/content#5558]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/Server-side/Django/Models

#### Specific section or headline?

The issue is in the pt-BR translated version where points ''Uma vez que você tenha escolhido qual banco será utilizado você precisa conversar diretamente com ele"

#### What did you expect to see?

"Uma vez que você tenha escolhido qual banco será utilizado você não precisa conversar diretamente com ele"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/learn/server-side/django/models`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/Server-side/Django/Models
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/learn/server-side/django/models/index.html
* Last commit: https://github.com/mdn/translated-content/commit/0f8f6f360cbbbf19bd60f14974b710faad611fc4
* Document last modified: 2021-06-01T01:52:39.000Z

</details>

**Comment by himanshugarg** [comment]
The line is no more and apparently replaced by -

> Uma vez que você tenha escolhido qual banco será utilizado você precisa conversar diretamente com ele - você somente escreve a estrutura do seu modelo e outros códigos, e o Django faz todo o trabalho sujo de comunicação com o banco para você.

Which google translates back to 
> Once you've chosen which database to use you need to talk to it directly - you just write your model structure and other code, and Django does all the dirty work of communicating with the database for you. 

So no changes required here.

**Comment by sideshowbarker** [comment]
Thanks @himanshugarg. Closing per https://github.com/mdn/content/issues/5558#issuecomment-912942914

But also, even if the text were still in the article, we don’t currently have an mechanism for updating any of the pt-BR content.

https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
