### ISSUE TITLE
Issue with "JavaScript": (short summary here please)

### ISSUE THREAD

**Issue by Hui123220** [mdn/content#5571]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Glossary/JavaScript

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/glossary/javascript`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Glossary/JavaScript
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/glossary/javascript/index.html
* Last commit: https://github.com/mdn/translated-content/commit/0f8f6f360cbbbf19bd60f14974b710faad611fc4
* Document last modified: 2021-06-01T01:52:39.000Z

</details>

**Comment by hamishwillee** [comment]
Closing as there is not enough information provided to understand the problem.
