### ISSUE TITLE
Issue with "DataView.prototype.byteLength": (short summary here please)

### ISSUE THREAD

**Issue by RedBeard0531** [mdn/content#5583]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/byteLength

#### What information was incorrect, unhelpful, or incomplete?
This is incorrect:

> The byteLength accessor property represents the length (in bytes) of this view **from the start of its ArrayBuffer or SharedArrayBuffer**.

(emphasis mine)

#### Specific section or headline?

intro

#### What did you expect to see?

Something like 

> The byteLength accessor property represents the length (in bytes) of this view from the start of its <ins>`byteOffset` into the</ins> ArrayBuffer or SharedArrayBuffer.

Or you could simply go for the minimalism of [TypedArray.prototype.byteLength](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/byteLength):

> The byteLength accessor property represents the length (in bytes) of a <del>typed array</del><ins>data view</ins>.

(As a minor grammar nit, I feel like the sentence should be using the definitive article: "of **the** typed array", but that should probably change in both places for consistency)

#### Did you test this? If so, how?

`new DataView(new ArrayBuffer(10), 5, 1).byteLength` is 1. If the description was accurate, it would be 6 (ie, including the 5 bytes of offset "from the start of its ArrayBuffer".)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/dataview/bytelength`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/byteLength
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/dataview/bytelength/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/5675 with a fix.
