### ISSUE TITLE
Issue with "Django Tutorial Part 6: Generic list and detail vi…": (short summary here please)

### ISSUE THREAD

**Issue by ayush458pandey** [mdn/content#5593]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views

#### What information was incorrect, unhelpful, or incomplete?
\locallibrary\catalog\urls.py", line 8, in <module>
    path('books/', views.BookListView.as_view(),name='books'), 
AttributeError: module 'catalog.views' has no attribute 'BookListView'
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/generic_views`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/generic_views/index.html
* Last commit: https://github.com/mdn/content/commit/16f66c643c9aa67a7839925d261f8c2775f0305b
* Document last modified: 2021-05-14T07:57:34.000Z

</details>

**Comment by hamishwillee** [comment]
The view is added in an earlier step on this page, so it definitely exists: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views#views

Further, this works for me (I don't get this error). The best thing to do is compare your project to the finished version: https://github.com/mdn/django-locallibrary-tutorial/blob/master/catalog/urls.py#L8

I suspect you just haven't added that class.
