### ISSUE TITLE
Issue with "Bitwise NOT (~)": Examples use int16 instead of int32

### ISSUE THREAD

**Issue by pinksynth** [mdn/content#5599]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_NOT

#### What information was incorrect, unhelpful, or incomplete?
The examples refer to `-3` as `1111111111111101`, which is valid for 16-bit signed integers, but not for 32-bit signed integers, which is what the operator (and the rest of the article) uses. Using 32 bit integers, `1111111111111101` is 65,533.

I would be happy to open a PR for this.

#### Specific section or headline?
"JavaScript Demo: Expressions - Bitwise NOT"

#### What did you expect to see?
The binary examples here should be 32 bits (`11111111111111111111111111111101`) instead of 16 bits (`1111111111111101`). Additionally, it would be helpful for beginners to include a link to something describing the "two's complement" going on here, which is a barrier for understanding this and other bitwise operators.

#### Did you test this? If so, how?
Not really "testable", but here's the specification for the bitwise "NOT" operand being converted to Int32.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/bitwise_not`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_NOT
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/bitwise_not/index.html
* Last commit: https://github.com/mdn/content/commit/f15c1b87b30b35be40d331632bd1c1dae5deafab
* Document last modified: 2021-05-28T04:44:16.000Z

</details>

**Comment by sideshowbarker** [comment]
Keeping this open until https://github.com/mdn/interactive-examples/pull/1839 is merged

**Comment by teoli2003** [comment]
Ping @sideshowbarker :-) (I can't close it myself :-) )

**Comment by sideshowbarker** [comment]
I
