### ISSUE TITLE
Issue with "Шаблоны": Live sample iframe returns 404

### ISSUE THREAD

**Issue by vrizo** [mdn/content#5618]
MDN URL: https://developer.mozilla.org/ru/docs/Web/SVG/Tutorial/Patterns

#### What information was incorrect, unhelpful, or incomplete?
The article is amazing but the Live sample refers to the [demos.prod.mdn.mozit.cloud](https://yari-demos.prod.mdn.mozit.cloud/ru/docs/Web/SVG/Tutorial/Patterns/_sample_.Patterns.html) page which returns 404

#### Specific section or headline?
The Screenshot/Live sample comparison table section after the source example in the [Шаблоны (Patterns)](https://developer.mozilla.org/ru/docs/Web/SVG/Tutorial/Patterns#%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D1%8B_patterns) section

#### What did you expect to see?
Working Live sample iframe

#### Did you test this? If so, how?
I opened the iframe source URL in a new tab and received `Sorry, the page /ru/docs/Web/SVG/Tutorial/Patterns/_sample_.Patterns.html could not be found.`

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/svg/tutorial/patterns`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/SVG/Tutorial/Patterns
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/svg/tutorial/patterns/index.html
* Last commit: https://github.com/mdn/translated-content/commit/3abeb963b17548b415a013a43aa1f4284541b8bb
* Document last modified: 2021-06-02T02:00:22.000Z

</details>

**Comment by dorward** [comment]
As well as being a 404, it also rejects the iframe in the same way as this issue: https://github.com/mdn/content/issues/5541

**Comment by sideshowbarker** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
