### ISSUE TITLE
Content bug: use of "bubbles through" to describe event firing is inaccurate

### ISSUE THREAD

**Issue by foolip** [mdn/content#5620]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Worker#properties
https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker#properties
https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/onmessage
https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/onerror

And other pages, search for "bubbles through" to find them all.

## What is the problem?

In this context, speaking of event bubbling isn't accurate. Events bubble in the DOM, upwards in the node hierarchy, in cases like the "click" event. In the cases linked, there is no hierarchy, the events are just fired directly at some object and that's that.

Possibly the notion here was that something happens in the worker and then an event is fired on the `Worker` object in the main thread, and that this is bubbling. That's not really correct though, and might confuse developers about what bubbling is.

## What did you expect to see?

Maybe just say "event occurs" without the bubbling bit.

**Comment by sideshowbarker** [comment]
Raised https://github.com/mdn/content/pull/5667 with fixes — please review
