### ISSUE TITLE
Issue with "Window.devicePixelRatio": code block is not ended properly

### ISSUE THREAD

**Issue by pcmill** [mdn/content#5625]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

#### What information was incorrect, unhelpful, or incomplete?
The last code block seems to be broken. It now says: "If you're able to see this, something went wrong on this page".

#### Specific section or headline?
The code below "Monitoring screen resolution or zoom level changes".

#### What did you expect to see?
A browser compatibility table.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/devicepixelratio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/devicepixelratio/index.html
* Last commit: https://github.com/mdn/content/commit/94c536f9b3a50303a85e7963a4ff4958d1aec382
* Document last modified: 2021-05-31T17:13:02.000Z

</details>

**Comment by teoli2003** [comment]
Thank you for reporting this, @pcmill
