### ISSUE TITLE
Issue with "<object>": tabindex isn’t deprecated

### ISSUE THREAD

**Issue by da2x** [mdn/content#5644]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object

#### What information was incorrect, unhelpful, or incomplete?
tabindex is a global attribute and isn’t deprecated.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object#attr-tabindex

#### What did you expect to see?
No deprecation icon next to the global tabindex attribute.

#### Did you test this? If so, how?
https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-object-element

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/object`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/object/index.html
* Last commit: https://github.com/mdn/content/commit/8d28de329fc4f723ad4362f0f703e46c4fa9e32d
* Document last modified: 2021-06-02T17:52:41.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/5666 with a fix.
