### ISSUE TITLE
Issue with "Number": "Unknown specifications" link title for ECMA262

### ISSUE THREAD

**Issue by criesbeck** [mdn/content#5645]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number

#### What information was incorrect, unhelpful, or incomplete?

The link for the ECMA 262 draft is titled "Unknown specifications". This is true on every JavaScript page with links to that standard I think.

#### Specific section or headline?

Specifications

#### What did you expect to see?

The title of the Draft ECMA 262 standard

#### Did you test this? If so, how?

Opened the page in Chrome 90.0 and Firefox 89.0 on MacOS Catalina and went to

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#specifications

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/number`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/number/index.html
* Last commit: https://github.com/mdn/content/commit/3c394e62835ef7b443fb5208343ecba892bbf6d5
* Document last modified: 2021-05-26T11:36:38.000Z

</details>

**Comment by Elchi3** [comment]
Thanks for your report! This will be fixed with a new release of https://github.com/mdn/browser-compat-data which should happen in the next few hours.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/5645#issuecomment-854365952 as this is expected to be fixed later today. If it’s not fixed as expected, we can revisit this.
