### ISSUE TITLE
Issue with "Strict mode": explicitly state ES6 classes are always in strict mode

### ISSUE THREAD

**Issue by jxu** [mdn/content#5647]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

#### What information was incorrect, unhelpful, or incomplete?

Strict mode page should include note that ES6 classes are always in strict mode. https://262.ecma-international.org/6.0/#sec-strict-mode-code 

#### Specific section or headline?

Probably an addition in section "Strict mode for modules"

#### What did you expect to see?

"ES6 classes are always in strict mode."

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/strict_mode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/strict_mode/index.html
* Last commit: https://github.com/mdn/content/commit/179e7d3a709f897d33ac9b833d9caff99f7396a3
* Document last modified: 2021-05-05T16:43:40.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5665 with a fix
