### ISSUE TITLE
Issue with "Storage Inspector": (short summary here please)

### ISSUE THREAD

**Issue by omerta6969** [mdn/content#5649]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/storage_inspector`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/storage_inspector/index.html
* Last commit: https://github.com/mdn/content/commit/e0a36d636574e8b25492026c064e39762bc36716
* Document last modified: 2021-02-10T18:03:04.000Z

</details>

**Comment by hamishwillee** [comment]
Closing. @omerta6969 is a timewaster.
