### ISSUE TITLE
Issue with "Function.name": The section "Function constructor name" got the wrong example code

### ISSUE THREAD

**Issue by andykao1213** [mdn/content#5653]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

#### What information was incorrect, unhelpful, or incomplete?
In the section [Function constructor name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name#function_constructor_name), the description says that the name property of `new Function(...)` or `Function(...)` should be anonymous. However, the sample code didn't trigger the `Function`. The result is an anonymous function instead of the expected result `"anonymous"`.

#### Specific section or headline?
[Function constructor name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name#function_constructor_name)

#### What did you expect to see?
The example code should be
```js
(new Function()).name
```

#### Did you test this? If so, how?
I've been testing it in the dev tool's console. `(new Function()).name` will return 'anonymous'

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/function/name`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/function/name/index.html
* Last commit: https://github.com/mdn/content/commit/3c394e62835ef7b443fb5208343ecba892bbf6d5
* Document last modified: 2021-05-26T11:36:38.000Z

</details>

**Comment by Andrew-Cottrell** [comment]
Please clarify; are you saying there is a difference between the following expressions?

- `(new Function).name`
- `(new Function()).name`

In my testing both evaluate to `"anonymous"`. The argument list is optional when using the [`new`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new#description) operator.

> `new Foo` is equivalent to `new Foo()`, i.e. if no argument list is specified, `Foo` is called without arguments.

**Comment by andykao1213** [comment]
Hi @Andrew-Cottrell. I found that it's the issue with my chrome extension. `(new Function).name` works expectedly in incognito mode. Sorry for the wrong issue. I'll close it. Thank you!
