### ISSUE TITLE
Issue with "Sintaxe e tipos": Data Types Outdated.

### ISSUE THREAD

**Issue by Igor-MPereira** [mdn/content#5662]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Grammar_and_types

#### What information was incorrect, unhelpful, or incomplete?
The Information On Data structures and types is outdated on portuguese translation, containing 6 primitives and object, being 7 primitives and object. the section is missing the BigInt primitive type.

#### Specific section or headline?
[Data structures and types - Data types](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#data_structures_and_types)

#### What did you expect to see?
All 7 primitive data types and object.

#### Did you test this? If so, how?
By checking the en-US version and using typeof BigInt(1).

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/web/javascript/guide/grammar_and_types`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Grammar_and_types
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/javascript/guide/grammar_and_types/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d5f6dd6b7f6653facfb468516ef657a2d4d5180c
* Document last modified: 2021-06-03T01:40:04.000Z

</details>

**Comment by sideshowbarker** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
