### ISSUE TITLE
Content bug: Network Monitor not "all network requests"

### ISSUE THREAD

**Issue by irvnriir** [mdn/content#5663]
[files/en-us/tools/network_monitor/index.html](https://github.com/mdn/content/blob/main/files/en-us/tools/network_monitor/index.html)

## What is the problem?

When it shows nothing, my traffic management show that Firefox constantly exchange data with the net .
(proves the article's statement wrong)

( Network Request can be a TCP connection request and other )

Its also expected that Network Monitor will show all traffic when it runs in Browser Toolbox .

**Comment by irvnriir** [comment]
Was it meant HTTP requests -- https://www.w3schools.com/tags/ref_httpmethods.asp ?

**Comment by himanshugarg** [comment]
Thanks @irvnriir . In your report, could you please include examples/screenshots where you see a mismatch. The Network Monitor does indeed show all HTTP requests made.

**Comment by irvnriir** [comment]
@himanshugarg if it shows only HTTP requests [*](https://github.com/mdn/content/issues/5663#issuecomment-854463367), than the article should be edited .
> ( "network request" can be a TCP connection request and other )
