### ISSUE TITLE
Issue with "display": (Defined as discrete, but is not animatable)

### ISSUE THREAD

**Issue by omalinov** [mdn/content#5672]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/display

#### What information was incorrect, unhelpful, or incomplete?

Display is noted as discretely animatable, however it is not animatable.

#### Specific section or headline?

Formal definition/Animation type

#### What did you expect to see?

I expected the animation type to be "not animatable".

#### Did you test this? If so, how?

With the following page https://codesandbox.io/s/summer-cdn-enns6?file=/index.html

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/display`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/display
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/display/index.html
* Last commit: https://github.com/mdn/content/commit/4c02f1d388bcb4a513dbdeebb19c735bbfa96251
* Document last modified: 2021-05-26T12:38:08.000Z

</details>

**Comment by teoli2003** [comment]
Good catch!

I've opened a PR in the repo where this has to be fixed. I also double checked in the spec that confirms your experiment.

Thanks a lot!
