### ISSUE TITLE
Issue with "Object.getOwnPropertyDescriptors()": (Improved comment for better understanding when creating a sub class)

### ISSUE THREAD

**Issue by Walluri** [mdn/content#5683]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors

#### What information was incorrect, unhelpful, or incomplete?
Incomplete: The comment was incomplete, it is easy to miss adding the constructor property as we are changing the prototype  of a function. 

#### Specific section or headline?
section : Creating a subclass

#### What did you expect to see?
current comment : // Define your methods and properties here
expected comment : // Define your constructor property and other methods and properties here

#### Did you test this? If so, how?
//------Incomplete commented code------
function superclass() {}
superclass.prototype = {
  // Define your methods and properties here
};

let sCObject = new superclass();
console.log(Object.getPrototypeOf(sCObject).constructor.name); //returns Object

//------Better commented code with sample 
function superclass() {}
superclass.prototype = {
  // Define your methods and properties here + constructor property
  constructor: superclass,
  //other Methods and properties goes below
};

let sCObject = new superclass();
console.log(Object.getPrototypeOf(sCObject).constructor.name); //returns superclass

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/getownpropertydescriptors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/getownpropertydescriptors/index.html
* Last commit: https://github.com/mdn/content/commit/3c394e62835ef7b443fb5208343ecba892bbf6d5
* Document last modified: 2021-05-26T11:36:38.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5687 with an update to the article.
