### ISSUE TITLE
Content bug: Variable Error Change Date to Day

### ISSUE THREAD

**Issue by jonesjaycob** [mdn/content#5691]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#to_get_date_month_and_year_or_time

## Specific page section or heading?

To get Date, Month and Year or Time

## What is the problem?

The variable `date` needs to be changed to `day`.

## What did you expect to see?

```let [month, date, year]    = new Date().toLocaleDateString("en-US").split("/")```
Needs to be changed to:
```let [month, day, year]    = new Date().toLocaleDateString("en-US").split("/")```

## Did you test this? If so, how?

Yes, I tested, and currently, `date` returns a day.

**Comment by mohddanish-cse** [comment]
Hi, I have tested the code. It is returning date.

`let [month, date, year] = new Date().toLocaleDateString("en-US").split("/")`
`console.log([month, date, year])`

Output: `["6", "5", "2021"]`

**Comment by sideshowbarker** [comment]
Thanks for reporting this. The bigger problem with that example is that to get the date parts, it’s using `toLocaleDateString(…).split("/")` — which is just not a good idea.

So I’ve opened https://github.com/mdn/content/pull/5711 with a fix.

**Comment by sideshowbarker** [comment]
> Hi, I have tested the code. It is returning date.
> 
> `let [month, date, year] = new Date().toLocaleDateString("en-US").split("/")`
> `console.log([month, date, year])`
> 
> Output: `["6", "5", "2021"]`

Yeah, using `date` as the variable name for the day of the month (`date.getDate()`) isn’t strictly wrong — it’s just a bit confusing in the context of the example.

But then the whole `Date` API has a lot of potential for confusion — e.g., it’s not obvious from the name that `date.getDay()` returns the day of the *week* while `date.getDate()` returns a *day* at all — let alone they day of the *month*. To be clear those methods should have just been named `date.getDayOfTheMonth()` and `date.getDayOfTheWeek()` — but I guess those would have been a bit verbose…
