### ISSUE TITLE
Automatically generate Dart wrappers and doc from MDN

### ISSUE THREAD

**Issue by jodinathan** [mdn/content#5694]
Hi,

I am a Dart developer and I would like to create a JS package for Dart devs to use.  
The idea is to read some MDN API, json file or even crawl the MDN website and generate the Dart files, for example:

```dart
@JS()
library window;

@JS()
abstract class HtmlElement {}

@JS()
abstract class HtmlDocument {
  external HtmlElement? getElemenyById(String buf);
}

@JS()
external HtmlDocument get document;
```

The above snippet is a Dart interface to use the window object along with document and getElementById.
What I am thinking in doing is automatize the process by reading stuff from MDN, generate wrappers like the above and publish a package to the community.

Is this ok?
If yes, do you have some API I could fetch these infos or something like that?

**Comment by sideshowbarker** [comment]
See https://developer.mozilla.org/en-US/docs/MDN/Tools/Unsupported_GET_API for info about the only thing available.

For example, to get a JSON representation of the https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement article, you can using https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/index.json

> Is this ok?

Yes, it’s OK to scrape the production site to get either that JSON data or the HTML source, or any  other data you want to get.

That said, you don’t actually need to remotely scrape the production site — you can instead run a “preview server” locally to get what you need. The details are in step 6 of https://github.com/mdn/content/blob/main/README.md#more-substantial-changes — but the gist of it is, you clone this repo, and then run this sequence of commands:

```bash
# Switch to a separate terminal.
cd ~/repos/mdn/content
yarn
yarn start
```
That will start a web server on your local system, accessible at http://localhost:5000. So if you want to get the JSON data for the `HTMLElement` element locally, you can use http://localhost:5000/en-US/docs/Web/API/HTMLElement/index.json.
