### ISSUE TITLE
Issue with "FileSystemDirectoryEntry.getDirectory()" : function SyntaxError

### ISSUE THREAD

**Issue by MainLeau** [mdn/content#5697]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryEntry/getDirectory

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryEntry/getDirectory#example

## What is the problem?

Incorrect function syntax

## What did you expect to see?

**NOT:**
`fileEntry.file(function(dictFile)) { ... }`
**BUT:**
`fileEntry.file(function(dictFile) { ... }`

**Comment by NegiAkash890** [comment]
Nice catch @MainLeau . I have raised a PR #5703 for the issue.
