### ISSUE TITLE
Examples in "HTMLSelectElement.form" article are misplaced, need to be replaced

### ISSUE THREAD

**Issue by pribilinskiy** [mdn/content#5704]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/form

#### What information was incorrect, unhelpful, or incomplete?
Examples are incorrect

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlselectelement/form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlselectelement/form/index.html
* Last commit: https://github.com/mdn/content/commit/cb20a8045f6cbdbd224b1068e46c8644470dd8c3
* Document last modified: 2021-06-01T09:10:31.000Z

</details>

**Comment by sideshowbarker** [comment]
Agreed. The examples in that article actually show nothing about using the `form` property of the `HTMLSelectElement` object.

**Comment by dev-nicolaos** [comment]
I can work on this.
