### ISSUE TITLE
Issue with ":focus-within": (short summary here please)

### ISSUE THREAD

**Issue by kannanwisen** [mdn/content#5708]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within

#### What information was incorrect, unhelpful, or incomplete?
The :focus-within CSS pseudo-class represents an element that has received focus or contains an element that has received focus. 

#### What did you expect to see?
The :focus-within CSS pseudo-class selects an element and all its ancestors elements when the element receives focus. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_focus-within`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_focus-within/index.html
* Last commit: https://github.com/mdn/content/commit/775066d2fc8d1561d5da61983d137c1297899315
* Document last modified: 2021-05-08T09:57:47.000Z

</details>

**Comment by kannanwisen** [comment]
Hi,

The word or is misleading.

For example

<!DOCTYPE html>
<html>
    <head>
        <style>
			:focus-within{
				padding:5px;
				border:1px solid red;
			}
        </style>
    </head>
    <body >
		<form>
			<div>
				<input type="text" name="city" />
			</div>
			<input type="text" name="country" />
		</form>
	</body>
	
</html>

When you focus on city field, it selects city field, and (not or) div, form, body, html elements.

when you focus on country field, it selects country field, and (not or) form, body, html elements.

**Comment by teoli2003** [comment]
Maybe rather than "selects", we should use "matches". The whole selector selects but the pseudo-class matches.

What about:
The `**:focus-within**`CSS pseudo-class matches the element that has focus and _any_ of its ancestors.

instead of

The `**:focus-within**`CSS pseudo-class is a selector for an element that has focus or _contains_ a descendant that has received focus.

**Comment by teoli2003** [comment]
Just pinging @fakela who wrote the PR and I'm not sure they'll be notified of new messages here (and whose input is valuable) :-)

**Comment by fakela** [comment]
@teoli2003 Thanks for pinging me on this.  
@kannanwisen thanks for the example shared. I tested the code on my end and to see how it works. 


without .focus-within applied
![Webp net-gifmaker (2)](https://user-images.githubusercontent.com/39309699/121044174-3953e080-c7ad-11eb-89f7-3e585aa893e3.gif)

with .focus-within applied
![Webp net-gifmaker (3)](https://user-images.githubusercontent.com/39309699/121047860-41605000-c7ae-11eb-9f6c-7248fca61675.gif)

From what I think,  form identifies itself as the parent of focusable content(which satisfies the first part of the definition) and we target the parent to display styles whenever one of its children is focused,  so as from the gif above when you focus on city field, it selects city field, and div, form.


Here is another example 
```
<div className="input-wrapper">
   <i className="fas fa-search" />
    <input
      id="input"
      placeholder="What are you looking for?"
      autoComplete="off"
    />
    <button>Search</button>
</div>
```
the container element uses a class .input-wrapper to identify itself as the parent of focusable content.
```
.input-wrapper:focus-within {
  /** Add desired outline, focus styles here */
  box-shadow: 0px 0px 10px 0px var(--primary-color);
  transition: box-shadow 250ms ease-in;
}
```

With that class handy, we can target the parent to display styles whenever one of its children is focused.



without .focus-within applied
<img width="463" alt="Screenshot 2021-06-07 at 16 46 53" src="https://user-images.githubusercontent.com/39309699/121051466-64403380-c7b1-11eb-830f-4e945c2fb30e.png">

.focus-within applied
<img width="455" alt="Screenshot 2021-06-07 at 16 47 03" src="https://user-images.githubusercontent.com/39309699/121051567-74f0a980-c7b1-11eb-9939-8edc3d802a95.png">



If you feel like there is something I am missing out, i am open to be corrected on that

**Comment by fakela** [comment]
> > Maybe rather than "selects", we should use "matches". The whole selector selects but the pseudo-class matches.
> > What about:
> > The **`:focus-within`** CSS pseudo-class matches the element that is focused and _any_ of its ancestors.
> 
> **Sounds perfect.**
> 
> > instead of
> > The **`:focus-within`** CSS pseudo-class is a selector for an element that has focus or _contains_ a descendant that has received focus.

Will effect the change to this

**Comment by kannanwisen** [comment]
You are welcome @fakela
