### ISSUE TITLE
Issue with "Match patterns in extension manifests": (invalid match patterns should include example with port number)

### ISSUE THREAD

**Issue by ManfredLange** [mdn/content#5718]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns

#### What information was incorrect, unhelpful, or incomplete?

The `host` section specifically states that `host must not include a port number` but that is easily overlooked.

#### Specific section or headline?

`host` section and `Invalid Match Patterns` section

#### What did you expect to see?

The `Invalid Match Pattern` should include an example of a host with a port number to show that it will not work as expected.

#### Did you test this? If so, how?

**Precondition for both tests: a web server is running on localhost at port 2502.**

Test 1:

The following in `manifest.json` will lead to CORS error:

```
   "permissions": [
      "*://localhost:2502/*",
   ],
```

Test 2:

The following in `manifest.json` will work (note the absence of the port number):

```
   "permissions": [
      "*://localhost/*"
   ],
```

These tests were conducted on Firefox version 89.0 (64-bit) running on Windows 10 Pro, version 10.0.19042 build 19042. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/match_patterns`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/match_patterns/index.html
* Last commit: https://github.com/mdn/content/commit/58d2649cd52f8c1d9baca86a1f02ca98b1fb2d09
* Document last modified: 2021-05-31T17:27:37.000Z

</details>

**Comment by Rob--W** [comment]
We will resolve this issue by changing Firefox to support permissions with ports in it - https://bugzilla.mozilla.org/show_bug.cgi?id=1350523

More details at https://bugzilla.mozilla.org/show_bug.cgi?id=1350523#c5

**Comment by sideshowbarker** [comment]
@Rob--W Should we add a note to the MDN article in the meantime? Or should be instead just keep this open until the change is made in the sources and that BMO bug is resolved?

**Comment by Rob--W** [comment]
This is already documented. The issue is about adding an extra example, but that's not necessary if we fix the issue in Firefox.

**Comment by ManfredLange** [comment]
I disagree. The documentation states that you must not use a port number. That is easy to overlook. Remember there is a lot of text in that page. Adding a row to the list of invalid examples would have save me a lot of time (a couple of hours?).

Even once fixed, the example should be either in the list of valid/invalid along with version information. If Firefox is changed so it considers (or at least ignores) port numbers as well, I think the documentation including the examples should be updated including which rule applies to which version of Firefox.

Just my two cents being a consumer of both the API as well as the documentation.

**Comment by rebloor** [comment]
Page includes the invalid example

| https://mozilla.org:80/ | Host must not include a port number.
-- | --
