### ISSUE TITLE
Issue with "TextEncoder": Reference to deprecated package

### ISSUE THREAD

**Issue by solkaz** [mdn/content#572]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder

#### What information was incorrect, unhelpful, or incomplete?
The `TextEncoder` page has the following note at the top:

> Note: There is a polyfill implementation to support non-UTF-8 text encodings on [GitHub](https://github.com/inexorabletash/text-encoding).

This links to [inexorabletash/text-encoding](https://github.com/inexorabletash/text-encoding), which has been archived and [deprecated](npmjs.com/package/text-encoding).

#### Specific section or headline?

Beginning of the page

#### What did you expect to see?

A more updated suggestion for those that need a polyfill implementation that supports non-UTF-8 text encodings.

#### Did you test this? If so, how?

Did not test.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/textencoder`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/textencoder/index.html
* Report started: 2020-12-22T11:57:39.047Z

</details>

**Comment by sideshowbarker** [comment]
@inexorabletash any suggestions for replacement Encoding polyfill?

**Comment by inexorabletash** [comment]
Nope. Someone else could fork and run with it if they desired. It was never intended for production use anyway - it tried to implement the spec (at the time) very directly, at the expense of performance.

**Comment by sideshowbarker** [comment]
> Nope. Someone else could fork and run with it if they desired.

OK, thanks — given that, I’ve opened #859 with a patch that removes mention of the polyfill, as well as dropping a couple other obsolete things from the See Also section.
