### ISSUE TITLE
Issue with "String.prototype.codePointAt()": …

### ISSUE THREAD

**Issue by jasontwuk** [mdn/content#573]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt

#### What information was incorrect, unhelpful, or incomplete?

The "Unicode code point value" part can be more specific.
![screenshot](https://user-images.githubusercontent.com/13745974/102885314-0e6a1000-444b-11eb-87e3-12ce92009dbd.png)

In [String.fromCharCode()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode), it uses `UTF-16 code units`.
![screenshot_1](https://user-images.githubusercontent.com/13745974/102886053-50478600-444c-11eb-9b4b-f09572d4e3e5.png)

From my understanding, I believe it would be better to use `UTF-16` instead of `Unicode` in this case. 

#### Specific section or headline?
Introduction

#### What did you expect to see?
Maybe change the Introduction to:
The `codePointAt()` method returns a non-negative integer that is UTF-16 code point value.

#### Did you test this? If so, how?
No test needed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/codepointat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/string/codepointat/index.html
* Report started: 2020-12-22T09:36:30.781Z

</details>

**Comment by Rumyra** [comment]
See https://github.com/mdn/content/pull/625
