### ISSUE TITLE
Issue with "Armazenando as informações que você precisa — Vari…": (short summary here please)

### ISSUE THREAD

**Issue by borghiacarlos** [mdn/content#5736]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/Variables

#### What information was incorrect, unhelpful, or incomplete?
Ao final do artigo, no link para o teste de habilidade, o hyperlink está incorreto.

#### Specific section or headline?
Na seção Testes suas Habilidades, ao final da página do artigo.

#### What did you expect to see?
O link atual: https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/Teste_suas_habilidades:_variaveis
O link correto: https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/Test_your_skills:_variables

#### Did you test this? If so, how?
Testei sim, estou lendo todos artigos.

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/learn/javascript/first_steps/variables`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/Variables
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/learn/javascript/first_steps/variables/index.html
* Last commit: https://github.com/mdn/translated-content/commit/f3327fb3029992c46efa718afdc92d3b555b3995
* Document last modified: 2021-06-05T01:06:14.000Z

</details>

**Comment by sideshowbarker** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
