### ISSUE TITLE
Issue with "Document and website structure": (typo found)

### ISSUE THREAD

**Issue by samxzhk** [mdn/content#5738]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure

#### What information was incorrect, unhelpful, or incomplete?
there's a simple typo ('roughy') in a note
(I'm sorry if it is not actually a typo because english is not my first language) 

#### Specific section or headline?
right below HTML for structuring content in a note 

#### What did you expect to see?
'Roughly 8% of men and 0.5% of women  instead of  'roughy'

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/document_and_website_structure`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/document_and_website_structure/index.html
* Last commit: https://github.com/mdn/content/commit/3af43c1dcfb9be19c73cf3fdd1178db9c74aa064
* Document last modified: 2021-04-27T01:03:07.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. Fixed by #5741 .

FYI, you can edit this kind of thing yourself if you like and create a pull request :-).
