### ISSUE TITLE
Issue with "Using the Notifications API": …

### ISSUE THREAD

**Issue by sgbeal** [mdn/content#576]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

#### What information was incorrect, unhelpful, or incomplete?

Conflicting info:

> You can check to see if you already have permission by checking the value of the Notification.permission read only property. 

Note the "read only" part. However, at least two code examples further down the page write to that property. e.g.

```
  if (window.Notification && Notification.permission !== "granted") {
    Notification.requestPermission(function (status) {
      if (Notification.permission !== status) {
        Notification.permission = status;
      }
    });
  }
```

Whether it's really read-only or not, i can't say - i'm just reporting the doc inconsistency.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API#Checking_current_permission_status

#### What did you expect to see?

N/A

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/notifications_api/using_the_notifications_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/notifications_api/using_the_notifications_api/index.html
* Report started: 2020-12-22T13:12:23.021Z

</details>

**Comment by nrayburn-tech** [comment]
I think it is readonly, https://notifications.spec.whatwg.org/#api.

It also looks like the callback style of requestPermission is deprecated in favor of a promise.
