### ISSUE TITLE
(Not a native speaker)

### ISSUE THREAD

**Issue by Grcy3g8** [mdn/content#5760]
(Not a native speaker)
Isn't this missing a `with`? I.e. `starting with/beginning with`?

_Originally posted by @intrigus-lgtm in https://github.com/github/codeql-go/pull/364#discussion_r506245230_

**Comment by hamishwillee** [comment]
Closing as this does not appear to be MDN content. I am closing now, but if you can post a link to the original MDN page that is affected then feel free to reopen to continue the discussion.
