### ISSUE TITLE
Issue with "Loops and iteration": (short summary here please)

### ISSUE THREAD

**Issue by KaungMyatThu-1001** [mdn/content#5769]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/loops_and_iteration`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/loops_and_iteration/index.html
* Last commit: https://github.com/mdn/content/commit/4a2976fab16bb915f41600bf6d2e50523325bd46
* Document last modified: 2021-03-29T10:38:42.000Z

</details>

**Comment by hamishwillee** [comment]
Closing. Not enough information to do anything with.
