### ISSUE TITLE
Content bug: Incomplete documentation of "sectioning root"

### ISSUE THREAD

**Issue by vassudanagunta** [mdn/content#5777]
## What page(s) did you find the problem on?

[Content categories](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories) correctly (I believe) makes the distinction between "Sectioning content" and the "sectioning root category". It has a link for "sectioning root" that points to [Using HTML sections and outlines
](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines#sectioning_roots) that no longer has the `#sectioning_roots` anchor or *any* information on sectioning roots.  At the bottom of the *Content categories* page is the section "Other content models", whose only content is the text "Sectioning root." with no explanation or link.

[Using HTML sections and outlines](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines) as mentioned above has no information on "sectioning roots", but a search of the doc repo reveals it in [a retired version of the page](https://github.com/mdn/retired-content/blob/c6431ebe6680ea887cc9308aaadc8689ee87642a/files/pt-pt/web/guide/html/using_html_sections_and_outlines/index.html)

[&lt;blockquote>: The Block Quotation element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote) says that they are in the Content categories "sectioning root", with no link to what that means. [&lt;figure>: The Figure with Optional Caption element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) is the same, except it has a link, but the same broken one mentioned earlier. Same issues with pages for other presumed sectioning roots: `<td>`, `<dialog>`, `<details>`, `<fieldset>`.

[HTML elements reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) has as its third section "[Sectioning root](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#sectioning_root)", but includes no explanation. Only a table presumably listing elements that are sectioning roots, but lists only `<body>`, not `<blockquote>` (see above) or any of the other presumed sectioning roots.  It has an section titled "[Content sectioning](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#content_sectioning)"  which doesn't explain "sectioning root" though it says the following with the same broken link for "sectioning root":

> The **`<footer>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a footer for its nearest [sectioning content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#sectioning_content) or [sectioning root](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines#sectioning_root) element. 

## What is the problem?

In short, there is minimal information on "sectioning root", and the page should be explaining, [Using HTML sections and outlines](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines), says nothing (but once did). 

Also I suspect that other elements such as `<ul>` and `<ol>` probably should either be "sectioning roots" or disallow sectioning elements in their content model. Because I can't see how a section occurring within a list take part in the outline of the content containing the list.

## What did you expect to see?

A solid definition of "sectioning root" along with a list of elements that are categorized as such on the [Content categories](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories) page, just as is done for [Flow content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#flow_content), and with all links to "sectioning root" pointing to it, also just as is done for Flow content.

## Did you test this? If so, how?

I'm trying to implement HTML5's model for sections and outlines and there are so many unanswered questions!

**Comment by rachelandrew** [comment]
As the note at the top of https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines explains, no browser currently implements outlines and so you should use heading levels to infer structure.

Due to this not being implemented, it's likely not going to be a priority to update on MDN as it isn't useful for anyone.

**Comment by teoli2003** [comment]
@rachelandrew, Should we retire (read: archive or delete) that page that is misleading as the algorithm will not be implemented by browser vendors in the forseeable future (I think the article is from 2010 or 2011, a decade ago)?

**Comment by rachelandrew** [comment]
@teoli2003 I think that might be a good idea, it's not actually useful to anyone right now.
