### ISSUE TITLE
Content bug: No link to another page

### ISSUE THREAD

**Issue by yuriyvyatkin** [mdn/content#5789]
## What page(s) did you find the problem on?

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

## Specific page section or heading?

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#обновление_и_синхронизация_разделяемой_памяти_с_помощью_атомарных_операций

## What is the problem?

Anchor tag doesn't have a href attribute for the word "атомарные".

## What did you expect to see?

Anchor tag with attribute href="https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Atomics#атомарные_операции" to the word "атомарные".

## Did you test this? If so, how?

I checked the need for a link.

**Comment by sideshowbarker** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
