### ISSUE TITLE
Issue with "Memory Management": Real-life example section, variable name is div but the explanation reference to it as myDivElement

### ISSUE THREAD

**Issue by HatimLagzar** [mdn/content#5790]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management

#### What information was incorrect, unhelpful, or incomplete?
Real-life example section
variable name is div but the explanation reference to it as myDivElement.

#### Specific section or headline?
Real-life example

#### What did you expect to see?
In the above example, the DOM element "div" has a circular reference to itself in the "circularReference" property. If the property is not explicitly removed or nulled, a reference-counting garbage collector will always have at least one reference intact and will keep the DOM element in memory even if it was removed from the DOM tree. If the DOM element holds a large amount of data (illustrated in the above example with the "lotsOfData" property), the memory consumed by this data will never be released and can lead to memory related issues such as the browser becoming increasingly slower.

#### Did you test this? If so, how?
No need to test.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/memory_management`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/memory_management/index.html
* Last commit: https://github.com/mdn/content/commit/4a2976fab16bb915f41600bf6d2e50523325bd46
* Document last modified: 2021-03-29T10:38:42.000Z

</details>

**Comment by himanshugarg** [comment]
This is no more an issue. The text reads

> In the above example, the DOM element **"myDivElement"** has a circular reference to itself in the

**Comment by sideshowbarker** [comment]
> This is no more an issue. The text reads
> 
> > In the above example, the DOM element **"myDivElement"** has a circular reference to itself in the

Thanks! — closing
