### ISSUE TITLE
Issue with "Advanced text formatting": …

### ISSUE THREAD

**Issue by mpm171** [mdn/content#583]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting

#### What information was incorrect, unhelpful, or incomplete?
On this page the Editable Code textareas have scripting problems that cause the user's work to be lost when showing solution/hiding solution.

#### Specific section or headline?
All 3 Active Learning areas have this issue

#### What did you expect to see?
When toggling between show and hide solution I expected to see changes that I've made to my code and the solution code respectively.

#### Did you test this? If so, how?
Make a change. Click Show Solution. Click Hide Solution. Change is gone.

THE REASON THIS IS BROKEN: all three areas use the same scripting and use const for "userEntry" and "solutionEntry". Use let for these variables and the script should work.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/advanced_text_formatting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.html
* Report started: 2020-12-21T19:21:04.272Z

</details>

**Comment by rachelandrew** [comment]
thanks @mpm171 and for providing information on a fix :) the above PR should sort that.
