### ISSUE TITLE
I cannot see the designated output 

### ISSUE THREAD

**Issue by avadhoot2008** [mdn/content#5831]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

#### What did you expect to see?
I expected to see a green message pop out that "your account has been created, now you can go ahead and sign in"
And stay on the same page 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status/405`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/405/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by teoli2003** [comment]
On which site were you trying to create an account?

**Comment by avadhoot2008** [comment]
my own emailing site but I figured it out  myself thanks
