### ISSUE TITLE
Issue with "Document.visibilityState": (incorrect safari comment)

### ISSUE THREAD

**Issue by jspurlin** [mdn/content#5834]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState

#### What information was incorrect, unhelpful, or incomplete?
Seems like the note "Safari doesn’t fire the visibilitychange event as expected when visibilityState transitions to hidden; so for that case, you need to also include code to listen for the pagehide event." doesn't seem correct based on the content on the [visibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) page. Should the safari note be scoped to `visibilityState` not transitioning to  `hidden` only when navigating away from the document?

#### Specific section or headline?
![image](https://user-images.githubusercontent.com/7033561/121402004-3cb2ad80-c90e-11eb-963c-a8c4459f3223.png)

#### What did you expect to see?
That the documentation for `Document.visibilityState` and `visibilitychange` to align around implementation notes

#### Did you test this? If so, how?
Did not test, but documentation doesn't align across the associated pages

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/visibilitystate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/visibilitystate/index.html
* Last commit: https://github.com/mdn/content/commit/fffe339bce9adcb9ced09d1d5eff291c105ce6ad
* Document last modified: 2021-05-29T05:32:06.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this — I’ve opened https://github.com/mdn/content/pull/5837 with a fix.
