### ISSUE TITLE
Issue with "Content  categories": <

### ISSUE THREAD

**Issue by jrpool** [mdn/content#5835]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/guide/html/content_categories`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/html/content_categories/index.html
* Last commit: https://github.com/mdn/content/commit/f988103f96564329b823f3482e9ab450e3c330ce
* Document last modified: 2021-05-14T08:02:56.000Z

</details>

**Comment by sideshowbarker** [comment]
Assuming this got submitted inadvertently and corrected with https://github.com/mdn/content/issues/5836

**Comment by jrpool** [comment]
Yes, that must have been. Sorry. Thanks, @sideshowbarker.

**Comment by sideshowbarker** [comment]
> Yes, that must have been. Sorry. Thanks, @sideshowbarker.

No worries — it happens fairly often
