### ISSUE TITLE
Issue with "Content  categories": <u> omitted from Flow and Phrasing lists

### ISSUE THREAD

**Issue by jrpool** [mdn/content#5836]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories

#### What information was incorrect, unhelpful, or incomplete?
`<u>` is flow and phrasing content, so it is incorrect to omit it from the lists of elements in those categories.
It should also be included in those categories’ separate pages.
#### Specific section or headline?
Flow Content; Phrasing Content

#### What did you expect to see?
`<u>` included.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/guide/html/content_categories`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/html/content_categories/index.html
* Last commit: https://github.com/mdn/content/commit/f988103f96564329b823f3482e9ab450e3c330ce
* Document last modified: 2021-05-14T08:02:56.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this — I’ve opened https://github.com/mdn/content/pull/5838 with a fix.
