### ISSUE TITLE
Review and Update Web Push API Notifications best practices

### ISSUE THREAD

**Issue by teoli2003** [mdn/content#5840]
In #5766, we are making a tiny technical update to the page https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Best_practices .

As:
- this page has an interesting and useful topic,
- is not linked neither from the relevant "landing pages" of the relevant API, nor from the sidebars
- is in a draft state since 2017, and need a thorough review,
- but looks already in a fair state,

I think we should update it and get it reviewed.

**Comment by Josh-Cena** [comment]
The `{{draft}}` was removed in #10504 and sidebar was added in #16364. I think it's okay if we now just merge this page into the main landing page.

**Comment by Josh-Cena** [comment]
This page is no longer orphaned and I think it makes more sense to keep it in this location. It also appears not outdated to me.
