### ISSUE TITLE
Issue with "Node.innerText": (short summary here please)

### ISSUE THREAD

**Issue by shevictory** [mdn/content#5845]
MDN URL: https://developer.mozilla.org/ru/docs/Web/API/HTMLElement/innerText

#### What information was incorrect, unhelpful, or incomplete?

Node.innerText

#### What did you expect to see?

HTMLElement.innerText

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/api/htmlelement/innertext`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/HTMLElement/innerText
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/api/htmlelement/innertext/index.html
* Last commit: https://github.com/mdn/translated-content/commit/bbed12e574958e07af25518c7e66bd5ee2fb2d2c
* Document last modified: 2021-06-09T00:40:02.000Z

</details>

**Comment by sideshowbarker** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
