### ISSUE TITLE
[HTML] Newline normalization & escaping in multipart/form-data

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#5861]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- The HTML spec is changing the way form payloads are handled to be more specific and match implementations better, in particular around newline normalization and escaping in multipart/form-data payloads.

## Related Gecko bugs

- [Implement spec-compliant newline normalization in form payloads](https://bugzilla.mozilla.org/show_bug.cgi?id=1686765).

**Comment by Rumyra** [comment]
FYI this came through as originally there was no `dev-doc-needed` @rachelandrew

**Comment by rachelandrew** [comment]
@Rumyra I'm not sure what needs documenting here other than adding a line to the release notes. I don't think we have the interoperability issue mentioned anywhere that I can see. Did you get given any more details as to what docs were needed?

**Comment by Rumyra** [comment]
@rachelandrew no - and to be honest when I was adding this issue I was thinking the same, I just wanted to get an experts opinion - so thank you 🙏  Very happy for this just to be an addition to release notes 👍

**Comment by andreubotella** [comment]
I think just a line on the release notes works.

For the record, although fixing this issue in the spec and to some extent implementing it had to deal more with newline normalizations than with the `multipart/form-data` escaping, I think only the escaping should be mentioned in the release notes, since the normalization seems like an incredibly technical detail.
