### ISSUE TITLE
Issue with "Website security": Mention of regular password changing policy against best practices

### ISSUE THREAD

**Issue by Its7up** [mdn/content#5866]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Website_security

#### What information was incorrect, unhelpful, or incomplete?
The statement "Encourage strong passwords that are **changed regularly**" is against best practices.

#### Specific section or headline?
Under the "A few key messages" headline, in the first bulletpoint.

#### What did you expect to see?
Don't encourage regular password changing policies. 

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/first_steps/website_security`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Website_security
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/first_steps/website_security/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for raising this — I’ve opened https://github.com/mdn/content/pull/5874 with a fix.

For the record here, let’s note in particular:

* https://www.schneier.com/blog/archives/2016/08/frequent_passwo.html
* https://www.ftc.gov/news-events/blogs/techftc/2016/03/time-rethink-mandatory-password-changes
