### ISSUE TITLE
Issue with "display": (short summary here please)

### ISSUE THREAD

**Issue by rodrigomoyano11** [mdn/content#5873]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/display

#### What information was incorrect, unhelpful, or incomplete?
Values for "display"

#### Specific section or headline?
Values -> Fallback Display Mode

#### What did you expect to see?
fullscreen
standalone
...

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/manifest/display`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/display
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/manifest/display/index.html
* Last commit: https://github.com/mdn/content/commit/f744fe0744483ac2c5b3f1f5fa3c8b5fec816c0a
* Document last modified: 2021-05-20T17:57:47.000Z

</details>

**Comment by rodrigomoyano11** [comment]
The error is in the last column of "Values" table, the "Fallback Display Mode" column

**Comment by sideshowbarker** [comment]
Can you explain what the exact error is? Do you mean the hyphen in “stand-alone”?

If so, that’s a soft hyphen — though it’s definitely misleading and we should try to keep it from happening.

So anyway is that the error you meant? Or is there some other error?
