### ISSUE TITLE
Issue with "TypeError: invalid arguments": examples are incorrect

### ISSUE THREAD

**Issue by CrimsonCodes0** [mdn/content#5875]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Typed_array_invalid_arguments

#### What information was incorrect, unhelpful, or incomplete?
The example shows passing a string into a TypedArray constructor, but in both, sloppy and strict mode, running on both, Chromium and Firefox, I cannot reproduce the error that they ended up with.
I believe that the entire page is unused and incorrect.

#### Specific section or headline?
"No strings in typed arrays"

#### What did you expect to see?
I had tested myself expecting the exception.

#### Did you test this? If so, how?
Running it in a browser console on an up-to-date version of Chromium and Firefox.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/typed_array_invalid_arguments`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Typed_array_invalid_arguments
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/typed_array_invalid_arguments/index.html
* Last commit: https://github.com/mdn/content/commit/6fe447217e08a28cf17b8896545f98d098582ac3
* Document last modified: 2021-02-19T20:01:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. Confirmed that, e.g., `new Uint8Array("nope")`:

* doesn’t throw in any current browsers, nor in node.js
* confirmed in https://matrixlogs.bakkot.com/TC39_General/2021-06-10#L42 that per-spec, it shouldn’t throw

…therefore, opened https://github.com/mdn/content/pull/5876 with a change that deletes that page.
