### ISSUE TITLE
Issue with "What is a web server?": (short summary here please)

### ISSUE THREAD

**Issue by olesiapoz** [mdn/content#5881]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_web_server

#### What information was incorrect, unhelpful, or incomplete?

You state that in HTTP only rewuest responce is working, what is true for HTTP 1.1 and not correct for HTTP 2.0.
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/common_questions/what_is_a_web_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_web_server
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/what_is_a_web_server/index.html
* Last commit: https://github.com/mdn/content/commit/8bca0ce2a46d1c2c60c0c2d91c8ab6683a86edda
* Document last modified: 2021-05-04T08:21:39.000Z

</details>

**Comment by sideshowbarker** [comment]
Can you please point out exactly which sentence, paragraph, or section in that article contains the incorrect statement that should be fixed?

**Comment by himanshugarg** [comment]
Second-guessing that the OP wants syncing with [HTTP/2 changes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Evolution_of_HTTP#http2_%E2%80%93_a_protocol_for_greater_performance) . The following lines are suspect:-

> All commands are plain-text and human-readable.

> Only clients can make HTTP requests, and then only to servers. Servers can only respond to a client's HTTP request.

Any thoughts?
