### ISSUE TITLE
Issue with "Debugging_JavaScript Article":  "Refused to execute inline script"

### ISSUE THREAD

**Issue by aquawicket** [mdn/content#5882]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/Debugging_JavaScript

#### What information was incorrect, unhelpful, or incomplete?
Page flashes html content for a split second the becomes blanked out

#### Specific section or headline?
Entire page

#### What did you expect to see?
Debugging_JavaScript Article

#### Did you test this? If so, how?
DevTools shows that it has been actively rejected.  "Refused to execute inline script".

`Debugging_JavaScript:1 [Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src-elem 'report-sample' 'self' *.speedcurve.com 'sha256-q7cJjDqNO2e1L5UltvJ1LhvnYN7yJXgGO7b6h9xkL1o=' www.google-analytics.com/analytics.js 'sha256-JEt9Nmc3BP88wxuTZm9aKNu87vEgGmKW1zzy/vb1KPs=' polyfill.io/v3/polyfill.min.js assets.codepen.io production-assets.codepen.io". Either the 'unsafe-inline' keyword, a hash ('sha256-7eCRCBmIzkkwwKs9dVv05dIH5pkJig+q6Fq5mkEVwMQ='), or a nonce ('nonce-...') is required to enable inline execution.`

`Debugging_JavaScript:75 [Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src-elem 'report-sample' 'self' *.speedcurve.com 'sha256-q7cJjDqNO2e1L5UltvJ1LhvnYN7yJXgGO7b6h9xkL1o=' www.google-analytics.com/analytics.js 'sha256-JEt9Nmc3BP88wxuTZm9aKNu87vEgGmKW1zzy/vb1KPs=' polyfill.io/v3/polyfill.min.js assets.codepen.io production-assets.codepen.io". Either the 'unsafe-inline' keyword, a hash ('sha256-iAN+QXw6j4osX9AA4Q9lR+S3YueWblxeNqNK3xE99VE='), or a nonce ('nonce-...') is required to enable inline execution.`

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/debugger`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/debugger/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by aquawicket** [comment]
This report template is from the page before. This is the actual page in question. 

MDN Content page report details
MDN URL: [https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/Debugging_JavaScript](https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/Debugging_JavaScript)

**Comment by sideshowbarker** [comment]
That “Debugging·JavaScript” article is obsolete/archived and as the details in the issue description indicate, it contains unsafe inline script that the current developer.mozilla.org CSP policy disallows.

Being obsolete/archived means that the source is not even in this repo but is instead in the https://github.com/mdn/archived-content repo — and as such, that means it’s not going to be considered worthwhile to invest work and time in making any change to it (to remove the unsafe inline script it’s using).

So instead I opened https://github.com/mdn/content/pull/5890 with a change that removes the one remaining link that MDN has to that article, which is in the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger article (and which, from the report details, seems to be where you came across it).
