### ISSUE TITLE
Issue with "TypedArray": Unclear, ambiguous reference to "subclassing feature"

### ISSUE THREAD

**Issue by CrimsonCodes0** [mdn/content#5884]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray

#### Specific section or headline?
"[Description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#description)," particularly the second subsection.

#### What information was incorrect, unhelpful, or incomplete?
The referenced paragraph is very unclear. Particularly this part:
> ...except when used during object creation in JS engines that support subclassing. There are at present no such engines...

It isn't clear what is meant by "subclassing." Is it specifically referring to %TypedArray% supporting subclassing? If so, an addendum making that connection explicit would significantly improve this pargraph. Currently it makes no sense because JavaScript has classes and subclassing/inheritance via the `extends` keyword, so to say that no ES engine supports subclassing doesn't make sense. Furthermore, the use of "support" here makes it seems like this is an ES specified feature that browsers have failed to support, which, when combined with the fact that modern browsers' JS engine support JS classes, it doesn't add up.

#### What did you expect to see?
N/A

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/typedarray`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/typedarray/index.html
* Last commit: https://github.com/mdn/content/commit/c0e54ff2aa029fbd132e936cfe1ba53549844ee6
* Document last modified: 2021-06-07T03:13:37.000Z

</details>

**Comment by sideshowbarker** [comment]
I’m inclined to think that at this point, we should drop that entire paragraph — that is, this:

> The <code>%TypedArray%</code> constructor on its own is not particularly useful.  Calling it or using it in a <code>new</code> expression will throw a <a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError"><code>TypeError</code></a>, except when used during object creation in JS engines that support subclassing. There are at present no such engines, so <code>%TypedArray%</code> is only useful to polyfill functions or properties onto all <code><var>TypedArray</var></code> constructors.

Maybe @jorendorff can confirm.

**Comment by jorendorff** [comment]
Yes, I can confirm. Delete it.

This thing is like an "abstract base class" in Java. It's the common base class of `Uint8Array`, `Float64Array`, and the rest. I think normal code basically never uses it.
