### ISSUE TITLE
Issue with "Test your skills: HTML text basics": (short summary here please)

### ISSUE THREAD

**Issue by Mucunguzi256** [mdn/content#5913]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics

#### Did you test this? If so, how? 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/test_your_skills_colon__html_text_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/test_your_skills_colon__html_text_basics/index.html
* Last commit: https://github.com/mdn/content/commit/c317bc0196ebd8b0e618b6e74e94e97728a2d372
* Document last modified: 2021-04-27T07:18:32.000Z

</details>

**Comment by NegiAkash890** [comment]
Thank @Mucunguzi256 
I would  like to add one more thing that I encountered while navigating through the page :

Before : 
![Screenshot from 2021-06-11 22-12-05](https://user-images.githubusercontent.com/55234838/121721900-63393a00-cb02-11eb-96c1-cce22a816fc5.png)

After :
![Screenshot from 2021-06-11 22-11-52](https://user-images.githubusercontent.com/55234838/121721919-69c7b180-cb02-11eb-8745-cb2affcd108f.png)

If I am not wrong the shouldn't we use markup just below the CSS example in the above picture like ![example 2](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics#html_text_basics_2) and ![example 3](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics#html_text_basics_3)have ?

Let me know if I can help here!

**Comment by rachelandrew** [comment]
@Mucunguzi256 I don't understand what you are reporting, as there are not any CodePens in the content you refer to.

Your CodePen doesn't have any styling for headings in it. So I'm not really sure how to help. If you are looking for help working through the examples then post here: https://discourse.mozilla.org/c/mdn/236 

@NegiAkash890 please raise a new ticket for any problem, I also don't understand your report as there appear to be two missign images. Please open a new ticket with all the information and I'll take a look.

**Comment by rachelandrew** [comment]
No response to questions so closing.
