### ISSUE TITLE
Issue with "The box model": (incorrect description of how negative margins collapse in CSS)

### ISSUE THREAD

**Issue by azerum** [mdn/content#5919]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model

While learning about the box model in CSS, I found this written about margin collpasing:

> If you have two elements whose margins touch, and both margins are positive, those margins will combine to become one margin, which is the size of the largest individual margin. **If one or both margins are negative, the amount of negative value will subtract from the total**. *(emphasis mine)*

I set negative margins to both of \<p\> elements [in the second example here](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model#margin). Their margins didn't subtracted from the total, instead the most negative margin (i.e. margin with greatest absolute value) was used. This makes sense, since margins are "collapsing".

Also, I found this in the [CSS spec](https://drafts.csswg.org/css2/#collapsed-margin):

> When two or more margins collapse, the resulting margin width is the maximum of the collapsing margins' widths. In the case of negative margins, the maximum of the absolute values of the negative adjoining margins is deducted from the maximum of the positive adjoining margins. **If there are no positive margins, the maximum of the absolute values of the adjoining margins is deducted from zero**. *(emphasis mine)*

So I think this part should be corrected

<details>
MDN Content page report details

* Folder: `en-us/learn/css/building_blocks/the_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/the_box_model/index.html
* Last commit: https://github.com/mdn/content/commit/bbe23f8c130f876a407d42fa991adc676adf129f
* Document last modified: 2021-02-27T17:32:36.000Z

</details>

**Comment by MuhammedSaleh** [comment]
There is a separate section on that page talking about the case of negative margins.
I think it's the same as your description above.
