### ISSUE TITLE
Issue with "Making decisions in your code — conditionals": …

### ISSUE THREAD

**Issue by NerdsAreIn** [mdn/content#592]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals

#### What information was incorrect, unhelpful, or incomplete?

The second bullet point under "Active learning: More Color Choices!" refers to the HTML for the test (specifically, the `option` elements), yet this is not accessible on the page. This  leaves the user to guess how the color values should be written in order to match the HTML.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/conditionals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/javascript/building_blocks/conditionals/index.html
* Report started: 2020-12-22T22:17:10.410Z

</details>

**Comment by chrisdavidmills** [comment]
I've had a look at this, and I'm not sure if there is really anything to change here. At the start of  the section, it says "In this example, you are going to take the ternary operator example we saw earlier and convert the ternary operator into a switch statement to allow us to apply more choices to the simple website." — so it invites you to look at the earlier example to see what that looks like and get a hint of the HTML structure.

Then the second bullet says "the choice should equal one of the possible values that can be selected, that is, white, black, purple, yellow, or psychedelic". It is telling you what color values you should use.

I guess we could put the color values in code font, to make it more obvious. Would that help?

**Comment by NerdsAreIn** [comment]
Yes, and then it says, "Note that the values are case sensitive, and should equal the <option> element value values rather than the visual labels." This is the confusing bit.

I thought that the <option> value value (a somewhat confusing wording in itself) for "psychedelic" might be something other than the word itself and tried a range of possibilities. I checked the HTML on here and, indeed, it is "psych". However, that didn't work in the task and "psychedelic" did. Maybe just delete the above sentence?

**Comment by chrisdavidmills** [comment]
I think you could be on to something here; I've made an update that removes the confusing sentence and adds some improvements to the previous one.

**Comment by chrisdavidmills** [comment]
ooops, see https://github.com/mdn/content/commit/cf2da19da0dc2379aabc3aee5d111c9174ca2b09 for the changes
