### ISSUE TITLE
Issue with "HTMLMediaElement: playing event": (short summary here please)

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#5932]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playing_event

#### What information was incorrect, unhelpful, or incomplete?
The events list on the sidebar does not include 'playing'.

![image](https://user-images.githubusercontent.com/40804543/121791047-3d1ba480-cbab-11eb-9a93-53ca55705224.png)

I'd also say this description:
"The playing event is fired when playback is ready to start after having been paused or delayed due to lack of data."
is a bit misleading.  The event also fires when you play for the first time, not just after pause or delay.  Maybe it is semantics, I don't know, since the audio may technically be 'paused' on page load.  It fires after 'canplay' event.

#### What did you expect to see?
All of the possible media events.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlmediaelement/playing_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playing_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlmediaelement/playing_event/index.html
* Last commit: https://github.com/mdn/content/commit/cb20a8045f6cbdbd224b1068e46c8644470dd8c3
* Document last modified: 2021-06-01T09:10:31.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. Fixed by #5965

FYI, Missing from sidebar because it did not have the "Events" tag. We're looking at making the generation of sidebar stuff a little more obvious in the near future by identifying the page type separately (rather than just having a tag), and then pulling it into sidebars as appopriate.
