### ISSUE TITLE
Issue with "Iteration protocols": The MDN page says `next` is a zero-argument function while ES2015 seems to say zero or one arg

### ISSUE THREAD

**Issue by monfera** [mdn/content#5933]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols

#### What information was incorrect, unhelpful, or incomplete?

The MDN page says for `next`: "A zero-argument function that returns an object with at least the following two properties"

#### Specific section or headline?

[The iterator protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterator_protocol)

#### What did you expect to see?

In line with the (I think) pertaining [spec page](https://tc39.es/ecma262/#sec-iteratornext), I expect to see something like: "A zero or one argument function that returns an object with at least the following two properties. If `next` is called with one argument, its value will be available to the `next` method being invoked."

#### Did you test this? If so, how?

I'm looking at the spec (see link above)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/iteration_protocols`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/iteration_protocols/index.html
* Last commit: https://github.com/mdn/content/commit/179e7d3a709f897d33ac9b833d9caff99f7396a3
* Document last modified: 2021-05-05T16:43:40.000Z

</details>

**Comment by sideshowbarker** [comment]
> I expect to see something like: "A zero or one argument function that returns an object with at least the following two properties. If `next` is called with one argument, its value will be available to the `next` method being invoked."

OK yes unless I’m misunderstanding, it seems like https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-%asyncfromsynciteratorprototype%.next also makes that clear.

But looking at https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-iteration I see:

> Arguments may be passed to the <code>next</code> function but their interpretation and validity is dependent upon the target <i>Iterator</i>. The for-of statement and other common users of <em>Iterators</em> do not pass any arguments, so <i>Iterator</i> objects that expect to be used in such a manner must be prepared to deal with being called with no arguments.

So should we include a similar note about that in the MDN article?

**Comment by sideshowbarker** [comment]
Thanks for raising this. I’ve opened with https://github.com/mdn/content/pull/5949 with a fix (which we can update further if we want to add a note like the one mentioned in https://github.com/mdn/content/issues/5933#issuecomment-860189725).

**Comment by monfera** [comment]
Thank you @sideshowbarker

> So should we include a similar note about that in the MDN article?

I think it'd be a good addition for education purposes, although it'd be added color rather than bringing the text into sync with the spec
