### ISSUE TITLE
Issue with "CSP: worker-src": wrong bug url: Edge 17 skips the script-src directive (bug).

### ISSUE THREAD

**Issue by artepic** [mdn/content#5941]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src

#### What information was incorrect, unhelpful, or incomplete?
wrong bug url: Edge 17 skips the script-src directive (bug).

#### Specific section or headline?
Fallback section

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/content-security-policy/worker-src`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/content-security-policy/worker-src/index.html
* Last commit: https://github.com/mdn/content/commit/703707a086279e44dca7ce75eea2948bc604b95d
* Document last modified: 2021-05-31T00:17:49.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/5947 with a fix. 
After that fix is merged, this issue will automatically be marked as resolved, and closed.
