### ISSUE TITLE
Wrong description of Padding on box model

### ISSUE THREAD

**Issue by MuhammedSaleh** [mdn/content#5944]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model

#### What information was incorrect, unhelpful, or incomplete?

Regarding padding, a paragraph says

> We can control the padding on each side of an element individually using the padding property, or each side individually using the equivalent longhand properties: padding-top, padding-right...

#### Specific section or headline?
Padding

#### What did you expect to see?
It should be: We can control the padding on **all sides on an element using the padding property**

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/the_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/the_box_model/index.html
* Last commit: https://github.com/mdn/content/commit/bbe23f8c130f876a407d42fa991adc676adf129f
* Document last modified: 2021-02-27T17:32:36.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this — I’ve opened https://github.com/mdn/content/pull/5946 with a fix. After that fix is merged, this issue will automatically be marked as resolved, and closed.
