### ISSUE TITLE
Issue with "clipboard": should have a clearer link to the clipboard webapi because both apis have same name giving confusion

### ISSUE THREAD

**Issue by opto** [mdn/content#5948]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard

#### What information was incorrect, unhelpful, or incomplete?

if you come from google and don't know about the clipboard webapi (as contrasted to the clipboard webextention api), then this sentence is a showstopper:
'Currently the API only supports copying images, but it's intended to support copying text and HTML in the future.'

why read on if you want to copy text into clipboard? it clearly specifies that no text can go into clipboard at current time.

I  admit that further down, a link to the webapi clipboard is given. I think this link is in the wrong position in the text.

#### What did you expect to see?

it is not obvious that there are two apis with the same name. The top of the page should mention that. 
That text copy is **intended** for the webextention api is not relevant to developers as long as that does not exist.

That text copy is possible with the other api, that is the relevant information. I would be glad if that could be mentioned more clearly.
Thanks, Klaus

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/clipboard`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/clipboard/index.html
* Last commit: https://github.com/mdn/content/commit/b3eebddc4c3a897597e3602655d596eed67851b6
* Document last modified: 2021-01-29T09:29:22.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5951 with a fix
