### ISSUE TITLE
Issue with "Math.clz32()": (mistake in count-leading ones example; two's complement)

### ISSUE THREAD

**Issue by sjswitzer** [mdn/content#5955]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/clz32

#### What information was incorrect, unhelpful, or incomplete?

The method for counting leading ones doesn't take into account two's complement arithmetic. For instance,

0001  - one, three leading zeros (assuming 4-bit word :) )
1111 - minus one (two's complement), FOUR leading ones.

Instead, count leading ones should be Math.clz32(-n-1), which uses the one's complement

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/math/clz32`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/clz32
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/clz32/index.html
* Last commit: https://github.com/mdn/content/commit/3c394e62835ef7b443fb5208343ecba892bbf6d5
* Document last modified: 2021-05-26T11:36:38.000Z

</details>

**Comment by sjswitzer** [comment]
I wrote that up in a hurry, but the basic problem is that "-n" does _not_ just invert the bits in "n", it inverts the bits [then adds one](https://en.wikipedia.org/wiki/Two%27s_complement). To compensate for this, you need to use "-n-1" to subtract out the one that two's complement negation added.

In C or C++ you'd use unary "~" for bitwise NOT, but JavaScript doesn't have that.

**Comment by Andrew-Cottrell** [comment]
The section [**Count Leading Ones and beyond**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/clz32#count_leading_ones_and_beyond) _does_ use JavaScript's [bitwise NOT](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_NOT) operator.

Are there 32-bit unsigned integers for which `const clon = n => Math.clz32(-n - 1);` produces a correct result and `const clon = n => Math.clz32(~n);` produces an incorrect result?

Or is the concern regarding use of JavaScript's bitwise NOT operator for numbers that are not 32-bit unsigned integers?

**Comment by sideshowbarker** [comment]
Closing this since per https://github.com/mdn/content/issues/5955#issuecomment-861330117 there doesn’t seem to be anything correct in the `Math.clz32()` article. But if there’s new information (and response to the questions in https://github.com/mdn/content/issues/5955#issuecomment-861330117), then we can revisit this.

**Comment by sjswitzer** [comment]
Sigh, my bad. It really did look like a minus to me.

**Comment by sideshowbarker** [comment]
> Sigh, my bad. It really did look like a minus to me.

No worries — thanks for having raised it. I learned something from it at least :)
