### ISSUE TITLE
Issue with "Backgrounds and borders": …

### ISSUE THREAD

**Issue by deekox** [mdn/content#596]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders

#### What information was incorrect, unhelpful, or incomplete?
Example 

.box {
  background-image: url(star.png);
  background-repeat: no-repeat;
  background-position: **top 20px;**
}

#### Specific section or headline?
"Positioning the background image" with two values (when one is keyword and second &lt;length>/&lt;percentage>

#### What did you expect to see?
Seems like (when providing two values) first value should be associated with horizontal dimension (left, center, right).
In the example the first value is 'top' and adding 2nd value does not change horizontal position. Setting 'top' as second value fixes the issue. Similar thing with vertical keywords.

#### Did you test this? If so, how?
On provided 'live' editor. On my own CSS. Both FF/Chrome do not accept such syntax.
I typed:
background-position: top 20px;

the image was **not** moved 20px right (from left edge)

I typed:
background-position: 20px top ;

the image was moved 20px right (from left enge)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/backgrounds_and_borders`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/css/building_blocks/backgrounds_and_borders/index.html
* Report started: 2020-12-23T01:56:00.563Z

</details>

**Comment by deekox** [comment]
Strangely enough this is not an issue when providing 4 values :/

**Comment by rachelandrew** [comment]
Hi @deekox thanks for the report, I think this is just an error as when mixing lengths and keywords the order matters as you noticed.

The PR linked above will fix that once it is merged. Thanks for the report!
