### ISSUE TITLE
Issue with "Advanced techniques: Creating and sequencing audio": Dead link to chrome sample wavetable repo

### ISSUE THREAD

**Issue by hngmn** [mdn/content#5960]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Advanced_techniques

#### What information was incorrect, unhelpful, or incomplete?
> It is taken from a [repository of wavetables](https://github.com/GoogleChromeLabs/web-audio-samples/tree/gh-pages/samples/audio/wave-tables)

Link is dead because they archived that directory to a different one

#### Specific section or headline?
In the "Note" under "The periodic wave" section. I quoted it above

#### What did you expect to see?
Probably should be something like https://github.com/GoogleChromeLabs/web-audio-samples/tree/main/archive/demos/wave-tables or point to a particular commit. I can also submit the change myself later

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/web_audio_api/advanced_techniques`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Advanced_techniques
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_audio_api/advanced_techniques/index.html
* Last commit: https://github.com/mdn/content/commit/2564f049b88915e3f70a0083788b1b294bf00d4f
* Document last modified: 2021-03-07T23:20:43.000Z

</details>

**Comment by sideshowbarker** [comment]
> Probably should be something like [https://github.com/GoogleChromeLabs/web-audio-samples/tree/main/archive/demos/wave-tables](https://github.com/GoogleChromeLabs/web-audio-samples/tree/main/archive/demos/wave-tables?rgh-link-date=2021-06-13T20%3A42%3A18Z) or point to a particular commit. I can also submit the change myself later

Yes it’d be great if you could open a pull request for this
