### ISSUE TITLE
Content bug: forEach. Added elements and callback Fn

### ISSUE THREAD

**Issue by DenisLopatin** [mdn/content#5968]
### In the description of the [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) method says: 

> Elements which are appended to the array after the call to forEach() begins will not be visited by callbackFn

But, the callback fn to the forEach method visited the "Hello" element that was added after it was called:

    var array = [1, 2, 3];

    array.forEach((item, index, currentArray) => {
        if (index === 1) {
            currentArray.splice(index + 1, 0, 'Hello');
        }
        console.log(item); // 1, 2, Hello
    });

as in the following case:

    var array = ['string', { name: 'person' }, 12];

    array.forEach((item, index) => {
        if (index === 1) {
            let element = array.pop();
            array.push(...['new element', element]);
        }
        console.log(item); // string, {name: "person"}, new element
    });

Elements that are added **to the beginning or end of the array** after the start of the forEach () function call **will not really** be visited by callbackFn

If I made a mistake, please explain.

But even if the element is added to the end of the array it can be passed to the callback function in some situations:

    var array = [1, 2, 3];

    array.forEach((item) => {
        if (item === 2) {
            array.pop();
            array.push('something');
        }
        console.log(item); // 1, 2, something
    });

Only elements added to the beginning of the array will not be visited by callbackFn.

If this description meant the following:

    var array = [1, 2, 3];

    array.forEach((item) => console.log(item)); // 1, 2, 3

    array.push(...[11, 22, 33]);

    console.log(array); // [1, 2, 3, 11, 22, 33]

then I don't understand why it was necessary at all.

**Comment by Andrew-Cottrell** [comment]
The description also includes

>The range of elements processed by `forEach()` is set before the first invocation of `callbackFn`.

This implies the `forEach` method only examines the array's length once, before first calling the callback function. The method then calls the callback function for each `index` less than the `length`. Therefore, additional values, that are **appended** to the array with indexes outside the pre-determined _range_, will not be passed to the callback function. The description doesn't specifically address what will occur if the array is mutated in other ways.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6012 with a change that updates the language using the @Andrew-Cottrell’s wording from https://github.com/mdn/content/issues/5968#issuecomment-860827713

**Comment by DenisLopatin** [comment]
However, this problem applies not only to the forEach method, but also to other array methods: map, filter, some, find, findIndex...

This is the perfect description:
> Elements which are assigned to indexes already visited, or to indexes outside the range, will not be visited by callbackFn

**Comment by sideshowbarker** [comment]
OK, let’s reopen this and label it “help wanted” and “good first bug”, to encourage other contributors to follow up by porting the same change to the documentation for map, filter, some, find, findIndex, and any other array methods where this change would apply

**Comment by nand-porko** [comment]
Hey @sideshowbarker this is my good first issue and I would like to fix it!

**Comment by teoli2003** [comment]
@nand-porko, the bug is yours.

**Comment by nand-porko** [comment]
Thank you @teoli2003 , I want a small clarification. So I will have to make changes to the markdown file right? As I'm not able to find any html files corresponding to [this webpage](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) for maps in the repo. I'm guessing that all the html content files have been switched to .md files.  Thank you in advance!

**Comment by teoli2003** [comment]
Yes, you are right: the JavaScript section of MDN Web Docs is generated from the .md files (unlike the rest of MDN, as we are in the progress of converting it).

**Comment by teoli2003** [comment]
@nand-porko Thanks for doing `Array.prototype.map()`!

Fancy doing the same for the other methods listed [here](https://github.com/mdn/content/issues/5968#issuecomment-861873467). It would be useful so we can close this issue!

**Comment by nand-porko** [comment]
Yes, I would love to finish it!

**Comment by teoli2003** [comment]
The production Web site is built once a day; read this [section](https://github.com/mdn/content#when-will-my-change-show-up-on-the-production-mdn-site) for more information.
