### ISSUE TITLE
Revise example's variable name because it's misleading: orderedArray implies it's ordered, and it's not.

### ISSUE THREAD

**Issue by elidoran** [mdn/content#6002]
https://github.com/mdn/content/blob/9159d258a7054d36d6c3f31564bd9e54cd8095a8/files/en-us/web/javascript/reference/global_objects/array/reduce/index.html#L511

The variable is named `orderedArray` even though the array result does not contain ordered elements. Using `new Set` does eliminate duplicates, but, it doesn't order them. 

Perhaps, the name would be better without 'ordered' in it...

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/issues/6002 with a fix.
