### ISSUE TITLE
Issue with "Base64": Missing content about conversion to typed array or ArrayBuffer

### ISSUE THREAD

**Issue by ericlaw1979** [mdn/content#6032]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Base64

#### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays has a link titled: "Getting ArrayBuffers or typed arrays from Base64-encoded strings" which links to a non-existent anchor:
https://developer.mozilla.org/en-US/docs/Glossary/Base64#appendix.3a_decode_a_base64_string_to_uint8array_or_arraybuffer

The en-US page does not seem to have an appendix and does not cover the topic described.

This content seems to be in https://developer.mozilla.org/zh-CN/docs/Glossary/Base64

#### Specific section or headline?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/base64`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Base64
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/base64/index.html
* Last commit: https://github.com/mdn/content/commit/48fca0c614add538e95f1075b2777fc396023d31
* Document last modified: 2021-03-16T07:50:01.000Z

</details>

**Comment by hardikshah197** [comment]
Should I take up this issue @ericlaw1979 ? if no one is working on it.

**Comment by ericlaw1979** [comment]
@hardikshah197 - I don't see anyone else working on this, so I think you're good to take it.

**Comment by sideshowbarker** [comment]
@hardikshah197, Thanks for speaking up — I’m going ahead and assigning this to you

**Comment by hardikshah197** [comment]
@sideshowbarker @ericlaw1979 I have added the content along with the anchor, See my changes in PR #6105
