### ISSUE TITLE
WindowOrWorkerGlobalScope call information on Window and WorkerGlobalScope is out of date

### ISSUE THREAD

**Issue by bjherbison** [mdn/content#6034]
Should https://developer.mozilla.org/en-US/docs/Web/API/Window and https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope just reference WindowOrWorkerGlobalScope instead of including everything in the Properties implemented from elsewhere section?
Currently both those pages don't mention crossOriginIsolated  and say origin "does not yet appear to be implemented in any browser" even though https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope says it was implemented in Chrome 59 and Firefox 54.

**Comment by himanshugarg** [comment]
1. Any pages that statically/dynamically fetch the relevant sections from others? We could do similar to fetch properties/methods/events from [WindowOrWorkerGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope).
2. Should we just link to relevant sections of [WindowOrWorkerGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope)? 
3. Do a one off sync to fix this bug?

**Comment by Elchi3** [comment]
We'd like to move these pages and I'm doing that work in https://github.com/mdn/content/pull/8351. The compat data will also be updated in https://github.com/mdn/browser-compat-data/pull/11518

**Comment by Elchi3** [comment]
We removed the abstract mixin page https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope. The exposed interface pages Window and WorkerGlobalScope remain.
