### ISSUE TITLE
Issue with "Object.assign()": mistake in first JS Demo

### ISSUE THREAD

**Issue by taramasonnutrien** [mdn/content#6035]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

#### What information was incorrect, unhelpful, or incomplete?
Initial description of Object.assign

#### Specific section or headline?
"_The Object.assign() method copies all enumerable own properties from one or more source objects to a target object. It returns the target object._"

#### What did you expect to see?
This description would be more helpful if it specified that the original target object will be modified. Something like "It returns the _modified_ target object."

#### Did you test this? If so, how?
Yes. I thought the example code was incorrect until I ran the code. the `target` const was different before it is run through Object.assign()

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/assign`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/assign/index.html
* Last commit: https://github.com/mdn/content/commit/3c394e62835ef7b443fb5208343ecba892bbf6d5
* Document last modified: 2021-05-26T11:36:38.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6037 with a fix.
