### ISSUE TITLE
Issue with "415 Unsupported Media Type": Content-Type does not indicate desired media type and should not be the basis of a 415 status code

### ISSUE THREAD

**Issue by xtofs** [mdn/content#6063]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415

#### What information was incorrect, unhelpful, or incomplete?

The article indicates that it might return 415  "due to the request's indicated Content-Type" 
but Content-Type is typically a HTTP response header. 

#### Specific section or headline?

Second paragraph: "The format problem might be due to the request's indicated Content-Type or [...]"

#### What did you expect to see?

I would expect "due to the request's indicated Accept Header" 

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status/415`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/415/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by sideshowbarker** [comment]
> MDN URL: [developer.mozilla.org/en-US/docs/Web/HTTP/Status/415](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415)
> 
> The article indicates that it might return 415 "due to the request's indicated Content-Type"
> but Content-Type is typically a HTTP response header.

POST requests always have a Content-Type request header, right?

I guess if it were instead considered in terms of a GET request, then Content-Type wouldn’t make sense — but the thing is, a 415 is actually about requests with payloads (request bodies, so not GET but instead POST, etc.).

The actually wording of the RFC is at https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.13:
> The 415 (Unsupported Media Type) status code indicates that the origin server is refusing to service the request because the payload is in a format not supported by this method on the target resource.  The format problem might be due to the request's indicated Content-Type or Content-Encoding, or as a result of inspecting the data directly.

So what we have in the MDN article now pretty much matches that, and it seems like we shouldn’t change it to mention anything about the Accept request header.

Would you agree?

**Comment by xtofs** [comment]
Yes, I agree. I missed the point about request body and I agree this is fully in line with the RFC

**Comment by sideshowbarker** [comment]
> Yes, I agree. I missed the point about request body and I agree this is fully in line with the RFC

Cool — thanks for having raised this, and please don’t hesitate to raise future issues when you some across something that should be made more clear. (I think this documentation for 415 response isn’t actually as clear as it ideally could be — but I think that’s mostly the fault of it just being a thin rewrite of what’s in the RFC, which is minimal…)
