### ISSUE TITLE
Issue with "Inheritance and the prototype chain": example should have arrow function (function expression is used instead))

### ISSUE THREAD

**Issue by alexkaduk** [mdn/content#6068]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain

#### What information was incorrect, unhelpful, or incomplete?
Current 
//  (Ps: There is one exception that arrow function doesn't have a default prototype property)
var doSomething = function(){};
console.log( doSomething.prototype );

Should be
//  (Ps: There is one exception that arrow function doesn't have a default prototype property)
var doSomething = () => {};
console.log( doSomething.prototype );

#### Specific section or headline?
It is part of section `Using prototypes in JavaScript`

#### What did you expect to see?
Arrow function should be used instead of a function expression.

//  (Ps: There is one exception that arrow function doesn't have a default prototype property)
var doSomething = () => {};

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6071 with a fix.
