### ISSUE TITLE
Issue with "MouseEvent.screenX": missing info about multiscreen environment

### ISSUE THREAD

**Issue by dszlachta** [mdn/content#6070]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/screenX

#### What information was incorrect, unhelpful, or incomplete?

Incomplete: I think that it should be mentioned how `screenX` behaves when there are multiple screens connected: it value range changes from [ 0; screenWidth ]  to [ -screenOneWidth; screenTwoWidth ]. This, I believe, have no implications when a user uses only one screen. But if there are more screens, weird bugs can happen. And yes, `clientX` should be used for getting the cursor position relative to the viewport, but mentioning this range change would make it more obvious which property (screenX vs clientX) a developer should use.

#### Specific section or headline?

I think it would make sense to include this information right after the header

#### What did you expect to see?

Something like: "NOTE: in multiscreen environment, screens aligned horizontally will be treated as a single device, thus the range of screenX value will increase".

#### Did you test this? If so, how?

I have created a fiddle to easily show how the range changes: https://jsfiddle.net/s6pce32x/
Check the range while using only one screen, it should be [0; screenWidth], then connect the second screen and the range should now change to [-screenOneWidth; screenTwoWidth] (I haven't moved the window between the screens)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mouseevent/screenx`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/screenX
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mouseevent/screenx/index.html
* Last commit: https://github.com/mdn/content/commit/19f75559a3df713dd1487807a4bbd84a9e3fd62e
* Document last modified: 2021-06-14T14:36:19.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6072 with a fix.
