### ISSUE TITLE
Issue with "Book list page": (short summary here please)

### ISSUE THREAD

**Issue by p0int-bl4nk** [mdn/content#6079]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_list_page

#### What information was incorrect, unhelpful, or incomplete?
Code to list books and their author names.

#### Specific section or headline?
Section: View

#### What did you expect to see?
 |   (#{book.author.family_name + ", " + book.author.first_name})     

#### Did you test this? If so, how?
Yes, on my computer.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/book_list_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_list_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/book_list_page/index.html
* Last commit: https://github.com/mdn/content/commit/b3eebddc4c3a897597e3602655d596eed67851b6
* Document last modified: 2021-01-29T09:29:22.000Z

</details>

**Comment by hamishwillee** [comment]
This is not a bug. The page lists `(#{book.author.name})` - that's the `name` virtual method defined in the Author model - see https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#author_model
