### ISSUE TITLE
Issue with "BookInstance list page": (short summary here please)

### ISSUE THREAD

**Issue by p0int-bl4nk** [mdn/content#6080]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/BookInstance_list_page

#### What information was incorrect, unhelpful, or incomplete?
Code of  /views/bookinstance_list.pug
${val.due_back} is incorrect

#### Specific section or headline?
View

#### What did you expect to see?
if val.status!='Available'
          span  (Due: #{val.due_date} )

#### Did you test this? If so, how?
yes, on my computer

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/bookinstance_list_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/BookInstance_list_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/bookinstance_list_page/index.html
* Last commit: https://github.com/mdn/content/commit/adc309da4235ec6c01f40e3212168ea5b98358c9
* Document last modified: 2021-01-29T01:56:44.000Z

</details>

**Comment by hamishwillee** [comment]
This is invalid - what you have listed in "What did you expect to see?" is what it does display inhttps://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/BookInstance_list_page#view
```
        if val.status!='Available'
          span  (Due: #{val.due_back} )
```
There is no mention of "${val.due_back} "

Thanks for posting. I'm closing on the assumption this is a mistake.

**Comment by p0int-bl4nk** [comment]
![mdn](https://user-images.githubusercontent.com/46352044/122541809-b1d95d80-d047-11eb-853e-19270bb1d609.PNG)

**Comment by hamishwillee** [comment]
Thanks, but I'm still not sure of your point (not withstanding that `#{val.due_back}` is not `"${val.due_back} "` as initially reported). That code looks fine. Further, it works.

**Comment by p0int-bl4nk** [comment]
I meant `#{val.due_back}` not `${val.due_back}`. It didn't work when i was doing it on my own, 'cause when the schema was created the field was named `due_date`. Sorry for the trouble!
