### ISSUE TITLE
Issue with "Getting started with HTML": (short summary here please)

### ISSUE THREAD

**Issue by semmottos** [mdn/content#6085]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started

#### What information was incorrect, unhelpful, or incomplete?
http should be replaced with https in several examples

#### Specific section or headline?
Single or double quotes? 

#### What did you expect to see?
http should be replaced with https in several examples

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/getting_started/index.html
* Last commit: https://github.com/mdn/content/commit/75c1271189903b4d96433a34a8174175dd089ef2
* Document last modified: 2021-04-28T14:08:28.000Z

</details>

**Comment by NegiAkash890** [comment]
Thanks @semmottos for raising this issue. I will have to ask @sideshowbarker if these changes are necessary then I will be moving forward with this one ;)

**Comment by hamishwillee** [comment]
@NegiAkash890 These changes are desirable but not absolutely "necessary" - I tend to fix them when I am doing other changes to a doc.

We did originally attempt to automate a full conversion, but not every site supports https, so if you do this you should do a quick check to make sure that the links work after changing.

**Comment by sideshowbarker** [comment]
> Thanks @semmottos for raising this issue. I will have to ask @sideshowbarker if these changes are necessary then I will be moving forward with this one ;)

What @hamishwillee said :) It’s fine and great to fix these when they get reported — so @NegiAkash890, assigning this one to you, if you’re willing to take care of it.
