### ISSUE TITLE
Issue with "Network request details": …

### ISSUE THREAD

**Issue by massic80** [mdn/content#609]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details

#### What information was incorrect, unhelpful, or incomplete?
An image is shrinked horizontally

#### Specific section or headline?
*Security tab* section

#### What did you expect to see?
A not-stretched or shrinked image

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/network_monitor/request_details`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/tools/network_monitor/request_details/index.html
* Report started: 2020-12-23T18:40:45.277Z

</details>

**Comment by mattiapontonio** [comment]
#832

**Comment by mattiapontonio** [comment]
@massic80 
Does it fixed?
https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details

**Comment by massic80** [comment]
It's probably not the image I was talking about, but looks like also Security Tab section is OK now :)
Thank you!
