### ISSUE TITLE
Issue with "What is JavaScript?": Broken Sentence

### ISSUE THREAD

**Issue by MKPATH2015** [mdn/content#6090]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript

#### What information was incorrect, unhelpful, or incomplete?
In "What is JavaScript doing on your page?" section.  The sentence "If the JavaScript loads and tries to run before the HTML and CSS it is affecting has been loaded, errors can occur." seems to be broken.

#### Specific section or headline?
 "If the JavaScript loads and tries to run before the HTML and CSS it is affecting has been loaded, errors can occur."

#### What did you expect to see?
I am not sure, as to what the writer wanted to communicate. May be  "If the JavaScript loads and tries to run before the HTML and CSS it is effects the page load time, errors can also occur."

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/what_is_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/what_is_javascript/index.html
* Last commit: https://github.com/mdn/content/commit/aebf96bd989465a1a3cab335b41ee46420ed19b9
* Document last modified: 2021-06-10T22:23:29.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks. The sentence is strictly correct but IMO a bit awkward. I have improved it in https://github.com/mdn/content/pull/6092
