### ISSUE TITLE
Issue with "Firefox 90 for developers": Text "Removals" showing prefixed to every section title

### ISSUE THREAD

**Issue by elycruz** [mdn/content#6091]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/90

#### What information was incorrect, unhelpful, or incomplete?
Over each new addition, in announcments page, the text "Removals" is listed.

#### Specific section or headline?
Almost all of them.

#### What did you expect to see?
The word "Additions" or no text, next to section headlines etc..

#### Did you test this? If so, how?
Opened the page in firefox developer edition v90.0b8.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/firefox/releases/90`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/90
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/90/index.html
* Last commit: https://github.com/mdn/content/commit/a7d7dc2eefaec4a13e1493ebf44e0efdd6dfc1cc
* Document last modified: 2021-06-14T16:35:51.000Z

</details>

**Comment by hamishwillee** [comment]
FF90 has not yet released. This is a document skeleton that is being populated over the coming weeks. On release the page will be cleaned up.

Thanks. Closing.

**Comment by elycruz** [comment]
(thanks)
