### ISSUE TITLE
Issue with "SpeechSynthesis.onvoiceschanged": (short summary here please)

### ISSUE THREAD

**Issue by Karthiseeni** [mdn/content#6101]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/onvoiceschanged

#### What information was incorrect, unhelpful, or incomplete?
onvoicechanged LIB.. while I reading about it there is lot of value in there, but in my VS code I access only 19 values only

#### Specific section or headline?
WEB SPEECH API

#### What did you expect to see?
Wanna to access all the value in onvoicechanged

#### Did you test this? If so, how?
Yes , through VC code 
// Init voices array
let voices = [];

const getVoices = () => {
    voices = synth.getVoices();
    console.log(voices);
    // Loop through voices and create an option for each one
    voices.forEach(voice => {
        //  Create option Element
        const option = document.createElement(`option`);
        // Fill option with voice and language
        option.textContent = voice.name + `(${voice.lang})`;

        // Set needed option attributes
        option.setAttribute(`data-lang`, voice.lang);
        option.setAttribute(`data-name`, voice.name);

        voiceSelect.appendChild(option);
    })
}
getVoices();
if (synth.onvoiceschanged !== undefined) {
    synth.onvoiceschanged = getVoices;
}

this. is the code I used to do 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/speechsynthesis/onvoiceschanged`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/onvoiceschanged
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/speechsynthesis/onvoiceschanged/index.html
* Last commit: https://github.com/mdn/content/commit/0d5312d317fb301c56441905dc84e1f902cb7046
* Document last modified: 2021-06-01T06:05:06.000Z

</details>

**Comment by sideshowbarker** [comment]
Is there some specific part of the https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/onvoiceschanged that has incorrect information? If so, can you please point out exactly what part of https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/onvoiceschanged is wrong?

**Comment by sideshowbarker** [comment]
Closing this for lack of response.
