### ISSUE TITLE
Issue with "Compile": (The term "software" is uncountable)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6123]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Compile

#### What information was incorrect, unhelpful, or incomplete?
_A compiler is a software_...

#### Specific section or headline?
Main section - **Compile**

#### What did you expect to see?
A compiler is **a piece of** software...

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/compile`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Compile
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/compile/index.html
* Last commit: https://github.com/mdn/content/commit/5fb569eddc18081727c03bb97cdb4c67f084804c
* Document last modified: 2021-04-24T03:00:55.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6127 with a fix. (There were a lot of other problems with that content, so I basically ended up rewriting most of it…)
