### ISSUE TITLE
Issue with "cookies.SameSiteStatus": meaning of 'none'

### ISSUE THREAD

**Issue by KaliszAd** [mdn/content#6124]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/SameSiteStatus

#### What information was incorrect, unhelpful, or incomplete?

no_restriction
    Represents a cookie set without a SameSite attribute.
doesn't seem to be incorrect/ not clear what it means. Setting 'none' seems to produce SameSite=None which is the desirable outcome.

#### Specific section or headline?

no_restriction
    Represents a cookie set without a SameSite attribute.

#### What did you expect to see?

'none' Corresponds to SameSite=None

#### Did you test this? If so, how?

Tried both in Firefox 78 and Chrome 91 both on Linux.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/cookies/samesitestatus`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/SameSiteStatus
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/cookies/samesitestatus/index.html
* Last commit: https://github.com/mdn/content/commit/b3eebddc4c3a897597e3602655d596eed67851b6
* Document last modified: 2021-01-29T09:29:22.000Z

</details>

**Comment by rebloor** [comment]
@KaliszAd  could I get some clarification, are you saying:

1. `no_restriction` is not the return value, the return value is `none`
1. the return value is `no_restriction`, but for consistency with the SameSite attribute of the Set-Cookie HTTP response header it should be `none`

**Comment by KaliszAd** [comment]
@rebloor there should be one more option of `none` which produces SameSite=None which is not the same as a missing SameSite attribute, which is produced by `no_restriction`.

**Comment by rebloor** [comment]
@KaliszAd again could I get some clarification, are you saying:

1. `none` is not return when SameSite=None, that is, the feature is missing
1. `none` is return when SameSite=None, that is, the documentation is missing

**Comment by Rob--W** [comment]
Firefox doesn't support `sameSite` "none"` yet, it would probably be good to mention this in the browser-compat-table, with a reference to https://bugzilla.mozilla.org/show_bug.cgi?id=1550032

**Comment by rebloor** [comment]
Thanks for the clarification @Rob--W
