### ISSUE TITLE
Issue with "Debugging HTML": (The referenced error is of punctuation and not spelling)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6125]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Debugging_HTML

#### What information was incorrect, unhelpful, or incomplete?
**Syntax errors**: These are spelling errors in your code that actually cause the program not to run, like the Rust error shown above.

#### Specific section or headline?
**Permissive code**

#### What did you expect to see?
**Syntax errors**: These are spelling **or punctuation** errors in your code that actually cause the program not to run, like the Rust error shown above.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/debugging_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Debugging_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/debugging_html/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6126 with a fix.

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/6126 — thanks again for having raised this
