### ISSUE TITLE
Lorem ipsum in examples

### ISSUE THREAD

**Issue by nschonni** [mdn/content#613]
Came across the use in a few examples, and you can seem some hits here https://github.com/mdn/content/search?q=Lorem
Not sure if these should be replaced with real text or allowed

**Comment by vkWeb** [comment]
@nschonni I think it's allowed. And lorem ipsum are pretty standard placeholders, so I don't think we should move over to real text.

**Comment by nschonni** [comment]
That's fine. cSpell does have a lorem-ipsem dictionary, but I wasn't sure if it should be replaced or ignored

**Comment by vkWeb** [comment]
@nschonni closing this, thanks for confirming btw ^_^!

**Comment by nschonni** [comment]
FYI, found out it's using other random non-lorem ipsum words from some generator, so i'd suggest finding a new sample/placeholder text to use consistently
