### ISSUE TITLE
Content suggestion: wide angle of the camera into navigator.mediaDevices.getUserMedia()

### ISSUE THREAD

**Issue by AndreaAcanfora** [mdn/content#6136]
## What is the new suggestion?
wide angle of the camera into navigator.mediaDevices.getUserMedia()

## Why is it important or useful?
Zoom can be entered, but wide angle cannot be adjusted

How many pages are likely to be needed?
How much time do you think this work should take? Few hours
Will the work enable learners or professionals to achieve their goals better? yes
Does it address critical needs in the web industry? yes
Is the work an operational necessity, i.e. is not having it a security risk? no
Does the content help make the web more ethical? no

**Comment by Josh-Cena** [comment]
It has been two years and it doesn't appear like this is a content issue. If you want to see a new feature being implemented, please send an issue to https://github.com/w3c/mediacapture-main
