### ISSUE TITLE
Issue with "PublicKeyCredential": …

### ISSUE THREAD

**Issue by pfloretz** [mdn/content#614]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential

#### Specific section or headline?
PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()Secure context
A static method returning a Promise which resolves to true if an authenticator bound to the platform is capable of verifying the user. With the current state of implementation, this method only resolves to true when Windows Hello is available on the system.

#### What did you expect to see?
The comment that this only resolves to true when Windows Hello is available is false. This resolves to true on MacOS in various browsers, as well as on iOS devices in Safari.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/publickeycredential`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/publickeycredential/index.html
* Report started: 2020-12-23T23:55:27.700Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it.

I’ve raised https://github.com/mdn/content/pull/619 with a patch that removes the statement cited in the question, as well as two similar statements in https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/isUserVerifyingPlatformAuthenticatorAvailable

I tested in Chrome on an Android device and in Safari on iOS and in both cases got true. I didn’t get true when when I tested in Chrome and Safari on my macOS laptop — but maybe I’m just not testing right.

Regardless, the fact iUVPAA resolves to true in iOS and Android is sufficient for determining that the statement about it only working with Windows Hello is no longer true.
