### ISSUE TITLE
Issue with "Date() constructor": what happens if parameters are out of range?

### ISSUE THREAD

**Issue by JBTournesol** [mdn/content#6141]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

#### What information was incorrect, unhelpful, or incomplete?
Incomplete concerning what happens (or should happen) if one or more values is outside of the valid range in the constructor.
For example, the month should be in the range from 0 to 11, inclusive.  What happens (or should happen) if you specify the month as 12 because it is December and you forgot to subtract 1?
Your example:  let birthday = new Date(1995, 11, 17)            // the month is 0-indexed
But what if we actually use:  let birthday = new Date(1995, 12, 17)            // Ooops !!!  the month is 0-indexed
#### Specific section or headline?
Examples

#### What did you expect to see?
How to test to see if the instance of the Date object is in fact valid or invalid, especially testing for invalid if parameters are out of the valid range.
Or, if it is not possible to test the Date object for validity, a statement that it is not possible to do so, perhaps with suggestions on how to test the Date object from outside the Date object.

#### Did you test this? If so, how?
With both Firefox and Safari, both running on Mac, I used isNaN(birthday) with an invalid value (month = 12) on my Date object, but isNaN gives false, indicating that the Date object seems to be valid.  I was hoping for true because the value for the month was invalid, which should make the entire Date object invalid.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/date`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/date/index.html
* Last commit: https://github.com/mdn/content/commit/8e4451e44af7128d2748bd37fa3be9afec5f18fe
* Document last modified: 2021-06-14T14:49:04.000Z

</details>

**Comment by Josh-Cena** [comment]
Trying to help, but I don't completely understand what can be clarified. There's nothing as an "invalid date", so there's no way to test this: all dates, under the hood, are just number timestamps. It's also already mentioned in the docs:

> - `monthIndex`
>   - : Integer value representing the month, beginning with `0` for January to `11` for December. If a value greater than `11` is passed in, then those months will be added to the date; for example, `new Date(1990, 12, 1)` will return January 1st, 1991

Would appreciate if anyone has any idea about what can be added?
