### ISSUE TITLE
Issue with "CSS Object Model (CSSOM)": A grammar change (leftover from rewriting sentences)

### ISSUE THREAD

**Issue by terrifricker** [mdn/content#6146]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/CSSOM

#### What information was incorrect, unhelpful, or incomplete?
The following sentence needs correction:

> The CSSOM, together with the DOM, ~to~ build the render tree, which is in turn used by the browser 
> to layout and paint the web page.

The word 'to' needs to be removed. not 'to build', but 'build

#### Specific section or headline?
The second paragraph on the glossary page for CSSOM

#### What did you expect to see?
N/A

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/cssom`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/CSSOM
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/cssom/index.html
* Last commit: https://github.com/mdn/content/commit/c016a6b893578b1f39794983682c6d9107910226
* Document last modified: 2020-12-21T07:50:05.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6155 with a fix.

**Comment by terrifricker** [comment]
The two paragraphs that you removed were extremely helpful to me in understanding what the CSSDOM is.  I would suggest only deleting the one word, rather than the entire section.

**Comment by sideshowbarker** [comment]
> The two paragraphs that you removed were extremely helpful to me in understanding what the CSSDOM

Those paragraphs are poorly written and not actually correct or relevant. That’s why I removed them.

For example, the following basically is nonsensical:

> Both of them are part of the critical rendering path which is a series of steps that must happen to properly render a website.

And the following is just plain wrong:

> The CSSOM, together with the DOM, build the render tree, which is in turn used by the browser to layout and paint the web page.

The CSSOM and the DOM do not “build the render tree”. The browser engine builds the render tree. The CSSOM does no building of anything, and the DOM does no building of anything. Instead, the _browser_ builds the CSSOM and the browser builds the DOM. And then the built DOM has APIs that expose methods and properties you can use for reading and modifying the document’s structure and content, and the built CSSOM has APIs that expose methods and properties you can use for reading and modifying the document’s style information.

But that’s not at all what’s said in the existing paragraphs that I replaced. Those paragraphs seem to have been written by someone who didn’t actually understand what the CSSOM is, nor what the DOM is. What they seem to have been trying to describe is something quite different from what the CSSOM actually is.

**Comment by terrifricker** [comment]
Then I'm very glad I pointed it out.  I do not want to go forward with a misunderstanding.
