### ISSUE TITLE
Issue with "Origin": question about Origin compose

### ISSUE THREAD

**Issue by zhangenming** [mdn/content#6148]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Origin

#### What information was incorrect, unhelpful, or incomplete?
Web content's origin is defined by the scheme (protocol), host (domain), and port 

#### What did you expect to see?
host include port
host =  hostname + port
according to https://developer.mozilla.org/en-US/docs/Web/API/Location
Location.host: Is a USVString containing the host, that is the hostname, a ':', and the port of the URL.

so Web content's origin is defined by the scheme (protocol), hostname, and port 
or Web content's origin is defined by the scheme (protocol) and host

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/origin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Origin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/origin/index.html
* Last commit: https://github.com/mdn/content/commit/9917bf17a97973166bb3cb3812a496e4117a778f
* Document last modified: 2021-01-11T13:30:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6167 with a fix.
