### ISSUE TITLE
Issue with "MutationObserver.observe()": reference to non-existent section

### ISSUE THREAD

**Issue by joriki** [mdn/content#6150]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe

#### What information was incorrect, unhelpful, or incomplete?

"For details and an example, see [Monitoring text content changes](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#monitoring_text_content________changes) in [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)."
There's no section called "Monitoring text content changes" on the page linked to; in fact that page doesn't contain the word "text".

#### Specific section or headline?

description of `characterDataOldValue`

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mutationobserver/observe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mutationobserver/observe/index.html
* Last commit: https://github.com/mdn/content/commit/19f75559a3df713dd1487807a4bbd84a9e3fd62e
* Document last modified: 2021-06-14T14:36:19.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6169 with a change to address it.

I can find no record that the `MutationObserver` article ever actually had a “Monitoring text content changes” section, and no record that existed anywhere else in MDN at any time.

Given that, unfortunately the only practical way I can think of to resolve this is to drop the reference completely.

I believe that MDN needs some “Monitoring text content changes” content and an example, then I’d suggest raising that as a separate issue.
