### ISSUE TITLE
Issue with "<input type="datetime-local">": (short summary here please)

### ISSUE THREAD

**Issue by kugo2006** [mdn/content#6161]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

#### What information was incorrect, unhelpful, or incomplete?
Date format info - incorrectly uses "dd" for two digit "day of month" formatting, which means the first two letters of the local name for the day of the week

#### Specific section or headline?
throughout page 

#### What did you expect to see?
"DD" for two digit "day of month" formatting

#### Did you test this? If so, how?
Compare to ISO8601 compliant documentation
https://momentjs.com/docs/#/displaying/format/
https://en.wikipedia.org/wiki/ISO_8601

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/datetime-local`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/datetime-local/index.html
* Last commit: https://github.com/mdn/content/commit/8d642a73750cb3ace88c4f92b6676dd627912f8a
* Document last modified: 2021-06-08T12:54:28.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6170 with a fix.
