### ISSUE TITLE
Issue with "Clipboard.read()": (short summary here please)

### ISSUE THREAD

**Issue by bmarotta** [mdn/content#6176]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read

#### What information was incorrect, unhelpful, or incomplete?

The example is incorrect

#### Specific section or headline?

Example

#### What did you expect to see?

A code that works

#### Did you test this? If so, how?

Copy/paste on an HTML file and opened in Chrome. The code fails because:

1) The data element returned in the promise doesn't have an items property. The data itself is a collection
2) The items of the data element don't have a type property but a types array property.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/clipboard/read`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/clipboard/read/index.html
* Last commit: https://github.com/mdn/content/commit/3a1c296a5aa68edca4614146747bdac8a1ecb975
* Document last modified: 2021-06-11T23:46:13.000Z

</details>

**Comment by FarazzShaikh** [comment]
Can confirm via this example after copying [this](https://lh3.googleusercontent.com/proxy/l3Sh-UdzMKAgGj2QWWjpjCYFm-Eer1IV3oVwbdQUTZDUCsLM4kZm4ICaH5kozp2ZAFggYz40kKAVDgHhvJMMYSt9I1u2cJL3MYltQnSNlTyWW3WKxEk) PNG:

```html
<!DOCTYPE html>
<html lang="en">
  <body>
    <script>
      navigator.permissions.query({ name: "clipboard-read" }).then((result) => {
        // If permission to read the clipboard is granted or if the user will
        // be prompted to allow it, we proceed.

        if (result.state == "granted" || result.state == "prompt") {
          navigator.clipboard.read().then((data) => {
            for (let i = 0; i < data.items.length; i++) {
              if (data.items[i].type != "image/png") {
                alert("Clipboard contains non-image data. Unable to access it.");
              } else {
                const blob = data.items[i].getType("image/png");
                imgElem.src = URL.createObjectURL(blob);
              }
            }
          });
        }
      });
    </script>
  </body>
</html>
```

The [specification](https://w3c.github.io/clipboard-apis/#dom-clipboard-read) (referred to in the Specifications section) defines `data` as a "sequence of ClipboardItems.". The type property also does not exist like mentioned. 

Furthermore, `getType()` returns a promise that resolves to the the blob data.

Here is an updated working example (assuming `imgElem` is defined).

```js
navigator.permissions.query({ name: "clipboard-read" }).then((result) => {
  // If permission to read the clipboard is granted or if the user will
  // be prompted to allow it, we proceed.

  if (result.state == "granted" || result.state == "prompt") {
    navigator.clipboard.read().then((data) => {
      for (let i = 0; i < data.length; i++) {
        if (!data[i].types.includes("image/png")) {
          alert("Clipboard contains non-image data. Unable to access it.");
        } else {
          data[i].getType("image/png").then((blob) => {
            imgElem.src = URL.createObjectURL(blob);
          });
        }
      }
    });
  }
});

```

Will PR this fix soon.
