### ISSUE TITLE
Issue with "Multimedia: Images": Safari>=14 supports WebP

### ISSUE THREAD

**Issue by ardgedee** [mdn/content#6201]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/Multimedia

#### What information was incorrect, unhelpful, or incomplete?
- WebP — Excellent choice for both images and animated images. WebP offers much better compression than PNG or JPEG with support for higher color depths, animated frames, transparency etc. (but not progressive display.). Supported by all major browsers except Safari.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/Performance/Multimedia#the_most_optimal_format

#### What did you expect to see?
- WebP — Excellent choice for both images and animated images. WebP offers much better compression than PNG or JPEG with support for higher color depths, animated frames, transparency etc. (but not progressive display.). Supported by all major browsers except Safari versions before 14.0.

#### Did you test this? If so, how?
Official documentation: https://developer.apple.com/documentation/safari-release-notes/safari-14-release-notes#Media

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/performance/multimedia`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/Multimedia
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/performance/multimedia/index.html
* Last commit: https://github.com/mdn/content/commit/fc36604b19a172f3fbedb2629e2403180f2eda55
* Document last modified: 2021-03-19T23:16:59.000Z

</details>

**Comment by hamishwillee** [comment]
Yeah, the official release notes are wrong. There's a note about this in the webp details docs: 
![image](https://user-images.githubusercontent.com/5368500/122840565-b9498100-d33d-11eb-95f0-412c53285380.png)

I'll add a clarification.

**Comment by hamishwillee** [comment]
I ended up duplicating that note in place - see #6207
