### ISSUE TITLE
Issue with "What’s in the head? Metadata in HTML": (should I add shortcut link type in icon)

### ISSUE THREAD

**Issue by tqma113** [mdn/content#6209]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML

#### What information was incorrect, unhelpful, or incomplete?

```html
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
```

#### Specific section or headline?
adding_custom_icons_to_your_site

#### What did you expect to see?
```html
<link rel="icon" href="favicon.ico" type="image/x-icon">
```

#### Did you test this? If so, how?
In https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types the shortcut link type is not recommanded.

![image](https://user-images.githubusercontent.com/22792671/122859487-b014e000-d34e-11eb-841b-143c1ec53e27.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/the_head_metadata_in_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/the_head_metadata_in_html/index.html
* Last commit: https://github.com/mdn/content/commit/8300f989c41abdb1695caa5ba496bf4864957680
* Document last modified: 2021-05-07T12:44:01.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you - you're absolutely right. Fixed by #6211
