### ISSUE TITLE
Issue with "Setting up a Node development environment": (short summary here please)

### ISSUE THREAD

**Issue by neathishere** [mdn/content#6219]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment

#### What information was incorrect, unhelpful, or incomplete?
npm install express-generator -g => this command works to some extent (there are some errors and warnings). According to the official documentation, the appropriate command is: npx express-generator

#### Specific section or headline?
Under the heading: Installing the Express Application Generator

#### What did you expect to see?
New express application after using that command line

#### Did you test this? If so, how?
Yes. I put this command line into my git bash. It worked but with some errors & warnings.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/development_environment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/development_environment/index.html
* Last commit: https://github.com/mdn/content/commit/87c896192dce2d07786b58ef9abc197912a4c737
* Document last modified: 2021-05-26T07:38:46.000Z

</details>

**Comment by FarazzShaikh** [comment]
The command `npm install <package> -g` Installs a package globally on your system

the command `npx <package>` download and runs a packages without having to install it

As you can see, `npm install` Does not run the package, in this case, to run `express-generator` Run the command: `express` After installation is done

The docs are accurate as the command you mentioned falls under the “Installing the Express Application Generator” section and indeed does tell you to run the `express` Command to run the package

**Comment by sideshowbarker** [comment]
@neathishere what are the exact errors and warnings that you get when running `npm install express-generator -g`?

And do you really run `npx express-generator`? And what happens when you run it? Do you also run `express helloworld`, as the part of the how-to at https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment#installing_the_express_application_generator says to do?

@FarazzShaikh Is there some reason you can think of for running `npx express-generator`? And if so, should the article be updated to include an `npx express-generator` step?

**Comment by FarazzShaikh** [comment]
@sideshowbarker As mentioned on the [Express site](https://expressjs.com/en/starter/generator.html), older versions (< 8.2.0) of Node did not include `npx`. I think with modern versions of Node, it is not necessary to globally install the `express-generator` package for simply creating an express app.

I think we could include similar phrasing to the official site. I will make a PR fixing this if you can assign this issue to me

**Comment by sideshowbarker** [comment]
> I think we could include similar phrasing to the official site. I will make a PR fixing this if you can assign this issue to me

Thanks much — assigned

**Comment by hamishwillee** [comment]
Thanks for this. Nxp is a new command for me. This is better than installing the generator, which you really only need to do once.
