### ISSUE TITLE
Issue with "Basic concepts of flexbox": initial value of justify-content

### ISSUE THREAD

**Issue by youngmysteriouslight** [mdn/content#6224]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox

#### What information was incorrect, unhelpful, or incomplete?

> The initial value is flex-start which will line the items up at the start edge of the container, but you could also set the value to flex-end to line them up at the end, or center to line them up in the centre.

#### Specific section or headline?
justify-content

#### What did you expect to see?
[The formal definition of justify-content](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#formal_definition) states that the initial value of justify-content is normal, not flex-start.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_flexible_box_layout/basic_concepts_of_flexbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.html
* Last commit: https://github.com/mdn/content/commit/4df8fc624cb319731c0e0ad052348b2b0f62e59e
* Document last modified: 2021-06-11T11:56:01.000Z

</details>

**Comment by rachelandrew** [comment]
`normal` in flexbox is `flex-start`, the formal definition is from box alignment, and normal behaves differently depending on the formatting context you are in. So `normal` is correct in terms of the definition, but in reality, it's `flex-start` as defined in the flexbox spec https://drafts.csswg.org/css-flexbox-1/#propdef-justify-content
