### ISSUE TITLE
Issue with "Storing the information you need — Variables": Poor Counter Example for the Importance of Variables

### ISSUE THREAD

**Issue by evans23** [mdn/content#6226]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables

#### What information was incorrect, unhelpful, or incomplete?
In the Section "What is a Variable?", the counter example meant to show why a world without variables would be bad uses the same variable as "Good" case, but just in some strange contrived way. This particular example wouldn't even suffer much from a world without variables.

  alert('Hello ' + prompt('What is your name?'); + ', nice to see you!');

A better example would be to use some other code snippet to show the need for the repeated retrieval of the same data from the user over and over again.

#### Specific section or headline?
"What is a Variable?"

#### What did you expect to see?
An example that didn't use variables when trying to prove that variables were important.

#### Did you test this? If so, how?
Yes. I ran locally.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/variables`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/variables/index.html
* Last commit: https://github.com/mdn/content/commit/be3c3e06d1d9b59d2ad38a3a3e9eb59fbaa9c6f1
* Document last modified: 2021-06-10T18:50:18.000Z

</details>

**Comment by FarazzShaikh** [comment]
I agree, I also find it odd how an example trying to teach the absolute basics of JavaScript jumps right into an example with DOM Access and Events

We could simplify and improve these examples, any suggestions on examples we could use?

**Comment by NegiAkash890** [comment]
I think it would be to update the current example , to show how we can update the variable value as the paragraph states:

`
But one special thing about variables is that their contained values can change. 
`

For Ex :
```javascript
let container = 'John'
container = 'John Doe'

```

**Comment by FarazzShaikh** [comment]
That's a good idea. However, I think the idea of the original example was sound. It was trying to show how variables are useful.

> But one special thing about variables is that their contained values can change.

This line simply alludes to one characteristic of variables and thus building an example around that idea does not really show how variables are useful in JavaScript.

I think a better example would, as @evans23 suggested would be to show how variables can help with "repeated retrieval of data" and lead to less code duplication.

**Comment by evans23** [comment]
I think the problem is that the initial example isn't particularly dependent on forced variable usage. Maybe we change the initial example to something like this,

const button = document.querySelector('button');
let heading = document.querySelector('h1');

button.onclick = function() {
  let name = prompt('What is your name?');
  alert('Hello ' + name + ', nice to see you!');
  heading.textContent = 'Welecome ' + name;
}

Which would then force the user in the counter example to prompt the user twice, like this,

const button = document.querySelector('button');
let heading = document.querySelector('h1');

button.onclick = function() {
  alert('Hello ' + prompt('What is your name?') + ', nice to see you!');
  heading.textContent = 'Welecome ' + prompt('What is your name?');
}

**Comment by FarazzShaikh** [comment]
Yeah I think this is a good idea. I’ll submit a PR for this issue with this example. Unless you’d like to?

**Comment by evans23** [comment]
Fire away, I'm in and out here.
