### ISSUE TITLE
Issue with "Using the MediaStream Recording API": Why is half of this article about CSS?

### ISSUE THREAD

**Issue by amundo** [mdn/content#6232]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Using_the_MediaStream_Recording_API

#### What information was incorrect, unhelpful, or incomplete?

The about `CSS` in this article is distracting and irrelevant.

#### Specific section or headline?

“CSS goodies” and subsections. The look of the app is nice, and it could make a good standalone tutorial or blog post, but when people are looking for information about the Media Stream Recording API, this much CSS/design content is mostly irrelevant.

#### What did you expect to see?

Nothing about `CSS`, given that this is a tutorial on a Javascript API, the MediaStream Recording API.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediastream_recording_api/using_the_mediastream_recording_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Using_the_MediaStream_Recording_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediastream_recording_api/using_the_mediastream_recording_api/index.html
* Last commit: https://github.com/mdn/content/commit/91421a3b1ec8bb2ce93dcfa64dfe6f745f1fe0f9
* Document last modified: 2021-06-05T22:34:41.000Z

</details>

**Comment by rachelandrew** [comment]
Hi @amundo - this is a tutorial for doing a particular thing, which does require some CSS if you want it to look the same as the example. It's not a reference page, it pretty much is what you describe, a tutorial.

The section about CSS does give you a link to skip to the JavaScript part, so I'm not sure what harm it is doing. You could just ignore it.

For the basics of using the API, without any extras, the main page for the API should give you that https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/6232#issuecomment-866064968 — the article is a how-to illustration of making a media-recording app with an engaging user experience, part of which includes some CSS styling (since CSS is central in making engaging user experiences). Removing the parts that show how to CSS to improve the user experience would make for something less engaging and less real-world.
