### ISSUE TITLE
Issue with "Taking still photos with WebRTC": Dead link

### ISSUE THREAD

**Issue by BScheltema** [mdn/content#6236]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos

#### What information was incorrect, unhelpful, or incomplete?

The "Try this sample" link in the see also section goes to a sever that doesn't seem to exist anymore.

#### Specific section or headline?

See also section

#### What did you expect to see?

A working version of the sample.

#### Did you test this? If so, how?

Yes, I clicked the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webrtc_api/taking_still_photos`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webrtc_api/taking_still_photos/index.html
* Last commit: https://github.com/mdn/content/commit/da2f6f9af33bad517ff6f3ac02234ba251d74076
* Document last modified: 2021-06-07T01:27:38.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — we’re aware of the issue and https://github.com/mdn/content/discussions/5772 has been opened to discuss it the general problem. When that general issue gets resolved, we can update this issue too.

**Comment by sideshowbarker** [comment]
Closing here since we’re already tracking at #5772
