### ISSUE TITLE
Issue with "Sticky footers": link to masonry broken

### ISSUE THREAD

**Issue by moniuch** [mdn/content#6238]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers

#### Specific section or headline?
The section titled `grid-template-rows` at the bottom has a compatibility table, and one of the rows is for masonry - the URL it is linking to, seems to be broken.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/layout_cookbook/sticky_footers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/layout_cookbook/sticky_footers/index.html
* Last commit: https://github.com/mdn/content/commit/4df8fc624cb319731c0e0ad052348b2b0f62e59e
* Document last modified: 2021-06-11T11:56:01.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for raising this — I’ve opened two different issues with fixes: https://github.com/mdn/browser-compat-data/pull/11203 and https://github.com/mdn/content/pull/6239. Whichever one of those that gets merged first will cause this issue to automatically be marked as resolved, and closed.
