### ISSUE TITLE
[HTTP] EXIF image density is respected

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#6240]
## Acceptance criteria

1. - [ ] The listed features are documented sufficiently on MDN
2. - [ ] BCD is updated
3. - [ ] Interactive example and data repos are updated if appropriate
4. - [ ] The content has been reviewed as needed

## Features to document

1. Images should be able to declare their own intrinsic resolution/size (EXIF density not honored). This is related to HTTP device (screen) client hints. Formerly there was an HTTP Response Content-DPR that allowed a server to say what an image DPR is, the new way is for server to write this info into EXIF. 
   - A little context here: https://github.com/WICG/responsive-image-client-hints/issues/14#issuecomment-865413309
   - Explainer: https://github.com/eeeps/exif-intrinsic-sizing-explainer

## Related Gecko bugs
1. - [ ] [Images should be able to declare their own intrinsic resolution/size (EXIF density not honored)](https://bugzilla.mozilla.org/show_bug.cgi?id=1680387)

For folks helping with Firefox-related documentation features — make sure above AC have been done, but also:

* Set bugs to dev-doc-complete
* Add entry to Firefox release notes if feature is enabled in release
* Add entry to Firefox experimental features page if feature is not yet enabled in release

**Comment by hamishwillee** [comment]
Hi @Rumyra This came up as part of other work I have been doing so added it to the project. It is not strictly speaking HTTP but is related. Still don't fully understand scope but the spec where it came up for me is part of Responsive client hints: https://wicg.github.io/responsive-image-client-hints/

I'll put my name against it and try do it this week.

**Comment by Rumyra** [comment]
Thank you so much @hamishwillee 🙏

I might add a note to guidelines that this is a good process if release contributors find anything - creating issues for releases isn't a perfect science ☺️
