### ISSUE TITLE
Issue with "MediaStream": missing link for Using... topic

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#6241]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream

#### What information was incorrect, unhelpful, or incomplete?
"Using the MediaStream API" list item does not have a link.

#### Specific section or headline?
"See also" 

#### What did you expect to see?
A link for the stated subject.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediastream`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediastream/index.html
* Last commit: https://github.com/mdn/content/commit/eb7e32ed5416c6df836b7d8638b799cec79cb19e
* Document last modified: 2021-06-18T03:14:23.000Z

</details>

**Comment by FarazzShaikh** [comment]
It’s possible that the article does not exist. We’d be happy if you could write one yourself 😄

**Comment by sideshowbarker** [comment]
While we don’t have a “Using the MediaStream API” article, we do have a “Using the MediaStream Recording API” article — which, regardless, seems like a very useful See Also link to have in the MediaStream article. So I’ve opened https://github.com/mdn/content/pull/6245 with a change that replaces the current bullet item in that list with a working link to the “Using the MediaStream Recording API” article.
