### ISSUE TITLE
Issue with "DOMException": missing errors

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#6242]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMException

#### What information was incorrect, unhelpful, or incomplete?
Some errors are missing in the list of errors, like 2, 6, 10, and 16.

#### Specific section or headline?
"Error names"

#### What did you expect to see?
All errors.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/domexception`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMException
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/domexception/index.html
* Last commit: https://github.com/mdn/content/commit/bf3d143038cc4cba0b5f30e6f81428cf2d1d7fc0
* Document last modified: 2021-06-12T21:25:39.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6247 with a fix.
