### ISSUE TITLE
Issue with "DOMException()": page not found for "error constant" link

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#6243]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMException/DOMException

#### What information was incorrect, unhelpful, or incomplete?
Link for "error constant" (https://developer.mozilla.org/en-US/docs/Web/API/DOMException/Web/API/DOMException#Error_constants) gives page not found.

#### Specific section or headline?
Parameters -> name

#### What did you expect to see?
A valid link.

It also would be great if the Example "TBD" was replaced with and example :-)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/domexception/domexception`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMException/DOMException
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/domexception/domexception/index.html
* Last commit: https://github.com/mdn/content/commit/bf3d143038cc4cba0b5f30e6f81428cf2d1d7fc0
* Document last modified: 2021-06-12T21:25:39.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6246 with a fix for the broken link.

> It also would be great if the Example "TBD" was replaced with and example :-)

It’d be preferable to have a new separate issue for that, if you’re willing to raise one.
