### ISSUE TITLE
Issue with "First contentful paint": (short summary here please)

### ISSUE THREAD

**Issue by samersh1** [mdn/content#6244]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/First_contentful_paint

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/first_contentful_paint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/First_contentful_paint
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/first_contentful_paint/index.html
* Last commit: https://github.com/mdn/content/commit/c016a6b893578b1f39794983682c6d9107910226
* Document last modified: 2020-12-21T07:50:05.000Z

</details>

**Comment by FarazzShaikh** [comment]
Please describe the issue.
