### ISSUE TITLE
Issue with "PaintWorklet": Add note that this feature is disabled for elements inside <a href>

### ISSUE THREAD

**Issue by Kaiido** [mdn/content#6257]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PaintWorklet

#### What information was incorrect, unhelpful, or incomplete?
To avoid leaking visited links, this feature is currently disabled for anchor (`<a>`) elements with an `href` attribute.  
See https://github.com/w3c/css-houdini-drafts/issues/791 for details.

#### Specific section or headline?
N/A

#### What did you expect to see?
This page should probably have a note about this limitation, we already had two question on stackoverflow by users suprised about it, and while there is a [small note hidden in the specs](https://drafts.css-houdini.org/css-paint-api/#privacy-considerations), having a clear one in MDN's article would probably be helpful.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/paintworklet`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PaintWorklet
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/paintworklet/index.html
* Last commit: https://github.com/mdn/content/commit/86b8b22f13d0185d97089c61d50a2229d22ddf4a
* Document last modified: 2021-06-15T05:22:45.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/issues/6257 with a fix.
