### ISSUE TITLE
Issue with "margin": Show correct ordering of constituent properties

### ISSUE THREAD

**Issue by bibhas2** [mdn/content#6267]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/margin

#### What information was incorrect, unhelpful, or incomplete?
The ordering of the constituent properties (margin-top, margin-bottom etc.) are not stated anywhere. In fact the ``Constituent properties`` section shows the properties in incorrect order. This just leads to unnecessary errors and confusion. The correct ordering should be:

- margin-top
- margin-right
- margin-bottom
- margin-left

#### Specific section or headline?

The ``Constituent properties`` section.

#### What did you expect to see?

The correct ordering should be explicitly documented. At minimum, fix the ordering of the properties as described above.

The same issue goes for pretty much any page where the ``Constituent properties`` section exists.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/margin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/margin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/margin/index.html
* Last commit: https://github.com/mdn/content/commit/c2267059151f609904286ad6ceca6e91ccd01a5f
* Document last modified: 2021-06-17T03:05:19.000Z

</details>

**Comment by rachelandrew** [comment]
Hi @bibhas2 the properties are listed there in alphabetical order, however underneath in the syntax section is an example with a code comment, plus then a breakdown of how the values are assigned if you use one, two, three, or four values. 

> "When four values are specified, the margins apply to the top, right, bottom, and left in that order (clockwise)."

So I think the page does explain the correct order if you use all four.

**Comment by bibhas2** [comment]
It is true that one of the examples show the correct order. But it is too far below. And the incorrect ordering upfront adds to confusion. May be it is just me. Somehow it feels more beneficial to list the properties in correct order rather than be alphabetical. 

The problem is a little more acute in ``border-radius``. There is one example showing the four corners. But I need to fish it out of many examples. And there is no documentation of the ordering below the examples.

**Comment by dorward** [comment]
Your "correct order" is only correct when all four values are explicitly specified in the shorthand property.

If you were to say `margin: 10px 20px` then the correct order is:

* top/bottom
* left/right

and not

* top
* right
* bottom
* left

**Comment by rachelandrew** [comment]
I don't think there is an issue with this specific page. I think that alphabetical order is probably most sensible for the constituent properties, and the page does explain the order both in a syntax example and prose. Feel free to raise issues about other specific pages that do not have mention of the order in syntax and the prose.
