### ISSUE TITLE
Issue with "Images in HTML": Clarify why it’s recommened to specify width and height

### ISSUE THREAD

**Issue by Pound-Hash** [mdn/content#6272]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML

#### What information was incorrect, unhelpful, or incomplete?
The following paragraph is obscure: 

> This doesn't result in much difference to the display, under normal circumstances. But if the image isn't being displayed, for example, the user has just navigated to the page, and the image hasn't yet loaded, you'll notice the browser is leaving a space for the image to appear in:

Why would specifying the width and height result in any difference at all? The reader isn't given any reason to think this. Indeed, the purpose of the whole paragraph is unclear. The next paragraph states that doing this is a good thing. Then the following paragraph tells us we shouldn't do it. This is confusing.

#### Specific section or headline?
Width and height

#### What did you expect to see?
Clarity

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/images_in_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.html
* Last commit: https://github.com/mdn/content/commit/c4b2d25d04d21121f7d3e66da414c1e3107dff9f
* Document last modified: 2021-04-07T14:35:05.000Z

</details>

**Comment by dorward** [comment]
> Why would specifying the width and height result in any difference at all?

If you don't, then the browser doesn't know how much space to leave, so after the image does load it has to reflow the rest of the page. Which is not smooth. I agree the the page could be more detailed there.

> Then the following paragraph tells us we shouldn't do it. 

No. The following paragraph says you shouldn't use it to **resize** the image. You **should** specify the actual size of the image. I think the description on the page is fine.

**Comment by ConsciousClay** [comment]
Nowhere in that section does it mention specifying "actual"  size
dimensions.

I reread it several times and was still unsure of the meaning. Experts
should always try to take the perspective of those who know less than them.
Otherwise the effects of hindsight bias are plainly felt.

**Comment by ConsciousClay** [comment]
> > Why would specifying the width and height result in any difference at all?
> 
> If you don't, then the browser doesn't know how much space to leave, so after the image does load it has to reflow the rest of the page. Which is not smooth. I agree the the page could be more detailed there.
> 
> > Then the following paragraph tells us we shouldn't do it.
> 
> No. The following paragraph says you shouldn't use it to **resize** the image. You **should** specify the actual size of the image. I think the description on the page is fine.

What you said is not what the website says, so how could you think it's fine? There's an obvious disparity there. You're talking about actual sizes and the website isn't.

**Comment by dorward** [comment]
It does say that. It just doesn't use the worth 'actual' which I added for emphasis as you had misunderstood it. It could probably be made clearer, but it isn't wrong. I do not have the energy to debate this further.

**Comment by ConsciousClay** [comment]
Here's MDN's reference page on **<img>**:

> Use both width and height to set the **intrinsic** size of the image, allowing it to take up space before it loads, to mitigate content layout shifts.

And here's W3schools on <img>:

> **Note: Also, always specify the width and height of an image.** If width and height are not specified, the page might flicker while the image loads.

So it's thought best to be explicit in the references (for use by the knowledgable), but it's not best to be explicit in a beginner's tutorial.

And, no, I didn't misunderstand. I didn't post this issue because I didn't understand. I posted it to help other beginners who come here. What kind of person assumes the bungling ignorance of those who try to help?

**Comment by dorward** [comment]
Our communication styles do not seem to be compatible. The points I am trying to make keep being missed and the more I agree with you the worse it gets, to the point where you are accusing me of being something unpleasant. I shall not be participating in this ticket further as doing so only seems to make things worse.

**Comment by teoli2003** [comment]
Revisiting the article is surely something that has to be done. Note that there has been a lot of thoughts over the past few years over this problem and the situation is still settling. This article has a great overview: https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/

The CSS property `aspect-ratio` is a recent adition to release browsers (read: in 2021)

Hope this article will help whoever will submit a PR. :-)

**Comment by Pound-Hash** [comment]
Ah, MDN. The first group I offered to help with clarifying documentation, only to be abruptly told to stop submitting citations of grammatical errors. After a couple dozen hours volunteered, all while homeless and jobless, no thanks at all for my work. Go fuck yourselves, assholes.
