### ISSUE TITLE
Issue with "Images in HTML": (inappropriate use of a comma)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6274]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML

#### What information was incorrect, unhelpful, or incomplete?
"The resulting embedded image**,** is arguably easier to position and control than HTML images."

#### Specific section or headline?
CSS background images

#### What did you expect to see?
"The resulting embedded image is arguably easier to position and control than HTML images."

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/images_in_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.html
* Last commit: https://github.com/mdn/content/commit/c4b2d25d04d21121f7d3e66da414c1e3107dff9f
* Document last modified: 2021-04-07T14:35:05.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/6280 with a fix.
