### ISSUE TITLE
Issue with "Руководство часть 5: Создание домашней страницы": (short summary here please)

### ISSUE THREAD

**Issue by guranchik** [mdn/content#6275]
hello.when i made webside ,with tutorial help . I have a  trouble. how can i fix it?
![Uploading Здымак экрана, 2021-06-23 22-35-29.png…]()

**Comment by Ryuno-Ki** [comment]
Closing. This repository is meant for work on [MDN Web Docs](https://developer.mozilla.org).
Please use StackOverflow for support questions.

**Comment by guranchik** [comment]
ok,i'm sory

**Comment by Ryuno-Ki** [comment]
No worries. I hope you'll get your issue sorted.
