### ISSUE TITLE
Issue with "DOMException()": Example is needed, currently is "TBD"

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#6279]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMException/DOMException

#### What information was incorrect, unhelpful, or incomplete?
This is a follow-on to #6243.  The Example section says only "TBD".

#### Specific section or headline?
Example.

#### What did you expect to see?
An example of how to use DOMException().

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/domexception/domexception`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMException/DOMException
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/domexception/domexception/index.html
* Last commit: https://github.com/mdn/content/commit/bf3d143038cc4cba0b5f30e6f81428cf2d1d7fc0
* Document last modified: 2021-06-12T21:25:39.000Z

</details>

**Comment by FarazzShaikh** [comment]
@sideshowbarker will get on this later today, could please assign it to me?

**Comment by sideshowbarker** [comment]
> @sideshowbarker will get on this later today, could please assign it to me?

Yup, thanks much — now assigned
