### ISSUE TITLE
Issue with "Groups and ranges": No browser compatibility table present, and non-functional link to non-existent table

### ISSUE THREAD

**Issue by mstange** [mdn/content#6284]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges

#### What information was incorrect, unhelpful, or incomplete?

This page has the following note: "Note: Not all browsers support this feature; refer to the compatibility table."
But the link in the note doesn't work. It takes you to the top of the page. And there is no compatibility table on the page.

#### Specific section or headline?

"Using named groups"

#### What did you expect to see?

Either no broken link, or an actual compatibility table.

#### Did you test this? If so, how?

n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions/groups_and_ranges`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/groups_and_ranges/index.html
* Last commit: https://github.com/mdn/content/commit/179e7d3a709f897d33ac9b833d9caff99f7396a3
* Document last modified: 2021-05-05T16:43:40.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/6286 with a fix.

**Comment by mstange** [comment]
Thanks for fixing!
