### ISSUE TITLE
Issue with "HTML elements reference": (short summary here please)

### ISSUE THREAD

**Issue by rich-tweed** [mdn/content#6299]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element

#### What information was incorrect, unhelpful, or incomplete?
The `<rb>` and `<rtc>` tags are listed under both 'Inline text semantics' and 'Obsolete and deprecated elements'. 

#### Specific section or headline?
'Inline text semantics' and 'Obsolete and deprecated elements'

#### What did you expect to see?
The elements placed under one or the other, or at least a note stating that they do belong in both sections if that is the case.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/index.html
* Last commit: https://github.com/mdn/content/commit/f988103f96564329b823f3482e9ab450e3c330ce
* Document last modified: 2021-05-14T08:02:56.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/issues/6299 with a fix.
