### ISSUE TITLE
Issue with "hyphens": misleading use of &shy;

### ISSUE THREAD

**Issue by wiiiiilllllll** [mdn/content#6307]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens

#### What information was incorrect, unhelpful, or incomplete?
The embedded demo at the top of the page uses the text "An extraordinarily long English word!" to demonstrate the `hyphens` CSS property. The demo includes a soft hyphen `&shy;` inside the word "extraordinarily", but this is not mentioned anywhere in the explanatory text. It implies that the text in the demo is hyphenated purely by CSS.

#### Specific section or headline?
Embedded demo at the top of the page.

#### What did you expect to see?
Viewing the page in a browser which doesn't support `hyphens` (such as Edge 91) I would expect to see an unhyphenated piece of text, or a separate demo for `&shy;`.

#### Did you test this? If so, how?
Visited in Edge 91. I removed the soft hyphen using dev tools; hyphenation no longer works in the demo.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/hyphens`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/hyphens/index.html
* Last commit: https://github.com/mdn/content/commit/8bc3398ff8f2f2f3c836825cf7adb3e325a811cc
* Document last modified: 2021-06-17T02:43:53.000Z

</details>

**Comment by FarazzShaikh** [comment]
I think we could remove the hyphen from "extraordinarily". Most uses i have seen of the word do not have a hyphen in them anyway. I will PR that in later today.

**Comment by wiiiiilllllll** [comment]
Thank you!

I do think soft hyphens are a totally valid method of hyphenation and they
deserve documentation on MDN, whether that's on this page or somewhere
else.

**Comment by FarazzShaikh** [comment]
On second though, Within the [Suggesting line break opportunities](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#suggesting_line_break_opportunities) section it is explained:

> An invisible, "soft" hyphen. This character is not rendered visibly; instead, it marks a place where the browser should break the word if hyphenation is necessary. In HTML, use `&shy;` to insert a soft hyphen.

It is also explained in the `auto` section:

> However, suggested line break opportunities (see Suggesting line break opportunities below) will override automatic break point selection when present.

It appears as though in "manual" mode, the text is indeed being hyphenated purely using CSS.

Aren't
