### ISSUE TITLE
Issue with "Spread syntax (...)": grammatical error

### ISSUE THREAD

**Issue by jonathan-graf** [mdn/content#6308]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

#### What information was incorrect, unhelpful, or incomplete?
This sentence may have a grammatical error:
`It copies own enumerable properties from a provided object onto a new object.`

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals

#### What did you expect to see?
I think perhaps the author meant to write:
`It copies its own enumerable properties from a provided object onto a new object.`

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/spread_syntax`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/spread_syntax/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by sideshowbarker** [comment]
It’s not actually a grammatical error. *“It copies own enumerable properties from a provided object onto a new object”* is correct.

“own enumerable properties” is a specific term of art in JavaScript — see for example the results at https://www.google.com/search?q=%22own+enumerable+properties%22

So I’m not sure we should actually change this — unless somebody has a proposal for how to change it without altering the meaning.

I’ll leave this open for discussion.

**Comment by jonathan-graf** [comment]
My apologies, I come from a Java background and have been modifying JS and TS software as needed but it seems there are JS terms I am completely unfamiliar with and in this case, I confused the term with being a typo.

**Comment by sideshowbarker** [comment]
> My apologies, I come from a Java background and have been modifying JS and TS software as needed but it seems there are JS terms I am completely unfamiliar with and in this case, I confused the term with being a typo.

No problem — I think many other readers probably read it in the same way you did. Rightly, we should have the term “own properties” defined somewhere, and make every use of it a reference.

But we have many such uses in the current MDN sources — see https://github.com/mdn/content/search?q=%22own+properties%22 — so it would require touching the sources of a lot of articles other than just the “Spread syntax” article. So I guess it’s best to leave it for now — until somebody more ambitious (and less lazy) than me feels like taking on the task of making all the changes that’d be needed…
