### ISSUE TITLE
Issue with "padding-block": misleading note about it accepting the same values as padding-left

### ISSUE THREAD

**Issue by LeaVerou** [mdn/content#6309]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block

"The padding-block property takes the same values as the padding-left property."

This is very misleading, because `padding-block` accepts one or two lengths, whereas `padding-left` only accepts one length, so they do *not* take the same values!

Similar confusing note in the pages for `padding-inline`, `margin-block`, `margin-inline`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/padding-block`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/padding-block/index.html
* Last commit: https://github.com/mdn/content/commit/c2267059151f609904286ad6ceca6e91ccd01a5f
* Document last modified: 2021-06-17T03:05:19.000Z

</details>

**Comment by kaushambisharma** [comment]
I'd like to work on this.

**Comment by teoli2003** [comment]
I think per #6476, this should be closed.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/6309#issuecomment-873523581
