### ISSUE TITLE
Obscene title in end of an article using Russian language.

### ISSUE THREAD

**Issue by ZirionNeft** [mdn/content#631]
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Errors/invalid_right_hand_side_instanceof_operand

**Comment by mattiapontonio** [comment]
I translated the title. It is actually off topic. But to my knowledge the language content is blocked, it's not them on GitHub.

**Comment by ZirionNeft** [comment]
What do you mean? Then where i could report that I found?

**Comment by mattiapontonio** [comment]
Actually I don't know.
I tag @chrisdavidmills.

**Comment by nschonni** [comment]
I believe the content is over https://github.com/mdn/translated-content, but I don't know if they are landing any PRs there yet

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations at the moment. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.

**Comment by nschonni** [comment]
@chrisdavidmills might be worth transferring these issues over to the `translated-content` repo so they can be tackled when you do start accepting PRs
