### ISSUE TITLE
Issue with "Writing WebSocket client applications": (short summary here please)

### ISSUE THREAD

**Issue by Elijah-Watson** [mdn/content#6312]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications

#### What information was incorrect, unhelpful, or incomplete?
The second note at the top of the article contains a broken link.  It is the hyperlink on the word "yourself" that is supposed to link to an example of the code in the article.  The broken link is "https://mdn-samples.mozilla.org/s/websocket-chat".

#### Specific section or headline?
The second note at the top of the article.

#### What did you expect to see?
A functional link.

#### Did you test this? If so, how?
Yes; by clicking on the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/websockets_api/writing_websocket_client_applications`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/websockets_api/writing_websocket_client_applications/index.html
* Last commit: https://github.com/mdn/content/commit/ba4a07195d8f8f4941e7ae06118b8405f9cac9cf
* Document last modified: 2021-04-10T23:58:36.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — we’re aware of the issue and https://github.com/mdn/content/discussions/5772 has been opened to discuss it the general problem. When that general issue gets resolved, we can update this issue too.

**Comment by sideshowbarker** [comment]
Closing here now since we’re already tracking at #5772
