### ISSUE TITLE
Issue with "Multimedia and Embedding": (Web literacy hyperlink broken)

### ISSUE THREAD

**Issue by CoralLemons** [mdn/content#6315]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding

#### What information was incorrect, unhelpful, or incomplete?
Web literacy 2 hyperlink opens new blank tab with error; page not found

#### Specific section or headline?
https://teach.mozilla.org/activities/web-lit-basics-two/

#### What did you expect to see?
the hyperlink listed above

#### Did you test this? If so, how?
no, opens new tab with "page cannot be found" redirect 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/index.html
* Last commit: https://github.com/mdn/content/commit/2c6f017de416f5817a109191417d549c60e90055
* Document last modified: 2021-04-14T07:08:39.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve raised https://github.com/mdn/content/pull/6319 with a fix
