### ISSUE TITLE
Issue with "Document.forms": it returns element, not Collection

### ISSUE THREAD

**Issue by ssk910** [mdn/content#6325]
MDN URL: https://developer.mozilla.org/ko/docs/Web/API/Document/forms

#### What information was incorrect, unhelpful, or incomplete?

I found a case that `document.forms` returns `element`, not `Collection`.

#### What did you expect to see?

As your document, it should return only `Collection`.

#### Did you test this? If so, how?

| Browser | Version | JS Engine |
| ---- | ---- | ---- |
| Chrome | 91.0.4472.114 | V8 9.1.269.36 |

If html has `<form>` elements more than one, `document.forms` returns `Collection`.
But, if html has only one `<form>` element, `document.forms` returns `element` which is child of `<form>`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ko/web/api/document/forms`
* MDN URL: https://developer.mozilla.org/ko/docs/Web/API/Document/forms
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ko/web/api/document/forms/index.html
* Last commit: https://github.com/mdn/translated-content/commit/52ccdf1f0a1cee3f0659ac78e81c79dae152399b
* Document last modified: 2021-06-23T00:34:06.000Z

</details>

**Comment by FarazzShaikh** [comment]
`document.forms` returns an **`HTMLCollection` of elements.** Even a single form returns a `HTMLCollection` of that element. Here is a [fiddle](https://jsfiddle.net/farazshaikh/twneqv63/). If you're having this problem could you please share your code?

**Comment by sideshowbarker** [comment]
Closing this for lack of response.
