### ISSUE TITLE
Issue with "HTMLOrForeignElement.dataset": Not quite accurate

### ISSUE THREAD

**Issue by PinkDuck** [mdn/content#6326]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset

#### What information was incorrect, unhelpful, or incomplete?
Under name conversion, 'Other characters (including other dashes) are left unchanged' suggests just that. Except if a data attribute is set with uppercase then that IS transformed into lower case within dataset. e.g. data-TEST > dataset.test.

#### Specific section or headline?
Name conversion

#### What did you expect to see?
Rules adequately explaining the transform logic

#### Did you test this? If so, how?
Yes, in Fx 89.0.1 JS

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlorforeignelement/dataset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlorforeignelement/dataset/index.html
* Last commit: https://github.com/mdn/content/commit/11c96e424b376432f8ab8ebb12a40e5383e31e9d
* Document last modified: 2021-03-30T03:01:23.000Z

</details>

**Comment by teoli2003** [comment]
Thanks for the report. You are right the explanation was not explicitely listing the conversion from upper- to lowercase.
