### ISSUE TITLE
Issue with "let or var": (Translation problems)

### ISSUE THREAD

**Issue by powercandy** [mdn/content#6330]
MDN URL: https://developer.mozilla.org/zh-CN/docs/learn/JavaScript/Building_blocks/Functions

#### What information was incorrect, unhelpful, or incomplete?

why use `let` in en docs, use `var` in zh-CN docs? 

#### Specific section or headline?

函数作用域和冲突

#### What did you expect to see?

change `var` to `let` or remove `另外，第二次尝试使用 let 关键字定义 name 变量导致了一个错误。`

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/learn/javascript/building_blocks/functions`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/learn/JavaScript/Building_blocks/Functions
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/building_blocks/functions/index.html
* Last commit: https://github.com/mdn/translated-content/commit/52ccdf1f0a1cee3f0659ac78e81c79dae152399b
* Document last modified: 2021-06-23T00:34:06.000Z

</details>

**Comment by sideshowbarker** [comment]
@mdn/yari-content-zh

**Comment by irvin** [comment]
welcome to submit PR to update the zh-can docs according to current english origin.

**Comment by powercandy** [comment]
> welcome to submit PR to update the zh-can docs according to current english origin.

okay
