### ISSUE TITLE
Issue with "Object.defineProperty()": (reset value will not error)

### ISSUE THREAD

**Issue by changeLong** [mdn/content#6331]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

chrome 90.0.4430.85

#### Did you test this? If so, how?
```
const object1 = {};

Object.defineProperty(object1, 'property1', {
  value: 42,
  writable: false
});

object1.property1 = 77;
// nothing happen !!!!!!! not error
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/object/defineproperty`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/object/defineproperty/index.html
* Last commit: https://github.com/mdn/translated-content/commit/52ccdf1f0a1cee3f0659ac78e81c79dae152399b
* Document last modified: 2021-06-23T00:34:06.000Z

</details>

**Comment by Prerna237** [comment]
Hi. Found this in the Writable Attribute section in the English version of the page - " As seen in the example, trying to write into the non-writable property doesn't change it but doesn't throw an error either ". The behaviour you are seeing is correct. 

If you log the value of object1.property1, the value will be 42.

**Comment by sideshowbarker** [comment]
@mdn/yari-content-zh

**Comment by irvin** [comment]
from Prerna's comment this is corrent, safe to close.

**Comment by sideshowbarker** [comment]
Thanks @irvin — closing per https://github.com/mdn/content/issues/6331#issuecomment-872762755
