### ISSUE TITLE
Issue with "What went wrong? Troubleshooting JavaScript": (just a proposal)

### ISSUE THREAD

**Issue by louistimti** [mdn/content#6334]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong

#### What information was incorrect, unhelpful, or incomplete?

Concerns warning against injected code from using live servers with code editors which could push the error code line much down when checking on the console.

#### Specific section or headline?

To be added in number 3 of section "Fixing Syntax Errors".

#### What did you expect to see?

A small text indicating to be aware of injected code from live server extensions from code editors etc.

#### Did you test this? If so, how?

Nope, just a proposal to add words.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/what_went_wrong`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_went_wrong
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/what_went_wrong/index.html
* Last commit: https://github.com/mdn/content/commit/33aaca169a01885174e3cf61c61801a5666c27e3
* Document last modified: 2021-04-03T12:54:32.000Z

</details>

**Comment by kylewcode** [comment]
I've tested the potential issue and found it to be correct using VSCode and its [Live Server extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer). The line where the error occurs has changed. See images.

Injected code
![image](https://user-images.githubusercontent.com/35872523/201934537-cf542ec0-9f2b-4021-b03e-50501cb71486.png)

Error now on new line. Current page states the error is on line 86.
![image](https://user-images.githubusercontent.com/35872523/201934633-adec8ddc-1a12-41a8-94bc-2a2ec979f731.png)
