### ISSUE TITLE
Issue with "How to fix a website with blocked mixed content": …

### ISSUE THREAD

**Issue by gbusan** [mdn/content#634]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content

In the documentation there is this sentence:

**For other domains, use the site's HTTPS version if available. If HTTPS is not available, you can try contacting the domain and asking them if they can make the content available via HTTPS.**

My question is: and if is **not possible** for them to make the content available via HTTPS, and that content is mandatory for my application? The only solution is to serve all my application in http?

**Comment by hamishwillee** [comment]
Unless the content from the other site results in the page being mixed _passive_ content, you're correct. You can't serve mixed active content on modern versions of most browsers and many are moving to blocking mixed passive content too.

So yes, you can try serving in HTTP, get them to serve it in HTTPS, or you can ask them whether you can host some of the content yourself.

**Comment by hamishwillee** [comment]
PS Note, no need for docs change  following this question
