### ISSUE TITLE
Issue with "Video and audio content": (typo)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6340]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content

#### What information was incorrect, unhelpful, or incomplete?
![image](https://user-images.githubusercontent.com/51193876/123454100-096e5080-d595-11eb-8680-8f32803c855b.png)

#### Specific section or headline?
Contents of a media file

#### What did you expect to see?
English words

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/video_and_audio_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/video_and_audio_content/index.html
* Last commit: https://github.com/mdn/content/commit/bb51655f7c0823e364fecb9a6c5ee0e5d04ca28f
* Document last modified: 2021-06-03T15:52:42.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Thanks for informing us about this.

To whomever is fixing this, the change in question has to happen in this file:

https://github.com/mdn/content/blob/526d8cdd696a42a250309de5d1a2467be4fbbc06/files/en-us/learn/html/multimedia_and_embedding/video_and_audio_content/containersandtracks.svg

**Comment by sideshowbarker** [comment]
I see @NegiAkash890 opened https://github.com/mdn/content/pull/6346 for this.
