### ISSUE TITLE
Issue with "Media container formats (file types)": (typo)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6344]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers

#### What information was incorrect, unhelpful, or incomplete?

> using a lossless compressed format at least prevent the accumulation of noise

#### Specific section or headline?
Guidelines

#### What did you expect to see?
...using a lossless compressed format at least prevent**S** the accumulation of noise...

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/media/formats/containers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/media/formats/containers/index.html
* Last commit: https://github.com/mdn/content/commit/05484de90272dc19c4ca833601ab5927e2cc9419
* Document last modified: 2021-03-17T10:20:08.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6422 with a fix.
