### ISSUE TITLE
Issue with "Media container formats (file types)": (the link for "MPEG-4 (MP4)" is broken)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6345]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers

#### What information was incorrect, unhelpful, or incomplete?
![image](https://user-images.githubusercontent.com/51193876/123458574-0a55b100-d59a-11eb-81d6-ba56bddb9dae.png)

#### Specific section or headline?
Index of media container formats (file types)

#### What did you expect to see?
A working link

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/media/formats/containers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/media/formats/containers/index.html
* Last commit: https://github.com/mdn/content/commit/05484de90272dc19c4ca833601ab5927e2cc9419
* Document last modified: 2021-03-17T10:20:08.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6422 with a fix.
