### ISSUE TITLE
Issue with "Video and audio content": (incorrect grammar)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6347]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content

#### What information was incorrect, unhelpful, or incomplete?
Finally, add label to help readers **identifying** the language they are searching for.

#### Specific section or headline?
Displaying video text tracks

#### What did you expect to see?
Finally, add label to help readers **identify** the language they are searching for.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/video_and_audio_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/video_and_audio_content/index.html
* Last commit: https://github.com/mdn/content/commit/bb51655f7c0823e364fecb9a6c5ee0e5d04ca28f
* Document last modified: 2021-06-03T15:52:42.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6421 with a fix.
