### ISSUE TITLE
Issue with "From object to iframe — other embedding technologi…": (ambiguous phrasing)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6351]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies

#### What information was incorrect, unhelpful, or incomplete?
... because of the second benefit of HTTPS above, no matter what the cost, you must never embed third-party content with HTTP. 

#### Specific section or headline?
Use HTTPS

#### What did you expect to see?
When it says "you must never embed third-party content with HTTP", is it saying that the content's _source_ must never be using the HTTP protocol, or is it saying that the _local_ server must never be using the HTTP protocol?

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/other_embedding_technologies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.html
* Last commit: https://github.com/mdn/content/commit/75c1271189903b4d96433a34a8174175dd089ef2
* Document last modified: 2021-04-28T14:08:28.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened with an update.
