### ISSUE TITLE
Issue with "Héritage et chaîne de prototype": (short summary here please)

### ISSUE THREAD

**Issue by feralfer** [mdn/content#6361]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Inheritance_and_the_prototype_chain

#### What information was incorrect, unhelpful, or incomplete?
Cela est équivalent à la propriété JavaScript __proto__ qui **était non-standard avant ES2015** mais qui était de fait implémentée par la majorité des navigateurs.

#### What did you expect to see?
This is equivalent to the JavaScript property __proto__ which is non-standard but de-facto implemented by many browsers. 

can be translated to French by 

Cela est équivalent à la propriété JavaScript __proto__ qui **est non-standard**  mais était de fait implémentée par la majorité des navigateurs.

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/javascript/inheritance_and_the_prototype_chain`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Inheritance_and_the_prototype_chain
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/inheritance_and_the_prototype_chain/index.html
* Last commit: https://github.com/mdn/translated-content/commit/52ccdf1f0a1cee3f0659ac78e81c79dae152399b
* Document last modified: 2021-06-23T00:34:06.000Z

</details>

**Comment by teoli2003** [comment]
cc/ @SphinxKnight

**Comment by feralfer** [comment]
En lisant "qui était non-standard avant ES2015" on se demande si __proto-- est devenu standard avec ES2015.
Le texte en anglais est très clair sur le fait que __proto__ n'a jamais été et n'est pas standard.

Étant donnée la précision requise pour expliquer les subtilités de JavaScript, il me semble dangereux de s'écarter du texte anglais en ajoutant dans la version française ce qui ressemble à des interprétations, des commentaires ou tout simplement des erreurs de traduction.

J'ai constaté que la traduction française concernant JavaScript comporte malheureusement de très nombreuses erreurs ou au moins ambiguïtés de cette nature, rendant la bonne compréhension encore plus délicate qu'en anglais.

Dans l'état actuel de la traduction française, je conseillerais de ne pas la lire et de se référer à l'anglais si on le parle.

De mon côté, je suis prêt aider à la traduction en français autant que mon temps le permet.

 Merci malgré tout à tous ceux qui ont contribué à la traduction actuelle et j'espère que mon commentaire sera perçu positivement et ne les découragera pas, mais comme dit le proverbe "les routes qui mènent à l'enfer sont pavées de bonnes intentions".

Bien cordialement
