### ISSUE TITLE
Content bug: underline of <a> causing " || " to read as ".|_|."

### ISSUE THREAD

**Issue by anujjoshi63** [mdn/content#6368]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#assigning_a_default_value_to_a_variable

## Specific page section or heading?

Problem can be found in \<code> part in line just below the heading "Assigning a default value to a variable".

## What is the problem?

![image](https://user-images.githubusercontent.com/14955086/123513513-3dd43080-d6ab-11eb-8997-486d8d908247.png)

## What did you expect to see?

![image](https://user-images.githubusercontent.com/14955086/123513568-7e33ae80-d6ab-11eb-8274-3b144e40a0d9.png)

Solution: Having \<code> tag inside of \<a> tag solves the issue
## Did you test this? If so, how?

Tested on various browsers and found out that this issue is not browser specific.

**Comment by anujjoshi63** [comment]
PS: I would like to solve this

**Comment by sideshowbarker** [comment]
This is interesting. I personally never noticed the difference in rendering behavior of something like `<code><a>||</a></code>` vs `<a><code>||</code></a>` — but clearly the `<a><code>||</code></a>` rendering is preferable. So that suggests we should have a style policy that `<a><code>||</code></a>` should be used instead. And maybe also we should have Yari flag cases like `<code><a>||</a></code>` as flaws. Would be good to hear from @mdn/core-dev about that.

**Comment by anujjoshi63** [comment]
> This is interesting. I personally never noticed the difference in rendering behavior of something like `<code><a>||</a></code>` vs `<a><code>||</code></a>` — but clearly the `<a><code>||</code></a>` rendering is preferable. So that suggests we should have a style policy that `<a><code>||</code></a>` should be used instead. And maybe also we should have Yari flag cases like `<code><a>||</a></code>` as flaws. Would be good to hear from @mdn/core-dev about that.

I don't think it will cause a rendering issue elsewhere (where || is not present). But yes, I agree with you :)

**Comment by sideshowbarker** [comment]
> I don't think it will cause a rendering issue elsewhere (where || is not present). But yes, I agree with you :)

Well I was thinking that in general it will happen with any glyphs that have parts which descend below the baseline — so g, j, p, q, y as well as `,` and `;` and `{ }` and `[ ]`. And those cases might not look at as bad as the || ends up looking, but they can still look suboptimal.

Another thing is, when we migrate everything to Markdown, if we did a naive conversion of `<code><a>anything</a></code>` to Markdown, we’re anyway not gonna end up with hyperlink but

**Comment by anujjoshi63** [comment]
> Well I was thinking that in general it will happen with any glyphs that have parts which descend below the baseline — so g, j, p, q, y as well as `,` and `;` and `{ }` and `[ ]`. And those cases might not look at as bad as the || ends up looking, but they can still look suboptimal.


Agreed. 
Also, as you said, there should be a style policy that  `<a><code>anything</code></a>` should be used because I think
<code><a href="https://example.com">Click here for more <code>anything</code></a></code> is much better than just <code>Click here for more <code><a href="https://example.com">anything</a></code></code>

> Another thing is, when we migrate everything to Markdown, if we did a naive conversion of `<code><a href="https://example.com>anything</a></code>` to Markdown, we’re anyway not gonna end up with a hyperlink in output but instead we’re gonna end up with a literal `[anything](https://example.com)` string.

This is serious enough. Definitely needs more attention.

**Comment by sideshowbarker** [comment]
I don’t think I’d actually intended to re-open this — so, closing again now
