### ISSUE TITLE
Issue with "The box model": Missing box-module link in "In this Module" section

### ISSUE THREAD

**Issue by mehnazyunus** [mdn/content#6376]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model

#### What information was incorrect, unhelpful, or incomplete?
Link to box module page is missing.

#### Specific section or headline?
"In this module" (at the end)

#### What did you expect to see?
3rd bullet should be **3.The box model**

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/the_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/the_box_model/index.html
* Last commit: https://github.com/mdn/content/commit/e38c6d165569733ef71c6e5052acfaf67cb5a801
* Document last modified: 2021-06-17T07:44:11.000Z

</details>

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/content/pull/6278 (but not yet deployed to the production MDN site)
