### ISSUE TITLE
Issue with "400 Bad Request": (short summary here please)

### ISSUE THREAD

**Issue by Francilda** [mdn/content#6377]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/400

#### Specific section or headline?
Não que entra no site

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/web/http/status/400`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/400
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/http/status/400/index.html
* Last commit: https://github.com/mdn/translated-content/commit/52ccdf1f0a1cee3f0659ac78e81c79dae152399b
* Document last modified: 2021-06-23T00:34:06.000Z

</details>

**Comment by Francilda** [comment]
Não quer entra pra prosseguir o pagamento nem pra colocar as informações de pagamento

**Comment by sideshowbarker** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
