### ISSUE TITLE
Issue with "Adding vector graphics to the Web": (ambiguous terminology)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6378]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web

#### What information was incorrect, unhelpful, or incomplete?
Make sure your SVG code snippet begins and ends with the <svg></svg> tags (don't include anything **outside** those.)

#### Specific section or headline?
How to include SVG code inside your HTML

#### What did you expect to see?
What does **outside** mean? Outside the tags? How can someone _include_ something on the **outside**?

I think the sentence was meant to be: "don't include anything **other than** those"

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web/index.html
* Last commit: https://github.com/mdn/content/commit/75c1271189903b4d96433a34a8174175dd089ef2
* Document last modified: 2021-04-28T14:08:28.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6385 with a fix.
