### ISSUE TITLE
Issue with "Working with Mozilla source code": …

### ISSUE THREAD

**Issue by bsammon** [mdn/content#638]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code

When I click on the "Downloading the source code" link, I get to a "Page not found" page

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/developer_guide/source_code`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/developer_guide/source_code/index.html
* Report started: 2020-12-25T04:11:02.979Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. I’ve raised https://github.com/mdn/content/pull/653 with a fix.
