### ISSUE TITLE
Issue with "Cascade and inheritance"

### ISSUE THREAD

**Issue by SebastienWae** [mdn/content#6384]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

I find the article quite confusing (Miriam Suzanne's video helps a lot, but I'm focusing on the written content), mainly because the terms "cascade" and "order of appearance" seems to be used interchangeably, but also because some information are missing and I think inheritance can be introduced separately after someone understand the cascade.

Here's a quick outline of the 2 pages that would make more sense in my opinion:

**The Cascade**
  - Intro
    - conflicting rules
    - the cascade order
  - Origin and Importance
    - author
    - user
    - user agent
    - !important
    - the order
    - (animation & transition ?)
  - (Context ?)
  - Specificity
  - Order of Appearance
  - Understanding how the concepts work together (Miriam Suzanne's video)

**Inheritance**
  - Intro
  - Initial
  - Inherit
  - Unset
  - Revert
  - Inheritable properties ([mdn/content#3622](https://github.com/mdn/content/issues/3622)?)

This would better match the CSS specs from my point of view.

A lot of the existing content and examples can be reused and I'm definitely up to make the changes and write the rest myself but since it's a substantial change and my first contribution to mdn I'd like to get some input before submitting a PR.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.html
* Last commit: https://github.com/mdn/content/commit/1fdf7958ea85bab45e1d7ba3634e9381eae937d1
* Document last modified: 2021-01-27T07:42:45.000Z

</details>

**Comment by rachelandrew** [comment]
Hi @SebastienWae 

I'd be very happy for you to have a go at rewriting it, some fresh eyes would be excellent.

As it's a bigger change it would be helpful for you to set up the project using the instructions in the Readme as then you'd be able to preview your own work. 

Other than that, if you add me as a reviewer once you have a PR, I can take a look.

**Comment by rachelandrew** [comment]
@SebastienWae are you intending to work on this?

**Comment by SebastienWae** [comment]
> @SebastienWae are you intending to work on this?

Yes, sorry for not replying earlier.
I already started, I’ll send a first draft in a day or two to get some feedbacks.
