### ISSUE TITLE
Issue with "handler.isExtensible()": translation error

### ISSUE THREAD

**Issue by DavidSama1993** [mdn/content#6388]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/isExtensible

#### What information was incorrect, unhelpful, or incomplete?
The additional remarks of item 'Invariants' in Chinese translation is incorrect.

#### Specific section or headline?
> "也就是必须返回true或者为true的值,返回false和为false的值都会报错。"

#### What did you expect to see?
也就是若Object.isExtensible(target)返回true, handler.isExtensible()必须返回true或者为true的值，若Object.isExtensible(target)返回false, handler.isExtensible()必须返回false或者为false的值

#### Did you test this? If so, how?
```
const obj1 = {};
const p1_true = new Proxy(obj1, {
    isExtensible(target) {
        return true;
    }
})
const p1_false = new Proxy(obj1, {
    isExtensible(target) {
        return false;
    }
})
console.log(Object.isExtensible(p1_true)); // true
console.log(Object.isExtensible(p1_false)); // TypeError

const obj2 = Object.preventExtensions({});
// const obj2 = Object.freeze({});
// const obj2 = Object.seal({});
const p2_true = new Proxy(obj2, {
    isExtensible(target) {
        return true;
    }
})
const p2_false = new Proxy(obj2, {
    isExtensible(target) {
        return false;
    }
})
console.log(Object.isExtensible(p2_true)); // TypeError
console.log(Object.isExtensible(p2_false)); // false
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/proxy/proxy/isextensible`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/isExtensible
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/proxy/proxy/isextensible/index.html
* Last commit: https://github.com/mdn/translated-content/commit/52ccdf1f0a1cee3f0659ac78e81c79dae152399b
* Document last modified: 2021-06-23T00:34:06.000Z

</details>

**Comment by sideshowbarker** [comment]
@mdn/yari-content-zh

**Comment by irvin** [comment]
Feel free to send PR to https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/proxy/proxy/isextensible/index.html

Also, in the future please open issues for zh-cn docs in this repo - 
https://github.com/mdn/translated-content/issues?q=is%3Aopen+is%3Aissue+label%3Al10n-zh

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/6388#issuecomment-872761299
