### ISSUE TITLE
Content bug: Math.PI formula error

### ISSUE THREAD

**Issue by hochan222** [mdn/content#6390]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/PI

## Specific page section or heading?

/Web/JavaScript/Reference/Global_Objects/Math/PI

head: Math.PI

## What is the problem?

![image](https://user-images.githubusercontent.com/22424891/123544154-e7d7b980-d78c-11eb-9d42-feb934be829f.png)

```html
<p><math display="block"><semantics><mrow><mstyle mathvariant="monospace"><mi>Math.PI</mi></mstyle><mo>=</mo><mi>π</mi><mo>≈</mo><mn>3.14159</mn></mrow><annotation encoding="TeX">\mathtt{\mi{Math.PI}} = \pi \approx 3.14159</annotation></semantics></math></p>
```

Something is wrong. What do you hope for the following text to be written? Is it broken because tags are no longer supported? If something is wrong, what information can I refer to to fix it?

## What did you expect to see?

I'm not sure, but I think it should be in a readable state.

**Comment by sideshowbarker** [comment]
Thanks for reporting this — it’s a known issue and we’re using https://github.com/mdn/content/issues/3435 to track it
