### ISSUE TITLE
Issue with "Multimedia and Embedding": (short summary here please)

### ISSUE THREAD

**Issue by adovemu** [mdn/content#6391]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding

#### What information was incorrect, unhelpful, or incomplete?
- broken link under 'See also'. Web literacy basics 2 points to https://teach.mozilla.org/activities/web-lit-basics-two/ which is broken.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/index.html
* Last commit: https://github.com/mdn/content/commit/2c6f017de416f5817a109191417d549c60e90055
* Document last modified: 2021-04-14T07:08:39.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Confirmed.

Whoever is going to fix this will need to delete these lines:

https://github.com/mdn/content/blob/1c67c18644267073df76203d16394cf35c2bfff9/files/en-us/learn/html/multimedia_and_embedding/index.html#L80-L83

Looks like Mozilla has no Teaching Area outside of MDN Web Docs anymore.

**Comment by sideshowbarker** [comment]
I believe this was fixed already by https://github.com/mdn/content/pull/6319.
