### ISSUE TITLE
Issue with "Responsive images": (what is meant by the "art direction problem"?)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6397]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

#### What information was incorrect, unhelpful, or incomplete?
An improvement would be to display a cropped version of the image which displays the important details of the image when the site is viewed on a narrow screen. A second cropped image could be displayed for a medium width screen device, like a tablet. This is commonly known as the **art direction problem**.

#### Specific section or headline?
Why responsive images?

#### What did you expect to see?
Does the **art direction problem** refer to the improvement cited in the first sentence of this paragraph? Or does it refer to the apparent solution given in the second paragraph? I'm confused.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.html
* Last commit: https://github.com/mdn/content/commit/be3c3e06d1d9b59d2ad38a3a3e9eb59fbaa9c6f1
* Document last modified: 2021-06-10T18:50:18.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6412 with a fix.
