### ISSUE TITLE
Issue with "Responsive images": (wrong grammar)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6398]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

#### What information was incorrect, unhelpful, or incomplete?
mobile users don't want to waste bandwidth by downloading a large image intended for desktop

#### Specific section or headline?
Why responsive images?

#### What did you expect to see?
The term "desktop" is countable and requires an article.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.html
* Last commit: https://github.com/mdn/content/commit/be3c3e06d1d9b59d2ad38a3a3e9eb59fbaa9c6f1
* Document last modified: 2021-06-10T18:50:18.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6412 with a fix.
