### ISSUE TITLE
Issue with "Responsive images": (typo?)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6400]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

#### What information was incorrect, unhelpful, or incomplete?
**Note**: The new features discussed in this article — srcset/sizes/<picture> — are all supported in **release** versions of modern desktop and mobile browsers (including Microsoft's Edge browser, although not Internet Explorer.) 

#### Specific section or headline?
Why responsive images?

#### What did you expect to see?
Is it supposed to say "**recent versions**" instead of "**release versions**"?

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/responsive_images/index.html
* Last commit: https://github.com/mdn/content/commit/be3c3e06d1d9b59d2ad38a3a3e9eb59fbaa9c6f1
* Document last modified: 2021-06-10T18:50:18.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6412 with a fix.
