### ISSUE TITLE
Content bug: Unicode-aware string-reverse working as expected in Firefox and Chrome

### ISSUE THREAD

**Issue by eyherabh** [mdn/content#6403]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split

## Specific page section or heading?

String.prototype.split() -> Examples -> Reversing a String using split()
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split#reversing_a_string_using_split

## What is the problem?

The page shows the following example
```
 const str = 'résumé'
const strReverse = str.split(/(?:)/u).reverse().join('')
// => "́emuśer"
```
However, the result I get in both Firefox 89 and Chrome 91.0.4472.114 is "émusér" as expected.
![image](https://user-images.githubusercontent.com/25811648/123556187-71d65100-d792-11eb-844e-96aa1be68827.png)

## What did you expect to see?

Perhaps a clarification on which browsers are affected by the problem the section mentions, or a correction if the unicode-aware reversing always works that it does solve the problem and that esrever is not necessary.

## Did you test this? If so, how?

I tested it by opening the developers console both in chrome and in firefox and copy&pasting the example.

**Comment by sideshowbarker** [comment]
Thanks very much for catching this — I’ve opened https://github.com/mdn/content/pull/6414 with a fix.
