### ISSUE TITLE
Issue with "Worker": sidebar links are duplicated

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/content#6408]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Worker

#### What information was incorrect, unhelpful, or incomplete?
All of the links in the sidebar are duplicated on this page and child pages.
![image](https://user-images.githubusercontent.com/40804543/123561685-90772080-d76f-11eb-98e8-7bbeb23a8828.png)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/worker`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Worker
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/worker/index.html
* Last commit: https://github.com/mdn/content/commit/64b0057f7238be9ad7a6f2f522efd8f5f7753095
* Document last modified: 2021-06-17T09:07:21.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/yari/pull/4097 with a fix.
