### ISSUE TITLE
Issue with "From object to iframe — other embedding technologi…": (deprecated attribute)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6411]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies

#### What information was incorrect, unhelpful, or incomplete?
![image](https://user-images.githubusercontent.com/51193876/123562766-a4b62000-d765-11eb-85e1-d53e60d8e670.png)

#### Specific section or headline?
Iframes in detail

#### What did you expect to see?
The attribute **frameborder** is deprecated, so it can't be _essential_.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/other_embedding_technologies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.html
* Last commit: https://github.com/mdn/content/commit/75c1271189903b4d96433a34a8174175dd089ef2
* Document last modified: 2021-04-28T14:08:28.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6416 with a fix.
