### ISSUE TITLE
Content bug: audioworkletnode-sample broken

### ISSUE THREAD

**Issue by Photosounder** [mdn/content#6426]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_AudioWorklet
https://audioworkletnode-sample.glitch.me/

## Specific page section or heading?

The live demo that shows how an audioworklet node is supposed to work.

## What is the problem?

It doesn't work, the console reports `** Error: Unable to create worklet node: InvalidStateError: Failed to construct 'AudioWorkletNode': AudioWorkletNode cannot be created: The node name 'hiss-generator.js' is not defined in AudioWorkletGlobalScope.`. That means I can't base my code off of this code because this code doesn't work.

## What did you expect to see?

I expected it to work.

## Did you test this? If so, how?

In Firefox and Chrome.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/issues/6426 with a fix.

**Comment by himanshugarg** [comment]
No more glitch here. We can close this I think.
