### ISSUE TITLE
Issue with "padding-inline-end": (short summary here please)

### ISSUE THREAD

**Issue by xingxingliang** [mdn/content#6435]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-end

#### What information was incorrect, unhelpful, or incomplete?
"The padding-inline-end property takes the same values as the padding-left property."

#### Specific section or headline?
"Values"

#### What did you expect to see?

"The padding-inline-end property takes the same values as the padding-right property."

#### Did you test this? If so, how?
no

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/padding-inline-end`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-end
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/padding-inline-end/index.html
* Last commit: https://github.com/mdn/content/commit/c2267059151f609904286ad6ceca6e91ccd01a5f
* Document last modified: 2021-06-17T03:05:19.000Z

</details>

**Comment by rachelandrew** [comment]
The spec currently defines this as the same as padding-top: https://drafts.csswg.org/css-logical/#padding-properties

I think this changed at some point as own formal syntax also has the mapped to padding-left. I think mapping it to padding-right is incorrect as it is only padding-right in a horizontal-tb writing mode.

That said, this has come up elsewhere. So perhaps we should actually detail what is allowed here as we do on the padding-x pages, leaving the formal syntax to detail what the spec says.

**Comment by sideshowbarker** [comment]
(I hadn’t actually meant to assign this myself; now unassigned)
