### ISSUE TITLE
Issue with "performance.measure()": Missing changes in the latest User Timing Level 3 working draft as implemented by Chrome and Safari

### ISSUE THREAD

**Issue by adam-h** [mdn/content#6441]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure

#### What information was incorrect, unhelpful, or incomplete?

Missing changes in the latest [User Timing Level 3](https://www.w3.org/TR/user-timing-3/#measure-method) working draft as implemented by Chrome and Safari.

In particularly the return of the `entry` instread of `undefined`.

While nothing is incorrect here, it could be more helpful by mentioning the differences. If you just glance at the article and try it out in a Chrome or Safari console, it's easy to implement something that doesn't work in all browsers.

#### Specific section or headline?

Generally the whole thing, in particular the 'Specifications' and 'Compatibility' sections

#### What did you expect to see?

A mention of the latest spec/implementations and how it differs accross browsers.

#### Did you test this? If so, how?

Checked the latest specification text. Also confirmed the new version is implemented in Chrome 92 and Safari 14.1.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/performance/measure`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/performance/measure/index.html
* Last commit: https://github.com/mdn/content/commit/e5c00d7f90e16029d1c96e7541aac3a9d1a09a31
* Document last modified: 2021-06-15T07:53:19.000Z

</details>

**Comment by himanshugarg** [comment]
The now closed issue #7544 fixes the following part but this bug apparently asks for more:-

> In particularly the return of the entry instread of undefined.

**Comment by Elchi3** [comment]
This particular issue looks fixed to me. Please file a new issue if you notice more things missing for the User Timing Level 3 update.

See also
- https://github.com/mdn/browser-compat-data/pull/18216
- https://github.com/mdn/browser-compat-data/pull/18228
- https://github.com/mdn/content/pull/22309
