### ISSUE TITLE
Issue with "@counter-style": No link to Ready-made Counter Styles

### ISSUE THREAD

**Issue by r12a** [mdn/content#6447]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style

#### What information was incorrect, unhelpful, or incomplete?
No mention of Ready-made Counter Styles doc at https://www.w3.org/TR/predefined-counter-styles/

That W3C document provides well over 100 ready-made code snippets for authors to include in their CSS style sheets, covering over 30 writing systems.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/@counter-style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@counter-style/index.html
* Last commit: https://github.com/mdn/content/commit/775066d2fc8d1561d5da61983d137c1297899315
* Document last modified: 2021-05-08T09:57:47.000Z

</details>

**Comment by rachelandrew** [comment]
@r12a thank you! This is really useful, I've added it in the linked PR.

**Comment by r12a** [comment]
Not sure whether it's of interest, but i just updated my Counter Styles Converter app at https://r12a.github.io/app-counters/

It's similar to the counter-style demo linked from the MDN page already, but it allows people to create and test their own styles, as well as populating the pulldown with additional pre-made styles from the Ready-made CS doc.

I mention it just in case you think it's worth a link, but no worries if not.
