### ISSUE TITLE
Issue with "Video textures": Video does not appear on Firefox for Android

### ISSUE THREAD

**Issue by kokotron** [mdn/content#6449]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example/Video_textures

#### What information was incorrect, unhelpful, or incomplete?
Video does not appear on Firefox for Android.

#### What did you expect to see?
Video should appear.

#### Did you test this? If so, how?
Tested on several Android devices with Firefox 89.1.1

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl_api/by_example/video_textures`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example/Video_textures
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/by_example/video_textures/index.html
* Last commit: https://github.com/mdn/content/commit/bbd9e232f08e5eae828c7ff969e66912b51a5060
* Document last modified: 2021-01-02T18:12:06.000Z

</details>

**Comment by sideshowbarker** [comment]
I can’t reproduce this in current Firefox on Android. In Firefox 102 on my Android device, the video appears as expected.

Given that, I’m going ahead and closing this.
