### ISSUE TITLE
Issue with "Array.prototype.filter()": Delete example not providing proper result

### ISSUE THREAD

**Issue by aryanisml** [mdn/content#6458]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

#### What information was incorrect, unhelpful, or incomplete?
Affecting Initial Array (modifying, appending and deleting)
The pop example is not working as expected

```js
// Deleting words
words = ['spray', 'limit', 'exuberant', 'destruction', 'elite', 'present']
const deleteWords = words.filter( (word, index, arr) => {
  arr.pop()
  return word.length < 6
})

console.log(deleteWords);
```

current output is ['spray', 'limit'];

if we change the element position then the output would be different 
e.g.

```js
words = ['spray', 'limit', 'elite', 'exuberant', 'destruction',  'present']
const deleteWords = words.filter( (word, index, arr) => {
  arr.pop()
  return word.length < 6
})

console.log(deleteWords);
```

current output is ['spray', 'limit', 'elite'];

Why this unusual behaviour as we are placing the elite in 3rd position instead of 5th position.

#### Specific section or headline?

Affecting Initial Array (modifying, appending and deleting)

#### What did you expect to see?

I am expecting if array.pop() operation is performed before filter return means it modify the array it will give the modify result.

#### Did you test this? If so, how?

```js
words = ['spray', 'limit', 'elite', 'exuberant', 'destruction',  'present']
const deleteWords = words.filter( (word, index, arr) => {
  arr.pop()
  return word.length < 6
})

console.log(deleteWords);
```

current output is ['spray', 'limit', 'elite'];

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/filter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/filter/index.html
* Last commit: https://github.com/mdn/content/commit/3c394e62835ef7b443fb5208343ecba892bbf6d5
* Document last modified: 2021-05-26T11:36:38.000Z

</details>

Edit: Added code fences and syntax highlighting to ease reading

**Comment by Ryuno-Ki** [comment]
@aryanisml I hope you're okay with me editing your post to add some colour :-)

Please be patient until someone has the chance to review this issue.

**Comment by NegiAkash890** [comment]
Hi @aryanisml , 

The reason the output differs because every time a pop operation is performed on an array , the array is modified . Since we are calling the filter method it checks for each element with a new value of `arr` argument
because we are popping the array.

```javascript

const deleteWords = words.filter( (word, index, arr) => {
 // arr value is changed everytime because of pop method
 })
```
Example :

```javascript
//Array intially
arr = ['spray', 'limit', 'exuberant', 'destruction', 'elite', 'present']

//Execution of Filter begin , the  Array is popped first and then we return
arr = ['spray', 'limit', 'exuberant', 'destruction', 'elite']   // ___ (1) 

//Similarly when filter executes again it executes on the above-modified value of arr (pointed by __(1)) 
//First we  pop and then we return with array being `__(1)`

arr =  ['spray', 'limit', 'exuberant', 'destruction']    // arr  at second execution

```

**Comment by aryanisml** [comment]
> @aryanisml I hope you're okay with me editing your post to add some colour :-)
> 
> Please be patient until someone has the chance to review this issue.

Yes sure thanks

**Comment by aryanisml** [comment]
> Hi @aryanisml ,
> 
> The reason the output differs because every time a pop operation is performed on an array , the array is modified . Since we are calling the filter method it checks for each element with a new value of `arr` argument
> because we are popping the array.
> 
> ```js
> const deleteWords = words.filter( (word, index, arr) => {
>  // arr value is changed everytime because of pop method
>  })
> ```
> 
> Example :
> 
> ```js
> //Array intially
> arr = ['spray', 'limit', 'exuberant', 'destruction', 'elite', 'present']
> 
> //Execution of Filter begin , the  Array is popped first and then we return
> arr = ['spray', 'limit', 'exuberant', 'destruction', 'elite']   // ___ (1) 
> 
> //Similarly when filter executes again it executes on the above-modified value of arr (pointed by __(1)) 
> //First we  pop and then we return with array being `__(1)`
> 
> arr =  ['spray', 'limit', 'exuberant', 'destruction']    // arr  at second execution
> ```

Thanks can you please try the example what I mentioned in issue.

**Comment by aryanisml** [comment]
> Hi @aryanisml ,
> 
> The reason the output differs because every time a pop operation is performed on an array , the array is modified . Since we are calling the filter method it checks for each element with a new value of `arr` argument
> because we are popping the array.
> 
> ```js
> const deleteWords = words.filter( (word, index, arr) => {
>  // arr value is changed everytime because of pop method
>  })
> ```
> 
> Example :
> 
> ```js
> //Array intially
> arr = ['spray', 'limit', 'exuberant', 'destruction', 'elite', 'present']
> 
> //Execution of Filter begin , the  Array is popped first and then we return
> arr = ['spray', 'limit', 'exuberant', 'destruction', 'elite']   // ___ (1) 
> 
> //Similarly when filter executes again it executes on the above-modified value of arr (pointed by __(1)) 
> //First we  pop and then we return with array being `__(1)`
> 
> arr =  ['spray', 'limit', 'exuberant', 'destruction']    // arr  at second execution
> ```

const words = ['spray', 'limit', 'elite', 'exuberant', 'destruction',  'present']
const deleteWords = words.filter( (word, index, arr) => {
  arr.pop()
  return word.length < 6
})

console.log(deleteWords);

check this one

**Comment by NegiAkash890** [comment]
```js
 const words = [ 'spray', 'limit', 'elite',' exuberant', 'destruction', 'present' ] //Array Intially 
 // deleteWords = [ ]  //Intially empty

//First Iteration 

// Array is popped and Array becomes = [ 'spray', 'limit', 'elite', 'exuberant', 'destruction' ]
// Since arr[0] 's length is less that 6. The deleteWords = [ 'spray' ]

//Second Iteration 

//Array is  [ 'spray', 'limit', 'elite', 'exuberant', 'destruction' ] 
//Again array is popped it becomes [ 'spray', 'limit', 'elite', 'exuberant' ]
//Now arr[1] 's length is less than 5 so now the deleteWords = [ 'spray', 'limit' ]

// Third Iteration 

/* Array is now  [ 'spray', 'limit', 'elite', 'exuberant' ]
   Array is popped again  [ 'spray', 'limit', 'elite' ]
   Now arr[2]'s length is again < 6 . So now deleteWords =  [ 'spray', 'limit', 'elite']
*/

//At this point the filter method has already executed for all the elements in the array so execution stops


```

**Comment by sideshowbarker** [comment]
Per https://github.com/mdn/content/issues/6458#issuecomment-873124554 and https://github.com/mdn/content/issues/6458#issuecomment-873124554 from @NegiAkash890 it seems the existing MDN content here is correct — so I’m going ahead and closing this issue.
