### ISSUE TITLE
Problem with the window to code

### ISSUE THREAD

**Issue by JulianPaez92** [mdn/content#646]
I leave an image of the problem, which does not allow writing code to practice the "&lt;iframe&gt;" exercise (I think the server is not taking the frame, or it is simply empty in the section "&lt;body&gt;"):

![image](https://user-images.githubusercontent.com/70548446/103143152-f109a000-46ef-11eb-887b-ad482f8ee2bf.png)

The link of the tab that generates inconvenience:
https://developer.mozilla.org/es/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies#Aprendizaje_activo_usos_de_incrustaci%C3%B3n_cl%C3%A1sicos 
-MDN Desde object hasta iframe - otras tecnologías de incrustación</a>

The trouble starts when i try to change the language, using the translator of the same page or from google translator, both generates that.

I wait for an answer, greetings!
PS: I love their courses, I am learning a lot, they are geniuses, greetings from Argentina

**Comment by mattiapontonio** [comment]
![Screenshot_20201227-160210.png](https://user-images.githubusercontent.com/44380480/103173705-fdf7d200-485c-11eb-9b36-9db1964c5d3d.png)

This Is a screenshot from the English version

**Comment by mattiapontonio** [comment]
The `iframe`'s `SRC` works? I don't know where Is It in GitHub.

**Comment by JulianPaez92** [comment]
[image: image.png]
Hi ! Still don't work, there is a problem in the translation that makes
this disappear. Try to "change language" into spanish and see the results.
I don't know where is the place in Github :(

**Comment by JulianPaez92** [comment]
![image](https://user-images.githubusercontent.com/70548446/103174038-9bdba480-483d-11eb-9293-ebb261b05e07.png)

**Comment by mattiapontonio** [comment]
Yes, the `iframe` is located in a `es/` path so maybe It Is not translateted.
I'm expecting the english one is in a `en/` path.
How to translate an iframe src?
Actually i don't know.

![Screenshot_20201227-162600.png](https://user-images.githubusercontent.com/44380480/103174194-61cfca00-4860-11eb-8d6e-a86d213c00cc.png)

**Comment by mattiapontonio** [comment]
I know that interactive examples are in this repository

https://github.com/mdn/interactive-examples

**Comment by JulianPaez92** [comment]
Oh i see. Well, maybe someone has to translate this, tx for the help Mattia ! Hug brother !

**Comment by mattiapontonio** [comment]
The issue can stay open...

**Comment by JulianPaez92** [comment]
Okay, i reopen it.

**Comment by sideshowbarker** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
