### ISSUE TITLE
http.headers.Forwarded - The example looks incorrect

### ISSUE THREAD

**Issue by prezaei** [mdn/content#6470]
#### What information was incorrect, unhelpful, or incomplete?
In the example below, it shows the UPV6 for X-Forwarded-For header within brackets. I believe that is incorrect for X-Forwarded-For but correct for the Forwarded header:

X-Forwarded-For: 192.0.2.43, "[2001:db8:cafe::17]"
Forwarded: for=192.0.2.43, for="[2001:db8:cafe::17]"

#### What did you expect to see?
X-Forwarded-For: 192.0.2.43, 2001:db8:cafe::17
Forwarded: for=192.0.2.43, for="[2001:db8:cafe::17]"

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Forwarded`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded
* Report started: 2021-06-29T20:52:07.834Z

</details>

**Comment by mnot** [comment]
`X-Forwarded-For` isn't specified anywhere, and there are differences between implementations. I'm not sure what's most common here, but since there isn't a formal spec, I don't know how "right" we can get this.

**Comment by sideshowbarker** [comment]
Thanks @mnot. Closing per https://github.com/mdn/content/issues/6470#issuecomment-881147247

@prezaei If you find a source somewhere which we could cite and which suggests the bracket-less form of the value is the best practice — or in wider use — then we could revisit this.

**Comment by prezaei** [comment]
> @prezaei If you find a source somewhere which we could cite and which suggests the bracket-less form of the value is the best practice — or in wider use — then we could revisit this.

Here we go: [RFC7239](https://datatracker.ietf.org/doc/html/rfc7239#section-7.4)

**Comment by sideshowbarker** [comment]
> > @prezaei If you find a source somewhere which we could cite and which suggests the bracket-less form of the value is the best practice — or in wider use — then we could revisit this.
> 
> Here we go: [RFC7239](https://datatracker.ietf.org/doc/html/rfc7239#section-7.4)

@mnot Any comment? On that face of it, the fact we have an RFC showing an X-Forwarded-For example without brackets would seem to suggest we should follow that example in MDN.

**Comment by mnot** [comment]
7239 doesn't define XFF; it's just an example there. Not that making this change *hurts* anything -- it's just there isn't any authoritative definition of XFF, and fair amount of variance in the field.
