### ISSUE TITLE
Issue with "POST": (short summary here please)

### ISSUE THREAD

**Issue by kariukiandy** [mdn/content#6475]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/methods/post`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/methods/post/index.html
* Last commit: https://github.com/mdn/content/commit/e7658344ddc971b8caa406b396fa8c15fcd71855
* Document last modified: 2021-05-31T17:21:16.000Z

</details>

**Comment by kariukiandy** [comment]
{"correlation_id":"124.6195372936469","transaction_status":"approved","validation_status":"success","transaction_type":"purchase","transaction_id":"ET182228","transaction_tag":"4629487231","method":"credit_card","amount":"11","currency":"USD","cvv2":"P","token":{"token_type":"FDToken","token_data":{"value":"1814884572053939"}},"card":{"type":"visa","cardholder_name":"000200614860495","card_number":"3939","exp_date":"1224"},"bank_resp_code":"100","bank_message":"Approved","gateway_resp_code":"00","gateway_message":"Transaction Normal","retrieval_ref_no":"210427"}

**Comment by Ryuno-Ki** [comment]
This look like an API response. I hid it (but you should reset your API token if possible, otherwise the account might be hijacked by some malicious actor).
