### ISSUE TITLE
Issue with "HTML table advanced features and accessibility": (inappropriate template)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6482]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced

#### What information was incorrect, unhelpful, or incomplete?
The learner is asked to use [this template](https://github.com/mdn/learning-area/blob/master/html/tables/basic/timetable-fixed.html), but this template is terribly complex and when opened in a web browser takes us to a site on Github Pages. I don't think this is what's intended.

#### Specific section or headline?
Active learning: Adding a caption

#### What did you expect to see?
A beginner-friendly template that shows a table when opened in a web browser.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/tables/advanced`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/tables/advanced/index.html
* Last commit: https://github.com/mdn/content/commit/98e906a10e9d266572e3645b70ecd8a1f28ab760
* Document last modified: 2021-06-22T06:53:26.000Z

</details>

**Comment by rachelandrew** [comment]
It doesn't seem especially complex the code is a simple table, we could move it off Github and just present the file but then it would open in the browser rather than be code, which potentially is more confusing.

**Comment by ConsciousClay** [comment]
But we're already directed to open it in a browser. And when we do, we are
sent to Github rather than presented with the table. I've gone through the
whole tutorial from the very beginning and I never saw anything like this.
Are you sure it's correct?

**Comment by ConsciousClay** [comment]
I don't think you understand the context. We are told to add a caption and open the document in a browser. That just doesn't work. I can't find the resource now, but when I first started these tutorials, there was a link to a GitHub page where we could download all the learning materials at once. I did that, and when I do the tutorials, I use those materials. Those materials _are not_ the same as the template in question. The template in question can't be the right one. The one I used, the one from the collection presented at the beginning, does in fact show a table when opened in a browser.

**Comment by rachelandrew** [comment]
Are you talking about this note:

"Note: You can find our version on GitHub — see timetable-caption.html (see it live also)."

The tables referred to in this are the code on GitHub, which is exactly the same link as the finished version from the previous lesson, and a live version (on GitHub Pages). I'm struggling to understand the issue with them.

So the context is that the previous lesson ended with an example (which is the timetable_fixed example you linked to).

You are then asked to go back to that table to add the caption. Or am I looking in completely the wrong place?

**Comment by ConsciousClay** [comment]
I found the collection of learning materials, [here](https://developer.mozilla.org/en-US/docs/Learn), under the section "Getting our code examples". In that collection, there is a file called "timetable-fixed" in the path /learning-area-master/html/tables/basic/. This file is accessible to a beginner and when a caption is added (as is our task) and opened in a web browser, we can see a table. Now this file is radically different than the one [here](https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced), under the section "Active learning: Adding a caption". Here, the file called "timetable-fixed" is not all the accessible to a beginner. These two files (with the same names) are radically different from one another. The correct file is 3 pages long (in word) and has 129 words. The wrong file is 79 pages long and has nearly 10,000 words. You can't honestly think that a beginner trying to just make a caption for a table should be working on a document with 10,000 words.

**Comment by ConsciousClay** [comment]
Here are the two files. The one labeled "active learning" is the one MDN is asking us to work with in the tutorial. It's the wrong one. The one labeled "from code example" is from the collection MDN suggests we use at the very beginning of the tutorials [here](https://developer.mozilla.org/en-US/docs/Learn).

[timetables.zip](https://github.com/mdn/content/files/6749663/timetables.zip)

**Comment by ConsciousClay** [comment]
![timetable](https://user-images.githubusercontent.com/51193876/124160900-9875df80-da51-11eb-97ee-8ac20319de21.jpg)

This file has 10,000 words in it. It's not the right one.

**Comment by rachelandrew** [comment]
You have downloaded the entire GitHub page there, it's just the code part that is needed for the example and it is the same file, in the same format, as the previous tutorial finishes with. If you copied the code out of the code part in GitHub, you'll see it's the same 98 lines as in the bare HTML file.

At the bottom of https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Basics

You will find the following sentence:

> "you can find our version on GitHub as timetable-fixed.html" 

This links to the file on GitHub https://github.com/mdn/learning-area/blob/master/html/tables/basic/timetable-fixed.html which is the same as the one you are referencing, which is then used again in the next tutorial.

**Comment by ConsciousClay** [comment]
I haven't got a clue what's going on. Last week that link provided me with
a huge file. Now it provides me with the simple file you're referring to. I
downloaded it several times last week when filing this issue. So no idea
what happened and no idea how I got that huge file. Well, situation seems
resolved now I guess.

**Comment by ConsciousClay** [comment]
Okay, I figured out the problem. It's my fault. I downloaded the link via
right-click "save link as" which downloads the entire GitHub page. I didn't
know we were supposed to follow the link to GitHub and *then *download the
file. That's where the confusion lies.

**Comment by rachelandrew** [comment]
I'm going to close this one then as the referenced table is the correct one.
