### ISSUE TITLE
Issue with "Preflight request": (short summary here please)

### ISSUE THREAD

**Issue by rbrtmrtn** [mdn/content#6496]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

#### What information was incorrect, unhelpful, or incomplete?

Minor typographic error

#### Specific section or headline?

Main text body

#### What did you expect to see?

In the final sentence:

> The preflight response can be optionally cached for the requests created in the same url using Access-Control-Max-Age header like in the above example.

"URL" should be capitalized.

#### Did you test this? If so, how?

n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/preflight_request`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/preflight_request/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by teoli2003** [comment]
Thanks. You are right; I opened a PR to fix it (and to make it a link to the relevant glossary page).
