### ISSUE TITLE
Issue with "Array.prototype.reduce()": Confusing presentation of core concept

### ISSUE THREAD

**Issue by GuywhoembalmedLenin** [mdn/content#6497]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

#### What information was incorrect, unhelpful, or incomplete?
The fact that this doc (as pretty much any other info sources ou there, I am aware) calls the first argument of the reduce() method "accumulator" appeared to me as a strong suggestion that the returned value of the callback function applied to it was ADDED to the accumulator, as opposed to assigned to it. The fact that the very first demo of the method right on top of the page is that of the currentValue being added on to the acummulator, further compounds in my opinion the possibility for this specific confusion. I willingly admit that I also didn't help matters by not taking my time to read it carefully, but it just seems like that's a bad habit many people may unfortunately fall into when acessing this documentation.

#### Specific section or headline?
Mentioned above.

#### What did you expect to see?
Perhaps a different or aditional example in the demo on the top of the page to that which is already there. And also maybe, a strong highlighting of the word "assigned" in the sentence "Your reducer function's returned value is **_assigned_** to the accumulator, whose value is remembered across each iteration throughout the array, and ultimately becomes the final, single resulting value."

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/reduce`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/reduce/index.html
* Last commit: https://github.com/mdn/content/commit/761ba0efe8230cec103437c215a79a2e6d2bb5f2
* Document last modified: 2021-06-15T08:30:35.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. I think part of the fix here is to now use the word *accumulator* at all but instead call it *currentValue* — which at https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.reduce is what the ES spec does.

In fact overall, the language in the spec at https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.reduce seems more clear than what we currently have in MDN. The current language in MDN has lead to other issues being reported here, such as https://github.com/mdn/content/issues/6156.

So I believe what should be done here is for the description in MDN to be rewritten to be more like what the ES spec says.

I’ve been planning to make that change myself, but I wouldn’t be unhappy if somebody beat me to it and raised a PR themselves with that change…

**Comment by NegiAkash890** [comment]
Instead of : 
`
Note: If initialValue is not provided, reduce() will execute the callback function starting at index 1, skipping the first index. If initialValue is provided, it will start at index 0.
`

We can state : 
`
Note: If initialValue is not provided, reduce() will execute the callback function starting at index 1, using array's first element as accumulator value . If initialValue is provided, it will start at index 0.
`

For the example, at the top, I suggest that adding comments will work .

**Comment by sideshowbarker** [comment]
@NegiAkash890 That’s definitely an improvement. To take it further,  I think we should drop the word *accumulator* and use the word *currentValue* instead.

And more broadly, I’m thinking a change for this should be formed around just quoting the language in the ES spec — something like this:

> The ECMASCript spec describes the behavior of `reduce()` as follows:
>
> > <var>callbackfn</var> should be a function that takes four arguments. <code>reduce</code> calls the callback, as a function, once for each element after the first element present in the array, in ascending order.
> > <var>callbackfn</var> is called with four arguments: the <var>previousValue</var> (value from the previous call to <var>callbackfn</var>), the <var>currentValue</var> (value of the current element), the <var>currentIndex</var>, and the object being traversed. The first time that callback is called, the <var>previousValue</var> and <var>currentValue</var> can be one of two values. If an <var>initialValue</var> was supplied in the call to <code>reduce</code>, then <var>previousValue</var> will be equal to <var>initialValue</var> and <var>currentValue</var> will be equal to the first value in the array. If no <var>initialValue</var> was supplied, then <var>previousValue</var> will be equal to the first value in the array and <var>currentValue</var> will be equal to the second. It is a <emu-val>TypeError</emu-val> if the array contains no elements and <var>initialValue</var> is not provided.
> > <code>reduce</code> does not directly mutate the object on which it is called but the object may be mutated by the calls to <var>callbackfn</var>.
> > The range of elements processed by <code>reduce</code> is set before the first call to <var>callbackfn</var>. Elements that are appended to the array after the call to <code>reduce</code> begins will not be visited by <var>callbackfn</var>. If existing elements of the array are changed, their value as passed to <var>callbackfn</var> will be the value at the time <code>reduce</code> visits them; elements that are deleted after the call to <code>reduce</code> begins and before being visited are not visited.
>
> [followed by more words and example code]

**Comment by sideshowbarker** [comment]
I’ve opened #7484 with a fix for this.
