### ISSUE TITLE
Trying to center align my text

### ISSUE THREAD

**Issue by Ines95Borges** [mdn/content#6499]
Here is my repository: [link to my repository](https://github.com/Ines95Borges/Portfolio-v4)
Here is the site live: [live website](https://blissful-dijkstra-0b8372.netlify.app/)
The code is on homeCanvas,js that is inside js folder.
It is line 47 and 48. The text "Inês Borges" doesn't stay centered in the middle of the screen and doesn't appear.
And also how can I optimize the performance on line 48 making the getImageData function look at less pixels?

**Comment by teoli2003** [comment]
Hi @Ines95Borges!

Thank you for your question! mdn/content is a repository about documentation about web technologies, it isn't q Q&A website.

You should consider asking your question on a specialized site like https://stackoverflow.com

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/6499#issuecomment-872831651
