### ISSUE TITLE
Issue with "Getting started with HTML": (short summary here please)

### ISSUE THREAD

**Issue by chipssy** [mdn/content#6501]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started

#### What information was incorrect, unhelpful, or incomplete?
The link in "character encoding is set to UTF-8" is wrong. 

#### Specific section or headline?
Entity references: Including special characters in HTML

#### What did you expect to see?
It's now "https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#specifying_your_document's_character_encoding", and it should be "https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#specifying_your_documents_character_encoding", without an apostrophe in "documents". It also works if you change the content of the linked page, but that will be a issue of the linked page.

#### Did you test this? If so, how?
With the modified link, it will go to the right place.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/getting_started/index.html
* Last commit: https://github.com/mdn/content/commit/36c2b75fb7ad07be7663fff798264c68761d0094
* Document last modified: 2021-06-20T00:12:20.000Z

</details>

**Comment by teoli2003** [comment]
Thanks! You are right. I opened a pull request to fix the link.
