### ISSUE TITLE
Content suggestion: Document CSS Property syntax strings

### ISSUE THREAD

**Issue by justinfagnani** [mdn/content#6506]
## What is the new suggestion?

The CSS Values and Properties API pages reference the `syntax` property of `@property` and `registerProperty`, but don't describe the syntax of the `syntax` property itself. That can be found in the [spec](https://drafts.css-houdini.org/css-properties-values-api/#syntax-string) but the MDN docs could use a more readable description of the syntax.

## Why is it important or useful?

There is currently only the most basic example of property syntax, like `"<color>"` and no hint that properties can be multi-valued.

This may deserve a new page, or could go on one of the CSS Values and Properties API pages. Describing syntax in readable form is hard, but hopefully something useful if not complete could be done in hours not weeks.

## Other supporting information

https://drafts.css-houdini.org/css-properties-values-api/#syntax-string
https://developer.mozilla.org/en-US/docs/Web/CSS/@property
https://developer.mozilla.org/en-US/docs/Web/API/CSS/RegisterProperty

**Comment by rachelandrew** [comment]
We actually have these (I was reading this and thinking I was sure I'd written them!)

For example: https://developer.mozilla.org/en-US/docs/Web/CSS/@property/syntax

They haven't been linked in though. Which I will do!

**Comment by justinfagnani** [comment]
Oh awesome, thank you!
