### ISSUE TITLE
Issue with "Basic concepts of flexbox": (short summary here please)

### ISSUE THREAD

**Issue by vicky-ops** [mdn/content#6507]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox

#### What information was incorrect, unhelpful, or incomplete?
>>>"Should you choose row or row-reverse, your main axis will run along the row in the inline direction."
Above mentioned line is not semantically correct.
#### Specific section or headline?
>>>"The main axis" This is the Section

#### What did you expect to see?
Change should be like
>>> choose row or row-reverse, your main axis will run along the row in the inline direction.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_flexible_box_layout/basic_concepts_of_flexbox`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.html
* Last commit: https://github.com/mdn/content/commit/4df8fc624cb319731c0e0ad052348b2b0f62e59e
* Document last modified: 2021-06-11T11:56:01.000Z

</details>

**Comment by sideshowbarker** [comment]
> > "Should you choose row or row-reverse, your main axis will run along the row in the inline direction."
>
>  Above mentioned line is not semantically correct.
> 
> Change should be like
> 
> > choose row or row-reverse, your main axis will run along the row in the inline direction.

That is exactly the same text as what’s cited above from the existing MDN article.

Did you mis-type?

**Comment by rachelandrew** [comment]
I don't see an issue with the phrase, and the OP hasn't replied to explain, so I'm going to close this. Feel free to reopen with more info though.
