### ISSUE TITLE
Issue with "General guidelines for all code - Use of color"

### ISSUE THREAD

**Issue by jchimene** [mdn/content#651]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#Use_of_color

#### What information was incorrect, unhelpful, or incomplete?
404
[MDN Fiori Guidelines](https://mdn.github.io/mdn-fiori/)

#### Specific section or headline?

Last line of the `Use of color` section. Begins with the URL causing the 404
https://mdn.github.io/mdn-fiori/

#### What did you expect to see?

Some info on MDN's Fiori guidelines 

#### Did you test this? If so, how?

Clicked the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/guidelines/code_guidelines/general`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/guidelines/code_guidelines/general/index.html
* Report started: 2020-12-25T20:17:27.983Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this and reporting it. I’ve raised https://github.com/mdn/content/pull/652 with a fix.
