### ISSUE TITLE
Issue with "mix-blend-mode": (short summary here please)

### ISSUE THREAD

**Issue by austin-e-cox** [mdn/content#6515]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode

In the Examples section,
section: "Effect of different mix-blend-mode values"
The image does not load with the message:
yari-demos.prod.mdn.mozit.cloud’s server IP address could not be found.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/mix-blend-mode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/mix-blend-mode/index.html
* Last commit: https://github.com/mdn/content/commit/4d4db6dba6f19271bf1917600d27385627be4d74
* Document last modified: 2021-06-23T14:55:44.000Z

</details>

**Comment by teoli2003** [comment]
It looks like it is working for me.

<img width="1104" alt="Screenshot 2021-07-02 at 13 21 28" src="https://user-images.githubusercontent.com/1466293/124267346-6be8c300-db38-11eb-9a45-bad3fa50e4bc.png">

Can you double check if it is still in error right now?

And `nslookup yari-demos.prod.mdn.mozit.cloud` returns: 
<img width="694" alt="Screenshot 2021-07-02 at 13 23 07" src="https://user-images.githubusercontent.com/1466293/124267528-a9e5e700-db38-11eb-9bc0-59514d143d17.png">

**Comment by teoli2003** [comment]
I assume it was a transient error; I'm closing this issue.

@austin-e-cox, if I am wrong, feel free to reopen it and provide more info.
