### ISSUE TITLE
Issue with "Promise": (using the terms "resolved" and "fulfilled")

### ISSUE THREAD

**Issue by andrasna** [mdn/content#6521]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#static_methods

## What is the problem?

https://github.com/mdn/content/blob/9d6db51442834ca103d66a9435a4c86bb8576376/files/en-us/web/javascript/reference/global_objects/promise/index.html#L204

> Returns a Promise that resolves after all of the given promises have either **resolved or rejected**...

## What did you expect to see?

> Returns a Promise that resolves after all of the given promises have either **fulfilled or rejected**...

Like how it is documented here:

https://github.com/mdn/content/blob/9d6db51442834ca103d66a9435a4c86bb8576376/files/en-us/web/javascript/reference/global_objects/promise/allsettled/index.html#L17

> ...returns a promise that resolves after all of the given promises have either **fulfilled or rejected**...

If this is indeed an issue, I think it might be a good idea to see if these terms need to be swapped in other places.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6571 with fixes (including fixes for all other places in the docs where I could find this pattern).

**Comment by andrasna** [comment]
@sideshowbarker Thank you.

I believe not all instances of "resolved or rejected" will be incorrect - I have left a comment in the pull request where I thought "resolved or rejected" was used correctly.

I think it might be good to review the use of "resolved" and "fulfilled" in the context of promises in general.

As an example:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

> The Promise.all() method takes an iterable of promises as an input, and returns a single Promise that resolves to an array of the results of the input promises. This returned promise will resolve when all of the input's promises have resolved, or if the input iterable contains no promises. 

While this may not be incorrect technically, I believe it is ambiguous and the essence isn't captured, namely the question **when the  result** of the promise returned by Promise.all **is an array**. It could be that the returned promise's result is not an array even though all promises in the iterable have resolved.

However, the returned promise is *fulfilled* with an array, if and only if each and every promise in the iterable passed to the method is *fulfilled*.

With examples:

```js
const lockedInPromise = Promise.resolve(new Promise(() => {}))
const fulfilledPromise1 = Promise.resolve('fulfilled 1')
const fulfilledPromise2 = Promise.resolve('fulfilled 2')

const promise1 = Promise.all([lockedInPromise, fulfilledPromise1, fulfilledPromise2])
const promise2 = Promise.all([fulfilledPromise1, fulfilledPromise2])

// Case 1
console.log('Case 1: ', promise1) // Pending, no array as a result, even though all inputs have resolved.

// Case 2
console.log('Case 2: ', promise2) // Fulfills with an array, because all inputs have fulfilled.
```

It is possible I am missing something, so thanks for looking into this.
