### ISSUE TITLE
Issue with "RTCPeerConnection.generateCertificate() static fun…": (2 minor issues with the example provided)

### ISSUE THREAD

**Issue by nwnisworking** [mdn/content#6527]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/generateCertificate

#### What information was incorrect, unhelpful, or incomplete?
In description, the example provided by RSASSA-PKCS1-v1_5 have 2 issues. 
One of which is Uint8Array is written as UInt8Array. 
The other was the naming of RSASSA-PKCS1-v1_5 which have an additional 0 making it RSASSA-PKCS1**0**-v1_5

#### Specific section or headline?
Description > Standard configurations > RSASSA-PKCS1-v1_5

#### What did you expect to see?
let stdRSACertificate = {
  name: "RSASSA-PKCS1-v1_5",
  modulusLength: 2048,
  publicExponent: new Uint8Array([1, 0, 1]),
  hash: "SHA-256"
};

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/rtcpeerconnection/generatecertificate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/generateCertificate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/rtcpeerconnection/generatecertificate/index.html
* Last commit: https://github.com/mdn/content/commit/0f3c54f5a6cbbafbba3b8c7e2e045b67b26e9984
* Document last modified: 2021-06-19T03:49:37.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching those typos — I’ve opened https://github.com/mdn/content/pull/6570 with fixes.
