### ISSUE TITLE
Issue with "What is CSS?": (short summary here please)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6531]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS

#### What information was incorrect, unhelpful, or incomplete?
CSS is constantly developing, with new features **coming** available.

#### Specific section or headline?
CSS Specifications

#### What did you expect to see?
CSS is constantly developing, with new features **becoming** available.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/first_steps/what_is_css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/first_steps/what_is_css/index.html
* Last commit: https://github.com/mdn/content/commit/eafecac4b16da90274167b23b000eec7f940e1b7
* Document last modified: 2021-03-29T03:57:40.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Got fixed by @NegiAkash890
