### ISSUE TITLE
Issue with "Getting started with CSS": (obscure meaning)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6535]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started

#### What information was incorrect, unhelpful, or incomplete?

> If you were to do this then you would no longer be able to apply the class to a <span> or another element by adding the class to it; you would have to add that element to the list of selectors:

`li.special,
span.special {
  color: orange;
  font-weight: bold;
}`

> As you can imagine, some classes might be applied to many elements and you don't want to have to keep editing your CSS every time something new needs to take on that style. Therefore it is sometimes best to bypass the element and refer to the class, unless you know that you want to create some special rules for one element alone, and perhaps want to make sure they are not applied to other things.

#### Specific section or headline?
Adding a class

#### What did you expect to see?
The first paragraph states we wouldn't be able to apply a class by adding a class. But the code immediately following has a class added to the **\<span\>** element. This is confusing. Also, we're not told why we would want to write our syntax like this until the very end, when we're told we might want special rules for one element. When I read this, I don't have any idea what the point is until the end. And even then I'm still somewhat in the dark as to the intent of this section. The second paragraph suggests that we wouldn't want to keep editing our CSS every time. But why would we have to anyhow? Lastly, we're told sometimes it's best to bypass the element. But why would we consider otherwise? This is the first lesson on CSS. We don't have any concepts regarding CSS beyond what's in the first sections of this first lesson.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/first_steps/getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/first_steps/getting_started/index.html
* Last commit: https://github.com/mdn/content/commit/75c1271189903b4d96433a34a8174175dd089ef2
* Document last modified: 2021-04-28T14:08:28.000Z

</details>

**Comment by ConsciousClay** [comment]
Update: After re-reading this several times, I think the idea is that writing our **selectors** with both an **element** and **class** _binds_ those two features together. That is, the **selector** `p.special` _binds_ the **class** "special" to the **element** "p". Once a class is _bound_ in such a way, that class can no longer be used freely with any other element unless those other elements are also _bound_ to the class. Is that right?

**Comment by rachelandrew** [comment]
I've read through this and don't see an issue with it, classes are introduced unattached to an element. We then go on to explain that sometimes you will see an element with a class attached. The text explains that by doing this you would need to have each element you wanted to apply it to in the list, unlike the previous example where you just target the class no matter which element it's applied to.

I think I would be arbitrarily rewording this, at this point. If you have a suggestion for clearer wording please make it, however, my opinion is that this is correct and describes the situation at the right level for where a reader is now (prior to learning about specificity and so on).

**Comment by ConsciousClay** [comment]
As a beginner who started from MDN's tutorials on HTML, I'm still not sure
what the purport of this passage is intended to be. How about my comment on
*binding*? Was that accurate? If not, then I clearly don't understand the
passage. And it wouldn't be for lack of trying. I suppose one way to
approach this passage is to ask what its purpose is. For example, why would
the user want to target *jointly *an element with a class? Why not solely
target a class with our CSS and then in our HTML apply that class to
whatever it is we want the CSS to decorate? To be sure, we are told at the
end of the section that,

Therefore it is sometimes best to bypass the element and refer to the
> class, unless you know that you want to create some special rules for one
> element alone, and perhaps want to make sure they are not applied to other
> things.


But still, what does this mean to us? Why would we want to create a special
rule for one element alone? What's the motivation for doing this instead of
just targeting a class and applying that class to our HTML? Informing us of
the rules without explaining what the use of those rules is is a case of
failing to see the forest for the trees.

Second, the sentence, "*If you were to do this then you would no longer be
able to apply the class to a <span> or another element by adding the class
to it*" is just confusing. Isn't the code *span.special {...} *an instance
of adding the class *special *to the element *span*?

I wouldn't be able to rewrite the first passage for you since I don't
understand what its meaning is in a wider context. Again, why would we want
to create a special rule? What would its purpose be? What would it look
like? What would the context be?

As for the second issue, perhaps the confusion lay in the verb *add*. Maybe
when we write code such as *span.special {...}*, the class special IS NOT
being ADDED to the element span. But in that case, the term add is being
used with a specific meaning which beginner's are not familiar with.
Because when I see code snippets like an *element span* and a *class
special* and then I see those two being *put together*, I think a natural
verb for that is *add*.

1) span
+
2) special
=
span.special

**Comment by rachelandrew** [comment]
Adding a class to an element in that way is a thing that happens, it's valid, and readers may well have come across this usage, or will see it in examples. Therefore it is included here, and explained (briefly, given that this is introductory material and an overview).
