### ISSUE TITLE
Issue with "Getting started with CSS": (wrong punctuation)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6537]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started

#### What information was incorrect, unhelpful, or incomplete?
Leaving the underline in place **,** can be an important clue...

#### Specific section or headline?
Styling things based on state

#### What did you expect to see?
Leaving the underline in place [no comma] can be an important clue...

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/first_steps/getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/first_steps/getting_started/index.html
* Last commit: https://github.com/mdn/content/commit/75c1271189903b4d96433a34a8174175dd089ef2
* Document last modified: 2021-04-28T14:08:28.000Z

</details>

**Comment by teoli2003** [comment]
Thanks! You are right!

I've opened a PR to get this fixed.
