### ISSUE TITLE
Issue with "rotate()": rotation matrices do not match stated rotation direction

### ISSUE THREAD

**Issue by jpumford** [mdn/content#6538]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate()

#### What information was incorrect, unhelpful, or incomplete?
The `rotate()` CSS function will rotate clockwise given a positive angle of rotation, and counter-clockwise if given a negative angle of rotation. The rotation matrices given in the "Values" section (just above "Examples") are for rotations in the conventional direction: counter-clockwise when positive, clockwise when negative.

#### Specific section or headline?
"Syntax" > "Values", in the matrix definitions table

#### What did you expect to see?
I would expect to see a rotation matrix that rotates clockwise with positive arguments and counter-clockwise with negative arguments, matching the description of the expected behavior of `rotate()`. One such example matrix is available on [Wikipedia](https://en.wikipedia.org/wiki/Rotation_matrix#Direction)
*NOTE*: I am not familiar with the homogenous coordinate system, but I would expect the arguments to `sin` and `cos` to also be scalars and behave similarly (`cos(-a) = cos(a)` and `sin(-a) = -sin(a)`). In my PR I'll hold off on making that change until I read up on the homogenous coordinate system or someone chimes in.

#### Did you test this? If so, how?
Verified my thoughts on wikipedia

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/transform-function/rotate()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/transform-function/rotate()/index.html
* Last commit: https://github.com/mdn/content/commit/null
* Document last modified: 2020-11-19T16:05:02.344Z

</details>

**Comment by jpumford** [comment]
I guess one important thing I should have thought about earlier; the way the matrices are written out definitely seem like "standard" math (using ℝ symbols and all), but these could be of a non-standard coordinate system and I could be wrong

**Comment by sideshowbarker** [comment]
Closing this for lack of response on the associated PR at https://github.com/mdn/content/pull/6539

If further comments are added here with new information, this issue could be revisited.
