### ISSUE TITLE
Issue with "CanvasRenderingContext2D.transform()": LaTEX expression not rendering

### ISSUE THREAD

**Issue by Scydact** [mdn/content#6542]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/transform

#### What information was incorrect, unhelpful, or incomplete?
Formula just below Syntax section
> The transformation matrix is described by: \left[ \begin{array}{ccc} a & c & e \\ b & d & f \\ 0 & 0 & 1 \end{array} \right]

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/transform`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/transform
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/transform/index.html
* Last commit: https://github.com/mdn/content/commit/52cb33d18729b3664a8d146c0ad23648790dc5dc
* Document last modified: 2021-06-11T14:43:07.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this. This is actually a known problem which we don’t have a solution for yet but that we’re using https://github.com/mdn/content/issues/3435 to track. Please consider subscribing to that issue.
