### ISSUE TITLE
Issue with "Functions": (short summary here please)

### ISSUE THREAD

**Issue by anjali-shah** [mdn/content#6545]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions

#### What information was incorrect, unhelpful, or incomplete?
Concept about the hoisting is incomplete

#### Specific section or headline?
 Function expressions are not hoisted onto the beginning of the scope, therefore they cannot be used before they appear in the code.

#### What did you expect to see?
 Function expressions are also hoisted onto the beginning of the scope. 
I do expect these concepts.
Concept of Hoisting for functions , what happens when have same name variable and functions and others concepts like this. 

#### Did you test this? If so, how? 
On visual studio in javaScript file.

  console.log (xyz());   // allowed
  function xyz(){
      return "allowed";
  }

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/functions/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by dorward** [comment]
> Function expressions are also hoisted onto the beginning of the scope.

They aren't.

> 
> ```
> function xyz(){
> return "allowed";
> }
> ```

That's a function declaration

----

The page could do with more detail on what context makes something that uses the `function` keyword an expression or a declaration though.

**Comment by jamesaucode** [comment]
Will it be accurate to say a `function declaration` must start with the word `function`, while a `function expression` doesn't?
For example, 2 ways of defining `function expression`
```js
// starts with assigning to a variable
const fn = function() {
  console.log('foo')
}
```

```js
// starts with a '('
(function() {
  console.log('foo')
}())
```

while `function declaration` must start with the `function` keyword

```js
function foo() {
  console.log('foo')
}
```

If we accept this, I can create a PR

**Comment by dorward** [comment]
No. The function expression itself still starts with `function`, it is the statement it is in which doesn't start with `function`. The page *already* says that though:

>  As we can see, both examples do not start with the function keyword. Statements involving functions which do not start with function are function expressions.

**Comment by sideshowbarker** [comment]
I’m going ahead and closing this because, per https://github.com/mdn/content/issues/6545#issuecomment-917593135 and https://github.com/mdn/content/issues/6545#issuecomment-873566316 and as far as I can see, the existing docs are correct. See also https://github.com/mdn/content/pull/11683#issuecomment-1004327053
