### ISSUE TITLE
Issue with "Array.prototype.sort()": (short summary here please)

### ISSUE THREAD

**Issue by aliaksei-pavlenko** [mdn/content#6552]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

#### https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#sorting_with_map

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/sort`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/sort/index.html
* Last commit: https://github.com/mdn/content/commit/02f63b273eec5bb6a0b8856188bd9592786efa3d
* Document last modified: 2021-06-24T15:58:43.000Z

</details>

**Comment by teoli2003** [comment]
Thanks a lot! Good catch!

I created a PR to get this fixed
