### ISSUE TITLE
Issue with "Using IndexedDB": 404 for "Basic Concepts about IndexedDB"

### ISSUE THREAD

**Issue by richb-hanover** [mdn/content#656]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB

#### What information was incorrect, unhelpful, or incomplete?

In the second paragraph, there's a link to "Basic Concepts about IndexedDB" that links to https://developer.mozilla.org/en/IndexedDB/Basic_Concepts_Behind_IndexedDB

This is a 404, and a quick search for that page doesn't turn up a replacement

#### Specific section or headline?
 Second paragraph of this page

#### What did you expect to see?

Working link to desired article.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/indexeddb_api/using_indexeddb`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/indexeddb_api/using_indexeddb/index.html
* Report started: 2020-12-26T19:46:32.002Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching and reporting this. I’ve opened https://github.com/mdn/content/pull/671 with a fix.

**Comment by sideshowbarker** [comment]
Actually it seems this was fixed by https://github.com/mdn/content/pull/630. So I’ll go ahead and close this — with thanks for catching the problem and reporting it.
