### ISSUE TITLE
Issue with "performance.measure()": missing note about DOMException: "An invalid or illegal string was specified"

### ISSUE THREAD

**Issue by BenLubar** [mdn/content#6563]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure

#### What information was incorrect, unhelpful, or incomplete?

There is no list of exceptions this function can throw. 

#### Specific section or headline?

Exceptions

#### What did you expect to see?

Documentation of the exceptions this function can throw.

#### Did you test this? If so, how?

```
performance.measure("somename", "mark_that_does_not_exist");
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/performance/measure`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/performance/measure/index.html
* Last commit: https://github.com/mdn/content/commit/e5c00d7f90e16029d1c96e7541aac3a9d1a09a31
* Document last modified: 2021-06-15T07:53:19.000Z

</details>

**Comment by harshilparmar** [comment]
Can I take this issue ?

**Comment by sideshowbarker** [comment]
@harshilparmar — yup, thanks — assigned

**Comment by himanshugarg** [comment]
@harshilparmar, sorry I stole this from you. Hope you can find other interesting ones.
