### ISSUE TITLE
Issue with "Using IndexedDB": …

### ISSUE THREAD

**Issue by AntonOfTheWoods** [mdn/content#657]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB

#### What information was incorrect, unhelpful, or incomplete?
Broken link [Test the online live demo](https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB/_samples_/Full_IndexedDB_example)

#### Specific section or headline?
Under Javascript Content

#### What did you expect to see?
A link that takes one to the example

#### Did you test this? If so, how?
Clicking on the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/indexeddb_api/using_indexeddb`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/indexeddb_api/using_indexeddb/index.html
* Report started: 2020-12-26T23:15:04.620Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. The cause seems to be a bug in the Yari backend; I opened https://github.com/mdn/yari/pull/2283 with a fix.

**Comment by escattone** [comment]
This is resolved. Thanks @AntonOfTheWoods and @sideshowbarker!
