### ISSUE TITLE
Issue with "Opérateur de coalescence des nuls (Nullish coalesc…": (short summary here please)

### ISSUE THREAD

**Issue by FranckFreiburger** [mdn/content#6577]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

#### What information was incorrect, unhelpful, or incomplete?

Not sure that Nullish_coalescing_operator is supported on firefox 72

#### What did you expect to see?

![image](https://user-images.githubusercontent.com/25509586/124376587-00256800-dca8-11eb-8d84-0c09095e5b63.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/javascript/reference/operators/nullish_coalescing_operator`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/operators/nullish_coalescing_operator/index.html
* Last commit: https://github.com/mdn/translated-content/commit/678b2b2567c0519f78c02aa3ad243415baebf90e
* Document last modified: 2021-07-02T15:09:59.000Z

</details>

**Comment by FranckFreiburger** [comment]
sorry

**Comment by Ryuno-Ki** [comment]
No worries. no harm done.
