### ISSUE TITLE
Issue with "SpeechSynthesisUtterance.onend": wrong unit for elapsedTime

### ISSUE THREAD

**Issue by lparcq** [mdn/content#6581]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/onend

#### What information was incorrect, unhelpful, or incomplete?
In the example, the elapsed time (event.elapsedTime) is printed as if it was milliseconds. But it's in second per specification and implementation.

#### Specific section or headline?
Examples

#### What did you expect to see?
console.log('Utterance has finished being spoken after ' + event.elapsedTime + ' seconds.');

#### Did you test this? If so, how?
Specification: https://wicg.github.io/speech-api/#speechsynthesisevent-attributes

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/speechsynthesisutterance/onend`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/onend
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/speechsynthesisutterance/onend/index.html
* Last commit: https://github.com/mdn/content/commit/642d6eb7feb73e17cfc1ef61d3d09c2d200e65ca
* Document last modified: 2021-06-17T03:52:55.000Z

</details>

**Comment by teoli2003** [comment]
The same problem happens in: 
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/end_event
- https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisEvent

But https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisEvent/elapsedTime is in seconds.

**Comment by teoli2003** [comment]
I found even more occurrence while creating the PR… 

Thanks for the report!

**Comment by micolous** [comment]
While the spec states this is in seconds, it looks like only Safari returns a value in seconds. Both Chrome and Firefox currently erroneously return a value in milliseconds:

* https://bugs.chromium.org/p/chromium/issues/detail?id=1253036
* https://bugzilla.mozilla.org/show_bug.cgi?id=1732498
