### ISSUE TITLE
Issue with "Expressions and operators": What _are_ left-hand-side expressions?

### ISSUE THREAD

**Issue by alattalatta** [mdn/content#6586]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators

#### What information was incorrect, unhelpful, or incomplete?

> Left values are the destination of an assignment.

What does it mean? I'm having trouble understanding it. The heading is "Left-hand-side expression", the description starts with "Left values are..."

In addition to this,

```js
new klass() = 3 // this won't work
```

According to the spec and [this SO answer](https://stackoverflow.com/a/3710015), for a left-hand-side expression to be the destination of an assignment, it ["is expected to produce a Reference Record."](https://262.ecma-international.org/#sec-reference-record-specification-type)

So, some lhs expressions can be the destination of an assignment, but not all, am I right?

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators#left-hand-side_expressions
Also this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators#left-hand-side_expressions

#### What did you expect to see?

A more detailed description than "destination of an assignment", maybe?

#### Did you test this? If so, how?

No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/expressions_and_operators`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/expressions_and_operators/index.html
* Last commit: https://github.com/mdn/content/commit/ad09d9d6da37e79a858d1efded796b86f0ee28ad
* Document last modified: 2021-05-21T06:21:00.000Z

</details>

**Comment by hochan222** [comment]
I found the following questions:

https://stackoverflow.com/questions/22802838/javascript-why-doesnt-p1-work

```js
p = 0;
(p+1)++;
> ReferenceError: Invalid left-hand side expression in postfix operation
```

`p+1` becomes a value, which gives an error. Variable must come.

> Left values are the destination of an assignment.

 It seems that something like this was intended, but I can't understand it well... I am still trying to understand the sentence.

**Comment by sideshowbarker** [comment]
> I wonder if it makes more sense to just remove this, for the sake of the Guide.

I think removing it makes more sense
