### ISSUE TITLE
Issue with "Set-Cookie": Duplicate content

### ISSUE THREAD

**Issue by BlackSunlight** [mdn/content#6588]
MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Set-Cookie

#### What information was incorrect, unhelpful, or incomplete?
Duplicated \<ul\> after the syntax section

#### Specific section or headline?
Syntax section: 

По умолчанию - хост текущего URL документа, не включая поддомены
В текущей спецификация начальная точка в имени хоста игнорируется (.example.com)
Cookie будут отправляться также на поддомены указанного хоста
Указывать несколько хостов недопустимо.
По умолчанию - хост текущего URL документа, не включая поддомены
В текущей спецификация начальная точка в имени хоста игнорируется (.example.com)
Cookie будут отправляться также на поддомены указанного хоста
Указывать несколько хостов недопустимо.

#### What did you expect to see?
Unique content

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/http/headers/set-cookie`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Set-Cookie
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/http/headers/set-cookie/index.html
* Last commit: https://github.com/mdn/translated-content/commit/68b6aba0b2a1f8005e1c181c06e40eea4af9cd2f
* Document last modified: 2021-07-04T00:36:02.000Z

</details>

**Comment by Ryuno-Ki** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
