### ISSUE TITLE
Issue with "The JavaScript input interpreter": images has bad ratio (height should be set to auto)

### ISSUE THREAD

**Issue by Juraj-Masiar** [mdn/content#659]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter

#### What information was incorrect, unhelpful, or incomplete?
![image](https://user-images.githubusercontent.com/6358971/103167748-1f8d9500-482e-11eb-8f66-f7ea118add28.png)
Bad image height (should be set to auto)

#### Specific section or headline?
Single-line mode

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/web_console/the_command_line_interpreter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/tools/web_console/the_command_line_interpreter/index.html
* Report started: 2020-12-27T09:22:07.195Z

</details>

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/issues/1498

**Comment by hamishwillee** [comment]
I have fixed this case in #713 by removing height styling. I'm aware that this may be fixed globally eventually.

**Comment by mattiapontonio** [comment]
https://github.com/mdn/content/search?l=HTML&q=style&type=

I'm not sure about _banning inline style_.
