### ISSUE TITLE
Issue with "History API": (misprint)

### ISSUE THREAD

**Issue by r-nicolay** [mdn/content#6596]
MDN URL: https://developer.mozilla.org/ru/docs/Web/API/History_API

#### What information was incorrect, unhelpful, or incomplete?
"методы объекта истории для добавления, замени и перемещения по истории"

#### Specific section or headline?
Примеры

#### What did you expect to see?
"методы объекта истории для добавления, замен**Ы** и перемещения по истории"

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/api/history_api`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/History_API
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/api/history_api/index.html
* Last commit: https://github.com/mdn/translated-content/commit/3f3c834f4bebd2680874d318925f9068fad47f1a
* Document last modified: 2021-07-04T21:52:14.000Z

</details>

**Comment by Ryuno-Ki** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
