### ISSUE TITLE
Think is a typo here

### ISSUE THREAD

**Issue by ejgutierrez74** [mdn/content#660]
https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Sentencias/throw

> function ZipCode(zip) {
>    zip = new String(zip);
>    pattern = /[0-9]{5}([- ]?[0-9]{4})?/;
>    if (pattern.test(zip)) {
>       // zip code value will be the first match in the string
>       this.value = zip.match(pattern)[0];
>       this.valueOf = function() {
>          return this.value
>       };
>       this.toString = function() {
>          return String(this.value)
>       };
>    } else {
>       throw new ExcepcionFormatoCodigoPostal(zip);
>    }
> }

should be in spanish language...

> function CodigoPostal(zip) {
>    zip = new String(zip);
>    pattern = /[0-9]{5}([- ]?[0-9]{4})?/;
>    if (pattern.test(zip)) {
>       // zip code value will be the first match in the string
>       this.value = zip.match(pattern)[0];
>       this.valueOf = function() {
>          return this.value
>       };
>       this.toString = function() {
>          return String(this.value)
>       };
>    } else {
>       throw new ExcepcionFormatoCodigoPostal(zip);
>    }
> }

**Comment by mattiapontonio** [comment]
<pre>
function <del>ZipCode</del>(zip) {
</pre>

**Comment by ejgutierrez74** [comment]
Is this approved ??

**Comment by mattiapontonio** [comment]
I tested using HTML in markdown.

```
<pre>
function <del>ZipCode</del><ins>CodigoPostal</ins>(zip) {
</pre>
```

Like in a PR.
But actually I think that a PR in language is not permitted, the Lang repositories are frozen.
About tranlating the code Yes, sounds good.
In this case the logic itself, the pattern, change from language to language.

<blockquote>
This means that upon launch, we still plan to display translations in all existing locales, but they will all initially be frozen — read-only, not editable.
</blockquote>
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/

**Comment by ejgutierrez74** [comment]
Why isnt approved ? If you dont change the name of the Function, to create a new CodigoPostal you need the function CodigoPostal and not ZipCode, it would generate an error. I noticed there are some errors like thatt...thanks

**Comment by mattiapontonio** [comment]
I don't know now how to fix.
Try to tag someone from the readme.

**Comment by chrisdavidmills** [comment]
I'm afraid we aren't accepting changes to localized content right now. The earlier blog post explains why: https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/
