### ISSUE TITLE
Issue with "Getting started with CSS": (typo)

### ISSUE THREAD

**Issue by andrasna** [mdn/content#6600]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started

Related to #6536 

#### What information was incorrect, unhelpful, or incomplete?

> You can change the way the link looks when the user hovers over it, for example by removing the underline, which is **achieved by in** the next rule:

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started#styling_things_based_on_state

#### What did you expect to see?

I think the "in" in "achieved by in" doesn't sound correct.

I think this is okay:

> ...is **achieved by** the next rule:

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/first_steps/getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/first_steps/getting_started/index.html
* Last commit: https://github.com/mdn/content/commit/a21526212cda17cefd5240d59cc27caeb35cfec6
* Document last modified: 2021-07-03T08:14:04.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Thank you, @rachelandrew, for addressing this in #6601.
