### ISSUE TITLE
Issue with "Using your new knowledge": (inappropriate color)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6607]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Using_your_new_knowledge

#### What information was incorrect, unhelpful, or incomplete?
Make the level one heading pink, using the CSS color keyword **hotpink**.

#### Specific section or headline?
Working with CSS

#### What did you expect to see?
The color hotpink is for girls. 

#### Did you test this? If so, how?
Just joking. I think you guys are great volunteering your time and knowledge to help others. Much love! Have a wonderful day.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/first_steps/using_your_new_knowledge`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Using_your_new_knowledge
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/first_steps/using_your_new_knowledge/index.html
* Last commit: https://github.com/mdn/content/commit/3dfbc889fe84917f10a78bd5ec6041ccc2821e36
* Document last modified: 2021-03-22T04:51:21.000Z

</details>

**Comment by Rumyra** [comment]
Thanks @ConsciousClay :) If it helps `hotpink` goes _really_ well with `yellowgreen` 👍
