### ISSUE TITLE
Issue with "MouseEvent.ctrlKey": 'command' instead of 'control' for Mac keyboards

### ISSUE THREAD

**Issue by MartinHeywang** [mdn/content#6624]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/ctrlKey

#### What information was incorrect, unhelpful, or incomplete?

As explained already in the title, the key corresponding to 'ctrl' on Windows/Linux is "command" on Mac.

#### Specific section or headline?

The very first "Note" at the top of the page.

#### What did you expect to see?

"Command", instead of "Control"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mouseevent/ctrlkey`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/ctrlKey
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mouseevent/ctrlkey/index.html
* Last commit: https://github.com/mdn/content/commit/19f75559a3df713dd1487807a4bbd84a9e3fd62e
* Document last modified: 2021-06-14T14:36:19.000Z

</details>

**Comment by teoli2003** [comment]
I tried "Command"-click in the live example on the  and it returned false. So I'm not convinced that it should be "Command".

It could be "Control"-click, but this is not transfered to the application as the OS intercepts it to display the contextual menu, so I couldn't validate.

**Comment by sideshowbarker** [comment]
I’m going ahead and closing this, because he existing statement *“Note: On Macintosh keyboards, this key is the `control` key”* is correct as written. (The example in the article isn’t a good one and should be replaced, but that’s not what this issue is about.)
