### ISSUE TITLE
Issue with "console.time()": minor typo

### ISSUE THREAD

**Issue by alecgregory** [mdn/content#6626]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Console/time

#### What information was incorrect, unhelpful, or incomplete?
time,vin milliseconds,

#### Specific section or headline?
time,vin milliseconds,

#### What did you expect to see?
time, in milliseconds,

#### Did you test this? If so, how?
occular inspection

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/console/time`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Console/time
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/console/time/index.html
* Last commit: https://github.com/mdn/content/commit/cbca1200cf311812cd61fab50a4d0ff67f759fd1
* Document last modified: 2021-06-28T01:25:18.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@alecgregory Thank you for reporting.
It just got fixed and can take up to 48 hours to appear on the website.
