### ISSUE TITLE
Issue with "Date formatting using luxon":Link to Formatting section of luxon documentation is broken

### ISSUE THREAD

**Issue by Prince-Thind** [mdn/content#6631]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Date_formatting_using_moment

#### What information was incorrect, unhelpful, or incomplete?
The link to luxon formatting documentation seems to have broken.

#### Specific section or headline?
Create The Virtual Property, The blue 'note' block

#### What did you expect to see?
I expected to see, the formatting documentation of the luxon js library.

#### Did you test this? If so, how?
Visiting the link seems to confirm that it is infact broken.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/date_formatting_using_moment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Date_formatting_using_moment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/date_formatting_using_moment/index.html
* Last commit: https://github.com/mdn/content/commit/3f0d70a833121be094f90194c23b3acfb19539fa
* Document last modified: 2021-01-29T00:55:21.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/6797 with a fix.
