### ISSUE TITLE
Content bug: Error in the result section code, contextmenu

### ISSUE THREAD

**Issue by hochan222** [mdn/content#6635]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contextmenu#result

## Specific page section or heading?

result

## What is the problem?

![image](https://user-images.githubusercontent.com/22424891/124716077-a1c5e700-df3e-11eb-9043-80fd2e134ad5.png)

Image is broken or something is wrong

---

The URL link is broken in the following code

```js
function changeImage() {
  var index = Math.ceil(Math.random() * 39 + 1);
  document.images[0].src =
      "https://developer.mozilla.org/media/img/promote/promobutton_mdn" +
      index + ".png";
}
```

## What did you expect to see?

![image](https://user-images.githubusercontent.com/22424891/124716150-b1453000-df3e-11eb-9c27-f96d094809f0.png)

There should be no picture above.

## Did you test this? If so, how?

no

**Comment by globau** [comment]
The missing files can be found at https://github.com/mdn/kuma/tree/d678bccd286f35302a333ca2e734358ab96a45f5/assets/static/img/promote, removed in https://github.com/mdn/kuma/commit/0d8bddf2c397bd6343623ceb0a53f9ad805a0647

**Comment by sideshowbarker** [comment]
Thanks @hochan222 for raising this, and thanks @globau for the pointer to older kuma revision with the images — I’ve opened https://github.com/mdn/content/pull/6799 with a fix.

**Comment by globau** [comment]
#6799 doesn't appear to be sufficient: `changeImage()` selects a random image between 1 and 39 inclusive, while #6799 only added image 5.  

Also note the changes to `changeImage()` sets the image src to `${index}.png`, while the images are named `promobutton_mdn${index}.png`.

**Comment by sideshowbarker** [comment]
> #6799 doesn't appear to be sufficient: `changeImage()` selects a random image between 1 and 39 inclusive, while #6799 only added image 5.
> 
> Also note the changes to `changeImage()` sets the image src to `${index}.png`, while the images are named `promobutton_mdn${index}.png`.

It doesn’t work anyway, right? Not even in Firefox — as far as I could see in testing — and definitely not in any other browsers.

I intentionally limited the patch to just fixing the broken image, and not spending any other time on the code. Since `contextmenu` itself is completely obsolete, making further substantive changes this article doesn’t seem like a good investment of anybody’s time.

In fact I guess we probably want to consider archiving this entire article.

**Comment by teoli2003** [comment]
Doesn't work on Firefox for Mac OS.

I'm still curious to know when this stopped working in Firefox as we need this info to update/remove the related bcd.
