### ISSUE TITLE
Issue with "GlobalEventHandlers.oninput": broken link to external reference

### ISSUE THREAD

**Issue by builder60** [mdn/content#6646]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/oninput

#### What information was incorrect, unhelpful, or incomplete?

The link under "A HTML5 Browser maze, oninput support" results in 404

#### Specific section or headline?

Browser compatibility notes.

#### What did you expect to see?
a page

#### Did you test this? If so, how?
yes, clicked on it.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/globaleventhandlers/oninput`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/oninput
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/globaleventhandlers/oninput/index.html
* Last commit: https://github.com/mdn/content/commit/bac34052947faec75a5d642efc2e0df0b2c3fb04
* Document last modified: 2021-06-13T07:49:26.000Z

</details>

**Comment by teoli2003** [comment]
Thanks a lot!

I wasn't able to find a working URL for it, so I just removed it.
