### ISSUE TITLE
Deprecated interface AudioStreamStrack which has no MDN page is appearing in the sidebar

### ISSUE THREAD

**Issue by SuperPauly** [mdn/content#6649]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API

404 page does not exist when I visit it.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/media_streams_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/media_streams_api/index.html
* Last commit: https://github.com/mdn/content/commit/95d888ea5c6202662c709880e47596f1d3466c52
* Document last modified: 2021-04-28T19:29:34.000Z

</details>

**Comment by rachelandrew** [comment]
Thanks @SuperPauly that Interface is deprecated, I'm not sure why it is still showing in the sidebar though, I've edited the issue title to make it more clear.

**Comment by teoli2003** [comment]
It is still listed in GroupData.json in yari.

<img width="736" alt="Screenshot 2021-07-07 at 17 22 59" src="https://user-images.githubusercontent.com/1466293/124786426-fd48a280-df47-11eb-95e8-6f56d63df695.png">

I'm creating a PR to remove it.
