### ISSUE TITLE
Issue with "Date.prototype.getTimezoneOffset()": …

### ISSUE THREAD

**Issue by AndreLeifert** [mdn/content#665]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset

The statement "The getTimezoneOffset() method returns the time zone difference, in minutes, from current locale (host system settings) to UTC." means local - UTC, while the function returns UTC - local.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/gettimezoneoffset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
* Report started: 2020-12-27T18:50:01.226Z

</details>

**Comment by sideshowbarker** [comment]
FYI I’m working on a patch for this, and will raise a PR as soon as I’ve got it ready

**Comment by sideshowbarker** [comment]
Opened https://github.com/mdn/content/pull/893
