### ISSUE TITLE
Issue with "Introduction to events": (when an event is fired modern broser runs three phases not two)

### ISSUE THREAD

**Issue by Archangelll** [mdn/content#6657]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events

#### What information was incorrect, unhelpful, or incomplete?
When the author said that modern browsers runs two phases (and not three) when an event is dispatched.
the capturing and bubbling phases **does not include** the target node.
it can lead the reader to misunderstand some MDN docs explanations, E.g: https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation
the above link mentions the capturing and bubbling phases and if the reader has in mind that the target phase is part of the capturing and bubbling phases, it will misunderstand what that method does
https://dom.spec.whatwg.org/#dom-event-eventphase

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#bubbling_and_capturing_explained

#### What did you expect to see?
When an event is fired on an element that has parent elements, modern browsers run three different phases — the capturing phase, the target phase and the bubbling phase.

#### Did you test this? If so, how?
nope

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/events/index.html
* Last commit: https://github.com/mdn/content/commit/e65944bcaf4056b8e78144aa62309defc1f32791
* Document last modified: 2021-06-08T12:51:38.000Z

</details>

**Comment by Archangelll** [comment]
@sideshowbarker i just read your update, and some capturing/bubbling content still wrong. the capturing phase does not reaches the event.target, it propagates up to the direct parent of the target node, and the bubbling phase does not include the event.target, it begins propagating from the direct parent of the event.target, and the target phase does not calls **any** event listeners registered for this phase, it calls only the event listeners that was registered with the 'click' Event (previous context).

**Comment by Archangelll** [comment]
see also:
https://stackoverflow.com/questions/4616694/what-is-event-bubbling-and-capturing
https://stackoverflow.com/questions/7398290/unable-to-understand-usecapture-parameter-in-addeventlistener

**Comment by sideshowbarker** [comment]
I invite you to consider doing a rewrite that expresses what more you believe needs to be added or changed.

At https://github.com/mdn/content/edit/main/files/en-us/learn/javascript/building_blocks/events/index.html you can edit the article source directly, and submit your changes, and then that will create a GitHub pull request we can review.

Alternatively, uou can post the re-write as a comment here, and I’ll be happy to review it and create a patch and pull request for getting it added.

**Comment by Archangelll** [comment]
can i include the following jsfiddle inside a note ?
https://jsfiddle.net/e3whkpv9/1/

**Comment by Archangelll** [comment]
@sideshowbarker done.

**Comment by Archangelll** [comment]
I've never used GitHub before except for uploading files to private repositories, so I think that you will make a better job than me in opening a pull request to update this article. following is the link to the changes that I had made:

https://github.com/mdn/content/pull/6985/files

**Comment by sideshowbarker** [comment]
> @sideshowbarker I've never used GitHub before except for uploading files to private repositories, so I think that you will make a better job than me in opening a pull request to update this article. 

Your changes in the PR were fine, actually. Today I’ll supplement those changes with the code from https://jsfiddle.net/Archangelll/we76k0fb/, and merge it all.

**Comment by sideshowbarker** [comment]
@Archangelll, your change landed in 8e6e2fa, so thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

**Comment by Archangelll** [comment]
thank you :)
