### ISSUE TITLE
Issue with "Cascade and inheritance": (run-on sentence)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6659]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

#### What information was incorrect, unhelpful, or incomplete?
There is a special piece of CSS that you can use to overrule all of the above calculations, however, you should be very careful with using it

#### Specific section or headline?
!important

#### What did you expect to see?
There are two independent clauses here being joined by the adverb **however**. This adverb is not a conjunction. The two clauses should be separate sentences and the adverb **however** should modify only one of them:

There is a special piece of CSS that you can use to overrule all of the above calculations. However, you should be very careful with using it...

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.html
* Last commit: https://github.com/mdn/content/commit/1fdf7958ea85bab45e1d7ba3634e9381eae937d1
* Document last modified: 2021-01-27T07:42:45.000Z

</details>

**Comment by teoli2003** [comment]
Hi, @ConsciousClay.

Thanks a lot for filling all these issues. I've opened a PR for this one. (So many occurences of _however_ on this page!)

For typos and grammar, the errors are fairly obvious once pointed at. ;aybe you should try to directly open PRs (Pull Requests). That way, you'll have less work to do, as opening a PRR is likely quicker than to describe the grammar problem in details.

If you don't want, no problem!

**Comment by ConsciousClay** [comment]
Okay, I'll try that next time.
