### ISSUE TITLE
Issue with "Working with Mozilla source code": …

### ISSUE THREAD

**Issue by Lexicon9** [mdn/content#666]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code

#### What information was incorrect, unhelpful, or incomplete?
https://developer.mozilla.org/en-US/Developer_Guide/Source_Code/Mercurial
link is missing/broken, the url is a 404

#### Specific section or headline?
"Getting the code from the Mercurial repository"

#### What did you expect to see?
a working page, at least https://developer.mozilla.org/en-US/Developer_Guide/Source_Code/Mercurial,
but better https://firefox-source-docs.mozilla.org/contributing/vcs/mercurial.html

#### Did you test this? If so, how?
by going to the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/developer_guide/source_code`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Source_Code
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/developer_guide/source_code/index.html
* Report started: 2020-12-27T19:31:27.307Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. I’ve opened https://github.com/mdn/content/pull/672 with a fix.
