### ISSUE TITLE
Issue with "Functions": (replace period ['.'] with colon [:] where appropriate to do so)

### ISSUE THREAD

**Issue by abergquist** [mdn/content#6665]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions

#### What information was incorrect, unhelpful, or incomplete?

Since certain text is a "lead-in" - introducing a code example - that code should not end with a period (".") but with a colon (":"). 

By making the two/2 changes requested below, it makes the text consistent with other already correctly "colon-ized" text (e.g., "For example, the following function definition defines myFunc only if num equals 0:")

#### Specific section or headline?

                                                                                               .
                                                                                               .
                                                                                               .
The following example shows a map function that should receive a function as first argument and an array as second argument.
                                                                                               .
                                                                                               .
                                                                                               .                                                                                              
In the following code, the function receives a function defined by a function expression and executes it for every element of the array received as a second argument.
                                                                                               .
                                                                                               .
                                                                                               .

#### What did you expect to see?

                                                                                               .
                                                                                               .
                                                                                               .
The following example shows a map function that should receive a function as first argument and an array as second argument:
                                                                                               .
                                                                                               .
                                                                                               .                                                                                              
In the following code, the function receives a function defined by a function expression and executes it for every element of the array received as a second argument:
                                                                                               .
                                                                                               .
                                                                                               .

#### Did you test this? If so, how?

Not applicable.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/functions/index.html
* Last commit: https://github.com/mdn/content/commit/eac726491e9dde375b769077f9c194d36203b801
* Document last modified: 2021-05-10T12:55:00.000Z

</details>

**Comment by teoli2003** [comment]
Thanks for the report. I've opened a PR adding these two colons.

**Comment by abergquist** [comment]
Thanks, @teoli2003 and @rachelandrew.

Trying to get a sense of timing ... how soon after this GitHub issue is closed should we see the change in the web page itself?

Thanks

**Comment by teoli2003** [comment]
You're welcome.

The short answer is usually about 24h. The detailed answer is there: https://github.com/mdn/content/#when-will-my-change-show-up-on-the-production-mdn-site

**Comment by abergquist** [comment]
Thanks, @teoli2003!
