### ISSUE TITLE
Issue with "FileReader.readAsText()": loadend link is wrong

### ISSUE THREAD

**Issue by yeya** [mdn/content#6677]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsText

#### What information was incorrect, unhelpful, or incomplete?
The loadend link points to XHR loadend event instead of FileReader loadend event

#### Specific section or headline?
[here](https://github.com/mdn/content/blob/main/files/en-us/web/api/filereader/readastext/index.html#L17)

#### What did you expect to see?
The link should point to https://developer.mozilla.org/en-US/docs/Web/API/FileReader/loadend_event

#### Did you test this? If so, how?
I clicked the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/filereader/readastext`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsText
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/filereader/readastext/index.html
* Last commit: https://github.com/mdn/content/commit/5ecba2e39835dc1ea70a9094e9d6099fd2c8295c
* Document last modified: 2021-06-13T08:03:46.000Z

</details>

**Comment by dontcallmedom** [comment]
It looks like this is a general problem with events whose names are re-used across several emitters; e.g. https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API links `ended` to https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/ended_event - and thus probably a limitation of the ``event()`` macro in Yari

**Comment by yeya** [comment]
I think that in this case it can be solved easily by `domxref` like the rest of the links in the header.

**Comment by teoli2003** [comment]
That's exactly this: after a reorganisation (separating synonym events), the {{event}} macro may point to the wrong event; the only way to solve it is to use {{domxref}} instead. 

I opened a PR.

Thanks for signaling it.
