### ISSUE TITLE
Issue with "HTMLImageElement.alt": (typo in content)

### ISSUE THREAD

**Issue by Astra-Gal** [mdn/content#6685]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt

#### What information was incorrect, unhelpful, or incomplete?
'This may impact the decisions you make shen writing the alt text for the diagram.'

#### Specific section or headline?
Images containing diagrams or maps

#### What did you expect to see?

'when' instead of 'shen'
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlimageelement/alt`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlimageelement/alt/index.html
* Last commit: https://github.com/mdn/content/commit/c3f983877e23ae219f9ea93ba497d1f6614397ad
* Document last modified: 2021-06-25T05:49:12.000Z

</details>

**Comment by teoli2003** [comment]
Thanks a lot ! I opened a PR to fix it.

For typo/grammar fixes, if you prefer, fill free to directly open a PR. But reporting them in an issue like you did is also fine!
