### ISSUE TITLE
Typed Arrays cannot be frozen

### ISSUE THREAD

**Issue by CrimsonCodes0** [mdn/content#669]
Not sure if this is the right place to mention it, but, it would be nice to have a note and example somewhere mentioning that freezing typed arrays may throw an exception.

**Comment by sideshowbarker** [comment]
Your PR at https://github.com/mdn/content/pull/752 seemed like it would resolve this issue. Is there a reason you closed that PR? Was it incomplete or something?

**Comment by CrimsonCodes0** [comment]
> Your PR at #752 seemed like it would resolve this issue. Is there a reason you closed that PR? Was it incomplete or something?

Oh, I think I was too busy then to have completed it then, but my schedule cleared up recently. I can probably revive the PR tommorow.

**Comment by sideshowbarker** [comment]
> Oh, I think I was too busy to have completed it then, but my schedule cleared up recently. I can probably revive the PR tomorrow.

🎉 That’s great to hear — looking forward to it

**Comment by CrimsonCodes0** [comment]
@sideshowbarker So, I was looking around, and hadn't seen any section that would be easily extensible to include the three exceptions that I would've tried documenting. I see that there's an [entire page dedicated to a single error that the constructor can throw](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Typed_array_invalid_arguments), and there's the single [`new` exception example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#examples) (but I doubt I'd do anything on that page), and the [primary page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays) on TypedArrays, which lacks any mention of exceptions, and I think it wouldn't fit in well.

Where would you suggest that I start the writeup?

(note: I had updated the [old PR](https://github.com/mdn/content/pull/752)'s description and goals, but I won't be reopening it as the branch was already deleted; I'll just create a new one)

**Comment by sideshowbarker** [comment]
> Where would you suggest that I start the writeup?

What about at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray — that is, the reference page for that `TypedArray` object itself?

**Comment by CrimsonCodes0** [comment]
> > Where would you suggest that I start the writeup?
> 
> What about at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray — that is, the reference page for that `TypedArray` object itself?

Okay, I'll get started there soon.
