### ISSUE TITLE
Issue with "Storage Inspector": Different origin links link to the same origin

### ISSUE THREAD

**Issue by martenmatrix** [mdn/content#6692]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector

#### What information was incorrect, unhelpful, or incomplete?
The text 'For example, "https://mozilla.org" and "https://mozilla.org" are two different origins so local storage items cannot be shared between them.'.

#### Specific section or headline?
Storage tree

#### What did you expect to see?
I expected to see two different links, which both would link to a different origin. Maybe I am wrong, but those two links are the same and therefore link to the same origin. Or I misunderstood something...

#### Did you test this? If so, how?
:/

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/storage_inspector`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/storage_inspector/index.html
* Last commit: https://github.com/mdn/content/commit/e0a36d636574e8b25492026c064e39762bc36716
* Document last modified: 2021-02-10T18:03:04.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this — I’ve opened https://github.com/mdn/content/pull/6800 with a fix.
