### ISSUE TITLE
Issue with "Classes": (short summary here please)

### ISSUE THREAD

**Issue by igdkaur** [mdn/content#6696]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
 
Static methods and properties

the link in the line "The static keyword defines a static method or property for a class. Static members (properties and methods) are called without instantiating " at the word instantiating leads to a wrong page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/classes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/classes/index.html
* Last commit: https://github.com/mdn/content/commit/f5fceb84ae30e2205fa3085f0bdd3142c46e655e
* Document last modified: 2021-06-25T05:47:10.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/6801 with a fix.
