### ISSUE TITLE
Issue with "Object.prototype.constructor": …

### ISSUE THREAD

**Issue by maruthimohan** [mdn/content#670]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor

#### What information was incorrect, unhelpful, or incomplete?
In the section mentioned below (Changing the constructor of a function), while describing how to add the static members of the Parent to Child,

```
...
Child = Object.assign(ParentWithStatic) // Notice that we assign it before we create(...) a prototype below
Child.prototype = Object.create(ParentWithStatic.prototype)
...
```
the above code segment does not seem correct. Because while copying enumerable properties from ParentWithStatic, `Object.assign(ParentWithStatic)` is completely removing the Child's reference to its function-constructor. As a result, the modified example with modifications suggested like below,

```
function ParentWithStatic() {}

ParentWithStatic.startPosition = { x: 0, y:0 } // Static member property
ParentWithStatic.getStartPosition = function getStartPosition() {
  return this.startPosition
}

function Child(x, y) {
  this.position = {
    x: x,
    y: y
  }
}

Child = Object.assign(ParentWithStatic)
Child.prototype = Object.create(ParentWithStatic.prototype)

Child.prototype.getOffsetByInitialPosition = function getOffsetByInitialPosition() {
  let position = this.position
  let startPosition = this.constructor.getStartPosition() // error undefined is not a function, since the constructor is Child

  return {
    offsetX: startPosition.x - position.x,
    offsetY: startPosition.y - position.y
  }
};

// Added the initialization code,
new Child().getOffsetByInitialPosition(); // Since we are going with Parent Constructor

```

throws an error stating that, `this.position` is undefined.

#### Specific section or headline?
Changing the constructor of a function

#### What did you expect to see?
I think the while adding the enumerable properties of the Parent to Child, the code line should have been like below,
`Child = Object.assign(Child, ParentWithStatic)`
instead of 
`Child = Object.assign(ParentWithStatic)`

#### Did you test this? If so, how?
I tested this error scenario both in local and in JS Bin.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/constructor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/object/constructor/index.html
* Report started: 2020-12-27T22:15:13.603Z

</details>

**Comment by sideshowbarker** [comment]
Do you want to open a pull request for this? If not, I could — just let me know.

**Comment by maruthimohan** [comment]
@sideshowbarker I would create a PR for this, thank you!

**Comment by maruthimohan** [comment]
@sideshowbarker could you please review the PR?
