### ISSUE TITLE
Issue with "Error() constructor": Missing options object with cause

### ISSUE THREAD

**Issue by HolgerJeromin** [mdn/content#6705]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error

#### What information was incorrect, unhelpful, or incomplete?

Missing some words about cause options.

#### What did you expect to see?

see https://v8.dev/features/error-cause

ref https://github.com/mdn/browser-compat-data/pull/11446

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/error/error`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/error/error/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by teoli2003** [comment]
This will likely be handled as part of #6714

**Comment by HolgerJeromin** [comment]
Closing as duplicate than.
