### ISSUE TITLE
Issue with "Setup": (short summary here please)

### ISSUE THREAD

**Issue by sumanchapai** [mdn/content#6707]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Build_a_phone_with_peerjs/Setup

#### What information was incorrect, unhelpful, or incomplete?
`mkdir` and `cd` have two different parameters

#### What did you expect to see?
`mkdir phone_app` and `cd phone_app` or any consistent name

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webrtc_api/build_a_phone_with_peerjs/setup`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Build_a_phone_with_peerjs/Setup
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webrtc_api/build_a_phone_with_peerjs/setup/index.html
* Last commit: https://github.com/mdn/content/commit/31b0666be2a938e5d52bb48bc1e03320c85546f7
* Document last modified: 2021-02-04T11:01:43.000Z

</details>

**Comment by teoli2003** [comment]
Thanks! for consistency with the `json` below, I chose "audio_app".
