### ISSUE TITLE
[JS] More additions to Intl.DateTimeFormat

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#6710]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- A few more additions to Intl.DateTimeFormat

## Related Gecko bugs

- [Ship Intl.DateTimeFormat.prototype.formatRange and .formatRangeToParts to release](https://bugzilla.mozilla.org/show_bug.cgi?id=1653024).
- [Implement Extended TimeZoneName Options for Intl.DateTimeFormat](https://bugzilla.mozilla.org/show_bug.cgi?id=1710429)

More functionality for the Intl.DateTimeFormat, docs & bcd will need updating.

## Other

- [Implement Intl.DisplayNames v2](https://bugzilla.mozilla.org/show_bug.cgi?id=1693575) Seems this bug suggest the proposal has been fully implemented. Worth checking and setting `dev-doc-complete` here too.

**Comment by hamishwillee** [comment]
## Status

[1653024: Ship Intl.DateTimeFormat.prototype.formatRange and .formatRangeToParts to release](https://bugzilla.mozilla.org/show_bug.cgi?id=1653024)
- This enables the (already) documented [Intl.DateTimeFormat.prototype.formatRangeToParts()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRangeToParts) and [Intl.DateTimeFormat.prototype.formatRange()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange) which were formerly only enabled in nightly. 
- - [ ] Experimental features - not present
- - [ ] Docs
   - [Intl.DateTimeFormat.prototype.formatRangeToParts()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRangeToParts) needs a little tidy as output does not match indicated info
      - - [ ] #6841
      - - [ ] #6843
   -  [Intl.DateTimeFormat.prototype.formatRange()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange) - no work required.
- - [ ] Interactive examples may need a little tidy.
  - - [ ]  https://github.com/mdn/interactive-examples/pull/1866
- - [ ] BCD https://github.com/mdn/browser-compat-data/pull/11497
- - [ ] Dev-docs-complete
- - [ ] Release note

[1710429: Implement Extended TimeZoneName Options for Intl.DateTimeFormat](https://bugzilla.mozilla.org/show_bug.cgi?id=1710429)
- Still investigating

**Comment by hamishwillee** [comment]
This is all done!

**Comment by Rumyra** [comment]
🙌
