### ISSUE TITLE
[JS] Implement the Error Cause proposal

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#6714]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Implement the Error Cause proposal

## Related Gecko bugs

- [Implement the Error Cause proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1679653). This needs investigating to whether any docs need updating. From a first pass this just looks like they're now defining a consistent way for errors within promises or try catch, but that's just my first impression.

## Other

- [TC39 proposal](https://github.com/tc39/proposal-error-cause)

**Comment by hamishwillee** [comment]
Status
- BCD: https://github.com/mdn/browser-compat-data/pull/11446#issuecomment-887093398 - Discussing version this actually went in for, and the right structure here (feels like it is a bit screwed)

**Comment by hamishwillee** [comment]
@Rumyra FYI All the parts for this now in place. They still need review though.

**Comment by Rumyra** [comment]
BCD is still open - but seems to be ready to merge Mon/Tues, so I'm going to 'done' & close this 👍 Thanks @hamishwillee
