### ISSUE TITLE
[CSS] fit-content() value for width/min-width/max-width property

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#6715]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- fit-content() value for width/min-width/max-width property

## Related Gecko bugs

- [Implement fit-content(<length-percentage>) value of width/min-width/max-width property](https://bugzilla.mozilla.org/show_bug.cgi?id=1312588).

**Comment by rachelandrew** [comment]
ok, I think all of the bits are in place for this one now.

**Comment by Rumyra** [comment]
Perfect - thanks @rachelandrew
