### ISSUE TITLE
[CSS] Implement 'content: none' for elements

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#6716]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Implement 'content: none' for elements

## Related Gecko bugs

- [Implement 'content: none' for elements](https://bugzilla.mozilla.org/show_bug.cgi?id=1699964).

## Other

- Possibly related (although possibly not anything doc related) ['content: none' behaves like 'content: normal' in ::marker instead of destroying it](https://bugzilla.mozilla.org/show_bug.cgi?id=1605473)

**Comment by rachelandrew** [comment]
Once the PRs are merged this is done. The syntax and so on already included the feature, as it's behind a flag and not implemented anywhere else it's a bit too early to add examples.

**Comment by Rumyra** [comment]
Going to move this to done, but I'll leave it open just for the moment (I read through the bcd thread and will keep my eye on it)

**Comment by rachelandrew** [comment]
This has been reverted in the spec and in Firefox https://github.com/w3c/csswg-drafts/issues/6503. So I'll need to roll back these changes.

**Comment by rachelandrew** [comment]
PR to remove from docs: https://github.com/mdn/content/pull/7963
