### ISSUE TITLE
[CSS] Dropping -moz prefix from tab-size property

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#6718]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Dropping -moz prefix from tab-size property

## Related Gecko bugs

- [Implement 'tab-size' (dropping the -moz- prefix)](https://bugzilla.mozilla.org/show_bug.cgi?id=737785).

**Comment by rachelandrew** [comment]
This is done pending merge of BCD and release notes.

**Comment by rachelandrew** [comment]
Everything is now merged, closing.
