### ISSUE TITLE
[CSS] font-size-adjust takes pair of values

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#6720]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- font-size-adjust takes pair of values

## Related Gecko bugs

- [css-fonts extend font-size-adjust to take a pair of values: <metric> <number>](https://bugzilla.mozilla.org/show_bug.cgi?id=1711479).

**Comment by rachelandrew** [comment]
Everything is now merged, closing this issue.
