### ISSUE TITLE
[webAPI] SecureContext for Gamepad API

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#6723]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Add SecureContext and Permission Policy to Gamepad API

## Related Gecko bugs

- [Add SecureContext and Permission Policy to Gamepad API](https://bugzilla.mozilla.org/show_bug.cgi?id=1704005). Worth checking through the Gamepad API docs, but should just need secure header.

**Comment by hamishwillee** [comment]
Looks like this might get backed out. Note also the name is deceptive - it is still FeaturePolicy not Permission Policy in FF.

**Comment by Rumyra** [comment]
Thanks @hamishwillee seems so... I'll keep my eye on the issue throughout the project. We can always move it to the next project if need be 👍

**Comment by hamishwillee** [comment]
FYI, looks like this might be going ahead, so I started the work of establishing exactly what delivered in https://bugzilla.mozilla.org/show_bug.cgi?id=1704005#c27

**Comment by hamishwillee** [comment]
Status:
- BCD permission/directive: https://github.com/mdn/browser-compat-data/pull/11770
-

**Comment by Rumyra** [comment]
Thanks @hamishwillee 👍
