### ISSUE TITLE
[CSS] Change how 'pad' descriptor handles negative

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#6724]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- [css-counter-styles] Change how 'pad' descriptor handles negative sign to match implementations

## Related Gecko bugs

- [css-counter-styles Change how 'pad' descriptor handles negative sign to match implementations](https://bugzilla.mozilla.org/show_bug.cgi?id=1714445). Rachel I'm sure you're more aware of this bug than I and on a first pass I doubt there's anything to do unless it's been mentioned in BCD anywhere. So feel free to close it if there isn't anything.

**Comment by rachelandrew** [comment]
@Rumyra this doesn't seem to be mentioned anywhere and is just a bugfix. I've updated the bug to dev-doc-complete and am going to add a note to the release notes then close this.

**Comment by Rumyra** [comment]
Thanks @rachelandrew - appreciated 🙏
