### ISSUE TITLE
Issue with "IndexedDB key characteristics and basic terminolog…": ("Limitations" section appears twice)

### ISSUE THREAD

**Issue by paddyohanlon** [mdn/content#6726]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Basic_Terminology

#### What information was incorrect, unhelpful, or incomplete?

The **Limitations** section appears twice on the page, with the same content. Both headings use the same `limitations` ID attribute.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Basic_Terminology#limitations

The same ID is used for both occurrences.

#### What did you expect to see?

At a glance, it seems the `h3` **Limitations** heading, under **Key characteristics** should not be there and should be removed.

#### Did you test this? If so, how?

This isn't really applicable.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/indexeddb_api/basic_terminology`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Basic_Terminology
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/indexeddb_api/basic_terminology/index.html
* Last commit: https://github.com/mdn/content/commit/9159d258a7054d36d6c3f31564bd9e54cd8095a8
* Document last modified: 2021-06-14T16:50:43.000Z

</details>

**Comment by teoli2003** [comment]
Thanks for the report. I opened a PR to fix it.
