### ISSUE TITLE
Issue with "ServiceWorkerRegistration": description for updateViaCache is missing

### ISSUE THREAD

**Issue by y-a-v-a** [mdn/content#6729]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration

#### What information was incorrect, unhelpful, or incomplete?
The property `updateViaCache` is only available in the compatability table, but is nowhere described.

#### Specific section or headline?
`updateViaCache`

#### What did you expect to see?
An explaination on the property updateViaCache

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/serviceworkerregistration`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/serviceworkerregistration/index.html
* Last commit: https://github.com/mdn/content/commit/642d6eb7feb73e17cfc1ef61d3d09c2d200e65ca
* Document last modified: 2021-06-17T03:52:55.000Z

</details>

**Comment by Blakelist7** [comment]
@sideshowbarker I'd like to work on this.
Please assign this to me.

**Comment by hamishwillee** [comment]
I've assigned it to you. FWIW No need to pick a specific person to assign to you since anyone who has the "rights" will be more than pleased to do so :-)
