### ISSUE TITLE
Issue with "Autoplay guide for media and Web Audio APIs": Documented default value of media.autoplay.block-webaudio not the same as actual default value

### ISSUE THREAD

**Issue by akwala** [mdn/content#6736]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide

#### What information was incorrect, unhelpful, or incomplete?
Doc says default value of `media.autoplay.block-webaudio` is `true`:
![image](https://user-images.githubusercontent.com/1786/125115550-7a475980-e0b9-11eb-8d87-7d800b9aa4d3.png)
In Firefox 89.0.2, the default value of `media.autoplay.block-webaudio` is `false`:
![image](https://user-images.githubusercontent.com/1786/125116046-1ffac880-e0ba-11eb-878c-ac29c774eb9a.png)

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide#firefox

#### What did you expect to see?
The actual default value of the preference in Firefox and its documented default value should be the same. I'm not sure which of these is erroneous.

#### Did you test this? If so, how?
See screenshots above.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/media/autoplay_guide`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/media/autoplay_guide/index.html
* Last commit: https://github.com/mdn/content/commit/098cee88a80dcc276b8bc0bf7cccae4c10fe0cd9
* Document last modified: 2021-06-14T01:37:48.000Z

</details>

**Comment by teoli2003** [comment]
By reading [Mozilla's bug 1511117](https://bugzilla.mozilla.org/show_bug.cgi?id=1511117) and [bug 1511120](https://bugzilla.mozilla.org/show_bug.cgi?id=1511120), I understand that `media.autoplay.block-webaudio` is set to `true` only in Nightly, not in other versions of the Firefox browser.

@padenot, maybe you can help us here, and comfirm or infirm this?

**Comment by padenot** [comment]
> @padenot, maybe you can help us here, and confirm or infirm this?

This is correct, this is only set to `true` in Nightly for now.

**Comment by teoli2003** [comment]
Thanks, Paul.
