### ISSUE TITLE
Issue with "Arrow function expressions": (short summary here please)

### ISSUE THREAD

**Issue by manngo** [mdn/content#6741]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

#### What information was incorrect, unhelpful, or incomplete?

The article refers to the use of __brackets__. That is misleading, as __brackets__ normally means the `[ … ]` symbols, AKA  the redundant __square brackets__.

The more common term for the `{ … }` symbols is __braces__, sometimes redundantly called __curly brackets__.

The distinction is important, since JavaScript has distinct roles for all three grouping symbols, __parentheses_ `( … )`, __brackets__ `[ … ]` and __braces__ `{ … }`, and mixing them up will confuse readers.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/functions/arrow_functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/functions/arrow_functions/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by teoli2003** [comment]
Thanks a lot!

You are right. I've opened a PR to fix it.
