### ISSUE TITLE
Issue with "chrome_settings_overrides": there are better descriptions of how the fields are required in the chrome source

### ISSUE THREAD

**Issue by AskAlice** [mdn/content#6744]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_settings_overrides

#### What information was incorrect, unhelpful, or incomplete?
If you take a look at https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/chrome/common/extensions/api/manifest_types.json

#### Specific section or headline?
[Syntax](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_settings_overrides#syntax)

#### What did you expect to see?
things like how keyword (among others) is required unless you provide a prepopulated id

#### Did you test this? If so, how?
no

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_settings_overrides
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides/index.html
* Last commit: https://github.com/mdn/content/commit/d716c648272ecdedf3eb957f1e37c500b58eaf0d
* Document last modified: 2021-05-31T17:42:48.000Z

</details>

**Comment by schalkneethling** [comment]
Hey @AskAlice, thank you for opening the issue. If you look at the [page as it is now](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_settings_overrides#syntax) and compare it to the JSON referenced in the issue description, does the issue raised still exist? Thanks!

**Comment by sideshowbarker** [comment]
Closing for lack of response to https://github.com/mdn/content/issues/6744#issuecomment-1150464121
