### ISSUE TITLE
Issue with "Window.requestAnimationFrame()": Example does not demonstrate description in text

### ISSUE THREAD

**Issue by tedsecretsource** [mdn/content#6746]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

#### What information was incorrect, unhelpful, or incomplete?
The description of this function says:

> (in the code example below we only animate the frame when the timestamp changes, i.e. on the first callback)

and 

> Be sure to always use the first argument (or some other method for getting the current time) to calculate how much the animation will progress in a frame, otherwise the animation will run faster on high refresh rate screens. Check the example below for a way to do this.

However, in the actual code, I don't see any test around the line that animates the object.

#### Specific section or headline?

`element.style.transform = 'translateX(' + Math.min(0.1 * elapsed, 200) + 'px)';`

#### What did you expect to see?
```javascript
const element = document.getElementById('some-element-you-want-to-animate');
let start, previousTimeStamp;

function step(timestamp) {
  if (start === undefined)
    start = timestamp;
  const elapsed = timestamp - start;
  
  if( previousTimeStamp !== timestamp ) {
    // `Math.min()` is used here to make sure that the element stops at exactly 200px.
    element.style.transform = 'translateX(' + Math.min(0.1 * elapsed, 200) + 'px)';
  }

  if (elapsed < 2000) { // Stop the animation after 2 seconds
    previousTimeStamp = timestamp
    window.requestAnimationFrame(step);
  }
}

window.requestAnimationFrame(step);
```

#### Did you test this? If so, how?

https://codepen.io/tedmasterweb/pen/dyWpMev

I have tested that the code provided works. I have not tested it against different refresh rates and depend on the documentation to be correct in this regard.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/requestanimationframe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/requestanimationframe/index.html
* Last commit: https://github.com/mdn/content/commit/64b0057f7238be9ad7a6f2f522efd8f5f7753095
* Document last modified: 2021-06-17T09:07:21.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. I reviewed and tested the code and then opened https://github.com/mdn/content/pull/6809 with patch.

**Comment by tedsecretsource** [comment]
Sorry I couldn't think of a better name for this issue!

**Comment by tedsecretsource** [comment]
Shall I close this now??

**Comment by teoli2003** [comment]
This will be closed when the PR will merge.

Has anybody tested the original code for me: it works for me and I don't see why it shouldn't work. It is not adding a fixed amount of "transformation", it is recalculating it.

Am I missing something?

**Comment by tedsecretsource** [comment]
Honestly, this is all a bit outside my area of expertise so I'm driving with one eye here. To be clear, the issue for me was/is the description of the example code suggests that if multiple frames are queued with the same timestamp, only the first will be processed. However, I'm not seeing any test for that in the example, which is why I submitted this change request.

As I re-read the original code and your comment (@teoli2003), I suppose you could say that the transform is happening in exactly the same way and thus not transforming? Regardless, seems like an overly complex example of skipping queued frames when the timestamp is the same.
