### ISSUE TITLE
Issue with "Array.prototype.reduce()": (short summary here please)

### ISSUE THREAD

**Issue by Emmybest1** [mdn/content#6747]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

#### What information was incorrect, unhelpful, or incomplete?
All information was correct but I want to contribute on how to remove duplicate items in an array

#### Specific section or headline?
Remove duplicate items in an array

#### What did you expect to see?
I want to add that : 
we can use the ES2016 spread operator to spread keyless set-object to an iterable unique array

**Code sample:**
    
    let myArray = ['a', 'b', 'a', 'b', 'c', 'e', 'e', 'c', 'd', 'd', 'd', 'd'];
    const uniqueArrays = [...new Set(myArray)];
    console.log(uniqueArrays);

#### Did you test this? If so, how?
Yes I tested this by passing in an array with duplicate items into the Set constructor

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/reduce`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/reduce/index.html
* Last commit: https://github.com/mdn/content/commit/761ba0efe8230cec103437c215a79a2e6d2bb5f2
* Document last modified: 2021-06-15T08:30:35.000Z

</details>

**Comment by Elchi3** [comment]
There is already a note that points to the reader to use a `Set` object: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#remove_duplicate_items_in_an_array

Is that not sufficient enough?

**Comment by himanshugarg** [comment]
The note in the section cited in https://github.com/mdn/content/issues/6747#issuecomment-878187114 serves the same purpose as requested by OP.
