### ISSUE TITLE
Issue with "HTML text fundamentals": (term clarification)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6753]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals

#### What information was incorrect, unhelpful, or incomplete?
One of HTML's main jobs is to give text structure and meaning (also known as semantics) so that a browser can display it correctly.

#### Specific section or headline?
HTML text fundamentals

#### What did you expect to see?
Does the term **semantics** really denote the _structure_ of a text? Outside of coding, the term normally used for textual structure is **syntax**.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/html_text_fundamentals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/html_text_fundamentals/index.html
* Last commit: https://github.com/mdn/content/commit/75c1271189903b4d96433a34a8174175dd089ef2
* Document last modified: 2021-04-28T14:08:28.000Z

</details>

**Comment by hamishwillee** [comment]
No, but semantics does related to the meaning of text. I'm happy with this, but will of course we will consider a PR that improves on it.
