### ISSUE TITLE
Issue with "Functions": replace all occurrences of "(i.e." with "(i.e.,"

### ISSUE THREAD

**Issue by abergquist** [mdn/content#6754]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions

#### What information was incorrect, unhelpful, or incomplete?

Every occurrence of "(i.e." needs to be replaced with "(i.e.," in the places listed in the next question.

#### Specific section or headline?

.
.
.
If you pass an object (i.e. a non-primitive value, such as Array or a user-defined object) as a parameter and the function changes the object's properties, that change is visible outside the function, as shown in the following example:
.
.
.
Note: This works only when defining the function using the above syntax (i.e. function funcName(){}).
.
.
.
1. B forms a closure including A (i.e. B can access A's arguments and variables).
.
.
.

#### What did you expect to see?

.
.
.
If you pass an object (i.e., a non-primitive value, such as Array or a user-defined object) as a parameter and the function changes the object's properties, that change is visible outside the function, as shown in the following example:
.
.
.
Note: This works only when defining the function using the above syntax (i.e., function funcName(){}).
.
.
.
1. B forms a closure including A (i.e., B can access A's arguments and variables).
.
.
.

#### Did you test this? If so, how?

Not applicable.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/functions/index.html
* Last commit: https://github.com/mdn/content/commit/3fbd2466d85fe7bf14ac849ff897f9684f8e426c
* Document last modified: 2021-07-08T07:17:50.000Z

</details>

**Comment by teoli2003** [comment]
American usage is with a comma; British one without. We use American usage (spelling, …) on MDN.

Note the the Chicago Manual of Style also mandates that _e.g._ should be **confined to parentheses and notes**, which is the case here.

**Comment by abergquist** [comment]
Thanks, I wanted to confirm; I was talking about "i.e." but you mention "e.g.".  In either case, though, they should both have a comma after them so isn't this still an issue?  Thanks again.

**Comment by teoli2003** [comment]
@abergquist, I fixed _i.e._. My mistake for speaking a about _e.g._ in the previous comment.

**Comment by abergquist** [comment]
No problem; thanks, Jean-Yves Perrier!
