### ISSUE TITLE
Issue with "Type, class, and ID selectors": (confusing phrasing)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6756]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors

#### What information was incorrect, unhelpful, or incomplete?
You can apply multiple classes to an element and target them individually, or only select the element when all of the classes in the selector are present.

#### Specific section or headline?
Target an element if it has more than one class applied

#### What did you expect to see?
What is the subject of "_only select the element when all of the classes in the selector are present._"? Is it **you**? That renders as "_you can only select the element when all of the classes in the selector are present._" But I don't understand this sentence. Is the verb supposed to be different than **select** or **can**?

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors/type_class_and_id_selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/type_class_and_id_selectors/index.html
* Last commit: https://github.com/mdn/content/commit/b0a768368d7ae61d095ab64f0dd210b3b4973ec0
* Document last modified: 2021-04-19T21:14:06.000Z

</details>

**Comment by Anurella** [comment]
@ConsciousClay 

<em> or only select the element when all of the classes in the selector are present </em> implies that the element will have a style applied if it contains the classes of that selector. that means the selector contains more than one class.

Example 

<code> .note.care { color: purple } </code> will only be applied to an element that has both note and care as classes.

**Comment by ConsciousClay** [comment]
@Anurella Thanks for the reply. I understand what the intended meaning of the passage is. But it sounds odd the way it's phrased. The first clause uses the auxiliary verb "**can**". Either this verb is implied in the second clause or it's not. If it's not, then the clause says "**You only select the element when...**" and this isn't right; this is not the intended meaning. Contrariwise, with the auxiliary "**can**" we have, "**You can only select the element when..**." and this isn't right either.

The two clauses should be rewritten. Or at the very least, the second clause should be.

Besides that, it also sounds odd to speak of selecting with selectors only if they satisfy a condition, i.e., having all the wanted classes. It's like saying, "**I'm only going to hammer with a hammer if the hammer can hammer nails.**" But that's a truism. There's no reason to say that.

**Comment by rachelandrew** [comment]
Closing as the content is correct here.
