### ISSUE TITLE
Issue with "Delete Author form": (short summary here please)

### ISSUE THREAD

**Issue by camiloa17** [mdn/content#6759]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Delete_author_form

#### What information was incorrect, unhelpful, or incomplete?
There is an issue with the lifespan virtual schema, if there is no date of death it will throw an error.
It comes from here.
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#author_model

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Delete_author_form#view
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#author_model

#### What did you expect to see?
There is an issue with the lifespan virtual schema, if there is no date of death it will throw an error.

#### Did you test this? If so, how?
Yes, I created an Author without a date of birth.

this is the error I got
TypeError: C:\Users\camil\Programming\web-technology\lab8\views\author_delete.pug:5
    3| block content
    4|   h1 #{title}: #{author.name}
  > 5|   p= author.lifespan
    6| 
    7|   if author_books.length
    8| 

Cannot read property 'getYear' of undefined

What I did is changed the lifespan virtual like this to at least give me the age of the author.
But you can decide how you want to do it.
AuthorSchema
.virtual('lifespan')
.get(function () {
  const today = new Date().getFullYear();
  return this.date_of_death? (this.date_of_death.getFullYear() - this.date_of_birth.getFullYear()).toString():(today - this.date_of_birth.getFullYear()).toString();
});

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/delete_author_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Delete_author_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/delete_author_form/index.html
* Last commit: https://github.com/mdn/content/commit/3f0d70a833121be094f90194c23b3acfb19539fa
* Document last modified: 2021-01-29T00:55:21.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you. You're correct. This was already fixed in the demo version, so I just copied that implementation.
