### ISSUE TITLE
Issue with "Beginning our Angular todo list app": (Failure in compiling)

### ISSUE THREAD

**Issue by forgerlil** [mdn/content#6763]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_todo_list_beginning

#### What information was incorrect, unhelpful, or incomplete?
Up until said topic, the tutorial was working as intended. 
As soon as I added the <code>addItem(description)</code> method at the very end of the <code>AppComponent</code> class, VS gave me a "Parameter 'description' implicitly has an 'any' type." warning (even though <code>item.ts</code> file sets the <code>description</code> property as a string). Angular immediately failed to compile the entirety of the app even before any of the HTML on <code>app.component.html</code> was modified.
All the code in the "Add items to the list" section has been copied and pasted to avoid syntax hiccups, and placed in the relevant files (<code>app.component.ts</code> and <code>app.component.html</code>) as directed by the tutorial.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_todo_list_beginning#add_items_to_the_list

#### What did you expect to see?
A label for an input field, an input field and an "Add" button. They were to add a new item on the todo list with the inputs' text content upon clicking the button or pressing enter while focusing the input field.

Instead, Angular fails to compile the code and presents a black screen with a failure statement.

#### Did you test this? If so, how?
As directed by VS, I changed <code>addItem(description)</code> to <code>addItem(description: string)</code>, which then worked, even though it is not DRY (<code>description</code> already being declared as a string in <code>item.ts</code>).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_todo_list_beginning
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/angular_todo_list_beginning/index.html
* Last commit: https://github.com/mdn/content/commit/11857b7d4b212319b2c9c998a85a71ca4e71f8ec
* Document last modified: 2021-04-09T13:58:05.000Z

</details>

**Comment by zacnomore** [comment]
I was able to reproduce this as well by following the articles directions. The default tsconfig from the ng cli has strict mode on which will get angry about implicit any. 

Submitting a PR to change the method signature
