### ISSUE TITLE
Issue with "Attribute selectors": (incomplete information)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6773]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors

#### What information was incorrect, unhelpful, or incomplete?
Matches elements with an _attr_ attribute (whose name is the value in square brackets).

#### Specific section or headline?
Presence and value selectors

#### What did you expect to see?
What is an **_attr_ attribute**? Is this a special kind of attribute? It seems nothing is gained by calling it an **attr attribute** rather than merely an **attribute**. Why not just say "attribute", as in, "Matches elements with an attribute whose name is located in square brackets."

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors/attribute_selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/attribute_selectors/index.html
* Last commit: https://github.com/mdn/content/commit/6eb0faf81c9fd235e59ec136fea5aaf1ed43b47a
* Document last modified: 2021-01-02T19:24:06.000Z

</details>

**Comment by hamishwillee** [comment]
`attr` is not special, but it is a common abbreviation. Upshot, I see no reason why it could not be "attribute" - but nor do I think anyone would be confused by this and I personally would not bother fixing it. If you feel the need, then it should be done on every example in MDN.

**Comment by ConsciousClay** [comment]
Yes, I had thought of its wide use on MDN last night and decided to remove this issue. I suppose I click that **Close** button on the bottom?

**Comment by hamishwillee** [comment]
Yes, that works :-).
