### ISSUE TITLE
Issue with "Attribute selectors": (short summary here please)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6774]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors

#### What information was incorrect, unhelpful, or incomplete?
By using **li[class]** we can match any selector with a class attribute.

#### Specific section or headline?
Presence and value selectors

#### What did you expect to see?
But **li[class]** doesn't match _any_ selector. It is specifically an **li element selector**.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/selectors/attribute_selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/selectors/attribute_selectors/index.html
* Last commit: https://github.com/mdn/content/commit/6eb0faf81c9fd235e59ec136fea5aaf1ed43b47a
* Document last modified: 2021-01-02T19:24:06.000Z

</details>

**Comment by NegiAkash890** [comment]
Hi @ConsciousClay , I think that the statement is correct as it simply conveys that it only selects `li` elements which have class attribute else it's simply ignored

`
By using li[class] we can match any selector with a class attribute. This matches all of the list items except the first one.
`

as  quoted on the page

or a solution would be to improve the current one with 

`By using li[class] we can match any list item with a class attribute. This matches all of the list items except the first one.`

**Comment by teoli2003** [comment]
_We can match any selector_ sounds very odd to me.

I understand that a selector _matches_ elements or _represents_ elements that _match_ a condition.

For example, in the [Selector Level 4 specificatiion](https://drafts.csswg.org/selectors-4/), we have clauses like:

> Selectors are patterns that match against elements in a tree

or

> A selector is a boolean predicate that takes an element in a tree structure and tests whether the element matches the selector or not.

or

> his structure can be used as a condition (e.g. in a CSS rule) that determines which elements a selector matches in the document tree

or the verb _to represent_ is used like in this table:
<img width="838" alt="Screenshot 2021-07-12 at 07 58 46" src="https://user-images.githubusercontent.com/1466293/125238147-199d6400-e2e7-11eb-878f-d1dc5dbcb573.png">

But it is never the web dev (_we_) that match a selector. So I would get rid of that.

**Comment by ConsciousClay** [comment]
> We can match any selector sounds very odd to me.
> I understand that a selector matches elements or represents elements that match a condition.

Compare:
a) Drills drill holes, but we also drill holes with drills.
b) A hammer's function is to hammer nails. But we also hammer nails by using hammers.

I'm sure there's a term for this phenomenon, probably some cognate of anthropocentrism, but I can't think of it at the moment.

<hr>

> or a solution would be to improve the current one with:
> By using li[class] we can match any list item with a class attribute. This matches all of the list items except the first one.

This is clearer. I still don't agree that the original is correct. The original is only made clear by its subsequent sentence. But having to look at later sentences to judge the meaning of previous ones is bad form.
