### ISSUE TITLE
Issue with "HTMLElement: change event": "change" event does not include de-selection

### ISSUE THREAD

**Issue by dbooth-boston** [mdn/content#6777]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event

#### What information was incorrect, unhelpful, or incomplete?
The documentation should explicitly explain that the "change" event is NOT fired for a radio button or single-select option that changes from selected to de-selected (because a different radio button or option was selected), even though its selection status obviously changed.

The problem is discussed in this StackOverflow post:
https://stackoverflow.com/questions/8838648/onchange-event-handler-for-radio-button-input-type-radio-doesnt-work-as-one

It would be helpful if this were explicitly discussed, with suggested workarounds.

#### Specific section or headline?
Multiple sections are affected.

#### What did you expect to see?
Because the event is called "change", I would have expected it to be fired when the radio button or option is EITHER selected or de-selected.  That's what the word "change" normally means.

#### Did you test this? If so, how?
Yes, with this code: https://jsfiddle.net/xbgpovqm/

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlelement/change_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/change_event/index.html
* Last commit: https://github.com/mdn/content/commit/acbf2f3051df9a8443a6479d203878e780054c7e
* Document last modified: 2021-07-06T08:34:48.000Z

</details>

**Comment by sideshowbarker** [comment]
A pull request with a patch for this would be welcome

**Comment by postmeback** [comment]
Can i contribute here ?

**Comment by octo-0rg** [comment]
this-is-GOD

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/11614
