### ISSUE TITLE
Issue with "<textarea>": (default display value is NOT block)

### ISSUE THREAD

**Issue by Prid13** [mdn/content#6792]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

#### What information was incorrect, unhelpful, or incomplete?
The page says that the default `display` value for `<textarea>` is `block`, while [most browsers](https://stackoverflow.com/questions/21614938/html-element-which-defaults-to-displayinline-block/21636061) have its default value as either `inline` or `inline-block`.

#### Specific section or headline?
[Styling with CSS](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#styling_with_css)

> <textarea> is a replaced element — it has intrinsic dimensions, like a raster image. **By default, its display value is block.**

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/textarea`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/textarea/index.html
* Last commit: https://github.com/mdn/content/commit/8d28de329fc4f723ad4362f0f703e46c4fa9e32d
* Document last modified: 2021-06-02T17:52:41.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/6842 with a fix.

**Comment by Prid13** [comment]
Thanks for the quick fix 😇👌

Context: I was running into issues with textarea's height when I finally realized that it was because the element's default display value _wasn't_ set to `block` as opposed to what MDN's docs said. That discovery finally solved my issue and prevented me from losing my sanity, and the only natural next step was to avert other's from getting caught in the same trap ;)
