### ISSUE TITLE
Should we write about old features that any current browsers does (or doesn't) implement?

### ISSUE THREAD

**Issue by NagayamaToshiaki** [mdn/content#6804]
Since Japanese is my mother tongue, English translation is not accurate. So, I put Japanese claims after it.

For example, "useCapture (of the addEventListener method) has not always been optional", which is false after IE9. These kinds of information are just the source of the confusion to most of the new comers, which only maintain for current browsers.
I hope you update the articles to up to date (at least for IE11) or write those deprecated informations at the end of the article they were on as a sidenote (for historic interest).

例えばaddeventListenerメソッドの「useCapture はどんなブラウザーでもオプションになっているわけではありません。」という記述はIE9以降は当てはまりません。このような情報は現行ブラウザの未対応している新参者にとっては混乱のもとでしかありません。
現行の（少なくともIE11まで対応の）情報だけを載せるか、古い情報は（歴史的興味として）記事末尾に参考情報として載せたほうが良いのではないでしょうか。

**Comment by wbamberg** [comment]
I agree with you, we should remove this note and should not in general document features of obsolete browsers.

The mdn/browser-compat-data project agreed a policy where (I think) if a feature had not been supported by any browsersfor >2 years, we should delete any docs for it. mdn/content has been tending to follow this policy as well.

I can never find where this policy is documented though.

**Comment by teoli2003** [comment]
browser-compat-data documents this policy [there](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features).

Reviewers of mdn/content applies the same, as far as I noticed when deleting content here. (But I don't think this is documented anywhere)
