### ISSUE TITLE
Issue with "Properly configuring server MIME types": No PHP error detection

### ISSUE THREAD

**Issue by David263** [mdn/content#6808]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Configuring_server_MIME_types

#### What information was incorrect, unhelpful, or incomplete?
Fails to describe the fact that setting an HTTP header is not properly error-checked by PHP, Apache, Firefox, Chrome, or Web Developer Tools.

#### Specific section or headline?
Not sure.

#### What did you expect to see?
Should point out that the PHP code `header('text/javascript');` will not set the MIME type of the response text as a developer might expect. It is required for the user to know that the proper code is `header('Content-type: text/javascript');`.

#### Did you test this? If so, how?
Wrote simple test case and struggled with it until I finally figured it out. It should be documented clearly.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/configuring_server_mime_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Configuring_server_MIME_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/configuring_server_mime_types/index.html
* Last commit: https://github.com/mdn/content/commit/41be28f3684df67a63c3c88e0143997de2e337e6
* Document last modified: 2021-02-09T18:26:50.000Z

</details>

**Comment by sideshowbarker** [comment]
`header('text/javascript')` does actually set a response header, right? It sets a response header with the literal header name `text/javascript`. There’s really not any way for the PHP interpreter to detect that what you actually wanted to set instead was a header named `Content-type` with the value `text/javascript`.

Similarly, it’s not clear to me what more we could say about this in MDN.

Do you have any suggestions? Something like *“Don’t try set a value by itself as a response header; instead you need to specify a header name, followed by a colon and space, followed by a value”*.

Or what?

**Comment by David263** [comment]
Yes, you are correct. My suggestion would be something like the following:

"One might think that the code `header('application/pdf');` might work to declare some data to the browser as a PDF file, but actually the full statement `header('Content-Type: application/pdf');` is necessary, and there is no error checking for this type of error."

Such a specific warning in this MDN page would have saved me many hours of debugging. It might even prompt some systems programmer to add an error check for this case, which is certainly doable.

**Comment by sideshowbarker** [comment]
OK, thanks — I’ve opened https://github.com/mdn/content/pull/6881 with a fix.
