### ISSUE TITLE
Issue with "Componentizing our React app": …

### ISSUE THREAD

**Issue by stonegrape** [mdn/content#682]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components

#### What information was incorrect, unhelpful, or incomplete?
执行示例代码，出错

#### Specific section or headline?
The Form
The FilterButton

#### What did you expect to see?
delete this code:
export default Form;
export defualt FilterButton;

#### Did you test this? If so, how?
yes, I test it.
SyntaxError: E:\create-react-app\moz-todo-react\src\components\Form.js: Only one default export allowed per module. (25:0)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.html
* Report started: 2020-12-28T13:34:23.565Z

</details>

**Comment by Coder-Manthan** [comment]
I think you should make a new file called `FilterButton.js` in `components` folder
And the export will work

**Comment by kevin51jiang** [comment]
Yeah I think @Coder-Manthan is right, there doesn't seem to be any issue with the docs.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/682#issuecomment-1112863608
