### ISSUE TITLE
Issue with "image-orientation": is the whole thing deprecated?

### ISSUE THREAD

**Issue by PhilterPaper** [mdn/content#6820]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation

#### What information was incorrect, unhelpful, or incomplete?

image-orientation has a big warning at the top that it is _deprecated_, but no replacement is provided for "from-image" value. This is important for dealing with phone camera images. Is this warning **incorrect** in that it only applies to the _flip_ and _rotation_ values, and "none" and "from-image" are actually still supported?

#### What did you expect to see?

If "from-image" (and "none") is still valid, the deprecation notice at the top should be modified to clarify that only _some_ values an flags are deprecated, and that others are _still_ valid.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/image-orientation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/image-orientation/index.html
* Last commit: https://github.com/mdn/content/commit/024f682d8c77ec9951639fa51a408eaf6f74b950
* Document last modified: 2021-06-23T11:56:35.000Z

</details>

**Comment by hamishwillee** [comment]
@PhilterPaper The doc does say "with the possible exception of from-image". I would normally assume you're right based on the compatibility table. 

@rachelandrew What do you think? I suspect that the from-image is probably useful - especially now FF90 respects EXIF data for image size and rotation.

**Comment by rachelandrew** [comment]
This property is no longer deprecated in the updated spec, and has been through some changes. I'll make some updates to the page.

**Comment by rachelandrew** [comment]
I think BCD is correct. The entire property is no longer deprecated, but in the spec there is a note that values other than none and from-image are deprecated. I'm about to make a PR that removes the big deprecated header and adds a note.

**Comment by PhilterPaper** [comment]
Thank you!
