### ISSUE TITLE
Issue with "Basic etiquette for open source projects": (incongruous conditional relation)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6823]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Open_source_etiquette

#### What information was incorrect, unhelpful, or incomplete?
....if you are spending your time working on a project for free, then it is reasonable to expect to get something out of it, and in fact you are far more likely to stick around for longer and contribute more productively to the project.

#### Specific section or headline?
Think about why you are contributing to an OSP

#### What did you expect to see?
The conditional equates to: "If you are spending your time working on a project for free, you are far more likely to stick around for longer and contribute more productively to the project."

I don't see the connection there.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/open_source_etiquette`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Open_source_etiquette
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/open_source_etiquette/index.html
* Last commit: https://github.com/mdn/content/commit/8af29e11c2342d5b044f76cd1907d6c5a2530c65
* Document last modified: 2021-03-25T00:50:48.000Z

</details>

**Comment by hamishwillee** [comment]
The current wording is

> Some of these reasons are self-serving, but that's OK too — if you are spending your time working on a project for free, then it is reasonable to expect to get something out of it, and in fact you are far more likely to stick around for longer and contribute more productively to the project. In addition, having a good set of reasons for contributing clear before you start will help make it easier to decide what tasks to start on.

This equates to:

>Some of these reasons are self-serving, but that's OK too - in fact you are far more likely to stick around for longer and contribute more productively to the project

I think this is OK, but generally if someone finds something unclear then even if it is technically correct there is room for improvement. So happy for you to propose a solution. Perhaps a full stop before ", and in fact you" and some extra words.

**Comment by ConsciousClay** [comment]
I'm not sure I understand. I wasn't suggesting an answer, but merely filing an issue.

The issue is that this idea:
**in fact you are far more likely to stick around for longer and contribute more productively to the project**

does not follow from this idea:
**Some of these reasons are self-serving, but that's OK too**

What's the connection?

**Comment by hamishwillee** [comment]
It says that if you're contributing for selfish reasons then you're more likely to stick around. That is of course arguable, but is quite likely true, and in any case non-harmful.

I don't see this as an issue. Assigned to @sideshowbarker who may feel differently.

**Comment by ConsciousClay** [comment]
Yes, I understand the connection now. But this clause is incomplete:

"**in fact you are far more likely to stick around for longer and contribute more productively to the project**"

**More** is a comparative adjective. What's the condition being compared? How about:

"**in fact, you are more likely to stick around and contribute productively to the project if for selfish reasons.**"

1) **far** is unnecessary
2) **for longer** is a redundancy of **stick around**
3) Standard usage dictates a comma after **in fact**
4) **more productively** is supfluous. The longer you stay, the more productive you'll be. ".. **and contribute productively**" _tout court_ is fine.
5) **if for selfish reasons**. - Some such reference to selfish reasons is required here to satisfy the condition inherent in "_morehood_".

**Comment by sideshowbarker** [comment]
Maybe a good way to resolve with this would be with a PR that proposes concrete changes.

To produce such a PR, I don’t think it’d be necessary to try to identify the intent of the existing language.

I say that because I personally can’t confidently say what the intent was. But it doesn’t matter — we don’t need to preserve the original intent. Instead it’d be sufficient if you could propose some similar statement with wording that you don’t think will be problematic in the way you find the current wording to be.

**Comment by hamishwillee** [comment]
You may well be "technically correct", but I see this as understandable. Feel free to create a PR and someone can argue the detail there

**Comment by hamishwillee** [comment]
@sideshowbarker Ha ha, crossover!

**Comment by sideshowbarker** [comment]
> @sideshowbarker Ha ha, crossover!

Nexus in the time stream! Watch your back for TVA to glitch in
