### ISSUE TITLE
Issue with "Basic etiquette for open source projects": (obscure and ungrammatical phrasing)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6828]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Open_source_etiquette

#### What information was incorrect, unhelpful, or incomplete?
The one ask here is

#### Specific section or headline?
Read the manual

#### What did you expect to see?
The wording doesn't make sense.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/open_source_etiquette`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Open_source_etiquette
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/open_source_etiquette/index.html
* Last commit: https://github.com/mdn/content/commit/8af29e11c2342d5b044f76cd1907d6c5a2530c65
* Document last modified: 2021-03-25T00:50:48.000Z

</details>

**Comment by hamishwillee** [comment]
Yes, this is "common colloquial English" :-). It means "Our one request here". I think it should be removed as unnecessary - so start with "Don't ...

Would you have time to make that change @ConsciousClay (or what you think is best if you have another suggestion?)

**Comment by ConsciousClay** [comment]
Oh, I get it. Never heard that expression before.

**Comment by hamishwillee** [comment]
> Should I close the issue now?

Github has some magic to auto close issues when an associated PR is merged. This is good because it adds a link to the issue and makes sure that the actual problem reported gets addressed (without you having to think about the issue again after creating the PR). So in the description of your PR can you put, on a new line, the following text:

Fixes #6828

**Comment by ConsciousClay** [comment]
How's [this](https://github.com/mdn/content/pull/6834)?

![image](https://user-images.githubusercontent.com/51193876/125377943-b50ff280-e342-11eb-8899-00c153c2d909.png)

**Comment by hamishwillee** [comment]
Perfect. Note above that there is now a link to the PR in _this_ issue, and that it has been auto closed by my merging your PR :-). 

Thanks very much!
