### ISSUE TITLE
Issue with "Proxy": broken link

### ISSUE THREAD

**Issue by wenfangdu** [mdn/content#6844]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

#### What information was incorrect, unhelpful, or incomplete?

> [the "little framework" published on the `document.cookie` page](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie/Simple_document.cookie_framework)

This link is broken.

#### Specific section or headline?

[A complete traps list example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#a_complete_traps_list_example)

#### What did you expect to see?

Can be successfully redirected.

#### Did you test this? If so, how?

Yes. Click.

<details>
<summary>MDN Content page report details</summary>

- Folder: `en-us/web/javascript/reference/global_objects/proxy`
- MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy
- GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/proxy/index.html
- Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
- Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/6846 with a fix.
