### ISSUE TITLE
Issue with "JavaScript guidelines": (short summary here please)

### ISSUE THREAD

**Issue by amiteshhh** [mdn/content#6847]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript

#### What information was incorrect, unhelpful, or incomplete?
Note for naming convention exception duplicated in naming convention for Function

#### Specific section or headline?
Function naming : https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript#function_naming

#### What did you expect to see?
We shouls not see `The only place where it is OK to not use human-readable semantic names is where a very common recognized convention exists, such as using i, j, etc. for loop iterators.` 

as its already mentioned in the __Variable naming__ section.

#### Did you test this? If so, how?
NA

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/guidelines/code_guidelines/javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/code_guidelines/javascript/index.html
* Last commit: https://github.com/mdn/content/commit/d57ebf115598c2ee7892b41e28cf98493cb579ee
* Document last modified: 2021-07-12T08:59:12.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6848 with a fix.
