### ISSUE TITLE
Issue with "File System Access API": (simplicity  ==  genius)

### ISSUE THREAD

**Issue by PageNotes** [mdn/content#6868]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API

#### What information was incorrect, unhelpful, or incomplete?
I'm grateful for the effort to provide a filehandling interface for JavaScript, we need it. But this is too complicated. Here's what we need:

1. Fix the input element so that it delivers file handles to JavaScript. None of this fakepath crap.
2. Retool fopen, fread, and fwrite to work with filehandles.

It's that simple. If people want to work with promises, more power to them, but promises are logically independent of file handling.

Thanks for listening.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/file_system_access_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/file_system_access_api/index.html
* Last commit: https://github.com/mdn/content/commit/c0e530c1dea1c62c011039c4467fd2c145779114
* Document last modified: 2021-04-16T13:52:42.000Z

</details>

**Comment by teoli2003** [comment]
Hi! 

Unfortunately, we are not the people creating the API, we are merely documenting them.

You may bring your ideas, comments to the w3c, or the specification editors, for example.

As we are not able to act on your comment, I'm closing this issue.

**Comment by PageNotes** [comment]
I'll take look at the community group draft report and contact the editor.

Thanks for pointing me in the right direction.
