### ISSUE TITLE
Issue with "GitHub for complete beginners": (confusing phrasing)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6875]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/GitHub_beginners

#### What information was incorrect, unhelpful, or incomplete?

> This is required for you to submit change requests to the main version of the repo...you can't submit changes directly to the main version of the repo.

#### Specific section or headline?
Forking and cloning

#### What did you expect to see?
We can or we can't submit changes to the main repo? I'm a bit confused.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/github_beginners`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/GitHub_beginners
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/github_beginners/index.html
* Last commit: https://github.com/mdn/content/commit/fcc38b5d1b88f3d841165467c4d789a90f8721b6
* Document last modified: 2021-03-25T16:41:51.000Z

</details>

**Comment by hamishwillee** [comment]
Good point. You cannot submit branches (with changes) directly to the main repo. In order to submit changes to the main repo you need to fork the main repo, push  changes to to your fork, and then create pull requests of your repo branch to the main repo.

If you can reword to make it say that more clearly, then please do.

**Comment by Pidut** [comment]
```

#- [ ] ****- ```_~~~~_

**Comment by Pidut** [comment]
```
```
```
```
```
> Please ![image](https://user-images.githubusercontent.com/87226746/129501937-1778393d-64fd-4386-b32b-c5d3c90fdbac.png)
- [ ] #`````
```
```
```
```

**Comment by Pidut** [comment]
Power mic and sound PUBG mobile [ ] #> @hamishwillee @hamishwillee
