### ISSUE TITLE
Intl.PluralRules() select with ordinal type returns cardinal numbers (one, two, three), not ordinal numbers (1st, 2nd, 3rd)

### ISSUE THREAD

**Issue by NathanQ** [mdn/content#6877]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules

#### What information was incorrect, unhelpful, or incomplete?
The example indicated ordinal number is supported, but the use case returns cardinal numbers. 

#### Specific section or headline?
The example under [Using Options](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules#using_options).

"The results can be customized using the options argument, which has one property called type which you can set to ordinal. This is useful to figure out the ordinal indicator, e.g. "1st", "2nd", "3rd", "4th", "42nd" and so forth."
  ```
  // example
  var pr = new Intl.PluralRules('en-US', { type: 'ordinal' });
  pr.select(0);
  // → 'other'
  pr.select(1);
  // → 'one'
  ...
  ```

#### What did you expect to see?
The documentation output is correct as JavaScript Intl.PluralRules ordinal type returns "one", "two", "three", but ordinal numbers are as indicated in the description, "ordinal indicator, e.g. "1st", "2nd", "3rd", "4th", "42nd" and so forth."" The documention should indicate the ordinal type does not return ordinal numbers.

#### Did you test this? If so, how?
Tested in Brave and the output is what is documented. 
```
intl = new Intl.PluralRules("en-US", {type: "ordinal"})
PluralRules {}
intl.select(1)
"one"
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/pluralrules/pluralrules`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/pluralrules/pluralrules/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6882 with a fix.
