### ISSUE TITLE
MathML Torture Test link not working

### ISSUE THREAD

**Issue by pedropaulosuzuki** [mdn/content#6878]
Hello!

Today, while trying to open the [MathML Torture Test](https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test) page, I found out that the [link](https://mdn.mozillademos.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test$samples/MathML_Torture_Test?revision=1506691) to the test was not actually working.

Instead, I was presented with the following warning:
```markdown
Legacy ($samples) URLs for live samples are now fully deprecated and will not work. If you have a document that relies on a URL with '$samples' in it, switch to using the EmbedLiveSample() macro instead.
```

I don't quite know that happened there, but it seems to be related to something related to the URL path being deprecated.

Thanks!

**Comment by sideshowbarker** [comment]
As noted at the top of https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test:

> This is an archived page. It's not actively maintained.

As such, any issues with it are out of scope for this repo, which is strictly for MDN content still being actively maintained.

So I’m going ahead and closing this issue.

But do note that you can still find copies of the actual tests and harness online in a number places. Probably best place to find them is https://codepen.io/rema/pen/YQyYoJ — but there’s also a version at https://www-archive.mozilla.org/projects/mathml/demo/texvsmml.xhtml

**Comment by scientificware** [comment]
@sideshowbarker So all links from MDN should be removed ?

**Comment by sideshowbarker** [comment]
> @sideshowbarker So all links from MDN should be removed ?

Yes

So a PR that removes them would be very much welcome — if you’re interested in writing up a PR. But otherwise, I’d be happy to write up a PR for it myself. Lemme know if you’d like me to do that.

**Comment by scientificware** [comment]
@sideshowbarker Thanks, writing up a PR would be great experience.
In [Web technology for developers > MathML > Examples](https://developer.mozilla.org/en-US/docs/Web/MathML/Examples).
Should I simply remove the link or replace it with torture test examples ?

**Comment by sideshowbarker** [comment]
>  In [Web technology for developers > MathML > Examples](https://developer.mozilla.org/en-US/docs/Web/MathML/Examples).
> Should I simply remove the link or replace it with torture test examples ?

I think simply removing the link would be an improvement. So I’d suggest we start with with a PR which does that. A later PR could be used for adding back some text examples.

**Comment by fred-wang** [comment]
I submitted https://github.com/mdn/content/pull/7766

**Comment by bkardell** [comment]
> As noted at the top of https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test:
> 
> > This is an archived page. It's not actively maintained.

I dont see that at all - I just get page not found?

**Comment by teoli2003** [comment]
@bkardell: The production Web site is usually built once a day; read this [section](https://github.com/mdn/content#when-will-my-change-show-up-on-the-production-mdn-site) for more information.

**Comment by sideshowbarker** [comment]
> > As noted at the top of [developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test](https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test):
> > > This is an archived page. It's not actively maintained.
> 
> I dont see that at all - I just get page not found?

I believe most or all of the archived pages were expunged from the production server.

The source for anything that’s been archived remains available in https://github.com/mdn/archived-content — but its existence there doesn’t mean it’s published any longer at the production site.
