### ISSUE TITLE
Use `console` instead of `Console`

### ISSUE THREAD

**Issue by teoli2003** [mdn/content#6883]
For `console` there is no debate, the actual name of the namespace is lowercase "console", not "Console". I'd like to see this changed in BCD and MDN :) It's just a little bit awkward as noted in https://console.spec.whatwg.org/#console-namespace the naming is for historical reasons, and will forever be an odd one out unless another mishap occurs.

_Originally posted by @foolip in https://github.com/mdn/content/issues/6856#issuecomment-879382153_

**Comment by foolip** [comment]
It looks like MDN is already pretty good on this point. There are a bunch of `{{domxref("Console")}` that will need lowercasing, however. Example here:
https://developer.mozilla.org/en-US/docs/Web/API/SharedWorkerGlobalScope#properties_inherited_from_workerglobalscope

**Comment by foolip** [comment]
Ah, and the URLs themselves need lowercasing.

**Comment by teoli2003** [comment]
Yep, nothing to big. On my radar (unless somebody else do it first)

**Comment by foolip** [comment]
I won't beat you to it, thanks for taking it on :)
