### ISSUE TITLE
firefox issue with Odysee

### ISSUE THREAD

**Issue by xlwyx** [mdn/content#6905]
There are a one problem with Firefox. There are users that record videos with ffmpeg and upload that videos to odysee; reality, I can't see the videos that recorded ffmpeg and  uploaded  on odysee. There're one way of view the odysee (odysee.com) videos over Firefox?  
Tanks...
My account:
yahoo: xx_xarehnass_x@yahoo.com
gmx: l_rewrite@gmx.com
My nyckname:
Lwy / Tuxito...
telegram: @testin' over GNU/linux

**Comment by teoli2003** [comment]
HI!

This looks like a support request about Firefox.

Unfotunately we can't help you: we are working only on the content of docs on MDN Web Docs. I think you should try to submit your problem to https://support.mozilla.org

I'm closing this issue.
