### ISSUE TITLE
There Is and what is the mapping between the Yari URL and the GitHub URL?

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#691]
### GitHub
https://github.com/mdn/content/blob/main/files/en-us/web/guide/html/editable_content/index.html

### Yari on developer.mozilla.org 

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content

Exists a Quick and documentable way to copy the production URL (#u-1), change something like the _origins_, _lowecase the path_, _append a index.html_ and then obtain the source URL (#u-2) to be mentioned in Issues for a help for the PR?

```
#u-1 https://github.com/mdn/content/blob/main/files/en-us/web/guide/html/editable_content/index.html
#u-2 https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content
```

Note: GitHub has several kind of urls (raw, branch, etc.. the best one).

**Comment by mattiapontonio** [comment]
https://github.com/mdn/content/issues/629

**Comment by Ryuno-Ki** [comment]
My understanding is this:

1. Take the path of an MDN URL
2. Lowercase it
3. Parse it like this: `/{locale}/docs/{filepath}`
4. Map it to `https://github.com/mdn/content/blob/main/files/{locale}/{filepath}/index.html`

**Comment by mattiapontonio** [comment]
```JavaScript
function f(str) {
	const url = new URL (str);
const arr = url.pathname.split('/');
arr.splice(1, 0, "mdn");
arr.splice(2, 0, "content");
arr.splice(3, 0, "blob");
arr.splice(4, 0, "main");
arr.splice(5, 0, "files");
arr.splice(7,1);
url.pathname = arr
.map(e=>e.toLowerCase())
.join("/");
url.host="github.com";
return url.toString();
};
console.assert(	f("https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content") == "https://github.com/mdn/content/blob/main/files/en-us/web/guide/html/editable_content"
);
```

**Comment by Ryuno-Ki** [comment]
```js
function f (str) {
  const url = new URL(str);
  const [locale, docs, ...rest] = url.pathname.split('/');
  const path = [
    'mdn',
    'content',
    'blob',
    'main',
    'files',
    locale,
    ...rest,
    'index.html'
  ]
  .map((part) => part.toLowerCase())
  .join('/');
  return `https://github.com/${path}`;
};
```

**Comment by mattiapontonio** [comment]
Se should run both f in a `Set` of tests 🤔🙂

**Comment by mattiapontonio** [comment]
> ```js
> function f (str) {
>   const url = new URL(str);
>   const [locale, docs, ...rest] = url.pathname.split('/');
>   const path = [
>     'mdn',
>     'content',
>     'blob',
>     'main',
>     'files',
>     locale,
>     ...rest,
>     'index.html'
>   ]
>   .map((part) => part.toLowerCase())
>   .join('/');
>   return `https://github.com/${path}`;
> };
> ```

- Knowing the `locale` Is the `locale` in this scope is not important.
- You names `doc` and `locale` because You want to move them but in reality the issue is about not _moving something_ but _removing and add something_ in this case.

**Comment by mattiapontonio** [comment]
Note to me

I have doubts whether to build the url inside the function or to verify it already built from the outside. Because I imagine that this object in general is built several times nice app so maybe it would be better to accept it from the outside and return a new one and test the `toString` or `href` of both.

**Comment by Ryuno-Ki** [comment]
> Your solution seems more flexible but I'm looking to a global pattern of exists...

Personally, I find `splice` harder to reason about. I only realised what you were up to once you changed the `host`.

**Comment by mattiapontonio** [comment]
still questionable
  
```JavaScript
function f(s) {
	const url = new URL(s);
const a = url.pathname.split('/');
url.host="github.com";
a.splice(1, 0, "mdn", "content", "blob", "main", "files");
a.splice(7,1);
url.pathname = a
.join("/")
.toLowerCase();
return url.toString();
};
console.assert(	f("https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content") == "https://github.com/mdn/content/blob/main/files/en-us/web/guide/html/editable_content"
);
```
