### ISSUE TITLE
Issue with "405 Method Not Allowed": Real World Example needed

### ISSUE THREAD

**Issue by iamshacky** [mdn/content#6917]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status/405`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/405/index.html
* Last commit: https://github.com/mdn/content/commit/f6f11d2a249520f01bad93d7c4a5e5cdf6ed914a
* Document last modified: 2021-02-19T19:33:30.000Z

</details>

**Comment by iamshacky** [comment]
The issues is that nobody on the freaking internet gives complete examples.

**Comment by Ryuno-Ki** [comment]
Not exactly the word's I've chosen, but thank you for providing more details. I'm reopening.

**Comment by Ryuno-Ki** [comment]
Does anyone of you know of an example for 405?
@hamishwillee, @Elchi3, @mirunacurtean

**Comment by teoli2003** [comment]
This can happen, for example, if your server is configured to reject `OPTIONS` HTTP requests; at that moment any request that require a CORS [preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) will fail with this error.

We could explain this, but there is not much of an example to write: it means that either the web server is misconfigured, or preventing something on purpose.

**Comment by iamshacky** [comment]
Sorry about my silly rant. Don't change anything just because of me.

**Comment by Ryuno-Ki** [comment]
No, it's fine. You bring up something, that many people closer to the knowledge don't even think about anymore, so it helps us making explanations clearer to a wider range of people.

Thank you for that.

Do you have a certain section where you would like to see Jean-Yves phrasing to be put in?

**Comment by teoli2003** [comment]
@iamshacky No worry! I'm happy to complete the article!

Putting this on my todolist (that is not that big :-) )

**Comment by iamshacky** [comment]
Thanks.

Certain section? No, but thanks for that. I've been having a tough time
with the formData thing in general. I just can't find any sort of stuff
that I need. I need to make a form that posts data into a database. I've
only known the regular html form post way until now. My whole process that
I want to do is 1) Have a localStorage cart with checkboxes that stay
clicked and enter page info into the localStorage (I'm using Jekyll so I
had to figure out that). Then on the cart page, I want to have a form with
basic contact info fields and attach the localStorage info to the formData
object when I send it. Then It needs to actually go to my php handling file
that I am also struggling with.

So no, I'm good on the offer. because one would have a lot to do :).  Whoa
is me.

Thanks and my apologies.

**Comment by iamshacky** [comment]
Oh ok, groovy.

**Comment by Ryuno-Ki** [comment]
(Okay, this kind of question rather belongs to StackOverflow or that like, but you sound like you've tried to find answers there already to no avail)

I would use HTML form, combine it with https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects#retrieving_a_formdata_object_from_an_html_form and use fetch API instead of XHR.

I can't help with PHP, but there is a [`$_POST`](https://www.php.net/manual/en/reserved.variables.post.php) superglobal, that should get you started (don't forget to validate to avoid attacks).

**Comment by iamshacky** [comment]
Hey thanks, that's very helpful. I was thinking in a different, overly
complicated way - barking up the wrong tree. I needed that bonus help out
of this rut.
