### ISSUE TITLE
Issue with "Storage Inspector": correction to final section

### ISSUE THREAD

**Issue by ChrisLMerrill** [mdn/content#6921]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector

#### What information was incorrect, unhelpful, or incomplete?

"The following articles cover different aspects of using the network monitor:"

#### Specific section or headline?

Working with the Storage Inspector

#### What did you expect to see?

... of using the **Storage Inspector** ...

#### Did you test this? If so, how?

Yes, with my eyes :)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/storage_inspector`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/storage_inspector/index.html
* Last commit: https://github.com/mdn/content/commit/821c317c971438756724aabea706d9922b2fad8b
* Document last modified: 2021-07-12T09:06:46.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened https://github.com/mdn/content/pull/6927 with a fix.
