### ISSUE TITLE
Issue with "About MDN Web Docs": …

### ISSUE THREAD

**Issue by brot** [mdn/content#694]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/About

#### What information was incorrect, unhelpful, or incomplete?

The Attribution line includes a wrong link. The Link to the Mozilla Contributors link to https://developer.mozilla.org/en-US/docs/MDN/About$history instead of https://developer.mozilla.org/en-US/docs/MDN/About/contributors.txt

#### Specific section or headline?

Documentation and articles / 1. Attribution

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/about`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/About
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/about/index.html
* Report started: 2020-12-28T17:35:23.833Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it; I’ve opened https://github.com/mdn/content/pull/704 with a fix.
