### ISSUE TITLE
Issue with "Quantifiers": Counting characters needs a better example

### ISSUE THREAD

**Issue by havajsky** [mdn/content#6948]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Quantifiers

#### What information was incorrect, unhelpful, or incomplete?
make it more helpful:
var notSoLongWord = /\b\w{1,6}\b/g;

#### Specific section or headline?
section "Counting characters"

#### What did you expect to see?
var notSoLongWord = /\b\w{2,6}\b/g;
instead of 
var notSoLongWord = /\b\w{1,6}\b/g;

i.e. between 2 and 6 matches rather than between 1 and 6 because "I" will be excluded.

#### Did you test this? If so, how?
no need

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions/quantifiers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Quantifiers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/quantifiers/index.html
* Last commit: https://github.com/mdn/content/commit/179e7d3a709f897d33ac9b833d9caff99f7396a3
* Document last modified: 2021-05-05T16:43:40.000Z

</details>

**Comment by sideshowbarker** [comment]
Can you explain why it’s better to exclude `"I"`?

It it because `"I"` is already matched by the first, `singleLetterWord` pattern?
