### ISSUE TITLE
Issue with "User interface": Images are skewed

### ISSUE THREAD

**Issue by ix5** [mdn/content#695]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface

#### What information was incorrect, unhelpful, or incomplete?

Several images are skewed.

Either apply `object-fit: contain` to each image, set the correct dimensions, or set it for all table images in `_base.scss` or `_table.scss`

#### Specific section or headline?

The main table, "Example" column.

#### What did you expect to see?

Images should not be skewed.

#### Did you test this? If so, how?

![mdn-screenshot](https://user-images.githubusercontent.com/10212877/103233122-8600d900-493c-11eb-9891-c90865e39fa4.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/user_interface`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/add-ons/webextensions/user_interface/index.html
* Report started: 2020-12-28T17:37:24.261Z

</details>

**Comment by hamishwillee** [comment]
Thanks. This is a known issue with styling that appears across the docs. I believe someone is looking at a global fix, but for this case I've just removed height styling - see linked PR.

**Comment by ix5** [comment]
Great, thanks!
