### ISSUE TITLE
Issue with "new operator": Messed up formatting on one page

### ISSUE THREAD

**Issue by gosoccerboy5** [mdn/content#6953]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new

#### What information was incorrect, unhelpful, or incomplete?
> Creating a user-defined object requires two steps:
> 
> 1. Define the object type by writing a function that specifies its name and properties. For example, a constructor function to  create an object `Foo` might look like this:
> ```js
> function Foo(bar1, bar2) {
>       this.bar1 = bar1;
>       this.bar2 = bar2;
>     }
> ```

#### Specific section or headline?
[#description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new#description)
https://github.com/mdn/content/blob/1f4efe144bc9c2aad70d8aae3ed2f25d4da9a864/files/en-us/web/javascript/reference/operators/new/index.html#L55-L58
#### What did you expect to see?
Normally formatted code that is consistent with the rest of the page

#### Did you test this? If so, how?
...

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/new`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/new/index.html
* Last commit: https://github.com/mdn/content/commit/1b532dac595c32a6f2dae046022c9ee75d206ef1
* Document last modified: 2021-07-03T16:22:48.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6954 with a fix.

**Comment by gosoccerboy5** [comment]
Thanks.
