### ISSUE TITLE
Issue with "Common MIME types": fold MIME-type articles together

### ISSUE THREAD

**Issue by mnot** [mdn/content#6956]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

#### What information was incorrect, unhelpful, or incomplete?

This page is listed in navigation as "Complete list of MIME types". That's obviously not true. It also duplicates some of the listing at the end of https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_Types - making me wonder if it could be folded into that page (or just deleted).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/basics_of_http/mime_types/common_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/mime_types/common_types/index.html
* Last commit: https://github.com/mdn/content/commit/13963ff487e978879d1ba95fb09495ed9c6c47bb
* Document last modified: 2021-05-21T03:41:06.000Z

</details>

**Comment by sideshowbarker** [comment]
> This page is listed in navigation as "Complete list of MIME types".

Can you point out where exactly that "Complete list of MIME types" string is being shown to you?

Grepping through the sources, I can’t find that string anywhere in the current sources.

I do find “*In*complete list of MIME types” in the list at https://developer.mozilla.org/en-US/docs/Glossary/MIME_type#learn_more …

**Comment by teoli2003** [comment]
It is in the sidebar, meaning we have to edit a macro in yari (trivial if we ignore the translations).

<img width="488" alt="Screenshot 2021-07-16 at 07 22 26" src="https://user-images.githubusercontent.com/1466293/125895989-e28be385-140b-4b02-90df-18adf026640f.png">

**Comment by sideshowbarker** [comment]
@teoli2003 Thanks — opened https://github.com/mdn/yari/pull/4224 with a fix.

**Comment by teoli2003** [comment]
I'm reopening this: During the future work on HTTP, I would like to consider this part of @mnot initial comment:

> making me wonder if it could be folded into that page (or just deleted).

Assigning myself so I don't forget :-)

**Comment by sideshowbarker** [comment]
Re-opening per https://github.com/mdn/content/issues/6956#issuecomment-881704048

**Comment by Josh-Cena** [comment]
Please see #34269; it seems most maintainers' opinions is that the two separate pages serve different purposes (one as a detailed explainer for the complex types, one as a more-complete cheatsheet for quick reference). If similar changes would just be rejected similarly, I think it's best to just close this issue.

**Comment by hamishwillee** [comment]
I see the arguments in that other issue as well reasoned, but it feels like it should be possible to do in a way that serves most purposes. Oh well, thanks for pursuing as far as was reasonable to do so.
