### ISSUE TITLE
Content bug: a typo found

### ISSUE THREAD

**Issue by logic-finder** [mdn/content#6957]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Simple_synth

## Specific page section or heading?

Building the keyboard

## What is the problem?

The table which maps note names and octaves to their **frequenies** is created by calling createNoteTable().

## What did you expect to see?

frequenies → frequencies

## Did you test this? If so, how?

I have translated en-US article to Korean before, but I have never tried translating en-US article itself and I have no idea how to do it. So I decided to make a issue here. Thank you.

**Comment by teoli2003** [comment]
Thank you! I opened a PR.

For small typo like this, you can easily use the GitHub UI to directly submit a PR, without the need to clone the whole repo. But filing an issue, is also perfectly fine.
