### ISSUE TITLE
Issue with "RTCPeerConnection": Methods section missing addTransceiver

### ISSUE THREAD

**Issue by dogben** [mdn/content#6962]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection

#### What information was incorrect, unhelpful, or incomplete?
RTCPeerConnection has an addTransceiver method (article linked in the Browser compatibility section), but it's not listed with the other methods.

#### Specific section or headline?
Methods

#### What did you expect to see?
addTransceiver summary

#### Did you test this? If so, how?
Article exists: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTransceiver

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/rtcpeerconnection`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/rtcpeerconnection/index.html
* Last commit: https://github.com/mdn/content/commit/c06fae922bad14ba616dbf1e82c46cec43fa7bc9
* Document last modified: 2021-07-04T00:13:56.000Z

</details>

**Comment by teoli2003** [comment]
This page use a broken macro that copy contennt from other page. So I would like to remove it at the same time. 

Assigning myself so this is on my radar. (Hopefully later today)

**Comment by teoli2003** [comment]
>  (Hopefully later today)

I know I shouldn't make "timed" promises, it was a kind of rabbit hole to fix it. Still trying to get out of it.
