### ISSUE TITLE
Issue with "Intl.DisplayNames() constructor": parameters are not optional

### ISSUE THREAD

**Issue by foolip** [mdn/content#6965]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/DisplayNames

#### What information was incorrect, unhelpful, or incomplete?

The page claims that the `locales` and `options` parameters are optional, but they are required in spec and implementations.

Also the description of `locales` is not clear that it can be either a string or an array. (This problem is present on other pages too.)

#### Did you test this? If so, how?

The spec is here:
https://tc39.es/ecma402/#sec-intl-displaynames-constructor

Also none of these snippets work in Chrome, Firefox or Safari:

```js
new Intl.DisplayNames();
new Intl.DisplayNames('sv');
new Intl.DisplayNames('sv', {});
```

As it turns out, the `type` parameter is required. This is the simplest working example I can make:

```js
new Intl.DisplayNames('sv', {type:'language'});
```

cc @Elchi3

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/displaynames/displaynames`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/DisplayNames
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/displaynames/displaynames/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by Elchi3** [comment]
This was fixed in https://github.com/mdn/content/pull/9165
