### ISSUE TITLE
Issue with "Set": methods list error

### ISSUE THREAD

**Issue by gilad905** [mdn/content#6968]
Under [Iteration methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#iteration_methods):

The methods [Set/values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/values) and [Set.prototype.values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/values) both refer to the same method. Also, the 2nd method references Set.prototype.keys(), although Set.prototype.keys() isn't listed.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/6974 with a fix.
