### ISSUE TITLE
Content bug: Possible parameters for URLSearchParams()

### ISSUE THREAD

**Issue by rimace** [mdn/content#6970]
## What page(s) did you find the problem on?
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams

## Specific page section or heading?
Parameters

## What is the problem?
new URLSearchParams() also takes a FormData object as a parameter, which is not documented.

## What did you expect to see?
Documentation what the init parameter can take.
Maybe I misunderstand something and the FormData type is a sequence of USVString pairs?
But still this example code (down here) could be included.

## Did you test this? If so, how?
You can use it that way to build a query string out of the FormData object.
This works:

```
const form = document.querySelect("form");
const formData = new FormData(form);
const urlParams = new URLSearchParams(formData);
const queryString = urlParams.toString();

```

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #7037 with a fix.
