### ISSUE TITLE
Issue with "Performance Analysis": (doesn't seem to do what is described)

### ISSUE THREAD

**Issue by David263** [mdn/content#6973]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Performance_Analysis

#### What information was incorrect, unhelpful, or incomplete?
Says that it will load the subject page twice and show the results. I'm not sure if this is a documentation problem (something left out) or a bug in Firefox Dev Tools.

#### Specific section or headline?
"Using the Performance analysis tool"

#### What did you expect to see?
I expected to see two different graphs. But both graphs are the same.

#### Did you test this? If so, how?
I opened a local test page using a local Apache server. I got the same result with setting Disable HTTP cache enabled and disabled. I'm not sure how much of my environment is relevant.

Posting [https://www.reddit.com/r/firefox/comments/bjdwwj/i_dont_understand_the_performance_analysis_tool/](url) from 2 years ago seems to describe a similar problem. Attached is a screenshot:
![Firefox-1](https://user-images.githubusercontent.com/3837238/125955000-24b5365c-1051-40c8-969e-6e3c30ec67e8.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/network_monitor/performance_analysis`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Performance_Analysis
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/network_monitor/performance_analysis/index.html
* Last commit: https://github.com/mdn/content/commit/0ea5ea66ca3ff5f0c02583c1f3606b3b7d4aee40
* Document last modified: 2021-02-02T16:28:31.000Z

</details>

**Comment by David263** [comment]
I've noticed two different 'stopwatch' icon buttons. One is part of a line of text seen when you first run Developer Tools and choose Network. The other is always shown in the status bar of the Network tool whenever it is visible. The problem I reported here happens after Network tool is populated, using the status bar icon.  I just tried it before the Network tool is populated using the  stopwatch icon near the top of the page, and I see the same problem: both the "Primed cache" and "Empty cache" graphs show the same numbers.

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
