### ISSUE TITLE
Issue with "Backgrounds and borders": (broken formatting)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6980]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders

#### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/51193876/125991967-c74e4af6-4d1f-4d81-ba30-146c919d00c2.png)

#### Specific section or headline?

Background images

#### What did you expect to see?

The first paragraph tells us that there's a background image larger than a box. The second paragraph tells us that the larger image is not scaled down to fit the box and that we can only see a small portion of it. But I don't see the truth of these statements in the pictures.

#### Did you test this? If so, how?

No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/backgrounds_and_borders`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/backgrounds_and_borders/index.html
* Last commit: https://github.com/mdn/content/commit/fc36604b19a172f3fbedb2629e2403180f2eda55
* Document last modified: 2021-03-19T23:16:59.000Z

</details>

**Comment by rachelandrew** [comment]
I've just tested this, it's the same image used for the other examples. Just in that example you only see the corner of it—as described. A following example then goes on to show how to manipulate the image to show all of it. 

https://mdn.github.io/css-examples/learn/backgrounds-borders/balloons.jpg

**Comment by ConsciousClay** [comment]
Yes, the full image and the explanation for how to view it is two sections below. But when the reader reads that they see a corner of an image, it's just a blueish rectangle. It doesn't look like a corner of an image at all. And we won't know what it's a corner of until we proceed past the section on the **background-repeat** property. Even then, I didn't notice the correlation between the two images when I read that article. I didn't notice it until now, when I just read your message. It would be better if the image contained some information to show us it was incomplete. For example, here are a picture of a chair and a clipped picture of that chair showing just a corner:

![image](https://user-images.githubusercontent.com/51193876/126191171-cabea996-6ec5-4513-a2ec-3bfa2577661b.png)

![image](https://user-images.githubusercontent.com/51193876/126191202-ecc4e257-9b92-4505-b132-24ef3486db9c.png)

I think this is much clearer.
