### ISSUE TITLE
Issue with "Backgrounds and borders": (poor formatting)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6982]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders

#### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/51193876/125995861-393d8522-c7c4-4c18-98fb-85f034a23528.png)

#### Specific section or headline?

Positioning the background image

#### What did you expect to see?

There's a lot of white space between the note and the rest of its section.

#### Did you test this? If so, how?

No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/backgrounds_and_borders`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/backgrounds_and_borders/index.html
* Last commit: https://github.com/mdn/content/commit/fc36604b19a172f3fbedb2629e2403180f2eda55
* Document last modified: 2021-03-19T23:16:59.000Z

</details>

**Comment by NegiAkash890** [comment]
![mdn_issue](https://user-images.githubusercontent.com/55234838/126371348-eaba99fd-4780-47d1-b3e1-12e93d5ff5c9.png)

It's probably because of the height of iframe. I think height of 600px would be fine instead of 800px.

**Comment by reddymahendra52** [comment]
I guess they have put that much height because on viewing those articles on different devices (mobile phones, tabs, e.t.c) it fits alright and for every `iframe` it would be hard to hardcode it responsively. So I think they have put that much height.
That's my opinion.
