### ISSUE TITLE
Issue with "Hoisting": Initializations using let and const are also not hoisted

### ISSUE THREAD

**Issue by npar0005** [mdn/content#6988]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting#only_declarations_are_hoisted

#### What information was incorrect, unhelpful, or incomplete?
The statement:

> Initializations using let and const are also not hoisted

is not correct. `let` and `const` are hoisted - this seems like a simplification that isn't correct, and should be updated to mention something about the temporal dead-zone.
#### Specific section or headline?
Under _Only declarations are hoisted_, after the second code-block.

#### What did you expect to see?
I expected to see mention of the temporal dead-zone.  Let and const declarations are hoisted, but they can't be accessed due to the TDZ.

#### Did you test this? If so, how?

This example shows that `let` is hoisted:
```js
let x = 'outer value';
(function() {
  // start TDZ for x
  console.log(x); // ReferenceError: Cannot access 'x' before initialization
  let x = 'inner value'; // declaration ends TDZ for x
}());
```
if `let` was not hoisted, then the log would show `'outer value'`. 

Example above from: [Temporal Dead Zone (TDZ) demystified](http://jsrocks.org/2015/01/temporal-dead-zone-tdz-demystified)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/hoisting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/hoisting/index.html
* Last commit: https://github.com/mdn/content/commit/75c1271189903b4d96433a34a8174175dd089ef2
* Document last modified: 2021-04-28T14:08:28.000Z

</details>

**Comment by hamishwillee** [comment]
Fixed in #7023

Thanks - you're right. The only real difference in "hoisting" behaviour is that var sets a default value of undefined while the other types don't. Otherwise everything is the same - you have to wait for the line in which the initialisation happens to actually execute.
