### ISSUE TITLE
Issue with "FileReader.onerror": (Incomplete/Irrelevant Comment)

### ISSUE THREAD

**Issue by Adarsh077** [mdn/content#6991]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FileReader/onerror

#### What information was incorrect, unhelpful, or incomplete?
There is a comment in the sample code which I found confusing. why is it there
```
reader.abort(); // (...does this do anything useful in an onerror handler?)
```

#### Specific section or headline?
Sample Code

#### What did you expect to see?
The answer to that question in a comment

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/filereader/onerror`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FileReader/onerror
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/filereader/onerror/index.html
* Last commit: https://github.com/mdn/content/commit/c842e7159d296e2298380acbc07ffcbd90ab8c1c
* Document last modified: 2021-05-31T16:49:38.000Z

</details>

**Comment by hamishwillee** [comment]
@Adarsh077 I'd say it is a mistake - the author wasn't sure if it is needed or not.

@Rumyra My read on the spec is that this line is not needed in the error handler as errors abort the process automatically. Can you confirm it would it be correct to simply remove this line? 

The [FileReader.abort()](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/abort) states "Upon return, the readyState will be DONE.". Do we know what the state would be following an error, and if you do, is it worth stating that too?
