### ISSUE TITLE
Issue with "<var>: The Variable element": wrong example used

### ISSUE THREAD

**Issue by pandammonium** [mdn/content#6996]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/var

#### What information was incorrect, unhelpful, or incomplete?

The example of overriding the browsers' applying the "italic" font-style to &lt;var&gt; by default looks like it's been copied and pasted from the later example of overriding the default styling of &lt;var&gt; (but keeping the italics).

#### Specific section or headline?

The wrong example is in Usage notes > Default style

The source example comes from Examples > Overriding the default style

#### What did you expect to see?

Something like:

var {
  font-style: normal;
}

#### Did you test this? If so, how?

n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/var`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/var
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/var/index.html
* Last commit: https://github.com/mdn/content/commit/8d28de329fc4f723ad4362f0f703e46c4fa9e32d
* Document last modified: 2021-06-02T17:52:41.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@schalkneethling Is this on your radar? Should we move this issue to minimalist repo?

**Comment by schalkneethling** [comment]
@pandammonium Am I correct that you are referring to the interactive example, and expected something more like this?

![Screenshot 2021-07-19 at 11 54 15](https://user-images.githubusercontent.com/10350960/126141907-04f9c6d2-5418-454f-8dcf-466dfb94f5f3.png)

Thanks for the ping @Ryuno-Ki - If this issue is related to the interactive example, then we should move it to the interactive examples repo.

**Comment by pandammonium** [comment]
> @pandammonium Am I correct that you are referring to the interactive example, and expected something more like this?

@schalkneethling No, I'm not referring to the interactive example; I'm referring to the main text.

The first screenshot below indicates the problem; the second shows the proposed solution (using BSI proofreading marks). I hope these images, along with the more detailed information, clarify my original report.

# The problem

Section 'Usage notes' has subsection 'Default style', which says that most browsers set `font-style: italic`. It goes on to say that this browser setting can be overridden using CSS, and an example is given. I would expect this example to show the value of `font-style` being overridden (1).

1. `var {`
`  font-style: normal;`
`}`

However, the example given (2) does not override the value of `font-style`. Instead, it overrides the values of `font-weight`, `font-size` and `font-family` (using the overarching `font` property).

2. `var {`
`  font: bold 15px "Courier", "Courier New", monospace;`
`}`

With the settings in (2), `var` elements will be rendered in a bold, 15px, Courier (New)/monospace, italic font.

Section 'Examples' has subsection 'Overriding the default style', which further discusses overriding the default style, and an example (3) is given. The example overrides the values of `font-weight`, `font-size` and `font-family` (using the overarching `font` property), leaving the value of `font-style` unchanged.

3. `var {`
`  font: bold 15px "Courier", "Courier New", monospace;`
`}`

Example (3) seems to have been incorrectly used in 'Usage notes' > 'Default style' instead of (1), above.

![The problem](https://user-images.githubusercontent.com/13066721/126160148-b20a1fdc-9fc7-4cb4-98e3-6974dcaff82c.png)

# The solution

Change incorrect example (2), above, to one which changes the font style, and only the font style, to something other than italic, as shown in (1), above.

![The solution](https://user-images.githubusercontent.com/13066721/126162912-e511b756-fd58-47e9-8e65-5550d05ac371.jpg)

**Comment by rachelandrew** [comment]
@pandammonium apologies for the confusion. I have just made a PR which fixes the problem that you correctly pointed out. Thank you!
