### ISSUE TITLE
Issue with "The box model": (confusing phrasing)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#6999]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model

#### What information was incorrect, unhelpful, or incomplete?

> The space taken up by our box using the standard box model will actually be 410px (350 + 25 + 25 + 5 + 5), and the height 210px (150 + 25 + 25 + 5 + 5), as the padding and border are added to the width used for the content box.

#### Specific section or headline?

The standard CSS box model

#### What did you expect to see?

I don't understand the insistence to attribute the size of 410px to the **space** of the box. The space of the box is not 410px. The box' **width** is 410px and the **height** is 210px. These sizes _do not_ combine into 410px. I also don't understand why the space of the box is being correlated with its height. The _width_ of a box should be correlated with its height. Lastly, I don't understand why the last clause only states that the padding and border are added to the width. What about the padding and border being added to the height? In any case, we were already told about this in the previous passage. Am I missing something here? I tried to file a PR but it was rejected.

#### Did you test this? If so, how?

No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/the_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/the_box_model/index.html
* Last commit: https://github.com/mdn/content/commit/1f4efe144bc9c2aad70d8aae3ed2f25d4da9a864
* Document last modified: 2021-07-15T23:57:49.000Z

</details>

**Comment by hamishwillee** [comment]
Agree. Fixed by #7019
