### ISSUE TITLE
Issue with "Using Service Workers": needs better examples

### ISSUE THREAD

**Issue by sjswitzer** [mdn/content#7006]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

#### What information was incorrect, unhelpful, or incomplete?
The information was correct but hard to puzzle through.

#### What did you expect to see?

I'd like some clearer examples. I understand the impulse to describe and explain it explicitly in terms of the Promises but not using async functions to implement service workers is a real missed opportunity.

After much pondering and _many_ failed attempts, I managed to reduce a service worker implementation to something very simple using async functions. Feel free to use it or variations on it in your examples if you think it's helpful.

  https://github.com/sjswitzer/UnitsCalc/blob/main/service-worker.js

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/service_worker_api/using_service_workers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/service_worker_api/using_service_workers/index.html
* Last commit: https://github.com/mdn/content/commit/5b8413c8fbdb692efa138053062c1408cd2bac09
* Document last modified: 2021-06-15T03:17:13.000Z

</details>

**Comment by SphinxKnight** [comment]
Seems like https://github.com/mdn/content/pull/13669 did the job.
cc @sideshowbarker for second thoughts before closing this one

**Comment by sideshowbarker** [comment]
@SphinxKnight Thanks yeah, let’s go ahead and close this as resolved by #13669

@sjswitzer If we missed something, this issue can be revisited (and re-opened)
