### ISSUE TITLE
Content bug: contradictory content

### ISSUE THREAD

**Issue by logic-finder** [mdn/content#7009]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Test_your_skills:_Loops

## Specific page section or heading?

'Note' and 'Assessment or further help'

## What is the problem?

At 'Note', it says: "We **didn't provide live editable versions** of these tasks because of the risk of creating infinite loops and crashing the assessment page!"

However, at 'Assessment or further help', it says: "You **can practice** these examples in **the Interactive Editors above**."

## What did you expect to see?

Since there are no interactive editors, I think the latter sentence needs to be deleted.

## Did you test this? If so, how?

**Comment by hamishwillee** [comment]
Thank you - fixed by #7018 (and yes, I agree this line can just be removed).
