### ISSUE TITLE
Issue with "String.prototype.substr()": description omits start == 0

### ISSUE THREAD

**Issue by dirkf** [mdn/content#7012]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

#### What information was incorrect, unhelpful, or incomplete?

The `start` parameter can be 0 but the description only covers positive and negative values.

#### Specific section or headline?
```
...
Description

substr() extracts length characters from a str, counting from the start index.

    If start is a positive number, the index starts counting at the start of the string. Its value is capped at str.length. 
...
```
#### What did you expect to see?

Should say `non-negative number`, not `positive number`, since a `start` value of 0 can be used to specify a substring starting with the first character of the string.

#### Did you test this? If so, how?

See eg description of `String.prototype.indexOf()`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/substr`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/substr/index.html
* Last commit: https://github.com/mdn/content/commit/13360cbad46b4ce6457f80492d73d2efd252e8a9
* Document last modified: 2021-05-05T10:31:52.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #7021 with a fix.
