### ISSUE TITLE
Issue with "MediaDevices.ondevicechange": (short summary here please)

### ISSUE THREAD

**Issue by dizarius** [mdn/content#7015]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/ondevicechange

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediadevices/ondevicechange`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/ondevicechange
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediadevices/ondevicechange/index.html
* Last commit: https://github.com/mdn/content/commit/6e703a5c1d7e263c827ead19a10be0654e0f456f
* Document last modified: 2021-07-12T17:44:17.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@dizarius What do you need help with?

**Comment by teoli2003** [comment]
Hi!

Unfortunately you didn't provide any information about the issue you are reporting. We cannot act on it.

I'm closing it. If you come back and provide more information, you are welcome to re-open it (or to fill a separate issue).

Thanks a lot for your interest!
