### ISSUE TITLE
Issue with "HTMLCanvasElement.toBlob()": (minor: docs do not list supported image types, nor mention fallback)

### ISSUE THREAD

**Issue by petersmagnusson** [mdn/content#7020]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

#### What information was incorrect, unhelpful, or incomplete?

The section on the second argument (mimeType) does not mention that if the requested type is not supported, the fallback is "png". 

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob#parameters

#### What did you expect to see?

A mention of the fact that various browsers will support different sets of types here, and that if the requested one is not supported it will fall back to png.

#### Did you test this? If so, how?

Wrote a script that will try various conversion types on various browsers.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlcanvaselement/toblob`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlcanvaselement/toblob/index.html
* Last commit: https://github.com/mdn/content/commit/106d7e1dfcd4068ff15b6c1cd887b7e4077701e7
* Document last modified: 2021-06-13T08:47:42.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/7028 with a fix.
