### ISSUE TITLE
Issue with "Getting started with CSS": (short summary here please)

### ISSUE THREAD

**Issue by 754194868** [mdn/content#7030]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started

The practice page can't be displayed, it shows that"mdn.github.io refused to connect."

**Comment by sideshowbarker** [comment]
Can you please identify exactly what you mean by “practice page”?\

Is there are link on https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started that you followed?

Or is the https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started article itself somewhere displaying an “mdn.github.io refused to connect” message?

**Comment by reddymahendra52** [comment]
Hello,
After going through this Issue. I went on to read the following article directed by the above links.
While going through the article I stumbled upon this line.
>Try this out in the interactive editor below (edit the code boxes), or in your local CSS document.

For a few moments, I couldn't find where the editor really was, and after poking around I found the editor.

So I was thinking of proposing this small change.

**Current Article:**

![Current Article](https://i.imgur.com/86YaK1v.png)

**Proposed Change:**

![Proposed Change](https://i.imgur.com/IfgMtoq.png)


Looking at the amount of size of the content could this change be practically possible??

**Comment by sideshowbarker** [comment]
@reddymahendra52 I see now — thanks.

I agree it would be useful to have an **Interactive editor** subheading above both of those code boxes — to make it clear that they’re editable. Adding any subheadings there would require edits to the sources at https://github.com/mdn/css-examples/blob/master/learn/getting-started/started1.html. Altering @rachelandrew to see what she thinks.

**Comment by rachelandrew** [comment]
I could probably do that, I'll take a look tomorrow as that seems like a reasonable suggestion.

**Comment by reddymahendra52** [comment]
Just asking.
Is it possible like, that I make a PR for this and it gets merged.

Or the changes are needed to be done on your end?

**Comment by rachelandrew** [comment]
If I'm going to change it for one, I want it to be consistent for all so I'd prefer to do this one. I can also roll it into some other tidying up of those examples I need to do.

**Comment by rachelandrew** [comment]
OK, this should now be in place for examples in the Learn CSS section of the site. It may mean that some of these editors have a scrollbar as it makes the area taller, but I can fix those as I come across them.

I think the original post must have been a network error, as these examples are loading so I'm going to close this. Feel free to reopen @754194868 if you still can't see the examples, with some more info so we can investigate.
