### ISSUE TITLE
Issue with "Building a cross-browser extension": Informtion involving Edge store is incorrect. 

### ISSUE THREAD

**Issue by cdowen** [mdn/content#7032]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

#### What information was incorrect, unhelpful, or incomplete?

Information involving Edge store is incorrect. To be specific, the registration fee, review process length and limit regarding submission for edge store are outdated now.

#### Specific section or headline?

The table in [Extension publishing section](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension#extension_publishing)

#### What did you expect to see?

Currently, publishing an extension in ms edge store is free and there is no registration fee. The pre-publication review process for edge may take one week. And any extension can be published, there is no limit now.

#### Did you test this? If so, how?
I just publish an extension to edge store and it is under review.
Besides, there is ms official doc for [submission](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension) and [dev registration](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/create-dev-account).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.html
* Last commit: https://github.com/mdn/content/commit/e7d3ed41dcb4c5da8f7137bde93d1ee3f4d41031
* Document last modified: 2021-06-08T21:41:43.000Z

</details>

**Comment by caitmuenster** [comment]
This issue is open to contributors! If this is your first contribution to MDN, check out this short guide to [getting started](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Getting_started#4_simple_steps_to_mdn). For more information about style guides, previewing changes, and submitting changes via pull requests, please see the [MDN content README](https://github.com/mdn/content/blob/main/README.md#making-contributions). 

Mentor: @caitmuenster
