### ISSUE TITLE
Issue with "Promise() constructor": various statements are false/incorrect, and others are incomplete/misleading/nonsensical

### ISSUE THREAD

**Issue by trincot** [mdn/content#7034]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise

#### What information was incorrect, unhelpful, or incomplete?

Quote: "The operation within executor is asynchronous and provides a callback."

This is false: the executor is executed synchronously.

Quote: "The callback is defined within the executor code."

What does this even mean? The the executor *is* the callback (passed to `new Promise`).

Quote: "The callback terminates by invoking resolutionFunc."

This is false: the callback continues executing after that function call.

Quote: "The invocation of resolutionFunc includes a value parameter."

This is incomplete: This value parameter is optional

Quote: "The value is passed back to the tethered Promise object."

The word "tethered" should not be used at all. It is non-standard. The executor just calls back.

Quote: "The Promise object (asynchronously) invokes any associated .then(handleResolved)"

This is misleading, as it does not invoke `.then`, but `handleResolved`.

Quote: "The value received by .then(handleResolved) is passed to the invocation of handleResolved as an input parameter"

This makes no sense. The value passed to `handleResolved` is the value the original promise resolved with, i.e. the value passed to `resolutionFunc`.

#### Specific section or headline?

Parameters - executor

#### What did you expect to see?

Information in line with ECMAScript specification. Content that has the high quality I am used to when reading MDN. This is a rare exception.

#### Did you test this? If so, how?

n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise/promise`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/promise/index.html
* Last commit: https://github.com/mdn/content/commit/75bf139c604bdca9e955c32618787a31458512b2
* Document last modified: 2021-06-23T08:11:11.000Z

</details>

**Comment by dorward** [comment]
Note that the section is labelled as describing a **typical** flow where "The operation **within** executor is asynchronous and provides a callback". You can pass a non-asynchronous function but that isn't a typical flow.

**Comment by jjarv-tuni** [comment]
Also someone could clearly explain why is it that when novice is trying to apply promises they tend to return more promises and not the intended value. Is it how they are designed or is there some common error to pay attention to.
