### ISSUE TITLE
Issue with "Navigator": sidebar contains duplicated elements

### ISSUE THREAD

**Issue by lucacasonato** [mdn/content#7036]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/battery

#### What information was incorrect, unhelpful, or incomplete?

The sidebar contains all properties 4 times. They all link to the same pages.

![image](https://user-images.githubusercontent.com/7829205/126159630-72aca2a6-e8df-45f7-bd5b-7a01dc8d407f.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/navigator/battery`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/battery
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/battery/index.html
* Last commit: https://github.com/mdn/content/commit/9b648e559239b3e682abfcb15845a954d420b207
* Document last modified: 2021-05-31T17:00:38.000Z

</details>

**Comment by teoli2003** [comment]
This happening on all navigator pages… `{{APIRef}}` is doing something weird.

**Comment by lucacasonato** [comment]
So Yari issue?

**Comment by sideshowbarker** [comment]
Yeah, this is a Yari issue — specifically, a kumascript macros issue — caused by some things having been deleted from MDN but not yet from `kumascript/macros/InterfaceData.json`. See https://github.com/mdn/yari/commit/02988aaf68d258a097d640357bcb60b800ce69e5 for another recent case.

**Comment by sideshowbarker** [comment]
Opened https://github.com/mdn/yari/pull/4252 with a fix.

**Comment by teoli2003** [comment]
Thank you, completely forgot about `InterfaceData`! So my fault. Thanks for fixing it.

**Comment by lucacasonato** [comment]
Thanks folks!
