### ISSUE TITLE
Issue with "CSS values and units": (clarification needed)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#7054]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units

#### What information was incorrect, unhelpful, or incomplete?

> **Note:** When you use a number in CSS as a value it should not be surrounded in quotes.

#### Specific section or headline?

Numbers

#### What did you expect to see?

When it says "**number**", does this mean any of unit [`<integer>, <number>, <dimension>, <percentage>`]? Or does it mean just the units of `<number>`?

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/values_and_units`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/values_and_units/index.html
* Last commit: https://github.com/mdn/content/commit/608267fea2ba42a8a5b1020f8e62d9559429fa99
* Document last modified: 2021-05-12T14:45:49.000Z

</details>

**Comment by hamishwillee** [comment]
My understanding is that values that are strings are quoted, but numbers and identifiers are not. In this case it means numeric value including the unit (the unit is an identifier). 

I guess you might clarify this explicitly in text but do you really think anyone would misinterpret this, particularly with the examples right there? If you suggest a PR that captures this more precisely we will consider it.

**Comment by rachelandrew** [comment]
Closing as I don't think this needs changing, likewise happy to consider a PR.
