### ISSUE TITLE
Issue with "CSS values and units": (clarification please)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#7055]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units

#### What information was incorrect, unhelpful, or incomplete?

> **Note:** At some point modern browsers were updated so that rgba() and rgb(), and hsl() and hsla() (see below), became pure aliases of each other and started to behave exactly the same.

#### Specific section or headline?

RGB and RGBA values

#### What did you expect to see?

So is **rgb()** an alias of **hsl()**?

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/values_and_units`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/values_and_units/index.html
* Last commit: https://github.com/mdn/content/commit/608267fea2ba42a8a5b1020f8e62d9559429fa99
* Document last modified: 2021-05-12T14:45:49.000Z

</details>

**Comment by hamishwillee** [comment]
No. rgba() and rgb() are aliases of each other, and  hsl() and hsla() are aliases. I also read the sentence to mean that.

**Comment by teoli2003** [comment]
We could change the and following the Oxford comma to _as well as_ to make it clearer.

**Comment by ConsciousClay** [comment]
It's only correct if it's interpreted in a certain way. But what is it about the text that warrants an expectation that a reader will interpret in that certain way? I genuinely wasn't sure if **rgb()** was an alias of **hsl()**. That's why I asked.

**Comment by reddymahendra52** [comment]
> We could change the and following the Oxford comma to _as well as_ to make it clearer.
> 
> I would approve any rewording that makes it clearer (even if it is correct now).

In reference to the above comment, I tried these changes If it's acceptable I can make the Pull Request.
![change](https://i.imgur.com/armQOMW.png)

**Comment by ConsciousClay** [comment]
That's a clearer explanation. But it's not very smooth. I'd suggest:

At some point, modern browsers were updated so that `rgb()` and `rgba()` became pure aliases of each other and started behaving the same way. This also happened with the functions `hsl()` and `hsla()`. For example, `rgb()` and `rgba()` both accept colors with or without alpha channel values.

I can provide an alternative if this doesn't read well to you guys.

**Comment by reddymahendra52** [comment]
@ConsciousClay, I am ready to agree with what ever you suggested. As long as it bodes well with everyone.

**Comment by rachelandrew** [comment]
It wasn't browsers that changed this, the spec was updated.

It is explained (correctly!) here: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgb_colors so I would suggest using similar wording.

**Comment by rachelandrew** [comment]
Fixed in #7118
