### ISSUE TITLE
Class constructor default parameters and accessing fields

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#7056]
1. It is not well documented how you set default values of a class. If this is documented at all, it is not well linked from class and constructor documentation. Might also be linked from private member docs.
2. There is a "gotcha" that is not documented. If you set a default value on declaration of a member this may be over-written by your constructor. However if your constructor doesn't have a default value then this will be overwritten to "undefined". So the hint should probably be that you should use constructor or declaration initialisation, but not both.

Discussion arises out of https://github.com/mdn/content/pull/6786#issuecomment-878738274

MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Comment by Josh-Cena** [comment]
Does this suffice? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields

> Fields without initializers are initialized to `undefined`.

Strictly speaking, `a = 1` is a field declaration with initializer, not a default value

**Comment by sideshowbarker** [comment]
@hamishwillee I think this one is waiting on your response to https://github.com/mdn/content/issues/7056#issuecomment-1162713244

**Comment by hamishwillee** [comment]
> Does this suffice

@Josh-Cena  Not really

There are two parts to this. The first is "how to I provide default values for class data". IN some languages you would do this using a syntax a bit like this - i.e. provide a default value by assignment in the constructor:
```
class Animal {
  constructor(name="my default name") {
    this.name = name;
  }
}
```

Is that how you do it in JavaScript? How would someone know that - we don't mention it in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes - or am I missing something?

The second part is highlighting the issue that  field declaration with initializer may be overwritten by your constructor. Do you think that "`Fields without initializers are initialized to undefined.`" is sufficient to cover that case? It may be that this is not something that a JavaScript developer would ever need to worry about or consider - but it seemed relevant to me.

**Comment by Josh-Cena** [comment]
> provide a default value by assignment in the constructor:

Ah, sure we can do that. Since constructor definitions follow normal function definition syntax, you can use basically anything.

> field declaration with initializer may be overwritten by your constructor

Yes we can have an example I think. The current explanation is quite abstract:

> Public instance fields are added with [`Object.defineProperty()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) either at construction time in the base class (before the constructor body runs), or just after `super()` returns in a subclass.

**Comment by hamishwillee** [comment]
@Josh-Cena Would you mind doing the PR for that? I trust you not to screw it up more than me.

**Comment by Josh-Cena** [comment]
No problem—I will get around to it eventually 😄
