### ISSUE TITLE
Issue with "Web video codec guide": Why the VP8 recommendation?

### ISSUE THREAD

**Issue by flaki** [mdn/content#7064]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#recommendations_for_everyday_videos

#### What information was incorrect, unhelpful, or incomplete?

Is there any particular reason the Web Video Codec Guide recommends VP8, over VP9?

#### Specific section or headline?

> **A WebM container using the VP8 codec for video and the Opus codec for audio.** These are all open, royalty-free formats which are generally well-supported, although only in quite recent browsers, which is why a fallback is a good idea.

#### What did you expect to see?

This is a weird combination, as, to my understanding, practically any modern browser that [supports Opus](https://caniuse.com/?search=opus) should [also support VP9](https://vpixacceleration.com/), with unsupporting browsers served by the h264+aac in 2. The VP9 codec offers much improved quality in reduced bandwidth over the older VP8, so this combination seems inefficient to me. The [Wikipedia transcoding guidelines](https://commons.wikimedia.org/wiki/Help:Converting_video#.webm) also recommend VP9 and Opus as their preferred webm targets. Is there any consideration I perhaps be missing here?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/media/formats/video_codecs`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/media/formats/video_codecs/index.html
* Last commit: https://github.com/mdn/content/commit/bd8952f00c7f5319216030e5f844d891004850b2
* Document last modified: 2021-06-14T15:33:20.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this.

> Is there any particular reason the Web Video Codec Guide recommends VP8, over VP9?

None that I can imagine. Rather I think it’s just that that part of the article hasn’t been updated in a very long time.

So I’ve opened #7065 with a change that just changes “VP8” there to “VP9”.
