### ISSUE TITLE
Issue with "Compiling from Rust to WebAssembly": code does not seem to work.

### ISSUE THREAD

**Issue by LollipopFt** [mdn/content#7076]
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

#### What information was incorrect, unhelpful, or incomplete?
The code did not seem to be working.

#### What did you expect to see?
Expected the code to work.

#### Did you test this? If so, how?
the file tree:
![image](https://user-images.githubusercontent.com/62802897/126316236-06247cd4-e08b-4fd3-8215-5399129f4c48.png)

using http.server:
![image](https://user-images.githubusercontent.com/62802897/126316623-aa38ffd6-43b7-494a-a719-da3bae24e134.png)
all folders can be seen, and even files:
![image](https://user-images.githubusercontent.com/62802897/126316695-8adcf3de-5eb7-4264-ab8d-674db84313a1.png)
however, when opening the hello-wasm example, nothing chooses to appear:
![image](https://user-images.githubusercontent.com/62802897/126316938-87765eab-f889-4ba1-994e-ed55dc4618a8.png)
![image](https://user-images.githubusercontent.com/62802897/126316820-8b56f588-b074-424d-bfa2-7ccefe96ed39.png)
so how do i fix this problem?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/rust_to_wasm`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/rust_to_wasm/index.html
* Last commit: https://github.com/mdn/content/commit/3decf70c58cce7b5022101b18acc43394ce123f2
* Document last modified: 2021-04-22T15:57:23.000Z

</details>

**Comment by sideshowbarker** [comment]
Did you complete the following steps?

* https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm#lets_write_some_rust
  > Let's put this code into src/lib.rs instead:
* https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm#compiling_our_code_to_webassembly
  > To compile our code correctly, we first need to configure it with Cargo.toml. Open this file, and change its contents to look like this:
* https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm#building_the_package
  > Now that we've got everything set up, let's build the package. Type this into your terminal:

**Comment by LollipopFt** [comment]
unfortunately i did... copied the code exactly.

**Comment by LollipopFt** [comment]
[hello-wasm.zip](https://github.com/mdn/content/files/6855707/hello-wasm.zip)

**Comment by LollipopFt** [comment]
could it be because some windows feature was disabled?

**Comment by MendyBerger** [comment]
@LollipopFt this is weired, I downloaded your zip file and ran it, I get the alert without any problems

![image](https://user-images.githubusercontent.com/12537668/128638735-d93a914c-52de-4b5d-99a0-d185c23ae905.png)

**Comment by LollipopFt** [comment]
i definitely think it has something to do how some of my windows features are turned off. may i know what is needed to be enabled for it to run?

**Comment by LollipopFt** [comment]
my set-up:
![image](https://user-images.githubusercontent.com/62802897/128675694-dfa15ec6-9ef1-43a9-a7bd-0fd94f4c600c.png)
![image](https://user-images.githubusercontent.com/62802897/128675905-3c242b22-feec-43df-acaa-3296914933fd.png)
is this all i need?

**Comment by LollipopFt** [comment]
hi, this is my console output:
```python
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::ffff:127.0.0.1 - - [28/Aug/2021 12:13:34] "GET / HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [28/Aug/2021 12:13:34] "GET /pkg/hello_wasm.js HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [28/Aug/2021 12:13:34] code 404, message File not found
::ffff:127.0.0.1 - - [28/Aug/2021 12:13:34] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by MendyBerger** [comment]
@LollipopFt what about the JavaScript console in the browser, any errors there?

**Comment by LollipopFt** [comment]
```javascript
Loading module from “http://localhost:8000/hello-wasm/pkg/hello_wasm.js” was blocked because of a disallowed MIME type (“text/plain”).
```
this is the console error I had found.

**Comment by LollipopFt** [comment]
I am using python's http.server, not sure if i have to add anything more for it to work.

**Comment by LollipopFt** [comment]
hi, sorry for the trouble, I have discovered that python's http.server is the problem. using [simple-http-server](https://github.com/TheWaWaR/simple-http-server) works.

**Comment by MendyBerger** [comment]
Yes, this issue is related to the server, in order for a .wasm module to work, the server needs to respond with the `application/wasm` MIME type.

So the server you used previously probably didn't support this MIME type yet and the python server already supports it.

I think you can go ahead and close this issue since nothing is wrong with the actual example, although it wouldn't be a bad idea to add a little comment on the page stating that this might be an issue, I'll try to do it. 

Just out of curiosity, what server did you use previously?

**Comment by LollipopFt** [comment]
hi @MendyBerger,
my python version: ```Python 3.9.6```
http.server http version: ```Version    HTTP/1.0```
no wonder it didn't work...
