### ISSUE TITLE
Issue with "XMLHttpRequest: progress event": Demo broken by CORS

### ISSUE THREAD

**Issue by dsernst** [mdn/content#709]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/progress_event

#### What information was incorrect, unhelpful, or incomplete?

The demo doesn't run because of Cross-Origin Access Controls.

#### Specific section or headline?

`Result` section

#### What did you expect to see?

The demo showing bytes transferring and updating with progress.

#### Did you test this? If so, how?

<img width="952" alt="image" src="https://user-images.githubusercontent.com/6340841/103246030-de24e480-4916-11eb-91c6-3d0833b3fee2.png">

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/xmlhttprequest/progress_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/progress_event
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/xmlhttprequest/progress_event/index.html
* Report started: 2020-12-28T22:09:18.226Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. I’ve opened https://github.com/mdn/content/pull/726 with a fix.

**Comment by dsernst** [comment]
🙌 you're fast! great job

**Comment by sideshowbarker** [comment]
> 🙌 you're fast! great job

Cheers 😀 It would have been even faster, except it took some time to figure how a suitable replacement resource with the right set of characteristics. Anyway, thanks again very much.
