### ISSUE TITLE
Issue with "Sizing items in CSS": (confusing explanation)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#7097]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS

#### What information was incorrect, unhelpful, or incomplete?

> Again, this is the intrinsic size of the element — its size is defined by its content.

#### Specific section or headline?

The natural or intrinsic size of things

#### What did you expect to see?

The previous two sentences just talked about the sizing being affected by the content. That affected size is not the intrinsic size. The last sentence in the paragraph doesn't make sense in the context it's in.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/sizing_items_in_css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/sizing_items_in_css/index.html
* Last commit: https://github.com/mdn/content/commit/6077d5f480b2a404b21a405acc3dd1b66c1cb4ef
* Document last modified: 2021-03-31T04:51:23.000Z

</details>

**Comment by rachelandrew** [comment]
That sentence appears to be perfectly correct, the content defines the intrinsic size of the box in the block dimension. As defined in CSS Box Sizing: https://www.w3.org/TR/css-sizing-3/#intrinsic-sizes

**Comment by ConsciousClay** [comment]
Does that mean that for elements without any inherent content, such as a `div`, their intrinsic size will always be determined by whatever content they have?

When I read that originally, it seemed to me to be saying that **divs** either don't have an intrinsic size or that their intrinsic size is zero (if that's even coherent, which in Euclidean geometry it is). In any case, I don't see how something can be both intrinsic and variable at the same time.

There are two definitions of **intrinsic** on the OED.

1.   Belonging to a thing in itself, or by its very nature; inherent, essential, natural (to).
2.  Situated within; interior, inner

The second is marked as obsolete. And I don't think that's the intended meaning anyhow. The first, at least in philosophy, is usually taken to amount to the proposition that if we make any changes to the intrinsic property, then we change the very thing itself into something numerically different. But in this case, a div is a div, regardless of its size.

**Comment by rachelandrew** [comment]
This is the meaning as used in CSS, I gave you a link to the spec where you can see how it is defined. As beginner material, this is a simplification, but the intrinsic size is defined by the content in this case (as opposed to the initial case where there was an element with a size - an image.)

**Comment by ConsciousClay** [comment]
Okay, I get it. In that case, I think it would be clearer if some such contrasting phrasing were used, such as "in contrast..."

**Comment by rachelandrew** [comment]
> Okay, I get it. In that case, I think it would be clearer if some such contrasting phrasing were used, such as "in contrast..."

I'm not sure what it would be in contrast to, my feeling is that this wording is correct for the level of explanation required in this beginner material. It introduces a term and concept as it is used in CSS.

**Comment by ConsciousClay** [comment]
Because we were just told that images have a height and width and that this is their intrinsic size. Then we're told that divs don't have a size. And then we're told that they have an intrinsic size determined by their content. Well, I understand it all now. But whether a passage is clear or not just seems pretty obvious to me. And being told that some elements have an intrinsic size set by their height and width and some elements don't have a size but yet have an intrinsic size set by their textual content just isn't exactly on the same footing. These are not analogous cases. Being correct is not at all the same thing as being clear.
