### ISSUE TITLE
Issue with "Sizing items in CSS": (incorrectly correlated ideas)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#7098]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS

#### What information was incorrect, unhelpful, or incomplete?

> As an example, if you were to set width: 100% on an image, and its intrinsic width was smaller than its container, the image would be forced to stretch and become larger, causing it to look pixelated.
> 
> If you instead use max-width: 100%, and its intrinsic width was greater than its container, the image is able to become smaller than its container size, and will stop at 100% of its container size.

#### Specific section or headline?

min- and max- sizes

#### What did you expect to see?

The first condition is of an image being smaller than its container. The second condition is of an image being larger than its container. These don't both correlate to the property `max-width` in the same way. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/sizing_items_in_css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/sizing_items_in_css/index.html
* Last commit: https://github.com/mdn/content/commit/6077d5f480b2a404b21a405acc3dd1b66c1cb4ef
* Document last modified: 2021-03-31T04:51:23.000Z

</details>

**Comment by Anurella** [comment]
Suggested Solution,
The second paragraph needs to be rephrased to correlate to the first. 
"If you instead use max-width: 100% and its intrinsic width is smaller than its container, the image will not be forced to stretch and become larger  thus preventing pixelation. "

The example in the article matches up. 

@ConsciousClay is this what you mean ?

**Comment by ConsciousClay** [comment]
@Anurella Bingo, you got it 😉

There should be a comma between **larger** and **thus** \- "...become larger, thus preventing..."
