### ISSUE TITLE
Issue with "background-origin": …

### ISSUE THREAD

**Issue by Yuniac** [mdn/content#710]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-origin

#### What information was incorrect, unhelpful, or incomplete?
The 'Result' section/preview is missing on that page.

#### Specific section or headline?
At the bottom of the page

#### What did you expect to see?
The results section after the examples section.

#### Did you test this? If so, how?
no

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/background-origin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-origin
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/background-origin/index.html
* Report started: 2020-12-28T22:23:58.893Z

</details>

**Comment by rachelandrew** [comment]
Not every page has a live example, though I don't see any reason why this one shouldn't. I'll add it to my list.
