### ISSUE TITLE
Issue with "Sizing items in CSS": (unclear concept)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#7100]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS

#### What information was incorrect, unhelpful, or incomplete?

Sizing things according to the viewport can be useful in your designs. For example, if you want a full-page hero section to show before the rest of your content, making that part of your page 100vh high will push the rest of the content below the viewport, meaning that it will only appear once the document is scrolled.

#### Specific section or headline?

Viewport units

#### What did you expect to see?

What's a **hero section**? I don't recall hearing about this in the previous tutorials.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/sizing_items_in_css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/sizing_items_in_css/index.html
* Last commit: https://github.com/mdn/content/commit/6077d5f480b2a404b21a405acc3dd1b66c1cb4ef
* Document last modified: 2021-03-31T04:51:23.000Z

</details>

**Comment by rachelandrew** [comment]
It's a standard term used in design, in addition, the prose explains it as a "full-page hero section", therefore even if you removed "hero" the intent is pretty clear.
