### ISSUE TITLE
Issue with "PKCS11 module installation": No Preferences dialog or Advanced tab

### ISSUE THREAD

**Issue by rvernica** [mdn/content#7101]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/PKCS11/Module_Installation

#### What information was incorrect, unhelpful, or incomplete?

> Open the Firefox preferences dialog. Choose "Advanced" > "Encryption" > "Security Devices"
> Choose "Load"

There is no _preferences_ dialog. In _Settings_ there is no _Advanced_

Also, please given an on how the PKCS 11 module looks like (e.g., file extension) and where would it be normally found.

I got this error in Firefox:
![image](https://user-images.githubusercontent.com/241185/126389560-94e5d3b0-a5ca-46d5-973d-8ab7a717f8dc.png)

I Googled the error message and ended up on this page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/projects/nss/pkcs11/module_installation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/PKCS11/Module_Installation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/projects/nss/pkcs11/module_installation/index.html
* Last commit: https://github.com/mdn/content/commit/480402ddfc6be287e940c30d8039820f71ed8e98
* Document last modified: 2021-04-05T18:57:07.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #7120 with at fix.
