### ISSUE TITLE
Issue with "AggregateError": (there is no section/link/reference to property "errors")

### ISSUE THREAD

**Issue by InExtremaRes** [mdn/content#7106]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError

#### What information was incorrect, unhelpful, or incomplete?

There is an example referencing the property `e.errors` (where `e instanceof AggregateError`) but there is no section or reference for the property itself.

#### Specific section or headline?

[Instance properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError#instance_properties)

#### What did you expect to see?

A link where the instance property is documented.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/aggregateerror`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/aggregateerror/index.html
* Last commit: https://github.com/mdn/content/commit/3c394e62835ef7b443fb5208343ecba892bbf6d5
* Document last modified: 2021-05-26T11:36:38.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #7116 with a fix.
