### ISSUE TITLE
Issue with "Django Tutorial Part 8: User authentication and pe…": (short summary here please)

### ISSUE THREAD

**Issue by magelead** [mdn/content#7113]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication

#### What information was incorrect, unhelpful, or incomplete?

I found an unpaired parenthesis.

#### Specific section or headline?

if you search for `...locallibrary folders).`, you can find it easily.

#### What did you expect to see?

...locallibrary folders). => ...locallibrary folders.

#### Did you test this? If so, how?

NA.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/authentication`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/authentication/index.html
* Last commit: https://github.com/mdn/content/commit/a6dc8107f445786988e76b73c69a25ca4684496f
* Document last modified: 2021-07-12T06:29:04.000Z

</details>

**Comment by teoli2003** [comment]
Thanks, I have opened a PR to get it fixed.
