### ISSUE TITLE
Content bug: wrong word

### ISSUE THREAD

**Issue by logic-finder** [mdn/content#7141]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/PeriodicWave

## Specific page section or heading?

Example

## What is the problem?

AudioContext.createPeriodicWave()

Its link goes to **Base**AudioContext/createPeriodicWave#example.

## What did you expect to see?

AudioContext.createPeriodicWave()
→
BaseAudioContext.createPeriodicWave()

## Did you test this? If so, how?

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #7144 with a fix.
