### ISSUE TITLE
Issue with "Taking still photos with WebRTC": First link on the webpage broken

### ISSUE THREAD

**Issue by aaryanporwal** [mdn/content#7150]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos

#### What information was incorrect, unhelpful, or incomplete?
The "Try this sample" hyperlink is broken: https://mdn-samples.mozilla.org/s/webrtc-capturestill.

#### Specific section or headline?
First paragraph

![image](https://user-images.githubusercontent.com/54525904/126605294-86f230d8-3bd4-4219-96ea-83b7ce4d4164.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webrtc_api/taking_still_photos`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webrtc_api/taking_still_photos/index.html
* Last commit: https://github.com/mdn/content/commit/da2f6f9af33bad517ff6f3ac02234ba251d74076
* Document last modified: 2021-06-07T01:27:38.000Z

</details>

**Comment by reddymahendra52** [comment]
It's mostly because a few of the files were omitted from the repository and the source might be one of those files. That's what I think

**Comment by teoli2003** [comment]
In fact, the source are not missing, but the _sample server_ is dead and won't be resurrected.

**Comment by wbamberg** [comment]
See also https://github.com/mdn/content/discussions/5772. We really ought to address this :(.

**Comment by aaryanporwal** [comment]
Issue addressed on pr #7219, closing this.
