### ISSUE TITLE
Issue with "IDBTransaction":Example needs explanation

### ISSUE THREAD

**Issue by HelmZalee** [mdn/content#7160]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction

#### What information was incorrect, unhelpful, or incomplete?
Arguments passed to db.transaction in an example are unexplained.

#### Specific section or headline?
First js code example (under IDBTransaction), for example the line db.transaction("foo", "readwrite");

#### What did you expect to see? 
Anything describing the meaning of the arguments, esp "foo" (which turns out to be a store name, and a special case of that first argument, which otherwise would be a _list_, not a string).  A link to the "transaction" article i found (see below) would be useful here.

#### Did you test this? If so, how? 
Did not test, but answered my own question with a google search for _indexedDB transaction method_, found the mozilla article ...IDBDatabase/transaction, which provided a lucid explanation.

A link to that article would be useful to rank amateurs like me.

At the same time, I have to comment that this mechanism for commenting on articles is new to me.  Thank you for providing it.  Earlier alternatives seemed to offer the opportunity to edit the article, and no way was I going to do that. It's especially nice to be able to reference the tab where the question arose as I complete this form.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/idbtransaction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/idbtransaction/index.html
* Last commit: https://github.com/mdn/content/commit/e7a0bb19fe8960c2f3ee1a1d0f28e567b1219735
* Document last modified: 2021-06-14T00:14:09.000Z

</details>

**Comment by Josh-Cena** [comment]
This page assumes you are already somewhat familiar with the IDB API to recognize what `transaction` etc. do. If you don't recognize these methods, you need to start with one of the guides, such as https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB. We usually don't overexplain our examples in references, especially when they are not used to illustrate the main point.

It has been open for ~3years and no one seems motivated enough to fix it, so I'm going to close it as wontfix.
