### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection - Left column lists incorrect properties and methods.

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#7161]
@parke commented on [Fri Aug 07 2020](https://github.com/mdn/sprints/issues/3582)

# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

On the referenced page, the left "quick navigation" column incorrectly lists:

Properties
item

The correct list would be:

Properties
length

Methods
item()
namedItem()

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection

**Comment by teoli2003** [comment]
I opened a PR that will add the property `length` to the sidebar (it was missing a tag).
For `namedLength`, it will appear automatically when it will be documented.

**Comment by teoli2003** [comment]
This how the sidebar looks after #7162; not perfect but better.
<img width="245" alt="Screenshot 2021-07-22 at 20 15 40" src="https://user-images.githubusercontent.com/1466293/126688720-910ef090-3563-4e8c-88ce-a6426610ad27.png">
