### ISSUE TITLE
Issue with "Fetch API": (short summary here please)

### ISSUE THREAD

**Issue by Francisco-AM** [mdn/content#7163]
this api is listed but does not appear
https://developer.mozilla.org/en-US/docs/Web/API/Body

**Comment by teoli2003** [comment]
Hi! This was a "mixin" that is a set of properties and methods that are not an interface by themselves but used in another API.

On which page do you it listed?

**Comment by Francisco-AM** [comment]
> ¡Hola! Este fue un "mixin" que es un conjunto de propiedades y métodos que no son una interfaz en sí mismos, sino que se utilizan en otra API.
> 
> ¿En qué página aparece?
> 
> ¿En la barra lateral de este? https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API



Exactamente.

**Comment by teoli2003** [comment]
Thanks a lot for detecting it. I opened a PR to fix it, it should be merged today (and likely deployed tomorrow).

**Comment by Francisco-AM** [comment]
Thanks to you for the great documentation
