### ISSUE TITLE
Issue with "margin-top": (short summary here please)

### ISSUE THREAD

**Issue by bigboss978** [mdn/content#7167]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/margin-top

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/margin-top`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/margin-top
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/margin-top/index.html
* Last commit: https://github.com/mdn/content/commit/69f5a958188c2c631e7b125992e3048625737ff1
* Document last modified: 2021-06-29T03:43:37.000Z
.content { margin-top:   5%; }
.sidebox { margin-top: 10px; }
.logo    { margin-top: -5px; }
#footer  { margin-top:  1em; }

</details>

**Comment by bigboss978** [comment]
.content { margin-top:   5%; }
.sidebox { margin-top: 10px; }
.logo    { margin-top: -5px; }
#footer  { margin-top:  1em; }
let longString = "This is a very long string which needs \
to wrap across multiple lines because \
otherwise my code is unreadable."
let longString = "This is a very long string which needs " +
                 "to wrap across multiple lines because " +
                 "otherwise my code is unreadable."

**Comment by teoli2003** [comment]
Hi!

Unfortunately you didn't provide any clear information about the issue you are reporting. We cannot act on it.

I'm closing it. If you come back and provide more information, you are welcome to re-open it (or to fill a separate issue).

Thanks a lot for your interest!
