### ISSUE TITLE
Archive of obsolete content is not available

### ISSUE THREAD

**Issue by LummoxJR** [mdn/content#7174]
This should speak for itself, but going here delivers a 404:

https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XUL/Tutorial

All other XUL pages are unviewable as well. This is a problem because it does impact anyone styling XUL, for instance in userChrome.css.

**Comment by sideshowbarker** [comment]
alerting @mdn/core-dev but I believe this is intentional

**Comment by peterbe** [comment]
It's intentional. It's been planned for months and executed on last week. 
The old content is available here: https://github.com/mdn/archived-content/tree/main/files/en-us/archive/mozilla/xul/tutorial
The follow-up blog post is coming this week, I think @Rumyra

**Comment by LummoxJR** [comment]
That link is helpful. Thanks! I still needed the info but all the search engine links point to the old content rather than the archive.
