### ISSUE TITLE
Issue with "Element: mouseenter event": Event names are probably the wrong way round

### ISSUE THREAD

**Issue by fmeyertoens** [mdn/content#7185]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event

#### Specific section or headline?
On the mentioned page it says:

> A single `mouseover` event is sent to the deepest element of the DOM tree, then it bubbles up the hierarchy until it is canceled by a handler or reaches the root.
With deep hierarchies, the number of `mouseenter` events sent can be quite huge and cause significant performance problems. In such cases, it is better to listen for `mouseover` events.

#### What did you expect to see?
The first sentence seems to imply that the bubbling of the `mouseover` event causes more events than `mouseenter` which does not bubble. Therefore the two event names should be switched around in the second sentence.

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/mouseenter_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/mouseenter_event/index.html
* Last commit: https://github.com/mdn/content/commit/8455a83fd1ba95f5e8cb2fadebab82cd77111579
* Document last modified: 2021-06-12T21:26:13.000Z

</details>

**Comment by sideshowbarker** [comment]
Agreed, and thanks much for catching this — I’ve opened #7289 with a fix.

**Comment by fmeyertoens** [comment]
After thinking about this again, I also think @jelenicak is correct here. I originally thought that the sentence in question referred to the bubbling of the `mouseover` event (which doesn't actually create new events though).
I made a quick demo to get a good picture of the events myself: https://codepen.io/fmeyertoens/pen/vYeebzV
There are 2 scenarios there:
1. In order to reach "Content ca" you have to go through "a" and "ba". Therefore much more event listeners are triggered but the number of events is the same for `mouseenter` and `mouseover` (see the target column). This is the scenario I originally had in mind.
![image](https://user-images.githubusercontent.com/26410884/147290246-a1457a63-e5dd-400c-8213-0a1c7094dbe1.png)
2. "Content cb" can be reached directly and triggers a single bubbling `mouseover` event and three `mouseenter` events. This is the scenario that the mdn page is talking about.
![image](https://user-images.githubusercontent.com/26410884/147290348-48ee52b1-4542-4281-b50a-18f6f3032a73.png)

Therefore the change in https://github.com/mdn/content/pull/7289 should be reverted.
