### ISSUE TITLE
Issue with "Quirks Mode and Standards Mode": Some links point to broken URLs

### ISSUE THREAD

**Issue by dcriado** [mdn/content#7190]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

#### What information was incorrect, unhelpful, or incomplete?

Links "list of quirks" and "almost standards mode" point to broken URLs.

#### Specific section or headline?

These issues were found in the last section, named "What are the differences between the modes?".

#### What did you expect to see?

The pages pointed by the links.

#### Did you test this? If so, how?

By clicking on each of the broken links.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/quirks_mode_and_standards_mode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/quirks_mode_and_standards_mode/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by meowmeowmeowcat** [comment]
This is fixed by PR #7196.

**Comment by dcriado** [comment]
Awesome. Thank you!
