### ISSUE TITLE
Issue with "HTMLImageElement.srcset": Broken image link at end of document

### ISSUE THREAD

**Issue by davidrocharz** [mdn/content#7201]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset

#### What information was incorrect, unhelpful, or incomplete?
The image that is meant to be displayed in the 'Results' section at the bottom of the document is broken and not able to load.

#### Specific section or headline?
Section: Result
![image](https://user-images.githubusercontent.com/5697121/126793760-b8b4662c-28b4-463e-aea3-99da759446b6.png)

#### What did you expect to see?
The image loaded into the demo area

#### Did you test this? If so, how?
Yes, I confirmed that the image is 404'ing via the browser console

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlimageelement/srcset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlimageelement/srcset/index.html
* Last commit: https://github.com/mdn/content/commit/4e2911c4c9235788b269e5991ea343875c8f1508
* Document last modified: 2021-06-13T10:12:53.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #7290 with a fix.
