### ISSUE TITLE
404 Not found (broken link)

### ISSUE THREAD

**Issue by IsaacHub** [mdn/content#7204]
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules

Under section "Caching a wasm module"
The link to " indexeddb-cache.html" is dead. This html file is not present there.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/caching_modules`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/webassembly/caching_modules/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by meowmeowmeowcat** [comment]
This is fixed by PR #7215.
