### ISSUE TITLE
Issue with "Path2D": Experimental notice should be gone.

### ISSUE THREAD

**Issue by Kaiido** [mdn/content#7208]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Path2D

#### What information was incorrect, unhelpful, or incomplete?
This feature is supported by more than 2 engines and has stable standards specs for quite long, it thus should not have an Experimental notice.

#### Specific section or headline?
The Experimental notice.

#### What did you expect to see?
No Experimental notice.

#### Did you test this? If so, how?
No.

Of further note, https://github.com/mdn/browser-compat-data/blob/7c35ca11b459782aa6a766cf144f8cb3eeb195be/api/Path2D.json seems to tell this is not experimental, so there might be a problem in the pipes in between?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/path2d`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Path2D
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/path2d/index.html
* Last commit: https://github.com/mdn/content/commit/86b8b22f13d0185d97089c61d50a2229d22ddf4a
* Document last modified: 2021-06-15T05:22:45.000Z

</details>

**Comment by meowmeowmeowcat** [comment]
This is fixed by #7226.
