### ISSUE TITLE
Issue with "bookmarks.onMoved": Add bug with inconsistent indexing.

### ISSUE THREAD

**Issue by ShadedBlink** [mdn/content#7227]
In Firefox(91.0b6; most likely works in other versions) bookmark index is not a zero-based position inside parent folder, but a value, which is used to sort bookmarks. Why do I mention this obvious thing? It is possible to create a lot of same-indexed bookmarks, first bookmark can have index `-1`. I am not sure if this is a bug or a firefox intended behaviour, but I think that it should be noted in MDN.
How to reproduce this bug:
1. Create a bookmarks folder.
2. Populate it with 10-15 bookmarks.
3. Invoke this code to reorder them:
```
browser.bookmarks.getChildren(yourBookmarksFolderId).then(arr => {
let g = 0;
for(const i of arr.sort((x,y) => Math.random() - 0.5)){
console.log(i.title);
browser.bookmarks.move(i.id, {index:g++})
}
})
```
4. Wait a bit so reorder will be completed.
5. Run this code to check their indexes:
```
browser.bookmarks.getChildren(yourBookmarksFolderId).then(arr => console.log(arr.map(x => ({Id:x.id,Index:x.index}))))
```
Watch thoroughly on the list you have got. Last bookmark always has right index, but any previous can have duplicate indexes and first bookmark can start with `-1`. In some cases it is possible for two bookmarks to have `-1` simultaneously.
It should be mentioned somewhere since due to this bug it is absolutely impossible to track bookmarks order using events, you always have to call `browser.bookmarks.getChildren()` to get true order, but most likely it won't be executed till next `onMoved` event due to its asynchronous nature.

About how `onMoved` is called in this case:
![изображение](https://user-images.githubusercontent.com/40367408/126864892-725368c7-4c6b-4b48-8af5-1f4d8d481d01.png)

MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/onMoved

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/bookmarks/onmoved`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/onMoved
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/bookmarks/onmoved/index.html
* Last commit: https://github.com/mdn/content/commit/eb5d682cbe5664b933e793ff6434fb252686f3c3
* Document last modified: 2021-05-31T17:26:19.000Z

</details>

**Comment by rebloor** [comment]
@ShadedBlink as this is an asynchronous API have you tried using `await` to ensure that the process has finished before you exam in the indexes? Something along the lines of:
```
(async function () { 
  const arr = await browser.bookmarks.getChildren(yourBookmarksFolderId);

  for(...) {
    await browser.bookmarks.move(i.id, {index:g++})
  }
});
```

**Comment by ShadedBlink** [comment]
@rebloor , yeah, I have tried and it works right with `await`. Still it is pretty confusing that this method has such vulnerability against racing requests.
