### ISSUE TITLE
"List of Proprietary CSS Features" needs attention

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#7235]
https://developer.mozilla.org/en-US/docs/web/css/list_of_proprietary_css_features starts with a warning:

> Warning: This page is incomplete and out of date. Please see the following for more current information:
>
> Microsoft CSS Extensions
> Mozilla CSS Extensions
> WebKit CSS Extensions

...followed by a very draft-y collection of lists.

If those pages are really better, this page should just be made to link to them.

**Comment by rachelandrew** [comment]
I don't know why we have this page. It doesn't seem very useful. I could rewrite it to explain what these prefixed features are and then link to the other pages.

I'm not sure how complete they are, however. The `-ms` page doesn't seem to include `-ms-grid` for example.

**Comment by teoli2003** [comment]
I think we should just make it a redirect to https://developer.mozilla.org/en-US/docs/Web/CSS/Reference.
