### ISSUE TITLE
Issue with "Unicode property escapes": "much more characters" should be "many more characters"

### ISSUE THREAD

**Issue by fwextensions** [mdn/content#7242]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes

#### What information was incorrect, unhelpful, or incomplete?

In standard English, "much" is used with singular nouns, like "much fanfare", whereas "many" is used with plural nouns, like "many characters".

#### Specific section or headline?

"much more characters" is used twice in the text.

#### What did you expect to see?

"many more characters"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions/unicode_property_escapes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/unicode_property_escapes/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by teoli2003** [comment]
Thanks a lot. I've opened a PR to fix it.
