### ISSUE TITLE
[Markdown] [CSS] Fix usages of <div class="hidden"> containing code blocks

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#7256]
This is part of https://github.com/mdn/content/issues/5865.

In preparing CSS docs for Markdown conversion we'd like to remove occurrences of `<div class="hidden">`. There are two main usages of this pattern:

1. to include comments for editors, like the comments attached to interactive examples
2. to hide code blocks that the author wants to participate in live samples, but doesn't want the reader to see

This issue to about removing instances of the second category. The fix in this case is to:

* move the `hidden` class from the `<div>` and attach it directly to the `<pre>` blocks that the `<div>` contains
* delete any other stuff in the `<div>`, having checked that it's not important*
* remove the `<div>` tags

This will work in Markdown because we support [info strings](https://github.github.com/gfm/#info-string) on code blocks, and we will support `hidden` as a value in there: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#example_code_blocks.

For example, given this (from https://developer.mozilla.org/en-US/docs/Web/CSS/align-content#examples):

```
<h2 id="Examples">Examples</h2>

<h3 id="CSS">CSS</h3>

<pre class="brush: css">
...CSS content skipped for brevity...
</pre>

<h3 id="HTML">HTML</h3>

<pre class="brush: html">
...HTML content skipped for brevity...
</pre>

<div class="hidden">
<h3 id="JavaScript">JavaScript</h3>

<pre class="brush: js">
...JS content skipped for brevity...
</pre>
</div>

<h3 id="Result">Result</h3>

<p>{{EmbedLiveSample("Examples", 260, 290)}}</p>
```

...we would instead do:

```
<h2 id="Examples">Examples</h2>

<h3 id="CSS">CSS</h3>

<pre class="brush: css">
...CSS content skipped for brevity...
</pre>

<h3 id="HTML">HTML</h3>

<pre class="brush: html">
...HTML content skipped for brevity...
</pre>

<pre class="brush: js hidden">
...JS content skipped for brevity...
</pre>

<h3 id="Result">Result</h3>

<p>{{EmbedLiveSample("Examples", 260, 290)}}</p>
```

* Note "delete any other stuff in the `<div>`, *having checked that it's not important*". The only case I can think of here is where the other stuff, such as headings, is providing an ID that the live sample can reference. Then deleting the heading will break the live sample. There definitely were some of these in the CSS docs but I think I fixed them all. Still worth checking though.

I believe these are all the pages under CSS which hide code blocks in a hidden `<div>`:

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke-color/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style/system/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/aspect-ratio/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/_colon_empty/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/_doublecolon_file-selector-button/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/_doublecolon_selection/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/align-content/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/align-items/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/attr()/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-repeat/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix()/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/contain/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/containing_block/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_animations/tips/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_background_and_borders/border-image_generator/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_background_and_borders/border-radius_generator/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_background_and_borders/box-shadow_generator/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_colors/color_picker_tool/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout/auto-placement_in_css_grid_layout/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout/basic_concepts_of_grid_layout/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout/box_alignment_in_css_grid_layout/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout/css_grid_and_progressive_enhancement/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout/css_grid_layout_and_accessibility/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout/css_grid_logical_values_and_writing_modes/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout/grid_template_areas/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout/layout_using_named_grid_lines/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout/line-based_placement_with_css_grid/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout/realizing_common_layouts_using_css_grid_layout/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_grid_layout/relationship_of_grid_layout/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/css_images/using_css_gradients/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/flex/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/font/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/font-style/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/conic-gradient()/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient()/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/radial-gradient()/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-conic-gradient()/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-linear-gradient()/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-radial-gradient()/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-end/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-start/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row-end/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row-start/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/place-content/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/place-items/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/rotate/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/text-align-last/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/text-justify/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/tools/linear-gradient_generator/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/url()/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space/index.html
https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode/index.html

(there might be some I missed because of code blocks that use bogus classes, like "brush:css" rather than "brush: css".)

**Comment by meowmeowmeowcat** [comment]
Hi, I would like to work on this issue!

**Comment by meowmeowmeowcat** [comment]
Refers to #7288.
