### ISSUE TITLE
[Markdown] [CSS] Handle `sup` and `sub` in the CSS docs

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#7267]
This is part of https://github.com/mdn/content/issues/5865.

The guide to [using Markdown in MDN](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#superscript_and_subscript) says:

> Writers will be able to use the HTML \<sup> and \<sub> elements if necessary, but should use alternatives if possible

So we should look through the places in the CSS docs where we are using these elements, and decide whether it would be better to use one of the alternatives.

Here's the list of pages that use `<sub>`:

https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape
https://developer.mozilla.org/en-US/docs/web/css/easing-function

Here's the list of pages that use `<sup>`:

https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric
https://developer.mozilla.org/en-US/docs/Web/CSS/integer
https://developer.mozilla.org/en-US/docs/Web/CSS/ratio
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/matrix()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/matrix3d()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/perspective()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate3d()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotatex()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotatey()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotatez()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale3d()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scalex()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scaley()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scalez()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/skew()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/skewx()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/skewy()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate3d()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translatex()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translatey()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translatez()

It's a matter of judgment in a lot of cases what to do. Previous PRs that do this for different areas of MDN:

https://github.com/mdn/content/pull/5766 (for Web/API)
https://github.com/mdn/content/pull/5128 (for JS)

**Comment by rachelandrew** [comment]
I'm just working through these now.
