### ISSUE TITLE
Content bug: broken link for /en-US/docs/Web/JavaScript/about_javascript#_flaws

### ISSUE THREAD

**Issue by hochan222** [mdn/content#7271]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/about_javascript#javascript_resources

![image](https://user-images.githubusercontent.com/22424891/126937756-95e594e9-fd1e-4c68-ae5f-a0878047ed39.png)

- broken link list
  - SpiderMonkey
  - Rhino 

## What is the problem?

JavaScript resources

## What did you expect to see?

That page must exist.

## Did you test this? If so, how?

none

**Comment by teoli2003** [comment]
I opened a PR that fixes the link in the paragraph about engines, and removed the links from "more info", as it is not really useful if you only want to use JS.
