### ISSUE TITLE
Content bug: `/en-US/docs/Storage` link broken, /Web/JavaScript/data_structures

### ISSUE THREAD

**Issue by hochan222** [mdn/content#7300]
## What page(s) did you find the problem on?

The following link is broken. `/en-US/docs/Storage`

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/data_structures

## Specific page section or heading?

String type

https://developer.mozilla.org/en-US/docs/Web/JavaScript/data_structures#string_type

## What is the problem?

The following link is broken. `/en-US/docs/Storage`

- **Not found:** https://developer.mozilla.org/en-US/docs/Storage

---

<img src="https://user-images.githubusercontent.com/22424891/127028661-b1627c04-c1dd-42f4-a833-1b3c53d1b476.png" height="150px" />

## What did you expect to see?

The `/en-US/docs/Storage` page must exist. 

## Did you test this? If so, how?

no

**Comment by sideshowbarker** [comment]
Thanks — I opened #7301 with a fix.
