### ISSUE TITLE
Content bug: markdown unconverted /javascript/web/equality_comparisons_and_sameness

### ISSUE THREAD

**Issue by hochan222** [mdn/content#7303]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#when_to_use_object.is_versus_triple_equals

## Specific page section or heading?

When to use Object.is versus triple equals

## What is the problem?

markdown unconverted

```html
<dl><dt><a href="/en-US/docs/Web/JavaScript/Reference/Operators#-_.28unary_negation.29"><code>- (unary negation)</code></a></dt><dd><pre class="brush: js">let stoppingForce = obj.mass * -obj.velocity;</pre><p>If <code>obj.velocity</code> is <code>0</code> (or computes to <code>0</code>), a <code>-0</code> is introduced at that place and propagates out into <code>stoppingForce</code>.</p></dd></dl>
```

![image](https://user-images.githubusercontent.com/22424891/127035934-b3a83982-3f2b-4e0f-9046-e68c252ee428.png)

## What did you expect to see?

html converted to GFM

maybe like this!

```
- [-(unary negation)](/ko/docs/Web/JavaScript/Reference/Operators#-_.28unary_negation.29)
  - ```js
    let stoppingForce = obj.mass * -obj.velocity;
    ```
    If `obj.velocity` is `0` (or computes to `0`), a `-0` is introduced at that place and propagates out into `stoppingForce`.
```

## Did you test this? If so, how?

http://127.0.0.1:3000/ko/docs/Web/JavaScript/Equality_comparisons_and_sameness#_flaws

![image](https://user-images.githubusercontent.com/22424891/127036594-fe95ab71-11cc-4627-aa25-62df36f1af7c.png)

<!-- Please provide any steps you took to test the problem, if appropriate  -->

**Comment by sideshowbarker** [comment]
alerting @wbamberg

**Comment by wbamberg** [comment]
Thanks for the ping! I think this is https://github.com/mdn/yari/issues/4307.

This `dl` element is also unconverted in the en-US docs: https://raw.githubusercontent.com/mdn/content/main/files/en-us/web/javascript/equality_comparisons_and_sameness/index.md and we probably ought to fix it there too.

(actually, in the places I've seen this, it always looks like a content problem fundamentally - a `<dd>` ought to begin with some text explaining what the thing is, and only then having a code block. But still, I think the converter ought to handle the case.)

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/content/issues/7303 :)
