### ISSUE TITLE
Content bug: `Worker.prototype.postMessage` is mistakenly said to block the receiving thread

### ISSUE THREAD

**Issue by andreubotella** [mdn/content#7315]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage

## Specific page section or heading?

Second paragraph in the introduction.

## What is the problem?

The MDN article mentions that `Worker.prototype.postMessage()` "blocks the thread that receives the message" (presumably the worker's thread). That is not true: [`Worker.prototype.postMessage`](https://html.spec.whatwg.org/multipage/workers.html#dom-worker-postmessage) delegates to [`MessagePort.prototype.postMessage`](https://html.spec.whatwg.org/multipage/web-messaging.html#dom-messageport-postmessage), which doesn't block any thread – instead it adds a task on the event loop corresponding to the receiving `MessagePort` (step 7 in [the message port post message steps](https://html.spec.whatwg.org/multipage/web-messaging.html#message-port-post-message-steps)).

## What did you expect to see?

That paragraph shouldn't be there.

## Did you test this? If so, how?

I don't think there's any way to test that _the worker thread_ blocks, since that doesn't seem to make much sense – the worker might be in the middle of a task at the moment `postMessage()` is called.

If there was any blocking involved, you'd instead expect that the call to `postMessage()` would block _the originating thread_ until the message is received, but that clearly doesn't happen, as the following example shows:

```js
const worker = new Worker("./worker.js");
console.log("%s Worker created", new Date().toISOString());
for (let i = 0; i < 10; i++) {
  worker.postMessage(i);
  console.log("%s Message %d sent.", new Date().toISOString(), i);
}
```

```js
// worker.js
self.onmessage = (evt) => {
  console.log("%s Received message %d.", new Date().toISOString(), evt.data);
};
```

In my testing across different browsers, every single sent message was printed before the first received message, so `postMessage()` doesn't block the current thread.

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #7327 with a fix.
