### ISSUE TITLE
Issue with "Transformations": transformation matrix not rendered correctly

### ISSUE THREAD

**Issue by hacker-eleos** [mdn/content#7321]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Transformations

#### What information was incorrect, unhelpful, or incomplete?
\left[ \begin{array}{ccc} a & c & e \\ b & d & f \\ 0 & 0 & 1 \end{array} \right]
Transformation matrix equation is not rendered perhaps we missed something.

#### Specific section or headline?
Transforms sections
https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/transformations/index.html  line 224

#### What did you expect to see?
I don't know. Probably a matrix I guess.

#### Did you test this? If so, how?
I can see it on the live mdn page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvas_api/tutorial/transformations`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Transformations
* GitHub URL: https://github.com/mdn/content/blob/7299/merge/files/en-us/web/api/canvas_api/tutorial/transformations/index.html
* Last commit: https://github.com/mdn/content/commit/null
* Document last modified: 2019-03-23T23:28:25.576Z

</details>

**Comment by hacker-eleos** [comment]
![image](https://user-images.githubusercontent.com/63001252/127101135-b7256d9a-502d-40d9-90f3-507f1bc62c9d.png)

**Comment by Amritanshu02** [comment]
Hello! I would like to work on this issue, could you suggest me where to start?

**Comment by hacker-eleos** [comment]
@Amritanshu02  https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/transformations/index.html line 224.

**Comment by sideshowbarker** [comment]
@hacker-eleos Is this not a duplicate of https://github.com/mdn/content/pull/7299?

If the problem is that you don’t see the #7299 change reflected yet at https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Transformations, then the answer is, it’s expected that the change would not show up in the production site. I can take up to 48 hours before changes that get merged actually get deployed to the production site.

**Comment by hacker-eleos** [comment]
@sideshowbarker  I thought the issue is still not fixed. It explains the delay in the production site but I still don't see the equation rendered correctly in the preview. See here the preview 

https://pr7299.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Canvas_API/Tutorial/Transformations

**Comment by teoli2003** [comment]
@hacker-eleos Do you check this in a browser supporting `<mathml>`? I think we don't have the polyfill for non-mathml loaded anymore.

**Comment by hacker-eleos** [comment]
@teoli2003 @sideshowbarker  Thanks for the direction. Now it is clear. I am using Edge so it is not rendered correctly. I just checked in Chrome, not rendered correctly either. It works in firefox well. Attached is the screenshot for `mathml` browser compatibility.

But I guess we still have to fix the issue for chrome at least considering the fact vast chunk of viewers uses Chrome for browsing.

Any work around for the issue?
Reference: https://developer.mozilla.org/en-US/docs/Web/MathML#browser_compatibility

![image](https://user-images.githubusercontent.com/63001252/127127909-ffe289a6-f021-4e19-8d10-f2214a3d4883.png)

**Comment by hacker-eleos** [comment]
@teoli2003 In case we don't have polyfill for mathml, I will close the issue?
What do you think?

**Comment by teoli2003** [comment]
Yes, you can. It will be fixed when mdn/yari#4222 lands (no ETA, though)

**Comment by hacker-eleos** [comment]
Alright. Sounds good. Closing the issue. Thanks for your time.
