### ISSUE TITLE
Issue with "<template>: The Content Template element": (click event doesn't show an alert)

### ISSUE THREAD

**Issue by davayd** [mdn/content#7329]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

#### What information was incorrect, unhelpful, or incomplete?
The information in 'Result' section doesn't match with below example result

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template#result

#### What did you expect to see?
By clicking on second <div>Click me</div> expected to see alert message

#### Did you test this? If so, how?
1. Click on first <div>Click me</div> works as expected (alert message is not showed)
2. Click on second <div>Click me</div> doesn't show an alert message

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/template`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/template/index.html
* Last commit: https://github.com/mdn/content/commit/8d28de329fc4f723ad4362f0f703e46c4fa9e32d
* Document last modified: 2021-06-02T17:52:41.000Z

</details>

**Comment by sideshowbarker** [comment]
Dmitry, thanks very much for raising this.

For the record here, the reason for this is:

> A different origin subframe tried to create a JavaScript dialog. This is no longer allowed and was blocked. See https://www.chromestatus.com/feature/5148698084376576 for more details.

I’ve opened #7351 with a fix.
