### ISSUE TITLE
Issue with "Arrow function expressions": …

### ISSUE THREAD

**Issue by bergus** [mdn/content#733]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#this_and_Arrow_Functions

#### What information was incorrect, unhelpful, or incomplete?

> Traditional functions default this to the window scope
> […]
> Arrow functions do not default this to the window scope

is wrong and [confusing](https://stackoverflow.com/questions/65493314/what-is-the-scope-of-this-in-the-arrow-functions-in-javascript).
Only sloppy-mode `function`s default an `undefined`/`null` this argument to the global object. Strict-mode `function`s (the new default in modules!) do not.

#### What did you expect to see?

This should not be mentioned at all in the arrow function documentation, it's irrelevant because it does not apply to them at all.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/functions/arrow_functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/functions/arrow_functions/index.html
* Report started: 2020-12-29T15:25:09.743Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. I opened https://github.com/mdn/content/pull/747 with a patch which just drops that entire subsection.
