### ISSUE TITLE
Issue with "cookies.onChanged": browser and cookies is not defined. Doesn't work according to the compatibility sheet.

### ISSUE THREAD

**Issue by gopkumargopi** [mdn/content#7341]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged

#### What information was incorrect, unhelpful, or incomplete?
This document is either outdated or simply doesn't work as illustrated. The `browser` object is not available at least in the global scope of the latest Chrome or Firefox. A workaround as mentioned [here](https://stackoverflow.com/questions/64330672/referenceerror-browser-is-not-defined) defines the browser object. But it still doesn't have the cookies API. Neither the cookies API is available globally in browser.

#### What did you expect to see?
More information is required as to the scope of the browser object. Or a simple example that is supposed to work on any browser.

#### Did you test this? If so, how?
I tested it by typing the object name in the developer tools console. But after finding it also undefined when used in my app.

Update
Look at the [test fiddle here](https://jsfiddle.net/rgqk2h9b/2/).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/cookies/onchanged`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/cookies/onchanged/index.html
* Last commit: https://github.com/mdn/content/commit/eb5d682cbe5664b933e793ff6434fb252686f3c3
* Document last modified: 2021-05-31T17:26:19.000Z

</details>

**Comment by evilpie** [comment]
`browser` and the `browser.cookies` API is only available in [extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) that can be installed in Firefox and other browsers.

Your fiddle is running in a normal webpage, so it won't have access to any of these APIs.

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/7341#issuecomment-888113973
