### ISSUE TITLE
Issue with "eval()": what does "performance buttering" mean?

### ISSUE THREAD

**Issue by theredpea** [mdn/content#7357]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval

#### What information was incorrect, unhelpful, or incomplete?
I don't understand what "performance buttering means"

#### Specific section or headline?

> Function() more easily allows your code to utilize the performance buttering "use strict";

#### What did you expect to see?
I just don't know , what does this mean: "performance buttering"
Maybe "performance bettering" / "performance improvement?

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/eval`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/eval/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #7377 with a fix.
