### ISSUE TITLE
Issue with "Using dns-prefetch": Ideal placement of `link` tag is unclear

### ISSUE THREAD

**Issue by Lalee10** [mdn/content#7383]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch

#### What information was incorrect, unhelpful, or incomplete?
The placement of `link` with rel attribute is not very clear. The comment in the example says that it should be above all other head elements but it is not clear if those head elements also include meta charset and viewport tags?

#### Specific section or headline?
Examples

#### What did you expect to see?
Expected to see what the ideal placement of the `link` element could be along with other common `meta` elements.

#### Did you test this? If so, how?
I placed the link tags at the very top of the head above the `meta` charset tag but some SEO experts I was working with flagged this as an incorrect placement. They said that nothing should be placed before the meta charset and meta viewport tags.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/performance/dns-prefetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/performance/dns-prefetch/index.html
* Last commit: https://github.com/mdn/content/commit/3659d6683a109a89ac9bebcf492a9e7591e111f3
* Document last modified: 2021-07-03T23:13:43.000Z

</details>

**Comment by Anurella** [comment]
@Lalee10 The best placement is after the `meta` charset and viewport tag. The example will be updated to reflect it.

**Comment by Lalee10** [comment]
Thanks! @Anurella

**Comment by AnilSeervi** [comment]
This issue can be closed right? It has been solved in #7463 @sideshowbarker

**Comment by sideshowbarker** [comment]
@AnilSeervi, yep — thanks much! Closing now
