### ISSUE TITLE
Issue with "WebAssembly.instantiate()": more information is needed

### ISSUE THREAD

**Issue by tiuvi** [mdn/content#7384]
Inaccurate documentation.
1 - File is required in c or c ++
2 - emscripten command to compile the file
3 - Javascript code.

The github is all messed up

MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiate
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly

**Comment by himanshugarg** [comment]
Hi @Francisco-AM . Is the issue on this page - [WebAssembly.instantiate()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiate)? Sorry it is not obvious what the issue is? Would you like to add more details?

**Comment by Francisco-AM** [comment]
I think more information is needed to understand webassembly

You can provide the wat code

(module
  (func $imports.imported_func (;0;) (import "imports" "imported_func") (param i32))
  (func $exported_func (;1;) (export "exported_func")
    i32.const 42
    call $imports.imported_func
  )
)


https://webassembly.github.io/wabt/demo/

and a tool for example for its transformation wat to wasm

I clone the whole project to carry out the examples but I think that with this the documentation would be more accurate.

**Comment by Josh-Cena** [comment]
It has been two years and it seems we don't have enough bandwidth to polish our Wasm docs. This is a reference page, which assumes you already know how to compile to Wasm binaries. Please read https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_Wasm instead.
