### ISSUE TITLE
video call can not support

### ISSUE THREAD

**Issue by KU5891** [mdn/content#7388]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/security/secure_contexts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/security/secure_contexts/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by hamishwillee** [comment]
There is not enough information here for us to understand the problem, and hence potential solutions.

I'm therefore going to close, but if you can provide more specific information about the problem, feel free add it and then reopen this issue.
