### ISSUE TITLE
Issue with "Date.prototype.toLocaleDateString()": Norwegian locale "nb-NO", "nn-NO" not working in Chrome

### ISSUE THREAD

**Issue by rittikdey** [mdn/content#7389]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

#### What information was incorrect, unhelpful, or incomplete?
Trying to display month names in Norwegian - specifying locale defaults to english on Chrome.  This used to work earlier, but stopped working during the summer.  Works in Safari.

#### What did you expect to see?
Expected date format to be Norwegian

#### Did you test this? If so, how?
```
let date = new Date("03/01/2021");
console.log(date.toLocaleDateString('nb-NO', {month: 'long'}))
```
Result: **March**
Expected: **Mars**

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/tolocaledatestring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by hamishwillee** [comment]
The page does not include the code you are demonstrating. We can't help you with bugs in particular browsers as this is a tracker for MDN content.

Note however that running your test code on Chrome 91.0.4472.164 (Official Build) (64-bit) works fine on Windows. 
![image](https://user-images.githubusercontent.com/5368500/127453900-0d86223e-1165-4db9-ac7e-81bd1769df82.png)

Please post the issue on the chrome bug tracker, including version information for the build you are using

Closing this now - feel free to reopen if I am misinterpreting you.
