### ISSUE TITLE
Change 'semantic' to 'semantics'

### ISSUE THREAD

**Issue by tannerdolby** [mdn/content#7400]
Although semantic is defined as: "relating to meaning in language or logic"

Typically when discussing the language/linguistics of something, I've read & heard "semantics". This is super nit-picky but when I was reading this page earlier today while looking at the updated styling for `.callout` containers, it sort of read funny as I was expecting "semantics". 

https://developer.mozilla.org/en-US/docs/Web/JavaScript

<img width="883" alt="Screen Shot 2021-07-27 at 4 31 25 PM" src="https://user-images.githubusercontent.com/48612525/127240682-ac3aa0ac-b86d-43bf-bf59-c138fa1deb0a.png">

Replace "However, the two programming languages have very different syntax, semantic, and use." with:

> "However, the two programming languages have very different syntax, semantics, and use."

Thoughts? @peterbe @schalkneethling

**Comment by peterbe** [comment]
@tannerdolby I think you should simply make a PR on https://github.com/mdn/content/edit/main/files/en-us/web/javascript/index.md and move the discussion to the PR when it's been created. Good catch!

**Comment by tannerdolby** [comment]
@peterbe Agreed. I just submitted the PR and linked to this issue. Closing here as we can move the discussion over to `mdn/content`. Thanks!

**Comment by peterbe** [comment]
You forgot to say "Fixes #7400" in the [PR](https://github.com/mdn/content/pull/7401) :)

**Comment by tannerdolby** [comment]
Woops! :) I haven't forgotten to do that in quite some time haha. I apologize 😄
