### ISSUE TITLE
The GitHub action for PR template could add a bit on 'Fixes #X' at the top for consistency

### ISSUE THREAD

**Issue by tannerdolby** [mdn/content#7404]
## What is the problem?
The GitHub action in `.github` for `PULL_REQUEST_TEMPLATE` mentions to first provide a reason for why the fix was needed, and directly after that asks to provide an associated issue number. Would it be worthwhile to add another blockquote above the first one saying `> Issue to be fixed (for example Fixes #123)` therefore, contributors (myself included) don't forget to add the bit on what associated issue is going to be fixed.

```
<!-- Please provide the following information to help us review this PR: -->

> What was wrong/why is this fix needed? (quick summary only)

> Issue number (if there is an associated issue)

> Anything else that could help us review it
```

It's nice to have the second blockquote requesting us to provide an associated issue but it sort of makes me feel like I shouldn't need to say "Fixes 'X'" if I've already included a link to the issue and GitHub will include it in the "Linked issues".

My proposal:

Add a new blockquote to the top of the PR template stating: 
```
> Issue number to be fixed (ie Fixes #123, if there is an associated issue)
``` 
and remove the blockquote that states `> Issue number (if there is an associated)` since we can blend the two together and get two-birds with one stone.

## What did you expect to see?
Not so much that I expected to see it, but when I submit a PR it usually is closing/fixing a related issue so before writing anything I (try to) add "Fixes #issueNumber" and then move along with the other PR details. So it would look like this:

```
<!-- Please provide the following information to help us review this PR: -->

> Issue number to be fixed (ie 'Fixes #123', if there is an associated issue)

> What was wrong/why is this fix needed? (quick summary only)

> Anything else that could help us review it
```

This way, new contributors (and current ones) are always "prompted/encouraged" to put "Fixes #123" at the top of the PR every time. Reducing the amount of times its forgotten.

**Comment by tannerdolby** [comment]
Thoughts? @peterbe @wbamberg

**Comment by wbamberg** [comment]
@tannerdolby , this seems like a good suggestion to me :).
