### ISSUE TITLE
Content bug: constraint validation example/demo doesn't work

### ISSUE THREAD

**Issue by JasonWoof** [mdn/content#7407]
This demo doesn't work: (it just shows the default validation failure message)

https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/input/_sample_.Client-side_validation.html?name=a

That demo is embedded in an iframe here:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#example

The demo fails to work because the html has an extra input element that shouldn't exist. It's an `<input type="time" ...>` element that's not even inside the form.

I tried pausing javascript with the debugger, reloading, deleting that extraneous input element, then resuming javascript, and that made the validator message customizations work as described.

**Comment by wbamberg** [comment]
Thanks for filing @JasonWoof ! I just opened https://github.com/mdn/content/pull/7408 with a fix.

**Comment by wbamberg** [comment]
You should be able to see the working example here: https://pr7408.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/input#custom_validation_error_example.

**Comment by JasonWoof** [comment]
Oh, it pulls the code off the page itself! No wonder I couldn't find that code anywhere else :)

Your PR preview works for me:
https://pr7408.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/input#custom_validation_error_example

Thanks!
