### ISSUE TITLE
InheritanceDiagram of Window is incorrect

### ISSUE THREAD

**Issue by trusktr** [mdn/content#7411]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Window

## What is the problem?

It should show `EventTarget <- Window`.

## Did you test this? If so, how?

```js
console.log(window.__proto__.__proto__.__proto__.constructor) // EventTarget
```

---

How does one edit what the `{{InheritanceDiagram}}` shows?

**Comment by teoli2003** [comment]
Thanks!

Confirmed by https://html.spec.whatwg.org/multipage/window-object.html#the-window-object.

I'll open a PR in mdn/yari.

**Comment by teoli2003** [comment]
PR open: you need to edit a json file in mdn/yari to fix what the macro displays.
