### ISSUE TITLE
Issue with "Basic math in JavaScript — numbers and operators": (short summary here please)

### ISSUE THREAD

**Issue by Womoemy** [mdn/content#7414]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math

#### What information was incorrect, unhelpful, or incomplete?
Links to reference pages

#### Specific section or headline?
Every section

#### What did you expect to see?
Links to reference pages opening in a new tab.

#### Did you test this? If so, how?
I clicked through all the links.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/math`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/math/index.html
* Last commit: https://github.com/mdn/content/commit/f06e7641c6ceb49f6dad06bc223699f658906eae
* Document last modified: 2021-06-03T02:16:28.000Z

</details>

**Comment by teoli2003** [comment]
Hi, @Womoemy!

Thanks a lot!

Where do you think we should add the links, on the operator in each tables?

**Comment by Womoemy** [comment]
The placement of the links are okay.
But I feel it would be better if when the links are clicked they open the
linked page in a new tab.
It helps one retain concentration on what's being studied.
Thanks.

**Comment by teoli2003** [comment]
Opening a link in a new tab often gets people lost: they don't know how to get back, especially on mobile browsers.
For the people who want to do so, your browser has an "Open link in a new tab…" option.

See for example, https://uxdesign.cc/linking-to-a-new-tab-vs-same-tab-f88b495d2187

I will let a second opinion here, but I think we shouldn't.

**Comment by hamishwillee** [comment]
Closing. @teoli2003 gives good reasons, and this reflects MDN "policy".

**Comment by Womoemy** [comment]
Oh yeah, I get it now.
That's  true, it would be an issue on mobile. I have been using the site on
my laptop.
Thanks for the clarification 🤠
