### ISSUE TITLE
Issue with "Request header": (short summary here please)meowgrowl!!!!!Lol

### ISSUE THREAD

**Issue by Deskbotxxxtop** [mdn/content#7415]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Request_header

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/request_header`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Request_header
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/request_header/index.html
* Last commit: https://github.com/mdn/content/commit/22e05c803b551280f8559904c370f4bc39852c38
* Document last modified: 2021-05-19T00:54:04.000Z

</details>

**Comment by Deskbotxxxtop** [comment]
> 
https://developer.mozilla.org/en-US/docs/Glossary/Request_header
>

**Comment by hamishwillee** [comment]
Closing, as no actual problem has been described.
