### ISSUE TITLE
Issue with "Test your skills: Math": (short summary here please)

### ISSUE THREAD

**Issue by michael-odonovan** [mdn/content#7419]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Math

#### What information was incorrect, unhelpful, or incomplete?
True — elephants weight less than mice!?
The above sentence returns in the dialogue box when you have the answer correct and it is grammatically incorrect. The word should be "weigh" instead of "weight". Also adding "do weigh" would be nicer.

#### Specific section or headline?
change:
True — elephants weight less than mice!?
to
True — elephants do weigh less than mice!?

#### What did you expect to see?
True — elephants do weigh less than mice!?

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/test_your_skills_colon__math`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Math
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/test_your_skills_colon__math/index.html
* Last commit: https://github.com/mdn/content/commit/88b8dc61828f0c111b5eda4197921dcf153f3b0f
* Document last modified: 2020-12-15T16:53:05.000Z

</details>

**Comment by Ryuno-Ki** [comment]
This issue might need a transfer from `mdn/content` to `mdn/learning-area`:

https://github.com/mdn/learning-area/blob/442c07afb8fb3f0759fd4ed9db58971cba8f60d2/javascript/introduction-to-js-1/tasks/math/math3-download.html#L51

seem to contain the line in question.
