### ISSUE TITLE
GainNode article recommends against constructor usage

### ISSUE THREAD

**Issue by max-vogler** [mdn/content#7426]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/GainNode

#### What information was incorrect, unhelpful, or incomplete?
The GainNode article recommends against using the constructor `new GainNode` and for using the factory function `context.createGain` without giving clear reasons.

#### Specific section or headline?
> You shouldn't manually create a gain node; instead, use the method BaseAudioContext.createGain.
https://developer.mozilla.org/en-US/docs/Web/API/GainNode#constructor

> Note: You should typically call BaseAudioContext.createGain to create a gain node.
– https://developer.mozilla.org/en-US/docs/Web/API/GainNode/GainNode

#### What did you expect to see?
The constructor [new GainNode](https://caniuse.com/mdn-api_gainnode_gainnode) is now widely supported in the latest browser versions. Noteworthy, the factory function [createGain()](https://caniuse.com/mdn-api_baseaudiocontext_creategain) has a little better browser support, due to having been implemented in Safari for a longer time.

[W3C TAG discussions from 2013](https://github.com/w3ctag/design-reviews/blob/main/2013/07/WebAudio.md#issue-constructibility--de-sugaring-of-static-methods) indicate that the constructor should be preferred over the factory function because it allows subclassing, allows understanding how construction works, is more idiomatic and allows easy passing in of arguments.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/gainnode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/GainNode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/gainnode/index.html
* Last commit: https://github.com/mdn/content/commit/6e968ae20750e6611ab0dc76063f178d07aac974
* Document last modified: 2021-06-22T04:40:01.000Z

</details>

**Comment by max-vogler** [comment]
I'll gladly send PRs to update the MDN pages if there is no objection.

**Comment by sideshowbarker** [comment]
Max, thanks for raising this — please to do ahead and create a PR
