### ISSUE TITLE
Issue with "How do you set up a local testing server?": (short summary here please)

### ISSUE THREAD

**Issue by WildOne777** [mdn/content#7432]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server

#### What information was incorrect, unhelpful, or incomplete?
I am having a lot of difficulty implementing the instructions on setting up a local server with Python 3.6.9. as I try running 'http.server' and the 'cd' command to get to the proper directory. 

#### Did you test this? If so, how?
I tried various methods and nothing is working. I am using Windows 10(Command Prompt). 
It is recognizing Python.
I tried running both 'SimpleHTTPserver' and 'http.server' but it shows a NameError message. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/common_questions/set_up_a_local_testing_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/set_up_a_local_testing_server/index.html
* Last commit: https://github.com/mdn/content/commit/a2bc0c1d84e532bfb4ae1e19c3736a70be62d239
* Document last modified: 2021-07-12T06:22:25.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Hey @WildOne777,

I'm not running Windows myself, but have supported colleagues in the past. I hope I can help you figure out the issue.

```sh
# If Python version returned above is 2.X
python -m SimpleHTTPServer
```

Python 2 has reached end of life. This line should likely be removed from the documentation.

You mentioned a NameError message.
Can you give me the output of the following?

```
python -v
python3 -v
py -V
python3 -m http.server
```

I expect some to throw error messages, others to give a line back.
Please include everything you have.

**Comment by Ryuno-Ki** [comment]
Oh, and double check that you have this ticked:

> On the first installer page, make sure you check the "Add Python 3.xxx to PATH" checkbox.

Otherwise it can be different for Windows to find Python in the first place (been there, done that).

**Comment by himanshugarg** [comment]
This is correctly documented and works fine. ![image](https://user-images.githubusercontent.com/2392803/131820242-a3744cbe-c06e-4343-9b40-16724c8868b2.png) .

**Comment by wbamberg** [comment]
Closing for lack of response.
