### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by JimmySorza** [mdn/content#7433]
When you visit this url https://www.mozilla.org/en-US/contribute and click in this button: 
<img width="320" alt="image" src="https://user-images.githubusercontent.com/28790876/127559091-22a2ca6a-094d-41ba-b595-37ae8344b475.png">
it show this: 
Sorry, the page /en-US/docs/Mozilla/Developer_guide/Introduction could not be found.
<img width="861" alt="image" src="https://user-images.githubusercontent.com/28790876/127559007-ca845fdd-288d-4d3d-a28b-672669dec2a2.png">

**Comment by sideshowbarker** [comment]
Thanks for raising this. I can’t actually reproduce it. Can you now?

For me, that page currently links to https://firefox-source-docs.mozilla.org/contributing/contributing_to_mozilla.html

If you don’t get that URL in you browser, maybe try force-reloading, or else you might try in a different browser.

**Comment by JimmySorza** [comment]
> Thanks for raising this. I can’t actually reproduce it. Can you now?
> 
> For me, that page currently links to https://firefox-source-docs.mozilla.org/contributing/contributing_to_mozilla.html
> 
> If you don’t get that URL in you browser, maybe try force-reloading, or else you might try in a different browser.

yes it is already resolved.
