### ISSUE TITLE
Issue with "Match patterns in extension manifests": (short summary here please)

### ISSUE THREAD

**Issue by aquilax** [mdn/content#7438]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns

#### What information was incorrect, unhelpful, or incomplete?

The example `ftps://files.somewhere.org/` is defined as passing, but the `ftps` schema is not listed in the `<all_url>` definition:
 
> "http", "https", "ws", "wss", "ftp", "data", and "file".

#### Specific section or headline?

Examples -> <all_url>

#### What did you expect to see?

Either `ftps://files.somewhere.org/` to be marked as failing or `ftps` to be in the list of allowed schemes

#### Did you test this? If so, how?

no

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/match_patterns`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/match_patterns/index.html
* Last commit: https://github.com/mdn/content/commit/58d2649cd52f8c1d9baca86a1f02ca98b1fb2d09
* Document last modified: 2021-05-31T17:27:37.000Z

</details>

**Comment by caitmuenster** [comment]
This issue is open to contributors! If this is your first contribution to MDN, check out this short guide to [getting started](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Getting_started#4_simple_steps_to_mdn). For more information about style guides, previewing changes, and submitting changes via pull requests, please see the [MDN content README](https://github.com/mdn/content/blob/main/README.md#making-contributions). 

Mentor: @caitmuenster

**Comment by singla-shivam** [comment]
Hi @caitmuenster, I would like to work on this issue

**Comment by singla-shivam** [comment]
It seems `ftps` in browsers (tested with Chrome, Brave and Firefox) is not supported at all.

From this code- https://searchfox.org/mozilla-central/source/toolkit/components/extensions/MatchPattern.cpp#231 -the`ftps` is also not there  in the supported schemes.

References for Firefox-
1. https://bugzilla.mozilla.org/show_bug.cgi?id=85464
2. https://bugzilla.mozilla.org/show_bug.cgi?id=1463440

This- https://www.chromestatus.com/feature/6246151319715840 - also says that Chrome/Chromium does not support `ftps` (and may remove `ftp` altogether).

**Comment by singla-shivam** [comment]
It seems `ftps` in browsers (tested with Chrome, Brave and Firefox) is not supported at all.

From this code- https://searchfox.org/mozilla-central/source/toolkit/components/extensions/MatchPattern.cpp#231 -the `ftps` is also not there in the supported schemes.

References for Firefox-
1. https://bugzilla.mozilla.org/show_bug.cgi?id=85464
2. https://bugzilla.mozilla.org/show_bug.cgi?id=1463440

This- https://www.chromestatus.com/feature/6246151319715840 - also says that Chrome/Chromium does not support `ftps` (and is going to remove `ftp` altogether).

So, `ftps` should not be there under the heading "scheme/Form". Also, the example `ftps://files.somewhere.org/` should either be not listed at all, or be moved to failing examples.

**Comment by rebloor** [comment]
@singla-shivam Nice work. I would suggest moving the "non-matches" examples as this will reinforce the fact that `ftps` is not supported and help avoid future questions.
