### ISSUE TITLE
Issue with "Date() constructor": incorrect documentation of return value

### ISSUE THREAD

**Issue by pavelhoral** [mdn/content#7450]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

#### What information was incorrect, unhelpful, or incomplete?

> Calling the Date() function (without the new keyword) returns a string. If called with an invalid date string, the Date() function returns the literal string Invalid Date.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#return_value

#### What did you expect to see?

Both sentences for calling `Date` constructor as a function (i.e. without the `new` keyword) are misleading because it simply returns current date and ignores any arguments (hence _Invalid Date_ is never returned). This is also apparent from ECMAScript spec - https://262.ecma-international.org/6.0/#sec-date-constructor (see *Else* branches in all the constructor variants).

#### Did you test this? If so, how?

I have checked how Chrome, Firefox and RhinoJS behave - all of them simply ignore any function arguments.

```
Date(0); // returns current date
Date("2020-01-01"); // returns current date
Date("2020-01-40"); // returns current date
Date(2020, 01, 01); // returns current date
Date(2020, 01, 40); // returns current date
Date(2020, 01, 40); // returns current date
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/date`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/date/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks very much for catching this — I’ve opened #7454 with a fix.
