### ISSUE TITLE
Issue with "height": fit-content causes horizontal scroll on mobile

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#7456]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/height

#### What information was incorrect, unhelpful, or incomplete?

Because fit-content contains several code elements, the line does not wrap on mobile.

#### Specific section or headline?

Values.

#### What did you expect to see?

Either a line break or rewording.

#### Did you test this? If so, how?

I opened the link in Fennec 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/height`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/height
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/height/index.html
* Last commit: https://github.com/mdn/content/commit/69f5a958188c2c631e7b125992e3048625737ff1
* Document last modified: 2021-06-29T03:43:37.000Z

</details>

CC @schalkneethling Could also have impact on mdn-minimalist

**Comment by rachelandrew** [comment]
On which part of the page are you seeing this scrollbar?

**Comment by Ryuno-Ki** [comment]
Basically everywhere. See the light gray bar at the bottom.

![Screen Shot 2021-08-04 at 21 42 21](https://user-images.githubusercontent.com/3097194/128076336-01843d72-76d5-409c-b592-bb5caee695fa.png)

Simulated on Firefox Desktop using Galaxy S9 as emulated device.

**Comment by rachelandrew** [comment]
I don't think this is a content issue so should probably be raised against https://github.com/mdn/mdn-minimalist/ 

If you believe it should be solved by adjusting the content then please re-open (or raise a PR).

**Comment by schalkneethling** [comment]
Created an issue on the Yari side to look into this https://github.com/mdn/yari/issues/4414
