### ISSUE TITLE
YouTube video in “Animation performance and frame rate” is no longer available 

### ISSUE THREAD

**Issue by jwatt** [mdn/content#7457]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Implement_a_settings_page

Both videos are unavailable.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/implement_a_settings_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Implement_a_settings_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/implement_a_settings_page/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment]
The videos are the following:

* https://youtu.be/E-WUhihF8fw
* https://youtu.be/ECt9cbWh1qs

They both just display a *“Video unavailable: This video is private”* message

**Comment by wbamberg** [comment]
Same for the videos in the other add-ons tutorials: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension.

**Comment by caitmuenster** [comment]
Thanks for reporting this; we're trying to chase down the account holders for Hacks & Mozilla Developer YouTube channels. Unfortunately, logins weren't handed off during some staffing changes.

**Comment by AnilSeervi** [comment]
A list of pages that have the same issue:
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization
- https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox
- https://developer.mozilla.org/en-US/docs/Tools/Style_Editor
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Add_a_button_to_the_toolbar
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests

**Comment by sideshowbarker** [comment]
From @AnilSeervi in https://github.com/mdn/content/issues/7768

> I've gathered some pages that have this issue :
> - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization
> - https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox
> - https://developer.mozilla.org/en-US/docs/Tools/Style_Editor
> - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
> - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Add_a_button_to_the_toolbar
> - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests 
> - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Implement_a_settings_page
> - https://developer.mozilla.org/en-US/docs/Tools/Performance/Scenarios/Animating_CSS_properties
> - https://developer.mozilla.org/en-US/docs/Tools/Performance/Scenarios/Intensive_JavaScript
> - https://developer.mozilla.org/en-US/docs/Tools/Performance/Allocations
> - https://developer.mozilla.org/en-US/docs/Tools/Performance/Flame_Chart
> - https://developer.mozilla.org/en-US/docs/Tools/Performance/UI_Tour
> - https://developer.mozilla.org/en-US/docs/Tools/Memory/Basic_operations
> - https://developer.mozilla.org/en-US/docs/Tools/Memory/Aggregate_view
> - https://developer.mozilla.org/en-US/docs/Tools/Memory/Dominators_view
> - https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Set_a_conditional_breakpoint
> - https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Disable_breakpoints
> - https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Step_through_code

**Comment by rebloor** [comment]
@Rumyra Any progress on recovering the videos?

**Comment by rebloor** [comment]
@wbamberg Will there be a way to comment out when we converted to markdown? Would commenting out/removing fit in with the markdown conversion workflow?

**Comment by rebloor** [comment]
Thanks @wbamberg , I'll look at tackling this next week once the conversion is complete. I also agree that it makes sense to remove. The relevant issue/PR will have a record should we have the opportunity to go back and re-create or otherwise fix the videos.

**Comment by Yet-Another-Programmer** [comment]
The videos still seem to exist but theys are private. Copy the video link and past it into the adress bar.
![mspaint_aOsACPUoZB](https://user-images.githubusercontent.com/72605853/141472731-766550c4-e476-41cc-9c7b-d3c4170f82d6.png)
Then you get to the video.
![image](https://user-images.githubusercontent.com/72605853/141472195-55cbe380-e04e-46f9-a948-de03b663a62a.png)

What i find strange however, is that the request doesn't bring back any status code. Even when a video is private something should be returned, when requesting it right?
![firefox_network](https://user-images.githubusercontent.com/72605853/141471901-a1554dd0-93c0-418a-955a-7977c77a1dab.png)

**Comment by rebloor** [comment]
Unavailable videos have now been removed from the web extensions pages. There remain unavailable videos on the following tools pages:

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Add_a_button_to_the_toolbar
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Modify_a_web_page
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_second_WebExtension
- https://developer.mozilla.org/en-US/docs/Tools/about:debugging/about:debugging_before_Firefox_68 (consider archiving)
- https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer  (maybe orphaned)
- https://developer.mozilla.org/en-US/docs/Tools/Memory/Dominators_view
- https://developer.mozilla.org/en-US/docs/Tools/Memory/Dominators_view
- https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS
- https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_HTML
- https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model
- https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Inspect_and_select_colors
- https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Reposition_elements_in_the_page
- https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_an_element
- https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_and_highlight_elements
- https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Work_with_animations/Animation_inspector_(Firefox_41_and_42) (consider archiving)
- https://developer.mozilla.org/en-US/docs/Tools/Performance/Allocations
- https://developer.mozilla.org/en-US/docs/Tools/Performance/Allocations
- https://developer.mozilla.org/en-US/docs/Tools/Performance/Flame_Chart
- https://developer.mozilla.org/en-US/docs/Tools/Shader_Editor (consider archiving)
- https://developer.mozilla.org/en-US/docs/Tools/Style_Editor
- https://developer.mozilla.org/en-US/docs/Tools/Style_Editor
- https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages
- https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate

**Comment by rebloor** [comment]
Remove the Content:WebExt tag, as all the available videos in the web extension to content have been removed.

**Comment by digitalvirtuallife** [comment]
@montidigital Git App Update Chrome For Firefox Tool When user SharesSomething you will see insoection tool

**Comment by ddbeck** [comment]
With devtools docs moved off of MDN, the last affected page appears to be https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate

**Comment by wbamberg** [comment]
Thanks @ddbeck ! I just filed https://github.com/mdn/content/pull/14270 for that last one (since I made all these videos in the first place it seems fitting).
