### ISSUE TITLE
Issue with "Example and tutorial: Simple synth keyboard": Synth keyboard requires CSS code to function on Firefox

### ISSUE THREAD

**Issue by lynnpepin** [mdn/content#7466]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Simple_synth

#### What information was incorrect, unhelpful, or incomplete?

This is a tutorial for a synth keyboard. For the tutorial to be complete, it should have the CSS included. This is because the script, surprisingly, does not function without the CSS.

The CSS is acquired by extracting it from the i-frame containing the synth keyboard:

https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/Web_Audio_API/Simple_synth/_sample_.The_video_keyboard.html

#### Specific section or headline?

N/A

#### What did you expect to see?

I expected to see plain-text "keys" without copying the CSS, and for the keys to play tones when clicking them.

However, clicking these keys returns an error:

`Uncaught TypeError: AudioParam.value setter: Value being assigned is not a finite floating-point value.`

This is for line `osc.frequency.value = freq;` of the function `playTone(freq)`

Curiously, this works when the CSS is copied. I am new to "web dev", but I did not expect at all that CSS is necessary for this to function, and that if if the CSS were necessary, it would have been included in the tutorial.

#### Did you test this? If so, how?

1. Copy-and-paste the HTML and JavaScript blocks.
2. Open in Firefox. (I am using Firefox 90.0 on Ubuntu 18.04 using an AMD x64 CPU.)
3. Click a key.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/web_audio_api/simple_synth`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Simple_synth
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_audio_api/simple_synth/index.html
* Last commit: https://github.com/mdn/content/commit/6264fccc1001eb0ff0851201d3dbc0a7ccf9e62a
* Document last modified: 2021-07-16T05:20:50.000Z

</details>

**Comment by Anurella** [comment]
@sideshowbarker I can extract the CSS and add it to the article

**Comment by sideshowbarker** [comment]
@Anurella — cool, have set you as the assignee

**Comment by hamishwillee** [comment]
The CSS is present but hidden. The question is whether it should be hidden or not?

**Comment by himanshugarg** [comment]
The keyboard works on Firefox and Chrome. Any further changes required for this issue?

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/7466#issuecomment-922261113
