### ISSUE TITLE
Issue with "Django Tutorial Part 2: Creating a skeleton websit…": makemigrations - No module named 'catalog.urls' 

### ISSUE THREAD

**Issue by saumyakswain** [mdn/content#7473]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website

#### What information was incorrect, unhelpful, or incomplete?
'catalog.urls' is not created/defined before running 'python3 manage.py makemigrations' so the step fails. Creating a simple view and the 'catalog.urls' file with valid URL patterns pointing to the view solves the issue. 

#### Specific section or headline?
Testing the website framework

#### What did you expect to see?
The test should succeed. I'm new to django so I don't know if this worked in previous versions but does not work with (3.2.5).

#### Did you test this? If so, how?
Followed all the steps of creating the skeleton app and ran the commands for testing which failed. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/skeleton_website`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/skeleton_website/index.html
* Last commit: https://github.com/mdn/content/commit/16f66c643c9aa67a7839925d261f8c2775f0305b
* Document last modified: 2021-05-14T07:57:34.000Z

</details>

**Comment by hamishwillee** [comment]
> 'catalog.urls' is not created/defined before running 'python3 manage.py makemigrations' so the step fails. Creating a simple view and the 'catalog.urls' file with valid URL patterns pointing to the view solves the issue.

Yes it is. See the bit where the text says:

> As a final step, create a file inside your catalog folder called urls.py, and add the following text to define the (empty) imported urlpatterns. This is where we'll add our patterns as we build the application.


That is the file catalog.urls

I ran through the instructions on a fresh install to this point on Ubuntu 20.04 and everything works fine.

Closing as invalid.

**Comment by saumyakswain** [comment]
Apologies for wasting your time. Missed the paragraph, somehow. Will be more careful in future.

**Comment by hamishwillee** [comment]
Absolutely not a problem. Thank you for taking the time to post rather than just ignoring a potential issue.
