### ISSUE TITLE
dead links for picture credit at developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works

### ISSUE THREAD

**Issue by GarryFlemings** [mdn/content#7474]
## What page(s) did you find the problem on?

developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works

## Specific page section or heading?

Credits

## What is the problem?

On this day, 
https://www.flickr.com/photos/kdigga/9110990882/in/photolist-cXrKFs-c1j6hQ-mKrPUT-oRTUK4-7jSQQq-eT7daG-cZEZrh-5xT9L6-bUnkip-9jAbvr-5hVkHn-pMfobT-dm8JuZ-gjwYYM-pREaSM-822JRW-5hhMf9-9RVQNn-bnDMSZ-pL2z3y-k7FRM4-pzd8Y7-822upY-8bFN4Y-kedD87-pzaATg-nrF8ft-5anP2x-mpVky9-ceKc9W-dG75mD-pY62sp-gZmXVZ-7vVJL9-h7r9AQ-gagPYh-jvo5aM-J32rC-ibP2zY-a4JBcH-ndxM5Y-iFHsde-dtJ15p-8nYRgp-93uCB1-o6N5Bh-nBPUny-dNJ66P-9XWmVP-efXhxJ
reports 404.

On this day,
https://www.flickr.com/photos/kdigga/
reports info not for _Kevin D._ (in HTML), nor for _kdigga_ (in the URL), but for _duba dubiu_.

## What did you expect to see?

The picture.
Info on Kevin D.

## Did you test this? If so, how?

Current Win 10, current Firefox. From USA.

## My attempts to report solutions

Unproductive searches on Flickr for "Kevin D.", "kdigga", and "street composing". 🤷‍♀️

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #7478 with a fix
