### ISSUE TITLE
Issue with "Debugging Firefox for Android with WebIDE": (short summary here please)

### ISSUE THREAD

**Issue by njamescouk** [mdn/content#7485]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE

#### What information was incorrect, unhelpful, or incomplete?
this link
https://developer.android.com/guide/developing/device.html#setting-up
is a 404

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/remote_debugging/debugging_firefox_for_android_with_webide`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/remote_debugging/debugging_firefox_for_android_with_webide/index.html
* Last commit: https://github.com/mdn/content/commit/4388bb9bbdfe74a2271e8d4df6a33e3b76737473
* Document last modified: 2021-04-29T03:28:00.000Z

</details>

**Comment by shaurya1709** [comment]
So First I searched for any stuff related to what I could analyse from the android developers & MDN Docs article.
<img width="1680" alt="Search Results" src="https://user-images.githubusercontent.com/74058580/127770798-5b9eece3-c66b-4c45-b97e-2a4bde263e36.png">
 Then I came across this on the Wayback Machine
<img width="1680" alt="Wayback Machine" src="https://user-images.githubusercontent.com/74058580/127770818-69d50d00-ab22-4009-a5f9-9561335ddd90.png">
[Wayback Machine Link](http://web.archive.org/web/20120619114904/http://developer.android.com/guide/developing/device.html)

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #7490 with a fix.

**Comment by sideshowbarker** [comment]
@shaurya1709 — thanks much for the info
