### ISSUE TITLE
Issue with "Adding 2D content to a WebGL context": just a black square as with previous tutorial

### ISSUE THREAD

**Issue by Max-Lovell** [mdn/content#7486]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context

#### What information was incorrect, unhelpful, or incomplete?
Using the source code from the GitHub repo doesn't work out of the box

#### Specific section or headline?
Link to github source code.

#### What did you expect to see?
The example at the bottom of the page

#### Did you test this? If so, how?
I pasted this into my own html file - I tried to do it in a single file or separately, changing the css to the URL to the raw css file on github, and adding window.onload = main to the bottom.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl_api/tutorial/adding_2d_content_to_a_webgl_context`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Adding_2D_content_to_a_WebGL_context
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/tutorial/adding_2d_content_to_a_webgl_context/index.html
* Last commit: https://github.com/mdn/content/commit/ab20139a60693f9f38c366743ebfa8d9a41228f1
* Document last modified: 2021-05-31T10:25:41.000Z

</details>

**Comment by sideshowbarker** [comment]
Can you please be more specific than “doesn't work”? What exactly doesn’t work?

When you open the `index.html` file in a browser, what do you see?

What do you expect to see that’s different from what you actually see?

**Comment by Max-Lovell** [comment]
Sorry yes, I just see a black square that looks exactly like the previous tutorial here: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Getting_started_with_WebGL with no white square in the middle.

**Comment by SVarvello** [comment]
Hacker on phone

**Comment by sideshowbarker** [comment]
> Sorry yes, I just see a black square that looks exactly like the previous tutorial here: [developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Getting_started_with_WebGL](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Getting_started_with_WebGL) with no white square in the middle.

OK — thanks for clarifying.

I can’t reproduce that when I clone the repo and then open https://github.com/mdn/webgl-examples/blob/gh-pages/tutorial/sample2/index.html locally. Instead, I see a white square within the black square, as expected. I tried in Firefox, Chrome, and Safari, and found they all show the white square within the black square.

Have you tried in different browsers?

What error messages does the browser log to the devtools console?

**Comment by sideshowbarker** [comment]
Closing this for lack of response.
