### ISSUE TITLE
Issue with SVG elements "Related Topics": Elements' names are lower-cased

### ISSUE THREAD

**Issue by Kaiido** [mdn/content#7503]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feImage (and any other SVG element's page)

#### What information was incorrect, unhelpful, or incomplete?
The left bar's "Related Topics" show all the name of related SVG elements lower-cased.  
Case is important in SVG.

#### Specific section or headline?
The "Related Topics" section's macro (not sure where this lives exactly).

<img width="246" alt="Screen Shot 2021-08-02 at 3 02 18 ⦿" src="https://user-images.githubusercontent.com/7843391/127811787-0b66a617-a1f3-40c8-ac8f-79f5f758913e.png">

Note that the "SVG Elements" details section doesn't suffer from this issue.
<img width="193" alt="Screen Shot 2021-08-02 at 3 02 26 ⦿" src="https://user-images.githubusercontent.com/7843391/127811872-6e53c358-37e4-4cdf-b1e7-133cad4fa65d.png">

#### What did you expect to see?
The name of these related elements in camelCase, e.g &lt;fe**B**lend> or &lt;fe**C**olor**M**atrix> etc.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/element/feimage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feImage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/feimage/index.html
* Last commit: https://github.com/mdn/content/commit/91456ead4017ad5b6c5be3cacc83cc72007483ca
* Document last modified: 2021-06-10T20:25:11.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for raising this — I’ve opened https://github.com/mdn/yari/pull/4373 with a fix.
