### ISSUE TITLE
Issue with "Introduction to the DOM": (short summary here please)

### ISSUE THREAD

**Issue by ajaypremshankar** [mdn/content#7515]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction

#### What information was incorrect, unhelpful, or incomplete?
The code snippet on the page doesn't work. Function `ver()` missing.

#### Specific section or headline?
Code snappet
<img width="711" alt="Screenshot 2021-08-02 at 8 25 53 PM" src="https://user-images.githubusercontent.com/8684703/127881744-3bc1d59a-68da-4d48-bac5-eb7c1bbd0e79.png">

#### What did you expect to see?
ver() function should be declared.

#### Did you test this? If so, how?
<img width="966" alt="Screenshot 2021-08-02 at 8 28 05 PM" src="https://user-images.githubusercontent.com/8684703/127881863-56405ab4-8119-4c76-97b9-1dbd1e2dd5bb.png">

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document_object_model/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document_object_model/introduction/index.html
* Last commit: https://github.com/mdn/content/commit/e65944bcaf4056b8e78144aa62309defc1f32791
* Document last modified: 2021-06-08T12:51:38.000Z

</details>

**Comment by Anurella** [comment]
@ajaypremshankar  The function name ought to be `test()` and the content of the function will be populated by you, the function is for you to play around with to understand how the DOM works.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #7517 with a fix.
