### ISSUE TITLE
Missing JSAPI doc pages

### ISSUE THREAD

**Issue by desantir** [mdn/content#7520]
The JS::Call and other JSAPI reference pages no longer work.  Have they moved somewhere else?

Sorry, the page /en-US/docs/Mozilla/Projects/SpiderMonkey/JSAPI_reference/JS::Call could not be found.

**Comment by teoli2003** [comment]
cc/ @Rumyra who should be able to answer the question.

**Comment by sideshowbarker** [comment]
As far as I call, those docs haven’t been moved “in tree” (into mozilla-central) nor anywhere else other than into the archived-content repo at https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/projects/spidermonkey/jsapi_reference

But archive.org has copies, so this works:

https://web.archive.org/web/https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/JSAPI_reference/JS::Call

…as does the JSAPI overview page:

https://web.archive.org/web/https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/JSAPI_reference

…and all the cross-reference links for there.

**Comment by Rumyra** [comment]
Yes @desantir these docs have been removed from MDN and are now in the archive repository mentioned above.

Some docs have been moved over here: https://firefox-source-docs.mozilla.org/js/index.html#components-of-spidermonkey 👍
