### ISSUE TITLE
Issue with "KeyboardEvent.initKeyboardEvent()": article has link to "compatibility table" but there is none

### ISSUE THREAD

**Issue by scottschup** [mdn/content#7522]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/initKeyboardEvent

#### What information was incorrect, unhelpful, or incomplete?
In the deprecation warning box at the top, it says 
> see the compatibility table at the bottom of this page to guide your decision

where "compatibility table" is a link. But clicking it does nothing and there is no table at the bottom of the page.

#### Specific section or headline?
Deprecation warning at top of page.

#### What did you expect to see?
Link works or is removed

#### Did you test this? If so, how?
Yes. By clicking the link.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/keyboardevent/initkeyboardevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/initKeyboardEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/keyboardevent/initkeyboardevent/index.html
* Last commit: https://github.com/mdn/content/commit/f0eebae101d62c399ec331467d740ab58c59ebe4
* Document last modified: 2021-05-26T05:52:54.000Z

</details>

**Comment by hamishwillee** [comment]
Fixed by #7526. Thanks for reporting.
