### ISSUE TITLE
Issue with "Window: orientationchange event": (short summary here please)

### ISSUE THREAD

**Issue by thomashh175** [mdn/content#7524]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/orientationchange_event

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/orientationchange_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/orientationchange_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/orientationchange_event/index.html
* Last commit: https://github.com/mdn/content/commit/64b0057f7238be9ad7a6f2f522efd8f5f7753095
* Document last modified: 2021-06-17T09:07:21.000Z

</details>

**Comment by hamishwillee** [comment]
Closing because you haven't provided any information about the bug.
