### ISSUE TITLE
Convert Web/HTTP to markdown

### ISSUE THREAD

**Issue by teoli2003** [mdn/content#7536]
As part of openwebdocs/project#43, I will review every HTTP pages, it is a good opportunity to move it to Markdown at the same time.

In addition, I will use this issue to track all activities needed, so, at the end, I can write a checklist for the conversion.

As an initial baseline:
<img width="871" alt="Screenshot 2021-08-03 at 06 52 34" src="https://user-images.githubusercontent.com/1466293/127959731-8281955d-2c94-42e5-91e4-36b91a80b8f2.png">

**Comment by hamishwillee** [comment]
Awesome. I'm happy to help with "generic markdown fixes or review" in HTTP if you need help
