### ISSUE TITLE
Issue with "Adding features to our bouncing balls demo": …

### ISSUE THREAD

**Issue by maruthimohan** [mdn/content#754]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Adding_bouncing_balls_features

#### What information was incorrect, unhelpful, or incomplete?

Under the section **Creating our new objects**, there is a statement that says, `The ball draw(), update(), and collisionDetect() method definitions should be able to stay exactly the same as they were before.` But from my observation, it is kind of incorrect. Because as the `EvilCircle` begins "eating" the bouncing balls, the number of existing balls to check for collision detection (i.e., the balls to be checked against are those with `exists` property set to `true`) also decreases, and hence, the `collisionDetect()` method of the `Ball` prototype needs to be updated as shown below.

```
Ball.prototype.collisionDetect = function () {
    for (let j = 0; j < balls.length; j++) {
        if (!(this === balls[j]) && balls[j].exists) {
            const dx = this.x - balls[j].x;
            const dy = this.y - balls[j].y;
            const distance = Math.sqrt(dx * dx + dy * dy);

            if (distance < this.size + balls[j].size) {
                balls[j].color = this.color = 'rgb(' + random(0, 255) + ',' + random(0, 255) + ',' + random(0, 255) + ')';
            }
        }
    }
}
```

#### Specific section or headline?

Creating our new objects

#### What did you expect to see?

The statement `The ball draw(), update(), and collisionDetect() method definitions should be able to stay exactly the same as they were before.` is kind of incorrect (although it is not wrong, the bouncing balls would "magically" change colors by themselves even without visibly colliding with the other balls as the number of balls with `exists` property set to `false` increase in number).

So if we could make a slight change in the `collisionDetect()` method, it would remove that tiny glitch.

Changes to be made:
`if (!(this === balls[j])) {` to `if (!(this === balls[j]) && balls[j].exists) {`

#### Did you test this? If so, how?
I followed this tutorial and verified the current state of working. Also updated the code and tested it in local.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/objects/adding_bouncing_balls_features`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Adding_bouncing_balls_features
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
* Report started: 2020-12-30T03:20:24.564Z

</details>

**Comment by maruthimohan** [comment]
Also, I could work on fixing this if this is considered a valid issue of the documentation.

**Comment by sideshowbarker** [comment]
> Also, I could work on fixing this if this is considered a valid issue of the documentation.

After skimming the issue description, it seems to me like a valid issue for the documentation. So I think it’s worth your time to write up a patch and raise a PR for it.

**Comment by maruthimohan** [comment]
@sideshowbarker Could you please review the PR?

**Comment by sideshowbarker** [comment]
> @sideshowbarker Could you please review the PR?

Yes I will right now
