### ISSUE TITLE
Well, I just want to say that you should add a "Go To Top" link in all your pages so that it will be easier for users to navigate to the top

### ISSUE THREAD

**Issue by Atul-Kumar-Official** [mdn/content#7547]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/html_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/html_basics/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for the feature suggestion. As a feature suggestion (rather than a specific content issue), the place to best place to discuss this wold be in the https://github.com/mdn/yari repo — so please re-raise this is at https://github.com/mdn/yari/issues/new

**Comment by Atul-Kumar-Official** [comment]
Thanks
