### ISSUE TITLE
Padding prominence in box model illustration

### ISSUE THREAD

**Issue by juleshwar** [mdn/content#7548]
### Issue
This format of the box model referenced in a pages like [`HTMLElement.clientWidth`](https://github.com/mdn/content/blob/ce74fef474c49a56cf9b70b56c41b8d00658447a/files/en-us/web/api/element/clientwidth/index.html#L41), [`HTMLElement.offsetWidth`](https://github.com/mdn/content/blob/ce74fef474c49a56cf9b70b56c41b8d00658447a/files/en-us/web/api/htmlelement/offsetwidth/index.html#L43) etc. fails to show the padding more prominently.  
It would be better if a "box" for the padding is shown as well. That would make it clear that `clientWidth` includes the padding as well.

### Reference image present in `HTMLElement.clientWidth`
![image](https://user-images.githubusercontent.com/24788774/128034068-5b83abe8-f601-4485-ad0f-7ebae2c539dd.png)

**Comment by dev-nicolaos** [comment]
I can take a crack at this

**Comment by sideshowbarker** [comment]
@dev-nicolaos Thanks much — now assigned to you
