### ISSUE TITLE
Issue with "WindowOrWorkerGlobalScope.setTimeout()": (short summary here please)

### ISSUE THREAD

**Issue by b-ras** [mdn/content#7553]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout

#### What information was incorrect, unhelpful, or incomplete?
An example did not run.

#### Specific section or headline?
The section: 'Setting and clearing timeouts'.

#### What did you expect to see?
The example 'show an alert box after...' did not work. See console log for more details : 'A different origin subframe tried to create a JavaScript dialog. This is no longer allowed and was blocked. See https://www.chromestatus.com/feature/5148698084376576 for more details.'

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/windoworworkerglobalscope/settimeout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/windoworworkerglobalscope/settimeout/index.html
* Last commit: https://github.com/mdn/content/commit/a581ca4d1c5bac8354670380121656793d733d00
* Document last modified: 2021-07-15T22:42:02.000Z

</details>

**Comment by Ryuno-Ki** [comment]
Dear @b-ras,

could you share the browser and OS you used? It worked in my case.

**Comment by wbamberg** [comment]
@Ryuno-Ki , it's a new thing in Chrome, I think.

There are a depressingly large number of these in our docs. This is a list of all `<pre class="js>` blocks inside Web/API that include `alert(`:

https://developer.mozilla.org/en-US/docs/Web/API/animation/ready
https://developer.mozilla.org/en-US/docs/Web/API/attr/localname
https://developer.mozilla.org/en-US/docs/Web/API/canvas_api/tutorial/applying_styles_and_colors
https://developer.mozilla.org/en-US/docs/Web/API/canvas_api/tutorial/basic_animations
https://developer.mozilla.org/en-US/docs/Web/API/canvasrenderingcontext2d/addhitregion
https://developer.mozilla.org/en-US/docs/Web/API/clipboard/read
https://developer.mozilla.org/en-US/docs/Web/API/console
https://developer.mozilla.org/en-US/docs/Web/API/console/timeend
https://developer.mozilla.org/en-US/docs/Web/API/console/timelog
https://developer.mozilla.org/en-US/docs/Web/API/document/evaluate
https://developer.mozilla.org/en-US/docs/Web/API/document/height
https://developer.mozilla.org/en-US/docs/Web/API/document/implementation
https://developer.mozilla.org/en-US/docs/Web/API/document/lastmodified
https://developer.mozilla.org/en-US/docs/Web/API/document/lastmodified
https://developer.mozilla.org/en-US/docs/Web/API/document/lastmodified
https://developer.mozilla.org/en-US/docs/Web/API/document/querycommandstate
https://developer.mozilla.org/en-US/docs/Web/API/document_object_model/introduction
https://developer.mozilla.org/en-US/docs/Web/API/domexception/domexception
https://developer.mozilla.org/en-US/docs/Web/API/domimplementation/createdocument
https://developer.mozilla.org/en-US/docs/Web/API/domimplementation/createdocumenttype
https://developer.mozilla.org/en-US/docs/Web/API/element/getattributenode
https://developer.mozilla.org/en-US/docs/Web/API/element/innerhtml
https://developer.mozilla.org/en-US/docs/Web/API/element/innerhtml
https://developer.mozilla.org/en-US/docs/Web/API/element/onfullscreenchange
https://developer.mozilla.org/en-US/docs/Web/API/element/requestfullscreen
https://developer.mozilla.org/en-US/docs/Web/API/element/requestfullscreen
https://developer.mozilla.org/en-US/docs/Web/API/element/setattributenodens
https://developer.mozilla.org/en-US/docs/Web/API/eventlistener
https://developer.mozilla.org/en-US/docs/Web/API/eventtarget/addeventlistener
https://developer.mozilla.org/en-US/docs/Web/API/file/name
https://developer.mozilla.org/en-US/docs/Web/API/file/type
https://developer.mozilla.org/en-US/docs/Web/API/file/using_files_from_web_applications
https://developer.mozilla.org/en-US/docs/Web/API/filereader/onerror
https://developer.mozilla.org/en-US/docs/Web/API/geolocation_api/using_the_geolocation_api
https://developer.mozilla.org/en-US/docs/Web/API/geolocation_api/using_the_geolocation_api
https://developer.mozilla.org/en-US/docs/Web/API/globaleventhandlers/onerror
https://developer.mozilla.org/en-US/docs/Web/API/globaleventhandlers/onkeypress
https://developer.mozilla.org/en-US/docs/Web/API/history_api/example
https://developer.mozilla.org/en-US/docs/Web/API/html_sanitizer_api
https://developer.mozilla.org/en-US/docs/Web/API/html_sanitizer_api
https://developer.mozilla.org/en-US/docs/Web/API/htmlanchorelement/rel
https://developer.mozilla.org/en-US/docs/Web/API/htmlareaelement/rel
https://developer.mozilla.org/en-US/docs/Web/API/htmlcanvaselement/mozfetchasstream
https://developer.mozilla.org/en-US/docs/Web/API/htmlimageelement
https://developer.mozilla.org/en-US/docs/Web/API/htmllinkelement/rel
https://developer.mozilla.org/en-US/docs/Web/API/htmlscriptelement
https://developer.mozilla.org/en-US/docs/Web/API/idbobjectstore/getkey
https://developer.mozilla.org/en-US/docs/Web/API/indexeddb_api/checking_when_a_deadline_is_due
https://developer.mozilla.org/en-US/docs/Web/API/keyboard/getlayoutmap
https://developer.mozilla.org/en-US/docs/Web/API/keyboard
https://developer.mozilla.org/en-US/docs/Web/API/keyboard_api
https://developer.mozilla.org/en-US/docs/Web/API/keyboardevent/altkey
https://developer.mozilla.org/en-US/docs/Web/API/keyboardevent/ctrlkey
https://developer.mozilla.org/en-US/docs/Web/API/keyboardevent
https://developer.mozilla.org/en-US/docs/Web/API/keyboardevent/metakey
https://developer.mozilla.org/en-US/docs/Web/API/keyboardevent/shiftkey
https://developer.mozilla.org/en-US/docs/Web/API/keyboardlayoutmap/get
https://developer.mozilla.org/en-US/docs/Web/API/keyboardlayoutmap
https://developer.mozilla.org/en-US/docs/Web/API/mediastreamevent
https://developer.mozilla.org/en-US/docs/Web/API/mediastreamevent/stream
https://developer.mozilla.org/en-US/docs/Web/API/mediastreamtrack/onoverconstrained
https://developer.mozilla.org/en-US/docs/Web/API/microdata_dom_api
https://developer.mozilla.org/en-US/docs/Web/API/mouseevent
https://developer.mozilla.org/en-US/docs/Web/API/navigator/appversion
https://developer.mozilla.org/en-US/docs/Web/API/navigator/oscpu
https://developer.mozilla.org/en-US/docs/Web/API/nodefilter/acceptnode
https://developer.mozilla.org/en-US/docs/Web/API/nodefilter
https://developer.mozilla.org/en-US/docs/Web/API/notification
https://developer.mozilla.org/en-US/docs/Web/API/notification/requestpermission
https://developer.mozilla.org/en-US/docs/Web/API/notifications_api/using_the_notifications_api
https://developer.mozilla.org/en-US/docs/Web/API/pagetransitionevent
https://developer.mozilla.org/en-US/docs/Web/API/pointer_lock_api
https://developer.mozilla.org/en-US/docs/Web/API/rtcpeerconnection/currentlocaldescription
https://developer.mozilla.org/en-US/docs/Web/API/rtcpeerconnection/currentremotedescription
https://developer.mozilla.org/en-US/docs/Web/API/rtcpeerconnection/localdescription
https://developer.mozilla.org/en-US/docs/Web/API/rtcpeerconnection/onremovestream
https://developer.mozilla.org/en-US/docs/Web/API/rtcpeerconnectioniceevent/candidate
https://developer.mozilla.org/en-US/docs/Web/API/rtcpeerconnectioniceevent
https://developer.mozilla.org/en-US/docs/Web/API/rtcsessiondescription/sdp
https://developer.mozilla.org/en-US/docs/Web/API/rtcsessiondescription/tojson
https://developer.mozilla.org/en-US/docs/Web/API/rtcsessiondescription/type
https://developer.mozilla.org/en-US/docs/Web/API/sanitizer
https://developer.mozilla.org/en-US/docs/Web/API/sanitizer/sanitize
https://developer.mozilla.org/en-US/docs/Web/API/sanitizer/sanitizer
https://developer.mozilla.org/en-US/docs/Web/API/sanitizer/sanitizetostring
https://developer.mozilla.org/en-US/docs/Web/API/selection
https://developer.mozilla.org/en-US/docs/Web/API/selection/tostring
https://developer.mozilla.org/en-US/docs/Web/API/trusted_types_api
https://developer.mozilla.org/en-US/docs/Web/API/trustedhtml
https://developer.mozilla.org/en-US/docs/Web/API/trustedhtml/tojson
https://developer.mozilla.org/en-US/docs/Web/API/trustedhtml/tostring
https://developer.mozilla.org/en-US/docs/Web/API/trustedtypepolicy/createhtml
https://developer.mozilla.org/en-US/docs/Web/API/trustedtypepolicy
https://developer.mozilla.org/en-US/docs/Web/API/trustedtypepolicyfactory
https://developer.mozilla.org/en-US/docs/Web/API/urlsearchparams/set
https://developer.mozilla.org/en-US/docs/Web/API/videoplaybackquality/totalframedelay
https://developer.mozilla.org/en-US/docs/Web/API/web_audio_api/migrating_from_webkitaudiocontext
https://developer.mozilla.org/en-US/docs/Web/API/web_audio_api/migrating_from_webkitaudiocontext
https://developer.mozilla.org/en-US/docs/Web/API/web_workers_api/using_web_workers
https://developer.mozilla.org/en-US/docs/Web/API/webgl_api/by_example/clearing_by_clicking
https://developer.mozilla.org/en-US/docs/Web/API/webgl_api/by_example/simple_color_animation
https://developer.mozilla.org/en-US/docs/Web/API/webgl_api/tutorial/adding_2d_content_to_a_webgl_context
https://developer.mozilla.org/en-US/docs/Web/API/webgl_api/tutorial/getting_started_with_webgl
https://developer.mozilla.org/en-US/docs/Web/API/webrtc_api/signaling_and_video_calling
https://developer.mozilla.org/en-US/docs/Web/API/webrtc_api/signaling_and_video_calling
https://developer.mozilla.org/en-US/docs/Web/API/window/alert
https://developer.mozilla.org/en-US/docs/Web/API/window/alert
https://developer.mozilla.org/en-US/docs/Web/API/window/find
https://developer.mozilla.org/en-US/docs/Web/API/window/location
https://developer.mozilla.org/en-US/docs/Web/API/window/location
https://developer.mozilla.org/en-US/docs/Web/API/window/navigator
https://developer.mozilla.org/en-US/docs/Web/API/window/prompt
https://developer.mozilla.org/en-US/docs/Web/API/windoworworkerglobalscope/cleartimeout
https://developer.mozilla.org/en-US/docs/Web/API/windoworworkerglobalscope/settimeout
https://developer.mozilla.org/en-US/docs/Web/API/windoworworkerglobalscope/settimeout
https://developer.mozilla.org/en-US/docs/Web/API/windoworworkerglobalscope/settimeout
https://developer.mozilla.org/en-US/docs/Web/API/workernavigator/appversion
https://developer.mozilla.org/en-US/docs/Web/API/xmldocument/load
https://developer.mozilla.org/en-US/docs/Web/API/xmlhttprequest/how_to_check_the_secruity_state_of_an_xmlhttprequest_over_ssl

Lots of these are not inside live samples - it would be great to get a list of which ones are, but that would be harder to figure out.
