### ISSUE TITLE
Issue with "DOMTokenList.toggle()": (Output not specified)

### ISSUE THREAD

**Issue by voxelfox** [mdn/content#7559]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle

#### What information was incorrect, unhelpful, or incomplete?
The output of the code block was not provided.

#### Specific section or headline?
Examples section.

#### What did you expect to see?
A written output for the code block which is showcased in the examples section.

#### Did you test this? If so, how?
No test is required.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/domtokenlist/toggle`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/domtokenlist/toggle/index.html
* Last commit: https://github.com/mdn/content/commit/bf3d143038cc4cba0b5f30e6f81428cf2d1d7fc0
* Document last modified: 2021-06-12T21:25:39.000Z

</details>

**Comment by voxelfox** [comment]
If this is one of those, "it's a hassle to include in the documentation," don't bother adding it. The code itself is self-explanatory. One just needs to spend a little time hashing the code to formulate an understanding of what the output may look like.

**Comment by sideshowbarker** [comment]
Can you please clarify exactly what’s missing?

At the end of https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle#examples, I see this:

![image](https://user-images.githubusercontent.com/194984/128098589-2f0752fc-54f5-4333-b89e-2e4019f1c5a5.png)

That is, the output of the code block is in fact provided, and it starts out with the content:
```
classList is 'a b'
```
… and if you click it, it changes to:

```
'c' added; classList is now "a b c".
```

… and if you click it again, it changes to:

```
'c' removed; classList is now "a b".
```

**Comment by AnilSeervi** [comment]
I guess what he's trying to say is, clicking on the span itself to toggle the list is not a good way to show the output accessibility wise.
I suggest why not add a button or so to toggle it which would be more practical and understandable.

**Comment by sideshowbarker** [comment]
> I guess what he's trying to say is, clicking on the span itself to toggle the list is not a good way to show the output accessibility wise.

No, as far as I can see at least, that doesn’t seem to be at all what the OP is actually saying.

I can’t see that the issue description either says or clearly implies at all anything about toggling the display of the output — nor anything at all about the accessibility of how the output is displayed.

Instead the issue description literally says *“The output of the code block was not provided”* — while as https://github.com/mdn/content/issues/7559#issuecomment-892232126 points out, the output is actually shown, preceded by text saying *“The output looks like this:”*.

So while we can speculate ourselves about what the OP might have meant, what seems necessary here is for the OP themselves to respond and clarify what actual problem they meant to report. 

> I suggest why not add a button or so to toggle it which would be more practical and understandable.

I can’t see that adding that would resolve what the actual issue description is about.

**Comment by voxelfox** [comment]
@sideshowbarker Thank you for getting back to me. Yes, that is correct on my browser there is no output block specified. I am using Firefox 90.0.2 (MacOS 64-bit).

The following image shows what is visible to me:
![Screen Shot 2021-08-07 at 12 37 55 PM](https://user-images.githubusercontent.com/59779638/128597395-d20c6d4f-6cc9-48f8-9e2e-94a2b8306105.png)

**Comment by sideshowbarker** [comment]
That is odd. When you open devtools and look at the console, doe you see any error messages that the browser has logged there?

**Comment by voxelfox** [comment]
Here is a screenshot of my console:

![Screen Shot 2021-08-07 at 9 23 43 PM](https://user-images.githubusercontent.com/59779638/128611743-23e59e4b-0611-4374-b54e-ad0d147739f0.png)

**Comment by sideshowbarker** [comment]
Is the output also missing if you open the article in a private window in Firefox?

What happens if you disable all our extensions/add-ons in Firefox and then view the article?

**Comment by AnilSeervi** [comment]
And is it missing from these pages too for you?
- https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/length
- https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/value

**Comment by voxelfox** [comment]
> Is the output also missing if you open the article in a private window in Firefox?
> 
> What happens if you disable all our extensions/add-ons in Firefox and then view the article?

@sideshowbarker You hit the nail on the head. It seems like one of my firefox extensions was blocking the content.

@AnilSeervi Yes, that's correct. When my extensions are enabled the output code block is not viewable in the browser.
