### ISSUE TITLE
Issue with "Understanding WebAssembly text format": …

### ISSUE THREAD

**Issue by Kylebrown9** [mdn/content#756]
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format

#### What information was incorrect, unhelpful, or incomplete?
This page goes into detail about each of the types of sections and a number of extensions to the standard which are not yet available, but does not provide any info about WAT/WASM control instructions which are an important part of the core spec.

#### Specific section or headline?
N/A, would require a new section.

#### What did you expect to see?
A basic overview of WAT/WASM control instructions.

#### Did you test this? If so, how?
N/A, there is nothing to test.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/understanding_the_text_format`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/webassembly/understanding_the_text_format/index.html
* Report started: 2020-12-30T04:59:55.578Z

</details>

**Comment by MendyBerger** [comment]
I looked into this and I think that I'd be able to create a basic table listing all control flow statements and provide a short description besides it, something like:

| Statement | Description |
| ------------- | ------------- |
| if | Starts the if parts of an if condition |
| else | Else block of an if condition |
| end | Ends a block, loop, if, or else |
| br | Performs a branch |
| Etc.. |


However, I don't think this is enough, I think it'll be much better to have a separate page for each statement where we can give a description, show an example, and add additional information if necessary, similar to what we have for JavaScript's statements [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements).

If needed, I think that I'll be able to provide a basic description and example to each statement.

Would you folks be open to something like this?

**Comment by sideshowbarker** [comment]
@MendyBerger Sounds great — I went ahead and assigned this to you.
