### ISSUE TITLE
WorkerGlobalScope.requestFileSystemSync() - Page not found

### ISSUE THREAD

**Issue by Ark-kun** [mdn/content#7569]
https://developer.mozilla.org/en-US/docs/Web/API/Window/resolveLocalFileSystemURL and https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/requestFileSystemSync do not exist.
Linked from https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API/Introduction

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #7572 with a fix.
