### ISSUE TITLE
Issue with "Basic Concepts of grid layout": missing image

### ISSUE THREAD

**Issue by lingtalfi** [mdn/content#7575]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout#grid_cells

There is a missing image in the grid cell section (see the link above).

**Comment by rachelandrew** [comment]
@lingtalfi which image is missing, can you tell me the URL of the image that doesn't load as it looks to me as if all the images are there.

**Comment by lingtalfi** [comment]
Ok for some reason now it's back in. So, it's not missing anymore (yesterday when I checked the page this image was not there: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout/1_grid_cell.png). All good then.

**Comment by teoli2003** [comment]
Thanks @lingtalfi. I'm closing this. Feel free to reopen it if it happens again.
