### ISSUE TITLE
Issue with "Basic Concepts of grid layout": unexplained notation

### ISSUE THREAD

**Issue by lingtalfi** [mdn/content#7577]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout#nesting_without_subgrid

In the "Nesting without subgrid" section, in the second code snippet, we have the following css code:
```css
.box1 {
  grid-column: 1 / 4;
}
```

which is not explained previously (I followed the tutorial linearly and this is the first element that is not explained before hand).
The "x / y" notation should be explained before hand to make this tutorial "perfect".

**Comment by Anurella** [comment]
@rachelandrew What section would you recommend the explanation of the suggestion be placed? This [section](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout#grid_lines) looks okay.

@lingtalfi the highlighted code indicates the start and end of the `grid-column`

**Comment by lingtalfi** [comment]
@Anurella Thanks (yes, I figured it by now :))
