### ISSUE TITLE
Add some explanatory images to CSS Building Blocks: Handling different text directions

### ISSUE THREAD

**Issue by rachelandrew** [mdn/content#7589]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Handling_different_text_directions

In the PR: https://github.com/mdn/content/pull/7001 we decided that the best solution was to add some images to that section. I have some figures I could use here, so raising this so I don't lose track before doing this.

**Comment by teoli2003** [comment]
We think this issue is stale. Rachel, feel free to create the PR in the future. The broken link fragment at the top of the page, has been fixed.
