### ISSUE TITLE
Issue with "BigInt64Array() constructor": `new BigInt64Array( new Int32Array(1) )` is not allowed

### ISSUE THREAD

**Issue by andrew-sayers** [mdn/content#7592]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array/BigInt64Array

Note: this issue applies to the constructors for all TypedArrays.  I picked this page because the problem is a little easier to describe for `BigInt64`s.

#### What information was incorrect, unhelpful, or incomplete?

All TypedArray constructors claim they can be constructed from "an object of any of the typed array types (such as `Int32Array`)".  If I'm reading the spec correctly, this is the behaviour it expects.  In practice, `BigInt64` and `BigUint64` typed arrays are not compatible with other types (see below for examples).

#### Specific section or headline?

Syntax > Parameters > typedArray > "an object of any of the typed array types (such as `Int32Array`)"

Alternatively, the page is missing a section discussing the deviation between the spec and observed behaviour.

#### What did you expect to see?

The *Syntax > Parameters > typedArray* section of all TypedArray constructors should indicate that `Big*` parameters are not accepted for non-`Big*` constructors, and vice versa.

and/or

A new section should be added discussing this issue.

#### Did you test this? If so, how?

Testing in the Firefox console shows this is always incompatible:

    >> new Int32Array( new BigInt64Array(0) )
    Uncaught TypeError: BigInt64Array elements are incompatible with Int32Array

    >> new Int32Array( new BigInt64Array(1) )
    Uncaught TypeError: BigInt64Array elements are incompatible with Int32Array

    >> new BigInt64Array( new Int32Array(0) )
    Uncaught TypeError: Int32Array elements are incompatible with BigInt64Array

    >> new BigInt64Array( new Int32Array(1) )
    Uncaught TypeError: Int32Array elements are incompatible with BigInt64Array

Testing in node shows that only non-empty TypedArrays cause errors:

    $ node
    Welcome to Node.js v12.21.0.
    Type ".help" for more information.
    > new Int32Array( new BigInt64Array(0) )
    Int32Array(0) []
    > new Int32Array( new BigInt64Array(1) )
    Uncaught TypeError: Cannot convert a BigInt value to a number
        at new Int32Array (<anonymous>)
    > new BigInt64Array( new Int32Array(0) )
    BigInt64Array(0) []
    > new BigInt64Array( new Int32Array(1) )
    Uncaught TypeError: Cannot convert 0 to a BigInt
        at new BigInt64Array (<anonymous>)
    > 

(Chromium's console output is similar to node)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/bigint64array/bigint64array`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array/BigInt64Array
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/bigint64array/bigint64array/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by bakkot** [comment]
The comment is wrong: you can only initialize a typed array from another typed array _of the same type_. (See [InitializeTypedArrayFromTypedArray](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-initializetypedarrayfromtypedarray) step 17.c.) That is, the Big* arrays can only be initialized from other Big* arrays, and the non-Big* arrays can only be initialized from the non-Big* arrays.

Chrome has a bug in that it fails to throw when the size is 0; I'll see if I can find an existing issue or, failing that, open one.

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve raised #7597 with a fix.

**Comment by andrew-sayers** [comment]
Turns out `TypedArray.set()` has the same behaviour, except without the Chrome bug.  Happy to file a separate issue if necessary, otherwise please make a similar edit to [the relevant page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set).

Node:

    $ node
    Welcome to Node.js v12.21.0.
    Type ".help" for more information.
    > new BigInt64Array(3).set(new Int32Array(0))
    Uncaught TypeError: Cannot mix BigInt and other types, use explicit conversions
        at BigInt64Array.set (<anonymous>)
    > new BigInt64Array(3).set(new Int32Array(1))
    Uncaught TypeError: Cannot mix BigInt and other types, use explicit conversions
        at BigInt64Array.set (<anonymous>)
    > 

Firefox console:

    >> new BigInt64Array(3).set(new Int32Array(0))
    Uncaught TypeError: Int32Array elements are incompatible with BigInt64Array

    >> new BigInt64Array(3).set(new Int32Array(1))
    Uncaught TypeError: Int32Array elements are incompatible with BigInt64Array

I've had a quick look through the list of `TypedArray` methods, and haven't spotted anything else where the documentation implies it would convert values from a different type of numeric.  I may have missed something though.

**Comment by bakkot** [comment]
> I've had a quick look through the list of `TypedArray` methods, and haven't spotted anything else where the documentation implies it would convert values from a different type of numeric. I may have missed something though.


From a quick skim of the uses of `[[ContentType]]`, I believe you're correct that the constructor and `.set` are the only places this comes up.
