### ISSUE TITLE
No docs for the ServiceWorker object’s postMessage method

### ISSUE THREAD

**Issue by Rolf-B** [mdn/content#7593]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker

### 2022-01-23 issue description

The `ServiceWorker` object has a `postMessage()` method of its own — which is not completely the same as the `Worker` object’s `postMessage()` method.

There is currently no documentation in MDN for the `ServiceWorker` object’s `postMessage()` method.

<details>
<summary>
2021-08-05 original issue description
</summary>

#### What information was incorrect, unhelpful, or incomplete?

You claim that ServiceWorker inherits from Worker. The spec says otherwise, it inherits from EventTarget. A ServiceWorker **is not** a Worker. Messages arrive at the ServiceWorkerGlobalScope, not the ServiceWorker itself. Yes, it's strange, but that's what the spec says.

#### Specific section or headline?

- Properties
The ServiceWorker interface inherits properties from its parent, Worker.

*The error isn't obvious, because Worker has no own properties and inherits them from EventTarget, but Worker is still not the parent*

- Methods
The ServiceWorker interface inherits methods from its parent, Worker, with the exception of Worker.terminate

  - *As far as I know, selective inheritance is not a thing in IDL or JavaScript*  
  - *Yes, Worker has a postMessage and a terminate method, and ServiceWorker has a postMessage method. But no, ServiceWorker doesn't inherit it. The procedures in the HTML and ServiceWorker specs are similar, but not identical.*

#### What did you expect to see?

A description that conforms to the spec. But I'm not familiar enough with the topic to rewrite this. 

#### Did you test this? If so, how?

I checked the prototype chain in Chrome DevTools. It's ServiceWorker -> EventTarget

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/serviceworker`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/serviceworker/index.html
* Last commit: https://github.com/mdn/content/commit/642d6eb7feb73e17cfc1ef61d3d09c2d200e65ca
* Document last modified: 2021-06-17T03:52:55.000Z

</details>
</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve raised #7596 with a fix

**Comment by Rolf-B** [comment]
Sorry, that was too quick - now postMessage is missing.

**Comment by sideshowbarker** [comment]
> Sorry, that was too quick - now postMessage is missing.

ah yeah OK — I’ll raise another PR which explicitly adds that

**Comment by sideshowbarker** [comment]
For clarity and for the record here, here’s the `ServiceWorker` IDL:

```IDL
[SecureContext, Exposed=(Window,Worker)]
interface ServiceWorker : EventTarget {
  readonly attribute USVString scriptURL;
  readonly attribute ServiceWorkerState state;
  undefined postMessage(any message, sequence<object> transfer);
  undefined postMessage(any message, optional StructuredSerializeOptions options = {});

  // event
  attribute EventHandler onstatechange;
};
ServiceWorker includes AbstractWorker;

enum ServiceWorkerState {
  "parsed",
  "installing",
  "installed",
  "activating",
  "activated",
  "redundant"

};
```
…so, notably, `postMessage()` is member of `ServiceWorker` itself (not inherited)
