### ISSUE TITLE
Issue with "Right shift assignment (>>=)": (short summary here please)

### ISSUE THREAD

**Issue by SantosXP** [mdn/content#7601]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Right_shift_assignment

#### What information was incorrect, unhelpful, or incomplete?
let b = -5;     // -00000000000000000000000000000101

b >>= 2;        // -00000000000000000000000000000010
console.log(b);
// expected output: -2

#### Specific section or headline?

b >>= 2;        // -00000000000000000000000000000010
console.log(b);
// expected output: -2
#### What did you expect to see?

b >>= 2;        // -00000000000000000000000000000001
console.log(b);
// expected output: -2
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/right_shift_assignment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Right_shift_assignment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/right_shift_assignment/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by NegiAkash890** [comment]
Hi, @SantosXP , I have tested the code in my browser's console and the result is same as mentioned in the doc.
Thanks

![image](https://user-images.githubusercontent.com/55234838/128285682-5ae20131-4d7e-43a9-a87e-c3e05e014776.png)

**Comment by sideshowbarker** [comment]
Thanks @NegiAkash890 — confirmed and closing per https://github.com/mdn/content/issues/7601#issuecomment-893133477

@SantosXP This issue tracker is scoped to reports of specific problems in existing MDN articles, or else to specific suggestions for improvements/additions to existing articles, or specific suggestions for new articles.

So if you have something specific to report that falls into any of those categories, this issue could be revisited.
