### ISSUE TITLE
Issue with "String.prototype.trim()":Remove polyfill

### ISSUE THREAD

**Issue by NagayamaToshiaki** [mdn/content#7602]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

#### What information was incorrect, unhelpful, or incomplete?
The last browser that needs polyfill was WebView Android 37, which was released 7 years ago.

#### Specific section or headline?
Polyfill

#### What did you expect to see?
Remove the section

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/trim`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/trim/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by teoli2003** [comment]
Thanks, I opened a PR for fixing it.
