### ISSUE TITLE
Issue with "JavaScript language resources": es-discuss mailing list link broken

### ISSUE THREAD

**Issue by AnilSeervi** [mdn/content#7609]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Language_Resources

#### What information was incorrect, unhelpful, or incomplete?
- [es-discuss mailing list](https://mail.mozilla.org/listinfo/es-discuss) link is broken

#### Specific section or headline?
- JavaScript language resources

#### Did you test this? If so, how?
- Visit it.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/language_resources`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Language_Resources
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/language_resources/index.md
* Last commit: https://github.com/mdn/content/commit/2323e74782942349f3241d59346afdc9616b8a1e
* Document last modified: 2021-07-30T08:30:30.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #7623 with an update
