### ISSUE TITLE
FormData() constructor should link to formdata event

### ISSUE THREAD

**Issue by ilogico** [mdn/content#7613]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData

#### What information was incorrect, unhelpful, or incomplete?
This page should mention and link to the `formdata` event.

The main `FormData` could also mention this event,.
#### What did you expect to see?
Information about the `FormData`s constructor running the event listeners for `formdata` and a link to this event's documentation.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/formdata/formdata`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/formdata/formdata/index.html
* Last commit: https://github.com/mdn/content/commit/5ecba2e39835dc1ea70a9094e9d6099fd2c8295c
* Document last modified: 2021-06-13T08:03:46.000Z

</details>

**Comment by ilogico** [comment]
Although compatibility data already exists in the [`formdata` event documentation](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/formdata_event), it would also be nice to have here and on the main `FormData` page.

**Comment by Biki-das** [comment]
Can you explain a little bit , what we exactly need to have on the formData page

**Comment by ilogico** [comment]
When you construct a FormData associated with a form element (`new FormData(formElement)`), the constructor will run the listeners attached to the form's `formdata` event, exposing the newly created FormData, and allowing the listeners to add or remove data to it.

When this event was introduced, documentation for it was added on its [own page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/formdata_event), but I think anyone reading about FormData should have a chance to learn this event exists.

I also feel the documentation on the formdata event is a bit misleading. I might be interpreting this wrong, but I believe the formdata event is meant for allowing the listeners to contribute to the FormData's construction. But the example in the documentation just shows an XMLHttpRequest being sent, which is something you could already do in the submit event.

**Comment by Josh-Cena** [comment]
The example was modified in https://github.com/mdn/content/pull/8973. Just missing some links where necessary.
