### ISSUE TITLE
Issue with "Array.prototype.flatMap()": map().flat() could be helpful

### ISSUE THREAD

**Issue by zachvictor** [mdn/content#7630]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

#### What information was incorrect, unhelpful, or incomplete?
There is nothing inherently wrong with the content on this page; however, I thought it _might_ be helpful to point out that the method name `flatMap` may be misleading for some, as the sequence it encapsulates is *not* `flat().map()` but actually `map().flat()`. 

It is possible that I am experiencing a cognition-related issue. 😬 On the face of it, I can understand why the compound word "flatMap" makes sense, for English compound words do indeed tend to read more often like `x(y())`, less like `y().x()` (interpreting functions/methods as verbs, I can understand "flatMap" as "flatten a mapped thing" or "flatten a map"). 

Nevertheless, in JS there is no such thing as `flat(map())`, and in defense of readers who might share my struggle, perhaps it is worth a few words of inline code to point our that `flatMap()` plays out as `map().flat()`. 

Yes, the second sentence does say, "It is identical to a `map()` followed by a `flat()`". I'm asking for that to be followed immediately by the JS-equivalent, to drive home the point. In that regard, it is worth noting that none of the "this is the same as that" examples in this article actually shows equivalent `flatMap()` and `map().flat()` statements.

#### Specific section or headline?
First paragraph.

#### What did you expect to see?
It is identical to a `map()` followed by a `flat()`: that is, `flatMap()` encapsulates `map().flat()`. 

#### Did you test this? If so, how?
Yes, using various examples in the Firefox  and Chrome dev consoles. For example (what follows is _not_ suggested material for the article—I'm just showing you what I was working with):

```javascript
// Convert variadic input to ? tokens as CSV for parameterized SQL w anon bind vars
const getBindTokens = (param, ...params) => [param, ...params].flat().map(val => '?').join(', ')

// getBindTokens: examples and tests
getBindTokens('a')
// "?"
getBindTokens('a', 2, ['c', 3, 'e'], 1, true)
// "?, ?, ?, ?, ?, ?, ?"


// getBindTokensOops - flatMap() is not flat().map() !
const getBindTokensOops = (param, ...params) => [param, ...params].flatMap(val => '?').join(', ')

// getBindTokensWhoops: examples and tests
getBindTokensOops('a')
// "?"
getBindTokensOops('a', 2, ['c', 3, 'e'], 1, true)
// "?, ?, ?, ?, ?"
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/flatmap`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/flatmap/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Would renaming the variable to `mapFlattened` be an improvement?

Or if not, could you suggest a different variable name that would be an improvement?

**Comment by sideshowbarker** [comment]
The issue description makes a valid point — it seems clear there’s some room for improvement here.

Would you be willing try using https://github.com/mdn/content/edit/main/files/en-us/web/javascript/reference/global_objects/array/flatmap/index.md to edit the source of the content directly, and make some changes to it yourself, in line with what you outlined in the issue description?

**Comment by zachvictor** [comment]
Yes, I am willing to try. I will read the guidelines and make an emendation for review.
