### ISSUE TITLE
Issue with "CDN": (short summary here please)

### ISSUE THREAD

**Issue by Abohelwa99** [mdn/content#7646]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/CDN

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/cdn`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/CDN
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/cdn/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

Unfortunately you didn't provide any information about the issue you are reporting. We cannot act on it.

I'm closing it. If you come back and provide more information, you are welcome to re-open it (or to fill a separate issue).

Thanks a lot for your interest!
