### ISSUE TITLE
Deprecated Property on Documentation for SVG clipPath Element

### ISSUE THREAD

**Issue by manngo** [mdn/content#7653]
In the documentation for the SVG `clipPath` element (https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath) the example uses the `use` element and the `xlink:href` attribute.

According to https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use#attributes, the `xlink:href` attribute has been deprecated in favour of the `href` attribute.

Should this be corrected?

**Comment by Ryuno-Ki** [comment]
Thanks for filling this issue, @manngo.
I put it in on my todo list to check, whether it works with `href`, too.

The change will likely require an update of the code sample, too. (I need to do some research what is required to do that).

**Comment by manngo** [comment]
Hi @Ryuno-Ki 

> whether it works with href, too

The `href` attribute worked for me on a number of different platforms, including Firefox.

Thanks

**Comment by Josh-Cena** [comment]
Fixed by #11463
