### ISSUE TITLE
Content bug: "Thunderbird Localization" page is gone missing

### ISSUE THREAD

**Issue by dminca** [mdn/content#7658]
## What page(s) did you find the problem on?

- https://www.thunderbird.net/en-US/get-involved/#qualityassurance
- https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Thunderbird/Thunderbird_Localization

## Specific page section or heading?

`/en-US/docs/Mozilla/Projects/Thunderbird/Thunderbird_Localization`

## What is the problem?

The page about _Thunderbird Localization_ is gone missing.

## What did you expect to see?

Thunderbird Localization information page.

## Did you test this? If so, how?

- Go to Thunderbird QA https://www.thunderbird.net/en-US/get-involved/#qualityassurance
- under Translation section, click _Thunderbird Localization_
- you will be redirected to MDN Web Docs with the error

> Sorry, the page `/en-US/docs/Mozilla/Projects/Thunderbird/Thunderbird_Localization` could not be found.

**Comment by hamishwillee** [comment]
That content moved off MDN proper [to the archive here](https://github.com/mdn/archived-content/blob/main/files/en-us/mozilla/projects/thunderbird/thunderbird_localization/index.html).

Projects are supposed to host their own docs now so this is not an MDN bug. I have reposted in https://bugzilla.mozilla.org/show_bug.cgi?id=1724655 and will close this.
