### ISSUE TITLE
Issue with "Deprecated tools": contradicts support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs

### ISSUE THREAD

**Issue by rjimeno** [mdn/content#7665]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Deprecated_tools

#### What information was incorrect, unhelpful, or incomplete?

"Scratchpad is deprecated as of Firefox 70 (bug 1565380), and will be removed as of Firefox 72 (bug 1519103)."

But the above contradicts:

https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs

The keyboard shortcuts in section 'Tools' lists the Scratchpad shortcut combination for Firefox 78 on a Mac. It reads:

"Scratchpad | Shift + F4"

But that does not work on Firefox 78 on a Mac.

If this problem should be reported elsewhere, please help me find the correct way to report it or forward this report on my behalf. I could not find a way to report the inconsistency for the other documentation webpage.

#### Specific section or headline?

"Scratchpad" section.

Conversely, the "Tools" section of https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs is wrong for Firefox 78 on a Mac and the entry should be removed.

#### What did you expect to see?

I expect to see consistent documentation. In other words,

https://developer.mozilla.org/en-US/docs/Tools/Deprecated_tools

and

https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs

should both match, but either is wrong (most probably  https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs) I found no way to report the problem with the other page (Keyboard shortcuts) so I'm reporting the inconsistency here.

#### Did you test this? If so, how?

I tried the key combination for the scratchpad (Shift + F4) on a Mac and it did not work. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/deprecated_tools`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Deprecated_tools
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/deprecated_tools/index.html
* Last commit: https://github.com/mdn/content/commit/23eebf57a003f8a933aad06436d78fe127f8223e
* Document last modified: 2021-02-02T16:49:47.000Z

</details>

**Comment by hamishwillee** [comment]
The MDN docs are consistent across the board in the pages you pointed out, the bug report, and in the release notes: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/72

So this looks like an issue with  https://support.mozilla.org/
Anyone know how to report bugs against that data?

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
