### ISSUE TITLE
Issue with "IndexedDB key characteristics and basic terminolog…": surprised to find an IDB in FF is entirely separate from an IDB in Chrome.  If true, the article sb more blunt in saying so.

### ISSUE THREAD

**Issue by HelmZalee** [mdn/content#7667]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Basic_Terminology

#### What information was incorrect, unhelpful, or incomplete?
Exactly how an IDB is uniquely identified is....murky. 

#### Specific section or headline?
Under "Every database has a name that identifies it within an origin.  In a paragraph headed IndexedDB adheres to a same-origin policy, we read "Every database has a name that identifies it within an origin".  Making that "Every database has a name that identifies it within an origin _and browser_ would improve it, but I think it is still unclear and inadequate.

Entirely separately, under "Key Characteristics", is this: "IndexedDB is a way for you to persistently store data inside a user's browser."  That's true, I suppose, but i think _very_ unexpected, as afaik nothing else about a site is permanently stored "within" a browser.  MS Word can read a PDF, and while formatting information may get lost and content garbled, I doubt that any content would disappear entirely.  Similarly, I don't expect data I enter using FF to disappear when I next visit the site with Chrome, and yet appear in FF.

If a user navigates to x.html and enters data the site says will be persistent, I think the user is entitled to expect it will be persistent _independent_ of what browser they next use to visit that site.  It is a surprise to find they will be wrong.

#### What did you expect to see?
I would expect at least a complete statement regarding the unique identification of an IDB, something like "An instance of an IDB is uniquely identified by name, origin, _**and browser**_".

#### Did you test this? If so, how?
Using Windows 10 & IIS, I built a site (localhost:81/idb.html) to test my understanding of IDB.  Once it "worked" in Firefox, I opened it in Chrome, and discovered that nothing I did in FF was reflected in Chrome, and vice-versa.  Then a google search found [this ](https://stackoverflow.com/questions/24648421/shared-indexeddb-store-between-different-web-browsers), with an answer that says "browsers can't access each other's data directly.".  Again, it is a surprise to learn that data a user enters into a site he is visiting belongs to the _browser_, and not the site.  I would guess this will be a big surprise to users as well.

I added the specific URL as, in writing this, I began to wonder if the db actually resides on the _server_.  I can't believe that's even possible w/o a great deal more coding, but the SO question alludes to cross-browser sharing using a server.  Putting the data on the site host seems to me to loose the utility of IDB entirely though.

My apologies if I am completely missing something.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/indexeddb_api/basic_terminology`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Basic_Terminology
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/indexeddb_api/basic_terminology/index.html
* Last commit: https://github.com/mdn/content/commit/edec63821384a17d23d229a810d217246ef44701
* Document last modified: 2021-07-09T11:46:29.000Z

</details>

**Comment by sideshowbarker** [comment]
> If a user navigates to x.html and enters data the site says will be persistent, I think the user is entitled to expect it will be persistent _independent_ of what browser they next use to visit that site. It is a surprise to find they will be wrong.

The thing is that in general when writing about this platform, when we say “user”, it doesn’t mean “person”. The same physical person may be multiple “users” — when a person has two different browsers on their local machine, that’s necessarily two different ”users”. When you visit a website from two different browsers running on your computer, that site doesn’t have any way to automatically recognize that it’s the same person visiting. Instead, it just sees two different “users”.

Every browser you run represents a different user. In fact, even within the same browser, if you have multiple browser profiles, they are different users.

Consider the case where you do have multiple profiles within the same browser, profile A and profile B. In that case, would you want profile B to automatically get all the IndexedDB storage from profile A?

Rather, you use different profiles A and B to in fact ensure that data/state stored for B is kept separate from data/stated stored for A.

So it’s the same across whatever different browsers you’re running. The different browsers on your computers can just be seen as different logical profiles.

> Similarly, I don't expect data I enter using FF to disappear when I next visit the site with Chrome, and yet appear in FF.

Replacing “FF” there with “profile A” and “Chrome” with “profile B”, we get this:

> I don't expect data I enter using profile A to disappear when I next visit the site with profile B, and yet appear in profile A.

So of course the data doesn’t disappear — instead it’s a matter of the data being intentionally kept separate, but design.

We can do the same by replacing “browser” in other parts of the issue description with “profile”:

> If a user navigates to x.html and enters data the site says will be persistent, I think the user is entitled to expect it will be persistent _independent_ of what profile they next use to visit that site. It is a surprise to find they will be wrong.
> 
> Again, it is a surprise to learn that data a user enters into a site he is visiting belongs to the _profile_, and not the site. I would guess this will be a big surprise to users as well.

To frame it slightly different in terms of you as a user: If you’re running two different browsers on your computer, and visiting the same site, that’s logically no different than if you were running a thousand different browsers on your computer, and visiting that same site. And *that* is logically no different than if you were running a thousand different computers, with one browser each on them, and visiting the same site. And to the site, that’s logically no different than a thousand different people visiting the site.

And clearly if you were one of those thousand different people visiting the site, you wouldn’t want the IndexedDB storage from the other 999 people to end up somehow automatically persisting into your personal IndexedDB storage for that site in your browser.

**Comment by HelmZalee** [comment]
Thank you for the careful and informative reply.  

Please bear with me here, I'm an old retired Fortran guy, self-taught in js, html, css etc.  Things obvious to you may not be obvious to me.  Writing this succinctly is a struggle.

Let me look at just one of your points: visiting one site with each of 1k browsers on _my_ desktop is logically no different than 1k _different_ people visiting that site, each on their own desktop, and if (interpreting your text here) the IDB were not specific to my _browser_, changes made to the IDB by those 1k different visitors might "...persist into [my] **personal** IDB storage...".

Then something is very wrong with my understanding of IDB.  I hope you can help me correct it.  

From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) it seems the IDB is _local to the client_: "IndexedDB is a low-level API for **client-side storage**" (emphasis mine).  How might client-side "...storage from the other 999 (visitors to the _server_)" persist into my browser?

As an aside, it looks like Firefox _implements_ IDB with its own internal SQL Light .  I find a .sqlite file at C:\Users\...AppData\...\Firefox...\storage\...\idb.  It has a recent timestamp.  It is mostly binary, but in it is an IDBIndex name from my IDB.  It seems an unlikely coincidence.  

This SQLite file seems a likely candidate for the "client-side storage" the MDN article mentions.

Getting back to changes made by 999 visitors ",,,persisting into [my personal] IDB storage": how would this data make its way from one client-side to another?  

It does appear that multiple _firefox_ clients running the same html under the same username on a single desktop will be using the same IDB (or sqllit) db.  The arrangement would likely cause problems.  I don't think it's the same as Bill down the street on his desktop affecting the IDB on my desktop.

My js has no Ajax code, my html makes no submit requests.  Once the page is loaded, I think there is no further communication with the server.  Though it's buggy and not very clean code, I'll attach it, only so this claim might be verified.  Not looking for any sort of analysis.

And thank you for taking the time to make the thorough reply (above).  Sorry I'm being so uncomprehending.

[idb.html.txt](https://github.com/mdn/content/files/6951439/idb.html.txt)
[IDB.js.txt](https://github.com/mdn/content/files/6951440/IDB.js.txt)

**Comment by HelmZalee** [comment]
Yes, I entirely missed the point.  Cookies and IDB are specific to a browser.  I shudda known...in general, application A should not have access to data belonging to application B.  Cookies and IDB are application resources, not OS resources.

**Comment by teoli2003** [comment]
Cool. I propose we close this issue then.
