### ISSUE TITLE
Issue with "Using CSS gradients": (linear-gradient animations)

### ISSUE THREAD

**Issue by riverleaf** [mdn/content#7670]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Using_CSS_gradients

#### Animated linear-gradient section, example: 2 styles transition, 1. background-image: linear-gradient(180deg, dodgerblue, forestgreen); background-image: 2. linear-gradient(180deg, deepskyblue, limegreen); And then, is there a way to hint linear-gradient transitions?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_images/using_css_gradients`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Using_CSS_gradients
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_images/using_css_gradients/index.html
* Last commit: https://github.com/mdn/content/commit/2c11e2b6b6b50b659020841048cd861b0aac8f74
* Document last modified: 2021-07-26T21:30:07.000Z

</details>

**Comment by riverleaf** [comment]
Is there a way to hint linear-gradient transitions?  Noting that gradients are not comma-separated... Something like:
linear-gradient(180deg, dodgerblue, forestgreen); 10%;  linear-gradient(180deg, deepskyblue, limegreen);

**Comment by rachelandrew** [comment]
Are you asking for some new content to be written about animations? I don't see any incomplete section here.

**Comment by rachelandrew** [comment]
Closing as OP didn't reply to the question. Please re-open if you have the info requested.
