### ISSUE TITLE
Issue with "padding": (short summary here please)

### ISSUE THREAD

**Issue by chavooshA** [mdn/content#7676]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/padding

#### What information was incorrect, unhelpful, or incomplete?
/* top | horizontal | bottom */
padding: 1em 2em 2em;

In the above statement "horizontal" is wrong, "vertical" is true

**Comment by chavooshA** [comment]
/* top | horizontal | bottom */
padding: 1em 2em 2em;

In the above statement "horizontal" is wrong, "vertical" is true

**Comment by teoli2003** [comment]
Thanks! I opened a PR with a fix.

Good catch!
