### ISSUE TITLE
Content bug: Link to wrong page

### ISSUE THREAD

**Issue by Nurou** [mdn/content#7687]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction#core_interfaces_in_the_dom

## What is the problem?

In the common API listing, document.querySelectorAll links to element.querySelectorAll instead of the page for document.querySelectorAll.

## What did you expect to see?

N/A

## Did you test this? If so, how?

N/A

**Comment by teoli2003** [comment]
Thanks! I opened a PR to get this fixed.
