### ISSUE TITLE
Issue with "How do you set up a local testing server?": (text flows out of div)

### ISSUE THREAD

**Issue by dhavall08** [mdn/content#7693]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server

#### What information was incorrect, unhelpful, or incomplete?
Texts are flowing out of the div due to a `code` tag wrapper. Therefore, the page is showing horizontal scrollbar without fitting to screen in mobile as well as desktop site.

#### Specific section or headline?
AFAIK, following two places cause the issue:

For this particular page in a web browser,
1. The unnecessary `code`  HTML tag inside of the `div` tag where the inner text is "Note: Older versions of Python..."...
2. Another `code` HTML tag right after the above `div`...

are causing the problem. As, those lines are wrapped with `code` tag which is why they're flowing out.

However, while looking into the source .html file of same page in Github, I couldn't find that html tags surrounding that texts. So, not sure where to find and fix that issue.

#### What did you expect to see?
The page should be displayed without horizontal scrollbar and text shouldn't be flowing out of div.

#### Did you test this? If so, how?
I tried with opening the page in Chrome, Firefox with different devices (Windows, Android) and all have this issue.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/common_questions/set_up_a_local_testing_server`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/set_up_a_local_testing_server/index.html
* Last commit: https://github.com/mdn/content/commit/4eface0d5f7fccbc69b1b4745847d5d285439cf5
* Document last modified: 2021-08-05T15:57:25.000Z

</details>

**Comment by meowmeowmeowcat** [comment]
Thanks! I've opened a PR and it should fix this issue.
