### ISSUE TITLE
Issue with "Multiple-column layout": (broken feature / missing instructions)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#7718]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Multiple-column_Layout

#### What information was incorrect, unhelpful, or incomplete?
![Untitled](https://user-images.githubusercontent.com/51193876/128647024-c9b64e7d-cd63-4c6d-ba17-c98515bc12aa.jpg)

#### Specific section or headline?
Columns and fragmentation

#### What did you expect to see?
There is no live example below. Furthermore, the reader is instructed to modify the code, but has never been told to obtain the code in any way.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/css_layout/multiple-column_layout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Multiple-column_Layout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/multiple-column_layout/index.html
* Last commit: https://github.com/mdn/content/commit/98e438b7d2e79c7dc04c72ca7e2f3bf36a84940f
* Document last modified: 2021-01-22T05:20:39.000Z

</details>

**Comment by rachelandrew** [comment]
Closing as I believe this was dealt with in https://github.com/mdn/content/pull/7721

**Comment by ConsciousClay** [comment]
I didn't fix this in #7721
