### ISSUE TITLE
Issue with "ReferenceError: "x" is not defined": (short summary here please)

### ISSUE THREAD

**Issue by samim69** [mdn/content#7723]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined

#### What information was incorrect, unhelpful, or incomplete?
this.frame_0 = function() {
		this.stop();
		var stage = new createjs.Stage("myCanvas");
		var barWidth = 200; //Bar geniÅŸliÄŸi
		var evTg = evt.currentTarget;
		var p = this.globalToLocal(evt.stageX, evt.stageY);
		evTg.x = p.x;
		var evTg1 = evt.currentTarget;
		var p = this.globalToLocal(evt.stageX, evt.stageY);
		evTg1.x = p.x;
		var evTg2 = evt.currentTarget;
		var p = this.globalToLocal(evt.stageX, evt.stageY);
		evTg2.x = p.x;
		if (!this.btn_click_cbk) {
			function btn_click(evt) {
				var evTg = evt.currentTarget;
				var evTg1 = evt.currentTarget;
				var evTg2 = evt.currentTarget;
				var evTg1.x = p.x;
				var evTg2.x = p.x;
		
				var b = Math.floor(5 * (evTg1.x / barWidth));
				var a = Math.floor(90 * (evTg2.x / barWidth));
				var c = Math.floor(5 * (evTg.x / barWidth));
		
				/*var d = Math.sin(a) * (Math.PI / 180);*/
				/*var e = Math.round(Math.asin(c * d) * (180 / Math.PI));*/
				var e = ((c * a) / b) * (180 / Math.PI);
				//var sinbr = Number((Math.round(n1.value * sinar) / n2.value) * 100) / 100;
				/*	console.log(e);
				console.log(c);
				console.log(b);
				console.log(a);*/
				this.info_4.text = a * (Math.PI / 180);
				this.info_5.text = e;
				// Start your custom code
				console.log("Button clicked");
				// End your custom code
			}
			$("#dom_overlay_container").on("click", "#btn", btn_click.bind(this));
			this.slider_btn1_click_cbk = true;
		}
		
		if (!this.slider_btn1_click_cbk) {
			function slider_btn1_click(evt) {
				var evTg = evt.currentTarget;
				var p = this.globalToLocal(evt.stageX, evt.stageY);
				evTg.x = p.x;
				if (evTg.x < 0) {
					evTg.x = 0;
				} else if (evTg.x > barWidth) {
					evTg.x = barWidth;
				}
				var c = Math.floor(5 * (evTg.x / barWidth));
				/*1.ortamÄ±n kÄ±rÄ±lma indisi*/
		
				//FaktÃ¶t 0 ile 1
				this.info_1.text = c;
				// Ã–zel kodunuzu baÅŸlatÄ±n
				console.log("Button clicked");
				// Ã–zel kodunuzu sonlandÄ±rÄ±n
			}
			$("#dom_overlay_container").on("click", "#slider_btn1", slider_btn1_click.bind(this));
			this.slider_btn1_click_cbk = true;
		};
		if (!this.slider_btn2_click_cbk) {
			function slider_btn2_click(evt) {
				var evTg1 = evt.currentTarget;
				var p = this.globalToLocal(evt.stageX, evt.stageY);
				evTg1.x = p.x;
				if (evTg1.x < 0) {
					evTg1.x = 0;
				} else if (evTg1.x > barWidth) {
					evTg1.x = barWidth;
				}
				var b = Math.floor(5 * (evTg1.x / barWidth));
				/*2.ortamÄ±n kÄ±rlma indisi*/
		
				//FaktÃ¶t 0 ile 1
				this.info_2.text = b; //
				// Ã–zel kodunuzu baÅŸlatÄ±n
				console.log("Button clicked");
				// Ã–zel kodunuzu sonlandÄ±rÄ±n
			}
			$("#dom_overlay_container").on("click", "#slider_btn2", slider_btn2_click.bind(this));
			this.slider_btn2_click_cbk = true;
		}
		
		
		
		if (!this.slider_btn3_click_cbk) {
			function slider_btn3_click(evt) {
				var evTg2 = evt.currentTarget;
				var p = this.globalToLocal(evt.stageX, evt.stageY);
				evTg2.x = p.x;
				if (evTg2.x < 0) {
					evTg2.x = 0;
				} else if (evTg2.x > barWidth) {
					evTg2.x = barWidth;
				}
				var a = Math.floor(90 * (evTg2.x / barWidth));
				/*1.ortamdan 2.ortama Gelme aÃ§Ä±sÄ±*/
				this.info_3.text = a;
				this.info_4.text = a * (Math.PI / 180);
				// Ã–zel kodunuzu baÅŸlatÄ±n
				console.log("Button clicked");
				// Ã–zel kodunuzu sonlandÄ±rÄ±n
			}
			$("#dom_overlay_container").on("click", "#slider_btn3", slider_btn3_click.bind(this));
			this.slider_btn3_click_cbk = true;
		}
	}

#### Did you test this? If so, how?
Uncaught SyntaxError: unexpected token: '.'
Uncaught ReferenceError: AdobeAn is not defined

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/not_defined`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/not_defined/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting, and fixing, problems in the MDN documentations.

It looks like you are looking for help with your code. Unfortunately, we don't have enough availability to help you.

May I suggest you ask your question on a specialized web site, like StackOverflow?

I'm closing this issue. If I've misunderstood you and you were reporting a problem in the documentation, feel free to reopen the issue, and to provide more information so we can understand the problem.

Thanks for your interest.
