### ISSUE TITLE
Content bug: Select is not visible at the example (Web/CSS/background-blend-mode)

### ISSUE THREAD

**Issue by shapkarin** [mdn/content#7724]
Page: https://developer.mozilla.org/en-US/docs/Web/CSS/background-blend-mode
Section: [Try out different blend modes](https://developer.mozilla.org/en-US/docs/Web/CSS/background-blend-mode#try_out_different_blend_modes)

Select is not visible
<img width="929" alt="Screenshot 2021-08-09 at 03 27 19" src="https://user-images.githubusercontent.com/1463086/128650342-6ffd4772-5d9e-43b5-b090-117192766f90.png">

Expected (to be visible):
<img width="806" alt="Screenshot 2021-08-09 at 03 29 11" src="https://user-images.githubusercontent.com/1463086/128650395-c9c17333-2914-427b-98c2-0e804a50e11e.png">

**Comment by teoli2003** [comment]
Closing. Fixed by #7725.

@shapkarin  A small tip, if you add "Fixes #7724" (where #7724 is the issue the PR fixes) in the description of the PR, it automatically close the issue, when the PR is merged.

**Comment by shapkarin** [comment]
> Closing. Fixed by #7725.
> 
> @shapkarin A small tip, if you add "Fixes #7724" (where #7724 is the issue the PR fixes) in the description of the PR, it automatically close the issue, when the PR is merged.

@teoli2003 I know, just forgot to use. it also has some aliases like `close`, `closes`, `fix` and etc

**Comment by teoli2003** [comment]
No problem! Thanks a lot!
