### ISSUE TITLE
Issue with "CanvasRenderingContext2D.drawImage()": …

### ISSUE THREAD

**Issue by raymond1** [mdn/content#773]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

#### What information was incorrect, unhelpful, or incomplete?
The API entry for the dx and dy parts say:
...Note that this argument is not included in the 3-argument syntax.

But that is not true. The argument is included in the 3-argument syntax.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/drawimage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/canvasrenderingcontext2d/drawimage/index.html
* Report started: 2020-12-30T16:48:02.561Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/837 with a fix.
