### ISSUE TITLE
Issue with "HTMLTableRowElement": clarity on delectCell()

### ISSUE THREAD

**Issue by manngo** [mdn/content#7731]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableRowElement

#### What information was incorrect, unhelpful, or incomplete?

The documentation states:

> `HTMLTableRowElement.deleteCell()`
> Removes the cell at the given position in the row. If the given position is greater (or equal as it starts at zero) than the amount of cells in the row, or is smaller than 0, it raises a DOMException with the IndexSizeError value.

#### Specific section or headline?

HTMLTableRowElement.deleteCell()

#### Comment

In my own testing, `deleteCell(-1)` removes the last cell from the table row. That appears to contradict the statement that if it is smaller than 0 it raises a DOMException.

The cited HTML standard document states:

>The position is relative to the cells in the row. The index −1 is equivalent to deleting the last cell of the row.
>If the given position is less than −1 or greater than the index of the last cell, or if there are no cells, throws an "IndexSizeError" DOMException.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmltablerowelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableRowElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmltablerowelement/index.html
* Last commit: https://github.com/mdn/content/commit/3a5d65124798f70ef4777aef7ab11b7e9a5b7dbf
* Document last modified: 2021-06-13T14:10:35.000Z

</details>

**Comment by teoli2003** [comment]
Thanks! I opened a PR with a fix.
