### ISSUE TITLE
[Media] AVIF support

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#7744]
[Enable AVIF support by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1682995) Looks like AVIF support is finally here

## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- AVIF support is enabled by default

## Related Gecko bugs

- [Enable AVIF support by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1682995)
- 

## Other

Fixes #1726

**Comment by hamishwillee** [comment]
Status

Status
- [x] Remove from Experimental Features page - https://github.com/mdn/content/pull/7873
- [ ] Docs - Release notes
- [ ] Docs: [List of default accept values](/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values) -  https://github.com/mdn/content/pull/7873
- [ ] Docs: Other stuff reverted in https://github.com/mdn/content/pull/2601 and https://github.com/mdn/content/pull/2590
   -  this is mostly removing info about firefox restrictions in the image format docs.
- [ ] BCD 
- [ ] dev-docs-complete

**Comment by hamishwillee** [comment]
I think this is all good/ready to review

**Comment by Rumyra** [comment]
Brill - thanks so much @hamishwillee 👍
