### ISSUE TITLE
[WebAPI] dragexit event no longer supported

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#7748]
[Remove support for the dragexit event](https://bugzilla.mozilla.org/show_bug.cgi?id=1635018) dragexit was removed from spec and has now been removed from FF

## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Remove dragexit event (or update docs to show deprecated), update bcd

## Related Gecko bugs

- [Remove support for the dragexit event](https://bugzilla.mozilla.org/show_bug.cgi?id=1635018)

**Comment by hamishwillee** [comment]
dragexit/ondragexit were removed from spec and have already been [marked deprecated and non-standard in BCD](https://github.com/mdn/browser-compat-data/pull/6710). There are no pages for the feature as a whole in MDN, but the events are linked in many others. 
This change removes the feature from FF92 nightly (interprets it as a dragleave). 

I think we should remove all mentions in docs other than the new one in the release notes, and update BCD. This is on the way out. 

- [ ] Confirm if is actually all versions. 
- [ ] BCD - 
- [ ] Docs - remove all mentions
- [ ] Docs - remove from sidebar in https://developer.mozilla.org//en-US/docs/Web/API/HTML_Drag_and_Drop_API
- [ ] Release note
- [ ] dev-doc-complete

**Comment by hamishwillee** [comment]
OK, I'm closing this because the change is limited to nightly and won't be in the actual release: https://bugzilla.mozilla.org/show_bug.cgi?id=1635018#c13

@Rumyra I guess this means we still don't have an easy way of knowing which stuff actually affects a release build. 

I am completely happy that https://github.com/mdn/content/pull/8113 already went in - anyone using this now shouldnt be. When this fix goes "live" there will be less work.
