### ISSUE TITLE
[NO DOCS REQUIRED] [webAPI] Enable dom.events.coalesce.touchmove in all channels

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#7750]
**NO DOCS REQUIRED. Engineering [have confirmed](https://bugzilla.mozilla.org/show_bug.cgi?id=1720200#c7) that this is effectively an internal optimisation. It has no API chance or effect on specs.**

[Enable dom.events.coalesce.touchmove in all channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1720200) Will be default in 92. IIRC the doc work has been done, so update to bcd & rel notes here

## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- dom.events.coalesce.touchmove default in 92

## Related Gecko bugs

- [Enable dom.events.coalesce.touchmove in all channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1720200)

**Comment by hamishwillee** [comment]
>IRC the doc work has been done

Hi @Rumyra, what makes you think that has been done? 
- I searched on  `dom.events.coalesce.touchmove` and the pref is not documented. 
- I searched for coalescing and found this for pointer events: [`PointerEvent.getCoalescedEvents()`](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/getCoalescedEvents). 
  - From this I infer that coalescing is a mechanism for sending a bunch of signals from a single event notification - so you can go back and get the moves if the browser couldn't fire the event fast enough.
  - But I don't see any similar method for touch events -searched in [Touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events), [Document: touchmove_event](https://developer.mozilla.org/en-US/docs/Web/API/Document/touchmove_event), [Element: touchmove event](https://developer.mozilla.org/en-US/docs/Web/API/Element/touchmove_event)

So I'm wondering whether perhaps I just don't know what coalescing means in this context. Anyway, I can ask in the bug, but assuming this was already documented I thought I should try you first.

**Comment by hamishwillee** [comment]
PS @Rumyra Just FYI, the big ugly **[NO DOCS REQUIRED]** is there so when you do your review or release notes it is obvious what you can omit. If you would rather I didn't do this, or we had some other way (a project column?) to indicate dropped docs work then just let me know what will work best for you.
