### ISSUE TITLE
[CSS] Implement break-inside: avoid-{page,column}

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#7753]
[Implement break-inside: avoid-{page,column}](https://bugzilla.mozilla.org/show_bug.cgi?id=1722945) Seems some doc updates have happened https://bugzilla.mozilla.org/show_bug.cgi?id=1722945#c7 worth an edit review

## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

- [Implement break-inside: avoid-{page,column}](https://bugzilla.mozilla.org/show_bug.cgi?id=1722945)

**Comment by rachelandrew** [comment]
Thanks to @SebastianZ these are already done pending merging of BCD.

**Comment by rachelandrew** [comment]
https://github.com/mdn/browser-compat-data/pull/11924

**Comment by syedaasim033** [comment]
i would love to contribute

**Comment by Rumyra** [comment]
I'm tidying up the project & closing with the notion that BCD will happen 👍
