### ISSUE TITLE
[webAPI] document.onselectionchange does not detect changes on input/textarea

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#7755]
[document.onselectionchange does not detect changes on input/textarea](https://bugzilla.mozilla.org/show_bug.cgi?id=1648944) Seems like a bug fix, so worth checking the docs reflect spec

## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Check docs reflect spec

## Related Gecko bugs

- [document.onselectionchange does not detect changes on input/textarea](https://bugzilla.mozilla.org/show_bug.cgi?id=1648944)

**Comment by hamishwillee** [comment]
Yes, this looks like a bug fix - on FF previously this was a bit like a focuschange. Text selections inside `textarea` or `input` elements were being ignored. This looks like the result of a spec ambiguity - which has sensibly been fixed. Still confirming.

- [ ] Confirm how this works: https://bugzilla.mozilla.org/show_bug.cgi?id=1648944#c17
- [ ] Docs - probably we need `selectionchanged event` docs for `textarea` and `input`, to fix up the handler to note what kind of event is received. Probably also need BCD note to indicate the version in which we start getting the events. Maybe some better examples.
- [ ] Release note
- [ ] BCD
- [ ] dev-doc-complete

**Comment by Rumyra** [comment]
I'm tidying up the project & closing with the notion that BCD will happen 👍
