### ISSUE TITLE
[webAPI] Implement the imperative slotting API

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#7756]
[Implement the imperative slotting API](https://bugzilla.mozilla.org/show_bug.cgi?id=1705141)

## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- Imperative slotting API

## Related Gecko bugs

- [Implement the imperative slotting API](https://bugzilla.mozilla.org/show_bug.cgi?id=1705141)

**Comment by jpmedley** [comment]
Some of these pages already exist, but may need review:

- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/name
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedNodes
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedElements
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event

Needs to be created:

- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assign

**Comment by Rumyra** [comment]
@jpmedley thank you so much 🙏

**Comment by Rumyra** [comment]
Hi @rachelandrew do we just need rel notes for this now?

**Comment by Rumyra** [comment]
Added 👍
