### ISSUE TITLE
A big Specifications page with a table

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#776]
A found this file:
https://www.github.com/mdn/yari/tree/master/kumascript%2Fmacros%2FSpecData.json

Should be intresting to have a page with a big `table` showing this data.

## Specifications

| Name | Href |...|
|------|------|---|
| ...  | ...  |...|

Or a list eventually 👎

## Specifications

1. 3 - [href]() - ... - ...;
2. 4 - [href]() - ... - ...;
3. 1 - [href]() - ... - ...;

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/pull/2292

**Comment by jpmedley** [comment]
It's an intriguing idea. Increasing perusal of the data would stir up more corrections. But that might increase the potential for breaking links elsewhere on the site.

**Comment by mattiapontonio** [comment]
@jpmedley 
I'll reveal the trick right away. I would like to increase the likelihood of improving data structures by multiplying use cases. 🧞 || 🤹‍♂️

**Comment by mattiapontonio** [comment]
But to close this issue I think we just have to take the JSON and manually transform it into an HTML table, but to do so we would need the guarantee that the thing is merged and someone's interested.

**Comment by mattiapontonio** [comment]
This could also be done with the BC table. You take it, put it on a hard-coded page, and let it grow 🌱 on its own in HTML only in love with minimalist. 
When it is ripe 🌳 you put it in a macro 🌳🌳🌳.

I don't know if you already cultivate like this 👨‍🌾. 
But it must be said somewhere.

**Comment by mattiapontonio** [comment]
Something off topic of which I am not an expert but which seems interesting to me

https://en.m.wikipedia.org/wiki/Theory_of_constraints

**Comment by jpmedley** [comment]
>You take it 1, put it on a hard-coded page (something real, when people are that not only us), and let it grow 🌱 on its own in HTML only in love with minimalist.

That's not really an option since this data is used by every reference page on the site. This is the source for what's in all the specification tables.
