### ISSUE TITLE
Issue with "ServiceWorkerRegistration.updateViaCache": not a method, it's a string typed property

### ISSUE THREAD

**Issue by Rolf-B** [mdn/content#7760]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/updateViaCache

#### What information was incorrect, unhelpful, or incomplete?

This is not a method, it's a string typed property

#### Specific section or headline?

all

#### What did you expect to see?

Description of property. It reflects the value of updateViaCache property of the options-Parameter in register(). The value of the property affects the behaviour of a ServiceWorker update.

#### Did you test this? If so, how?

(1) Register a serviceworker, set a breakpoint, inspect the ServiceWorkerRegistration object
(2) Read the spec - V1 and nightly

Sorry that I don't create a pull request. But I don't want to become a MDN author, because of lack of expertise AND time. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/serviceworkerregistration/updateviacache`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/updateViaCache
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/serviceworkerregistration/updateviacache/index.html
* Last commit: https://github.com/mdn/content/commit/cad672e1d7ab78a63f60a5d79914520b1486b534
* Document last modified: 2021-07-29T14:32:30.000Z

</details>

**Comment by dontcallmedom** [comment]
this is indeed bogus; the description and categorization would also need to be fixed in https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration

**Comment by Blakelist7** [comment]
If someone else wants to work on this, please do so; I'm currently occupied with other tasks.

**Comment by timeowilliams** [comment]
I haven't contributed to MDN yet, but I'd like to have this be my first contribution. Request to be assigned.

**Comment by timeowilliams** [comment]
@Rolf-B 

Before moving on with this, I just need some clarification. When looking at the docs from these two sources: 
1. https://w3c.github.io/ServiceWorker/#dom-serviceworkerregistration-updateviacache
2. https://w3c.github.io/ServiceWorker/#enumdef-serviceworkerupdateviacache

the updateViaCache is labelled as a getter, which to my knowledge is consistent with it being a method. If all this is accurate, is it necessary to revise the MDN docs on this?

**Comment by himanshugarg** [comment]
Thanks @timeowilliams for your time. The docs match the spec and no further updates might be needed. See also #14377

**Comment by sideshowbarker** [comment]
I’m going ahead and closing this a fixed by #14377. It can be revisited if it turns out we missing something.
