### ISSUE TITLE
Content bug: Some of the youtube videos are unavailable.

### ISSUE THREAD

**Issue by AnilSeervi** [mdn/content#7768]
I've gathered some pages that have this issue :
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization
- https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox
- https://developer.mozilla.org/en-US/docs/Tools/Style_Editor
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Add_a_button_to_the_toolbar
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests 
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Implement_a_settings_page
- https://developer.mozilla.org/en-US/docs/Tools/Performance/Scenarios/Animating_CSS_properties
- https://developer.mozilla.org/en-US/docs/Tools/Performance/Scenarios/Intensive_JavaScript
- https://developer.mozilla.org/en-US/docs/Tools/Performance/Allocations
- https://developer.mozilla.org/en-US/docs/Tools/Performance/Flame_Chart
- https://developer.mozilla.org/en-US/docs/Tools/Performance/UI_Tour
- https://developer.mozilla.org/en-US/docs/Tools/Memory/Basic_operations
- https://developer.mozilla.org/en-US/docs/Tools/Memory/Aggregate_view
- https://developer.mozilla.org/en-US/docs/Tools/Memory/Dominators_view
- https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Set_a_conditional_breakpoint
- https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Disable_breakpoints
- https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Step_through_code

**Comment by wbamberg** [comment]
See also https://github.com/mdn/content/issues/7457.

**Comment by sideshowbarker** [comment]
Since we already have https://github.com/mdn/content/issues/7457 open for this, I copied the issue description from this issue over to that issue as a comment — https://github.com/mdn/content/issues/7457#issuecomment-899161971. So I’m going ahead and closing this issue.
