### ISSUE TITLE
Issue with "Node.getRootNode()": typo in the text

### ISSUE THREAD

**Issue by mlejva** [mdn/content#778]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode

#### What information was incorrect, unhelpful, or incomplete?
There's a typo in the following paragraph
>This more complex example shows the difference between returning a normal root, and a root incuding the shadow root. (See the full source code):

#### Specific section or headline?
Section `Examples`.

#### What did you expect to see?
The word with a typo is `incuding`. Instead, it should be `including`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/node/getrootnode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/node/getrootnode/index.html
* Report started: 2020-12-30T18:44:53.717Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much - fixed by #783. FYI for these little typos, just as easy to select the "Source on GitHub" link at the bottom of every page and just make the change :-)
