### ISSUE TITLE
Issue with "Regular expressions": Tables with rowspan looks broken

### ISSUE THREAD

**Issue by NagayamaToshiaki** [mdn/content#7780]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

#### What information was incorrect, unhelpful, or incomplete?
Tables with rowspan lacks vertical border in the right of the rowspan cell, except for the first one.

#### Specific section or headline?
"Results of regular expression execution." inside Using regular expressions in JavaScript

#### What did you expect to see?
The right border of the rowspan cell should illustrate correctly.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/regular_expressions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by AnilSeervi** [comment]
I've opened a PR in [mdn/mdn-minimalist](https://github.com/mdn/mdn-minimalist) regarding a fix for this issue.
