### ISSUE TITLE
Issue with "font-family": Drop info about IE6

### ISSUE THREAD

**Issue by NagayamaToshiaki** [mdn/content#7786]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

#### What information was incorrect, unhelpful, or incomplete?
(However, this doesn't work in Internet Explorer 6 or earlier.)
IE6 has been unsupported for 7 years, and discontinued Windows XP supports IE8.

#### Specific section or headline?
The first section.

#### What did you expect to see?
The remark to be unseen.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/font-family`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-family/index.html
* Last commit: https://github.com/mdn/content/commit/97e37d7edce2ca724011258da4b1e264eeae1531
* Document last modified: 2021-07-31T01:38:11.000Z

</details>

**Comment by teoli2003** [comment]
Thanks, I opened a PR to get it removed.
