### ISSUE TITLE
Issue with "padding": Incorrect comment in syntax section.

### ISSUE THREAD

**Issue by defmech** [mdn/content#7792]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/padding

#### What information was incorrect, unhelpful, or incomplete?

```
/* top | vertical | bottom */
padding: 1em 2em 2em;
```

should be

```
/* top | horizontal | bottom */
padding: 1em 2em 2em;
```

Second value, when three values, is the horizontal value.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/padding`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/padding
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/padding/index.html
* Last commit: https://github.com/mdn/content/commit/a5ecd34055c668eeadd0531a491a0aee7954a6dc
* Document last modified: 2021-08-07T08:45:55.000Z

</details>

**Comment by teoli2003** [comment]
I just "corrected" this a few days ago. I wonder if I wasn't awake that day.

Let me ponder a bit on this and check similar pages so that all is correct and coherent. 

I'll happily review a PR that comes before I can go back to this!

**Comment by teoli2003** [comment]
Thanks for the report, @defmech ; thanks for the fix @AnilSeervi . And sorry for having introduced that error last week, I don't know what I thought.
