### ISSUE TITLE
Issue with "Multiple-column layout": (broken feature / missing instructions)

### ISSUE THREAD

**Issue by ConsciousClay** [mdn/content#7801]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Multiple-column_Layout

#### What information was incorrect, unhelpful, or incomplete?
Sometimes, this breaking will happen in places that lead to a poor reading experience. **In the live example below**, I have used multicol to lay out a series of boxes, each of which have a heading and some text inside. The heading becomes separated from the text if the columns fragment between the two.

...

To control this behavior we can use properties from the CSS Fragmentation specification. This specification gives us properties to control breaking of content in multicol and in paged media. For example, **add the property break-inside with a value of avoid to the rules for .card.** This is the container of the heading and text, and therefore we do not want to fragment this box.

#### Specific section or headline?
Columns and fragmentation

#### What did you expect to see?
There is no live example below. Also, the reader is instructed to modify the code, but has never been told to obtain the code in any way.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/css_layout/multiple-column_layout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Multiple-column_Layout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/multiple-column_layout/index.html
* Last commit: https://github.com/mdn/content/commit/98e438b7d2e79c7dc04c72ca7e2f3bf36a84940f
* Document last modified: 2021-01-22T05:20:39.000Z

</details>

**Comment by rachelandrew** [comment]
This issue appears to have been raised on a previous version of the document before changes that were made on it recently. I've searched the text for the phrases and they do not exist in the document.
