### ISSUE TITLE
Issue with "Setting up your own test automation environment": confusion about shell script

### ISSUE THREAD

**Issue by mattiasinokuchi** [mdn/content#7816]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment

#### What information was incorrect, unhelpful, or incomplete?
bash is no longer default on mac OSX.

#### Specific section or headline?
Setting up Selenium in Node

#### What did you expect to see?
An alternative using zsh or how to switch to bash `(exec bash)`

#### Did you test this? If so, how?
Switched back to bash.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.html
* Last commit: https://github.com/mdn/content/commit/3af43c1dcfb9be19c73cf3fdd1178db9c74aa064
* Document last modified: 2021-04-27T01:03:07.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #7868 with a fix.
