### ISSUE TITLE
Update index.html title not very helpful

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#782]
Github bases issue names based on the title. Because all our files are named index.html we end up with lots of issues named   **Update index.html**. 

Can we trick github to grab the name from the parent folder by default?

**Comment by chrisdavidmills** [comment]
This is an interesting point. @escattone @peterbe is there a way we can do this?

**Comment by nschonni** [comment]
Maybe as a stop-gap (as I don't think you can fix the GitHub behaviour), would be to add a small CI job to fail if the title is "Update index.html" and add a comment to please give a more descriptive name.

It might be possible to do that same job to update the title though ...

**Comment by peterbe** [comment]
I'm doubtful that we can coax how the GitHub UI works. But it's clearly [a common thing](https://github.com/mdn/content/pulls?q=is%3Apr+%22Update+index.html%22+).
I think it would make sense to do something like @nschonni suggested.

**Comment by peterbe** [comment]
I have a PR coming that is at least the beginning of a solution to this. 

(I admit, I spent too much time on it but I think there's always value in learning more about what you can do with GitHub Actions).
