### ISSUE TITLE
Issue with "Network Security Services": (Broken Links)

### ISSUE THREAD

**Issue by arshadnoor** [mdn/content#7820]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS

#### What information was incorrect, unhelpful, or incomplete?
The links to "introduction to PUblic-Key Cryptography" and "Introduction to SSL" are broken.
While MDN considers them an "archive", they are extremely useful in helping newbies to understand PKI, digital certificates and chain validation. I would encourage finding them and linking them back again. Thank you.

#### Specific section or headline?
Background Section

#### What did you expect to see?
The documents referenced by the links.

#### Did you test this? If so, how?
By clicking on the links.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/projects/nss`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/projects/nss/index.html
* Last commit: https://github.com/mdn/content/commit/cec9e8ed306805d484e197fdc153f7305d69ce83
* Document last modified: 2021-03-09T20:34:57.000Z

</details>

**Comment by arshadnoor** [comment]
I found archived copies here: 
http://web.archive.org/web/20140704130514/https://developer.mozilla.org/en-US/docs/Introduction_to_Public-Key_Cryptography
http://web.archive.org/web/20140915182341/https://developer.mozilla.org/en-US/docs/Introduction_to_SSL

**Comment by hamishwillee** [comment]
Thanks very much. I'm going to close this. Not because your report is wrong, but because that document is moving off MDN and will be owned by a different team.

You can track this in https://github.com/mdn/content/pull/4681
