### ISSUE TITLE
Issue with "runtime.Port": postMessage blocking behaviour not documented

### ISSUE THREAD

**Issue by minfrin** [mdn/content#7821]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/Port

#### What information was incorrect, unhelpful, or incomplete?

postMessage docs.

#### Specific section or headline?

PostMessage.

#### What did you expect to see?

the blocking / non blocking behaviour of postMessage documented.

Does postMessage block? Does postMessage not block and you must handle flow control? Docs are silent.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/runtime/port`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/Port
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/runtime/port/index.html
* Last commit: https://github.com/mdn/content/commit/eb5d682cbe5664b933e793ff6434fb252686f3c3
* Document last modified: 2021-05-31T17:26:19.000Z

</details>

**Comment by rebloor** [comment]
@minfrin Have you checked out [Connection-based messaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#connection-based_messaging), does that help?

**Comment by zombie** [comment]
What do you mean by "does it block"?  There is no response as part of `postMessage` so what would it block for?

**Comment by minfrin** [comment]
> What do you mean by "does it block"? There is no response as part of postMessage so what would it block for?

Blocking would mean that there would be a way (a promise marked resolved, for example) to confirm that the message sent with postMessage has been accepted by the other side.

Non blocking would mean that there is no way to know if the other side has accepted the message (fire and forget), and any attempt to send multiple messages would start piling up, and any attempt to send large messages could see part of the chain hit a resource limit (queue too big, out of memory, etc) and in turn any expectation of flow control (flow control meaning the sender being indicated that it should back off until the receiver has acknowledged the message) is the responsibility of the caller and requires explicit ack messages instead of implicit behaviour of the API.

Docs are silent on what a person who might want to be sending lots of messages should do.

**Comment by minfrin** [comment]
> @minfrin Have you checked out Connection-based messaging, does that help?

Alas that gives an example of how to send exactly one message. If you want to send more than one message, the docs are silent on what you should do to do so safely.

**Comment by zombie** [comment]
There's no way to even know if the other side has an `port.onMessage` listener, so messages don't "pile up", they just go away if nobody is listening.  The only thing you can know if the port was disconnected, and `postMessage` would throw in that case (with some corner cases with racing with a disconnect from the other end with -- no guarantees).

The best way for reliable communication is for the other side to post a message back after it has processed it, since nothing else is guaranteed.  Hope that helps, feel free to ask further if it didn't.

**Comment by rebloor** [comment]
@minfrin Do you have any further comment?

**Comment by rebloor** [comment]
No documentation changes have been identified here.
