### ISSUE TITLE
Content bug: Rust_to_wasm fails to mention Perl and Make

### ISSUE THREAD

**Issue by Dionysusnu** [mdn/content#7831]
## What page(s) did you find the problem on?

Compiling from Rust to WebAssembly
https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm
## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm#wasm-pack
## What is the problem?

Installing wasm-pack using cargo requires both perl and make to be installed. These aren't on Windows by default, but nothing is mentioned about it in the guide.
## What did you expect to see?

The guide should make mention of this, and recommend how to install both of them. It's a lengthy process though..
## Did you test this? If so, how?

I ran into this issue myself, while following the guide.
The error is
```
error: failed to run custom build command for `openssl-sys v0.9.65`
```
with some more clutter output lines.
However, no clear problem can be identified from this output. It does mention running a perl script, but it is not at all obvious that it fails because it cannot find perl itself.
This issue for the library shows how unclear the error is: https://github.com/sfackler/rust-openssl/issues/1455

**Comment by himanshugarg** [comment]
Closed the PR (https://github.com/mdn/content/pull/9254) as Rust setup docs are more appropriate for documenting this.

**Comment by wbamberg** [comment]
Yes, closing this, because listing requirements for Rust installation are out of scope for this article.

**Comment by himanshugarg** [comment]
@Dionysusnu thanks for reporting the issue. Please consider posting it on https://github.com/rust-lang/rust-forge or a more appropriate Rust forum for this.
