### ISSUE TITLE
Issue with "RangeError: invalid array length": Is the limit 2GB or 4GB?

### ISSUE THREAD

**Issue by lifthrasiir** [mdn/content#7835]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length

> For `Array` the maximum length is 2GB-1 (2^32-1). For `ArrayBuffer` the maximum is 2GB-1 on 32-bit systems (2^32-1). From Firefox version 89 the maximum value of `ArrayBuffer` is 8GB on 64-bit systems (2^33).

2^31-1 is 4GB and not 2GB. I haven't tested with 32-bit systems, but given the code consistently refers to 2^32-1 and not 2^31-1, I guess 4GB is the correct figure.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/invalid_array_length`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/invalid_array_length/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by hamishwillee** [comment]
Thank you. My error :-(. Fixed in https://github.com/mdn/content/pull/7866
