### ISSUE TITLE
Issue with "class": examples are an anti-pattern

### ISSUE THREAD

**Issue by TrangOul** [mdn/content#7840]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/class

#### What information was incorrect, unhelpful, or incomplete?
Classes in the example. First, the class `Polygon` should be called `Rectangle`, as it has only width and height. Second, more important, `Square extends Rectangle` is a [classic OOP problem](https://en.wikipedia.org/wiki/Circle–ellipse_problem) which violates the [Liskov substitution principle ](https://en.wikipedia.org/wiki/Liskov_substitution_principle). By including it in the documentation, the incorrect usage is being spread among the developers.

#### Specific section or headline?
Examples, A simple class declaration.

#### What did you expect to see?
Other classes, which are not an anti-pattern. Example:
```
class Rectangle {
	constructor(height, width) {
		this.name = 'Rectangle';
		this.height = height;
		this.width = width;
	}
}

class FilledRectangle extends Rectangle {
	constructor(height, width, color) {
		super(height, width);
		this.name = 'Filled rectangle';
		this.color = color;
	}
}
```

Feel free to choose another one (maybe classic `Hound extends Animal`, which is more intuitive than math?).
#### Did you test this? If so, how?
Technically the existing code works, but is incorrect conceptually.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/class`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/class
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/class/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by NegiAkash890** [comment]
> I would gladly accept a PR. Would you like to do it?

Hi @teoli2003 can I work on this ?

**Comment by teoli2003** [comment]
This issue is yours, @NegiAkash890

**Comment by teoli2003** [comment]
@TrangOul, could you review PR #7874? This would help us!

**Comment by TrangOul** [comment]
@teoli2003 sure! Done.
