### ISSUE TITLE
Issue with "Web Serial API": missing Browser compatibility table

### ISSUE THREAD

**Issue by Leobriand31** [mdn/content#7843]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API

"Secure context : This feature is available only in secure contexts (HTTPS), in some or all supporting browsers."
The "supporting browsers" link is not working, could you fix it please?
And if you would add Serial API to Firefox that would be amazing ☺
Thanks!
Léo

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/web_serial_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_serial_api/index.html
* Last commit: https://github.com/mdn/content/commit/f8870835d0eb78e5f69e71a961be8fd2cb0c4b17
* Document last modified: 2021-05-13T14:17:18.000Z

</details>

**Comment by teoli2003** [comment]
Assigning myself as I plan to update the spec table here this week anyway.

**Comment by sideshowbarker** [comment]
ping @teoli2003
