### ISSUE TITLE
Issue with "Redirections in HTTP": Order of precedence

### ISSUE THREAD

**Issue by iamCristYe** [mdn/content#7859]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections

#### What information was incorrect, unhelpful, or incomplete?

> HTML redirects (<meta>) execute if there weren't any HTTP redirects.
> JavaScript redirects execute last, and only if JavaScript is enabled.
> 

But this is not the case. I tested with the attached HTML, on both Chrome/Firefox, JS redirect prevails.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections#order_of_precedence

#### What did you expect to see?
improved doc

#### Did you test this? If so, how?
Test with the following HTML
```
<!DOCTYPE html>

<head>
  <meta http-equiv="Refresh" content="0; URL=https://example.com">
</head>

<body>
  <script type="text/javascript">
    window.location = "https://example.net";
  </script>
</body>
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/redirections`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/redirections/index.html
* Last commit: https://github.com/mdn/content/commit/fa67a7b1bac8e49f2c24e8c780ad871cfd47fcac
* Document last modified: 2021-08-07T05:41:14.000Z

</details>

**Comment by MatthiasSaihttam** [comment]
I can confirm this behavior.

**Comment by sideshowbarker** [comment]
FYI, see my comment at https://github.com/mdn/content/pull/34087#discussion_r1637440393, and my related question at https://matrixlogs.bakkot.com/WHATWG/2024-06-13#L0

**Comment by sideshowbarker** [comment]
Update: (for the record here) The relevant requirements in the HTML spec are in the definition of _“a refresh is said to have come due”_ in step 13 of https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv-refresh

> For the purposes of the previous paragraph, a refresh is said to have come due as soon as the later of the following two conditions occurs:
> 
> - At least time seconds have elapsed since document's [completely loaded time](https://html.spec.whatwg.org/multipage/document-lifecycle.html#completely-loaded-time), adjusted to take into account user or user agent preferences.
> - If meta is given, at least time seconds have elapsed since meta was [inserted into the document](https://html.spec.whatwg.org/multipage/infrastructure.html#insert-an-element-into-a-document) document, adjusted to take into account user or user agent preferences.

(Thanks Josh for pointing that out)
