### ISSUE TITLE
Issue with "Text formatting": Comment in example is incorrect

### ISSUE THREAD

**Issue by meowmeowmeowcat** [mdn/content#7894]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Text_formatting

#### What information was incorrect, unhelpful, or incomplete?

Last comment `// Returns the string "2+2"` is incorrect.
```js
const firstString = '2 + 2'; // Creates a string literal value
const secondString = new String('2 + 2'); // Creates a String object
eval(firstString); // Returns the number 4
eval(secondString); // Returns the string "2 + 2"
```

#### Specific section or headline?

String objects

#### What did you expect to see?

The comment should be `// Returns a String object containing "2+2"`
(Just like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#description)

#### Did you test this? If so, how?

```shell
$ node
Welcome to Node.js v14.16.0.
Type ".help" for more information.
> const secondString = new String('2 + 2');
undefined
> eval(secondString); 
[String: '2 + 2']

```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/text_formatting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Text_formatting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/text_formatting/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #7909 with a fix.
