### ISSUE TITLE
Issue with "Object": The definition makes it sound like a synonym for "Class"

### ISSUE THREAD

**Issue by pfernandez** [mdn/content#7895]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Object

#### What information was incorrect, unhelpful, or incomplete?

The definition of an object leads one to believe that an object and class are the same:

> Object refers to a data structure containing data and instructions for working with the data. Objects sometimes refer to real-world things, for example a car or map object in a racing game. JavaScript, Java, C++, Python, and Ruby are examples of object-oriented programming languages.

But in the [Details of the object model](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Details_of_the_Object_Model), we read:

> JavaScript is an object-based language based on prototypes, rather than being class-based.

#### What did you expect to see?

A definition emphasizing the key-value nature of JS objects rather than emphasizing their similarity to classes. From the [type description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#objects):

> In JavaScript, objects can be seen as a collection of properties. With the object literal syntax, a limited set of properties are initialized; then properties can be added and removed. Property values can be values of any type, including other objects, which enables building complex data structures. Properties are identified using key values. A key value is either a String or a Symbol value.
>
> There are two types of object properties which have certain attributes: The data property and the accessor property.

Notice that in this description, an "accessor property" is referred to as a _property_, not a method. In JavaScript we can give objects class-like accessors by using a function as a value, but that doesn't make it a class. This distinction is very important; we shouldn't lead people to believe that JS is class-based.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/object`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Object
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/object/index.html
* Last commit: https://github.com/mdn/content/commit/1fdf7958ea85bab45e1d7ba3634e9381eae937d1
* Document last modified: 2021-01-27T07:42:45.000Z

</details>

**Comment by sideshowbarker** [comment]
Agreed - thanks for catching this and reporting it. I’ve opened #7903 with a change that rewrites the glossary entry to largely just follow the description at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#objects.

If we decide the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#objects description could be improved on, then we can use the PR to take the opportunity to iterate on that description to refine it further, updating it in both places.

That said, I think the nature of reader expectations for the Glossary is that glossary entries should be kept succinct — so personally I feel like the current rewrite in that PR hits the sweet spot pretty well, as far as giving an accurate and useful description while also keeping it succinct.

> Notice that in this description, an "accessor property" is referred to as a _property_, not a method. In JavaScript we can give objects class-like accessors by using a function as a value, but that doesn't make it a class. This distinction is very important; we shouldn't lead people to believe that JS is class-based.

I added that as Note in both places. It stretches the length of the glossary entry a bit, but it’s a useful-enough key point that can be made relatively succinctly (35 words) and so merits being included.
