### ISSUE TITLE
[Markdown] [Web/API] Remove hidden elements that don't contain live sample code blocks

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#7902]
Part of https://github.com/mdn/content/issues/7898.

In preparing Web/API docs for Markdown conversion we'd like to remove occurrences of `<div class="hidden">`. There are two main usages of this pattern:

1. to include comments for editors, like the comments attached to interactive examples
2. to hide code blocks that the author wants to participate in live samples, but doesn't want the reader to see

This issue to about removing instances of the first category. The fix in this case is often just to delete the content, although there might be some exceptions.

For an example of this pattern:

https://github.com/mdn/content/blob/a9f58a4051857c0eb85512c8c2d7b77a0010bd8d/files/en-us/web/api/svgpointlist/replaceitem/index.html#L59-L61

Sometimes this happens when an author has set `hidden` directly on a `<pre>` block that's part of a live sample. In this case we should keep the `hidden` class.

**Comment by wbamberg** [comment]
These are all the pages in Web/API in which a `class="hidden"` element does not contain any <pre>` block, and are therefore in this category:

https://developer.mozilla.org/en-us/docs/web/api/css_painting_api/guide
https://developer.mozilla.org/en-us/docs/web/api/css_painting_api
https://developer.mozilla.org/en-us/docs/web/api/css_typed_om_api/guide
https://developer.mozilla.org/en-us/docs/web/api/csskeywordvalue/csskeywordvalue
https://developer.mozilla.org/en-us/docs/web/api/csskeywordvalue
https://developer.mozilla.org/en-us/docs/web/api/csspositionvalue
https://developer.mozilla.org/en-us/docs/web/api/effecttiming/easing
https://developer.mozilla.org/en-us/docs/web/api/elementinternals/labels
https://developer.mozilla.org/en-us/docs/web/api/elementinternals/reportvalidity
https://developer.mozilla.org/en-us/docs/web/api/elementinternals/role
https://developer.mozilla.org/en-us/docs/web/api/elementinternals/shadowroot
https://developer.mozilla.org/en-us/docs/web/api/elementinternals/states
https://developer.mozilla.org/en-us/docs/web/api/file/name
https://developer.mozilla.org/en-us/docs/web/api/hidconnectionevent/hidconnectionevent
https://developer.mozilla.org/en-us/docs/web/api/hiddevice/close
https://developer.mozilla.org/en-us/docs/web/api/hiddevice/productid
https://developer.mozilla.org/en-us/docs/web/api/hiddevice/productname
https://developer.mozilla.org/en-us/docs/web/api/hiddevice/receivefeaturereport
https://developer.mozilla.org/en-us/docs/web/api/hiddevice/sendfeaturereport
https://developer.mozilla.org/en-us/docs/web/api/hiddevice/vendorid
https://developer.mozilla.org/en-us/docs/web/api/htmlimageelement/alt
https://developer.mozilla.org/en-us/docs/web/api/htmlimageelement/usemap
https://developer.mozilla.org/en-us/docs/web/api/htmlmediaelement/texttracks
https://developer.mozilla.org/en-us/docs/web/api/midioutput/clear
https://developer.mozilla.org/en-us/docs/web/api/midioutput
https://developer.mozilla.org/en-us/docs/web/api/midioutput/send
https://developer.mozilla.org/en-us/docs/web/api/midiport/close
https://developer.mozilla.org/en-us/docs/web/api/rtcicecandidatepairstats/firstrequesttimestamp
https://developer.mozilla.org/en-us/docs/web/api/svgpointlist/appenditem
https://developer.mozilla.org/en-us/docs/web/api/svgpointlist/clear
https://developer.mozilla.org/en-us/docs/web/api/svgpointlist/getitem
https://developer.mozilla.org/en-us/docs/web/api/svgpointlist
https://developer.mozilla.org/en-us/docs/web/api/svgpointlist/initialize
https://developer.mozilla.org/en-us/docs/web/api/svgpointlist/insertitembefore
https://developer.mozilla.org/en-us/docs/web/api/svgpointlist/length
https://developer.mozilla.org/en-us/docs/web/api/svgpointlist/numberofitems
https://developer.mozilla.org/en-us/docs/web/api/svgpointlist/removeitem
https://developer.mozilla.org/en-us/docs/web/api/svgpointlist/replaceitem
https://developer.mozilla.org/en-us/docs/web/api/windoworworkerglobalscope/settimeout

**Comment by NegiAkash890** [comment]
Hi @wbamberg can I work on this one ? Let me know anything that I will need to fix this issue.

**Comment by wbamberg** [comment]
That would be great! Please ask if you're not sure what to do about any of the pages.
