### ISSUE TITLE
No autoplay in Firefox after clicking on link?

### ISSUE THREAD

**Issue by stefan-reich** [mdn/content#7908]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide

#### What information was incorrect, unhelpful, or incomplete?

I would like to know if it is intended that Firefox's anti-autoplay policies are even harsher than Chrome's.

In Chrome, it is enough if the user clicks on an in-domain link once. After that, the following pages from the same domain can autoplay.

This is REALLY important. I want to interact with the user including audio, and I absolutely have to do it on page load also (after the user has clicked on a link within the site).

In Firefox, clicking on a link seems to reset the autoplay prohibition, thus requiring _another_ (completely useless!) click.

[Demo site](https://mouth.gazelle.rocks/beaHTML/16?page=1&text=This+browser+is+better)

**Comment by himanshugarg** [comment]
Sorry @stefan-reich for the late question. In the issue description, would you like to indicate what fixes are needed to the docs? The [Demo site](https://mouth.gazelle.rocks/beaHTML/16?page=1&text=This+browser+is+better) probably showed the difference in autoplay behavior in the two browsers, but it no longer works. Thanks.

**Comment by sideshowbarker** [comment]
Closing for lack of response to https://github.com/mdn/content/issues/7908#issuecomment-1092399358
