### ISSUE TITLE
Issue with "CacheStorage.keys()": (missing ')' in example)

### ISSUE THREAD

**Issue by ulvido** [mdn/content#7913]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/keys

#### What information was incorrect, unhelpful, or incomplete?
```
this.addEventListener('activate', function(event) {
  var cacheWhitelist = ['v2'];

  event.waitUntil(
    caches.keys().then(function(keyList) {
      return Promise.all(keyList.map(function(key) {
        if (cacheWhitelist.indexOf(key) === -1) {
          return caches.delete(key);
        }
      }); // <- missing ) at this line.
    })
  );
});
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/cachestorage/keys`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/keys
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/cachestorage/keys/index.html
* Last commit: https://github.com/mdn/content/commit/52cb33d18729b3664a8d146c0ad23648790dc5dc
* Document last modified: 2021-06-11T14:43:07.000Z

</details>

**Comment by teoli2003** [comment]
Thanks! Good catch. I've opened a PR to get this fixed.
