### ISSUE TITLE
Issue with "Understanding client-side web development tools": (short summary here please)

### ISSUE THREAD

**Issue by lukki25** [mdn/content#7917]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/index.html
* Last commit: https://github.com/mdn/content/commit/2c6f017de416f5817a109191417d549c60e90055
* Document last modified: 2021-04-14T07:08:39.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

Unfortunately, you didn't provide any information about the issue you are reporting. We cannot act on it.

I'm closing it. If you come back and provide more information, you are welcome to re-open it (or to fill a separate issue).

Thanks a lot for your interest!
