### ISSUE TITLE
Issue with "runtime.sendMessage()": Security details undocumented

### ISSUE THREAD

**Issue by minfrin** [mdn/content#7925]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage

#### What information was incorrect, unhelpful, or incomplete?

From archeology, it appears that the ability to call this function is limited in scope.

#### What did you expect to see?

Where can this function be executed? In a background script? In a content script? In a web page? Are there additional steps required to make this work?

Docs are silent.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/runtime/sendmessage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/runtime/sendmessage/index.html
* Last commit: https://github.com/mdn/content/commit/eb5d682cbe5664b933e793ff6434fb252686f3c3
* Document last modified: 2021-05-31T17:26:19.000Z

</details>

**Comment by rebloor** [comment]
@minfrin Can you clarify "From archeology, it appears that the ability to call this function is limited in scope."?

**Comment by minfrin** [comment]
I understand there are situations where this function is not allowed to be executed. I cannot find a full definition of the behavior.

**Comment by Rob--W** [comment]
This function can always be called when it exists, in Firefox: in extension pages, including background scripts, and in content scripts.

Could you clarify what's missing? The documentation appears to be complete to me. The only potential thing that I can think of is that in Chromium-based browsers, the method is also available in web pages, and offers access to extensions as documented at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/externally_connectable.

**Comment by minfrin** [comment]
> This function can always be called when it exists

The trouble with the current docs is there is no clear explicit definition in the docs of where this function exists.

I am aware this information isn't needed by someone who focuses mainly on webextentions and is aware of the limitations through experience of using code, however for people who are trying to factor webextensions into a wider system, the lack of this information makes design difficult.

**Comment by Rob--W** [comment]
> > This function can always be called when it exists
> 
> The trouble with the current docs is there is no clear explicit definition in the docs of where this function exists.

The API reference is listed under the "Browser Extensions" category. Those unfamiliar with this concept can click on that link to get an overview. At the bottom of the overview page, there is a "JavaScript APIs section (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions#javascript_apis) that links to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API, which clearly spells out that these APIs can only be used in some places.

> I am aware this information isn't needed by someone who focuses mainly on webextentions and is aware of the limitations through experience of using code, however for people who are trying to factor webextensions into a wider system, the lack of this information makes design difficult.

The last part of this response is vague. Can you be more concrete about what you are looking for?

**Comment by rebloor** [comment]
@minfrin Do you have any further comment on this?

**Comment by rebloor** [comment]
No documentation requirements identified here
