### ISSUE TITLE
Issue with "Image gallery": the connect to link(grab the ZIP) can't be reached from section of Starting point

### ISSUE THREAD

**Issue by letsgo0** [mdn/content#793]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Image_gallery

#### What information was incorrect, unhelpful, or incomplete?
I just can't download this file below.
[https://github.com/mdn/learning-area/blob/master/javascript/building-blocks/gallery/gallery-start.zip?raw=true](url)

#### Specific section or headline?
Starting point

#### What did you expect to see?
tell me a proper way to get this file, please.

#### Did you test this? If so, how?
i clicked that link many times. It gived me the same result--can't find this website.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/image_gallery`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Image_gallery
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/javascript/building_blocks/image_gallery/index.html
* Report started: 2020-12-31T06:33:06.139Z

</details>

**Comment by sideshowbarker** [comment]
I can’t reproduce this problem. For me, the download from that link works as expected in every browser I tried (Firefox, Chrome, and Safari).

Maybe you have some anti-virus software or something which is blocking the download?

**Comment by sideshowbarker** [comment]
Closing for lack of response
