### ISSUE TITLE
Add data for COEP: credentialless

### ISSUE THREAD

**Issue by RealAlphabet** [mdn/content#7931]
`Cross-Origin-Embedder-Policy: credentialless` was shipped in [Chrome 93](https://www.chromestatus.com/feature/4918234241302528).
It needs to be added to BCD and documented on MDN.

Ressource documentation :
- [Proposal](https://wicg.github.io/credentiallessness/#:~:text=Credentialless%20is%20a%20Cross%2DOrigin,%2DPolicy%20(COEP)%20variant.&text=Contrary%20to%20require%2Dcorp%2C%20it,is%20requesting%20them%20without%20credentials.)
- [Chrome Blog](https://developer.chrome.com/blog/coep-credentialless-origin-trial)

**Comment by rachelandrew** [comment]
I think this is an origin trial based on https://www.chromestatus.com/feature/4918234241302528

If so, we don't normally document things at this point.

cc: @jpmedley

**Comment by jpmedley** [comment]
This is more definitive: https://developer.chrome.com/origintrials/#/view_trial/3036552048754556929

Origin trials aren't documented on MDN. 
* At the end of the OT, this functionality will be shut off in 93, 94, and 95.
* The feature will probably be enabled by default in 96, but that is not assured. I could go away completely. (This has happened.) There could be a second OT with a new design. (This has also happened.)
* Even if this does ship in 96, it's not guaranteed to follow the current design.

**Comment by rachelandrew** [comment]
Thanks, @jpmedley I think we should probably close this, for now, to prevent community members from picking up the task, and document it when it ships.

Thanks for raising the issue @RealAlphabet - it's just a little early right now.
