### ISSUE TITLE
Issue with "JavaScript data types and data structures": the “Data and Structure types” section uses terminology that doesn’t align with the spec

### ISSUE THREAD

**Issue by joekingTheThird3** [mdn/content#7939]
Reference section:
'Structural Types:

 '   Object : typeof instance === "object". Special non-data but Structural type for any constructed object instance also used as data structures: new Object, new Array, new Map, new Set, new WeakMap, new WeakSet, new Date and almost everything made with new keyword;
    Function : a non-data structure, though it also answers for typeof operator: typeof instance === "function". This is merely a special shorthand for Functions, though every Function constructor is derived from Object constructor.
'
non-data but Structural type
What are you trying to say when you say 'non-data'?
And what does ' Function : a non-data structure'  actually mean? Are you saying there is no data in it? The type of object is 'non-data'? In a general sense isn't everything 'data'? Do you mean non-data type? It is something other than the data types (the primitives)?

MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/data_structures`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/data_structures/index.md
* Last commit: https://github.com/mdn/content/commit/9a7b342805564de1829161354b3da86cb977614e
* Document last modified: 2021-08-12T06:54:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks much for catching this and reporting it — I’ve opened #7944 with a fix.
