### ISSUE TITLE
Remove title attribute in links

### ISSUE THREAD

**Issue by lychyi** [mdn/content#794]
## Background
After cleaning up some broken links in #722 with @ericwbailey, there was some discussion around cleaning up any anchor tags with `title` attributes in them. I think @ericwbailey said it best in this [comment](https://github.com/mdn/content/pull/722#pullrequestreview-560173303).

> the title attribute's content is duplicative at best and (ironically) inaccessible at worst.

Indeed after cleaning some of these up, there were `title` attributes that either duplicated the URL, were the exact same thing as the text contents of the anchor tag, or were dramatically different (and sometimes incredibly lengthy) than the text contents. Not great for screen readers I'm sure.

## What to do?
After doing a bit of reading and talking with @ericwbailey, it seems like MDN should wholesale get rid of link `title` attributes. This helps make MDN more accessible, especially for those that are using screen readers.

## Lots of files
If we do want to proceed with doing this, it is going to be a massive PR, probably a lot easier to review if broken up bit by bit. From experience, the find and replace isn't hard and someone with better regex chops can probably do this quickly with more confidence. But the scope of the change is nearly 2000 instances across 600 files.

## Next steps
If one of the maintainers wants to give this issue a thumbs up or down, I can go ahead and work on it or close it out respectively.

**Comment by nschonni** [comment]
I've been chipping away at the "this are the same as the links" ones. Just submitted #816 for a few more, but I think dropping them all probably does make sense

**Comment by chrisdavidmills** [comment]
I would agree with this.

**Comment by nschonni** [comment]
Another chunk in #867

**Comment by himanshugarg** [comment]
This may no longer be an issue

```bash
$ grep -r '<a[^>]*title>' 
$ 
```

**Comment by Elchi3** [comment]
Closing this since we are in markdown now
