### ISSUE TITLE
<Iframe name> target not working in new firefox browser on index pages.

### ISSUE THREAD

**Issue by EDiamond777** [mdn/content#7946]
Good Morning, my name is Nick Slade from E Diamond,  there is a error. on the new Firefox browser.
1) When the browser loads it blocks out <iframe name> targeting on a index Page. This was used on a multiple page nested <iframe>. tested on windows 10 4K MSi. 

Separate issuie
2) Browser Crashes in windows 7. it just freezes. 

E Diamond
Nick Slade
{212} 777-5683

**Comment by sideshowbarker** [comment]
This sounds like something that you should consider instead reporting at https://bugzilla.mozilla.org/

The scope of this issue tracker is limited to the content of the https://developer.mozilla.org/en-US/ site.
