### ISSUE TITLE
Issue with "Select an element": Videos do not exist on the page.

### ISSUE THREAD

**Issue by RookTKO** [mdn/content#7954]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_an_element

#### What information was incorrect, unhelpful, or incomplete?
Videos are unavailable.

#### What did you expect to see?
I expected to be able to see the videos.

#### Did you test this? If so, how?
Videos don't exists. Head over to url: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_an_element and try to watch the videos or click the link to see them,.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/select_an_element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_an_element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/select_an_element/index.html
* Last commit: https://github.com/mdn/content/commit/05b71a290b2ab444b23e0f35f619d93203c7e2d8
* Document last modified: 2021-02-02T16:31:29.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. This is a known issue, and we have https://github.com/mdn/content/issues/7457 open to track it, so I’m going ahead and closing this issue. Please subscribe to https://github.com/mdn/content/issues/7457 if you want to keep track of progress on getting this fixed.
