### ISSUE TITLE
Issue with "Introduction to events": We may remove Cross Browser Compatibility

### ISSUE THREAD

**Issue by NagayamaToshiaki** [mdn/content#7955]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events

#### What information was incorrect, unhelpful, or incomplete?
IE8, which was the latest IE for now obsolete Xindows XP, was discontinued. So, saying about compatibility makes no sense as of 2021.

#### Specific section or headline?
What mechanism should I use?

#### What did you expect to see?
The other two are relatively interchangeable, at least for simple uses:

- Event handler properties have less power and options, but ~~better cross-browser compatibility (being supported as far back as Internet Explorer 8)~~ *are easier to understand*. You should probably start with these as you begin learning.

- DOM Level 2 Events (addEventListener(), etc.) are more powerful, but can also become complex ~~and are less well supported (supported as far back as Internet Explorer 9)~~. You should also experiment with these, and try to use them where possible.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/events`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/events/index.html
* Last commit: https://github.com/mdn/content/commit/c21e639b5476db0f15eb563ec61876862c1c01df
* Document last modified: 2021-08-08T15:07:38.000Z

</details>

**Comment by sideshowbarker** [comment]
Agreed. Thanks much for catching this and for the proposed changes — I’ve opened #7956 with a fix.
