### ISSUE TITLE
Issue with "Django introduction": text indicates line-in-bold but nothing is in bold in the code block

### ISSUE THREAD

**Issue by siraj-samsudeen** [mdn/content#7958]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Introduction

#### What information was incorrect, unhelpful, or incomplete?
Just a cosmetic mismatch

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Introduction#querying_data_views.py

#### What did you expect to see?
I expect this line of code to be in bold:
list_teams = Team.objects.filter(team_level__exact="U09")

#### Did you test this? If so, how?
NA

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/introduction/index.html
* Last commit: https://github.com/mdn/content/commit/574182225b599b79b228b8863380154d8401ed19
* Document last modified: 2021-06-30T16:29:36.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #7960 with a fix.

We’ll eventually be migrating the source of this article to Markdown — and with that move, losing the ability to do any bold/italic character formatting of any parts of code blocks. So as I noted in the description for #7960, we need to replace the *“The line in bold”* reference with something that doesn’t require boldfacing that line in the code block. And the easiest and clearest way to achieve the same effect it just copy that line of code verbatim into the paragraph.

**Comment by siraj-samsudeen** [comment]
Excellent fix and thank you for the quick action. 

And thanks to the entire team for such a wonderful intro/summary of Django - this is THE best I have seen so far.
