### ISSUE TITLE
Issue with "Number.MIN_VALUE": Example is wrong

### ISSUE THREAD

**Issue by MadaraUchiha** [mdn/content#7975]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_VALUE

#### What information was incorrect, unhelpful, or incomplete?
```js
function multiply(x, y) {
  if (x * y < Number.MIN_VALUE) {
    return 'Process as -Infinity';
  }
  return (x * y);
}

console.log(multiply(5e-324, 1));
// expected output: 5e-324

console.log(multiply(-1.7976931348623157e+308, 2));
// expected output: Process as -Infinity
```

The demo in question (at least the second one) seems copied from MAX_VALUE and a negative sign added. This is the wrong usage for MIN_VALUE (which is the closest positive value to 0, not the most negative number).

#### Specific section or headline?
Demo

#### What did you expect to see?
```js
function divide(x, y) {
  if (x / y < Number.MIN_VALUE) {
    return 'Process as 0';
  }
  return (x / y);
}

console.log(divide(5e-324, 1));
// expected output: 5e-324

console.log(divide(5e-324, 2));
// expected output: Process as 0
```

#### Did you test this? If so, how?
Ran in the browser

#### Extra
I wanted to open a PR, but I didn't understand how to edit the example html file, and I couldn't find it in the project.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/number/min_value`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_VALUE
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/number/min_value/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by teoli2003** [comment]
Hi! Nice catch.

> I wanted to open a PR, but I didn't understand how to edit the example html file, and I couldn't find it in the project.

This is because, for historical reasons (we were a wiki before migrating to Github), the file is in a different repo.

Here is the file you are looking for:

https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/number/number-min-value.js
