### ISSUE TITLE
Issue with "PWA developer guide": Content missing from page

### ISSUE THREAD

**Issue by masonlogan1** [mdn/content#7977]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Developer_guide

#### What information was incorrect, unhelpful, or incomplete?
Page is missing information; every section just has the word "description" where the content should be. Content was last updated in March 2021

#### Specific section or headline?
All of them

#### What did you expect to see?
Helpful content

#### Did you test this? If so, how?
Tried disabling adblocker/NoScript, no change to page

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/progressive_web_apps/developer_guide`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Developer_guide
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/developer_guide/index.html
* Last commit: https://github.com/mdn/content/commit/70beea48a72c7dbc0d07e2a0dd9c9a95aa457d47
* Document last modified: 2021-03-26T23:17:12.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. It seems that nobody ever got around to actually creating any of the articles in the outline in that https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Developer_guide page — other than the page at https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Developer_guide/Installing.

Given that, I’ve opened #7984 with a change that:

- removes that never-finished https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Developer_guide page
- moves the https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Developer_guide/Installing page up in the hierarchy to become https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installing
