### ISSUE TITLE
Content bug: The garbage collection glossary page has an issue with the link pointing to the memory management documentation in JavaScript

### ISSUE THREAD

**Issue by hamiecod** [mdn/content#7978]
## What page(s) did you find the problem on?
https://developer.mozilla.org/en-US/docs/Glossary/Garbage_collection

## Specific page section or heading?
The anchor tag in the first paragraph

## What is the problem?
The anchor tag's link does not point to the memory management documentation. This is probably because it wasn't updated after the memory management documentation was added.

## What did you expect to see?
The anchor tag with the text of `memory management` should have a link to the memory management docs https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #7983 with a fix.
