### ISSUE TITLE
Issue with "Using Promises": …

### ISSUE THREAD

**Issue by deanrobertcook** [mdn/content#798]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises

#### What information was incorrect, unhelpful, or incomplete?
The following line: 

> Callbacks added with `then()`, as above, will be called even _after_ the success or failure of the asynchronous operation.

Is somewhat unclear to me. The word "even" suggests surprise in the author's tone, like there is some other outcome we should be expected to see outside of "success or failure", but "success or failure" accounts for 100% of all possible outcomes. In combination with the emphasis on _after_, I'm also not too sure how to read this in my mind.

#### Specific section or headline?
Guarantees

#### What did you expect to see?
This is how I understand this guarantee in slightly modified wording:

> Callbacks added with `then()`, as above, will be always be called _after_ the success or failure of the asynchronous operation (as opposed to passed-in callbacks, where the callbacks my be called at any point during the asynchronous operation).

#### Did you test this? If so, how?
N/A

I hope that makes sense, thanks in advance!

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/using_promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/guide/using_promises/index.html
* Report started: 2020-12-31T08:59:31.941Z

</details>

**Comment by Fayti1703** [comment]
The wording is confusing on this, but I suspect the "*even* after" refers to how, if a Promise is already resolved/rejected by the time `.then()` is called, the callbacks will still be invoked, despite the fact the asynchronous operation has already completed (which would not happen with, say, event listeners)

**Comment by jadjoubran** [comment]
This can be closed now 👍🏼 The PR was merged successfully

**Comment by chrisdavidmills** [comment]
@jadjoubran done!
