### ISSUE TITLE
How-to instructions for syntax boxes are wrong for method instructions

### ISSUE THREAD

**Issue by jpmedley** [mdn/content#7980]
## What page(s) did you find the problem on?

Instructions for syntax boxes are wrong for method instructions. 

## Specific page section or heading?

https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Write_an_API_reference#structure_of_a_method_page

## What is the problem?

The instructions still show the use of `<em>` elements.

## What did you expect to see?

This is inconsistent with a structures page located elsewhere.

## Did you test this? If so, how?

NA

## Additional information

This may be one sample of a larger problem. The structures section contains the latest information on how certain things are done. This whole page may need to be evaluated for consistency with new material or possible removal.

**Comment by Josh-Cena** [comment]
Fixed by #17549
