### ISSUE TITLE
Issue with "<input type="button">": (short summary here please)

### ISSUE THREAD

**Issue by Bam993** [mdn/content#7981]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/button`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/button/index.html
* Last commit: https://github.com/mdn/content/commit/2bfb6c1a571f4ac6895f9dced0e389b6d55e20f3
* Document last modified: 2021-05-31T10:26:33.000Z

</details>

**Comment by Ryuno-Ki** [comment]
@Bam993 was this opened by mistake?
It does not contain enough information to be actionable.

**Comment by Bam993** [comment]
I can't fix the problems in the system I think that someone is blocking the fixing problems and controlling the operating system

**Comment by sideshowbarker** [comment]
> I can't fix the problems in the system I think that someone is blocking the fixing problems and controlling the operating system

The scope of this issue tracker is the content of the documentation in https://developer.mozilla.org/en-US/ site. That problem description doesn’t sound like a problem we can solve here — so I’m going ahead and closing this issue.
