### ISSUE TITLE
salesforce HTTP error: status code 503, net::ERR_HTTP_RESPONSE_CODE_FAILURE shown in console

### ISSUE THREAD

**Issue by Harshalatest** [mdn/content#7985]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status/503`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/503/index.md
* Last commit: https://github.com/mdn/content/commit/46234997b6257b619423a11ce31154afa336143f
* Document last modified: 2021-08-13T16:17:49.000Z

</details>

**Comment by sideshowbarker** [comment]
This scope of this issue tracker is for changes or additions to the content https://developer.mozilla.org/ itself. This issue doesn’t look like a report about that content but instead about something else.

So I’m going ahead and closing this. But if you do in fact want to report a specific problem with the content of the https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503, then please post a comment with additional details, and this issue can be revisited.
