### ISSUE TITLE
Issue with "Supporting both TouchEvent and MouseEvent": deprecated by Pointer Events

### ISSUE THREAD

**Issue by fonsp** [mdn/content#800]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent

#### What information was incorrect, unhelpful, or incomplete?
It seems like this page is deprecated now that we have Pointer events ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events)). 

**I propose a [redirect]/[new section at the top with a link] to the [pointer events page](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events), but I am not sure what should happen with the existing content.** I would be happy to make this PR myself if someone can make that decision.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/touch_events/supporting_both_touchevent_and_mouseevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/touch_events/supporting_both_touchevent_and_mouseevent/index.html
* Report started: 2020-12-31T11:00:02.507Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this and sorry for the lack of response until now.

> **I propose a [redirect]/[new section at the top with a link] to the [pointer events page](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events), but I am not sure what should happen with the existing content.** I would be happy to make this PR myself if someone can make that decision.

We don’t need to fully or even partially preserve the existing content. If you create a new article that’s up to date with the current specs — and that aligns with browser support — then we could end up just redirecting the old https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent article to your new article.

So if you’re still interested in putting together a PR for this, then it’d be very much welcome.
