### ISSUE TITLE
Issue with "Relationship of grid layout to other layout method…": (Unexpected result)

### ISSUE THREAD

**Issue by mangelozzi** [mdn/content#8004]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout

#### What information was incorrect, unhelpful, or incomplete?
The information is correct, and very helpful, thank you for the great tutorial. Just one point that confuses me.

#### Specific section or headline?
`A grid container as containing block`

#### What did you expect to see?
I expected to see `box3` positioned `40px` from the left of the `wrapper` container, instead it does not look 40px from the left.

#### Did you test this? If so, how?
Yes, with a `codepen.io`. The documentation was all really clear up until this point. I don't understand why `box3` is positioned relative to `box2` and not `wrapper`.I have read the documentation and can't understand why. Thank you!

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_grid_layout/relationship_of_grid_layout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_grid_layout/relationship_of_grid_layout/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by AnilSeervi** [comment]
> 
> 
> MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout
> #### What information was incorrect, unhelpful, or incomplete?
> 
> The information is correct, and very helpful, thank you for the great tutorial. Just one point that confuses me.
> #### Specific section or headline?
> 
> `A grid container as containing block`
> #### What did you expect to see?
> 
> I expected to see `box3` positioned `40px` from the left of the `wrapper` container, instead it does not look 40px from the left.
> #### Did you test this? If so, how?
> 
> Yes, with a `codepen.io`. The documentation was all really clear up until this point. I don't understand why `box3` is positioned relative to `box2` and not `wrapper`.I have read the documentation and can't understand why. Thank you!
> MDN Content page report details

The `box3` is positioning itself like that because of the line-based placement of it from `2`(`grid-column-start: 2)`.
It does position relatively to the `wrapper` of `left: 40px` and `top: 40px` first, then you are just moving it to start from the line-based column number 2.

**Comment by rachelandrew** [comment]
As far as I can see the example and code is correct.
