### ISSUE TITLE
Issue with Progressive web apps (PWAs) can be improive.

### ISSUE THREAD

**Issue by yabuki** [mdn/content#8023]
Hello, MDN folks.

I'd like to report this documentation.

MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps

#### What information was incorrect, unhelpful, or incomplete?

What does progressive web application mean. Please write thesis first then examples. I hard to understand "progressive".
Because follow sentences should place "Progressive" examples (and detail links). 

#### Specific section or headline?

first paragraph.

#### What did you expect to see?

>  Please write thesis first then examples. I hard to understand "progressive".
>  Because follow sentences should place "Progressive" examples (and detail links). 

#### Did you test this? If so, how?

No. I didn't mention sample programs.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ja/web/progressive_web_apps`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/Progressive_web_apps
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/progressive_web_apps/index.html
* Last commit: https://github.com/mdn/translated-content/commit/01aad4e9d467a4b4a5b237f888b6c8fda3b07815
* Document last modified: 2021-08-07T20:22:47.000Z

</details>

**Comment by sideshowbarker** [comment]
Yabuki-san, thanks very much for raising this issue. It led to me spending some time today doing a major update to the https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps while also doing a related update to the https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement doc.

> What does progressive web application mean. … I hard to understand "progressive".

The short answer is that the “progressive” in “progressive web application“ comes from “progressive enhancement” — and so “progressive” shouldn’t be considered on its own but instead as part of “progressive enhancement”, which is “term of art” with a special meaning.

So to help make that clear, I’ve turned the words “progressive enhancement” on the https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps page into a hyperlink to https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement.

I considered adding some sentences explaining “progressive comes from *progressive enhancement*” on the https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps page itself — but I think it would add so much extra text there that it would be distracting.

So what I did instead was to update https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement to add this:

> The word _progressive_ in _progressive enhancement_ means creating a design that achieves a simpler-but-still-usable experience for users of older browsers and devices with limited capabilities, while at the same time being a design that **progresses the user experience up** to a more-compelling, fully-featured experience for users of newer browsers and devices with richer capabilities.

…and then I also added the following links:

<ul>
<li><a href="https://www.freecodecamp.org/news/what-is-progressive-enhancement-and-why-it-matters-e80c7aaf834a/">What is Progressive Enhancement, and why it matters</a> at freeCodeCamp</li>
<li><a href="https://www.quirksmode.org/blog/archives/2021/02/progressive_enh_1.html">Progressive Enhancement reading list 2021</a> at QuirksMode</li>
<li><a href="https://alistapart.com/article/understandingprogressiveenhancement/">Understanding Progressive Enhancement</a> by Aaron Gustafson; a 2008 <em>A List Apart</em> article which first “placed progressive enhancement at the forefront of web developer thinking”</li>
<li><a href="http://hesketh.com/publications/inclusive_web_design_for_the_future/">Inclusive Web Design For the Future with Progressive Enhancement</a> (<a href="http://www.hesketh.com/progressive_enhancement_and_the_future_of_web_design.html">related article)</a> by Steve Champeon and Nick Finck; a 2003 SXSW presentation cited by Aaron Gustafson as “unveiling a blueprint for a new way of approaching web development”, and naming it “progressive ehancement”</li>
</ul>
