### ISSUE TITLE
Issue with "ReferenceError: can't access lexical declaration`X…": Bad/misleading examples

### ISSUE THREAD

**Issue by yunusabd** [mdn/content#8025]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_lexical_declaration_before_init

#### What information was incorrect, unhelpful, or incomplete?
> In this case, the variable "foo" is redeclared in the block statement using let. 

The fact that we're redeclaring foo isn't the issue here, it's simply this: `let foo = (foo + 55);`. In fact, the whole example can be boiled down to that line. It's confusing because it looks like we're trying assign the value from the outer scope foo to the new variable foo in the `if`-scope. So you might think `(foo + 55)` gets foo from the outer scope, but we're actually getting the foo that we're declaring in the `if`-scope (which is in a TDZ, which causes the error). 

This example is more about scopes than about `can't access lexical declaration 'variable' before initialization`. It's confusing and goes beyond the scope (no pun intended) of the error. 

#### Specific section or headline?
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_lexical_declaration_before_init#invalid_cases](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_lexical_declaration_before_init#invalid_cases)

#### What did you expect to see?
Either a better explanation how `foo` gets overwritten in the `if`-scope or a different example that's more clear.

#### Did you test this? If so, how?
In the console.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/cant_access_lexical_declaration_before_init`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_lexical_declaration_before_init
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/cant_access_lexical_declaration_before_init/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by NegiAkash890** [comment]
I am working on this one ,will come with easy to understand example !

**Comment by sideshowbarker** [comment]
@yunusabd Can you please review #8174 and confirm whether or not it resolves this issue to your satisfaction?
