### ISSUE TITLE
Issue with "Navigator.appVersion": (short summary here please)

### ISSUE THREAD

**Issue by JoshuaLamley** [mdn/content#8030]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/appVersion

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

</details>

**Comment by teoli2003** [comment]
Hi!

Unfortunately, you didn't provide any information about the issue you are reporting. We cannot act on it.

I'm closing it. If you return and provide more information, you are welcome to re-open it (or to fill a separate issue).

Thanks a lot for your interest!
