### ISSUE TITLE
Issue with "Styling web forms": (short summary here please)

### ISSUE THREAD

**Issue by rhysfog** [mdn/content#8031]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms

#### What information was incorrect, unhelpful, or incomplete?
The link to the postcard background image is broken.

#### Specific section or headline?
A specific styling example
   Organizing your assets

#### What did you expect to see?
The background image like this: https://mdn.github.io/learning-area/html/forms/postcard-example/

Instead, the file could not be found:
Page not found. Sorry, the page /files/4151/background.jpg could not be found.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/styling_web_forms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/styling_web_forms/index.html
* Last commit: https://github.com/mdn/content/commit/75c1271189903b4d96433a34a8174175dd089ef2
* Document last modified: 2021-04-28T14:08:28.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #8054 with a fix.
