### ISSUE TITLE
Issue with "Your first extension": (short summary here please)

### ISSUE THREAD

**Issue by yeokaiwei** [mdn/content#8032]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

#### What information was incorrect, unhelpful, or incomplete?
![Capture](https://user-images.githubusercontent.com/36597018/129846644-3e3365f7-ca73-4056-920b-888784db8f48.PNG)

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

#### What did you expect to see?
I expected to see a proper Youtube video tutorial on Installing Extensions and how to make your own Firefox extension.

#### Did you test this? If so, how?
Yes, I clicked on the link and it went to Youtube only.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/your_first_webextension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/your_first_webextension/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by AnilSeervi** [comment]
Same issue as #7457

**Comment by sideshowbarker** [comment]
Closing, as this is a known problem, and we have #7457 open to track getting a resolution for it.
