### ISSUE TITLE
Issue with "<input type="time">": time-picker details out of date

### ISSUE THREAD

**Issue by rob-raymond-sdc** [mdn/content#8035]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

#### What information was incorrect, unhelpful, or incomplete?
The information for both Chrome and Edge is out of date and incomplete. Chrome no longer shows up/down arrows, and instead has a clock icon which brings up selector dropdowns for Hours, minutes, and seconds, depending on the step attribute.
Edge, now being Chromium-based, has the same time picker, other than colour.
In addition, it would be helpful to mention that this time picker does not limit the selectable options as per the step attribute (e.g. a step of 300 would still show single-minute increments).

#### Specific section or headline?
Appearance - Chrome and Opera
Appearance - Edge
Additional attributes - Step

#### What did you expect to see?
An accurate description and up-to date screenshots of the time-picker element that Chrome and Edge use, and the way this interacts with the step attribute.

#### Did you test this? If so, how?
Yes, by usign a time picker attribute in up-to-date versions of both Chrome and Edge.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/time`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/time/index.html
* Last commit: https://github.com/mdn/content/commit/180b14138e5003fdb9f0a014efb26727d2335c76
* Document last modified: 2021-05-31T17:00:04.000Z

</details>

**Comment by Biki-das** [comment]
I would like to take this issue, and start working on it,looking forward to be assigned

**Comment by Biki-das** [comment]
How do i take the screenshot of time picker , whenever i try to take screenshot of the time picker it goes away any suggestion
