### ISSUE TITLE
Missing: Bug writing guidelines

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [mdn/content#8036]
This page
https://support.mozilla.org/en-US/kb/contributors-guide-writing-good-bug#w_existing-guidelines-for-writing-your-first-bug
has a Link to the _Bug writing guidelines_ linked to this
https://developer.mozilla.org/de/docs/Mozilla/QA/Bug_writing_guidelines
but the server answers with 404

It seems like that the content was moved. Maybe here?
https://github.com/mdn/archived-content/blob/main/files/en-us/mozilla/qa/bug_writing_guidelines/index.html

**Comment by sideshowbarker** [comment]
Thanks for catching this. The content is now available at https://bugzilla.mozilla.org/page.cgi?id=bug-writing.html (for background, see https://github.com/mozilla-bteam/bmo/pull/1738 and https://bugzilla.mozilla.org/show_bug.cgi?id=1721056) — so I’ve opened #8055 to add a redirect.

Once that redirect gets deployed, all requests to https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines will be redirected to https://bugzilla.mozilla.org/page.cgi?id=bug-writing.html.
