### ISSUE TITLE
Issue with "Location: reload()": Firefox does have a parameter...

### ISSUE THREAD

**Issue by Kaiido** [mdn/content#8039]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Location/reload

#### What information was incorrect, unhelpful, or incomplete?
The paragraph labeled ["location.reload() has no parameter"](https://developer.mozilla.org/en-US/docs/Web/API/Location/reload#location.reload_has_no_parameter) states that no current browser supports the `boolean`  parameter in `location.reload()`.  
Turns out  that Firefox does: https://searchfox.org/mozilla-central/source/dom/base/Location.cpp#551

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Location/reload#location.reload_has_no_parameter

#### What did you expect to see?
Maybe an edulcorated version of the same text, explaining that this is not standard nor on standards tracks ans should not be used, even if Firefox does support this.

#### Did you test this? If so, how?
I checked the network panel of my dev-tools to confirm.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/location/reload`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Location/reload
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/location/reload/index.html
* Last commit: https://github.com/mdn/content/commit/d8b62fd735cddcd481e15be0aed1e7820c528c16
* Document last modified: 2021-08-14T08:38:47.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks, nice catch — I’ve opened #8059 with a change that updates the content to mention Firefox support.
