### ISSUE TITLE
Issue with "Arrow function expressions": (comment on code seems misleading)

### ISSUE THREAD

**Issue by angelayanpan** [mdn/content#8050]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

#### What information was incorrect, unhelpful, or incomplete?

> //since the arrow function was created within the "obj", it assumes the object's "this"

```
var obj = {
    count : 10,
    doSomethingLater : function(){ // of course, arrow functions are not suited for methods
        setTimeout( () => { // since the arrow function was created within the "obj", it assumes the object's "this"
            this.count++;
            console.log(this.count);
        }, 300);
    }
}

obj.doSomethingLater();
```

#### Specific section or headline?

Arrow Example:

#### What did you expect to see?
The comment of `since the arrow function was created within the "obj", it assumes the object's "this"`  seems confusing to me because consider the following example code.  while the comment above it did make it clear that "arrow functions are not suited for methods",  the explanation of why that arrow function assumes' the object's "this“ seems to imply that as long as it's created within the obj, it will be.  And the following example breaks that assumption. 

```

const calculate = {
  array: [1, 2, 3],
  sum: () => {
    console.log(this === window); // => true
    return this.array.reduce((result, item) => result + item);
  }
};

// Throws "TypeError: Cannot read property 'reduce' of undefined"
calculate.sum();
```
  
This arrow function is created within the obj, but it doesn't assume the obj's "this"
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/functions/arrow_functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/functions/arrow_functions/index.md
* Last commit: https://github.com/mdn/content/commit/c09780e7c432029e3f8a966582e6c1c4eb85deff
* Document last modified: 2021-08-03T23:05:38.000Z

</details>

**Comment by mikoMK** [comment]
Would it make sense to change both comments like this:
```
...
doSomethingLater : function(){ // the traditional function binds "this" to the surrounding "obj"
        setTimeout( () => { // since the arrow function was created within the traditional function, it also uses the object's "this"
...
```

**Comment by angelayanpan** [comment]
> // since the arrow function was created within the traditional function, it also uses the object's "this"

the biggest part that I wouldn't understand if I'm new to this topic would be: the arrow function is created within setTimeout( )

Especially the beginning of the documentation says "arrow functions establish 'this" based on the scope the arrow function is defined within"     isn't the arrow function defined within setTimeout()?

**Comment by mikoMK** [comment]
You are right. That comment doesn't answer this question. I think the sentence "arrow functions establish ..." itself is misleading. The part from the very beginning of the docu is better: "Does not have its own bindings to this or super".

The question is: How to convey in a simple way that setTimeout operates on the global scope, but doesn't create a new "this" binding, neither does the arrow function and therefore the "this" binding of the traditional function is inherited by the arrow function 🤔

**Comment by mikoMK** [comment]
What about this:
```
...
doSomethingLater : function(){ // the traditional function binds "this" to the "obj" context
        setTimeout( () => { // since the arrow function doesn't have its own binding and
                               // setTimeout (as a function call) doesn't create a binding itself,
                               // the "obj" context of the traditional function will be used whitin
...
```
It's a rather long code comment but looking at some comments on [this | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this) I think it's just normal for a complex topic.
Do you think that is easier to understand, @angelayanpan?

**Comment by angelayanpan** [comment]
yes, I agree it needs to be longer than before to be a helpful comment.   by the way, there is a typo "within" in your 3rd line.

**Comment by mikoMK** [comment]
Thank you very much for your feedback, @angelayanpan. I updated my comment.
@sideshowbarker: Do you think the improved comment in my last message is good enough for a pull request?

**Comment by sideshowbarker** [comment]
> @sideshowbarker: Do you think the improved comment in my last message is good enough for a pull request?

Yes — I’d be happy to review a PR with that change
