### ISSUE TITLE
Issue with "AudioScheduledSourceNode.start()": it only accepts one argument

### ISSUE THREAD

**Issue by saschanaz** [mdn/content#8061]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioScheduledSourceNode/start

#### What information was incorrect, unhelpful, or incomplete?

It incorrectly argues it accepts three arguments

#### Specific section or headline?

Syntax

#### What did you expect to see?

Only the first argument

#### Did you test this? If so, how?

https://webaudio.github.io/web-audio-api/#AudioScheduledSourceNode

Found from https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1107

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/audioscheduledsourcenode/start`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioScheduledSourceNode/start
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/audioscheduledsourcenode/start/index.html
* Last commit: https://github.com/mdn/content/commit/677b3a037ac941f70eb95bc049b14cb169d3d112
* Document last modified: 2021-06-11T12:10:28.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this — I’ve opened #8064 with a fix.
