### ISSUE TITLE
Issue with "JavaScript shells": broken link to JavaScript Shell (js)

### ISSUE THREAD

**Issue by andresorge** [mdn/content#8085]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Shells

#### What information was incorrect, unhelpful, or incomplete?
broken link to JavaScript Shell (js)

#### Specific section or headline?
in the lower section "List of JavaScript shells" the link to JavaScript Shell (js): https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Introduction_to_the_JavaScript_shell is broken

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/shells`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Shells
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/shells/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this. The https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Introduction_to_the_JavaScript_shell was intentionally deleted from MDN and archived at https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/projects/spidermonkey/introduction_to_the_javascript_shell.

And we follow a practice of also dropping all links to such deleted/archived content — so I’ve opened #8088 with fix that removes that link, as well as removing some links to other outdated resources.
