### ISSUE TITLE
Issue with "Object.hasOwn()": (short summary here please)

### ISSUE THREAD

**Issue by bluespringstest** [mdn/content#8086]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn

#### What information was incorrect, unhelpful, or incomplete?

The 1st example, when the run icon is selected returns this error:

'Error: Object.hasOwn is not a function'

#### Specific section or headline?
JavaScript Demo: Object.hasOwn()

#### What did you expect to see?
The demo states that the expected output value was to be:

'prop' is own property

#### Did you test this? If so, how?
just selected the icon.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/hasown`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/hasown/index.md
* Last commit: https://github.com/mdn/content/commit/c1084ff2d6cff3fdbc7b677c25fb6d661d69a79b
* Document last modified: 2021-08-02T13:27:57.000Z

</details>

**Comment by teoli2003** [comment]
Are you using a Nightly build of Firefox? According to the compat table on the MDN page, it works only there.

I agree we should mark it as experimental, though.
