### ISSUE TITLE
Issue with "How the Web works":

### ISSUE THREAD

**Issue by Junaid-1993** [mdn/content#8096]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works

#### What information was incorrect, unhelpful, or incomplete?
I have a question about the browser or server is parsing the HTML?

#### Specific section or headline?
Order in which component files are parsed

#### What did you expect to see?
in the article, you said, "Once the client’s request is approved, the server first sends back the HTML (index) file". Then below you said, "From a **server** standpoint it is important to know the order in which these files are parsed when the response is sent back:". I am confused from a server standpoint or from a browser standpoint isn't the browser's job to parse the HTML.

 And also down below you said "The HTML file is parsed first and, by looking inside that file, the **server** recognizes which CSS and JavaScript files are referenced." so again isn't this browser's job to recognize the other linked files and request for those resources or servers.

I just have a little confusion about this.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/how_the_web_works`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/how_the_web_works/index.html
* Last commit: https://github.com/mdn/content/commit/25b23dba0248ede4ae0bde96ede0f7851b449db4
* Document last modified: 2021-08-02T17:35:04.000Z

</details>

**Comment by Zaidtech** [comment]
@sideshowbarker Can i help to resolve this?

**Comment by sideshowbarker** [comment]
Thanks for raising this. The existing description in that article definitely has some room for improvement — so I opened #8108 with a change that makes it much more clear and accurate.

> @sideshowbarker Can i help to resolve this?

I think #8108 does a pretty good job of resolving this — but I suspect there are probably other parts of the https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works that are likely in need of improvements and correction similar to what’s in the #8108 change.

So what I’d suggest is: give the entire article a thorough read-through, and raise PRs with fixes for any problems you find.

**Comment by Junaid-1993** [comment]
Hi, I am new to Github and don't fully understand this process the fix you opened has an accurate and good explanation but these changes are not applied on the original MDN docs it's on change in the draft area.

**Comment by teoli2003** [comment]
Hi @Junaid-1993 

The production Web site is usually built once a day; read this [section](https://github.com/mdn/content#when-will-my-change-show-up-on-the-production-mdn-site) for more information.

So the PR who landed a couple of hours ago is not yet visible in production but will be either tomorrow, either on Monday.

**Comment by Junaid-1993** [comment]
Ok, now I understand Thank you for everything.
