### ISSUE TITLE
Infra: Enable the “Automatically delete head branches” option, to cause a pull-request branch to get automatically deleted after the pull request is merged

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/content#810]
At https://github.com/mdn/content/settings, at the end of the **Merge button** section, there’s a setting:

![image](https://user-images.githubusercontent.com/194984/103421969-84583f00-4be2-11eb-9133-2eb85cca0689.png)

This is a request to consider enabling that “Automatically delete head branches” option.

**Comment by chrisdavidmills** [comment]
Sounds good to me, but I'll request a second opinion first. What say you, @escattone ?

**Comment by escattone** [comment]
@chrisdavidmills @sideshowbarker Sorry for the delay! I'm slowly catching up with a backlog of email/tasks. I didn't even realized that option existed! I like it!

**Comment by escattone** [comment]
Done! ✅
