### ISSUE TITLE
Issue with "The performance hazards of  [[Prototype]] mutation": …

### ISSUE THREAD

**Issue by spazmodius** [mdn/content#811]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/The_performance_hazards_of__[[Prototype]]_mutation

#### What information was incorrect, unhelpful, or incomplete?

The last 5 paragraphs seem to be chopped up nonsense.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/the_performance_hazards_of__[[prototype]]_mutation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/The_performance_hazards_of__[[Prototype]]_mutation
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/the_performance_hazards_of__[[prototype]]_mutation/index.html
* Report started: 2020-12-31T18:48:50.692Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened https://github.com/mdn/content/pull/5820 with a fix that removes that stuff (as fun as it is to ponder what caused it to end up in the article to begin with).
