### ISSUE TITLE
[Markdown] [Web/API] Remove summary and seoSummary classes

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#8110]
Part of https://github.com/mdn/content/issues/7898.

See also https://github.com/mdn/content/issues/3923 for some background here.

There are three cases:

1. `seoSummary` or `summary` are used to mark up the first non-macro paragraph. In these cases the classes are effectively a no-op and can be removed without anything changing. We can also automate these cases.

2. `seoSummary` or `summary` are used to truncate the first non-macro paragraph (usually taking the first sentence). In these cases it's probably worth checking that the whole first paragraph is reasonable to use as the summary, or whether we should split it. We don't have very precise guidelines for how long this should be though, and given that `seoSummary` and `summary` are usually omitted, I think it's OK to be pretty forgiving here.

3. `seoSummary` or `summary` are used to mark up a completely different part of the doc. In this case we should make sure that the first paragraph provides an appropriate summary. https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_AudioWorklet is a good example of a page that uses these classes intentionally, to provide an indirect opening paragraph with a direct summary. We'll need to stop doing things like this.

As far as I can tell the breakdown for Web/API is:

4072 pages - no `summary` or `seoSummary`
1423 pages - `summary` or `seoSummary` matches the first paragraph (case 1)
 345 pages - `summary` or `seoSummary` truncates the first paragraph (case 2)
  86 pages - `summary` or `seoSummary` selects a different text (case 3)

**Comment by teoli2003** [comment]
Case 1 should be easy to script (a bit tedious to review)

**Comment by wbamberg** [comment]
Yes, we should automate these. Do you think it's OK to have it in 1 PR?

**Comment by teoli2003** [comment]
> Yes, we should automate these. Do you think it's OK to have it in 1 PR?

It is much easier to review by batches of 400. That's what I have done for the spec macros. So they can land quickly, and do not rot.

**Comment by wbamberg** [comment]
I think this is now done!

**Comment by wbamberg** [comment]
...and thanks Jean-Yves for all the reviews!
