### ISSUE TITLE
Issue with "CacheStorage": (need warning that CacheStorage needs serviceWorker to be available)

### ISSUE THREAD

**Issue by Trinovantes** [mdn/content#8111]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage

#### What information was incorrect, unhelpful, or incomplete?

The docs should have a warning that all CacheStorage APIs are not available in Firefox's private mode and will throw a `DOMException: The operation is insecure.` error

#### What did you expect to see?

A warning in the docs explaining that all operations should be guarded by `if ('serviceWorker' in navigator)`

It's not intuitive that CacheStorage APIs are not available in Firefox's private mode and can only be checked (AFAIK) by checking if service workers are available

#### Did you test this? If so, how?

`caches.open('test').then(console.log)` will succeed in Firefox

The same operation in Firefox private mode will throw an error

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/cachestorage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/cachestorage/index.html
* Last commit: https://github.com/mdn/content/commit/a559c7d8a9e43bf3dc669050a408032f568c8edb
* Document last modified: 2021-07-06T08:21:07.000Z

</details>

**Comment by himanshugarg** [comment]
The security note says :-

> This feature is available only in secure contexts

And `window.isSecureContext` is `true` in private mode. Along with the suggested fix, what might be an explanation for  `caches.open('test')` being disabled? Shouldn't the private mode take care of cache cleanup on close?

**Comment by Trinovantes** [comment]
According to this bug report https://bugzilla.mozilla.org/show_bug.cgi?id=1320796, it seems Cache Storage/Service Worker implementation requires file system access. It's disabled in Firefox private mode whereas Chrome's incognito mode uses a memory file system.
