### ISSUE TITLE
Issue with "font-synthesis": (short summary here please)####Display error

### ISSUE THREAD

**Issue by mglight** [mdn/content#8116]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/font-synthesis`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-synthesis/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>
The result displayed under 'Disabling font synthesis' is incorrect, it should not be italic.

**Comment by mglight** [comment]
The result displayed under 'Disabling font synthesis' is incorrect, it should not be italic.

**Comment by AnilSeervi** [comment]
It's the behaviour of `<em>`  tags.
The example shows how to disable `font-systhesis` using its `none` property value

**Comment by NegiAkash890** [comment]
> MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis
> 
> #### What information was incorrect, unhelpful, or incomplete?
> #### Specific section or headline?
> #### What did you expect to see?
> #### Did you test this? If so, how?
> MDN Content page report details
> The result displayed under 'Disabling font synthesis' is incorrect, it should not be italic.

Hi @mglight that might be because of compatibility issue.

Here is the table :


![image](https://user-images.githubusercontent.com/55234838/130325742-bbcc03dd-8fa9-43b6-bf4f-a2abfa6ba01a.png)

**Comment by rachelandrew** [comment]
Closing as the result is correct in a supporting browser.
