### ISSUE TITLE
Array.from, which is first? length or iterable?

### ISSUE THREAD

**Issue by gMan1990** [mdn/content#8118]
https://github.com/mdn/content/blob/27ffb76e66e25862f9092d4eb80b217068d1c754/files/en-us/web/javascript/reference/global_objects/array/from/index.md#L54

```js
// test code
let str="\u{1F601}";
console.log(str.length);
console.log(str[Symbol.iterator]);
console.log(Array.from(str).length);
```

**Comment by gibson042** [comment]
Array.from is defined at https://tc39.es/ecma262/#sec-array.from , and checks if its first argument is iterable before falling back to interpreting it as an array-like. So for example, `Array.from({length: 0, [Symbol.iterator]: function*(){yield 0; yield 1; yield 2}}).length` is 3.

**Comment by sideshowbarker** [comment]
Thanks @gibson042.

@gMan1990 Does the information in https://github.com/mdn/content/issues/8118#issuecomment-903143487 resolve your question?
