### ISSUE TITLE
PublicKeyCredentialCreationOptions.attestation: missing enum value "enterprise"

### ISSUE THREAD

**Issue by jpstotz** [mdn/content#8126]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/attestation

#### Specific section or headline?

Section `Value` defines three possible values: 

* "none": 
* "indirect"
* "direct"

According to WebAuthn level3 & level 2 the possible values of `publicKeyCredentialCreationOptions.attestation` are defined by the enum `AttestationConveyancePreference`:

> This member is intended for use by Relying Parties that wish to express their preference for attestation conveyance. Its values SHOULD be members of AttestationConveyancePreference

See https://w3c.github.io/webauthn/#dom-publickeycredentialcreationoptions-attestation and https://www.w3.org/TR/2021/REC-webauthn-2-20210408//#dom-publickeycredentialcreationoptions-attestation

And AttestationConveyancePreference is defined as:
```
enum AttestationConveyancePreference {
    "none",
    "indirect",
    "direct",
    "enterprise"
};

```
#### What did you expect to see?

The value ` "enterprise"` is missing. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/publickeycredentialcreationoptions/attestation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/attestation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/publickeycredentialcreationoptions/attestation/index.html
* Last commit: https://github.com/mdn/content/commit/3b550e1a749853c0d46c02ae5db694e4dd1f0c68
* Document last modified: 2021-06-15T14:47:47.000Z

</details>

**Comment by teoli2003** [comment]
For whoever will document this, it is in Chromium, not in Gecko. So this will need an update to bcd too.
