### ISSUE TITLE
Issue with "A first splash into JavaScript": (short summary here please)

### ISSUE THREAD

**Issue by xatracho** [mdn/content#8140]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash

#### What information was incorrect, unhelpful, or incomplete?

Hi! I don't believe the javascript is set up properly in the "Number Guessing Game" example to execute properly. I enter in a number and nothing happens.

#### Specific section or headline?

First Splash into Javascript > Example Guess the number game

#### What did you expect to see?

I expected to enter in a number and have it tell me whether it was too high or too low.

#### Did you test this? If so, how?

I opened this link in a new tab https://mdn.github.io/learning-area/javascript/introduction-to-js-1/first-splash/number-guessing-game-start.html and entered in a value. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/a_first_splash`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/a_first_splash/index.html
* Last commit: https://github.com/mdn/content/commit/cb257575007c0d4273a9c55b984387f27a1e9a41
* Document last modified: 2021-07-15T13:27:06.000Z

</details>

**Comment by wbamberg** [comment]
That is the initial setup for the game, which is linked from  https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash#initial_setup. As it says there:

> At the moment you'll see a simple heading, paragraph of instructions and form for entering a guess, but the form won't currently do anything.

It's just a template for you to add the code that actually implements the game, which is what the rest of the page takes you through.

The finished game is embedded in the page at https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash#example_%E2%80%94_guess_the_number_game, and also linked from the end of the page.

It's at https://mdn.github.io/learning-area/javascript/introduction-to-js-1/first-splash/number-guessing-game.html.
