### ISSUE TITLE
Content bug: Length of URL

### ISSUE THREAD

**Issue by estelle** [mdn/content#8143]
In /content/ under /en-us/web we have

demos_of_open_web_technologies

can we shorten it to "demos" since everything in that directory (which is just one file) is web related, or perhaps "examples" or something similar

**Comment by teoli2003** [comment]
The only reason this is kept is [this](https://github.com/mdn/content/issues/2764#issuecomment-800189030).

Note that this is really one single _logical_ MDN page (and not an MDN directory: index.html being the content of the page, without any other resources included) and should be renamed using `yarn content move oldSlug newSlug`.

I guess it is a call for @Rumyra.

**Comment by Rumyra** [comment]
🤔 Yes it's a shame we have to keep it - but yes happy for it to be shortened.
