### ISSUE TITLE
Issue with "HTMLMediaElement: canplaythrough event": (Syntax error on code example)

### ISSUE THREAD

**Issue by DiriectorDoc** [mdn/content#8145]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplaythrough_event

#### What information was incorrect, unhelpful, or incomplete?
There is a syntax error in the example code. The string opening (`'`) is on the wrong line.

#### Specific section or headline?
[Examples](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplaythrough_event#examples) section

#### What to change
```
58. -   console.log('I think I can play through the entire ' + '
59. -       video without ever having to stop to buffer.');
58. +   console.log('I think I can play through the entire ' +
59. +       'video without ever having to stop to buffer.');

67. -   console.log('I think I can play thru the entire ' + '
68. -       video without ever having to stop to buffer.');
67. +   console.log('I think I can play thru the entire ' +
68. +       'video without ever having to stop to buffer.');
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlmediaelement/canplaythrough_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplaythrough_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlmediaelement/canplaythrough_event/index.html
* Last commit: https://github.com/mdn/content/commit/3a5d65124798f70ef4777aef7ab11b7e9a5b7dbf
* Document last modified: 2021-06-13T14:10:35.000Z

</details>

**Comment by teoli2003** [comment]
Good catch! I've opened a PR with a fix.
