### ISSUE TITLE
Issue with "Internationalization": A broken link.

### ISSUE THREAD

**Issue by zhoushengdao** [mdn/content#8162]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization

#### What information was incorrect, unhelpful, or incomplete?
In the [Line 384](https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/internationalization/index.html#L384), there has a broken link.(The first link.)

#### Specific section or headline?
Testing out your extension

#### What did you expect to see?
It will link to an article about "loading from disk"

#### Did you test this? If so, how?
I don't find another article tells somethings about "Loading from disk", so I want someone to help.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/internationalization`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/internationalization/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by StephNathai** [comment]
I believe this broken link should lead [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing). Can someone please confirm if this is correct? If so, I will fix this link. This same link is also broken [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/debugging_(before_firefox_50)) (search for "package and install"). I can fix this link as well upon confirmation of the correct link.

**Comment by himanshugarg** [comment]
Thanks @StephNathai . It could also be this - https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/ . Whichever you choose, you could go ahead and create a PR without waiting too long for a confirmation.

**Comment by StephNathai** [comment]
Thanks @himanshugarg , I'll push up the fix shortly.
