### ISSUE TITLE
Content bug: <TITLE OF PROBLEM>

### ISSUE THREAD

**Issue by bt2go** [mdn/content#8168]
## What page(s) did you find the problem on?

[](https://github.com/bt2go/atom-material-ui/commit/d5ac6e307faa1df94d143d617a34416771fc6f24)

**Comment by teoli2003** [comment]
Hi!

Unfortunately, you didn't provide any information about the issue you are reporting. We cannot act on it.

I'm closing it. If you return and provide more information, you are welcome to re-open it (or fill a separate issue).

Thanks a lot for your interest!
