### ISSUE TITLE
Content bug: Browser Compatibility not found

### ISSUE THREAD

**Issue by Wixonic** [mdn/content#8221]
## What page(s) did you find the problem on?

* https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clearHitRegions
* https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/addHitRegion
* https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/removeHitRegion

## Specific page section or heading?

Browser Compatibility

## What is the problem?

No compatibility data found.

**Comment by Elchi3** [comment]
Thanks for your issue!

The compat data was removed in https://github.com/mdn/browser-compat-data/pull/8442 because these features aren't part of the web platform anymore. I'm removing the content in https://github.com/mdn/content/pull/8226

**Comment by Wixonic** [comment]
> The compat data was removed in https://github.com/mdn/browser-compat-data/pull/8442 because these features aren't part of the web platform anymore. I'm removing the content in https://github.com/mdn/content/pull/8226

Ok
