### ISSUE TITLE
Issue with "Conditional (ternary) operator": Specify short-circuit behavior

### ISSUE THREAD

**Issue by jxu** [mdn/content#8239]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

#### What information was incorrect, unhelpful, or incomplete?

For conditional operator I believe only one side will be evaluated. For example `cond ? f() : g()` will only evaluate one of f or g. It is obvious in if statements, though I'm not sure if this is obvious or not in an expression (i.e. if we thought about it as `ifelse(cond, f(), g())`).

#### Specific section or headline?

Description

#### What did you expect to see?

Short note about it

#### Did you test this? If so, how?

ex `true ? alert(0) : alert(1)`

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/conditional_operator`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/conditional_operator/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by hamishwillee** [comment]
Yes, depending on the result of the test condition (which is always evaluated) **either** the truthy or falsy expression is evaluated (but not both).

The text says that - I personally don't see how you might interpret this as both truthy and falsy expressions might get executed:

> "then an expression to execute if the condition is truthy followed by a colon (:), and finally the expression to execute if the condition is falsy."

You could submit a PR if you like if you disagree. We could then see whether the text helps or hinders.

**Comment by jxu** [comment]
True. I got confused a little when debugging earlier due to operator precedence in the condition (I wrote something like `str + cond ? ... ` then got confused about side effects. I'll leave it open to see if anyone else wants to say something

**Comment by sideshowbarker** [comment]
We’ve had this open for a week now without any further comments. So I’m going ahead and closing it. But that doesn’t actually prevent from adding new comments.
