### ISSUE TITLE
Issue with "WebGL by example": …

### ISSUE THREAD

**Issue by SimonSiefke** [mdn/content#824]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example

#### What information was incorrect, unhelpful, or incomplete?
It shows `{{IncludeSubnav("/en-US/Learn")}}`

![templating](https://user-images.githubusercontent.com/23744935/103435991-40336180-4c17-11eb-86ca-1152efa7878f.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl_api/by_example`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/webgl_api/by_example/index.html
* Report started: 2021-01-01T08:52:11.963Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/833 with a fix
