### ISSUE TITLE
Issue with "Document.importNode()": write about deep's default value

### ISSUE THREAD

**Issue by NagayamaToshiaki** [mdn/content#8249]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/importNode

#### What information was incorrect, unhelpful, or incomplete?
No info about the defaolt value of `deep` parameter.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Document/importNode#parameters

#### What did you expect to see?
Default value is false.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/importnode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/importNode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/importnode/index.html
* Last commit: https://github.com/mdn/content/commit/612e1a827520dac2cb9d79944aec91234ffcebc0
* Document last modified: 2021-08-06T05:47:18.000Z

</details>

**Comment by teoli2003** [comment]
Thanks, good catch. I've opened #8252 with a correction.
