### ISSUE TITLE
Issue with "Array": Missing methods flat and flatMap in Instance Methods section

### ISSUE THREAD

**Issue by That-Guy977** [mdn/content#8251]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

#### What information was incorrect, unhelpful, or incomplete?
The Instance Methods list did not include `flat` and `flatMap` (present in sidebar and compatibility table)

#### Specific section or headline?
Instance Methods

#### What did you expect to see?
The `flat` and `flatMap` methods listed in the section

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/index.md
* Last commit: https://github.com/mdn/content/commit/47da68432612b44565ff446e7b801046e178ce23
* Document last modified: 2021-08-01T19:24:10.000Z

</details>

**Comment by teoli2003** [comment]
Good catch! Thanks. I've opened a PR to fix this omission.
