### ISSUE TITLE
Issue with "Safely inserting external content into a page": (short summary here please)

### ISSUE THREAD

**Issue by SailorMax** [mdn/content#8258]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page

#### What information was incorrect, unhelpful, or incomplete?
This article don't talk anything about form controls!
In result when I trying to put in `textarea.value` external content as is in my extension, you moderation force me to sanitize it and give me link to this page.
Can you add some mark about it or talk about it with your moderators?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/safely_inserting_external_content_into_a_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/safely_inserting_external_content_into_a_page/index.html
* Last commit: https://github.com/mdn/content/commit/3af43c1dcfb9be19c73cf3fdd1178db9c74aa064
* Document last modified: 2021-04-27T01:03:07.000Z

</details>

**Comment by Rob--W** [comment]
Could you share the code snippet that did not pass review?
A link to the add-on is also acceptable (please mention the version number of the rejected add-on).

**Comment by sideshowbarker** [comment]
Closing for lack of response.
