### ISSUE TITLE
Content bug: mention since which Firefox version, cookies have SameSite set to Lax by default

### ISSUE THREAD

**Issue by baptx** [mdn/content#8259]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/set-cookie/samesite/index.md

## Specific page section or heading?

In "browser compatibility" section, the version number should be added in the row "Defaults to
Lax":
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#browser_compatibility

## What is the problem?

The documentation says "Standards related to the Cookie SameSite attribute recently changed" but it is not mentioned since which Firefox version, cookies have SameSite set to Lax by default, there is just the opt-in mentioned since version 69.
Another problem is that if JavaScript is disabled, for example with an addon like uMatrix or NoScript, the "browser compatibility" section does not load and displays "BCD tables only load in the browser". This error message is not clear enough, it should say "enable JavaScript to view data" but a better solution would be to use progressive enhancement for better accessibility, so we can see the version numbers without JavaScript (there is no need for JavaScript to see text content like version numbers).

Update: it looks like Firefox does not yet default to Lax but we can keep this issue open (and maybe rename the title) to make the "browser compatibility" section work without JavaScript with progressive enhancement or with a fallback at least.

## What did you expect to see?

Correct version numbers displayed even if JavaScript is disabled.

## Did you test this? If so, how?

Yes, visit the links shared above.

**Comment by hamishwillee** [comment]
Ah, now I understand you. I'm closing this and have posted as an "infrastructure" issue: https://github.com/mdn/yari/issues/4581
