### ISSUE TITLE
Issue with "Introducing a complete toolchain": (short summary here please)

### ISSUE THREAD

**Issue by AndrewSRea** [mdn/content#8268]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain

#### What information was incorrect, unhelpful, or incomplete?

This **Note** doesn't make sense, semantically, grammatically:

**Note**: If you want to just take our existing project and set it up, ready to use, you could go into the root directory of the unzipped downloaded, and run one single installation command to install all of the project’s dependencies: `npm install`. This is possible because we installed all the tools locally, not globally, and highlights why it is such a powerful option.

#### Specific section or headline?

**Getting the project code files**

#### What did you expect to see?

Clearer instruction.

#### Did you test this? If so, how?

n/a

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.html
* Last commit: https://github.com/mdn/content/commit/cb257575007c0d4273a9c55b984387f27a1e9a41
* Document last modified: 2021-07-15T13:27:06.000Z

</details>

**Comment by hamishwillee** [comment]
You're right - that's horrible. Would you be able to create a PR with a fix?

**Comment by NegiAkash890** [comment]
Working on this one : )
