### ISSUE TITLE
Anatomy of an extension: Link doesn't lead to corresponding content

### ISSUE THREAD

**Issue by leonard-9500** [mdn/content#827]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension

#### What information was incorrect, unhelpful, or incomplete?
Below the paragraph "The manifest can also contain pointers to several other types of files:" the link "Sidebars, popups, and options pages:" doesn't let the user jump to the corresponding heading on the page. It does show the path in the browser's address bar as **"Anatomy_of_a_WebExtension#Sidebars_popups_options_pages".**

#### Specific section or headline?
Sidebars, popups, and options pages:

#### What did you expect to see?
Jump to the corresponding action.

#### Did you test this? If so, how?
Tested in
Chrome 87.0.4280.88 (Official Build) (64-bit) (cohort: Stable) and
Edge 87.0.664.66 (Official build) (64-bit)
on
Windows 10 OS Version 1909 (Build 18363.1256).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/anatomy_of_a_webextension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
* Report started: 2021-01-01T12:30:23.473Z

</details>

**Comment by toshkv** [comment]
@chrisdavidmills could you assign this task to me?

**Comment by chrisdavidmills** [comment]
Certainly can; thanks for helping us out, @toshkv !

**Comment by toshkv** [comment]
Thank you!
