### ISSUE TITLE
Issue with "::-webkit-meter-bar": Link to moz-meter-bar

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/content#8271]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-meter-bar

#### What information was incorrect, unhelpful, or incomplete?

I'm aware, that vendor prefixes should be avoided if possible, but according to https://stackoverflow.com/a/56155547 a `<meter>` can be styled in Firefox, too.

Can this article link to `::-moz-meter-bar` (not on MDN yet)?

#### Specific section or headline?

See also.

#### What did you expect to see?

An example on how to style a `<meter>` across browsers (instead of falling back to cooking my own „solution”).

#### Did you test this? If so, how?

I've opened https://stackoverflow.com/a/56155547 in Firefox and Chromium and ran the example.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_doublecolon_-webkit-meter-bar`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-meter-bar
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_-webkit-meter-bar/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by schalkneethling** [comment]
Thank you for raising the issue @Ryuno-Ki. I have opened the following discussion around the larger topic of documenting vendor prefixes: https://github.com/mdn/mdn-community/discussions/128

**Comment by Rumyra** [comment]
Are we ok to close this as it's been transferred to a discussion? We can open an actionable issue once we've decided what course of action we'll take 👍

**Comment by schalkneethling** [comment]
> Are we ok to close this as it's been transferred to a discussion? We can open an actionable issue once we've decided what course of action we'll take 👍

Makes sense to me as well.
