### ISSUE TITLE
[JS] Object.hasOwn() shipped

### ISSUE THREAD

**Issue by hamishwillee** [mdn/content#8273]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Documented in #7063 but was added as nightly only in FF91. Might need some minor tidy for this.

Note, BCD for this is here: https://github.com/mdn/browser-compat-data/pull/12165

## Related Gecko bugs

Shipped FF92: https://bugzilla.mozilla.org/show_bug.cgi?id=1721149

**Comment by hamishwillee** [comment]
FYI only @Rumyra Rediscovered this task from BCD

**Comment by jamiebuilds** [comment]
FYI: `Object.hasOwn` just reached Stage 4 at today's TC39 meeting.

**Comment by sideshowbarker** [comment]
Can this be closed now that the link PRs have been merged?

**Comment by hamishwillee** [comment]
Yes, and I will because this was quite trivial. The reason I leave them open is so that @Rumyra can take a last look at the whole job and mark them closed when she is happy.

**Comment by jamiebuilds** [comment]
Should this be updated to remove the "experimental technology" warning now that it is stage 4? Or does that refer to browser support specifically?

**Comment by hamishwillee** [comment]
> Should this be updated to remove the "experimental technology" warning now that it is stage 4? Or does that refer to browser support specifically?

@jamiebuilds No. Generally this is based on the feature being supported on at least two major browser versions. I usually use the trigger of a browser compatibility update to update the flags there and in MDN.
