### ISSUE TITLE
Issue with "Basic Concepts of grid layout": (short summary here please)

### ISSUE THREAD

**Issue by KelseyThornton** [mdn/content#8277]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout

In the note regarding the 'gap', there appears to be a global replace fault. It says:

"Note: When grid first shipped in browsers the column-gap, row-gap and gap were prefixed with the grid- prefix as column-gap, row-gap and gap respectively."

The second instances should all have the (deprecated?) prefix 'grid-'.  :-)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_grid_layout/basic_concepts_of_grid_layout`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by teoli2003** [comment]
Yes, likely a too-eager cut and past. I opened a PR with a fix.
