### ISSUE TITLE
Issue with "Content scripts": Typo below "Use connection-based messaging when…"

### ISSUE THREAD

**Issue by leonard-9500** [mdn/content#828]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts

#### What information was incorrect, unhelpful, or incomplete?
"The extension **need** to know about task progress, **needs to know** if a task is interrupted, or may want to interrupt a task initiated using messaging."

I suggest also removing the second "needs to know" after the first comma as it seems a little repetitive.

#### Specific section or headline?
Use connection-based messaging when…

#### What did you expect to see?
The extension **needs** to know about task progress, if a task is interrupted, or may want to interrupt a task initiated using messaging.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/content_scripts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/add-ons/webextensions/content_scripts/index.html
* Report started: 2021-01-01T12:49:05.507Z

</details>

**Comment by chrisdavidmills** [comment]
Fixed by https://github.com/mdn/content/commit/ac211a78ad7496b31739f69ea1601b82460b4d11

Thanks for reporting!
