### ISSUE TITLE
Issue with "Tools": CSS Menu Maker (cssmenumaker.com) not Found

### ISSUE THREAD

**Issue by digi-booster** [mdn/content#8282]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Tools

#### What information was incorrect, unhelpful, or incomplete?
redundant link

#### Specific section or headline?
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/Tools#other_tools">Other Tools</a>

#### What did you expect to see?
A Website.

#### Did you test this? If so, how?
Yes, by clicking on it.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/tools`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Tools
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/tools/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by hv48067** [comment]
https://cssmenumaker.com/ can be replaced with https://www.cssportal.com/css3-menu-generator/.

**Comment by rachelandrew** [comment]
I don't think this is useful, I think we are better to add genuinely useful things to relevant pages than have a list of tools. I'll make a PR to remove it.

**Comment by wbamberg** [comment]
> The general problem with “here’s a list of external tools” pages like that is, they invite people to do self-promotion by adding their own sites/tools to the list. And even when they aren’t a vector for spammy self-promotion, such site/tool lists generally end up rotting over time, because nobody has any interest in actively maintaining/updating/pruning them.

So much this!
