### ISSUE TITLE
Issue with "Forms": …

### ISSUE THREAD

**Issue by MGreest** [mdn/content#829]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms

#### What information was incorrect, unhelpful, or incomplete?
All 3 links in main content are broken

#### Specific section or headline?
**Basic form hints**: Adding hints and descriptions for invalid or required fields
**Alerts**: Using alerts to provide client-side validation error messages
**Multi-part labels**: Enabling complex form labels with a control inside each label

#### What did you expect to see?
Appropriate page when each link was clicked on.

#### Did you test this? If so, how?
Tested on Edge

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/forms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/accessibility/aria/forms/index.html
* Report started: 2021-01-01T13:12:46.159Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/831 with a fix.
