### ISSUE TITLE
Why Promise.all on Service Workers' event.waitUntil(caches.keys() ...

### ISSUE THREAD

**Issue by hacktivista** [mdn/content#8312]
In several places over MDN (and internet in general) I've found code using Promise.all to clear the cache on the activate event of service workers. I can't understand why, since the promise of caches.keys() resolves to a plain array of strings instead of an array of promises.

Here is (kind of) what I've seen:
```
self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keyList) => {
    return Promise.all(keyList.map((key) => {
      // ... do something ...
    }));
  }));
});

```

Here is what I think is correct:
```
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keyList) => {
    keyList.forEach((key) => {
      // ... do something ...
    });
  }));
});
```

Here a list of the files I've found this (apparent) mistake on MDN:
- content/files/en-us/web/api/service_worker_api/using_service_workers/index.html
- content/files/en-us/web/api/cachestorage/keys/index.html
- content/files/en-us/web/api/cachestorage/delete/index.html
- content/files/en-us/web/progressive_web_apps/offline_service_workers/index.html

**Comment by himanshugarg** [comment]
Nice catch @hacktivista . I'll take it from here :)

**Comment by himanshugarg** [comment]
Thanks @sideshowbarker . On a second look, the current code looks alright. The `Promise.all()` call, is meant to resolve on the results of the promises returned by the `map`ped calls to `cache.delete()` which does indeed [return a promise](https://developer.mozilla.org/en-US/docs/Web/API/Cache/delete). And this is the same on all the pages reported. What do you think @hacktivista ?

**Comment by himanshugarg** [comment]
The code sample in issue #8695 provides evidence that no more changes are required for this one.
