### ISSUE TITLE
Images stretched

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#832]
Some images are stretched there.
https://developer.mozilla.org/en-US/docs/web/http/cors

Is fixable in this repository via some HTML change?

## GitHub URL
TBD

## Screenshot
![Screenshot_20210101-192401.png](https://user-images.githubusercontent.com/44380480/103444238-173abd00-4c67-11eb-8f67-0d344d2bc95a.png)

**Comment by Ryuno-Ki** [comment]
I believe, this comes up time and again. Perhaps worth to create a meta issue to collect all duplicates?

**Comment by mattiapontonio** [comment]
@Ryuno-Ki i was thinking the same thing.
We Need to comment and use the title with the keywords like in SEO

- stretched
- immagini schiacciate 🇮🇹
- img
- inline style
- global content issue
- ... 🤷🏻‍♂️

**Comment by mattiapontonio** [comment]
https://github.com/mdn/content/search?q=stretched&type=issues

**Comment by mattiapontonio** [comment]
https://github.com/mdn/content/pull/390/files

**Comment by mattiapontonio** [comment]
![Screenshot_20210120-011128.png](https://user-images.githubusercontent.com/44380480/105109239-76e4f500-5abc-11eb-8e4c-78c9a7d50b05.png)

👍 Fixed
