### ISSUE TITLE
Issue with "Link": missing Browser compatibility table

### ISSUE THREAD

**Issue by sacru2red** [mdn/content#8347]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link

#### What information was incorrect, unhelpful, or incomplete?

It seems like Specifications, Browser compatibility parts are broken.

but there is a [Resources_and_specifications](https://developer.mozilla.org/ko/docs/Web/HTTP/Resources_and_specifications) doc, RFC 5988

ps1. sorry about my english
ps2. 
[refer1](https://www.iana.org/assignments/link-relations/link-relations.xhtml)
[refer2](https://www.w3.org/TR/REC-html40/types.html#type-links)

#### Specific section or headline?

Specifications, Browser compatibility

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/link`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/link/index.md
* Last commit: https://github.com/mdn/content/commit/46234997b6257b619423a11ce31154afa336143f
* Document last modified: 2021-08-13T16:17:49.000Z

</details>

**Comment by sacru2red** [comment]
> @sacru2red 닫은 이유가 있나요? 그것은 나에게 완벽하게 유효한 문제처럼 보입니다 ...



> @sacru2red Any reason you closed this? It looks like a perfectly valid issue to me…

don't you mean you're on plan?
I thought It will be relsolve someday

**Comment by sacru2red** [comment]
> @sacru2red Any reason you closed this? It looks like a perfectly valid issue to me…

don't you mean you're on plan?
I thought It will be relsolve anytime

**Comment by teoli2003** [comment]
Yes, but I will be using your report to not forget it :-) Thanks for it!

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/browser-compat-data/pull/18126 as the page has the spec link and browser compat data now. Further changes, should there be any, should go into BCD.
