### ISSUE TITLE
Issue with "Using Promises": Promise rejection events and Node.js

### ISSUE THREAD

**Issue by danburzo** [mdn/content#838]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises

#### What information was incorrect, unhelpful, or incomplete?

> One case of special usefulness: __when writing code for Node.js__, it's common that modules you include in your project may have unhandled rejected promises. These get logged to the console by the Node runtime. You can capture these for analysis and handling by your code—or just to avoid having them cluttering up your output—by __adding a handler for the unhandledrejection event__, like this:

(Emphasis mine)

The article then offers a browser-only solution, involving the _window_ object. Should it use [`process.on(...)`](https://nodejs.org/api/all.html#process_event_unhandledrejection) instead?

#### Specific section or headline?

§[Promise Rejection Events](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#Promise_rejection_events)

#### What did you expect to see?

Either a Node-specific example for the proposed scenario, or a different, browser-specific scenario for the code sample.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/using_promises`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/guide/using_promises/index.html
* Report started: 2021-01-01T20:49:10.282Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/840 with some replacement language and code.

**Comment by danburzo** [comment]
Ah, much better, thank you!
