### ISSUE TITLE
Issue with ":nth-last-of-type()": Deprecated HTML element used in example - <strike>

### ISSUE THREAD

**Issue by digi-booster** [mdn/content#8385]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-of-type

#### What information was incorrect, unhelpful, or incomplete?

Example using the deprecated HTML element
<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike">strike</a>
#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-of-type#html
#### What did you expect to see?

del or s
#### Did you test this? If so, how?
Nope!

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_nth-last-of-type`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-of-type
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_nth-last-of-type/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by digi-booster** [comment]
> @teoli2003 this issue can be closed now.

Yes, but the result iframe is still using the strike element if you know how to access that code, please fix it, thanks in advance.

**Comment by AnilSeervi** [comment]
> > @teoli2003 this issue can be closed now.
> 
> Yes, but the result iframe is still using the strike element if you know how to access that code, please fix it, thanks in advance.

Yes, that's what you've changed. It'll take effect shortly.
