### ISSUE TITLE
Issue with "async function":  return await promiseValue vs. return promiseValue 

### ISSUE THREAD

**Issue by danburzo** [mdn/content#839]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

#### What information was incorrect, unhelpful, or incomplete?

The information box at the end of the article sets out to elucidate how:

> The implicit wrapping of return values in `Promise.resolve` does not imply that `return await promiseValue` is functionally equivalent to `return promiseValue`.

However, it seems to me the example goes out of its way to elicit a "gotcha". In the usual asynchronous function, an unconditional `return promise` has the same practical effect as `return await promise`. Wrapping the construct in a `try/catch` block obviously changes the semantics (the awaitless promise should get its corresponding `catch()`), but I wonder if that proves the point satisfactorily, or whether on the whole it sets up an unnecessary caveat lector.

#### Specific section or headline?

The _return await promiseValue vs. return promiseValue_ info box.

#### What did you expect to see?

IMHO the infobox can be removed.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/async_function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/statements/async_function/index.html
* Report started: 2021-01-01T21:33:43.671Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. I agree with the points made in the issue description — so I’ve opened https://github.com/mdn/content/pull/5818 with a fix which completely drops that “notecard”.
