### ISSUE TITLE
Issue with "Basic usage of canvas": (broken link inside Fallback Content )

### ISSUE THREAD

**Issue by angelayanpan** [mdn/content#8396]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_usage

#### What information was incorrect, unhelpful, or incomplete?

> Telling the user to use a different browser that supports canvas does not help users who can't read the canvas at all, for example. Providing a useful fallback text or sub DOM helps to make the canvas more accessible. 

 **(broken link here)**

Sorry, the page /en-US/docs/Web/API/Canvas_API/Tutorial/Hit_regions_and_accessibility could not be found.

#### Specific section or headline?
    Fallback Content

#### What did you expect to see?

    either no link. or a link that directs to a page with helpful content. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvas_api/tutorial/basic_usage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_usage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/basic_usage/index.html
* Last commit: https://github.com/mdn/content/commit/8f97f1f075370e145b155d4309e3fbc477f8d5d1
* Document last modified: 2021-08-21T17:09:49.000Z

</details>

**Comment by Elchi3** [comment]
Yes, so Hit Regions aren't specced and in browsers anymore so this content was removed. Looks like I missed a link here. Opening a PR to remove it.
