### ISSUE TITLE
Issue with "<details>: The Details disclosure element": (short summary here please)

### ISSUE THREAD

**Issue by jjnilton** [mdn/content#8398]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

#### What information was incorrect, unhelpful, or incomplete?

> Chrome doesn't support this yet, however, so we also need to use its non-standard ::-webkit-details-marker pseudo-element to customize the appearance in that browser.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#customizing_the_disclosure_widget

#### What did you expect to see?

Maybe this referring to old Chrome versions?

#### Did you test this? If so, how?

Tried to remove the summary style with `summary { list-style: none }` and it worked both in Chrome for Linux and Chrome for Android.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/details`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/details/index.html
* Last commit: https://github.com/mdn/content/commit/8d28de329fc4f723ad4362f0f703e46c4fa9e32d
* Document last modified: 2021-06-02T17:52:41.000Z

</details>

**Comment by NegiAkash890** [comment]
Hi @jjnilton . Yes, it works fine and the combability table at the end of the doc also says so. 

![image](https://user-images.githubusercontent.com/55234838/131206829-267be30c-a257-4dfa-aeed-fb09c5598131.png)

We can do one of the two things either drop the section or update the current section just to show how to `customize the disclosure widget`.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #8450 with a fix that just drops that outdated note.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
