### ISSUE TITLE
Issue with "Canvas API": (left sidebar content under Examples: missing link )

### ISSUE THREAD

**Issue by angelayanpan** [mdn/content#8400]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API

#### What information was incorrect, unhelpful, or incomplete?
 2 second item under **Examples** named "Canvas code snippets" ( under "A basic raycaster")  doesn't have content inside? or missing link? 

> Sorry, the page /en-US/docs/Mozilla/Add-ons/Code_snippets/Canvas could not be found.

#### Specific section or headline?

examples on the left side panel 
 
#### What did you expect to see?

missing link 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvas_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/index.html
* Last commit: https://github.com/mdn/content/commit/e317eb64ed790b7b6e8753f907a7efba530b70c8
* Document last modified: 2021-08-23T20:45:51.000Z

</details>
![Capture](https://user-images.githubusercontent.com/2455168/131173474-bb14becc-9cd6-4ab7-96e3-96d3dad243a2.JPG)

**Comment by wbamberg** [comment]
Thanks for filing!

This was an archived page has recently been removed from the site (see https://hacks.mozilla.org/2021/08/spring-cleaning-mdn-part-2/). The content still exists at https://github.com/mdn/archived-content/blob/main/files/en-us/archive/add-ons/code_snippets/canvas/index.html.

Was there something there in particular that you were looking for? If it's valuable we could restore the part of it that's Web-accessible (as opposed to the part that's for add-ons only). But it doesn't look particularly valuable to me - I think it would be better to remove the sidebar link. The canvas tutorial seems to be a much more organized way to learn useful things about Canvas.

**Comment by angelayanpan** [comment]
"Was there something there in particular that you were looking for?"  no, was just looking at the "raycaster" section above it and then moved on to this link to see what it contains. 

Thank!
