### ISSUE TITLE
HTML Drag and Drop API needs overhaul

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#8404]
In particular, it lists multiple APIs which haven't been supported anywhere for > 2 years, such as:

https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/mozSetDataAt
https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/mozItemCount

...and guides that talk extensively about these APIs, such as:

https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Multiple_items
https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types

**Comment by skyclouds2001** [comment]
As I didn't find any reference about these two proerties yet when searching in this repository, expect for the firefox release note, maybe it's time to close this issue

**Comment by Josh-Cena** [comment]
Done in https://github.com/mdn/content/pull/22092
