### ISSUE TITLE
Issue with "opacity": setting background opacity example is vague

### ISSUE THREAD

**Issue by AnilSeervi** [mdn/content#8411]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/opacity

#### What information was incorrect, unhelpful, or incomplete?
- The [example](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#setting_background_opacity) is kinda vague.
- The example is applying opacity on both the text and the background i.e., the whole element itself and this doesn't demonstrate `setting opacity on a background`.

#### Specific section or headline?
- [`Setting Background Opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#setting_background_opacity)

#### What did you expect to see?
- Perhaps the right way to do it would be to have something behind the element and then apply different values of opacity to the foreground element to make the element behind visible? 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/opacity`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/opacity
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/opacity/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by digi-booster** [comment]
I think the title should be <b>setting the opacity of elements</b> instead of <b>setting background opacity</b>, or background: rgba(225, 225, 0, a); should be used in CSS.

**Comment by rachelandrew** [comment]
I'm more concerned that the example mentions IE7 :D I'll do some work on this page.
