### ISSUE TITLE
Issue with "Right shift (>>)": Wrong binary conversion

### ISSUE THREAD

**Issue by olaoluwa-98** [mdn/content#8414]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Right_shift

#### What information was incorrect, unhelpful, or incomplete?

`-9` base 10 should be  1000 0000 0000 0000 0000 0000 000 1001 in base 2 but in the right shift example `-9 >> 2 `, `-9` was  represented as 1111 1111 1111 1111 1111 1111 1111 0111. Same mistake was made for `-3` base 10.

#### Specific section or headline?

description

#### What did you expect to see?

- Expected `-9` base 10 to be `1000000000000000000000000001001` in base 2
- Expected `-3` base 10 to be `1000000000000000000000000000011` in base 2

#### Did you test this? If so, how?
```js
console.log((-9).toString(2)) // -1001 which will be 1000000000000000000000000001001 in 32 bit
console.log((-3).toString(2)) // -11 which will be 1000000000000000000000000000011 in 32 bit
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/right_shift`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Right_shift
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/right_shift/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by NegiAkash890** [comment]
Hi @olaoluwa-98 you are right  when we are taking about just `binary` representation of these numbers but on further investigation I noticed that it was intentional that author used `signed binary` representation instead of `binary` representation. I think it's worth mentioning this in the doc as well and can be confusing .

**Comment by olaoluwa-98** [comment]
@NegiAkash890 thanks for the clarification. I think the docs should mention that `signed binary` representation is being used so it's clearer.

**Comment by NegiAkash890** [comment]
Hi @sideshowbarker if it's fine can you assign me this ?

**Comment by sideshowbarker** [comment]
> Hi @sideshowbarker if it's fine can you assign me this ?

I’ve already been working on it and will opening a PR for it soon.
