### ISSUE TITLE
Issue with "Unsigned right shift (>>>)": Wrong binary conversion

### ISSUE THREAD

**Issue by olaoluwa-98** [mdn/content#8415]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Unsigned_right_shift

#### What information was incorrect, unhelpful, or incomplete?

`-9` base 10 should be  1000 0000 0000 0000 0000 0000 000 1001 in base 2 but in the right shift example `-9 >> 2 `, `-9` was  represented as 1111 1111 1111 1111 1111 1111 1111 0111.

#### Specific section or headline?

description

#### What did you expect to see?

Expected `-9` base 10 to be `1000000000000000000000000001001` in base 2

#### Did you test this? If so, how?
```js
console.log((-9).toString(2)) // -1001 which will be 1000000000000000000000000001001 in 32 bit
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/unsigned_right_shift`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Unsigned_right_shift
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/unsigned_right_shift/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by AnilSeervi** [comment]
`(-9>>>0).toString(2)` returns `"11111111111111111111111111110111"` and not the value you mentioned.
You can check here https://stackoverflow.com/questions/9939760/how-do-i-convert-an-integer-to-binary-in-javascript for more info on why?

**Comment by teoli2003** [comment]
Closing per [comment](https://github.com/mdn/content/issues/8415#issuecomment-907738329)

**Comment by olaoluwa-98** [comment]
@AnilSeervi  thanks for the clarification. I think the docs should mention that `signed binary` representation is being used so it's clearer.
