### ISSUE TITLE
add hreflang

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/content#842]
add `hreflang` to the `a` of #777

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

**Comment by toshkv** [comment]
@chrisdavidmills could you assign this task to me?

**Comment by mattiapontonio** [comment]
@toshkv I saw this:
https://github.com/toshkv/orthographic-pedant

Can You automate something that correct a lot of things but in small PR?

This is an example of a thing that should be done several times.

There's a lot of things that I imagine should be at least PR by a bot.

Just for ask.

**Comment by toshkv** [comment]
@mattiapontonio I'm not sure. Sounds like a great idea. I forked that repo out of interest, but I can't say I know how to customize it for the purpose you are describing. I'm happy to learn how to. I'll look into it.

**Comment by mattiapontonio** [comment]
@toshkv this Is the One that i was thinking about:

https://github.com/mdn/content/issues/832

But feel free to navigating around and open and closing issues and open, drafting and closing PR

**Comment by mattiapontonio** [comment]
See also https://github.com/mdn/yari/pull/2279

**Comment by nschonni** [comment]
Why should a link on the English page going to another link on the English site have an hreflang?

**Comment by mattiapontonio** [comment]
`hreflang`
> Hints at the human language of the linked URL. No built-in functionality. Allowed values are the same as the global lang attribute.

We could for example add a flag via CSS. There is no real reason, it is an attribute that enriches the html right now.
In any case it is a case that the URL is in a page in the same language, it is not said and above all it is not "defined in that scope".

It could also be an English page in a specific French div with a link pointing to a German page.

In general I wanted to understand what can be done with all attributes and whether or not they are implemented in macros.

**Comment by mattiapontonio** [comment]
You should create elements with all attributes set and deployed so they are created as macros for copy and paste.

**Comment by mattiapontonio** [comment]
And if o don't want the flag? 🙄
Make It optional

```html
<a
hreflang="fr"
data-flag
>
```

**Comment by mattiapontonio** [comment]
Even that is a link written in italian that point to a franch Page

```html
<a
href="/pâtes-à-la-carbonara"
hreflang="fr"
lang="it"
>
La ricetta pasta alla carbonara scritta in francese
</a>
```

**Comment by chrisdavidmills** [comment]
In the grand scheme of things, adding `hreflang` is not important right now, compared to all the other things we have to fix, so I'm closing this one. I shouldn't have tagged it in the first place.

If we do want to add hreflang to all anchors throughout MDN, then we should discuss it at a high level first, rather than trying to "fix" individual cases.
