### ISSUE TITLE
Issue with "class": (short summary here please)

### ISSUE THREAD

**Issue by farzaneh9978** [mdn/content#8422]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class

#### Did you test this? If so, how?
I use this is template for django website but when I want it works dynamic with class="{% if  request.path == path %} current-menu-item{% endif %}" or class="{% if  request.path == teaching_url %}active{% endif %}" is not work.please help me :(

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/global_attributes/class`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/class/index.html
* Last commit: https://github.com/mdn/content/commit/a90c5d2bfa167fff2df049096dee5ee0dd937c3f
* Document last modified: 2021-05-20T21:15:13.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing, problems in the MDN documentation.

It looks like you are looking for help with your code. Unfortunately, we don't have enough availability to help you.

May I suggest asking your question on a specialized website, like StackOverflow?

I'm closing this issue. If I've misunderstood you and you were actually reporting a problem in the documentation, feel free to reopen it, while providing more information so we can understand the problem.

Thanks for your interest.
