### ISSUE TITLE
Issue with "All keyboard shortcuts": Source Editor section is incomplete

### ISSUE THREAD

**Issue by MikuChan03** [mdn/content#8446]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts

#### What information was incorrect, unhelpful, or incomplete?
The "Source editor" section is a bit off. It starts by telling us how to change the preferred keymap in the Editor Preferences, goes on to telling us about changing it in the about:config site, before finally assuring us that we can change it in Editor Preferences.
Also the content is by definition incomplete. How can there be only one set of bindings, when you just said that there is actually support for 4 different keymaps, namely default, vim, emacs and sublime. Please tell us which bindings are being displayed and what the alternative keymaps look like. Since this is no small task, maybe you could in the meantime at least put up links to the keymap files as they are being used in CodeMirror. I have gone through the troublems of searching them out for you, with the first line being the default keymap:

https://codemirror.net/src/input/keymap.js
https://codemirror.net/keymap/emacs.js
https://codemirror.net/keymap/vim.js
https://codemirror.net/keymap/sublime.js

#### Specific section or headline?
Source editor

#### What did you expect to see?
Good stuff

#### Did you test this? If so, how?
Tested this using a rather inefficient processor called my brain.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/keyboard_shortcuts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/keyboard_shortcuts/index.html
* Last commit: https://github.com/mdn/content/commit/6e59c64149037dd061cd56064b92ac18684368a7
* Document last modified: 2021-05-07T07:36:48.000Z

</details>

**Comment by MikuChan03** [comment]
That oughta do it.

**Comment by MikuChan03** [comment]
If it's alright for you guys, I can do the changes myself and then link a pull request. Is that something that you're ok with?

**Comment by sideshowbarker** [comment]
> If it's alright for you guys, I can do the changes myself and then link a pull request. Is that something that you're ok with?

I think that’d be great.

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
