### ISSUE TITLE
Issue with "Accessibility: What users can do to browse more sa…": …

### ISSUE THREAD

**Issue by nicklum** [mdn/content#845]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/Accessibility:_What_users_can_to_to_browse_safely

#### What information was incorrect, unhelpful, or incomplete?

The primary purpose of BeeLine Reader is to enable color gradient text, which assists visual tracking and is helpful for many people with dyslexia, ADHD, or visual impairments. While grayscale is one possible configuration, it is not one of the more popular options. Also, the BeeLine Reader plugin offers the OpenDyslexic font, not Dyslexie.

If you have further questions about how to describe BeeLine, feel free to email me: nick@beelinereader.com. I am the founder of BeeLine.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/accessibility_colon__what_users_can_to_to_browse_safely`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/Accessibility:_What_users_can_to_to_browse_safely
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/accessibility/accessibility_colon__what_users_can_to_to_browse_safely/index.html
* Report started: 2020-12-31T19:54:23.465Z

</details>

**Comment by ericwbailey** [comment]
Closing for spam.
