### ISSUE TITLE
Issue with "URL.searchParams": (short summary here please)

### ISSUE THREAD

**Issue by Ark-kun** [mdn/content#8452]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams

#### What information was incorrect, unhelpful, or incomplete?

The example code constructs the URL object the following way: `new URL(document.location)`. The type of `document.location` is `Location` but the `URL` constructor accepts `string`, not `Location`.

Would it be better to use `new URL(document.location.href)` like on this page? https://developer.mozilla.org/en-US/docs/Web/API/URL#usage_notes

I might be wrong though...

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/url/searchparams`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/url/searchparams/index.html
* Last commit: https://github.com/mdn/content/commit/e9f0298e84dd04caa14270e703ee21d4b70a9786
* Document last modified: 2021-06-17T02:20:25.000Z

</details>

**Comment by teoli2003** [comment]
The example is correct. `Location` has a _stringifier_ that is a `toString()` method that is called wherever a `Location` object must be converted to a string, like in the example.

in the case of `Location`, the `.toString()`  method is actually a read-only version of the `href` property.

See the [HTML spec](https://html.spec.whatwg.org/multipage/history.html#the-location-interface) and the [WebIDL spec](https://heycam.github.io/webidl/#idl-stringifiers). This is a common pattern used in many Web APIs.

So, the example does work, is a common pattern, and is the shortest way of achieving it.

**Comment by Ark-kun** [comment]
@teoli2003 Thank you for explanation.

My issue was prompted by TypeScript throwing error for that expression:
`Argument of type 'Location' is not assignable to parameter of type 'string'.ts(2345)`

I guess, the TS team should map/detect the types with stringifiers and the classes that accept them.

**Comment by teoli2003** [comment]
Yes, likely. Meanwhile, I'm closing this.
