### ISSUE TITLE
Content bug: CanvasRenderingContext2D.createPattern SVGImageElement link

### ISSUE THREAD

**Issue by franzeal** [mdn/content#8465]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createPattern

## Specific page section or heading?

Syntax -> Parameters -> image

## What is the problem?

SVGImageElement's <image> tag reference links to the HTML element documentation.

## What did you expect to see?

SVGImageElement's <image> tag reference links to the SVG element documentation.

## Did you test this? If so, how?

I navigated the page with a web browser.

**Comment by Ryuno-Ki** [comment]
Fixed by https://github.com/mdn/content/commit/43c26180f834a1c98cd83e2a4671cd7569a43742
