### ISSUE TITLE
Issue with "Hoisting": Javascript is an interpreted language, so it should say 'interpreter' instead of 'compiler'

### ISSUE THREAD

**Issue by makennamartin97** [mdn/content#8472]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

#### What information was incorrect, unhelpful, or incomplete?
'JavaScript Hoisting refers to the process whereby the compiler allocates memory for variable and function declarations prior to execution of the code.' 

#### Specific section or headline?
First line

#### What did you expect to see?
Javascript is an interpreted language, not a compiled one. So I believe the word compiler should be switched with interpreter because Javascript source code gets translated line by line rather than as a whole like C and Java.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/hoisting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/hoisting/index.html
* Last commit: https://github.com/mdn/content/commit/a2e7e2ec8feeb18dd677cf5540ea9d726cf45d34
* Document last modified: 2021-08-19T16:18:45.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks - seems reasonable. Fixed by https://github.com/mdn/content/pull/8473
