### ISSUE TITLE
Issue with "Array.prototype.sort()": …

### ISSUE THREAD

**Issue by pengpeng9413** [mdn/content#848]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

#### What information was incorrect, unhelpful, or incomplete?
in this part of Examples, 
var stringArray = ['Blue', 'Humpback', 'Beluga'];

console.log('stringArray:', stringArray.join());
console.log('Sorted:', stringArray.sort());

stringArray: Blue,Humpback,Beluga
Sorted: Beluga,Blue,Humpback

the above output is incorrect, the correct output is following

stringArray: Blue,Humpback,Beluga
Sorted: ['Beluga','Blue','Humpback']

#### Specific section or headline?
in examples

#### What did you expect to see?
the correct output is like this :
stringArray: Blue,Humpback,Beluga
Sorted: ['Beluga','Blue','Humpback']

#### Did you test this? If so, how?
i test this in chrome in console, and the array of join method in javascript seems con't change the origin array
![image](https://user-images.githubusercontent.com/17780650/103455424-f9815c80-4d27-11eb-9373-a983d4bf6bd0.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/sort`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/array/sort/index.html
* Report started: 2021-01-02T09:56:45.883Z

</details>

**Comment by sideshowbarker** [comment]
Nice catch. Thanks for reporting it. I’ve opened https://github.com/mdn/content/pull/852 with a fix.
