### ISSUE TITLE
Issue with "Animating objects with WebGL": Confusing in the word "Making the square rotate"

### ISSUE THREAD

**Issue by khoand7** [mdn/content#8486]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Animating_objects_with_WebGL

#### What information was incorrect, unhelpful, or incomplete?
I think ""Making the square rotate"" is confusing for the beginner. Looking at the source code, I think we are rotating the camera instead of the Square.

#### Specific section or headline?
Making the square rotate

#### What did you expect to see?
May be we could add a few statements about camera rotating and explain more detail about modelViewMatrix here.

#### Did you test this? If so, how?
Yes, the source code is working fine. But the document confused me.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webgl_api/tutorial/animating_objects_with_webgl`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Animating_objects_with_WebGL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/tutorial/animating_objects_with_webgl/index.html
* Last commit: https://github.com/mdn/content/commit/e317eb64ed790b7b6e8753f907a7efba530b70c8
* Document last modified: 2021-08-23T20:45:51.000Z

</details>

**Comment by vlwkaos** [comment]
It seems there actually is a sentence indicating that the sample is rotating the camera at the top.

> In this example, we'll actually rotate our square plane.

I will take a look at this and place that information somewhere more noticeable so that it is less confusing for people.
