### ISSUE TITLE
Issue with "history.deleteAll()": (short summary here please)

### ISSUE THREAD

**Issue by thomasmoors** [mdn/content#8488]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history/deleteAll

#### What information was incorrect, unhelpful, or incomplete?

This function seems not to exist in at least Chrome.

#### Specific section or headline?
Code example also does not work. Also browser is not a default object in the root (window).

#### What did you expect to see?
That this function is depricated (or never existed, I don't know)

#### Did you test this? If so, how?
https://jsfiddle.net/tgkanb6p/

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/history/deleteall`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history/deleteAll
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/history/deleteall/index.html
* Last commit: https://github.com/mdn/content/commit/eb5d682cbe5664b933e793ff6434fb252686f3c3
* Document last modified: 2021-05-31T17:26:19.000Z

</details>

**Comment by sideshowbarker** [comment]
I think the https://jsfiddle.net/tgkanb6p/ test case may not be the correct way to test this.

The `deleteAll()` method isn’t available to normal frontend JavaScript code — instead it’s a method that’s restricted to being available to extensions.

https://developer.chrome.com/docs/extensions/reference/history/#method-deleteAll has the Chrome docs for it.

Given all that, I’m going ahead and closing this. But if I’ve misunderstood anything, then this issue can be revisited.

**Comment by thomasmoors** [comment]
I think I read over that part as I was coming from google. Thanks for clearing this up!
