### ISSUE TITLE
Issue with "max-width": live example iframe not working

### ISSUE THREAD

**Issue by digi-booster** [mdn/content#8490]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/max-width

#### What information was incorrect, unhelpful, or incomplete?
An iframe is not loading -
firefox show this message in an iframe;
Firefox Developer Edition can't open this page

To protect your security, yari-demos.prod.mdn.mozit.cloud will not allow Firefox Developer Edition to display the page if another site has embedded it. To view this page, you must open it in a new window.

![screenshot (13)](https://user-images.githubusercontent.com/74658643/131487700-c6f83697-432f-4d93-b14e-122dcf754f86.png)

 and open a new window showing page not found:
![screenshot (14)](https://user-images.githubusercontent.com/74658643/131488583-06793be2-2d1d-40dd-8f76-d297563b1269.png)

And Chrome is showing this in the console log:
![screenshot (11)](https://user-images.githubusercontent.com/74658643/131487891-a4b73781-f700-4d91-a7db-66ac8b3abad9.png)
![screenshot (12)](https://user-images.githubusercontent.com/74658643/131487947-f4984e8b-99f0-4fe8-ae74-36f506361cb7.png)

#### Specific section or headline?

<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/max-width#setting_max_width_in_pixels">Example - Setting max width in pixels</a>

#### What did you expect to see?
result?

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/max-width`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/max-width
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/max-width/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by AnilSeervi** [comment]
This issue must be fixed by now but it seems to still persist.
mdn/yari#4535 proposed a fix for the issues at #8020 and #8124 
and certainly this [issue]() too seems to be the same  :/

**Comment by digi-booster** [comment]
> This issue must be fixed by now but it seems to still persist.
> [mdn/yari#4535](https://github.com/mdn/yari/pull/4535) proposed a fix for the issues at #8020 and #8124
> and certainly this issue too seems to be the same :/

For me, this page iframe is still not working and the issue you mentioned is also not working from my side.

**Comment by teoli2003** [comment]
I think mdn/yari#4613 will fix it. Please recheck this on Monday once the fix has propagated to the live site.

**Comment by digi-booster** [comment]
> I think [mdn/yari#4613](https://github.com/mdn/yari/pull/4613) will fix it. Please recheck this on Monday once the fix has propagated to the live site.

Yes, it's fixed now.
Thanks, I'm closing the issue now.
