### ISSUE TITLE
Issue with "Window.localStorage": Safari deletes after 7 days unvisited

### ISSUE THREAD

**Issue by dsernst** [mdn/content#8510]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

#### What information was incorrect, unhelpful, or incomplete?

The page suggests that localStorage persists forever. 

But then WebKit made this March 2020 announcement https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/ that they will automatically clear a domain's localStorage after 7 days where the browser is opened but the domain is not visited.

#### Specific section or headline?

>  the stored data is saved across browser sessions.

> except that while `localStorage` data has no expiration time

#### What did you expect to see?

A clarification note about Apple's stated policy of automatically deleting a domains localStorage if not visited for 7 days when Safari is opened.

Some commentary on this issue:

- https://www.theregister.com/2020/03/26/apple_relax_were_not_totally/
- https://ar.al/2020/03/25/apple-just-killed-offline-web-apps-while-purporting-to-protect-your-privacy-why-thats-a-bad-thing-and-why-you-should-care/
- https://andregarzia.com/2020/03/private-client-side-only-pwas-are-hard-but-now-apple-made-them-impossible.html

These all respond to the announcement, but I'm having trouble finding recent documentation about this issue on MDN or elsewhere.

#### Did you test this? If so, how?

Not yet. Requires at least 7 days to test, but I can write something up if there's interest.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/localstorage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/localstorage/index.html
* Last commit: https://github.com/mdn/content/commit/67029603b9457e2ec278a254998df208ff2591c3
* Document last modified: 2021-08-21T21:04:34.000Z

</details>

**Comment by dsernst** [comment]
Another clarifying comment about this from a Safari team member: https://twitter.com/jonathandavis/status/1243228885006708737

**Comment by sideshowbarker** [comment]
> Not yet. Requires at least 7 days to test, but I can write something up if there's interest.

Yes, please go ahead and either create a pull request with a patch — or else if for some reason you don’t want to create the pull request yourself, post some proposed text as a comment here.

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/25019
