### ISSUE TITLE
Issue with "Concurrency model and the event loop": Is console.log will be created a frame in stack

### ISSUE THREAD

**Issue by VivianWang1993** [mdn/content#8515]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop

#### What information was incorrect, unhelpful, or incomplete?
```
function foo(b) {
  let a = 10
  return a + b + 11
}

function bar(x) {
  let y = 3
  return foo(x * y)
}

console.log(bar(7)) //returns 42
```
> When calling bar, a first frame is created containing references to bar's arguments and local variables.

My question is if a frame will be created when the  console.log is processed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/eventloop`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/eventloop/index.md
* Last commit: https://github.com/mdn/content/commit/2e2631aa9d11718154ca50c2c3cc82074ab34ccd
* Document last modified: 2021-08-31T15:21:54.000Z

</details>

**Comment by vlwkaos** [comment]
@VivianWang1993 As far as I know, the `frame` sementic is akin to function execution context, so yes, `console.log` will create a frame. 

It would be thankful if anyone else would confirm my guess. 

If it is, then where would you suggest to put the relevant information in the page?

**Comment by VivianWang1993** [comment]
> @VivianWang1993 As far as I know, the `frame` sementic is akin to function execution context, so yes, `console.log` will create a frame.
> 
> It would be thankful if anyone else would confirm my guess.
> 
> If it is, then where would you suggest to put the relevant information in the page?

I agree with you. But I'm not sure about it.

**Comment by vlwkaos** [comment]
> I agree with you, so I think the `console.log` will create the first frame instead of the `bar` funciton. But I'm not sure about it.

However, `console.log` used in the code sample is just for the sake of printing the value of `bar` but not to illustrate the concept of frame stack. So the information stands.

If the existence of line `console.log`confused you understanding the concept shown on the page, then it would justify to change the content to make it more clear.

In that case, think it is better to change the code sample to simply call `bar` to match the explanation. Do you agree?

**Comment by VivianWang1993** [comment]
> > I agree with you, so I think the `console.log` will create the first frame instead of the `bar` funciton. But I'm not sure about it.
> 
> However, `console.log` used in the code sample is just for the sake of printing the value of `bar` but not to illustrate the concept of frame stack. So the information stands.
> 
> If the existence of line `console.log`confused you understanding the concept shown on the page, then it would justify to change the content to make it more clear.
> 
> In that case, think it is better to change the code sample to simply call `bar` to match the explanation. Do you agree?

Yes, I totally agree with you
