### ISSUE TITLE
Issue with "Creating hyperlinks"

### ISSUE THREAD

**Issue by jsannemo** [mdn/content#8517]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks

#### What information was incorrect, unhelpful, or incomplete?
> Second, it's more efficient to use relative URLs wherever possible. When you use an absolute URL, the browser starts by looking up the real location of the server on the Domain Name System (DNS) — see How the web works for more information. Then it goes to that server and finds the file that's being requested. With a relative URL, the browser just looks up the file that's being requested on the same server. If you use absolute URLs where relative URLs would do, you're constantly making your browser do extra work, meaning that it will perform less efficiently.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#use_relative_links_wherever_possible

#### What did you expect to see?
Surely there is no difference in DNS lookups between absolute and relative URLs? Either a browser would cache the DNS lookup for a given hostname or it would not, but only caching it for relative URLs as suggested in the guide makes no sense.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/creating_hyperlinks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/creating_hyperlinks/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. Agreed — and without that incorrect paragraph in the section, there’s actually nothing else that merits a “Use relative links wherever possible” recommendation; so I’ve opened #8519 with a change that removes that entire section.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
