### ISSUE TITLE
Issue with "DOMParser": (short summary here please)

### ISSUE THREAD

**Issue by python-coding-404** [mdn/content#8526]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMParser

#### What information was incorrect, unhelpful, or incomplete?

nothing
#### Specific section or headline?
nope

#### What did you expect to see?
a section that shows if it is nested and every tag has content of text how to access the specific text on each tag

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/domparser`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMParser
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/domparser/index.html
* Last commit: https://github.com/mdn/content/commit/b246c061055cf681b103b9053d81175e5f56e7ea
* Document last modified: 2021-08-20T04:18:21.000Z

</details>

**Comment by python-coding-404** [comment]
When You fix it I fil close the  issue

**Comment by Biki-das** [comment]
Will need to look i this Assap

**Comment by sideshowbarker** [comment]
> a section that shows if it is nested and every tag has content of text how to access the specific text on each tag

That description isn’t clear.

* In “if it is nested” what is “it”?
* Can you elaborate on exactly what you mean by “and every tag has content of text”?
* Can you elaborate on exactly what you mean by “how to access the specific text on each tag”?

Maybe it would help if you could provide a short example of a HTML document that you want to do something with using DOMParser, and then explain exactly what the parts of the document tree are that you’re referring to in the issue description.

But anyway, you do understand that all that DOMParser itself does is to take some markup source and parse it into a DOM, right? So whatever is being described in the issue description, it doesn’t seem like it relates to what DOMParser does. In particular, the “how to access the specific text on each tag” part doesn’t like something that would be appropriate for the DOMParser article.

**Comment by sideshowbarker** [comment]
Closing for lack of response. If further comments are added with responses to the questions in https://github.com/mdn/content/issues/8526#issuecomment-910521184, this could be reopened.
