### ISSUE TITLE
Issue with "Element.classList": Mention toggle or replace methods

### ISSUE THREAD

**Issue by plfstr** [mdn/content#8538]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

#### What information was incorrect, unhelpful, or incomplete?
The classList methods .toggle() and .replace are only mentioned in the code examples. There is a sentence which fails to mention them: 
> The DOMTokenList itself is read-only, although you can modify it using the add() and remove() methods.

Seems they also modify and should be mentioned in that statement?

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#returns

#### What did you expect to see?
Perhaps the sentence should mention .toggle() and .replace()?
Example: "The DOMTokenList itself is read-only, although you can modify it using the add(), remove(), replace() and toggle() methods."

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/classlist`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/classlist/index.html
* Last commit: https://github.com/mdn/content/commit/e317eb64ed790b7b6e8753f907a7efba530b70c8
* Document last modified: 2021-08-23T20:45:51.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #8539 with a fix. After that fix is merged, this issue will automatically be marked as resolved, and closed.
