### ISSUE TITLE
Issue with "<summary>: The Disclosure Summary element": typo in opening description

### ISSUE THREAD

**Issue by StephNathai** [mdn/content#8541]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary

#### What information was incorrect, unhelpful, or incomplete?
The word "element" is repeated twice in the first sentence of the `<summary>` description

#### Specific section or headline?
The typo is in the description block under the `<summary>` h1

#### What did you expect to see?
The word "element" is repeated twice. We would remove one of them so as to not have the unnecessary repetition.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/summary`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/summary/index.html
* Last commit: https://github.com/mdn/content/commit/8d28de329fc4f723ad4362f0f703e46c4fa9e32d
* Document last modified: 2021-06-02T17:52:41.000Z

</details>

**Comment by StephNathai** [comment]
I would like to fix once I am given the okay, thank you.

**Comment by wbamberg** [comment]
@StephNathai thanks for finding and offering to fix this issue! When you say "once given the appropriate permissions" - is this on your end? You shouldn't need any permissions to open a PR against this repo.

**Comment by StephNathai** [comment]
This issue was assigned to me and I was just about to get approval from my company to push this fix up. Not sure why @digi-booster opened a PR and closed this issue out on my behalf.

**Comment by wbamberg** [comment]
I'm sorry @StephNathai , this was a miscommunication on our side. It's difficult sometimes when there are lots of remote contributors and reviewers, but I would have preferred to wait for your PR. I hope it doesn't discourage you from contributing to MDN.

**Comment by StephNathai** [comment]
No worries @wbamberg, thanks so much for the clarification! I will try for another MDN contribution.
