### ISSUE TITLE
Content bug: specifications/browser compat gone

### ISSUE THREAD

**Issue by losnappas** [mdn/content#8542]
## What page(s) did you find the problem on?

For example,

https://developer.mozilla.org/en-US/docs/Web/API/btoa#specifications

https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#specifications

## Specific page section or heading?

"Specifications" and the section compat data one.

## What is the problem?

Missing the info

## What did you expect to see?

I would think that the data exists, however I'm not 100% certain as I don't recall looking for these before. I just happened to see the yellow boxes today and something seems off.

## Did you test this? If so, how?

I went to the page and saw the yellow box saying

> No compatibility data found for api.btoa.
Check for problems with this page or contribute missing data to mdn/browser-compat-data.

**Comment by wbamberg** [comment]
Thanks for filing!

I think this is a temporary thing because we moved these pages yesterday and BCD hasn't caught up yet. It should be fixed in the next couple of days.

@Elchi3 , right?

**Comment by Elchi3** [comment]
Yup, BCD will be released today and then it should be back, sorry for the temporary hassle.
