### ISSUE TITLE
Issue with "<label>": (short summary here please)

### ISSUE THREAD

**Issue by NeilWix** [mdn/content#8553]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

#### What information was incorrect, unhelpful, or incomplete?
Please elaborate on the "for" attribute. Does it support multiple ID refs?
Also, you may wish to add an explanation that the label passes the focus to the target in the "for" attribute.
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/label`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/label/index.html
* Last commit: https://github.com/mdn/content/commit/567daa98535c1ec4c13e4f0111e0c1ce1e4b23b5
* Document last modified: 2021-06-21T10:18:13.000Z

</details>

**Comment by vlwkaos** [comment]
> The form control that the label is labeling is called the labeled control of the label element. One input can be associated with multiple labels.

From the page you provided, I think this answers your first question. But as you suggested, this could be more clear.


> You can click the associated label to focus/activate the input, as well as the input itself. This increased hit area provides an advantage to anyone trying to activate the input, including those using a touch-screen device.

And as per the suggestion, I think there already is a relevant information.

**Comment by sideshowbarker** [comment]
@NeilWix Thanks for raising this, and @vlwkaos thanks for adding the clarifying comments here. I’ve opened #8642 with a fix. After that fix is merged, this issue will automatically be marked as resolved, and closed.
