### ISSUE TITLE
Issue with "Create BookInstance form": Copy code button missing

### ISSUE THREAD

**Issue by nicolascampbell** [mdn/content#8561]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_BookInstance_form

#### What information was incorrect, unhelpful, or incomplete?
Copy code button is missing on pug code. So basically all code sections have this button to easily copy code but pug sections dont.

#### Specific section or headline?
View section

#### What did you expect to see?
A button to easily copy

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_bookinstance_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_BookInstance_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_bookinstance_form/index.html
* Last commit: https://github.com/mdn/content/commit/eb9e13de6a8edf52ea406126c2aef0832db46ff7
* Document last modified: 2021-08-31T06:53:43.000Z

</details>

**Comment by NegiAkash890** [comment]
I am working on this one !

**Comment by hamishwillee** [comment]
@NegiAkash890 _How_ are you planning on fixing this? The copy button is added by the brush type call, but there is no support for a `pug` brush type. We could perhaps "fake" by using html, but this might break something.

In any case, it might we worth holding off as I am working on converting these files to markdown.

**Comment by nicolascampbell** [comment]
Would be nice to have a general language brush type with no syntax highlighting. Anyway then should I close the issue @hamishwillee?

**Comment by hamishwillee** [comment]
OK, fixed by #8671.
It turns out there is a generic brush type @nicolascampbell (brush: plain) :-)
