### ISSUE TITLE
Content bug: Two pages need better explanation for `text/javascript` v. `application/javascript`

### ISSUE THREAD

**Issue by danielparks** [mdn/content#8566]
There are two pages ([one](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Configuring_server_MIME_types), [two](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types)) that list `text/javascript` as the canonical MIME type for JavaScript but don’t have links to support that. There is a [third page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) that’s great; you should copy that one.

Previous issues: https://github.com/mdn/content/issues/4077, https://github.com/mdn/content/issues/4078

### https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript

Specifies that `text/javascript` is the officially correct type and that `charset` should not be used in some cases (see below).

Only links to the [MIME Sniffing living standard](https://mimesniff.spec.whatwg.org/), which does not specify a canonical MIME type for JavaScript (note that it links to the general page for the standard rather than the [specific part that relates to JavaScript](https://mimesniff.spec.whatwg.org/#javascript-mime-type)).

### https://developer.mozilla.org/en-US/docs/Learn/Server-side/Configuring_server_MIME_types#javascript_legacy_mime_types

Specifies that `text/javascript` is the officially correct type, but only links to the above page as a source.

Note that the very next link, under “How to determine the MIME type to set” is https://www.iana.org/assignments/media-types/index.html, which says the correct type is `application/javascript`, presumably because the IETF hasn’t fully approved [a new RFC](https://datatracker.ietf.org/doc/draft-ietf-dispatch-javascript-mjs/) to officially replace RFC4329.

### https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

This is great. It has a short, well sourced explanation:

> (Specifications: [HTML](https://html.spec.whatwg.org/multipage/#scriptingLanguages) and its [reasoning](https://html.spec.whatwg.org/multipage/#dependencies:willful-violation), and [IETF](https://datatracker.ietf.org/doc/draft-ietf-dispatch-javascript-mjs/))

## What did you expect to see?

Each page should link to the [WHATWG HTML spec](https://html.spec.whatwg.org/multipage/#scriptingLanguages) and probably also [the explanation](https://html.spec.whatwg.org/multipage/#dependencies:willful-violation). Linking to the [IETF Internet Draft](https://datatracker.ietf.org/doc/draft-ietf-dispatch-javascript-mjs/) might be good, too.

## Note about `charset`

From the bottom of https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript:

> Some content you find may have a `charset` parameter at the end of the `text/javascript` `media` type, to specify the character set used to represent the code's content. This is not valid, and in most cases will result in a script not being loaded.

I think this is misleading. It appears to be valid, but ignored.

The [WHATWG spec](https://html.spec.whatwg.org/multipage/scripting.html#prepare-a-script) seems to say that the charset should be determined by the `charset` attribute on the `script` tag (**not** a charset parameter on the `script` tag `type` attribute) falling back to the charset of the document the `script` tag exists in. If this is how browsers actually handle it (I have not tested), then the `charset` attribute returned as part of the `Content-Type` header for a `text/javascript` document is ignored, but will **not** cause the the script not to be loaded.

The [IETF Internet Draft](https://datatracker.ietf.org/doc/draft-ietf-dispatch-javascript-mjs/) says to check the byte order mark first, then look at the `charset` of the `Content-Type` header, then assume `UTF-8`.

I suspect that the IETF is declaring how they think it should work, while the WHATWG is documenting actual browser behavior.

Perhaps this was meant to be about the use of the `charset` parameter within the `type` attribute of a `script` tag?

## Mild irony

The MDN site serves JavaScript with `Content-Type: application/javascript; charset=utf-8`.

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/18351, and IANA registry is also updated
