### ISSUE TITLE
Issue with "Debugging (before Firefox 50)": Embedded Youtube Videos are Unavailable 

### ISSUE THREAD

**Issue by digi-booster** [mdn/content#8570]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging_(before_Firefox_50)

#### What information was incorrect, unhelpful, or incomplete?
The embedded Youtube videos are now private, so the video is showing the message of the unavailable video.

#### What did you expect to see?
Tutorial Videos

#### Did you test this? If so, how?
Yes, right-click on that video, then copy the link and then open it in a new tab.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/debugging_(before_firefox_50)`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging_(before_Firefox_50)
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/debugging_(before_firefox_50)/index.html
* Last commit: https://github.com/mdn/content/commit/cb257575007c0d4273a9c55b984387f27a1e9a41
* Document last modified: 2021-07-15T13:27:06.000Z

</details>

**Comment by digi-booster** [comment]
It has only two situations-
1. remove the embedded youtube videos,
2. Or, re-make video and upload on youtube and embed on-page and forget about your YT channel :-)

**Comment by wbamberg** [comment]
Thanks for filing! This has already been reported: https://github.com/mdn/content/issues/7457
