### ISSUE TITLE
Content bug: Unable to reproduce NOT_SUPPORTED_ERR stated on the HTMLMediaElement defaultPlaybackRate page

### ISSUE THREAD

**Issue by greg-el** [mdn/content#8578]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/defaultPlaybackRate#value

## What is the problem?

The docs state that setting the value to 0.0 will produce `NOT_SUPPORTED_ERR`, however, I am not able to recreate this in any browser.

## Did you test this? If so, how?
As an example:
```
Firefox
Version 	91.0.2
Build ID 	20210823123856

> var v = document.createElement("video");
> v.defaultPlaybackRate = 0.0;
0
```
Results are the same in Chrome, Opera, Safari, Edge and IE

**Comment by hamishwillee** [comment]
I think you're right thanks. I've clarified in #8579
