### ISSUE TITLE
Issue: beastify example in webextensions canot run in google chomre

### ISSUE THREAD

**Issue by woojamwtj** [mdn/content#8582]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_second_WebExtension

#### What information was incorrect, unhelpful, or incomplete?
I run this example in chrome ,when i click popup menu ,it fails to change to some animal like snake or turtle

**Comment by rebloor** [comment]
@woojamwtj This is expected behavior. The example uses the `browser` namespace and returns a promise from `tabs.executeScript`.  See [Chrome incompatibilities](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities), for more information.
