### ISSUE TITLE
Issue with "HTTP": (short summary here please)

### ISSUE THREAD

**Issue by badbitch94** [mdn/content#8585]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/index.md
* Last commit: https://github.com/mdn/content/commit/df265b5f36a00589ee99acd5308858a8a1b3fb28
* Document last modified: 2021-08-13T16:17:49.000Z

</details>

**Comment by hamishwillee** [comment]
Closing as not information about any problem provided
