### ISSUE TITLE
Incomplete or No Cache-control Header Set

### ISSUE THREAD

**Issue by naveen1430** [mdn/content#8596]
Details of Vulnerability The cache-control header has not been set properly or is missing, allowing the browser and proxies to cache content.

**Comment by sideshowbarker** [comment]
This doesn’t look like report about a problem in any MDN articles, so I’m going ahead and closing this.

This can be revisited if you add a comment suggesting an update to a particular MDN article, by citing the article URL, and being specific about what part of that article needs updating.
