### ISSUE TITLE
Issue with "WebAssembly.Memory() constructor": No "shared" field in the spec

### ISSUE THREAD

**Issue by saschanaz** [mdn/content#860]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/Memory

#### What information was incorrect, unhelpful, or incomplete?

The document describes `shared` dictionary field but it's not in the spec

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/Memory#Syntax

#### What did you expect to see?

A note about why it's not in spec, or just delete it.

#### Did you test this? If so, how?

[SpiderMonkey seems to support it](https://searchfox.org/mozilla-central/rev/8e8a8fc213d77689d625851b19249013064c1bb3/js/src/wasm/WasmJS.cpp#989), didn't check Blink.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/webassembly/memory/memory`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/Memory
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/webassembly/memory/memory/index.html
* Report started: 2021-01-02T17:53:51.032Z

</details>

**Comment by Elchi3** [comment]
This is the spec: https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md#javascript-api-changes

**Comment by saschanaz** [comment]
Cool, then the work item would be to add it to the spec table.

**Comment by himanshugarg** [comment]
As I see it, the file [SpecData.json](https://github.com/mdn/yari/blob/main/kumascript/macros/SpecData.json) needs a new entry. The [spec link shared by Elchi3](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md#javascript-api-changes) is specific to WebAssembly threads and the current more generic:-

```javascript
 "WebAssembly JS": {
    "name": "WebAssembly JavaScript Interface",
    "url": "https://webassembly.github.io/spec/js-api/",
    "status": "WD"
  }
```
I am hoping that adding the following would fix it but I don't know what the `name` and `status` values should be to get the Specifications macro use this instead for this particular page
```javascript
 "?": {
    "name": "?",
    "url": "https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md#javascript-api-changes",
    "status": "?"
  }
```
