### ISSUE TITLE
Issue with "Game development": broken link

### ISSUE THREAD

**Issue by digi-booster** [mdn/content#8602]
MDN URL: https://developer.mozilla.org/en-US/docs/Games

#### What information was incorrect, unhelpful, or incomplete?

broken link in GameSidebar
#### Specific section or headline?
Related Topics > APIs for game development > fullscreen

#### What did you expect to see?
https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/User_notifications/Full_screen_api -> https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/games`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/index.html
* Last commit: https://github.com/mdn/content/commit/5fb569eddc18081727c03bb97cdb4c67f084804c
* Document last modified: 2021-04-24T03:00:55.000Z

</details>

**Comment by teoli2003** [comment]
Thanks. I opened a PR in yari to get this fixed.
