### ISSUE TITLE
Issue with "Using Fetch": (short summary here please)

### ISSUE THREAD

**Issue by givanov95** [mdn/content#8603]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

#### What information was incorrect, unhelpful, or incomplete?
In section "Uploading multiple files" the loop rewrites FormData.append with 'photos'.  :
for (let i = 0; i < photos.files.length; i++) {
  formData.append('photos', photos.files[i]);
}

It's ok if i try with: 

for (let i = 0; i < photos.files.length; i++) {
  formData.append(**i**, photos.files[i]);
}

#### Specific section or headline?
Uploading multiple files

#### What did you expect to see?
Separated array elements with $_FILES variable in PHP

#### Did you test this? If so, how?
Sending POST query to php file, and get the query via golbal $_FILES variable.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/fetch_api/using_fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/fetch_api/using_fetch/index.html
* Last commit: https://github.com/mdn/content/commit/2e2631aa9d11718154ca50c2c3cc82074ab34ccd
* Document last modified: 2021-08-31T15:21:54.000Z

</details>

**Comment by wenh08** [comment]
what language is this code?
