### ISSUE TITLE
[Web API] Implement self.reportError

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#8608]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

`WindowOrWorkerGlobalScope.reportError()` (`WindowOrWorkerGlobalScope` is being changed to self however this is outside the scope of this bug) see https://html.spec.whatwg.org/#runtime-script-errors

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1722448

**Comment by rachelandrew** [comment]
This is also landing in Chromium 95.

**Comment by hamishwillee** [comment]
Status
- [ ]  BCD 
  - was added in https://github.com/mdn/browser-compat-data/pull/12531 - see [api/_globals/reportError.json](https://github.com/mdn/browser-compat-data/blob/main/api/_globals/reportError.json)
  - will need update to include MDN URL.
- [ ] Docs
- [ ] Release note
- [ ] dev-docs-complete

**Comment by hamishwillee** [comment]
@Rumyra This is essentially done. 

Note I removed the interactive example from the page. It is in no way vital - but if I ever get an answer to https://github.com/mdn/interactive-examples/issues/1919 I might add it in.

The page also still doesn't display the BCD. I think it is perhaps just that BCD doesn't publish the data yet. The key matches what was done for `fetch()`
