### ISSUE TITLE
[Web EXT] extension.getView doesn't contain sidebars

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#8612]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Addition to rel notes and bcd updates - seems work is already being done or done https://bugzilla.mozilla.org/show_bug.cgi?id=1612390#c6

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1612390

## Other

@rebloor I've noticed you've already done work on this, so I'll pass this to you to update here if there's anything else needed 👍

**Comment by rebloor** [comment]
@Rumyra I included release notes in #8399, is there something else that needs doing?

**Comment by Rumyra** [comment]
If the docs and browser compat are up to date then no - feel free to check off the Acceptance Criteria list at the top if that helps 👍

**Comment by rebloor** [comment]
Thanks @Rumyra , all the items on the acceptance criteria list are done.
