### ISSUE TITLE
[Event] onsecurypolicyviolation event handler

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#8614]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

`onsecuritypolicyviolation` event handler needs documenting - see https://html.spec.whatwg.org/#event-securitypolicyviolation

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1727302

**Comment by hamishwillee** [comment]
Status

- [ ] BCD - https://github.com/mdn/browser-compat-data/pull/12289

**Comment by Rumyra** [comment]
As bcd is non-blocking I'll close just for tidying sake - thanks so much @hamishwillee
