### ISSUE TITLE
Issue with "Common MIME types": "MP4 audio" instead of "MP4 video"

### ISSUE THREAD

**Issue by avi12** [mdn/content#8615]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

#### What information was incorrect, unhelpful, or incomplete?
The table contains:

.mp4 | MP4 audio | video/mp4
-- | -- | --

#### What did you expect to see?

.mp4 | MP4 video | video/mp4
-- | -- | --

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/basics_of_http/mime_types/common_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/mime_types/common_types/index.md
* Last commit: https://github.com/mdn/content/commit/b67c8a2128ca23d7cd448cc120bf3c45601181b0
* Document last modified: 2021-08-13T16:17:49.000Z

</details>

**Comment by teoli2003** [comment]
Thanks, I opened a PR to fix it.
