### ISSUE TITLE
[Web API] ElementInternals.shadowRoot 

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#8616]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Looks to be documented, but an update to BCD needed

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1723521

**Comment by rachelandrew** [comment]
Checked that we have docs, which we do, so just updating support data.

**Comment by Rumyra** [comment]
Thanks @rachelandrew
