### ISSUE TITLE
[JS] Intl.Enumeration needs documenting

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#8618]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Looks like we don't have this yet, so the API needs documenting. Spec is here: https://github.com/tc39/proposal-intl-enumeration

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1670033

**Comment by hamishwillee** [comment]
Status

- [ ] Interactive example: https://github.com/mdn/interactive-examples/pull/1912
- [ ] BCD
- [ ] Docs
- [ ] Release note
- [ ] dev-doc-complete
- [ ] ?
