### ISSUE TITLE
[Event] KeyboardEvent.initKeyEvent to return undefined

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#8623]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated - NA
- [x] Interactive example and data repos are updated if appropriate - NA
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Seems like a removal of functionality. Some investigation should be done, but it's not part of spec and maybe consider removing the MDN page

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1717760

**Comment by hamishwillee** [comment]
The method [KeyboardEvent.initKeyEvent()](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/initKeyEvent) is being hidden behind the preference `dom.keyboardevent.init_key_event.enabled` in FF93. It is planned for removal in FF96 if no one screams. 

What I have done is added info about the preference and an even stronger warning in https://github.com/mdn/content/pull/8793

@Rumyra I suggest maybe the only other thing we need to do is add a release note - right?

Note, I didn't just delete the page, though it wouldn't have done much harm. I figure that we can wait until the removal actually happens.

**Comment by Rumyra** [comment]
Brilliant - thanks @hamishwillee
