### ISSUE TITLE
[Event] Add onslotchange event handler

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#8624]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Check `onslotchange` event is documented

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1501983

**Comment by hamishwillee** [comment]
Review
- [HTMLSlotElement : slotchange_event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event) documented. Example shows `addEventListener` called on slto.
- [HTMLSlotElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement#examples) has an example showing use of Shadowroot

This adds the `onslotchange` global event handler. I think the job is as simple as adding the handler below [GlobalEventHandlers](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers) and updating the links in the two documents above. Maybe also update the https://github.com/mdn/web-components-examples/blob/master/slotchange/main.js to use this.

**Comment by hamishwillee** [comment]
Status
- [ ] BCD
- [ ] Release notes: #8785
- [ ] Docs - Add `GlobalEventHandlers.onslotchange` - #8790
- [ ] Update example - Decided not to do it (no actual benefit)
- [ ] dev-doc-complete
