### ISSUE TITLE
Issue with "<input type="datetime-local">": timezone picker

### ISSUE THREAD

**Issue by evert** [mdn/content#8631]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

#### What information was incorrect, unhelpful, or incomplete?

The page contains this snippet:

```html
<select name="timezone_offset" id="timezone-offset" class="span5">
    <option value="-12:00">(GMT -12:00) Eniwetok, Kwajalein</option>
    <option value="-11:00">(GMT -11:00) Midway Island, Samoa</option>
    <option value="-10:00">(GMT -10:00) Hawaii</option>
    <option value="-09:50">(GMT -9:30) Taiohae</option>
    <option value="-09:00">(GMT -9:00) Alaska</option>
    <option value="-08:00">(GMT -8:00) Pacific Time (US &amp; Canada)</option>

  ...

</select>
```

The use of offsets should probably be discouraged. They are incorrect for half the year where in places that have DST, and given that many countries change their timezone rules every year, it can create inaccuracies given that the original location is lost.

It's highly recommended to just use the olson strings, e.g.: `Europe/Amsterdam`, `America/Toronto` for at least the `value` field.

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#setting_timezones

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/datetime-local`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/datetime-local/index.html
* Last commit: https://github.com/mdn/content/commit/8e6fa5b7e581b7a941d49eae4e0960573c300deb
* Document last modified: 2021-08-04T14:54:47.000Z

</details>

**Comment by sideshowbarker** [comment]
100% agreed — thanks for raising this. I’ve opened #8635 with a fix.
