### ISSUE TITLE
List of External Broken Link

### ISSUE THREAD

**Issue by digi-booster** [mdn/content#8645]
|Broken Link|Link Text|Page Where Link Found|Error|
|--- |--- |--- |--- |
|https://cors-image-example.glitch.me/|try out|<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image#:~:text=You%20can-,try%20out,-or">Allowing cross-origin use of images and canvas</a>|404|
|http://mxr.mozilla.org/mozilla-central/source/security/manager/ssl/src/nsKeygenHandler.cpp?mark=179-185,187-206,208-227,229-256|nsKeygenHandler.cpp|<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/keygen#:~:text=the%20table%20in-,nsKeygenHandler.cpp,-.%20(Note%20that%20only">&lt;keygen&gt;</a>|Bad Host DNS_PROBE_FINISHED_NXDOMAIN|
|http://roots.io/using-less-source-maps/|1.5.0 version of Less|<a href="https://developer.mozilla.org/en-US/docs/Tools/Style_Editor#:~:text=1.5.0%20version%20of%20Less">Style Editor</a>|404|
|https://www.gimp.org/docs/plug-in/appendix-alpha.html|alpha-premultiplied sRGBA color space|<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#:~:text=alpha-premultiplied%20sRGBA%20color%20space">&lt;color&gt;</a>|404|
|https://addons.mozilla.org/en-US/firefox/addon/7434|Extension Developer's Extension|<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Shells#:~:text=Extension%20Developer%27s%20Extension">JavaScript shells</a>|404|
|https://www.html5rocks.com/temporary/|http://www.html5rocks.com/temporary/|<a href="https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntrySync#:~:text=http%3A//www.html5rocks.com/temporary">FileSystemEntrySync</a>|404|
|http://www.webperformancetoday.com/2012/04/02/latency-101-what-is-latency-and-why-is-it-such-a-big-deal/|latency|<a href="https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Author_fast-loading_HTML_pages#:~:text=user%2C%20thereby%20reducing-,latency,-.">Tips for authoring fast-loading HTML pages</a>|500|
|http://archivist.incutio.com/viewlist/css-discuss/2685|Eric Meyer's note about the Working Group's stance|<a href="https://developer.mozilla.org/en-US/docs/Learn/CSS/Howto/CSS_FAQ#:~:text=Eric%20Meyer%27s%20note%20about%20the%20Working%20Group%27s%20stance">CSS FAQ</a>|Bad Host DNS_PROBE_FINISHED_NXDOMAIN|

**Comment by hamishwillee** [comment]
Thanks @digi-booster ! Better to post these as bugs against the individual pages because the people who are likely to be expert in each area are different.

I can't do much with most of them. But FYI https://www.html5rocks.com/ redirects to https://developers.google.com/web and following the path to the URL from here, https://developers.google.com/web/updates/2011/08/Debugging-the-Filesystem-API takes you to https://web.dev/read-files/#toc-filesystemurls

**Comment by digi-booster** [comment]
> Thanks @digi-booster ! Better to post these as bugs against the individual pages because the people who are likely to be expert in each area are different.
> 
> I can't do much with most of them. But FYI https://www.html5rocks.com/ redirects to https://developers.google.com/web and following the path to the URL from here, https://developers.google.com/web/updates/2011/08/Debugging-the-Filesystem-API takes you to https://web.dev/read-files/#toc-filesystemurls

I will take care of it next time, next time I will report issues on individual pages, for now, can I replace the URL with their page title, maybe it will be useful for people, as the problems are fixed I will <del>del</del> or <s>s</s> a row from the table.

**Comment by hamishwillee** [comment]
That would be great. They are genuine problem. Thanks.
