### ISSUE TITLE
Issue with "Introduction": Images in tutorial are not SVGs

### ISSUE THREAD

**Issue by AndreasChristianson** [mdn/content#8652]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Introduction

#### What information was incorrect, unhelpful, or incomplete?

> SVG is an XML language, similar to XHTML, which can be used to draw vector graphics, such as the ones shown to the right.

The image to the right is a png, a raster graphics format. 

#### Specific section or headline?

Introduction

#### What did you expect to see?

The SVG tutorial should contain examples of fully fleshed out SVGs, not raster screenshots of them.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/tutorial/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/tutorial/introduction/index.html
* Last commit: https://github.com/mdn/content/commit/4a810357cb7f1a75de023c65fc0c83a884bd2b08
* Document last modified: 2021-03-25T00:07:10.000Z

</details>

**Comment by angelayanpan** [comment]
It seems like this was closed by mistake?
