### ISSUE TITLE
Issue with "word-spacing": percentages no longer allowed

### ISSUE THREAD

**Issue by ylafon** [mdn/content#8653]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/word-spacing

#### What information was incorrect, unhelpful, or incomplete?

Formal syntax is as follow:
`normal | <length-percentage>
where 
<length-percentage> = <length> | <percentage>`

but the definition in the [css-text](https://drafts.csswg.org/css-text/#word-spacing-property) is now
`Value: | normal \| <length>`

#### Specific section or headline?

Formal syntax, but all reference to percentages should be removed.

#### What did you expect to see?

See above.

#### Did you test this? If so, how?

cf. spec.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/word-spacing`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/word-spacing
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/word-spacing/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by sideshowbarker** [comment]
Opened https://github.com/mdn/data/pull/505 with a fix
