### ISSUE TITLE
Issue with "How to make PWAs installable": Incorrect information

### ISSUE THREAD

**Issue by stijnhommes** [mdn/content#8654]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

#### What information was incorrect, unhelpful, or incomplete?
All the information on the page was incorrect and unhelpful.
Apps belong in the app drawer. NOT on the home screen.
But that is really irrelevant, because a PWA is a misnomer and allows you to fake install a website, NOT an app.

#### Specific section or headline?
Not applicable.

#### What did you expect to see?
An empty page. 
We need the ability to remove the install button in the omnibox and install item in the menu of the browser.
We need the ability to recognize PWAs on mobile app stores, so they can be avoided.
Yet you refuse to post actually useful content or make it possible.

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/progressive_web_apps/installable_pwas`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/installable_pwas/index.html
* Last commit: https://github.com/mdn/content/commit/ece4d88d33c92bebcf8089a62997b3e810b9c04b
* Document last modified: 2021-02-24T02:42:32.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this. Their are no plans to delete that page, and beyond that I don’t see any other suggestions that could be acted on, so I’m going ahead and closing this.

**Comment by stijnhommes** [comment]
Good evening,

So you'd rather leave incorrect information instead of solving the issue.
That makes it crystal clear where your priorities lie.

If you continue to close raised issues without actually solving them, I
guess I'll have to report you for spreading misinformation and not dealing
with security issues in a timely manner.

Regards and thanks for nothing.
