### ISSUE TITLE
Issue with "Array.prototype.copyWithin()": Typo on line 9 in the interactive example

### ISSUE THREAD

**Issue by Reeshul** [mdn/content#8659]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin

#### What information was incorrect, unhelpful, or incomplete?

Typo in line 9 in the iframe at the top. 

Should be 

```
// expected output: Array ["a", "d", "e", "d", "e"]
```

instead of 

```
// expected output: Array ["d", "d", "e", "d", "e"]
```

#### Specific section or headline?

The iframe at the top of the page which comes from https://interactive-examples.mdn.mozilla.net/pages/js/array-copywithin.html

#### What did you expect to see?

```
const array1 = ['a', 'b', 'c', 'd', 'e'];

// copy to index 0 the element at index 3
console.log(array1.copyWithin(0, 3, 4));
// expected output: Array ["d", "b", "c", "d", "e"]

// copy to index 1 all elements from index 3 to the end
console.log(array1.copyWithin(1, 3));
// expected output: Array ["a", "d", "e", "d", "e"]
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/copywithin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/copywithin/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks @Reeshul  . When I run the code I see that the output matches the comment. Am I missing something here:-
![image](https://user-images.githubusercontent.com/2392803/132129290-302dce3f-9951-40e0-976a-7de367475a20.png)

**Comment by AnilSeervi** [comment]
The method is modifying the variable so the second time you are using `copyWithin` method it is actually copying within the previously modified array.
