### ISSUE TITLE
/ru/docs/Learn/What_is_a_web_server could not be found.

### ISSUE THREAD

**Issue by RSKOne** [mdn/content#8662]

**Comment by RSKOne** [comment]
Couldn't go from https://developer.mozilla.org/ru/docs/Learn/Common_questions/Pages_sites_servers_and_search_engines 
to page
https://developer.mozilla.org/ru/docs/Learn/What_is_a_web_server

But if go to English version of this page and then switch the language to Russian then everything works.

**Comment by himanshugarg** [comment]
See https://github.com/mdn/content/issues/8387#issuecomment-907963824

**Comment by sideshowbarker** [comment]
https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ documents the MDN course of action with regard to translations, which is that the set of locales for which changes can be made is the following:

* Simplified Chinese (zh-CN)
* Traditional Chinese (zh-TW)
* French (fr)
* Japanese (ja)

All locales other than those are frozen unless/until someone submits a proposal for maintaining them going forward, “including evidence of an active team willing to be responsible for the work associated with that locale”.

If/when someone comes forward with such a proposal and evidence, we can revisit this issue.
