### ISSUE TITLE
Content bug: Explanation for `Cache-Control: no-store, max-age=0`

### ISSUE THREAD

**Issue by Jxck** [mdn/content#8668]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#preventing_caching

## Specific page section or heading?

> Note: The no-store directive will prevent a new resource being cached, but it will not prevent the cache from responding with a non-stale resource that was cached as the result of an earlier request. Setting max-age=0 as well forces the cache to revalidate (clears the cache).
> `Cache-Control: no-store, max-age=0`

## What is the problem?

Is the line below really true ?

> Setting max-age=0 as well forces the cache to revalidate (clears the cache).

IIUC, `no-store` doesn't stored in any cache storage according to [spec](https://httpwg.org/http-core/draft-ietf-httpbis-cache-latest.html#cache-response-directive.no-store).

So any directive combined with `no-store` doesn't affect any cache storage. I don't know why `max-age=0` could clear the cache in previously stored response with `no-store`.

## What did you expect to see?

If it's mentioned in the spec (which I couldn't find), it should be mentioned explicitly.
or if major implementation behave like it, it can also be linked as source.

otherwise, delete this Notes and leave it only

```http
Cache-Control: no-store
```

## Did you test this? If so, how?

I wanna ask how to test it who wrote this section.

**Comment by hamishwillee** [comment]
Yes. Untested, but this is what the spec says/implies.

The spec says 

> The "no-store" response directive indicates that a cache must not store any part of either the **immediate** request or response ...

That says that the **current** request will not be cached. It does not say that existing cache records will be cleared. Therefore if you just call `no-store` it is valid for a cache to return a value that it had previously cached. 

So if you really want to clear the cache you need to do something extra.

**Comment by Jxck** [comment]
@hamishwillee Thanks for comments.

I also find same thing in `no-store` section too.

> Clients can set max-age=0 to also clear existing cache responses, as this forces the cache to revalidate with the server (no other directives have an effect when used with no-store).

If everyone agree with removing this line, I can send PR for here.

**Comment by hamishwillee** [comment]
@Jxck I do not agree with removing the line. If you don't have that line then a reader might assume that `no-store` clears pre-existing cache entries.

Perhaps @teoli2003 might take a different view, or I misunderstand your point. It would not be the first time I was wrong :-0

**Comment by Jxck** [comment]
IIUC, **there are no way to clear exisitng cache with response c-c header directive**.
That's why `Clear-Site-Data` standardized on the other hand.
So if these explanation added while MDN are wiki, it should be review again now. (I'd love to help it, even if rewriting cache-control section)
But if I misuderstood here, welcome to pint me out by anyone.

**Comment by hamishwillee** [comment]
> IIUC, there are no way to clear existing cache with response c-c header directive.

Just to be very clear, the docs say that
-  you use  `Cache-Control: no-store` to ensure that the immediate response is not cached
-  you use  `Cache-Control: no-store, max-age=0` to ensure that the immediate response is not cached and clear any existing cache (though possibly this might set that future requests are invalidated).

What I think you are saying is that `Cache-Control: no-store, max-age=0` does not work to clear cache hits that have already been stored. Is that correct? 

Have you verified this/why do you think it is so? I'm not saying you're wrong - just trying to confirm why you think this. I can imagine perhaps setting `no-store` means that the `max-age` never gets added to the cache record. 

As an aside, `Clear-Site-Data` appears to only affect user-agent caches, while `Cache-Control` is targeted for more general caching. I'm sure you know that (my point just being that it is a different discussion). 

If you think you can rewrite the Cache Control docs better we'd welcome a PR. It is an incredibly important section. I would not be qualified to review such a change in-depth :-)

**Comment by Jxck** [comment]
@hamishwillee 

> What I think you are saying is that Cache-Control: no-store, max-age=0 does not work to clear cache hits that have already been stored. Is that correct?

Yes.
`max-age=0` is directive affects for stored response it contains. so if it stored to the cache storage, it will override existing cache and will revalidate always, so it can say "clear existing cache".
https://httpwg.org/http-core/draft-ietf-httpbis-cache-latest.html#validation.model

but `no-store` permits storing it response from any cache storage. So I think it doesn't works for cache cleaner.
https://httpwg.org/http-core/draft-ietf-httpbis-cache-latest.html#cache-response-directive.no-store

If I mis-understanding it, please correct me.

**Comment by hamishwillee** [comment]
@Jxck I can't correct you, because I don't understand your response above. Let me get some fresh eyes.

@sideshowbarker @teoli2003 Can you please help me out/advise here? [or suggest someone else good to ask for a caching query?]

Specifically, MDN docs say:
-  A server can use  `Cache-Control: no-store` to ensure that the immediate response is not cached.
-  _But this will not clear a pre-existing cache entry_, so it is possible for a client to get an old record even if you use that directive.
-  You use  `Cache-Control: no-store, max-age=0` to ensure that the immediate response is not cached and clear any existing cache (though possibly this might set that future requests are invalidated).

@Jxck is suggesting that this last point is wrong. The `Cache-Control: no-store, max-age=0` will not result in clearing the existing cache record. 

1. I am willing to accept this might be true and even that perhaps it is more _likely_ than the current statement, but I don't know how to verify it. Any ideas?
2. What then would be the recommended way to make sure the response is not stored and intermediate cache is cleared?

**Comment by sideshowbarker** [comment]
> @Jxck is suggesting that this last point is wrong. The `Cache-Control: no-store, max-age=0` will not result in clearing the existing cache record.

Paging in @mnot for guidance

**Comment by Jxck** [comment]
Thanks @mnot for helping here

> What then would be the recommended way to make sure the response is not stored and intermediate cache is cleared?

1. if you don't responed very first response
use `no-store` for here, and `private` would be fine too only for shared cache.

2. if you already responed very first response with `max-age`
there are no way to *remove* already stored response from shared cache via `cache-control` field.
workaround is override cache with `no-cache` and force client to revalidate before reusing cache.
`clear-site-data` can be alternative, but it clears every cache on site so it's basically overkill.

I wonder if spec has `cache-control: remove` for removing already stored response for each key in storage can be cover this case.

**Comment by Jxck** [comment]
I'm working on PR for here.

**Comment by hamishwillee** [comment]
Thanks guys - really appreciate your patience and persistence. 

@Jxck How are you going with that PR? I'm happy to take first shot at this if you haven't got around to it yet?

**Comment by Jxck** [comment]
I'm working on it, and push it this weekend.
