### ISSUE TITLE
Issue with "Browser detection using the user agent": (short summary here please)

### ISSUE THREAD

**Issue by lozzy1964** [mdn/content#8679]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/browser_detection_using_the_user_agent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/browser_detection_using_the_user_agent/index.md
* Last commit: https://github.com/mdn/content/commit/94924d6f875bd90c1b719c38ab5e25fb47ca5f74
* Document last modified: 2021-08-28T20:44:16.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks @lozzy1964 . In your report, could you please mention the issue you found on the page and the changes you'd like to see?
