### ISSUE TITLE
Issue with "CanvasRenderingContext2D.createPattern()": need to mention that it can return null

### ISSUE THREAD

**Issue by smmilut** [mdn/content#8684]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createPattern

#### What information was incorrect, unhelpful, or incomplete?

The "Return value" is not always a `CanvasPattern`.

In the special case where the source `image` is not fully loaded (`image.complete` is `false`), then `CanvasRenderingContext2D.createPattern()` returns `null`.

#### Specific section or headline?

In page "Web technology for developers > Web APIs > CanvasRenderingContext2D > CanvasRenderingContext2D.createPattern()", at section "Syntax > Return value".

#### What did you expect to see?

I expect to see both :
 - the return value for the expected case : returning a `CanvasPattern`. This is now correctly documented.
 - as well as the return value for the edge case : returning `null` when the image is not complete. This is missing from the documentation.

Knowing this could help with handling that special case.

#### Did you test this? If so, how?

I had a bug when my program used `CanvasRenderingContext2D.createPattern(img, "repeat-x")` on an image element `img` that was not always fully loaded depending on timing. When it happened, the return value was `null` and that was unexpected for me when I relied on this documentation.

I tested it in two browsers :
- Firefox 91.0.2 (64-bit) on Linux (official package for Arch Linux)
- Chromium Version 93.0.4577.63 (Official Build) Arch Linux (64-bit)

I fixed it by using the correct form described further down in the same page under section "Examples > Javascript" where an image is only used after its `load` event.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/createpattern`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createPattern
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/createpattern/index.html
* Last commit: https://github.com/mdn/content/commit/dfd3bb751da1f424ba5091cbcb9130293bd0b5d1
* Document last modified: 2021-09-02T01:36:33.000Z

</details>

**Comment by bsmth** [comment]
Hi @smmilut thanks a lot for reporting this one. Would you like to open a pull request with your suggested changes?

**Comment by smmilut** [comment]
Hi @bsmth , thanks for the suggestion, it motivated me to contribute for the first time :)
I tried to follow guidelines and make the modification concise. I hope I didn't make any Markdown style mistake because I was unable to test my change (having only made the change from the GitHub web interface).
I'll try to stay available if further collaboration is needed.

**Comment by bsmth** [comment]
> it motivated me to contribute for the first time

That's great, well done on the first contribution 🎉
