### ISSUE TITLE
Issue with "Making PWAs work offline with Service workers": Promises not returned in example code

### ISSUE THREAD

**Issue by forevermatt** [mdn/content#8695]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers

#### What information was incorrect, unhelpful, or incomplete?
It looks like the code example for clearing the cache is missing a `return` or two.

#### Specific section or headline?
Clearing the cache

#### What did you expect to see?
When the `map()` call inside `Promise.all()` executes, it seems like it should return the promise(s) created by any calls to `caches.delete()`, but it doesn't do so.

It also seems like the Promise returned by `Promise.all()` should be returned, but I'm not certain about that.

#### Did you test this? If so, how?
Yes, by modifying the example from this...
```
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keyList) => {
    Promise.all(keyList.map((key) => {
      if (key === cacheName) { return; }
      caches.delete(key);
    }))
  }));
});
```
... to this...
```
self.addEventListener('activate', (e) => {
    console.log('activate', e) // TEMP
    e.waitUntil(caches.keys().then((keyList) => {
        const promises = keyList.map((key) => {
            if (key === cacheName) { return; }
            console.log('Deleting old cache', key) // TEMP
            caches.delete(key);
        })
        console.log('promises', promises) // TEMP
        return Promise.all(promises)
    }));
});
```
... and seeing this in the console output:
```
[Service Worker] Install
[Service Worker] Caching all: app shell and content
activate [object ExtendableEvent]
Deleting old cache example-cache-name-v2
promises 
Array [ undefined, undefined ]
```

Once I changed `caches.delete(key);` to `return caches.delete(key);`, the output was this (after several tries):
```
[Service Worker] Install
[Service Worker] Caching all: app shell and content
activate [object ExtendableEvent]
Deleting old cache example-cache-name-v5
promises 
Array [ "[object Promise]", undefined ]
```

I don't know the full effects of not returning those promises, but it looks like the intent was that the return values would be Promises, not undefined (when there was a promise).

I'll be glad to submit a PR to fix it, but wanted to check that it was desired (and would be correct) before doing so.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/progressive_web_apps/offline_service_workers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/progressive_web_apps/offline_service_workers/index.html
* Last commit: https://github.com/mdn/content/commit/e9e1a522fe5850379d89fe043b8a3116e94ed0c5
* Document last modified: 2021-08-19T06:58:03.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks @forevermatt . You could submit a PR and let the reviewer confirm. [This ](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/keys) page has the same code but with the `return`s.
