### ISSUE TITLE
Issue with "Intersection Observer API": ( explanation not complete under "Intersection observer concepts and usage")

### ISSUE THREAD

**Issue by angelayanpan** [mdn/content#8696]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

#### What information was incorrect, unhelpful, or incomplete?

> Typically, you'll want to watch for intersection changes with regard to the element's closest scrollable ancestor, or, if the element isn't a descendant of a scrollable element, the viewport. To watch for intersection relative to the root element, specify null.

Reading from the beginning(top of the page), getting to this paragraph: "To watch for intersection relative to the root element, specify null."  

not sure where to specify null. or "null" is for what function? very confusing.  then, continue to read the next 2 paragraphs, still not clear what needs to be set to null. 

#### Specific section or headline?

Intersection observer concepts and usage

#### What did you expect to see?

"To watch for intersection relative to the root element, specify null."  "specify null" at where? at this point, no functions are introduced yet. 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/intersection_observer_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/intersection_observer_api/index.html
* Last commit: https://github.com/mdn/content/commit/489893489a3af769c080b0be9ae6253b01e17e6a
* Document last modified: 2021-08-26T04:37:27.000Z

</details>

**Comment by vlwkaos** [comment]
I will try and make an amend. I think a simple code block demonstrating the description should suffice.

**Comment by angelayanpan** [comment]
"Typically, you'll want to watch for intersection changes with regard to the element's closest scrollable ancestor, or, if the element isn't a descendant of a scrollable element, the viewport. To watch for intersection relative to the root element, specify null for root option. Keep reading for more detailed explanation about intersection observer options." 

- does this mean that the "root element" is the "viewport"?  is that the assumption?
-  another thing I noticed is that my Grammarly plugin is trying to correct "for more detailed explanation" to "for **a** more detailed explanation" 
- Before the above-quoted section, the article says "That specified element is called the root element or root for the purposes of the Intersection Observer API."    if I'm understanding this correctly,  any specified element can be called the "root element".  so this sentence is still confusing: "to watch for intersection relative to the root element, specify null for root option."

**Comment by vlwkaos** [comment]
@angelayanpan Thanks for the feedback!
