### ISSUE TITLE
Issue with "Continuous Media": (short summary here please)

### ISSUE THREAD

**Issue by feruzismail14** [mdn/content#8697]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Continuous_Media

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/continuous_media`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Continuous_Media
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/continuous_media/index.html
* Last commit: https://github.com/mdn/content/commit/358a7f5946e91555bf9221841fd60273beb8ee8e
* Document last modified: 2021-08-01T23:15:20.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks @feruzismail14 . In your report, could you please mention the issue you found on the page and the changes you'd like to see?
