### ISSUE TITLE
Issue with "Expressions and operators": …

### ISSUE THREAD

**Issue by toshkv** [mdn/content#870]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators

#### What information was incorrect, unhelpful, or incomplete?
The link bookmarks do not take you to the linked location. Here are the linked items below. The links reference an invalid link. For example, "Assignment operators" links to "#Assignment", but the actual href is "#Assignment_operators".

    Assignment operators
    Comparison operators
    Arithmetic operators
    Bitwise operators
    Logical operators
    String operators
    Conditional (ternary) operator
    Comma operator
    Unary operators
    Relational operators

#### Specific section or headline?
Every linked bookmark category under "Operators".

#### What did you expect to see?
Each linked bookmark should take you to the corresponding Operators category.

#### Did you test this? If so, how?
Clicked the links.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/expressions_and_operators`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/guide/expressions_and_operators/index.html
* Report started: 2021-01-03T01:20:11.338Z

</details>

**Comment by toshkv** [comment]
@chrisdavidmills could you assign this task to me?

**Comment by chrisdavidmills** [comment]
@toshkv done!

**Comment by gnittala** [comment]
@toshkv this is the first time I am looking around to pick items for helping in MDN docs, will you raise this PR or can I take a stab at this one. Seems like the fix required is to update the inline links to add the `_operators` to each of them. Is that right ?

Thank You

**Comment by toshkv** [comment]
I'll raise the PR. Yes, that's correct.

**Comment by sideshowbarker** [comment]
Fixed by eb56bd9 / #1376
