### ISSUE TITLE
Issue with "Paged media": (short summary here please)

### ISSUE THREAD

**Issue by 14JeffMcc** [mdn/content#8700]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Paged_Media

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/paged_media`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Paged_Media
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/paged_media/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks @14JeffMcc . In your report, could you please mention the issue you found on the page and the changes you'd like to see?

---

Something like this https://github.com/mdn/browser-compat-data/issues/12287#issuecomment-913907126 might help here as well.
