### ISSUE TITLE
https://developer.mozilla.org/en-US/Thunderbird/Autoconfiguration

### ISSUE THREAD

**Issue by iBelow** [mdn/content#8720]
https://developer.mozilla.org/en-US/Thunderbird/Autoconfiguration
great, and how i can add Autoconfiguration for mx server?

![image](https://user-images.githubusercontent.com/8112733/132341317-3a6f3a53-45ec-4673-b25b-59ba1f965fb4.png)

**Comment by sideshowbarker** [comment]
https://web.archive.org/web/20200915064942/https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration

**Comment by himanshugarg** [comment]
This page https://support.mozilla.org/en-US/kb/automatic-account-configuration has links to the one reported missing. Fix for this issue would probably require updating that page with content/link in https://github.com/mdn/content/issues/8720#issuecomment-914257452

**Comment by sideshowbarker** [comment]
Closing, as there’s no resolution for this which can be made in the mdn/content sources
