### ISSUE TITLE
Issue with "What will your website look like?": (Font section description needs to be changed in its entirety)

### ISSUE THREAD

**Issue by FlamboyantFeroz** [mdn/content#8723]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/What_will_your_website_look_like

#### What information was incorrect, unhelpful, or incomplete?
The description in "Font" section of this page regarding "Google Fonts" is completely out of date. The entire pic that asks to 'Click the "plus" (Add to) icon next to the font you want' is vague. No such "plus" (Add to) icon appears next to any font on "Google Fonts" website. Description given in other two steps(i.e. step 3 and step 4) is also not applicable to the "Google Fonts" website. This information is proving to be incorrect, unhelpful and incomplete in its entirety. Please someone make appropriate changes to this section.

#### Specific section or headline?
In a "Font" Section, entire description steps and pic need to be changed.

#### What did you expect to see?
I expect to see the appropriate description steps along with the appropriate pic that will guide new users in using "Google Fonts", especially the concept of "Variable Fonts".

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/what_will_your_website_look_like`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/What_will_your_website_look_like
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/what_will_your_website_look_like/index.html
* Last commit: https://github.com/mdn/content/commit/b7c594e7a8e5eb31a70bcf3e07d931e4603d201b
* Document last modified: 2021-09-03T05:34:55.000Z

</details>

**Comment by wbamberg** [comment]
We 100% shouldn't be documenting the UI of external websites on MDN! IMO this section should just tell people that Google Fonts exists, what it can be used for, and how to get there.

**Comment by FlamboyantFeroz** [comment]
> We 100% shouldn't be documenting the UI of external websites on MDN! IMO this section should just tell people that Google Fonts exists, what it can be used for, and how to get there.

I'm not asking for documenting the UI of external website, Google Fonts in this case. I'm only requesting to do the necessary correction to the part which is intended to guide new learners to use Google Fonts. Also the most important thing, the usage of "The Variable Fonts" in order to create custom styles is completely missing from the current description. I'm not requesting only for changing the description just for the sake of UI. I'm requesting to correct the description in order to make it easier for new learners to use Google Fonts and Variable Fonts. Thank You.

**Comment by wbamberg** [comment]
Sorry if I wasn't clear. I'm just saying that the fix for this bug should be to remove the Google Fonts screenshots and detailed instructions for how to use the site, and just point people to the website instead.

As for variable fonts, I think this page intentionally doesn't get into variable fonts as this is a very basic introduction. Later chapters discuss variable fonts.
