### ISSUE TITLE
Issue with ":checked": option color property

### ISSUE THREAD

**Issue by JohanAltamar** [mdn/content#8731]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:checked

#### What information was incorrect, unhelpful, or incomplete?
```
/* Option elements, when selected */
option:checked {
  box-shadow: 0 0 0 3px lime;
  color: red;
}
```

#### Specific section or headline?
Examples - CSS - https://developer.mozilla.org/en-US/docs/Web/CSS/:checked#examples

#### What did you expect to see?
properties that can be styled, color property relies on O.S.

#### Did you test this? If so, how?
Yes, I tested it in the same way as the example says. No style changes, so the color remain black. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_checked`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:checked
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_checked/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by NegiAkash890** [comment]
Hi @JohanAltamar, by OS I think you mean browser so I opened the web page on edge, firefox and chrome and all of these have correct identical behaviour.

**Comment by rachelandrew** [comment]
There is also a note above mentioning that browsers treat these differently. I'm closing this as I don't think there is a reason to change it.

**Comment by JohanAltamar** [comment]
> There is also a note above mentioning that browsers treat these differently. I'm closing this as I don't think there is a reason to change it.

But if browser treat it differently that means that we are not able to set that property and in that way this could not be a working example. And this issue was wrongly closed @rachelandrew

**Comment by JohanAltamar** [comment]
> Hi @JohanAltamar, by OS I think you mean browser so I opened the web page on edge, firefox and chrome and all of these have correct identical behaviour.

Did you try changing the color from 'default' to another one? I tried changing it to red and there was no changes. By OS I mean Windows, linux, ... . Actually I'm having issues with an app that checked options are displayed 'white' on Windows and 'black' on Mac. That's why I'm saying this example is wrong and should be removed from docs.
