### ISSUE TITLE
[Markdown] Convert Web/API to Markdown

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#8741]
This is a tracking bug for actually converting Web/API to Markdown.

I think the plan could be something like:
* [x] Get sign-off on conversion report (meaning: close https://github.com/mdn/content/issues/7898)
* [ ] Merge as many open Web/API PRs as possible
* [ ] Freeze PRs to Web/API for a little while. Ensure that all Web/API reviewers know about this!
* [ ] File a PR to convert all of Web/API to Markdown
* [ ] Ask reviewers to review converted pages
* [ ] Make any updates needed
* [ ] Merge PR (without squashing :-)
* [ ] Unfreeze PRs to Web/API

We should aim to keep the tree frozen for not more than 2 days, say. We should ensure that all reviewers know in advance when the freeze is expected to happen, and ensure all reviewers know it's actually happening.

We should have a set of volunteers to help review the PR. Suggestions:
@Rumyra 
@sideshowbarker 
@hamishwillee 
@Elchi3 
@teoli2003 
@estelle 
@ddbeck 

Am I missing anyone?

I thought this time I could make batches of randomly selected 200 pages and each reviewer could review a batch. If we have 8 reviewers that's 1600 oages or about 1/4 the total number.

**Comment by Rumyra** [comment]
Specific Web API reviewers are: @sideshowbarker , @Elchi3 , @wbamberg , @jpmedley and myself. If everyone above is made aware along with @rachelandrew & @escattone hopefully that covers our 'Do not merge' basis 👍

**Comment by wbamberg** [comment]
Here's the list of current open PRs that touch Web/API:

https://github.com/mdn/content/pull/1560 Adding Interface HTMLPortalElement plus subpages.
https://github.com/mdn/content/pull/6103 Adds HIDInputReportEvent
https://github.com/mdn/content/pull/6462 [DO NOT MERGE] Rename feature policy in APIs (1 of 4).
https://github.com/mdn/content/pull/6481 [DO NOT MERGE] Rename feature policy in APIs (2 of 4).
https://github.com/mdn/content/pull/6498 [DO NOT MERGE] Rename feature policy in APIs (3 of 4).
https://github.com/mdn/content/pull/6508 [DO NOT MERGE] Rename feature policy in APIs (3 of 4).
https://github.com/mdn/content/pull/7218 Add more examples of using URLSearchParams
https://github.com/mdn/content/pull/7516 Showing the CSS for the synth keyboard example
https://github.com/mdn/content/pull/7570 Replace alert() in Web/API live samples
https://github.com/mdn/content/pull/8018 adds BluetoothUUID
https://github.com/mdn/content/pull/8045 Add Crypto.randomUUID page
https://github.com/mdn/content/pull/8397 Bug-1575625-Make-Cache-API-available-to-webextensions
https://github.com/mdn/content/pull/8511 Adds the AudioData interface
https://github.com/mdn/content/pull/8629 Add missing ondragleave attribute.
https://github.com/mdn/content/pull/8667 add missing <head> tag and rearrange closing tag
https://github.com/mdn/content/pull/8722 Adds WebCodecs VideoFrame
https://github.com/mdn/content/pull/8734 Add pages for URLPattern API
https://github.com/mdn/content/pull/8755 Release notes and a small update to the ResizeObserver page
https://github.com/mdn/content/pull/8771 Adds VideoColorSpace
https://github.com/mdn/content/pull/8776 Fix a dl closing tag

**Comment by jpmedley** [comment]
When is the conversion starting?

**Comment by hamishwillee** [comment]
@jpmedley According to @wbamberg he hopes to cut a draft PR for conversion early on Monday morning, UTC time with goal being to merge Tuesday afternoon Pacific time.

**Comment by wbamberg** [comment]
I spent some time today looking at our open PRs against Web/API. I've managed to close or advance a few, and put them in a spreadsheet with my assessment of whether they might be mergeable and what would need to happen to get them merged: https://docs.google.com/spreadsheets/d/1hSffPgqB-5zPPseFY0NzJC8D3uSEF8p62vNwkGFwFLM/edit?usp=sharing . It looks to me like some of them are not going to be mergeable, some we could merge, and some are already in Markdown so no action is needed \o/.

If you are the author of one of these PRs or are involved in its review, I'd love to hear what you think. Please ask me for access if you want to edit it :).

Ping @jpmedley , @rachelandrew , @Ryuno-Ki who are authors of open PRs that need some attention or are tagged as reviewers on open PRs.

As Hamish says up there, I'd like to file a PR for conversion early Monday morning, UTC time, and freeze merges of other PRs at that point. By that time I'll have prepared bunches of randomly-selected pages for people to review, which I'll link from this issue.

**Comment by jpmedley** [comment]
Rachel and I have been submitting new content in markdown for a few weeks now. The only thing I'm really concerned about in our PRs is one's that update files still in HTML. @rachelandrew Do any of your PRs update HTML?

**Comment by escattone** [comment]
It's amazing to see this completed far earlier than I ever expected. Great work everyone! 🎉 🍾

**Comment by wbamberg** [comment]
Thanks everyone who helped get this PR merged!

In case anyone's wondering what's left, here's a spreadsheet with the remaining areas and the number of pages each one contains: https://docs.google.com/spreadsheets/d/1gIW85rRxPkgsGjYw_5wLa_kGgMeOgnfYrpWytOMD8Lw/edit?usp=sharing

Apart from marvelling at the total confusion of our top-level IA, the obvious takeaway is that these are the areas left which contain >100 pages:

Area | Page count
-- | --
glossary | 538
learn | 362
mozilla | 1135
tools | 149
web/accessibility | 104
web/html | 234
web/svg | 376
