### ISSUE TITLE
Issue with "NSPR functions": external links 404

### ISSUE THREAD

**Issue by kevinburke** [mdn/content#8758]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Reference/NSPR_functions

#### What information was incorrect, unhelpful, or incomplete?

The links are all broken - "NSPR", "PR_Recv", etc, go to 404 pages.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/projects/nss/reference/nspr_functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Reference/NSPR_functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/projects/nss/reference/nspr_functions/index.html
* Last commit: https://github.com/mdn/content/commit/7ce080a8d79c3ba23048cb7e28655818d6e49efb
* Document last modified: 2021-08-23T21:16:18.000Z

</details>

**Comment by AnilSeervi** [comment]
Refer https://github.com/mdn/content/issues/7827#issuecomment-906869971

**Comment by hamishwillee** [comment]
Yes, I'm closing. This page is going "soon" (a process that has taken quite a while unfortunately). Thanks for reporting.
