### ISSUE TITLE
Issue with "Selection.selectAllChildren()": API is not experimental

### ISSUE THREAD

**Issue by zcorpan** [mdn/content#8766]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Selection/selectAllChildren

#### What information was incorrect, unhelpful, or incomplete?

The "Experimental: This is an experimental technology" box seems incorrect. The spec for this has existed since [at least 2014](https://github.com/w3c/selection-api/commit/8b3b5e86f9de1a8e0b17e7c8db7f85d7a9bbac8c), and it has been supported in browsers since forever. Am I missing something?

#### What did you expect to see?

No "experimental" banner.

#### Did you test this? If so, how?

https://wpt.fyi/results/selection/selectAllChildren.html?label=master&label=experimental&aligned

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/selection/selectallchildren`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Selection/selectAllChildren
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/selection/selectallchildren/index.html
* Last commit: https://github.com/mdn/content/commit/65b5fed3c37fd772df9f018d2ad013ef46ccdaa6
* Document last modified: 2021-06-16T06:29:37.000Z

</details>

**Comment by sideshowbarker** [comment]
Opened #8767 and https://github.com/mdn/browser-compat-data/pull/12311
