### ISSUE TITLE
Issue with "The box model": 

### ISSUE THREAD

**Issue by Dorin-David** [mdn/content#877]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model

#### What information was incorrect, unhelpful, or incomplete?
I think there is a little typo
#### Specific section or headline?
**'What is the CSS box model?'**

#### What did you expect to see?
In the last line of the section we have this sentence: _'To add some additional complexity, there is a standard and an **alternate** box model._
Whereas throughout the rest of the article we see _**alternative** box model_

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/the_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/css/building_blocks/the_box_model/index.html
* Report started: 2021-01-03T12:48:36.274Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. You’re right that the article should use the same term consistently.

 Do you want to try making the change yourself directly?

* source: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/the_box_model/index.html
* how-to: https://github.com/mdn/content/blob/main/README.md#simple-changes

Or if not, I could make the change myself. Let me know.

**Comment by Dorin-David** [comment]
Hello Michael: I've corrected the typos and I've pulled a request. As you can see in the comment of the pull request,  there is still a typo at line 170;  however, changing it may cause a problem as, straight after it, we have an embed challenge (from another repository). This is the first time I commit a change so I'm not felling comfortable in pulling a request for the other repository too. Would you mind doing it? Let me know so I can close the Issue. Thanks for your time Michael!

**Comment by rachelandrew** [comment]
@Dorin-David I just commented on your PR, before I saw this issue and discussion:

> In US English alternate and alternative are equivalent. The spec doesn't define it using either term (it describes the different values) and doing a search finds references to both alternate and alternative used in various tutorials. So not really sure it's a typo, more US usage of the term which seems pretty commonplace.

We should probably use one or the other but on the web it seems that alternate box model is used quite a lot by other tutorials so I'd suggest we make sure we are using the terminology that people are most likely to search on, given that the spec doesn't define this naming.

**Comment by Dorin-David** [comment]
@rachelandrew thanks for you comment. 
I really had no idea of the fact that in US English alternate and alternative are equivalent, thanks for the info. However, for those that are not US english speakers that could be confusing as in most languages 'alternate' is something that 'occurs in turn repeatedly', while alternative is quite intuitive. Anyway, as @sideshowbarker put it, imho we should use a term consistently. What do you think?

**Comment by rachelandrew** [comment]
The PR that also had discussion on this was closed as it would create inconsistency with the example so I don't think there is anything to do here.
