### ISSUE TITLE
Wide tables in WebXR docs

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#8775]
For https://github.com/mdn/content/pull/8736 I did some analysis of tables in Web/API that are coming out too wide in GFM, where "too wide" means > 150 characters.

It turns out that there are a few such tables in the WebXR pages that have already converted to Markdown. I think we might want to consider converting these tables back into HTML. Sorry!

https://developer.mozilla.org/en-US/docs/Web/API/xrsession/requestreferencespace (594 chars wide)
https://developer.mozilla.org/en-US/docs/Web/API/xrreferencespace  (594 chars wide)
https://developer.mozilla.org/en-US/docs/Web/API/xrpermissionstatus/granted  (594 chars wide)
https://developer.mozilla.org/en-US/docs/Web/API/webxr_device_api (342 chars wide)
https://developer.mozilla.org/en-US/docs/Web/API/webxr_device_api/geometry (594 chars wide)

I should do the same analysis for JS and CSS and HTTP, since we have only just started considering this problem.

**Comment by hamishwillee** [comment]
FWIW if you're going to do this probably easiest to do it sooner rather than later. Right now you could probably just cut-paste the original text for the tables back in.

**Comment by Elchi3** [comment]
I'm working on this today.
