### ISSUE TITLE
Issue with "Element.attachShadow()": missing information about the slotAssignment option

### ISSUE THREAD

**Issue by ilogico** [mdn/content#8782]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow

#### What information was incorrect, unhelpful, or incomplete?
The init parameter is missing information about the `slotAssignment` option, which should also be listed in the compatibility table.

#### Specific section or headline?
[Parameters](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow#parameters)

#### What did you expect to see?
Information about the `slotAssignment` option.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/attachshadow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/attachshadow/index.html
* Last commit: https://github.com/mdn/content/commit/a25e681dccbb6a990b404b4becc0a548266a6bfd
* Document last modified: 2021-08-23T14:15:15.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by #20197
