### ISSUE TITLE
Issue with "HTMLSlotElement.assign()": wrong API and missing information

### ISSUE THREAD

**Issue by ilogico** [mdn/content#8783]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assign

##### Incorrect
The `assign` method has variadic parameters, not a single array argument.
The text describes a single argument as set (which is vague, but might be interpreted as an iterable) and the example shows an array being used a single argument, which throws and exception.

##### Incomplete
It should be mentioned that nodes assigned using this method will be ignored unless the shadow root containing the slot was created with `slotAssignment` set to `"manual"`. I also think the example should show the call to `attachShadow` with the correct option.

#### Specific section or headline?
[Syntax](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assign#syntax) doesn't show the parameters are variadic
[Parameters](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assign#parameters) doesn't describe the parameters correclty
[Examples](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assign#examples) is incomplete and incorrect (the code will throw an error)

#### What did you expect to see?
It's described above.

#### Did you test this? If so, how?
I tested Firefox 92 and Chromium 93. Neither accept an array as an argument.
The `slotAssignment` option is necessary in order for this method to have effect.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlslotelement/assign`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assign
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlslotelement/assign/index.html
* Last commit: https://github.com/mdn/content/commit/5046559999ea6d9aa6a55154088ca85ca3a27408
* Document last modified: 2021-08-25T16:59:19.000Z

</details>

**Comment by Pyrolistical** [comment]
I ran into this as well. WPT has a proper code sample showing the slotAssignment must be set to manual when attaching a shadow. https://github.com/web-platform-tests/wpt/blob/7b0ebaccc62b566a1965396e5be7bb2bc06f841f/shadow-dom/slots-imperative-slot-api.tentative.html#L16

Here is the spec for the shadow dom slottable which covers manually assigned nodes https://dom.spec.whatwg.org/#light-tree-slotables

Here is the spec for the html slot element on manually assigned nodes https://html.spec.whatwg.org/multipage/scripting.html#manually-assigned-nodes

**Comment by Josh-Cena** [comment]
This has been fixed via #10533, #10548 and #15447
