### ISSUE TITLE
Issue with "setInterval()": remove MiniDaemon section

### ISSUE THREAD

**Issue by ricardobeat** [mdn/content#8798]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/setInterval

#### What information was incorrect, unhelpful, or incomplete?

Half of the page is dedicated to a third-party 'MiniDaemon' library and it's API.

Edit history appears to have been lost in this recent move https://github.com/mdn/content/commits/main/files/en-us/web/api/setinterval/index.html so can't verify when it was introduced.

#### Specific section or headline?

"MiniDaemon - A framework for managing timers"

#### What did you expect to see?

Documentation about setInterval. The third-party library in question is not even particularly popular to solve the 'problem' posed: it has 12 stars on GitHub, and is not published on any package managers. Would remove the whole section as not relevant.

It also introduces extra arguments (like a `length` parameter to limit the amount of calls) compared to the native `setTimeout` API that can introduce confusion.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/setinterval`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/setInterval
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/setinterval/index.html
* Last commit: https://github.com/mdn/content/commit/2e2631aa9d11718154ca50c2c3cc82074ab34ccd
* Document last modified: 2021-08-31T15:21:54.000Z

</details>

**Comment by teoli2003** [comment]
I'm removing it in #8810. At first sight, I don't think we need to replace it with something else.
