### ISSUE TITLE
Issue with "HTTP response status codes": incorrectly anchored link

### ISSUE THREAD

**Issue by CSharperMantle** [mdn/content#8806]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

https://github.com/mdn/content/blob/8d8a419c0f94a43700972370247a1b7226fdb79e/files/en-us/web/http/status/index.md#L20-L25

#### What information was incorrect, unhelpful, or incomplete?

The link here to RFC 7231 has an anchor point at "section-6.5.1", which referrs "6.5.1. 400 Bad Request" section in RFC 7231, a section describing a *specific* response status code.

However, this conflicts with the previous link to RFC 2616, which has an anchor to a *general* section "10 Status Code Definitions".

#### Specific section or headline?

In the opening paragraph.

#### What did you expect to see?

A link to RFC 7231 with a proper anchor point, e.g. https://datatracker.ietf.org/doc/html/rfc7231#section-6 .

#### Did you test this? If so, how?

N/A.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/status`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/status/index.md
* Last commit: https://github.com/mdn/content/commit/fd1e82ce91e89ea1d521ffdf052198f2bc1ff78e
* Document last modified: 2021-08-13T16:17:49.000Z

</details>

**Comment by teoli2003** [comment]
Thanks! I opened a PR with a fix.

**Comment by CSharperMantle** [comment]
> Thanks! I opened a PR with a fix.

Oops I opened one too 🤣 .
 
Please close mine if you have a better version.

**Comment by teoli2003** [comment]
I'll keep yours
