### ISSUE TITLE
Issue with "Document: DOMContentLoaded event": Race condition in "Checking whether loading is already complete"?

### ISSUE THREAD

**Issue by johnpmcconnell** [mdn/content#8808]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event#checking_whether_loading_is_already_complete

#### What information was incorrect, unhelpful, or incomplete?

The section "Checking whether loading is already complete" contains this code:

```
function doSomething() {
  console.info('DOM loaded');
}

if (document.readyState === 'loading') {  // Loading hasn't finished yet
  document.addEventListener('DOMContentLoaded', doSomething);
} else {  // `DOMContentLoaded` has already fired
  doSomething();
}
```

But isn't this a race condition? If the state switches from `loading` to `interactive` *after* the `if` condition finishes the check but before the event is fired, the `doSomething` function will not be invoked.

#### Specific section or headline?

"Checking whether loading is already complete"

#### What did you expect to see?

I expect to see one of two things, depending on whether my assessment is correct:

  * If there *is* a race condition, the code should be revised to prevent it somehow.
  * If there *is not* a race condition, then the page should document this fact and how we know that `readyState` cannot change between the `if` condition check and adding the event listener.

#### Did you test this? If so, how?

No, I didn't run any testing. I'm not sure how you could test a race condition reliably here.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/domcontentloaded_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/domcontentloaded_event/index.html
* Last commit: https://github.com/mdn/content/commit/b02518d8440b256c0a40377f1bb751f918ba650b
* Document last modified: 2021-08-15T05:40:09.000Z

</details>

**Comment by Josh-Cena** [comment]
JavaScript has run-to-completion semantics. If the document is loading at the particular tick of an event loop, it can't become loaded until the next event tick, at which time the handler is already attached and will be fired. This is a fundamental part of JavaScript.
