### ISSUE TITLE
Issue with "Payment Request API": Widely referenced "basic-card" payment method has been deprecated

### ISSUE THREAD

**Issue by rsolomakhin** [mdn/content#8828]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API

#### What information was incorrect, unhelpful, or incomplete?

The document references the "basic-card" payment method extensively, but that payment method has been deprecated:

- https://lists.w3.org/Archives/Public/public-payments-wg/2021Aug/0038.html
- https://github.com/w3c/payment-method-basic-card/pull/90/files
- https://groups.google.com/a/chromium.org/g/blink-dev/c/fLpgY6iLibo/m/8FpouUKiBAAJ

#### Specific section or headline?

References to "basic-card" are sprinkled throughout the document.

#### What did you expect to see?

It may be cleanest to remove the PaymentRequest section of MDN entirely, because it's not clear which of the remaining implemented payment methods should be referenced.

 - Apple Pay: Implemented only on Safari and available only on Mac OS and iOS.
 - Google Pay: Can be invoked through PaymentRequest, but Google's tutorials typically recommend using a wrapper JS library instead of invoking PaymentRequest API directly.
 - Secure Payment Confirmation: Not yet widely used and may be moved out of PaymentRequest API in the future.

Each one of these payment methods has extensive documentation elsewhere. Perhaps it would be better to link to those documents instead? 

#### Did you test this? If so, how?

I own the "basic-card" feature in Chrome and it's my job to remove the deprecated code.

cc @ianbjacobs, @stephenmcgruer, @marcoscaceres.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/payment_request_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/payment_request_api/index.html
* Last commit: https://github.com/mdn/content/commit/1fdb7dfe66928e12d6d5210f805312f6909f3f73
* Document last modified: 2021-09-07T03:03:16.000Z

</details>

**Comment by hamishwillee** [comment]
@Rumyra Did you see this one? Leaving it with you unless someone assigns me specifically as a task  ...

FWIW we might reasonably mark the `BasicCardRequest`, `BasicCardResponse`, `BasicCardChangeDetails`,  `BasicCardErrors` as deprecated as a very first step, but I agree with the above that this is messy. Mostly because we talk a lot about basic-card and if you remove that then there isn't a lot of content in the docs.

I probably wouldn't remove the whole section in MDN, but maybe cut it back to mostly just the links to the supported interfaces and start again.

**Comment by Rumyra** [comment]
As a first pass review I'd suggest the whole API is worth an update.

This will be on hold this week whilst we convert Web API docs to markdown, but then here's my list:

- [ ] Triage this issue
- [ ] See if I can find someone with bandwidth to update

**Comment by Rumyra** [comment]
@jpmedley @rachelandrew this is the Payment Request API update issue 👍

**Comment by rsolomakhin** [comment]
@jpmedley @rachelandrew - If you need us to write the initial draft for this, we'd be happy to do that. Please let us know if we can help.

**Comment by rsolomakhin** [comment]
They have not be removed. Chrome still supports them as of today. We're discussing the deprecation and removal in https://groups.google.com/a/chromium.org/g/blink-dev/c/fLpgY6iLibo/m/8FpouUKiBAAJ, where we're being asked to remove references to "basic-card" from MDN (and other places) first.

**Comment by maxlgu** [comment]
I believe this bug has been fixed by https://github.com/mdn/content/pull/9212
