### ISSUE TITLE
Issue with "Object.prototype.toString()": Nouns are flipped in overriding toString section

### ISSUE THREAD

**Issue by vgkids** [mdn/content#8830]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString

#### What information was incorrect, unhelpful, or incomplete?

The nouns in this line are incorrect: 
"With the preceding code in place, any time theDog is used in a string context, JavaScript automatically calls the dogToString() function, which returns the following string:"

Should be
"With the preceding code in place, any time `toString` is used in a Dog context, JavaScript automatically calls the dogToString() function. 

```javascript
theDog.toString(); // returns "Dog Gabby is a female chocolate Lab"
```

#### Specific section or headline?
Overriding the default toString method

#### Did you test this? If so, how?

Pasted example code as edited into chrome console and achieved results describe article update.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/tostring`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/tostring/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by teoli2003** [comment]
Thanks, I opened a PR to get it fixed.
