### ISSUE TITLE
Issue with "Date.prototype.getTime()": (example is incorrect in {{EmbedInteractiveExample("pages/js/date-gettime.html","shorter")}} The moon landing time is off by putting hours in the minutes section) 

### ISSUE THREAD

**Issue by cliffclof** [mdn/content#8831]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime

#### What information was incorrect, unhelpful, or incomplete?
the moon landing time is off.   If someone is learning and they assume the minutes section is the hours function.   just saying, the time in the example is off.  Should be 20 hours 17 or 18 minutes.   not 20 minutes 18 seconds

#### Specific section or headline?
In the example code

#### What did you expect to see?
const moonLanding = new Date('July 20, 69 20:17:40 GMT+00:00');

// milliseconds since Jan 1, 1970, 00:00:00.000 GMT
console.log(moonLanding.getTime());
// expected output: -14182940000

#### Did you test this? If so, how?
Yes, looked up the correct answer because the ms didn't match.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/gettime`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/gettime/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by teoli2003** [comment]
I opened a PR to get this fixed. Thanks!
