### ISSUE TITLE
Issue with "Array.from()": (does it create a shallow copy? )

### ISSUE THREAD

**Issue by nakulbhatt01** [mdn/content#8833]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

#### What information was incorrect, unhelpful, or incomplete?
first line under title of the page says it is a shallow-copied array instance, I checked and it is not shallow copied.
my test results are under "" #### Did you test this? If so, how? ""

If I am wrong, could you please explain with an example.
Please clarify how it is shallow-copied with an example

#### Did you test this? If so, how?
let arr = [1,2,3,4,['a','b', 'c'],5,6]
let arrCopy = Array.from(arr)
arrCopy.length = 6 // this statement doesn't change the original array. If it is a shallow copy the original array should have changed.
console.log(arrCopy.length) // output: 6
console.log(arr.length) // output: 7

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/from`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/from/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by jamesaucode** [comment]
iirc, modifying `.length` should only change that specific instance of the array. (`arrCopy` in your example), it doesn't actually remove elements from memory because arr still contains those elements.

I did some testing and `Array.from` is indeed doing a shallow copy.
```js
const arr = [ [1,2,3] ]
const arrCopy = Array.from(arr)

arr[0].push(4)
console.log(arr) // [ [1,2,3,4 ] ]
console.log(arrCopy) // [ [1,2,3,4] ]
```

**Comment by nakulbhatt01** [comment]
Right, got your point. Thanks.
