### ISSUE TITLE
Issue with "Array.prototype.mapUsingReduce()": (Code fails because index is not defined)

### ISSUE THREAD

**Issue by thiscool** [mdn/content#8861]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#write_map_using_reduce

#### What information was incorrect, unhelpful, or incomplete?
Code is incorrect under "Write map using reduce" section

#### Specific section or headline?

mappedArray[**index**] = callback.call(initialValue, currentValue, currentIndex, array)

this should be mappedArray[**currentIndex**] = callback.call(initialValue, currentValue, currentIndex, array)

#### What did you expect to see?
If we use the code as is, it complains  "index" not defined.

#### Did you test this? If so, how?
Yeah, tested the code snippet in chrome devtools

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/reduce`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/reduce/index.md
* Last commit: https://github.com/mdn/content/commit/260094b613de640ff7eff377ffb0a0ef072016eb
* Document last modified: 2021-08-16T05:07:13.000Z

</details>

**Comment by johnkelvinhhg** [comment]
Array.prototype.mapUsingReduce
