### ISSUE TITLE
can't get using_files_from_web_applications to work

### ISSUE THREAD

**Issue by DaveDixon** [mdn/content#8866]
I've duplicated the code under "Asynchronously handling the file upload process" on this page

https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications#asynchronously_handling_the_file_upload_process

And two things happen that I can't get around. Everything works fine in HTML and Javascript. When the php page is called from the XMLHttpRequest, the $_FILES is empty but $_POST['myFile'] exists.  And, it contains a FileSystemFileEntry object. But, if I try to cast it as FileSystemFileEntry, I get a 500 Internal Server Error with referrer strict-origin-when-cross-origin.

So why isn't $_FILES populated? And what about the cross origin error? The point of a file upload is to get files from the client to the server. Isn't it? 

Ubuntu 20.04, Apache 2.4.41, PHP v7.4, FireFox 92.0.

**Comment by Josh-Cena** [comment]
Hi, it has been a long while, but I've just tried locally and this simple example works. It's possible that you've run into cross-origin restrictions, but that would unfortunately be out of scope for this demo of the File API. I'm also not sure why it would be cross-origin—shouldn't you be communicating with the same endpoint that sends the HTML?
