### ISSUE TITLE
"await" is not always a keyword

### ISSUE THREAD

**Issue by spazmodius** [mdn/content#887]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

#### What information was incorrect, unhelpful, or incomplete?
Has a box that says:
 > The await keyword is only valid inside async functions. If you use it outside of an async function's body, you will get a SyntaxError.

It's not generally true that "outside of an async function's body, you will get a SyntaxError". Generally the word `async` will be parsed as an identifier.  (Maybe [modules are an exception](https://tc39.es/ecma262/#_ref_15481)?)

#### Specific section or headline?

In the **Description**

#### Did you test this? If so, how?
This is entirely legal syntax:
```
function await() { return 42 }

function g() { return await `abc` }

console.log(g())
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/statements/async_function`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/statements/async_function/index.html
* Report started: 2021-01-03T20:27:00.236Z

</details>

**Comment by chrisdavidmills** [comment]
I see what you are saying, but the text is referring to the `await` keyword. Your code is legal syntax, but it is using `await` as a function name and then invoking that function, which isn't the same thing. Knowing that there is an `await` keyword in the language, you wouldn't call a function `await` too, as that would just confuse things.

So I'm not convinced there is anything to add here?

**Comment by spazmodius** [comment]
That sentence seemed focused on the _syntax_ of `await`, but perhaps it really means "awaiting" is only valid in an async function?

**Comment by chrisdavidmills** [comment]
Yes, that's exactly what it means, afaiui

**Comment by spazmodius** [comment]
It's entirely possible I'm in the minority with how literally I read it, or perhaps its intent could be stated more clearly.  Your call.

**Comment by chrisdavidmills** [comment]
I think maybe it would help to link "async functions" in that sentence to the page covering async functions, to make the context clearer.

**Comment by wbamberg** [comment]
Thanks for filing, but really I think this note is clear as it stands.
