### ISSUE TITLE
Content suggestion: Share Target Should be Documented

### ISSUE THREAD

**Issue by jpmedley** [mdn/content#8887]
## What is the new suggestion?
Document the [Web Share Target API](https://w3c.github.io/web-share-target/). 

## Why is it important or useful?
The [Web Share API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API) is one side of a coin. It lets web apps to share links, text, and files with other applications on a user's system. The flip side of this is allowing web apps to received such shared resources from other apps, whether native or web based. 

This API is already [supported by Chromium browsers](https://www.chromestatus.com/features#web%20share%20target).

How many pages are likely to be needed? 
One: the API adds a member to the Web App Manifest

How much time do you think this work should take? A few hours? A week? A month?
An hour our two.

Will the work enable learners or professionals to achieve their goals better?
It makes it easier for devices to share resources with web-based apps.

Does it address critical needs in the web industry?
From the [explainer](https://github.com/w3c/web-share-target/blob/main/docs/explainer.md): "This is one of the missing pieces of letting web apps behave like native apps. We've recently gotten new web technologies to let websites be installed alongside native apps, run outside of the browser window, theme the system title bars, and receive push notifications. The one thing many web apps (chat clients, social networking apps) need is a way to receive content from other web apps and native apps."

Is the work an operational necessity, i.e. is not having it a security risk?
No

Does the content help make the web more ethical?
I can't say either way.

**Comment by jpmedley** [comment]
I also need somebody to approve percy.

**Comment by hamishwillee** [comment]
@jpmedley I don't know what that means ("Percy")

**Comment by jpmedley** [comment]
I wrote that in the wrong window. Sorry.
