### ISSUE TITLE
Issue with "JSON viewer": Missing Video

### ISSUE THREAD

**Issue by cas-c4ta** [mdn/content#8891]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer

#### Video missing

An embedded youtube video is obviously missing. 

#### What did you expect to see?

A video.

#### Did you test this? If so, how?

It’s obvious, no test neccessary.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/json_viewer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/json_viewer/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by AnilSeervi** [comment]
- Same issue at #7457
