### ISSUE TITLE
Issue with "SyncManager.register()": incorrect params and return

### ISSUE THREAD

**Issue by jeffposnick** [mdn/content#8893]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SyncManager/register

#### What information was incorrect, unhelpful, or incomplete?
A lot of the information on the page appears to be incorrect. I see substantial discrepancies between the description of `register()` in the [WICG spec](https://wicg.github.io/background-sync/spec/#syncmanager) and the MDN docs.

#### Specific section or headline?
There are discrepancies in all of the sections:

- description
- syntax
- returns
- parameters

#### What did you expect to see?
- The description says that the method returns `Promise<SyncRegistration>`, but the spec says it's `Promise<undefined>`.
- The syntax section shows that `[options]` are passed in as a parameter, but the spec says it's a single `string` used as the tag. The syntax also shows `.then(function(syncRegistration) { ... })`, but as previously stated, it's `Promise<undefined>`.
- The returns section should be `Promise<undefined>`, not `Promise<SyncRegistration>`.
- The parameters are incorrect. They don't mention the `tag` `string` value at all, and have a bunch of options that are... I'm not really sure where they come from, but I don't see them mentioned in the specification at all. 

#### Did you test this? If so, how?
I am just comparing the MDN docs to the specification. I have used `register('tagname')` before, though, and I know that the parameter is supposed to be a string.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/syncmanager/register`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/SyncManager/register
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/syncmanager/register/index.html
* Last commit: https://github.com/mdn/content/commit/7eaf51c2a4e856ea0eec2bf733756f44850f30c8
* Document last modified: 2021-07-26T09:31:13.000Z

</details>

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/mdn/content/pull/25215
