### ISSUE TITLE
Ambiguous Selector description

### ISSUE THREAD

**Issue by tvguho** [mdn/content#8898]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

#### What information was incorrect, unhelpful, or incomplete?
The description "... such as A is the child of B ..." directly contradicts the following descriptions which are all arranged in "B is the child of A" ordering. Reading it triggers dyslexic brain fuzz.

Also, in none of the detailed descriptions does it clearly state whether the A or B selector element match is to become the targeted object of the properties-list block. Are the properties to be applied to, for example, the parent A or the child B?

#### Specific section or headline?
Combinators

#### What did you expect to see?
Perhaps: ... such as "B is a child of A" or "B is adjacent to A."
Perhaps: In all instances the element matching the B selector becomes the target of the property-list block.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/reference/index.md
* Last commit: https://github.com/mdn/content/commit/1a9005e74ea495ae88f134fa95b15dfc7e8adcd3
* Document last modified: 2021-08-22T02:57:17.000Z

</details>

**Comment by NegiAkash890** [comment]
Working on this : )

**Comment by bit-by-bits** [comment]
@tvguho I believe this issue can be ignored as the Docs are simply trying to give examples about selectors not defining the following paragraphs in particular. If you still think this must be resolved, I would do it instantly.

**Comment by tvguho** [comment]
The title of the page is "CSS Reference". If you think it is somehow about "examples" then perhaps you are not looking at the correct section. The section is titled "Selectors". And it proceeds to give DEFINITIONS of selectors, without any examples. Try this more specific link: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#combinators

**Comment by tvguho** [comment]
It turns out that somebody has already corrected the page. They did so on virtually the same day the bug was reported. But they did not close this report. Doing so now.
