### ISSUE TITLE
Issue with "Join the MDN Web Docs community": …

### ISSUE THREAD

**Issue by nschonni** [mdn/content#890]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community

#### What information was incorrect, unhelpful, or incomplete?
There is an old NavBar macro as text at the top

![image](https://user-images.githubusercontent.com/1297909/103493325-9e6e6900-4dfe-11eb-91f2-33f1b5563ba4.png)

The page also doesn't appear to be in this repo

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/community`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/community/index.html
* Report started: 2021-01-04T01:01:27.884Z

</details>

**Comment by nschonni** [comment]
Maybe a duplicate of #2135

**Comment by sideshowbarker** [comment]
> Maybe a duplicate of [mdn/yari#2135](https://github.com/mdn/yari/issues/2135)

Yeah I think all `IncludeSubnav` instances have now been expunged on the main branch.

**Comment by chrisdavidmills** [comment]
Yup, I'm pretty sure we've gotten rid of all of these.

**Comment by nschonni** [comment]
@chrisdavidmills there is still one being rendered on this page though. Is it a matter of waiting for a deploy, or is this an odd page (that isn't in this repo)

**Comment by sideshowbarker** [comment]
Looking at https://github.com/mdn/content/commit/9a95cc8, it seems that revision deleted the `files/en-us/mdn/community/index.html` source from the tree:

```
$ git show --name-status 9a95cc8250dd78763fa40b20f9b997a02ea0ffb9
commit 9a95cc8250dd78763fa40b20f9b997a02ea0ffb9 (mdn-meta-docs)
Author: Chris Mills <cmills@mozilla.com>
Date:   Mon Dec 14 22:26:57 2020 +0000

    updating MDN meta docs — changes to About and Contribute

M       files/en-us/_wikihistory.json
M       files/en-us/mdn/about/index.html
D       files/en-us/mdn/about/linking_to_mdn/index.html
D       files/en-us/mdn/community/conversations/index.html
D       files/en-us/mdn/community/doc_sprints/index.html
D       files/en-us/mdn/community/index.html
D       files/en-us/mdn/community/whats_happening/index.html
D       files/en-us/mdn/community/working_in_community/index.html
M       files/en-us/mdn/contribute/howto/convert_code_samples_to_be_live/index.html
M       files/en-us/mdn/contribute/howto/create_and_edit_pages/index.html
D       files/en-us/mdn/contribute/howto/do_a_technical_review/index.html
D       files/en-us/mdn/contribute/howto/set_the_summary_for_a_page/index.html
M       files/en-us/mdn/contribute/howto/write_a_new_entry_in_the_glossary/index.html
D       files/en-us/mdn/contribute/howto/write_an_article_to_help_learn_about_the_web/index.html
M       files/en-us/mdn/contribute/howto/write_for_seo/index.html
M       files/en-us/mdn/contribute/index.html
M       files/en-us/mdn/structures/live_samples/index.html
D       files/en-us/mdn/tools/document_parameters/index.html
```
So from that, I would think https://developer.mozilla.org/en-US/docs/MDN/Community would be a 404. Maybe it needs a redirect?

**Comment by nschonni** [comment]
Yeah, the page is also linked to from the global navigation bar, so maybe it should be added back

**Comment by chrisdavidmills** [comment]
I'd rather update the homepage link so that it points to the correct place.
