### ISSUE TITLE
Issue with "React interactivity: Events and state": …

### ISSUE THREAD

**Issue by stonegrape** [mdn/content#891]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_interactivity_events_state

#### What information was incorrect, unhelpful, or incomplete?
const headingText = `${taskList.length} tasks remaining`;
#### Specific section or headline?
Detour: counting tasks
#### What did you expect to see?
const headingText = taskList.length +` tasks remaining`;

#### Did you test this? If so, how?

yes, I tested.
const headingText = taskList.length +` tasks remaining`;
当我在执行这一句代码时，执行结果：正确

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_interactivity_events_state
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_interactivity_events_state/index.html
* Report started: 2021-01-04T00:54:35.672Z

</details>

**Comment by chrisdavidmills** [comment]
The code supplied on the page is correct — it just uses a template literal rather than old-school string concatenation. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals for more details.
