### ISSUE TITLE
Content bug: Outdated a11y-related content on <button>

### ISSUE THREAD

**Issue by rachelandrew** [mdn/content#8929]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus

## What is the problem?

There is a table at the bottom of this page that is obviously outdated. I'm typically removing browser-specific info when I find it, however, this is a bit different as we don't have a way to log a11y-related issues in BCD.

I don't have the means to fully test a replacement, as I don't currently have a Mac or an Android device. So opening this to ask firstly, **do we want to maintain tables like this in the docs?**

If yes, then if someone with the appropriate technology can update, or at least do the tests on Android and Safari and comment here then I can update.

Related: https://developer.mozilla.org/en-US/docs/Web/Accessibility

**Comment by Josh-Cena** [comment]
Fixed by #21721. IIRC, the policy is that "wontfix issues and working-as-intended discrepancies go into prose; actual bugs that will be fixed go into the compatibility table.
