### ISSUE TITLE
Issue with "Event.composed": (short summary here please)

### ISSUE THREAD

**Issue by peebeebee** [mdn/content#8937]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Event/composed

#### What information was incorrect, unhelpful, or incomplete?
1. There is no definition of the closed-shadow component
2.  (see it live) has no link

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/event/composed`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Event/composed
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/event/composed/index.html
* Last commit: https://github.com/mdn/content/commit/67029603b9457e2ec278a254998df208ff2591c3
* Document last modified: 2021-08-21T21:04:34.000Z

</details>

**Comment by wbamberg** [comment]
The first part of this was just fixed by @ibrahim-301  in https://github.com/mdn/content/pull/12177 , and it looks like the second part was already fixed in https://github.com/mdn/content/pull/9917/files#diff-aec8543e18978ab0b3782016068629d56af60ce9714cce4dfe66b298fa70050f.
