### ISSUE TITLE
Issue with "<img>: The Image Embed element": …

### ISSUE THREAD

**Issue by ajeurkar** [mdn/content#894]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Supported_image_formats

#### What information was incorrect, unhelpful, or incomplete?
There is a typo for the word 'virtually' under the note section.

#### Specific section or headline?
[Supported image formats](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Supported_image_formats)

#### What did you expect to see?
**Note:** The older formats like PNG, JPEG, GIF have poor performance compared to newer formats like WebP and AVIF, but enjoy broader "historical" browser support. The newer image formats are seeing increasing popularity as browsers without support become increasingly irrelevant (i.e. have ~~virually~~ virtually zero market share).

#### Did you test this? If so, how?
On the browser.
![Screenshot from 2021-01-04 10-39-43](https://user-images.githubusercontent.com/52557440/103503315-e8486500-4e79-11eb-9f86-cb26d845609a.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/img`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/html/element/img/index.html
* Report started: 2021-01-04T05:04:03.275Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/895 with a fix.
