### ISSUE TITLE
Issue with "Gradients in SVG": (screenshots missing in all examples? tested in chrome & firefox)

### ISSUE THREAD

**Issue by angelayanpan** [mdn/content#8956]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients

#### What information was incorrect, unhelpful, or incomplete?
all the examples on this page have a left box that's labeled "screenshot."  but it's empty in chrome and firefox. 

#### Specific section or headline?

all examples

#### What did you expect to see?
if it's not needed, maybe we can not show the box?  if they are needed, the screenshots are missing?

#### Did you test this? If so, how?

Tried in chrome and firefox, don't see any screenshots. But can see the live examples. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/tutorial/gradients`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/tutorial/gradients/index.html
* Last commit: https://github.com/mdn/content/commit/45a7c78ec1b5fbe7aa9107059a15e9e2c142f834
* Document last modified: 2021-02-19T18:47:12.000Z

</details>

**Comment by digi-booster** [comment]
> The following png files give a 404 error and don't seem to be in the content repo:-
> 
> * https://developer.mozilla.org/files/722/SVG_Linear_Gradient_Example.png
![SVG_Linear_Gradient_Example](https://user-images.githubusercontent.com/74658643/133467290-62ffff34-b9d2-4c34-a0e7-87c1022f03a5.png)

> * https://developer.mozilla.org/files/726/SVG_Radial_Gradient_Example.png
![SVG_Radial_Gradient_Example](https://user-images.githubusercontent.com/74658643/133467360-64c4ad68-5c37-4cc1-a87d-8fcf5f51d574.png)

> * https://developer.mozilla.org/files/727/SVG_Radial_Grandient_Focus_Example.png
![SVG_Radial_Grandient_Focus_Example](https://user-images.githubusercontent.com/74658643/133467410-ae7518af-4842-47a1-ac7e-dfe34ed4510c.png)

> * https://developer.mozilla.org/files/728/SVG_SpreadMethod_Example.png
![SVG_SpreadMethod_Example](https://user-images.githubusercontent.com/74658643/133467453-5a564904-b526-430d-b8a0-09a21d895810.png)

**Comment by digi-booster** [comment]
You can also take and crop live examples screenshots and then upload them.

**Comment by digi-booster** [comment]
You can take and crop live examples/samples screenshots and then upload them.

**Comment by Un-index** [comment]
I don't see the point of a screenshot, it's probably best to remove it. Either way the only relevant image a search for "Linear_Gradient_Example" yields is the image already used in the live sample:

<img src = "https://user-images.githubusercontent.com/68165727/133470865-9cdbfc9e-b399-4d34-922a-0e191235495d.png" width=100/>

at this url: https://webplatform.github.io/docs-assets/3/3e/SVG_Linear_Gradient_Example.png

**Comment by digi-booster** [comment]
> I don't see the point of a screenshot, it's probably best to remove that column. 
Might be for people whose browsers don't support [CSS gradients](https://caniuse.com/?search=gradients).

**Comment by angelayanpan** [comment]
I assume screenshots exist for compatibility issues. I'm not sure of the support for SVG gradient in all browsers, so whether screenshots are needed or not requires additional info

**Comment by himanshugarg** [comment]
Tried creating a PR to remove the screenshots but couldn't locate the HTML (that renders the svg/png) in interactive-examples:-

https://github.com/mdn/content/blob/6114b2b7adfb48010192db334d45c315d4034979/files/en-us/web/svg/tutorial/gradients/index.html#L46
