### ISSUE TITLE
Issue with "Your first extension": video links are broken

### ISSUE THREAD

**Issue by obtusedev** [mdn/content#8957]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

#### What information was incorrect, unhelpful, or incomplete?
The video links are broken. "This video is unavailable."
![Screenshot 2021-09-15 at 13-15-00 Your first extension - Mozilla MDN](https://user-images.githubusercontent.com/66740598/133479342-f8548150-6590-451c-bbc6-10742de39326.png)

#### Specific section or headline?
Trying it out

#### What did you expect to see?
I expected to see a working YouTube video.

#### Did you test this? If so, how?
1. Open new FF or Chrome tab
2. go to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
3. Scroll down to Trying it out
4. See broken video links

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/your_first_webextension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/your_first_webextension/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by digi-booster** [comment]
Thanks for reporting the issue, but these issues have already been reported.
see https://github.com/mdn/content/issues/7457
