### ISSUE TITLE
Issue with "Guidelines to the MDN editor UI": …

### ISSUE THREAD

**Issue by xfq** [mdn/content#896]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Editor

#### What information was incorrect, unhelpful, or incomplete?

A lot of the information in this page seems to no longer apply to the current MDN. Should we remove or update them?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/editor`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Editor
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/editor/index.html
* Report started: 2021-01-04T06:13:18.310Z

</details>

**Comment by chrisdavidmills** [comment]
> A lot of the information in this page seems to no longer apply to the current MDN. Should we remove or update them?
> MDN Content page report details

Yes, definitely! As it happens, I am currently working through all of the MDN contributor docs to get them updated so they make sense for the new platform. So this should get changed or removed soon.
