### ISSUE TITLE
Content bug: Expressions and operators page doesn't contain `return` or `throw` keyword

### ISSUE THREAD

**Issue by Yash-Singh1** [mdn/content#8965]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators#primary_expressions

## Specific page section or heading?

Primary Expressions

## What is the problem?

Doesn't have `return` or `throw`

## What did you expect to see?

`return` and `throw`

## Did you test this? If so, how?

Opened up the link above in the web browser and searched for `return` then `throw`

**Comment by zacnomore** [comment]
I believe their exclusion is correct as `return` and `throw` are both statements rather than expressions



[Return](https://262.ecma-international.org/5.1/#sec-12.9)

[Throw](https://262.ecma-international.org/5.1/#sec-12.13)

**Comment by Yash-Singh1** [comment]
Then should `yield` be moved to the statements reference too?

**Comment by zacnomore** [comment]
Despite it's similarity to `return`, it seems `yield` [is an expression](https://tc39.es/ecma262/#prod-YieldExpression).

**Comment by Josh-Cena** [comment]
I don't think there's anything that needs to be done here, is there? The categorization of `return` / `throw` as statements and `await` / `yield` as expressions is correct.
