### ISSUE TITLE
Issue with "<input type="datetime-local">": (short summary here please)

### ISSUE THREAD

**Issue by schpaa** [mdn/content#8982]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

#### What information was incorrect, unhelpful, or incomplete?

Firefox does not support 'datetime-local' but the webpage says it does.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/datetime-local`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/datetime-local/index.html
* Last commit: https://github.com/mdn/content/commit/0d6ffba519d40913ce5ed176d4c8af4c354408cd
* Document last modified: 2021-09-13T12:41:16.000Z

</details>

**Comment by digi-booster** [comment]
@schpaa see [datetime-local](https://caniuse.com/?search=datetime-local).

**Comment by rachelandrew** [comment]
It's supported from Firefox 93, which is what the compat table at the bottom of the page indicates.
