### ISSUE TITLE
Issue with "Basic math in JavaScript — numbers and operators": (short summary here please)

### ISSUE THREAD

**Issue by Koda-Pig** [mdn/content#8983]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math

#### What information was incorrect, unhelpful, or incomplete?

This line beneath the "Active learning: sizing a canvas box" heading;

"Change the line that calculates x so the box is 200px wide, but the 200 is calculated using the number 4 and an assignment operator."

#### Specific section or headline?
Active learning: sizing a canvas box
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math#active_learning_sizing_a_canvas_box

#### What did you expect to see?
It is unclear if they want the value of 200 to be calculated using the first value that x is given (50), the most recent value that was calculated in the previous question regarding x (250) or from scratch. I've asked my mentor to help me with this issue and he could not make sense of it either.

#### Did you test this? If so, how?
The only solution I could find was:
4^3.8219280948874 = 200
but this doesn't make logical sense to me.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/math`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/math/index.html
* Last commit: https://github.com/mdn/content/commit/b7c594e7a8e5eb31a70bcf3e07d931e4603d201b
* Document last modified: 2021-09-03T05:34:55.000Z

</details>

**Comment by himanshugarg** [comment]
> Change the line that calculates x so the box is 200px wide, but the 200 is calculated using the number 4 and an assignment operator.

Could it be `x = x * 4`? And if yes, do you still think the statement needs an update?

While we're at it, I am curious how to solve these?
> Change the line that calculates x so the box is 250px wide, but the 250 is calculated using two numbers and the remainder (modulo) operator.
> Change the line that calculates y so the box is 150px high, but the 150 is calculated using three numbers and the subtraction and division operators.

**Comment by Koda-Pig** [comment]
@himanshugarg I believe you're right. The original value of x was given as 50, so x = x * 4 would return 200.

I made the mistake of ADDING a new line to calculate x/ y, instead of CHANGING it like the exercise specified. 

My solution to the others you mentioned were:

`Change the line that calculates x so the box is 250px wide, but the 250 is calculated using two numbers and the remainder (modulo) operator.`
x = 250%2500;

`Change the line that calculates y so the box is 150px high, but the 150 is calculated using three numbers and the subtraction and division operators.`
y = 400 / 2 - 50;
