### ISSUE TITLE
Content bug: Some TeX equations on the 3D Collision Detection article are not rendering or are incomplete

### ISSUE THREAD

**Issue by brebory** [mdn/content#8988]
## What page(s) did you find the problem on?

MDN URL: https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_collision_detection

## Specific page section or heading?

**TeX equation not rendering**

- Point vs. AABB: https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_collision_detection#point_vs._aabb
- Point vs. Sphere: https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_collision_detection#point_vs._sphere
- Sphere vs. Sphere: https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_collision_detection#sphere_vs._sphere

**TeX equation incomplete**

- AABB vs. AABB https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_collision_detection#aabb_vs._aabb

## What is the problem?

The TeX annotated equations appear to not render on this page and instead show the raw source, which makes them a little harder to understand than if they were rendered properly. Additionally, one of the equations on the page appears to to be incomplete.

## What did you expect to see?

I expected to see the TeX equations to be properly rendered.

## Did you test this? If so, how?

No other testing was completed.

## Environment Information

OS: Windows 10 Pro
Version: 21H1
Build: 19043.1165

Browser: Chrome
Version: 93.0.4577.63 (Official Build) (64-bit)

## Screenshots
![mdn-tex-errors](https://user-images.githubusercontent.com/2609819/133654078-023b7c64-c7f5-4756-a26c-bcd4c2b057a4.png)

**Comment by himanshugarg** [comment]
Thanks @brebory for the report. Would you like to include details of the browser and OS you are on. I tried the page with FF 88 on Ubuntu and these seem to be rendered fine:-

![image](https://user-images.githubusercontent.com/2392803/133642241-c46a78c2-eaf6-43cd-9002-2c1554bfef87.png)
![image](https://user-images.githubusercontent.com/2392803/133642346-49a115e0-87e7-4634-a8ad-2fae96358bcf.png)
![image](https://user-images.githubusercontent.com/2392803/133642400-cf135104-0f35-45f1-b841-f45f380717aa.png)
![image](https://user-images.githubusercontent.com/2392803/133642472-f00eba3b-52c5-47d5-ac0f-c0387aa18998.png)

**Comment by brebory** [comment]
OS: Windows 10 Pro 
Version: 21H1
Build: 19043.1165

Browser: Chrome
Version: 93.0.4577.63 (Official Build) (64-bit)

**Comment by wbamberg** [comment]
Thanks for filing, @brebory !

This is a known issue: https://github.com/mdn/yari/issues/4197

Firefox renders MathML, Chrome doesn't support it. In the old (Kuma) platform, there was a polyfill that enabled MathML to work in Chrome, but that never made it into the new (Yari) platform.

Peter was working on a fix for this in https://github.com/mdn/yari/pull/4222 .
