### ISSUE TITLE
Content suggestion: Cascade Layers

### ISSUE THREAD

**Issue by mirisuzanne** [mdn/content#8999]
## What is the new suggestion?
The [Cascade Layers specification](https://www.w3.org/TR/css-cascade-5/) has become fairly stable, with all three major browser engines already working on implementation:

- **Gecko** (Firefox):
  - [Tracking issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1699215)
  - In Firefox Nightly, this is available behind the `layout.css.cascade-layers.enabled` feature flag in `about:config`
- **Blink** (Chrome/Edge):
  - [Tracking issue](https://crbug.com/1095765)
  - In Chrome Canary, this is available behind the `--enable-blink-features=CSSCascadeLayers` run-time flag. (a public feature flag is expected soon)
- **Webkit** (Safari):
  - [Tracking issue](https://bugs.webkit.org/show_bug.cgi?id=220779)

It may become available in production across browsers by late 2020 or early 2021.

## Why is it important or useful?

Cascade Layers will help authors avoid specificity and source-order issues by allowing them to describe their own structural "layers" of the cascade. This can be used to manage third-party tools and overrides, and avoid unnecessary use of `!important`. This is a major change to the cascade, with big implications for how authors use specificity and source-order (both of which are common pain points in CSS). 

Since the entire feature is designed around the `@layer` rule (the `revert-layer` keyword is at-risk), this can likely be covered in a single page that defines the at-rule. However, it may also have an impact on other cascade-related content. It would likely take a couple hours to a couple days, depending how many other cascade pages need to be adjusted.

## Other supporting information

- [Initial explainer](https://css.oddbird.net/layers/explainer/)
- [Working Draft specification](https://www.w3.org/TR/css-cascade-5/)
- [Editor's Draft specification](https://drafts.csswg.org/css-cascade-5/)
- [WPT tests](http://wpt.live/css/css-cascade/) (Cascade Layer tests all begin with the `layer-` prefix)
- [The Future of CSS: Cascade Layers (CSS @layer)](https://www.bram.us/2021/09/15/the-future-of-css-cascade-layers-css-at-layer/) (article by **Bramus Van Damme**)

**Comment by rachelandrew** [comment]
I think we could probably document `@layer` at this point (and add to the Experimental Features page given Firefox is implementing). I'd probably avoid adding things to other pages just yet as it can be confusing for folk if there is a mix of usable and not yet usable stuff.

So I'd propose initially documenting `@layer` as a start, and revisiting the subject once at least one browser has shipped with wider changes to information about the cascade. I'll take a look at that. 

Thanks for raising the issue @mirisuzanne

**Comment by mirisuzanne** [comment]
Sounds good, thanks for taking that on!
