### ISSUE TITLE
Optional chaining example

### ISSUE THREAD

**Issue by YvonneD** [mdn/content#9000]
In the example,  should it be  "dog" instead of "cat" in the object adventurer? 
```
const adventurer = {
  name: 'Alice',
  cat: {
    name: 'Dinah'
  }
};

const dogName = adventurer.dog?.name;
console.log(dogName);
// expected output: undefined
```

**Comment by wbamberg** [comment]
Thanks for filing!

`dog` is intentional here. The use case for optional chaining is that it won't throw if an intermediate reference (`dog` in this case) is undefined. If we used `cat` it wouldn't show the use case, because `cat` is not undefined.
