### ISSUE TITLE
IOS 13 keyboard and viewport behavior problem

### ISSUE THREAD

**Issue by itsukiuehara** [mdn/content#9018]
## What is the problem?

I am displaying this contact form inside my webview but when I click on the bottom most text area it focuses on it and moves the point of view into the center ( I think this is a normal / desirable behavior ) But after the keyboard hides it remains like that thus creating a white space on the bottom part and It will get stuck into this state unless I click the top most input text. I checked this behavior on IOS 14 and it seems like it got fixed. But I am just wondering how to get around this on IOS 13.

## What did you expect to see?

in IOS 14 this works fine. I am wondering how to fix this on IOS 13
<img width="451" alt="スクリーンショット 2021-09-17 15 21 14" src="https://user-images.githubusercontent.com/60599699/133782957-66fe94c4-8403-489f-885b-36f119a881d3.png">
<img width="455" alt="スクリーンショット 2021-09-17 15 21 30" src="https://user-images.githubusercontent.com/60599699/133782974-fca4e5e0-98ba-459b-bc57-50f3b42b17ed.png">
<img width="439" alt="スクリーンショット 2021-09-17 15 21 37" src="https://user-images.githubusercontent.com/60599699/133782977-2815f729-741d-40fa-9e8b-f50bb926da5b.png">

**Comment by himanshugarg** [comment]
If this is not an issue with MDN Web Docs then StackOverflow might be a better forum for getting help.

**Comment by schalkneethling** [comment]
> If this is not an issue with MDN Web Docs then StackOverflow might be a better forum for getting help.

You are correct @himanshugarg. @itsukiuehara, you will get much faster replies for these kinds of questions and issues on Stackoverflow. This repository and the issues are specifically for issues related to the content on MDN Web Docs. (https://developer.mozilla.org)
