### ISSUE TITLE
Object.defineProperty defining getter and setter are using older coding style

### ISSUE THREAD

**Issue by KelvinPaul** [mdn/content#9026]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineSetter__

the above two links contains older coding style, under **Standard-compliant ways** heading

Older style:
```
Object.defineProperty(o, 'value', {
  set: function(val) {
    this.anotherValue = val;
  }
});
```
Modern style:
```
Object.defineProperty(o, 'value', {
  set(val) {
    this.anotherValue = val;
  }
});
```
I think we don't need this old style to define a property while using Object.defineProperty.
I checked in Firefox as well as Chrome, no problems were raised, even in the case of getter method

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/9026#issuecomment-1038552418
