### ISSUE TITLE
Missing items from CSS_Ref

### ISSUE THREAD

**Issue by rachelandrew** [mdn/content#903]
As raised in the sprints repo https://github.com/mdn/sprints/issues/2068 there are various missing properties in the CSS Reference at https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

The pages for the missing properties exist on MDN.

I'm not sure how this is generated, but I can go fix the missing items if I'm pointed in the right direction.

**Comment by sideshowbarker** [comment]
As far as I can see from looking at the https://github.com/mdn/content/blob/main/files/en-us/web/css/reference/index.html source, the content of that article, none of it is generated; instead it’s added to manually.

**Comment by rachelandrew** [comment]
it's the property names in the index I'm talking about, sorry if that wasn't clear. They are generated by the macro {{CSS_Ref}}

**Comment by sideshowbarker** [comment]
> it's the property names in the index I'm talking about, sorry if that wasn't clear.

Thanks, I see now — sorry for having been daft

From looking into the sources, here’s a short summary of how it seems to work:

* https://github.com/mdn/data/tree/master/css is the upstream source it’s generated from
* https://www.npmjs.com/package/mdn-data is the downstream source it’s directly taken from
* https://www.npmjs.com/package/mdn-data was last published 2 months ago, so there’s a lag
* https://github.com/mdn/data/tree/master/css items without `"status": "standard"` don’t get picked up

So, taking `user-select` as an example, it’s in https://github.com/mdn/data/blob/e545c59014e0760af428145b5f56125423fa77f9/css/properties.json#L8976-L8991 — but per https://github.com/mdn/data/blame/e545c59014e0760af428145b5f56125423fa77f9/css/properties.json#L8989 and https://github.com/mdn/data/commit/65ef6ada8c5504389905b26c270ce8c2015835b7, it was marked `nonstandard` until Nov 23rd.

So it *would* show up in the index now — after a new https://www.npmjs.com/package/mdn-data package is released — but because the current package is two months behind the changes to the https://github.com/mdn/data source, it’s not showing up yet.

Taking a look at a couple others: `aspect-ratio` and `appearance` don’t show up because per https://github.com/mdn/data/blob/master/css/properties.json#L1948-L1963 and https://github.com/mdn/data/blob/master/css/properties.json#L1932-L1947, they’re both marked `"status": "experimental"`. If they get marked `standard`, they’ll show up in the index.

---

(FYI https://github.com/mdn/yari/blob/56db834cc548d63dbd6fcd7132893ecb08db05b9/kumascript/macros/CSS_Ref.ejs#L11-L13 is what shows it only grabs `"status": "standard"` items.)

**Comment by rachelandrew** [comment]
@sideshowbarker I think there is a case for including the experimental items in this list. Some of them have a lot of developer interest, and there aren't a huge number of them (I was involved in a project last year to figure out which we should remove the flag from). I feel that if there is enough reason for us to document them there is reason to expose them in the list.

Pinging @chrisdavidmills for his opinion on that.

**Comment by sideshowbarker** [comment]
> I think there is a case for including the experimental items in this list… I feel that if there is enough reason for us to document them there is reason to expose them in the list.

100% agreed, for exactly that same line of thinking

> Pinging @chrisdavidmills for his opinion on that.

I’ve also gone ahead and raised https://github.com/mdn/yari/pull/2338 with the change to the macro source that’d be needed to enable this. That allows testing it locally. So with that in place in my local environment, I’ll generate a diff for https://developer.mozilla.org/en-US/docs/Web/CSS/Reference output (in a few hours), so we can see exactly what all it would add that’s not included now.

**Comment by chrisdavidmills** [comment]
> @sideshowbarker I think there is a case for including the experimental items in this list. Some of them have a lot of developer interest, and there aren't a huge number of them (I was involved in a project last year to figure out which we should remove the flag from). I feel that if there is enough reason for us to document them there is reason to expose them in the list.
> 
> Pinging @chrisdavidmills for his opinion on that.

Yes, agreed.

**Comment by sideshowbarker** [comment]
OK I tested the https://github.com/mdn/yari/pull/2338 fix and found that it doesn’t break anything, and adds the following 41 entries to the index:

<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/--*"><code>--*</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/align-tracks"><code>align-tracks</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/:any-link"><code>:any-link</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/appearance"><code>appearance</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio"><code>aspect-ratio</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-x"><code>background-position-x</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-y"><code>background-position-y</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/:blank"><code>:blank</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/block-overflow"><code>block-overflow</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/:defined"><code>:defined</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible"><code>:focus-visible</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within"><code>:focus-within</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display"><code>font-display (@font-face)</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/::grammar-error"><code>::grammar-error</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/:has"><code>:has</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/:host()"><code>:host()</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context()"><code>:host-context()</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/image-resolution"><code>image-resolution</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/@property/inherits"><code>inherits (@property)</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/initial-letter"><code>initial-letter</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/initial-letter-align"><code>initial-letter-align</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/@property/initial-value"><code>initial-value (@property)</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/:is"><code>:is</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/justify-tracks"><code>justify-tracks</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/line-clamp"><code>line-clamp</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/line-height-step"><code>line-height-step</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/margin-trim"><code>margin-trim</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/masonry-auto-flow"><code>masonry-auto-flow</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/max-lines"><code>max-lines</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/offset-position"><code>offset-position</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/::part"><code>::part</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown"><code>:placeholder-shown</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/@property"><code>@property</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-align"><code>ruby-align</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-merge"><code>ruby-merge</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-position"><code>ruby-position</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/::spelling-error"><code>::spelling-error</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/@property/syntax"><code>syntax (@property)</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip"><code>text-decoration-skip</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust"><code>text-size-adjust</code></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/:where"><code>:where</code></a>

**Comment by rachelandrew** [comment]
they all look perfectly sensible as things to include :)

**Comment by escattone** [comment]
Thanks @sideshowbarker @rachelandrew @chrisdavidmills! I just reviewed/merged @sideshowbarker's https://github.com/mdn/yari/pull/2338, which should take care of adding these CSS items with an experimental status. I'm also going to publish a new npm package for `mdn-data`, which should take care of things like the missing `user-select` (see https://github.com/mdn/sprints/issues/2068).

**Comment by escattone** [comment]
This is resolved.

**Comment by Ryuno-Ki** [comment]
> OK I tested the [mdn/yari#2338](https://github.com/mdn/yari/pull/2338) fix and found that it doesn’t break anything, and adds the following 41 entries to the index:

Do we need an issue tracking the progress of documenting those?
