### ISSUE TITLE
Issue with "text-emphasis-color": (short summary here please)

### ISSUE THREAD

**Issue by MalikRumi** [mdn/content#9034]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-color

#### What information was incorrect, unhelpful, or incomplete?
You say the em will be colored green, but in your example, it isn't!

#### Specific section or headline?
example result

#### What did you expect to see?
GREEN!

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/text-emphasis-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-color
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/text-emphasis-color/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by rachelandrew** [comment]
@MalikRumi which browser are you using?

**Comment by NegiAkash890** [comment]
> MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-color
> 
> #### What information was incorrect, unhelpful, or incomplete?
> You say the em will be colored green, but in your example, it isn't!
> 
> #### Specific section or headline?
> example result
> 
> #### What did you expect to see?
> GREEN!
> 
> #### Did you test this? If so, how?
> MDN Content page report details

You need to use vendor prefix for some browsers  as shown in the table at the bottom : 

![image](https://user-images.githubusercontent.com/55234838/134016607-abfe3afc-2951-4e17-94b1-452eb9bff8a6.png)
