### ISSUE TITLE
AudioContext.createMediaElementSource does not work in Safari

### ISSUE THREAD

**Issue by leanderseige** [mdn/content#9042]
The example does neither work in Safari 14 / Mojave nor in Safari / iOS 14.8. Is the compatibility table correct anyway?

<details>
<summary>MDN page report details</summary>

* Query: `api.AudioContext.createMediaElementSource`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource
* Report started: 2021-09-17T17:25:38.880Z

</details>

**Comment by Josh-Cena** [comment]
It works for my Safari now (I remember it didn't work two years ago), so assuming something has changed. Otherwise, we should keep track of https://github.com/mdn/webaudio-examples/issues/56 anyway.
