### ISSUE TITLE
Issue with "appearance (-moz-appearance, -webkit-appearance)": Prefixed properties should go first - standardized should be last

### ISSUE THREAD

**Issue by cotwitch** [mdn/content#9043]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/appearance

#### What information was incorrect, unhelpful, or incomplete?
Prefixed properties should be placed **before** the standardized ones. So `appearance` (without prefix) should be placed at bottom.

```
    appearance: none;
    -moz-appearance: none;
-webkit-appearance: none;
```

#### Specific section or headline?
"CSS Demo: appearance" - in the almost beginning of page, just under header

#### What did you expect to see?
Property `appearance` (without prefix) should be placed at bottom.
```
    -moz-appearance: none;
-webkit-appearance: none;
    appearance: none;
```

#### Did you test this? If so, how?
Nope :) It should work "out of the box"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/appearance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/appearance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/appearance/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by rachelandrew** [comment]
fix merged in Interactive Examples.
