### ISSUE TITLE
Issue with "setInterval()": (Typewriter simulation demo results 404)

### ISSUE THREAD

**Issue by igorradovanov** [mdn/content#9044]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/setInterval

#### What information was incorrect, unhelpful, or incomplete?

View this demo in action under the Typewriter simulation resolves to 404 Page Not Found.

#### Specific section or headline?

Yes, https://developer.mozilla.org/en-US/docs/Web/API/setInterval#example_3_typewriter_simulation

#### What did you expect to see?

Demo page for the Typewriter simulation.

#### Did you test this? If so, how?

Yes, by visiting the demo page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/setinterval`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/setInterval
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/setinterval/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by AnilSeervi** [comment]
It can be linked to JS Fiddle - https://jsfiddle.net/4o0zycpf/

**Comment by igorradovanov** [comment]
> It can be linked to JS Fiddle - https://jsfiddle.net/4o0zycpf/

Not sure if JSFiddle links are allowed in the MDN docs.
