### ISSUE TITLE
Issue with "Advanced text formatting": unneeded <p> inside <address>

### ISSUE THREAD

**Issue by mikoMK** [mdn/content#9059]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting#marking_up_contact_details

#### What information was incorrect, unhelpful, or incomplete?
We provide three `<address>` examples:
```
<address>
  <p>Chris Mills, Manchester, The Grim North, UK</p>
</address>
```
```
<address>
  <p>
    Chris Mills<br>
    Manchester<br>
    The Grim North<br>
    UK
  </p>

  <ul>
    <li>Tel: 01234 567 890</li>
    <li>Email: me@grim-north.co.uk</li>
  </ul>
</address>
```
```
<address>
  <p>Page written by <a href="../authors/chris-mills/">Chris Mills</a>.</p>
</address>
```
In my opinion the nested `<p>` element is unnecessary in examples 1 and 3. It makes sense in example 2 since we have a more complex structure.
We neither use nested `<p>` elements in the marking guide nor on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address

If there is an agreement on changing the examples you can assign me to this issue and I will provide a PR.
#### Specific section or headline?
Marking up contact details

#### What did you expect to see?
No nested `<p>` element in examples 1 and 3.

#### Did you test this? If so, how?
Both versions are valid HTML according to [W3C Validator](https://validator.w3.org/nu/#textarea).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/advanced_text_formatting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.html
* Last commit: https://github.com/mdn/content/commit/b7c594e7a8e5eb31a70bcf3e07d931e4603d201b
* Document last modified: 2021-09-03T05:34:55.000Z

</details>

**Comment by rachelandrew** [comment]
The elements are valid in that context, the bigger issue with that page is that it doesn't explain what the correct use of `<address>` is. As in it isn't for generic contact details but it's for the contact details for the particular content.

https://html.spec.whatwg.org/multipage/sections.html#the-address-element
