### ISSUE TITLE
Typo in Box alignment in CSS Grid Layout section

### ISSUE THREAD

**Issue by Evavic44** [mdn/content#9061]
In this section, the word `Axis` was misspelled with `Axes` about 6 times. 
5 of these errors were recorded in the main area while the sidebar has one. 

Link to issue: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Box_Alignment_in_CSS_Grid_Layout

Here is a preview that shows the errors using the find tool.
![box-alignment-mdn-typo](https://user-images.githubusercontent.com/62628408/133910555-2f1bc9cb-04fb-468a-acee-8cdd52c8d597.png)

**Comment by digi-booster** [comment]
@wbamberg Close this issue as well?
