### ISSUE TITLE
Issuecd5bab42-60d4-4c5b-b0a1-0c266a56beac with "Strict-Transport-Security": (short summary here please)

### ISSUE THREAD

**Issue by malkitrataul** [mdn/content#9073]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/strict-transport-security`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/strict-transport-security/index.md
* Last commit: https://github.com/mdn/content/commit/6cecaf6b41e8b366bbb57755f85334fd0d99d55e
* Document last modified: 2021-08-14T15:42:25.000Z

</details>

**Comment by teoli2003** [comment]
Hi!

Unfortunately, you didn't provide any information about the issue you are reporting. We cannot act on it.

I'm closing it. If you return and provide more information, you are welcome to re-open it (or fill a separate issue).

Thanks a lot for your interest!
