### ISSUE TITLE
Issue with "JavaScript basics": (short summary here please)

### ISSUE THREAD

**Issue by itsdebartha** [mdn/content#9089]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics

#### What information was incorrect, unhelpful, or incomplete?
The image changer function works not as it was written on this page or as I had expected it to work.

#### Specific section or headline?
In the section 'Adding an Image Changer' under the heading 'Supercharging our Example Website'

#### What did you expect to see?
Upon clicking the image for the second time, I expect the function to revert to the image which was initially present on the website.

#### Did you test this? If so, how?
I tested the function on my local machine and even hosted the website via GitHub pages ([link to website](https://itsdebartha.github.io/)) but in both instances, upon clicking the image for the second time, the image does not load.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/javascript_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/javascript_basics/index.html
* Last commit: https://github.com/mdn/content/commit/b7c594e7a8e5eb31a70bcf3e07d931e4603d201b
* Document last modified: 2021-09-03T05:34:55.000Z

</details>

**Comment by digi-booster** [comment]
I think you don't have your second image (images/**249137482.png**) in your images directory.

**Comment by digi-booster** [comment]
```js
else {
        myImage.setAttribute('src','images/icons.png'); // There is no icons.png file in your images directory.
    }
```
change into
```js 
else {
        myImage.setAttribute('src','images/icon.png');
    }

**Comment by itsdebartha** [comment]
Well, that fixes this. Thank you...
