### ISSUE TITLE
Issue with "<label>": No anchor inside a label

### ISSUE THREAD

**Issue by alattalatta** [mdn/content#9096]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

#### What information was incorrect, unhelpful, or incomplete?

There's a `<a>` inside a `<label>` in a code snippet:

```html
<label for="username"><a href="/username-forgot">Forgot your username?</a></label>
```

In the same page, under [Accessibility concerns](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#accessibility_concerns):

> Don't place interactive elements such as anchors or buttons inside a label. Doing so makes it difficult for people to activate the form input associated with the label.

#### Specific section or headline?

The bottom of the intro section, under:

> The form control that a label is labeling is called the labeled control of the label element. Multiple labels can be associated with the same form control:

#### What did you expect to see?

No anchor inside the `<label>`. (Also, can "Forgot your username" represent *a caption for an item*?)

#### Did you test this? If so, how?

No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/label`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/label/index.html
* Last commit: https://github.com/mdn/content/commit/ed8b6995c3c1cd006848e615e738ead5b1863c04
* Document last modified: 2021-09-04T05:27:10.000Z

</details>

**Comment by mikoMK** [comment]
I agree that there shouldn't be an `<a>` inside `<label>`, @alattalatta.
Just removing it like in @NegiAkash890's PR #9110 seems to make the example confusing. (Sorry!)
Since the example wants to show the possibility of having two labels for one form control, maybe this would be a better version:
```
<label for="username">Enter your username:</label>
<input id="username">
<label for="username">Forgot your username?</label>
<a href="/username-forgot">Find it!</a>
```
What do you think?

**Comment by digi-booster** [comment]
> I agree that there shouldn't be an `<a>` inside `<label>`, @alattalatta.
> Just removing it like in @NegiAkash890's PR #9110 seems to make the example confusing. (Sorry!)
> Since the example wants to show the possibility of having two labels for one form control, maybe this would be a better version:
> 
> ```
> <label for="username">Enter your username:</label>
> <input id="username">
> <label for="username">Forgot your username?</label>
> <a href="/username-forgot">Find it!</a>
> ```
> 
> What do you think?

Forgot your username label for username input doesn't make any sense, how can it help to find a username?
