### ISSUE TITLE
Issue with "repeat()": (short summary here please)

### ISSUE THREAD

**Issue by eddybrando** [mdn/content#9102]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/repeat()

#### What information was incorrect, unhelpful, or incomplete?

The specification link is wrong.

![Screenshot 2021-09-20 at 13 30 28](https://user-images.githubusercontent.com/22047320/133995421-9c1b0c02-3b7c-40a4-a2c8-43fa3da3ce7b.png)
#### Specific section or headline?

Specifications

#### What did you expect to see?

A link to the spec.

#### Did you test this? If so, how?

I clicked on it.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/repeat()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/repeat()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/repeat()/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by rachelandrew** [comment]
this isn't a problem with the link, the CSSWG site is having some issues. When it is back up again this link is correct.
