### ISSUE TITLE
Issue with "Network Security Services": …

### ISSUE THREAD

**Issue by SmallJoker** [mdn/content#911]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS

#### What information was incorrect, unhelpful, or incomplete?

Following links lead to an error 404 Page:
 * Download PKI Source
 * highlevel overview of internal details of NSS
 * getting started with NSS
 * Get the source code and Build it
 * Introduction to Network Security Services
 * NSS SSL Reference

#### Specific section or headline?

Spread across the board

#### What did you expect to see?

Documentation pages. I would like to check whether this library would fit for a little project I am planning to do.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/projects/nss`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/projects/nss/index.html
* Report started: 2021-01-04T14:33:35.517Z

</details>

**Comment by chrisdavidmills** [comment]
Closing this, as a (semi-)dupe of https://github.com/mdn/content/issues/2669
