### ISSUE TITLE
Issue with "Using shadow DOM": needs better example

### ISSUE THREAD

**Issue by jacobmakestheweb** [mdn/content#9121]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM

#### What information was incorrect, unhelpful, or incomplete?

the example to 'run through' includes a whole file structure and an image. 
the example itself is pointless as it does not show a functioning (working) example. 
the pop-up created is not even in view of the browser, this makes it hard to understand if 
setting up the constructor worked the way it should as described in the example, all in all this a really bad example of what should be a common practice. in-accesibilty in documention like this defeats the point of providing detailed docs in the first place. Gonna have to review the shadow DOM again as a concept because if anything this page made my understanding even fuzzier.

#### Specific section or headline?

The section "Working Through A Simple Example". I had a better understanding before my attempt to run through the example.

#### What did you expect to see?

a clear example, which functions correctly in the browser that i can actaullly run through myself to quickly put to use what the page described. Even if the documentation is correct and up to date, it is hard to discern what's being explained through the use of a non functioning example. It would honestly be better just not include this example at all.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/web_components/using_shadow_dom`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/web_components/using_shadow_dom/index.html
* Last commit: https://github.com/mdn/content/commit/ac06d9acff5fc139347fc3c744f2666343f0ab6a
* Document last modified: 2021-07-20T13:29:00.000Z

</details>

**Comment by vlwkaos** [comment]
@jacobmakestheweb The way I see it,  If you combine the given examples, it should to work. But as you suggested, an actual functioning example would be much helpful in this case. I will try and come up with one myself.

**Comment by vlwkaos** [comment]
@jacobmakestheweb [shadowDOM demo](https://codesandbox.io/s/nice-water-84hts?file=/src/shadowTest.js): this is the result from the sample. Most of the sample codes should be implemented inside constructor of `PopUpInfo.` I think adding a sentence or two to tell readers how it should be implemented would be enough. But If you think a working example is needed, that works too.
