### ISSUE TITLE
Issue with "What is a URL?": (Absolute URLs vs relative URLs)

### ISSUE THREAD

**Issue by esdnm** [mdn/content#9143]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL

#### What information was incorrect, unhelpful, or incomplete?

Absolute URLs vs relative URLs section has no pointers to spec

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#absolute_urls_vs_relative_urls

#### What did you expect to see?

Link to spec on the rules browsers follow for different syntax of Absolute URLs and relative URLs

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/common_questions/what_is_a_url`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/what_is_a_url/index.html
* Last commit: https://github.com/mdn/content/commit/b7c594e7a8e5eb31a70bcf3e07d931e4603d201b
* Document last modified: 2021-09-03T05:34:55.000Z

</details>

**Comment by esdnm** [comment]
@Rumyra any update on this?

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #12501 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
