### ISSUE TITLE
Issue with "Operator precedence": (issue in Postfix increment / decrement have 18 precedence which must be lower form Assignment operator  )

### ISSUE THREAD

**Issue by i-abhishekkumar** [mdn/content#9146]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

#### What information was incorrect, unhelpful, or incomplete?
Postfix increment / decrement have 18 precedence which must be lower form Assignment operator which have 3 .

#### Specific section or headline?
Table section (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table)

#### What did you expect to see?

Precedence of Postfix increment / decrement must be lower than Assignment operator.

#### Did you test this? If so, how?
Yes,
var x = 2;
var y = x++;
console.log(y); //. 

    *
O/P  =>>2 
Output is 2 because Assignment have higher precedence than  Postfix Increment . same goes with Postfix Decrement .

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/operator_precedence/index.md
* Last commit: https://github.com/mdn/content/commit/80591d2eda357ab33580af0eeeec695e398160d4
* Document last modified: 2021-08-15T13:24:35.000Z

</details>

**Comment by digi-booster** [comment]
```js
var x = 2;
var y = x++;
console.log(y); // 2
```
```js
var x = 2;
var y = ++x;
console.log(y); // 3
```
Order of Evaluation of `++` is **right to left** not **left to right**

**Comment by digi-booster** [comment]
see [Increment (++)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Increment) and [Decrement (--)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Decrement)

**Comment by digi-booster** [comment]
> @digi-booster i am aware of fact Prefix increment / Decrement works from right to left .

Both prefix and postfix increment/decrement work from right to left.
> In this issue i am talking about Postfix Increment / Decrement values and there is no Associativity of Postfix

The operator precedence values for prefix and postfix increment/decrement are the same.

**Comment by i-abhishekkumar** [comment]
@digi-booster  as per your (The operator precedence values for prefix and postfix increment/decrement are the same.)

Please explain me why 
```
var x = 2;
var y = x++;
console.log(y); // 2

var x = 2;
var y = ++x;
console.log(y); // 3
```
thy have different values if both have Associativity Right to Left and same  precedence. 

If you are not understanding my issue then please DryRun the above code you will get my question .

**Comment by digi-booster** [comment]
> @digi-booster as per your (The operator precedence values for prefix and postfix increment/decrement are the same.)
> 
> Please explain to me why
> 
> ```
> var x = 2;
> var y = x++;
> console.log(y); // 2
> 
> var x = 2;
> var y = ++x;
> console.log(y); // 3
> ```
> 
> they have different values if both have Associativity Right to Left and same precedence.
# Increment 
If used postfix, with operator after operand (for example, x++), the increment operator increments and returns the value before incrementing.

If used prefix, with the operator before operand (for example, ++x), the increment operator increments and returns the value after incrementing.
[Learn more](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Increment)
## Example
### Postfix increment
```js
let x = 3;
y = x++;

// y = 3
// x = 4
```
### Prefix increment
```js
let a = 2;
b = ++a;

// a = 3
// b = 3
```
# Decrement 
If used postfix, with operator after operand (for example, x--), the decrement operator decrements and returns the value before decrementing.

If used prefix, with the operator before operand (for example, --x), the decrement operator decrements and returns the value after decrementing.

## Example
### Postfix decrement
```js
let x = 3;
y = x--;
// y = 3
// x = 2
```
### Prefix decrement
```js
let a = 2;
b = --a;

// a = 1
// b = 1
```
[Learn more](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Decrement)

**Comment by i-abhishekkumar** [comment]
@digi-booster  Exactly  that means in Postfix increment 
let x = 3;
y = x--;

first  x will assign value to y which help of Assignment operator then,
x will decrement its value by 1 with help of Postfix decrement operator ,

which means 1st Assignment operator ran hence Assignment operator should have higher precedence then Postfix decrement.
But in the given Table i have raise Issue Postfix have higher precedence which is wrong . 

hope your understood! my point

**Comment by digi-booster** [comment]
I apologize that the operator precedence of postfix and prefix increment/decrement is not the same, and the Associativity of postfix and prefix increment/decrement is also not the same. I was confused yesterday sorry for that.

but here is nothing related to assignment operator precedence you get that result because of how prefix and postfix works

For example, the grouping operator has the highest operator precedence (21), I just modified your code to prove my point.
```js
var x = 2;
var y = (x++);
console.log(x, y); // 3, 2
```
same as
```js
var x = 2;
var y = x++;
console.log(x, y); // 3, 2
```

**Comment by AnilSeervi** [comment]
This might help you understand what precedence means and what's really happening with the postfix operators - https://stackoverflow.com/questions/54561978/how-to-justify-c-postfix-increment-operator-with-precedence-table

**Comment by Josh-Cena** [comment]
Closing because this really isn't an issue with operator precedence, but where the side-effect of postfix {in,de}crement kicks in.

Question for the reader: what's the value of `x` after

```js
let x = 1;
x = x++ + ++x;
```
