### ISSUE TITLE
Issue with "Express Tutorial Part 3: Using a Database (with Mo…": (short summary here please)

### ISSUE THREAD

**Issue by ameen-demidem** [mdn/content#9155]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

#### What information was incorrect, unhelpful, or incomplete?
Including the "luxon"  NPM package to the project was not mentioned

#### Specific section or headline?
Author model
Book model
BookInstance model

#### What did you expect to see?
instructions to install the package: `npm install --save luxon`
the missing code in the model files: `var { DateTime } = require("luxon");`

#### Did you test this? If so, how?
Checked the project Git repository because my code didn't work.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.html
* Last commit: https://github.com/mdn/content/commit/a872f1455d533a205c0f7169de7d710ce646b0d7
* Document last modified: 2021-09-06T05:03:33.000Z

</details>

**Comment by hamishwillee** [comment]
This is not a bug. If you follow the instructions to this point there is no dependency in the code for luxon.

It comes later when you're refining the UI - see https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Date_formatting_using_moment
