### ISSUE TITLE
Content suggestion: WebSocket.readyState enum properties WebSocket.OPEN, WebSocket.CLOSING, etc

### ISSUE THREAD

**Issue by MoritzKn** [mdn/content#9156]
## What is the new suggestion?
WebSocket docs are missing the `WebSocket.readyState` enum properties `WebSocket.CONNECTING`, `WebSocket.OPEN`, `WebSocket.CLOSING` and `WebSocket.CLOSED`.

Extract from the specification:

```
interface WebSocket : EventTarget {
  [...]

  // ready state
  const unsigned short CONNECTING = 0;
  const unsigned short OPEN = 1;
  const unsigned short CLOSING = 2;
  const unsigned short CLOSED = 3;
  readonly attribute unsigned short readyState;
  readonly attribute unsigned long long bufferedAmount;
  [...]
}
```

https://html.spec.whatwg.org/multipage/web-sockets.html#the-websocket-interface

## Why is it important or useful?

This would probably need to be 4 short pages. I think this can be done in less than an hour.

Having this info will make it easier for devs to find out these properties exits and lead to better code in the ecosystem.
Not knowing they exit devs might write checks like `webSocket.readyState === 1` which is confusing to readers. Devs should be enabled to write `webSocket.readyState === WebSocket.OPEN` by giving them this info.

## Other supporting information

See: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

## My contribution

I'm happy if someone fixes this but I am also willing to do it myself. However, I am unsure where to start.
Is this something that should/would be added to MDN? How are "enum states" like this usually documented? How do I go about creating these pages?

**Comment by teoli2003** [comment]
I think it is worth expanding a bit this page https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState

But we don't create a whole page for each enum entry.

**Comment by MoritzKn** [comment]
As an MDN user, my assumption usually is that each property is listed in the sidebar and has a page. When I saw that Chrome had these properties my first thought actually was that it was a custom property not in line with the spec because I didn't see it on MDN.
I feel like just putting it on the readyState page could possibly obscure that they exit. Is it possible to have them on that page but still have links in the sidebar to an anchor on that page?
