### ISSUE TITLE
Issue with "Media container formats (file types)": AV1 is mostly enabled in Firefox now

### ISSUE THREAD

**Issue by jwatt** [mdn/content#9170]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers

This page says "Firefox support for AV1 is currently disabled by default". This is not quite true. It is enabled on non-ARM Windows, macOS and Linux. It is not enabled on Android or Windows-on-ARM. See the latest version of this file:

https://searchfox.org/mozilla-central/rev/235982cdb78d0dc3ab4e48326b084ce087302cab/modules/libpref/init/StaticPrefList.yaml#8495

The bug for enabling support on Android is https://bugzilla.mozilla.org/show_bug.cgi?id=1672276 which may be worth linking to from any text that's added mentioning Android.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/media/formats/containers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/media/formats/containers/index.html
* Last commit: https://github.com/mdn/content/commit/88ad1756dc33b3c4ad0e7cf5afc1075f6d32f934
* Document last modified: 2021-06-28T09:46:56.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks very much. Fixed as you suggested in #9574
