### ISSUE TITLE
screen capture example not working

### ISSUE THREAD

**Issue by skywo1f** [mdn/content#9179]
I transferred the code onto an html file and tried to run it, but it gave me this error:

async function startCapture(displayMediaOptions) { let captureStream = null; try { captureStream = await navigator.mediaDevices.getDisplayMedia(displayMediaOptions); } catch(err) { console.error("Error: " + err); } return captureStream; } function startCapture(displayMediaOptions) { return navigator.mediaDevices.getDisplayMedia(displayMediaOptions) .catch(err => { console.error("Error:" + err); return null; }); } const gdmOptions = { video: true, audio: true } const gdmOptions = { video: { cursor: "always" }, audio: { echoCancellation: true, noiseSuppression: true, sampleRate: 44100 } } const videoElem = document.getElementById("video"); const logElem = document.getElementById("log"); const startElem = document.getElementById("start"); const stopElem = document.getElementById("stop"); // Options for getDisplayMedia() var displayMediaOptions = { video: { cursor: "always" }, audio: false }; // Set event listeners for the start and stop buttons startElem.addEventListener("click", function(evt) { startCapture(); }, false); stopElem.addEventListener("click", function(evt) { stopCapture(); }, false); console.log = msg => logElem.innerHTML += `${msg}
`; console.error = msg => logElem.innerHTML += `${msg}
`; console.warn = msg => logElem.innerHTML += `${msg}
`; console.info = msg => logElem.innerHTML += `${msg}
`; async function startCapture() { logElem.innerHTML = ""; try { videoElem.srcObject = await navigator.mediaDevices.getDisplayMedia(displayMediaOptions); dumpOptionsInfo(); } catch(err) { console.error("Error: " + err); } } function stopCapture(evt) { let tracks = videoElem.srcObject.getTracks(); tracks.forEach(track => track.stop()); videoElem.srcObject = null; } function dumpOptionsInfo() { const videoTrack = videoElem.srcObject.getVideoTracks()[0]; console.info("Track settings:"); console.info(JSON.stringify(videoTrack.getSettings(), null, 2)); console.info("Track constraints:"); console.info(JSON.stringify(videoTrack.getConstraints(), null, 2)); }

This example shows you the contents of the selected part of your display. Click the Start Capture button to begin.

**Comment by digi-booster** [comment]
I am formatting your code to make it readable.
```js
async function startCapture(displayMediaOptions)
{
  let captureStream = null;
  try
  {
    captureStream = await navigator.mediaDevices.getDisplayMedia(displayMediaOptions);
  }
  catch (err)
  {
    console.error("Error: " + err);
  }
  return captureStream;
}

function startCapture(displayMediaOptions)
{
  return navigator.mediaDevices.getDisplayMedia(displayMediaOptions).catch(err =>
  {
    console.error("Error:" + err);
    return null;
  });
}
const gdmOptions = {
  video: true,
  audio: true
}
const gdmOptions = {
  video:
  {
    cursor: "always"
  },
  audio:
  {
    echoCancellation: true,
    noiseSuppression: true,
    sampleRate: 44100
  }
}
const videoElem = document.getElementById("video");
const logElem = document.getElementById("log");
const startElem = document.getElementById("start");
const stopElem = document.getElementById("stop"); // Options for getDisplayMedia() var displayMediaOptions = { video: { cursor: "always" }, audio: false }; // Set event listeners for the start and stop buttons startElem.addEventListener("click", function(evt) { startCapture(); }, false); stopElem.addEventListener("click", function(evt) { stopCapture(); }, false); console.log = msg => logElem.innerHTML += ${msg} ; console.error = msg => logElem.innerHTML += ${msg} ; console.warn = msg => logElem.innerHTML += ${msg} ; console.info = msg => logElem.innerHTML += ${msg} ; async function startCapture() { logElem.innerHTML = ""; try { videoElem.srcObject = await navigator.mediaDevices.getDisplayMedia(displayMediaOptions); dumpOptionsInfo(); } catch(err) { console.error("Error: " + err); } } function stopCapture(evt) { let tracks = videoElem.srcObject.getTracks(); tracks.forEach(track => track.stop()); videoElem.srcObject = null; } function dumpOptionsInfo() { const videoTrack = videoElem.srcObject.getVideoTracks()[0]; console.info("Track settings:"); console.info(JSON.stringify(videoTrack.getSettings(), null, 2)); console.info("Track constraints:"); console.info(JSON.stringify(videoTrack.getConstraints(), null, 2)); }
```

**Comment by digi-booster** [comment]
What was the error about?

**Comment by digi-booster** [comment]
Can you share the screenshot of this?

**Comment by sideshowbarker** [comment]
Closing for lack of response
