### ISSUE TITLE
Issue with "Subresource Integrity": Possible need of setup of openssl not mentioned

### ISSUE THREAD

**Issue by deap82** [mdn/content#9193]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

#### What information was incorrect, unhelpful, or incomplete?
It did not mention that openssl might be something that's not setup on your computer.

#### Specific section or headline?
Sections referring to openssl.

#### What did you expect to see?
How to add openssl if you don't have it set up.
For example I found this instruction for users already having Git installed; https://stackoverflow.com/a/68253950/226589

Following the instructions about the .bat file on windows did not work initially. Without openssl in the PATH a window just opened and then instantly closed down, so I didn't grasp what was wrong until I tried running the openssl commands manually.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/security/subresource_integrity`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/security/subresource_integrity/index.html
* Last commit: https://github.com/mdn/content/commit/5cfaccce722b3ca44d9131f0da97ed83d04da938
* Document last modified: 2021-05-27T00:30:32.000Z

</details>

**Comment by bsmth** [comment]
hi @deap82, thanks a lot for raising this issue. Would you like to open a pull request that adds a hint or a link to openssl installation docs?
