### ISSUE TITLE
Issue with "Native manifests": (short summary here please)

### ISSUE THREAD

**Issue by alieme** [mdn/content#9220]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/native_manifests`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/native_manifests/index.html
* Last commit: https://github.com/mdn/content/commit/b0fddc6a09d0fdb52262a069aedfc74108a80090
* Document last modified: 2021-06-14T22:13:24.000Z

</details>

**Comment by Rumyra** [comment]
Hi @alieme can you give some more information as to the issue you found with this page please - thanks!

**Comment by sideshowbarker** [comment]
Closing for lack of response
