### ISSUE TITLE
Issue with "<param>: The Object Parameter element": (short summary here please)

### ISSUE THREAD

**Issue by wailmonir** [mdn/content#9223]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/param

#### What information was incorrect, unhelpful, or incomplete?
Why didn't I notice any behavior for the <param> element, considering the code below?

#### Did you test this? If so, how?
https://codepen.io/wailmonir/pen/qBjMKyz

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/param`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/param
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/param/index.html
* Last commit: https://github.com/mdn/content/commit/8d28de329fc4f723ad4362f0f703e46c4fa9e32d
* Document last modified: 2021-06-02T17:52:41.000Z

</details>

**Comment by teoli2003** [comment]
You should use the `<video>` element. `<object>`  and  `<param>` are for plugins and I would avoid them.

**Comment by wailmonir** [comment]
@teoli2003 Thanks, I already know that, but I want to know how it works, considering the following examples because I tried both, and it didn't show the effect they mentioned in both examples:
https://www.w3schools.com/tags/tag_param.asp
or this
https://www.geeksforgeeks.org/html-param-tag/

**Comment by sideshowbarker** [comment]
I’m going ahead and closing this because it’s not clear what you’re expecting from the code at https://codepen.io/wailmonir/pen/qBjMKyz — but regardless, that code is not from the MDN article, and it doesn’t seem like any change to the MDN article is being proposed here.
