### ISSUE TITLE
Content suggestion: Update CanvasRenderingContext2D.getContextAttributes()

### ISSUE THREAD

**Issue by yiyix** [mdn/content#9224]
## What is the new suggestion?
Update CanvasRenderingContext2D.getContextAttributes(), so it matches the attributes list in [HTMCanvasElement.getContext](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext)

## Why is it important or useful?
Readers may believe that getContextAttributes() returns two values only, alpha and desynchronized. I think it's better to keep it synchronous with HTMCanvasElement.getContext, so users has better idea of what to expect.

How many pages are likely to be needed? 
1
How much time do you think this work should take? A few hours? A week? A month? 
A few hours - few days (less than 1 week).
Will the work enable learners or professionals to achieve their goals better?
yes
Does it address critical needs in the web industry?
Maybe
Is the work an operational necessity, i.e. is not having it a security risk?
no

**Comment by yiyix** [comment]
@jpmedley could you take a look? Thank you.

**Comment by jpmedley** [comment]
@yiyix When will this be implemented in a browser?

**Comment by yiyix** [comment]
it's implemented for Chrome and the [spec change](https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-canvas-getcontextattributes) is done.

It's behind a flag now. We plan to ship it in the next release.

**Comment by jpmedley** [comment]
We'll need an approved [intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev) before we can put this on MDN.

**Comment by Elchi3** [comment]
This got done in https://github.com/mdn/content/pull/21765
