### ISSUE TITLE
Issue with "Connecting the peers": (peerjs --port 443 --key peerjs --path /myapp) not working 

### ISSUE THREAD

**Issue by Utkarshp23** [mdn/content#9246]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Build_a_phone_with_peerjs/Connect_peers

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webrtc_api/build_a_phone_with_peerjs/connect_peers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Build_a_phone_with_peerjs/Connect_peers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webrtc_api/build_a_phone_with_peerjs/connect_peers/index.md
* Last commit: https://github.com/mdn/content/commit/f63c5e74032ad21654f85dc1e5bf6bb54e2276bd
* Document last modified: 2021-09-22T23:37:53.000Z

</details>

**Comment by digi-booster** [comment]
Can you share your code?

**Comment by himanshugarg** [comment]
Thanks @Utkarshp23 for opening this issue. Could you please include more details about the specific error you are seeing.

**Comment by Utkarshp23** [comment]
I am following tutorial step step by step. On this page while running the command - "peerjs --port 443 --key peerjs --path /myapp
" I am getting an error that is - "peerjs: command not found" . But I installed both packages i.e. peer & peerjs, still it's showing the same error. what should do them ?

**Comment by himanshugarg** [comment]
Thanks @Utkarshp23. The binaries are installed in `<your-app-dir>/node_modules/.bin/` so in this case try running it with the path prefix from `<your-app-dir>` using `./node_modules/.bin/peerjs`

**Comment by Utkarshp23** [comment]
> Thanks @Utkarshp23. The binaries are installed in `<your-app-dir>/node_modules/.bin/` so in this case try running it with the path prefix from `<your-app-dir>` using: `./node_modules/.bin/peerjs --port 443 --key peerjs --path /myapp`

It's working but giving error that - "Error: Error: listen EACCES: permission denied :::443"

**Comment by sideshowbarker** [comment]
@Utkarshp23 were you ever able to get the _"Error: Error: listen EACCES: permission denied :::443"_ error resolved?

**Comment by sideshowbarker** [comment]
Closing for lack of response
