### ISSUE TITLE
Issue with "ARIA: cell role": refers to role="colheader", should be columnheader

### ISSUE THREAD

**Issue by dbjorge** [mdn/content#925]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Cell_Role

#### What information was incorrect, unhelpful, or incomplete?

The page contains some references to a non-existent `colheader` role, which should instead be `columnheader`

#### Specific section or headline?

* Second paragraph of Description section
* Third link in See also section (there aren't currently individual pages for the `columnheader` or `rowheader` roles, so possibly both of those links should be either removed or redirected to [Cell_Role's Subclass roles section](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Cell_Role#Subclass_roles)

#### What did you expect to see?

Page should refer to `columnheader` role

#### Did you test this? If so, how?

Refer to https://www.w3.org/TR/wai-aria-practices/#table

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/roles/cell_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Cell_Role
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/accessibility/aria/roles/cell_role/index.html
* Report started: 2021-01-04T20:31:11.120Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve opened https://github.com/mdn/content/pull/947 with a fix.

**Comment by dbjorge** [comment]
Thanks for such a quick response, @sideshowbarker !
