### ISSUE TITLE
Issue with "Cross-Origin Resource Sharing (CORS)": (Mismatching identification of resource)

### ISSUE THREAD

**Issue by nawazish-github** [mdn/content#9259]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

#### What information was incorrect, unhelpful, or incomplete?
In the section `https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests`, the code makes a `POST` call to the resource `/resources/post-here`. However, while illustrating the `HTTP` request-response flow diagram the resource is changed to `/doc` thus creating a disconnect in reading and understanding. 

#### Specific section or headline?
Preflighted request: `https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests`

#### What did you expect to see?
In the request-response flow diagram, I expected to see a consistent identification of the resource as `/resources/post-here`

#### Did you test this? If so, how?
Not required, as it is a documentation.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/cors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/cors/index.md
* Last commit: https://github.com/mdn/content/commit/d82c6335701cd3dbfba74a14e0e1fd59187ac6c4
* Document last modified: 2021-09-06T04:57:06.000Z

</details>

**Comment by bhaveshraj336** [comment]
Can u get it assigned ?

**Comment by nawazish-github** [comment]
Hi,

Could we get this assigned to somebody concerned?
Sincerely,
MNK

**Comment by nawazish-github** [comment]
I have commented on github to get this assigned. Let me know if there is
some other process for it.

**Comment by bhaveshraj336** [comment]
@teoli2003 can u get these assigned ?

**Comment by hamishwillee** [comment]
@nawazish-github The process is that issues wait in a queue until someone thinks they are important enough to fix and volunteers to do so. The fact this is tagged as "help wanted" means that the original triage thought that this was a valid issue that would be good for a community member to take. None have done so yet.

@bhaveshraj336 Are you volunteering to fix this?

**Comment by bhaveshraj336** [comment]
@hamishwillee yes I wanted but I saw the page in details 
The illustration  that he mentioned is for the examples below it 
And the one whixh is before the illustration 
Is only a example 
So it's seems these is no issue so no fix required ?

**Comment by bhaveshraj336** [comment]
@teoli2003  i think these issue can be resolved it don't required any work 
The website has both illustrations and the example just it has one example without illustrations?

**Comment by bhaveshraj336** [comment]
@teoli2003  I think you should close these issue  we don't need to update anything

**Comment by bhaveshraj336** [comment]
@teoli2003  We should close these issue as it is not required to chnage any thing the img which @nawazish-github mention is not valid as the example he mentions is a example without a img and then img  example has been explained below it only so no need to chnage any thing

**Comment by sideshowbarker** [comment]
@nawazish-github After reading @bhaveshraj336’s comments here, do you agree that no fix is actually needed here after all?

**Comment by sideshowbarker** [comment]
@nawazish-github The resolution of this issue is still waiting on a response from you about whether, after reading @bhaveshraj336’s comments here, you agree that no fix is actually needed here after all.

**Comment by sideshowbarker** [comment]
Closing per previous comments and for lack of response to those
