### ISSUE TITLE
Issue with "WorkerGlobalScope.console": (short summary here please)

### ISSUE THREAD

**Issue by blockbustersaraa** [mdn/content#9271]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/console

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/workerglobalscope/console`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/console
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/workerglobalscope/console/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Rumyra** [comment]
Hi @blockbustersaraa can you give some information about the issue you had with this page - thanks!

**Comment by sideshowbarker** [comment]
Closing for lack of response.
