### ISSUE TITLE
Issue with "Introduction to the server side": (short summary here please)

### ISSUE THREAD

**Issue by nitin100994** [mdn/content#9272]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction

#### What information was incorrect, unhelpful, or incomplete?
I am learning about web servers and I don't know if I am correct or not but I found order of numbers in the diagram for topic "Dynamic sites" is incorrect, on number 7 showing static resource shared with web server but we already have http response on 6th number with client, how static resources will be shared after http response is completed.

#### Specific section or headline?
Topic - "Dynamic sites", section is diagram. 

#### What did you expect to see?
order of Http response should be 7 instead of 6

#### Did you test this? If so, how?
No, it is my understanding, I may be incorrect.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/first_steps/introduction`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/first_steps/introduction/index.html
* Last commit: https://github.com/mdn/content/commit/0c86c4383e38a87df048c6fe2b95771e82420fc0
* Document last modified: 2021-09-03T03:34:08.000Z

</details>

**Comment by hamishwillee** [comment]
The diagram is correct (shows what it intends to) - but I can see why you are confused. 

When you make a request for a web page, the server returns that web page. As it loads the page it discovers it needs other files - CSS, javascript, images, etc. So it makes NEW requests for those files. after completing the dynamic request you see in the image there would have been separate requests to get the static resources 1, 7, 6.

The reason the image is correct is that we're not trying to show any of that. The diagram is showing the flow of the dynamic request. 

To "fix" this I have simply removed the numbering from the image  for step "7" - see #9274.  

Thanks for posting!
