### ISSUE TITLE
Issue with "font-synthesis": Interactive example is broken in chromium based browser

### ISSUE THREAD

**Issue by digi-booster** [mdn/content#9285]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis

#### What information was incorrect, unhelpful, or incomplete?
 Interactive example is broken  in chromium based browser
![image](https://user-images.githubusercontent.com/74658643/134892899-f18f13a1-269b-45d7-a094-5b47bd0e60ab.png)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/font-synthesis`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-synthesis/index.md
* Last commit: https://github.com/mdn/content/commit/7eedc4160a4be218371aa73324d52aed73bf06d7
* Document last modified: 2021-09-06T11:23:42.000Z

</details>

**Comment by rachelandrew** [comment]
that is the correct display when the property is unsupported. If you check the BCD you will see that there is no support in Chrome.

**Comment by digi-booster** [comment]
> that is the correct display when the property is unsupported. If you check the BCD you will see that there is no support in Chrome.

It should be hidden in the browser which is not supporting it with the help of @supports?
