### ISSUE TITLE
Issue with "Cooperative asynchronous JavaScript: Timeouts and …": (short summary here please)

### ISSUE THREAD

**Issue by seemeocon** [mdn/content#9289]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Timeouts_and_intervals

#### What information was incorrect, unhelpful, or incomplete?
Fixed typo

The **net** result of the previous code is that when the Start button is pressed, the spinner is shown and the players are made to wait a random amount of time before they are asked to press their button. This last part is handled by the setEndgame() function, which you'll define next.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/timeouts_and_intervals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Timeouts_and_intervals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/timeouts_and_intervals/index.html
* Last commit: https://github.com/mdn/content/commit/b7c594e7a8e5eb31a70bcf3e07d931e4603d201b
* Document last modified: 2021-09-03T05:34:55.000Z

</details>

**Comment by digi-booster** [comment]
Which typo?

**Comment by seemeocon** [comment]
The **net** result of the previous code -> the **next** result of the previous code.
Sorry my english

**Comment by digi-booster** [comment]
> The **net** result of the previous code -> the **next** result of the previous code.

Here net result refers to the final/end result of the previous code and describes how the code will be executed.

**Comment by seemeocon** [comment]
Tks

**Comment by sideshowbarker** [comment]
Closing per https://github.com/mdn/content/issues/9289#issuecomment-929370880
