### ISSUE TITLE
Issue with "Firefox Developer Tools": …

### ISSUE THREAD

**Issue by TheBicPen** [mdn/content#929]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools

#### What information was incorrect, unhelpful, or incomplete?
Most images on this page appear stretched, making them hard to read. 
browser: Firefox 84.0.1 (64-bit).
example: 
![image](https://user-images.githubusercontent.com/23622288/103584047-b8a75600-4e95-11eb-8fc3-e15d743bfd12.png)

#### Specific section or headline?
The Core Tools
JavaScript Debugger
Network Monitor
etc.

#### What did you expect to see?
![image](https://user-images.githubusercontent.com/23622288/103584017-ac22fd80-4e95-11eb-95ed-02feb48cddfd.png)

#### Did you test this? If so, how?
Edited image properties, setting width and height to auto
`style="border: 1px solid black; display: block; height: auto; margin-left: auto; margin-right: auto; width: auto;"`

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/tools/index.html
* Report started: 2021-01-04T22:00:01.627Z

</details>

**Comment by chrisdavidmills** [comment]
This is a known issue; @peterbe @schalkneethling pinging you here, in case this is helpful.
