### ISSUE TITLE
Issue with "Working with objects": Intern example is missing a space between variable name and '='

### ISSUE THREAD

**Issue by tjamesmac** [mdn/content#9290]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects

#### What information was incorrect, unhelpful, or incomplete?

Missing space on the example for `Intern`

#### Specific section or headline?

Missing space can be found  at [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects#using_this_for_object_references) link.

#### What did you expect to see?

A space between the variable name and the '='

#### Did you test this? If so, how?

I haven't tested this

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/guide/working_with_objects`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/working_with_objects/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by digi-booster** [comment]
I am working on this.
