### ISSUE TITLE
Issue with "Web Components": webcomponents.org is no longer a helpful reference

### ISSUE THREAD

**Issue by emclain** [mdn/content#931]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components

#### What information was incorrect, unhelpful, or incomplete?
The link to webcomponents.org is unhelpful because that site has fallen into disrepair. 

#### Specific section or headline?
"See Also"

#### What did you expect to see?
A link to a more current site (I saw a recommendation for https://open-wc.org on webcomponent.org's chat - https://gitter.im/webcomponents/community?at=5fc2a9b78c7c4215bb95d201)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/web_components`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/web_components/index.html
* Report started: 2021-01-04T22:09:48.701Z

</details>

**Comment by sideshowbarker** [comment]
Agreed that https://open-wc.org/ is a great site.

Do you want to try making the change yourself directly?

* source: https://github.com/mdn/content/blob/main/files/en-us/web/web_components/index.html
* how-to: https://github.com/mdn/content/blob/main/README.md#simple-changes
