### ISSUE TITLE
Issue with "Inputs and input sources": (short summary here please)

### ISSUE THREAD

**Issue by JakeJustLearning** [mdn/content#9311]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Inputs

#### What information was incorrect, unhelpful, or incomplete?

in the example 
`let targetRayPose = frame.session.getPose(primaryInput.targetRaySpace,viewerRefSpace);`
`let targetRayOrigin = targetRayPose.transform.position;`
`let targetRayVector = targetRayPose.transform.orientation;`

`getPose` is not a function on an `XRsession` I believe the first line should read:
`let targetRayPose = frame.getPose(primaryInput.targetRaySpace,viewerRefSpace);`

removing `session`

#### Specific section or headline?
the first example under Target ray space

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/webxr_device_api/inputs`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Inputs
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webxr_device_api/inputs/index.md
* Last commit: https://github.com/mdn/content/commit/5f37823e99ce4599fa8e2101d22ba6e06664be4a
* Document last modified: 2021-08-13T09:56:36.000Z

</details>

**Comment by vlwkaos** [comment]
I agree. Looking at [XRFrame](https://developer.mozilla.org/en-US/docs/Web/API/XRFrame) and [XRSession](https://developer.mozilla.org/en-US/docs/Web/API/XRSession) documents, `getPose` belongs to `XRFrame.`
