### ISSUE TITLE
Issue with "HTMLImageElement.sizes": Images missing

### ISSUE THREAD

**Issue by letharion** [mdn/content#9313]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes

#### What information was incorrect, unhelpful, or incomplete?
The image files are missing

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes#result

#### What did you expect to see?
Actual images

#### Did you test this? If so, how?
I loaded the page, images did not.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlimageelement/sizes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlimageelement/sizes/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by himanshugarg** [comment]
Btw there were some svg screenshots that lost themselves because they were no longer needed - https://github.com/mdn/content/issues/8956 . This one should have stayed. I wonder where they all might be now :)
