### ISSUE TITLE
Issue with "Element: keydown event": What generates a KeyboardEvent?

### ISSUE THREAD

**Issue by mubaraqwahab** [mdn/content#9321]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event

#### What information was incorrect, unhelpful, or incomplete?

Please I don't understand what's meant by this paragraph in the MDN article:

> Keyboard events are only generated by `<inputs>`, `<textarea>` and anything with the `contentEditable` attribute or with `tabindex="-1"`.

#### What did you expect to see?

They seem to be generated by arbitrary focusable elements. I expected something like:

> Keyboard events are only generated by focusable elements. This includes `<button>`, `<a>`, `<input>`, `<textarea>`, and anything with the `contenteditable` or `tabindex` attributes.

#### Did you test this? If so, how?

I added listeners for the `keydown` and `keyup` events to an `<a>`, a `<button>` and a `<span>` with `tabindex=0`, and then when I typed while the elements were focused, the listeners got called.

I should also add that the listeners for these events that were attached to parents of the focusable elements also got called (I'm guessing this is because the event bubbles up).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/keydown_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/keydown_event/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Josh-Cena** [comment]
https://github.com/mdn/content/pull/23621/ fixes some of it but I think things like `<a>` or `<button>` are still not covered
