### ISSUE TITLE
Image in example gets "invalid response" error

### ISSUE THREAD

**Issue by HelmZalee** [mdn/content#9323]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Adding_z-index

#### What information was incorrect, unhelpful, or incomplete?
Hover over block containing image & see "yari-demos.prod.mdn.mozit.cloud sent an invalid response."

#### Specific section or headline?
Using Z Index

#### What did you expect to see?
Don't know, but did not expect to see this "sad face" image (within a large rectangle)
![image](https://user-images.githubusercontent.com/38479119/135123885-d33c9111-a574-4316-bd70-1ea41aa88be4.png)

#### Did you test this? If so, how?
Opened the page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_positioning/understanding_z_index/adding_z-index`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Adding_z-index
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_positioning/understanding_z_index/adding_z-index/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks @HelmZalee for reporting this issue. Are you consistently seeing this? I am unable to reproduce the issue as I see the following but let me know if I am missing something here:-
![image](https://user-images.githubusercontent.com/2392803/135185593-a7d49347-4c72-4621-b898-bbddab76e99c.png)

**Comment by HelmZalee** [comment]
Unfortunately, I am NOT seeing the issue consistently.  I just went to the page, and it’s fine.  Suggest the issue be closed.

**Comment by HelmZalee** [comment]
Saw this again, in Chrome Version 94.0.4606.61 (Official Build) (64-bit),  Went to get version of Chrome, and was invited to update.  Did so, to Version 94.0.4606.71 (Official Build) (64-bit), pasted in the URL and...problem gone.
