### ISSUE TITLE
Content bug: Compatibility for String.prototype.match is incorrect

### ISSUE THREAD

**Issue by AlexanderStromer** [mdn/content#9328]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/match

states that IE is not supporting this function, but it is. Please correct.

**Comment by wbamberg** [comment]
The title refers to `String` but the URL in your comment is for `Symbol`. Can you clarify which page has the problem?

**Comment by AlexanderStromer** [comment]
You are right, thanks for pointing that out.
String match actually has a correct compatibility for IE:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match
