### ISSUE TITLE
Issue with "Cascade and inheritance": Inheritance values don't seem to work properly in the interactive editor

### ISSUE THREAD

**Issue by EmannuelMartinez** [mdn/content#9345]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

#### What information was incorrect, unhelpful, or incomplete?
Inheritance values don't seem to work properly in the interactive editor.

#### Specific section or headline?
Cascade_and_inheritance#resetting_all_property_values

#### What did you expect to see?
Unset is defined on the same page here, Cascade_and_inheritance#controlling_inheritance, as "Resets the property to its natural value, which means that if the property is naturally inherited it acts like inherit, otherwise it acts like initial." So I'd assume that unset would give me the value of either inherit or initial. But unset does neither. 

#### Did you test this? If so, how?
I tested it just by replacing the values of the property "all" with initial, inherit, unset, and revert. Unset is actually closest to initial, but the font is different. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/cascade_and_inheritance`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.html
* Last commit: https://github.com/mdn/content/commit/b7c594e7a8e5eb31a70bcf3e07d931e4603d201b
* Document last modified: 2021-09-03T05:34:55.000Z

</details>

**Comment by estelle** [comment]
I don't see any issues. closing.
