### ISSUE TITLE
Issue with "Firefox 89 for developers": Missing mention of `aspect-ratio` being shipped

### ISSUE THREAD

**Issue by bramus** [mdn/content#9349]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/89

#### What information was incorrect, unhelpful, or incomplete?

`aspect-ratio` shipped with Firefox 89 _([ref](https://bugzilla.mozilla.org/show_bug.cgi?id=1672073))_, but the notes for developers have no mention of this.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/firefox/releases/89`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/89
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/89/index.html
* Last commit: https://github.com/mdn/content/commit/93667e79c4a3ae558f0102707d3d09972f1b24f9
* Document last modified: 2021-07-14T14:36:44.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks! Fixes to this specific issue done in https://github.com/mdn/content/pull/9398. Note more work will need to be done on related docs though.
