### ISSUE TITLE
Issue with "Firefox 77 for developers": Link to "host permissions" is broken

### ISSUE THREAD

**Issue by binlabs** [mdn/content#935]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77

#### What information was incorrect, unhelpful, or incomplete?
There is a link for "host permissions" that goes to a URL that does not exist:
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#Host_permissions

#### Specific section or headline?
"Other" section

#### What did you expect to see?
A working page, or no link at all.

#### Did you test this? If so, how?
Manually with 78.6.0esr (64-bit) on Windows 10.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/firefox/releases/77`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mozilla/firefox/releases/77/index.html
* Report started: 2021-01-04T22:59:29.343Z

</details>

**Comment by chrisdavidmills** [comment]
Fixed via https://github.com/mdn/content/commit/31f3393952fbc93dbd2c15f21dcbf8bfe80b2202.
