### ISSUE TITLE
Issue with "Remotely debugging Thunderbird": (short summary here please)

### ISSUE THREAD

**Issue by CCOGITHUB** [mdn/content#9352]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Thunderbird

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/remote_debugging/thunderbird`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Thunderbird
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/remote_debugging/thunderbird/index.html
* Last commit: https://github.com/mdn/content/commit/0ea5ea66ca3ff5f0c02583c1f3606b3b7d4aee40
* Document last modified: 2021-02-02T16:28:31.000Z

</details>

**Comment by hamishwillee** [comment]
Closing - no information provided
