### ISSUE TITLE
Issue with "Advanced form styling": (short summary here please)

### ISSUE THREAD

**Issue by seemeocon** [mdn/content#9355]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling

#### What information was incorrect, unhelpful, or incomplete?
**section: file input types**, omitted source (Page not found)
https://github.com/mdn/learning-area/blob/master/html/forms/styling-examples/styled-file-picker.html-US/docs/

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/advanced_form_styling`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/advanced_form_styling/index.html
* Last commit: https://github.com/mdn/content/commit/46b2a2e2da1f295e4c7316234a2a546d1bd80f9e
* Document last modified: 2021-09-23T06:36:10.000Z

</details>

**Comment by digi-booster** [comment]
Thanks for raising the issue hope my pull request(pr) will fix it. :-)
