### ISSUE TITLE
Edit on GitHub and Source on GitHub links broken for some .md converted files

### ISSUE THREAD

**Issue by AnilSeervi** [mdn/content#9359]
## What page(s) did you find the problem on?
- Probably all `input` element pages 

List of some pages
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option
- and more...
## What is the problem?
- Edit on GitHub and Source on GitHub links at the end of the pages seem to be leading to 404 pages for some `.md` pages

## What did you expect to see?
Proper links to respective pages on Github

## Did you test this? If so, how?
Visit it!

**Comment by digi-booster** [comment]
I was facing the same error 1 week ago and I think it is caused by markdown conversion of HTML and it gets fixed automatically after 1-2 days of merging.

**Comment by AnilSeervi** [comment]
> I was facing the same error 1 week ago and I think it is caused by markdown conversion and renaming of HTML (#9303)  and it gets fixed automatically after 1-2 days of merging.

Yes, I see that. These files were converted just hours ago.
Closing this!
