### ISSUE TITLE
[WebAPI + HTML] Ship enterkeyhint

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#9367]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

Ship enterkeyhint - looks like this is documented [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/enterKeyHint) and [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint) - so should just be BCD update

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1648332

**Comment by hamishwillee** [comment]
- [ ] Release note: #9545 
- [ ] Remove from Experimental features - not required as is not present
- [ ] BCD 
- [ ] Docs - docs already OK. NO work to do
- [ ] dev-docs-complete

**Comment by Rumyra** [comment]
Perfect! I haven't even finished the previous release things and you've already done half the work for the next one @hamishwillee 😆 - thank you 🙏

**Comment by hamishwillee** [comment]
We got lucky - _some_ of this is easy :-)
