### ISSUE TITLE
[CSS] Implement @scroll-timeline rule

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#9368]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] mdn/data updated
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

It's back https://bugzilla.mozilla.org/show_bug.cgi?id=1676791 - so should be able to get this one done

Implement @scroll-timeline rule - should be under 'at-rules'

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1676782

**Comment by teoli2003** [comment]
@Ruymra, it is likely me misreading GitHub here, but I think you said in mdn/browser-compat-data#14663 that you will reopen a bcd bug, but never did. (Sorry if I misread)

**Comment by Rumyra** [comment]
@teoli2003 no you didn't misread at all - my local git was all messed up & I didn't quite get to fix & reopen before my week off unfortunately - it's done now tho :)
