### ISSUE TITLE
[CSS] Add support for layer() option to @import

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#9369]
## Acceptance Criteria

- [ ] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] mdn/data updated
- [ ] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

More implemented so it looks like we're good to go https://bugzilla.mozilla.org/show_bug.cgi?id=1699215 and https://bugzilla.mozilla.org/show_bug.cgi?id=1699220

Add support for layer() option to @import - this page https://developer.mozilla.org/en-US/docs/Web/CSS/@import but might want to check learn etc...

NB currently in experimental features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1699217

**Comment by rachelandrew** [comment]
This relates to https://developer.mozilla.org/en-US/docs/Web/CSS/@layer which mentions the `@import` method.

**Comment by Rumyra** [comment]
Also related #9656

**Comment by dipikabh** [comment]
@Rumyra, yes, I'll get started on this.

**Comment by dipikabh** [comment]
1. Documentation update:

- [x] https://github.com/mdn/content/pull/15205

2. Other related updates:

- [x] https://github.com/mdn/content/pull/14967
- [ ] https://github.com/mdn/content/pull/15215

3. Linked bugs are already set to to `dev-doc-complete`.
4. [Release note](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/97#css) looks updated for `layer()` support in `@import`.
