### ISSUE TITLE
SPECIFY SPLASH SCREEN FOR MANIFEST

### ISSUE THREAD

**Issue by whiwo** [mdn/content#9371]
## What is the new suggestion?
Add a parameter for a specific splash screen to the manifest

## Why is it important or useful?
I use a square icon with just the inititals of my website (Party Favorz) PF on a red background for the app to fill in for various shapes on mobile devices. My actual logo does not work (see user profile) for this purpose. 

It would be nice if there was an easy way to include a specific splashscreen and icons in a few sizes so that when the app is launched on a device, the actual logo appears as opposed to the default icon option created solely for the appearance on mobile devices.

I've read a multitude of ways to implement this and it's clearly possible because large corporations do it but for someone that doesn't know that much code — there has to be a simpler way to implement it. 

Does it address critical needs in the web industry? Yes. Branding is key to any website and not everyone's logo will be the same as the default app icon for devices. 

 -->

This is my current icon for mobile apps: [https://partyfavorz.com/wp-content/uploads/2021/09/party-favorz-logo-2021-mobile-512-1.png](url) This is my logo that I would prefer just for the splashscreen: [https://partyfavorz.com/wp-content/uploads/2021/09/Party-Favorz-Logo-512x512-1.png](url)

**Comment by sideshowbarker** [comment]
This seems like an issue for the Manifest spec that should be raised in https://github.com/w3c/manifest/issues
