### ISSUE TITLE
Content bug: Incomplete Exception information for fetch

### ISSUE THREAD

**Issue by tjcrowder** [mdn/content#9377]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions

## Specific page section or heading?

**Exceptions**

## What is the problem?

For `TypeError` it says only:

> `TypeError`:
>  The specified URL string includes user credentials. This information should instead be provided using an `Authorization` header.

That's true, but incomplete and importantly it's missing the primary reason the promise would be rejected: The request failed at the network level.

## What did you expect to see?

`fetch` rejects its promise with a `TypeError` for [several reasons](https://fetch.spec.whatwg.org/#dom-request):

* If the URL cannot be parsed
* If it has credentials (as described above)
* If any network error occurs trying to process the request

## Did you test this? If so, how?

No, I'm working from the spec.

I have a couple of other outstanding MDN issues assigned to me I hope to get to next week. I'll do this at the same time, if you want to assign this to me.

**Comment by wbamberg** [comment]
> I have a couple of other outstanding MDN issues assigned to me I hope to get to next week. I'll do this at the same time, if you want to assign this to me.

Thank you! <3

**Comment by Josh-Cena** [comment]
Fixed by #9449, then #10045
