### ISSUE TITLE
Issue with "Preflight request": preflight/options requests are not cacheable

### ISSUE THREAD

**Issue by jlax47** [mdn/content#9385]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

#### What information was incorrect, unhelpful, or incomplete?
"The preflight response can be optionally cached for the requests created in the same URL using Access-Control-Max-Age header like in the above example."

My understanding is that OPTIONS requests are NOT cacheable. You can read more about that in the spec and on the additional references that are linked on this page.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

It says right at the top that it is Cacheable: No

#### Specific section or headline?
just above the "see also" section.

#### What did you expect to see?
I believe that preflight / OPTIONS requests are NOT cacheable, so I wouldn't expect this page to mention caching at all.

#### Did you test this? If so, how?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS
https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.7

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/preflight_request`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/preflight_request/index.html
* Last commit: https://github.com/mdn/content/commit/56211004a0e5c0583d8d29c967d66e8a52e29741
* Document last modified: 2021-07-02T08:15:08.000Z

</details>

**Comment by vlwkaos** [comment]
[Here is a relevant article about preflight request caching.](https://httptoolkit.tech/blog/cache-your-cors/)

You are correct about OPTIONS requests being not cacheable.
But also, as per

> "The preflight response can be optionally cached for the requests created in the same URL **using Access-Control-Max-Age header like in the above example**."

preflight response can be cached(client/browser) and is an exception.

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #18020 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
