### ISSUE TITLE
Issue with "Contact us": (short summary here please)

### ISSUE THREAD

**Issue by alizila** [mdn/content#9386]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Contact_us

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/contact_us`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Contact_us
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/contact_us/index.html
* Last commit: https://github.com/mdn/content/commit/949677748336f7ce68d4c0b3942407fbb8d9b6f9
* Document last modified: 2020-12-23T18:33:36.000Z

</details>

**Comment by hamishwillee** [comment]
Closing as no information provided on problem
