### ISSUE TITLE
Issue with "Dummy Landing": …

### ISSUE THREAD

**Issue by nschonni** [mdn/content#939]
MDN URL: https://developer.mozilla.org/en-US/docs/web-rtc-tutorial-landing

#### What information was incorrect, unhelpful, or incomplete?

This page and it's children seem to be something that should be moved into a sub folder. Not sure if it's "Learn", "Web/Guide", etc...

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web-rtc-tutorial-landing`
* MDN URL: https://developer.mozilla.org/en-US/docs/web-rtc-tutorial-landing
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web-rtc-tutorial-landing/index.html
* Report started: 2021-01-05T00:37:18.216Z

</details>

**Comment by chrisdavidmills** [comment]
This is a set of articles that our contributor @lolaodelola is working on; they should be moved to the correct place soon, so I think we're all good here.
