### ISSUE TITLE
Issue with "Demos of open web technologies": …

### ISSUE THREAD

**Issue by nschonni** [mdn/content#940]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Demos_of_open_web_technologies

#### What information was incorrect, unhelpful, or incomplete?

This page seems like it might belong somewhere else, even the weird "Temporary" space https://developer.mozilla.org/en-US/docs/Web#Temporary

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/demos_of_open_web_technologies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Demos_of_open_web_technologies
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/demos_of_open_web_technologies/index.html
* Report started: 2021-01-05T00:40:22.517Z

</details>

**Comment by mattiapontonio** [comment]
Yep not doc.
Learning, Explore...

**Comment by chrisdavidmills** [comment]
That doc now appears in the temporary list, so I guess we can call this one closed? I think I'll take an action to improve the structure of the Web landing page, and get rid of that weird "Temporary" list...

**Comment by chrisdavidmills** [comment]
That doc now appears in the temporary list, so I guess we can call this one closed? I think I'll take an action to improve the structure of the Web landing page, and get rid of that weird "Temporary" list...
