### ISSUE TITLE
How to get ImageData directly from an image?

### ISSUE THREAD

**Issue by Rratic** [mdn/content#9412]
## What page(s) did you find the problem on?
https://developer.mozilla.org/en-US/docs/Web/API/ImageData

## What is the problem?Is something just weird?
I can put a image(setting `src`) on canvas using `Image` and get part of canvas to `ImageData`, but I can't do it directly.

## What did you expect to see?
Someone help me.

**Comment by Rratic** [comment]
anyone here?

**Comment by teoli2003** [comment]
Hi!

This bug tracker is about reporting and fixing, problems in the MDN documentation.

It looks like you are looking for help with your code. Unfortunately, we don't have enough availability to help you.

May I suggest asking your question on a specialized website, like StackOverflow?

I'm closing this issue. If I've misunderstood you and you were actually reporting a problem in the documentation, feel free to reopen it, while providing more information so we can understand the problem.

If somebody answer you elsewhere, you can also link the solution here and, then, we can see if we can improve the documentation here.

Thanks for your interest.
