### ISSUE TITLE
Issue with "Object.assign()": The demo of this method is wrong in part

### ISSUE THREAD

**Issue by mreed4** [mdn/content#9434]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

#### What information was incorrect, unhelpful, or incomplete?
In the Javascript Demo of  `Object.assign()`, the comment on Line 7 re "expected output (of `console.log(target)`)"  shows the outcome for logging `returnedTarget` (not `target`)

#### Specific section or headline?
N/A

#### What did you expect to see?
The comment on Line 7 should read `// expected output: Object { a: 1, b: 2 }` as Line 6 is logging `target` .  `target`, in Line 1, is set to `{ a: 1, b: 2 }`, not to `{ a: 1, b: 4, c: 5 }`.

#### Did you test this? If so, how?
N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/object/assign`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/assign/index.md
* Last commit: https://github.com/mdn/content/commit/94136dca4ac1e694eeddc9492e50434c4427b497
* Document last modified: 2021-09-17T04:32:31.000Z

</details>

**Comment by vlwkaos** [comment]
> Properties in the target object are overwritten by properties in the sources if they have the same key. Later sources' properties overwrite earlier ones. 

Using `Object.assign()`, the target is modified as well. It is the correct behavior.

**Comment by mreed4** [comment]
Thanks, had to take a second look!
