### ISSUE TITLE
The youtube videos on the your first extension page aren't available

### ISSUE THREAD

**Issue by zefster** [mdn/content#9438]
The title pretty much explains it the youtube videos half way down this page https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension do not load:
![image](https://user-images.githubusercontent.com/35194854/135720743-2e80b5a8-fb00-4c65-9ec5-02395f2aeaaa.png)

(I checked this in incognito and also while vpned to America and it still happened so im reasonably sure its not a browser cache thing)

**Comment by AnilSeervi** [comment]
- Similar issue #7457
