### ISSUE TITLE
Issue with "String.prototype.slice()": …

### ISSUE THREAD

**Issue by manngo** [mdn/content#944]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice

#### What information was incorrect, unhelpful, or incomplete?

>If endIndex is specified and __startIndex__ is negative, endIndex should be negative, otherwise an empty string is returned. (For example, slice(-3, 0) returns "".)

>If endIndex is specified, and __startIndex__ and endIndex are both positive or negative, endIndex should be greater than __startIndex__, otherwise an empty string is returned. (For example, slice(-1, -3) or slice(3, 1) returns "".)

#### Specific section or headline?

endIndex

#### What’s the problem?

The term __startIndex__ is introduced. In the parameter list and the rest of the documentation, it is called `_beginIndex`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/slice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/string/slice/index.html
* Report started: 2021-01-05T01:02:10.874Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it — I’ve raised https://github.com/mdn/content/pull/945 with a fix.
