### ISSUE TITLE
<!-- build_hash: db99dbebb97f630fc3d144016c8cafb5 date: 2021-10-02 15:39:19.226524 -->

### ISSUE THREAD

**Issue by mlitvin116** [mdn/content#9444]
## Preview URLs

- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Window/transitionrun_event>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Window/transitionstart_event>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/@media/grid>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/Class_selectors>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/List_of_Proprietary_CSS_Features>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/Tutorials>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/aspect-ratio>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/background-size>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/border-style>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/counter-set>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/cross-fade()>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/margin-left>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/margin-right>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/orphans>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/perspective-origin>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/text-decoration-line>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/text-decoration-style>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/text-underline-offset>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/text-underline-position>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/transform-style>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/transform>
- <https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/widows>

## Flaws

Note! *8 documents with no flaws that don't need to be listed. 🎉*

URL: [`/en-US/docs/Web/CSS/margin-right`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/margin-right)
Title: `margin-right`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/margin-right/index.md)
Flaw count: 1

- **broken_links**:
  - `Can't resolve /en-US/docs/Web/CSS/margin_collapsing`

---

URL: [`/en-US/docs/Web/CSS/cross-fade()`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/cross-fade())
Title: `cross-fade()`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/cross-fade()/index.md)
Flaw count: 11

- **macros**:
  - `/en-US/docs/Web/CSS/url redirects to /en-US/docs/Web/CSS/url()`
  - `/en-US/docs/Web/CSS/_image redirects to /en-US/docs/Web/CSS/image/image()`
  - `/en-US/docs/Web/CSS/image-set redirects to /en-US/docs/Web/CSS/image/image-set()`
  - `/en-US/docs/Web/CSS/element redirects to /en-US/docs/Web/CSS/element()`
  - `/en-US/docs/Web/CSS/linear-gradient redirects to /en-US/docs/Web/CSS/gradient/linear-gradient()`
  - *and 4 more flaws omitted*
- **broken_links**:
  - `Can't resolve /en-US/docs/`
  - `Can't resolve /en-US/docs/Web/CSS/Using_CSS_gradients`

---

URL: [`/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds)
Title: `Using multiple backgrounds`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/css_backgrounds_and_borders/using_multiple_backgrounds/index.md)
Flaw count: 2

- **broken_links**:
  - `Can't resolve /en-US/docs/Web/CSS/linear-gradient`
  - `Can't resolve /en-US/docs/Web/CSS/Using_CSS_gradients`

---

URL: [`/en-US/docs/Web/CSS/@media/grid`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/@media/grid)
Title: `grid`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/@media/grid/index.md)
Flaw count: 2

- **macros**:
  - `/en-US/docs/Web/CSS/mq-boolean redirects to /en-US/docs/Web/CSS/Media_Queries/Using_media_queries`
- **broken_links**:
  - `Anchor not lowercase`

---

URL: [`/en-US/docs/Web/CSS/margin-left`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/margin-left)
Title: `margin-left`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/margin-left/index.md)
Flaw count: 1

- **broken_links**:
  - `Can't resolve /en-US/docs/Web/CSS/margin_collapsing`

---

URL: [`/en-US/docs/Web/CSS/Tutorials`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/Tutorials)
Title: `CSS Tutorials`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/tutorials/index.md)
Flaw count: 14

- **macros**:
  - `/en-US/docs/Web/CSS/counters redirects to /en-US/docs/Web/CSS/counters()`
  - `/en-US/docs/Web/CSS/counter redirects to /en-US/docs/Web/CSS/counter()`
- **broken_links**:
  - `Can't resolve /en-US/docs/Web/CSS/Getting_Started`
  - `Can't resolve /en-US/docs/Web/CSS/Using_CSS_multiple_backgrounds`
  - `Can't resolve /en-US/docs/Web/CSS/Scaling_background_images`
  - `Can't resolve /en-US/docs/Web/CSS/Media_queries`
  - `Can't resolve /en-US/docs/Web/CSS/Understanding_z-index`
  - *and 7 more flaws omitted*

---

URL: [`/en-US/docs/Web/CSS/background-size`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/background-size)
Title: `background-size`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/background-size/index.md)
Flaw count: 3

- **broken_links**:
  - `Is currently http:// but can become https://`
  - `Can't resolve /en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Scaling_background_images`
  - `Can't resolve /en-US/docs/Web/CSS/Scaling_background_images`

---

URL: [`/en-US/docs/Web/CSS/counter-set`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/counter-set)
Title: `counter-set`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/counter-set/index.md)
Flaw count: 4

- **macros**:
  - `/en-US/docs/Web/CSS/counter redirects to /en-US/docs/Web/CSS/counter()`
  - `/en-US/docs/Web/CSS/counters redirects to /en-US/docs/Web/CSS/counters()`
- **broken_links**:
  - `Can't resolve /en-US/docs/Web/Guide/CSS/Counters`
  - `Can't resolve /en-US/docs/Web/CSS/Counters`

---

URL: [`/en-US/docs/Web/CSS/perspective-origin`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/perspective-origin)
Title: `perspective-origin`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/perspective-origin/index.md)
Flaw count: 2

- **broken_links**:
  - `Can't resolve /en-US/docs/Web/CSS/transform-function/perspective`
  - `Can't resolve /en-US/docs/Web/CSS/transform-function/perspective`

---

URL: [`/en-US/docs/Web/CSS/transform-style`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/transform-style)
Title: `transform-style`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/transform-style/index.md)
Flaw count: 1

- **broken_links**:
  - `Can't resolve /en-US/docs/Web/CSS/Using_CSS_transforms`

---

URL: [`/en-US/docs/Web/CSS/aspect-ratio`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/aspect-ratio)
Title: `aspect-ratio`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/aspect-ratio/index.md)
Flaw count: 1

- **macros**:
  - `/en-US/docs/Web/CSS/auto redirects to /en-US/docs/Web/CSS/width`

---

URL: [`/en-US/docs/Web/CSS/List_of_Proprietary_CSS_Features`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/List_of_Proprietary_CSS_Features)
Title: `List of Proprietary CSS Features`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/list_of_proprietary_css_features/index.md)
Flaw count: 16

- **macros**:
  - `/en-US/docs/Web/CSS/-moz-margin-end redirects to /en-US/docs/Web/CSS/margin-inline-end`
  - `/en-US/docs/Web/CSS/-moz-margin-start redirects to /en-US/docs/Web/CSS/margin-inline-start`
  - `/en-US/docs/Web/CSS/-moz-padding-end redirects to /en-US/docs/Web/CSS/padding-inline-end`
  - `/en-US/docs/Web/CSS/-moz-padding-start redirects to /en-US/docs/Web/CSS/padding-inline-start`
  - `/en-US/docs/Web/CSS/-moz-stack-sizing does not exist`
  - *and 8 more flaws omitted*
- **broken_links**:
  - `Can't resolve /en-US/docs/Web/CSS/Microsoft_CSS_extensions`
  - `Can't resolve /en-US/docs/Web/CSS/Webkit_Extensions`
  - `Can't resolve /en-US/docs/Web/CSS/Draft_Implementations_of_CSS_Features`

---

URL: [`/en-US/docs/Web/CSS/transform`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/transform)
Title: `transform`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/transform/index.md)
Flaw count: 4

- **macros**:
  - `/en-US/docs/Web/CSS/transform-function/perspective redirects to /en-US/docs/Web/CSS/transform-function/perspective()`
- **broken_links**:
  - `Anchor not lowercase`
  - `Can't resolve /en-US/docs/Web/Guide/CSS/Using_CSS_transforms`
  - `Can't resolve /en-US/docs/Web/CSS/Using_CSS_transforms`

---

URL: [`/en-US/docs/Web/API/Window/transitionrun_event`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Window/transitionrun_event)
Title: `Window: transitionrun event`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/api/window/transitionrun_event/index.md)
Flaw count: 4

- **macros**:
  - `/en-US/docs/Web/API/GlobalEventHandlers/ontransitionrun does not exist`
- **broken_links**:
  - `Can't resolve /en-US/docs/Web/CSS/Using_CSS_transitions`
  - `Can't resolve /en-US/docs/Web/API/GlobalEventHandlers/ontransitionrun`
  - `Anchor not lowercase`

---

URL: [`/en-US/docs/Web/API/Window/transitionstart_event`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Window/transitionstart_event)
Title: `Window: transitionstart event`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/api/window/transitionstart_event/index.md)
Flaw count: 5

- **macros**:
  - `/en-US/docs/Web/API/GlobalEventHandlers/ontransitionstart does not exist`
  - `/en-US/docs/Web/API/GlobalEventHandlers/ontransitionstart does not exist`
  - `/en-US/docs/Web/API/GlobalEventHandlers/ontransitionstart does not exist`
- **broken_links**:
  - `Can't resolve /en-US/docs/Web/CSS/Using_CSS_transitions`
  - `Anchor not lowercase`

## External URLs

URL: [`/en-US/docs/Web/CSS/Class_selectors`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/Class_selectors)
Title: `Class selectors`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/class_selectors/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/margin-right`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/margin-right)
Title: `margin-right`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/margin-right/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/cross-fade()`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/cross-fade())
Title: `cross-fade()`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/cross-fade()/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/text-underline-offset`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/text-underline-offset)
Title: `text-underline-offset`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/text-underline-offset/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds)
Title: `Using multiple backgrounds`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/css_backgrounds_and_borders/using_multiple_backgrounds/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/widows`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/widows)
Title: `widows`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/widows/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/text-decoration-style`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/text-decoration-style)
Title: `text-decoration-style`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/text-decoration-style/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/@media/grid`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/@media/grid)
Title: `grid`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/@media/grid/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/margin-left`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/margin-left)
Title: `margin-left`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/margin-left/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/Tutorials`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/Tutorials)
Title: `CSS Tutorials`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/tutorials/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/text-underline-position`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/text-underline-position)
Title: `text-underline-position`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/text-underline-position/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/text-decoration-line`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/text-decoration-line)
Title: `text-decoration-line`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/text-decoration-line/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/orphans`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/orphans)
Title: `orphans`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/orphans/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/border-style`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/border-style)
Title: `border-style`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/border-style/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/background-size`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/background-size)
Title: `background-size`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/background-size/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/counter-set`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/counter-set)
Title: `counter-set`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/counter-set/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/perspective-origin`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/perspective-origin)
Title: `perspective-origin`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/perspective-origin/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/transform-style`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/transform-style)
Title: `transform-style`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/transform-style/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/aspect-ratio`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/aspect-ratio)
Title: `aspect-ratio`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/aspect-ratio/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/List_of_Proprietary_CSS_Features`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/List_of_Proprietary_CSS_Features)
Title: `List of Proprietary CSS Features`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/list_of_proprietary_css_features/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/CSS/transform`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/transform)
Title: `transform`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/css/transform/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/API/Window/transitionrun_event`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Window/transitionrun_event)
Title: `Window: transitionrun event`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/api/window/transitionrun_event/index.md)

No *new* external URLs

---
URL: [`/en-US/docs/Web/API/Window/transitionstart_event`](https://pr9441.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Window/transitionstart_event)
Title: `Window: transitionstart event`
[on GitHub](https://github.com/mdn/content/blob/9441/merge/files/en-us/web/api/window/transitionstart_event/index.md)

No *new* external URLs

_Originally posted by @github-actions[bot] in https://github.com/mdn/content/issues/9441#issuecomment-932772133_

**Comment by hamishwillee** [comment]
No info. Closing.
