### ISSUE TITLE
<!-- build_hash: 7e5af67f3e97b2d3c7cfa73026d72191 date: 2021-10-01 18:01:14.254048 -->

### ISSUE THREAD

**Issue by mlitvin116** [mdn/content#9446]
## Preview URLs

- <https://pr9427.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Response/statusText>

## Flaws

*None!* 🎉

## External URLs

URL: [`/en-US/docs/Web/API/Response/statusText`](https://pr9427.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Response/statusText)
Title: `Response.statusText`
[on GitHub](https://github.com/mdn/content/blob/9427/merge/files/en-us/web/api/response/statustext/index.md)

No *new* external URLs

_Originally posted by @github-actions[bot] in https://github.com/mdn/content/issues/9427#issuecomment-932442471_

**Comment by hamishwillee** [comment]
No info. Closing.
