### ISSUE TITLE
Issue with "Your first extension": YouTube videos are unavaible

### ISSUE THREAD

**Issue by martenmatrix** [mdn/content#9450]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

#### What information was incorrect, unhelpful, or incomplete?
The YouTube videos are unavailable. YouTube does not state, that it is because of the country I resident in.

#### Specific section or headline?
Installing and Testing

#### What did you expect to see?
Videos, which teach me, how to make an extension for Firefox.

#### Did you test this? If so, how?
I did not access the site with a VPN because, as stated above, it is not a region-related issue. If it were, YouTube would display the following error message: "This video is not available in your country". However, the error message states: "This video is not available".

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/your_first_webextension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/your_first_webextension/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing! This issue is being tracked as https://github.com/mdn/content/issues/7457.
