### ISSUE TITLE
Issue with "AudioContext.suspend()": Example Button Caption is wrong after Stop during Suspend

### ISSUE THREAD

**Issue by DrTechDaddy** [mdn/content#9451]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/suspend

#### What information was incorrect, unhelpful, or incomplete?
The example 
https://mdn.github.io/webaudio-examples/audiocontext-states/
has a bug.
The sequence: 
Create context; Suspend context; Stop context; Create context
results with the context running and sounding but the suspend/resume button caption remains Resume context.
FIX: add a line in startBtn.onclick()
   susresBtn.textContent = 'Suspend context';

#### Specific section or headline?
Example: see it running live

#### What did you expect to see?
The susres button label should always show 'Suspend context' when the context is running

#### Did you test this? If so, how?
Yes. I ran the linked example.''
I made a local fix and tested it.
I did not make any changes on GitHub.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/audiocontext/suspend`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/suspend
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/audiocontext/suspend/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Rumyra** [comment]
Resolved via recent webaudio-examples updates
