### ISSUE TITLE
Fix `InvalidStateException` exceptions

### ISSUE THREAD

**Issue by teoli2003** [mdn/content#9456]
The way we described [DOM Exceptions](https://developer.mozilla.org/en-US/docs/Web/API/DOMException) is inconsistent.

Some pages use tables, some pages use lists. Also, we want to indicate that these `InvalidStateException`are `DOMException` object of a given type.

The right way of doing this is to have an _Exceptions_ paragraph with a `<dl>` list, like this:

```
### Exceptions
- `NotSupportedError` {{domxref("DOMException")}}
  - : Thrown if …
```

The goal here is to go through the list of pages below and, for each of them, to be sure that the exception section is in the adequate format. If the `InvalidStateException` is inside the text, make sure that it is followed by `{{domxref("DOMException")}}` so the reader is aware of it.

- [x] files/en-us/web/api/sourcebuffer/remove/index.md
- [x] files/en-us/web/api/pannernode/pannernode/index.md
- [x] files/en-us/web/api/pannernode/coneoutergain/index.md
- [x] files/en-us/web/api/xrsession/requestlightprobe/index.md
- [x] files/en-us/web/api/xrsession/requesthittestsource/index.md
- [x] files/en-us/web/api/xrsession/updaterenderstate/index.md
- [x] files/en-us/web/api/xrsession/requesthittestsourcefortransientinput/index.md
- [ ] files/en-us/web/api/mediarecorder/pause/index.md
- [ ] files/en-us/web/api/mediarecorder/onerror/index.md
- [x] files/en-us/web/api/mediarecorder/start/index.md
- [x] files/en-us/web/api/audioencoder/encode/index.md
- [x] files/en-us/web/api/audioencoder/configure/index.md
- [x] files/en-us/web/api/audioencoder/flush/index.md
- [ ] files/en-us/web/api/paymentrequest/show/index.md
- [x] files/en-us/web/api/xrwebglbinding/getdepthinformation/index.md
- [x] files/en-us/web/api/xrwebglbinding/xrwebglbinding/index.md
- [ ] files/en-us/web/api/idbrequest/index.md
- [ ] files/en-us/web/api/idbrequest/error/index.md
- [ ] files/en-us/web/api/idbrequest/result/index.md
- [x] files/en-us/web/api/idbdatabase/transaction/index.md
- [x] files/en-us/web/api/idbdatabase/deleteobjectstore/index.md
- [x] files/en-us/web/api/idbdatabase/createobjectstore/index.md
- [x] files/en-us/web/api/imagedecoder/decode/index.md
- [x] files/en-us/web/api/channelmergernode/channelmergernode/index.md
- [x] files/en-us/web/api/datatransferitemlist/remove/index.md
- [x] files/en-us/web/api/canvasrenderingcontext2d/putimagedata/index.md
- [ ] files/en-us/web/api/rtcpeerconnection/setremotedescription/index.md
- [x] files/en-us/web/api/audiodecoder/decode/index.md
- [x] files/en-us/web/api/audiodecoder/configure/index.md
- [x] files/en-us/web/api/audiodecoder/flush/index.md
- [x] files/en-us/web/api/rtcpeerconnection/createdatachannel/index.md
- [x] files/en-us/web/api/rtcpeerconnection/addicecandidate/index.md
- [x] files/en-us/web/api/rtcpeerconnection/removetrack/index.md
- [x] files/en-us/web/api/rtcpeerconnection/createoffer/index.md
- [x] files/en-us/web/api/rtcpeerconnection/addtrack/index.md
- [x] files/en-us/web/api/rtcpeerconnection/addstream/index.md
- [x] files/en-us/web/api/rtcpeerconnection/setconfiguration/index.md
- [x] files/en-us/web/api/htmlinputelement/stepup/index.md
- [x] files/en-us/web/api/htmlinputelement/stepdown/index.md
- [x] files/en-us/web/api/audiobuffersourcenode/start/index.md
- [x] files/en-us/web/api/mediastreamaudiosourcenode/mediastreamaudiosourcenode/index.md
- [x] files/en-us/web/api/mediastreamaudiosourcenode/index.md
- [x] files/en-us/web/api/rtcpeerconnection/setlocaldescription/index.md
- [x] files/en-us/web/api/rtcpeerconnection/setidentityprovider/index.md
- [x] files/en-us/web/api/rtcpeerconnection/removestream/index.md
- [x] files/en-us/web/api/serialport/open/index.md
- [x] files/en-us/web/api/serialport/setsignals/index.md
- [x] files/en-us/web/api/serialport/getsignals/index.md
- [x] files/en-us/web/api/mediarecordererrorevent/error/index.md
- [x] files/en-us/web/api/dommatrixreadonly/index.md
- [x] files/en-us/web/api/idbindex/opencursor/index.md
- [x] files/en-us/web/api/idbindex/get/index.md
- [x] files/en-us/web/api/idbindex/getkey/index.md
- [x] files/en-us/web/api/idbindex/openkeycursor/index.md
- [x] files/en-us/web/api/idbindex/name/index.md
- [x] files/en-us/web/api/idbindex/getall/index.md
- [x] files/en-us/web/api/idbindex/count/index.md
- [x] files/en-us/web/api/idbindex/getallkeys/index.md
- [x] files/en-us/web/api/offlineaudiocontext/suspend/index.md
- [x] files/en-us/web/api/offlineaudiocontext/resume/index.md
- [x] files/en-us/web/api/mediasource/addsourcebuffer/index.md
- [x] files/en-us/web/api/mediasource/duration/index.md
- [x] files/en-us/web/api/mediasource/endofstream/index.md
- [x] files/en-us/web/api/xrsystem/requestsession/index.md
- [x] files/en-us/web/api/oscillatornode/type/index.md
- [ ] files/en-us/web/api/sourcebuffer/trackdefaults/index.md
- [x] files/en-us/web/api/sourcebuffer/appendwindowstart/index.md
- [x] files/en-us/web/api/sourcebuffer/appendwindowend/index.md
- [x] files/en-us/web/api/sourcebuffer/changetype/index.md
- [x] files/en-us/web/api/sourcebuffer/timestampoffset/index.md
- [x] files/en-us/web/api/sourcebuffer/mode/index.md
- [x] files/en-us/web/api/sourcebuffer/abort/index.md
- [x] files/en-us/web/api/idbtransaction/commit/index.md
- [x] files/en-us/web/api/idbtransaction/objectstore/index.md
- [x] files/en-us/web/api/idbtransaction/abort/index.md
- [x] files/en-us/web/api/remoteplayback/watchavailability/index.md
- [x] files/en-us/web/api/remoteplayback/prompt/index.md
- [x] files/en-us/web/api/remoteplayback/cancelwatchavailability/index.md
- [x] files/en-us/web/api/fetchevent/respondwith/index.md
- [x] files/en-us/web/api/rtcrtpsender/setstreams/index.md
- [x] files/en-us/web/api/rtcrtpsender/setparameters/index.md
- [ ] files/en-us/web/api/rtcrtpsender/replacetrack/index.md
- [ ] files/en-us/web/api/baseaudiocontext/createiirfilter/index.md
- [x] files/en-us/web/api/filesystemwritablefilestream/write/index.md
- [ ] files/en-us/web/api/mediastreamtrackaudiosourcenode/mediastreamtrackaudiosourcenode/index.md
- [x] files/en-us/web/api/rtcdatachannel/send/index.md
- [x] files/en-us/web/api/cssstylesheet/insertrule/index.md
- [ ] files/en-us/web/api/element/attachshadow/index.md
- [ ] files/en-us/web/api/domerror/index.md
- [x] files/en-us/web/api/contactsmanager/select/index.md
- [x] files/en-us/web/api/cssgroupingrule/insertrule/index.md
- [ ] files/en-us/web/api/cssgroupingrule/deleterule/index.md
- [x] files/en-us/web/api/xrframe/getviewerpose/index.md
- [x] files/en-us/web/api/xrframe/getdepthinformation/index.md
- [x] files/en-us/web/api/animation/pause/index.md
- [x] files/en-us/web/api/periodicsyncmanager/register/index.md
- [x] files/en-us/web/api/domexception/index.md
- [x] files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.md
- [ ] files/en-us/web/api/extendableevent/index.md
- [x] files/en-us/web/api/xmlhttprequest/responsetext/index.md
- [x] files/en-us/web/api/xmlhttprequest/send/index.md
- [x] files/en-us/web/api/xmlhttprequest/responsexml/index.md
- [x] files/en-us/web/api/rtcdtmfsender/insertdtmf/index.md
- [x] files/en-us/web/api/idbcursor/continue/index.md
- [x] files/en-us/web/api/rtcrtptransceiver/direction/index.md
- [x] files/en-us/web/api/rtcrtptransceiver/stop/index.md
- [x] files/en-us/web/api/hiddevice/open/index.md
- [x] files/en-us/web/api/audioparam/setvaluecurveattime/index.md
- [x] files/en-us/web/api/webglrenderingcontext/makexrcompatible/index.md
- [x] files/en-us/web/api/xrwebgllayer/getviewport/index.md
- [x] files/en-us/web/api/xrwebgllayer/xrwebgllayer/index.md
- [x] files/en-us/web/api/idbcursor/continueprimarykey/index.md
- [x] files/en-us/web/api/idbcursor/advance/index.md
- [x] files/en-us/web/api/idbcursor/delete/index.md
- [x] files/en-us/web/api/idbcursor/update/index.md
- [x] files/en-us/web/api/ndefreader/scan/index.md
- [x] files/en-us/web/api/htmldialogelement/showmodal/index.md
- [x] files/en-us/web/api/audiodata/clone/index.md
- [x] files/en-us/web/api/audiodata/copyto/index.md
- [x] files/en-us/web/api/paymentresponse/complete/index.md
- [x] files/en-us/web/api/texttrack/addcue/index.md
- [x] files/en-us/web/api/videoencoder/configure/index.md
- [x] files/en-us/web/api/videoencoder/encode/index.md
- [x] files/en-us/web/api/videoencoder/flush/index.md
- [ ] files/en-us/web/api/webrtc_api/perfect_negotiation/index.md
- [x] files/en-us/web/api/mediadevices/selectaudiooutput/index.md
- [x] files/en-us/web/api/mediadevices/getdisplaymedia/index.md
- [x] files/en-us/web/api/videoframe/clone/index.md
- [x] files/en-us/web/api/midioutput/send/index.md
- [x] files/en-us/web/api/backgroundfetchregistration/matchall/index.md
- [x] files/en-us/web/api/idbobjectstore/openkeycursor/index.md
- [x] files/en-us/web/api/idbobjectstore/opencursor/index.md
- [x] files/en-us/web/api/idbobjectstore/getkey/index.md
- [x] files/en-us/web/api/idbobjectstore/getall/index.md
- [x] files/en-us/web/api/idbobjectstore/get/index.md
- [x] files/en-us/web/api/idbobjectstore/deleteindex/index.md
- [x] files/en-us/web/api/idbobjectstore/name/index.md
- [x] files/en-us/web/api/idbobjectstore/index/index.md
- [x] files/en-us/web/api/idbobjectstore/createindex/index.md
- [x] files/en-us/web/api/idbobjectstore/count/index.md
- [x] files/en-us/web/api/idbobjectstore/add/index.md
- [x] files/en-us/web/api/idbobjectstore/getallkeys/index.md
- [x] files/en-us/web/api/idbobjectstore/put/index.md
- [x] files/en-us/web/api/idbobjectstore/delete/index.md
- [x] files/en-us/web/api/backgroundfetchregistration/match/index.md
- [x] files/en-us/web/api/xmlserializer/serializetostring/index.md
- [x] files/en-us/web/api/videodecoder/decode/index.md
- [x] files/en-us/web/api/videodecoder/configure/index.md
- [x] files/en-us/web/api/videodecoder/flush/index.md
- [x] files/en-us/web/api/xrmediabinding/xrmediabinding/index.md
- [x] files/en-us/web/api/merchantvalidationevent/complete/index.md
- [ ] files/en-us/mozilla/firefox/releases/43/index.html
- [ ] files/en-us/mozilla/firefox/releases/69/index.html

If you want to work on this, and are not used to the format, feel free to make a PR for one of the files, and we'll review it. Also, you don't need to do 1 big PR but can break this down in pieces (although, here, larger PRs are easier to review).

Thanks a lot for any help here.

**Comment by hamishwillee** [comment]
Me either FYI @teoli2003

**Comment by dipikabh** [comment]
With this last PR, I have completed looking at all the files listed in this issue and fixed the required ones.

**Comment by sideshowbarker** [comment]
@teoli2003 Do we want to still keep this issue open?

**Comment by teoli2003** [comment]
Thank you, I forgot this one. Yes, we can close it.
