### ISSUE TITLE
HTTP caching: introduce concept of "cache keys"

### ISSUE THREAD

**Issue by BrittHuys** [mdn/content#9484]
## What is the new suggestion?
I suggest to add some more information about "cache keys" before referring to it for the first time in the ## Targets of caching operations section of this file: https://github.com/mdn/content/edit/main/files/en-us/web/http/caching/index.md / https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

## Why is it important or useful?
It's a bit confusing to a reader who does not have much knowledge about caching if you introduce a new concept out of the blue in a doc that is meant to explain "caching" to the reader.

**Comment by Josh-Cena** [comment]
The referenced section no longer exists after #16009, so the doc is self-contained now.
