### ISSUE TITLE
Issue with "ARIA: tab role": …

### ISSUE THREAD

**Issue by jkarttunen** [mdn/content#949]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role

#### What information was incorrect, unhelpful, or incomplete?

Broken links to tablist and tabpanel

#### Specific section or headline?
First sentence

#### What did you expect to see?
Working links

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/roles/tab_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/accessibility/aria/roles/tab_role/index.html
* Report started: 2021-01-05T07:30:47.857Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for catching this and reporting it. I’ve opened https://github.com/mdn/content/pull/950 with a fix.
