### ISSUE TITLE
Issue with "browserSettings.ftpProtocolEnabled": (short summary here please)

### ISSUE THREAD

**Issue by simoadam44** [mdn/content#9506]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/ftpProtocolEnabled

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/browsersettings/ftpprotocolenabled`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/ftpProtocolEnabled
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/browsersettings/ftpprotocolenabled/index.html
* Last commit: https://github.com/mdn/content/commit/eb5d682cbe5664b933e793ff6434fb252686f3c3
* Document last modified: 2021-05-31T17:26:19.000Z

</details>

**Comment by hamishwillee** [comment]
Closing - no information about a problem to resolve has been added.
