### ISSUE TITLE
Issue with "<track>: The Embed Text Track element": crossorigin attribute required even when track source is on the same website as video source

### ISSUE THREAD

**Issue by teodorcalin** [mdn/content#9526]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track

This page does not discuss the "Security Error" raised by Mozilla Firefox  (e.g. version 92.0.1)
about loading the WEBVTT file - whether its URL is local or absolute.

I would expect to see information on any potential security issues with the `<track>`  tag and how to avoid them.

Tested in codepen.io and with `file:///` the following code:
```
<video controls src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/10558/moonwalk.480p.h264.mp4">
  
  <track src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/10558/moonwalk.vtt"
         kind="captions"
         label="English"
         srclang="en"
         default>
</video>
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/track`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/track/index.md
* Last commit: https://github.com/mdn/content/commit/bbaf3676373af6f6ce9817141d25fbf7ba88ef8d
* Document last modified: 2021-09-29T14:51:58.000Z

</details>

**Comment by teodorcalin** [comment]
Ssolved this by adding the `crossorigin` attribute to the parent `<video>` tag, but this is not intuitive. Even when the track source website is the same as video source website, `crossorigin` is required. An example and explanation would be welcome.

**Comment by ddbeck** [comment]
@teodorcalin Thanks for reporting this. It appears that the page does mention this, in [the bit about the `src` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track#attr-src). I think this covers the issue you've raised, but if it doesn't, please update here and we can figure out next steps. Thank you again!
