### ISSUE TITLE
Content bug: Broken link

### ISSUE THREAD

**Issue by becarpenter** [mdn/content#9546]
## What page(s) did you find the problem on?
Firefox Source Code Directory Structure
https://firefox-source-docs.mozilla.org/contributing/directory_structure.html

## Specific page section or heading?

nsprpub

## What is the problem?

There is a link to "Netscape Portable Runtime" at https://www.mozilla.org/projects/nspr/

That's a broken link.

**Comment by becarpenter** [comment]
And another one in the same page, under "netwerk" there is a broken link to https://developer.mozilla.org/en-US/docs/Necko

**Comment by hamishwillee** [comment]
Thanks @becarpenter , MDN used to host these projects but we don't any more. These are not MDN bugs - they are bugs with the Firefox docs.

Can you please re-raise the issues through the forum suggested in those docs: https://firefox-source-docs.mozilla.org/contributing/contributing_to_mozilla.html#contributing-to-mozilla-projects ?
