### ISSUE TITLE
Issue with "@property": … typo

### ISSUE THREAD

**Issue by bubblobill** [mdn/content#955]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@property#Syntax

#### What information was incorrect, unhelpful, or incomplete?
\@property **--propery-name** {
  syntax: '<color>';
  inherits: false;
  initial-value: #c0ffee;
}

#### Specific section or headline?
Syntax

#### What did you expect to see?
+t
\@property **--property-name** {
  syntax: '<color>';
  inherits: false;
  initial-value: #c0ffee;
}

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/@property`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@property
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/@property/index.html
* Report started: 2021-01-05T10:42:28.045Z

</details>

**Comment by chrisdavidmills** [comment]
Fixed by https://github.com/mdn/content/commit/68e78f4cd6ac4537ebf530c81c0b000a20e7f94c; thanks for reporting!
