### ISSUE TITLE
<template> element: missing shadowroot attribute

### ISSUE THREAD

**Issue by felix9** [mdn/content#9559]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

#### What information was incorrect, unhelpful, or incomplete?

In some browsers, the template element has a shadowroot attribute, as described here https://github.com/mfreed7/declarative-shadow-dom/blob/master/README.md

#### Specific section or headline?

Attributes, Browser compatibility

#### What did you expect to see?

A description of the "shadowroot" attribute, and a row for it in the browser compatibility table.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/template`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/template/index.md
* Last commit: https://github.com/mdn/content/commit/775662998e66813a612e3ff27e02f2ada867bc17
* Document last modified: 2021-10-03T00:01:51.000Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for raising this — I’ve opened #20424 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.
