### ISSUE TITLE
Issue with "File.lastModifiedDate": (short summary here please)

### ISSUE THREAD

**Issue by garywheeler69** [mdn/content#9583]
[MDN](url) URL: https://developer.mozilla.org/en-US/docs/Web/API/File/lastModifiedDate

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/file/lastmodifieddate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File/lastModifiedDate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/file/lastmodifieddate/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by ddbeck** [comment]
It looks like the original reporter isn't coming back to this one. I'll close this up.
