### ISSUE TITLE
CSP script-src link in sidebar duplicated

### ISSUE THREAD

**Issue by aph3rson** [mdn/content#9592]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

This appears to be a sidebar-specific thing, though - not seeing anything in the source for the page other than loading the default sidebar.

## Specific page section or heading?

Sidebar, `CSP Directives` section.

## What is the problem?

The `script-src` link in the sidebar is duplicated. Both lead to the exact same page.
![Selection_329](https://user-images.githubusercontent.com/838916/136107185-3fdc7057-13c6-4efa-987b-d673cf3efe72.png)

## What did you expect to see?

Single link (though you probably knew that :wink:).

## Did you test this? If so, how?

Same problem from other CSP directive pages - seems to only impact the `script-src` page, though.

**Comment by ddbeck** [comment]
I'm not sure what caused this in the first place but I can't reproduce it now. Since this seems to be resolved, I'll close this issue, but feel free to follow up if I've missed something. Thanks!
