### ISSUE TITLE
Issue with "Remainder (%)": …

### ISSUE THREAD

**Issue by meatnordrink** [mdn/content#961]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder

#### What information was incorrect, unhelpful, or incomplete?

"Note that while in most languages, ‘%’ is a remainder operator, in some (e.g. Python, Perl) it is a modulo operator. For positive values, the two are equivalent, but when the dividend and divisor are of different signs, they give different results. To obtain a modulo in JavaScript"

#### Specific section or headline?
Remainder (%)

#### What did you expect to see?

Instead of: "For positive values, the two are equivalent, but when the dividend and divisor are of different signs, they give different results."
It should say: "For two values of the same sign, the two are equivalent, but when the dividend and divisor are of different signs, they give different results."

It would also be helpful for some explanation of what the actual difference between the remainder and modulus *are,* or at least a link to one. This is the best explanation for the difference, in JS, that I've found: https://2ality.com/2019/08/remainder-vs-modulo.html

#### Did you test this? If so, how?

Yes. I ran a number of manual modulus and remainder calculations in Node v14, and confirmed that modulus and remainder produce the same results if both operands are negative.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/remainder`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/operators/remainder/index.html
* Report started: 2021-01-05T14:45:59.304Z

</details>

**Comment by kocvrek** [comment]
I would like to work on this issue.

**Comment by hamishwillee** [comment]
@kocvrek Thanks very much - that would be great! I agree with both points above - the text and the need to link to a good explanation. The one provided is good, but you could additionally link to https://rob.conery.io/2018/08/21/mod-and-remainder-are-not-the-same/

**Comment by sideshowbarker** [comment]
@kocvrek Do you still plan to work on this issue?

**Comment by kocvrek** [comment]
@sideshowbarker yes! I've started working on this a while back just haven't had the time to finish. I need a bit more time if that's all right.

**Comment by sideshowbarker** [comment]
@kocvrek sure, that’s fine
