### ISSUE TITLE
Content bug: Add reason to the section: "service worker failing to register"

### ISSUE THREAD

**Issue by mireille-raad** [mdn/content#9679]
## What page(s) did you find the problem on?

Using Service Workers > Why is my service worker failing to register?

https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#why_is_my_service_worker_failing_to_register

## Specific page section or heading?
Why is my service worker failing to register?

## What is the problem?

There are more reasons that service workers could fail to register. I've tested:

In Firefox:
- When history is off. 
- When I have selected `Delete cookies and site data when Firefox is closed` (unless I add the url or localhost to exception list)

In Chrome:
- When I selected `Block all cookies (not recommended)`

## What did you expect to see?
I expected to see these reasons listed -- especially the one about "delete cookies". It might be frustrating to know why SW is not working especially when it is the settings of the browser, not the code.

## Did you test this? If so, how?

On Chrome and Firefox, by changing the settings and restarting the browsers, registering/unregistering the service worker.

## Solution

I can submit a PR adding those to the list.

**Comment by mireille-raad** [comment]
Do you want me to submit a PR to fix this? (it seems this issue got triaged and there is someone else who struggled with it ;p)

**Comment by SphinxKnight** [comment]
I hope #22682 will help fix this. 
Also, long time no speak @trollepierre :)

**Comment by Josh-Cena** [comment]
This seems to be fixed by #22682; all points mentioned here are incorporated in that PR.
