### ISSUE TITLE
Issue with "Global object": add example for differing behavior of `let` and `const`

### ISSUE THREAD

**Issue by ElijahLynn** [mdn/content#9684]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Global_object

#### What information was incorrect, unhelpful, or incomplete?

After a 5 year hiatus from JS, coming from the pre ES5 world, where `var` was the way...

I was looking for what the behavior is of `const` and `let` as when I create a variable with them, they don't go to the global `window` object. I think this article would be a good place to put examples of the different behavior of those, or link off to something that does. 

#### What did you expect to see?

In the console:
`const bar = 'bar'` 
`window.bar` = undefined

Where does the variable go? 

I know I can access in the console local scope with simply `bar` but is it attached to any other object? 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/global_object`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Global_object
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/global_object/index.md
* Last commit: https://github.com/mdn/content/commit/4a9f9d2e9c1811ce3519a7061e906db9200a5e97
* Document last modified: 2021-10-08T00:24:32.000Z

</details>

**Comment by hamishwillee** [comment]
FWIW I disagree with updating this doc for this reason. `var` is mentioned (and linked) because it is attached to the global object. `let`, `const`, and the thousands of other non-global objects are not mentioned because they are not attached to the global object.
