### ISSUE TITLE
Issue with "Test your skills: Object basics": (editing the codes on provided windows does not give desired output)

### ISSUE THREAD

**Issue by basushaunak** [mdn/content#9690]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Test_your_skills:_Object_basics

#### What information was incorrect, unhelpful, or incomplete?
codes do not run on the MDN site

#### Specific section or headline?
None of the codes seem to run on the MDN site (live editor)

#### What did you expect to see?
Code output

#### Did you test this? If so, how?
Tried running exactly the same code on Firefox Dev console - it seems to work fine.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/objects/test_your_skills_colon__object_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Test_your_skills:_Object_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/test_your_skills_colon__object_basics/index.html
* Last commit: https://github.com/mdn/content/commit/d4e436594b6c72d99e9b796235e46c6c7c6b6c6e
* Document last modified: 2021-09-30T23:28:46.000Z

</details>

**Comment by AnilSeervi** [comment]
They are working fine for me.
It could probably be one(or some) of your extensions.
