### ISSUE TITLE
Issue with "shape-outside": shape-outside: path doesn't seem a valid value

### ISSUE THREAD

**Issue by Terbiy** [mdn/content#9703]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside

#### What information was incorrect, unhelpful, or incomplete?
`shape-outside: path('M0.5,1 C0.5,1,0,0.7,0,0.3 A0.25,0.25,1,1,1,0.5,0.3 A0.25,0.25,1,1,1,1,0.3 C1,0.7,0.5,1,0.5,1 Z');` didn't produce any effect when I tried to use it.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside#syntax

#### What did you expect to see?
I expected to see a working example or the absence of `shape-outside: path`.

#### Did you test this? If so, how?
I tried to search for an example on the Internet, on GitHub, and finally, I tried to use in-browsers autocomplete to discover `shape-outside: path`. I failed to find it in Firefox and Chrome.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/shape-outside`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/shape-outside/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by wbamberg** [comment]
I don't think we should remove `path()` from the page. It's a legitimate part of the specification that AFAIK browsers are working on supporting.

The `path()` syntax for `shape-outside` is part of the [`<basic-shape>` type](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside#values), and the page for `<basic-shape>` describes `path()` as only supported behind a pref: https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape#browser_compatibility.

It's confusing that the [BCD for `shape-outside`](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside#browser_compatibility) lists some value of `<basic-shape>` (e.g. `circle()`, `inset()`) but not others (such as `path()`).

It might be more consistent for the `shape-outside` BCD to have subfeatures that map to the values listed, i.e. `<shape-box>`, `<basic-shape>`, `<image>`.

There's a bit of a policy question here we have come up against before: should we record BCD for data types in themselves, or only for the places that use the data types?

**Comment by dipikabh** [comment]
Hello @Terbiy, the examples for `path()` are documented on the [path()](https://developer.mozilla.org/en-US/docs/Web/CSS/path#examples) page (using `offset-path: path()`). 

In the [browser compat table](https://developer.mozilla.org/en-US/docs/Web/CSS/path#browser_compatibility), for both Firefox and Chrome, it is noted that `path()` is supported on the `offset-path` property (and not on the `shape-outside` property).
