### ISSUE TITLE
Settings: changing the devtools language is undocumented

### ISSUE THREAD

**Issue by kklepper** [mdn/content#9706]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Settings

#### What information was incorrect, unhelpful, or incomplete?

No hint how to change language - my system language is de, firefox language is en-us, developer tools language is de. 

If I want to communicate internationally it is unhelpful to cite German messages. That's why I want English messages. How can I get them?

#### What did you expect to see?

Menu items and error messages in English.

#### Did you test this? If so, how?

Searched all over and googled, no hint anywhere.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/settings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Settings
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/settings/index.html
* Last commit: https://github.com/mdn/content/commit/5d8fbcb7e86afaae9504eda006c8ced7396b1d34
* Document last modified: 2021-04-28T23:00:48.000Z

</details>

**Comment by himanshugarg** [comment]
Thanks for reporting the issue. I was able to change  language (of Firefox and Developer Tools both together) from Extras > Einstellungen > "Sprache"

![grafik](https://user-images.githubusercontent.com/2392803/136714615-d3e4bb7a-b170-4eaa-8333-9efd8da9df6b.png)

Is this what you want documented? Or did you mean something else?

**Comment by kklepper** [comment]
>Is this what you want documented? Or did you mean something else?

Exactly. Firefox has been set to en-us, developer tools is unaffected:

![image](https://user-images.githubusercontent.com/6130319/136763617-d526cda1-fa46-410c-b16e-1219f0bbaa74.png)

**Comment by ddbeck** [comment]
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!
