### ISSUE TITLE
Issue with "String.prototype.includes()": (short summary here please)

### ISSUE THREAD

**Issue by qiudaoermu** [mdn/content#9716]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

### includes Polyfill
```
if (!String.prototype.includes) {
  String.prototype.includes = function(search, start) {
    'use strict';

   if (search instanceof RegExp) {
       **throw TypeError('first argument must not be a RegExp');** 
    } 
    if (start === undefined) { start = 0; }
    return this.indexOf(search, start) !== -1;
  };
}
```
why  throw TypeError('first argument must not be a RegExp')?

#### What did you expect to see?
 the search is a string , search instanceof String

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/includes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/includes/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by AnilSeervi** [comment]
> thanks!

You can close the issue if you're clear with it :)
