### ISSUE TITLE
Issue with "Array.prototype.fill()": Example for random values is wrong

### ISSUE THREAD

**Issue by davobutt** [mdn/content#9732]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

#### What information was incorrect, unhelpful, or incomplete?
The example labelled : "This example shows how to populate an array with random values. The end value does not have to be specified." doesn't fill the array with "Random" values;

#### Specific section or headline?
Using fill() to populate an Empty Array

#### What did you expect to see?
Either an example actually showing random filling, or something else, it isn't clear what the intention is. Perhaps the author meant specific, as opposed to random? 

#### Did you test this? If so, how?
`> Array(5).fill("girl",0)`
`[ 'girl', 'girl', 'girl', 'girl', 'girl' ]`

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/fill`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/fill/index.md
* Last commit: https://github.com/mdn/content/commit/16ea72ef891dc1340f2992d82d6204822562ef7d
* Document last modified: 2021-10-04T21:51:12.000Z

</details>

**Comment by hamishwillee** [comment]
Thanks - you're right. Fixed by #9738
