### ISSUE TITLE
Content bug: Speculative parsing doc not redirected

### ISSUE THREAD

**Issue by hsivonen** [mdn/content#9734]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing

## What is the problem?

The content has moved to https://developer.mozilla.org/en-US/docs/Glossary/speculative_parsing but the above page doesn't redirect despite the above URL being an in-product URL baked into many releases of Firefox.

## What did you expect to see?

Expected https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing to redirect to https://developer.mozilla.org/en-US/docs/Glossary/speculative_parsing

## Did you test this? If so, how?

Tried to navigate to https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing

You can see the URL baked into Firefox UI strings at https://searchfox.org/mozilla-central/rev/2c4b830b924f42283632b70f39a60fd36433dd4d/dom/locales/en-US/chrome/dom/dom.properties#26

**Comment by escattone** [comment]
This is redirecting properly now. Sorry for the delay.

**Comment by hsivonen** [comment]
Still not redirecting for me. I even tried private browsing mode in case the old page was cached on the browser side.

**Comment by ddbeck** [comment]
@hsivonen Could you try again tomorrow? The CDN cache is usually 24 hours. I don't know exactly when Ryan fixed this, but it's possible your nearest server is still serving from cache.

When I tried it just now, I got a cache miss and the redirect worked.

<details>

<summary><code>$ curl -I https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing</code></summary>

```sh
$ curl -I https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing
HTTP/2 301 
content-length: 0
server: CloudFront
date: Tue, 02 Nov 2021 10:11:24 GMT
location: /en-US/docs/Glossary/speculative_parsing
cache-control: max-age=2592000,public
x-cache: Miss from cloudfront
via: 1.1 024e0eb7c8dbc0f1008d8bc14f1acebf.cloudfront.net (CloudFront)
x-amz-cf-pop: LHR61-C1
x-amz-cf-id: --2RCk1Kbg5PfYaJGUDJhGoX7w10x0qXYE-MR07gH6UVJ_1Z93NLmQ==
```

</details>

**Comment by escattone** [comment]
@hsivonen Can you try the `curl` command that @ddbeck shows above? FYI, I also expliciitly cleared the CDN cache for `/en/Optimizing_Your_Pages_for_Speculative_Parsing` just to be safe.

**Comment by hsivonen** [comment]
The redirect works now. Thank you!
