### ISSUE TITLE
Issue with "image-set()": image formats example uses unnecessary `-webkit` property value pair

### ISSUE THREAD

**Issue by jsnkuhn** [mdn/content#9751]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set()

#### What information was incorrect, unhelpful, or incomplete?

image formats example includes a `-webkit` fallback but there is no `-webkit` implimentation of this property that includes the `type()` function. Therefore, this property/value pair will never be used by any browser.

#### Specific section or headline?
Using image-set() to provide alternative image formats

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/image/image-set()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/image/image-set()/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by AnilSeervi** [comment]
Yes, the `type()` function isn't supported by any browser even if the property is prefixed.
Other browsers only seem to be supporting `url()` for now.

**Comment by estelle** [comment]
These examples are on mdn/css-examples, not in mdn/content
