### ISSUE TITLE
Issue with "Your first extension": missing videos

### ISSUE THREAD

**Issue by njames** [mdn/content#9790]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

#### What information was incorrect, unhelpful, or incomplete?
The videos were missing under the heading `try it out`

#### Specific section or headline?
Three videos were missing under `try it out`

#### What did you expect to see?
I expected to see the normal thumbnail for a video

#### Did you test this? If so, how?
I tried to search for the videos on youtube but guess they are unlisted  - there were many other videos from other channels about creating an extension

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/your_first_webextension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/your_first_webextension/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by hfiguiere** [comment]
Videos are actually private. Right click, copy URL, paste in URL bar to go to the video on YouTube.
