### ISSUE TITLE
AudioWorklet: missing secure contexts rationale

### ISSUE THREAD

**Issue by pinobatch** [mdn/content#9808]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioWorklet

#### What information was incorrect, unhelpful, or incomplete?
The hatnote fails to hint at _why_ `AudioWorklet` is restricted to secure contexts.

#### Specific section or headline?
Hatnote

#### What did you expect to see?
"secure" and "because" in the same sentence.

The hatnote on `AudioWorklet` links to [Secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), which states that affected APIs are "powerful APIs that could further compromise the victim of an attack." I expected to see, either on the `AudioWorklet` page or on the "Secure contexts" page, some sort of explanation, or a link to an explanation, of what problems could be caused if browsers were to allow use of `AudioWorklet` over cleartext HTTP. One context that I have run into that is hard to make secure is between a web server on a desktop computer on a home LAN and a web browser on a mobile device on the same LAN.

#### Did you test this? If so, how?
No testing was performed inside any web browser.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/audioworklet`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioWorklet
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/audioworklet/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by sideshowbarker** [comment]
It’s not really in scope for MDN to document, for each feature where something requires a secure context, why that feature requires a secure context. “Why” questions of that kind are best addressed to the editors/group who wrote the spec. So https://github.com/WebAudio/web-audio-api/issues is the right place to ask.

So I’m closing this. But I guess it’s also worth having some info in the record here, so I’m also Cc’ing @padenot (the spec editor) so to give him a chance to comment here too.
