### ISSUE TITLE
Issue with "Date() constructor": Is new Date(Date) acceptable or documented?

### ISSUE THREAD

**Issue by manngo** [mdn/content#9830]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

#### What information was incorrect, unhelpful, or incomplete?

Some discussions (on SO, for example) suggest cloning a date by using the original date in the constructor:

```js
var date = new Date();
var dateCopy = new Date(date);
```

This works, but the discussion suggests that it may be a bit dubious.

My guess is that using the `Date` in the constructor results in either the `toString()` or the `valueOf()` method being called, and that value being used in the constructor. If it’s the `toString()` method, then I understand that there is no guaranteed consistency between browsers (or other JavaScript engines, for that matter).

However all of that discussions is some years old.

The question is:

- Is a `Date` object a valid argument for the constructor?
- If not, is it true that the `toString()` or the `valueOf()` method is being called, and, if so, which one?
- In either case, is it safe to use a `Date` object?

Since using a `Date` object was literally the first thing I thought of, I thought it should be mentioned in the documentation. Once I know the answers, I would be happy to write something myself.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/date/date`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/date/index.md
* Last commit: https://github.com/mdn/content/commit/4ef854f8698c75c8e248742e3c22be3f4ac84a9e
* Document last modified: 2021-08-04T18:33:27.000Z

</details>

**Comment by wbamberg** [comment]
It looks to me like this case is explicitly covered in section 21.4.2.1, step 4(b) in https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date-constructor:

> if numberOfArgs = 1, then
>   ...
>    b. If Type(value) is Object and value has a [[DateValue]] internal slot, then
>        i. Let tv be ! thisTimeValue(value).

...which suggests that `valueOf()` will be used in this case. Does that seem right to you too?

**Comment by manngo** [comment]
Yes, that’s how I interpret that section. Well done, for finding it. This would suggest that a Date object is a valid argument for the constructor.

Can we add this to the documentation?

**Comment by manngo** [comment]
I think I have made the changes. This is my first pull request, so I’m not sure how it’s going.

**Comment by manngo** [comment]
> > Can we add this to the documentation?
> 
> Absolutely I think we should. Thanks for raising this issue! As you said in the OP, do you want to do this?

Thanks for your comments. I have now added this to the documentation.
