### ISSUE TITLE
Issue with "::marker": `content` not supported in Safari

### ISSUE THREAD

**Issue by tedw** [mdn/content#984]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::marker

#### What information was incorrect, unhelpful, or incomplete?
The `content` property isn’t supported in Safari or iOS Safari yet:
https://bugs.webkit.org/show_bug.cgi?id=204163

#### Specific section or headline?
“Browser compatibility,” and might be worth noting in the “Allowable properties” section as well.

#### What did you expect to see?
A note about Safari not supporting `content`.

#### Did you test this? If so, how?
Yes, I tested this in Safari and iOS Safari before finding the webkit bug ticket (https://bugs.webkit.org/show_bug.cgi?id=204163).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_doublecolon_marker`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::marker
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/_doublecolon_marker/index.html
* Report started: 2021-01-05T22:12:36.365Z

</details>

**Comment by chrisdavidmills** [comment]
Confirmed that there is an issue here. I didn't test _everything_, but I did do a test with the following rule:

```
ul li::marker {
  color: red;
  font-size: 1.5em;
  content: "@b-";
  direction: rtl;
}
```

And the last two declarations work in Firefox/Chromiums but not Safari.

I'd suggest the best course of action would be to update the Safari/iOS [data for this pseudo](https://github.com/mdn/browser-compat-data/blob/master/css/selectors/marker.json) to mark it as partial support, and add a note saying that only `color` and 'font-size' are supported.
