### ISSUE TITLE
Issue with "Test your skills: Arrays": (Array 2 Interactive Editor flagging correct solution)

### ISSUE THREAD

**Issue by ahmed-alimi** [mdn/content#9856]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Arrays

**#### What information was incorrect, unhelpful, or incomplete?**

The Interactive editor is generating a bug for a correct solution. The same code produced desired result in the developer console:
`let myString = 'Ryu+Ken+Chun-Li+Cammy+Guile+Sakura+Sagat+Juri';
let myArray = myString.split('+');
`
**#### Specific section or headline?**
Array 2 task

**#### What did you expect to see?**
That the solution passed the test.

**#### Did you test this? If so, how?**
Tested the same solution in chrome web developer tool:
`let myString = 'Ryu+Ken+Chun-Li+Cammy+Guile+Sakura+Sagat+Juri';
let myArray = myString.split('+');
myArray;
// Returned Array Below:
(8) ['Ryu', 'Ken', 'Chun-Li', 'Cammy', 'Guile', 'Sakura', 'Sagat', 'Juri']`

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/test_your_skills_colon__arrays`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Arrays
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/test_your_skills_colon__arrays/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by AnilSeervi** [comment]
Can you elaborate on the bug you are getting cuz I'm getting the proper output?

![image](https://user-images.githubusercontent.com/61609033/137587539-b55c8e86-170c-4aed-8492-27e8c3c4351c.png)

**Comment by ahmed-alimi** [comment]
> Can you elaborate on the bug you are getting cuz I'm getting the proper output?
> 
> ![image](https://user-images.githubusercontent.com/61609033/137587539-b55c8e86-170c-4aed-8492-27e8c3c4351c.png)
I checked it again, and it seems to be working fine now, I will now close the issue. Thanks.
