### ISSUE TITLE
Issue with "Intercept HTTP requests": (short summary here please)

### ISSUE THREAD

**Issue by KirkH420** [mdn/content#9861]
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests

#### What information was incorrect, unhelpful, or incomplete?
Dead Youtube videos and I worked through every line of this example and it doesn't work at all. I think some of the links used in the examples are dead too.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/intercept_http_requests`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/intercept_http_requests/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by hamishwillee** [comment]
Yes, this also occurs on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

The web extension is not being installed. There appear to be a couple of bugs here, the most obvious one being that Firefox does not give you any indication that it has failed and why. There seem to be other things going on in https://bugzilla.mozilla.org/show_bug.cgi?id=1672859

@Rob--W I saw that you have been involved with these bugs - any hints on what I need to do - there are so many bugs on this and no summary "workaround to get it working".

**Comment by 14nd90** [comment]
This drove me crazy for a while; but has an easy fix. In the Browser Console (Ctrl + Shift + J), use the settings menu (top right) to check the option "Show Content Messages"

**Comment by hamishwillee** [comment]
Thanks @14nd90 - How the hell you found that I don't know! Even knowing it existed took me ages, because I **assumed** that the menu option must be on the "normal" console. As you see below, it is not. I'm going to raise a defect against FF.

![image](https://user-images.githubusercontent.com/5368500/140872454-602403ad-f899-4c73-9bb5-ff5e77a3dbd3.png)

**Comment by hamishwillee** [comment]
Partially fixed in https://github.com/mdn/content/pull/10557

That will make the first part work. I understand all this part of MDN will be reviewed and it makes sense that all be done together. I've just added enough to make the page usable.
