### ISSUE TITLE
"CSS Functional Notation": Missing grid functions

### ISSUE THREAD

**Issue by lemnis** [mdn/content#9884]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions

#### What information was incorrect, unhelpful, or incomplete?
I am missing the CSS Grid functions on the page.

#### What did you expect to see?
I expected [`minmax()`](https://developer.mozilla.org/en-US/docs/Web/CSS/minmax()), [`repeat()`](https://developer.mozilla.org/en-US/docs/Web/CSS/repeat()) and [`fit-content()`](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content()) to be listed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_functions`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_functions/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by NiedziolkaMichal** [comment]
It was fixed by [#11842](https://github.com/mdn/content/pull/11842)

**Comment by teoli2003** [comment]
Closing per comment.
