### ISSUE TITLE
"slot" attribute: no example

### ISSUE THREAD

**Issue by vanillajonathan** [mdn/content#9895]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/slot

#### What did you expect to see?
Some example code.

I know it links to the "[Using templates and slots](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots)" article, but that article only deals with slots using web components, not without web components.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/global_attributes/slot`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/slot
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/slot/index.md
* Last commit: https://github.com/mdn/content/commit/775662998e66813a612e3ff27e02f2ada867bc17
* Document last modified: 2021-10-03T00:01:51.000Z

</details>

**Comment by ddbeck** [comment]
> I was wondering if they could be used without web components too, and if so then how.

I think the answer to this question is no. I wouldn't be surprised if someone's using the `slot` attribute for some unusual purpose, but I doubt it's the sort of thing we'd document or encourage. It definitely seems to be intended for the shadow DOM and web components.

> Is the `slot` attribute a read-only attribute, or can I assign to it too? Is it a collection that I append to, do I assign a string or maybe a `HTMLElement`?

It's a little confusing, but that sort of thing is covered in the web API docs. See [the `Element.slot` page](https://developer.mozilla.org/en-US/docs/Web/API/Element/slot).

In general, I think the HTML attribute pages tend to be a bit thin. They often don't do much on their own, so there's not much to say about them, except to link off to other pages. See [the `class` page for comparison](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class).

I don't think there's much left to do here, so I'll close this issue. But I'll make a note of it, as I'm giving some thought to more consistent structures between pages and this structure in particular may merit some expansion or revision.

Thank you!

**Comment by vanillajonathan** [comment]
Alright.

You might want to add that it is intended for the shadow DOM and web components.
