### ISSUE TITLE
Issue with "Clear-Site-Data": seems to only work on secure context but not described

### ISSUE THREAD

**Issue by split-n** [mdn/content#991]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data

#### What information was incorrect, unhelpful, or incomplete?
Clear-Site-Data seems to only work on secure context, but not described on this page.

I found that from:  
https://stackoverflow.com/questions/61737455/expected-behavior-when-clear-site-data-header-is-set/61775745#comment109308738_61775745
https://source.chromium.org/chromium/chromium/src/+/master:content/browser/browsing_data/clear_site_data_handler.cc;l=168;drc=073e74ade285c0c22ef01bccdf260854d7b1aa85

It's hard to read the fact from W3C draft. https://www.w3.org/TR/clear-site-data/

#### What did you expect to see?
Describe it on the page.  

Possibly also should be listed on this page? https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts

#### Did you test this? If so, how?
Using Chrome 87.0.4280.88 and W3C demo

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/clear-site-data`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/http/headers/clear-site-data/index.html
* Report started: 2021-01-06T04:26:40.614Z

</details>

**Comment by hamishwillee** [comment]
Thanks, agree. This is not listed in the draft but it is clearly only available in secure contexts in FF [here](https://searchfox.org/mozilla-central/source/toolkit/components/clearsitedata/ClearSiteData.cpp#166) and the author of the spec wrote [this test code](https://github.com/w3c/webappsec-clear-site-data/tree/master/demo) which states **(NOTE: Clear-Site-Data only works on localhost and https **



Requires update to:
- [ ] [BCD](https://github.com/mdn/browser-compat-data/blob/master/http/headers/clear-site-data.json) to add `secure_context_required`
- [ ] [features_restricted_to_secure_contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts)

I don't think we need to note in the doc other than in the BCD. Note, probably should make sure all the other things listed in the restricted features have the correct BCD.

**Comment by hamishwillee** [comment]
OK, it went into BCD (but BCD has not yet gone live). In https://github.com/mdn/content/pull/2158 I have also added the Secure context header to the top of the page. 

I decided not to update "Features restricted to secure contexts". This header didn't feel like a "feature" per-se.
