### ISSUE TITLE
Notify me example button doesn't work

### ISSUE THREAD

**Issue by ygrigoriev** [mdn/content#994]
MDN URL: https://developer.mozilla.org/ru/docs/Web/API/notification

**What information was incorrect, unhelpful, or incomplete?**

`Notify me!` example button doesn't work. The reason for that is in the Chrome error message:
> Permission for the Notification API may no longer be requested from a cross-origin iframe. You should consider requesting permission from a top-level frame or opening a new window instead. See https://www.chromestatus.com/feature/6451284559265792 for more details.

**Specific section or headline?**

`Notify me!` button in the example section

**What did you expect to see?**

Working notification example

**Did you test this? If so, how?**

Pushed the button, debugged js

**Comment by chrisdavidmills** [comment]
Yup, the English page was updated to allow for this.

Unfortunatately, we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
