### ISSUE TITLE
Content suggestion: EyeDropper API

### ISSUE THREAD

**Issue by captainbrosset** [mdn/content#9955]
## What is the new suggestion?

I suggest documenting the new EyeDropper API.

## Why is it important or useful?

Many creative applications allow users to pick colors from parts of the app window or even from the entire screen, typically using a pipette metaphor (Photoshop, PowerPoint, ...).

People building a creative application with web technologies might want to provide a similar feature to their users.
However, doing this on the web until now was hard, if possible at all. There wasn’t a browser-supplied eyedropper tool that web apps can use for their own needs. The `input type=color` comes close, but is hard to style and it only has an eyedropper option on desktop chromium browsers.

The EyeDropper API fills this gap by bringing a new standard API for browsers to provide a simple eyedropper tool from a JS API.

This API is currently incubating, and has been implemented by Microsoft Edge in the Chromium engine. It is available in all chromium-based browsers as of Chrome/Edge 95 (unsure about other chromium browsers' version numbers).

* Original Edge explainer: https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/EyeDropper/explainer.md
* WICG spec: https://wicg.github.io/eyedropper-api/

While the API is new, it is already usable in chromium, and I think it should be documented.

**Comment by Rumyra** [comment]
@captainbrosset can this issue be closed with now the above pr has been merged?

**Comment by captainbrosset** [comment]
Yes this can be closed. Thank you!
