### ISSUE TITLE
Issue with "Base64": there is no `b64DecodeUnicode` to correspond to `b64EncodeUnicode`

### ISSUE THREAD

**Issue by JounQin** [mdn/content#9970]
MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Base64

#### What information was incorrect, unhelpful, or incomplete?

As title

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Glossary/Base64#solution_1_%E2%80%93_escaping_the_string_before_encoding_it

#### What did you expect to see?

A `b64DecodeUnicode` function

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/glossary/base64`
* MDN URL: https://developer.mozilla.org/en-US/docs/Glossary/Base64
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/glossary/base64/index.md
* Last commit: https://github.com/mdn/content/commit/4a9f9d2e9c1811ce3519a7061e906db9200a5e97
* Document last modified: 2021-10-08T00:24:32.000Z

</details>

**Comment by ddbeck** [comment]
Hi @JounQin, thanks for opening this issue. Can you elaborate on your expectations here? It's not clear to me what you mean by `b64DecodeUnicode` since that string doesn't appear in the page. Can you tell us more about what problem you're having with this page? Thank you!

**Comment by JounQin** [comment]
@ddbeck In https://developer.mozilla.org/en-US/docs/Glossary/Base64#solution_1_%E2%80%93_escaping_the_string_before_encoding_it There is a `b64EncodeUnicode` function, so I'd expect there should be a `b64DecodeUnicode` function too.

> Another possible solution without utilizing the now deprecated 'unescape' and 'escape' functions.

**Comment by ddbeck** [comment]
Ahh, I understand now: unlike the other example, there's no symmetrical decode function to go along with the encode. Thank you for the added detail!
