### ISSUE TITLE
Replace hand-written compat sections with BCD tables

### ISSUE THREAD

**Issue by foolip** [mdn/content#9972]
## What page(s) did you find the problem on?

These pages show browser compat without using BCD tables:
- [ ] https://developer.mozilla.org/en-US/docs/Games/Techniques/Controls_Gamepad_API#api_status_and_browser_support (prose)
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#value_of_keycode (prose and tables)
- [x] https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams#browser_support (prose)
  - https://github.com/mdn/content/pull/27215
- [x] https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API/Using_the_Web_Animations_API#browser_support (prose)
  - https://github.com/mdn/content/pull/23925
- [x] https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Cross-browser_audio_basics#browser_support (tables)
  - https://github.com/mdn/content/pull/32868
- [x] https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Live_streaming_web_audio_and_video#streaming_file_format_support (table)
  - https://github.com/mdn/content/pull/32868
- [x] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus (tables)
  - https://github.com/mdn/content/pull/21721
- [ ] https://developer.mozilla.org/en-US/docs/Web/Media/Audio_and_video_delivery/WebAudio_playbackRate_explained#browser_support (bullet points)
- [ ] https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers (tables)
- [ ] https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types (tables)
- [x] https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts (tables)
  - https://github.com/mdn/content/pull/18621

## What is the problem?

The information is presented in a different way to BCD tables used on most pages. For some of these pages there may be good reasons to maintain it by hand, but I suspect most could be replaced by linked BCD tables.

**Comment by hamishwillee** [comment]
A lot of this is media format support - in particular the image formats. We don't track that in BCD. Perhaps we should, though I suspect the "detail" of format support is why this has been done superficially in tables.

**Comment by wbamberg** [comment]
Yeah, for media support: when Sheppy was writing the media guide he asked about BCD supporting media support, but it doesn't really map onto BCD because BCD slices things into web platform features, and a browser supporting something like AV1 tends to cute across features.

https://discourse.mozilla.org/t/deciding-on-how-to-track-media-format-information/35531
