### ISSUE TITLE
Issue with "How do I start to design my website?": (short summary here please)

### ISSUE THREAD

**Issue by ijuuu930104** [mdn/content#9976]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Thinking_before_coding

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/common_questions/thinking_before_coding`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Thinking_before_coding
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/thinking_before_coding/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by hamishwillee** [comment]
Closing, as not enough information for us to act on.
