### ISSUE TITLE
Issue with "Navigator.platform": (short summary here please)

### ISSUE THREAD

**Issue by devcer** [mdn/content#9980]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform

#### What information was incorrect, unhelpful, or incomplete?
I think providing an example or link for an alternative to `navigator.platform` would be helpful

#### What did you expect to see?
I wish to see what I could use as an alternative for this API.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/navigator/platform`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/platform/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment]
Yes, generally useful :-). Done in #9999
