### ISSUE TITLE
Issue with "JavaScript typed arrays": ("js-ctypes" page is not found in MDN docs)

### ISSUE THREAD

**Issue by sureshUngarala** [mdn/content#9986]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays

#### What information was incorrect, unhelpful, or incomplete?

Section("Working with complex data structures") links another MDN page for **js-ctypes**. But, https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes shows "Page not found" page.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays#working_with_complex_data_structures

#### What did you expect to see?
List of C structures that can be used in JS

#### Did you test this? If so, how?
Tested it by manually opening the URL.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/typed_arrays`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/typed_arrays/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by abdelrazek-alaa** [comment]
> I'm not sure how up to date it is, but one option might be just to link to: https://wiki.mozilla.org/JSctypes
I'll work on this.
